### ISSUE TITLE
Stats: Custom Post Types with 'exclude_from_search' set to true do not show titles

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#100]
Post type definition:

``` php
register_post_type( 'plugin_event',
        array(
            'labels' => array(
                'name' => __( 'Events' ),
                'singular_name' => __( 'Event' )
            ),
        'public' => true,
        'has_archive' => true,
        'rewrite' => array('slug' => 'events'),
        'supports' => array('title', 'editor', 'custom-fields'),
        'exclude_from_search' => true,
        'show_in_admin_bar' => false,
        )
    );
}
```

When I view my Jetpack Stats page on my blog, any visits to a post of this type will show up with a title of "#xxxx (loading title)". 
I have verified that if I change `exclude_from_search` to false, then the title does show up.

This might be because of a bug upstream in WordPress, though.

**Comment by kraftbj** [comment]
@jeherve Just checking -- is this an issue after Sync went in?

**Comment by jeherve** [comment]
This was before. Closing now as it never came up again.
