### ISSUE TITLE
Jetpack 6.4.1 - Comments: can not log in social accounts

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#10005]
#### Steps to reproduce the issue

1. Install Jetpack 6.4.1 and activate the "Comments" module
2. Visit a post without logging in any social or WP.com accounts.
3. Click on a social icon links. 

#### What I expected

A pop-up window for logging in my social accounts.

#### What happened instead

Nothing happens. Checking in the browser console, there is a couple of JS errors: 

> ??/wp-content/js/jquery/jquery.autoresize.js,/wp-content/mu-plugins/highlander-comments/script.js?m=1521806916j:911 Blocked opening 'https://jetpack.wordpress.com/public.api/connect/?action=request&service=wordpress' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.

#### Notes 

* I tested and this issue does not happen on Jetpack 6.3.3. 

![image](https://user-images.githubusercontent.com/10045087/43873940-11e485d2-9bb3-11e8-9687-a56085448d64.png)

**Comment by htdat** [comment]
1334913-zen

**Comment by arunsathiya** [comment]
I am able to reproduce the same as well on a test site. 

<img width="1280" alt="screen shot 2018-08-09 at 09 17 29" src="https://user-images.githubusercontent.com/18581859/43876985-31f20ad2-9bb5-11e8-884c-8f3b89fc231a.png">

--- 

WordPress 4.9.8 and Jetpack 6.4.1 using Google Chrome Version 68.0.3440.84 (Official Build) (64-bit) on macOS 10.13.6
