### ISSUE TITLE
Wrong IP being detected

### ISSUE THREAD

**Issue by edward-of-clt** [Automattic/jetpack#10014]
#### Steps to reproduce the issue

1. deploy jetpack on docker swarm
1. place swarm behind load balancer on digital ocean
1. route traffic through traefik with x-forward on

#### What I expected

I expected the x-forward or x-real-ip to be used

#### What happened instead

Instead of the user's ip, I see the actual private IP of my servers. I've debugged and ensured that HTTP_X_FORWARDED_FOR is actually returning the correct IP, concatenated with the docker container IP. (i.e., 192.168.16.15, 10.0.0.4)

**Comment by abidhahmed** [comment]
Thanks for the report!

I'm wondering though, does it work properly for you when there's no load balancing involved and just the reverse proxy? (could be anything, doesn't have to be Traefik)

**Comment by edward-of-clt** [comment]
Yeah, so basically if the DigitalOcean load balancer is taken out of the equation, the IP address is correct.

**Comment by edward-of-clt** [comment]
Correct - But it picks the IP of the server itself.

**Comment by abidhahmed** [comment]
@edward-of-clt ~ We can change this detection algorithm to suit your headers. By doing this, if you were to switch hosts or change this setup to something else, you'd have to contact us. Does that work?

Feel free to let us know the site here or if you'd prefer to take this over to a ticket, please reach out via [this form](https://jetpack.com/contact-support/?rel=support) and we'll take care of this for you. Thanks!

**Comment by jeherve** [comment]
@edward-of-clt Did you have the chance to email us about this with your site URL, so we can look into it some more? 

Thank you!

**Comment by edward-of-clt** [comment]
Submitted the form just now. Thanks

**Comment by jeherve** [comment]
Closing as the issue should now be fixed.
