### ISSUE TITLE
Use standard Permalinks for Publicize

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#1003]
We choose the URL sent to the Publicize recipients in this order of preference:

1) WP.me shortlink
2) custom shortlink used by the site (bit.ly, for example)
3) default WordPress shortlink (example.com/?p=1234)

This was mainly because of Twitter's character limits, if I understood the rationale correctly.

Ever since the changes mentioned in https://github.com/Automattic/jetpack/issues/411, though, we don't worry about Twitter's character limits. So, I propose that instead of using the default WordPress permalink, we use whatever permalink that the post currently has. This has the advantage of being less "ugly" on services such as Facebook, which don't care about shortlinks in any case. 

Thoughts?

This was first brought up in 1907600-t.

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/jetpack-publish-doesnt-use-pretty-permalinks?replies=1&view=all

**Comment by jkudish** [comment]
A recent change on WordPress.com's side of Publicize has all tweets using the full permalink now.
