### ISSUE TITLE
Conflict with S5 image fader plugin

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#10030]
When Jetpack is activated the S5 widget can't be saved.

#### Steps to reproduce the issue

1. Install Jetpack and [S5 Image and Content Fader](https://wordpress.org/plugins/s5-image-and-content-fader/).
2. Add the S5 Image widget to a widget area, add a title and click Save.

#### What I expected

The widget should save. (It works when Jetpack is deactivated).

#### What happened instead

The widget won't save, the spinner just hangs.

500 error on `/wp-admin/admin-ajax.php`

1348047-zen

**Comment by jeherve** [comment]
Would it be possible to get more details about the 500 error, by enabling `WP_DEBUG` on the site and try to reproduce the issue again? 

Thanks!

**Comment by danjjohnson** [comment]
Nothing in debug.log, just seeing this in the console:

![image](https://user-images.githubusercontent.com/1990037/45093796-76c54400-b111-11e8-9d17-c0394c38c449.png)

**Comment by danjjohnson** [comment]
With script_debug enabled:

![image](https://user-images.githubusercontent.com/1990037/45093907-cc015580-b111-11e8-918c-de106b1e585b.png)

**Comment by jeherve** [comment]
Thanks! I was able to reproduce the issue, and it does not seem to be limited to a specific Jetpack widget: the problem remained even when removing Search, Simple Payments, and the Extra Sidebar Widgets module. It seems to happen as soon as Jetpack is connected to WordPress.com. Looking at the plugin, it seems it hasn't been updated in the last 3 years; it is going to be hard to work with the plugin author to try to find a solution to the problem.

Instead, I would recommend using the customizer to edit the widget. The title field appears to work there. The other buttons don't work there, but that seems to be an issue even when Jetpack is deactivated.
