### ISSUE TITLE
Setting Permalink to "Day and Name" makes Jetpack config fail

### ISSUE THREAD

**Issue by mhatta** [Automattic/jetpack#10044]
#### Steps to reproduce the issue

1. Set "Settings" -> "Permalink" -> "Common Settings" to "Day and Name"
2. Set "Jetpack" -> "Settings" -> Try to change some configuration

#### What I expected

Configuration should be updated without errors.

#### What happened instead

"Error updating settings. JSON.parse: unexpected character at line 1 column 1 of the JSON data" shows up and doesn't update the setting.  Setting Permalink to "Plain" fixes this issue.

**Comment by brbrr** [comment]
Hi @mhatta,
Thanks for your report. I tried to reproduce it on a clean site with Jetpack from `master` branch with no success. What Jetpack version are you using? Maybe there some other plugins interfere with Jetpack?

**Comment by mhatta** [comment]
Hi @brbrr,

Jetpack is 6.4.2.  Wordpress is 4.9.8.  I disabled all plugins except Jetpack, still could reproduce this.  What else can I check?  (BTW, it was working until recently)

**Comment by mhatta** [comment]
Hi @brbrr, I actually deleted all plugins (including Jetpack) and reinstalled Jetpack.  To no avail, still got error.

**Comment by mhatta** [comment]
@brbrr Well, I guess that's what I did as 1.

**Comment by jeherve** [comment]
Could you try the following:

<ol>
	<li>Open the dashboard page.</li>
	<li><a href="https://codex.wordpress.org/Using_Your_Browser_to_Diagnose_JavaScript_Errors#Step_3:_Diagnosis">Open your browser console</a></li>
	<li>Click on the Network tab</li>
	<li>Refresh the page.</li>
	<li>Try to change some of the settings.</li>
	<li>If you see any lines in red inside the browser console, click on them. A new panel should appear on the right.</li>
	<li>Click on the "Response" tab in that new panel.</li>
	<li>Copy the message displayed there.</li>
	<li>Paste it here.</li>
	<li>If no red lines appeared in the browser console, click on the "Console" tab of the browser console.</li>
	<li>Copy any errors displayed there, and paste them here.</li>
</ol>

Thank you!

**Comment by mhatta** [comment]
Thanks a lot for replies.

I updated Jetpack to 6.4.5 and still get the error.  I'm using the latest Firefox Quantum on Windows 10 (the server is FreeBSD 10.4, btw).

Funny thing is, I also updated PHP to 7.2.8, and the error message became different.  Now it says

`Error updating settings. 読み取りに失敗しました。`  ("Failed to read" in Japanese).

Note that I set the Site Language to English for reporting this issue, but a part of the error message is still translated into Japanese.  Why?

I also installed the Health Check plugin and it reports my database is too old (I'm still using MySQL 5.0.95) and utf8mb4 support is off.  Does this affect anything?  I will update the DB this weekend anyway.

**Comment by jeherve** [comment]
@mhatta I don't believe the problem is linked to your site's permalink structure. It would seem that the WordPress REST API is not available on your site:
http://www.mhatta.org/wp/wp-json/

That API is part of WordPress itself, and is used by plugins like Jetpack to make changes to your site's settings. 

Do you use a plugin that may block access to that API? If you don't, could you check your site's `.htaccess` file and make sure you have not blocked access to the API there? 
If none of this helps, I would recommend that you contact your hosting provider and make sure they do not have any security rules in place that may block access to that API.

Once you can access the API, everything should start working.

Let us know how it goes.

**Comment by mhatta** [comment]
@jeherve You are right, my server provider blocked access to wp-json by default from the outside IPs of my country.  So in .htaacess, I specifically allow (I guess) Automattic server IPs.

```
allow from 122.248.245.244
allow from 54.217.201.243
allow from 54.232.116.4
allow from 192.0.80.0/20
allow from 192.0.96.0/20
allow from 192.0.112.0/20
```

I'm not sure which one is vital, but anyway it works now.  Thanks.
