### ISSUE TITLE
Contact Form: Erasing feedback using Erase Personal Data does not remove all feedback

### ISSUE THREAD

**Issue by abidhahmed** [Automattic/jetpack#10076]
Attempting to erase all feedback using `Erase Personal Data` on Jetpack Beta does not remove any feedback.

#### Steps to reproduce the issue

1. Create a contact form on your site
2. Manually edit `modules/contact-form/grunion-contact-form.php` on line 846 to read `$per_page = 1;`
Test:
3. Submit 3 feedbacks through the form, all with the same email address.
4. Go to `wp-admin/ -> Tools -> Erase Personal Data`.
5. Enter the email address you used, click `Send Request`.
6. Find that Pending Request in the table on that page, hover over it and click `Force Erase Personal Data`.
7. See the AJAX requests go, and the success message `All of the personal data found for this user was erased.` appear.
8. Go to `wp-admin/ -> Feedback`
9. Expect to see no feedbacks left with the email you used before.

#### What I expected

All 3 feedbacks to be removed.

#### What happened instead

All 3 feedbacks continue to exist.

**Comment by oskosk** [comment]
@mdawaffe I couldn't reproduce this report coming from the CFT for jetpack 6.5. @abidh couldn't either according to his comment in the CFT.

**Comment by coder-karen** [comment]
An update on this – I tried with a different email address and it worked. I tried again with the original and it didn’t. That was a yahoo email address.

**Comment by mdawaffe** [comment]
Interesting! I followed up on the internal CFT post.
