### ISSUE TITLE
WordAds: Getting duplicate ads

### ISSUE THREAD

**Issue by abidhahmed** [Automattic/jetpack#10077]
After turning on ads with default settings on Jetpack Beta, there are duplicate ads being displayed.

#### What I expected

Different ads or just a single ad.

#### What happened instead

Multiple duplicated ads.

<img width="200" alt="duplicate-ads" src="https://user-images.githubusercontent.com/7570415/44842243-f317dd00-ac62-11e8-90ed-ac2f1199613c.png">

**Comment by rclations** [comment]
This is correct - there are 2 ad slots there, and if the same advertisers purchases both of them, it's possible to see the same ad twice.
