### ISSUE TITLE
VideoPress: AT Sites on Two-Year Business Plan are asked to Upgrade to Activate VideoPress

### ISSUE THREAD

**Issue by druesome** [Automattic/jetpack#10085]
Atomic sites on a two-year Business Plan are asked to upgrade to be able to host videos on the VideoPress service.  This looks similar to #9949 where the Simple Payments Button wasn't working on the same plan.

#### Steps to reproduce the issue

1. Visit the wp-admin panel of an AT site with a one-year Business Plan
2. Go to Jetpack > Settings
3. Under Media > Video, you should be able to see a tab with the text `Enable high-speed, ad-free video player` to activate or deactivate VideoPress.
4. Replace the site's Business Plan to a two-year one in Store Admin
5. Go back to Jetpack > Settings
6. Under Media, VideoPress seems to be unavailable, and the tab to turn it on or off is missing.  Instead, there is a blue "Upgrade" button next to the text `Host fast, high-quality, ad-free video.`

<img src="http://cld.wthms.co/2HaVCg+" width="600" />

#### What I expected

I expected to see the toggle button to activate VideoPress after switching to a two-year Business plan.

#### What happened instead

I see this option missing, and I'm being asked to click on a blue button to upgrade.  It is worth noting that I'm still able to upload videos normally to VideoPress, but this can be really confusing to users who either want to use VideoPress or not.

**Comment by Robertght** [comment]
Ref ticket: #1383493-zen
