### ISSUE TITLE
General: Filter module description

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#1008]
Currently, we provide a filter for the module short descriptions, `jetpack_short_module_description`, but the full module text is added via hooks (in testing, I couldn't determine how to unhook it).

Would it make sense to add a set of `jetpack_long_module_description_*` filters that are run through on each module?

Requested in http://wordpress.org/support/topic/hook-after-module-infophp-is-loaded?replies=8#post-5899272

**Comment by jeherve** [comment]
Fixed in #1919
