### ISSUE TITLE
MailChimp Widget: Can't Convert Updated Popup Code

### ISSUE THREAD

**Issue by druesome** [Automattic/jetpack#10104]
Related to #7945, Mailchimp changed their popup Javascript code again, and this causes the Mailchimp widget to not convert it correctly into the proper shortcode.

Previously, it looked like:

`<script type="text/javascript" src="//downloads.mailchimp.com/js/signup-forms/popup/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script><script type="text/javascript">require(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us8.list-manage.com","uuid":"be06c2a596db91bfe4099fde8","lid":"b47399ad05"}) })</script>`

Now, it looks like:

`<script type="text/javascript" src="//downloads.mailchimp.com/js/signup-forms/popup/unique-methods/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script><script type="text/javascript">window.dojoRequire(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us8.list-manage.com","uuid":"be06c2a596db91bfe4099fde8","lid":"08cf5fa008","uniqueMethods":true}) })</script>`

Saving the the above code doesn't convert into the shortcode, or result in the popup showing up on the site.

Note that the `src` value has changed with the additional `/unique-methods/` subfolder, `require` was changed to `window.dojoRequire` and `uniqueMethods":true` was added at the end.  A workaround back then was to simply change the src URL, but this time it doesn't work.  Manually creating the shortcode with the `baseURL`, `uuid` and `lid` values still works, though.

An update on this widget would be fantastic.  Thank you in advance!

**Comment by BandonRandon** [comment]
Thanks for your work on this @jeherve we also have a report of this on WP.com so commenting to make sure this fix gets backported :) 
https://en.forums.wordpress.com/topic/mailchimp-html-snippet-for-subscribe-popup-is-being-stripped

**Comment by tanjoymor** [comment]
I dealt with a ticket regarding this issue and wanted to share some information that came about from my interaction.

The site is a WordPress.com on a Premium Plan with a custom domain.

The before code looked like:

```
<script type="text/javascript" src="//downloads.mailchimp.com/js/signup-forms/popup/unique-methods/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script><script type="text/javascript">window.dojoRequire(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us16.list-manage.com","uuid":"7fd6eb5d6e7da5b3c14b87112","lid":"cbea7a4be4","uniqueMethods":true}) })</script>
```

The after code looked like:

```
<a href="//downloads.mailchimp.com/js/signup-forms/popup/unique-methods/embed.js">//downloads.mailchimp.com/js/signup-forms/popup/unique-methods/embed.js</a>window.dojoRequire(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us16.list-manage.com","uuid":"7fd6eb5d6e7da5b3c14b87112","lid":"cbea7a4be4","uniqueMethods":true}) })
```

Based on the suggested work-around here:
https://heinvestigations.wordpress.com/2018/09/03/adding-mailchimp-pop-up-code-to-an-at-site/#comment-237

```
[mailchimp_subscriber_popup baseUrl='$baseURL' uuid='$uuid' lid='$lid' usePlainJson='true' isDebug='false']
```

It was tested on a different WordPress.com site and worked as:

```
[mailchimp_subscriber_popup baseUrl='mc.us19.list-manage.com' uuid='afe3a740a3564021d20926a86' lid='baf322b918' usePlainJson='true' isDebug='false']
```

However, on the site in my ticket, this didn't work:

```
[mailchimp_subscriber_popup baseUrl='mc.us18.list-manage.com' uuid='dfcfbdf87405fa8f23dd1ec96' lid='db0bec8e13' usePlainJson='true' isDebug='false']
```

Then the user replaced the single quotes with double quotes and it has worked like this:

```
[mailchimp_subscriber_popup baseUrl="mc.us18.list-manage.com" uuid="dfcfbdf87405fa8f23dd1ec96" lid="db0bec8e13" usePlainJson="true" isDebug="false"]
```

Wasn't sure if this could be useful, so wanted to share. :-)

**Comment by edwinho89** [comment]
Reported on #1432034-zen as well.
