### ISSUE TITLE
Jetpack caching woocommerce order total and conflicts with YITH Gift Card Plugin

### ISSUE THREAD

**Issue by johnskillerprotein** [Automattic/jetpack#10110]
#### Steps to reproduce the issue

We have a YITH plugin called YITH WooCommerce Gift Cards Premium.  it's used to generate gift cards.  With Jetpack enabled, when a customer attempts to use a gift card during checkout, the order total does not reflect the use of the gift card and still requires full payment, even though the gift card shows as being applied to the order.

With Jetpack disabled, the checkout process works perfectly and the order total reflects the usage of the gift card.

1.  Shop and add items to basket
2. At checkout, enter gift card code
3. Proceed to Checkout

#### What I expected

When a gift card code is being applied to the order, I expect the order total to be reduced by the value of the gift card.  For example, an order for $300 with a gift card for $250 should mean the order total should be $50.

#### What happened instead
Wordpress with Jetpack enabled is showing the gift card for $250 is being applied, however the order total remains at $300 and requires full payment.

With Jetpack disabled, the process is fine.  The problem only occurs with Jetpack enabled.

**Comment by jeherve** [comment]
Could you check for Javascript errors on the checkout page, as explained here:
http://codex.wordpress.org/Using_Your_Browser_to_Diagnose_JavaScript_Errors

Could you also confirm that you use the most recent version of Jetpack on your site?

Could you also let us know if you use any specific Jetpack features related to WooCommerce, like [the Google Analytics feature](https://jetpack.com/support/google-analytics/) and its eCommerce tracking?

Let us know what you find!

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
