### ISSUE TITLE
Simple Payments: Make the product name consistent

### ISSUE THREAD

**Issue by naokomc** [Automattic/jetpack#10114]
During our i18n test on WordPress.com logged-out homepage, some of Team Global members found that the word "Simple Payments" is translated inconsistently.

As I was looking into a way to re-send the strings that include this product name, I also found that some variations of it:

- Simple Payments (correct)
- Simple Payment (singular)
- simple payments (lowercase)
- simple payment (lowercase singular)

From the translation perspective, it would be the best if they are always spelled "Simple Payments" so that the phrase matches existing glossaries.

Inconsistent strings within the plugin:
https://translate.wordpress.org/projects/wp-plugins/jetpack/dev/ja/default?filters%5Bterm%5D=simple+payment+&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

All "simple payment" matches in WordPress.com (low priority "↓" ones don't need to be fixed):
https://translate.wordpress.com/projects/wpcom/ja/default?filters%5Bterm%5D=Simple+Payment&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

**Comment by codestor4** [comment]
Submitted a PR (my first one in this repo). That should fix the **ones that need to be fixed**.
