### ISSUE TITLE
WooCommerce Analytics: changes to the module

### ISSUE THREAD

**Issue by iannacone** [Automattic/jetpack#10119]
https://github.com/Automattic/jetpack/blob/2d15c2ee920c2760aba82d4a335dcea63419fc36/modules/woocommerce-analytics/classes/wp-woocommerce-analytics-universal.php#L69

could this function also be `static`, please?

**Comment by jeherve** [comment]
Could you tell us more about what you are trying to achieve, or the problems you are having?

**Comment by iannacone** [comment]
i was trying to remove the relative action.
i already found the solution and removed the action.
but it was really useful to have it as `static` for better and easly manage the hook(s) also externally.

**Comment by jeherve** [comment]
Thanks for the extra details. Do not hesitate to open a Pull Request if you feel that change would be useful to other Jetpack site owners.
https://github.com/Automattic/jetpack/blob/master/.github/CONTRIBUTING.md#write-and-submit-a-patch
