### ISSUE TITLE
Jetpack auto sharing problem

### ISSUE THREAD

**Issue by mohiuddin3824** [Automattic/jetpack#10115]
#### Steps to reproduce the issue

1.When I post new article it share to social media automatically! i it working good but i see it share a big link of my post. I want to share short link not big. please help me
2.
3.

**Comment by jeherve** [comment]
Could you contact us via [this contact form](https://jetpack.com/contact-support/?rel=support) and give us more details about your post as well as some examples, so we can investigate and try to understand what is happening?

Thank you.
