### ISSUE TITLE
WooCommerce Analytics: not referring to the static class property

### ISSUE THREAD

**Issue by iannacone** [Automattic/jetpack#10117]
https://github.com/Automattic/jetpack/blob/2d15c2ee920c2760aba82d4a335dcea63419fc36/modules/woocommerce-analytics/wp-woocommerce-analytics.php#L76

`self::$analytics = new Jetpack_WooCommerce_Analytics_Universal();`

**Comment by jeherve** [comment]
Could you tell us more about what you are trying to achieve, or the problems you are having / errors you are seeing?

**Comment by iannacone** [comment]
no problem or error. just the fact that the class has a `private static $analytics` at the top which is never used. i supposed that the `$analytics` var at the line 76 refers exactly to that `static` previously declared.
