### ISSUE TITLE
Bug: Tonesque Comment Error

### ISSUE THREAD

**Issue by Kalus** [Automattic/jetpack#10124]
#### Steps to reproduce the issue
1. In jetpack/_inc/lib/tonesque.php, line 89.
2. Tonesque has a comment saying it returns returns HSL. Should probably read as HSV?

#### What I expected
`* @param optional $type (hex, rgb, hsv)`

#### What happened instead
`* @param optional $type (hex, rgb, hsl)`

**Comment by jeherve** [comment]
Yes, you're correct, that's a typo. We'll fix it in #10126
