### ISSUE TITLE
Google Translate Widget - Does Not Include Site Default Language

### ISSUE THREAD

**Issue by scosgro** [Automattic/jetpack#10131]
#### Steps to reproduce the issue

1. Add the Google Translate Widget to your site
2. Try to translate a page to the site's default language
3. Site's default language is not an option

#### What I expected

1. If a user's site default is English, but a guest post is written in French, that the widget would be able to translate that to English

#### What happened instead

1. English is not available as a language to translate to, since it's the site's default language.

User's site is primarily in English, and they use the widget to have translation options available. A few of their posts are written in French, but the translate tool cannot translate the posts into English, since the widget does not display the site's default language as an option.

**Comment by jeherve** [comment]
I am afraid that is not something we can easily change; the Google translate widget requires a default language (that will be hidden from the Google Translate UI), and the only information we have in Jetpack is the site's language. Individual posts' languages are not stored anywhere in WordPress.

**Comment by KokkieH** [comment]
Just noting this came up today in the [dotcom forums](https://en.forums.wordpress.com/topic/language-missing-in-jetpack-google-translate-widget)
