### ISSUE TITLE
Font Styles Not Able To Apply to Text with Jetpack Proofreading and Gutenberg

### ISSUE THREAD

**Issue by reginabally** [Automattic/jetpack#10138]
This issue was originally reported on Gutenberg: https://github.com/WordPress/gutenberg/issues/9658

#### Steps to reproduce the issue

1. Turn on Jetpack Proofreading and select all proofread options.
2. Type or copy and paste as plain text of the following paragraph.
> Enter your email address (optional) and the domain name that you want to install SSL certificate. To simplify things, I would suggest generating a wildcard certificate that can be installed for your domain as well as its sub-domains. In my example, I entered reginafoo.blog, *.reginafoo.blog in the Domains field.
3. Highlight the text "reginafoo.blog, *.reginafoo.blog" and apply Bold and Italic font styles to the selected text.

#### What I expected
Font styles should be applied to the highlighted texts.

#### What happened instead
Font styles only applied to "*.reginafoo.blog" but not the entire selected texts.

#### Screenshot

![image](https://user-images.githubusercontent.com/40906847/45522815-05178500-b7f8-11e8-8adb-1a50e9f811bd.png)

#### HTML Codes

```
<!-- wp:paragraph -->
<p>Enter your email address (optional) and the domain name that you want to install SSL certificate. To simplify things, I would suggest generating a wildcard certificate that can be installed for your domain as well as its sub-domains. In my example, I entered <g class="gr_ gr_6 gr-alert gr_spell gr_inline_cards gr_run_anim ContextualSpelling ins-del multiReplace" id="6" data-gr-id="6">reginafoo</g><g class="gr_ gr_9 gr-alert gr_gramm gr_inline_cards gr_run_anim Style replaceWithoutSep" id="9" data-gr-id="9">.blog</g><em><strong>, *.reginafoo.blog</strong></em> in the Domains field.</p>
<!-- /wp:paragraph -->
```

#### Other Information
My device: Laptop
OS: Windows 7 Enterprise SP1
Browser: Google Chrome
Version: 68.0.3440.75 (Official Build) (64-bit)
WordPress: 4.9.8 Multisite
Gutenberg: 3.7.0 (when the issue originally spotted) and 3.8.0 (re-tested when I file this issue)
PHP: 7.2

**Comment by jeherve** [comment]
I can't seem to be able to reproduce the issue on my end, in Chrome as well. Here is how it looks in the Gutenberg editor:

<img width="789" alt="screenshot 2018-09-14 at 11 45 23" src="https://user-images.githubusercontent.com/426388/45543035-d909fd00-b813-11e8-9f8e-78269f8285c9.png">
<img width="732" alt="screenshot 2018-09-14 at 11 45 16" src="https://user-images.githubusercontent.com/426388/45543036-d9a29380-b813-11e8-8a7a-090e333eebb6.png">

And on the frontend of my site:

<img width="736" alt="screenshot 2018-09-14 at 11 45 45" src="https://user-images.githubusercontent.com/426388/45543051-e3c49200-b813-11e8-92f8-e5d6d126807f.png">

My HTML code is different from yours, though:
`In my example, I entered <em><strong>reginafoo.blog, *.reginafoo.blog</strong></em> in the Domains field.</p>`

I tried making my browser smaller, as you had mentioned in the original issue, and it seems to work well there as well:

<img width="635" alt="screenshot 2018-09-14 at 11 49 32" src="https://user-images.githubusercontent.com/426388/45543240-5cc3e980-b814-11e8-8464-5f6c6717bc38.png">

Do you happen to use the Grammarly extension in your browser? I believe that is what may be adding those HTML tags to your post content. If you do use that extension, could you try to deactivate it and see if it helps? If it does, it may be worth contacting Grammarly directly about it, as this may be happening in other editors as well.

Let me know how it goes.

**Comment by reginabally** [comment]
Hi @jeherve,

You're right! I have Grammarly extension on my Chrome. When I tried on IE it doesn't seem to have the problem. Thanks for pointing that out. :)

I'll go ahead and close this issue.
