### ISSUE TITLE
This is not a bug, but I want to know the answer!

### ISSUE THREAD

**Issue by shangdev** [Automattic/jetpack#10149]
I want to discuss how the module is loaded. As described in the subfile headers meta under module, We can set Auto Activate to Yes or No.

When I set Yes, 
He can be loaded automatically. I found this function: activate_default_modules in class.jetpack.php.

But When I set No, 
I didn't find a function to go and load it in class.jetpack.php. This is my confusion, that is, I don't understand how Auto Activate: No module is loaded.

Although this is not a bug, I just want to know how the module works. Can you help me with this?

**Comment by shangdev** [comment]
After my exploration, I found load_modules.

Please close this issue, sorry to bother!

Great plugin!

**Comment by oskosk** [comment]
Glad you could find the answer @shangdev !
