### ISSUE TITLE
Site verification: Google verification automatically triggered on new sites

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#10141]
Coming back to #10041, I believe something is wrong with the current approach and behaviour.

#### Steps to reproduce the issue

1. Start a brand new Jetpack site using a version of Jetpack that includes the new Verification process introduced in #10041. Here is an example: jurassic.ninja/create?jetpack-beta&branch=add/improve-search-upgrade-message&shortlived&wp-debug-log&gutenberg
2. Connect your site to WordPress.com
3. Go to Jetpack > Settings > Traffic. 
4. Notice a notification that settings are being updated.
5. Scroll down; the site is shown as verified with Google: 
<img width="505" alt="screenshot 2018-09-14 at 12 14 09" src="https://user-images.githubusercontent.com/426388/45544472-b37ef280-b817-11e8-8c2c-c152edea0209.png">

I can indeed see the tag on the frontend.
I can't, however, see the site on my own Google account.

- Why was the verification started without me explicitly starting the process?
- What Google account is the site linked to?

cc @Tug and @cbauerman; could you take a look at this?

Thank you!

**Comment by Tug** [comment]
Indeed we assumed that if you already have a token for google site verification it means you already clicked on the "Connect with Google" button but we didn't account for multisite... It's a quick fix as it only impacts the jetpack UI.

However you should be able to see your site verified in the Google Search console or webmaster tool: https://www.google.com/webmasters/verification/home?hl=en&authuser=2
I did reproduce the problem twice and was able to see both site added there.

**Comment by jeherve** [comment]
> you should be able to see your site verified in the Google Search console or webmaster tool: google.com/webmasters/verification/home?hl=en&authuser=2

I see it there indeed. For some reason I don't see it here:
https://www.google.com/webmasters/tools/home?hl=en&authuser=2

That's what threw me off.
