### ISSUE TITLE
Update reCAPTCHA constants to match Google's Verbage

### ISSUE THREAD

**Issue by BrookeDot** [Automattic/jetpack#10159]
Jetpack allows reCAPTCHA to be defined on Post by Email and possibly on Contact Form soon ( https://github.com/Automattic/jetpack/pull/9389) 

The constants to activate this feature are currently set to:
```
define( 'RECAPTCHA_PUBLIC_KEY', 'XXXXXXX' );
define( 'RECAPTCHA_PRIVATE_KEY', 'XXXXXXX' );
```

https://github.com/Automattic/jetpack/blob/f8078c2cd12ac508334da2fb08e37a92cf283c14/modules/sharedaddy/sharedaddy.php#L261

When setting up the keys Google calls these the **Site key** and **Secret key**. 
![screenshot_17-09-2018-21 06 47](https://user-images.githubusercontent.com/150348/45663894-bac72a00-babd-11e8-8c54-dbb28bd17b2e.png)

By updating both the constants and [our documentation](https://jetpack.com/2013/04/15/recaptcha-email-sharing-button/) we can make setting up this feature clearer.

I propose:
```
define( 'RECAPTCHA_SITE_KEY', 'XXXXXXX' );
define( 'RECAPTCHA_SECRET_KEY', 'XXXXXXX' );
```

**Comment by kraftbj** [comment]
Note for implementation we would need to support both gracefully.

**Comment by BrookeDot** [comment]
> Note for implementation we would need to support both gracefully.

Agreed, I was actually going to patch this but then realized we'd want a fallback. I was thinking we could perhaps just do something like define `RECAPTCHA_PUBLIC_KEY` as `RECAPTCHA_SITE_KEY` but there's likely a more elegant solution then something like:

```
if ( ( ( defined ( RECAPTCHA_PUBLIC_KEY ) ) && ( ! (defined ( RECAPTCHA_SITE_KEY ) ) ) ) {
define( 'RECAPTCHA_SITE_KEY', RECAPTCHA_PUBLIC_KEY );
}
```

**Comment by kraftbj** [comment]
There might be something more elegant, but that works. :) You could clean it up a bit with:

if( defined( RECAPTCHA_PUBLIC_KEY ) && ! defined ( RECAPTCHA_SITE_KEY ) ) {
...
}

**Comment by jlapitan** [comment]
just adding some source not sure if fully related, there is new version of recaptcha(beta)

https://developers.google.com/recaptcha/docs/v3
