### ISSUE TITLE
Publicize: publicizing to Facebook fails for posts with images using relative src paths

### ISSUE THREAD

**Issue by designsimply** [Automattic/jetpack#1015]
Steps to reproduce:
1. Open a Jetpack blog
2. Go to Settings > Sharing
3. Connect Facebook and Twitter to test accounts
4. Go to Posts > Add New
5. Insert an image using the ‘Add Media’ button
6. Click the Text tab for the editor and adjust the image so the src points to a relative path
7. Make sure Facebook and Twitter show up in a Publicize line at the bottom of the Publish meta box
8. Click ‘Publish’
- Result: the post is publicized to Twitter but does not show up on Facebook

Additional testing steps:
1. Repeat the same steps as above, except use a full image src ref instead of a relative one
- Result: the post is publicized to both Twitter and Facebook

Reported in:
- http://wordpress.org/support/topic/publicize-is-not-posting-on-facebook?replies=10#post-3608553

I think it’s pretty common to use full URL image src references, and it appears that’s what Facebook requires—so I’m not sure whether this is a problem on the Jetpack side or the Facebook side and I will leave it up to the Jetpack developers to make a final decision on if/how to move forward.

**Comment by teohhanhui** [comment]
So why was #418 fixed while this was a wontfix?

**Comment by designsimply** [comment]
It looks like the answer is given in the previous comment, which said that core is mean to work from absolute paths. You can also see in step 6 above that you have to manually change the image path from the default get it to break. If you insert an image the way most people do, then it should work without any trouble. Because of that, it probably affects fewer people.

That said, things change and nothing is set in stone. If someone were to make a good argument or enough people were having trouble or someone from the community were to submit a patch to make a change, a decision like that could always be reconsidered in the future.

**Comment by teohhanhui** [comment]
@designsimply I'm not questioning the above reasoning (though I may personally like to be able to use root relative paths for everything). What piqued my interest is the apparent inconsistency between this issue and the other as I've pointed out (Perhaps I'm mistaken? Do point out if that's the case...)

**Comment by designsimply** [comment]
I'm not sure. :) It might just be timing or that one change made more sense than the other. Also, one thing looks like a user-facing setting while the other is something in a function (I think), so that could be another reason for the difference.
