### ISSUE TITLE
Publicize: Remove Path Connection & Sharing

### ISSUE THREAD

**Issue by timnolte** [Automattic/jetpack#10155]
#### Steps to reproduce the issue

1. Path has officially announced that it will be shutting down in October.

#### What should it do
Path should no longer be an option.

**Comment by kraftbj** [comment]
https://path.com/about for the official notice. While there is a short period (until Oct 18) where the service seems to be functional after our release, I say we remove the UI immediately and can remove the backend pieces when it makes sense.

**Comment by kraftbj** [comment]
Re-opening until there's been a handoff of the backend removal to another group.

**Comment by lancewillett** [comment]
REST API change deployed now.

**Comment by jeherve** [comment]
Closing this issue then. 👍

**Comment by kraftbj** [comment]
@lancewillett Are you aware where we're tracking when we actually remove the stale info from the db post-closure?

**Comment by lancewillett** [comment]
@kraftbj Nope, nothing yet. Probably a Phab diff?
