### ISSUE TITLE
PHPCS: Fix all automatically fixable errors

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#10168]
This is a master issue to refer back to when running PRs on individual modules/sections of code. We're now at WPCS 1.1.0 and moving forward to matching it through phpcbf-eligible fixes.

**Comment by jeherve** [comment]
List of the matching Fusion Diffs:

[ ] D18509-code

**Comment by kraftbj** [comment]
We are having to abandon a number of fusion diffs that are picking up unsynced changes from years ago in some cases. Keeping a list to come back to.

**Comment by kraftbj** [comment]
Going to close this as we're still working through them, but there isn't a usefulness IMO to tracking them (and we haven't been).
