### ISSUE TITLE
Network Deactivation of Plugin Causes Broken Connections for Sub-sites

### ISSUE THREAD

**Issue by doctored** [Automattic/jetpack#1016]
Have plugin network activated letting site owners make their own wordpress.com connections. If i need to network deactivate plugin (even in a staging environment which seems to share the same live connection) this causes an issue where the individual sites are still connected but only in a partially functional way. For instance, wp.com will continue to record stats data but the site owner or super admin cannot visit the stats page (returns broken token or something like that (afraid to replicate this)). This forces the network admin to have to reach out to the individual site owners to reset their connections often with a lot of hand holding because of the fact that the screen indicates that it is connected even though the connection is partially broken.

**Comment by jeherve** [comment]
Closing, as I can't seem to reproduce the issue anymore. Network deactivating the plugin seems to remove all aspects of the plugin everywhere.
