### ISSUE TITLE
No rewind button for wheelingforgod.com on Activity log

### ISSUE THREAD

**Issue by sjaved87** [Automattic/jetpack#10177]
This user migrated from Jetpack professional to WordPress.com Business plan, manually.  The sit JP was connected with the old Jetpack blog instead of Business plan site. 

I have fixed that by connecting with the correct blog. But still no rewind button.

Rewind debug says everything is correct.

First, it looks like we missed something here to properly connect with VaultPress? I posted but did not get a response that is why I am reporting here as well: p9F6qB-1tk-p2

Second, it looks like they had some backup in the past for the blog ID: 140502774 (Jetpack site). 
Can we migrate that record over to this site?

#### Steps to reproduce the issue

1. Make some edit or install/activate the plugin on the site.
2. Check the activity log from My Sites -> Activity page.

#### What I expected
It should display the log record along with the rewind button.

#### What happened instead
The record is there but no rewind button.

**Comment by jeherve** [comment]
Closing this issue as this is most likely not the best place to report that problem. Will DM you for more info.
