### ISSUE TITLE
Override carousel CSS via enqueue_style?

### ISSUE THREAD

**Issue by sterndata** [Automattic/jetpack#10192]
’m trying to override some of the CSS for the jetpack tiled gallery and carousel.

I added
`
wp_enqueue_style( 'my-jetpack', get_stylesheet_directory_uri() . '/my-jetpack.css', 'jetpack-carousel' );
`

Note: I’m hooking this to ‘wp_enqueue_scripts’.

Note2: I also tried a dependency on ’tiled-gallery’.

What’s the trick?

#### What I expected
I expected my  CSS to load after jetpack-carousel

#### What happened instead
But the dependency doesn’t seem to work as it loads before jetpack-carousel.

**Comment by jeherve** [comment]
Since Jetpack's Carousel is concatenated into a big `jetpack.css` file, this will be a bit more complicated. Here is a quick guide to help you disable concatenation, and then dequeue the original carousel stylesheet.

https://css-tricks.com/snippets/wordpress/removing-jetpack-css/
