### ISSUE TITLE
Site not verified when I visit the search console link

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#10213]
#### Steps to reproduce the issue

I unearthed this about using Jurassic.ninja. I haven't yet confirmed on other sites.

1. Connect a jetpack site and verify with Google with one click
2. Click the link to the search console below the input field

#### What I expected

To see my site in search console

#### What happened instead

Site was not found

<img width="1680" alt="site not verified" src="https://user-images.githubusercontent.com/51896/46032475-95837e80-c0b0-11e8-893a-4cc8c7c1cf45.png">

**Comment by jeherve** [comment]
I can't seem to reproduce on my end:

![screen recording 2018-09-25 at 08 39 pm](https://user-images.githubusercontent.com/426388/46035409-41ee5080-c103-11e8-9eb6-027094c2b063.gif)

Do you happen to be logged in with different Google accounts in that browser?

**Comment by gravityrail** [comment]
Closing for now as I think this was caused by our token reuse issue, now fixed.
