### ISSUE TITLE
Manual verification appears to have no effect

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#10216]
#### Steps to reproduce the issue

1. Connect a jetpack site and go to traffic settings, Site verification tools
2. Click "Manually verify with Google"
3. Click save

#### What I expected

UI should reflect the fact that I am verifying manually, and tell me what I need to do next

#### What happened instead

UI reverts to original state With Option to verify manually or automatically

Video: https://cloudup.com/ce9IhVol0GH

**Comment by gravityrail** [comment]
@jeffgolenski do you have thoughts on how this should work?

**Comment by gravityrail** [comment]
it occurred to me that rather than have an edit button, it might make sense to have an X like we do on the publicise connections. clicking this X would remove your keyring credentials from WordPress.com, which would mean that you either need to connect again or manually verify

**Comment by jeherve** [comment]
What seems worse is that even if I manually go through the steps and verify my site manually on my own, even though my site will end up being verified the Jetpack interface will not reflect that and will remain like this:

<img width="847" alt="screenshot 2018-09-27 at 21 14 28" src="https://user-images.githubusercontent.com/426388/46169195-aa236a80-c29a-11e8-9f86-bb79477dffa7.png">

To reproduce:

1. Create a new site.
2. Click on "Manually verify with Google"
3. Go to https://www.google.com/webmasters/tools/home?hl=en
4. Click on Add Property.
5. Add your site URL.
6. Select alternate methods, copy the meta tag.
7. Back to your dashboard, paste it in the field.
8. Save your changes.
9. Back to the Search console, click to validate that you added the tag; Google verifies your site and confirms it's been verified.
10. Back to your dashboard, refresh the page and Jetpack does not seem to know that your site is verified.

**Comment by Tug** [comment]
> Back to your dashboard, refresh the page and Jetpack does not seem to know that your site is verified.

Sadly it cannot know. Google doesn't expose this information publicly, you need a connected account to access their API.

I agree with Dan, we could give more direction

**Comment by jeherve** [comment]
Could we store the fact that one clicked to manually verify, or check the contents of the field and when a site is not connected with Google but the field is filled in, we show the field without the auto-verify options?

**Comment by gravityrail** [comment]
If the field has a value, but the server has no tokens, we should show the "manual mode" UI with a warning: "You have chosen to manually verify your site with Google. Click _here_ to view your site in Search Console. If it's not available, follow _these_ instructions to verify manually", plus a button to clear the value and return to the "chooser" UI, auto vs manual.

No additional state storage necessary.

cc @Tug  @jeherve

**Comment by gravityrail** [comment]
This has been pretty much addressed by https://github.com/Automattic/jetpack/pull/10263
