### ISSUE TITLE
General: break apart test_absolutize_css_urls_properly_handles_use_cases into proper tests

### ISSUE THREAD

**Issue by blobaugh** [Automattic/jetpack#1022]
Currently the test test_absolutize_css_urls_properly_handles_use_cases has 17 different test cases. Each of these tests needs to be broken out into its own test case. Why? Because testing should test the smallest possible piece of code and fail specifically. If this current test implementation fails it is impossible to know when/where/why it failed. Breaking into 17 tests will show specifically which test has failed and where to fix it.

**Comment by jeherve** [comment]
Closing as `wontfix` as this issue didn't get any traction in the past 18 months.
