### ISSUE TITLE
Conflict between Photon and Revslider

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#10221]
Originally reported in 1444268-zen as well as in a chat I had but don't have the link for it anymore.

When using the Revslider (Revolution Slider) plugin on a site, along with Photon, images do not appear.  It seems that the plugin replaces the `src` URL of an image file with a `data:image/gif:base64` which fails to load. With Photon off, the images work as expected.

**Comment by jeherve** [comment]
Since this is a Premium plugin this is going to be hard for us to test things. 

Does this happen regardless of the Lazy Images module?

**Comment by richardmtl** [comment]
I've asked the reporter to try.

**Comment by tmmbecker** [comment]
1817568-zen

I've asked them to answer the question about Lazy Images.

**Comment by ntpixels** [comment]
Update for 1817568-zen
The issue occurs whether Lazy Load is enabled or not. They have also said they will reach out to the plugin's developer for more information.

**Comment by annezazu** [comment]
2718094-zen

**Comment by jenhooks** [comment]
2730598-zen

**Comment by cena** [comment]
2730598-zen

**Comment by druesome** [comment]
I can confirm that this is fixed based on my tests.  Closing this issue.  For more info: p9F6qB-5y4
