### ISSUE TITLE
Carousel: display notification if Carousel bails because another plugin or theme overrides the gallery shortcode

### ISSUE THREAD

**Issue by designsimply** [Automattic/jetpack#1023]
Steps to reproduce:

1. Set up a fresh install of WP
1. Install and activate the Cleaner Gallery plugin
1. Install Jetpack and make sure the Carousel module is activated
1. Go to Posts > Add New
1. Add a gallery
1. Click the Publish button
1. Open the post on the front end and check to see if Carousel works when you click on one of the images in the gallery
* Expected: a notification explaining carousel was disabled due to another plugin is overriding the `[gallery]` shortcode
* Actual: carousel doesn’t work and there’s no notifications, it looks like it’s enabled and that it should be working

![screen shot 2014-08-21 at thu aug 21 3 45 34 pm](https://cloud.githubusercontent.com/assets/1119271/4002350/f3acf616-296b-11e4-919c-f0ed160dd540.png)

Tested with WP trunk r29342 and JP 3.1.1 on Chrome 36.0.1985.143 on Mac OS X 10.9.4

Here’s what I see with no extra plugins installed:

* [gallery on front-end](https://cloudup.com/iq2RMeldnb7)
* [carousel after clicking an image](https://cloudup.com/iDEQvr0gdqN)

Here’s what I see with the Cleaner Gallery plugin installed:

* [gallery on front-end](https://cloudup.com/iNA6g8Xr73m)
* [no carousel after clicking an image](https://cloudup.com/ifPvhXs-oIq)
* [carousel settings](https://cloudup.com/il_3Qs6aXuN)

When the Carousel bails, we should detect that and show a notice in the admin.

https://plugins.trac.wordpress.org/browser/jetpack/tags/3.1.1/modules/carousel/jetpack-carousel.php#L80

`// Bail because someone is overriding the [gallery] shortcode`

Props mdawaffe for the original report (3762-wpcom)

**Comment by dereksmart** [comment]
Fixed in #1277
