### ISSUE TITLE
Auto/manual verify button text is cut off on mobile

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#10230]
#### Steps to reproduce the issue

1. Go to Verification tools on a mobile device
2. Depending on the device, the button and text will be cut off

#### Proposed solution

Shorten text to "Auto" and "Manual" on mobile devices, or put buttons on separate rows.

#### Screenshot

FF on Galaxy 8

<img width="335" alt="text cut off" src="https://user-images.githubusercontent.com/51896/46122358-0cae3500-c1cd-11e8-8536-0324d19cc3ce.png">

**Comment by stephanethomas** [comment]
This looks like a duplicate of https://github.com/Automattic/jetpack/issues/10219. Or am I missing something?

**Comment by stephanethomas** [comment]
Oh, I've now connected the dots. We should still take into account [the comment](https://github.com/Automattic/jetpack/issues/10219#issuecomment-425077542) I left there though.
