### ISSUE TITLE
Settings Save Fails When Change Is Undone and Saved

### ISSUE THREAD

**Issue by cbauerman** [Automattic/jetpack#10254]
![out](https://user-images.githubusercontent.com/2810519/46324940-14524d00-c5c4-11e8-9202-a5fc23c1e887.gif)

#### Steps to reproduce the issue

1. Navigate to Jetpack -> Settings -> Traffic -> Site Verification
2. Change one of the verification values, then revert the changes
3. Press the "SAVE SETTINGS" button

#### What I expected

Either to be notified that the settings were saved or that the settings weren't change or not to be able to click the "SAVE SETTINGS" button.

#### What happened instead

I received an Error "Error Updating Settings (400)."

**Comment by stephanethomas** [comment]
This error is actually generated here:

https://github.com/Automattic/jetpack/blob/f8078c2cd12ac508334da2fb08e37a92cf283c14/_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php#L1003

The `$invalid` array is empty, but `$not_updated` [contains](https://github.com/Automattic/jetpack/blob/f8078c2cd12ac508334da2fb08e37a92cf283c14/_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php#L970):

```php
array (
  'bing' => '',
)
```

The value should be considered to be the same here:

https://github.com/Automattic/jetpack/blob/f8078c2cd12ac508334da2fb08e37a92cf283c14/_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php#L753

However, it looks like `$grouped_options_current` only contains the value of the HTML meta tag:

```javascript
array (
  0 => '',
  'google' => 'something',
  'bing' => 'something else',
  'pinterest' => '',
)
```

Whereas `$grouped_options` actually contains the whole HTML tag:

```javascript
array (
  0 => '',
  'google' => 'something',
  'bing' => '<meta name="msvalidate.01" content="something else" />',
  'pinterest' => '',
)
```

**Comment by stephanethomas** [comment]
It looks like this issue existed before our changes. I checked out [6.5](https://github.com/Automattic/jetpack/commit/037acaa016d141c765c398ea166ba32b72519d04), and got the same error.
