### ISSUE TITLE
Idea to improve Custom CSS for huge and high traffic websites

### ISSUE THREAD

**Issue by MarceloPedra** [Automattic/jetpack#1026]
I manage several sites with almost 1000 post and 2000 tags, very well positioned in Google, thus receiving 5k-7k daily visitors, and I noticed that server load skyrocketed from 2 to 5 in rush hours when using JetPack's Custom CSS. Even when I use W3TC to create html cache which is refreshed only once daily. But I'm noticing a lot of Apache calls to "?custom-css=1&csblog=1&cscache=6&csrev=10" which I traced back to Custom CSS:

By doing that, every visitor hit is bypassing the html cache triggering a db query, which is what we need to minimize.

Is there a possibility to change the way you save the CSS to use a physically existing -and cachable- file?
It will improve the amount of queries for big sites and constrained servers.

Of note: I use a couple themes which don't include settings for custom CSS and are receiving monthly updates. Also, those sites are built on the original themes, rather than child ones. That's why  we cannot simply update the CSS files, nor always able to recall these customization, since the only thing changed in the theme. I give support for WordPress owners and this is a very common issue for a lot of websites. And this proposed improvement could help a lot of people and servers to improve performance of their websites.

Hope to hear soon from you.
Thank you

**Comment by sigginet** [comment]
I agree with inlining.
It will not only fix the problem with high server loads, it will also increase performance (especially when doing either fragment or full page caching).

I sent this as a suggestion this weekend to Automattic and they sent me here ..

Anyway, I decided to just fix this and add the patch to Jetpack.
You can find the updated file here: https://github.com/sigginet/jetpack/blob/patch-1/modules/custom-css/custom-css.php

I tested this on my client's website (whom I made the mod for) and it tested fine.

You can add this mod to your client's sites in order to reduce your server load.

**Comment by MarceloPedra** [comment]
Thanks sigginet. I currently have not a single place to test this because I switched all my sites to use custom code provided by free CJT plugin, which also provides ways to inject HTML and PHP, inline, and via shortcodes. Anyway, I'm very happy to see you have solved it finally. all ocdes should always be inserted inline. Thanks

**Comment by georgestephanis** [comment]
Fixed by #1592

**Comment by MarceloPedra** [comment]
Hi. I'm not sure if I understand the fix of commit a6681fc:

If the CSS code length is > 2000 characters, it will be pasted within <style>...</style> tags rather than being loaded using
<link rel="stylesheet" id="custom-css-css" type="text/css" href="....." />

I'm getting it right?

**Comment by sigginet** [comment]
If it is shorter than 2000 characters, the code will be inline in a "style" tag in the head.
If it is longer, it will use a "link" tag, causing it to be slow on non optimized hosting servers.

**Comment by georgestephanis** [comment]
Yes, however there's a filter you can use to force it either direction if you'd like.
