### ISSUE TITLE
Dashboard: Backups link still goes to VP for Rewind sites

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#10264]
#### Steps to reproduce the issue

For a site with Rewind, the _View backup history_ link takes you to VaultPress rather than the site's Activity Log:

![](http://cld.wthms.co/Ytmkk9+)
Image Link: http://cld.wthms.co/Ytmkk9

#### What I expected

This link should go directly to Activity Log where the user can Rewind.

**Comment by jeherve** [comment]
Related: #11662

**Comment by eliorivero** [comment]
Can you please tell me if the VP plugin was installed and active on that site?

**Comment by eliorivero** [comment]
Using Jetpack Beta, I was able to repro with Latest Stable but it's fixed with Bleeding Edge, so I'll close this.
