### ISSUE TITLE
Size dropdown in social icon widget doesn't respond

### ISSUE THREAD

**Issue by adamleone** [Automattic/jetpack#10284]
#### Steps to reproduce the issue

1. Install theme Small BusinessVersion: 1.0.2 
2. Navigate to Customize > Widget > Footer Widget 2 > Add Widget > Add social Icon Jetpack > Enter in the social media links into the spaces
3. Select a size from the drop down (small, medium, large) > Hit Done/save

#### What I expected

I expected the sizes of the icons to change. 

#### What happened instead

The sizes of the icons remain the same.

**Comment by kraftbj** [comment]
Hi @adamleone -- can you send an URL of a site impacted? Did this start with today's release? I _think_ it may be resolved by #10280.

**Comment by adamleone** [comment]
Hello @kraftbj - the site impacted is ohioshaunted.com. Yes, it was after an Jetpack plugin update.

**Comment by kraftbj** [comment]
Thanks! #10280 will fix them up. We're planning on shipping it in 6.6.1 tomorrow.
