### ISSUE TITLE
Disconnecting results in "Could not validate security token"

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#10290]
When a site has issues with the security token, our debug tool shows a handy “Could not validate security token” error.

However, when a user intentionally disconnects Jetpack, either via wp-admin or WordPress.com, the debug tool also shows “Could not validate security token.”

Is there any way we could add some kind of flag when a user disconnects on purpose, that the debug tool could pick up on, so that it could say “The user disconnected this site” instead of “Could not validate security token”?

**Comment by jeherve** [comment]
#9297 should help with this a bit.

**Comment by kraftbj** [comment]
This feels to be a regression as it used to not do that for intentional disconnections, unless one of the two sides was offline (e.g. Jetpack down was temporarily down and disconnected via Calypso).

**Comment by kraftbj** [comment]
Closing this to defer to https://github.com/Automattic/jetpack/issues/17532
