### ISSUE TITLE
Assets CDN: jQuery not enqueing with MailPoet

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#10295]
#### Steps to reproduce the issue

1. Running stable WP and stable Jetpack, activate the Asset CDN
2. Install MailPoet (wordpress.org/plugins/mailpoet)
3. Visit the MailPoet page within wp-admin

#### What I expected
Plugin UI to load

#### What happened instead
jQuery errors and not seeing jQuery in the source.

```
ReferenceError: jQuery is not defined[Learn More] mailpoet.eaab3da3.js:4913:1
TypeError: MailPoet.I18n is undefined, can't access property "add" of it[Learn More] admin.php:339:1
TypeError: MailPoet.I18n is undefined, can't access property "add" of it[Learn More] admin.php:342:1
TypeError: $.fn is undefined, can't access property "select2" of it[Learn More] admin_vendor.eaab3da3.js:35395:3
TypeError: _mailpoet2.default.I18n is undefined, can't access property "t" of it[Learn More]
```
I don't quite understand what is going wrong yet, but seems like no JS files are being included in the source. Only CSS.

Without the Asset CDN, jQuery, etc is included via `load-scripts.php`. On other pages with Assets CDN enabled, I see jQuery via the CDN.

cc: @georgestephanis @zinigor @kriskarkoski @richardmtl

**Comment by cecoates** [comment]
Replicated this with two more users, 7140357-hc and 1459698-zen

**Comment by codemonkey-jack** [comment]
@kraftbj Jack from MailPoet here, we're releasing a patch for this on our side Tuesday. 

The issue arises from the way we exclude 3rd party assets from loading on MailPoet admin pages to prevent breaking the newsletter editor and renderer. 

Because of this, we have a list of paths that we allow assets to load from which are as follows; 

```
// WP default
      '^/wp-admin',
      '^/wp-includes',
      'googleapis.com/ajax/libs',
      // third-party
      'query-monitor',
      'wpt-tx-updater-network'
```

Anything from a path outside of that will be blocked. We're patching in the Jetpack CDN and will be looking at other CDNs for a future release.

**Comment by kraftbj** [comment]
@codemonkey-jack Thanks for explanation! I had this on my list to dig into today and appreciate you stopping by. If there's anything you need from us, please let me know. I'll close this issue for now, deferring to y'all.

**Comment by carolynrosner** [comment]
11/26/18 - was a patch ever pushed? I have updated the plugin but it still does not work on my WP.com instance. Have contacted MailPoet support (Jack) ... hate to keep bugging you but I'm getting bugged by others about why this still doesn't work - maybe I'm doing something wrong.

**Comment by kriskarkoski** [comment]
@codemonkey-jack I'm not sure if it's related to the recent Jetpack update, but the media modal no longer works in MailPoet with Jetpack CDN on. I've disabled it for a user and confirmed that fixes this issue.

@carolynrosner In your Jetpack settings search "CDN" and turn off the "Speed up static file load times" option and let us know if that gets MailPoet working again for you. If not feel free to get in touch with us at wordpress.com/help/contact and we can help you further
