### ISSUE TITLE
Admin Page: Photon description is incorrect.

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#10300]
When going to Jetpack > Settings, here is the current description for the Photon feature:

> Jetpack's global Content Delivery Network (CDN) optimizes images so your visitors enjoy the fastest experience regardless of device or location. It also helps you save space on your hosting plan, since images are stored on our servers.

The second sentence is incorrect, since the images remain stored on the site as well. We would need to remove this.

The issue was introduced in #9720

We can also take that opportunity to update the support link from https://jetpack.com/support/image-cdn/ to https://jetpack.com/support/photon/

**Comment by simison** [comment]
cc @jeffgolenski @benhuberman

**Comment by simison** [comment]
I think the sentiment was to say it saves from hosting's _bandwidth_ plan, but for the sake of clarity, we're probably better without that sentence completely.

**Comment by jeffgolenski** [comment]
@simison Yeah definitely. We can just get rid of that one completely. Thanks @simison and @jeherve
