### ISSUE TITLE
MySQL warning unsafe statement

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#10304]
Originally reported here: https://wordpress.org/support/topic/mysql-warning-unsafe-statement/

<blockquote>mysqld[1824]: 2018-09-29 12:25:00 140636419537664 [Warning] Unsafe statement written to the binary log using statement format since BINLOG_FORMAT = STATEMENT. The statement is unsafe because it uses a LIMIT clause. This is unsafe because the set of rows included cannot be predicted. Statement: DELETE FROM 'wp_options' WHERE 'option_name' LIKE 'jetpack\\_nonce\\_%' AND CAST('option_value' AS UNSIGNED ) < 1538220300 ORDER BY 'option_id' LIMIT 100

</blockquote>

**Comment by jeherve** [comment]
The problem seems related to the user's setup.

This should help:
https://wordpress.org/support/topic/jetpack-mysql-errors/#post-6060531

> It’s because that statement can’t be safely replicated across to another database because there is no way of guaranteeing that the delete statement will delete the same rows in the replicated database.
> 
> You should find that setting your binlog replication to mixed fixes it.
