### ISSUE TITLE
Erroneous string on Jetpack Dashboard when site is in Chinese

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#10313]
First reported in https://wordpress.org/support/topic/website-statistics-browsing-display-code/

1) Switch site to Chinese (China)
2) Visit /wp-admin/admin.php?page=jetpack#/dashboard
3) See this bad string:

![screen shot 2018-10-12 at 10 56 38](https://user-images.githubusercontent.com/3676359/46876928-8ec56d00-ce0d-11e8-88fa-fb3c07aab5c4.png)

**Comment by eliorivero** [comment]
Tested this with zh_cn, zh_tw, and zh_hk. It's working fine in all these languages so will close.

<img width="820" alt="Captura de Pantalla 2019-05-06 a la(s) 16 27 08" src="https://user-images.githubusercontent.com/1041600/57249628-d31f9100-701b-11e9-8c40-0a276b665a8c.png">
