### ISSUE TITLE
Jetpack sharing at the start of Post

### ISSUE THREAD

**Issue by mj00712** [Automattic/jetpack#10317]
Please add social media sharing at the start of the post. I know we can add that by changing the code but kindly include this in the next update of the plugin. Due to this, I have switched to another plugin

**Comment by jeherve** [comment]
That is not something we plan on adding to the Jetpack plugin in the near future.

You can, however, as you pointed out, use custom code to add those sharing buttons to the top of your posts. Here is how:
https://jetpack.com/2013/06/10/moving-sharing-icons/

If you do not feel comfortable making those changes on your own, I would recommend using a plugin like this one instead:
https://wordpress.org/plugins/jetpack-sharing-butttons-shortcode/

It will allow you to add buttons anywhere you want in the content of your posts.

**Comment by mj00712** [comment]
thanx but consider adding it
