### ISSUE TITLE
Gutenberg: enqueue blocks' scripts and styles conditionally

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#10325]
#### Steps to reproduce the issue

1. Using the latest version of Jetpack Master, add Gutenberg blocks as described here:
https://github.com/Automattic/jetpack/blob/master/docs/guides/gutenberg-blocks.md#L1
2. From that point on Jetpack enqueues 2 files on every page of your site, whether you use Jetpack blocks or not, on that page or not.

Ideally, we should only enqueue those files when needed. 

Related: #10198

**Comment by sirreal** [comment]
#10328 should fix this.

**Comment by jeherve** [comment]
Reopening for now, as #10491 reverted some of our work.

**Comment by enejb** [comment]
@jeherve can you explain what broke? 
editor.js now has both the previous view.js as well as the editor.js files

**Comment by jeherve** [comment]
> editor.js now has both the previous view.js as well as the editor.js files

What does this mean in practice? Will we be loading the full `editor.js` on all pages that have a tiled gallery or any other Jetpack block?

**Comment by jeherve** [comment]
Closing this as this now works well.
