### ISSUE TITLE
Module Info: Display "More Link" to push people to Jetpack.me support docs

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#1032]
In module-info.php, we have more_link directing people to documentation (e.g. https://github.com/Automattic/jetpack/blob/master/modules/module-info.php#L901-904 via a `jetpack_learn_more_button_$module` filter).

On the pop-up modal of the description, we seem not to output the link: https://cloudup.com/cAE_z0E1hmR

**Comment by zinigor** [comment]
I vote to close this one in favor of developments to happen in 4.0
