### ISSUE TITLE
Environment Developer Yarn build display errors

### ISSUE THREAD

**Issue by mostafaabd** [Automattic/jetpack#10329]
#### Steps to reproduce the issue

1. my os system is win 10 and i install vvv
2.  I insalled kali linux and node ver 10 , yarn 1.7
3. when run command yarn build display this error
<pre>
Mostafa (master) jetpack
$ yarn distclean && yarn build
yarn run v1.7.0
$ rm -rf node_modules && yarn cache clean
success Cleared cache.
Done in 47.25s.
yarn run v1.7.0
$ yarn install-if-deps-outdated && yarn build-client
$ yarn check 2> /dev/null || yarn install --check-files
The system cannot find the path specified.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[----------------------------------------------------------------------] 0/1491(
node:7688) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security
and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Bu
ffer.from() methods instead.
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check.
Excluding it from installation.
[4/5] Linking dependencies...
warning " > eslint-eslines@1.0.0" has incorrect peer dependency "eslint@4.*".
[5/5] Building fresh packages...
$ gulp
[12:36:51] Failed to load external module @babel/register
[12:36:51] Requiring external module babel-register
[12:37:04] Using gulpfile E:\vvv\www\wordpress-default\public_html\wp-content\pl
ugins\jetpack\gulpfile.babel.js
[12:37:04] Starting 'react:build'...
[12:37:05] Starting 'frontendcss:separate'...
[12:37:05] Starting 'admincss'...
[12:37:05] Starting 'admincss:rtl'...
[12:37:05] Starting 'old-sass'...
[12:37:05] Starting 'old-sass:rtl'...
[12:37:05] Starting 'check:DIR'...
[12:37:05] Starting 'php:lint'...
[12:37:05] Starting 'js:hint'...
[12:37:05] Starting 'php:module-headings'...
[12:37:05] Starting 'gutenpack'...
[12:37:05] Starting 'gutenpack:jetpack-blocks'...
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn php ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:217:19)
    at onErrorNT (internal/child_process.js:394:16)
    at process._tickCallback (internal/process/next_tick.js:174:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:223:12)
    at onErrorNT (internal/child_process.js:394:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
</pre>

**Comment by jeherve** [comment]
Sorry you ran into issues. I wonder if this may be an issue with your version of `yarn`. Could you try to uninstall and then reinstall the latest stable as explained here:
https://yarnpkg.com/en/docs/install

Let us know how that goes.

Related: #8267

**Comment by jeherve** [comment]
> at the end there is command make how can is use it

It comes with most Linux distributions so that should not be an issue here, but you can test and see if Make is installed on your Vagrant machine by running `make`.

**Comment by mostafaabd** [comment]
So sorry for that, but i take me 5 days and nothing work , how and where i can use it i run it see when i write it
<pre>
Mostafa (master) vvv
$ make
bash: make: command not found
Mostafa (master) vvv
$ vagrant make
Usage: vagrant [options] <command> [<args>]

    -v, --version                    Print the version and exit.
    -h, --help                       Print this help.

Common commands:
     box             manages boxes: installation, removal, etc.
     destroy         stops and deletes all traces of the vagrant machine
     global-status   outputs status Vagrant environments for this user
     halt            stops the vagrant machine
     help            shows the help for a subcommand
     hostsupdater
     init            initializes a new Vagrant environment by creating a Vagrantfile
     login           log in to HashiCorp's Vagrant Cloud
     package         packages a running vagrant environment into a box
     plugin          manages plugins: install, uninstall, update, etc.
     port            displays information about guest port mappings
     powershell      connects to machine via powershell remoting
     provision       provisions the vagrant machine
     push            deploys code in this environment to a configured destination
     rdp             connects to machine via RDP
     reload          restarts vagrant machine, loads new Vagrantfile configuration
     resume          resume a suspended vagrant machine
     snapshot        manages snapshots: saving, restoring, etc.
     ssh             connects to machine via SSH
     ssh-config      outputs OpenSSH valid configuration to connect to the machine
     status          outputs status of the vagrant machine
     suspend         suspends the machine
     up              starts and provisions the vagrant environment
     validate        validates the Vagrantfile
     version         prints current and latest Vagrant version

For help on any individual command run `vagrant COMMAND -h`

Additional subcommands are available, but are either more advanced
or not commonly used. To see all subcommands, run the command
`vagrant list-commands`.
</pre>

**Comment by mostafaabd** [comment]
i remove kali linux and add it again , error message is same
<pre>
 yarn distclean && yarn build
yarn run v1.10.1
$ rm -rf node_modules && yarn cache clean
success Cleared cache.
Done in 108.76s.
yarn run v1.10.1
$ yarn install-if-deps-outdated && yarn build-client
$ yarn check 2> /dev/null || yarn install --check-files
The system cannot find the path specified.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check.
Excluding it from installation.
[4/5] Linking dependencies...
warning " > eslint-eslines@1.0.0" has incorrect peer dependency "eslint@4.*".
[5/5] Building fresh packages...
$ gulp
[16:29:51] Failed to load external module @babel/register
[16:29:51] Requiring external module babel-register
[16:30:02] Using gulpfile E:\vvv\www\wordpress-default\public_html\wp-content\pl
ugins\jetpack\gulpfile.babel.js
[16:30:02] Starting 'react:build'...
[16:30:03] Starting 'frontendcss:separate'...
[16:30:03] Starting 'admincss'...
[16:30:03] Starting 'admincss:rtl'...
[16:30:03] Starting 'old-sass'...
[16:30:03] Starting 'old-sass:rtl'...
[16:30:03] Starting 'check:DIR'...
[16:30:03] Starting 'php:lint'...
[16:30:03] Starting 'js:hint'...
[16:30:03] Starting 'php:module-headings'...
[16:30:03] Starting 'gutenpack'...
[16:30:03] Starting 'gutenpack:jetpack-blocks'...
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn php ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:217:19)
    at onErrorNT (internal/child_process.js:394:16)
    at process._tickCallback (internal/process/next_tick.js:174:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:223:12)
    at onErrorNT (internal/child_process.js:394:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

</pre>

**Comment by jeherve** [comment]
I wonder if there may be an issue with the way PHP is installed, as explained here:
https://stackoverflow.com/a/51091705/1045686

Could you try to run `php ./tools/build-module-headings-translations.php`, and see what you get? That should tell us more about the issue, as we'll see if PHP is available or not.

Thank you!

**Comment by mostafaabd** [comment]
i think you mean run it inside jetpack
<pre>
Mostafa (master) jetpack
$ ./tools/build-module-headings-translations.php
./tools/build-module-headings-translations.php: line 1: ?php: No such file or directory
./tools/build-module-headings-translations.php: line 3: =: command not found
./tools/build-module-headings-translations.php: line 18: syntax error near unexpected token `('
./tools/build-module-headings-translations.php: line 18: `$jp_dir = dirname( dirname( __FILE__ ) ) . '/';'
</pre>

**Comment by jeherve** [comment]
Could you run `php ./tools/build-module-headings-translations.php` instead?

**Comment by mostafaabd** [comment]
Hello, Thanks for your help i don't know how its works now,
its work with yarn 1.10.1, and node 10.12.0 but in documentation for Development Environment https://github.com/Automattic/jetpack/blob/master/docs/development-environment.md 
write to use yarn 1.7, and node 10.0 .
last steps i do but not worked yesterday and worked no
1- install kali linux
2- node
3- yarn
and when i build its display error at above but it working no without use `yarn build`
when i write this line 
Could you run `php ./tools/build-module-headings-translations.php ` instead? display this error with and without ssh, so which folder i write this command, i use git bash as CLI
<pre>
Mostafa (master) jetpack
$ php ./tools/build-module-headings-translations.php
bash: php: command not found
Mostafa (master) jetpack
$ vagrant ssh
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  Have a nice day


vagrant@vvv:~$ php ./tools/build-module-headings-translations.php
Could not open input file: ./tools/build-module-headings-translations.php
vagrant@vvv:~$
<pre>
and please see this when i run Admin Page unit tests
<pre>
$ yarn
yarn install v1.10.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check.
Excluding it from installation.
[4/5] Linking dependencies...
warning " > eslint-eslines@1.0.0" has incorrect peer dependency "eslint@4.*".
[5/5] Building fresh packages...

Done in 57.82s.
Mostafa (master) jetpack
$ yarn test-client
yarn run v1.10.1
$ NODE_ENV=test NODE_PATH=tests:_inc/client:node_modules/@automattic/dops-compon
ents/client tests/runner.js
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
Mostafa (master) jetpack
$ yarn test-gui
yarn run v1.10.1
$ NODE_ENV=test NODE_PATH=tests:_inc/client:node_modules/@automattic/dops-compon
ents/client tests/runner.js gui
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
Mostafa (master) jetpack
$ yarn test-modules
yarn run v1.10.1
$ NODE_ENV=test NODE_PATH=tests:_inc/client:node_modules/@automattic/dops-compon
ents/client tests/runner.js modules
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
Mostafa (master) jetpack
</pre>

**Comment by kraftbj** [comment]
You'd need to run `php ./tools/build-module-headings-translations.php` after `vagrant ssh` in the folder of the Jetpack directory. Right now, looks like you're running it from the home directory. e.g. you'd need to `cd /srv/www/wordpress-develop/public_html/build/wp-content/plugins/jetpack` (if you had Jetpack checked out so that WordPress trunk's install was using it).

**Comment by jeherve** [comment]
Another alternative would be to try to use our Docker implementation instead, as described here:
https://github.com/Automattic/jetpack/tree/master/docker

**Comment by mostafaabd** [comment]
@kraftbj i run it inside jetpack folder but not work, but inside wordpress-default because link to wordpress-develop not work with me.
@jeherve Very thanks its work with vvv, for the last message i send i mean jetpack work but i don't know why its work now ? very thanks

**Comment by kraftbj** [comment]
For the sake of tracking, I'm going to close this issue until there's a bug found, but the conversation can continue.

Regrading the `php ./tools/build-module-headings-translations.php` command -- what was the output?

**Comment by mostafaabd** [comment]
hello, display error, i  run it in this path www\wordpress-default\public_html\wp-content\plugins\jetpack
<pre>
Mostafa (master) jetpack
$ vagrant ssh
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  Have a nice day


vagrant@vvv:~$ php ./tools/build-module-headings-translations.php
Could not open input file: ./tools/build-module-headings-translations.php
vagrant@vvv:~$

</pre>

**Comment by kraftbj** [comment]
From that text, you're running it in the home directory. 
From `vagrant@vvv:~$`, you'd need to `cd /srv/www/wordpress-default/public_html/wp-content/plugins/jetpack`

That particular error is saying you're not actually referring to an actual file.

**Comment by mostafaabd** [comment]
This is first time using vvv so i talk time to learn it. i run command fist with `php` at beginning of command in this case don't display any thing and second without `php` in this case display error.
<pre>
vagrant@vvv:/srv/www/wordpress-default/public_html/wp-content/plugins/jetpack$ php ./tools/build-module-headings-translations.php
vagrant@vvv:/srv/www/wordpress-default/public_html/wp-content/plugins/jetpack$ ./tools/build-module-headings-translations.php
: No such file or directorygs-translations.php: line 1: ?php
./tools/build-module-headings-translations.php: line 2: $'\r': command not found
./tools/build-module-headings-translations.php: line 3: =: command not found
./tools/build-module-headings-translations.php: line 16: $'\r': command not found
./tools/build-module-headings-translations.php: line 17: $'\r': command not found
./tools/build-module-headings-translations.php: line 18: syntax error near unexpected token `('
'/tools/build-module-headings-translations.php: line 18: `$jp_dir = dirname( dirname( __FILE__ ) ) . '/';
vagrant@vvv:/srv/www/wordpress-default/public_html/wp-content/plugins/jetpack$
</pre>

**Comment by kraftbj** [comment]
The first instance is correct -- the file doesn't echo anything. I'll toss this back to @jeherve wrt what he was wanting to test by you doing that.

**Comment by jeherve** [comment]
If PHP is available here you should be all set, everything should work. Do you still experience issues?

**Comment by mostafaabd** [comment]
ok thanks a lot
