### ISSUE TITLE
 Social Menu & Social Media Icons: Add Mastodon Support

### ISSUE THREAD

**Issue by transmothra** [Automattic/jetpack#10338]
Please add support for [Mastodon](https://joinmastodon.org/), a distributed, decentralized, federated micro-blogging platform popular among people abandoning Twitter and Free software/Free culture enthusiasts ([many nodes exist](https://the-federation.info/mastodon))

**Comment by chrisaldrich** [comment]
I've noticed that @janboddez has a plugin that will do this for a variety of Fediverse instances including Mastodon: <a href="https://github.com/janboddez/add-fediverse-icons-to-jetpack" rel="noopener" target="_blank">https://github.com/janboddez/add-fediverse-icons-to-jetpack</a>.

There's also an approved version in the repository named <a href="https://wordpress.org/plugins/add-fediverse-icons-to-jetpack/" rel="noopener" target="_blank">Add Fediverse Icons to Jetpack</a>.

(Originally published on https://boffosocko.com/2020/01/26/fediverse-icons-for-jetpack/)

**Comment by chrisaldrich** [comment]
Bump. Perhaps this would be more useful now? ;)
