### ISSUE TITLE
MailPoet 3 does not work with Asset CDN enabled

### ISSUE THREAD

**Issue by codemonkey-jack** [Automattic/jetpack#10353]
#### Steps to reproduce the issue

1. Install MailPoet 3 and enable Asset CDN in Jetpack
2. Go to wp-admin > MailPoet > Emails > Add new, select a template and newsletter type (doesn't matter which)
3. Try and add an image to the newsletter.

#### What I expected

I expected the image to be added to the newsletter by selecting the image from the media library and then selecting the appropriate image. 

#### What happened instead

The WordPress media library loads blank/doesn't load and no image is added to the newsletter. 
Note this relates to; https://github.com/Automattic/jetpack/issues/10295 (We've already added a fix on our end).

**Comment by kraftbj** [comment]
Were there any console errors?

**Comment by codemonkey-jack** [comment]
@kraftbj I've found the issue, it's with this code; 

```
		if ( self::is_public_version( $version ) ) {
			$site_url = trailingslashit( site_url() );
			foreach ( $wp_scripts->registered as $handle => $thing ) {
				if ( wp_startswith( $thing->src, self::CDN ) ) {
					continue;
				}
				$src = ltrim( str_replace( $site_url, '', $thing->src ), '/' );
				if ( self::is_js_or_css_file( $src ) && in_array( substr( $src, 0, 9 ), array( 'wp-admin/', 'wp-includ' ) ) ) {
					$wp_scripts->registered[ $handle ]->src = sprintf( self::CDN . 'c/%1$s/%2$s', $version, $src );
					$wp_scripts->registered[ $handle ]->ver = null;
				}
			}
			foreach ( $wp_styles->registered as $handle => $thing ) {
				if ( wp_startswith( $thing->src, self::CDN ) ) {
					continue;
				}
				$src = ltrim( str_replace( $site_url, '', $thing->src ), '/' );
				if ( self::is_js_or_css_file( $src ) && in_array( substr( $src, 0, 9 ), array( 'wp-admin/', 'wp-includ' ) ) ) {
					$wp_styles->registered[ $handle ]->src = sprintf( self::CDN . 'c/%1$s/%2$s', $version, $src );
					$wp_styles->registered[ $handle ]->ver = null;
				}
			}
		}
```

In `jetpack/modules/photon-cdn.php` from line 54 till 76. 

Specifically 

`				if ( self::is_js_or_css_file( $src ) && in_array( substr( $src, 0, 9 ), array( 'wp-admin/', 'wp-includ' ) ) ) {
`

Should be 

`				if ( self::is_js_or_css_file( $src ) && in_array( substr( $src, 0, 9 ), array( 'wp-admin/', 'wp-includes' ) ) ) {
`

Updating both instances of `wp-includ` to `wp-includes` gets everything working correctly again!

**Comment by kraftbj** [comment]
@zinigor - Can you give this a look?

**Comment by jeherve** [comment]
> Updating both instances of wp-includ to wp-includes gets everything working correctly again!

Unfortunately that is not something we can do. By doing so you essentially do not activate the Asset CDN feature for any of the site's resources in the `wp-includes` directory. We do want to serve those resources via the CDN.

What is odd is that I do not notice anything wrong with any of the resources served via the CDN; all the files in the `wp-includes` directory are served properly.

Taking a closer look, I can see that when the Asset CDN module is enabled, some specific WordPress Core resources are not loaded on the MailPoet page. `media-views.css` is one of those resources.
This file should be loaded via `wp_enqueue_media()`, which you call here if I am correct:
https://plugins.trac.wordpress.org/browser/mailpoet/trunk/lib/Config/Menu.php#L651

However I can't see any of the Media files enqueued anywhere when the Asset CDN feature is active, for some reason. If I enqueue them myself manually it works.

Could you tell us more about how you enqueue those files on your end?

**Comment by carolynrosner** [comment]
As a temporary workaround, one can access the Media Library a different way, copy an image URL, return to MP email build, and paste URL in image field. Clunky, but works.

**Comment by codemonkey-jack** [comment]
@jeherve We found the issue after some extensive testing and as quite often with these things it turned out to be the obvious that was initially missed!

In the last release we added support for the CDN JS files, but the CSS files weren't allowed in oiur conflict resolver, after running some tests and updating the conflict resolver on our end it now works. 

We'll push this patch in our release on Tuesday, thanks for checking! Feel free to close this out. :)

**Comment by jeherve** [comment]
Excellent, thanks for the update! 🎉 	

Closing this now then.

**Comment by carolynrosner** [comment]
Just re-installed MP with WP help and am still experiencing the blank Media Library screen when trying to add images to a newsletter I'm building. Installed 3.12.1 version of MP.

**Comment by carolynrosner** [comment]
Just learned that the fix is coming in the coming Jetpack release, please disregard!
