### ISSUE TITLE
Push Notifications for Monitor

### ISSUE THREAD

**Issue by pento** [Automattic/jetpack#1037]
It'd be nice if Monitor sent a push notification to my WP.com account if my site is down.

**Comment by kraftbj** [comment]
Requested also in 2101261-t

Generating a normal WP.com notification (like a comment already does) would be a huge win.

**Comment by ntpixels** [comment]
2718621-t

**Comment by lezama** [comment]
@enejb what do we need to do to make this happen? :)

**Comment by jeherve** [comment]
This is being worked on in #7892

**Comment by brbrr** [comment]
This is already implemented 🎉
