### ISSUE TITLE
Shortcodes: slideshow-shortcode.js uses ? for URL parameters when & is correct

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#104]
[On line 42 in slideshow-shortcode.js](https://github.com/Automattic/jetpack/blob/2.7/modules/shortcodes/js/slideshow-shortcode.js#L42) the "w" parameter is added to the image URL
using a question mark.

Sometimes images already have parameters.

This will lead to invalid URLs like example.com/image.jpg?n=1?w=200

An easy fix would be to use a question mark only if there are no parameters
present in the image URL. In all other cases use an ampersand instead.

**Comment by osiux** [comment]
That wes removed in ebcdf36, so maybe close this?

**Comment by jeherve** [comment]
Good call!
