### ISSUE TITLE
Import meta descriptions from Yoast to Jetpack SEO

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#10406]
#### Is your feature request related to a problem? Please describe.

> If you could suggest to the dev team to add an option or create a plugin to import meta description from other SEO plugins, that would be great for "old" wordpress websites or if they have a solution via PHPmyadmin otherwise i don't see how we can move all this stuff to jetpack SEO?!!!

#### Describe the solution you'd like

An option to import meta descriptions and title structures into Jetpack SEO from other SEO plugins.

#### Additional context

Requested in 1517827-zen

**Comment by kraftbj** [comment]
There's a third-party solution that works well for this by StudioPress: https://wordpress.org/plugins/seo-data-transporter/

**Comment by kraftbj** [comment]
Going to close this one. StudioPress still actively maintains the plugin mentioned above and they're a reputable shop. It makes sense to suggest that utility for folks instead of us reinventing the wheel.
