### ISSUE TITLE
Comments module: Reply HTML is stripped out

### ISSUE THREAD

**Issue by dashkevych** [Automattic/jetpack#10471]
By default, WordPress allows to add custom HTML to the Reply title by using `title_reply_before` and `title_reply_after`. Here is an example:

```
comment_form( array(
  'title_reply_before' => '<h2 id="reply-title" class="comment-reply-title"><span>',
  'title_reply_after'  => '</span></h2>',
) );
```

As a result, the output looks like this:

```
<h2 id="reply-title" class="comment-reply-title">
<span>Leave a Reply</span>
</h2>
```

When the Comments module is active, the output looks totally different and it ignores the values that were added to `title_reply_before` and `title_reply_after`.

The output looks like this:

```
<h3 id="reply-title" class="comment-reply-title">Leave a Reply</h3>
```

Is there a way to keep `title_reply_before` and `title_reply_after` settings?

**Comment by jeherve** [comment]
I'm afraid that's a known problem with Jetpack's comment form (see #477); like other comment form plugins, it completely replaces the comment form with its own form, added via an iFrame and thus hosted somewhere else (on WordPress.com), where customization is often impossible. You would get similar issues with another external comment solution.

If you wish to customize the comment form fields, I would consequently recommend that you deactivate Jetpack's Comment form feature.
