### ISSUE TITLE
Mods.js throws TypeError when using jQuery alias ($)

### ISSUE THREAD

**Issue by joshuatf** [Automattic/jetpack#10474]
The mods.js file includes a jQuery alias ($) that throws a TypeError and probably needs to be replaced with `jQuery` - https://github.com/Automattic/jetpack/blob/2a01b10ba931c94f79c8add0f2dea06c4f5892c1/modules/calypsoify/mods.js#L34

#### Steps to reproduce the issue

1. Make sure `JETPACK_DEV_DEBUG` is set to true.
2. Go to any page in the admin dashboard.
3. Append `calypsoify=1` to the URL to enable Calypsoify.
4. Check console for error.

#### What I expected
Expected no TypeError to be thrown.

#### What happened instead
TypeError was thrown.

**Screenshots**
<img width="368" alt="screen shot 2018-10-29 at 8 13 26 am" src="https://user-images.githubusercontent.com/10561050/47651921-8af65200-db52-11e8-8e07-90458f1df613.png">

**Comment by jeherve** [comment]
cc @georgestephanis who has been working on numerous changes in #10371

**Comment by joshuatf** [comment]
Glancing at that those changes, it does look like this is resolved here - https://github.com/Automattic/jetpack/blob/69051d12872aef61d5b208de6c15560378bf2b14/modules/calypsoify/mods.js#L68

This issue can probably be closed pending merge of #10371

**Comment by jeherve** [comment]
We'll close this when #10474 gets merged then 👍
