### ISSUE TITLE
Allow subsite admins to dismiss Jetpack connection notice if they don't want to use/connect Jetpack

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#1049]
If a Network Admin selects the "Allow individual site administrators to manage their own connections (connect and disconnect) to WordPress.com" checkbox, and a subsite admin decides that they don't want to use or connect Jetpack, clicking the X in the "Jetpack is installed" notice on the subsite should dismiss the notice and ideally remove the Jetpack menu item. Instead, the subsite admin gets sent to the Jetpack page of their site, and is shown the following notice:

![screenshot on 2014-08-27 at 11-55-31](https://cloud.githubusercontent.com/assets/3676359/4063000/57fedf3e-2e04-11e4-878e-6b1fb5c21860.png)

**Comment by dereksmart** [comment]
Unless we're talking about something else here, the connection banner will only show on `/wp-admin/plugins.php`, which only super admins will have access to.  Dismissing the notice by a super admin will deactivate Jetpack, as it does in a single site.  

Closing this issue, please reopen if I'm mistaken on what banner we're referring to.

**Comment by jeherve** [comment]
> the connection banner will only show on /wp-admin/plugins.php, which only super admins will have access to.

Site admins can also access the Plugins menu if the super admin allowed them access, thanks to the checkbox at the bottom of Network > Settings in the Network admin panel.

**Comment by dereksmart** [comment]
From my tests, this is no longer the case and sub sites can dismiss the connection banner.
