### ISSUE TITLE
Stats: 'more' icon missing on non-default admin themes

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#10502]
#### Steps to reproduce the issue

1. Go to Jetpack > Site Stats with default admin theme.
2. Look at the Top Posts & Pages box and see the icon here:

![image](https://user-images.githubusercontent.com/1990037/47845769-c8aae300-ddbd-11e8-83cf-780b676ca238.png)

3. Go to Users > Your Profile, and activate the 'Light' theme.
4. Check the stats again.

#### What I expected

The 'more' stats icon would appear as in above screenshot.

#### What happened instead

The icon is missing.

**Screenshots**

![image](https://user-images.githubusercontent.com/1990037/47845859-10316f00-ddbe-11e8-9d6d-0b0d816e165e.png)

Looks like all themes are affected other than the default.

Reported in 1522206-zen

**Comment by jeherve** [comment]
Closing this since the stats screen has now been redesigned.
