### ISSUE TITLE
Authors / RSS Widget: improve layout for Twenty Nineteen

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#10522]
1. Add the Twenty Nineteen theme to your site.
2. Add both the Authors widget and the RSS widget to the sidebar:

<img width="226" alt="9s1prkliia" src="https://user-images.githubusercontent.com/426388/47926029-de083600-debf-11e8-9fc9-84345897b1d2.png">
<img width="391" alt="0fl589sxdv 1" src="https://user-images.githubusercontent.com/426388/47926030-de083600-debf-11e8-8e05-d102f8098a9f.png">

> I think the bullets don’t make much sense in this theme – I don’t see them in any other widget. Perhaps we should just remove them and the space that they introduce?
> Same for the RSS widget

**Comment by allancole** [comment]
> I think the bullets don’t make much sense in this theme – I don’t see them in any other widget. Perhaps we should just remove them and the space that they introduce? Same for the RSS widget

While there might not be other _widgets_ that use bullets for lists, bullets do appear in the List Block (and in normal lists from the old editor). Screenshot:

![image](https://user-images.githubusercontent.com/709581/48104788-e1265d80-e202-11e8-9b49-db2f6f7e3f41.png)

**Comment by allancole** [comment]
I think the appearance for these should look as close as possible to comments with avatars:

![image](https://user-images.githubusercontent.com/709581/48104907-60b42c80-e203-11e8-99e5-ea6e3795d9c8.png)

**Comment by crunnells** [comment]
This issue should be fixed by the above commit, pending review by @allancole

**Comment by allancole** [comment]
Yup, this is looking great, @crunnells. Thanks!
