### ISSUE TITLE
'wpas_default_message' filter cannot define the message to social media.

### ISSUE THREAD

**Issue by kankando** [Automattic/jetpack#10532]
#### Steps to reproduce the issue

1. Go to create a plugin and 'add_filter('wpas_default_prefix', 'override_default_message' )
2. define override_default_message function which return string "testing".
3. create and publish a post, with jetpack linked to a facebook page
4. still the facebook post with the default_message title only but not "testing"

#### What I expected
facebook post should with "testing" instead.

#### Here is the function
```
function override_default_message( $default_message ) {
    return "testing";
}
```

**Comment by jeherve** [comment]
I can't seem to be able to reproduce the issue on my end:

<img width="315" alt="screenshot 2018-11-05 at 9 28 53" src="https://user-images.githubusercontent.com/426388/47986545-5c8def00-e0dd-11e8-92bd-47a206ab5270.png">
<img width="333" alt="screenshot 2018-11-05 at 9 28 13" src="https://user-images.githubusercontent.com/426388/47986546-5c8def00-e0dd-11e8-90d9-daadcf10a7bf.png">

You may be running into #1836 though, if your posts are scheduled.
