### ISSUE TITLE
Teachers (Sensei plugin) can't manage their own videos uploaded via VideoPress

### ISSUE THREAD

**Issue by amroland** [Automattic/jetpack#10536]
#### Steps to reproduce the issue

1. Log in as a Teacher
2. Go to **Media » Library** menu, use default GRID mode (VideoPress doesn't support LIST mode).
3. Click on Add new button and upload a video file.
4. After uploaded you can see the uploaded video in the list.
5. Refresh the page.
6. Uploaded video is disappeared.

#### What I expected
Teachers should manage (see or delete) their own videos uploaded via VideoPress.
Furthermore Teachers should only see **their own videos**, and shouldn't see videos uploaded by other Teachers.

#### What happened instead
Users with Teacher role can't see or delete their own videos uploaded via VideoPress in Media Library.
After uploading them videos are disappearing.
Nevertheless using VideoPress upload in any posts (by clicking Add Media button) the shortcode of this video is still visible. But the current uploaded videos still couldn't be found in Media Library.

It must be some kind of role capability problem, because currently users with Administrator, Editor and Author role can normally manage their VideoPress videos. They all can upload, see and delete videos. They can see ALL VideoPress videos uploaded by ANYONE. After all this works as it should, only Teachers should see their own videos, not by others.

**Screenshots**
Uploading:
![kepernyofoto 2018-11-04 - 13 17 42](https://user-images.githubusercontent.com/39312392/47964074-a4a50700-e034-11e8-8b83-a3eb4eeb1158.png)
![kepernyofoto 2018-11-04 - 13 17 55](https://user-images.githubusercontent.com/39312392/47964075-ab337e80-e034-11e8-81d2-c76382a9d56e.png)

After refreshing the page video is disappeared:
![kepernyofoto 2018-11-04 - 13 18 39](https://user-images.githubusercontent.com/39312392/47964084-be464e80-e034-11e8-94ad-ce3da193e078.png)

Uploading video in any post VideoPress shortcode is still visible:
![kepernyofoto 2018-11-04 - 13 28 22](https://user-images.githubusercontent.com/39312392/47964148-b3d88480-e035-11e8-9960-e9906cadbda8.png)

Environment:
WordPress 4.9.8.
Sensei 1.9.20.
Jetpack 6.6.1.

**Comment by jeherve** [comment]
Thanks for the report.

Does this keep happening once the teachers have linked their own account to their own WordPress.com account? They can do so under Jetpack > Dashboard, by clicking on the banner offering to link their account at the top of the page?

If this keeps happening then, could you let me know if this also happens when uploading videos via the WordPress.com media interface?
https://wordpress.com/media/

**Comment by amroland** [comment]
Hi Jeremy,

I will try it immediately.
But a prompt reply: Users with Editor or Author role can normally use
VideoPress without linking their account to WordPress.com account.

I am coming back with the results soon.

Ambrus Roland


Jeremy Herve <notifications@github.com> ezt írta (időpont: 2018. nov. 5.,
H, 9:35):

**Comment by amroland** [comment]
Hi,

I tested linking their account to WordPress.com. It does keep happening the same way.
The uploaded video appeared in their own WordPress.com account in Media menu. But it doesn't appeared in Media menu of the website.

However Media menu in teacher's WordPress.com account is not visible, because teachers don't have purchased WordPress.com plan, only administrator has. The current webpage doesn't belong to teachers either.
![kepernyofoto 2018-11-05 - 14 34 35](https://user-images.githubusercontent.com/39312392/48001727-b60c1300-e109-11e8-9d9b-b63db2a7e3cc.png)

**Comment by jeherve** [comment]
Thanks for the extra details. I ran some tests, and it appears that this is a limitation added by Sensei.

By default, Sensei restricts what a teacher can see in the media library; you will only be able to see the media you have uploaded:
https://github.com/Automattic/sensei/blob/a124c4bb23fb276cd53fcccd55da30f8b82d0902/includes/class-sensei-teacher.php#L1306

When you upload a video via VideoPress, the video is not uploaded in the name of the uploader. Thus, the teacher can't see the video they have uploaded.

To fix this for now, I would recommend that you remove the restrictions added by Sensei and allow teachers to see all media in the Media Library.

----

Looking further, it seems this was already reported and discussed here:
https://github.com/Automattic/sensei/issues/2128

I'll consequently close this issue in favor of the other one, that includes more information about the problem and potential solutions.
