### ISSUE TITLE
Gutenberg: when Jetpack is active, part of the contextual toolbar is missing from Text block

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#10549]
#### Steps to reproduce the issue

1. Start with a site running Jetpack 6.7 and WP 5.0 Beta 3
2. Go to Posts > Add New
3. Start writing some text. 
4. See this toolbar for the block:

<img width="404" alt="screenshot 2018-11-06 at 19 11 10" src="https://user-images.githubusercontent.com/426388/48084535-49237680-e1f8-11e8-83bd-4cbb6da261fe.png">

#### What I expected

This is what I should be seeing, and what I see when Jetpack is deactivated.

<img width="461" alt="screenshot 2018-11-06 at 19 12 42" src="https://user-images.githubusercontent.com/426388/48084565-5ccedd00-e1f8-11e8-9f1f-d1c74b5c189a.png">

Setting `add_filter( 'jetpack_gutenberg', '__return_false' );` solves the problem, but deactivating the Markdown module does not.

**Comment by jeherve** [comment]
This seems to be limited to WP 5.0 Beta 3. It does not happen when using Gutenberg.

Related issue: #10548

**Comment by roccotripaldi** [comment]
We traced this to: https://github.com/Automattic/jetpack/blob/master/class.jetpack-gutenberg.php#L189

which is where we enqueue dependencies for our gutenpack script. 

This was likely a core issue, and it looks like it was resolved with the latest build ( 5.0-beta3-43878 )
Someone else was reporting a similar problem: https://core.trac.wordpress.org/ticket/45271

I tested on both jurassic.ninja and on my local docker env, and can confirm that the latest build fixed the issue for me. Can you verify too @jeherve ?

**Comment by jeherve** [comment]
It does indeed seem to be fixed now! Nice catch! Closing.
