### ISSUE TITLE
Settings: create a new settings tab for performance

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack#10550]
This issue is a placeholder to discuss creating a new tab in settings for Performance-related features like image and file CDN, lazy load, AMP (just a promotion), WPSC (just a promotion), and so forth. 

The tab would want to have a pre-amble at the top explaining our performance options and perhaps piloting an autopilot or turbo booster master switch.

**Comment by jeffgolenski** [comment]
@rickybanister can you clarify what you mean by the acronym "WPSC" in your comment above?

**Comment by jeffgolenski** [comment]
Note: This issues changes a large section of Jetpack's IA. we'll have to be strategic for updating this across our various jetpack platforms.

A "performance" section doesn't currently exist. We'll be grabbing sections from other areas and adding them altogether, here.

*** BEFORE ***

**wp-admin**
![screen shot 2018-12-06 at 2 05 57 pm](https://user-images.githubusercontent.com/214813/49606115-76cb1f00-f960-11e8-94ed-9335ec1fef6d.png)


**Calypso**
![screen shot 2018-12-06 at 2 05 32 pm](https://user-images.githubusercontent.com/214813/49606112-73379800-f960-11e8-8002-fdb26761d8f6.png)


**Mobile**
![photo dec 06 13 44 05](https://user-images.githubusercontent.com/214813/49606067-48e5da80-f960-11e8-966d-0c312319da73.png)


*** AFTER ***

**wp-admin**

Jetpack Free & Professional views


![jetpack free - wp-admin](https://user-images.githubusercontent.com/214813/49606216-c01b6e80-f960-11e8-9516-3940130e231d.png)
![jetpack pro - wp-admin](https://user-images.githubusercontent.com/214813/49606217-c01b6e80-f960-11e8-91fb-e63b15732d31.png)


**Calypso**

Jetpack Free & Professional views

![jetpack free - calypso](https://user-images.githubusercontent.com/214813/49606223-c7427c80-f960-11e8-9a21-c50069314cca.png)
![jetpack pro - calypso](https://user-images.githubusercontent.com/214813/49606224-c7427c80-f960-11e8-90b2-5f97de51c95d.png)


**Mobile**

![mobile - after](https://user-images.githubusercontent.com/214813/49606231-cb6e9a00-f960-11e8-8087-99ee670709c6.png)

cc @joanrho @keoshi @rickybanister @iamthomasbishop @SylvesterWilmott

**Comment by jeffgolenski** [comment]
@rickybanister There's a lot to going on here, I'd like to consider breaking these two into different issues:

1) The tab would want to have a pre-amble at the top explaining our performance options

Love that idea, but we should do it for all of the tabs - which I think we explored at one point. After we get this hefty issue tackled we can do that one. 

2) piloting an autopilot or turbo booster master switch.

This would be great for all settings areas as well.

**Comment by joanrho** [comment]
Thanks for sharing the mocks, @jeffgolenski! The new "Performance" section looks great. Few Qs:

1. What happened to the "General" tab?
2. In response to your numero uno pre-amble mention above, this already exists as an open issue (#10688) so you don't need to create a new one. We'll tackle all of them at once with Editorial's assistance.
3. What exactly do you mean by "piloting an autopilot or turbo booster master switch"? Sounds cool but i don't fully understand it...

**Comment by rickybanister** [comment]
@jeffgolenski WPSC is WP Super Cache, the caching plugin we maintain.

**Comment by jeherve** [comment]
@jeffgolenski I would have a few questions about the wp-admin part: 

- On your mockup the new "Performance" tab is the first. Until now the Writing tab was first and appeared as the default tab when someone would access `wp-admin/admin.php?page=jetpack#/settings`. Should we change it to Performance now?
- The AMP prompt is new. Could you give me more details about this?
    - The wording I should use.
    - The different states (AMP uninstalled, AMP installed)
    - Should it appear in development mode as well?
    - Where the link should bring us (I was thinking about `wp-admin/plugin-install.php?s=amp&tab=search&type=term`, but the first result there is not our plugin. We could load it in Calypso, at `https://wordpress.com/plugins/amp/siteurl`, but then we would have to provide a different link when in dev mode)

Thank you!

**Comment by jeffgolenski** [comment]
@jeherve Thanks for the follow up! Here are some answers for you...

1) Yes - let's give Performance a shot at being the first item listed in the settings navigation. We can restructure it later if we need to, but I think there's more value to show to customers there, than the writing tab at this point.

2) For the sake of time, let's forgo adding AMP to this area (same goes for WP Super Cache rick mentioned above as well). That prompt currently exists in the calypso UI. But I think we should spend a little more time about thinking how to add it to the context of the wp-admin. I'll create a new issue for that. 

Thanks Jer!

**Comment by jeffgolenski** [comment]
@joanrho Sorry I missed your questions!

> What happened to the "General" tab?

The general tab has never existed within the Jetpack dash inside /wp-admin/. Only in calypso. It will remain there in calypso, "performance" will come right after it.

> In response to your numero uno pre-amble mention above, this already exists as an open issue (#10688) so you don't need to create a new one. We'll tackle all of them at once with Editorial's assistance.

Yessa. I took this on before that issue. ✔️ 

> What exactly do you mean by "piloting an autopilot or turbo booster master switch"? Sounds cool but i don't fully understand it...

My guess is that @rickybanister means at the top of each section there would be a "master switch" to enable every feature in said category. Example: On the performance tab, up at the top near the the description, there would be a card with a toggle that would say "Enable all performance features," or something?

**Comment by jeffgolenski** [comment]
Issues for 
Calypso: https://github.com/Automattic/wp-calypso/issues/29545
Mobile: p4a5px-2jI

**Comment by joanrho** [comment]
@jeffgolenski @rickybanister thanks for clarifying! I love the idea of a "turn everything on" type of turbo boost master switch (😂) for each section in settings, but let's shelve that idea for improved onboarding. I'll open a separate issue for that so we don't forget.
