### ISSUE TITLE
Connection banner: add new Performance section

### ISSUE THREAD

**Issue by joanrho** [Automattic/jetpack#10563]
Introduce new Performance section in the disconnected connection banner that appears on the Plugins page and Jetpack Dashboard. Update copy to better align with updates made to the Jetpack.com homepage ([#](https://github.com/Automattic/jetpack-com/issues/96)).

ref: p1HpG7-5J1#comment-28364

**Comment by jeffgolenski** [comment]
This is done and in the plugin!

![screen shot 2018-12-06 at 11 49 30 am](https://user-images.githubusercontent.com/214813/49598790-652c4c00-f94d-11e8-9e34-3c427eee8b83.png)

**Comment by joanrho** [comment]
@jeffgolenski This isn't the right location, although that tabbed banner could use it to. If you refer to the linked P2 thread and scroll up to this comment, p1HpG7-5J1#comment-28306, this is referring to the full-screen banners that echo the jetpack.com homepage styles.

**Comment by joanrho** [comment]
Don't forget to add your updated design (just adding the Performance section) to #8618 as well, since we're waiting on Devs to build that out and they may as well include the new section whenever they get to it. Thanks!

**Comment by joanrho** [comment]
@jeherve Here's an updated mockup:

![disconnected full-screen banner](https://user-images.githubusercontent.com/204742/49661682-f8758800-fa06-11e8-9906-47caa42c7678.png)


### Image assets and copy to use:

asset: `/images/customize-theme.svg`
>**Design & Customization**
>Browse hundreds of professionally-designed WordPress themes to find the right one for your site.
>
>Customize your homepage, blog posts, sidebars, and widgets — all without touching any code.
>
>Seamlessly embed rich content and videos, deliver them all at high speed, and replace default search with an Elasticsearch-powered service.

—
asset: https://cloudup.com/cB59pL8UVZh (let's name this asset `jetpack-speed.svg`
>**Built-in Performance**
>Load pages faster, and serve your images and static files from our global network of servers.
>
>Improve your site speed and take control of your SEO with Jetpack’s site accelerator.
>
>Shorter load times can lead to happier readers, more page views, and — if you’re running a store — improved sales.

—
asset: `images/security.svg`
>**Security & Backups**
>Prevent unwanted intrusions with effective brute force attack protection, malware scanning, and spam filtering.
>
>Keep your site totally backed up in real-time with no storage limits and one-click restores.
>
>Get alerts about downtime instantly via email and push notifications in both your browser and the mobile app.

—
asset: `images/jetpack-performance.svg`
>**Effortless Marketing**
>Schedule social media promotion of your newest posts, pages, and products before they’re published.
>
>Keep visitors interested with automatic links to your related content, and monitor stats and notifications on the go with the WordPress mobile app.
>
>Grow your revenue with the WordPress ad program and simple payment buttons.
