### ISSUE TITLE
Gutenberg: Improve styles in Publicize connected modal in settings page

### ISSUE THREAD

**Issue by tyxla** [Automattic/jetpack#10573]
As @mapk suggested in pafL3P-7k-p2 #comment-489 and #comment-465 we should improve the styles of the modal that appears after connecting a Publicize service on the settings page.

**Comment by tyxla** [comment]
I'll unassign myself from this one, as IIRC @mapk was planning to work on it. However, I'll standby in case I can be of help with it - feel free to ping me if you need anything, Mark!

**Comment by tyxla** [comment]
This came up again in p1HpG7-5Ta-p2 - quoting @melchoyce:

---

This modal has some styling issues:

![](https://cldup.com/31n-9CPwVo.png)

1. It should be using the `notice-alt`, because it appears on a white background.
2. The notice should be left-aligned, not centered.
3. There doesn’t need to be a border under the X.
4. Instead of a checkbox and a confirmation button, it would be better to do something like:

> You have successfully connected your Twitter account with Jetpack.
> 
> Do you want to make this connection available to all users of this blog?
> [ Yes ] [ No ]

Where “Yes” is primary, and “no” is secondary. Or vice-versa, depending on what you want to encourage.

![](https://cldup.com/Y0udLI-7v7.png)

Alternately — forego the modal entirely, and do something like this:

![](https://cldup.com/lADgZDpOZq.png)

Alternately alternately, display within the appropriate connection section on the page:

![](https://cldup.com/5j9pEbd8mI.png)

**Comment by simison** [comment]
@jeherve @kraftbj this connect page is no more, right?

**Comment by jeherve** [comment]
You're right. Closing.
