### ISSUE TITLE
"Show related content after post" parameter needs to be divided into two separate ones

### ISSUE THREAD

**Issue by cawa-93** [Automattic/jetpack#10572]
#### Is your feature request related to a problem? Please describe.
I'm developing a theme that can independently display similar posts from jetpack. They can be downloaded from the REST API or displayed in the widget. However, for this purpose, I have to cancel the display of similar posts by the jetpack itself, deregister relevant scripts, etc. And for my users, it remains unclear why they should enable "Show related content after post" to display similar posts in the appropriate widget. Because if this option is disabled then the related posts will not be displayed even if you receive data from REST API.

#### Describe the solution you'd like
I believe that this parameter needs to be divided into two separate ones:
- "Enable related posts" — this global option will enable support for related posts, they will be displayed in the REST API, [jetpack-related-posts] shortcode and other.
-  "Show related content after post" — this option does the same thing now: registers a `related-posts.min.js` script, creates a block of related posts after the post...

**Comment by jeherve** [comment]
You should be able to solve this issue by manually removing the Related Posts like so:
https://jetpack.com/support/related-posts/customize-related-posts/#delete

To remove the scripts and styles, you can use `wp_dequeue_style`([#](https://developer.wordpress.org/reference/functions/wp_dequeue_style/)) and `wp_enqueue_script` ([#](https://developer.wordpress.org/reference/functions/wp_enqueue_script/)).

I hope this helps.

**Comment by cawa-93** [comment]
@jeherve Actually I described this problem:
First I must enable "Show related content after post"
Then I must then cancel this action
And only then I can display the related posts where I want.

If you split this option into two: one is responsible for maintaining the relevant posts, and the other directly for displaying after the post - it would be easier from the point of view of the developer and even from the user's point of view.

Currently, even if you refuse programming:
A regular user can not use ONLY Shortcode if they do not display related posts after the post.

**Comment by jeherve** [comment]
I think I understand what you mean, thanks for the extra details.

> First I must enable "Show related content after post"
> Then I must cancel this action
> And only then I can display the related posts where I want.

For the site owners using your theme, would that be an issue? They will not have to worry about 2) and 3) at all; they will enable Related Posts if they are interested in the feature, and your theme will add them to the posts right away, albeit in a custom location and with a custom design. If they do not want to use Related Posts anymore, they can disable the feature and it won't be displayed anymore.

Removing the default posts and adding custom ones will all be done for them by your theme, behind the scenes.

> If you split this option into two: one is responsible for maintaining the relevant posts, and the other directly for displaying after the post - it would be easier from the point of view of the developer and even from the user's point of view.

If we were to do that, it would make things more confusing for site owners who just want one thing: related posts. Why would they have to enable 2 different things to use one feature?

On your end as a developer, if we were to do this you would still have to do what you must do today:
- Check if Related Posts are available.
- Display them if they are.
- Check if some posts are added to the bottom of the post content. Whether this is done by default or via an additional option does not change anything for you imo; you will still have to check for that option and disable it if it is on.

Am I missing something here?

> A regular user can not use ONLY Shortcode if they do not display related posts after the post.

That should not be an issue today, as when you use the `[jetpack-related-posts]` shortcode in a post, we automatically stop displaying the related posts at the end of the post content. As a site owner, you can just start using the shortcode; you do not have to worry about anything else.
