### ISSUE TITLE
Photon: ensure compatibility with Block editor

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#10580]
#### Steps to reproduce the issue

 The issue is described in details here: https://github.com/WordPress/gutenberg/issues/8734

> The problem is related to the image_downsize filter, which is normally suppressed (in both Photon and ExactDN) by a call to is_admin(), but Gutenberg doesn't use admin-ajax, it uses the REST API, which doesn't send any signals about being in wp-admin.
> [...]
> Photon and ExactDN should pre-empt the parsing of image_downsize for the REST API when it is detected that the request is made from the editor.

**Comment by nosilver4u** [comment]
FYI, this now happens again for new uploads in the block editor, because $request['context'] is not set.
I'm using this:
`if ( is_string( $route ) && false !== strpos( $route, 'wp/v2/media' ) && ! empty( $request['post'] ) && ! empty( $request->get_file_params() ) )...`

**Comment by jeherve** [comment]
@nosilver4u Thanks for the comment. It just happened that #16035 was reported earlier today.
