### ISSUE TITLE
JITM: Enhancement: Hide if the module is activated already

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/jetpack#10588]
#### Steps to reproduce 

- Start with a WordPress.org site
- Install, activate and connect Jetpack to WordPress.com account
- Click on `Activate recommended modules` when show, as a part of the onboarding flow

#### What is expected 

The `Site accelerator` JITM is not shown, as the `Photon` module was activated as a part of the onboarding flow

#### What happens instead 

The `Site accelerator` JITM is not shown, and it can also be seen that the `Site accelerator` module is activated for images, but not static files.

#### Screenshots 

<img width="1281" alt="screenshot 2018-11-09 at 22 38 31" src="https://user-images.githubusercontent.com/18581859/48279026-57ca9180-e475-11e8-93a4-052ea5464320.png">
<div align="center"><sup>Image indicating that the `Site accelerator` module is activated</sup></div> 

<img width="1281" alt="screenshot 2018-11-09 at 22 38 34" src="https://user-images.githubusercontent.com/18581859/48279029-58632800-e475-11e8-8a8e-209e6f67fef8.png">
<div align="center"><sup>Image indicating that the JITM is shown, which could be removed if the module is activated</sup></div>

**Comment by jeherve** [comment]
I'll close that issue in favor of #9462.

> The Site accelerator JITM is not shown, as the Photon module was activated as a part of the onboarding flow

That JITM matches the other feature (Asset CDN), and won't be shown if that feature is active.
