### ISSUE TITLE
Improve Jetpack plans page in wp-admin

### ISSUE THREAD

**Issue by joanrho** [Automattic/jetpack#10582]
The Plans page in wp-admin > Jetpack Dashboard > Plans is very long and visually clunky. Screenshot: https://cloudup.com/ccKVlFXdwyJ

Let's update this view to reflect the changes we've made on the Calypso side in Plan > My Plan (with the feature cards) so items are easier to read/understand and are more actionable for users.

**Comment by jeherve** [comment]
Related: #10556
