### ISSUE TITLE
Improve new user modal experience in wp-admin

### ISSUE THREAD

**Issue by joanrho** [Automattic/jetpack#10584]
We need to improve the new user modal experience that they encounter when navigating to wp-admin > Jetpack Dashboard. Having one full-screen modal immediately followed by another feels spammy and hasn't proven to be beneficial in any way during our in-person user research sessions. The second modal won't be necessary if we update the Plans view to align more with the Calypso Plan > My Plan page (related issue: #10582 ).

Details:

Screenshots: https://cloudup.com/clvKhRoLi-U

**First full-screen modal** (aka Jumpstart): "Your Jetpack site is ready to go!" 
with a card listing out recommended features and a CTA prompting me to [Activate recommended features].

After clicking "Activate recommended features", a notice appears in the upper right (Activating recommended features), and then the screen is replaced by another full-screen modal.

**Second full-screen modal** :  "Your Jetpack Premium plan is powering up!" 
with a card describing customization (themes, video hosting), social sharing tools, scheduled posting, toggles for automated social sharing and ads and VideoPress, and a security section describing backups and scans with toggles for site downtime notifications, suspicious sign-in blocking, and backups/scans/automatic fixes. There's also a small section at the bottom of the popover that links to "Monetize your site with ads". 

I have to close out of this second modal to finally get back to the regular Jetpack Dashboard view.

**Comment by joanrho** [comment]
Explore JITMs in place of modals for a less disruptive and more contextually relevant experience.

ref: p6TEKc-2pR#comment-5477

**Comment by keoshi** [comment]
My suggestion is that we lose the jumpstart modal:

- It is less important than welcoming the user to their correct plan.
- The current IA is a mess, and makes it super easy to dismiss.
- Its goal is easily accomplished by a button at any time in their NUX (even before or after activating plan-specific features).

In that sense, this is my proposal to move forward with one less modal:

- Use a banner instead; this could live in At a Glance, My Plan, Plans, etc. until it's acted upon.
- Use it for a super quick intro but highlight the recommended features.
- Link the learn more link to https://jetpack.com/support/quick-start-guide/#jumpstart
- Keep the illustration.

![jumpstart-banner](https://user-images.githubusercontent.com/390760/49746385-fc203d80-fc98-11e8-9daa-98ebbd77e9a2.png)

**Comment by jeherve** [comment]
> Use a banner instead; this could live in At a Glance, My Plan, Plans, etc. until it's acted upon.

Noting that "My Plan" is currently targetting folks with a plan; we would have to make it useful to folks with a free plan as well; that new banner definitely seems useful.

**Comment by keoshi** [comment]
> Noting that "My Plan" is currently targetting folks with a plan; we would have to make it useful to folks with a free plan as well

So true, we should definitely address that in this project.

**Comment by keoshi** [comment]
Actually, the “My Plan“ page has conditionals to show free plan content and promo material:

![image](https://user-images.githubusercontent.com/390760/49747287-06433b80-fc9b-11e8-8fdb-0478fdef9b03.png)

**Comment by jeherve** [comment]
Should we stop working on other issues impacting Jumpstart and focus on this issue instead then? There are other issues in this project offering changes to the Jumpstart modal, but maybe those are not necessary anymore?

**Comment by keoshi** [comment]
Let's check with @joanrho to see what she says about this solution before committing to it and abandoning all other jumpstart issues.

**Comment by keoshi** [comment]
Joan said we should pursue this instead! Let's lose the modal.

**Comment by jeherve** [comment]
Ok! Should I update #10888 to only update the wording of the modal in the Plugins page so we can merge those changes, and then work on that new card in "My Plan" in a new PR?

Could you give me the text I can use in that new card?

**Comment by keoshi** [comment]
@jeherve Details are here: https://github.com/Automattic/jetpack/issues/10584#issuecomment-445880005 and IMO we should have this banner show up in all views until it's either dismissed or customers activate the recommended features.

I don't know if that invalidates the work you did on #10888 because we're talking about different stages in the flow here (pre vs post connection) — what are your thoughts?

**Comment by jeherve** [comment]
> I don't know if that invalidates the work you did on #10888 because we're talking about different stages in the flow here (pre vs post connection) — what are your thoughts?

Yes, that makes total sense! I'll get started on this then. 👍 	

> we should have this banner show up in all views until it's either dismissed or customers activate the recommended features.

I like the idea 👍
