### ISSUE TITLE
 Twitter auto embedding breaks if user name starts and ends with an underscore 

### ISSUE THREAD

**Issue by edent** [Automattic/jetpack#10595]
#### Steps to reproduce the issue

1.  Try to embed a Tweet where the user's name starts and ends with `_`
1.   For example `https://twitter.com/_sagesharp_/status/1061094348152918017`
1.  The text is rendered as `https://twitter.com/<em>sagesharp</em>/status/1061094348152918017` rather than an oembed.
1.  The JetPack MarkDown processor is incorrectly interpreting the underscores in a URL as being valid MarkDown. 

Tried on a fresh install of 4.9.8, with only JetPack installed, MarkDown editing switched on, and using the classic editor.

This works fine for embedding `[tweet 1061094348152918017]`

#### What I expected
The tweet should OEmbed as per usual.

#### What happened instead
The underscores in the name get treated as MarkDown.  The resultant URL is not properly parsed.

**Screenshots**
MarkDown in classic editor:

![screenshot at 2018-11-10 12-27-12](https://user-images.githubusercontent.com/837136/48301697-bdf0fc00-e4e9-11e8-853a-95a7e92169f1.png) 

The first link is rendered incorrectly but the second one works:
![screenshot at 2018-11-10 12-27-56](https://user-images.githubusercontent.com/837136/48301696-bdf0fc00-e4e9-11e8-9bc8-68dd924ea95e.png)

**Comment by edent** [comment]
This was originally raised as https://core.trac.wordpress.org/ticket/45324 - but I was told to reassign it here.

**Comment by edent** [comment]
This is still an issue. It affects the classic editor.  Here is a reproducible test case:

```
This Tweet does not embed:

https://twitter.com/_sagesharp_/status/1061094348152918017

This Tweet works:

[tweet 1061094348152918017]
```

**Comment by edent** [comment]
Coming up on the 2 year anniversary of this bug report. The markdown parser is still broken with some embeds. Can someone please help me find the code responsible and I'll try and file a PR.

**Comment by jeherve** [comment]
> Can someone please help me find the code responsible and I'll try and file a PR.

We may have to add an exception here:
https://github.com/Automattic/jetpack/blob/ad6ddac5d214dfad14f1caafa1945b89bb26a2da/_inc/lib/markdown/gfm.php#L85-L92

**Comment by edent** [comment]
Anything I can do to help this along?

**Comment by jeherve** [comment]
Sorry this fell off my radar. I'll aim to revisit this in the next few weeks.
