### ISSUE TITLE
Sites Listing in Network Admin needs Search Capability

### ISSUE THREAD

**Issue by mrjarbenne** [Automattic/jetpack#1060]
In situations where you have a large number of sites on a Multisite network, and Jetpack is being selectively activated from the Network admin panel, the ability to search for a site is critical so that admin don't have to search through hundreds of pages to enable Jetpack from the network admin menu.

![2014-08-29_09-56-19](https://cloud.githubusercontent.com/assets/480667/4091062/7e33899e-2f84-11e4-95b9-c208403749a0.png)

Note that in the core Sites menu this functionality already exists and could potentially be ported over:

![2014-08-29_09-57-04](https://cloud.githubusercontent.com/assets/480667/4091081/b723405a-2f84-11e4-8062-787c9841f930.png)

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
