### ISSUE TITLE
Jetpack rewind created both wp_152978617... and wp_... tables

### ISSUE THREAD

**Issue by kosiew** [Automattic/jetpack#10608]
User rewound site and thereafter reported that they could not invite an email to their site although the email was not in the People list. 

On investigation, found that there are both wp_152978617_users and wp_users tables. There were a lot of other wp_xxx tables too.

An AA has deleted the unexpected the tables already but please investigate whether this is rewind gone wrong.

#### Steps to reproduce the issue

N/A

#### What I expected

Emails not in People list can be invited.

#### What happened instead
This particular email which was not in the People list could not be invited.

**Screenshots**

**Comment by kosiew** [comment]
![double-tables](https://user-images.githubusercontent.com/29057562/48408767-1c7dda80-e775-11e8-8f10-fb42fd3c04a9.png)
Screenshot of double tables.

**Comment by jeherve** [comment]
Closing in favour of 3084-gh-jpop-issues
