### ISSUE TITLE
Need a Revoke access button after an invitation is accepted

### ISSUE THREAD

**Issue by sandeepmondal** [Automattic/jetpack#10618]
I am the admin of a blog running on WordPress.org. Bought a Jetpack subscription and have connected my site with WordPress.com. There are numbers of authors in my site, and for them, I have created their WordPress.com profile with the same email id they have on the main website. I have sent invitations to them to connect the site in their WordPress.com. Now, until they are accepting the request, there is a revoke access option that the admin can remove the invitation anytime. But the point is - when they have accepted, and they have connected with the site an admin cannot remove an invited user. Suppose that user only have the access from WordPress.com to the site and he is occurring any activity harmful to the website or the blog or the company. The admin cannot remove the user access from the site instantly for security reason.

There should be a revoke access option button from admin side and a super admin profile like WordPress.org that he can easily remove other admins, authors or any lower label user profiles to stop the vulnerability.

**Comment by jeherve** [comment]
I am not quite sure I understand. Could you give us more details about what you are trying to accomplish?

- What is the role of those users on your site? You can see that role under Users > All Users in your dashboard.
- When you say you would like to "revoke their invitation", what would you like to happen to those users? Would you like to keep their account on your site, but change to a different role? If so, which one?
