### ISSUE TITLE
Gutenpack Messaging: Adding copy about Gutenpack to the post-activation welcome modal

### ISSUE THREAD

**Issue by mapk** [Automattic/jetpack#10638]
To get ready for the release of Gutenberg blocks within Jetpack, we'd like to start adding msging where we can to inform our users that we have blocks now. One such place is on the _post-activation welcome modal_.

I've updated the **"Design & Customization"** section to talk a bit about Gutenberg and updated the illustration as well.

@jeffgolenski @keoshi - I believe this is your creation, so would love some thoughts on it.
@michelleweber - I'd like to get a review of the copy as well. 

![04-welcome](https://user-images.githubusercontent.com/617986/48575443-cc169200-e8c6-11e8-81ff-dfb346eab320.png)

**Comment by jeffgolenski** [comment]
I dig it @mapk . Did you also try an exploration with Gutenberg in the title? I know that's definitely a hype-word right now and anywhere we can use it to grab attention, the better.

**Comment by keoshi** [comment]
Looking great, @mapk! I don't know that everyone recognizes the “Gutenberg” name, and I wonder if we should go for “Publish” or something like that, since every other intro is a call-to-action of some sort as well (“Design”, “Optimize”, “Promote”).

**Comment by mapk** [comment]
Thanks folks! I'm going to follow WPCOM's lead here. If they're not referring to it as Gutenberg, I think, for consistency sake, and stronger clarity, we call it the "new editor" as well. 

I'll try to rework this messaging into my flows.

**Comment by mapk** [comment]
I've updated the wording a bit to reflect the "new WordPress editor" and still managed to drop the "Gutenberg" name as well. I've also changed the first word of the paragraph from "Gutenberg" to "Customize" in response to @keoshi's comment above.

![welcome-v2](https://user-images.githubusercontent.com/617986/48649255-e3c54780-e9a6-11e8-87df-8d130a9cb818.png)

**Comment by mapk** [comment]
@davidakennedy  brought up a good point that users may not know what blocks are quite yet. So maybe we ditch that last sentence under "customization" for this instead?

"Get more customization options for Jetpack features all from right within the new editor."

**Comment by jeffgolenski** [comment]
@mapk the update is looking good to me, and I concur with

> "Get more customization options for Jetpack features all from right within the new editor."

But can we say "new WordPress editor" so folks new to the ecosystem don't think the editor is a Jetpack production? Just a tiny detail.

**Comment by mapk** [comment]
Alrighty, I've updated the text. @jeffgolenski @michelleweber @davidakennedy 

![updated-text](https://user-images.githubusercontent.com/617986/48731703-87eefe80-ebf2-11e8-9440-134df6247627.png)

**Comment by michelleweber** [comment]
The smallest change: can we say "JP features right in the new editor"? A wee bit snappier.

**Comment by mapk** [comment]
> The smallest change: can we say "JP features right in the new editor"? A wee bit snappier.

Made the change, but I kept the "new WordPress Editor" in response to Jeff's point earlier. 

![screen shot 2018-11-19 at 1 56 16 pm](https://user-images.githubusercontent.com/617986/48737482-005dbb80-ec03-11e8-85b5-4eff62696ab2.png)

**Comment by jeherve** [comment]
Fixed in #10672
