### ISSUE TITLE
CDN: Requests fail for unreleased versions

### ISSUE THREAD

**Issue by sirreal** [Automattic/jetpack#10633]
#### Steps to reproduce the issue

1. Create a new development site from `master` (for example with Jetpack Docker)
2. Enable the Asset CDN module
3. Try to use Jetpack Admin or other things that depend on Jetpack CDN files – `/wp-admin/admin.php?page=jetpack#/settings`
4. 💥 Broken pages. You'll see a lot of 404 requests

The CDN seems to naively CDNify requests for a version of Jetpack that's unavailable.

```
admin.php?page=jetpack:104 GET https://c0.wp.com/p/jetpack/6.8-alpha/_inc/build/style.min.css net::ERR_ABORTED 404
admin.php?page=jetpack:70 GET https://c0.wp.com/p/jetpack/6.8-alpha/_inc/build/admin.dops-style.css net::ERR_ABORTED 404
admin.php?page=jetpack:296 GET https://c0.wp.com/p/jetpack/6.8-alpha/modules/widgets/social-icons/social-icons-admin.js net::ERR_ABORTED 404
admin.php?page=jetpack:290 GET https://c0.wp.com/p/jetpack/6.8-alpha/modules/masterbar/tracks-events.js net::ERR_ABORTED 404
admin.php?page=jetpack:67 GET https://c0.wp.com/p/jetpack/6.8-alpha/css/jetpack-admin-jitm.css net::ERR_ABORTED 404
admin.php?page=jetpack:66 GET https://c0.wp.com/p/jetpack/6.8-alpha/css/jetpack-icons.min.css net::ERR_ABORTED 404
admin.php?page=jetpack:63 GET https://c0.wp.com/p/jetpack/6.8-alpha/modules/masterbar/overrides.css net::ERR_ABORTED 404
admin.php?page=jetpack:289 GET https://c0.wp.com/p/jetpack/6.8-alpha/_inc/accessible-focus.js net::ERR_ABORTED 404
admin.php?page=jetpack:68 GET https://c0.wp.com/p/jetpack/6.8-alpha/_inc/genericons/genericons/genericons.css net::ERR_ABORTED 404
admin.php?page=jetpack:69 GET https://c0.wp.com/p/jetpack/6.8-alpha/css/jetpack-admin.css net::ERR_ABORTED 404
admin.php?page=jetpack:65 GET https://c0.wp.com/p/jetpack/6.8-alpha/modules/widgets/social-icons/social-icons-admin.css 
```

#### What I expected

Things work.

#### What happened instead

Things broke.

**Screenshots**

![screen shot 2018-11-15 at 12 33 06](https://user-images.githubusercontent.com/841763/48550308-ac856680-e8d2-11e8-8dbf-ed7806b68833.png)
![screen shot 2018-11-15 at 12 32 23](https://user-images.githubusercontent.com/841763/48550309-ac856680-e8d2-11e8-93b2-fb550a2b6a72.png)

**Comment by jeherve** [comment]
That's to be expected, as there is no 6.8-alpha version of Jetpack in the SVN repository, which is where the CDN pulls its files from. On your development environment, I would recommend that you use the following filter to force the feature to not impact your files:
`add_filter( 'jetpack_force_disable_site_accelerator', '__return_true' );`

**Comment by jeherve** [comment]
This should help making sure this won't happen again without having to use a filter.
#10647

**Comment by sirreal** [comment]
I was hoping for a solution more along those lines, thanks @jeherve 🙌
