### ISSUE TITLE
Post-purchase banner: make it easier to dismiss

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack#10657]
Our post-upgrade banner is helpful in explaining just what you purchased, but if you don't scroll down or click the small gray 'x' in the corner you can get stuck.

![image](https://user-images.githubusercontent.com/437258/48641655-7c0ffc00-e9a8-11e8-9a99-c94b2844745e.png)

Instead we should have a call to action button at the top of this screen that says 'get started' that also dismisses the banner.

We could also consider allowing folks to click on the background to dismiss it, but that seems less effective.

p6TEKc-2pR-p2

**Comment by keoshi** [comment]
> We could also consider allowing folks to click on the background to dismiss it, but that seems less effective.

Confirmed this is already the case.

**Comment by joanrho** [comment]
Since both clicking the X in the upper right of the modal OR clicking anywhere in the background dismisses the modal (standard modal behavior), I don't think the CTA is necessary.

**Comment by rickybanister** [comment]
@joanrho did you read the original thread linked in the issue? The customer didn't know the modal was easily dismissed and felt their plan or jetpack in general was broken. 

My hope for this issue is that we could provide a CTA that says 'get started' or something and then further address the modal issue in the future by working to make these kinds of messages in the page, vs on top of the content.
