### ISSUE TITLE
Gutenpack Messaging: Adding copy about Gutenpack to the post-update modal

### ISSUE THREAD

**Issue by mapk** [Automattic/jetpack#10658]
After a user updates Jetpack they are presented with a warm-update modal. We need to create an update talking about our new blocks.

**Proposed update for Gutenpack**

![post-update-modal](https://user-images.githubusercontent.com/617986/48647804-f8eba780-e9a1-11e8-9227-c0259125ec9d.png)

**Comment by michelleweber** [comment]
In sentence, you don't need to capitalize "new" or "editor" -- it's not a proper name, it's just a description. (Related: do we need to mention "Gutenberg" at all here, if it's not a term they'll ever really run into again?) I think you could also use a "learn more" link to info on the new editor and how it works.

Re: the actual substance of the modal, I sort of want to rephrase things a little, if it works for you:

> New in Jetpack!
> The features you rely on, adapted for the new WordPress editor. (A new editor? Yes! Learn more.)
> 
> Build your Jetpack site with blocks
> Today, we're introducing the first wave of Jetpack-specific blocks built specifically for the new editor experience: payment buttons, contact forms, maps, and markdown.

**Comment by jeffgolenski** [comment]
@mapk Looks great and reads very simply. I'm a fan. 

My only gripe is that after this, how is a customer supposed to get to this feature? Should we split the CTAs into two parts? "Take me to the editor" button being the primary so they can try it, and "Okay, got it!" being the secondary button that dismissed the notice?

**Comment by mapk** [comment]
@michelleweber & @jeffgolenski 

I've updated the mockup with your suggestions.

![post-update-modal v2](https://user-images.githubusercontent.com/617986/48731481-fa131380-ebf1-11e8-9f08-41e0396d0905.png)

**Comment by mapk** [comment]
@roccotripaldi Here are the two assets for this modal when you're ready for them.

https://cloudup.com/cxub1392z38

Also, now that we're including the "Take me to the new editor" button at the bottom, let's drop the `(a new editor? Yes! Learn more.)` text. I'm not sure where that link would go anyways.

**Comment by jeffgolenski** [comment]
@mapk That's what's up! I like that a lot. Let's just make sure we get some tracks data points built into those two buttons so we can monitor how folks use them as well!

**Comment by simison** [comment]
Neat! Love it.

> Take me to the new editor

What should happen if the user is using Classic plugin or hasn't updated to 5.0 when they upgrade Jetpack?

**Comment by jeherve** [comment]
Fixed in #10672

**Comment by jeherve** [comment]
> What should happen if the user is using Classic plugin or hasn't updated to 5.0 when they upgrade Jetpack?

While we do not handle the classic editor plugin (yet), we do offer the option to upgrade to those who are not running WP 5.0 yet.
