### ISSUE TITLE
Blocks: View assets inconsistently enqueued in editor

### ISSUE THREAD

**Issue by sirreal** [Automattic/jetpack#10665]
While looking at https://github.com/Automattic/jetpack/pull/10641#discussion_r234349085, I noticed that view assets are not enqueued in the editor if the block is not in the page when the editor loads.

If blocks in the editor expect their view assets to be present, we need to make sure they are.

#### Steps to reproduce the issue

1. Set up and connect a new Jetpack site with Gutenberg and the beta blocks.
2. Open the Gutenberg editor.
3. Add a map block. Note that the map view assets are not present.
4. Save the draft and refresh. Note that now the view assets are enqueued for the map block that was in the post when loaded.

The map block is an unusual example because it doesn't actually want the view assets in the editor, however it highlights the inconsistency which may be problematic.

#### What I expected

When a block is in the editor, its assets should consistently be available.

#### What happened instead

When inserted, the view assets are missing. When loaded as a saved post in the editor, they are present.

cc: @Automattic/poseidon @Automattic/luna @jeffersonrabb

**Comment by roccotripaldi** [comment]
Would it be a viable solution to never load view assets in the editor?
Are there blocks that need view assets in the editor?

**Comment by simison** [comment]
>Would it be a viable solution to never load view assets in the editor?

It would make things easier with Maps and Tiled Gallery block for now.

**Comment by sirreal** [comment]
I'm also inclined to think that editor scripts can `import` what they need when and if they need it. Seems like simply removing auto-enqueue of view assets from the editor is a good solution.
