### ISSUE TITLE
Sharing on wp-admin: Facebook: Unable to add new accounts

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/jetpack#10666]
#### Steps to reproduce 

- Setup a Jetpack site and activate `Publicize` module on it
- Visit `{example.com}/wp-admin/options-general.php?page=sharing`
- Connect a Facebook page
- Click `Add new` to connect another Facebook page

#### What is expected 

I am able to connect a new Facebook account as in the case of https://wordpress.com/sharing

#### What happens instead 

The page refreshes and shows the same Facebook account's pages as a list. There is no way to connect a new Facebook account.

![screenshot 2018-11-19 at 20 43 23](https://user-images.githubusercontent.com/18581859/48715773-cb218f80-ec3b-11e8-9279-5eb1e8b73c2a.png)

I have tested this against Twitter, Google+ and LinkedIn but those look to be good. 👍🏽 

I haven't tested with Tumblr though.

**Comment by jeherve** [comment]
That is to be expected. You cannot connect multiple Facebook accounts to a single WordPress site:
https://jetpack.com/support/publicize/facebook/#multiple-pages

**Comment by torres126** [comment]
Automattic/wp-calypso#30423
