### ISSUE TITLE
Jetpack Social Widget: Documentation Update

### ISSUE THREAD

**Issue by andpiazza** [Automattic/jetpack#10661]
#### Steps to reproduce the issue
1. Go to Existing documentation on [Social Media Icons](https://jetpack.com/support/extra-sidebar-widgets/social-media-icons/): https://jetpack.com/support/extra-sidebar-widgets/social-media-icons/

#### What I expected

- To read information on how to setup Jetpack's current Social Widget.
- To read on "Troubleshooting" 
. how to configure the new social widget icons using Social Logos via CSS
. how to use the alternate [Social Logos icons available](https://wpcalypso.wordpress.com/devdocs/design/social-logos) such as Twitter, Google Plus, Facebook, Pinterest, Tumblr on jetpack's social widget 
. since Social Logos are implemented via SVG, how to properly dequeue it and enqueue another set of icons (such as [Genericons Neue](https://github.com/Automattic/genericons-neue), which has a much broader set of icons) for usage with Jetpack's social widget

#### What happened instead
Existing Documentation on the Social Widget reflects Genericons (deprecated a while ago in favor of [Social Logos](https://github.com/Automattic/social-logos).)

**Comment by jeherve** [comment]
We'll update our documentation to match the new widget 👍 	

cc @danjjohnson
