### ISSUE TITLE
Social Menu & Social Media Icons: Add Whatsapp Support

### ISSUE THREAD

**Issue by andpiazza** [Automattic/jetpack#10663]
#### Steps to reproduce the issue
1. Go to Social Icon widget
2. Add URL for WhatsApp (starting _https://web.whatsapp.com/_ or _https://api.whatsapp.com/_)
3. Click on Save

#### What I expected
When URL starts with the following patterns:
1. https://web.whatsapp.com/
2. https://api.whatsapp.com/
widget would exhibit the WhatsApp icon

#### What happened instead
Widget shows chain icon (generic)

**Comment by jeherve** [comment]
The widget does not support Whatsapp yet.

**Comment by jeremypaavola** [comment]
1755826-zen

**Comment by donalirl** [comment]
I want to note here that you can create a public WhatsApp link using this format https://wa.me/15551234567 (replace 15551234567 with your cell number). 

This is useful for people who want to add a link to WhatsApp as one of their social icons, though we do not support the icon itself yet. It would be great if it could be recognized with the https://wa.me/ URL as well.

This came up in #11913124-hc

**Comment by donalirl** [comment]
WhatsApp has more users than most of our currently-supported icons. I'm removing the stale label in the hopes that this will be worked on soon.

**Comment by lakellie** [comment]
Received a request to add the WhatsApp icon from a user in 16512296-hc

**Comment by nielslange** [comment]
Another report on https://github.com/Automattic/themes/issues/1736

**Comment by JaviRpo** [comment]
is there any workaround?

**Comment by jeherve** [comment]
@JaviRpo There are no workarounds yet. We'll update this issue once we make progress on this.

**Comment by anaemnesis** [comment]
Not yet stalebot

**Comment by kathrynwp** [comment]
Requested again in 23400366-hc

**Comment by katiebethbrown** [comment]
Requested in 23442316-hc

**Comment by asheliza29** [comment]
Requested again in 3310731-zen

**Comment by fashuvo** [comment]
Another request in 3438829-zen
