### ISSUE TITLE
Top Posts & Pages Widget

### ISSUE THREAD

**Issue by dancaragea** [Automattic/jetpack#10660]
Top Posts & Pages Widget is used on many sites and blogs. But unfortunately it also leads some performance problems.
For example, PageSpeed Score from GTmetrix is very low for „Combine images using CSS sprites” because all images (from maximum 10 posts) do not meet this requirement – they are automatically resized – and „Remove query strings from static resources” where same resources (images) contain a “?” in the URL.
Please consider these things and eliminate them to meet those requirements.
I’m convinced that any uses this widget, so appreciated and used, will see an improvement in performance and page load times.
Thanks in advance.

**Comment by jeherve** [comment]
> „Combine images using CSS sprites” 

I am afraid this is not something that can easily be implemented. To do so, we would have to create sprite images on the fly, thus causing other performance issues.

> „Remove query strings from static resources” where same resources (images) contain a “?” in the URL.

This is a warning you can safely ignore. You can read more about it here:
https://github.com/Automattic/jetpack/issues/5618#issuecomment-264022916
