### ISSUE TITLE
Connection banner: introduce paid plans in pre-connection banner

### ISSUE THREAD

**Issue by joanrho** [Automattic/jetpack#10683]
Introduce and highlight value of paid plans in the pre-connection banner upfront.

ref: p6TEKc-2m8-p2 (RB / item 5.1)

**Comment by jeffgolenski** [comment]
Before:
![screen shot 2018-12-05 at 5 22 33 pm](https://user-images.githubusercontent.com/214813/49548017-62304d80-f8b2-11e8-9dde-2c174c96c353.png)

**Comment by jeffgolenski** [comment]
After:

Last tab (see me for CR data here)
![connection-banner-plans](https://user-images.githubusercontent.com/214813/49550249-f69dae80-f8b8-11e8-9850-44301e94b707.png)

Text:

Tab: "Premium Services"

Powerful premium services for your WordPress site


Whether you're a hobbyist or a large organization, Jetpack paid plans offer even more powerful performance, security, and revenue tools to help you keep your site safe, fast, and generate income.
* Real-time automated backups & malware scanning - if your site gets hacked, we’ve got your back
* Ad network - Automatic approval for placing and making money from ads on your site
* Simple payment buttons - Add products to your site and accept payments via PayPal instantly
* Enhanced search - A faster, more relevant search tool for WordPress
* Priority support & concierge setup - Expedited support from our WordPress experts & a one-to-one session to max your value with Jetpack
* Setup Jetpack to get started or visit our site for the full feature list.
