### ISSUE TITLE
Settings: Add headers to each section to explain each section's theme

### ISSUE THREAD

**Issue by joanrho** [Automattic/jetpack#10688]
The entire settings sections don’t have headers that explain why users should care about something like ‘Writing enhancements’. Let's add headers that help explain the theme of the settings below.

ref: p6TEKc-2m8-p2 (RB / item 5.13)

**Comment by jeffgolenski** [comment]
related project: https://github.com/orgs/Automattic/projects/28

**Comment by jeffgolenski** [comment]
@joanrho Are you thinking of something like this for each section?

![screen shot 2018-12-07 at 1 48 58 pm](https://user-images.githubusercontent.com/214813/49666731-f6bbbc80-fa26-11e8-81ec-fbed780d6d7b.png)

**Comment by joanrho** [comment]
@jeffgolenski Yes, that looks perfect! Thank u, Jeff.

**Comment by keoshi** [comment]
@joanrho I searched around and doesn't seem like we have copy for these yet. Did you start a Gdoc, or should I come up with something and ping Editorial for input? Thanks!
