### ISSUE TITLE
Jumpstart: offer users option to explore settings on their own

### ISSUE THREAD

**Issue by joanrho** [Automattic/jetpack#10686]
We don't offer a way for users to access settings from the Jumpstart modal. Users have to agree to turn on half of Jetpack without knowing what it does. Jumpstart can be improved further as part of our "[improving the modal experience](https://github.com/Automattic/jetpack/issues/10584)" effort, but a smaller and quicker fix would be to offer an "or explore settings yourself" option.

ref: p6TEKc-2m8-p2 (RB / item 5.2)

**Comment by jeffgolenski** [comment]
See also: Adding relevant changes to woo onboarding wizard.

**Comment by jeffgolenski** [comment]
Before: 
![screen shot 2018-12-05 at 4 54 47 pm](https://user-images.githubusercontent.com/214813/49546583-96a20a80-f8ae-11e8-885f-0f36e5a8d5e5.png)

**Comment by jeffgolenski** [comment]
After:
![screen shot 2018-12-05 at 5 07 04 pm](https://user-images.githubusercontent.com/214813/49547334-678c9880-f8b0-11e8-9301-d1e499b4c421.png)

**Comment by jeffgolenski** [comment]
Also thinking the link should say "Skip and explore features" - sounds a lot more attractive than "Settings"

**Comment by joanrho** [comment]
How about a simple "Skip for now"? It's a widely used and familiar way of dismissing feature activation modals like this.
