### ISSUE TITLE
Settings: add actionable cards to activated modules

### ISSUE THREAD

**Issue by joanrho** [Automattic/jetpack#10690]
Activating settings doesn't provide any actionable next steps for users. 

For example, we should have an "add a testimonial" clickable card appear below that setting once it is turned on. Or something like ‘customize your widgets’ if you enable a widget. We already do this for the Search setting, which adds an italic line of text and a link to "add the Jetpack Search widget to your sidebar".

ref: p6TEKc-2m8-p2 (RB / item 5.15)

**Comment by joanrho** [comment]
**Proposed solution:**

When a feature like Testimonials is activated, add a compact card with text that reads "Add a testimonial" that links to the new Testimonials section. This will help users get started with using the features they have just activated. Development help will be needed to add the compact card and set up the conditional logic for this (compact card hidden when module deactivated, compact card shown when module activated).

BEFORE:
<img width="1394" alt="before" src="https://user-images.githubusercontent.com/204742/49408948-ca006000-f71b-11e8-87fe-31d89a85fca9.png">

AFTER:
<img width="1387" alt="after" src="https://user-images.githubusercontent.com/204742/49408954-d1276e00-f71b-11e8-8da2-5403687f4709.png">

**Comment by oskosk** [comment]
@joanrho these screenshots show Calypso, just to confirm, this same actionable card should be present in the Jetpack settings page on wp-admin right ?
