### ISSUE TITLE
Calypsoify: module build keeps building on top of itself

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#10697]
#### Steps to reproduce the issue

1. Start from a fresh checkout of Jetpack.
2. Run `gulp sass:calypsoify`. Notice that the .css files get built.
3. Run it again. More files get built.
4. If you happen to be building the plugin multiple times, it can get pretty messy:

<img width="520" alt="screenshot 2018-11-21 at 9 42 05" src="https://user-images.githubusercontent.com/426388/48829135-d4147d00-ed71-11e8-8e2d-bc0eaec84159.png">

**Comment by georgestephanis** [comment]
I think this should have been resolved by #10631 ?  Will give it another test to see.
