### ISSUE TITLE
Publicize: Consider Facebook profile connection as connection error

### ISSUE THREAD

**Issue by tyxla** [Automattic/jetpack#10703]
As discussed in pafL3P-7k-p2 and p1HpG7-5Ta-p2 we need to update the Publicize connection endpoints to properly indicate that Facebook connection has an error when a page hasn't been selected.

cc @mdawaffe

**Comment by jeherve** [comment]
Can we ship without this, or is it a blocker for the initial release?

**Comment by tyxla** [comment]
I don't think it's a blocker. It's not ideal and we should fix it, but it is not a deal breaker IMHO. @mapk @MichaelArestad what do you think?

**Comment by MichaelArestad** [comment]
Not a blocker, but we need to do this in Phase 2.

**Comment by tyxla** [comment]
We're taking care of this one as part of https://github.com/Automattic/wp-calypso/pull/29352
