### ISSUE TITLE
CSP issues - remove inline scripts

### ISSUE THREAD

**Issue by omerlh** [Automattic/jetpack#10707]
#### Is your feature request related to a problem? Please describe.
Yes, I tried to enable [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) on my WordPress site. One of the things I wanted to block with CSP is inline scripts. To my surprise, I find out the JetPack add a lot of inline scripts. For example:
```
     <script>
	document.documentElement.classList.add(
		'jetpack-lazy-images-js-enabled'
	);
    </script>
```
I had to allow inline scripting in the policy so my site will keep working with the plugin.
#### Describe the solution you'd like
Use regular JS files instead of inline scripting.

#### Describe alternatives you've considered
Adding specific hashes for each one of the inline scripts (see it [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Sources), down the list). This was not easy to go over all the scripts and might break on future releases.

**Comment by jeherve** [comment]
Thanks for your contribution.

Jetpack does indeed use inline scripts. It is common practice when working with WordPress, and WordPress makes it possible via the `wp_add_inline_script` function:
https://developer.wordpress.org/reference/functions/wp_add_inline_script/

WordPress itself does this in many areas, and you can see this when looking at your site's dashboard.

For this reason, implementing CSP in WordPress may prove difficult, as you found out. You can read more about it [here](https://walterebert.com/blog/using-csp-wordpress/) and [here for a detailed process](https://colorblindprogramming.com/implementing-csp-wordpress). Some [plugins](https://wordpress.org/plugins/wp-content-security-policy/) can be used to help you with that process.

You can get an idea of where inline scripts are used in Jetpack by searching for this function in the codebase:
https://github.com/Automattic/jetpack/search?q=wp_add_inline_script&unscoped_q=wp_add_inline_script

We may be able to remove some of those inline scripts in the future, but this may not be possible everywhere without impacting performance. We'll consider it for each change that can be done.

**Comment by omerlh** [comment]
Thank you for the detailed response :) I'm aware to the plugins and posts you referred to (actually I just published my own post about this subject). I opened this issues mainly for tracking - for future users like me who will face the same issue.
I know that removing inline scripts is not a simple issue, but users like me need a better solution so we use CSP. Maybe you can create the hashes for the CSP policies and release them with each plugin version? Not sure how feasible this idea is...

**Comment by fainpablo** [comment]
Definitely +1. Today I added seven hashes to my CSP policy -all of them for Jetpack inline-scripts- and have three aditional that are tied to the page/post so can’t be added using the hash as it changes with every page.

Thanks!
