### ISSUE TITLE
VideoPress Videos assigned to User ID 0

### ISSUE THREAD

**Issue by macmanx2** [Automattic/jetpack#10704]
When uploading a video to VideoPress via the three methods listed at https://jetpack.com/support/video-hosting/#uploading-videos the upload is assigned to User ID 0, meaning no author is attributed to it:

<img width="913" alt="screen shot 2018-11-21 at 11 20 53 am" src="https://user-images.githubusercontent.com/4856235/48863898-d382e300-ed7f-11e8-9ccf-c11082951503.png">

When videos are uploaded to WordPress normally _without_ VideoPress, they are properly attributed to the user who uploaded them:

<img width="918" alt="screen shot 2018-11-21 at 11 22 35 am" src="https://user-images.githubusercontent.com/4856235/48863900-d7af0080-ed7f-11e8-88f2-4822673352f3.png">

**Comment by jeherve** [comment]
Also reported here:
https://github.com/Automattic/sensei/issues/2128

And in #10536

**Comment by amroland** [comment]
If I am right JetPack API doesn't use Author ID. Therefore it is set to `0`.
We are waiting to be fixed. :)

**Comment by RCowles** [comment]
We received another report of this issue. Any update or anything we can recommend in the meantime?

**Comment by jeherve** [comment]
I am afraid we have made no progress on this just yet; the latest can be found here: pxWta-N4-p2

> anything we can recommend in the meantime?

If this conflicts with the Sensei plugin, this can help:
https://github.com/Automattic/jetpack/issues/10536#issuecomment-435899602

If this conflicts with another plugin, I am afraid there is no workaround right now.

**Comment by RCowles** [comment]
Thanks, Jer! It doesn't appear they're using Sensei in this latest report (1886029-zen for reference).

**Comment by ntpixels** [comment]
also reported in 2071225-zen

**Comment by a8ck3n** [comment]
User in 2071225-zen noted:

> This wasn’t an issue until a day or two ago, users were being assigned to videos without a problem. Why has it all of a sudden changed?

Double-checking on this point as this thread seems to indicate it never worked correctly when it comes to assigning a user.

**Comment by anaemnesis** [comment]
Reported in 3184332-zen

**Comment by csonnek** [comment]
Also requested in 3195898-zen - user cancelled their plan because of this.
