### ISSUE TITLE
$_SERVER['HTTP_HOST'] may be undefined in class.jetpack-sync-listener.php

### ISSUE THREAD

**Issue by mdrovdahl** [Automattic/jetpack#10717]
#### Steps to reproduce the issue

1. While running a wp-cli script, I'm bombarded with warnings: 
"Notice: Undefined index: HTTP_HOST in /opt/sites/1017586/wordpress/plugins/jetpack/6.7/sync/class.jetpack-sync-listener.php on line 307" 
2. Looking at https://github.com/Automattic/jetpack/blob/master/sync/class.jetpack-sync-listener.php#L307 I see an `isset()` check on the first `$_SERVER[]` call, but not on the subsequent two
3. Looking at https://github.com/Automattic/jetpack/pull/10134#pullrequestreview-154723849 it seems @roccotripaldi anticipated this scenario =)
4. Fix could be either adding `isset()` checks, or what Rocco suggested, ref: https://konstantin.blog/2012/current-url-in-wordpress/

**Comment by jeherve** [comment]
@gititon Do you think you could take a look at this when you get the chance?

**Comment by chuckreynolds** [comment]
same. bump.

**Comment by afragen** [comment]
This is starting to clutter up my logs daily.
