### ISSUE TITLE
Publicize options in Gutenberg can be hidden

### ISSUE THREAD

**Issue by dartiss** [Automattic/jetpack#10724]
I'm running Jetpack 6.8 RC and testing the new Publicize option for Gutenberg.

Sorry to open a new ticket for this - have attempted to find something existing but have ended up going in circles.

Basically, if you have the Gutenberg option "Pre-publish checks" switched off, the option to edit Publicize option never appears. I had this switched off as, ordinarily, I don't need the pre-publish checks. 

I think it may be worth ensuring that this case is documented, so it doesn't confuse other users.

**Comment by jeherve** [comment]
Good call!

@danjjohnson Could you add this to our documentation when you get the chance?

**Comment by dartiss** [comment]
Always happy to give @danjjohnson something to do 😉

**Comment by danjjohnson** [comment]
This won't be required since we're adding the publicize options to a Jetpack sidebar that appears before the pre-publish checks. Right, @jeherve ?

**Comment by jeherve** [comment]
That's correct. Those changes will be part of Jetpack 6.9. 

For more info, here is the related PR:

https://github.com/Automattic/wp-calypso/pull/28899
