### ISSUE TITLE
Dashicons loading on frontend when in development mode

### ISSUE THREAD

**Issue by catchmyfame** [Automattic/jetpack#10735]
I'm not sure if this is related to https://github.com/Automattic/jetpack/issues/9913 or https://github.com/Automattic/jetpack/issues/10089, but when Jetpack runs in development mode (define('JETPACK_DEV_DEBUG', true)), the dashicons are being loaded on the frontend automatically. Disabling Jetpack stops this behavior.

I'm running the latest versions of WP and jetpack.

**Comment by jeherve** [comment]
Could you let me know which theme you are using? What happens when you switch to a different theme?

**Comment by catchmyfame** [comment]
We're using a custom theme we developed, but testing it with any theme, including the default twentyseventeen, caused the same issue.

**Comment by jeherve** [comment]
Do you see the file when visiting your site while logged out of your admin account? I wonder if the CSS may be added by WordPress as part of the admin bar.

**Comment by catchmyfame** [comment]
Yup, I tested in incognito mode and in another browser I don't usually use and wasn't logged into WP with.

**Comment by jeherve** [comment]
I can't seem to reproduce at the moment. 

Could you give me a list of the different Jetpack modules currently active on your development site?

**Comment by catchmyfame** [comment]
Sure: Markdown, sharing buttons, sitemaps, site stats and akismet.

**Comment by jeherve** [comment]
Thank you. I tried with a similar set of modules (except for Site Stats, which is not available in development mode -- did you mean a different module?), on fresh site running WP 4.9.8 and Jetpack 6.8, with [Jetpack Development mode](https://jetpack.com/support/development-mode/) active. 

I could see the `wp-includes/css/dashicons.min.css?ver=4.9.8` being loaded when I was logged in, as the icons are needed for the admin bar, but when I logged out the file was not loaded anymore. 

Can you think of anything that may be different between your setup and mine?

**Comment by catchmyfame** [comment]
Welp, I'm not sure if a Jetpack update that came out after I reported this fixed the problem, but it seems to be gone for now.
