### ISSUE TITLE
Carousel: clicking on Gallery image always opens first image of the gallery

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#10747]
Following up from #10646

#### Steps to reproduce the issue

1. Start on a site that runs WP 5.0 and Jetpack 6.8. The carousel module must be active.
2. Go to Posts > Add New, and add a new gallery to your post using the Gallery block.
3. Publish your post.
4. On the frontend, click on any picture of the gallery, but not the first one.
5. The Carousel modal opens, but the first image of the gallery appears, not the one you clicked on.

![screen recording 2018-11-29 at 06 27 pm](https://user-images.githubusercontent.com/426388/49240038-8b5d6380-f404-11e8-8263-eac40eda5563.gif)

**Comment by bikedorkjon** [comment]
1639878-zen and also reproduced this.

**Comment by KokkieH** [comment]
This also happens on WordPress.com sites. Report [from the forums](https://en.forums.wordpress.com/topic/image-gallery-22/#add-note), and I was able to replicate on a test site.
