### ISSUE TITLE
Tiled gallery block: load block outside the tiled-gallery module

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#10753]
Currently, tiled gallery block relies on Tiled gallery module, which relies on the Photon module.

If we don't rely on Photon for the layouts, there's no reason to hide Tiled gallery block when user disables Photon. The block doesn't rely on anything from the Jetpack module neither, so perhaps the gallery should always be available.

Test by disabling Photon (_"speed up image load times"_):

<img width="746" alt="image" src="https://user-images.githubusercontent.com/87168/49281921-79c49c00-f496-11e8-96fd-a4b333c92d5d.png">

Tiled gallery block should't now load assets in frontend. The editor side currently loads regardless of the module.

You can test the block following instructions from https://github.com/Automattic/wp-calypso/pull/28944

cc @MichaelArestad  @jeherve

**Comment by jeherve** [comment]
Related discussion: pafL3P-aF-p2

**Comment by sirreal** [comment]
We're relying on Photon for the block, but we're not relying on the Tiled Gallery module for the block 🙃 

I'd like to remove the dependence on the Tiled Gallery module and instead rely on Photon.

Related: https://github.com/Automattic/wp-calypso/issues/29495

**Comment by MichaelArestad** [comment]
> I'd like to remove the dependence on the Tiled Gallery module and instead rely on Photon.

You have my blessing.
