### ISSUE TITLE
Placement Of Notify Check Boxes On Comment Form

### ISSUE THREAD

**Issue by marcbkk** [Automattic/jetpack#1076]
The following two check boxes that the user has the option to click on the option form should be moved to appear below the comment box, but above the post comment button. 

As it is now they appear below the post comment button, but these are options the user needs to decide upon first before pressing the post comment button so they should appear first before the button I think. The way they are now makes it a bit confusing for the user I think.

Notify me of follow-up comments by email. 
Notify me of new posts by email.
![screen](https://cloud.githubusercontent.com/assets/8626314/4116682/44d8a84e-3288-11e4-8415-9d56ec3a806b.jpg)

Attached is a screen shot of how they appear now on my web site.

If you can change the order that would be much appreciated.

Best wishes,

Marc

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
