### ISSUE TITLE
Portfolio: "Add New" opens a blank page

### ISSUE THREAD

**Issue by yongihkim** [Automattic/jetpack#10782]
#### Steps to reproduce the issue

1. Login to WP backend.
2. Go to "Portfolio" and click "Add New"

#### What I expected

Be able to add portfolios.

#### What happened instead

It opens up a blank page.

Here are errors in wp-admin.

Stack trace:
#0 /home4/meehangr/public_html/wp-content/plugins/jetpack/_inc/lib/core-api/wpcom-fields/post-fields-publicize-connections.php(136): WPCOM_REST_API_V2_Post_Publicize_Connections_Field->permission_check(564)
#1 /home4/meehangr/public_html/wp-content/plugins/jetpack/_inc/lib/core-api/class-wpcom-rest-field-controller.php(116): WPCOM_REST_API_V2_Post_Publicize_Connections_Field->get_permission_check(Array, Object(WP_REST_Request))
#2 /home4/meehangr/public_html/wp-includes/rest-api/endpoints/class-wp-rest-controller.php(394): WPCOM_REST_API_V2_Field_Controller->get_for_response(Array, 'jetpack_publici...', Object(WP_REST_Request), 'jetpack-portfol...')
#3 /home4/meehangr/public_html/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(1579): WP_REST_Controller->add_add in /home4/meehangr/public_html/wp-content/plugins/jetpack/_inc/lib/core-api/wpcom-fields/post-fields-publicize-connections.php on line 118

**Screenshots**

**Comment by jeherve** [comment]
Thanks for the report! To solve this issue, I would recommend that you enable the Publicize option under Jetpack > Settings in your dashboard.

This issue was reported in #10727, so I'll close this issue as duplicate.
