### ISSUE TITLE
Tumblr publicize showing 2 images in the post if post has featured image

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/jetpack#10781]
## Summary
When Publicize shares a post to Tumblr, Tumblr shows 2 images if the WordPress post has featured image set.

## Steps to Reproduce

1. Link Publicize to Tumblr
2. Create a new post with an image in the body
3. Set a featured image for the post
4. Publish and ensure Publicize to Tumblr is enabled.

### Expected Result

Tumblr post should only show 1 image

### Actual Result

Tumblr post showing 2 images, 1 featured image and the first image in the Tumblr post.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
