### ISSUE TITLE
VaultPress: Restore status bar showing 100% too early

### ISSUE THREAD

**Issue by chickenn00dle** [Automattic/jetpack#10845]
#### Is your feature request related to a problem? Please describe.
The Restore status bar is showing 100% too early.

#### Describe the solution you'd like
From 1607626-zen

> right now the progress bar displays "100%" and the progress bar looks 100% full, however, it is apparent that the restore process hasn't finished, and above the progress bar it still says "Restoring ..." and the blue spinner next to the word "Restoring ..." is still spinning, and the text below the progress bar which shows the current file/operation is still changing. At least 10 minutes later, "100%" is still displayed, yet it is not done restoring as I can see the files/operations text updating. To fix this, I'd recommend setting the progress bar's (coded) math calculation to be from 1% (instead of 0%) to 99% (instead of 100%), and then only when the process is complete manually setting the progress bar to 100% full and manually setting the text of the progress bar to "100%" (hard-coded), rather than using a mathematical calculation for that part.

**Comment by jeherve** [comment]
Since that restore bar lives in the VaultPress service and is not related to the Jetpack plugin, I would recommend that you report this issue on +vaultp2 instead.

**Comment by chickenn00dle** [comment]
Thank you!
