### ISSUE TITLE
Publicize - (Gutenberg) Not sending New posts when publishing now, only twitter when scheduled posts go live

### ISSUE THREAD

**Issue by mlbanddrb** [Automattic/jetpack#10843]
#### Steps to reproduce the issue

1. Post 1. Published post immediately, expected to see published posts in Twitter, Facebook, and LinkedIn. Nothing posted. Link to post: https://cantspeakgeek.com/wordpress-5-0-is-coming/

2. Post 2 was scheduled for this morning. Post went out. Post sent to both Twitter addresses but not to LinkedIn or Facebook. Post link: https://cantspeakgeek.com/wp-weekly-spotlight-chris-wiegman/

3. Core, plugins, and themes are up-to-date. All connections are showing working.

**Comment by bikedorkjon** [comment]
I checked their Pub RC and they had a successful post 10 days ago so closing this.
