### ISSUE TITLE
Setting: fix deep link from Security text link in Jetpack Dashboard

### ISSUE THREAD

**Issue by joanrho** [Automattic/jetpack#10847]
Depends on #10846 

#### Steps to reproduce the issue
1. Check out #10846 according to the instructions in that PR
2. Go to Jetpack Dashboard
3. Scroll down to Security section
4. Click on the text link "Manage security settings"

#### What I expected
I expected to see the top of the page once I was sent to Jetpack Settings > Security (located at `/wp-admin/admin.php?page=jetpack#security`)

#### What happened instead
The page view jumps midway down the Jetpack Settings > Security page, for some reason.

**Screenshots**
![securitylink](https://user-images.githubusercontent.com/204742/49559518-45087880-f8cc-11e8-905a-468c60063bc4.gif)

**Comment by keoshi** [comment]
This should be easily fixed by adding `window.scrollTo( 0, 0 )` to that link. Ref: https://github.com/Automattic/jetpack/blob/63049e4ea370bda098198d4561cf95480c5c3620/_inc/client/main.jsx#L317
