### ISSUE TITLE
Error banner needs more context

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#10853]
Error in wp-admin after plan upgrade lacks any useful information to customers

![screen shot 2018-12-06 at 1 11 33 pm](https://user-images.githubusercontent.com/214813/49603344-fd7bfe00-f958-11e8-8385-f763395506f7.png)

**Steps to reproduce**

1. I had a free plan on a jurassic ninja site
2. I clicked "update to professional" from within the plans grid within wp-admin
3. Used credits (didn't test with an actual credit card)
4. Site "powered up" without error. In calypso I clicked "back to my site"
5. Brought back to jetpack dashboard within wp-admin and saw this error

note: Jetpack Beta was NOT active during this process. 
Jetpack version 6.8
WordPress development version (5.0-RC3-43969)

#### What I expected

I didn't expect an error as the site "powering up" indicated everything was fine.

#### What happened instead

Error message displayed without any information of what went wrong and how to fix it.

**Comment by jeffgolenski** [comment]
@jeherve @dereksmart Are any of you able to replicate this?

**Comment by jeherve** [comment]
I am afraid not. I'll close it for now, we can reopen if it starts happening again.
