### ISSUE TITLE
WordPress 5.0 with JS/CSS CDN

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#10857]
Updated a site to 5.0 that had the new cdn feature enabled, all the cdn urls generate a 404 breaking wordpress admin.

https://screenshots.brandonhubbard.com/1d35d00f8ed5

**Comment by bhubbard** [comment]
Example link reference, if needed:
https://c0.wp.com/c/5.0/wp-admin/css/themes.min.css

**Comment by jeherve** [comment]
Could you give it another try now? The link works for me right now, so you may just have caught it as it was still being deployed.

**Comment by bhubbard** [comment]
@jeherve You are correct, I just cleared cache, and the 404s disappeared. Closing.
