### ISSUE TITLE
Performance JITM stays on screen after goal accomplished

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#10865]
After the CTA to activate the "improve your site's performance and speed" JITM on the jetpack dashboard is clicked, it should disappear. It currently stays on the dash after the goal is accomplished.

![screen shot 2018-12-06 at 6 46 35 pm](https://user-images.githubusercontent.com/214813/49618713-890c8380-f987-11e8-8540-362954e950e2.png)

**Comment by jeherve** [comment]
I'll close that issue in favor of #9462.
