### ISSUE TITLE
Subscriptions: add Gutenberg support on option to toggle email delivery on a per-post basis

### ISSUE THREAD

**Issue by keoshi** [Automattic/jetpack#10876]
With WordPress 5.0 it became impossible for customers to use the `jetpack_allow_per_post_subscriptions` filter as described here: https://jetpack.com/support/subscriptions/#filters

Previously, a new option would appear in a metabox, like this:

![image](https://user-images.githubusercontent.com/390760/49648568-2dd9a000-fa1e-11e8-9106-f127c2dcc89f.png)

Code ref: https://github.com/Automattic/jetpack/blob/d7a1fadb4163d62d388c1b636c05f261fbab31fd/modules/subscriptions.php#L122-L159

Reported in 1626604-zen

**Comment by jeremypaavola** [comment]
Reported as well in 1637443-zen

**Comment by htdat** [comment]
1638413-zen

**Comment by bikedorkjon** [comment]
To be clear the current behavior for those who have this filter installed and updated to 5.0 is that `dont_email_post_to_subs=1` and their emails will not send, correct?

**Comment by jeherve** [comment]
@bikedorkjon Yes, that is correct. I would recommend removing the filter in those cases.

**Comment by oifabio** [comment]
Hi! Has someone found a solution for this issue?

**Comment by chaselivingston** [comment]
Also requested in 1738651-zen

**Comment by USRFSledge** [comment]
Forgive me my stupidity (and google isn't helping either), where are those #####-zen tickets referring to?
Tried to get some more information on the matter, but where can I find these reports?
```
1626604-zen
1637443-zen
1638413-zen
1738651-zen
```

[I'm sure I make some of you giggle now]

**Comment by jeremypaavola** [comment]
Hi @USRFSledge; those are references to reports relating to the issue at hand that have come through our (other) support channels. You won't have access to view these, but they wouldn't contain any new information either, so you're not missing out on anything.

**Comment by USRFSledge** [comment]
Thank you for the clarification @jeremypaavola . Now it make sense I couldn't find anything about them on google. I'll be monitoring this thread, as I really prefer to have this option back again.

**Comment by bikedorkjon** [comment]
1877078-zen

**Comment by mzakariya** [comment]
User in 1877078-zen wants us to notify them once issue is fixed, and specifically asked us to keep their ticket open.

Placing their ticket on an indefinite hold, so we stop sending reminder/CSAT emails.

**Comment by chaselivingston** [comment]
I closed 1877078-zen so we don't have to keep dealing with it in Play mode. The user won't be notified or asked for CSAT. If they write back in a follow-up will be created. Similarly, when we need to follow-up with them, we can create a follow-up easily from that closed ticket.

**Comment by kievmc** [comment]
Following

**Comment by macmanx2** [comment]
Also 1999231-zen

**Comment by mzakariya** [comment]
2061366-zen

**Comment by Paraplexo** [comment]
Thanks @mzakariya I'm now following directly here...

**Comment by Paraplexo** [comment]
Is this fixed in the latest Jetpack release? I couldn‘t find anything about in the release notes. Or is there another way to achieve this? The other filters i have tested based on categories also not seem to work. Either all emails are sent or none.

**Comment by jeherve** [comment]
@Paraplexo We haven't addressed this issue yet. We'll post here when we start working on this.

> The other filters i have tested based on categories also not seem to work. 

Those filters should still work. Could you reach out to us again via [this contact form](https://jetpack.com/contact-support/?rel=support) and give us more details about the filters you used, and what emails were sent when they should not have been?

You'll want to use the filters as described here:
https://jetpack.com/2016/02/10/hook-month-control-subscriptions/

**Comment by ntpixels** [comment]
2272075-zen

**Comment by rngeer** [comment]
I am interested in this feature being brought back as well.

**Comment by gwensmithx** [comment]
Hi all,

Just wondering if we have plans to have this filter available in the future? If not, we are thinking of removing it from our documentation here: https://jetpack.com/support/subscriptions/ to keep it up-to-date :)

**Comment by jeherve** [comment]
> Just wondering if we have plans to have this filter available in the future?

Yes, we've been thinking of ways to do that in https://github.com/Automattic/jetpack/pull/14021

> we are thinking of removing it from our documentation here: jetpack.com/support/subscriptions to keep it up-to-date

Let's keep the filter in the documentation, since it's still useful for anyone using the Classic editor. 👍 Let's add a mention that this is specific to the classic editor to avoid confusion.

**Comment by rezzap** [comment]
Requested in 3813952-zen again. I've advised them they'll need to use the Classic Editor for the option to work.

**Comment by jeherve** [comment]
Also in pdHDFB-5-p2

**Comment by wpsmartuk** [comment]
Has there been any progress with this? 

I was told to use this filter:
`add_filter( 'jetpack_allow_per_post_subscriptions', '__return_true' );`
But this does not work with the block editor.

**Comment by jeherve** [comment]
Also suggested in #34061.
