### ISSUE TITLE
WooCommerce version JITM: Suppress if WordPress 5.0 site already has WooCommerce 3.5.1+

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/jetpack#10895]
#### Steps to reproduce 

- Start with a WordPress 5.0 site and install WooCommerce 
- Install Jetpack and setup Jetpack (connect with WordPress.com account) 
- Visit the WooCommerce dashboard

**Easy way to create a test site**: Visit [woo.jurassic.ninja/create](https://woo.jurassic.ninja/create) and setup WooCommerce. Install and setup Jetpack later on.

#### What is seen

A WooCommerce JITM recommending WooCommerce 3.5.1 and higher on WordPress 5.0 sites is seen.

<img width="1281" alt="screenshot 2018-12-08 at 19 25 03" src="https://user-images.githubusercontent.com/18581859/49686791-bbe97f80-fb1f-11e8-876e-9a924660b907.png">

#### What I would expect instead

Suppress the JITM if the WordPress 5.0 site already has WooCommerce 3.5.1 or higher.

#### Screenshots

In my case, I had WordPress 5.0 and WooCommerce 3.5.2.

<img width="1281" alt="screenshot 2018-12-08 at 19 25 25" src="https://user-images.githubusercontent.com/18581859/49686790-b8ee8f00-fb1f-11e8-9cc1-85d6a16cb7e6.png">

<img width="1281" alt="screenshot 2018-12-08 at 19 25 40" src="https://user-images.githubusercontent.com/18581859/49686789-b8ee8f00-fb1f-11e8-961c-4c5684b4fade.png">

---

From what I see, this JITM arrives from Jetpack. Happy to be directed to another repository, as required.

**Comment by jeherve** [comment]
cc @davidlenehan, who I believe worked on that JITM.

**Comment by davidlenehan** [comment]
This JITM has now been removed. It was not possible to accurately target plugin version numbers as we wanted to, so we just decided it was important for most Woo users to be made aware of that blog post.
