### ISSUE TITLE
Twitter Widget height not working

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [Automattic/jetpack#10891]
This issue was raised in 8609405-hc. I thought it may be related to the theme, but I tried on Ixion, Penscratch and another theme to the same result.

#### Steps to reproduce the issue

1. Go to the customizer of your site
2. Click on 'Widgets'
3. Add a Twitter timeline widget
4. Set ~5 tweets to show
5. Try adding a height so that a scrollbar activates

#### What I expected

A height can be added and a scrollbar can be used

#### What happened instead
The height keeps getting stripped and does not save.

**Screenshots**
![screen shot](https://cdn-std.dprcdn.net/files/acc_698200/IDmbdW)

**Comment by Piyopiyo-Kitsune** [comment]
Follow up ticket: 1628824-zen

**Comment by arunsathiya** [comment]
@Piyopiyo-Kitsune If I understand [this support document](https://jetpack.com/support/extra-sidebar-widgets/twitter-timeline-widget/) right, the height setting cannot be used (meaning, will be stripped out) if the number of tweets is defined. It appears to be working as expected.

**Comment by jeherve** [comment]
> the height setting cannot be used (meaning, will be stripped out) if the number of tweets is defined. It appears to be working as expected.

That is correct. Closing this.

**Comment by Piyopiyo-Kitsune** [comment]
Thanks y'all! Got back to the user in their ticket. :-)
