### ISSUE TITLE
Gutenberg: Enable Contact Form block by default / Block Discoverability

### ISSUE THREAD

**Issue by kevinwhoffman** [Automattic/jetpack#10903]
#### Steps to reproduce the issue

1. Install Jetpack v6.8.1
2. Add `define( 'JETPACK_DEV_DEBUG', true );` to wp-config.php.
3. Add new post.
4. Open the block inserter and scroll to Jetpack. Note the Form block is not available.
5. Visit `[yourjetpack.blog]/wp-admin/admin.php?page=jetpack_modules`. Note that the Contact Form module is not enabled despite [documentation](https://jetpack.com/support/jetpack-blocks/form-block/) saying that it should be activated by default.
6.Enable the `Contact Form` module. At this point the Form block becomes available in the editor.

#### What I expected

I expected the Form block to be available in the Gutenberg block inserter and in slash commands by default.

#### What happened instead

Instead I had to search through every setting to look for a way to enable the `Form` block. When I did not find a setting, I eventually found the Debug link in the footer where I then followed the link to enable the Contact Form module, which in turn enabled the Form block.

**Screenshots**
Screenshot of the block inserter immediately after plugin activation, showing that the `Form` block is missing:
![image](https://user-images.githubusercontent.com/1938671/49704229-f57cc200-fbd5-11e8-958b-46d1aa72e5d3.png)

#### Primary issue

#32401

**Comment by kevinwhoffman** [comment]
> Does the site have any other Contact Form plugins active?

This was a fresh install of WordPress 5.0 and Jetpack 6.8.1. There were no other plugins installed.

> Something you can do in the future is use the search field on the Jetpack settings page. It's that magnifying glass icon.

The search bar doesn't help because it doesn't provide a control or link necessary to enable the module. It simply shows an information icon that links to documentation.

![image](https://user-images.githubusercontent.com/1938671/49704478-3fb37280-fbd9-11e8-8ab5-43f0d5277c7f.png)

The overall Settings UI is quite confusing because some features are enabled in the Jetpack Dashboard, others in Jetpack Settings, and others still that can only be enabled via the Debug link in the footer. A new user can't be expected to know the URL scheme necessary to access the modules page directly.

**Comment by dereksmart** [comment]
> This was a fresh install of WordPress 5.0 and Jetpack 6.8.1

Got it, possible that dev_debug constant alone doesn’t auto-activate modules. It normally happens during the connection process. 

> It simply shows an information icon that links to documentation

That’s the view when the module is already active. You should see a toggle for the ones that are inactive.

Really do appreciate the feedback about the settings UX. Always room for improvements and we’re continually trying to make the experience better.

**Comment by jeherve** [comment]
> possible that dev_debug constant alone doesn’t auto-activate modules. It normally happens during the connection process.

Yep, in Jetpack's Development mode all modules are deactivated by default; you have to go and enable them on your own if you want to test something with them. That's most likely what caused the confusion here.

> Feel free to close if you think the behavior is working as expected, since I'm unsure of whether the Form block should be enabled by default in dev mode specifically.

We'll leave your issue opened, thank you. It fits into a larger discussion we've been having about block discoverability, and how we can make it easier for one to know what blocks are available, even when the feature itself has not been activated yet.

**Comment by jeherve** [comment]
Also in p8oabR-DS-p2#comment-5223
