### ISSUE TITLE
Instagram shortcode on classic editor

### ISSUE THREAD

**Issue by jlapitan** [Automattic/jetpack#10901]
#### Steps to reproduce the issue

1. Install jetpack on wordpress 5
2. Install classic editor
3. use instagram shortcode embed

#### What I expected

normal instagram embed

#### What happened instead
shortcode did not render

**Screenshots**

**Comment by jeherve** [comment]
Could you post the exact shortcode you used on your site, so we can run some tests on our end? 

Thank you!

**Comment by jlapitan** [comment]
hi @jeherve below is the shortcode i used

[instagram url=https://www.instagram.com/p/bNd86MSFv6/ hidecaption=true width=320]

shortcode based from https://www.instagram.com/developer/embedding/

I am running wordpress 5.0 and PHP 7.2.9 and using the default theme from wordpress 5.0

**Comment by jeherve** [comment]
It seems to work on my end. Could you go to Jetpack > Settings in your dashboard, search from "shortcodes", and make sure the Shortcodes feature is active?

if that does not help, could you contact us via [this contact form](https://jetpack.com/contact-support/?rel=support) so we can investigate some more with you?

Thank you!

**Comment by jlapitan** [comment]
@jeherve that solves the problem. will close this issue
