### ISSUE TITLE
Build Task: Error when running `react:build` gulp task

### ISSUE THREAD

**Issue by creativecoder** [Automattic/jetpack#10921]
#### Steps to reproduce the issue

1. Clone repo
1. Run `yarn build` from root of repo on `master` branch

#### What I expected

Build development assets

#### What happened instead

An error:

```
[13:13:37] 'react:master' errored after 12 s
[13:13:37] ModuleNotFoundError in plugin "webpack"
Message:
    Module not found: Error: Can't resolve 'history/lib/Actions' in '/Users/Grant/Automattic/Sites/jetpack/node_modules/react-router/es'
Details:
    details: resolve 'history/lib/Actions' in '/Users/Grant/Automattic/Sites/jetpack/node_modules/react-router/es'
```

This appears to be caused by updating `history` package to v4 (https://github.com/Automattic/jetpack/commit/8fe1ddd89c62cc37dd592a3819c61172b07ac885)

Reverting that commit allowed me to complete the build task successfully.

**Comment by creativecoder** [comment]
I'm not sure why `react-router` package is accessing the project's version of `history` from `node_modules/history` rather than it's own version from `node_modules/react-router/node_modules/history`...

**Comment by jeherve** [comment]
I'm running into the same issue as well, and I believe it may be caused by #10852.

**Comment by jeherve** [comment]
#10906 may fix the problem. Testing now.

**Comment by creativecoder** [comment]
Thanks!
