### ISSUE TITLE
Gutenberg / Classic / Jetpack: wp.me short link is not accessible 

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#10925]
I was just investigating an issue that a customer was having. With the wp 5.0 update / gutenberg now being the primary editor, any one who previously used our wp.me shortlinks is unable to get their short link in wp-admin. 

They either have to revert to the classic editor or view their site using the calypso interface in order to get a short link for a post

**Before Gutenberg / wp 5.0:**
<img width="888" alt="screen shot 2018-12-10 at 5 28 57 pm" src="https://user-images.githubusercontent.com/214813/49765670-34c41500-fca1-11e8-8788-6d9e200acd49.png">

**After Gutenberg / wp 5.0** 
<img width="1367" alt="screen shot 2018-12-10 at 5 30 24 pm" src="https://user-images.githubusercontent.com/214813/49765715-4dccc600-fca1-11e8-9bfc-0cde2dcad11a.png">

As a Jetpack UX bonus:

The moment a customer publishes a post we should display the wp.me short link in the "what's next" column (jetpack branded of course)

<img width="1518" alt="screen shot 2018-12-10 at 5 19 56 pm" src="https://user-images.githubusercontent.com/214813/49765819-908e9e00-fca1-11e8-8df7-ad6906c81b88.png">
 

cc @MichaelArestad @davidakennedy

**Comment by MichaelArestad** [comment]
Thanks for creating this issue. We will get to this, but we have limited resources and higher priority blocks/integrations to build first.

**Comment by arunsathiya** [comment]
Related on Calypso: https://github.com/Automattic/wp-calypso/issues/29221

**Comment by htdat** [comment]
Another 
--- 

![screen shot on 2018-12-17 at 13 56 08](https://user-images.githubusercontent.com/10045087/50071231-9df8da80-0203-11e9-9005-054dea32d9fd.png)

@bikedorkjon  - it's working for me in Classic Editor in a Pressable testing site. Is there any chance you was not enabling "WP.me Shortlink" module when testing? 

---- 

Another report: 1646640-zen

**Comment by tyxla** [comment]
#29475 has been merged. Shortlinks will appear under the Publicize panel in the Jetpack sidebar from the next Jetpack release on:

![](https://cldup.com/0yLlAwF39H.png)

**Comment by asm0dey** [comment]
Still don't have it, at least for podcast

**Comment by jeherve** [comment]
@asm0dey Do you rely on a Custom Post Type to store and display your podcasts? If so, you would need to declare support for shortlinks like so:
https://jetpack.com/support/wp-me-shortlinks/#cpt

**Comment by asm0dey** [comment]
I'm using seriously simple podcasting plugin and I don't have any idea about post types it uses

**Comment by jeherve** [comment]
@asm0dey This plugin uses the `podcast` post type, so you would have to add Shortlinks support for that custom post type on your site, by following the instructions I posted earlier. This can help too:
https://jetpack.com/support/adding-code-snippets/

**Comment by garikaib** [comment]
Hi,
I don't see this on my site. I am not using custom posts. I have Gutenberg 6.5.0 and have been desperately searching for this feature ever since I moved from Classic editor. Using other shorteners takes a lot of effort plus my other one from Google closed.Is there a setting I am missing somewhere.
