### ISSUE TITLE
Bug with Jetpack Auto-update and WPCLI

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#10964]
Reported in 1640435-zen

The user is seeing this error in his logs:

<blockquote>
The system failed to run the wp-cli batch commands with the following issues: 
[...]

Uncaught ArgumentCountError: Too few arguments to function Jetpack_Autoupdate::autoupdate_core(), 1 passed in /home/showmete/corporate.showmetech.com.br/wp-includes/class-wp-hook.php on line 286 and exactly 2 expected in /home/showmete/corporate.showmetech.com.br/wp-content/plugins/jetpack/class.jetpack-autoupdate.php:98 
</blockquote>
 
@seear saw this:

<blockquote>
#0 /home/REDACTED/wp-includes/class-wp-hook.php(286): Jetpack_Autoupdate->autoupdate_core('minor')
#1 /home/REDACTED/wp-includes/plugin.php(203): WP_Hook->apply_filters('minor', Array)
#2 /usr/local/cpanel/php/wp-cli/get_auto_update_settings.php(79): apply_filters('auto_update_cor...', 'minor')
#3 /usr/local/cpanel/php/wp-cli/get_auto_update_settings.php(93): get_autoupdate_core()
#4 phar:///usr/local/cpanel/3rdparty/share/wp-cli/wp-cli.phar/vendor/wp-cli/eval-command/src/EvalFile_Command.php(43): include('/usr/local/cpan...')
#5 phar:///usr/local/cpanel/3rdparty/share/wp-cli/wp-cli.phar/vendor/wp-cli/eval-command/src/EvalFi in /home/REDACTED/wp-content/plugins/jetpack/class.jetpack-autoupdate.php on line 98
</blockquote>

> Looks like some code in there (get_auto_update_settings.php) that is not part of either Jetpack or WP-CLI is passing the wrong number of arguments when running an update command.

`get_auto_update_settings.php` seems to be related to the WP Time Capsule service or plugin from what I could find, but the user's host says that they don't have this on the VPS.

So at this point, I'm out of ideas and don't know what would be causing this. We do not have any further reports.

**Comment by jeherve** [comment]
> Looks like some code in there (get_auto_update_settings.php) that is not part of either Jetpack or WP-CLI is passing the wrong number of arguments when running an update command.

That does indeed seem like the source of the problem. Jetpack uses a WordPress hook, `auto_update_{$type}`, that requires 2 parameters:
https://developer.wordpress.org/reference/hooks/auto_update_type/

We specify those in Jetpack here:
https://github.com/Automattic/jetpack/blob/7df7d828854b5ddde136452b26a38dd6d2726da7/class.jetpack-autoupdate.php#L36

However, another plugin, or the theme, seems to be using the same filter but only specifies 2 parameters, thus creating issues with all other plugins that come after it and also use the filter.

I would recommend that the site owner searches for all instances of `auto_update_core` on their installation to find out what is causing this. That should help.
