### ISSUE TITLE
Jetpack appears to break toolbar after 4.9.9 update

### ISSUE THREAD

**Issue by dartiss** [Automattic/jetpack#10967]
Overnight, my site's back-end toolbar has broken. All that has happened is that WP has updated from 4.9.8 to 4.9.9.

However, deactivating Jetpack resolves the issue and the toolbar displays correctly.

I'm using the standard WordPress toolbar, not the WordPress.com version.

<img width="1338" alt="screenshot 2018-12-13 at 10 12 00" src="https://user-images.githubusercontent.com/14928971/49931819-9b267e80-febf-11e8-818a-f98c2bbd7a13.png">

**Comment by jeherve** [comment]
This may be a duplicate of #10857. Could you check for errors in your browser console? Do you see any 404s for some core files? Do you use the Asset CDN feature on your site? If you clear your browser cache after checking all this, does it help?

**Comment by dartiss** [comment]
It does appear to have been a cache issue as it's resolved itself overnight. Thanks 👍🏼
