### ISSUE TITLE
Admin Page: yarn watch does not build everything needed to start developing as yarn build does

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#10963]
#### Steps to reproduce the issue

1. Run `yarn clean-client`
2. Run `yarn watch`
3. Load the admin page.
4. Expect to see unstyled content

#### What I expected

To be able to just start coding with `yarn watch`.

#### What happened instead

I have to run `yarn build` at least once before `yarn watch`.

**Screenshots**

![image](https://user-images.githubusercontent.com/746152/49891450-4b937480-fe25-11e8-834d-064bc4c9aacd.png)

**Comment by kraftbj** [comment]
Also see #11698 and needs to be updated again with the composer work.
