### ISSUE TITLE
Missing Social Icons using AMP and WP 5.0.x

### ISSUE THREAD

**Issue by allen-mcnichols** [Automattic/jetpack#10973]
**Describe the bug**
There seems to be an issue with the recent changes in WP 5.0.1 with AMP and Jetpack's social sharing icons that causes them to no longer display.

**To Reproduce**
1. Scroll down to the bottom of the post where the social sharing links are
2. See error

**Expected behavior**
Social Sharing icons should be displayed instead of basic ul li list

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/43300142/49955927-dc676000-feb8-11e8-9493-103192e0d9a0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 70.0.3538.110

**Comment by allen-mcnichols** [comment]
Latest version of the AMP plugin but this was discovered on a staging server so I don't have an example other than my screenshot that I can provide.

**Comment by davebonds** [comment]
It is happening on the latest version of the official AMP plugin https://wordpress.org/plugins/amp/ and latest Jetpack 6.8.1 on WP 5.0.1

**Comment by jeherve** [comment]
Thank you both for the replies. This will be fixed by #10945
