### ISSUE TITLE
Jetpack Plans and My Plans areas: Consolidate up-sell prompts

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#10995]
If a customer is on Jetpack Free, the "My Plan" and "Plans" area offers up a bunch of up-sell CTAs in a tacky sort of way. I think we should come up with a single up-sell CTA area that shuffles content based on the context of the customer, otherwise this looks like complete spam and bloated.

**Currently:**
![fireshot capture 003 - jetpack cathol_ - https___catholic-tangle jurassic ninja_wp-admin_admin php](https://user-images.githubusercontent.com/214813/50116957-afe57800-0219-11e9-9295-8becd11cae97.png)
![fireshot capture 004 - jetpack cathol_ - https___catholic-tangle jurassic ninja_wp-admin_admin php](https://user-images.githubusercontent.com/214813/50116958-afe57800-0219-11e9-949b-5a4544e581ae.png)

**Proposed:**

Just some quick in browser mocks that need a little more thought and discussion...

**"My Plan"**

![fireshot capture 006 - jetpack cathol_ - https___catholic-tangle jurassic ninja_wp-admin_admin php](https://user-images.githubusercontent.com/214813/50119802-d0193500-0221-11e9-8961-da3b29ce2d2d.png)

* Add value cards for customers on free, with more strategically placed upgrade prompts.
* Right now the cards displayed on "free" don't accurately reflect all the features included with free - it's not clear those are upgrades since there's no CTA to help them along. I think we need to sell more people on the value of the feature rather than just arbitrarily asking them to upgrade from a small white square box, so I propose adding buttons and taking them to the proper areas within the plugin

Content not finalized!

> **Design the perfect website**
> 
> _text about customization and themes tbd...._
>
> Button: [Explore design tools] url: https://jetpack.com/features/design/
>
> **Increase traffic and revenue**
>
> _text about our marketing and growth tools tbd...._
> 
> Button: [Configure marketing & traffic tools] url: settings: traffic
>
> **Always-on security to keep you safe**
>
> _text about our security tools tbd...._
>
> Button: [Ensure you're safe] url: settings: security
>
> **Built-in performance**
>
> _text about performance tbd...._
>
> Button: [Speed up your site] url: settings/performance (coming soon)
>
> **Mobile apps for any device**
>
> _text about our mobile apps tbd...._
>
> Button: [Get the WordPress app] url: https://apps.wordpress.com/
>
> **Enjoy priority support**
> 
> _text about priority support tbd...._
>
> Button: [Get faster solutions] url: Plans tab
>
> **Jetpack offers so much more**
> 
> _text about more benefits tbd...._
>
> Button: [Explore all features] url: Plans tab

I want to keep customers in the jetpack UI where possible, but since our product and marketing IA in inconsistent, it's difficult at the moment. Some links will divert customers to settings areas, while other areas will take them to jetpack.com (example: design & themes)

* I'm not sure how activity fits into this in a way that explains value to the customer on free, so I didn't include it 

**"Plans"**

![screen shot 2018-12-17 at 4 40 32 pm](https://user-images.githubusercontent.com/214813/50117305-9c86dc80-021a-11e9-8980-32dba87751b1.png)

* The plans grid is the only up-sell area we need on this page - we can roll any other feature mention into this grid - such as the Premium themes, priority support, and WP Apps. We also need to clean up this plans table quite a bit to be consistent with Jetpack.com

**Comment by jeffgolenski** [comment]
I'd love your thoughts on this squad: @keoshi @joanrho @rickybanister - this is a quick birthday cake I think we can roll up right after the new year. It needs a little more thought, but the current pages pain me pretty badly.

**Comment by joanrho** [comment]
@jeffgolenski apologies for the delay in reply, but I think your design direction is a solid place to start. It aligns with the experience users see in Paid Plan tiers and helps bring to attention all the features Jetpack users get under the Free tier. Let's start with this and save birthday cakes for future iterations.
