### ISSUE TITLE
Add option to Publicize full post text rather than just an excerpt

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#1101]
As requested here: http://wordpress.org/support/topic/copying-full-text-of-posts-to-tumblrfacebooketc-via-publicize?replies=3#post-5864025

An option (or even better, a filter) that would allow the full text of a post to be Publicized, rather than just the excerpt. The feasibility of this depends on any limits Facebook et al. have imposed in their API.

**Comment by jkudish** [comment]
It's on our team's list to go through all the shortcodes/embeds on WP.com and sync as many as possible to Jetpack. Since this hasn't happened yet, feel free to sync this one individually, there's no reason not to.

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/publish-whole-article-content?replies=1&view=all

**Comment by jeherve** [comment]
Related: #261

**Comment by jeherve** [comment]
Closing this in favor of #261
