### ISSUE TITLE
Related Posts: Allow block to have more than 3 posts

### ISSUE THREAD

**Issue by tyxla** [Automattic/jetpack#11014]
Quoting @jeherve from https://github.com/Automattic/jetpack/pull/10132#pullrequestreview-185643209:

> The block inspector offers me the option to display up to 3 posts per block. It would be nice to have the option to display more, especially since that is possible with the existing Related Posts (through a filter).

---

Via https://github.com/Automattic/wp-calypso/issues/30101:

> > by default, the maximum number to be displayed is 3. Soon will the max be at 6 ?
> 
> It would be nice if the block allowed you to insert more than 3 posts, just like you can customize the number of posts returned with the regular related posts:
https://jetpack.com/support/related-posts/customize-related-posts/#number
> 
> Requested here:
> https://jetpack.com/2019/01/10/jetpack-6-9-introducing-more-tools-for-the-new-block-editor/#comment-193506

**Comment by aldavigdis** [comment]
Taking this on!
