### ISSUE TITLE
Related Posts: Add spacing below related posts block clarifications

### ISSUE THREAD

**Issue by tyxla** [Automattic/jetpack#11012]
As @jeherve suggested in https://github.com/Automattic/jetpack/pull/10132#pullrequestreview-185643209 and @tyxla addressed in https://github.com/Automattic/jetpack/pull/10132#issuecomment-448599438 we added some clarifications that site-wide Related Posts settings don't apply to the Related Posts blocks (particularly, the **_The following settings..._** message):

![](https://cldup.com/q5RmIoZ7pB.png)

![](https://cldup.com/VIG-pLF7q1.png)

But @jeherve suggested in https://github.com/Automattic/jetpack/pull/10132#issuecomment-448625933 that we add some spacing.

Personally, I think both messages currently look well as they are, so I'd like to call for some design help - what do you folks think? Would you add some spacing, and how much would you add?

cc @MichaelArestad @mapk

**Comment by jeherve** [comment]
I'll close this in favour of #11021, since it seems like it offers other solutions.
