### ISSUE TITLE
Create our custom Publicize message

### ISSUE THREAD

**Issue by almendron** [Automattic/jetpack#11047]
1) “_wpas_mess” is a function of JetPack (modules/publicize/publicize.php)
Add a record in the postmeta table where “meta_key” = “_wpas_mess”. Therefore, we can use:

`<?php` update_post_meta( $post_id, $meta_key, $meta_value, $prev_value ); `?>`

2) WordPress 5.0.2 and Classic Editor:

`<?php` update_post_meta( $post_id, '_wpas_mess', $meta_value, $prev_value ); `?>`

It works perfectly

3) The same function with Gutenberg Editor: It does not work.

The postmeta table is updated correctly: [see image 1](https://almendron.com/compartir/gutenberg/compartir-1.png).

However, the values do not appear in the editor: [see image 2](https://almendron.com/compartir/gutenberg/compartir-2.png). The words “Periodismo” y “España” are missing.

It is, therefore, a JetPack problem with the Gutenberg editor.

PS. It is an error that the message appears after clicking “Publish”.
The box “Share this post” should be on the first screen, next to the categories, tags, etc.

**Comment by jeherve** [comment]
Thanks for the report. I'll close this issue as duplicate, as it was already reported in https://github.com/Automattic/wp-calypso/issues/29128
