### ISSUE TITLE
Lazy Loading: Class exclusion images contain noscript tags

### ISSUE THREAD

**Issue by bikedorkjon** [Automattic/jetpack#11054]
In 1655173-zen we have a user who has an embed plugin that includes image urls to copy and paste into other sites, and even though they are using the jetpack_lazy_images_blacklisted_classes filter it still is including the noscript tags included by lazy load (but excluding the lazy loading classes). Looking at code this appears to be because the should_skip_image_with_blacklisted_class method is called in the process_image_attributes method before we build the image, so it's just skipping over the lazy loading attributes versus skipping over the image entirely. We either need to add a second should_skip_image_with_blacklisted_class check inside the process_image_attributes process_image method or just move the entire check in there so that the noscript tags are not added.

https://github.com/Automattic/jetpack/blob/abf3988da482778e9d90ddb35b9ee2368a9d905d/modules/lazy-images/lazy-images.php#L182

**Comment by htdat** [comment]
https://github.com/Automattic/jetpack/blob/abf3988da482778e9d90ddb35b9ee2368a9d905d/modules/lazy-images/lazy-images.php#L179-L182

I think the simple way is to compare whether or not $new_attibutes and $old_atributes are the same. Then, we will decide whether or not to output the `noscript` tags. 

```php
		$new_attributes     = self::process_image_attributes( $old_attributes );

		if ( $new_attributes == $old_attributes ) {
			// Do not output noscript tags as this image is skipped from Lazy Images
			return sprintf( '<img %s>', $matches[0] );	
		} else {
			// This image is included in Lazy Images, so output noscript tags.
			$new_attributes_str = self::build_attributes_string( $new_attributes );
			return sprintf( '<img %1$s><noscript>%2$s</noscript>', $new_attributes_str, $matches[0] );		
		}
```

**Comment by darylldoyle** [comment]
I just wanted to note that I'm facing this exact issue currently. I was looking for a way to counter this bug by stripping the `<noscript>` out again for the image I'm concerned about, but as the filter is added at `PHP_INT_MAX` it makes it extremely difficult.
