### ISSUE TITLE
Twenty Nineteen: Tiled galleries circles layout: Images cut off on the right

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/jetpack#11058]
#### Steps to reproduce 

- Start with a WordPress.com site or a Jetpack site
- Install `Twenty Nineteen` theme 
- Create a post or a page
- Use Jetpack's `Tiled galleries` feature and add 2 or more images
- Choose `Circles` layout for the gallery

#### What is expected 

The images appear in circles layout in full

#### What happens instead 

A few images are cut off, on the right

#### Screenshots

<img width="942" alt="screenshot 2019-01-01 at 23 31 24" src="https://user-images.githubusercontent.com/18581859/50575128-64d48300-0e1d-11e9-95a4-53fe17887e16.png">
<img width="795" alt="screenshot 2019-01-01 at 23 27 49" src="https://user-images.githubusercontent.com/18581859/50575129-64d48300-0e1d-11e9-930b-81e80b8e0cab.png">
<img width="677" alt="screenshot 2019-01-01 at 23 27 32" src="https://user-images.githubusercontent.com/18581859/50575130-656d1980-0e1d-11e9-80a3-e1410e7448b5.png">

#### Notes:

This specifically seems to happen only with the Twenty Nineteen theme. I also tested with Twenty Seventeen theme, and I am not able to see this erroneous behaviour.

I also haven't seen this behaviour with any other themes in the past.

Let me know if this can be reported on [Twenty Nineteen's repository](https://github.com/WordPress/twentynineteen) instead.

**Comment by jeherve** [comment]
Could you clarify if this happens when using the new Tiled Gallery block, or when using the classic block with a tiled gallery?

**Comment by arunsathiya** [comment]
@jeherve That's a good question. It happens with the tiled gallery on classic editor (Calypso editor) / classic editor on wp-admin dashboard.

It does not happen with the new `Tiled gallery` block - p1HpG7-65C-p2 #comment-29671

**Comment by jeherve** [comment]
I can't seem to reproduce on my end right now:

![image](https://user-images.githubusercontent.com/426388/50592886-524a6000-0e96-11e9-8b6a-e6399f0a98cb.png)
![image](https://user-images.githubusercontent.com/426388/50592894-58d8d780-0e96-11e9-98e0-97ed7194c763.png)

Could you give it another try, and let me know if you see any JS errors in your browser console?

**Comment by arunsathiya** [comment]
I am consistently able to reproduce this with different image sets. Here is how it looks at the moment, and console logs show what's below.

```
[Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://assistant-raccoon.jurassic.ninja/wp-content/plugins/jetpack/_inc/social-logos/social-logos.eot?51b607ee5b5cb2a0e4517176475a424c
(index):1 Failed to decode downloaded font: https://assistant-raccoon.jurassic.ninja/wp-content/plugins/jetpack/_inc/social-logos/social-logos.eot?51b607ee5b5cb2a0e4517176475a424c
(index):1 OTS parsing error: invalid version tag
(index):1 Failed to decode downloaded font: https://assistant-raccoon.jurassic.ninja/wp-content/plugins/jetpack/_inc/social-logos/social-logos.eot?51b607ee5b5cb2a0e4517176475a424c
(index):1 OTS parsing error: invalid version tag
```

I am not sure if they help with debugging.

I can also confirm I have used multiple browsers without any extensions. It's consistently reproducible with the Twenty Nineteen theme.

<img width="1281" alt="screenshot 2019-01-02 at 19 09 03" src="https://user-images.githubusercontent.com/18581859/50594344-3d83c180-0ec2-11e9-945d-358b148d1feb.png">
<img width="808" alt="screenshot 2019-01-02 at 19 07 30" src="https://user-images.githubusercontent.com/18581859/50594345-3d83c180-0ec2-11e9-97f9-790eb1ab8cb8.png">
<img width="805" alt="screenshot 2019-01-02 at 19 07 24" src="https://user-images.githubusercontent.com/18581859/50594347-3d83c180-0ec2-11e9-97b5-2eb4075baac3.png">

**Comment by arunsathiya** [comment]
I am not sure if this helps, but these are the [two](https://cloudup.com/c_Ed5HUVcZJ) [sets](https://cloudup.com/cZNsqCdlq0a) of images I used.

**Comment by jeherve** [comment]
Could you let me know which version of Twenty Nineteen you currently use on your site?

**Comment by arunsathiya** [comment]
The Jurassic Ninja site I was testing on has Twenty Nineteen v1.1. I just tested on a WordPress.com site as well, with the latest version of Twenty Nineteen from https://wordpress.com/themes 

Same issue.

But I have an update. It seems to be a display issue at my end.

It seems to happen only my external monitor. When I open on my Mac's display, it shows up fine. I don't know why there is a difference between the two.

The images below are from the Jurassic Ninja site, and WordPress.com Business plan site, respectively.

<img width="1680" alt="screenshot 2019-01-03 at 14 58 58" src="https://user-images.githubusercontent.com/18581859/50630810-239cba00-0f68-11e9-9643-6348e39c0b22.png">
<img width="1680" alt="screenshot 2019-01-03 at 14 58 53" src="https://user-images.githubusercontent.com/18581859/50630811-24355080-0f68-11e9-97d7-733fc35eca96.png">

At this stage, I shall close this report as this is clearly not a Jetpack issue. 

I will be digging in a bit more and report on Twenty Nineteen's repo, as required. 

Thanks for looking along so far!

**Comment by jeherve** [comment]
That's a good find! Do you happen to know if your monitor is a Retina monitor?

If you inspect one of the images from the gallery when viewing it on your monitor, could you let me know what the image URL looks like? I am especially interested in the query strings at the end of the URL.

**Comment by arunsathiya** [comment]
Sorry about the delayed response, but I lost track of this ping.

Yes, I have a retina monitor and it turns out the display issue happens when I am on strange resolutions like `1280 x 720`. When I use the recommended `3840 x 2160` resolution, it appears fine.

The image's code is available here:

```
<img data-attachment-id="161" data-orig-file="https://assistant-raccoon.jurassic.ninja/wp-content/uploads/2019/01/img-1301623762.png" data-orig-size="700,400" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="img-1301623762.png" data-image-description="" data-medium-file="https://i2.wp.com/assistant-raccoon.jurassic.ninja/wp-content/uploads/2019/01/img-1301623762.png?fit=300%2C171&amp;ssl=1" data-large-file="https://i2.wp.com/assistant-raccoon.jurassic.ninja/wp-content/uploads/2019/01/img-1301623762.png?fit=640%2C366&amp;ssl=1" src="https://i2.wp.com/assistant-raccoon.jurassic.ninja/wp-content/uploads/2019/01/img-1301623762.png?zoom=2&amp;w=316&amp;h=316&amp;crop=1&amp;ssl=1" width="316" height="316" data-original-width="316" data-original-height="316" itemprop="http://schema.org/image" title="img-1301623762.png" alt="img-1301623762.png" style="width: 316px; height: 316px;" class="jetpack-lazy-image jetpack-lazy-image--handled" data-lazy-loaded="1" src-orig="https://i2.wp.com/assistant-raccoon.jurassic.ninja/wp-content/uploads/2019/01/img-1301623762.png?w=316&amp;h=316&amp;crop=1&amp;ssl=1" scale="2">
```

I assume this is the specific part you want:

```
https://i2.wp.com/assistant-raccoon.jurassic.ninja/wp-content/uploads/2019/01/img-1301623762.png?zoom=2&amp;w=316&amp;h=316&amp;crop=1&amp;ssl=1
```

The one on the left, unaffected image, looks so:

```
<img data-attachment-id="175" data-orig-file="https://assistant-raccoon.jurassic.ninja/wp-content/uploads/2019/01/img-330800790.png" data-orig-size="700,400" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="img-330800790.png" data-image-description="" data-medium-file="https://i2.wp.com/assistant-raccoon.jurassic.ninja/wp-content/uploads/2019/01/img-330800790.png?fit=300%2C171&amp;ssl=1" data-large-file="https://i2.wp.com/assistant-raccoon.jurassic.ninja/wp-content/uploads/2019/01/img-330800790.png?fit=640%2C366&amp;ssl=1" src="https://i2.wp.com/assistant-raccoon.jurassic.ninja/wp-content/uploads/2019/01/img-330800790.png?zoom=2&amp;w=316&amp;h=316&amp;crop=1&amp;ssl=1" width="316" height="316" data-original-width="316" data-original-height="316" itemprop="http://schema.org/image" title="img-330800790.png" alt="img-330800790.png" style="width: 316px; height: 316px;" class="jetpack-lazy-image jetpack-lazy-image--handled" data-lazy-loaded="1" src-orig="https://i2.wp.com/assistant-raccoon.jurassic.ninja/wp-content/uploads/2019/01/img-330800790.png?w=316&amp;h=316&amp;crop=1&amp;ssl=1" scale="2">
```

I don't see any differences between the two, but it hopefully helps you in some way.

The post is also available [here](https://assistant-raccoon.jurassic.ninja/2019/01/02/282/) if you want to take a look at it.

**Comment by jeherve** [comment]
Thanks for the extra details. That seems to be an issue with a specific CSS rule in the Twenty Nineteen theme:

```css
@media only screen and (min-width: 1168px) {
  .entry .entry-content > *,
  .entry .entry-summary > * {
    max-width: calc(6 * (100vw / 12) - 28px);
  }
}
```
It seems to impact all containers at specific browser widths, as you mentioned. I think it would be worth reporting this in the Twenty Nineteen repo.
