### ISSUE TITLE
Display elastic search results in an IFrame

### ISSUE THREAD

**Issue by iamkunaldesai** [Automattic/jetpack#11051]
How about displaying elastic search results in an iframe?

No need to render html document.

Good for speed.

**Comment by jeherve** [comment]
Could you give us more details about what you'd like to see implemented, and why? Jetpack's Search feature currently does not handle the display of the results, this is all done by the theme, so if you wanted to display search results in an iFrame, you could do that in your theme.

**Comment by iamkunaldesai** [comment]
Display search results in an iframe just like google custom search engine.

**Comment by jeherve** [comment]
Where would that iFrame be hosted, in this case? On WordPress.com? What are the benefits of hosting the page somewhere else instead of on your site?

**Comment by iamkunaldesai** [comment]
On my own domain.

**Comment by jeherve** [comment]
It's worth noting that we're working on something related; while not in an iFrame,  our upcoming "Instant Search" iteration will allow us to display results as you type, without the need to load a results page.

The feature is currently in Alpha, but we'll be releasing a Beta soon. I would recommend that you follow our blog at https://jetpack.com/blog/ We'll post about Instant Search there very soon!
