### ISSUE TITLE
Add Media RSS Support

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#11062]
#### Is your feature request related to a problem? Please describe.
When someone migrates from WordPress.com Simple to a Jetpack-powered site, they may be surprised to find that their RSS feeds no longer include rich media information.

#### Describe the solution you'd like
We should migrate/implement the Media RSS extension we already have on WP.com in Jetpack. It can be found in our codebase at `/wp-content/blog-plugins/mrss.php`.

#### Additional context
Since there are [other Media RSS plugins](https://wordpress.org/plugins/tags/mrss/) out there, and (that I'm aware of) no good way to detect their output, we might want to detect and defer to them (although their install-bases seem very low).

**Comment by xpurichan** [comment]
We received a new request for this in 2014952-zen

**Comment by rinatkhaziev** [comment]
We also just received a similar request, currently leaning towards copying over to [VIP Go / WordPress.com Compat](url) in the meantime, but will gladly open a PR here to save everybody a little bit of time.

/cc @beaulebens @jeherve

**Comment by jeherve** [comment]
@rinatkhaziev That sounds good. Do not hesitate to reach out in #jetpack-crew if you need any feedback. This will also be helpful:
PCYsg-fTc-p2

**Comment by allykmyta** [comment]
We received a new request for this in 2803036-zen

**Comment by aleone89** [comment]
Hello! Received another report here: 3237386-zen

**Comment by philnick206** [comment]
Another report here: #6365944-hc

**Comment by susanjanec** [comment]
Another report here - 27003432-hc

**Comment by the-misha** [comment]
Another report here: 5187972-zd-woothemes

**Comment by cuemarie** [comment]
Another report of this issue here: 36258308-hc

Recommended they try [WP Feed Post Thumbnail](https://wordpress.org/plugins/wp-feed-post-thumbnail/) or [Featured Images in RSS for Mailchimp & More](https://wordpress.org/plugins/featured-images-for-rss-feeds/) to address the issue.

**Comment by zdenys** [comment]
6009293-zd-woothemes

**Comment by cuemarie** [comment]
another request specifically for featured images in RSS feeds here: 7999357-zen

**Comment by the-misha** [comment]
another request: 8521615-zd-a8c

**Comment by cuemarie** [comment]
Added this to the One Board so it can go through the latest process, since we're still seeing reports come in.

**Comment by jeherve** [comment]
I'll close this issue as won't fix. We're not currently planning on adding any RSS-related features to the Jetpack plugin. I would consequently recommend using another plugin to add such media enclosures to RSS feeds if needed.

If folks on WoA sites find they miss the feature when moving from WordPress.com Simple to WoA, they should be able to add such a plugin. 

If we continue to receive support requests and comments on this GitHub issue, we may always reconsider this in the future.

**Comment by Gustavo-Hilario** [comment]
Another report here: 8583962-zen

Recommended they try [WP Feed Post Thumbnail](https://wordpress.org/plugins/wp-feed-post-thumbnail/) to address the issue.
