### ISSUE TITLE
WPCOMSharing doesn't handle server errors gracefully

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/jetpack#1107]
WPCOMSharing doesn't handle server errors gracefully. Here's `update_facebook_count`:

	update_facebook_count : function( data ) {
		if ( 'undefined' != typeof data[0].total_count && ( data[0].total_count * 1 ) > 0 ) {
			WPCOMSharing.inject_share_count( 'sharing-facebook-' + WPCOM_sharing_counts[ data[0].url ], data[0].total_count );
		}
	},

When Facebook returns a server error, data[0] is undefined, meaning data[0].total_count won't be defined, and you get this TypeError:

    Uncaught TypeError: Cannot read property 'total_count' of undefined

**Comment by jeherve** [comment]
This should be solved now that we use a new method to get Facebook sharing counts.

Feel free to reopen if you continue to experience issues!
