### ISSUE TITLE
Enhancement: Need updated Connection Banner verbiage

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#11089]
Spotted by @annezazu, the new header of the connection banner doesn't read that well.

<img width="1664" alt="screen shot 2019-01-03 at 9 51 25 am" src="https://user-images.githubusercontent.com/214813/50707553-30381580-102f-11e9-83f4-17786403cbd8.png">

Currently:

> Set up Jetpack to boost your site performance and get dozens of customization, marketing, and security tools.

Proposed:
> Set up Jetpack to boost your site performance and unlock powerful customization, marketing, and security tools.

#### Steps to reproduce the issue

Install + activate Jetpack. View the connection banner on the Plugins page or the main dashboard in wp-admin.

#### What I expected

Better verbiage

#### What happened instead

I messed up the verbiage! 

**Screenshots**

**Comment by jeherve** [comment]
Fixed in #11090
