### ISSUE TITLE
Jetpack does not display search filters, under several conditions

### ISSUE THREAD

**Issue by benlk** [Automattic/jetpack#11116]
#### Steps to reproduce the issue

There are several ways to reproduce this, with a site that is connected to a Jetpack Pro plan and has Search enabled. Both happen under Jetpack 6.8.1.

Following the instructions for adding sidebar filters using the customizer, https://jetpack.com/support/search/customize-search/#customizer-facets :

1. Create a widget area on the search template, which is the one displayed at `/?s=search+query`
2. Add a Jetpack Search widget to the widget area.
3. Define a couple filters using the widget's interface.
4. View the search page.

Following the instructions for adding sidebar filters using code, but still displaying them in the widget https://jetpack.com/support/search/customize-search/#code-facets :

1. Create a widget area on the search template, which is the one displayed at `/?s=search+query`
2. Add a Jetpack Search widget to the widget area.
3. Define a couple filters using [the code here](https://github.com/INN/umbrella-gijn-resources/blob/9821ed9b70996cd796649d9ccfe7ecd794486a75/wp-content/themes/resources/inc/jetpack-search.php#L12-L28)
4. View the search page.

Following the instructions for adding filters to a page without usign a sidebar widget https://jetpack.com/support/search/customize-search/#template-tags :

1. On the search template, where the widget area exists, add the code described at https://jetpack.com/support/search/customize-search/#template-tags : `<?php Jetpack_Search_Template_Tags::render_available_filters(); ?>`
2. Define a couple filters using [the code here](https://github.com/INN/umbrella-gijn-resources/blob/9821ed9b70996cd796649d9ccfe7ecd794486a75/wp-content/themes/resources/inc/jetpack-search.php#L12-L28)
3. View the search page.

#### What I expected

I expect to see the toggleable checkbox items for search controls.

#### What happened instead

The filtering instructions on https://jetpack.com/support/search/customize-search/ for code or widget-based customizations to the search filters do not work. I've tried the code-based approach with Jetpack_Search::instance()->set_filters( ... ); and you can see the current approach of using the Jetpack Search widget at https://gijn2018.wpengine.com/?s=data&search+submit=.

In none of the above cases does Jetpack_Search_Template_Tags::render_available_filters(); output any filter tags, whether that function is called by the Jetpack Search widget or called directly by the template, whether the filters are defined by the widget options or by code.

The issue, as far as I can tell, is that Jetpack_Search_Template_Tags::render_filter( ... ) is not being passed any filters that have a 'buckets' argument, even when the filters are defined in the Jetpack Search widget.

Here's the code that's expecting `$filter['buckets']:

https://github.com/Automattic/jetpack/blob/6.8.1/modules/search/class.jetpack-search-template-tags.php#L83

And here's what was being passed by the widget settings as the array of `$filters` that `render_available_filters` should try to render:

```php
array (
  'taxonomy_0' => 
  array (
    'name' => 'Categories',
    'type' => 'taxonomy',
    'taxonomy' => 'category',
    'count' => 12,
    'widget_id' => 'jetpack-search-filters-2',
    'buckets' => 
    array (
    ),
  ),
  'taxonomy_1' => 
  array (
    'name' => 'Tags',
    'type' => 'taxonomy',
    'taxonomy' => 'post_tag',
    'count' => 10,
    'widget_id' => 'jetpack-search-filters-2',
    'buckets' => 
    array (
    ),
  ),
)
```

**Comment by benlk** [comment]
The corresponding Zendesk support request ID for this GitHub issue appears to be [YD6QE5-R2GP].

**Comment by bperson** [comment]
@benlk Could you give me more information about the filters you have set up? ( a screenshot of your customiser or copy-paste the code you used to setup the filters since it's in a private org, I don't have access to it, GH is 404-ing me ;) )

**Comment by benlk** [comment]
Sure can.


This is the code that was used to attempt setting the filters programmatically:

```php
/**
 * Define our custom search filters
 *
 * @link https://jetpack.com/support/search/customize-search/
 * @since Jetpack 6.8.1
 */
function resources_jp_search_setup_filters() {
	if ( class_exists( 'Jetpack_Search' ) ) {
		Jetpack_Search::instance()->set_filters( array(
			'Categories' => array(
				'name' => 'Categories',
				'type' => 'taxonomy',
				'taxonomy' => 'category', 
				'count' => 12,
			),
		) );
	} else {
		error_log(var_export( 'aaaa', true));
	}
}
// Commenting this out for now because it appears that this filter
// prevents the widget-set filters from taking effect
#add_action( 'init', 'resources_jp_search_setup_filters' );
```

These are the current search settings, provided by a Jetpack Search widget on https://gijn2018.wpengine.com/?s=GIJN

<img width="413" alt="screen shot 2019-01-11 at 3 59 08 pm" src="https://user-images.githubusercontent.com/1754187/51059354-e4024d80-15b9-11e9-83b8-4f216e275192.png">

And here's the output of that search widget:

```
<aside id="jetpack-search-filters-2" class="widget widget-1 odd default jetpack-filters widget_search clearfix"><div id="jetpack-search-filters-2-wrapper">
		<h3 class="widgettitle">Search Filters</h3></div></aside>
```

**Comment by bperson** [comment]
> @bperson can you elaborate on how buckets might end up being empty? We could follow up with improved documentation around this question, too.

`buckets` were empty because the site wasn't properly indexed, because it wasn't fully synced. I relaunched a full sync this morning which just finished and it looks like there is some categories and filters now.

**Comment by simison** [comment]
Excellent, thank you @bperson 

@benlk could you confirm if that solved the issue?

**Comment by benlk** [comment]
Yes, the filters do now appear in the Search Widget: https://gijn2018.wpengine.com/?s=gijn&search+submit=

We'll try to programmatically set the filters today.

**Comment by simison** [comment]
This seems to be solved; don't hesitate to write back here if the issue appears again!
