### ISSUE TITLE
Custom Content Types: Testimonials order

### ISSUE THREAD

**Issue by blazevivan** [Automattic/jetpack#11118]
#### Steps to reproduce the issue

1. Go to Testimonials
2. Click on Add new (create at least 3 different testimonials)
3. In attributes set order 1 to 3
4. Go to the Testimonials page 

#### What I expected

I expected to see that order of the Testimonials changed according to the order set in Attributes 

#### What happened instead
Order of the Testimonials was set by date created and Attributes order was completely ignored 

The issue is same with Classic and Block editor. The user reported the issue and I was able to reproduce it on simple and AT sites.

**Comment by jeherve** [comment]
Does the problem remain the same regardless of the theme you use?

**Comment by blazevivan** [comment]
Yes, an issue was reproduced on 3 different themes (one theme was on a user's site, and two of my test sites used different themes).
