### ISSUE TITLE
Provide a way to add hashtag to the FB sharer URL

### ISSUE THREAD

**Issue by joshuaabenazer** [Automattic/jetpack#11126]
#### Is your feature request related to a problem? Please describe.
Facebook allows you the prefill the user message with a single hashtag while sharing a URL ( https://github.com/Automattic/jetpack/blob/master/modules/sharedaddy/sharing-sources.php#L976 )

Currently the FB sharer URL in the code is hardcoded and does not have filters to add the extra hashtag parameter to it -> https://developers.facebook.com/docs/sharing/reference/share-dialog/#params_share

#### Describe the solution you'd like
Provide an option to the user to add a FB hashtag while sharing a URL, similar to how the twitter handle option is provided.

#### Describe alternatives you've considered
We could also provide a filter on the sharer url to provide more control for devs, but not sure how much useful that would be at this stage, it could lead to corrupting the URL too.

**Comment by Spellcoder** [comment]
Just wanted to note that sharer.php does have a hashtag parameter, but it may not be documented.  . Also it has a "quote" parameter which I use in a project I work on to pass a title when the URL I try to share is a PDF. For example: https://www.facebook.com/sharer.php?u=aminet.net&hashtag=%23amiga&quote=repository%20of%20amiga%20software
