### ISSUE TITLE
AMP: last AMP compatibility changes impact CSS concatenation

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#11123]
In #10945, we made changes to our AMP compatibility file that impact the way we load CSS. Unfortunately, this change impacts all site owners currently using the `jetpack_implode_frontend_css` filter

#### Steps to reproduce the issue

1. Start from a site using Jetpack 6.8.1 and with the following code snippet: `add_filter( 'jetpack_implode_frontend_css', '__return_false' );`
2. Separate CSS files are loaded by Jetpack on the frontend.
3. Update to Jetpack 6.9
4. Your code snippet does not have any impact anymore, the concatenated `jetpack.css` is loaded instead. You have to change the priority for it to start working again, like `add_filter( 'jetpack_implode_frontend_css', '__return_false', 99 );`.

I have not tested, but I suspect this also impacts the other filters in use by the AMP compatibility file.

Reported here:
https://jetpack.com/2019/01/10/jetpack-6-9-introducing-more-tools-for-the-new-block-editor/#comment-193496

**Comment by vijayaraghavanramanan** [comment]
`add_filter( 'jetpack_implode_frontend_css', '__return_false', 11 );`

itself works, not just 99.

**Comment by jeherve** [comment]
@macmanx2 confirmed this also impacts another filter on that list, `jetpack_sharing_counts`

**Comment by macmanx2** [comment]
Thanks, Jeremy!

Confirming that `add_filter( 'jetpack_sharing_counts', '__return_false', 99 );` does indeed work.

If you're using the Code Snippets plugin, simply setting the priority there to 99 doesn't seem to fix the problem, but if you change your snippet to `add_filter( 'jetpack_sharing_counts', '__return_false', 99 );` and set whatever priority level you want in the plugin, it works perfectly.

**Comment by chriscoyier** [comment]
Hey gang! Just noting I got burned by this. It's a heck of a thing to have essentially dequeued Jetpack CSS only to have it show up all the sudden by upgrading a version with no warning.

**Comment by Garconis** [comment]
It would be nice if your plugin would first check to see if any of the modules need to have your `jetpack.css` and `devicepx-jetpack.js` loaded. Right now, none of the modules that we have active within Jetpack require those files to be loaded on the frontend. Rather than having to remove those via PHP snippets, it would be good if your plugin removed them automatically when they aren't needed.

**Comment by jeherve** [comment]
@Garconis We currently treat those 2 files a bit differently, as they do different things:

- `devicepx` is loaded as soon as you activate Jetpack, as it can be useful even when no modules are active. That said, with WordPress Core's improvements with responsive images, we've been discussing ways of deprecating that feature in favor of Core, or only loading it on demand. You can follow our progress and chime in with your thoughts here: #10189
- `jetpack.css` is loaded when your site is not in development and is connected to WordPress.com, as it can be useful from that point on. Its behaviour could be improved though. That is something we've discussed in this issue: #1258

**Comment by Garconis** [comment]
@jeherve thanks! For now, I will keep both removed via PHP, but will keep an eye on the pulls/issues to adjust as needed.
