### ISSUE TITLE
Menus: Pinterest ccTLD links show chain icon 

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/jetpack#11132]
Hello! I noticed while working with a user that Pinterest shows a chain icon in a social menu if the custom link used isn't _.com_. The issue is this particular service (unlike Twitter or Facebook) uses ccTLDs instead of a redirection, so users may use these URLs and get a chain icon instead of a Pinterest icon.

My suggestion would be that we make an exception for this service and show the Pinterest icon from the moment a user enters a valid _pinterest.tld_ URL.

#### Steps to reproduce

1. Choose a theme that comes with a social links menu (eg: Radcliffe 2)
2. Go to https://site.wordpress.com/wp-admin/customize.php?autofocus%5Bpanel%5D=nav_menus
3. Add a custom link to Pinterest such as https://www.pinterest.com/wordpressdotcom/ to get a Pinterest icon
4. Change link to https://www.pinterest.fr/wordpressdotcom/ and you'll get a chain icon

#### GIF

![screen capture on 2018-04-04 at 17-24-48](https://user-images.githubusercontent.com/16645645/38317749-1607bab4-382e-11e8-8e2e-aee70a6b7a0b.gif)

**Comment by samiff** [comment]
Reported in 366636-hc for `.es`

**Comment by damiannep** [comment]
This issue came up today for .co.uk in #10039959-hc
