### ISSUE TITLE
Code Snippets

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [Automattic/jetpack#11138]
#### Is your feature request related to a problem? Please describe.
Jetpack itself has filters where users can add filters to dequeue css, js and prevent new features. The best place is to write the code is in Jetpack itself
#### Describe the solution you'd like
A code snippet screen, like custom CSS but custom PHP in this case where these filters can be added to control Jetpack behaviour and run on the action filter `get_theme`, just before theme functions.php is loaded. The code can be saved in database to avoid rewrite on update. It can be Jetpack specific: only allow filters in Jetpack to be used.

**Comment by jeherve** [comment]
That is not something we plan on adding to Jetpack in the near future. Instead, we recommend using existing plugins from the Plugins directory. You can find one of our recommendations, the Code Snippets plugin, here:
https://jetpack.com/support/adding-code-snippets/
