### ISSUE TITLE
Facebook Embeds: embed preview doesn't work in Visual Editor

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1113]
Steps to reproduce:
1. Activate the Shortcode Embeds module
2. Go to Posts > Add New, and create a new post including a Facebook URL like this one:
   https://www.facebook.com/jetpackme/posts/701668806581375
3. Publish the Post.
   - The embed is displayed properly in the post on the Frontend of your site. 
     ![screen shot 2014-09-12 at 11 28 51 am](https://cloud.githubusercontent.com/assets/426388/4247799/3c153dce-3a5f-11e4-9f59-d9b580a14d7b.png)
   - In the Text editor, I see the Facebook URL:
     ![screen shot 2014-09-12 at 11 29 59 am](https://cloud.githubusercontent.com/assets/426388/4247816/65148a0e-3a5f-11e4-836d-c3dddfc483b9.png)
   - In the Visual Editor, however, I see no embed, no placeholder, not even the URL:
     ![screen shot 2014-09-12 at 11 29 31 am](https://cloud.githubusercontent.com/assets/426388/4247808/53902388-3a5f-11e4-94e7-f2c39c61ea51.png)

I would expect to see a preview in the Visual Editor, much like for Youtube or Twitter embeds:
![screen shot 2014-09-12 at 11 32 07 am](https://cloud.githubusercontent.com/assets/426388/4247842/b3184e98-3a5f-11e4-8efb-75250f371625.png)

**Comment by jordant1089** [comment]
I've ran into this issue and began tracking it down. I've tracked the issue down to [/modules/shortcodes/facebook.php](https://github.com/Automattic/jetpack/blob/master/modules/shortcodes/facebook.php), line 40.

```
if ( defined( 'DOING_AJAX' ) && DOING_AJAX && ! empty( $_POST['action'] ) && 'parse-embed' == $_POST['action'] ) {
	return $embed . wp_scripts()->do_items( array( 'jetpack-facebook-embed' ) );
} else //...
```

It looks like the issue is the behavior of `wp_scripts()->do_items()`. It echos the script tags, which are printed before the JSON content in the ajax return. The ajax call returns the content below. 

```
<script type='text/javascript' src='https://news-dev.illinoisstate.edu/wp-includes/js/jquery/jquery.js?ver=1.12.3'></script>
<script type='text/javascript' src='https://news-dev.illinoisstate.edu/wp-includes/js/jquery/jquery-migrate.js?ver=1.4.0'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var jpfbembed = {"appid":"249643311490","locale":"en_US"};
/* ]]> */
</script>
<script type='text/javascript' src='https://news-dev.illinoisstate.edu/wp-content/plugins/jetpack/_inc/facebook-embed.js'></script>
{"success":true,"data":{"body":"<div class=\"embed\" rel=\"https:\/\/www.facebook.com\/IllinoisStateUniversity\/photos\/a.207927582443.131714.18773072443\/10153696954992444\/?type=3&theater\"><fb:post href=\"https:\/\/www.facebook.com\/IllinoisStateUniversity\/photos\/a.207927582443.131714.18773072443\/10153696954992444\/?type=3&#038;theater\"><\/fb:post>Array<\/div>","attr":{"width":960,"height":1000}}}
```

A quick way that I found to fix this was to wrap the `wp_scripts()->do_items()` in an buffer and append that to the embed content. 

```
if ( defined( 'DOING_AJAX' ) && DOING_AJAX && ! empty( $_POST['action'] ) && 'parse-embed' == $_POST['action'] ) {
	ob_start();
	wp_scripts()->do_items( array( 'jetpack-facebook-embed' ) );
	$scripts = ob_get_contents();
	ob_end_clean();
	return $embed . $scripts;
} else //...
```

**Comment by jeherve** [comment]
> Since this is getting implemented into WP core, let's just plan to remove it from Jetpack once WP 4.7 is our minimum
