### ISSUE TITLE
Jetpack Shortcode messing with Video Embed Code Field in Sensei

### ISSUE THREAD

**Issue by codestor4** [Automattic/jetpack#11141]
Steps to reproduce:

- Create a course and a lesson, publish them
- Edit the lesson and add Vimeo video embed code in the video embed code field.
- Refresh the page, the embed code turns into a shortcode (no problem).
- View the lesson on the front-end, you'll see shortcode but no video (problem).

Note: I could not reproduce this on a Jurassic Ninja site running Sensei 1.12.2, WordPress 5.0.2 and Jetpack 6.8.1.

But could reproduce it on Sensei 1.12.2, WordPress 4.9.9 and Jetpack 6.8.1.

Adam found: 

> This issue does not occur if you use Gutenberg to compose the lesson, which is likely why you couldn't repro with WP 5.0.2. We must be running the video embed code through some filters in JP that replace the embed code with a shortcode. 

Dat suggests the following fix:

> Do not let Jetpack Shortcodes converts the embedded code in the Video Embed Code field.

**Comment by jeherve** [comment]
@codestor4 What happens when you toggle the `Disable HTML security` option under Sensei > Settings > General? Does it solve the issue?

> Dat suggests the following fix:
> Do not let Jetpack Shortcodes converts the embedded code in the Video Embed Code field.

This was something that was implemented in Sensei in https://github.com/Automattic/sensei/pull/1587, but it looks like https://github.com/Automattic/sensei/pull/1631 added the option to disable this.

**Comment by jeherve** [comment]
@donnapep Would it be an option to add `do_shortcode` back to the output of the field here:
https://github.com/Automattic/sensei/blob/c0e4faabe200d1bf0289294dc0d5a6ab60709505/includes/class-sensei-course.php#L467

It was removed in https://github.com/Automattic/sensei/pull/1631 , and I believe that is what is causing the regression here.

**Comment by donnapep** [comment]
@jeherve I'm not sure that's the right line number to change. In https://github.com/Automattic/sensei/pull/1631, `do_shortcode` was removed [here](https://github.com/Automattic/sensei/pull/1631/files#diff-c0922c04ec6aa809fbd289ed7aabc9d7L2938), but is still called (albeit a bit sooner) [here](https://github.com/Automattic/sensei/pull/1631/files#diff-c0922c04ec6aa809fbd289ed7aabc9d7R2940).

**Comment by jeherve** [comment]
Ah, indeed, my bad. Does the problem remain when calling `do_shortcode` after `Sensei_Wp_Kses::maybe_sanitize`?

**Comment by donnapep** [comment]
@codestor4 I just tried this again on WordPress 4.9.9, Sensei 1.12.2, Jetpack 6.9 and although the video embed code changes to a shortcode, the video still shows on the front-end. Can you confirm?

**Comment by codestor4** [comment]
> I just tried this again on WordPress 4.9.9, Sensei 1.12.2, Jetpack 6.9 and although the video embed code changes to a shortcode, the video still shows on the front-end. Can you confirm?

@donnapep Tested this once again and it still doesn't work on the same setup you mentioned. I have now added you as admin to my staging site and DM'd credentials to you on Slack!

**Comment by donnapep** [comment]
@jeherve It's because we're now running the output of the video embed box through `wp_kses` for better security - https://github.com/Automattic/sensei/pull/2296/files#diff-13aafd4aa94b68d0038331ecdc377fafR189.

Is Jetpack explicitly filtering out certain tags in `wp_kses`?

**Comment by jeherve** [comment]
This would depend on the environment (Jetpack or wpcom), the user role, and what you enter as your embed code. Do you use shortcodes there, or an iFrame from Vimeo / YouTube? Do you have an example I could use?

**Comment by jeherve** [comment]
Related discussion:
p1549295343010100-slack-sensei

In this case Jetpack should not do anything to that content. In my test, that embed code remains exactly the same when inside a post.

If, however, an author or editor were to paste that shortcode, Jetpack would convert it into `[vimeo 8733915 w=640 h=360]` on save.

We have a hook Sensei could use to disable specific embeds inside the module; that might be the easiest solution.
Here is the filter, with an example:
https://developer.jetpack.com/hooks/jetpack_shortcodes_to_include/

Here is the list of embeds that are enabled, and that you could disable:
https://github.com/Automattic/jetpack/tree/master/modules/shortcodes

I guess `vimeo.php` and `youtube.php` would be a good start.

**Comment by donnapep** [comment]
@codestor4 Could you open an issue for this in the Sensei repo? Thx.

**Comment by donnapep** [comment]
Logged as https://github.com/Automattic/sensei/issues/2420.

**Comment by codestor4** [comment]
@donnapep sorry I couldn't get to this sooner as the new lead role consumed a lot of my time. It should get better as I get used to it. Thanks for creating an issue though! <3
