### ISSUE TITLE
LinkedIn API: Update to v2 

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#11145]
The LinkedIn API is being [updated](https://engineering.linkedin.com/blog/2018/12/developer-program-updates). We'll need to update to v2 for the Feb release, since the v1 API will no longer work after March 1. 

- [x] Update publicize API's 
- [x] Update any other calls made to LinkedIn API (Sharing... Others?)
- [x] Ensure the UX for existing LinkedIn connections is not bad/broken

**Comment by eliorivero** [comment]
This is ready for review in

D23425-code

**Comment by jeherve** [comment]
I've run some tests with all 3 patches applied, and it seems to work well in my tests 👍 👏 !
