### ISSUE TITLE
Markdown: Inline HTML & IDs from Extra Markdown not working

### ISSUE THREAD

**Issue by aybassiouny** [Automattic/jetpack#11147]
#### Steps to reproduce the issue
1. Start a new [jetpack](https://jurassic.ninja/create/) site
2. Activate Markdown
3. Start a new post and add the following in a markdown block: 

```
## Test inline html

<p> There should be no html tags </p>

## test anchors       {#header2}

There should be an an id for the above line, not extra markdown syntax.

```
4. [Result](https://due-manx.jurassic.ninja/2019/01/16/test/)

#### What I expected

According to Jetpack's [Markdown documentation](https://jetpack.com/support/markdown/), the flavor of MD used is [Markdown Extra](https://michelf.ca/projects/php-markdown/extra/). However, both [IDs](https://michelf.ca/projects/php-markdown/extra/#spe-attr) and [inline html](https://michelf.ca/projects/php-markdown/extra/#html) should be supported, which steps above show is not the case.   

#### What happened instead

Special syntax is ignored and rendered on the screen instead. As a result, I am completely blocked from adding in-page links on my blog. 

**Screenshots**

![image](https://user-images.githubusercontent.com/342331/51226431-4c2b9900-1904-11e9-8de0-6215f6460288.png)

**Comment by jeherve** [comment]
Thanks for the feedback!

That's indeed a bit confusing. Jetpack's Markdown feature follows the Markdown Extra spec. The Markdown block, however, follows a different implementation that follows the [CommonMark spec](https://spec.commonmark.org/). CommonMark does not support manually set IDs as far as I can tell. You can check this thread to find out more:
https://talk.commonmark.org/t/anchors-in-markdown/247/32
This is also discussed here:
https://github.com/markdown-it/markdown-it/issues/28

Adding raw HTML, however, is definitely something we could support in our block. I created an issue to track this in the `wp-calypso` repository, where we develop the block:
https://github.com/Automattic/wp-calypso/issues/30188

**Comment by bikedorkjon** [comment]
This came up in 2019865-zen
