### ISSUE TITLE
Carousel: Long captions break overflow and overlay

### ISSUE THREAD

**Issue by sirreal** [Automattic/jetpack#11152]
Image carousels are designed to fit within the browser window without scrolling. They display on top of a black overlay. Depending on certain conditions —like a very long image caption– they may not fit within the browser window. They overflow, and when the window is scrolled the visual result is broken.

![bad-carousel](https://user-images.githubusercontent.com/841763/51268473-8195bc80-19c0-11e9-8a47-dc826d14f1c1.png)

#### Steps to reproduce the issue

1. The conditions must be correct for carousels to display. Enabling suggested settings on a new Jetpack site is sufficient.
1. Add a gallery with a few images.
1. Add a very long caption to an image.
1. Click on the image to view it in the carousel.
1. When the carousel is displayed, scroll down to see the broken visual.

#### What I expected

The carousel should fit nicely within the screen. Long captions might need to fit within a scrollable container. Alternatively, the window could scroll but the black overlay should cover the entire page.

#### What happened instead

The display does not look good.

Reported in 1721369-zen

**Comment by jamiepalatnik** [comment]
Also reported here: 9670332-hc
Followed up in 1732011-zen

**Comment by sirreal** [comment]
A temporary workaround that seems to give good results is to add this custom CSS:

```css
.jp-carousel-overlay {
  position: fixed !important;
}
```
