### ISSUE TITLE
Carousel: image meta data not added to image when image is loaded via AJAX

### ISSUE THREAD

**Issue by abhijitrakas** [Automattic/jetpack#11151]
[This filter](https://github.com/Automattic/jetpack/blob/6.8.1/modules/carousel/jetpack-carousel.php#L79) not working on ajax call. It's perfectly working on page load and carousel also working fine.  

I have `Load more` button to load images, on click of that button I am fetching images using ajax call. But during this ajax call [the filter](https://github.com/Automattic/jetpack/blob/6.8.1/modules/carousel/jetpack-carousel.php#L79) doesn't get called and the image data attribute doesn't load. 

Because data attribute doesn't load for all newly added images the carousel doesn't work for those images.

**Comment by jeherve** [comment]
I'm afraid Carousel wasn't built for this use-case. This is not something we plan on implementing right now, but if you want to contribute a PR to add this feature, we'll happily review it!

Thanks for the feedback.

**Comment by abhijitrakas** [comment]
@jeherve  After digging in the code, I found that `wp` hook not gets called on REST-API call. Hence [this action](https://github.com/Automattic/jetpack/blob/master/modules/carousel/jetpack-carousel.php#L32) not get called.

Changes in [this PR](https://github.com/Automattic/jetpack/pull/10945) creates an issue. Probably [this action](https://github.com/Automattic/jetpack/blob/master/modules/carousel/jetpack-carousel.php#L32) should call on `init` hook like [it was before](https://github.com/Automattic/jetpack/blob/6.8.1/modules/carousel/jetpack-carousel.php#L32). But, I think if we revert it back then, it creates issues for AMP pages.

**Comment by jeherve** [comment]
That makes sense indeed, nice catch! That PR has created other issues, so we'll see what we can do to fix this.

Related: #10945
