### ISSUE TITLE
No need for setting comment cookies which serve no purpose

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [Automattic/jetpack#11164]
If I activate subscriptions, it also allows the choice of having the commenter follow the blog and get notifications for other comments, in addition to the subscription widget in the sidebar. 

However, a Jetpack user can choose not to have these and just have the subscription widget. There is no need for cookies even though it sets expired ones.

The relevant code is here: https://github.com/Automattic/jetpack/blob/master/modules/subscriptions.php#L761-L771

**Comment by jeherve** [comment]
> However, a Jetpack user can choose not to have these and just have the subscription widget. 

That is correct. In this case, Jetpack will not set up in any cookies for you. The cookies are only set when leaving a comment, and if at least one of the checkboxes is set while leaving the comment. If you remove the checkboxes, no cookies will ever be set.

**Comment by vijayaraghavanramanan** [comment]
Cookies are set with expiry in the far past. It shows up when you click the lock icon in the address bar. I observe jetpack entries even though I don't have the boxes above the submit button. I just have the subscription box in the sidebar.

**Comment by jeherve** [comment]
Do the cookies remain when you flush your browser's cookies, and then browse your site again? I suspect the cookies you are seeing may have been set a long time ago.
