### ISSUE TITLE
Fetch alt text and description with Jetpack_PostImages::get_image

### ISSUE THREAD

**Issue by aldavigdis** [Automattic/jetpack#11175]
#### Is your feature request related to a problem? Please describe.
During my work on the Related Posts block, I noticed that `Jetpack_PostImages::get_image()` in the PHP code only gets the image dimensions and the URL for the given image. We should expand this to include the alt text and description.

#### Describe the solution you'd like
Alt text set in the Media Library and the description would be useful here in the context of accessibility. Adding `alt` and `description` keys to the array returned by the `Jetpack_PostImages::get_image()` function would be very useful for accessibility and presentation of images in general.

#### Describe alternatives you've considered
Looking at the Related Posts block, I was forced to use the post title instead of the image's actual alt text, which results in a repeated title in the a11y context, which is undesirable even if it satisfies automated checks that generally just check if the `alt` attribute is set at all.

**Comment by jeherve** [comment]
That's a good idea. It would also allow us to fix issues like #10593.

> Adding `alt` and `description` keys to the array returned by the `Jetpack_PostImages::get_image()` function would be very useful

While this makes sense, I wonder if we should make a conscious choice about what we return before we start working on this. For images coming from your own Media Library, WordPress offers you 4 ways to describe that image:
- A title
- A caption
- A description
- An Alt tag.

What are the values that would be useful for us to fetch and store, to use them in other areas of Jetpack?

**Comment by aldavigdis** [comment]
@jeherve — In https://github.com/Automattic/jetpack/pull/11339, which is a dependency of https://github.com/Automattic/jetpack/pull/11324, I decided that an alt_text attribute/key would be sufficient for the time being.

The question remains for images from Gravatar for example, which does not supply an alt text.
