### ISSUE TITLE
Top Posts & Pages Widget: Remove the current post from the widget.

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#11174]
#### Is your feature request related to a problem? Please describe.

Exclude the current post from showing up on the top posts widget https://jetpack.com/support/extra-sidebar-widgets/top-posts-pages-widget/

#### Describe the solution you'd like

I think this does make sense as nobody wants to display a link to the post they are already on

#### Describe alternatives you've considered

Currently, users can use `Example 2: Remove the current post from the Top Posts & Pages Widget.` from https://developer.jetpack.com/hooks/jetpack_widget_get_top_posts/

#### Additional context

From 1734390-zen.
If we think this is worth to integrate into our code directly, I am happy to create a PR for this.

**Comment by jeherve** [comment]
While this makes sense to add to Jetpack in my opinion, we would need to solve #2369 before we implement this here.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
