### ISSUE TITLE
Multisite: Jetpack's network admin "sites" page is broken

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#11186]
#### Steps to reproduce the issue

1. New Jurassic Ninja multisite on subdir 
2. Do not connect Jetpack yet
3. Add a new site to your multisite 
4. Navigate to Jetpack > Sites `/wp-admin/network/admin.php?page=jetpack`
5. See errors

#### What I expected
- A list of sites? 

#### What happened instead
- Some notice flashes on the screen for less than a second, and then nothing. Left with the Jetpack header, footer, and some console errors. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7129409/51636512-77773f00-1f27-11e9-8bf0-b543e5c9bdb1.png)

**Comment by jeherve** [comment]
It looks like this was caused by #9952 (cc @enejb). Reverting this fixes the issue. #11189 should help.

**Comment by jeherve** [comment]
@enejb I think we all missed it, no worries! It's interesting that we got no reports about it at all in 6 months. I guess Multisite is not that important. ¯\_(ツ)_/¯
