### ISSUE TITLE
Need upgrade as per current PHP  Version

### ISSUE THREAD

**Issue by senindiaonline** [Automattic/jetpack#11187]
#### Steps to reproduce the issue

1.
2.
3.

#### What happened instead

Notice: jetpack_lazy_images_skip_image_with_atttributes used for an anonymous function is deprecated since version ! Use jetpack_lazy_images_skip_image_with_attributes instead. in /var/www/html/senindiaonline.in/wp-includes/functions.php on line 3923

**Comment by jeherve** [comment]
The filter you added to your site, `jetpack_lazy_images_skip_image_with_atttributes`, is deprecated. You will need to edit the code on your site to use `jetpack_lazy_images_skip_image_with_attributes` instead (notice that the filter name is almost the same, we only removed one `t`).
