### ISSUE TITLE
Undefined index: page in _inc/lib/admin-pages/class.jetpack-admin-page.php

### ISSUE THREAD

**Issue by amandato** [Automattic/jetpack#11213]
$_GET['page'] not handled correctly in _inc/lib/admin-pages/class.jetpack-admin-page.php

#### Steps to reproduce the issue

1. Enable debug mode on site
2. Use any plugin that performs ajax in the wp-admin area
3. Notice messages will appear such as: 

> Notice: Undefined index: page in /home3/jennywhe/public_html/thejoysofbingereading/wp-content/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-admin-page.php on line 67

#### What I expected
No "Undefined index: page" messages when using this plugin.

#### What happened instead
I get the following:

> Notice: Undefined index: page in /home3/jennywhe/public_html/thejoysofbingereading/wp-content/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-admin-page.php on line 67

**Screenshots**
Not applicable

Possible code to replace on line 67: `( 'admin.php' === $pagenow && isset( $_GET['page'] ) && 'jetpack' === $_GET['page'] )`

Notice the addition of `isset( $_GET['page'] )` before using `$_GET['page']`.

**Comment by jeherve** [comment]
Thanks for the report. This was fixed in #11139
