### ISSUE TITLE
Mobile theme assumes gallery posts have wp-attachment

### ISSUE THREAD

**Issue by Praful** [Automattic/jetpack#11228]
#### Steps to reproduce the issue
1. Use REST API to add a post of type "gallery". The post should have several images but even if it doesn't, make the format "gallery".
2. Set Jetpack to use the mobile theme.
3. View post in Firefox or Chrome using resonspive mode (to trigger Jetpack's mobile theme).

#### What I expected

To see the post, which I do in non-mobile mode and mobile mode with other themes.

#### What happened instead
Some of the post (featured media) appears and these errors:

``
[30-Jan-2019 14:28:35 UTC] PHP Notice:  Trying to get property 'ID' of non-object in /var/www/html/wp-content/plugins/jetpack/modules/minileven/theme/pub/minileven/content-gallery.php on line 38
[30-Jan-2019 14:28:35 UTC] PHP Notice:  Trying to get property 'ID' of non-object in /var/www/html/wp-content/plugins/jetpack/modules/minileven/theme/pub/minileven/content-gallery.php on line 39
[30-Jan-2019 14:28:35 UTC] PHP Notice:  Trying to get property 'ID' of non-object in /var/www/html/wp-content/plugins/jetpack/modules/minileven/theme/pub/minileven/content-gallery.php on line 40
[30-Jan-2019 14:28:35 UTC] PHP Notice:  Trying to get property 'ID' of non-object in /var/www/html/wp-content/plugins/jetpack/modules/minileven/theme/pub/minileven/content-gallery.php on line 41
``

Looking at the code in content-gallery.php, I see that it is expecting wp-attachment objects to be associated with the post. This is not the case when the post is created via the REST API. It is the case if the post is created using the WordPress UI.

I disabled all other plugins to create the bug. If I don't use Jetpack's mobile theme and use the mobile theme of another theme eg twentyfifteen, all is fine.

**Screenshots**

**Comment by jeherve** [comment]
> Use REST API to add a post of type "gallery". The post should have several images but even if it doesn't, make the format "gallery".

Could you walk me through the steps I could follow to reproduce this issue? Did your posts have single images, or a gallery? Were those images part of your media library? If not, how did you insert them in your post?

Thank you!

**Comment by Praful** [comment]
Hello



I am using [WP-API](http://wp-api.org/node-wpapi/using-the-client/), which wraps the WordPress API.

I upload the media using the media API of WP-API by wrapping it in a function like this:

````javascript
  create({ key, caption = null, date = null }) {
    const fullpath = `${this.source_image_dir}/${key}`
    const newMedia = {
      alt_text: key,
    }
    if (caption) newMedia.caption = caption
    if (date) newMedia.date = Utils.unixDateToString(date)

    const result = this.wp.media().file(fullpath).create(newMedia)
      .then(data => {
        Console.log(`Created media ${key}, id: ${data.id}`)
        return data
      })
      .catch(error => {
        Console.log(`Error creating media: ${key}`)
        throw error
      })

    return result
  }
````

This is an extract from a class I've written, which I'm developing and will eventually put on Github when it's stable. You'll need to change `this.source_image_dir`. You can hard-code the date since you won't have my function.

After I've uploaded the required media, I create a post using something like this:

````javascript
    const result = this.wp.posts().create(newPost)
      .then(data => {
        Utils.log(`Created post ${fbPost.title}, id: ${data.id}`)
        return data
      })
      .catch(error => {
        Utils.log(`Error creating post: ${fbPost.title}`)
        Utils.printError(error)
        throw error
      })
````

Again this is an extract from another class but will point you in the right direction.

The ``newPost`` object has some or all of the following properties set (most of which are probably irrelevant for this issue but I include for completeness):

- title
- content
- status
- date
- tags
- category
- format
- featured_media 

This issue occurs when format is set to "gallery" and the content contains a gallery specified by the gallery short code eg

````javascript
  newPost.content='[gallery id="123,789"]'
````

where "ids" is the value ids of the images uploaded earlier via REST.

I tried the above via the UI and the Jetpack mobile theme worked. Therefore, I suspect that media is different when uploaded via REST. You might just want to upload media via REST and examine the resulting JSON via a browser.

On a related but different note, since you're looking at this, if the format is set to "link" and the content is an external URL, the Jetpack mobile theme behaves incorrectly. What should happen is that when you look at the post, the title of the post becomes a link to the external URL. Instead, the Jetpack mobile theme makes the post title a link back to itself! Again this works on a non-mobile theme. Specifically, for this:

````javascript
newPost.content='My new post'
newPost.format='link'
newPost.content='<a href="https://www.google.com"/>'
````

the title (_My new post_ in this case) should be a link to Google when viewing the post.

Thanks!

**Comment by jeherve** [comment]
Thanks for the extra details. Could you give #11238, and let me know if that fixes the problem for you?

> if the format is set to "link" and the content is an external URL, the Jetpack mobile theme behaves incorrectly.

I am afraid the theme does not support the link post format at all. Jetpack's Mobile Theme only provides custom views for the Gallery post format. All the other post formats are treated like regular posts, and as a result the post title does indeed link to the post. We have no plans on adding support for more post formats, but if you'd like to submit a Pull Request to add support for the Link Post Format inside [this template file](https://github.com/Automattic/jetpack/blob/f098dbe15b348e8d41a1ef97ea65b4e8d7224900/modules/minileven/theme/pub/minileven/content.php#L22), we'll happily review it!

**Comment by Praful** [comment]
Thanks for the speedy response. The new version has fixed the defect.

I have just started using WordPress and am working on creating a site - and therefore still learning. However, when I've finished, I'll revisit the link issue (and, if appropriate, other post formats). For now, I'm trying to create a minimal site and that feature is not essential.

Thanks again.
