### ISSUE TITLE
Update character illustration color

### ISSUE THREAD

**Issue by drw158** [Automattic/jetpack#11229]
[This illustration](https://github.com/Automattic/jetpack/blob/master/images/characters.svg) is an svg with a png embedded inside of it. I could not update the colors because it's not a vector file.

If possible the source file should be provided so that the colors can be updated.

![screen shot 2019-01-30 at 10 37 25 am](https://user-images.githubusercontent.com/618551/51996773-0d0c5480-247b-11e9-8701-ccbba13156c9.png)

cc @joanrho

**Comment by jeherve** [comment]
Related: #11198
