### ISSUE TITLE
Sitemaps: Reduce JP_NEWS_SITEMAP_INTERVAL time in development mode

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/jetpack#11232]
When `JETPACK_DEV_DEBUG` is `true`, the time for `JP_NEWS_SITEMAP_INTERVAL` should be reduced from `12 * HOUR_IN_SECONDS` to a smaller value, like 1 minute or 1 second.

Perhaps this value can be filterable, or can check for the presence of another constant.

```php
if ( ! defined( 'JP_NEWS_SITEMAP_INTERVAL' ) ) {
	if ( defined( 'JETPACK_DEV_DEBUG' ) && true === JETPACK_DEV_DEBUG ) {
		if ( defined( 'JP_NEWS_SITEMAP_INTERVAL_DEBUG' ) ) {
			define( 'JP_NEWS_SITEMAP_INTERVAL', JP_NEWS_SITEMAP_INTERVAL_DEBUG );
		} else {
			define( 'JP_NEWS_SITEMAP_INTERVAL', 60 );
		}
		
	} else {
		define( 'JP_NEWS_SITEMAP_INTERVAL', 12 * HOUR_IN_SECONDS );
	}
}
```

**Comment by paulschreiber** [comment]
@jeherve does the approach above work for you? Can I submit a PR with that?

Are there other, similar constants that should be adjusted while in development mode?

**Comment by paulschreiber** [comment]
@jeherve Can you submit a PR with those changes?

**Comment by jeherve** [comment]
@paulschreiber I am working on the upcoming version of Jetpack at the moment (we're currently in the Beta period), so feel free to have a go at it, I'll be happy to review any PR.

For now, I think something like this in `modules/sitemaps/sitemap-constants.php` would be a good start:

```php
if ( defined( 'JETPACK_DEV_DEBUG' ) && JETPACK_DEV_DEBUG ) {
	define( 'JP_SITEMAP_INTERVAL', 60 );
	define( 'JP_NEWS_SITEMAP_INTERVAL', 60 );
}
```

What do you think?
