### ISSUE TITLE
Hidden textarea in comments needs aria-hidden="true"

### ISSUE THREAD

**Issue by NicktheGeek** [Automattic/jetpack#11231]
During an accessibility audit for a site using Jetpack with the comments module it was reported that the comment form needed some changes.

> This textarea has a lot of styles to hide it, but it's still in the DOM. Add aria-hidden="true" to remove this from the Accessibility API.
> 
> `<textarea aria-hidden="true" tabindex="-1" style="position: absolute; top: -999px; left: 0px; right: auto; bottom: auto; border: 0px; padding: 0px; box-sizing: content-box; word-wrap: break-word; overflow: hidden; transition: none; height: 0px !important; min-height: 0px !important; font-family: Arial, Helvetica, Tahoma, Verdana, sans-serif; font-size: 14px; font-weight: 400; font-style: normal; letter-spacing: 0px; text-transform
: none; text-decoration: none solid rgba(0, 0, 0, 0.7); word-spacing: 0px; text-indent: 0px; line-height: normal; width: 577px;" class="autosizejs ">`

#### Steps to reproduce the issue

1. Enable Comments for WordPress and the Jetpack module
1. Visit a post or page with comments enabled
1. View page source/inspect the comment form

#### What I expected
`<textarea>` hidden with JS/CSS should also include `aria-hidden="true"` attribute.

#### What happened instead
The aria-hidden attribute is not present.

**Comment by uxcitizen** [comment]
Also tracking in VIP ticket: #88679

**Comment by uxcitizen** [comment]
Element is created in `jquery.autoresize.js`. 

I've drafted a proposed revision in `D23814-code`.

**Comment by alexiskulash** [comment]
This revision has been deployed in `r187941`. 

Thank you @NicktheGeek @uxcitizen @jeherve and @GaryJones!
