### ISSUE TITLE
top-posts.php returns wrong number of posts if days is set larger than 2

### ISSUE THREAD

**Issue by bsugerman** [Automattic/jetpack#11235]
I'm trying to change `top-posts.php` to show the most-viewed posts over a longer duration than just the last two days. But as I increase the value of `$days`, the number of posts that are actually returned becomes increasingly different from the value of `$count`.

Example: 

* if `$days=2` and `$count=5` then the top 5 posts are returned.
* if `$days=4` and `$count=5` then only the top 4 posts are returned. 
* if `$days=10` and `$count=5` then only the top 3 posts are returned.
* if `$days=365` and `$count=5` then only 1 post is returned. 

Hoping this is an easy fix, because I'd like to show the most-viewed posts over the entire lifetime of my site.

**Comment by jeherve** [comment]
Could you contact us via [this contact form](https://jetpack.com/contact-support/?rel=support) with more information about your site, how you customize that value (I assume you use `jetpack_top_posts_days`), and what your widget settings are (the post types you chose to display can have an impact here)? Once we have more information we should be able to investigate.

Thank you.
