### ISSUE TITLE
Accessibly concern: nested <a> within <label>

### ISSUE THREAD

**Issue by chriscoyier** [Automattic/jetpack#11236]
#### Steps to reproduce the issue

1. Enable Jetpack Elastic Search feature
2. Use the search/filters widget
3. You'll get sorting and filtering options, like this:

<img width="356" alt="screen shot 2019-01-31 at 7 00 51 am" src="https://user-images.githubusercontent.com/69156/52062762-fa028e80-2525-11e9-8e06-09b89f3eb249.png">

The issue is that the HTML is like this for those checkboxes:

```
<li>
					<label>
						<input type="checkbox" checked="checked" style="cursor: inherit;">&nbsp;
						<a href="https://css-tricks.com/?s=flexbox&amp;orderby=relevance&amp;post_type=post%2Cpage%2Cguide">
							layout&nbsp;(12)						</a>
					</label>
				</li>
```

Those are _nested_ interactive elements. The label itself is interactive (clicking labels activates the checkbox), and the anchor link is interactive (it's a link). 

I had an accessibility audit done on my site and they tell me:

> Nesting one interactive element inside of another (for example, a link inside of a checkbox label) creates a confusing, annoying experience for someone navigating with assistive technology and/or who has motor control or cognitive concerns.

**Comment by gibrown** [comment]
@ebinnion I remember there were a bunch of complications with how we ended up with this structure to make things work for both reloading the page and getting it to work in different themes. Do you happen to remember any details?

**Comment by bluefuton** [comment]
Happily, this will be fixed by Instant Search, which uses a `<label>` only.

<img width="351" alt="Screen Shot 2020-01-17 at 15 16 19" src="https://user-images.githubusercontent.com/17325/72578885-54198100-393c-11ea-906c-0f21d6137b0c.png">

Thanks for the report @chriscoyier!
