### ISSUE TITLE
Copy a post: Content not copied when using Block editor and default post format set in Settings > Writing

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#11256]
#### Steps to reproduce the issue

0. Make sure your theme supports post types (such as `Twenty Seventeen`)
0. Under Settings > Writing, set a default post format other than "Standard"
1. Go to `wp-admin/post-new.php`
2. Set 'Gallery' or 'Image' post format
3. Add a paragraph and gallery blocks as a content
4. Publish and try to copy the post.
5. Post copied without content

#### What I expected

post content is copied no matter what post format I used

#### What happened instead

See reproduction steps

![screencast 2019-02-04 16-09-44](https://user-images.githubusercontent.com/5654161/52199029-7df6a680-2897-11e9-8a44-172533afddeb.gif)

**Comment by jeherve** [comment]
I believe this is caused by the default content added by the Block editor when you've set a default post format for your site; it overwrites the content that is brought over by Jetpack.

This was implemented here:
https://github.com/WordPress/gutenberg/pull/4554

**Comment by jeherve** [comment]
@kwight Maybe we should handle content a bit differently when in the block editor, and load the original post's content into the editor later?

**Comment by brbrr** [comment]
> jeherve changed the title Copy a post: Content not copied for non-standard post formats is some cases Copy a post: Content not copied when using Block editor and default post format set in Settings > Writing

FWIW - it also reproducible when post type was set manually on the original post.

**Comment by kwight** [comment]
Hm, I'll look into this today. Very intentionally, I've kept things so that all work is done before we even know what editor is being used – so that the editor should never be a factor. Maybe I've just missed some proper post format handling.

**Comment by jeherve** [comment]
It seems the block editor and its reusable blocks get a bit in the way, because they add some default content to the editor after the editor is initiated.

**Comment by jeherve** [comment]
@chuckreynolds That is to be expected. Jetpack's Copy Post feature does not copy post meta, so data from ACF will be copied from one post to the next.

**Comment by kwight** [comment]
@chuckreynolds Note that the hooks do exist for any plugin to add their own support 👍

**Comment by jeherve** [comment]
> Note that the hooks do exist for any plugin to add their own support

👍 I should have mentioned that, my bad. For reference, the hooks are available here:
https://developer.jetpack.com/module/copy-post/

And here is the module itself:
https://github.com/Automattic/jetpack/blob/7.0/modules/copy-post.php

**Comment by jeherve** [comment]
> I would assume however that Jetpack would take post meta as part of the "copy"

That's a good point. That's something we've opted not to do, as it can sometimes have some unintended consequences, when post meta is used to store data that has to remain unique to a post. An example can be WooCommerce product meta data, or Jetpack Publicize information (whether a post has been publicized or not). Depending on the feedback we get in the next few weeks / months about this new feature, we may reconsider and consider switching to some kind of post meta blacklist of things that should not be copied for example.

**Comment by chuckreynolds** [comment]
> we may reconsider and consider switching to some kind of post meta blacklist of things that should not be copied for example.

Cool - I can understand it to not be high on the triage list at this point but I think that's definitely something to explore moving forward. Thanks for listening. Cheers!
