### ISSUE TITLE
Support Pinterest sharing counts in unofficial icons

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#1126]
Recently, we added Sharing counts to the official Pinterest button. The API returns the counts without needing auth or a token ( http://api.pinterest.com/v1/urls/count.json?callback=receiveCount&url=http://flagshipwp.com/giveaway/ ), so we should be able to insert these into the unofficial buttons as well.

Requested in https://twitter.com/rob_neu/status/513453897776513026

**Comment by alinclamba** [comment]
We've got a recent user in forum with this issue: https://wordpress.org/support/topic/remove-pinterest-sharing-button-count-to-omit-connection-to-pinterest-api/#post-17130045

Reported in Slack: p1697291956617699-slack-CDLH4C1UZ
