### ISSUE TITLE
Large logo in Screen options tab

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#11265]
Jetpack logo is a tad bit too big at WP dashboard Screen options:

<img width="1432" alt="screenshot 2019-02-04 at 22 13 43" src="https://user-images.githubusercontent.com/87168/52234580-af3c9a00-28ca-11e9-839a-c55cf2f081b2.png">

- Latest Jetpack master
- Ensure you've built assets with `yarn build`
- Open `/wp-admin/` and press "Screen options" open
- Witness massive Logo 💥 

Browser: Firefox

**Comment by jeherve** [comment]
This was caused by #10958, where I changed the name of the widget.

**Comment by supernovia** [comment]
Another report here: https://twitter.com/jordonzook/status/1098632284020899841
