### ISSUE TITLE
MailChimp block: Update texts

### ISSUE THREAD

**Issue by sirreal** [Automattic/jetpack#11297]
Some copy already introduced in the MailChimp ~shortcode~ block needs review (👋 @Automattic/editorial 🙇). Please review these texts and let us know of any changes:

- `title`
  > Join my email list
- `emailPlaceholder`
  > Enter your email
- `submitLabel`
  > Join My Email List
- `consentText`
  > By clicking submit, you agree to share your email address with the site owner and MailChimp to receive marketing, updates, and other emails from the site owner. Use the unsubscribe link in those emails to opt out at any time.
- `processingLabel`
  > Processing…
- `successLabel`
  > Success! You've been added to the list.
- `errorLabel`
  > Oh no! Unfortunately there was an error. Please try reloading this page and adding your email once more.

If the usage of any of these texts in unclear, please let me know and I'll provide more screenshots:

![screen shot 2019-02-07 at 09 38 18](https://user-images.githubusercontent.com/841763/52399320-2ab16d80-2abc-11e9-9ce7-bf04945f6349.png)

cc: @jeherve @jeffersonrabb @artpi 

Via https://github.com/Automattic/jetpack/pull/11092/files/2655ec90865057cbec48a6622ff5b09891df5911#diff-87c09e43ae364fd1e5472c2476a9d860

**Comment by michelleweber** [comment]
Let's sentence-case the button text, so "Join my email list" and the success label to "Success! You're on the list." 

And let's change the "Oh no!..." to  "Whoops! There was an error and we couldn't process your subscription. Please reload the page and try again." -- "oh no" seems a little too dramatic for not being able to join an email list :)

**Comment by sirreal** [comment]
Thanks @michelleweber, I'll handle these changes 👍
