### ISSUE TITLE
Mailchimp block: View form is rendered when connection is broken

### ISSUE THREAD

**Issue by sirreal** [Automattic/jetpack#11290]
#### Steps to reproduce the issue

1. Follow the steps to produce a new mailchimp block
2. Add the block
3. View it on the frontend
4. Disconnect MailChimp from your account
5. The editor will show a placeholder, but the block is still rendered view-side.

#### What I expected
Remove the block and/or show some error messaging.

#### What happened instead

The block is still rendered.

cc: @artpi / @jeffersonrabb

**Comment by artpi** [comment]
> Remove the block and/or show some error messaging.

That is actually pretty impossible to do in current situation and requires reworking the whole connection logic.

Connection is removed from keyring, but sites are not "notified" of that.  I tried to do this, but disconnect hook is not called properly in keyring and its a wider issue.
I would link here, but because of oxygen in the open, I cannot.

This is of course not ideal, but how should it be done? Should we loop through all the sites?
Anyways, its impossible to fix in JP, has to be wpcom codebase.

**Comment by jeffersonrabb** [comment]
I would think this would be doable by simply replicating the logic from the API ( https://github.com/Automattic/jetpack/blob/master/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-mailchimp.php#L40-L50 ) in the block's `render_callback`. If the logic returns false, we return null and the block will not be rendered. Any reason why this wouldn't work?

**Comment by jeffersonrabb** [comment]
> Connection is removed from keyring, but sites are not "notified" of that. I tried to do this, but disconnect hook is not called properly in keyring and its a wider issue.

If correct, this will affect the block in the editor too. If the Mailchimp connection has been disconnected, the block will continue to appear in the editor as if usable. The only action which would cause the block to go back to it's pre-connected state would be to unset the list selection.

**Comment by artpi** [comment]
> Any reason why this wouldn't work?

The mere existence of keyring id does not tell us if that keyring id is in fact working.
And we will not know that without doing both of these:
a) querying keyring DB
b) doing request to mailchimp to confirm that in fact, this token is working and user did not disconnect in Mailvchimp panel

**Comment by jeffersonrabb** [comment]
From my testing, it didn't seem like broken keyring ID was the crux of the issue. I found that:

1) If I go to the WP.com Sharing interface and unset the list, the Jetpack site is informed and the option is updated. This flow is perfect. 😄 
2) If I go to WP.com Sharing interface and disconnect Mailchimp by clicking the `Disconnect` button, the Jetpack site is _not_ informed and the option remains the same as it was before, with both a keyring ID and list. This is the situation where the block is broken. 😞 

Couldn't the Jetpack site's local option be unset after a disconnection is requested? Alternatively we could go back to the approach where the Jetpack API makes a server-to-server API call to WP.com to get status from the absolute source of truth, but the structure is much simpler now and hopefully we wouldn't have to do this.

**Comment by artpi** [comment]
> Couldn't the Jetpack site's local option be unset after a disconnection is requested?

Yes, this would solve 95% of the issues. Definitely.
But we need to loop through all the sites.
Also, 

>  I tried to do this, but disconnect hook is not called properly in keyring

But I was not very persistent :)

**Comment by jeffersonrabb** [comment]
Anything I can do to help?

**Comment by artpi** [comment]
I will share link privately becuase I don't see how can I conform to processes and document it here.

**Comment by artpi** [comment]
@jeffersonrabb fix here: D24426-code

**Comment by sirreal** [comment]
> Well, for to fix that, the block would have to be SSR. But since it's not rendered, but assembled in html, I don't think we can do much.

Could you explain what you mean here? The block is rendered on page load, we should be able to replace or remove it:

https://github.com/Automattic/jetpack/blob/86757d7335c85069aeedb8972b36c2b5235da972/extensions/blocks/mailchimp/mailchimp.php#L19-L88

**Comment by artpi** [comment]
> Could you explain what you mean here?

I was clearly wrong! I misunderstood how that works :)
