### ISSUE TITLE
Shortcode Embeds and/or VideoPress Breaks Sorbet Theme under iOS 8

### ISSUE THREAD

**Issue by macmanx2** [Automattic/jetpack#1129]
The Sorbet theme has buttons in the header area which reveal new parts of the site, as seen via http://macmanx.com/ and http://delta.jhuff.me/

Under iOS 7, these worked with a double-tap, but under iOS 8 these have stopped working entirely, only with either the Shortcode Embeds module or VideoPress module (or both) enabled. If both modules are disabled, the header buttons work perfectly under iOS 8.

They work fine under Safari 7.1 on desktop, though I should mention that the Like button is now horribly misaligned under Safari 7.1 (it was fine under Safari 7.0.5), which you can see at http://macmanx.com/ (I can't get Likes to even display at Delta for other reasons).

Please feel free to poke around http://delta.jhuff.me/ as it is a better test environment. Jetpack is the only enabled plugin there with JSON API, Monitor, Notifications, Shortcode Embeds, and WordPress.com Stats as the only enabled modules.

The issue can be reproduced on any iPhone or iPad running iOS 8 at http://delta.jhuff.me/

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
