### ISSUE TITLE
Cookie widget container blocks underlying elements after being dismissed

### ISSUE THREAD

**Issue by iandunn** [Automattic/jetpack#11311]
#### Steps to reproduce the issue

1. Open https://2019.laspalmasgc.wordcamp.org/programa-schedule/
2. Dismiss the cookie banner
1. Find the `.show-email-form` element in your browser's element inspector (under `.entry-content`), and disable the `z-index: 50002;` rule. I added that rule to work around this bug, so you'll need to disable it in order to reproduce the bug.
3. Click on one of the ⭐️ icons in the schedule. A new fixed-position element will appear in the bottom-right hand corner of the screen, containing ⭐️ and ✉️ icons.
4. Try to click on that new element, nothing will happen.
5. Right-click on the element and inspect it, you'll see that `.widget_eu_cookie_law_widget` is sitting on top of it.

x-ref: https://wordpress.slack.com/archives/C08M59V3P/p1549564933216200

#### What I expected

When a user clicks the button to dismiss the widget, all of its DOM elements should be removed.

#### What happened instead

`#eu-cookie-law` is removed, but the `.widget_eu_cookie_law_widget` container remains, with `display: block`, `position: fixed`, etc. 

If Another element is also fixed to a similar position, then it can become inaccessible, with an invisible element sitting on top of it. The user won't know why they can't click on it, only that nothing happens when they try.

**Screenshots**

<img width="2048" alt="screen shot 2019-02-08 at 10 39 54 am 2" src="https://user-images.githubusercontent.com/484068/52498539-f27a5f80-2b8d-11e9-87b5-3240d7fe37bd.png">

**Comment by pmciano** [comment]
Reported here 1814722-zen
