### ISSUE TITLE
Comment error in Carousel images in Gallery widget

### ISSUE THREAD

**Issue by pdotk** [Automattic/jetpack#1132]
Comments can't be left on Carousel images in gallery widget if Carousel module is deactivated.

Steps to reproduce:
1. Deactivate Carousel module
2. Add Gallery widget to sidebar.
3. Add images to widget. Make sure to link to Carousel.
4. Save widget.
5. Go to site, click on gallery image in sidebar widget. 
6. Attempt to leave comment on Carousel image.
7. Get error: "Sorry, but there was an error posting your comment. Please try again later."

Can be reproduced on WordPress.com site by unchecking "Display images in full-size carousel slideshow." in Settings > Media

**Comment by lancewillett** [comment]
Similar bug report in WP.com 6955-wpcom

> If you uncheck "Enable carousel" at Settings -> Media in your blog's Dashboard, and then add a Gallery widget to your blog, all images will still open in the Carousel across the entire site. If you then remove the Gallery widget, the images no longer open in the Carousel.

**Comment by oskosk** [comment]
The Jetpack Gallery Widget was retired in favour of the new Media Gallery widget present in core since 4.9. Closing as it's not possible to link to carousel anymore.
