### ISSUE TITLE
Jetpack social sharing url for eBay shows link icon

### ISSUE THREAD

**Issue by wsolum** [Automattic/jetpack#11331]
#### Steps to reproduce the issue

I've added eBay to the Jetpack social menu and it displays a chain link icon. The issue seems similar to Pinterest #8422, except that the chain link does not go away.
The eBay link is https://www.ebay.com/usr/cherirtoys.

Could it be that the eBay icon does not exist?

I am using Dara theme w/Jetpack social. 

#### What I expected
The correct icon for eBay

#### What happened instead

It always displays the chain link icon.

**Comment by jeherve** [comment]
Thanks for the suggestion. Closing as duplicate of #11330
