### ISSUE TITLE
wpvideo shortcode: Undefined index when VideoPress inactive

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#1134]
When using a `[wpvideo xyz]` shortcode on a site when VideoPress is inactive, the following errors are thrown while putting together the OG tags:

Notice: Undefined index: id in /home/kraftbj/public_html/wp-content/plugins/jetpack/class.media-summary.php on line 63

Notice: Undefined index: id in /home/kraftbj/public_html/wp-content/plugins/jetpack/class.media-summary.php on line 64

The shortcode is still registered and renders correctly, besides the OG tag creation.

**Comment by dbtlr** [comment]
This is effectively fixed in #3853
