### ISSUE TITLE
Dashboard: Site accelerator JITM shouldn't be shown to non-admin roles

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/jetpack#11348]
#### Steps to reproduce 

- Start with a Jetpack site without "site accelerator" feature activated. Or, simply deactivate if active
- Visit the Jetpack dashboard on wp-admin, with non-admin role
- Notice that the JITM card banner is shown
- Click on `Activate` button

#### What is expected 

The card banner is not shown because non-admin roles cannot activate this setting.

#### What happens instead 

- Clicking `Activate` seems to work, and the card banner disappears. Different from what's mentioned here https://github.com/Automattic/jetpack/issues/11288
- Visiting the Jetpack settings does not show the `site accelerator` setting, because this feature can be activated only by admin role users.

![screenshot 2019-02-14 at 18 28 52](https://user-images.githubusercontent.com/18581859/52788452-f83cdd00-3086-11e9-99cf-7006999428b9.png)
![screenshot 2019-02-14 at 18 28 58](https://user-images.githubusercontent.com/18581859/52788453-f8d57380-3086-11e9-99ad-bf6107a59bb8.png)

**Comment by jeherve** [comment]
This seems like a big issue as it impacts all JITMs, not just this one. @withinboredom Could you take a look since you are more familiar with JITMs? How do we handle requests when the external user ID (let's say `2` on a site with one admin and one editor only) does not match a WordPress.com User for that blog because the editor has not connected their account to their WordPress.com account?

**Comment by jeherve** [comment]
This will be addressed in D24434-code.

**Comment by jeherve** [comment]
More recent internal reference: D24890-code

**Comment by kbrown9** [comment]
This is being fixed in D32286-code.

**Comment by sparky672** [comment]
Why did this bug just sit for 7 months after it was supposed to "be addressed"?

**Comment by jeherve** [comment]
@sparky672 We weren't able to find the best way to fix this until now, but we're on track with a good solution now. We'll close this issue once this is done.

In the meantime you can rest assured: while the notice is displayed to non-admins, they cannot actually enable features unless they have the admin role.

**Comment by jeherve** [comment]
This should now be closed.
