### ISSUE TITLE
Different orderby causes double load in Infinite Scroll 

### ISSUE THREAD

**Issue by unsalkorkmaz** [Automattic/jetpack#1135]
Hi,

When loop's **orderby** is different then "modified" or "date", `get_last_post_date` and `get_query_sort_field`  functions returns false and that causes double load first posts. 

(Edit: talking about Infinite Scroll)

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/using-new-filters-to-deal-with-infinite-scroll-post-repeating?replies=1&view=all

**Comment by pavelevap** [comment]
Same problem. Also when I tried to check for example `$args['post_type']` inside `infinite_scroll_query_args` filter, I received bad (default) results. I had to check `$_REQUEST['query_args']['post_type']` to get relevant values. And that is strange because `$args` is passed into this filter and should contain relevant information.

**Comment by pavelevap** [comment]
Sorry, I did not realize, that I have to call `add_filter()` for `infinite_scroll_query_args` with higher priority, because there is `inject_query_args()` hooked at default `10`.

**Comment by fclaussen** [comment]
Using @davidmosterd solution worked for me. But since I was only using orderby for one post_type I was having trouble with the `infinite_scroll_query_args` returning default results.

Thanks to @pavelevap I tried a higher priority and it worked.

Final Code:

```
function hm_fix_people_infinite_scroll_paging( $args ) {
    if ( 'people' === $args['post_type'] ) {
	    $args['paged']++;
    }
    return $args;
}
add_filter( 'infinite_scroll_query_args', 'hm_fix_people_infinite_scroll_paging', 100 );
```

**Comment by lamdayap** [comment]
Also reported here: #2679697-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/is-there-any-post-ordering-plugin-that-works-with-infinite-scroll

**Comment by alextsoi** [comment]
I also posted a fix in https://wordpress.org/support/topic/is-there-any-post-ordering-plugin-that-works-with-infinite-scroll
and hope someone who needs help can find the temp fix easily ( also, try bringing out more discussion on this)

I am using jetpack version 4.3.1. My fix is in the below, so far so good.
`add_filter( 'infinite_scroll_query_args', 'jetpack_infinite_scroll_query_args' );

function jetpack_infinite_scroll_query_args( $args ) {
	
    // Customize the ordering
    $args['orderby'] = 'meta_value_num';
    $args['meta_key'] = 'YOUR_META_KEY';
    $args['order'] = 'DESC';

    try{
    	// Get the start page, if the request is from 1st page, it will be 0,  and then no need to do decrement.
    	$startPage = intval($_POST['query_args']['paged']);
    	if($startPage != 0) $startPage--;

        // Adding $args is to avoid the people making infinite scrolling request in
        // non 1st page
    	$currentPage = ($args['paged'] + $startPage);

    }catch(Exception $x){
        // If error exists, I just use back the paged argument
    	$currentPage = $args['paged'];
    }

    // Using offset is used to override the paged args which will be used in WP_Query
    $args['offset'] = $args['posts_per_page'] * $currentPage;
    
    return $args;
}`

If you will use infinite scroll for custom post type with meta_key ordering, you have to change the query params in 'pre_get_posts' hook too to make the post display consistent.
