### ISSUE TITLE
Codestyling Localization Plugin: load_textdomain error

### ISSUE THREAD

**Issue by lizkarkoski** [Automattic/jetpack#11351]
This report is coming in from the Jetpack Forums at 
https://wordpress.org/support/topic/load_textdomain-error-4/

Their Localisation Plugin says that Jetpack is using `load_textdomain` instead of the `load_plugin_textdomain`

The problem is causing a change in WordPress behavior. Certain filters and actions are no longer executed.

**Comment by jeherve** [comment]
Jetpack actually uses `load_plugin_textdomain` to handle translations:
https://github.com/Automattic/jetpack/blob/472524627d75b8d6864c37153160666bc3453235/class.jetpack.php#L1041

The automated tool used to scan the plugin may have just found another instance of `load_textdomain`, that we don't actually use to translate strings on the site. It is only used for the WordPress.com REST API:
https://github.com/Automattic/jetpack/blob/518984760e16cdcf24c52e5f8770adf7ee0f8ae4/class.jetpack-xmlrpc-server.php#L734

Translations should work well in Jetpack. If they don't, or if the site owner found any conflicts with another plugin, we'd love to know more about those problems, here or on the thread!
