### ISSUE TITLE
Uncheck Sharing Button Option By Default In Meta Box When Sharing Is Enabled

### ISSUE THREAD

**Issue by catchmyfame** [Automattic/jetpack#11355]
I'd like to give my authors the ability to add the sharing widget to their pages, however I don't want the sharing buttons to always be checked by default, adding the sharing buttons on every page automatically. 

I'd like to see an option added to the sharing buttons settings that unchecks it by default, so that a page would need to opt-in to using it when sharing is enabled, rather than the way it is now, where authors have to opt-out if sharing has been enabled. Thanks!

**Comment by jeherve** [comment]
While we are not planning on adding such an option to the interface, you could change the default on your own.

The status of the sharing button is saved in the `sharing_disabled` post meta for each post. You could consequently add a code snippet to your site to automatically set the `sharing_disabled` post meta to `1` when a draft post is first saved, and then let your authors change that value using the sharing checkbox.
