### ISSUE TITLE
Multiple email addresses not supported through the Contact Form

### ISSUE THREAD

**Issue by spncrb** [Automattic/jetpack#1136]
If you use the GUI version of the contact form ("Add Contact form"), but try and add multiple email addresses (comma separated), once you add the form to the page, it converts the comma to  %26#x002c; which makes sense for the rest of the short codes (for form data inside quotes, etc), but for email addresses it breaks their functionality.

To make multiple emails work you have to do it manually inside the shortcode, which is less than ideal for the user experience.

**Comment by gaswirth** [comment]
Hi there,

I just emailed Jetpack support, but I'm currently experiencing this issue, though this bug was closed back in April.

**Comment by jeherve** [comment]
> I just emailed Jetpack support

We'll get back to you soon!

**Comment by gaswirth** [comment]
Many thanks!!!

Nick Gaswirth
-----
*Roundhouse Designs*
roundhouse-designs.com

**Comment by chaselivingston** [comment]
Seems this issue may still be reoccurring. I just tried adding multiple notification email addresses, and after the first comma, the others get converted to `%26#x002c`.

**Comment by dereksmart** [comment]
The fix in #1636 only fixed the first instance of the comma.  A global replace like `/%26#x002c;/g` should fix it.  PR incoming.

**Comment by gaswirth** [comment]
Is there a bug release coming? Why was this issue closed?

**Comment by dereksmart** [comment]
@gaswirth yep the fix for this was just merged into `master` and will be included in the next release (soon)

**Comment by gaswirth** [comment]
Awesome. Thanks, all!

Nick Gaswirth
-----
*Roundhouse Designs*
roundhouse-designs.com
