### ISSUE TITLE
Publicize: [ # more words ] on Facebook is not translated

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#11378]
To reproduce:

1- Set your blog language to Spanish under Settings > General.
2- Publish a long test post and Publicize it to Facebook.
3- Notice that it contains the string `[ # more words ]` which is not translated.

That should probably be in the blog's language?

**Comment by jeherve** [comment]
> I'm able to reproduce it as well.

@Khrol Could you give me some steps I can follow to reproduce the issue, so we can take a closer look?

**Comment by jeherve** [comment]
I was able to reproduce, following the instructions in the original post.

For reference, this was first solved in r118803-wpcom.

From what I can tell in my tests, `get_locale()` always returns `en` at that point in the submission process, regardless of the language that was set on the site and synced back with WordPress.com.

**Comment by ihab-mardoud** [comment]
It's not translated in Arabic also
I had translated it but it need to be accepted

**Comment by Josimarcsilva** [comment]
Same problem for Brazilian Portuguese. It is not translated.

Ideally an option to customize this phrase. I might be able to customize for example with the phrase: [read more in]

See the example in the image below

![Publicize](https://user-images.githubusercontent.com/4340052/64607970-fd090b80-d39f-11e9-91b4-ef81499f623a.jpg)

**Comment by jeherve** [comment]
Also in 2483059-zen

**Comment by jeherve** [comment]
This should be fixed as of r216642-wpcom
