### ISSUE TITLE
Contact Info: Make sure that international phone numbers (starting with +) are supported

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#11395]
<img width="769" alt="screenshot-2019-02-21-at-9 48 01" src="https://user-images.githubusercontent.com/115071/53242548-e85e6380-3659-11e9-93c1-1007501062db.png">

#### Steps to reproduce the issue
Add Phone number starting with 0 in the contact info block. See it break. 

also Numbers like “+358123123” render tel:358123123 which is not expected.

**Comment by jeherve** [comment]
I can't seem to reproduce the issue with the leading zeros anymore, but it would indeed be nice to fix the problem with international phone numbers. 👍
