### ISSUE TITLE
Buisness Hours Block: The closed text doesn't work as expected.

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#11399]
See:
<img width="368" alt="screen shot 2019-02-22 at 8 06 35 am" src="https://user-images.githubusercontent.com/115071/53254731-d17b3980-3678-11e9-8918-236b9e29f296.png">

It is telling me that the place is closing. Even though it isn't even open.

**Comment by jeherve** [comment]
I am not sure I understand. Isn't 12:00AM midnight, i.e. Friday 00:00, in which case the place is indeed open?
