### ISSUE TITLE
Jetpack_JSON_API_Cron_Schedule_Endpoint: WordPress 5.1 compat

### ISSUE THREAD

**Issue by mjangda** [Automattic/jetpack#11392]
https://github.com/Automattic/jetpack/blob/f8078c2cd12ac508334da2fb08e37a92cf283c14/json-endpoints/jetpack/class.jetpack-json-api-cron-endpoint.php#L201-L203

The return signature of `wp_schedule_single_event` is changing in WordPress 5.1 from `false` or `null` to `boolean` (`true` or `false`). See https://core.trac.wordpress.org/browser/tags/5.1/src/wp-includes/cron.php#L118

As such, the `is_null` check to determine whether the event was added will fail starting WordPress 5.1.

It may be better to change the check to `false !== $next`.

**Comment by nickdaugherty** [comment]
Also important to note that the event _does_ get correctly scheduled and will run, but this endpoint will return `false` due to the changed return value of `wp_schedule_single_event()`.

**Comment by jeherve** [comment]
Thanks for the report!

For reference:
https://make.wordpress.org/core/2019/01/23/cron-api-changes-in-wordpress-5-1/

We don't seem to have any other instances that would be problematic in Jetpack; the one above is the only one.

We'll want to keep supporting folks who haven't updated to 5.1, though.

> It may be better to change the check to `false !== $next`.

Could we do #11402 instead?

**Comment by mjangda** [comment]
> It may be better to change the check to `false !== $next`.
> Could we do 11402 instead?

I think both equate to the same thing:

Known return values pre-5.1: `false` and `null`
Known return values post-5.1: `false` and `true`.

`false !== $next` is just a bit simpler.

**Comment by jeherve** [comment]
Ok! Done in b43dd5a2e57348b80b497f0ccd3228fc302309e0
