### ISSUE TITLE
Sharing: Official LinkedIn icon misaligned

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/jetpack#11407]
#### Steps to reproduce 

- Start with a WordPress.com site or a Jetpack site
- Visit https://wordpress.com/sharing/buttons
- Choose `Official buttons` type
- Add a few icons and LinkedIn icon

#### What is expected 

The LinkedIn icon is aligned with the other icons

#### What happens instead 

The LinkedIn icon is not aligned with the other icons.

#### Notes

Similar issue with Pinterest icon - https://github.com/Automattic/jetpack/issues/8883

I also tested with a various themes like Twenty Nineteen and WordPress.com's Business, WordPress.com's Affinity and WordPress.com's new Business themes. On Affinity and Business, I am also see this behaviour clearly.

<img width="653" alt="screenshot 2019-02-23 at 23 47 21" src="https://user-images.githubusercontent.com/18581859/53290177-7ce5d480-37c6-11e9-94ee-7b50a3114729.png">
<img width="448" alt="screenshot 2019-02-23 at 23 52 26" src="https://user-images.githubusercontent.com/18581859/53290178-7fe0c500-37c6-11e9-8344-b256021d18f9.png">

But, on Twenty Nineteen, and the new Business themes from WordPress.com, I am seeing a much different behaviour as shown below - the Like and Reblog buttons overlap with sharing icons. Any thoughts on whether this should require a separate issue? 

@Automattic/testing, if you can try reproducing, it would be helpful!

<img width="424" alt="screenshot 2019-02-23 at 23 51 27" src="https://user-images.githubusercontent.com/18581859/53290206-cc2c0500-37c6-11e9-9c1a-bfe030ae6938.png">
<img width="399" alt="screenshot 2019-02-23 at 23 51 49" src="https://user-images.githubusercontent.com/18581859/53290207-cc2c0500-37c6-11e9-829d-c8ecfd17f521.png">

I am not entirely sure if this is a theme-level question or one for Jetpack to tackle.

I also tested with Google Chrome Version 72.0.3626.109 (Official Build) (64-bit) and Firefox Quantum 65.0.1 (64-bit). 

No browser extensions in use.

**Comment by torres126** [comment]
Automattic/wp-calypso#31321

**Comment by arunsathiya** [comment]
11039714-hc (1863088-zen) // cc @nagpai's report.

**Comment by torres126** [comment]
PR in #12037
