### ISSUE TITLE
Attachments do not have thumbnails in Related Posts

### ISSUE THREAD

**Issue by aldavigdis** [Automattic/jetpack#11413]
#### Steps to reproduce the issue

Manage to get a post of the type Attachment (item from the media library) as a related post to another in the Related Posts widget or block. This requires some (bad) luck and patience.

Alternatively, attachments should not be included, as per https://github.com/Automattic/jetpack/issues/11412.

#### What I expected
The attachment should have a thumbnail in the Related Posts widget.

#### What happened instead
The item does not have a thumbnail.

<img width="836" alt="screenshot 2019-02-25 at 15 34 56" src="https://user-images.githubusercontent.com/191583/53345765-8af23d00-390d-11e9-8f1c-262e4d230555.png">

**Comment by kraftbj** [comment]
This isn't a Related Posts issue per se. RPs grab info from the `Jetpack_PostImages` class which does not return any hits for an attachment post. It makes sense that if checking an attachment that's an image, the image itself is returned! PR submitted.

**Comment by kraftbj** [comment]
This will be resolved in the April release of Jetpack and updated on WP.com Simple sites via r188460-wpcom
