### ISSUE TITLE
Show unique visitors with Jetpack widget

### ISSUE THREAD

**Issue by Igorowytsch** [Automattic/jetpack#11428]
Hi

You already have this widget which shows the amount of all visitors from the beginning.
Unfortunately it shows only visitors and not unique visitors, what means that same user can count several times.

I really would appreciate to see this widget with the option to choose between visitors **and** unique visitors.

Hope to see that update in near future. :)

**Comment by codestor4** [comment]
This can be one easy enhancement to make but the API does not return unique visits. It only returns total `views` and `visitors` - https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/stats/

I can confirm this is the case by using `var_dump` on stats fetched from `$stats = stats_get_from_restapi( array( 'fields' => 'stats' ) );` in `blog-stats.php`

Not sure how I'd go about fetching unique visitors.. :(

@jeherve @kraftbj any advice?

**Comment by jeherve** [comment]
I don't think that data is available in the WordPress.com REST API right now, so we'd have to extend the API first.
