### ISSUE TITLE
Hook `wpmu_new_blog` callbacks to `wp_insert_site` / `wp_initialize_site`

### ISSUE THREAD

**Issue by iandunn** [Automattic/jetpack#11437]
Jetpack hooks into the `wpmu_new_blog` action in two places:

https://github.com/Automattic/jetpack/blob/ca7c26b/modules/likes.php#L80

https://github.com/Automattic/jetpack/blob/b578d60/class.jetpack-network.php#L76

[WP 5.1 deprecated that hook](https://core.trac.wordpress.org/ticket/41333) in favor of `wp_insert_site` and `wp_initialize_site`.

Because of that, notices are being triggered when any plugin calls `wp_insert_site()`, even if that plugin uses the new hooks correctly. [The notice is triggered if any active plugin is using the deprecated hooks](https://github.com/WordPress/WordPress/blob/c2c021b/wp-includes/ms-site.php#L94). Because of that, local development workflows are broken by `headers already sent` crashes, and production error logs are cluttered with noise, making them less useful.

#### Steps to reproduce the issue

1. Activate latest JP on WP 5.1
2. Call `wp_insert_site()` from an mu-plugin, `wp shell`, etc

#### What I expected

No notices should be triggered.

#### What happened instead

A notice was triggered.

**Screenshots**

<img width="2048" alt="screen shot 2019-02-27 at 5 09 14 pm" src="https://user-images.githubusercontent.com/484068/53534183-a2b6f600-3ab2-11e9-8eab-7e8e5f865573.png">

**Comment by iandunn** [comment]
Just noting that this is still happening, so that Stalebot doesn't close the issue.

**Comment by kraftbj** [comment]
I'm marking this as 7.4. As soon as WP 5.2 has been released, our minimum supported WP version becomes 5.1 so we can switch to this without any version checks for 5.0 for the old hooks.

**Comment by kraftbj** [comment]
I'm not going to attempt to fix the Likes reference in the Jetpack PR since that is code that only runs on WordPress.com and the callable being passed to the filter does not exist in the JP codebase. 

I'd like to fix it on the WP.com and bring it over in Fusion.

**Comment by iandunn** [comment]
Thanks!
