### ISSUE TITLE
Blog Subscriptions: Follower Count missing from Form

### ISSUE THREAD

**Issue by supernovia** [Automattic/jetpack#11446]
#### Steps to reproduce the issue
Start with a site that has followers.

1. Add a subscription form to a page or post, using either a shortcode or a block.
2. Choose to display follower count using a toggle or shortcode setting
3. Publish, and note the follower count does not display

#### What I expected
To see a follower count when that option is enabled

#### What happened instead
No follower count is rendered

**Comment by jeherve** [comment]
@gititon Any chance you could take a look at this? I believe this is caused by #11124.
