### ISSUE TITLE
Subscriptions: filter jetpack_subscriptions_exclude_these_categories not working

### ISSUE THREAD

**Issue by kentskyo** [Automattic/jetpack#11445]
I have added the following to functions.php… however, those who have previously subscribed via email notifications are still getting notified when I post to the category. 

```
function jetpackme_exclude_posts_subscriptions( $categories ) {
    $categories = array( 'log' );
return $categories;
}
add_filter( 'jetpack_subscriptions_exclude_these_categories', 'jetpackme_exclude_posts_subscriptions' );
```

What I expected

When new posts were added to the category, those who subscribed for notifications would not see notifications of new posts in the filtered category.

What actually happend

Same notifications as before, filter apparently ignored/useless.

Perhaps the intention of the filter is to work only for new subscribers or perhaps to not allow the subscription option in these categories (but nevertheless broadcast them if subscribed to the blog as the email for subscription form doesn't offer any granularity as far as user options)

**Comment by jeherve** [comment]
> Perhaps the intention of the filter is to work only for new subscribers

The filter excludes all posts that would belong to that category from being emailed to any of your subscribers.

As a first step, I would recommend that you double check that your category slug is indeed `log`. Then, try to remove that code from where you had added it, and add it again following this method instead:
https://jetpack.com/support/adding-code-snippets/

If that does not help, could you contact us via [this contact form](https://jetpack.com/contact-support/?rel=support) and give us more details about your site, as well as an example of a post belonging to the `log` category that was sent to subscribers after you added that code, so we can investigate further?

Thank you.
