### ISSUE TITLE
WordAds shortcode - add option for Rectangle or Square box display

### ISSUE THREAD

**Issue by formosattic** [Automattic/jetpack#11463]
Add a parameter option to the shortcode `[wordads]` to control whether ads will get displayed in a rectangle or square box.

User report: 10904375-hc

**Comment by jeherve** [comment]
Closing as this option will become available in the Ad block, scheduled to become available with the next Jetpack release tomorrow.

**Comment by aheckler** [comment]
@jeherve What about people who did something like this:

`<?php echo do_shortcode('[wordads]'); ?> `

... in a custom template?

**Comment by jeherve** [comment]
Those folks won't have the option to specify a custom size within the shortcode parameters for now. Since we are focussing our efforts on the new block editor nowadays, it's unlikely that we'll add that option to the shortcode any time soon. I would recommend using blocks when possible, instead.
