### ISSUE TITLE
Blocks migration: figure out Prettier in Jetpack

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#11474]
Jetpack Gutenberg blocks migration to Jetpack and our build there doesn't depend on Prettier per-se, but would be good to ensure Prettier continues to work for blocks and share same Prettier config between projects as a package.

[Packaging docs](https://github.com/Automattic/wp-calypso/blob/ce2493f7fcb3662d16dda09d8885620f0051728b/docs/monorepo.md#readme)

https://prettier.io/docs/en/configuration.html

`.prettierrc` configs:
- [in Jetpack](https://github.com/Automattic/jetpack/blob/ada24ea2b6e173f77ecb4f9c32393d72554013cc/.prettierrc)
- [in Calypso](https://github.com/Automattic/wp-calypso/blob/ad3e86832a0cec80b1c341f82e2a14e8fef62720/.prettierrc)

Related previous work in Jetpack https://github.com/Automattic/jetpack/pull/11007

See also https://github.com/Automattic/wp-calypso/issues/31204

cc @brbrr  @jsnajdr

**Comment by sirreal** [comment]
Figured it out 😝 😅 : #11507
