### ISSUE TITLE
Blocks: Video vs VideoPress blocks

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#11480]
Within WordPress Core, since it supports VideoPress oembeds out of the box, it generates a VideoPress block.

Our own work to better support Jetpack Videos/VideoPress is by amending the Core video block.

This may be confusing to customers, so should/could we suppress the VideoPress block in some way?

#### Steps to reproduce the issue

1. Go to Block Editor with a Jetpack site with video hosting enabled.
2. Click the UI to add a new block.
3. See both a Video and VideoPress block.

#### What I expected
No confusion on what block to use.

#### What happened instead
It can be confusing.

When pasting a VideoPress link, auto-converting to a VideoPress block is fine, but could we just remove it as an option in the new block UI?

cc: @mmtr

**Comment by mmtr** [comment]
Thanks for opening this issue @kraftbj! I agree this can confuse users.

I also agree that preventing to add VideoPress blocks from the block inserter looks like a good way to avoid the confusion.

**Comment by simison** [comment]
@rickybanister brought this up in Slack convo.

p1556116967006400-slack-jetpack-gutenberg

Note that APIs for "soft disabling" blocks are now much better in Gutenberg with the release of "Block manager":

https://github.com/WordPress/gutenberg/issues/14139#issuecomment-480261866

https://wordpress.org/gutenberg/handbook/designers-developers/developers/data/data-core-edit-post/#hideblocktypes

Also https://github.com/WordPress/gutenberg/issues/12931

**Comment by simison** [comment]
I'll remove "bug" label since this is more confusing UI than it is a "bug". :-)
