### ISSUE TITLE
Translations Not Fully Loading for Blocks

### ISSUE THREAD

**Issue by macmanx2** [Automattic/jetpack#11491]
Under Jetpack 7.1 and WordPress 5.1, translations do not appear to be fully loading for blocks.

To reproduce the issue, simply switch to any supported language at Settings > General in your site's Dashboard. The following screenshots are Spanish and German, and display the block list and Business Hours block, though this issue affects all of our blocks:

![screen shot on 2019-03-05 at 14-15-20](https://user-images.githubusercontent.com/4856235/53841634-201ab480-3f52-11e9-8091-96f433f780de.png)
![screen shot on 2019-03-05 at 14-15-45](https://user-images.githubusercontent.com/4856235/53841665-3759a200-3f52-11e9-9026-1a973740924b.png)
![screen shot on 2019-03-05 at 14-18-48](https://user-images.githubusercontent.com/4856235/53841670-39bbfc00-3f52-11e9-8296-09c6f3cc4b96.png)
![screen shot on 2019-03-05 at 14-19-03](https://user-images.githubusercontent.com/4856235/53841676-3c1e5600-3f52-11e9-95cc-d58de4fd74a2.png)

Originally reported at https://wordpress.org/support/topic/jetpack-blocks-are-not-translated-in-version-7-1/

**Comment by jeherve** [comment]
We're going to have to postpone this to the next major release, as the problem seems more complex; the strings are currently available in the editor, but we need to review how we use `wp.i18n.setLocaleData` and the format of the JSON file that is used there to make sure it is still compatible with the recommendations here:
https://make.wordpress.org/core/2018/11/09/new-javascript-i18n-support-in-wordpress/

**Comment by kraftbj** [comment]
Internal discussion about a larger project to make internationalization possibly less fragile: pafL3P-my-p2

**Comment by kraftbj** [comment]
This was partly fixed, but punting the issue to 7.3 for the remaining bits which make the most sense to me to tackle once the Jetpack blocks live natively in this repo.

**Comment by kraftbj** [comment]
Noting that we're getting close. With recent work, translate.wordpress.org is picking up strings from our blocks to translate. Still need to test if translations provided for those strings are included when the files are enqueued.

**Comment by simison** [comment]
@liviopv  on wpcom the translations aren't loaded for blocks is indeed an issue as well but solution is separate from Jetpack plugin's solution. These will need to be fixed separately.

cc @yoavf what would be good place to follow progress for wpcom side?

**Comment by simison** [comment]
>

Also, do think this also explains the fact that default field labels of the Form Block are not translated? Or would that be a different issue?

Default labels on forms shouldn't be a separate issue from the rest of the block translations.
