### ISSUE TITLE
Illegal string offset 'custom_css_post_id' 

### ISSUE THREAD

**Issue by dimonpvt1236** [Automattic/jetpack#11494]
I have many php warning in log file on my site:

PHP message: PHP Warning:  Illegal string offset 'custom_css_post_id' in /var/www/redorbit/wp-includes/theme.php on line 903" while reading response header from upstream, client: , server: www.redorbit.com, request: "GET /news/business/1752187/wisconsins_failed_gm_bid_was_409m/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "www.redorbit.com"

#### Steps to reproduce the issue
1. Install plugin with default settings
2. Go to any post page

Wordpress version 4.9.5

**Comment by jeherve** [comment]
That warning seems to come from WordPress' CSS Editor feature, that you can find under Appearance > Customize > CSS. Do you use this feature on your site. If not, could you try to head to that screen and save settings there?

If that does not help, could you try to deactivate Jetpack's Custom CSS feature, which extends WordPress' CSS editor? You can do so there:
https://www.redorbit.com/wp-admin/admin.php?page=jetpack_modules

Let me know how it goes.
