### ISSUE TITLE
“Notify me of follow-up comments by email.” checkbox on pages (not only on posts)

### ISSUE THREAD

**Issue by erikpkn** [Automattic/jetpack#11496]
I wanted to show the "Notify me of follow-up comments by email." checkbox on my front page and other pages (not only on posts). I found out that there’s no supported way of doing that.

I traced that behaviour to the funtion `comment_subscribe_init` in `wp-content/plugins/jetpack/modules/subscriptions.php`. This function is restricting the e-mail follow-up on comments to posts only (so pages are prohibited from using this mechanism): `'post' == get_post_type()`:

`if ( FALSE === has_filter( 'comment_form', 'show_subscription_checkbox' ) && 1 == get_option( 'stc_enabled', 1 ) && empty( $post->post_password ) && 'post' == get_post_type() ) {`

I changed that line to:

`if ( FALSE === has_filter( 'comment_form', 'show_subscription_checkbox' ) && 1 == get_option( 'stc_enabled', 1 ) && empty( $post->post_password ) ) {`

I tested this change and now it is working well. People that are submitting a comment now get an e-mail when I respond to their comment, even when this comment is on a page.

The problem is that the next time there is an update for Jetpack, my changes will be overwritten. So my question is: can you implement this.

**Comment by jeherve** [comment]
That's indeed not an option as Subscriptions are only meant to work for posts right now. No other post types are officially supported.

While that fix may work for now, you may run into other issues in the future, as pages are not fully supported right now. 

This should get solved if we address this issue: #760

**Comment by rcman123** [comment]
Things would be so much better if jet pack were on pages, I can have a sense of the user experience.  [RC Mowers](http://www.remotecontrollawnmowers.com
)

**Comment by latestbdnews** [comment]
It’s important to bring attention to these matters, and your thoughtful analysis helps deepen understanding. Thanks for shedding light on this important topic!

**Comment by hassanmujtabahashmi477-ship-it** [comment]
Awesome post! Thanks for sharing such useful and valuable information.
https://arcignite.com/
