### ISSUE TITLE
Break Jetpack into core + addons

### ISSUE THREAD

**Issue by galbaras** [Automattic/jetpack#11493]
Jetpack is HUGE and complicated and most people likely don't use all of it. It's gotten to the point where it makes more sense to me to break it into a core plugin, which includes the wp.com connectivity, and several addons.

I'm sure the team can look at usage stats to find the best way to package things (NOT by the current configuration sections), and it's OK to have a little bit of redundancy, but splitting things up should make code maintenance less complicated and allow the team to split and specialize, which is always a good thing.

Automattic is already doing this with WooCommerce, and that's how other collections work, e.g. Genesis, Memberships Pro, Yoast, Monsterinsights and more.

**Comment by jeherve** [comment]
Thanks for the suggestion. This is definitely something we've considered in the past, and may consider again in the future as we keep iterating and improving Jetpack.

Until then, I'll close this issue, as it is a bit too broad to be actionable and closed by a simple Pull Request here. If we revisit this, we would break this into multiple issues to get this fixed.

Thanks again for your feedback!

**Comment by galbaras** [comment]
I'm surprised. This could be the start of a great Open Source discussion, where the community of passionate JetPack users comes together to usher it into a new era.

**Comment by jeherve** [comment]
We can definitely have a discussion about it, but making such a change is not something that can be done in a simple PR here.

There are several things to consider, plan, and change, most of them not actually related to the code living in this repository. This change impacts things going from the user experience of new and existing site owners alike, to the WordPress.org plugin directory guidelines.

When we do start working on that change, I'll be sure to comment again on this issue so you can follow our progress on this.
