### ISSUE TITLE
Block type "jetpack/related-posts" is already registered

### ISSUE THREAD

**Issue by kevinlisota** [Automattic/jetpack#11506]
Recent versions of Jetpack are filling my debug logs with thousands of the following error:

```
Block type "jetpack/related-posts" is already registered. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 5.0.0.) in /var/www/mysite.com/wp-includes/functions.php on line 4667
```
Not sure if this is relevant, but we are not using Gutenberg blocks, nor do we use any default display options for Related posts on our site. 

Related Posts is enabled and we retrieve a list of related posts using Jetpack_RelatedPosts::init_raw and then render the results ourselves.

**Comment by jeherve** [comment]
Could you share the code you use to disable the default Related Posts, and enable your own custom posts? That should help us reproduce your issue and come up with a fix.

Until we have a fix in place, could you try the following and see if it stops your logs from getting overloaded?

```php
/**
 * Do not make Related Posts blocks available.
 *
 * @see https://github.com/Automattic/jetpack/issues/11506
 *
 * @param array $whitelist List of available extensions.
 */
function jetpackcom_unset_related_posts_block( $whitelist ) {
	$index = array_search( 'related-posts', $whitelist, true );
	if ( false !== $index ) {
		unset( $whitelist[ $index ] );
	}
	return $whitelist;
}
add_filter( 'jetpack_set_available_extensions', 'jetpackcom_unset_related_posts_block' );
```

**Comment by kevinlisota** [comment]
We have the Classic Editor installed and active as well. Here are the snippets.

To remove related posts default display. Wondering if the call to `Jetpack_RelatedPosts::init` is causing this? Or perhaps the call to `init_raw`. I haven't tested those two calls.
```
	/**
	 * Remove jetpack related posts from bottom of article.
	 *
	 * @since    1.0.0
	 */
    public function jetpackme_remove_rp() {
        if ( class_exists( 'Jetpack_RelatedPosts' ) ) {
			$jprp = \Jetpack_RelatedPosts::init();
			$callback = array( $jprp, 'filter_add_target_to_dom' );
			remove_filter( 'the_content', $callback, 40 );
		}
    }
add_filter( 'wp', 'jetpackme_remove_rp', 20 );
```
Function to get our own array of related posts:
```
	public static function get_related_posts( $post_id ) {
		$related_posts = [];
		if (get_post_status($post_id) == 'publish') {
			if ( class_exists( 'Jetpack_RelatedPosts' ) && method_exists( 'Jetpack_RelatedPosts', 'init_raw' ) ) {
				$related_posts = \Jetpack_RelatedPosts::init_raw()
				->set_query_name( 'jetpack-related')
				->get_for_post_id(
					$post_id,
					array( 'size' => 4 )
				);
			}
		}
		return $related_posts;
	}
```

**Comment by jeherve** [comment]
Thank you!

> Wondering if the call to Jetpack_RelatedPosts::init is causing this?

Yes, this may be what's causing it. Unfortunately, I don't think there is currently a much cleaner way to remove the related posts from the bottom of the post content.

I wonder if this may be fixed by moving the block registration outside of the `Jetpack_RelatedPosts`, like we've done for other modules in the past (see #11325 for example).

@aldavigdis Do you think you could take a look at this?

**Comment by simison** [comment]
Similar related issue with simple payments block: https://github.com/Automattic/jetpack/issues/11590

**Comment by kraftbj** [comment]
+1 to moving the register block function outside something that can be called multiple times.
