### ISSUE TITLE
Plugin Search Hints: cannot install VaultPress or Akismet anymore

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#11504]
The new Plugin Search Hints feature removes the VaultPress plugin from the search results in Plugins > Add New. 
While that is fine for folks who may not have a plan yet and who should go through WordPress.com to get a plan and get their site auto-configured, it poses a problem in some scenarios:

- In some cases folks may have to deactivate, delete, and then reinstall VaultPress as part of debugging. They already have a plan, can't go through the setup on WordPress.com anymore.
- In some cases folks may have a legacy VaultPress-only plan.
- In some cases (e.g. Multisite), the auto-configuration after purchasing a plan will not set up VaultPress for them; they'll consequently need to install the plugin manually and Jetpack won't let them do that.

For now the only work around for them would be to make a more specific search, like "vaultpress plugin", that won't trigger Jetpack's "Plugin Search Hints".

The same problems apply for the Akismet plugin.

**Comment by eliorivero** [comment]
I'll let Jesse decide whether he wants to have VP and Akismet cards back again. We removed them because the method of taking the user to the landing page where they can acquire a plan was more effective for our purposes than simply installing the plugin (in Akismet case, user can start using it without a plan).
A workaround that could be suggested instead of trying different searches, is to install the plugins from Calypso, at `https://wordpress.com/plugins/THESITE.TLD`

**Comment by jeherve** [comment]
> A workaround that could be suggested instead of trying different searches, is to install the plugins from Calypso, at https://wordpress.com/plugins/THESITE.TLD

I am afraid that wouldn't work for things like Multisite, where you may not be able to install plugins from the Calypso interface.

**Comment by jessefriedman** [comment]
This is a neat problem. Thank you @jeherve for spotting it.  @eliorivero I think I'm going to look at what it'd look like if we return or plugins to the search results.  It may be less confusing to keep them in after all.

**Comment by bikedorkjon** [comment]
Discussion in p1553021693110300-slack-jetpack-plugin regarding users not being able to see VaultPress and Akismet when needing to install/reinstall. Agreed that that "vaultpress plugin" search was sufficient.

**Comment by jessefriedman** [comment]
I definitely agree that going forward we should stop hiding cards for our own plugins, in this case VaultPress and Akismet. Originally we didn't want to confuse users with two choices but now realize we are causing more confusion for users who need those cards.

**Comment by eliorivero** [comment]
Ok I'll make the change: cards for Akismet and VaultPress will no longer be hidden.

**Comment by kraftbj** [comment]
@eliorivero you're busy with Shortcopy. I can knock this out quick.
