### ISSUE TITLE
Blank dashboard from handling of views_today

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/jetpack#11513]
#### Steps to reproduce the issue

1. Go to /wp-admin/admin.php?page=jetpack#/dashboard, specifically on a site with a new Jetpack connection
2. In some cases when views_today returns bad data the Dashboard will be inaccessible
3. Console shows the following error:

![views_today console error](https://user-images.githubusercontent.com/1900444/53911955-d6030300-4025-11e9-944a-3ec6d0d1f620.jpg)

#### What I expected
The Jetpack Dashboard to load normally

#### What happened instead
It loads for a second, then disappears. Once good data loads (usually within a few minutes) the Dashboard loads normally.

From @kraftbj:

> the one thing that was recently added and related to stats
> 
> before: if the wp.com API didn't return good data for stats, it wouldn't cache the response and keep trying on every page load
> 
> now: it'll cache a blank response for 5 minutes (what a successful call does)
> 
> i bet this probably happened since always
> but the 5-minute caching is making it persist after a refresh, so folks are thinking something's actually wrong instead of folks' usual "oh well, a refresh worked"

**Comment by kraftbj** [comment]
I'm not sure if bad data is what's happening; in a quick test, I couldn't immediately duplicate it. In any event, should handle if `generalStats` is not available.

**Comment by GaryJones** [comment]
Based on a [similar issue](https://github.com/Automattic/jetpack/issues/6646#issuecomment-287906542) from a while ago, here is the response for `wp-json/jetpack/v4/module/stats/data?range=day&_cacheBuster=1551955068944`

```
{"general":{"cached_at":1551954929},"day":[]}
```

**Comment by GaryJones** [comment]
[This line](https://github.com/Automattic/jetpack/blob/c85b94d13b3926cb217d8282aab9c1e8a714164e/_inc/client/at-a-glance/stats/dash-stats-bottom.jsx#L18) checks if `this.props.statsData.general` is an object, and then _assumes_ that `.stats` is one of the keys inside of it.

Changing that line from:

```js
if ( 'object' === typeof this.props.statsData.general ) {
```

to

```js
if ( 'object' === typeof this.props.statsData.general && 'object' === typeof this.props.statsData.general.stats ) {
```

...would actually check that the thing exists before assigning it to `generalStats`.

**Comment by boboz** [comment]
Have this issu too. 

`load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils&ver=5.1:8 JQMIGRATE: Migrate is installed, version 1.4.1
admin.js?ver=7.1.1:1 TypeError: Cannot read property 'views_today' of undefined
    at t.value (admin.js?ver=7.1.1:1)
    at t.value (admin.js?ver=7.1.1:1)
    at ca (admin.js?ver=7.1.1:1)
    at sa (admin.js?ver=7.1.1:1)
    at admin.js?ver=7.1.1:1
    at Ka (admin.js?ver=7.1.1:1)
    at Ja (admin.js?ver=7.1.1:1)
    at Ti (admin.js?ver=7.1.1:1)
    at ki (admin.js?ver=7.1.1:1)
    at yi (admin.js?ver=7.1.1:1)
ha @ admin.js?ver=7.1.1:1
`

**Comment by kraftbj** [comment]
The typical previous response when the API failed: `{"general":{"errors":{"http_request_failed":["cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received"]},"error_data":[]},"day":[]}`
