### ISSUE TITLE
Widget Visibility: Add Parent Page Option to Logic

### ISSUE THREAD

**Issue by mrwweb** [Automattic/jetpack#1153]
For hierarchical sites, it would be really handy to be able to select a Parent page and then the widget appears on all descendants (e.g. not just children but grandchildren). I think this is how many people would expect a "Parent" setting to work, despite the fact that "Grandchildren" pages would have a page other than the specified one chosen in their "Parent" field. Maybe the option would be "Descendant of" than "Parent Page."

**Comment by fgilio** [comment]
+1
This is similar to [#506 Widget Visibility in all Parent Category childs](https://github.com/Automattic/jetpack/issues/506).
I yet don't have the coding skills to develop this, but would be glad to help testing it.

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/widget-visibility-for-pages-children?replies=1&view=all

**Comment by odie2** [comment]
Seems like working - https://github.com/odie2/jetpack/tree/widgetvisibility-children (two commits).
Only needs improvement of show/hide checkbox if new selected item from checkbox by user has (no) children.

It also need tests - it could working on my even only due rest of development or something.
I tested it on parent page, children page and another page with 4 items, 2 to show when parent/his children and 2 to hide when the same.

**Comment by odie2** [comment]
Any progress?
I am stay on version 3.5.3 with code modified from by fork, as I have no time to update to latest version and did this change for 4 installs that I use this feature as must-have.

**Comment by kraftbj** [comment]
@odie2 -- opened a PR from your branch to help make it easier to discuss those changes and if they're something we'd like to bring upstream into Jetpack.
