### ISSUE TITLE
[Shortcopy] Settings: prioritize Security and Performance sections

### ISSUE THREAD

**Issue by folletto** [Automattic/jetpack#11536]
Refocusing Jetpack around Security and Performance.

Move to left at SITE_URL/wp-admin/admin.php?page=jetpack#/settings
Design TBD

**Comment by keoshi** [comment]
PRs ready:

- Calypso: https://github.com/Automattic/wp-calypso/pull/31355
- Jetpack: https://github.com/Automattic/jetpack/pull/11538

**Comment by jeherve** [comment]
Closing as this has now been merged.

**Comment by keoshi** [comment]
Thanks for catching @jeherve — there's too damn much issues and PRs to update! :P
