### ISSUE TITLE
[Shortcopy] WP Admin Connection Banner: Reframe content

### ISSUE THREAD

**Issue by folletto** [Automattic/jetpack#11532]
Refocusing Jetpack around Security and Performance.

Design TBD

**Comment by jeffgolenski** [comment]
@joanrho @keoshi 

Here's my concept for our connection banner cupcake. Our color updates should be launched fairly soon, so I thought it would be nice to mod the content as well as color. A super quick cupcake. Wouldn't take more than an hour to make both the content and style changes.

Final content: tbd
Final illo color: tbd

![connection-banner-7-2-cupcake](https://user-images.githubusercontent.com/214813/54163987-4dbf9c00-4431-11e9-9dcc-788ff2acedd7.jpg)

Thoughts on this direction? 

See the figma project for the live design.

**Comment by keoshi** [comment]
I really dig the overall look! I'm a big fan of how the green shines against this dark blue, and this feels like a nice bridge between Jetpack in wp-admin and the new onboarding. This will ensure a much smoother transition when connecting JP!

In terms of content, this does seem like a wall of text that I would probably avoid reading. :( I like that we're being descriptive, but even in this large resolution this banners takes over more than half the Dashboard real-estate. We can probably be more straight to the point with the copy, and refine the white space around the text, illo, and the `Set up Jetpack` button to make them even more effective.

Can we test how the text could overflow to two different columns in large resolutions? Maybe we can even reduce the content to the point where we don't even need that. What if the illo comes out of the right edge of the banner?

Great work, Jeff! I like this new direction a whole lot.

**Comment by keoshi** [comment]
Adding a couple of rough ideas for how much content I had in mind and how the elements could play off each other:

![image](https://user-images.githubusercontent.com/390760/54165565-27155b80-4459-11e9-83e2-f0a1428f872e.png)

I've added these to the Figma project as well.

**Comment by jeffgolenski** [comment]
@keoshi I'm a huge fan of your first iteration with the logo and illo on the left side. Minimal text. I think it looks really nice.

**Comment by jeffgolenski** [comment]
@keoshi Content is still TBD, but I worked on the illustration color and stole your format. I think, we're getting closer. How do you feel about something like this?

![7 2 cupcake banner (Filipe)](https://user-images.githubusercontent.com/214813/54239949-10234780-44f3-11e9-8953-7b90b3fa82de.png)

The illustration is in dropbox as well. Illustrations > jetpack specific

**Comment by keoshi** [comment]
Heck yeah, I love it! I really like how you worked the colors into the illustration, and I must say I'm surprised how well the bright tones work in the dark background.

My only two nitpicks would be:

- The large white space at the bottom. But I'd rather have the logo + title align at the top anyway, so if we can't have both I'm on board.
- Can we play a bit more with the proportions of the logo and illo? The logo could have more preponderance, and I think the content would benefit from having a smaller illustration (demanding less attention).

Again, minor minor details. I think this is ready to be built and then we can refine little things later on.

Awesome work, Jeff — thanks for running with this!

**Comment by jeffgolenski** [comment]
@keoshi I made a few more adjustments - the illo is now smaller to place more emphasis on the logo, I adjusted the alignment of some elements, and I just tossed some more real sample text instead of the lipsum. I'm all in favor with polishing this off in development if you are. 

![7 2 cupcake banner (Filipe)](https://user-images.githubusercontent.com/214813/54280134-1b1abe00-456d-11e9-9c3b-0a5748f7d28f.png)

**Comment by keoshi** [comment]
Love it — let's ship it!! 🙌

**Comment by jeffgolenski** [comment]
Based on the conversation and feedback in visual status today, I've reverted the color-scheme back to its original until we can dedicate more time into refining it properly. 

Attached is our new IA / content changes, but with our current color scheme. BUT, I've modified the color of the illustration to match the work that @drw158 did a while back. Let me know what you think:

![7 2 cupcake - light revised (jeff)](https://user-images.githubusercontent.com/214813/54321330-0ff47c00-45c7-11e9-847c-3887e0d37b49.jpg)

**Special note:** With our early January plugin release, we added a *controversial* green bar to the top of the banner in order to gain more attention in the hectic wp-admin UI. In this mockup I've changed it to match the illo color scheme from Dave's work - reserving the green for the logo and CTA. The idea here is that it will still gain attention, but with a more a11y friendly scheme.

Here's what the banner currently looks like:

<img width="1664" alt="Screen Shot 2019-03-13 at 7 39 05 PM" src="https://user-images.githubusercontent.com/214813/54321475-b80a4500-45c7-11e9-8a9f-e46683299180.png">


 I've been watching the data trends over the past several months with these banners. Our connections with this banner since that release with the green bar (both in wp-admin/index.php and wp-admin/plugins.php) have increased substantially. I won't link to the tracks data there, but I'd urge us to keep it or at the very least entertain a conversation about it. 

@keoshi @shaunandrews @joanrho

**Comment by keoshi** [comment]
I don't know that we need the `(!)` icon in the top left corner. To me that says “warning” and conveys a not so positive message.

I'm also unsure that we need the top portion at all, but if we can correlate that change to an increase in number of connections, let's keep it. Just seems odd to have what is essentially a banner inside another banner, but I get why it works. Won't the color change to the grayish blue make it too subdued and annul its effect though?

Finally, I think we should ping @jennyzhu (or look up that thread) about the TOS line having to come before the `Set up Jetpack` button, to clear that up.

Everything else looks great, let's ship it!!

**Comment by jeffgolenski** [comment]
@keoshi Go to bed, it's late. haha

> I'm also unsure that we need the top portion at all, but if we can correlate that change to an increase in number of connections, let's keep it. Just seems odd to have what is essentially a banner inside another banner, but I get why it works. Won't the color change to the grayish blue make it too subdued and annul its effect though?

I'm down to remove the (!) icon for sure. You're right. 

Everything is an experiment. Given the fact that we can't acquire data on how many people who actually see this and don't act on it vs. do act on it, dilutes our hypothesis strength pretty badly I think.

 I'm afraid with a subtle white banner with just a small green button, the effectiveness of getting people's attention will dwindle. 

Here's an example of what one of my wordpress dashboards actually looks like. Look at all the banners and green buttons of our competitors...

<img width="1660" alt="Screen Shot 2019-03-13 at 8 00 39 PM" src="https://user-images.githubusercontent.com/214813/54322248-cf96fd00-45ca-11e9-9ca9-6a0063f910c9.png">

**Comment by keoshi** [comment]
Yeah, maybe it’s better that we ship just an MVP right now (keep the top portion) and continue to evaluate how it performs, as opposed to making lots of changes and not knowing the source if something goes awry.

**Comment by jeffgolenski** [comment]
Absolutely!

**Comment by jeffgolenski** [comment]
@eliorivero Regarding the conversation above here, just leave that green strip above the connection banner for now, like this:

![7 2 cupcake - light revised (jeff)-greenheader](https://user-images.githubusercontent.com/214813/54395160-64f6c780-4685-11e9-9c5b-1cf61029743b.jpg)


We're taking 6 "slides" down to 1 in this iteration, so the navigation on the left can just be removed in the banner. 

The SVG is located here: https://www.dropbox.com/s/yc7ghy93fx9sc9w/jetpack-all-devices-2019.svg?dl=0

Here's the interim text:

> Jetpack free protects your site against brute force attacks and unauthorized logins. Our premium security servives also include unlimited backups of your entire site, spam protection, malware scanning, and automated fixes.
> 
> Activate Jetpack’s site accelerator to load pages faster, optimize your images, and serve your images and static files (like CSS and JavaScript) from our global network of WordPress.com servers. Speed up your site for mobile viewers and reduce bandwidth usage, which may lead to lower hosting costs.

@Automattic/editorial This is the same content[ I asked for review here](https://github.com/Automattic/jetpack/issues/11537#issuecomment-472997969), your thoughts are greatly appreciated!

**Comment by jeffgolenski** [comment]
@eliorivero Also, can we assign a new tracks event for this button? Right now the buttons in each respective slide are named based on jetpack v 4.4 (when we initially implemented it), slide number and their location within wp-admin. This connection banner displays on `wp-admin/index.php` and also `plugins.php` as I'm sure you're already aware of. 

So the names look like this:
<img width="479" alt="Screen Shot 2019-03-14 at 6 26 38 PM" src="https://user-images.githubusercontent.com/214813/54395653-cec3a100-4686-11e9-9f57-4cdea4802fa0.png">

Can we add a convention like this for this new banner?
`connect-banner-72-dashboard`
`connect-banner-72-plugins`

@keoshi Would love your input here as well

**Comment by eliorivero** [comment]
Ok will do 👍

**Comment by keoshi** [comment]
Sorry, @jeffgolenski — this ping got lost in the Sea of Email™.

That sounds great to me, I like having the release version so we can pinpoint the data we get back. Faaantastic!
