### ISSUE TITLE
[Shortcopy] README.txt: update description to reflect focus

### ISSUE THREAD

**Issue by folletto** [Automattic/jetpack#11539]
Refocusing Jetpack around Security and Performance.

Update: https://github.com/Automattic/jetpack/blob/master/readme.txt 
Copy TBD

**Comment by keoshi** [comment]
Will automatically update content on this page: https://wordpress.org/plugins/jetpack/

**Comment by keoshi** [comment]
Here are the proposed changes:

### Description

> Security, performance, and hassle-free design — all in one place
> 
> #### ALWAYS-ON SECURITY
> 
> Jetpack protects you against brute force attacks and unauthorized logins. Basic protection is always free, while premium plans add > unlimited backups of your whole site, spam protection, malware scanning, and automated fixes.
> 
> - Brute force attack protection, spam filtering, and downtime monitoring
> - Daily or real-time backups of your entire site
> - Secure logins with optional two-factor authentication
> - Malware scanning, code scanning, and automated threat resolution
> - Activity: a record of every change and update on your site
> - Fast, priority support from WordPress experts
> 
> #### BUILT-IN PERFORMANCE
> 
> Activate site accelerator tools and watch your page load times and hosting costs drop -- we'll optimize your images and serve them > from our own powerful global network of servers, and speed up your mobile site to reduce bandwidth usage.
> 
> - Load pages faster, optimize your images, and serve your images and static files (like CSS and JavaScript) from our global > network of servers. You’ll also reduce bandwidth usage, which may lead to lower hosting costs.
> - Elasticsearch-powered related content and site search
> - Lazy image loading for a faster mobile experience
> - Unlimited and high-speed video content delivery network
> 
> #### CODE-FREE DESIGN CUSTOMIZATION
> 
> Create and customize your WordPress site from start to finish, and optimize your business as you watch your site grow.
> 
> - Site stats and analytics
> - Hundreds of professional themes for any kind of site
> - Intuitive and powerful customization tools
> - Simple PayPal payment buttons
> - SEO tools for Google, Bing, Twitter, Facebook, and WordPress.com
> - Advertising program that includes the best of AdSense, Facebook Ads, AOL, Amazon, Google AdX, and Yahoo
> - Integration with the official WordPress mobile apps

### Screenshots

> 1. Security: Protection against brute force attacks, spam, and malware. On-demand backups and restores.
> 2. Downtime Monitoring: Get notified if and when your site goes down.
> 3. Performance: Free high-speed content delivery network for your images.
> 4. Analytics: Simple and concise site stats and traffic insights.
> 5. Themes: Choose from hundreds of customizable, professional themes.
> 6. Apps: Update your site from any device with the free WordPress apps.
> 7. Revenue: Sell products & take payments with simple payment buttons.
> 8. Sharing: Connect your site to social networks for automated social sharing.

### Before

![image](https://user-images.githubusercontent.com/390760/54548537-10628d80-49a0-11e9-9e68-a46ef5bc65c7.png)


### After

![image](https://user-images.githubusercontent.com/390760/54548439-d4c7c380-499f-11e9-8459-730791b5b870.png)


cc @jeffgolenski @michelleweber would appreciate your reviews here. Thanks in advance!

**Comment by jeffgolenski** [comment]
The organization works for me!

**Comment by michelleweber** [comment]
Will review this tonight!

**Comment by michelleweber** [comment]
There's considerable redundancy in the intro text and the bulleted lists -- I'd love if it we could tighten up the intro text, let the bullets carry the finer detail, and eliminate the bits that are word-for-word repetitive. We could also use smoother transitions from the intro text into the lists; it's a little abrupt right now. Here's my suggested version.

-----------

Security, performance, and hassle-free design: the best way to WordPress is with Jetpack.

24/7 SITE SECURITY
Jetpack is your site's security detail, guarding you against brute-force attacks and unauthorized logins. Basic protection is always free, while premium plans add expanded backup and automated fixes. Jetpack's full suite of site security tools include:

- Brute-force attack protection, spam filtering, and downtime monitoring.
- Backups of your entire site, either once daily or in real time.
- Secure login, with optional two-factor authentication.
- Malware scanning, code scanning, and automated threat resolution.
- A record of every change on your site to simplify troubleshooting.
- Fast, priority support from WordPress experts.

PEAK PERFORMANCE
Activate site accelerator tools and watch your page load times and hosting costs drop -- we'll optimize your images and serve them from our own powerful global network, and speed up your mobile site to reduce bandwidth usage (and save money!). Connect Jetpack to take advantage of:

- Images and static files, like CSS and JavaScript, served from our servers, not yours.
- Elasticsearch-powered related content and site search, for relevant results with no drain on your servers.
- Lazy image loading for a faster mobile experience.
- Unlimited and high-speed video via our content delivery network.

CODE-FREE CUSTOMIZATION
Create and customize your WordPress site, optimize it for visitors and revenue, and enjoy watching your stats tick up. Built it, share it, and watch it grow with:

- Advanced site stats and analytics for understanding your audience.
- Hundreds of professional themes, for a pro site no matter what your niche. 
- Intuitive and powerful customization tools to match your website to your brand.
- Simple PayPal payment buttons for selling products and services.
- SEO tools for Google, Bing, Twitter, Facebook, and WordPress.com to maximize your reach.
- An advertising program that includes the best of AdSense, Facebook Ads, AOL, Amazon, Google AdX, and Yahoo.
- Integration with the official WordPress mobile apps, to manage your site from anywhere.

Screenshots
Security: Protection against brute force attacks, spam, and malware. On-demand backups and restores.
Downtime Monitoring: Know right away if and when your site goes down.
Performance: Free high-speed content delivery network for your images.
Analytics: Concise site stats and traffic insights.
Themes: Hundreds of customizable, professional themes.
Apps: Update your site from any device with the free WordPress apps.
Revenue: Sell products and take payments with simple payment buttons.
Sharing: Connect your site to social networks for automated social sharing.

**Comment by keoshi** [comment]
That's so much better, @michelleweber — thank you!! 🙌

**Comment by lezama** [comment]
should we still say "hassle-free design"? I would change it to something more concrete 😅

**Comment by keoshi** [comment]
What do you suggest, @lezama ?

**Comment by keoshi** [comment]
> Security, performance, and professional themes: the best way to WordPress is with Jetpack.

Like so? To me that goes from overarching benefits to a single feature too quickly. What about this one, even though I'm not a fan of “tools” here:

> Security, performance, and design tools: the best way to WordPress is with Jetpack.

**Comment by joanrho** [comment]
IMO "design tools" and "code-free customization" doesn't accurately reflect our list of features. 

People don't come to jetpack seeking design or themes, rather they come seeking tools that cover their site's security, performance, and _site management_ (like stats and related content, automated social media posting, SEO tools, etc.).

**Comment by keoshi** [comment]
Good point, @joanrho ! Do you think we can change the tagline to:

> Security, performance, and site management: the best way to WordPress is with Jetpack.

And the title on the third block to:

> Effortless Site Management

Without changing the rest of the content and losing the overall context?

cc @michelleweber

**Comment by keoshi** [comment]
Created a follow-up PR to adjust the copy here: https://github.com/Automattic/jetpack/pull/11652
