### ISSUE TITLE
AMP Issues with JetPack

### ISSUE THREAD

**Issue by edjarrett** [Automattic/jetpack#11530]
I am running WordPress 5.1, JetPack 7.1.1 and AMP for WP 1.0.2 in paired mode with sanitation turned on. Every page I edit now returns a number of errors that are sanitized so not really impacting AMP validation. But they are troubling nonetheless. Five of these errors are identified as coming from JetPack. I have attached a text file with the error messages from AMP.

[JetPack AMP errors.txt](https://github.com/Automattic/jetpack/files/2947873/JetPack.AMP.errors.txt)

**Comment by kraftbj** [comment]
I'm closing this to defer to the exhaustive list of AMP issues that @westonruter put together (major props to him).
