### ISSUE TITLE
Publicize: Sharing to Twitter with Chinese characters fails

### ISSUE THREAD

**Issue by thebud15** [Automattic/jetpack#11547]
#### Steps to reproduce the issue

These steps will need to be done with a site that is connected to Twitter through Publicize.

1. Go to My Site > Blog Posts > Add
2. Create dummy content in a new post
3. Click Publish and enter Chinese characters in the "Share this post" field for Twitter.
4. Publish the post and check the connected Twitter account to see results. 

#### What I expected
I expected to see the post shared with the Chinese characters as the message accompanying the Tweet.

#### What happened instead
Instead, the post shares with the link, but without the text entered from step 3 above. In testing this with English characters in that field, the message shares properly. 

**Screenshots**
![Screen Shot on 2019-03-11 at 19_34_27](https://user-images.githubusercontent.com/29046778/54170677-da1f8e00-4434-11e9-9dba-34f9d42b96ec.png)

You'll see the publicized tweet with English characters that worked, as I tested this once. The others shared, but without a message. This happened when the characters were at or below the character limit.

**Comment by thebud15** [comment]
Original report: 9851182-hc
Follow up: 1754097-zen

**Comment by grvrulz** [comment]
I did some testing for this, and it looks like when there are more than 131 characters, the tweet doesn't get posted. Dummy text that I tried in Calypso classic sharing box(103 characters remaining, goes through nicely)

> 側経意責家方家閉討店暖育田庁載社転線宇。得君新術治温抗添代話考振投員殴大闘北裁品間識部案代部案代 側経意責家方家閉討店暖育田庁載社転線宇。得君新術治温抗添代話得君新術治温抗添代話 得君新術治温抗添代話得君新術治温抗 添代話得君新術治温抗添代話得君新術治温抗添添

One I tried in Twitter's posting box, posts nicely.

> 側経意責家方家閉討店暖育田庁載社転線宇。得君新術治温抗添代話考振投員殴大闘北裁品間識部案代部案代 側経意責家方家閉討店暖育田庁載社転線宇。得君新術治温抗添代話得君新術治温抗添代話 得君新術治温抗添代話得君新術治温抗 添代話得君新術治温抗添代話得君新術治温抗添添添添添添添添添添添添閉

Twitter considers this as a full 280 characters, while Calypso's sharing box, Gutenberg's sharing box, and a few character counting websites only count this as 142 characters. Tried on these two services:
- http://www.twitter-character-counter.com/
- https://www.lettercount.com/

Looks like this is what Twitter uses to parse text and count characters
https://github.com/twitter/twitter-text

They have some info on this here
https://developer.twitter.com/en/docs/basics/counting-characters

This is what we currently use
https://github.com/Automattic/wp-calypso/tree/master/client/components/forms/counted-textarea


P.S. I have only tested this on Calypso, and not in the WP Admin with Jetpack and a self-hosted site. I'll do additional testing for this, and add notes here.

**Comment by jeherve** [comment]
closing as duplicate of #13987.
