### ISSUE TITLE
Can't translate Related Posts heading on atomic or self hosted sites

### ISSUE THREAD

**Issue by mlaetitia** [Automattic/jetpack#11549]
#### Summary

The Related Posts heading set in the Customizer -> Related Posts cannot be translated

Tested using a combo with Polylang+LocoTranslate

#### Steps to reproduce the issue

1.  Create a new wordpress site (any of these replicate the issue) - or use an existing one
2. Connect Jetpack + Activate the Related Posts module + the heading option
3. Install the Twenty Nineteen theme, head to the customizer -> related posts, activate the heading option and enter something there
4. Install polylang and set up a secondary language
5. Translate the hello world post into the secondary language
6. Create 3 more posts with the same category+tags in both languages
7. The related posts should start appearing at the end of individual posts. Independently of the post language, that string will always appear in the same language
8. Checking in Polylang, there is only one string to be translated there from Jetpack, which is the "Share This" string, the one set in the customizer doesn't appear anywhere.

#### What I expected
Not sure :) I am not saying that Jetpack must be compatible with PolyLang - just that there should likely be a way to translate this for multilingual sites :)

Video of what happens with a mutilingual site setup: https://cld.wthms.co/nJZ7s7

**Screenshots**

**Comment by kraftbj** [comment]
Typically settings aren't translated in WordPress—it's just an option saved in the database, so Polylang or whatever multiligual plugin should handle it.

A custom plugin could probably do it based on https://polylang.pro/doc/developpers-how-to/ using https://developer.jetpack.com/hooks/jetpack_sharing_headline_html/

This isn't tested, but something like
```
<?php
$options = Jetpack_Options::get_option( 'relatedposts', array() );
