### ISSUE TITLE
My Plan: update heading illustration

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#11541]
Following up https://github.com/Automattic/jetpack/pull/11505#issuecomment-471639047

The illustration next to My Plan main header should be updated once we have a clear decision on the style direction.

**Comment by keoshi** [comment]
Thanks, @eliorivero !

**Comment by keoshi** [comment]
Hey again, @eliorivero — would this be a satisfactory iteration, given we won't have clarity on the new brand for a while?

This takes the existing plan icons as seen on WordPress.com and Jetpack.com and tweaks a few colors to match the illos in the My Plan page — this allows us at least to bring that consistency to the plugin, which has used different illustrations for the different plans for a while.

![image](https://user-images.githubusercontent.com/390760/54192932-f234f300-44b0-11e9-8176-8c5a05c17d7b.png)

Here's how it would look like in place for the Premium plan, for example:

![image](https://user-images.githubusercontent.com/390760/54193044-2d372680-44b1-11e9-9d31-a1bcd46949a8.png)

Even if you agree with this change, I propose that we don't close this issue to make sure we update all of these when the new branding is defined.

**Comment by eliorivero** [comment]
Yeah, that's much better than the current one

<img width="751" alt="Captura de pantalla 2019-03-14 a la(s) 09 32 13" src="https://user-images.githubusercontent.com/1041600/54357164-31dc1600-463c-11e9-98c1-3829f3d06bda.png">

Which is more busy. It's still a bit more pale than the Site Security and Built-in Performance but I think that's ok so the user is dragged to those, that are much more important.

**Comment by jeffgolenski** [comment]
@eliorivero Let's do this. Are you all set to move forward with this? Let me know if you need any resources.

**Comment by eliorivero** [comment]
Let's do it. Point me to the images and I'll update them.

**Comment by jeffgolenski** [comment]
[jetpack-plan-icons.zip](https://github.com/Automattic/jetpack/files/2990156/jetpack-plan-icons.zip)

@eliorivero Here's 4 crisp, optimized svgs for you. Thanks!

**Comment by keoshi** [comment]
Thanks for doing that, @jeffgolenski ! I've replaced the light gray color for the darker blue `#204A69` so that the icons match the illustrations below better.

Here's the file, @eliorivero: [jetpack-plan-icons-v2.zip](https://github.com/Automattic/jetpack/files/2991486/jetpack-plan-icons-v2.zip)

**Comment by jeffgolenski** [comment]
heck yeah. thanks @keoshi
