### ISSUE TITLE
Shortcopy: update list of modules included in Jumpstart

### ISSUE THREAD

**Issue by joanrho** [Automattic/jetpack#11556]
We are reducing the number of modules included in Jumpstart (Recommended Features) to the minimum Security and Performance essentials:

**BEFORE:**
- Carousel
- Contact Form
- Gravatar Hovercards
- Sharing
- Subscriptions
- Lazy-images
- Monitor
- Photon
- Related-posts
- SSO
- Tiled-gallery

**AFTER:**
- Static File Hosting
- Image Hosting (Photon)
- Lazy Loading Images (Lazy-images)
- XML Sitemaps
- Downtime Monitoring (Monitor)
- SSO

ref: p1HpG7-6qm-p2

**Comment by eliorivero** [comment]
For future reference, we had 11 jumpstarted features.

<img width="316" alt="Captura de pantalla 2019-03-13 a la(s) 14 12 56" src="https://user-images.githubusercontent.com/1041600/54299713-364ff280-459a-11e9-96d5-b6971377abea.png">

**Comment by joanrho** [comment]
Thanks for the clarification, @eliorivero! Will update my Issue details to reflect all those.
