### ISSUE TITLE
Sharedaddy: Add hook to allow for modification of the Ajax action name

### ISSUE THREAD

**Issue by dcooney** [Automattic/jetpack#11565]
#### Is your feature request related to a problem? Please describe.
Sharedaddy does **NOT** work in Ajax calls (admin-ajax.php) unless the action is named `get_latest_posts`.

Line 754 of `plugins/jetpack/modules/sharedaddy/sharing-service.php` has the following conditional where the action name (`get_latest_posts`) is hard coded.
```
// Allow to be used on P2 ajax requests for latest posts.
if ( defined( 'DOING_AJAX' ) && DOING_AJAX && isset( $_REQUEST['action'] ) && 'get_latest_posts' == $_REQUEST['action'] ) {
	$show = true;
}
```

#### Describe the solution you'd like
The action name should be filtered to allow for it to work in other scenarios and with other plugins by using the following `sharing_ajax_action` hook .
```
// Allow to be used on P2 ajax requests for latest posts.
if ( defined( 'DOING_AJAX' ) && DOING_AJAX && isset( $_REQUEST['action'] ) && apply_filters('sharing_ajax_action', 'get_latest_posts') == $_REQUEST['action'] ) {
	$show = true;
}
```

#### Describe alternatives you've considered
I have asked my customers/users to modify the core plugin or use a different sharing service.

#### Additional context
I am willing to submit a pull request if this is something worthwhile.

**Comment by jeherve** [comment]
> I am willing to submit a pull request if this is something worthwhile.

Yes, that's definitely something we'll be happy to review!

**Comment by dcooney** [comment]
Thanks @jeherve Submitted.

**Comment by kraftbj** [comment]
Reopening. It'll automatically close once the PR is accepted or if, for whatever reason, it isn't, the issue can stay open until it is resolved.
