### ISSUE TITLE
Sandboxing: Doublecheck that communication with jetpack.com does not need to conditionally add sslverify:false to requests

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#11574]
In #11488 we piggybacked a change to the list of domains that are sandboxed if the JETPACK__SANDBOX_DOMAIN constant is set.

I'll try to add reproduction steps properly but I think that under some condition Jetpack shows a red notice stating that the site cannot communicate via SSL with WordPress.com (probably because it tries to reach jetpack.com and fails to verify a certificate). I'm assigning this issue to myself.

**Comment by kraftbj** [comment]
That would make sense since the other domains are all *.wordpress.com subdomains. Probably can just sslverify false for that when sandboxed.

**Comment by oskosk** [comment]
Just found this and I don't have an idea of what I was talking about. Closing
