### ISSUE TITLE
Publicize: "# more words" duplicate

### ISSUE THREAD

**Issue by kristarella** [Automattic/jetpack#11575]
#### Steps to reproduce the issue

1. Publish a post on a site with a Facebook Publicize connection with enough words to exceed excerpt
2. Check post on Facebook
3. Bottom of post will say something like "537 more words [ 535 more words ]"

#### What I expected
It should only say `# more words` once, and the word count should be correct... it is showing two different counts here.

#### What happened instead
There are two sets of remaining word counts, and the count is different in each

**Screenshots**
<img width="495" alt="Screen Shot 2019-03-15 at 2 25 53 pm" src="https://user-images.githubusercontent.com/2031017/54406669-143ba900-472f-11e9-9862-58fd2a70439f.png">

- Can be viewed at this [FB post](https://www.facebook.com/permalink.php?story_fbid=266272210972745&id=266266290973337&__xts__%5B0%5D=68.ARBp4XczFZ9iuLbDInWsOUnP0qM0gp93eK-bJ00-5whuxFSjoM4MKi4npKHX9FLt_w5ogScagfDynK_9S-jXUn4GdtiAOUKcKYVNXZlyxOZhKx_x7ROvEem6svmcWUTc7IHH1aMsG96aGcZ2Qr4jAHyN97O7aJM13osH_rRPFaYpUWwPxN9cHq__a3D_vZmD0BGIm8_BiISl9pHm08cEfTh9QkCrTlw7KPxLmj0UlibsCX4ehnN_mbcVue46LAAI1n4tQqucpH91kl7uRGtlkjdH3GHFhmYPpAk-zK6V7K5ov5FK6iT_rTc-N3xAFC8X2xC0L6a5Y8zW1SoddTRfG64&__tn__=-R)
- Originally reported in 11143642-hc

**Comment by kraftbj** [comment]
As far as you're aware, have there been any reports of this on Jetpack/Atomic or only on Simple?

**Comment by kraftbj** [comment]
I'm going to move this over to 8141-wpcom since this is a bug on the WordPress.com side.

**Comment by kraftbj** [comment]
Nothing this has been fixed on the wpcom side. r189016-wpcom
