### ISSUE TITLE
Show password protected pages in Jetpack stats

### ISSUE THREAD

**Issue by leandroprz** [Automattic/jetpack#11586]
I noticed pages with a password don't show up on Jetpack stats.

Would it be possible to add a feature so I could keep track of how many people is visiting password protected pages?

**Comment by jeherve** [comment]
Could you reach out to us via [this contact form](https://jetpack.com/contact-support/?rel=support) and give us some examples so we can take a closer look at this?

Thank you!

**Comment by leandroprz** [comment]
I can't contact you using that page, it says "Support for customers on Jetpack's Free Plan is temporarily closed." and I don't see any form.

**Comment by jeherve** [comment]
In this case could you post some examples here, so I can take a closer look?

**Comment by leandroprz** [comment]
I was going to show you how this wasn't working but after a few tests I noticed it is working perfectly.

Maybe it was fixed somehow in latest updates.

Sorry about this.
Thanks!
