### ISSUE TITLE
Docker: Do not display PORT_WORDPRESS warning as often

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#11583]
See https://github.com/Automattic/jetpack/pull/11318#discussion_r266184878

The `WARNING: The PORT_WORDPRESS variable is not set. Defaulting to a blank string.` is helpful, but maybe we shouldn't display it as often as we are displaying it as it can cause hiccups in testing.

**Comment by mdawaffe** [comment]
It's annoying that Docker issue a warning here at all. We provide a [default value](https://github.com/Automattic/jetpack/blob/3f9dc9cae037825065f8ca88b64b5a50a1087467/docker/docker-compose.yml#L80) for that variable.

**Comment by mdawaffe** [comment]
Oh! But a few lines down we don't.
