### ISSUE TITLE
JITM: Excess margin above JITM

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#11597]
#### Steps to reproduce the issue

1. Checkout latest master
2. Go to Jetpack admin
3. Notice JITM has some excess margin

#### What I expected

The JITM to not have so much margin above.

#### What happened instead

Lots of margin.

**Screenshots**

<img width="1269" alt="Screen Shot 2019-03-18 at 9 56 59 PM" src="https://user-images.githubusercontent.com/1126811/54577307-36505800-49c9-11e9-90e8-f2f6c66e14de.png">

**Comment by kraftbj** [comment]
I'm moving this out of 7.2 since there isn't a PR and we're a few hours away from code freeze.
