### ISSUE TITLE
Filter Products by Attribute widget disappears when Widget Visibility is enabled in Jetpack 

### ISSUE THREAD

**Issue by treibalen** [Automattic/jetpack#11608]
Affected ticket 1885161-zen

#### Steps to reproduce the issue

1. Go to Appearance > Widgets > add Filter Products by Attribute widget:

![https://cld.wthms.co/25pZvA](https://cld.wthms.co/25pZvA+) 
Full Size: https://cld.wthms.co/25pZvA

2. Widget is shown properly on the shop page: 

![https://cld.wthms.co/3ru9Dp](https://cld.wthms.co/3ru9Dp+) 
Full Size: https://cld.wthms.co/3ru9Dp

3. Now enable Widget Visibility in Jetpack modules and set this widget to be visible on, for example, Shop page:

![https://cld.wthms.co/0w10bx](https://cld.wthms.co/0w10bx+) 
Full Size: https://cld.wthms.co/0w10bx

4. Widget disappears:

![https://cld.wthms.co/ZMvjjn](https://cld.wthms.co/ZMvjjn+) 
Full Size: https://cld.wthms.co/ZMvjjn

#### What I expected

Filter Products by Attribute should show up on the page.

#### What happened instead

It disappeared.

**Comment by jeherve** [comment]
Closing as duplicate of #8343. My comment there should help you find a workaround that will work here.

**Comment by htdat** [comment]
Thanks Jeremy, replied in 1885161-zen.
