### ISSUE TITLE
Add "beta" badge to beta blocks in block picker

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#11621]
Add "beta" badge to beta blocks in block picker as currently it's impossible to see what is beta and what is not:

<img width="417" alt="Screenshot 2019-03-20 at 11 32 17" src="https://user-images.githubusercontent.com/87168/54674936-20947d00-4b06-11e9-8430-dbb52ad2a70e.png">

<img width="409" alt="Screenshot 2019-03-20 at 11 32 03" src="https://user-images.githubusercontent.com/87168/54674910-0f4b7080-4b06-11e9-99a0-09116c3a7fea.png">

(P.S. it's _VR_ and _Repeat visitor_)

**Comment by ockham** [comment]
Fixed by #11739
