### ISSUE TITLE
Search Widget: Clarify that filters will only show after search results.

### ISSUE THREAD

**Issue by WPprodigy** [Automattic/jetpack#11648]
Here is a quick look at the Jetpack Search widget:
![](https://cld.wthms.co/4pFnyM+)

Based on how this looks, I would expect the search box and the filters to show up on every page in the sidebar where this widget is placed. That is not the case though, as filters only appear after search results have come back from ES. So they will only show up on the search page after a search has happened.

This isn't super clear in the UI, nor even in the docs: https://jetpack.com/support/search/

I imagine this is mainly due to the fact this started as a widget just for the filters (which would make sense to only work on the search page). But then later on the search form was added, which displays on all pages.

I'm suggesting two things:

1)  Make a change in the UI itself that better explains / sets the expectation for this behavior.
2) Update the docs to express how this works as well. The `"I added extra filters to the search widget, but they’re not showing on the page – how do I get them to appear?"` section could be expanded a bit / made more generic to talk about why filters aren't showing at all.

**Comment by kraftbj** [comment]
Relayed the documentation suggestion to Quill in p93VbO-8t-p2 .

**Comment by WPprodigy** [comment]
Also, somewhat related, is the odd behavior of the "sort by" field on the widget frontend when enabled. This is another thing that is designed for the search results page, but is displayed/works on all pages.

On a normal page, changing the "Sort by" value automatically redirects you to the search page, regardless if you have typed anything into the search box yet. This behavior makes sense on the search results page, but feels clunky/wrong on other pages.

So perhaps it should be grouped in with the filters to distinguish how it's meant to function on the search-results page.

**Comment by gibrown** [comment]
The instant search prototype (not yet in full release) has implemented filtering to always be shown even before a search has been performed, so closing this.
