### ISSUE TITLE
Jetpack error message: min required WP version needs visual update

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#11642]
For versions of WordPress prior to 5, we display this error message when Jetpack is activated.

<img width="842" alt="Screen Shot 2019-03-19 at 2 55 45 PM" src="https://user-images.githubusercontent.com/214813/54764478-42593700-4bce-11e9-9b25-87c89c6e73a5.png">

I think we can do a bit better here. Make it a little more noticeable and friendlier. Perhaps a link to send folks to the update page within wp-admin.

Design tbd. cc @keoshi @joanrho 

@dereksmart I saw this quickly, but i'm unable to reproduce with wp downgrade and earlier wp versions. Can you provide more info so I can get this error back up?

**Comment by keoshi** [comment]
Yeah, adding the link to the update page would be amazing. I don't think we should do much more than that here; I'd try avoiding any branding at all because we don't want people to see “Jetpack” and “fatal error” on the same sentence, and I don't think we can suppress the latter message?

**Comment by jeherve** [comment]
That specific error message is added by Core, and is a consequence of #11460. We've been thinking of handling this better, and are currently working on this in #11609. Maybe you can chime in there to help improve the message we'll display there?

Closing this one for now as duplicate.
