### ISSUE TITLE
What are the data center locations of i0.wp.com cdn?

### ISSUE THREAD

**Issue by nabtron** [Automattic/jetpack#11665]
I am unable to find any information about the locations of datacenter of i*.wp.com cdn's around the world. 

Need it to confirm if it's a good choice for my project or should I use amazon or any other, based on proximity of my visitors.

Thanks & Regards.

**Comment by jeherve** [comment]
We continuously add more and more locations so this is something that's very much in flux, but you can see a current map on this page:
https://vip.wordpress.com/infrastructure/

I hope this helps.
