### ISSUE TITLE
Error message: The string did not match the expected pattern when installing recommended features

### ISSUE THREAD

**Issue by bartholdja** [Automattic/jetpack#11664]
#### Hello, when I try to active recommended features, this error shows:
Recommended features failed to activate. SyntaxError: The string did not match the expected pattern.

I managed to follow the instructions to check the error message in the browser console from a previous, closed issue and the message reads "Failed to load resource: the server responded with a status of 500 ()"

Any chance I can get help here?

**Comment by jeherve** [comment]
Since you closed the issue, I assume you found the solution to your problem. Could you share your findings here for others who may run into similar issues in the future?

Thank you!

**Comment by bartholdja** [comment]
Hi! Unfortunately, I didn't find the solution. I read on the jetpack webpage that there is no direct support for the free version, so I figured it a bit cheeky to ask here. Hence I closed the issue because I couldn't figure out how to delete it.

**Comment by jeherve** [comment]
> I read on the jetpack webpage that there is no direct support for the free version, so I figured it a bit cheeky to ask here.

You could always post about in the support forums here, we'll be happy to help you there:
https://wordpress.org/support/plugin/jetpack/

We will need to know your site URL to find out more, though.

Before you post anywhere, I would also recommend that you enable WordPress Debugging mode as explained [here](https://gist.github.com/jeherve/e6acfc973c07cb500836804e1044d12a), and then try to reproduce the issue. If you can reproduce it, the error log will then tell you a lot more about the error that caused the problem.

I hope this helps.
