### ISSUE TITLE
Keep blocks in sync with Calypso

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#11674]
An issue to keep track of PRs to merge back to Jetpack from Calypso.

While code from [`/packages/jetpack-blocks`](https://github.com/Automattic/wp-calypso/tree/7e05668b788f3104aff8e68aadcf306cf999ccf0/packages/jetpack-blocks) is moving to [`/extensions`](https://github.com/Automattic/jetpack/tree/b8717477aecd787bf7078e73a69cf1f49ada56dc/extensions) in Jetpack repo but we still haven't removed Calypso files, we need to manually keep these in sync.

Folder histories for both:
- Jetpack: https://github.com/Automattic/jetpack/commits/master/extensions
- Calypso: https://github.com/Automattic/wp-calypso/commits/master/packages/jetpack-blocks

#### Merged in Calypso
- [x] https://github.com/Automattic/wp-calypso/pull/31720
- [x] https://github.com/Automattic/wp-calypso/pull/31608 synced in https://github.com/Automattic/jetpack/pull/11640
- [x] https://github.com/Automattic/wp-calypso/pull/31739 synced in https://github.com/Automattic/jetpack/pull/11640
- [x] https://github.com/Automattic/wp-calypso/pull/31750 (moves release visitor block to prod from beta list, synced in https://github.com/Automattic/jetpack/pull/11640)

#### Open in Calypso
- [ ] https://github.com/Automattic/wp-calypso/pull/29744 ( this has been moved to Jetpack https://github.com/Automattic/jetpack/pull/11709 )
- [ ] https://github.com/Automattic/wp-calypso/pull/30989 

cc @Automattic/gutenpack

**Comment by roccotripaldi** [comment]
Thanks for doing this!

**Comment by sirreal** [comment]
Calypso master @ e4862897aec6ccd7e3ef7120df19f20df216a07a has been synced to Jetpack build PR: https://github.com/Automattic/jetpack/pull/11640

**Comment by simison** [comment]
This can be closed since blocks are no more in Calypso. 

Now we need to keep PRs synced the other way around, from Jetpack to Calypso's Jetpack 7.2 branch: https://github.com/Automattic/wp-calypso/pull/31793
