### ISSUE TITLE
Port .com [tweet] shortcode to Jetpack

### ISSUE THREAD

**Issue by mrwweb** [Automattic/jetpack#1168]
As noted in [this blog post](http://stevebuttry.wordpress.com/2014/10/08/frustrating-flaws-and-one-solution-in-twitters-embed-codes/), the default twitter embed pulls in the tweet thread and twitter cards (at least some times). WordPress.com helps people around this with a [[tweet] shortcode](http://en.support.wordpress.com/twitter/twitter-embeds/). It seems this would be useful to self-hosted users and righ at home in the Shortcode Embeds module.

**Comment by jkudish** [comment]
It's on our team's list to go through all the shortcodes/embeds on WP.com and sync as many as possible to Jetpack.  

Jetpack pit crew: Since this hasn't happened yet, feel free to sync this one individually, there's no reason not to.

**Comment by jeherve** [comment]
Also suggested here:
https://twitter.com/Jtsternberg/status/659422372949282816

**Comment by jeherve** [comment]
#5518

**Comment by jeherve** [comment]
Fixed in #5838
