### ISSUE TITLE
Implement Picture-element and srcset support into Photon.

### ISSUE THREAD

**Issue by georgestephanis** [Automattic/jetpack#1169]
We've previously upsampled images used in Photon via [devicepx-jetpack.js](http://s0.wp.com/wp-content/js/devicepx-jetpack.js?minify=false).  However, with browser support of responsive images coming via both the `srcset` attribute and the `picture` element, let's explore supporting one or both, and dropping `devicepx-jetpack.js` instead.

Related: http://s0.wp.com/wp-content/js/devicepx-jetpack.js?minify=false (the unminified source)
Related: #820

**Comment by jeherve** [comment]
This was addressed in devicepx.
