### ISSUE TITLE
Gutenberg: Tags Added to Pages and Portfolio Projects are Converted to Numbers

### ISSUE THREAD

**Issue by juliasydnor** [Automattic/jetpack#11695]
Some WP.com themes add Tags to Pages and Portfolio Projects, usually for featured content. When a Tag is added to a Portfolio Project, it is converted to a string of numbers. I was able to reproduce on WP.com simple sites, but not AT sites.

#### Steps to reproduce
1. On a WP.com simple site, activate the Rebalance theme.
2. Go to My Site > Portfolio and add a new Portfolio Project.
3. Add a Tag to the Portfolio Project.
4. Publish or Update the Portfolio Project.

#### What I expected

I expected the Portfolio Project to have the Tag I typed in.

#### What happened instead

The Tag I typed in was converted to a string of numbers.

#### Browser / OS version

Chrome Version 72.0.3626.119 (Official Build) (64-bit)
macOS Mojave version 10.14.3

#### Screenshot / Video

![tag-numbers](https://user-images.githubusercontent.com/29981758/53970746-60507300-40c9-11e9-8340-ee36a6a9ba0d.gif)

#### Context / Source
#user-report #manual-testing

**Comment by eoinsav** [comment]
another: 9566559-hc

**Comment by erricgunawan** [comment]
11597559-hc

Theme: Arcane

When we enter even the same converted tag number from Calypso/iFramed Gutenberg, the number was turned to be another number again.

So it won't work at all there.

I edited the page from WP Admin and it works just fine there.

**Comment by rodrigoi** [comment]
Fix by @mdawaffe is underway on D26092-code.

**Comment by cecilearkay** [comment]
Adding another report for posterity: https://fr.forums.wordpress.com/topic/probleme-etiquettes/

**Comment by mdawaffe** [comment]
I believe this is now fixed. New updates to pages, portfolios, etc. should work correctly.
