### ISSUE TITLE
Properly escape attr_esc( json_encode( $data ) ) 

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#1170]
Currently we are not doing it right and we could be introducing bugs for people that are not on PHP 5.3 or higher. See shortcode/slideshow.php line 211  for an example how to do it right.
https://github.com/Automattic/jetpack/blob/master/modules/shortcodes/slideshow.php#L211

**Comment by jeherve** [comment]
Closing as I believe this may have been fixed in #24086
