### ISSUE TITLE
All Modules Page: Support Link Consistency

### ISSUE THREAD

**Issue by kriskorn** [Automattic/jetpack#11711]
#### Steps to reproduce the issue

1. Go to wp-admin/admin.php?page=jetpack_modules
2. Click on individual module titles to be redirected to their support page

#### What I expected

That all individual modules link to their respective support page.

#### What happened instead

- Comment Likes
- Progressive Web Apps
- Search

The above modules direct you to the page you are on in WP Admin. ( _The all modules page._ )

Their respective support links are following:
1) Comment Likes - https://jetpack.com/support/comment-likes/
2) Progressive Web Apps - _Not really sure which support article would apply here._
3) Search - https://jetpack.com/support/search/

**Comment by jeherve** [comment]
> Progressive Web Apps - Not really sure which support article would apply here.

We don't really have one, as that module isn't much of a module so far. I've created one just for the sake of that page.
