### ISSUE TITLE
Tile Galleries: Nicer tile gallies display in the WYSYWIG WP Editor

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#1171]
Currently the tiled galleries don't display like they do on the font end of the site in the tinymce editor. The update in 4.0 displays galleries much nicer in the editor then in the

**Comment by abidhahmed** [comment]
I don't think this is needed anymore since Gutenberg is coming and we have better Tile Galleries as part of Jetpack itself. 

Closing this for now, please feel free to reopen if needed.
