### ISSUE TITLE
Clean out unnessary logic from block registration

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#11738]
When blocks were built across multiple repositories, we were relying on some logic to make it easier to show beta blocks in the client even if accompanying PHP registrations were missing.

Now with JavaScript and PHP registrations being in the same repository, we can simplify the setup, e.g.:

https://github.com/Automattic/jetpack/blob/303908fd5bd351a787fd5cfccc002c2d3d5ff86d/class.jetpack-gutenberg.php#L321-L324

See https://github.com/Automattic/jetpack/pull/11673#issuecomment-477107567

**Comment by ockham** [comment]
I'll look into this.

**Comment by simison** [comment]
Do we need preset loading anymore either or can we now simplify it?

https://github.com/Automattic/jetpack/blob/e5cd0d59bc78ed645733cda0121d1b3b3664956e/class.jetpack-gutenberg.php#L286-L327

The bundle output contains `index.json` but that file is now [in the repository](https://github.com/Automattic/jetpack/blob/e5cd0d59bc78ed645733cda0121d1b3b3664956e/extensions/setup/index.json) and can be also synced to wpcom.
