### ISSUE TITLE
Google Translate Widget: not working in all Browsers

### ISSUE THREAD

**Issue by AMcGrady** [Automattic/jetpack#11733]
#### Steps to reproduce the issue

1. Add a Google Translate Widget to site
2. View Live Site on different browsers

Example Site:
https://noorseboskatlover.com/

#### What I expected
To have a dropdown menu to translate the page on all browsers

#### What happened instead
Google Chrome version 72 displays the Title of the Widget but no dropdown

**Screenshots**
Google Chrome 72:
https://d.pr/free/i/xLXU1G

Safari:
https://snag.gy/2lBLSy.jpg

Firefox:
https://snag.gy/KiHque.jpg

**Comment by jeherve** [comment]
It would appear that Google no longer supports the widget:
https://translate.google.com/intl/en/about/website/

![image](https://user-images.githubusercontent.com/426388/55149877-45fb3980-514b-11e9-89dd-18a2a3db8ab5.png)

According to that message though, existing widgets should keep working. Unfortunately, they don't. That's an issue with all widgets, even when they are not created via Jetpack. It's been reported elsewhere as well:
- https://stackoverflow.com/q/55275275/1045686
- https://stackoverflow.com/q/55372689/1045686

Unfortunately, there isn't much we can do about it, short of waiting for Google to solve the issue. I'll see if we can contact them to let them know about the problem.

**Comment by jeherve** [comment]
Here is an example of the widget not working in Chrome, but working in Firefox:
https://jeherve.keybase.pub/testing-gtranslate.html

In the example above, the page only relies on JS offered by Google's Website Translator tool.

**Comment by jeherve** [comment]
Following changes by Google, this should now be fixed, and working in all browsers.
