### ISSUE TITLE
Repeat Visitor: Add "return" as a keyword to trigger it

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#11749]
It's easy to try `/return` to get a "Returning" visitors block. Let's add that to what triggers adding the block.

#### Steps to reproduce the issue

1. Block Editor
2. Try adding a "Returning" visitor block.

#### What I expected
Return is pretty close to repeat visitor in concept, so the block should appear.

#### What happened instead
No block.

**Screenshots**

**Comment by jsnmoon** [comment]
We'd [love to add this](https://github.com/Automattic/wp-calypso/pull/31060), but we've already reached the [maximum of 3 keywords](https://github.com/WordPress/gutenberg/pull/13848) for this block. 

For future reference, we'd also like to add the following keywords:
- `hidden`
- `conditional`
