### ISSUE TITLE
Full feature list: update design and presentation

### ISSUE THREAD

**Issue by joanrho** [Automattic/jetpack#11754]
The module list currently at `/wp-admin/admin.php?page=jetpack_modules` could use a series of fixes to improve the experience.

- [x] Make sure all the links go to a relevant support page.
- [x] Make all the "Activate," "Deactivate," and "Configure" links visible all the time
- [x] Make all the "Configure" links direct the user to the Jetpack setting (when available)
- [x] Add any missing "Configure" links if a setting is available
- [x] Perhaps add a link in the footer or somewhere in settings to help folks needing to debug or bulk activate/deactivate modules

![screencapture-renewed-pigeon-jurassic-ninja-wp-admin-admin-php-2019-03-28-16_15_23](https://user-images.githubusercontent.com/204742/55196557-5f18e000-5175-11e9-86e3-e1d2f31b1861.png)

**Comment by kraftbj** [comment]
Are there any PRs on deck for this issue or will we be moving it out of 7.3? The code freeze is EOD Monday.

**Comment by MichaelArestad** [comment]
@kraftbj we're working on them today.
