### ISSUE TITLE
Twitter timeline width overflow (iPhone)

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/jetpack#11760]
#### Steps to reproduce the issue

1.- Activate Twenty Fourteen on a test site (It also happens on some other themes)
2.- Add the Twitter Timeline Widget
3.- Add parmafansww as the username
4.- Check the site on an iPhone (Checked with iPhone 5/ SE and 7)

#### What I expected

Tweets in the timeline to be correctly displayed
![WhatsApp Image 2019-03-29 at 07 40 07](https://user-images.githubusercontent.com/6404071/55221463-d0a26e00-5209-11e9-9417-b21b6897e069.jpeg)

#### What happened instead
Tweets in the timeline are wider than the widget DIV
![WhatsApp Image 2019-03-29 at 07 30 44](https://user-images.githubusercontent.com/6404071/55221500-e748c500-5209-11e9-9ddb-b63a85ac20b1.jpeg)
(In this image I added 2 Twitter widgets, one for the above mentioned user and another one for mine rantoncuadrado -that is working properly-.

**Screenshots**

A CSS fix was proposed in p9cu9o-1xJ-p2 but it doesn't really fix the problem:

```css
@media (max-width: 600px){
.content-sidebar iframe#twitter-widget-0,
.content-sidebar > *, 
a#clustrmaps-widget-v2, 
#clustrmaps-widget-v2 > *,
.clustrmaps-map-container > * {
    width: auto !important; 
}   

.site { 
       overflow-x: hidden;    
}
}
```

The overflow-x: hidden; doesn’t necessarily fix the issue but at least doesn’t show that bar anymore. 

I used 2 twiter timelines mine and user’s to be sure it has to do with the particular picture they have. And it seems so (Mine rantoncuadrado is the first twitter timeline, user’s the 2nd)

![1](https://user-images.githubusercontent.com/6404071/55221876-d056a280-520a-11e9-9246-2c72bd3c787b.jpeg)

After applying the CSS code both timelines are impacted

![2](https://user-images.githubusercontent.com/6404071/55221878-d2b8fc80-520a-11e9-95ff-83157e240dfe.jpeg)

Note You can’t reproduce the weird behavior in a computer even with http://quirktools.com/screenfly/ or so. You can just see the bug on a real iPhone

Test2: Has it to do with a given tweet?
The tweet that seems to be causing the issue is the t-shirt retweet… Well, I also retweeted it on my Twitter account, but cannot reproduce the problem. It is still properly displayed on my profile, but not so in the user’s
![3](https://user-images.githubusercontent.com/6404071/55221967-06942200-520b-11e9-8af1-13081c17cd54.jpeg)

Test3: Is it browser related?
Browsers behavior (iPhone 7):
Chrome, Safari, Opera Mini and Brave: same issue
**Puffin: WORKS PROPERLY!
Firefox: Doesn’t show the tweets (?)**

Puffin picture:
![4](https://user-images.githubusercontent.com/6404071/55222034-29263b00-520b-11e9-9db2-29e5c4da0289.jpeg)

Test4: Is it theme related? It doesn't seem so.
I changed the theme to Apostrophe2 and the issue is still there on iPhone… well it is even worse. In Firefox the Widget is not showing the time line at all, in Chrome, this is what we get:

https://cld.wthms.co/6RZ3ix

**Comment by yelly** [comment]
I am experiencing a similar issue. The debugging I have done so far has not produced any leads.
Can be viewed on [this site](beerblog.co.il).

**Comment by darrin-rambillo** [comment]
Also facing this issue, and seemingly managing for now with the following CSS

```
.twitter-timeline {
	width: 100vw !important;
}
```

**Comment by jjchrisdiehl** [comment]
Looks like this issue isn't resolved hc-14633184

@jeherve Any news on this?

Can confirm that Darrin's CSS worked

**Comment by brookewp** [comment]
Another report of this here hc-13693797

Gave them CSS fix in the meantime

**Comment by jeherve** [comment]
> Any news on this?

Not yet, but we'll update this issue when we start working on this.

**Comment by wunc** [comment]
This bug affects iOS Safari in general, not just iPhones, and is a longstanding issue.

[This solution](https://stackoverflow.com/a/23083463/4511958) worked for me. For reference, you assign to the iframe a `min-width: 100% !important` and a `width:10px !important` (or something that is less than 100%).

The AMP project solved this issue in basically the same way: https://github.com/ampproject/amphtml/issues/11133

**Comment by cecoates** [comment]
116927-hc

Provided CSS workaround.

**Comment by codestor4** [comment]
I couldn't reproduce this issue on mobile (both Chrome and Safari) on iPhone XS and iPhone 7. 
cc: @rantoncuadrado
