### ISSUE TITLE
Publicize: default Custom Share message is not followed if not edited

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/jetpack#11776]
#### Steps to reproduce the issue

1. Setup FB share connection
1. Create a new post
1. Publish the post
1. Observe that the default share message is the post title

#### What I expected

The shared message in Facebook should be the post title.

#### What happened instead
The post excerpt/summary is shared instead.

#### Workaround
Cut the default custom message and paste it back into the box.

**Comment by jeherve** [comment]
This was done on purpose, as explained here:
https://github.com/Automattic/jetpack/issues/2163#issuecomment-105306134

I can see how confusing this is, though. Ultimately, I think those 2 issues should fix such problems: #261 #565
