### ISSUE TITLE
Tiled galleries loses images in galleries on load

### ISSUE THREAD

**Issue by withinboredom** [Automattic/jetpack#11778]
#### Steps to reproduce
1. In Calypso
2. Add a gallery
3. Add some images
4. Convert to tiled gallery
5. Save the post draft
6. Reload the post (via closing tab or refresh)
7. Edit the images in the tiled gallery (by clicking the little pencil icon)
8. Change to a different style
9. Save the post and reload the post
10. Very likely to find some images (or all of them) missing, keep repeating 6-9 until it happens.

#### What I expected
Tiled galleries to "just work"

#### What happened instead
Lost time and lost images

#### Browser / OS version
Chrome 72.0.3626.109 (Official Build) (64-bit) -- Linux and ChromeOS

#### Context / Source

cc: @Automattic/gutenpack 

See p1550501568176300-slack-automattic for discussion

**Comment by FedgeNo** [comment]
I think this is what's happening here: https://fedgeno.com/118139-2/

**Comment by jeherve** [comment]
This should now be fixed, I cannot seem to reproduce anymore. Noting that we've just merged #20583 to address some issues with transforms, so this may be what fixed things.

I'll close this issue now, do not hesitate to reopen or comment if this still happens to you with the upcoming version of Jetpack, 10.1, scheduled to be released in early september.
