### ISSUE TITLE
Infinite Scroll: stops at page 2 when query is set to Ascending Order

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1178]
I was doing some testing to see if this could be done, and I found that Infinite Scroll DOES work in ascending order when using `pre_get_posts` but for some reason it stops after page 2.

Here’s what I added to `functions.php` in TwentyFourteen (also tried in TwentyTwelve):

```
function ma_ascending_posts( $query ) {
    if ( !is_admin() ) {
        $query->set('order', 'ASC');
    }
}
add_action( 'pre_get_posts', 'ma_ascending_posts' );
```

You can see a working example here: http://mikey.press/nickcage/

**Comment by jeherve** [comment]
@mikeyarce Does using the `infinite_scroll_query_args` filter help, as explained here:
https://github.com/Automattic/jetpack/issues/1135#issuecomment-65706295

**Comment by jeherve** [comment]
Closing this in favor of #1135
