### ISSUE TITLE
Tiled Gallery block: images are served with Photon, but not resized

### ISSUE THREAD

**Issue by ChrisBegley** [Automattic/jetpack#11782]
#### Steps to reproduce the issue

1. Add a Tiled Gallery with Gutenberg using large, hi-res images.
2. The images on the back end and front end aren't resized with Photon. They are loading in the large, full-sized images instead. This causes the browser to freeze up and leads to slow loading on the front end.

#### What I expected
Photon should have added the "w" and "h" attributes to load in smaller versions of the images. This works correctly when using Tiled Gallery and the Classic Editor. 

#### What happened instead
Tiled Gallery (Gutenberg) loads in the full-sized images. This causes the browser to freeze on the back end and the images to load in slowly on the front end if the images are very large.

**Comment by jeherve** [comment]
This should now be fixed.
