### ISSUE TITLE
Jetpack: plugin conflicts with Thrive Apprentice v2.1.5 in `wp-admin`

### ISSUE THREAD

**Issue by StefMattana** [Automattic/jetpack#11788]
A user found out there's a conflict between Jetpack and Thrive Apprentice.

When Thrive Apprentice is active, Plan info doesn't update in wp-adminJetpack dashboard.
User could see prompts that they need to upgrade in order to use Pro features like search and VideoPress.

I tried replicating the issue with success, and I can confirm that doesn't happen in Calypso.
Upon deactivating Thrive Apprentice, the issue disappears.

I suggested the user to report this to the plugin author; from the conversation in the previous issue I opened (3695-gh-jpop-issues), we reckoned we don't need to add this to the Known Issues page for the time being, but reporting the option just in case. 

- Ticket/Forum/Chat: 1908497-zen

**Comment by jeherve** [comment]
Since the product is not freely available, it's going to be hard for us to work on this, try to reproduce the problem and fix it.

> Plan info doesn't update in wp-adminJetpack dashboard

This seems to be the main issue here. Are there any other things that do not work properly in the dashboard?
- Can they activate / deactivate features?
- Can they make changes to feature settings?
- Does the Stats graph in the main Jetpack dashboard work?
- When on WordPress.com, can they make changes to feature settings / access posts / edit posts?

**Comment by StefMattana** [comment]
I can definitely ask the user about that :)
Thanks, Jer!

If I recall it correctly, they cannot activate any paid features when both plugins are active, while the free ones where okay. 

When I tried to replicate the issue at my end, all looked good in WordPress.com (Stats, Plan status etc) although the paid features couldn't be activated from there too.

**Comment by jeherve** [comment]
> When I tried to replicate the issue at my end

Was this on your own site, or on the same site?

If it was on your own site, do you think you could get me a copy of the plugin so I can run some tests?
If it was on the same site, it may be limited to that site and its plan status.

**Comment by StefMattana** [comment]
It's the second guess, but I could try replicating on my test site if I could find a free version of the plugin - even though I suppose you thought of it already, with no success.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
