### ISSUE TITLE
VaultPress: add option to install VaultPress from the modal

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1179]
![screen shot 2014-10-10 at 10 00 39 am](https://cloud.githubusercontent.com/assets/3220162/4596047/24b3f340-509f-11e4-9b02-1643bc21e0fc.png)

I would suggest we change this to "Install VaultPress" which would then install the VaultPress plugin and take you to Jetpack > VaultPress where you can activate a Free Trial.

**Comment by richardmuscat** [comment]
@jeherve why is this issue from 2 years ago added to JPR? we won't even have the modals.

**Comment by jeherve** [comment]
> we won't even have the modals.

That's the point :) Once JPR ships, that issue will be closed.

**Comment by richardmuscat** [comment]
This will become redundant when 4.3 ships.
