### ISSUE TITLE
Staging/Development Mode: Check and use `WP_LOCAL_DEV`

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#11798]
Jetpack Development Mode and Staging Mode are used by plugin and site developers to indicate if a site should function without a WordPress.com connection or if the site is a staged copy of a production site.

Core's new site health reports on the status of the `WP_LOCAL_DEV` constant. I've found this referenced in various blog posts, but I hadn't seen a Core usage of it until now.

With Core reporting it, we should determine how we will act with it.

#### Describe the solution you'd like
If Jetpack is connected (e.g. tokens) and `WP_LOCAL_DEV` is set, go into Staging Mode.
If Jetpack is not connected and `WP_LOCAL_DEV` is set, go into Development Mode.
Ensure filters can be used to modify this behavior (at least set/disable each mode).

**Comment by kraftbj** [comment]
Moving this out of the milestone.

**Comment by jeherve** [comment]
Related core ticket, offering a new `SITE_ENVIRONMENT` constant in Core itself:
https://core.trac.wordpress.org/ticket/33161

**Comment by kraftbj** [comment]
https://core.trac.wordpress.org/changeset/47919
https://core.trac.wordpress.org/changeset/48188

**Comment by kraftbj** [comment]
From the changesets and reading the ticket,
1. We can expand our hardcoded list ( https://github.com/wp-media/wp-rocket/blob/c7a020448d6639ca3cb4cddf72195f9d9c18fbec/inc/functions/api.php#L85 ).

2. I'm thinking we can pull this value as the default, while still using our filter afterwards. Since our product can be a little weird and sometimes people do want to act like Jetpack is working even though they're on staging, we should let it be filtered by us still.
