### ISSUE TITLE
Add `wp-polyfill` as a dependency for all the blocks

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#11793]
Since we're not polyfilling blocks during the build step, we're manually adding `wp-polyfill` as a dependency to several blocks.

Changes in block files could accidentally render the block broken in IE11 or other old browsers and to be on safe side, we should add `wp-polyfill` as a dependency to all the blocks.

Ideally the polyfill would be loaded conditionally depending on browser's age, but that's for 2nd iteration.

**Comment by sirreal** [comment]
Shall we plan to handle this as part of #11591?

**Comment by simison** [comment]
Sounds good to me 👍
