### ISSUE TITLE
Wufoo Shortcode

### ISSUE THREAD

**Issue by joshbetz** [Automattic/jetpack#1180]
There's a Wufoo shortcode on WordPress.com that should be included in Jetpack.

**Comment by jimmyandrade** [comment]
Any news about this? (Open since Oct 2014)

**Comment by jkudish** [comment]
It's on our team's list to go through all the shortcodes/embeds on WP.com and sync as many as possible to Jetpack.

Jetpack pit crew: Since this hasn't happened yet, feel free to sync this one individually, there's no reason not to.
