### ISSUE TITLE
Add Gutenpack specific linting rules

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#11822]
- can we use these in Jetpack from [shared Gutenberg config](https://github.com/WordPress/gutenberg/tree/29b3dc5f26bef7b991ed0556ed6bfcc1be754396/packages/eslint-plugin)?
- shall we simply copy these over to Jetpack and include in [Eslint overrides](https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns) for [`extensions`](https://github.com/Automattic/jetpack/tree/eb67cd555521dc06cdd916f757d5ae04b2144940/extensions) folder?
- https://eslint.org/docs/user-guide/configuring#using-a-shareable-configuration-package

https://github.com/Automattic/wp-calypso/blob/3892cdcb868ca8892f192bb2f19c40db58fbbf1c/.eslintrc.js#L24-L46

See also higher level eslint task: https://github.com/Automattic/wp-calypso/issues/31204

**Comment by jeherve** [comment]
This should no longer necessary now that we've improved the linting setup.
