### ISSUE TITLE
Markdown block: add footnotes support

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/jetpack#11849]
### Issue 

Markdown block does not render/hyperlink footnotes as it should

### Steps to reproduce

Create a site on WordPress.com, or .org site with Jetpack (Markdown enabled in settings)
Add markdown block
Paste in footnote markdown
   e.g- 
```
I have more [^1] to say up here.  
[^1]: To say down here.
```
Preview/Publish

### Expected Result
I expected something along the lines of https://www.markdownguide.org/extended-syntax/#footnotes

### Actual Result
Seems to not render the footnote page jump links

WP.com
![image](https://user-images.githubusercontent.com/16580129/52027095-298aaa00-24d8-11e9-9d64-9e57123e4356.png)

Jetpack site
![image](https://user-images.githubusercontent.com/16580129/52027305-eaa92400-24d8-11e9-8492-04ebc73d72cb.png)

**Comment by jeherve** [comment]
Related: #325 for the Classic Markdown feature.

**Comment by liviopv** [comment]
Another request 2003538-zen

**Comment by liviopv** [comment]
Also, a non-markdown solution for Footnotes is being discussed in core Gutenberg https://github.com/WordPress/gutenberg/pull/15267

**Comment by vincenzo** [comment]
Any development here? Any workaround to still have footnotes working with Markdown?

**Comment by vincenzo** [comment]
Should've complied with https://en.support.wordpress.com/markdown-quick-reference/

**Comment by jeherve** [comment]
> Any development here? Any workaround to still have footnotes working with Markdown?

We have made no progress on this so far, but will update this issue when we do.

> Should've complied with en.support.wordpress.com/markdown-quick-reference -- it's the link shown as "support reference" for the markdown block.


The Markdown block currently relies on a different flavor of Markdown, thus causing those inconsistencies. See #11881 to find out more.

**Comment by rickmgithub** [comment]
Another one came up here today about footnotes - 2285644-zen

**Comment by KokkieH** [comment]
Requested via [Twitter](https://twitter.com/CoreyJMahler/status/1170498966309310464)

**Comment by adityabhaskar** [comment]
I wonder if this is something related to this issue but the footnotes appear to have completely stopped appearing for non Blocks Editor, Jetpack-powered blogs.

Jetpack still seems to be parsing them but not publishing them—the footnote text was just removed from the published post.

**Comment by jeherve** [comment]
@adityabhaskar Could you paste an example of a footnote you've tried to add to a post using the Classic editor, and where that footnote was not displayed on the site?

Thank you.

**Comment by adityabhaskar** [comment]
```markdown
 - Love of a good dog[^1].

....

[^1]: Read as 'Love of a dog', _because they are all good dogs, Brant_.
```

It was on [this post](https://c306.net/spkeasy/2019/what-makes-a-good-morning/).

The footnote text was completely removed from the published post. For the moment, I have removed the square brackets marking the footnote to make it appear.

**Comment by jeherve** [comment]
It seems to work on my end:

<img width="962" alt="screenshot 2019-09-20 at 16 00 00" src="https://user-images.githubusercontent.com/426388/65332859-c3b27600-dbbf-11e9-9701-9ed020b53f15.png">
<img width="847" alt="screenshot 2019-09-20 at 15 59 52" src="https://user-images.githubusercontent.com/426388/65332861-c3b27600-dbbf-11e9-9db5-f410b0ef7357.png">

Could you give it another try, but while composing your post from the text editor instead of the visual editor?

**Comment by adityabhaskar** [comment]
Yes, it is working now.

I tested it by composing both from the text editor and the visual editor, and it worked. I even updated the reference post, and the footnote shows.

Thanks @jeherve !

**Comment by kosiew** [comment]
Another case here - #2400283-zen.

There is no option to edit as Text in Classic Block.
![Screen Shot 2019-10-05 at 15 02 02](https://user-images.githubusercontent.com/29057562/66251309-630b6780-e781-11e9-97e2-a836f5e6c2be.png)

**Comment by jeherve** [comment]
> There is no option to edit as Text in Classic Block.

You can pick the "Code Editor" option in the block editor's sidebar:

![image](https://user-images.githubusercontent.com/426388/66296257-6e7ba180-e8ed-11e9-9f0a-4deed9e73184.png)

**Comment by msilbers** [comment]
Just experienced this issue and wanted to add some thoughts. It seems to me that Footnotes shouldn't require a markdown block, and previously worked by just enabling markdown on a site in the Writing Settings

When adding a footnote, people generally won't be including a whole paragraph or sentence as markdown text to show that way. It's not how it works in the classic editor.

**Comment by smithkyle45** [comment]
Received another report of this issue in #16931073-hc

* Footnotes not appearing within Markdown block 
* option enabled via WP Admin > Settings > Writing

**Comment by gwensmithx** [comment]
Another instance of this on a Premium Site, markdown enabled. Tried markdown block, paragraph block, code block but couldn't get it to show the footnotes:

17152867-hc
Followup - 2542691-zd

**Comment by sourourn** [comment]
Another one reported, user was unable to add footnotes. Markdown is enabled, tried paragraph block, markdown block, classic block but it did not work.

Chat: 17432713-HC
Follow-up: 2575189-zen

**Comment by fashuvo** [comment]
Another user reported the issue. Markdown is enabled in wp-admin > Settings > Writing, but the footnote doesn't work in the block editor. Suggested them to use Page Jumps as an alternative for now.

Ticket: 2596298-zen

**Comment by mriyazuddin** [comment]
Another user faced this issue here: 2625624-zen

**Comment by llune** [comment]
I have the same issue! I'm using Jetpack on a self-hosted blog and the Markdown block but foonotes are not working.

**Comment by gwensmithx** [comment]
I'm sad to see this is still open. I have a user on a simple site and footnotes are not working. Everything else is working fine in the markdown block and markdown is enabled. Tried using code block, editing via HTML, paragraph block, markdown block but couldn't get the footnotes to display.

Zen# 2902657
HC: 20467334

**Comment by jeherve** [comment]
Using other blocks or the Markdown block indeed won't work. Jetpack's Markdown block relies on [the Markdown It library](https://github.com/markdown-it/markdown-it) to parse content and create HTML. This library does not currently support footnotes, hence why the block using that library does not support footnotes either.

We could potentially add support for footnotes via an additional plugin for the library, as described in https://github.com/Automattic/jetpack/issues/11881#issuecomment-457610671
However, we're not currently working on the Markdown block. When we next iterate on this block however, we'll definitely consider it!

**Comment by monogenea** [comment]
I am having the same problem. I tried everything but the footnotes are not parsed. Neither Code or Visual editors work. Any idea of when this could be sorted?

**Comment by jeherve** [comment]
> I tried everything but the footnotes are not parsed. Neither Code or Visual editors work. 

To use Markdown footnotes right now, and until they are supported in Jetpack's Markdown block, I would recommend using the Classic editor.

**Comment by monogenea** [comment]
@jeherve working now. Note that reverting a post from the modern to the classic editor disables Markdown (at least did not render footnotes for me). A new draft from the classic editor did enable footnotes and the usual markdown features. I look forward to use the updated modern editor with full functionality. Thank you

**Comment by joweber123** [comment]
Another report here 22169373-hc.  The workaround works but they would really like to see this added by default to our platform in the Block Editor.

**Comment by retnonindya** [comment]
Another report: 3104440-zen. I suggested them to switch to Classic Editor, but it would be nice to see the feature added by default on Block Editor.

**Comment by otpidusprime** [comment]
> Another report: 3104440-zen. I suggested them to switch to Classic Editor, but it would be nice to see the feature added by default on Block Editor.

This user came back at 22276497-hc. I am checking for a workaround on the Block Editor using HTML anchors. Shal update this comment once I find something.

**Comment by rinazrina** [comment]
Another report: 3117587-zen

**Comment by carladoria** [comment]
Another report in 3117587-zen. It is not working on the classic editor either. Not only on the user's post but also on one of my test sites with the classic editor.

**Comment by eduardozulian** [comment]
Another request in 3209017-zen

**Comment by mikeicode** [comment]
Another 23315797-hc

**Comment by chrisfromthelc** [comment]
I discovered through a support interaction that [Footnotes syntax](https://michelf.ca/projects/php-markdown/extra/#footnotes) does not work, even though we say it's supported (via Markdown Extra) [here](https://wordpress.com/support/wordpress-editor/blocks/markdown-block/#markdown-extra-and-markdown-in-jetpack).

This wasn't a user-reported issue, but discovered in the context of an interaction.

I've tested and confirmed on a simple WordPress.com Site, an Atomic Site, and a Jetpack-connected self-hosted site to confirm.

**Comment by dhackneya8c** [comment]
User reporting this issue in 23501739-hc

**Comment by badger732** [comment]
Hopping in to say this is happening for me as well.  Footnotes using the [^x] shortcut do not work in the new editor.  Was told to use markdown but that doesn't work either.  tried everything.  This is stupid.

**Comment by KokkieH** [comment]
Another report in https://wordpress.com/forums/topic/footnote-in-mark-down-block-of-new-editor/

**Comment by poojashetty18** [comment]
Another report: 3357048-zen

**Comment by thesacredpath** [comment]
Another report here: 

11315242-hc
Follow-up: 3399389-zen

**Comment by KokkieH** [comment]
Another report: https://wordpress.com/forums/topic/footnotes-ms-word-libreoffice-and-wp-editors/

**Comment by monogenea** [comment]
> @jeherve working now. Note that reverting a post from the modern to the classic editor disables Markdown (at least did not render footnotes for me). A new draft from the classic editor did enable footnotes and the usual markdown features. I look forward to use the updated modern editor with full functionality. Thank you

Again not working. Why is WP rushing into the blocks thing and discarding the classic editor? It does not work with neither Classic or Markdown blocks after setting WP Admin > Writing > Enable Markdown.

**Comment by tanjoymor** [comment]
I ran into another customer asking how to use Footnotes during a Quick Start session. After some testing, I found that in the Block Editor, if you start with regular blocks, there's no way to get the Footnote feature to work.

But if you start in the Block Editor and switch it to the Code Editor, creating a Footnote will work. It ends up creating the text as a Classic Block. You are then able to convert that to Regular Blocks to continue adding new blocks wherever desired.

Here's a recording of the process: https://d.pr/v/FYBiyN

However, you can't add a Classic Block to a page with Regular Blocks to get the same result and you can't switch a page using Regular Blocks to the Code Editor to then add the Footnote markdown - it doesn't work.

You have to start a new page, use the Code Editor, add the Footnote markdown, then convert to Regular Blocks and carry on. If you miss adding the Footnote markdown initially, it can't be added later.

@jeherve Since this has been an open issue for over a year, should we perhaps be editing the support documentation to either reflect this information or remove the information that it's even possible? It's not really a reasonable work around for most customers.

**Comment by swamidass** [comment]
Is there any progress in fixing this?

**Comment by sbathompson-he** [comment]
Another user had this issue in chat today. Both classic and block editor. I even tried the Code Editor, and it seemed to not work for me.

3640581 - ZEN
22995021 - CHAT

**Comment by bernoullies** [comment]
Logging the same issue. Footnotes not rendering in Block or Classic (Visual or Text).

**Comment by happychait** [comment]
30140270-hc

Workaround of using the classic editor > Text tab worked.

**Comment by B3ginnersMind** [comment]
Footnotes do not fit right to the block oriented Gutenberg editor: With a footnote a new block at the end of the text has to be created. If one adds another footnote this remote block has to be modified and expanded. However, the concept of Gutenberg is that one always is editing a block locally only. Furthermore, markdown does only make sense if it can be edited in a _markdown code editor_. Immediately transforming markdown to HTML appears to be counterproductive as one intends to modify footnotes. There seems to be the risk that footnotes might vanish in Wordpress after the end of the classic editor. For me, this is a major obstacle to use Wordpress.

**Comment by jeherve** [comment]
> Furthermore, markdown does only make sense if it can be edited in a markdown code editor.

That is what Jetpack's Markdown block is; a single editor where you can write all your Markdown, footnotes included. 

However, the Markdown library we rely on for that block does not support footnotes out of the box. That is the issue discussed here. For footnotes to work in that block, add-ons to the original library would have to be used, as outlined here:
https://github.com/Automattic/jetpack/issues/11881#issuecomment-457610671

**Comment by shameemreza** [comment]
Here is another one: ZD-5827144. Footnote is not working using the markdown block., so I suggested using the classic editor.
