### ISSUE TITLE
Contact Form Block: Cannot set as re-usable

### ISSUE THREAD

**Issue by ockham** [Automattic/jetpack#11868]
Originally reported at p58i-7sR-p2 #comment-40518 while testing on WP.com

<img width="492" alt="screen-shot-2018-12-04-at-5-23-20-pm" src="https://user-images.githubusercontent.com/96308/49442546-16a27480-f7ca-11e8-86d3-05efb413802b.png">

/cc @georgestephanis

**Comment by jeherve** [comment]
This was fixed in #13924
