### ISSUE TITLE
Gallery Widget: resize images in the widget

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1186]
At the moment, Images in the Gallery widget don't use Photon's `resize` parameter. They use `w` and `h`, which seems to query a full-size image.

It creates 2 issues:
1. It loads full-size images instead of thumbnails. That can be a bit slow.
2. The images can appear squeezed if they were originally very large.

Here is an example:
![screen shot 2014-10-13 at 1 21 40 pm](https://cloud.githubusercontent.com/assets/426388/4612651/34e22bfa-52cb-11e4-9da8-7ff6c7c258c0.png)

Could we update the way the URLs are built in that widget?

Reported here:
https://wordpress.org/support/topic/image-proportions-in-gallery-widget

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/tiled-galleries-using-full-sized-imaged?replies=1&view=all

**Comment by itmustbe** [comment]
I think this is more important than it might seem, as many people don't realize their sites are serving up the full-size images.  For use cases like photo portfolios it is particularly painful and costly in bandwidth, as the full-size images are most often retina-resolution versions.  I assumed Jetpack would use Wordpress' built-in resize and was so surprised to realize that this issue existed.

**Comment by felixdorner** [comment]
+1 

Is there a known work-around / hack so far?

**Comment by pedger** [comment]
I also have the feeling that this is more important than it seems, as some users like to use slideshows loaded with pictures (I've seen cases with more than 60 pictures, taking 150+MB and more than 160 sec to load their homepages). 

Reported at 2405785-t.

**Comment by kraftbj** [comment]
https://github.com/Automattic/jetpack/blob/master/modules/widgets/gallery.php#L235 -- we're calling for the full size. That function also accepts a size array in place of `full`, which WordPress will return the smallest size not smaller than that array value.

We should be able to have something much smarter, using `$this->_instance_width` (default 265), etc

**Comment by lschuyler** [comment]
Also reported in 2488146-t.
