### ISSUE TITLE
Related Posts Block: Available in Block Picker even if Disabled

### ISSUE THREAD

**Issue by ockham** [Automattic/jetpack#11861]
#### Steps to reproduce
1. On a WP.com test site, start a new post in the block editor, and add a 'Related Posts' block.
2. Publish and view the post to verify that the block is present on the frontend.
3. At `https://wordpress.com/settings/traffic/<yourSite>`, disable the Related Posts toggle
4. Reload the published posts, and verify that the Related Posts block is no longer visible
5. Edit the post again in Calypso. 

#### What I expected

The block to be disabled (showing an error that it's unavailable), and to be missing from the block picker

#### What happened instead

The block is still there (displaying example content), and is still shown in the block picker

#### Context

In Jetpack, this works as expected.

I'm guessing something is wrong with block registration.

/cc @tyxla 

#### Primary issue

#32401

**Comment by jeherve** [comment]
To be honest this is how I would expect things to work. On WordPress.com simple sites, the feature is always active, and thus the block is always available. The toggle in the traffic settings allows you to remove the section from the bottom of your posts, but it does not disable the feature (unlike the toggle in Jetpack sites, which does disable the module entirely). 

If anything, I would like the block to be less coupled to the module in Jetpack as well. What do you think?

Related: #11021

**Comment by MichaelArestad** [comment]
> If anything, I would like the block to be less coupled to the module in Jetpack as well. What do you think?

I agree. I think we should decouple the block from the module. The block should be always on regardless of whether the module is.

**Comment by jeherve** [comment]
Related: #20628
