### ISSUE TITLE
Tiled gallery block: support re-ordering images by dragging

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#11874]
Right now the only way to ensure specific order of images is to add them in a specific order. There's no way to re-arrange them short from deleting some images and re-adding them in right order.

Would be lovely to be able to re-order images by dragging:

<img width="767" alt="image" src="https://user-images.githubusercontent.com/87168/49235104-f48fa780-f401-11e8-8264-4e7ae9481827.png">

- Not quite sure how that should look for mobile though.

- Core gallery doesn't currently support this neither, but there are some open PRs: https://github.com/WordPress/gutenberg/pull/9945 https://github.com/WordPress/gutenberg/pull/7946

- See also `Draggable` component: https://github.com/WordPress/gutenberg/tree/ba7ddb9319be36d43f199ea29af7070f34f0fbfc/packages/components/src/draggable#readme

**Comment by darnelldibbles** [comment]
Another user report in the [forums](https://en.forums.wordpress.com/topic/problems-with-new-galleries/)

**Comment by simison** [comment]
Closing this, here's another more elaborate one for this: https://github.com/Automattic/jetpack/issues/14546
