### ISSUE TITLE
Map block: maps without markers forget their position

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#11892]
Map forgets its location in the published post if it doesn't contain markers.

I positioned a map in the editor and hit "publish post". I expected to see a map like I saw in the editor also at the theme side.

Instead:
- [x] it jumped back to default position.
- [x] The map isn't from site edge-to-edge like it's in the editor (using [TwentyNineteen](https://github.com/WordPress/twentynineteen/) theme)
- [ ] I see "full screen" icon at the theme side, although I don't see it in the editor. The editor version should look as close to the like the output as possible when the block is unselected.
- [ ] In the theme side, borders in +/- icons look a bit off: 
    <img width="74" alt="image" src="https://user-images.githubusercontent.com/87168/48888954-f2937a80-ee3c-11e8-9885-85ebd259adc2.png">

## I expected this

<img width="400" alt="screenshot 2018-11-22 at 09 38 30" src="https://user-images.githubusercontent.com/87168/48888752-5bc6be00-ee3c-11e8-99b5-4b1046dbccb7.png">

## I got this instead

<img width="400" alt="screenshot 2018-11-22 at 09 38 53" src="https://user-images.githubusercontent.com/87168/48888751-59646400-ee3c-11e8-8071-0be75c19fbfd.png">

cc @MichaelArestad  @jeffersonrabb

**Comment by Copons** [comment]
> it jumped back to default position.

This is not the case anymore! 🎉
