### ISSUE TITLE
Map Block: Add option to prevent map zoom if you scroll while cursor is on the map

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#11904]
#### Steps to reproduce
1. Add a map to a page.
2. View the page.
3. Scroll down the page using trackpad or scroll wheel
4. Try to scroll while the cursor is over the map.

#### What I expected

The page will continue to scroll.

#### What happened instead

The map zoomed in/out instead

#### Browser / OS version

Chrome Version 70.0.3538.110 (Official Build) (64-bit)
MacOS 10.14

#### Screenshot / Video

![map-scroll-zoom](https://user-images.githubusercontent.com/1990037/49886800-7c2ddb00-fe32-11e8-80c8-ef9c05ac8a94.gif)

#### Context / Source

Reported in 1618575-zen

**Comment by melchoyce** [comment]
Worth noting this also happens inside the editor — and when you scroll inside the editor, it resets the position of the map on the front-end. So if you scroll down, get trapped in the map, and accidentally move around or zoom out, that new position is saved when you publish or update the page. I've done this a couple times already on the WCUS site and it's a pain.

**Comment by melchoyce** [comment]
Still really annoying!

**Comment by iamtakashi** [comment]
+1. This prevents layouts to have a large map. 

@michaeldcain has noted Google's solution [here](https://github.com/Automattic/Dotcom-roadmap/issues/74#issuecomment-577263881).
