### ISSUE TITLE
Port Box.com widget from WordPress.com 

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#1190]
As requested from a Jetpack user in 1967314-t, we could port the Box.com widget from WordPress.com:

http://en.support.wordpress.com/widgets/boxcom-widget/

**Comment by jwenerd** [comment]
It says now on WordPress.com that "As of December 1st, 2014, Box.com sharing widgets can no longer be created. Instead, you can create a link to a shared Box.com file or folder."  

So perhaps this should be closed.  Alternatively,  Jetpack could support the box.com embed code which allows individual folders or files to be embedded.

**Comment by jkudish** [comment]
This has been removed from WP.com so no-go :-1:
