### ISSUE TITLE
Import material icons from library

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#11901]
Since we decided using [Material icons](https://material.io/tools/icons/) on our Gutenberg blocks (https://github.com/Automattic/wp-calypso/issues/28519, https://github.com/Automattic/wp-calypso/issues/28500), we'll have plenty more of these coming up.

Would be great to be able to import these directly from a library instead of manually copying them over like we're doing now.

We'll need the actual SVG contents, not just image path and image copied with bundle like we do for the rest of the images:

https://github.com/Automattic/wp-calypso/blob/70d34aeda7ed952d929269bf60b9cf60e6dad5db/client/gutenberg/extensions/simple-payments/editor.js#L29-L34

Some candidate source libraries:
- https://www.npmjs.com/package/@material-ui/icons
- https://www.npmjs.com/package/material-design-icons

(via https://github.com/Automattic/wp-calypso/pull/28501#issuecomment-438417992)

**Comment by simison** [comment]
Relevant reading https://make.wordpress.org/design/2019/02/12/whats-next-for-dashicons/

**Comment by simison** [comment]
>It looks like Gutenberg has a custom SVG wrapper

Might change in future: https://github.com/WordPress/gutenberg/issues/14628

**Comment by blowery** [comment]
Relevant work over in Calypso: https://github.com/Automattic/wp-calypso/pull/32172

**Comment by simison** [comment]
We now have internal NPM package where we can pull from https://github.com/Automattic/wp-calypso/tree/3e69a83a497e8e2c0708d074311398cd98037df0/packages/material-design-icons

**Comment by simison** [comment]
We now also have `@wordpress/icons` library.
