### ISSUE TITLE
Call to undefined function WP_Error in .../publicize-services.php:148

### ISSUE THREAD

**Issue by GaryJones** [Automattic/jetpack#11919]
A WordPress.com VIP client (PHP 7.2), who has so much Jetpack stats that it can't be returned and so just links to the view on WordPress.com, reported the following:

```
Error: Uncaught exception ‘Error’ with message ‘Call to undefined function WP_Error()’ in /.../mu-plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/publicize-services.php:148

Stack trace
in WPCOM_REST_API_V2_Endpoint_List_Publicize_Services::get_items_permission_check called at /.../wp-includes/rest-api/
class-wp-rest-server.php (916)
in WP_REST_Server::dispatch called at /.../wp-includes/rest-api/
class-wp-rest-server.php (329)
in WP_REST_Server::serve_request called at /.../wp-includes/rest-api.php (309)
in rest_api_loaded called at /.../wp-includes/class-wp-hook.php (286)
in WP_Hook::apply_filters called at /.../wp-includes/class-wp-hook.php (310)
in WP_Hook::do_action called at /.../wp-includes/plugin.php (531)
in do_action_ref_array called at /.../wp-includes/class-wp.php (387)
in WP::parse_request called at /.../wp-includes/class-wp.php (737)
in WP::main called at /.../wp-includes/functions.php (1105)
in wp called at /.../wp-blog-header.php (16)
in require called at /.../index.php (17)
```

Ref: [code](https://github.com/Automattic/jetpack/blob/201ec52be66261a364f0805a6e44d25269d84793/_inc/lib/core-api/wpcom-endpoints/publicize-services.php#L148)

Their logs show that this was happening at least in Jetpack 7.1, and continues in Jetpack 7.2.

**Comment by jeherve** [comment]
hm, that's odd. Are they on WordPress.com or VIP Go? If they use Jetpack, do they use a custom version? If so, could you confirm that their version of Jetpack includes this fix?
https://github.com/Automattic/jetpack/pull/11502/files

If yes, do you think you could check if:
- they use the Publicize module.
- they have any CPTs on their site.

That could help us narrow down the issue.

Thanks!

**Comment by GaryJones** [comment]
- VIP Go
- standard version AFAIK - https://github.com/Automattic/vip-go-mu-plugins says it's submodule with hash 61a625b71fc15d11f36b16facc42376418c6b9b9 which is indeed the same has that was tagged for the 7.2 release.

I'll check on the other questions.

**Comment by kraftbj** [comment]
Not hearing other reports or additional information about this error, I'm going to close this.
