### ISSUE TITLE
Slideshow block: Unhandled promise rejection

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#11917]
#### Steps to reproduce
1. Visit https://deutsche-musical.de/night-of-classics/
2. Scroll down to the slideshow
3. When the auto-play returns to the first slide, note that the image is missing!
4. Note `Unhandled promise rejection TypeError: "n is undefined"` in the console

I was only able to observe the bug in Firefox.I was not able to replicate this behavior on any of my testing sites, so I'm not sure how to work out a fix.

Pinging @jeffersonrabb 

h/t to @benchilcote for reporting

**Comment by simison** [comment]
We haven't heard from these issues withing a month (we used to hear more) so I suspect we can close?

**Comment by simison** [comment]
@scruffian the slideshow there doesn't currently work because of https://github.com/Automattic/jetpack/issues/11910
