### ISSUE TITLE
Slideshow Block Not Working When Published

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/jetpack#11910]
#### Steps to reproduce the issue

1. Go to post or page editor
2. Add a Slideshow block to the post or page
3. Add images to the block
4. Publish the page or post

#### What I expected

When viewing the page or post, the slideshow will advance when the forward/backward buttons are clicked and, if autoplay is enabled, slideshow will autoplay

#### What happened instead
Slideshow doesn't autoplay, and navigation buttons don't work

**Screenshots**
Screen recording: [https://cld.wthms.co/jIzmqE](https://cld.wthms.co/jIzmqE)

Reported in #11677427-hc / #1935045-zen and #11811004-hc

**Comment by simison** [comment]
This is limited to Jetpack self hosted and Atomic sites. Simple sites are not affected.

https://github.com/Automattic/jetpack/pull/11913 fixes this and we'll ship it today.
