### ISSUE TITLE
Search suggestions should only show if the user actively installed JetPack (not pre-installs)

### ISSUE THREAD

**Issue by DavidAnderson684** [Automattic/jetpack#11918]
I'm following with interest the debate upon adding feature suggestions into plugin search results.

The rationale being given (and I think this is an honourable, defensible point of view, though I have strong reservations about how it's being applied) is that if the user installed JetPack, then it's not wrong to inform the user of what they've already got installed. To let them know that they don't need a new plugin - that they already have the features.

However, this rationale fails in situations in which the user did not install and activate JetPack themselves. If JetPack was pre-installed by the hosting company, then the user never indicated a specific interest in JetPack.

In that situation, JetPack is effectively gaming the search results. Giving itself an unearned advantage. The user never indicated interest in JetPack, and what the user searched for may have previously resulted in JetPack appearing in position #4, or off the initial viewport entirely. The JetPack pre-install effectively gets it into #1 position for the viewer's eyeballs (which research shows is very influential).

So, if the rationale is that users can be informed if they previously actively showed interest, then there should be code to test for that. e.g. That one of several actions was taken to indicate that, e.g. plugin was installed from the directory. Otherwise, JetPack should appear in the search results only where it would otherwise have appeared, based upon the search term entered.

**Comment by jeherve** [comment]
The Feature hints are only displayed once you've connected your site to your WordPress.com. They consequently won't be displayed on your site unless you went through the connection process.

As a result, they are not displayed on a site where Jetpack was pre-installed but when the site owner did not actually express interest in using the plugin that came installed (and in some cases activated) for them.

I hope this clarifies things a bit.

**Comment by DavidAnderson684** [comment]
@jeherve Thank you, yes, that does clarify things, and is a good thing.
