### ISSUE TITLE
Settings - Create Extra Sidebar Widgets setting 

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#11933]
The Extra Sidebar Widgets module will no longer be on by default. Because of this, we need to make a setting for it visible in Jetpack and Calypso settings.

It will exist in the Writing tab of Jetpack and Calypso settings.

Here is the copy used:
```
Make extra widgets available for use in your sidebar including images and Twitter streams
```

The copy was loosely copied from a card already implemented in Jetpack Settings. You can see it in action if you search for "widgets". However, I think the copy could use an update so I'd like us to see if we can improve it and then we'll pull in editorial.

Here is what it will look like:

![image](https://user-images.githubusercontent.com/1123119/55582571-174a0980-56dd-11e9-9c28-d274fd9cfdcb.png)

Here is what it will look like in context:

![image](https://user-images.githubusercontent.com/1123119/55582583-1c0ebd80-56dd-11e9-86ed-ba7223f14c39.png)

Dev needs:
- [x] Add to Jetpack settings and make sure it is off by default
- [x] Add to Calypso settings
- [x] Just like the other settings, the toggle should immediately activate or deactivate the feature and show global notices representing "saving/saved/error" states.
- [x] Remove old searchable-only card (probably can copy useful bits out of the old card)

**Comment by crunnells** [comment]
Design looks good. Copy suggestion:

> Make extra widgets availble for use on your site including images and Twitter streams

Not all themes have sidebars, and widgets can be in headers, footers, posts, etc. Another approach would be to say "themes" instead of "site" but I think people probably understand the latter more.

**Comment by MichaelArestad** [comment]
Perfect.

**Comment by oskosk** [comment]
@MichaelArestad in your screenshot you show a "SAVE SETTINGS" button, but we only have toggles in there. The button is not needed, right?

**Comment by eliorivero** [comment]
Reopening since it was closed by mistake: we still need to address the Calypso side.

**Comment by MichaelArestad** [comment]
@oskosk I missed that comment, but there is no need for a save settings button.
