### ISSUE TITLE
Settings - Create Shortcode embeds setting

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#11934]
The Shortcode embeds module will no longer be on by default. Because of this, we need to make a setting for it visible in Jetpack and Calypso settings.

It will exist in the Writing tab of Jetpack and Calypso settings.

Here is the copy used:
Toggle label
```
Compose using shortcodes to embed media from popular sites
```

Tooltip:
```
Shortcodes are WordPress-specific markup that let you add media from popular sites. This feature is no longer necessary as the editor now handles media embeds rather gracefully.
```

The copy was loosely copied from a card already implemented in Jetpack Settings. You can see it in action if you search for "shortcode". However, I think the copy could use an update so I'd like us to see if we can improve it and then we'll pull in editorial.

Here is what it will look like:

![image](https://user-images.githubusercontent.com/1123119/55582732-74de5600-56dd-11e9-8914-a4f22cbd199c.png)

Here is what it will look like in context:

![image](https://user-images.githubusercontent.com/1123119/55582737-7871dd00-56dd-11e9-9a7c-ba2b85e63cf3.png)

Dev needs:
- [x] Add to Jetpack settings and make sure it is off by default
- [x] Add to Calypso settings
- [x] Just like the other settings, the toggle should immediately activate or deactivate the feature and show global notices representing "saving/saved/error" states.
- [x] Remove old searchable-only card (probably can copy useful bits out of the old card)

**Comment by crunnells** [comment]
Design looks good. Copy suggestion:

> Compose using shortcodes to embed media from popular sites into posts and pages

**Comment by MichaelArestad** [comment]
I think I would stick with the original just because the surrounding settings don't mention posts or pages either. Just for consistency.
