### ISSUE TITLE
Settings - Create WP.me shortlinks setting

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#11935]
The WP.me shortlinks module will no longer be on by default. Because of this, we need to make a setting for it visible in Jetpack and Calypso settings.

It will exist in the Writing tab of Jetpack and Calypso settings.

Here is the copy used:

Toggle label:
```
Create short and simple links for all posts and pages 
```

Tooltip:
```
Generates shorter links so you can have more space to write on social media sites.
```

The copy was already implemented in Jetpack Settings. You can see it in action if you search for "shortlinks". However, I think the copy could use an update so I'd like us to see if we can improve it and then we'll pull in editorial.

Here is what it will look like:

![image](https://user-images.githubusercontent.com/1123119/55582916-d999b080-56dd-11e9-969c-eb5b4b59f16f.png)

Here is what it will look like in context:

**Note: this will be in the Traffic sections. Not the Sharing section.**

![image](https://user-images.githubusercontent.com/1123119/55582921-dc94a100-56dd-11e9-8bad-b2716d572cb2.png)

Dev needs:
- [x] Add to Jetpack settings and make sure it is off by default
- [x] Add to Calypso settings
- [x] Just like the other settings, the toggle should immediately activate or deactivate the feature and show global notices representing "saving/saved/error" states.
- [x] Remove old searchable-only card (probably can copy useful bits out of the old card)

**Comment by crunnells** [comment]
Design looks good. Let's make the copy a little more descriptive:

> Create short and simple links for all posts and pages so you can have more space to write on social media sites.

The above partially taken from the Jetpack.com/support description for WP.me Shortlinks

**Comment by MichaelArestad** [comment]
Perfect.

**Comment by eliorivero** [comment]
<img width="741" alt="Captura de Pantalla 2019-04-16 a la(s) 14 12 48" src="https://user-images.githubusercontent.com/1041600/56230052-ca0d5680-6051-11e9-811a-5fc04f6f153d.png">

Text looks super long. Maybe this is more suitable for the popover and we can reduce this to 

> Create short links for all posts and pages to share on social media sites.
