### ISSUE TITLE
Settings - Create beautiful Beautiful Math setting

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#11931]
Beautiful Math will no longer be on by default. Because of this, we need to make a setting for it visible in Jetpack and Calypso settings.

It will exist in the Writing tab of Jetpack and Calypso settings.

Here is the copy used:
```
Use LaTeX markup for complex equations and other geekery
```

The copy was already implemented in Jetpack Settings. You can see it in action if you search for "Beautiful". However, I think the copy could use an update so I'd like us to see if we can improve it and then we'll pull in editorial.

Here is what it will look like:

![image](https://user-images.githubusercontent.com/1123119/55581840-1e701800-56db-11e9-9a3e-0432a7988473.png)

Here is what it will look like in context:

![image](https://user-images.githubusercontent.com/1123119/55581812-1021fc00-56db-11e9-9722-df09d9899653.png)

Dev needs:
- [ ] Add to Jetpack settings and make sure it is off by default
- [ ] Add to Calypso settings
- [ ] Just like the other settings, the toggle should immediately activate or deactivate the feature and show global notices representing "saving/saved/error" states.
- [ ] Remove old searchable-only card (probably can copy useful bits out of the old card)

**Comment by oskosk** [comment]
Proposal in #11956. Will wait for copy review before merging

**Comment by crunnells** [comment]
Design looks good!
