### ISSUE TITLE
Remove Happiness banner and upsell from Jetpack settings

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#11938]
I'm proposing we remove this banner from Jetpack settings:

![image](https://user-images.githubusercontent.com/1123119/55583592-74df5580-56df-11e9-8b61-b29aa2e10d34.png)

It would remain on the Jetpack Dashboard. The idea is that we are simplifying the number of items competing for attention within settings.

Before we remove this, it would be good to get input from our marketing team and from Happiness.

**Comment by tmmbecker** [comment]
I agree that it would slim things down, but it would be great if we had some data here to make a more informed decision, so that we aren't inadvertently removing an avenue that's frequently used to contact us.

**Comment by MichaelArestad** [comment]
@tmmbecker I agree! You can see a little data in the comments on this thread: p1HpG7-6x9

We're still trying to determine if we should remove it and want both Marketing and Happiness to weigh in before we move forward with this.

**Comment by chaselivingston** [comment]
I think an important distinction here is that this proposal is for removing the banner from Jetpack > Settings, but not the Jetpack > Dashboard which is likely the main landing page for customers interacting with Jetpack in wp-admin. If that's the case, then I can support removing the banner from Settings while leaving it available on the Dashboard.
