### ISSUE TITLE
Settings - Create widget visibility setting

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#11936]
The Widget visibility module will no longer be on by default. Because of this, we need to make a setting for it visible in Jetpack and Calypso settings.

It will exist in the Writing tab of Jetpack and Calypso settings.

Here is the copy used:
```
Control where widgets appear on your site with visibility settings
```

The copy was already implemented in Jetpack Settings. You can see it in action if you search for "widget". However, I think the copy could use an update so I'd like us to see if we can improve it and then we'll pull in editorial.

Here is what it will look like:

![image](https://user-images.githubusercontent.com/1123119/55583053-2bdad180-56de-11e9-8fc2-415cb1d78adb.png)

Here is what it will look like in context:

![image](https://user-images.githubusercontent.com/1123119/55583060-31381c00-56de-11e9-9894-08b97516774c.png)

Dev needs:
- [x] Add to Jetpack settings and make sure it is off by default
- [x] Add to Calypso settings
- [x] Just like the other settings, the toggle should immediately activate or deactivate the feature and show global notices representing "saving/saved/error" states.
- [x] Remove old searchable-only card (probably can copy useful bits out of the old card)

**Comment by crunnells** [comment]
Design is solid. I wonder if we can work the word "visibility" into the copy here, since that's what it's called in the Widgets UI.

> Control where widgets appear on your site with visibility settings.

**Comment by MichaelArestad** [comment]
Let's try it. It still sounds a little funny, but maybe Editorial can help us smooth it out.

**Comment by eliorivero** [comment]
Reopening because this is not ready: the searchable module hasn't been removed and the feature itself is not searchable.
