### ISSUE TITLE
Testimonial

### ISSUE THREAD

**Issue by benlumia007** [Automattic/jetpack#11943]
When I add the following support

add_theme_support( 'jetpack-testimonials' );

it should give me choices in the customizer right, 

I also added this so that I can edit

```
$testimonial_title = get_option( 'jetpack_testimonials[page-title]', esc_html__( 'Testimonials', 'camaraderie' ) );
$title             = '';

if ( isset( $testimonial_title ) && '' !== $testimonial_title ) {
	$title = esc_html( $testimonial_title );
} else {
	$title = esc_html( post_type_archive_title( '', false ) );
}
echo $before . $title . $after; // phpcs:ignore
```
i've tried whatever I can think of, when i try to change the title, content, and the featured image on a custom template. its not showing up especially when i create an `archive-jepack-testimonial.php`

**Comment by jeherve** [comment]
You would need to use `add_theme_support( 'jetpack-testimonial' );` instead of `add_theme_support( 'jetpack-testimonials' );` (notice the `s`). That will help.

**Comment by benlumia007** [comment]
sorry, i checked my code. im actually using add_theme_support( 'jetpack-testimonial' );

**Comment by benlumia007** [comment]
first of all, i'm trying to use `add_theme_support( 'jetpack-testimonial' );` to create a custom page so I can display the output of the title, content and the featured image. I want to be able to edit and change the content, the title from a custom loop using single-jetpack-testimonial.php and archive-jetpack-testimonial.php

and is not displaying whatsoever.  all i did for jetpack-portfolio by using get_option( 'jetpack_portfolio_title' ); and i can change it. but for  get_option( 'jetpack_testimonails[page-title]' ); it won't display if i want to change the default.

**Comment by benlumia007** [comment]
i'm going to assume because its an array, so how exactly am i as a developer for my theme to be able to display the word Testimonials from grabbing the settings int he customizer.

**Comment by benlumia007** [comment]
forget it, i figured it out
