### ISSUE TITLE
Block Does Not Appear When a More Block has Hide Teaser Active

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/jetpack#11959]
#### Steps to reproduce the issue

1. Open a post or page from WP Admin
2. Add test text to the post or page
3. Add a More block, and activate the "Hide Teaser Before The More Tag" option
4. Add a MailChimp block

#### What I expected
Page wouldn't display text above the More block, but all content beneath the More block, including the MailChimp block, would be displayed

#### What happened instead
MailChimp block is not displayed, other content after the MailChimp block is shown as expected

**Screenshots**
![Screen Recording](https://cld.wthms.co/ONw1qQ+)

Initially reported in #1940339-zen

**Comment by simison** [comment]
Seems to happen with other blocks that require view-side JS/CSS, too. For example tiled gallery:

<img width="1887" alt="image" src="https://user-images.githubusercontent.com/87168/55739582-fada0400-5a31-11e9-9801-856015d1f81f.png">

**Comment by simison** [comment]
Confirmed this happens in current Jetpack `master` as well with latest stable version 7.2.1.

**Comment by simison** [comment]
Noting that in the post content, block meta is visible (the stuff with `<!-- -->`) while normally those aren't there.

<img width="628" alt="image" src="https://user-images.githubusercontent.com/87168/55746376-341a7000-5a42-11e9-9cc3-b003234c3290.png">

Made me me think this is a core bug, but regular core gallery block does load styles just fine in this scenario.

**Comment by simison** [comment]
Confirmed this is a core bug, closing this one: https://github.com/WordPress/gutenberg/issues/14874
