### ISSUE TITLE
A/B test removal of green connection bar

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#11955]
The green bar isn't very helpful in the connection banner. We either need to come up with a way for it to be helpful (as it is is quite eye catching) or we should test removing it. For now, we're going to test removing it.

Here's what it currently looks like:

![image](https://user-images.githubusercontent.com/1123119/55642824-cdb9f700-578e-11e9-9349-a61869ad9574.png)

**Comment by MichaelArestad** [comment]
@joanrho I thought initially the banner needed to be updated to reflect our focus on security and performance, but it already does that. What aspect of the banner needs updating? The only thing that stands out to me is that it would probably be good to remove "You're almost done."

**Comment by jeffgolenski** [comment]
Relevant conversation on the green bar posted in the comments here: p1HpG7-6yy

**Comment by crunnells** [comment]
If I understand correctly, we're going to do an A/B test on the green bar to see if losing it negatively impacts connections, right?

**Comment by MichaelArestad** [comment]
I don't think so. I was planning on just removing it and looking for a dip in connections from it.

**Comment by joanrho** [comment]
@MichaelArestad @crunnells any reason _not_ to A/B test and, with all other conditions being the same, determine after our hypothesis tool has established significance that one or the other is the winner/route to take going forward? It's just a bit more deliberate and controlled so the results aren't due to chance.

**Comment by crunnells** [comment]
@joanrho I really like the idea of using an A/B test for this so we can make a more informed decision about removing this banner. Let's do it!

**Comment by MichaelArestad** [comment]
@eliorivero I updated the description. Can you set up an A/B test with the removal of the green banner? I think it should just run for one release cycle.

**Comment by jeffgolenski** [comment]
@eliorivero @MichaelArestad  Make sure the version without the green has a new tracks event applied to the jetpack CTA please, so we can see how many connections are made through it, otherwise we won't be able to see any difference in tracks trends.
