### ISSUE TITLE
Subscriptions: Comment submit button filter breaks HTML

### ISSUE THREAD

**Issue by justintadlock** [Automattic/jetpack#11957]
When enabling comment subscriptions on a post, the filter on `comment_form_submit_button` breaks the HTML output of the comment form.

Code reference: 

https://github.com/Automattic/jetpack/blob/2a17aa8cffc665e950c6b62f58365ca13496d0a6/modules/subscriptions.php#L88

https://github.com/Automattic/jetpack/blob/2a17aa8cffc665e950c6b62f58365ca13496d0a6/modules/subscriptions.php#L608

That particular hook is for the `<input>` rather than the wrapper field around the submit input.  Jetpack adds `<p>` tags there and appends the input at the end.

A more appropriate hook might be `comment_form_submit_field`.  That way, you append the entire wrapper `<p>` for the submit at the end instead.

**Comment by jeherve** [comment]
Thanks for the report. 

This was introduced in #11149.

**Comment by Misplon** [comment]
Super, thanks for resolving this :)
