### ISSUE TITLE
Content Options: not working properly for search results page

### ISSUE THREAD

**Issue by rilwis** [Automattic/jetpack#11977]
We have a problem with the Content Options. In our theme [Floral on wordpress.com](https://wordpress.com/theme/floral), we output the content of the posts in the `content.php` file (which is common and the same as default themes).

However, the Content Options for Blog page doesn't work properly for search results page. Turns out it happens because WordPress searches for **both posts and pages**. And the Content Options only **filter the posts**, not pages.

And that gives an inconsistent content type in the search result page. A customer has reported it [here](https://premium-themes.forums.wordpress.com/topic/setting-the-search-result-to-title-only/#post-142368).

#### Steps to reproduce the issue

1. Go to https://ihya.home.blog/
2. Search for "hikam"
3. See error

#### What I expected

All the content should be excerpt.

#### What happened instead

Post content is excerpt, but page content is full.

**Comment by jeherve** [comment]
cc @thomasguillot

**Comment by thomasguillot** [comment]
This has nothing to do with Content Options. Blog Display doesn't affect the search page, only the blog and the archive pages.

See: `if ( ( is_home() || is_archive() ) && ! is_post_type_archive( array( 'jetpack-testimonial', 'jetpack-portfolio', 'product' ) ) ) {`

By the way, the site above doesn't seem to be using Floral.
