### ISSUE TITLE
VideoPress: Stats in wp-admin are non-functional

### ISSUE THREAD

**Issue by abcxyz-m** [Automattic/jetpack#11983]
#### Steps to reproduce the issue

1. Use VideoPress. Video is popular, gets some views.
2. Attempt to view Stats in wp-admin for that video.

#### What I expected

3. Get sent to the Stats page, where you can view what page(s) reference this video, and view more detailed stats.

#### What happened instead

3. Get redirected back to the Stats main page.

**Screenshots**

![](https://cld.wthms.co/UFdzTe+)
Image Link: https://cld.wthms.co/UFdzTe

I consider this "high" priority, because in combination with #9933, self-hosted users don't really get any Stats tracking out of VideoPress, largely negating the usefulness of this feature.

**Comment by mzakariya** [comment]
Reported in 10963959-hc

**Comment by dallinchase** [comment]
I'm excited for this to be resolved!

**Comment by chasebros** [comment]
Really excited for this to be fixed!

**Comment by joendotcom** [comment]
1950007-zen
