### ISSUE TITLE
Sync: More granularity on sync status details. 

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#11985]
Right now sync status returns how many "sync_items" sync has queued/sent/etc. A "sync_item" is comprised of many objects, we want to be more granular about the types and counts of objects in the "sync item"s.

We want to be able to tell how many posts, comments, users, term that we are sending over in total. 
This will help visualisation and debugging. 

Before:

```
Sent:                     111 items
```

After:

```
Sent:                     50 posts, 20 post meta, 30 comments, 11 options

**Comment by lezama** [comment]
@tyxla this is a hard one, it touches many important aspects of sync. Even if it's really not easy I think it could be a good one to start exploring Sync code.

**Comment by tyxla** [comment]
I've created D27227-code that does this for the Jetpack debugger:

Before:
![](https://cldup.com/nQWXas6_lj.png)

After:
![](https://cldup.com/jcZbC23DXF.png)

Let me know if that makes sense - there's a chance I might be misunderstanding the scope of this task.

**Comment by tyxla** [comment]
#12125 has been merged as a dependency, shipping D27227-code shortly.

**Comment by tyxla** [comment]
D27227-code shipped, change announced in p1HpG7-6Sj-p2, closing.
