### ISSUE TITLE
Connection: Fatal error when connecting network subsite

### ISSUE THREAD

**Issue by dd32** [Automattic/jetpack#11993]
#### Steps to reproduce the issue

1. Go to '/wp-admin/network/admin.php?page=jetpack'
2. Click on 'Connect' for a site
3. See 500 error

The fatal error encountered is:
`Uncaught Error: Cannot use object of type WP_Site as array in wp-content/plugins/jetpack/class.jetpack-network.php:461`

Cause is https://github.com/Automattic/jetpack/pull/11450 where `get_blog_details()` (a WP_Site object) is treated as an array.

**Comment by tyxla** [comment]
Oops! Fix coming up in https://github.com/Automattic/jetpack/pull/11994
