### ISSUE TITLE
“View backups” link sends user to VaultPress

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#11990]
#### What I expected
Link should take user to Calypso’s Activity Log

#### What happened instead
Link takes the user to VaultPress

**Screenshots**
![image](https://user-images.githubusercontent.com/1123119/55823231-84cfae80-5abe-11e9-9b5c-913ad5a2dc9b.png)

**Comment by jeherve** [comment]
> Link should take user to Calypso’s Activity Log

What about site owners that do not have access to Rewind yet (i.e. the majority of our customers today)?

I'll close this issue in favor of #10264 which seems more detailed.
