### ISSUE TITLE
“View security scan details” link sends user to VaultPress

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#12007]
We're going to want to have this point to Calypso's Activity log at some point. Just need to make sure it is a solid replacement for the security view in VaultPress.

**Comment by eliorivero** [comment]
This was done in #11753 and hasn't been released yet so you'd have to use the Jetpack Beta plugin to test Bleeding Edge. Closing for now. If there's something out of place, please reopen and let me know.
