### ISSUE TITLE
Clean out old files on `yarn build-extensions`

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#12019]
`yarn build-extensions` doesn't wipe out `_inc/blocks` folder first (you'd have to manually run `yarn clean-extensions`) so you end up with old files around:

<img width="348" alt="image" src="https://user-images.githubusercontent.com/87168/55945402-65b65580-5c53-11e9-9964-d709980e8c91.png">

This could bring trouble when;
- Testing and file exists when it shouldn't
- When manually syncing to sandbox
- Possibly even when doing a release?

`yarn build-production` includes distclean, which cleans blocks.

**Comment by kraftbj** [comment]
That makes a lot of sense and I like it. Let's fix it.

**Comment by kraftbj** [comment]
Noting that with our new processes, this shouldn't impact a release. I doubt it would have before, but it really shouldn't now.

**Comment by jeherve** [comment]
This seems to be fixed. Closing.
