### ISSUE TITLE
Elaborate on what's included in Jump Start

### ISSUE THREAD

**Issue by crunnells** [Automattic/jetpack#12043]
Currently the Jump Start card doesn't elaborate on the Recommended Features (instead, it links to a support page on Jetpack.com). See screenshot:

<img width="1406" alt="0PXHgXx8F3-3000x3000" src="https://user-images.githubusercontent.com/4297811/56069278-02ddc080-5d1e-11e9-9c59-60f9228664ff.png">

Ideally we should inform our users about what we're doing before asking them to perform an action.

Proposed MVP for letting users know what features are activated:

![Screenshot_2019-04-12 Jetpack ‹ Allied Skylark — WordPress](https://user-images.githubusercontent.com/4297811/56069322-391b4000-5d1e-11e9-9349-19e9204f34bd.png)

The links in the paragraph go out to the appropriate JP.com support pages.

**Comment by MichaelArestad** [comment]
Some notes for the proposed mockup:

I don't think the linked items need to also be bold because the link color stands out already (dual purpose!)

Our skip/cancel buttons are usually to the left of (or above) the submit/continue buttons. In this case, I would make a borderless button that only says "Skip" and move it to the left of the primary button.

Copy suggestions:
"feature set" to "features"

Perhaps something like this:
> Next, activate Jetpack's recommended features to maximize your site's security and performance. The secure authentication and downtime monitoring features will immediately help secure your website and inform you if your site goes down. Image hosting, static file hosting, and lazy loading images are all features that will speed up the loading of your site.

Clearly we will need Editorial's help on this.

**Comment by crunnells** [comment]
I've updated the mockup with your feedback. PR coming soon.

**Comment by michelleweber** [comment]
I feel like linking to each thing individually is a bit overwhelming; I'd probably stick to a single "Learn more about these features" at the end of the para. Then I'd simplify just a smidge, to end up somewhere in between the original and the mockup above:

_Next, activate Jetpack's recommended features. We've picked the features most useful for maximizing your site's security and performance, like secure authentication, downtime monitoring, image hosting, and lazy loading image. Activate them all with a click, and they'll make sure your site is safe and speedy. Learn more about our recommended features._

**Comment by crunnells** [comment]
Updated copy, should be ready for review/merge.
