### ISSUE TITLE
Geo-location: improve display of xmlns:georss attribute

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#12051]
From #9885:

> I think the solution could be improved. Currently the generated tag looks like this for me:
```xml
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
	
xmlns:georss="http://www.georss.org/georss" xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#"
>
```
> 
> Which I find to be suboptimal. xmlns:slash and xmlns:georss are now only separated by new line. All others are separated by new line plus a tab.
In my special case, the rss reader compresses the file by stripping line breaks and replacing 1+n tabs by a space. Which would work well with a document generated by simple_xml entirely as you can be sure there will be tabs in front of every sub-node.
> 
> So to insert safely into the generated document, I suggest to add a tab char in front of xmlns:georss.

cc @jbjhjm

**Comment by Ael02** [comment]
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
	
xmlns:georss="http://www.georss.org/georss" xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#"
>
