### ISSUE TITLE
Publicize & Gutenberg

### ISSUE THREAD

**Issue by LWGShane** [Automattic/jetpack#12068]
Issue: In the Gutenberg Editor, the "Share this Post" tab in Jetpack options displays "Connect and select the accounts where you'd like to share your post". However, on WordPress.com, the .com editor successfully displays my connected accounts.

How to Reproduce: Connect social media accounts to Jetpack's Publicize interface, create a new post with the Gutenberg editor, and try viewing your connected sites. Now try viewing your connected sites in the WordPress.com editor.

**Comment by jeherve** [comment]
It seems like there could be some issues with your site's connection to WordPress.com.

Could you contact us via [this contact form](https://jetpack.com/contact-support/?rel=support) and give us more details about your site so we can take a closer look?

Thank you.
