### ISSUE TITLE
Carousel: Image title field does not display in if the title starts with uppercase "IMG"

### ISSUE THREAD

**Issue by tbradsha** [Automattic/jetpack#12067]
#### Steps to reproduce the issue

1. Create a Gallery that has an image with the title of "IMG [any other text here]" (make sure the IMG is uppercase.
2. View the gallery in a page or post, and the title won't appear.

**Screenshots**
Image with good title:
![Image](https://cld.wthms.co/yBAEl0+)

Gallery view:
![Image](https://cld.wthms.co/luZj5D+)

Image with "IMG" title:
![Image](https://cld.wthms.co/M9muA9+)

Gallery view:
![Image](https://cld.wthms.co/JiPZcM+)

**Comment by tbradsha** [comment]
Reported in 12133279-hc. Workarounds include using a prefix (e.g. "Title: IMG xxxx") or lowercase (e.g. "img_xxxx").

**Comment by scottsweb** [comment]
The code responsible for this can be found here: https://github.com/Automattic/jetpack/blob/master/modules/carousel/jetpack-carousel.js#L1281

**Comment by scottsweb** [comment]
A little more context here:

> this function is meant to prevent the generating of titles based on filenames that weren’t created by a human.

I do however have some concerns about the code myself. Based on the current set of exclusions for example, I cannot have a title called 'Scanning the mountains' or 'SAM & MATT' - both very plausible titles. 

I will open a PR to remove this code. I would favour not modifying the titles in this way as it creates very unexpected outcomes.

**Comment by tbradsha** [comment]
I figured it was something like that. In this case the user actually wanted the title of the specific filename to show. While I wouldn't do it myself, I don't see any reason why we should restrict the title from showing whatever they put in.
