### ISSUE TITLE
Facebook Likebox: Failed to load resource: net::ERR_CACHE_MISS

### ISSUE THREAD

**Issue by mayeenulislam** [Automattic/jetpack#1206]
![screenshot_1](https://cloud.githubusercontent.com/assets/4551598/4692364/68f1500a-575e-11e4-8a83-6aee2ec5562e.png)

Always is showing this error in here:
https://www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.faceboo…e&stream=false&show_border=true&header=false&force_wall=false&locale=bn_IN
- [Live site](http://www.innotech.com.bd/purbokone/)

I'm using no cacheing plugin on my site.

**Comment by tonytranupc** [comment]
I got the same issue like you but with Twitter, not Facebook. After digging on Google for solutions, I found this one, which may help you too.

It was helped me to fix [the ERR_CACHE_MISS error](https://usefulpcguide.com/17838/err_cache_miss/) on my Google Chrome. Give it a try!

P/S: Just disable the cache system of Google Chrome, everything will be fine.

**Comment by Jason383** [comment]
I Follow [How To Fix ERR_CACHE_MISS in Google Chrome](http://www.wiknix.com/how-to-fix-err_cache_miss-in-google-chrome/) instruction and problem solved with in minutes.
