### ISSUE TITLE
Calypsoify: Update color of border in plugins screen

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#12074]
#### Steps to reproduce the issue

1. Get any active plugin that needs updating (tweak version number manually if needed)
2. Go to the plugins screen when it's calypsoified (`/wp-admin/plugins.php?calypsoify=1`)
3. Observe the left border of the plugins table next to the plugin update notice

#### What I expected
I'd expect the border color to just be the same as the other active plugins/rest of the table.

#### What happened instead
It's using a different blue.

**Screenshots**
<img width="293" alt="Screen Shot 2019-04-17 at 8 46 23 AM" src="https://user-images.githubusercontent.com/108942/56297515-af88bb00-60ed-11e9-8728-4234b1ffef34.png">

**Comment by scottsweb** [comment]
Ran some tests on this PR and it hadn't updated the border colour for me:

![Screenshot 2019-04-26 at 12 40 22](https://user-images.githubusercontent.com/411945/56805309-8cae8300-6820-11e9-8e5a-c736e355e0a0.png)

Will push an additional selector that updates it to this:

![Screenshot 2019-04-26 at 12 40 36](https://user-images.githubusercontent.com/411945/56805330-9afc9f00-6820-11e9-9b44-6c5a887e46a8.png)
