### ISSUE TITLE
Portfolio Displays 'Random' Category Description in Archives

### ISSUE THREAD

**Issue by BinaryMoon** [Automattic/jetpack#12104]
1. Add portfolio items
2. Go to the portfolio archive
3. Look at the category description

#### What I expected
No description

#### What happened instead
A description of 'Portfolio Items' was displayed. This doesn't serve a purpose and is not editable in the admin (as far as I can see). The only way to edit is to filter the parameter.

**Screenshots**
You can see an example of it happening on my website.
https://www.binarymoon.co.uk/portfolio/

<img width="988" alt="Screenshot 2019-04-20 at 20 10 19" src="https://user-images.githubusercontent.com/1004130/56461305-5d26f300-63a8-11e9-8d71-545babfda8ba.png">

**Solution**
I can't see a need to use this for either site owners or site visitors so I would suggest removing the description when registering the post type. 

https://github.com/Automattic/jetpack/blob/f8078c2cd12ac508334da2fb08e37a92cf283c14/modules/custom-post-types/portfolios.php#L264

**Comment by jeherve** [comment]
> I would suggest removing the description when registering the post type.

That seems fair. I think it would be okay to remove it indeed.

**Comment by BinaryMoon** [comment]
Awesome. Should I make a pull request?

**Comment by jeherve** [comment]
I'd be happy to review one. Thank you! 🙇

**Comment by BinaryMoon** [comment]
Thanks - I've submitted it here: https://github.com/Automattic/jetpack/pull/12134
