### ISSUE TITLE
Tiled gallery block: alt and title fields blank on front end

### ISSUE THREAD

**Issue by KokkieH** [Automattic/jetpack#12109]
#### Steps to reproduce the issue

1. Create a post in the block editor
2. Add a tiled gallery block and add some images
3. Edit the images and add text in the title, description and alt fields
4. Publish the post, and then view the source code for any image in the gallery in the browser inspector.

#### What I expected
To be able to see the title, description and alt text if I view the source code for the image in the browser inspector.

#### What happened instead
The description text is there, but both alt and title are blank, showing only `"title":""` and `alt=""`

This happens with the Core gallery block as well, and found https://github.com/WordPress/gutenberg/issues/13164 which appears to be related, but I'm not completely sure. Also thought I'd make an issue here if it's something we're able to fix specifically for the Jetpack gallery block.

Reported in https://en.forums.wordpress.com/topic/alt-text-of-image-is-empty-in-developer-tools/ by an Atomic user, but was also able to replicate it on a self-hosted Jetpack site.

**Comment by jeherve** [comment]
This is an issue with how the block editor adds that data to images, vs. how it used to be done in the past. You can read more about it here:
https://github.com/WordPress/gutenberg/issues/12913

I am afraid there is not much that can be done about it in Jetpack. However, I see that the Accessibility label was added to the issue above a few days ago, so we may see some movement about this in Core soon.

**Comment by KokkieH** [comment]
Thanks. I prepared the user that this might have to be fixed in Core, so I'll let them know.

Thanks for pointing me to the correct GB issue!
