### ISSUE TITLE
Admin page: Plans shows nothing on Dev Mode

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#12119]
<img width="1074" alt="Captura de Pantalla 2019-04-22 a la(s) 18 17 16" src="https://user-images.githubusercontent.com/1041600/56531905-3218dc80-652b-11e9-80df-fec215214f6b.png">

This is how Plans looks like when the site is in Development Mode. Maybe we should hide this tab? Show some content explaining the situation like we do in My Plan?

**Comment by eliorivero** [comment]
@MichaelArestad @crunnells thoughts about this?

**Comment by MichaelArestad** [comment]
Hiding the tab in dev mode works for me.
