### ISSUE TITLE
Jetpack Onboarding Emails: Paid Plan

### ISSUE THREAD

**Issue by crunnells** [Automattic/jetpack#12111]
Update the post-connection confirmation email to focus on security and performance.

#### Proposal:
--------------------------

# [SITE NAME] is all powered up.

Congratulations on your purchase!

You now have the most powerful set of tools at your disposal to really secure and speed up your site. Right out of the box, you get secure authentication, downtime monitoring, and protection against brute force attacks. Also, your site can load pages faster by serving your images and static files from our global network of servers. Shorter load times can lead to happier readers, more page views, and — if you’re running a store — improved sales.

And with your <PLAN LEVEL> plan, you’re getting automated backups and one-click restoration of your site. Never worry about losing your site data in the event of a hack, malware, or a server crash -- now, peace of mind is always a click away.

<a href="#">Explore your plan</a>

#### Additional Context

p1HpG7-6Sq

**Comment by eliorivero** [comment]
Patch is up for review at D27449-code

**Comment by MichaelArestad** [comment]
Done!
