### ISSUE TITLE
Jetpack Onboarding Emails: Free Plan

### ISSUE THREAD

**Issue by crunnells** [Automattic/jetpack#12110]
Update the post-connection confirmation email to focus on security and performance.

#### Proposal

-------------------------------------

# Welcome to your safer, speedier site!

You now have a solid array of tools to secure and speed up your site. Right out of the box, Jetpack adds secure authentication, downtime monitoring, and protection against brute force attacks. And your site can load pages faster by serving your images and static files from our global network of servers! Shorter load times mean happier readers, more page views, and — if you’re running a store — improved sales.

Jetpack can do even more to keep your site safe and sound. Jetpack’s Personal and Premium plans include automated backups and one-click restoration of your site, or go Professional to keep your site backed up in real-time. Never worry about losing your site data in the event of a hack, malware, or a server crash. All that, plus automated malware scanning and automatic security fixes -- complete peace of mind is just a click away.

[Upgrade Jetpack »](https://jetpack.com/pricing/)

-------------------------------------

#### Additional Context

p1HpG7-6Sq

**Comment by kraftbj** [comment]
Removing the `Needs Review` status since we use that for when there's code to review. Thanks!

**Comment by eliorivero** [comment]
Patch is up for review at D27449-code

**Comment by MichaelArestad** [comment]
Done!
