### ISSUE TITLE
Suppress site accelerator JITM for initial login, and if still applicable, fix duplicate instance of it

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#12129]
<img width="1106" alt="05 jitm" src="https://user-images.githubusercontent.com/426388/56591003-4d95ed00-65e8-11e9-935b-c5ebc5afa7f7.png">

**Comment by jeherve** [comment]
Related: #10752

**Comment by eliorivero** [comment]
In progress in D27288-code
