### ISSUE TITLE
Privacy checkbox in Blog Subscriptions widget

### ISSUE THREAD

**Issue by AiratHalitov** [Automattic/jetpack#12120]
#### Is your feature request related to a problem? Please describe.

In Russia we have a Federal Law №154 "About Personal Data" (154 ФЗ "О персональных данных"), which says that all contact and subscription forms should have a checkbox with agreement with Privacy Policy. It should be looks like checkbox with a text “Yes, I agree with your **Privacy Policy**“, where phrase “Privacy Policy” is a link to real Privacy Policy on website.

#### Describe the solution you'd like

Can you add privacy checkbox to **Blog Subscriptions** widget, please?
The text can be customizable and translated to different languages with using GlotPress (or plugin settings). Link to Privacy Policy page you can use from WordPress settings (page `/wp-admin/privacy.php` in admin dashboard) or it can be also customizable in JetPack settings. 

#### Additional context

- Jetpack 7.2.1
- WordPress 5.1.1

Related: https://wordpress.org/support/topic/privacy-checkbox-in-blog-subscriptions-widget/

**Comment by jeherve** [comment]
We are not planning on adding such a checkbox to the Subscriptions form right now, for the reasons James mentioned on the thread above, but you could still add a checkbox on your site manually with some JavaScript, like so:

```js
// Find the Subscription form.
const jetpackSubscription = document.querySelector( '.jetpack_subscription_widget' );

// Find the Submit button that we will modify.
let jetpackSubscriptionSubmit = jetpackSubscription.querySelector( '#subscribe-submit' );

// Create a checkbox element.
let subsPrivacyLinkCheckbox = document.createElement('input');
subsPrivacyLinkCheckbox.type = 'checkbox';
subsPrivacyLinkCheckbox.value = 1;
subsPrivacyLinkCheckbox.checked = true;
subsPrivacyLinkCheckbox.name = 'Agree to our Privacy Policy';

// Add that element to the submit button.
jetpackSubscriptionSubmit.appendChild(subsPrivacyLinkCheckbox);

// Add some text after the checkbox.
subsPrivacyLinkCheckbox.outerHTML = `${ subsPrivacyLinkCheckbox.outerHTML } Agree to our privacy policy`;
```

Another approach would be to remove the Subscriptions widget from your sidebar, and instead create a Susbcription page where you will insert the Subscription block:
https://jetpack.com/support/jetpack-blocks/subscription-form-block/

This will allow you to add some custom text before the form if needed.

I hope this helps.

**Comment by AiratHalitov** [comment]
Thanks! 
And how can I add the Privacy checkbox into Subscription block?

**Comment by jeherve** [comment]
> how can I add the Privacy checkbox into Subscription block?

You would add it before or after the block, in another block.
