### ISSUE TITLE
Publicize: portfolio projects don't display publicize connections during the pre-publish check

### ISSUE THREAD

**Issue by cecoates** [Automattic/jetpack#12147]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/block-editor/edit/jetpack-portfolio/ on a Simple Site.
2. Create a new project.
3. Click Publish.
4. The pre-publish menu slides out, but the "Share this post" options are empty.

#### What I expected

To see checkboxes to enable/disable publishing to social media connected via Publicize.

#### What happened instead

Area is empty, as if there are no connections on the site.

#### Browser / OS version
Chrome Version 73.0.3683.86 (Official Build) (64-bit)

Pop!_OS 18.10

#### Screenshot / Video

Pre-publish check in Block Editor for a portfolio project.

![Screen Shot on 2019-04-24 at 12_36_58](https://user-images.githubusercontent.com/10121835/56685474-a5d7f800-6697-11e9-8272-f24a79455091.png)

Pre-publish check in Block editor for a post, same site:
![Screen Shot on 2019-04-24 at 12_38_45](https://user-images.githubusercontent.com/10121835/56685505-ba1bf500-6697-11e9-87ac-e4bd7eeb96a3.png)

Sharing settings when Block Editor is disabled:

![Screen Shot on 2019-04-24 at 13_22_08](https://user-images.githubusercontent.com/10121835/56685755-475f4980-6698-11e9-8e87-31bed9ac506f.png)

#### Context / Source

12319475-hc

Does not seem to affect Atomic or Jetpack sites.

**Comment by simison** [comment]
Portfolio projects have `supports.publicize=true` which causes this panel to be visible. This info is available via:
```
https://public-api.wordpress.com/wp/v2/sites/[SITE_ID]/types/post
https://public-api.wordpress.com/wp/v2/sites/[SITE_ID]/types/jetpack-portfolio
```

Or you can throw this in the console for editor page and check returned `supports` arrays:
```js
wp.data.select( 'core' ).getPostType( 'post' );
wp.data.select( 'core' ).getPostType( 'jetpack-portfolio' );
wp.data.select( 'core' ).getPostType( 'jetpack-testimonial' ); // no publicize support so no panel rendered
```

When the panel is rendered, [it fetches a list of connections](https://github.com/Automattic/jetpack/blob/d37ed70e58a9cc0987e3204c03e8c9e6ffe3c28d/extensions/blocks/publicize/panel.js#L46) from post attributes but for the portfolio it doesn't receive them.

You can test by throwing this to console when editing a post and a portfolio project:

```
wp.data.select( 'core/editor' ).getEditedPostAttribute( 'jetpack_publicize_connections' )
```

Post attributes are available via these API endpoints:
```
https://public-api.wordpress.com/wp/v2/sites/SITE_ID/jetpack-portfolio/POST_ID
https://public-api.wordpress.com/wp/v2/sites/SITE_ID/posts/POST_ID
```

...but `jetpack_publicize_connections` is missing for `jetpack-portfolio`. This leads to something being off in [`WPCOM_REST_API_V2_Post_Publicize_Connections_Field`](https://github.com/Automattic/jetpack/blob/09b077ba6c39b3904cb080693edc0d1afe8438d6/_inc/lib/core-api/wpcom-fields/post-fields-publicize-connections.php) or wpcom equivalent of it?

**Comment by simison** [comment]
Oh and there's no need to go to "prepublish" step. It's enough to open editor for each post type in simple site's wp-admin and open the Jetpack sidebar:

| *Portfolio* | *Post* |
|-----------|------|
| <img width="310" alt="image" src="https://user-images.githubusercontent.com/87168/56691890-a6997a00-66e9-11e9-9727-984b13a0eac5.png"> | <img width="288" alt="image" src="https://user-images.githubusercontent.com/87168/56692139-2de6ed80-66ea-11e9-8351-5acb0fade0bb.png">|

**Comment by codebykat** [comment]
Okay so notably... when there actually are no connections, there's a link to the settings:

<img width="281" alt="Screen Shot 2019-04-24 at 2 59 45 PM" src="https://user-images.githubusercontent.com/52152/56696760-a4abc880-66a1-11e9-96bb-989a238e6199.png">

That's on Jetpack. On WPCOM simple sites we just get this (no connections, also no link):
  
<img width="319" alt="Screen Shot 2019-04-24 at 2 52 34 PM" src="https://user-images.githubusercontent.com/52152/56696780-aecdc700-66a1-11e9-99ee-02080152ef48.png">

**Comment by codebykat** [comment]
Okay so looking at https://github.com/Automattic/jetpack/blob/09b077ba6c39b3904cb080693edc0d1afe8438d6/_inc/lib/core-api/wpcom-fields/post-fields-publicize-connections.php#L36

I was very suspicious of the `$this->object_type = get_post_types_by_support( 'publicize' );` in the `register_fields()` call but changing it to `get_post_types()` (so all post types are returned) does not fix the issue. Interestingly that only seems to be getting hooked into `post` types (even on Jetpack, where it is working as intended). I'm guessing things might be getting hooked in out of order.

**Comment by codebykat** [comment]
Aha so changing `	add_action( 'rest_api_init', array( $this, 'register_fields' ) );` in `class-wpcom-rest-field-controller.php`

to `add_action( 'restapi_theme_init', array( $this, 'register_fields' ), 20 );` (hook later) fixes the issue... because the Portfolio CPT is hooked to `restapi_theme_init` to register..

**Comment by codebykat** [comment]
See also https://github.com/Automattic/jetpack/pull/12031/files basically same issue and same ugly fix :/

**Comment by codebykat** [comment]
PR to fix this up for review here https://github.com/Automattic/jetpack/pull/12152
