### ISSUE TITLE
Tiled Gallery: Images becoming distorted in carousel

### ISSUE THREAD

**Issue by xpurichan** [Automattic/jetpack#12200]
We can setup similar galleries using the Tiled Gallery and Gallery blocks. Once created these galleries both look fine on the page. However, when we click on one image and have the carousel option enabled (which loads the images in to a full-screen carousel/slideshow) the images look very distorted when using the Jetpack Tiled Gallery block instead of the basic Gallery Block.

Here is an image from the Tiled Gallery block when we view it in a carousel:
![Screen Shot 2019-04-29 at 5 39 24 PM](https://user-images.githubusercontent.com/33190975/56931508-dbb91a00-6aa5-11e9-8e0b-a591b58d35b1.jpg)

Here is the same image from a Gallery block in a carousel:
![Screen Shot 2019-04-29 at 5 39 37 PM](https://user-images.githubusercontent.com/33190975/56931513-e2e02800-6aa5-11e9-9220-eb4160f78615.jpg)

Both the initial report and the test above were performed on WordPress.com simple sites with the Premium plan.

#### Steps to reproduce the issue

1. Enable Gutenberg
2. Create a post/page and add the Tiled Gallery (Jetpack) block, add multiple images to the block
3. Once the block is created then you can edit the settings of the block. For the column option any number of columns can be used. For the "Link to:" option please choose **None**.
4. Save your changes and publish the page.
5. Visit https://DOMAIN.COM/wp-admin/options-media.php and ensure that the "Display images in full-size carousel slideshow" option is checked.
6. Visit your new gallery page and click on an image in the gallery to open the carousel, notice that the image becomes stretched.
7. Optionally compare this to how your images look in a normal Gallery block when viewed in the carousel

#### What I expected
The gallery images in the Tiled Gallery block should maintain their aspect ratio when viewed in carousel, just like they do with the Gallery block carousel.

#### What happened instead
Images are distorted in the carousel when using a Tiled Gallery block.

Issue was reported on 1996611-zen. 

The problem was replicated on my test site: https://lillytest123456.blog/gallery-test/
(This above page is my testing page which still has both galleries setup.)

**Comment by simison** [comment]
Thanks for a great report! I'll close this since we have https://github.com/Automattic/jetpack/issues/11150 already.
