### ISSUE TITLE
Jetpack Manage Notice Cannot be Dismissed

### ISSUE THREAD

**Issue by macmanx2** [Automattic/jetpack#12232]
Now that Jetpack Manage can no longer be selectively switched on/off, the notice for activating it can not be dismissed on sites that have kept it off:

![MvwXUuZ](https://user-images.githubusercontent.com/4856235/57037053-f0fb8900-6c0a-11e9-91ff-d9fd376912bb.png)

The notice should either be dismissable, or made more clear that activating Manage is now a requirement.

Reported at https://wordpress.org/support/topic/jetpack-centralised-site-management-remove-message/

**Comment by jeherve** [comment]
This should be fixed in Jetpack 7.3, as per #9089.
