### ISSUE TITLE
Update screenshot captions to match screenshots

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#12230]
On the plugin page on the plugin repo, the captions don't match the images. We should update them to match. We might also update the screenshot to focus on security and performance. TBD

**Comment by kraftbj** [comment]
https://wordpress.org/plugins/jetpack/#screenshots

Example:
![2019-05-01 at 14 49](https://user-images.githubusercontent.com/88897/57038761-55751300-6c20-11e9-87fd-11d18eedf76e.jpg)

**Comment by MichaelArestad** [comment]
Done!
