### ISSUE TITLE
Publicize: Connecting to a Tumblr account using emojis breaks JP connection

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#1224]
If you have a Tumblr blog with an emoji character in the title (which Tumblr seems to allow), when you try to connect that blog to your Jetpack site, things go haywire.

After you "connect", you see this:

![screen shot 2014-10-28 at 10 54 36 am](https://cloud.githubusercontent.com/assets/5512652/4810324/813de55a-5eb2-11e4-988d-621ce447fb1f.png)

And then once you click OK:

![screen shot 2014-10-28 at 10 54 45 am](https://cloud.githubusercontent.com/assets/5512652/4810328/87420922-5eb2-11e4-95ce-611965d6be75.png)

The only way to fix it is to attempt to "reconnect" JP (even though you were never disconnected).

**Comment by jkudish** [comment]
This should no longer be an issue with the latest versions of WordPress core.
