### ISSUE TITLE
Show details in media library

### ISSUE THREAD

**Issue by LtCmdrKeene** [Automattic/jetpack#12257]
#### Is your feature request related to a problem? Please describe.

I'm frustrated when I'm looking for a specific media file (video for example) and the media library only shows thumbnails without filenames or dates or other info that might help me find the correct file.

#### Describe the solution you'd like

I'd love a "details" view in the Media library that shows a couple columns like Filename, Upload Date, Uploaded by person name, etc.

**Comment by jeherve** [comment]
The Jetpack plugin itself does not make any changes to the general view of the Media Library; this is handled by WordPress itself. 

If you would like to make suggestions on how to improve that screen for all WordPress site owners, I would recommend that you open a trac ticket here:
https://core.trac.wordpress.org/newticket

You can learn more about how to contribute to the WordPress bug tracker here:
https://make.wordpress.org/core/handbook/testing/reporting-bugs/

I hope this clarifies things a bit.
