### ISSUE TITLE
Contact form block: Review use of incorrect __ 

### ISSUE THREAD

**Issue by sirreal** [Automattic/jetpack#12260]
See https://github.com/Automattic/wp-calypso/pull/29058

Some context translations incorrectly use `__` (should be `_x`).

https://github.com/Automattic/jetpack/blob/a2cb10408593230c9f0359551a4181562758445a/extensions/blocks/contact-form/index.js#L313

_Originally posted by @sirreal in https://github.com/Automattic/wp-calypso/pull/29058#issuecomment-489133197_

**Comment by jeherve** [comment]
This has now been fixed.
