### ISSUE TITLE
Soundcloud Shortcode: Colour Parameter Broken

### ISSUE THREAD

**Issue by torres126** [Automattic/jetpack#12265]
#### Steps to reproduce the issue

1. Go to https://en.support.wordpress.com/soundcloud-audio-player/#customizing-shortcode
2. Notice how the text above states that the colour should be green, it's orange
3. Try following these steps on your own site, and note that the colour still won't work.

#### What I expected
The colour parameter to update the colour of the Soundcloud embed. 

#### What happened instead

It always remains orange. In the example below, I tried to make it pink.

<img width="316" alt="Screenshot 2019-05-03 at 21 29 02" src="https://user-images.githubusercontent.com/43215253/57163962-8143f480-6dea-11e9-9d60-b39fcc6ad672.png">

**Comment by jeherve** [comment]
Thanks for the report. This will be fixed in #12221.
