### ISSUE TITLE
RSS feeds broken

### ISSUE THREAD

**Issue by R1Law** [Automattic/jetpack#12280]
#### Steps to reproduce the issue

1. Email client cannot see sites RSS feed
2. This behavior happened after installing Jetpack
3.

#### What I expected
I expected functionality to keep working
#### What happened instead
My feeds are down.

**Comment by jeherve** [comment]
I unfortunately can't seem to reproduce on my end right now.

Could you contact us via [this contact form](https://jetpack.com/contact-support/?rel=support) and give us more details about your site there, so we can investigate with you and try to understand what is happening on your site, and if the Jetpack plugin may be conflicting with another plugin on your site right now.

Thank you.
