### ISSUE TITLE
Widget visibility: Button doesn't work when admin screen loads with no widgets

### ISSUE THREAD

**Issue by scottnelle** [Automattic/jetpack#12302]
When widget visibility is enabled and widgets are added to a completely empty Appearance > Widgets screen, the Visibility button doesn't work, instead the browser behaves as if you've clicked a link with `href="#"`. Once the page has been reloaded with at least one widget present, the Visibility button does to work. I suspect that the click event for the visibility button/link is not added to a new widget unless at least one widget is already present on DOM ready or on page load.

#### Steps to reproduce the issue

1. Go to Appearance > Widgets
2. If any widgets are present in any of the defined sidebars, delete them and then refresh the page.
3. Add any widget to any sidebar.
4. In the new widget, click the "Visibility" link.

#### What I expected
The visibility settings form is added to the widget, allowing me to adjust visibility settings.

#### What happened instead
A hash (`#`) is appended to the URL and the browser scrolls to the top of the page. No visibility settings form appears.

**Screenshots**

**Comment by codestor4** [comment]
I tested this and I confirm this is indeed an issue. I tried some fixes but failed. Would love to work on this if I get some initial direction from developers.

**Steps to reproduce:**
1. Go to the widgets page, remove all widgets from the widget area and refresh the page (imp step).
2. Add a widget, hit visibility button, it doesn't work
3. Refresh the page, hit visibility button, it works!

There's "something" that happens during "refresh" that helps the button to work. If we could replicate that "something" right when a widget gets added to the widget area or when a widget gets auto-saved, we could potentially fix this.

**Comment by jeherve** [comment]
> There's "something" that happens during "refresh" that helps the button to work.

Do you experience similar issues under Appearance > Customize > Widgets?

**Comment by codestor4** [comment]
> Do you experience similar issues under Appearance > Customize > Widgets?

Nope. It works fine in the customizer.

_disappears and continues troubleshooting based on this new information_

**Comment by chickenn00dle** [comment]
I was curious about this one, so dug in and found the issue is related to how widget-visibility checks if we are in the customizer or widgets.php. When no widgets are selected, the script thinks we are in the customizer. 

So the script doesn't actually run on newly added widgets until the page is reloaded after a widget is added.

Applied a potential fix in #13858
