### ISSUE TITLE
Block Editor: Plugins are not registered (`missing_module`).

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#12300]
Loading the block editor, I see the following warnings in the console: "Plugin ... couldn't be registered because it is unavailable (missing_module)."

<img width="1117" alt="Screen Shot 2019-05-08 at 9 03 18 AM" src="https://user-images.githubusercontent.com/349751/57390167-90230200-7170-11e9-91de-1fccad517cf0.png">

**Comment by jeherve** [comment]
This happens when a module is not enabled. If you go to Jetpack > Settings and enable each module the warnings should disappear.

Can you give it a try?

**Comment by kwight** [comment]
Oh! Looks like you're right – I just never noticed them before today, apparently.
