### ISSUE TITLE
`can_display_jetpack_manage_notice` incorrectly deprecated by `jetpack_json_manage_api_enabled`

### ISSUE THREAD

**Issue by iandunn** [Automattic/jetpack#12303]
#### Steps to reproduce the issue

1. Enable `WP_DEBUG`
1. Add this to an mu-plugin:

```php
add_filter( 'can_display_jetpack_manage_notice', '__return_false' );
```

3. Open `wp-admin` in browser

#### What I expected

Jetpack Manage notices should be disabled.

#### What happened instead

Error:

```

( ! ) Notice: can_display_jetpack_manage_notice used for an anonymous function is <strong>deprecated</strong> since version ! Use jetpack_json_manage_api_enabled instead. in public_html/mu/wp-includes/functions.php on line 4435
Call Stack
#	Time	Memory	Function	Location
1	0.0001	395584	{main}( )	.../index.php:0
2	0.0001	395968	require_once( 'public_html/mu/wp-admin/network/admin.php' )	.../index.php:11
3	0.0001	396672	require_once( 'public_html/mu/wp-admin/admin.php' )	.../admin.php:13
4	0.0001	397088	require_once( 'public_html/mu/wp-load.php' )	.../admin.php:34
5	0.0001	397912	require_once( 'public_html/wp-config.php' )	.../wp-load.php:42
6	0.0002	401584	require_once( 'public_html/mu/wp-settings.php' )	.../wp-config.php:160
7	0.0802	6379328	do_action( )	.../wp-settings.php:525
8	0.0802	6379704	WP_Hook->do_action( )	.../plugin.php:465
9	0.0802	6379704	WP_Hook->apply_filters( )	.../class-wp-hook.php:310
10	0.2706	7479096	Jetpack->deprecated_hooks( )	.../class-wp-hook.php:286
11	0.2707	7479304	_deprecated_function( )	.../class.jetpack.php:6400
12	0.2707	7479624	trigger_error ( )	.../functions.php:4435
```

Also, I'm guessing that Manage notices are no longer disabled? Or maybe they don't exist anymore, which is why that filter was set to `null` in b31fb6655f19d9846909bb2e808e0fb9719fc59d?

@oskosk, did you intend to deprecate `can_display_jetpack_manage_notice` in 9f63a6dd0f62b8b07681d00d5ea44b822e145c17, or did you copy/paste the above line and forget to change it to something new?

Adding it overwrote the previous line, and `jetpack_json_manage_api_enabled` doesn't seem related to `can_display_jetpack_manage_notice` at all.

**Comment by iandunn** [comment]
Related: #12232

**Comment by iandunn** [comment]
Oh, I think I see. The notice was removed, because the notice was just asking people to enable the module, but now the module is baked-in to core Jetpack, so it's always on? And `jetpack_json_manage_api_enabled` was chosen to deprecate `can_display_jetpack_manage_notice` because disabling `jetpack_json_manage_api_enabled` would disable all Manage functionality?

In that case, the only problem is the duplicate array key. I would suggest the following change, because I don't think that `jetpack_json_manage_api_enabled` is a logical replacement for `can_display_jetpack_manage_notice`. `null` makes more sense, because there's no notice to disable anymore.

```diff
'can_display_jetpack_manage_notice'                      => null,
- 'can_display_jetpack_manage_notice'                      => 'jetpack_json_manage_api_enabled',
```

**Comment by jeherve** [comment]
Nice catch!

I think the duplicate key comes from a bad rebase, it definitely should not be there.

I'd be okay with setting the replacement as `null` instead of `jetpack_json_manage_api_enabled`, since the 2 filters don't really do the same thing.

PR incoming.

**Comment by iandunn** [comment]
Thanks!

**Comment by myBRAIN-isOPEN** [comment]
Hi,

The developer of UpdraftPlus (David Anderson) has stated that there is still an issue with the display of this notice. 

May 29, 2019 at 8:11 am
Looking again at https://github.com/Automattic/jetpack/issues/12303, it says that they *did* update it in JetPack 7.3.1, which they released two weeks ago; please check that you have updated. (If not, you should re-open that issue).
David

Full details here:
https://updraftplus.com/forums/topic/jetpack-incompatibility/#post-393428

I would appreciate if someone could review this.

Many thanks

Thomas

**Comment by DavidAnderson684** [comment]
> The developer of UpdraftPlus (David Anderson) has stated that there is still an issue with the display of this notice.

I have not personally experienced this issue. I posted on that thread that if you are experiencing it, and are running JetPack 7.3.1, then you should report it here, as it is a notice emitted by JetPack that they believe is already fixed in that release.

**Comment by DavidAnderson684** [comment]
Actually - apologies... I've misinterpreted this issue. Please ignore. Thomas, I will reply back on the forum.

**Comment by tmmbecker** [comment]
2722402-zen reports that they're seeing this message after updating to 8.2.3. Can someone take a look? Thanks.

**Comment by jeherve** [comment]
@tmmbecker Do you think you could ask them to search for usage of the `can_display_jetpack_manage_notice` filter on their codebase, and remove it? The filter is not useful anymore.
