### ISSUE TITLE
Save CSS editor changes in the background instead of reloading the page

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#1231]
Right now when you save changes in the CSS editor, the page reloads and you lose your place in the file. It would be great if the save could be done in the background much like drafts are saved while you're writing posts so that you don't have to lose your place each time you save a change.

**Comment by jeherve** [comment]
#1621

**Comment by jeherve** [comment]
#5539

**Comment by jeherve** [comment]
Closing as this will be addressed in #5527
