### ISSUE TITLE
Site Health: The WP.com endpoint can 404

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#12325]
<img width="823" alt="captura_de_pantalla_2019-05-08_a_la_s__22 55 03" src="https://user-images.githubusercontent.com/88897/57460318-7e0d9600-723a-11e9-8fdf-8ef92d0b4d51.png">

This is the `test__wpcom_connection_test` failing to get a response (a 404) from the WP.com endpoint. My guess is this check:
```
		if ( ! Jetpack::is_active() || Jetpack::is_development_mode() || Jetpack::is_staging_site() || ! $this->pass ) {
			return self::skipped_test( $name );
		}
```
isn't stopping the test, perhaps the `!$this->pass` with the decoupling of the tests for the Site Health section. I believe investigating on a never-connected site would be the first thing to try.

#### Steps to reproduce the issue

1. Unsure right now.

#### What I expected
No PHP errors and results from the Site Health are all complete.

#### What happened instead
See screenshot.

**Comment by eliorivero** [comment]
I experienced this in a local site using the Docker dev environment provided by Jetpack and online through ngrok.

**Comment by kraftbj** [comment]
I couldn't figure out a way to duplicate it, but @eliorivero can you give 12328 a go? It should provide the error handling to gracefully fail and provide a more useful message.
