### ISSUE TITLE
Masterbar: handle Hamburger menu when in block editor on mobile

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#12320]
#### Steps to reproduce the issue

1. Activate the WordPress.com toolbar feature.
2. On mobile, go to Posts > Add New
3. You'll see the hamburger getting in the way of content:

![image](https://user-images.githubusercontent.com/426388/57451783-84176d00-7262-11e9-88e0-54d2b2d0f093.png)

**Comment by simison** [comment]
Something funky going on here with block editor sidebar open: 
<img width="327" alt="image" src="https://user-images.githubusercontent.com/87168/57452475-8979b500-726c-11e9-8c95-52e27b0c9f8b.png">

**Comment by jeherve** [comment]
For reference, here is how the Core toolbar handles it:

![image](https://user-images.githubusercontent.com/426388/57452721-d063ac80-7264-11e9-959f-d5b4ccc7c09d.png)

**Comment by jeherve** [comment]
Reopening, as this is happening again right now (see https://github.com/Automattic/wp-calypso/issues/40426 )

**Comment by sirreal** [comment]
Brought this up in some masterbar-related discussions: pbAPfg-3G-p2#comment-988

**Comment by lakellie** [comment]
Noting here we have a user in #2806214-zen who should be followed up with if/when this is resolved.

**Comment by jeherve** [comment]
I have not tested this myself, but this should now be fixed as of https://github.com/Automattic/wp-calypso/issues/40426#issuecomment-648045204
