### ISSUE TITLE
YouTube shortcode: span classes causes responsive issue in Gutenberg

### ISSUE THREAD

**Issue by AertHulsebos** [Automattic/jetpack#12322]
#### Steps to reproduce the issue

1. Install Block editor / Gutenberg
2. Add embedded YouTube video
3. Gutenberg responsive properties and span class from Jetpack cause issue when trying to block before consent. For themes and plugins alike. Noticed when we tried to add a placeholder before consent.

#### What I expected

Respecting Gutenberg as new standard. Dropping responsive video addition from Jetpack

#### What happened instead

The opposite

**Comment by jeherve** [comment]
The `span` added by Jetpack is mostly used to respect the alignment settings you can pass as a shortcode parameter with the `align` parameter. It can consequently be useful regardless of the editor used.
One potential improvement we could make, however, would be to only add the span when the shortcode parameter is provided.

Could you tell us more about how the span blocks you from adding a placeholder?

Thanks!

**Comment by AertHulsebos** [comment]
Hi @jeherve, has there been an update?

We wanted to show you with a sandbox, but it seems to be resolved, somehow.

Regards Aert

**Comment by jeherve** [comment]
No, we have made no changes on our end.

Glad to hear you could figure it out then 👍

**Comment by AertHulsebos** [comment]
No changes at our end either. Well.. There we go.

**Comment by AertHulsebos** [comment]
Hi Jeremy,

The issue reappeared. Can we continue in this thread? http://defeated-kea.w6.wpsandbox.pro/blunders/ you can see the issue.

**Comment by jeherve** [comment]
I can see the `<span class="embed-youtube"` before the videos, as is expected for YouTube embeds with Jetpack:
https://github.com/Automattic/jetpack/blob/1cd9bc55b845a4efc8d45d3a1ba144e4d0619ec3/modules/shortcodes/youtube.php#L347

Could you tell me more about the issues this introduces on your end? I was able to play the videos on your site just now.

**Comment by AertHulsebos** [comment]
Hi @jeherve,

http://plugin.complianz.io/ we set up a dedicated site for this issue.

As you can see the video, with our placeholder and Jetpack span class, the video moves down quite a bit. With Jetpack off, responsiveness and the placeholder are intact.

If you need access to the back-end or FTP let me know.

**Comment by jeherve** [comment]
I see what you mean now, thank you. 

You should be able to use the `video_embed_html` filter (see https://github.com/Automattic/jetpack/blob/1cd9bc55b845a4efc8d45d3a1ba144e4d0619ec3/modules/shortcodes/youtube.php#L354 ) to remove the wrapper from all videos at once. If you use the filter in your plugin, the layout issue will be solved as soon as site owners enable your plugin, while not breaking the layout for sites that do not use your plugin.

Let me know how that goes.

**Comment by AertHulsebos** [comment]
Hi @jeherve,

This looks like we have to parse HTML and remove the span class when necessary. I'm just curious why, when Gutenberg enabled, this span class still is enforced.

My opinion, if Gutenberg is the default lay-out builder, any video output controlled by another plugin/theme should built upon Gutenberg's default functionalities. Less is more in all cases.

Let me know. Thanks as always.

**Comment by jeherve** [comment]
Unfortunately we cannot assume that Gutenberg is enabled; Jetpack remains compatible with sites that use the Classic Editor, for example. We can't check if that plugin is active either, since one may use different plugins to manage what editor they use on their site, or may use the classic editor for some post types and the block editor for others.
