### ISSUE TITLE
Mp3 hosting

### ISSUE THREAD

**Issue by devagar** [Automattic/jetpack#12334]
Greetings, 

Since, Jetpack can handle, hosting of photos and videos, why not to also allow mp3 to be loaded. Those of us who podcast would be immensely 
grateful instead of hosting outside of our blogs. 

Regards.

**Comment by jeherve** [comment]
Thanks for the feedback. I'll close your issue as this suggestion is already tracked in #10125

**Comment by MrRedBeard** [comment]
That one got closed too so can we reopen one of them?
