### ISSUE TITLE
My plan checklist: Analytics

### ISSUE THREAD

**Issue by sirreal** [Automattic/jetpack#12335]
You'll probably need to add onClick tracking here:

https://github.com/Automattic/jetpack/blob/21108a1084b6d8b68bcb5a466fa9daa7d671934a/_inc/client/my-plan/checklist-progress-card/index.js#L36

_Originally posted by @jeherve in https://github.com/Automattic/jetpack/pull/12277_

**Comment by simison** [comment]
I take that this is already handled and we can close?

https://github.com/Automattic/jetpack/blob/7fadb8ad3953ef4456d30a795b12bf68710a3ccb/_inc/client/my-plan/my-plan-header/index.js#L27-L35

**Comment by sirreal** [comment]
Good to close, thanks. This issue was for the following, which includes analytics:

https://github.com/Automattic/jetpack/blob/d427df53c7a974e64e2a4a3f3dee54c05c5256e8/_inc/client/my-plan/my-plan-header/checklist-progress-card/index.js#L49-L58
