### ISSUE TITLE
Lazy Load: Prevents Images from showing in Elementor Pro Popups

### ISSUE THREAD

**Issue by azollafox** [Automattic/jetpack#12344]
#### Steps to reproduce the issue

1. Install Activate Elementor Pro. Make sure Jetpack Lazy Load images is going. 
2. Head to `Templates`>`Popups` and publish a pop up with an image
3. Take a look at your pop up on the live site. Images will be missing
4. Turn off Lazy Load. Your image will be back in the pop up upon refresh.

#### What I expected
I expected images to work on my site when lazy load was enabled

#### What happened instead
Lazy load prevents images from showing in an Elementor popup.

**Screenshots**
Turning Lazy Load on

![lazy load](https://cld.wthms.co/Lu8iuN+)

(Image link: https://cld.wthms.co/Lu8iuN )

Issue reported in 2023176-zen. 
For testing you can find our license for Elementor Pro in the Secret Store

**Comment by gsmumbo** [comment]
User provided clarification that the problem exists in two locations:

1) Popups in Elementor pro 
2) Using Astra Theme when placing an image in the right sidebar

**Comment by ntpixels** [comment]
Following up here as the ticket has re-opened after the traditional hold. Is there any new information we can provide to the user?

**Comment by jeherve** [comment]
@ntpixels No, there has been no progress on this issue yet. I'm afraid I can only recommend turning off the feature for now, until an update is posted on this issue.
