### ISSUE TITLE
VideoPress: Revisit block extension behavior

### ISSUE THREAD

**Issue by mmtr** [Automattic/jetpack#12358]
Currently, the VideoPress extension for the block editor extends the `core/video` block in order to use the VideoPress player in both the [editor](https://github.com/Automattic/jetpack/blob/66fdea2069b7dca13992a64512fdc3a68f727b72/extensions/blocks/videopress/edit.js) and the [published](https://github.com/Automattic/jetpack/blob/66fdea2069b7dca13992a64512fdc3a68f727b72/extensions/blocks/videopress/save.js) view if the video has been transcoded by VideoPress. 

Since we're saving a different block output into the post content from whats `core/video` saves, we could lead to failures when the block markup is validated:
- When Jetpack is deactivated.
- On environments that can edit existing posts but where the Jetpack blocks are not loaded (i.e. WordPress mobile apps).

<img width="1237" alt="Screen Shot 2019-05-14 at 10 28 44" src="https://user-images.githubusercontent.com/1233880/57664439-294f8e00-7633-11e9-8610-595d5ebb83ff.png">

We should revisit the current approach, since this might not result in a great experience. One option is to change the block output server-side only and leave the `core/video` block unaltered. Another approach is to deactivate `core/video` and register a new block so we avoid conflicts.

Unfortunately, we should keep maintaining the current behavior as a deprecated version of the `core/video` block in order to handle video blocks that have been created until the new approach is available.

**Comment by creativecoder** [comment]
@lessbloat @cathymcbride I'm adding this one to the Manage backlog for increased visibility.

This is a long standing issue and has to do with how the VideoPress block was implemented to override the Core video block markup. I see [at least one related user report](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1152#issuecomment-617947012).

Related Gutenberg Mobile issue: ([Videos added/edited on the web don't load in mobile editor](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1152)

I can replicate the problem by following the instructions in that issue.

**Comment by creativecoder** [comment]
More background discussion: pafL3P-pg-p2

**Comment by hypest** [comment]
Hello 👋! Is there any progress or maybe new understanding or plan for this ticket on the Jetpack side of things? Thanks!

**Comment by cathymcbride** [comment]
I'm not sure there has been any movement on this. @jeherve, do you?

**Comment by jeherve** [comment]
I don't believe the Video block is on anyone's radar at the moment; it's still in the Manage backlog as you can see on the project boards.

**Comment by jeherve** [comment]
Closing as this was addressed with the recent improvements made to the VideoPress block.
