### ISSUE TITLE
Sharedaddy module is suddenly exhausted 

### ISSUE THREAD

**Issue by seb86** [Automattic/jetpack#12362]
This error is causing a white screen of death in admin and not even the new fatal recovery feature added in version 5.2 of WordPress is helping me.

`[14-May-2019 12:23:44 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 8192 bytes) in /home/oceanthe/public_html/mydomain.com/wp-content/plugins/jetpack/modules/sharedaddy/sharing-sources.php on line 277
`
I increased memory in my `wp-config.php` file and nothing changed. I have WP 5.2 and PHP 7.3

Tested last two versions of JetPack. Not sure why this is happening because I have not made any changes to my site in months except for updating WordPress to 5.2. No issues until a few days later I find I can not access admin today.

Any idea why or are you aware of this bug? Please let me know what I can do to help solve this issue as I can not even disable the module.

Thank you.

**Comment by jeherve** [comment]
Could you let me know what sharing services are currently active on your site? Do you use any custom sharing services that you've set up via Settings > Sharing in your dashboard? Do you use plugins like [this one](https://wordpress.org/plugins/scoopit-for-jetpack/) to extend or customize the list of sharing services available in Jetpack?

Could you also try to deactivate other plugins on your site, one at a time, to make sure you don't have another plugin that is loaded before Jetpack and eats up most of your memory?

Let me know how it goes.

**Comment by seb86** [comment]
@jeherve Thank you for your quick response. I don't have any custom sharing services just what JetPack offers. I also have WooCommerce enabled with WooCommerce Services. I can't disable any other plugins (extensions for WC) as this is a live e-commerce site. The front-end works fine from what I can see.

This is the only issue being logged.

**Comment by jeherve** [comment]
Thanks. Could you let me know what buttons you currently use?

**Comment by seb86** [comment]
Facebook, Twitter, Pinterest and Email.

**Comment by seb86** [comment]
I just noticed I made a mistake with increasing my memory in my `wp-config.php` file to help the issue.

I used `WP_MAX_MEMORY_LIMIT` not `WP_MEMORY_LIMIT`

Both set at 256 and can now access the back-end again but never needed to use these constants until now so the issue still exists. That or you need to apply a requirement on memory for JetPack.

**Comment by jeherve** [comment]
Alright, thank you. I'm not sure why you would run into this error on that line in those conditions.

> I can't disable any other plugins (extensions for WC) as this is a live e-commerce site. 

Would you be able to test on a staging site and see if you experience the same issues there?

**Comment by seb86** [comment]
Limited space on server so no.

**Comment by jeherve** [comment]
I can't seem to be able to reproduce on my end, but my setup is probably different from yours. Unfortunately without running more tests, there isn't really a way to know what's eating up that much memory on your site; each one of your plugins is consuming its own part and Jetpack happens to be where you run out of memory, but you would need to know what else consumes that much memory before Jetpack to be able to understand what is happening.

Let us know once you get the chance to run more tests, on your server or locally.

**Comment by kraftbj** [comment]
I'm going to close this out until we're able to isolate a particular bug (conversation can still continue here). My guess is this isn't really an issue with Jetpack per se. As more code is being included via WordPress, your theme, and other plugins, you're hitting the point of memory exhaustion while Jetpack is loading, in particular when the sharing module is loading.

My guess is if you changed to a smaller theme (if you are using a particularly feature-rich one) or if you disabled some other plugins (namely those that load before Jetpack) or changed your Jetpack settings to load fewer modules, the error would also go away or indicate a different line item.
