### ISSUE TITLE
Full subscribers list cannot be found

### ISSUE THREAD

**Issue by blawrimore** [Automattic/jetpack#12364]
#### What happened instead

**Screenshots**

**Comment by jeherve** [comment]
It seems you did not include any information alongside that issue. Could you provide us more info about your request?

**Comment by blawrimore** [comment]
1. Go to https://www.charlotteareanews.com/charlotte-city-manager-presents-fiscal-year-2020-budget/
2. See number of subscribers (755)
3. When I access subscriber list through Jetpack > wordpress.com, I can only see 7 total subscribers. Where are the rest of them?

**Comment by blawrimore** [comment]
Sorry jeherve you are faster than I am! :-)

**Comment by blawrimore** [comment]
Yes thanks I added more information - sorry it took me a few minutes to look for it to be sure I was not in error.
Thanks for your rapid response!

Buck

Buck Lawrimore
President
Lawrimore Inc.
1320 Fillmore Ave., Ste 312
Charlotte NC 28203
704-332-4344
http://www.Lawrimore.com




On May 14, 2019, at 12:39 PM, Jeremy Herve <notifications@github.com> wrote:

It seems you did not include any information alongside that issue. Could you provide us more info about your request?

**Comment by jeherve** [comment]
This is to be expected.

Jetpack’s Subscriptions Widget includes all your site subscribers: your email and WordPress.com followers, but also your Facebook and Twitter Followers since they too receive updates for each one of your posts thanks to Publicize. As a result, you might have around 7 followers for Jetpack but you have more followers including your social media profiles.

I hope this make things clearer.

**Comment by blawrimore** [comment]
Ah yes thank you sir

Buck

Buck Lawrimore
President
Lawrimore Inc.
1320 Fillmore Ave., Ste 312
Charlotte NC 28203
704-332-4344
http://www.Lawrimore.com




On May 14, 2019, at 12:45 PM, Jeremy Herve <notifications@github.com> wrote:

This is to be expected.

Jetpack’s Subscriptions Widget includes all your site subscribers: your email and WordPress.com followers, but also your Facebook and Twitter Followers since they too receive updates for each one of your posts thanks to Publicize. As a result, you might have around 7 followers for Jetpack but you have more followers including your social media profiles.

I hope this make things clearer.
