### ISSUE TITLE
Akismet Key Check: Move to cron/admin

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#12382]
In https://github.com/Automattic/jetpack/pull/9669 and previous PRs, we added a key check for Akismet so we can confirm Akismet is not only installed/active, but using a valid key.

The check happens up to once every 10 minutes whenever we check for Akismet, which happens on the front end when e-mail sharing buttons are used.

We should move this to be a 24-hour check or when using wp-admin, akin to how Jetpack plan status is synced.

See Slack convo p1557934337326600-slack-jetpack-crew

**Comment by jeherve** [comment]
This can now be closed since we now use mailto instead of a custom email sharing button (see #24040).
