### ISSUE TITLE
Dashboard: Not Displaying in IE 11

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/jetpack#12407]
In 2035678-zen, the user reports that the Jetpack dashboard is blank in IE 11. I am able to replicate.

This user is blind and uses the Dolphin Supanova screen reader, which only fully works in IE. 

Per the customer:

> currently Dolphin are working on Chrome to try making it work there and so far it is about 50% working so unfortunately currently I can only work with IE.

There are no issues with Edge but the Dolphin Supanova doesn't work with that either.

There is a known issue with IE 11 in that the developer tools cause the tab to freeze - I've tried this many times now - so I'm not able to check the console for any errors.

#### Steps to reproduce the issue

1. Open IE 11
2. Go to Jetpack → Dashboard on a site with a Pro plan
3. Note that no information is displayed

#### What I expected

I should see the full Jetpack dashboard.

#### What happened instead

No information

**Screenshots**

![image (1)](https://user-images.githubusercontent.com/22805865/57939034-6b790980-7897-11e9-8a10-c3a0ce5e83d2.png)

**Comment by kraftbj** [comment]
@tmmbecker If you still have the IE11 box setup, can you check the console log for any errors and post them here?

**Comment by kbrown9** [comment]
I can confirm this issue in IE11 without a Pro plan. Luckily, developer tools didn't cause any problems for me! I saw this error in the console log:

> SCRIPT1010: Expected identifier
> File: admin.js, Line: 1, Column: 199710

Column 199710 is at the rest parameter `...` in this statement:
`t.log=function(...e)`

And, it looks like the ES6 rest parameter isn't supported by IE11; see this [ECMAScript 6 Compatibility Table](https://kangax.github.io/compat-table/es6/).

I hope this is useful!
