### ISSUE TITLE
Layout bug with SSO on "Lost Password" screen

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#1241]
If you have Jetpack SSO enabled, and click through to the "lost password" page during login, the SSO button is both outside the login box, and right-aligned

![screen shot 2014-10-31 at 10 18 24 am](https://cloud.githubusercontent.com/assets/108942/4864108/ca03a7de-6119-11e4-9d9a-15fb3bfb1a95.png)

It should probably either be inside the box, or perhaps just hidden entirely on this page.

**Comment by jeherve** [comment]
This seems to be fixed now. Closing.
