### ISSUE TITLE
Sharing: Make Reddit button orange to be in line with their brand guidelines

### ISSUE THREAD

**Issue by uncertainquark** [Automattic/jetpack#12439]
The Reddit button orange to be in line with their brand guidelines.

![Screenshot from 2019-05-22 20 28 29](https://user-images.githubusercontent.com/22585732/58186976-83a3bb00-7cd3-11e9-9a5c-a5aa92cbf52c.png)

The light blue one is also rather not attractive.

**Comment by jeherve** [comment]
Closing as duplicate of #9819
