### ISSUE TITLE
"Why are you disconnecting" modal is shown and then is immediately hidden

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#12452]
When disconnecting a Jetpack site from wp-admin, a black modal appears at the top of the screen that says something along the lines of "Fill out this survey to tell us why you're disconnecting, LINK", but that modal is almost immediately covered up by this screen:

<img width="1057" alt="screen_shot_2019-05-23_at_9 49 25_am" src="https://user-images.githubusercontent.com/3676359/58259264-2f83ef80-7d42-11e9-8f1e-ef7d302f2380.png">

We should probably get rid of that modal.

**Comment by jeherve** [comment]
Related: #10888
