### ISSUE TITLE
Tiled Gallery Block / Infinite Scroll: galleries loaded via Infinite Scroll miss scripts and styles

### ISSUE THREAD

**Issue by xpurichan** [Automattic/jetpack#12453]
> [!NOTE]
> This is only an issue with the Tiled Gallery Block. Classic Tiled Galleries inserted in a classic block are displayed properly.

### Steps to reproduce

1. Enable a theme that supports Infinite Scroll on your site, like Dara.
2. Under Jetpack > Settings, enable both Infinite Scroll and the image CDN.
3. Create a new post, publish it, backdate it to a point where it will only appear on your home page after Infinite Scroll is triggered.
4. Add a tiled gallery block to that post. 
5. Load your home page, and scroll down.
6. As the page including the gallery loads, you will notice that it is not styled properly.

The problem is limited to the Tiled Gallery block, it can't be reproduced when using a Tiled Gallery in a classic block.

************

### Original report

We received a user report of unexpected formatting on a tiled gallery block. When we're viewing this blog post from a category page than the tiled gallery will appear but the images are very large which makes the subject matter difficult to see, and many of the images include a lot of white space above/below them. Oddly, there are other tiled galleries (which are also using the tiled mosaic setting) on this category page and they are not experiencing the issue. I can't determine what is causing this to happen just for a few galleries on this page.

If we visit the blog post directly (outside of this category page) then the tiled gallery appears just as expected and fine.

Gallery from the category page:
![Screen Shot 2019-05-23 at 10 41 21 AM](https://user-images.githubusercontent.com/33190975/58266513-67d9fc80-7d47-11e9-882b-eb1e91863261.jpg)

Gallery directly on the blog post:
![Screen Shot 2019-05-23 at 10 42 31 AM](https://user-images.githubusercontent.com/33190975/58266559-804a1700-7d47-11e9-96cb-cc286b90d1a0.jpg)
 
User-reported on: 2048173-zen
See this ticket for further details and links to examples.

**Comment by jeherve** [comment]
Could you give us more details so we can try to reproduce?

- Can you reproduce on a test site?
- Does it happen on a WordPress.com site or a Jetpack site, or both?
- Does it happen when using a tiled gallery block, or a gallery using the tiled gallery type inside a classic block?
- Does switching themes resolve that issue?
- Do you see any errors in the browser console on the page? You can check for Javascript errors on the page as explained here:
http://codex.wordpress.org/Using_Your_Browser_to_Diagnose_JavaScript_Errors

Thanks!

**Comment by xpurichan** [comment]
@jeherve I apologize, I posted this GH report for another HE and didn't delve in as much as I should have.

I am struggling to reproduce this and I don't know why it's happening in the first place. I have recreated the setup on an AT and a Simple site:

AT - https://lillylearns.com/category/test/
Simple - https://lillytest123456.blog/category/test/

On both test sites I'm using the same Dara theme, a sidebar, category page, and I copied over the user's custom CSS.

Their issue doesn't appear on either test site once the page loads, but I _think_ that I do see the problem happen on the Simple Site for just a moment during the process of loading the page, then the images snap back in to place.

It seems like there is something "missing" in terms of how the images are being optimized on the user's website in this case.

**Comment by jeherve** [comment]
Thanks for the extra details. What if you add extra posts to your test sites, enough so that the post with the gallery gets loaded only later on as you scroll down and trigger infinite scroll?

**Comment by xpurichan** [comment]
We're getting somewhere interesting with this test. I exported the user's website on to my simple test site. Next I gave about 20 pages the category "test" and then changed the publish date of my "WordPress support test" post to February 28th 2019 so it would appear lower on the category page. Currently I can see the blog post in the list, but only the featured image and Youtube video appear. If I check the page's code I can see that the gallery is _supposed_ to be present, but it isn't loading at all:

https://lillytest123456.blog/category/test/

This is also the case for where the user's original problematic post appears a little below mine on this same category post (it's titled _Kemetamorphosis Conference 2018_).

**Comment by jeherve** [comment]
> I can see the blog post in the list, but only the featured image and Youtube video appear. If I check the page's code I can see that the gallery is supposed to be present, but it isn't loading at all:

That's interesting. That seems to be another problem though, and one I would suggest that you report on wpcom.trac, as it's specific to WordPress.com's image handling:

![image](https://user-images.githubusercontent.com/426388/58576653-1cdb5000-8245-11e9-9b41-59bd219ccdd4.png)

Apart from that WordPress.com issue, I was definitely able to reproduce the issue on a Jetpack site, and it's linked to Infinite Scroll. I've edited the original issue description to clarify things.

**Comment by xpurichan** [comment]
Mixed media, I would have never guessed. Thanks for that, I'll get it reported ASAP.

**Comment by KokkieH** [comment]
Another report from the [dotcom forums](https://en.forums.wordpress.com/topic/tiled-galleries-not-displaying-properly-on-older-posts)

**Comment by Robertght** [comment]
Another case found on my end and tested with both a WPCOM and self-hosted site.

The issue is present in Safari only on my end.

**Comment by jeherve** [comment]
Also in these 2 sites:

- 2743663-zen (Simple WPcom site. Theme: Snaps)
- 2692412-zen (Atomic WPcom site. Theme: Karuna)

**Comment by dromero20** [comment]
This site is also affected:

- 2772897-zen (Atomic WPcom site. Theme: Snaps)

**Comment by yansern** [comment]
Feature request. It will be nice to have an "Image Fit" dropdown on the block settings which applies the necessary classnames with CSS styling to cover or contain the image.

I've created a mockup of how it can look like.

![image](https://user-images.githubusercontent.com/1287077/132511129-1ceccba8-f39e-4c55-919e-63a8c83d06d7.png)

**Comment by jp-imagines** [comment]
Another similar report in 6651246-zd-a8c.

This site has infinite scrolling disabled, but clicking the `older posts` button yields the same results: the `jetpack-block-tiled-gallery-inline-css` style isn't loaded. It is loaded when visiting the affected post with the Tiled Gallery block, or when navigating directly by URL to `/page/x` to load the proper page of posts.

**Comment by jeherve** [comment]
Also reported in p1718716864223799-slack-C0299DMPG

As suggested by @simison, it may be worth exploring if WordPress' new [interactivity API](https://make.wordpress.org/core/2024/03/04/interactivity-api-dev-note/) could help us fix this issue.
