### ISSUE TITLE
My Plan: page layout is broken in IE11

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#12464]
#### Steps to reproduce the issue

1. In IE11 go to Jetpack > My Plan
2. See error

#### What I expected

correct layout

#### What happened instead
There is a syntax error, but it seems related to jitms, and nothing to do with this bug:
`Unable to get property 'indexOf' of undefined or null reference jetpack-jitm.js (222,3)`

<img width="1125" alt="MSEdge - Win10 2019-05-24 19-05-31" src="https://user-images.githubusercontent.com/5654161/58341524-191b8800-7e57-11e9-91c9-8505d6627318.png">

**Comment by sirreal** [comment]
This could be related to #12429

**Comment by sirreal** [comment]
I tried reverting 3e3f5220e52ce6e1f6ffd96f22e687816ae623d5 and still see the issue, so this is likely not a regression introduced in #12429
