### ISSUE TITLE
Private sites feature disables many Jetpack features without warning or explanation

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#12499]
#### Steps to reproduce the issue

1. Go to `/wp-admin/admin.php?page=jetpack#/security`
2. Enable "Private Sites"
3. Attempt to configure any of the following features:

```
'publicize',
'sharedaddy',
'subscriptions',
'json-api',
'enhanced-distribution',
'google-analytics',
'photon', // just for images, static files work
'sitemaps',
'verification-tools',
'wordads'
```

4. See that these features of Jetpack are unavailable and disabled

This is caused by a filter running in the Private Sites module:

https://github.com/Automattic/jetpack/blob/master/modules/private/class-jetpack-private.php#L257

#### What I expected

A clear explanation of why these features are disabled.

#### What happened instead

The message just says "features disabled by a site administrator". Probably it should:

(a) warn that these features will become unavailable **before** (or when) I enable Private Sites
(b) update the message for these features to say "X is unavailable for private sites. To enable this feature, first disable Private Sites"

**Screenshots**

<img width="395" alt="whoops" src="https://user-images.githubusercontent.com/51896/58595803-bc3d1a80-8226-11e9-8a17-44d5b1806742.png">

**Comment by gravityrail** [comment]
Also, for what it's worth, a private sites feature seems ideal for developing a site in private before releasing it, but this means all features need to be working for the person developing the site. Disabling social sharing buttons, for example, means they can't test or even see how these buttons look before making their site public, which hurts that whole use case. 

The rationale for disabling these features is we don't want to leak any information, but if course we don't (and can't) disable the information-leaking features of third parties, so to be honest this seems of dubious value. We can't act like Jetpack is the only plugin on the site.

**Comment by jeherve** [comment]
Related: #12491

**Comment by simison** [comment]
For more context p9dueE-HV-p2

**Comment by simison** [comment]
Note also p58i-7NH-p2

**Comment by jeherve** [comment]
Closing for now since the feature was removed from Jetpack in #12519
