### ISSUE TITLE
No easy way for a user to know what their site looks like when private

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#12497]
#### Is your feature request related to a problem? Please describe.

As a user, I don't know what my site looks like to logged-out users. Setting my site to private and viewing the home page shows the regular home page.

#### Describe the solution you'd like

Here is the current settings UI:

<img width="615" alt="make-site-private" src="https://user-images.githubusercontent.com/51896/58594506-b0e7f000-8222-11e9-834b-00aa8c37d29c.png">

I would like a preview or screenshot of what the site looks like to logged-out users. Also not everyone knows what it means for someone to be a "member" of their site, since "member" has so many meanings. For example, my site is for a club that has members. A member views the site and gets the login screen. So, we don't just care if someone's a member, we care if they're **logged in**.

<img width="391" alt="private-site-preview" src="https://user-images.githubusercontent.com/51896/58594435-78481680-8222-11e9-9407-66642f4584bd.png">

#### Describe alternatives you've considered

I guess you could describe how to view the site in incognito mode? Seems a bit advanced.

**Comment by jeherve** [comment]
Closing for now since the feature was removed from Jetpack in #12519
