### ISSUE TITLE
Carousel: "View full size" link doesn't use Photon when the Tiled Galleries module is active

### ISSUE THREAD

**Issue by ChrisBegley** [Automattic/jetpack#1250]
This issue came up before (#522) and was fixed in #523, but it's a problem again after the Jetpack 3.2 update.

When Tiled Galleries is deactivated, the "View full size" link in the Carousel uses Photon.

But when Titled Galleries is activated, the "View full size" link in the Carousel points to the original image instead.

**Comment by zinigor** [comment]
Let's look at this in relation to the Core responsive images feature.

**Comment by kraftbj** [comment]
The link is generated in JS. We'd probably need to photonize the URL and pass it through to JS through the localization function.

**Comment by zinigor** [comment]
Should be fixed by #3200
