### ISSUE TITLE
Anomaly with the likes column in the WordPress backend?

### ISSUE THREAD

**Issue by TheJeffr0** [Automattic/jetpack#1251]
In the backend of WordPress, there's a column for comments and a column for Likes. In the likes column, there is this little triangle thing to the bottom left of the Likes digit. It's attached to the icon and points to the same permalink as the actual Likes button. Is this some sort of display anomaly as it looks out of place. The screenshot shows what I'm talking about. Using the latest version of Jetpack with WordPress 4.0. 

![thisthing](https://cloud.githubusercontent.com/assets/6315977/4895617/7ed5ef02-63ed-11e4-8e9b-4b322c24129a.png)

**Comment by aheckler** [comment]
@TheJeffr0 -- Is this still occurring for you?

**Comment by TheJeffr0** [comment]
Nope, it looks fine now.
