### ISSUE TITLE
Block Editor: Bunch of Jetpack blocks are not available due to syntax error in IE11

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#12511]
#### Steps to reproduce the issue

1. Go to `post-new.php` in IE11
2. See error in console:

`SCRIPT1002: Syntax error _inc/blocks/editor.js (12,140634)`

The above line points to the `./node_modules/photon/node_modules/ms/index.js` transpiled chunk

#### What happened instead
Only 6 Jetpack blocks are available in IE11 (on Pro plan).
<img width="469" alt="MSEdge - Win10 2019-05-30 19-03-02" src="https://user-images.githubusercontent.com/5654161/58646196-9474b200-830d-11e9-811f-ffab3bac07c0.png">

**Comment by simison** [comment]
Ay ay ay.

IE11 keeps giving.

**Comment by simison** [comment]
So this seems like we're depending on photon that is depending on something that is ES6 code and we don't transpile node_modules (in Jetpack nor in Calypso unless that has changed recently, cc @blowery )

This could happen in future (or could be happening elsewhre already) with any package used by block editor extensions or by Jetpack dashboard.

**Comment by sirreal** [comment]
`punycode` is being pulled in, [which sets it's `module` field to an es6 file](https://github.com/bestiejs/punycode.js/blob/68df855dc42d1086ada161331b3074468e8d848d/package.json#L8).

We can try to force webpack to use punycode's `main` (`punycode/punycode.js`) or try to get that transpiled…

Transpiling that would look like changing the [`TranspileConfig.loader`](https://github.com/Automattic/wp-calypso/blob/9980108e2780289a1441d16a6db0e8868fe5834f/packages/calypso-build/webpack.config.js#L105) (from `@automattic/calypso-build`) `excludes` to not exclude `punycode` like this:

```js
TranspileConfig.loader( {
	cacheDirectory: true,
	configFile: babelConfig,
	exclude: /node_modules\/(?!punycode)/,
	presets,
	workerCount,
} ),
```

Not sure of the best way to do that, we aren't accessing `TranspileConfig` directly right now 😞 

cc @ockham

**Comment by ockham** [comment]
Looking into this now :eyes:

**Comment by ockham** [comment]
Upstream bug: https://github.com/bestiejs/punycode.js/issues/86

**Comment by ockham** [comment]
We have a mechanism in Calypso-the-app to tackle the same problem: https://github.com/Automattic/wp-calypso/blob/91c59bb35a5f3c12b7c51bbbceb674e222cd4bca/webpack.config.js#L204-L210

and

https://github.com/Automattic/wp-calypso/blob/91c59bb35a5f3c12b7c51bbbceb674e222cd4bca/webpack.config.js#L112-L138

I think the solution should be to move this mechanism into `calypso-build`.

We might want to re-consider the way we determine which packages to transpile -- currently, it's just a whitelist. Maybe we should take some `package.json` fields into consideration after all? `jsnext:main`, [which is used by `punicode`](https://github.com/bestiejs/punycode.js/blob/68df855dc42d1086ada161331b3074468e8d848d/package.json#L7), might be exotic enough to give it a try...

/cc @Automattic/team-calypso

**Comment by sirreal** [comment]
A thought: I don't know how widespread the practice is, but `punycode` points its `module` field to `punycode.es6.js`. Could we transpile node_modules files like `*.es6.*`?
