### ISSUE TITLE
Infinite Scroll and Masonry don't work well together

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#1253]
When using Masonry, there isn't a bounded page that can be replaced by a div for infinite scroll, so that causes posts to disappear and reappear. You can see the issue at http://d.pr/i/1aKMy+

Ticket ID: 1988225

**Comment by mindctrl** [comment]
@jeherve @michaeldcain any chance of getting this one fixed soon? If the caching can't be fixed by the next update can it at least be reverted until someone has time to give it a good look to fix it?

**Comment by mikemcalister** [comment]
@jeherve @michaeldcain Hey guys, thanks for looking into this! I can confirm I'm seeing the same thing with several of our premium themes. The latest Infinite Scroll changes referenced above have broken masonry and seem to be causing unpredictable behavior. 

It would be great to see a revert or temporary fix so Infinite Scroll isn't broken out of the box. Let me know if there's any info I can provide to help!

**Comment by ms-studio** [comment]
For debugging purposes, here is a very basic test case (theme: Designer): http://sandbox.4o4.ch/wp-git/portfolio/

In order to trigger the disappearance of the second item, the browser window has to be very narrow:

- width below 500px, so that the items are in one column.
- height below 490px, to allow the first item to disappear from view.

I created only two Portfolio items, and set the "Blog pages show at most" value to 1, in order to display the "More" button.

**Comment by jamez14** [comment]
Is there a work around for this currently? Such as reverting back to a previous version of Jetpack? If so, which version? 

I'm experiencing similar erratic behavior when using Masonry & Jetpack infinite scroll together. Pages jumping, loading on top of each other, scrolling forever (literally). Any help in finding a temporary solution would be great.

**Comment by mindctrl** [comment]
@jamez14 we ended up hacking around it by moving the elements out of the infinite-view-* containers with javascript.

**Comment by ms-studio** [comment]
@jamez14 In the case of the Designer theme, the issue was fixed by theme update 1.1.6 - infinite scroll is now working fine with Jetpack 3.6.1.

**Comment by jeherve** [comment]
Closing, as we've had no other reports of this issue in the past few months.
