### ISSUE TITLE
Jetpack DNA: Connection package update

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#12539]
In https://github.com/Automattic/jetpack/pull/12399 we merged the basic skeleton of the Connection package. We'll need to take it further so that it includes the 
Jetpack::is_active method as this is directly related to connections, as well as other related bits.

And we'll need to test it to ensure that it actually works.

**Comment by jeherve** [comment]
In progress in #12669

**Comment by gravityrail** [comment]
This ticket is too generic, let's open specific tickets for the remaining tasks.

https://github.com/Automattic/jetpack/pull/12669 is done
