### ISSUE TITLE
Search: add optional Powered by logo

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#12540]
There are some cases (especially internal sites) where we should display the Jetpack logo, and we have added config to the new customization controls.

Here are designs:

<img width="457" alt="Screen Shot 2020-01-23 at 5 26 07 PM" src="https://user-images.githubusercontent.com/820871/73035530-a0b20000-3e05-11ea-8a9c-9438237e3ef6.png">

<img width="318" alt="Screen Shot 2020-01-23 at 5 26 24 PM" src="https://user-images.githubusercontent.com/820871/73035536-a4de1d80-3e05-11ea-8c6d-c1890eebe8da.png">

There is a logo and display available in https://github.com/Automattic/wp-calypso/tree/master/client/components/jetpack-colophon and https://wpcalypso.wordpress.com/devdocs/design/jetpack-colophon

These should link to https://jetpack.com/support/search/ for now.

- [x] Add "powered by Jetpack" colophon
- [x] Add Jetpack magnifying glass to search input

**Comment by bluefuton** [comment]
Can we drop the icon in the search input at smaller breakpoints? It'd be taking up precious input space while not really adding much value.

**Comment by keoshi** [comment]
Adding a few more options for the input icon here:

![image](https://user-images.githubusercontent.com/390760/73058630-e9ac9780-3e8b-11ea-978b-9d15f04c2cda.png)

> Can we drop the icon in the search input at smaller breakpoints?

I think we should, yes.

**Comment by gibrown** [comment]
@keoshi my 2 cents... I like (e) the most for the inverted colors which feel lighter weight, and (a) the most for the longer handle. (e) looks too much like the logo inside of a Q. If I was only picking between these I would choose (a).

**Comment by gibrown** [comment]
Maybe we can also create a button with the icon that a user can easily add to their site (code snippet I guess) that will activate the search overlay. For instance, on jetpack.com it would be good to just add a button to the header.

**Comment by bluefuton** [comment]
Added the "Search powered by Jetpack" colophon in #14519.

**Comment by jsnmoon** [comment]
@keoshi Could you upload the SVG for icon A? I'm currently working with a vectorized version of your screenshot, which probably isn't ideal 😉.

**Comment by keoshi** [comment]
@jsnmoon My bad — was at the JP GM last week and just saw your comment above. Should I adjust it directly on https://github.com/Automattic/jetpack/pull/14629/ ?

**Comment by jsnmoon** [comment]
@keoshi Yup, that sounds great. There are some rough edges in #14629 that would benefit from your guidance. Thanks!

**Comment by jsnmoon** [comment]
Fixed by #14519 and #14629.

**Comment by folletto** [comment]
A couple of comments on the icon here, sorry if I didn't catch it before.

Note: we should be very careful in using branding in a UI component. There are exceptions, but as a rule of thumb, _be wary of using the logo in a UI element._

In this case, to me it doesn't just break that rule of thumb, but also doesn't seem to fit properly visually. The filled one isn't really a lens, and the diagonal 45° angle of it makes the logo feel "turned" off its axis (i.e. if you had a logo on the magnifying class, it would be aligned with the magnifying class axis).

My advice here is either:
1. Go for a simple icon that is JUST search icon (the classic magnifying glass). We can maybe make it more memorable if we want, but this paired with the footer added in #14519 should be enough.
2. If we really really really really want to have the logo there, then let's use icon (e) which doesn't break the mental model of a magnifying glass — and then I agree with Greg, let's make the handle longer tho.

**Comment by keoshi** [comment]
I've been struggling with the idea of the magnifying glass but also didn't think too much of it. While I disagree on this point:

> if you had a logo on the magnifying class, it would be aligned with the magnifying class axis

Because I believe the idea here is that the magnifying glass is hovering on the logo itself (which doesn't make much sense either way), but other that that nitpick I appreciate the feedback here @folletto — you've put into words what I couldn't quite put my finger on, and done it so clearly. 🌟

I agree that we should reduce the amount of branding, especially since we already offer the option of adding the credit on the footer, which feels way classier to me. If we get rid of the complex icon, the search UI is allowed to breathe much more too, like so:

![image](https://user-images.githubusercontent.com/390760/74645442-d9789700-516f-11ea-9ba1-145f47ce389a.png)

I'll get a PR started.

**Comment by folletto** [comment]
> Because I believe the idea here is that the magnifying glass is hovering on the logo itself 

Yes: that is why option (e) works, as it's hollow and feels like hovering, but if it's full it doesn't as it feels like being part of it ;)

> like so

It feels way lighter. :)

**Comment by keoshi** [comment]
> but if it's full it doesn't as it feels like being part of it ;)

Ha yes, of course — ignore me, still waking up. Thanks a ton for this piece of feedback!

**Comment by keoshi** [comment]
Addressed @folletto's feedback on https://github.com/Automattic/jetpack/pull/14664/
