### ISSUE TITLE
Remove `gulp-browserstack`

### ISSUE THREAD

**Issue by mdawaffe** [Automattic/jetpack#12550]
As far as I can tell, this package was never used. It was included as part of the transition to`gulp` in https://github.com/Automattic/jetpack/commit/3b52571e90949154f272ffb96be6e12f5c85c0b8 (part of #3800).

@dereksmart, do you know if we still need this package?

#### Steps to reproduce the issue

1. `yarn audit`
2. See `gulp-browserstack` is requiring an old `fstream`.

#### What I expected
Let's aim for clean audits.

#### What happened instead
Dirty audits.

**Comment by mdawaffe** [comment]
> Let's aim for clean audits.

Removing `gulp-browserstack` together with https://github.com/Automattic/jetpack/pull/12549 would yield a clean `yarn audit`.

**Comment by brbrr** [comment]
From package description:
> Start and SSH tunnel before you run your e2e tests in Gulp and tear it down properly afterwards. 

I'd say it's not needed, and according to our code - it's not used anywhere. So I'd say we save to get rid of it.
