### ISSUE TITLE
Professional Plan ::: Publicize Unable To Connect To Facebook

### ISSUE THREAD

**Issue by gk7279** [Automattic/jetpack#12559]
Publicize Unable To Connect To Facebook
#### Steps to reproduce the issue

Our site's publicize connection to facebook is broken. It wouldn't connect even after following the steps mentioned here - https://jetpack.com/support/publicize/facebook/

Twitter is connected and it works fine.

We are on professional plan and it has been more than 36 hours since I wrote to Jetpack team. This sort of customer care is unappreciated and ridiculous.

#### What I expected

I tried other plugins and facebook auto publish works fine. So there is something with publicizes facebook module that is preventing us. We post 100s of articles on a daily basis and to manually post them would be a pain in the ass. Please help.

**Comment by jeherve** [comment]
Could you let me know your site URL, your support ticket ID, or your email address so I can look for your email in our support system and see what happened with your ticket?

Thank you.

**Comment by gk7279** [comment]
www.TNILIVE.com

editor.tnilive@gmail.com

**Comment by gk7279** [comment]
The page was added to our business maanger account. I just removed it and tried reconnecting. Still no luck. Jetpack was unable to connect. So I re-added back the page to our business manager. Thanks.

**Comment by jeherve** [comment]
I found your ticket, thank you. It was wrongly categorized by our ticket system, sorry about that. I'll take a look at your site settings and reply to your email right away.

For reference: 2081792-zen
