### ISSUE TITLE
At a Glance: Switch to Upgrade banner on Spam Protection DashItem

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#12566]
### The problem
The Compact Notice components are no longer serving well as an upgrade call to action. They make the dashboard look broken. There is also a redundant text link that is a secondary redundant call to action.

Here is the current Spam Protection DashItem:
![image](https://user-images.githubusercontent.com/1123119/58903073-c1381900-86c1-11e9-9896-35587b1826b9.png)

### Proposal

**Copy:**
Spammers have state-of-the-art tech. You should too! Akismet keeps your site spam-free.

**Gridicon**
`icon="flag"`

**Mockup**
![image](https://user-images.githubusercontent.com/4297811/59139880-3ad63e00-8932-11e9-8a97-83c120cdeecb.png)

**Comment by eeeeevon13** [comment]
Looks good to me... except... PENCIL ICON! I still don't get it.

**Comment by MichaelArestad** [comment]
What is spam defense? Is spam too niche of a word? Perhaps we can use both "spam" along with something like "defense against evil robot comments" or something like that?

**Comment by jessefriedman** [comment]
looks good to me

**Comment by crunnells** [comment]
@Automattic/editorial or @michelleweber can you take a look at the copy here please? Thanks!

**Comment by michelleweber** [comment]
I don't think "spam" is too niche, though I would like to avoid using in three times in such a small bit of text. How about something like:

_You work too hard on your site to have it clogged with spam! Keep the junk our so your content can shine.

You work too hard on your site to have it clogged with spam! Akismet keeps the junk out.

Spammers have state-of-the-art tech. You should too! Akismet keeps your site spam-free._

(Related question: do we _have_ to reference Akismet? It's built in to JP; is it not enough to reference JP? The less we introduce terms/names that we then have to define for the user, the better.)

**Comment by MichaelArestad** [comment]
@michelleweber Those are good suggestions.

Made a minor tweak to this one:
> You work too hard on your site to have it covered with spam! Keep the junk out and let your content shine.

And I also like:
> Spammers have state-of-the-art tech. You should too! Akismet keeps your site spam-free.
Or maybe something like:


> (Related question: do we have to reference Akismet? It's built in to JP; is it not enough to reference JP? The less we introduce terms/names that we then have to define for the user, the better.)

Good question. Akismet isn't built into Jetpack, but it is part of Jetpack plans. There is still a separate Akismet plugin. I think the thinking was that it might be good to mention Akismet before folks get a surprise plugin with a different name.

**Comment by michelleweber** [comment]
I feel like the place to introduce it isn't in this very short upgrade message, but during/just after the actual upgrade process, where you have a little more room to contextualize it.
