### ISSUE TITLE
At a Glance: Switch to Upgrade banner on Backups DashItem

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#12565]
### The problem
The Compact Notice components are no longer serving well as an upgrade call to action. They make the dashboard look broken. There is also a redundant text link that is a secondary redundant call to action.

Here is the current Backups DashItem:
![image](https://user-images.githubusercontent.com/1123119/58902965-833af500-86c1-11e9-83c2-c795d471694f.png)

### Proposal

**Copy:**
Never worry about losing your site -- Automatic backups keep your content safe.

**Gridicon:**
`icon="history"`

**Mockup**
![image](https://user-images.githubusercontent.com/4297811/59139891-60634780-8932-11e9-8795-badb16d057ea.png)

**Comment by eeeeevon13** [comment]
@crunnells  my suggestions https://wp.me/p6TEKc-2Ju

**Comment by crunnells** [comment]
Updated mockups and copy based on @eeeeevon13's suggestions.

**Comment by MichaelArestad** [comment]
I think the suggestions are good. Let's get a copy review. I know there needs to be some fix to grammar/punctuation, but I'm not sure what the best route is. Time to call in the expert! CC @michelleweber

**Comment by jessefriedman** [comment]
"Never worry about losing your data, get automatic daily or real-time back ups."

To most users data doesn't mean files, themes, settings and content.  I think we should say something that is more inclusive to the entire site. 

"Eliminate stress and have confidence in trying out new changes because to try new things with daily or real-time Jetpack backup" 

"Secure, restore, move and even experiment with the confidence of security expert because you've enabled Jetpack backup"

**Comment by michelleweber** [comment]
I like that direction, but I do think we also need to include some language, however high-level, that gets at what a backup actually is.

Some tweaks/suggestions based on the above:

Create and experiment with the confidence of web security expert -- you've got Jetpack backup, so your content's always safe.

Posts, pages, themes, settings, plugins -- Automated backups protect them all, so you can create stress-free.

**Comment by MichaelArestad** [comment]
I like all of these suggestions. Perhaps something simpler that is sort of the best of both sets of suggestions?

> Never worry about losing your site -- Automatic backups keep your content safe.
