### ISSUE TITLE
At a Glance: Switch to Upgrade banner on Jetpack Search DashItem

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#12567]
### The problem
The Compact Notice components are no longer serving well as an upgrade call to action. They make the dashboard look broken. There is also a redundant text link that is a secondary redundant call to action.

Here is the current Jetpack Search DashItem:
![image](https://user-images.githubusercontent.com/1123119/58903219-11af7680-86c2-11e9-809a-78e94eb5be10.png)

### Proposal

**Copy:**
Help visitors find what they're looking for with Jetpack search -- the faster, customizable, super-relevant search tool.

**Gridicon**
`icon="zoom-in"`

**Mockup**
![image](https://user-images.githubusercontent.com/4297811/59139858-fd71b080-8931-11e9-8f85-0f4aab2fc162.png)

**Comment by eeeeevon13** [comment]
@MichaelArestad Suggestion: "Replace the standard search with a faster, scalable, customizable & highly-relevant search hosted in the WordPress.com cloud".

**Comment by MichaelArestad** [comment]
I dig.

**Comment by jessefriedman** [comment]
Just an idea on content:

"Increase engagement by showing visitors more relevant and compelling site search results with Jetpack search"

**Comment by crunnells** [comment]
@Automattic/editorial or @michelleweber can you take a look at the copy here please? Thanks!

**Comment by michelleweber** [comment]
Can we go a little more natural-language sounding and split the difference in approaches with something like:

_Help visitors find what they're looking for with Jetpack search -- the faster, customizable, super-relevant search tool._

Related: can we see all the upgrade banner copy in a single doc/in one post? It would be great to review them all together so we can be totally sure the tone is consistent across the board.
