### ISSUE TITLE
At a Glance: Switch to Upgrade banner on Security Scanning DashItem

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#12564]
### The problem
The Compact Notice components are no longer serving well as an upgrade call to action. They make the dashboard look broken. There is also a redundant text link that is a secondary redundant call to action.

Here is the current Security Scanning DashItem:
![image](https://user-images.githubusercontent.com/1123119/58902607-a6b17000-86c0-11e9-8abe-59a8d147cf9b.png)

### Proposal

**Copy:**
Jetpack's comprehensive security scanning finds issues early so we can help fix them fast.

**Gridicon**
`icon="lock"`

**Mockup**
<img width="530" alt="Security Scanning v3" src="https://user-images.githubusercontent.com/4297811/59135178-ba0b4800-8919-11e9-83cc-5fcc1452d541.png">

**Comment by eeeeevon13** [comment]
@MichaelArestad Do we have an icon that is more relevant to security?  A lock or something?? The pencil doesn't make sense here, not scannable. Ya know?

**Comment by MichaelArestad** [comment]
@eeeeevon13 The short answer: Not yet. Unfortunately, it is out of scope for this project, but something we could pursue sometime after the meetup.

**Comment by MichaelArestad** [comment]
I think the copy on this one is ready for review. CC @michelleweber

**Comment by jessefriedman** [comment]
@MichaelArestad @crunnells I'll comment here for all the design changes across this project. I really like the style, icons, and general feel.  

As for the content I'd caution against saying that malicious file scanning can "protect against" attacks or hacks.  Technically scanning detects those things and helps to reverse them but we don't prevent attacks.  Jetpack Protect does this for logins and Akismet does this for spam, but we don't thwart attacks with malicious file scanning. 

Here's a suggestion: 
"Start comprehensive Jetpack scans for security threats and malicious activity; don't stress we can help you remove anything we find."

A statement like this is action driven and empowering to the user.  They know what they get, when they can start using it, and how they will solve the problem if one exists.

**Comment by michelleweber** [comment]
Taking that above into account, a few other options:

Nip malware and malicious attacks in the bud with comprehensive security scanning.

The best defense against hacks? A solid offense. Protect yourself with comprehensive security scanning.

Jetpack's comprehensive security scanning finds issues early so we can help fix them fast.

**Comment by crunnells** [comment]
> Jetpack's comprehensive security scanning finds issues early so we can help fix them fast.

I vote for this line.

**Comment by crunnells** [comment]
Updated the mockup to show the 'lock' icon we're using in the banner.
