### ISSUE TITLE
Jetpack JITM Package: remove dependencies

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#12579]
In the [initial PR](https://github.com/Automattic/jetpack/pull/12516) for making a JITM package,  we left a few Jetpack-specific dependencies.

We need to circle back and remove them on the next iteration.

**Comment by gititon** [comment]
In progress

**Comment by gititon** [comment]
Started with https://github.com/Automattic/jetpack/pull/12596

**Comment by gravityrail** [comment]
Dupe of https://github.com/Automattic/jetpack/issues/12686
