### ISSUE TITLE
Plans: Remove recommended features prompt from plans / my plans

### ISSUE THREAD

**Issue by scottsweb** [Automattic/jetpack#12584]
The recommended features prompt is confusing in the my plans context. It stands between the user and the important information they are seeking.

**Before:**

![Screenshot 2019-06-06 at 14 26 13](https://user-images.githubusercontent.com/411945/59036913-1c0b7500-8868-11e9-8521-4266f78d7352.png)

![Screenshot 2019-06-06 at 14 26 23](https://user-images.githubusercontent.com/411945/59036933-23328300-8868-11e9-8bee-8eda2bf58320.png)

**After:**

![Screenshot 2019-06-06 at 14 26 48](https://user-images.githubusercontent.com/411945/59036951-2b8abe00-8868-11e9-81f0-bc41e660bbd9.png)

![Screenshot 2019-06-06 at 14 27 03](https://user-images.githubusercontent.com/411945/59036961-2f1e4500-8868-11e9-97da-65bb6676d5aa.png)

**Comment by jeffgolenski** [comment]
Thanks @scottsweb Just tying this together with Luna (@simison) for when we're ready to dissolve jumpstart for the full checklist upon its completion.

**Comment by simison** [comment]
@jeffgolenski  @scottsweb; can you help make sure everyone in Jetpack design is aware of our plans to phase out Jumpstart? Let's also figure out a timeframe for it soonish. Seems to boil down to question "can we remove it already for Jetpack 7.5?"

**Comment by scottsweb** [comment]
That is good to know, perhaps we can just close off this issues then?

**Comment by simison** [comment]
>That is good to know, perhaps we can just close off this issues then?

Fine by me! I opened another one to track this: https://github.com/Automattic/jetpack/issues/12601
