### ISSUE TITLE
Add upgrade prompt on Settings > Share page

### ISSUE THREAD

**Issue by eeeeevon13** [Automattic/jetpack#12594]
#### Is your feature request related to a problem? Please describe.
Currently, there is no upgrade prompt on the Settings > Sharing page. There are some great paid features, like being able to schedule your social media posts that we are not surfacing to users

#### Describe the solution you'd like
Add an upgrade prompt to this page 

#### Describe alternatives you've considered
Ideally, I'd love to see an A/B test where we take users directly to the checkout page on this one because we do NOT currently list this feature on the plans page (will put another issue for that)

**CURRENT:**
![Current](https://user-images.githubusercontent.com/426388/59051914-3c4e2a80-888e-11e9-8c0d-d4695a343bf2.png)

**PROPOSED SOLUTION**
![settings-sharing-proposed](https://user-images.githubusercontent.com/426388/59051917-3fe1b180-888e-11e9-9970-293889f552e4.png)

**TRACKING**
Let's make sure and add Tracks to the button

**DESIGN**
Still getting my arms around which icons are used where. I may have grabbed the wrong one @MichaelArestad please advise.

@obi2020 @krisnikolova @pablohoneyhoney @scottsweb

**Comment by eeeeevon13** [comment]
@jeffgolenski @lucasartoni This would be a good one to A/B test. As I mentioned above, we do not list this feature on the plans page. So having an A where users go to plans page and B where users go directly to checkout with the Premium plan selected (maybe set to monthly??) would be a great test.

**Comment by scottsweb** [comment]
Added to the copy sprint 1.0 project board. We may need to look at the "editorial calendar" heading.

**Comment by jeherve** [comment]
This has now been implemented.
