### ISSUE TITLE
Security: Plugin auto-update copy

### ISSUE THREAD

**Issue by scottsweb** [Automattic/jetpack#12590]
Need to settle on a format for 'auto-update', 'autoupdate' etc

**Before:**

![Screenshot 2019-06-06 at 15 46 00](https://user-images.githubusercontent.com/411945/59042372-3a766e00-8872-11e9-80d8-139f869a4326.png)

**After:**

![Screenshot 2019-06-06 at 15 48 31](https://user-images.githubusercontent.com/411945/59042553-8e815280-8872-11e9-9067-49b56eca1cbc.png)

> With Jetpack you can choose to have your plugins auto updated with each new plugin release. You’ll get the latest security and bug fixes right away, ensuring your site stays secure.

> Choose which plugins to auto-update

**Comment by obi2020** [comment]
Please standardize hyphen usage throughout. I.e. 

- For the feature label: `Plugin auto-updates` ... which, now that I'm looking at it is easier to read as `Auto-update plugins` <<< prefer this, though it will obscure the word "plugin" somewhat. 

- In the description: `...have your plugins auto-updated...`

- CTA: looks good 👍

Checked in with @benhuberman on this, BTW and he's onboard with using the hypen.

**Comment by scottsweb** [comment]
Excellent, thank you for checking on this.
