### ISSUE TITLE
Post By Email: Support our own shortcode embeds

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#1259]
We should allow the shortcodes listed [here](http://jetpack.me/support/shortcode-embeds/) to be used in addition to the [existing PBE ones](http://jetpack.me/support/post-by-email/#shortcodes). 

Right now, for example, there is literally no way to embed a video in a post using PBE: neither the `[youtube]` shortcode, the YouTube.com-provided `iframe`, nor just pasting the URL on it's own line works. :(

**Comment by aheckler** [comment]
Forums user with same issue: https://wordpress.org/support/topic/youtube-embed-urls-1

**Comment by samhotchkiss** [comment]
No good!  This should be a pretty easy fix, I'd imagine.  Tagging for 3.5

**Comment by aheckler** [comment]
@samhotchkiss I can't remember if I tested this on WP.com or not, so it may not work there either. I will have to test and get back to you.

**Comment by samhotchkiss** [comment]
Either way, it should just require us to make sure we're running the same filters.

**Comment by aheckler** [comment]
Huh, weird. Now that I test it with a YouTube video, it works fine when you use the shortcode:

`[youtube=https://www.youtube.com/watch?v=3d2VnZu70IY]`

... but doesn't work when you just insert the link, like so:

`https://www.youtube.com/watch?v=3d2VnZu70IY`

This is probably expected. It also worked with the Facebook shortcode. 

Did we maybe fix this at some point and I missed it? I swear it didn't work when I opened this...

**Comment by kevmarsden** [comment]
The same user contacted us in the [P2 theme forum](https://wordpress.org/support/topic/youtube-embed-urls?replies=4). I tested post by email using YouTube both HTTP and HTTPS raw links and found that neither links created a embedded video.

**Comment by samhotchkiss** [comment]
Our implementation of Post by Email is intended to be very simple and minimal, so, unfortunately, this doesn't align with our development goals and plans at this time, and is not on our roadmap for future development.

**Comment by richardmtl** [comment]
Noting that this came up again here:

https://wordpress.org/support/topic/posts-by-email-and-youtube/

Just using the link did **not** embed the Youtube video, as described by Adam.
