### ISSUE TITLE
Site accelerator: initial toggle switch is redundant 

### ISSUE THREAD

**Issue by scottsweb** [Automattic/jetpack#12593]
![Screenshot 2019-06-06 at 17 01 16](https://user-images.githubusercontent.com/411945/59047974-dad19000-887c-11e9-8e67-fbe046377b75.png)

The initial top level toggle does not provide any value at the moment. It is not possible to have it on in isolation and requires one of the child toggles to be enabled. I think we can simplify this UI by removing it.

**Comment by jeherve** [comment]
See p9jf6J-11u-p2 for more information about this. The idea was to create a group of features you could enable in one click, as the distinction between the 2 settings may not be clear for everyone.

**Comment by scottsweb** [comment]
Thanks for the context, closing.
