### ISSUE TITLE
Customize center lat/long for map block

### ISSUE THREAD

**Issue by bracketsberlin** [Automattic/jetpack#12605]
Right now, the center of a map which is included with a map block always uses San Francisco as the center and then flies to the added marker position as defined in `jetpack/extensions/blocks/map/settings.js`. Flying from San Francisco to a Marker in Dubai, for instance, is most of the time pretty undesirable. 

Could you please think about an extended set of settings for the Map block which would allow specifying a custom center lat/long via the InspectorControl?

Example:
![GIF](https://media.giphy.com/media/jsHt5ZSujvSK9lzTBN/giphy.gif)

Thank you very much.

**Comment by jeherve** [comment]
Thanks for the feedback!

> Could you please think about an extended set of settings for the Map block which would allow specifying a custom center lat/long via the InspectorControl?

Adding geolocation to the block would have that effect, and it's something we've considered. See #11878 for more discussion about this.

I'll close this as duplicate of #11878 since solving that other issue would solve the issue you reported.

**Comment by bracketsberlin** [comment]
Thanks for getting back to this feature request. I don't think that this necessarily is connected to GeoLocation. Consider this use case: a website about Dubai would maybe start with a low zoom-level above the town Dubai. And then, it zooms automatically to the markers.

I'd highly suggest allowing any location as the center

**Comment by jeherve** [comment]
> Consider this use case: a website about Dubai would maybe start with a low zoom-level above the town Dubai. And then, it zooms automatically to the markers.

That makes sense, I could see this as being useful to some indeed.

**Comment by Copons** [comment]
Closing this as fixed in Jetpack 8.2 (https://github.com/Automattic/jetpack/pull/14417)
