### ISSUE TITLE
Integrate Likes and Comments in the Reader for Jetpack Sites

### ISSUE THREAD

**Issue by zandyring** [Automattic/jetpack#1262]
WP.com blogs show likes/comments within the Reader. Jetpack sites don't, even when using JP Comments or Likes.

**Comment by richardmtl** [comment]
Requested in 2108882-t

**Comment by blowery** [comment]
We have like support now, most of the time. Comments are still a ways off.

**Comment by jeherve** [comment]
Closing this, as Comment Likes don't exist on Jetpack sites yet (see #3224)
