### ISSUE TITLE
Jetpack vs WordPress core

### ISSUE THREAD

**Issue by nvartolomei** [Automattic/jetpack#1263]
Hello,
First of all I really hope I'm not first who asks this question, but I couldn't find answers to it anywhere.

My questions is, why do Automattic strive to develop Jetpack standalone and does not contribute this beautiful product into WordPress Core?

It was not a concern for me until now because many features were not belonging to WordPress Core, but today I saw [Site Logo][1], you (Jetpack) encourage developers to use it and to display logo using function from Jetpack. This is cool in many ways, first of all this feature is reinvented in each theme and theme framework out there in so many wrong ways, even I do! Let me say for example that I will remove this feature from my themes and I'll use one from Jetpack and I will encourage users further to use Jetpack on every site, how can I be sure about Jetpack future?

Why this isn't shipped with WordPress? It does belong to WordPress for sure, right in general settings near Site Title, this feature is critical almost for every website.

PS. this question is not only about site logo, but this way it was shorter and clearer to explain.

More to come!
Nicolae.

[1]: http://jetpack.me/support/site-logo/

**Comment by jeherve** [comment]
> On our end, if the feature proves popular on WordPress.com and in Jetpack, I'm sure we'll end up opening a ticket and proposing the feature for core, if you don't beat us to it. :)

Closing this issue as Site Logo has now been proposed to Core:
https://core.trac.wordpress.org/ticket/33755
