### ISSUE TITLE
 Include conversion rate

### ISSUE THREAD

**Issue by brunoborges92** [Automattic/jetpack#12683]
Add the rate of conversion of the requests, since this is a very important information.

**Comment by jeherve** [comment]
Hi!

Could you give us more details about your request? Do you have a specific type of request in mind, or something specific you'd like to track within the Jetpack plugin?

Thank you!

**Comment by brunoborges92** [comment]
Hi! And I created it in woocommerce-admin, but I think in jetpack it would be easier because it already has the stasis of visitors on the site. Yes it would report to online store the conversion rate is the total number of orders divided by the number of sessions in a given period.

**Comment by jeherve** [comment]
> it would tell the online store that the conversion rate is the total number of requests divided by the number of sessions in a given period.

You should be able to get that information if you were to activate Jetpack's Google Analytics feature and its Enhanced Ecommerce Tracking features. You can read more about it here:
https://jetpack.com/support/google-analytics/
