### ISSUE TITLE
Jetpack DNA: Properly publish packages that rely on other packages

### ISSUE THREAD

**Issue by tyxla** [Automattic/jetpack#12680]
#### Is your feature request related to a problem? Please describe.
We have several packages that have other packages as dependencies. That sometimes also leads to a chain of dependencies For example:

* `sync` relies on `options`.
* `options` relies on `constants`.

Currently, in each of those packages, and in Jetpack itself, we depend just on the `@dev` version. This works great for development, as we always use the latest version of the package, regardless of the branch we're working in.

However, this will be a problem once we publish one of those packages with internal dependencies. Imagine we want to use `sync` and `connection` in VaultPress. Both of those packages have other packages as dependencies, but have `@dev`. This opens several problems:

* Where and how will `sync` find the `options` (and thus, `constants`) package? It obviously won't be in VP, unless we require it specifically.
* Which version of `sync` do we want to use in VP?
* Which version of `options` (and thus, `constants`) do we want to use in VP?

#### Describe the solution you'd like
**Main suggestion:** We could consider starting to maintain the `version` property in each package's `composer.json`, and make sure to keep it up to date with the releases. Ideally, all of this would be automated.

#### Describe alternatives you've considered

**Alternative 1:** when publishing packages with package dependencies, we can update and expand the publishing script and follow some guidelines:

* We will be aiming to prepare and publish packages in a specific order:
  * Packages without package dependencies (let's call them 1st class packages)
  * Packages with 1st class package dependencies (let's call them 2nd class packages)
  * Packages with 2nd class package dependencies
  * and so on...
* Package publishing script creates a commit to change `@dev` for each dependency in `composer.json` to the latest package version, inferred from the current tags in the Jetpack repo.
* After that commit is pushed, we release the new package, so the tagged version will have proper dependencies.
* Once we're done with releasing all packages, we revert those commits, in order to be able to develop with the latest version of each package (`@dev`).

**Alternative 2 (hacky):**

VP could have a manual list of repos (the mirrors), and list all the dependency tree specifically as `@dev` or `dev-master`, so VP would end up always using the latest package master.

While this guarantees that a stable version will be used, we wouldn't know which version it is, because it'll be just `@dev` or `dev-master`. That would make it pretty terrible for debugging and iteration.

Any other alternatives you can think about, @Automattic/jetpack-dna ?

#### Additional context
Part of the Jetpack DNA project - p1HpG7-70O-p2

**Comment by zinigor** [comment]
Thanks for forming your concerns in the form of an issue, this really helps!

I see the problem you're describing, and it's especially serious now, when most of the parts that depend on each other are moving very fast. I like your first alternative, but with several changes.

When reading what you have described, it struck me that it's similar to what package managers do when they need to figure out the dependency tree and correct versions to use. So here I guess comes the real test: we need to be able to run the monorepo in such a way that:
- each package can clearly define their dependencies in a semver-compatible way;
- and be able to receive the version it needs from the package repository, not from the monorepo.

In my opinion, that will make sure we're using development and release practices that are suitable for third party consumers of Jetpack packages as well. Because we will also be consuming them the way all others are.

Do you think that would work?

**Comment by tyxla** [comment]
TBH, I'm not very sure which one would work, I just outlined the main idea I had, plus 2 alternative ones, just in case one of them could be useful. We should try different things and choose what works best for us.

**Comment by dereksmart** [comment]
I imagined a solution like: 
- Jetpack GitHub repo (master and dev branches) always runs `@dev` versions of it's own monorepo packages. 
- For each Jetpack release, we publish all of the packages to Packagist, and update the *release branch* composer.json to use those versions. 

This way our production Jetpack will always be running with versioned, public, and published packages just like other plugins that consume them. 

It will take either some effort in scripting or manual effort or both, but it feels clean enough to me.

**Comment by gravityrail** [comment]
That solution sounds good to me.

**Comment by jeherve** [comment]
#13382 shows a different problem the reliance of `@dev` creates:

> Composer install of 7.6 fails due to reliance on dev package

**Comment by jeherve** [comment]
This can now be closed, as it was handled via Changelogger and the autotagger tool added in #19192. Our packages' stable versions now always rely on stable packages.
