### ISSUE TITLE
Jetpack Sync Package: name-spaced classes for sync module

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#12712]
Each module in the Jetpack sync package needs a name-spaced class, [like the attachments and callable modules for example](https://github.com/Automattic/jetpack/tree/master/packages/sync/src/modules).

Please assign yourself a module by writing your github username next to the corresponding module in the list:

- [x] Attachments @tyxla https://github.com/Automattic/jetpack/pull/12707
- [x] Callables @tyxla https://github.com/Automattic/jetpack/pull/12710
- [x] Comments @gititon https://github.com/Automattic/jetpack/pull/12734
- [x] Constants @gititon https://github.com/Automattic/jetpack/pull/12769
- [x] Full Sync @gititon https://github.com/Automattic/jetpack/pull/12768
- [x] Import @gititon https://github.com/Automattic/jetpack/pull/12740
- [x] Menus @gititon https://github.com/Automattic/jetpack/pull/12743
- [x] Meta @tyxla https://github.com/Automattic/jetpack/pull/12724
- [x] Network Options @roccotripaldi #12766
- [x] Options @roccotripaldi #12736
- [x] Plugins @roccotripaldi #12726
- [x] Posts @gititon https://github.com/Automattic/jetpack/pull/12735
- [x] Protect @roccotripaldi #12816
- [x] Stats @gititon https://github.com/Automattic/jetpack/pull/12742
- [x] Terms @tyxla #12725 
- [x] Themes @roccotripaldi #12737
- [x] Updates @gititon https://github.com/Automattic/jetpack/pull/12746
- [x] Users @roccotripaldi #12737
- [x] Woo Commerce @gititon https://github.com/Automattic/jetpack/pull/12772
- [x] WP Super Cache @lezama https://github.com/Automattic/jetpack/pull/12722

**Comment by gravityrail** [comment]
Nice work! This is done.
