### ISSUE TITLE
Switching WP lang to ru_RU breaks JP admin CSS

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#1275]
To reproduce:

1- Set WP to English, install and activate JP.
2- Install Russian language file and switch to it.
3- Your Jetpack admin pages don't look quite right. Screenshot below.

Notice the module names are no longer linked, and the vertical separators are visible. If you hover over a module, a third link appears (which I think translates to "Module Information") but when you click it, nothing happens.

http://d.pr/i/VVqE.png

In the browser console, you see this:

`Uncaught SyntaxError: Unexpected token ;`

... so when you look at the source of the page, here's the issue:

```html
<script type='text/javascript'>
/* <![CDATA[ */
var jetpackModulesData = ;
/* ]]> */
</script>
```

On a working site, `jetpackModulesData` would contain all the module data.

(issue 1987560-t)

**Comment by richardmtl** [comment]
@aheckler can you still repro since #1437 was merged? If not, close this one, then? :)

**Comment by aheckler** [comment]
WFM now, closing.
