### ISSUE TITLE
Sync: namespace all the sync core classes

### ISSUE THREAD

**Issue by tyxla** [Automattic/jetpack#12751]
Each core class in the Jetpack sync package needs a name-spaced class, just like we are doing for the sync modules in #12712.

This is part of the strategy to namespace and autoload the entire sync package with PSR-4.

Please assign yourself a module by writing your github username next to the corresponding module in the list:

- [x] Actions @tyxla #12783
- [x] Defaults @gititon https://github.com/Automattic/jetpack/pull/12790
- [x] Functions @gititon https://github.com/Automattic/jetpack/pull/12793
- [x] JSON_Deflate_Array_Codec @gititon https://github.com/Automattic/jetpack/pull/12795
- [x] Listener @tyxla #12762
- [x] Main @gititon https://github.com/Automattic/jetpack/pull/12797
- [x] Modules @gititon https://github.com/Automattic/jetpack/pull/12798
- [x] Queue @tyxla #12756
- [x] Queue_Buffer @tyxla #12756
- [x] Utils @tyxla #12756
- [x] Sender @tyxla #12729
- [x] Server @tyxla #12750
- [x] Settings @gititon https://github.com/Automattic/jetpack/pull/12789
- [x] Simple_Codec @gititon https://github.com/Automattic/jetpack/pull/12799
- [x] Users @gititon https://github.com/Automattic/jetpack/pull/12800
- [x] WP_Replicastore @gititon https://github.com/Automattic/jetpack/pull/12802
- [x] Codec interface @tyxla #12760
- [x] Replicastore interface @gititon https://github.com/Automattic/jetpack/pull/12802

**Comment by gravityrail** [comment]
This is completed!
