### ISSUE TITLE
Jetpack: Fatal error for logged in users using Jetpack after Version 7.2.1.1 and Thrive Apprentice, Version 2.1.8.3

### ISSUE THREAD

**Issue by dkmyta** [Automattic/jetpack#12770]
A user is reporting fatal errors for any logged-in user for anything that is after Jetpack 7.2.1.1 with the latest version of Thrive Apprentice, Version 2.1.8.3.

Similar but unique to the report here: #11788

User has disabled everything except for Jetpack (v7.4) and Thrive Apprentice using default Twenty Nineteen theme, running Wordpress 5.2.2 and PHP 7.3 and the issue persists.

User uses the Thrive Product Manager plug-in to install but believes it requires my personal login due to the site license. They have tried attaching the ZIP file to this email, but it was blocked due to security reasons.

User will continue to look into options for getting us a copy of the plugin for testing purposes.

Ticket/Forum/Chat: 2119037-zen

**Comment by jeherve** [comment]
Would it be possible to enable debugging mode on the site to learn more about what's causing the fatal error exactly?
https://gist.github.com/jeherve/57cc50246aab776e110060926a2face2

**Comment by dkmyta** [comment]
Requested they enable debugging mode as requested via the steps outlined in the provided link and they will report back once complete.

**Comment by gsmumbo** [comment]
User sent over their debug log in 2119037-zen

**Comment by jeherve** [comment]
That's helpful, thank you.

```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Jetpack_Subscriptions::comment_subscribe_init(), 1 passed in wp-includes/class-wp-hook.php on line 286 and exactly 2 expected in wp-content/plugins/jetpack/modules/subscriptions.php:602
```

This points us to the `comment_form_submit_field` filter, used by Jetpack to add elements to the Comment form's submit form. That filter expects 2 arguments:
https://developer.wordpress.org/reference/hooks/comment_form_submit_field/

Jetpack does pass the 2 arguments as expected, but another plugin on the site also uses the filter and does not pass the 2 arguments. As a result, that plugin causes issues with all other plugins (like Jetpack) that rely on the filter.

I would consequently recommend that the site owner gets in touch with the Thrive Apprentice authors and ask them to audit their use of the `comment_form_submit_field` filter; they will want to make sure they pass 2 arguments to any function that is hooked to that filter.
