### ISSUE TITLE
Simple Payments block: unable to edit settings using Code Editor

### ISSUE THREAD

**Issue by tbradsha** [Automattic/jetpack#12774]
#### Steps to reproduce the issue

1. Create a Simple Payments block.
2. Switch to the Code Editor.
3. Change the block settings in the markup (e.g. the price).
4. Publish or switch to Visual Editor.

#### What I expected
The block settings would update whether in the Code Editor or Visual Editor.

#### What happened instead
The block settings only update if in the Visual Editor.

**Comment by jeherve** [comment]
Closing as duplicate of #13709
