### ISSUE TITLE
devicepx script is causing some admin screen breakage

### ISSUE THREAD

**Issue by DrewAPicture** [Automattic/jetpack#1278]
WordPress: 4.0.0
JetPack: 3.1.1, 3.2 (didn't test earlier versions)

A client reported (and I confirmed) some breakage on admin screens for Gravity Forms related to the devicepx script, due to `document.body` being null. @georgestephanis was able to track down the error in the unminified source to [L#260](https://gist.github.com/georgestephanis/9ab16296052cce73c451#file-devicepx-jetpack-js-L260).

The error as reported against the minified source in FF 33.0.2 was:

```
TypeError: document.body is null
http://s0.wp.com/wp-content/js/devicepx-jetpack.js?ver=201445
Line 7
```

Latest Chrome is also tossing "Can't read property 'style' of null"

**Comment by DrewAPicture** [comment]
@georgestephanis Any follow up here? Still seeing this issue w/ Jetpack 3.3.

**Comment by zinigor** [comment]
Let's look at this in relation to Core's responsive images feature.

**Comment by kraftbj** [comment]
Related: #2918 (tracking ticket for HiDPI and srcset)

**Comment by kraftbj** [comment]
I couldn't immediately duplicate, but `devicepx` is now behind a theme support flag anyhow. It shouldn't be used. It doesn't work on modern versions of browsers.
