### ISSUE TITLE
Site Icon: add more parameters to make site tile compatible with Windows Phones

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1279]
The `msapplication-TileImage` tag added by the Site Icon module doesn't seem to be enough to create a tile on WIndows Phones. Compare the tile at the bottom, center of the phone (created from a site using Jetpack's Site Icon) to the tile at the bottom left (created from [this site](http://www.neowin.net/))

![wp_ss_20141107_0001](https://cloud.githubusercontent.com/assets/426388/4959641/569c0434-66ba-11e4-900a-398a681e9643.png)

The site where Windows Phone Tiles work includes other tags:

```html
<meta name="msapplication-TileColor" content="#1e5078">
  <meta name="msapplication-TileImage" content="/images/orion/icons/mstile-144x144.png">
  <meta name="msapplication-config" content="/images/orion/icons/browserconfig.xml">
```

Following the steps on [Windows's official site](http://www.buildmypinnedsite.com/en), it seems that both the color code and the `msapplication-TileImage` tag are needed. The `browserconfig.xml` is only there to provide extra image sizes. Here is the content of the file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<browserconfig>
  <msapplication>
    <tile>
      <square70x70logo src="/images/orion/icons/mstile-70x70.png"/>
      <square150x150logo src="/images/orion/icons/mstile-150x150.png"/>
      <square310x310logo src="/images/orion/icons/mstile-310x310.png"/>
      <wide310x150logo src="/images/orion/icons/mstile-310x150.png"/>
      <TileColor>#1e5078</TileColor>
    </tile>
  </msapplication>
</browserconfig>
```

Would it be worth trying to sample the Site Icon with `Tonesque`, and automatically create a color tag?

**Comment by RehanSaeed** [comment]
Windows tiles can show items from the RSS feed too which is a few extra lines of XML. See https://github.com/Automattic/jetpack/issues/2204.

**Comment by kraftbj** [comment]
Tile Image moved to Core, so Jetpack could add the color and/or manifest file for the added fun. Could be a cool usage of Tonesque. A check on has_site_icon and add it to the wp_head automatically?

**Comment by dereksmart** [comment]
Site Icon lives in core now
