### ISSUE TITLE
Jetpack Related Posts - suggested accessibility improvements

### ISSUE THREAD

**Issue by abrightclearweb** [Automattic/jetpack#12811]
#### Steps to reproduce the issue

1. Enable Jetpack Related Posts module.
2. Use NVDA screen reader to read out the content in the Related section. I used it on this post: https://www.abrightclearweb.com/accessibility-testing-wordpress-gutenberg-first-look/.

#### What happened 

Because the image link and title link are separate, and both have title attributes, this is what is read out to a screen reader user:

The User Experience and Accessibility of Gutenberg (The WordPress 5.0 Block Editor)
graphic
visited  link  The User Experience and Accessibility of Gutenberg (The WordPress 5.0 Block Editor) As WordPress 5.0 launches today, with a new block editor, it seems timely to revisit this presentation I gave at WordCamp Edinburgh 2018 on 17 November. This was the talk description: The new Gutenberg editor is a key part of WordPress 5.0 which is going to change the user experience…
The User Experience and Accessibility of Gutenberg (The WordPress 5.0 Block Editor)
visited  link  The User Experience and Accessibility of Gutenberg (The WordPress 5.0 Block Editor) As WordPress 5.0 launches today, with a new block editor, it seems timely to revisit this presentation I gave at WordCamp Edinburgh 2018 on 17 November. This was the talk description: The new Gutenberg editor is a key part of WordPress 5.0 which is going to change the user experience…
heading  level 4

This is verbose, and duplicates information. It's also two links to tab through instead of one.

Also, the **Related** is a h3 and post title an h4. On my post, it looks as if the Related part is a subsection of h2 **Have your say**. If there were no subheadings in this post and just the post title, there would be a skipped heading level.

**Suggestions for improvement**

Combine the image link and post title link into one link, as suggested here: https://www.w3.org/TR/WCAG20-TECHS/H2.html. Have null alt text on the image (`alt="")`. Consider not having the post titles as headings - see the _Link block level elements with care_ section of https://www.filamentgroup.com/lab/a11y-links.html.

Remove the title attributes: they are redundant.

Make the **Related** heading an h2, and the post titles `<span>`. Adjust CSS as necessary.

**Comment by scottsweb** [comment]
I have opened a PR to make improvements: https://github.com/Automattic/jetpack/pull/16088

It doesn't address all your issues @abrightclearweb as we need to be careful with backwards compatibility. There is a link in the PR which details how to do advanced customisation of the related posts feature. This will help you if you wish to improve things further.
