### ISSUE TITLE
Country Stats display "Vietnam" as "Viet Nam"

### ISSUE THREAD

**Issue by mpeshev** [Automattic/jetpack#1283]
While checking the daily stats of a blog, I found out that Vietnam was displayed as "Viet Nam" instead.

![vietnam](https://cloud.githubusercontent.com/assets/328189/4965344/80a51f28-6790-11e4-8922-819fd3e46f06.png)

**Comment by vanquang9387** [comment]
I'm Vietnamese. Both "Vietnam" and "Viet Nam" are alright.

**Comment by AjkP** [comment]
@vanquang9387 @mpeshev Should this get closed then?

**Comment by vanquang9387** [comment]
@AjkP I think this issue can be closed.
"Viet Nam" has been confirmed by ISO
https://www.iso.org/obp/ui/#iso:code:3166:VN

**Comment by kraftbj** [comment]
Thanks @vanquang9387 for confirming. Closing.
