### ISSUE TITLE
Compat for \Jetpack_Client::_wp_remote_request($url, $args, $set_fallback)

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#12853]
This is used externally and we should make sure it still works.

**Comment by dereksmart** [comment]
This was merged to feature branch in d0bf799ec448e15c9a73080998498276977ccd62

**Comment by eliorivero** [comment]
Done in https://github.com/Automattic/jetpack/pull/12857/files#diff-4cc971fa470c8d9acd5851b284e03d7aR15
