### ISSUE TITLE
Jetpack Sharing & Likes button request to apply WCAG 2.1 style and functionality standards

### ISSUE THREAD

**Issue by dkmyta** [Automattic/jetpack#12866]
A user has reached out in 2120307-zen outlining accessibility issues specific to the Facebook and Twitter sharing buttons, as well as the Likes button (among potential others).

The issues in general are:

* Poor focus indicators (Twitter and Facebook, and the Like button)

* Poor hover indicators (Twitter and Facebook, and the Like button)

* Poor color contrast on icons (Twitter, and the Like button)

* Text does not zoom with Text-only zoom (Twitter and Facebook, and the Like button)

* The Twitter Widget also has a blue hover state on the Share and Twitter icons, and a red hover state on the Like (heart) icon. These are also poor contrast.

They have requested that we apply the Web Content Accessibility Guidelines (WCAG) 2.1 
standards to these modules to resolve the issues as per: https://www.w3.org/TR/WCAG21/

They have also provided this link they believe will be helpful in addressing the above indications: https://www.w3.org/WAI/GL/wiki/Using_the_WAI-ARIA_aria-expanded_state_to_mark_expandable_and_collapsible_regions

They request these standards be applied to make the modules properly accessible for people with disabilities, as they are bound by Section 508 of the 1973 Rehabilitation Act.

**Comment by TechThomas** [comment]
This issue affects our site at https://equalentry.com as well. Any updates on the status on this one?

**Comment by jeherve** [comment]
> Any updates on the status on this one?

We haven't made any progress on this, but we'll update this issue as soon as we get started on this.

The issue is also labelled as "Good For Community", so anyone interested is welcome to contribute a patch for this, we'll be happy to review it!
