### ISSUE TITLE
Sharing: "Open in the same window" option doesn't work

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1288]
Steps to reproduce:

1. Enable the Sharing module
2. Go to Settings > Sharing, set up some non-official buttons
3. Choose to open the links in the same window
4. Save your changes
5. Visit a post, click on a sharing button
    - The sharing form opens in a new window

Since we use `js_dialog` ([ref](https://github.com/Automattic/jetpack/blob/3.2/modules/sharedaddy/sharing-sources.php#L164)) to overwrite the default link behaviour for each one of the buttons, it doesn't matter whether `target="_blank"` is set in the link ([ref](https://github.com/Automattic/jetpack/blob/3.2/modules/sharedaddy/sharing-sources.php#L1092)).

Should we add a "target" option to `js_dialog` to allow links to open in the same window?

Reported here:
- https://wordpress.org/support/topic/open-sharing-buttons-in-a-new-window-not-tab?replies=1

**Comment by dereksmart** [comment]
@georgestephanis does #1519 make sense?

**Comment by georgestephanis** [comment]
@dereksmart I don't think so, as the point of this (and I know @jeherve will correct me if I'm wrong) is to have them all open in the same popup rather than a new popup per share?  I think?

**Comment by dereksmart** [comment]
Hm, will wait for JH to respond with what expected behavior should be.

**Comment by jeherve** [comment]
> have them all open in the same popup rather than a new popup per share

That's a good point. I never thought about it this way.

![screen shot 2015-01-20 at 9 03 55 am](https://cloud.githubusercontent.com/assets/426388/5813769/4d8198a2-a083-11e4-900a-d1d70b140e07.png)

@beaulebens worked on the original Sharing plugin so he would know what the expected behaviour is:
- When choosing "Same Window", clicking on a sharing button makes you leave the post and open the sharing dialog in that window.
- When choosing "Same Window", clicking on a sharing button opens a new pop up, but then clicking on another sharing button changes the content of that pop up to load another social network dialog.

**Comment by dereksmart** [comment]
It would make sense if "same window" acted like the former, and "new window" acted like the latter, as I think it's fair to say if they click on a second sharing button before sending the first, they don't want the first one still floating around.

**Comment by dereksmart** [comment]
@georgestephanis, @jeherve how does this work for y'all? 
41c2e2d

**Comment by georgestephanis** [comment]
I'd prefer to wait and get @beaulebens take on it before merging either direction.

**Comment by beaulebens** [comment]
It's been a while, but I believe the original intent was as @jeherve outlined (but I think you mean "New window" in the second bullet?).

I think a lot of services assume/only really provide UI that makes sense within a popup now though don't they? Maybe we can/should just simplify it and ONLY provide the "new window" approach (and thus remove/ignore this option entirely?)

**Comment by samhotchkiss** [comment]
The advantage of "same window" is that you could then overwrite it with your own JS

What if we ditched the option and made it a filterable thing?

**Comment by beaulebens** [comment]
That'd work for me. On WP.com, since people can't filter, and since the most sensible option in that case is New Window, we should default it to that.

**Comment by samhotchkiss** [comment]
How clever is that?  @dereksmart, want to take another swing?

**Comment by dereksmart** [comment]
:+1: updated PR

**Comment by qant** [comment]
Where is exactly those options? Cos after update i get links opened in new tabs

**Comment by jeherve** [comment]
@qant We've removed those options from Jetpack in version 3.4, in January of last year.

> after update i get links opened in new tabs

That's the expected behaviour. Links always opened new tabs, even before we removed the option.

If you think something isn't behaving as usual on your site, could you send us an email with more details about your site so we can take a look?
http://jetpack.me/contact-support/

Thanks!
