### ISSUE TITLE
Banner Prompt to schedule Concierge, but Concierge is closed

### ISSUE THREAD

**Issue by kristinaplauche** [Automattic/jetpack#12888]
I just enabled a Jetpack professional plan on one of my self-hosted sites. I see a prompt to schedule a concierge call? :grimacing: I don't see it listed as an issue in GH under jpop-issues. Is this known? Is there somewhere else I should look and report this?  https://cld.wthms.co/qg8RLP
#### Steps to reproduce the issue

1. Jetpack installed on self-hosted site.
2. Upgraded to professional plan.
3. Wp-admin Dashboard banner prompt tells me I can schedule a Concierge call, but [Concierge is closed.](https://jetpackp2.wordpress.com/2019/04/18/happiness-pausing-livechat-and-concierge/#comment-31766)
![screenshot](https://cld.wthms.co/qg8RLP+)
Image link: https://cld.wthms.co/qg8RLP

#### What I expected

I expected to NOT be prompted to schedule a call for Concierge. 
#### What happened instead
I saw a banner prompting me to schedule a call with Concierge, which is closed.

**Screenshots**

**Comment by gravityrail** [comment]
Fixed in D29905-wpcom

**Comment by gravityrail** [comment]
Fix deployed in r193610-wpcom

**Comment by kristinaplauche** [comment]
Looks good. Thanks!
