### ISSUE TITLE
Debugger / Site Health Displaying False-Positive Errors

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#12881]
#### Purpose of this GitHub issue 

- Gather sites/reports with the error in Site Health (WP Admin dashboard) but there is no issue with any Jetpack feature or https://jetpack.com/support/debug/.
- After that, we will troubleshoot and improve our debugger in WP Admin.  

#### Details of the issue. 

- In WP Admin -> Tools -> Site Health, you're seeing a Jetpack error like the following. 

![0cb8ff40c8f9b125efddbb54ce7f727e](https://user-images.githubusercontent.com/10045087/60251273-87c18a80-98c8-11e9-88c2-0833a77f21b8.png)

- When checking your site staus in https://jetpack.com/support/debug/ , it's still showing `Everything looks great!`. 

#### What to report 

- Jetpack Debug status (do not need to post the JPDB link).
- Site ID (blog_id) (optional for Automattic Happiness Engineers)
- In WP Admin -> Tools -> Site Health -> Info -> Scoll down to "Jetpack" -> Send us "Connection Tests" info 

### Other info 

Originally in 3927-gh-jpop-issues

**Comment by jeremypaavola** [comment]
**Ticket**: 2169467-zen
**Jetpack debug**: [Everything looks great!](https://jetpack.com/support/debug/?url=https%3A%2F%2Fwww.allindiandjsdrive.in%2F)
**Site URL**: https://www.allindiandjsdrive.in/
**Site ID**: 148793315
**Connection test**:

```
cxn_tests: {"9":{"name":"test__wpcom_self_test","pass":false,"message":"Jetpack.com detected an error.","resolution":"Visit the Jetpack.com debugging page for more information or contact support.","action":false,"severity":"critical","group":["default"],"type":"direct"}}
```

**Comment by ntpixels** [comment]
Ticket: 2202245-zen
Jetpack debug: [Everything looks great!](https://jetpack.com/support/debug/?url=https%3A%2F%2Ftheartacademy.net)
Site URL: https://theartacademy.net
Site ID: 164759548
Connection test:

`cxn_tests: {"9":{"name":"test__wpcom_self_test","pass":false,"message":"Jetpack.com detected an error.","resolution":"Visit the Jetpack.com debugging page for more information or contact support.","action":false,"severity":"critical","group":["default"],"type":"direct"}}`

**Comment by pranali333** [comment]
Ticket: 2213829-zen
Jetpack debug: [Everything looks great!](https://jetpack.com/support/debug/?url=https%3A%2F%2Fpokemonnewspaper.com.au%2F)
URL: https://pokemonnewspaper.com.au/ 
Site ID: 163415962
Connection test:

`cxn_tests: {"9":{"name":"test__wpcom_self_test","pass":false,"message":"Jetpack.com detected an error.","resolution":"Visit the Jetpack.com debugging page for more information or contact support.","action":false,"severity":"critical","group":["default"],"type":"direct"}}`

**Comment by htdat** [comment]
Tix: 2250241-zen
Jetpack debug: Everything looks great!
Site ID: 158699724

```
cxn_tests: {"9":{"name":"test__wpcom_self_test","pass":false,"message":"Jetpack.com detect\u00f3 un error.","resolution":"Visita la p\u00e1gina de depuraci\u00f3n de Jetpack.com para m\u00e1s informaci\u00f3n o contactar con soporte.","action":false,"severity":"critical","group":["default"],"type":"direct"}}
```

**Comment by a8ck3n** [comment]
Ticket: https://woothemes.zendesk.com/agent/tickets/2254863
Jetpack debug is good.
Site ID: 41160620

```
cxn_tests: {'9':{'name':'test__wpcom_self_test','pass':false,'message':'Jetpack.com detected an error.','resolution':'Visit the Jetpack.com debugging page for more information or contact support.','action':false,'severity':'critical','group':['default'],'type':'direct'}}
```

**Comment by dericleeyy** [comment]
Ticket: 2272084-zen

Jetpack Debug is good.

Site ID: 155898264

```
cxn_tests: {"9":{"name":"test__wpcom_self_test","pass":false,"message":"Jetpack.com detected an error.","resolution":"Visit the Jetpack.com debugging page for more information or contact support.","action":false,"severity":"critical","group":["default"],"type":"direct"}}
```

**Comment by htdat** [comment]
2290973-zen
Jetpack Debug is good.
Site ID: 120401281

```
cxn_tests: {"9":{"name":"test__wpcom_self_test","pass":false,"message":"Jetpack.com detected an error.","resolution":"Visit the Jetpack.com debugging page for more information or contact support.","action":false,"severity":"critical","group":["default"],"type":"direct"}}
```

**Comment by jeremypaavola** [comment]
2299364-zen
Jetpack Debug is good
Site ID: 165021488

```
cxn_tests: {"9":{"name":"test__wpcom_self_test","pass":false,"message":"Jetpack.com detected an error.","resolution":"Visit the Jetpack.com debugging page for more information or contact support.","action":false,"severity":"critical","group":["default"],"type":"direct"}}
```

**Comment by coder-karen** [comment]
2290680-zen 
Jetpack Debug is good
Site ID: 143332086

```
cxn_tests: {"9":{"name":"test__wpcom_self_test","pass":false,"message":"Jetpack.com detected an error.","resolution":"Visit the Jetpack.com debugging page for more information or contact support.","action":false,"severity":"critical","group":["default"],"type":"direct"}}
```

**Comment by lizthefair** [comment]
Ticket:  2312741-zen
Jetpack Debug status: Everything looks great!
Site ID (blog_id): 82368205

` cxn_tests: {"9":{"name":"test__wpcom_self_test","pass":false,"message":"Jetpack.com detected an error.","resolution":"Visit the Jetpack.com debugging page for more information or contact support.","action":false,"severity":"critical","group":["default"],"type":"direct"}}`

**Comment by jeremypaavola** [comment]
Ticket: 2317282
Jetpack Debug: [Everything looks great!](https://jetpack.com/support/debug/?url=https%3A%2F%2Fwww.politikaperu.org%2F)
Site ID: 103873295
Connected via REST.

```
cxn_tests: 
{'9':{'name':'test__wpcom_self_test','pass':false,'message':'Jetpack.com 
detectu00f3 un error.','resolution':'Visita la pu00e1gina de depuraciu00f3n de 
Jetpack.com para mu00e1s informaciu00f3n o contactar con 
soporte.','action':false,'severity':'critical','group':['default'],'type':'direct'}}
```

**Comment by aheckler** [comment]
2318941-zen
Debug OK: https://jetpack.com/support/debug/?url=https%3A%2F%2Fthebroodle.com%2F
Site ID: 67178716
Connected via REST
`cxn_tests: {"9":{"name":"test__wpcom_self_test","pass":false,"message":"Jetpack.com detected an error.","resolution":"Visit the Jetpack.com debugging page for more information or contact support.","action":false,"severity":"critical","group":["default"],"type":"direct"}}`

**Comment by htdat** [comment]
@aheckler and @jeremypaavola - Site ID and JPDB result are good enough. Avoid providing site URLs in this public issue ;)

**Comment by mdrovdahl** [comment]
Slack: https://a8c.slack.com/archives/C0CMN0V97/p1567620876088300
Debug OK
Site ID: 162042271
Connected via XML-RPC
`{"9":{"name":"test__wpcom_self_test","pass":false,"message":"Jetpack.com detected an error.","resolution":"Visit the Jetpack.com debugging page for more information or contact support.","action":false,"severity":"critical","group":["default"],"type":"direct"}}`

**Comment by htdat** [comment]
Updating the priority to `[Pri] Normal` as we have more and more reports.

**Comment by jeremypaavola** [comment]
2328536-zen
Debug OK
Site ID: 112133580
Connected via REST
`
cxn_tests: {"9":{"name":"test__wpcom_self_test","pass":false,"message":"Jetpack.com detected an error.","resolution":"Visit the Jetpack.com debugging page for more information or contact support.","action":false,"severity":"critical","group":["default"],"type":"direct"}}
`

**Comment by jeremypaavola** [comment]
2329845-zen
Debug: 503 due to a CF block on /xmlrpc.php?for=jetpack (but not on /xmlrpc.php)
Site ID: 103947952
Connected via XML-RPC (but not really)
`{'9':{'name':'test__wpcom_self_test','pass':false,'message':'Jetpack.com 
detected an error.','resolution':'Visit the Jetpack.com debugging page for more 
information or contact 
support.','action':false,'severity':'critical','group':['default'],'type':'direct'}}`

**Comment by jeremypaavola** [comment]
324579-zen
Debug: OK
Site ID: 137516216
Connected via XML-RPC
`cxn_tests: All Pass.`

**Comment by aheckler** [comment]
2328310-zen
ID: 121282792
Debug: OK
Connected via REST.
`cxn_tests: {"7":{"name":"test__wpcom_connection_test","pass":false,"message":"blue dirt girl - original indie band from vancouver is not connected.: 200","resolution":"Please contact Jetpack support.","action":false,"severity":"critical","group":["default"],"type":"direct"}}`

**Comment by juliasydnor** [comment]
Ticket: 2343601-zen
ID: 162687667
Debug: OK

```
Connection Tests {"9":{"name":"test__wpcom_self_test","pass":false,"message":"Jetpack.com a d\u00e9tect\u00e9 une erreur.","resolution":"Visitez la page de d\u00e9bogage de Jetpack.com pour en savoir plus ou contactez l'assistance.","action":false,"severity":"critical","group":["default"],"type":"direct"}}
```

**Comment by jeremypaavola** [comment]
2341843-zen
Debug: OK
Site ID: 151135806
`{'9':{'name':'test__wpcom_self_test','pass':false,'message':'Jetpack.com detected an error.','resolution':'Visit the Jetpack.com debugging page for more information or contact support.','action':false,'severity':'critical','group':['default'],'type':'direct'}}`

**Comment by chaselivingston** [comment]
2360289-zen
Debug ok
Site ID: 137938645
```
Connection Tests

{"9":{"name":"test__wpcom_self_test","pass":false,"message":"Jetpack.com detected an error.","resolution":"Visit the Jetpack.com debugging page for more information or contact support.","action":false,"severity":"critical","group":["default"],"type":"direct"}}
```

**Comment by kraftbj** [comment]
I'd like to see if we can break up this issue some.

`test__wpcom_self_test` -- this is the same as when the SELF test failed on the old in-plugin debugger. The Jetpack site pings wp.com and requests WP.com run the Jetpack debugger, then handles the response as long as it comes back within 30 seconds. If it takes longer than 30 seconds, it'll fail. A potential resolution is to provide a middle state ("Test did not respond in time.").

`test__wpcom_connection_test` -- this one is stating that the /jetpack-blogs/%d/test-connection endpoint did not think the site was connected. Maybe confirm the URLs are what is expected?

**Comment by cena** [comment]
238828-zen
JP DB: Everything looks great!
Site ID: 164977491

`cxn_tests: {"9":{"name":"test__wpcom_self_test","pass":false,"message":"Jetpack.com detected an error.","resolution":"Visit the Jetpack.com debugging page for more information or contact support.","action":false,"severity":"critical","group":["default"],"type":"direct"}}`

**Comment by jeremypaavola** [comment]
2401729-zen
Debug: OK
Site ID: 123989187
Connected via XML-RPC

`cxn_tests: {"9":{"name":"test__wpcom_self_test","pass":false,"message":"Jetpack.com detected an error.","resolution":"Visit the Jetpack.com debugging page for more information or contact support.","action":false,"severity":"critical","group":["default"],"type":"direct"}}`

**Comment by kraftbj** [comment]
For the purposes of the issue, I don't think we need any additional reports until sites are running 7.9 and we can determine if there are cases not covered by the existing fix.

**Comment by joendotcom** [comment]
2409631-zen
Everything looks great!
44649782

```
cxn_tests: {"9":{"name":"test__wpcom_self_test","pass":false,"message":"Jetpack.com detected an error.","resolution":"Visit the Jetpack.com debugging page for more information or contact support.","action":false,"severity":"critical","group":["default"],"type":"direct"}}
```

**Comment by RCowles** [comment]
Also reported in 2463999-zen, user on Jetpack 7.8.

**Comment by coder-karen** [comment]
User on 7.9, Site Health reports a curl 28 timeout error. All tests pass in the debugger.
2468476-zen

**Comment by kraftbj** [comment]
The loopback request mentioned in the ticket is from Core -- their site did not respond to a request to itself as expected ( https://github.com/WordPress/WordPress/blob/f1b5f2aa94c45aa087e96ac91ca53d241ee3146b/wp-admin/includes/class-wp-site-health.php#L1642 ).

The `http_request_failed` test means that their site did not get a response back from something within 10 seconds, but it isn't clear in the ticket from what.

All in all, I think that is the site debug working as expected. It isn't a false positive error -- loopback isn't working as expected and whatever the http request, it was expecting to get a response back within 10 seconds and didn't. That could indicate the test is expecting something too quickly or network issues between the Jetpack site and the server, etc. I think this site is just slow.

**Comment by tmmbecker** [comment]
2496139-zen 
JP 7.9.1
Debug is great. Self-test is failing.

**Comment by htdat** [comment]
2514574-zen
JP 7.9.1 
blog_id = 73509231
Debug is great. Self-test is failing.

**Comment by aicee** [comment]
2525376-zen
JP: 7.9.1
blog_id = 162706612
Debug is great. Self-test is failing.

**Comment by htdat** [comment]
@kraftbj - We're seeing more and more reports. Do you think we should report this in a separate issue?

**Comment by htdat** [comment]
2535860-zen
JP 8.0
blog_id = 157196708

**Comment by aicee** [comment]
2535296-zen
JP 7.9.1
blog_id = 51124069
Debug is great. Self-test is failing.

**Comment by madhattermattic** [comment]
2535251-zen
JP 8.0
Blog ID: 156763502
Debug is great. Self-test is failing.

**Comment by htdat** [comment]
2531506-zen
JP 8.0
Blog ID: 169763173
Debug is great. Self-test is failing.

**Comment by tmmbecker** [comment]
2534598-zen
Self-test is failing and user-facing debugger is showing `Could not fetch data`.
JP 8.0

**Comment by csonnek** [comment]
2540352-zen
JP 8.0
Self-test failing
Debug OK (both for Super admin and user-facing) - blog ID 169685843

**Comment by kraftbj** [comment]
Going to just not run the self test and moving forward with using the newer suite.

**Comment by bhoop** [comment]
2543967-zen
JP 8.0
Self-test failing
Debug is great

**Comment by kraftbj** [comment]
No need to keep reporting these.

**Comment by chaselivingston** [comment]
@kraftbj Just saw another instance of this in 2601672-zen using Jetpack 8.0. Should this still be happening or do you think there's a new problem?

**Comment by csonnek** [comment]
@kraftbj I have one in 2615740-zen as well. 

> The Site Health plugin is listing JetPack as having a Critical Issue.
> Specifically, it says, 'Jetpack.com detected an error on the WPcom Self Test.'
> When I click the link to debug it, it says, 'Debug Unknown error An unknown
> error has occurred.'

They're on 8.0 and the [debug](https://jetpack.com/support/debug/?url=https://www.unitedbypop.com/) is OK.

**Comment by kraftbj** [comment]
@chaselivingston & @csonnek Pulling out the old debugger is coming in Jetpack 8.1 and converting the server-side old debugger to use the new suite is pending review in D37439

**Comment by nielslange** [comment]
Another report in

17798236-zen
2630165-hc

**Comment by druesome** [comment]
Seeing this happening consistently in Atomic sites atm.  When running jetpack status, common error message is:

`test__wpcom_self_test: Jetpack.com detected an error on the WPcom Self Test.`

Disconnecting and reconnecting doesn't help.

2629897-zen

**Comment by kraftbj** [comment]
This issue should remain closed and any others should have a new ticket. The impacted test was removed in #14198, but that code didn't ship until 8.1 (today). If there are still issues, please confirm they are not running an older version. If they are running 8.1 or higher, please open a new issue as it is not related to this one since the test is no longer running by default (requires a filter to enable it currently).
