### ISSUE TITLE
Rewind credentials screen should not autofill the username and password

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#12893]
#### Steps to reproduce the issue

1. Go into the Rewind setup flow (https://wordpress.com/start/rewind-setup)
2. Click "Add your credentials"
3. FTP creds are autofilled with my stored WPCOM creds (for Chrome, and for LastPass)

#### What I expected
No autofill of these fields with WPCOM creds, inexperienced users are unlikely to realise that these should be diifferent credentials, obtained from their host

#### What happened instead
Credentials were autofilled

In addition, submitting the form offered to update my stored WPCOM credentials, which (again for a non-technical user) could have broken my ability to login to WPCOM my browser's password manager (Chrome 75 on Mac)

**Screenshots**

<img width="912" alt="autofill-credentials-page" src="https://user-images.githubusercontent.com/51896/60316681-76a46800-9920-11e9-9db5-13fed39fe9c7.png">

This also happens in Settings->Security->Backups, and overwrites the stored creds with my WPCOM creds.

<img width="676" alt="autofill-calypso" src="https://user-images.githubusercontent.com/51896/60317096-583f6c00-9922-11e9-85a1-d5ebf9058af5.png">

**Comment by simison** [comment]
Adding `autocomplete="off"` to these fields should fix the issue. cc @Automattic/chronos 

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by seear** [comment]
Thanks @simison! Although, reading further, we might require `autocomplete="new-password"`, because [browsers will ignore `autocomplete="off"`](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields) for username/password fields.

**Comment by singerb** [comment]
Yeah, `new-password` might be better. Also, this is why autofilling forms is a terrible idea that I always turn off.

**Comment by seear** [comment]
The `autocomplete` approaches seem to need a specific option set in LastPass for it to respect that property.

This fix uses `data-lpignore="true"` https://github.com/Automattic/wp-calypso/pull/34376.
