### ISSUE TITLE
Smoke test plugins that leverage Jetpack classes or functions to ensure DNA compat

### ISSUE THREAD

**Issue by gititon** [Automattic/jetpack#12908]
Smoke test plugins that leverage Jetpack classes or functions to ensure DNA compat.
  
  - [x] woocommerce => 4000000 (https://github.com/Automattic/jetpack/pull/12907/ addressed)
  - [x] woocommerce-services => 700000 (https://github.com/Automattic/jetpack/pull/12907/ addressed)
  - [x] accelerated-mobile-pages => 100000
  - [x] vaultpress => 80000
  - [x] tiled-gallery-carousel-without-jetpack => 30000
  - [x] carousel-without-jetpack => 20000
  - [x] slimjetpack => 10000 (Incompatible with Jetpack generally, also fatals)
  - [x] essential-content-types => 10000
  - [x] catch-gallery => 9000
  - [x] wp-native-articles => 6000 (Didn't setup Instant Articles with Facebook, but no errors upon installation or viewing posts)
  - [x] allfacebook-instant-articles => 3000 (Didn't setup Instant Articles with Facebook, but no errors upon installation or viewing posts)
  - [x] jetpack-module-control => 1000
  - [x] radcontrol => 1000
  - [x] amp-wp => 1000
  - [x] user-id-changer => 1000
  - [x] weeblramp => 800
  - [x] rest-api-post-embeds => 700
  - [x] connect-for-woocommerce => 20 (Could not find [specific plugin](view-source:http://jollycoder.ngrok.io/wp-admin/plugin-install.php?s=connect-for-woocommerce&tab=search&type=term) and there are apparently only 20 installs so I am skipping this one. Checking it off to signify that it's been considered).

Result of testing was https://github.com/Automattic/jetpack/pull/12907/

**Comment by gravityrail** [comment]
This appears to be done! (branch got merged)
