### ISSUE TITLE
Publicize: add wpas_force_publicize filter to Jetpack

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1290]
WordPress.com includes a filter, `wpas_force_publicize`, that allows you to force Publicize to be triggered again, as explained here:
http://vip.wordpress.com/documentation/customizing-publicize-sharing-behavior/#add-a-checkbox-to-send-new-post-updates-to-publicize

Unfortunately, that filter isn't available in Jetpack. It'd be nice to have a similar option for self-hosted sites.

Suggested here:
https://wordpress.org/support/topic/re-publish?replies=6

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/publicise-after-the-publish?replies=1&view=all

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/publish-post-social-media-in-editing-mode?replies=1&view=all

**Comment by timaschew** [comment]
+1

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/post-a-article-on-facebook?replies=1&view=all

**Comment by 108Bis** [comment]
I'm interesting for.

**Comment by jeherve** [comment]
Also suggested in 2675823-t

**Comment by artpi** [comment]
We introduced some changes to the API as part of "Republicize" project: p58i-41F-p2

**Comment by jeherve** [comment]
Closing this as this is now part of Republicize:
https://jetpack.com/support/publicize/#republicize
