### ISSUE TITLE
Feature Request: VideoPress Stats in WordPress.org Dashboard

### ISSUE THREAD

**Issue by EnigmaSolved** [Automattic/jetpack#1291]
Currently I believe the only way I can view my VideoPress stats (Impressions, Plays, etc.) is via WordPress.com (e.g., https://wordpress.com/my-stats/). It would be much more convenient if I could view these stats directly within my WordPress.org Dashboard.

I do not currently use WP.com Stats in Jetpack, so ideally the VideoPress Stats would be viewable/accessible in the .org Dashboard independent of the WP.com Jetpack Stats feature.

I suggest a multi-stage approach to adding this functionality:
1. Add links to https://wordpress.com/my-stats/ in appropriate places in the .org Dashboard, such as, Media->VideoPress page and Jetpack->VideoPress popup.
2. Add the following info (which is currently only viewable on the My Stats page in the Summary tab of the Video Plays panel) to the linkable Summaries page (https://wordpress.com/my-stats/?view=videoplays&summarize&numdays=7):
   
   > Aggregated stats for November, 2014
   > Impressions: ???
   > Plays: ???
   > Minutes: ???
   > Bandwidth: ??? MB
3. Update the links in the .org Dashboard to point to the above page.
4. Enable the .org Dashboard to just load the above page main content in an `iframe` so that everything stays within the .org Dashboard.

Thanks for considering my request!  :)
Sean

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
