### ISSUE TITLE
At a Glance: Site Stats needs better focus styling

### ISSUE THREAD

**Issue by crunnells** [Automattic/jetpack#12910]
When tabbing through the Dashboard > At a Glance page, the `:focus` styling needs help to better distinguish selected links from active links. This is present on both the period links (Days, Weeks, Months) as well as the bar graph links (which currently have no `:focus` styles, only `:hover`).

#### Steps to reproduce the issue

1. Go to Dashboard > At a Glance
2. Use the tab key to cycle through the site stat section
3. Note it's difficult to tell which link is currently selected

#### What I expected
Better focus styles

#### What happened instead
No/poor focus styles

**Screenshots**
<img width="1072" alt="Screen Shot 2019-06-28 at 12 21 43 PM" src="https://user-images.githubusercontent.com/4297811/60374378-e0178b80-999f-11e9-9822-db0da81e2ff9.png">
Can you tell which of these is active and which is selected?

**Comment by scottsweb** [comment]
Working on a PR for this
