### ISSUE TITLE
Publicize Connection setup flow severely broken for Jetpack customers (Calypso & wp-admin)

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#12929]
Hey y'all. I'm reporting a bunch of stuff since I found this all on a usability interview with a customer earlier today. Feel free to break this out into multiple PRs / issues. Some of this may exist in calypso while other parts in Jetpack (I'm not sure!).

Testing on a jurassic.ninja site running jetpack 7.5, and WP version 5.2.2 

### Two screen recordings of the issues so you can see everything outlined below

https://cloudup.com/cMk0sheXxEf

### 1) In Jetpack: "Connect your social media accounts" link goes to wrong place. Customers currently can't set this feature up.

When a customer clicks "Connect your social media accounts" link in the jetpack settings within wp-admin they're taken to https://wordpress.com/stats/day. They become lost and cannot get to the place they need to.

I actually can't even get to the page I need to either. See #3 down below!

![Screen Shot 2019-07-02 at 5 28 50 PM](https://user-images.githubusercontent.com/214813/60548415-087cee00-9cf0-11e9-87b1-1e530b19b0c8.png)

![Screen Shot 2019-07-02 at 5 29 03 PM](https://user-images.githubusercontent.com/214813/60548429-10d52900-9cf0-11e9-9b5a-c0fb44662543.png)

### 2) In Calypso: Traffic page is "only available to 3.4 or or higher with sharing mode activated."

![Screen Shot 2019-07-02 at 5 27 46 PM](https://user-images.githubusercontent.com/214813/60548633-8c36da80-9cf0-11e9-8b06-6a33068de459.png)

On `https://wordpress.com/marketing/traffic/[url]` I'm seeing this error message. I can see the page, but I still see an error that's confusing and has no actionable steps? As a customer I'm thinking "What's the sharing module?" "How do I turn it on?" I can see use this page however.

### 3) In Calypso: "Connection" tab disappears when sharing module is not enabled 

Inside calypso, the "connection" tab is not visible until a customer navigates back to wp-admin, enables it, and then returns to wordpress.com. Then it appears. 

![Screen Shot 2019-07-02 at 5 57 02 PM](https://user-images.githubusercontent.com/214813/60549541-34e63980-9cf3-11e9-958d-dcd5a31e46d0.png)

![Screen Shot 2019-07-02 at 5 57 10 PM](https://user-images.githubusercontent.com/214813/60549547-36affd00-9cf3-11e9-9e4c-dec6aff460ae.png)

Unless you're an experienced a12, no one is going to know how to do this to begin connecting their social accounts. 

We should have have "Connections" always be visible, with an empty page that allows customers to enable the sharing module.

Ideally, we always show the social media connections UI - the module should auto switch on the minute a customer clicks / taps "connect" on any of the buttons.

Tagging folks from all over to figure out who the most appropriate people to fix this are. At this point it feels nearly impossible to use this feature from the Jetpack side of things.

@jancavan @belcherj @Automattic/catalyst 
@MichaelArestad @dereksmart @jeherve @Automattic/jetpack 

Thank you everyone!

**Comment by jeherve** [comment]
> When a customer clicks "Connect your social media accounts" link in the jetpack settings within wp-admin they're taken to wordpress.com/stats/day. 

This tends to happen with new sites, right after the connection to WordPress.com. After a couple of minutes the problem disappears.

**Comment by jeherve** [comment]
> 2) In Calypso: Traffic page is "only available to 3.4 or or higher with sharing mode activated."

This is tracked here:

https://github.com/Automattic/wp-calypso/issues/34436

**Comment by jeherve** [comment]
> 3) In Calypso: "Connection" tab disappears when sharing module is not enabled

This is even more of a problem now that we do not automatically enable the module on connection.

Discussion about this is happening here:
https://github.com/Automattic/wp-calypso/issues/20102
https://github.com/Automattic/wp-calypso/issues/14808

**Comment by jeherve** [comment]
Since 2) and 3) are already tracked elsewhere, I would recommend creating a new issue to keep track of 1), to keep each problem focussed on its own issue.

Thank you!

**Comment by jeffgolenski** [comment]
@jeherve Done. Thanks for the quick response. 

Issue: https://github.com/Automattic/jetpack/issues/12937

**Comment by jeherve** [comment]
Thank you!
