### ISSUE TITLE
Feature Request: Store syndicated links

### ISSUE THREAD

**Issue by zdfs** [Automattic/jetpack#1292]
I think it would be very valuable for Jetpack to retrieve and expose the syndicated link. For example, I post something on my site, Jetpack syndicates it to Twitter and after Twitter creates the post, Jetpack grabs the Twitter permalink and stores it in my Wordpress DB. Creating some post meta information that we could expose in our templates would be ideal.

**Comment by jkudish** [comment]
Some improvements for this are in the works. Stay tuned.
