### ISSUE TITLE
If theme is tagged as 'responsive', hide the mobile theme module

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#1295]
Problem: Users don't realize that their theme is already mobile friendly, so they activate the mobile theme

Solution: Check the theme tags for "responsive", and, if it's there, hide the mobile theme

**Comment by macmanx2** [comment]
Just adding for the record and search, the tag used in themes is "responsive-layout". :)

I'm not sure I'd be in favor of completely hiding the module, some folks like our Mobile theme better, but at least a warning or an "Are you sure?" prompt would be nice.

**Comment by dereksmart** [comment]
+1 to James' suggestion. Probably best to politely tell them their theme may already be responsive instead of hiding it completely.

**Comment by beaulebens** [comment]
Agreed adding a warning would/should be enough.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by rachelsquirrel** [comment]
We're seeing more tickets in Happiness from users who have enabled the option in the new Jetpack Settings screen to optimise their site but they don't realise it will change the mobile theme to the Jetpack mobile theme. The option in Settings says to "Optimize your site for smartphones" but most themes these days are already responsive and most users are better off using their own theme. I think this option should be less prominent and the wording changed to "Use the Jetpack mobile theme" or something like that.

![themes](https://user-images.githubusercontent.com/7946521/27624287-ec13dd42-5bd7-11e7-8173-a417ce4aabe0.png)

**Comment by aheckler** [comment]
Just wanted to leave another note in support of this. I don't have specific ticket links atm, but anecdotally I have seen half a dozen or so users confused/misled by this in the past couple weeks.

**Comment by dereksmart** [comment]
Re-closing.  The original issue here was opened to auto-detect if the theme is responsive.  Discussion about the the verbiage for the feature is being discussed in #7036
