### ISSUE TITLE
Jetpack Stats for categories and tags

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#12968]
#### Summary 

Currently, Stats is supporting category/tag tracking in Simple sites only. It's nice if it's installed in Jetpack / Atomic sites as well. 

#### Steps to reproduce the issue

1. On a simple site, head to Stats -> Insights 
2. There is an area there to check stats per categories and tags:

![Screen Shot on 2019-07-05 at 13:27:08](https://user-images.githubusercontent.com/10045087/60721963-cfcb5780-9f2f-11e9-8fe6-efdd18776d03.png)

#### More Info

Currently, the JavaScript tracking code in Atomic/Jetpack sites is recording tags/categories with `post:'0'`. For example, it looks like this in my testing site https://my-test-site.blog/category/uncategorized/ :

```
	_stq.push([ 'view', {v:'ext',j:'1:7.4.1',blog:'8888888888',post:'0',tz:'8',srv:'my-test-site.blog'} ]);
```
Related code: 

https://github.com/Automattic/jetpack/blob/3ed3de86a58730377bbc29f8b7df7aa7729f28ce/modules/stats.php#L208-L223

--- 

Thanks @mlaetitia for originally reporting this issue in 4048-gh-jpop-issues

**Comment by htdat** [comment]
124804-zd 
/cc @yolizh

**Comment by rebcro** [comment]
+1 to this feature request (I'm the above-mentioned VIP client 👆😇). 

The ability to monitor category and tag traffic is a key component of corporate blog management. If I don't have insight into how visitors are navigating through my blog's categories and tags, it's very difficult to gauge what types of content they're seeking, and it's much harder to make informed strategy and editorial decisions. 

Happy to provide additional context / answer follow-up questions. Thanks!

**Comment by kelasante** [comment]
Another request in 4726651-zd. User has free content and Premium content that are categorized with tags. They would like to see stats for tags.

**Comment by StefMattana** [comment]
Another +1 reported in 4730091-zen
This user is currently on Free Jetpack plan.

**Comment by cagrimmett** [comment]
+1 !

**Comment by danjjohnson** [comment]
Another request here: https://wordpress.org/support/topic/include-categories-in-wordpress-stats/

**Comment by tfk2** [comment]
another +1 request for thsi for me.

surely if you use a CATEGORY based menu system then those clicks are not recorded. crazy.

I use a category as my home page...and that's crucial to have recorded for me!!

**Comment by gibrown** [comment]
This should be fixed for the Calypso version of Stats (running on wordpress.com). The (very) old version of stats displayed in wp-admin is still not showing it, but there is some work afoot to update that page, so we are going to consider that old stats is a case that we won't fix.

**Comment by JiveDig** [comment]
+1
