### ISSUE TITLE
Operators on where clause

### ISSUE THREAD

**Issue by davidmosterd** [Automattic/jetpack#1296]
The function `query_time_filter` in infinity.php decides on an operator around line ~449.
For me I had to change the default operator `<`  to `<=` using the `infinite_scroll_posts_where` filter to make things work properly. It excluded a lot of posts that where posted on exact the date that was equal to the `last_post_date` in the `$_REQUEST` var.

I'm not sure if this is a bug or a feature, but I am not used to see `<` and `>` as opposites an if statement, usually one of the operators has the `=` added to ensure exact matches can also be part of the result set.

If this is indeed a bug or enhancement, I could of course submit a pull request.

**Comment by jeherve** [comment]
Closing in favor of #1554
