### ISSUE TITLE
Slideshow Block: Fade Transition alters background

### ISSUE THREAD

**Issue by azollafox** [Automattic/jetpack#12962]
#### Steps to reproduce the issue

1. Create a Slideshow Block in a theme with a darkbackground
2. Change the transition effect to `Fade` and publish
3. View the page at different widths. At one point you'll begin to see a white outline around images.

*This is not reproducible on all browsers. Myself and the user see it in Chrome + Safari. Two other HEs do not. 

#### What I expected

The slider should match the background of the page no matter if its transition is slider or fade.

#### What happened instead

![](https://cld.wthms.co/PYdkYR+)

(Image link: https://cld.wthms.co/PYdkYR )

**Comment by sarahfg** [comment]
I wonder if it's related to https://github.com/Automattic/jetpack/issues/11839

**Comment by sarahfg** [comment]
I tested this on Atomic + Simple sites with several themes and successfully reproduced it. Lodestar with a black background ( to reproduce the effects the user reported) and Sophisticated Business were used

**Comment by tijosh** [comment]
I want to say I had a user with this same underlying issue in #14426015-hc 

Vertical images were being displayed past the white/beige background:

![Screenshot](https://cld.wthms.co/N4l9PQ+)

I could reproduce in Chrome, but other HEs could not

**Comment by yansern** [comment]
In order to test this, use portrait images (height longer than width).

A white (actually light gray) background is added when using fade transition. This `background` CSS property just needs to be removed.

```
.wp-block-jetpack-slideshow .swiper-container-fade .wp-block-jetpack-slideshow_slide {
    background: #f6f7f7;
}
```

![image](https://user-images.githubusercontent.com/1287077/132509914-92b1d87a-addf-4d99-8de6-01ede9cb9db0.png)

![image](https://user-images.githubusercontent.com/1287077/132509944-f5d8c6e1-8bca-49d1-9b7d-3ac14024604a.png)

**Comment by ivan-ottinger** [comment]
Actually, it turns out that removal of that class would make the slideshow messy (images displaying one over another). :/

![Markup on 2021-09-09 at 17:10:06](https://user-images.githubusercontent.com/25105483/132712590-53603d4a-306d-4fd8-88cd-c3db777426f3.png)

But, maybe we could set the background color to a variable coming from the theme, e.g. 

```
.swiper-container-fade .wp-block-jetpack-slideshow_slide {
	background: var( --global--color-background );
}
```

I will take a look if there is a common color variable we could use.

**Comment by ivan-ottinger** [comment]
To add more details:

The slideshow background color is taken from a variable `--color-neutral-0` in `style.scss`:
https://github.com/Automattic/jetpack/blob/449b76bef6d6165d67c9a2aa46bba8c40e3263d3/projects/plugins/jetpack/extensions/blocks/slideshow/style.scss#L67-L69

If every theme used the same variable for the background, we could use something that I proposed in the previous comment:

```css
.swiper-container-fade .wp-block-jetpack-slideshow_slide {
	background: var( --global--color-background );
}
 ```

or maybe even add fallback values, e.g.:

```css
.swiper-container-fade .wp-block-jetpack-slideshow_slide {
	background: var( --global--color-background, var( --color-neutral-0 ) );
}
```

but each theme is different unfortunately.

One way of fixing this issue could be to make the background transparent, but this would require changing the way the slideshow works (to make sure only the active image is displayed at one time).

Another alternative (that seems more reasonable to me considering the low issue prevalence), would be to change the background color using CSS on a case-by-case basis.

**Comment by yansern** [comment]
Okay so after removing the background color, adding this seems to prevent other images from showing up.
```
.swiper-container-fade .wp-block-jetpack-slideshow_slide:not(.swiper-slide-active) {
    opacity: 0 !important;
}
```

As the transition is too fast to verify whether it is really A-to-B fading, I slowed down the transition duration to 5 seconds to make sure that image A fades out the same time that image B fades in. Here's a video that shows that it is indeed A-to-B fading.

https://user-images.githubusercontent.com/1287077/132807185-97ef0b0f-73a3-4f8c-bb3d-b8390c91ea78.mp4


(Of course, setting `opacity: 0` probably is cleaner done on the JS script, but if the CSS works it's easier to just patch it like this and move on.)
