### ISSUE TITLE
Slideshow Block Not Appearing Under Safari (desktop and iOS)

### ISSUE THREAD

**Issue by macmanx2** [Automattic/jetpack#12961]
As reported at https://en.forums.wordpress.com/topic/images-not-displaying-on-posts/ images in the Slideshow Block are not appearing under Safari, both desktop and iOS.

The example post is https://buysecondhandfurniture.wordpress.com/2019/06/02/white-wooden-bench/

Under Firefox 67.0.4:

<img width="953" alt="Screen Shot 2019-07-04 at 2 53 07 PM" src="https://user-images.githubusercontent.com/4856235/60688665-7e599480-9e6b-11e9-93bc-eb3d24aba1f3.png">

Under Safari desktop 12.1.1:

<img width="847" alt="Screen Shot 2019-07-04 at 2 52 27 PM" src="https://user-images.githubusercontent.com/4856235/60688677-93cebe80-9e6b-11e9-97ed-51fb07872df6.png">

Under Safari iOS 12.3.1:

![IMG_1644](https://user-images.githubusercontent.com/4856235/60688722-d1334c00-9e6b-11e9-95f5-5eeb8e6f8c2c.jpeg)

Content blockers are disabled, and no errors appear in the JS console.

**Comment by jeherve** [comment]
Also reported in 2140810-zen

**Comment by gugaalves** [comment]
Not sure if it's the same issue but at https://kaeso000.com/ I can't see the slideshow too, using Google Chrome, Safari and Firefox (desktop), also white and only showing the arrows.

**Comment by simison** [comment]
FYI @jeffersonrabb in case this affects things at your projects.

**Comment by yovko** [comment]
It seems like this bug is here again (after the update to Jetpack 9.8).

**Comment by yansern** [comment]
This very old issue is no longer replicable.
