### ISSUE TITLE
Extend Widget Visibility to private and scheduled pages

### ISSUE THREAD

**Issue by theukedge** [Automattic/jetpack#1297]
I use Widget Visibility quite extensively, but quite an awkward aspect of it is that it only pulls up published pages in the list of pages to add rules for.

This makes life difficult in many of the scenarios that I need Widget Visibility for. Consider the following example:

I have a client whom covers major industry events on their site. They usually run a set of standard ads throughout their site, but on these special event coverage pages, they sell different ads in the same ad spot, which are solely for this event. As such, I prepare the landing page and publish it privately, so that I and others can view it and work on it until we're ready to pull the trigger and make it live. However, this limits us from installing the special event ad units, as the page can't be selected under Widget Visibility, since it is not yet published. We either have to publish the page early and make the widget visibility changes before switching it back to privately published until we're ready to go live, or have someone ready to update all of the widgets when the page does go live (not ideal if it's scheduled at an out-of-hours time for instance and also not ideal because there's a period where the ad units aren't serving on the live page). We're also limited from adding the "hide" logic on the standard ad units until the page is published, for the same reasons.

I'm proposing including privately published and scheduled pages in the list of pages that can be used for widget visibility.

I'm willing to submit the patch for this.

**Comment by aheckler** [comment]
3115455-t

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by nikdow** [comment]
Is there a filter that could add private pages to the visibility criteria?
I've added private pages to the menu builder as per https://stackoverflow.com/questions/30588611/wordpress-how-to-show-links-to-private-pages-in-wp-nav-menu/42181485#comment130817136_42181485
but now I need to show the menu only on related private pages...
