### ISSUE TITLE
Jetpack 7.5 fatals on sites with PHP < 5.6

### ISSUE THREAD

**Issue by ntwb** [Automattic/jetpack#13002]
My site is still on WP 5.1.x, here's why (I know, my bad)

> _"You cannot update because WordPress 5.2.2 requires PHP version 5.6.20 or higher. You are running version 5.5.9-1ubuntu4.29."_

Though with plugin automatic updates enabled by way of this plugin https://en-au.wordpress.org/plugins/automatic-updater/ Jetpack was automatically upgraded to v7.5 on my site, so per the [Jetpack changlog](https://jetpack.com/2019/07/02/jetpack-7-5/):

> _"Please note that this release requires that you run a recent version of WordPress (5.2 or newer), as well as a version of PHP higher than PHP 5.6. If you use an outdated version of WordPress or PHP, we recommend that you update your site to the latest version as soon as possible."_

I suspect whatever check Jetpack is, or is not doing is not taking into account that I am still using WP 5.x.x and PHP < 5.6.20

#### What happened instead

**Screenshots**

**Comment by jeherve** [comment]
Yes, that was a bug in Jetpack 7.5, sorry about that. It was fixed in Jetpack 7.5.1, as per those changes: #12931

**Comment by anantdubey91** [comment]
i am getting this error 

Notice: client.php is deprecated since version jetpack-7.5 with no alternative available. in /var/www/html/wp-includes/functions.php on line 4592.

is there any help on this notice.

**Comment by jeherve** [comment]
@anantdubey91 It seems one of your plugins or your theme is calling a Jetpack file that is now deprecated. I would recommend that you deactivate each one of your plugins, one at a time, until you find the source of the problem. You can then contact them to let them know they'll need to update their plugin to get rid of the deprecation notice.
