### ISSUE TITLE
Premium block flows: post checkout confirmation / thank you

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#13003]
The flow currently. Customer:
- inserts a premium block to the post in the block editor
- presses "upgrade"
   ![image](https://user-images.githubusercontent.com/87168/60811565-3fdc1680-a198-11e9-9f86-ed5df9ba60bd.png)
- purchases a plan
- after checkout gets redirected back to the block editor, the upgrade nudge is gone.

After the last step, we should show some kind of simple confirmation modal that they've purchased a plan and can now insert premium blocks to the editor.

There might be other "thank you for the purchase" visuals around Calypso that we can borrow?

**Comment by fditrapani** [comment]
Thanks for the ping @simison. Your best bet would probably be to use a banner of some sort:

https://wpcalypso.wordpress.com/devdocs/design/banner

Maybe something like this:

![image](https://user-images.githubusercontent.com/6981253/60888723-79a72e80-a225-11e9-8d42-7b41962b6a91.png)

**Comment by simison** [comment]
Fabulous! I like this, so simple!

**Comment by fditrapani** [comment]
yeah, it's good to start with and use as a base to iterate.

**Comment by simison** [comment]
Feel free to drop any copy ideas here.

**Comment by fditrapani** [comment]
cc'ing @ranh and @obi2020 for any suggestions here. For a little background, @simison is implementing a new upgrade flow and he'd like to present the customer with some kind of messaging after the purchase is complete and they're returned to the point they initiated the purchase. This message we currently use after an upgrade could be a starting point:

![image](https://user-images.githubusercontent.com/6981253/61007959-3d1a2680-a33c-11e9-8d97-4c7e6b525fad.png)

**Comment by simison** [comment]
This is how new snackbar updates look like in Gutenberg, instead of green bar on top of the editor:

<img width="432" alt="Screenshot 2019-08-06 at 08 20 48" src="https://user-images.githubusercontent.com/87168/62513056-28d62600-b823-11e9-89d1-a33befe7684d.png">

Good enough for the first iteration but eventually we'll need some design work to make a more celebratory modal when landing back in the editor (like in the screenshot above comment).

The copy could be something along the lines:

> Your site is now on the [WordPress.com Premium / Jetpack Premium] plan.

No need to mention the block name on the first iteration at least.

**Comment by michaeldcain** [comment]
Just /cc'ing @monikaburman to make sure that this is on her radar for upcoming design needed.

**Comment by ockham** [comment]
For a first iteration, I think we can:
- Use the [Snackbar](https://github.com/Automattic/jetpack/issues/13003#issuecomment-518506440) for UI (disclaimer: haven't worked with it yet, hope the is a good fit for our problem, implementation wise)
- Append a query arg to the [redirect URL](https://github.com/Automattic/jetpack/blob/dc2c9d5ae26aac8cc230b9ed5c00609863331512/extensions/shared/upgrade-nudge/index.jsx#L86-L97) to trigger showing it ([also on the frontend](https://github.com/Automattic/jetpack/blob/dc2c9d5ae26aac8cc230b9ed5c00609863331512/_inc/lib/components.php#L89-L98))
- Get the current plan from our [plans store](https://github.com/Automattic/jetpack/blob/dc2c9d5ae26aac8cc230b9ed5c00609863331512/extensions/shared/upgrade-nudge/index.jsx#L69-L70) and show it in the snackbar ("Upgraded to Jetpack Premium" or whatever).

**Comment by ockham** [comment]
Could also consider the [Notice](https://github.com/WordPress/gutenberg/tree/495608246d3ccdc8e3ff3271eee94d51474acb7e/packages/components/src/notice) component which is a bit more prominent (might be appropriate for a plan upgrade). Probably easy enough to switch out one for the other.

**Comment by simison** [comment]
>Could also consider the Notice component 

Oh, good point; I thought those might've been deprecated. I think `Notice` indeed is more appropriate for this use-case since notice is shown after landing to the page, not after pressing a button in the editor UI (e.g. compared to saving draft or publishing page).

We talked with @chriskmnds that the logic could be placed in a new file in `/extensions/shared` and imported to `extensions/editor.js` so that it runs each time editor is initialized.

**Comment by monikaburman** [comment]
Added @jancavan as assignee for design work. 

cc: @michaeldcain @simison

**Comment by jancavan** [comment]
`Snackbars` are meant for temporary messages, so I wouldn't use that here. The `Notice` component is better in the sense that it is more noticeable, but it isn't really appropriate here either.

Purchasing a plan is a big deal to a user, especially one that requires an annual commitment, so this warrants a proper success notification. Either of these two confirmations will work:

1. A dialog box
2. The current payment confirmation screen. The CTA will have to be updated here to say something like, "Back to editing my post (or page)"

@simison @michaeldcain
