### ISSUE TITLE
Premium block nudge: turn banner blue when multiple blocks are selected

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#13008]
Via https://github.com/Automattic/jetpack/pull/12963#issuecomment-508735110

> >   I'd expect upgrade banner to get a blue hue when multiple blocks are selected:
> >     <img alt="image" width="817" src="https://user-images.githubusercontent.com/87168/60713769-57aa6500-9f22-11e9-9223-7b2ad59eb5df.png">
> >   — might be just a matter of correct z-index or `background:transparent`?
> 
> Ideally, yeah. However, I've seen a bunch of code and/or styling in core (e.g. in the `Warning` component that this PR uses) that says something like 'make sure it works with multi-block selection' (or something like that), so it might be a tad more involved :grimacing: 
> 
> Edit: E.g. https://github.com/WordPress/gutenberg/blob/21e2dce2b287347e21c3e0618bc8fa8c0c1ef5ca/packages/block-editor/src/components/warning/style.scss#L11-L14 Though that's really just `background:transparent` :joy:

**Comment by ockham** [comment]
Make sure to merge #13019 before working on this (or base your branch on that PR) since you might otherwise encounter some stray borders behind the nudge that you'll be tempted to fix even though you don't need to :sunglasses:

**Comment by ockham** [comment]
I think this is actually also fixed by #13019.
