### ISSUE TITLE
Premium block nudge: ensure nudge looks good in dark theme mode

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#13014]
When using "Sophisticated Business" on .com simple sites, block editor is in ["dark mode"](https://developer.wordpress.org/block-editor/developers/themes/theme-support/#dark-backgrounds):

<img width="1440" alt="Screenshot 2019-07-09 at 21 07 32" src="https://user-images.githubusercontent.com/87168/60912322-c58dbe00-a28d-11e9-858b-cc773c7d49d1.png">

The nudge should turn dark, too. Looks like something to PR in the core since we're simply using a core component here. See also the alert below the Simple payments block; that's the same component in "invalid block"-state. Maybe temporarily in the theme as well.

You can re-create an invalid block state by inserting a block, editing the name of it in code-mode and switching back to visual mode.

This is how the banner normally looks like:

![image](https://user-images.githubusercontent.com/87168/62030947-e2634480-b1ee-11e9-95b8-5b021cb825b2.png)

It's ok to leave it white as long as text is visible, but ideally, it would have a dark background. We could re-use the dark background color from media placeholder visible in the first screenshot.

Repo: p1562696490448400-slack-onboarding-exp

**Comment by jeherve** [comment]
Somewhat related: #12738

**Comment by simison** [comment]
Nudge looks good these days:

<img width="812" alt="image" src="https://user-images.githubusercontent.com/87168/97340010-eff0f980-188b-11eb-8da6-e96702741c52.png">
