### ISSUE TITLE
Premium blocks nudge: protect theme font size leaking in

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#13011]
Nudge texts show up quite big when using "Independent Publisher 2" theme:

<img width="803" alt="Screenshot 2019-07-09 at 20 41 03" src="https://user-images.githubusercontent.com/87168/60910730-3b902600-a28a-11e9-916b-f6d059c9d863.png">

Let's protect against this by applying higher specificity selector to those texts. 

This could actually be fixed in the core component, too:

<img width="633" alt="image" src="https://user-images.githubusercontent.com/87168/60910983-c83ae400-a28a-11e9-891d-08abe7ceedcb.png">

**Comment by ockham** [comment]
Shouldn't that be considered a bug in the theme? :thinking: Looks like some _very_ generic selector is used there (maybe `p`?) that's bound to leak everywhere. I'm not sure that's tolerable behavior if even core itself is affected...

**Comment by sirreal** [comment]
This was introduced in the original Gutenberg support for the theme in r51124-wpcom-themes by @laurelfulford 

The warning component uses a `p`, the Upgrade nudge adds divs and spans inside for layout and styling. I think we may be the offenders here and should add stricter styling in the upgrade nudge. If we were adding a simple `p` text paragraph in the warning, I don't think there would be any problem. I'll look at improving styling for the Upgrade nudge.
