### ISSUE TITLE
Weird PHP Notices

### ISSUE THREAD

**Issue by BusinessBloomer** [Automattic/jetpack#13020]
Errors in my log:

```
[10-Jul-2019 11:17:24 UTC] PHP Notice:  client.php is <strong>deprecated</strong> since version jetpack-7.5 with no alternative available. in /home/***/public_html/wp-includes/functions.php on line 4592
[10-Jul-2019 11:17:24 UTC] PHP Notice:  jetpack_tracks_get_identity is <strong>deprecated</strong> since version jetpack-7.5! Use Automattic\Jetpack\Tracking->tracks_get_identity instead. in /home/***/public_html/wp-includes/functions.php on line 4435
```

Any hint?

**Comment by htdat** [comment]
This will be fixed in WooCommerce in the upcoming version https://github.com/woocommerce/woocommerce/pull/24050

**Comment by carllockett3** [comment]
Same issue...PHP Notice: jetpack_tracks_get_identity is deprecated since version jetpack-7.5! Use Automattic\Jetpack\Tracking->tracks_get_identity instead.

The previous posts said it was fixed and it definitely was not.

**Comment by jeherve** [comment]
The notices will disappear once you update to WooCommerce 3.7.0. That version of WooCommerce is not available yet, but will be in the future.

Until then, and if you see those notices appear on the front end of your production site, I would recommend that you edit your site's `wp-config.php` and make sure `WP_DEBUG` is set to `false`.

Thank you.

**Comment by vihsalGithub** [comment]
Hello all, i am having an issue in file "editor.deps.json" which is under "inc/block" folder, Here is a dependency called "wp-edit-post" which created an issue in my custom plugin for Guthenberg editor.
Please help me in this case.

Thanks in advance.

**Comment by jeherve** [comment]
@vihsalGithub Could you create a new issue and give us more details about your plugin, as well as the issue you ran into?

Thank you!
