### ISSUE TITLE
Sharing: add Dailymotion screenshots to Open Graph meta tags

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1302]
Jetpack currently automatically generates images for both Vimeo and Youtube videos, but not from Dailymotion.

It'd be a nice addition.

Suggested here:
https://wordpress.org/support/topic/problem-to-share-dailymotion-video-on-facebook?replies=1

**Comment by zinigor** [comment]
Tested, looking good!

**Comment by samhotchkiss** [comment]
Per an internal discussion, we've decided not to include dailymotion at this point due to their small marketshare.  We can re-evaluate down the road if this is a widely requested feature.

**Comment by samhotchkiss** [comment]
Under reconsideration, this was merged in
