### ISSUE TITLE
Instant Search: Outstanding issues

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#13027]
Here are some issues discovered in #12741 that we'd like to track for the Instant Search project (p3QzjZ-V3).

Bugs and defects:
- [x] Unapplicable search filters should automatically be disabled/removed; this often happens when changing the search query with a date filter active.
- [x] `#results` target for `React.Portal` should be more specific ([source](https://github.com/Automattic/jetpack/pull/12741#discussion_r299356870))
- [x] Add error handling for API request logic in SearchWidget ([source](https://github.com/Automattic/jetpack/pull/12741#discussion_r299357837))
- [x] Remove `target="_blank"` from search result links ([source](https://github.com/Automattic/jetpack/pull/13138#discussion_r316188248))
- [x] When placed in footer, it's hard to tell that the main content area is now displaying the user's search results ([source](https://github.com/Automattic/jetpack/pull/13761#pullrequestreview-303856308))

Needs fleshing out:
- ~What should happen when multiple widgets request `grabFocus`?~ ([source](https://github.com/Automattic/jetpack/pull/12741#discussion_r299368735)) - `grabFocus` has been removed
- [x] How should multiple search widgets behave when rendered onto a single page? ([source](https://github.com/Automattic/jetpack/pull/12741#discussion_r299374365))
- [x] Refactor enqueuing js into a separate class. Maybe class.jetpack-search-app.php. ([source](https://github.com/Automattic/jetpack/pull/12741/files#diff-47deebe9b1fd7090caed8291af235f54R197)) 
- [x] Add more comments about what all this code does and what it is for. Probably add a README. ([source](https://github.com/Automattic/jetpack/pull/12741#pullrequestreview-263758992))
- [x] Move js build into `_inc/build` probably. ([source](https://github.com/Automattic/jetpack/pull/12741#discussion_r305998499))

Enhancements: 
- [ ] Add cancellation logic for outdated fetches ([source](https://github.com/Automattic/jetpack/pull/12741#discussion_r299373087))
- [ ] Enqueue unminified CSS when `SCRIPT_DEBUG` is set to true ([source](https://github.com/Automattic/jetpack/pull/13138#discussion_r316195338))
- [x] "No Results" text flashes on the screen while the network request is in progress. 
- [ ] "It would be nice if the infinite loader used a similar style to the one used for Infinite Scroll module, to keep things consistent." ([source](https://github.com/Automattic/jetpack/pull/13761#pullrequestreview-303856308))

**Comment by keoshi** [comment]
Everything looks good to me except for this one:

>  Unapplicable search filters should automatically be disabled/removed

It seems this might have been a bug at some point and was fixed, but please check the use case on https://github.com/Automattic/jetpack/issues/14179 to see if it is relevant.

**Comment by bluefuton** [comment]
I've created separate issues for the outstanding items on the list: #14404, #14405 and #14406.
