### ISSUE TITLE
At a Glance: Align cards so they form a seamless grid

### ISSUE THREAD

**Issue by crunnells** [Automattic/jetpack#13036]
Currently, the Upgrade banners on the dashboard cards are not all the same height, so some alignment problems occur:

<img width="690" src="https://user-images.githubusercontent.com/4297811/61085160-50c09e00-a3cb-11e9-9e07-ab6b262d4772.png">

It's worth noting, the obvious solution of making them expand so the height always matches their neighbor isn't the best solution (specifically the anti-spam card):

<img width="690" alt="screen-shot-2019-07-08-at-9 56 33-am" src="https://user-images.githubusercontent.com/4297811/61085262-806fa600-a3cb-11e9-9376-2d1c681ce9f9.png">

We need to explore some options to re-arrange the cards so that the nearest neighbor is close in height, so we don't end up with unnecessary vertical space. We'll need to keep in mind that the card content can change, depending on the card's state(s), and that the content may change entirely in the future.

**Comment by crunnells** [comment]
At the very least, we need to remove the `margin-bottom` from the JetpackBanner components, so they don't push the cards below them further than necessary.

**Comment by MichaelArestad** [comment]
My instinct for now is to leave them as is until we come up with a better solution. Rearranging the cards sort of works unless an admin has completely disabled the feature, in which case, an upgrade card could be next to a regular one again.
