### ISSUE TITLE
Tiled Gallery block disappears with Gutenberg 6.1.0

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/jetpack#13037]
#### Steps to reproduce the issue

1. Install Gutenberg 6.1.0 on site https://wordpress.org/plugins/gutenberg/
2. Ensure that Photon is enabled
3. Try to add Tiled Gallery Block

#### What I expected
Tiled Gallery block appears in list of blocks under Jetpack.

#### What happened instead
Tiled Gallery block is not present in the list of blocks. The issue resolves by disabling the Gutenberg plugin, using the core block editor.

**Comment by dericleeyy** [comment]
Not sure if this PR resolves this issue:
https://github.com/WordPress/gutenberg/pull/16518

**Comment by jeherve** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/34386

**Comment by gwwar** [comment]
@jeherve this one can be closed, we verified that this was fixed with v6.1.1
