### ISSUE TITLE
Implement a friendlier approach to alternative user authentication methods

### ISSUE THREAD

**Issue by aitorpazos** [Automattic/jetpack#13033]
After trying the SQRL plug-in (https://wordpress.org/plugins/sqrl-login/ , https://github.com/kalaspuffar/wordpress-sqrl-login) I noticed that Jetpack wraps the Wordpress login page and creates an intermediate screen which impacts UX. ie: this page refers to the original login page as "Log in with username and password" which is not really true if different authentication schemes are used:

![image](https://user-images.githubusercontent.com/2015196/61067319-22f54c80-a3ff-11e9-9c75-4d470c5cf89b.png)

It would be great if Jetpack can remove this intermediate page and maybe give more weight to the "Login with Wordpress.com" option in the login page with the rest of login alternatives. This would prevent adding additional clicks to the user experience.

![image](https://user-images.githubusercontent.com/2015196/61067428-6bad0580-a3ff-11e9-9ea5-186426324307.png)

**Comment by jeherve** [comment]
That is something you can implement on your site with a filter, like so:

```php
add_filter( 'jetpack_sso_default_to_sso_login', '__return_false' );
```

![image](https://user-images.githubusercontent.com/426388/61141046-94e39980-a4c4-11e9-89fa-38ead493c7a4.png)


You can read more about it here:
https://developer.jetpack.com/hooks/jetpack_sso_default_to_sso_login/

The plugin author could add that filter to their own plugin if they'd like. I'll suggest that in your issue.
