### ISSUE TITLE
Lazy Load: Images not lazy loading within Related Posts

### ISSUE THREAD

**Issue by ntpixels** [Automattic/jetpack#13068]
**Summary**
A user reached out after noticing that Jetpack's lazyload classes aren't being applied to their related posts sections. After testing this on our own sites, we are experiencing the same: lazyload is being applied to images in the post body (single images, galleries), but not to related post images.

**Steps to Reproduce**
1. Enable Jetpack's Lazy Load functionality
2. Enable Jetpack's Related Posts, and related post feature image, functionality
3. Activate a default theme, like Twenty Nineteen
4. Inspect the related post featured images. They are missing the `jetpack-lazy-image` and `jetpack-lazy-image--handled` classes.

JP v 7.5.2:
![](https://camo.githubusercontent.com/d437f58651c8b430dcab7f952c135bdd59d302e2/68747470733a2f2f636c2e6c792f3839656665326638313939612f496d61676525323532353230323031392d30372d313425323532353230617425323532353230342e30312e303825323532353230706d2e706e67)

JP v 7.1.1: 
<img width="1440" alt="Screen Shot 2019-07-16 at 12 22 49 PM" src="https://user-images.githubusercontent.com/3965153/61323677-75e74f00-a7c5-11e9-9c3e-97252dd2f60b.png">

**Tested with**
- All plugins except Jetpack, Akismet, and VaultPress disabled
- Jetpack v 7.1.1 and v 7.5.2
- Default themes: Twenty Nineteen and Seventeen
- Reinstalling and reconnecting Jetpack
- Toggling the relevant Jetpack settings
- Confirmed that there are no console errors
- This works fine with the OceanWP theme, although we suspect that it's using its own Related Posts markup.

**Comment by rsamborski** [comment]
I am experiencing the same issue. 
Additionally the problem appears for lists of posts and main page (which in my case is basically a list of posts) - there is no lazy loading for images besides the ones inside particular post. 

Examples:
 https://karieranaobcasach.com
 https://karieranaobcasach.com/category/project-management/
 https://karieranaobcasach.com/2016/04/design-thinking/ ("you might also like" section)

**Comment by ADAPTiveBen** [comment]
I'm also experiencing this issue where images within the Jetpack related posts module are not being lazy-loaded.

Is there any update to this?

A possible solution would be to lazy load the entire module rather than just the images.

**Comment by jeherve** [comment]
> Is there any update to this?

Not yet, but we'll update this issue once we make progress on this.

**Comment by rilwis** [comment]
I'm having the same issue with Autoptimize's lazyload. I open [a thread](https://wordpress.org/support/topic/lazyload-image-not-working-with-jetpack-related-posts/) on Autoptimize's support forum and after a discussion, I realized that Jetpack uses JS to insert the related posts into the DOM dynamically.

Is there any workaround to make it statically? So Lazyload plugins can filter the output?

**Comment by jeherve** [comment]
> Is there any workaround to make it statically? So Lazyload plugins can filter the output?

Yes, you can use this method to output your own Related Posts, using the index of posts prepared by Jetpack:
https://jetpack.com/support/related-posts/customize-related-posts/#raw

**Comment by Squazz** [comment]
As this is still open, could we then at lead get loading="lazy" implemented
That way at least all supporting browses would handle this for you. https://caniuse.com/#feat=loading-lazy-attr

I'd guess it should be added around here: https://github.com/Automattic/jetpack/blob/771f691a72715db3e8c5de604d3b94b86cdb3509/modules/related-posts/related-posts.js#L157

**Comment by jeherve** [comment]
> could we then at lead get loading="lazy" implemented

Noting that this feature will be added to WordPress itself in version 5.5:
https://make.wordpress.org/core/2020/02/25/lazy-loading-update/

Jetpack will consequently be updated accordingly.

**Comment by samafroxy22** [comment]
Even after WordPress latest update, it is still hard to get lazy load on jetpack related posts images...

**Comment by galbaras** [comment]
@jeherve Since it's safe to assume that lazy loading is OK for related post images, and WordPress isn't handling images that are dynamically loaded via scripts, is it too much to ask that you add `loading="lazy"` to the IMG tags in the script?

These images are the ONLY ones that Google PageSpeed lists as not being deferred on my sites, as, I would imagine, on many other well optimised sites, and it's such a small effort with no down side.

**Comment by jeherve** [comment]
> is it too much to ask that you add loading="lazy" to the IMG tags in the script?

That's what we were discussing above indeed. I just opened #21073 for it.

**Comment by galbaras** [comment]
> Yes, you can use this method to output your own Related Posts, using the index of posts prepared by Jetpack:
> https://jetpack.com/support/related-posts/customize-related-posts/#raw

I've activated Jetpack on a test site that uses the Classic Editor plugin and Classic Widgets, in case this makes a difference. How do I get all the required post attributes for `Jetpack_RelatedPosts::render_block_item`? Is there some other way to generate the HTML from a post ID?

**Comment by jeherve** [comment]
> is there any difference between the static/PHP related posts and the ones output by the script?

No, there shouldn't be. Both pull the related posts from the same index on WordPress.com.
