### ISSUE TITLE
XML-RPC: The method verifyRegistration is not available if Jetpack is not connected. 

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#13084]
After some DNA refactors related to the connection, with Jetpack 7.5 [this change](https://github.com/Automattic/jetpack/commit/b52fa91e7cb07c2e99740a681d371f99bd5dc3f8#diff-4a3a36ebe6824f1968d3bd385dab82afL78) moved the declaration of the `verifyRegistration` method which caused a problem with the way we detect if Jetpack is active as a plugin on the remote site when using a connection flow that involes [wordpress.com/jetpack/connect](https://wordpress.com/jetpack/connet).

#### Steps to reproduce the issue

1. Apply D30576-code on your sandbox. (This should revert mitigation code).
2. Sandbox public-api.wordpress.com.
1. Go to https://wordpress.com/jetpack/connect.
2. Enter the URL of a site running Jetpack >= 7.5 (Jetpack needs to be installed and active in the site).
3. Click **Continue** and confirm that you get prompted to enter credentials. This shouldn't happen.

![image](https://user-images.githubusercontent.com/746152/61477445-a49c2b80-a965-11e9-9bdd-f9b41b5154a7.png)

The symptom presented on the connection flow if started from WordPress.com will be mitigated temporarily by D30579-code

#### What I expected

* To be able to conenct the site on continue the flow, for choosing a plan.

#### What happened instead

* WordPress.com thinks the Jetpack plugin is not active on the site.

**Comment by zinigor** [comment]
Fixed in #13139
