### ISSUE TITLE
Upgrade nudge: IE11 text overflows

### ISSUE THREAD

**Issue by sirreal** [Automattic/jetpack#13082]
> This is not super pretty in IE11 right now 
> Would there be a way to wrap the text in those conditions?

![ie11 overflow](https://user-images.githubusercontent.com/426388/61453910-a7941d80-a95f-11e9-8c91-1a64ed76f62a.png)

@jeherve I suspect that's an existing issue that's highlighted by the longer text here. I'll see about addressing it in another PR.

_Originally posted by @sirreal in https://github.com/Automattic/jetpack/pull/13065#issuecomment-512778946_

**Comment by jeherve** [comment]
Closing this now that this nudge doesn't exist in this form in the editor.
