### ISSUE TITLE
Featured image: Add support for custom post types

### ISSUE THREAD

**Issue by enventa** [Automattic/jetpack#13107]
When a user selects the option to NOT display featured images on posts (Customizer > Content Options), that do not only affect to regular posts, but also to any type of custom post.

As a developer, I would like to have some kind of hook I could use to short-circuit the `jetpack_featured_images_remove_post_thumbnail` function from the `featured-images.php`. Maybe something like the code below:

```php
<?php
/**
 * The function to prevent for Featured Images to be displayed in a theme.
 */
function jetpack_featured_images_remove_post_thumbnail( $metadata, $object_id, $meta_key, $single ) {
   $opts = jetpack_featured_images_get_settings();

   if ( apply_filters( 'shortcircuit_jetpack_featured_images_remove_post_thumbnail', false ) ) return $metadata;

   // Automatically return metadata if it's a PayPal product - we don't want to hide the Featured Image.
   if ( 'jp_pay_product' === get_post_type( $object_id ) ) {
	return $metadata;
   }

   (...)
```

Thanks for considering!

**Comment by jeherve** [comment]
Could you add more details about your suggestion, where it would apply, and what you are looking for?

Thank you!

**Comment by enventa** [comment]
> 
> 
> Could you add more details about your suggestion, where it would apply, and what you are looking for?
> 
> Thank you!

Sorry, I submitted my request without any content by mistake. I've updated it on the original request.
Thanks!

**Comment by sury-silu** [comment]
Hi @jeherve 

This is my first contribution, so please let me know if i did anything wrong in the process so that i can rectify it.

The suggestion here was for a filter to exclude the custom post types from the featured image option. But that only would help to developers. So instead i have added an option through which all users can manage it easily. Just by giving a comma separated list of custom post type slugs would hide featured images for them. For all other it would be displayed by default. Let me know if it would be useful, also if it needs any improvement.

Thanks,
Surya

**Comment by jeherve** [comment]
> a comma separated list of custom post type slugs would hide featured images for them

If we were to add a user interface, I would instead recommend a list of checkboxes listing all publicly displayed post types on the site, so it's easier for one to check or uncheck where they want featured images.

**Comment by enventa** [comment]
> If we were to add a user interface, I would instead recommend a list of checkboxes listing all publicly displayed post types on the site

Agree. Anyhow, no matter how that info is gotten (statically as the plugin does now or dynamically as proposed by @sury-silu), I think it should be filterable. That way both, end users and developers could take advantage of it.

**Comment by enventa** [comment]
Great! Thanks!!
