### ISSUE TITLE
Stats: store stats in transient instead of Jetpack option

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#13121]
Consider using transients to store data collected via `stats_get_from_restapi`:
https://github.com/Automattic/jetpack/blob/3ed3de86a58730377bbc29f8b7df7aa7729f28ce/modules/stats.php#L1632-L1689

This would improve performance when having to query for that data, especially on sites using a persistent object cache.

Related discussion:
- p1HpG7-7hA-p2

**Comment by gravityrail** [comment]
Let's also make sure we store it in one transient per cache key. There's no benefit to storing everything as one lump.
