### ISSUE TITLE
Connection: XMLRPC_Connector can never work

### ISSUE THREAD

**Issue by mdawaffe** [Automattic/jetpack#13136]
b52fa91e7cb07c2e99740a681d371f99bd5dc3f8 introduced Connection Connectors.

When the site is not yet active, the XML-RPC Connector is instantiated at https://github.com/Automattic/jetpack/blob/976231241de07c4dcab2983f5c7a254b1f2283d6/class.jetpack.php#L624

This adds an XML-RPC method: `jetpack.verifyRegistration`:
https://github.com/Automattic/jetpack/blob/976231241de07c4dcab2983f5c7a254b1f2283d6/packages/connection/src/XMLRPC_Connector.php#L32-L45

However, the next line in `class.jetpack.php` clears all existing XML-RPC methods since `Jetpack_XMLRPC_Server::bootstrap_xmlrpc_methods` does not filter its input but instead outputs only its own methods:
https://github.com/Automattic/jetpack/blob/976231241de07c4dcab2983f5c7a254b1f2283d6/class.jetpack-xmlrpc-server.php#L86-L94

Thus, when WordPress.com tries to use the `jetpack.verifyRegistration` method, it always fail, and WordPress.com always falls back to the REST Connector.

**Comment by oskosk** [comment]
Related #13084
