### ISSUE TITLE
Authors Widget: add filter to allow adding your own arguments to get_users

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#13141]
The Authors Widget allows you to display a list of users from your site.

https://github.com/Automattic/jetpack/blob/2240568d83c5a78d9be2bfc8032d5aa537f98dc4/modules/widgets/authors.php#L93

We've added a filter, `jetpack_widget_authors_exclude`, allowing you to exclude some specific users from being displayed on the site.

However, we could also add a filter for the whole array passed to `get_users`, this way folks could add their own arguments, such as `order` or `orderby`.

Suggested here:
https://developer.jetpack.com/hooks/jetpack_widget_authors_exclude/#comment-19398

**Comment by dreamertim** [comment]
Adding a filter for all params going into the `get_users` call would technically make the `jetpack_widget_authors_exclude` duplicative. Should the current filter be phased out in favor of filtering all the params going into `get_users`?

**Comment by jeherve** [comment]
Hey Tim 👋:) Happy to see you here!

Yes, I think it'd make sense to deprecate the old filter once we have a new filter in place that will give more flexibility.

**Comment by tmoorewp** [comment]
> Hey Tim 👋:) Happy to see you here!

Hey! Happy to be back :) Sorry, I didn't see this until now. How are you?
