### ISSUE TITLE
spin.min.js and jquery.spin.min.js files

### ISSUE THREAD

**Issue by dashkevych** [Automattic/jetpack#13155]
I've just noticed that these two files are loaded in the same time. Do they provide the same functionality?

`<script type='text/javascript' src='https://c0.wp.com/p/jetpack/7.5.3/_inc/build/spin.min.js'></script>`
`<script type='text/javascript' src='https://c0.wp.com/p/jetpack/7.5.3/_inc/build/jquery.spin.min.js'></script>`

**Comment by jeherve** [comment]
The 2 files work together, and rely on each other: `jquery.spin` extends the `spin` library, so it is expected to see the 2 files loading together.

**Comment by BusinessBloomer** [comment]
Why are these 2 scripts required? Or when do they load? Never seen a frontend spinner honestly and they load on every WordPress page, so I'm thinking of dequeueing them. 

Thank you & let me know

**Comment by jeherve** [comment]
> Why are these 2 scripts required? Or when do they load?

The spinner is used by 3 different Jetpack features:
- Carousel: the spinner is used when loading the comment form below each image.
- Comics: when using the Comics Post Type, one can upload new comics straight from the frontend, and there is a loading spinner there.
- Infinite Scroll. If you use the Infinite Scroll feature, the spinner is used when new content is being loaded.

If you don't use any of those 3 features, the scripts won't be enqueued. If you see them on every page, you're most likely using Jetpack's Carousel feature.
