### ISSUE TITLE
Debugger - should not redirect you to a new site

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1315]
When using the Debugger, it redirects you to this page after submitting your request:
![screen shot 2014-11-18 at 9 11 39 am](https://cloud.githubusercontent.com/assets/3220162/5115623/b97dc0ba-6ff7-11e4-8cdf-21105eb996cb.png)
It would be nice if it took you back to your Jetpack > Settings page with a success message letting you know we'll get back to you.

**Comment by dereksmart** [comment]
It's redirecting to a thank you page on jetpack.com correctly, but we can fix this in wpcom if it's still annoying and the browser's `back` button is not sufficient enough to stop the requests.
