### ISSUE TITLE
Dashboard: layout issues in IE11

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#13161]
Some of the dashboard screens don't look too great in IE11:
1. The Main connection screen
2. The main illustration in the "My Plan" screen:

<img width="908" alt="screenshot 2019-07-31 at 18 26 39" src="https://user-images.githubusercontent.com/426388/62230424-12167600-b3c2-11e9-8e36-e511cc67e3ce.png">
<img width="854" alt="screenshot 2019-07-31 at 18 25 09" src="https://user-images.githubusercontent.com/426388/62230425-12167600-b3c2-11e9-892d-3d0c47a926b2.png">

**Comment by kraftbj** [comment]
We will be deprecating IE 11 support this summer and thus are wontfix'ing IE 11 issues now. See p1HpG7-c8n-p2
