### ISSUE TITLE
Require adding new PHP files to `bin/phpcs-whitelist.js`?

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#13164]
Could Travis CI fail if when creating a PR and in commits, there are _new_ *.php files that weren't added to the list in [`bin/phpcs-whitelist.js`](https://github.com/Automattic/jetpack/blob/ed1bffebf24b2c802115c00d921a6f97a1bfa597/bin/phpcs-whitelist.js) used by [`pre-commit-hook`](https://github.com/Automattic/jetpack/blob/ed1bffebf24b2c802115c00d921a6f97a1bfa597/bin/pre-commit-hook.js)?

There might be situations where this would be bad that I'm just not seeing, e.g. when files are being moved around? Should the test be in Travis' "failures allowed" matrix in that case?

**Comment by brbrr** [comment]
We have this check in danger CI: https://github.com/Automattic/jetpack/blob/add/es5-pre-commit-linting/dangerfile.js#L45

We can switch `warn` to `fail` to make CI build fail.

**Comment by jeherve** [comment]
> We can switch warn to fail to make CI build fail.

Let's do it! 👍

**Comment by simison** [comment]
_Love you both!_
