### ISSUE TITLE
Sharing: Allow shortlink URLs 

### ISSUE THREAD

**Issue by kbrown9** [Automattic/jetpack#13170]
#### Is your feature request related to a problem? Please describe.

The social sharing buttons use the full URL. This can be a problem for sharing to services with limited character lengths, like Twitter.

#### Describe the solution you'd like

Allow the social sharing buttons to use shortlinks when the WP.me Shortlinks feature is enabled.

#### Additional context
Suggested in 2207262-zen

**Comment by jeherve** [comment]
While that is not something that we currently plan on adding to Jetpack itself (shortlinks aren't as important as they once were), you can use the following plugin to add that feature to your own site if needed:
https://wordpress.org/plugins/jetpack-shortlinks-for-sharing-buttons/
