### ISSUE TITLE
Feedback post type has invalid capability

### ISSUE THREAD

**Issue by justintadlock** [Automattic/jetpack#13178]
The Contact Form / Grunion module registers a CPT of `feedback`.  In the `$args['capabilities']` array, it sets the `create_posts` capability to `false`.

Capabilities should be strings.  I'm presenting a couple of options below for a fix:

1) If the idea is to not allow this, the capability should be set to `'do_not_allow'`.  

2) If the idea is to be consistent with the "edit" cap, this should be `'edit_pages'`.

See: https://github.com/Automattic/jetpack/blob/511df9e3ee54ae6ef5784f0cf2567ff8371b7315/modules/contact-form/grunion-contact-form.php#L193

**Comment by jeherve** [comment]
Related: #3123

**Comment by tmoorewp** [comment]
I propose to use the `do_not_allow`, as I recall the point was to disallow back-end creation of feedbacks.
