### ISSUE TITLE
Code shortcode For Jetpack and WordPress.com doesn't render well in AMP

### ISSUE THREAD

**Issue by ashercantrell** [Automattic/jetpack#13177]
I'm not certain if this is the correct place for this, maybe I need to post it in https://github.com/ampproject/amp-wp/ Please let me know if so!

I received a report from a customer today that, when using the [code] shortcode on WordPress.com sites or Jetpack-enabled WordPress sites, one can see rendering issues. Namely, the text can escape the borders of the page.

You can see this, as an example, on this post: https://buildingsteps.wordpress.com/2019/02/03/typed-claims-in-asp-net-core-2-1/

On the AMP version, the text is rendered out past the edge of the screen:
https://buildingsteps.wordpress.com/2019/02/03/typed-claims-in-asp-net-core-2-1/amp/

**Comment by jeherve** [comment]
That shortcode isn't part of Jetpack; it's managed by another plugin:
https://github.com/Viper007Bond/syntaxhighlighter/issues

I'd suggest creating an issue there. It may also be worth pinging the Guardians team since I believe they are the ones who now manage Alex's plugins.
