### ISSUE TITLE
AMP: amp-images in IE11 are too small 

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#13186]
#### Steps to reproduce the issue

1. Activate an AMP plugin
2. Load a post page with an image in amp view
3. See the small images

#### What happened instead

<img width="1440" alt="MSEdge - Win10 2019-08-06 10-11-46" src="https://user-images.githubusercontent.com/5654161/62524313-a86cf080-b835-11e9-8f1e-f6a7a33539e1.png">

**Comment by jeherve** [comment]
Does this happen even when the Image CDN module is off? If so, you may want to report this directly in the AMP repo.
