### ISSUE TITLE
Widgets: add Instagram widget from WordPress.com

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1319]
WordPress.com includes an Instagram widget:
http://en.support.wordpress.com/instagram/instagram-widget/

It'd be nice it it were available in Jetpack as well.

**Comment by jeherve** [comment]
#5493

**Comment by woshilapin** [comment]
In the source code of the [Keyring plugin](https://srd.wordpress.org/plugins/keyring/), I can find that the [Instagram service](https://github.com/beaulebens/keyring/blob/master/includes/services/extended/instagram.php) is provided.  However, I cannot find it when trying to discover keyring services on [WP.com API](https://developer.wordpress.com/docs/api/console/) with :
```
GET /meta/external-services/
```

Did I miss something?

**Comment by beaulebens** [comment]
We definitely have the Instagram service file on WordPress.com, but I think that endpoint is currently only listing services which we have Publicize support for.

**Comment by woshilapin** [comment]
Thanks @beaulebens, do you have any documentation or example on how to access/use the Instagram service?

**Comment by jeherve** [comment]
@woshilapin The Instagram service isn't accessible as part of Jetpack. If you'd like to connect your site to Instagram, you'll need to install [the Keyring plugin](https://wordpress.org/plugins/keyring/) on your site; the plugin will allow you to [connect your site](https://wordpress.org/plugins/keyring/installation/) to your own Instagram app.

You can then build your own plugin to use that connection. A good example is the [Keyring Social Importers](https://wordpress.org/plugins/keyring-social-importers/) plugin, that allows you to pull Instagram posts into your WordPress site.

**Comment by htdat** [comment]
User is asking here 698987-hc

**Comment by annezazu** [comment]
938553-zen

**Comment by annezazu** [comment]
1144297-zen

**Comment by mbarmettler** [comment]
are there any updates on this?
i wanted to add similar to the FB feed a Instagram Feed on our page...
alternatives?

**Comment by mbarmettler** [comment]
thanks for catching up htdat.

i'm using now the insta feed plugin from here: https://wordpress.org/plugins/instagram-feed/
it works quite good and serves my needs.

**Comment by zdenys** [comment]
Another user was suggested to use https://wordpress.org/plugins/instagram-feed/ but they don't like the look as much. So they asked if it's going to be available eventually. #1692489-zen

**Comment by supernovia** [comment]
Just noting another user looking for this widget here:
https://en.forums.wordpress.com/topic/no-instagram-widget/

**Comment by tmmbecker** [comment]
2541084-zen

**Comment by supernovia** [comment]
Is this resolved?

**Comment by jeherve** [comment]
@supernovia No. We'll close this issue when this is resolved. This will most likely happen when #15791 is merged, which may happen soon.
