### ISSUE TITLE
yarn watch triggers infinite loop

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#13198]
#### Steps to reproduce the issue

1. Check out the latest `master` branch. 
2. Run `yarn` and `yarn build`.
3. Run `yarn watch` and wait for the watch tasks to initialize.
4. Touch any SCSS file.

#### What I expected
Gulp to rebuild CSS files.

#### What happened instead
Gulp rebuilds CSS files ad infinitum.

#### Screenshots
<img width="382" alt="Screen Shot 2019-08-07 at 4 47 07 PM" src="https://user-images.githubusercontent.com/4044428/62662959-0a5f5000-b933-11e9-9709-7b0b9896c743.png">
These rebuilds were triggered by a single file change.

#### Potential source of the issue

This issue disappears when `sass:packages:rtl` is disabled. This gulp task was introduced in #13143 -- @jeherve, any idea on what's happening here?

**Comment by jeherve** [comment]
I can reproduce, and it's definitely caused by my PR, but I have not been able to figure out why yet :( I'll take a look when I am back from AFK, unless someone beats me to this :)
