### ISSUE TITLE
Nova Menus: Enhancements

### ISSUE THREAD

**Issue by webmandesign** [Automattic/jetpack#1320]
**These suggestions are related to [`nova.php` custom post type](https://github.com/Automattic/jetpack/blob/master/modules/custom-post-types/nova.php) module.**

I'd like to suggest a little enhancement for Food Menu custom post type. 
- Please consider adding HTML ID attribute on the menu group header output. This would be handy when creating an anchor navigation for menu sections.
- Or better, allow filtering the output HTML of the menu group title and description.

Thanks for considering!

(Originally suggested at https://wordpress.org/support/topic/food-menu-cpt-suggestion)

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
