### ISSUE TITLE
Social Logos CSS Not Optimized

### ISSUE THREAD

**Issue by ScottTravisHartley** [Automattic/jetpack#13201]
When evaluating the performance impact of various plugins I decided to look at JetPack that was rather strange albeit not a major issue it is a present one.

Files: 
/jetpack/_inc/social-logos/social-logos.min.css
&
/jetpack/_inc/social-logos/social-logos.css

Are currently unoptimized. 
1. The .woff file shouldn't be inlined with a data attribute it should just be included as a URL like the rest but more importantly some oddness. 
2. Due to the inclusion of two @font-face rules the .eot file is loaded unnecessarily regardless of browser type (such as on chrome).  
3. The .woff2 file simply isn't present in the file but it is included in the plugin files which would further reduce weight.

**Comment by jeherve** [comment]
Noting that the first patch to fix that problem (in #13363) could not be merged as it causes issues in some use cases, detailed in the comments of that PR.

**Comment by jeherve** [comment]
This should be fixed as of #28849
