### ISSUE TITLE
Twitter Widget: Font Size Incorrect on iPad

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/jetpack#13206]
#### Steps to reproduce the issue

1. Activate the Twenty Seventeen Theme
2. Enable Twitter Timeline Widget.
3. View the widget.

#### What I expected
The font size shouldn't be so large.

#### What happened instead

Notice a larger font size than expected when compared to the rest of the site.

**Screenshots**
See:

![img_0427](https://user-images.githubusercontent.com/5654161/63247215-2a650c80-c26d-11e9-96a9-9db40cd23a7b.png)
![img_0428](https://user-images.githubusercontent.com/5654161/63247218-2b963980-c26d-11e9-8726-63d4f49289af.png)

This was reported by a customer using the Broadsheet theme on WordPress.com. See: https://premium-themes.forums.wordpress.com/topic/problem-with-how-theme-displays-on-ipad/ He also reproduced it on Twenty Seventeen, so I don't believe it's a theme issue.

**Comment by jeherve** [comment]
I can't seem to reproduce, whether I use Jetpack's Twitter Timeline or Twitter's own embeds in an HTML widget.

Do you see similar issues when viewing the widget here?
https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2Fjetpack&widget=Timeline

**Comment by davidakennedy** [comment]
Hmm... I do see the text size being much larger than our average Twitter widget embed on a site. Maybe it was a change in the embed code itself from Twitter?

**Comment by jeherve** [comment]
> Maybe it was a change in the embed code itself from Twitter?

Yes, that's most likely the case. I'd recommend reporting this issue here:
https://twittercommunity.com/c/publisher/websites
