### ISSUE TITLE
Gutenberg: Ad Block Doesn't Fit in Border

### ISSUE THREAD

**Issue by Aurorum** [Automattic/jetpack#13214]
#### Steps to reproduce the issue

1. Add an Ad Block to a page
2. Pick a Leaderboard format (mobile or normal) 

I would have expected the entire block to fit within the border. Instead, this occurs. 

<img width="767" alt="Screenshot 2019-08-12 at 09 32 22" src="https://user-images.githubusercontent.com/43215253/62853436-418f8180-bce4-11e9-9a69-55ceb3214f1b.png">
<img width="862" alt="Screenshot 2019-08-12 at 09 33 51" src="https://user-images.githubusercontent.com/43215253/62853446-4eac7080-bce4-11e9-8327-86c3cc4337a4.png">

(on a WordPress.com site)

FWIW, this started popping up the same time that Automattic/wp-calypso#35286 did for me.

**Comment by simison** [comment]
We had an incident where some styling went missing for several blocks. This should now be fixed.

Thanks for the report!
