### ISSUE TITLE
Goodreads Widget: not accepting user's ID if users have so many books

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#13240]
From 4216-gh-jpop-issues

### Steps to reproduce the issue

Jetpack Goodreads widget showing user's ID (3846340) as invalid even though it is valid:
https://www.goodreads.com/user/show/3846340-fv-angela

Getting "Invalid User ID, please verify and re-enter your Goodreads numeric user ID. "

My newly created ID (101233110) is working correctly:
https://www.goodreads.com/user/show/101233110-deric-lee

I've checked the user's profile and confirmed that it is a public profile. I've tested this on my own test site.

### What I expected

3846340 should be valid. 

### Debug 

`timeout` in the following lines is the cause for Goodreads users having a lot of books. If changing it to a bigger number, e.g: 10, it will resolve the issue.

https://github.com/Automattic/jetpack/blob/2240568d83c5a78d9be2bfc8032d5aa537f98dc4/modules/widgets/goodreads.php#L93-L107

### Solution 

@dereksmart suggests: 

> I would recommend sending the patch to the user and opening a github Issue/PR about it. Maybe we can make the timeout filterable? There is also an opportunity to make the error messaging a bit more helpful :)

I will try create a patch for this one and update here later :)

**Comment by codestor4** [comment]
Solved in the PR above.
