### ISSUE TITLE
Mailchimp block: Hardcoded alignment setting

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/jetpack#13257]
Currently, the block has a hardcoded alignment setting `aligncenter`, and this forces the block appear centre aligned on the front of the site while it's left aligned in the editor. Can we remove the hardcoded alignment?

**Front of the site:**
<img width="1374" alt="Screen Shot 2019-08-19 at 14 05 16" src="https://user-images.githubusercontent.com/908665/63267851-d537f380-c28a-11e9-8f86-5b476797d9db.png">

**In the Editor:**
<img width="976" alt="Screen Shot 2019-08-19 at 14 06 12" src="https://user-images.githubusercontent.com/908665/63267864-d9fca780-c28a-11e9-85ca-965a697a05fb.png">

**Comment by jeherve** [comment]
> Can we remove the hardcoded alignment?

We default to a center alignment for most of our block buttons when no alignment is provided in the editor. Do you think we should default to left instead?

**Comment by iamtakashi** [comment]
> Do you think we should default to left instead?

Do we need to have an alignment? I couldn't find default alignment in Subscription form or Contact form. If a block doesn't provide any alignment setting, no alignment specified makes sense to me.

**Comment by jeherve** [comment]
> Do we need to have an alignment?

I don't suppose we do. I'd be fine with removing it. I've just created #13302 to do just that, and would appreciate your review!
