### ISSUE TITLE
Recurring Payments Block: Stripe Form Broken on FireFox

### ISSUE THREAD

**Issue by sarahfg** [Automattic/jetpack#13276]
Issue:

The recurring payment button on https://jsrunningcoach.com/personalized-coaching-registration/ is not working as expected. On the popup the card related fields are not working 

![](https://cld.wthms.co/jZX7pu+)
(Image link: https://cld.wthms.co/jZX7pu )

In browser console I see JS error from stripe because of empty publishable key being passed. But I don't see any option to re-authorize or recheck the stripe connection when I edit the page and the payment button. 

#### Steps to reproduce the issue

1. Using Firefox go to https://jsrunningcoach.com/personalized-coaching-registration/ 
2. Click on '$100 Contribution Button'

#### What I expected

No errors and the ability to submit a payment through Stripe

Reported by user at #2280967-zen

**Comment by jeherve** [comment]
@artpi Do you think you could take a look? 

Thank you!

**Comment by artpi** [comment]
Yes, I appologize. We had an issue over the weekend where it got broken everywhere.
I fixed it yesterday morning, but it seems not fast enough.

I am seeing it working on customers site now, ccan you confirm?

<img width="850" alt="Zrzut ekranu 2019-08-21 o 11 20 28" src="https://user-images.githubusercontent.com/3775068/63419895-e6f1d600-c405-11e9-99f3-765ed2dda7cf.png">

**Comment by sarahfg** [comment]
Yes, it looks much better now! I'm updating the user on this to let them know
