### ISSUE TITLE
Asset CDN: add filter to disable only in wp-admin

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#13294]
## Summary

2265657-zen is sending us his observation: 

> Regarding CDN for images and Static files 
> We are surprised how fast this CDN works, we did some tests loading images from Cloudflare Edge Cache vs. Jetpack CDN, and you can check the results for your reference, they speak for themselves.
> 
> Even though we get amazing results from the CDN, the back-end is performing worst due to the high number of requests loading (29 before, 150 after). As you can see in the screenshot, after we activated Jetpack, the back-end went from 979 ms to 1750 ms.

![Jetpack CDN - Backend](https://user-images.githubusercontent.com/10045087/63409912-465ae080-c41c-11e9-9046-c4e5d8347aa0.png)

I've tested on my site in Pressable for loading a post in Gutenberg https://my-site.com/wp-admin/post.php?post=1168&action=edit. This is the result I got (I have not noted the loading time as it looks random in my testing site): 

- With Asset CDN: 200 - 204 requests
- Without Asset CDN: 150 - 151 requests. 

**In my mind, we just replace asset files with our CDN links so the request numbers should be the same between with and without Asset CDN. But in fact, this is not true.** 

## Site Info

- blog_id: 165704624
- Ticket/Forum/Chat: 2265657-zen

**Comment by htdat** [comment]
Great comment from @jeherve in 4249-gh-jpop-issues: 

---- 

I believe I know what's happening here.

By default, WordPress core concatenates some CSS and JS in the dashboard, thus serving you one big file instead of multiple CSS or JS files. It makes sense for most sites (and can be disabled on development sites using the `SCRIPT_DEBUG` constant).

Jetpack's Asset CDN, however, does not do any concatenation. Instead it serves multiple files (hence the additional requests), all from our CDN. What's different here is that Jetpack's CDN serves all assets using HTTP/2. In those conditions, it's often best to not concatenate. This is explained in more details here:
https://blog.cloudflare.com/http-2-for-web-developers/

However, since this user is using CloudFlare, they do get resources served via HTTP/2 even when they don't use Jetpack's CDN. They consequently get fast resources out of the box, without Jetpack's CDN, with some of their resources concatenated. When they stop concatenating (via Jetpack's CDN), they get more requests. It should not normally have an impact on performance, quite the opposite in fact as pointed out in the CloudFlare article above, but their numbers show otherwise.

We currently do not have a way to disable Jetpack's Asset CDN only in wp-admin for example; that would be the ideal solution for them. I think it may be worth creating an issue in the Jetpack repo to suggest that improvement, via a filter for example.

**Comment by jeherve** [comment]
> We currently do not have a way to disable Jetpack's Asset CDN only in wp-admin for example; that would be the ideal solution for them. 

This is now possible, with the following code snippet:

```php
/**
 * Disable Jetpack's Asset CDN in the wp-admin dashboard.
 *
 * @return bool
 */
add_filter(
	'jetpack_force_disable_site_accelerator',
	function () {
		if ( is_admin() ) {
			return true;
		}
		return false;
	}
);
```
