### ISSUE TITLE
Integration with Qtranslate-xt

### ISSUE THREAD

**Issue by jurgen-74** [Automattic/jetpack#13296]
Hi all,

I am not sure whether this idea can be achieved  or maybe this is something that is there already, but here goes.
I love to work with qtranslate-xt. It is an easy plugin to make the website bilingual. It makes use of shortcode like this:
**[:nl]Tekst voorbeeld[:en]Text example[:]**
But now when someone subscribes to the posts they receive an update with the post tiltle in two languages included the shortcode:
**[:nl]Naam van het bericht[:en]Name of the post[:]**
It would be great to use Jetpack in a way that it recognises these kind of shortcodes. Can that be achiveed? Or is this a silly question.

Regards,
Jurgen

**Comment by jeherve** [comment]
> It would be great to use Jetpack in a way that it recognises these kind of shortcodes. Can that be achiveed? Or is this a silly question.

Not a silly question at all! It's a tricky thing to implement since those are not your typical WordPress shortcodes, and can be set to use multiple language codes. 

We are keeping track of that problem here:
#2195 

I'll close this issue as duplicate.

**Comment by jurgen-74** [comment]
Okay, thank you for introducing me to the original post about this. I couldn't find something about this due to bad internet speeds on Madagascar :( Just a side note, Facebook seems to recognise the shortcodes from qtranslate-xt.
Blessings
Jurgen
