### ISSUE TITLE
Instant Search: Ship Jetpack Fusion differentials

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#13292]
We shipped #12741 and #13138. However, we haven't shipped the corresponding Fusion differentials for WordPress.com.

- [ ] Ship D29592-code ([source](https://github.com/Automattic/jetpack/pull/13138#pullrequestreview-277798811))
- [ ] Ship D30956-code ([source](https://github.com/Automattic/jetpack/pull/13138#pullrequestreview-277798811))
- [ ] Ship D31891-code ([source](https://github.com/Automattic/jetpack/pull/13290/files))

**Comment by gibrown** [comment]
Done.
