### ISSUE TITLE
Instant Search: Fix encoding issues for title and excerpt

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#13291]
Reported by @jeherve [here](https://github.com/Automattic/jetpack/pull/13138#discussion_r316188758) and [here](https://github.com/Automattic/jetpack/pull/13138#discussion_r316188937).

#### Steps to reproduce the issue

* Add `define( "JETPACK_SEARCH_PROTOTYPE", true );` to your wp-config.php.
* Ensure that your site has the Jetpack Pro plan and has Jetpack Search enabled.
* Enter a query into a search widget. 
Alternatively, navigate to a search page like `/?s=this+is+a+search`.
* Ensure that you see a new Instant Search interface replacing the `main` content area on the left side of the page.

#### What I expected
Search results rendered clearly without any Unicode escape characters.

#### What happened instead
Search results rendered with Unicode escape characters.

**Screenshots**
![image](https://user-images.githubusercontent.com/426388/63436782-98563300-c429-11e9-83b8-8ccf13e7fbfc.png)

![image](https://user-images.githubusercontent.com/426388/63436806-a3a95e80-c429-11e9-8a64-e2a79e6c53b2.png)

**Comment by gibrown** [comment]
I think this is because React escapes all content... Part of a larger fix...

**Comment by jsnmoon** [comment]
I don't think this has anything to do with React; the raw API response contains these escaped Unicode characters. 

Here's an [exmaple search](https://public-api.wordpress.com/rest/v1.3/sites/20115252/search?query=this%20is%20a%20search&fields[0]=author&fields[1]=comment_count&fields[2]=date&fields[3]=excerpt_html&fields[4]=gravatar_url&fields[5]=permalink.url.raw&fields[6]=title_html) that contains several `&nbsp;`.

**Comment by gibrown** [comment]
I think all of these have been fixed.
