### ISSUE TITLE
Premium block flows: upgrade nudge success banner copy

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#13309]
When a customer purchases a plan via upgrade nudge banners in the block editor, we land them back in the editor and show upgrade banner:

https://github.com/Automattic/jetpack/blob/fc0e2be9a2a498a417d769c4b4577f3e71661dcd/extensions/shared/plan-upgrade-notification.js#L18-L21

Let's have this copy in the banner:

> Congratulations! Your site is now on the WordPress.com Premium plan. [View my plan].

For Jetpack sites, it'll say "Jetpack Premium" instead.

With a link to `https://wordpress.com/plans/my-plan/:SITE_SLUG` for .com sites and `/wp-admin/admin.php?page=jetpack#/my-plan` in Jetpack.

When plan info isn't available we can just say "on a paid plan" — I'd expect this to be an intermediate step before we add that info available in block-editor — unless it already is available readily?

>Congratulations! Your site is now on a paid plan. [View my plan].

cc @jancavan 

Via p7rd6c-22L-p2#comment-2768

**Comment by chriskmnds** [comment]
> For context - when/how does this happen? @simison

Mikael is referring to an intermediate state (part 1), as pulling in the plan info may be slightly more involving i.e. it doesn't equate to an actual state in the system.

**Comment by simison** [comment]
Yeah, so this would be temporary and short term only, while we add the needed plumbing to have that info available in the block editor in all environments.

**Comment by chriskmnds** [comment]
We won't be showing the actual registered plan in the banner? e.g.

> Congratulations! Your site is now on the WordPress.com Professional plan. [View my plan].

> Congratulations! Your site is now on the WordPress.com Premium plan. [View my plan].
