### ISSUE TITLE
Class not found Error on 7.6

### ISSUE THREAD

**Issue by dpegasusm** [Automattic/jetpack#13329]
Updated to Jetpack 7.6 and am getting:

PHP Fatal error: Class 'Automattic\Jetpack\Status' not found in /html/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/Actions.php on line 187

**Comment by jeherve** [comment]
Could you let me know what version of PHP you run on your site, how you installed Jetpack there (from here on GitHub or from the Plugins menu in your dashboard), and if you have any other plugins installed on your site?

Could you also try to deactivate and delete the Jetpack plugin, and then reinstall it from scratch?

Let me know how that goes!

**Comment by jeherve** [comment]
Thanks for giving it a try. Do you see the following file in your installation?

`vendor/automattic/jetpack-status/src/Status.php`

Could you also let me know if you see that Fatal when trying to access your site's dashboard, your site's front end, or only in your logs, and if so, does it happen at regular intervals / specific moments?

Thank you!

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
