### ISSUE TITLE
Sharing: Reddit Official Button broken - 404 Errors

### ISSUE THREAD

**Issue by csonnek** [Automattic/jetpack#13328]
#### Steps to reproduce the issue

1. Enable Sharing buttons
2. Add Reddit to the Enabled Services List
3. Choose "Official Buttons" and save. 
4. View a single post and check the console for `404 Not Found` errors tied to `button_info.json` - related share URL: `https://buttons.reddit.com/button_info.json?jsonp=buttonEmbed.parseSubmission&url=SINGLEPOSTURL`

This only impacts the Official Sharing button for Reddit - but the bug would impact every user who has the Reddit Official Button enabled in Sharing.

**Comment by jeherve** [comment]
Since we load the button directly from Reddit in an iFrame, we won't be able to fix this. That is something that would have to be updated on Reddit's end.
