### ISSUE TITLE
Photon should cache and serve WordPress.com images.

### ISSUE THREAD

**Issue by jenhooks** [Automattic/jetpack#1332]
In 1985970-t, a user seems to have exported/imported to a self-hosted site from WordPress.com, and unattached images in the media library are still being served from WordPress.com, on old posts. 

Since Photon doesn't cache and serve images from WordPress.com servers, the images are showing as broken on the new self-hosted blog:

![broken_photon_images_wpcom](https://cloud.githubusercontent.com/assets/7585054/5184578/96800418-7486-11e4-947e-88199d38664a.png)

<a href="http://i1.wp.com/turnwhentheroaddoes.files.wordpress.com/2013/10/20130812_182257.jpg" target="new">Here</a> is a broken sample image on the Jetpack site, from <a href="http://turnwhentheroaddoes.com/2013/10/13/the-cell-boosterat-last/" target="new">this post</a>.

We should allow Photon to cache and serve WordPress.com images, or we shouldn't use Photon at all if the image is already hosted on WordPress.com. <a href="https://github.com/Automattic/jetpack/blob/master/class.photon.php#L433" target="new">Here</a> is where we could stop Photon from being applied to WordPress.com URLs.

**Comment by jeherve** [comment]
Photon doesn't seem to return broken images anymore, as long as the images are publicly accessible. If the images are hosted on a private WordPress.com site, they shouldn't be made available to the public via Photon.
