### ISSUE TITLE
Option to see pages/posts shortened links on the admin bar

### ISSUE THREAD

**Issue by leandroprz** [Automattic/jetpack#13320]
#### Is your feature request related to a problem? Please describe.

Everytime I need a shortlink I have to access the WordPress dashboard, go to Pages/Posts and search for the page/post I want to share, edit it and search for the shortlink. This is time consuming and a bit tedious.

#### Describe the solution you'd like

A simple solution for this would be to add the shortlink on the WordPress admin bar so we could just right click and copy it.

#### Additional context

https://i.imgur.com/0uWkVNY.png

**Comment by jeherve** [comment]
This is probably not something we would add to Jetpack itself as we have not received many requests for it, but that is something you could add to your own site with a functionality plugin, by adding code like this:

```php
function jeherve_shortlinks_admin_bar( $wp_admin_bar ) {
	if (
		! class_exists( 'Jetpack' ) 
		|| ! Jetpack::is_module_active( 'shortlinks' )
	) {
		return;
	}

	$link = wpme_get_shortlink( 0, 'query' );
	
	if ( ! empty( $link ) ) {
		$wp_admin_bar->add_menu(
			array(
				'id'    => 'jetpack_shortlink',
				'title' => esc_html( 'Shortlink' ),
				'href'  => esc_url( $link ),
			)
		);
	}
}
add_action( 'admin_bar_menu', 'jeherve_shortlinks_admin_bar', 99 );
```

I hope this helps.
