### ISSUE TITLE
Ancient favicon.png file loaded by build.min.js for logged in users

### ISSUE THREAD

**Issue by galbaras** [Automattic/jetpack#13337]
#### Steps to reproduce the issue

1. Log into site
2. Display any page (front end or back end)
3. Check browser console

```
GET https://behappyinlife1.get-business-online.com/wp-content/uploads/2013/01/favicon.png?w=48 net::ERR_NAME_NOT_RESOLVED
Image (async)
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:77
value @ build.min.js?db22c4aaa2aa2155e18f:77
ci @ build.min.js?db22c4aaa2aa2155e18f:33
No @ build.min.js?db22c4aaa2aa2155e18f:33
Do @ build.min.js?db22c4aaa2aa2155e18f:33
Ba @ build.min.js?db22c4aaa2aa2155e18f:33
$a @ build.min.js?db22c4aaa2aa2155e18f:33
Ps @ build.min.js?db22c4aaa2aa2155e18f:33
Cs @ build.min.js?db22c4aaa2aa2155e18f:33
ks @ build.min.js?db22c4aaa2aa2155e18f:33
Xa @ build.min.js?db22c4aaa2aa2155e18f:33
enqueueSetState @ build.min.js?db22c4aaa2aa2155e18f:33
b.setState @ build.min.js?db22c4aaa2aa2155e18f:41
s.onStateChange @ build.min.js?db22c4aaa2aa2155e18f:77
p @ build.min.js?db22c4aaa2aa2155e18f:77
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:77
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:77
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:25
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:25
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:25
E @ build.min.js?db22c4aaa2aa2155e18f:25
load (async)
t.bind @ build.min.js?db22c4aaa2aa2155e18f:77
t.default @ build.min.js?db22c4aaa2aa2155e18f:25
t.default @ build.min.js?db22c4aaa2aa2155e18f:25
a.get @ build.min.js?db22c4aaa2aa2155e18f:77
Re @ build.min.js?db22c4aaa2aa2155e18f:77
wi.getNotes @ build.min.js?db22c4aaa2aa2155e18f:77
bi @ build.min.js?db22c4aaa2aa2155e18f:77
wi.setVisibility @ build.min.js?db22c4aaa2aa2155e18f:77
value @ build.min.js?db22c4aaa2aa2155e18f:77
ci @ build.min.js?db22c4aaa2aa2155e18f:33
No @ build.min.js?db22c4aaa2aa2155e18f:33
Do @ build.min.js?db22c4aaa2aa2155e18f:33
Ba @ build.min.js?db22c4aaa2aa2155e18f:33
$a @ build.min.js?db22c4aaa2aa2155e18f:33
Ps @ build.min.js?db22c4aaa2aa2155e18f:33
Cs @ build.min.js?db22c4aaa2aa2155e18f:33
ks @ build.min.js?db22c4aaa2aa2155e18f:33
Xa @ build.min.js?db22c4aaa2aa2155e18f:33
enqueueSetState @ build.min.js?db22c4aaa2aa2155e18f:33
b.setState @ build.min.js?db22c4aaa2aa2155e18f:41
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:77
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:25
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:25
E @ build.min.js?db22c4aaa2aa2155e18f:25
load (async)
t.bind @ build.min.js?db22c4aaa2aa2155e18f:77
t.default @ build.min.js?db22c4aaa2aa2155e18f:25
value @ build.min.js?db22c4aaa2aa2155e18f:77
ci @ build.min.js?db22c4aaa2aa2155e18f:33
No @ build.min.js?db22c4aaa2aa2155e18f:33
Do @ build.min.js?db22c4aaa2aa2155e18f:33
Ba @ build.min.js?db22c4aaa2aa2155e18f:33
$a @ build.min.js?db22c4aaa2aa2155e18f:33
Ps @ build.min.js?db22c4aaa2aa2155e18f:33
Cs @ build.min.js?db22c4aaa2aa2155e18f:33
ks @ build.min.js?db22c4aaa2aa2155e18f:33
Xa @ build.min.js?db22c4aaa2aa2155e18f:33
js @ build.min.js?db22c4aaa2aa2155e18f:33
Rs @ build.min.js?db22c4aaa2aa2155e18f:33
qs.render @ build.min.js?db22c4aaa2aa2155e18f:33
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:33
Ds @ build.min.js?db22c4aaa2aa2155e18f:33
Ws @ build.min.js?db22c4aaa2aa2155e18f:33
render @ build.min.js?db22c4aaa2aa2155e18f:33
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:77
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:77
n @ build.min.js?db22c4aaa2aa2155e18f:1
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:1
(anonymous) @ build.min.js?db22c4aaa2aa2155e18f:1
14:49:33.752
```

The full URL of the script is https://widgets.wp.com/notifications/build.min.js?db22c4aaa2aa2155e18f

#### What I expected

The correct site icons are specified by the theme as follows:

```
<link rel="icon" href="https://www.noff.com.au/wp-content/uploads/2019/08/cropped-noff-baras-logo-1-32x32.png" sizes="32x32" />
<link rel="icon" href="https://www.noff.com.au/wp-content/uploads/2019/08/cropped-noff-baras-logo-1-192x192.png" sizes="192x192" />
<link rel="apple-touch-icon-precomposed" href="https://www.noff.com.au/wp-content/uploads/2019/08/cropped-noff-baras-logo-1-180x180.png" />
<meta name="msapplication-TileImage" content="https://www.noff.com.au/wp-content/uploads/2019/08/cropped-noff-baras-logo-1-270x270.png" />
```

#### What happened instead

It seems that Jetpack is getting an old value, which is still linked to my user profile somewhere.

Importantly, the correct site icon is showing on https://wordpress.com/settings/general/www.noff.com.au, so Jetpack must be looking somewhere else.

The problem remains even after a data sync.

**Comment by jeherve** [comment]
I think this icon may be called because one of your notifications (accessible by clicking on the small bubble in the top right corner in the admin bar) is for that old site.

Could you try to go to this page:
https://wordpress.com

There, disconnect each one of your old sites from WordPress.com (you can do so when clicking on the red icon in the left sidebar, next to the site you want to disconnect). 

Let me know if it helps.

**Comment by galbaras** [comment]
I've found out that the incorrect icon belongs to another site, but I see incorrect/missing site icons for some of the other sites.

After disabling the Notifications module, I no longer have the problem, and I don't need this module, but even a full sync with a site doesn't update the icon, so something should be done about it.

**Comment by jeherve** [comment]
> I see incorrect/missing site icons for some of the other sites.

Do you have a few examples, so I can take a closer look?

Thank you!

**Comment by galbaras** [comment]
https://www.behappyinlife.com/

https://www.get-business-online.com/

https://www.plastic2go.com.au/

**Comment by jeherve** [comment]
I can't seem to spot any obvious issues with those sites at the moment. Do you see calls to the same incorrect icon as before when Notifications are enabled, or do you see an incorrect icon when editing each site in the WordPress.com interface?

**Comment by galbaras** [comment]
As soon as I turned on Notifications on plastic2go.com.au, the browser complained about not finding the exact same image file. Turning Notifications off removed that issue.

I think this icon was linked to my account at the account level at a time when I was running behappyinlife.com within a multisite (ages ago). Notifications are not site specific. They are user specific.

**Comment by jeherve** [comment]
Could you go to this page, and see if there are any old sites that are there but that you would like to remove?
https://dashboard.wordpress.com/wp-admin/index.php?page=my-blogs

If so, let me know and I'll see that they get disconnected from your account. Once we do that the problem should disappear.

**Comment by galbaras** [comment]
None. They all seem OK

**Comment by jeherve** [comment]
Thanks! At this point I'm afraid I can only recommend waiting a bit; as new notifications start coming up for your account, the old, now irrelevant notifications will be pushed out and the problem should disappear.

Don't hesitate to reopen this issue if this is still an issue once you only have new notifications in your panel.

**Comment by jeherve** [comment]
> I've just visited make.wordpress.org/core/2019/09/06/introducing-twenty-twenty and the browser complained about the missing favicon.png.
> 
> Where would that be from? It may be related to the comment system.

Notifications are also loaded on that site, since it uses Jetpack and chooses to display the admin bar at all times:

![image](https://user-images.githubusercontent.com/426388/64871535-6775b200-d613-11e9-9001-97e02da67133.png)

As a result, the old problematic notification will load there as well.

**Comment by galbaras** [comment]
Where do I need to report this? It's annoying, and likely a problem for others, who may not be getting errors, but an old/incorrect image.

Why would Jetpack notifications even try to get a favicon? That's for a site, not a user.

**Comment by jeherve** [comment]
Is this still happening for you now? I can't seem to be able to reproduce right now.

**Comment by galbaras** [comment]
Yes. It's still happening. It's likely you will only be able to reproduce it using my wp.com login, or by tracing through https://widgets.wp.com/notifications/build.min.js?db22c4aaa2aa2155e18f and figuring out what it looks at.

I've tried changing all my Gravatar images. No change.

I've tried changing my default website on wp.com. No change.

Again, it no longer seems like a Jetpack issue, but can you tell me where to report it?

**Comment by jeherve** [comment]
> I've tried changing all my Gravatar images. No change.
> I've tried changing my default website on wp.com. No change.

That won't help I am afraid, since those changes do not impact the list of notifications that load in your Notifications panel.

> it no longer seems like a Jetpack issue, but can you tell me where to report it?

Here is fine really, the problem is linked to Notifications, which can be used in Jetpack. We're also tracking the issue internally, in order to better refresh that notifications list: pKdGS-1iN-p2

**Comment by galbaras** [comment]
I seem to have solved the issue by changing the behappyinlife.com site icon.

Thank you for your support.
