### ISSUE TITLE
Insecure URL generated inside of Contact Info Widget

### ISSUE THREAD

**Issue by joweber123** [Automattic/jetpack#13352]
#### Steps to reproduce the issue

1. Add a Contact Info & Map widget to any widget area.
2. Insert a map with a valid API key.
3. View the URL inside of the iframe generated.
4. The URL for the Google logo image is insecure `http://maps.gstatic.cn/mapfiles/embed/images/google4.png`
5. This is causing the page to be displayed as insecure in the browser which can be seen on the website https://www.whynopadlock.com

#### What I expected
All elements of the inserted iframe to be coming from a website with a SSL certificate.

#### What happened instead
The URL of one image inside of the iframe is coming from an insecure website.  

**Screenshots**
![Screen Shot 2019-08-28 at 16 44 52](https://user-images.githubusercontent.com/24914028/63835816-3a8a9380-c9b3-11e9-94f4-7bfcbe1314f4.png)

**Comment by jeherve** [comment]
I am afraid there isn't much we can do about this in Jetpack; the image is added by Google themselves. 

I would consequently recommend that you report the issue to Google directly instead.
