### ISSUE TITLE
Activity Log: ActionScheduler actions on the Activity page

### ISSUE THREAD

**Issue by galakhyati** [Automattic/jetpack#13354]
#### Steps to reproduce the issue

1. Make sure the site is connected to Jetpack.
2. The site has WooCommerce latest and the WooCommerce Admin plugin installed. (v3.7.0 and 0.17.0 respectively)
3. Go to Activity Log
4. See multiple entries of `ActionScheduler`.

#### What I expected
Expect nothing from WooCommerce Admin to be displayed on Activity Log.

#### What happened instead
Saw multiple entries from WooCommerce Admin for comments.

And when clicked on the event, they are loading a blank page.

**Screenshots**
1. 
![Screen Shot on 2019-08-28 at 15-13-08](https://user-images.githubusercontent.com/7382505/63844782-6ce1c400-c9a6-11e9-9b6a-774b668f3e09.png)

2. 
![Screen Shot on 2019-08-28 at 15-26-18](https://user-images.githubusercontent.com/7382505/63845817-415fd900-c9a8-11e9-9d4b-abae0cdf4aba.png)

I understand the screenshots are in Japanese, though I did not have WooCommerce Admin plugin installed on my test site to replicate the issue on my site immediately. The previous error will help to understand the issue better.

There was a similar issue which was fixed and was supposed to hide the records from WooCommerce Admin from Activity Log:
https://github.com/Automattic/jetpack/issues/12714

This was fixed with this PR: https://github.com/Automattic/jetpack/pull/12830

Chat: #14857641-hc

**Comment by jeherve** [comment]
Here is one of the comments that is displayed in the Activity Log for that site:

```
'WP_Comment Object
(
    [comment_ID] => 3468
    [comment_post_ID] => 25402
    [comment_author] => ActionScheduler
    [comment_author_email] =>
    [comment_author_url] =>
    [comment_author_IP] =>
    [comment_date] => 2019-08-28 18:33:41
    [comment_date_gmt] => 2019-08-28 09:33:41
    [comment_content] => action created
    [comment_karma] => 0
    [comment_approved] => 1
    [comment_agent] => ActionScheduler
    [comment_type] => action_log
    [comment_parent] => 0
    [user_id] => 0
    [children:protected] =>
    [populated_children:protected] =>
    [post_fields:protected] => Array
        (
            [0] => post_author
            [1] => post_date
            [2] => post_date_gmt
            [3] => post_content
            [4] => post_title
            [5] => post_excerpt
            [6] => post_status
            [7] => comment_status
            [8] => ping_status
            [9] => post_name
            [10] => to_ping
            [11] => pinged
            [12] => post_modified
            [13] => post_modified_gmt
            [14] => post_content_filtered
            [15] => post_parent
            [16] => guid
            [17] => menu_order
            [18] => post_type
            [19] => post_mime_type
            [20] => comment_count
        )

)
'
```

I originally thought that the `action_log` comment type would be enough to stop it from being synced, as per #13079, but it seems I was wrong.

#12830 stopped the parent post from being synced but that was not enough. I just created #13355 to try to fix this for good.

**Comment by chickenn00dle** [comment]
As a heads up, we have another case of this here: 2319257-zen

Here is the screenshot provided by the user (in case an English screenshot is useful):

![](https://d.pr/i/8qTmNB+)
Image link: https://d.pr/i/8qTmNB

And the site is: https://www.vividlipi.com/

**Comment by thehenrybyrd** [comment]
The user from 2319257-zen came back to us in the mobile queue in 2346558-zen. They're still seeing the comments - please let us know if there's any other information we can gather on this.

**Comment by shashidesai** [comment]
And seems like these activity messages are showing up more than before. It's concerning because users will miss out on important activity messages if the activity list is all taken over by these "ActionScheduler" messages.
Screenshot of activity list showing ActionScheduler:
https://d.pr/free/i/V8eSAt
