### ISSUE TITLE
Business Hours Block: format appears incorrectly with many numbers

### ISSUE THREAD

**Issue by sourourn** [Automattic/jetpack#13357]
The Business Hours block format appears incorrectly on the user's site, with many extra numbers. I was not able to replicate this issue on my test site. But was able to replicate it on the user's site. Asked user to switch themes but it did not help. 

#### Steps to reproduce the issue

1. Go to My Site > Site > Posts / Pages > Add 
2. Add business hours block > Publish 

#### What I expected
Business hours appear correctly as set in the editor 

#### What happened instead
When you preview the live page - the business hours appear incorrectly with many extra numbers.

**Screenshots**
![Screen Shot on 2019-08-28 at 15-26-37](https://user-images.githubusercontent.com/39188945/63859833-56d50300-c9a8-11e9-8383-649f608aa252.png)
![Screen Shot on 2019-08-28 at 15-26-56](https://user-images.githubusercontent.com/39188945/63859842-5c324d80-c9a8-11e9-8f73-616f84b1b828.png)

-----User report: #2269827-zen

**Comment by jeherve** [comment]
Could you let us know what the date and time format is set to under Settings > General in wp-admin?

**Comment by sourourn** [comment]
Date and time format are both set to a custom format (see screenshot below). Should I change it?

![Screen Shot on 2019-08-28 at 15-32-31](https://user-images.githubusercontent.com/39188945/63860340-378aa580-c9a9-11e9-8544-990e9038e333.png)

**Comment by jeherve** [comment]
That time format does not appear to be correct, as you can see from the preview. I would recommend changing it to a correct format, that displays a time in the preview.

**Comment by sourourn** [comment]
Noted, will do. Thank you!
