### ISSUE TITLE
jetpack-branch-7.5-built virus

### ISSUE THREAD

**Issue by MariuSStar** [Automattic/jetpack#13378]
Hi guys, 

First, thank you for Jetpack, you're doing a great job.

Second, It seems to me that the 7.5 branch, the built version has some sort of a virus in it.
It keeps on getting detected by my host "jetpack-branch-7.5-built.zip, contains a virus so the upload was canceled: Sanesecurity.Foxhole.Zip_fs187.UNOFFICIAL FOUND".

Can you look into it? I would be a shame for this great project to get intercepted this way.

Thank you

**Comment by jeherve** [comment]
First of all, you can rest assured; if you downloaded the plugin from [the official WordPress.org plugin directory](https://wordpress.org/plugins/jetpack/) or from [the original repository here on GitHub](https://github.com/Automattic/jetpack), your version of Jetpack will be virus-free. The alert you're seeing is most likely a false positive.

We can find out a bit more about this here:
https://security.stackexchange.com/a/170050/172106

I can't find any mention of the `Zip_fs187` scan in the related database:
https://sanesecurity.com/foxhole-databases/

I would consequently recommend that you contact them directly to find out more.
https://sanesecurity.com/contact-us/

Until then, and if you want to use the Jetpack plugin on your site, I would recommend that you go to Plugins > Add New in your dashboard and install the plugin from there. This will ensure that you get an up to date version of the plugin. The version you are referring to above, `jetpack-branch-7.5-built.zip`, is an old version of the plugin.
