### ISSUE TITLE
WP-Admin Connect Flow: Login box disappears immediately, can't connect

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#13379]
#### Steps to reproduce the issue

0. You should be logged out of WordPress.com
1. Create a Jurassic Ninja site and somewhere set the wp-admin connect button flag using `define( 'JETPACK_SHOULD_USE_CONNECTION_IFRAME', true );`
2. Go through the connect flow
3. When I click "Connect with WordPress.com", the pop-up login window shows briefly then disappears

#### What I expected

To be able to log in and connect

#### What happened instead

Login window disappears immediately

**Video**

https://cloudup.com/cbgSQJRE_u3

**Comment by dereksmart** [comment]
I can't reproduce on a brand new JN site :/ 

@gravityrail could it be a browser thing? I see you're using Chrome, but do you have any extensions running in incognito?

**Comment by tyxla** [comment]
I can't reproduce either 😕 Is it possible there's a step missing in the test instructions?

**Comment by lezama** [comment]
@gravityrail could you try login in to try add a like to a post? it uses similar technology

**Comment by delawski** [comment]
This hopefully gets fixed with D32387-code.
