### ISSUE TITLE
Composer install of 7.6 fails due to reliance on dev package.

### ISSUE THREAD

**Issue by peterwilsoncc** [Automattic/jetpack#13382]
Composer installs are currently defaulting to Jetpack 7.4.1 due to later packages having `@dev` dependencies with `"minimum-stability": "dev",`.

Composer inherits the minimum stability from the parent package.

#### Steps to reproduce the issue

1. Initialise a composer config
1. Run `composer require "automattic/jetpack *"`
1. Composer will install from the 7.4 branch as that is the latest branch with stable packages. 
1. Run `composer require "automattic/jetpack 7.6"`
1. Composer will refuse to upgrade as Jetpack uses a dev release: 
  ```
  composer require "automattic/jetpack 7.6"

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for automattic/jetpack 7.6 -> satisfiable by automattic/jetpack[7.6].
    - automattic/jetpack 7.6 requires automattic/jetpack-connection @dev -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
   ```
Note: My package does not have a minimum stability setting so the second suggested cause comes from composer default settings. 

#### What I expected

Jetpack to install the latest release using stable dependencies. 

#### What happened instead
Jetpack 7.4.1 installed.

**Comment by jeherve** [comment]
Related: #12680

**Comment by jeherve** [comment]
We're still working on this. #14964 is what we are currently working on.

**Comment by jeherve** [comment]
This can now be closed, as it was handled via Changelogger and the autotagger tool added in #19192. Our packages' stable versions now always rely on stable packages.
