### ISSUE TITLE
Transferring ownership: refine UI

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#13387]
> The screen seems confusing to me.

> It has two primary actions: “Set new connection owner” and “Confirm deletion”.
> The top area seem separate from the bottom one, creating doubts on what happens if I action each of these. If I do the first, can I do the second later? If I do the second, would I have the first later?
> 
> In general: if I’m removing a user, I’m unlikely to be stopped by this. Why can’t we just reuse the options specified below instead of a separate dropdown and a separate button? Or inject code in a way that is similar to the content below and is triggered by the same button?

Reported here:
p8oabR-oH-p2#comment-3302

**Comment by jeherve** [comment]
cc @dereksmart

**Comment by dereksmart** [comment]
Hooking into the `delete_user_form` was the first thing I tried. Unfortunately, that hook fires within a <form>, so adding another <form> within it to do it's own thing wouldn't be valid HTML. 

I didn't look so far as to whether or not I could also hook into core's submit actions, but at that time it started to feel a little messy so I went with the notice approach which also has an additional benefit of being reusable on other pages if we would like to later. 

It's not worth it IMO.

**Comment by dereksmart** [comment]
> if I’m removing a user, I’m unlikely to be stopped by this

as an aside, I would argue that we should not block this action anyway. In many cases, it would require connecting another user. If someone is trying to delete a user in a hurry (maybe for security reasons), the last thing we want to do is have Jetpack stop them.
