### ISSUE TITLE
WP-Admin Connect Flow: Login box shows 502 error

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#13381]
#### Steps to reproduce the issue

0. As a user logged into WordPress.com...
1. Go to dashboard of newly rebuilt Jetpack from branch-7.7 on VVV, with `define( 'JETPACK_SHOULD_USE_CONNECTION_IFRAME', true );` in your wp-config.php
2. Disconnect then enable the Jetpack plugin
3. Attempt to connect via the wp-admin flow
4. When you get to the verification step, click "connect as a different user", and then click the "Connect with WordPress.com" button when it appears
5. Pop up box as the message "

I noticed that the URL of the connection pop up is 2611 bytes. It is generally recommended not to have URLs with more than 2048 bytes.... and also this just seems needlessly enormous!

I also noticed that removing the very large "login_url" parameter seems to make the page actually load (though I haven't completed the flow this way)

**Screenshots**

<img width="1192" alt="bad-gateway-popup" src="https://user-images.githubusercontent.com/51896/64069876-79655700-cc08-11e9-8aed-1c43aaba37db.png">

**Comment by delawski** [comment]
I found that this issue occurs only if you sign out from wpcom using wordpress.com site. If you click "Switch account" inside the iframe, it works well. More about it here: p1567440085025800-slack-poseidon

**Comment by lezama** [comment]
No one has been able to reproduce or see a 502 once besides you @gravityrail 😅 . 

Closing for now, feel free to reopen.
