### ISSUE TITLE
"Image Performance" name on Jetpack dashboard is confusing

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#13380]
The name "Image Performance" feels incomplete and insufficiently descriptive. It describes a feature area, and not what the feature actually is (even though a brief description is included in the box of the box)

<img width="486" alt="image-performance-name" src="https://user-images.githubusercontent.com/51896/64069799-c5af9780-cc06-11e9-8199-c6e6096670d7.png">

Ideally we would have a descriptive title, like "Image Accelerator" or "Optimize my images using the Jetpack CDN", and also some details about what it does, like "Optimize your images for smallest size, while serving them from Jetpack's global CDN for maximum loading performance", as well as a benefit like "Sites with faster image loading see more user engagement, particularly on mobile devices"

**Comment by folletto** [comment]
I agree.

Here's the kind of change I would make:

> Images Load Acceleration
> *Activate* to reduce image size and load them faster.

I would agree also in adding a benefit, but that will require to review all the blocks to be more coherent, also but not only for length concerns.

**Comment by keoshi** [comment]
Since we already refer to the CDN-suite features as “accelerator” it only makes sense to apply the same logic here. I'd suggest:

> Image Accelerator
> Reduce image load times for your readers and optimize them for mobile devices.

**Comment by simison** [comment]
"CDN" probably needs explaining if it's used, although customers seem to be getting more familiar with "CDN" and "VPN" specifically these days since they're used so much in marketing...
