### ISSUE TITLE
Retire mobile theme (minileven)

### ISSUE THREAD

**Issue by scottsweb** [Automattic/jetpack#13385]
With the majority of themes now responsive we should consider the retirement of the mobile theme feature. Ideally it will be off by default and then we can work towards a plan for retirement.

p2EDhh-Ia-p2
p1HpG7-7l5-p2

*****

**Project**: 1132000191628751-as-1150873576828085

**Comment by jeherve** [comment]
> Ideally it will be off by default

All good on that front. Jetpack's Mobile Theme has been off by default since it was first introduced in Jetpack, in 2012.

> we can work towards a plan for retirement

Maybe a simple first step would be to remove the option to enable it from the Jetpack Settings dashboard, so not that many folks enable it since it's unlikely they really need it in this day and age.

**Comment by jeherve** [comment]
#1295 also suggested a different approach with the settings UI, a few years back:

> If theme is tagged as 'responsive', hide the mobile theme module

**Comment by talgalili** [comment]
Some of us (e.g.: me) still use the mobile theme for website that needs to deal with legacy code. Please do not remove it (or move it to an external package). Thanks :)

**Comment by scottsweb** [comment]
Hi @talgalili thanks for letting us know, we would definitely make it available via an external package if it were to be removed from Jetpack core.

**Comment by jeherve** [comment]
Keeping this one opened for a bit more, as the Mobile theme is not removed from Jetpack just yet.

**Comment by dstein64** [comment]
> Hi @talgalili thanks for letting us know, we would definitely make it available via an external package if it were to be removed from Jetpack core.

@scottsweb mentions above that the mobile theme will be made available as an external package. I was following this issue for an update on that, but with this issue now closed, is there some other way to track that?

**Comment by jeherve** [comment]
@dstein64 That's not an option we recommend overall, but if you must use the Mobile Theme until you can find a better solution, the standalone plugin is available here:
https://github.com/Automattic/minileven

That plugin will not be supported or maintained, so I would recommend switching to a responsive theme if that's an option to you.

**Comment by dstein64** [comment]
@jeherve, thanks for the link. Per your suggestion, I've updated my theme.
