### ISSUE TITLE
Instant Search: Format/Localize Dates

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#13390]
We could use @wordpress/date, but using that more than doubles the size of our js bundle:
- w/o - 222240 Sep  2 03:12 jp-search.bundle.js
- with datei18n - 593190 Sep  2 01:39 jp-search.bundle.js

This is pretty absurd. We should just build our own I think. We need to localize the dates for:
- filtering
- displaying results

**Comment by simison** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString :grin:
