### ISSUE TITLE
Contact Form: Add "Mark as Spam" link to the notification email

### ISSUE THREAD

**Issue by cfinke** [Automattic/jetpack#13403]
#### Is your feature request related to a problem? Please describe.

When Akismet missed a spam contact form submission, there's no clear way to mark it as spam via the email notification. The sooner a missed spam is submitted to Akismet, the better, so adding a clear path to mark a submission as spam from the email is important.

#### Describe the solution you'd like

Ideally, we would add a "Mark as Spam" link to the email that works like the links in core WordPress's comment notifications and links to a page where the user can confirm that that individual submission should be marked as spam.

If that isn't possible, just adding a link to the recent form submissions wp-admin page would be an improvement, since the recent submissions are at the top and can be marked as spam with one click there.

One possible issue is that if the site owner replies to a user who submitted a valid contact form by replying to the email, the "Mark as spam" links would be present in their reply.  I don't know how bad this is, since the reply email would also already include the stuff like the user's IP address and whether or not they were verified, etc.

**Comment by kriskarkoski** [comment]
+1 to adding a Mark as Spam link in the email. I found I just ignored some spam submissions without the easy link to mark as spam.

**Comment by jeherve** [comment]
I'll close this as "won't fix". While this would be a useful addition to the email, many folks hit "reply" on those emails to directly reply to the person who submitted the form. We consequently cannot add links to wp-admin in the original email, as folks would then see the link in the quoted email.
