### ISSUE TITLE
"Stay connected" should be default option in disconnect modal?

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#13404]
The "Stay connected" button makes me nervous as a user because I'm not sure what it does and it's not default (or recommended) by Jetpack.

#### Steps to reproduce the issue

1. On the dashboard, click the "Manage site connection" link
2. Observe that modal has a bright red "Delete" button, but a grey, non-default "Stay connected" button

#### What I expected
A recommended or default option, so I feel confident keeping Jetpack connect. Or at least a close button of some kind so I can exit the modal without side-effects.

**Screenshots**

<img width="430" alt="stay-connected-not-default" src="https://user-images.githubusercontent.com/51896/64191286-00931480-ce2d-11e9-9b25-a3f4001faac7.png">

**Comment by jeherve** [comment]
cc @cbauerman who is currently working on the Disconnect experience. I am not sure if that modal will change as part of the project.

Internal reference: parBdM-fY-p2

**Comment by folletto** [comment]
The existing one to me seems the right approach however: the red button is a "Warning" button, and it's a common pattern to keep that red and the not-breaking alternative in default styling.

I would prefer not changing this unless there's a strong opinion otherwise.

We could make sure that "esc" dismisses the modal if it doesn't do it already.

**Comment by gravityrail** [comment]
Thanks @folletto. What do you think about adding an "X" in the corner to close the dialog? We do this in other places, e.g. the full screen modals.

**Comment by folletto** [comment]
I was about to say along the same lines: if we have it in similar modals elsewhere, then yes, let's add it here too :)

**Comment by cbauerman** [comment]
Like @jeherve mentioned we have a full redesign of this dialog in progress. As soon as #13303 is complete the next step will be implementing these changes:

<img width="450" alt="Screen Shot 2019-09-03 at 9 47 25 AM" src="https://user-images.githubusercontent.com/2810519/64192606-e870c480-ce2f-11e9-9f4b-e166bb077d1d.png">
<img width="450" alt="Screen Shot 2019-09-03 at 9 47 33 AM" src="https://user-images.githubusercontent.com/2810519/64192612-ead31e80-ce2f-11e9-83ad-c980eab8667c.png">

The "Disable Jetpack" heading will be "Disconnect Jetpack" when invoked from the manage site connection link.

**Comment by gravityrail** [comment]
Perfect @cbauerman ! I'll close this issue.
