### ISSUE TITLE
Bring back deprecation notices for deprecated methods

### ISSUE THREAD

**Issue by lezama** [Automattic/jetpack#13401]
On 7.7 we removed some deprecation notice to give Akismet and VaultPress time to deal with the deprecated methods.

See: https://github.com/Automattic/jetpack/pull/13397#event-2603255144

**Comment by jeherve** [comment]
Pushing this to the next release since the plugins have not been updated yet.

This is tracked for VaultPress here: https://github.com/Automattic/vaultpress/pull/59

@stephdau Do you know if this is tracked internally somewhere for Akismet?

Thank you.
