### ISSUE TITLE
"Jetpack Search" vs "Search" for dashboard widget

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#13408]
#### Steps to reproduce the issue

1. On a site without a Jetpack Professional plan...
2. Go to the Jetpack dashboard
3. Observe dashboard widget named "Jetpack Search"
4. Subscribe to a Jetpack Pro plan
5. Go back to dashboard and see that widget is now called "Search"

#### What I expected
Consistent naming

#### What happened instead
Inconsistent naming

**Screenshots**

Search unavailable:

<img width="477" alt="jetpack-search-widget-off" src="https://user-images.githubusercontent.com/51896/64192575-d8f17b80-ce2f-11e9-9a52-190d546bdc88.png">

Search available:

<img width="472" alt="jetpack-search-widget-on" src="https://user-images.githubusercontent.com/51896/64192584-dc850280-ce2f-11e9-8123-6ae4aea0ecae.png">

**Comment by folletto** [comment]
I think a similar discussion came up recently about other parts of the plan, I'm not sure what's the general preference... we need to review this in general.

@robertbpugh maybe has already a suggestion here?

**Comment by robertbpugh** [comment]
In this instance I would make the card title consistent - Jetpack Search. The body copy would be repetitive so could be reworded but at least the cards would be consistent.

As folletto mentioned these are all over the marketing and product so we would likely need a project to wrangle them all, or keep fixing one-offs when we notice and have the chance.

**Comment by gibrown** [comment]
As background, I had been intentionally trying to use "Jetpack Search" in order to make it more clear that it is it's own "thing" and to more strongly reinforce our brand (particularly when this is seen on WP.com sites in Calypso or on Atomic sites).
