### ISSUE TITLE
WP-Admin Connect Flow: Smoother state transitions

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#13418]
Right now the wp-admin connect flow has several transitions, e.g. while loading the iframe, where the user just sees whitespace and elements moving around (depending on connection speed, site speed etc)

We should ensure that we have proper placeholders/spinners/transitional-states so that the user always knows what's going on and the flow feels seamless.

**Comment by folletto** [comment]
Can you add screenshots to show what you mean and where?

**Comment by gravityrail** [comment]
I just went through the latest master and it's actually really seamless now, due to other changes. Looking good! I'll open another more specific ticket if I find related issues.
