### ISSUE TITLE
WP-Admin Connect Flow: Connecting to an account with 2fa shows many unwanted links, wrong color scheme

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#13419]
#### Steps to reproduce the issue

1. On a disconnected Jetpack site with the wp-admin connect flow enabled
2. Click through the flow
3. If you are logged in, click "Switch account"
4. Click the "Connect with WordPress.com" button
5. Attempt to log in with a WordPress.com account that uses 2fa

#### What I expected
A Jetpack-themed 2fa confirmation screen that keeps me in the connect flow no matter what I do

#### What happened instead
A WPCOM-themed confirmation screen with lots of links out of the flow

**Screenshots**

<img width="568" alt="jetpack-connect-2fa-credentials-screen" src="https://user-images.githubusercontent.com/51896/64204374-81acd480-ce4a-11e9-989b-fd0d69337652.png">

**Comment by jeffgolenski** [comment]
Good find Dan. As far as I know, we don't have a specific jetpack-only 2fa screen, so we'll need to create on. Here's a quick vid with further thoughts:

https://cloudup.com/c1Y-nakiG0m

Basically for this flow, we should remove the masterbar and make sure the links below the form(s) reroute to wordpress.com/jetpack/... flows, not the wordpress.com/start flows.

**Comment by gravityrail** [comment]
@jeffgolenski I can't hear any audio on that screencast. Can you re-upload?

**Comment by jeffgolenski** [comment]
I guess it recorded without sound. Ugh. 

That's alright. All I was saying is that we need to remove the masterbar and make sure all the links below the forms go the right places. 

Are we able to dynamically size the new pop-up window to fit the content so it's not cut off / below the fold of the pop-up?

**Comment by folletto** [comment]
Note: I would strive to have this screen to not be a fork from the existing one, otherwise it will double up maintenance and the Jetpack one would risk to get out of sync.

For instance if the bar is there in one, let's keep it in both, or discuss to remove in both.

**Comment by gravityrail** [comment]
1) Presumably there is already a technique implemented in the code for removing masterbar etc. for other parts of the Jetpack flow
2) Component based architecture is supposed to allow us to reuse part of all of the 2FA flow in other places, so even if we need to drop the existing 2FA components into a new context (e.g. in the connect flow) then it shouldn't break the universe.

**Comment by tyxla** [comment]
There are indeed techniques for reusing the Jetpack color scheme, so I'm going to use them and just apply them to the 2FA screens. PR coming soon.

**Comment by tyxla** [comment]
FWIW, this is a Calypso issue.

**Comment by tyxla** [comment]
PR: https://github.com/Automattic/wp-calypso/pull/36302
