### ISSUE TITLE
WP-Admin Connect Flow: fade out Jetpack promotional copy when starting flow

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#13410]
#### Steps to reproduce the issue

1. On an unconnected site
2. Go to the Jetpack Dashboard
3. Start the connection process (click "Set up Jetpack") and go through sign-up, either logged-in or logged-out from WordPress.com
4. Observe that as iframe loads and changes, promotional illustrations and copy are moved up and down

#### What I expected
A smooth, non-jarring flow

#### What happened instead
Bits of the screen moving around arbitrarily

**Screenshots**

<img width="963" alt="should-fade-out" src="https://user-images.githubusercontent.com/51896/64193075-e4917200-ce30-11e9-8832-0ab152d93ac3.png">

**Comment by jeffgolenski** [comment]
I like this idea. When a prospective customer clicks "set up Jetpack" we can do an easing fade to 50% opacity I think:

![Screen Shot 2019-09-03 at 4 37 45 PM](https://user-images.githubusercontent.com/214813/64206807-4a015500-ce69-11e9-896f-d2fde16d0f6b.png)

**Comment by gravityrail** [comment]
The idea behind fading it out completely (rather than just 50%) would be that it has the side-effect of not bouncing the content up and down as you proceed through the flow.

**Comment by gravityrail** [comment]
Since we need extra whitespace at certain times for the iframe contents.

**Comment by jeffgolenski** [comment]
Got it! yeah that sounds good. I commented on the PR
