### ISSUE TITLE
WP-Admin Connect Flow: When clicking to connect a different account, assume login not creation

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#13413]
#### Steps to reproduce the issue

1. With the WP-Admin connect flow, as a user logged in to WordPress.com...
2. When you get to the "Authorize" step, showing your gravatar, click "Switch account" link
3. When prompted, click "Connect using WordPress.com" 

#### What I expected
A login prompt (since I clicked "Switch account", the implication is that there is an account to switch to)

#### What happened instead
A signup prompt. I recognise that this is because my admin account email doesn't match a known WPCOM account email, but in this case we should override that behaviour in order to comply with the user's intent.

**Screenshots**

<img width="502" alt="switch-account-prompt" src="https://user-images.githubusercontent.com/51896/64195905-7ac89680-ce37-11e9-8e44-17a84fde5114.png">

**Comment by jeffgolenski** [comment]
I was just going through and testing this. I'm unable to reproduce when I'm already logged into my account. I see the screens in this order:

1) Approval of currently logged in wpcom account

![Screen Shot 2019-09-03 at 4 22 23 PM](https://user-images.githubusercontent.com/214813/64205977-42d94780-ce67-11e9-94db-e5ce7b9dd3dc.png)


2) Switch account link shows a new button that says "Connect using WordPress.com"

![Screen Shot 2019-09-03 at 4 10 04 PM](https://user-images.githubusercontent.com/214813/64205986-4967bf00-ce67-11e9-8c59-4982a2a15246.png)

3) new browser window opens log in form

![Screen Shot 2019-09-03 at 4 10 45 PM](https://user-images.githubusercontent.com/214813/64205998-4ff63680-ce67-11e9-9e1d-91f90a18ff3a.png)


I think we can reduce a step here as well. 

Is there any specific reason we show the "connect using WordPress.com" blue button by itself? I'm thinking when the customer clicks "switch account", we should just automatically open a new window with the log in form there.

**Comment by gravityrail** [comment]
I realise now why I was seeing this "bug" - when we load the login/signup screen, we check to see whether the user's wp-admin email address is in our database. If not, we default to the create-an-account screen. 

So I'm gonna say this is not actually a bug. The greater good is to get the user closer to what they need, and in this case the email address was not associated with an account, so creating it was a good default.
