### ISSUE TITLE
SSO: parameter removed from URL when logging in via SSO

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1342]
Steps to reproduce:

1. Log out of your self-hosted WordPress site.
2. Enter the following URL in your browser: `http://yoursite.com/wp-admin/admin.php?page=jetpack&configure=minileven`
3. You'll be redirected to the log in screen.
4. Click on the WordPress.com log in option.
5. You're redirected to `http://yoursite.com/wp-admin/admin.php?page=jetpack`

**Comment by ebinnion** [comment]
I can definitely take a look at it. We're on the tail end of our meetup though, so I probably won't get to it until this weekend.
