### ISSUE TITLE
Updating Jetpack 7.7: cron jobs causes fatal errors with Sync

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#13421]
#### Summary

In 2321902-zen, the user is reporting that they get an email from WordPress core: 

> Since WordPress 5.2 there is a built-in feature that detects when a plugin or 
> theme causes a fatal error on your site, and notifies you with this automated 
> email.
> 
> In this case, WordPress caught an error with one of your plugins, Jetpack by 
> WordPress.com.
> 
> First, visit your website (https://www.demo-site.com/) and check for any 
> visible issues. Next, visit the page where the error was caught 
> (https://www.demo-site.com/wp-cron.php?doing_wp_cron=1567546698.4277820587158203125000) 
> and check for any visible issues.
> 
> Please contact your host for assistance with investigating this issue further.
> 
> If your site appears broken and you can't access your dashboard normally, 
> WordPress now has a special 'recovery mode'. This lets you safely login to your 
> dashboard and investigate further.
> 
> https://www.demo-site.com/wp-login.php?action=enter_recovery_mode&rm_token=xxxxxxxx&rm_key=yyyyyyyy
> 
> To keep your site safe, this link will expire in 1 day. Don't worry about that, 
> though: a new link will be emailed to you if the error occurs again after it 
> expires.
> 
> Error Details 
> ============= 
> An error of type E_ERROR was caused in line 296 of the file 
> /wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/Actions.php. 
> Error message: Uncaught Error: Class 'Jetpack_IXR_Client' not found in 
> /wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/Actions.php:296 
> Stack trace: 
> #0 /wp-includes/class-wp-hook.php(286): 
> AutomatticJetpackSyncActions::send_data(Array, 'deflate-json-ar...', 
> 1567546706.3084, 'sync', 0.0025510787963867, 0.0035309791564941) 
> #1 /wp-includes/plugin.php(208): 
> WP_Hook->apply_filters(Array, Array) 
> #2 
> /wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/Sender.php(468): 
> apply_filters('jetpack_sync_se...', Array, 'deflate-json-ar...', 
> 1567546706.3084, 'sync', 0.0025510787963867, 0.0035309791564941) 
> #3 
> /wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/Sender.php(322): 
> AutomatticJetpackSyncSender->do_sync_for_queue(Object(AutomatticJetpackSyncQueue)) 
> #4 
> /wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/Sender.php(293):

#### Troublehoosting 

This issue happens when the site updates Jetpack 7.7 and runs cron jobs for scheduled sync actions, which were scheduled with Jetpack 7.6. 

If there is no issue with the site after seeing this error, we can safely ignore it for now. 

**However, developers may look into it to mitigate these errors and reduce the confusions to website owners.**

### Other info 

Similar issues for Jetpack 7.6 update: https://wordpress.org/support/topic/fatal-error-uncaught-error-35/

**Comment by htdat** [comment]
2322275-zen
Blog ID: 77990108

**Comment by tyxla** [comment]
Ah, that one again 😞 

Fix in #13422.

**Comment by joendotcom** [comment]
2322744-zen
Blog ID: 118296757

**Comment by KokkieH** [comment]
Two more reports in https://wordpress.org/support/topic/fatal-error-uncaught-error-class-jetpack_ixr_client/

Blog ID (one site mentioned): 41160620

**Comment by chuckreynolds** [comment]
aye. same. glad to hear there's a known issue && fix.  https://twitter.com/ChuckReynolds/status/1169431112969359362
