### ISSUE TITLE
Full image size (Gutenberg block "image") is not full size but limited at 702px

### ISSUE THREAD

**Issue by edwinhamers** [Automattic/jetpack#13433]
#### Steps to reproduce the issue

1. Create a Gutenberg post with the image block
2. Select an image (wider than 1024px)
3. Turn Jetpack "Speed up image loading time" on
4. View post. The image is limited to 702px
5. Turn Jetpack "Speed up image loading time" off
6. image is shown in full size

**Screenshots**
**Jetpack image loading ON**
![image](https://user-images.githubusercontent.com/10197201/64341207-244e8a00-cfe8-11e9-9ddb-3a5e5c642f49.png)

**Jetpack Image loading OFF**
![image](https://user-images.githubusercontent.com/10197201/64341263-45af7600-cfe8-11e9-863e-31fadee58f17.png)

## And the html code for comparison
**Jetpack image loading ON**
`<figure class="wp-block-image"><img src="https://i0.wp.com/www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton.jpg?w=702&amp;ssl=1" alt="" class="wp-image-50798 jetpack-lazy-image no-display jetpack-lazy-image--handled appear" data-recalc-dims="1" srcset="https://i0.wp.com/www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton.jpg?w=1078&amp;ssl=1 1078w, https://i0.wp.com/www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton.jpg?resize=300%2C56&amp;ssl=1 300w, https://i0.wp.com/www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton.jpg?resize=768%2C142&amp;ssl=1 768w, https://i0.wp.com/www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton.jpg?resize=600%2C111&amp;ssl=1 600w, https://i0.wp.com/www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton.jpg?resize=610%2C113&amp;ssl=1 610w" data-lazy-loaded="1" sizes="(max-width: 702px) 100vw, 702px"><noscript><img src="https://i0.wp.com/www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton.jpg?w=702&#038;ssl=1" alt="" class="wp-image-50798" srcset="https://i0.wp.com/www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton.jpg?w=1078&amp;ssl=1 1078w, https://i0.wp.com/www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton.jpg?resize=300%2C56&amp;ssl=1 300w, https://i0.wp.com/www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton.jpg?resize=768%2C142&amp;ssl=1 768w, https://i0.wp.com/www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton.jpg?resize=600%2C111&amp;ssl=1 600w, https://i0.wp.com/www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton.jpg?resize=610%2C113&amp;ssl=1 610w" sizes="(max-width: 702px) 100vw, 702px" data-recalc-dims="1" /></noscript></figure>`

**Jetpack image loading OFF**
`<figure class="wp-block-image"><img src="https://www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton.jpg" alt="" class="wp-image-50798 jetpack-lazy-image no-display jetpack-lazy-image--handled appear" srcset="https://www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton.jpg 1078w, https://www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton-300x56.jpg 300w, https://www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton-768x142.jpg 768w, https://www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton-600x111.jpg 600w, https://www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton-610x113.jpg 610w" data-lazy-loaded="1" sizes="(max-width: 1078px) 100vw, 1078px"><noscript><img src="https://www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton.jpg" alt="" class="wp-image-50798" srcset="https://www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton.jpg 1078w, https://www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton-300x56.jpg 300w, https://www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton-768x142.jpg 768w, https://www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton-600x111.jpg 600w, https://www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner-nobutton-610x113.jpg 610w" sizes="(max-width: 1078px) 100vw, 1078px" /></noscript></figure>`

**Comment by jeherve** [comment]
Do you experience similar issues when using a different theme, like Twenty Nineteen?

Could you also let us know if your theme supports both full images and responsive embeds, thanks to this in your theme's `functions.php`?
```php
add_theme_support( 'align-wide' );
add_theme_support( 'responsive-embeds' );
```

Could you also let us know if your theme defines a `$content_width` value, and if so, what is set to?

Thank you!

**Comment by edwinhamers** [comment]
I found this in the main theme (using a child theme)

```
// Content width is required for for oebmed and Jetpacks
		global $content_width;
		
		if (!isset($content_width)) {
			$content_width = 702;
		}
```
Is this code outdated?

I did not find the add_theme_support() ....

**Comment by edwinhamers** [comment]
I removed the code mentioned above from the main theme and now the image display at max-width 1000px

`<img src="https://i1.wp.com/www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner.jpg?ssl=1" alt="Vrindavana Parikrama 2019" class="wp-image-50794 no-display appear" srcset="https://i1.wp.com/www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner.jpg?w=1078&amp;ssl=1 1078w, https://i1.wp.com/www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner.jpg?resize=300%2C56&amp;ssl=1 300w, https://i1.wp.com/www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner.jpg?resize=768%2C142&amp;ssl=1 768w, https://i1.wp.com/www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner.jpg?resize=600%2C111&amp;ssl=1 600w, https://i1.wp.com/www.kksblog.com/wp-content/uploads/2019/05/braja-parikrama2019-banner.jpg?resize=610%2C113&amp;ssl=1 610w" sizes="(max-width: 1000px) 100vw, 1000px" width="1000" height="185">`

**Comment by jeherve** [comment]
Thanks for giving that a try. 

You can keep this value, it's not outdated, but if you want your full-size images to be really full-size, you'd need to implement true responsive embeds in addition to that `$content_width` value.

You can look at the Twenty Nineteen theme to see how this can be implemented.

**Comment by myosotisgit** [comment]
The theme (smart-mag) defines the maximum width for a full size post as 1078. So i used that value and hope/pray that the theme makers will advance to the future....
