### ISSUE TITLE
Contact Info Widget: API keys with website restrictions not working correctly

### ISSUE THREAD

**Issue by kbrown9** [Automattic/jetpack#13448]
Google Maps API keys that have been restricted to the site's URL are not working with the Contact Info widget. When a restricted API key is used, an error is displayed during setup of the map.

A user can restrict their API key to specific websites. When these restrictions are in place, the HTTP ‘Referer’ is checked against the website restrictions. The Maps request is rejected if the referrer URL is not in the list of allowed websites.

The widget's `has_good_map()` method checks whether an API key is valid using `wp_remote_get()`. (See the code [here](https://github.com/Automattic/jetpack/blob/master/modules/widgets/contact-info.php#L417)). The `wp_remote_get()` method sets the HTTP request ‘Referer’ to the requested URL, which is _https://<span></span>www.google.com/maps/embed/v1/place?..._.  Therefore, if the API key is restricted to the site’s URL, this API key check fails, and the user sees an error in their widget admin panel.

#### Steps to reproduce the issue

1. Obtain a Google Maps API key and restrict the key to your site’s URL.

2. Make sure the Extra Sidebar Widgets are enabled: https://jetpack.com/support/extra-sidebar-widgets/

3. Navigate to Appearance->Widgets and add the Contact Info Widget to your site’s footer or sidebar.

4. Click the Show Map checkbox and enter your Google Maps API key.

5. Click save. You should see this error:

> Google Maps Platform rejected your request. This IP, site or mobile application is not authorized to use this API key. Request received from IP address …, with referer: https://<span></span>www.google.com/maps/embed/v1/place?q=…

#### What I expected
API Keys that are restricted to the site’s URL should work.

#### What happened instead

API keys that are restricted to the site’s URL don’t work.

-------------------

### Fix
There are two ways to work around this:

* The user can remove all HTTP restrictions from their API key before setting up the Contact Info widget. After the API key has been added to the widget and the widget has been saved, the website restriction can be added to the API key.

* A user can add the Google Maps URL:

        https://www.google.com/maps/embed/v1/place?*

   to their API key’s restricted websites list.

**Comment by jeherve** [comment]
Fixed in #13664
