### ISSUE TITLE
Gallery Carousel: Incorrect images loading in carousel

### ISSUE THREAD

**Issue by galakhyati** [Automattic/jetpack#13458]
#### Steps to reproduce the issue

1. Go to Pages, add Gallery block. Add a couple of images. I added 20 of them. Publish the page. The Link To option for Gallery block is set to None.
2. Visit the page, click on one of the images, one of the other images in the gallery opens in Carousel.
3. Click on next image, only a couple of images load (3 in my case), no other images load.

#### What I expected
When I click on an image, I expect to see that exact image.

#### What happened instead
Some other image in the gallery opens in full view in the carousel.
I even tried to clear the cache on the page and try again, still no luck.

**Screenshots**
https://cld.wthms.co/1E39ct
My Test site: https://mywptest.blog/gallery-page/
User's page: https://sidetosideblog.com/art-for-sale

#2346013-zen

**Comment by galakhyati** [comment]
>On your test post, a lot of the images are actually not hosted on the site itself, but are hotlinked from pexels.com instead. 

I checked my Media and all the images that were added to the gallery with my site's URL. I added those images from Free Photo Library. And as per the support guide of [Free Photo Library](https://en.support.wordpress.com/free-photo-library/):

`  Please note that any images you use will be imported to your media library`

>Could you try to upload those images into that post, and give it another try?

I tried to add the same image to another gallery on the same page and the gallery worked this time. 

I am not sure why it would not work the 1st time. Not sure why images that are _supposed_ to be downloaded to the media would not link to the post.

https://mywptest.blog/gallery-page/#anchor

>On the page of the artist who reported the problem, I noticed that some of the images are not attached to any post. That in itself should not be an issue, but it makes me wonder how they uploaded those images in the first place. Could they tell us more about how they added an image like this one to their site?

The user said they uploaded the image from their machine, so it was a normal upload and not from a URL. We have asked if they uploaded the image to the Media or from the page itself. Waiting for a reply.

**Comment by jeherve** [comment]
> I am not sure why it would not work the 1st time. Not sure why images that are supposed to be downloaded to the media would not link to the post.

It looks like they were imported properly, but not actually replaced in the post. If you can reproduce the problem again, it may be worth reporting the issue in the `wp-calypso` repo.

**Comment by kristarella** [comment]
I have another similar report. I can't replicate it, but I also can't figure out what is wrong with the page: https://iamwoody.photo.blog/my-p-world/

If anyone can help identify the issue that would be appreciated!

2574024-zen

**Comment by jeherve** [comment]
@kristarella It may be worth trying to re-upload the images that do not appear in the Carousel view, and replace those images in the gallery.

**Comment by sophiegyo** [comment]
> @kristarella It may be worth trying to re-upload the images that do not appear in the Carousel view, and replace those images in the gallery.

Regarding 2574024-zen above, is there any particular reason why when attempting to modify the gallery at https://iamwoody.photo.blog/my-p-world/ , no images are found?
Screenshot: https://d.pr/i/LESr0T

They're definitely there: https://d.pr/i/5scE6Y

Prior to seeing "no images", I saw some images - not all, but some.

I've asked the user to re-upload the images that were missing from the carousel per your suggestion :)

**Comment by kristarella** [comment]
Thanks for the follow-up. I meant to respond because no images were missing, a different image from the gallery showed in the carousel, as if the gallery and carousel were in a different order. I thought the user had already re-uploaded, might they might have just tried to create the gallery again.

**Comment by sophiegyo** [comment]
>Thanks for the follow-up. I meant to respond because no images were missing, a different image from the gallery showed in the carousel, as if the gallery and carousel were in a different order. I thought the user had already re-uploaded, might they might have just tried to create the gallery again.

Tbh I'm not sure what's up with the gallery! I went through it carefully one by one, comparing what showed up in the carousel vs what was on the published page vs what was in the editor, and there were some images that were just plain left off in the carousel - those are the ones I listed in the email to the user.  It's a mystery to me ¯\_(ツ)_/¯

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
