### ISSUE TITLE
css editor parse problem on css "transition"

### ISSUE THREAD

**Issue by jjgh** [Automattic/jetpack#1346]
Hi I'm seeing the editor will strip out the "s" for seconds when the parameter is 0:

"transition: background-color .6s ease 0s;"

after saving becomes:

"transition: background-color .6s ease 0;"

This will make the transition not work in Firefox which will see the string as incorrect.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
