### ISSUE TITLE
Jetpack blocks result in duped HTML and console.error's

### ISSUE THREAD

**Issue by willstocks** [Automattic/jetpack#13475]
#### Steps to reproduce the issue

1. Open DevTools
2. Navigate to https://willstocks.co.uk/review-obins-anne-pro-2/
3. See errors logged in console

#### What I expected

I see a couple of errors, mainly because I'm using a Jetpack block in this article (have a look at some of my other posts - none contain Jetpack blocks so none of these errors there!).

When reviewing these elements in the HTML, there are two of the _exact same_ elements at the bottom of my `<body>`.

```html
<script type='text/javascript'>
( function( domain, translations ) {
	var localeData = translations.locale_data[ domain ] || translations.locale_data.messages;
	localeData[""].domain = domain;
	wp.i18n.setLocaleData( localeData, domain );
} )( "default", { "locale_data": { "messages": { "": {} } } } );
</script>

...

<script type='text/javascript'>
( function( domain, translations ) {
	var localeData = translations.locale_data[ domain ] || translations.locale_data.messages;
	localeData[""].domain = domain;
	wp.i18n.setLocaleData( localeData, domain );
} )( "default", { "locale_data": { "messages": { "": {} } } } );
</script>
```

So two things:
1. Why am I seeing two of the exact same scripts being applied to my HTML? This seems unnecessary/bloaty? They also both appear "empty" by default - or am I missing something?
2. I'm using Autoptimize, what can I do to prevent these errors showing (if I even need the scripts at all?)

#### What happened instead
I see errors 😢 

**Screenshots**

![image](https://user-images.githubusercontent.com/43744514/64970546-ef6eec80-d89d-11e9-8570-33660aa7f9b4.png)

**Comment by willstocks** [comment]
Loading `lodash` AND `jquery` (`jquery` being fairly default for everything WP) is a bit of a killer too in terms of bloat/performance, but that's another conversation 😉

**Comment by jeherve** [comment]
I can't seem to be able to reproduce the issue on my end, when using the Slideshow block or any other Jetpack plugin, whether my site is set to English US or English GB.

Can you reproduce on another post that would use only the slideshow block?

Could you also let me know if you use any other plugin that may have an impact here, such as plugins making changes to the block editor?

Thank you.

**Comment by willstocks** [comment]
Hi @jeherve 

I will get another post whipped up for you with just a slideshow block!

I believe the errors show due to the enqueing of `wp.i18n.` which I'm figuring out at the mo... but even then that still doesn't explain why there's two instances/why it's there at all if it's empty/`undefined`?

Ubuntu 18.04
PHP 7.3.9
WP 5.2.3
Gutenberg 6.4

A list of plugins for you:

| name | status | update | version|
| ---| ---| ---| ---| 
| akismet | active| none| 4.1.2
autoptimize| active| none| 2.5.1
autoptimize-criticalcss| active| none| 1.17.1
cloudflare-page-cache| active| none| 1.4
contact-form-7| 	active	| none	| 5.1.4
contact-form-cfdb7| 	active| 	none| 	1.2.4.7
cookie-notice| 	active| 	none| 	1.2.46
custom-permalinks| 	active| 	none| 	1.5.1
easy-table-of-contents| 	active| 	none| 	1.7
enlighter| 	active| 	none| 	3.10.0
ewww-image-optimizer| 	active| 	none| 	4.9.3
featured-image-admin-thumb-fiat| 	active| 	none| 	1.5.3
gutenberg| 	active| 	none| 	6.4.0
jetpack| 	active| 	none| 	7.7.1
kirki| 	active| 	none| 	3.0.45
linx-essentials| 	active| 	none| 	1.2
mailchimp-for-wp| 	active| 	none| 	4.5.5
meta-box| 	active| 	none| 	5.1.2
optimum-gravatar-cache| 	active| 	none| 	1.4.5
wpcf7-recaptcha| 	active| 	none| 	1.2.1
remove-orphan-shortcodes| 	active| 	none| 	1.1
super-progressive-web-apps| 	active| 	none| 	2.0.2
ultimate-blocks| 	active| 	none| 	2.1.4
updraftplus| 	active| 	none| 	1.16.17
w3-total-cache| 	active| 	none| 	0.10.1
wp-optimize| 	active| 	none| 	3.0.11
wp-mail-smtp| 	active| 	none| 	1.6.2
amazon-s3-and-cloudfront| 	active| 	none| 	2.2.1
wordpress-seo| 	active| 	available| 	12.0
youtube-embed-plus| 	active| 	none| 	13.1.1

**Comment by jeherve** [comment]
Thank you. That seems limited to the Slideshow block, and only happens when the Gutenberg plugin is active.

I'm not quite sure what we do differently with `wp.i18n` in that block. @jeffersonrabb Do you have any idea about what could cause this?

**Comment by jeffersonrabb** [comment]
I suspect this is related to Autoptimize—I also haven't been able to repro the exact errors reported, but after installing the plugin and playing  around with some of the settings (`Optimize Javascript Code` | `Aggregate JS Files` | `Force Javascript in <head>` | etc) I'm  getting other Javascript errors which look similar—somehow related to order of loading.  @willstocks could you share your Autoptimize settings so I can try to reproduce the exact issue?

**Comment by willstocks** [comment]
Of course @jeffersonrabb - my AO config:

![image](https://user-images.githubusercontent.com/43744514/65333827-19cfeb00-dbb9-11e9-83ae-460cc48ea952.png)

Exclude scripts: `admin-bar.min.js, seal.js, js/jquery/jquery.js, lodash, webfont.js, /js/jquery.masonry.min.js, /js/jquery/jquery-migrate.min.js, /js/jquery/jquery-migrate.js, /js/imagesloaded.min.js, /wp-content/plugins/contact-form-7/includes/js/scripts.js, superpwa-sw.js, /wp-content/plugins/super-progressive-web-apps/, /wp-content/plugins/super-progressive-web-apps/public/js/register-sw.js, register-sw.js, ytprefs.min.js, fitvids.min.js, /wp-content/plugins/contact-form-7/includes/js/scripts.js, /wp-content/plugins/enlighter/, wp-includes/js/dist, ws-lazysizes.js`

One of the things I don't understand is why I see this code twice in HTML though, if I'm only using a single block (even then, do I really need multiple of these for multiple blocks?)? Or is that a red-herring?

**Comment by jeffersonrabb** [comment]
Thanks @willstocks!

I'm not super clear on it, but I suspect a red herring. This is just my hypothesis, but it looks like that inline JS is produced for each library that includes `i18n`, and the `messages` object contains all of the translatable text. In this case, several libraries use it (`lodash`, `@wordpress/dom-ready`) but contain no translatable text, which is why we're seeing 100% identical code. Similar question here: https://github.com/WordPress/gutenberg/issues/17394. 

I tried your AO settings but still haven't been able to repro. Would you be willing to try two things just so I can determine if I'm on the right track?

1) Clear the AO cache and see if the console error goes away.
2) Deactivate AO, test the page, then reactivate.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
