### ISSUE TITLE
css editor parse problem on "@-moz-document url-prefix() {}" rule

### ISSUE THREAD

**Issue by jjgh** [Automattic/jetpack#1347]
Hi I'm seeing the editor will strip out the internal selector used in a "@-moz-document url-prefix() {}" rule.

For example:

```
@-moz-document url-prefix() { 
  #my-div { 
    padding:10px: 
  }
}
```

after saving becomes becomes:

```
@-moz-document url-prefix() { 
      padding:10px: 
  }
}
```

thus breaking the rule completely.

**Comment by jeherve** [comment]
This is now fixed.
