### ISSUE TITLE
phpcs: linter fails for one-line files

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#13472]
PHPCS linting fails for files like this with an error about empty lines at the end:

```php
<?php
/**
 * Markdown Block.
 *
 * @since 6.8.0
 *
 * @package Jetpack
 */
jetpack_register_block( 'jetpack/markdown' );

```

![image](https://user-images.githubusercontent.com/87168/64924070-83618b00-d7ae-11e9-860d-727016f785d0.png)

(note that there is an empty line correctly at the end of the file)

It works if I add space after the comment block:

```php
<?php
/**
 * Markdown Block.
 *
 * @since 6.8.0
 *
 * @package Jetpack
 */

jetpack_register_block( 'jetpack/markdown' );

```

File I was modifying was [`extensions/blocks/markdown/markdown.php`](https://github.com/Automattic/jetpack/blob/8aeb14fe4fb4ce3241ce5e669e45a6087d3efa75/extensions/blocks/markdown/markdown.php) in PR https://github.com/Automattic/jetpack/pull/13473

**Comment by kraftbj** [comment]
I think this is correct behavior. The first comment at the time is being understood as the file comment, which needs a blank line after it before the rest of the file.
