### ISSUE TITLE
Tiled gallery block: make the block available without Photon module

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#13470]
Tiled gallery block currently depends on the Photon module and PHP class, although it doesn't really use those.

Availability of Photon servers is not limited to Photon module being active for the site.

For Tiled gallery block to be available, people need to know to switch "image CDN" setting on which is very unintuitive:

![image](https://user-images.githubusercontent.com/87168/64922969-0a106b00-d7a3-11e9-82d0-47bd3f1240be.png)

Tiled gallery block should just always be available.

**Comment by jeherve** [comment]
Related: #7576
