### ISSUE TITLE
use of deprecated get_magic_quotes_gpc

### ISSUE THREAD

**Issue by aaronjorbin** [Automattic/jetpack#13480]
Function get_magic_quotes_gpc() is deprecated in `/jetpack/vendor/automattic/jetpack-connection/legacy/class.jetpack-signature.php` on line 229.  This is on PHP7.4.

#### Steps to reproduce the issue

1. Run php7.4 with error reporting turned on
2. Visit the stats page
3. See error

#### What I expected
To be able to run Jetpack using PHP7.4

#### What happened instead
I got an errror notice about a deprecated function

**Comment by kraftbj** [comment]
Fixed in https://github.com/Automattic/jetpack/commit/ad6ddac5d214dfad14f1caafa1945b89bb26a2da#diff-4bfbe382477eca79468868b0db5d3ea4
