### ISSUE TITLE
Sharing: JS error in IE8-

### ISSUE THREAD

**Issue by Firebird75** [Automattic/jetpack#1348]
While using the sharing module in IE 8 (and IE 7), I get the following error :
Object doesn't support property or method 'keys'

it is using the object.keys property that isn't supported in IE < 9.

The workaround would be to add this code to sharing.js on line 17 :
    if (!Object.keys) {
    Object.keys = function(obj) {
        var keys = [],
            key;

```
    for (key in obj) {
        if (obj.hasOwnProperty(key)) {
            keys.push(key);
        }
    }

    return keys;
};
```

}

**Comment by dereksmart** [comment]
We now only support IE11+ 

https://github.com/Automattic/jetpack/blob/master/docs/coding-guidelines.md
