### ISSUE TITLE
Carousel: only add Carousel data to divs that need it

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#13499]
Following up from #13446 .

We currently add the Carousel data to all divs by default, with a few exceptions. It would be nice if we switched to more of a whitelist, where that data would only be added to divs that need it.

See https://github.com/Automattic/jetpack/pull/13446#discussion_r321868272

**Comment by MichaelArestad** [comment]
I'm running into issues with this on my site. You can see an example here:

https://michael.blog/2019/09/19/workbench/

It's adding data to container blocks like Group which adds a cursor to the text on much of my site. :/

**Comment by anaemnesis** [comment]
3172737-zen

**Comment by carinapilar** [comment]
Another one on 29552673-hc

**Comment by jeherve** [comment]
Closing in favor of #13531
