### ISSUE TITLE
Add support for Jetpack open graph tags in AMP stories

### ISSUE THREAD

**Issue by spacedmonkey** [Automattic/jetpack#13492]
AMP Stories are a custom post type in the [AMP Plugin](https://github.com/ampproject/amp-wp).
However, the template does not use call `wp_head`, so the OG tags generated by jetpack are not inserted. AMP stories has a custom action `amp_story_head` which performs a similar action, introduced in https://github.com/ampproject/amp-wp/pull/3039 . 
 
#### Describe the solution you'd like
A solution for this should be pretty simple. In the case `Jetpack_AMP_Support` there is already a hook into `amp_post_template_head` to add og graph tags in this line. 

```
// include Jetpack og tags when rendering native AMP head
add_action( 'amp_post_template_head', array( 'Jetpack_AMP_Support', 'amp_post_jetpack_og_tags' ) );
```
Add support for amp stories could be as simple as adding the following code. 

```
add_action( 'amp_story_head', array( 'Jetpack_AMP_Support', 'amp_post_jetpack_og_tags' ) );
```

#### Additional context
Related: 
https://github.com/Yoast/wordpress-seo/pull/13446
https://github.com/ampproject/amp-wp/pull/3039
https://github.com/ampproject/amp-wp/issues/3179

Looping @westonruter and @swissspidy for visibility.

**Comment by jeherve** [comment]
This is in progress in #13492
