### ISSUE TITLE
Predominant color and low quality placeholders for lazy load

### ISSUE THREAD

**Issue by MediaMaquina** [Automattic/jetpack#13518]
Lazy load is great. But it would be nice for user experience to see better placeholders (I'm aware of the filter, but it's not enough), I'd like a unique placeholder for each image.

Two techniques come to mind:

1. Predominant color placeholders: 
Shows a solid image of the predominant color, used by Google images, example:
![google-images-placeholder](https://user-images.githubusercontent.com/8179611/65448014-1d24da00-de38-11e9-8701-a56992e5241a.png)

2. Low quality placeholder:
Consists on using a small pixelated version of the real image and apply a blurry CSS filter to it.
Details: https://jmperezperez.com/medium-image-progressive-loading-placeholder/

This is probably wishful thinking, but was worth asking for. Thanks!

**Comment by jeherve** [comment]
Noting that Jetpack ships with Tonesque, which can be used to pick a predominant color for each image.
https://github.com/Automattic/jetpack/blob/3ab7fecabb4566d450c0eaab6ff7b6ebfcb63f00/_inc/lib/tonesque.php

This would have an impact on performance though, as we would need to fetch that color in the first place. This may defeat the point of Lazy Loading images in the first place.
