### ISSUE TITLE
Theme Tools / Infinite Scroll: add support for Twenty Twenty

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#13511]
Twenty Twenty is expected to ship with WordPress 5.3 in November. It is currently being developed here:
https://github.com/WordPress/twentytwenty

In the past, and with previous default themes, we've added a number of compatibility files and functions to make sure new WordPress site owners had the best experience they could get when using the default theme and Jetpack. In practice, it meant adding the following:

- [x] Add Infinite Scroll support and tweak CSS to make sure the IS buttons look good.
- [x] Tweak CSS for Sharing buttons / Likes / Related Posts
- [x] Alter Gallery widget default width.
- [x] Style all Jetpack widgets to match the style of the theme.
- [ ] Add Content Options support
- [x] Ensure that sharing buttons and Likes are not hooked into the excerpt when one is added to a post.

See how it was done for Twenty Nineteen for example: https://github.com/Automattic/jetpack/blob/50fe8a75fd8cfaa2aad34228ca3f02bb7ec60077/modules/theme-tools/compat/twentynineteen.php

**Comment by jeherve** [comment]
Got a PR started to start tackling those things and addressing things as I test the theme.

**Comment by jeherve** [comment]
> Add Content Options support

Leaving this out for now. The theme itself comes with some basic theme options. Let's see if Content Options become needed in the future, either here or on wpcom.

**Comment by arunsathiya** [comment]
@jeherve May I ask some questions about infinite scrolling functionality on Twenty Twenty theme? I identified the following:

- On a WordPress.org site with blog archive set to show 3 posts, and with `Load more posts as the reader scrolls down` enabled on Jetpack settings, I am not able to see more posts as I scroll down. I see a `Older posts` button in that place.
- On the same site, with a WooCommerce product category/archive though, only a few first products appear (Not 3 unfortunately, but 12, which is a different issue) and there is no button to see more products.

| <img width="1179" alt="Screenshot 2020-09-27 at 2 55 51 PM" src="https://user-images.githubusercontent.com/18581859/94361445-f72cb800-00d1-11eb-9e97-002372e5fbe3.png"> | <img width="805" alt="Screenshot 2020-09-27 at 2 55 37 PM" src="https://user-images.githubusercontent.com/18581859/94361447-fac03f00-00d1-11eb-9cdd-1b8d22c755cd.png"> |
|------|------|
| <img width="757" alt="Screenshot 2020-09-27 at 2 55 34 PM" src="https://user-images.githubusercontent.com/18581859/94361449-fbf16c00-00d1-11eb-9f30-c4f8e78e04d6.png"> | <img width="1541" alt="Screenshot 2020-09-27 at 3 00 20 PM" src="https://user-images.githubusercontent.com/18581859/94361481-30652800-00d2-11eb-9732-646d6894a025.png"> | 

Found when working on 3352735-zen. This information may not be sufficient for your testing, in which case, feel free to ping me for access to my test site.

**Comment by jeherve** [comment]
> On a WordPress.org site with blog archive set to show 3 posts, and with Load more posts as the reader scrolls down enabled on Jetpack settings, I am not able to see more posts as I scroll down. I see a Older posts button in that place.

- Do you happen to have footer widgets on that site?
- What happens when you click on the "Older posts" button? Does this trigger Infinite Scroll?

> On the same site, with a WooCommerce product category/archive though, only a few first products appear (Not 3 unfortunately, but 12, which is a different issue)

It may be worth trying to test with #17130 applied to your site, to see if that would solve the issue. 

Let me know how that goes!
