### ISSUE TITLE
Post Dates Displayed By Default for Related Posts

### ISSUE THREAD

**Issue by xyu** [Automattic/jetpack#1352]
In #778 we merged in a change that was supposed to allow post dates to be optionally displayed as contextual information for related post items. This should have been off by default (hidden via CSS) however it appears this is broken and post dates are displayed by default.

Should / can this be changed back?

/cc @georgestephanis

**Comment by lancewillett** [comment]
This is now obsolete, as the date option for Related Posts isn't respected in the UI anymore.
