### ISSUE TITLE
SSO: Password field disabled when using the WordPress nightly build

### ISSUE THREAD

**Issue by desrosj** [Automattic/jetpack#13551]
With WordPress.com login enabled in Jetpack, the password field is disabled when visiting the WP login screen.

#### Steps to reproduce the issue

1. Make sure you are running 5.3 Beta 1, or the latest nightly.
2. Install and activate Jetpack.
3. View the WordPress login screen.
4. Click "Login with username and password" link.
5. Password field is disabled.

#### What I expected
I expected the password field to be usable.

I have been able to reproduce this in Firefox (nightly), and Safari (12.1.2) on MacOS.

**Screenshots**
![Screen Shot 2019-09-26 at 9 50 34 AM](https://user-images.githubusercontent.com/359867/65693987-25049a00-e043-11e9-8883-f7c130326c5f.png)

**Comment by jeherve** [comment]
Good catch! 

It also doesn't seem to be displayed properly here:

![image](https://user-images.githubusercontent.com/426388/65695057-1b952500-e077-11e9-98ac-9711d8277fcd.png)

I think this may be linked to [#46349-code](https://core.trac.wordpress.org/ticket/#46349), but will need to run more tests. Noting that [#42888-core](https://core.trac.wordpress.org/ticket/42888) also introduced some changes.

**Comment by desrosj** [comment]
_May_ also be worth looking at any changes related to [#47153-core](https://core.trac.wordpress.org/ticket/47153) too, which are continuing to be tweaked.
