### ISSUE TITLE
Backups: Backup status in wp-admin doesn't match VaultPress dashboard

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#13568]
#### Steps to reproduce the issue

1. Create a new site on Jurassic.Ninja with a plan that includes backups
2. In wp-admin, visit `/wp-admin/admin.php?page=jetpack#/security`
3. See that status is "Your site is backed up and threat-free."
4. Click link to "configure your security scans" which goes to https://dashboard.vaultpress.com/

#### What I expected
VP to show backup completed

#### What happened instead
VP shows "Backups: never"

Secondarily, in VP it shouldn't say there are "No threats found" if we haven't performed a backup yet. We should say "Waiting for backup"

**Screenshots**

WP Admin:

<img width="977" alt="backups-wp-admin" src="https://user-images.githubusercontent.com/51896/65795403-0a075800-e11f-11e9-8b1e-e60f7fa210ec.png">

VaultPress Dashboard:

<img width="881" alt="vp-dash" src="https://user-images.githubusercontent.com/51896/65795414-1095cf80-e11f-11e9-9af9-decd001f0f9b.png">

**Comment by briancolinger** [comment]
Fixed in r15096-vaultpress and r15097-vaultpress.
