### ISSUE TITLE
Tiled Gallery: Photon strips color profile information

### ISSUE THREAD

**Issue by jordesign** [Automattic/jetpack#13561]
It appears that when images are inserted into a Tiled Gallery they include the string `?strip=all` in the Photon URL.  This strips EXIF data and color profile information (as documented [here](https://developer.wordpress.com/docs/photon/api/#strip)).

The result is that when an image that has been saved with a color profile _other_ than sRGB is inserted - the color will shift in a way the user doesn't expect. When the thumbnail is clicked - it loads the image _without_ the color profile stripped which makes it even more obvious

By comparison - the native 'Gallery' and CoBlocks 'Masonry' gallery insert the thumbnails _without_ stripping the color profile. The behavior should be consistent across the three gallery types.

#### Steps to reproduce the issue

1. Start a new Page or Post
2. Insert a 'Tiled Gallery' block
3. Include an image that has a color profile saved as part of the file ([here's one you can test](https://lamontjordan.files.wordpress.com/2019/09/img_9901-test.jpg) )
4. Publish post/page

#### What I expected
The image to be displayed on the page as it shows on my local machine, in the media library, and when loaded directly in the browser

#### What happened instead
The image shows with the colors shifted to different tones

#### Testing/Example ###

You can review this post which contains a default Gallery, Tiled Gallery and Masonry Gallery for comparison: https://lamontjordan.blog/2019/09/25/testing-a-gallery/

**Screenshots**

Result of color shift
![](https://cldup.com/MgY2LIssOK-2000x2000.png)

**Comment by jeherve** [comment]
cc @sirreal; do you remember why we had needed that parameter in #12061?

**Comment by sirreal** [comment]
> do you remember why we had needed that parameter in #12061?

It looks like an oversight and we should have used `?strip=info` or just omitted it.

**Comment by kristarella** [comment]
We have another report of this in 2413433-zen

If it's not needed we would love for it to be removed :)

**Comment by jordesign** [comment]
Closing as this is reslved in https://github.com/Automattic/jetpack/pull/13735
