### ISSUE TITLE
Activity Log tooltip and banner help links go to different URLs

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#13572]
#### Steps to reproduce the issue

1. On a newly-connected Jetpack site, head to My Plan and click the "Activity Log" link
2. You will be taken to https://wordpress.com/activity-log/your-site-url.com
3. A tooltip appears with a link to https://jetpack.com/support/activity-log/
4. A banner appears with a link to https://en.blog.wordpress.com/2018/10/30/introducing-activity/

#### What I expected
Documentation to get started with activity log should be in one place

#### What happened instead
Users are being directed to two different places to learn more about Activity Log

**Comment by codestor4** [comment]
@gravityrail Not sure if this is fixed. I'm not seeing a tool-tip. Also, not seeing `https://jetpack.com/support/activity-log/` in the source code on `/activity-log/site-url` page.

I'm only seeing the banner as follows -

![Screen Shot on 2019-10-03 at 18:35:52](https://user-images.githubusercontent.com/20779676/66129064-c9bb4480-e60c-11e9-8ae4-a064a692c8bc.png)

**Comment by IAMNITESHPANDIT** [comment]
this will be kind of a website where we share our services. 
if anyone need  website customization in word press then contact us. 

Thank you

**Comment by jeherve** [comment]
Closing as I can't seem to see the tooltip anymore either.
