### ISSUE TITLE
Carousel: Gallery blocks cannot accept extra data attributes.

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#13604]
Discovered by @kbrown9 in #13582 :

We have a `jp_carousel_add_data_to_container` filter that allows plugins to add any data attributes they would like to carousel markup. Currently, Jetpack adds one attribute (`data-carousel-extra`) itself, so this is only an issue for third-party plugins using this filter.

The string replacement [here](https://github.com/Automattic/jetpack/blob/master/modules/carousel/jetpack-carousel.php#L545) relies on a needle of `<ul class="wp-block-gallery`. This will succeed the first time, but will fail for any additional attempts, since the first attempt inserts its data before the `class` attribute – meaning our needle no longer exists on any subsequent attempts.

#### Steps to reproduce the issue

1. Create a post with a Gallery block, and set the Link To dropdown to "Media File" (this is what triggers the carousel).
2. Add an additional element to the `$extra_data` array [here](https://github.com/Automattic/jetpack/blob/master/modules/carousel/jetpack-carousel.php#L526) (or create a hook on `jp_carousel_add_data_to_container` somewhere that appends more elements).
3. Publish the post, and inspect the carousel markup.
4. Observe the `data-carousel-extra` data attribute, but not the extra data you added yourself.

#### What I expected
All data attributes should be present in the front-end markup.

#### What happened instead
Only the first data attribute of the filtered `$extra_data` array is present.

**Screenshots**
n/a

**Comment by jeherve** [comment]
Closing this in favor of #13531.
