### ISSUE TITLE
Deprecated: Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by aaronjorbin** [Automattic/jetpack#13616]
This is new in PHP7.4. 
At least two instances that I've seen in Jetpack 7.8:

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/daily.jorb.in/wp-content/plugins/jetpack/modules/shortcodes.php on line 94

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/daily.jorb.in/wp-content/plugins/jetpack/modules/shortcodes.php on line 122

**Comment by kraftbj** [comment]
Fixed via https://github.com/Automattic/jetpack/pull/13584/files#diff-a567a793c433f89e6d242ea0fa21aa91

**Comment by kraftbj** [comment]
To add context - we're aiming November's Jetpack 7.9 for PHP 7.4 compat since 7.4 GA is in late November, so picked up a lot of fixes post-7.8 code freeze last week.
