### ISSUE TITLE
Comments: Can't leave a comment while logged in Safari

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#13619]
Currently Safari doesn't allow the cookies to be read or set from an iframe. This cause a number of issues in Jetpack for safari users.

#### Steps to reproduce the issue
Using latest Safari on Mac. 
1. Connect Jetpack and set you site to use the jetpack comments. 
2. Go to a blog post. Try to leave a comment by logging into any of the services. 
3. Notice that you are not able to login. 

#### What I expected
Be able to login to leave a comment.

#### What happened instead
You are not able to login.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
