### ISSUE TITLE
Deprecation: Update wp.editor.* to wp.blockeditor.*

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#13612]
Various wp.editor functions/components have been deprecated in WordPress 5.3. This is to keep it on the radar but likely need to sit until 5.3 is our minimum.

`wp.editor.withColors is deprecated. Please use wp.blockEditor.withColors instead.`
`wp.editor.BlockIcon is deprecated. Please use wp.blockEditor.BlockIcon instead.`
etc

The full list (as of 5.3b2): https://build.trac.wordpress.org/browser/trunk/wp-includes/js/dist/editor.js?rev=46163#L14712

#### Steps to reproduce the issue

1. Open the block editor.
2. Add various Jetpack blocks, e.g. Business Hours.

#### What I expected
Clean console.

#### What happened instead
Deprecation notice in the console.

**Screenshots**
n/a

**Comment by jeherve** [comment]
It's all good now, it's been updated. Closing.
