### ISSUE TITLE
Jetpack GIF block - fix alignment of search field and search button

### ISSUE THREAD

**Issue by joanrho** [Automattic/jetpack#13646]
Breaking this one out of @simison's original mega-issue #13618 that lists out several visual regressions so we can tackle them one by one in separate PRs.

The alignment of the search field and search button are off in the Jetpack GIF block. Here are mockups of what it should ideally look like:

**Before/After:**
<img width="1773" alt="Screen Shot 2019-10-03 at 4 02 36 PM" src="https://user-images.githubusercontent.com/204742/66167485-7a1e4e00-e5f7-11e9-831b-bf57408b8a12.png">

**Comment by simison** [comment]
See also https://github.com/WordPress/gutenberg/pull/17616
