### ISSUE TITLE
Instant Search: add ARIA live region

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#13644]
#### Describe the solution you'd like
The filtering and sorting options in Instant Search alter content earlier in the document without a page reload. To help those using screenreaders and other assistive devices, we should add `aria-controls` and `aria-live` attributes as described here:

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

#### Additional context

Instant Search is a prototype feature currently under development.

**Comment by diegohaz** [comment]
A note on `aria-controls`:

The only assistive technology that used it was JAWS, and [they've removed support for it](https://twitter.com/stevefaulkner/status/1138834162562019328). Now it does nothing.

It seems that it would be very confusing to users even if supported: https://www.heydonworks.com/article/aria-controls-is-poop

**Comment by bluefuton** [comment]
Thanks for that information @diegohaz.

Is `aria-live="polite"` on the search results still a potentially useful addition?

**Comment by diegohaz** [comment]
@bluefuton Can you point me to the UI so I can test it?

**Comment by jsnmoon** [comment]
Hi @diegohaz, you might be interested in #13884 which includes accessibility fixes and instructions for setting up the Instant Search interface.

**Comment by diegohaz** [comment]
Sure! I'll have a look by the end of the week! I've never played with this repository yet though. Is this doc the best way to get started? https://github.com/Automattic/jetpack/blob/master/docs/development-environment.md

**Comment by jsnmoon** [comment]
I found the [Docker setup](https://github.com/Automattic/jetpack/blob/master/docker/README.md#to-get-started) to be the easier to work with. You need to:

1. Run `yarn build` to build the assets
2. Run `yarn docker:up` to spin up the instance.
3. Use [ngrok](https://github.com/Automattic/jetpack/blob/master/docker/README.md#using-ngrok-with-jetpack) to set a domain for your local installation.
