### ISSUE TITLE
Recipe Shortcode: Create Inline Shortcode for Recipe Image

### ISSUE THREAD

**Issue by RCowles** [Automattic/jetpack#13660]
Jetpack's Recipe Shortcode provides a few inline shortcodes to customize the output of the `[recipe]` shortcode itself. For example, `[recipe-notes]` allows the user to customize where the notes section is output:
https://github.com/Automattic/jetpack/blob/89a9af96b669e2e5a2ed47d3f3e07c804d6e0dd0/modules/shortcodes/recipe.php#L322-L359

When it comes to images, users currently have the ability to assign an image as an attribute of the `[recipe]` shortcode. That image is then output at the top of the rendered recipe here:
https://github.com/Automattic/jetpack/blob/89a9af96b669e2e5a2ed47d3f3e07c804d6e0dd0/modules/shortcodes/recipe.php#L288-L294

This `image` attribute provides the proper schema requirements for Google, but the user is unable to control the placement of the image within the recipe. It would be nice if we could add a `[recipe-image]` shortcode to allow the user to control the placement of the assigned image. It could be similar to the existing `[recipe-notes]` and `[recipe-ingredients]` shortcodes.

**Comment by kraftbj** [comment]
Related https://github.com/Automattic/jetpack/issues/2888

**Comment by ChaosExAnima** [comment]
Closed by #13841.
