### ISSUE TITLE
Photon: feature activated when cloning site locally

### ISSUE THREAD

**Issue by isabellachen** [Automattic/jetpack#13679]
#### Steps to reproduce the issue

1. Connect remote WP site to Jetpack and Wordpress.com and enable site accelerator
2. Now images will be served from WP CDN on the remote site
3. Import the site to local WP installation, everything works until the wp_options table is imported
4. Now images are served from non-existant WP CDN location because local site is not connected

#### What I expected
I expected since the local installation is not connected to Jetpack (actually Jetpack is not ever activated in the local environment) that the images should not be served from the CDN

#### What happened instead
The srcset values of img tags are of the form https://i2.wp.com/mh.local/wp-content/uploads/2019/09/photo-HDR.jpg when I need them to be, simply,  https://mh.local/wp-content/uploads/2019/09/photo-HDR.jpg 

Not sure I know what the best way to deal with this is. Can I simply remove or change some value in the wp_options table so this does not happen? I'm not sure why this is happening even if Jetpack is not connected, but since I don't have any other plugin that does such a thing and my theme does not do such a thing, I really don't think anything else could be causing this.

**Comment by jeherve** [comment]
That's indeed to be expected; when you cloned your site to a local copy, you also cloned the status of all Jetpack features on your site, thus turning on Jetpack's Image CDN feature on your local site.

I would recommend that you deactivate the Image CDN module on your development site; that should fix things. You can do so from this page:
`http://mh.local/wp-admin/admin.php?page=jetpack_modules`
Or via WP Cli:
`wp jetpack module deactivate photon`

If that doesn't help, could you clarify a few things for me:
- Is the plugin active on your local site, or deactivated?
- If it is active, do you see a Development mode notice when you go to Jetpack > Settings in your dashboard?
- Does it help when turning on [Jetpack's Development mode](http://jetpack.com/support/development-mode)?
- If you still see images being served via the CDN when the plugin is inactive, does this happen for all images on your site, or specific images, served by a widget / plugin? What happens with newly uploaded and inserted images?

Thank you!

**Comment by isabellachen** [comment]
I realised I needed to put `const JETPACK_DEV_DEBUG = TRUE;` in my wp-config file because my site has a period in the hostname. Thanks a lot for the tips :)
