### ISSUE TITLE
Sharing: update reCaptcha to the new reCaptcha service

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1368]
The Email sharing button includes an option to use reCaptcha ([ref](http://jetpack.me/2013/04/15/recaptcha-email-sharing-button/)):
https://github.com/Automattic/jetpack/blob/3.2.1/modules/sharedaddy/recaptchalib.php

It'd be nice to update to the new version of reCaptcha instead:
- https://developers.google.com/recaptcha/
- https://github.com/google/ReCAPTCHA/blob/master/php/recaptchalib.php

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/the-new-recaptcha-and-jetpack-email-sharing?replies=1

**Comment by jkudish** [comment]
passing along to @aduth master of sharing buttons
