### ISSUE TITLE
Calypsoify: update to be compatible with WordPress 5.3 admin CSS changes

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#13704]
#### Steps to reproduce the issue

1. Go to `https://yoursite.com/wp-admin/plugins.php?calypsoify=1`
2. On WP 5.2, you'll see a screen like this:
![image](https://user-images.githubusercontent.com/426388/66557261-ddf1cb00-eb51-11e9-9381-1366639cb016.png)

3. On WP 5.3, you'll see this:
![image](https://user-images.githubusercontent.com/426388/66557597-725c2d80-eb52-11e9-991a-75f220d84609.png)

Master issue: #13597

**Comment by MichaelArestad** [comment]
I'm not having success in testing this. Can you describe in more detail what I need to do to test? (I always forget how to test this particular module.)

**Comment by MichaelArestad** [comment]
I'm unable to reproduce.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1123119/67606623-370b5280-f73f-11e9-9c4e-dd1bec443bca.png">

**Comment by jeherve** [comment]
Same here, it seems that the problem is now fixed. Closing.
