### ISSUE TITLE
Jetpack Authors Widget - improve Author/Post text hierarchy

### ISSUE THREAD

**Issue by joanrho** [Automattic/jetpack#13718]
The Jetpack Authors Widget needs better Author/Post text hierarchy and styling.

**Before/After**
<img width="914" alt="Screen Shot 2019-10-10 at 4 38 34 PM" src="https://user-images.githubusercontent.com/204742/66611679-86b52000-eb7c-11e9-89d3-9ce55c3c9583.png">

**Comment by MichaelArestad** [comment]
This looks good enough to move forward with dev. The only remaining thing would be to make sure it looks good with a widget title (if it allows one).

**Comment by joanrho** [comment]
Yep, looks good, just like all the other widgets with titles.

<img width="409" alt="Screen Shot 2019-10-10 at 4 49 37 PM" src="https://user-images.githubusercontent.com/204742/66612216-4ce51900-eb7e-11e9-9bc6-0c61ecd8e761.png">

**Comment by jeherve** [comment]
Fixed in #13516
