### ISSUE TITLE
Jetpack Ads block - remove white background color

### ISSUE THREAD

**Issue by joanrho** [Automattic/jetpack#13715]
The current Jetpack Ads block has a white background on all the blocks that should be removed.

**Before:**
<img width="317" alt="Screen Shot 2019-10-10 at 2 43 12 PM" src="https://user-images.githubusercontent.com/204742/66604949-60878400-eb6c-11e9-9b96-b665eb6f6bb3.png">

**After:**
<img width="338" alt="Screen Shot 2019-10-10 at 2 43 36 PM" src="https://user-images.githubusercontent.com/204742/66604957-654c3800-eb6c-11e9-9605-4612b627b7a8.png">

**Comment by folletto** [comment]
Just to be clear: the "after", the gray area is meant to be a placeholder with transparency?

**Comment by joanrho** [comment]
@folletto Sorry I missed your Q above, but yes. That's correct.
