### ISSUE TITLE
Publicize: Include links to posts in each WPML language

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#13726]
The customer in 2414228-zen would like to be able to have the Publicize posts that go to their social networks include links to all of the various languages they have set up with WPML on their site.

> you could get the title, URL, Description of each post's language and post it in FB in one post consisting of multiple translations for instance?

**Comment by kraftbj** [comment]
I'd vote wontfix for this one. There is already some filters to edit the message on the client side which will probably be the best route. Making this change on the WP.com side is not feasible.

**Comment by jeherve** [comment]
> There is already some filters to edit the message on the client side which will probably be the best route. 
I would agree.
