### ISSUE TITLE
Jetpack free and premium blocks not visible in block picker until activated in Settings

### ISSUE THREAD

**Issue by joanrho** [Automattic/jetpack#13733]
<img width="1311" alt="Screen Shot 2019-10-11 at 4 49 07 PM" src="https://user-images.githubusercontent.com/204742/66689180-14f5d880-ec47-11e9-961c-5643e05d8257.png">

The following three blocks are not visible in the block picker until a user manually goes into settings to activate the modules. Unless the user knows to manually do this, these blocks are hidden and will likely go overlooked.

1.  “Subscriptions” (available on all plan levels, including Free) in /wp-admin/admin.php?page=jetpack#/discussion
2. “Related Posts” (available on all plan levels, including Free) in /wp-admin/admin.php?page=jetpack#/traffic
3. “Ads” (available on Premium and Pro plan levels) in /wp-admin/admin.php?page=jetpack#/traffic

The "Simple Payments" block does not need to be activated with any toggle in Settings but only Premium/Pro users can see the block (it's entirely hidden from Free/Personal users)

Suggested solutions:
* **Option 1:** Have numbers 1 and 2 automatically activated for all plan levels and number 3 activated for just the Premium/Pro levels. This will reveal these blocks in the block picker.
* **Option 2:** Show a disabled block icon for all three blocks in the block picker and indicate for 1 and 2 that the settings need to be activated first before the block can be used and show an upgrade nudge for 3 to be activated (can also include "Simple Payments" here too: disabled icon + upgrade nudge for Free/Personal plan users).

#### Primary issue

#32401

**Comment by jeherve** [comment]
This is probably part of a bigger project about improving visibility of all blocks, including those that are not available yet in the editor because the module is not active.

Related: #12367

Internal reference, with links to previous conversations about this in the comments:
pafL3P-cP-p2

**Comment by AaronCHKL** [comment]
MINDER-WITH (MINDER-HOST)

**Comment by AaronCHKL** [comment]
<meta name="expected-hostname" content="github.com">
    <meta name="js-proxy-site-detection-payload" content="MDE4NDg0NzNlZGEwZmQ3ZjdiYWUxZTlkNWY1NGE1MzkyYzUwY2M3NDI1MWMyZTYwZGFhZjgzODFjYTg2Y2FmMXx7InJlbW90ZV9hZGRyZXNzIjoiNDUuOS4xMC4yMTUiLCJyZXF1ZXN0X2jfhylkIjoiODBCOTo0QzA5OjJCMjU3QjA6M0ZENUNBRjo1REE2QUM0NyIsInRpbWVzdGFtcCI6MTU3MTIwNDE2OCwiaG9zdCI6ImdpdGh1Yi5jb20ifQ==">

    <meta name="enabled-features

**Comment by jeherve** [comment]
Closing in favor of #32401
