### ISSUE TITLE
Instant Search: correct formatting for tags/categories/taxonomies

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#13749]
The sidebar filtering for the sidebar currently displays the slug of the tag/category/taxonomy term. We should be displaying the actual name that the user has set. This requires the following changes:
- the aggregation and filtering needs to run against a `*.name.raw` field
- the categories and tags need to have `.name.default.raw` fields created (we don't seem to currently have them, but we do for taxonomies)

**Comment by jsnmoon** [comment]
@bluefuton does #14437 fix this issue as well? Or does this require `slug_slash_name` integration?

**Comment by bluefuton** [comment]
@jsnmoon #14437 partly fixes it (just for custom taxonomies) but https://github.com/Automattic/jetpack/pull/14492 will fix it for tags and categories too 👍

**Comment by bluefuton** [comment]
Fixed in #14492.
