### ISSUE TITLE
Availability to publicize wordpress post to Stocktwits.com

### ISSUE THREAD

**Issue by sstowers** [Automattic/jetpack#13754]
#### Is your feature request related to a problem? Please describe.

No, this is not a problem but a gap in functionality.

#### Describe the solution you'd like

Would like the  option to publicize wordpress posts to Stocktwits.com

#### Describe alternatives you've considered

Zapier.com

**Comment by kraftbj** [comment]
Howdy! Thanks for the request. At this time, we are not expanding Publicize to new social networks, so I'm going to close the request. We will keep it in mind for when we re-examine the social networks that are integrated with Publicize.

Thanks!
