### ISSUE TITLE
Social Menu & Social Media Icons: Add TikTok Support

### ISSUE THREAD

**Issue by mbhthompson** [Automattic/jetpack#13765]
#### Is your feature request related to a problem? Please describe.

No

#### Describe the solution you'd like

The chain icon should instead display a TikTok icon.

![](https://cld.wthms.co/AQlTnf+)

#### Describe alternatives you've considered

There aren't any alternatives. This seems to be a straightforward solution - similar to #3181.

#### Additional context

Requested in 2426575-zen

**Comment by rahul020691** [comment]
Another user requested tiktok icon yesterday. hc-19676905

Are we adding these icons? Tiktok is very popular now. I am sure other users might like it too.

**Comment by galbaras** [comment]
+1.

Meanwhile, [this icon](https://www.noff.com.au/wp-content/themes/noff/images/tiktok.svg) may be a starting point to use with CSS.

**Comment by kathrynwp** [comment]
Also requested in 19879139-hc

**Comment by rahul020691** [comment]
Also requested in 20394509-hc

**Comment by wynwin** [comment]
Also requested 3014671-zen

**Comment by xpurichan** [comment]
Request in 26158314-hc

**Comment by davipontesblog** [comment]
Request in 26963246-hc

**Comment by sdixon194** [comment]
PR to add TikTok (and a bunch of other logos): https://github.com/Automattic/jetpack/pull/18563

**Comment by DavidSaladu** [comment]
Also requested in 4334670-zd-woothemes

**Comment by sdixon194** [comment]
@DavidSaladu TikTok has been added as a social icon for Jetpack, however there are some themes, like Varia and its child themes, that have their own social links implementation for the social menu and don't use Jetpack's. I'd recommend adding the request in the theme repo here: https://github.com/Automattic/themes/issues/4355
