### ISSUE TITLE
Pinterest save button not offering multiple image choices

### ISSUE THREAD

**Issue by keilabl** [Automattic/jetpack#13768]
#### Steps to reproduce the issue

1. Go to website page with sharing icons enabled 
Example: https://practicaltyping.com/2019/08/06/sonic-x-characters-part-1-2/
2. Scroll down to the bottom of the page
3. Click on Pinterest 'Save' button (amongst the list of other sharing icons)
4. You'll see the page's featured image automatically selected, with no option to pick a different image from the page

#### What I expected
I expect the dialogue prompted by thte Pinterest 'Save' button to show other images from the page so I can choose the best one or most preferred one. This is pretty standard functionality for a Pinterest 'Save' button but for some reason is not working in Jetpack. (I was able to create my own Pinterest 'save' button that can do this.. but I would prefer to have all of my sharing icons listed together and not have a Pinterest button awkwardly off by itself.) Jetpack does provide 'save' buttons when a user hovers over individual images on the page, but most users aren’t going to scroll back up the page to hover over an image that has been specifically designed to be a pin. It's important for marketing for users to easily be able to share pages from a website. 

#### What happened instead
As explained, the featured image was automatically selected with no option to choose a different image. 

**Screenshots**
An screenshot of clicking the "save" button on the page I listed earlier:
![pinterestscreenshot](https://user-images.githubusercontent.com/56684614/67011962-8bb72980-f0be-11e9-95b4-b2c651297595.png)

I expect something more like this (pulled from a random blog):
![pinterestcapture](https://user-images.githubusercontent.com/56684614/67012742-e9984100-f0bf-11e9-9b76-6853cb0f90c6.PNG)

**Comment by jeherve** [comment]
Thanks for the contribution. This is something we've discussed and are currently tracking in #2650. I'll consequently close this issue as duplicate.
