### ISSUE TITLE
Instant Search: Make it possible to configure `w.js` ( Tracks ) to only use a short-lived in-memory anon ID

### ISSUE THREAD

**Issue by bperson** [Automattic/jetpack#13762]
Following the merge of #13730, I tested it further and the default behavior of `w.js` is to rely on cookies, we should explore how we can have the kind of short-lived non-tracking-across-pageviews anonID mentioned [in this comment](https://github.com/Automattic/jetpack/pull/13730#issuecomment-541498350).

#### What happened instead

**Screenshots**

**Comment by jsnmoon** [comment]
It seems like this is happening because `send` invokes `loadIdentity`. What do you think about performing `clearIdentity` on page load? This would ensure that the user identifying cookie is reset before we send any pixels.

**Comment by gibrown** [comment]
Would that also clear the data in the browser? Or just for this page load? I don't think we want to clear the identity for logged in users, just make sure that we don't use it.

**Comment by jsnmoon** [comment]
AFAIK: it'll clear the user identification cookie and generate/assign a new anonymous cookie, thereby discarding data received from any previous invocation of `identifyUser`.

**Comment by jsnmoon** [comment]
@bperson: [This commit](https://github.com/Automattic/jetpack/commit/9ba6bd064096ef6275f88b38880ac84439f43520) adds a `clearIdentity` call on every initial page load. Let me know what you think -- I plan on pushing this out along with #13761.

**Comment by gibrown** [comment]
I suspect that we should not clear the cookie since that may mess with other analytics we are doing elsewhere, but I don't really know enough here.

**Comment by jsnmoon** [comment]
> @bperson: [This commit](https://github.com/Automattic/jetpack/commit/9ba6bd064096ef6275f88b38880ac84439f43520) adds a `clearIdentity` call on every initial page load. Let me know what you think -- I plan on pushing this out along with #13761.

The above commit has been pushed to master.
