### ISSUE TITLE
Post by Email: Draft Post Email Notification 

### ISSUE THREAD

**Issue by kriskorn** [Automattic/jetpack#13767]
#### Steps to reproduce the issue

1. Turn on _Post by Email_ feature in WordPress.com by following the instructions here - https://en.support.wordpress.com/post-by-email/#generating-a-post-by-email-address
2. Send a message in via email with the `[status draft]` shortcode
3. Site administrator will receive a **New Post** email if they are following their site.

#### What I expected

Not to receive a new post notification, as it is a **draft** post. 

#### What happened instead

A new post email notification was sent out.

<img width="530" alt="post-by-email-draft" src="https://user-images.githubusercontent.com/12064241/66997381-02fab680-f0db-11e9-8bb3-32c8342f005e.png">

- - - - - 

User reported: 13776745-hc
Internal troubleshooting: p2EDhh-V3-p2

It seems that behaviour only happens on WordPress.com and not self-hosted sites, as a notification was not sent out in that case. Moreover, it seems it happens only with newly generated emails in WP Admin. If an older generated email address was used, then a notification was not sent out. 

Is this expected, as the email notification indicates like a new post was published on the site, which actually has not happened, as the post is a draft. It also seems that this email is only sent to the administrator of the site.

**Comment by jeherve** [comment]
> It seems that behaviour only happens on WordPress.com

Since this only impacts WordPress.com and is about a feature that lives in the  WordPress.com codebase and not in Jetpack, it may make more sense to report it there, in wpcom.trac.

You can then close this issue I think.

**Comment by kriskorn** [comment]
Closed in favor of 8173-wpcom.
