### ISSUE TITLE
Related Posts on AMP: Lower-priority filter hooks are removed

### ISSUE THREAD

**Issue by micropat** [Automattic/jetpack#13775]
Filter hooks with a low-priority number of `41` or greater are removed on AMP pages when the Related Posts module is activated and setup.

#### Steps to reproduce the issue

1. Add the PHP code below to the site's [`functions.php`](https://codex.wordpress.org/Functions_File_Explained) or similar.
2. Activate & setup the official [AMP plugin](https://wordpress.org/plugins/amp/).
3. Observe that additional content is added to post content on an AMP page.
4. Activate & setup Jetpack's Related Posts module.
4. Observe that additional content is _not_ added to post content on an AMP page.

```
add_filter( 'the_content', 'add_something_to_content_filter', 41 );

function add_something_to_content_filter( $content ) {
	$original_content   = $content;
	$add_before_content = 'SOMETHING BEFORE CONTENT.';
	$add_after_content  = 'SOMETHING AFTER CONTENT.';
	
	$content = $add_before_content . $original_content . $add_after_content;

	return $content;
}
```

#### What I expected
`SOMETHING BEFORE CONTENT.` should prepend content.
`SOMETHING AFTER CONTENT.` should append content.

#### What happened instead
No additional content is added to content.

**Comment by jeherve** [comment]
We've been looking at this as well, most likely thanks to a customer we have in common. :)

Internal reference: 4412-gh-jpop-issues

@kbrown9 has been spearheading this investigation so far, and here is what she's found so far:

> This issue is caused by a bug in WordPress that was first reported ~10 years ago. Multiple tickets have been opened for this over the years, but a fix hasn't been accepted.
> 
> https://core.trac.wordpress.org/ticket/9968
> https://core.trac.wordpress.org/ticket/40393
> https://core.trac.wordpress.org/ticket/40685
> 
> Until this gets fixed in Core, I'll try to figure out a way to avoid this bug in the Related Posts feature.

**Comment by kbrown9** [comment]
Thanks for the bug report @micropat!

I just want to add an additional detail about this bug. If there are multiple filters with priorities greater than 40, only the first filter with a priority greater than 40 is skipped. All of the other filters are applied.

For example, if you try this code, you’ll see that 'add_something_to_content_filter2’ is applied.
```
add_filter( 'the_content', 'add_something_to_content_filter', 41 );

function add_something_to_content_filter( $content ) {
	$original_content   = $content;
	$add_before_content = 'SOMETHING BEFORE CONTENT.';
	$add_after_content  = 'SOMETHING AFTER CONTENT.';
	
	$content = $add_before_content . $original_content . $add_after_content;

	return $content;
}

add_filter( 'the_content', 'add_something_to_content_filter2', 42 );

function add_something_to_content_filter2( $content ) {
	$original_content   = $content;
	$add_before_content = 'SOMETHING BEFORE CONTENT 2 .';
	$add_after_content  = 'SOMETHING AFTER CONTENT 2 .';
	
	$content = $add_before_content . $original_content . $add_after_content;

	return $content;
}
```
