### ISSUE TITLE
Stats page: fix misaligned text in "Show Me" button

### ISSUE THREAD

**Issue by joanrho** [Automattic/jetpack#13783]
There is some styling that is throwing off the proper text alignment in this button on the Stats page (/wp-admin/admin.php?page=stats):

<img width="1178" alt="Screen Shot 2019-10-18 at 1 45 35 PM" src="https://user-images.githubusercontent.com/204742/67125490-23e20b00-f1b2-11e9-9db1-2fc142c1a5de.png">

**Comment by julyyg** [comment]
hello!

**Comment by jeherve** [comment]
Closing this, since the Stats page was redesigned.
