### ISSUE TITLE
Widgets: Twitter Timline deletes height value upon saving

### ISSUE THREAD

**Issue by kriskorn** [Automattic/jetpack#13789]
#### Steps to reproduce the issue

1. Go to WP Admin -> Appearance -> Widgets / My Sites -> Design -> Customize -> Widgets
2. Add Twitter Timeline widget and fill in the information

#### What I expected

- To see all the settings saved.

#### What happened instead

- In WP Admin it clears the Height field value upon saving. 
- In Customizer, the autosave clears the value right away.

Issue affects both self-hosted and WordPress.com sites. 

User report: 2432042-zen

**Comment by jeherve** [comment]
Does this happen regardless of the height value you pick, and even if you don't specify a limit of number of tweets?

**Comment by kriskorn** [comment]
My bad. Should have said that as well. The value gets cleared as soon the "# of Tweets Shown" is entered. If the field is empty and the default value is used, then you can also have a height. However, when you select the number of Tweets, then the Height value can be whatever you input, but it will be cleared.

**Comment by jeherve** [comment]
> when you select the number of Tweets, then the Height value can be whatever you input, but it will be cleared.

Yes, that's the expected behaviour

> A timeline with a specified limit is expanded to the height of those Tweets.
> The specified height value no longer applies, so we reject the height value when a valid limit is set: a widget attempting to save both limit 5 and height 400 would be saved with just limit 5.

**Comment by kriskorn** [comment]
If that is the expected behaviour, then this needs an enhancement. Although a user may want to show 10 tweets on their site, they may not want it to be 2000px long, which basically makes a site look like broken. Or shall this be always taken care of extra CSS?

**Comment by jeherve** [comment]
> If that is the expected behaviour, then this needs an enhancement.

That makes sense. We could gray out the field/remove it, and/or add a notice explaining why that field is not available.
