### ISSUE TITLE
autoload_classmap_package.php contains version number 9999999-dev

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#13793]
Take a look at the `vendor/composer/autoload_classmap_package.php`

Notice that the version numbers are all `9999999-dev` and do not correspond to the latest version of each of the different package. 

This prevents other plugins from using the latest version of a particular package. Even if Jetpack isn't running the latest version. 

#### What I expected
Take a look at the `vendor/composer/autoload_classmap_package.php`
To contain the real version numbers of each package as a snapshot in time of the package used.

**Comment by jeherve** [comment]
Related: #12680, #13382, #13497 

I believe we should be able to solve some of those issues by always working with the latest version of each package.

**Comment by kraftbj** [comment]
This is coming from Composer: https://github.com/composer/composer/issues/8323

When we use dev, it normalizes it. https://github.com/composer/semver/blob/master/src/VersionParser.php#L113-L115

**Comment by htdat** [comment]
We have at least 2 reports in our internal tracker: 4425-gh-jpop-issues like the following. I think they're related to the issue here? 

> Notice: Jetpack_XMLRPC_Server was called incorrectly. Not all plugins have loaded yet but we requested the class Jetpack_XMLRPC_Server Please see Debugging in WordPress for more information. (This message was added in version 9999999-dev.) in /home/html/wp-includes/functions.php on line 4778

**Comment by jeherve** [comment]
This can now be closed, as it was handled via Changelogger and the autotagger tool added in #19192. Our packages' stable versions now always rely on stable packages.
