### ISSUE TITLE
Instant Search: query params get cleared when the search is exited.

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#13808]
#### Steps to reproduce the issue

1. Follow instructions in https://github.com/Automattic/jetpack/pull/13761 to get search running
2. Load the home page with a query param in the url (does not need to do anything)
3. Run a search
4. Clear the search

The query param gets removed.

**Comment by gibrown** [comment]
This doesn't seem to be fixed for me on http://gibrown.wpsandbox.me/demo/ (currently running master).

**Comment by jsnmoon** [comment]
@gibrown That's a different bug -- this bug relates to the initial query parameter being removed; the bug affecting the above link removes the pathname when appending a query string to the URL.

Working on a fix now. Could we track this in a separate issue, please?

**Comment by jsnmoon** [comment]
This is now being tracked in #13845.
