### ISSUE TITLE
Instant Search: Non-English taxonomy filter is encoded

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#13812]
#### Steps to reproduce the issue

1. Follow instructions in https://github.com/Automattic/jetpack/pull/13761 to get search running
2. Configure a taxonomy filter for language on wordpress.tv
3. Load up the filters and you will see:

<img width="376" alt="Screen Shot 2019-10-22 at 2 06 12 PM" src="https://user-images.githubusercontent.com/820871/67336935-6a51a580-f4e3-11e9-8a8e-1a9c04bd6b12.png">

**Comment by gibrown** [comment]
I was thinking in the client, but I really haven't looked at exactly what is coming from the API and ES.

**Comment by jsnmoon** [comment]
I think the correct approach would be to correct this in the API. 

In an ideal world, the above screenshot might look like the following:
- `english` should be `English`, or `English (English)`
- `spanishespanol` should be `Spanish (Español)`
- `germandeutsch` should be `German (Deutsch)`
- `frenchfrancais` should be `French (Français)`
- `japanese%e6%97%a5%e6%9c%ac%e8%aa%9e` should be `Japanese (日本語)`

<img width="254" alt="Screen Shot 2019-10-28 at 1 04 26 PM" src="https://user-images.githubusercontent.com/4044428/67709412-817d1100-f983-11e9-9d25-9d2a14393342.png">

**Comment by bluefuton** [comment]
Available fields: https://developer.wordpress.com/elasticsearch-post-doc-schema-v2/#es-mapping-post-tags

**Comment by jsnmoon** [comment]
Fixed in #14437.
