### ISSUE TITLE
Instant Search: Mobile and non-sidebar support

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#13816]
Currently Instant Search is not at all optimized to work well when on a mobile device or when the theme does not have a sidebar or a search button in a reasonable place. Some good example themes are: 2013, 2019, and Argent. The design fix here is to add a search box, sorting box, and filter dropdown or overlay above the search results area. Possibly this is done via Gutenberg Phase 2 menu blocks, or maybe it is just injected into the page. Likely the page should be auto-scrolled once the user starts trying to search and the search box should stay on screen (or hide/unhide on scroll).

Here are a few old mockups to give an idea, but there have been a number of ongoing design discussions since these about having the filters slide in from the side.

![SAYT CPU Filter Popup](https://user-images.githubusercontent.com/820871/67342997-151c9080-f4f1-11e9-81d9-31f47972c25a.png)

![SAYT Mobile3](https://user-images.githubusercontent.com/820871/67343026-2fef0500-f4f1-11e9-80de-f6a7286c00bc.png)

cc @joanrho

**Comment by bluefuton** [comment]
@joanrho's suggested improvements are here:

https://cloudup.com/cK8mBUIKy95/f

**Comment by gibrown** [comment]
I think this is pretty much done and out of date now

**Comment by incorvia** [comment]
If this is done, I do not see it on my site. Is there something I need to do to enable this new top filter bar within mobile contexts?

**Comment by gibrown** [comment]
Hi @incorvia this isn't yet released yet, and it is currently only available in the beta for our instant search. This implementation is in the release that will go out tomorrow though (Mar 3rd) and you can enable it with the instructions here: https://jetpack.com/support/beta-instant-search-and-filtering-prototype/

There is still a bit of work going on here before we'll be ready to make this the default search experience: https://github.com/Automattic/jetpack/milestone/139

Let us know what you think.

**Comment by incorvia** [comment]
@gibrown Thank you so much. Appreciate it!
