### ISSUE TITLE
Random Redirect: improve performance

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1381]
Random Redirect can be quite resource-intensive. It'd be nice to make some changes to the module, as it was done here:
https://wordpress.org/plugins/better-random-redirect/

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by bindlegirl** [comment]
Mentioned again in 3999767-zen

**Comment by pendantry** [comment]
I don't know if this is the right place to mention this.

?random, which I've been merrily using for some time, seems to have picked up some hiccups.

Sometimes ?random works fine, redirecting to any old post on a site (though it often seems to have a preference for newer posts).

But just lately, I've noticed that it's misbehaving quite oddly. On several sites I've used it on, it's been presenting me with the same page, over and over again. If I wait a while and try again, I'll get a different page offered, which again will be repeatedly offered over and over. Even more peculiar is that the same page is presented apparently irrespective of the browser – I've just encountered that while testing, on Firefox 95.0.2 (64-bit) and Chrome 96.0.4664.110 (Official Build) (64-bit).

I see that '[Random Redirect by Matt Mullenweg](https://wordpress.org/plugins/random-redirect/)', which I assume is the code in use by default on all WordPress sites, has a note:

> "This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress."

It would be good to get this fixed, it's a very useful facility.

**Comment by cyberscribe** [comment]
You might try this: https://wordpress.org/plugins/better-random-redirect/

**Comment by pendantry** [comment]
> You might try this: https://wordpress.org/plugins/better-random-redirect/

That's not an option for me personally (I'm on WordPress.com with a 'personal plan', so cannot install plugins without 'upgrading' to a 'business plan'... which would be a serious downgrade because I would have to change domains to do so).

I'm more concerned about the default behaviour of ?random, as it affects the entire WordPress community. If ?random is no longer being supported, it will no doubt become increasingly problematic to use it.

**Comment by cyberscribe** [comment]
The code base for this plugin is derived from the Jetpack version and
enhanced. So if the WP team wanted to upgrade the Jetpack version, this
would be one possible model for how to make it reliable and efficient.

**Comment by jeherve** [comment]
Closing this issue since the Random Redirect feature is no longer part of the Jetpack plugin.
