### ISSUE TITLE
Instant Search: use the site's locale rather than the browser for displaying dates

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#13810]
#### Steps to reproduce the issue

1. Follow instructions in https://github.com/Automattic/jetpack/pull/13761 to get search running
2. Run a search and see the date format. It matches your browser settings for localization

We should (maybe/probably) be using the sites settings for deciding how to display dates. Use `get_option( 'date_format' )` and `get_option( 'locale' )` and pass in the options?

**Comment by ivanovov** [comment]
Hello i see  not is hire for ask bat not see anoter place 
i have this code
 $out['desc']  = cot_title('user ' .$urr['user_name'] .' ' .user in.'.' ' .$urr['user_text'] ); i wont limit in 100 charaters output Thanks in advance.

**Comment by gibrown** [comment]
This is now getting passed to the js and just needs to get applied: https://github.com/Automattic/jetpack/blob/instant-search-master/modules/search/class-jetpack-instant-search.php#L115

**Comment by bluefuton** [comment]
Current status: the `locale` is being passed through to the `SearchResult` component but the custom date format is not.

**Comment by bluefuton** [comment]
The current implementation is:
* dates appear in the site’s locale
* dates do not use the site’s custom date format if specified
* we’re not translating dates to the visitor’s browser locale

Marking this as done 👍
