### ISSUE TITLE
SEO Tools: add fields for custom title and description to post editor

### ISSUE THREAD

**Issue by chickee0311** [Automattic/jetpack#13827]
**What's the feature I'm requesting?**
Ability to override SEO title/description tags (independently of the actual post title/description).

**What I'm seeing**
I think we have some room for improvement in being able to modify the SEO title tag and meta description on a post level. Although you can set custom title formats by reordering Site Name/Date/Post Title/ect., there is some missed opportunity to modify those title tags beyond the post title (see: https://jetpack.com/support/seo-tools/).

Say for example that you have your title tag set to pull in the post title and site name and you want to target a particular keyword in your title tag, you would have to make your post title that keyword. This doesn't lend itself well to being able to search internally for posts, especially considering those who have a lot of content. The goal would be to be able to modify the title tag independently from the post title. 
Here's an example:
<img width="242" alt="Screen Shot 2019-10-23 at 4 53 56 PM" src="https://user-images.githubusercontent.com/48809176/67440217-d56bac80-f5b5-11e9-8896-05872db6a165.png">
<img width="742" alt="Screen Shot 2019-10-23 at 4 45 10 PM" src="https://user-images.githubusercontent.com/48809176/67440284-0a77ff00-f5b6-11e9-9330-8e9496e93a28.png">

So if I want to optimize my title tag for the search term `Best Type of Potato` with my website placed at the end of that tile tag, this is what it would look like:
<img width="503" alt="Screen Shot 2019-10-23 at 4 52 42 PM" src="https://user-images.githubusercontent.com/48809176/67440402-6e022c80-f5b6-11e9-92f9-77b5035ed215.png">
<img width="760" alt="Screen Shot 2019-10-23 at 4 53 23 PM" src="https://user-images.githubusercontent.com/48809176/67440524-c9ccb580-f5b6-11e9-8101-227180284c06.png">

As far as meta descriptions go, you can currently set a meta description for the front page, but it would be good to be able to set a unique meta description within each post in order to craft a unique call to action. 

**Why am I requesting this?**
As a specialist in SEO, I need to be able to modify title tags and meta descriptions for every page and post on our site. There are unique keyword opportunities that we try to target, and providing a unique and concise title and meta description for each post/page helps us target those keywords on every page to follow on-page SEO best practices. To that length, posts/pages with duplicate or missing title tags and descriptions make it difficult for search engine crawlers to understand the page content, thus leading to a lower chance of ranking well.

**What's the ideal fix here?**
- Make a separate SEO title tag field, which is a feature that I believe is currently missing
- Make a separate SEO meta description field, which works at WordPress.com already, but ideally would make it work in the new block editor, also adding it to Jetpack self-hosted installs.

**Comment by jeherve** [comment]
> Make a separate SEO meta description field, which works at WordPress.com already, but ideally would make it work in the new block editor, also adding it to Jetpack self-hosted installs.

This is currently not possible, but that's something we're discussing internally, so it may happen in the future.

> Make a separate SEO title tag field, which is a feature that I believe is currently missing

You're correct, that feature does not exist at all in Jetpack right now. That's something we'd have to add.

**Comment by tmmbecker** [comment]
2461321-zen requesting access to SEO meta for the post in the new block editor.

**Comment by mbhthompson** [comment]
another user is requesting access to the SEO meta description in the post editor: 3127463-zen

**Comment by mzakariya** [comment]
Another user would like to use this feature in 3143553-zen.

**Comment by tmmbecker** [comment]
3282660-zen

**Comment by coder-karen** [comment]
Also 3352495-zen
