### ISSUE TITLE
Contact Form: Required fields have blank data in received form responses

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#13828]
I'm looking into an issue where contact form responses have been received with blank field data, where those fields have been marked as required.

The first form field has a default option which is being sent along, and Akismet isn't marking these submissions as spam.

From the front-end, the form appears to validate for blank fields, but there are several recorded responses in Feedback that have blank data for the required fields.

For specifics please see:
pZbK5-5EF-p2
#user-report

**Comment by jeherve** [comment]
It looks like the form was added directly into the theme with `do_shortcode`. This workaround isn't working properly right now, as per #102.

Closing as duplicate.
