### ISSUE TITLE
Your installation of Jetpack is incomplete. If you installed Jetpack from GitHub, please refer to this document to set up your development environment.

### ISSUE THREAD

**Issue by techonlinebd** [Automattic/jetpack#13834]

**Comment by jeherve** [comment]
Hi there!

Could you tell us more about your issue, and what you've tried to solve the issue? The error you mentioned links to this document. This should help you get Jetpack to work when you install it from GiHub:
https://github.com/Automattic/jetpack/blob/master/docs/development-environment.md#start-development

**Comment by hitzgh** [comment]
i am also facing same issue after migrating my wordpress site

**Comment by htdat** [comment]
@hitzgh if you install Jetpack from GitHub, please follow up https://github.com/Automattic/jetpack/blob/master/docs/development-environment.md#start-development

Otherwise, please download Jetpack from https://wordpress.org/plugins/jetpack
