### ISSUE TITLE
Plugin menu icon in Calypsoify has wrong shade of gray

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#13857]
#### Steps to reproduce the issue

1. Go to /wp-admin/plugins.php?calypsoify=1
2. Observe inconsistent colors of menu icons (plugins icon appears lighter)

#### What I expected
Consistent colors

#### What happened instead
Nup

**Screenshots**

<img width="532" alt="plugins-icon-gray" src="https://user-images.githubusercontent.com/51896/67702145-6f44a800-f96e-11e9-84d6-f83c04abf027.png">

**Comment by jeherve** [comment]
cc @sixhours. I believe this may have been introduced by your changes in #13659.

**Comment by gravityrail** [comment]
@jeherve @sixhours this related change caused a build error that I'm seeing now

https://github.com/Automattic/jetpack/pull/13628

**Comment by gravityrail** [comment]
I opened a separate ticket for that: #13859

**Comment by Aurorum** [comment]
I think it's because #13659 was merged before #13628, and I didn't realise so that was merged without updating things. I'll propose a PR to fix them in a second.

**Comment by Aurorum** [comment]
#13861 should take care of both things, I don't think it was a change in #13659; the plugins icon seems to be a brightness filter as it's an image.
