### ISSUE TITLE
Likes / PHPCS: replace file_get_contents by wp_remote_get

### ISSUE THREAD

**Issue by joendotcom** [Automattic/jetpack#13851]
Although this is only used on WordPress.com, we could replace the use of `file_get_contents` in the Likes module (`modules/likes/jetpack-likes-settings.php`) by Core's `wp_remote_get`.

One could go a step further and fix all PHPCS errors and warnings on the file, so we can add it to the whitelist here:
https://github.com/Automattic/jetpack/blob/93a5f3e57b235ba0feaab08220e99e6dd9cf0533/bin/phpcs-whitelist.js

**Comment by kraftbj** [comment]
Resolved in, at least, #24368.
