### ISSUE TITLE
No close button and other style inconsistencies in Jetpack backup notice

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#13866]
#### Steps to reproduce the issue

1. Activate Jetpack premium on a site with VaultPress (e.g. Pressable)
2. You will see this notice:

<img width="727" alt="jetpack-handling-backups-note" src="https://user-images.githubusercontent.com/51896/67712598-8b057980-f981-11e9-980b-8f1d2ac8300c.png">

3. It doesn't have a close button (though it does disappear on reload)
4. It also has a large font for the title, inconsistent with other notices.

#### What I expected

A less obtrusive, closeable notice

#### What happened instead

No close icon, obtrusive font style

**Screenshots**

<img width="783" alt="jetpack-handling-backups" src="https://user-images.githubusercontent.com/51896/67712670-aa040b80-f981-11e9-8839-04a6bea6bba7.png">

**Comment by joanrho** [comment]
@gravityrail Can you replace that notice with something that resembles the Akismet one? But with a green border-left and the following message that lets users know where to access their backups:

>**Jetpack is now handling your backups.**
>Vaultpress is no longer needed and has been deactivated. You can access your backups on your site's [Activity](#) page.

^ where "Activity" links to the Activity page in Calypso.



<img width="1144" alt="Screen Shot 2019-10-28 at 2 50 30 PM" src="https://user-images.githubusercontent.com/204742/67716981-7382bc80-f992-11e9-8e0b-17eb325a80f8.png">

**Comment by gravityrail** [comment]
@joanrho I have updated the PR to include your suggested changes
