### ISSUE TITLE
Jetpack Plans grid: update several Jetpack feature names

### ISSUE THREAD

**Issue by joanrho** [Automattic/jetpack#13868]
Update items in plans grid located at wp-admin Jetpack Dashboard > Plan:

1. “Daily Backups” replaced with “Jetpack Backup (Daily)”
2. “Spam Protection” replaced with “Jetpack Anti-spam”
3. “Daily Malware Scanning” replaced with “Jetpack Scan”
4. “Real-time Backups” replaced with “Jetpack Backup (Real-time)”

ref: p1HpG7-7Ro (feature naming alignment)

<img width="1291" alt="Screen Shot 2019-10-28 at 1 50 47 PM" src="https://user-images.githubusercontent.com/204742/67712633-fd7a5780-f989-11e9-9615-84f664d1184b.png">

**Comment by jeherve** [comment]
Closing this for now since the "My Plans" page now redirects to WordPress.com.
