### ISSUE TITLE
Submit fails when Jetpack Gutenberg Form contains Title-block

### ISSUE THREAD

**Issue by eirikbacker** [Automattic/jetpack#13887]
#### Steps to reproduce the issue

1. Go to any page/post
2. Add a Jetpack Gutenberg form
3. Test form in front-end: *Shows confirmation screen after submit*
4. Go back to edit, and add a Title-block in the form block
5. Test form in front-end: *Does not show confirmation - only shows form again*

#### What I expected
Confirmation screen, regardless of wether form contains title/heading or not.

#### What happened instead
Does not show confirmation - only shows form again

**Screenshots**
*1: Form:*
![image](https://user-images.githubusercontent.com/691801/67833116-0b43f000-fae4-11e9-9546-ba2244e17c53.png)

*2: Expected result:*
![image](https://user-images.githubusercontent.com/691801/67833291-8c9b8280-fae4-11e9-8a8e-615a526e74e6.png)

*3: Actual result:*
![image](https://user-images.githubusercontent.com/691801/67833129-14cd5800-fae4-11e9-9cb7-817c637129e2.png)

**Comment by jeherve** [comment]
Could you try to install [Jetpack's Beta plugin](http://jetpack.com/download-jetpack-beta/), activate it on your site next to the Jetpack plugin, and then go to Jetpack > Beta and switch to the Release Candidate option?

We've made quite a few changes to the Form block in the past month and will release those changes in the next version of Jetpack next week. I would be interested in knowing if this may have fixed the bug you're seeing. 

Thank you!

**Comment by eirikbacker** [comment]
Hi and thanks for super fast response @jeherve! I have now tested (with both `Latest stable` and `Bleeding edge`) and can confirm the bug is still present unfortunately.
Though - the form is actually submitted, just, the user does not know 😅 

Also just a PS: if typing comma in the multiple checkbox field, this becomes several checkboxes when rendered in the front end:

*Admin* | *Front ent*
:-- | :--
![image](https://user-images.githubusercontent.com/691801/67921929-93d89400-fba9-11e9-800e-688445ebd5df.png) |  ![image](https://user-images.githubusercontent.com/691801/67921952-9f2bbf80-fba9-11e9-8248-ff9dc115c916.png)

But, the confirmation message is more important :)
Thanks for looking into it!
