### ISSUE TITLE
Disconnect dialog: text indenting does not match previous paragraph

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#13889]
![image](https://user-images.githubusercontent.com/426388/67852771-545c6a00-fb0d-11e9-8fe8-8e974b463835.png)

> Should there be something before the “Have a question?” text? The indent before that text seems rather large and empty.

cc @cbauerman

**Comment by cbauerman** [comment]
cc @scottsweb

**Comment by cbauerman** [comment]
I will whip up a quick fix.
