### ISSUE TITLE
Sharing: Move Recaptcha to after "send email" is clicked

### ISSUE THREAD

**Issue by rebeccahum** [Automattic/jetpack#13909]
#### Describe the solution you'd like
For performance reasons, it would be nice to have the reCAPTCHA verification display after the "Send Email" button is clicked, rather than during the "Send to Email Address" initial load dialog.  

#### Additional context
![image](https://user-images.githubusercontent.com/16962021/67877968-2c1a3e80-fb00-11e9-8a1b-3b9099d933ac.png)

Currently on the share email, this is what loads initially ^^.

**Comment by jeherve** [comment]
This can now be closed since we now use mailto instead of a custom email sharing button (see #24040).
