### ISSUE TITLE
Contact Form: improve URL field validation for URL fields on the frontend

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#13914]
We currently rely on the `url` input type to validate URLs when one submits a URL in a form field:

![image](https://user-images.githubusercontent.com/426388/67965966-4c7ef180-fc03-11e9-8e6d-cd8235b7e7a4.png)

This was added in #7801.

This works ok, but isn't perfect as a lot of folks may want to add incomplete URLs, without the protocol. It's especially true on mobile, and as browsers start making the protocol less important (not displaying them in the address bar).

We could move away from the html5 `url` input type and instead rely on a custom solution to validate URLs in those fields.

As suggested here:
p8oabR-qb-p2

**Comment by chaitanyamsv** [comment]
A customer asked for it in #21319236-hc

**Comment by chaitanyamsv** [comment]
A customer was confused by this in 25381111-hc

**Comment by CGastrell** [comment]
Would the changes introduced on #27138 be enough to close this one? The changes include two main features:

- improved validation message: `Please enter a valid URL - https://www.example.com`
- the input will now accept URLs without protocol, validated both on frontend and backend

**Comment by jeherve** [comment]
Yes, I think that improvement is a good first step, thanks! Closing this issue now.
