### ISSUE TITLE
Like button libraries loaded even when not necessary

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#13929]
#### Steps to reproduce the issue

1. Enable Likes or Comment Likes
2. Go to the blog page
3. Look at what JS is loaded - you'll see postmessage.js, likes/queuehandler.js, etc.

#### What I expected
Bulky Likes code shouldn't load if Like widget isn't going to be rendered

#### What happened instead
Likes JS was loaded

**Screenshots**

**Comment by josephscott** [comment]
While running tests with Jetpack modules, I found the `Comment Likes` triggered a few different issues:

1. It loads on views that do now show comments
2. It requires jQuery

The first item means that even on the front page of a site, with just post content, we are paying the price of the `Comments Like` feature, even though it can't be used there.

The second item relates to the weight of the feature on slowing down pages.  I recently ran a test to compare just turning on the `Comment Likes` feature under slow mobile conditions and it increased the start render time by 42.8%.  It increased the amount of JS on the page by 364%, of which jQuery alone is 94 KB.  Then jQuery migrate comes along too, at another 9.8 KB.

**Comment by kienstra** [comment]
Good idea to open this!

https://github.com/Automattic/jetpack/pull/14841 addresses this for the Likes module, but not `comment-likes.php`. I'll look at fixing this for the `comment-likes.php` module.

**Comment by kienstra** [comment]
Ah, sorry. #14841 doesn't address:

>Bulky Likes code shouldn't load if Like widget isn't going to be rendered

It only prevents dependencies from blocking page rendering, by moving them to the footer.

**Comment by josephscott** [comment]
Adding:

```
		if ( ! $this->settings->is_likes_visible() ) {
			return;
		}
```

to `load_styles_register_scripts()` from #14841 is enough to fix the problem of the comment like resources being loaded on views where there are no comment likes being displayed.

Doing just that is a huge improvement - https://www.webpagetest.org/video/compare.php?tests=200305_Z1_fc597a58623d41d112dfd85fd9de4947%2C200305_DZ_143c64721f87507448fe594d2350211a%2C200305_CD_5d82ad15281436fb87245bd379ad319d&thumbSize=200&ival=100&end=visual
