### ISSUE TITLE
Instant Search: hook up postTypeFilters to be applied

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#13927]
The search widget lets you apply a post type filter to all search results. Although we are passing that param to the search app, currently it is not getting applied anywhere to the search results.

https://github.com/Automattic/jetpack/search?utf8=%E2%9C%93&q=postTypeFilters&type=

The existing functionality is for this to completely filter the search results and so we should do that.

We should also add a way for an ES formatted filter to be applied to all search results through the options hook.

**Comment by bluefuton** [comment]
So to clarify - this is a restriction on the post types returned by searches that is globally applied, and set up by the user?

**Comment by gibrown** [comment]
@bluefuton ya, so this could be set in a WP filter to let the end user define a filter that would always get applied from that page load. Right now we pass in the options from the widget config, but I guess we should actually build an ES filter on the php side and then just apply that to the query.

Marking this as low priority because I think we can ship without it but I fully expect it to come up.

**Comment by jsnmoon** [comment]
A typical user currently defines at least two Jetpack Search widgets: one outside the overlay and one inside the overlay. Because of this, each widget can be configured with a different post type filter. 

I recommend figuring out a design solution to this before pushing forward with implementation.

**Comment by keoshi** [comment]
> A typical user currently defines at least two Jetpack Search widgets: one outside the overlay and one inside the overlay.

I keep coming back to defining a single widget — the one we know exists for sure inside the overlay — and add an option on each filter to expose them outside.

The most simplistic example I can think of is the following:

![image](https://user-images.githubusercontent.com/390760/73460511-82518480-4370-11ea-9205-d689eb0ebc89.png)

Granted, this is not ideal. We'd also have to offer an option to select which widget area is then populated, not to mention the complex implementation this could be.

Is there a way we can restricts the options that are available on the second Jetpack Search widget — the one outside the overlay — so at least they're always in sync?

**Comment by gibrown** [comment]
> Is there a way we can restricts the options that are available on the second Jetpack Search widget — the one outside the overlay — so at least they're always in sync?

So I kinda did something like this in #14448 where what we render for the overlay widget is different than what we do for the front end widget. I may be able to make that work for the customizer and limit what options we show. I still think we will want to let the user customize some sort of a default filter though this kinda gets into the area of having multiple "search engines" on the site that have different filters.

I am very uncertain about duplicating the results between two widgets (they are stored in the DB separately), and it is not clear to me what we would do if the user configures multiple JP Search widgets in a single sidebar.

This feels like it is getting into a bigger customization issue. I wonder if we should initially just hide some of these options when instant search is enabled.

**Comment by gibrown** [comment]
Requested for css-tricks to remove the results from the forums:

> One thing I’d really like to do is remove results from the forums

**Comment by chriscoyier** [comment]
My use case is that we've shut down our forums. I'm not deleting them from the site, but they are closed to new activity. I'd prefer not to send people there at all from on-site search results. 

![forums](https://user-images.githubusercontent.com/69156/79004811-5853d580-7b0a-11ea-86b9-e5c0662e5a68.png)

**Comment by jsnmoon** [comment]
This has been fixed by #15548. We intend to rework the sort and post type configuration into the Jetpack Search section of the customizer in the future.
