### ISSUE TITLE
Mailchimp / AMP: form cannot be submitted if site does not have SSL

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#13955]
#### Steps to reproduce the issue 

1. Start from a Jetpack site connected to WordPress.com, with the AMP plugin active, on a site using HTTP.
2. Go to Posts > Add New, and add a new Mailchimp block to your post. 
3. Configure the block and publish your post. 
4. You should be able to submit an email address to the form with no issues.
5. Now visit that same post in an AMP view, and try to add a new email address.
6. You will receive the following error upon submission:

```
Access to fetch at 'https://public-api.wordpress.com/rest/v1.1/sites/xxx/email_follow/amp/subscribe/?__amp_source_origin=xxx' from origin 'xxx' has been blocked by CORS policy.
The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'
```

- AMP support for the block was added in #12695 
- I am not sure what the best solution is here. Since AMP itself makes it clear in its settings that a site that does not use HTTPS will not support all AMP features, maybe we shouldn't try to display the form on such sites?

cc @jeffersonrabb 

Originally reported here:
p8oabR-qb-p2#comment-3537

**Comment by jeffersonrabb** [comment]
I'll verify, but as I understand it SSL is a hard requirement for AMP forms. @jeherve do you think we should suppress the form entirely on insecure sites? Or  show a message explaining why it isn't available?

**Comment by jeherve** [comment]
I'm not sure what the best User Experience would be here. Paging @Automattic/jetpack-design for some opinions.

**Comment by keoshi** [comment]
I've given this a test and it appears I'm able to subscribe to create a subscription in the AMP view of the post without a problem on a site that has no SSL certificate.

**Comment by jeherve** [comment]
I can't reproduce the bug anymore either  ¯\_(ツ)_/¯

Closing.
