### ISSUE TITLE
Sharing buttons do not work correctly on HTTPS pages (retrieving post count)

### ISSUE THREAD

**Issue by patschi** [Automattic/jetpack#1396]
Hello,

I noticed today that the sharing buttons do not work correctly on HTTPS pages. The buttons are shown correctly and they even work, but the JavaScript functionality which should retrieve the count how many the single article got posted, does not.

It seems that this is because the required Twitter, Facebook and co libraries are loaded over HTTP, which gets blocked by the browser (I'm using Google Chrome). See the following error messages:

```
Mixed Content: The page at 'https://domain.tld/awesome-article' was loaded over HTTPS, but requested an insecure resource 'http://platform.twitter.com/widgets.js'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at 'https://domain.tld/awesome-article' was loaded over HTTPS, but requested an insecure script 'http://platform.twitter.com/widgets.js'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at 'https://domain.tld/awesome-article' was loaded over HTTPS, but requested an insecure resource 'http://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fdomain.tld%2Fquic…_faces=false&width=1000&action=like&font=arial&colorscheme=light&height=21'. This request has been blocked; the content must be served over HTTPS.
```

And I really would appreciate a possibility to deactivate exactly this functionality (the retrieving of the post count from the social networks) and to just show the buttons. I know that it's possible to hack a bit in the JavaScript code to deactivate this behaviour manually, but I don't want to make this over and over again, when a new Jetpack update gets published and I update it (which does overwrite my modifications ofcourse). Is there any other hack like a Wordpress hook to easily realize that?

Thanks for any help!

**Comment by Vinodang** [comment]
@jeherve thank u very much!  when i set the url : 
<a href="http://127.0.0.1:8080/download/1.txt"> from a https request, it report  error : 
Mixed Content: The page at 'https://127.0.0.1/index.html' was loaded over HTTPS, but requested an insecure resource 'http://127.0.0.1:8080/download/1.txt'. 
This request has been blocked; the content must be served over HTTPS.
Failed to load resource: net::ERR_CACHE_MISS

when i added the target="_blank" to the url: <a target="_blank" href="http://127.0.0.1:8080/download/1.txt">, it works! 
it's well known that target="_blank" means opening the linked document in a new window or tab or a new request!
What do u think?

**Comment by jeherve** [comment]
@Vinodang Your problem doesn't appear to be linked to the Jetpack plugin. I'd suggest posting in the support forums of the tool you used to create that page.
