### ISSUE TITLE
Instant Search: add locale-specific currency formatting to product results

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#13983]
Product results, introduced in #13826, show the product price where available. @jsnmoon raised in code review that we should take the formatting rules of the currency into account when showing it. 

We could potentially use `getCurrencyDefaults` from `@automattic/format-currency` (this is what the Simple Payments button uses in Calypso).

Todo:
- [ ] add currency to the API response
- [ ] add localized currency formatting

**Comment by gibrown** [comment]
I've added two fields for this:
- 'wc.currency' - the CLDR currency code
- 'wp.currency_pos' - where to place/formate the currency symbol

There are a number of other options we maybe will need. Bunch of details here: https://github.com/woocommerce/woocommerce/blob/bccb93fa3cfde83fb8200b5d54d67815ba830965/includes/admin/settings/class-wc-settings-general.php#L228

**Comment by gibrown** [comment]
Ugh... I think I did the right thing on the indexing side, but on at least one site the options don't seem to be getting synced, so I think this will need some work on syncing the correct data. Fun...

**Comment by bluefuton** [comment]
We now get a formatted currency from the API, which includes the currency symbol in the right position.
