### ISSUE TITLE
Photon/Image CDN Feature’s devicepx JavaScript Has Conflict With a3 Lazy Load

### ISSUE THREAD

**Issue by KZeni** [Automattic/jetpack#14024]
It appears enabling Jetpack’s Photon / WP.com Image CDN functionality also triggers devicepx JS (http://s0.wp.com/wp-content/js/devicepx-jetpack.js) to be included on the site’s pages. This then creates a problem for a3 Lazy Load (https://wordpress.org/plugins/a3-lazy-load/ & 200,000+ active installations) per this script resulting in the srcset value for images to be populated with the placeholder/loading image used by a3 Lazy Load instead of the actual image asset(s).

The problem is then surfaced when using a high-dpi/retina screen or anything else that otherwise has the browser looking at the srcset value instead of the src for the img element (src being accounted for properly to use the actual asset, but srcset is used by the browser instead based on the srcset value[s]).

### – Summary of Issue –
In short, enabling the image CDN from Jetpack has devicepx JS included which incorrectly grabs the placeholder/loading image for the srcset value on the images and then a3 Lazy Load then doesn’t account for that fact so the placeholder/loading image is simply never switched away from since that asset is still what’s present as the srcset value which the browser sees as what’s supposed to be used.

### – Workaround –
My current workaround was to add this to the site’s functions.php file (I happened to place it alongside where the other scripts for the theme are being enqueued, but I imagine it could be implemented elsewhere):
```
// Disable Jetpack's devicepx (has a conflict with a3 Lazy Load [retains the placeholder as the higher-dpi image asset)
wp_dequeue_script( 'devicepx' );
```
### – Possible Solution –
I’m wondering if the implementation of devicepx could/should be updated to behave more favorably for lazy loading behaviors (ex. check for additional sources of the image asset in the image element’s HTML parameters prior to the lazy load swap / asset is triggered to be loaded to avoid grabbing a placeholder image and using that for the resulting srcset value).

Btw, I know Jetpack has its own lazy loading feature now, but I’d like to keep using a3 Lazy Load since this also accommodates iframes, video, etc. which Jetpack’s implementation is currently lacking (among other customizations, functionality, etc.)

As an aside, this has also been posted at https://wordpress.org/support/topic/photon-image-cdn-features-devicepx-javascript-has-conflict-with-a3-lazy-load/ for cross-reference/visibility. I've also posted on a3 Lazy Load’s support forum at https://wordpress.org/support/topic/conflict-with-jetpacks-photon-wp-com-image-cdn-features-devicepx-javascript/, but I’m also posting here since there might be something to be done on the Jetpack/devicepx side of things to avoid this conflict (I imagine whomever fixes the conflict first is the best result for all while having both resolve the conflict would be harmless & potentially resolve other possible conflicts.).

**Comment by jeherve** [comment]
Thanks for the detailed report.

Do you happen to know if a3 Lazy Load uses a specific attribute to store its placeholder image? Jetpack's Lazy Images feature uses `data-lazy-src` for example.

Knowing this, we may be able to make changes to be more compatible with a3 Lazy Load.

Thank you!

**Comment by KZeni** [comment]
a3 Lazy Load uses https://github.com/ressio/lazy-load-xt for its implementation.

It actually has the placeholder image set using the `src` value (preventing the actual asset from loading until it's lazy loaded) while the actual image is then set using a `data-src` value. This results in the following example as the base HTML that's output (prior to any JS being executed) when Photon is enabled via Jetpack with a3 Lazy Load set to lazy load images with a noscript fallback enabled:
```
<img class="lazy lazy-hidden" src="//www.domain.com/wp-content/plugins/a3-lazy-load/assets/images/lazy_placeholder.gif" data-lazy-type="image" data-src="https://i2.wp.com/www.domain.com/wp-content/uploads/2019/10/logo@4x.png?ssl=1" alt="Logo" width="360" height="94" /><noscript><img src="https://i2.wp.com/www.domain.com/wp-content/uploads/2019/10/logo@4x.png?ssl=1" alt="Logo" width="360" height="94" /></noscript>
```
That has me thinking... could devicepx check to see if `data-src` exists first (catch the actual asset for a lazy loading setup such as this one) and then use `src` as the fallback? I don't really see data-src being used as something other than the actual asset's src (which then wasn't immediately used as the src for a case like this.)

**Comment by jeherve** [comment]
Ok, thanks for the extra details!

I ran some tests, and interestingly this doesn't seem to create any issues on my end. I cant reproduce this:

> the srcset value for images to be populated with the placeholder/loading image used by a3 Lazy Load instead of the actual image asset(s).

On my end, the `srcset` value is always correct.

Here is my markup in my editor:

```html
<!-- wp:image {"id":22,"align":"wide"} -->
<figure class="wp-block-image alignwide"><img src="https://mysite.com/wp-content/uploads/2019/11/our-cappuccino-and-scone.jpg" alt="" class="wp-image-22"/></figure>
<!-- /wp:image -->
```

Here is the HTML content generated by WordPress:

```html
<figure class="wp-block-image alignwide">
	<img
		src="https://i0.wp.com/mysite.com/wp-content/plugins/a3-lazy-load/assets/images/lazy_placeholder.gif?w=640"
		data-lazy-type="image"
		data-src="https://mysite.com/wp-content/uploads/2019/11/our-cappuccino-and-scone.jpg"
		alt=""
		class="lazy lazy-hidden wp-image-22"
		srcset=""
		data-srcset="https://i0.wp.com/mysite.com/wp-content/uploads/2019/11/our-cappuccino-and-scone.jpg?w=450&amp;ssl=1 450w, https://i0.wp.com/mysite.com/wp-content/uploads/2019/11/our-cappuccino-and-scone.jpg?resize=150%2C150&amp;ssl=1 150w, https://i0.wp.com/mysite.com/wp-content/uploads/2019/11/our-cappuccino-and-scone.jpg?resize=300%2C300&amp;ssl=1 300w"
		sizes="(max-width: 450px) 100vw, 450px"
		data-recalc-dims="1"
	/><noscript
		><img
			src="https://i0.wp.com/mysite.com/wp-content/uploads/2019/11/our-cappuccino-and-scone.jpg?w=640&#038;ssl=1"
			alt=""
			class="wp-image-22"
			srcset="
				https://i0.wp.com/mysite.com/wp-content/uploads/2019/11/our-cappuccino-and-scone.jpg?w=450&amp;ssl=1            450w,
				https://i0.wp.com/mysite.com/wp-content/uploads/2019/11/our-cappuccino-and-scone.jpg?resize=150%2C150&amp;ssl=1 150w,
				https://i0.wp.com/mysite.com/wp-content/uploads/2019/11/our-cappuccino-and-scone.jpg?resize=300%2C300&amp;ssl=1 300w
			"
			sizes="(max-width: 450px) 100vw, 450px"
			data-recalc-dims="1"
	/></noscript>
</figure>
```

And the end result on the site:

```html
<figure class="wp-block-image alignwide">
	<img
		src="https://mysite.com/wp-content/uploads/2019/11/our-cappuccino-and-scone.jpg"
		data-lazy-type="image"
		data-src="https://mysite.com/wp-content/uploads/2019/11/our-cappuccino-and-scone.jpg"
		alt=""
		class="wp-image-22 lazy-loaded"
		srcset="
			https://i0.wp.com/mysite.com/wp-content/uploads/2019/11/our-cappuccino-and-scone.jpg?w=450&amp;ssl=1            450w,
			https://i0.wp.com/mysite.com/wp-content/uploads/2019/11/our-cappuccino-and-scone.jpg?resize=150%2C150&amp;ssl=1 150w,
			https://i0.wp.com/mysite.com/wp-content/uploads/2019/11/our-cappuccino-and-scone.jpg?resize=300%2C300&amp;ssl=1 300w
		"
		data-srcset=""
		sizes="(max-width: 450px) 100vw, 450px"
		width="1020"
		height="1020"
	/><noscript
		><img
			src="https://i0.wp.com/mysite.com/wp-content/uploads/2019/11/our-cappuccino-and-scone.jpg?w=640&#038;ssl=1"
			alt=""
			class="wp-image-22"
			srcset="
				https://i0.wp.com/mysite.com/wp-content/uploads/2019/11/our-cappuccino-and-scone.jpg?w=450&amp;ssl=1            450w,
				https://i0.wp.com/mysite.com/wp-content/uploads/2019/11/our-cappuccino-and-scone.jpg?resize=150%2C150&amp;ssl=1 150w,
				https://i0.wp.com/mysite.com/wp-content/uploads/2019/11/our-cappuccino-and-scone.jpg?resize=300%2C300&amp;ssl=1 300w
			"
			sizes="(max-width: 450px) 100vw, 450px"
			data-recalc-dims="1"
	/></noscript>
</figure>

```

This was for a single image, but the same seems to hold true for Featured Images and Gallery images in my tests.

It's interesting that your markup doesn't have any `srcset` or `data-srcset` attributes.

Do you experience this issue with any image on your site, regardless of where it is hosted / if it was uploaded to the media library / how it is inserted in the post?
