### ISSUE TITLE
Jetpack Backup: add tracking to links

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#14049]
Add tracking and track source URL to outgoing links in the different Backup product components.

See https://github.com/Automattic/jetpack/pull/14027#discussion_r346437645 and https://github.com/Automattic/jetpack/pull/14027#discussion_r346436123

> Do we need to add tracking to that link, maybe via `getUpgradeUrl`?

> Should we add tracking to all those buttons? We have analytics.tracks.recordJetpackClick that can help you there, as I think ideally we'd want to be able to follow where people are going form there.

**Comment by robertf4** [comment]
@jeherve, the outgoing links are built using `getUpgradeUrl` now. Does that suffice for tracking, or do we need to add further tracking via `recordJetpackClick`? Only think I could think of for that would be tracking the toggle between realtime and daily.

**Comment by jeherve** [comment]
I would recommend having both. We tend to usually track both sides. `getUpgradeUrl` builds the query strings that will allow redirecting to the right place (and potentially track affiliates) from Jetpack.com; `recordJetpackClick` registers a Tracks event that we can use in funnels (and thus see if we lose folks between wp-admin and Calypso).

> Only thing I could think of for that would be tracking the toggle between realtime and daily. 

I could personally see tracking on the "Which one do I need?" link, and the main Upgrade button (where we could pass info about what option was picked as a prop).

**Comment by jeherve** [comment]
Fixed in #14103
