### ISSUE TITLE
Map Block: Map Theme buttons lack styling

### ISSUE THREAD

**Issue by pento** [Automattic/jetpack#14058]
Note: This is not reproducible in WordPress 5.3, it requires the latest Gutenberg plugin.

#### Steps to reproduce the issue

1. Activate the Gutenberg plugin.
2. Create a new post in the block editor.
3. Add a Map block.
4. Observe that the "Map Theme" buttons in the sidebar lack the correct styling.

#### What I expected

The Map Theme buttons should preview each theme.

#### What happened instead

Plain text buttons are shown, instead.

#### Screenshots

WordPress 5.3:

<img width="279" alt="" src="https://user-images.githubusercontent.com/352291/69016800-12309500-09f6-11ea-9c22-0e71ed51e710.png">

Gutenberg 6.9.0:

<img width="279" alt="" src="https://user-images.githubusercontent.com/352291/69016806-2b394600-09f6-11ea-9c3e-8b8f9735ca71.png">

**Comment by scottsweb** [comment]
![Screenshot 2019-11-18 at 12 56 37](https://user-images.githubusercontent.com/411945/69054145-e49e1880-0a02-11ea-9aeb-f1d18cab0a8d.png)

Just tested this on the `master` branch with a fresh mapbox account and it seems to working well. Can you see if the images are being blocked at all by something in your browser or network (only thing I think it could be).

**Comment by pento** [comment]
@scottsweb: Gutenberg `master`, or Jetpack `master`? It's definitely broken with Gutenberg `master`, regardless of the Jetpack version.

The bug is caused by `WordPress/gutenberg#17880`, which changed the class name which should be used in [extensions/blocks/map/map-theme-picker/style.scss](https://github.com/Automattic/jetpack/blob/master/extensions/blocks/map/map-theme-picker/style.scss) from `edit-post-settings-sidebar__panel-block` to `block-editor-block-inspector`.

**Comment by scottsweb** [comment]
I tested Jetpack `master` not Gutenberg which explains the difference :)
