### ISSUE TITLE
The Twitter Timeline Widget requires Height and Width values to be configured

### ISSUE THREAD

**Issue by machx0r** [Automattic/jetpack#1405]
The Twitter Timeline Widget requires Height and Width values to be configured. By default the widget served from Twitter.com will use the height specified during initial configuration and set a width to fill the container. Unfortunately the Jetpack widget requires both these values to be configured. This is problematic for responsive themes where the designer/owner cannot predict the width while configuring the Wordpress widget.

**Comment by samhotchkiss** [comment]
Fixed by #1406
