### ISSUE TITLE
Plans: Hide "Explore our Jetpack Plans" section when Jetpack Backup card displays

### ISSUE THREAD

**Issue by robertf4** [Automattic/jetpack#14052]
#### Steps to reproduce the issue
From https://github.com/Automattic/jetpack/pull/14018#pullrequestreview-315656185

1. Go to :site/wp-admin/admin.php?page=jetpack#/plans-prompt
2. Observe that the "Explore our Jetpack Plans" section does not look good with the Jetpack Backup Solutions section.

**Comment by jeherve** [comment]
This was fixed.
