### ISSUE TITLE
Jetpack Backup: implement code style improvements

### ISSUE THREAD

**Issue by robertf4** [Automattic/jetpack#14065]
I'm creating this to keep track of the feedback on https://github.com/Automattic/jetpack/pull/14056 that needs to be addressed.

- [ ] Do not pass entire `backupPlanPrices` prop object to SingleProductBackupBody
- [ ] Make the appropriate propTypes required
- [ ] Do not define `backupOptions` or `upgradeTitles` on render
- [ ] Split `single-product-backup.jsx` into multiple files
- [ ] Rename `PlanPriceDisplay` to be more specific

**Comment by delawski** [comment]
@robertf4 @jeherve It seems that most if not all of the issues here have been resolved. Is it correct?

**Comment by tyxla** [comment]
Some haven't been resolved yet, I'll move this to the next release as these are not blockers at all.
