### ISSUE TITLE
Jetpack Backup: refactor price display in Backup card

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#14060]
The price display does not currently match the other prices displayed in wp-admin:

- [ ] The currency isn't the same as in Calypso or the other prices displayed in wp-admin https://github.com/Automattic/jetpack/pull/14018#pullrequestreview-317747937
- [x] "/year" doesn't match the "per year" used elsewhere https://github.com/Automattic/jetpack/pull/14018#pullrequestreview-315656185 (fixed in https://github.com/Automattic/jetpack/pull/14073)
- [x] The current `'%(currencySymbol)s%(dailyBackupYearlyPrice)s-%(realtimeBackupYearlyPrice)s /year'` price string is going to be hard to translate for our translators.

**Comment by robertf4** [comment]
>     * The current `'%(currencySymbol)s%(dailyBackupYearlyPrice)s-%(realtimeBackupYearlyPrice)s /year'` price string is going to be hard to translate for our translators.

@jeherve, do you have suggestions on a better way to do this? I did it this way to give the translators maximum freedom in translating this as they can use those parameters to order the currency symbol and the prices however they need to.

**Comment by jeherve** [comment]
I'll cc @akirk whose feedback will most likely be a lot better than mine. 

@akirk Could you give us your opinion / suggestions / dismissal of my concerns on this?
https://github.com/Automattic/jetpack/pull/14018/files#diff-7457a6cdabf24fa36923c20d4c9b101cR83
Thank you :)

**Comment by akirk** [comment]
Honestly this is pretty confusing in English for me already, it looks like I need to calculate 20 minus 50. Why not "from $20 to $50 per year"? The currency symbol is a can of worms, I'd suggest to not put this up for translation but just include it in the price value.

Currency formatting is dependent on language, country and currency. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat can we just use that?

**Comment by delawski** [comment]
Note that there's a new `PlanPrice` UI component introduced (actually it's a simplified version of `PlanPrice` from Calypso) in #14089 which we may want to use not only in the product card but also in the plans grid. It standardizes the way a price, discounted price or price range is rendered. [Check out the implementation](https://github.com/Automattic/jetpack/pull/14089/files#diff-b50ecaaf2ebec7706ca81c5439a99bddR1-R85).

**Comment by jeherve** [comment]
This should now be fixed.

**Comment by jeherve** [comment]
Reopening as item number 1 on the list is still an issue.

Also reported in p8oabR-qW-p2#comment-3617

**Comment by tyxla** [comment]
Grabbing as I'm fixing the remaining issue

**Comment by tyxla** [comment]
Addressed in https://github.com/Automattic/jetpack/pull/14149 and D36105-code
