### ISSUE TITLE
Instant Search: search boxes other than jp search widget no longer working

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#14062]
It used to be that you could add the core Search widget, or use the built in search box for the theme and instant search would work.

Doesn't work anymore. For a good theme, try 2013.

**Comment by bluefuton** [comment]
Happily, this is resolved with the overlay approach. Tested in 2013:

![2020-01-14 15-38-12 2020-01-14 15_38_45](https://user-images.githubusercontent.com/17325/72309500-04407d00-36e4-11ea-9a71-f44c7f35e5d3.gif)
