### ISSUE TITLE
Running wpcli

### ISSUE THREAD

**Issue by scruffian** [Automattic/jetpack#14064]
When I try to run a `wpcli` command (like `wp jetpack scaffold block`), from the `wordpress` director I get this error:

`Error: Required file 'psysh' doesn't exist (from project's wp-cli.yml).`

If I do it from `jetpack` I get this error:

```Error: This does not seem to be a WordPress installation.
Pass --path=`path/to/wordpress` or run `wp core download`.```

**Comment by jeherve** [comment]
Could you try to run it from your Docker instance?

`yarn docker:wp jetpack scaffold block`?

**Comment by scruffian** [comment]
That works! Thanks :)
