### ISSUE TITLE
Hour info field in Contact Info plugin is not showing

### ISSUE THREAD

**Issue by alviser** [Automattic/jetpack#14077]
#### Steps to reproduce the issue

1. add the widget to a sidebar
2. in the editor put something in the Opening hours fied
3. check the frontend

#### What I expected

to see the content put into the field

#### What happened instead

nothing is shown

###

The problem seems to be in jetpack/modules/widgets/contact-info.php on line 160:

`'<div class="confit-hours" itemprop="openingHours"></div>',`

Quick fix:

`'<div class="confit-hours" temprop="openingHours">%1$s</div>',`

**Comment by jeherve** [comment]
That's indeed a known issue, it will be fixed in the next minor Jetpack release, scheduled to be released soon.

You can find out more here:
#13982
