### ISSUE TITLE
MailChimp Block Success Message has White Text

### ISSUE THREAD

**Issue by jorgefilipecosta** [Automattic/jetpack#14087]
report by @marcuswisecaesar at https://github.com/WordPress/gutenberg/issues/18647.
**Describe the bug**
First noticed in 2482935-zen on a Simple Site when adding a Jetpack Mailchimp block, the success message after submitting an email address comes through as white text on the white background of the site. 

**To reproduce**
1. On a core WordPress.com site add the MailChimp Block to a Page.
2. Publish the Page.
3. View the Page and enter a test e-mail address into the Form.
4. You will see Processing, but then nothing...

**Expected behavior**
Expected to see Processing message, and then Success as set in the Block Editor.

**Screenshots**
![screenshot](https://cld.wthms.co/TS7CNy+)
[Direct Link](https://cld.wthms.co/TS7CNy)

**Desktop (please complete the following information):**
 - OS: OS X Catalina
 - Browser: Chrome 
 - Version: 78

**Comment by jeherve** [comment]
It seems the problem is limited to WordPress.com simple sites; there the CSS variable `--color-success` is not transformed in `#008a00`. In Jetpack it works.

cc @sirreal who brought in those changes in #13503.

**Comment by sirreal** [comment]
> It seems the problem is limited to WordPress.com simple sites; there the CSS variable `--color-success` is not transformed in `#008a00`. In Jetpack it works.
> 
> cc @sirreal who brought in those changes in #13503.

👋  @simison

**Comment by ockham** [comment]
From a quick glance, this seems like it could be due to the same issue as I described here: https://github.com/Automattic/jetpack/pull/13854#issuecomment-550898168

**Comment by simison** [comment]
FYI @jeffersonrabb who's working on MailChimp block iteration. Wanna help fix this small bug? :-)

**Comment by simison** [comment]
Found the problem, fix at D35821-code

**Comment by simison** [comment]
Fixed in r199801-wpcom
