### ISSUE TITLE
Customize Message for Publicize may not appear in social media

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#14097]
## Summary

Originally reported in 4003-gh-jpop-issues by @senff 

When publishing a new Blog Post, the customized message for sharing on social media isn't used consistently.  In most cases, it does not take it at all. 

## Steps to Reproduce

1. make sure a Twitter account is connected to your site
2. in Calypso create a new Blog Post with a Title and content
3. select the Jetpack icon on the top right of the editing screen.
4. under "Share This Post", add a message in the field "Customize your Message"
5. publish the post

### Expected Result
- the custom message is used in the tweet

### Actual Result
- sometimes/often, it's using the title of the post, and just ignores the custom message

### Workaround 

From @jeherve: 

Try again, with 4 different combinations:

- once by saving your draft before you publish
- once by filling in a custom Publicize text and then publishing right away

Then try the same as above, but on a Jetpack site?

### Additional information

I've tested this on my site. First I published a post called "_Welcome to my blog_" with a custom message "_A fine custom introduction_":

![custom-tweet-1](https://user-images.githubusercontent.com/1710669/59539739-6a55ef00-8ecc-11e9-9888-9ac54259b2e8.png)

This gave the desired result at https://twitter.com/BobWordpress/status/1139641708864520193 :

![custom-tweet-1-good](https://user-images.githubusercontent.com/1710669/59539750-7641b100-8ecc-11e9-8357-93a36e75f1ac.png)

Then I did the exact same thing, only with a different title ("Walcome" instead of "Welcome"):

![custom-tweet-2](https://user-images.githubusercontent.com/1710669/59540700-bbfe7980-8ecc-11e9-9e00-55807a92cb57.png)

This time, it used the post title in the tweet, as you can see at https://twitter.com/BobWordpress/status/1139646483433697282 :

![custom-tweet-2-bad](https://user-images.githubusercontent.com/1710669/59540808-c751a500-8ecc-11e9-8568-af347bc491b4.png)

I made a few more attempts, but I was unable to make it work the way I expected, and it would use the post title every time.

**Comment by sophiegyo** [comment]
Should we still log reports from users in this issue instead of the closed one?
If so, here's one:  2513309-zen

**Comment by jeherve** [comment]
@sophiegyo You can log them here. 👍

**Comment by KokkieH** [comment]
Another report via [Twitter](https://twitter.com/CPMountains/status/1209772602807455744)

**Comment by vajrasar** [comment]
Another report here - #2614310-zen

In my testing, Simple sites fail to produce the expected result every time, however, AT sites succeed.

**Comment by jeherve** [comment]
Closing this in favor of #11752, where we track a similar problem.
