### ISSUE TITLE
Sync: Settings are unfilterable

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/jetpack#14095]
#### Steps to reproduce the issue

1. Add a filter on the `jetpack_sync_settings_max_queue_size` option in theme or plugin code, like:

```
add_filter( 'option_jetpack_sync_settings_max_queue_size', function( $value ) {
    return 1;
} );
```

2. Check option value (`wp shell`):

```
get_option( 'jetpack_sync_settings_max_queue_size' );
int(1)
```

Looks good so far...

3. Check JP Sync Settings value:

```
Automattic\Jetpack\Sync\Settings::get_setting( 'max_queue_size' )
int(1000)
```

Oh no, the default!

#### What I expected

When filtering the options that store Sync settings, those filters should correctly alter the settings returned by `Automattic\Jetpack\Sync\Settings`.

#### What happened instead

The filters are ignored because they were not registered early enough.

As soon as JP loads, it ends up loading the Sync settings - this can happen before userland filters are registered, depending on where they live (theme, or a later loading plugin).

JP Sync Settings has an internal static cache of settings, which means that `get_option()` is only ever called once, before filters can get registered, and therefore we're unable to filter the values.

Here's the code:

https://github.com/Automattic/jetpack/blob/1b981c3573c82a4c83b3c212a241b59097691792/packages/sync/src/class-settings.php#L140-L142

Maybe we can just omit the cache altogether?

**Comment by gravityrail** [comment]
I think we should get rid of the cache. It was a bad idea of mine, premature optimisation, and WordPress caches options for the duration of a request anyway.
