### ISSUE TITLE
Sharing: Make settings mobile-friend

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#141]
Currently, dragging and dropping services is required to activate individual services in Sharedaddy, which fails on mobile as it is impossible to drag any of them (in Android and iOS).

Related: #136

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/how-do-i-add-sharing-buttons-with-an-ipad-mini?replies=1&view=all

**Comment by RCowles** [comment]
Also reported in 2808687-t

**Comment by jeherve** [comment]
Closing this for now since we're now developing a new Sharing settings screen that will be responsive, accessible, and live under Jetpack > Settings.
