### ISSUE TITLE
Sync package needs tests

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#14106]
#### Describe the solution you'd like
I made a change to the Sync package but I had no sync-specific tests I could run. They exist only in the main Jetpack project. At some point, let's move them to the Sync package.

**Comment by anomiex** [comment]
Tests have existed in [projects/packages/sync/tests](https://github.com/Automattic/jetpack/tree/trunk/projects/packages/sync/tests) for a while now.
