### ISSUE TITLE
Jetpack lazy loading breaks materialize parallax

### ISSUE THREAD

**Issue by pbradl42** [Automattic/jetpack#14115]
It took me a while to track this down. I had two identical sites (one dev, one production) - both using materialize 'parallax' for the main landing page. It worked on dev and not production. Code of the page itself is in the screenshot attached.

I went into 'troubleshooting' mode and turned on plugins one at time. The parallax effect stopped when I turned on jetpack. So then I went through jetpacks options.  

It's 'lazyload' that is causing the problem.

Here's a screenshot-video of the bug: https://youtu.be/XFkNvzmUw4c

#### Steps to reproduce the issue

1. Use materialize parallax
2. enable lazy loading

#### What I expected

Parallax should work

#### What happened instead
 It doesn't
<img width="749" alt="Screen Shot 2019-11-24 at 2 39 53 PM" src="https://user-images.githubusercontent.com/12827845/69501635-d8b7c800-0ed4-11ea-8d67-f2a1f4efc4fc.png">

**Comment by jeherve** [comment]
Could you try to add the following to your site, and let me know if this helps?

```php
function jetpackcom_exclude_parallax_lazy_load( $classes ) {
    $classes[] = 'parallax';
    return $classes;
}
add_filter( 'jetpack_lazy_images_blacklisted_classes', 'jetpackcom_exclude_parallax_lazy_load' );
```

**Comment by pbradl42** [comment]
No change unfortunately - just to make sure, I put it in the themes ‘functions.php’ after my ‘add_theme_support (‘post-thumbnails’… line.

Peter Bradley | Director of the Honors Program
Ferris State University
202 South Street, Pickell 142 | Big Rapids, MI 49307
peterbradley@ferris.edu | www.ferris.edu/honors/
@FerrisHonors | @pbradl42
231.591.2216

**Comment by jeherve** [comment]
Thanks for giving that a try.

I'm seeing a few JavaScript errors on your site right now, and I wonder if this may create a conflict with Jetpack's Lazy Images.

![image](https://user-images.githubusercontent.com/426388/69715087-eef99a00-1107-11ea-993c-cd92493bc568.png)

Could you try to remove the Facebook Pixel from your site for a bit, as well as the system adding the counter for your guide metrics?

Let me know if that changes anything.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
