### ISSUE TITLE
Copy Post: Sharing buttons don't appear if post is copied using block editor

### ISSUE THREAD

**Issue by KokkieH** [Automattic/jetpack#14117]
#### Steps to reproduce the issue

1. Make sure the Copy Post module in Jetpack is activated, and that the Classic Editor plugin is not active.
2. At WP-Admin ->Posts, make sure you have a post with sharing and Like buttons enabled, and check the buttons are visible in the published post on the front end
3. Use the Copy Post feature to create a new post
4. Before publishing, check the Jetpack sidebar and make sure sharing and Like buttons are enabled
5. Publish the copied post

#### What I expected

For the sharing and Like buttons to appear below the post content same as on the original post

#### What happened instead
Only the Like button appears. The sharing buttons don't appear.

The only way to get the sharing buttons to appear is to edit the post again, disable sharing buttons and update, enable sharing buttons and update again.

This happens when copying posts using the block editor from both the post lists in WP-Admin and Calypso. If the Classic Editor plugin is installed and the classic editor set as default so it's used to publish the copied post, the sharing buttons appear as they're supposed to.

Reported in the forums at https://wordpress.org/support/topic/share-buttons-dont-show-with-copy-post/

**Comment by KokkieH** [comment]
Another report, this time of it happening on a dotcom site: https://en.forums.wordpress.com/topic/share-button-does-not-appear-on-post/

**Comment by scottsweb** [comment]
Tested in WordPress 5.3.2 with Jetpack 8.1 beta and I am seeing a similar issue, at first everything looks fine from the admin (the Likes and sharing buttons are checked in both the original and the duplicated post).

On the front end though I get different results:

Original:

![Screenshot 2020-01-02 at 16 33 40](https://user-images.githubusercontent.com/411945/71678765-dbcc9080-2d7d-11ea-83bb-1939991d4501.png)

Copy:

![Screenshot 2020-01-02 at 16 33 29](https://user-images.githubusercontent.com/411945/71678786-ebe47000-2d7d-11ea-89dc-d59c884e01e2.png)

Only the like button is visible on the copied post. In the admin, both remain "checked". 

Doing some further investigation

**Comment by scottsweb** [comment]
Meta before:

![Screenshot 2020-01-02 at 16 41 57](https://user-images.githubusercontent.com/411945/71679365-5053ff00-2d7f-11ea-876d-6a7a9d58d36f.png)

Meta after:

![Screenshot 2020-01-02 at 16 45 16](https://user-images.githubusercontent.com/411945/71679377-5c3fc100-2d7f-11ea-8b35-9f7afeea6c83.png)

Looks like we are explicitly setting `sharing_disabled` and `switch_like_status` despite the original post relying on the global setting
