### ISSUE TITLE
Masonry Block: Unable to add/edit image caption

### ISSUE THREAD

**Issue by retnonindya** [Automattic/jetpack#14116]
#### Steps to reproduce the issue

1. Add Masonry block on page/post editor
2. Add some images to populate the gallery
3. For images with pre-existing caption, the caption is editable
4. For images without a caption, you can't add the caption even though there's a text "Write caption..." on the image

**Screen recording (.gif)**

https://cldup.com/oEA6kUPcYa.gif

#### What I expected

The image caption for images within Masonry block should be editable. The text "Write caption..." should be editable and I can enter my preferred caption there.

**Additional information**:
- WordPress.com website with Premium plan and no plugins
- MacOS Catalina. Chrome ver. 78.0.3904.108

**Comment by jeherve** [comment]
That block is provided by CoBlocks, not by Jetpack. I'd suggest reporting this in the appropriate repo.
