### ISSUE TITLE
Admin Page: compact button padding adjustments

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#14128]
In #13946 we made a number of changes to the generic compact DOPS button. It seems it's had an impact on the close buttons we used at the top of some of our modals. Here is an example:

**Before**

<img width="1407" alt="screenshot 2019-11-26 at 12 27 23" src="https://user-images.githubusercontent.com/426388/69626118-446e7200-1048-11ea-8926-b2477cbb08f2.png">

**Now**

<img width="1433" alt="screenshot 2019-11-26 at 12 28 09" src="https://user-images.githubusercontent.com/426388/69626127-4801f900-1048-11ea-939f-96839bfd1d57.png">

**Comment by scottsweb** [comment]
Picking this up, expect a PR shortly
