### ISSUE TITLE
Ratings Block: improve accessibility

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#14120]
See discussion here:
https://github.com/Automattic/jetpack/pull/14091#discussion_r349804845

> I wonder if we should add more to that markup to make the block output more accessible to screen readers?
> I get simple "yellow five-pointed star" indicators when loading our markup on its own:
> https://jeherve.keybase.pub/testing-rating.html
> I think we could add some content to wrap the whole rating to mention what it is.

**Comment by simison** [comment]
Other places where block fallback content is important:

- RSS feeds
- Emails
- WordPress.com reader
- When exporting content to another site
