### ISSUE TITLE
Comment form to expand

### ISSUE THREAD

**Issue by metodiew** [Automattic/jetpack#1412]
This is an year old post, but it's still valid case: https://wordpress.org/support/topic/default-comment-form-to-expanded. I'm creating this issue based on Twitter conversation: https://twitter.com/daljo628/status/542411341193945088
cc @georgestephanis

**Comment by samhotchkiss** [comment]
This is not in line with our current priorities/roadmap.  We may re-assess down the road, but I'm closing for now.  If there are 3 more requests after this comment, please re-open.

**Comment by jeherve** [comment]
It's a quite common request in the forums. In general, requests to customize the look of the form are fairly common.

Here are 2 examples:
- https://wordpress.org/support/topic/jetpack-comment-form-is-always-collapsed?replies=3&view=all
- https://wordpress.org/support/topic/how-to-get-jetpack-comment-box-opened-as-expanded-always-1?replies=2&view=all

I'll make sure to post links to future requests here.

Related: #477

**Comment by metodiew** [comment]
I remember at least 10 different conversation with people who are asking about feature like this. For me, having this option would be something really useful, especially for visitors who might missed the comment section otherwise

**Comment by richardmtl** [comment]
Requested in 2646854-t

**Comment by kevinhq** [comment]
Any updates on this 2020? Or is this just abandoned request?
