### ISSUE TITLE
Social Menu & Social Media Icons: Add Patreon Support

### ISSUE THREAD

**Issue by supernovia** [Automattic/jetpack#14122]
#### Is your feature request related to a problem? Please describe.
Not exactly, but it would be nice.

#### Describe the solution you'd like
Add Patreon to Social Icons Widget

#### Describe alternatives you've considered
Using a separate widget. We also suggested using Jetpack's Recurring Payments.

#### Additional context
User requested here:
https://twitter.com/NeilEvansRocks/status/1199064507609468928

I'm sure other users would find it handy, too.

**Comment by supernovia** [comment]
Not stale; if I have icon I can probably try to sort this one out

**Comment by sdixon194** [comment]
[Opened an icon request here ](https://github.com/Automattic/social-logos/issues/101)so we can have Patreon added to our social logo repo, then we can add support for the menus/widget.
