### ISSUE TITLE
Performance Optimization: Plugin upgrade routine

### ISSUE THREAD

**Issue by blobaugh** [Automattic/jetpack#1413]
On every page load I see the query

```
SELECT option_value FROM wp_options WHERE option_name = 'jetpack_id' LIMIT 1;
```

This query is only referenced in a single place in Jetpack and that is the Jetpack::plugin_upgrade() method: https://github.com/Automattic/jetpack/blob/master/class.jetpack.php#L287

The upgrade call is triggered **every** time Jetpack loads. This causes an additional unneeded query to run for every Jetpack install since 1.2. 

There is additional logic inside the plugin upgrade method that is also utilizing resources that do not need to be consumed on every page load

See https://github.com/Automattic/jetpack/blob/master/class.jetpack.php#L267

It would be more optimal to use a hook for running the plugin updates such as *upgrader_process_complete*
See http://codex.wordpress.org/Plugin_API/Action_Reference/upgrader_process_complete

**Comment by jubstuff** [comment]
I think that this issue can be closed since the code responsible for that query was removed in [this PR](https://github.com/Automattic/jetpack/pull/3537)

**Comment by kraftbj** [comment]
👍
