### ISSUE TITLE
Performance Optimization: Minileven query does not always need to run

### ISSUE THREAD

**Issue by blobaugh** [Automattic/jetpack#1414]
There is a query on Minileven that is always running regardless of if it is needed. This query should only be running on pages that are available for displaying the ad on. When in wp-admin it does not need to run at all. It might also be worth looking into storing this option in the Jetpack option so that even if it does run all the time it will not perform another database query but instead a simple array lookup.

See https://github.com/Automattic/jetpack/blob/master/modules/minileven.php#L16

**Comment by samhotchkiss** [comment]
Makes sense, but isn't in line with our current goals for Jetpack and isn't high priority enough to focus on right now.  Would be open to PRs from the community addressing this.

**Comment by kraftbj** [comment]
Resolved by https://github.com/Automattic/jetpack/commit/ad3872413d5879be1526a2fac2c728eee3d9e3c5
