### ISSUE TITLE
Pinterest: return error when a Pinterest URL cannot be turned into an embed

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#14157]
#### Steps to reproduce the issue 

1. Add a Pinterest block to a new post.
2. Paste in the following URL: `https://www.pinterest.co.uk/invalidurltest/`
3. You receive no validation error or any indication about what happened.

It would be nice if you could get an error showing that this is not a valid pin / board / Pinterest embed URL.

Reported here:
p8oabR-qW-p2#comment-3734

**Comment by creativecoder** [comment]
For reference, this is what you see when this happens

<img width="698" alt="Screen Shot 2020-02-25 at 22 54 00" src="https://user-images.githubusercontent.com/1699996/75313196-c0cc4900-5821-11ea-8cc9-f8138cef56af.png">

Additionally the error message should use a notice

<img width="631" alt="Screen Shot 2020-02-25 at 22 59 47" src="https://user-images.githubusercontent.com/1699996/75313535-b9f20600-5822-11ea-8cd2-71982c2671f7.png">

**Comment by apeatling** [comment]
This looks like a more in depth fix since the checks currently are just basic regex checks on the URL. We'd need to expand this to make some sort of request to check the validity of a URL first of all. Not sure it is worth the time investment.

**Comment by creativecoder** [comment]
The Eventbrite block handles this by [checking all URLs with a resolve redirect function](https://github.com/Automattic/jetpack/blob/master/extensions/blocks/eventbrite/edit.js#L70), including transforms, and erroring if those links return a 404 status. 

Pinterest does a similar resolve redirect, but only for `pin.it` urls. I don't think it would be too hard to tweak the Pinterest block so it checks the transform links, as well.

**Comment by apeatling** [comment]
Great! Let me give that a go.

**Comment by apeatling** [comment]
@creativecoder Thanks for pointing me in the right direction here, this was actually quite easy once I was looking in the correct place. A good reminder to ask before making a final assessment. :)
