### ISSUE TITLE
Ads doesn't set status code for ads.txt

### ISSUE THREAD

**Issue by hastinbe** [Automattic/jetpack#14169]
#### Steps to reproduce the issue

1. Enable Ads under Traffic
2. Request domain.com/ads.txt
3. Content for the ads.txt is returned but the status code is 404

#### What I expected
The ads.txt data and an HTTP 200 status code.

#### What happened instead
The ads.txt data was returned in the response body but the HTTP status code is 404, which was set by the web server because a physical ads.txt did not exist.

The response will be ignored and the file will be considered non-existent by Google's crawler if the response code is not a 200.

**Comment by htdat** [comment]
Just for ref, I've noticed two users with this issue: 

2515605-zen 
2541726-zen

**Comment by htdat** [comment]
I've updated two tickets above and asked them to use this snippet (created by @zinigor). 

**When JP 8.1 is released, this snippet should be removed.** 

Note: we recommend following this guide to add snippets https://jetpack.com/support/adding-code-snippets/

```php
function jetpack_filter_ads_txt_status_header( $string, $code, $description, $protocol ) {

	// Only running on URLs that end on /ads.txt
	if (
		! isset( $_SERVER )
		|| ! isset( $_SERVER['REQUEST_URI'] )
		|| false === strpos( '/ads.txt', $_SERVER['REQUEST_URI'], -8 )
	) {
		return $string;
	}
	return sprintf( "%s 200 OK", $protocol );
}
add_filter( 'status_header', 'jetpack_filter_ads_txt_status_header', 10, 4 );
```

**Comment by tmmbecker** [comment]
I modified that predef a bit and added it to TE: `jp.ads404-8.0`
