### ISSUE TITLE
Map Block: multiple location markers error

### ISSUE THREAD

**Issue by catkiinson** [Automattic/jetpack#14177]
#### Steps to reproduce the issue

1. Add the map block.
2. Add 3 location markers with different addresses.

#### What I expected
To be able to successfully add more than two location markers and still be able to view and edit the block in the editor. 

#### What happened instead
Received this error and the block could no longer be viewed in the editor. 
![Screen Shot 2019-12-04 at 6 36 38 PM](https://user-images.githubusercontent.com/43645273/70198943-357d6480-16c5-11ea-92a7-611d32950342.png)

The map did show when using "Preview" and on the live site after publishing. 

User reported on their simple site in 2354189-HC. I was able to replicate on my own AT test site.

**Comment by jeherve** [comment]
cc @jeffersonrabb Any idea about what could cause this?

**Comment by jeffersonrabb** [comment]
I can repro as well. It looks like it may relate to a change in the Mapbox library. Here's the console error: 

```TypeError: Cannot read property 'off' of undefined
    at No.onRemove (mapbox-gl.js:32)
    at r.removeControl (mapbox-gl.js:32)
    at Map.eval [as setBoundsByMarkers] (component.js:170)
    at Map.componentDidUpdate (component.js:339)
    at qi (react-dom.min.js:130)
    at ui (react-dom.min.js:133)
    at react-dom.min.js:158
    at unstable_runWithPriority (react.min.js:27)
    at Vc (react-dom.min.js:158)
    at Sc (react-dom.min.js:158)```

I'm digging in...
