### ISSUE TITLE
Instant search: add option to clear out search

### ISSUE THREAD

**Issue by keoshi** [Automattic/jetpack#14181]
#### Steps to reproduce the issue

- Enter any search term; e.g.: "maintenance".

or

- Filter content using any of the filters available; e.g.: "Year: 2019".

#### What I expected

- To have an option to clear out my search query and/or filters.
- This could be as simple as a cross, or it could be a link.
- It would clear out the search box, toggle all filters back off, and rewrite a clean URL.

![image](https://user-images.githubusercontent.com/390760/70234772-4c6d9680-1759-11ea-8d0b-39b6b93fd5d5.png)

#### What happened instead

- I'm left with clicking back in my browser (see https://github.com/Automattic/jetpack/issues/14180 for related issue) or clicking the navigation menu to go to another page.

Related: https://github.com/Automattic/jetpack/issues/13814

**Comment by bluefuton** [comment]
#14324 added a 'clear filters' button, but there's still no functionality to clear out a search term.

**Comment by gibrown** [comment]
This shipped last week.
