### ISSUE TITLE
Map-block API Level - Change to 1.+

### ISSUE THREAD

**Issue by bracketsberlin** [Automattic/jetpack#14183]
Hi there,
Mapbox has two methods of billing: pay per tile request and pay per map view. With your animations, auto-center near SF, etc. the map per tile request gets very expensive pretty quick. We had to deactivate the plugin since only some users (1000) made XXXXX tile requests. Could you please update the mapbox API version to 1.0+ as stated here? https://docs.mapbox.com/accounts/overview/pricing/#mapbox-gl-js-v100-and-higher

This would enable one to switch to the "pay per map view" (unlimited tile requests) mode.

Thanks

**Comment by jeherve** [comment]
For reference, we currently use v0.54.1:
https://github.com/Automattic/jetpack/blob/8e65975bb5f1bfdfb643b7f5f14063d1d5c10f92/package.json#L133

cc @jeffersonrabb who first worked on the block in https://github.com/Automattic/wp-calypso/pull/28498/
