### ISSUE TITLE
Instant search: search doesn't work from 404 page

### ISSUE THREAD

**Issue by keoshi** [Automattic/jetpack#14184]
#### Steps to reproduce the issue

- Go to a non-existent page on the site where a search form is visible.
- Try to enter “posts” into the search box.

#### What I expected

To be able to enter my query and to see results populate the bottom portion.

#### What happened instead

Search results took over that entire container and the search box only captured the first character.

#### Screen capture

![jps-search-from-page](https://user-images.githubusercontent.com/390760/70243909-72039b80-176b-11ea-9cb0-633026bfdd11.gif)

**Comment by bluefuton** [comment]
The new overlay approach fixes this 🎉

![2020-01-14 15-24-52 2020-01-14 15_25_19](https://user-images.githubusercontent.com/17325/72308843-2a651d80-36e2-11ea-9b28-746490fadfd2.gif)

**Comment by keoshi** [comment]
Amazing! Thanks, @bluefuton.
