### ISSUE TITLE
Photon: stop photonizing og:image links.

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1419]
We are photonizing `og:image` links which are causing some issues when Publicizing to Facebook.
@jeherve pointed out that it's coming from this commit: https://github.com/Automattic/jetpack/commit/1bdffc8094b549c89cd85730a4428207c1117c5c

**Comment by jkudish** [comment]
What kind of issues is this causing @mikeyarce ?

**Comment by mikeyarce** [comment]
@jkudish specifically we've seen issues where Facebook doesn't like images from Photon when a post is Publicized - and so it just won't display any images instead.

**Comment by jkudish** [comment]
Some concrete examples would be really helpful.

**Comment by kraftbj** [comment]
It's been about a year since it was first reported. @jeherve any insight and are we still seeing this?

**Comment by jeherve** [comment]
Some images are still photonized, but we haven't had any reports from Facebook on this for quite a while now. Closing this for now, we'll reopen if it resurfaces.

**Comment by jeherve** [comment]
Actually just got a new report here:
https://wordpress.org/support/topic/still-troubles-with-facebook-publicize?replies=1&view=all

**Comment by kraftbj** [comment]
Another report in 2418740-t. Reopening.

**Comment by kraftbj** [comment]
Er, after further investigation, other things was causing 2418740. I'll re-close.
