### ISSUE TITLE
Post by email: improve the log

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#14206]
Currently, we don't have a good way to investigate if an email was delivered as expected since we don't store the the api response. Let's add some logging around that.

**Comment by jeherve** [comment]
Is that something you'd see on the WordPress.com side, or something you'd like to see available to end users?

I am asking since we do have some data on the WordPress.com side already.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
