### ISSUE TITLE
Invalid argument supplied for foreach(), since 8.0 and using the WP-CLI

### ISSUE THREAD

**Issue by larssn** [Automattic/jetpack#14202]
#### Steps to reproduce the issue

1. Install the wp-cli.
2. Just type `wp` standing in the wordpress root directory.

#### What I expected
No warning

#### What happened instead
The following warning is thrown:
`Warning: Invalid argument supplied for foreach() in wordpress/wp-includes/rest-api/endpoints/class-wp-rest-controller.php on line 295`

Pre. 8.0 no warning was generated, so you must've changed something.

Disabling jetpack removes the warning.

The function breaking is this one:
```
        /**
	 * Retrieves the item's schema for display / public consumption purposes.
	 *
	 * @since 4.7.0
	 *
	 * @return array Public item schema data.
	 */
	public function get_public_item_schema() {

		$schema = $this->get_item_schema();

		foreach ( $schema['properties'] as &$property ) {
			unset( $property['arg_options'] );
		}

		return $schema;
	}
```

How critical it is, that this function doesn't work as expected is not something I can answer.

**Comment by jeherve** [comment]
Thanks for the report!

I can't seem to be able to reproduce the issue on my end right now. Do you think you could give me a few more details about your setup, so I can try to reproduce?

- Do you have any other plugins active? If so, which ones?
- What's your version of WP? 
- What's your version of PHP?
- Does this happen regardless of the theme you use?

**Comment by larssn** [comment]
@jeherve Hey, thanks for replying.
You may be onto something, I think WooCommerce is an element in this happening.

If Jetpack and WC is enabled: The warning happens
If only WC is enabled: Warning goes away.
If only Jetpack is enabled: Warning goes away.
Changing the theme doesn't affect the above.

- Mine and our servers' WP versions are: 5.3
- Local php version is: 7.3.11
- Servers' php version is: 7.2.24-0ubuntu0.18.04.1

**Comment by jeherve** [comment]
Thanks for the extra details.

This appears to be a bug in WordPress itself, as JSON Schema appears to allow for the base type to not be an `object`, so `properties` won’t necessarily be defined here.

It is currently being tracked here:
https://core.trac.wordpress.org/ticket/48785
