### ISSUE TITLE
Sharing / AMP: unsupported services are still displayed when using Official Buttons

### ISSUE THREAD

**Issue by Zabi09** [Automattic/jetpack#14217]
Firstly I am using the latest version of both AMP and jetpack - https://prnt.sc/q9s3uv and if I use the official button option - https://prnt.sc/q9s76p then the output of the AMP is really not looking good.
See this screenshots:
https://prnt.sc/q9s5jv
https://prnt.sc/q9s6fp

**Comment by htdat** [comment]
@jeherve this seems a duplicate of https://github.com/Automattic/jetpack/issues/12639 ?

**Comment by jeherve** [comment]
@htdat Yes you're right. Closing this as duplicate.
