### ISSUE TITLE
Contact Form Block: Unable to use square brackets [] in form labels

### ISSUE THREAD

**Issue by jordesign** [Automattic/jetpack#14223]
I've discovered that when a closing square bracket (`[]`) is used in the label of a field - it seems to display the remainder of the field declaration on the front end, and breaks the next label.

#### Steps to reproduce the issue

1. Edit a page or post
2. Add a Form block 
3. Insert a label which contains square brackets `[]`
4. Publish the page/post and then view it

#### What I expected
The form and labels to be displayed correctly

#### What happened instead
The form renders incorrectly - with the label showings as broken, and unexpected HTML output instead.

**Screenshots**
<img width="1146" alt="Screen Shot 2019-12-13 at 4 44 11 pm" src="https://user-images.githubusercontent.com/1842363/70788809-d1098600-1de5-11ea-8849-83564770187d.png">
Form fields in the editor

<img width="759" alt="Screen Shot 2019-12-13 at 8 16 51 pm" src="https://user-images.githubusercontent.com/1842363/70788810-d1098600-1de5-11ea-81d5-941ff67d32ad.png">
Front end of site

----
This may be related to #7713 (which seems similar but for the contact form shortcode)

**Comment by jeherve** [comment]
> This may be related to #7713

It is indeed the same issue, as it is the same code powering both the shortcode and the block. I'll close this issue, we can keep track of things in the other issue.

Thanks for the report.
