### ISSUE TITLE
Sharing: Don't allow URL to be entered into email sharing `Name` field

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#14221]
Currently, it's possible to enter a URL in the `Name` field when using the email sharing button:

![](https://d.pr/i/GhqADC+)
Image Link: https://d.pr/i/GhqADC

This seems like a potential security risk or at least a spam risk. Would it be possible to disallow URLs in that field?

**Comment by jeherve** [comment]
Closing as duplicate of #5271
