### ISSUE TITLE
Gallery: Gallery Widget Style Options missing on WordPress.com, gallery resource 404'ing

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/jetpack#14237]
Gallery Widget is missing [Style options](https://en.support.wordpress.com/widgets/gallery-widget/).  May also be impacting other gallery options elsewhere that rely on the missing resource. 

`Failed to load resource: the server responded with a status of 404 ()`
`https://s1.wp.com/wp-content/mu-plugins/jetpack/_inc/build/gallery-settings.min.js?ver=20121225`

A similar issue of missing resources were recently reported and resolved on https://github.com/Automattic/jetpack/issues/14235 , https://github.com/Automattic/wp-calypso/issues/38434 , and the code that was reverted via D36769-code

Internal discussion of previous issue(s): p1576334924003000-slack-dotcom

However, this issue appears to be present regardless of where the site is hosted.  ***See my first reply to this as this actually appears to be WordPress.com specific since the Gallery Widget in Jetpack was deprecated after WP 4.9***.

#### Steps to reproduce the issue

1 Add new Gallery widget on a site (Appears to be impacting WordPress.com sites and self-hosted)
2. See error, lack of style options as noted at https://en.support.wordpress.com/widgets/gallery-widget/
3. Check the console for missing resource errors. 

#### What I expected
Gallery style options to be available. 

#### What happened instead
Images can be added but no style options.

**Comment by JoshuaGoode** [comment]
Hmm, on second thought -- wasn't the Gallery widget deprecated in Jetpack after WP 4.9?

So would this be more of a WPCOM specific thing since we were still providing, or documenting, it as an option?

**Comment by noora7776** [comment]
--
Sent from Outlook Email App for Android السبت, ١٤ ديسمبر ٢٠١٩, ٠٨:٣٤م +03:00 from VeryGoode  notifications@github.com :

**Comment by davoraltman** [comment]
Adding 2561190-zen here so that we can follow up when this gets fixed.

**Comment by lakellie** [comment]
Another report in 2562746-zen

**Comment by kraftbj** [comment]
Someone on Crew or myself will investigate at last within the next 24 hours. The report timing matches the other issues but the one that caused the earlier headache was reverted. It may be related to adding packages to WP.com but the timing isn't a slam dunk.

**Comment by kraftbj** [comment]
This is resolved as of r200743-wpcom. Same root issue as discussed in https://github.com/Automattic/jetpack/pull/14204#issuecomment-565775268
