### ISSUE TITLE
Jetpack 8.0 Update: Site Experiencing a Technical Issue

### ISSUE THREAD

**Issue by mrwweb** [Automattic/jetpack#14243]
I have updated a number of sites to Jetpack 8.0 just now and have received 3 "Your Site is Experiencing a Technical Issue" so far. They all list the same error.

The error is always caught on a page like: `/wp-load.php?no_cache_XXXXXXX=YYYYYYYYYY`. Visiting that page reveals a blank screen.

> Error Details
> =============
> An error of type E_ERROR was caused in line 270 of the file /wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/Listener.php. Error message: Uncaught Error: Class 'Automattic\Jetpack\Roles' not found in /wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/Listener.php:270
> Stack trace:
> #0 /wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/Listener.php(239): Automattic\Jetpack\Sync\Listener->get_actor('jetpack_plugins...', Array)
> #1 /wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/Listener.php(114): Automattic\Jetpack\Sync\Listener->enqueue_action('jetpack_plugins...', Array, Object(Automattic\Jetpack\Sync\Queue))
> #2 /wp-includes/class-wp-hook.php(288): Automattic\Jetpack\Sync\Listener->action_handler(Array, Array)
> #3 /wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
> #4 /wp-includes/plugin.php(478): WP_Hook->do_action(Array)
> #5 /wp-content

The sites have overlapping plugins but are on at least two different hosts (Bluehost, SiteGround) and use very different themes (child themes of Twenty Sixteen, Twenty Fifteen, and Shoreditch).

I'm happy to try to provide further info as requested.

**Comment by jeherve** [comment]
That's indeed a known issue with the update. You can read more about it here:
https://wordpress.org/support/topic/fatal-error-when-updating-to-jetpack-8-0-read-this/

The error should only happen during the update, though.

We're working on ways to prevent this in the future in #14172
