### ISSUE TITLE
Flows: Stats Configure link should open the card

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#14255]
#### Steps to reproduce the issue

1. Go to Jetpack->Site Stats (in wp-admin)
2. Click on the "Configure" link near the top.
3. See that you're directed to the React admin settings page.

#### What I expected
The Stats setting card to be expanded so I could see the settings without having to click to expand the card.

#### What happened instead

The stats setting card is the only item present, but collapsed.

**Screenshots**

![2019-12-17 at 4 25 PM](https://user-images.githubusercontent.com/88897/71039585-1a115100-20ea-11ea-9a75-4a5c377de1d3.png)

**Comment by jeherve** [comment]
closing as duplicate of #15657
