### ISSUE TITLE
Toolbar / Stats: change link for sparkline to point to Calypso instead of WP Admin

### ISSUE THREAD

**Issue by lancewillett** [Automattic/jetpack#14258]
The stats sparkline in the masterbar still links to the wp-admin version of stats. Could we link this directly to wordpress.com instead? Calypso

Steps to repeat:

1. Log in to your Jetpack site
2. Look at the toolbar on the front end — the stats "sparkline" is next to the "New" post link
3. Click the sparkline graphic

Example:
<img width="1392" alt="Screen Shot 2019-12-17 at 17 50 59" src="https://user-images.githubusercontent.com/66797/71046519-cad11d80-20f5-11ea-88a4-f8f20cada824.png">

**Old URL:**
https://chilly-laughing.jurassic.ninja/wp-admin/admin.php?page=stats

**New URL:**
https://wordpress.com/stats/day/chilly-laughing.jurassic.ninja

**Comment by lancewillett** [comment]
Suggested in testing by @m on ma.tt

I'm able to replicate the old behavior on both Jurassic Ninja and my own Jetpack sites.

_Details_
- Latest WordPress: 5.3.1
- Jetpack beta plugin: release candidate (8.0)
- Twenty Twenty default theme

**Comment by jeherve** [comment]
> Could we link this directly to wordpress.com instead?

Noting that we can't flip this to wpcom for everyone; we would need to check if the user's local account is connected to WordPress.com first, as we don't want to display a link to WordPress.com stats for folks who do not have access to WordPress.com for that site.

**Comment by jeherve** [comment]
This can now be closed, since the wp-admin stats page was redesigned.
