### ISSUE TITLE
Build: Dashboard, Instant Search, Blocks broken in IE11

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#14273]
Originally reported in 4578-gh-jpop-issues

*************

All our bundles are currently broken in IE11, as more and more of our dependencies we rely on use ES6, which can't be used in IE11.

There are different ways to solve that problem. 

In the past, we have made an exception and transpiled modules that shipped with ES6:
#12511 
#12541 

Calypso does that for multiple modules:
https://github.com/Automattic/wp-calypso/blob/5d143f1e7f4d96ddf833db4e0c42c0598d9406aa/webpack.config.js#L126

A potential solution that would work for everyone could be to rely on `calypso-build` to do that work for us:
https://github.com/Automattic/wp-calypso/pull/33496
https://github.com/Automattic/wp-calypso/pull/33492

**Comment by ockham** [comment]
@jsnajdr recently merged https://github.com/Automattic/wp-calypso/pull/38531 -- an update to `calypso-build` v6 might thus fix the issue.

**Comment by jeherve** [comment]
Yep, waiting on Renovate to hit us up with a PR soon :)

**Comment by simison** [comment]
Not sure why Renovate isn't updating this PR even if it's been some time since calypso-build v6.0.0 update: https://github.com/Automattic/jetpack/pull/14194

**Comment by jeherve** [comment]
I can't seem to build Jetpack with Calypso Build 6.0.0:

```
Message:
    Module build failed (from ./node_modules/@automattic/calypso-build/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
[BABEL] wp-content/plugins/jetpack/node_modules/@automattic/format-currency/node_modules/debug/src/browser.js: Cannot find module '@babel/plugin-transform-runtime' from 'wp-content/plugins/jetpack'
```

**Comment by simison** [comment]
> can't seem to build Jetpack with Calypso Build 6.0.0:

I think both @blowery and @jsnajdr are AFK today but I'll ping 'em anyway 😁

**Comment by simison** [comment]
Blocks & Search bundles were mentioned fixed.

Did the Jetpack dashboard also get fixed?

**Comment by jeherve** [comment]
> Did the Jetpack dashboard also get fixed?

Yes, it works well in IE11 in my test.
