### ISSUE TITLE
Event Countdown Block: Base on Site Timezone

### ISSUE THREAD

**Issue by Aurorum** [Automattic/jetpack#14289]
Is this an appropriate place to write about the Event Countdown block? I can't find the code or any issues related to it here, but Jetpack is in the class name of the block, and this is on a WordPress.com site.

#### Is your feature request related to a problem? Please describe.
Currently, the block counts down to a date and time based on the date of the user's device. This can be quite frustrating when wanting to countdown to a single event on a blog that is viewed across the world. 

#### Describe the solution you'd like

It would be much better if the date and time was based on the timezone in Settings (or at least if there was an option for this to be the case). 

![Screenshot_20200101-205527](https://user-images.githubusercontent.com/43215253/71644425-2942f200-2cd9-11ea-8397-58d206d2bb00.jpg)

#### Describe alternatives you've considered
I'm afraid there's none I can think of (I'm quite limited as a WordPress.com blogger on a Free plan)

**Comment by jeherve** [comment]
Thanks for the report!

I'll move this issue to another repository, where the block is being developed.
