### ISSUE TITLE
Jetpack Subscriptions: E-Mail field is invalid when no e-mail was entered

### ISSUE THREAD

**Issue by patschi** [Automattic/jetpack#1428]
Hello,

I noticed a little bug since I upgraded to 3.3, which got published some hours ago. It seems that the e-mail box is shown as invalid, even no e-mail address was entered yet:
![2014-12-16_091618-y7fux](https://cloud.githubusercontent.com/assets/2029878/5450345/7e5bd6e4-8504-11e4-8f44-35087c714c81.png)

Finally I found the cause, why this is happening: It is because the default value. If I remove the "value" html attribute from the input box, the "invalid-tag" is gone.
```
<p id="subscribe-email"> 
  <label id="jetpack-subscribe-label" for="subscribe-field" style="clip: rect(1px 1px 1px 1px); position: absolute; height: 1px; width: 1px; overflow: hidden;"> Email Address </label> 
  <input type="email" name="email" value="Email Address" id="subscribe-field" placeholder="Email Address" data-cip-id="subscribe-field">
</p>
```

Regards,
Patrik

**Comment by welho63** [comment]
Hi. It looks to me that the Subscribe Placeholder widget option is not doing anything at all, at least not on Safari or Chrome on Mac (Jetpack 3.3, WordPress 4.1). Regardless of the string I enter in the widget configuration options, the website shows Email Address in the email field. This looks like a bug to me, but perhaps someone better versed in Jetpack can comment. My site is http://behavioralquant.com/. Many thanks!

**Comment by jeherve** [comment]
@welho63 That bug will be fixed in the next Jetpack release. You can apply b1d993bfb8d020ed51ac6a875e60156ea332a9e3 if you want to make the change on your site now.
