### ISSUE TITLE
Instant Search: apply overlay settings from customizer without a page reload

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#14296]
I think it should be possible to pass customizer changes directly to the front end app (related posts does it here: https://github.com/Automattic/jetpack/blob/89a9af96b669e2e5a2ed47d3f3e07c804d6e0dd0/modules/related-posts/related-posts-customizer.js and https://developer.wordpress.org/themes/customize-api/the-customizer-javascript-api/).

This would make for a much better UX than needing to reload the page to see how the opacity or colors are changing.

**Comment by gibrown** [comment]
We should also change some of the default colors when the user changes from light to dark mode. See https://github.com/Automattic/jetpack/pull/14429#issuecomment-577701918

**Comment by bluefuton** [comment]
Fixed by @jsnmoon in #14504.
