### ISSUE TITLE
Contact info block: Phone number schema does not appear in stuctured data

### ISSUE THREAD

**Issue by KokkieH** [Automattic/jetpack#14298]
#### Steps to reproduce the issue

1. Add the Contact info block to the site's front page
2. Fill in the email address, phone number and address
3. Publish/update the page, and submit the URL to Google's Structured Data Testing tool at https://search.google.com/structured-data/testing-tool/u/0/

#### What I expected

For the Organization card in the results to include the phone number

#### What happened instead
Email and physical address are listed, but not the phone number

**Screenshots**

Block as added on my test site:

![Add_New_Page_‹_My_Core_Sandbox_—_WordPress](https://user-images.githubusercontent.com/11873759/71804056-1464b680-306b-11ea-9b09-dae44385df4e.png)

Results if I run it through the testing tool:

![Structured_Data_Testing_Tool](https://user-images.githubusercontent.com/11873759/71804101-29414a00-306b-11ea-85a9-5367e9400935.png)

For comparison, here's how it appears if I use the Contact Info widget instead:

![Structured_Data_Testing_Tool](https://user-images.githubusercontent.com/11873759/71804165-5857bb80-306b-11ea-95c2-26b5e65eae23.png)

Reported in https://wordpress.org/support/topic/contact-info-block/

**Comment by jeherve** [comment]
Good catch. I think that's because the phone number is wrapped in a link tag `a` instead of a `span`.
https://github.com/Automattic/jetpack/blob/43f02648806d6a927445e528a007176a76e31875/extensions/blocks/contact-info/phone/save.js#L38

**Comment by skumar1st** [comment]
Hi,
Above path (jetpack/extensions/blocks/contact-info/phone/save.js) is not available. Only two files are available.
jetpack\extensions\blocks\contact-info\class-jetpack-contact-info-block.php
jetpack\extensions\blocks\contact-info\contact-info.php

Need to create this path or something else.

Pls guide.

**Comment by jeherve** [comment]
@skumar1st The file I referenced is not shipped with the production version of Jetpack. It is only available in the development version of Jetpack available here on GitHub, and used to build a minified JavaScript bundle including all Jetpack blocks.

**Comment by skumar1st** [comment]
I am not tech background.
Could you please confirm when this bug will fix?

Thanks.

**Comment by jeherve** [comment]
@skumar1st We'll comment here as soon as we start working on this problem.
