### ISSUE TITLE
Can't "like" a post when logged into Safari

### ISSUE THREAD

**Issue by annezazu** [Automattic/jetpack#14317]
#### Steps to reproduce the issue

1. Make sure you are logged out of WP.com on Safari
2. Open a post in Safari. For example: https://rostgaard.org/2019/10/15/holsteintor/
3. Try to like the post
4. This will force the login flow for WP.com for you to complete

Note: this happens for both WP.com simple sites and Jetpack connected sites.

#### What I expected

I expected the like would show up on the post. 

#### What happened instead

A strange loop happens that triggers an initial pop up screen that then disappears. 

**Screenshots**

Here's a video recording of me talking through it (apologies for the rambling at the end):

https://cloudup.com/ctN63IOnYav

I'm using Safari Version 12.1.1 (14607.2.6.1.1).  Perhaps this is related to Safari ITP?

**Comment by jeherve** [comment]
Closing as duplicate of #15184
