### ISSUE TITLE
Instant Search: Add some dummy content on the search page

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#14311]
If you go directly to a search page link then we are bypassing the main search query to avoid hitting the DB, but that also means we have no content to show.

<img width="1284" alt="Screen Shot 2020-01-08 at 4 52 19 PM" src="https://user-images.githubusercontent.com/820871/72026018-4c205980-3237-11ea-9b6a-71640baa1099.png">

I tried adding some dummy content that I return, but this generates a bunch of warnings and is still not ideal:

```
		return array(			return array();
			new WP_Post(	
				array(	
					'ID'             => 1,	
					'post_author'    => 1,	
					'post_date'      => current_time( 'mysql' ),	
					'post_date_gmt'  => current_time( 'mysql', 1 ),	
					'post_title'     => 'Some title or other',	
					'post_content'   => 'Whatever you want here. Maybe some cat pictures....',	
					'post_status'    => 'publish',	
					'comment_status' => 'closed',	
					'ping_status'    => 'closed',	
					'post_name'      => 'fake-page',	
					'post_type'      => 'page',	
					'filter'         => 'raw',	
				)	
			),	
		);
```

This probably needs some design work @keoshi. The main page is only really visible until the js has completed loading, and we discussed having the close box trigger loading the home page for these cases, so not super important.

**Comment by keoshi** [comment]
Just to be clear, are we talking about a scenario where:

- We go directly to a search page URL; e.g.: https://mygroovydomain.com/?s=psts
- See the overlay with no search results.
- Close the overlay but I'm still on an a page with no results; e.g.: https://mygroovydomain.com/?s=psts

Is that correct?

If so, what you proposed sounds good to me: 

> having the close box trigger loading the home page for these cases

Because if a customer has instant search enabled (via the overlay), the actual/default search page — https://mygroovydomain.com/?s=psts — is no longer needed, and once the overlay is closed it makes sense to redirect visitors to the homepage.

**Comment by gibrown** [comment]
Cool ya the close box triggering a home page reload seems good for that case.

There is also a short period of time where the main html on the search page is loading, but the js has not yet loaded and so we don't have anything we can yet display. 

![loading-search-page](https://user-images.githubusercontent.com/820871/72288797-0ed91480-3607-11ea-8a68-20a0be062e3f.gif)

Now that I am saying it though, I wonder if we have any empty state for the overlay that we could load and display server side when we are on a search page. @jsnmoon @bluefuton would that be possible do you think? We have the overlay sidebar hidden by default, could/should we not hide it when on a search page and also display some loading content in an overlay?

**Comment by bluefuton** [comment]
> I wonder if we have any empty state for the overlay that we could load and display server side when we are on a search page.

Sounds like a good idea 👍 We need to check if Instant Search is active and have a peek in the query string for search-y arguments.

**Comment by keoshi** [comment]
That does sound like an interesting solution to avoid that tiny delay, just hope it doesn't add a lot of overhead (both in terms of project and performance-wise).

**Comment by gibrown** [comment]
Removing from the launch milestone in favor of #14532

**Comment by jsnmoon** [comment]
I believe this has already been implemented, please re-open if not.
