### ISSUE TITLE
Means to filter out spams that keep changing domains

### ISSUE THREAD

**Issue by TheAllenChou** [Automattic/jetpack#14329]
#### Is your feature request related to a problem? Please describe.

There is a particular SEO website (https://www.xtraffic.plus/cn/) that keeps showing up in my stats. The referral link format is http://somedomain/blog/345323123. The exact link changes every time, so spamming it every time doesn't prevent future spam.

#### Describe the solution you'd like

I'm wondering if there's a way to identify that these links are all from the same spammer and have them filtered out once and for all.

**Comment by jeherve** [comment]
Could you contact us via this contact form and give us more details about your site there?
https://jetpack.com/contact-support/?rel=support

Once we have more details, we should be able to investigate and figure out a way to address this.

Thank you!
