### ISSUE TITLE
JP Manage Can't Distinguish between WordPress.com and WordPress.org Sites with Shared Domains

### ISSUE THREAD

**Issue by macmanx2** [Automattic/jetpack#1432]
When a WordPress.com and WordPress.org blog under the same account via JP Manage have the same domain, My Sites cannot distinguish between them.

For example, let's say that I had example.com mapped to a WordPress.com blog a year ago, and later moved example.com self-hosted with Jetpack and switched the WordPress.com blog to a Site Redirect upgrade. Now, My Sites has two instances of example.com. Clicking both bring up either the WordPress.com blog for both or the WordPress.org blog for both.

Which one it chooses to display seems to be random, but it's always the same for both, and it seems to occasionally switch when the browser's cache is cleared.

Disconnecting and deleting, then reinstalling and reconnecting Jetpack made no difference.

It do apologize for the lack of detail in this report, it's random enough for me to not be able to make much sense of it, but frustrating enough that I felt like I should report something. The issue was identified on a site which was mission-critical at the moment, so JP Manage was disabled and no further testing was done. At the moment, I do not have any test sites available which match the affected scenario.

**Comment by jeherve** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/6779
