### ISSUE TITLE
OpenTable block: add alignment support

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#14335]
It would be nice to allow site owners to align the OpenTable blocks using the alignment options offered by the block editor.

See https://github.com/Automattic/jetpack/pull/14220/files#r364242144

**Comment by iamtakashi** [comment]
My center-aligned OpenTable button isn't center-aligned in the editor. (It's in the center on the front-end).

I'll reopen this issue, but if I need to report this somewhere else, please let me know.

**Editor**
<img width="1366" alt="Screenshot 2020-02-03 at 09 43 14" src="https://user-images.githubusercontent.com/908665/73642677-086c1480-466a-11ea-8ba5-38b83bc3e322.png">

**Front of the site**
<img width="1366" alt="Screenshot 2020-02-03 at 09 43 21" src="https://user-images.githubusercontent.com/908665/73642710-1752c700-466a-11ea-8d15-66ade489463d.png">

**Comment by huguesvincent** [comment]
I reflected this on our board @iamtakashi no need to re-open one.

**Comment by iamtakashi** [comment]
OK, I'm closing this. Thank you!
