### ISSUE TITLE
Add Support For TikTok Embeds

### ISSUE THREAD

**Issue by donalirl** [Automattic/jetpack#14338]
#### Is your feature request related to a problem? Please describe.
TikTok is one of the fastest growing social media platforms in the world and is no longer just a passing trend. It now has 500 million active users (more than LinkedIn, Twitter, Pinterest, and Snapchat.) [Source](https://au.oberlo.com/blog/tiktok-statistics).

#### Describe the solution you'd like
Let's support TikTok embeds on WordPress.com sites. Here is an example TikTok video:

https://www.tiktok.com/@rybkatwinsofficial/video/6751398597490658565

The sharing options include an embed code, which seems to work in the Gutenberg edit screen:
<img width="930" alt="tiktok1" src="https://user-images.githubusercontent.com/30727666/72394458-72d81600-378a-11ea-90f8-0f1e2e6d0fd3.PNG">

but does not fully translate to the live site:
<img width="543" alt="tiktok2" src="https://user-images.githubusercontent.com/30727666/72394464-79ff2400-378a-11ea-920e-7db7b1add165.PNG">

Here's that test page:

https://wpdoc20170704.com/1676-2/

Can we support video embeds from TikTok?

#### Additional context
#12630535-hc / #2633089-zen

**Comment by jeherve** [comment]
This will be included in Gutenberg soon:
https://github.com/WordPress/gutenberg/pull/19345

It should then land in WordPress itself soon after that:
https://core.trac.wordpress.org/ticket/49083
