### ISSUE TITLE
OpenTable block: layout issues

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#14344]
This may be an issue with Core itself, but there are some layout issues with some of the components:

- Without Gutenberg installed:

![image](https://user-images.githubusercontent.com/426388/72427715-a61ba480-378c-11ea-9809-c52da65432c7.png)

- With Gutenberg installed:

![image](https://user-images.githubusercontent.com/426388/72428092-4e316d80-378d-11ea-8a06-4d49344e3397.png)

![image](https://user-images.githubusercontent.com/426388/72428105-52f62180-378d-11ea-96d1-22cb42e16df6.png)

It may be worth investigating to see what can be done about it.

**Comment by pablinos** [comment]
This is a hard one to debug. I've spent a long time on it this evening and I'm consistently seeing this problem with Gutenberg 7.2, on multiple sites and browsers. Other people have tested it and aren't able to replicate it.

I think there's a mixture of problems with Core and our styling, although if I remove all our editor CSS, I still have the issue.

- There's a height of 36px set on `components-button` which is causing the remove button to be too large. The actual height should be 24px, so we could fix this by setting it on the remove button as a patch in core
- The suggestions list is picking up list styling from the editor, which needs to be reset
- The weirdest one is where the label of the token is taller than the remove button. This doesn't happen with the `FormTokenField` when used in the sidebar, so I think it is picking up some editor styles again, but I've not had any luck in finding out what they are.

**Comment by glendaviesnz** [comment]
Looks like this issue is resolved in latest guteberg master by the likes of https://github.com/WordPress/gutenberg/commit/6e42279179026cad2785e2eb267f2ef168d7d3f8 - if I build gutenberg from master and install on JP site token sizing is fixed.

<img width="1020" alt="Screen Shot 2020-01-16 at 1 38 29 PM" src="https://user-images.githubusercontent.com/3629020/72483624-7fca3780-3866-11ea-8c7c-14c6253b1b41.png">
