### ISSUE TITLE
OpenTable block: update support links in placeholder

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#14347]
Those links are not up to date right now, they will need to be updated:
https://github.com/Automattic/jetpack/blob/12dceeb8bcc12b3f64501d3036e6cc6b9c761898/extensions/blocks/opentable/edit.js#L247-L250

**Comment by jeherve** [comment]
Related: #14459

**Comment by huguesvincent** [comment]
Here is the published link to be updated 
https://en.support.wordpress.com/wordpress-editor/blocks/opentable-block/

cc @scruffian

**Comment by jeherve** [comment]
And for the Jetpack side:
https://jetpack.com/support/jetpack-blocks/opentable-block/
