### ISSUE TITLE
Creating mobile-first stylesheets

### ISSUE THREAD

**Issue by galbaras** [Automattic/jetpack#14359]
The Jetpack stylesheet contains media queries with `max-width` in them, which implies desktop-first styling. It also means that desktop styles are being loaded on mobile phones unnecessarily.

This can be improved by including only mobile styles, which are typically much slimmer, in the main stylesheet and adding a wide-display/desktop stylesheet with a `min-width` media attribute, which will  only be loaded on wider displays.

This will help sites score better on mobile friendliness and improve SEO and mobile user experience.

**Comment by jeherve** [comment]
The Jetpack stylesheet is a concatenated version of all Jetpack features that rely on CSS enqueued on the site. 

Could you consequently take a closer look to find out what features you think should be modified to solve this, and open issues for each feature? I think this would prove more actionable and easier to address than a general issue like this one.

Thank you!

**Comment by galbaras** [comment]
Just to clarify, is this file created by Jetpack only for **active** features?

Honestly, modern styling should be every module's standard practice, and [a search for "(max-width:"](https://github.com/Automattic/jetpack/search?q=%22%28max-width%3A%22&unscoped_q=%22%28max-width%3A%22) should quickly reveal which parts need to change. Do I **really** have to start separate issues?

**Comment by jeherve** [comment]
> is this file created by Jetpack only for active features?

It concatenates all frontend CSS, whether a feature is active or not. To only include CSS from active features, we would have to either create a new concatenated CSS file for each possible combination of active / inactive features (that is not really realistic as you can imagine), or generate the CSS file on the fly which would not be good for performance.

> Honestly, modern styling should be every module's standard practice, and a search for "(max-width:" should quickly reveal which parts need to change. Do I really have to start separate issues?

I don't think that is something that we could reasonably change in one giant patch. Such patch would be really hard to test and review thoroughly. We find it's often more productive to make smaller iterations, as it's easier to discuss, review, and test changes like this. With one giant patch, we would run the risk of missing an edge case when testing.

I hope this clarifies things a bit.

**Comment by galbaras** [comment]
In the days of HTTP/2 and excellent caching plugins, is there a way to use the files separately?

This way, I can dequeue some of them and prioritise which of them need to change more easily via issues.

**Comment by jeherve** [comment]
> In the days of HTTP/2 and excellent caching plugins, is there a way to use the files separately?

Yes.
https://developer.jetpack.com/hooks/jetpack_implode_frontend_css/

**Comment by galbaras** [comment]
Awesome. This actually seems to include only the stylesheets of active modules, which is exactly what I wanted.

Thank you!
