### ISSUE TITLE
Instant Search: scroll on overlay scroll page underneath

### ISSUE THREAD

**Issue by keoshi** [Automattic/jetpack#14351]
#### Steps to reproduce the issue

1. Enter search term or click filter to trigger the search overlay.
1. Scroll through search results.

#### What I expected

- To only scroll through the overlay content.

#### What happened instead

- Notice how it's possible to scroll through the overlay, as well as the page underneath.

**Screenshots**

![search-scrolling-01](https://user-images.githubusercontent.com/390760/72448030-4635f580-37ae-11ea-8cad-290d335fa1e2.gif)

**Comment by keoshi** [comment]
Damn, the GIF above didn't capture the page below through the transparent overlay.

**Comment by bluefuton** [comment]
Fixed by #14478.
