### ISSUE TITLE
Calendly block: fails to load on Firefox due to regex error

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/jetpack#14376]
Firefox appears to take exception to the regular expressions used  in https://github.com/Automattic/jetpack/blob/master/extensions/blocks/calendly/utils.js#L1. The exception thrown causes the blocks not to load.

#### Steps to reproduce the issue

1. With jetpack beta blocks loaded add a calendly block in Chrome
2. Attempt to load the block in Firefox and you will see the below error:

<img width="1036" alt="Screen Shot 2020-01-17 at 2 06 02 PM" src="https://user-images.githubusercontent.com/3629020/72575808-87efa900-3932-11ea-81a2-87a7fc1f61d3.png">

If lines 1-32 of the utils file are commented out then the block loads in Firefox. At a glance it looks like these include lookbehinds which are not supported by firefox.

**Comment by arunsathiya** [comment]
I am not able to see the beta blocks on Safari either. Version 13.0.4 (15608.4.9.1.3) on macOS 10.15.2 - MacOS Catalina. Found when p58i-8tn-p2#comment-44412

**Comment by katiebethbrown** [comment]
Noting here that I can't see _any_ Jetpack blocks in Firefox when I'm proxied. If I unproxy the production JP blocks are visible.

So this seems to be blocked in some way related to proxied connections.

**Comment by arunsathiya** [comment]
Correction on my last comment: Same situation as @katiebethbrown. Cannot see any Jetpack blocks on Firefox *and* Safari.

**Comment by jeherve** [comment]
@katiebethbrown That's to be expected. When you're proxied, you'll be served a totally different bundle of blocks (including Beta blocks) on WordPress.com. The bug introduced with the new Calendly Beta block consequently impacts the whole bundle of blocks.

We're working on a fix in #14375.

**Comment by pablinos** [comment]
Fix is merged and deployed to wpcom, so you should be able to see the beta blocks in all browsers now.

**Comment by arunsathiya** [comment]
I confirm they are visible on Firefox and Safari now, thanks Jeremy and Paul!
