### ISSUE TITLE
Top Posts & Pages Widget: Retrieving Low Qaulity Img for Image List

### ISSUE THREAD

**Issue by jacoswan** [Automattic/jetpack#14380]
#### Steps to reproduce the issue

1. Add the Top Posts & Pages Widget to a sidebar area
2. In the "Display As" section, select "Image List"
3. Save and view on the front-end of the site
4. Notice the tiny, low-quality images displayed
5. Contrast to when Display As = Image Grid, images a clear and crisp

#### What I expected
Thumbs that a relatively clear and crisp, especially if source is high quality

#### What happened instead
Thumbs are overly compressed and low quality

**Screenshots**
Here's what it looks like when Display as = Image list

![image](https://user-images.githubusercontent.com/15178758/72606438-4279ae80-3927-11ea-9158-6910a3057900.png)

And here's what it looks like when Display as = Image Grid

![image](https://user-images.githubusercontent.com/15178758/72606525-6b01a880-3927-11ea-8995-13a6529f9214.png)

**Comment by jeherve** [comment]
Could you post a link to the site where you've seen this, so we can take a closer look?

Are there any customizations made to the widget on that site?

**Comment by jacoswan** [comment]
Apologies for the tardy reply, @jeherve . The affected site is here: https://sneaker-girl.com/

The site's admin is in Japanese, so a little hard to figure out, but a side-by-side comparison of the default widget from my test site, makes it look as if it's they're using the standard one: 

![image](https://user-images.githubusercontent.com/15178758/73017414-79b8f580-3e28-11ea-940c-68a23aee0054.png)

**Comment by jeherve** [comment]
They would be using the regular widget, but there are ways to customize the output of that widget. Here are some examples:
https://jetpack.com/2016/01/12/hooks-customize-top-posts-pages-widget/

Can you ask them if they have done anything of the sort?

It may also be worth trying to switch to another theme for a few minutes, to see if the problem could be linked to their theme applying CSS to that widget.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
