### ISSUE TITLE
Jetpack Autoloader: Conflicts can occur when the autoload files are used

### ISSUE THREAD

**Issue by superdav42** [Automattic/jetpack#14389]
#### Steps to reproduce the issue

1. Install 2 WordPress Plugins Both of which use Jetpack autoloader to avoid dependency version conflicts. Both require the popular guzzlehttp/guzzle library. 
2. If the first plugin loaded includes on older version of the guzzle V 6.3.3 
3. The second plugin loaded includes a newer version V 6.5.2
4. When either plugin tries to use the guzzle library they will get the error that the function `_idn_uri_convert()` is not defined. 
5. This is because guzzle's `functions.php` file is included as soon as the `autoload_packages.php` file is required by the first plugin which has an older version of guzzle installed and the [autoload files](https://github.com/guzzle/guzzle/blob/master/composer.json#L59) option is used by guzzle

#### What I expected
The latest version of guzzle's functions.php of all dependencies to be loaded. 

#### What happened instead
The first plugin loaded loads its version of the files rather than the latest version.

Jetpack autoloader should wait for all plugins to be loaded before including any files.

**Comment by enejb** [comment]
This is not a bug in the Jetpack Autoloader. It has more to do how the 2 different plugins calling the `guzzlehttp/guzzle` library the wrong way :(

How the autoloader know what file to load from where is by plugins telling the autoloader about the different libraries that are required the libraries.

In order for the autoloader to load the latest library the plugins need to wait for all the plugins to be loaded. 
To do this in WordPress, plugins need to call libraries at the earliest on  `plugins_loaded` hook.

Doing it before that results in a PHP error being thrown by the autoloader. See https://github.com/Automattic/jetpack/blob/master/packages/autoloader/src/autoload.php#L92

Hope that helps getting to the bottom of this.

**Comment by superdav42** [comment]
> In order for the autoloader to load the latest library the plugins need to wait for all the plugins to be loaded.
To do this in WordPress, plugins need to call libraries at the earliest on plugins_loaded hook.

You're right but even if both plugins wait for `plugins_loaded` before using guzzle it will still give this error. I can make two simple plugins if you need to be able to reproduce it.

**Comment by jeherve** [comment]
> I can make two simple plugins if you need to be able to reproduce it.

That'd be super helpful, thank you!

**Comment by superdav42** [comment]
Here's two simple plugin with reproduce the problem. Both plugins load autoload_packages.php immediately but do not use guzzle until after `plugins_loaded`
[jetpack-autoloader-failuer-example.zip](https://github.com/Automattic/jetpack/files/4087439/jetpack-autoloader-failuer-example.zip)

**Comment by kbrown9** [comment]
I like those plugins :smile:

Our Autoloader package only ensures that the latest versions of classes are loaded. As @superdav42 found, the files that just contain functions are loaded from whichever plugin is loaded first. You can see how the files are required [here](https://github.com/Automattic/jetpack/blob/master/packages/autoloader/src/AutoloadGenerator.php#L272).

In Jetpack, we also autoload a few files. For example, in the Connection package, we autoload  [legacy/load-ixr.php](https://github.com/Automattic/jetpack/blob/master/packages/connection/composer.json#L16).  All of the autoloaded files for version 8.1 can be found in [composer\autoload_files.php](https://plugins.trac.wordpress.org/browser/jetpack/tags/8.1/vendor/composer/autoload_files.php).

It looks like we should consider updating the Autoloader so that it requires the latest version of the autoloaded files.

**Comment by superdav42** [comment]
> It looks like we should consider updating the Autoloader so that it requires the latest version of the autoloaded files.

Yes, I believe we need to create an array for files just like we do for classes. Record the version with the file and only add files to the array if they are a newer version. Then after `plugins_loaded` require all the files that are registered.

**Comment by kbrown9** [comment]
I can’t think of any reason not to make this change. We'll need to set the priorities correctly for any `add_action('plugins_loaded'` calls in our autoloaded files, like this [one](https://github.com/Automattic/jetpack/blob/master/packages/compat/functions.php#L23) in `/compat/functions.php`.
