### ISSUE TITLE
Jetpack Related Posts Change Post Title Header

### ISSUE THREAD

**Issue by samunderwood** [Automattic/jetpack#14393]
#### Is your feature request related to a problem? Please describe.
Is there any way to change the heading structure for the related posts widget? I'd like the post titles to be H3's rather than H4's. I've already changed the 'Related Posts' header to a H2 rather than the default H3. 

#### Describe the solution you'd like
A code snippet that changes the post titles to H3s rather than H4s.

#### Additional context
![image](https://user-images.githubusercontent.com/15370634/72718328-a7bee100-3b6d-11ea-8448-0c89641ed379.png)

**Comment by jeherve** [comment]
You can use this filter to make the change:
https://developer.jetpack.com/hooks/jetpack_relatedposts_filter_post_heading/
