### ISSUE TITLE
Related Posts: Apostrophes in Titles Renders as HTML Entity Number

### ISSUE THREAD

**Issue by jacoswan** [Automattic/jetpack#14391]
#### Steps to reproduce the issue

**This only seems to happen on WordPress.com simple sites.**

1. Visit any single post page with a Jetpack Related Posts section at the bottom (Twenty Ninteteen, for instance, does this by default)
2. Edit one of the posts you see in that section, and add a normal apostrophe to the title ( ' )
3. Save the post you edited, and refresh the single post page where you have the Related Posts section open on
4. Notice how the apostrophe renders as `&#039;`

#### What I expected
I expected an apostrophe `'`

#### What happened instead
I got `&#039;` instead

**Screenshots**
Without an apostrophe `'`

![image](https://user-images.githubusercontent.com/15178758/72703055-40993080-3b5d-11ea-8fa7-7a25774690ec.png)

With an apostrophe `'`

![image](https://user-images.githubusercontent.com/15178758/72703089-54dd2d80-3b5d-11ea-9435-669ce5d5f6f7.png)

Issue reported in 2640192-zen, and I as able to recreate this on my own Premium plan with TwentyNineteen active, on Chrome and Firefox.

**Comment by jeherve** [comment]
I can't seem to be able to reproduce on my end:

<img width="513" alt="screenshot 2020-01-20 at 10 43 49" src="https://user-images.githubusercontent.com/426388/72715978-c45d1800-3b71-11ea-91ce-289ea6e843eb.png">
<img width="369" alt="screenshot 2020-01-20 at 10 41 59" src="https://user-images.githubusercontent.com/426388/72715979-c45d1800-3b71-11ea-9c71-969cd56ac08e.png">

Which apostrophe did you use in your posts?

`'` or `’`?

Could you also let me know if you've set a custom character encoding on your site and / or a custom language, other than utf-8 / en_US?

Thank you.

**Comment by jacoswan** [comment]
Images are from standard, Premium-plan sites. 
Both site are just the default English as per Manage » Settings » Language
I tested this with English (UK) too, results are the same for me. 
No special encoding was selected anywhere (that I'm aware of), sites are just created as per my default WPCOM profile, i.e. English. 
My keyboard is standard Apple Extended Keyboard, and my system language is set to English (UK). 
I used a `'` - the one that sits between `;` and `\`under the right-hand pinky (touch typing) 

This image is from a test Premium-plan site: https://jcopremium.wordpress.com/2019/08/11/ratings-blocks/, where the theme TwentyNineteen is active. Related Posts can be toggled via the Tools » Marketing » Traffic » Related posts setting, and looks like this:

![image](https://user-images.githubusercontent.com/15178758/73019673-ba1a7280-3e2c-11ea-96ef-3c972fef3171.png)

It's irrespective of "Show a thumbnail image where available" being on/off

![image](https://user-images.githubusercontent.com/15178758/73021775-ed5f0080-3e30-11ea-97b8-307bdbf8b0c4.png)


If I use a Related Posts Block in the editor instead, the block shows the entity in the editor, but renders fine on the front-end, and blocks the built-in Related Posts from showing:

![image](https://user-images.githubusercontent.com/15178758/73021555-7b86b700-3e30-11ea-9c06-08f8028323e1.png)

![image](https://user-images.githubusercontent.com/15178758/73021571-80e40180-3e30-11ea-8a60-43376be191b4.png)




These images are from a new test Premium-plan site: https://jcoprem2020.design.blog/2020/01/08/example-post/. Active theme is Maywood, which doesn't have Related Posts built in, so ignores the settings you can set in Tools » Marketing » Traffic, but you can use the Related Posts Block in the Editor. In Maywood, the block in the editor also shows the error, but renders fine on the front-end.

Block in the Editor: 

![image](https://user-images.githubusercontent.com/15178758/73019903-31500680-3e2d-11ea-8841-6d9e4b2e28cf.png)

Front-end:

![image](https://user-images.githubusercontent.com/15178758/73020002-6a887680-3e2d-11ea-875e-00c1006b01e5.png)

@jeherve

**Comment by kbrown9** [comment]
I can’t reproduce this on my Jetpack test site. However, I am seeing it on a wpcom site - see p9dueE-1aq-p2.

**Comment by samiff** [comment]
2668689-zen

Reproduced on wpcom simple & atomic sites.

**Comment by charliescheer** [comment]
Same problem in  2668839-zen

**Comment by tarunvijwani** [comment]
Same problem in 2669039- zen

**Comment by damiannep** [comment]
Possibly related to https://github.com/Automattic/wp-calypso/issues/38362

**Comment by jeherve** [comment]
@damiannep Good catch! Do you think you could try editing one of the posts with an apostrophe on one of the sites that show the issue, re-type the apostrophe and save the post, and see if that helps?

**Comment by jeherve** [comment]
Internal reference: pbAok1-dx-p2

**Comment by chaitanyamsv** [comment]
Another report in 18575571-hc

**Comment by arunsathiya** [comment]
2717300-zen

**Comment by khristiansnyder** [comment]
Another report in hc-13342089

Any posts with ' in the title get that rendered as` &#039 `in the related post list on single post pages. Theme is Hermes and is a simple site.

**Comment by iamgabrielma** [comment]
Another case here: 2718529-zen . Simple site and theme Publication.

**Comment by pauljacobson** [comment]
Also reported here: 18925743-hc

**Comment by darnelldibbles** [comment]
Also reported here: https://en.forums.wordpress.com/topic/apostrophe-transformed-to-on-on-the-same-topic-section/

**Comment by chaitanyamsv** [comment]
Another report in 19283860-hc

**Comment by gwensmithx** [comment]
Another report - 2783476zd / 19308983hc

Theme: Twenty Twenty
Site language is English but site interface language is:

![Screen Shot 2020-03-11 at 3 52 08 PM](https://user-images.githubusercontent.com/5779512/76467989-7a91f080-63b0-11ea-80c0-2753f4185da7.png)

**Comment by tijosh** [comment]
#19358377-hc 

Independent Publisher 2

**Comment by noahtallen** [comment]
This is resolved in the latest Gutenberg version on WordPress.com. Let us know if it continues happening!
