### ISSUE TITLE
Instant Search: allow output of unminified CSS in development

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#14405]
@jeherve suggested in https://github.com/Automattic/jetpack/pull/13138#discussion_r316195338:

> I think it would be nice to enqueue an unminified version of the CSS when `SCRIPT_DEBUG` is set to true. We usually do that in Jetpack, to help with debugging:
https://github.com/Automattic/jetpack/blob/b96f66a73398cd79dd460127fa07855ee4b85fcf/_inc/social-logos.php#L10

**Comment by jsnmoon** [comment]
This should be fixed with #17495!
