### ISSUE TITLE
Widgets: Gallery widget "choose images" button does not work while in the Customizer

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1440]
![screen shot 2014-12-17 at 8 52 30 pm](https://cloud.githubusercontent.com/assets/3220162/5483801/c29d4998-862e-11e4-87b1-30227bdcdd4b.png)
While in the Customizer, the `Choose Images` button doesn't work.  Works fine if under Appearance > Widgets.  Couldn't see any console errors.

WordPress 4.0.1, Jetpack 3.3

**Comment by jackdh** [comment]
Still not working for me on 4.1

**Comment by dereksmart** [comment]
@jackdh are you running 3.3 or master?  The fix has been merged, but has not been released yet.

**Comment by jackdh** [comment]
Yes i'm on 3.3. Sorry If I spoke out too soon.

**Comment by dereksmart** [comment]
No worries :) feel free to test it out, the fix is <a href="https://github.com/Automattic/jetpack/pull/1460/files">here</a>, or you can pull from master.
