### ISSUE TITLE
Instant Search: load more results on scroll

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#14406]
We currently handle paging by displaying a 'load more...' button. It'd be better if more results appeared magically on scroll instead.

@jeherve suggested in https://github.com/Automattic/jetpack/pull/13761#pullrequestreview-303856308:

> It would be nice if the infinite loader used a similar style to the one used for Infinite Scroll module, to keep things consistent.

**Comment by gibrown** [comment]
I'm not sure if the style is an issue anymore give that we now have an overlay, but we do need to hook up infinite scroll to work.

**Comment by bluefuton** [comment]
> I'm not sure if the style is an issue anymore give that we now have an overlay, but we do need to hook up infinite scroll to work.

Sounds good 👍 I've updated the title and description.

**Comment by jsnmoon** [comment]
Infinite scroll has been implemented in Instant Search.
