### ISSUE TITLE
Eventbrite/Pinterest Blocks: Extract resolveRedirect as shared utility function

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#14439]
As a follow up to #14075 (see also https://github.com/Automattic/jetpack/pull/14075#discussion_r369121237), we should extract the `resolveRedirect` and `resolveUrl` functions, respectively from the Pinterest and Eventbrite blocks, and move them into a single shared utility function.

**Comment by creativecoder** [comment]
Note that the [Calendly block now uses the resolve-redirect endpoint](https://github.com/Automattic/jetpack/pull/14814) as well.

**Comment by Copons** [comment]
In https://github.com/Automattic/jetpack/pull/14814 I've created a new `testEmbedUrl` that should make using `resolve-redirect` simpler.

See longer description: https://github.com/Automattic/jetpack/pull/14814#issuecomment-595493100

#14814 adds it to Calendly. I'll take care of Eventbrite and Pinterest once the function is merged.
