### ISSUE TITLE
Map Block: Update the Mapbox library to the latest version

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#14443]
Mapbox used to bill per tile load, but changed to map load with the v1.0.0 of their library.
We still use the [v0.54.1](https://github.com/Automattic/jetpack/blob/56165fe00ab035f3bd9daf1aa230927d5659663f/package.json#L135) and should definitely update (they are on [v1.6.1 right now](https://www.npmjs.com/package/mapbox-gl))

**Comment by jeherve** [comment]
Closing as duplicate of #14183
