### ISSUE TITLE
Protect: Incorrect IP being returned from jetpack_protect_get_ip (CloudFront instead of Client)

### ISSUE THREAD

**Issue by edavis** [Automattic/jetpack#14455]
Hello!

Problem popped up today with a client reporting major problems throughout the office of users being unable to login:

<img width="710" alt="Screen Shot 2020-01-23 at 9 50 24 PM" src="https://user-images.githubusercontent.com/622509/73048017-8dfef180-3e2c-11ea-9405-1478052d8cf4.png">

And here are the relevant settings from Site Health and Jetpack:

<img width="707" alt="Screen Shot 2020-01-23 at 10 09 03 PM" src="https://user-images.githubusercontent.com/622509/73048149-0665b280-3e2d-11ea-877b-7765d78b05af.png">

<img width="1071" alt="Screen Shot 2020-01-23 at 10 08 58 PM" src="https://user-images.githubusercontent.com/622509/73048156-08c80c80-3e2d-11ea-9d60-82c8da14da12.png">

(68.108.0.222 is my personal IP address and 130.176.4.68 appears to be a [CloudFront IP](http://d7uri8nf7uskq.cloudfront.net/tools/list-cloudfront-ips). It'll change nearly every refresh.)

The client first started hearing about staff login problems on Jan 20, 2020.

I am seeing an ongoing elevated level of failed logins. So my thinking is Jetpack has flagged the IP address of a nearby CloudFront point-of-presence and now most (but not all) legit users are unable to login.

As I understand it, the `trusted_ip_header` site option is a serialized response from api.bruteprotect.com. It's purpose is to inform `jetpack_protect_get_ip` how to obtain the client's IP address even with proxies, load balancers, and CDNs sitting between viewers and websites.

As I step through `jetpack_protect_get_ip` in modules/protect/shared-functions.php (Jetpack version 7.7.2), I believe this is what's happening:

* [segments is 0 when obtained from `trusted_ip_header`](https://github.com/Automattic/jetpack/blob/7.7.2/modules/protect/shared-functions.php#L165)
* [Because 0 is false-y, it gets set to 1](https://github.com/Automattic/jetpack/blob/7.7.2/modules/protect/shared-functions.php#L178-L180)
* The first `if` block is skipped because there are two IPs
* [The returned IP is `$ips[ 2 - 1 ]`](https://github.com/Automattic/jetpack/blob/7.7.2/modules/protect/shared-functions.php#L188-L189) which is the CloudFront IP as detailed [here](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#RequestCustomIPAddresses)

I guess my question is: What do I do here? Is there a configuration change I've missed? Does this need to be changed upstream? 

I've toyed around with a filter on `site_option_trusted_ip_header` to manually set segments to 2 but it feels kludgy. Am I even on the right track? Any help getting to the bottom of this would be much appreciated. Thanks in advance!

**Comment by jeherve** [comment]
> 68.108.0.222 is my personal IP address and 130.176.4.68 appears to be a CloudFront IP. 

That does seem to be the problem indeed.

> So my thinking is Jetpack has flagged the IP address of a nearby CloudFront point-of-presence

Yes, that is most likely what happened.

> What do I do here? Is there a configuration change I've missed? Does this need to be changed upstream?

If you can't make any changes to your server configuration to address this, could you reach out to us via this contact form?
https://jetpack.com/contact-support/?rel=support

Once we know your site URL, we should be able to change the way the Protect API picks up the IP to make sure we pick up the right one.

Thank you.

**Comment by edavis** [comment]
Thanks for the speedy response, @jeherve!

I am able to make any and all server configuration and/or code changes. Does that change how best to handle this?

**Comment by jeherve** [comment]
You could try to get rid of the CloudFront IP in your IP headers if you can, or overwrite it in your site's `wp-config.php` file.
Alternatively, on our end we can make sure the Protect API always looks at a specific IP in the list of IP headers provided by your site.
