### ISSUE TITLE
Slideshow & Tiled gallery blocks: Error uploading additional images

### ISSUE THREAD

**Issue by chriskmnds** [Automattic/jetpack#14457]
I notice an error when uploading a _second_ image to the `Jetpack -> Slideshow` block. This happens on WPCOM in both Gutenberg 7.2.0 (prod) and 7.3.0 (edge) to me.

#### Steps to reproduce the issue

1. Go to a block-editor post
2. Click on the block inserter and add a `Jetpack -> Slideshow` block
3. Click to upload an image (should work as expected)
4. Click to upload another image (should show error in console)

#### What I expected

Upload a second image to the slideshow.

#### What happened instead

Error.

**Screenshots**

![Kapture 2020-01-24 at 11 58 10](https://user-images.githubusercontent.com/1705499/73063537-a2cc9b00-3ea7-11ea-9fd0-920428d5bc22.gif)
```
Uncaught TypeError: Object(...) is not a function
    at t.addFiles (editor-beta.js?m=1579787284h&ver=wpcom:2)
    at editor-beta.js?m=1579787284h&ver=wpcom:2
    ...
```

CC @ockham

**Comment by jeherve** [comment]
This can also be reproduced in current Jetpack stable without the Gutenberg plugin. 

As a workaround, I was able to upload a new image using the Edit pencil icon for the block.

**Comment by jeherve** [comment]
This also impacts the Tiled Gallery block as reported in #14508 by @bindlegirl (good catch!).

2664014-zen

**Comment by kriskarkoski** [comment]
Drag and drop uploading also appears to be broken I suspect by the same issue. It opens the image in the same tab instead of uploading.

**Comment by tijosh** [comment]
Another report of this in #18016187-hc

**Comment by simison** [comment]
Looking at [core gallery](https://github.com/WordPress/gutenberg/tree/2a57efe9e73674b0d562b225812c7b3120cfb8ea/packages/block-library/src/gallery) block might reveal what changes are needed. Some of the tiled gallery is modeled after that block so copying the file upload methods over might be good.

@pablinos mentioned on Slack that he could look into this at some point (p1581493933212600-slack-explorers).
