### ISSUE TITLE
Eventbrite block: Improve default UI

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#14462]
This issue tracks two different enhancements:
- [x] ~Provide a default text (e.g. "Register") for the block's Button mode.
Right now, a missing text for the button could go unnoticed in the editor where it has a placeholder text, but looks weird on the front end.~ #14585

- [x] ~Return a link to the event on the front end.
When reading the post in contexts that don't have the Eventbrite block (mail, feeds, with Jetpack deactivated) the block would still show something useful.~ #14510

- [x] ~Add default styling to the Embed button in the placeholder so that it has a border like all other blocks.~ #14588

**Comment by creativecoder** [comment]
>  Return a link to the event on the front end.

Was resolved by https://github.com/Automattic/jetpack/pull/14510
