### ISSUE TITLE
On first view only smiley face shows although "hide the stats smiley face" is checked

### ISSUE THREAD

**Issue by mshioda** [Automattic/jetpack#14483]
Smiley faces show below every oEmbed cards on first view although I checked "Hide the stats smiley face image" in Jetpack settings page.
On reload they are hidden correctly.

#### Steps to reproduce the issue

1. show site with new incognito window
2. on first view smiley faces are shown below each oEmbed card
3. reload the page
4. no smiley faces are shown

**Screenshots**
On first view
![first-time](https://user-images.githubusercontent.com/2947838/73151056-dceaa680-410c-11ea-9cab-6c4d02e02fef.png)

On reload
![reloaded](https://user-images.githubusercontent.com/2947838/73151074-f55ac100-410c-11ea-9661-50aca3a9859d.png)

**Comment by jeherve** [comment]
Could you post a link to a page where you've added such an embed, so I can take a closer look?

Thank you.

**Comment by mshioda** [comment]
Yes.  Please access to the following link:
https://blog.8card.net/2020/01/24/hr-vol2/

**Comment by jeherve** [comment]
Thank you.

Could you try adding the following code to [a functionality plugin on your site](https://jetpack.com/support/adding-code-snippets/), and let me know if it helps?

```php
add_action( 'embed_head', 'stats_hide_smile_css' );
```

**Comment by mshioda** [comment]
The smiley face images have been hidden correctly even when the image tags remain in the HTML code!  It seems good.

Thank you for your help.

**Comment by jeherve** [comment]
Thanks for letting me know. We'll see about getting this fix included in a future release of Jetpack.
