### ISSUE TITLE
jetpack_modules_loaded now runs multiple times

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#14499]
Prior to the 8.2 beta, `jetpack_modules_loaded` fired once, so custom code that expects to only fire once all modules have been loaded can error out (e.g. defining a class or requiring a file).

While this behavior likely should be corrected in the custom code, we should ensure we are loading only once OR if we must run multiple times, we go into it aware of the potential breakage.

Marking as a blocker for consideration before 8.2 final.

Psuedo-example code to test: 

```
add_action('jetpack_modules_loaded','special_one_time');
function special_one_time() {
​
	// If tiled galleries are disabled, this class is undefined.
	if ( ! class_exists('Jetpack_Tiled_Gallery') ) return;
​
	class extra_Jetpack_Tiled_Gallery extends Jetpack_Tiled_Gallery { }
}
```

Original report: p1580222270136600-slack-jetpack-crew

**Comment by jeherve** [comment]
Related: 1146297891914257-as-1151187353457655
