### ISSUE TITLE
Shortcodes: VR shortcode embeds don't work if image file name contains non-Latin characters

### ISSUE THREAD

**Issue by KokkieH** [Automattic/jetpack#14495]
#### Steps to reproduce the issue

1. Take a 360- or panorama-image
2. Save two versions of the image - one version using only regular alpha-numeric characters for the filename, and one version using a non-Latin script (reporter is using Thai characters and I confirmed the bug using Hebrew)
3. Create a new post, and insert both versions of the image using the `[vr]` shortcode, as explained at https://en.support.wordpress.com/embedding-360-photos-and-virtual-reality-vr-content/, using either the classic or the block editor
4. Publish and view the post.

#### What I expected

To see the embedded viewer allowing me to view the full image.

#### What happened instead
The image with the non-Latin characters in the file name simply displays `Please supply a valid URL parameter`

**Screenshots**
![VR_photo_–_My_Core_Sandbox](https://user-images.githubusercontent.com/11873759/73255986-d0785380-41c9-11ea-8e27-7615e49fe7b1.png)

Reported in https://wordpress.org/support/topic/wordpress-jetpack-vr-shortcode-not-support-the-thais-character-alphabet/

I've also confirmed this is broken on WordPress.com simple sites, in both block and classic editors.

Test site running WordPress v5.3.2, Jetpack v8.1.1, Gutenberg v7.3 and Classic Editor v1.5

**Comment by jeherve** [comment]
Good catch. This is definitely worth fixing. However, I think it's also good practice to avoid using special characters in file names in general. Plugins like this can help:
https://wordpress.org/plugins/clean-image-filenames/

**Comment by KokkieH** [comment]
Thanks, @jeherve. I'll suggest that to them.

**Comment by GenCharisma** [comment]
Thank you, I'm looking forward to it

**Comment by GenCharisma** [comment]
After research a bit(and more knowledge than the last time), I discovered that Jetpack is working just fine. **It's nothing wrong with Jetpack, It's work as it should be**

But the problem is the "https://vr.me.sh/" which do the VR's thing does not accept non-latin character.
Example :
Work => https://vr.me.sh/view/?view=360&url=https://www.website.com/englishlanguage.jpg
Not Work => https://vr.me.sh/view/?view=360&url=https://www.website.com/ภาษาไทย.jpg

**Comment by jeherve** [comment]
Thanks for following up with us on this. I've forwarded the info to the team working on me.sh.
