### ISSUE TITLE
Eventbrite Block: No error message with invalid urls

### ISSUE THREAD

**Issue by creativecoder** [Automattic/jetpack#14507]
#### Steps to reproduce the issue

1. Add the Eventbrite block in a post or page
2. For the event url, use something that won't embed, like `https://eventbrite.com`

#### What I expected

An error message and option to "Convert block to link" below the event url

#### What happened instead

No error message

**Screenshots**

![Eventbrite block no error](https://user-images.githubusercontent.com/1699996/88722331-abb75700-d0ec-11ea-9d42-cc91a631739e.gif)

**Comment by creativecoder** [comment]
Looks like the layout issue is fixed in Gutenberg, but not yet released https://github.com/WordPress/gutenberg/pull/19673

We still need to add the outline to the Embed and Convert block to link buttons here, though.

**Comment by jeherve** [comment]
Since this also impacts core embeds, I would be tempted to wait until the fix makes it to a stable version of Gutenberg soon.

> We still need to add the outline to the Embed and Convert block to link buttons here, though.

Does this mean switching to a different button style (secondary)?

**Comment by creativecoder** [comment]
Looks like there's now _no_ error message showing for the Eventbrite block with invalid urls. I've updated the issue title and description.

**Comment by ivan-ottinger** [comment]
I have tested the issue and it looks like that the `setErrorNotice()`:

https://github.com/Automattic/jetpack/blob/8f30c2c17148ede399d48954e8859e177f9d32ef/projects/plugins/jetpack/extensions/blocks/eventbrite/edit.js#L76-L89

is called only when the `testEmbedUrl` promise fails:

https://github.com/Automattic/jetpack/blob/8f30c2c17148ede399d48954e8859e177f9d32ef/projects/plugins/jetpack/extensions/blocks/eventbrite/edit.js#L67-L70

But this depends on the `responseStatusCode` (in `test-embed-url.js`):

https://github.com/Automattic/jetpack/blob/8f30c2c17148ede399d48954e8859e177f9d32ef/projects/plugins/jetpack/extensions/shared/test-embed-url.js#L28-L44

and therefore only "really invalid" URLs, e.g. `https://www.testtestevenbrite.com/` will display the error message. All other URLs, e.g. `https://google.com` won't return any error message.

**Comment by alshakero** [comment]
PR ready https://github.com/Automattic/jetpack/pull/21247
