### ISSUE TITLE
Slideshow Block: Fade transition doesn't work

### ISSUE THREAD

**Issue by mrleemon** [Automattic/jetpack#14525]
1. Add a Slideshow block in a page and add some images to it
2. Select the "Fade" transition
3. Without saving or leaving the editor, click the Next arrow in the Slideshow block

#### What I expected
The next image in the slideshow should appear

#### What happened instead
All images disappear

**Screenshots**
![fade-transition](https://user-images.githubusercontent.com/2060659/73452962-4ec02b80-436b-11ea-81be-43e278e76822.jpg)

I'm using Jetpack 8.1.1 and WordPress 5.3.2
Tried this with Firefox 72 and Chrome 79

**Comment by jeherve** [comment]
I can't seem to reproduce on my end. 

Do you see any JavaScript errors in your browser console?
https://wordpress.org/support/article/using-your-browser-to-diagnose-javascript-errors/#step-3-diagnosis

Thank you!

**Comment by mrleemon** [comment]
The issue only occurs just after inserting the Slideshow block with some images IN THE EDIT SCREEN (not the frontend). Once I save the post/page and reload it, the fade transition works.

**Comment by jeherve** [comment]
> Once I save the post/page and reload it, the fade transition works.

Ah, nice catch. That is where I messed up. I'll update the original issue description to mention that.

**Comment by mrleemon** [comment]
Thanks!
