### ISSUE TITLE
Slideshow block: slider doesn't auto-advance on Win 10 computers with animations disabled

### ISSUE THREAD

**Issue by KokkieH** [Automattic/jetpack#14523]
#### Steps to reproduce the issue

1. Create a post with a slideshow block and add some images to it.
2. On a Windows 10 computer, go to Settings ->Display, and under "Simplify and personalize Windows" toggle the "Show animations in Windows" to off.
3. View the post using any browser

#### What I expected

For the slider to advance automatically.

#### What happened instead
The slider doesn't advance, and can only be advanced using the arrow buttons, or the controls below the slider.

Upon toggling the Show animations setting to on and refreshing the page, the slider auto-advances normally.

Reported by users in https://wordpress.org/support/topic/jetpack-slideshow-not-advancing/ and https://wordpress.org/support/topic/slideshow-block-autoplay/

The user in the second thread managed to track the issue down to the line:

`.matchMedia("(prefers-reduced-motion: reduce)")`

Modifing that line as follows allow the slider to work:

`.matchMedia("(prefers-reduced-motion: no-preference)")`

Was this added to the block with the intent of respecting this Windows setting in this way, or is this something we might be able to fix? 

I found one issue mentioning `.matchMedia`, #8309, where it was added to improve accessibility regarding the now-deprecated holiday snow feature, so adding the accessibility tag here as well.

**Comment by jeherve** [comment]
This seems like the expected behaviour. If I were to disable animations in my OS settings, I would expect the slider not to move on its own. I think it's a useful feature for folks who may experience discomfort with moving images.

Closing as won't fix.

**Comment by KokkieH** [comment]
Thanks for checking. I'll let the user know.
