### ISSUE TITLE
Form Block: Add reCAPTCHA to the form block

### ISSUE THREAD

**Issue by damiannep** [Automattic/jetpack#14526]
#### Is your feature request related to a problem? Please describe.

Some spam submissions through the form block are not caught by Akismet because they look like they are from legitimate emails but they are clearly Spam.

#### Describe the solution you'd like

Enable reCAPTCHA in the form block to decrease this SPAM.

#### Additional context

This request is in response to customer feedback e.g. 5130224-hc

**Comment by jeherve** [comment]
That's not something we'll add to the contact form, for the reasons outlined here:
https://github.com/Automattic/jetpack/pull/9389#issuecomment-467976310

You can, however, use plugins to add the feature. Here is an example:
https://github.com/DevriX/jetpack-recaptcha

**Comment by damiannep** [comment]
Thanks for the link and note @jeherve. The user in the referenced chat didn't have an option to install plugins.
