### ISSUE TITLE
Contact Form Block: Allow form fields in email subject line

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#14521]
#### Is your feature request related to a problem? Please describe.

* When receiving multiple email notifications for the same contact form, some email providers (eg Gmail) group emails with the same subject line. This can disrupt the workflow of users that need each form response email notification to have a unique subject line.
* Note, Gmail does provide a setting for the email grouping ([conversation view](https://support.google.com/mail/answer/5900)), but unique subjects lines are still desired.

#### Describe the solution you'd like

* Allow some of the form fields to be used in the email notification subject line.
* The [CoBlocks](https://github.com/godaddy-wordpress/coblocks) form block is an example of this:

![Screen Shot on 2020-01-29 at 17:35:46](https://user-images.githubusercontent.com/15803018/73410014-33e3ad80-42be-11ea-814a-b554229550d2.png)

#### Additional context
#user-report 1748296-hc

**Comment by jeherve** [comment]
That's already possible thanks to form tokens. 

Here is an example:

![image](https://user-images.githubusercontent.com/426388/73436113-2c69e600-434a-11ea-8871-59b6664f20e2.png)
![image](https://user-images.githubusercontent.com/426388/73436122-3390f400-434a-11ea-85ac-01cc1d757926.png)

And here is how the email subject line looks like:
![image](https://user-images.githubusercontent.com/426388/73436054-13613500-434a-11ea-8550-71385c3781b5.png)

You can read more about it here:
https://jetpack.com/support/contact-form/#customization

> Jetpack allows you to customize the fields you add to the contact form, and also offers an option to change the subject of the email sent to you after each form submission.
> 
> You can add tokens to the subject field, like {city}, and Jetpack will replace the token with the value of the “City” form field (case insensitive, just make sure that the words match).

**Comment by asafm7** [comment]
@jeherve I was also looking for this functionality.

I found the page you referred to before finding this thread. It seems the part you quoted isn't a part of the page anymore though.  There is no reference to the tokens.

It might be a good idea to re-introduce the information to the page.

**Comment by jeherve** [comment]
@asafm7 Tha's a good point. I've added that section back to the support document:
https://jetpack.com/support/jetpack-blocks/contact-form/#customize-the-subject-field-in-notification-emails
