### ISSUE TITLE
Publicize: modal window appears at the end of the HTML Content

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1453]
After creating a new Publicize connection, you're redirected back to your site and a modal window appears with some additional Publicize options.

Unfortunately, that modal window appears at the bottom of the HTML content, with no indication whatsoever for users who may not see the modal because they're using a screen reader.

It would be nice to include a message at the top of the page to direct screen readers to the modal window.

Reported here:
https://wordpress.org/support/topic/how-to-use-publisher-with-two-accounts-and-two-different-profiles?replies=3

**Comment by chrisdc** [comment]
As I understand the code the modal window is being created in javascript (modules/publicize/assets/publicize.js), so would there be any disadvantages to simply focusing the window when it's created, and moving focus back to the top of the page when it's closed?

**Comment by jeherve** [comment]
Closing as this is tracked internally, and since the Publicize interface will soon be available in the Jetpack Dashboard.
