### ISSUE TITLE
Blocks: It's not possible to rearrange images in a tiled gallery block

### ISSUE THREAD

**Issue by apeatling** [Automattic/jetpack#14546]
I love our tiled gallery block for two reasons, it's visually more interesting, and it will horizontally and vertically align all your images. It makes it easy to make any number of images a full section of the page.

However there are two really sore points that make it frustrating:

1. I can't rearrange images
2. I can't randomize the ordering and sizing of the images

Number two is frustrating because it's deciding which images are big, and which are small in order for them to fit. However, there are often multiple ways this can be done. For example in this view:

<img width="946" alt="Screen Shot 2019-10-25 at 2 08 20 PM" src="https://user-images.githubusercontent.com/1464705/67605439-3bca0980-f733-11e9-87a5-3914ffb6eb42.png">

I would much prefer the image of the person at the computer in the bottom right to be in the bigger section the photos on the wall currently occupies. There is no way for me to do this.

The two ways this can be fixed are:

1. Allow me to drag and drop images into new locations (limiting the drop spots to images that are the same dimensions)
2. Have a button that regenerates the gallery and updates the positions of the image. That way I can keep clicking the button until I get something that looks good.

I think number 2 might be the easiest solution, but having both number 1 and number 2 would be ideal.

**Comment by tbradsha** [comment]
18675881-hc:
>I was just working to change the arrangement of the tiles in my photo block in a certain window, and now I can't find it again. Help!

Turns out reordering a tiled gallery block doesn't work in Calypso, but it does work in WP Admin.
