### ISSUE TITLE
SSO JITM appears in Calypso Sidebar

### ISSUE THREAD

**Issue by gwwar** [Automattic/jetpack#14547]
It looks like an SSO JITM is showing up in the sidebar, probably unintentionally. This was originally found and reported by @rickybanister 

I believe this one is registered at https://github.com/Automattic/jetpack/blob/e17a5c667d9d7aaf5527e9c626911d00489aa073/modules/sso.php#L1113

<img width="1212" alt="Screen Shot 2020-01-31 at 2 16 51 PM" src="https://user-images.githubusercontent.com/1270189/73578516-b7270f80-4434-11ea-875e-fa2340f59413.png">

But appears in two API responses on the `calypso:stats-day:admin-notices` and `calypso:stats:sidebar_notice`. For the amount of content here the API should not be returning this.

<img width="1218" alt="Screen Shot 2020-01-31 at 2 18 31 PM" src="https://user-images.githubusercontent.com/1270189/73578735-3583b180-4435-11ea-88e5-74a4e6a585d0.png">

<img width="1224" alt="Screen Shot 2020-01-31 at 2 17 26 PM" src="https://user-images.githubusercontent.com/1270189/73579291-dde64580-4436-11ea-9261-98a4a82ccad4.png">

We do have an A/B test running for sidebar banners, but this is unrelated since I see the same behavior in Calypso master at `9820c2fa70292fda1db438deca943ce1b29f0faa` before the PR was merged.

@Automattic/manage is happy to help review any PRs if folks have a fix.

#### To Reproduce This:
- Create a test site ([this branch](https://github.com/Automattic/jetpack/pull/14543) makes it easier for the SSO JITM to display), https://jurassic.ninja/create/?jetpack-beta&branch=try/sso-jitm
- Setup Jetpack and Connect to WordPress.com
- Turn on the following setting in Jetpack Settings:
<img width="1025" alt="Screen Shot 2020-01-31 at 1 43 35 PM" src="https://user-images.githubusercontent.com/1270189/73578814-754a9900-4435-11ea-8855-e6ba7e9990d7.png">

- Visit WordPress.com/stats/day/siteslug

Expected: Banner appears in Stats
Actual: Banner appears in Stats and in Sidebar

**Comment by gwwar** [comment]
cc @jeherve we're also happy to help fix this one if folks guide us a bit in code. I suspect we have a regex here that's too inclusive.

**Comment by jeherve** [comment]
Nice catch!

This one is a bit of a custom JITM, it doesn't work the same way as the other messages. We force-inject it to the list of messages you should get when you first log in to your site after enabling SSO.

That makes fixing things a bit more complicated. To be honest I don't think it makes sense for this message to appear at all in Calypso.

Do you happen to know if there would be a way to remove a specific JITM right in Calypso?

**Comment by gwwar** [comment]
@jeherve Is there no clean way of modifying the API response from `v4/jitm`?

One sanity check might be that anything added to the `calypso:*:sidebar_notice` path should use a template of sidebar. Depending on how difficult it is, we can try to do this this on the server (preferable) or ignore this in Calypso on the slot.

**Comment by jeherve** [comment]
> Is there no clean way of modifying the API response from v4/jitm?

Yes, that would seem to be the best way. #14622 should take care of that, hopefully.

**Comment by gwwar** [comment]
Thanks @jeherve I've added 14622 to our review list!

**Comment by gwwar** [comment]
cc @rickybanister, thanks to @jeherve this one should be fixed in the 8.3 release
