### ISSUE TITLE
Map Block: UI for map themes

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/jetpack#14559]
@shaunandrews has pointed out the UI for the map themes would probably better to follow the block style pattern. https://github.com/Automattic/Dotcom-roadmap/issues/74#issuecomment-574770538

+1!

**Comment by jeherve** [comment]
As pointed out in p58i-8JL-p2, it may also be worth making those styles available from the block toolbar:

> bring more tools to the toolbar or contextually to the block. For example, the different themes should be accessible from the toolbar.

**Comment by pento** [comment]
> it may also be worth making those styles available from the block toolbar

This is done automagically in Automattic/jetpack#14852, by switching to using the block styles API.
