### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Qinweixiang1** [Automattic/jetpack#14554]
### ”Write posts or pages in plain-text Markdown syntax“ This feature has been disabled by a site administrator 

How do I enable feature ？？？

**Comment by Qinweixiang1** [comment]
**Jetpack -> settings ->Discussion**

“Enable Markdown use for comments.”
can't click on

help me

email：563460171@qq.com

**Comment by jeherve** [comment]
If you need help with the Jetpack plugin, could you please contact our support team here?
https://jetpack.com/contact-support/?rel=support

Thank you.
