### ISSUE TITLE
Calendly: Inline embed height is set for one style

### ISSUE THREAD

**Issue by pablinos** [Automattic/jetpack#14566]
#### Steps to reproduce the issue

1. Use a Jetpack site with beta blocks enabled
2. Insert a Calendly block with a user URL e.g. https://calendly.com/paul-bunkham
3. Insert a block after the Calendly block

#### What I expected

The Calendly block should fit the size of its content

#### What happened instead

The block renders much taller than required due to the CSS `height` being set for the calendar view. 

<img width="640" alt="image" src="https://user-images.githubusercontent.com/96462/73742667-d67bb080-4744-11ea-8ad4-e910d926acb6.png">

#### Notes

This isn't straightforward to fix. We could set the height differently based on this other type of embed, but we have no way to know how many meeting types are active. The only solutions I can think of currently:

- Prevent these user-level embeds
- Fix the height embed to an arbitrary number of meeting types
- Use some JavaScript to resize the iframe, once the content has loaded, or when it changes.

The last option is the best UX but is also ~~the most brittle and time-consuming~~ only possible with help on the Calendly side..

**Comment by pablinos** [comment]
Looking at [the answer to this question](https://help.calendly.com/hc/en-us/articles/360019861794-Common-embed-questions#3), I think we may have to live with this for now, unless Calendly start sending `postmessage` events as the content size in the iframe changes.

**Comment by jeherve** [comment]
Also in #15266.

**Comment by jeherve** [comment]
Also in #15358.

**Comment by gravityrail** [comment]
The best fix I found so far was using CSS that is tuned to match Calendly's _current_ responsive styles and approximate typical size of an event description.

These settings worked for me:

```
#calendly-block-1 {
	margin-top: 0;
	height: 900px;
}

@media only screen and (min-width: 780px) {
	#calendly-block-1 {
		height: 1150px;
	}
}
```

You could ask the user to set the "desktop" and "mobile" iframe heights in the UI, theoretically. The hosting page can't see if it's scrolling, but the user can.

A longer term fix for this would be to do our own rendering based on output from [Calendly's API](https://developer.calendly.com/) (if it supports this use case)

**Comment by davemart-in** [comment]
I don't see any straightforward solutions to the problem outlined by @pablinos. I'm going to close this out. Happy to reopen it if anyone can think of a reasonable solution.

**Comment by sophiegyo** [comment]
User report in: 7568163-zen

I tested some quick-fix CSS to set the height of the block to 888px and that seemed to manage OK for desktop; it still looks a little cramped on mobile but that's largely due to the iframe contents IMO.
