### ISSUE TITLE
Calendly Block - Issue with pasting Calendly account level URL - Block stuck

### ISSUE THREAD

**Issue by huguesvincent** [Automattic/jetpack#14581]
#### Steps to reproduce the issue

1. Go to the editor
2. Add Calendly
3. Copy your Calendly account level URL 
(in our demo account that is https://calendly.com/wordpresscom not one of the specific calendar you have set up like https://calendly.com/wordpresscom/jetpack-block-example

#### What I expected
I should be able to select a calendar which would then display availability. 

#### What happened instead
The block is stuck and doesn't allow me to pick one of the calendar available

**Screenshots**

[Calendly bug.zip](https://github.com/Automattic/jetpack/files/4161083/Calendly.bug.zip)

Tested on WordPress.com

**Comment by pablinos** [comment]
This is confusing but expected behaviour. In the editor you just see a preview of the block and it's set to the account level view. To get it to display that appointment type you would need to put in the https://calendly.com/wordpresscom/jetpack-block-example URL.

**Comment by huguesvincent** [comment]
Thanks for the clarification. I hadn't tested that behavior so far

**Comment by pablinos** [comment]
I'm not sure what the solution would be for this.

* Is there a way to show that you can't interact with the preview of the component?
* Can we make it easy to change the embed URL?
* We should probably add a line or two about this to the support doc
* I don't think there is currently, but could we got a list of appointment types based on the user level URL and allow that to be selected/changed in the editor?

**Comment by huguesvincent** [comment]
> I don't think there is currently, but could we got a list of appointment types based on the user level URL and allow that to be selected/changed in the editor?
Not sure exactly what you mean there. 

> We should probably add a line or two about this to the support doc
I'll take care of that.

**Comment by pablinos** [comment]
> > I don't think there is currently, but could we got a list of appointment types based on the user level URL and allow that to be selected/changed in the editor?
> 
> Not sure exactly what you mean there.

Yeah, that's not the easiest thing to describe. I was talking about the list of appointments you get presented with when visiting the user level URL:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/96462/75338779-31f21780-5887-11ea-93f2-a0bcd4cbbbff.png">

Admittedly there's only one choice here! If we could use some API call to get this list then we could add a dropdown or other setting that would allow the user to pick the one they wanted. Maybe we could use block variations to allow people to pick whether they want the user level view or a particular appointment type to be displayed.

**Comment by scruffian** [comment]
I think this is the expected behaviour, so closing as a wontfix.
