### ISSUE TITLE
(3P) Update block categorization in CoBlocks

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#14598]
As a writer, I'd like blocks to be categorized appropriately, so they are easier for me to find.

#### Acceptance Criteria:
- [ ] Blocks make use of four new categories: Blog, Earn, Marketing, and Social.
- [ ] Blocks are part of the assigned category.
- [ ] Blocks are not within a "collection" category (meaning "Jetpack" or "Coblocks").

#### Resources:
* [Spreadsheet with Blocks and their new categories](https://docs.google.com/spreadsheets/d/1Oua0oDUhGJJtabatoBS3XBzZ6K3oUiB5-kSdWl00M-I/edit#gid=0).

#### Implementation Notes

- [ ] Confirm it's ok to register the same Category twice without causing an error. This is in case Core creates a new Category with the same as ours. (Also can we check for cat exists before creating?).

#### How to Demo:
* In the block selector, identify two or three blocks that found their new home in a core-registered or custom category.
* Show how blocks not make use of "collection" categories anymore.

More discussion: p58i-8yl-p2.

**Comment by obenland** [comment]
@lessbloat We was wondering if there's a list of the blocks this should apply to, that ideally would also include the category and collection they should fall into?

**Comment by davemart-in** [comment]
I outlined my proposal for 4 collections [here](https://docs.google.com/spreadsheets/d/1Oua0oDUhGJJtabatoBS3XBzZ6K3oUiB5-kSdWl00M-I/edit#gid=0). Let's hold off on category changes until [this core PR](https://href.li/?https://github.com/WordPress/gutenberg/pull/19279) is merged.

**Comment by obenland** [comment]
The issue description was updated and reflects the latest status of this task

**Comment by marekhrabe** [comment]
Let's make sure newly registered categories (like "Layout") would not cause a fatal error if other plugin or core decides to register the same name.

**Comment by retrofox** [comment]
> Let's make sure newly registered categories (like "Layout") would not cause a fatal error if other plugin or core decides to register the same name.

Adding a new category with the same slug produces a funny visual bug. Basically, both sections in the _according_ will act as a single one. it means if you open one of them, both will be open. Same closing the accordion.
Also, both section containers are filled with the same blocks, which makes sense because the category slug is for both sections.

<img src="https://user-images.githubusercontent.com/77539/74761115-3c465d00-525a-11ea-922a-d7ce3661334b.gif" width="500px" />

**Comment by retrofox** [comment]
in https://github.com/Automattic/jetpack/pull/14721 I've handled the categories straight in Jetpack. We agreed that it'd be better to handle them in the respective repositories. For instance, for coblocks we should tackle them at https://github.com/Automattic/coblocks-builder, and so on with other blocks.

**Comment by frontdevde** [comment]
> Let's hold off on category changes until this core PR is merged.

https://github.com/WordPress/gutenberg/pull/19279 still hasn't been merged and it looks like the discussion in core is stalling.

**Comment by obenland** [comment]
Jetpack side is done, only CoBlocks category update remains
