### ISSUE TITLE
Emoji integration

### ISSUE THREAD

**Issue by sinofanger** [Automattic/jetpack#1459]
One of the most helpful modules in Jetpack would be the new twitter emojis, in the 3.4 version, which can enable the use of these emojis in both posts and comments. 

Also it would be helpful to load the emoji set from maxcdn ( https://www.maxcdn.com/blog/emojis-ftw/) or WordPress.com servers so as to minimize load on the self hosted blog.

http://en.blog.wordpress.com/2014/11/06/emoji-everywhere/

**Comment by jeherve** [comment]
While we could add support for Emoji in Jetpack, WordPress itself will need to be improved to support such characters first. You can follow progress in Core here:
https://core.trac.wordpress.org/ticket/21212

**Comment by jeherve** [comment]
Emojis are now part of WordPress core, as of [4.2](https://wordpress.org/news/2015/04/powell/).
