### ISSUE TITLE
Instant Search: Re-hide Mobile Filter Dropdown

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#14606]
After the user applies a filter or changes the sorting, we should hide the dropdown and immediately show the results. The user should not have to do another tap to get out of the filters and see the new results.

**Comment by jsnmoon** [comment]
I'll pick up this task. @keoshi can you confirm that this UX is desirable?

**Comment by keoshi** [comment]
Yep, I believe so. Greg and I talked about this and the reason behind it is that:


1. By displaying the results we can more easily highlight the fact that the search/filtering happens instantly.
2. Search results should be good enough that you find what you’re looking for with a single filter or ideally none at all.
3. It’s probably not that common that people refine filter terms/options more than once or twice, so the fact we’re hiding the popover isn’t too concerning.

I’d still like some data on the latter, but we agreed to keep a close eye on the various tracks we’re recording to see if this is something we should change in the future.
