### ISSUE TITLE
Instant Search: Background request to API before the click happens

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#14604]
When a user starts to get near a filter link we should optimistically fire off the request before they click so that we can hide more of the latency.

Basically can we act a bit more optimistically and hide more of our network and search latency: https://rauchg.com/2014/7-principles-of-rich-web-applications/#act-immediately-on-user-input

This probably requires canceling our api requests and doing a better job managing them in general.

**Comment by jsnmoon** [comment]
I believe we're already doing this.
