### ISSUE TITLE
Widget: Top Posts and Pages Widget - Increase Range of Time To Determine Top Posts

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#14600]
#### Is your feature request related to a problem? Please describe.

The Top Posts and Pages widget only looks at data from the last 48 hours to pull posts into the widget.

#### Describe the solution you'd like

An option to extend the amount of historical data the widget will use, (ie up to 30 days) to display posts.

#### Additional context
[Current documentation that explains how the widget works found here.](https://en.support.wordpress.com/widgets/top-posts-widget/)

**Comment by jeherve** [comment]
You can use this filter to customize the amount of days used in the widget:
https://developer.jetpack.com/hooks/jetpack_top_posts_days/
