### ISSUE TITLE
Instant Search: Design Styling Details

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#14616]
- [x] close button hidden by scroll bar in Chrome desktop
- [x] "clear filters" button should be less prominent style
- [x] sort selector is missing for desktop
- [x] sort should be a set of buttons/links rather than a dropdown since that is fewer clicks and works better on mobile

**Comment by keoshi** [comment]
> - [ ] sort should be a set of buttons/links rather than a dropdown since that is fewer clicks and works better on mobile

Checking off this one since we're already discussing alternatives on https://github.com/Automattic/jetpack/issues/14607 and pretty close to a decision, I believe.

**Comment by keoshi** [comment]
> - [x] close button hidden by scroll bar in Chrome desktop

This is being handled in https://github.com/Automattic/jetpack/pull/14680

**Comment by keoshi** [comment]
> - [x] sort selector is missing for desktop

This was addressed in https://github.com/Automattic/jetpack/pull/14711

**Comment by keoshi** [comment]
> - [x] "clear filters" button should be less prominent style

Last one from the list being ticked off in https://github.com/Automattic/jetpack/pull/14744

**Comment by gibrown** [comment]
All merged!
