### ISSUE TITLE
Instant Search: Display Selected Filters that are not in overlay widget

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#14615]
To help mitigate cases where the front end filter widget has different filters than have been configured in the overlay widget(s) let's display any enabled filters that are not otherwise shown above the other ones. So just some extra checkboxes that are already selected. This way a user can see that the filter has indeed been selected and they can deselect it.

**Comment by jsnmoon** [comment]
Two questions:

- Where should these unselectable filter values be rendered? Below the overlay sidebar?
- Should these unselectable filter values also be shown in the mobile popover?

**Comment by gibrown** [comment]
Hmmm, so my though is let's just put them at the top underneath the "Clear Filters" link but before any of the configured filters. I guess don't have any heading, just a list of checkboxes (unless you can think of a heading that makes sense.

Will need a bit more design work once @keoshi gets back, but I think this will still be an improvement. We should show it on mobile also though I think it will very rarely happen on mobile unless we start adding some filter button blocks that the end user can add to their site.

**Comment by keoshi** [comment]
I've added some thoughts to https://github.com/Automattic/jetpack/pull/14834 but let me know if this is a better place to discuss the UI.

In short, it sounds like a good idea to place the “transient” filters above the JPS sidebar and display them in mobile as well — both seem to be in place, so I'm happy with what we have. :)
