### ISSUE TITLE
Instant Search: Fix up theme issues

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#14610]
- [x] storefront theme (the default for all WooCommerce), has a number of broken styling details
- [x] storefront: the text color in the close button is black (maybe this won't matter when we change to an X) http://gibrown.wpsandbox.me/demo/?blog_id=20115252&theme=storefront&s=related%20psts
- [x] 2014 no load more button at bottom - http://gibrown.wpsandbox.me/demo/?s=related%20psts&blog_id=20115252&theme=twentyfourteen
- [x] 2015 weird break on filters http://gibrown.wpsandbox.me/demo?blog_id=20115252&theme=twentyfifteen&s=related%20psts https://cloudup.com/cy-YEMc6bwz

**Comment by keoshi** [comment]
> - [ ] storefront theme (the default for all WooCommerce), has a number of broken styling details

Do you remember what these were, @gibrown ? I can only see the poor legibility on the widget titles here:

![image](https://user-images.githubusercontent.com/390760/74443524-3e2fab00-4e6b-11ea-9b21-fc0433c6963a.png)

If that's it, I think that a good case to extend a similar solution to what I proposed on https://github.com/Automattic/jetpack/issues/14666 to a few elements, which also applies to the second bullet point on this issue.

**Comment by keoshi** [comment]
> - [x] 2014 no load more button at bottom - http://gibrown.wpsandbox.me/demo/?s=related%20psts&blog_id=20115252&theme=twentyfourteen

Addressed in https://github.com/Automattic/jetpack/pull/14669

**Comment by keoshi** [comment]
> - [x] 2015 weird break on filters http://gibrown.wpsandbox.me/demo?blog_id=20115252&theme=twentyfifteen&s=related%20psts https://cloudup.com/cy-YEMc6bwz

Addressed in https://github.com/Automattic/jetpack/pull/14670

**Comment by gibrown** [comment]
I think all of the storefront stuff has now been fixed by the styling changes for the search box, close button, etc.
