### ISSUE TITLE
Calendly: Resize block when the window resizes.

### ISSUE THREAD

**Issue by scruffian** [Automattic/jetpack#14619]
#### Steps to reproduce the issue

1. Add a Calendly block 
2. Set the alignment to left or right
3. Resize the window smaller
4. Make the window larger again
5. Notice that the Calendly iframe doesn't get larger again:
<img width="1440" alt="Screenshot 2020-02-10 at 12 58 12" src="https://user-images.githubusercontent.com/275961/74153280-315f4d00-4c08-11ea-815f-f25a67724d6f.png">

#### What I expected
The iframe should expand to fill the window.

#### What happened instead
See above

**Comment by retrofox** [comment]
does it happen in the editor canvas or in the front-end?

**Comment by scruffian** [comment]
I can't replicate this. Let's close.
