### ISSUE TITLE
Security: Threats Found button has formatting issue

### ISSUE THREAD

**Issue by ChaosExAnima** [Automattic/jetpack#14641]
#### Steps to reproduce the issue

1. Create security issue for site.
2. Go to Jetpack -> Settings.
3. Look at warning for Backups and security scanning, button on upper right.

Text shows `Threats Found!FIX`.

**Screenshots**
<img width="1078" alt="Screen Shot 2020-02-11 at 10 46 26 AM" src="https://user-images.githubusercontent.com/1760168/74253025-88bef500-4cbc-11ea-845b-a40b2a4fef67.png">

**Comment by ChaosExAnima** [comment]
@Automattic/jetpack-design, what should this look like?

**Comment by keoshi** [comment]
@ChaosExAnima Is that a clickable button? If so, how does this sound:

> Fix threats now

But also, are we sure they are able to fix the existing threats on the following step? If not we should be more careful about the wording, to avoid setting the wrong expectation.

**Comment by folletto** [comment]
It seems a notice("Threat found!") with button ("FIX"):
https://wpcalypso.wordpress.com/devdocs/design/notice 

Should look like this:
![Screenshot 2020-02-11 at 16 00 22](https://user-images.githubusercontent.com/4389/74253925-a5bced80-4ce7-11ea-8979-55325ff00263.png)

**Comment by ChaosExAnima** [comment]
@keoshi - Clicking that button takes the user to the VaultPress dashboard page, it does not fix anything.

**Comment by jeffgolenski** [comment]
@folletto Yeah I suppose you're right, but that design pattern tho... I wonder how effective it is.

**Comment by keoshi** [comment]
@ChaosExAnima I'd go for `See threats` then.

**Comment by ChaosExAnima** [comment]
@keoshi - Sounds good. Would we replace all the text with that, or just `FIX`?

**Comment by keoshi** [comment]
I'd replace the entire thing like so:

![image](https://user-images.githubusercontent.com/390760/74257062-34336e00-4cec-11ea-9472-9d0e02d6e848.png)

The label itself and the icon (as well as the card's content) already provide enough context for a customer to know that there are active threats.
