### ISSUE TITLE
Jetpack image CDN 403s all requests when running on a staging site with Site Accelerator enabled

### ISSUE THREAD

**Issue by benlk** [Automattic/jetpack#14646]
#### Steps to reproduce the issue

1. On your live site, enable Jetpack's "site accelerator" and "Speed up image load times" in Jetpack -> Settings ->  Performance -> Performance & Speed (https://jetpack.com/support/site-accelerator/)
2. Clone your live site to a staging site that Jetpack recognizes as a staging site. (https://jetpack.com/support/staging-sites/) The site where I noticed this behavior uses WP Engine, with a `*.staging.wpengine.com` URL, and Jetpack was automatically set in Staging mode.
3. View any page containing images.
4. Observe that images are failing to load.
5. Inspect network traffic: requests to `i2.wp.com` and `i1.wp.com` and `i0.wp.com` for images receive a `403 Forbidden` response.

The fix for this issue was to disable the site accelerator in Jetpack -> Settings ->  Performance -> Performance & Speed.

#### What I expected

I expected images to load.

#### What happened instead

No images loaded on the site; requests for images were served with a 403 error.

#### Potential fixes

There are a couple fixes that I can think of; either would solve this problem:

- Change the CDN behavior to enable use of CDN-hosted assets on known staging sites
- When automatically putting Jetpack into staging mode, disable the Site Accelerator.

**Comment by jeherve** [comment]
This most likely happened because your site was set to private, and the image CDN could not access the images on your site. This will happen whether you use Staging mode or not; the CDN can only fetch and cache images that are publicly accessible.

To avoid issues, I would recommend leaving the image CDN option off on your private test site.

**Comment by benlk** [comment]
The site was not password-protected. IIRC, visiting the same CDN URL used on the staging site but without the staging site set as a referer did not result in a 403.

If you recommend leaving the image CDN off on staging sites, should Jetpack turn off the image CDN when it recognizes it's running in staging mode?

**Comment by jeherve** [comment]
> If I recall correctly, visiting the same CDN URL used on the staging site but without the staging site set as a referer did not result in a 403.

If you are still able to reproduce the issue, do you think you could contact us via [this form](https://jetpack.com/contact-support/?rel=support) and give us more details about your setup so we can investigate with you?

> If you recommend leaving the image CDN off on staging sites, should Jetpack turn off the image CDN when it recognizes it's running in staging mode?

You can use the image CDN on staging sites, there are no restrictions there. You cannot, however, use the image CDN on sites that are not publicly accessible.

I hope this clarifies things a bit.

**Comment by benlk** [comment]
It looks like the staging site is running with `<meta name="robots" content="noindex,nofollow">`, so that's probably contributing to the lack of indexing.

**Comment by jeherve** [comment]
No worries there, the image CDN does not care about those tags. If the images are publicly accessible, it will grab them, regardless of any robots.txt or robots meta tag.

**Comment by RazzerDE** [comment]
I have the same error now. Just installed, reloaded the page a few times, and it happened.
