### ISSUE TITLE
React Dash: Do not show backups AAG on Multisite

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#14656]
Jetpack Backups are not available for multisite installs, so we should not prompt for the update.

#### Steps to reproduce the issue

1. Have a multisite.
2. Connect Jetpack
3. Start with Free
4. Revisit the AAG page of the Jetpack Dashboard.

#### What I expected
No mention of backups

#### What happened instead

Ad for backups.

**Screenshots**
![2020-02-12 at 4 18 PM](https://user-images.githubusercontent.com/88897/74382630-622fb580-4db3-11ea-882d-64e346a331d7.png)

Also see https://github.com/Automattic/wp-calypso/issues/39421

**Comment by brbrr** [comment]
There is one more upgrade nudge on the settings page. We might want to take care of that too.
