### ISSUE TITLE
Subscriptions block: Provide outline button style

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/jetpack#14663]
I've suggested adding more block styles to the block in #14662, but it'd be also nice if the user is able to choose the button style like the core buttons block. 

The outline style is very handy when there is a background image behind the form.
![Screenshot 2020-02-13 at 13 01 23](https://user-images.githubusercontent.com/908665/74438014-24896600-4e61-11ea-82b1-63e7ee45cdde.png)

**Comment by apeatling** [comment]
@iamtakashi I think this is possible with the latest version?

**Comment by iamtakashi** [comment]
Oops, sorry! Yes, it's now possible with the update. Closing.
