### ISSUE TITLE
Comments: Dark color scheme on light background result in hidden text

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#1466]
Specifically, the checkbox labels.

![image](https://cloud.githubusercontent.com/assets/1123119/5583346/197ef8a6-9034-11e4-977c-6e46ca0dc19b.png)

Reported by @danhauk

**Comment by ebinnion** [comment]
I just ran into this while testing 4.3. 

@jeherve Does "Not Core Jetpack Team" in this case mean the issue is on WP.com?

**Comment by jeherve** [comment]
> Does "Not Core Jetpack Team" in this case mean the issue is on WP.com?

Correct. This is how the comment form is designed today, and that issue can be reproduced on WordPress.com sites as well.

**Comment by Robertght** [comment]
Hi there!

I noticed the same thing on my end after I've applied the Dark color scheme:

![image](https://user-images.githubusercontent.com/6737345/34078020-980b1c40-e31a-11e7-8bc1-4f57b21614a3.png)

I noticed the styling comes from this path: 
![image](https://user-images.githubusercontent.com/6737345/34078055-6dc772b6-e31b-11e7-9d86-998d7c09497e.png)

Is this a thing that can be fixed from Jetpack or should it be addressed somewhere else?

**Comment by jeherve** [comment]
> Is this a thing that can be fixed from Jetpack or should it be addressed somewhere else?

That's something that will need to be fixed on WordPress.com, we won't be able to patch it in Jetpack itself since the comment form lives in an iFrame hosted on WordPress.com.

Until the problem is fixed, you could work around the problem by changing the color scheme on your site, or adding a background color to the whole div (usually `#respond`) surrounding the form.

**Comment by brbrr** [comment]
I've tested using Twenty-Seventeen theme in Dark mode, and this issue no longer there. Jetpack 6.3-beta

<img width="1347" alt="tested jetpack6test mystagingwebsite com at pressable 2018-06-29 14-00-17" src="https://user-images.githubusercontent.com/5654161/42089202-e9502078-7ba4-11e8-8f08-d1dc9a40e62e.png">
