### ISSUE TITLE
Subscriptions block: Provide a compact block style

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/jetpack#14662]
The current style — the input field and the button are on its own line works well when it's in a narrower area like a sidebar. But when the width isn't a concern, it'd be nice for the users to be able to put the input field and the button on the same line to save the height.

For example, this is the current default.
![Screenshot 2020-02-13 at 12 04 52](https://user-images.githubusercontent.com/908665/74434594-a5912f00-4e5a-11ea-9e1c-866ad025db4e.png)

In the case like above, it'd be much better if the user can choose an alternate block style that appears like:
![Screenshot 2020-02-13 at 12 05 48](https://user-images.githubusercontent.com/908665/74434710-dbceae80-4e5a-11ea-9140-0f29bccabc71.png)

What do you think?

**Comment by jeherve** [comment]
This has now been added as a new option to the block.

**Comment by iamtakashi** [comment]
Thank you @apeatling and all who made this reality 🙇
