### ISSUE TITLE
OpenGraph: Improve default og:title for search results page

### ISSUE THREAD

**Issue by GaryJones** [Automattic/jetpack#14677]
#### Steps to reproduce the issue

1. Do a front-end search on a site with Jetpack enabled.
2. View the source and look for og:title
3. Value is "(no title)"

#### What I expected

It would be good to have a default value of "Search results: {search term}" or something similar, for the og:title. Other OG tags may also benefit from being tweaked for the search results page.

#### What happened instead

```
<meta property="og:site_name" content="{redacted}" />
<meta property="og:image" content="https://{redacted}" />
<meta property="og:image:width" content="449" />
<meta property="og:image:height" content="449" />
<meta property="og:title" content="(no title)" />
<meta property="fb:app_id" content="{redacted}" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:site" content="{redacted}" />
<meta property="og:locale" content="en_GB" />
<meta property="fb:pages" content="{redacted}" />
```

Seems like [this code](https://github.com/Automattic/jetpack/blob/6bd4c590f6168376047e2c36483c323009e03c64/functions.opengraph.php#L69-L163) is missing `is_search()` condition and logic.

**Comment by coleshaw** [comment]
@GaryJones , I'd be interested in taking this on. Do you have other ideas for attributes that would be useful to set in the `search` page?

**Comment by coleshaw** [comment]
Also, can you clarify what a "front-page" search is? I see the `og` metadata tags on a post, but when I search with the top-right box on my test site (WP 5.3.2, Jetpack 8.3), I don't see any `og` tags at all. Am I using the wrong search feature?

<img width="1047" alt="Screen Shot 2020-02-19 at 7 54 31 PM" src="https://user-images.githubusercontent.com/4930129/74890313-aaba1680-5351-11ea-957b-1ee285306536.png">
