### ISSUE TITLE
Post Images: Rework `Jetpack_PostImages::from_gallery()` to use `get_post_galleries()`

### ISSUE THREAD

**Issue by paulgibbs** [Automattic/jetpack#1468]
I've been porting some of the image parsing code out of Jetpack in the last couple of weeks to potentially use for upcoming BuddyPress features. While extracting and tidying and rewriting significants amount of code, I noticed that `Jetpack_PostImages::from_gallery()` could be drastically simplified by using WP's `get_post_galleries()` or related nearby functions.

The only thing the WP function doesn't do is try to extract any wrapping anchor element's `href`, but perhaps you could try to submit something upstream if you need to keep the feature.

**Comment by dereksmart** [comment]
@georgestephanis, can you think of any reason why we needed our own function for this?  Some quick tests using `get_post_galleries()` seemed to work okay.
