### ISSUE TITLE
Testimonials Widget

### ISSUE THREAD

**Issue by BinaryMoon** [Automattic/jetpack#1469]
I think it would be a good idea to add a testimonials widget (this would be handy for wp.com as well). This could show 1 random testimonial, and link through to the testimonials page.

Adding this (and the testimonials shortcode https://github.com/Automattic/jetpack/issues/1345) would mean that themes do not need to explicitly support testimonials for users to be able to make use of them.

**Comment by michaeldcain** [comment]
It would probably be worth adding both a Portfolio and Testimonial widget. Now that they both will have shortcodes, we could just do a basic widget that uses the shortcode options and then runs the shortcode.
