### ISSUE TITLE
Slideshow doesn't work inside column or layout grid blocks

### ISSUE THREAD

**Issue by kmrpankaj** [Automattic/jetpack#14723]
#### Steps to reproduce the issue

1. Add a columns block or Layout Grid block (using any layout preset)
2. Add a slideshow block inside one of the columns and add some images to it.

#### What I expected

A working slider with images.
#### What happened instead
Column stretched to infinite width showing nothing.

**Screenshots**
![Gif of the bug](https://pankajpre.files.wordpress.com/2020/02/slideshow-bug.gif)
![img1](https://pankajpre.files.wordpress.com/2020/02/slideshow-bug-img2.png)
![img2](https://pankajpre.files.wordpress.com/2020/02/slideshow-bug-img1.png)

I am using the Maywood theme and tested it on the TwentyTwenty theme. 
Tested it on WordPress.com site with Premium and Personal and Business plans.

The issue was reported here 18686766-HC

**Comment by jeherve** [comment]
This is most likely the same issue as in #14524.
