### ISSUE TITLE
Calypso Build: production build now outputs .LICENSE files

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#14731]
For the past few releases (I think it may have started after we updated to calypso-build 6 in #14194), I’ve noticed that we are now generating `.LICENSE` files next to bundles, i.e. `editor.js` now has `editor.js.LICENSE` too.

To reproduce, run `NODE_ENV=production yarn build-extensions` and watch `_inc/blocks` for `.LICENSE` files.

I wonder if it may originate from https://github.com/Automattic/wp-calypso/pull/37412

We may have to add additional build options here:
https://github.com/Automattic/wp-calypso/blob/master/packages/calypso-build/webpack/minify.js#L39
https://github.com/webpack-contrib/terser-webpack-plugin#extractcomment

---

Internal discussion: p1582131921461500-slack-team-calypso

**Comment by kraftbj** [comment]
Assigning myself for the Asana sync since it only does Crew folks for now.

**Comment by jeherve** [comment]
Fixed in #14849
