### ISSUE TITLE
VideoPress: Fix the Upgrade Flow via the Video Block

### ISSUE THREAD

**Issue by apeatling** [Automattic/jetpack#14733]
## Steps to reproduce the issue

1. Go to WordPress.com and a free site
2. Add a Video block to the editor
3. Try and upload an MP4 file

<img width="456" alt="screen-shot-2020-02-17-at-22 31 16" src="https://user-images.githubusercontent.com/1464705/74866938-94d43380-5308-11ea-8009-3a6b7284dc7d.png">

#### What I expected
See a banner notifying me that I should upgrade to a premium plan so that I can upload videos and get our VideoPress player:

![videopress-upgrade-promo](https://user-images.githubusercontent.com/1464705/74866971-a9b0c700-5308-11ea-9f4b-414cf69e8cc7.png)

#### What happened instead

I get the error above.

Related:
https://github.com/Automattic/wp-calypso/issues/33013
https://github.com/Automattic/wp-calypso/issues/27772
https://github.com/Automattic/jetpack/issues/14392

**Comment by lancewillett** [comment]
How can we help test this and move it along?

**Comment by apeatling** [comment]
Got a PR to review here: https://github.com/Automattic/jetpack/pull/14735
