### ISSUE TITLE
Twitter Timeline Widget: Link color can no longer be customized

### ISSUE THREAD

**Issue by csonnek** [Automattic/jetpack#14734]
#### Steps to reproduce the issue

Add the Twitter Timeline Widget to a sidebar and enter `jetpack` in the field and change nothing else:

![Widgets_‹_Moar_Kittens__—_WordPress](https://user-images.githubusercontent.com/2814452/74866133-f0f28400-5317-11ea-936e-01bdd20979c7.jpg)

Check the widget on the front end of the site:

![twitterwidget](https://user-images.githubusercontent.com/2814452/74866217-1e3f3200-5318-11ea-96c0-57aa97efa671.jpg)

Go back to the widget settings and change the link color to anything else: 

![widgetsetings](https://user-images.githubusercontent.com/2814452/74866328-5181c100-5318-11ea-805d-0b506689659d.jpg)

Check the front end again and nothing has changed. 

![twitterwidget](https://user-images.githubusercontent.com/2814452/74866217-1e3f3200-5318-11ea-96c0-57aa97efa671.jpg)

- - - 

It appears that the link color no longer works. Also, setting the Border Color also has undesired results: 

![widgetborder](https://user-images.githubusercontent.com/2814452/74866612-c8b75500-5318-11ea-9cbe-31bb321c557c.jpg)

I checked to see if it was tied to whatever colors are set on the Twitter page, but that has no relevance to these settings. 

Reported in 2722461-zen

**Comment by jeherve** [comment]
I've reached out to Twitter to find out more about this; it seems to be an issue with all Twitter embedded timelines right now, so I wonder if they may have deprecated the parameter.

For reference:
https://twittercommunity.com/t/embedded-timelines-custom-link-color-deprecated/134603

**Comment by jeherve** [comment]
Well, it would seem the link color option was deprecated by Twitter in December. :(

I'll remove it from the widget options.
