### ISSUE TITLE
Premium blocks on the front end

### ISSUE THREAD

**Issue by scruffian** [Automattic/jetpack#14743]
#### Steps to reproduce the issue

1. Open the editor on a free Simple site
2. Add an OpenTable block
3. Add a Calendly block
4. Add a Simple Payments block
5. Save the post
6. Open the post in the front end of your site

#### What I expected
I expected to see a message saying the block is unavailable (See paAmJe-so-p2).
<img width="538" alt="screenshot-2019-06-06-at-15 11 07" src="https://user-images.githubusercontent.com/275961/74927030-cf080880-53ce-11ea-804e-6b91faeed360.png">

#### What happened instead
Instead I saw links to opentable.com and calendly.com and nothing for Simple Payments.
<img width="653" alt="Screenshot 2020-02-20 at 10 49 50" src="https://user-images.githubusercontent.com/275961/74926990-bb5ca200-53ce-11ea-8e24-cf6f56b0bc0d.png">

**Comment by apeatling** [comment]
The simple payments block does not show anything, not even a link.
