### ISSUE TITLE
Jetpack 8.2.2 triggering fatal errors on multisite installations

### ISSUE THREAD

**Issue by mzakariya** [Automattic/jetpack#14748]
#### Steps to reproduce the issue

1. Install and **network activate** Jetpack 8.2.2 on a multisite install

#### PHP Fatals

**_WP Admin for a site on the network:_**

> Fatal error: Uncaught Error: Call to a member function api_url() on null in /srv/users/usere66c0661/apps/usere66c0661/public/wp-content/plugins/jetpack/class.jetpack-connection-banner.php:157 Stack trace: 
> 
> #0 /srv/users/usere66c0661/apps/usere66c0661/public/wp-includes/class-wp-hook.php(288): Jetpack_Connection_Banner::enqueue_connect_button_scripts('plugins.php') 
> #1 /srv/users/usere66c0661/apps/usere66c0661/public/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array) 
> #2 /srv/users/usere66c0661/apps/usere66c0661/public/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
> #3 /srv/users/usere66c0661/apps/usere66c0661/public/wp-admin/admin-header.php(104): do_action('admin_enqueue_s...', 'plugins.php') 
> #4 /srv/users/usere66c0661/apps/usere66c0661/public/wp-admin/plugins.php(481): require_once('/srv/users/user...') 
> #5 {main} thrown in /srv/users/usere66c0661/apps/usere66c0661/public/wp-content/plugins/jetpack/class.jetpack-connection-banner.php on line 157

- seems to affect the Dashboard and Plugins pages in WP Admin

------

**_Users page in WP Admin for a site on the network:_**

> Fatal error: Uncaught Error: Call to a member function is_user_connected() on null in /srv/users/usere66c0661/apps/usere66c0661/public/wp-content/plugins/jetpack/class.jetpack.php:1723 Stack trace: 
> 
> #0 /srv/users/usere66c0661/apps/usere66c0661/public/wp-content/plugins/jetpack/class.jetpack.php(6880): Jetpack::is_user_connected(1) 
> #1 /srv/users/usere66c0661/apps/usere66c0661/public/wp-includes/class-wp-hook.php(288): Jetpack->jetpack_show_user_connected_icon('', 'user_jetpack', 1) 
> #2 /srv/users/usere66c0661/apps/usere66c0661/public/wp-includes/plugin.php(206): WP_Hook->apply_filters('', Array) 
> #3 /srv/users/usere66c0661/apps/usere66c0661/public/wp-admin/includes/class-wp-users-list-table.php(583): apply_filters('manage_users_cu...', '', 'user_jetpack', 1) 
> #4 /srv/users/usere66c0661/apps/usere66c0661/public/wp-admin/includes/class-wp-users-list-table.php(399): WP_Users_List_Table->single_row(Object(WP_User), '', '', '1') 
> #5 /srv/users/usere66c0661/apps/usere66c0661/public/wp-admin/includes/class-wp-list-table.php(1273): WP_ in /srv/users/usere66c0661/apps/usere66c0661/public/wp-content/plugins/jetpack/class.jetpack.php on line 1723

---

**_Upon attempting to deactivate Jetpack in Network Admin:_**

> Fatal error: Uncaught Error: Call to a member function clean_nonces() on null in /srv/users/usere66c0661/apps/usere66c0661/public/wp-content/plugins/jetpack/class.jetpack.php:3310 Stack trace: 
> 
> #0 /srv/users/usere66c0661/apps/usere66c0661/public/wp-content/plugins/jetpack/class.jetpack-network.php(205): Jetpack::disconnect() 
> #1 /srv/users/usere66c0661/apps/usere66c0661/public/wp-content/plugins/jetpack/class.jetpack.php(3294): Jetpack_Network->deactivate() 
> #2 /srv/users/usere66c0661/apps/usere66c0661/public/wp-includes/class-wp-hook.php(288): Jetpack::plugin_deactivation(true) 
> #3 /srv/users/usere66c0661/apps/usere66c0661/public/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array) 
> #4 /srv/users/usere66c0661/apps/usere66c0661/public/wp-includes/plugin.php(478): WP_Hook->do_action(Array) 
> #5 /srv/users/usere66c0661/apps/usere66c0661/public/wp-admin/includes/plugin.php(802): do_action('deactivate_jetp...', true) 
> #6 /srv/users/usere66c0661/apps/usere66c0661/public/wp-admin/plugins.php(192): deactivate_plugins('j in /srv/users/usere66c0661/apps/usere66c0661/public/wp-content/plugins/jetpack/class.jetpack.php on line 3310

Tested on a multisite installation with only Jetpack installed/activated. Didn't encounter any issues when activating Jetpack **only** on a specific site, instead of across the network.

**Comment by kraftbj** [comment]
Duplicated with a network activated multisite and visiting the wp-admin of a non-connected subsite.

Only wp-admin/index.php and wp-admin/plugins.php are impacted, so directly visiting wp-admin/edit.php etc will still work.

Once we get a fix out, visiting wp-admin/network/update-core.php will allow folks to update.

**Comment by kraftbj** [comment]
Noting that a non-connected site will fatal wp-admin/index.php and wp-admin/plugins.php. For a connected subsite, the front end will fatal for logged-in views only.

To duplicate, need a subsite with no "local" plugins (only network activated plugins).
