### ISSUE TITLE
Site Management: notice when WP_DEBUG is set to true

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1477]
`Notice: Undefined index: QUERY_STRING in /hermes/bosoraweb113/b2632/ipg.journeyofmyspiritcom/wp-content/plugins/jetpack/class.jetpack.php on line 2406`

See https://github.com/Automattic/jetpack/blob/3.3/class.jetpack.php#L2406

Reported here:
https://wordpress.org/support/topic/notice-undefined-index-query_string-1?replies=1

**Comment by georgestephanis** [comment]
Commit: https://github.com/Automattic/jetpack/commit/bf20347c32b04187f403af8f11d8ae671b643c56

I'd suggest changing this:

```php

```
if ( false !== strpos( $_SERVER['QUERY_STRING'], 'page=jetpack' ) )
    return;
to:

```php
if ( empty( $_GET['page'] ) || 'jetpack' !== $_GET['page'] ) {
    return;
}
```

cc: @enejb

**Comment by abdellahaski** [comment]
problem not sloved yet

Notice: Undefined index: QUERY_STRING in /hermes/bosnaweb05a/b944/ipg.apkgeekcom/almahwouscom/wp-content/plugins/jetpack/class.jetpack.php on line 2406

**Comment by jeherve** [comment]
@abdellahaski Could you try to install Jetpack's development version on your site? The fix is not part of 3.3, but will be included in 3.4.

**Comment by abdellahaski** [comment]
i had install it but i've got the same problem

**Comment by abdellahaski** [comment]
@jeherve  also i've got a problem when trying to connect my site to wordpress.com 
here is the error message:
Your Jetpack has a glitch. Something went wrong that’s never supposed to happen. Guess you’re just lucky: missing_secrets
Try connecting again.

**Comment by jeherve** [comment]
@abdellahaski Could you try to install this plugin and let me know if it helps?
https://github.com/georgestephanis/object-cache-flusher-button

**Comment by abdellahaski** [comment]
the first time i used the development version i download it from this link:
https://wordpress.org/plugins/jetpack/developers/
now Adam Heckler told me (on wp.org forum) that i need to install the beta version from this link : 
https://github.com/Automattic/jetpack/releases/tag/3.4-beta1

now whan i've instaled the beta version and the first problem was sloved 
but i still can't connect my site to wp.com
i get this error message:

```Your Jetpack has a glitch. Something went wrong that’s never supposed to happen. Guess you’re just lucky: missing_secrets
Try connecting again.```

**Comment by jeherve** [comment]
Could you let me know what other plugins are currently active on your site?

**Comment by abdellahaski** [comment]
I use:
BackWPup
Contact Form 7
Floating Social Bar
Image Watermark
iThemes Security
jetpack
Object Cache Flusher Button
OptinMonster
Quick Page/Post Redirect Plugin
Responsive Lightbox
Revolution Slider
TablePress
W3 Total Cache
WordPress SEO

**Comment by abdellahaski** [comment]
I have desactivate all my plugins and i was able to connect my site to wp.com
and i've activate all the pluging one by one and test the wp.com conection after activating any plugin and i was also able to connect to wp.com
i don't know how
now all my plugins are activated and the wp.com connection works also.
anyway thanks for the help
and sorry for my bad english

**Comment by jeherve** [comment]
I see you've been chatting about this problem with Adam in [this thread](https://wordpress.org/support/topic/undefined-index-query_string-1?replies=3). I'll let him reply to your questions there.

**Comment by abdellahaski** [comment]
ok thank you very much
