### ISSUE TITLE
Instant Search: filter the locale for linking to jetpack.com

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#14785]
Per https://github.com/Automattic/jetpack/pull/14762#discussion_r383418029 let's add a bit more validation to the locale linking to jetpack.com.

My first thought is to link to jetpack.com if the locale string is going to contain any characters outside of A-Za-z. Could also limit to a max of 5 chars.

**Comment by jsnmoon** [comment]
Might it be better to create a whitelist of locales actually supported by Jetpack.com instead? Validating the user's locale doesn't guarantee the validity of the generated link to Jetpack.com.

Also, testing for correct IETF language tags even with just regex can be quite [cumbersome](https://stackoverflow.com/questions/7035825/regular-expression-for-a-language-tag-as-defined-by-bcp47/7036171#7036171).

**Comment by gibrown** [comment]
I was hoping to not have to update anything if jetpack.com adds support for a new language.

I think the https://wpastra.com/docs/complete-list-wordpress-locale-codes/ should be sufficient and pretty easy to support. I just realized that there may be some cases that are currently bugs though. Example: https://zh-cn.jetpack.com/
