### ISSUE TITLE
Instant Search: change how we display what was searched for

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#14782]
Currently we place the searched for term in quotes. This looks pretty bad if the end user actually searches for a string in quotes.

<img width="984" alt="Screen Shot 2020-02-24 at 10 22 39 AM" src="https://user-images.githubusercontent.com/820871/75175823-48199f80-56f0-11ea-8b32-6f4b68f76acf.png">

Maybe we should bold the searched for phrase?

41 results for **"state of the word"**

**Comment by gibrown** [comment]
Or maybe only bold it for the cases where we are correcting the search?

**Comment by folletto** [comment]
Do we need to repeat it at all? The search field is right above... if the string doesn't get "processed" to a different string, we can probably just skip it and simplify the page:

> 41 results

**Comment by keoshi** [comment]
Ditto on @folletto's comment above. How about we just go for:

> Found 41 results

Or, as per https://github.com/Automattic/jetpack/pull/14858, if we're loading results at the moment:

> Finding results
