### ISSUE TITLE
Widget Visibility: visibility settings aren't honored when the Infinite Scroll and Widget Visibility modules are both active

### ISSUE THREAD

**Issue by designsimply** [Automattic/jetpack#1478]
In my testing, the problem appears to happen only when both the Infinite Scroll and Widget Visibility modules are both active. It does not happen for every theme, but I am not sure why. I can reproduce the problem using Twenty Fourteen but not Twenty Fifteen.

Steps to reproduce:

1. Open WordPress.org blog running WP 4.1, Jetpack 3.3, and Twenty Fourteen 1.3
1. Go to Jetpack and make sure the plugin is connected to WordPress.com
1. Go to Jetpack > Settings and make sure the Infinite Scroll and Widget Visibility modules are activated
1. Go to Appearance > Customize > Widgets
1. Add the "Archives" widget to the "Primary Sidebar" widget area
1. Click the "Visibility" button and select “Hide” if “Page” is “About”
1. Click the “Save & Publish” button
1. View the About page

* Result: I expected the Archives widget to be hidden on the About page, but it's still visible

Example screencast: https://cloudup.com/ctkjYIadsUP (Length: 4:52)

Seen at http://whatisinfinity.com/wp-admin/customize.php (under Widgets) and http://whatisinfinity.com/about/ using WordPress 4.1, Jetpack 3.3, Twenty Fourteen 1.3, and Twenty Fifteen 1.0 on a shared hosting Bluehost setup running PHP 5.4.34, no caching plugins (aside from Photon in Jetpack)

Reported in 

* https://github.com/Automattic/jetpack/commit/d84dcc21234920fdaddf208b0cb73115332f4284
* https://wordpress.org/support/topic/widget-visibility-no-longer-working?replies=23
* Issue 5909 in WordPress.com Premium Theme SupportPress

**Comment by jeherve** [comment]
Related: #1377

**Comment by jeherve** [comment]
cc'ing @cfinke, who is looking into that issue.
