### ISSUE TITLE
Woocommerce IOS app conection errors

### ISSUE THREAD

**Issue by fluxpixel** [Automattic/jetpack#14789]
Hi there. After this lastest release i was able to login and conect again my woocommerce stores to the ios woocommerce app but there´s still some errors, the app is only fetching the general infos on the main tab, if i go to orders or reviews tab it gives and error and doesn´t show any data, it´s like there´s no orders or reviews on the store. Best regards

**Comment by jeherve** [comment]
Could you contact us via the WooCommerce dashboard and give us more details about  your site, its plugins, and the errors you're seeing when accessing different tabs within the app?
https://woocommerce.com/my-account/create-a-ticket/

Once we have more information about your site, we should be able to help.

Thank you!
