### ISSUE TITLE
Instant Search: only gray-out the search results when updating

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#14781]
This came up when user testing with a friend, I handed him my phone and he played with the demo site.

When you do a search and after the request is sent the entire overlay is getting "grayed out". It is kinda confusing/distracting when you are typing in a search box to then have it gray out. He also felt like the number of search results getting displayed should get cleared so that the number is no longer shown. I suspect that would be unnecessary if we just gray out the correct parts of the overlay.

![Screen Recording 2020-02-24 at 10 16 21 AM 2020-02-24 10_18_48](https://user-images.githubusercontent.com/820871/75175207-22d86180-56ef-11ea-89ee-f999fdbb861f.gif)

I think we should gray out:
- The actual search results
- The count of what the results are and what term we searched against
- Probably the filters - they are about to get redisplayed, and if the user just clicked on one it is nice to have a very immediate response in the UI that the user is actively looking at.

(He loved the UX overall btw, and very quickly noticed that we were caching past results.)

**Comment by folletto** [comment]
Can you include screenshot of how this problem surfaces? :)

**Comment by gibrown** [comment]
@folletto added a gif :) On mobile it is even more obvious I think partly because we were sitting someplace with a bad connection.

**Comment by folletto** [comment]
Got it! :D 

I think one approach could be to... not gray out anything.

Imagine this scenario:
1. I run a search
2. I got some good results, even if not perfect
3. I refine the search, but it's slow
4. In the meantime, I just scroll the list reading through

I think there's value in keeping visible as normal the whole content of the page _even if_ there's work in progress. I'd indicate the work is in progress in some other way.

**Comment by jeffgolenski** [comment]
I like @folletto  suggestion, but I wonder if that's the optimum approach. If I'm re-searching I'm not happy with the current list and I don't imagine I want to keep reading through it. But I don't want to assume the customers' intent here. 

If we do have a scenario where the query is running for more than a couple reasons, Perhaps we could add a message in place of "Showing x results..." but say something like "Looking for items related to [search term]..."?

**Comment by folletto** [comment]
Yes, going for some different way to tell it's updating is way better. That's a simple change we can start with. :)

**Comment by jeffgolenski** [comment]
The more I test this, the most I'm inclined to agree to not gray anything out, and to just substitute the messaging as I mentioned above. Here's a video example of exactly why:

https://cloudup.com/cTk2_KoC1N7

**Comment by gibrown** [comment]
Most of the time the results update should be so fast that any text we display will likely just be noise on the screen (though maybe we only show the message if we don't get a response in less than 500ms or something).

We could also do things like removing the existing results completely? We need a transition that works both when the user is typing, but also when the user clicks on a filter. I think we tried just replacing the results in place, but it felt very jarring. @jsnmoon do you remember?

**Comment by gibrown** [comment]
If we do change the text I'd go shorter: "Looking for XXX"

**Comment by jsnmoon** [comment]
> We could also do things like removing the existing results completely? We need a transition that works both when the user is typing, but also when the user clicks on a filter. I think we tried just replacing the results in place, but it felt very jarring. @jsnmoon do you remember?

I vaguely remember it being jarring, but not much else.

Do we have a consensus on how we ought to proceed? cc @keoshi

**Comment by keoshi** [comment]
Not much else to say here, since Jason's proposal on https://github.com/Automattic/jetpack/pull/14858 is perfect IMO. It appears to make search even faster than before and maintains full legibility at all times.
