### ISSUE TITLE
Lazy Images: Only run as polyfill

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#14799]
As `loading=lazy` is added to more browsers, we should fallback to only load our implementation when needed.

This is currently an enhancement, but could become a bug when this lands in Core. Should be fixed by Jetpack 8.8 if Core's timeline and plans hold.

#### Steps to reproduce the issue

1. Run the WP feature plugin https://wordpress.org/plugins/wp-lazy-loading/
2. Run Chrome 80 (FF support is slated in the April stable release).
3. Activate Jetpack + Lazy Images feature.
4. Open a page on the site.

#### What I expected
Only see `loading=lazy` in Chrome. I'd expect to see our code in FF and older versions of Chrome.

#### What happened instead
Our code is present.

**Screenshots**
n/a

**Comment by kraftbj** [comment]
To detect browser support via JS per https://web.dev/native-lazy-loading/ . See the page for a more fleshed out example.
```if ('loading' in HTMLImageElement.prototype) {
  // supported in browser
} else {
  // fetch polyfill/third-party library
}```

**Comment by dero** [comment]
Relates to https://github.com/Automattic/jetpack/issues/12512

**Comment by jeherve** [comment]
I'll close this one so we can only keep #12512.
