### ISSUE TITLE
Google Calendar Block: layout breaks on smaller browser width

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#14815]
#### Steps to reproduce the issue

Try adding a Google Calendar block to the editor when the editor's width is a bit smaller. Try with a different theme if you don't get that result right away.

![image](https://user-images.githubusercontent.com/426388/75368392-f45eb000-58c1-11ea-95b1-a529c530341b.png)

**Comment by jeherve** [comment]
cc @glendaviesnz @pento

**Comment by apeatling** [comment]
Taking a look at this. The good news is the new G2 design that has merged in master does not outline blocks when selected, so this doesn't present as a visual problem:

<img width="960" alt="Screen Shot 2020-02-26 at 10 36 25 AM" src="https://user-images.githubusercontent.com/1464705/75375883-dc683b80-5883-11ea-9551-b9f54f59fe86.png">

**Comment by apeatling** [comment]
@glendaviesnz @pento I've opened a PR for this, it seems as though a min-width was the culprit. Is there a good reason for keeping this? It seemed to work okay without it, and fix this issue.

**Comment by glendaviesnz** [comment]
The fix in the PR looks reasonable to me, but will wait for @pento to comment as I am not sure why the min width was added initially - there may be some other gotcha that we are overlooking 😃
