### ISSUE TITLE
Tiled Gallery: Tiled mosaic doesn't resize after loading more posts

### ISSUE THREAD

**Issue by tijosh** [Automattic/jetpack#14816]
#### Steps to reproduce the issue

1. Add a tiled gallery to a post that is behind pagination
2. Click on "Load more posts" 
3. See incorrect layout of tiled gallery

I've not been able to reliably reproduce this. I've tested with the More tag, without the More tag, with the "Gallery" post format, without the post format—I have no idea what is triggering this. I've been able to get my test site to produce the problem once or twice after small edits, but there's no obvious conditions that reproduce the problem. 

#### What I expected

The gallery images are resized and rearranged into a tiled mosaic
#### What happened instead

Gallery layout and image sizes are inconsistent

#### Context

#2743663-zen (Simple WPcom site. Theme: Snaps)
#2692412-zen (Atomic WPcom site. Theme: Karuna)

**Screenshots**

![Screenshot](https://d.pr/i/lUCCFm+)

**Comment by jeherve** [comment]
Is this happening with galleries created in old posts (pre-gutenberg) or via the Classic block, or with galleries using the Tiled Gallery block?

Could you also let me know if you see any JavaScript errors in your browser console?

Thanks!

**Comment by tijosh** [comment]
@jeherve It's the Tiled Gallery block, not the Classic block. 

No JS errors in Console.

This seemed different to me than the issue that you mentioned, but you probably have a better idea of the underlying issue.
