### ISSUE TITLE
Site Accelerator Conflicts with PodLove Plugin

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/jetpack#14813]
This has been reported to the PodLove devs:

https://sendegate.de/t/mein-feed-validiert-nicht-was-kann-ich-tun/6975

#### Steps to reproduce the issue

1. Install and activate PodLove. Add a podcast. 
2. Click on your site's feed (yourgroovysite/feed/mp3/). Note that it loads.
3. Activate the image accelerator.
4. See that the feed is broken.

#### What I expected

The feed should still work.

#### What happened instead

The feed doesn't load.

Reported in 2726497-zen

**Comment by jeherve** [comment]
Closing as duplicate of #8321
