### ISSUE TITLE
Publicize: add filters to provide custom app secrets and thus post via your own app

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1482]
While it doesn't seem to make much sense to add new fields to the sharing settings screen, I wonder if we could allow site owners to use a custom Facebook app instead of ours, by providing filters allowing you to overwrite the default values.

Suggested here:
http://www.wpbeginner.com/opinion/is-jetpack-misusing-your-brand-to-promote-wordpress-com/#comment-1774091379

**Comment by jkudish** [comment]
Publicize goes through WP.com servers to determine how best to publish the content and then does so using our app and secrets. For another app to be used, we'd need to collect the FB app ID and secrets from the user, which is not something we should take lightly and it's not as simple as filter. I don't think we want to get into this and there are other plugins out there that can accomplish this for those who want to publish to FB that way.

Closing as wontfix
