### ISSUE TITLE
Google Calendar block: lack of space around error notice

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#14824]
When and invalid embed code is pasted into the Google Calendar Block, the resulting error notice lacks spacing and is misaligned with the content.

#### Steps to reproduce the issue

1. Add Google Calendar block to a post or a page.
2. Paste any random text in the input field, to invoke the error message. Note the position of the message.

#### What I expected
For the error message to be aligned with the text, and have adequate vertical spacing.

**Screenshots**
![image](https://user-images.githubusercontent.com/4550351/75413065-9640d400-5978-11ea-87b8-1e26f8190bc1.png)

Found while testing the Google Calendar block.

**Comment by apeatling** [comment]
I'll take this one.
