### ISSUE TITLE
Block: Google Calender block placeholder layout slightly  broken

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/jetpack#14836]
In 8.3 release and with Gutenberg < 7.2 the Google Calendar block placeholder layout is slightly broken. 

#### Steps to reproduce the issue

 * In an Jetpack instance with 8.3 release and Gutenberg < 7.2 try adding a Google Calendar block. The font is different to all the other block fonts, and the ol items are incorrectly centred.

<img width="637" alt="Screen Shot 2020-02-28 at 9 26 48 AM" src="https://user-images.githubusercontent.com/3629020/75498380-dd3bd180-5a2b-11ea-97a7-2cca22180927.png">

#### What I expected
The Font of the list items should match the rest of the block, and the list items should be left aligned.

**Comment by mdbitz** [comment]
Verified this fixes the center alignment that was seen in Gutenberg < 7.2.

Testing in progress on new Gutenberg versions.
