### ISSUE TITLE
Subscriptions: add a reply-to to the subscription emails

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1483]
Jetpack Subscription emails are sent from a WordPress.com email address. The sender name uses the blog title.

Some readers reply to the subscription emails, expecting their emails to reach the site owner. That obviously doesn't work and the emails get lost, but I wonder if we could add a `reply-to` parameter to the emails, matching the author's email address or the Jetpack site's admin email address. That would avoid a lot of lost emails.

Suggested here:
https://wordpress.org/support/topic/change-the-from-email-address-generated-by-the-jetpack-subscription-servers?replies=1

**Comment by charlottegibb** [comment]
Hi there, I was wondering if there was any progress on this issue? It is creating quite a lot of havoc for me! Thanks!

**Comment by jeherve** [comment]
@charlottegibb We haven't made any progress on this yet, but we'll post here as soon as we have some news!

**Comment by melindahelt** [comment]
Any updates on this yet? I have a few users asking for solutions for this.

**Comment by jeherve** [comment]
@melindahelt No, no updates yet. We'll post here as soon as we work on this.

**Comment by RCowles** [comment]
Requested here:
https://wordpress.org/support/topic/can-we-change-the-reply-to-for-subscriptions?replies=1

**Comment by gracie** [comment]
Requested in WordPress.com Support as well.

**Comment by RCowles** [comment]
2819590-t

**Comment by vladsopov** [comment]
**Two years** since requested, and case is still open?

**Comment by cena** [comment]
3230270-t

**Comment by SteveKaye** [comment]
Has any progress been made on this?

Last week I was shocked to learn that I've sent out 113 blog posts (over the past few years) with a donotreply return e-mail address. This has undoubtedly hurt my business and my reputation.

Please fix this.

Thank you.

**Comment by macmanx2** [comment]
I discovered that one of my close long-time followers has replied to every single subscription email with a comment. These of course just went into a void, never to be published or even seen.

This would really be nice to have.

**Comment by htdat** [comment]
3443683-zen

**Comment by danjjohnson** [comment]
3534662-zen

**Comment by opr** [comment]
4193084-zen

**Comment by lakellie** [comment]
5262389-zen

**Comment by sitandplas** [comment]
Today I have spoken with Jetpack support and there is still no solution. Developers will only create a fix if Wordpress users press
Meanwhile, our corporate image continues to be damaged.

**Comment by dhanson-wp** [comment]
We have several clients we build sites for that would also like to customize the `reply-to` email. In some instances the email might be different than the site's or Jetpack connection admin email, so a field somewhere that a unique email could be added. If one is not added, then `reply-to` would not be enabled.

[Substack already handles email replies](https://support.substack.com/hc/en-us/articles/360037832731-How-do-I-see-replies-to-an-email-I-ve-sent-out-) automatically and allows for site owners to [change their email](https://support.substack.com/hc/en-us/articles/4418724934676-Can-I-receive-emails-to-my-Substack-email-address-from-my-subscribers-only-).

**Comment by bryanwmiller** [comment]
+1 to @dhanson-wp's comment above. This feature would make it significantly more useful for people who want to use it in a professional capacity.

**Comment by essleeung** [comment]
+ 1 as requested here: 6584185-zd-woothemes

**Comment by bixfrankonis** [comment]
This seems like a no-brainer?

**Comment by simison** [comment]
It's now possible to set blog author to appear as "reply to" email, and responses will go to their email:

![image](https://github.com/Automattic/jetpack/assets/87168/d12f1f80-b63c-4450-90f9-324df0213a57)

There are a few more related follow-ups we're working or considering, including using _any_ email as "reply to" address:

- https://github.com/Automattic/jetpack/issues/37369 (implementing)
- https://github.com/Automattic/jetpack/issues/37354 (implementing)
- https://github.com/Automattic/jetpack/issues/37371 (considering)

**Comment by tehjaymo** [comment]
> It's now possible to set blog author to appear as "reply to" email, and responses will go to their email:
> 
> ![image](https://private-user-images.githubusercontent.com/87168/330705857-d12f1f80-b63c-4450-90f9-324df0213a57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjA1MDUsIm5iZiI6MTcxNTc2MDIwNSwicGF0aCI6Ii84NzE2OC8zMzA3MDU4NTctZDEyZjFmODAtYjYzYy00NDUwLTkwZjktMzI0ZGYwMjEzYTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA4MDMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZWI0OGIyNGVhNDhhN2MxOWY4OWE3OTcxZjZhYzJiNWRjYjY5ZDAxZjJhZWNiZDdiZWQ0MTY3MGNjMjFjOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zFNzAJhfVIE4V2-PxYYtAlLOzx9pT0WA9dV-kTa1aB0)
> 
> There are a few more related follow-ups we're working or considering, including using _any_ email as "reply to" address:
> 
> * [Allow "reply to" as comments for Atomic & Jetpack sites #37369](https://github.com/Automattic/jetpack/issues/37369) (implementing)
> * [Newsletter: allow customizing "From" name #37354](https://github.com/Automattic/jetpack/issues/37354) (implementing)
> * [Allow custom "reply to" addresses in emails #37371](https://github.com/Automattic/jetpack/issues/37371) (considering)

What steps do I need to follow to find this setting?

**Comment by simison** [comment]
@tehjaymo the feature will be available in the next Jetpack release (13.5) released in June 4th.

After upgrading, go to Jetpack → Settings → Newsletter and see "Reply to" setting:

<img width="1305" alt="Screenshot 2024-05-15 at 11 08 52" src="https://github.com/Automattic/jetpack/assets/87168/8310014c-41f0-4d0d-8b52-b5053d8eeba8">
<img width="1085" alt="Screenshot 2024-05-15 at 11 08 31" src="https://github.com/Automattic/jetpack/assets/87168/021a81b4-2402-40af-a88e-b4f5f4d8305b">

**Comment by simison** [comment]
@tehjaymo and others, it's now possible to replies go to blog comments as well as of Jetpack 13.6:

![image](https://github.com/Automattic/jetpack/assets/87168/fdcc65fc-54d2-4539-8862-7f577619edeb)
