### ISSUE TITLE
Block: Google calendar block errors if shareable link used

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/jetpack#14838]
If a Google Calendar shareable link is used instead of an embed link the block errors, but doesn't indicate to the user why.

#### Steps to reproduce the issue

1. On Jetpack 8.3 setup add a Google Calendar block and use the Shareable link option which appears at the top of the Settings page.

#### What I expected
To see an error indicating that I had used the wrong link

#### What happened instead
https://calendar.google.com/calendar?cid=Z2xlbi5kYXZpZXNAYThjLmNvbQ

<img width="636" alt="Screen Shot 2020-02-28 at 2 20 37 PM" src="https://user-images.githubusercontent.com/3629020/75501885-1aa55c80-5a36-11ea-84e3-0ffdf6cc4932.png">

**Comment by scruffian** [comment]
Would it be possible to make the shareable link work?
