### ISSUE TITLE
Add Testimonial CPT option in admin

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#1484]
With the addition of a <a href="https://github.com/Automattic/jetpack/pull/1480">testimonial shortcode</a>, it's a good time to add the CPT as an option here: 

![screen shot 2015-01-07 at 12 36 29 pm](https://cloud.githubusercontent.com/assets/7129409/5650620/fd838960-966d-11e4-9bf0-cd526c54bce1.png)

**Comment by michaeldcain** [comment]
+1

**Comment by samhotchkiss** [comment]
Still needed:
1) Update the help box that pops up when you hit "Custom Content Types" in the module list
2) This learn more link goes to portfolio: https://cloudup.com/cDka9cFFzkf

**Comment by dereksmart** [comment]
@squirk could you whip up something for the help box please?

**Comment by samhotchkiss** [comment]
@squirk here's a screenshot of where we're talking about: https://cloudup.com/csa6XXGuOJA

**Comment by squirk** [comment]
@dereksmart 

Custom Content Types

Organize and display different types of content on your site, separate from posts and pages.
To enable a custom content type, head over to Settings → Writing → Your Custom Content Types to activate either "Portfolio Projects” or “Testimonials” by checking the corresponding checkbox. You can now add projects and testimonials under the new "Portfolio” or “Testimonials” menu item in your sidebar. Once added, your custom content will be visible on your website at url/portfolio/ or url/templates/, or you may add them with <link>shortcodes</link>.

**Comment by samhotchkiss** [comment]
This has been merged in, @dereksmart just needs to get Stephen's copy in

**Comment by dereksmart** [comment]
@samhotchkiss updated the copy in aa7c62d

**Comment by samhotchkiss** [comment]
sweet!
