### ISSUE TITLE
Calendly block: stepping back in block navigates away from page

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#14846]
#### Steps to reproduce the issue

1. Visit a post with a Calendly block.
2. Click to book a specific slot (e.g. "15 minutes meeting")
![image](https://user-images.githubusercontent.com/426388/75577238-dd56c400-5a61-11ea-9f57-c2c62cedfb94.png)
3. Click on the back button at the top of the modal:
![image](https://user-images.githubusercontent.com/426388/75577266-ed6ea380-5a61-11ea-99e9-c4b4be8024ad.png)
4. Watch as you are redirected away from your site, to calendly.com.

**Comment by aaronrobertshaw** [comment]
I haven't been able to replicate this issue. I've tested both the modal and inline embeds across different browsers, with a couple of different themes, as well as with and without the Gutenberg plugin.

@jeherve Can you confirm if this is still an issue or should we close this?

![Calendly-BlockBackButton](https://user-images.githubusercontent.com/60436221/89855537-103ce080-dbda-11ea-983f-3c6db881db91.gif)

**Comment by jeherve** [comment]
This looks like it's been fixed. 🎉 Closing.
