### ISSUE TITLE
OpenTable :: embed dimensions

### ISSUE THREAD

**Issue by mdbitz** [Automattic/jetpack#14857]
The OpenTable embed has different layouts including a "wide" version with a width of 840 pixels. In some themes the content width is less than 840 pixels on desktop. Would it be possible to add a warning to users in these scenarios so they know it will not display fully?

#### Steps to reproduce the issue

1. Install and Activate twentytwenty theme
2. Click Posts > Add New
3. Insert a Open Table block
4. Choose a restaurant then select "wide" layout from options
5 Notice that the the full content of the embed is not displayed

#### What I expected
If possible we should let the user know that their current layout is not going to display properly

#### What happened instead
We display a partial embed that end users are going to have trouble interacting with.

**Screenshots**
<img width="645" alt="Screen Shot 2020-03-02 at 3 11 30 PM" src="https://user-images.githubusercontent.com/5784663/75715283-29d91400-5c9b-11ea-829e-8c0fa7b80d82.png">

**Comment by creativecoder** [comment]
Noting that there may be learnings from [solving similar issues with the Google Calendar block](https://github.com/Automattic/jetpack/issues/14823) to guide us on this one.

**Comment by alaczek** [comment]
I encountered the same thing. The single-line wide style form width is 806px, which is wider then content width in Varia child themes (750px). This means that to display it in full the block needs to be in wide mode. Could the block be switched to wide by default when that style is selected? 

It also means that it’s not possible to have the block centered because we can’t have block both centered and wide 😕

**Comment by glendaviesnz** [comment]
Had an initial look at this today, and it looks like the only option currently would be to only allow `wide` alignment option if the `wide`  as @alaczek mentions. Currently if you select the `wide` style it does automatically switch your alignment to `wide` also, but there is nothing to stop the user changing it after that. Had a look to see if there was a way to remove the other alignment options if wide was selected but there isn't currently, so tomorrow will have a look at how to best notify the user that anything other than `wide align` is unlikely to work with `wide style`.
