### ISSUE TITLE
Tiled Gallery :: srcset using Accelerated urls when not enabled.

### ISSUE THREAD

**Issue by mdbitz** [Automattic/jetpack#14856]
When a user repositions images in a Tiled Gallery the srcset generated contains the in.wp.com accelerated url instead of the original domain when Site Accelerator is disabled.

Tiled Gallery needs to only use in.wp.com urls when Site Accelerator has been enabled.

#### Steps to reproduce the issue

1. Go to jetpack_modules admin page (wp-admin/admin.php?page=jetpack_modules)
2. Disable Site Accelerator module
3. Click Posts > Add New
4. Add a Tiled Gallery to the page
5. View source you will see it uses the site's domain for srcsets
6. Move an image in the gallery via < > buttons or "Edit Gallery" drag-n-drop
7 View source you will see all srcsets now use the iN.wp.com domains

#### What I expected
iN.wp.com domains should only be generated if the site is using Site Accelerator

#### What happened instead
iN.wp.com domains are being generated for images when Site Accelerator is disabled

--

```
<!-- wp:jetpack/tiled-gallery {"ids":[52,49,51]} -->
<div class="wp-block-jetpack-tiled-gallery aligncenter is-style-rectangular"><div class="tiled-gallery__gallery"><div class="tiled-gallery__row"><div class="tiled-gallery__col"><figure class="tiled-gallery__item"><img alt="" data-height="1024" data-id="52" data-link="http://YYYY/2020/03/02/test-posting-gallery/20191012_093446-m/" data-url="http://YYYY/wp-content/uploads/2020/03/20191012_093446-m.jpg" data-width="576" src="https://i2.wp.com/YYYY/wp-content/uploads/2020/03/20191012_093446-m.jpg"/></figure></div><div class="tiled-gallery__col"><figure class="tiled-gallery__item"><img alt="" data-height="2560" data-id="49" data-link="http://YYYY/2020/03/02/test-posting-gallery/20191012_093417/" data-url="http://YYYY/wp-content/uploads/2020/03/20191012_093417-scaled.jpg" data-width="1440" src="https://i0.wp.com/YYYY/wp-content/uploads/2020/03/20191012_093417-scaled.jpg"/></figure></div><div class="tiled-gallery__col"><figure class="tiled-gallery__item"><img alt="" data-height="1440" data-id="51" data-link="http://YYYY/2020/03/02/test-posting-gallery/20191012_093440/" data-url="http://YYYY/wp-content/uploads/2020/03/20191012_093440-scaled.jpg" data-width="2560" src="https://i2.wp.com/YYYYwp-content/uploads/2020/03/20191012_093440-scaled.jpg"/></figure></div></div></div></div>
<!-- /wp:jetpack/tiled-gallery -->
```

**Comment by jeherve** [comment]
> Tiled Gallery needs to only use in.wp.com urls when Site Accelerator has been enabled.

@simison could weigh in with more information here, but I believe we've moved away from this in #13471. Photon is now used even if you don't have the module on. We only stop using Photon in some special use cases:
- Local sites
- WordPress.com Simple sites
- VIP Go sites (see #13293)

Closing this for now. @simison Feel free to reopen if I got something wrong.

**Comment by simison** [comment]
Yep, Tiled Gallery always needs Photon to crop/resize images on the fly.

> WordPress.com Simple sites
> VIP Go sites (see #13293)

We always use Photon outside localhost, those are just Photon-like servers in different URLs.
