### ISSUE TITLE
Instant Search: Inputted characters are dropped when overlay opens

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#14872]
See https://github.com/Automattic/jetpack/pull/14788#issuecomment-594006231.

#### Steps to reproduce the issue

1. Setup Jetpack Instant Search on your site.
2. Type quickly into your site search input.

#### What I expected
Typed characters to be persisted in the overlay input.

#### What happened instead
Typed characters are dropped while the overlay is opening and shifting focus to its input.

**Comment by bluefuton** [comment]
No longer seems to be an issue.
