### ISSUE TITLE
Block previews in Premium blocks

### ISSUE THREAD

**Issue by scruffian** [Automattic/jetpack#14881]
#### Is your feature request related to a problem? Please describe.
We disable block previews for premium blocks. I assume this is because of the UpgradeNudge.

#### Describe the solution you'd like
We now have a `__isBlockPreview` attribute we can use to hide the `UpgradeNudge` (see https://github.com/Automattic/jetpack/blob/ef97833724912a78d17d9f5b0cf094c50a582259/extensions/shared/wrap-paid-block.jsx) so we can enable previews for Premium blocks.

#### Describe alternatives you've considered
We could also generate an image preview like the map block does.

#### Additional context
The example is removed here: https://github.com/Automattic/jetpack/blob/a998fb84c69fa83c79c9ae4302d3d179c9813e3a/extensions/shared/register-jetpack-block.js#L51

**Comment by simison** [comment]
> We could also generate an image preview like the map block does.

Map block uses an image just because we cannot load map tiles without API key.

If you need alternative, I think you can extract the visual components to dummy component that you can then render as a preview.

**Comment by davemart-in** [comment]
> I assume this is because of the UpgradeNudge.

I believe it's also because a few of the premium blocks have a blanks lat screen that requires entering info before you see the block. In the dynamic preview this blank slate screen is shown instead of the rendered block. 

As @simison pointed out, using an image should be fine in these scenarios.

**Comment by davemart-in** [comment]
@lcollette can we make some screenshots for each of the premium blocks? Once we have screenshots I'm happy to push this over to the Janitorial queue.

**Comment by davemart-in** [comment]
@rickybanister mentioned that we might want to explore having a preview mode with dummy data.

**Comment by retrofox** [comment]
Fixed by https://github.com/Automattic/jetpack/pull/17580. Closing.
