### ISSUE TITLE
Jetpack Infinite Scroll on HTTPS doesn't load

### ISSUE THREAD

**Issue by ste93cry** [Automattic/jetpack#1488]
Hi, I'm running my site on HTTPS protocol and I have JetPack Infinite Scroll enabled. On the frontend, the script is loaded before the definition of the `infiniteScroll` variable, and the following check is executed too early throwing an error in the console:

    if ( "https:" == document.location.protocol ) {
        infiniteScroll.settings.ajaxurl = infiniteScroll.settings.ajaxurl.replace( "http://", "https://" );
    }

Probably, this code should be executed in the `$(document).ready` block, so I think this is a bug. If confirmed, this problem breaks the plugin on HTTPS sites and should be fixed asap.

Reference to my post on WordPress forum: [https://wordpress.org/support/topic/jetpack-infinite-scroll-on-https-doesnt-load](https://wordpress.org/support/topic/jetpack-infinite-scroll-on-https-doesnt-load)

**Comment by jeherve** [comment]
Could you post your site URL here, so I can have a look?

If you want it to remain private, you can also contact us via this contact form:
http://jetpack.me/contact-support/

> Reference to my post on WordPress forum: https://wordpress.org/support/topic/jetpack-infinite-scroll-on-https-doesnt-load?replies=1#post-6412659

I get redirected to `/support/`. Could you check that the URL is correct?

**Comment by ste93cry** [comment]
sorry I fixed the link to the post on WordPress forum. The website is [https://www.visitabanomontegrotto.com](https://www.visitabanomontegrotto.com)

**Comment by jeherve** [comment]
Could you post a link to the page listing blog posts and where Infinite Scroll is triggered?

**Comment by ste93cry** [comment]
sorry, it's Monday and I'm still sleeping :sleeping: I re-enabled temporarily the plugin, but this is a production website so I can't have it breaks the pagination for a long time. Please check and let me know when you're done, so I can disable it again until the problem is fixed

**Comment by jeherve** [comment]
Thanks.

The `infiniteScroll` variable is added to `wp_footer`, with a priority of `2` ([ref](https://github.com/Automattic/jetpack/blob/3.3/modules/infinite-scroll/infinity.php#L340)).
`infinite.js` is loaded via another function, also hooked into `wp_footer`, with a priority of `21` ([ref](https://github.com/Automattic/jetpack/blob/3.3/modules/infinite-scroll/infinity.php#L342)).

I checked on 2 sites of mine, and that seems to work properly.

Your site, on the other hand, seems to handle things differently, and the priority setting is lost. I also notice that other resources are not added to the ` head` and the `footer` of your site. Does your theme use `wp_head` and `wp_footer`, or do you enqueue manually somehow differently?

**Comment by ste93cry** [comment]
My site uses `wp_head` and `wp_footer` functions inside a Timber-enabled theme. I usually don't enqueue theme scripts by using that functions because I don't have the need to do it, except one JS file that handles the custom infinite scroll behaviour.

    add_action( 'wp_enqueue_scripts', 'enqueue_scripts' );

    public function enqueue_scripts() {
        wp_enqueue_script( 'vam-news', get_template_directory_uri() . '/lib/js/news.js', array( 'jquery', 'the-neverending-homepage' ), null, true );
    }

I obviously didn't edit any plugin. I can't see what's wrong with my theme

**Comment by jeherve** [comment]
Could you send me a link to the theme so I can take a look?

**Comment by ste93cry** [comment]
The theme is a custom made theme, so I can't give you the access to the files. I tried debugging the `wp_filter` variable during the execution of the `wp_footer` action, and you can see the order of the functions is correct).

![wp_filter_variable](https://cloud.githubusercontent.com/assets/1770485/5703922/e26cbb44-9a6c-11e4-8cc1-fda5d7efdc54.png)

I found out that nggGallery is the cause of the problem: Their resource manager uses the `wp_print_scripts` function (I didn't dive into the code to understand why they do this), and this cause the scripts to be removed from the queue of outputted scripts so that they are inserted before the time they should. Probably, the settings block of Infinite Scroll is added later, so it isn't catched by the manager. I found the constant `NGG_DISABLE_RESOURCE_MANAGER` that when enabled fixes the problem, although it can cause other problems in pages where the gallery is used. Just for reference, here the file that causes the problem: [class.photocrati_resource_manager.php](https://plugins.trac.wordpress.org/browser/nextgen-gallery/tags/2.0.66.37/non_pope/class.photocrati_resource_manager.php#L95)

**Comment by jeherve** [comment]
Nice catch. :+1: 

Closing this issue then.

**Comment by georgestephanis** [comment]
Just tweeted this at the NGG folks so they're aware of the conflict.

https://twitter.com/daljo628/status/554656150382456833

**Comment by scottwyden** [comment]
Thanks for making us aware. We're looking into it!

**Comment by ste93cry** [comment]
maybe it could be useful to have a warning in the JetPack Infinite Scroll documentation saying of the conflict and talking about the constant I found as a workaround?

**Comment by georgestephanis** [comment]
@ste93cry Depending on the volume of issues that come it, may be worthwhile.  But to the best of my knowledge, this is the first time it's happened thus far.

**Comment by ste93cry** [comment]
just two more suggestion for the JS plugin: it would be great to have the `post-load` jQuery event to be namespaced, and it would be cool to have a `pre-load` plugin so devs are able to edit the POST request parameters before sending them to the server

**Comment by georgestephanis** [comment]
@ste93cry Can you make a new issue for that, so it doesn't get lost and tag me in it?  I'd love to get it discussed independently of this.
