### ISSUE TITLE
Recurring Payments block: Upgrade Nudge

### ISSUE THREAD

**Issue by scruffian** [Automattic/jetpack#14893]
The Recurring Payments block tries to upsell people to a plan before they can use it, which is a different pattern to our other blocks. We should show an UpgradeNudge and allow users to interact with the block before purchasing the plan.

**Comment by simison** [comment]
Note that the nudge visibility & possibility to demo the block behaves differently on wpcom and Jetpack.

Here's how the block looks like on wpcom sites:

<img width="845" alt="Screenshot 2020-03-06 at 19 42 55" src="https://user-images.githubusercontent.com/87168/76108141-b3158100-5fe2-11ea-90af-ef74fbdb2e0e.png">

(Looks like the top-margin needs fixing, likely went missing due changes in core)

**Comment by davemart-in** [comment]
@scruffian I'm seeing:

> You can try it out before upgrading, but only you will see it. It will be hidden from your visitors until you upgrade.

in the premium block banner for recurring payments. Was this fixed?

**Comment by scruffian** [comment]
The difference is that for the other blocks we also show the UpgradeNudge on the front end. Once  https://github.com/Automattic/jetpack/pull/14426 merges we should update Recurring Payments to use this new approach.

**Comment by jeherve** [comment]
Related discussions:
- p1HpG7-grb-p2
- p1HpG7-7ir-p2

**Comment by jeherve** [comment]
Closing as this block is now free to all users.
