### ISSUE TITLE
The API doesn't return with the authors from co-authors-plus

### ISSUE THREAD

**Issue by csabaxyz** [Automattic/jetpack#14894]
Hey,
I'm kind of at a loss here, because I'm not 100% sure that this is supposed to be classified as a bug, but it certainly doesn't do what I'd expect it to do. And considering that both Jetpack and Co-Authors-Plus plugin is under the same umbrella, this behavior seems to be a bug to me.

#### Steps to reproduce the issue

1. Create a post, and add one or many authors to it via the https://github.com/Automattic/Co-Authors-Plus plugin
2. Check the API endpoint, e.g. this is a live sample from a client's site: https://public-api.wordpress.com/rest/v1/sites/www.localfutures.org/posts/38424
3. The author is not the one that was set.

#### What I expected

I expected that the same author would be used as here: https://www.localfutures.org/the-folly-of-farm-free-food/

#### What happened instead

But the site admin was used instead. Also, the email notifications from Wordpress.com show the incorrect author, but I'm guessing it comes from the same API.

I think, the issue comes from here: https://github.com/Automattic/jetpack/blob/1364e8049ccd517132ef466d609d028d91dc7219/json-endpoints/class.wpcom-json-api-post-endpoint.php#L171-L173

And also here it is documented that the author is supposed to be an `object`, but what would happen if there are multiple authors?
https://github.com/Automattic/jetpack/blob/1364e8049ccd517132ef466d609d028d91dc7219/json-endpoints/class.wpcom-json-api-post-endpoint.php#L8

So, my question is: is it possible and safe to overwrite the author with the info coming from the Co-Authors-Plus plugin, even if there are multiple authors set?

**Comment by jeherve** [comment]
Interestingly, the author ID appears to be correct, it matches:
- On your site, [the post is authored by user 844](https://www.localfutures.org/wp-json/wp/v2/posts/38424): https://www.localfutures.org/wp-json/wp/v2/users/844 (I could not access that last page though, as your site seems down at the moment).
- On WordPress.com, [the post is also authored by user 844](https://public-api.wordpress.com/rest/v1/sites/www.localfutures.org/posts/38424) but its info may be different:
```json
"author": {
	"ID": 844,
	"login": "Local Futures",
	"email": false,
	"name": "Local Futures",
	"first_name": "Local",
	"last_name": "Futures",
	"nice_name": "local-futures",
	"URL": "",
	"avatar_URL": "https://secure.gravatar.com/avatar/f20a1c9f7849b06b6365ba9cef9730dc?s=96&d=mm&r=g",
	"profile_URL": "https://en.gravatar.com/f20a1c9f7849b06b6365ba9cef9730dc",
	"ip_address": false
}
```

This may not be related to Co-Authors Plus. It may be a communication issue between your site and WordPress.com, thus causing the data to become out of date between the 2 platforms.

Once your site is back up, could you contact us via [this contact form](https://jetpack.com/contact-support/?rel=support) and give us more information about your site so we can look into this and investigate with you?

Thank you.
