### ISSUE TITLE
Tiled Gallery Block: Block Toolbar layout broken in IE11

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#14890]
#### Steps to reproduce the issue

1. On IE11, open the post editor.
2. Insert a Tiled Gallery block
3. Add images to the block.
4. Notice the broken block toolbar:

![image](https://user-images.githubusercontent.com/426388/75968126-35138600-5ecd-11ea-942c-8ebd5cd9bb0b.png)

This seems limited to the Tiled Gallery block.

**Comment by kraftbj** [comment]
We will be deprecating IE 11 support this summer and thus are wontfix'ing IE 11 issues now. See p1HpG7-c8n-p2
