### ISSUE TITLE
Tiled Gallery: images are upscaled when too small to fit the content width

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#14891]
#### Steps to reproduce the issue

1. Go to the post editor.
2. Create a tiled gallery with small images, all smaller than the theme's content width.
3. Publish post.
4. See that the images are upscaled by Photon:

![image](https://user-images.githubusercontent.com/426388/75970584-db14bf80-5ed0-11ea-9628-a54b5a80ba7e.png)

**Comment by ivan-ottinger** [comment]
I was able to reproduce the issue. The same behavior is present in other gallery blocks as well, e.g. Gallery block and Masonry, Stacked, Collage (available in CoBlocks and WPCOM).

We could change the way the images are rendered. For example, if the image is smaller, we could center it and have either transparent or black/white background around it. But then, I would say, the form and shapre of the gallery would be kind of lost. 🤔

I think that if the user is uploading a smaller image, they could use the Image block for example. 

With the above said, I would suggest to mark this issue as `won't fix`. In other words, I would say the gallery is working as expected.

What do you think?

**Comment by jeherve** [comment]
That works for me. We can always reopen and reconsider if more reports come in. 👍
