### ISSUE TITLE
Add upgrade nudge to Audio block for Simple site free plan users

### ISSUE THREAD

**Issue by apeatling** [Automattic/jetpack#14902]
Matching the result in https://github.com/Automattic/jetpack/pull/14735 
Related: https://github.com/Automattic/wp-calypso/issues/33013

**Comment by apeatling** [comment]
I've started some initial investigation into this, however there needs to be more robust WordPress.com plan checking available before this can be done.

Requires both: https://github.com/Automattic/jetpack/pull/14426 and https://github.com/Automattic/jetpack/pull/14735 to be merged first.

**Comment by apeatling** [comment]
Moving this to blocked since #14426 still needs to merge.

**Comment by creativecoder** [comment]
This should be unblocked now.

**Comment by davemart-in** [comment]
This was merged with https://github.com/Automattic/jetpack/pull/16717
