### ISSUE TITLE
Jetpack Dashboard: Scan card layout looks bad when threats are found

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#14914]
#### Steps to reproduce the issue

1. purchase a Jetpack plan 
2. install/activate VaultPress
3. Go to the Jetpack AAG dashboard in wp-admin 
4. In Jetpack footer, click "Dev Tools", and then click the button for "threats"
<img width="480" alt="Screen Shot 2020-03-06 at 1 56 32 PM" src="https://user-images.githubusercontent.com/7129409/76113550-5b5f2180-5fb2-11ea-9271-671328dac3d6.png">
5. Look at the scan card

#### What I expected

The scan card to be in style 😎 

#### What happened instead
The scan card doesn't look great 

![image (9)](https://user-images.githubusercontent.com/7129409/76113471-34a0eb00-5fb2-11ea-8616-e7434dd6ed99.png)

**Comment by sergeymitr** [comment]
@dereksmart how does it look?
Any other suggestions on the UI?

<img width="536" alt="Screen Shot 2020-03-19 at 1 44 33 PM" src="https://user-images.githubusercontent.com/1341249/77103227-12629080-69e8-11ea-892b-ce828f674c9d.png">
