### ISSUE TITLE
WhatsApp Share Button Not appearing on AMP Pages

### ISSUE THREAD

**Issue by SanjayKumarMonu** [Automattic/jetpack#14926]
Hi Jetpack Developers,

Sanjay Here. First of all I would like to congratulate you guys for buiding such a wonderful plugin.

Well, as everyone says, nobody is perfect so as the Jetpack plugin. Recently, I have enabled AMP on my website and came across to see that some of the Jetpack sharing buttons are not appearing on AMP pages. Take WhatsApp Sharing button as an example.

I have enabled Jetpack Social Sharing feature (I call it that way) on my website also have drag and dropped WhatsApp Sharing button in the sharing configuation in Jetpack Plugin. However, the WhatsApp Sharing button doesn't appear in AMP post pages.

Hope you guys resolve it as WhatsApp is one of the most engaging sharing platform out there where a user like to share a content the most.

Regards,
Sanjay

**Comment by jeherve** [comment]
Related: #12639

**Comment by SanjayKumarMonu** [comment]
Hi,

Thanks for Including **WhatsApp button** to work in the **Native AMP** (also called **_AMP First_** or the **_Standalone Mode_**). However, In the same thread I couldn't find anything about the inclusion of Jetpack **Like** Button in the Native AMP pages.

Could you please tell me whether the Like button is also going to be included in the **8.7** release?

Regards,
Sanjay
