### ISSUE TITLE
Consolidate the Button component implementations for use in blocks

### ISSUE THREAD

**Issue by pablinos** [Automattic/jetpack#14935]
#### The problem

We currently have three implementations of a button component that are used to add buttons to some of the blocks. A common pattern is to have a button block style as well as an inline style for embed blocks like [Eventbrite](https://github.com/Automattic/jetpack/blob/bf3e4cca0925175b92ee7e05df6b65046b3d784f/extensions/blocks/eventbrite/edit.js#L31) and [Calendly](https://github.com/Automattic/jetpack/blob/bf3e4cca0925175b92ee7e05df6b65046b3d784f/extensions/blocks/calendly/edit.js#L33). A button is also used as an InnerBlock of [the contact form](https://github.com/Automattic/jetpack/blob/bf3e4cca0925175b92ee7e05df6b65046b3d784f/extensions/blocks/contact-form/components/jetpack-contact-form.js#L26) and similarly with the [Revue block](https://github.com/Automattic/jetpack/blob/bf3e4cca0925175b92ee7e05df6b65046b3d784f/extensions/blocks/revue/edit.js#L25). It's also used with the MailChimp and Recurring Payments blocks.

The main [`SubmitButton` implementation](https://github.com/Automattic/jetpack/blob/bf3e4cca0925175b92ee7e05df6b65046b3d784f/extensions/shared/submit-button.js) has got out of sync with the core button block component and doesn't have the same features. The other two implementations were an attempt to remedy this, with [the version used in the Revue block](https://github.com/Automattic/jetpack/blob/bf3e4cca0925175b92ee7e05df6b65046b3d784f/extensions/blocks/revue/button-preview.js) being closest to the current core version.

#### Proposed solution

We have been [discussing the best approach to reusing the core button](https://github.com/WordPress/gutenberg/issues/20634) components. The current favoured solution is to adapt the button block so that the link settings UI can be turned off and then the button block can be used within block variations. This could work in some situations and needs to be explored further, but in the meantime, it seems appropriate to consolidate the implementations we currently have and get all the blocks using a button component that's as similar as possible to the core Gutenberg version.

To this end, @copons has been exploring this with [a PR to make the button used in the Revue block shared](https://github.com/Automattic/jetpack/pull/14920), and another [PR that uses this shared component in the other blocks](https://github.com/Automattic/jetpack/pull/14931).

This issue is to track progress on those PRs as well as other possible solutions within Gutenberg.

**Comment by pablinos** [comment]
Just linking to [@copons comment that summarises the situation](https://github.com/Automattic/jetpack/issues/14761#issuecomment-591413060). The plan is to combine #14630 and #14761 with the new #14920 and #14931

**Comment by Copons** [comment]
Thanks for wrangling this @pablinos!
I'll try to add the Calendly button (based upon #14761) in the `Button` example PR (#14931) and see what happens, and then update the `Button` main PR (#14920) with the needed changes.

**Comment by creativecoder** [comment]
We have a series of issues for updating each individual block to use this component, so I'm going to close this issue.

https://github.com/Automattic/jetpack/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BBlock%5D+Button%22
