### ISSUE TITLE
Upgrade Nudge Tracking

### ISSUE THREAD

**Issue by scruffian** [Automattic/jetpack#14949]
#### Is your feature request related to a problem? Please describe.
We have tracking on our UpgradeNudge when it is displayed in the editor, but on the frontend of the site there is no tracking.

#### Describe the solution you'd like
We should add tracking so that we can see the performance of the UpgradeNudge on the front end

#### Describe alternatives you've considered
Since the nudge only shows to admin users who will already have seen it in the editor, we might decide that the effort needed here doesn't outweigh the benefits.

#### Additional context
C03DKP1JP/p1583930346148900-slack
p4qSXL-32Z-p2

**Comment by davemart-in** [comment]
Let's keep all keyring issues on the Explorers backlog.

**Comment by scruffian** [comment]
This is nothing to do this keyring :)

**Comment by retrofox** [comment]
I think this issue doesn't make sense anymore, since

1) `Upgrade Nudge` has been removed completely from the app
2) `Update Banner` is not shown in the front-end.

Is it correct?

**Comment by scruffian** [comment]
We still have the component in the app: https://github.com/Automattic/jetpack/blob/dcfa5ca8bdfc31aacec107aec27bb24357d6cdac/extensions/shared/components/upgrade-nudge/index.jsx

If it's not used any more then lets remove it :)

**Comment by retrofox** [comment]
> If it's not used any more then lets remove it :)

it sounds like a follow-up task. Glad to take a look when I have the chance. What about this one? 😅

**Comment by scruffian** [comment]
I'm not convinced it's not used: https://github.com/Automattic/jetpack/search?q=render_upgrade_nudge

**Comment by retrofox** [comment]
fair enough. I think it isn't rendered in the front-end anymore. [Updated the comment](https://github.com/Automattic/jetpack/issues/14949#issuecomment-714718936). If so, I think this issue doesn't make sense. Maybe I'm missing something.

**Comment by scruffian** [comment]
Yeah looks like you're right I don't see it in the frontend.
