### ISSUE TITLE
Subscriptions: Allow time delays for emails

### ISSUE THREAD

**Issue by wpyb** [Automattic/jetpack#1494]
For blog administrators it might be useful to set a general time delay for subscription emails.

**Comment by nicolinuxfr** [comment]
Not a bad idea I think ! Not a long delay, but one or two minutes would be enough to correct big problems before emails are sent.

**Comment by jeherve** [comment]
What would be the goal behind the delay?

If it's to fix mistakes, I'm not convinced delaying emails is the right answer to that problem. It might be best to preview your drafts before to publish them, or use the "Pending Review" status and have someone else review your posts before you publish them.

**Comment by wpyb** [comment]
It is to fix mistakes in case you clicked accidentally on the publish button.

**Comment by jeherve** [comment]
How about using a plugin that will ask you to confirm before to really publish instead?
Here are 2 examples I found in the plugin repository:
- https://wordpress.org/plugins/publish-confirm/
- https://wordpress.org/plugins/are-you-sure/

**Comment by nicolinuxfr** [comment]
Well, you're right, I had not thought of this. I'd still like a small delay, just to check if everything is OK, but I understand your point.

I'd rather have the post thumbnail displayed in the mail, if I could choose one thing to update on this matter. :-)

**Comment by jeherve** [comment]
> I'd rather have the post thumbnail displayed in the mail, if I could choose one thing to update on this matter. :-)

Yes, that's on our roadmap, that's something we'd like to add for both WordPress.com sites and Jetpack sites. I don't have an ETA yet, though.

**Comment by nicolinuxfr** [comment]
Oh, great news if it's in progress !

**Comment by wpyb** [comment]
Thanks, the plugin "Publish confirm" is a good alternative for this use case.
