### ISSUE TITLE
Search: Clearing filters when no search doesn't show all results

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#14956]
1. Go to a page with just filters: http://gibrown.wpsandbox.me/demo?post_types=page
2. Then clear the filters
3. The results and filters don't get updated

<img width="1204" alt="Screen Shot 2020-03-11 at 12 17 52 PM" src="https://user-images.githubusercontent.com/820871/76449907-8a024100-6392-11ea-94ae-41a2c4777275.png">

<img width="1088" alt="Screen Shot 2020-03-11 at 12 18 02 PM" src="https://user-images.githubusercontent.com/820871/76449913-8cfd3180-6392-11ea-8752-7e5cd0a2b3c8.png">

**Comment by jsnmoon** [comment]
This has been fixed.
