### ISSUE TITLE
Premium block: "paid" word is off in the inserter

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#14977]
When opening the block inserter via `/` in Gutenberg 7.7, the "paid" word seems to be off somehow:

<img width="293" alt="Screenshot 2020-03-13 at 15 58 29" src="https://user-images.githubusercontent.com/87168/76627428-ac878c00-6543-11ea-8bc9-07940c501155.png">
<img width="336" alt="Screenshot 2020-03-13 at 15 57 18" src="https://user-images.githubusercontent.com/87168/76627432-adb8b900-6543-11ea-88a5-0b3731905543.png">
<img width="328" alt="Screenshot 2020-03-13 at 15 57 12" src="https://user-images.githubusercontent.com/87168/76627434-ae514f80-6543-11ea-8609-d3eaa3b4067a.png">

I don't know if this is a core Gutenberg issue or something in our block titles, but it's worth investigating.

#### Steps to reproduce the issue

1. With Gutenberg 7.7 on WordPress.com free simple site, press `/`
2. Observe paid plan names

cc @artpi @Automattic/ajax @Automattic/explorers

**Comment by simison** [comment]
Prolly something in core since I see the same problem in other menus with long texts:

<img width="431" alt="image" src="https://user-images.githubusercontent.com/87168/76629295-b8288200-6546-11ea-9d06-64a4889ad746.png">

**Comment by Copons** [comment]
Yeah this must be something in Core, because we don't really do anything particular with the block names AFAIK.

Also for some reasons, in my test the second line gets slightly cut off (noticeable with the "p" in "paid"):
<img width="271" alt="Screenshot 2020-03-13 at 15 37 12" src="https://user-images.githubusercontent.com/2070010/76636427-f02cc680-6540-11ea-9907-1718271cd5f6.png">

**Comment by creativecoder** [comment]
@Automattic/explorers when you start this one, since it seems to be an issue with Core, please open an issue in Core and we'll solve it there, if possible.

**Comment by Copons** [comment]
I've opened a Core PR to address this: https://github.com/WordPress/gutenberg/pull/20962

**Comment by Copons** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/20962 💃

**Comment by simison** [comment]
Thank you @Copons for jumping into it! 🙌
