### ISSUE TITLE
Simple Payments: Alfred hotkey converts block to a paragraph!

### ISSUE THREAD

**Issue by scruffian** [Automattic/jetpack#14974]
#### Steps to reproduce the issue

1. Add a Simple Payments block
2. Add your email address via an Alfred hotkey
3. The block is transformed to a paragraph block

#### What I expected
I expected it to insert a simple playments block!

**Screenshots**
![Mar-13-2020 13-29-19](https://user-images.githubusercontent.com/275961/76625269-c79bd100-652e-11ea-9c12-23123b1620e4.gif)

**Comment by jeherve** [comment]
closing as duplicate of #11906
