### ISSUE TITLE
Markdown block: buttons lost visual CSS with Gutenberg 7.7

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#14978]
Testing with Gutenberg 7.7 on WordPress.com simple sites, I see this:

<img width="663" alt="image" src="https://user-images.githubusercontent.com/87168/76629572-29683500-6547-11ea-9296-6874bcd6eb54.png">

I expected it to look like core HTML block:

<img width="402" alt="image" src="https://user-images.githubusercontent.com/87168/76629610-3b49d800-6547-11ea-986b-272d16462b95.png">

**Comment by jeherve** [comment]
Noting that this may get fixed by #14446.

**Comment by apeatling** [comment]
Let's wait for #14446 to merge and then tackle this if it's still an issue. Moving to blocked until that merges.

**Comment by jeherve** [comment]
It seems it's still an issue, unfortunately.
