### ISSUE TITLE
Amazon block: Preview button and input misaligned

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#14980]
Preview button and input are misaligned on Amazon block with Gutenberg 7.7, and Varia theme on WordPress.com simple site:

<img width="825" alt="Screenshot 2020-03-13 at 16 32 45" src="https://user-images.githubusercontent.com/87168/76630233-5b2dcb80-6548-11ea-8d3b-a096e419103a.png">

#### Steps to reproduce the issue

1. Just add Amazon block to block editor on Gutenberg 7.7

cc @Automattic/explorers

**Comment by simison** [comment]
Cannot say if this has changed in 7.7 vs older versions, but it could be improved — there's either too much space in different parts and not enough space to read the search results:

<img width="807" alt="image" src="https://user-images.githubusercontent.com/87168/76630338-87e1e300-6548-11ea-9bdd-19d9a3ada4e3.png">

**Comment by scruffian** [comment]
The Amazon block is current on hold since we can't get access to their API. I don't think this was ever aligned in the first place :)

**Comment by simison** [comment]
Oh okay, so I won't do further testing. :-) Feel free to close this!
