### ISSUE TITLE
Shortlinks: wp.me always redirects to http, even if site uses HTTPS

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1498]
Steps to reproduce:
1. Connect a full-https site to WordPress.com via Jetpack.
2. Check the wp.me shortlink of one of the posts. It redirects to the http shortlink. Here is an example:

``` bash
$ curl -I http://wp.me/p4LPVl-3PY
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Wed, 14 Jan 2015 13:35:28 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Location: http://www.liveroomescape.com/?p=14754
```

Reported here:
https://wordpress.org/support/topic/publicize-facebook-links-are-not-secure-for-https-site?replies=3

**Comment by isaumya** [comment]
Yes this indeed an wired bug. Looking to be fixed in the next update.

**Comment by alexryans** [comment]
Is this bug still being looked at? I'm still seeing it in the latest version of WordPress and links posted to Facebook and Twitter are showing a `http://` link, rather than `https://`.

**Comment by isaumya** [comment]
@alexryans Very good question. I've almost forgot that I've ever replied on this issue as there is almost no replies. Besides the time shows "Future", which could be in 2166 :wink:  when Vandal Savage will concur the earth :smile:

**Comment by alexryans** [comment]
As a fan of Legends of Tomorrow, I 100% appreciate that reference, @isaumya. I do, however, hope it's fixed much sooner than that!

**Comment by jeherve** [comment]
@alexryans @isaumya We haven't looked at it yet, but we'll see if we can get this resolved in a future release. We'll update this issue as soon as we make progress.

You can rest assured, we'll get this fixed before 2166. If all else fails, we'll have The Flash go back in time and fix the bug on January 13, 2015, before I even opened it ;)

**Comment by jeherve** [comment]
This has now been fixed.
