### ISSUE TITLE
Jetpack Mobile: A case where clicking "View Full Site" in footer loads mobile site

### ISSUE THREAD

**Issue by michiecat** [Automattic/jetpack#150]
This was spotted on http://dentedreality.com.au. Clicking the "View Full Site" link in the footer just reloads the mobile site instead of the full site.

The link works fine on WP.com blogs. I tested with a self-hosted blog running the latest version of Jetpack, and I wasn't able to reproduce. I will test on some other sites to see if I can reproduce the issue. 

Is anyone else having this problem on their self-hosted blogs with Jetpack mobile?

**Comment by chaselivingston** [comment]
Seeing this on http://bethesdacathedral.org/ running JP 3.3 and WP 4.1. I'm also able to reproduce on my JP sandbox running JP master and WP 4.1.

**Comment by dereksmart** [comment]
I was able to replicate with WP Super Cache both activated, and installed but not deleted.  Once I deleted it, the link worked properly.

**Comment by dereksmart** [comment]
Also worked if I just turn off caching https://cloudup.com/cnlLiL-U1ZO

**Comment by samhotchkiss** [comment]
While this looks like a legitimate issue, it also seems to affect a relatively small number of users and is not in line with our current goals for Jetpack, so I'm closing ATM-- if we end up with 5 more reports after this point, please reopen.
