### ISSUE TITLE
"wp_print_styles should not be used to enqueue styles"

### ISSUE THREAD

**Issue by pathawks** [Automattic/jetpack#1500]
Is there a reason [Jetpack is using `wp_print_styles`](https://github.com/Automattic/jetpack/blob/648437e8f05048ff4e690fcc7c1569e566de3fb3/class.jetpack.php#L489) to add it's CSS, rather than the recommended `wp_enqueue_style`?

```php
add_action( 'wp_print_styles', array( $this, 'implode_frontend_css' ), -1 );
```

**Comment by georgestephanis** [comment]
That's intentionally being done late at wp_print_styles to give the actual enqueued components that the imploded css replaces a chance to be accounted for or dequeued.  (if they all get dequeued, the implode function no longer adds the concatenated one)

**Comment by teohhanhui** [comment]
This forces me to hook into wp_print_styles as well, to make sure my child theme's stylesheet goes after Jetpack's CSS. In my case, to style the social sharing buttons...

**Comment by jeherve** [comment]
> to style the social sharing buttons

Could you work around it by being more specific in your CSS, so the load order doesn't matter?

**Comment by teohhanhui** [comment]
Yes, of course I can, but that's merely a workaround (of course, having to
use `!important` is even worse but that's another issue).

**Comment by teohhanhui** [comment]
Yes, of course I can, but that's merely a workaround (of course, having to
use `!important` is even worse but that's another issue).

**Comment by jeherve** [comment]
I'd recommend against using `!important`, being more specific should be enough.

We can't really hook earlier, as @georgestephanis [mentioned above](https://github.com/Automattic/jetpack/issues/1500#issuecomment-70103601), but if you don't want to have to hook into `wp_print_styles` or update your CSS to be more specific, you could deactivate Jetpack's CSS concatenation, like so:
`add_filter( 'jetpack_implode_frontend_css', '__return_false' );`

Once you do so, Jetpack stylesheets will return to their previous behaviour and be enqueued through `wp_enqueue_scripts`.

**Comment by teohhanhui** [comment]
> I'd recommend against using `!important`
That's what Jetpack does in its CSS (for the social sharing buttons at least), prompting some to even disable the loading of 
the default stylesheet. I don't know the history of why the "sharedaddy_disable_resources" option was added, but could it be related to that as well?

**Comment by jeherve** [comment]
> That's what Jetpack does in its CSS (for the social sharing buttons at least)

That's a problem indeed. I created an issue for that problem here: #1922

> I don't know the history of why the "sharedaddy_disable_resources" option was added, but could it be related to that as well?

It was added to make it easier for site owners who wanted to completely redesign the sharing buttons. The option makes it easier for them to change the look of the buttons without having to overwrite every single style with CSS.
