### ISSUE TITLE
Custom Draggable Marker for Map Block

### ISSUE THREAD

**Issue by Chihueiliu** [Automattic/jetpack#15007]
#### Is your feature request related to a problem? Please describe.
It'd be helpful to have the ability to drag and drop the marker onto a specific point on a map for when/if I am unable to find my location using the search feature. 

#### Describe the solution you'd like
Mapbox GL JS allows you to create a draggable marker - https://docs.mapbox.com/mapbox-gl-js/example/drag-a-marker/

#### Describe alternatives you've considered

N/A

#### Additional context

N/A

**Comment by richtabor** [comment]
I think it's ok not doing this.
