### ISSUE TITLE
Jetpack Dev tools: support Backup plans

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#15006]
#### Steps to reproduce the issue

1. Go to the plans page on a connected site
2. Click on 'Dev Tools' in the footer menu
3. Select either the "Jetpack Backup Daily" or the "Jetpack Backup Realtime" plan

#### What I expected
I'd expect to see either of these cards displayed in the UI indicating what plan i'm on:

<img width="546" alt="Screen Shot 2020-03-11 at 5 50 45 PM" src="https://user-images.githubusercontent.com/4044428/76474363-0d3a8b80-63c1-11ea-9822-ef98486a5d45.png">

<img width="546" alt="Screen Shot 2020-03-11 at 5 50 39 PM" src="https://user-images.githubusercontent.com/4044428/76474375-14fa3000-63c1-11ea-9dc8-05a24e260ced.png">

#### What happened instead

Nothing appeared in the UI to indicate my plan.

( initially reported in #14961 )

**Comment by jeherve** [comment]
This has now been implemented.
