### ISSUE TITLE
Instant Search: Add images to search results

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#15013]
Add a version of the search results that display featured images.

An example layout:

<img width="915" alt="screen_shot_2020-03-17_at_6 27 00_am" src="https://user-images.githubusercontent.com/820871/76867617-65dbaf80-682b-11ea-936f-3c3f62d4f636.png">

This is a bit different from the WIP layout we have for products in #14017 

A bit closer to the "engagement" layout that we have been planning to steal from WP.com Reader. See #13350

**Comment by jeremypaavola** [comment]
Requested in 2963990-zen

**Comment by rickalee** [comment]
Any movement on this feature? Expecting to use Instant Search in upcoming redesign.

**Comment by jsnmoon** [comment]
@anaemnesis & @rickalee: I have an open PR that implements this new result format in #16179.

**Comment by tmmbecker** [comment]
3085068-zen

Offered to notify when this is released.
