### ISSUE TITLE
Podcast Player: URL validation too strict.

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#15022]
The URL validation for Podcast Player rejects URLs with trailing slashes, like https://distributed.blog/category/podcast/feed/

Introduced in https://github.com/Automattic/jetpack/pull/14948/commits/0aaa7c209002705d80fd16c66da495ee7e68c6f9

Being careful about what types of URLs we accept is great! At the same time, let's also give SimplePie a chance to help decide what's a valid feed and what's not.

**Comment by getdave** [comment]
We should wrap in `trailingslashit`

https://codex.wordpress.org/Function_Reference/trailingslashit

**Comment by getdave** [comment]
> At the same time, let's also give SimplePie a chance to help decide what's a valid feed and what's not.

I would still say we should not trust code we don't "own" to validate our attributes. I still prefer adding the validation within our code even if that's duplicating something that happens in SimplePie.

**Comment by marekhrabe** [comment]
I don't know how I feel about adding a trailing slash. Will it 100% work all the time? 

Some servers could interpret that as a different request. I definitely know most caching proxies will treat it as two different requests. 

What is the root cause? It feels strange that URL without a trailing slash fails some sort of validity check. There must be a reason

**Comment by obenland** [comment]
> What is the root cause? It feels strange that URL without a trailing slash fails some sort of validity check. There must be a reason

Great question. Initially I wondered if it depends on the `home_url` setting of the hosting site, but now I'm having a hard time reproducing the bug in the first place, so I'm not sure.

Has anyone else run into this bug yet?

**Comment by getdave** [comment]
I've tested this again on `master` and I can no longer replicate. 

![Screen Capture on 2020-03-26 at 10-25-20](https://user-images.githubusercontent.com/444434/77636590-412eb880-6f4c-11ea-9819-2372fdabd774.gif)

Inclined to think this was some kind of anomaly during @obenland's testing.

If you can reproduce @obenland I'm happy to investigate further. If not please feel free to close.

**Comment by marekhrabe** [comment]
I have not tested anything now but I can say I have not experienced this issue during my development.

**Comment by getdave** [comment]
No update so I'm going to close this one.
