### ISSUE TITLE
Infinite Scroll: Automatic scrolling not working on 2020 or 2019

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#15027]
#### Steps to reproduce the issue

1. Enable the infinite scroll module on your site, and set it to "Load more posts as the reader scrolls down" (Jetpack settings page)
2. Create a 3 posts and set the posts per page to 2 in Settings -> Reading
3. Go the the home page and scroll down

For a limited time, you can observe the issue here:
https://whole-landfowl.jurassic.ninja

#### What I expected
I'd expect the 3rd post to load automatically.

#### What happened instead
There was instead an "older posts" button

**Screenshots**

![Screen Shot 2020-03-17 at 6 30 06 PM](https://user-images.githubusercontent.com/2694219/76908024-183c6280-687e-11ea-8b26-167225b3cf15.png)

The issue is present on both 2020 and 2019 themes.

**Comment by jeherve** [comment]
I believe that's to be expected. We force the `type` so the footer widgets can be accessed:

> scroll is the default, but if a theme has footer widgets, this could be overridden to click so the widgets are accessible.
-- http://jetpack.com/support/infinite-scroll/

https://github.com/Automattic/jetpack/blob/204361576070326f20ffdb1cab6a9bc1c917783b/modules/theme-tools/compat/twentytwenty.php#L23

**Comment by roccotripaldi** [comment]
Thanks for explaining that. Ideally we wouldn't show the option on the settings page if the theme doesn't support it, but i suppose that's a different can of worms.
