### ISSUE TITLE
(3P) Podcast Player: Add Schema markup

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#15039]
#### Is your feature request related to a problem? Please describe.
As we expand on the display of those episodes, @jeherve wonders if it may be worth looking into adding schema.org markup to the display: https://schema.org/PodcastEpisode

See https://github.com/Automattic/jetpack/pull/14989#pullrequestreview-377167519

**Comment by marekhrabe** [comment]
> All markup should use logical and semantic markup for "podcast" with "podcast episode" items. 

also mentioned in my [tech specs](https://github.com/Automattic/Dotcom-roadmap/issues/100#issuecomment-589759810) 

Thanks for making an issue! After this iteration, I'll come back, update it and make sure to raise issues for other things that were not addressed

**Comment by marekhrabe** [comment]
Testing tool https://search.google.com/structured-data/testing-tool/u/0/

**Comment by retrofox** [comment]
> Testing tool https://search.google.com/structured-data/testing-tool/u/0/

[Distributed podcast feed](https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fdistributed.blog%2Fcategory%2Fpodcast%2Ffeed%2F)

**Comment by obenland** [comment]
I think the one question I’d have would be about duplicated content.
If we added that markup, would we suggest the embedding site to be the root site for these podcast episodes? Not sure if you have more insight there @jeherve?

**Comment by jeherve** [comment]
That's a good question. Since the markup includes data about the podcast, I don't know if that would really be an issue, Google may have enough issue to figure everything out?

**Comment by obenland** [comment]
I'd just like to avoid a situation where the embedding site becomes the authority on the podcast they're embedding :) 
And frankly I don't know enough about schema markup to go one way or the other

**Comment by marekhrabe** [comment]
I'm more and more inclined towards closing this, since we are not the origin of the content. I don't think it's reasonable to add markup that looks like we are the source of the podcast, just like a blog post with a youtube video embedded wouldn't mark the whole page with markup suggesting it's a video.
