### ISSUE TITLE
Podcast Player: List numbers displayed oddly

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#15037]
The list numbers seem to be off for in the editor (using Chrome, Twenty Twenty, WP 5.3.2, **no Gutenberg**):

**Screenshots**
![image](https://user-images.githubusercontent.com/426388/76999428-e77c2c00-6956-11ea-8075-465a1839b8f8.png)

See https://github.com/Automattic/jetpack/pull/14989#pullrequestreview-377167519

**Comment by jeherve** [comment]
Closing this as it's been fixed by the recent style iterations.
