### ISSUE TITLE
Podcast Player: Frontend not functional in IE11

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#15038]
In IE11, clicking on a podcast episode in the player redirects you to the page where the episode lives.

See https://github.com/Automattic/jetpack/pull/14989#pullrequestreview-377167519

**Comment by marekhrabe** [comment]
Thanks for making an issue - we've only had a card for it on the iteration board. Root cause is is the usage of `Element.prototype.closest` and it should be fairly easy to either shim or rewrite using more low-level functions.
