### ISSUE TITLE
Block: Subscription Form Improvements

### ISSUE THREAD

**Issue by apeatling** [Automattic/jetpack#15076]
Current state:

<img width="750" alt="screenshot-2020-03-19-at-22 00 34" src="https://user-images.githubusercontent.com/1464705/77200249-6e401e80-6aa7-11ea-84f9-a08a5a8d3105.png">

List from @mtias:

- [x] Improve the button design, make the button and input field look like they belong together
- [x] The toggle button for subscriber count should not be in the canvas, move to sidebar
- [x] Provide further customization options beyond the button color (outline style, radius control, font-size, layout, width, etc)
- [x] When toggling the “show subscriber count” it looks like three unrelated elements on the page
- [x] No period at the end of the subscriber count sentence

We need to be able to support a block pattern such as:

![image-7](https://user-images.githubusercontent.com/1464705/77200431-c24b0300-6aa7-11ea-92ce-773849da6423.png)

@iamtakashi @pablohoneyhoney Do we have any other block patterns using this block for reference?

**Comment by pablohoneyhoney** [comment]
Some initial sketches

<img width="860" alt="Subscription Form" src="https://user-images.githubusercontent.com/25516611/77204942-30082680-6aca-11ea-80d1-04bcc89a5b65.png">
<img width="860" alt="Subscription Form-2" src="https://user-images.githubusercontent.com/25516611/77204937-2e3e6300-6aca-11ea-844a-2c40e3c831a9.png">
<img width="860" alt="Subscription Form-1" src="https://user-images.githubusercontent.com/25516611/77204939-2f6f9000-6aca-11ea-9edd-6522d4fbb709.png">
<img width="860" alt="Subscription Form-3" src="https://user-images.githubusercontent.com/25516611/77204933-2d0d3600-6aca-11ea-981c-7077a7ea6b98.png">

**Comment by mtias** [comment]
A border radius control that applies to the input and the button would make sense as a start.

**Comment by iamtakashi** [comment]
I like the input field and the button to be next to each other makes sense most of the time, especially the width isn't a concern. But when the available width is restricted (like a sidebar), the current pattern (the field and the button to be on its line) would leave a wider input field. It should accommodate both cases.

<img width="720" alt="Screenshot 2020-03-21 at 00 19 44" src="https://user-images.githubusercontent.com/908665/77215174-9dd44280-6b0a-11ea-95ed-890248c0472c.png">

**Comment by apeatling** [comment]
Thanks for all the above, I'll start working on this today.

**Comment by obenland** [comment]
Opening an English-language post containing the block in wp-admin with the user locale set to a different language, breaks the block. pbNZNv-1Q-p2
In my case user locale was German.
/cc @iamtakashi

**Comment by apeatling** [comment]
Based on the pattern designs above, I think these are the settings that should accommodate all of them:

<img width="1717" alt="Screen Shot 2020-03-25 at 3 57 36 PM" src="https://user-images.githubusercontent.com/1464705/77593513-8c47bd80-6eb1-11ea-8fc7-ee419bfc22ee.png">

The exception being the subscriber count placement, which I will handle separately.

@mtias Interested in your feedback here regardless of where these settings end up (sidebar or toolbar). Looking at the way color panels are handled it looks like it could be difficult to separate color settings out into multiple panels. I do feel as though organizing settings by what you are changing is easier to parse, than trying to include multiple color settings in one panel.

**Comment by mtias** [comment]
Nice work, this looks good. Just a few notes:

- The border color should probably be a single control and apply to both elements for concordance.
- The text color on the input field seems also possibly unnecessary: does it apply to the placeholder text or what the visitor would type? In any case, it seems like something that should be set and not controlled by the user.
- I'd simplify some of the labels: "Background Settings" -> "Background Color" and then "Email Field Background Color" to just "Email Field" and "Submit Button".
- I like the space controls. We might be getting some better tools in the short term in Gutenberg core, but this works for now.

**Comment by apeatling** [comment]
> The border color should probably be a single control and apply to both elements for concordance.

This is fine for most of the patterns above, but these two I wondered about:

<img width="384" alt="Screen Shot 2020-03-26 at 9 13 42 AM" src="https://user-images.githubusercontent.com/1464705/77669541-29523700-6f42-11ea-89ef-cf05b7e74087.png">

> The text color on the input field seems also possibly unnecessary: does it apply to the placeholder text or what the visitor would type? In any case, it seems like something that should be set and not controlled by the user.

That seems fine to me. I was considering it controlling both placeholder (at a lower opacity) and the actual text color. Fine to leave it alone right now.

> I'd simplify some of the labels: "Background Settings" -> "Background Color" and then "Email Field Background Color" to just "Email Field" and "Submit Button".

👍 

> I like the space controls. We might be getting some better tools in the short term in Gutenberg core, but this works for now.

That sounds great, we can always whip these out later.

**Comment by apeatling** [comment]
Updated settings based on the above:

<img width="1711" alt="Screen Shot 2020-03-26 at 9 21 31 AM" src="https://user-images.githubusercontent.com/1464705/77670309-41768600-6f43-11ea-92e0-4f75f4ad5ece.png">

**Comment by pablohoneyhoney** [comment]
Can we refrain _Custom_? Seems too technical. 

Here it's unnecesary, as it's obvious with the first label _Text size_
<img width="438" alt="Screen Shot 2020-03-26 at 12 25 49 PM" src="https://user-images.githubusercontent.com/25516611/77670760-01bc9800-6f5d-11ea-9904-a8f908e27c64.png">

For color, what users do is _Edit_ or _Add color_ instead of _Custom_. More natural. 
<img width="440" alt="Screen Shot 2020-03-26 at 12 26 05 PM" src="https://user-images.githubusercontent.com/25516611/77670758-01bc9800-6f5d-11ea-8cc2-2b760707b7eb.png">

**Comment by mtias** [comment]
> I could see a scenario like the first one where you might want a bordered button, with a background color only textfield.

Right, perhaps we should support it but not expose it in the UI. My worry is that, while it allows some of the patterns we might want to do, it will also lead to some weird combinations by users.

**Comment by apeatling** [comment]
@pablohoneyhoney This is a core component, so this wording is present on all blocks that use font sizing. It would be good to open a core Gutenberg ticket for the suggestion so it can change everywhere.

The PR https://github.com/Automattic/jetpack/pull/15107 now includes all of the settings discussed above.

**Comment by kjellr** [comment]
Just wanted to share a pattern that came up in a theme design @melchoyce is working on: 

<img width="455" alt="Screen Shot 2020-04-16 at 1 52 56 PM" src="https://user-images.githubusercontent.com/1202812/79489662-a0cb3180-7fe9-11ea-94d2-cd392536d6d9.png">

Structurally, this is a bit similar to this pattern that @pablohoneyhoney shared above. Just with some different styles: 

<img width="373" alt="Screen Shot 2020-04-16 at 1 53 36 PM" src="https://user-images.githubusercontent.com/1202812/79489723-bcced300-7fe9-11ea-9d85-763a85b6e32d.png">

In any case, it would be really cool to be able to create this today using this block. Glad to see there's work happening on this. 👍

**Comment by apeatling** [comment]
The pattern that Pablo shared is possible. The one from Mel is slightly thicker. It could be done with control over the border thickness of each side of the button, but the space above and below the narrow border complicates it a bit.

**Comment by apeatling** [comment]
It could be done with a "Button inside of text field" option, and then control over individual button border sides.

**Comment by kjellr** [comment]
> ... but the space above and below the narrow border complicates it a bit.

Yeah, in the near-term I think it's totally understandable that a little refinement like might be omitted. 👍

**Comment by mtias** [comment]
Yes, I think this one falls a bit in the realm of "the theme needs to supply some custom CSS".

**Comment by jeherve** [comment]
Related: #15454
