### ISSUE TITLE
Related Posts: Adjust margins for Varia and Varia Child Themes

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/jetpack#15089]
Related Posts are appearing on the far left for sites using the Varia theme or a Varia Child theme from WordPress.com.

This was previously reported and resolved for Twenty Twenty: https://github.com/Automattic/jetpack/issues/14020

#### Steps to reproduce the issue

1. Activate Varia or a Varia child theme on a self-hosted or WordPress.com Business plan site (with hosting configuration features enabled).
2. Go to `/wp-admin/admin.php?page=jetpack#/traffic` and ensure that Related posts are activated
3. Ensure your site has posts to populate the related posts module.
4. View a post, see error.

#### What I expected
For the related posts to be centered.

#### What happened instead
Related posts are to the left due to the margin styles for `#jp-relatedposts`

#### Screenshot
![image](https://user-images.githubusercontent.com/4887830/77342066-05a2ad00-6d06-11ea-8266-d8a57984c7e5.png)

#### WordPress.com Themes Impacted

- Varia
- Alves
- Balasana
- Barnsbury
- Brompton
- Coutoire
- Dalston
- Exford
- Hever
- Leven
- Mayland
- Maywood
- Morden
- Redhill
- Rivington
- Rockfield
- Shawburn
- Stow
- Stratford

**Comment by jeherve** [comment]
This is most likely something that will need to be handled by the themes themselves. We do try to support the default WordPress themes in Jetpack, but we can't reasonably offer custom stylesheets for all the themes out there.

https://github.com/Automattic/jetpack/blob/5e411ee98397287583c658e77cf660b5daf23f77/modules/theme-tools.php#L40-L45

For the rest of the themes out there, we leave each theme customize the look of each Jetpack element to fit their needs.

**Comment by JoshuaGoode** [comment]
Thanks for looking, I'll get a report going for Varia and its child themes on https://github.com/Automattic/themes/
