### ISSUE TITLE
Simple Payments block: INR is not listed as a currency in the drop-down

### ISSUE THREAD

**Issue by aisajib** [Automattic/jetpack#15083]
After I found out that the INR currency is not listed on the Simple Payment block, I was informed, and found it to be true, that the Simple Payments widget actually had the INR currency as an option. 

I inserted a new Simple Payments widget and added a new button with the INR currency. While it did not work with a non-Indian PayPal account ([probably due to restrictions from PayPal](https://developer.paypal.com/docs/api/reference/currency-codes/)), it did work with an Indian PayPal account. 

That suggests to me that an Indian user can use the Simple Payments widget with the INR, but that currency is missing on the Simple Payments block. 

#### Steps to reproduce

1. Go to Customizer -> Widgets -> widget area -> Add a Widget and insert a Simple Payments widget.
2. Click on Add New.
3. Scroll down to Price and click the drop-down of currencies. 
4. INR is listed there. 
5. Open a new page/post window in the block editor and insert the Simple Payments block. 
6. The INR currency is missing from the price drop-down menu.

#### What I expected

I expected the INR currency to be available in both the Simple Payments block and the widget.

#### What happened instead

Instead, the INR option was missing on the Simple Payments block.

**Comment by jeherve** [comment]
That's unfortunately done on purpose, as support for INR is limited on PayPal. You can find out more about this here:
https://github.com/Automattic/wp-calypso/pull/28236#issuecomment-436255859

We had removed it from the widget as well for a little while (see #10581 ), but ended up adding it back for the reasons outline in #10610.

**Comment by aisajib** [comment]
Thanks @jeherve 

From the second PR: 

>we could just include them with some UI changes to set user's expectations clear that these might be problematic to use.

I wonder if there is any UI change that tells the user that these might be problematic? I did not find any indication that when inserting INR in the widget area it might be problematic.

**Comment by jeherve** [comment]
No, this hasn't been implemented yet.

**Comment by simison** [comment]
We can keep this at another issue: https://github.com/Automattic/wp-calypso/issues/41176#issuecomment-2009585389
