### ISSUE TITLE
Subscriptions: preview new post emails when editing posts

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#15086]
#### Is your feature request related to a problem? Please describe.

> What I can't do is see what the email that subscribers are going to get will look like. This is a real problem, as I have to guess how images will be positioned, and how text will be broken -- I have no control and no ability to preview. As long as the "automatic, one-time-only email" feature is in place, some way of see what it's going to look like is important. 

#### Describe the solution you'd like

- Add a feature to preview new post emails right in the post editor.
- It would be nice if we can have previews in mobile, desktop, and some popular apps like Outlook, Apple Mail, etc. 

#### Additional context

Requested in 2786370-zen

**Comment by jeherve** [comment]
This was eventually implemented in #31021.
