### ISSUE TITLE
Plans: Monthly toggle doesn't apply to Single Products

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#15094]
#### Steps to reproduce the issue

1. Navigate to `/wp-admin/admin.php?page=jetpack#/plans`
2. Click on `Monthly` at the top of the page.

#### What I expected
Monthly pricing to be shown in the Backups product card.

#### What happened instead
Yearly pricing was shown in the Backups product card.

**Screenshots**

<img width="528" alt="Screen Shot 2020-03-23 at 5 52 36 PM" src="https://user-images.githubusercontent.com/4044428/77373931-1a476b00-6d2f-11ea-8a72-f8a8d5ea384e.png">

**Comment by jsnmoon** [comment]
cc @gibrown @keoshi @AnnaMag

**Comment by keoshi** [comment]
Can confirm this is happening on single-sites that don't have a Backup Plan.

Heads up @eeeeevon13 @lucasartoni @Automattic/jetpack-voyager

**Comment by enejb** [comment]
We will tackle this next week.
