### ISSUE TITLE
My Plans: React/JS warnings in console

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#15093]
Running on master and using Chrome on a site that has Jetpack Pro.

Open /wp-admin/admin.php?page=jetpack#/my-plan

Two errors in the console:

<img width="1401" alt="Screen Shot 2020-03-23 at 5 30 57 PM" src="https://user-images.githubusercontent.com/820871/77372842-47464e80-6d2c-11ea-913b-93eb10fa91fb.png">

**Comment by jeherve** [comment]
Closing this for now since the "My Plans" page now redirects to WordPress.com.
