### ISSUE TITLE
Gutenberg: Adding Cover Block breaks WP.com Notifications

### ISSUE THREAD

**Issue by annezazu** [Automattic/jetpack#15108]
#### Steps to reproduce the issue

1. Create a new jurassic.ninja site.
2. Install the latest version of Gutenberg and connect Jetpack.
3. Turn on the [WordPress.com notification feature](https://jetpack.com/support/notifications/). 
4. Add in a few text blocks followed by the Cover block.
5. Publish the post and view it. 
6. Try to check notifications and you'll see they are cut off. 

#### What I expected

Notifications would continue working as expected. 

#### What happened instead

Video of problem: https://cloudup.com/c0TuX3fsYn7

Screenshot highlighting problem: 
<img width="226" alt="Screen Shot 2020-03-24 at 2 45 11 PM" src="https://user-images.githubusercontent.com/26996883/77480018-20e0eb80-6dde-11ea-9e4f-bc99a9603d74.png">

**Comment by jeherve** [comment]
I can't seem to be able to reproduce the issue on my end right now. I wonder if you may be running into this issue:
https://core.trac.wordpress.org/ticket/49030

Can you reproduce with a theme other than Twenty Twenty?

**Comment by annezazu** [comment]
Ah ha! You are correct. I tried testing with TwentyNineteen and couldn't replicate. Nice catch! I'll close this out.
