### ISSUE TITLE
SSO: enable SSO when user hide's login area

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1511]
Some plugins like iThemes Security have a feature that hides your login area and changes it from wp-admin to something like wplogin or something obscure of your choice.  When this feature is active, SSO doesn't display for users.

It would be neat if we could detect the login page and still enable SSO regardless of the location.

**Comment by georgestephanis** [comment]
Hrm.  I seem to recall us working with some of them, I'd be interested to see why we're not working with others.

@ChrisWiegman -- does the iThemes Security login page change not fire `login_init` on the new login page?

**Comment by ChrisWiegman** [comment]
It fires. However I haven't tested it with Jetpack SSO (in fact I no longer use the feature and we will at some point be removing it from iThemes Security). That said, Is it connecting to the login page or anything directly for that Auth @georgestephanis ?

**Comment by georgestephanis** [comment]
I believe so when it redirects back.  Some of the login page url changers redirect the old to the new, so that may be the difference.  Unsure.

But the question above seems to be more that the SSO button itself doesn't show.

I'd like to see some more testing on our end to clarify what the status quo actually is.

**Comment by samhotchkiss** [comment]
@squirk Can you do some testing on this this week?  Test single sign on against iTheme Security, Wordfence, Bulletproof WP-- any others we should hit, @georgestephanis?

**Comment by squirk** [comment]
Here's that tag from the dotorg repo: https://wordpress.org/plugins/tags/single-sign-on

**Comment by squirk** [comment]
@georgestephanis Any thoughts here?  So far, I've not seen issues with the 3 mentioned, but will test more with subsequent versions.

**Comment by ebinnion** [comment]
Closing this since last time we checked there were no issues and there have been no more reported.
