### ISSUE TITLE
Pinterest: Embeds not working

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#15112]
I tried embedding a pin, a board, and profile using the Pinterest block, and was not able to. After pasting the URL no content appeared, nor was there an error message. I also noticed the embeds are missing on WordPress.com support page: https://wordpress.com/support/embed-from-pinterest/

![image](https://user-images.githubusercontent.com/4550351/77499144-67e5e400-6ea5-11ea-9da7-d7b2cfbf7cde.png)

#### Steps to reproduce the issue

1. Start a new post or a page. (I tried on WordPress.com on free plan)
2. Add the Pinterest block.
3. Paste code to embed a pin/post/profile, for example:
https://www.pinterest.com/pin/343751384058775602/
4. No content is being embedded.

#### What I expected
For the content to appear, or to see an error message.

**Screenshots**
![23tDV1qJCV](https://user-images.githubusercontent.com/4550351/77499497-5cdf8380-6ea6-11ea-94c8-9dabddc17984.gif)

**Comment by jeherve** [comment]
I can't seem to be able to reproduce the issue right now:
![image](https://user-images.githubusercontent.com/426388/77515179-5b976200-6e78-11ea-8483-ec92eef083bf.png)


Do you happen to use an Ad blocker or privacy browser extension that may block Pinterest resources from loading? Do you see any errors in your browser console?

**Comment by alaczek** [comment]
Yep, it looks like it's my privacy settings 🤦‍♀️Sorry!
