### ISSUE TITLE
Publicize: Default custom message shows wrong instructions

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#15115]
When using Publicize the custom message box says:

> Write a message for your audience here. If you leave this blank, we'll use the post title as the message.

https://github.com/Automattic/jetpack/blob/8.3/extensions/blocks/publicize/form-unwrapped.js#L94

However, when Publicizing a post we use the sub-heading as well as partial body text:

![77529234-84772180-6e8f-11ea-9cff-cb6215ed463b](https://user-images.githubusercontent.com/88897/77535391-8974aa80-6e68-11ea-9f5b-37e2b91a8658.png)

#### Steps to reproduce the issue

1. Jetpack + Publicize enabled.
2. New post in G.
3. See the Publicize panel.

#### What I expected
Text to match actual output.

#### What happened instead
More than just the title was used.

cc: @joendotcom as the original reporter from 2793791-zen

**Comment by bisko** [comment]
@kraftbj I'm wondering if the solution should be to change the behavior or update the message in the Publicize block to say:

> Write a message for your audience here. If you leave this blank, we'll use part of the post content as the message. 

Or something of the sort?

This behavior (to use the post content as the message) has been like this for a while and I've seen customers use it often. I'm not sure if changing the behavior to match the message is a better option than changing the message to reflect the behavior?

**Comment by kraftbj** [comment]
@bisko Yeah, I wouldn't suggest changing behavior, just updating what expectations we're showing.
