### ISSUE TITLE
Gutenberg 7.7.1/7.8: Simple Payments Block is removed if pasting into the email field

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/jetpack#15121]
**Describe the bug**

**To reproduce**
1. Edit a page
2. Add a Simple Payments Block
3. Paste any text into the **Email** field
4. See that the field is removed

**Expected behavior**
The text should be pasted into the field

**Screenshots**
![Screen Capture on 2020-03-25 at 16-45-37](https://user-images.githubusercontent.com/7596032/77583927-47735500-6eb8-11ea-9a24-28eac028915d.gif)

**Desktop (please complete the following information):**
 - OS: MacOS V10.15.4 (19E266)
 - Browser Firefox
 - Version 74.0 (64-bit)

**Additional context**
- Started with Gutenberg 7.7.1. Also tested on the 7.8 edge version.
- This issue does not happen on previous versions
- Discovered in WPCOM Calypso, also tested on JN with 7.7.1 and 7.8 Gutenberg versions

**Comment by glendaviesnz** [comment]
The problem is caused by the fact that Gutenberg is using the `input` field  DOM element selectStart attribute to determine if it is a `text` input. Inputs of type `email` return null for `input` of type `email`, so the method at https://github.com/WordPress/gutenberg/blob/master/packages/dom/src/dom.js#L454 returns false, and then the copy handler does not return at https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/copy-handler/index.js#L46, and the gutenberg paste handler takes over and kills the email field.

**Comment by jeherve** [comment]
Related: #11906

**Comment by simison** [comment]
Should we temporarily make the field `type=text` at least on wpcom, if not in Jetpack?

**Comment by glendaviesnz** [comment]
> Should we temporarily make the field `type=text` at least on wpcom, if not in Jetpack?

The only other way I could see to fix in wpcom/jetpack ahead of a fix in gutenberg was to trap the copy/cut/paste events on the email field and stop propogation - [PR doing this here](https://github.com/Automattic/jetpack/pull/15143)  - but this is much more heavy handed than just changing the email field to `text` for now.

**Comment by glendaviesnz** [comment]
@simison & @jeherve  - what are your thoughts on [trapping the events](https://github.com/Automattic/jetpack/pull/15143) versus [changing field type to text](https://github.com/Automattic/jetpack/pull/15145) as a temporary fix on wpcom/jetpack. 

Trapping the events was an interesting exercise and may be useful to inform a solution in gutenberg that allows passing an extra prop to `TextControl` to indicate if native copy/paste should be preserved ... but it is probably overkill as a temporary fix. The field type change fixes the issue and email validation still works.

**Comment by simison** [comment]
Type text sounds better because of simplicity. Type email doesn't sound
that critical anyway?

**Comment by jeherve** [comment]
> Type text sounds better because of simplicity

Agreed, let's go with this for now.
