### ISSUE TITLE
Issues while setting Testimonial Page Featured Image in Customizer

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#1513]
Setting Testimonial Page Featured Image in Customizer does not work properly:
* Testimonial's archive displays featured image only when the image is uploaded. Selecting an image from Media Library has no effect (it does not change in preview and after saving options).
* Customizer does not show currently set featured image after Customizer page refresh.

![testimonials_customizer_issues](https://cloud.githubusercontent.com/assets/4550351/5793032/52b90e4a-9f34-11e4-933a-87d50ebfd921.png)

Tested with themes: Motif, Sela

**Comment by michaeldcain** [comment]
>Notice: Undefined index: page-content in /local/wp-content/themes/premium/forefront/archive-jetpack-testimonial.php on line 45

The custom control was written for the dotcom Customizer and before some recent Customizer changes. I'll take a look.
