### ISSUE TITLE
Function to trigger publicize using post ID

### ISSUE THREAD

**Issue by raphcadiz** [Automattic/jetpack#15130]
Hi, 

I'm looking for a way to programatically trigger the publicize function, something like. 
publicize($post_id);

I don't find any existing solution for this. Can you help. 

Thanks

**Comment by jeherve** [comment]
Publicize is automatically triggered when a post is published, and goes through different steps to figure out if a post should be publicized. You can check the source code here to see when Publicize is triggered, and where you can hook into those actions yourself:
https://github.com/Automattic/jetpack/blob/2b392342af16d9adc942734462559e0a4eca48e3/modules/publicize/publicize.php#L45-L47

**Comment by wolffe** [comment]
Any example on how to do this programmatically?

I have an array of posts that I'd like to publish after a specific event has occurred on the site.
