### ISSUE TITLE
Podcast Player: make sure embedded URL is truly a podcast, not a common RSS.

### ISSUE THREAD

**Issue by getdave** [Automattic/jetpack#15134]
With the Podcast Player Block trying to embed https://distributed.blog/podcast/ will cause the block to render but the tracks will be invalid and result in an error when trying to play.

This is because the tracks end up being valid `jpeg` images rather than audio.

![Screen Shot 2020-03-26 at 11 53 54](https://user-images.githubusercontent.com/444434/77644135-7f31d980-6f58-11ea-92f5-5cad254c77b6.png)

The fix should be to detect (in `_inc/lib/class-jetpack-podcast-helper.php`)  whether any tracks in the track list are not valid `wp_get_audio_extensions` and if so discard them.

Then in the track list empty return an error.

Note this is tricky because we need to detect whether the track's `url` file is anything other valid audio extensions. However some URLs are actually redirects which resolve to valid extension. How can we solve this (@obenland any ideas?)?

**Comment by obenland** [comment]
I noticed `type` is empty. `Jetpack_Podcast_Helper::get_audio_enclosure()` should pick that up. I wonder if the fallback in that method is not working right

**Comment by obenland** [comment]
Returning `null` as a fallback instead of the first enclosure lets us weed out those image enclosures. Doing that seems to make `tracks` an object though, breaking the player.

**Comment by getdave** [comment]
I do have a PR open for this. Not sure if you saw @obenland?

**Comment by obenland** [comment]
Apologies, I didn't. I just tried to get back on top of my notifications. I left a comment in the PR.
