### ISSUE TITLE
Dashboard widget visual overlap

### ISSUE THREAD

**Issue by tillkruss** [Automattic/jetpack#15141]
Latest version of WP and Jetpack. The dashboard widget is overlapping.

<img width="486" alt="Screen Shot 2020-03-26 at 4 44 32 PM" src="https://user-images.githubusercontent.com/665029/77706988-1f035d80-6f81-11ea-84ff-88218dc015c9.png">

**Comment by jeherve** [comment]
This was fixed in #15090. The fix will be part of the next Jetpack release.
