### ISSUE TITLE
Revue: Add single line block style

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#15146]
Currently, there's only one style for Revue block, and that is to display the form field stacked like so:

![image](https://user-images.githubusercontent.com/4550351/77723617-17a58800-7045-11ea-80d5-11e4312d4fcd.png)

This gives us limited options when it comes to block pattern design. It would be great if we could have alternate block style, where all the fields are on the same line, like this (preferably with the button matching the input height):

![image](https://user-images.githubusercontent.com/4550351/77723820-94386680-7045-11ea-8343-86f28b30419a.png)

**Comment by creativecoder** [comment]
Moving this one over as part of @apeatling 's Blocks v2 effort.

**Comment by davemart-in** [comment]
@apeatling heads up that I removed this from our backlog. Don't know if this is something the View team would be interested in picking up.

**Comment by apeatling** [comment]
Added to our backlog.

**Comment by jeherve** [comment]
The block is no longer available, so this can be closed.
