### ISSUE TITLE
Mobile Theme: Samsung Galaxy tabs are considered mobile devices instead of tablets

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1515]
https://developer.chrome.com/multidevice/user-agent

Jetpack's mobile detection follows these recommendations ([reference](https://github.com/Automattic/jetpack/blob/3.3/class.jetpack-user-agent.php#L1025)), but it would seem that Samsung Galaxy Tab doesn't. In my tests, Samsung Galaxy Tab 10.1's User Agent was the following:

`Mozilla/5.0 (Linux; U; Android 2.2; en-us; SCH-I800 Build/FROYO) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1`

Since it includes the word "Mobile", we consider it as a mobile device.

We'd have to add a new custom rule to catch Galaxy Tabs and set them as tablets. It seems that looking for `SCH-I800` would work.

Reported here:
https://wordpress.org/support/topic/jetpack-mobile-theme-3

**Comment by samhotchkiss** [comment]
fixed by #1547, props @chaselivingston
