### ISSUE TITLE
Podcast Player: allow for submitting the same URL twice

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/jetpack#15150]
#### Steps to reproduce the issue

1. Insert an empty Podcast Player block into a new post
1. Open the network tab in devtools and keep it opened on a side
1. Disable all network requests
1. Go back to the block, input a valid podcast URL and submit
1. Observe an error (because we cannot contact the API)
1. Enable network requests
1. Hit the submit button again in the block
1. Infinite loading spinner!

#### What I expected
After reconnecting to the network and hitting the submit button again, you should be able to successfully load the podcast data.

#### What happened instead
Loading state is shown but no API request is even issued on the second submission, because the only way to trigger API call now is for the block attribute with the URL to change. Since you are submitting the same value repeatedly, the attribute doesn't change and thus doesn't trigger the effect.

**Comment by obenland** [comment]
Fixed in #15219
