### ISSUE TITLE
Use an algorithm for perfectly balanced photo galleries

### ISSUE THREAD

**Issue by swissspidy** [Automattic/jetpack#1516]
Hey everyone,

Did you know that there's an algorithm for perfectly balanced photo galleries? I always wanted to build a plugin leveraging it, but it might be easier if this could be implemented in Jetpack.

Explanation: https://www.crispymtn.com/stories/the-algorithm-for-a-perfectly-balanced-photo-gallery
jQuery Plugin: https://github.com/crispymtn/chromatic.js
Demo: http://www.chromatic.io/FQrLQsb (resize your browser window)

I'd love to see this in Jetpack!

**Comment by georgestephanis** [comment]
It feels a lot like what's already in place with Tiled Galleries.  Is there a specific win that this makes over TG?

**Comment by swissspidy** [comment]
I see it as an enhancement to Tiled Galleries, as TG are somewhat limited and ["boring"](http://jetpack.me/support/tiled-galleries/#jp-carousel-3960), always [repeating the same schema](https://github.com/Automattic/jetpack/blob/master/modules/tiled-gallery/tiled-gallery/tiled-gallery-rectangular.php#L33). The [partition problem](http://www8.cs.umu.se/kurser/TDBAfl/VT06/algorithms/BOOK/BOOK2/NODE45.HTM) really solves this for any image sizes/ratios and I think it's worth looking at it. I mean... if there's a mathematical solution for this, why not use it? Images would fit better in the grid and the overall feeling is more natural.

**Comment by georgestephanis** [comment]
I don't really see the difference between the propsal and the existing 'tile' view -- that leverages Photon to resize the images on the fly.

**Comment by swissspidy** [comment]
Looking at the `Jetpack_Tiled_Gallery_Grouper ` code, the tile view only "knows" 8 different row sizes. Instead of hard-coding these sizes you could make it more dynamic and clever.

I don't think more visually appealing rows like these are possible with Jetpack. To take Chromatic as an example again:

Here the appearance changes depending on how many pictures fit in the container: http://www.chromatic.io/D4UlTXg

In comparison, the Jetpack TG rows are always fixed and don't change on window resize: https://cloudup.com/ctpKXmxjzRi

Of course this is just a proposal, but IMHO this sounds to me like the right approach for the problem of tiled galleries. The algorithm wasn't invented for fun :-)

I wonder what others think about this. Maybe it needs a prototype or something, or really isn't a fit for Jetpack...

**Comment by samhotchkiss** [comment]
@georgestephanis -- do tiled galleries allow some tiles to be vertical while others are horizontal?

Personally, I would love to see a prototype of this.  @swissspidy, if you wanted to build it out and submit it as a PR, maybe it flies and makes it in, maybe not, but if not you could still release it as a standalone plugin for people who want a more robust solution.

**Comment by swissspidy** [comment]
I haven't had time yet to dig deeper into that. Hope I'll be able to build something in the near future.

**Comment by dzver** [comment]
This could be another option, equal to Tiles and Squares and I suspect that many people will find it nice and use it.

The original idea of the Tiled Gallery is not to create a perfectly balanced gallery. It was to create a rectangle full with photos with no white space other than margins, and with greatly varying sizes of the photos.

The example you're giving has only one shape - N images per row, where N depends on the image proportions and it's selected in a way that will keep the rows identical. This can be easily implemented with the current gallery - it's only one extra shape :-) but it won't have the nice responsive feel.

Looking forward to seeing a PR by you.
