### ISSUE TITLE
Search: Set has_jetpack_search_product option if plan exists and option not set

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#15172]
In #15156 we are correctly gating on the search plan, but in my testing because my api call failed, i then got an error when trying to activate the module.

If there is an error when the user tries to activate the module, then let's check the api and try to set `has_jetpack_search_product ` to true.

**Comment by jsnmoon** [comment]
Does that mean we'd want to make an API request each time we're checking for module eligibility ([here](https://github.com/Automattic/jetpack/blob/master/_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php#L73) and [here](https://github.com/Automattic/jetpack/blob/master/class.jetpack-plan.php#L229))?

I could imagine this becoming a performance bottleneck.

**Comment by gibrown** [comment]
I was more thinking that if the module activation fails then we should try and set the option before saying that there was a failure. More to make the problem self healing at the time when it happens.

**Comment by jsnmoon** [comment]
Fixed by https://github.com/Automattic/jetpack/pull/15153/commits/d07122a997281940afff0274bc5da72c52d1f4c2.
