### ISSUE TITLE
Search: instant search still triggered when on a pro plan

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#15176]
If you are on a pro plan but the instant_search_enabled option is true the front end still triggers the overlay. Unfortunately, on the backend there is no guarantee that the content will be getting indexed correctly.

This is probably only an issue when downgrading from a Search plan. However, It is also no longer possible to turn off the instant_search_enabled option from the UI once you have downgraded.

**Comment by jsnmoon** [comment]
It'd make sense to toggle `instant_search_enabled` to `false` during the downgrade process.

**Comment by gibrown** [comment]
Good idea... added to D41051

**Comment by jsnmoon** [comment]
I think this is fixed by D41051-code; closing.
