### ISSUE TITLE
(5P) Podcast Player: IE11 audio compatibility

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/jetpack#15188]
IE11 doesn't support `<audio>` unless the user enables the audio support for webpages. Let's investigate and decide whether to disable dynamic player for IE11 or whether we can only disable it when we can't play audio.

Ref: https://stackoverflow.com/questions/34802319/audio-tag-is-not-working-in-ie11/41172831

The `<audio>` seems to throw an error immediately after loading it (before any user interaction) and that might be useful for detecting the support.

**Comment by marekhrabe** [comment]
I have tried looking at this and IE is not very helpful with the detection :( The audio element is always available in JS and all the methods like `canPlayType` for checking audio format support still return positive results just as if everything worked fine. 

The only thing that is happening differently is the audio element throwing an error immediately after the player component initializes. We obviously catch the error and thus we display the "episode can't be played" error state but all this happens before user touches the player. Maybe we can use this idea and treat all errors from audio happening before any user interaction as critical failure and roll back to the static HTML at that point.

**Comment by marekhrabe** [comment]
Flash-based fallbacks were removed from the ME.js library in WP 4.9.2. I will go with the error detection method here and downgrade the block.

**Comment by marekhrabe** [comment]
#15369 introduces an error boundary which we can use on the frontend to replace the dynamic React block by its static markup in case there is any fatal error. 

Based on the feedback in the PR, let's figure out a sound plan to tackle the IE11 audio specifically in a follow-up PR. We can partially use this code I wrote for my first attempt but improve it when run in the editor: https://github.com/Automattic/jetpack/pull/15369/commits/8eaf71fa2a639c357205ccbc462a46b1f028f2f0

**Comment by frontdevde** [comment]
Summarising discussions had on other issues and Slack, there are currently two ideas on how we could solve this:

1.) Show a descriptive error message in IE
> If the error occurs and the user hasn't interacted, we check if the user is on IE11. If they are on IE11, we display an error message that
> a) describes the issue
b) notes that the block settings can still be edited/saved
c) explains to the user how they could activate the needed setting in their IE11 settings

2.) Not show an error at all and disable the audio player instead
> not throwing any error while inside the editor and introducing a local state that disabled just the player

Personally, while I suggested 1), I can definitely see how from a user perspective 2) could feel like a better user experience.

**Comment by frontdevde** [comment]
@davemart-in Any thoughts on which of the above would be the better user experience?

**Comment by davemart-in** [comment]
I'm definitely open to helping the customer solve the issue. I'm not sure about:

> b) notes that the block settings can still be edited/saved

though. I'd just show A and C.
