### ISSUE TITLE
Search: test purchasing after a remote install on an existing site

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#15182]
Steps:
- set up a WP site without Jetpack
- go to the landing page and try to buy a search plan for the existing site
- it should do a remote install and then redirect you into the purchase flow

Unsure if there are bugs here or not.

**Comment by gibrown** [comment]
Needs https://github.com/Automattic/wp-calypso/issues/40627 fixed

**Comment by AnnaMag** [comment]
@gibrown this currently cannot be tested, as landing page does not have CTAs.
That said, if once they are in place the redirect url format is as defined currently in WP.com, 
https://github.com/Automattic/wp-calypso/pull/40661 is setting us up for success. 
JPC is detecting site status and redirects automatically ([this](https://github.com/Automattic/wp-calypso/pull/40661/files#diff-0eb2723c7831b33a4cb7c1d5548e04b6L31) specifically)

**Comment by gibrown** [comment]
Should be possible now with the LP deployed

**Comment by AnnaMag** [comment]
LP does not yet have a CTA, so still on hold :)

**Comment by AnnaMag** [comment]
tested on a variety of sites. Jetpack Connect works great, but the Thank you screen.

https://github.com/Automattic/wp-calypso/issues/40753

**Comment by gibrown** [comment]
Even without that fix this flow is now working great for me so closing.
