### ISSUE TITLE
Likes: don't load on attachment pages

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1518]
Previously reported in 4973-wpcom.

Looks like media attachments are not synced for Jetpack sites - so the "Like" button never loads.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/share-and-likes-buttons?replies=7&view=all

I could reproduce, the problem seems limited to logged in users.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/like-button-broken-on-attachment-pages?replies=1&view=all

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/like-this-not-loading?replies=1&view=all

**Comment by elliott-stocks** [comment]
This is something that needs to be changed on WordPress.com, right?

The API doesn't support attachments -

`{"code":404,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"unknown_post","message":"Unknown post"}}`

**Comment by oskosk** [comment]
Closing as can't reproduce. Don't get to even see an attempt to load likes on an attachment pages. @jeherve please reopen if I got it wrong.
