### ISSUE TITLE
Subscriptions: offer an option to customize the email sent after you've confirmed your subscription

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#152]
We could add that option to **Settings > Reading**, below the other subscription email options.

This will allow folks to add links to e-books to that email as a welcome gift, for example.

Suggested here:
- http://wordpress.org/support/topic/free-e-book-from-subscription?replies=3

**Comment by jenhooks** [comment]
Also requested here: 2171454-t

**Comment by jenhooks** [comment]
2207008-t

**Comment by annezazuu** [comment]
2677370-t

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/email-subscription-management/

**Comment by jenhooks** [comment]
2912209-t

**Comment by lamdayap** [comment]
[https://wordpress.org/support/topic/subscription-confirmation-mail-jetpack-points-to-strange-postspages/](https://wordpress.org/support/topic/subscription-confirmation-mail-jetpack-points-to-strange-postspages/) - Add the ability to choose your own posts/pages to set on 'Great content you might have missed on ...'  after confirming a subscription

**Comment by StefMattana** [comment]
Also requested in #1201164-zen

**Comment by StefMattana** [comment]
Also requested in 1217732-zen

**Comment by tmmbecker** [comment]
2780568-zen

**Comment by eduardozulian** [comment]
19101439-hc

**Comment by lakellie** [comment]
Heard from another user requesting this feature in 5767635-zen

**Comment by simison** [comment]
I'll close this one as it's possible to customize the welcome email. Visit Jetpack -> Settings -> Newsletter, and scroll to the end of page:

![Image](https://github.com/user-attachments/assets/f1bb9b4d-7f6f-464e-8386-4d7bdebd020c)


Customizing can be improved a lot, which has an issue here:

- https://github.com/Automattic/jetpack/issues/36581
