### ISSUE TITLE
Instant Search: searches with spaces in customizer are plusses

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#15206]
Open the Customizer and start typing to do an instant search for something like "related posts".

The space character will actually be a `+`. I think this is because the url is getting converted to that by the customizer.

<img width="771" alt="Screen Shot 2020-03-30 at 2 45 06 PM" src="https://user-images.githubusercontent.com/820871/77960357-65183400-7295-11ea-8489-0684468483e6.png">

**Comment by bluefuton** [comment]
No longer happening in the current release. 👍
