### ISSUE TITLE
Podcast Player: Safari player is not linked to the tracklist audio element

### ISSUE THREAD

**Issue by jeryj** [Automattic/jetpack#15202]
In Safari, the me.js player and tracklist are not in sync. 

#### Steps to reproduce the issue

1. Go to a podcast player in Safari
2. Play the second track in the list
3. The me.js player will not update.
4. Click play on the me.js player
5. It will load and play the first track. The second track will also continue playing.

#### What I expected
The same behavior in Chrome or Firefox. The player and tracklist should be in sync.

`jetpackPodcastPlayers.playerInstances["jetpack-podcast-player-block-1"].player.mediaElement.media.querySelector('audio') === jetpackPodcastPlayers.playerInstances["jetpack-podcast-player-block-1"].player.audio` should return `true`, but in Safari this returns `false` (replace `"jetpack-podcast-player-block-1"` with the instance ID of your player.

**Comment by obenland** [comment]
Fixed in #15215.
