### ISSUE TITLE
Podcast Player: error if Block unmounts whilst fetching feed.

### ISSUE THREAD

**Issue by getdave** [Automattic/jetpack#15214]
Currently the Podcast Player Block uses `apiFetch` to trigger a Ajax request for the feed data. Once it [the fetch promise] resolves then state and attributes updates are triggered.

If, whilst the network request is in progress, the Block is "unmounted" then the console will show an error along the lines of

> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

This is because the `.then` handler on the fetch still triggers even though the Block no longer exists.

##### Steps to reproduce the issue

* Insert Podcast Block.
* In Network Tools switch to "Slow 3G mode".
* Add a valid feed URL and submit.
* Immediately (before the fetch request resolves) delete the Block.
* See error in console. 

#### What I expected

If the Block is removed in the middle of the fetching of the feed then there should be no errors in the console and everything should be handled gracefully. 

#### What happened instead

There are errors in the console.

> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

#### Solution

Please see the `LinkControl` component from Gutenberg. In this, I encountered a similar problem which I solved by [wrapping the Promise to allow it to be cancelable](https://github.com/WordPress/gutenberg/blob/ddd3fffdd327d2f9c5202481345fb7427d4a822b/packages/block-editor/src/components/link-control/index.js#L62).

The cancellables then need to be [stored in refs](https://github.com/WordPress/gutenberg/blob/ddd3fffdd327d2f9c5202481345fb7427d4a822b/packages/block-editor/src/components/link-control/index.js#L167) to ensure they can be handled.

Then [when the block is "unmounted" all cancellables should be `.cancel()`](https://github.com/WordPress/gutenberg/blob/ddd3fffdd327d2f9c5202481345fb7427d4a822b/packages/block-editor/src/components/link-control/index.js#L365).

I would also like to experiment to see if we can extract this to a hook and then see if @aduth would be interested in having it in Gutenberg because he and I discussed that this might be an issue for 3rd party Blocks.

**Comment by obenland** [comment]
Fixed in #15228
