### ISSUE TITLE
Related Posts: Add filter to show Related Posts on blog/archives page

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#1524]
A few requests have come in to allow Related Posts to display on the main blog or archives pages, not just single post pages, perhaps we could add a filter for this functionality.

**Comment by samhotchkiss** [comment]
Looks like there already is one.  See `jetpack-related-posts.php:1022` :
```return apply_filters( 'jetpack_relatedposts_filter_enabled_for_request', $enabled );```

However, I'm not sure if the JS will support more than one instance of related posts on a page-- I think that may be our bottleneck here.  Maybe @xyu can chime in there?

**Comment by xyu** [comment]
Unfortunately not :( our JS/CSS currently only supports displaying one related post section per page and is thus restricted to single posts/pages. Our APIs are not restricted however so I suppose it's possible to build something like this into a theme / plugin using the provided `Jetpack_RelatedPosts_Raw()` class:

https://github.com/Automattic/jetpack/blob/master/modules/related-posts/jetpack-related-posts.php#L1076-L1126

**Comment by richardmtl** [comment]
Requested in 2306875-t

**Comment by jeherve** [comment]
Closing as duplicate of #409
