### ISSUE TITLE
Jetpack settings shows a blank page when any XHR fails

### ISSUE THREAD

**Issue by adamziel** [Automattic/jetpack#15255]
If you go to Jetpack dashboard, and any request, such as `/wp-json/jetpack/v4/site/purchases?` fails - the entire dashboard becomes a blank page. 

#### Steps to reproduce the issue

1. "Break" something in your backend to make sure e.g. `/wp-json/jetpack/v4/site/purchases?` returns 403 or 200 with an unexpected response like `{"code":"success","message":"Site purchases correctly received.","data":"{\"error\":\"unauthorized\",\"message\":\"User cannot access this private blog.\"}"}`
1. Go to Jetpack Dashboard in /wp-admin
1. See that it's not rendered anymore

#### What I expected
To see the dashboard, maybe just with some features disabled. At a very least I expected an error message.

#### What happened instead
Blank screen

**Comment by jeherve** [comment]
I can't seem to be able to reproduce that issue right now. Whether I block the request to `v4/site/purchases` or whether I edit `get_purchases` in `_inc/lib/core-api/class.jetpack-core-api-site-endpoints.php` to return an error, it does not seem to break the dashboard for me.

Could you tell me about how I could reproduce this?

Thank you!

**Comment by adamziel** [comment]
I reported this issue recently, but I've initially hit it a month ago when working on allowing the private site to use the API using the blog token. I just reproduced the initial setup with 403 errors and I can't reproduce the problem anymore - it seems likely that something was improved in the meantime. Either way, it seems like it's okay to close it.
