### ISSUE TITLE
Blocks: block spinners are left-aligned in WP 5.4

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#15256]
#### Steps to reproduce the issue

1. Start with the site running WP 5.4
2. Start a new post, and add a MailChimp block
4. See the spinner appears left-aligned
5. Try other blocks such as business hours, recurring payments, etc

#### What I expected
Centered content is centered in the container

#### What happened instead
![githu](https://user-images.githubusercontent.com/5654161/78273440-7ff9db00-7517-11ea-9eec-1b2a38985549.gif)

**Comment by jeherve** [comment]
closing since Jetpack now requires WP 5.5.
