### ISSUE TITLE
Subscriptions Widget: Remove the value from the email input field

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1525]
Right now in the Subscriptions Widget, no matter what the Placeholder text is, there is always the value of "Email Address" in the input field.  When someone goes to fill out their email, they first have to delete the current text and then input their address.

We should just let the Widget "Placeholder Text" be there, but leave the value out.

Widget screen:
![screen shot 2015-01-21 at 11 02 25 am](https://cloud.githubusercontent.com/assets/3220162/5842845/0f88520e-a15d-11e4-9a35-b140111ef697.png)

Displayed on site:
![screen shot 2015-01-21 at 11 02 43 am](https://cloud.githubusercontent.com/assets/3220162/5842850/1a24f6f4-a15d-11e4-8e4f-57c869691f44.png)

**Comment by samhotchkiss** [comment]
This is already fixed in master #1448

**Comment by aheckler** [comment]
Mentioned in 2065652-t.
