### ISSUE TITLE
Tiled Galleries: circle galleries "squish" the images

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1526]
1. Add the Gallery Widget to your Widget Area
2. Add a few images
3. Select them to be displayed in the Circle Style
4. Some of the images will look squished - without proper dimensions.

My Widget:
![screen shot 2015-01-21 at 11 51 34 am](https://cloud.githubusercontent.com/assets/3220162/5843794/e33db28c-a163-11e4-9a98-744189e650e3.png)

My Sidebar:
![screen shot 2015-01-21 at 11 50 20 am](https://cloud.githubusercontent.com/assets/3220162/5843798/ef651816-a163-11e4-9aa3-5ad2a30da48a.png)

Note the second row, all images seem to have been squished.  
originally reported by user in #2060350-t

**Comment by dereksmart** [comment]
Is this a bug? This also happens for "square tile" view.  
I feel like this is expected for images that aren't square.  In order to make a circle or square from a rectangle image, we either need to resize the image or crop part of it out.  Do you recommend we do the latter instead?

**Comment by dereksmart** [comment]
After a short internal discussion - cropping is way better

**Comment by jeherve** [comment]
Also reported in 2093606-t

**Comment by samhotchkiss** [comment]
@jeherve @dereksmart -- any reason we need to push this to 3.5?  Should be a pretty simple param to crop instead of squish, right?

**Comment by dereksmart** [comment]
It may have been tagged 3.5 because of 3.4 beta?  Since it's not broken on wpcom, the culprit is probably in Jetpack.  I'll take a look today.

**Comment by dereksmart** [comment]
Actually, may have been tagged for 3.5 because the url params to resize & crop only work for images served from wpcom/photon.  I'll look for another way to do this on our end that won't interfere with wpcom, since all the gallery widget code is synced.

**Comment by s-a-s-k-i-a** [comment]
Will this be worked on? As for now, I won't be able to make use of the galleries in my clients site, because her images get squeezed.

**Comment by gracie** [comment]
Also reported in #3115337-t

**Comment by rachelmcr** [comment]
There were similar reports on the WordPress.com side and some fixes to address the issue, although it isn't entirely resolved. Internal ref: 7861-wpcom

**Comment by Soft-Shock** [comment]
![capture](https://user-images.githubusercontent.com/6386318/31299957-4bc10182-aaae-11e7-9181-c771e40a846a.PNG)

For me, both Square Tile, and Circles stretch/squish the images.

This is on a self-hosted install, but still, whenever I use Jetpack Tiled Galleries, without their Photon CDN, Square Tile, and Circle, is always stretching non-square images. This occurs even after regenerating thumbnails.

What's weird is that in the [Jetpack Demo](https://jetpack.com/2013/05/25/tiled-galleries/) they have non square photos for their galleries, and they are not distorted.

My only guess is that they are using Photon CDN and I'm not. Or that I am self hosted (on DreamHost) and they are not.

Here is my link, but the domain may change in the near future, so refer to the screenshot. https://mjmetz.northstarexteriors.ca/dev.brielle-cosmetic-couture.lan/gallery/

Any suggestion on a workaround would be much appreciated (CSS or a filter in WordPress).

**Comment by jeherve** [comment]
@Soft-Shock Do you use Jetpack's Development mode on your site, to be able to use Tiled Galleries without Photon? What happens when you activate Photon on your site?

**Comment by Soft-Shock** [comment]
Ah, unfortunately I am only using JETPACK_DEV_DEBUG mode. I didn't want to hook up the client's site to wordpress.com, and they don't have a wordpress.com account.

I finally see the warning, in the jetpack media settings

> Speed up images and photos
> 
> Must be enabled to use tiled galleries.

but it was greyed out, so it was hard to see.

I temporarily connected my account to the development site and the images resize properly with Photon.

So I guess I either need clients to have a free wordpress.com account, or use a different tiled gallery plugin (for circle and square tiled. Tiled Mosaic and Tiled Columns work without photon).

**Comment by jeherve** [comment]
> I guess I either need clients to have a free wordpress.com account

It might be worth asking them, they might already have one; if they don't it could be useful for them to get one for other things as well, like Gravatar or Akismet.

You can also help them and create that account for them, and only change the account's email address to theirs when you're ready to hand it over.
To create a simple account without a WordPress.com site, you can use this link:
https://wordpress.com/start/jetpack

**Comment by Soft-Shock** [comment]
Great, thanks for the tips @jeherve!

**Comment by donpark** [comment]
FYI, this is now happening consistently on WPCOM Simple sites for Square Gallery added using Classic Editor.

Simplest fix I found was to add `object-fit: cover` to image tag style.

**Comment by donpark** [comment]
I have a tentative patch D28285-code that fixes Squished Tiled Gallery image problem for Square and Circle mode on WPCOM. What I don't fully understand is why same problem exists on Jetpack sites.

**Comment by AtrumGeost** [comment]
Hi folks!

I'm reopening this issue since this is still happening on WordPress.com simple sites with the Classic Editor. I was able to reproduce this on my test site using a "Square Tiles" gallery with 2 columns:

![Screen Shot on 2019-06-17 at 12:48:25](https://user-images.githubusercontent.com/3696121/59625349-b2f4ee80-90fe-11e9-959d-1dde87402cf1.png)

This was reported here: 4983350-hc

And here's my test site where I could replicate that: https://atrumtest03.wordpress.com/2019/06/17/testing-gallery-4983350-hc/

**Comment by donpark** [comment]
> I'm reopening this issue since this is still happening on WordPress.com simple sites with the Classic Editor. I was able to reproduce this on my test site using a "Square Tiles" gallery with 2 columns:

My patch D28285-code, awaiting review, will fix this for WPCOM.

**Comment by donpark** [comment]
> My patch D28285-code, awaiting review, will fix this for WPCOM.

Hate to remind y'all but nothing will get fixed unless the patch is accepted and deployed.

**Comment by donpark** [comment]
FYI: Patch for Jetpack should ship in the next release. Patch for WPCOM (D28285-code) will be deployed as soon as it's approved. Stay tuned.

**Comment by donpark** [comment]
WPCOM patch deployed! Thanks to @jeherve @simison and @lancewillett.
