### ISSUE TITLE
OpenTable: Some text obscured when block is placed against background.

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#15268]
OpenTable's single-line wide block style has text above and below the form. This text does not change color when the block is placed against a background, which makes it invisible when placed on dark/black, and obscured when a block is placed against an image. 

I'm not sure if this is possible to address, because the background color/image is not an OpenTable block setting (it has to be nested in cover or group block), but I thought it's worth bringing up anyway.

#### Steps to reproduce the issue

1. Add a cover block to a page, and upload an image.
2. Add OpenTable block inside the cover block. Pick the wide block style.
3. Notice the obscured "Make a reservation" text above the form, and "Open Table" text below.
4. Remove the image from the cover block, and select a black background. Notice the text is not visible anymore.

#### What I expected
For the text to automatically change color when block is placed against a background - similar to what happens to paragraph text added inside cover block.

**Screenshots**

![image](https://user-images.githubusercontent.com/4550351/78322903-cbfe5b80-75bb-11ea-84c0-06f735da4159.png)

**Comment by glendaviesnz** [comment]
Unfortunately this text colour is set by OpenTable, and because it is in an iFrame there is no way we can override it. Happy for others to give a second opinion in case I am missing something, otherwise I suggest we close this one for now.

**Comment by scruffian** [comment]
We could add an option to add background colour to the block, but since the text that is hard to read is non-essential, I agree with @glendaviesnz, this should be closed.
