### ISSUE TITLE
Podcast Player: Align feed url input element and button.

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#15263]
Once the text field and button heights match, can we also make sure that we have the same padding height above and below the text field (18px feels right):

![heights](https://user-images.githubusercontent.com/1398304/78305365-9131f000-74f5-11ea-916f-7ca3dca2b132.png)

**Comment by WunderBart** [comment]
To compare with current YT embed:

![image](https://user-images.githubusercontent.com/1451471/78356962-db2bdc00-75b0-11ea-9f06-87150e1b30d2.png)

I think we should also use the same input placeholder text: "Enter URL to embed here..."

**Comment by frontdevde** [comment]
Fixed by https://github.com/Automattic/jetpack/pull/15376
