### ISSUE TITLE
Podcast Player: Show duration as hh:mm

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#15261]
Let's remove seconds so that all of the times are consistent (showing just hours:minutes), and double check that if a podcast is 3 hours flat that it shows as 3:00, not 3:

**Comment by WunderBart** [comment]
Technically, an episode can have less than 1 minute, no?

**Comment by marekhrabe** [comment]
I'm not sure about this. Some other services I have quickly checked all include seconds and optional hours.

**Comment by obenland** [comment]
Pinging @davemart-in to give him a chance to folow-up

**Comment by davemart-in** [comment]
> Technically, an episode can have less than 1 minute, no?

Good point. Thinking about this again, I'd love to make this more human readable. Would it be possible to convert the current HH:MM:SS format to:

- 3 hr
- 1 hr 32 min
- 56 min
- 1 min (for anything 1 minute or less)

**Comment by marekhrabe** [comment]
I was looking if we can use anything from WP core and there is indeed [`human_readable_duration`](https://developer.wordpress.org/reference/functions/human_readable_duration/), however if generates a long form of time units ("minutes", "hours", …) 

If we want the short ones, we might need to copy the core function and rewrite translations with our custom ones.

**Comment by davemart-in** [comment]
Yeah, I think we'd need shorter ones, simply to preserve space.

**Comment by obenland** [comment]
Let's close this until we do another round of updates to the podcast player
