### ISSUE TITLE
(2P) Podcast Player: Track icon is off-middle in the editor

### ISSUE THREAD

**Issue by WunderBart** [Automattic/jetpack#15284]
#### Steps to reproduce the issue

1. Add Podcast Player block to your page,
2. Use e.g. https://anchor.fm/s/9400d7c/podcast/rss as the feed URL and embed it,
3. In the editor, click on a track to play it,
4. Notice the loudspeaker icon on the left of the track is 1px off-middle to the bottom,
4. Go to preview and compare it with front-end - the icon there is exactly in the middle.

#### What I expected
The track icon should be in the middle vertically exactly the same in both editor and front-end.

#### What happened instead
The track icon in the editor is 1px off.

**Screenshots**
| editor  | front-end |
| ------------- | ------------- |
|<img width="340" alt="Screenshot 2020-04-03 18 11 54" src="https://user-images.githubusercontent.com/1451471/78382676-80f24180-75d7-11ea-843a-b681cdb2399a.png">|<img width="340" alt="Screenshot 2020-04-03 18 12 59" src="https://user-images.githubusercontent.com/1451471/78382679-818ad800-75d7-11ea-934d-5a5bae341de3.png">|

**Comment by marekhrabe** [comment]
IE11 is now more off than ever! 😅

<img width="588" alt="Screenshot 2020-04-08 at 12 23 00" src="https://user-images.githubusercontent.com/156676/78774290-c6768c00-7994-11ea-8ec5-0f2ba18ccf95.png">

**Comment by jeryj** [comment]
@marekhrabe 😭😭😭😭😭

Opened a new PR to address 👍

**Comment by WunderBart** [comment]
Fixed by https://github.com/Automattic/jetpack/pull/15343 and https://github.com/Automattic/jetpack/pull/15371.
