### ISSUE TITLE
(3P) Podcast Player: HTML entities in description not decoded

### ISSUE THREAD

**Issue by WunderBart** [Automattic/jetpack#15282]
#### Steps to reproduce the issue

1. Add Podcast Player block to your page,
2. Use https://anchor.fm/s/9400d7c/podcast/rss as the feed URL and embed it,
3. Click on the second track to play it ("May 6-10: A week of submersion."),
4. See description with escaped `&nbsp;` entities.

#### What I expected
HTML entities in the episode description text to be unescaped.

#### What happened instead
HTML entities in the episode description text were escaped.

**Screenshots**
![image](https://user-images.githubusercontent.com/1451471/78381191-4be4ef80-75d5-11ea-9471-48cef42e256c.png)

**Comment by obenland** [comment]
https://whatsurfave.com/category/podcast/feed/ is another good feed to test with
