### ISSUE TITLE
In-place connection: Try again button is not well aligned

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#15285]
#### Steps to reproduce the issue

1. It's a bit tricky since you'll need to force a connection to fail
2. Try to connect via in-place connection
3. See that "Try again" button is not well aligned

#### What I expected
not sure, actually. Should "Try again" replace the "Approve" button?

#### What happened instead

![buttons_alignment](https://user-images.githubusercontent.com/5654161/78387696-73918300-75e8-11ea-9ffa-f4440e22a978.jpg)

**Comment by brbrr** [comment]
Labeled it as High priority, since similar connection errors might happen quite often, and since it will create not a great first impression, I think we should prioritize fixing it.

**Comment by brbrr** [comment]
This should be fixed once D47074-code is merged

it would look like this:

<img width="495" alt="Jetpack ‹ Weekly Snakes — WordPress 2020-07-28 17-40-12" src="https://user-images.githubusercontent.com/5654161/88680999-c643fd00-d0f9-11ea-9957-cd1494c8341c.png">

**Comment by brbrr** [comment]
@Automattic/jetpack-design may I bother you with the sanity check for the above styling update?

**Comment by folletto** [comment]
The above seems a good fix for me. 👍

**Comment by brbrr** [comment]
These errors coming from WPCOM's `/jetpack-blogs/$clientId/authorize` response, so indeed we can iterate on them. Although it might not be a simple change. I'd prefer to leave this fix to remain style-related. 

I wonder if we have plans on reviewing these error responses as part of our connection focus? (not sure who to ping about the above question, so cc @kbrown9 @leogermani)

**Comment by folletto** [comment]
Yes, makes sense to just fix the visual first. I was asking as the first screen was showing something different — let's go ahead. :)

**Comment by brbrr** [comment]
Deployed via r211170-wpcom

**Comment by kbrown9** [comment]
> I wonder if we have plans on reviewing these error responses as part of our connection focus?

As you can see from the first screenshot, the current error messages aren't very actionable. We do have plans to work on providing better connection error messages.
