### ISSUE TITLE
Publicize: Path: Image missing from post publicized

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#153]
Steps to reproduce:

1) Enable Jetpack, Publicize, and make a connection with Path
2) Publish an post using the image post format on your site. Define a large Featured image for that post

Only a link appears on Path instead of a link along with the Featured Image, like for WordPress.com blogs.

Reported here:
​http://wordpress.org/support/topic/issue-on-publicize-path-connection

Ported from https://plugins.trac.wordpress.org/ticket/1980

**Comment by jkudish** [comment]
@richardmtl can you please confirm if this is still an issue and if so re-post it (and link it) on the private io repo?

**Comment by richardmtl** [comment]
Done, reproduced so re-posted and closing this one.
