### ISSUE TITLE
Related Posts : bad quality images

### ISSUE THREAD

**Issue by nicolinuxfr** [Automattic/jetpack#1530]
On [my blog](http://voiretmanger.fr), I'd like to display three related posts with only pictures, and at 100 % width, so 1/3 of the width for each pictures. Unfortunately, the result isn't great, since the images are really blurry (open this screenshot at full size to see the problem).

![related-posts-bad-pictures](https://cloud.githubusercontent.com/assets/2078386/5853471/4dba2fda-a224-11e4-8d87-5fd3e4d555a3.png)

The code explains why : the image pulled from Photon is at 350 pixels width, where it should be in this case at least 640px wide. 

```html
<img class="jp-relatedposts-post-img" src="http://i0.wp.com/voiretmanger.fr/wp-content/2012/04/titanic-james-cameron.jpg?resize=350%2C200" width="480" alt="Titanic, James Cameron" height="274" src-orig="http://i0.wp.com/voiretmanger.fr/wp-content/2012/04/titanic-james-cameron.jpg?resize=350%2C200" scale="1">
```

Is there a way to change this parameter and have bigger sized images instead ? Thanks for your help !

**Comment by jeherve** [comment]
Yes, you can use the `jetpack_relatedposts_filter_thumbnail_size` filter, like so:

```php
function jetpackchange_image_size ( $thumbnail_size ) {
	$thumbnail_size['width'] = 422;
	$thumbnail_size['height'] = 241;
	return $thumbnail_size;
}
add_filter( 'jetpack_relatedposts_filter_thumbnail_size', 'jetpackchange_image_size' );
```
