### ISSUE TITLE
Search: Theme incompatibilities

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#15304]
Looks like somewhere along the way we broke a few themes, especially on mobile.

All links are to my test site which is running 8.4 branch.

I only tested these in Chrome on Mac. For the mobile theme problems I really only verified these using the chrome debug tools though I saw at least some of them on iOS Chrome also. 

If I had to prioritize based on existing users though, we should fix 2019 which I think has the most existing customers using it. And fixing that fixes many others. Here is a sceenshot:

<img width="446" alt="Screen Shot 2020-04-05 at 1 05 06 PM" src="https://user-images.githubusercontent.com/820871/78507585-1ad3fe80-773e-11ea-9edd-c5f56c2223c1.png">

2010 and 2012 are scary bad but I am not sure anyone is currently using them with Search.

On Mobile:
- 2010: showing the sidebar: http://gibrown.wpsandbox.me/demo/?s=related%20psts&blog_id=20115252&theme=twentyten&orderby=relevance&order=DESC
- 2011: search box is off the screen: http://gibrown.wpsandbox.me/demo?s=related%20psts&blog_id=20115252&theme=twentyeleven&orderby=relevance&order=DESC&category=releases
- 2012: yikes! extra search button, offset search icon, overlapping highlighting of matches: http://gibrown.wpsandbox.me/demo/?s=related%20psts&blog_id=20115252&theme=twentytwelve
- 2014: search box too wide http://gibrown.wpsandbox.me/demo/?s=related%20psts&blog_id=20115252&theme=twentyfourteen&orderby=relevance&order=DESC
- 2019: search box too wide http://gibrown.wpsandbox.me/demo/?s=related%20psts&blog_id=20115252&theme=twentynineteen&orderby=relevance&order=DESC&category=releases
- Shapely: search icon alignment, search box too wide http://gibrown.wpsandbox.me/demo/?s=related%20psts&blog_id=20115252&theme=shapely&category=releases
- zerif-lite: search icon alignment, search box too wide http://gibrown.wpsandbox.me/demo?s=related%20psts&blog_id=20115252&theme=zerif-lite&category=releases&orderby=date&order=ASC

On Desktop:
- 2012: extra search button, offset search icon, overlapping highlighting of matches: http://gibrown.wpsandbox.me/demo/?s=related%20psts&blog_id=20115252&theme=twentytwelve

**Comment by keoshi** [comment]
Quick running through the list:

> 2010: showing the sidebar

Good catch. This theme doesn't have a `viewport` meta definition (supposedly because it isn't responsive), so the overlay won't be either. This is not something we can change with CSS only.
