### ISSUE TITLE
Instagram Gallery Block: Update Popup Monitor

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#15314]
In #15091 we've added the mechanism to connect the Instagram Gallery block to an Instagram account. The authorization flow happens in a popup.

Jetpack has a `PopupMonitor` library, obtained from Calypso, which is not exposed to the extensions.
In Jetpack context, it was enough to resolve the library folder as a module in Webpack.
Unfortunately, this doesn't work in WPCOM.

There are two options now:
- Publish Calypso's `PopupMonitor` as a package, and import it via npm.
- Revert to using a "manual" popup. Incidentally, it was like this until https://github.com/Automattic/jetpack/pull/15091/commits/d50652291ca1e35bb28ae96f1e281f5833133028, so we already have a working copy. 🙂 

Regardless, we should also remember to clean up the Webpack changes afterwards.

- [x] Update the popup implementation. (#15482)
- [x] Remove the Wepback [unnecessary resolution rules](https://github.com/Automattic/jetpack/pull/15091/commits/d50652291ca1e35bb28ae96f1e281f5833133028#diff-09575ea3a128e617b9c541a2b7262da5). (#15535)
- [x] Sync the Instagram Gallery block back to WPCOM.
- [x] Add the new lib to the Fusion list on WPCOM.

See:
https://github.com/Automattic/jetpack/pull/15091#issuecomment-609917064
https://github.com/Automattic/jetpack/pull/15091#issuecomment-609923235
D40701-code
p1586192619168700-slack-jetpack-crew
p1586193009061900-slack-team-calypso

**Comment by scruffian** [comment]
cc @Automattic/team-calypso who might be willing/interested to make make this code reusable.

**Comment by Copons** [comment]
I've opened this https://github.com/Automattic/wp-calypso/pull/40972 but I've got a few issues building it. (see p1586441098093100-slack-team-calypso )

**Comment by scruffian** [comment]
> Add the new lib to the Fusion list on WPCOM.

I don't think we need to do this do we?

**Comment by jeherve** [comment]
It looks like @Copons already took care of it in r207009-wpcom. This should be good to close now.

**Comment by Copons** [comment]
> > Add the new lib to the Fusion list on WPCOM.
> 
> I don't think we need to do this do we?

Right, a few days ago I tried to remember what that line meant, but just couldn't, and then forgot about it. 😄
