### ISSUE TITLE
My Plan: Update copy for the Premium Themes card

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#15313]
#### Steps to reproduce the issue

1. Get a Pro plan
2. Visit /wp-admin/admin.php?page=jetpack#/my-plan
3. See the Themes card

"Access hundreds of beautifully designed premium themes at no extra cost." could be improved to reflect latest themes changes

Internal ref: p1HpG7-8Ik-p2

**Screenshots**
<img width="761" alt="Jetpack ‹ jetpack6test mystagingwebsite com at Pressable — WordPress 2020-04-06 20-22-09" src="https://user-images.githubusercontent.com/5654161/78586608-578a1d80-7844-11ea-982f-c4b628389101.png">

**Comment by crunnells** [comment]
What we've done in other places is just remove the `"hundreds of"` line, changing the copy to:

`Access beautifully designed premium themes at no extra cost`
