### ISSUE TITLE
Instant Search: sort order always set to score_default

### ISSUE THREAD

**Issue by skjaini** [Automattic/jetpack#15324]
#### Steps to reproduce the issue

1. Go to Customizer -> Widgets -> Jetpack Search Sidebar
2. Use 'Default sort order' dropdown to select any option to sort the results
3. Inspect the site search API request for `score` query param
4. Notice it always set to `score_default` for 'Oldest first' and 'Newest first' sort order options
5. Search results displayed in the live preview are unchanged

#### What I expected
When 'Oldest first' is selected, `sort` should be set to `date_asc`.
When 'Newest first' is selected, `sort` should be set to `date_desc`.

#### What happened instead
`sort` always set to `score_default`

**Screenshots**
<img width="250" alt="Screen Shot 2020-04-06 at 4 55 15 PM" src="https://user-images.githubusercontent.com/4796269/78616144-492e0880-7828-11ea-9a77-49b03fbbfc75.png"><img width="250" alt="Screen Shot 2020-04-06 at 4 55 39 PM" src="https://user-images.githubusercontent.com/4796269/78616151-4cc18f80-7828-11ea-84ad-1488efb05309.png"><img width="250" alt="Screen Shot 2020-04-06 at 4 55 54 PM" src="https://user-images.githubusercontent.com/4796269/78616156-4d5a2600-7828-11ea-8e56-1548a3dbd42e.png">

**Comment by gibrown** [comment]
Oh ya good catch. We should probably hide some of these options in the widget settings. I think the post filter types are also not set up.

**Comment by jsnmoon** [comment]
This has been superseded by a default sort order option in the Jetpack Search section of the Customizer (#https://github.com/Automattic/jetpack/pull/16017).

I will create a follow-up PR to remove the sort order selects from the Jetpack Search widget options after merging #15989, which includes handling for rendering instant search specific widgets.
