### ISSUE TITLE
cache system

### ISSUE THREAD

**Issue by camaran** [Automattic/jetpack#1532]
Add a robust cache system

**Comment by jeherve** [comment]
If you're looking for caching plugins, I'd suggest trying [WP Super Cache](https://wordpress.org/plugins/wp-super-cache/) or [W3 Total Cache](https://wordpress.org/plugins/w3-total-cache/), as they already offer tons of options to add caching to your site. I'm afraid adding such options to Jetpack is not on our roadmap at the moment.
