### ISSUE TITLE
Podcast Player: Inconsistent "speaker" icons

### ISSUE THREAD

**Issue by WunderBart** [Automattic/jetpack#15337]
#### Steps to reproduce the issue

The Player uses 2 different "speaker" icons:

<img width="767" alt="Screenshot 2020-04-07 13 07 02" src="https://user-images.githubusercontent.com/1451471/78667636-9b7b3200-78d9-11ea-8464-891b61daeda4.png">

The one in volume control comes from the [MediaElement SVG sprite](https://github.com/mediaelement/mediaelement/blob/master/src/css/mejs-controls.svg). The other one is from the [material icons](https://material.io/resources/icons/?icon=volume_up&style=outline).

#### What I expected
To see the same "speaker" icon used as both, track playback indication and volume control.

**Comment by WunderBart** [comment]
Because of how things are implemented, I suggest extracting the volume icon from the [mejs-controls.svg](https://github.com/mediaelement/mediaelement/blob/master/src/css/mejs-controls.svg) sprite and replacing the track "playing" icon with it.

**Comment by jeryj** [comment]
Does this suggest an issue with the sound icon itself? One controls the volume and one indicates the track is currently playing.

I do like the sound icon within the track list more though... I agree it would be a lot easier to use the MEjs one though. 

All that said, I don't have an issue with leaving it as is and not replacing the sound icon. 

cc @lessbloat

**Comment by frontdevde** [comment]
I took the mediaelement SVG icon sprite and reduced it down to the paths and classes that make up the speaker icon:

```
<svg xmlns="http://www.w3.org/2000/svg" width="400" height="120" viewBox="0 0 400 120">
    <style>
        .st0{fill:currentColor;width:16px;height:16px} 
        .st1{fill:none;stroke:currentColor;stroke-width:1.5;stroke-linecap:round;} 
    </style>
    <path class="st0" d="M67 5.8c-.5.4-1.2.6-1.8.6H62c-.6 0-1 .4-1 1v5.7c0 .6.4 1 1 1h4.2c.3.2.5.4.8.6l3.5 2.6c.4.3.8.1.8-.4V3.5c0-.5-.4-.7-.8-.4L67 5.8z"/>
    <path class="st1" d="M73.9 2.5s3.9-.8 3.9 7.7-3.9 7.8-3.9 7.8"/>
    <path class="st1" d="M72.6 6.4s2.6-.4 2.6 3.8-2.6 3.9-2.6 3.9"/>
</svg>
```

I changed the values for `fill:` and `stroke:` to `currentColor` which would allow the icon to be color customizable via the text-color. That said, I'm not certain having this as an additional icon inline is the right way to do this. Maybe we should stay consistent with how this icon works on the audio player and use the actual mediaelement sprite with masking instead.

**Comment by frontdevde** [comment]
Fixed in https://github.com/Automattic/jetpack/pull/15445
