### ISSUE TITLE
Infinite Scroll: broken when footer is set to false

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#15348]
#### Steps to reproduce the issue

1. Install a theme such as [Cubic](https://wordpress.com/theme/cubic/) on a Jetpack site.
    - Another theme would do, the important part is that the theme must set the `footer` parameter to `false` when declaring support for Infinite Scroll, like so:
```php
function cubic_jetpack_setup() {
        /**
         * Add theme support for Infinite Scroll.
         * See: http://jetpack.me/support/infinite-scroll/
         */
        add_theme_support( 'infinite-scroll', array(
                'container'      => 'main',
                'footer'         => false,
                'wrapper'        => false,
                'posts_per_page' => 9,
        ) );
}
add_action( 'after_setup_theme', 'cubic_jetpack_setup', 11 );
```
2. Create many posts so IS can be triggered.
3. Not that IS is not triggered, and the following JS error appears:
```js
Uncaught TypeError: Cannot read property 'setAttribute' of null at Scroller.gotop (infinity.min.js?ver=8.4-alpha-is5.0.0:3)
```

This was caused by #15017. Since those themes do not have a footer, this won't find an element:
https://github.com/Automattic/jetpack/blob/30140ab4e188bda3820346b9d2a83e6eb244d9ad/modules/infinite-scroll/infinity.js#L202

Until we have a fix, I would recommend forcing Infinite Scroll to show a footer, and then hide that footer with CSS. This can be done [in a functionality plugin](https://jetpack.com/support/adding-code-snippets/):

```php
function jetpackcom_fix_broken_is() {
	add_theme_support( 'infinite-scroll', array(
		'type'           => 'scroll',
		'container'      => 'main',
		'footer'         => true,
		'wrapper'        => false,
		'posts_per_page' => 9,
	) );
}
add_action( 'after_setup_theme', 'jetpackcom_fix_broken_is', 12 );

function jetpackcom_hide_is_footer() {
	wp_add_inline_style( 'the-neverending-homepage', '#infinite-footer{display:none;}' );
}
add_action( 'wp_enqueue_scripts', 'jetpackcom_hide_is_footer' );
```

**Comment by jeherve** [comment]
Also reported in 20067334-hc

**Comment by jeherve** [comment]
cc @dero who worked on the original PR.

**Comment by dero** [comment]
@jeherve Thanks for flagging me. I'll work on a fix today.

**Comment by GeoJunkie** [comment]
Ran into this in 13262545-hc (follow-up: 2858382-zen). They're using the Maxwell theme.

**Comment by rickmgithub** [comment]
Also on here 20090829-hc and follow up 2857745-zd. Theme is Baskerville.

**Comment by zdenys** [comment]
Need to follow-up here 2864205-zen as the issue is still present on the site it seems https://d.pr/v/kzLG9C The user came into chat 20153274-hc

**Comment by mrsjaved** [comment]
Same issue with another user. Along with the infinite scroll, the load more button is also not working that loads the posts on click via AJAX.

zd-59100746

**Comment by GeoJunkie** [comment]
Encountered in 20120575-hc (follow-up: 2861765-zen) with the Cubic theme.

Applied the workaround and it fixed the issue.

**Comment by GeoJunkie** [comment]
> Ran into this in [13262545-hc](https://href.li/?https://mc.a8c.com/support-stats/happychat/transcript.php?id=13262545) (follow-up: [2858382-zen](https://href.li/?https://automattic.zendesk.com/agent/tickets/2858382)). They're using the Maxwell theme.

Just a note that I applied the workaround on this site and it didn't work.

**Comment by kathrynwp** [comment]
I ran into a recently broken IS button in 2865173-zen but it's for Baskerville 2, and I'm not sure it's the same issue as this one, because:

1) Baskerville 2 **doesn't** set `footer` to false:

```
	// Add support for Infinite Scroll.
	add_theme_support( 'infinite-scroll', array(
		'container'      => 'posts',
		'footer_widgets' => array( 'sidebar-2', 'sidebar-3', 'sidebar-4', ),
		'footer'         => 'content',
		'wrapper'        => false,
		'render'         => 'baskerville_2_infinite_scroll_render',
		'posts_per_page' => 9,
	) );
```

2) Adding the snippet to my test site did **not** fix the issue, instead it completely hid the "Older posts" button.

3) I'm not seeing the same JS error.

A workaround for my user was setting their site's IS behaviour to "Load more posts using the default theme behavior"

@jeherve  - let me know if you think this might still be related or if I should keep troubleshooting. Thank you!

**Comment by kathrynwp** [comment]
See also https://github.com/Automattic/themes/issues/1914

**Comment by aheckler** [comment]
2871677-zen, a broken JP site

**Comment by jeherve** [comment]
@kathrynwp Do you think you could test with the "Bleeding edge" option set in the  Jetpack Beta plugin? This issue has already been fixed in the development version of Jetpack, hence why this issue was closed. I'll close it again.

If you find sites where the latest development version of the plugin does not solve the issue, let me know or open a new issue. Thank you!

**Comment by Netzberufler** [comment]
I'm the author of the already mentioned Maxwell theme, which uses this implementation:
```
// Add Support for Infinite Scroll.
add_theme_support( 'infinite-scroll', array(
	'container'      => 'post-wrapper',
	'footer_widgets' => array( 'sidebar-2', 'sidebar-3', 'sidebar-4', 'sidebar-5' ),
	'wrapper'        => false,
	'render'         => 'maxwell_infinite_scroll_render',
) );
```

Infinite Scroll also breaks with the parameter `wrapper` set to `false`, but without any JavaScript error. I guess Baskerville has the same issue.

I can confirm that the bug is fixed with the latest development version, using the Jetpack Beta plugin from https://jetpack.com/download-jetpack-beta/

When can we expect an update of the normal Jetpack plugin? I already got several support requests about this and would like to see this fixed as soon as possible.

**Comment by jeherve** [comment]
Thanks for giving the Beta a try.

> When can we expect an update of the normal Jetpack plugin?

We aim to release an update later today or tomorrow, once we're done with all testing.

**Comment by Netzberufler** [comment]
Thanks so much for your reply and the quick bugfix update, I really appreciate it.
