### ISSUE TITLE
Podcast Player: Error colors visual conflict with custom colors

### ISSUE THREAD

**Issue by WunderBart** [Automattic/jetpack#15341]
#### Steps to reproduce the issue

1. Add the Podcast Player block to your page,
2. Block a request / go offline to throw the episode error,
3. In the editor, customize Player colors and notice how the error elements are not affected.
It means that e.g. when the background is set to `red`, the error text and icon will become (almost) invisible:

   <img width="609" alt="Screenshot 2020-04-07 17 27 29" src="https://user-images.githubusercontent.com/1451471/78688899-0a668400-78f6-11ea-91b9-654de394ecb9.png">

#### What I expected
To see the error elements colors work together with custom colors.

**Comment by marekhrabe** [comment]
What if we skipped applying the red color in case there is ANY background set by user and we used the same color as the rest of the text in the track (primary/secondary)? The idea is that primary/secondary vs the background will always be readable.

**Comment by WunderBart** [comment]
> What if we skipped applying the red color in case there is ANY background set by user and we used the same color as the rest of the text in the track (primary/secondary)?

Sounds good to me!

I suggest we use primary color for the icon and the `Episode unavailable.` text. For the `Open in new tab` link let's use the secondary one. Example screenshot:

![image](https://user-images.githubusercontent.com/1451471/78773492-9b3f6d00-7993-11ea-8e63-27456818169d.png)

**Comment by davemart-in** [comment]
> I suggest we use primary color for the icon and the Episode unavailable. text. For the Open in new tab link let's use the secondary one.

Sounds good to me. 👍Thanks!

**Comment by WunderBart** [comment]
Fixed by https://github.com/Automattic/jetpack/pull/15394.
