### ISSUE TITLE
Infinite Scroll: some posts are not loaded

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#15352]
#### Steps to reproduce the issue

1. Install [the Pena theme](https://wordpress.com/theme/pena) on a site running Jetpack.
2. Create about 20 posts on your site. You can give them numbers as the post title, it will be easier later on.
3. Access your home page and scroll. On the second page some posts are not loaded at all. 

I have not been able to understand exactly what is triggering this yet. I assume this is linked to #15017 but more investigation is needed.

**Comment by jeherve** [comment]
Reported in 20067334-hc.

**Comment by jeherve** [comment]
cc @dero who worked on those Infinite Scroll changes.

**Comment by edequalsawesome** [comment]
Similar issue reported in #17231389-hc, except that none of the posts are loading after reaching the bottom of the screen -- the customer is using Attache, which is a retired theme, but they reported Infinite Scroll was working until about an hour ago.

With Attache on my test site, I was able to duplicate the issue, and saw this error in the JavaScript console:

[![JavaScript Error](https://d.pr/i/qVVquQ+)](https://d.pr/i/qVVquQ)

The code snippet in #15348 didn't work for me on my test site, unfortunately.

If there's any other information I can get from my site to help with this, let me know and I'll get it for you!

**Comment by gwensmithx** [comment]
Another report 2856461-zd.

Customer is using Apostrophe 2 Theme on AT Site with the setting **Load more posts as the reader scrolls down** on and there are random posts missing. Customer has listed some in the ticket above. It seems if I turn on the default theme behaviour setting the posts are all there.

I was also able to replicate this on my test AT site.
