### ISSUE TITLE
Calendly: add Edit button toolbar

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#15357]
#### Steps to reproduce the issue

1. Create a calendly block
2. Try to change the address it points to from the block itself.
3. Ya can't

#### What I expected

To be able to change the address (in this case, the URL of my event page had been changed)

#### What happened instead

Ya can't.

**Comment by jeherve** [comment]
It is possible, but only from the block sidebar so far:

![image](https://user-images.githubusercontent.com/426388/78769911-37667580-798e-11ea-9813-f3f4b1484fc4.png)

It may be nice to add an edit option to the block toolbar, like for Pinterest:

![image](https://user-images.githubusercontent.com/426388/78770057-68df4100-798e-11ea-8ae2-f483a16798b8.png)

**Comment by creativecoder** [comment]
I think we should create a consistent pattern for all embed blocks. Core uses the edit icon, so we have all Jetpack embed blocks follow that pattern. However, we could also surface the url in the sidebar as well, as some users will have any easier time finding this.

Either way, it should be consistent for all embed blocks.

**Comment by davemart-in** [comment]
Let's just add the "Edit" button to the toolbar (Not a pencil icon) and leave the ability to edit in the sidebar to start.
