### ISSUE TITLE
AMP: Jetpack now always hides the admin bar

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#15353]
This was introduced in #14840.

> I do not think this is right. It is causing the admin bar to be hidden on all AMP pages, even when it should be displayed.
> 
> In AMP plugin 1.3 we introduced AMP dev mode support to exclude the admin bar from being subject to AMP validation constraints, allowing administrative scripts and styles to work as expected even on AMP pages.
>
> More info: weston.ruter.net/2019/09/24/integrating-with-amp-dev-mode-in-wordpress

-- https://github.com/Automattic/jetpack/pull/14840#discussion_r405001113

> if the issue is the scripts and styles that the Jetpack Likes module includes, a better way to resolve this I think is to explicitly mark them for AMP dev mode by adding admin-bar as a dependency for the scripts and styles.

**Comment by westonruter** [comment]
A quick workaround to restore the admin bar in AMP pages is via this plugin code:

```php
add_filter( 'show_admin_bar', 'is_user_logged_in', 11 );
```

But I'm not clear specifically why the admin bar was removed in the first place, other than it being an easy way to prevent AMP-invalid scripts/styles from being added to the page.

**Comment by kitchin** [comment]
Probably the same bug: https://wordpress.org/support/topic/amp-1-5-2-completely-breaks-site/

Jetpack and Amp have this weird interaction, but a third plugin is calling `is_admin_bar_showing()` which causes it to happen. That call is on the action `plugins_loaded` so I don't think you can say the third plugin is doing it too early.

See the traceback in the support topic above: https://wordpress.org/support/topic/amp-1-5-2-completely-breaks-site/page/2/#post-12643000

**Comment by philipjohn** [comment]
FYI we've already had a publisher reach out to both Happiness and Newspack team about this as they were confused where the post edit link had gone when viewing articles.

**Comment by westonruter** [comment]
Another report on the AMP plugin forum: https://wordpress.org/support/topic/amp-endpoint-error/

**Comment by westonruter** [comment]
> A quick workaround to restore the admin bar in AMP pages is via this plugin code:
> 
> ```
> add_filter( 'show_admin_bar', 'is_user_logged_in', 11 );
> ```
> 
> In plugin form: https://gist.github.com/westonruter/d168c290d6c01c107da960d48fa3dad3

Here's a better workaround that also prevents the `is_amp_endpoint()` notices from occurring when `is_admin_bar_showing()` is called before the `wp` action:

```php
// Unhook the show_admin_bar filter added in Jetpack_AMP_Support::init().
add_action(
	'init',
	function () {
		remove_filter( 'show_admin_bar', [ 'Jetpack_AMP_Support', 'show_admin_bar' ] );
	},
	2 // Because Jetpack_AMP_Support::init() happens at priority 1.
);
```
