### ISSUE TITLE
Social Icon Block: Block picks up theme's UL indent

### ISSUE THREAD

**Issue by aleone89** [Automattic/jetpack#15390]
#### Steps to reproduce the issue

1. Go to a page
2. Add and configure social I con block
3. Publish changes
4. See social icons with an indent on published page

#### What I expected

If the the social icons are left aligned, then I expect them to be left aligned, and vice versa with center and right aligned. 

#### What happened instead

Social icons are indented, and so therefore not fully left aligned or center aligned. 

This seems to happen when a theme has `ul` is defined in the theme's CSS - but not in themes that don't have this set.

So far I've seen this happen on themes TwentyTwenty and Adaline.

**Screenshots**

Please see this screenshot [https://d.pr/i/4xQAJm](https://d.pr/i/4xQAJm) (simple site)
Please see this screenshot [https://d.pr/i/wqvljh](https://d.pr/i/wqvljh)(Self-hosted JP site)

**Comment by jeherve** [comment]
Since that block is a core WordPress block, I would encourage you to report this issue in the Gutenberg repository.

In fact, it seems it's been reported here:
https://github.com/WordPress/gutenberg/issues/20893
