### ISSUE TITLE
More AMP compatibility for Sharing module

### ISSUE THREAD

**Issue by kienstra** [Automattic/jetpack#15399]
#### Is your feature request related to a problem? Please describe.
Some of the sharing buttons in the [Sharing module](https://jetpack.com/support/sharing/) don't appear in AMP.

#### Describe the solution you'd like

In AMP, the [Sharing module](https://jetpack.com/support/sharing/) should add buttons for pocket, skype, tumblr, reddit, telegram, whatsapp, and print. The print button could probably use the [print target](https://amp.dev/documentation/guides-and-tutorials/learn/amp-actions-and-events/#target:-amp).

#### Describe alternatives you've considered
None

#### Additional context
In AMP, the [Sharing module](https://github.com/Automattic/jetpack/blob/feeadafa22309b7cf0d77077c0354d9df1f74eda/modules/sharedaddy.php) now [only has](https://github.com/Automattic/jetpack/blob/feeadafa22309b7cf0d77077c0354d9df1f74eda/3rd-party/class.jetpack-amp-support.php#L364-L374) [amp-social-share](https://amp.dev/documentation/components/amp-social-share/) buttons for twitter, facebook, linkedin, tumblr, and pinterest:

![amp-social-share](https://user-images.githubusercontent.com/4063887/78957033-c4eab800-7aa9-11ea-9b32-9647da92021b.png)

...where non-AMP URLS have more buttons:

![sharing-b](https://user-images.githubusercontent.com/4063887/78957071-df249600-7aa9-11ea-8c8d-459647f9dd12.png)

Here are [all of the buttons](https://github.com/Automattic/jetpack/blob/master/modules/sharedaddy/sharing-service.php#L59-L71).

**Comment by kienstra** [comment]
**Local Development Setup**

1. In Jetpack > Settings > Sharing, toggle this on:

![sharing-s](https://user-images.githubusercontent.com/4063887/78957452-f912a880-7aaa-11ea-94e7-88022f0c6dbe.png)

2. Next to the toggle, click the link 'Configure your sharing buttons'
3. If that UI doesn't allow changing anything, you can enable more buttons with:

```php
add_filter(
	'sharing_default_services',
	static function( $enabled ) {
		$enabled['visible'] = array_merge(
			$enabled['visible'],
			[
				'print',
				'facebook',
				'linkedin',
				'reddit',
				'twitter',
				'tumblr',
				'pinterest',
				'pocket',
				'telegram',
				'skype',
				'whatsapp',
			]
		);

		return $enabled;
	}
);
```

4. In WordPress, go to the front-end of a post
5. At the bottom of the post, the sharing buttons should appear:

![amp-social-share](https://user-images.githubusercontent.com/4063887/78957600-61fa2080-7aab-11ea-92b7-67b86b366c2d.png)

**Comment by kienstra** [comment]
**Possible Approach**

The background-images in the `<amp-social-share>` components come from a stylesheet that the AMP runtime adds:
![share-im](https://user-images.githubusercontent.com/4063887/78958514-d8981d80-7aad-11ea-99e5-af953578d92f.png)

But that stylesheet doesn't have an image for every button.

For example, on adding more buttons to those used in AMP:

```diff
diff --git a/3rd-party/class.jetpack-amp-support.php b/3rd-party/class.jetpack-amp-support.php
index 73234d50d..67c063684 100644
--- a/3rd-party/class.jetpack-amp-support.php
+++ b/3rd-party/class.jetpack-amp-support.php
@@ -366,11 +366,16 @@ class Jetpack_AMP_Support {
                                /** This filter is documented in modules/sharedaddy/sharing-sources.php */
                                'data-param-app_id' => apply_filters( 'jetpack_sharing_facebook_app_id', '249643311490' ),
                        ),
-                       'twitter'   => array(),
                        'pinterest' => array(),
-                       'whatsapp'  => array(),
-                       'tumblr'    => array(),
+                       'print'     => array(),
                        'linkedin'  => array(),
+                       'pocket'    => array(),
+                       'skype'     => array(),
+                       'tumblr'    => array(),
+                       'twitter'   => array(),
+                       'reddit'    => array(),
+                       'telegram'  => array(),
+                       'whatsapp'  => array(),
                );
                $sharing_links      = array();
                foreach ( $sharing_enabled['visible'] as $id => $service ) {
```

...the newly added buttons don't have background images:

![redditpri](https://user-images.githubusercontent.com/4063887/78958883-03cf3c80-7aaf-11ea-985d-61728ca3b42a.png)

One approach would be us creating an image for each of the new ones.

As an example, here's LinkedIn's:

```css
.amp-social-share-facebook {
        background-image:url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'%3E%3Cpath fill='%23fff' d='M211.9 197.4h-36.7v59.9h36.7v175.8h70.5V256.5h49.2l5.2-59.1h-54.4v-33.7c0-13.9 2.8-19.5 16.3-19.5h38.2V82.9h-48.8c-52.5 0-76.1 23.1-76.1 67.3-.1 38.6-.1 47.2-.1 47.2z'/%3E%3C/svg%3E")
}
```

**Comment by ebinnion** [comment]
Does AMP allow icon fonts? 

If so, an alternative to creating a separate image for each of these would be to rely on the icons that we already load for the sharing buttons. For example, when I select "Icon only", I see the following on my site:

![Screen Shot 2020-04-10 at 11 58 00 AM](https://user-images.githubusercontent.com/1126811/79008363-d8863500-7b22-11ea-9ec6-fd2b74e99be2.png)

If AMP doesn't support icon fonts for this purpose, then create a new image for each of the sharing services makes sense to me.

I've pinged our design team for support on this.

**Comment by kienstra** [comment]
**Icons Fonts Work** 😄 

Hi @ebinnion,
Good question.

1. Yes, it looks like the AMP plugin [handles external icon fonts well](https://github.com/ampproject/amp-wp/blob/cfd87a240138ccfe86b2b81bdf0c819f9fcfd116/includes/sanitizers/class-amp-style-sanitizer.php#L2352-L2368).

2. If it sounds good to you, my thought is to keep using the existing [amp-social-share components](https://github.com/Automattic/jetpack/blob/025161a8d99dfef98a0f86de9328acea1e979fb2/3rd-party/class.jetpack-amp-support.php#L387).

So that if/when AMP supports analytics for them [as proposed](https://github.com/ampproject/amphtml/issues/3135), these sharing buttons will have analytics.

Keeping the `<amp-social-share>` will mean some refactoring of [sharing.css](https://github.com/Automattic/jetpack/blob/master/modules/sharedaddy/sharing.css#L244-L346) to account for the AMP selectors, like `amp-social-share`.

If you'd prefer a simpler change, we could remove the use of `<amp-social-share>`:

```diff
diff --git a/3rd-party/class.jetpack-amp-support.php b/3rd-party/class.jetpack-amp-support.php
index 67c063684..166c6a49f 100644
--- a/3rd-party/class.jetpack-amp-support.php
+++ b/3rd-party/class.jetpack-amp-support.php
@@ -28,10 +28,6 @@ class Jetpack_AMP_Support {
                 */
                remove_theme_support( 'jetpack-devicepx' );
 
-               // Sharing.
-               add_filter( 'jetpack_sharing_display_markup', array( 'Jetpack_AMP_Support', 'render_sharing_html' ), 10, 2 );
-               add_filter( 'sharing_enqueue_scripts', array( 'Jetpack_AMP_Support', 'amp_disable_sharedaddy_css' ) );
-
                // enforce freedom mode for videopress.
                add_filter( 'videopress_shortcode_options', array( 'Jetpack_AMP_Support', 'videopress_enable_freedom_mode' ) );
```

The non-AMP buttons are almost entirely valid in AMP, and only the 'Official buttons' setting looked bad in AMP:

![sharing-in](https://user-images.githubusercontent.com/4063887/79030254-bb228c80-7b5d-11ea-8f5d-a1d0afeb1be6.png)

![sharing-look-b](https://user-images.githubusercontent.com/4063887/79030293-ec9b5800-7b5d-11ea-9f3e-f2af9ccea0e4.png)

Maybe we could use the 'Icon + Text' instead of 'Official buttons', if that option is selected. 

Thanks, Eric! And have a great weekend.

**Comment by jeherve** [comment]
Related: #14926 and #12639

**Comment by kienstra** [comment]
Ah, nice! Thanks for pointing those out.

**Comment by ebinnion** [comment]
> If it sounds good to you, my thought is to keep using the existing amp-social-share components.

To clarify, does this mean to use `amp-social-share` but use the icon font icons? If so, that sounds like an ideal solution. The main benefits being:

1. If/when we add an icon in the future, it'll automatically be added and should be AMP compatible
2. The design is more consistent between AMP/non-AMP

> Only the 'Official buttons' setting looked bad in AMP:

Yea, that doesn't look great. Perhaps an option there is to force the sharing buttons to be icon only for AMP? We already do this actually for AMP, just with squared icons.

**Comment by kienstra** [comment]
>To clarify, does this mean to use amp-social-share but use the icon font icons? If so, that sounds like an ideal solution.

That's right. It'd use the same `<amp-social-share>` components that are currently used, but with the icon fonts.

> Yea, that doesn't look great. Perhaps an option there is to force the sharing buttons to be icon only for AMP? We already do this actually for AMP, just with squared icons.

Yeah, on AMP, we'll use the 'Icon only' fonts instead.

**Comment by ebinnion** [comment]
Great. This sounds good to me then. 👍
