### ISSUE TITLE
Notifications trigger an HTTPS warning in IE

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#154]
Steps to reproduce:
- Access your dashboard in IE
- In the Jetpack Menu, enable the Notifications module
- Head over to your site’s home page

You will receive the following warning:
Only secure content is displayed

Reported here: ​http://wordpress.org/support/topic/only-secure-content-is-displayed-warning-bar?replies=5#post-3681585

Ported from https://plugins.trac.wordpress.org/ticket/1748

**Comment by annezazuu** [comment]
reported here #2570610-t I asked them to disable the settings in IE 11 to fix the problem.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
