### ISSUE TITLE
Instant Search: Make overlay trigger configurable

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#15404]
We have had a few requests (including from MM) to have the overlay open immediately once the user starts interacting with a search box. We think maybe this should be configurable with two options:
- "Open Immediately"
- "Open When Results Available"

In 2020 in particular the feedback is that opening the searchbox is already jarring. It is better to be jarring once than to be jarring multiple times. This is probably especially true on mobile. Maybe we should make "open immediately" the default given the prevalence of this mobile interaction?

cc @keoshi

**Comment by keoshi** [comment]
Would “open immediately” be on `focus` or similar?

> In 2020 in particular the feedback is that opening the searchbox is already jarring. It is better to be jarring once than to be jarring multiple times.

Specifically in 2020, I don't think it would be possible to show the overlay without showing the searchbox, so unsure what the benefit would be, but I'm happy to try a different approach here.

**Comment by gibrown** [comment]
My impression was that showing the search box is fine, but that one jarring transition is better than two. I think that means that we would use on `focus` to trigger the overlay. Having this as an option does feel like the right path though.

**Comment by keoshi** [comment]
Let's add that as an option then with your suggested copy.

One nitpick on all options actually: could we use sentence case instead?

**Comment by jsnmoon** [comment]
To summarize, I'll move forward with adding two configurable options:

- "Open Immediately" (on focus)
- "Open When Results Available" (our current implementation, basically)

Is this correct?
