### ISSUE TITLE
Publicize: Not working for scheduled post

### ISSUE THREAD

**Issue by shield-9** [Automattic/jetpack#1541]
It seems Publicize is not working for scheduled posts.

When I publish post manually, it works. But when I publish post using "scheduled post" (ex: [this post](http://www.extendwings.com/blog/2015/01/wordpress-u2f-login-intro/)), nothing is posted to SNS.

Environment: WordPress 4.2-alpha-31275 + Jetpack 3.3

**Comment by jeherve** [comment]
I can't seem to reproduce. Publicize seems to work for scheduled posts on my end.

Could you let me know what other plugins are currently active on your site?

**Comment by shield-9** [comment]
I couldn't find solution, but it works now.
(maybe WP.com server-side problem)
