### ISSUE TITLE
Block Extensions - does view.js load from within editor?

### ISSUE THREAD

**Issue by mkaz** [Automattic/jetpack#15428]
The [documentation for block extensions](https://github.com/Automattic/jetpack/blob/master/extensions/README.md) states that the view.js file is automatically loaded on both the editor and theme views.

In developing a block this does not appear to be the case, I thought it might be due to creating an "experimental block" but when looking at the slideshow block for reference, the code to trigger the slideshow in the editor view is done through imports, and not the loading of view.js

I'm not sure if this is a bug or documentation error.

**Comment by jeherve** [comment]
Oh, good catch. The docs need to be updated. I took care of that in 1aedf4cda297f5dac2c48e1c7fee962ac50788b4.
