### ISSUE TITLE
linktracker_init being called with missing parameter

### ISSUE THREAD

**Issue by morganestes** [Automattic/jetpack#1544]
In `stats_template_redirect()`, `linktracker_init` is being called with parameters generated from PHP, but the `$blog` variable isn't always set, which causes the JS to fail when the page loads.

From the `stats_template_redirect()` method:
```php
var load_cmc = function(){linktracker_init($blog,$post,2);};
````
```js
function linktracker_init(b,p){window._stq.push(['clickTrackerInit',b,p]);}
```

Results in:

```js
var load_cmc = function(){linktracker_init(,0,2);};
```

Which throws
```
 Uncaught SyntaxError: Unexpected token ,
```

**Comment by jeherve** [comment]
cc @xyu

**Comment by xyu** [comment]
I think I invariantly fixed this when working on #1506 so it should no longer be a problem with the next release. However, if `$blog` is empty then there would be no way for us to correlate a page view with the blog it's coming from making it useless.

We should either:
* Bail before appending any stats JS files.
* Throw some error / warning that stats can't work without `Jetpack_Options::get_option( 'id' )` set.

**Comment by georgestephanis** [comment]
That should already be in place -- the stats module requires a connection to wpcom, which should necessitate having an id.

**Comment by georgestephanis** [comment]
@morganestes -- I'd be very eager to find out how you've got a site where `Jetpack_Options::get_option( 'id' );` isn't set.

**Comment by morganestes** [comment]
@georgestephanis So would I!

I'm going to open another issue about it, but something is causing Jetpack to get disconnected from wp.com. The plugin is still active, but I lose access to modules like Stats and Publicize. It happened again a couple of days ago, right at the time that I found this error.

**Comment by xyu** [comment]
Ok, given that this is "fixed" with the new stats code in the latest release and the fact it should never happen in the first place (with issue #1561 opened to investigate how it happened) I'm going to mark this as closed.
