### ISSUE TITLE
(8P) Podcast Player: Add Global Styles compat

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#15469]
It looks like Global Styles are only applied to the currently playing episode. Let's review our implementation and make sure the rest of the block respects those settings as well.

#### Screenshots
![screen-shot-on-2020-04-09-at-161643](https://user-images.githubusercontent.com/1398304/79482253-70719c00-7fc5-11ea-9498-61e9a03f52af.png)

**Comment by obenland** [comment]
A good start would be to remove custom font overrides and see what else needs to be done to accommodate global styles

**Comment by getdave** [comment]
Consider that we may be able to [detect Global Styles support](https://github.com/WordPress/gutenberg/pull/20530/files#diff-3924a41ad88da62082971d8c0aa8b20fR15) and apply CSS conditionally.
