### ISSUE TITLE
Instagram Block: Refresh connection token

### ISSUE THREAD

**Issue by creativecoder** [Automattic/jetpack#15460]
_Note:_ This implementation for this will be in wpcom, but I'm tracking it as a Jetpack issue since it's needed for the Instagram Gallery Block that's currently a beta block in Jetpack.

## Requirements

Users with Instagram Basic Display API tokens have their tokens automatically refreshed before they expire (after 60 days) so that the Instagram block (and WordPress.com Instagram widget) continue to display images from Instagram.

## Notes

[Facebook documentation for refreshing tokens](https://developers.facebook.com/docs/instagram-basic-display-api/guides/long-lived-access-tokens#refresh-a-long-lived-token)

Tokens are stored in Keyring on wpcom.

**Comment by pablinos** [comment]
D42310-code is the diff that has the job to be used for this process. It would be good to port this to the Keyring plugin at some point, but I'm not sure we can rely on cron there.

**Comment by creativecoder** [comment]
D42310-code should be ready for review
