### ISSUE TITLE
Connection: handle WordPress.com simple sites as well

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#15468]
#### Steps to reproduce the issue

Some Jetpack features, like the Mailchimp block, make calls to the WordPress.com API to get information about a feature. Those calls happen with `Client::wpcom_json_api_request_as_blog`:
https://github.com/Automattic/jetpack/blob/3010b47431d784ba4771188ca1da2637bb922d97/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-mailchimp.php#L116

This works well on Jetpack sites, but even though the Connection package is now available on WordPress.com, and consequently the `Client` class and its methods, those methods aren't adapted to work with WordPress.com today.

In the example of `wpcom_json_api_request_as_blog`, those requests fail because WordPress.com simple sites do not have a token:
https://github.com/Automattic/jetpack/blob/0b734a5779a6c31138d578161462faf50bc59121/packages/connection/src/class-client.php#L56-L57

We would need to update the package to take WordPress.com sites into account.

Internal reference: D35555-code

**Comment by scruffian** [comment]
I think it would be good to try to figure out a way to abstract the differences between Jetpack and Simple sites so that the connection works for all site types without having to do a different implementation for each.

**Comment by creativecoder** [comment]
@scruffian I believe you implemented this for the Latest Instagram Posts block (and many thanks for that 🙏 !)

Would you say this issue is complete, in that we now have a standard way to do this? If so, how should we document it?

If there's more to do, what is it?

**Comment by scruffian** [comment]
Almost. I just need to merge D50857-code and then I plan to do a post. I'll close this issue at the same time.

**Comment by scruffian** [comment]
I p2'd this: p7H4VZ-2LY-p2

Do you think we should add any more documentation?

Should we leave this open until the other places where this is an issue are fixed?

**Comment by scruffian** [comment]
I added a PR to update the instagram widget code from WPCOM: https://github.com/Automattic/jetpack/pull/17610/files

**Comment by creativecoder** [comment]
> Do you think we should add any more documentation?

Yes, I think one or both of these Fieldguide pages should be updated
PCYsg-eah-p2
PCYsg-alz-p2

> Should we leave this open until the other places where this is an issue are fixed?

Probably more effective to create separate issues for tracking where all the updates are needed (and maybe a milestone to collect them all). I doubt we'd be able to handle all of these in one push.

**Comment by scruffian** [comment]
Created a new issue: https://github.com/Automattic/jetpack/issues/17646
