### ISSUE TITLE
Subscriptions Block: Improve different states

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#15474]
The blog subscription block has four states depending on visitors being logged in/out and subscription status.

![subscribe_block_states](https://user-images.githubusercontent.com/4550351/79519204-84d19980-8096-11ea-9bf6-75ce8b353196.jpg)

Yet in the editor you can only see the logged-out state, with no easy way of previewing or changing other states.

![image](https://user-images.githubusercontent.com/4550351/79519301-d11cd980-8096-11ea-883c-416e649c19b2.png)

#### Describe the solution you'd like
At the very least it would be great to have alignment option for other states - as seen in the example above things look particularly bad if a heading/text above the subscription block is centered.

**Comment by apeatling** [comment]
I've noticed this too after working on #15076. I'm inclined to show the email form to all users and simply pre-fill the email field with the dotcom account email address. The states once subscribed could definitely be cleaned up.

**Comment by alaczek** [comment]
> I'm inclined to show the email form to all users and simply pre-fill the email field

Yes, I think this is a great idea! That lonely Subscribe button looks really off most of the time.
Here are some examples:

![image](https://user-images.githubusercontent.com/4550351/89847033-2e98e100-dbc6-11ea-8c7c-e7dae1ce53a3.png)

![image](https://user-images.githubusercontent.com/4550351/89847055-42dcde00-dbc6-11ea-965d-fcbaf29f5240.png)
