### ISSUE TITLE
(5P) Podcast Player: Themes' incompatibilities

### ISSUE THREAD

**Issue by WunderBart** [Automattic/jetpack#15478]
Tested Podcast Player with a few themes and listed visual conflicts I noticed in each of them. I think we can treat this issue as a master thread to report all the theme styling issues that need to be taken care of.

### TwentyEleven

<img width="635" alt="Screenshot 2020-04-17 12 21 49" src="https://user-images.githubusercontent.com/1451471/79559707-860ac280-80a6-11ea-9dd1-ac6ad81a4c4c.png">

- Podcast title doesn't inherit secondary color
- The cover image is squashed

### TwentyTwelve

<img width="647" alt="Screenshot 2020-04-17 12 28 55" src="https://user-images.githubusercontent.com/1451471/79560031-1812cb00-80a7-11ea-98f7-5e68ae4c3aff.png">

- Visited link has different color
- Cover image has border-radius

### TwentyThirteen

<img width="664" alt="Screenshot 2020-04-17 12 09 28" src="https://user-images.githubusercontent.com/1451471/79559772-a175cd80-80a6-11ea-8878-5720cc2a3941.png">

- ~~MediaElement elements have different colors~~: Won't be fixed https://github.com/Automattic/jetpack/issues/15478#issuecomment-617384963
- Visited link has a different color (`#ac0404`)
- Hovered link have different styles (underline, black color)

### TwentyFourteen

<img width="525" alt="Screenshot 2020-04-17 12 32 56" src="https://user-images.githubusercontent.com/1451471/79560317-abe49700-80a7-11ea-9542-e5690ac5dab1.png">

- Visited/hovered link has adifferent color
- ~~MediaElement have different colors & icons ⚠️~~: Won't be fixed https://github.com/Automattic/jetpack/issues/15478#issuecomment-617384963

### TwentyFifteen

<img width="718" alt="Screenshot 2020-04-17 12 36 03" src="https://user-images.githubusercontent.com/1451471/79560590-244b5800-80a8-11ea-9fdc-917b234596f1.png">

- Borders everywhere! :D

### TwentySixteen

<img width="653" alt="Screenshot 2020-04-17 12 37 32" src="https://user-images.githubusercontent.com/1451471/79560682-5066d900-80a8-11ea-8436-cfd032177067.png">

- As in TwentyFifteen - extra borders

### TwentySeventeen

<img width="697" alt="Screenshot 2020-04-17 12 39 58" src="https://user-images.githubusercontent.com/1451471/79561108-0df1cc00-80a9-11ea-8664-4ca4f6c0fb8c.png">

- Borders!
- Header title has top margin & different font-weight
- Podcast title color is not inherited from secondary

### TwentyNineteen

- Lookin' good!

### TwentyTwenty

- Lookin' good!

### Varia

- Lookin' good!

### Maywood

![image](https://user-images.githubusercontent.com/1451471/79561461-b142e100-80a9-11ea-9121-0a4f28873ee4.png)

- Hovered link color is always black (front-end only)

**Comment by obenland** [comment]
Let's remove those `li` borders & link styles globally and _lightly_ explore what a CSS reset for the block might look like and which consequences that would entail

**Comment by jeryj** [comment]
https://github.com/Automattic/jetpack/pull/15504 fixes almost all of the issues with very minor CSS overrides overall.

The only issues it doesn't fix is the twenty fourteen and twenty thirteen media players. They both (but especially twenty fourteen) include CSS specific to the media elements player. We could increase the specificity and add a few more things to address twenty thirteen, but twenty fourteen would include many changes _only relevant to twenty fourteen_. 

In my opinion, as both themes are 6 - 7 years old and would require so many specific changes just for them, that it's not worth addressing.

**Comment by obenland** [comment]
Nice job! Yes, let's not invest more time in those mejs styles.
