### ISSUE TITLE
Calendly: Change buttons to a standard link for AMP requests

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#15498]
Once the new Button inner block PR (#15370) is merged we need to use it in Calendly and update it to make it AMP compliant.

See the original PR (#14630 by @pablinos) for more info:

> AMP strips out `onClick` handlers, so when the button version of
the block is rendered we should change it to a standard link to the Calendly
appointment page.
>
> We could probably get around this by attaching the click handler in
another way, but it would still be good to treat an AMP request
differently.

**Comment by aaronrobertshaw** [comment]
As part of #15863 the Calendly block will render the buttons as links. There is still a little work that needs doing for the AMP requests however. If the Calendly block sets any of the default color styles for the button they'll be missing on AMP views.

**Comment by Copons** [comment]
> As part of #15863 the Calendly block will render the buttons as links. There is still a little work that needs doing for the AMP requests however. If the Calendly block sets any of the default color styles for the button they'll be missing on AMP views.

I think the color issue you are mentioning is the same as this one: https://github.com/Automattic/jetpack/issues/15697
I'm a little unsure on how to tackle it to be honest, but we can at least disregard it in the Calendly (and others) Button replacement PRs.

**Comment by Copons** [comment]
Fixed by #15863
