### ISSUE TITLE
VideoPress: activating the module breaks the "Add New" button in /wp-admin/upload.php

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1551]
Steps to reproduce:
1. Go to Jetpack > Settings, and activate the VideoPress module
2. Go to `yoursite.com/wp-admin/upload.php`
3. Click on "Add New". Here is what should be displayed: 

![screen shot 2015-01-27 at 5 44 04 pm](https://cloud.githubusercontent.com/assets/426388/5922467/1c138cca-a64c-11e4-83ae-1177699e5a6d.png)

Unfortunately, nothing happens as long as VideoPress is active.

**Comment by nickmomrik** [comment]
If I get rid of https://github.com/Automattic/jetpack/commit/48d4aa77c06645ebd67c3fb4f966044b3c147395 the button works again.

**Comment by kraftbj** [comment]
@georgestephanis do you recall what JS glitches SHA: 48d4aa7 / #1198 was fixing?

**Comment by jeherve** [comment]
@kraftbj The problem first came up in #1950928-t.

> When clicking to load the VideoPress library, it loads but doesn't return any videos, although there are videos on the linked WordPress.com site.
>
> According to the user, the first video starts appearing after 7 minutes. Looking at the request, I do not get any results.
> I could reproduce the bug on a test site of mine, although I get a response with a list of all videos. They still don't get displayed in the library

**Comment by dereksmart** [comment]
(Copy of my comment on an internal p2)

It’s the additional `submit_button()` <a href="https://github.com/Automattic/jetpack/blob/master/modules/videopress/videopress.php#L710">#</a> in videopress’ uploader that’s causing the problem.

Quick thought – wondering if instead of having a separate button, the upload could hook onto insert video so it’s uploaded right before it’s inserted?

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/videopress-module-breaks-front-end-use-of-the-media-uploader?replies=1&view=all

> We're making use of the media uploader for our front-end plugin. The only issue is that the VideoPress module is calling the admin-only function `submit_button` within `Jetpack_VideoPress->print_media_templates` which isn't available on the front-end and is preventing any further code execution.

**Comment by dbtlr** [comment]
This is addressed in #5326
