### ISSUE TITLE
Comments: add_filter to remove "Website" field

### ISSUE THREAD

**Issue by nicosmaris** [Automattic/jetpack#15510]
#### Is your feature request related to a problem? Please describe.

Yes, Jetpack doesn’t have a built-in option to remove the field "website" of Jetpack Comments.

#### Describe the solution you'd like

An add_filter method in php could help.

#### Describe alternatives you've considered

As the Jetpack comments form run in an iframe, it’s not possible to use CSS to hide only that one form field, so you’ll likely need to modify the plugin using custom PHP code via a functionality plugin. We’re not able to help you with the code you’d need for that, though.

https://wordpress.org/support/topic/how-to-remove-website-field-from-comment-form-2

**Comment by jeherve** [comment]
Related: #477 and #13277

**Comment by nicosmaris** [comment]
you can close this assuming that the following still applies, thanks.

https://github.com/Automattic/jetpack/issues/477#issuecomment-136015098

**Comment by jeherve** [comment]
I'm afraid it still does, yes. I'll add a reference to your issue and @mention in the other one though, this way if we ever reopen this you'll get a notification!
