### ISSUE TITLE
Site Logo: outputs empty logo link even if the logo is not set

### ISSUE THREAD

**Issue by dashkevych** [Automattic/jetpack#15540]
I've just noticed that the `jetpack_the_site_logo()` function outputs an empty link if the logo is not set.

Site (Jetpack v8.4.2; WordPress v5.4): https://demo.themesharbor.com/appetite/
Customizer screenshot: https://snipboard.io/8IgnpM.jpg

It happens at WordPress.com and WordPress.org (Jetpack).

**Comment by kristarella** [comment]
+1 for changing this

I had a WordPress.com user report that their site title no longer links to the home page and I believe it's because this function is causing a weird nesting of links:

```
							<h1 class="site-title">
								<a href="..." rel="home">
									<a href="..." class="site-logo-link" rel="home" itemprop="url"></a>									<span>...</span>
								</a>
							</h1><!-- .site-title -->
```

**Comment by scottsweb** [comment]
@dashkevych could you provide the code snippet you are using on your site for the logo area. This feature was largely replaced by the core implementation: https://developer.wordpress.org/themes/functionality/custom-logo/

The Jetpack feature is looking for either the image to be set via core or via Jetpack, if neither are found, then the link appears to be output on its own, that doesn't seem ideal, but most themes seem to check for the presence of a logo before calling the function. 

You can see an example of this (using the core function) here: https://github.com/WordPress/twentynineteen/blob/2a8e9d8aa9d6f1150e58b21ee513a0f000a7d972/template-parts/header/site-branding.php#L12-L14

**Comment by dashkevych** [comment]
Support added via the following function:

`add_theme_support( 'site-logo', array( 'size' => 'large' ) );`

OR

```
add_theme_support( 'site-logo', array(
  'header-text' => array(
    'site-title',
    'site-description',
  ),
'size' => 'full',
) );
```

Then the following function is used to display the logo:

```
function themeslug_the_custom_logo() {
	if ( function_exists( 'jetpack_the_site_logo' ) ) {
		jetpack_the_site_logo();
	}
}
```

Here is a live demo:

(1) https://appetitedemo.wordpress.com/
(2) https://fortunedemo.wordpress.com/

**Comment by dashkevych** [comment]
Using `has_custom_logo()` does not work when support is declared via Jetpack (`add_theme_support( 'site-logo', array( 'size' => 'large' ) );`).

`has_custom_logo()` outputs `false` even if the custom logo is set.

--

**"...if neither are found, then the link appears to be output on its own, that doesn't seem ideal..."**
Any plans to fix it? Are there any particular reasons to show an empty link when nothing is set?

**Comment by dashkevych** [comment]
So, I've done some tests and it looks like Jetpack now provides a backward compatibility for a native logo functionality (https://developer.wordpress.org/themes/functionality/custom-logo/). 

It means that we can safely remove a support declared via `add_theme_support( 'site-logo');` and a native one instead. This is great!

**Comment by scottsweb** [comment]
> It means that we can safely remove a support declared via add_theme_support( 'site-logo'); and a native one instead. This is great!

That would be my suggested approach too. I would also use:

https://developer.wordpress.org/reference/functions/has_custom_logo/

Before calling `the_custom_logo()`. This will ensure that a logo has been set, before trying to output something onto the page. 

```
<?php if ( has_custom_logo() ) : ?>
		<div class="site-logo"><?php the_custom_logo(); ?></div>
	<?php endif; ?>
```

We also have some Jetpack wrapper functions for the same thing but you might as well use core now. Am I OK to close this issue?

**Comment by dashkevych** [comment]
We can close this issue. Thank you for adding a backward compatibility.
