### ISSUE TITLE
Instagram Gallery Block: Improve caching and disconnect flow

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#15551]
#### Improve Transient Naming

The Instagram Gallery block caches the galleries in a `'jetpack_instagram_gallery_block_' . $access_token . '_' . $count` transient.

We should avoid caching it by block's image count, but by the maximum count possible, so that, for example, a gallery of 3 images would reuse the first 3 from the cache of 30 images.

#### Delete Transient on Disconnection

Removing the count from the transient key would also help us with the disconnect flow.
When disconnecting an Instagram account, it will stop all other blocks associated to the same token but with different image counts, at the next images fetch.

#### Deactivate All Blocks Using the Disconnected Connection

To make sure all blocks will _immediately_ stop using the disconnected connection, we might want to introduce a new custom Redux store to the editor, that keeps track of the Instagram tokens used in any given editor instance.
Disconnecting a block would update the state and all affected block would react accordingly.

**Comment by creativecoder** [comment]
@Copons does #15628 resolve this issue, or is there more to do?

**Comment by Copons** [comment]
Correct, that and https://github.com/Automattic/jetpack/pull/15623 together! :)
