### ISSUE TITLE
Search: Conflict with Sitemaps?

### ISSUE THREAD

**Issue by jeremypaavola** [Automattic/jetpack#15570]
We have a report 2908620-zen that the following fatal is generated when Yoast's XML Sitemaps feature is enabled alongside the new Jetpack search, even if Jetpack Sitemaps is deactivated:

>Fatal error: Uncaught Error: Class 'Jetpack_Search_Helpers' not found in /homepages/.../wp-content/plugins/jetpack/modules/search/class.jetpack-search.php:353 Stack trace: #0 /homepages/.../wp-includes/class-wp-hook.php(287): Jetpack_Search->set_filters_from_widgets('') #1 /homepages/.../wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #2 /homepages/.../wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /homepages/.../wp-settings.php(540): do_action('init') #4 /homepages/.../wp-config.php(171): require_once('/homepages/21/d...') #5 /homepages/.../wp-load.php(37): require_once('/homepages/21/d...') #6 /homepages/21/d552708976/htdocs/clickandbu in /homepages/.../wp-content/plugins/jetpack/modules/search/class.jetpack-search.php on line 353

Reporting here as requested by @gibrown

**Comment by EuropeanWilderness** [comment]
Hi, deactivating Jetpack lets YOAST Premium 10.4. generate and display the XML sitemaps. Enabling it again and it creates the fatal error again. Therefore is directly linked to the new search issue.
