### ISSUE TITLE
Button Block: Improve selection area when parent block is floating

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#15580]
The Button block is rendered in a way that, if it's the only inner block, it doesn't fill the entire parent block area, so that clicking outside the button will select the parent block.

This doesn't work when the parent block is floating (align left/right).

**Comment by Copons** [comment]
Added priority and size labels: this is an edge case that might be possible to be solved with CSS only.

**Comment by Copons** [comment]
I've been investigating this for a while, but I can't find a good solution.

The issue is in how Gutenberg handles floating blocks.
Upon selecting a `left` or `right` alignment, it wraps the block in a `.wp-block[data-align="left"]` (or right) div, with `height: 0`, and then `float: left` the block itself, basically making the parent block disappear if it doesn't contain anything else other than the inner button.

E.g.
```html
<div class="wp-block" data-type="parent/block">
  <div class="block-editor-inner-blocks">
    <div class="block-editor-block-list__layout">
      <div <!-- this div only exists when the inner block is floating -->
        class="wp-block"
        data-align="left"
        style="height: 0" <!-- example style -->
      >
        <div
          data-type="inner/block"
          style="float: left" <!-- example style -->
        />
      </div>
    </div>
  </div>
</div>
```

Ideally, we could solve this by _clearfix_-ing the `.wp-block` wrapper, but we don't have a proper way to target it via CSS, since it appears outside the inner block, and I'd say it's not cool doing so via JS.

Luckily, Gutenberg 8.3 greatly improves the inner/parent blocks relationships, adding a new "select parent" button appearing when hovering on the inner block's icon:

<img width="281" alt="Screenshot 2020-06-22 at 15 40 43" src="https://user-images.githubusercontent.com/2070010/85300801-ef3ff500-b49e-11ea-89e6-7175cf878788.png">

I think that we could settle on this behaviour for now, unless anyone comes up with a better idea. 🤔

**Comment by creativecoder** [comment]
> I think that we could settle on this behaviour for now, unless anyone comes up with a better idea. 🤔

In that spirit, let's close this for now. Seems like changes in Core would be required to make this any better without an unreliable JS hack.
