### ISSUE TITLE
SSO - opens site in pop-up window on "session expired"

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#1558]
Steps to reproduce: 
- Enable SSO
- Log out of your site in another window
- Wait for "Expired Session" pop-up
- Click "Log in using wordpress.com"

It technically works, but fails to close the popup and instead loads the site in the popup

![screen shot 2015-01-27 at 3 15 34 pm](https://cloud.githubusercontent.com/assets/426388/5927032/1c373a3e-a670-11e4-979a-19467835d36a.png)

**Comment by v18** [comment]
This seems to be fixed. Here are the steps I tried:

1. Log in using user1 in one browser
2. Log in using user1 in a different browser
3. Turn on SSO in browser # 1
4. Log user1 of all other sessions in browser 1
5. Refresh in browser 2, saw the log in page. Clicking the 'log in' button does not show the dashboard in a popup.

@dereksmart I'm closing this issue as solved, feel free to re-open with new steps if you still see it.
