### ISSUE TITLE
Instagram Gallery Block: Disconnect option breaks if another block disconnects

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/jetpack#15588]
If you add multiple Instagram Gallery Blocks on a single page/post, and then 'Disconnect' one of the blocks, the Disconnect call on the other block fails with a 403, so block can't be disconnected.

Low priority as edge case and workaround is to delete the block and add again, and then it will show as disconnected.

#### Steps to reproduce the issue
1. Apply #15544 and D42457 if not already merged
2. Add an Instagram Gallery block to a post or page, and connect it to an instagram account
3. Add a second block to the same post or page - it should automatically connect
4. Chose the option to 'Disconnect' this second block
5. Then try and 'Disconnect' the first block - the disconnect API call fails with a 403

The same thing happens if I disconnect the block on one post and then try and disconnect an existing block on another post.

![disconnect](https://user-images.githubusercontent.com/3629020/80433426-01902d80-894b-11ea-99c5-9944b8897b4d.gif)

#### What I expected
Either all blocks on the page using that token should disconnect, or the disconnect option should work even if already run on another block.

**Comment by creativecoder** [comment]
@Copons Did we fix this one already, or is it still a problem?

**Comment by Copons** [comment]
@creativecoder You're correct, this doesn't happens anymore, since disconnecting a block doesn't trigger any API requests anymore.
