### ISSUE TITLE
After the Deadline unescaping escaped html/php

### ISSUE THREAD

**Issue by diddledan** [Automattic/jetpack#156]
I just wrote a post with ATD turned ON with the following code (raw html, as visible in the text editor, not the visual version):

```
<pre><code>&lt;?php add_action('init', 'menu_excerpt__add_menu_field'); function menu_excerpt__add_menu_field() {
     if (!is_callable('bh_add_custom_menu_fields'))
         return;
     bh_add_custom_menu_fields(array(
         'excerpt' =&gt; array(
            'description' =&gt; 'Excerpt',
            'type' =&gt; 'textarea',
            )));
}
?&gt;</code></pre>
```

as you can see I correctly escaped my < and > symbols to &amp;lt; and &amp;gt; (actually I let the wysiwyg editor do that for me when I pasted it). Unfortunately after ATD has checked the text it changes to the following code, as visible from view-source on the front-end (i.e. what the visitor's browser sees and renders):

```
<pre><code><!--?php add_action('init', 'menu_excerpt__add_menu_field'); function menu_excerpt__add_menu_field() {
     if (!is_callable('bh_add_custom_menu_fields'))
         return;
     bh_add_custom_menu_fields(array(
         'excerpt' =--> array(
            'description' =&gt; 'Excerpt',
            'type' =&gt; 'textarea',
            )));
}
?&gt;</code></pre>
```

as you can see in this second code the initial &amp;lt; and a supposedly matching &amp;gt; have both been converted to an HTML comment tag thereby hiding the bulk of my code in the visitor's browser.

Disabling ATD (the ONLY change I made) in the JetPack admin screen and recreating the mangled code will correctly post and be visible.

However, re-enabling ATD and hitting update on the same post that I just saved with ATD disabled will reliably re-mangle/break the same section of code. This proved in my mind that the issue is within the ATD JetPack code or in the ATD service backend.

**Comment by brbrr** [comment]
I wasn't able to reproduce it with Jetpack 6.3-beta

Proofreaded text in text editor: 
<img width="931" alt="edit post jetpack6test mystagingwebsite com at pressable wordpress 2018-06-28 14-28-06" src="https://user-images.githubusercontent.com/5654161/42031649-b238b782-7adf-11e8-8a4a-df2bc781d720.png">

Rendered post page(https://jetpack6test.mystagingwebsite.com/2018/06/tested/)
<img width="813" alt="tested jetpack6test mystagingwebsite com at pressable 2018-06-28 14-28-27" src="https://user-images.githubusercontent.com/5654161/42031656-b830fcda-7adf-11e8-96bc-b97dc4d28c35.png">
