### ISSUE TITLE
Facebook count double on https://

### ISSUE THREAD

**Issue by remcotolsma** [Automattic/jetpack#1560]
The Facebook share buttons displays count likes double. Jetpack requests the count of the http:// and the https:// URL's:

* https://github.com/Automattic/jetpack/blob/3.3/modules/sharedaddy/sharing.js#L14-L16
* https://github.com/Automattic/jetpack/blob/3.3/modules/sharedaddy/sharing.js#L19-L25

In the Facebook update count callback function those values are added to an total count:

* https://github.com/Automattic/jetpack/blob/3.3/modules/sharedaddy/sharing.js#L62-L77

Example:

* https://www.lentis.nl/2015/01/19/altijd-blue-monday/
* https://graph.facebook.com/?ids=http%3A%2F%2Fwww.lentis.nl%2F2015%2F01%2F19%2Faltijd-blue-monday%2F,https%3A%2F%2Fwww.lentis.nl%2F2015%2F01%2F19%2Faltijd-blue-monday%2F&format=json&callback=WPCOMSharing.update_facebook_count&_=1421939521666

**Comment by jeherve** [comment]
Related: 91c10c3c6c1090aa86197066c5732ba6b9f1b311

cc @justinshreve

**Comment by shield-9** [comment]
It seems Facebook consider `https://~` and `http://~` is same if the value of `<link rel="canonical">` matches.

**Comment by sc0ttkclark** [comment]
Having the same issue here as well

**Comment by sc0ttkclark** [comment]
Perhaps you can add an argument and filter for forcing http or https (default blank) in the localized variable for sharing-js, which, if set, would only add one or the other to the Facebook and Twitter service urls. Then, in the update_facebook_count you'd also want to change this:

`if ( 'undefined' != typeof data[Object.keys(data)[1]].shares )`

to 

`if ( 'undefined' != typeof Object.keys(data)[1] && 'undefined' != typeof data[Object.keys(data)[1]].shares )`

in case there's only one URL sent to Facebook (when forcing http or https).

**Comment by richardmtl** [comment]
cc @aduth

**Comment by aduth** [comment]
@sc0ttkclark, can you provide me with an example URL you're having issues with? I've found that sometimes Facebook caches invalid counts, which can be cleared up if you force a rescrape of all related using the Open Graph debugger:

https://developers.facebook.com/tools/debug/og/object/

**Comment by sc0ttkclark** [comment]
I've privately sent you the URL in question.

**Comment by aduth** [comment]
It's not immediately relevant to this issue, but we're going to face another problem with Facebook's [impending removal of 1.0 APIs on April 30](https://developers.facebook.com/docs/apps/changelog) on which these count requests rely. From that point onward, there will be no official API for retrieving share counts that won't require an authenticated, rate-limited request. With this in mind, we may need to preempt the deprecation by removing sharing counts from the custom button styles.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/publicize-likes-numbers-problem-with-facebook?replies=5&view=all

**Comment by jkudish** [comment]
I think we can close this now, @aduth?

**Comment by jeherve** [comment]
As per #1946, we now use a different method to get Facebook Sharing counts. This can now be closed.

**Comment by aduth** [comment]
@jkudish: Correct, the issue here should be resolved by #1946. Thanks for closing, @jeherve.
