### ISSUE TITLE
Earn blocks: save page before taking off to connect to Stripe

### ISSUE THREAD

**Issue by artpi** [Automattic/jetpack#15602]
The Premium Content block’s Stripe connect button saves before going to Stripe’s form while the Payments and Donations blocks does not. It warns you that you are about to lose your changes so you have to save or lose your progress. Let's match the behaviour of the premium content block for a smoother experience.

Please read this: pbAPfg-k3-p2

**Comment by mmtr** [comment]
Fixed by https://github.com/Automattic/jetpack/pull/16961
