### ISSUE TITLE
Older YouTube embeds not displaying videos in Safari or Firefox

### ISSUE THREAD

**Issue by 319heads** [Automattic/jetpack#15610]
I run a site with many years worth of older YouTube videos and it's been reported by many of our users that no older videos are displaying for Safari (desktop + iphone) or Firefox users.

When jetpack is active the older embeds (~2011 and older) are not displaying at all in these browsers (Safari shows a blank area equal to the width and height where the video should be displayed and Firefox shows nothing). If jetpack is de-activated the videos display without issue in all browsers.

This occurs for all videos that use the following style of embed code that YouTube used to provide:

`<object width="640" height="510"><param name="movie" value="http://www.youtube.com/v/s237ilu0c6g?fs=1&amp;hl=en_US&amp;rel=0&amp;hd=1" /><param name="allowFullScreen" value="true" /><param name="allowscriptaccess" value="always" /><embed src="http://www.youtube.com/v/s237ilu0c6g?fs=1&amp;hl=en_US&amp;rel=0&amp;hd=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="allowfullscreen" width="640" height="510" /></object>`

**Steps to reproduce the issue in any theme and even with jetpack as the sole active plugin:**
1. Create a new post and insert the above object embed code into a classic block or html block.
2. View the post in Safari or Firefox and the video will not be displayed if jetpack is active.
3. Use the 'Convert to Blocks' option on the classic or html section and the video will then display in the admin but will still be invisible on the front-end.</br></br>

**In the admin the videos look like this in the visual editor:**

<img width="781" alt="Screen Shot 2020-04-29 at 10 45 07 AM" src="https://user-images.githubusercontent.com/1848048/80616562-ade31a00-8a06-11ea-9847-e6d3e26016f0.png">

**If you convert the post to blocks, the youtube video will show in the admin:**

<img width="854" alt="Screen Shot 2020-04-29 at 10 48 06 AM" src="https://user-images.githubusercontent.com/1848048/80620261-614e0d80-8a0b-11ea-88bc-da555bb59b1a.png">

**However, it will still be missing in the front-end in Safari and Firefox whether still classic or converted to blocks:**

<img width="1022" alt="Screen Shot 2020-04-29 at 10 48 38 AM" src="https://user-images.githubusercontent.com/1848048/80620268-6317d100-8a0b-11ea-9465-20bbcc1a3ae8.png">

**Comment by scottsweb** [comment]
I am not convinced there will be a fix for this. The main issue appears to be the URL you are using for your embed now 404's:

```
http://www.youtube.com/v/s237ilu0c6g?fs=1&amp;hl=en_US&amp;rel=0&amp;hd=1
``

The new format looks like this:

```
https://www.youtube.com/watch?v=Bey4XXJAqS8
```

Can you confirm the video is still present at the location you expect it to be. 

I also note the lack of `https` on the URL, if your site is using SSL, there is a chance that browsers will block the request for security reasons. 

It would be useful if you could either provide the URL of a broken page, or the [browsers console output](https://www.wickedlysmart.com/hfjsconsole/) (scroll to Safari section) when the page is loaded. This might give us some pointers as to what the issue is.

**Comment by scottsweb** [comment]
Closing due to lack of reply.
