### ISSUE TITLE
Jetpack connection drops, causing errors with Publicize and Stats

### ISSUE THREAD

**Issue by morganestes** [Automattic/jetpack#1561]
I have Jetpack installed on multisite and activated for one of the sites. At irregular intervals, Jetpack disconnects itself from wp.com (but stays activated) with no indication in either the Jetpack or server logs as to why.

We notice this when Publicize stops working. I then reconnect Jetpack to wp.com and reconnect the Publicize accounts. After I connect the first one, all the previously connected Publicize accounts reappear and work normally.

During the time that the plugin is in this active but disconnected state, Stats throws a JavaScript error (see #1544 for details).

**Comment by georgestephanis** [comment]
Can you take a snapshot of this db query immediately after connecting, and then when you get problems?

```mysql
SELECT * FROM `wp_options` WHERE `option_name` LIKE 'jetpack_%'
```

(don't drop them here)

My guess is that something is messing up your `id` option which is serialized in the `jetpack_options` option.

**Comment by morganestes** [comment]
We have a separate staging environment with the same JP connection info, but haven't had any problems with it. The production connection has dropped 3x since November, but without any pattern that we're aware of.

I'll alert Systems so they can grab the queries from the DB as soon as we notice any problems, then let you know when we have the data.

**Comment by georgestephanis** [comment]
Some staging to production deploy patterns delete the jetpack I'd option to
prevent identity conflicts, as Jetpack is a two way connection.

**Comment by kraftbj** [comment]
Also, are you deactivating/disconnecting Jepack on the staging site? If you're changing the connection on the staging site, that would inform WP.com to terminate the token, in effect, breaking the connection with production.

**Comment by morganestes** [comment]
@georgestephanis We don't deploy from staging to production in this case. We do deploy theme code, but plugins aren't version controlled.

@kraftbj I don't think we've made any changes to staging, but I'll look into it to see if there's any noticeable patterns on there around the time production got disconnected.

**Comment by morganestes** [comment]
@georgestephanis  It happened again, so I'm going to get Systems to run the query, reconnect, and run it again. What should I be looking for?

Also, if I set staging to development mode, will that prevent conflicts with production since there won't be any connection to wp.com?

**Comment by georgestephanis** [comment]
If you could, also grab the contents of the `jetpack_log` option and email
it all to me directly -- gs@automattic.com

**Comment by morganestes** [comment]
@georgestephanis I emailed you the data a couple of weeks ago (on 2/13). Have you had a chance to review it yet?

**Comment by morganestes** [comment]
We've finally narrowed it down to a single cause: flushing memcached. Any time we manually flush the cache, or when it's triggered by some other action, Jetpack loses the connection.

We've done it three times this past week for various server and code updates, and each time the connection was broken. I've checked the Jetpack Debug screen and get the connection error message (XMLRPC is working fine, but JP says it can't connect), but after reconnecting the account successfully we're immediately back in business.

We suspect that when we flush memcached it's also flushing the cached `wp_options` table, and that's what's causing Jetpack to go haywire. That would account for nothing in the log showing a disconnect (since a disconnect wasn't triggered from the admin side), but doesn't explain why Jetpack logs don't show it being reconnected each time.

If there's anything else we can do to test from our end we're happy to help. In the meantime our client has asked me to investigate finding a more stable solution that doesn't rely on the wp.com connection. :person_frowning:

**Comment by samhotchkiss** [comment]
@georgestephanis - any ideas on this?

**Comment by jeherve** [comment]
Closing this as it seems it was handled via email.

@morganestes If this is still happening, feel free to let us know!

**Comment by morganestes** [comment]
@jeherve Nope, wasn't resolved via email yet. 

I'm off the project where we discovered the issue, but I'll check with the new team and see if they're still experiencing the issue.
