### ISSUE TITLE
Revue: required label is not aligned properly

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#15626]
When adding a new Revue block to a post, you'll notice that the Required labels aren't aligned properly in the editor:

![image](https://user-images.githubusercontent.com/426388/80739242-677ce080-8b16-11ea-85a4-3da77f56adbc.png)

On the frontend, everything looks good:
![image](https://user-images.githubusercontent.com/426388/80739281-75cafc80-8b16-11ea-934b-5c7a60801980.png)

This can be reproduced with different themes, including Twenty Twenty and Twenty Seventeen.

**Comment by truongwp** [comment]
Hi @jeherve,

I would like to contribute to this issue. I hope it does not conflict with others' work.

My solution is using `<span contenteditable>` instead of `<textarea>` for the label edit. The label edit will be like this:

`<span contenteditable>Email address</span> <span>(required)</span>`

With this markup, the `(require)` text is always at the end of the label, like on the frontend.

How do you think?

**Comment by Copons** [comment]
This issue should be automatically sorted with https://github.com/Automattic/jetpack/pull/15362.

To give more context: the Revue block reuses the `JetpackFieldLabel` component from the Contact Form block.
Currently, `JetpackFieldLabel` uses the Gutenberg's `PlainText` component, which renders a `<textarea>`.
With the Contact Form v2 update, [`JetpackFieldLabel` will use the `RichText` component instead](https://github.com/Automattic/jetpack/pull/15362/files#diff-b03ffc932b1c9aa6cb19e488f828291b).
`RichText` renders a `contenteditable` element (in this case an actual `<label>`) which, exactly as proposed by @truongwp, will fix the "required" position. 🙂 

<img width="662" alt="Screenshot 2020-05-05 at 18 03 15" src="https://user-images.githubusercontent.com/2070010/81094602-a8e90380-8efb-11ea-99a7-b2eb0ad44192.png">

**Comment by truongwp** [comment]
That's good. I will try the above PR. Thanks.

**Comment by davemart-in** [comment]
This should be fixed now that  #15362 has merged. Closing this issue.
