### ISSUE TITLE
 Button block: better default values for radius

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#15627]
#### Steps to reproduce the issue

1. Add a new Revue block to a post
2. Click on the button
3. You'll notice that the Radius option does not have a default filled in:

![image](https://user-images.githubusercontent.com/426388/80739507-deb27480-8b16-11ea-85d5-c65a8b8e13e9.png)

**Comment by Copons** [comment]
Just noting that this is the same behaviour of the Core Button block.

<img width="996" alt="Screenshot 2020-04-30 at 19 16 34" src="https://user-images.githubusercontent.com/2070010/80744803-233e1000-8b17-11ea-8d8c-10b44f41e02c.png">

**Comment by jeherve** [comment]
👍 Closing as duplicate of https://github.com/WordPress/gutenberg/issues/17596
