### ISSUE TITLE
Recurring Payments: wrong language passed

### ISSUE THREAD

**Issue by artpi** [Automattic/jetpack#15621]
This is submitted by @fresatomica 

On this site : https://locosporlosgatos.es/apadrina
Subscription is set up. The recurring payments checkout iframe opens with this url:
https://subscribe.wordpress.com/memberships/?blog=164604816&plan=739&lang=**es_ES**&pid=737&redirect=https%3A%2F%2Flocosporlosgatos.es%2Fapadrina&display=alternate

And the translation is not working (open in incognito)- should be in spanish

With this link
https://subscribe.wordpress.com/memberships/?blog=164604816&plan=739&lang=**es**&display=alternate

it works:
<img width="813" alt="Zrzut ekranu 2020-04-30 o 13 04 51" src="https://user-images.githubusercontent.com/3775068/80703508-33d49300-8ae3-11ea-935a-70c935212bcf.png">

Seems the problem is in:
https:// code . a8c . com /diffusion/WP/browse/trunk/wp-content/mu-plugins/subscribe-to-blogs.php$99

We should be translating these lang strings into different format.

**Comment by n3f** [comment]
Up for review: https://code.a8c.com/D43139

**Comment by artpi** [comment]
🚢  !
