### ISSUE TITLE
OpenTable Block: Additional CSS classes not populating field on reload

### ISSUE THREAD

**Issue by aaronrobertshaw** [Automattic/jetpack#15639]
Reloading the editor after saving an additional CSS class under an OpenTable block's Advanced settings, loses the CSS class from that field. 

#### Steps to reproduce the issue

1. Open a post to edit
2. Add an OpenTable block using the button style
3. Select OpenTable block and add additional CSS class under block's advanced settings
4. Save the post
5. View the post in a new tab
6. Confirm that the new CSS class has been added to block's container
7. Switch tab back to post's edit page and reload
8. Re-select the OpenTable block
9. See that CSS class is no longer in CSS field under block's advanced settings
10. Save the post again
11. Switch back to tab viewing the post and refresh
12. See that the CSS class has been lost from the block's container

#### What I expected
The additional CSS field would retain the CSS classes added to it and saved.

#### What happened instead
The additional CSS field is not populated with previously saved CSS classes.

**Screenshots**

![OpenTableBlockCSS](https://user-images.githubusercontent.com/60436221/80773715-0c8ecc00-8b9e-11ea-903c-5ec2dfdc9522.gif)

**Comment by creativecoder** [comment]
@aaronrobertshaw Do you know if this an issue on any other blocks? (I'm wondering if this is an issue with Gutenberg, rather than the block, itself)

**Comment by aaronrobertshaw** [comment]
@creativecoder I haven't seen it with any other blocks. I can confirm the additional CSS classes field works as expected with the Calendly, Mailchimp, paragraph and button blocks.

**Comment by aaronrobertshaw** [comment]
Looks like this is related to the method by which the injected `className` attribute value is determined [in Gutenberg](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/hooks/custom-class-name.js#L153). 

It serializes a block without the custom `className` attribute and compares the css classes parsed from the root element of that, against the actual saved block's root element. The [opentable block saves](https://github.com/Automattic/jetpack/blob/master/extensions/blocks/opentable/index.js#L41) content within short syntax fragment tags preventing this from working.

Switching those tags to `<div></div>` allows the `className` to be parsed. Some further testing is needed to see what effects wrapping the block content would create.
