### ISSUE TITLE
Revue Block: Unexpected border when editing form titles

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#15643]
#### Steps to reproduce the issue

1. Start in block editor
2. Add a Revue block and fill in your username
3. In the appeared Revue form, click on one of the input titles
4. See unexpected border, and reposition

#### What I expected
No reposition, and no border

#### What happened instead
![screencast 2020-05-01 12-29-16](https://user-images.githubusercontent.com/5654161/80796378-b030aa00-8ba7-11ea-8111-eda2581ecdda.gif)

**Comment by davemart-in** [comment]
Note: The boxes are showing up there because you can edit the labels:

![Screen Recording 2020-05-25 at 10 48 AM](https://user-images.githubusercontent.com/5634774/82823322-5b661380-9e75-11ea-8d2a-61ede2a93e25.gif)
