### ISSUE TITLE
Subscriptions block: handle connected and subscribed states on WordPress.com

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#15649]
This is a follow-up for #15107.

In testing D40775-code, I realized that we can have a big difference between the look of the block in the editor and the block on site, for logged in users (like the admins) and folks already subscribed.

The block may look like this on the frontend:
![image](https://user-images.githubusercontent.com/426388/80822953-01f32780-8bdc-11ea-8d6d-0e897dbcf9fd.png)

Even though you may have spent some time customizing the block in your editor:

![image](https://user-images.githubusercontent.com/426388/80823009-146d6100-8bdc-11ea-8860-6608f6037372.png)

You won't get to see those changes on the frontend of your site though, because you're logged in.

I am not sure how / if this should be addressed.

cc @apeatling

**Comment by apeatling** [comment]
I think the UI needs to be retained on the front end in all circumstances, possibly with an extra message below to denote subscribed status.

**Comment by jeherve** [comment]
Closing as duplicate of #15474.
