### ISSUE TITLE
Image Compare Block: Add AMP support

### ISSUE THREAD

**Issue by mkaz** [Automattic/jetpack#15653]
#### Describe the solution you'd like

Add AMP support for new Image Compare block using the `<img-image-slider>` component:
https://amp.dev/documentation/examples/components/amp-image-slider/

Note: The component currently does not support vertical orientation, the ideal solution is to detect when a site is using the AMP plugin, and to not surface the vertical option if it is. This prevents the user from expecting one behavior in the editor that will not be matched when viewing.

See: #15598

**Comment by kraftbj** [comment]
AMP errors: https://github.com/Automattic/jetpack/issues/16093
