### ISSUE TITLE
Site Stats → Configure: Takes you to search results page, instead of what user specifically requested

### ISSUE THREAD

**Issue by abcxyz-m** [Automattic/jetpack#15657]
#### Steps to reproduce the issue

1. Go to: **Jetpack** → **Site Stats** → **Configure** in WP Admin

#### What I expected
A page that lets me Configure Stats.

#### What happened instead
I'm presented with a page that is basically search results, and inexplicably includes Jetpack Backup as the primary result.

**Screenshots**

![](https://d.pr/i/jdEwZI+)
Image Link: https://d.pr/i/jdEwZI

This flow previously took you to a page that **only** had Stats Configuration. Granted, that page previously wasn't formatted as nicely as this one currently is - I personally think it's a bit confusing that the thing I just asked for is "folded" shut by default, though.

**Comment by mzakariya** [comment]
I'm _guessing_ this is because "Site Stats" are now baked into **Settings** → **Traffic** → **Site stats**, and this approach can reuse some things. This has the side effect of making the button a bit confusing, though:

![](https://d.pr/i/Z65NNB+)

**Comment by jeherve** [comment]
Noting that we've now added headings that should make fixing this a bit easier:
#15440.

**Comment by scottsweb** [comment]
Checked on two Jetpack sites and this is working as expected for me.

![Screenshot 2020-06-11 at 14 38 29](https://user-images.githubusercontent.com/411945/84386255-e6226e80-abe8-11ea-9100-eb7d04ec1efc.png)

**Comment by jeherve** [comment]
Closing since the new Stats screen doesn't include a configure option.
