### ISSUE TITLE
SimplePie: ensure compatibility with Podcast player

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#15662]
The SimplePie library has been updated in WordPress trunk from version 1.3.1 to version 1.5.5. We'll want to make sure the Podcast player still works well with this updated version. 

> Here are some resources that may help you:
>
> A full list of changes in the library:
> - https://github.com/simplepie/simplepie/blob/master/CHANGELOG.md
> The changeset updating SimplePie in WordPress:
> - https://core.trac.wordpress.org/changeset/47733
-- https://make.wordpress.org/plugins/2020/05/01/simplepie-updated-for-wordpress-5-5/

**Comment by davemart-in** [comment]
Thanks for the heads up @jeherve!

**Comment by obenland** [comment]
Still works as expected. Tested with:

https://anchor.fm/s/22b6608/podcast/rss
https://allthepresidentslawyers-feed.kcrw.com/
https://distributed.blog/category/podcast/feed/
http://shoptalkshow.com/feed/podcast/
http://feeds.nightvalepresents.com/aliceisntdeadpodcast
https://www.omnycontent.com/d/playlist/aaea4e69-af51-495e-afc9-a9760146922b/8f57a588-9582-4b05-89c9-aaa001627e6f/5e92c398-71a9-4767-8181-aaa001627e86/podcast.rss

**Comment by jeherve** [comment]
Thanks for testing!
