### ISSUE TITLE
Carousel: cannot scroll up from Comments area in Firefox

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#15678]
#### Steps to reproduce the issue

1. Create a gallery and pick the option to link images to attachment page.
2. Go to Jetpack > Settings and enable Carousel.
3. On one of the images in the gallery, leave a few long comments.
4. Open that Carousel modal in Firefox, scroll down to see the comments, until you don't see the image in your viewport.

You will then not be able to scroll back up.

Original report: p8oabR-uL-p2#comment-4213

**Comment by apeatling** [comment]
Will be fixed by https://github.com/Automattic/jetpack/pull/20107
