### ISSUE TITLE
Search: document/allow applying a filter from the search box and/or from a button

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#15685]
It should be possible to add default filters to the search box and create links that open the overlay with a filter already added. We should test these and create some documentation of how to use them on https://jetpack.com/support/search/#faq

The filters in the search widget look like this:
```
<a href="#" class="jetpack-search-filter__link" data-filter-type="post_types" data-val="page">Page&nbsp;(2)</a>
```

And I think we can use something like that in general and it will just work.

Some use cases:
- Add a search box with [get_search_form()](https://developer.wordpress.org/reference/functions/get_search_form/) and apply a filter when it is used (maybe this needs JS to add the filter to the URL?)
- A code snipped to add a button with a search icon to the page which will open the overlay with an applied filter
- How to add a search button in Gutenberg with a filter added

**Comment by jsnmoon** [comment]
> There are cases where a particular page or set of pages should be able to have a default filter applied, but the end user should still be able to undo that filter. e.g. searching on a jobs page (related to #15685). In this case you do want to let the user customize the widget since the widget could then be set to only be shown on certain pages. Likely in the future we will just want a block that triggers the overlay with filters already applied. (@gibrown, from a discussion in #16072)

@gibrown, could you go into more detail about what pain point we're trying to address by letting site operators apply search filters via arbitrary HTML elements? Would we want to allow these elements to also define a preset search query to increase search result relevancy?

**Comment by jsnmoon** [comment]
@gibrown, any updates on this issue?

**Comment by gibrown** [comment]
Ya, I implemented this in the sidebar of https://wordpress.com/support/tutorials/business-website-tutorial/#choosing-a-theme and have also created some search boxes. I want to create examples in the support documentation for all of these cases since there are clearly cases where it is helpful. But when I started doing that I then got into needing to restructure the support pages...

**Comment by gibrown** [comment]
I rewrote the support pages and have included this in the main customization page: https://jetpack.com/support/search/
