### ISSUE TITLE
Infinite Scroll: Render filter ignoring custom query on second page load

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#1568]
see https://www.screenr.com/KLtN

**Comment by dereksmart** [comment]
Since the custom query is not being compared against the "duplicated posts" array on second page load, I believe this is not a bug and will with transients.

**Comment by samhotchkiss** [comment]
^ @dereksmart what do you mean by "I believe this is not a bug and will with transients."

**Comment by dereksmart** [comment]
will *work if the user stores the array in transient. typo

**Comment by samhotchkiss** [comment]
So, should we wontfix this, @dereksmart ?
