### ISSUE TITLE
Podcast Player: add save

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#15682]
We currently do not save anything to post content when you add a block to a post. This is problematic for folks who may deactivate Jetpack later on, and for folks accessing the post outside of the WordPress context (RSS feeds, subscription emails, ...)

I think we should aim to have something simple saved in the post content, such as  a link to the RSS feed at least.

**Comment by davemart-in** [comment]
A link to the RSS feed sounds reasonable. 

I'm not sure what someone expects if they deactivate Jetpack, but I suspect folks might do it mistakenly in which case it might be nice to have a reference to the RSS feed URL still showing.
