### ISSUE TITLE
No syntax highlighting in Markdown block

### ISSUE THREAD

**Issue by joendotcom** [Automattic/jetpack#15695]
## Steps to reproduce the issue

1. Create a new post
2. Add a Markdown block
3. Add [markdown-it](https://markdown-it.github.io/) compatible code into the block

## Info

Tested with Jetpack 8.5 on WordPress 5.4.1.

This is a regression since release, internal ref p1HpG7-5EW-p2

Originally reported in 2934781-zen

### Example post

https://joentest1.mystagingwebsite.com/2020/05/markdown-block-test/

#### What I expected

Code block with syntax highlighting.

Should look like this:

![Screen Shot on 2020-05-06 at 13-02-10](https://user-images.githubusercontent.com/8905369/81169838-d5ebf380-8f99-11ea-90ed-59b99431f692.png)

#### What happened instead

Code block, but no syntax highlighting:

![Screen Shot on 2020-05-06 at 13-03-36](https://user-images.githubusercontent.com/8905369/81169956-0b90dc80-8f9a-11ea-9535-2b130c4123dd.png)

**Comment by jeherve** [comment]
The Markdown feature processes Markdown into HTML on your site; it does not provide syntax highlighting features. You'll see your code wrapped in `pre` and `code` HTML markup, but the actual coloring is not handled by Markdown.

If you want syntax highlighting, you will consequently need to use a different plugin, such as the 2 following plugins:
- https://wordpress.org/plugins/syntaxhighlighter/
- https://wordpress.org/plugins/code-syntax-block/
