### ISSUE TITLE
WordAds Block: Remove toggle from canvas

### ISSUE THREAD

**Issue by apeatling** [Automattic/jetpack#15700]
The Ads block looks to be used quite a bit among users. It also has the same problem of using toggles in the canvas of the block — it should be moved to the sidebar. 

![image-9](https://user-images.githubusercontent.com/1464705/81233219-1e5fdd00-8fab-11ea-825e-afbe1c746708.png)

**Comment by jeherve** [comment]
I believe this was done in #15120. Is this what you had in mind?

**Comment by apeatling** [comment]
Yes! Perfect. Closing this one out.
