### ISSUE TITLE
Podcast Player: Disable block preview

### ISSUE THREAD

**Issue by WunderBart** [Automattic/jetpack#15707]
Currently, the Podcast Player's block preview in the inserter doesn't look very appealing:

![image](https://user-images.githubusercontent.com/1451471/81292259-8fff6000-906b-11ea-8bda-bc795a615599.png)

Similar blocks like Embed, YouTube, or Spotify have the preview disabled, so let's do the same for the Player.

#### Environment:

WP.com
Gutenberg v8.0.0

**Comment by marekhrabe** [comment]
Disabling is definitely the quickest fix we can do 👍 

If we don't want to disable our preview, it would be super neat if we could pass our block a new attribute which will fill the `podcastData` and skip any URL/API logic and directly rendered it.

**Comment by davemart-in** [comment]
Happy to skip it for now.
