### ISSUE TITLE
Sharing: Allow replacing FB "Like" button with "Recommend" button

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#1570]
FB's like button allows you to change the text to "Recommend":

https://developers.facebook.com/docs/plugins/like-button

![screen shot 2015-01-30 at 11 19 19 am](https://cloud.githubusercontent.com/assets/5512652/5978988/de7f9d18-a871-11e4-8abd-eceb4f15097b.png)

Maybe we could add a filter that supports this?

However, if we end up switching to the Share button instead (#1441), this ticket becomes moot.

**Comment by samhotchkiss** [comment]
What's the difference between liking and recommending?  Is it just different terminology or things treated differently?

**Comment by aheckler** [comment]
I believe it's just a terminology difference.

**Comment by jeherve** [comment]
@aduth Following 82cbc63e5bddeb0a9a261d769e3c579180f591b5, and considering the different options Facebook offers (Like, Share, Recommend), I was wondering if it were possible to add a filter to the button output to allow site owners to overwrite the official button's output to pick their own Facebook button variant.

What do you think?

**Comment by aduth** [comment]
@jeherve, I like that idea. It should be fairly straight-forward to support, only requiring minor variations in the `data-` attributes provided to the Facebook widget. I can aim to set aside some time for it, but I've got a few higher-priority items on my plate at the moment.

**Comment by 7diac** [comment]
Thank you to consider the opportunity to set back the Like button. It is not just a question of terminology, they act different even the counter sum them. The like button is really more fast and easy, it is instantaneous and people are accustomed to Like things. The sharing button open an old style popup and ask for a second action (to compile and send the form).

Thank you again for your work.

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/sharing-11

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/facebook-like-button-38

**Comment by jenhooks** [comment]
2195694-t requested here.
