### ISSUE TITLE
Site Health: Jetpack Prevents Test from Officially Completing

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/jetpack#15709]
#### Steps to reproduce the issue

1. Start with Jetpack active and connected.
2. Go to Tools → Site Health to run the health check. Notice that it never completes. 

![Screen Shot on 2020-05-07 at 10-33-34](https://user-images.githubusercontent.com/22805865/81307836-18233c80-904f-11ea-8d0c-f820e6c3a00f.png)

1. Disconnect Jetpack and then deactivate.
2. Go to Tools → Site Health. Notice that the test completes. 

#### What I expected

Jetpack should allow Site Health to complete the test and display the status (Good, Needs improvement). 

#### What happened instead

The results never loaded. 

Reported in 2947807-zen

**Comment by jeherve** [comment]
I can't seem to reproduce on my own sites at the moment. I wonder if this may be caused by a specific test that fails and breaks things.

Do you think it'd be possible to click to expand the tests at the bottom of the page, and see if the Sync Health test is listed there?

**Comment by kraftbj** [comment]
I'm able to duplicate it on my personal site and in my docker instance. I'm working on tracking down exactly what's causing it.

**Comment by kraftbj** [comment]
Narrowed it down to when `show_in_site_health` is `false`, there will be a fatal JS error in the console `TypeError: data.badge is undefined`.

**Comment by jeherve** [comment]
Also in 
https://wordpress.org/support/topic/site-health-results-are-still-loading/
https://wordpress.org/support/topic/site-health-stats-stuck-in-results-are-still-loading-with-jetpack-8-5/

**Comment by kraftbj** [comment]
The Core side of this is being tracked in https://core.trac.wordpress.org/ticket/50145

On our side, we should return a well-formed test result. On the Core side, they could not fatally fail if a plugin doesn't return a well-formed result.

**Comment by rajsquid** [comment]
Hi, just wondering if this issue has been fixed and updated to next release. I am getting the same error but not if I deactivate the plugin. Any clue is highly appreciated.

**Comment by kraftbj** [comment]
@rajsquid The issue has been fixed and will be in the next release, which is currently slated for release on the first Tuesday of June. If we have any releases before that, it will be included in that release.

**Comment by rajsquid** [comment]
Thank you @kraftbj for the update.
