### ISSUE TITLE
Block Categories Updates

### ISSUE THREAD

**Issue by mtias** [Automattic/jetpack#15708]
The [following new categories](https://github.com/WordPress/gutenberg/pull/19279#issuecomment-621322775) are set to be coming to Gutenberg shortly. There are mappings in place, so all blocks would end up somewhere. However, it'd be worth to look at registering things like Tiled Galleries or Slideshow in the Media group. (I'd imagine Jetpack would need to retain older categories as well for previous versions of Gutenberg / WP.)

**Comment by sirreal** [comment]
Recommendations for how to safely start using new categories: https://github.com/WordPress/gutenberg/pull/19279#issuecomment-635982767:

```js
var hasFormattingCategory = wp.blocks.getCategories().some( function( category ) {
   return category.slug === 'formatting';
} );

wp.blocks.registerBlockType( 'my-plugin/my-block', {
   category: hasFormattingCategory ? 'formatting' : 'media',

   // ...
} );
```

**Comment by davemart-in** [comment]
Looks like this has been picked up by the Good Mountain team. I'm removing this from the Manage Group backlog.
