### ISSUE TITLE
Contact Form: 16314 Character limit in emails

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1572]
If you have more than 16314 characters in your message, you will not be sent an email, however it does go to the Feedbacks section.

**Comment by richardmtl** [comment]
16314..   There must be a secret code in that somewhere.

**Comment by dereksmart** [comment]
I just tested with 37272 characters in the message, and I received an email.  Can anyone else reproduce?

**Comment by dereksmart** [comment]
@mikeyarce confirmed that this no longer happens in 3.3.1 - was able to reproduce it with a message of 130,000+, which pretty much makes it a non-issue.
