### ISSUE TITLE
Search: 'Display "Powered by Jetpack"' option doesn't save

### ISSUE THREAD

**Issue by anaemnesis** [Automattic/jetpack#15735]
#### Steps to reproduce the issue

1. Navigate to **Appearance --> Customize**
2. Open the **Jetpack Search** options
3. Uncheck the `Display "Powered by Jetpack"` option
4. Click **Publish**
5. Close the Customizer, and refresh the site to see that the Jetpack footer is still present
6. Navigate back to the Customizer
7. The `Display "Powered by Jetpack"` option is once again checked

Tested Jetpack Search in Twenty Twenty.

#### What I expected

The `Powered by Jetpack` text and logo should be hidden, while the Customizer option should save state.

#### What happened instead

The `Powered by Jetpack` text and logo continued to display, and the Customizer option did not save state.

**Screenshots**

![Screen Recording 2020-05-10 at 01 26 pm](https://user-images.githubusercontent.com/426388/81554698-876a9a80-9387-11ea-9d93-3c17b0a11a27.gif)

**Comment by gibrown** [comment]
@jeremypaavola I wasn't able to reproduce this with 2020 or other themes.

Any errors on this test site or something? What role did the user have on the site?

**Comment by jeremypaavola** [comment]
@gibrown The gif above is from my sandbox:

- Admin user role
- Twenty Twenty theme active
- Jetpack, WooCommerce, and the WordPress Importer plugins were active
- Akismet, AMP, and Hello Dolly were inactive

- Issue persists for me with only Jetpack installed and active
- The issue persists with Jetpack active and _only_ Search enabled
- No console errors
- `debug.log` is clean
- No PHP errors that I can find

**And then...**

- Deleted my `error.log`
- Deleted `debug.log`
- **The search display option worked**

No memory errors and disk isn't at capacity, so I'm not sure why that worked, but now the option is working. I'll follow up with the user asking them to try the same, huh.

**Comment by gibrown** [comment]
That is super confusing. @jsnmoon @bluefuton any ideas?

**Comment by jsnmoon** [comment]
I suspect this issue to be related to how the Customizer's publish function works, but I haven't been able to figure it out so far. The fact that deleting the log files fixes the issue makes it even stranger.

**Comment by jsnmoon** [comment]
There's a potential fix for this in https://github.com/Automattic/jetpack/pull/15989 which changes how we store and retrieve boolean-like values for these customizer checkboxes.
