### ISSUE TITLE
Publicize: Don't go beyond "more" tag when building og:description

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#1573]
As it stands now, if you have a post/page like so:

```
Short bit of content.

<!-- more -->

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor 
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud 
exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute 
irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla 
pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia 
deserunt mollit anim id est laborum. 
```

... Publicize will build an `og:description` that ignores the more tag:

`<meta property="og:description" content="Short bit of content. Lorem ipsum dolor sit amet, consectetur adipisicing..." />`

You could make a case, though, that we should stop if we find a more tag and not pull in content that lies beyond it.

Came up in this thread: https://wordpress.org/support/topic/how-to-limit-jetpack-open-graph-description-with-more-tag

**Comment by chaselivingston** [comment]
Looks like according to https://github.com/Automattic/jetpack/blob/df4d33a2089398096c1c73853e86f2b3c8b7883d/functions.opengraph.php#L69 the post excerpt should be used when creating the og:description, and I don't believe the excerpt is supposed to go beyond the `<!--more-->` tag, so if it is there's probably an issue.

**Comment by ms-studio** [comment]
If the post excerpt has content, then it should certainly be used. But it may happen that people use the `<!--more-->` tag while leaving the excerpt field blank.

Also, the excerpt isn't enabled for Pages, but the `<!--more-->` tag can be used on Pages, and pages also get their og:description.

**Comment by aheckler** [comment]
The above PR should work for pages and posts. :smile:

**Comment by DiegoQueiroz** [comment]
I think this issue should be temporary be reopened, since commit 77f3f75 caused a regression in changes done by pull request #1600.
