### ISSUE TITLE
Image Compare Block: JavaScript error on upload

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#15743]
https://github.com/Automattic/jetpack/pull/15598/files/274ddf76d0e329b3878c2c98fff668e8e4fc7842#diff-16ba0c2319cc7d7beca274462864405d

I didn't experience any issues with this in Jetpack, but ran into the following error in the editor, after uploading the first image in the block, when testing D42965-code:

`Uncaught TypeError: Cannot read property 'classList' of null`

******

From #15598.

**Comment by mkaz** [comment]
I tested this on my sandbox with the merged version and did not see any errors.
What browser were you testing with? Do you still see the same error?

I added a bit of a small defensive check in #15746

**Comment by jeherve** [comment]
> What browser were you testing with? Do you still see the same error?

That was in Chrome. I can't reproduce anymore, so not sure what was going on at the time.
