### ISSUE TITLE
Image Compare Block: add additional alignment options

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#15740]
> I think it would be nice if the block supported wide and full sizes, since that can be handy for images we want to display.

> Good suggestion, we should add this feature.

> Also agreed, but also V2, or at the very least a followup PR. This one may seem trivial, but I have that tingling sensation that it is absolutely not at all. Already now we had some challenges with the responsiveness of the block, I imagine the hooks we have to fire to re-fire the JS will take more time to get right than we think it does.

*******

From #15598.

**Comment by p3ob7o** [comment]
It would be nice if the size of the images was defined through CSS and not with inline styles so that one could change _it if they really wanted_ :)

**Comment by supernovia** [comment]
Noting a request here:
https://wordpress.org/support/topic/the-new-before-after-image-comparison/

**Comment by ACEkin** [comment]
As supernovia mentioned, I favor adding width adjustments to the image compare block.
