### ISSUE TITLE
Eventbrite: Centred button is no longer centred in the editor

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/jetpack#15761]
I've realised a centred button is no longer appearing correctly in the editor. The button appears correctly on the front of the site.

**In the editor**
![Screenshot 2020-05-12 at 13 48 09](https://user-images.githubusercontent.com/908665/81693279-96208280-9457-11ea-8b1e-246e48b5e86d.png)

**Comment by aaronrobertshaw** [comment]
There is currently a [PR that will update this block's button](https://github.com/Automattic/jetpack/pull/15918) with the new shared button component. I couldn't replicate this alignment issue using that PR.

**Comment by tullyhansen** [comment]
Looks like customer may be seeing something similar in the wild – however, the issues is in both editor and published page.

- ticket: https://woothemes.zendesk.com/agent/tickets/3040297
- example: https://atexansfitness.com/book-club/
  <img width="640" alt="image" src="https://user-images.githubusercontent.com/3039301/84036666-de907900-a9e0-11ea-97bd-be6316b5a037.png">

**Comment by frontdevde** [comment]
**Dotcom Manage Janitor rotation note Mon, Jun 22nd:**
Talked to @Copons who just merged https://github.com/Automattic/jetpack/pull/15918. He offered to take care of this issue as it's related to his work on updating the Eventbrite button. Thus removing this issue from the Janitor board and assigning it over to @Copons (thank you!).
