### ISSUE TITLE
Category links in subscription emails are broken when a custom slug is used.

### ISSUE THREAD

**Issue by jenhooks** [Automattic/jetpack#1576]
If a custom URL-friendly slug is assigned when creating a category, category links in Jetpack subscription emails will be broken, since the link URL in the email is derived from the name of the category rather than the slug.

Steps to reproduce:
1. Install Jetpack on a self-hosted WordPress blog. Make sure permalinks are set to Post Name format.
2. Subscribe to the blog by email.
3. Create a new category with a name that is different than the slug name (as in screenshot below)

![cat_slug2](https://cloud.githubusercontent.com/assets/7585054/6004148/aac09144-aace-11e4-98ff-5e647abc8e39.png)
1. Write and publish a test post assigned to that category.
2. Check email and click on the category link in the footer of the subscription email, a 404 results.

In my test post's subscription email, the category URL in the email's footer is:

http://jenhooks.wpsandbox.me/?taxonomy=category&term=general-news

But the category URL on my test blog is actually:

http://jenhooks.wpsandbox.me/category/general/

Ticket reference: 2067962-t ported from 3201-wpcom

**Comment by jeherve** [comment]
This is still an issue. Adding this to the Sync label, maybe Poseidon can take a look.

**Comment by enejb** [comment]
I followed the directions above and it seem to work as expected for me. 

As long as sync works I think this should work as expected. 
closing this now. Feel free to open this if this is not the case
