### ISSUE TITLE
Admin Page: getDefaultProps warnings

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#15773]
#### Steps to reproduce the issue

1. Navigate to Jetpack > Dashboard
2. Notice the following warnings in your browser console.

```
Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
```

*******

Originally reported in #15757.

**Comment by darssen** [comment]
I have tried to reproduce it and I'm unable. Am I doing something wrong?

**Comment by jeherve** [comment]
You're right, it seems to be fixed now. I couldn't find the PR that moved us away from `createClass` in the last few components where we used it, but we seem to be good now! Closing.
