### ISSUE TITLE
CDN: Wikimedia images are broken

### ISSUE THREAD

**Issue by fresatomica** [Automattic/jetpack#15772]
#### Steps to reproduce the issue

1. Enable CDN on your site
2. Add an image and link it to another site
3. Click on the published image
4. See error that the link does not exist

#### What I expected
Once you've clicked the image you should be redirected to the correct link.

#### What happened instead
`https://i0.wp.com/` is added before the URL and so the link does not work.

![Screen Shot 2020-05-13 at 10 39 04](https://user-images.githubusercontent.com/40177971/81790685-071e7380-9506-11ea-94b7-b09bd622382d.png)

Reported [here.](https://wordpress.org/support/topic/i0-wp-com-in-image-link/)

**Comment by jeherve** [comment]
Good catch. This should be fixed in the next release with #15774.
