### ISSUE TITLE
Subscriptions Block: Invalidates when edited in different language

### ISSUE THREAD

**Issue by sirreal** [Automattic/jetpack#15776]
If a Subscription Block is added to a post with one localization, then subsequently edited in another localization, the block will be invalidated with no good way of recovering. The default texts in the block must be maintained, customization of the texts will prevent invalidation.

Core Gutenberg is working out how to handle situations like this:
- https://github.com/WordPress/gutenberg/issues/21932
- https://github.com/WordPress/gutenberg/issues/7604

Some of the default block attributes are localized with `__`:

https://github.com/Automattic/jetpack/blob/db3e47183b64a343aa594fd32a815483bfdf302d/extensions/blocks/subscriptions/attributes.js#L7-L10
https://github.com/Automattic/jetpack/blob/db3e47183b64a343aa594fd32a815483bfdf302d/extensions/blocks/subscriptions/attributes.js#L19-L22

These attributes are stored directly in the save function:

https://github.com/Automattic/jetpack/blob/db3e47183b64a343aa594fd32a815483bfdf302d/extensions/blocks/subscriptions/save.js#L24-L47
https://github.com/Automattic/jetpack/blob/db3e47183b64a343aa594fd32a815483bfdf302d/extensions/blocks/subscriptions/save.js#L105-L129

The block may be saved with a localized text `Enter your email address`, then when the editor loads and validates the block content, it finds an unexpected localization (e.g. _`Dirección de correo electrónico`_) and determines that the block content is not valid.

I wrote about the problem of "impure save" here in more detail: pafL3P-kL-p2
In this case, translations implicitly leak into the block's save, rendering them impure and susceptible to invalidation.

This causes the following issues:
- https://github.com/Automattic/jetpack/issues/15475
- https://github.com/Automattic/jetpack/issues/15076#issuecomment-603448947
- https://github.com/Automattic/wp-calypso/issues/41364#issuecomment-627642782

This has been present since the very first iteration of the block: https://github.com/Automattic/wp-calypso/pull/28887

cc: @obenland @iamtakashi 

#### Steps to reproduce the issue

1. Create a new site
1. Connect Jetpack
1. Enable [Subscriptions](https://jetpack.com/support/subscriptions/) (`/wp-admin/admin.php?page=jetpack#/discussion`)
1. Create a new post (`/wp-admin/post-new.php`)
1. Add a *Subscription Form* block (Start typing `/subscription`)
1. Save the post
1. Change the site language (e.g. Español) (`/wp-admin/options-general.php`)
1. Update localizations (`/wp-admin/update-core.php`)
1. Open the previous post
1. The block will be invalidated with errors in the console.

Save (English):

![Screen Shot 2020-05-13 at 11 46 57](https://user-images.githubusercontent.com/841763/81798121-f2df7400-950f-11ea-83c7-25e80e9d122e.png)

Load (Spanish):

![Screen Shot 2020-05-13 at 11 47 40](https://user-images.githubusercontent.com/841763/81798131-f672fb00-950f-11ea-805e-2727c31a432e.png)

```
Block validation: Block validation failed for `jetpack/subscriptions` ({name: "jetpack/subscriptions", icon: {…}, …

Content generated by `save` function:

<div class="wp-block-jetpack-subscriptions">[jetpack_subscription_form show_subscribers_total="false" show_only_email_and_button="true"]</div>

Content retrieved from post body:

<div class="wp-block-jetpack-subscriptions">[jetpack_subscription_form show_only_email_and_button="true" custom_background_button_color="undefined" custom_text_button_color="undefined" submit_button_text="Subscribe" submit_button_classes="undefined" show_subscribers_total="false" ]</div>
```

**Comment by sirreal** [comment]
I added `8.6` milestone from #15475.

**Comment by jeherve** [comment]
cc @apeatling who's been working on some improvements to the Subscriptions block.

**Comment by sirreal** [comment]
I was doing some additional testing and it doesn't seem like you can modify the placeholder text through the block UI at all.

**Comment by simison** [comment]
Ah bummer, this was tested but somehow slipped still through https://github.com/Automattic/jetpack/pull/15107#discussion_r401088736

**Comment by apeatling** [comment]
@sirreal Was this tested with the updates to the block in master? I couldn't reproduce this when I was working on it, but I probably wasn't doing it correctly.

**Comment by sirreal** [comment]
@apealing Yep, I just spun up a new site with Jetpack beta "Bleeding edge" build and was able to reproduce the issue following the instructions in the description.

**Comment by apeatling** [comment]
Few options I can think of:

1. Remove the defaults as translatable for these two strings. The user can update the input button text on their own, and we can make the placeholder text editable.

2. Remove the defaults as translatable and add logic to the edit component to check for a different translation and update it once the block has been loaded (assuming the value hasn't been edited).

3. ??

**Comment by akirk** [comment]
I think `source: html` would be a solution here, since [by default the text is stored in the HTML comment](https://developer.wordpress.org/block-editor/developers/block-api/block-attributes/) which can lead to incompatible data (English attribute, translated HTML).

**Comment by creativecoder** [comment]
Note that this affects several blocks

- [Subscriptions](https://github.com/Automattic/jetpack/blob/3466b0681a195db76416077b8d3647f877f41448/extensions/blocks/subscriptions/attributes.js#L9)
- [Eventbrite](https://github.com/Automattic/jetpack/blob/3466b0681a195db76416077b8d3647f877f41448/extensions/blocks/subscriptions/attributes.js#L9)
- [Calendly](https://github.com/Automattic/jetpack/blob/3466b0681a195db76416077b8d3647f877f41448/extensions/blocks/calendly/attributes.js#L21)
- [Revue](https://github.com/Automattic/jetpack/blob/3466b0681a195db76416077b8d3647f877f41448/extensions/blocks/revue/attributes.js#L13)
- [Contact Form](https://github.com/Automattic/jetpack/blob/5fbf71770770dc16d20eae74c07946493a89945a/extensions/blocks/contact-form/attributes.js#L9)

**Comment by iamtakashi** [comment]
> Note that this affects several blocks

I'm not sure if it was the same reason, but the Map block and the Contact Info block were also broken (invalidated) with the translations for all the Mag 16, and I had to manually fix in the json files. It was really time-consuming, and the issue blocks us to deploy layouts regularly.

**Comment by creativecoder** [comment]
Note, I updated my comment above to indicate that it's not an exhaustive list

> (and maybe others--I only searched through the `attributes.js` files, so this may have missed blocks that set default attributes in other ways)

**Comment by apeatling** [comment]
> I think source: html would be a solution here, since by default the text is stored in the HTML comment which can lead to incompatible data (English attribute, translated HTML).

In the case of the contact form and subscription blocks, the `source: html` is not going to work because the save function creates a shortcode that is then rendered via the backend at runtime. 

It could work for the other blocks that do not do this however.

**Comment by apeatling** [comment]
I tried this with the Calendly block, but I'm not having any luck with selecting via source: html or text because of the server side rendering.

**Comment by creativecoder** [comment]
@lessbloat This might be a good candidate for the Manage Janitorial rotation

**Comment by davemart-in** [comment]
@creativecoder by the looks of it, this is likely too complex for the Janitor rotation.

**Comment by Copons** [comment]
> Note that this affects several blocks
> 
>     * [Subscriptions](https://github.com/Automattic/jetpack/blob/3466b0681a195db76416077b8d3647f877f41448/extensions/blocks/subscriptions/attributes.js#L9)
> 
>     * [Eventbrite](https://github.com/Automattic/jetpack/blob/3466b0681a195db76416077b8d3647f877f41448/extensions/blocks/subscriptions/attributes.js#L9)
> 
>     * [Calendly](https://github.com/Automattic/jetpack/blob/3466b0681a195db76416077b8d3647f877f41448/extensions/blocks/calendly/attributes.js#L21)
> 
>     * [Revue](https://github.com/Automattic/jetpack/blob/3466b0681a195db76416077b8d3647f877f41448/extensions/blocks/revue/attributes.js#L13)
> 
>     * [Contact Form](https://github.com/Automattic/jetpack/blob/5fbf71770770dc16d20eae74c07946493a89945a/extensions/blocks/contact-form/attributes.js#L9)
> 
> 
> (and maybe others--I only searched through the `attributes.js` files, so this may have missed blocks that set default attributes in other ways)

I've just run a quick test, and of these only Subscriptions seems to be affected.
(TBH I haven't tried _all_ Contact Form variations, but it shouldn't matter)

The difference is that those blocks don't save the localized attributes in the block content, whereas Subscriptions does.

#### Examples

```html
<!-- wp:jetpack/revue {"revueUsername":"test"} -->
<div class="wp-block-jetpack-revue">
	<!-- wp:jetpack/button {"element":"button","text":"Subscribe"} /-->
	<a class="wp-block-jetpack-revue__fallback" href="https://www.getrevue.co/profile/test">
		https://www.getrevue.co/profile/test
	</a>
</div>
<!-- /wp:jetpack/revue -->
```

Revue has all the fields labels and placeholders as localized attributes, plus the button text, which is an attribute of the Button inner block.

No field labels/placeholders are saved in the block content, as the form is built server-side.

The inner Button doesn't break because the parent block is actually defining it with the localized attribute: in other words, we are actually _setting_ its text attribute with the localized string.
The side effect is that changing the site language won't also change the Button text.
This might be considered an issue, though, but a different one.

```html
<!-- wp:jetpack/subscriptions -->
<div class="wp-block-jetpack-subscriptions wp-block-jetpack-subscriptions__supports-newline">
	[jetpack_subscription_form
		subscribe_placeholder="Enter your email address"
		submit_button_text="Sign Up"
	]</div>
<!-- /wp:jetpack/subscriptions -->
```

Subscriptions (example trimmed for readability), instead, saves the defaults in the block content.
As pointed out by @sirreal, when the block loads with a different translation, it tries to match it with the block content, and fails, breaking the block.

I'm still trying to figure out a good solution, though.
SSR-ing the block is not a good one, as we want the shortcode to stay in the post content.
Maybe instead of having attribute _defaults_, we could actually save them as attribute _values_?
We would end up with the same issue I've pointed out earlier about the Button inner block, but I'd argue it's better than having the block break? 🤔

**Comment by Copons** [comment]
Actually I think I've found a nice solution! ✨

**Comment by Copons** [comment]
I've unassigned myself, but of course feel free to pick #16361 up! 🙂
