### ISSUE TITLE
Subscriptions: Gallery not displaying

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#1578]
Ported from 3290-wpcom

No matter what kind of gallery you try (thumbnail, tiled, slideshow), no images show in the email.

![screen shot 2015-02-02 at 2 38 38 pm](https://cloud.githubusercontent.com/assets/3676359/6007590/5d827c6a-aae9-11e4-8539-cfe2eab45a79.png)

If including the images is tricky, maybe we could include some placeholder text to indicate that there are images there, and that people should visit the post on the site?

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/gallery-images-not-appearing-in-subscription-emails-1?replies=1&view=all

**Comment by roccotripaldi** [comment]
also reported in kayako #2174325

**Comment by csonnek** [comment]
Also 2424410-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/content-of-post-in-subscriber-email-a-problem?replies=1&view=all

**Comment by tmmbecker** [comment]
Reported here: https://wordpress.org/support/topic/image-resolution-for-follow-on-wordpress-com-notification-mails/

though images are appearing in this case, just not properly sized or in a tiled format.

**Comment by richardmtl** [comment]
Leaving this open, because it's actually gotten even worse!

<img width="664" alt="screen shot 2018-11-15 at 9 38 30 am" src="https://user-images.githubusercontent.com/3676359/48559778-44c32180-e8ba-11e8-9889-f81b419e2f5b.png">

I just copy-pasted the exact same post content and published it again. This is the exact content of the post:

```
Thumbnail grid:

[gallery ids="130,129,128,127,131"]
Tiled Mosaic:

[gallery type="rectangular" ids="89,88,87,86"]
Circles:

[gallery type="circle" ids="91,90,64,65"]
Squares:

[gallery type="square" ids="84,74,73,72"]
Slideshow:

[gallery type="slideshow" ids="60,59,58,53,55"]
```

**Comment by richardmtl** [comment]
Not any better:

<img width="620" alt="Screen Shot 2019-11-11 at 11 29 43 AM" src="https://user-images.githubusercontent.com/3676359/68603598-9f17a380-0476-11ea-9e8f-b938fccc0eb8.png">

**Comment by tmmbecker** [comment]
3590772-zen

**Comment by danjjohnson** [comment]
Noting that for 3590772-zen the images do display, but not in a gallery layout. Apparently it was working fine until an update in late 2020. The user in this case uses Apple Mail.

**Comment by pranali333** [comment]
Can anyone check further on the issue?

**Comment by kwight** [comment]
This was fixed at some point, likely with the push on block rendering last year.

<img width="702" alt="Screen Shot 2021-08-11 at 10 56 30 AM" src="https://user-images.githubusercontent.com/349751/129079504-4e0d48d5-3cde-4ca9-9850-5325b742a4b0.png">
