### ISSUE TITLE
Search: binding to search box in hamilton theme not working

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#15785]
The header of the Hamilton theme has a search box that looks something like this:

```
<div id="header-search" style="display: none;">
<form role="search" method="get" action="https://www.moneytalksnews.com/">
<input type="search" class="form-control" placeholder="Search …" value="" name="s" title="Search for:">
</form>
</div>
```

I think our list of input selectors does not currently work: https://github.com/Automattic/jetpack/blob/f5bbb77d3a020f285a6a6b97f82ad627f4fd63ee/modules/search/instant-search/lib/dom.js#L9

#### Steps to reproduce the issue

1. Go to a site running Hamilton
2. Click in the search box in the header
3. The search works, but only after a page reload

Reported in https://github.com/Automattic/jpop-issues/issues/5230

**Comment by jsnmoon** [comment]
Strange, `'input[name="s"]:not(.jetpack-instant-search__box-input)'` should definitely select this.

**Comment by jsnmoon** [comment]
I can't reproduce this issue with the [Hamilton theme](https://wordpress.org/themes/hamilton/) from WP, which doesn't come with a search button in the header.

I also manually tested our event binding code on moneytalksnews.com and confirmed that the search input selectors should work as expected.

**Comment by bluefuton** [comment]
@gibrown can you repro this on the default Hamilton theme? As @jsnmoon says, it doesn't appear to have search box and the theme doesn't have a widget area.

**Comment by gibrown** [comment]
Huh, I guess that site must have a custom header of some sort going on. Closing.
