### ISSUE TITLE
Manage: Need Module Info Text

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#1580]
https://github.com/Automattic/jetpack/blob/master/modules/module-info.php needs Manage information so the card on the Jetpack wp-admin page is populated.

**Comment by squirk** [comment]
How were you able to pull a card?  I'm not seeing one in 3.3 at all and @samhotchkiss said there isn't one present in 3.4.

**Comment by squirk** [comment]
When if/we do have one, we can probably use something like:

New in Jetpack: Centralized Site Management
Manage multiple sites and keep plugins up-to-date from one dashboard at wordpress.com/plugins. Enabling allows all existing, connected Administrators to modify your site from WordPress.com.

**Comment by kraftbj** [comment]
¯\_(ツ)_/¯ Just went to the main Jetpack page within wp-admin running master and it's sitting right there: https://cloudup.com/c7VeyGyNFkz

**Comment by dereksmart** [comment]
That's interesting - I can't find any instances of that in our repo... Is it possible you have (git) ignored files in your Jetpack folder?

**Comment by kraftbj** [comment]
@dereksmart More or less, that's what it was. The git to production deploy I'm using was not deleting files deleted within git. Short of something else to prove to me it isn't just unique to me, closing as invalid.

**Comment by squirk** [comment]
Should this still be open though?  I don't think other people can see it.

**Comment by dereksmart** [comment]
Closed issues are still searchable

**Comment by dereksmart** [comment]
Oh, you meant a Manage card isn't viewable.  Technically manage isn't a module, so should it be added?

**Comment by kraftbj** [comment]
In my case, the module/manage.php file was still present on production, even though it had been deleted in the git repo. That is what was causing the card to appear, so not really a Jetpack problem.
