### ISSUE TITLE
Enable unique email subject line with Contact Form

### ISSUE THREAD

**Issue by WhatcomMktg** [Automattic/jetpack#15816]
**Problem:**
Contact Form users receive multiple responses from site visitors under the same email subject line. and it's common practice to configure email clients to nest emails with identical subject lines. But that makes handling each form submissions difficult since the separate email conversations are nested under the same subject line.

**Desired fix:** 
Enabling unique email subject lines for each form submission.

**Possible solutions include:**
* append a date/time stamp or other unique identifier to the subject line (quick solution)
* enabling use of a variable pulled from field contents in the subject line (e.g. "Job Application from %%name_field%%")
* the ability to select a field(s) to serve as the subject line or as a suffix to the subject line

**Comment by jeherve** [comment]
I would recommend using tokens in the email field, as explained here:
https://jetpack.com/support/jetpack-blocks/contact-form/contact-form-classic-editor/#customization
(see the "Customize the Notification Emails." section).
