### ISSUE TITLE
Protect: Need module info text

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#1581]
https://github.com/Automattic/jetpack/blob/master/modules/module-info.php needs Protect information so the card on the Jetpack wp-admin page is populated.

**Comment by jeherve** [comment]
On a related note, It'd be nice to add a module icon as well:

![screen shot 2015-02-02 at 6 30 34 pm](https://cloud.githubusercontent.com/assets/426388/6011427/9bc09a78-ab09-11e4-96f6-18e4bd3216ca.png)
