### ISSUE TITLE
(5P) External Media: Image grid a11y

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#15829]
For the image grid, the core Media Uploader uses an `<ul>` with each image as something like `<li role="checkbox" tabindex="0" aria-checked="false"><img ../><button>Checkbox</button</li>` and a click on the `<li>` displays a check button to indicate it is selected. As much as I love a <button> for a click interaction, it seems like the check button is unnecessary, as using role="checkbox" and aria-checked communicate that state better, IMO. I think we could have a pretty decent first pass with:
Change markup to `<ul>` for images wrapper and `<li role="checkbox" tabindex="0" aria-checked="false">` around each image
Add a click and keydown listener on space/enter for each `<li>`
When an `<li>` is selected:
display a checkmark in the top right corner (not a button like the core implementation)
set `aria-checked="true"` (if only one image is selectable, switch the previously selected to `aria-checked="false"`

**Comment by jeryj** [comment]
Fixed by https://github.com/Automattic/jetpack/pull/15850
