### ISSUE TITLE
Notice - "Jetpack_Options was called incorrectly" with JetPack > 8.5 and WC > 4.1 in mulltisite

### ISSUE THREAD

**Issue by vedanshujain** [Automattic/jetpack#15844]
In a multisite environment, when JetPack is not enabled on all sites (but enabled on some), this notice is displayed:

```
Jetpack_Options was called incorrectly. Not all plugins have loaded yet but we requested the class Jetpack_Options Please see Debugging in WordPress for more information. (This message was added in version 1.4.0.0.)

    wp-includes/functions.php:5167
    Automattic\J\A\autoloader()
    wp-includes/functions.php:5167
    spl_autoload_call()
    wp-content/plugins/jetpack/class.jetpack.php:2189
    Jetpack::get_option()
    wp-content/plugins/jetpack/class.jetpack.php:702
    Jetpack->__construct()
    wp-content/plugins/jetpack/class.jetpack.php:405
    Jetpack::init()
    wp-content/plugins/jetpack/load-jetpack.php:86
```

Initially, I thought this is a WooCommerce issue, but as far as I can see, we do not call `Jetpack_Options` before initialization. 

#### Steps to reproduce the issue

1. Start a new multisite (maybe using JN)
2. Install WooCommerce and network activate
3. You should be able to see the notice\

#### What I expected
No notice

Note that it goes away on JetPack 8.4.* or on WC 4.0. Maybe we are not using some feature correctly. Would appreciate the help here. Thanks!

**Comment by kbrown9** [comment]
That notice is caused by Jetpack, not WooCommerce. Beginning with v8.5, Jetpack uses `Jetpack_Options` before all plugins have been loaded, and v1.7 of the Jetpack Autoloader package ignores the `Jetpack_Options` PHP notice [here](https://github.com/Automattic/jetpack-autoloader/blob/master/src/autoload.php#L149)

It looks like WC 4.1.1 is using v1.6 of the Autoloader package, Can you upgrade that package to v1.7?

**Comment by kbrown9** [comment]
Also, just FYI, we're working on a major upgrade to the autoloader that will remove the restriction that packages can't be used until all of the plugins have been loaded. That PR is [here](https://github.com/Automattic/jetpack/pull/15106).

**Comment by ObliviousHarmony** [comment]
We will update the autoloader. Very excited for the 2.0 release!
