### ISSUE TITLE
Protect: IP address not valid when field is empty

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#1584]
When the box is empty a la http://d.pr/i/14iIG and you click the Save button, a message appears that says "One of your IP addresses was not valid." http://d.pr/i/1iQrw

**Comment by chaselivingston** [comment]
Maybe it should say "Please enter an IP address" or just nothing at all if left blank.

**Comment by dereksmart** [comment]
Related issues to this: 
- throws php warnings for bad IPs:  `Warning: inet_pton(): Unrecognized address in /home/dereksma/public_html/wp-content/plugins/jetpack/modules/protect/shared-functions.php on line 86`
- There's no easy way to clear the field

**Comment by roccotripaldi** [comment]
I fixed it. Now you can clear the field and have an empty whitelist.
Not sure how to suppress the warnings from inet_pton. That's just how the function behaves.
I'm closing this, and I may create a different issue for the warnings.

**Comment by samhotchkiss** [comment]
@roccotripaldi can you quiet it with `@`?

**Comment by roccotripaldi** [comment]
I suppose I could.
> @: This operator is affectionately known by veteran phpers as the stfu operator.
