### ISSUE TITLE
Video Hosting: Videos in AMP pages fail AMP test

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#15864]
Videos inserted via Jetpack's Video Hosting feature included with the Premium and Professional plans output invalid code for AMP causing the page to fail Google's AMP validation test.

Ex: https://search.google.com/test/amp?skip_amp_follow=true&id=cG1oGsjoC9geMwBNtLZmEQ

**Screenshots**
![](https://d.pr/i/7zPa4J+)
Image Link: https://d.pr/i/7zPa4J

**Comment by jeherve** [comment]
This example post doesn't appear to be built using the block editor. When using the block editor, the AMP markup appears to be valid:
https://search.google.com/test/amp?id=5qtxJDxbRCj6KbPrRCFbuw

Given that the markup is built by the AMP plugin and not by Jetpack itself, we most likely won't be able to make any changes to the markup in videos built in the old editor. I would recommend switching to the block editor instead.
