### ISSUE TITLE
Portfolio shortcode: Allow to load own styles instead of default styles

### ISSUE THREAD

**Issue by dashkevych** [Automattic/jetpack#15872]
Currently, the shortcode loads its own styles when the shortcode is used on the site: https://github.com/Automattic/jetpack/blob/master/modules/custom-post-types/portfolios.php#L633

I am aware of the method of avoiding to load default styles via the action and `wp_dequeue_style` and then including own styles in the theme.

I am wondering if there is a way to include own styles only when the shortcode is used without using `has_shortcode` and checking each post for this shortcode.

Would `wp_register_style` help in this case to make `portfolio_shortcode()` more flexible? (see: https://wordpress.stackexchange.com/a/191512/85513)

**Comment by jeherve** [comment]
> Would wp_register_style help in this case to make portfolio_shortcode() more flexible?

That could indeed be helpful. We already take a similar approach for other Jetpack resources:
https://github.com/Automattic/jetpack/blob/4729f971efab6464f301224e0abdffa7db9c8eda/class.jetpack.php#L1168-L1175

It may make sense to try the same approach with the stylesheets in Custom Post Types as well.

**Comment by scottsweb** [comment]
PR opened that supports overwriting styles of both the `[portfolio]` and `[testimonial]` shortcode

**Comment by dashkevych** [comment]
Hi @scottsweb,
Thank you for making changes to the `[portfolio]` and `[testimonial]` shortcodes.

This change allows to load own styles for these shortcodes without loading default styles.

Is it also possible to do similar as it shown here: https://github.com/Automattic/jetpack/issues/15872#issuecomment-631974573

So, we can allow plugins and themes to register own stylesheets for the `[portfolio]` and `[testimonial]` shortcodes and then load these stylesheets only when the shotcode is used.

We can use just `wp_enqueue_style( 'jetpack-testimonial-style' );` and `wp_enqueue_style( 'jetpack-portfolio-style' );` instead of this: https://github.com/Automattic/jetpack/pull/16134/files

In this case, we make these shortcodes more flexible, and also avoid loading stylesheets when these shortcodes are not present on the page.

What do you think about it?

**Comment by scottsweb** [comment]
Hi @dashkevych - I don't follow the use case or suggestion you are making, would you be able to provide a more detailed example?

The original issue asked for the ability to load custom styles for these shortcodes (replacing the default styles). The PR I submitted allows this by registering your own styles using the same identifiers (`jetpack-testimonial-style`, `jetpack-portfolio-style`). 

Are you asking for the check I implemented:

```
if ( ! wp_style_is( 'jetpack-portfolio-style', 'enqueued' ) )
```

to check for registered styles rather than enqueued perhaps?

**Comment by dashkevych** [comment]
@scottsweb,

Your current solution is much better than original one but there is still a small downside. Please see explanation below.

**Current state**

We can define our own styles using the following function:

```php
function slug_replace_default_shortcode_styles() {
  wp_enqueue_style( 'jetpack-testimonial-style', 'URL of the stylesheet', array(), '1.0.0' );
}
add_action( 'wp_enqueue_scripts', 'slug_replace_default_shortcode_styles' );
```

Once we have this function defined in the theme (or plugin), Jetpack is not going to load its own styles for the shortcode (in this case, it's testimonial shortcode): https://github.com/Automattic/jetpack/blob/4b85be883b3c584c64eeb2fb0f3fcc15dabe2d30/modules/custom-post-types/testimonial.php#L579-L581

The problem is that our stylesheet will be loaded globally on the site. We can use a conditional function, such as `has_shortcode()`, but it will affect a performance of the site because we will need to check every single post for a present of the testimonial shortcode.

**Proposed change**

Instead of enqueuing the stylesheet from the theme (plugin), we can register it with our own URL. And then let Jetpack to load the stylesheet **only** when the shortcode is used.

We can add additional function to the CPT class to register a style if it's not already registered in the theme (plugin). Example:

```php
function register_assets() {
    if ( ! wp_register_style( 'jetpack-testimonial-style', 'registered' ) ) {
        wp_register_style(
            'jetpack-testimonial-style',
            plugins_url( 'css/testimonial-shortcode.css', __FILE__ ),
            array(),
            '20140326'
        );
    }
}
```

Then, in the `jetpack_testimonial_shortcode()` (https://github.com/Automattic/jetpack/blob/4b85be883b3c584c64eeb2fb0f3fcc15dabe2d30/modules/custom-post-types/testimonial.php#L526) we just need to enqueue the style:

```php
wp_enqueue_style( 'jetpack-testimonial-style' );
```

In this case the stylesheet will be loaded only when the shortcode is used.

Themes and plugins can define (register) the path to their own styles for this shortcode. Jetpack will take care of loading the stylesheet.

I hope it makes more sense now. Please let me know if it still sounds confusing :)
