### ISSUE TITLE
Sharing Buttons: Sharing Buttons Don't Follow Style Settings on AMP Standard Mode.

### ISSUE THREAD

**Issue by druesome** [Automattic/jetpack#15882]
When AMP is set to Standard mode, the sharing buttons stop following button style settings in Settings > Sharing.

#### Steps to reproduce the issue

1. Install AMP Plugin and activate it.
2. Activate the Sharing module in Jetpack > Settings > Modules
2. Go to Settings > Sharing and add some sharing buttons to display and select a style.
2. Click on AMP and select Standard mode, then Save Changes.
3. View any published post.

#### What I expected

For the sharing buttons to follow the button style settings.

#### What happened instead

The sharing buttons appear in a different style that does not correlate with any available button style in Settings > Sharing.

**Screenshots**

Sharing buttons on Reader or Transitional AMP mode:

<img src="https://d.pr/i/C0oVnY+" width="600" />

Sharing buttons on Standard AMP mode:

<img src="https://d.pr/i/NMSN9E+" width="600" />

Reference: p9F6qB-5gN

**Comment by jeherve** [comment]
That's indeed the expected behaviour with sharing buttons and AMP. Note that we're working on some improvements in that area in #15497.
