### ISSUE TITLE
Podcast Player: Pasting Anchor.fm Episode-specific URL Renders All Recent Episodes Instead

### ISSUE THREAD

**Issue by zdenys** [Automattic/jetpack#15892]
#### Steps to reproduce the issue

1. Copy an episode-specific URL from Anchor.fm, such as `https://anchor.fm/Sree.Kumar/episodes/STRESS---its-a-matter-of-judgment-edqkkh/a-a2565o6` named `STRESS - it's a matter of judgment`
2. Paste into the Podcast Player

#### What I expected
See the specific episode

#### What happened instead
Most recent episode of the podcast load, but not the specific episode

**Screenshots**

Anchor.fm view:

![Markup 2020-05-22 at 14 23 20](https://user-images.githubusercontent.com/1398304/87592088-21a7d100-c69e-11ea-96b8-b5021b0cb599.png)
_Link: https://d.pr/i/DwgJAy_

Editor view:

![Markup 2020-05-22 at 14 22 00](https://user-images.githubusercontent.com/1398304/87592107-28364880-c69e-11ea-8631-d03c3dd0b938.png)
_Link: https://d.pr/i/aT942O_

#user-report 19415720-hc

**Comment by obenland** [comment]
I'm not sure I'd necessarily expect the same behavior as on Anchor.fm, but maybe limiting the player to just show that one episode?
A lot of it comes down to how Anchor.fm handles these types of links and what the RSS response for it looks like. Based on your report they just always return the full feed and not an episode-specific one.

**Comment by getdave** [comment]
> https://anchor.fm/Sree.Kumar/episodes/STRESS---its-a-matter-of-judgment-edqkkh/a-a2565o6

I followed that link in my browser and the source of the page has a link to the RSS feed which return ALL the episodes

https://anchor.fm/s/1f0ebab8/podcast/rss

Therefore it's' going to be tricky for us to get the single episode. This feels like a problem with Anchor rather than this specific block.

**Comment by marekhrabe** [comment]
This block doesn't support embedding a single specific episode. That would need to be developed separately (and has nothing to do with Anchor.fm, which correctly returns RSS with all episodes even on single episode page). I'll close this for now and if needed, we can reopen a feature request for the ability (or a new block) to embed a specific podcast episode, not just a feed.
