### ISSUE TITLE
Protect: whitelist save status needs styling

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#1590]
success : 
![screen shot 2015-02-03 at 11 22 47 am](https://cloud.githubusercontent.com/assets/2694219/6024184/53f38f46-ab97-11e4-9c86-3c279b517c85.png)

and error:

![screen shot 2015-02-03 at 11 23 01 am](https://cloud.githubusercontent.com/assets/2694219/6024190/5860479a-ab97-11e4-85cf-fcda0d911305.png)

**Comment by jeffgolenski** [comment]
Done: https://github.com/Automattic/jetpack/commit/152d9e2dd13a5dd4d95279d2bf9f05057c1e9439
