### ISSUE TITLE
Video block is unselectable once upload completes

### ISSUE THREAD

**Issue by ockham** [Automattic/jetpack#15922]
_Originally filed by @roo2 as https://github.com/WordPress/gutenberg/issues/22589_

---

**Describe the bug**
After uploading a video using the video block, the block becomes unselectable

![video](https://user-images.githubusercontent.com/22446385/82768026-7e8dc480-9e6f-11ea-879d-1fc68c67e8c5.gif)

#### Steps to reproduce the issue:
1. Go to the editor
2. Add a video block
3. Upload a sample video
4. The video becomes unselectable! (see gif)

**Editor version**
- On wordpress.com atomic site running 8.1.0
- Interestingly, I created a new atomic site and could not reproduce this, however I was able to see it on existing atomic sites.
 - I tested with firefox on macos

**More context**

This seems to have been introduced by the light block wrapper that was added to Gutenberg's Video block per https://github.com/WordPress/gutenberg/pull/22028.

**Comment by roo2** [comment]
I can confirm that existing users are experiencing this but we can't reproduce it on new atomic sites 🤔 both using GB 8.1.0. p1589943272033100-slack-create-gardeners . 
I wonder if it will be fixed once #15883 and #15906 are deployed 🤔

**Comment by jeherve** [comment]
> I wonder if it will be fixed once #15883 and #15906 are deployed 🤔

Good call. You should be able to test that theory by installing [the Jetpack Beta plugin](https://jetpack.com/download-jetpack-beta/) on an Atomic site and switching to Bleeding Edge under Jetpack > Beta.

**Comment by ockham** [comment]
Fixed by #15958
