### ISSUE TITLE
Shortlinks: Tooltip Text Incorrect

### ISSUE THREAD

**Issue by csonnek** [Automattic/jetpack#15937]
In the settings for WP.me Shortlinks - under Jetpack -> Settings -> Traffic tab - the tool tip text indicates: 

> Generates shorter links so you can have more space to write on social media sites. Learn more

Most social networks don't penalize you for the character counts of URLs anymore. In fact we removed the wp.me shortlink in Publicize [back in 2015](https://github.com/Automattic/jetpack/commit/ca4ff30458a2543a41867a32f2c6dedc2476b0ea). 

We should update that text in both the tooltip and support documentation to remove the mention of "have more space to write on social media sites". Suggestion:

> Generates shorter links using the wp.me domain

**Comment by kraftbj** [comment]
I agree that the current copy reads dated. Maybe there are still social media networks that the character count include raw URLs, but I don't think the mainstream ones where one would share a link.
