### ISSUE TITLE
Connection Package: Blank page when retrying authorization

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/jetpack#15932]
If the `authorization` doesn't succeed the first time in Calypso, and the user clicks `Try again`, they'll be redirected to a blank page.

#### Steps to reproduce the issue
- Make sure Jetpack-the-plugin is **not** installed in your site.
- Go to the `Client Example` plugin, start the Calypso flow for authorization.
- Before clicking "Approve" in Calypso, add something to your local site that would make the request fail. I just killed my `ngrok` tunnel.
- Click `Approve`, you'll get an error notice with a "Try again" link.
- Take your local site back online.
- Click `Try Again`. You'll be redirected to a blank page.

The problem is that the page you're redirected is `https://YOUR_SITE/wp-admin/admin.php?action=authorize&_wpnonce=8ab6029e62&redirect=<REDIRECT_URL>`, and the logic to process that is in Jetpack-the-plugin: https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/class.jetpack.php#L4186-L4195

#### What I expected
I expected the retry flow to work the same way as in Jetpack.

#### What happened instead
Blank page.

**Comment by sergeymitr** [comment]
@DanReyLop

I've investigated the issue and it appears that `jetpack-connection` package is missing the handler for the redirect-based authorization, and only supports the REST API authorization request.
In your example Calypso receives the "unsuccessful authorization" response, and falls back to the redirect-based approach, which isn't supported by `jetpack-connection`.

Jetpack supports both REST API authorization and the redirect-based one. As you mentioned, Calypso behaves a little bit differently when it detects Jetpack, but the general idea is the same.

That's a really good find, and we should fix it as a part of the "non-Jetpack connections" effort.
I'll get back to it tomorrow and see what's the best way we can solve this.

Thank you reporting it.

**Comment by DanReyLop** [comment]
> As you mentioned, Calypso behaves a little bit differently when it detects Jetpack, but the general idea is the same.

This part still baffles me. I don't know how Calypso is even detecting that the site has a real Jetpack plugin if, at the moment of authorization, the entire site is unreachable. But I can live without knowing the specifics :)

> That's a really good find, and we should fix it as a part of the "non-Jetpack connections" effort.
I'll get back to it tomorrow and see what's the best way we can solve this.

Thanks for taking a look! It doesn't look like a blocker to get this flow working, but it would definitely be a nice improvement even after launch.

**Comment by DanReyLop** [comment]
I think the `Attempt 2` in this comment is a different variant of this issue. Looks like he was on the Authorize flow for a while, so the token expired, and he was redirected back to his site to a page that doesn't exist without Jetpack-the-plugin: `https://..../wp-admin/admin.php?page=jetpack&connect_url_redirect=true&...`

**Comment by sergeymitr** [comment]
Thanks @DanReyLop.
I'll look into that tomorrow.
