### ISSUE TITLE
Form Block: Unable To Remove Contact Form Entries

### ISSUE THREAD

**Issue by allykmyta** [Automattic/jetpack#15939]
I've attempted to replicate this but this is very specific to this users site. Steps listed below can only be done within the user site to replicate. 

#### Steps to reproduce the issue

1. Go to Pages > select Contact Page > remove any extra entries in Form Block
2. Select Update (this should appear correctly in live mode)
3. View page and select "Edit" on the page. 
4. Return back to page editor and see all contact form entries added back (but not appearing on the front end of the site)

#### What I expected
The Form Block entries should remain removed and not be added back automatically.

#### What happened instead
Random entries were added back but not appearing on the front end of the site.

**Screenshots**
Video of this behavior is available in #3005443-zen

**Comment by jeherve** [comment]
Do you experience the same issue if you remove the block altogether, add a fresh new block back, and then attempt to modify it?

**Comment by allykmyta** [comment]
Yes. I tried creating a new page and adding just the contact form block and it had the same effect. 
I then created a new Contact page and added a Contact page layout which was edited and worked for us (no duplication appearing below).

**Comment by jeherve** [comment]
Ah, interesting. It may be worth trying without using the page layout option. I believe this may be linked to the blocks preset in the block layout.

**Comment by allykmyta** [comment]
I just attempted that and it seemed to work. I also attempted to replicate this issue again on the customer's site and it seems to work as expected now 🤔, may have resolved itself? I appreciate you looking into this @jeherve

**Comment by jeherve** [comment]
> may have resolved itself?

This may indeed have been fixed in the last Gutenberg update. Closing this for now, since the problem seems fixed! 🤞
