### ISSUE TITLE
Wizard: blank setup page following connection

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#15936]
#### Steps to reproduce the issue

0. In Chrome (we want the connect-in-place flow)
1. Start with a brand new Jurassic Ninja site
2. Under Jetpack > Beta, pick 8.6-beta in the "Search for a Jetpack tag" section
3. In a functionality plugin, add the following: 
```php
add_filter( 'jetpack_pre_connection_prompt_helpers', '__return_true' );
add_filter( 'jetpack_show_setup_wizard', '__return_true' );
```
4. Go to the Jetpack menu
5. Click tho connect the site to WordPress.com.
6. After the connection, you'll be redirected to the plans prompt page, `wp-admin/admin.php?page=jetpack#/plans-prompt`
7. Pick the free option at the bottom of the page (leading you to `wp-admin/admin.php?page=jetpack`
8. You'll be redirected to `wp-admin/admin.php?page=jetpack#/setup`
9. You'll see the page URL briefly flash to the intro route
10. You'll be redirected back to `wp-admin/admin.php?page=jetpack#/setup`
11. The page will be blank
```
react-dom.min.js?ver=16.9.0:103 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
```
https://reactjs.org/docs/error-decoder.html/?invariant=185

> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

@robertf4 Do you think you can take a look?

Thanks!

**Comment by kbrown9** [comment]
I think the problem might be that, after leaving the plans prompt, the route doesn't include `/setup`. So the redirect route that's created in `SetupWizard` [here](https://github.com/Automattic/jetpack/blob/master/_inc/client/setup-wizard/index.jsx#L56) is just `//intro`.

In the main component, the [default case](https://github.com/Automattic/jetpack/blob/master/_inc/client/main.jsx#L249) for the route switch statement is used for the `//input` route, which creates an infinite loop with `SetupWizard`, adding `/input` to the route each time.

**Comment by robertf4** [comment]
That was exactly the problem @kbrown9, thank you for the info!
