### ISSUE TITLE
Improve auto posting to Twitter

### ISSUE THREAD

**Issue by gonzague** [Automattic/jetpack#1593]
By also posting the first picture of post to illustrate the Tweet :)

**Comment by jeherve** [comment]
Jetpack already adds Twitter Cards Meta tags to your posts, unless you already use another Twitter Cards plugin to do that.

Once your posts include the necessary tags, you can apply to get Twitter Cards displayed below each one of your tweets [here](https://cards-dev.twitter.com/validator).

Here is an example of a tweet including a "Summary Large Image" card:
https://twitter.com/jetpack/status/529288733774712833

And here is an example of tweet including a "Photo" card:
https://twitter.com/Flickr/status/423511451970445312

Each twitter client decides how to display these cards, but in most cases they're only displayed when looking at a single tweet, to avoid cluttering your twitter timeline by adding images under each tweet.

If you'd like to display images below your tweets in the twitter timeline as well, you'll need to upload an image to Twitter alongside your tweet. Jetpack won't allow you to do that, but you can use twitter clients like Hootsuite to upload an image and tweet a link.

**Comment by rickalee** [comment]
@jeherve Getting conflicting answers to this question. See your WordPress.org forum response.

https://wordpress.org/support/topic/publicize-share-feature-image-instead-of-twitter-card/

I would like for Publicize to Tweet to attach first image in post. Is there a hook or filter for this?

**Comment by jeherve** [comment]
@rickalee This GitHub issue is quite old, and predates some changes we made to Publicize. Publicize now automatically takes your posts' Featured Image and attaches it to the tweets published by [Publicize](http://jetpack.com/support/publicize/).

Here is an example:
https://twitter.com/jeherve/status/839186603499220992

If that doesn't work for you, I'd recommend that you make sure that set Featured Images that are large enough (280x180px minimum) and not too bug (Twitter refuses images larger than 5242880 bytes).

I hope this helps. If you still have questions, don't hesitate to send us more info about your site and some examples via [this contact form](http://jetpack.com/contact-support/).
