### ISSUE TITLE
Jetpack Setup Wizard: rename Jetpack Scan in recommendations

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#15948]
> Security Scanning – should we call it something different? I had a hard time connection Security Scanning and Jetpack Scan are the same thing right away. On the plans table we call it Daily Melware Scanning and we call the product Jetpack Scan.
-- p8oabR-vj-p2#comment-4245

cc @robertf4

**Comment by robertf4** [comment]
Currently making as won't fix but might revisit tomorrow.
