### ISSUE TITLE
Jetpack setup wizard: layout conflicts between configure buttons and "included" messages

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#15972]
#### Steps to reproduce the issue

1. On a brand new site, before to connect to WordPress.com, add the following:
```php
add_filter( 'jetpack_show_setup_wizard', '__return_true' );
add_filter( 'jetpack_pre_connection_prompt_helpers', '__return_true' );
```
2. Connect your site to WordPress.com and pick a Professional plan
3. Head back to wp-admin
4. Click on setup.
5. Pick Business and the Advertizing option in the flow
6. On the recommended features, next to the Ads card, the configure button and "included" messages will conflict:

![image](https://user-images.githubusercontent.com/426388/83150236-52867380-a0fb-11ea-99ed-cb4b78c5aa74.png)

-- p8oabR-vj-p2#comment-4300

cc @robertf4 @jeffgolenski

**Comment by jeffgolenski** [comment]
Just posting the proposed designs for all the use-cases again for easy access:

![Screen Shot 2020-05-28 at 10 02 29 AM](https://user-images.githubusercontent.com/214813/83151320-6b2a6580-a0ca-11ea-9b15-79f0c29d120c.png)
