### ISSUE TITLE
Form block: form type tooltips are misaligned

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#15978]
#### Steps to reproduce the issue

1. Add a form block
2. Hover over one of the form types
3. See the tooltip

#### What I expected

Tooltip is placed above the button frame

#### What happened instead
The tooltip is placed above the icon.

Comparing to tooltip behavior in core components, I'd say it should be placed above the button

![Edit Post ‹ jetpack6test mystagingwebsite com at Pressable — WordPress 2020-05-28 21-37-23](https://user-images.githubusercontent.com/5654161/83180396-0d2e6a00-a12c-11ea-9b31-28a101136172.png)

**Comment by jeherve** [comment]
cc @apeatling

**Comment by apeatling** [comment]
This is because the icons are bigger in this variation picker to give more space for text labels underneath in newer versions of Gutenberg. 

Is there something specific this affects? Otherwise I don't think it's a big enough issue to address.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
