### ISSUE TITLE
Form block: Add AMP support

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#15981]
We should update styles for form block in AMP views. right now it looks really ugly

#### Steps to reproduce the issue

1. Publish a post with default form block
2. View the post in amp view
3. See how it's presented

![image](https://user-images.githubusercontent.com/5654161/83182336-e160b380-a12e-11ea-8290-1456b47d4876.png)

**Comment by pereirinha** [comment]
Hi @brbrr 

I'm keen to open a PR to fix this, but I wasn't to replicate the issue you described. The form seems to be very close both on non-AMP and AMP experience, regardless of its settings.

Please check the following side by side print screen.
<img width="1635" alt="Screenshot 2020-06-23 at 16 53 22" src="https://user-images.githubusercontent.com/2189187/85426318-377c1780-b572-11ea-98b2-35960bdc00f3.png">

Do you think it can be related to the theme you used? I'm currently using the core `twenty twenty` theme.

**Comment by brbrr** [comment]
Ouch, sorry, forgot to mention AMP setting I used. I can see this problem in "Reader" mode:

https://jetpack6test.mystagingwebsite.com/2020/06/23/form-block-test/?amp=1

**Comment by westonruter** [comment]
@brbrr Here's a PR to fix that: #17252
