### ISSUE TITLE
We still reference "rewinding" or "rewound" in mobile notifications

### ISSUE THREAD

**Issue by jessefriedman** [Automattic/jetpack#16028]
As you can see in the screenshot we reference "rewound" your site but we don't use "rewind" anymore to describe the restore process. It'd be great to audit the mobile notifications and change these to "restored" or "restore". cc/ @robertbpugh 

<img width="396" alt="Screen Shot 2020-06-01 at 1 59 19 PM" src="https://user-images.githubusercontent.com/1749986/83439024-558da680-a410-11ea-9fd7-622746e4bba2.png">

**Comment by jessefriedman** [comment]
Also, if all I did was restore my site so I could bring back a lost post or image, then my site was never down so the content "Your site should now be up and running" is actually making it sound like the restoring process took down the site for a bit.

**Comment by jeherve** [comment]
This is not something we'll be able to fix in Jetpack I'm afraid. @singerb Do you happen to know where those notifications live?

**Comment by singerb** [comment]
These live in wpcom; `notify-site-activity.php` is the entry point that triggers e-mails and notifications based on activity log events arriving.

**Comment by jeherve** [comment]
D44292-code should fix this.
