### ISSUE TITLE
Instant Search: Search results displaying possibly deleted posts

### ISSUE THREAD

**Issue by skjaini** [Automattic/jetpack#16029]
#### Steps to reproduce the issue

1. Visit https://dentedreality.com.au
2. Search for some term like `Williamsburm`
3. Click on each of the top 5 search results

#### What I expected
Expected to see a post or a page upon clicking on search results.

#### What happened instead
Some of the results end up with "Oops! That page can’t be found." which might possibly be due to deleted posts.

#### Screenshots
Captured here: https://d.pr/i/vqpUor

**Comment by gibrown** [comment]
@beaulebens I wonder if you could kick off a full sync of your site and see if that fixes this? Or if you have any insight?

**Comment by beaulebens** [comment]
Depending on which results are being clicked on, my site does some pretty weird things with hiding certain post types in certain conditions, so you might just be running into that. In particular if you try to view what appears to be a tweet reply (starts with `@`) then it won't display properly.

**Comment by gibrown** [comment]
Closing this... it seems specific to this site and ya seems to be about the `@` symbol in the url
