### ISSUE TITLE
Failed to load plugin url: https://erangpurcity.com/wp-content/plugins/jetpack/_inc/build/contact-form/js/tinymce-plugin-form-button.min.js problem

### ISSUE THREAD

**Issue by rakibrg1971** [Automattic/jetpack#16021]
**Failed to load plugin url: https://erangpurcity.com/wp-content/plugins/jetpack/_inc/build/contact-form/js/tinymce-plugin-form-button.min.js Pronlem**

when create a new post its problem http://prntscr.com/sr71ah

### Begin System Info (Generated 2020-05-31 17:08:53) ###
------------ SITE INFO
Site URL:                 https://erangpurcity.com
Home URL:                 https://erangpurcity.com
Multisite:                No

------------ USER BROWSER
Platform:                 Windows 
Browser Name:             Chrome  
Browser Version:          83.0.4103.61 

------------ WORDPRESS CONFIG
WP Version:               5.4.1
Language:                 en_US
Permalink Structure:      /%category%/%postname%/
Active Theme:             Hueman 3.5.8
Show On Front:            posts
ABSPATH:                  /home1/codexprof/erangpurcity.com/
WP_DEBUG:                 Disabled
WP Memory Limit:          40MB

------------ NIMBLE CONFIGURATION
Version:                  2.0.20
Upgraded From:            2.0.18
Started With:             2.0.13

------------ WP ACTIVE PLUGINS
Accelerated Mobile Pages: 1.0.52
AddToAny Share Buttons: 1.7.40
Akismet Anti-Spam: 4.1.5
Cloudflare: 3.4.1
Cookie Notice: 1.3.2
Date and Time Widget: 1.1.0
Insert Headers and Footers: 1.4.5
Jetpack by WordPress.com: 8.5
MOJO Marketplace: 1.5.3
Nimble Page Builder: 2.0.20
Post Views Counter: 1.3.2
PWA for WP: 1.7.14.1
ShortPixel Image Optimizer: 4.18.1
WPForms Lite: 1.6.0.2
WP Responsive Recent Post Slider/Carousel: 2.3.1
Yoast SEO: 14.2

------------ WP INACTIVE PLUGINS
DMCA Website Protection Badge: 2.0.3
Newsletter: 6.6.9
Smush: 3.6.3

------------ WEBSERVER CONFIG
PHP Version:              7.1.14
MySQL Version:            5.6.41
Webserver Info:           Apache
Writing Permissions:      OK

------------ PHP CONFIG
Memory Limit:             256M
Upload Max Size:          256M
Post Max Size:            260M
Upload Max Filesize:      256M
Time Limit:               30
Max Input Vars:           1000
Display Errors:           On (1)
PHP Arg Separator:        &
PHP Allow URL File Open:  1

**Comment by jeherve** [comment]
Thanks for the report. This is known issue, currently tracked in #10919.

Could you try the steps in that issue to try to find out more about the issue, and let us know what you find?

Thank you!

**Comment by rakibrg1971** [comment]
i did not get my question answear ?

**Comment by jeherve** [comment]
@rakibrg1971 Could you try the steps in #10919 to try to find out more about the issue, and let us know what you find?
