### ISSUE TITLE
[data-carousel-extra] cursor: pointer on all blocks

### ISSUE THREAD

**Issue by bradley2083** [Automattic/jetpack#16031]
#### Steps to reproduce the issue

1. Add a none-image block and save your page
2. Hover over the new block
3. Notice the cursor: pointer (should be "auto" - or "none" when hovering none-image elements, but for some reason it's set to:

[data-carousel-extra] { cursor: pointer; } 

and therefore the cursor changes on ALL blocks.

**Screenshots**

<img width="1209" alt="Screen Shot 2020-06-01 at 3 13 42 PM" src="https://user-images.githubusercontent.com/1781226/83460154-95f22200-a41a-11ea-9898-1abbafb2c215.png">

**Comment by jeherve** [comment]
Thanks for the report. This is currently tracked in #13428.
