### ISSUE TITLE
Photon: Photon links for images inserted in editor when Site Accelerator is active

### ISSUE THREAD

**Issue by KokkieH** [Automattic/jetpack#16035]
#### Steps to reproduce the issue

1. With Site Accelerator disabled, create a new post and upload an image via the image block
2. Switch to the HTML editor - note the `src` attribute of the image indicates the WordPress media file URL.
3. With Site Accelerator enabled, create a new post and upload an image via the image block
4. Switch to the HTML editor and note the `src` attribute

#### What I expected

For the image added while Site Accelerator was active to also show the WordPress media URL.

#### What happened instead
The image shows the Photon URL in the editor (as opposed to being generated dynamically on the front end when the site loads.

After disabling Site Accelerator/disconnecting Jetpack completely, the `src` attribute for the image when viewing the post in a browser still shows the Photon URL, rather than the media file URL.

**Screenshots**
HTML view of images added with Site Accelerator enabled and disabled respectively:
![Editor](https://user-images.githubusercontent.com/11873759/83502725-5121c600-a4c2-11ea-80ae-b4fe6980b5e0.png)

Browser inspector showing HTML for image with Jetpack completely disabled on the site:
![Front end](https://user-images.githubusercontent.com/11873759/83502787-6b5ba400-a4c2-11ea-8290-f579f41c524c.png)

Reported in https://wordpress.org/support/topic/photon-inserting-https-i0-wp-com-images-in-post-content/

**Comment by jeherve** [comment]
See https://github.com/Automattic/jetpack/issues/10580#issuecomment-637663083 for a potential way around this.

**Comment by hubertnguyen** [comment]
I noticed this with the new image comparison plugin as well, just a FYI. It probably goes through the same code path .

**Comment by jeherve** [comment]
cc @kraftbj  Do you think you could take a look at this this week, if you have the bandwidth?

Thank you!

**Comment by kraftbj** [comment]
I can't duplicate this behavior on either with trunk Jetpack with WP 5.4.2 or 5.4.2+Gutenberg 8.3.0. Asking for others to try to reproduce.

**Comment by kraftbj** [comment]
Still working on exactly the repo steps. Images of a certain size will trigger it, but not others.

**Comment by hubertnguyen** [comment]
@kraftbj , I sawe your message on Wordpress org. Looks like you're onto it. Let me know you need me to try something. I often use 1000-1500px wide images.
Perhaps the issue happens with "large" but not "full" images?
