### ISSUE TITLE
Custom CSS: Use Standard URL

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#1605]
WP Engine, perhaps others, have a "Redirect Bots" options that redirect pages with query arguments to the main page when the UA matches a known bot.

This impacts users with Custom CSS whose custom code modifies their design to make it mobile-friendly and they're looking for Google's mobile-friendly "badge".

Since our Custom CSS is loaded via /?custom-css=1...., when the `Googlebot` or `Smartphone Googlebot`, etc scrapes the site, on WPE, the /?custom-css=1 is 301'd to /, which fails to load the CSS.

Idea: Use an URL without query args for custom CSS—either by default or via a filter that could, for example, be added to WP Engine's mu-plugin.

**Comment by kraftbj** [comment]
My inclination would be to wontfix this as an edge case, unless there are more/other issues related to our method for custom CSS. Posted it to get wider comment before dismissing it out of hand.

**Comment by jeherve** [comment]
> WP Engine, perhaps others, have a "Redirect Bots" options that redirect pages with query arguments to the main page when the UA matches a known bot.

Does that break Related Posts as well?

**Comment by kraftbj** [comment]
> Does that break Related Posts as well?

It does break it _when loaded with a Googlebot UA_. I'm not sure how often/if ever the RPs failing for a bot would cause problems for users.

**Comment by georgestephanis** [comment]
Honestly, I'm not sure what a more reliable url to pull from would be.  We can't assume pretty permalinks, and there are a number of sites that password protect their `wp-admin` directory, so admin-ajax for normal site visitors probably isn't the best choice.

Honestly, I'm thinking this is a wontfix, and WPE's overoptimization is at fault for breaking things and should be examined on that end.

**Comment by kraftbj** [comment]
Before diving into the code, _if_ we do anything, I'd suggest a filter that would enable a better option. Though, as I type that, unless this become a bigger issue, that may be overkill. Marking as wontfix and closing, though always open for further discussion if this kind of optimization becomes more widespread.
