### ISSUE TITLE
External Media: "Select Image" button text is incorrect

### ISSUE THREAD

**Issue by pento** [Automattic/jetpack#16064]
#### Steps to reproduce the issue

1. Create a new post in the block editor.
2. Add a Cover block (or any block that allows more than media type to be inserted).
3. Observe the "Select Image" button disagreeing with the instruction to "Upload an image or video file...".

#### What I expected

That the button text show that the button can be used for more than just images. (For reference, the button it replaces uses the text "Media Library", since it directly opens the media library.)

#### What happened instead

<img width="663" alt="" src="https://user-images.githubusercontent.com/352291/83726062-53cd1880-a686-11ea-8c9c-567deee7d9d9.png">

**Comment by obenland** [comment]
Fixed in #16071.
