### ISSUE TITLE
External Media: Unable to add images to an existing Gallery block

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#16070]
#### Steps to reproduce the issue

1. Create a Gallery block with a few images.
2. In the Upload bar at the bottom of the block, click on "Select image"
3. Find the upload modal appearing over the library dropdown.

#### What I expected

For the library dropdown to be usable as usual.

#### Screenshots
![Screen Recording 2020-05-26 at 12 04 PM](https://user-images.githubusercontent.com/426388/82894512-f8e34500-9f52-11ea-84f7-9d775d10b937.gif)

See https://github.com/Automattic/jetpack/pull/15717#pullrequestreview-418201700

**Comment by marekhrabe** [comment]
I'm worried in general that we might be breaking many other blocks (non-core) in a similar way, as we are using the API in a way it wasn't designed for and no other blocks expect

**Comment by jancavan** [comment]
I experienced this yesterday, and was just about to ask 👍

**Comment by obenland** [comment]
Fixed in #16124.
