### ISSUE TITLE
Support Organization Logo Schema for Site Logo

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#1608]
Not sure if it should be default or not, but would like the ability to use the Jetpack Site Logo feature with schema support Organization Logo, example:

    <div itemscope itemtype="http://schema.org/Organization">
    <a itemprop="url" href="http://www.mysite.com">
    <img itemprop="logo" src="http://www.mysite.com/logo.jpg" alt="My Site Name" />
    </a>
    </div>

**Comment by bhubbard** [comment]
Digging into code a bit, we just need to let users define the `itemprop` for the url and Image tags.

**Comment by jeherve** [comment]
Fixed in #1609
