### ISSUE TITLE
Stats: JS file returning 400 error and showing up in GTMetrix report

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#16084]
The user in 3019081-zen reported that the following file is showing up in the `Avoid bad requests` section of their GTMetrix report. I was able to reproduce this on several other Jetpack-connected sites.

`/wp-content/plugins/jetpack/https:/stats.wp.com/s-202023.js`

![](https://d.pr/i/9H013e+)
Image Link: https://d.pr/i/9H013e

Is it possible to resolve this or otherwise provide some sort of workaround, or is this just something that they'll need to live with?

**Comment by jeherve** [comment]
Closing as duplicate of #16047. Check the PR description for a work-around.
