### ISSUE TITLE
Form Block: Nesting a Spacer Block Does Not Add Space on Site

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/jetpack#16082]
#### Steps to reproduce the issue

1. Create a new page
2. Add a Form block
3. Insert a Spacer block in between two form fields

#### What I expected
The Spacer block would be respected and space would be added in between the two fields

#### What happened instead
No space is displayed on the live site

**Screenshots**
From within the editor:
![Screen Shot 2020-06-06 at 08 29 37](https://user-images.githubusercontent.com/42454301/83944256-01980e80-a7d0-11ea-8152-d6cafc845de6.png)
And on the live site:
![Screen Shot 2020-06-06 at 08 30 04](https://user-images.githubusercontent.com/42454301/83944257-05c42c00-a7d0-11ea-86bc-92d2e325354f.png)

User reported: 3038813-zen

**Comment by dcoleonline** [comment]
Also encountered in 26118774-hc

The workaround there was to use CSS to set the spacer div to 100% width. This allowed it to apply the height to the spacer as set in the editor.

**Comment by katiebethbrown** [comment]
Another report in 26656109-hc

I shared this CSS (page specification removed) to correct it:

```
/* Fix Spacer Block Placement In Form */ 
div.wp-block-spacer {
  width: 100%;
}
```

**Comment by dcoleonline** [comment]
#28019978-hc
Provided CSS fix

**Comment by annbingle** [comment]
Another Report here.
30198303-hc

As a workaround, the user added a separator block on top of the spacer block then only the spacer took effect on the live site.
