### ISSUE TITLE
Form Block: Make it easier to get to block-level settings

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/jetpack#16092]
Once you've created a form block and moved away from the form settings, getting back to the main block-level settings is hard. 

@anaemnesis figured out that the only real way to do this is to click in the top-most field and then use the up arrow to select the main block. 

#### Describe the solution you'd like

Include the form-level settings in a more intuitive place. Or include a link from within each sub-block settings page. 

From 3044690-zen

**Comment by jeherve** [comment]
That's something that would need to be addressed in core itself I think. I don’t think it’s very easy to grasp the UI concepts around inner blocks right away. Only when you get familiar with the block navigation button in the top toolbar can you really start to browse and select blocks a bit faster.

The good news, there is some work being done on this in Gutenberg right now, so it should become easier over time:
https://github.com/WordPress/gutenberg/issues/22705
https://github.com/WordPress/gutenberg/issues/22089
