### ISSUE TITLE
Comment form in Opera Mini doesn't show the email and name fields nor the Submit button

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#161]
If you try to view the Jetpack comments form on Chrome or Safari for iPhone, you do see the Name and Email fields and the Submit button. However, if you try the same site with Opera Mini, you only get the comment field and thus can't submit your comment.

I tested on iOS 6.1.3 on an iPhone 4S and Opera Mini 7.0.5.45389

Ported from https://plugins.trac.wordpress.org/ticket/1820

**Comment by chaselivingston** [comment]
Also reported in 2147615-t

**Comment by samhotchkiss** [comment]
16 months between reports?
