### ISSUE TITLE
Slideshow: First and last images do not display properly with Lazy Loading

### ISSUE THREAD

**Issue by kbrown9** [Automattic/jetpack#16127]
#### Steps to reproduce the issue

1. The site must have Jetpack active and the Lazy Loading module enabled.
2. Add content to a post, including a slideshow block with multiple images.
3. View the post while logged out or in an incognito window.
4. Click the slideshow arrow buttons to display the slide show images. When the slideshow images loop, the images are not displayed:
   * When the last image is displayed, click the forward arrow button and notice that the first image is not displayed.
   * When the first image is displayed, click the back arrow button and notice that the last image is not displayed.

#### What I expected
All images in the slideshow should display.

#### What happened instead
The first and last images in the slideshow did not display properly.

**Comment by joweber123** [comment]
Another report of this here: 24670248-hc
