### ISSUE TITLE
Search: Initial sorting when opening the overlay using the wrong sorting

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#16123]
When the search overlay first opens the sorting is by date rather than by relevance despite what the UI claims.

1. Go to https://wordpress.com/support/tutorials/business-website-tutorial/
2. Click in the search box
3. Note that the sorting is by date even though "Relevance" is highlighted. If you click on "Relevance" then the sorting will be correct.

This prevents us from having the default sorting based on popular content when the overlay first opens.

**Comment by jsnmoon** [comment]
This might have been fixed by #16017, but I'm not sure how to verify the fix.

cc @gibrown

**Comment by bluefuton** [comment]
With default sort set to 'relevance', I am now seeing the initial results sorted by relevance when opening the overlay 👍
