### ISSUE TITLE
Block Editor Welcome Modal Has Incorrect Dimensions 

### ISSUE THREAD

**Issue by gwwar** [Automattic/jetpack#16143]
In Jetpack Master, it looks like the welcome modal isn't rendering as expected:

| Jetpack 8.6.1 | Jetpack Master | 
| ------------- | ------------- |
| <img width="1253" alt="Jetpack 8 6 1" src="https://user-images.githubusercontent.com/1270189/84424312-c1bc9700-abd4-11ea-83ce-9e1dda6b54b8.png"> | <img width="1253" alt="master" src="https://user-images.githubusercontent.com/1270189/84424374-db5dde80-abd4-11ea-86a2-cbf625040238.png"> |

| Jetpack 8.6.1 + Gutenberg Plugin | Jetpack Master + Gutenberg Plugin |
| ------------- | ------------- |
| <img width="1649" alt="stable+gutenberg" src="https://user-images.githubusercontent.com/1270189/84424461-fcbeca80-abd4-11ea-8392-e8beed12a3e8.png"> | <img width="1514" alt="master+gutenberg" src="https://user-images.githubusercontent.com/1270189/84424545-1bbd5c80-abd5-11ea-987c-23abbbb4ad87.png"> |

### To Reproduce

- Install Jetpack Master or use the Bleeding Edge option in Jetpack Beta
<img width="822" alt="Screen Shot 2020-06-11 at 11 01 51 AM" src="https://user-images.githubusercontent.com/1270189/84424619-38599480-abd5-11ea-9139-9c6dd0c597f4.png">
- Enter the post editor at /wp-admin/post-new.php
- Click on Welcome Guide
<img width="306" alt="Screen Shot 2020-06-11 at 11 02 35 AM" src="https://user-images.githubusercontent.com/1270189/84424714-58895380-abd5-11ea-9b21-010ffe4dd5e4.png">

Expected: Welcome modal appears with no scrollbars
Actual: Scrollbars are visible for both WP latest and Gutenberg plugin

**Comment by gwwar** [comment]
@retrofox @Automattic/ajax do you mind following up on this, looks like this broke from https://github.com/Automattic/jetpack/pull/15717/files#diff-79802d81ad46429980258e1ae67b1befR74-R79

We need a more specific selector, since this will be applied to any modals in the editor view.

**Comment by simison** [comment]
@retrofox FYI I noted 3 other CSS lines that needs fixing from that PR since they're leaking to core components.

**Comment by retrofox** [comment]
Thanks @gwwar and @simison for reporting the issue and help us how to fix it. It
s already tackled in https://github.com/Automattic/jetpack/pull/16144.
Just FYI, not sure if I introduced these changes but the whole team. It was the feature branch of the external media feature. 🙇‍♂️

**Comment by simison** [comment]
@retrofox no worries! Happens. Thanks for jumping so quick to fix it.
