### ISSUE TITLE
Monitor: Enhancement request - add an option to turn Monitor OFF from the montior emails

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1614]
We get quite a bit of support tickets that ask us to turn Monitor off for people who either
A) Are moving servers and know their site is down for a bit
or 
B) Shut down their sites but forgot to turn Monitor off before deleting their sites

It would be great if we added something like
`Click here to disable these emails: for the next 24 hours / forever.`

**Comment by georgestephanis** [comment]
I like it.

**Comment by kraftbj** [comment]
Link to https://wordpress.com/settings/general/[JP-DOMAIN] which links to the manage settings or directly to https://wordpress.com/manage/[JP-BLOG-ID] to simply deactivate monitor completely.

I assume the latter will eventually be rolled into the former?

**Comment by mikeyarce** [comment]
Got this in an email today: 
> the jetpack kept sending me emails like 70 emails a day regarding my site being down

**Comment by samhotchkiss** [comment]
@kraftbj - that should be pretty easy to roll in.  Something like:

Would you like to disable these notifications?  Manage your monitor settings here:
https://wordpress.com/settings/general/[JP-DOMAIN]

**Comment by samhotchkiss** [comment]
As this isn't release dependent, I'm clearing the milestone.  @richardmuscat, would you mind taking a look at this when you get a chance?  This is in `footer-jetpack.php` on wpcom

**Comment by jeherve** [comment]
Closing this, as a Manage link has been added to the Monitor emails.

**Comment by clu8** [comment]
I have redeployed a website which previously used WordPress with Jetpack Monitor. However, I am still getting several emails about my site going up and down every day. 

Going to https://wordpress.com/settings/general/[JP-DOMAIN] or https://wordpress.com/settings/security/[JP-DOMAIN] results in a mostly blank page with "Finishing set up..." in the top right. Any fixes for this? Thanks!

**Comment by jeherve** [comment]
@clu8 If you still experience issues, could you send us an email with more info about your site so we can take a closer look?
http://jetpack.com/contact-support/

Thanks!
