### ISSUE TITLE
When activate jetpack latest version, my rest api for woocommerce doesnt work

### ISSUE THREAD

**Issue by sebastianperear** [Automattic/jetpack#16140]
Before activate jetpack all work perfect with the same url 
![image](https://user-images.githubusercontent.com/66791158/84405927-6f787780-abce-11ea-9ad1-2d8e44f8e3dd.png)

**Comment by jeherve** [comment]
Thanks for the report. Could you give us more details about the problem so we can take a closer look?

- Do you get the same error code for all WooCommerce REST API queries?
- Is this limited to WooCommerce REST API queries, or does it happen for core REST API endpoints as well? 
- Is this when running the most recent version of the WooCommerce plugin?
- Do you use any other plugins on that site? Do you have the same issue when using only WooCommerce and Jetpack?

Thank you!

**Comment by sebastianperear** [comment]
Hi @jeherve thank you for your response. 
- Yes it's for all queries.
- It's for all REST API
- Yes, the latest version of woocommerce.
- Yes only when install jetpack , because in other site as work perfect, when install jetpack the rest api don't work ever. 

Thank you.

**Comment by jeherve** [comment]
Thanks for the extra details. Could you give us more details, some exact steps to reproduce, maybe an example route that returns that error? I can't seem to reproduce at the moment, when setting up a read only key and hitting the `wp-json/wc/v1/orders` route:

![image](https://user-images.githubusercontent.com/426388/84688982-86a5c500-af40-11ea-8de8-848f9990d028.png)

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
