### ISSUE TITLE
External Media: Improve Google Photos filtering options

### ISSUE THREAD

**Issue by jancavan** [Automattic/jetpack#16153]
This is what our current Google Photos filtering functionality looks like:

![ezgif-6-b1f575e711e3](https://user-images.githubusercontent.com/4924246/84546348-09ffb600-acb6-11ea-8bc0-c602e33854d5.gif)

As mentioned in: https://github.com/Automattic/jetpack/issues/15880#issuecomment-636956272, its UI and UX could use a lot of improvement.

Related: https://github.com/Automattic/jetpack/issues/15880

cc @Automattic/ajax @Automattic/dotcom-manage-design

**Comment by davemart-in** [comment]
This one is done I believe.
