### ISSUE TITLE
OpenTable block: Style "wide" is not responsive.

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#16156]
The OpenTable embed has different layouts including a "Wide 840x150px" version with a width of 840 pixels. I noticed that this block is being cut off on mobile with no way of accessing the hidden parts of the form (including the button).

#### Steps to reproduce the issue

1. Add an OpenTable block to a post or a page. Pick the "Wide 840x150px" block style.
2. Visit the post/page on desktop. 
3. Visit the post/page on mobile. Compare to the desktop version and notice how part of the form is cut off and inaccessible.

Tested on Safari/iPhone 11, but the issue is also visible when resizing the browser on desktop.
Themes: TwentyTwenty, Stratford.

![IMG_1673](https://user-images.githubusercontent.com/4550351/84611470-4f63f380-af01-11ea-99fd-1d6eced407ae.PNG)

#### What I expected
I expected the form would be responsive and all fields accessible across all devices.

**Comment by getdave** [comment]
I understand this is being handled by @Automattic/explorers and does not need to be picked up by the @Automattic/ajax janitor rotation. See p1598433481423500-slack-explorers
