### ISSUE TITLE
VideoPress: addVideoPressSupport() hook is messing up core/video's block attribute schema.

### ISSUE THREAD

**Issue by yansern** [Automattic/jetpack#16158]
The `addVideoPressSupport()` hook recreates the `core/video`'s block attribute schema instead of modifying the existing attribute schema that was passed in.

This causes the `align` property that was added to the attribute schema by the `align` hook from core to be removed.

More explanation in this issue comment: https://github.com/Automattic/wp-calypso/issues/43252#issuecomment-643581599

#### Steps to reproduce the issue

1. Go to post editor.
2. Create a video block.
3. Align the video left or right.
4. Save post.
5. Re-open post in editor.

#### What I expected
Video should still be aligned after reopening the post in editor.

#### What happened instead
Video is not aligned.

**Comment by simison** [comment]
@lessbloat would this be on Manage focus?
