### ISSUE TITLE
Media upgrade nudge text changes in response to Plan data being received

### ISSUE THREAD

**Issue by getdave** [Automattic/jetpack#16174]
Result of testing on https://github.com/Automattic/jetpack/pull/16171#pullrequestreview-431492378.

Essentially when the notice first appears there are two "states" for the text. 

Initially, the text has no mention of the plan "type" (eg: "WordPress Premium"), but then (depending on your network) sometime later this text is replaced with full details including information about the plan. This often happens quite quickly so there is a noticeable "jump" effect with the notice' text changing which is quite jarring.

Here's a screen capture (I'm uploading a video file btw!):

![Screen Capture on 2020-06-16 at 14-30-23 (1)](https://user-images.githubusercontent.com/444434/84787371-cf638980-afe5-11ea-9d6d-13cd4d11adf2.gif)

#### Steps to reproduce the issue

1. Go to Cover block
2. Open devtools and throttle to Slow 3G.
2. Click on `Upload`
3. Upload a video / movie file.
4. See upgrade notice change text content as per screenscapture.

#### What I expected
The text to remain constant without a "jump" between two states.

#### What happened instead
The text changed whilst I was reading the Notice. This was disconcerting and caused me to lose my place when reading.

**Comment by anomiex** [comment]
Relevant code was removed in https://github.com/Automattic/jetpack/pull/16598
