### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by nb** [Automattic/jetpack#1618]
Adding a new issue can be a daunting task. There are a ton of labels and maybe some conventions I don’t know about. As a reporter, it would be great if I can have a hint about how it will works.

If there is a `CONTRIBUTING.md` file in the root of the repository, GitHub [will show a nice yellow bar](https://github.com/blog/1184-contributing-guidelines) with a link to the file:

![screenshot](https://camo.githubusercontent.com/71995d6b0e620a9ef1ded00a04498241c69dd1bf/68747470733a2f2f6769746875622d696d616765732e73332e616d617a6f6e6177732e636f6d2f736b697463682f6973737565732d32303132303931332d3136323533392e6a7067)

**Comment by jeherve** [comment]
I like that! When we created the GitHub repo I added a new page in the Wiki and mentioned contributing there, but I didn't know about `CONTRIBUTING.md`. I'll take care of that.

**Comment by jeherve** [comment]
I did a first pass at contributing docs in 1855059baa397493bbe0cb10e87b3bee9624c1c0. I'd be happy to get feedback on it.

- Should we mentions [tests](https://github.com/Automattic/jetpack/tree/master/tests)?
- Should we mention [Grunt](https://github.com/Automattic/jetpack/blob/master/Gruntfile.js)?

**Comment by kraftbj** [comment]
I think it would be good to mention both, but stress what is minimum for contributing and what's nice to have, either within the repo here or on the jetpack.me page we're linking to.

**Comment by kraftbj** [comment]
> There are a ton of labels
@nb : Specifically on that, only a12s can add/modify labels as members of the Automattic GH group.  Internally, the JP devs and/or HEs can manage the labels. Generally, we'll update the issue to match conventions. The only one I can think of initially is the issue title is generally "[Module]: [Bug Title]"

**Comment by jeherve** [comment]
> I think it would be good to mention both, but stress what is minimum for contributing and what's nice to have 

Yeah. I would just be afraid to turn contributors away by mentioning things that seem too complicated.

**Comment by aheckler** [comment]
Maybe link to some small-ish "Good First Bugs" that had PR's to show what good ones look like?

**Comment by jeherve** [comment]
I added a few more things in ed23939a3cc5e78689c454c937059167cdfebde3

**Comment by nb** [comment]
Looks like a great start, thanks guys.
