### ISSUE TITLE
(5P) Social Previews: Add Jetpack sidebar panel

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#16195]
This will add a new section to the Jetpack sidebar that allows users on a Business/eCommerce plan to preview their posts in various social media channels. The "preview" link will be noop in this task.

# Design
Keeping it simple to provide an overview, display the social icons, and a CTA to preview.

<img width="1440" alt="02D" src="https://user-images.githubusercontent.com/67021691/88414099-51e02580-cdaa-11ea-8653-1310f0297d90.png">

See 84-gh-dotcom-manage.

**Comment by marekhrabe** [comment]
Jetpack plugin sidebar is already written as an extensible surface - we will add this using the slot/fill mechanism.

Existing Slot for the Jetpack sidebar: https://github.com/Automattic/jetpack/blob/4c63a49fc0139c3296248e09ee69dedb537e024f/extensions/shared/jetpack-plugin-sidebar.js

Example how existing features of the sidebar (Shortlink panel here) are being added dynamically. We'll copy this approach.

https://github.com/Automattic/jetpack/blob/4c63a49fc0139c3296248e09ee69dedb537e024f/extensions/blocks/shortlinks/index.js#L31-L35
