### ISSUE TITLE
(8P) Social Previews: Add modal with previews

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#16196]
Using the NPM package `@automattic/social-previews` which should already be required in Jetpack from #16594, this modal will show the social previews for the current post/page.

We will use components from the block editor to build the UI - `Modal` for sure and maybe something for the "tabs" on the left, or we will code the left sidebar from scratch.

#### Design

<img width="1440" alt="02E" src="https://user-images.githubusercontent.com/67021691/88414572-1560f980-cdab-11ea-8f12-8e0e7f08290a.png">

In case the heading font isn't available, we have a go to use a standard font that the block editor uses for the UI (eg: not override font-family and we should be good).

This builds on #16195 and https://github.com/Automattic/wp-calypso/issues/43469.
See 84-gh-dotcom-manage.

**Comment by marekhrabe** [comment]
For a reference, this is what an unstyled combination of Gutenberg [`<Modal>`](https://developer.wordpress.org/block-editor/components/tab-panel/) and [`<TabPanel>`](https://developer.wordpress.org/block-editor/components/modal/) components look like out of box. That could potentially be a good starting point in code for us, as it very likely has all the accessibility/focus management built-in and all we need is to style it.

<img width="409" alt="Screenshot 2020-07-22 at 17 45 50" src="https://user-images.githubusercontent.com/156676/88197828-4b836980-cc43-11ea-93b4-2ed2d09a9563.png">


```
export const modalWithTabs = () => {
    const modalProps = {
        isDismissible: true,
        shouldCloseOnEsc: true,
        shouldCloseOnClickOutside: true,
        title: 'Social Previews',
    };
 
    const [ isOpen, setOpen ] = useState( false );
    const openModal = () => setOpen( true );
    const closeModal = () => setOpen( false );
 
    return (
        <>
            <Button isSecondary onClick={ openModal }>
                Open Modal
            </Button>
            { isOpen && (
                <Modal { ...modalProps } onRequestClose={ closeModal }>
                    <TabPanel
                        className="my-tab-panel"
                        tabs={ [
                            {
                                name: 'tab1',
                                title: text( 'Tab 1 title', 'Facebook' ),
                                className: 'tab-one',
                            },
                            {
                                name: 'tab2',
                                title: text( 'Tab 2 title', 'Twitter' ),
                                className: 'tab-two',
                            },
                            {
                                name: 'tab3',
                                title: text( 'Tab 3 title', 'Google Search' ),
                                className: 'tab-three',
                            },
                        ] }
                    >
                        { ( tab ) => <p>Selected preview: { tab.title }</p> }
                    </TabPanel>
                </Modal>
            ) }
        </>
    );
};
```
