### ISSUE TITLE
Hide likes/sharing/related posts in print views

### ISSUE THREAD

**Issue by kjellr** [Automattic/jetpack#16205]
Jetpack should automatically hide extraneous elements like Likes, Sharing, and Related posts in print media. These are interactive elements, and don't make sense in the context of a printed page. 

## Screenshot

<img width="543" alt="Screen Shot 2020-06-19 at 3 20 06 PM" src="https://user-images.githubusercontent.com/1202812/85173421-3761dc00-b241-11ea-811c-e3bc8a13289a.png">

**Comment by spsiddarthan** [comment]
We're going to do address this in three separate PR's, one per feature as detailed below. 

- [ ] Hide share this section in the print view
- [ ] Hide the like posts section in the print view
- [ ] Hide the related posts section in the print view.

**Comment by spsiddarthan** [comment]
This issue has two more features that need to be addressed, reopening the issue.
