### ISSUE TITLE
Tiled Gallery - Choose images doesn't work

### ISSUE THREAD

**Issue by kismetjess** [Automattic/jetpack#1620]
I have installed jetpack and am trying to add the tiled images gallery to my sidebar. When I click "Choose Images" nothing happens. I have tried multiple browsers. Any ideas?

Http://www.southwestern.edu/suonline
![screen shot 2015-02-11 at 12 51 17 pm](https://cloud.githubusercontent.com/assets/10964304/6153778/b2d71e14-b1ec-11e4-84f1-84031bc480e2.png)

**Comment by richardmtl** [comment]
Hi! Something in your site is changing how widgets are behaving, and is likely affecting the media chooser as well. Can you contact us at http://jetpack.me/contact-support/ so we can help you? Please include a list of active plugins on your site. Thanks!

**Comment by jeherve** [comment]
The problem is most likely caused by a conflict between Jetpack's widgets and WordPress' accessibility mode. It might be worth trying to deactivate the accessibility mode and see if it changes anything. You can access accessibility options by clicking on Screen Options at the top right of the page.

**Comment by kismetjess** [comment]
Thanks for the quick reply. Unfortunately, that did not fix my issue.

On Wed, Feb 11, 2015 at 2:46 PM, Jeremy Herve <notifications@github.com>
wrote:

> The problem is most likely caused by a conflict between Jetpack's widgets
> and WordPress' accessibility mode. It might be worth trying to deactivate
> the accessibility mode and see if it changes anything. You can access
> accessibility options by clicking on Screen Options at the top right of the
> page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Automattic/jetpack/issues/1620#issuecomment-73961230>.
>



-- 
*Jessica Corliss*
Assistant Director of University Relations - Graphic Designer
Southwestern University
Georgetown, Texas
512.863.1036
<http://goog_1806220589>

<http://goog_1806220589>
<http://www.southwestern.edu/175>

**Comment by jeherve** [comment]
Sorry to hear that. Could you then contact us [via this contact form](http://jetpack.me/contact-support/) as @richardmtl suggested above? We'll be happy to run more tests with you to get to the bottom of the issue.
