### ISSUE TITLE
Stats module .js tag now causes 500 error due to broken src (plugin base url is being prepended)

### ISSUE THREAD

**Issue by codetipi** [Automattic/jetpack#16202]
#### Steps to reproduce the issue

1. Enable stats module.
2. Check console:

500 error:
https://mysite.com/wp-content/plugins/jetpack/https://stats.wp.com/s-202025.js 

#### What I expected
For the `https://stats.wp.com/e-' . gmdate( 'YW' ) . '.js` file to output without the plugin's base url prepended.

#### What happened instead
500 error due to broken tag src

**Comment by jeherve** [comment]
Thanks for the report. This will be fixed in the upcoming version of Jetpack. You can learn more about the error and find a workaround to fix your site until the release here:
https://github.com/Automattic/jetpack/pull/16047
