### ISSUE TITLE
Custom CSS: add to Customizer / merge with WordPress Core

### ISSUE THREAD

**Issue by BinaryMoon** [Automattic/jetpack#1621]
**Synopsis:** Custom CSS is being added to WordPress Core, and will ship with 4.7, scheduled to be released at the end of the year. Jetpack's Custom CSS module needs to be compatible with that new core Feature.

**Responsible:** TBD

**User experience:** We'll need to figure out a way to:

- Be compatible with the Core CSS editor.
- Stay compatible with existing Jetpack Custom CSS users.
- Stay compatible with themes and plugins using Custom CSS libs (e.g. [Semicolon](https://konstantin.blog/themes/semicolon/) or [Umbra](https://themes.redradar.net/blog/2014/12/08/introducing-umbra/))
- Be compatible with transfers from WordPress.com to a self-hosted WordPress site.

- Related Core ticket: https://core.trac.wordpress.org/ticket/38672
- Main Core CSS ticket: https://core.trac.wordpress.org/ticket/35395
- In Progress PR to add Jetpack's Custom CSS to the customizer. #3152
- Related issues: #1951, #1231

**Complete:** 0%

**Last Updated:** 2016-11-04 (by @jeherve)

**Original issue content:**

> I'd really like to see the custom css module added to the customizer. This works great on wordpress.com so hopefully some of the code can be shared from there. Using it in the Customizer makes using the custom css module fun (since you see instant updates) - whereas using it in a separate page is just a bit of a pain.

**Comment by westonruter** [comment]
FYI: This feature was brought up on the core dev chat today, starting at https://wordpress.slack.com/archives/core/p1473885305001533

**Comment by BinaryMoon** [comment]
@westonruter thanks for the heads up!

**Comment by jeherve** [comment]
I'll close this in favor of #5539, where we'll track all future improvements for the upcoming Core CSS feature.
