### ISSUE TITLE
Publicize - Refresh connection to LinkedIn text ilformatted 

### ISSUE THREAD

**Issue by alisterscott** [Automattic/jetpack#16226]
#### Steps to reproduce

1. Starting at URL: wordpress.com/post
2. Click Jetpack icon for site with broken LinkedIn connection

#### What I expected

Nicely formatted text

#### What happened instead

<img width="304" alt="Screen Shot 2020-04-07 at 5 20 10 pm" src="https://user-images.githubusercontent.com/128826/78742176-a3e97080-799e-11ea-8609-f80279417cef.png">

#### Browser / OS version

chrome latest on macOS latest

**Comment by cpapazoglou** [comment]
Transferred the issue to jetpack Repo (from wp-calypso) cause the affected component is `publicize` from jetpack extensions.
