### ISSUE TITLE
Facebook Video Embeds fail to render

### ISSUE THREAD

**Issue by AdrianMachado** [Automattic/jetpack#16225]
See discussion on: https://github.com/WordPress/gutenberg/issues/22774
It was suggested that I file an issue here.

#### Steps to reproduce the issue

1. Go to post editor
2. Search for the facebook block
3. Use a facebook video link (ex. https://www.facebook.com/NASA/videos/245765083275254)
4. See error in console
5. Publish the page
6. Visit page and no embed shows up

#### What I expected
The facebook video embed should show up.

#### What happened instead
When trying to embed a facebook video via Facebook embed block, embed block, or video block - 
I see the following error in the console
```
Block validation: Block validation failed for `core-embed/facebook` ({name: "core-embed/facebook", icon: {…}, attributes: {…}, keywords: Array(1), save: ƒ, …}attributes: align: {type: "string"}allowResponsive: {type: "boolean", default: true}ampLayout: {type: "string"}ampNoLoading: type: "boolean"__proto__: Objectcaption: {type: "string", source: "html", selector: "figcaption"}className: {type: "string"}providerNameSlug: type: "string"__proto__: Objecttype: {type: "string"}url: type: "string"__proto__: Object__proto__: Objectcategory: "embed"deprecated: Array(1)0: attributes: {url: {…}, caption: {…}, type: {…}, providerNameSlug: {…}, allowResponsive: {…}, …}save: ƒ (e)__proto__: Objectlength: 1__proto__: Array(0)description: "Embed a Facebook post."edit: ƒ r()icon: {foreground: "#3b5998", src: {…}}keywords: ["social"]name: "core-embed/facebook"save: ƒ (e)supports: {align: true}title: "Facebook"transforms: {from: Array(1), to: Array(1)}__proto__: Object).

Content generated by `save` function:

<figure class="wp-block-embed-facebook wp-block-embed is-type-rich"><div class="wp-block-embed__wrapper">
https://www.facebook.com/NASA/videos/245765083275254
</div></figure>

Content retrieved from post body:

<figure class="wp-block-embed-facebook wp-block-embed is-type-rich">[facebook url="https://www.facebook.com/NASA/videos/245765083275254
&lt;/" /]</figure>
```
and the videos fail to embed on me page. https://adrianweiwei.wordpress.com/2020/05/30/another-vod/

**Screenshots**
Seems there is an extra left chevron being added for some reason
![image](https://user-images.githubusercontent.com/11202679/85251113-52814700-b40d-11ea-888d-8b57ad24ca9b.png)

**Comment by jeherve** [comment]
Thanks for the report. We'll look into it. This may be specific to the WordPress.com environment, but that may be something we can fix in Jetpack.

**Comment by AdrianMachado** [comment]
@jeherve any progress here? Let me know if there's anything I can do to help from the FB side!

**Comment by jeherve** [comment]
This was fixed in r209717-wpcom. @AdrianMachado If you try to publish a new video on your site, things should work now!
