### ISSUE TITLE
Subscriptions: allow basic HTML tags in confirmation emails

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1623]
Steps to reproduce:
1. Enable Jetpack Subscriptions
2. Go to Settings > Reading > Follower settings in your dashboard.
3. Enter some custom confirmation text, including basic HTML tags like links, or `strong`.
4. Save your changes.
5. Your tags appear in the saved text.
6. Subscribe to your site.
7. The confirmation email you receive doesn't include any of these tags.

It would be nice to allow these tags in the confirmation emails, or at least remove them upon saving your custom text.

**Comment by georgestephanis** [comment]
Sounds like they're being kses'd out when used, but not when saved.

What tags and attributes do we want to allow?

**Comment by jeherve** [comment]
It feels like anything in [here](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/kses.php#L60) would be useful. We could limit it to [this](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/kses.php#L419) if we don't want anything that would break the email layout.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
