### ISSUE TITLE
Write Unit tests to Connection Manager::is_registered

### ISSUE THREAD

**Issue by leogermani** [Automattic/jetpack#16250]
Write PHPUnit tests for Connection Manager::is_registered() method.

See #16057

**Comment by kbrown9** [comment]
Note that I changed the title and description from `is_active` to `is_registered`. There are a couple of tests for `Manager::is_active()` [here](https://github.com/Automattic/jetpack/blob/master/packages/connection/tests/php/test_Manager.php#L93). We need unit tests for `is_registered()`.
