### ISSUE TITLE
AMP Sharing Support: undefined constant warnings

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#16259]
I've just noticed the following warnings in the logs of a site running Jetpack `master` and the AMP plugin in Reader mode. The Sharing module is not enabled on the site.

```
PHP Warning:  Use of undefined constant WP_SHARING_PLUGIN_DIR - assumed 'WP_SHARING_PLUGIN_DIR' (this will throw an Error in a future version of PHP) in /wp-content/plugins/jetpack/3rd-party/class.jetpack-amp-support.php on line 435
PHP Warning:  file_get_contents(WP_SHARING_PLUGIN_DIRamp-sharing.css): failed to open stream: No such file or directory in /wp-content/plugins/jetpack/3rd-party/class.jetpack-amp-support.php on line 435
```

This was introduced in #15497. 

cc @MattGeri who worked on the original PR. I think we'd want to add a check to make sure the Sharing module is active before we do anything.

**Comment by MattGeri** [comment]
Thanks for the information @jeherve, I will have a look at this now and see what the issue is.

**Comment by MattGeri** [comment]
@jeherve I've pushed a hotfix PR for this: https://github.com/Automattic/jetpack/pull/16260
