### ISSUE TITLE
Allow custom post statuses to be set

### ISSUE THREAD

**Issue by theukedge** [Automattic/jetpack#1625]
In the Post By Email module, it would be nice if the [status] shortcode supported custom post statuses, such as those created by [Edit Flow](https://wordpress.org/plugins/edit-flow/).

**Comment by samhotchkiss** [comment]
Our implementation of Post by Email is intended to be very simple and minimal, so, unfortunately, this doesn't align with our development goals and plans at this time, and is not on our roadmap for future development.
