### ISSUE TITLE
Subscriptions: Follow button missing wp-block-button__link class

### ISSUE THREAD

**Issue by BinaryMoon** [Automattic/jetpack#16263]
Hi

The subscription form block includes a 'follow' button. In the editor it includes a `wp-block-button__link` class. On the front end this class has gone.

This makes it harder to create consistent styles.

It would be better if the class was included on both the front and back end of the site. The following screenshots were taken on my WordPress.com sandbox.

**Editor:**
<img width="1174" alt="Screenshot 2020-06-24 at 13 47 47" src="https://user-images.githubusercontent.com/1004130/85559238-72895400-b621-11ea-9cae-804d60fce1f7.png">

**Front end:**
<img width="1194" alt="Screenshot 2020-06-24 at 13 47 37" src="https://user-images.githubusercontent.com/1004130/85559164-5e455700-b621-11ea-8b4f-dd936926b2d5.png">

There are other classes missing as well but that's the one that's most used since it works on all GB button blocks.

Thanks

**Comment by jeherve** [comment]
cc @apeatling who worked on the Subscription block changes in #15107.

**Comment by creativecoder** [comment]
@apeatling Looks like you're working on this. If that changes and you have other priorities, please send this over to https://github.com/orgs/Automattic/projects/172 for triage.
