### ISSUE TITLE
[Widget visibility] make it with BuddyPress

### ISSUE THREAD

**Issue by gregoirenoyelle** [Automattic/jetpack#1627]
Hi
Great plugins. Thanks. 
For managing, I use a custom taxonomy as filter to make my conditionals. 
in BuddyPress, you can choose a Page for the members. In this physical page, I have apply the same taxonomy but the filter do not works. Is it a BuddyPress limitation?
Have you a better way to do it?
Thanks

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
