### ISSUE TITLE
Social Menu & Social Media Icons: Add Telegram Support

### ISSUE THREAD

**Issue by 360fun** [Automattic/jetpack#16281]
When I add a **t.me/nickname** or **telegram.me/nickname** Telegram profile link the icon is a generic "chain" and not the official paper plane one:
![image](https://user-images.githubusercontent.com/844090/85639240-5f5d9f00-b688-11ea-856e-45f8a5c89452.png)

**Comment by scottsweb** [comment]
The underlying issue here appears to be that `Genericons` are being used to render the icons, but there is no Genericon for Telegram. This could be solved by bringing the SVG into CSS directly, or updating the original icon font.

**Comment by 360fun** [comment]
> The underlying issue here appears to be that `Genericons` are being used to render the icons, but there is no Genericon for Telegram. This could be solved by bringing the SVG into CSS directly, or updating the original icon font.

Actually social icons are not part of `Genericons` but `social-menu.svg` inside **JetPack**:
https://github.com/Automattic/jetpack/blob/62b20bf86f4ddd8eaa8e10c2dedcd4356a7437c6/modules/theme-tools/social-menu/social-menu.svg

**Comment by jeherve** [comment]
@scottsweb or anyone interested in contributing a fix: here is what it would take to add the icon to Jetpack, with a previous example: #15065. The Telegram logo can be found here:
https://github.com/Automattic/social-logos/blob/98daee5f3e1c028b522c6c54357d4b53c1d69b14/svg-min/telegram.svg

**Comment by 360fun** [comment]
> @scottsweb or anyone interested in contributing a fix: here is what it would take to add the icon to Jetpack, with a previous example: #15065. The Telegram logo can be found here:
> https://github.com/Automattic/social-logos/blob/98daee5f3e1c028b522c6c54357d4b53c1d69b14/svg-min/telegram.svg

I can do it but wouldn't be nicer the "plane" version? like this one:
https://fontawesome.com/icons/telegram-plane?style=brands

**Comment by 360fun** [comment]
I put both, just delete the not necessary one if you don't want to keep 2 versions. ;)
