### ISSUE TITLE
Site Icon: Images not on local filesystem don't work

### ISSUE THREAD

**Issue by ryanmarkel** [Automattic/jetpack#1629]
When in an environment where uploads are not on the local filesystem of the host blog, uploading a site icon creates a junk response and the image is not properly updated.

>PHP Warning: fopen(http://ryanmarkel.com/wp-content/uploads/2015/01/ico7-54c1aab0v1_site_icon.png): failed to open stream: HTTP wrapper does not support writeable connections in wp-includes/class-wp-image-editor.php on line 424

Here's an example of the output on trying to save the new site icon:

![e2c006c0-a082-11e4-9891-02f1172327f4](https://cloud.githubusercontent.com/assets/4636317/6182845/62eef0ae-b311-11e4-9618-486990772490.png)

**Comment by jeherve** [comment]
Could you try to test again with Master? We've made a few changes in #1380, but the commits are not part of any stable release yet, they'll be shipped with 3.4.

**Comment by ryanmarkel** [comment]
I pulled master last night before filing the report. The same problem is still happening.

**Comment by jeherve** [comment]
Thanks!

cc @enejb

**Comment by enejb** [comment]
@ryanmarkel My guess this is not the case for you. (But just for my sanity). Do you have problems uploading images to your site though the media uploader build into WordPress?

**Comment by ryanmarkel** [comment]
@enejb Any word on this one? We'll be putting clients on v2 before long and I just tested and it's still broken for me. I have no trouble uploading to the media library.

**Comment by jeherve** [comment]
@ryanmarkel See #1895 for a related Pull Request.

**Comment by kraftbj** [comment]
Marking as closed deferring to Core's feature in 4.3.
