### ISSUE TITLE
Sharing: icons are off-center in Icon-only button style 

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#16301]
Follow-up from #16294. 

The sharing icons are a bit off-center in Icon-only button style:

![](https://user-images.githubusercontent.com/426388/85848446-70ea9800-b7a9-11ea-8452-a56f46311885.png)

**Comment by idiosyn** [comment]
In **sharing.css**, changing this

```
.sd-social-icon .sd-content ul li[class*='share-'] a.sd-button:before {
	top: 1px;
}
```
to `top: 0;` apparently solves the issue (or at least makes it less bad).

**Comment by jeherve** [comment]
Also reported in p8oabR-BT-p2#comment-4946
