### ISSUE TITLE
Carousel: Javascript error in IE8

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1631]
Carousel uses `Date.now` ([#](https://github.com/Automattic/jetpack/blob/3.3.1/modules/carousel/jetpack-carousel.js#L395), [#](https://github.com/Automattic/jetpack/blob/3.3.1/modules/carousel/jetpack-carousel.js#L565)), that is not supported in installed versions earlier than Internet Explorer 9:
https://stackoverflow.com/questions/9430357/please-explain-why-and-how-new-date-works-as-workaround-for-date-now-in/16456107#16456107

We'd need to handle that to avoid errors in older versions of Internet Explorer.

Reported here:
https://wordpress.org/support/topic/datenow-bug-in-ie8?replies=1

**Comment by georgestephanis** [comment]
I'd like to add a line or two to make it work, if it's not terribly difficult

IE8 I'm fine with graceful degradation on, but something that might kill JS evaluating -- I'd like to not have it crash.

**Comment by georgestephanis** [comment]
IE8 still seems to have substantial market share, by my first googling anyways -- https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0

**Comment by osiux** [comment]
So per the SO post, adding something like

	if ( typeof Date.now === 'undefined' ) {
		Date.now = function () {
			return +new Date();
		}
	}

At about line ~13 should be enough? Or better to check IE version before running that code?
