### ISSUE TITLE
Pinterest pin title overlaps on mobile

### ISSUE THREAD

**Issue by bsanevans** [Automattic/jetpack#16325]
#### Steps to reproduce the issue

1. Add a Pinterest block to a new post and insert link
2. Publish
3. Check browser on mobile

#### What I expected
Pin titles should not be overlapping other details at the bottom of the pin card

#### What happened instead
![Webp net-compress-image](https://user-images.githubusercontent.com/49054298/86074654-4eb28c00-bac1-11ea-85a7-4fbd6ad378d8.jpg)

Originally reported on 22274534-hc (follow-up 3104336-zen)

Confirmed on Simple, Atomic and Self-Hosted, all using different themes.

**Comment by jeherve** [comment]
I'm afraid that's not something we may be able to fix on our end. The card styles are controlled by Pinterest themselves.

Pinterest does not seem to have a bug reporting platform we could use to report that bug to them I'm afraid, so I am not too sure what to suggest here; you could try to use the report tool on that specific pin to send them a screenshot of how the pin looks like on mobile:
https://help.pinterest.com/en/article/report-something-on-pinterest

**Comment by bsanevans** [comment]
Thanks for looking into that. I will let the user know.
