### ISSUE TITLE
Publicize: Add Parler to List of Connection Options

### ISSUE THREAD

**Issue by mbhthompson** [Automattic/jetpack#16347]
https://parler.com/

Requested in 3106897-zen

**Comment by jeherve** [comment]
I'll close this for now, for 3 reasons:

- Parler is still new, and we'd need to wait a bit to ensure the service would be a good long-term candidate for Publicize.
- The service does not offer any public API yet, so we will not be able to integrate with it yet.
- We're not currently planning on adding any new Publicize options at the moment.
