### ISSUE TITLE
Send a Message Block: Phone # with country code - error message does not disappear when corrected.

### ISSUE THREAD

**Issue by inaikem** [Automattic/jetpack#16349]
#### What I expected
If a number is entered incorrectly and then fixed, the message should disappear.

#### What happened instead
The error message remained after correction (see below).

#### Steps to reproduce the issue

1. Enter phone number (with country code and "+" sign, no spaces).
2. "Please enter a valid phone number." error message appears.
3. Correct number by removing "+" sign and country code.
4. Error message remains.
5. Save/preview.
6. Error message cleared.

NB: Removing the CC and adding a "0" clears the error without needing to refresh.

#### Screenshot
<img width="287" alt="Screen Shot 2020-07-01 at 12 31 16 PM" src="https://user-images.githubusercontent.com/66711744/86203128-c7cfe300-bb96-11ea-8f52-459b161320ef.png">

#### Environment
- Jurassic Ninja (fresh install, no mods)
- macOS 10.14.6
- Chrome 83.0.4103.116 (Official Build) (64-bit)

**Comment by jeherve** [comment]
cc @apeatling
