### ISSUE TITLE
Search: Implement Grid/Product Results Layout

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#16367]
We already have this partially implemented.

<img width="996" alt="Screen Shot 2020-07-01 at 10 36 09 AM" src="https://user-images.githubusercontent.com/820871/86299088-8eaa6980-bbbc-11ea-9417-54c2c08dd0b3.png">

Missing features and requests for features:
- [ ] Display WooCommerce prices
  - [ ] Fallback to displaying prices from `price` post meta when woo data is not there: https://github.com/Automattic/jetpack/issues/15666#issuecomment-652631474
  - [ ] Display coupons or on-sale info
- [ ] Display WooCommerce currencies
- [ ] Display highlights from reviews/comments
- [ ] Display a custom taxonomy value on the items. Something like `jetpack_search_label`. https://github.com/Automattic/jetpack/issues/15666#issuecomment-652631474

**Comment by StefMattana** [comment]
Hey @gibrown I have a user in #3728749-zen who's trying to get three columns for search results as it's more e-commerce friendly. 

Both @bindlegirl  and I tried to replicate this layout ^^ in our test sites with no success. Are we missing something out or we still need to deploy this feature? Thanks :)

**Comment by StefMattana** [comment]
@bindlegirl has tracked down this problem that's been reported here: https://wp.me/p8oabR-B4#comment-4869

Adding this bit in case it helps also to provide a compelled answer to this user :)

**Comment by gibrown** [comment]
Ya, the implementation of this is still a WIP, though I think will be out in the next release.

**Comment by gibrown** [comment]
This is done
