### ISSUE TITLE
Payments: payments block links to the wrong support doc

### ISSUE THREAD

**Issue by artpi** [Automattic/jetpack#16377]
The “Read more about Payments and related fees.” link in the Payments block links to https://wordpress.com/support/wordpress-editor/blocks/payments/#related-fees	which redirects to https://wordpress.com/support/store/payments/#related-fees	which talks about managing payments in WooCommerce. It should link to related fees to using Stripe – WooCommerce is not involved in any capacity in this block AFAIK.

Per @atanas-dev

**Comment by jeherve** [comment]
This should be fixed. The support doc was not published.
