### ISSUE TITLE
Lazy load not working with AJAX Load More using jscroll

### ISSUE THREAD

**Issue by bhautiknada** [Automattic/jetpack#16379]
Hello,

We are using Jetpack lazy load for the images. We implemented jscroll to load posts using AJAX instead of pagination. When we load next set of posts, the thumb image is not loading for those posts. Right now, Thumbs are loading properly on local server but not on live server.

It seems like Jetpack lazy load is not initializing properly after AJAX load. We are triggering this function after the AJAX call.

`$( document.body ).trigger('post-load');`

This was working alright before few months. 

Any help would be appreciated.

Thanks,
Bhautik

**Comment by jeherve** [comment]
Closing since the feature is now removed from Jetpack in favor of Core's implementation. See #33782.
