### ISSUE TITLE
SSO: JITM popping up even though login occurred via username+password

### ISSUE THREAD

**Issue by keoshi** [Automattic/jetpack#16378]
#### Steps to reproduce the issue

1. Start with a connected Jetpack site and with SSO enabled.
1. Add a second user though wp-admin.
1. Log in as the second user by picking the option to enter username + password.

#### What I expected

No SSO notice to be displayed.

#### What happened instead

A JITM letting me know I successfully logged in with SSO, even though I didn't.

**Screenshots**

![image](https://user-images.githubusercontent.com/390760/86470116-aefc3480-bd32-11ea-966a-314f91400cb3.png)

**Comment by jeherve** [comment]
Closing this one as we've now removed this JITM: #17077.
