### ISSUE TITLE
jetpack-admin-rtl.css

### ISSUE THREAD

**Issue by emiluzelac** [Automattic/jetpack#1637]
From: https://github.com/Automattic/jetpack/blob/master/css/jetpack-admin-rtl.css

The value of 90 needs a length, number alone will not work.

```
@media (max-width: 530px) {

    .clouds-sm {
        height: 90
    }
}
```

Max with does not support auto: https://developer.mozilla.org/en-US/docs/Web/CSS/max-width

```
.jetpack_page_jetpack_modules .header-nav {
    max-width: auto;
    margin: 0
}
```

There is a typo here:

```
.footer .a8c-attribution {
    margin-top: 6px auto 0;
    padding: 0 6px;
    font-size: 0.78571em;
    font-family: "Gill Sans", "Gill Sans MT", "Open Sans", Helvetica, Arial, sans-serif;
    text-transform: uppercase
}
```

Margin top can't have more than one value.

**Comment by jeffgolenski** [comment]
Great finds @emiluzelac Ill fix those up over the weekend. Thank you!

**Comment by emiluzelac** [comment]
You guys are super fast :+1:

**Comment by jeffgolenski** [comment]
@emiluzelac Just love what we do... always trying to make the web a better place!

**Comment by emiluzelac** [comment]
Same here.

**Comment by emiluzelac** [comment]
Sorry, this will also affect: https://raw.githubusercontent.com/Automattic/jetpack/master/css/jetpack-admin.css as well :)

**Comment by jeffgolenski** [comment]
Cleaned up in: https://github.com/Automattic/jetpack/commit/03689be5a78cebf3dc1d7fb9f0970d8b43603337

Thanks for discovering these. Moving forward I'll be cleaning up a lot more css, so anytime you find anything like this, just let me know!

**Comment by emiluzelac** [comment]
Thanks
