### ISSUE TITLE
Photon: handle Rocket Lazy Load

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1638]
Jetpack's Photon already supports Lazy load plugins that use `data-lazy-src` to handle original images ([ref](https://github.com/Automattic/jetpack/blob/master/class.photon.php#L158)). It'd be nice to handle plugins using another handle.

Rocket Lazy Load, for example, uses `data-lazy-original` ([ref](https://plugins.trac.wordpress.org/browser/rocket-lazy-load/trunk/rocket-lazy-load.php#L78)).

**Comment by gravityrail** [comment]
We now have an official Lazy Load solution, and it's probably wise to recommend against other Lazy Load plugins when using Photon.

https://github.com/Automattic/jetpack/pull/8093
