### ISSUE TITLE
Photon: animated gifs have bad quality

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#16380]
Hi, I found this while trying to upload a gif to a post. Photon renders the gifs with very low quality as
https://i2.wp.com/startfunction.com/wp-content/uploads/2020/07/reactgc.gif?resize=705%2C333&ssl=1

You can see the original gif at the end of this post
https://startfunction.com/how-to-create-deno-cli-tool/#react-generate

I had to tell Photon to skip gif images using the `jetpack_photon_skip_for_url` filter
Kudos to @jeherve for writing https://developer.jetpack.com/hooks/jetpack_photon_skip_for_url/ 👍 

Ideally, I'd have all images processed/delivered by Photon but gifs are right now rendered with very bad quality.

**Comment by jeherve** [comment]
Thanks for the report. I was able to reproduce with another gif on my end. I opened a ticket here (that is where the Photon service lives):
https://code.trac.wordpress.org/ticket/92
