### ISSUE TITLE
Email site users to request they whitelist their IP

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#1641]
Allow a site admin email all the site's users with a click of a button, asking them to whitelist themselves on the Protect module.
Users will receive a special link that they can use to automatically add their current IP address to the whitelist

**Comment by samhotchkiss** [comment]
I don't know about this-- the goal of protect is to be totally invisible and not need pro-activity from users in 99.999% of situations.

I'd be more apt to support a better tool for helping locked out users.

**Comment by roccotripaldi** [comment]
Agree. Closing as a wontfix.

**Comment by jeherve** [comment]
Couldn't we do this without even asking the user? Whenever the module is activated, Jetpack queries for the user's IP address, and adds it to the whitelist?

**Comment by roccotripaldi** [comment]
That is a neat idea. I've always liked the idea of smart, automatic whitelisting.
Similar ideas have been brought up in the past, and we always end up squelching them for one reason or an other. Unfortunately, I cannot find any records of the conversations. Perhaps it is time for a P2 post on the matter.
