### ISSUE TITLE
Instant Search: Changing default sort discards other Customizer changes

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#16418]
#### Steps to reproduce the issue

1. Ensure that your site has the Jetpack Search product.
2. Go to the Jetpack Search section of the Customizer.
3. Change any setting that doesn't cause a page refresh (e.g. "Show sort selector").
4. Ensure that the change from step 3 works as expected in the Customizer iframe.
5. Change the default sort setting; this should refresh the Customizer iframe.

#### What I expected
Changes from step 3 should be applied along with the default sort change from step 5.

#### What happened instead
Changes from step 3 are discarded and only changes from step 5 are applied.

First reported by p8oabR-wn-p2#comment-4351.

**Comment by kangzj** [comment]
Hey @jsnmoon I couldn't reproduce this. Are you still able to?

**Comment by jsnmoon** [comment]
Thanks for looking into this, @kangzj. I'm also not able to reproduce -- closing this issue now.
