### ISSUE TITLE
Admin becomes unscrollable after contact form modal closes

### ISSUE THREAD

**Issue by bfintal** [Automattic/jetpack#1642]
While editing a post/page, opening and closing the contact form modal prevents the page from scrolling. I removed all plugins aside from Jetpack and it still occurs.

Steps to replicate:
1. Create a new page/post
2. Click on the **Add Contact Form** button
3. Add a new contact form
4. Click again on the **Add Contact Form** button
5. Close the modal by either clicking on the **X** button then the **okay** button to close it, or re-insert the contact form
6. You will be unable to scroll the page

Another way:
1. Create a new page/post
2. Click on the **Add Contact Form** button
3. Close the modal by clicking on the **X** button then the **okay** button to close it
4. You will be unable to scroll the page

**Comment by jeherve** [comment]
I could reproduce:

https://cloudup.com/cyzFCvUyo_k

**Comment by bfintal** [comment]
@jeherve Oh yea, no errors in the page. Thanks
