### ISSUE TITLE
Post-By-Mail Doesn't Trigger Webhooks

### ISSUE THREAD

**Issue by microslayer** [Automattic/jetpack#16429]
#### Steps to reproduce the issue

1. Create a WordPress.com blog (in my case, I used the [P2 Theme](https://wordpress.com/p2/)). 
2. [Create a webhook](https://wordpress.com/support/webhooks/) on new post creation.  
3. Set up [Post-By-Mail](https://wordpress.com/support/post-by-email/).  
4. Create a new post by sending an email to the mail obtained in step 3. 

#### What I expected

The post created by the email should trigger the webhooks. 

#### What happened instead

The webhooks do not execute, but do execute on a post created manually.

**Comment by simison** [comment]
FYI @Automattic/lighthouse since P2 mentioned. :-)

**Comment by jeherve** [comment]
Internal reference: s3hLNG-bug-p2

**Comment by jeherve** [comment]
Unfortunately, I don't think there is much we'll be able to do from the Jetpack end about that problem; the API behind Post By Email lives on WordPress.com, and the webhooks are handled by a separate plugin on WordPress.com (HookPress).

I created 8215-wpcom to keep track of this on the WordPress.com side.

**Comment by lezama** [comment]
Thanks for the ping @simison !

I hope you are enjoying your new P2 @microslayer! Please ping me if you encounter any other P2 issues or if you have any feedback.
