### ISSUE TITLE
(3P) External Media: uploaded images are not attached to post on WordPress.com sites

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#16425]
#### Steps to reproduce the issue

1. Go to Posts > Add New
2. Write a few words, save your draft.
3. Insert an image block.
4. Pick an image, either from Pexels or from Google Photos
5. Insert it.
6. Save your draft again.
7. Go to Media > Library
8. You'll notice that the new image is not attached to its parent post.

**Comment by jeherve** [comment]
This was fixed in Jetpack in #16558, but the issue remains on WordPress.com. We may have to make a similar set of changes for the `rest/v1.1/external-media-upload` endpoint as well (that's what's in use on wpcom simple sites).

**Comment by obenland** [comment]
> We may have to make a similar set of changes for the `rest/v1.1/external-media-upload` endpoint as well (that's what's in use on wpcom simple sites).

Can we add a new parameter to an endpoint without versioning it?

First pass in D47566-code.

**Comment by ebinnion** [comment]
> Can we add a new parameter to an endpoint without versioning it?

Yes. Generally, we've taken the stance that adding extra data to an endpoint was fine. But, modifying, or removing, existing data required a version change.

**Comment by obenland** [comment]
Deployed in r212074-wpcom

**Comment by mreishus** [comment]
Reverted in r212349-wpcom.  Possibly caused an issue with iOS uploads? p1HpG7-9XE-p2

**Comment by ebinnion** [comment]
@mreishus – It looks like that's no longer the issue. Would you mind recommitting?

**Comment by mreishus** [comment]
This did not cause the issue we were looking at earlier; redeployed.

Deploy: r212074-wpcom (8/12)
Revert: r212349-wpcom (8/19)
Re-deploy: r212451-wpcom (8/20)
