### ISSUE TITLE
Tiled Gallery images disappear after load (localhost)

### ISSUE THREAD

**Issue by bradley2083** [Automattic/jetpack#16426]
#16007 ## Steps to reproduce the issue

1. In local install, add Tiled Gallery
2. Upload images to gallery
3. Gallery images load and once loaded, they disappear (and show 404 in the dev console)

#### What I expected
Images to appear in gallery.

**Screenshots**
<img width="792" alt="Screen Shot 2020-07-07 at 10 56 40 AM" src="https://user-images.githubusercontent.com/1781226/86822561-a3fe1880-c040-11ea-90d5-e5e75f2e6b11.png">

**Comment by jeherve** [comment]
> In local install, add Tiled Gallery

Thanks for the report. The Tiled Gallery block relies on Jetpack's Image CDN to resize the images on the fly, and consequently cannot be used on a site that's not publicly accessible, where the CDN cannot fetch the images. Ideally the block would not appear when your site is not connected to WordPress.com to avoid this confusion. We'll get this fixed. 👍
