### ISSUE TITLE
Jetpack Lazyload and Cumulative Layout Shift (CLS) 

### ISSUE THREAD

**Issue by talgalili** [Automattic/jetpack#16421]
#### Is your feature request related to a problem? Please describe.

The recent google update has highlighted “Cumulative Layout Shift (CLS)” as an important feature to pay attention to.
Sadly, jetpack’s lazyload is damaging that metric, since when using it we get a shift in the content once the image is loaded.

#### Describe the solution you'd like
Several solutions would be great:
1. make lazy load wrap the img tag with <div style=”min-height:100px;”> <img…> </div>
When the image height “min-height:100px;” is decided based on the height of the image.
This could be taken from the height parameter set in img (ideal first solution).
An even better fallback is to detect the image height and set it based on that (the best solution would offer to do it also for images that are hosted outside of the website).
2. to add a control parameter of "port height" that will indicate how close should the user be before the image will start loading. Currently, this value is 0. But if it were to be (say) 100px (or some other configurable method), then the images would be loaded before the user sees them (but after the rest of the page load, and only conditional on the user scrolling down).

These features would be great.

#### Describe alternatives you've considered
Turn off the plugin.

#### Additional context
https://web.dev/cls/

**Comment by amooreTO** [comment]
@talgalili perhaps this will also help with the CLS issue https://github.com/Automattic/jetpack/pull/16034

**Comment by talgalili** [comment]
@amooreTO it looks good!
I'm waiting for the PR to be reviewed and all the issues to be addressed.
Thanks for the ping. :)
