### ISSUE TITLE
Sharing: add option to upload/insert icon to custom service

### ISSUE THREAD

**Issue by elliott-stocks** [Automattic/jetpack#1644]
When specifying an Icon URL for a custom service it requires the full URL. We could still keep that option but also add a button which opens up the media frame for quicker uploading/inserting of icons hosted locally.

Retina support for icons would be a bonus too!

**Comment by jkudish** [comment]
I think this is too much of an edge case for us to add. @aduth do you agree?

**Comment by aduth** [comment]
@jkudish: It would certainly be lower priority based on the usage patterns, but it's a reasonable request. For the moment this can be accomplished via Media > Click item > Highlight and copy URL field.

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/custom-sharedaddy-sharing-service-button-icon?replies=1

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
