### ISSUE TITLE
PHP Notice/Warning in Instagram connections API endpoint when not connected

### ISSUE THREAD

**Issue by dd32** [Automattic/jetpack#16443]
#### Steps to reproduce the issue

1. Request 'https://example.site/wp-json/wpcom/v2/instagram-gallery/connections' when Jetpack isn't connected
2. Observe PHP logs for warnings/notices.
3. See error.

#### What I expected

No PHP Warnings/Notices to be generated

#### What happened instead
 - E_NOTICE: wp-content/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-instagram-gallery.php:137 - Undefined property: stdClass::$connections
 - E_WARNING: wp-content/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-instagram-gallery.php:137 - Invalid argument supplied for foreach()

This happens because `Client::wpcom_json_api_request_as_user()` returns https://github.com/Automattic/jetpack/blob/master/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-instagram-gallery.php#L125-L138
```
wp-content/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-instagram-gallery.php:135:
object(stdClass)[1351]
  public 'code' => string 'rest_cannot_view' (length=16)
  public 'message' => string 'Sorry, an active connection must be used to access this resource.' (length=65)
  public 'data' => 
    object(stdClass)[1353]
      public 'status' => int 401
```

**Comment by pablinos** [comment]
I was just fixing this and discovered that @kraftbj beat me to it. This is fixed by #16451

**Comment by kraftbj** [comment]
Oh sorry! Didn't even see the issue!

**Comment by pablinos** [comment]
No problem, it was perfect timing!
