### ISSUE TITLE
Open Graph: 8.7 og:description refactoring breaks expected behavior

### ISSUE THREAD

**Issue by cagrimmett** [Automattic/jetpack#16459]
The 8.7 release changed the way Open Graph meta description tags are handled.

The refactored code to get the og:description content falls back to 'Visit the post for more' if there's an image tag/gutenberg image block at the beginning of the post.

The [refactoring](https://github.com/Automattic/jetpack/commit/8db9ae25e92513dcc7e37890f3cebbef75756fdd) changed the order of some calls, namely removing URLs and stripping HTML tags. It now removes URLs first, which invalidates the `img` tag by removing the last `"` of the src attribute. Stripping HTML tags next removes the `img` tag and everything after instead of just the `img` tag itself. If the description is empty it uses the fallback text.

This causes posts that start with an image and do not have an excerpt to fall back to 'Visit the post for more' when the expected behavior is that the image gets stripped and the remaining text is set as the description.

h/t to @robrobsn for figuring this out.

**Comment by cagrimmett** [comment]
Pinging @jeherve, who authored these changes in the 8.7 release.

**Comment by jeherve** [comment]
Also in p1594497671124000-slack-jpop-support
