### ISSUE TITLE
JetPack's 8.7 update the have added new social icon code and that is breaking in AMP pages

### ISSUE THREAD

**Issue by TMsravan** [Automattic/jetpack#16465]
Below is the error coming on the site  showmetech.com.br and corporate.showmetech.com.br. due to this amp page is not getting validated.

This is the test url https://search.google.com/test/amp?skip_amp_follow=true&id=ZXCwxoGDMN9V0cqu76m52Q

and when I debug it I have figured out the issue, this was due to JetPack's 8.7 update the have added new social icon code and that is breaking in AMP pages,

If I turn-off social icons or rollback Jetpack to 8.6 and it's working fine.

once rolling back to old version of Jetpack the test passed in showmetech.com.br

[09-Jul-2020 14:41:13 UTC] PHP Fatal error:  Uncaught Error: Class 'AMPforWP\AMPVendor\WP_Error' not found in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php:583
Stack trace:
#0 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1623): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->get_validated_url_file_path('social-logos.wo...', Array)
#1 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1507): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_font_face_at_rule(Object(Sabberworm\CSS\RuleSet\AtRuleSet))
#2 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1350): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_css_declaration_blo in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php on line 583
[09-Jul-2020 14:41:15 UTC] PHP Fatal error:  Uncaught Error: Class 'AMPforWP\AMPVendor\WP_Error' not found in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php:583
Stack trace:
#0 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1623): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->get_validated_url_file_path('social-logos.wo...', Array)
#1 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1507): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_font_face_at_rule(Object(Sabberworm\CSS\RuleSet\AtRuleSet))
#2 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1350): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_css_declaration_blo in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php on line 583
[09-Jul-2020 14:41:19 UTC] PHP Fatal error:  Uncaught Error: Class 'AMPforWP\AMPVendor\WP_Error' not found in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php:583
Stack trace:
#0 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1623): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->get_validated_url_file_path('social-logos.wo...', Array)
#1 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1507): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_font_face_at_rule(Object(Sabberworm\CSS\RuleSet\AtRuleSet))
#2 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1350): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_css_declaration_blo in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php on line 583
[09-Jul-2020 14:41:19 UTC] PHP Fatal error:  Uncaught Error: Class 'AMPforWP\AMPVendor\WP_Error' not found in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php:583
Stack trace:
#0 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1623): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->get_validated_url_file_path('social-logos.wo...', Array)
#1 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1507): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_font_face_at_rule(Object(Sabberworm\CSS\RuleSet\AtRuleSet))
#2 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1350): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_css_declaration_blo in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php on line 583
[09-Jul-2020 14:41:20 UTC] PHP Fatal error:  Uncaught Error: Class 'AMPforWP\AMPVendor\WP_Error' not found in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php:583
Stack trace:
#0 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1623): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->get_validated_url_file_path('social-logos.wo...', Array)
#1 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1507): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_font_face_at_rule(Object(Sabberworm\CSS\RuleSet\AtRuleSet))
#2 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1350): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_css_declaration_blo in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php on line 583
[09-Jul-2020 14:41:21 UTC] PHP Fatal error:  Uncaught Error: Class 'AMPforWP\AMPVendor\WP_Error' not found in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php:583
Stack trace:
#0 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1623): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->get_validated_url_file_path('social-logos.wo...', Array)
#1 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1507): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_font_face_at_rule(Object(Sabberworm\CSS\RuleSet\AtRuleSet))
#2 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1350): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_css_declaration_blo in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php on line 583
[09-Jul-2020 11:41:23 America/Sao_Paulo] PHP Fatal error:  Uncaught Error: Class 'AMPforWP\AMPVendor\WP_Error' not found in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php:583
Stack trace:
#0 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1623): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->get_validated_url_file_path('social-logos.wo...', Array)
#1 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1507): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_font_face_at_rule(Object(Sabberworm\CSS\RuleSet\AtRuleSet))
#2 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1350): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_css_declaration_blo in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php on line 583
[09-Jul-2020 14:41:24 UTC] PHP Fatal error:  Uncaught Error: Class 'AMPforWP\AMPVendor\WP_Error' not found in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php:583
Stack trace:
#0 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1623): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->get_validated_url_file_path('social-logos.wo...', Array)
#1 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1507): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_font_face_at_rule(Object(Sabberworm\CSS\RuleSet\AtRuleSet))
#2 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1350): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_css_declaration_blo in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php on line 583
[09-Jul-2020 14:41:26 UTC] PHP Fatal error:  Uncaught Error: Class 'AMPforWP\AMPVendor\WP_Error' not found in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php:583
Stack trace:
#0 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1623): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->get_validated_url_file_path('social-logos.wo...', Array)
#1 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1507): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_font_face_at_rule(Object(Sabberworm\CSS\RuleSet\AtRuleSet))
#2 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1350): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_css_declaration_blo in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php on line 583
[09-Jul-2020 11:41:27 America/Sao_Paulo] PHP Fatal error:  Uncaught Error: Class 'AMPforWP\AMPVendor\WP_Error' not found in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php:583
Stack trace:
#0 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1623): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->get_validated_url_file_path('social-logos.wo...', Array)
#1 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1507): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_font_face_at_rule(Object(Sabberworm\CSS\RuleSet\AtRuleSet))
#2 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1350): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_css_declaration_blo in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php on line 583
[09-Jul-2020 14:41:28 UTC] PHP Fatal error:  Uncaught Error: Class 'AMPforWP\AMPVendor\WP_Error' not found in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php:583
Stack trace:
#0 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1623): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->get_validated_url_file_path('social-logos.wo...', Array)
#1 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1507): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_font_face_at_rule(Object(Sabberworm\CSS\RuleSet\AtRuleSet))
#2 /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php(1350): AMPforWP\AMPVendor\AMP_treeshaking_Style_Sanitizer->process_css_declaration_blo in /home/showmetechcom/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tree-style-sanitizer.php on line 583

**Comment by jeherve** [comment]
It appears that this was fixed in the AMP for WP plugin:
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4624

If you update to the most recent version of the plugin, the issue should go away.
