### ISSUE TITLE
Carousel: Remove "Link to" options in Gallery Settings when Carousel is enabled

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#1646]
When the Carousel module is enabled, the "Link to" options (Attachment Page / Media File / None) in the Gallery settings don't actually do anything, because the Carousel will show no matter which one is selected. To prevent user confusion, we should remove the "Link to" dropdown when Carousel is enabled, if possible.

Suggested here: https://wordpress.org/support/topic/link-to-not-removed-with-gallery-carousel

**Comment by kraftbj** [comment]
An idea/decision is allow, either by default or via a filter, those options to be visible and matter. Without looking at the code, add a default option to show in the carousel, and let the other options retain their original behavior.

Suggested in 2492177-t

**Comment by richardmtl** [comment]
Noting that the user came up with this code, which works for him as a workaround:

```add_shortcode('discarousel', '_disableCarousel');
function _disableCarousel(){
global $wp_filter;
$wp_filter['post_gallery'][1000]=null; // removes Jetpack Carousel
filters
$wp_filter['post_gallery'][-1000]=null; // removes Jetpack Carousel
filters
}```

**Comment by mrwweb** [comment]
I'd actually advocate that it remain and that "None" enable users to avoid the carousel for that particular gallery.

**Comment by samiff** [comment]
Closing in favor of: https://github.com/Automattic/jetpack/issues/11264
