### ISSUE TITLE
404: stats.wp.com called incorrectly

### ISSUE THREAD

**Issue by galbaras** [Automattic/jetpack#16487]
The tracking script is included on pages like this:

`<script async defer src='https://www.behappyinlife.com/wp-content/plugins/jetpack/https://stats.wp.com/s-202029.js'></script>`

This results in a 404 error, as one might expect.

I think the problem is that this script is enqueued using `Assets::enqueue_async_script`, which adds the plugin's URL to the script file.

**Comment by jeherve** [comment]
I would recommend updating to the most recent version of Jetpack; this issue was fixed in Jetpack 8.7.

Related PR: #16047
