### ISSUE TITLE
Modular assets files for performance improvement 

### ISSUE THREAD

**Issue by asafm7** [Automattic/jetpack#16494]
Hi,

My site uses only 4% percent of the jetpack.css file.

![image](https://user-images.githubusercontent.com/14274769/87582138-a1f02580-c6e2-11ea-9117-c27a9de4cc0e.png)

The rest 96% is loaded with no need and hurts the site performance. (Removing unused CSS is one of the main advice given to me by the Google PageSpeed tool)

Of course, I can dequeue the script and copy the relevant CSS to a custom file, but in the long run, it is hard to maintain.

I thought it is maybe possible to make the assets modular - to split them per-feature and to only load the assets relevant to the features that are enabled and in use (and later to re-combine the relevant code blocks to one file to save HTTP requests, either by Jetpack or a cache or optimization plugin). For example, I explicitly deactivated the Carousel feature, but its CSS seem to still be loaded in the jetpack.css. (If I interpret the 'jp-carousel' class correctly)

I think one of the main critiques of Jetpack is about it being bloated, and while it serves some great features you will surely use, it also serves many that you are not using and are just making your site 'heavier'. My proposed change might address this weakness.

I hope it makes any sense.

**Comment by jeherve** [comment]
Thanks for the feedback.

> I thought it is maybe possible to make the assets modular - to split them per-feature and to only load the assets relevant to the features that are enabled and in use

That's something you can activate with the following filter:

`add_filter( 'jetpack_implode_frontend_css', '__return_false', 99 );`
-- https://developer.jetpack.com/hooks/jetpack_implode_frontend_css/

> and later to re-combine the relevant code blocks to one file to save HTTP requests, either by Jetpack or a cache or optimization plugin

That's something we're tracking in #1258.

I'll close this issue in favour of the other one.
