### ISSUE TITLE
General: Improve visibility of the primary WP.com connected account from /wp-admin/

### ISSUE THREAD

**Issue by krogsgard** [Automattic/jetpack#1649]
When someone doesn't know what WordPress.com account is connected to their .org install, there is no easy way to find out within the website administrative panel. There should be. 

Even the "disconnect from WordPress.com" button just _does it_, it doesn't  go to a screen to say what you're doing. That's also troublesome, because the disconnect can cause headaches. It should be double opt-in imo and request confirmation.

**Comment by kraftbj** [comment]
@krogsgard What about via the Debug link in the footer? The page that loads has a "The primary connection is owned by xyz@example.com" line?

**Comment by krogsgard** [comment]
@kraftbj Ah, that's nice! Wish it was easier to find but that's cool. I thought I clicked all the links looking for it but I was wrong. Any way to make that a bit more clear?

**Comment by kraftbj** [comment]
Always open for improvements! Any particular ideas/thoughts on how to do that? @jeffgolenski has some beginning plans in the works to generally improve the Jetpack admin UI.

**Comment by krogsgard** [comment]
It could easily include the email address somewhere under "You're successfully connected" https://cloudup.com/ci3mvjwJMji

**Comment by jessefriedman** [comment]
What do we think of a profile button at the top of the page (1) that leads to your .com profile (2)? 

1. https://cloudup.com/iHnIkCQCjpc
2. https://cloudup.com/iaIBR23UCIF

**Comment by jeherve** [comment]
> that leads to your .com profile (2)?

That would only work when people have access to that WordPress.com profile. Other admins and users on the site don't, and in many cases the primary admin isn't connected to their WordPress.com account anymore.

I like the idea of the profile button, though. How would you display that button to other users on the site? There would have to be a difference between the existing master connection and the option to link your own account.

**Comment by jessefriedman** [comment]
Round two

https://cloudup.com/c1x5Zrxq6c5

Users who are connected will see links to their .com profile. If you are a non owner it defines that in the profile.

**Comment by krogsgard** [comment]
Would this show the owner account to the non-owner? That's part of the point, to try and figure out which account is actually connected.

**Comment by jeffgolenski** [comment]
UI changed. "My Connection" button added to header of Jetpack admin. Button opens modal listing details of said users' connection. https://github.com/Automattic/jetpack/tree/enhancement/connection-status
