### ISSUE TITLE
General: Make Disconnect double opt-in

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#1650]
Disconnecting is a single-click experience which requires a fair amount of extra work to reconnect if done accident. 

Add an AYS to the disconnect link?

(h/t @krogsgard via #1649)

**Comment by samhotchkiss** [comment]
Can we at least do this via a JS `confirm()` for now, and pretty it up in 3.5?

@jeherve @georgestephanis - do we forbid `confirm()`?

**Comment by georgestephanis** [comment]
As we're already under string freeze, can you scan for an existing string we could use, or just use a stock confirm()?

**Comment by samhotchkiss** [comment]
I can't find anything :-1: 

I'm just going to put it in, this isn't something most users are going to run across, and it'll get picked up for translation for 3.4.1
