### ISSUE TITLE
Featured Image not being passed to Pinterest

### ISSUE THREAD

**Issue by jrparks** [Automattic/jetpack#1651]
The sharedaddy module has a bug where it is not passing the media parameter to Pinterest with the featured image URL. I patched my own code however I would like you to include this in your next release.

In the sharing-sources file I changed the following line:

FROM:
$pinterest_url = esc_url_raw( 'http://pinterest.com/pin/create/button/?url=' . rawurlencode( $this->get_share_url( $post->ID ) ) . '&description=' . rawurlencode( $this->get_share_title( $post->ID ) ) );

TO:
$pinterestimage = wp_get_attachment_image_src( get_post_thumbnail_id( $post->ID ), 'full' );
$pinterest_url = esc_url_raw( 'http://pinterest.com/pin/create/button/?url=' . rawurlencode( $this->get_share_url( $post->ID ) ) . '&description=' . rawurlencode( $this->get_share_title( $post->ID ) ) . 
'&media=' . rawurlencode( $pinterestimage[0] ) );

Thank you
Jason

**Comment by jeherve** [comment]
I believe that's done on purpose, so you can select just about any image in the post for your pin.

![screen shot 2015-02-19 at 12 07 04 pm](https://cloud.githubusercontent.com/assets/426388/6265529/db305fbc-b82f-11e4-91d6-a1d26a5f99e8.png)

If we were to limit the images you could pin form the button, that would most likely make the majority of our users unhappy, so I'll close this issue as a wontfix.
