### ISSUE TITLE
Jetpack CRM

### ISSUE THREAD

**Issue by VR51** [Automattic/jetpack#16538]
This is the quickest way I know to get in touch with the Jetpack team. My apologies for using this channel to ask this question but I feel it urgent to question the product's authenticity.

Is jetpackcrm.com an Automatic product and a part of Jetpack or is this product a scam?

The site design looks similar to the standard Jetpack site design. The sales method looks Automatic like. The product logo is the same as the one used by Jetpack.

Right at the bottom of the site is the name Aut O'Mattic (not Automattic). This suggests to me this product is a scam.

![image](https://user-images.githubusercontent.com/5859901/88056333-4a294280-cb58-11ea-9d34-52a7b26920ab.png)

This product was advertised to me via an email sent from donotreply@e0.jetpack.com.

Regards,
Lee

**Comment by jeherve** [comment]
Hi!

Thanks for reaching out.

Jetpack CRM is an Automattic product, on worries there! Aut O'Mattic is an Irish subsidiary of Automattic.

You can find out more about the product on our blog here:
https://jetpack.com/2020/07/20/introducing-jetpack-crm/

**Comment by VR51** [comment]
Thanks Jeremy. Was a little worried there.

**Comment by jeherve** [comment]
I've passed on your feedback to the team working on the CRM feature; we'll see about making things clearer to avoid that kind of confusion. Thanks again for the feedback!
