### ISSUE TITLE
Content Options: Output of inline CSS without a selector

### ISSUE THREAD

**Issue by dashkevych** [Automattic/jetpack#16557]
The Content Options module outputs an inline CSS without a selector when nothing is selected to hide: 

https://github.com/Automattic/jetpack/blob/d05b9d8d286e75483b27ffe75e2ad15d5bba3be8/modules/theme-tools/content-options/post-details.php#L47

Here is an example of output using 2020 theme:

![inline CSS without a selector](https://snipboard.io/wbIX17.jpg)

The issue is possible to resolve by checking for an empty array before adding any custom CSS:

```php
if ( empty( $elements ) ) {
 return;
}
```

This check should be added before the following lines:

https://github.com/Automattic/jetpack/blob/d05b9d8d286e75483b27ffe75e2ad15d5bba3be8/modules/theme-tools/content-options/post-details.php#L42-L44

**Comment by avlisesac** [comment]
I'll work on this issue!

**Comment by avlisesac** [comment]
pull request created: https://github.com/Automattic/jetpack/pull/16572

**Comment by dashkevych** [comment]
Do know in which version of Jetpack this fix will be included?
