### ISSUE TITLE
General: Deactivating of WP-Stats prevents the site from working correctly

### ISSUE THREAD

**Issue by patschi** [Automattic/jetpack#1655]
It seems that deactivating the WP-stats plugin of Jetpack does corrupt the wordpress site, because some elements on the site didn't load correctly anymore. When I re-activated the plugin, the site was working well again as before. While WP-stats was deactivated, the following error appeared each visit on website in the apache2 error log:
<pre>[Thu Feb 19 13:58:12 2015] [error] [client X.X.X.X] PHP Fatal error:  Call to undefined function stats_get_csv() in /var/www/htdocs/wp-content/plugins/jetpack-popular-posts/jetpack-popular-posts.php on line 235</pre>

Activated plugins:
![2015-02-19_141205-ghcva](https://cloud.githubusercontent.com/assets/2029878/6267084/53060b02-b841-11e4-98ee-4889485ecccb.png)

**Comment by georgestephanis** [comment]
Yes, the Jetpack Popular Posts third-party plugin is indeed dependent on the Stats being module being active.

https://wordpress.org/plugins/jetpack-popular-posts/

Unfortunately, it's a third-party module, we have no control over the quality or content of its code.  But if you just disable that plugin on your install, you should be able to safely disable the Stats module.

**Comment by patschi** [comment]
I just read "/plugins/jetpack-*"... Sorry! Didn't even knew that someone installed this plugin. Sorry for disturbing you with this!
