### ISSUE TITLE
Publicize: Japanese body text is not trimmed for Facebook post

### ISSUE THREAD

**Issue by naokomc** [Automattic/jetpack#1656]
When you publicize a Japanese post (without manually inserted excerpt) to Facebook, full body text is attached to the Publicized item.

![facebook-publicize](https://cloud.githubusercontent.com/assets/34067/6267481/d05d22fc-b887-11e4-8c2b-1d4fb25ded2b.png)

The above post has 809 characters according to the WordPress editor screen. The whole post content minus the image is shown on Facebook.

Steps to reproduce:
1. Create a long post with Japanese content (e.g. copy text from http://ja.wikipedia.org/)
2. Publicize it to Facebook

**Comment by kevmarsden** [comment]
Reported by another Japanese user in 2571240-t

**Comment by naokomc** [comment]
This is only happening on Calypso. Moved to https://github.com/Automattic/wp-calypso/issues/4150 after talking to @eliorivero
