### ISSUE TITLE
(8P) Google Photos: add account disconnect link in the media browser

### ISSUE THREAD

**Issue by johngodley** [Automattic/jetpack#16560]
Currently the only way to disconnect a Google Photos account from the external media feature is to go to My Site > Tools > Marketing on WordPress.com. This isn't the most obvious thing to do.

The Google Photos team have requested a disconnect link to be added somewhere in the media browser itself. This could either be in the modal title bar, or in the photo filters toolbar.

![image](https://user-images.githubusercontent.com/1277682/88271308-dd848400-ccce-11ea-8489-1634e51365e4.png)

Note that there are UX guidelines around account disconnection:

https://developers.google.com/photos/library/guides/ux-guidelines

**Comment by davemart-in** [comment]
I removed this from the Manage backlog. @obenland can you please add this as an option for your maintenance cycle? Thanks!
