### ISSUE TITLE
{Feature Request} Contact form : Submit button Allignment + Customisation

### ISSUE THREAD

**Issue by anmol257** [Automattic/jetpack#16609]
#### Is your feature request related to a problem? Please describe.
It needs flexible so that it can be tailored to suit website needs.

#### Describe the solution you'd like
Heading is sufficient

#### Describe alternatives you've considered
Tried other form plugins but none have this feature.

#### Additional context
Other forms have many new features like captcha etc which the jetpack lags. It would be great to transform it with respect to present times.

**Comment by jeherve** [comment]
Could you give us more details about the features you'd be looking for? We've recently updated the form's submit button to be more customizable, so you can change its alignment, main style, colors, borders:

![image](https://user-images.githubusercontent.com/426388/88649850-81ec3900-d0c8-11ea-8fa3-e59f570c5de2.png)

Were you looking for different / additional options?

> Other forms have many new features like captcha etc which the jetpack lags

If you'd like to add a Captcha feature to a Jetpack contact form, I would recommend using this plugin:
https://github.com/DevriX/jetpack-recaptcha

It's worth noting, however, that if you use the Akismet plugin on your site, you won't need to add a captcha to Jetpack's contact form; the Akismet plugin will automatically scan each form submission and filter spam for you.

**Comment by anmol257** [comment]
> 
> 
> Could you give us more details about the features you'd be looking for? We've recently updated the form's submit button to be more customizable, so you can change its alignment, main style, colors, borders:
> 
> ![image](https://user-images.githubusercontent.com/426388/88649850-81ec3900-d0c8-11ea-8fa3-e59f570c5de2.png)
> 
> Were you looking for different / additional options?
> 
> > Other forms have many new features like captcha etc which the jetpack lags
> 
> If you'd like to add a Captcha feature to a Jetpack contact form, I would recommend using this plugin:
> https://github.com/DevriX/jetpack-recaptcha
> 
> It's worth noting, however, that if you use the Akismet plugin on your site, you won't need to add a captcha to Jetpack's contact form; the Akismet plugin will automatically scan each form submission and filter spam for you.

Need the option to "align centre"

**Comment by anmol257** [comment]
As for the other features, you can check out the "WP forms" plugin.
*The ability to have it aligned with respect to other buttons on the page.{For reference u can check out my website [www.inspiredbyanmol.com]](url)
*Captcha

**Comment by jeherve** [comment]
> Need the option to "align centre"

That makes sense, thank. Tracking this in #16610 

> The ability to have it aligned with respect to other buttons on the page.{For reference u can check out my website (www.inspiredbyanmol.com)

Could you clarify what you'd like to see a bit more?

Thank you!

**Comment by anmol257** [comment]
@jeherve 
Following are some of the features which would make jetpack forms great:

**

- **Smart Form Confirmation** – Show a custom success message, or redirect users to a custom thank you page.

- **Custom Captchas** – Create custom captchas for your contact form.

- **Layout customisation of form** - It can have the ability to add a picture or to make it transparent rather than opaque.

- **2 in1 form**: The form can have a tab feature on top(like a browser of a laptop) with the left side being contact & right feedback(Submit testimonials).It would be very user friendly as well as have an aesthetic appeal.

- **For submitting Testimonials**: A way to verify it like an option of uploading pictures and attaching social media handles. This feature would make sure testimonials published are genuine.

etc.

**Comment by anmol257** [comment]
> 
> 
> > Need the option to "align centre"
> 
> That makes sense, thank. Tracking this in #16610 

It would be great if you could let me know as soon as this option is included so that I can update my website accordingly.

**Comment by anmol257** [comment]
> It's worth noting, however, that if you use the Akismet plugin on your site, you won't need to add a captcha to Jetpack's contact form; the Akismet plugin will automatically scan each form submission and filter spam for you.

**Askminet** is not 100% accurate as it sometimes even flags genuine comments as spam.

**Comment by jeherve** [comment]
> Smart Form Confirmation – Show a custom success message, or redirect users to a custom thank you page.

This is already available in Jetpack contact forms. Check the block sidebar to find those options.

> Custom Captchas – Create custom captchas for your contact form.

As I mentioned above, you'll need to use a third-party plugin to add that option.

> Layout customisation of form - It can have the ability to add a picture or to make it transparent rather than opaque.

You can add your own image block inside each form. If you'd like to add an image as the background of the form, I would recommend using CSS to customize the form to fit your needs. That's probably not an option we'd add to the form settings.

> 2 in1 form: The form can have a tab feature on top(like a browser of a laptop) with the left side being contact & right feedback(Submit testimonials).It would be very user friendly as well as have an aesthetic appeal.

I would recommend combining different blocks to get to something like this. You can combine column blocks from WordPress itself, tab blocks provided by other block plugins, and Jetpack blocks to reach the look you need.

> For submitting Testimonials: A way to verify it like an option of uploading pictures and attaching social media handles. This feature would make sure testimonials published are genuine.

That's most likely not something we'll implement in the near future. You can follow the conversation here to find out more:
https://github.com/Automattic/jetpack/issues/450

> It would be great if you could let me know as soon as this option is included so that I can update my website accordingly.

I would recommend hitting the "Subscribe" button appearing in the sidebar of that issue; you'll then receive notifications when there are updates on that topic.

> Akismet is not 100% accurate as it sometimes even flags genuine comments as spam.

If you experience such issues, I would recommend the following:

1. Mark such comments / form submissions as non-spam to help Akismet learn so it doesn't do the same mistake again.
2. If it keeps happening, you can contact the Akismet team here to let them know:
https://akismet.com/contact/

I will now close this issue since we've split the tasks into a different issue.

**Comment by anmol257** [comment]
@jeherve can you please suggest me the 3rd party plugin you refered above to add captchas to jetpack form?

**Comment by jeherve** [comment]
See my comment here:
https://github.com/Automattic/jetpack/issues/16609#issuecomment-664944113

**Comment by anmol257** [comment]
Thanks a ton for your help buddy.
& take care.
