### ISSUE TITLE
Grunion: New prefixed field labels break back-compat

### ISSUE THREAD

**Issue by iandunn** [Automattic/jetpack#1661]
The new unique indexes that are prefixed to form labels break backwards compatibility with plugins using the `grunion_pre_message_sent` hook, since the data used to be passed without prefixes.

Commit:  334a713
PR: #652
Issue: #145

That commit breaks things like [the wordcamp-forms-to-drafts](https://meta.trac.wordpress.org/browser/sites/trunk/wordcamp.org/public_html/wp-content/plugins/wordcamp-forms-to-drafts/wordcamp-forms-to-drafts.php?rev=698#L128) plugin, because it relies on the old behavior where the indexes matched the field names. (That's probably not the best example, since it's a hacky prototype, but it at least demonstrates the broken compatibility.)

The possibility of breaking back-compat was [touched on](https://github.com/Automattic/jetpack/pull/652#issuecomment-45153731) in #652, but it doesn't seem like the solution was ever implemented before the PR was merged.

I realize this might be a `wontfix` since it's been more than 6 months and nobody else has mentioned it, but I thought i'd at least get the issue documented and discussed. I'm happy to update my plugin to handle the prefixes if you guys decide to continue passing them to the hook.

cc @rase-

**Comment by georgestephanis** [comment]
If there's a way to support backcompat without being incredibly ugly and troublesome, I'm totally fine with getting it implemented.  But yeah -- you're the first issue we've heard about on the case.

**Comment by dereksmart** [comment]
Closing as wontfix, since it seems to be the only reported issue since the commit in 14 months
