### ISSUE TITLE
(13P) Social Previews: Configure server-side plan checks

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/jetpack#16616]
This will build on top of #16196 & #16195. 

We need to figure out how to add plan checks for the feature. The standard plan check won't work for us because it completely hides the feature but we actually want it to be visible, just show the "upgrade needed" version.

#### Plan requirement for Social Previews
- free for all Jetpack sites
- requires Business/eCommerce plan on simple and atomic

#### Sidebar design
<img width="1440" alt="02A" src="https://user-images.githubusercontent.com/67021691/88414075-48ef5400-cdaa-11ea-8a47-aaffe9453b12.png">

#### Modal design

<img src="https://user-images.githubusercontent.com/67021691/88414417-cd41d700-cdaa-11ea-8316-761509e15deb.png" />

**Comment by marekhrabe** [comment]
The old implementation in Calypso used to have a different wording for people who can upgrade and for those who don't have sufficient permissions: https://github.com/Automattic/wp-calypso/pull/41194

We should probably do the same check

**Comment by getdave** [comment]
Starting some research here. Looks like we should look at the following files:

- `_inc/client/lib/plans/constants.js`

**Comment by getdave** [comment]
## Researcg

Some research - updating as I go.

**Comment by retrofox** [comment]
> * how do we get the slug of the current plan?

I've seen that he plan slug is hardcoded in the code. [Here](https://github.com/Automattic/jetpack/blob/master/modules/simple-payments/simple-payments.php#L28) for Payments blocks, and [here](https://github.com/Automattic/jetpack/blob/master/extensions/blocks/videopress/editor.js#L166) for videopress.

**Comment by retrofox** [comment]
> * `const plan = select( 'wordpress-com/plans' ).getPlan( planName );` will return the info about that plan.

https://github.com/Automattic/jetpack/edit/feature/premium-blocks/extensions/shared/premium-blocks/upgrade-plan-banner.jsx?pr=%2FAutomattic%2Fjetpack%2Fpull%2F16611 is how the upgrade banner gets the current site plan.

Something like the following:

```es6
import { useSelect } from '@wordpress/data';


const MyComponent = () => {
	const plan = useSelect( select => {
		const PLAN_SLUG = 'value_bundle';
		return select( 'wordpress-com/plans' ).getPlan( PLAN_SLUG );
	} )

	return (
		//...
	);
}
```

**Comment by retrofox** [comment]
Also do not forget to load the plan store, it's located here https://github.com/Automattic/jetpack/blob/master/extensions/shared/components/upgrade-nudge/store.js

**Comment by marekhrabe** [comment]
Documenting my recomendations from Slack here:

based on `Jetpack_Editor_Initial_State.available_blocks['social-previews']`, Jetpack frontend decides if it runs you code or not that you register. like here we register ours:

https://github.com/Automattic/jetpack/blob/master/extensions/blocks/social-previews/editor.js#L7

If the block is available, then your plugin is executed and if not, your code will not be run. What I'm thinking is that in the `social-previews/editor.js`, we could add our own check for `Jetpack_Editor_Initial_State.available_blocks['social-previews']` and if it is NOT available, register our own separate plugin directly with Gutenberg (so it skips plan checks) via `require('@wordpress/plugins').registerPlugin`. This second "fallback" plugin will show the upgrade UI using the Slot/Fill for the Jetpack sidebar

We will also need to update the plan definitions so `social-previews` are listed where they need to be (all Jetpack plans, incl. free + some selected wpcom plans). Since we'll be available in Jetpack under any circumstance, upgrade nudges will only ever be visible on simple and atomic sites with insufficient plan.

**Comment by getdave** [comment]
> We will also need to update the plan definitions so social-previews are listed where they need to be (all Jetpack plans, incl. free + some selected wpcom plans). Since we'll be available in Jetpack under any circumstance, upgrade nudges will only ever be visible on simple and atomic sites with insufficient plan.

This is the bit where I'm not 100% on how we do it.

**Comment by retrofox** [comment]
> > We will also need to update the plan definitions so social-previews are listed where they need to be (all Jetpack plans, incl. free + some selected wpcom plans). Since we'll be available in Jetpack under any circumstance, upgrade nudges will only ever be visible on simple and atomic sites with insufficient plan.
> 
> This is the bit where I'm not 100% on how we do it.

I think it's doable in the `Jetpack_Plan` class, [here](https://github.com/Automattic/jetpack/blob/733b4609c095aabe8ea140a67245b0d6c8562358/class.jetpack-plan.php#L16).

**Comment by marekhrabe** [comment]
Yeah, we are already there for jetpack free plan: 

https://github.com/Automattic/jetpack/blob/733b4609c095aabe8ea140a67245b0d6c8562358/class.jetpack-plan.php#L35

We might just need to figure out where exactly add our plugin - probably to those selected paid plans too? It will probably be super easy for somebody who has been settings other paid features. Maybe we can blame the file and ping them :)

**Comment by getdave** [comment]
Have a look at D43206-code.

**Comment by getdave** [comment]
Following up here with D47637-code which tries to gate the feature for Dotcom only. No luck. I assume this is due to us having the plan marked as available in all Jetpack Plans within the [Jetpack_Plan class](https://github.com/Automattic/jetpack/blob/733b4609c095aabe8ea140a67245b0d6c8562358/class.jetpack-plan.php#L35).

**Comment by pablinos** [comment]
You might want to look into using this [`set_availability_for_plan`](https://github.com/Automattic/jetpack/blob/master/class.jetpack-gutenberg.php#L1083) for setting the availability of the extension. It will look at Jetpack_Plan for Jetpack sites and the Store_Product_List for wpcom. 

As this is designed for blocks you might have to adapt things a bit. You can see [in `register_jetpack_block`](https://github.com/Automattic/jetpack/blob/master/class.jetpack-gutenberg.php#L52) that we hook in a call to the method when block registration happens. Reading through this issue, Social Previews isn't your average block, so this might not be appropriate, but you could hook in at the same point, just so that availability is set at the correct point of the lifecycle.

**Comment by getdave** [comment]
Reopening as we still need to handle the server side code for gating.

**Comment by marekhrabe** [comment]
I have renamed this issue to reflect the remainder of the work left.

**Comment by obenland** [comment]
Is this ticket what D48017-code tries to solve?

**Comment by getdave** [comment]
Yes. All done 🥳
