### ISSUE TITLE
Cookies and Consents Banner (Jetpack) Widget: Javascript error

### ISSUE THREAD

**Issue by DarknessFX** [Automattic/jetpack#16625]
Problem:
On Cookies and Consents Banner (Jetpack) if you set Capture consent & hide the banner to 30 seconds, if the user already had approved the cookie after 30 seconds javascript throws an error (on DevTools Console).

Error:
Uncaught TypeError: Cannot read property ‘removeChild’ of null
at eu-cookie-law.min.js?ver=20180522:2

Script:
function(){n.parentNode.removeChild(n);…

Why it happens?
The widget know it didn't have to create the banner but "Capture consent & hide the banner" timer is still active and tries to remove the never created banner.

Fix (not ideal, but it works for now):
Edit /wp-content/plugins/jetpack/_inc/build/widgets/eu-cookie-law/eu-cookie-law.min.js
Column 1391
Replace:
n.parentNode.removeChild(n)
With:
try {n.parentNode.removeChild(n)} catch (error) {}

How to replicate this error:
Open WordPress Admin Dashboard.
Go to Appearance > Widgets.
Add Cookies & Consents Banner (Jetpack) to your primary sidebar.
Set Capture consent & hide the banner to After this amount of time 30 seconds.
Save.
Visit your WP page (maybe using an European VPN?).
The Cookies and Consent banner shows up, click Agree.
Open your browser DevTool, check Console outputs. No errors.
Press F5 (Refresh).
The widget knows you already consent, so it don’t display the banner again.
Wait 30 seconds.
This error shows up.

**Comment by FireEmerald** [comment]
I can confirm that the issue still exists in jetpack 8.9.1 under wordpress 5.5.1.
