### ISSUE TITLE
Business Hours Block: add 24h time option

### ISSUE THREAD

**Issue by csonnek** [Automattic/jetpack#16622]
#### Is your feature request related to a problem? Please describe.

Currently, the Business Hours Block only allows for a 12h (AM/PM) time format input: 

![hoursblock](https://user-images.githubusercontent.com/2814452/88708629-8ff68580-d0d9-11ea-8649-bccd19adb820.jpg)

While you can enter time in 24h (e.g. entering `17:00` as the closing time will automatically convert to `05:00 PM`), it will still display in a 12h time format. As most countries in the world use the 24h format for time, it would be nice to have the option to display hours in the site owner's preferred time format

#### Describe the solution you'd like

Add an option or a toggle to display the times in either a 12h or 24h format.

**Comment by jeherve** [comment]
If you'd like to display times in a 24h format on your WordPress site, I would recommend changing the option under Settings > General:

![image](https://user-images.githubusercontent.com/426388/88789567-2ccb2880-d197-11ea-84d7-9c21636f3d45.png)

The Business Hours block will respect this option:

<img width="899" alt="screenshot 2020-07-29 at 12 28 58" src="https://user-images.githubusercontent.com/426388/88789606-3c4a7180-d197-11ea-8780-e8a043163ece.png">
<img width="767" alt="screenshot 2020-07-29 at 12 28 48" src="https://user-images.githubusercontent.com/426388/88789618-3e143500-d197-11ea-8a0f-151383045268.png">

**Comment by csonnek** [comment]
TIL - thanks @jeherve
