### ISSUE TITLE
(8P) Premium Blocks: Replace (paid) label with upgrade indicator

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#16628]
Let's replace the `(paid)` label with a star indicator in every premium block's icon. This task does not include adding the contextual tip shown in the screenshot.
We might need to add block-specific CSS to position the star correctly in each icon.

This might require changes in both Jetpack and FSE plugin.

#### Screenshot
<img alt="image-2020-07-07-at-9 27 22-pm" src="https://user-images.githubusercontent.com/1398304/87077984-d478ba80-c1d8-11ea-9b41-12396c5f4258.png">

#### Prior art:
* [Premium Content](https://github.com/Automattic/wp-calypso/blob/0797cbc29f1391948b965ea05691717f691b8110/apps/full-site-editing/full-site-editing-plugin/premium-content/index.js#L80-L97)
* [Donations block](https://github.com/Automattic/wp-calypso/blob/197353ce969331626ba9b46f9d180cb215b2cbc4/apps/full-site-editing/full-site-editing-plugin/donations/index.js#L107-L137)
* https://github.com/Automattic/jetpack/pull/14739

Example for star usage: [Donation Block](https://github.com/Automattic/wp-calypso/blob/39ed68c25110278412f8dfa753e99562dd84beab/apps/full-site-editing/full-site-editing-plugin/donations/stripe-nudge.js#L31)

See 123-gh-dotcom-manage

**Comment by cpapazoglou** [comment]
Current Issue covers jetpack blocks, we have 2 more pending issues for FSE and WPcom:
https://github.com/Automattic/wp-calypso/issues/44524
https://github.com/Automattic/wp-calypso/issues/44352
