### ISSUE TITLE
WordAds Settings: Empty settings section on subdir sites

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#16647]
#### Steps to reproduce the issue

1. Visit `wp-admin/admin.php?page=jetpack#/traffic` on subdir site
2. Make sure WordAds is enabled
3. Note that 3d section (which should be `Customize your ads.txt file`) is empty, but the section is still visible

**Screenshots**
<img width="738" alt="screen-shot-2020-07-29-at-12 11 22-pm" src="https://user-images.githubusercontent.com/5654161/88929141-662c9280-d282-11ea-95da-0e6f19072983.png">

**Comment by jeherve** [comment]
This seems to be done on purpose:

> On a site WP install utilizing a subdirectory (e.g. www.site.com/foo/wp-admin) check that the ads.txt portion is removed, as ads.txt requires by definition not to run under a subdirectory.
-- https://github.com/Automattic/jetpack/pull/9996

@dbspringer Do you know if this is still the case?

**Comment by dbspringer** [comment]
Yes, this is still true. The ads.txt file must be placed under the root domain and not a subdomain or subdirectory.

**Comment by brbrr** [comment]
> This seems to be done on purpose:

Yup, I'm not saying we should show it for subdir sites. This issue is about _how_ we are hiding that section in this case:
https://github.com/Automattic/jetpack/blob/master/_inc/client/traffic/ads.jsx#L335-L402

as you can see from the above, `isSubDirSite` check is used only for child components of the section, I think we should just hide the whole section behind `isSubDirSite` check
