### ISSUE TITLE
JP Dashboard: Email wrapping in "Account connection" card

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#16641]
#### Steps to reproduce the issue

1. Go to /wp-admin/admin.php?page=jetpack#/dashboard
2. Scroll down to "Account connection" card
3. Tweak email to be long enough (> 27 chars)
4. See that email is wrapped to the second line

#### What happened instead

<img width="568" alt="Jetpack ‹ jetpack6test mystagingwebsite com at Pressable — WordPress 2020-07-30 10-30-40" src="https://user-images.githubusercontent.com/5654161/88894055-f998a000-d24f-11ea-9ee9-8e1f7a8d2c90.png">

**Comment by crunnells** [comment]
I'm working on a PR for this right now.
