### ISSUE TITLE
Payments: Bold does not change button's font-weight

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#16650]
#### Steps to reproduce the issue

1. Start new post and add a Payments block
2. Add text to the button, and make it bold
3. See that font-weight have not changed

**Screenshots**

<img width="287" alt="screen-shot-2020-07-29-at-11 02 40-am" src="https://user-images.githubusercontent.com/5654161/88938492-1e136d00-d28e-11ea-8873-ea90f6a4e00e.png">

**Comment by Copons** [comment]
Not applicable anymore — although some themes will define button labels with a bold font-weight by default, which overrides the block's inline controls.
