### ISSUE TITLE
Increase priority for `editor.MediaUpload` filter

### ISSUE THREAD

**Issue by ravichdev** [Automattic/jetpack#16668]
#### Is your feature request related to a problem? Please describe.
The `editor.MediaUpload` [hook](https://github.com/Automattic/jetpack/blob/master/extensions/shared/external-media/index.js#L32-L60) replaces the "Media Library" to add support for selecting external media. The filter callback uses an HOC to return a new component, this prevents plugins hooking into the filter with a higher priority to override the original `MediaUpload` [component](https://github.com/WordPress/gutenberg/blob/master/packages/media-utils/src/components/media-upload/index.js#L227).

#### Describe the solution you'd like
The priority of `11` should be increased to a bigger number like 50 or 100 so the plugin's HOC updates the `render` method as late as possible and allows plugins to update/replace the original component.

**Comment by jeherve** [comment]
Thanks for reaching out!

> allows plugins to update/replace the original component.

Could you tell us more? Is our current implementation breaking another plugin / implementation by hooking in too early?

**Comment by ravichdev** [comment]
Thank you for the quick response!

AMP plugin hooks into the `editor.MediaUpload` [filter](https://github.com/ampproject/amp-wp/blob/develop/assets/src/block-editor/index.js#L35) to add some custom notices when selecting images. It uses the default priority of `10` and the Jetpack's filter with priority `11` works well with the AMP component changes. The problem is when we want to extend or modify the component returned by the AMP filter, because it uses `10` and Jetpack uses `11` we need to use one of these priorities and ensure our filter is loaded either before the Jetpack filter or after the AMP filter (depending on the priority).

Increasing Jetpack's priority to a big number like `100` would solve this issue and lets other plugins make changes to the `MediaUpload` component.
