### ISSUE TITLE
The Carousel is not displayed correctly on IE if the language direction is RTL

### ISSUE THREAD

**Issue by duduik** [Automattic/jetpack#1667]
Incorrect next and previous image position. There is no image on the previous link. The previous image is displayed on the next link instead, the image is displayed too big and sometimes it covers the main image.

It works on Chrome 40, Firefox 35, Opera 27 and IE 8 (no previous and next images). 
It doesn't work on IE11, IE10 and IE9.

Steps to reproduce:
1. Use an RTL language. Or use RTL Tester plugin to change the direction to RTL.
2. Write a post with a gallery.
3. View it in IE11, IE10 or IE9. 

Expected behavior (screenshot from Firefox):
![jpcrs-ff](https://cloud.githubusercontent.com/assets/5810623/6324488/2c875a7e-bb6d-11e4-876d-9ea005f32f2d.jpg)

Actual behavior (screenshot from IE11):
![jpcrs-ie](https://cloud.githubusercontent.com/assets/5810623/6324499/4d16b87a-bb6d-11e4-9341-b8e8b1f3a3c2.jpg)

WordPress 4.1.1
Theme Twenty Fifteen 1.0
Jetpack 3.3.2

**Comment by kraftbj** [comment]
We will be deprecating IE 11 support this summer and thus are wontfix'ing IE 11 issues now. See p1HpG7-c8n-p2
