### ISSUE TITLE
Infinite Scroll Displaying the wrong number of posts

### ISSUE THREAD

**Issue by BinaryMoon** [Automattic/jetpack#16686]
Hi - I sell themes on wordpress.com and recently I have had a number of users complain that the number of posts on the homepage has changed.

You can see the support requests here:
https://premium-themes.forums.wordpress.com/topic/the-section-latest-shows-more-posts-than-it-should/
https://premium-themes.forums.wordpress.com/topic/front-page-keeps-showing-articles-that-are-not-sticky/
https://premium-themes.forums.wordpress.com/topic/homepage-latest-posts-2/

I don't know if you have access to see this but there's also a support ticket from the theme team here:
https://premium-review-trac.wordpress.com/ticket/7368

The issue seems to be with the `posts_per_page` property in the infinite scroll settings. The number of posts seems to always be used in all situations, however I think it should only be used when the infinite scroll type is set to `scroll`. I use the value to make the number of posts displayed larger than the height of the page. If it's shorter then the IS does not trigger. If the type is set to `click` then this is not needed.

I don't know what the old behaviour was but this is how I believe it should work.

**Comment by jeherve** [comment]
Thanks for the extra details. That's most likely the same issue as in #16471. I'll close this issue now, and we can keep tracking the problem in the other issue.
