### ISSUE TITLE
JITM: Call-to-action button incorrectly escaped

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#16697]
There was a report in /p9F6qB-5FA-p2 about an a CTA button that had incorrectly escaped characters in it.

#### Steps to reproduce the issue

1. Switch Jetpack site to French
2. Go to stats page
3. Ensure that Jetpack Search JITM displays
4. See escaped character

#### What I expected

For the html entity to not be escaped

#### What happened instead

The html entity was escaped

**Screenshots**

<img width="704" alt="screen-shot-2020-08-03-at-11 18 56-am" src="https://user-images.githubusercontent.com/1126811/89221601-28d54700-d599-11ea-9591-8b5990b4eb27.png">

**Comment by jeherve** [comment]
It seems it was a translation issue. I fixed it [here](https://translate.wordpress.com/projects/wpcom/fr/default/?filters%5Bterm%5D=Plus+d%26rsquo%3Binfo.&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc).
