### ISSUE TITLE
Social Previews: Sidebar design iteration

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/jetpack#16701]
With the first implementation of the sidebar UI in #16633, we've discover some issues that come from using existing established components and patterns to translate the design to code. 

| Normal style | With focused button (explains the misalignment) |
| - | -
| <img width="300" src="https://user-images.githubusercontent.com/156676/89185865-38ee2600-d59b-11ea-8e99-8bafb0358205.png" /> | <img width="285" alt="Screenshot 2020-08-04 at 12 19 57" src="https://user-images.githubusercontent.com/156676/89283137-ee2ce680-d64c-11ea-8886-715bee70d937.png">

Issues identified in dev and review:

- The "Preview" button not being very noticable as a small blue link. Also difficult to align properly (because under the hood it needs to be the `Button` component and it comes with some padding. 
  - Suggestion: Would it be okay to swich the preview button to use the `secondary` style? demo https://wordpress.github.io/gutenberg/?path=/story/components-button--secondary
- Social service icons are single color, as we are reusing `@automattic/social-icons` and those don't have multi-colored variants. Since our first three supported services all use close but different shade of blue as their primary color, I think they look a bit strange.
  - Suggestion: Would it be okay to switch them all to the same neutral grayscale color in this sidebar? 

What do you think about these, @sfougnier? Thanks!

**Comment by sfougnier** [comment]
@marekhrabe I agree, this makes sense. Yes, let's go ahead and change to the secondary button style and the icons to grayscale. I did a quick mock of it below to test.

<img width="1440" alt="02D" src="https://user-images.githubusercontent.com/67021691/89302405-c764b500-d638-11ea-9c23-3101374a2a44.png">
