### ISSUE TITLE
Replace Jetpack user token with blog token by module

### ISSUE THREAD

**Issue by fgiannar** [Automattic/jetpack#16709]
A list of modules that use the Jetpack user token.

Checking a module, means that the user token has been replaced with the blog token OR has been audited, and deemed user is required for this feature.

**Before checking off, please make sure to add context. i.e. "Requires user connection" or "moved to blog token in #PR_NUM"**

### Modules using the user token.

- [x] stats (@leogermani)
https://github.com/Automattic/jetpack/blob/master/modules/stats.php#L674 - #16727 and D47631-code (changed to blog token)
https://github.com/Automattic/jetpack/blob/master/modules/stats.php#L898 - #16698 (changed to blog token)
https://github.com/Automattic/jetpack/blob/master/modules/stats.php#L1312 - #16727 and D47631-code (changed to blog token)
https://github.com/Automattic/jetpack/blob/master/modules/stats.php#L1567 - #16716 and D47584-code (changed to blog token)

- [x] subscriptions (@leogermani)
Both changed to blog token
https://github.com/Automattic/jetpack/blob/master/modules/subscriptions/views.php#L564. - see #16635
https://github.com/Automattic/jetpack/blob/master/modules/subscriptions.php#L549 - see #16692

- [x] post-by-email (@sergeymitr)
Requires user connection, email addresses are generated on per-user basis.
https://github.com/Automattic/jetpack/blob/master/modules/post-by-email/class-jetpack-post-by-email.php#L161
https://github.com/Automattic/jetpack/blob/master/modules/post-by-email/class-jetpack-post-by-email.php#L216
https://github.com/Automattic/jetpack/blob/master/modules/post-by-email/class-jetpack-post-by-email.php#L228
https://github.com/Automattic/jetpack/blob/master/modules/post-by-email/class-jetpack-post-by-email.php#L240

- [X] monitor (@sergeymitr)
PR #16736 (Merged)
~https://github.com/Automattic/jetpack/blob/master/modules/monitor.php#L38~ (deprecated)
~https://github.com/Automattic/jetpack/blob/master/modules/monitor.php#L46~ (user ID is required to subscribe to notifications)
~https://github.com/Automattic/jetpack/blob/master/modules/monitor.php#L75~ (user ID is required to check if the user is subscribed)
~https://github.com/Automattic/jetpack/blob/master/modules/monitor.php#L92~ (deprecated)
~https://github.com/Automattic/jetpack/blob/master/modules/monitor.php#L105~ (deprecated)
~https://github.com/Automattic/jetpack/blob/master/modules/monitor.php#L124~ (`user_token` is replaced with `blog_token`)

- [X] protect (@sergeymitr)
PR #16758 (Merged)
https://github.com/Automattic/jetpack/blob/master/modules/protect.php#L252

- [X] sso (@sergeymitr)
PR #16830 (Merged)
PR #16915 (Merged)
~https://github.com/Automattic/jetpack/blob/master/modules/sso.php#L622~ (user ID is required)
~https://github.com/Automattic/jetpack/blob/master/modules/sso.php#L645~ (cleaned up)
~https://github.com/Automattic/jetpack/blob/master/modules/sso.php#L676~ (cleaned up)

- [x] masterbar (Requires user auth)
https://github.com/Automattic/jetpack/blob/master/modules/masterbar/masterbar.php#L197

- [X] videopress (@sergeymitr)
We need user ID in there. Found a bug though (PR #16869, merged).
_Note that those are incoming requests to the remote Jetpack site._
https://github.com/Automattic/jetpack/blob/master/modules/videopress/class.videopress-xmlrpc.php#L44 
 
### Other foundational things that need audit (non-modules)
- [x] Sync

- [x] (@leogermani) Fetch Site options - https://github.com/Automattic/jetpack/pull/16634 (needs testing)

**Comment by leogermani** [comment]
Closing this issue in favor of p1HpG7-a4a-p2 and https://github.com/Automattic/jetpack/issues/17379
