### ISSUE TITLE
Slideshow: double left and right slideshow arrows appearing on WordPress.com Simple sites

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack#16719]
I noticed today that the left and right slideshow arrows are doubling up suddenly:

<img width="888" alt="Screen Shot 2020-08-03 at 1 47 16 PM" src="https://user-images.githubusercontent.com/437258/89212375-53bb9d00-d591-11ea-8de3-9a95db966cdd.png">

I'm not sure where each set is coming from or why they are doubled.

**Comment by simison** [comment]
There are few breaking changes mentioned in 5.x and 6.x in the changelog: https://github.com/nolimits4web/swiper/blob/master/CHANGELOG.md

Would be good to check if e.g. color-varible changes affect us, in case we were overriding any defaults.

**Comment by brbrr** [comment]
I wasn't been able to reproduce it in the Jetpack site. It seems like WPCOM specific.

**Comment by jeherve** [comment]
I cannot seem to reproduce in Jetpack right now, even when using the Gutenberg plugin; this only seems to be an issue on WordPress.com.

I wonder if this may be a by-product of how our build tools work on WordPress.com; files are never removed by the TeamCity task that updates the build artifacts, so we keep old files around forever.

I've created D47600-code to fix things up a bit, but that's not solving our issue here (and I think we may have to update the way we do things so we don't have to clean up like this).

Looking at the build artifacts, on WordPress.com I see things like this:
```css
.swiper-button-prev:after, .swiper-container-rtl .swiper-button-next:after {
    content: "prev";
}
```

But I don't see that in Jetpack build artifacts.

Still looking.

**Comment by simison** [comment]
Does the swiper bundle on .com get hash or is it without hash? If without, it could be cache issue with older version of CSS sticking in cache and newer version of markup.

**Comment by jeherve** [comment]
> Does the swiper bundle on .com get hash or is it without hash?

With the hash (and the correct one, from what I can tell).

**Comment by brbrr** [comment]
I wonder if these path updates will generate different bundles:

https://github.com/Automattic/jetpack/pull/16587/files#diff-b41e2b8aacf8404d14a7d9dbf5e413b9L43-R46

**Comment by simison** [comment]
I don't have much knowledge on Webpack dynamic imports... reaching out to Team Calypso might help since they're our Webpack experts.

https://webpack.js.org/api/module-methods/#import-1

**Comment by JoshuaGoode** [comment]
Encountered on 23163569-hc

**Comment by samiff** [comment]
I ran into this, and an issue with the `Fade` transition effect making it so the images don't transition correctly:

https://github.com/Automattic/wp-calypso/issues/44723

**Comment by joweber123** [comment]
Another report here 3202279-zen

**Comment by simison** [comment]
@kraftbj would it be possible to revert back to previous version of Slider until issues are fixed?

Currently this looks pretty broken on people's sites:

<img width="438" alt="Screenshot 2020-08-06 at 18 22 10" src="https://user-images.githubusercontent.com/87168/89550110-e10d2480-d811-11ea-8b8d-cb5b4dbb34be.png">

cc @lessbloat in case Manage focus can triage this as well (it's a visual breakage in slideshow block)

**Comment by tavilla61** [comment]
I have another issue of this on a simple site. The double arrows appear, and also the images don't transition well and some of the previous image still shows as the new image appears, looking like an overlapped image. 

<img width="951" alt="Screen Shot on 2020-08-06 at 12-44-15" src="https://user-images.githubusercontent.com/33466168/89569966-b8ba0180-d7e2-11ea-88d5-d3bca732e668.png">

#22293720-hc
#3203732-zen

**Comment by lakellie** [comment]
Another report in 3209766-zen

**Comment by goblinartificer** [comment]
Another of the duplicates and image overlap on Fade mode in #23042840-hc

**Comment by davemart-in** [comment]
Note: This can be seen on an internal P2: pc6Vrl-2j-p2

**Comment by allykmyta** [comment]
Another report in #3213658-zen

**Comment by aaronrobertshaw** [comment]
I have been able to replicate this issue on a local Jetpack dev site as well as simple WordPress.com sites. Using the Jetpack Beta plugin on an Atomic site, the issue isn't present when using the latest stable version but it is there on bleeding edge. Whether the Gutenberg plugin was active or not didn't make a difference either.

**Comment by khristiansnyder** [comment]
Another report in 21504878-hc. CSS provided above helped in the meantime.

**Comment by simison** [comment]
D47922-code still needs deploying for simple sites to get the fix.

**Comment by aaronrobertshaw** [comment]
D47922-code has been shipped.
