### ISSUE TITLE
Shortcode slideshow uses jQuery `.load`

### ISSUE THREAD

**Issue by Clorith** [Automattic/jetpack#16715]
jQuery deprecated the `.load` function as an event handler in version 1.8, and it's been removed entirely in 3.0, which is used by the slideshow shortcode.

The function is called at https://plugins.trac.wordpress.org/browser/jetpack/tags/8.8/modules/shortcodes/js/slideshow-shortcode.js#L58

jQuery recommends replacing it with a call to `.on( 'load', <handler> )`.

As WordPress is working on upgrading jQuery, this may cause problems in version 5.6 when it is released (it will work in the upcoming 5.5, as the event handler use here is still valid in the version shipped with core).

**Comment by jeherve** [comment]
Definitely something we need to update. It's also impacting other features (Stats, Calypsoify, Likes, Sharing, Presentions shortcode, Recipes shortcode, and more).

Related: #16409, #15388

**Comment by sophiegyo** [comment]
Would this also be affecting slideshows that are added in sidebar widgets in the Customizer? I encountered an issue where a gallery widget set to slideshow won't work at all, but it's fine when the gallery is set to static images. 
This is how it looks: https://d.pr/i/IHic6v

**Comment by formosattic** [comment]
Following-up on @sophiegyo's case, 3363437-zd.

It happens on a site with a retired theme, Responsive. I haven't been able to reproduce it with a current theme.
Here's the error that comes up in the console:
![Markup on 2020-10-05 at 12:39:10](https://user-images.githubusercontent.com/15944096/95041028-1ba71680-0708-11eb-8b3c-cff38167b6a3.png)
