### ISSUE TITLE
(2P) Social Previews: Document the upgrade nudge approach

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/jetpack#16728]
As discussed in p1596637160315500-slack-CJS75TX3R, let's make sure we document implementation from #16724 (why `plan_check` isn't enough with extensions that are not your typical blocks) in `extensions/README.md`, or in the file itself, for our futureselves.

**Comment by getdave** [comment]
Nice following up. I'll pick this up tomorrow whilst it's fresh in my mind.

**Comment by getdave** [comment]
Let's waited until we're 100% on the approach we've taken in https://github.com/Automattic/jetpack/pull/16724.
