### ISSUE TITLE
Backslashes gets stripped from the Markdown code blocks

### ISSUE THREAD

**Issue by hilja** [Automattic/jetpack#1673]
If I have a backslashs anywhere in a codeblock:

```
\
```

It get's stripped out on save.

If I escape with another backslash:

```
\\
```

The first one get's stripped on first save and the second after that.

They don't get stripped from outside code blocks. I've got no other plugins active in my theme.

**Comment by jeherve** [comment]
cc @mattwiebe

**Comment by dereksmart** [comment]
@hilja, could you help me reproduce this?  Here's what I tried with Jetpack 3.3.2 & WP 4.1 (no other plugins):

\`\`\`echo "you\'re awesome!  Here\'s a single backslash: \"; \`\`\`

\<code>echo "you\'re awesome! here\'s a single backslash: \"; \</code>

\<pre>echo "you\'re awesome!  Here\'s a single backslash: \"; \</pre>


Which gives me this, when saving from both the visual and text editor: 
https://cloudup.com/c-y1xtw5ocO

**Comment by hilja** [comment]
This seems to keep the backslashes:

```
```echo "you\'re awesome!  Here\'s a single backslash: \"; ```
```
```
\```
echo "you\'re awesome!  Here\'s a single backslash: \"; 
\```
```


But if I put line breaks  before and after it like this:

**Comment by jeherve** [comment]
> But if I put line breaks before and after it backslashes get stripped.

I could reproduce on my end as well. Since you're supposed to leave line breaks before and after ```, that seems like a bug with Markdown.

When disabling Markdown, backslashes don't get stripped anymore.

**Comment by hilja** [comment]
> Since you're supposed to leave line breaks before and after ```, that seems like a bug with Markdown.

How would I then give a class to the code block? This:
```
```lang-php echo "you\'re awesome!  Here's a single backslash: \"; ```
```
Will output:

![screenshot 2015-02-28 18 07 31](https://cloud.githubusercontent.com/assets/2558021/6427044/afcb0aec-bf74-11e4-9610-90bd8661a61c.png)


Is Jetpack using Markdown Extra as a parser?

**Comment by jeherve** [comment]
> How would I then give a class to the code block?

That's what I meant. :) You are supposed to leave line breaks, so the fact
that it doesn't  work with line breaks is a bug.

We'll look into it.

**Comment by hilja** [comment]
Ah, exactly :) :hammer:

**Comment by dereksmart** [comment]
Reopening, as my attempt (<a href="https://github.com/Automattic/jetpack/commit/8975d80835d0e2e125b782e210593eb94857772f" target="_blank">#</a>) caused more problems than it solved - see #1703.

After running through again, I tracked the root problem to when the text is run through `codeblock_restore()`'s <a href="https://github.com/Automattic/jetpack/blob/master/_inc/lib/markdown/gfm.php#L161" target="_blank">regex</a>.  Slashes go into that function, and never come out.  

I am amateur at best when it comes to regex, so I'm raising a flag to any regex wizards who would like to take a look, as @mattwiebe is busy with his IRL baby and other things.

**Comment by Atlas7** [comment]
Hello. I'm so glad there there is actually an open issue ticket on this! Here are some sample snapshots.

Markdown code (I mean to have the backslash in the code block):

![markdown-extra-bug-backslash-code](https://cloud.githubusercontent.com/assets/11135428/6531603/553c7616-c432-11e4-9c02-c78d306c7d37.PNG)

Wordpress displays this (backslash got stripped unexpectly.):

![markdown-extra-bug-backslash-article](https://cloud.githubusercontent.com/assets/11135428/6531612/5c8ff744-c432-11e4-83d6-3873690ff7d7.PNG)

Thank you!

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/backslashes-in-code-blocks-consumed-on-every-save-when-using-markdown?replies=1&view=all
https://wordpress.org/support/topic/backslashes-in-code-blocks-are-consumed-on-every-save?replies=10&view=all
