### ISSUE TITLE
Subscriptions: Follower Emails no longer respect the more block, while "Full Text" is chosen in Settings > Reading

### ISSUE THREAD

**Issue by spencerberry** [Automattic/jetpack#16731]
#### Steps to reproduce the issue

1. In WP Admin > Settings > Reading > **For each post in a feed, include** > Full Text should be selected (This is the same as WordPress.com > Manage > Settings > Writing > Feed Settings > "Limited feed to excerpt" toggled OFF)
2. Please follow your own site, and make sure that instant email notifications are enabled https://wordpress.com/following/manage
3. Publish a post, with multiple blocks of content. Be sure to include the more block, between two of the blocks. This more block should represent the cutoff point for the post, both in the archive, and the email.
4. Note that in your email, the more block is not respected, and the entire content of the post is present.
5. Feel free to toggle this feed option to summary/excerpt, from Step 1. Now the email will respect the more block.

I believe this behavior has changed in a recent update, from a few conversations that I've had recently with users who are experiencing this change without making any changes themselves.

#### What I expected

1) When full text is enabled, the more block should still be respected in emails to followers
2) When full text is enabled, the excerpt is ignored in emails to followers
3) When full text is disabled (summary/limit feed to excerpt is chosen), the more block should only take precedence if there is no excerpt at all. This is how it works now.

#### What happened instead
1) When full text is enabled, the more block is ignored

**Comment by jeherve** [comment]
Are you able to reproduce this issue on a site for a new post now? I made some changes this morning on WordPress.com that may have fixed this.

**Comment by spencerberry** [comment]
Yes, just tested again and it is still happening, both on Business site with plugins and a Personal site without.

I believe it is the same issue as this, I thought it was Jetpack related 🤔
https://github.com/Automattic/wp-calypso/issues/44536

**Comment by jeherve** [comment]
> I believe it is the same issue as this, I thought it was Jetpack related

It is the same issue indeed.

The code controlling this lives on WordPress.com, so I suppose wpcom.trac would be the most appropriate place to report this issue. That said, The Calypso repo is as a good a place as any, as long as it gives visibility to the issue.

I'll close this issue in favor of the one in the Calypso repo to avoid duplicates.
