### ISSUE TITLE
Subscriptions: use site Icon in top right corner of Subscriptions emails

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1674]
Right now the subscription emails include 2 customizable spaces:
- The author can change their profile picture by uploading a Gravatar.
- The WordPress logo on the right can be changed by uploading a Blavatar (available only on WordPress.com).

Since we've added the Site Icon module to Jetpack, it'd be nice if Subscription emails could use that Site Icon if it exists.

Suggested here:
https://wordpress.org/support/topic/edit-wordpress-subscription-logo?replies=1&view=all

**Comment by richardmtl** [comment]
requested in 2282545-t

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/using-blavatar-to-replace-wp-logo-in-subscribe-emails?replies=1&view=all

**Comment by zigojacko** [comment]
Any update on whether we can expect support for the Blavatar (Blog Picture / Icon) on Wordpress.org sites any time soon?

**Comment by jeherve** [comment]
@zigojacko No update yet, but we'll post here as soon as we start working on this.

**Comment by rachelsquirrel** [comment]
Another request #2824458-t

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/email-logo/

**Comment by beaulebens** [comment]
Done in r143031-wpcom at least for subscription emails, there might be some others around that are using a different template or something that I still need to fix up.
