### ISSUE TITLE
General: Certain passwords fail when using XMLRPC clients

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#1677]
When Jetpack is activated, certain passwords with special characters will fail when using other XMLRPC applications—WP mobile apps, desktop apps, etc.

This occurs because Jetpack assumes the `wp.GetOptions` xmlrpc method, escapes the `$args`, then call the original `wp.GetOptions` method, which escapes the `$args` a second time unexpectedly (to WP) which causes the password to fail.

PR incoming with one method to resolve.

**Comment by theukedge** [comment]
@kraftbj Thanks for your persistence in running this issue down. I'll be very glad to see the back of this issue soon!

**Comment by samhotchkiss** [comment]
Thanks, @kraftbj!
