### ISSUE TITLE
(3P) Social Previews: Docs (both jetpack and wpcom)

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#16787]
Adapt WP.com support docs to Jetpack, incl updated screenshots etc.

https://wordpress.com/support/seo-tools/#search-and-social-previews

https://jetpack.com/support/seo-tools/
(Edit: Jeremy suggested we create a new page for Jetpack rather than adding to the existing one. See comments below.)

**Comment by getdave** [comment]
Related 713-gh-en.support-docs-content.

**Comment by frontdevde** [comment]
For wpcom:

Created a draft copy of the original post, so we can copy paste from there once we're ready. See 713-gh-en.support-docs-content#issuecomment-674830265.

**Comment by frontdevde** [comment]
Image assets created for/on wpcom:

<img width="925" alt="Screenshot 2020-08-17 at 13 35 14" src="https://user-images.githubusercontent.com/1562646/90392470-33aad400-e08f-11ea-84c0-a347bc20ff2f.png">
<img width="436" alt="Screenshot 2020-08-17 at 12 52 32" src="https://user-images.githubusercontent.com/1562646/90392481-37d6f180-e08f-11ea-8451-af3a59c9889a.png">

**Comment by frontdevde** [comment]
For Jetpack:

1. Change headline to ` ~~Search and~~ Social Previews`
2. Change first paragraph to
```
Before you publish your new post or page, you can use the Social Previews feature to preview what it will look like on search engines and social media.

To do so, look for the Social Previews section in the Jetpack sidebar. In the Social Previews section, click the Preview button to open the Social Previews modal.
```
3. Change image to 
<img width="274" alt="Screenshot 2020-08-17 at 14 25 28" src="https://user-images.githubusercontent.com/1562646/90395886-91421f00-e095-11ea-980a-ab0dbb38b68b.png">
4. Change second paragraph to

```
The Social Previews feature will use the custom description you set in the SEO Description box so you can get an idea of what it will look like on Google Search, Facebook, and Twitter. 
```

5. Add image
<img width="934" alt="Screenshot 2020-08-17 at 14 32 19" src="https://user-images.githubusercontent.com/1562646/90396441-81770a80-e096-11ea-9238-8f8f55cde07b.png">

**Comment by jeherve** [comment]
In Jetpack, I would recommend keeping SEO Tools and Social Previews separate in the docs. The 2 features will not really be linked; one is free and available as soon as you connect Jetpack to WordPress.com, the other is paid and requires activating a specific module.

**Comment by frontdevde** [comment]
Thanks for chiming in, @jeherve!

What I assume you are suggesting is we create a new support document for Social previews? If so that would probably fit better under `Support Home > Social` than `Support Home > Appearance` (where SEO Tools lives).

Also should we remove the "Search and Social Previews" section from SEO Tools once that document is live?

**Comment by jeherve** [comment]
> What I assume you are suggesting is we create a new support document for Social previews?

Yes. I think it could then be added to the list of extensions at the bottom of the page here:
https://jetpack.com/support/jetpack-blocks/

I think the External Media extension will go there as well, at some point:
1143503926117064-as-1181953898395145

> If so that would probably fit better under Support Home > Social than Support Home > Appearance (where SEO Tools lives), no?

Indeed. I'd suggest reaching out to #jpop-quill about this, they'll know best.

> should we remove the "Search and Social Previews" section from SEO Tools once that document is live?

Maybe we should keep the section, but make it smaller and point to the new doc? Maybe Quill would have some ideas there.

**Comment by frontdevde** [comment]
> I'd suggest reaching out to #jpop-quill about this

I did a couple of days ago. Just did so again, hoping for a reply :) C2LPC2EMN-p1597669653030200-slack

**Comment by RCowles** [comment]
> Yes. I think it could then be added to the list of extensions at the bottom of the page here:
> https://jetpack.com/support/jetpack-blocks/

We discussed this on Slack and agree this would be a good approach. We can mention it in the overall list and link out to a new doc with more information.

> In Jetpack, I would recommend keeping SEO Tools and Social Previews separate in the docs.

I would also +1 this approach, in keeping the SEO Tools and Social Previews as-is.

Just to make sure I'm not missing anything, is there anything else you'd like input on from the Quill side?

**Comment by frontdevde** [comment]
> Just to make sure I'm not missing anything, is there anything else you'd like input on from the Quill side?

That's it, thank you for your input! 👍

**Comment by cpapazoglou** [comment]
### WordPress.com
Addressed 713-gh-en.support-docs-content

### Jetpack
- Added the `Social Previews` extension to the bottom of the page https://jetpack.com/support/jetpack-blocks/
- Created https://jetpack.com/support/extension-social-previews/
- Added here https://jetpack.com/support/social/ (automatically by tag)
- Changed https://jetpack.com/support/seo-tools/ section

Before | After
-------|------
![](https://cln.sh/rXYGZy+) | ![](https://cln.sh/yN9Hup+)

**Comment by coder-karen** [comment]
@frontdevde just noticing this:

> The Social Previews extension will use the custom description you set in the Advanced SEO meta description settings so you can get an idea of what it will look like on Google Search, Facebook, and Twitter.

This is only applicable to WordPress.com sites isn't it? Since the feature is available on all Jetpack plans, then it doesn't make sense to allude to the SEO meta description box here. I'm happy to edit the doc if I'm understanding this correctly :)

**Comment by jeherve** [comment]
> This is only applicable to WordPress.com sites isn't it?

That's correct.
