### ISSUE TITLE
(2P) Social Previews: Unify approaches for responsive CSS

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/jetpack#16785]
Both #16744 and #16704 were created at the same time to style adjacent components but they both use vastly different approaches to responsive styling (one something closer to Gutenberg, one is using Jetpack SCSS helpers)

Let's settle on a single approach. But I don't know which one! From a brief look in the `extensions` dir (searching for `@media`), #16704 is the only place where something from the Jetpack root `scss` dir is imported, which makes me think it's probably not the correct way.

cc: @frontdevde @cpapazoglou @jeherve

**Comment by jeherve** [comment]
> something from the Jetpack root scss dir is imported, which makes me think it's probably not the correct way.

Yep. That part of Jetpack is not available on WordPress.com, so that's not an option.

**Comment by frontdevde** [comment]
- Changed approach to use Gutenberg breakpoints ([commit](https://github.com/Automattic/jetpack/pull/16704/commits/00785bc96e4e491d677dffebecc84432173fb849))
- Removed color-studio dependency in favor of Gutenberg colors ([commit](https://github.com/Automattic/jetpack/pull/16704/commits/06f2daaf1ec336eb375e48ef87ea3e171c074f9c))
- Removed atoms colors dependency in favor of Gutenberg colors ([commit](https://github.com/Automattic/jetpack/pull/16704/commits/76e312b1fd6929f41348735107601435c435e828))
