### ISSUE TITLE
Subscriptions: Improve Messaging when an email has too many Pending subscriptions

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/jetpack#16790]
Users that have 50 pending subscriptions aren't able to subscribe to any more, but the error message is very vague:

![Screen Shot on 2020-08-10 at 13-55-37](https://user-images.githubusercontent.com/22805865/89814586-59752d80-db11-11ea-816a-e8bfea2c3cc9.png)

We fixed the error message for those trying to subscribe to a site for which they already have a pending sub in #14326, but the message users see when subscribing to a new site is still very confusing. 

#### Steps to reproduce the issue

1. Start with a WordPress.com account that has at least 50 pending subscriptions.
2. Try to subscribe to a new site. 
3. See the confusing error. 
4. Remove some of those pending subscriptions from the account. 
5. Subscribe again successfully

#### What I expected

I'd expect to see a message indicating that I have too many pending subs and that's why I'm not able to subscribe, with a link to my subscriptions dashboard where I can remove those pending subs. 

Internal ref: 3202604-zen

**Comment by htdat** [comment]
Actually, we have already handled this case with this PR https://github.com/Automattic/jetpack/pull/14275

> There was an error when subscribing. Please try again.

This error message comes from the `default` case. Maybe another issue happens instead of so many pending subscriptions. 

https://github.com/Automattic/jetpack/blob/be0708aa2d550b4578c53e85c2386bad3f6cd327/modules/subscriptions/views.php#L209-L211

**Comment by htdat** [comment]
> Users that have 50 pending subscriptions. 

Also, our limit is much less than this now.

**Comment by tmmbecker** [comment]
I'll close this for now. 

But it's a bit odd that I got that message, removed a bunch of the pending subs and then was able to subscribe with no error. If it were something else, I wouldn't have expected the error to clear after only removing the pending subs.
