### ISSUE TITLE
Payments: Asking for upgrade on sites with biyearly subscriptions

### ISSUE THREAD

**Issue by ezebecke** [Automattic/jetpack#16796]
#### Steps to reproduce the issue

1. Create a site with a biannual WordPress.com Personal plan. 
2. Go to any page/post and try adding the Payments block
3. Block will ask you to upgrade to a paid plan

#### What I expected

To add the block without any error/upgrade messages. 

#### What happened instead

The block doesn't seem to notice biannual plans. The workaround was to add an annual plan for now.

Reported: 3213918-zd

**Comment by dsas** [comment]
I can't reproduce this on the Payments or Donations block, it works for me. It looks at the plan type and not the duration.

Personal sites don't get the Pay with paypal block, it's premium and above.

@ezebecke can you still reproduce this? If so can you walk me through how?

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
