### ISSUE TITLE
[Infinite Scroll] Uncaught type error: cannot set property 'html' of undefined

### ISSUE THREAD

**Issue by Barralait** [Automattic/jetpack#1679]
So I'm trying to get Infinite Scroll to work on this custom theme on a website. The posts are correctly loaded, however, each time the user scrolls past an infinite-view, the error *Uncaught type error: cannot set property 'html' of undefined* appears.

I tried deleting these two functions which are the cause of this error, and everything works fine afterwards. But this is hacky and bad and I'd like to find the real cause of the problem. I know it is due to the theme because everything works fine when I change to Twenty Fifteen, but I can't seem to find out why this is happening.

The page in question [is here](http://www.cblawparis.com/en/crossen-borowsky/actualites/). Also note that the page numbers are not added to the URL when scrolling because of this bug.
````javascript
	$.each(setsHidden, function() {
		var $set = $('#' + this.id);
		if( $set.hasClass( 'is--replaced' ) ) {
			return;
		}

	        self.pageCache[ this.pageNum].html = $set.html();

		$set.css('min-height', ( this.bottom - this.top ) + 'px' )
		    .addClass('is--replaced')
		    .empty();
	});

	$.each(setsInView, function() {
		var $set = $('#' + this.id);

		if( $set.hasClass('is--replaced') ) {
			$set.css('min-height', '').removeClass('is--replaced');
			if( this.pageNum in self.pageCache ) {
				$set.html( self.pageCache[this.pageNum].html );
		        	self.body.trigger( 'post-load', self.pageCache[this.pageNum] );
			}
		}
	});
````

**Comment by jeherve** [comment]
For reference, the error refers to [this line](https://github.com/Automattic/jetpack/blob/3.3.2/modules/infinite-scroll/infinity.js#L530).

Could you try to dequeue your `script.js` file ([#](http://www.cblawparis.com/wp-content/themes/crossenborowsky/js/script.js?ver=4.1.1)), and let us know if it changes anything?

**Comment by Barralait** [comment]
Hey @jeherve, and thanks for the answer!

I dequeued script.js, to no avail...

As I was already dequeuing `script.js`, I also tried with all the external js files I'm enqueuing (`jquery.vegas.js`, `bootstrap.min.js` and custom `navigation.js` and `skip-link-focus-fix.js`), the error was still there.

**Comment by jeherve** [comment]
Could you paste the code you used to add Infinite Scroll support here, so I can take a look?

**Comment by Barralait** [comment]
````php
function cb_infinite_scroll_init() {
        add_theme_support( 'infinite-scroll', array(
            'container' => 'en-content',
            'wrapper' => 'row',
            'footer' => false,
            'posts_per_page' => 3,
        ) );
}
add_action( 'init', 'cb_infinite_scroll_init' );
````

**Comment by jeherve** [comment]
Could you try to rename the HTML elements that use the `raw` class outside of the post container? Infinite Scroll is probably failing because the `raw` class should only be used for containers meant to be used with Infinite Scroll.

Let me know how it goes. 

props @folletto for finding this! :)

**Comment by Barralait** [comment]
Ok this is definitely it. My only problem is that I need the posts to be wrapped in `rows` for correct alignment - Bootstrap limitation. But this is a Bootstrap and theme code issue, and I thank you for the time you spent helping me on this, I've got this covered from now on! And I guess thanks to @folletto are also in order!
