### ISSUE TITLE
Extensions: Prevent importing files that won't be available in wpcom

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/jetpack#16803]
#### Is your feature request related to a problem? Please describe.
When working in the `extensions` directory, you can import any file from the whole Jetpack repo (for example `_inc` or `scss`). This all works well and doesn't complain but it will in fact fail once synced to wpcom, where some of these files are not synced.

#### Describe the solution you'd like
`yarn build-extensions` showing warnings/errors when importing file that won't be available. How can we determine this? Should we block everything above the `extensions` directory to be safe or is there a list of files we might use for more clever matching?

#### Describe alternatives you've considered
—

#### Additional context
It's something we've hit when working on #16785

**Comment by jeherve** [comment]
With the new build system this shouldn't be an issue anymore. Closing.
