### ISSUE TITLE
Infinite Scroll: Jetpack 8.8 breaks Infinite Scroll with type:'click' and wrapper:'false'

### ISSUE THREAD

**Issue by robrobsn** [Automattic/jetpack#16807]
(See cause of error below)

#### Steps to reproduce the issue

1. Make sure Jetpack 8.8 or Jetpack 8.8.1 is installed and activated
2. Activate a Theme with Support for Infinite Scroll with the following settings:
'type'      => **'click'**,
'wrapper'   => **false**,

```php
add_theme_support(
	'infinite-scroll',
	array(
		'container' => 'site-content',
		'footer'    => false,
		'render'    => 'theme_infinite_scroll_render',
		'type'      => 'click',
		'wrapper'   => false,
	)
);
```
3. Go to the Dashboard > Jetpack > Settings > Writing 
4. Scroll down to 'Theme enhancements' > 'Infinite Scroll' 
5. Check 'Load more posts in page with a button' and click 'Save settings'
6. Switch to the front end of the site and go to the blog page
7. Scroll down to and click the 'Load more' button ( Make sure the site has enough posts for the Infinite Scroll button to be visible )

#### What I expected
The next batch of posts are added, the 'Load more' button is visible and works when clicking it again.

#### What happened instead
The next batch of posts are added. A JavaScript error occurs and the 'Load more' button has been removed even when more posts are available.

#### Cause of error
Jetpack 8.8 made the following improvement 'Infinite Scroll: improve accessibility of the "Load More" behavior.' and added the following lines to infinite.js
```js
document
	.querySelector( '#infinite-view-' + ( self.page + self.offset - 1 ) + ' a:first-of-type' )
	.focus( {
		preventScroll: true,
	} );
```
[see GitHub commit](https://github.com/Automattic/jetpack/commit/82db44a44297c6cd3d49dad49334d21038ad1a2b#diff-4266603d8a785dc1033a6dfd87d33c80R489-R495).

The script throws an error because with 'wrapper' set to **false** the container '#infinite-view-2' doesn't exist and 'document.querySelector' returns 'null'.

**Comment by andyaffleck** [comment]
Note: FWIW, Rob is a contractor who is on retainer with Team 51.

**Comment by jeherve** [comment]
Thanks for the report!

@scottsweb Do you think you could take a look?

**Comment by scottsweb** [comment]
Looking now.

**Comment by scottsweb** [comment]
PR is open: https://github.com/Automattic/jetpack/pull/16817

**Comment by dashkevych** [comment]
I am also getting the issue. Here is a screenshot:
![JS issue in the Infinite Scroll functionality ](https://snipboard.io/O9CGKS.jpg)
