### ISSUE TITLE
Tiled Galleries UI doesn't load in Core/trunk

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#1681]
https://core.trac.wordpress.org/changeset/31373/ refactors how JS is handled in core. We may be declaring a dependency that is no more in https://github.com/Automattic/jetpack/blob/master/functions.gallery.php#L38-39

Result is when editing a post and adding a gallery, there are no Tiled Galleries options.

Noting it here so we can discuss with Core if this is something they could account for or if we need to adjust.

(Note: tested on "build" via core.svn)
cc: @georgestephanis

**Comment by samhotchkiss** [comment]
Kicking down the road to 3.5...

**Comment by jeherve** [comment]
@samhotchkiss Seeing that WordPress 4.2 is planned for next month, shouldn't we aim to fix this as soon as possible, so we have as many people as possible running a version of Jetpack including the fix when 4.2 comes out?

**Comment by kraftbj** [comment]
+1 to not letting this hang. The only way to add a Tiled Gallery in next month's 4.2 is to set the global Settings->Media.

Additionally, if we can track exactly why this breaks, we can bring it up to core before 4.2 ships. We're likely not the only plugin that this will happen to. It might be something we have to fix or something that core didn't consider (in terms of backwards compat) when refactoring.

**Comment by samhotchkiss** [comment]
Makes sense-- this isn't going to make it for 3.4, but I'm tagging it for 3.4.1, which should happen within 3 weeks, probably sooner

**Comment by samhotchkiss** [comment]
cc: @michaeldcain

**Comment by kraftbj** [comment]
Resolved in Core via https://core.trac.wordpress.org/changeset/31935
