### ISSUE TITLE
Subscriptions: Site owner added as Subscriber if someone comments and checks the "Subscribe to blog/site" checkboxes

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#1682]
How to reproduce:

1) Connect a site to WordPress.com, but don't Follow or Subscribe to it; activate Jetpack Comments and Subscriptions.
2) Have someone else leave a comment on it, and check the "Notify me of new comments via email." and "Notify me of new posts via email." boxes.
3) The WordPress.com account that made the primary connection to WordPress.com is now a WordPress.com Follower for the site without any email asking them to confirm the subscription, as well as the person who left the comment.

Permutations I didn't check:

1) Without Jetpack Comments active
2) With only one of the 2 checkboxes checked
3) Whether or not the commenter needs to confirm their subscription before the site owner is added as a Follower (but I suspect that they don't need to).

**Comment by shawnajroberts** [comment]
Pretty sure I have another instance of this here - http://en.forums.wordpress.com/topic/im-receiving-subscription-notifications-for-my-own-site-im-not-subscribing

**Comment by lizthefair** [comment]
As a follow up the user in Shawna's thread above did more testing and reports the following:

>Someone subscribed as an email follower with the address he has registered at WP and I was subscribed at the exact same moment.

>I presume it's a WP account. It's the same address he is registered as a Contributor with.

**Comment by jeremeylduvall** [comment]
Still working with the individual here:

https://en.forums.wordpress.com/topic/im-receiving-subscription-notifications-for-my-own-site-im-not-subscribing?replies=58

I just tested again on a self-hosted site, and I'm experiencing the behavior Richard mentioned above.

**Comment by richardmtl** [comment]
this came up again in 2300156-t

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
