### ISSUE TITLE
Jetpack::(*)_option duplicated methods.

### ISSUE THREAD

**Issue by lezama** [Automattic/jetpack#1683]
@georgestephanis are there any reasons to keep this methods alive?
https://github.com/Automattic/jetpack/blob/master/class.jetpack.php#L1231-L1258

Let me know if you want me to kill them all.

**Comment by jeherve** [comment]
@lezama I believe we still use a few of those in quite a lot of places in Jetpack. Third-party plugin developers also use them, for things like this for example:

```php
// Force deactivate all Jetpack modules, except for stats
function jeherve_force_deactivate_everything_but_stats() {
	if ( class_exists( 'Jetpack_Options' ) )
		Jetpack_Options::update_option( 'active_modules', array_unique( array( 'stats' ) ) );
}
add_action( 'init', 'jeherve_force_deactivate_everything_but_stats' );
```

If you decide to remove them, can you deprecate them nicely?

Thanks!

**Comment by lezama** [comment]
@jeherve: I want to delete `Jetpack::update_option` and siblings in favor of `Jetpack_Options::...`

**Comment by georgestephanis** [comment]
I left them initially as a backcompat for any old plugins or the like that used the old way

https://github.com/Automattic/jetpack/blob/master/class.jetpack.php#L1195-L1258

If we can, I'd prefer to add in a `_doing_it_wrong()` call to catch anyone still using them for a release or two, but if you need to burn them, I won't shed too many tears.
