### ISSUE TITLE
Site Accelerating Serving Wrong Sized Image

### ISSUE THREAD

**Issue by LocalSKIM** [Automattic/jetpack#16834]
I originally posted this in the Wordpress Jetpack help forum (https://wordpress.org/support/topic/site-accelerator-upscaling-images/#post-13246782) but was asked to post this here.

Site Accelerator is serving up the wrong sized image under certain conditions.

In my functions.php file, it is set to crop all featured images (entry_without_sidebar) to 1128 x 550

```
function modified_thumb_for_blog_pages( $size ){
  $size['entry_without_sidebar'] = array('width'=>1128, 'height'=>550 );      
  return $size;
```
The physical space for the image on my website is only 564 wide but to accommodate retinal displays, I make the images double the size (1128 x 550). But on a regular monitor, the image will be scaled down to 564 x 275.

The photo that I had a problem with had an original size of 1024 x 819. So the featured image would be automatically cropped to 1024 x 550 (as per the code in the functions.php file). However, I used the media library editor in WordPress to crop the picture to 564 x 275 so it would display properly. But when the image is shown on the website, site accelerator serves the original image of 1024 x 550 (the photo shown is 564 x 303 pixels, intrinsic 1024 x 550 pixels).  

Here is the image url served by site accelerator:

`<img width="1024" height="550" src="https://i2.wp.com/localskim.com/stcatharines/wp-content/uploads/sites/2/2020/08/Dunn-IceDogs-e1597206081885.jpg?resize=564%2C274&amp;ssl=1" class="attachment-entry_without_sidebar size-entry_without_sidebar wp-post-image" alt="" srcset="https://i2.wp.com/localskim.com/stcatharines/wp-content/uploads/sites/2/2020/08/Dunn-IceDogs-e1597206081885.jpg?zoom=2&amp;resize=1024%2C550&amp;ssl=1 2048w, https://i2.wp.com/localskim.com/stcatharines/wp-content/uploads/sites/2/2020/08/Dunn-IceDogs-e1597206081885.jpg?zoom=3&amp;resize=1024%2C550&amp;ssl=1 3072w" sizes="(max-width: 1024px) 100vw, 1024px">`

However when I edit the original image to 564 x 275 using a photo editor program and then upload the image into WordPress, the image displays correctly since that is the only sized image site accelerator has.

Here is the image url from site accelerator when I edit the image before uploading to WordPress:

`<img width="564" height="275" src="https://i1.wp.com/localskim.com/stcatharines/wp-content/uploads/sites/2/2020/08/Dunn-IceDogs-Edited.jpg?resize=564%2C275&amp;ssl=1" class="attachment-entry_without_sidebar size-entry_without_sidebar wp-post-image" alt="" srcset="https://i1.wp.com/localskim.com/stcatharines/wp-content/uploads/sites/2/2020/08/Dunn-IceDogs-Edited.jpg?w=564&amp;ssl=1 564w, https://i1.wp.com/localskim.com/stcatharines/wp-content/uploads/sites/2/2020/08/Dunn-IceDogs-Edited.jpg?resize=300%2C146&amp;ssl=1 300w" sizes="(max-width: 564px) 100vw, 564px">`

I cannot find anyway to fix this issue, besides editing the photo before uploading to Wordpress which is less than ideal.

**Comment by jeherve** [comment]
I'm afraid that's indeed something that's bound to happen. Jetpack's Image CDN, also known as Photon, works with the original image and ignores all resized versions of that image by design. Instead it creates its own resized versions when needed, based off the original image. It does not cache, optimize, or even know about the existing resized images on your site.

It's not really something that we can change without changing the way the CDN works as a whole.

As a result, I am afraid I can only recommend that you turn off Jetpack's Image CDN feature for now, as it's not really compatible with the way images work on your site.
