### ISSUE TITLE
Custom CSS and Extra Sidebar Widgets: Activating both modules causes CSS previews to break

### ISSUE THREAD

**Issue by druesome** [Automattic/jetpack#16841]
Activating the Custom CSS and Extra Sidebar Widgets Jetpack modules causes the CSS to stop previewing when you type in new CSS code.  The bug happens only when both modules are turned on.

#### Steps to reproduce the issue

1. In Google Chrome, switch to the default Twentytwenty theme
2. Visit Jetpack > Settings
3. Make sure that the Custom CSS and Extra Sidebar Widgets modules are turned off
4. In a new browser tab, visit Appearance > Customize > Additional CSS
5. Add some CSS that applies to the front page and is easy to notice, such as setting the font color to red or the heading color to blue.
6. Make sure that the CSS is applying to the front page preview.
7. Click Save Changes.
8. Switch to the tab where you have Jetpack > Settings open.
9. Activate the Custom CSS and Extra Sidebar Widgets modules
10. Switch back to the tab where the Customizer is and refresh it.
11. Click Additional CSS
12. Type something
13. Notice the CSS not applying to the preview anymore
14. Go back to the main Customizer menu and check or uncheck any box in Theme Options
15. Notice the CSS applying again
16. Go back to Additional CSS and press any key, CSS stops previewing
17. Go to Jetpack > Settings and turn off either Custom CSS or Extra Sidebar Widgets
18. Refresh the Customizer and type some new CSS
19. Notice that the CSS is previewing correctly

#### What I expected

For the CSS to preview regardless of Custom CSS and Extra Sidebar Widgets Jetpack modules being active or not.

#### What happened instead

The CSS stops previewing after typing something into the Additional CSS section when the Custom CSS and Extra Sidebar Widgets modules are both active.

**Screenshots**

Here is a screencast: https://d.pr/v/sKDbI2

Tested and confirmed happening on Atomic and self-hosted WordPress.org sites in the latest Google Chrome browser (version 84.0.4147.125).  Seems to work ok in Firefox.

**Comment by jeherve** [comment]
Closing this since the feature is no longer available on self-hosted sites.
