### ISSUE TITLE
Image Compare Block: No caption in AMP

### ISSUE THREAD

**Issue by fresatomica** [Automattic/jetpack#16858]
#### Steps to reproduce the issue

1. Add Image Compare Block
2. Add a caption to the image
3. Display the site in AMP mode
4. See no caption displayed

#### What I expected
A caption would display in both standard and AMP versions

Example: https://fireattacktest.wordpress.com/2020/08/14/test-image-compare-mobile-caption/amp/
Reported in the WordPress.com forums: https://wordpress.com/forums/topic/image-compare-blocks-caption-doesnt-show-in-amp-site/

**Comment by westonruter** [comment]
PR to fix: #17254

**Comment by fireattack** [comment]
Original reporter here, thanks for the PR!
