### ISSUE TITLE
Photon stopped working in WooCommerce 4 short descriptions

### ISSUE THREAD

**Issue by leandroprz** [Automattic/jetpack#16856]
#### Steps to reproduce the issue
1. Create a new product in WooCommerce.
2. Add an image to the short description.
3. Enable Jetpack Photon module.
4. Check the product you created in step 1. The image is not served from WordPress servers.

Example: https://leandroperez.com.ar/tienda/cursos/ciclo-cuarentena-fotografica/

#### What I expected
The image to be picked up by WordPress servers.

#### What happened instead
The image is not being served by WordPress servers.

#### Previously working solution
[This snippet](https://github.com/Automattic/jetpack/issues/11732#issuecomment-477546113) was working in WooCommerce 3, but stopped working after updating to v4.

```
function jeherve_photonize_woo_short_description_images( $short_description ) {
    if ( class_exists( 'Jetpack_Photon' ) ) {
        $short_description = Jetpack_Photon::filter_the_content( $short_description );
    }

    return $short_description;
}
add_filter( 'woocommerce_short_description', 'jeherve_photonize_woo_short_description_images' );
```

**Comment by jeherve** [comment]
It does seem to work for me, with WooCommerce 4.3.3 and Jetpack 8.8.1. Could you try to deactivate any other plugins on your site, and ensure that no other plugin is causing a conflict here?

**Comment by leandroprz** [comment]
So sorry for the late reply. I was able to do some tests and realized some of my custom code was causing the issue.
