### ISSUE TITLE
Declaration of Jetpack_IXR_Client::query() should be compatible with IXR_Client

### ISSUE THREAD

**Issue by WilliamTai** [Automattic/jetpack#16857]
#### Steps to reproduce the issue

1. Upgrade to WordPress 5.5 automatically
2. Login to admin
3. `Declaration of Jetpack_IXR_Client::query() should be compatible with IXR_Client` appear on top of dashboard

#### What I expected

nothing should be there.

#### What happened instead

This issue appear after auto upgrade to WordPress 5.5.

I saw a thread in WordPress forum talking about this issue, not sure is reported or not.
https://wordpress.org/support/topic/declaration-of-jetpack_ixr_clientquery-should-be-compatible-with-ixr_client/

**Comment by jeherve** [comment]
Could you let me know what version of Jetpack you currently run on your site, and if you have any other plugins installed? We aimed to fix that issue in #16316, so if you run the latest version of Jetpack you should not experience this.

**Comment by jeherve** [comment]
@Njengah Could you also let me know what versions of Jetpack you currently use on your site, as well as any other plugins you may be using on your site?

Thank you.

**Comment by WilliamTai** [comment]
@jeherve 
Hello, the Jetpack version is v6.9 and I notice that the auto-update is not working.
After delete the old one and re-install this issue fix.
thanks.
