### ISSUE TITLE
Embedded Contact Forms within nested pages

### ISSUE THREAD

**Issue by thisislawatts** [Automattic/jetpack#1688]
When a child page is displayed on the same URL as it's Parent page it's not possible to submit the form.
I believe this is where I've rewritten the child's permalink so that it would read **/parent#childslug**.  Using the existing filter `grunion_contact_form_form_action` I have been able to fix the problem of 2 hashes appearing, however at this point once submitted it's trying to submit a contact form it's expecting to be contained within the parent.

I appreciate that this might seem like a very particular edge case, however it's been easy to workaround with the addition of just two filters  thisislawatts/jetpack@d4690f4f91735056ec325f87ba07c121db1f9fd0

**Comment by georgestephanis** [comment]
I'm going to rough in a possibility of how we can do this without Jetpack changes tomorrow morning.

**Comment by thisislawatts** [comment]
That would be great @georgestephanis, be interested to read your solution

**Comment by thisislawatts** [comment]
Cleaning up my GH issues, and marking this as closed
