### ISSUE TITLE
infinite Scroll: Not Including infinity.js

### ISSUE THREAD

**Issue by davidbarratt** [Automattic/jetpack#169]
I've added infinite scroll support to my theme and I've enabled the Jetpack plugin. However, infinity.js isn't even being included in the page. wp_head() is being called properly and other scripts like jQuery are being included, but not infinity.js.

What is wrong?

**Comment by Z3RatuL** [comment]
I'm having the same problem. I enable Infinite Scroll, include the necessary code in my Theme's function.php file but infinity.js is never loaded.

**Comment by jeherve** [comment]
@Z3RatuL Could you send us an email with more details about your site, so we can take a look?
http://jetpack.me/contact-support/

Thanks!

**Comment by Z3RatuL** [comment]
OK I've sent a message using your contact support page. Thanks!
