### ISSUE TITLE
Google Maps shortcode generates a bad url for "View Larger Map"

### ISSUE THREAD

**Issue by salcode** [Automattic/jetpack#1690]
Issue was discovered on http://lancasterpa.wordcamp.org/2015/location/

When the [View Larger Map](https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3053.9383820957555!2d-76.282494!3d40.054476!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c624a8aa2d1bb9:0x7e35e940194b567f!2s1020%20New%20Holland%20Ave,%20Lancaster,%20PA%2017601!5e0!3m2!1sen!2sus!4v1422973712907) link is clicked, the result is
```
The Google Maps Embed API must be used in an iframe.
```

Since the place card includes a [View on Google Maps](http://maps.google.com/maps?ll=40.054476,-76.282494&z=16&t=m&hl=en-US&gl=US&mapclient=embed&q=1020%20New%20Holland%20Ave%20Lancaster%2C%20PA%2017601) link, I would consider removing the __View Larger Map__ link found below the map.

![image](https://cloud.githubusercontent.com/assets/5194588/6414260/0130a336-be64-11e4-80b4-27ea27c4040e.png)

**Comment by kraftbj** [comment]
This is fixed in `master` via d09a4ecbd30e48042cfdc8a0017afdaa458ebfa6 . Assigning it to the 3.4 milestone so it can get picked up for the next release.

**Comment by georgestephanis** [comment]
Drat, wish I'd have caught that in a point release.  Ah well.
