### ISSUE TITLE
Explore adding new files to Fusion

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#16920]
> Things get more complicated for files that are brand new on both sides and this workflow is in flux, so ping the Jetpack team for help.
—PCYsg-fTc-p2

Let's find out what's keeping Fusion from syncing newly added files to phab diffs and see if we can fix that.
As a first step, can we get files that are added to a sync'd folder become part of the phab diff.

**Comment by obenland** [comment]
D48433-code expands `_jetpack_file_sync_files()` to include new files that are part of an existing directory. I assume we'd also need to make sure `jetpack_file_sync_diff()` still works and does what it's supposed to.

**Comment by mreishus** [comment]
I'm worried that the code would only enter the `	if ( empty( $all_jetpack_files ) ) {` on line 133 if change includes only new files.  If there were a mix of existing and new files, then I think it might not enter the new code.  However, this is just speculation as I haven't tested it.  Currently not sure how to manually test a modified version of `wp-content/lib/jetpack-file-sync.php`.  I'm investigating, but if anyone knows, please share.

**Comment by cpapazoglou** [comment]
> I'm worried that the code would only enter the ` if ( empty( $all_jetpack_files ) ) {` on line 133 if change includes only new files. If there were a mix of existing and new files, then I think it might not enter the new code. However, this is just speculation as I haven't tested it. Currently not sure how to manually test a modified version of `wp-content/lib/jetpack-file-sync.php`. I'm investigating, but if anyone knows, please share.
> 
> Edit: This post ( [p9dueE-8k-p2](https://href.li/?p9dueE-8k-p2) ) has some directions on running the sync from the command line. I am still interested in seeing the automated build code that calls it, or a log of real commands that were executed after a push to github triggered a fusion sync.

`_jetpack_file_sync_files()` runs for every single file so there is no problem with a mix of files

I used the development guidelines in the FG and the following 2646e-pb as payload which is generated from this PR https://github.com/Automattic/jetpack/pull/17047. That said, I didn't got it working yet. It seems that this part
```
$dest = '/' . ltrim( $dest, '/' );
				if ( 0 === strpos( $search, $dest ) ) {
					$all_jetpack_files[ $search ] = str_replace( $dest, $source, $search );
				}
```
doesn't work well for my `$search = "extensions/test-fusion.php"`. Also, after working around this, I got
`Warning: file_get_contents(/home/wpcom/public_html/wp-content/mu-plugins/jetpack/extensions/test-fusion.php): failed to open stream: No such file or directory in /home/wpcom/public_html/bin/jetpack/utility-functions.php on line 138` cause the file doesn't exist yet in wpcom! So I will keep digging!

**Comment by cpapazoglou** [comment]
> Warning: file_get_contents(/home/wpcom/public_html/wp-content/mu-plugins/jetpack/extensions/test-fusion.php): failed to open stream: No such file or directory in /home/wpcom/public_html/bin/jetpack/utility-functions.php on line 138 cause the file doesn't exist yet in wpcom! 

I have created a new post here p9dueE-1Ow-p2 so that we can discuss further the consequences of files not existing in wpcom.

**Comment by cpapazoglou** [comment]
Still a WIP, just noting down the phab diffs
Jetpack D48433-code
MC D48979-code

**Comment by cpapazoglou** [comment]
Deployed 
r213567-wpcom
r213564-missioncontrol
