### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by ZeroWasteIngi** [Automattic/jetpack#16929]
Error on my website. I read on another page that this is cause jetpack. 

Uncaught TypeError: Cannot read property 'classList' of null
    at eu-cookie-law.min.js:2
    at eu-cookie-law.min.js:2

Do you know how this can be corrected?

#### What happened instead

**Screenshots**

**Comment by jeherve** [comment]
Thanks for the report. Closing as duplicate of #16625.
