### ISSUE TITLE
Donations: Improve usability

### ISSUE THREAD

**Issue by mmtr** [Automattic/jetpack#16928]
As noted by @krymson24 in p58i-9k2-p2#comment-47371, there are some usability improvements we could apply to the Donations block.

**Fix decimals to max decimals allowed by currency** ☑

E.g. For USD, we shouldn’t allow the user to enter any more digits after .00. It doesn’t do anything anyway and it just unnecessarily expands the donation button when they’re editing it.

![image](https://user-images.githubusercontent.com/1233880/90870950-9e635480-e39a-11ea-9424-01e63d7d7760.png)

**Do not allow to enter text** ☑

Strings can be entered in these boxes, which is not expected. On top of that, the string persists, but disappears when the page is updated and navigated back to.

![image](https://user-images.githubusercontent.com/1233880/90871068-c652b800-e39a-11ea-85ce-d87a2cd4c0ad.png)

**Format amounts when typing**

Format numbers onChange instead of onBlur so it doesn’t creating a jarring or surprising effect when they click away

![2020-08-21-01 11 25](https://user-images.githubusercontent.com/1233880/90871133-dff3ff80-e39a-11ea-9119-d225558f9ed8.gif)

**Improve custom amount input**

It is not immediately obvious that the custom amount input it is not editable. Perhaps we can allow users to change the placeholder and allow it to be editable.

We can also display an extra piece of text clarifying the purpose of this input as suggested by @Luchadores. For example: “This field gives your customers the possibility to enter any amount they want”.

**Comment by jeherve** [comment]
> It is not immediately obvious that the custom amount input it is not editable. Perhaps we can allow users to change the placeholder and allow it to be editable.

Here is some more feedback on this:

> Looking at the “Or enter a custom amount”, I feel like I want to click there and enter a custom amount for my visitors. I don’t get that, the input field there is already made for my visitors and I don’t have to edit it myself.

> One quick option that I had in mind, was to show the entire area grayed out, of the custom amount (like $50 in the input field). So that it’s a bit more clear, that as a user, I cannot interact with it.

------

p8oabR-za-p2#comment-4729

**Comment by dsas** [comment]
Fix decimals to max decimals allowed by currency is done, on blur it will round-up the entered number accordingly

Do not allow to enter text is done, any text is stripped on blur.

Improve custom amount input, I _think_ this is done, the amount is shown as a placeholder and the amount box isn't focusable
![image](https://user-images.githubusercontent.com/93301/172829562-08cbec4b-6b41-4738-a2bf-a997faffe0f1.png)

**Comment by Copons** [comment]
Abandoning this in favour of a block pattern approach using the revamped Payment Button block.
See: 600-gh-Automattic/dotcom-manage
