### ISSUE TITLE
Manage: Remove Plugin Update Card

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#16933]
![screen-shot-2020-07-17-at-4 41 42-pm](https://user-images.githubusercontent.com/88897/90898698-8b498800-e38c-11ea-859b-7d7a1741ba93.png)

With Core adding this functionality, until our backup/restore integrations are in place, we should remove this card to avoid confusion.

#### Steps to reproduce the issue
n/a

#### What I expected
n/a

#### What happened instead
n/a

**Comment by pablinos** [comment]
I'd missed [this feature being merged](https://make.wordpress.org/core/2020/07/15/controlling-plugin-and-theme-auto-updates-ui-in-wordpress-5-5/). Perhaps we could check for the presence of `wp_is_auto_update_enabled_for_type` and use that to determine whether to disable this UI?

**Comment by jeherve** [comment]
> Perhaps we could check for the presence of wp_is_auto_update_enabled_for_type and use that to determine whether to disable this UI?

Since that's a Core feature now, I'd be tempted to not mention the feature at all in the Jetpack dashboard, at least not until we've made some improvements to our implementation so it's better than Core's.

**Comment by pablinos** [comment]
That makes sense. I suppose I was thinking about people that were on < WP 5.5, but then any change would be in a new version of Jetpack they would need to update to also.

**Comment by allilevine** [comment]
> > Perhaps we could check for the presence of wp_is_auto_update_enabled_for_type and use that to determine whether to disable this UI?
> 
> Since that's a Core feature now, I'd be tempted to not mention the feature at all in the Jetpack dashboard, at least not until we've made some improvements to our implementation so it's better than Core's.

Should we hide the feature from the dashboard (e.g. with a feature/config flag)? Or remove it from the code entirely since it will be implemented differently if it comes back?

**Comment by jeherve** [comment]
I think it'd be safe to remove entirely. We can always pull the code back if needed later on.
