### ISSUE TITLE
Jetpack Image Optimizer Ruins Colors (RGB vs sRGB Compression)

### ISSUE THREAD

**Issue by Kantuva** [Automattic/jetpack#16939]
James Huff moderator recommended to share here as well
original link and report:
https://wordpress.org/support/topic/jetpack-image-optimizer-ruins-colors-rgb-vs-srgb-compression/#post-13239720

____________________________

Hey guys.

I am talking of this setting in particular; Speed up image load times

https://i.imgur.com/E36Af5I.png

Issue is chronic to Jetpack for what I can tell, I am using

Jetpack 8.8.1
Firefox 79.0 (latest version)
Wordpress 5.4.2

Colors when the setting is turned OFF:
https://i.imgur.com/mAijxqu.jpg

Colors when the setting is turned ON:
https://i.imgur.com/VAtZzJ7.jpg

The image above is RGB, not sRGB but Firefox processes it “correctly”, meaning that it shows it with the same degree of saturation it had when I worked with it on Photoshop CS5

Here’s a link to all the information of the image itself:
https://i.imgur.com/WvWUE4O.png

This is a direct link to the image:
http://dseverino.com/wp-content/uploads/2020/08/Sunspear-Frontiers-002.jpg

With Photoshop I re-exported the image as sRGB and this is the information of the image:
https://i.imgur.com/YjjgtGh.png

This issue happens only when using WordPress Carousel, and only when the setting above is enabled. The website thumbnails are shown on their correct colors, be them on tiled mosaic, circles, square tiles, tiled columns, default wordpress galleries or slideshows. they of course will appear in a lower resolution, but the colors are correct. So that means that Jetpack compression is somehow not affecting the colors of the Thumbnail compressed images, but it is screwing up the colors for the bigger Carousel images.

The problem appears to be that the compression system that you guys are using is forcing Firefox to load the images as the “wrong” version, which is just overall strange unexpected and inconsistent behaviour, given that when disabled Firefox handles the images flawlessly

Regards

_____________

**Comment by jeherve** [comment]
Thanks for the report. I logged it here, where we develop Jetpack's image processing tool:

https://code.trac.wordpress.org/ticket/94
