### ISSUE TITLE
Extensions: Create and move Jetpack plugins to ./plugins folder

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#16931]
There is [an issue](https://github.com/Automattic/jetpack/issues/16816) which suggests _revisit registration and directory structure_, and also, according to the Extension Type description:

> - Blocks are available in the editor itself.
> - Plugins are available in the Jetpack sidebar that appears on the right side of the block editor.

We've [created `./extended-blocks` folder](https://github.com/Automattic/jetpack/tree/master/extensions/extended-blocks) so I suggest continuing with these changes moving all plugins defined into the `./blocks` folder  such as `social-preview`, or wherever to `./extensions/plugins/social-preview` folder.

**Comment by jeherve** [comment]
Maybe this can now be closed as duplicate of #20943?

**Comment by retrofox** [comment]
let's close the newest.
