### ISSUE TITLE
Square or Circular tiled gallery thumbnails link to square image when the original is rectangular

### ISSUE THREAD

**Issue by ACEkin** [Automattic/jetpack#16940]
The following problem can be viewed when Jetpack Carousel is not used, in fact, no lightbox overlays at all. [The conversaton originally started on JP Support forum.](https://wordpress.org/support/topic/square-tile-galleries-show-square-images-2/)

#### Steps to reproduce the issue

1. Insert a tiled gallery block
2. Add vertical and horizontal images
3. Set the type to Square or Circular
4. Set the Link to the Media file
5. View the post and the square tiled gallery
6. Click on an image thumbnail to see a square image being presented rather than a vertical or horizontal rectangular one

#### What I expected
I would expect to see the original image linked with the proper aspect ratio.

Apparently, the link settings for the gallery need to be set to Media File, not to the Attachment Page. In the post, the link is indeed set to the Media file.

The post that started this all is below. But, that being a staging site, the content may disappear:
https://www.testbed.biz/tiled-gallery-samples/

You may notice another problem on that page too, but that's a different story!

**Comment by jeherve** [comment]
Also reported in #20980.

This happens because the file path uses Photon, and the size parameters are not stripped from the image link. 
When using a tiled gallery inside the classic block, the size parameters are properly removed.
