### ISSUE TITLE
(2P) Social Previews: Get all the copy reviewed and apply changes to code

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#16955]
Sidebar description, upgrade nudge.

**Comment by michelleweber** [comment]
Is there something Editorial can help with?

**Comment by getdave** [comment]
@michelleweber We have a CfT available here p58i-9k2-p2. If you follow the instructions on that you will see the content that we would appreciate Editorial takin a look at.

We'll look up the lines of code now for you for reference.

**Comment by frontdevde** [comment]
@michelleweber

 I just noticed that the above comment linked the wrong CfT. The Social Previews CfT can be found at p7DVsv-97x-p2.

If it helps, the line of copy that initially prompted us to ask for a review was `'Preview what this will look like on social networks and Google search.`.

Feedback from Editorial on this issue would be appreciated as ideally we'd love to close this one out this week. Thank you!

**Comment by obenland** [comment]
@Automattic/editorial It looks like personal pings got lost, do you think you'll have time to take a look at this?

**Comment by clucasrowlands** [comment]
Sorry to miss this earlier -- best to ping the entire team from now on.

> (edit: p7DVsv-97x-p2). If you follow the instructions on that you will see the content that we would appreciate Editorial taking a look at.

I'd prefer to preview this in the right context but I don't know what "p7DVsv-97x-p2" means. Do I need to log in somewhere else?

**Comment by obenland** [comment]
It's the shorthand for P2 posts, I'll DM a FG link with more.

**Comment by clucasrowlands** [comment]
I just have two tiny style tweaks:

> Upgrade to a Business **plan** to unlock the power of our SEO tools

Lowercase "plan"

> Customize your front page **metadata** to change how your site appears to search engines

"Metadata" is one word

Everything else looked clear to me. Thanks!
