### ISSUE TITLE
Lazy Images: consolidate package to rely on Assets package

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#16971]
Right now the Lazy Images package replicates some of the work done by other packages, such as the Assets package with `get_file_url_for_environment`. It would be nice to consolidate things to avoid duplicating code.

Related PR: #16657

cc @davidlonjon

**Comment by davidlonjon** [comment]
Hi @jeherve ,

I can a look at this next Tuesday (Sept 1st) unless someone else have a go at it before then

**Comment by davidlonjon** [comment]
Here is my attempt to implementing this requirement: https://github.com/Automattic/jetpack/pull/17045
Hopefully it is heading the right direction.
