### ISSUE TITLE
Donations block: Currency separator of modal is always a decimal.

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#16976]
In the modal popup for Stripe that opens when a donor clicks on the Donate button, the currency separator is always a decimal, even for currencies that use other symbols (like commas for Euro).

<img width="1213" alt="Screen Shot 2020-08-25 at 12 52 47 PM" src="https://user-images.githubusercontent.com/349751/91221662-d50ad900-e6d2-11ea-8f52-46af5804f43a.png">

**Comment by mmtr** [comment]
D48830-code aims to fix this.
