### ISSUE TITLE
Donations block: Stripe confirmation message isn't appropriate for donations.

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#16975]
The donations block shares the Stripe prompt with the Payments block, which came before donations. This message presumes the user is working with a Payments block, and references "making money", which may not be appropriate when accepting donations:

<img width="1184" alt="Screen Shot 2020-08-25 at 11 03 48 AM" src="https://user-images.githubusercontent.com/349751/91211449-a20d1900-e6c3-11ea-936f-29a2e7568e7f.png">

Maybe the easiest fix is to change the text to "...accepting money!", which would work for both cases.

**Comment by mmtr** [comment]
> Maybe the easiest fix is to change the text to "...accepting money!", which would work for both cases.

Yup, agree on that.

@blackjackkent or @krymson24, if you're interested, this is a relatively easy change that can continue to help get you familiar with Jetpack blocks in general and Earn blocks in particular.
