### ISSUE TITLE
Fatal error - class.jetpack.php file not found

### ISSUE THREAD

**Issue by vijayhardaha** [Automattic/jetpack#16984]
I'm using version 8.8.2 and it gives a fatal error for `class.jetpack.php` file not found

```[26-Aug-2020 02:04:04 UTC] PHP Fatal error:  require_once(): Failed opening required '/home1/{username}/public_html/wp-content/plugins/jetpack/class.jetpack.php' (include_path='.:/opt/cpanel/ea-php72/root/usr/share/pear') in /home1/{username}/public_html/wp-content/plugins/jetpack/load-jetpack.php on line 41```

**Comment by LifeIsADeflatingVest** [comment]
I'm facing the same issue.  WordPress 5.5, Jetpack 8.8.2, PHP 7.4.9

Error message: require_once(): Failed opening required '/home3/{username}/public_html/blog/wp-content/plugins/jetpack/class.jetpack.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear')

Bluehost support claims it's a "known JetPack issue", having to do with the latest Wordpress update.

**Comment by vijayhardaha** [comment]
I am trying to debug it. I am also using Bluehost. `class.jetpack.php` comes with the plugin but somehow it's getting deleted. I will update if I find anything.

**Comment by jeherve** [comment]
Your installation of Jetpack seems incomplete, you're missing some files. The `class.jetpack.php` that error refers to is part of the Jetpack 8.8.2 plugin.

Could you try to log in to your site via FTP or CPanel, delete the existing Jetpack plugin folder, and reinstall the plugin from scratch?

You'll find the Jetpack plugin folder here:
```
wp-content
   plugins
     jetpack - DELETE THIS FOLDER
```

If you're not sure how to do this, you can ask your hosting company for help. They should also have documentation explaining how to edit or remove files from your site using FTP or a File Manager in your admin panel.

Let me know how it goes.

**Comment by LifeIsADeflatingVest** [comment]
On the wordpress forum — https://wordpress.org/support/topic/jetpack-has-broken-my-site-twice/ — someone mentions:

"I have counted 7 people that have similar issues, 6 people use BlueHost and 1 uses HostGator, both are under the parent company of Endurance International Group. As a test, I utilized a site I have on GoDaddy to try and re-create the issue. My Godaddy site did not crash. So it would appear that it is something specifically happening with BlueHost and HostGator."

I doubt this could be related, but thought to bring it up.

**Comment by jeherve** [comment]
Thanks for pointing me to that thread, I'll go comment there as well to see if I can help.

It's indeed something that can come up. It happens on some sites on plugin updates, regardless of where the site is hosted and regardless of the plugin.

When a plugin is being updated on your site, a zip archive of the new plugin version is downloaded, and then that zip is uncompressed and the new files are moved to their new location in the `wp-content/plugins` directory on your hosting plan. Sometimes, and especially on sites with limited resources and for large plugins with a lot of files, some files are left behind during that process, thus creating those issues.

Re-installing the plugin from scratch should solve the problem.

Could you both let me know if that solves the issue for you?

**Comment by LifeIsADeflatingVest** [comment]
I compared my existing jetpack folder with the downloaded one, and the only meaningful difference (minus changelog etc) is the absence of the class.jetpack.php file. I copied it and reactivated the plugin. Seems to work now. 

Of course, this doesn't quite explain how the file was deleted in the first place. The last update was many days ago, this doesn't feel like a plugin update issue (otherwise how come the plugin worked for a whole week withoug the class.jetpack.php file?)

**Comment by jeherve** [comment]
@LifeIsADeflatingVest It would be interesting to know if your installation included a `quarantine.class.jetpack.php.[randomnumbers]` file, as mentioned by somebody else on the support thread; this would indicate that, just like this other person, something on your WordPress installation or hosting plan is flagging the `class.jetpack.php` file as malicious and renaming it.

**Comment by LifeIsADeflatingVest** [comment]
Yeah, I noticed it on the support thread. In my case, there was no such file (i.e. `quarantine.class.jetpack.php`)

If I recall correctly, the only modification between the last JetPack update (which, again, was several days ago) and the issue was updating PHP to 7.4.9, updating the Yoast plugin, and adding the W3 Total Cache plugin some days ago.

I don't see how any of these could cause the deletion of the `class.jetpack.php` file and, in any case, the site has been working fine for two or three days since the modifications above (with the exception of Yoast, which I think was yesterday).

Oh well, things happen. Let's keep an eye on this! Thanks for your help.

**Comment by LifeIsADeflatingVest** [comment]
**Update:**
The problem returned. 
The file `class.jetpack.php` is once again deleted. More mindbogglingly, I had saved a back file of the file (named `BACKUP_class.jetpack.php`) and now this is deleted as well.

Does the plugin scan and make alterations to its root directory (plugins/jetpack)? I can't understand this behavior.

**Comment by jeherve** [comment]
Interesting. That seems to be what's happening to others hosted with BlueHost at the moment. Something is deleting the `class.jetpack.php`.

> Does the plugin scan and make alterations to its root directory (plugins/jetpack)?

The Jetpack plugin does not have that kind of permissions on your site. Something else must be at play here.

Do you use any other security plugin, or any security service via your Bluehost account?

**Comment by LifeIsADeflatingVest** [comment]
No security plugin. The only new plugin (I installed it about 4-5 days ago) is W3 Total Cache, which really shouldn't be relevant. All the rest of my (very few) plugins I've been using for a long time, and — with the exception of Yoast — are minor functionality plugins (reading progress, tooltips, etc). I'd be happy to offer a complete list, of any other information, if it would help

**Comment by jeherve** [comment]
Thank you. Do you think you could reach out to BlueHost to let them know about this? I have reached out on my end, and will comment here again once I get a reply.

In short, it would be good if they could let us know if there is any system / service in place that scans and deletes files from sites, and if they don't know of one, if there is any security log from your site that you or they could check to find out more about what happened.

**Comment by LifeIsADeflatingVest** [comment]
I contacted them earlier, looking for help with the issue. They told me it's a "known JetPack issue" (implying they've been contacted by other users), but —at least at that point —they suggested contacting JetPack for help troubleshooting it.

I could of course try again. I can report back if I learn anything.

**Comment by LifeIsADeflatingVest** [comment]
Unfortunately I can't get to Bluehost tech support at the moment — they're likely swamped with requests, I've never seen the Bluehost tech support so busy.

Following some of the messages on the support thread, it seems as if there is some functionality within some system that alters the plugins/jetpack directory. The reasons _might_ be related to some perceived issue (security or incompatibility).

Although you can never be certain, I'd assume that if that system belonged to Bluehost, their tech support should be aware of it. Judging by the replies given to other users, I'm not sure that's the case. Then again, I'm out of ideas regarding what system that could be. And how come it didn't show up earlier (e.g. when the update came out)?

This is utterly baffling.

**Comment by jeherve** [comment]
I've contacted BlueHost as well, and I'll update this issue as soon as I get a reply from them; hopefully it will shed light on what's causing this problem.

**Comment by ashraf20078** [comment]
Solved!
Hi Every One
Today I was Facing Same Problem on Bluehost
The soluition i did :
Go to > Cpanel > File Manager > wp-content/plugins/
Delete Jetpack Folder
Download The Zip File https://downloads.wordpress.org/plugin/jetpack.8.8.2.zip
Then Go To Cpanel > File Manager > wp-content/plugins And Upload The File jetpack.8.8.2.zip
Then Right Click On The File And Select "Extract"
To See The Folder same This > wp-content/plugins/jetpack
Fastly Go To Installed Plugins > jetpack settings > Disable Brute force attack protection
Done.
Now My Site Is Working Very Good.

**Comment by LifeIsADeflatingVest** [comment]
Is it still working? Because I've tried variations of what you're describing, and the file is eventually deleted.

Is there *still* no word from Bluehost on this? Their silence is deafening…

**Comment by jeherve** [comment]
> Is there still no word from Bluehost on this?

They're still looking into the issue, and will update us as soon as they find out what's happening.

**Comment by jeherve** [comment]
<strong>I have good news!</strong>

Bluehost found out which of their internal scans was removing the file, and fixed it. The problem should now be solved. 

You should be able to re-install Jetpack now, the file should not get removed again.

<strong>Note:</strong> If you had only deactivated Jetpack via WordPress' recovery mode, you'll want to delete the plugin, and then re-install it from scratch.

If any of you still experience issues with a fresh installation of Jetpack, let us know!

**Comment by ashraf20078** [comment]
Now Its Working Very Good On Bluehost.
Thank You Very Much @jeherve
