### ISSUE TITLE
Earn Block: Incorrect Minimum Stripe Currency Threshold for Donations

### ISSUE THREAD

**Issue by krymson24** [Automattic/jetpack#16992]
A donations block currently does not use the correct Stripe currency threshold minimum when a user is submitting a donation.
#### Steps to reproduce the issue

* Set up a test site:
  * Use your sandboxed website
  * Sandbox the API, the store and `subscribe.wordpress.com` (see PCYsg-lW4-p2 #sandbox-method for detailed instructions).
  * Make sure you have a Premium or Professional plan.
* Go to Posts > New and insert a new Donations block.
* Set up the Stripe connection (you will be able to see a link above the form letting you to skip and instantly create a test account).
* Go back to the editor and modify the donations block to use Euros
* Ensure your site is public
* Publish the post and visit it.
* Enter a custom donation amount above 0.5 Euros and below 5 Euros. When the donation pop-up shows up, confirm the donation amount.

#### What I expected
The donation goes through without any errors.

#### What happened instead
An error was displayed mentioning that the amount was below the threshold.

**Comment by mmtr** [comment]
Changes in D48642-code should fix this

**Comment by mmtr** [comment]
Closing this one out since D48642-code has landed.
