### ISSUE TITLE
Instant Search: issues updating Jetpack Search Widget

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#17000]
This happened on my personal site, `53262711`.

My existing Jetpack Search widget has 3 filters added. I wanted to add a fourth one.

#### Steps to reproduce the issue

1. Go to Appearance > Customize > Widgets
2. Open the Jetpack Search sidebar area.
3. Open the Search (Jetpack) Widget in there.
4. Add a new filter using the button at the bottom.
5. Watch the `update-widget` ajax call fail: `{"success":false,"data":"widget_setting_too_many_options"}`

![image](https://user-images.githubusercontent.com/426388/91453100-a2521380-e87f-11ea-907e-31ad030da9df.png)

Here is the form data:

```
action: update-widget
wp_customize: on
nonce: xxx
customize_theme: twenty-jeremy
customized: {}
widget-jetpack-search-filters[5][title]: 
widget-jetpack-search-filters[5][filter_type][]: taxonomy
widget-jetpack-search-filters[5][taxonomy_type][]: trakt_genre
widget-jetpack-search-filters[5][date_histogram_field][]: post_date
widget-jetpack-search-filters[5][date_histogram_interval][]: month
widget-jetpack-search-filters[5][filter_name][]: 
widget-jetpack-search-filters[5][num_filters][]: 5
widget-jetpack-search-filters[5][filter_type][]: taxonomy
widget-jetpack-search-filters[5][taxonomy_type][]: trakt_show
widget-jetpack-search-filters[5][date_histogram_field][]: post_date
widget-jetpack-search-filters[5][date_histogram_interval][]: month
widget-jetpack-search-filters[5][filter_name][]: 
widget-jetpack-search-filters[5][num_filters][]: 5
widget-jetpack-search-filters[5][filter_type][]: date_histogram
widget-jetpack-search-filters[5][taxonomy_type][]: category
widget-jetpack-search-filters[5][date_histogram_field][]: post_date
widget-jetpack-search-filters[5][date_histogram_interval][]: year
widget-jetpack-search-filters[5][filter_name][]: 
widget-jetpack-search-filters[5][num_filters][]: 5
widget-jetpack-search-filters[5][filter_type][]: taxonomy
widget-jetpack-search-filters[5][taxonomy_type][]: category
widget-jetpack-search-filters[5][date_histogram_field][]: post_date
widget-jetpack-search-filters[5][date_histogram_interval][]: month
widget-jetpack-search-filters[5][filter_name][]: 
widget-jetpack-search-filters[5][num_filters][]: 5
widget-id: jetpack-search-filters-5
id_base: jetpack-search-filters
widget-width: 250
widget-height: 200
widget_number: 5
multi_number: 
add_new: 
customize_preview_nonce: xxx
```

**Comment by jsnmoon** [comment]
I tried reproducing this issue without much success; here's what I've learned so far:

- The error originates from [the call_widget_update function](https://github.com/WordPress/WordPress/blob/56c162fbc9867f923862f64f1b4570d885f1ff03/wp-includes/class-wp-customize-widgets.php#L1471), which checks if it's updating more than one option. 
- A widget's `update` function is responsible for determining the value saved into the widget's option value.
- The Search widget's [`update` function](https://github.com/Automattic/jetpack/blame/master/modules/widgets/search.php#L638) appears to be properly formed. Calling `add_option` or `update_option` here would be an easy way to trigger the `widget_setting_too_many_options` error, but we don't invoke either functions here.

@jeherve: Would it be possible to figure out which extraneous option is being updated in addition to the widget option? I think this should be possible if we print some debug lines before the `widget_setting_too_many_options` error is invoked in `class-wp-customize-widgets.php`.

**Comment by jeherve** [comment]
Looks like it's trying to update 2 different options, `widget_jetpack-search-filters` and `jetpack_log`.

While I was looking at the log, I also saw this notice:
```
[29-Oct-2020 16:22:51 UTC] PHP Notice:  Undefined index: sort in wp-content/plugins/jetpack-dev/modules/widgets/search.php on line 644
```

**Comment by jsnmoon** [comment]
`jetpack_log` is being updated [here](https://github.com/Automattic/jetpack/blob/e940e90c3f26a6f24f8e7fccd72a1dd6360be2b5/class.jetpack.php#L3424). I'll take a closer look at this tomorrow, but it looks like we might be calling `Jetpack::log( ... )` while executing `call_widget_update` for some reason.

**Comment by jsnmoon** [comment]
I'm at a bit of a loss as to how to fix this issue. Do you have any ideas, @jeherve?

**Comment by jeherve** [comment]
Since it only happens to me on a test site of mine, and I can't really explain why this is happening, I'm okay closing this as wontfix. If this happens to somebody else we can reopen.

Maybe that's something like this triggering it?
https://github.com/Automattic/jetpack/blob/23370f719e46cf49993b085fe0ebd41e2c96dbb0/modules%2Fcustom-css%2Fmigrate-to-core.php#L19
