### ISSUE TITLE
Search: Add the dropdown type for filters

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#17005]
#### Is your feature request related to a problem? Please describe.

Currently, Jetpack Search overlay is showing only checkboxes for filters. 
However, it's not convenient if each filter has many options.

#### Describe the solution you'd like

It would be great if we can let site owners choose between checkbox vs dropdown.

#### Additional context

From 3241955-zen

**Comment by gibrown** [comment]
Can you describe this a little more? Do you mean when configuring the filters, or on the front end?

**Comment by pranali333** [comment]
Thanks for checking!
Yes, on the front end here: https://d.pr/i/O9xPsX
If each filter has too many options, it will be difficult to manage.
Thanks!

**Comment by gibrown** [comment]
Cool that was what I was guessing. I'm going to close this in favor of https://github.com/Automattic/jetpack/issues/9682 which is pretty similar. Thanks!
