### ISSUE TITLE
Mark some debug data as private in Site Health

### ISSUE THREAD

**Issue by Clorith** [Automattic/jetpack#17007]
Jetpack makes great use of the Site Health component in WordPress core, but some of the information it provides is not ideal for public sharing.

This is fine when a Jetpack user looks for Jetpack support, and they can then be directed to post it privately, or informed of what might be considered sensitive, but if they are looking for help from another plugin or theme, they won't have this information up front.

The information that shouldn't be shared publicly that is very obvious to me:
- `master_user`
- `current_user`
- `HTTP_CF_CONNECTING_IP`
- `HTTP_X_FORWARDED_FOR`
- `REMOTE_ADDR`

The users contain both a username and an email address, since a public posting of emails on WordPress.org is discouraged by the guidelines there, even though an email address in it self isn't security related, this should probably be marked as private.

There may be other items I'm not familiar with that could be considered private, but I'm not familiar enough with the data here to know what they might be, but this ticket would serve as a great place to outline what fields that may be if any.

The IP addresses, although not a very private matter by them selves, if the wrong person reveals their address, that information may be used by those with ill intent.

#### Describe the solution you'd like
Implementing the `private => true` flag on sensitive data fields will keep it away from the easy copy-paste interface, and the users would need to provide that information manually (if Jetpack needs that info, it adds a small hurdle, but given the size of the ecosystem, it would be an overall win).

**Comment by jeherve** [comment]
cc @kraftbj who originally worked on #12247.

**Comment by kraftbj** [comment]
Thanks for raising the issue. I'll look into this.

**Comment by kraftbj** [comment]
The e-mail addresses are a quick win. Going to drop those ( 16b0542c88fbe58ee9ebbdf67a3aaed0a228cd4f ). The IP addresses are a bit harder as we need them more often in debugging.

In thinking more about this, I'd almost want Core to offer a third state :). "Private" -- make it hard to share. "Reserved" and "Public". Public would be what is safe for forums. Reserved is what is okay for support staff, but not something you'd want the world to see.

The difference between Private and Reserved would be API keys. Jetpack support doesn't need to see any API keys usually and definitely not API keys that we don't provide. Likewise, other support shops would not need to see any Jetpack/Akismet API keys.

Reserved would be items, like the IP addresses, that wouldn't be good for the world to see, but okay for a support shop to see. The copy/paste button would turn into two "Copy debug details for a public forum" "Copy debug details for private support" (or something like that).

I need to think a bit more on the best way to handle this.

**Comment by kraftbj** [comment]
In discussing this with JP Happiness, they can make a tweak to their language on requesting debug data when someone has contacted us via a private support route. My ideological dream aside, I'll mark the server variable fields as private (where the IP addresses are included).
