### ISSUE TITLE
External Media: Show descriptive error on failure to upload

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/jetpack#17010]
**builds on https://github.com/Automattic/jetpack/pull/16986**

#### Steps to reproduce the issue
With the introduction of https://github.com/Automattic/jetpack/pull/16986, using external media (google photos, pexels) to upload an image will now do a space check and return errors if for example not enough space is available. This is in contrast to previous behaviour which would let all uploads from external media pass.

* Go to /wp-admin/options.php of your sandbox
* Change the `blog_upload_space` value to 1 (1mb). Be careful to note down the previous value
* Go to https://wordpress.com/media/ of that site
* You should be seeing that you are over the limit (if not, try uploading something)
![](https://cln.sh/MsrMmR+)
* In a new post, create an `Image` block and try to upload an image from google photos or pexels by clicking `Select Image` and the respective source.
* Upload a new image through google photos or pexels, thus triggering the `rest_upload_user_quota_exceeded` error

Don't forget to revert after testing
* Go to `/wp-admin/options.php` of your sandbox
* Change the `blog_upload_space` value to what you have noted before

#### What I expected

* You should get a descriptive error like `1 file could not be uploaded because you have reached your plan storage limit.` 

#### What happened instead
* Even though the response contains the correct error, a generic error is returned
![](https://cln.sh/0LfYg1+)

**Comment by cpapazoglou** [comment]
The response has 200 OK http code, but `apiFetch` reports an error
https://github.com/Automattic/jetpack/blob/4c01799bc83324e027a4c237ba0b4bb0daac378e/extensions/shared/external-media/sources/with-media.js#L233

**Comment by obenland** [comment]
Let's prioritize this for this iteration, since we introduced #16986 this week as well
