### ISSUE TITLE
Sharing: sharing counts not showing after update to master

### ISSUE THREAD

**Issue by jessefriedman** [Automattic/jetpack#1702]
After updating jes.se.com to Master (latest commit is: https://github.com/Automattic/jetpack/commit/d396079f89e402de4610dccd8ac7e488288b6a8f), the share icons at the bottom of the posts lost their counts. 

https://cloudup.com/ciKv7wc9Dlc

After working with @jeherve he found issues with the commits below. Jeremy advised: 
git checkout febfeece3968559062bbe0fd9e9465c128debdbf modules/sharedaddy/sharing.js which solved the problem.

https://cloudup.com/cdj-hNkgwns

https://github.com/Automattic/jetpack/commit/8efa2d65dee6d3d47a7c17e14829871d5997bd6e#diff-4bcbd547825fca0edbbc4cd432fffda8
https://github.com/Automattic/jetpack/commit/fb4e0bc337306be8fd895b62cbb0dfb72df3d4bd#diff-4bcbd547825fca0edbbc4cd432fffda8
https://github.com/Automattic/jetpack/commit/9d89a0161b1a44b07234e45c636e30b3df1a11e7#diff-4bcbd547825fca0edbbc4cd432fffda8 (edited)

cc @georgestephanis

**Comment by georgestephanis** [comment]
Yup, I need to find which change did it.  There were a lot of small things.

If you could do some testing to isolate it, it would be helpful.
