### ISSUE TITLE
Poor quality of images with Jetpack site accelerator, users can't read text on images

### ISSUE THREAD

**Issue by sarangsss29** [Automattic/jetpack#17023]
So I have enabled Jetpack Photon or Site accelerator / and the images are so poor quality that users can't even read the text on them and distinguish what's is the image about. When I upload the images they are high quality and already optimized/compressed for viewing. But Jetpack compresses them so much that one can't even see it. 
Here is an example of the images in a gallery or caurosel on this pagehttps://www.androidsage.com/2020/08/17/oxygen-os-11-enables-dual-sim-5g-for-both-slots/

Loo at the screenshots:
https://app.box.com/s/zfm986y5ncoh5j0h7gr5n2ep9zitm1gc
https://app.box.com/s/xm7s4mbuebgioll7m6o4fxjxyhrmit19

Looks quite low quality, especially on mobile. It is also unreadable on desktop. 
Look at the quality I uploaded!
https://www.androidsage.com/wp-content/uploads/2020/08/OnePlus-8-Pro-dual-sim-5g-feature-with-oxygen-os-11.jpg

Yes, I know that there is a link at the bottom to see the actual image but that's not quite ideal for a reader and also the option does not show up on mobile.

**Comment by jeherve** [comment]
I see you've found the original issue where this is being tracked: #14113 

I'll close your issue in favor of the other one.
