### ISSUE TITLE
Pay with Paypal: New lines in Description field

### ISSUE THREAD

**Issue by devNigel** [Automattic/jetpack#17035]
#### Is your feature request related to a problem? Please describe.
The description field in Pay with Paypal block moves to new line on press of `Enter` key.

However, on the rendered page, there are no line breaks. **This is misleading and gives false expectations to the user.**

![image](https://user-images.githubusercontent.com/33957570/91764498-09abf280-ebf5-11ea-8469-151d25c3f451.png)

#### Describe the solution you'd like
The rendered description filed should be able to show new lines. Alternatively, show a tooltip or nudge in the Pay with Paypal block informing about the `<br>` tag.

#### Describe alternatives you've considered
A workaround is to use `<br>` tag. However, **an average user would not be familiar with such tags.** 

#### Additional context

Rendered element:
![image](https://user-images.githubusercontent.com/33957570/91765140-1da42400-ebf6-11ea-86e7-9aaaa2051484.png)

**Comment by tbradsha** [comment]
I ran across a case where there was a large description using `<br>` to format; they then were able to use the the shortcode to include the same content in widgets and other pages. It'd be great if basic formatting (e.g. newlines) were supported in this block.

On that note, it seems now that `<br>` is no longer working; it's being treated as literal chars instead of a tag.

**Comment by pauljacobson** [comment]
We have another instance of this here: 24696753-hc

**Comment by htdat** [comment]
Maybe relate to https://github.com/Automattic/jetpack/issues/17576

**Comment by sdixon194** [comment]
26114821-hc

**Comment by synora** [comment]
@apeatling can you add this to the View team's board? ([#](https://a8c.slack.com/archives/C02FMH4G8/p1607110901210100?thread_ts=1607107806.206800&cid=C02FMH4G8))

**Comment by eoinsav** [comment]
Another report: #27493662-hc

**Comment by carinapilar** [comment]
Another one on 3619036-zd-woothemes - the user shared that they always used the `<br>` tag, and it stopped working. It seems to only be working now if you add directly to the code editor.
