### ISSUE TITLE
Cannot log in 

### ISSUE THREAD

**Issue by acr1618** [Automattic/jetpack#17041]
#### Steps to reproduce the issue

1. Go to https://criticadaeconomia.com/wp-admin/admin.php?page=jetpack#/
2. Click on Configurar o jetpack
3. Click on Continue with google 
4 or Click on Continue with Wordpress
4. Choose an account

#### What I expected
I expected to be logged in and have acces to configuration

#### What happened instead
The login window closes and nothing happens. No login, no configuration.

**Screenshots**
![image](https://user-images.githubusercontent.com/11392990/91786501-a96e7e00-ebff-11ea-81ab-2952cca2ef8c.png)
![image](https://user-images.githubusercontent.com/11392990/91786535-be4b1180-ebff-11ea-8b29-3ea80cb42daf.png)
![image](https://user-images.githubusercontent.com/11392990/91786546-c440f280-ebff-11ea-9602-d04305f21cb2.png)
![image](https://user-images.githubusercontent.com/11392990/91786576-d589ff00-ebff-11ea-9973-9f44809d1edb.png)

**Comment by jeherve** [comment]
Could you try in a different browser, such as Firefox or Safari, and let us know if that helps?

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
