### ISSUE TITLE
Broken links on Jetpack modules page

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/jetpack#17040]
#### Steps to reproduce the issue

1. Go to /wp-admin/admin.php?page=jetpack_modules
2. Click on "Asset CDN" or "Image CDN"
3. Get redirected to https://jetpack.com/support/asset-cdn?site=www.xyz.com or https://jetpack.com/support/photon?site=www.xyz.com
4. See 404 error

#### What I expected
Help documentation

#### What happened instead
Error

**Comment by jeherve** [comment]
Thanks for the warning! This should be fixed now.
