### ISSUE TITLE
Monitor: Include Site ID in the e-mail

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#1705]
In the event of oddities with the Monitor e-mails, it would helpful for HEs to know exactly the Site ID generating the Monitor alerts.

**Comment by kraftbj** [comment]
I'm thinking something at the end of the e-mail: "If you need to contact support regarding this e-mail, please include Site ID xxxxx in the message", etc. 

The problem, on our end, is when someone changes the URL and it doesn't flow up to us, the site we search for and/or see displayed in the NA might be one URL, while the home/site URL within the site settings indicate another. It makes it easy for us to tell someone something regarding site A when site B is problematic.

**Comment by georgestephanis** [comment]
cc: @lezama -- probably a quick fix.  Maybe just include it in the footer so if they reply/fwd the email, it gets included automatically?

**Comment by zinigor** [comment]
Added in r119094
