### ISSUE TITLE
Stats: staging mode does not prevent sending stats.

### ISSUE THREAD

**Issue by zinigor** [Automattic/jetpack#17052]
#### Steps to reproduce the issue

1. On your testing site confirm that your site sends visits information by confirming that the following script gets loaded:
```
<script type='text/javascript' src='https://stats.wp.com/e-202036.js' async='async' defer='defer'></script>
<script type='text/javascript'>
	_stq = window._stq || [];
	_stq.push([ 'view', {v:'ext',j:'1:9.0-alpha',blog:'YOURBLOGID',post:'POSTID',tz:'3',srv:'YOURDOMAIN'} ]);
	_stq.push([ 'clickTrackerInit', 'YOURBLOGID', 'POSTID' ]);
</script>
```
This script is for tracking a blog, a page view can be different. Keep in mind that stats are not sent for logged in administrators by default.
2. Add a constant to enable staging mode `define('JETPACK_STAGING_MODE', true );`
3. Try to load a page that sent visit information in step 1 again.

#### What I expected
I expected no stats to be sent.

#### What happened instead
I see stats sent using the same script, increasing the views count.

**Comment by mdbitz** [comment]
https://github.com/Automattic/jetpack/pull/17063 --> is ready for review that disables rendering of stats code if site is in staging mode.
