### ISSUE TITLE
Stats: issues accessing wp-admin stats after 8.9 update

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#17053]
Following #16727 and #16716, some site owners are currently seeing the following error when trying to access stats in wp-admin:

> You are not a member of this site.
>
> If you have just installed the WordPress.com Stats plugin, this error probably appeared because the API key entered in the plugin belongs to a different WordPress.com user account.
>
> The owner of the API key must visit this site’s stats page to grant access.

Disconnecting / reconnecting fixes the issue.

----

Initial report:
https://wordpress.org/support/topic/jetpack-stats-missing-4/#post-13350471

**Comment by chaselivingston** [comment]
3280412-zen

**Comment by joendotcom** [comment]
3376213-zen

**Comment by StefMattana** [comment]
Just noting that the user in 3376213-zen still has this issue despite they reconnected and also reinstalled Jetpack. 
Stats in Calypso are looking fine. 

Is there anything I can ask the user to check from their end? DB green: https://tools.jetpack.com/debug/?url=https://www.portalmie.com

I asked to flush the cache and try another reconnection just in case, meanwhile.

**Comment by jeherve** [comment]
@leogermani Do you think you could take a look?

Thank you!

**Comment by gaurav1984** [comment]
From the user in 3376213-zen

I solved the problem by installing the Enable jQuery Migrate Helper plugin
https://wordpress.org/plugins/enable-jquery-migrate-helper/

**Comment by jeherve** [comment]
Closing this as it hasn't come up much since immediately after the update.

**Comment by leogermani** [comment]
I'm sorry to get that late to the party, but for the record and future readers: this error will also happen if, for any reason, the WPCOM site does not have a valid WPCOM user configured as its owner.
