### ISSUE TITLE
Widget Visibility / Widgets: ensure compatibility with Gutenberg 8.9 

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#17062]
Gutenberg 8.9 enables the block-based widgets screen for all plugin users:
- https://github.com/WordPress/gutenberg/pull/24843

The feature is still experimental, but should ship with WordPress 5.6.

Let's ensure that:

- [ ]  all our Extra widgets are compatible with the new interface.
- [ ]  We add the Widget Visibility interface to the new interface.

Current work:
- #17413

**Comment by davemart-in** [comment]
@sirreal I'm wondering if this project would be a better fit for Good Mountain? Is this something that your team can take on?

**Comment by sirreal** [comment]
> I'm wondering if this project would be a better fit for Good Mountain? Is this something that your team can take on?

I think the teams that work on or own these features need to handle this. We can't be responsible for making sure all features are up to date with the latest Gutenberg features. We will do our best to communicate about and support those efforts, although @jeherve is already doing a stellar job of being on top of these things 🙇‍♂️ 

For the time being, we've disabled the widget screens on WordPress.com. We're happy to coordinate with teams for testing and planning to activate the feature when we're ready (assuming there continue to be filters to disable the feature in Gutenberg and Core).

@davemart-in I'll remove this from the Good Mountain board.

**Comment by jeherve** [comment]
This was also brought up in the Gutenberg repo:
https://github.com/WordPress/gutenberg/issues/25836

**Comment by georgestephanis** [comment]
Relevant discussion in #core-restapi as well today -- https://wordpress.slack.com/archives/C02RQC26G/p1602181082183400

**Comment by jeherve** [comment]
closing in favor of #20057.
