### ISSUE TITLE
Move Related posts to a different position within the content

### ISSUE THREAD

**Issue by doug-bside** [Automattic/jetpack#17067]
#### Is your feature request related to a problem? Please describe.
Most readers do not read or scroll to the end of the article. We would like to display related posts earlier so that readers can read and potentially click to additional content earlier.

#### Describe the solution you'd like
The option to position the related posts somewhere within the content, as a percent or after X number of paragraphs.

#### Describe alternatives you've considered
No alternatives have been considered

**Comment by jeherve** [comment]
You have two different ways to position the Related Posts somewhere within your post content:

- You can use [the Related Posts block](https://jetpack.com/support/jetpack-blocks/related-posts-block/) anywhere within your post's content, and it will replace the related posts displayed at the bottom of the post.
- You can remove the related posts from the bottom of your posts, add them back anywhere within the post content programatically or via a shortcode, as explained [here](https://jetpack.com/support/related-posts/customize-related-posts/#delete).

**Comment by doug-bside** [comment]
Thank you Jeremy, but we don't want to add it manually. We would like it to
be automated.

**Comment by doug-bside** [comment]
Sorry, I see what you mean about inserting it programmatically, but we
don't have the ability to change the functions file.

**Comment by doug-bside** [comment]
Thanks for your help :)

**Comment by doug-bside** [comment]
Oh, never mind again. We can write a plugin. Thanks.
