### ISSUE TITLE
Shortcode embeds on HTTPS

### ISSUE THREAD

**Issue by theukedge** [Automattic/jetpack#1707]
I just noticed that my HTTPS site had a mixed content warning. I traced it back to me having embedded a TED talk in one of my posts using the [ted] shortcode. Evidently, the freeze frame used in that embed is only delivered over HTTP, even when the page/site you're embedding on is HTTPS. I'm not sure if this is just limited to the [ted] shortcode, but you can see it in action [on my site](https://www.davidclements.me/2015/02/18/ricardo-semlers-take-on-corporate-democracy/) and even [on wordpress.com](https://en.support.wordpress.com/videos/ted-talks/)

**Comment by georgestephanis** [comment]
Interesting.

It looks like the video iframe itself is loaded over https, so it's up to the folks over at TED that goofed and are serving up a http image.

Not much we can do about that, I'm afraid. :\

**Comment by theukedge** [comment]
Thanks for looking into it. I'll contact TED and see if they can do anything about it.
