### ISSUE TITLE
Form Block: icon color changes broke the main Form view

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#17089]
In #15311, we changed the color of all block icons. This appears to have broken the form block.

#### Steps to reproduce the issue

1. Start with a site running Jetpack's `master`.
2. Go to Posts > Add New
3. Add a Form block (not a form block variation, just the main form block).
4. You'll get the following error:

![image](https://user-images.githubusercontent.com/426388/92373431-9a576680-f0fe-11ea-8f09-2dfcded7f2a8.png)

https://reactjs.org/docs/error-decoder.html/?invariant=31&args[]=object%20with%20keys%20%7Bsrc%2C%20foreground%7D&args[]=

```
Objects are not valid as a React child (found: object with keys {src, foreground}). If you meant to render a collection of children, use an array instead.
```

**Comment by jeherve** [comment]
cc @keoshi and @scottsweb

**Comment by keoshi** [comment]
Looking into this right now.
