### ISSUE TITLE
CSS Tidy: add clip-path

### ISSUE THREAD

**Issue by kristarella** [Automattic/jetpack#17106]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/clip) the `clip` property has been deprecated for `clip-path`, but we don't support `clip-path` in custom CSS.

Can we please add this property to the allowed CSS?

related ticket 3294186-zen

**Comment by pauljacobson** [comment]
@jeherve Is this an involved change to make? I needed to use Custom CSS with this property to overcome an issue in the block editor for a user where the rendered page didn't circle crop images correctly.

I'm sure the team has about a billion tasks, but adding this property could be a huge benefit for HEs trying to work around what seems to be a block editor styling issue.

**Comment by jeherve** [comment]
> Is this an involved change to make?

I can't really say for sure without testing, but it should be as straightforward as adding the new property to the list of properties we support. #15044 is a good example of how that's done.

**Comment by pauljacobson** [comment]
Thanks @jeherve. If it would help, I can try my hand at submitting a PR (if I can figure out which file to work on)?
