### ISSUE TITLE
Site Icon: Add more tags for increased compatibility

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#1715]
[RealFaviconGenerator.net](http://realfavicongenerator.net/) is the most comprehensive tool I've found for generating favicon tags. An example of what it creates for you:

```HTML
<link rel="apple-touch-icon" sizes="57x57" href="apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="manifest.json">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-TileImage" content="mstile-144x144.png">
<meta name="theme-color" content="#ffffff">
```
A walkthrough of why all of these tags are needed is [in their FAQ](http://realfavicongenerator.net/faq). As it stands now, the Site Icon module only generates three tags:

```HTML
<link rel="icon" href="http://example.com/wp-content/uploads/2015/03/Screen-Shot-2015-03-06-at-1.55.06-PM-54f9f895v1_site_icon-32x32.png" sizes="32x32" />
<link rel="apple-touch-icon-precomposed" href="http://example.com/wp-content/uploads/2015/03/Screen-Shot-2015-03-06-at-1.55.06-PM-54f9f895v1_site_icon-128x128.png">
<meta name="msapplication-TileImage" content="http://example.com/wp-content/uploads/2015/03/Screen-Shot-2015-03-06-at-1.55.06-PM-54f9f895v1_site_icon-128x128.png"/>
```

 Jetpack should consider adding whatever tags we're missing for the sake of completeness.

**Comment by aheckler** [comment]
Related to #1279

**Comment by samhotchkiss** [comment]
Sounds like a good idea, @aheckler!

One potential gotcha-- the largest version we currently serve is 128x128, but these go up to 192x192 -- do we keep a large enough copy to be able to upscale?

**Comment by aheckler** [comment]
I believe the module won't accept images less than 512x512, so upscaling shouldn't be necessary.

**Comment by samhotchkiss** [comment]
Fantastic!  Would you want to work on a PR, @aheckler?  I'm happy to review it for you.

**Comment by aheckler** [comment]
Will do.

**Comment by aheckler** [comment]
I think we can strike a happy medium between our current (very basic) device support and supporting ALL THE THINGS by using the second example provided [here](https://css-tricks.com/favicon-quiz/) under "Example 2: Medium support". 

This would support:

- IE11+
- Chrome
- Google TV
- Safari
- iOS + Touch icons + full Retina support
- Android Chrome

Ideally we could support past versions of IE, but that requires creating `.ico` files I believe, which Jetpack currently doesn't do. 

I can also add some basic Win 8 tile support using this page: http://www.buildmypinnedsite.com/en

**Comment by samhotchkiss** [comment]
> Ideally we could support past versions of IE, but that requires creating .ico files I believe, which Jetpack currently doesn't do.

Yeah, I don't know that we want to get in to converting image formats :-/

**Comment by RehanSaeed** [comment]
Windows 8/8.1/10 can display items from your RSS/Atom feed on the tile. Are there any plans to add this functionality? You can check out http://www.buildmypinnedsite.com to find out how to do it but it's a single new meta tag:

```
<meta name="msapplication-notification" content="frequency=30;polling-uri=http://notifications.buildmypinnedsite.com/?feed=http://rehansaeed.co.uk/feed&amp;id=1;polling-uri2=http://notifications.buildmypinnedsite.com/?feed=http://rehansaeed.co.uk/feed&amp;id=2;polling-uri3=http://notifications.buildmypinnedsite.com/?feed=http://rehansaeed.co.uk/feed&amp;id=3;polling-uri4=http://notifications.buildmypinnedsite.com/?feed=http://rehansaeed.co.uk/feed&amp;id=4;polling-uri5=http://notifications.buildmypinnedsite.com/?feed=http://rehansaeed.co.uk/feed&amp;id=5; cycle=1"/>
```

Also you should consider moving to using a browserconfig.xml for Windows support rather than loads of meta tags. People not using Windows 8 and above will not need to download the extra tags. See https://realfavicongenerator.net/blog/more-browserconfig-xml-less-html/ for more information.

**Comment by kraftbj** [comment]
@RehanSaeed -- I see this as a separate issue from the Site Icon subject of this ticket. I ported your comment over to a new ticket at #2204 so each conversation can be self-contained.

**Comment by kraftbj** [comment]
Noting that we should watch Core and proceed in a harmonious way: https://core.trac.wordpress.org/ticket/16434

**Comment by aheckler** [comment]
First peek at the API that core will be using: https://make.wordpress.org/core/2015/07/27/site-icon/

**Comment by dereksmart** [comment]
Site icon is now handled in core
