### ISSUE TITLE
Instant Search: if a Chrome autocomplete suggestion is used, search input cannot be submitted

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#17162]
#### Steps to reproduce the issue

1. In Google Chrome, go to a site with Jetpack Instant Search enabled, using the 'when results are ready' overlay trigger
2. Enter your search query and visit the results
3. Repeat step 2, but this time choose the query from Chrome's suggestions (see video)
4. Notice that you can't submit the form

#### What I expected

When choosing an auto-complete suggestion from my browser, I should be able to search using that suggestion.

#### What happened instead

I was unable to search without clearing the search input and typing the query again.

![2020-09-15 12-21-56 2020-09-15 12_22_22](https://user-images.githubusercontent.com/17325/93151083-f8afc500-f74e-11ea-8832-71ac84829762.gif)

**Comment by jsnmoon** [comment]
I'm not able to reproduce on Chrome 85, but I've had autocomplete disabled on all my browsers for several years now. 

Nonetheless, I'll spin up a quick PR for this.
