### ISSUE TITLE
Blog subscriptions widgets subscribe button

### ISSUE THREAD

**Issue by oleteacher** [Automattic/jetpack#17189]
#### Is your feature request related to a problem? Please describe.
Blog subscriptions widgets subscribe button: Button tag does not have any style /class associated with it.

#### Describe the solution you'd like
<button class="widget_subscribe_btn"> or something unique to the Jetpack widget.

#### Describe alternatives you've considered
There is no need to actually associate any css with with the class, that can be left up to the site owner.

#### Additional context
Without the ability to "style" the button, many themes simply display text and it is very unattractive.

**Comment by jeherve** [comment]
While the button itself does not have its own class, parent containers do. You should be able to style the button like so for example:

```css
.jetpack_subscription_widget button[type="submit"] {
	background-color:yellow;
}
```
(note that you can use more specific selectors if needed)

**Comment by oleteacher** [comment]
Did not work for me, had tried that before submitting here.

I will remove jetpack and use my old ways, much easier and lighter anyway.

Thanks anyway.

**Comment by jeherve** [comment]
If relying on CSS specificity rules does not quite work for you, you could try to use the Subscriptions shortcode instead; it comes with a `submit_button_classes` attribute that you can use to add a custom class to your Subscription widget's button. Here is an example of the shortcode with a few of its attributes:

```
[jetpack_subscription_form submit_button_classes="a_very_custom_class" title="My Custom Title" subscribe_text="My custom subscribe text!" subscribe_button="Sign Me Up" show_subscribers_total="1"]
```

You can add such a shortcode inside a post or a page, or in a Text widget, like so:

![image](https://user-images.githubusercontent.com/426388/93477819-c42d3c00-f8fb-11ea-96b1-fc3c1896cc47.png)


![image](https://user-images.githubusercontent.com/426388/93478231-05255080-f8fc-11ea-8577-6d4bea3093bb.png)
