### ISSUE TITLE
Automattic IP Ranges: offer IP list via API endpoint.

### ISSUE THREAD

**Issue by MarceloPedra** [Automattic/jetpack#1719]
Hello guys. I was under a heavy xmlrpc attack, and had to block access to xmlrpc.php using the iThemes Security plugin. But to allow JetPack to work in the meantime, I allowed this IP range:

``` ApacheConf
<files xmlrpc.php>
    Order allow,deny
    Deny from all
    Allow from 192.0.64.0/18
</files>
```

My question is: is there any other IP range that should be allowed for JetPack to work properly?

Thank you!

**Comment by georgestephanis** [comment]
Our list of IP ranges do change, so I really couldn't recommend whitelisting.  Nearly all of our requests do come in with the `?for=jetpack` get string on the end.

Plus, you can use the `add_filter( 'xmlrpc_enabled', '__return_false' );` filter to turn off xmlrpc from with WordPress safely without negatively affecting Jetpack.

**Comment by jeherve** [comment]
Here are the IPs you can use:
http://whois.arin.net/rest/org/AUTOM-93/nets
You'll also need to `185.64.140.0/22` and `a04:fa80::/29` to the list.

Overall, we don't suggest this approach since our IP block will change over time, changing the possible IP addresses and this would prevent any of the mobile apps or other desktop clients from working.

Alternatively, Jetpack requests are routed to `/xmlrpc.php?for=jetpack` , so matching that string and allowing that is another option. Jetpack has protocols in place to only accept incoming requests that have been signed by our servers.

I believe iThemes Security includes an option to block XML-RPC pingback requests only. Since this is the most common vector of attack to XML-RPC today, you could block only that while still allowing other XML-RPC requests from plugins and mobile apps.
You can also use this plugin to disable XML-RPC pingback requests:
https://wordpress.org/plugins/disable-xml-rpc-pingback/

**Comment by Jany-M** [comment]
@jeherve Not too good an regex, could you maybe share a snippet to effectively match the string, so I can also use that method, rather then IPs?

**Comment by jeherve** [comment]
@Jany-M This should help: http://www.analyticsmarket.com/freetools/ipregex

**Comment by Jany-M** [comment]
@jeherve I think the link only helps with IP ranges, am I mistaken? I meant a snippet to match the `/xmlrpc.php?for=jetpack` string, or anything jetpack related (or even WP API related), you think should be allowed.

**Comment by jeherve** [comment]
>  I think the link only helps with IP ranges, am I mistaken?

That's correct.

Overall, we don't recommend that approach though. You can check a possible alternative in my comment above.

**Comment by jeherve** [comment]
I like that idea. That's not on our roadmap right now, but I'll reopen that issue so we can go back to it later.

**Comment by MarceloPedra** [comment]
Hi! Any news on this request?

**Comment by Retriev3r** [comment]
@MarceloPedra 
Here are the new addresses (2017) to block all XMLRPC requests and allow only Jetpack (Wordpress.com) + also working with your website behind Cloudflare.

`

	<files xmlrpc.php>
		Order deny,allow
		Deny from all
		
        # Whitelist Jetpack / Automattic CIDR IP Address Blocks (source: http://whois.arin.net/rest/org/AUTOM-93/nets )
		Allow from 192.0.64.0/18
		Allow from 185.64.140.0/22
		Allow from 76.74.255.0/25
		Allow from 76.74.248.128/25
		Allow from 198.181.116.0/24
		Allow from 64.34.206.0/24
		Allow from 2620:115:C000::/40
		Allow from 122.248.245.244
		Allow from 54.217.201.243
		Allow from 54.232.116.4

        # Whitelist Cloudflare CIDR IP Address Blocks (source: https://www.cloudflare.com/ips/ )
		Allow from 103.21.244.0/22
		Allow from 103.22.200.0/22
		Allow from 103.31.4.0/22
		Allow from 104.16.0.0/12
		Allow from 108.162.192.0/18
		Allow from 131.0.72.0/22
		Allow from 141.101.64.0/18
		Allow from 162.158.0.0/15
		Allow from 172.64.0.0/13
		Allow from 173.245.48.0/20
		Allow from 188.114.96.0/20
		Allow from 190.93.240.0/20
		Allow from 197.234.240.0/22
		Allow from 198.41.128.0/17
	</files>
`

**Comment by tfpdeveloper** [comment]
What's the status of this issue ?

As IP range might change over time, any doable solution to block all xml-rpc requests except from automattic?

**Comment by jeherve** [comment]
> What's the status of this issue ?

We have not made any progress on this, but will update this issue when we do.

**Comment by CurtisBelt** [comment]
Looks like the IPs have a changed a bit, just posting in case anyone was about to copy from the other list.

Only way to know for sure is to go to http://whois.arin.net/rest/org/AUTOM-93/nets
Then use a converter with the bulk range -> CIDR, such as https://www.cidrcalculator.com/

**Automatic CIDR ranges as of March 20th 2018**
```
192.0.64.0/18
198.181.116.0/22
2001:1978:1e00:3::/64
2620:115:c000::/40
64.34.206.0/24
66.155.105.128/26
69.90.253.0/24
76.74.248.128/25
76.74.255.0/25
```

Cloudflare offers dynamic plain text endpoints here:

https://www.cloudflare.com/ips-v4
https://www.cloudflare.com/ips-v6

+1 to Automatic getting something like this! Thanks.

**Comment by pipdig** [comment]
+1 A plaintext file like Cloudflare would be extremely useful for automation

**Comment by stephengroat-dd** [comment]
in case anyone's interested, i made a little script that pulls the ip addresses using ARIN's api: https://github.com/stephengroat/whitelist/commit/bb0874f61c0bfcfbd66e37168627a2351da3583f

**Comment by mjangda** [comment]
This page includes details about IPs: https://jetpack.com/support/hosting-faq/

And also mentions two endpoints that can be used:

https://jetpack.com/ips-v4.json
https://jetpack.com/ips-v4.txt

The caveat noted on the page is important:

> These IP addresses are subject to change. If you are writing IP-based firewall rules, you’ll need to update those rules any time the addresses change.

**Comment by neonardo1** [comment]
Thank you!

**Comment by iamkingsleyf** [comment]
This is confusing

**Comment by GwynethLlewelyn** [comment]
In case that someone comes here via Google and needs the latest lists of _official_ IP addresses:

- **Jetpack:** 
  - https://jetpack.com/ips-v4.txt (only IPv4 though)
  -  IPv6 addresses [as before](http://whois.arin.net/rest/org/AUTOM-93/nets):
    `2001:1978:1e00:3::/64`
    `2620:115:c000::/40`
- **Akismet:** (as of [2021-04-06](https://blog.akismet.com/akismet-hosting-faq/); this is manually updated...)
    `192.0.80.244`
    `192.0.80.246`
    `192.0.96.247`
    `192.0.96.248`
    `192.0.123.250`
    `195.234.111.251`
    `195.234.111.252`
- **Cloudflare:** (as posted above, their endpoints have not changed)
  - https://www.cloudflare.com/ips-v4
  - https://www.cloudflare.com/ips-v6

Source: https://jetpack.com/support/hosting-faq/
