### ISSUE TITLE
Payments: In-block upgrades lead to checkout for the Premium plan.

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#17206]
The upgrade prompt within the Payments block currently links to `https://wordpress.com/checkout/fair-nurse.jurassic.ninja/premium` (which still works).

<img width="773" alt="Screen Shot 2020-09-18 at 1 57 53 PM" src="https://user-images.githubusercontent.com/349751/93644880-a7563e80-f9b7-11ea-9e2a-570879cfcbd4.png">

This will need to be changed to `wordpress.com/plans/:site` or, if we want to continue going straight to checkout, we'll need to decide what new plan should be in the cart.

**Comment by kwight** [comment]
We'll use Jetpack Security Daily (p1HpG7-abh-p2).

**Comment by scottsweb** [comment]
Related to: p1HpG7-aiL-p2

**Comment by jeherve** [comment]
Related: p1HpG7-aKx-p2

**Comment by dsas** [comment]
This now links to jetpack security daily rather than premium so I think we can close this
