### ISSUE TITLE
Donations block: Add Block Background Option

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#17225]
I’ve been testing the donations block, researching similar functionality on other websites, and started designing some patterns around it. One of the first things I tried, is putting the donations block inside a cover block since it’s a really popular pattern I saw on charity websites. It didn’t really work, because without background the text can be hard to read or unreadable. Having background color controls would take care of that, plus allow us to create consistent designs. 

This is how the donations block looks like right now when nested in cover block:

![image](https://user-images.githubusercontent.com/4550351/93842233-7f2d4f00-fcd9-11ea-9bf3-473fecf054a1.png)

Here's how it looks like when nested inside a group block with background set to white:
![image](https://user-images.githubusercontent.com/4550351/93842272-9bc98700-fcd9-11ea-9eda-01033161096a.png)

While nesting in group block is a viable option, it might be hard for the customers to figure it out - this is why I'm advocating for having the option in the donations block.

**Comment by Copons** [comment]
Abandoning this in favour of a block pattern approach using the revamped Payment Button block.
See: 600-gh-Automattic/dotcom-manage
