### ISSUE TITLE
Masterbar: remove "Deactivate" option in environments where it cannot be disabled

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/jetpack#17229]
#### Steps to reproduce the issue

0. Host a site on WordPress.com business
1. Go to https://somesite.com/wp-admin/admin.php?page=jetpack_modules
2. Click on "Deactivate" beside "WordPress.com Toolbar"

#### What I expected
Modules is deactivated.

#### What happened instead
Page reloads. Module is still active.

**Screenshots**

WordPress 5.5.1
Jetpack 8.9.1

**Comment by jeherve** [comment]
The WordPress.com Toolbar is indeed activated by default on WordPress.com Business sites, and can only be disabled via code, as discussed in https://github.com/usdigitalresponse/election-websites/issues/136. This configuration is specific to WordPress.com Business sites, where site owners sign up and manage some of the aspects via the WordPress.com interface; for them, having easy access to that WordPress.com interface is important.

I see you've added the snippet to your theme; that should solve the issue. 👍

**Comment by paulschreiber** [comment]
If this module cannot be disabled, the UI should change to indicate this. The Deactivate link should be removed, as it is for VideoPress:
![image](https://user-images.githubusercontent.com/86784/93884074-6d838180-fcb0-11ea-817c-0a87c4a21652.png)

**Comment by jeherve** [comment]
That's a good point 👍
