### ISSUE TITLE
Donations block: Add option to remove the separator

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#17228]
Depending on the theme, it might be displayed as two separate dashes, which looks wrong. 

![image](https://user-images.githubusercontent.com/4550351/93843314-d2ed6780-fcdc-11ea-8240-2fc42688bfbf.png)

It’s also confusing that customers can remove every text element in the block (or at least leave it empty), but not the separator. This becomes particularly problematic when the text between the separator and the button is removed, as in the screenshot above. In that case, the separator on its own doesn’t make any sense. If we don’t want to give the ability to delete this element, maybe it could be linked to the thank you message, and if it’s empty not display it either?

**Comment by Copons** [comment]
Abandoning this in favour of a block pattern approach using the revamped Payment Button block.
See: 600-gh-Automattic/dotcom-manage
