### ISSUE TITLE
Plans: adjust wording for all upgrades when site is part of a Multisite network

### ISSUE THREAD

**Issue by tiffanybridge** [Automattic/jetpack#17220]
### Steps to reproduce the issue 

1. Start from a site that's the main site of a Multisite network.
2. Connect that site to WordPress.com.
3. Go to Jetpack > Dashboard in wp-admin
4. Click on the prompts to upgrade
5. You'll be able to purchase a Jetpack Complete Plan
6. Upon purchase, and when back to wp-admin, you'll still see prompts to upgrade in the AAG dashboard as well as in Jetpack > Settings.

The call to `jetpack/v4/rewind` returns the following:

```
{"code":"success","message":"Backup &amp; Scan data correctly received.","data":"{\"reason\":\"multisite_not_supported\",\"state\":\"unavailable\",\"last_updated\":\"2020-09-21T17:03:10.651+00:00\",\"has_cloud\":true}"}
```

- [ ] It seems like we should take such Rewind states into account better.
- [ ] We may want to update the purchase prompts and flows so we do not even get into that state.

**Screenshots**

![image (10)](https://user-images.githubusercontent.com/6172029/93779333-d9a0af80-fbf4-11ea-9429-149d3a4ea2fe.png)

Team51 project, backups and scan on settings page also entirely blank. 

<img width="869" alt="CleanShot 2020-09-21 at 09 21 14@2x" src="https://user-images.githubusercontent.com/6172029/93779523-1bc9f100-fbf5-11ea-9489-62cfc6895dbb.png">

**Comment by jeherve** [comment]
I can't seem to be able to reproduce right now:

![image](https://user-images.githubusercontent.com/426388/93781952-41bdb880-fc2a-11ea-86c8-5ddc1519b631.png)

![image](https://user-images.githubusercontent.com/426388/93781977-4a15f380-fc2a-11ea-960e-68f57aa5b534.png)

Was this a brand new site, or a site where you had a plan before?

**Comment by tiffanybridge** [comment]
This site had previously had a Business plan.

**Comment by jeherve** [comment]
I can't reproduce just yet, but we're discussing things in p1600704235120100-slack-C0CMN0V97

cc @Automattic/jetpack-voyager

**Comment by mattgawarecki** [comment]
I was able to reproduce using the updated instructions. Right now I'm asking around to figure out our approach to purchases from multi-site networks.
