### ISSUE TITLE
Donations Block: Match the background color of the tabs with the theme color palette.

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#17227]
The blue tabs really stick out and make it very difficult to create a consistent visual style. Even if we consider an isolated block pattern, the mismatch of styles between the tabs and the button is jarring. Ultimately, having color controls would be ideal, but matching to theme palette could be a start. 

In terms of how to do this, we could get a list of theme colors from the `editor-color-palette` declaration (if available), and use the color marked as `primary`, or whatever is first on the list (just a rough idea). I’m sure there would be more to it, and ultimately adding color controls might be easier than guessing the colors and ensuring proper contrast 🙂. 

This is how the block looks currently, with blue as the default color:

![image](https://user-images.githubusercontent.com/4550351/93843124-50fd3e80-fcdc-11ea-96ef-2399d9a20ff8.png)

This is how it would look like if we matched theme color palette:

![image](https://user-images.githubusercontent.com/4550351/93843087-3034e900-fcdc-11ea-8313-813f7fbf1a37.png)

**Comment by creativecoder** [comment]
Using the shared Button component here (like what's used for some of the embed blocks), might solve the color issue for the button, as that component already ties into the color palette options.

**Comment by Copons** [comment]
Abandoning this in favour of a block pattern approach using the revamped Payment Button block.
See: 600-gh-Automattic/dotcom-manage
