### ISSUE TITLE
Donations Block: Add option to center align the content

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#17231]
Right now all the elements inside the block are left-aligned with no option to change that. I think having an option to center align the elements would allow us to create more varied designs (and it's a popular pattern in general).

This is how the block looks like now:
![image](https://user-images.githubusercontent.com/4550351/93843926-ee597200-fcde-11ea-8396-f81d43255da4.png)

This is the end result I'm after:
![image](https://user-images.githubusercontent.com/4550351/93843863-bb16e300-fcde-11ea-9351-bd943f2a1f2e.png)

**Comment by Copons** [comment]
Abandoning this in favour of a block pattern approach using the revamped Payment Button block.
See: 600-gh-Automattic/dotcom-manage
