### ISSUE TITLE
Donations block: Add options to change the styling of the amount selector

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#17230]
The frame around the selected item blends in and does not make it stand out. The most popular pattern I’ve seen out there is to highlight the selected item by switching the background/text color. **Could we have this as a style variation?** Or maybe even go as far as making this the default style, with a frame around being the alternative option? For the most design flexibility, I think it would make sense to have the same controls as the buttons block. 

Here's what I had in mind:

![image](https://user-images.githubusercontent.com/4550351/93843528-776fa980-fcdd-11ea-82be-45a3e391260e.png)

**Comment by Copons** [comment]
Abandoning this in favour of a block pattern approach using the revamped Payment Button block.
See: 600-gh-Automattic/dotcom-manage
