### ISSUE TITLE
Donations block: Feature parity for headings, paragraphs, and button

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#17232]
All the individual elements inside the block (paragraphs, headings, button) should have the same styling options available as if they were individual blocks. For paragraphs and headings, it’s the font size, line-height, color settings. For button, it’s button style (fill, outline), color settings, and border-radius.

**Comment by simison** [comment]
Having these supports componentized somehow so that the right thing would be easy to implement could be useful and make maintenance much easier.

Basically, in a block you'd declare "use button here" and all the future customizations available to button block would just work.

**Comment by Copons** [comment]
Abandoning this in favour of a block pattern approach using the revamped Payment Button block.
See: 600-gh-Automattic/dotcom-manage
