### ISSUE TITLE
add rel = 'noopener' or rel = 'noreferrer' to the external Google Translate widget

### ISSUE THREAD

**Issue by pgg1958** [Automattic/jetpack#17255]
I registered this problem with Jetpack Support and was instructed to register it here.

Google Lighthouse accuses security breach caused by the Google Translate widget
installed by Jetpack. The problem is the link inserted in 'Powered by Google
Translate' (https://translate.google.com/) which has no rel = 'noopener' or rel
= 'noreferrer' which causes the security breach pointed out by Google Lighthouse
. This can be seen on the website https://programeviagem.com
I believe that because it is a security problem the plugin should be fixed in a
next version. However, if anyone knows how to get around the problem, I would
like to get information.
 
<img width="1278" alt="Captura de Tela 2020-09-24 às 11 06 42 AM" src="https://user-images.githubusercontent.com/71831216/94156966-0f44d300-fe57-11ea-8904-113cb21c90d2.png">
<img width="902" alt="Captura de Tela 2020-09-23 às 4 18 08 PM" src="https://user-images.githubusercontent.com/71831216/94156986-14098700-fe57-11ea-90fd-f5e4881312c6.png">

**Comment by jeherve** [comment]
I'm afraid we will not be able to help with this. The Jetpack plugin pulls the widget from Google, and does not control its display or output; this is all managed by Google themselves, via a script that's loaded on your site from `translate.google.com`.

I would consequently recommend that you reach out to Google directly with this feedback. I believe you can do so here:
https://support.google.com/webmasters/community/?hl=en&gpf=%23!forum%2Fwebmasters

**Comment by pgg1958** [comment]
I understand. Grateful for the attention.
