### ISSUE TITLE
Jetpack Search: Expanded Result Format is too wide on mobile

### ISSUE THREAD

**Issue by cagrimmett** [Automattic/jetpack#17265]
#### Steps to reproduce the issue

1. Pick a site with Featured Images in posts
2. Enable Jetpack Search and set the Result Format to Expanded 
3. Run a search query on mobile
4. See that the content overflows off the right side of the screen

I verified this on two sites with two different themes, so I don't think it is a theme-specific issue.

The search result path below each post's title is too wide, no-wrap with a hard-coded max-width. This seems to fix it:

```
.jetpack-instant-search__result-expanded__path.jetpack-instant-search__result-expanded__path{
	white-space: normal;
}
```

That said, I'm not sure what it is supposed to look like on mobile, so this may not be the appropriate fix.

**Screenshots**
Version that overflows (default)
![IMG_B9524940A750-1](https://user-images.githubusercontent.com/8738771/94287582-7d0b0080-ff24-11ea-91ff-55ac48315e3b.jpeg)

Version with `white-space: normal`
![IMG_1BE0D91B1604-1 2](https://user-images.githubusercontent.com/8738771/94287666-9613b180-ff24-11ea-9576-955a4c76d8da.jpeg)

**Comment by gibrown** [comment]
Ya this was fixed in https://github.com/Automattic/jetpack/pull/17187 and will be in the next release on Oct 6th.
