### ISSUE TITLE
Donations Block: Block breaks on theme switch

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#17261]
I think this issue sits at an intersection of themes and donations block, hopefully, this is the right place to report.

#### Steps to reproduce the issue

1. With one of the Varia child themes active (for example Rockfield), create a post or a page and add donations block.
2. Save the post, then go back to the dashboard and switch themes (I tried Seedlet and a couple other Varia child themes).
3. Go back to editing your post. Note the error message "This block contains unexpected or invalid content". Also note how all the elements inside the block are duplicated.
4. Also note visual bug where the error message is unreadable if the donations block is nested in a cover block.
5. Click "Attempt Recovery". This fixes all the issues, and block works normally afterward.

I made a video of this issue in case this is helpful:

https://cloudup.com/cKnNhqHOFWc

**Comment by dsas** [comment]
I can't reproduce this. @alaczek can you re-open if you still can?
