### ISSUE TITLE
Cannot publicize CPT after it's published

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#17281]
I want to be able to publicize my podcast episodes after I have created them. Currently the social network icons are disabled with no explanation (please, could you include an explanation?) and I can't find a way to enable them.

<img width="571" alt="cannot-publicize-post" src="https://user-images.githubusercontent.com/51896/94383236-ceb0c680-0182-11eb-8b8a-0775b572be14.png">

#### Steps to reproduce the issue

I am using the "Seriously Simple Podcasting" plugin, which has a `podcast` post type.

In order to enable publicize for the `podcast` post type, I added the following snippet using the snippets plugin:

```php
add_action('init', 'add_publicize_to_podcast_cpt');
function add_publicize_to_podcast_cpt() {
    add_post_type_support( 'podcast', 'publicize' );
}
``` 

I have the "Jetpack Complete" plan so that I can schedule and re-publicize posts, and this sortof works when I use Calypso (via drop-down menus on the post), but I want to do everything locally via Gutenberg. (separate issue: clicking to edit my posts using Calypso results in **all kinds of crazy** in my wp-admin afterwards, where browsing around my wp-admin gets "themed" as WordPress.com, but only on certain pages...)

#### What I expected

To be able to publicize posts during initial publish and also after publishing.

#### What happened instead

Inexplicably greyed out publicize toggles in Gutenberg.

**Screenshots**

<img width="571" alt="cannot-publicize-post" src="https://user-images.githubusercontent.com/51896/94383388-3ebf4c80-0183-11eb-91e9-f11bbaf9541b.png">

**Comment by jeherve** [comment]
I've split this issue into two different ones so we can keep track of both of your remarks:

- Publicize: add explanation when toggles are disabled for a published post #17282 
- Publicize: add Re-Publicize options to block editor #17283
