### ISSUE TITLE
Extensions: Jetpack blocks disappear when ActiveCampaign plugin is activated

### ISSUE THREAD

**Issue by creativecoder** [Automattic/jetpack#17289]
#### Steps to reproduce the issue

1. On a connected Jetpack Site
1. Purchase a "Jetpack Complete" plan, if the site doesn't already have one
1. Enable experimental blocks  -- `define( 'JETPACK_EXPERIMENTAL_BLOCKS', true );` in wp-config.php
1. Enable SEO Tools module in Calypso -- `https://wordpress.com/marketing/traffic/{site}`
1. Verify that you can see the "SEO description" input in the editor sidebar
1. Then activate the [ActiveCampaign plugin](https://wordpress.org/plugins/activecampaign-subscription-forms/)
1. Load a post in the editor

#### What I expected

1. All Jetpack blocks to be available

#### What happened instead

1. No Jetpack blocks are available
1. There's a js error in `editor-experimental.js`

**Screenshots**

<img width="200" alt="Screen Shot 2020-09-28 at 14 41 53" src="https://user-images.githubusercontent.com/1699996/94482979-c5822280-019f-11eb-9d77-c09345b61e45.png">
<img width="400" alt="Screen Shot 2020-09-28 at 14 46 41" src="https://user-images.githubusercontent.com/1699996/94482977-c4e98c00-019f-11eb-9188-739c48f6d1a0.png">
<img width="400" alt="Screen Shot 2020-09-28 at 14 47 15" src="https://user-images.githubusercontent.com/1699996/94482972-c31fc880-019f-11eb-82ce-e18cb916f849.png">

**Comment by jeherve** [comment]
This seems to happen to me even when the SEO Tools module is disabled, and even with the Production blocks. The error points to the Social Previews extension, and not SEO tools:

https://github.com/Automattic/jetpack/blob/51c422eb82ee6fd16f4fb3a4b138ef3e80e2b1fb/extensions/shared/external-media/constants.js#L167-L170

On my end, the error actually is a few lines downer:

![image](https://user-images.githubusercontent.com/426388/94531268-9bcb0900-023c-11eb-93d7-de6f67977528.png)

**Comment by creativecoder** [comment]
You're right about the source--my screenshot is in Firefox, looks like Chrome wins the prettifying minified js in this case.

To see what would happen, [I removed lodash as a dependency from that file](https://github.com/Automattic/jetpack/pull/17312). It triggered the same error elsewhere.

I did a little digging, I still don't totally understand what's going on, but I can see that activating the ActiveCampaign plugin makes lodash disappear for `editor-experimental.js` (and maybe elsewhere?)

| ActiveCampaign active | ActiveCampaign inactive |
| - | - |
| <img width="915" alt="Screen Shot 2020-09-29 at 17 51 52" src="https://user-images.githubusercontent.com/1699996/94624876-0b60e880-027d-11eb-9588-2fa60480d100.png"> | <img width="916" alt="Screen Shot 2020-09-29 at 17 51 29" src="https://user-images.githubusercontent.com/1699996/94624885-13208d00-027d-11eb-9765-fe5cdbc476b3.png"> |

**Comment by jeherve** [comment]
>  I can see that activating the ActiveCampaign plugin makes lodash disappear for editor-experimental.js

I could find the ActiveCampaign plugin on GitHub to check its source code. Maybe we could reach out to them, maybe they do something to dequeue or modify the copy of lodash that comes bundled with WordPress and is used here?

**Comment by creativecoder** [comment]
I think I found the issue, a conflict with `window.webpackJsonp` in the webpack builds of Jetpack blocks and the ActiveCampaign block. It looks like this [has happened up with other plugins](https://wordpress.org/support/topic/conflict-between-divi-visual-builder-and-mailpoet-3-with-latest-releases/).

The [webpack docs](https://webpack.js.org/configuration/output/#outputjsonpfunction) state

> If multiple webpack runtimes (from different compilations) are used on the same webpage, there is a risk of conflicts of on-demand chunks in the global namespace.

If someone more versed in Jetpack webpack config can help me set the `output.jsonpFunction` setting to a custom value (at least for blocks, if not all transpiled Jetpack JS), I think that will resolve this.

**Comment by creativecoder** [comment]
Here's my first attempt, which didn't seem to work (the jsonp global name does not change)

https://github.com/Automattic/jetpack/pull/17312/commits/33815b44dd0d69f039aa543ef3dc71f37e338820

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/podcast-support-gone/

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/twitter-block-doesnt-show-unroll-option/

**Comment by creativecoder** [comment]
Now I see that the calypso-build package needs to be updated to support customizing the config for `output.jsonpFunction` in order to customize this.

PR: https://github.com/Automattic/wp-calypso/pull/46252
