### ISSUE TITLE
Publicize: Allow plugins to provide support for transforming their blocks into tweets.

### ISSUE THREAD

**Issue by pento** [Automattic/jetpack#17295]
This issue is a spin-off from #17149.

After seeing the Twitter Threads feature for the first time, a frequent question I've had is "how can I hook into this?". This issue is for exploring what the limitations of an API would be, and what it would need to provide.

## Potential Limitations

While it would be easy enough (if the appropriate filters were provided) for a plugin to hook into the block/tweet parser on a site, this parsing process is only used for the preview functionality, it isn't used to generate the thread that's published to Twitter. Once the post has been published, it's re-parsed on WordPress.com servers, to ensure the content being sent to Twitter is properly controlled.

In order for a plugin to provide the Tweet-able version of their blocks, they'd need to be able to provide the content when the post is published, that content would be synced to WordPress.com (in some sort of postmeta, presumably), then the WordPress.com parser would incorporate that content into the thread. For security, it's not possible for plugins to execute code on WordPress.com servers, the content _must_ be prepared on the Jetpack site.

The [Block Directory Guidelines](https://developer.wordpress.org/plugins/wordpress-org/block-specific-plugin-guidelines/) require that plugins have minimal PHP code in them. Given that all the block/tweet parsing happens on the server side, this could potentially be an issue. I'd like to get feedback from the WordPress Plugins Team on this.

## Potential Requirements

Due to the complexity of the many ways we have to count characters, I don't think it's reasonable to ask plugin developers to provide the exact content that will be used in each tweet, but they'll certainly need some level of control. There are several options to explore here, but I'd like to see examples of the kinds of blocks that plugins would like to transform into tweets, to get a better sense of what's required.

## Feedback

If you've got blocks that you'd like to see turned into tweets, tell me more about them in the comments. 🙂

**Comment by jeherve** [comment]
Closing since the feature is no longer available.
