### ISSUE TITLE
Stats: remove smiley face setting

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#17304]
The Stats settings currently include this setting:

![image](https://user-images.githubusercontent.com/426388/94591476-6cda8480-0288-11eb-8e7e-c9a3a3545181.png)

While the setting made sense when the smiley face was shown by default, I don't believe the setting is that useful today, as few will toggle this.

*****

Related discussion:
p8oabR-y3-p2/#comment-4570

**Comment by RCowles** [comment]
Noting here that we've received a report that the smiley displays `on` by default with a new WP install, and with the UI option removed the user is unable to disable the smiley:

- https://wordpress.org/support/topic/where-has-the-hide-the-stats-smiley-face-image-gone/

I've requested more information from the user, not asking for action here yet. But just noting for reference in case we need to followup.

**Comment by jeherve** [comment]
> the smiley displays on by default with a new WP install

I can't seem to be able to reproduce on a new WP install. The smiley has defaulted to being off by default since 2014 (see #656), and it still works in my test. 

On existing installations, however, or installations that are made by copying options from an old site, it could be that the option is still set to on.

> with the UI option removed the user is unable to disable the smiley

The Stats options are stored in an option, `stats_options`. Even if the UI is gone, you should be able to deactivate the option like so:

```php
function jeherve_hide_stats_smiley() {
	if ( ! function_exists( 'stats_set_option' ) ) {
		return;
	}
	stats_set_option( 'hide_smile', true );
}
add_action( 'admin_init', 'jeherve_hide_stats_smiley' );
```

Note that you don't need to keep this snippet around for too long; Once you've refreshed wp-admin once with this snippet active, the option will have been updated, and you can consequently remove the snippet.

Another alternative would be to do this via WP Cli if that's an option on the site. `wp option pluck stats_options hide_smile` would return the current status of the option (`1` if the smiley is hidden, `0` if it is not). `wp option patch update stats_options hide_smile 1` would hide it.

Another alternative is to add some custom CSS to hide the smiley, under Apperance > Customize > Edit CSS:

```css
img#wpstats{display:none;}
```
