### ISSUE TITLE
At A Glance: Anti-spam counter card alignment issues

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#17306]
### Steps to reproduce the issue

1. Connect your site to your WordPress.com account
2. Purchase a plan as part of the connection flow to automatically activate and configure Anti-spam.
3. Go to Jetpack > Dashboard

The “Spam comments blocked” stat looks misaligned, with the number being large and the text being small but not centered (or aligned in any specific way).

![image](https://user-images.githubusercontent.com/426388/94594582-e9219780-0289-11eb-9aa8-2e8033b1b559.png)

******

Reported here:
p8oabR-y3-p2#comment-4563

**Comment by scottsweb** [comment]
Card should not be considered in isolation: https://github.com/Automattic/jetpack/pull/17457#issuecomment-709963828
