### ISSUE TITLE
Pay with PayPal: Currency indicator is fixed on the end.

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#17336]
Instead of the currency indicator always being after the value, its placement should depend on the currency itself (eg. dollars at the front).

<img width="603" alt="Screen Shot 2020-09-30 at 1 34 03 PM" src="https://user-images.githubusercontent.com/349751/94737178-42d5a080-0322-11eb-977d-590b23519cef.png">

**Comment by jeherve** [comment]
closing as duplicate of #11897.
