### ISSUE TITLE
Pay With PayPal Block: Currency form elements are misaligned.

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#17337]
The form elements in the edit view are misaligned and awkward-looking.

<img width="767" alt="Screen Shot 2020-09-30 at 1 42 35 PM" src="https://user-images.githubusercontent.com/349751/94737638-ffc7fd00-0322-11eb-9253-9c13fc286984.png">

**Comment by mreishus** [comment]
I see some slight misalignment when I narrow my browser, but I'm not able to reproduce the original problem yet.

![2020-10-05_17-23](https://user-images.githubusercontent.com/937354/95138362-aa7b5980-072f-11eb-8025-e66559891e5f.png)
![2020-10-05_17-23_1](https://user-images.githubusercontent.com/937354/95138370-ad764a00-072f-11eb-874c-2c46c5573ef8.png)
![2020-10-05_17-23_2](https://user-images.githubusercontent.com/937354/95138374-b0713a80-072f-11eb-860d-fa23efbfd45a.png)

Here, I'm running off jetpack master branch - 29a66cac dated Mon Oct 5 19:14:02 2020 - using `yarn build-extensions`  and rsyncing to my wpcom sandbox (business simple site with 2020 theme). It's possible this workflow is at fault, I can try with wp-env tomorrow.

**Comment by retrofox** [comment]
It's funny we're hiding the label.
![Uploading Screen Shot 2020-10-20 at 3.38.10 PM.png…]()

**Comment by retrofox** [comment]
Not sure why we are [hiding the labels](https://github.com/Automattic/jetpack/blob/1e6b558b831fe9cc065e3fac17454bafad01f66e/extensions/blocks/simple-payments/editor.scss#L11) instead of don't define them.

**Comment by kwight** [comment]
Are the labels there for accessibility maybe? I think they might be read by screen readers.

**Comment by retrofox** [comment]
> Are the labels there for accessibility maybe? I think they might be read by screen readers.

ohhhh, this is a very good point! @jeryj could you help us to confirm if this is a kind of technique to deal with these issues?

**Comment by retrofox** [comment]
> Are the labels there for accessibility maybe?

should we use aria-label instead?

**Comment by jeryj** [comment]
`display: none;` won't be read by a screen reader. `<label>` is better than `aria-label`, so I'd leave it as is and use different CSS to hide the label while still letting the screen reader access it. 

Here's the CSS we used for the Podcast Player to hide content visually but allow access via the SR: https://github.com/Automattic/jetpack/blob/06e20fbb4eb098c32bc01631f570735b1f55e5ac/extensions/blocks/podcast-player/style.scss#L25-L32

**Comment by retrofox** [comment]
> `display: none;` won't be read by a screen reader. `<label>` is better than `aria-label`, so I'd leave it as is and use different CSS to hide the label while still letting the screen reader access it.

Thanks, that's exactly what we did in the PR, on [this commit](https://github.com/Automattic/jetpack/pull/17546/commits/7ed63e056350020ed902bb28569f8c358be6da55). 👍
