### ISSUE TITLE
jetpack_featured_images_remove_post_thumbnail() unexpectedly applies to shortcode rendering custom post type

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/jetpack#17345]
Our plugin uses a shortcode to render a recipe card where the underlying storage mechanism is a custom post type. The Recipe card is supposed to display the featured image of the custom post type:

<img width="685" alt="image" src="https://user-images.githubusercontent.com/36432/94842887-c64dcb00-03d0-11eb-8d1c-255a049ce784.png">

When Jetpack's remove featured image feature is active, the featured image within our recipe card doesn't display.

Ideally, `jetpack_featured_images_remove_post_thumbnail()` would only apply when `get_the_ID() === get_queried_object_id()`. However, making this change might cause a perceived break in the existing behavior for some users.

Here's the workaround we're offering to our users:

```php
add_filter(
	'get_post_metadata',
	function( $metadata, $object_id, $meta_key ) {
		if ( 'tasty_recipe' === get_post_type( $object_id )
			&& '_thumbnail_id' === $meta_key ) {
			return null;
		}
		return $metadata;
	},
	100,
	3
);
```

Related #13107

**Comment by jeherve** [comment]
> However, making this change might cause a perceived break in the existing behavior for some users.

cc @thomasguillot who may have a better idea of the impact this may have on existing themes.

**Comment by thomasguillot** [comment]
We could add `tasty_recipe` to the list of CPT we don't want to hide the featured image: https://github.com/Automattic/jetpack/blob/master/modules/theme-tools/content-options/featured-images.php#L8

I don't see any impact this may have on existing themes 😊

**Comment by jeherve** [comment]
Thanks. It seems to me like we could at least add a filter in there to allow everyone to add their own CPT when needed.
