### ISSUE TITLE
Donations: WP.com notifications need sensible fallback content.

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#17358]
A Donations block, when rendered in a WordPress.com bell notification, displays all the tabbed markup with no styles or structure.

<img width="1337" alt="Screen Shot 2020-10-02 at 10 28 40 AM" src="https://user-images.githubusercontent.com/349751/94952391-c3b7a800-049a-11eb-945a-28e28417bd5a.png">

**Comment by bsanevans** [comment]
Noting a user case here where the content shown in the post publication email was the markup, too, and not sensible to the subscribers. 3424809-zd-woothemes

I've let the user know we are working on a fix, but gave no timeline.
