### ISSUE TITLE
Search is not enabled after purchasing JP Search ( Dev Environment ) 

### ISSUE THREAD

**Issue by nirmalc** [Automattic/jetpack#17366]
Search is not enabled after purchasing JP Search ( Dev Environment ) 

#### Steps to reproduce the issue

1. Follow https://github.com/Automattic/jetpack/blob/master/docker/README.md to setup Docker - Jetpack dev environment
2. Purchase Search from here : https://jetpack.com/upgrade/search/     ( Search is not listed for purchase in admin ) 
3. After purchasing - you will be redirected to /wp-admin/customize.php?autofocus[section]=jetpack_search
4. Jetpack Search section is missing from `Customize` toolbar

#### What I expected
The toolbar should show JP Search `Customize` section.

#### What happened instead
The search was not enabled. The redirect will work properly once we manually enable search by navigating to /wp-admin/admin.php?page=jetpack#/performance

**Comment by bluefuton** [comment]
Thanks for flagging this @nirmalc!

I'm not able to reproduce this using a jurassic.ninja test site. I'll try using my local Docker container too.
