### ISSUE TITLE
Instant Search: Localization doesn't work on WordPress.com sites

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#17364]
#### Steps to reproduce

Navigate and search a non-English locale site like [this](https://es.jetpack.com/?s=busca) or [that](https://wordpress.com/es/support?s=busca).

#### What I expected

Overlay interface to be translated into the appropriate locale.

#### What happened instead

- Overlay interface remains in English.
- Browser console shows an uncaught ReferenceError: `wp is not defined` when trying to call `wp.i18n.setLocaleData( localeData, domain );`.

#### Context / Source

It looks like wp.i18n is being instantiated **after** the `wp.i18n.setLocaleData` invocation.

**Comment by pauljacobson** [comment]
I have an instance of this in 3370880-zen for a user in Vietnam who would very much like to translate the text strings on the Jetpack Search buttons. Is there a workaround in the meantime?

**Comment by jeherve** [comment]
> Is there a workaround in the meantime?

I am afraid not.

**Comment by jsnmoon** [comment]
This is also being tracked in pMz3w-c5g-p2.

**Comment by jsnmoon** [comment]
There's a pending fix for this issue at D50895-code.

**Comment by jsnmoon** [comment]
The fix has been deployed (r215079-wpcom, cc @pauljacobson).

**Comment by pauljacobson** [comment]
Thank you, I've updated the user in my ticket.
