### ISSUE TITLE
Search: Add a block

### ISSUE THREAD

**Issue by KokkieH** [Automattic/jetpack#17374]
#### Is your feature request related to a problem? Please describe.

The current implementation of Jetpack Search via widget only limits where on a site a search box can be placed. Specifically, on themes that don't have a sidebar it means the search box can only be placed in the site footer.

#### Describe the solution you'd like

We've had a request for Jetpack Search to be available as a block that can be placed inside posts and pages.

#### Additional context

Requested in the dotcom forums: https://wordpress.com/forums/topic/jetpack-search-block/

**Comment by gibrown** [comment]
The core search block should also work. Is that not the case?

**Comment by KokkieH** [comment]
Oh, I didn't know about that block, and I'm guessing our forums mod don't either :D 

So if JP Search is active on the site, that block will automatically use that instead WordPress's built-in search?

**Comment by gibrown** [comment]
It should. I tested it at one point. JPS tries to use the main core search field if it is present. Could be in the theme, or a widget, or the search block.

**Comment by KokkieH** [comment]
Thanks. Then I guess this issue can be closed :)
