### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by Fi0navar** [Automattic/jetpack#17418]
It would be awesome if JetPack developed a Dark Theme for the Admin side of WP.

**Comment by jeherve** [comment]
This is most likely not something we'll implement in the Jetpack plugin. I would recommend relying on the color schemes available under Users > My Profile in your dashboard, or use plugins like [this one](https://wordpress.org/plugins/admin-color-schemes/) to add additional colors to the set of available schemes.

There are also plugins allowing you to implement a "dark mode" on your site's dashboard as well as on the frontend. Here are 2 examples:
- https://wordpress.org/plugins/dark-mode/
