### ISSUE TITLE
Search: Post types with exclude_from_search are still indexed

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#17430]
#### Steps to reproduce the issue

1. Create a custom post type with `exclude_from_search: true`
2. Create a post using the new post type
3. Search for the new post

#### What I expected
I would expect the post not to be indexed since `exclude_from_search` is set to true.

#### What happened instead

- The post appears in search results
- The post type appears in the post type filter

However, the post type does not appear in the Excluded Post Types section of the search settings, so there is no way to exclude it from search.

3387752-zen

**Comment by jeherve** [comment]
`exclude_from_search` appears to work in my tests (using Search, not Instant Search); when provided when registering the post type, the posts are then excluded from search results.

Do you think you could gather more details about this?

- Was this when using Search, or Instant Search, or both?
- Could they send us the snippet they used to register their post type?

Thank you!

**Comment by danjjohnson** [comment]
Sorry, this was from my own testing, after the user reported it on their site.

- It seems it only happens with Instant Search. The post type is excluded from regular search as expected.
- I can ask for the snippet if necessary, but in my testing I used the Custom Post Type UI plugin, with the following settings:

```
name: rate
label: Rates
singular_label: Rate
description: ""
public: true
publicly_queryable: true
show_ui: true
show_in_nav_menus: true
delete_with_user: false
show_in_rest: true
rest_base: ""
rest_controller_class: ""
has_archive: false
has_archive_string: ""
exclude_from_search: true
capability_type: post
hierarchical: false
rewrite: true
rewrite_slug: ""
rewrite_withfront: true
query_var: true
query_var_slug: ""
menu_position: ""
show_in_menu: true
show_in_menu_string: ""
menu_icon: ""
custom_supports: ""
```

**Comment by madhattermattic** [comment]
Dat sent this:

![Screen Shot 2020-10-16 at 15 39 09 (1)](https://user-images.githubusercontent.com/22449866/96298751-9a2d6f00-0fb8-11eb-9670-6dcb4b392767.png)

> We can see your selected post types do not display in the search overlay.
> 
> We'd like to access your site and check what is causing this mismatch.
> 
> Please provide us the access for SSH/SFTP/FTP of your site including: server address, username, password (or SSH key), and port in the following form.
> 
> Make sure that this SSH/SFTP/FTP user has access to your WordPress installation folder. You can ask your host if you have no idea where to look for this info.

However, the user got very upset and replied with this:

> Surely this must be a joke. You just sent me a screenshot illustrating that the overlay shows Posts and Pages both available in the overlay, after I just sent a screenshot of my customizer settings showing the "Excluded Post Types" leaving Posts and Pages unchecked. This has, yet again, nothing to do with my actual question, and is the expected behavior. We'd love to stop wasting time continuing this conversation that is leading nowhere. Is it possible to speak to someone on the phone? If not, we may have to look to a forum or something, or simply give up, since this has been such an absolute waste of time and energy. Hope you understand. Please let me know if it's possible to speak to someone.

All this being said, I have told them that we absolutely need these creds to have a deeper look, so I'm asking them again and we should wait until we have those.

However, he did confirm that Kristina grasped the problem correctly when she said:

> You are using Jetpack Search on this site: https://rmlefcu.org/. The question about the rates and rate-groups custom post-types was resolved by setting exclude_from_search to false. However, one issue remains.
> 
> You want one of the search overlays show only blog posts, but right now it shows posts and pages. You are using a link with custom parameters to trigger the overlay. It looks like this: <a href="#" class="jetpack-search-filter__link" data-filter-type="post_types" data-val="post" >Search Posts</a> You want to know if the "excluded post types' settings impact all instances of the overlay including the overlays triggered by that link.
> 
> If I understand that correctly, the answer is that they do. Those settings in the Customizer widget override any parameter in the link. IF a post type is excluded in the Customizer settings, that post type will not show up in the search results of a link - even if that link uses the custom parameter for that post type.
> 
> For example:
> 
> - IF posts are excluded in the Customizer widget, & the overlay link has the parameter for posts, posts WILL NOT show up in the search results.
> - On the flip side of that, IF NO post types are excluded in the Customizer widget & the overlay link has the parameter for posts, ONLY posts WILL show up in the search results.
> 
> If you want to display only certain post types on certain pages, that is possible, but only if those post types are enabled in the Customizer widget. I tested this on my test site. I hope that makes sense.

So please keep in mind that, once we get the creds, that THIS ^ is the actual problem that needs looked into at the moment. Thanks!

**Comment by robfelty** [comment]
I tested this today by spinning up a new test site, and registered a custom post type in the themes functions.php file like so:
```
add_action( 'init', 'my_cpt_init' );
function my_cpt_init() {
    register_post_type( 'foobar', [
		'exclude_from_search'=>true,
		'show_in_menu'=> true,
		'menu_position' => 5,
		'show_ui' => true,
		'label' => 'foobars',
	] );
}
 
add_action( 'after_switch_theme', 'my_rewrite_flush' );
function my_rewrite_flush() {
    my_cpt_init();
    flush_rewrite_rules();
}
```
I created one post of the type "foobar". 
I verified that the custom post type was synced to the shadow site, and that it does not get indexed at all. The default hello world and about page did get indexed.

I think we can mark this one closed. Do you agree @danjjohnson ?

**Comment by gibrown** [comment]
Marking this one closed.
