### ISSUE TITLE
General: Replace older-style PHP type conversion functions with type casts

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#17432]
In coordination with Core's latest change in [this ticket](https://core.trac.wordpress.org/ticket/42918), let's aim to clean things up in Jetpack as well: let's replace all instances of `intval()`, `strval()`, and `floatval()` by type casts( `(int)`, `(string)`, `(float)`.

https://core.trac.wordpress.org/changeset/49108

**Comment by annafoldvari** [comment]
Hello, I am happy to work on this. Is there a way to indicate I am working on it?

**Comment by jeherve** [comment]
> Is there a way to indicate I am working on it?

I think you just did :) 

Feel free to split the work into multiple Pull Requests if you'd like, that will make things easier to review.

**Comment by kraftbj** [comment]
Related: I'm proposing adding these to the `WordPress-Extra` coding standard: https://github.com/WordPress/WordPress-Coding-Standards/pull/1955
