### ISSUE TITLE
Video Block: video does not resize when inside a column block

### ISSUE THREAD

**Issue by joweber123** [Automattic/jetpack#17465]
### Steps to reproduce

1. Add a column block to the page.
2. Inside of this column block add a video block.

#### What I expected
I expected the video block to resize to the width of the column.

#### What happened instead
The video block is cutting off the video and displaying full height.

#### Browser / OS version
Firefox/Mac OS Catalina

#### Screenshot / Video
![video_block](https://user-images.githubusercontent.com/24914028/83478954-25a6d780-a4d2-11ea-9735-3afc51e941b8.png)

#### Context / Source
3021461-zen

**Comment by cpapazoglou** [comment]
Created a here https://github.com/Automattic/jetpack/pull/17464 a PR that resolves the editor issues.
I am checking the frontend now.

**Comment by cpapazoglou** [comment]
Fixed both in Editor & Frontend. Bare in mind that users will need to update their posts for this change to take effect.
