### ISSUE TITLE
Image Block: External media source icons in the wrong spot

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#17476]
I mentioned this issue in a comment here https://github.com/Automattic/jetpack/issues/17472, but it was missed.

#### Steps to reproduce the issue
1. Create a new post or a page. Add Image block.
2. Pick an image from the media library or upload a new one.
3. Look at the block settings in the sidebar, scroll to the bottom of the "Image settings" section.
4. Note how the external media source icons (Google Photos, Pexels) are to the right of the text, which in the context of the sidebar looks off - they are too far removed from the corresponding label.
5. Also note the text itself is not aligned with other elements.

**Screenshots**
![image](https://user-images.githubusercontent.com/4550351/95929295-619e6180-0e0f-11eb-93ca-535a6602ca82.png)

**Comment by jeherve** [comment]
Good catch, sorry for missing that one!

**Comment by obenland** [comment]
That seems to be an incompatibility with a Coblocks feature.
