### ISSUE TITLE
Add schema.org markup to social share buttons

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#1748]
Would like to support schema for the social sharing buttons provided by Jetpack.
https://schema.org/interactionCount

**Comment by jkudish** [comment]
@aduthie any thoughts on this?

**Comment by jkudish** [comment]
Tagged the wrong person above. So sorry. @aduth

**Comment by kraftbj** [comment]
That schema item superseded by https://schema.org/interactionStatistic

**Comment by aduth** [comment]
What's the proposed benefit of adding the schema?

Is there any precedent of services including these in their official buttons?

**Comment by bhubbard** [comment]
Closing this issue, I haven't found any use of this in the wild.
