### ISSUE TITLE
Pay With PayPal Widget: Widget has display issues in the new block-based widgets page.

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#17483]
Gutenberg 9.1 allows us to test the new block-based widgets page.

Existing Pay With PayPal widgets, while showing up fine in the current core widgets page, will not display in the new interface:

Current | Block-Based
--- | ---
<img width="550" alt="Screen Shot 2020-10-14 at 10 55 35 AM" src="https://user-images.githubusercontent.com/349751/96027515-d623d100-0e0c-11eb-9c72-c5919919f97f.png"> | <img width="819" alt="Screen Shot 2020-10-14 at 10 47 38 AM" src="https://user-images.githubusercontent.com/349751/96026575-85f83f00-0e0b-11eb-937c-32301b53a736.png">

Adding a new widget will result in an empty Edit view, but a populated Preview. The Edit view should have a dropdown that allows choosing an existing PayPal button.

![2020-10-14 10 58 41](https://user-images.githubusercontent.com/349751/96027370-a4126f00-0e0c-11eb-9a70-af564aaccdf6.gif)

**Comment by jeherve** [comment]
Related issue: #17062

**Comment by mmtr** [comment]
@kwight seems to work me:

![Oct-15-2020 13-49-14](https://user-images.githubusercontent.com/1233880/96119610-8963f700-0eed-11eb-9c8f-7c79b094e103.gif)

These are the steps I followed:
- [Create a JN site](https://jurassic.ninja/create/?jetpack-beta).
- Set up Jetpack and purchase a Jetpack Security plan.
- Install latest version of Gutenberg (currently 9.1.1).
- Enable widgets in Jetpack > Settings > Writing:
<img width="1065" alt="Screen Shot 2020-10-15 at 13 44 10" src="https://user-images.githubusercontent.com/1233880/96119572-78b38100-0eed-11eb-8890-be6d337f3ee2.png">

- Go to Appearance > Widgets.
- Add a Pay with PayPal widget.

**Comment by kwight** [comment]
Ah, I was testing on a Simple site – will confirm.

**Comment by kwight** [comment]
Yep, confirmed – Jetpack standalone looks fine, I'm seeing the problem on Simple sites. Moved to https://github.com/Automattic/dotcom-manage/issues/275.
