### ISSUE TITLE
Add Houzz Button to Jetpack Sharing

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#1749]
Would like to see support for the houzz button in jetpack sharing:
http://www.houzz.com/buttonsAndBadges/page=houzzbutton

**Comment by georgestephanis** [comment]
related: https://github.com/Automattic/jetpack/issues/449

**Comment by jkudish** [comment]
I think this is too niche for us to add. I'd suggest users use the "custom button" option to add this to their site.

**Comment by andymb** [comment]
Houzz requires certain data attributes within the link to verify site ownership and the Jetpack interface isn't sufficient to add these. https://www.houzz.co.uk/buttonsAndBadges/button
