### ISSUE TITLE
Pay With PayPal Block: Empty blocks are displayed on the front-end with `NaN` for price.

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#17505]
Users can publish an empty Pay With PayPal block if they like, but if they do, we'll show a price with a lovely `NaN` value. 🙃 

![2020-10-16 12 16 02](https://user-images.githubusercontent.com/349751/96300835-1a4cd800-0fab-11eb-8e1d-a6e230206c72.gif)

**Comment by retrofox** [comment]
addressed here r215467-wpcom
