### ISSUE TITLE
Pay with Paypal block: saving with empty price is crashing the block

### ISSUE THREAD

**Issue by razvanpapadopol** [Automattic/jetpack#17502]
#### Steps to reproduce the issue

1. Go to block editor to edit a page or post.
2. Add Pay with Paypal block or edit a previously added block.
3. Leave the price input empty or remove its existing value.
4. Save the page/post.
5. After reload, the block is crashing.

#### What I expected
User should be able to leave the price empty when saving the page and not crash the block or page when opening it later.
Demo: https://cloudup.com/cAdKRiaJx3w

#### What happened instead
The block (and for some pages the whole block editor; eg: [Balasana homepage design](https://cloudup.com/c7XlrT5Xn0f)) crashed when reloading after:
1. user removed the price of a previously added block with all inputs valid. Demo: https://cloudup.com/cldTuvhLuXA
2. user added a new block and doesn't entered price. Demo: https://cloudup.com/coML1WSZslW

**Screenshots**
<img width="460" alt="Screenshot 2020-10-16 at 16 27 29" src="https://user-images.githubusercontent.com/14192054/96278306-02db1280-0fde-11eb-8246-dc7e0189cc4d.png">

**Comment by kwight** [comment]
It looks like this is a problem specific to WordPress.com; I couldn't replicate on a new JN site.

![2020-10-16 12 16 02](https://user-images.githubusercontent.com/349751/96300593-a27ead80-0faa-11eb-86b5-2271c4345a4d.gif)

This issue has been moved to https://github.com/Automattic/dotcom-manage/issues/276, with the `NaN` output reported in https://github.com/Automattic/jetpack/issues/17505

**Comment by retrofox** [comment]
Let me re-open this issue since it needs to be fixed here in the Jetpack plugin.

**Comment by retrofox** [comment]
Closing it again because the code is not completely synced with wpcom. This issue is being handled by D51442-code, but we should be aware we need to deal with this after the next release. [Here more context](https://github.com/Automattic/jetpack/pull/17393#issuecomment-711789180).
cc @jeherve, and please let me know if I can help with this, creating a sync PR or whatever.

**Comment by retrofox** [comment]
fixed r215467-wpcom

**Comment by jeherve** [comment]
> This issue is being handled by D51442-code, but we should be aware we need to deal with this after the next release. Here more context.

Yes, I think we should bring the changes from D51442-code into Jetpack.

**Comment by retrofox** [comment]
> > This issue is being handled by D51442-code, but we should be aware we need to deal with this after the next release. Here more context.
> 
> Yes, I think we should bring the changes from D51442-code into Jetpack.

Sorry, would you like me to do this 😅 , or it's something that the Jetpack crew is going to take over?

**Comment by jeherve** [comment]
> Sorry, would you like me to do this 😅 , or it's something that the Jetpack crew is going to take over?

Merging #17531 should be enough I think!

**Comment by retrofox** [comment]
> > Sorry, would you like me to do this 😅 , or it's something that the Jetpack crew is going to take over?
> 
> Merging #17531 should be enough I think!

Correct, in the end, we'll have to sync once the new release lands.

**Comment by jeherve** [comment]
> we'll have to sync once the new release lands

👍 Should happen in D50729-code on release day.
