### ISSUE TITLE
Contact Form: Allow Contact Form to be used in sidebar

### ISSUE THREAD

**Issue by RCowles** [Automattic/jetpack#17520]
We had a request in 3413556-zen to allow Jetpack's Contact Form to be used in a sidebar as a widget. This was previously possible by inserting a Contact Form shortcode in any widget that filters content with `do_shortcode()`. However, this is no longer possible with the latest version of Jetpack and WordPress.

#### Describe the solution you'd like

Allow a Jetpack Contact Form to be added to a widget area.

#### Describe alternatives you've considered

As a workaround, users can create a Contact Form Block and use the [Block Widget](https://wordpress.org/plugins/block-widget/) plugin to add a Contact Form widget.

**Comment by jeherve** [comment]
I still see to be able to add a contact form in a widget area. I just tested with a Text widget and it seemed to work.
![image](https://user-images.githubusercontent.com/426388/96586069-babf3700-12e0-11eb-9791-fa3355165726.png)

![image](https://user-images.githubusercontent.com/426388/96586086-c3b00880-12e0-11eb-9e57-0dc9e034c187.png)


I'd recommend trying with the Text widget, and not with an HTML widget which will not process shortcodes.
