### ISSUE TITLE
Add schema.org support to social links

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#1753]
Would like to support schema for social links. Need option to add `itemprop="sameAs"` in the urls.

http://jetpack.me/support/social-links/
https://developers.google.com/structured-data/customize/social-profiles

**Comment by jeherve** [comment]
Since you build the links yourself in your theme, that's probably not something we need to handle in Jetpack itself. In your theme, you can do something like this:

```php
<a itemprop="sameAs" href="<?php echo esc_url( get_theme_mod( 'jetpack-facebook' ) ); ?>">
    <?php _e( 'Facebook', 'textdomain' ); ?>
</a>
```
