### ISSUE TITLE
Widget visibility is not working with buddyboss-platform

### ISSUE THREAD

**Issue by AiratHalitov** [Automattic/jetpack#17555]
**Describe the bug**
When buddyboss-platform plugins is active Jetpack widget visibility module's button doesn't showing in widgets.

**To Reproduce**
1. Install [Jetpack plugin](https://wordpress.org/plugins/jetpack/) and enable Widget Visibility module (`/wp-admin/admin.php?page=jetpack_modules`)
2. Go to widgets page (`/wp-admin/widgets.php`) and try to change widget visibility
3. Install and activate [buddyboss-platform](https://github.com/buddyboss/buddyboss-platform) and try to change widget visibility again
4. The visibility button will disappear (`style="display: none;"` will be added)

**Expected behavior**
`style="display: none;"` shouldn't be added to elements

**Screenshots**

Widget Visibility:

![widgets](https://user-images.githubusercontent.com/4050715/90403927-155acd80-e0bb-11ea-95a6-f00a72c9e943.gif)
---

Related: https://github.com/buddyboss/buddyboss-platform/issues/1365

**Configuration:**

- buddyboss-platform v1.5.3
- Jetpack v9.0.2
- WordPress v5.5.1

**Comment by jeherve** [comment]
This seems to happen within the Buddyboss plugin, here:
https://github.com/buddyboss/buddyboss-platform/blob/cfc0def7d95ad8a65455f67032dcf9d379824663/src/bp-core/admin/js/settings-page.js#L494-L505

That's something that will need to be fixed within that plugin I think.

I'll comment on the other issue about this, hopefully it helps a bit.

**Comment by AiratHalitov** [comment]
@jeherve 
Thanks for quick response!
