### ISSUE TITLE
Tracking: add a README for the package

### ISSUE THREAD

**Issue by kbrown9** [Automattic/jetpack#17569]
#### Is your feature request related to a problem? Please describe.
The Tracking package needs better documentation.

#### Describe the solution you'd like
- Add a README doc for the Tracking package.
- Add a note to the legacy `Jetpack_Tracks_Event` that instructs developers to use the `Tracking` class instead.

**Comment by jeherve** [comment]
Somewhat related: #15929

**Comment by leogermani** [comment]
I'll use the tracking package for the [upgrade nudges project](p1HpG7-cfa-p2) and will review the docs we have and add them to the package.
