### ISSUE TITLE
Cookie Widget: Uncaught TypeError: Cannot read property 'hasAttribute' of null

### ISSUE THREAD

**Issue by drbiskit** [Automattic/jetpack#17560]
Steps to reproduce the issue:
1. Go to https://limpingchicken.com
2. Check console for error:
eu-cookie-law.min.js Uncaught TypeError: Cannot read property 'hasAttribute' of null

Details:
After updating to the most recent version of Jetpack, this js error started happening.  The 'Privacy and cookies' panel can now not be closed by clicking on the 'Close and accept' button - Am presuming this is as a result of/connected to this error.

Everything is up to date on the site (at time of writing).

**Comment by jeherve** [comment]
Related: #15839, #16625, #16666
