### ISSUE TITLE
Protect: Needs better IPv6 handling

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#17566]
#### Steps to reproduce the issue

1. Run `jetpack_clean_ip` on an IPv6 URL. (example `2001:db8:a0b:12f0::1` )

#### What I expected
The IP to be returned.

#### What happened instead
The initial `2001:` has been stripped.

It is being caused by a bug with `parse_url`. It doesn't handle IPv6 very well: https://github.com/php/php-src/pull/2079

The 2001 is being parsed by PHP as the scheme, as it proceeds the initial colon and there is no scheme present. But, adding a fake scheme (`https://` for the sake of conversation) also produces a problem:
```
>>> $parsed_url = parse_url( 'https://2001:db8:a0b:12f0::1');
=> [
     "scheme" => "https",
     "host" => "2001:db8:a0b:12f0:",
     "port" => 1,
```
and cuts off the end of the IP address.

**Comment by anomiex** [comment]
Note that to use an IPv6 literal as the host in a URL, it would need to be `https://[2001:db8:a0b:12f0::1]`. Without the brackets, it's invalid according to RFC 3986.

Why is `jetpack_clean_ip` using `parse_url` in the first place? ... I see it was added in #7048 to try to avoid breaking IPv6 IPs when removing ports, but it's not clear to me how that ever actually worked. In turn that was trying to fix #6755, which has no details but [a comment](https://github.com/Automattic/jetpack/pull/6755#issuecomment-296220047) claims that "some server configurations" somehow include a port in `$_SERVER['REMOTE_ADDR']`.

**Comment by jeherve** [comment]
> "some server configurations" somehow include a port in $_SERVER['REMOTE_ADDR'].

This specific use-case (and the cause of the PR) can be found in 131-gh-jpop-issues

**Comment by anomiex** [comment]
> This specific use-case (and the cause of the PR) can be found in 131-gh-jpop-issues

Ah, that's about X-Forwarded-For, not `$_SERVER['REMOTE_ADDR']`.
