### ISSUE TITLE
Lazy Images: Improve JS handling

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#17562]
Originally reported in https://github.com/Automattic/jetpack/pull/17489#issuecomment-713520423 via @ockham regarding the Lazy Image package JS.

* We're only bundling code here (through Webpack), not transpiling it (through Babel). This means that statements like const end up in built files, as detected by the ES5 validation script.
* We're dropping our built files (*.min.js) into src/, rather than a separate location.
* We're adding built files to GH.
* We're including the Interaction Observer polyfill verbatim.

In order to fix these issue, [he] suggests

* using calypso-build (which takes care of transpilation, and by default drops files into a separate build/ directory, thus resolving items 1. and 2.)
* deleting built files from GH, and adding the build/ subdirectory to .gitignore in order to prevent that from happening in the future
* adding the Interaction Observer npm to package.json (rather than copying it verbatim)
* Revert https://github.com/Automattic/jetpack/pull/17561 to re-enable validation.

**Comment by kraftbj** [comment]
One thing we'd need to figure out is since this is a Composer package, it is likely expected to be consumed by other plugins without the need to incorporate it into a JS build step? (the original push to get this into a package was for a non-Jetpack consumer: https://github.com/Automattic/jetpack/pull/16657 )

In either case, removing it would break BC for consumers, so that needs to be handled in some way.

**Comment by jeherve** [comment]
> We're dropping our built files (*.min.js) into src/, rather than a separate location.
> We're adding built files to GH.

I think this is fine. We'd want the package to be ready to use by anyone adding the package to their composer.json file.

**Comment by jeherve** [comment]
> using calypso-build

We should be able to update `webpack.config.packages.js` to start transpiling things, that should solve our issue here and ensure that the Lazy Images lib. can be used in old browsers again.
