### ISSUE TITLE
Stats: add option to display views for each post on the frontend

### ISSUE THREAD

**Issue by JenSwish** [Automattic/jetpack#17588]
#### Is your feature request related to a problem? Please describe.
Would like to be able to show the number of times a post has been viewed since it was published on all site posts, using the data from Jetpack stats. 

#### Describe the solution you'd like
Would like to be able to turn on/off the feature to show post counts on individual posts and post archive pages.

#### Describe alternatives you've considered
There are some plugins available that do this, but they don't pull their data from Jetpack stats, so the post counts start from the point the plugin was activated. 

#### Additional context
Many of these plugins require a shortcode be added to every post, which is very cumbersome if the site has a large number of posts.

**Comment by jeherve** [comment]
Until this is implemented in Jetpack, I would recommend using [this plugin](https://wordpress.org/plugins/post-views-for-jetpack/): it relies on Jetpack Stats data, and its shortcode can be placed in your theme's template files so you won't have to add it manually to each post.

**Comment by jeherve** [comment]
Also requested in https://github.com/Automattic/wp-calypso/issues/63584

- 5210255-zen

**Comment by Aurorum** [comment]
I've been messing around with blocks and Stats a lot lately, so I'd like to take a stab at converting the legacy widget to a block and adding this, if that's okay. :)
