### ISSUE TITLE
Issue with Akismet button in Jetpack Dashboard

### ISSUE THREAD

**Issue by squirk** [Automattic/jetpack#1759]
In the new Jetpack dashboard widget, the Akismet button isn't working.  The link appear to link to ```/wp-admin/index.php#```.    Once Akismet is activated via the plugins page, the button disappears – even if you haven't obtained an API key.  I assume there should be a message that you need to configure Akismet.

![jetpack-akismet](https://cloud.githubusercontent.com/assets/3333136/6625891/60d05948-c8c9-11e4-8b41-da94647ca283.png)

**Comment by georgestephanis** [comment]
Yeah, I hadn't fleshed that out.  About to.
