### ISSUE TITLE
Subscription Management

### ISSUE THREAD

**Issue by ghost** [Automattic/jetpack#176]
Hey! I'm really loving Jetpack right now, but is there any chance that we'll be able to see updates to the subscriptions part of the plugin? Features like adding subscribers to a list manually and managing subscriber lists are things that I'd really like to see added in the future. Is there any possibility of this coming soon? Please let me know, thanks :D

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/suggestion-for-the-plugin-e-mail-subscriptionnotification?replies=1

**Comment by beaulebens** [comment]
It would also be good if we tracked and displayed how many time an email has bounced, so that site owners could keep on top of things. Even better would be to just auto-remove emails if they bounce too many times.

**Comment by syzygy-org** [comment]
the party line at jp appears to be a simple 'they will subscribe again, or use RSS'
That's NOT the point. RSS can be cut off, easily if abused. I can kill WP Users if abused. 
It is simple interpersonal logic that an owner of content can observe and handle inappropriate behavior. If repeated, then the duty of the owner is to 'handle' as many times as needed.

I can point to dozens of non WP sites that the owner/manager have to take out the garbage periodically. It is obvious if someone repeat-subscribes. One of mine loved to adverb her adverbs. simple.

now, can we put this 7 year old hole in WP/JP to bed with a quick fix?

**Comment by kraftbj** [comment]
Closing this as it is being worked on outside of Jetpack. Preview: https://horizon.wordpress.com/people/followers/
