### ISSUE TITLE
Slideshow Block: Block breaks in Editor when set to Full Width

### ISSUE THREAD

**Issue by ockham** [Automattic/jetpack#17616]
#### Steps to reproduce the issue

1. Enable the Gutenberg plugin (version 9.2.2).
1. Insert the Slideshow block into the editor, and add a few images.
1. Set the block to full width.

#### What I expected
The block to work.

#### What happened instead
The block disappears; only the left/right slideshow controls remain

**Screenshots**
![slideshow JP](https://user-images.githubusercontent.com/96308/97222566-e6ee2280-17ce-11eb-8b91-156350148273.gif)

**Notes**

The bug is not present when the Gutenberg plugin (v9.2.2) isn't enabled. This suggests that it might be related to the recent `block-supports` rewrite (as issues with `block-supports` tend to affect blocks that are set to full-width alignment).

Note the inline styling in the browser console in the above screencast: When changing the block layout to 'Full Width', two numeric values (for the `width` and `transform` attributes) are assinged weird floating point numbers that probably don't work in CSS :grimacing: 

AFAIK, that inline styling is provided by the Swiper library that we use to implement the Slideshow block, and added to the [HTML element with the `swiper-wrapper` class](https://github.com/Automattic/jetpack/blob/64e29549270bee9f6f9aa29a8ff92e48e899b207/extensions/blocks/slideshow/slideshow.js#L138). I suspect that the lib is attempting to read some dimensions from the block but gets them wrong and thus ends up settings those weird values.

Also note that the block toolbar isn't aligned with the block (rather than sitting right on top, it is the very left of the editor; it's more visible on a wide screen). This could be related to the same issue -- some dimensions being incorrectly computed.

This bug also affects WP.com. It has been discussed here: p1603739210304100-slack-C015AL3QL7M

cc/ @TheSteveK @eduardozulian @fullofcaffeine @nosolosw

**Comment by katiebethbrown** [comment]
Another report in 3284766-hc. Worth noting that it breaks the remaining content in the editor as well. Changing the slideshow to wide width returns things to normal so the page can be edited.

**Comment by nielslange** [comment]
Another report in 25186634-hc.

**Comment by nielslange** [comment]
Another report in 25193575-hc

**Comment by nosolosw** [comment]
:wave: I've bisected this error to this PR https://github.com/WordPress/gutenberg/pull/25884 which was part of the 9.2 release Pinging @jeyip as he may have some more knowledge what happened there that affected this.

**Comment by ockham** [comment]
cc/ @Automattic/cylon :slightly_smiling_face:

**Comment by Copons** [comment]
<img width="313" alt="Screenshot 2020-10-27 at 16 46 20" src="https://user-images.githubusercontent.com/2070010/97333876-f4a9b380-1873-11eb-90a3-88e38a3559c3.png">

33554400 pixel wide.

![bc90b8e94e2aafe0](https://user-images.githubusercontent.com/2070010/97334032-215dcb00-1874-11eb-8d8a-92f006608b80.gif)

**Comment by ockham** [comment]
> ![bc90b8e94e2aafe0](https://user-images.githubusercontent.com/2070010/97334032-215dcb00-1874-11eb-8d8a-92f006608b80.gif)
> 
> This doesn't look exactly right (but I've yet to figure out where these values come from)...
> 
> <img alt="Screenshot 2020-10-27 at 16 58 04" width="402" src="https://user-images.githubusercontent.com/2070010/97335432-c0cf8d80-1875-11eb-898a-15eaa3ad30a4.png">

I had a theory that I mentioned in the PR desc, not sure you saw...

**Comment by Copons** [comment]
> I had a theory that I mentioned in the PR desc, not sure you saw...

Apologize, I commented while doing other things and somehow missed the second half of the PR description. 🤦 

I didn't even realize it was importing an external library, and looking at `node_modules/swiper/swiper-bundle.js`, those styles are indeed added by that (to `$wrapperEl`).


One extremely suspicious detail is that the block width seems to **always** be `33554400px`, which in scientific notation would be `3.35544e7` (or `3.35544e+07`, AFAIK are valid values in both JS and CSS), which is what ends up in the wrapper's `translate3d` and the slide's `width`.

**Comment by edequalsawesome** [comment]
Another report in 4752856-hc

**Comment by jartes** [comment]
Another report in 21476315-hc

**Comment by jartes** [comment]
And another one here 3439767-zen

**Comment by khristiansnyder** [comment]
Another in 25208641-hc

**Comment by eoinsav** [comment]
Another report of a user not able to edit their Pages because they all have Slideshow Blocks on them: #20607867-hc

**Comment by davipontesblog** [comment]
Another report: 8848011-hc

**Comment by Copons** [comment]
I've opened a PR in Gutenberg that seems to fix this issue: https://github.com/WordPress/gutenberg/pull/26552.

@Automattic/good-mountain As mentioned elsewhere, we might need to bring it into JP immediately, rather than wait for the PR to get approved and included in the next Gutenberg release.

**Comment by davipontesblog** [comment]
Thanks @Copons ! I agree, I don't think this can wait for a Gutenberg release, it completely breaks the editor.

**Comment by ockham** [comment]
Thanks a ton, @Copons! I'll file a JP PR for now.

**Comment by JessBoctor** [comment]
Had another report in #25238205-HC

**Comment by ockham** [comment]
> Thanks a ton, @Copons! I'll file a JP PR for now.

https://github.com/Automattic/jetpack/pull/17645
WP.com counterpart: D51956-code

I'll merge the WP.com counterpart soon, since this is affecting a lot of users.

**Comment by ockham** [comment]
> I'll merge the WP.com counterpart soon, since this is affecting a lot of users.

r216021-wpcom

**Comment by eduardozulian** [comment]
@ockham can you confirm if this also fixes AT sites? I just chatted on 23423694-hc and the issue persists unless I disable Gutenberg.

**Comment by ockham** [comment]
> @ockham can you confirm if this also fixes AT sites? I just chatted on [23423694-hc](https://href.li/?23423694-hc) and the issue persists unless I disable Gutenberg.

It will, but only once a Jetpack version that includes this fix is released (or a Gutenberg version that includes WordPress/gutenberg#26552 is released) and installed on Atomic. The next JP release is scheduled for November 10 -- if we need a fix for AT earlier, we'll have to ship it through a different vector (wpcomsh) :thinking:

**Comment by Copons** [comment]
An update from Gutenberg side: we are pondering if reverting the change (https://github.com/WordPress/gutenberg/pull/25884) that introduced this issue.
It's a bit of a pain, as we have merged a bunch of PRs relying on it, but still.

The workaround used here (https://github.com/Automattic/jetpack/pull/17645) would NOT be affected by a revert, nor would it cause any regressions, as the `.interface-interface-skeleton__editor` element has been introduced in https://github.com/WordPress/gutenberg/pull/25884.
Once reverted, the JP fix would simply cease working, and it will be possible to just simply delete it.

I'll keep y'all updated with whatever we'll end up doing!

**Comment by mikeicode** [comment]
Another 23174703-hc

**Comment by mikeicode** [comment]
Another 25305689-hc

**Comment by Copons** [comment]
Well, I totally forgot to keep y'all updated as promised, but just as a heads up, this should be fixed everywhere for a few weeks now.
The fix has been merged separately in:

- Gutenberg
- Jetpack
- Editing Toolkit

so it should cover any possible site type.
Given it's a one-line CSS fix, I think it's not a big deal to have it in 3 different places at the same time for now.
