### ISSUE TITLE
Jetpack Setting Modal for Gravatar Hovercards looks off

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#1762]
Just notices that the Modal for Gravatar Hovercards looks broken
![image](https://cloud.githubusercontent.com/assets/115071/6628883/5d7ea63a-c8c6-11e4-9c6c-e440a0c0197a.png)

**Comment by jeffgolenski** [comment]
Got it covered. h5 was clearing everything instead of just left items.

**Comment by jeffgolenski** [comment]
fixed: https://github.com/Automattic/jetpack/commit/125334263b89f4d5a598c42466ff27edddfeb209
