### ISSUE TITLE
Search: Set a maximum number of taxonomies to auto config

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#17630]
If the site has a lot of taxonomies (the one I came across has hundreds) then the auto config will add hundreds of filters to the sidebar in the overlay. The search query will then have 100s of aggregations that are requested and our API (correctly) rejects such a request.

I think we should auto config at most 3 custom taxonomies here: https://github.com/Automattic/jetpack/blob/master/modules/search/class-jetpack-instant-search.php#L543

We could also add some limits to our api code to prevent the search from being completely broken if the user tries to do this manually, and adjust the error message from "It looks like you're offline. Please reconnect for results." I think we get that message because trying to do a GET request that is 100k characters long completely fails.

**Comment by bluefuton** [comment]
> We could also add some limits to our api code to prevent the search from being completely broken if the user tries to do this manually

D53600-code implements this check.
