### ISSUE TITLE
Pay with PayPal Block: quantity field is not always clear

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#17639]
> When viewing a published block on the front end, the quantity box is a little confusing. There’s just a number, which isn’t super clear that it’s a quantity box that can be changed. The up/down arrows appear when hovering over the quantity box, so maybe making those arrows more permanent would clarify it without the need for a “quantity” label.

![image](https://user-images.githubusercontent.com/426388/97478984-019cd480-1952-11eb-8e5b-1c23bbca74af.png)

------

p8oabR-za-p2#comment-4693

**Comment by rcrdortiz** [comment]
Firefox and Safari show the arrows by default, this issue only needs to be fixed for Google Chrome.
