### ISSUE TITLE
[Gutenberg WPCOM e2e tests i1] Change GB E2E test task to always use the latest GB

### ISSUE THREAD

**Issue by fullofcaffeine** [Automattic/jetpack#17642]
Project: pc9Uba-8b-p2
Tracking issue: https://github.com/Automattic/wp-calypso/issues/46583

As part of #46583, we want to make sure each upstream repo that hosts blocks constantly and consistently runs its E2E tests on the latest available GB release. JP set a good precedent by implementing a [job](https://github.com/Automattic/jetpack/pull/15784) to run its E2E tests on the latest GB stable. The idea here though is to run on the latest available release on Github, stable or RC.

This could be a new job or it could replace the existing one. Thoughts?

We should also document when GB tests are running - when does the job run? Does it run as part of PRs checks by default? Does it need a special tag? What about recurring runs, does it run periodically?

**Comment by jeherve** [comment]
cc @brbrr

**Comment by ockham** [comment]
> cc @brbrr

Note that this could be good trial material cc/ @bsessions85

**Comment by fullofcaffeine** [comment]
@brbrr I think we can close this one, right?

**Comment by fullofcaffeine** [comment]
This was solved by https://github.com/Automattic/jetpack/pull/19132. Thanks @brbrr!
