### ISSUE TITLE
Tracking: Notice during the E2E tests

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#17651]
### Steps to reproduce the issue

Not sure how to reproduce it manually, but here is the log:

```
Notice:  Trying to access array offset on value of type bool in /var/www/html/wp-content/plugins/jetpack-dev/vendor/automattic/jetpack-tracking/src/class-tracking.php
```

It happens quite often (maybe every time), so it should be easy to replicate via E2E tests

**Comment by anomiex** [comment]
Tracking package has been abandoned and merged into the Connection package. See #23448.
