### ISSUE TITLE
Pay with PayPal Block: layout issues in subscription emails 

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#17655]
#### Steps to reproduce the issue

Start with a Jetpack site connected to WordPress.com, with a Paid plan, and the Subscriptions module active.

1. Go to Posts > Add New, and publish a new post with a subscription block.
2. Subscribe to your own site using that block.
3. Publish a new post with a Pay with PayPal block.
4. You'll notice some layout issues in the email

![image](https://user-images.githubusercontent.com/426388/97616659-1d20e180-1a1d-11eb-8b9a-6dd20b9e14a0.png)

This was in Chrome, using Gmail.

-------

p8oabR-za-p2#comment-4734

**Comment by rcrdortiz** [comment]
Hi @jeherve, I've tested this issue and it seems to be solved already. Can you reproduce it? Maybe I'm doing something wrong.

**Comment by jeherve** [comment]
This was a while ago, so may have been fixed. Closing, we can always reopen later if necessary.
