### ISSUE TITLE
Jump Start: Success message repeats itself

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1766]
![screen shot 2015-03-13 at 8 04 58 am](https://cloud.githubusercontent.com/assets/3220162/6640943/ebea54a0-c957-11e4-9752-ed22650b2d9f.png)

Having successfully "jump started" my site, I feel like the text "Jump Start your site" should be removed for just "Success! You've jump started your site."

Example:
![screen shot 2015-03-13 at 8 32 17 am](https://cloud.githubusercontent.com/assets/3220162/6641524/7afa7de8-c95b-11e4-9569-492aea0720a0.png)

**Comment by jessefriedman** [comment]
Can you please confirm this problem exists? I have not been able to duplicate it 
![screen shot 2015-03-16 at 9 04 59 am](https://cloud.githubusercontent.com/assets/1749986/6666517/9b411dc0-cbbb-11e4-8ac2-a04815be9af2.png)

**Comment by jeherve** [comment]
I can't reproduce it either.

**Comment by mikeyarce** [comment]
Updated to the latest Beta and it looks good now.
