### ISSUE TITLE
Instagram Block:  Improve URL handling for "Reels"

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/jetpack#17662]
Instagram Reels use a slightly different URL from standard Instagram videos, and does not work in the Instagram block.

For example, this URL does not work:  https://www.instagram.com/reel/CG7PQkGhA8J/
Whereas this URL does seem to work:  https://www.instagram.com/p/CG7PQkGhA8J/

#### Steps to reproduce the issue

1. Go to Gutenberg and add Instagram block
2. Add URL from an Instagram reel (https://www.instagram.com/reel/CG7PQkGhA8J/) and attempt to embed
3. Error message in block:  Sorry, this content could not be embedded.
4. Edit the URL to change reel to p and try again
5. Video is embedded as expected

See screencast of the issue here:  https://d.pr/v/9ZP5tN

Also worth noting that Instagram does not allow Reels to be viewed as on other sites, so the resulting (successful) embed displays the video frame, but with a "play on Instagram" player button.  An argument can be made that due to this we should block Reels from being embedded, and show more specific error message like "Instagram Reels cannot be embedded" instead.

**Comment by donalirl** [comment]
Had a request for this in #25227934-hc
