### ISSUE TITLE
Pay with PayPal Block: Product image icon alignment issue

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#17664]
> Icon from the Product Image doesn’t align to the left with the Upload button and the Media Library link

![image](https://user-images.githubusercontent.com/426388/97702207-e5627a00-1aae-11eb-97d4-ccfe8229ac35.png)

--------

p8oabR-za-p2#comment-4729

**Comment by rcrdortiz** [comment]
The Pay with PayPal Block has been re-designed and now the alignment is correct as we can see here:
<img width="658" alt="Captura de pantalla 2022-01-11 a las 12 18 26" src="https://user-images.githubusercontent.com/1989914/148933442-f8f950dc-5336-4f03-9eb9-ff80d88392ba.png">
The media library link has a slight padding and isn't aligned, that behaviour is a Gutenberg core behavior of the [MediaPlaceholder](https://github.com/WordPress/gutenberg/tree/3e645c4693023fb7dd08e3feb36c82d5968c0c98/packages/block-editor/src/components/media-placeholder) component.
