### ISSUE TITLE
Jump Start: after Jump starting site, Jetpack page goes blank

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1767]
I click Jump Start, and get a success message.  When I click back to go to Jetpack, I get a blank page:

![screen shot 2015-03-13 at 8 41 24 am](https://cloud.githubusercontent.com/assets/3220162/6641730/e2421942-c95c-11e4-98c7-642a5fdc13d1.png)

**Comment by jessefriedman** [comment]
This was solved with this https://github.com/Automattic/jetpack/commit/49558a248d4af6992956123587b2a6d1da5b91ee  I didn't see the ticket before I fixed the problem.
