### ISSUE TITLE
Loom Block: full-width and wide-width ignored inside block editor

### ISSUE THREAD

**Issue by annemirasol** [Automattic/jetpack#17731]
#### Steps to reproduce the issue

1. Open the WordPress.com editor and create a Loom embed block.
2. Change the alignment setting to `Wide width` or `Full width` and note that the block preview does not change its width. 

#### What I expected

I expected the Loom embed block to follow the alignment settings inside the editor, similar to how other embed blocks behave. See https://d.pr/v/VcBvnu, where I compare the Loom block behavior with another type of embed block.

#### What happened instead
The Loom embed block did not adjust its dimensions even when alignment was changed to full-width or wide-width.

**Screenshots**
Screen recording: https://d.pr/v/VcBvnu

**Comment by jeherve** [comment]
cc @retrofox, who worked on this embed.

**Comment by retrofox** [comment]
I don't believe it's a Jetpack issue, but a wpcom one.

**Comment by retrofox** [comment]
let me close in favor of D52485-code (wpcom) and a possible solution in core https://github.com/WordPress/gutenberg/pull/26842
