### ISSUE TITLE
Deregister scripts

### ISSUE THREAD

**Issue by pixedelic** [Automattic/jetpack#1774]
Hi, tried this solution https://gist.github.com/jeherve/df4e349a209d532a7978 both with a theme developed by me, and with TwentyFifteen. No success all... Is there anything with the recent versions of JetPack? In particular subscriptions, slideshow and carousel CSS are always loaded (I'm testing those features at the moment). Does it have anything to do with the fact the subscriptions CSS (for instance) are enqueued along the widget function and slideshow ones are enqueued along the shortcode function instead of using the 'wp_enqueue_scripts' action?

Sorry for the bad english and thank you in advance. Manuel :-)

**Comment by jeherve** [comment]
You're correct. These stylesheets are enqueued differently to make sure they're only enqueued when the widget is present (either added to a sidebar or inserted into a post via the shortcode). You'll probably need to change the priority where the dequeuing function is hooked to make sure it's run late enough.

I hope this helps.

**Comment by pixedelic** [comment]
Any clue...? I mean, I tried with many priority values and different hooks as well... nothing seems enough.  Are you sure there is a way to deregister styles and scripts once are added in that way? Thanks

**Comment by obenland** [comment]
@jeherve Not sure if it warrants a new ticket, but it fits into the broader scheme of JP enqueueing its styles when it shouldn't:
You probably know that if JP is network activated, it enqueues its styles on the front end on every site of that network. The kicker is that it does that even if JP is not connected to wp.com on that site. Example: wordpress.org/themes.

I briefly chatted with @samhotchkiss about it last week and wanted to follow up on that. Should I create a new ticket?

**Comment by pixedelic** [comment]
@jeherve I'm so stupid, I tried 'wp_enqueue_scripts' and 'wp_print_styles' (and many other without any relation, to be honest) and I haven't tried 'wp_print_scripts', that is the only one I should have try.

So, in this way it seems to work:

```php
function remove_jp_scripts() {
  wp_deregister_style( 'jetpack-carousel' ); // Carousel
  wp_deregister_style( 'jetpack-slideshow' ); // Slideshows
  wp_deregister_style( 'jetpack-subscriptions' ); // Subscriptions
  //etc. as for https://gist.github.com/jeherve/df4e349a209d532a7978
}
add_action( 'wp_print_scripts', 'remove_all_jp_css' );
```

Thank you and sorry!

**Comment by jeherve** [comment]
@obenland That seems like a different problem, so a new GitHub issue would probably be better. I guess we should wait until Jetpack is connected to WordPress.com or used in development mode before to enqueue anything on the frontend.

@pixedelic I'm glad you could figure it out!

**Comment by adiacone** [comment]
@pixedelic I've been pulling my hair for the last few hours trying to figure out how to remove the default styling for the <code>[portfolio]</code> shortcode. I'm currently using this:

```php
function _prefix_remove_plugin_styles() {
	wp_deregister_style( 'jetpack-portfolio-style' );
	wp_deregister_style( 'sharedaddy' );
	wp_deregister_style( 'grunion.css' );
}
add_action( 'wp_print_styles', '_prefix_remove_plugin_styles' );
```

Seems to work fine for all modules, except for the Portfolio, even though I tried all sorts of hooks and priorities. Is it because it's loaded in the footer?

Thanks!

**Comment by jeherve** [comment]
@adiacone `wp_deregister_style( 'jetpack-portfolio-style' );` should do the trick ([#](https://github.com/Automattic/jetpack/blob/master/modules/custom-post-types/portfolios.php#L469)). `sharedaddy` and `grunion.css` are used for the sharing buttons and the contact form.

**Comment by adiacone** [comment]
@jeherve Yes, I thought so too, but it doesn't work. I left the other two lines of code to check if <code>wp_deregister_style</code> works for other modules. It works for the Sharing and Contact Form modules (and probably for all other modules), but not for the Portfolio. Seems really weird, the only reason I could think of is some sort of priority issue.

**Comment by jeherve** [comment]
Hm, that's weird.

@michaeldcain Any idea how to dequeue the Portfolio stylesheet that's enqueued inside the shortcode?

**Comment by dashkevych** [comment]
Hi guys,

Any tips on how to dequeue the Portfolio stylesheet?

**Comment by michaeldcain** [comment]
If `jetpack-portfolio-style` hasn't already been enqueued when the shortcode is called, the script gets added to a list of handles to be enqueued with `print_late_styles()`. 

I couldn't seem to get `wp_dequeue_style` to run on a late enough hook, so we can just filter the list of items to be enqueued like so:

```
function _prefix_remove_jetpack_portfolio_styles_from_array( $queue ) {
	$style_key = array_search( 'jetpack-portfolio-style', $queue );
	
	if ( false !== $style_key ) {
		unset( $queue[ $style_key ] );
	}
	
	return $queue;
}
add_filter( 'print_styles_array', '_prefix_remove_jetpack_portfolio_styles_from_array', 2, 1 );
```
