### ISSUE TITLE
Consider whether `RTL_Admin_Bar` is still required in masterbar module

### ISSUE THREAD

**Issue by getdave** [Automattic/jetpack#17773]
@jeherve Is `RTL_Admin_Bar` something that we need at all? It looks like it's currently defunct, the `wp_admin_bar_class` callback gets registered on `admin_bar_init`, which is after `wp_admin_bar_class` runs.
Testing with Hebrew, the master bar seems to render fine without it.

_Originally posted by @obenland in https://github.com/Automattic/jetpack/pull/17762#discussion_r520773799_

**Comment by jeherve** [comment]
That's a good question. You're ahead of me on this one; I can't get the RTL Masterbar to work at all. Even when my WordPress.com account settings are set to Hebrew, `$this->user_data['text_direction']` remains set to `ltr` for me.

**Comment by obenland** [comment]
That seems to be cached for a day in `Jetpack::get_connected_user_data()`, I had to comment out the cached data return to get the updated value

**Comment by jeherve** [comment]
Ah yes, this was it, thank you. It does look the same to me as well, it would seem we don't really need `RTL_Admin_Bar` anymore.
