### ISSUE TITLE
Sharing buttons: Add parler.com sharing button

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/jetpack#17787]
https://parler.com/

Requested in https://twitter.com/davidould/status/1326661847638925312

Noting that this issue seems similar and I assume we will pass on this for now for similar reasons, but opening an issue now in case that changes over time:  https://github.com/Automattic/jetpack/issues/16347

**Comment by jeherve** [comment]
> I assume we will pass on this for now for similar reasons

That is correct. The service does not seem to offer official Sharing buttons yet, so we would not be able to add them to Jetpack right now.

For now and for anyone looking to add Parler sharing buttons to their site, it may be worth trying to set up a custom Jetpack sharing button under Settings > Sharing, and as explained [here](https://ryanmarkel.com/2968/adding-a-custom-sharing-service-to-wordpress-com/). I cannot confirm that this would work as I do not have an account myself, but it would appear that a sharing URL of the following format may work:

`https://parler.com/new-post?message=%post_title%&url=%post_url%`
