### ISSUE TITLE
SSO doesn't work when the WP login URL is changed.

### ISSUE THREAD

**Issue by sergeymitr** [Automattic/jetpack#17782]
Changing the URL for `wp-login.php` is a popular security measure. It's usually done via third-party plugins (e.g. WPS Hide Login).

When somebody tries to authenticate via SSO, they get redirected back to `wp-login.php` instead of the new login URL.
Therefore, the final step of the SSO auth does not work.

#### Steps to reproduce the issue

1. Connect Jetpack, enable the Jetpack SSO module.
2. Install the WPS Hide Login plugin, replace the default login URL with a custom one.
3. Logout from your site.
4. Try to login using the SSO.

#### What I expected
Logged in successfully.

#### What happened instead
I was redirected to the default `wp-login.php` URL, which resulted in 404.

#### Suggested solution
Pass the `wp_login_url()` value from the Jetpack site to WP.com along with other SSO parameters.
Then return back to this correct URL instead of the default `wp-login.php`.
**Important: The solution needs to be properly reviewed before being implemented.**

**Comment by anaemnesis** [comment]
Reported in 110517-z,

**Comment by sergeymitr** [comment]
@anaemnesis apparently I don't have access to that ticket.
Is the customer waiting for this to be fixed? If so, I'll look into it in the next couple of days.

**Comment by anaemnesis** [comment]
@sergeymitr Sorry, just saw this. The ticket above is VIP, but yes, it would be ideal if this could be taken care of (but it's not urgent, urgent).
