### ISSUE TITLE
Shortcodes: add Display Posts shortcode

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1780]
WordPress.com includes a ["Display Posts" shortcode](https://en.support.wordpress.com/display-posts-shortcode/). It'd be nice to add it to Jetpack as well.

**Comment by kraftbj** [comment]
WordPress.com's shortcode is https://wordpress.org/plugins/display-posts-shortcode/ with a helper function to allow caching the output.

**Comment by jeherve** [comment]
Marking this as wontfix, as we've opted not to add the shortcode (#5518). It remains available as a standalone plugin:
https://wordpress.org/plugins/display-posts-shortcode/

**Comment by catehstn** [comment]
@beaulebens - ran into this trying to use it on my Pressable / Jetpack setup - worth revisiting?

**Comment by kraftbj** [comment]
Noting that the plugin we're using on WP.com is publicly available and never by an Automattician. https://wordpress.org/plugins/display-posts-shortcode/

If we did include it, we would need a better process to ensure it is kept up to date, etc. For Atomic sites, I would say we can lean on the helper scripts there to ensure it is present.
