### ISSUE TITLE
Widgets: Instagram widget throwing PHP notices

### ISSUE THREAD

**Issue by emrikol** [Automattic/jetpack#17801]
So I specifically noticed this when using [query monitor](https://querymonitor.com/).  When trying to add an Instagram widget when Query Monitor enabled, there are PHP notices being thrown about undefined indexes.  This is causing the AJAX request to fail and the widget cannot be set up.

#### Steps to reproduce the issue

1. Enable sidebar widgets
2. Install and enable Query Monitor, or alternatively enable output of PHP notices
3. Try to add an Instagram widget

#### What I expected

I expected the widget to work properly.

#### What happened instead

The widget fails with a `Instagram is currently experiencing connectivity issues, please try again later to connect.` error.

I've tested with the patch below, which wraps the offending arrays/indexes with an `isset()`:

```
Index: modules/widgets/class-jetpack-instagram-widget.php
===================================================================
--- modules/widgets/class-jetpack-instagram-widget.php    (revision 1263)
+++ modules/widgets/class-jetpack-instagram-widget.php    (working copy)
@@ -587,11 +587,11 @@
             $instance['token_id'] = $old_instance['token_id'];
         }

-        $instance['title'] = wp_strip_all_tags( $new_instance['title'] );
+        $instance['title'] = isset( $new_instance['title'] ) ? wp_strip_all_tags( $new_instance['title'] ) : $instance['title'];

-        $instance['columns'] = max( 1, min( $this->valid_options['max_columns'], (int) $new_instance['columns'] ) );
+        $instance['columns'] = isset( $new_instance['columns'] ) ? max( 1, min( $this->valid_options['max_columns'], (int) $new_instance['columns'] ) ) : $instance['columns'];

-        $instance['count'] = max( 1, min( $this->valid_options['max_count'], (int) $new_instance['count'] ) );
+        $instance['count'] = isset( $new_instance['count'] ) ? max( 1, min( $this->valid_options['max_count'], (int) $new_instance['count'] ) ) : $instance['count'];

         return $instance;
     }
```

**Comment by andyjdavis** [comment]
Hi. I have been having a look at this. The suggested fix does indeed resolve the PHP errors.

Unfortunately it does not resolve the "Instagram is currently experiencing connectivity issues" problem. For me at least get_connect_url() is returning a wp_error instance. I've run out of time this evening and need to get some sleep but hopefully I will be able to have another look tomorrow.

**Comment by andyjdavis** [comment]
I have put up a pull request with a possible fix for this. See https://github.com/Automattic/jetpack/pull/18900/files

Although the ternarys did the job I switched to if's. That made these checks match the token_id check right above them. I also felt like it made the intent a little clearer.
