### ISSUE TITLE
Jump Start: button spinner is not aligned properly

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1781]
When clicking on the `Jump Start` button, the loading icon used to be inside the button, now it's floating on top:

![screen shot 2015-03-16 at 8 27 01 am](https://cloud.githubusercontent.com/assets/3220162/6669499/79b6eee6-cbb6-11e4-92ca-98dcd45a36a9.png)

**Comment by mikeyarce** [comment]
This is on Chrome 41 (Mac)

**Comment by jeffgolenski** [comment]
Thanks @mikeyarce. This was intentional since the spinner sitting on top of the button isn't that crisp. But now that I let it sit over the weekend, I'll revisit placing the spinner on top of the button and reducing the button opacity even more.
