### ISSUE TITLE
Additional SM integrations

### ISSUE THREAD

**Issue by oaknorton** [Automattic/jetpack#17816]
#### Is your feature request related to a problem? Please describe.
I don’t know if you have noticed, but the recent American election has created new opportunities for alternative platforms to Facebook & Twitter due to their heavy censorship of things they did not want shared. Massive amounts of people are flocking to alternative platforms, including myself. I would very much like my website to be able to publish directly to my pages or groups on other platforms. The biggest ones right now are Mewe.com, Parler.com, and Gab.com, which I am looking to use. Will you please work on an integration for these platforms so I can publish there as well? I believe another app (Blog2Social) is working on other integrations and I think you should as well.

**Comment by jeherve** [comment]
This has come in the past:
- #16347 
- #11393 

If some of those Social Networks grow to be more popular all around the world, we'll consider adding them as a new option to our Publicize feature. 

For that to happen, however, those services will need to offer a public and documented API that we could rely on. As far as I can tell, none of those services offer an API yet, so integrations are not yet possible.

I'll close this issue for now; we can reopen it in the future if the situation changes.
