### ISSUE TITLE
Uncaught TypeError: r is not a function

### ISSUE THREAD

**Issue by mrleemon** [Automattic/jetpack#17824]
I built a plugin that registers a Gutenberg block that prints a simple Mailchimp form. The plugin works with no issues. But, if I activate Jetpack and try to edit any page or post, I get a blank screen and multiple `Uncaught TypeError: r is not a function` console errors such as this one with little variations:

```
editor.js?ver=9.1:6 Uncaught TypeError: r is not a function (https://domain.com/wp-content/plugins/jetpack/_inc/blocks/editor.js?ver=9.1)
    at editor.js?ver=9.1:6
    at Array.forEach (<anonymous>)
    at e.exports (editor.js?ver=9.1:6)
    at f (editor.js?ver=9.1:6)
    at Module.<anonymous> (editor.js?ver=9.1:18)
    at o (editor.js?ver=9.1:1)
    at Object.<anonymous> (editor.js?ver=9.1:18)
    at o (editor.js?ver=9.1:1)
    at editor.js?ver=9.1:1
    at editor.js?ver=9.1:1]
```

The `index.js` file in My Mailchimp block plugin imports two SCSS files so the build process is able to create the corresponding CSS files:

```
import './editor.scss';
import './style.scss';
```

I found that if I comment out the `import './editor.scss'` line, Jetpack stops throwing the console errors. So, it seems there’s something in my plugin that is conflicting with Jetpack.

Can someone help me, please? I’m completely lost.

I’m running WP 5.5.3 and Jetpack 9.1 and I have the `SCRIPT_DEBUG` constant set to true.

This is the `index.js` file full code:

```
const { __ } = wp.i18n;
const { Fragment } = wp.element;
const { Disabled, PanelBody, TextControl, ToggleControl } = wp.components;
const { InspectorControls } = wp.blockEditor;
const { registerBlockType } = wp.blocks;
const ServerSideRender = wp.serverSideRender;

import './editor.scss';
import './style.scss';

export const name = 'my/mailchimp';

export const settings = {
    title: __( 'Mailchimp', 'my-mailchimp' ),
    description: __( 'A Mailchimp form.', 'my-mailchimp' ),
    icon: 'email',
    category: 'embed',
    keywords: [ __( 'email' ), __( 'newsletter' ) ],
    attributes: {
        url: {
            type: 'string',
            default: '',
        },
        u: {
            type: 'string',
            default: '',
        },
        id: {
            type: 'string',
            default: '',
        },
        firstName: {
            type: 'boolean',
            default: false,
        },
        lastName: {
            type: 'boolean',
            default: false,
        },
    },

    edit: props => {
        const attributes = props.attributes;

        const setID = value => {
            props.setAttributes( { id: value } );
        };

        const setURL = value => {
            props.setAttributes( { url: value } );
        };

        const setU = value => {
            props.setAttributes( { u: value } );
        };

        const toggleFirstName = () => {
            props.setAttributes( { firstName: ! props.attributes.firstName } );
        };

        const toggleLastName = () => {
            props.setAttributes( { lastName: ! props.attributes.lastName } );
        };

        return (
            <Fragment>
                <InspectorControls>
                    <PanelBody title={ __( 'Mailchimp Settings', 'my-mailchimp' ) }>
                        <TextControl
                            label={ __( 'URL', 'my-mailchimp' ) }
                            type='url'
                            value={ attributes.url }
                            onChange={ setURL }
                        />
                        <TextControl
                            label={ __( 'U', 'my-mailchimp' ) }
                            type='text'
                            value={ attributes.u }
                            onChange={ setU }
                        />
                        <TextControl
                            label={ __( 'ID', 'my-mailchimp' ) }
                            type='text'
                            value={ attributes.id }
                            onChange={ setID }
                        />
                        { attributes.url && attributes.u && attributes.id && (
                            <ToggleControl
                                label={ __( 'Show First Name', 'my-mailchimp' ) }
                                checked={ !! attributes.firstName }
                                onChange={ toggleFirstName }
                            />
                        )}
                        { attributes.url && attributes.u && attributes.id && (
                            <ToggleControl
                                label={ __( 'Show Last Name', 'my-mailchimp' ) }
                                checked={ !! attributes.lastName }
                                onChange={ toggleLastName }
                            />
                        )}
                    </PanelBody>
                </InspectorControls>
                <Disabled>
                    <ServerSideRender
                        block='my/mailchimp'
                        attributes={ attributes }
                        className={ props.className }
                    />
                </Disabled>
            </Fragment>
        );
    },

    save: () => {
        return null
    }

};

registerBlockType( name, settings );
```

Thanks

**Comment by jeherve** [comment]
Is your plugin available somewhere so we could give it a try?

Could you also tell us more about what you use to build the block and process the scss? Do you rely on something like `@wordpress/scripts` and `node-sass`?

**Comment by mrleemon** [comment]
You can download the plugin from [here](https://github.com/mrleemon/rather-simple-mailchimp).
To build the plugin, I use the main build script from`@wordpress/scripts`, which processes SCSS files automatically if they are referenced in any JS file. Both `editor.scss` and `style.scss` are compiled and JS files are generated correctly with no errors.
The console errors appear either with the latest Gutenberg plugin active or not.

**Comment by jeherve** [comment]
I can't seem to be able to reproduce on my end:

![image](https://user-images.githubusercontent.com/426388/99569910-8323d780-29d1-11eb-95ba-80c8465533a4.png)

(I uncommented the `editor.scss` import and rebuilt your block, things still appeared to work).

Do you still experience the issue when you install [Jetpack's Beta plugin](https://jetpack.com/download-jetpack-beta/), go to Jetpack > Beta and set the "Bleeding edge" option?

**Comment by mrleemon** [comment]
I installed the bleeding edge version of Jetpack with the same results. This is really weird.

**Comment by mrleemon** [comment]
I tried my plugin in a local environment with just Jetpack active and I get the console errors.

**Comment by mrleemon** [comment]
Can you send me your built `build/index.js` file so I can compare it with mine, please?

**Comment by jeherve** [comment]
Sure thing: https://gist.github.com/jeherve/8ca6b7c87f9458f045254375af7e7fae

**Comment by mrleemon** [comment]
I'm dumbfounded. Your file is exactly like mine. I don't know why it works for you and not for me. I'm using a vanilla WP install with just Jetpack active and one of the Twenty themes.

**Comment by jeherve** [comment]
Same, I was also using a fresh WP install.

I tested in Chrome; do you use a different browser, maybe?

**Comment by mrleemon** [comment]
I get the same results in Chrome and Firefox.
Do you get any console errors in your end?

**Comment by mrleemon** [comment]
I get the same results in Chrome and Firefox.
Do you get any console errors/warnings in your end?

**Comment by jeherve** [comment]
No, no console errors on my end, the block just renders as on the screenshot above.

**Comment by mrleemon** [comment]
Ok, you can close this issue if you want, then. There might be something on my end that's causing this. I need to investigate further.

**Comment by quemuel** [comment]
Pode ser a versão do navegador, eu tive esse problema, no meu pc chrome Versão 101.0.4951.67 (Versão oficial) 64 bits funciona quando uso o tablete versão 81.0.40.44.138 não funciona e dá esse erro "TypeError: r.at is not a function". quando uso "array.at(-1)"
