### ISSUE TITLE
Jump Start: Prompt comes back after connection cycle

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1782]
If you Jump Start a site, and then do a disconnect and reconnect, the Jump Start prompt comes back.

Steps to reproduce
1. Install Jetpack 3.4 beta 2
2. Connect Jetpack
3. Jump Start site
4. Disconnect Jetpack
5. Connect Jetpack
6. Jump Start will show again

**Comment by samhotchkiss** [comment]
@jessefriedman ^

I don't think this needs to be addressed for 3.4, we can handle in 3.4.1

**Comment by richardmtl** [comment]
Also worth noting is that when I clicked the link to expand what would be activated, it showed me this:

![image](https://cloud.githubusercontent.com/assets/3676359/6919802/1be64392-d788-11e4-9a3d-2ab21072129e.png)

All the relevant modules were already activated. Running 3.4.1
