### ISSUE TITLE
Block build: truncated scripts?

### ISSUE THREAD

**Issue by mrleemon** [Automattic/jetpack#17837]
The generated `editor.js` file found in the `\_inc\blocks\` folder bundles some external scripts such as `classnames` or `number_format`. Examining it, it seems that the end of those scripts is truncated.

Some examples:

- `function(e,t,n){var r;`
- `return(l=(o?` (line 6)
- `function(e,t,n){` (line 14)

Is this normal?

**Comment by jeherve** [comment]
> Is this normal?

That's a good question, we'll look into that. It only seems to happen in the minified/production version, but I don't know that it causes any trouble right now, somehow.

**Comment by mrleemon** [comment]
#17824 might be connected to this

**Comment by sirreal** [comment]
I don't think there's anything wrong here. Minified files are particularly difficult to understand, but if you run them through a code formatter you can start to make sense of things. I've done that to compare builds and don't see anything suspicious. These are line breaks triggered by comments that are not stripped by the build. They happen to come in positions that look confusing or broken, but can be parsed just fine by the browser. The code is not actually truncated.

| prod | dev |
| --- | --- |
| <img width="568" alt="prod" src="https://user-images.githubusercontent.com/841763/99588151-6ea00900-29ea-11eb-988a-acf8bf0c2c39.png"> | <img width="814" alt="dev" src="https://user-images.githubusercontent.com/841763/99588174-76f84400-29ea-11eb-985f-cefc9463cc3c.png"> |



You can see these files are different, but structurally they're the same. I don't see any issue with the `editor.js` file and if it were truly invalid in some way there would be numerous reports of major issues in the block editor.

**Comment by ockham** [comment]
Aside, we'll have some extra safety once we introduce ES5 validation to [`build-production-extensions`](https://github.com/Automattic/jetpack/blob/9c683afdf1bbf80165c8e8979d620b023f81c4d5/package.json#L27), see #17127. Unfortunately, that's currently blocked by https://github.com/Automattic/jetpack/pull/16845#issuecomment-704923725, so it'll be a bit longer until we'll have that.

**Comment by mrleemon** [comment]
Ok, thanks for your answer.
