### ISSUE TITLE
Jetpack blocks not being loaded/found on Gutenberg 9.4 on WPCOM/AT when using Firefox

### ISSUE THREAD

**Issue by fullofcaffeine** [Automattic/jetpack#17850]
#### Steps to reproduce the issue

**IMPORTANT:** The issue only happens on Firefox.

##### WPCOM

1. Create a new WPCOM test site;
2. Add the `gutenberg-edge` sticker to it in order for it to load GB `9.4.1`;
3. Start a new post and try to search for/nsert a JP block (Tiled Gallery and Contact Info come to mind). 

##### AT

1. Create a new WPCOM test site;
1. Upgrade to the business plan and install a plugin in order for it to become AT;
1. SFTP into it _(Get the SFTP info @ `https://wordpress.com/hosting-config/<site>`)_ and remove the `gutenberg` symlink in `/htdocs/wp-content/plugins`
1. Download Gutenberg `9.4.1` from [here](https://wordpress.org/plugins/gutenberg/) and upload it to your AT site;
3. Start a new post and try to search for/insert a JP block _(`Tiled Gallery` and `Contact Info` come to mind)_. 

It also happens on an org instance with GB 9.4 (I used `jurassic.ninja` to test) as long as FF is being used to access it.

#### What I expected

I expect all JP blocks to load (and function) correctly so I can find them in the inserter and am able to add them to the editor.

#### What happened instead

You can't find them in the inserter _(which I guess is related to the error shown in the screenshot below)_. That also means any post that uses one of these blocks will render a "block not supported" error.

**Screenshots**

|  Trying to find the "Contact Info" block | Console errors (same error on WPCOM/AT) |
| ------------- | ------------- |
| ![jp2](https://user-images.githubusercontent.com/81248/99862417-4d145e00-2b5f-11eb-8151-5a55a7cc7d92.png) | ![jetpack_](https://user-images.githubusercontent.com/81248/99862759-90230100-2b60-11eb-9129-7b5fe849d785.png) |

#### Env

- `Firefox Quantum Developer Edition, 84.0b3`
- `Ubuntu Linux 18.04`

#### Context

Originally reported here: p1605902335056900-slack-CBG1CP4EN.

**Comment by fullofcaffeine** [comment]
UPDATE: I was wondering why our GB Calypso upgrade tests were passing for me (locally) if they also test some JP blocks (Tiled Gallery and Contact Info). I just logged into the account we use to hold the sites and started a new post on one of the edge sites and JP blocks seem to be working fine there with JP 9.4. 

I decided to use Chrome for this test since FF is proxied by default for me. It then clicked -- the browsers are different. I unproxied FF and tested the same site again and it once again crashed. This seems to be an issue that is specific to/only manifests itself on FF for some reason.

**Comment by katiebethbrown** [comment]
User report in 25784527-hc

**Comment by ockham** [comment]
> It also happens on an org instance with GB 9.4 (I used jurassic.ninja to test) as long as FF is used to access it.

I can also repro this.
Judging from the console, it seems like there's an issue with the `@wordpress/date` package, and how it's used from a JP block. I'll continue to debug.

Aside, maybe we can add e2e coverage for FF to our JP e2e tests to catch issues like this :thinking:

**Comment by ockham** [comment]
History for `@wordpress/date`: https://github.com/WordPress/gutenberg/commits/master/packages/date

Not a lot of changes lately. Potential candidate: https://github.com/WordPress/gutenberg/pull/25782

**Comment by ockham** [comment]
Running JP locally seems to point at this `dateI18n` call as the potential problem: https://github.com/Automattic/jetpack/blob/425907b6c0eb253135cd21062ca993d1ed3db033/extensions/shared/external-media/constants.js#L179

**Comment by ockham** [comment]
@jeherve @anomiex I've added this to the 9.2 milestone since it's kinda critical. @fullofcaffeine has tracked down the issue and is filing a PR as we speak which we hope to include in the release.
