### ISSUE TITLE
General: Jetpack logo squished in IE 9 & 10

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1785]
The Jetpack logo in the wp-admin pages looks squished in IE9 and 10:
![screen shot 2015-03-16 at 9 21 18 am](https://cloud.githubusercontent.com/assets/3220162/6670783/e9be38e6-cbbd-11e4-900a-edd9ebd866d1.png)

Looks fine in IE11:
![screen shot 2015-03-16 at 9 24 17 am](https://cloud.githubusercontent.com/assets/3220162/6670836/4531e6d2-cbbe-11e4-8ded-c3d567f31852.png)

**Comment by jeffgolenski** [comment]
oh wow, I wonder how long this has been like this for. I'll look into it!

**Comment by jeffgolenski** [comment]
I believe I just repaired this with: https://github.com/Automattic/jetpack/commit/ebfdf429a3d5d15cf503990bedf27929ef10071d @mikeyarce can you verify? I tested in ie 9 + 10 on windows 7 (within browser stack).

Please be sure to clear your cache and test master again!

**Comment by mikeyarce** [comment]
Odd - I'm still seeing the issue after updating Master and clearing the caches.

**Comment by jeffgolenski** [comment]
I'll check it out again either en route to London or once I get there

**Comment by jeffgolenski** [comment]
@mikeyarce in the meantime, here's a screenshot of what I've got right now. But again, see above message. I'm sure there's something getting in the way. 
![screen shot 2015-03-17 at 4 52 08 pm](https://cloud.githubusercontent.com/assets/214813/6697438/e414de04-ccc6-11e4-8086-779c690b6e7b.png)

**Comment by mikeyarce** [comment]
I spun up a new site to test the changes, looks good now.  Probably a Windows problem with my old site.  I'm going to blame mr. Paperclip.
