### ISSUE TITLE
Do not enqueue styles until connected

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#1786]
From #1774: 
If JP is network activated, it enqueues its styles on the front end on every site of that network. The kicker is that it does that even if JP is not connected to wp.com on that site. Example: wordpress.org/themes.

I briefly chatted with @samhotchkiss about it last week and wanted to follow up on that.

**Comment by georgestephanis** [comment]
You mean the concatenated stylesheet?

Any extra conditional would probably go in here: https://github.com/Automattic/jetpack/blob/master/class.jetpack.php#L5456-L5524

I'd like to see this in a 3.4.1 point release.

@obenland Do you see anything that looks like `"<!-- " . esc_html( $handle ) . " is included in the concatenated jetpack.css -->\r\n"` in the source if you run it with WP_DEBUG on?

**Comment by obenland** [comment]
> Do you see anything that looks like "\r\n" in the source if you run it with WP_DEBUG on?

I don't. Yes, it looks like it just needs another check there. With `SCRIPT_DEBUG` on it doesn't enqueue it, as expected.

**Comment by samhotchkiss** [comment]
Tagged for 3.4.1

**Comment by samhotchkiss** [comment]
Fixed by #1915
