### ISSUE TITLE
Podcast player: refactoring -> consider exposing components 

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#17861]
The [podcast-player block](https://github.com/Automattic/jetpack/tree/master/extensions/blocks/podcast-player) has some components that can be usable by other components/blocks. We'd like to move some of these components to the [./shared location](https://github.com/Automattic/jetpack/tree/master/extensions/shared).

### Components

- [ ] [Audio player](https://github.com/Automattic/jetpack/blob/master/extensions/blocks/podcast-player/components/audio-player.js)

**Comment by creativecoder** [comment]
Handled by https://href.li/?https://github.com/Automattic/jetpack/pull/17879
