### ISSUE TITLE
Contact Form only submits to WordPress.com account email if added via classic block

### ISSUE THREAD

**Issue by noteeth** [Automattic/jetpack#17872]
#### Steps to reproduce the issue

1. Add classic block to a page on a WordPress.com site.
2. Add the contact form within classic block
3. In form settings, under What would you like the subject of the email to be? add an email address that is not the WordPress.com account related email address.
<img width="1519" alt="Screen Shot 2020-11-23 at 11 38 15 AM" src="https://user-images.githubusercontent.com/16570939/100007240-a7403980-2d80-11eb-99bf-dfe2f5d2055d.png">

4. Email is sent to account related email address

#### What I expected
I expected the form to submit to the chosen email address, added to the form settings.  

#### What happened instead
The form only submits to account related email.

I understand that when working via blocks, it would be best to add the contact form as a separate block.  Adding this issue only because there are some WordPress.com users who only work within the classic block and do not feel comfortable with additional blocks, so they are adding the form via classic block.

**Comment by jeherve** [comment]
This should be fixed as of #17697.
