### ISSUE TITLE
Fatal Error when using the Beta plugin

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#17897]
I'm running into issues on a single site since we merged #17833 

```
PHP Notice:  Constant JETPACK__MINIMUM_WP_VERSION already defined in /wp-content/plugins/jetpack/jetpack.php on line 17
PHP Notice:  Constant JETPACK__MINIMUM_PHP_VERSION already defined in /wp-content/plugins/jetpack/jetpack.php on line 18
PHP Notice:  Constant JETPACK__VERSION already defined in /wp-content/plugins/jetpack/jetpack.php on line 19
PHP Notice:  Constant JETPACK_MASTER_USER already defined in /wp-content/plugins/jetpack/jetpack.php on line 27
PHP Notice:  Constant JETPACK__API_VERSION already defined in /wp-content/plugins/jetpack/jetpack.php on line 29
PHP Notice:  Constant JETPACK__PLUGIN_DIR already defined in /wp-content/plugins/jetpack/jetpack.php on line 30
PHP Notice:  Constant JETPACK__PLUGIN_FILE already defined in /wp-content/plugins/jetpack/jetpack.php on line 31
PHP Fatal error:  Uncaught Error: Call to undefined method Automattic\Jetpack\Status::get_site_suffix() in /wp-content/plugins/jetpack-dev/modules/publicize/publicize.php:1267
Stack trace:
#0 /wp-content/plugins/jetpack-dev/modules/publicize/ui.php(30): publicize_calypso_url()
#1 /wp-includes/class-wp-hook.php(287): Publicize_UI->init()
#2 /wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#3 /wp-includes/plugin.php(478): WP_Hook->do_action()
#4 /wp-settings.php(546): do_action()
#5 /wp-config.php(160): require_once('/home/...')
#6 /wp-load.php(37): require_once('/home/...')
#7 /wp-blog-header.php(13): require_once('/home/...')
#8 /index.php(17): require('/home/...')
#9 {main}
  thrown in /wp-content/plugins/jetpack-dev/modules/publicize/publicize.php on line 1267
```

The site is a Multisite network, where both Jetpack and the Jetpack beta plugin are network-activated. VaultPress is active on the main site of the network.

I'm not quite sure why I run into it, and not on any other test site, but it may be worth looking into.

**Comment by kraftbj** [comment]
Just noting the file structure— `/wp-content/plugins/jetpack/`... which is the stable build while we usually are installed in `jetpack-dev` via the beta plugin.

Is this a case where the two plugins are both active somehow?

**Comment by jeherve** [comment]
Right, that's why I included those notices; that seems odd. It may have something to do that and the fact that the plugins are network-activated. 

I'll try replacing `jetpack` by the Beta version of Jetpack, without the Beta plugin, and see what happens.

**Comment by jeherve** [comment]
That did the trick. That must be a fluke with my setup. Closing this now.

**Comment by mzakariya** [comment]
(Nearly) identical user report in #3536623-zen. Extremely unlikely the user has ever installed the Jetpack Beta build. 

However, the error indicates they're on Jetpack **9.1**, so this might have been a failed auto-update. Just noting here for now, will only re-open this if we rule out an update issue.

**Comment by dereksmart** [comment]
FWIW I had the same thing happen to me today, and debugged it down to a conflict with the Boost plugin. Updating the composer packages _within boost_ resolved it. May be something to 👀  around autoloader and version compatibility.

**Comment by kraftbj** [comment]
Boost is running dev versions, so they would likely be higher than the beta version, FWIW.

**Comment by jeherve** [comment]
It does indeed seem related to the Autoloader. So far it's only happened on sites that run one or more of the above:

- Boost using dev versions
- VaultPress
- WooCommerce

In 3536623-zen, the problem now appears to be fixed.

@kbrown9 Any idea what may be happening here?

**Comment by kbrown9** [comment]
My comments are the different site environments are below:

* 3536623-zen: That looks like an update failure. A fresh copy of Jetpack was installed, and the error is no longer generated. I haven't seen any other reports of this error on production sites.

* **Multisite with the Jetpack Beta plugin** - It does look like two versions of Jetpack were somehow active on that site. The autoloader will load stable package versions by default. So, if the site somehow had Jetpack 9.1 and a development version of Jetpack installed, the autoloader would load the stable package versions from Jetpack 9.1. Jetpack 9.1 did not have the `Automattic\Jetpack\Status::get_site_suffix()` method, so the fatal error occurs when the development version of Jetpack tries to call that method.

  @jeherve - if you know how to recreate that situation, I can look into it further. 

* **Boost using dev versions** - The autoloader prefers to select stable versions of packages by default. This behavior can be changed by setting the `JETPACK_AUTOLOAD_DEV` constant to true, which makes the autoloader select the first dev version it finds.

   @dsmart - I would need to see the plugins that were installed on your test site to determine exactly what happened. Do you remember which version of Jetpack you had installed on your site (was it a stable version or a development branch)? Also, did you have the `JETPACK_AUTOLOAD_DEV` constant set to true? 

- **VaultPress/WooCommerce** - Have there been reports of errors on production sites with these plugins installed?

**Comment by dereksmart** [comment]
> I would need to see the plugins that were installed on your test site

It was in my dev setup, so both Jetpack and Boost were running master/trunk respectively (both dev-master versions of packages). I was not setting JETPACK_AUTOLOAD_DEV. You might be able to reproduce it by finding an old commit hash of the jetpack-status that doesn't include the new method, and declaring that in boost composer.json like `dev-master#SHANUMBER`, and re-building?

**Comment by jeherve** [comment]
> It does look like two versions of Jetpack were somehow active on that site. The autoloader will load stable package versions by default. So, if the site somehow had Jetpack 9.1 and a development version of Jetpack installed, the autoloader would load the stable package versions from Jetpack 9.1.

That must have been it indeed. Since both the Jetpack plugin and the Jetpack Beta plugin were network-activated, both the stable version of Jetpack and the Bleeding edge version provided by the Beta plugin must have been active at the same time.
