### ISSUE TITLE
Enhancement: more prominent wpcom disconnect button in wp-admin

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#1789]
https://cloudup.com/cQ_DPgqE1eB

Just need a slightly more prominent style on the disconnect link. slightly.

**Comment by georgestephanis** [comment]
Why?

**Comment by jeffgolenski** [comment]
Per a internal slack / p2 discussion regarding Jetpack's UI with @mikeyarce @kraftbj , and @richardmtl around Feb. 17th:

"Users have a hard time finding the “Disconnect” button, and it should be a little more prominent so JP support doesn’t have to show them where it is every time, when troubleshooting. We don’t want to something obnoxious, but something a little more noticeable would help."

Feel free to jump in and comment everyone. I was thinking something similar in appearance to: 

https://cloudup.com/cHjGEFgsn88

**Comment by jessefriedman** [comment]
I would suggest better documenting how to disconnect on jetpack.me. If we do it right a simple google search for "Disconnect Jetpack" will answer the users problem pretty quickly.

**Comment by samhotchkiss** [comment]
My vote is for "leave it as is" + "better documentation"

**Comment by jeffgolenski** [comment]
In https://github.com/Automattic/jetpack/tree/enhancement/connection-status the disconnect button in the footer, is becoming a "my connection" link in the header. This issue will be irrelevant once that branch is merged. Closing now.
