### ISSUE TITLE
Donation Block causes display issues with Cover Blocks

### ISSUE THREAD

**Issue by ktyfuller604** [Automattic/jetpack#17898]
#### Steps to reproduce the issue

1. Create a new page
2. Add a cover block set to full width, then a donation block, then another cover block set to full width
3. Preview the page or publish it
4. Note that the full-width cover block below the donation block is the same width as the donation block; removing the donation block makes the cover block go to the correct width

#### What I expected

I expected the cover block below the donation block to be full width as I set it. 

#### What happened instead

The full-width cover block below the donation block was the same width as the donation block. 

**Screenshots**
![image](https://user-images.githubusercontent.com/38542929/100232313-36229280-2ef6-11eb-9902-9cab217dc4ce.png)

Ref: 3517469-zen

**Comment by sarahfg** [comment]
This came up in chat for me and I can see why it causes an issue. For some reason blocks added after this block get put inside it. I think it's missing a `</div>` . When I use an HTML block to add that missing code in things seem to work.

![](https://d.pr/i/EjpIGU+)
(Image link: https://d.pr/i/EjpIGU )
