### ISSUE TITLE
Donations Block within a Layout Grid causes contents to collapse into one column

### ISSUE THREAD

**Issue by adelineyaw** [Automattic/jetpack#17894]
Adding a Donations Block within a Layout Grid, (assuming there are multiple columns), causes all contents within the Layout Grid to collapse into the first column.

**To reproduce**
1. Edit any post/page
2. Click on + Layout Grid, then select 'two column'
3. Add a Donations Block in the first column
4. Within the second column, add any block
5. Preview post/page, and you will see the error, ie. all contents collapsed in one column.

**Expected behavior**
We should expect to see the same results within the Editor, appear when previewed on the front-end.

**Screenshots**
1). List view of Layout Grid used: ​https://d.pr/i/An0lhO
2). Editor view: https://d.pr/i/QPO3Dc
3). Video (of front-end preview): ​https://d.pr/v/5Mwdiq

**Comment by kylemcph** [comment]
I'm closing ticket 3515609-zen. We can open a new follow-up ticket when there's an update.

**Comment by joweber123** [comment]
Another report 3961282-zen

**Comment by ahmadbaig1** [comment]
Another report 4278930-zen
Also, it's just not the Layout Grid block, it even collapses the Columns block into one column!

**Comment by KirkwallDay** [comment]
Some more info. If you have a block or blocks below the column or layout grid blocks, they will get 'pulled' into the column and layout grids as additional columns!

Editor view: 
<img width="1233" alt="Editor View" src="https://user-images.githubusercontent.com/49131029/133294674-ab9d8212-6cc9-45ae-9569-3b21ab7668c0.png">

Preview View:
<img width="709" alt="Preview View" src="https://user-images.githubusercontent.com/49131029/133294706-67998ad7-fd9d-4878-94b1-9d4030551c5c.png">
