### ISSUE TITLE
Intermittent endless spinner on stats page

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#1790]
Reported by Mika and @csonnek -- not reproducible, but we should investigate and make sure that there isn't something obviously amiss that could cause an intermittent failure

**Comment by csonnek** [comment]
This is the error I'm seeing in the console: 

<img src="http://d.pr/i/543e+">

Updated to the latest beta using the testing plugin (v. 1426451422) and still see the error.

**Comment by samhotchkiss** [comment]
@georgestephanis -- who would be the right person to help look at this?
