### ISSUE TITLE
Connection Package: Removing warnings related to HTTP_RAW_POST_DATA

### ISSUE THREAD

**Issue by coder-karen** [Automattic/jetpack#17917]
The `HTTP_RAW_POST_DATA` global is still used in some places, and with debugging enabled people may see PHP warnings similar to this:

`PHP Notice: Undefined index: HTTP_RAW_POST_DATA in
/wp-content/plugins/jetpack/vendor/automattic/jetpack-connection/src/class-manager.php`

These error messages point to [this particular line](https://github.com/Automattic/jetpack/blob/144bdf0c12aded6979e0b607e59f024d38cdb391/packages%2Fconnection%2Fsrc%2Fclass-manager.php#L2374) in class-manager.php.

This is related to #16488

If possible, could those warnings be avoided?

**Comment by archon810** [comment]
Seeing the notice in our logs too. Please fix it soon.

```
ErrorException: Notice: Undefined index: HTTP_RAW_POST_DATA
#10 /wp-content/plugins/jetpack/vendor/automattic/jetpack-connection/src/class-manager.php(2363): Automattic\Jetpack\Connection\Manager::xmlrpc_methods
```
