### ISSUE TITLE
Subscriptions: Clicking on Subscribe button without having entered an email address reloads the page

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#1793]
If you have the Subscription widget and click the Subscribe button without having added an email address to the field, it simply reloads the page. Ideally, it'd avoid the page reload and display a message notifying the user that they should add an email address.

**Comment by georgestephanis** [comment]
We could probably get this in to a point release by adding some js that just fails the submit and focuses the box.

Alternately use html5 required attributes.  Or both.
