### ISSUE TITLE
CDN: Jetpack’s CDN is not working with SG Optimizer Lazy Loading feature by Siteground

### ISSUE THREAD

**Issue by solosik** [Automattic/jetpack#17931]
Jetpack and SG Optimize plugin by Siteground are not really compatible.

For those of you guys, who are using Jetpack’s CDN and SG Optimizer as me, please note that they're not really compatible.

So when the SG Optimizer Lazy Loading feature is enabled - Jetpack’s CDN stops working for the images inside the post. However, it’s still working for featured images, but not for all other images inside the post, for example.

I’m writing here because I tried to resolve the issue with the SG support team, so I spent a lot of my time, but it seems that they don’t want to fix it.

I also would like to kindly ask Jetpack's team to add this issue on their plugins compatibility page because they also didn’t show it there. It tells that there're no issues with SG Optimizer.

#### Steps to reproduce the issue

1. Any default WP theme
2. Installed SG Optimizer and Jetpack plugins
3. Jetpack’s CDN (accelerator) enabled
4. Jetpack’s Lazy Load - OFF
5. SG Optimizer Lazy Load - ON
6. Create a post and add two images: Featured Image and another one image please insert inside the post, then publish the post

#### What I expected

All images should have in HTML inside SRC parameter of the image the URL from Jetpack’s CDN

#### What happened instead

1. Featured Image SRC URL - from Jetpack’s CDN, that's OK
2. Second Image SRC URL inserted inside the post - from the local storage instead of the Jetpack's CDN

**Other**

SG support reproduced the issue on the clean install without additional plugins and with the default theme.

However, it seems that they're not going to fix it.

I hope that this information will help someone like me who’s using these plugins and for who it might be important.

**Comment by jeherve** [comment]
I don't have a SiteGround-hosted site so cannot reproduce the issue at the moment I'm afraid (the SG Optimizer is designed to work on SiteGround sites only).

I looked at the plugin's code and couldn't immediately find anything that would create a conflict, but I must be missing something.

Do you think you could give us more details about the images that do not get served by Jetpack's Image CDN? Are those inserted via an image block  in the block editor, or via the classic editor? Could you copy the HTML code for one of those images as it appears in the editor, and as it appears when viewing your post's source code, and then paste the results here?

Thank you!

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
