### ISSUE TITLE
Stats overflowing and underflowing on desktop and mobile

### ISSUE THREAD

**Issue by Clorith** [Automattic/jetpack#1796]
These all occur on the individual stats page.

The Search Engine Terms can overflow as they please, this happens on all devices, see desktop screenshot below
![desktop-view](https://cloud.githubusercontent.com/assets/468735/6683234/bc406f1c-cc83-11e4-97e3-24475f95c9b7.PNG)

The same overflow makes some awkward sidescrolling on mobile, but mobile also cuts off everything else on the stats page unfortunately (in portrait mode, landscape mode behaves much like on a desktop thanks to the slight increase in viewport sizing).
![mobile-view-top](https://cloud.githubusercontent.com/assets/468735/6683241/e7bcc7b2-cc83-11e4-8c4a-58d276ac75b2.png)
![mobile-view-bottom](https://cloud.githubusercontent.com/assets/468735/6683242/e7bdbff0-cc83-11e4-9ce3-5b473912e057.png)

**Comment by dereksmart** [comment]
@jeffgolenski could you take a look?

**Comment by deviodigital** [comment]
I've been noticing this same issue on mobile recently so I started looking around.

The CSS that's controlling the width of the "Search Engine Terms" and "Clicks" sections is [this file](https://s1.wp.com/wp-content/admin-plugins/blog-stats/blog-stats.css?20121217)

I already wrote the CSS that would fix this issue on mobile, but have no idea where that file is.

**Comment by jeherve** [comment]
@deviodigital Since the code is hosted on WordPress.com, there is no easy way for you to propose a patch. Don't hesitate to post the diff here though, or send it to us [via email](https://jetpack.com/contact-support/). 

Thanks!

**Comment by deviodigital** [comment]
Here's the CSS that help the overlapping in mobile. Let me know if you need it submitted in another way.

https://gist.github.com/deviodigital/825a6d3e3ff637b8777d733d048f1d4e

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/all-time-views-and-comments-overprint-each-other/

**Comment by jeffgolenski** [comment]
@jeherve We're going to be working on the stats display within the jetpack dashboard, in the near future, eliminating a lot of old code (hopefully). When we do that, we'll be cleaning this up!

**Comment by mzakariya** [comment]
Reported in #2117681-zen and easily replicated on my own site:

![](https://cld.wthms.co/lRhGK9+)
Image Link: https://cld.wthms.co/lRhGK9

Moving the blocks around on the page can either fix it, or make it 10x worse, depending on some combination of luck/where you drag them to.

Recommended user try Calypso or the mobile app.

**Comment by edent** [comment]
This is still an issue. On desktop, search engine terms overflow horribly.
![Screenshot_2020-04-29 Site Stats ‹ Terence Eden’s Blog — WordPress](https://user-images.githubusercontent.com/837136/80591914-6f555b80-8a16-11ea-8370-575dbdf31bb4.png)

It's a two line CSS fix. 
``
overflow: hidden;
text-overflow: ellipsis;
``
![Screenshot_2020-04-29 Site Stats ‹ Terence Eden’s Blog — WordPress(1)](https://user-images.githubusercontent.com/837136/80591918-70868880-8a16-11ea-9bcf-84fe9e6745c5.png)
Which is exactly how the "Clicks" column is formatted.

**Comment by edent** [comment]
If I submit that CSS as a patch, is it likely to be accepted?

**Comment by jeherve** [comment]
> If I submit that CSS as a patch, is it likely to be accepted?

We'll be happy to review it! We'll see if it make sense to merge it as is, or make a few tweaks before we merge it.

**Comment by edent** [comment]
Can you please tell me where the "blog-stats.css" is kept? It is literally a one line change to fix this - but I can't find the CSS in this repo.

It is served from https://s2.wp.com/wp-content/admin-plugins/blog-stats/blog-stats.css

**Comment by jeherve** [comment]
That file doesn't live in this GitHub repository; it is versioned in a private repository of ours.

Could you post your patch here? I can then review that change for you in our system.

Thank you!

**Comment by edent** [comment]
It's a little hard without access to the unminimised CSS - but here's my best effort.

The current code is:
```
table.statsDay td.label {
  text-overflow: ellipsis;
  -o-text-overflow: ellipsis;
  -icab-text-overflow: ellipsis;
  -khtml-text-overflow: ellipsis;
  -moz-text-overflow: ellipsis;
  -webkit-text-overflow: ellipsis;
}
```
The ellipsis doesn't show - as per Firefox's description of the problem:
![Screenshot from 2022-07-27 16-19-44](https://user-images.githubusercontent.com/837136/181285548-c7a98990-7904-45f6-9317-74e8a51d8528.png)

So `table.statsDay td.label` needs at *add*:
```css
overflow: hidden;
```

This will cause a problem with `td.label a, th.label a, td.label span`

```css
td.label a, th.label a, td.label span {
  text-overflow: ellipsis;
  -o-text-overflow: ellipsis;
  -icab-text-overflow: ellipsis;
  -khtml-text-overflow: ellipsis;
  -moz-text-overflow: ellipsis;
  -webkit-text-overflow: ellipsis;
  display: inline-block;
  width: 100%;
  white-space: nowrap;
  overflow: hidden;
 }
```

Needs to *remove* `display: inline-block;`
And, to make it look neater, *add* `vertical-align: top;`

TBH, the whole of that CSS is a bit of a mess! The whole thing could use rationalising. Doesn't look like it has been touched in 4 years.

**Comment by jeherve** [comment]
> TBH, the whole of that CSS is a bit of a mess! The whole thing could use rationalising. Doesn't look like it has been touched in 4 years.

It's been some time indeed, more than 4 years in fact. We've focussed our efforts on [the WordPress.com Stats view](https://wordpress.com/stats/day) instead, which provides more information and is mobile-friendly.

For now, I've included the changes you suggested, they seemed to test well on my end. You should start seeing the changes appear in your dashboard soon (that file is cached so it may take a little while).

Thanks for the patch!

*******

Internal reference: r249737-wpcom
