### ISSUE TITLE
Link from WordPress.com to enable Manage is improper

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#1800]
Pointed out by @jeherve:
Since Manage now has its own module instead of a setting under Jetpack > Settings > JSON API > Configure, the links asking you to enable Manage on <a href="http://wordpress.com/plugins">wordpress.com/plugins</a> lead you to an empty page (`/wp-admin/admin.php?page=jetpack&configure=json-api`)

Since there's no longer a fixed page to enable this, how should we handle?  Should we change the wpcom link to just go to the module listing?  Make a page specifically for enabling this?

Punting to 3.4.1, but this needs some thought

**Comment by mikeyarce** [comment]
also reported here: https://github.com/Automattic/calypso-pre-oss/issues/4540

**Comment by dereksmart** [comment]
Looks like it's been fixed! 

After testing, the link directs me to `http://dsmart.me/wp-admin/admin.php?page=jetpack&configure=manage`, which seems correct.
