### ISSUE TITLE
Podcast Player: single episode version

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#18008]
Variation of Podcast Player block for a single episode.

- Includes UI for selecting a single episode
- For Anchor, episode will be set by `anchor_episode` query parameter, which contains the episode guid

See PR: https://github.com/Automattic/jetpack/pull/18201

**Comment by retrofox** [comment]
design here 361-gh-Automattic/dotcom-manage#issuecomment-744655164

**Comment by retrofox** [comment]
361-gh-Automattic/dotcom-manage#issuecomment-744655164

**Comment by pablinos** [comment]
Fixed by #18719
