### ISSUE TITLE
VideoPress: Incorrect URL on All Modules Page

### ISSUE THREAD

**Issue by julsyd** [Automattic/jetpack#18017]
Clicking the VideoPress link on the All Modules page results in a 404 on the Jetpack support site.

#### Steps to reproduce the issue

1. In WP Admin, go to Jetpack > Modules.
2. Scroll down and click on the VideoPress module link.

#### What I expected

I expected the VideoPress link to bring me to one of the following support articles:

- https://jetpack.com/support/video-hosting/
- https://jetpack.com/support/jetpack-blocks/video-block/

#### What happened instead

Clicking the VideoPress link brings me to https://jetpack.com/support/videopress?site=DOMAIN, which returns a 404.

**Screenshots**

![Screen Shot on 2020-12-08 at 11:53:41](https://user-images.githubusercontent.com/29981758/101515151-0c348b80-394c-11eb-9b4b-5fa3c5da2746.png)

User report: 3557133

**Comment by jeherve** [comment]
This should now be fixed.
