### ISSUE TITLE
Instant Search: HTML entities in result title

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#18044]
#### Steps to reproduce the issue

1. Go to FG (internal users only)
2. Search for "laptop"

#### What I expected

HTML entities are turned into their corresponding character for display.

#### What happened instead
Big old `&amp;` in my results.

**Screenshots**

<img width="727" alt="Screen Shot 2020-12-10 at 14 20 07" src="https://user-images.githubusercontent.com/17325/101709077-a71b9a00-3af3-11eb-80dd-533033eb446d.png">

**Comment by gibrown** [comment]
Ugh... I guess we messed something up when trying to fix some related encoding problems the other week.

**Comment by robfelty** [comment]
Since this seems to be cause by my change, I fixed it - The issue was with double-encoding of html entities. I think that this should solve it
D54569-code

**Comment by robfelty** [comment]
Deployed fix in r218631-wpcom

**Comment by bluefuton** [comment]
Can confirm that fixes the original issue ✅ Thanks for the patch @robfelty!

<img width="427" alt="Screen Shot 2020-12-22 at 10 28 54" src="https://user-images.githubusercontent.com/17325/102823864-91d23400-4440-11eb-9d4d-e5aa356a1f14.png">
