### ISSUE TITLE
Subscription Block: the placeholder/button text in the editor doesn't match the site

### ISSUE THREAD

**Issue by kbrown9** [Automattic/jetpack#18072]
### Steps to reproduce the issue

1. Install, activate, and connect Jetpack.
2. Navigate to `wp-admin -> Jetpack Settings -> Discussion`.
3. Scroll down to the Subscriptions card and enable the `Let visitors subscribe to new posts and comments via email` setting.
4. Create a new post.
5. Add a `Subscription Form` block. Notice that the email field placeholder text is `Enter your email address` and the button text is `Sign Up`.
6. Publish the post.
7. Navigate to the post. Notice that the email field placeholder text is `Email Address`, and the button text is `Subscribe`.

**Screenshots**
#### The Subscription Form block In the post editor:

<img width="654" alt="Screen%20Shot%20on%202020-12-11%20at%2015-32-55" src="https://user-images.githubusercontent.com/50059399/101953735-e0720980-3bc8-11eb-885a-14eaa0b92489.png">

#### The Subscription Form block in the post:

<img width="668" alt="Screen%20Shot%20on%202020-12-11%20at%2015-33-35" src="https://user-images.githubusercontent.com/50059399/101953713-d6500b00-3bc8-11eb-9ba1-b7dc93b32088.png">

### Previous Report

I found a previous report of a similar problem [here](https://github.com/Automattic/jetpack/issues/17590#issuecomment-716941502). In that report, the placeholder text was `Email Address` in the editor and `Enter your email address` on the site, which is the opposite of what I'm seeing now.

**Comment by ai2n** [comment]
Still running into this. 36772792-hc

**Comment by oskosk** [comment]
As of today, the rendering supports the text of the place holder and button as declared in the block attributes, But;
1. There's no UI for updating the placholder text. Although if you edit with code editor and add `{"subscribePlaceholder":"New placeholder"}` it's respected
1. The button text just works as expected 


#### Editor

<img width="738" alt="image" src="https://user-images.githubusercontent.com/746152/191951377-05aec396-b0bf-47d1-ae72-1ba60ffee79b.png">

#### Frontend

<img width="726" alt="image" src="https://user-images.githubusercontent.com/746152/191951620-7aff4cd6-dcdb-474f-a6cf-5dc319b4d3d4.png">


@ai2n I think your report arrived a few days after we fixed, but there wasn't a new release of Jetpack for the user at that moment.

**Comment by oskosk** [comment]
Closing this issue in favor of #26377
