### ISSUE TITLE
Publicize and Sharing: OG:Description Meta Tag is Forced on WooCommerce Shop Page

### ISSUE THREAD

**Issue by dcoleonline** [Automattic/jetpack#18071]
I tested this on a self-hosted site using only WordPress 5.6, WooCommerce 4.8.0, and Jetpack 9.2.1. I also tested this on WordPress.com using the Business plan. The issue can be reproduced on Storefront, Twenty Twenty-One, Twenty Twenty, and Twenty Nineteen, as well as various other themes I've tested.

1. Enable either the Publicize module, the Sharing module, or both.
2. Install WooCommerce
3. The Shop page should already be published and also designated within WooCommerce's settings here:
 `/wp-admin/admin.php?page=wc-settings&tab=products`. 
4. Visit the Shop page's URL in the browser and inspect the code to find this meta tag:
`<meta property="og:description" content="This is where you can add new products to your store.">`
6. Edit the Shop to include some text content. Publish those changes.
7. The meta tag does not update to override the default text, so the meta tag remains.

#### What I expected

I expected that the `og:description` meta tag would be not be forced on a Shop page which has no content in the editor.
I also expected that adding text to the page would replace the text in the `og:description` meta tag.

#### What happened instead

It seems like enabling either the Publicize or Sharing module forces this meta tag. Disabling both modules causes the meta tag to go away.

I also entered a custom description into the SEO Tools section on my WordPress.com test, but it did not overwrite the forced `og:description` meta tag.

**Screenshots**
This is what gets shared to Facebook for a test site's Shop page even though I have content in the page.

![image](https://user-images.githubusercontent.com/3505172/101933261-90338100-3ba1-11eb-9a55-6218fd0a8aae.png)

#### Source
WordPress.com Support 3555244-zen & 24024259-hc

**Comment by xpurichan** [comment]
Another report in 29580868-hc.

**Comment by katiebethbrown** [comment]
For searchability, noting that the description was updated in Aug 2021 to 

`"This is where you can browse products in this store.` 

but the main issue of the text being forced (and not using the excerpt as expected) remains.

Related:

- https://github.com/woocommerce/woocommerce/issues/30553

**Comment by samiff** [comment]
#24726 has been merged which should ship out with Jetpack version 11.1 on 2022-07-05

When "Customize your SEO settings" is enabled in `wp-admin/admin.php?page=jetpack#/traffic`, then you will see Jetpack's custom SEO description setting when editing a post/page:

![Screen Shot 2022-06-13 at 12 43 35 PM](https://user-images.githubusercontent.com/15803018/173429142-526eca0f-14f6-4a93-a1d3-1612a7d831a8.png)

And #24726 should allow that custom description to come through now.
