### ISSUE TITLE
Subscriptions Block: Unable to create logged-in centred layout

### ISSUE THREAD

**Issue by ianstewart** [Automattic/jetpack#18085]
It appears that it may be difficult to create a centered layout with the subscriptions block in the following scenario. (Active theme: Spearhead, Chrome, MacOS.)

Block in Editor, as added by user …

![image](https://user-images.githubusercontent.com/545779/102140729-507ccb80-3e25-11eb-9b67-23aae3ea6140.png)

Result logged-in on the front-end.

![image](https://user-images.githubusercontent.com/545779/102140643-2cb98580-3e25-11eb-882f-a79e6ebb614a.png)

**Comment by scruffian** [comment]
Connected to https://github.com/Automattic/jetpack/issues/15474
