### ISSUE TITLE
Style Jetpack dash widget connect box more appropriately 

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#1809]
The connect box for the Jetpack dash widget needs to be restyled to be less distracting for users. 

https://cloudup.com/cA_YeLFCcKo

**Comment by jeffgolenski** [comment]
Repaired in: https://github.com/Automattic/jetpack/tree/enhancement/consistent-ui-design-changes

**Comment by jeherve** [comment]
Nice! :+1:

**Comment by georgestephanis** [comment]
I felt the point of the green for the initial connect nag was to be distracting.  We want their attention so they'll connect Jetpack, or choose to deactivate it.

**Comment by jeffgolenski** [comment]
I understand the logic of being obtrusive behind all the green, but on the same token I think it sets the user up with a bad taste in their mouth by being overwhelming from the start. Trying to find a tasteful, yet prominent way to display our CTA. The new rendition is still large enough to get anyone's attention, but it's not too much. 

I'd like to do some testing with this new connect screen, perhaps get some feedback from users?

**Comment by jeffgolenski** [comment]
@georgestephanis just a follow up to the conversation above. What are your thoughts to my reply, sir?

**Comment by jeffgolenski** [comment]
Updated: 
![screen shot 2015-04-14 at 2 15 56 pm](https://cloud.githubusercontent.com/assets/214813/7144179/bf9422be-e2b1-11e4-9137-94e0386d4d27.png)

**Comment by dereksmart** [comment]
<3
