### ISSUE TITLE
Nav Unification: nav unification styles override and/or don't account for color schemes

### ISSUE THREAD

**Issue by frontdevde** [Automattic/jetpack#18092]
While testing color schemes in the context nav unification we noticed that nav unification styles override and/or don't account for color schemes. These issues surface when choosing any color scheme other than the default.

For example when choosing the existing color scheme Ectoplasm, the following issues can be observed:

**Masterbar:**
- [x] Masterbar background color isn't changing
- [x] Masterbar hover color isn't changing
- [x] Masterbar active color isn't changing

**Sidebar:**
- [x] Site card domain color isn't changing
- [x] Site card fadeout color isn't changing
- [x] Site card background color is changing on hover
- [x] Site card icon color isn't changing on hover

|Calypso|wp-admin|
|-|-|
|<img width="450" alt="Screenshot 2020-12-15 at 14 36 12" src="https://user-images.githubusercontent.com/1562646/102222571-deb78700-3ee3-11eb-9e4d-f772f250310d.png">|<img width="559" alt="Screenshot 2020-12-15 at 14 36 28" src="https://user-images.githubusercontent.com/1562646/102222564-db240000-3ee3-11eb-8cba-25b09c068b70.png">|

**Comment by frontdevde** [comment]
Noting that the masterbar background and hover color is not an issue for the color schemes ported from Calypso as I had already accounted for the same issue in Jetpack when the masterbar is active by adding override styles:

<img width="517" alt="Screenshot 2020-12-15 at 15 04 40" src="https://user-images.githubusercontent.com/1562646/102225007-f8a69900-3ee6-11eb-81b3-a070dc9b3810.png">

**Comment by frontdevde** [comment]
Looks like most (all?) of the selectors that have color values changed in Masterbar `admin-menu.css` might have to be adjusted for all color schemes.

Started with some of them for the Calypso color schemes
<img width="447" alt="Screenshot 2020-12-15 at 16 46 58" src="https://user-images.githubusercontent.com/1562646/102238145-b8024c00-3ef5-11eb-93c9-c095fba4baed.png">

**Comment by cpapazoglou** [comment]
@frontdevde I have created a PR fixing `fresh` and `light`. 
I have added the color specific rules to the bottom. You can copy the `light` rules and adjust them to calypso schemes. I am wondering though what we should do for the wp-admin themes. Should we leave the rules there (will be merged to proper files once nav-unification goes live)

**Comment by cpapazoglou** [comment]
> I am wondering though what we should do for the wp-admin themes. Should we leave the rules there (will be merged to proper files once nav-unification goes live)?

I am leaning towards creating `colors.css` relative to `modules/masterbar/admin-menu/admin-menu.css`. What is your take?
