### ISSUE TITLE
Social Icons widget should only add SVG code for the selected services

### ISSUE THREAD

**Issue by mishrashutosh** [Automattic/jetpack#18094]
#### Current behavior:
When added to a site, the Social Icons widget appends SVG code for all of its supported services to the page HTML. I might add only a few services like Facebook, Twitter, RSS, etc and the widget still adds SVG code for all the supported services from 500px to YouTube. That's over 20KB gzipped data (over 50KB uncompressed).

This can be verified at [https://testsite.ashutoshmishra.org/](https://testsite.ashutoshmishra.org/).

#### Preferred behavior:
If feasible, the widget should only add code for services chosen by the user. This will reduce size of the page HTML.

**Comment by jeherve** [comment]
Thanks for the report. This is currently tracked in #16673, so I'll close this as duplicate.
