### ISSUE TITLE
Send a Message/Whatsapp Button block: The button can't be removed EXCEPT when using Code Editor

### ISSUE THREAD

**Issue by retnonindya** [Automattic/jetpack#18104]
Hello awesome Jetpack team!

Just recently, I received a user report -- and I can replicate it -- that they unable to remove WhatsApp Button block (Send a Message Button block) from their editor.

#### Steps to reproduce the issue

Make sure the editor is displayed as Visual Editor:

1. Create a post or a page with the button.
2. Publish the post/page
3. Go out from editor, and go back. Click the post/page with the button to edit.
4. Remove WhatsApp Button block
5. Sometimes, the block will reappear back
6. Sometimes, it looks it's gone. Click 'Update'
7. Refresh the editor
8. The block reappears

#### What I expected
I expected the WhatsApp Button block to be removed and not reappear when the post/page editor is updated

#### What happened instead
The block reappears even after the post/page editor is updated.

The block can be removed only by using **Code Editor**. Click the three dots on the top right corner > Code Editor > Find the code

**Screenshots**

When trying to remove the block for the first time:
GIF: https://cldup.com/4chu_JBRHK.gif

Second attempt. The block is "removed" so I clicked 'Update'. Refresh the post editor and the block reappears:
GIF: https://cldup.com/-4i1V0IDCG.gif

The workaround (using Code Editor):
GIF: https://cldup.com/ATi6pBC-eb.gif

Anyway, I checked Code Editor after my attempt on removing the block from Visual Editor, and it seems a code remnant?
GIF: https://cldup.com/M-wQSEGH4B.gif

Thank you for checking into this!

**Comment by jeherve** [comment]
I believe this happens because you're deleting the child block, and not the parent block. Here is how I would go about it:

https://videopress.com/v/pYqlck4o

That's an annoying byproduct of parent / child blocks. @apeatling Can you think of a way we could address this on our end, or should this be something better addressed in Gutenberg itself in your opinion?

**Comment by retnonindya** [comment]
(Saw Jeremy's screen recording)

Oh my gooooosh! Thank you so much, Jeremy! This is a TIL for me. Thank you!

**Comment by philnick206** [comment]
Just had a chat related to this. We were struggling until we saw the parent block to remove: https://cln.sh/5sthGs

Reported in #8226220-hc

**Comment by jeherve** [comment]
Closing in favor of #25105.
