### ISSUE TITLE
Fatal error when tweetstorm invoked with non-http url

### ISSUE THREAD

**Issue by dd32** [Automattic/jetpack#18103]
On WordPress.org the following fatal error was encountered:
```
POST https://example.com/wp-json/wpcom/v2/tweetstorm/generate-cards?_locale=user

E_ERROR: Uncaught Requests_Exception: Only HTTP(S) requests are handled. in wp-includes/class-requests.php:566
Uncaught Requests_Exception: Only HTTP(S) requests are handled. in wp-includes/class-requests.php:566
Stack trace:
#0 wp-includes/class-requests.php(460): Requests::set_defaults('WordPress.org', Array, Array, 'GET', Array)
#1 wp-content/plugins/jetpack/_inc/lib/class-jetpack-tweetstorm-helper.php(1607): Requests::request_multiple(Array)
#2 wp-content/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-tweetstorm-parse.php(104): Jetpack_Tweetstorm_Helper::generate_cards(Array)
#3 wp-includes/rest-api/class-wp-rest-server.php(1160): WPCOM_REST_API_V2_Endpoint_Tweetstorm_Parse->generate_cards(Object(WP_REST_Request))
```

I'm unsure of the input to the endpoint that caused it, other than to say that it came from a post being edited, which doesn't appear to have any specific blocks related to Jetpack - https://wordpress.org/news/2020/12/introducing-learn-wordpress/   Revision history doesn't show any specific blocks, but at the time of the fatal the Youtube video was being inserted, it could also be related to the hashtag links included at the bottom?

It looks like Tweetstorm doesn't use WP_HTTP, but uses Requests directly with the multiple-request support, [it needs to either validate the URI's it's passing or catch exceptions (or both)](https://github.com/Automattic/jetpack/blob/9a437395f0d2f8248bea436faacd8445e71de846/_inc/lib/class-jetpack-tweetstorm-helper.php#L1597-L1607)

#### Steps to reproduce the issue

Unknown. 

#### What I expected

A valid API response.

#### What happened instead

A fatal error.

**Screenshots**

**Comment by jeherve** [comment]
cc @pento I'm not quite sure how to best address this. Do you think you could take a look?

It would seem that one of the blocks that was parsed for the Publicize Twitter Thread preview included a URL without a protocol. Should we correct / remove those when parsing the blocks' contents, and / or `esc_url` every URL in `Jetpack_Tweetstorm_Helper::generate_cards()` before we make any requests?
