### ISSUE TITLE
Admin Color Schemes: Fix site switcher contrast

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#18114]
This will probably need adjustment in the admin menu CSS file to account for the different background colors the admin menu can have.

#### Steps to reproduce the issue

1. With the admin menu active, select a color scheme other than the default.
2. Observe the fade-out transition in the site card standing out

**Screenshots**
<img width="1279" alt="Screen Shot 2020-12-16 at 09 21 48" src="https://user-images.githubusercontent.com/444434/102329372-3b687f80-3f80-11eb-9b96-2c5f3f3e6a27.png">

**Comment by obenland** [comment]
@frontdevde @cpapazoglou Is this something you could look at next week and try and get into 9.3?

**Comment by cpapazoglou** [comment]
@obenland something seems off in your screenshot. I can't reproduce it in my sandbox. Maybe you have cached CSS?

**Comment by obenland** [comment]
Indeed! Thank you!
