### ISSUE TITLE
Site Stats weeks and months charts show information for days

### ISSUE THREAD

**Issue by MattSpaur** [Automattic/jetpack#18113]
#### Steps to reproduce the issue

1. Click on Jetpack > Site Stats
2. Click on Weeks or Months Tab
3. Hover over column.

#### What I expected
You'll see information displayed for days in the tool tip box. See attached screenshot. 

#### What happened instead
I expected to see information for weeks or months. This happens even after I turned off all other plug-ins and switched to default 2021 theme. 

![Jetpack issue report 2020-12-16](https://user-images.githubusercontent.com/76114715/102364838-c0956980-3f6b-11eb-8662-ecb0c010453d.png)

**Comment by jeherve** [comment]
Thanks for the report. This is already tracked in #18109 so I'll close this issue as duplicate.
