### ISSUE TITLE
Conversation/Dialogue: follow-up issues list

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#18123]
The following is an issues list that we should tackle once https://github.com/Automattic/jetpack/pull/17916 is merged.

- [ ] Translate participants string. https://github.com/Automattic/jetpack/pull/17916#discussion_r544212748
- [ ] Consider using Date function to the timestamp control
- [x] Remove `entry-content` class from conversation block. https://github.com/Automattic/jetpack/pull/17916#discussion_r544227973
- [ ] Move away from the .json file https://github.com/Automattic/jetpack/pull/17916#discussion_r542285520
- [x] Reconsider lock dialogue blocks, making them available only in a conversation context
- [ ] Fix edge cases editing and removing participants between conversation and dialogue blocks.
- [x] Line-breaks in dialogues appear within the editor, but not on the frontend: https://github.com/Automattic/jetpack/pull/17916#pullrequestreview-554614205
- [ ] Wonder if we would be able to use schema.org metadata to give more context to conversations
- [x] Set default dialogue timestamp value according to the previous one
- [ ] Improve conversation block styles. Block preview performance is not good when the conversation gets long. https://github.com/Automattic/jetpack/pull/18247
- [ ] Remove or create fallback for `__experimentalNumberControl`

**Comment by jeherve** [comment]
Can we move away from the .json file as well, as we discussed here?
https://github.com/Automattic/jetpack/pull/17916#discussion_r542285520

**Comment by retrofox** [comment]
> Can we move away from the .json file as well, as we discussed here?
> [#17916 (comment)](https://github.com/Automattic/jetpack/pull/17916#discussion_r542285520)

yes, I think the translation is kind of a blocker for this approach. I really like the idea of sharing the same file with both sides, but it could get things unnecessarily complex.

**Comment by creativecoder** [comment]
What do you think of adding a new participant to the parent conversation when setting a custom participant in a dialogue block?

**Comment by creativecoder** [comment]
I've created issues for the remaining items, and will close this one out.

- https://github.com/Automattic/jetpack/issues/18282
- https://github.com/Automattic/jetpack/issues/18281
- https://github.com/Automattic/jetpack/issues/18283
- https://github.com/Automattic/jetpack/issues/18285
