### ISSUE TITLE
Donation Block: incorrect markup when inserting it in a column within the Columns block

### ISSUE THREAD

**Issue by jartes** [Automattic/jetpack#18165]
When adding a **Donation** block inside a column within the Column block, the markup gets broken: 

![Markup on 2020-12-21 at 17:08:51](https://user-images.githubusercontent.com/1046943/102796962-4e7bb500-43af-11eb-9b6f-0dd332d8f36a.png)

#### Steps to reproduce the issue

1. Create a new post or page.
2. Add a new Columns block with two columns
3. Add a Donation block in the first or second column. 
4. Add any other block on the other column

#### What I expected

A donation block inside the desired columns with the proper markup.

#### What happened instead

The donation block is displayed incorrectly, and it seems the markup is incorrect. 

**Screenshots**:

On the editor: 
![Markup on 2020-12-21 at 17:12:14](https://user-images.githubusercontent.com/1046943/102797232-b16d4c00-43af-11eb-8fca-6064fe7380c2.png)

On the front-end: 

![Markup on 2020-12-21 at 17:08:51](https://user-images.githubusercontent.com/1046943/102796962-4e7bb500-43af-11eb-9b6f-0dd332d8f36a.png)

Maybe related to #17894

**Comment by brookewp** [comment]
I ran into a similar issue, where an image block placed in adjacent column stacks below (which may be happening in the screenshot you shared, but out of view) hc-33272753
