### ISSUE TITLE
Button Block: Text Size does not change on published page

### ISSUE THREAD

**Issue by NoHopeRadio** [Automattic/jetpack#18162]
#### Steps to reproduce the issue

1. Create new post on Atomic site in most themes (Changing text size in Button Block is not an option on Simple sites. Tried on Stratford, Exford, different behavior in TwentyTwenty)
2. Add text.
3. Increase the text size.
4. Preview page.

#### What I expected
The text size should have some bearing on the size of the block on the finished page, and show similarly to how it appears in the editor.

#### What happened instead
The button remains small. Changing the size of the block with some of the other options leaves the text the same size as well, even at full width.

**Screenshots**
Editor: https://d.pr/i/8r5DUK -> Preview: https://d.pr/i/A0isNH
Editor: https://d.pr/i/xMBG9N -> Preview: Same as above.
Editor: https://d.pr/i/bM5ZuC -> Preview: https://d.pr/i/0OmBoO
In the TwentyTwenty theme, the text size does change in the editor, only the margins around the button:
https://d.pr/i/mxSE3j -> https://d.pr/i/q4228W

Have not tested changing the text size with CSS or anything else.

**Comment by jeherve** [comment]
Thanks for the report.

Since the Button block is part of the core WordPress experience, I would recommend reporting that problem in [the Gutenberg repository](https://github.com/wordpress/gutenberg/issues) instead.
