### ISSUE TITLE
Infinite Scroll "infinite-scroll" in body_class is not applied when using click to scroll

### ISSUE THREAD

**Issue by ryelle** [Automattic/jetpack#1817]
When Infinite Scroll is enabled using the click type to load more posts, the `body_class` function thinks it's disabled and doesn't add the class. I think this was introduced in #1208. This is causing duplicate buttons in themes that use `.infinite-scroll` to hide the core pagination links: https://themes.redradar.net/museum/ 

It looks like the `infinite_scroll` setting is not set, which is why `body_class` thinks it's disabled.

**Comment by samikeijonen** [comment]
I confirm this and it'll probably affect all _s based themes. I was wondering why it's milestone is 3.5.? I think it could be fixed sooner.

**Comment by bradyvercher** [comment]
This is affecting some client sites, so I'd like to see the milestone bumped as well. I've added some unit tests and a fix if it'll help get this through faster. Thanks!

**Comment by mikeyarce** [comment]
User also reported in 2142684-t

**Comment by jeherve** [comment]
Also reported in 133074-chat
