### ISSUE TITLE
Autoloader: woocommerce/packages remains empty on v2.7.1

### ISSUE THREAD

**Issue by szepeviktor** [Automattic/jetpack#18186]
#### Steps to reproduce the issue

Add this to `composer.json`

```json
{
    "require": {
        "php": "~7.1",
        "ext-gettext": "*",
        "ext-hash": "*",
        "ext-json": "*",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "woocommerce/woocommerce": "4.9.0-rc.1"
    },
    "minimum-stability": "stable",
    "extra": {
        "installer-paths": {
            "{$name}/": [
                "type:wordpress-plugin"
            ]
        }
    }
}
```

Execute `composer update`

#### What I expected

It worked in v2.2.0 with WC v4.8.0, copied all 3 packages under `woocommerce/packages/`.

#### What happened instead

In v2.7.1 `woocommerce/packages/` directory remains empty.

Please advise.
I release WC stubs here https://github.com/php-stubs/woocommerce-stubs

**Comment by vedanshujain** [comment]
Looks like this is because of the new WC release process, where we tag the source before dist files are added, and not an JP issue. I will update the release using the old process so that these packages are included again and close this issue.

**Comment by valeciawolf34** [comment]
"require": {
        "php": "~7.1",
        "ext-gettext": "*",
        "ext-hash": "*",
        "ext-json": "*",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "woocommerce/woocommerce": "4.9.0-rc.1"
    },
    "minimum-stability": "stable",
    "extra": {
        "installer-paths": {
            "{$name}/": [
                "type:wordpress-plugin"

Valecia G Rodriguez

**Comment by szepeviktor** [comment]
@vedanshujain Thank you for response.
Now the ZIP - Composer gets - already contains 3 directories inside `packages/`.
So Composer downloads all 4 packages and WC has copies of the other 3 inside it.

In WC v4.8.0 all 4 packages **were sound** and `jetpack-autoloader` copied the 3 packages to `woocommerce/packages/` during `dump-autoload`. Could we get that back?

**Comment by kbrown9** [comment]
Hi @szepeviktor I've tested this a bit, and I'm not seeing a difference between WooCommerce v4.8.0 and v4.9.0-rc.1.

If you build with WooCommerce v4.8.0, do you get the 4 packages installed at the top level? For example, using your `composer.json` file with Woo 4.8.0:

```
{
    "require": {
        "php": "~7.1",
        "ext-gettext": "*",
        "ext-hash": "*",
        "ext-json": "*",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "woocommerce/woocommerce": "4.8.0"
    },
    "minimum-stability": "stable",
    "extra": {
        "installer-paths": {
            "{$name}/": [
                "type:wordpress-plugin"
            ]
        }
    }
}
```

Then run `composer update`, which results in:

<img width="649" alt="Screen%20Shot%20on%202020-12-29%20at%2009-57-25" src="https://user-images.githubusercontent.com/50059399/103292710-5ee9ec00-49bc-11eb-8998-5059f9a8d675.png">

**Comment by szepeviktor** [comment]
@kbrown9 Thank you for your response.

- v4.8.0 gives you 3 packages copied to woocommerce/packages directory during Composer's dump-autoload

/action-scheduler  
/woocommerce-admin 
/woocommerce-blocks

- previous v4.9.0-rc.1 gave you an empty woocommerce/packages directory

- current v4.9.0-rc.1 gives you the above 3 packages in woocommerce/packages but without jetpackautoloader, pacakged in woocommerce/woocommerce - which is a very bad thing: having 3 other packages inside a package

Please restore the original state:

- 4 sound packages: woocommerce action-scheduler woocommerce-admin  woocommerce-blocks
- jetpackautoloader doing its jobs: copying those 3 to WC's packages/ directory

Thank you.

**Comment by szepeviktor** [comment]
From its inception my stubs generators work from `source/woocommerce/packages/*/src`
https://github.com/php-stubs/woocommerce-stubs/blob/master/finder-packages.php#L4

- which is all right in v4.8.0
- completely empty in previous v4.9.0-rc.1
- fake pre-packaged in v4.9.0-rc.1

**Comment by kbrown9** [comment]
Thanks for the details!

I’m not aware of any recent changes to the `jetpack-autoloader` package that would have caused changes to the WooCommerce build. I’ll look into that further, but I don’t think the `jetpack-autoloader` package is causing this.

### WooCommerce v4.8.0

When I build a project using the `composer.json` file above with Woo v4.8.0, I get the three packages in `woocommerce/packages` and the three packages in the top level directory, as show in my previous comment.

The WooCommerce v4.8.0 source does have the three packages pre-packaged in the `woocommerce/packages` directory: https://github.com/woocommerce/woocommerce/tree/4.8.0/packages

If you build the project with Woo v4.8.0, do you end up with the three packages in both the top level directory and the `woocommerce/packages` directory like I did?

**Comment by szepeviktor** [comment]
> If you build the project with Woo v4.8.0, do you end up with the three packages in both the top level directory and the `woocommerce/packages` directory like I did?

Yes!
Those were released okay https://github.com/php-stubs/woocommerce-stubs/releases/tag/v4.8.0

**Comment by szepeviktor** [comment]
This is the proper empty directory
https://github.com/woocommerce/woocommerce/tree/4.7.1/packages

This is the pre-populated :(
https://github.com/woocommerce/woocommerce/tree/4.9.0-rc.1/packages

And it is shocking to realize that v4.8.0 also not empty
https://github.com/woocommerce/woocommerce/tree/4.8.0/packages 🤯

**Comment by szepeviktor** [comment]
What is up here??
https://github.com/woocommerce/woocommerce/tree/4.6.0/packages
v4.6.0 is also non-empty.

**Comment by kbrown9** [comment]
Do you mind opening an issue in the WooCommerce repo, so that the Woo team can take a look at the release process and determine if they should make changes?

Since the `jetpack-autoloader` package isn't involved, I'm going to close this issue. If I'm mistaken about that and `jetpack-autoloader` is actually involved, we can reopen it.

**Comment by szepeviktor** [comment]
Maybe you have the knowledge. #29078
Is it `jetpack-autoloader`'s job to populate WC's `packages/` directory?

**Comment by kbrown9** [comment]
Hi @szepeviktor - I believe your issue is related to the Woo release process. The `jetpack-autoloader` doesn't populate WC's `packages` directory.

**Comment by szepeviktor** [comment]
@kbrown9 Thank you.
Do you imply that they manually copy those packages into `/packages`?

**Comment by ObliviousHarmony** [comment]
@szepeviktor Since this issue has nothing to do with Jetpack I will reply in your [other issue](https://github.com/woocommerce/woocommerce/issues/29078).
