### ISSUE TITLE
 Bug PHP 8: PHP Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /wp-content/plugins/jetpack/class.jetpack-modules-list-table.php:138

### ISSUE THREAD

**Issue by codetipi** [Automattic/jetpack#18185]
Hey everyone,

1. With PHP 8 running, click to open the Jetpack modules list page
2. The "Show" section on the right has:
"THERE HAS BEEN A CRITICAL ERROR ON THIS WEBSITE. PLEASE CHECK YOUR SITE ADMIN EMAIL INBOX FOR INSTRUCTIONS. LEARN MORE ABOUT DEBUGGING IN WORDPRESS."
3. Error Log shows:
PHP Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /wp-content/plugins/jetpack/class.jetpack-modules-list-table.php:138

Hope this info helps.

**Comment by jeherve** [comment]
Thanks for the report. This was fixed in #18053.
