### ISSUE TITLE
Jetpack Search: Issue with the search results after switching language

### ISSUE THREAD

**Issue by devNigel** [Automattic/jetpack#18190]
#### Steps to reproduce the issue

1. Create a Business plan site, set Site Language as English.
2. Create a few posts or WooCommerce products.
3. Switch Site Language to another language such as Bulgarian ( language for the site I debugged )
4. Create a few posts or WooCommerce products in that language script.
5. User search functionality to search for products, you will notice the search result will show content only created with currently set language regardless of the language used to search.

#### What I expected

I expected search functionality to show products that were added before updating the site language.

#### What happened instead

Search functionality did not return products that were added before updating the site language.

More info: 3581571-zd

**Comment by robfelty** [comment]
Fixed with D54822-code
