### ISSUE TITLE
Contact Form in Classic Editor Block converted to Shortcode Block

### ISSUE THREAD

**Issue by ianstewart** [Automattic/jetpack#18210]
#### What I expected

When a contact form shortcode is in a classic editor block I expected it to become a contact form block when converted to a block.

#### What happened instead

It was converted to a shortcode block.

![contact-form-shortcode](https://user-images.githubusercontent.com/545779/103700806-9c291d80-4f6a-11eb-8ac7-aadb9c5fb4d7.gif)

**Comment by simison** [comment]
Rest of the old Jetpack shortcodes might need to be audited in case there are other blocks like this?

**Comment by ianstewart** [comment]
Fun. https://jetpack.com/support/shortcode-embeds/ :D
