### ISSUE TITLE
Nav Unification: Settings Link in Calypso goes to WP-Admin

### ISSUE THREAD

**Issue by ktyfuller604** [Automattic/jetpack#18216]
#### Steps to reproduce

1. Click on the "Settings" menu option in Calypso

#### What I expected

The menu to expand like the other menu options (Tools for example)

#### What happened instead

The Settings menu opened WP-Admin

#### Browser / OS version

MacOS Catalina v 10.15.7/ Chrome v. Version 86.0.4240.198

#### Screenshot / Video

https://user-images.githubusercontent.com/1398304/103673482-7aac3f80-4f32-11eb-8a3a-c8aaf0fda1b5.mov

#### Context / Source

#manual-testing

**Comment by obenland** [comment]
Can you help me understand what needs fixing here?

From what I see in the video, the submenus _do_ expand, they just do it in wp-admin and not Calypso. The interoperability of Calypso and wp-admin is what this project is about, so to me this feels more like a feature (albeit one where I wish the loading duration was shorter).

**Comment by obenland** [comment]
> Can you help me understand what needs fixing here?

Resolved in https://github.com/Automattic/jetpack/pull/18219#issuecomment-755509987
