### ISSUE TITLE
Mailchimp Block: confusing flow for unconnected users

### ISSUE THREAD

**Issue by kbrown9** [Automattic/jetpack#18211]
#### Steps to reproduce the issue

1. Install, activate, and connect Jetpack. The site and first user are now connected.
2. Create another admin user, the secondary admin. Do not connect this user to wpcom.
3. Log in as the secondary admin.
4. Create a post and add the Mailchimp block.
5. Click the `Setup Mailchimp` button.
6. Log in to your WPCOM account.
7. See a blank page and a JS error in the console.

This occurs because the user is not connected and cannot manage the site using Calypso.

#### What I expected
An unconnected user should be prompted to connect to their WPCOM account when they attempt to set up a Mailchimp block.

#### What happened instead
An unconnected user sees a blank page.

**Comment by tmmbecker** [comment]
@kbrown9 it appears that this was fixed in [9.7](https://github.com/Automattic/jetpack/pull/19507).

**Comment by kbrown9** [comment]
Thanks for noticing this issue @tmmbecker! Yes, it's working correctly for me now.
