### ISSUE TITLE
Infinite Scroll on Single Posts

### ISSUE THREAD

**Issue by MuhammedSwalihct** [Automattic/jetpack#18226]
The Jetpack Infinite Scroll is a great feature. However, it doesn't support infinite scrolling on Single Posts. Many websites such as CNET use infinite scrolling to increase the pageviews thus gain better user engagement. As Jetpack already has this feature, would it be possible to extend its functionality to Single posts as well? Or is there already a way to do that?

**Comment by jeherve** [comment]
Related: #79

We discussed this a few years ago, and opted not to implement such a feature in Jetpack, as it would rely a lot on specific themes. I would recommend that you look for a theme that implements that feature out of the box, or that you look for another plugin that offers such a feature.

**Comment by MuhammedSwalihct** [comment]
Please check this.. https://github.com/Automattic/jetpack/issues/79#issuecomment-757108837
