### ISSUE TITLE
Protect: Call to undefined function inet_pton() 

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#1824]
From 2132428-t:

```
Fatal error: Call to undefined function inet_pton() in
H:\hshome\XXXXX\domain.com\wp-content\plugins\jetpack\modules\protect.php
on line 268
```

See https://github.com/piwik/piwik/issues/2385

cc @samhotchkiss

**Comment by aheckler** [comment]
Seeing a related problem on my personal site. On `wp-login.php` I am seeing this error:

`Warning: inet_pton(): Unrecognized address 2601:8:3200:7125:6d67:7d94:9b8:84db in /home/adamheck/public_html/wordpress/wp-content/plugins/jetpack/modules/protect.php on line 276`

The IP shown is my IPv6 IP, but it turns out that the version of PHP on my server was not compiled with IPv6 support, so `inet_pton()` throws this error. It's *not* the "call to undefined function" error.

Solution, for my problem anyway, is to see if `AF_INET6` is defined, since it won't be if IPv6 support is not compiled in PHP.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/jetpack-34-update-fatal-error-call-to-undefined-function-wp_generate_password?replies=11&view=all#post-6734219

**Comment by jeherve** [comment]
Also reported in these threads:
https://wordpress.org/support/topic/error-in-jetpack-2?replies=1&view=all
https://wordpress.org/support/topic/connecting-jetpack-to-wordpresscom-causes-error-in-wp-login?replies=5&view=all

**Comment by richardmtl** [comment]
Also 2138955-t

**Comment by kraftbj** [comment]
2139071-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/fatal-error-call-to-undefined-function-after-upgrade?replies=6&view=all

**Comment by mikeyarce** [comment]
also here: 2140171-t

**Comment by richardmtl** [comment]
Also in 2140821-t

**Comment by Aaronls79** [comment]
http://evil.gnome.ninja/wp-login.php
I am seeing the error here as well. 
The blog is hosted on godaddy.
I see the error on Chrome and IE
https://www.dropbox.com/s/mtzfwbov1zrtonn/php%20error.png

**Comment by richardmtl** [comment]
Also in 2155929-t

**Comment by dereksmart** [comment]
http://php.net/manual/en/function.inet-pton.php

This function is supported in Windows PHP >= 5.3, and other platforms >= 5.1

These errors are most likely coming from sites that are running Windows < PHP 5.3

Other than suggesting to upgrade PHP version, I'm not sure there is a good workaround as I imagine changing that logic would be painful.  

cc @roccotripaldi

**Comment by jeherve** [comment]
Since WordPress only requires PHP 5.2.4 ([ref](https://wordpress.org/about/requirements/)), can we find a way to make this work on 5.2.4?

**Comment by Aaronls79** [comment]
@dereksmart You are correct, I updated my version of PHP to be 5.4 and the problem went away. When I installed this feature it gave me no indication of required PHP version. Is there away you could block or warn users when installing this feature that they do not have the required version?

**Comment by samhotchkiss** [comment]
Yes, we had a fallback function in BruteProtect, just need to move it over

**Comment by samhotchkiss** [comment]
Nevermind... that was a different function.  I'm pinging @roccotripaldi, as he did the swap

**Comment by aheckler** [comment]
> These errors are most likely coming from sites that are running Windows < PHP 5.3

My personal SiteGround site is on PHP version 5.5.17 and was showing this error. Not now (likely because I have an IPv4 IP though.

**Comment by dereksmart** [comment]
@aheckler which error are you referring to?  The `Unrecognized address` error you mentioned before is separate from the `Call to undefined function`.

**Comment by aheckler** [comment]
Ahh you're right, sorry. :/ Was confused.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/cant-login-into-my-domain-error-call-to-undefined-function-inet_pton?replies=1&view=all

**Comment by samhotchkiss** [comment]
@jeherve - If we have a particularly tech-savvy user, it would be great to have them test out the patch in #1962
