### ISSUE TITLE
Subscriptions Block: font size cannot be modified

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#18250]
#### Steps to reproduce the issue

1. Start from a site running Jetpack and the Gutenberg plugin
2. Go to Jetpack > Settings > Discussion and enable Subscriptions
3. Go to Posts > Add New
4. Add a Subscriptions block
5. In the block sidebar, attempt to change the font size; it won't work.

https://videopress.com/v/vwMbJPOK

It seems to be limited to installs of Gutenberg so far. 

Reported here:

p8oabR-B4-p2#comment-4843

**Comment by aaronrobertshaw** [comment]
This one stems from a breaking change introduced in https://github.com/WordPress/gutenberg/commit/5d7ebd11d0221aefd721c3d5b426a759bf7d0275 and the subsequent update to Gutenberg's theme.json file https://github.com/WordPress/gutenberg/pull/27083. I'll work on a fix for this today.
