### ISSUE TITLE
Instagram Gallery block: not compatible with localhost?

### ISSUE THREAD

**Issue by chvillanuevap** [Automattic/jetpack#18253]
Are the Instagram blocks compatible with localhost development?

#### Steps to reproduce the issue

1. Open a localhost development site.
2. Add a new post.
3. Try to add an Instagram or Instagram Gallery block.
4. It does not show up in the options (Facebook and Pinterest do show up).

#### What I expected

I want to be able to use Instagram blocks in development to design the footer of a blocks theme.

#### What happened instead

No Instagram blocks are available in localhost development.

**Comment by jeherve** [comment]
Closing as duplicate of #18252
