### ISSUE TITLE
.com Admin Bar is Missing Hamburger Nav in wp-admin (AT sites) 

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/jetpack#18256]
#### Steps to reproduce the issue

1. Have a Site on WordPress.com Business/eCommerce
2. Add an Author to the site 
3. As an Author of the site go to wp-admin 
4. See the issue where there's no hamburger menu to navigate. 

#### What I expected

To see the hamburger menu as I do on simple sites. 
Screen recording of what I expect to see: https://d.pr/v/ioZ02q 

**Note:** Admin roles on the AT site will see the hamburger menu, Authors won't (I haven't had time today to test other roles like a contributor, Editor, etc.).  

#### What happened instead

The Hamburger menu is missing so there's no way to effectively navigate wp-admin to page or posts. 
Screenshot:

<img width="289" alt="Screen Shot 2021-01-08 at 15 24 10" src="https://user-images.githubusercontent.com/426388/104157083-b9d30880-53ea-11eb-9a78-ac4f4aa01e39.png">

- 3633199-zen
- p1610126297015800-slack-C02FMH4G8

**Comment by jeherve** [comment]
Thanks for the report. It's worth noting that we're currently making significant changes to this interface as part of the nav-unification project. It may be worth trying to test with the latest changes to see if the bug is still there. 

Reference: paYJgx-1eA-p2

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
