### ISSUE TITLE
Instagram Gallery Block: Not working in localhost?

### ISSUE THREAD

**Issue by chvillanuevap** [Automattic/jetpack#18252]
Are the Instagram blocks compatible with localhost development?

#### Steps to reproduce the issue

1. Open a localhost development site.
2. Add a new post.
3. Try to add an Instagram or Instagram Gallery block.
4. It does not show up in the options (Facebook and Pinterest do show up).

#### What I expected

I want to be able to use Instagram blocks in development to design the footer of a blocks theme.

#### What happened instead

No Instagram blocks are available in localhost development.

**Comment by jeherve** [comment]
That is correct. The Instagram Gallery block relies on a connection to WordPress.com to work. That connection is used to connect to Instagram without the need for you to manage a Facebook developer account and an app and its maintenance. You will not be able to use the block on a site that is not connected to WordPress.com.
