### ISSUE TITLE
Jetpack is causing timeout errors on update-core.php

### ISSUE THREAD

**Issue by pippinsplugins** [Automattic/jetpack#1825]
Since Jetpack 3.4, it is causing timeout errors when loading update-core.php, both when checking for updates and when performing updates.

The timeout appears to happen after the the update checks are performed but before the results are displayed to the site admin.

It also seems to happen when attempting to install new plugins.

I've confirmed this across 5-6 sites.

The problem immediately goes away when Jetpack is deactivated. 3.4.1 does not solve it either.

**Comment by pippinsplugins** [comment]
For example:
![screen shot 2015-03-19 at 1 25 50 pm](https://cloud.githubusercontent.com/assets/1034109/6737742/7bdebce4-ce3b-11e4-8141-6b83a6f2f315.png)

**Comment by pippinsplugins** [comment]
My sites are running on Pagely but I saw this on other sites on other hosts too.

**Comment by pippinsplugins** [comment]
One more detail: my sites are a mix of multisite and single site, so it doesn't appear to be specific to one setup.

**Comment by georgestephanis** [comment]
@pippinsplugins Do you have xdebug active on any of them that you can get a profiling dump as to the cause?

**Comment by pippinsplugins** [comment]
No I don't. I'll try and get more info for you.

**Comment by Ipstenu** [comment]
@pippinsplugins I don't know if this is related, but I ran into this:

> Warning: Creating default object from empty value in /home/ipstenu/public_html/wp-content/plugins/easy-digital-downloads/includes/EDD_SL_Plugin_Updater.php on line 154

Hit refresh, it went away.

**Comment by pippinsplugins** [comment]
Hmm, I have not seen that but this did happen on a site without EDD, so I'd venture a guess that it is unrelated.

**Comment by samhotchkiss** [comment]
I've not been able to recreate this-- anybody else?

**Comment by pippinsplugins** [comment]
Happened again this morning:
![screen shot 2015-03-20 at 9 56 42 am](https://cloud.githubusercontent.com/assets/1034109/6753925/73cfa048-cee7-11e4-875c-8fedc648e34e.png)

I'm going to try and track it down to a specific module (if possible).

**Comment by pippinsplugins** [comment]
I've tracked this down to a conflict with our custom plugin updater in Easy Digital Downloads: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/EDD_SL_Plugin_Updater.php

My guess is that the auto update class and EDD's is conflicting: https://github.com/Automattic/jetpack/blob/master/class.jetpack-autoupdate.php

**Comment by samhotchkiss** [comment]
Hey Pippin, can you send me a copy of EDD to test with?  sam at automattic

**Comment by pippinsplugins** [comment]
It's available on .org: https://wordpress.org/extend/plugins/easy-digital-downloads/

Or github: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/

**Comment by samhotchkiss** [comment]
:+1: will check this out

**Comment by pippinsplugins** [comment]
My best guess so far is that it's due to this: https://github.com/Automattic/jetpack/commit/46851431e0ed54df6a470b989ae49efd8aedfd1d#diff-ac54787f5c8bcac1491098d8fb5a8d18

**Comment by samhotchkiss** [comment]
@roccotripaldi can you take a look at ^

**Comment by pippinsplugins** [comment]
Oh! There's no return in `save_update_data`. It needs to the value passed to it since it's being called on a filter. I'll submit a PR now.

**Comment by pippinsplugins** [comment]
Wait, maybe not, you're using the action instead of the filter, so that could be fine.

**Comment by pippinsplugins** [comment]
Ok scratch that, I forgot there was an action called `set_site_transient_{transient}` and not just filters.

**Comment by dereksmart** [comment]
I think this has been resolved since 3.4 

Please reopen if any more reports with current Jetpack
