### ISSUE TITLE
Subscriptions Block: Missing email address

### ISSUE THREAD

**Issue by scruffian** [Automattic/jetpack#18278]
The email address on the Subscriptions block is missing in the front end. Originally reported here: pNEWy-duL-p2#comment-52549

#### Steps to reproduce the issue

1. Create a Simple site
2. Add a Jetpack Subscriptions block
3. Preview the page
4. Notice that the email address field is missing

**Screenshots**
![image-2](https://user-images.githubusercontent.com/275961/104196588-ddfb0d80-541b-11eb-9b71-8c36d51ae68d.png)

**Comment by jeherve** [comment]
> Notice that the email address field is missing

I believe that's done on purpose. On WordPress.com, if you are logged in you're presented with a simpler form, you do not need to enter your email address, you can subscribe right now. The problem is, we do not reflect that different state in the editor right now. This is tracked here: #15474.
