### ISSUE TITLE
Anchor.fm: Podcast episode post player options

### ISSUE THREAD

**Issue by creativecoder** [Automattic/jetpack#18279]
When a new post is created from a link, turn off the following podcast player block options

- Show cover art
- Show episode title
- Show episode description

<img width="265" alt="image" src="https://user-images.githubusercontent.com/1699996/104201750-b1c99780-53ef-11eb-9a84-b57cd522311c.png">

**Comment by kwight** [comment]
Why don't we want these?

**Comment by creativecoder** [comment]
> Why don't we want these?

@kwight They're duplicative of content already on the page in the single episode template.

Reference: pb5gDS-13j-p2#comment-2315
