### ISSUE TITLE
wpautop in Gutenberg template part function adding <br> tags to Instagram Gallery

### ISSUE THREAD

**Issue by chvillanuevap** [Automattic/jetpack#18271]
#### Steps to reproduce the issue

1. Activate the TT1 Blocks theme.
2. Open the FSE and edit the header (or any other) template part.
3. Add the "Latest Instagram Posts" block. Select 6 columns and 6 posts. 
4. Save and preview.

#### What I expected
The posts to display.

#### What happened instead
The posts do display, but multiple `<br>` tags are added in between the anchor tags, causing the grid to not display properly. This issue DOES NOT occur if the block is added to the post content of a regular post or page. It is isolated to adding the block in a template part with the FSE. It is caused by the `wpautop` function call in `gutenberg_render_block_core_template_part`.

I'm not sure if this is an issue with Jetpack or Gutenberg.

**Screenshots**
![screencapture-tt1-blocks-ngrok-io-2021-01-09-11_54_38](https://user-images.githubusercontent.com/3827771/104106241-9c2e6380-5271-11eb-99c6-60698fd52c13.png)

**Comment by chvillanuevap** [comment]
A workaround is to filter how the block is rendered and remove all newline characters before the output is processed through `wpautop`.
```
add_filter( 'render_block', 'myfunction_render_jetpack_instagram_gallery_block', 10, 2 );
/**
 * Filter the block being rendered in the Instagram Gallery block render callback, before it's processed.
 *
 * @param string $block_content The block content about to be appended.
 * @param array  $parsed_block  The full block, including name and attributes.
 *
 * @return string String of rendered HTML.
 */
function myfunction_render_jetpack_instagram_gallery_block( $block_content, $parsed_block ) {

	if ( 'jetpack/instagram-gallery' === $parsed_block['blockName'] ) {
		$block_content = str_replace( [ "\r", "\n" ], '', $block_content );
	}

	return $block_content;

}
```

**Comment by jeherve** [comment]
I cannot seem to be able to reproduce on my end, with or without the latest version of the Gutenberg plugin. Does this happen regardless of the theme you use on your site?

**Comment by chvillanuevap** [comment]
Yes, it's regardless of theme. TT1 Blocks and my theme have a block-template-part, header.html. I inserted the Instagram Gallery block from Jetpack in this header.html using the FSE. Block template parts use `gutenberg_render_block_core_template_part` to render the block, which filters the content through `wpautop`. This function is replacing `\n` characters with `<br>` characters on the theme.

I'm using WordPress 5.6, Gutenberg 9.7.0, and Jetpack 9.2.1. That's it. If you can't reproduce, it might just be an issue on my end. Either way, the workaround I wrote removes the newlines, and fixes the issue for me. Thanks!

**Comment by jeherve** [comment]
Ah, I was able to reproduce as well. Thank you!

**Comment by yansern** [comment]
This issue is no longer replicable. Tested with the latest TT1 Blocks on Atomic with Side Editor enabled.
