### ISSUE TITLE
Stats: Dashboard widget header styling

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#18287]
The header for the stats dashboard widget has some layout issues, specifically with the configure link being pushed out of the layout. See the screenshot below.

#### Steps to reproduce the issue

1. Create JN site
2. Connect JN site
3. Go to WP-admin dashboard

#### What I expected

For all of the items to be within the widget.

#### What happened instead

Not that. 😄 

**Screenshots**

<img width="513" alt="Screen Shot 2021-01-11 at 11 16 55 AM" src="https://user-images.githubusercontent.com/1126811/104215561-8ef2af80-53fe-11eb-991c-469b377e4089.png">

In Slack, @folletto made a suggestion that we could move the "configure" link down to the bottom of the widget and mocked this up.

![Screenshot 2021-01-11 at 16 37](https://user-images.githubusercontent.com/1126811/104216239-67501700-53ff-11eb-885b-d3fdf1577314.png)

**Comment by jeherve** [comment]
This seems to be caused by the changes in https://core.trac.wordpress.org/changeset/48373

I'll take a look at updating our widget accordingly.
