### ISSUE TITLE
Post By Email: Email addresses in links are half-stripped

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#1828]
If I send some plaintext content with email addresses like so:

```
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
occaecat cupidatat non proident, sunt in culpa qui officia deserunt
mollit anim id est laborum. 

adam@egewgwgwe.com

adam.me@ewgwegewwgeweg.com

adam@yahoo.com

email addresses are maybe stripped? here's an @ symbol, what happens?
```

Everything comes out in the post OK. Screenshot: http://d.pr/i/1hVNw/iUvAu8IC

If I link one of the addresses with a `mailto` link, however, the `@` and everything after is stripped. Screenshot: http://d.pr/i/au7l/38Fd9ZEi

2077516-t and 2130038-t

**Comment by samhotchkiss** [comment]
@aheckler: Unless I'm mistaken, this isn't a Jetpack issue, but a Post By Email issue, right?  Can it be replicated on wpcom?

**Comment by aheckler** [comment]
@samhotchkiss -- You're right, happens on WP.com too:

![screen shot 2015-04-01 at 2 55 45 pm](https://cloud.githubusercontent.com/assets/5512652/6948951/39d5ed7e-d87f-11e4-8b4e-faeffd313667.png)

Close this I guess?

**Comment by jeherve** [comment]
> Close this I guess?

And reopen on wpcom. :)

**Comment by aheckler** [comment]
As it turns out, there's already a Trac ticket for it (#5425).
