### ISSUE TITLE
Conversation/dialog blocks: line spacing between dialog entries

### ISSUE THREAD

**Issue by creativecoder** [Automattic/jetpack#18297]
Make line spacing consistent within editing and on the front end (https://github.com/Automattic/jetpack/pull/17916#pullrequestreview-554614205)

<img width="300" src="https://user-images.githubusercontent.com/426388/102492624-3e439d00-4072-11eb-9448-e0fc84ecb413.png" />
<img width="200" src="https://user-images.githubusercontent.com/426388/102492651-4a2f5f00-4072-11eb-848c-a09225395e34.png" />

**Comment by retrofox** [comment]
I think it's already solved. Can you confirm it?

Editor canvas | Front end
--------------|----------
![image](https://user-images.githubusercontent.com/77539/105032841-1612d980-5a36-11eb-8f52-2ad8ad27ddd0.png) | ![image](https://user-images.githubusercontent.com/77539/105032904-2d51c700-5a36-11eb-99cd-25f9edc31102.png)

**Comment by creativecoder** [comment]
I'm still seeing a difference, but looks like it's coming from Core block wrapper styles, so would be expected. Closing this issue.

<img width="1397" alt="Screen Shot 2021-01-20 at 13 38 18" src="https://user-images.githubusercontent.com/1699996/105225956-f60e1380-5b24-11eb-9062-635d2c2f04d2.png">

**Comment by retrofox** [comment]
Yeah, and let's keep in mind that it's handled by the theme too. So I'm pretty sure it could change even more depending on the site theme.
