### ISSUE TITLE
Stats: Configuration options are no longer available on dashboard widget

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#1830]
It used to be possible to configure the dashboard stats widget by hovering over the Title bar and clicking "Configure":

![image](https://cloud.githubusercontent.com/assets/3676359/6753698/52497ec4-ceee-11e4-9907-d6e5c57ba389.png)

As of 3.4, it's no longer possible.

**Comment by richardmtl** [comment]
Reported in 2132660-t

**Comment by georgestephanis** [comment]
Is possible, hover over stats header in the widget.
