### ISSUE TITLE
Clients asking for alternative social media posting. 

### ISSUE THREAD

**Issue by jefferisp7** [Automattic/jetpack#18301]
Many of my clients are now asking for the ability to auto-post from WP not only to facebook but now to alternative social media as they are upset by the censorship going on by the big three. 

They would like posting options to parler.com, gab.com, mewe.com, clouthub.com, and  telegram as alternatives. The clients seem to be abandoning the big three in droves, and/or they do not want to support them.   

For me personally, I'm finding Facebook's latest update terribly junking looking and they never seem to have improved the navigation issues, esp. for managing multiple accounts.  I'm getting kind of tired of them and they aren't has productive for businesses I manage as they used to be.

**Comment by jeherve** [comment]
Thanks for the report. This has come up in the past:
- #17787 
- #16347 
- #11393 

If some of those Social Networks grow to be more popular all around the world, we'll consider adding them as a new option to our Publicize feature. 

For that to happen, however, those services will need to offer a public and documented API that we could rely on. As far as I can tell, none of those services offer an API yet, so integrations are not yet possible.

I'll close this issue for now; we can reopen it in the future if the situation changes.
