### ISSUE TITLE
Protect: Add link to IPv6 range calculator?

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#1835]
IPv6 formatting is hard. We should consider adding a link to a range calculator (like [this one](https://www.ultratools.com/tools/ipv6CIDRToRangeResult?ipAddress=2001%3A980%3A5686%3A1%3A%3A%2F64)) to the Protect configuration page:

![screen shot 2015-03-21 at 10 55 08 am](https://cloud.githubusercontent.com/assets/5512652/6765494/c179699c-cfb8-11e4-93d0-55e71f37dcdd.png)

Requested in 2131883-t.

Thoughts?

**Comment by samhotchkiss** [comment]
I'm not strongly pro or con, but I do lean very slightly on the con side...

Open to other opinions...

**Comment by samhotchkiss** [comment]
Closing for now, if more requests come in, we can reconsider.
