### ISSUE TITLE
Jetpack Fatal Errors

### ISSUE THREAD

**Issue by lkwdwrd** [Automattic/jetpack#1838]
Something in the most recent update caused my site to start fataling. I'm getting the following

```
hhvm: 
Fatal error: Uncaught exception 'BadMethodCallException' with message 'Call to a member function stat() on a non-object (NULL)' in /var/www/wdwrdfam.com/htdocs/wp-content/plugins/jetpack/class.jetpack-heartbeat.php:85
Stack trace:
#0 /var/www/wdwrdfam.com/htdocs/wp-includes/plugin.php(546): Jetpack_Heartbeat->cron_exec()
#1 /var/www/wdwrdfam.com/htdocs/wp-cron.php(100): do_action_ref_array()
#2 {main}
```

Running on php-fpm results in a bad gateway error.

**Comment by kraftbj** [comment]
Can you confirm which version of Jetpack you're running and what line 85 of class.jetpack-heartbeat.php has?

Looking in the tagged 3.4.1, L85 is blank: https://plugins.trac.wordpress.org/browser/jetpack/tags/3.4.1/class.jetpack-heartbeat.php#L85 so would like to make sure we're looking at the same thing. We've seen in a couple cases where a server would retain an older version of a particular file cached and execute improperly.

**Comment by kraftbj** [comment]
@lkwdwrd Checking in again on these details.

**Comment by lkwdwrd** [comment]
Thanks @kraftbj It was running 3.0, so there was probably an issue there, sorry. I've had an issue with two of my sites, though, where I activate jetpack and nginx starts throwing 502s, which is why I was trolling the logs a bit for jetpack errors. I have a couple of small sites co-located on the server. Everythign starts working again when I comment out the the auto-updates module.

https://github.com/Automattic/jetpack/blob/master/jetpack.php#L50

I'll let you know if I find more, but will open another ticket at that time.
