### ISSUE TITLE
Admin Page: i18n error, strings in _n() must include a number

### ISSUE THREAD

**Issue by tobifjellner** [Automattic/jetpack#18391]
While checking pending translations, I stumbled upon a place in Jetpack where _n() is used incorrectly. The platform translate.wordpress.org links to https://plugins.trac.wordpress.org/browser/jetpack/tags/9.3.1/_inc/build/admin.js#L59 but right now plugin trac seems a bit slow and I get timeout when I want to grab a code sample.

The problematic string is like this:

Singular:
The Jetpack Connection is also used by another plugin, and it will lose connection.
Plural:
The Jetpack Connection is also used by other plugins, and they will lose connection.

_n() is the wrong tool to distinguish between singular and plural. It should ONLY be used when the "steering" number is included in the string.
Although it nicely takes a singular and a plural string as arguments, various languages may actually need to provide a different number of translated strings. For instance, there are languages that CAN translate singular and plural differently, but where the word forms won't change at all for various numbers in the string – so they'll provide only one translated string for a _n().

Russian translations provide at least three translations on a _n(). The singular form is used wherever the word "one" is pronounced at the end of the number (1, 21, 31, 41, 51..., 101, 121, 131...). Then they use a special form of word ("dual") for numbers that end in a pronounced 2, 3, or 4 (2, 3, 4, 22, 23, 24, 32, 33, 34...). 

You can fix this in two ways.
1. If you know the number of conflicting plugins, just include it in the string:
The Jetpack Connection is also used by &d other plugin, and it will lose connection./The Jetpack Connection is also used by &d other plugins, and they will lose connection.
2. if you don't want/or can't show the specific number, use normal logic to distinguish between "1" and ">1" and use two discrete strings instead.

You may have the same problem in more places. I just found this occurrence and decided to let you know.
If you have any additional questions, feel free to contact me via Slack "Making WordPress", either in channel "polyglots" or me directly, my username is tobifjellner there, as well.

**Comment by jeherve** [comment]
Good point, we'll get this fixed.
