### ISSUE TITLE
Upgrade to 3.4.1 throws undefined wp_get_current_user() fatal error

### ISSUE THREAD

**Issue by EvanHerman** [Automattic/jetpack#1839]
After upgrading to 3.4.1 yesterday, I can no longer access the front end of my site. It throws a fatal error : 
```php
Fatal error: Call to undefined function wp_get_current_user() in /home/content/p3nexnas05_data01/16/2107516/html/wp-includes/capabilities.php on line 1356
```

I've seen a thread or two pop up in the wordpress.org forums, but not in the jetpack support forum specifically or here on github.

reference: https://wordpress.org/support/topic/jetpack-34-breaks-site

Only solution I've found is to temporarily deactivate Jetpack.

Evan

**Comment by kraftbj** [comment]
Evan—would it be possible to get a stack trace of that error? I haven't been able to duplicate this on my end.

If not, could you include additional details on your site—what version of WP are you running, what modules of Jetpack did you have active, etc?

Thanks!

**Comment by chaselivingston** [comment]
Also reported in 2132721-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/update-caused-white-page-of-death?replies=3&view=all

**Comment by kadimi** [comment]
@kraftbj 

Maybe this could help

- WordPress 4.1.1
- PHP 5.4
- Jetpack 3.4.1 with all modules deactivated

This happens on my server, I'll migrate to my computer to produce a backtrace.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/white-screen-of-death-after-updated?replies=30&view=all#post-6777249

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/fatal-error-call-to-undefined-function-72?replies=1&view=all

**Comment by richardmtl** [comment]
Alsi on 2152040-t

**Comment by kraftbj** [comment]
Possibly related from 2143903 -- Another plugin had `set_site_transient( 'update_plugins', null );` which would fire off our filter attached to that, early, before pluggable.php was loaded.

**Comment by samhotchkiss** [comment]
Oy-- do we have any way of knowing where this is coming from, so we can stop the carnage?

**Comment by EvanHerman** [comment]
After some extensive testing I've tracked the issue back to one of my premium plugins. I am hosting the plugin on my personal site and push out updates from there. Within my plugin I have included a third party class file for auto updates from my external repo.

I was requiring this class file too soon, before most of WordPress core files were loaded. Inside of the external updater wp_get_current_user() was being called, and since the function didn't exist the error was thrown and execution was killed off.

Glad I finally got things resolved and cleared up for my users. It's possible a lot of the users reporting this issue have similar problems with a plugin running alongside Jetpack. 

I'm not sure If I should close this issue since I have it resolved but others have reported the same error.

Evan

**Comment by kraftbj** [comment]
Thanks for the additional details, Evan. We'll leave this open for the moment to see if there is a way we can handle it better.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/too-heavy?replies=1&view=all

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/fatal-error-function-wp_get_current_user

**Comment by dereksmart** [comment]
No reports of this in months, and we're now on 3.6.  Please reopen if it comes back.
