### ISSUE TITLE
Beta Plugin: Add way to refresh update_plugins transient

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#18409]
We use the update_plugins transient to store update information, so we can likely refresh it via the Core Updates page. That's not obvious and requires a few different clicks. We should add a button to the Jetpack Beta page to refresh.

This would help when we're releasing commits to a beta branch so sites waiting for the next commit can get offered it on demand without needing to flip around within wp-admin.

**Comment by sdixon194** [comment]
Spent a good time on this one today, but can't reproduce reliably enough to see this being an issue for now. The update nudge appears fairly consistently on the beta page itself without having to check on the core page first. Just a refresh after the branch builds nudges me:

![Screen Shot on 2021-02-01 at 15_44_02](https://user-images.githubusercontent.com/33553323/106524441-944c9280-64b0-11eb-9241-c64d6abbecb6.png)


Closing for now, but if this becomes more of a noticeable issue, reopen for further investigation!
