### ISSUE TITLE
Newsletter Block: Styling discrepancy between the editor and front end

### ISSUE THREAD

**Issue by danieldudzic** [Automattic/jetpack#18404]
#### Steps to reproduce the issue

1. Activate the Seedlet theme
2. On a site with Jetpack enabled, add a Newsletter Sign-up block to a post.
3. See that the disclaimer text is small and a regular font weight.
4. Preview your post.
5. See that the disclaimer text is larger and bold.

In the editor, the Jetpack newsletter signup block disclaimer looks like this:
![104492553-d36a8080-55a1-11eb-8b8b-8ab6bd7d9e0e](https://user-images.githubusercontent.com/905781/104972421-fe196680-59f1-11eb-8200-872c9998d64e.png)

While on the front-end, it looks like this:
![104492588-e2e9c980-55a1-11eb-893a-8a1ea8fb6c56](https://user-images.githubusercontent.com/905781/104972436-0b365580-59f2-11eb-8bad-03c10c52f8df.png)

-----

I have done some investigating and found out that, Jetpack:

- Loads the [editor-ui.css](https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/modules/contact-form/css/editor-ui.css) file in the editor
- Loads the [grunion.css](https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/modules/contact-form/css/grunion.css) file on the frontend

The styling (in `grunion.css`) "causing" the issue is:
```
.contact-form label {
    margin-bottom: 0.25em;
    float: none;
    font-weight: bold;
    display: block;
}
```
Since the code in `grunion.css`, styles Contact Form labels in a specific way - I'm assuming this is the correct styling.

The solution isn't for me clear here.

Should `grunion.css` be also loaded in the editor? Or should we copy over (a part of) the code to `editor-ui.css` to fix the issue?

In addition to the above, the selector used in `grunion.css`, `.contact-form` is not present in the editor. Making it work would require changing the selector in css or adding an extra class in the Contact Form block editor markup.

**Comment by jeherve** [comment]
> Loads the grunion.css file on the frontend

This only happens if there is a contact form to display on the page, though.

Ideally our contact form CSS wouldn't be that specific: #5876 

I don't really understand how that CSS impacts the Newsletter block description though. In my test this is a `p` tag, and the `.contact-form` class is nowhere to be found on the page. Could you give me more details on how to reproduce, or maybe link to a page where you see this happening?

Thank you!

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
