### ISSUE TITLE
Beta Plugin: Warning in Jetpack beta admin page when switching to bleeding edge

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#18411]
![image](https://user-images.githubusercontent.com/746152/51861557-56459280-231b-11e9-83e3-3acb4d2d9eaa.png)

The message is:
> Notice: Undefined property: stdClass::$files in wp-content/plugins/jetpack-beta/jetpack-beta.php on line 947

**Comment by sdixon194** [comment]
This one doesn't seem to be reproducible anymore. Going to close for now and if it becomes an issue again, re-open.
