### ISSUE TITLE
Beta Plugin: Monitor how many sites use the Beta Plugin

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#18417]
Maybe related to Automattic/jetpack-beta#77, we need a reliable way to determine how many sites (and which ones) are running the Beta plugin. 

We should filter out: 
- JN sites
- a8c people

**Comment by kraftbj** [comment]
@dereksmart Would this already be possible? Do we need to keep this as an outstanding issue?

**Comment by dereksmart** [comment]
This can be closed. There are now two filters in the Site Profiler that will allow us to get this info 

![image](https://user-images.githubusercontent.com/7129409/105044171-6b4deb80-5a34-11eb-82a3-561f53d68e82.png)

![image](https://user-images.githubusercontent.com/7129409/105044188-7b65cb00-5a34-11eb-8631-30bb3dc1de12.png)
