### ISSUE TITLE
Beta Plugin: "To Test" doesn't show the first time Bleeding Edge is activated

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#18426]
Steps to reproduce:

1. deactivate and activate Jetpack Beta Tester
2. click "Let's get testing!" link
3. click Bleeding Edge button

What I expected:

Jetpack's to-test.md text to be shown

What happened instead:

No text was shown.

### Notes
- It only happens the first time. If after activating Bleeding Edge the first time you activate Release Candidate and then Bleeding Edge again, the text will show.
- Only Bleeding Edge has this issue. If Release Candidate is activated, the text will show.
- If after activating Bleeding Edge the first time, the page is reloaded, the text will show.

**Comment by sdixon194** [comment]
Tried in a few different environments but wasn't able to reproduce this one - to-test.md loads on first activation for me. This request seems a bit old, but @eliorivero are you able to still reproduce this one and have more info on your testing environment?
