### ISSUE TITLE
Update wording for Latest Stable and Release Candidate

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#18421]
Currently the **Latest Stable** text is confusing because it actually means "Whatever version you had installed on your site before playing around with Jetpack Beta settings".

This is a screenshot of a site with Jetpack 6.2.1 installed but at a time where the very latest Stable is Jetpack 6.3.2.

![image](https://user-images.githubusercontent.com/746152/42289456-ff164eba-7f95-11e8-8eaa-ce5133f0b96a.png)

**Comment by sdixon194** [comment]
>This is a screenshot of a site with Jetpack 6.2.1 installed but at a time where the very latest Stable is Jetpack 6.3.2

Is this more a of a bug with the plugin not prompting an update to the latest stable version? Or are there cases where you'd have a previous version of Jetpack installed and we wouldn't expect the prompt to update

**Comment by oskosk** [comment]
I have no idea of what I wanted, closing
