### ISSUE TITLE
Protect: WP.com should have global whitelist

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#1842]
With the to-be-launched Security tab, I have to add my IP to the whitelist on every single site, either via /wp-admin/ or wp.com/settings/security/[url]. It would be nice to have a field at wp.com/settings/security/ to "These IPs should be whitelisted on all my JP sites".

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/jetpack-protect-how-to-define-whitelist-ips-network-wide-on-multisite?replies=3&view=all#post-6734232

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/jetpack-protect-and-wordpress-multisite?replies=1&view=all

**Comment by samhotchkiss** [comment]
This has been discussed, I think @roccotripaldi was looking at it previously

**Comment by roccotripaldi** [comment]
We've discussed this a little bit. There is currently not a way to manage any settings on a global level on wordpress.com - It may be awhile before we see it. I'll bring it up again at today's meeting. I think 3.5 is still a fair milestone estimate.

@jeherve : it may be worth noting on this ticket ( https://wordpress.org/support/topic/jetpack-protect-how-to-define-whitelist-ips-network-wide-on-multisite?replies=3&view=all#post-6734232 ) that you do not need to whitelist each site individually in a multi-site network.  the whitelist is saved as a `site_option`, so if you whitelist an IP address on site 1, it will also be whitelisted on site 2.

**Comment by jeherve** [comment]
> if you whitelist an IP address on site 1, it will also be whitelisted on site 2.

Good to know, thank you!

**Comment by jenhooks** [comment]
Would be useful here: 2229200-t.

**Comment by lezama** [comment]
😛

**Comment by brbrr** [comment]
Its already implemented in WP.com settings

**Comment by kraftbj** [comment]
@brbrr I'm fine closing this issue, but where is the setting? I didn't realize we had one for a global whitelist.

**Comment by brbrr** [comment]
Maybe I mixed up something, but this is the menu I was referring to: 

![screen shot on 2018-07-20 at 08 59 07](https://user-images.githubusercontent.com/5654161/42985689-3ecbc136-8bfb-11e8-94d0-c1c890f8796d.png)
