### ISSUE TITLE
Subscriptions: Restore option to display subscriber count

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#1843]
3.4 changed the way subscriber widget displays sub count (previously include it via an option vs now requiring user to add a quasi-shortcode)

Generating a solid amount of user pushback.

Related: #1556, #1527, 4ca209da5c8dd544981bd7129f3592f5e3de34ae, 5e9e97b0e4f17588cbb1a9d6cf9f0e1730ca3db8

**Comment by kraftbj** [comment]
Idea: If option from former versions is present (if we still have that in the db), add predefined text. Still allows editing and new users could follow new way.

**Comment by aheckler** [comment]
A couple I'm handling right now:

- 2133801-t
- 2132786-t

There were more over the last few days, but they're somewhere in my closed tickets and I can't find them now.

**Comment by kraftbj** [comment]
Another idea: If the show count option is in the db to show subs number and the text matches the default, save the widget instance again dropping the show count option and saving the previously used text.

**Comment by mikeyarce** [comment]
Another report: 2148736-t

**Comment by jeherve** [comment]
@dereksmart I can't seem to be able to get the old option to appear on my test site, even with a new widget, and after hitting save and reloading the page.

The widget shows the text:
![screen shot 2015-04-24 at 12 19 55 pm](https://cloud.githubusercontent.com/assets/426388/7317017/3cade4e8-ea7c-11e4-9598-e0f20130f00b.png)

But I have no option to remove that text in the widget settings:
![screen shot 2015-04-24 at 12 20 08 pm](https://cloud.githubusercontent.com/assets/426388/7317025/4b58b400-ea7c-11e4-9d61-6338b6e9d8a5.png)

Also reported here:
https://wordpress.org/support/topic/blog-subscriptions-widget-total-subscribers-toggle-removed?replies=1&view=all

What would be the work-around?

**Comment by chaselivingston** [comment]
Also reported in 2169629-t

**Comment by dereksmart** [comment]
@jeherve submitted a patch for this already, but in the meantime if anyone has this problem, clearing out  any instance of the widget in the "inactive widgets" will resolve this.

**Comment by jenhooks** [comment]
2170882-t
2171064-t
