### ISSUE TITLE
I can't assign one single task to multiple user

### ISSUE THREAD

**Issue by nishaspec** [Automattic/jetpack#18445]
hii,
i am using jetpack CRM on my WordPress website. i want to assign one single task to multiple users. is there any addon to assign tasks for multiple users? or is there any way to make custom code for multiple users on a theme?

Plz, help me to solve this issue because I am badly stuck on my site.

Thanks.

**Comment by jeherve** [comment]
Thank you for the report!

Could you contact us via [this URL](https://kb.jetpackcrm.com/submit-a-ticket/) to give us more information about your site and about the issue? 

Thank you.
