### ISSUE TITLE
Module idea: SMTP Relay Service

### ISSUE THREAD

**Issue by pmgarman** [Automattic/jetpack#1845]
Email deliverability is a thing, most WordPress site owners just do not know that it is a thing. Emails "just work" and their WordPress site sends emails from their cPanel hosts just fine... BUT sometimes it needs a little help. Not to mention the number of sites going to "the cloud" (read: any sort of virtual machine) ... but sending emails from any sort of virtualized network is generally not great ([one of many sources](https://documentation.mailgun.com/best_practices.html#hosting))

This usually requires setting up an account with an SMTP relay (which usually a user knows nothing about), then getting that services plugin setup on the site, then getting API keys or SMTP credentials configured.... all while trying to explain sending email through a Gmail account's SMTP is not a great idea. (Or at least that's my regular interaction with it and helping someone get their emails sending better through WordPress)

Jetpack offers some pretty powerful features that a user can enable at a simple click of the mouse: Photon and Subscriptions are two huge time savers to name just a few that don't require any real work (or technical knowledge) from the end user but to setup any other way would.. and these are free. While most WordPress sites would probably fit right into a free plan (many SMTP services offer a few thousand emails a month) some sites need higher volume and may need bigger plan. VaultPress already set's a precedent for having a paid service included in Jetpack. It also is a simple service that enables any WordPress user to have automagical backups of their site.

So what do you think, SMTP relay service a possibility for a future version of Jetpack? :) Not a small task but would be an awesome resource.

**Comment by jeherve** [comment]
Jetpack already uses WordPress.com mail servers for most of the features that require emails, with the exception of the emails generated by contact form submissions. I think we'd rather start using WordPress.com mail servers for that too, instead of adding a new module.

But we'll consider your idea!

**Comment by pmgarman** [comment]
Yeah figured wordpress.com had a smtp service of some sort that already powers millions of sites, so tapping into that to give any Jetpack user the ability to send reliable emails would be awesome.

**Comment by jeherve** [comment]
Closing this as `wontfix` for now, as there haven't been any other requests for a similar service.

We'll reopen if we get other requests.

Thanks for the feedback!
