### ISSUE TITLE
Error on plugin activate immediately after install

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#1846]
https://cloudup.com/c0qW91ox_Q9

Redirecting back to reinstall the plugin after it's already been installed

**Comment by lkwdwrd** [comment]
I've been having similar issues on a couple of my sites. Both https://lkwdwrd.com and another non-public site.

I got both working again after commenting out the include of the auto-updates module: https://github.com/Automattic/jetpack/blob/master/jetpack.php#L50

Haven't dug in deeply to see why this caused nginx to start throwing 502s, but they are both at least operational again.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/jetpack-installactivation-issue?replies=3&view=all

**Comment by samhotchkiss** [comment]
Looks like this IS resolved by #1984
