### ISSUE TITLE
Feature request: Floating page-based social sharing sidebar/widget

### ISSUE THREAD

**Issue by galbaras** [Automattic/jetpack#1848]
Floating social sharing sidebars are quite common nowadays and encourage visitors to share the page they're on by having the sharing buttons visible to them all the time. It would be a great addition to Jetpack to have something like this.

Styling can be easily "borrowed" from other plugins (a quick Google image search for "floating social sidebar" shows many great options). However, the main points of styling are keeping the floater visible as much as possible and "unfloating" it to the bottom of the page content when the viewport is too narrow.

A function like this cannot rely on a post object to be available on archive pages. The current "sharing_display" function creates buttons for the last post listed on the page, but on archive pages, the sidebar should share the page, not one of the posts. This means that to enable a floating sidebar, "sharing_display" and the respective sharing services must be extended to allow sharing of archive pages (including the default index page, where is_home() == true).

Once page-based sharing is an option, Jetpack can also be extended with a sharing widget, which can be added to a normal sidebar. In fact, the floating element can be based on a custom sidebar, which displays the new widget, while making the widget available to be placed elsewhere as well.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
