### ISSUE TITLE
Devicepx: add it as a module or a theme tool to avoid confusion

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1850]
Right now, `devicepx-jetpack.js` is enqueued on your site as soon as you activate Jetpack, and even before you connect your site to your WordPress.com account. There is no mention of it anywhere in the Jetpack menu, and no way to deactivate it without code.

It would be nice to offer an option to disable it from the dashboard, or add it as a theme tool via `add_theme_support()` so it's not on by default without any mechanism to turn it off.

Suggested here:
https://wordpress.org/support/topic/jetpack-postinf-to-social-profiles-without-permission?replies=3&view=all#post-6733290

**Comment by jeherve** [comment]
Related: #804

**Comment by georgestephanis** [comment]
Honestly, I really want to just drop devicepx entirely, we just need to get browser native support up first.

**Comment by lumpysimon** [comment]
I'm running a high traffic site with only the Protect module activated. We're keen to minimise requests and pageload time, but the devicepx script is loading. This seems completely redundant, as far as I can tell this script is only related to images, nothing at all to do with the Protect module.

**Comment by Technowix** [comment]
Any new on disabling this thing ?

**Comment by jeherve** [comment]
@Technowix No news, but we'll update this issue when we make progress on this.

In the meantime, you can use the following snippet to disable it on your site:

```php
function jeherve_dequeue_devicepx() {
    wp_dequeue_script( 'devicepx' );
}
add_action( 'wp_enqueue_scripts', 'jeherve_dequeue_devicepx' );
```

**Comment by Technowix** [comment]
Thanks for reply @jeherve , where did I put this little snippet ?

**Comment by jeherve** [comment]
You can paste this in your theme's functions.php file, or in a <a href="https://wordpress.org/plugins/code-snippets/">functionality plugin</a>

**Comment by webdados** [comment]
So... nothing new on this?

**Comment by Technowix** [comment]
Beside having to hack things... Nuh

**Comment by webdados** [comment]
@Technowix Surprise, surprise
