### ISSUE TITLE
Error when Following Link to Blog Followers in WP Admin Site Stats

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/jetpack#18528]
#### Steps to reproduce the issue

1. Go to Jetpack → Site Stats
2. Click on Blog link in the Subscriptions box. 
![Screen Shot on 2021-01-25 at 12-33-19](https://user-images.githubusercontent.com/22805865/105743101-4eb92400-5f0a-11eb-8b7e-6e24d8cdeb89.png)
Note that the link is YOURSITEURL/wp-admin/admin.php?page=stats&blog_subscribers
3. See error message "We were unable to get your stats just now. Please reload this page to try again."

![Screen Shot on 2021-01-25 at 12-34-35](https://user-images.githubusercontent.com/22805865/105742916-14e81d80-5f0a-11eb-886b-aa2f177602ea.png)

Repeat the process for the Comments link and get the same outcome.

#### What I expected

To see my blog subscribers and my comment subscribers. 

#### What happened instead

I got that error. 

We should replace those links with the corresponding to the follower stats in the WordPress.com dashboard.

Reported in 3674093-zen

**Comment by jeherve** [comment]
cc @leogermani Do you think this could be caused by #16727 and #16716? Those links used to work in the past, and I wonder if those changes may have broken this.

**Comment by jeherve** [comment]
Also in 3678913-zen

**Comment by jeherve** [comment]
Also in 3678175-zen

**Comment by adviceineeded** [comment]
Thanks for posting @tmmbecker I am also having this issue and not sure how to fix.

**Comment by StefMattana** [comment]
Possibly affecting also [this user in the JP forum](https://wordpress.org/support/topic/cant-see-email-followers-blog-subscribers/).

**Comment by kbrown9** [comment]
I've been able to reproduce this and confirmed that switching from the blog token to the user token resolves the problem. We might need to consider switching back to the user token for these requests until we're able to fix the wpcom side to handle blog tokens.

**Comment by leogermani** [comment]
Hi, sorry I missed the ping, thanks to Kim for bringing this to my attention.

I think it's better if we fix it on WPCOM side:

* Will not require a plugin update
* Will be consistent with the rest of the Stats feature

The blog token is used for all requests in the Stats feature, and we would have to add a conditional for these requests. I don't think we need that.

For some reason, these endpoints have an additional check that was breaking for requests authenticated with the blog token. I've worked on a fix but I need a second pair of eyes to look at it and see the safer way of fixing the issue. Here's the fix:

D56206-code

We will update this issue as soon as we manage to fix it.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/follower-subscriptions-unable-to-be-loaded/

**Comment by tmmbecker** [comment]
3689865-zen

**Comment by brucea8c** [comment]
The user from 3678913-zen is asking for an update on this.

**Comment by leogermani** [comment]
The fix is ready to be deployed. I think it's safe to say this will be fixed on Monday.

**Comment by leogermani** [comment]
The fix is now deployed. The Subscribers lists should be working now!

r220672-wpcom

**Comment by tmmbecker** [comment]
I confirmed that this works for me now. Thank you @leogermani!
