### ISSUE TITLE
Premium Content Block: padding issues in 

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#18522]
#### Steps to reproduce the issue

1. Start on a free WordPress.com Simple site running the latest iterations on the Premium Content block and upgrade nudges (see D53531-code and related diffs).
2. Insert a Premium Content Block.
3. Inside the block, you'll notice that the upgrade nudge misses some padding:

![](https://user-images.githubusercontent.com/426388/105509366-b59dc980-5ccd-11eb-8fb1-aa929d6c5af7.png)

**Comment by Copons** [comment]
Closing because not reproducible anymore. ✨
