### ISSUE TITLE
Premium Content Block: default Payment plan does not exist when you first add a block

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#18521]
#### Steps to reproduce the issue

1. Start with a site running `master`, and connected to WordPress.com.
2. Purchase a plan giving you access to the Premium Content block (e.g. Complete).
3. Add the block to a new post.
4. Follow the prompt to connect your site to Stripe.
5. Once back in the editor, publish your post.
6. You will not see a payment button on the frontend, only in the editor.
7. Add a separate Payment button outside of the Premium Content block, create a new Payment plan inside the Payment block controls, and update the post.
8. Now that a Payment plan exists, the Payment button can appear on the frontend, both in the Premium Content block and in the separate Payment block.

**Comment by stacimc** [comment]
@jeherve Any chance you had the store sandboxed when you first connected to Stripe?

I followed the steps above (while sandboxing the api and my site but not the store) and was unable to reproduce this -- the $5/month default plan was added and selected by default, and the Subscribe button appeared in the published post.

The only way I was able to reproduce this was by sandboxing the store. When I connected to Stripe with the store sandboxed, there was an error creating the plan, resulting in the misconfiguration and the missing button. I wasn't able to create new payment plans at all until un-sandboxing the store though, so there may be something different in our environments.

**Comment by jeherve** [comment]
I wasn't Store sandboxed, no. 

I was testing with a brand new site, freshly connected to WordPress.com, if that matters?

**Comment by apeatling** [comment]
@jeherve Did you test this on a Jetpack site? Your testing instructions including purchasing a Jetpack plan indicate you did. I'm wondering how, because the block is disabled if not running on a WordPress.com or Atomic site?

**Comment by jeherve** [comment]
Yes, this was on a Jetpack site. 

> I'm wondering how, because the block is disabled if not running on a WordPress.com or Atomic site?

The block is available when Beta or experimental blocks are enabled on the site. That's how I was testing.

**Comment by Copons** [comment]
@jeherve I'm trying to repro this issue on a JN running JP Bleeding Edge, connected to WPCOM, and with a Complete plan.
I don't see the Premium Content block though.

Looking at the registration code, it really, really, shouldn't be registered outside of WPCOM. 🤔 

https://github.com/Automattic/jetpack/blob/2bc858a2c6220af1fe606b06ef1d4cea7b6f2256/projects/plugins/jetpack/extensions/blocks/premium-content/premium-content.php#L29

Would you mind double-checking if this is still happening?

**Comment by jeherve** [comment]
> Looking at the registration code, it really, really, shouldn't be registered outside of WPCOM. 🤔

Yes you're right. Maybe we should add an additional gate, something like #22712?
