### ISSUE TITLE
Anchor.fm: error message when episode isn't available

### ISSUE THREAD

**Issue by creativecoder** [Automattic/jetpack#18541]
#### Is your feature request related to a problem? Please describe.

When a new podcast episode post is created as part of the Anchor.fm flow, if the podcast episode was just published, there may be a caching delay before the episode actually shows up in the feed. This results in a blank episode post.

#### Describe the solution you'd like

If the podcast show is valid, but the supplied episode id is not in the feed, show an error notice at the top of the editor that says

> We couldn’t find that episode in your feed. If you just published the episode, please try creating the post again in a few minutes. Retry

"Retry" should be a link to create the post again, using the podcast information

#### Describe alternatives you've considered

I'm open to other ideas!

#### Additional context

paYJgx-1co-p2

**Comment by creativecoder** [comment]
Notes from discussion:

Should Anchor provide a title in the query string, so we could at least use that for the post?

Let's also add a retry link in the notice, so users can easily try again.

**Comment by kwight** [comment]
> Should Anchor provide a title in the query string, so we could at least use that for the post?

I'd tend to avoid new parameters at this point – if we're not in a working state, I'm not sure seeing a title would help anything.
