### ISSUE TITLE
[Feature Request] Automatically add content I want after all posts and pages

### ISSUE THREAD

**Issue by ricjcs** [Automattic/jetpack#18559]
Below the posts and pages the Jetpack automatically adds elements such as: advertisements, sharing buttons and related posts.

I wish it was possible to have a space bellow the posts and pages that I could customize and turn on or off. I could add blocks that would be available in all posts and pages, as with the Jetpack elements I mentioned above.

This feature would be very useful for example to subscribe to a newsletter and consequently increase the list of leads, to publicize an event, to request a donation, and various other purposes that are in line with the scope of the Jetpack.

There are alternatives such as creating a reusable block, but it is not practical when you have hundreds of posts and you want the block to appear in all of them. It is also possible to use the sidebar but it is not the best option for the intended one. There are also plugins for Wordpress, but I am a wordpress.com customer without access to plugins.

I created mockups with a design proposal.

**Mockup 1**
In this proposal the space is customizable through the block editor. The link to access this feature comes in the left sidebar in the Jetpack menu. On the left side we can turn this feature on or off for posts and pages (all or individually). In the center we can add and edit the desired blocks, which will come under the posts and pages. In the image there is only an example of blocks added, the user can add anything he wants.

![Mockup1_Special Space](https://user-images.githubusercontent.com/11923491/105997606-b8206a80-60a3-11eb-94c5-69aa11b56873.jpg)

**Mockup 2**
This is a simplified proposal. Only the code that will generate what the visitor will see is added. And you will also have buttons to turn on and off for posts and pages (all or individually). An even simpler proposal would only turn on or off the feature for all posts and pages.

![Mockup2_Special Space](https://user-images.githubusercontent.com/11923491/105997646-c2426900-60a3-11eb-960e-a9c218f6f97b.jpg)

**Mockup 3**
This is the final result that the visitor will see on the website.

![Mockup3_Special Space](https://user-images.githubusercontent.com/11923491/105991824-2d883d00-609c-11eb-9399-15fe031a8c61.jpg)

**Mockup 4**
In a comment below, I added another design proposal to configure the content shown after all the posts and pages, which I think is better and easier to implement.

**Comment by jeherve** [comment]
I like the idea, but part of me wonders if this wouldn't be better implemented in Core. There are after all many other plugins that hook into `the_content` to display information below the post content. 

In an ideal scenario, I think Core could display a list of everything that's hooked into the content for a given post, and give the author the option to disable it for that specific post.

I realize that's a much bigger undertaking in Core, though, since it would first require figuring out when something hooked into `the_content` is actually something displayed below posts, and not just manipulation of the content.

As for Jetpack, we do some of this already, in the Jetpack sidebar:

![image](https://user-images.githubusercontent.com/426388/106029866-d4d19800-60cd-11eb-9c70-16c3c32a88a7.png)

I'll leave this issue opened, as we could expand this to also include Related Posts and Ads.

**Comment by ricjcs** [comment]
Hi @jeherve, 

Thank you for your reply.

But I think you did not understand my idea well. It seems to me that the new title does not express my idea well or else I didn't understand the title. Could you check if this is the best title? My English is also not the best...

The idea is that I create a certain content, and that content will be below all posts and pages.

I think that if, for example, I insert the html code of a block or something in functions.php in a certain place, it will be available in all posts and pages. That's the idea, but with a graphical interface to edit.

In the mockup I used the image of editor, but it is not about editing a post or page, it is just to edit the content that will automatically be in all posts or pages. In the case of the pages I just thought that I could have the alternative of choosing which pages this content appeared on.

Automatically placing content under all posts is very used and useful for subscribing to newsletters and generating leads, requests for donations, etc. And now with so many useful blocks, this feature would be great.

I think it is within the purpose of JetPack, which is to grow the site, monetize, among others. For worpress.com premium users like me, you can't install a plugin or edit functions.php. But this is a feature that I think would enrich Jetpack. And it doesn't seem like a complicated thing to implement.

I don't know if the core would implement the idea...

**Comment by jeherve** [comment]
Oh, I see. I indeed misunderstood. I still think we could add toggles for Jetpack's own features, though. :) 

> if, for example, I insert the html code of a block or something in functions.php in a certain place, it will be available in all posts and pages. That's the idea, but with a graphical interface to edit.
> [...]
> it is just to edit the content that will automatically be in all posts or pages.

I think that's a problem that Full Site Editing will solve for everyone. It allows you to create templates of blocks and use those templates on multiple pages. That should be just what you need.

You can read more about Full Site Editing here for example:
https://wptavern.com/what-is-full-site-editing-and-what-does-it-mean-for-the-future-of-wordpress

**Comment by ricjcs** [comment]
One more thing, this configuration is not to be made in the editor where I am editing a post or a page.

**Comment by ricjcs** [comment]
Take this page as an example:
[https://www.lionsroar.com/yes-we-can-have-hope/]()

At the end of the post is a message with a donation button. This appears on all posts and pages.

The idea is that JetPack has a feature that allows me to choose the blocks I want to appear in all posts and pages.

**Comment by ricjcs** [comment]
> I think that's a problem that Full Site Editing will solve for everyone. It allows you to create templates of blocks and use those templates on multiple pages. That should be just what you need.

But the idea I say is for any type of website. Whatever template I have, it will work. I don't need to do the full editing. It's even simpler, as long as that option exists.

JetPack already puts things after all the posts and pages, just allow me to add what I want. For some situations it is very useful.

@jeherve  I changed the title to something more appropriate. Do you think it looks better this way?

**Comment by ricjcs** [comment]
Another mockup for the configuration. I think that this way is even easier to implement. The configuration will be implemented on the panel with options "Marketing and Integrations" (Tools > Marketing). This space already exists, it would be to add this new option and configure what it does.

![Mockup4_Special Space](https://user-images.githubusercontent.com/11923491/106069008-93ef7880-60f9-11eb-826d-4ca0f921cd1e.jpg)

**Comment by jeherve** [comment]
> Jetpack already puts things after all the posts and pages, just allow me to add what I want. For some situations it is very useful.

I can see how useful this could be, but that is not something that's currently on Jetpack's roadmap. It's a feature, while useful, that will become less useful once FSE will be fully ready. It consequently makes it less interesting to develop today. It's also not something we could ever implement as is for WordPress.com simple sites, for the security reasons I mentioned earlier.


I'll close this issue as "Won't Fix", and we can defer to #18585 for the Related Posts and Ads options we discussed above.

Until then, and if one needs such a feature, I would recommend this plugin:
https://wordpress.org/plugins/insert-blocks-before-or-after-posts-content/

If you're currently using WordPress.com Premium, you will either need to update to a Business plan to use that plugin, or rely on Full Site Editing since WordPress.com already includes many features you can use.

**Comment by ricjcs** [comment]
OK! But I don't understand the security reasons. It is the same as editing a post. I can also take a "Custom html" widget and place it on the site sidebar. It is exactly the same thing, but in a different location.

**Comment by jeherve** [comment]
> I can also take a "Custom html" widget and place it on the site sidebar. It is exactly the same thing, but in a different location.

Yep, same thing. And it's fine as long as you try to insert HTML that's allowed. Anything that's not allowed (such as js, forms, or iFrames, things you'll typically find in elements one adds below the content) will be stripped.

**Comment by ricjcs** [comment]
> Yep, same thing. And it's fine as long as you try to insert HTML that's allowed. Anything that's not allowed (such as js, forms, or iFrames, things you'll typically find in elements one adds below the content) will be stripped.

Exactly, this is what would happen with the new feature if it were implemented. What you can insert is exactly what you can insert in a post or a widget. For security reasons it would not be a problem.
