### ISSUE TITLE
Dialogue block: fallback content

### ISSUE THREAD

**Issue by creativecoder** [Automattic/jetpack#18557]
The server-side code for rendering blocks is not executed in several contexts, including email notifications for posts, reader, and AMP pages.

Context: paYKcK-FI-p2

The dialogue block needs fallback content output from the `save` functions to cover rendering the blocks in these contexts.

**Comment by retrofox** [comment]
The `Conversation` block doesn't render on the server-side, so I think it should be handled only in the Dialogue block.

**Comment by creativecoder** [comment]
> The Conversation block doesn't render on the server-side, so I think it should be handled only in the Dialogue block.

Thanks @retrofox -- I updated the issue title and description to reflect this.

**Comment by creativecoder** [comment]
Draft PR at https://github.com/Automattic/jetpack/pull/18598
