### ISSUE TITLE
Autoupdates: Audit respect for the disabling filter/constant

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#18562]
When Core brought UI and handling for automatic plugin updates, we updated our code to use the same option so we could take advantage of Core's UI. Additionally, while our autoupdates are generally faster than Core's, we still use Core's as a fallback.

We need to audit the paths that an autoupdate happens to ensure we're respecting the various filter/constants provided by Core to disable it: https://wordpress.org/support/article/configuring-automatic-background-updates/

Some notes:
* If someone filters out particular plugins, what does the UI option look like for that in wp-admin? Calypso?
* If someone disables all updates, what does the Calypso UI look like?

See p1611759468252700-slack-CBG1CP4EN

**Comment by samiff** [comment]
Tested with a JN WP site with Jetpack active, that had some outdated plugins with updates available from WPorg.

* Using `define( 'AUTOMATIC_UPDATER_DISABLED', true );` ([docs](https://wordpress.org/support/article/configuring-automatic-background-updates/#constant-to-disable-all-updates))
  * Works as expected hiding `Enable auto-updates` in WP Admin for all plugins.
  * When JP is connected, the Calypso Plugin management screen `wordpress.com/plugins/manage/__SITE__` shows as expected with the disabled `Autoupdates` toggle for all plugins:

![1](https://user-images.githubusercontent.com/15803018/106090700-06eff380-60e8-11eb-9179-6b9fea52b7be.png)

* Using `add_filter( 'automatic_updater_disabled', '__return_true' );` ([docs](https://wordpress.org/support/article/configuring-automatic-background-updates/#disabling-all-updates-via-filter))
  * Works as expected hiding `Enable auto-updates` in WP Admin for all plugins.
  * However, the Calypso Plugin management screen does not have the `Autoupdates` toggle disabled.
  * From Calypso, was able to turn on `Autoupdates` for a plugin (which was immediately updated), and that plugin is added to the `auto_update_plugins` option.

![2](https://user-images.githubusercontent.com/15803018/106091725-3869be80-60ea-11eb-94cc-815057c76b0a.png)

If I turn back on `define( 'AUTOMATIC_UPDATER_DISABLED', true );` at this point, turning off the filter, Autoupdates are still enabled for the plugin. Rolling back the plugin works on the WP Admin side of things, but visiting the Calypso management screen triggers a successful plugin update.

* Using `add_filter( 'auto_update_plugin', '__return_false' );` ([docs](https://wordpress.org/support/article/configuring-automatic-background-updates/#plugin-theme-updates-via-filter))
  * Works as expected showing `Auto-updates disabled` in WP Admin for all plugins.
  * Same behavior as `add_filter( 'automatic_updater_disabled', '__return_true' );` in Calypso, the toggle switch works.

* And for filtering updates on specific plugins ([docs](https://wordpress.org/support/article/configuring-automatic-background-updates/#plugin-theme-updates-via-filter))
  * Works as expected in WP Admin, shows `Auto-updates disabled` next to the plugin I turned off updates for, even though it was in the `auto_update_plugins` option.
  * In Calypso, the filter was not being respected however, and toggle worked.

**My immediate takeaways are:**

1. The Calypso plugin management screens will always update any plugin set to automatically update (in `auto_update_plugins` option), regardless of whether a filter or constant is present to disable automatic updates.
2. `define( 'AUTOMATIC_UPDATER_DISABLED', true );` does disable the `Autoupdates` toggle in Calypso which is the expectation, but the filters do not it seems.

Next item I'll work on is verifying core behavior for `auto_update_plugins` when filters/constant have the updates disabled, and dig into how Jetpack/Calypso might affect that.

**Comment by kraftbj** [comment]
The constant works but not the filters. We may need to do something similar to https://github.com/Automattic/jetpack/blob/jetpack/branch-9.4/projects/plugins/jetpack/modules/publicize.php#L62-L97 in order to pass that filter value upstream.

**Comment by samiff** [comment]
On the WP core side of things:

* `define( 'AUTOMATIC_UPDATER_DISABLED', true );` 
* `add_filter( 'automatic_updater_disabled', '__return_true' );`
* `add_filter( 'auto_update_plugin', '__return_false' );`
  * or filtering specific plugins using the `auto_update_plugin` filter

All work to prevent automatic plugin updates from happening, even if a plugin is present in the `auto_update_plugins` option.

---

On the WordPress.com Calypso side of things, there are a few plugin management paths:

* https://wordpress.com/plugins/manage (all sites)
* https://wordpress.com/plugins/hello-dolly (single plugin)
* https://wordpress.com/plugins/manage/example.wordpress.org (single site)

In regards to fetching/updating plugins, they work in similarly. Though **neither the constant or filters are respected when it comes to auto-updating**; any plugin item with `plugin.update && plugin.autoupdate` is [updated](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/plugins/installed/actions.js#L520).

`class.jetpack-json-api-plugins-modify-endpoint.php` [handles](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/json-endpoints/jetpack/class.jetpack-json-api-plugins-modify-endpoint.php#L294) the update request.

---

Some thoughts:

1. For `class.jetpack-json-api-plugins-modify-endpoint.php`, I wonder if we should add a call to core's `WP_Automatic_Updater->`[should_update()](https://core.trac.wordpress.org/browser/trunk/src/wp-admin/includes/class-wp-automatic-updater.php#L139) to align the autoupdate behavior a bit more.
2. [Filter](https://developer.wordpress.org/reference/hooks/automatic_updater_disabled/) `automatic_updater_disabled` parallels the `AUTOMATIC_UPDATER_DISABLED` constant in name. Would we want to sync this up?
    * What about `add_filter( 'auto_update_plugin', '__return_false' );`?
    * Or what about individual items filtered by `auto_update_plugin`? 
3. At the least, I think we should pull in the `automatic_updater_disabled` constant and prevent updates from firing on the Calypso side of things [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/plugins/installed/actions.js#L520).

**Comment by kraftbj** [comment]
Apologies for the delay. 

1. Yes, I think it makes sense to check for `should_update()` within the API endpoint that handles WP.com-side updates. That provides a failsafe, even if any values failed to sync up to WP.com for any given reason. That's a good immediate thing to PR without regard to the other options.

3. Agreed here too.

2. Yeah, I think it makes sense to sync the value of related filters and think about how to display the UI. This can become a bit of a bigger bear and may be good to include design.

My thought is do 1 on the JP side immediately. 3, likewise, we can ensure the constant & filter are being synced up (both JP and WP.com changes needed) and then find where the update async job is fired off from to incorporate it. 2. Likewise, sync the value of that filter.

2. Would be good as a new wp-calypso issue to figure out the UI.

Thinking about the plugin filter, maybe it'll be a bit messy to ensure we have the right value and are using it right. Should the endpoint return an error when blocked from updating a plugin b/c of it that WP.com consumes and handles? I'm not too sure.

In any event, the immediate ability to respect locally via `should_update` at least prevents site-changing impact and we should be sure to land in 9.5.

**Comment by samiff** [comment]
> In any event, the immediate ability to respect locally via should_update at least prevents site-changing impact and we should be sure to land in 9.5.

Agreed, this is being requested in #18697

**Comment by samiff** [comment]
New PR #18707

With those changes, the majority of the concerns mentioned [above](https://github.com/Automattic/jetpack/issues/18562#issuecomment-770593867) are addressed; visiting the Calypso plugin management pages will respect the local site autoupdate constant & filters.

And while the `Autoupdates` toggles in Calypso do not accurately represent all combinations of a plugin's autoupdate status (e.g. when using `auto_update_plugin` to filter certain plugin slugs), it doesn't look like you are able to force a new autoupdate status for a plugin in such a case from Calypso. Once these changes are merged & live, I will do an enhancement request in the Calypso repo.

**Comment by samiff** [comment]
https://github.com/Automattic/jetpack/pull/18707 has been merged and will ship in JP 9.6, and a Calypso issue filed for the remaining issues with the Autoupdates toggle logic: https://github.com/Automattic/wp-calypso/issues/50551
