### ISSUE TITLE
`yarn install` causes global system changes

### ISSUE THREAD

**Issue by anomiex** [Automattic/jetpack#18564]
#### Steps to reproduce the issue

1. Check out the repository on a clean system.
2. Run `yarn install`

#### What I expected

No changes would be made globally.

#### What happened instead
A symlink was created in the global `~/.yarn/bin` directory. This directory is intended for packages that were globally installed using `yarn global add` or `yarn link`.

#### Notes

This is due to a postinstall script for `tools/cli/` trying to make `node_modules/jetpack-cli` be a symlink instead of a copy. Ideally we'd use `link:tools/cli` instead of `file:tools/cli` in package.json to make this happen, but due to https://github.com/yarnpkg/yarn/issues/8290 that breaks creation of the bin symlink in `node_modules/.bin/`. There's a [PR for Yarn that would fix it](https://github.com/yarnpkg/yarn/pull/5112), but it has been stalled since 2018 on a nitpick and possibly Yarn wouldn't even accept it anymore because they've apparently frozen 1.x in favor of their version 2.0 rewrite. Sigh.

**Comment by kraftbj** [comment]
I'm not having much success finding a clean way to do this yet. Adding the bin directly to the repo root and using `link` or `file` didn't make `jetpack` functional for me. Tried adding the bin directly, removing the cli package, etc. Calling the file directly works, but loses the magic of being able to run the command from anywhere.

I tried using `npm install` instead for grins using npm v6.14.11 and that did seem to work. It added the jetpack/node_modules to my `$PATH`, but I stopped short of seeing how they did that. I didn't check to see if editing the files would be instantly available or still needed to do some type of linking (and what would that have done).

**Comment by kraftbj** [comment]
Some other options:

* Remove the postinstall step and print a console message with install instructions.
* While the `yarn link` via the postinstall command is still needed to develop the CLI and use without a forced install, most people wouldn't need that. The instructions could just say how to add the node_modules/.bin location of the cli to PATH.

Thoughts?

**Comment by anomiex** [comment]
My main thought is that I wish yarn would fix their bug so `link:` would properly set `node_modules/.bin/`. At a quick glance it's probably fixed in yarn 2, but apparently they changed a lot of stuff in incompatible ways.

IMO yes, if people want it to be available globally then they should be willing to follow some instructions to do it themselves.

**Comment by kraftbj** [comment]
I'll adjust to remove the automatic steps, the dev env check and instructions, and other docs (needed anyhow).

I don't think there's a way to develop the CLI without using `yarn link` and making it global, but there is the `yarn install --force` workaround to "build" changes for testing for anyone not wanting to link.
