### ISSUE TITLE
Onboarding / Recommendations: state of the tab can take a while to update

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#18588]
Jumping in and out of the Recommendation tab leads to weird stuff, like not instantly detecting that Creative Mail had been installed or the recommended action not being visible. See the video below (weirdness starts at 0:19)

It all takes a long time to update too — couldn’t we save a final “state” so it doesn’t have to fetch the options every time?

https://videopress.com/v/4lrUAx1k

------

p8oabR-BT-p2#comment-4909

**Comment by robertf4** [comment]
Addressed with loading indicators in https://github.com/Automattic/jetpack/pull/18601

> It all takes a long time to update too — couldn’t we save a final “state” so it doesn’t have to fetch the options every time?

This is the case if navigating to this URL from within the React app, but when navigating to the URL directly it must reload the state as the React app is reloaded.
