### ISSUE TITLE
Port 1022 not available on macOS when running `yarn docker:up`

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#18603]
On macOS (at least my machine, running v11.1, Big Sur) TCP port 1022 is already claimed by /sbin/nfsd, so the docker environment won't boot.

Running this fixes it:

`PORT_SFTP=1023 yarn docker:up`

We should probably change the default port if this is affecting a bunch of people.

**Comment by jeherve** [comment]
I can't seem to reproduce (I'm also on Big Sur, fresh install). Do you think something else could impact `/sbin/nfsd` on your machine?

**Comment by gravityrail** [comment]
It may be triggered by enabling network sharing of folders on your machine.

**Comment by jeherve** [comment]
That didn't seem to create any issues for me. 

Unless this impacts other people, maybe it's enough of a workaround to specify the port in your `.env`?

**Comment by kraftbj** [comment]
I couldn't trigger it either. With one report, I would concur with @jeherve to note the port in a `tools/docker/.env` file ( https://github.com/Automattic/jetpack/blob/master/tools/docker/README.md#L71 )

I would suggest we close this for now, but open to reconsider if there are additional reports or other reasons to change it.
