### ISSUE TITLE
Subscription Form Block: Block errors when using color selector

### ISSUE THREAD

**Issue by bsessions85** [Automattic/jetpack#18619]
Found while testing pciE2j-bv-p2 - Video will be posted there soon.

#### Steps to reproduce the issue

1. Add Subscription Form block in editor
2. In Settings, click on one of the color circles so that it is selected
3. Click Custom Color link right below
4. Block shows an error

#### What I expected

I expected to see the color selector pop up so I can choose a color

#### What happened instead
The block shows the message "This block has encountered an error and cannot be previewed."

All the settings disappear

Console shows:
react-dom.min.de439aae.js:125 TypeError: Cannot read property 'hex' of null
    at ai (index.js?ver=39c79359c8398684c2536bc8034f5194:3)
    at new o (index.js?ver=39c79359c8398684c2536bc8034f5194:3)
    at Yg (react-dom.min.de439aae.js:68)
    at rh (react-dom.min.de439aae.js:98)
    at zj (react-dom.min.de439aae.js:228)
    at Th (react-dom.min.de439aae.js:152)
    at tj (react-dom.min.de439aae.js:152)
    at Te (react-dom.min.de439aae.js:146)
    at react-dom.min.de439aae.js:61
    at unstable_runWithPriority (react.min.e713ea3b.js:25)

**Screenshots**
![image](https://user-images.githubusercontent.com/31110506/106325327-e171ff80-6237-11eb-8dab-98ab8de1bdde.png)
<img width="1229" alt="Screen Shot 2021-01-29 at 1 43 52 PM" src="https://user-images.githubusercontent.com/31110506/106325560-3dd51f00-6238-11eb-847f-c2139230eee4.png">

**Comment by kwight** [comment]
This was fixed at some point – all color selectors for the block work as expected. Closing.

<img width="1398" alt="Screen Shot 2021-08-17 at 9 46 53 AM" src="https://user-images.githubusercontent.com/349751/129767230-95d12e9d-46d0-48a2-bb97-a2d92f6d1c46.png">
