### ISSUE TITLE
Widget Visibility: PHP Notice:  Undefined property: stdClass::$post_status

### ISSUE THREAD

**Issue by roykho** [Automattic/jetpack#18616]
Seeing `PHP Notice:  Undefined property: stdClass::$post_status in /srv/www/gitwooplugins/public_html/wp-admin/includes/misc.php on line 1433`

For every page that is on the site.

#### Steps to reproduce the issue

1. Activate the Jetpack (9.3.1) and ensure no other plugins are activated.
2. Go to Appearance->Widgets settings page.
3. See the PHP notice (mentioned above) in the logs. It will log one notice for every page that exists on the site.
4. Do the same test without Jetpack enabled, no more notices.

Other reports I've seen in the wild - https://wordpress.org/support/topic/error-in-wp-admin-includes-misc-php-on-line-1433/

#### What I expected

I am expecting to see no notices in the PHP logs.

#### What happened instead

I am seeing notices.

**Screenshots**

**Comment by jeherve** [comment]
Thanks for the report. I can't seem to be able to reproduce on my end at the moment, so there must be something different between your set up and mine? Is this happening on a test site of yours? If so, would you be able to get a stack trace of the error, so we can find out more about what's causing this?

If that's not an option, could you let me know what Jetpack modules are currently active on your site?If you go to `wp-admin/admin.php?page=jetpack_modules` you should get a full list.

Thank you!

**Comment by roykho** [comment]
Yes it is on a dev setup. So these are PHP notices so I don't think it has backtraces at least my environment is not configured to do so. But if it helps, Jetpack is in "Offline" mode.

![](https://d.pr/i/YN9hoq+)

**Comment by roykho** [comment]
Update: Ok so if I deactivate `Widget Visibility`, the notices go away. ![](https://d.pr/i/9Cdy4O+)

**Comment by roykho** [comment]
If it helps - the notice is generated when this happens https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/misc.php#L1433

Basically that check is expecting $page to be a WP Post object. But instead the pages are coming as stdClass objects. Thus `post_status` property doesn't exist.

**Comment by jeherve** [comment]
Related: #17434 

> Basically that check is expecting $page to be a WP Post object. But instead the pages are coming as stdClass objects. Thus post_status property doesn't exist.

Do you know if you have a plugin on your site that may make that change?

**Comment by roykho** [comment]
> Do you know if you have a plugin on your site that may make that change?

Only Jetpack is active during my test.

**Comment by jeherve** [comment]
cc @david-binda, who worked on #17434.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/error-after-activating-jetpack-in-wp-admin-includes-misc-php-on-line-1433/

**Comment by danjjohnson** [comment]
Also here: https://wordpress.org/support/topic/error-in-widgets-and-json-in-post-editor/

**Comment by wunc** [comment]
@jeherve  Here's a stack trace:

```
_wp_privacy_settings_filter_draft_page_titles (/Users/wunc/Sites/wordpress/web/wp/wp-admin/includes/misc.php:1433)
WP_Hook->apply_filters (/Users/wunc/Sites/wordpress/web/wp/wp-includes/class-wp-hook.php:287)
apply_filters (/Users/wunc/Sites/wordpress/web/wp/wp-includes/plugin.php:212)
Walker_PageDropdown->start_el (/Users/wunc/Sites/wordpress/web/wp/wp-includes/class-walker-page-dropdown.php:86)
Walker_PageDropdown->display_element (/Users/wunc/Sites/wordpress/web/wp/wp-includes/class-wp-walker.php:144)
Walker_PageDropdown->walk (/Users/wunc/Sites/wordpress/web/wp/wp-includes/class-wp-walker.php:244)
walk_page_dropdown_tree (/Users/wunc/Sites/wordpress/web/wp/wp-includes/post-template.php:1563)
Jetpack_Widget_Conditions::widget_admin_setup (/Users/wunc/Sites/wordpress/web/app/plugins/jetpack/modules/widget-visibility/widget-conditions.php:169)
WP_Hook->apply_filters (/Users/wunc/Sites/wordpress/web/wp/wp-includes/class-wp-hook.php:287)
WP_Hook->do_action (/Users/wunc/Sites/wordpress/web/wp/wp-includes/class-wp-hook.php:311)
do_action (/Users/wunc/Sites/wordpress/web/wp/wp-includes/plugin.php:484)
WP_Customize_Widgets->customize_controls_init (/Users/wunc/Sites/wordpress/web/wp/wp-includes/class-wp-customize-widgets.php:340)
WP_Hook->apply_filters (/Users/wunc/Sites/wordpress/web/wp/wp-includes/class-wp-hook.php:287)
WP_Hook->do_action (/Users/wunc/Sites/wordpress/web/wp/wp-includes/class-wp-hook.php:311)
do_action (/Users/wunc/Sites/wordpress/web/wp/wp-includes/plugin.php:484)
require (/Users/wunc/Sites/wordpress/web/wp/wp-admin/customize.php:112)
{main} (/Users/wunc/.composer/vendor/laravel/valet/server.php:219)
```

Digging into it, shows that [Jetpack_Widget_Conditions@get_pages()](https://github.com/Automattic/jetpack/blob/9.3/modules/widget-visibility/widget-conditions.php#L253) indeed creates an array of StdClass objects with only ID, post_parent, and post_title fields. So, that's why `$page` doesn't have a "post_status" property when it gets to that filter [_wp_privacy_settings_filter_draft_page_titles() line 1433](https://github.com/WordPress/WordPress/blob/5.6.2/wp-admin/includes/misc.php#L1433) later.

One possible fix would be to just add `{$wpdb->posts}.post_status` to [the SELECT on line 260](https://github.com/Automattic/jetpack/blob/9.3/modules/widget-visibility/widget-conditions.php#L260). I can confirm that if I make this change locally, the PHP Notice goes away.

**Comment by rezzap** [comment]
Another report on this in 3840136-zd-woothemes. I've asked them to try disabling the visibility widget to test this and check for any plugin or theme conflicts.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/error-in-wp-admin-includes-misc-php-on-line-1433-3/

**Comment by JenSwish** [comment]
Reported in 4040151-zen. Asked the user to try disabling widget visibility to see if this resolves the issue.

**Comment by LoonSongSoftware** [comment]
Seems like the simple fix from wunc is the answer. Do I need to submit a pull request to get this into the release cycle? Otherwise, the file's going to be overwritten whenever Jetpack updates...

**Comment by jeherve** [comment]
@LoonSongSoftware Feel free to submit a Pull Request, we'll be happy to take a look at it!

**Comment by JonHeist** [comment]
Same issue here, fix provided by wunc fixed the issue, although the @get_pages() was different from what they'd shared, was on line 343... maybe due to an update between that post and now.  I'd been seeing the same issue for several months when viewing the widgets editor and ignored them and then today noticed that my homepage was not loading properly (missing media all over) and the root cause was the jetpack plugin.  Again the fix by wunc took care of it (adding {$wpdb->posts}.post_status)

**Comment by danjjohnson** [comment]
Also reported here: https://wordpress.org/support/topic/error-of-type-e_error-was-caused-in-line-440/#post-14739007

**Comment by bizanimesh** [comment]
@jeherve is this related: https://wordpress.org/support/topic/error-of-type-e_error-was-caused-in-line-440/#post-14758278

**Comment by jeherve** [comment]
> @jeherve is this related: [wordpress.org/support/topic/error-of-type-e_error-was-caused-in-line-440/#post-14758278](https://wordpress.org/support/topic/error-of-type-e_error-was-caused-in-line-440/#post-14758278)

@bizanimesh That seems to be a different problem. It could be that the ctype PHP extension is not enabled on their server. They'd have to reach out to their hosting provider to let them know about the issue.
