### ISSUE TITLE
Protect: add network-wide panel on multisite networks 

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1861]
It would be nice to add a security panel allowing Mutlisite super admins to change whitelist settings for all sites in their network, at once.

Suggested here:
https://wordpress.org/support/topic/jetpack-protect-and-wordpress-multisite?replies=3&view=all#post-6734629

Related: #1842

**Comment by jeherve** [comment]
Network-wide protection was also suggested here:
https://wordpress.org/support/topic/bruteprotect-to-jetpack-protect-module-on-multisite

**Comment by RavanH** [comment]
Thanks Jeremy for adding my vote :) Hope this can be implemented sooner rather than later! By the way, does Protect work when Jetpack is in development mode?

**Comment by jeherve** [comment]
> does Protect work when Jetpack is in development mode?

No, your site has to be connected to WordPress.com for you to use the Protect API.

**Comment by dereksmart** [comment]
Global whitelisting was made available in #2192 :)
