### ISSUE TITLE
Sharing to Facebook option 

### ISSUE THREAD

**Issue by Piet-Reijers** [Automattic/jetpack#18618]
Using Jetpack for posting new posts to Facebook. Have the need of mever passing the post body tekst. Only the URL and title.

Can't find it in the script where to change this manualy.

How I now use it is making a new post. Cut all tekst from the message. Publicize the post and it's getting posted on FAce Book also. Then I copy the text back in and do an update.

**Comment by jeherve** [comment]
Thanks for your contribution. This should become possible once we implement #261.
