### ISSUE TITLE
Tiled Gallery: Galleries load full size images and not thumbnails in mosaic layout

### ISSUE THREAD

**Issue by RCowles** [Automattic/jetpack#18636]
Jetpack used to load resized images via Photon for Tiled Gallery thumbnails. Now, in what appears to be a regression, full-sized images are served as gallery thumbnails.

--------

#### Steps to reproduce the issue

1. Create a new Tiled Gallery.
2. Select the `Mosaic` layout option.
3. View source for `img` thumbnails.

--------

#### What I expected

The source image for gallery thumbnails would be resized and scaled down via Photon.

--------

#### What happened instead

Full-size images were served.

**Comment by snowmads** [comment]
If it's helpful, a user in 3684943-zen updated us to say that 

>"SInce some time (don't know which wordpress update it was) links in galleries start showing to attacment_id. Before that links were "pretty links" just like regular ones."
>
>A gallery made in 2019 shows those links to the attachment_id page. It redirects to pretty links but in tiled gallery images are full size. A gallery from 2017 is showing pretty links inside tiled gallery, and images are thumb size.

Some example links are in the ticket, but I don't want to post them publicly.

**Comment by mreishus** [comment]
The change should have only happened for sites that are both private and atomic. If it's happening for regular sites that don't meet these conditions, it is definitely a bug. The relevant code that changed recently is here: https://github.com/Automattic/jetpack/pull/19201

**Comment by jeherve** [comment]
Related: #24636

**Comment by jeherve** [comment]
This was done in #32598.
