### ISSUE TITLE
Admin UI: add standard WP footer to the bottom of the admin pages

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1863]
Jetpack doesn't include the standard admin footer that appears on all other dashboard pages, and for that reason site owners can't use hooks like `in_admin_footer` to add content to the footer on our pages.

It'd be nice to add this footer back. It was removed when we switched to the new UI back in Jetpack 3.0.

Suggested here:
https://wordpress.org/support/topic/main-jetpack-and-settings-page-do-not-show-admin-footer

**Comment by dereksmart** [comment]
It's still loaded on our admin pages but is <a href="https://github.com/Automattic/jetpack/blob/master/scss/templates/_main.scss#L35">hidden with css</a>.  It can still be hooked into and displayed with overriding CSS.  

That said, doesn't feel right to me that we're not displaying it.
