### ISSUE TITLE
Fatal error in class.jetpack.php: Using $this when not in object context

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1865]
When activating the plugin:

`Fatal error: Using $this when not in object context in /home3/tony/public_html/wp-content/plugins/jetpack/class.jetpack.php on line 1534`

Reported here:
https://wordpress.org/support/topic/jetpack-causing-fatal-errors?replies=1&view=all

**Comment by dereksmart** [comment]
Looks like an oversight when the method was changed to static a few days ago.  <a href="https://github.com/Automattic/jetpack/commit/93a4a7f505a0332427ded7fb4b598e7cdcc2c1cc">#</a>

**Comment by RCowles** [comment]
Also reported in #2144907-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/fatal-error-using-this-when-not-in-object-context-across-entire-site?replies=1&view=all
