### ISSUE TITLE
Publicize doesn't respect the OG tags set by other plugins

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#1866]
If setting a different OG tag (such as the og:description through Yoast's SEO plugin), the Publicized post doesn't respect the new OG tag; instead, it Publicizes what the OG tag would be if it were Jetpack that was generating the tags. 

However, running the post through Facebook's debugger shows the OG tags as set by the other plugin. This is unexpected behaviour for a user. First mentioned in 2136753-t

**Comment by jkudish** [comment]
Publicize doesn't claim to use OG tags for deciding what content to publish to external services. And it probably never will. I guess there's some confusion because they are sort of related things...

If one wants to modify the string sent to the service, then they should set a custom message.

**Comment by jeherve** [comment]
> If one wants to modify the string sent to the service, then they should set a custom message.

@jkudish The custom message only edits the title of the message, though:

![screen shot 2015-04-22 at 10 43 49 am](https://cloud.githubusercontent.com/assets/426388/7269461/c39a4cae-e8dc-11e4-99d8-c83d296beda9.png)
![screen shot 2015-04-22 at 10 44 05 am](https://cloud.githubusercontent.com/assets/426388/7269463/c9585c94-e8dc-11e4-92b6-1ec54ed2aeb2.png)

How would one go about creating their own message there? I guess setting an excerpt would be a good solution, once #508 is fixed?

**Comment by jkudish** [comment]
That's not currently possible as you correctly point out. We'll work out new ways for folks to customize what's publicized with some more updates over the next few months. But it won't pull from `og` tags from other plugins regardless. The only thing that `og` will affect is the little preview generated by Facebook.
