### ISSUE TITLE
Cookie Widget: Preview from Gutenberg block-based widget screen doesn't display correctly

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#18664]
#### Steps to reproduce the issue

1. Have Jetpack (v9.5-alpha used) active, and make sure extra widgets are turned on in `/wp-admin/admin.php?page=jetpack#/writing`
2. Have the Gutenberg plugin active (v9.8.3 used).
3. In `WP Admin > Appearance > Widgets` add the `Jetpack Cookies & Consents Banner` to a widget area and save changes.
4. Click on `Preview` for the cookie widget (wrapped by the Legacy Widget block wrapper).

#### What I expected

* For a preview of the cookie widget to render.

#### What happened instead

* The cookie widget isn't previewed in a useful way. The widget content is added under the `wp-block-legacy-widget__preview` iframe, though I imagine there is some CSS or rendering conflict at play.

**Screenshots**

![Markup on 2021-02-01 at 18:24:32](https://user-images.githubusercontent.com/15803018/106539182-c105a780-64ba-11eb-840d-2b2335607a18.png)

**Comment by xpurichan** [comment]
Reported in 25565225-hc. This is probably larger issue given that block editing widgets is default now.
