### ISSUE TITLE
contact-field shortcode issues Warning if used on its own with no parameters

### ISSUE THREAD

**Issue by bobbingwide** [Automattic/jetpack#1867]
I was documenting the syntax of Jetpack's shortcodes and inadvertently tried 
[contact-field] on its own. 

It produced.

Warning: Invalid argument supplied for foreach() in C:\apache\htdocs\oikcom\wp-content\plugins\jetpack\modules\contact-form\grunion-contact-form.php on line 1177

Not a major problem. 

As an aside. If you do something silly like
[contact-form show_subject="no" submit_button_text="Send"]
[contact-field]
[/contact-form]
you don't get the warning, but you do get a fairly useless form with an unlabelled text field.

**Comment by samhotchkiss** [comment]
Moved to 3.5, as this should be a very easy fix, and we should protect users from silly errors as much as possible :)

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
