### ISSUE TITLE
Updating from older Jetpack version causes redirect to admin even when requesting frontend site

### ISSUE THREAD

**Issue by jwenerd** [Automattic/jetpack#1868]
We are upgrading from Jetpack 3.3 to 3.4.1 

The activate_new_modules method in the Jetpack class calls activate_default_modules which then results in a redirects to /wp-admin/admin.php?page=jetpack from this line: https://github.com/Automattic/jetpack/blob/3.4.1/class.jetpack.php#L1956

This is the backtrace I used to find the problem: https://gist.github.com/jwenerd/ae8c924fb8c9a215f9dd

**Comment by mikeyarce** [comment]
Related conversation in 2140108-t

**Comment by samhotchkiss** [comment]
Fixed by #1984
