### ISSUE TITLE
Testimonials: 'jetpack-testimonial' theme support does not enable CPT automatically

### ISSUE THREAD

**Issue by dashkevych** [Automattic/jetpack#18703]
`add_theme_support( 'jetpack-testimonial' )` added to the theme does not enable Testimonial CPT in dashboard. In order to display Testimonial CPT in dashboard, we need go to Jetpack > Settings > Writing, and toggle a Testimonials option.

Is it supposed to be like that? If yes then what's the reason of using this `add_theme_support` in the theme?

#### Steps to reproduce the issue

1. I've created a fresh new WordPress site using LocalWP. 
2. Then I've added `add_theme_support( 'jetpack-testimonial' )`  to the `twenty_twenty_one_setup` function in the Twenty Twenty One theme.
3. Then I've installed Jetpack.
4. Switch to Twenty Twenty theme (which does not have testimonial support).
5. Switch back to Twenty Twenty One.

#### What I expected

I expected to see Testimonial CPT enabled in dashboard automatically without a need of enabling it in Jetpack settings.

#### What happened instead

Testimonial CPT was not enabled in dashboard.

WordPress: **5.6.1**
Jetpack: **9.4**

**Comment by jeherve** [comment]
You're most likely running into this issue, since you're testing locally: #7971
