### ISSUE TITLE
Subscriptions Block: invalid block error when opening existing post with old version of block

### ISSUE THREAD

**Issue by p-jackson** [Automattic/jetpack#18706]
#### Steps to reproduce the issue
1. Grab this headstart annotation 28360-pb. The post content on the home page was valid at one point in time
2. Put it on your wpcom sandbox
3. Run `wp headstart run --url={{your-test-site.wordpress.com}} --user={{your-wpcom-username}} --annotation={{path-to-the-annotation-file}}`
4. Open the new "Home" page in the editor
5. Scroll down to see the Subscriptions block

#### What I expected
This annotation uses an old version of the subscription block, and I would expect to see now invalid block error and the post content get updated to the latest version.

#### What happened instead
Invalid block error.

<img width="996" alt="Screenshot 2021-02-04 at 4 25 33 PM" src="https://user-images.githubusercontent.com/1500769/106840741-a3784e00-6705-11eb-94a0-ce585b6f63c7.png">

The post content is specifying the `subscribePlaceholder` and `submitButtonText` attributes even though it's just using the default text. In #16361 a change was made that stopped specifying these attributes if it was just the default, and I wonder if that's where this issue came from. That PR includes migrations though, but it doesn't seem to be working in this case.

Another possible hint about what's going wrong is that on WordPress.com the php changes the default text to something different from what's used on WordPress.org. I don't think the js knows about this difference though. Maybe that's what's causing the problem?
https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/modules/subscriptions/views.php#L658

**Comment by jeherve** [comment]
> Another possible hint about what's going wrong is that on WordPress.com the php changes the default text to something different from what's used on WordPress.org. 

I believe that's the root of the problem. I'll close this issue in favor of #18518, where we're tracking the problem.
