### ISSUE TITLE
portfolio shortcode missing ob_start() when there are no posts to display

### ISSUE THREAD

**Issue by bobbingwide** [Automattic/jetpack#1871]
The portfolio / jetpack_portfolio shortcode misbehaves when there are no posts to display.
The page can become very badly formatted.

Expected output:
Your Portfolio Archive currently has no entries. You can start creating them on your dashboard.

Actual output:
This message appears in the wrong place

Problem explanation:
missing call to ob_start() in the else for if ( $query->have_posts() )

Fix: 
Move the ob_start() to before the test

Workaround:
Create some projects or don't use the shortcode.

Additionally: 
This message is produced whenever query_posts() returns no rows. 
It's misleading when the user has passed invalid values for the include_type or include_tag parameters.

**Comment by bobbingwide** [comment]
Same problem and fix for the testimonial shortcode.

**Comment by jeherve** [comment]
cc @michaeldcain
