### ISSUE TITLE
Tiled Gallery: Malformed markup triggering Block Recovery

### ISSUE THREAD

**Issue by 0aveRyan** [Automattic/jetpack#18710]
After upgrading a site from Jetpack 8.6 to Jetpack 9.4, Jetpack Tiled Gallery blocks are all triggering the "This block has encountered an error and cannot be previewed" dialog. No other modifications to the Block Editor have been made. The only other plugin extending the Block Editor is Yoast SEO.

<img width="776" alt="Code diff from Gutenberg showing malformed markup" src="https://user-images.githubusercontent.com/9565066/106912997-ccc2bb00-66c0-11eb-968d-5d0195198c09.png">

#### Steps to reproduce the issue

1. Install Jetpack 8.6
2. Insert a Tiled Gallery block
3. Upgrade Jetpack to 9.4
4. Reopen post containing Tiled Gallery

**Comment by jeherve** [comment]
Thanks for the report. That's indeed a known issue when migrating old versions of the blocks to the new one. This is currently tracked here:
#16514
