### ISSUE TITLE
Contact Form: Other user using admin email as notif address doesn't work

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#1873]
To reproduce:

1. On test site, set the admin email (under Settings > General) to `something@domain.com`.
2. As a second user (with email `different@domain.com`), create a page with a contact form.
3. In the contact form, don't set a custom email notification address.
4. Fill out contact form and send.
5. Email goes to `different@domain.com` as expected, since they are the page author.
6. Edit page and use `something@domain.com` and custom email notif address.
7. Insert shortcode. (The email you set is stripped from the shortcode.)
8. Fill out form and send.
9. Email comes to `different@domain.com`, which is unexpected.

It seems the admin email might be being detected as the default, therefore being stripped from the shortcode, and thus the email ultimately ends up going to the post author.

**Comment by aheckler** [comment]
From 2134072-t.

@chaselivingston also had one like this. Mind dropping the ticker # here? :)

**Comment by chaselivingston** [comment]
2138026-t

**Comment by dereksmart** [comment]
It strips the admin email even if the admin is the one who created the post.  I'll look into this today, but in the meantime you can tell users that manually adding the `to="admin@email.com"` attribute will work.  It's only getting stripped from the form builder.
