### ISSUE TITLE
Jetpack adds extra [data-carousels] with cursor: pointer to non-linked content in column blocks

### ISSUE THREAD

**Issue by swmarlow** [Automattic/jetpack#18731]
#### Steps to reproduce the issue

1. Go to https://penmetparks.org/parks/sunrise-beach-park/
2. Hover over any of the column blocks on the Page
3. The cursor changes from default to a pointer (line 4 jetpack.css), despite unlinked content 
4. You can see multiple data carousel divs throughout the page, starting with the Jetpack Contact Block

#### What I expected
The [data carousel] pointer should only be present in the 3 column block with the Jetpack image gallery

This appears to be a duplicate bug reported at WordPress.org:
https://wordpress.org/support/topic/issue-errors-with-jetpack-possibly-carousel-please-help/

**Comment by jeherve** [comment]
Thanks for the report. This is a known issue, currently tracked in #13428, so I'll close this issue.
