### ISSUE TITLE
Social icons block: Skype call link not working

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/jetpack#18739]
#### Steps to reproduce the issue

1. Add the social icons block to a page
2. add skype:username?call as the link for a skype icon
3. publish page and click link (make sure you have skype client installed)
4. See that page just reloads

#### What I expected
 
button should open a prompt to connect to user account in skype app

#### What happened instead

page just reloads and no prompt or connection is made

add info:
3717856-zen
p1612688702078700-slack-C03TY6J1A

**Screenshots**

**Comment by jeherve** [comment]
The Social Icons block is not provided by Jetpack, so I'm afraid I will not be able to be of much help. The block is part of WordPress Core, so I would recommend reporting this issue in the Gutenberg repo if you can reproduce on a self-hosted WordPress site. If this only happens on a WordPress.com site, I would recommend creating an issue in the Calypso repo, as it could be linked to extra sanitizing happening on WordPress.com.

**Comment by chad1008** [comment]
Thanks @jeherve. I was able to reproduce on a JN site, so I've [reported it over in the Gutenberg repo](https://github.com/WordPress/gutenberg/issues/28991).

For any future searchers: this only applies to the social links block, manually creating the link in a paragraph or HTML block works fine. Might be a temporary workaround.
