### ISSUE TITLE
Custom CSS: add option or filter to turn off some of CSSTidy's features

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1874]
It would be nice if site owners could disable some of the features that create code that doesn't match their coding standards, such as removing leading zeros.

> You could add an option to allow/disallow those changes and some code-beautifying perhaps.

Suggested here:
https://wordpress.org/support/topic/css-stylesheet-editor-is-buggy-use-simple-custom-css-instead?replies=3&view=all#post-6745116

**Comment by kraftbj** [comment]
This would provide a nice workaround for cases where people want to use advanced CSS that is too new for our CSS libraries.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
