### ISSUE TITLE
Protect: Add admin notice upon activation

### ISSUE THREAD

**Issue by RCowles** [Automattic/jetpack#1875]
When Protect is enabled (manually or auto-activated) it would be nice to include an admin notice. This notice could briefly explain Protect, and prompt the admin user to whitelist their IP Address right away. This would help to avoid situations where an admin is accidentally locked out from their Dashboard. (See #2139552-t for reference)

**Comment by samhotchkiss** [comment]
There are some other considerations here-- we'll get it fully thought out before implementing, possibly in 3.6

**Comment by RCowles** [comment]
Thanks, Sam!
