### ISSUE TITLE
Protect: Add option to always have the Captcha

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#1876]
The user in 2139913-t would like to always have the captcha on the login screen; perhaps a filter can be made for that?

**Comment by samhotchkiss** [comment]
They can just use:

`set_transient( 'brute_use_math', 1, DAY_IN_SECONDS );`

That's the transient that Protect checks to see whether or not to display the CAPTCHA.  They put that in their functions.php, they'll always see the CAPTCHA
