### ISSUE TITLE
Infinite Scroll: Body class is not applied with multisite. 

### ISSUE THREAD

**Issue by puikinsh** [Automattic/jetpack#1878]
Body class for infinite scroll (.infinite-scroll) is not applied therefor I can't hide existing page navigation using CSS. This happens only on multisite as you can see [here](http://colorlib.com/dazzling/)

And here is [another website](http://www.armybases.co/) using the same plugins but works as a standalone installation. Infinite scroll works the same way but body class is applied, so I can hide existing navigation.
It was working fine until recently but can't recall which version of Jetpack did broke this functionality. 

Just some information that might help just in case: Both sites are using Ubuntu, Nginx, W3 Total Cache + Memcached + fastcgi_cache. The only difference that one that isn't working uses HHVM but I tried to disable that but with no success. 

Let me know if you need any other details.

**Comment by jeherve** [comment]
I'm not sure the problem is linked to Multisite. Could you try to apply the fix in #1826, and let me know if it helps/

**Comment by puikinsh** [comment]
Thank you! It did the trick. However, I am a bit puzzled as it affected only my multisite and not dozens of sites that I checked that use Dazzling theme. All were using "click" type infinite scroll as this is how theme is built by default. 

Thanks again for your help!
