### ISSUE TITLE
Avoid mixed-content warnings when embedding videos

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/jetpack#1880]
To avoid mixed-content warnings when embedding videos, If the site is a secure site (`https://`), then we should always output a secure embed.

Currently, if the user pastes in a Vimeo or YouTube link beginning with `http:` instead of `https:`, the outputted iframe/embed begins with http, even if the site is loaded https.

Jetpack should either:
• always use https (preferred), or,
• always use https when the site is loaded over https

**Comment by kraftbj** [comment]
Right now, we use `set_url_scheme` which should return http or http based on the result of `is_ssl`. [youtybe code ref](https://github.com/Automattic/jetpack/blob/e6004a22d9582ed96d2e1ab5c9394cae6f2b05ff/modules/shortcodes/youtube.php#L294), so it should already output the second option.

Any harm in always using https or worst case, can go protocol neutral.
