### ISSUE TITLE
Search Widget: Is case sensitive in Cyrylic

### ISSUE THREAD

**Issue by fresatomica** [Automattic/jetpack#18825]
#### Steps to reproduce the issue

1. In a post, add Cyrillic and non-Cyrillic language words starting with an upper case.
2. Search for a term in Cyrillic, ignoring the upper case.
3. Search for a term in non-Cyrillic, again ignoring the upper case.
3. See the results

#### What I expected

Both terms should be found, regardless of the upper case.

#### What happened instead
The search widget only ignores the upper case in the case of a non-Cyrillic language.

<img width="603" alt="Screen Shot 2021-02-15 at 12 16 12" src="https://user-images.githubusercontent.com/40177971/107939861-a423a680-6f87-11eb-83db-4f642a71afae.png">

<img width="773" alt="Screen Shot 2021-02-15 at 12 18 44" src="https://user-images.githubusercontent.com/40177971/107940093-fbc21200-6f87-11eb-8422-de8b17146388.png">

Reported in https://wordpress.com/forums/topic/search-is-case-sensitive-for-cyrillic/.

**Comment by nirmalc** [comment]
I think the user might be using default search and not JPS. We do tokenize Cyrillic in a case-sensitive way; One thing I see is that our language detector identifies Netherlandia ( sorry - hard to type Cyrillic in my keyboard) as Ukrainian.  JPS defaults to English / ISO tokenization in this case..

Here is my test:
 
`https://nirmal.blog/?s=%D0%9D%D1%96%D0%B4%D0%B5%D1%80%D0%BB%D0%B0%D0%BD%D0%B4%D0%B8`

^ Netherlands starting with capital 

`https://nirmal.blog/?s=%D0%BD%D1%96%D0%B4%D0%B5%D1%80%D0%BB%D0%B0%D0%BD%D0%B4%D0%B8`

^ All lowercase

Both will give identical results. Please let me know what you think  - I can debug if this problem can be recreated.  

Sorry for the delay!

cc: @gibrown

**Comment by zdenys** [comment]
5743217-zd-woothemes

> Since all posts are published in FULL CAPS, the users can't find any of our news unless they search in caps as well.

**Comment by zdenys** [comment]
Is there any workaround for WP.com Simple Sites that cannot use Jetpack Search? Or do we need to wait for a fix?

**Comment by robfelty** [comment]
I looked into this a bit more, and it seems that JP Search works fine with Cyrllic. Closing.
