### ISSUE TITLE
Jetpack Search: theme styling issues in new P2+ modal 

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#18838]
In https://github.com/Automattic/jetpack/pull/18702 we have introduced a new modal style for Jetpack Instant Search.

In this issue we'll test the following themes and detail any issues encountered with the new modal design:

- [x] argent
- [x] astra
- [x] colormag
- [x] hamilton
- [x] shapely
- [x] storefront
- [x] sydney
- [x] twentyeleven
- [x] twentyfifteen
- [x] twentyfourteen
- [x] twentynineteen
- [x] twentyseventeen
- [x] twentysixteen
- [x] twentyten
- [x] twentythirteen
- [x] twentytwelve
- [x] twentytwenty
- [x] twentytwentyone

**Comment by bluefuton** [comment]
Twenty Twenty One: checkboxes are misaligned.

<img width="299" alt="Screen Shot 2021-02-16 at 15 18 25" src="https://user-images.githubusercontent.com/17325/108012061-53867900-706d-11eb-8cd8-f8e43f834398.png">

**Comment by bluefuton** [comment]
Twenty Twelve: result subtitle (slug in this case) is being clipped at the bottom:

<img width="672" alt="Screen Shot 2021-02-16 at 15 31 04" src="https://user-images.githubusercontent.com/17325/108012112-7022b100-706d-11eb-893d-1500801f1e40.png">

**Comment by bluefuton** [comment]
Twenty Sixteen: heavy black border after sidebar sections.

<img width="412" alt="Screen Shot 2021-02-16 at 15 35 04" src="https://user-images.githubusercontent.com/17325/108012149-87619e80-706d-11eb-8422-1fc5e49394be.png">

**Comment by bluefuton** [comment]
[ ] Twenty Fourteen - links are not visible in light mode unless hovered over (white text color by default in theme).

<img width="586" alt="Screen Shot 2021-02-17 at 10 55 15" src="https://user-images.githubusercontent.com/17325/108126457-be3bc100-710e-11eb-9d4f-4d01db417643.png">

**Comment by jsnmoon** [comment]
Just spun up a PR that should address all the aberrations mentioned in this issue.

**Comment by bluefuton** [comment]
- [ ] Sydney: active search inputs have a bright red border. Can look a bit odd in the modal because it doesn't encompass the entire input area.

<img width="1329" alt="Screen Shot 2021-02-17 at 11 01 30" src="https://user-images.githubusercontent.com/17325/108127147-aa448f00-710f-11eb-9f97-ee0588c22e85.png">
