### ISSUE TITLE
Subscriptions: Anchor Name not correct

### ISSUE THREAD

**Issue by benjaminwolkchen** [Automattic/jetpack#18856]
#### Steps to reproduce the issue

1. Go to awesomebible.de
2.  Scroll down to the footer.
3. Subscribe via a (fake) Email
4. The page refreshes

#### What I expected

The browser automatically scrolls down to the subscribe form via the anchor tag.

#### What happened instead
The browser doesn't scroll down.

I think this happens, because the anchor tag is not correct.
The URL shows `https://awesomebible.de/?subscribe=success#blog_subscription-19` but the anchor "blog_subscription-19" isn't found anywhere in the HTML.

The subscription form has the following anchor tags: `ct-widget widget_blog_subscription jetpack_subscription_widget`.

Here the full code for the subscribe form:
```
<div class="ct-widget widget_blog_subscription jetpack_subscription_widget"><h2 class="widget-title">Blog via E-Mail abonnieren</h2><div class="success"><p>Sehr schön! Es wurde gerade eine E-Mail versandt, um dein Abonnement zu bestätigen. Bitte öffne diese E-Mail jetzt und klicke auf „Folgen bestätigen“, um dein Abonnement zu starten.</p>
</div>
```

**Comment by jeherve** [comment]
This appears to be an issue with your theme, Blocksy. When themes register sidebar areas, WordPress provides an option to add a unique id to each widget that is added to that sidebar. Here is how it's done in the Twenty Twenty One theme for example:
```php
'before_widget' => '<section id="%1$s" class="widget %2$s">',
```
-- https://core.trac.wordpress.org/browser/tags/5.6.1/src/wp-content/themes/twentytwentyone/functions.php#L361

Your theme, however does not declare that unique ID:
```php
'before_widget' => '<div class="ct-widget %2$s">',
```
-- https://themes.trac.wordpress.org/browser/blocksy/1.7.69/inc/init.php#L509

I would recommend that you get in touch with the theme author and let them know about the issue. They should be able to address this in a future update.

I hope this helps.

**Comment by benjaminwolkchen** [comment]
Thanks for your help.
I notified the Theme Author.
