### ISSUE TITLE
Display Posts Widget: remove !important from CSS

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1886]
We should remove `!important` from the Display Posts Widget CSS to make it easier for folks to style the widget.

Reference:
https://github.com/Automattic/jetpack/blob/3.4.1/modules/widgets/wordpress-post-widget/style.css#L18

Reported here:
https://twitter.com/tsiger/status/582536932372164608

**Comment by jeffgolenski** [comment]
I'll take a look at this. @jeherve feel free to assign me to any CSS related issues. Ideally, we need to remove every instance of `!important` within our css.

**Comment by tsiger** [comment]
Also, the line-height and font-size styles should be removed. I have tested this widget in more than 30 themes and it breaks visual hierarchy, especially the line-height style.

**Comment by jeffgolenski** [comment]
@tsiger thanks for the feedback! I'll look into it!

**Comment by samhotchkiss** [comment]
@jeffgolenski - what's the status on this?  should we plan to push to 3.6?

**Comment by jeffgolenski** [comment]
@samhotchkiss this is going to be an ongoing thing. push it to 3.6, please. I want to scour all of the code and rewrite what's necessary to remove any and all !important tags we may have.

**Comment by samhotchkiss** [comment]
Pushed it real good.

**Comment by lancewillett** [comment]
Noticed this one in a search for Display Posts Widget. Still a pending task or should we abandon it?

**Comment by jeffgolenski** [comment]
@lancewillett This is one of those back-burner items that's in no way a priority at this time. I don't want to abandon it, but we should keep the "not currently planned" milestone.
