### ISSUE TITLE
Blocks: switch away from __experimentalBlock to useBlockProps

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#18864]
WordPress 5.6 (soon to be required to use the Jetpack plugin) introduces the following change:
https://make.wordpress.org/core/2020/11/18/block-api-version-2/

It will allow us to switch away from `__experimentalBlock` to `useBlockProps` for some of our blocks.

- [ ] Video
- [x] Premium content Take one done https://github.com/Automattic/jetpack/pull/19844, needs take two https://github.com/Automattic/jetpack/pull/19844#issuecomment-844024627

Matching Gutenberg change:
https://github.com/WordPress/gutenberg/pull/31419

*******

Primary issues: #18842  (5.7), https://github.com/Automattic/jetpack/issues/19654 (5.8)

**Comment by andrewserong** [comment]
@jeherve just double checking, it looks like WordPress 5.6 is the required minimum version of WordPress for the Jetpack plugin. I assume this means we can move over to using `useBlockProps` directly without having to guard it behind a check / maintain the existing `__experimentalBlock` for backwards compatibility?

**Comment by jeherve** [comment]
@andrewserong Yes, correct. In addition to that, we can aim to have this issue closed by the time WordPress 5.8 is available (Jetpack 9.9); by then, Jetpack will require WP 5.7.

**Comment by andrewserong** [comment]
Great, thanks for confirming!

**Comment by roundhill** [comment]
@jeherve has anyone on Jetpack taken on the Video block changes? If not we'll handle it 😄

**Comment by jeherve** [comment]
Noone has looked at it yet, no. I'll be happy if you do :)

**Comment by roundhill** [comment]
Video block is ready for review: #19913
