### ISSUE TITLE
Jetpack Search: modal close button could be ambigious (could be interpreted as 'clear input')

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#18879]
#### Steps to reproduce the issue

1. Open a search modal on a site with Instant Search enabled.

#### What I expected
It's possible to close the search modal, or to clear the search input.

#### What happened instead
The 'X' closes the modal, but may be interpreted as a 'clear search input' button.

<img width="1098" alt="Screen Shot 2021-02-19 at 15 05 53" src="https://user-images.githubusercontent.com/17325/108447177-4f07cd80-72c4-11eb-9a31-47c749b920b1.png">

This came up as feedback after @jeffgolenski's excellent presentation at the Jetpack Design Share.

**Comment by jeffgolenski** [comment]
p2 formerly had a "clear" near the X icon, but it doesn't appear to be there. @evilluendas do we have any data / reasoning on why that was removed? I'd like to harness any data you've collected on usage out in the world. Thanks!

**Comment by evilluendas** [comment]
@jeffgolenski It was in the [original mockups](https://www.figma.com/file/I5d3mVcMN0y1MnOds4fO5V/P2?node-id=4694%3A779) (see below) but we never actually got to implement it. I can't remember exactly why, though,maybe it was a technical issue with the styling? @unDemian do you remember?

It'd be awesome to have it though, I think it'd be very useful and would make very clear what the 'X' actually does.

![image](https://user-images.githubusercontent.com/820374/108737816-e1a9a600-752a-11eb-9b0b-dbf22da473b2.png)

**Comment by jeffgolenski** [comment]
Ah! that's where I saw it! Thanks @evilluendas 

@bluefuton @jsnmoon I think we should have a dividing line between the two elements. 

Having just "clear" near the X, make them feel as though they are the same element and would do the same thing. I'd hate to have people accidentally close a search when they simply meant to clear it!

![Screen Shot 2021-02-22 at 12 04 05 PM](https://user-images.githubusercontent.com/214813/108742857-31c24180-7506-11eb-9f00-dd2b4b8c2aa7.png)

**Comment by jsnmoon** [comment]
@jeffgolenski: I really like this solution!
