### ISSUE TITLE
Markdown parsing issue for code tags 

### ISSUE THREAD

**Issue by yuis-ice** [Automattic/jetpack#18895]
Here I have an example text content I want to post from the WordPress new post page: 

~~~
npmパッケージが正常に公開されているかどうかを確認するには以下コマンドを使用します。

```
npm show <package-name>
```

例として、僕の作成したnpmパッケージでは以下のように表示されます。
~~~

But when I clicked the title area, or "draft", the content become a garbled like this: 

~~~
npmパッケージが正常に公開されているかどうかを確認するには以下コマンドを使用します。

```
npm show <package-name>
```</package-name>

例として、僕の作成したnpmパッケージでは以下のように表示されます。
~~~

I updated my WordPress and Jetpack plugin, re-turned off and on the "enable markdown" button.

**Comment by jeherve** [comment]
Thanks for the report. Could you let me know if you experienced this issue with the Markdown block in the block editor, or when using the classic editor?

**Comment by yuis-ice** [comment]
@jeherve 

I'm afraid to say but don't know the difference, here is the screen shot. 

![https://yuis.xsrv.jp/images/ss/ShareX_ScreenShot_986d37d2-569d-422b-8d84-fe384bc0a316.png](https://yuis.xsrv.jp/images/ss/ShareX_ScreenShot_986d37d2-569d-422b-8d84-fe384bc0a316.png)

**Comment by jeherve** [comment]
Ah, I see what is wrong. You seem to be typing in markdown in a standard paragraph block. I'm afraid WordPress does not support that. You would need to use the Markdown block instead, like so:


https://user-images.githubusercontent.com/426388/109189559-7236ef00-7794-11eb-8bb3-d68680f62116.mov

**Comment by yuis-ice** [comment]
great, thanks.
