### ISSUE TITLE
Carousel: Improve Swiping on Mobile to not be Clunky

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#18923]
>Swiping between photos was a little clunky. In the video below, you can see the image moving around when I’m swiping normally left or right, trying to get to another image. This is in Safari on an iPhone 12 mini.

Another comment:

>I miss the elasticity that I’m used to having on mobile. Right now going from one image to another feels very static. Here is a video

#### Additional context

p8oabR-Co-p2#comment-4998
p8oabR-Co-p2#comment-5001

**Comment by jeherve** [comment]
cc @glendaviesnz, who worked on #18720. This may be good feedback.

**Comment by glendaviesnz** [comment]
@sdixon194 we made some improvements to swiping in #18720 which may fix the issues you are having. The main change in this PR was to make it possible to pinch and zoom on the central image, but the swipe left and right should also now be more responsive.

**Comment by jeherve** [comment]
> we made some improvements to swiping in #18720 which may fix the issues you are having

To clarify, the feedback above was from testing #18720.

**Comment by glendaviesnz** [comment]
> To clarify, the feedback above was from testing #18720.

Ah, sorry 🤦  

> I miss the elasticity that I’m used to having on mobile

@sdixon194 are you able to confirm if this relates to the experience you had with the Jetpack carousel on mobile prior to the #18720 changes, or to the experience that you have on mobile when using other photo related apps in general? Just wanting to clarify if we have made the experience of using the carousel worse with #18720 and we need to revert something,  or if it is case of making further improvements on these changes.

**Comment by sdixon194** [comment]
@glendaviesnz I did some more testing on my android phone running Chrome and noticed that it seems in the new release, there's a "dead zone" in the middle of the screen where swiping gets kind of messed up or doesn't work at all - probably to allow for the pinch zoom, but I can see how this leads to increased "clunkiness":

https://user-images.githubusercontent.com/33553323/109521446-5163e780-7a7b-11eb-9eb7-46a7befec500.mp4

This doesn't occur in the current release prior to #18720, I can swipe anywhere rapidly without an issue and consistently scroll through the images:

https://user-images.githubusercontent.com/33553323/109521552-6f314c80-7a7b-11eb-89c5-6500b3d45f28.mp4

**Comment by glendaviesnz** [comment]
Thanks for the extra detail @sdixon194. Copying @sgomes in as he is also doing some work on carousel at https://github.com/Automattic/jetpack/pull/18858

**Comment by sgomes** [comment]
Thanks for looping me in, @glendaviesnz!

**Comment by apeatling** [comment]
This will be fixed in https://github.com/Automattic/jetpack/pull/20107
