### ISSUE TITLE
Masterbar: Unnecessary db write on every front-end page load

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#18949]
It looks like `wp_jetpack_admin_menu_link_destination` gets updated on every page load when `use_wp_admin_links` from the connected user's data is an empty string.

#### Steps to reproduce the issue

1. Load the front-end of your WoA test site.
2. Click on "Debug" in the toolbar
3. Click on "Queries" in the sidebar navigation
4. Looks for entries mentioning `wp_jetpack_admin_menu_link_destination`.

#### What happened instead

`UPDATE `wp_usermeta` SET `meta_value` = '' WHERE `user_id` = USER_ID AND `meta_key` = 'wp_jetpack_admin_menu_link_destination'`

https://github.com/Automattic/jetpack/blob/9a65c4bb54eb4f2ffdf6b970c05242f2e4ee4a18/projects/plugins/jetpack/modules/masterbar/masterbar/class-masterbar.php#L112

This check returns true for empty values, should it be a `! empty()` check instead?

Reading through [`update_metadata()`](https://developer.wordpress.org/reference/functions/update_metadata/) (the underlying update function), it's not clear to me if it takes unchanged values into account. We might have to do that ourselves.

See https://github.com/Automattic/jetpack/pull/18548

**Comment by mmtr** [comment]
Turns out this is caused by a bug in Core: https://core.trac.wordpress.org/ticket/22192. `update_metadata` compares the previous value with the new value to avoid an unnecessary update, but it does not check correctly falsey/empty values.
