### ISSUE TITLE
Twitter Block: Unroll - Have More Specific Verification Notices

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#18943]
> Unrolling Twitter threads can cause the permission banner to be shown multiple times. The banner also has no context for which Twitter thread or block it’s referring to.

![image-5-4](https://user-images.githubusercontent.com/33553323/109189720-531f6980-7762-11eb-988c-89953d646758.png)

When someone is embedding and unrolling multiple Twitter threads on the same page, the verification notice appears each time a new block is unrolled.

We can improve the verification notices by having more specific messaging, such as from which account the tweet is from, and then setup a way to auto-dismiss the notices to prevent clutter. Specificity also helps the user know the issue may exist on multiple blocks.'

**Additional Context**

p8oabR-Co-p2#comment-5037

**Comment by jeherve** [comment]
Closing since the feature is no longer available.
