### ISSUE TITLE
Disabling JP Gutenberg does not Disable all JP Gutenberg features

### ISSUE THREAD

**Issue by tomjn** [Automattic/jetpack#18958]
#### Steps to reproduce the issue

1. Add the following to a theme or plugin: `add_filter( 'jetpack_gutenberg', '__return_false' );`
2. Load the block editor
3. Inspect the registered formats and the formatting toolbar

#### What I expected

I expected that disabling jetpack gutenberg features would disable jetpack gutenberg featurees

#### What happened instead

Blocks were disabled but formats were not. `wpcom/justify` and `wpcom/underline` remained, in addition to the wp.com block editor library and module. I did not enable this in settings, and it's served from a remote server too. In particular `wpcom-block-editor-default-editor-script` is enqueued, it should not have been enqueued.

**Comment by tomjn** [comment]
I had to rely on this code to eliminate the scripts, though there are still parts of that module that are problematic:

```php
add_filter( 'jetpack_gutenberg', '__return_false' );

if ( class_exists( 'Jetpack_WPCOM_Block_Editor' ) ) {
        $jpwpcombe = Jetpack_WPCOM_Block_Editor::init();
        remove_action( 'enqueue_block_editor_assets', [ $jpwpcombe, 'enqueue_block_editor_assets' ], 9 );
        remove_action( 'enqueue_block_assets', [ $jpwpcombe, 'enqueue_block_assets' ] );
        remove_action( 'mce_external_plugins', [ $jpwpcombe, 'add_tinymce_plugins' ] );
        remove_action( 'block_editor_settings', 'Jetpack\EditorType\remember_block_editor' );
        remove_action( 'login_init', [ $jpwpcombe, 'allow_block_editor_login' ] );
        remove_action( 'enqueue_block_editor_assets', [ $jpwpcombe, '' ] );
}
```

I would note that this site will never be edited using the wp.com editor (it wouldn't even make sense to do so), and does some rather questionable things with the sites cookies, there needs to be an off button

**Comment by jeherve** [comment]
Good catch. This is definitely something where we should short-circuit early when Jetpack's block editor functions are disabled.
