### ISSUE TITLE
Food Menu quick edit does not work

### ISSUE THREAD

**Issue by webmandesign** [Automattic/jetpack#18957]
#### Steps to reproduce the issue

1. First you need to use a theme that supports Nova Restaurant module, such as [Auberge theme](https://wordpress.org/themes/auberge/).
2. Create at least 2 food menu items under **Food Menus** admin section.
3. In admin, in **Food Menus &rarr; Menu Items** drag a menu item and reorder it. This works fine.
4. On the same screen, when hovering a menu item, enable _"Quick Edit"_ and try to change status to something else. This does not work as the whole item row is treated as draggable, effectively preventing any inline editing.

(BTW, I think [you know about the issue already](https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/modules/custom-post-types/nova.php#L25).)

#### What I expected

It should be possible to edit food menu items inline using quick edit.

#### What happened instead
Instead, a drag behavior is triggered preventing the quick edit.

**Comment by leogermani** [comment]
> (BTW, I think you know about the issue already.)

I think that comment refers to the fact that the row breaks after you save the edit. Here's how it looks:

![Captura de Tela 2021-03-02 às 11 22 11](https://user-images.githubusercontent.com/971483/109662301-ab32e300-7b49-11eb-86c2-518101ae45af.png)

I think this deserved an issue of its own
