### ISSUE TITLE
calls to class.jetpack-json-api-get-comment-backup-endpoint.php generating error

### ISSUE THREAD

**Issue by CmputrAce** [Automattic/jetpack#18965]
#### Steps to reproduce the issue

1. call class.jetpack-json-api-get-comment-backup-endpoint.php
2.
3.

#### What I expected
I don't know, to tell you the truth

#### What happened instead
a php_errorlog file is created in the folder (public_html/wp-content/plugins/jetpack/json-endpoints/jetpack/) with this error:
[28-Feb-2021 15:49:38 UTC] PHP Fatal error:  Uncaught Error: Class 'Jetpack_JSON_API_Endpoint' not found in /home/customer/www/c-aces.com/public_html/wp-content/plugins/jetpack/json-endpoints/jetpack/class.jetpack-json-api-get-comment-backup-endpoint.php:3
Stack trace:
#0 {main}
  thrown in /home/customer/www/c-aces.com/public_html/wp-content/plugins/jetpack/json-endpoints/jetpack/class.jetpack-json-api-get-comment-backup-endpoint.php on line 3

I noticed that this file was being directly called from France, Canada, US, and Monaco this morning, so I renamed it in case there is a leak.

**Comment by jeherve** [comment]
Thanks for the report. Calling the file directly won't really be helpful to anyone, hence the error, but it would indeed be fine for Jetpack to short-circuit that kind of direct access. We're tracking this in #3056.
