### ISSUE TITLE
Download original file format when downloading an image from a browser

### ISSUE THREAD

**Issue by susanjanec** [Automattic/jetpack#18963]
#### Is your feature request related to a problem? Please describe.
It appears when an image is downloaded from a user's site on Firefox it appears to download as a webP file format instead of the original file type due to Photon CDN settings. On Chrome it appears to download as the original file type. This makes it vary across browsers and user settings.

#### Describe the solution you'd like
Be able to download the image by going to "Save Image as" and download with the original file type across all browsers.

#### Describe alternatives you've considered
Using the Chrome browser instead of Firefox browser, but it can be an inconvenience to those using the Firefox browser or any other browser that automatically saves as a webP file format.

#### Additional context

None

**Comment by jeherve** [comment]
I'm afraid that's something that would need to be handled by the browser directly. This is not something we have control over in Jetpack. Our only option would be to not deliver WebP images in Firefox, but that would negate some of the performance improvements WebP provides.

This may be something worth reporting to the Mozilla team, if that hasn't been suggested already:
https://bugzilla.mozilla.org/home
