### ISSUE TITLE
Jetpack_Data deprecation issues

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#18977]
**Note: this may very soon be addressed in a new release of the WooCommerce Shipping & Tax plugin**

In #18812, we got rid of the deprecated `Jetpack_Data` class. This is causing issues for plugins that still rely on the class, such as WooCommerce Shipping & Tax:
https://github.com/Automattic/woocommerce-services/blob/8d05b1f2d23483d142fe799e537664b5e6acbec5/classes/class-wc-connect-nux.php#L315

The problem is, we were not outputting a big deprecation notice, so that deprecation probably flew under the radar for all these years.

*******

Potential solutions:

- A WooCommerce Shipping & Tax to get rid of the deprecated code https://github.com/Automattic/woocommerce-services/pull/2346
- A Jetpack point release to bring the class back.
- Both?

**Comment by jeherve** [comment]
Reports:
- p1614700936209600-slack-C3GP81E05 
- p1614699388293500-slack-C3NCP7ZJ6
- p1614703679083300-slack-CU6SYV31A

**Comment by tbradsha** [comment]
25409975-hc

**Comment by happychait** [comment]
19473560-hc

**Comment by carladoria** [comment]
3786924-hc

**Comment by rwaynick** [comment]
Adding 3787204-zen and 3786946-zen so that I can follow-up once it's resolved.

**Comment by wpericam** [comment]
28131980-hc

**Comment by jessLundie** [comment]
28132279-hc -> 3787505-zen

**Comment by fevered** [comment]
3787205-zen

**Comment by jessLundie** [comment]
26706439-hc -> 3787549-zen

**Comment by jeherve** [comment]
**The problem has now been fixed on Atomic sites**. For folks running the self-hosted version of Jetpack and WooCommerce Shipping & Tax, the WooCommerce Shipping & Tax plugin will be updated soon to fix this issue.

**Comment by sbathompson-he** [comment]
Zen - 3787186 & 3786936

**Comment by tbradsha** [comment]
@jeherve I'm still seeing this on my end despite clearing my cache. Anything else that needs to be done?

**Comment by desnum** [comment]
Another case here 28133794-hc where the issue still persists on an Atomic site

**Comment by ash1eygrace** [comment]
The issue is persisting on an AT site after the temporary fix above. 28132059-hc > 3787722-zd

**Comment by happychait** [comment]
I still see the issue on my customer's site too.

**Comment by CompChris** [comment]
11417480-hc Atomic problem here as well

**Comment by desnum** [comment]
Another case: 17852724-hc

**Comment by dani-elo** [comment]
Adding these tickets to notify the users when the issue is fixed.

3787787-zen --> The issue is persisting on an AT site after the temporary fix above.
3787800-zen --> Self hosted

**Comment by frosso** [comment]
[WooCommerce Shipping & Tax](https://wordpress.org/plugins/woocommerce-services/) version 1.25.8 has been released with a fix.

**Comment by danjjohnson** [comment]
We have a report in 3787724-zen that after updating to v1.25.8, the option for "No, I will enter prices exclusive of tax" remains grayed-out, and the following errors are shown:

```
The plugin generated 263 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

Warning: Use of undefined constant JETPACK_MASTER_USER - assumed 'JETPACK_MASTER_USER' (this will throw an Error in a future version of PHP) in /wp-content/plugins/woocommerce-services/classes/class-wc-connect-nux.php on line 305

Warning: Cannot modify header information - headers already sent by (output started at /wp-content/plugins/woocommerce-services/classes/class-wc-connect-nux.php:305) in /wp-includes/functions.php on line 6360

Warning: Use of undefined constant JETPACK_MASTER_USER - assumed 'JETPACK_MASTER_USER' (this will throw an Error in a future version of PHP) in /wp-content/plugins/woocommerce-services/classes/class-wc-connect-nux.php on line 305

Warning: Cannot modify header information - headers already sent by (output started at /wp-content/plugins/woocommerce-services/classes/class-wc-connect-nux.php:305) in /wp-admin/includes/misc.php on line 1310

Warning: Cannot modify header information - headers already sent by (output started at /wp-content/plugins/woocommerce-services/classes/class-wc-connect-nux.php:305) in /wp-includes/pluggable.php on line 1296
```

Is this related to the same issue?

**Comment by jeherve** [comment]
@danjjohnson I believe this is tracked here:
185-gh-Automattic/woocommerce-shipping-issues

I'll close this issue.
