### ISSUE TITLE
Protect: Blocking local installs when pulling from live site.

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1897]
We have a user reporting that when pulling their site in through WP DB Migrate Pro to their local instance, they get blocked by Jetpack Protect.  The block shows that `127.0.0.1` has been blocked.

A few questions: 
1. Should `127.0.0.1` always be whitelisted for cases like this?
2. What's the best procedure for syncing databases when using protect to make sure you don't get blocked?  making sure the local install always has development mode enabled?

**Comment by jeherve** [comment]
Also reported here:
https://twitter.com/Vidyut/status/585360880977608704

**Comment by jeherve** [comment]
Also reported here:
https://twitter.com/elishaterada/status/585133950407815168

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/jetpack-problem-with-cloning?replies=1&view=all
