### ISSUE TITLE
Search: Add note in customizer for the expanded and images

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#18983]
**Currently:**

With the release of Jetpack 9.5 is the ability to display images within search results. However, there's no indication that the expanded view will display images (the minimal view does not display images).

![Screen Shot 2021-03-02 at 3 30 34 PM](https://user-images.githubusercontent.com/214813/109711397-d4b13600-7b6c-11eb-814a-72566006d44e.png)

Proposed:

1) Add "shows images" to the dropdown in parenthesis next to "Expanded"
2) Add a line in the description that communicates that the expanded view will show featured images of posts and pages.

![Screen Shot 2021-03-02 at 3 32 09 PM](https://user-images.githubusercontent.com/214813/109711602-0924f200-7b6d-11eb-9682-15ad0a1eeded.png)

Thoughts? @jsnmoon @bluefuton

**Comment by jsnmoon** [comment]
This feels like a pretty straightforward solution 👍

**Comment by gibrown** [comment]
Related to this... could we add a link from this customizer panel to where the filters get configured in the customizer. I think a link like `/wp-admin/customize.php?autofocus[section]=sidebar-widgets-jetpack-instant-search-sidebar` will do it. This should help with cases where folks haven't configured their filters.
