### ISSUE TITLE
Search: Multiple URL polyfills in use

### ISSUE THREAD

**Issue by sgomes** [Automattic/jetpack#19003]
As far as I can tell, there are multiple `URL` polyfills in use in search. There's both the `url-polyfill` package, which is being used in the main bundle, as well as the `core-js` URL polyfill, which is being included in the IE 11 polyfill chunk.

![image](https://user-images.githubusercontent.com/409615/109849172-fa137200-7c48-11eb-8551-cc7875ff0296.png)

Is this expected? I don't see any reason to include a polyfill anywhere outside of IE 11, given [the great support URL has](https://caniuse.com/url).

**Comment by jsnmoon** [comment]
Thanks for the report, @sgomes! We intended to remove `url-polyfill` with #18506, but it looks like we accidentally omitted that change. We'll spin up a PR for this shortly.

**Comment by sgomes** [comment]
Woohoo, thank you for the quick fix, @jsnmoon! 👍
