### ISSUE TITLE
Calypsofied WP-Admin when accessing block editor from WordPress.com

### ISSUE THREAD

**Issue by bindlegirl** [Automattic/jetpack#19039]
#### Steps to reproduce the issue

1. Go to any block editor page from WordPress.com dashboard (post, testimonial, portfolio)
2. The page gets redirected to WP-Admin and loads the block editor
3. On exiting the editor Calypsofied WP-Admin is loaded

I'm not sure if this is expected, but when I was testing the Nav Unification I got slightly different behavior when accessing block editor for posts (but not testimonials and portfolio items). With NU, the block editor for posts opens in the WordPress.com dashboard, and when you leave it you go back to the WordPress.com dashboard.

Should the Calypsofied WP-Admin be removed?

**Comment by jeherve** [comment]
> Should the Calypsofied WP-Admin be removed?

I'm not quite sure where this stands on our roadmap. @obenland Do you have more information about this, by any chance?

**Comment by jeherve** [comment]
@bindlegirl To clarify, was this with a Jetpack, Atomic, or WordPress.com simple site?

**Comment by bindlegirl** [comment]
This is my test Jetpack site. When exiting the block editor (that I accessed through Calypso) I see this: 

![Imagelink:https://d.pr/i/KXFTCY](https://d.pr/i/KXFTCY+)

**Comment by jeherve** [comment]
Ah, I see. that is the expected behaviour; Calypsoify is enabled when nav-unification isn't enabled, and when you start editing custom post types from Calypso.

**Comment by obenland** [comment]
> Do you have more information about [Calypsofied WP-Admin being removed], by any chance?

I do! After wrapping up their current project this week, Explorers will pick that work back up starting next week!
