### ISSUE TITLE
Blocks: conflict between Gutenberg 10.1.0 and multiple Jetpack blocks

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#19038]
The issue is best described in this Gutenberg PR: 

https://github.com/WordPress/gutenberg/pull/29491

The problem is currently visible on all sites running the most recent version of Gutenberg (10.1.0, released 2 days ago) and Jetpack. The issue is already fixed in Gutenberg's `master`, and is currently slated to be pushed out with Gutenberg 10.2.0.

In Jetpack, the Gutenberg ends up impacting multiple blocks: 

- [x] Podcast player #19036
- [x] Latest Instagram Posts #19034
- [x] Opentable #19043

#### Steps to reproduce the issue

1. Start with a site running the Jetpack plugin and the most recent version of the Gutenberg plugin, 10.1.0
2. Go to Posts > Add New
3. Try to insert any of the blocks above.
4. Notice the editor crashing.

**Internal references**

- p1614912413220000-slack-C02A41GCS
- p1614895798108900-slack-CBTN58FTJ
- p1614929521146100-slack-C45SNKV4Z
- p1614928145004300-slack-CBG1CP4EN
- p1614930165108900-slack-CJS75TX3R

**Comment by pablinos** [comment]
I've just created this fix for Gutenberg, which should handle all uses of `noticeOperations` WordPress/gutenberg#29582

**Comment by jeherve** [comment]
@pablinos Do you think we can close this now that this will be handled in Gutenberg directly?

**Comment by pablinos** [comment]
Yeah I think so. We've merged all the fixes too.
