### ISSUE TITLE
Can't connect Jetpack v9.5 on Opera 74.0.3911.203 

### ISSUE THREAD

**Issue by StefMattana** [Automattic/jetpack#19037]
When trying to connect Jetpack to my site on Opera, I am prompted to login to my WordPress.com account. 

<img width="824" alt="Screenshot 2021-03-05 at 07 30 52" src="https://user-images.githubusercontent.com/11662998/110082040-bcb3ff00-7d84-11eb-98e2-5ef999148354.png">

Upon doing it, a new pop-up window opens where I can enter my login details, but after doing it correctly nothing happens. I land again on the very same page above. 

I'm running Jetpack v9.5 and I use macOS 11.2.1

I tried to reconnect Jetpack through different browsers and it works. I tested this as a user in the forums reports a similar problem on Opera v74.0.3911.160:  https://wordpress.org/support/topic/connecting-fails-via-opera-bug/

I asked the user to provide more information when possible and to follow this thread.

**Comment by jeherve** [comment]
Thank you. It may be because Opera doesn't handle third-party cookies like other browsers, and behaves more like Safari, where we've disabled in-place connection. We may have to do the same for Opera.

**Comment by jeherve** [comment]
cc @sergeymitr What's your take on this?

**Comment by NekoJonez** [comment]
Hi there, I'm the user from the forum thread mentioned in OP's first post. 

Sadly enough, due to me having to connect JetPack ASAP on a live website, I totally forgot to take screenshots. Apologies for that. 

To describe what happened is that when I got the pop-up and logged in... The pop-up closed like a flash when it started the auth process. Even when I disabled all plugins or built in features that are blocking trackers and such. Same issue.

**Comment by jeherve** [comment]
@NekoJonez Thanks for the additional details. I suspect the issue is similar to what we fixed a while back for the Safari browser, in #13550.

**Comment by NekoJonez** [comment]
You are more then welcome man! The fewer issues there are in the plugin the better. ;)

**Comment by kraftbj** [comment]
Tested and confirmed the bad behavior. Third-parties strike again.

**Comment by sergeymitr** [comment]
> cc @sergeymitr What's your take on this?

Sorry @jeherve, somehow missed the ping.

It looks like @kraftbj has fixed that already, but I'm going to research it anyway to see why the auto-fallback to Calypso didn't happen.

**Comment by kraftbj** [comment]
@sergeymitr Thanks! It would be great to know why the auto-fallback didn't work.
