### ISSUE TITLE
Soft crop thumbnails

### ISSUE THREAD

**Issue by geoffak** [Automattic/jetpack#1904]
I think it would be great if Related Posts gave us the option to soft crop thumbnails, as an alternative to hard cropping.  These thumbnails could then be positioned in a clickable 350x200 container, which would become the hyperlink for that post.

My use case is that my featured images come in many different sizes.  As a result, they end up getting cropped in odd places.  This looks particularly bad when there's text in the image, because the text gets cut off.

I've attached two images from my blog.  The first one shows what Jetpack displays.  The second one is from the Contextual Related Posts plugin, which shows how this could be implemented.

![jetpack-related-posts](https://cloud.githubusercontent.com/assets/1308736/6953165/4cbc4512-d87c-11e4-8c29-767e8063e5e3.png)

![contextual-related-posts](https://cloud.githubusercontent.com/assets/1308736/6953174/5c39e9fe-d87c-11e4-9245-0fc1649b66aa.png)

**Comment by blix1** [comment]
I too am having this problem & this thread seems to be the only reference I can find. The automatic hard cropping is making the images illegible. 
The second image examples above (just the images, not the layout or styling) posted by Geoffak are exactly what I need, which I guess is soft cropping? Is there anyway to achieve this? 

Attached is an example of one of my pages. I'm using this for a catalogue of lighting products. I just need the images to resize so users can see the whole thing (as Geoffak shows above)
![jetpack-crop-example](https://cloud.githubusercontent.com/assets/13150120/8476280/d7b1c6d2-20b7-11e5-93e3-ec8d2064c7d2.jpg)

Thanks in advance for your time.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
