### ISSUE TITLE
Instant Search: consider replacing `axios`

### ISSUE THREAD

**Issue by sgomes** [Automattic/jetpack#19041]
`axios` is a 13KB (4.5KB gzipped) library, currently taking up around 10% of the main bundle size in Instant Search. It's only used [in one location](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/search/instant-search/lib/api.js#L328). As far as I can tell, it was primarily picked due to the ability to abort ongoing requests, unlike the native `fetch` API (at least in the early days).

Nowadays, the `fetch` API has support for this through `AbortController`/`AbortSignal`, so this could be an option for reimplementing with native APIs. We'd need to make sure they're polyfilled, of course.

The other option is to use a plain old `XMLHttpRequest` and its `abort()` (which is what `axios` uses under the hood), potentially wrapping it all up in a small lib with a nice Promise-based API.

I'm happy to take on that work, but I'd love to hear more on whether I'm missing anything, and what you think the best approach would be!

**Comment by bluefuton** [comment]
cc @jsnmoon as you worked on implementing the request cancellation.

**Comment by jsnmoon** [comment]
@sgomes: I would love to see `axios` replaced with either option you've presented. I vote for whichever would be easier to maintain!

**Comment by sgomes** [comment]
Done in #19186!

I opted for `fetch` with `AbortController`/`AbortSignal`, since this is standard functionality built into each browser, and since it maps really well to the approach that was already in use with `axios`. It shouldn't result in any maintenance work, unless I accidentally introduced a bug 😄 

Once we no longer support IE 11, it's also trivial to drop the polyfills by just changing the `webpack` config.
