### ISSUE TITLE
Infinite scroll event or body class

### ISSUE THREAD

**Issue by pixedelic** [Automattic/jetpack#1907]
Is there a way to detect when posts are loading? I mean: I would like to add my personal loader via CSS or jQuery, make it appear during post loading and remove it on `post-load` event, but the only trigger I can use is `post-load` that detects when posts are already loaded, and the body class `infinity-success` isn't really useful in this case, since it has almost the same role, if I've understood correctly. There isn't an event that detect when posts are starting loading... or am I missing something?

Thank you in advance. Manuel :-)

**Comment by jeherve** [comment]
Could you follow the instructions here to load your own spinner, and let me know if you still experience issues?
https://wordpress.org/support/topic/replace-infinite-scroll-loader?replies=3&view=all

Thanks!

**Comment by pixedelic** [comment]
Thank you very much... I'll try to understand how to work, even if at a first sight it doesn't seem what I was looking for, but maybe I'm missing something. I would like to use the infinite scroll that starts loading new posts when the user scroll to the end of the page, without clicking any button of course. I admit I found this solution a little hard to understand, but I'll make some tests. Thank you for kind reply, as always. Manuel :-)

**Comment by pixedelic** [comment]
However I think I can only style the default loader, without tracking anything and keep the life easier :-)
