### ISSUE TITLE
Latest Instagram Posts: add support for image Lazy Loading

### ISSUE THREAD

**Issue by rsmith4321** [Automattic/jetpack#19086]
#### Steps to reproduce the issue

Add instagram latest post block

#### What I expected

Images should use loading="lazy" like other images in wordpress

#### What happened instead
Images bypass browser lazyloading and load on first page load

**Screenshots**

**Comment by jeherve** [comment]
That's a good suggestion, thank you. It would be nice if we supported both WordPress Core's Lazy Load feature as well as Jetpack's Lazy Images implementation. 
To do so, we may also need to add `width` and `height` attributes to the images currently displayed by the block.

**Comment by rsmith4321** [comment]
I just wanted to mention again if you could please implement this easy fix! After the latest Jetpack update I need to edit the code again.
