### ISSUE TITLE
Instant Search: Search modal is opened by default in IE11

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#19100]
#### Steps to reproduce the issue

1. Visit a site that uses Instant Search in IE11.
2. As the page finishes loading, the Instant Search modal will be opened by default, even if you have not searched for anything.

**Comment by bluefuton** [comment]
Confirmed in Browserstack. The `?s=` gets immediately appended to the URL on load, and the modal is opened.

**Comment by bluefuton** [comment]
Leaving my notes here for @jsnmoon *hands baton*

I tracked it down to the `onInput` handler for the input in `SearchBox`. You can add some debug to the `setSearchQuery` action to see it happen.

In most browsers, we see a single `setSearchQuery` to `null` when the page loads:

<img width="1149" alt="Screen Shot 2021-03-10 at 14 10 10" src="https://user-images.githubusercontent.com/17325/110560300-a1912700-81aa-11eb-82c5-e6ceec1a3a4a.png">

In IE11, the `onInput` is unexpectedly fired when the page loads, which leads to `setSearchQuery` being called with the value `""` (which now opens the search modal).

<img width="499" alt="Screen Shot 2021-03-10 at 14 09 44" src="https://user-images.githubusercontent.com/17325/110560370-bf5e8c00-81aa-11eb-8282-fbc300ff0839.png">

(The forEach error does not seem related but bears further investigation - related to querySelectorAll calls I suspect.)

**Comment by jsnmoon** [comment]
I've discerned the cause: IE11 immediately fires an onChange event if the input placeholder contains a Unicode character. Guess what our placeholder for the search input includes?

`…` <- This.
