### ISSUE TITLE
Instant Search: closing modal with 'Esc' fails when modal was loaded with page

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#19125]
#### Steps to reproduce the issue

1. Go to a site with Instant Search enabled and specify a search in the query string, like `?s=sloth`.
2. Wait for the modal to load, and press Esc to close the modal.

#### What I expected
The modal closes when I press Esc.

#### What happened instead
The modal does not close when I press Esc.

It does still work if I land on the page then open the search modal by entering search text or clicking 'Search', so this is a bug related to the opening of the modal on page load.

**Comment by jsnmoon** [comment]
Funnily enough, clicking on the close overlay button works as expected.

**Comment by bluefuton** [comment]
Indeed it does. Just affects the keypress 🤷‍♂️
