### ISSUE TITLE
Subscriptions: Allow subscribing to a particular category

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#1916]
In 2147348-t the user explains that they have a multilingual blog, and the posts use a different category per language. The user suggested allowing the use of a "category" parameter in the shortcode or in the widget, to allow subscriptions only to a particular category. This was mentioned by someone in #757 but it was worth making a separate enhancement request for it.

**Comment by ecobux** [comment]
We noticed now that we have the same issue with automatic sharing to social media via Jetpack. Here, too, it would be awesome to keep the languages (i.e. a subset of categories) separate when posts get promoted to social media. (We have different Facebook pages and Twitter accounts matching the languages of the blog.)

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/subscribeunsubscribe-by-category-1

**Comment by bethnicol** [comment]
not sure if this is the same request, or different:  would be nice to be able to exclude one or more categories from being sent out to subscribers. I haven't found a way to do that either.

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/double-new-post-email-notification-with-polylang?replies=1&view=all

**Comment by richardmtl** [comment]
also requested in 2262073-t

**Comment by richardmtl** [comment]
Kind of requested here: 2278297-t ; subscribe to all *but* one category.

**Comment by luisrull** [comment]
I'd love to have "select categories" feature. Any chance to have it in the near future?

**Comment by beaulebens** [comment]
We don't support this on WordPress.com because it's never received enough interest. If people want to provide more granular/specialized subscription services, then they should probably look into other email-subscription plugins.
