### ISSUE TITLE
Search: Polyfill object-fit styling for IE11

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#19172]
IE11 currently doesn't support [object-fit styling](https://caniuse.com/object-fit), which we intend to use with our new product layout.

Potential resource: https://www.stevefenton.co.uk/2019/09/fixing-css-object-fit-for-internet-explorer/

**Comment by bluefuton** [comment]
@jsnmoon is this still needed given the different approach we ended up using for the product layout?

**Comment by jsnmoon** [comment]
Yes, we still use `object-fit` with the new product layout due to using `img` elements instead of `div`s. We now use `object-fit` with the expanded layout as well.

**Comment by kraftbj** [comment]
We will be deprecating IE 11 support this summer and thus are wontfix'ing IE 11 issues now. See p1HpG7-c8n-p2
