### ISSUE TITLE
SVN tag 9.5.1 contains version "9.5" on WP.org

### ISSUE THREAD

**Issue by szepeviktor** [Automattic/jetpack#19177]
#### Steps to reproduce the issue

See https://plugins.trac.wordpress.org/browser/jetpack/tags/9.5.1/readme.txt#L4
How come that version 9.5 is tagged 9.5.1?

Properly versioned in https://plugins.trac.wordpress.org/browser/jetpack/tags/9.5.1/jetpack.php

---

BTW Tagging here on GitHub is not part of the release process 😿 
https://github.com/Automattic/jetpack/tags

@jeherve Please advise.

**Comment by szepeviktor** [comment]
> BTW Tagging here on GitHub is not part of the release process 😿

Answere: Here it is https://github.com/Automattic/jetpack-production/releases

**Comment by szepeviktor** [comment]
>  How come that version 9.5 is tagged 9.5.1?

:) Answer: You don't have viktor onboard to manufacture human-checking robots 🤖🤖🤖

**Comment by jeherve** [comment]
> How come that version 9.5 is tagged 9.5.1?

9.5.1 is not considered the latest stable, hence why it was not set to be the stable tag on WordPress.org:
https://wordpress.org/plugins/jetpack/
![image](https://user-images.githubusercontent.com/426388/111271610-ba2d9100-8631-11eb-87c4-e8f4363e3f30.png)

As you discovered on the release page, 9.5.1 is marked as "internal release":
https://github.com/Automattic/jetpack-production/releases/tag/9.5.1

I hope this clarifies things a bit.

**Comment by szepeviktor** [comment]
I see!! 👀 

![kép](https://user-images.githubusercontent.com/952007/111272747-4d1afb00-8633-11eb-9f98-6a6ea93cce94.png)

**Comment by szepeviktor** [comment]
BTW WP-Packagist recognizes the tag and Composer installs v9.5.1
https://wpackagist.org/search?q=jetpack&type=plugin&search=

**Comment by jeherve** [comment]
That's alright I think. It doesn't hurt to install that version of Jetpack on your site. It's just that the changes it includes were fixing issues that were impacting a small number of sites, so did not warrant prompting an update for everyone using the plugin.
