### ISSUE TITLE
Went to another tab and can't get back to my website page

### ISSUE THREAD

**Issue by ReneeCK** [Automattic/jetpack#19174]
#### What I expected

I opened Google Analytics in a new tab to get my property ID. I expected to come back to my WordPress dashboard where I could enter tracking info.

#### What happened instead
I clicked back to the WordPress tab and was redirected to https://sexwithsocks.reneeck.com/wp-login.php?redirect_to=https%3A%2F%2Fsexwithsocks.reneeck.com%2Fwp-admin%2Fwidgets.php&reauth=1 with the following error (screenshot) returned.
![image](https://user-images.githubusercontent.com/80725325/111234820-c67c0480-85c5-11eb-881f-fb858ece05ba.png)

When I remove the tracking info and simply use https://sexwithsocks.reneeck.com/wp-login.php I get this:
![image](https://user-images.githubusercontent.com/80725325/111235027-368a8a80-85c6-11eb-86f4-9169912376ba.png)

**Screenshots**

**Comment by jeherve** [comment]
You seem to be running a very old version of Jetpack. Could you update to the most recent version of the plugin, version 9.5? That should solve this issue.
