### ISSUE TITLE
Notice message from staticize_subdomain in localhost breaks loading.gif img tag

### ISSUE THREAD

**Issue by bobbingwide** [Automattic/jetpack#1918]
In my local environment, where `qw` is the name of my localhost and `oikcom` is the WordPress folder, the parameter passed to staticize_subdomain() is:
http://qw/oikcom/wp-content/plugins/jetpack/modules/sharedaddy/images/loading.gif

$exploded_host becomes
`exploded_host(2)  Array
(
    [0] => qw
)`

This leads to a Notice being issued from 
`$name = $exploded_host[ count( $exploded_host ) - 2 ];`
since the index is -1. 

#### Workaround:
* Ensure WP_DEBUG is false - easy
* OR use a different name for the local system - I don't plan on doing that

#### Notes:
* This is a follow on to #1663 
* This is a minor problem

**Comment by bobbingwide** [comment]
Having applied the WP_DEBUG workaround I missed a few Notices from my own code.
So I reset it to true and created a quick patch - testing count( $exploded_host )

Then I realised that the new domain ignores tlds of the form .co.uk, .org.uk and also uk.com
So it'll whitelist wp.uk.com. - a domain that does actually exist
and wp.au.com - which currently doesn't.
Then I realised the flaw in my argument... $name will become uk or au, not wp

Do you want a pull request for this change?

**Comment by jeherve** [comment]
> Do you want a pull request for this change?

Go ahead, we'll be happy to review and merge if it looks good and works.
