### ISSUE TITLE
Jump start prompts to jump start after I've already jump started

### ISSUE THREAD

**Issue by jkudish** [Automattic/jetpack#1920]
Say the title 10x fast ;)

Just kidding... On a more serious note. I installed Jetpack 3.4.1 and activated it, it asked me to jump start, I did (successfully) and then after 2 or 3 seconds it prompted me again (without a button to do so this time):

![screen shot 2015-04-06 at 11 45 28 am](https://cloud.githubusercontent.com/assets/260253/6999608/cbaa0894-dc52-11e4-93db-bef78409b8d6.png)

**Comment by jeherve** [comment]
I believe this was fixed in #1894.
