### ISSUE TITLE
Empty "Jetpack Search Sidebar" title generates a PHP Notice

### ISSUE THREAD

**Issue by szepeviktor** [Automattic/jetpack#19216]
#### Steps to reproduce the issue

1. Enable WP_DEBUG
2. Load any page

#### What happened instead

> PHP Notice: Undefined index: type in wp-content/plugins/jetpack/modules/search/class.jetpack-search-helpers.php on line 181

Setting the title makes the notice go away.

**Screenshots**

![kép](https://user-images.githubusercontent.com/952007/111629451-96b14480-87f1-11eb-8598-9e1dd8f3a919.png)

**Comment by jeherve** [comment]
Thanks for the report.
This should be fixed in the development version of Jetpack, thanks to #17632. The fix will ship with the next major Jetpack update, 9.6.

**Comment by szepeviktor** [comment]
Thank you.
