### ISSUE TITLE
CSSTidy: Shorthand optimisation for padding breaks blocks

### ISSUE THREAD

**Issue by aaronrobertshaw** [Automattic/jetpack#19224]
#### Steps to reproduce the issue

1. On wpcom create a new post and add a group block
2. Select the group block and via the sidebar controls set different top/bottom and left/right margins e.g. 96px 56px;
3. Save the post and reload
4. The block will report a validation error in console. Inspecting the saved post content vs generated you should see that the saved inline styles have been converted to the shorthand format.
5. Repeating the test where the group is inside something like the LayoutGrid block it won't be automatically recovered

#### What I expected
Inline styles added to blocks were honoured and remained untouched so the block doesn't not fail validation.

#### What happened instead
Inline styles were optimised into shorthand format breaking the block.

#### Additional Notes
- This issue will break any block using the spacing block support feature from Gutenberg.
- Appears related to optimisations intended for Custom CSS from the Customizer
- Initial report of the issue: p1616112763110500-slack-CS0SC36SX
- Further discussion: p1616117324116300-slack-CS0SC36SX

**Screenshots**
![OptimisedStylesIssue](https://user-images.githubusercontent.com/60436221/111722006-bbb6bd80-88ac-11eb-8791-b3e1d8c49637.gif)

**Comment by ramonjd** [comment]
I have managed to replicate this while testing the [patterns inserter](https://github.com/Automattic/wp-calypso/pull/50694).

The patterns inserter pulls post body content and renders it to the inserter bar.

Where there is a group block with padding applied we see the invalid block error:

![Mar-26-2021 11-22-10](https://user-images.githubusercontent.com/6458278/112560349-21fc8c80-8e27-11eb-9208-52229204bc75.gif)

Padding applied in the group block spacing controls:

<img width="286" alt="Screen Shot 2021-03-26 at 11 26 48 am" src="https://user-images.githubusercontent.com/6458278/112560367-29bc3100-8e27-11eb-9d48-aceb20b88774.png">

In the editor code view:

```
<!-- wp:group {"style":{"spacing":{"padding":{"top":"10px","right":"10px","bottom":"10px","left":"10px"}}}} -->
<div class="wp-block-group" style="padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px"><div class="wp-block-group__inner-container"></div></div>
<!-- /wp:group -->
```

The save function outputs:

```
<div class="wp-block-group" style="padding:10px;"><div class="wp-block-group__inner-container"></div></div>
```

As a result one we are limited in the way we use spacing when designing blocks.


What's your feeling on priority for this one @aaronrobertshaw @apeatling ?

**Comment by andrewserong** [comment]
Just adding that I think we encountered the same issue in the cover block in: https://github.com/Automattic/blockpatterns/issues/173

**Comment by andrewserong** [comment]
The use of CSSTidy in general might wind up causing us similar related issues. It's been raised in https://github.com/Automattic/jetpack/issues/19669 that it lacks support for CSS variables which could become an issue for us, too.

**Comment by ramonjd** [comment]
Can we close this after D60947-code?

**Comment by andrewserong** [comment]
> Can we close this after D60947-code?

Yes, I believe we can. I just walked through the reported steps again to be doubly sure to confirm it's fixed, and will close it out. We can always re-open / open up follow-ups if we need to.
