### ISSUE TITLE
Publicize: add TSU as a service

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#1923]
requested in t-2147973

https://www.tsu.co/

**Comment by georgestephanis** [comment]
As it's an invite-only service, I'm thinking wontfix this.

I'm also not seeing any documentation on a posting API that publicize could use.

cc: @justinshreve for the final call.

**Comment by justinshreve** [comment]
Agreed on wontfixing this.

**Comment by lezama** [comment]
requested again in t-2174891
