### ISSUE TITLE
Post by Email: Images rejected when sending through Gmail

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1928]
When using PBE from Gmail, no images are accepted (both inline images and images as attachments).  Instead, the following errors show up:
```
Some attachments were rejected from the following WordPress.com Post by Email:
- 229474_503448678786_2231_n.jpg - Invalid response from the Jetpack site
```
Sending the same images in the same emails through another email service like Outlook.com works without any issues.

Tried through 2 different Gmail accounts, one using Google Apps and one without.

**Comment by chaselivingston** [comment]
Also reported in 2147658-t

**Comment by mikeyarce** [comment]
Attachments are also now being rejected through Outlook.com, although originally they were fine, now they are not going through.

**Comment by chaselivingston** [comment]
2152945-t

**Comment by mikeyarce** [comment]
Not an issue, please see https://github.com/Automattic/jetpack/issues/1929 for more details on the real issue.
