### ISSUE TITLE
White background and white text when editing markdown block

### ISSUE THREAD

**Issue by abers** [Automattic/jetpack#19285]
#### Steps to reproduce the issue

1. Create new post
2. Add markdown block
3. Attempt to edit text

#### What I expected

The block to respect my [website's theme](https://constellations.scot/).

#### What happened instead

The block when editing text turns white, which combined with a white font makes it impossible to see anything. When the block does not have focus it respects my theme - and when posted the post respects my theme. It is only when in edit mode and the block has focus that this issue occurs.

![image](https://user-images.githubusercontent.com/11317054/112352347-97028180-8cc2-11eb-9850-270d473e3691.png)

**Comment by basicgm** [comment]
Same issue here although black on black instead.

**Comment by zeitkunst** [comment]
I also have this problem...is there any suggested solution or mitigation?

**Comment by zeitkunst** [comment]
In case others want a solution for this using something like Tampermonkey, this is what I came up with:

```
// ==UserScript==
// @name         Change markdown text color while editing block
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://SITE-NAME/wp-admin/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    function GM_addStyle(css) {
  const style = document.getElementById("GM_addStyleBy8626") || (function() {
    const style = document.createElement('style');
    style.type = 'text/css';
    style.id = "GM_addStyleBy8626";
    document.head.appendChild(style);
    return style;
  })();
  const sheet = style.sheet;
  sheet.insertRule(css, (sheet.rules || sheet.cssRules || []).length);
}



    GM_addStyle ( `
    .wp-block-jetpack-markdown__editor {
        color: #COLOR;
    }
` );
})();
```

Change SITE-NAME and COLOR to what works for you.
