### ISSUE TITLE
Instant Search: Filter options shown as links instead of checkboxes on macOS Safari

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#19295]
#### Steps to reproduce the issue

1. Open Safari on macOS
2. Go to Jetpack Search enabled site, change theme to **twenty twenty** or **twenty twenty one**
3. Search something, check the popup overlay

#### What I expected
Filter options should be shown as checkboxes:

<img width="1064" alt="expected" src="https://user-images.githubusercontent.com/1425433/112425203-8ae9f300-8d9a-11eb-87a9-29c75263c2d9.png">

#### What happened instead
But shown as links:

![image](https://user-images.githubusercontent.com/1425433/112425059-4fe7bf80-8d9a-11eb-907d-bca6303f97b8.png)

**Comment by bluefuton** [comment]
Good find. Seems to be related to the custom styling of checkboxes in those themes, and specifically:

<img width="335" alt="Screen Shot 2021-03-25 at 16 37 34" src="https://user-images.githubusercontent.com/17325/112540763-726bee00-8e17-11eb-9361-a1f8453f0238.png">
