### ISSUE TITLE
Open Graph meta: remove blank fallback og:image

### ISSUE THREAD

**Issue by niallkennedy** [Automattic/jetpack#1931]
Jetpack uses a 200x200 white square as an `og:image` fallback if no suitable image is found. This image meets the [200px minimum requirement of a Facebook Open Graph object](https://developers.facebook.com/docs/sharing/best-practices#images), triggering what appears as offset text within story templates. LinkedIn uses Open Graph protocol as well, causing a similar behavior. Twitter uses Open Graph protocol as a fallback if a `twitter:image` is not present, causing an offset template display as well.
https://github.com/Automattic/jetpack/blob/77629b6de0a3651b5cff0e6139682c0e8d388369/functions.opengraph.php#L236

#### Facebook news.publishes action article object template:
![jetpack-blank-facebook](https://cloud.githubusercontent.com/assets/1100/7036246/e478e0d0-dd46-11e4-8971-242d682799d5.png)

#### LinkedIn:
![jetpack-blank-linkedin](https://cloud.githubusercontent.com/assets/1100/7036247/e47a87fa-dd46-11e4-9c4f-0ed59cb46a27.png)

#### Twitter summary card template:
![jetpack-blank-twitter](https://cloud.githubusercontent.com/assets/1100/7036248/e47b51e4-dd46-11e4-8827-7d09df098dac.png)

Jetpack likely added the feature to stop Facebook's search for a suitable image on the page, and what may have seemed like randomness to the `img` selection process.

Having a blank image vs. no image may or may not positively effect the likelihood the shared story will appear in the ranked Facebook News Feed.

I don't like the blank image. I rather have Jetpack stop emitting the image than need to filter it out at the crawler level.

**Comment by kraftbj** [comment]
The blank image is the last of the last fallback after the blavatar (wp.com only function), the site logo, or the site icon: https://github.com/Automattic/jetpack/blob/master/functions.opengraph.php#L219-241

Alternatively, you can set your own fallback image using
```
add_filter( 'jetpack_open_graph_image_default', 'your_custom_fallback' );
function your_custom_fallback() {
        return 'http://URL-to-your-fallback/image.jpg';
}
```

Is there a different fallback you would suggest? IIRC, we should have something, else FB's debugger will throw an error which can cause issues with automated posting via Publicize.

**Comment by jeherve** [comment]
Closing as `wontfix`, since we've now added more levels of feedback before one gets the blank default image.

**Comment by rubel3200** [comment]
Anyone help me please.
How can I fix this issue 
http://wetdreams.life/author/m44cog/
Notice: Trying to get property of non-object in /home/cluster-sites/4/w/wetdreams.life/public_html/wp-content/plugins/jetpack/functions.opengraph.php on line 79 Notice: Trying to get property of non-object in /home/cluster-sites/4/w/wetdreams.life/public_html/wp-content/plugins/jetpack/functions.opengraph.php on line 83 Notice: Trying to get property of non-object in /home/cluster-sites/4/w/wetdreams.life/public_html/wp-content/plugins/jetpack/functions.opengraph.php on line 85 Notice: Trying to get property of non-object in /home/cluster-sites/4/w/wetdreams.life/public_html/wp-content/plugins/jetpack/functions.opengraph.php on line 86 Notice: Trying to get property of non-object in /home/cluster-sites/4/w/wetdreams.life/public_html/wp-content/plugins/jetpack/functions.opengraph.php on line 87 Notice: Trying to get property of non-object in /home/cluster-sites/4/w/wetdreams.life/public_html/wp-content/plugins/jetpack/functions.opengraph.php on line 288

**Comment by jeherve** [comment]
@rubel3200 Could you try to go to Users > My Profile in your dashboard and fill in the different fields here, especially the Nickname and "Display Name publicly as" fields?

If that does not seem to help, could you let me know if you use any plugins on your site that may change the different user fields or names?

**Comment by rubel3200** [comment]
My user profile
http://prntscr.com/jpeu5j
My plugin list
http://prntscr.com/jpevwb
i have already deactivated the Meks Smart Author Widget Plugin

**Comment by jeherve** [comment]
Could you try to deactivate all other plugins, one at a time, and let us know if you find a conflicting plugin?

**Comment by rubel3200** [comment]
I deactivated all plugin but I am still facing the problem

**Comment by rubel3200** [comment]
When I deactivated the jatpack i won't face any problem

**Comment by jeherve** [comment]
Could you contact us via this contact form so we can run some more tests with you?
https://jetpack.com/contact-support/?rel=support

Thank you.
