### ISSUE TITLE
Sanitize IP headers

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#1934]
So people can't inject their own headers and get back stuff like:

`Your IP (<hola>88.139.175.7) has been flagged for potential security violations...`

**Comment by attritionorg** [comment]
Is this just a silly bug that allows you to inject text into your own response, or can this be used for a reflected XSS attack? i.e. Will it return back full script tags and render them?

**Comment by samhotchkiss** [comment]
Anything injected is only reflected back to you

**Comment by dmchale** [comment]
@samhotchkiss that's still a bad thing though, right?

**Comment by samhotchkiss** [comment]
Only in that you can show things to yourself-- the only time you would see your IP reflected back would be as a logged-out user (who is blocked from logging in), so there's not a risk of malicious code injection
