### ISSUE TITLE
Nav Unification conflicts with Page Optimize plugin on RTL sites

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/jetpack#19340]
#### Steps to reproduce the issue

1. Change the language to RTL one
2. Change the color scheme
3. Visit a WP-Admin page

#### What I expected

The color scheme should change to the one configured and the width to be 270px.
#### What happened instead
The color scheme remains black and Nav width is 160px

The issue is caused by a conflict with Page Optimize plugin on AT and any other site that has the plugin installed. Based on a quick research it seems that it's caused by the CSS concatenate feature of the plugin.

A quick workaround for it is to add `colors,jetpack-admin-menu,admin-bar,dashicons` in the CSS exclude list input located in `Settings > Performance` section

**Comment by obenland** [comment]
We should be able to exclude our handle by filtering `option_page_optimize-js-exclude` and `option_page_optimize-css-exclude`.
https://plugins.trac.wordpress.org/browser/page-optimize/tags/0.5.1/page-optimize.php#L140
