### ISSUE TITLE
Error on plugin installation - Multisite

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1938]
See video for extra details:
https://cloudup.com/cakqZ39EzBm

I was able to reproduce the issue on 2 different multisite networks, both running WP 4.1.1 and trying to install 3.4.1.

Although the error appears, the plugin is in fact network activated.

Reported here:
https://wordpress.org/support/topic/wpmu-install-success-activation-reports-failure-to-install

**Comment by dereksmart** [comment]
Same error in #1846

**Comment by jeherve** [comment]
Marking as duplicate and closing, then, thanks!
