### ISSUE TITLE
Payments Block: cursor can get trapped outside of button

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#19392]
In some situations, the cursor can get trapped in a situation where you cannot type text into the button, but you are not in the parent block either:

https://user-images.githubusercontent.com/426388/113415385-61931d80-93bf-11eb-8d08-452cad733170.mov

Original report: p8oabR-DS-p2#comment-5146

**Comment by rcrdortiz** [comment]
The block seems to be working as expected. Now you can always type text in the block.

https://user-images.githubusercontent.com/1989914/150307890-0c7ea081-2ae7-4872-9274-36305343c1a4.mp4
