### ISSUE TITLE
SEO: Twitter Preview Doesn't Wrap Long Text

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#19396]
#### Steps to reproduce the issue

When adding a meta description to the site and previewing how it appears on various services, Twitter's preview doesn't wrap lengthy text. This issue happens when there is a long, unbroken word (no spaces):

<img width="768" alt="screenshot-on-2021-04-01-at-15-36-43" src="https://user-images.githubusercontent.com/33553323/113422061-1d415680-939a-11eb-9dd0-bb0ccdf88714.png">

Discussion from testing: p8oabR-DS-p2#comment-5149

**Comment by Aurorum** [comment]
PR for this issue in Automattic/wp-calypso#51659. :>
