### ISSUE TITLE
An Option to Attach WP Post Featured Images on Jetpack Tweets

### ISSUE THREAD

**Issue by bizanimesh** [Automattic/jetpack#19395]
Feature request from a user: 

- #3875095-zen

#### Is your feature request related to a problem? Please describe.

> I see established websites get rich Twitter cards on Google which displays 5-6
latest Tweets from their handle. We have one for our website.
>
> Now coming to my concern, sites attaching images on Tweets get their image
displayed on the Google Latest Tweets carousel however, links embedded to display
images don't get shown there.

#### Describe the solution you'd like

> I would love to see a feature (a global option or per post option) where the admin
can choose between attach image automatically from the featured image or embed
them as a link. That can solve this issue. By attaching images on Tweets, we can
display them on Google Search which increases our Tweet clicks to view ratio and
hence more engagement.

#### Additional context

> Our site embedding images from content as a link: https://ibb.co/4S35VfT
>
> Other sites attaching as images: https://i.ibb.co/vDZJYkv/Screenshot-20210402-114909-Chrome.jpg

**Comment by jeherve** [comment]
You can use the `jetpack_publicize_options` filter to change the way Publicize handles media for your site. You can read more about the filter and how to use it here:
https://developer.jetpack.com/hooks/jetpack_publicize_options/

That should help!
