### ISSUE TITLE
Allow filtering of the featured modules

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/jetpack#1939]
Currently it's not possible to filter the featured modules on the main Jetpack admin page grid. These modules:

![screen shot 2015-04-09 at 2 32 09 pm](https://cloud.githubusercontent.com/assets/233434/7067956/fce83ffe-dec6-11e4-98eb-b53f41262262.png)

It would be nice to be able to filter these to target specific audiences on particular installs, e.g. maths students might appreciate Beautiful Math more than many more literarily oriented site owners.

**Comment by jessefriedman** [comment]
As we begin to look at customizing the admin screen for specific use cases this I think would be really helpful.  Even outside the educational space. If I for example run a multisite for a niche like restaurants I'd appreciate greater control over what my users see and when.

**Comment by dereksmart** [comment]
Merged in 3e05077
