### ISSUE TITLE
Payments / Upgrade nudge: Redirect Back to Post on Checkout

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#19404]
>When upgrading / purchasing a plan from a block up-sell in the editor, we need to bring customers back to their post or page that they were editing. Right now, if a customer is editing a post / page in wp-admin, clicks on an up-sell, and buys a Jetpack plan, we then bring them to calypso blue (wordpress.com). That’s very disorienting. In the very least, we need to drop them back off in wp-admin

p8oabR-DS-p2#comment-5199

**Comment by rcrdortiz** [comment]
When upgrading we trigger a WordPress.com checkout flow in a new tab (target blank), https://wordpress.com/checkout/jetpack_security_daily_monthly?site={site that's upgrading}. We are going to need to check if we can somehow instruct the WPCom checkout process where he should redirect to after completing the process, or check if the checkout process uses the PostMessage API to communicate the checkout status to the opener.

**Comment by lukaszwilczakwilnet** [comment]
This task was resolved by another [issue](https://github.com/Automattic/wp-calypso/pull/62021)
