### ISSUE TITLE
Image CDN: Double Download

### ISSUE THREAD

**Issue by chriscoyier** [Automattic/jetpack#19409]
#### Steps to reproduce the issue

1. Use Site Accelerator with "Speed up image load times" on and also "Enable Lazy Loading for images"
2. Load a page with an image above the fold. 

#### What I expected

Single downloads of images.

#### What happened instead

Double download of above-the-fold image.

### Details

<details>
  <summary>HTML Output</summary>
  <pre><code>&#x3C;img width=&#x22;1200&#x22; height=&#x22;600&#x22; src=&#x22;https://css-tricks.com/wp-content/uploads/2021/04/wpn-20210402.jpg&#x22; class=&#x22;article-thumbnail wp-post-image jetpack-lazy-image&#x22; alt=&#x22;&#x22; loading=&#x22;lazy&#x22; data-lazy-srcset=&#x22;https://i0.wp.com/css-tricks.com/wp-content/uploads/2021/04/wpn-20210402.jpg?w=1200&#x26;amp;ssl=1 1200w, https://i0.wp.com/css-tricks.com/wp-content/uploads/2021/04/wpn-20210402.jpg?resize=300%2C150&#x26;amp;ssl=1 300w, https://i0.wp.com/css-tricks.com/wp-content/uploads/2021/04/wpn-20210402.jpg?resize=1024%2C512&#x26;amp;ssl=1 1024w, https://i0.wp.com/css-tricks.com/wp-content/uploads/2021/04/wpn-20210402.jpg?resize=768%2C384&#x26;amp;ssl=1 768w, https://i0.wp.com/css-tricks.com/wp-content/uploads/2021/04/wpn-20210402.jpg?resize=1000%2C500&#x26;amp;ssl=1 1000w&#x22; data-lazy-sizes=&#x22;(min-width: 735px) 864px, 96vw&#x22; data-lazy-src=&#x22;https://css-tricks.com/wp-content/uploads/2021/04/wpn-20210402.jpg?is-pending-load=1&#x22; srcset=&#x22;data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7&#x22; /&#x3E;
</code></pre>
</details>

<details>
  <summary>How it looks in DOM after page loads</summary>
  <pre><code>&#x3C;img width=&#x22;1200&#x22; height=&#x22;600&#x22; src=&#x22;https://css-tricks.com/wp-content/uploads/2021/04/wpn-20210402.jpg&#x22; class=&#x22;article-thumbnail wp-post-image jetpack-lazy-image jetpack-lazy-image--handled&#x22; alt=&#x22;&#x22; loading=&#x22;eager&#x22; srcset=&#x22;https://i0.wp.com/css-tricks.com/wp-content/uploads/2021/04/wpn-20210402.jpg?w=1200&#x26;amp;ssl=1 1200w, https://i0.wp.com/css-tricks.com/wp-content/uploads/2021/04/wpn-20210402.jpg?resize=300%2C150&#x26;amp;ssl=1 300w, https://i0.wp.com/css-tricks.com/wp-content/uploads/2021/04/wpn-20210402.jpg?resize=1024%2C512&#x26;amp;ssl=1 1024w, https://i0.wp.com/css-tricks.com/wp-content/uploads/2021/04/wpn-20210402.jpg?resize=768%2C384&#x26;amp;ssl=1 768w, https://i0.wp.com/css-tricks.com/wp-content/uploads/2021/04/wpn-20210402.jpg?resize=1000%2C500&#x26;amp;ssl=1 1000w&#x22; data-lazy-loaded=&#x22;1&#x22; sizes=&#x22;(min-width: 735px) 864px, 96vw&#x22;&#x3E;</code></pre>
</details>

Screenshot of double download:

<img width="1281" alt="Screen Shot 2021-04-03 at 1 33 17 PM" src="https://user-images.githubusercontent.com/69156/113490767-3244e500-9481-11eb-9745-102eeffc8a25.png">

The confusing part to me is that the 2nd image it downloads is this:
https://i1.wp.com/css-tricks.com/wp-content/uploads/2021/03/wpn-20210312.jpg?resize=300%2C300

Confusing because:

1. That URL doesn't appear anywhere in the HTML originally or after the DOM changes.
2. The size of it is quite small and not used anywhere, so why download it at all?

I'm not 100% sure it's a bug, but it does seem weird.

**Comment by samiff** [comment]
@chriscoyier Are you still able to reproduce this issue? I'm not able to see the double image downloads on my end currently.

**Comment by chriscoyier** [comment]
> @chriscoyier Are you still able to reproduce this issue? I'm not able to see the double image downloads on my end currently.

Yeah seems fine now 🤷‍♀️
