### ISSUE TITLE
AMP: White on white content in Cover Block with predefined colors

### ISSUE THREAD

**Issue by claudiucelfilip** [Automattic/jetpack#19416]
#### Steps to reproduce the issue

1. Activate the WP AMP plugin (at least v2.0.x), with Reader mode enabled
2. Create a new post
3. Add a Cover block and select one of the predefined colors (see screenshot)
4. Make sure to Enable AMP
5. Publish
6. Check the post in AMP (ex. by appending `/amp` to the URL)

#### What I expected
The Cover block in should am should have the selected color as background.

#### What happened instead
The Cover block has a white background, and text. (see screenshot)

**Screenshots**

<img width="480" alt="Screenshot on 2021-04-05 at 14-13-48" src="https://user-images.githubusercontent.com/2749938/113571354-e92a9780-961e-11eb-8ff9-6cbd81259e6e.png">
<img width="480" alt="Screenshot on 2021-04-05 at 14-13-48" src="https://user-images.githubusercontent.com/2749938/113571369-f21b6900-961e-11eb-8bfb-7dddaaa9e1d5.png">

#### Details
When using these predefined colors, a corresponding class (ex. `.has-accent-background-color`)  is added to the cover block element (`.wp-block-cover`) which is defined by the blog's theme.
Because the WP AMP plugin switches to the Legacy Reader theme, these color classes are lost. That's why, choosing a custom color works as expected.

**Comment by jeherve** [comment]
Since the Cover block is a core WordPress feature, that's not something we can help you with here. I would recommend opening an issue about this in the AMP repo:
https://github.com/ampproject/amp-wp/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
