### ISSUE TITLE
Jetpack CLI + Changelog: Auto-add new changelog?

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#19426]
#### Is your feature request related to a problem? Please describe.
After adding a changelog, you always have to `git add` the new file. Couldn't we make that smoother? At least `git add` the new file so the commit can be done without remembering to manually add?

#### Describe the solution you'd like
An automatic git add for the new file.

#### Describe alternatives you've considered
Auto-commit, but that wouldn't work if anything else is staged. If/when we get to `jetpack changelog add` to walk through all impacted projects, want to be sure to commit after them all, but add wouldn't have that problem.

**Comment by jeherve** [comment]
I kinda of like the idea of automatic commit if there is only one new file in a `/changelog` directory, and bailing in other scenarios so the person can do things on their own.

**Comment by sdixon194** [comment]
How's this then for starters? https://github.com/Automattic/jetpack/pull/19436
