### ISSUE TITLE
Carousel: always show the first line of the description

### ISSUE THREAD

**Issue by ricjcs** [Automattic/jetpack#19433]
#### Is your feature request related to a problem? Please describe.
The image title is always shown, regardless of the monitor size and resolution. But the image description is not always shown. For example, on a 14-inch monitor, with 1920x1080 resolution and Chrome with the favorites bar active, the image description is not shown without scrolling down. The user has to scroll down to see the description, but there is no visual information to show that there is a hidden description.

#### Describe the solution you'd like
I would like the first line of the description to always be shown.

If the description is too long, showing the full description may not be a good idea, as it can shrink the image. I think that showing the first line of the description is enough to let the user know that there is a description.

An alternative would be to show an arrow pointing downwards or other type of visual information that would let the user know that there is something else below.

#### Additional context

**Screenshot: there is no visual information to show that there is a hidden description.**
![Captura de ecrã 2021-04-06 131013](https://user-images.githubusercontent.com/11923491/113713899-c2806580-96df-11eb-8c39-a35da4b240e0.jpg)

**Screenshot: scrolling down shows the description.**
![Captura de ecrã 2021-04-06 131056](https://user-images.githubusercontent.com/11923491/113713947-cd3afa80-96df-11eb-8ce8-858cf3ce1b4b.jpg)

**Comment by jeherve** [comment]
Thanks for the contribution. This is currently tracked in #8418. I'll close this issue as duplicate.

**Comment by ricjcs** [comment]
Thank you! I searched but didn't notice that the same proposal already existed.
