### ISSUE TITLE
Image CDN: Option to clear cache

### ISSUE THREAD

**Issue by ricjcs** [Automattic/jetpack#19434]
#### Is your feature request related to a problem? Please describe.
Enabling Image CDN will keep the images in cache forever. Even if the image is deleted from the website, it is cached and indexed in search engines. The user is no control of their own images. The Image CDN service is very good, but because of the images being cached forever I avoid using the feature.

Contacting support and indicating the link of the image to be deleted is the option suggested by JetPack, but it is not a viable option if there are hundreds or thousands of images to be removed.

#### Describe the solution you'd like
I liked an option in the interface to clear the cache.

For privacy reasons, the absence of this feature can be problematic.

#### Describe alternatives you've considered
Cloudflare and other services with similar functionality allow you to clear the cache.

#### In the absence of this feature
When the user activates the option "Speed up image load times", it should be shown that the images will be cached forever. This information is only shown if the user enters the website, a large part of the users will not read the information and know that they will keep the images in cache forever. This information should be shown together with the button.

**Comment by jeherve** [comment]
Thanks for the report. This issue was discussed in #917. I would encourage you to follow the discussion and workarounds that were offered there to find out more.
