### ISSUE TITLE
Debug page: Links are broken for "known issues" support documentation

### ISSUE THREAD

**Issue by lakellie** [Automattic/jetpack#19438]
#### Steps to reproduce the issue

1. Go to Jetpack > Dashboard > Debug
2. Under the `Trouble with Jetpack?` section, click the two links in the first section regarding known issues: `known conflicts` and `list`.

#### What I expected
To be brought to a page with known issues

#### What happened instead
The link is set to https://jetpack.com/redirect/?source=jetpack-contact-support-known-issues&site=kellietestsite.mystagingwebsite.com which then redirects to https://jetpackme.wordpress.com/contact-support/known-issues?site=kellietestsite.mystagingwebsite.com and results in a 404.

#### To fix
It looks like those two links should be updated to link here instead: https://jetpack.com/support/getting-started-with-jetpack/known-issues/

I'm not sure what appending the site to the URL with `?site=kellietestsite.mystagingwebsite.com` is meant to do or if that's necessary to keep.

**Comment by jeherve** [comment]
Good catch! This should now be fixed.
