### ISSUE TITLE
Tiled Gallery block: Images are not optimized.

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#19445]
Because it was better than not seeing images at all, we recently [bypassed Photon use in the Tiled Gallery](https://github.com/Automattic/jetpack/pull/19201) when the site was an Atomic site with the "private" setting on. This allowed the images to be visible by loading the full images directly from the site's media gallery. However, this also means that when small images are all that's needed for a tiled gallery element, the entire full-size image is loaded anyways (causing unnecessary data and time consumption).

Optimizing these images is more complicated that it seems on the surface – @mreishus goes through existing explorations and possible next steps in his [summary of the main issue](https://github.com/Automattic/wp-calypso/issues/41272#issuecomment-811481221).

**Comment by jeherve** [comment]
Related: #18636

**Comment by jeherve** [comment]
This was done in #32598.
