### ISSUE TITLE
Stats not showing weekly or monthly figures

### ISSUE THREAD

**Issue by Anterotesis** [Automattic/jetpack#19455]
After updating Jetpack to 9.6, the stats page on self-hosted WP websites are broken. Clicking on the 'Weeks' or 'Months' tabs doesn't change the graph, which remains displaying the 'Daily' figures. Tested in WP 5.6 and WP 5.7 installs.

#### Steps to reproduce the issue

1. Update Jetpack to 9.6
2. Go to Jetpack > Statistics page
3. Click on 'Weekly' or 'Monthly' tabs.

#### What I expected

Display of graph showing Weekly or Monthly stats.

#### What happened instead

Graph purportedly reloaded (there was a spinner), but numbers displayed wiere Daily.

**Comment by jeherve** [comment]
I was able to reproduce as well. We'll take a look and get this fixed, thank you for the report!
