### ISSUE TITLE
Site Editor Compatibility: Business Hours Block styling issue with open/closed toggle

### ISSUE THREAD

**Issue by andrewserong** [Automattic/jetpack#19463]
In the new site editor in Gutenberg (/wp-admin/admin.php?page=gutenberg-edit-site), there are some styling issues with the Business Hours block when rendered in the site editor.

#### Steps to reproduce the issue

Related to: 256-gh-Automattic/view-design

1. With the Gutenberg plugin active (>=10.4.0-rc1), activate a block-ready theme (like tt1-blocks)
2. In the site editor, insert a Business Hours block into the Footer template part.
3. Observe that the size / placement of the Open / Closed button differs to when rendered in the post/page editor (the CSS-in-JS styles that affect the font size don't appear to be carried over, as in https://github.com/WordPress/gutenberg/issues/30553)

#### What I expected

The UI in the editor canvas to look the same as in the post/page editor

#### What happened instead
The font size of the controls is slightly bigger, and the Open / Closed toggle is a bit lower than it should be.

**Screenshots**

| FSE running tt1-blocks theme | Post editor in Twenty Twenty One theme |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/14988353/113970150-b16b5c00-9879-11eb-9dd2-59e0900875c4.png) | ![image](https://user-images.githubusercontent.com/14988353/113970868-0491de80-987b-11eb-9b3e-d2bdbc94587e.png) |

**Comment by ramonjd** [comment]
Just adding notes here while I'm debugging:

`.editor-styles-wrapper` is overriding the default `body` classes:

<img width="364" alt="Screen Shot 2021-04-13 at 4 43 23 pm" src="https://user-images.githubusercontent.com/6458278/114508316-8ddc5300-9c77-11eb-8141-16c4e1512878.png">
