### ISSUE TITLE
Site Editor Compatibility: Blocks that depend on the Button block styling

### ISSUE THREAD

**Issue by andrewserong** [Automattic/jetpack#19464]
In the new site editor in Gutenberg (/wp-admin/admin.php?page=gutenberg-edit-site), there are some styling issues with Jetpack blocks that use buttons when rendered on the front end of the site. These blocks depend on the Button block styling, which may not be loaded in the template part if there is not also a Buttons block in the content of that template.

#### Steps to reproduce the issue

1. With the Gutenberg plugin active (>=10.4.0-rc1), activate a block-ready theme (like tt1-blocks)
2. In the site editor, insert a Donations block into the Footer template part (also hook up your site to a compatible plan / connect Stripe)
3. Save the template part, and load the front end of the site
4. Observe that the Donate button in the Donations block is mostly unstyled

#### What I expected

The button to render with Button styling from Gutenberg

#### What happened instead
The button is rendered either unstyled or close to it.

Note that if you add a Buttons block to the template part you're working on, the Buttons styling will be loaded, and the button will start to render on the front end with the expected (or close to it) styling.

#### Blocks affected

* [ ] Calendly block (when using the Link style for the block, it'll render a `jetpack/button` block)
* [ ] Contact Form block
* [ ] Donations block
* [ ] Eventbrite block (when using the Button & Modal style for the block, it'll render a `jetpack/button` block)
* [ ] Mailchimp block (also raised in: https://github.com/Automattic/jetpack/issues/19481)
* [ ] Revue block (also raised in: https://github.com/Automattic/jetpack/issues/19485)
* [ ] Premium content buttons

**Screenshots**

| Donations block | Contact Form block |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/14988353/113973760-29d51b80-9880-11eb-8159-f37a28961a9a.png) | ![image](https://user-images.githubusercontent.com/14988353/113973813-3d808200-9880-11eb-9175-ee8de829a5ad.png) |
| Calendly block | Eventbrite |
| ![image](https://user-images.githubusercontent.com/14988353/113974813-e67bac80-9881-11eb-9c97-671fd751cf13.png) | ![image](https://user-images.githubusercontent.com/14988353/113975510-f647c080-9882-11eb-9a52-55fa1beccac6.png) |
| Mailchimp block | Revue block |
| ![image](https://user-images.githubusercontent.com/14988353/114120051-22208000-992f-11eb-9c48-ca18a897102e.png) | ![image](https://user-images.githubusercontent.com/14988353/114127036-f1474780-993c-11eb-920f-129ca15de4b1.png) |
| Premium Content Buttons block | |
| ![image](https://user-images.githubusercontent.com/14988353/114137283-4a1fdb80-994f-11eb-8e13-5bd4cfc2f7b4.png) | |

**Comment by apeatling** [comment]
Any styles added to the button block in the editor will work in the front end. There are no base padding or border styles in TT1-blocks though. These will be added in newer block themes. For now we'll need to add some base styles. This worked for contact form:

`.wp-block-jetpack-button button {
	padding: 20px 30px;
	border: inherit;
	font: inherit;
}`

**Comment by andrewserong** [comment]
I have a potential global fix for this in Jetpack in: https://github.com/Automattic/jetpack/pull/19595 — I haven't tested it against all of the blocks that use the Jetpack Button Block, but at first glance it appears to address most of the issues with this block.

**Comment by andrewserong** [comment]
We've merged in #19595 which addresses the main issues (loading default styling for the Jetpack button block). There are some outstanding Button block alignment issues (particularly with using right alignment), but these issues are also present in non-FSE, so I think we can close out this issue. I'll open up issues for the backlog for remaining issues we encounter.
