### ISSUE TITLE
Site Editor Compatibility: Instagram Gallery Block styling issues in editor

### ISSUE THREAD

**Issue by andrewserong** [Automattic/jetpack#19466]
In the new site editor in Gutenberg (`/wp-admin/admin.php?page=gutenberg-edit-site`), there are some issues with the Instagram Gallery block within the editor. It appears that the block renders correctly on the front end of the site, though.

#### Steps to reproduce the issue

1. With the Gutenberg plugin active (>=10.4.0-rc1), activate a block-ready theme (like tt1-blocks)
2. In the site editor, insert an Instagram Latest Posts block into the Footer template part
3. If you already have multiple accounts connected, note that the styling for the radio buttons looks off
4. Connect an account, and note that the images are loaded much too tall vertically

#### What I expected

* The radio buttons in the placeholder state to look normal
* The images in the gallery to be of a normal height

#### What happened instead
* The radio button styling is off within the placeholder state
* The images are rendered too tall within the editor

**Screenshots**

| Placeholder state | Connected within the editor |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/14988353/113980183-82f57d00-9889-11eb-986e-4399c421b6f0.png) | ![image](https://user-images.githubusercontent.com/14988353/113980207-8a1c8b00-9889-11eb-9e14-d284aa82b01f.png) |

**Comment by aaronrobertshaw** [comment]
The checkbox styling issue was resolved in https://github.com/WordPress/gutenberg/pull/30670
