### ISSUE TITLE
Site Editor Compatibility: Map block

### ISSUE THREAD

**Issue by andrewserong** [Automattic/jetpack#19482]
In the new site editor in Gutenberg (/wp-admin/admin.php?page=gutenberg-edit-site), there are some issues with the Map block in the editor. The Map block itself appears to be able to be initialised within the site editor canvas, likely as a result of the editor canvas being rendered within an iframe. It looks like Mapbox expects to be given a string to match against a DOM node, or be given a DOM node.

Is there a way for us to get the Mapbox initialisation to play nicely with an iframe?

#### Steps to reproduce the issue

1. With the Gutenberg plugin active (>=10.4.0-rc1), activate a block-ready theme (like tt1-blocks)
2. In the site editor, insert a Map block into the Footer template part
3. Observe that the map block throws an error as in the screenshot below
4. Save the template part
5. Observe that the map _does_ render on the front end of the site

#### What I expected
The map to render and be usable within the editor

#### What happened instead
The map isn't rendered, and throws an error
![image](https://user-images.githubusercontent.com/14988353/114120240-71ff4700-992f-11eb-81d1-dd26b00e0ad4.png)

**Comment by glendaviesnz** [comment]
Fixed by https://github.com/Automattic/jetpack/pull/19552, but follow up issue added to refactor to new api when stable - https://github.com/Automattic/jetpack/issues/19896
