### ISSUE TITLE
Site Editor Compatibility: Revue Block styling issues on front end

### ISSUE THREAD

**Issue by andrewserong** [Automattic/jetpack#19485]
In the new site editor in Gutenberg (/wp-admin/admin.php?page=gutenberg-edit-site), there are some issues with the Revue block within the front end of the site.

#### Steps to reproduce the issue

To test this you'll need to create an account at https://www.getrevue.co/ if you haven't already.

1. With the Gutenberg plugin active (>=10.4.0-rc1), activate a block-ready theme (like tt1-blocks)
2. In the site editor, insert a Revue block into the Footer template part
3. Add your username and click Embed
4. Save the Footer template part and view the front end of your site
5. Observe that the block doesn't provide its own default styling for the input fields and button.

#### What I expected

The block to be rendered with comfortable defaults for the components used, if not provided by the active theme. In this case, I expected it to look like the Twenty Twenty theme:

![image](https://user-images.githubusercontent.com/14988353/114125916-b6dcab00-993a-11eb-8ff8-45eb4430ca2f.png)

#### What happened instead

The tt1-blocks theme doesn't provide its own default styling for these elements, so the input fields and button are rendered (mostly) unstyled on the front end of the site:

![image](https://user-images.githubusercontent.com/14988353/114125989-e2f82c00-993a-11eb-817b-52f4f1d10d6e.png)

This issue appears to be quite similar to the issues with the Contact Form #19462, Mailchimp #19481, and Jetpack Button blocks #19464

**Comment by apeatling** [comment]
@andrewserong Your button updates should fix the button. The form fields match front end and editor and are like this because TT1-blocks does not have form field styles. I think we can leave this as is?

**Comment by andrewserong** [comment]
That sounds fair to me, thanks for taking a look @apeatling!
I'll add this to my list of things to check when the Buttons [PR lands](https://github.com/Automattic/jetpack/pull/19595), then I can close it out.

**Comment by andrewserong** [comment]
Closing this out now as the Button block styling was resolved in https://github.com/Automattic/jetpack/pull/19595 which has now been deployed. I did a smoke test, and the block now behaves the same way in the site editor as it does in the post editor. Below are a couple of screenshots of how the block renders in a couple of FSE-capable themes:

| TT1 blocks (theme has missing styles for input fields) | Seedlet block (which includes input field styling) |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/14988353/116330697-678aeb80-a811-11eb-8ffa-cc2054a1360d.png) | ![image](https://user-images.githubusercontent.com/14988353/116330753-88ebd780-a811-11eb-99d4-b1dab11915ae.png) |
