### ISSUE TITLE
SSO: Hide login form using stronger method than JS

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#1949]
Currently when hiding the existing login form, it uses JS/jQuery to hide the form. Disabling JS in the browser enables the traditional form when it is displayed (upon logout, bad wpcom login, etc).

**Comment by ebinnion** [comment]
This is no longer an issue since we hide the form with CSS. We also added a filter to `authenticate` so users can not show the form and log in via username and password. 😉
