### ISSUE TITLE
Premium Blocks: Show upgrade banners on Free Atomic sites 

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#19498]
#### Steps to reproduce the issue

- Set up a Free tier of Atomic by either cancelling a Business plan on an Atomic site, or pinging me for instructions. 
- In the post editor, pull up a Premium block. There's a list here: pbAPfg-yo-p2
- See that the block does not have an upgrade banner

#### What I expected

Banner to be shown
![image](https://user-images.githubusercontent.com/7129409/114236144-2eb4d080-994f-11eb-9c2d-7edefc18938e.png)

#### What happened instead
No banner to upgrade

**Screenshots**

Upgrade banner is handled in the ./paid-blocks extention https://github.com/Automattic/jetpack/tree/master/projects/plugins/jetpack/extensions/extended-blocks/paid-blocks

**Comment by retrofox** [comment]
In order to show the upgrade banners, we need to enable the feature for Atomic sites. tackled on this PR 679-gh-Automattic/wpcomsh

Then, we update the availability of the features for Atomic sites with the changes purposed here https://github.com/Automattic/jetpack/pull/19762
