### ISSUE TITLE
Nav Unification: "View detailed stats" button leads to page with error "Sorry, you are not allowed to access this page."

### ISSUE THREAD

**Issue by druesome** [Automattic/jetpack#19502]
On the Jetpack stats page, clicking on "View detailed stats" button leads to a page with this error: 

Sorry, you are not allowed to access this page.

#### Steps to reproduce the issue

1. Go to Jetpack > dashboard
2. Click on "View detailed stats" button

#### What I expected

For the link to bring me to the stats page with more details

#### What happened instead

I see the error "Sorry, you are not allowed to access this page."

**Comment by jeherve** [comment]
Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/51381
