### ISSUE TITLE
Custom CSS pain points

### ISSUE THREAD

**Issue by iandunn** [Automattic/jetpack#1951]
Over on the WordPress.org Community Team p2 we've been [discussing some of the pain points that WordCamp organizers have experienced with the CSS Editor](https://make.wordpress.org/community/2015/03/05/improving-wordcamp-org-user-experience-of-the-css-editor/).

Nothing has been decided yet, but it's been proposed that we either send PRs to Jetpack to fix those issues, or build an alternative solution. Either way, I thought it'd be helpful to open a ticket here -- if we end up building an alternative, then this is still good feedback for Jetpack; and if we decide to send PRs then this could serve as a meta-ticket.

> - There isn’t any post-locking or strong version control, so it’s easy for two users to accidentally overwrite each other’s changes. There are revisions, but they fall short of true version control.
> - Saving edits requires a page refresh, which makes you lose your place. With larger rulesets, finding your place again takes too long and often breaks mental “flow”, which is frustrating.
> - The browser’s built-in Find functionality doesn’t always work
> - The rules can’t be modularized into small, manageable files — and then recombined during processing — for easier development and maintenance.
> - There isn't any code-completion or other advanced features that IDEs offer
> - Cross-browser/device testing can’t be easily done with the Preview functionality
> - Syncing between production and a local testing environment has to be done manually
> - Time-saving tools like LiveReload can’t be used.
> - There are two scroll bars (one for the page itself, and then another inside the editor), which makes using the scroll wheel on a mouse annoying.
#1621 and #1231 are related.

**Comment by kraftbj** [comment]
Personal opinion: I think a fair amount of these are things that should be improved in JP (post locking, ajax saving, double-scroll stand out). I think the vision of Jetpack+Custom CSS, though, is the ability to make relatively quick, relatively minor CSS changes.

With WordCamp.org, a lot of camps are, virtually, making css-only child themes. Our advice has been for larger changes, using a child theme makes more sense (performance-wise, the management/VCS pain points mentioned, etc). 

Interested in hearing tdiv's thoughts.

**Comment by iandunn** [comment]
Yup, that's exactly why we're discussing the possibility of building an alternative solution. If we go that route, though, it won't replace Jetpack, it'll just be an additional choice the organizers have.

**Comment by joseluis** [comment]
:+1: I was going to open an issue about this.

Right now the Sass pre-processor discards all `display: flex` rules (vendor-prefixed or not) after the first rule. E.g.:
```
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
```

Results in:
```
  display: -webkit-box;
```

**Comment by aheckler** [comment]
> The browser’s built-in Find functionality doesn’t always work

Also mentioned in 2589027-t.

**Comment by iandunn** [comment]
> Also mentioned in 2589027-t.

@aheckler, steps to reproduce are at https://make.wordpress.org/community/2015/03/05/improving-wordcamp-org-user-experience-of-the-css-editor/#comment-20402

**Comment by jeherve** [comment]
#1621

**Comment by jeherve** [comment]
Closing this as `wontfix` as Custom CSS is now part of Core.
