### ISSUE TITLE
Block Editor: Respect the `send_auth_cookies` filter

### ISSUE THREAD

**Issue by dd32** [Automattic/jetpack#19516]
#### Steps to reproduce the issue

1. Add a filter on `send_auth_cookies` to `__return_false`
2. Attempt to login

#### What I expected
Login should fail, as no cookies will be sent to the client.

#### What happened instead
Jetpack sets the authentication cookies instead, with the cross-site attributes set.

https://github.com/Automattic/jetpack/blob/ba2dd6c30be137baad96aafb2466d0aed7e182e5/projects/plugins/jetpack/modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php#L431-L450

Two thoughts come to mind:
 - The filters that set the cookies should check the `send_auth_cookies` filter
 - The existing `__return_false` filter on `send_auth_cookies` should be removed, and instead it should only be set to false if Jetpack has indeed sent the cookies.

I'm unsure if just running the filter / storing the result at the point in time of `enable_cross_site_auth_cookies()` being run would be proper, I'm leaning towards no.

#### Temporary hotfix
```
add_filter( 'jetpack_disable_cross_site_auth_cookies', function( $disable ) {
	return ! apply_filters( 'send_auth_cookies', true );
} );
```

#### Possible solution

* Remove the existing `send_auth_cookies` filter
* Do not set the cookies on the `set_*_cookies` filters, instead temporarily store them internally
* Late on the `send_auth_cookies` filter, if the filter value is truthful, then send the cookies & return false on the filter.

**Comment by kraftbj** [comment]
@pablinos Would it be fair to aim for this to be done in the next month so it makes 9.8? I don't want to leave this hanging open too long.
