### ISSUE TITLE
Disable Audio File Download on Podcast player

### ISSUE THREAD

**Issue by JessBoctor** [Automattic/jetpack#19528]
#### Is your feature request related to a problem? Please describe.

I want to showcase my audio files but only have them be able to play on the site. I don'w want them to be available to download via right-click

#### Describe the solution you'd like

Disable download/right-click option built into the player

#### Describe alternatives you've considered

Installing a right-click disabling plugin that will disable right-click across the whole site

#### Additional context

Customer request
#28995508-HC

**Comment by jeherve** [comment]
The Audio player is provided by WordPress Core itself, and relies on the browser built-in player. It does not include any mechanism to encode the played media. As a result, it is currently impossible to block downloading of the data. Even if right-clicking was not an option, one could still easily get the direct media URL in the browser network tools.

I'll consequently close this issue as "Won't fix". If one is interested in completely blocking downloads, they would need to use a custom player that breaks down the media files before they get played. Some third-party players do that.
