### ISSUE TITLE
VideoPress: can't upload video via the post editor, only via Media > VideoPress > Add New

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#1952]
Steps to reproduce: 
- Connect to your VideoPress account
- Upload an MOV video through the media uploader
- Insert it in the post 
- Just a link.  

It embeds as expected in wpcom.

**Comment by georgestephanis** [comment]
cc: @rauchg -- has there been a changeover on wpcom sites that hasn't been implemented for Jetpack yet or something?

**Comment by kraftbj** [comment]
Are you uploading directly into the Media Uploader's "Insert Media" or using the "VideoPress" left-side tab. The former uploads it directly to the site's server (and tries to use the .mov directly). The latter uploads it to VideoPress via the user's wpcom site that has the upgrade, then inserts the [wpvideo] shortcode.

**Comment by dereksmart** [comment]
@kraftbj Same result for both instances - inserts a link rather than a shortcode/embed

**Comment by kraftbj** [comment]
Yup, something up. Drag and drop or VideoPress->Upload is uploading the video locally (not to VideoPress). I can't click on an existing VP video to insert (only see the info, which I can copy/paste the shortcode). I don't think it is limited to .mov. Tested on latest trunk/master. Haven't bisected to figure out what changed.

**Comment by jeherve** [comment]
I think we have 2 different issues here, not limited to .mov files. I'll break them down into 2 different GitHub issues.

> Drag and drop or VideoPress->Upload is uploading the video locally (not to VideoPress).

This never worked, we never implemented drag and drop upload to VideoPress unfortunately. I've logged this in 

However, when clicking the VideoPress tab, and then "Upload Files", you used to be redirected to the VideoPress video uploader, which looks like this:

![screen shot 2015-04-11 at 12 32 54 pm](https://cloud.githubusercontent.com/assets/426388/7101108/e748325e-e046-11e4-9703-793fdf3871df.png)

Now you're redirected to the core media uploader and your file is in fact uploaded to your own site:
![screen shot 2015-04-11 at 12 34 24 pm](https://cloud.githubusercontent.com/assets/426388/7101113/1b025098-e047-11e4-943c-d2a0f3bfaf81.png)

I'll rename this issue to reflect this problem.

> I can't click on an existing VP video to insert (only see the info, which I can copy/paste the shortcode; "Insert Post" either doesn't "light" or either simply fails). I don't think it is limited to .mov. 

I think that used to work. As you mentioned, it's not limited to .mov. I assume it worked before all the changes to the Media uploader that were added to WP in 4.0.

Here is a video to demonstrate the issue:
https://cloudup.com/cUAtaciFkpA

In my tests, I couldn't even get a link to appear. The only way to add a video is to copy the shortcode.

I'll create a new issue (#1953) for that problem

**Comment by nickmomrik** [comment]
@georgestephanis we haven't launched anything new yet.

**Comment by supernovia** [comment]
Hoping for an update on this, re: https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=2221695

This user can't upload videos without going to their WordPress.com site and uploading there.

**Comment by kraftbj** [comment]
@supernovia No update (anything would have been noted here).

**Comment by becklz** [comment]
Hoping for a fix with this too! Looks like it's starting to get worked on...

**Comment by kraftbj** [comment]
Indeed. There was a lot changing with VideoPress internally that has now been announced/launched on WP.com, so we let the dust settle a bit. We're aiming to have this and a slew of other new things for VideoPress out soon.

**Comment by becklz** [comment]
That's good news! I was starting to worry since video press has been buggy
for months.

Thanks for your help!
Liz
On Aug 11, 2015 9:04 AM, "Brandon Kraft" <notifications@github.com> wrote:

> Indeed. There was a lot changing with VideoPress internally that has now
> been announced/launched on WP.com, so we let the dust settle a bit. We're
> aiming to have this and a slew of other new things for VideoPress out soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Automattic/jetpack/issues/1952#issuecomment-129945892>
> .
>

-- 
 

********************************************************************

CONFIDENTIAL: The Hamlin School This email and attachments are sent

by The Hamlin School and may contain information that is privileged

or confidential. If you are not the intended recipient, please

delete the email and any attachments without reading, printing,

copying, or forwarding it, and please notify us. helpdesk@hamlin.org

********************************************************************

**Comment by becklz** [comment]
Any update on this issue?

**Comment by kraftbj** [comment]
@becklz No, more will be posted here when there's something to update. There is a team assigned to this for a pretty massive overhaul.

**Comment by dbtlr** [comment]
This interface has been deprecated completely in #5326 which effectively solves this bug
