### ISSUE TITLE
Jetpack Search: Product categories able to be added in widget even though they're not supported in searching

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#19524]
#### Steps to reproduce the issue

1. With a site that has Jetpack Search and WooCommerce
2. Navigate to Widgets > Jetpack Search Sidebar
3. Add Jetpack Search widget if not already there
4. Verify that you see an option to add product categories via the widget
5. Load frontend of WooCommerce site

#### What I expected

Since I had the ability to add a filter for product categories, I expected to see product categories in the list of filters

#### What happened instead

There were no filters

**Screenshots**

![Screen Shot 2021-04-13 at 12 41 59 PM](https://user-images.githubusercontent.com/1126811/114596851-ba7f7300-9c55-11eb-96b6-ec4daf75702a.png)
<img width="478" alt="Screen Shot 2021-04-06 at 5 04 22 PM" src="https://user-images.githubusercontent.com/1126811/114596858-bce1cd00-9c55-11eb-8693-da628b1d79d7.png">

**Comment by kangzj** [comment]
Hi @bluefuton as woo-related filters are not supported for now, I'm going to hide them. 

Just one question, does our backend only support post categories and post tags or it just doesn't support woo product taxonomies, and others are all supported?

Thanks.

**Comment by bluefuton** [comment]
> Just one question, does our backend only support post categories and post tags or it just doesn't support woo product taxonomies, and others are all supported?

I'll hand this one over to @gibrown and @robfelty :)

**Comment by kangzj** [comment]
```
aggregations[taxonomy_3][terms][field]: taxonomy.product_cat.slug_slash_name
aggregations[taxonomy_3][terms][size]: 5
```

```
"taxonomy_3": {
"doc_count_error_upper_bound": 0,
"sum_other_doc_count": 0,
"buckets": []
}
```

I can see the frontend is passing product taxonomy to WPCOM API if woo category filter is set, but API returned empty.

**Comment by gibrown** [comment]
Seems like this should work as long as the data is getting synced. https://github.com/Automattic/jetpack/pull/19674 maybe needs to get merged in for sync to work properly though. Once it is we should probably also use that list of what we are syncing to filter the list of available taxonomies for filtering.

**Comment by kangzj** [comment]
Thanks @gibrown for your advice 👍 

The Jetpack Search Sync PR #19674 is going to be merged pretty soon. 

Talked to @bluefuton and decided that  we leave the issue for now so that the current release will benefit once sync PR is merged. Otherwise if we remove product filters now -  as Jetpack is released monthly - we would delay _product filtering_ to be delivered to users (around two months for org users regarding the release cycle).

Will come back to this one and align settings with #19674 once it's merged and working.
