### ISSUE TITLE
VideoPress: can't click to insert video into post

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1953]
> I can't click on an existing VP video to insert (only see the info, which I can copy/paste the shortcode; "Insert Post" either doesn't "light" or either simply fails).

Originally reported in #1952

Here is a video to demonstrate the issue:
https://cloudup.com/cUAtaciFkpA

The only way to add a video is to copy the shortcode.

**Comment by richardmtl** [comment]
Another report in 2192897-t

**Comment by becklz** [comment]
Any ETA on when this issue will be resolved?

**Comment by zinigor** [comment]
@becklz It's hard to say for certain. There's a pretty good chance that it will be fixed for 3.8, but no guarantees.

**Comment by becklz** [comment]
Thank you for letting me know. Here's hoping!

**Comment by shawnajean** [comment]
Another report in 2436294-t

**Comment by dbtlr** [comment]
This has been addressed and is fixed by merging VideoPress into the standard media library: #5326
