### ISSUE TITLE
Asset CDN not sending `Access-Control-Allow-Origin` headers

### ISSUE THREAD

**Issue by swissspidy** [Automattic/jetpack#19541]
#### Steps to reproduce the issue

For the [Web Stories WordPress plugin](https://wordpress.org/plugins/web-stories/) we set [cross-origin isolation](https://web.dev/coop-coep/) on some admin pages, which requires loading 3P resources with the `crossorigin` attribute and the requested resource responding with corresponding `Access-Control-Allow-Origin` headers.

If not done, loading these resources will fail with corresponding errors.

This happens with the Asset CDN URL, which makes scripts and styles to be loaded from `https://c0.wp.com/...`.

1. Activate [Web Stories for WordPress](https://wordpress.org/plugins/web-stories/)
2. Activate Site Accelerator module (Asset CDN)
3. Go to Stories -> My Stories or Stories -> Add New
4. Check console errors

Related: #19411

#### What I expected

Using Site Accelerator / Asset CDN should not cause console errors on admin pages due to missing CORS headers.

The CDN should have a `Access-Control-Allow-Origin: *` response header.

#### What happened instead

Blocked requests and tons of console errors due to missing CORS headers.

**Screenshots**

![Screenshot 2021-04-14 at 22 18 39](https://user-images.githubusercontent.com/841956/114773466-65378480-9d6f-11eb-832e-4b23392ece32.png)

**Comment by bazza** [comment]
I changed the CDN to send CORS headers unconditionally (even when there is no Origin request header). This should hopefully resolve your issue.  

```
$ curl https://c0.wp.com/p/jetpack/9.6.1/css/jetpack.css -I
HTTP/2 200 
server: nginx
date: Wed, 14 Apr 2021 21:11:51 GMT
content-type: text/css
content-length: 77191
vary: Accept-Encoding
last-modified: Tue, 30 Mar 2021 16:59:40 GMT
expires: Thu, 14 Apr 2022 21:11:51 GMT
cache-control: max-age=31536000
strict-transport-security: max-age=15552000
x-nc: HIT dfw 1
timing-allow-origin: *
access-control-allow-methods: GET, HEAD
access-control-allow-origin: *
accept-ranges: bytes
```

**Comment by swissspidy** [comment]
It does, thanks a lot!
