### ISSUE TITLE
Markdown block: double quotes are not rendered as smart quotes

### ISSUE THREAD

**Issue by kbrown9** [Automattic/jetpack#19549]
#### Steps to reproduce the issue

1. Add a Markdown block to a post.
2. Add some double quotes in the Markdown block. 
3. Publish the page and notice that the double quotes are straight double quotes rather than smart double quotes.

This issue was reported in [the support forums](https://wordpress.org/support/topic/smart-quotes-in-markdown-block/).

**Screenshot**

<img width="425" alt="Screen%20Shot%20on%202021-04-15%20at%2012-13-52" src="https://user-images.githubusercontent.com/50059399/114902757-2263c400-9de4-11eb-8faf-adfc92194a47.png">

**Comment by bixfrankonis** [comment]
So was this never addressed, or is it back, because it’s either still happening two years later (inexplicable), or has returned (stuff happens).

**Comment by jeherve** [comment]
@bixfrankonis This issue has remained untouched (and consequently unaddressed). I'll see if I can take a look at it today.
