### ISSUE TITLE
Add Facebook Verification as an option to the "Site Verification Services"

### ISSUE THREAD

**Issue by jonesch** [Automattic/jetpack#19548]
#### Is your feature request related to a problem? Please describe.
It's not part of a problem, but more expanding on what [**Site Verification Services** already offers](https://jetpack.com/features/traffic/site-verification/)

#### Describe the solution you'd like
Add a field for Facebook Verification to the Site Verification Services:
![image](https://user-images.githubusercontent.com/1905918/114890165-c6e00900-9dd8-11eb-8f43-d0ccd46012e4.png)

#### Describe alternatives you've considered
The alternative option is to manually add the `<meta>` tag into the theme. Or upload a HTML file. Or make a change to DNS.

#### Additional context
[Facebook Ad Manager is asking to verify ownership of a domain](https://developers.facebook.com/docs/sharing/domain-verification/verifying-your-domain/) before a user can start to use all the features inside of Facebook's Ad Manager
![image](https://user-images.githubusercontent.com/1905918/114889842-7799d880-9dd8-11eb-8d13-3c0c1a60dbd2.png)

**Comment by Aurorum** [comment]
PR for this issue in #19725. :)
