### ISSUE TITLE
Sitemaps: offer options to exclude posts from News Sitemap

### ISSUE THREAD

**Issue by ctdealba** [Automattic/jetpack#19550]
Hi all! I'm just sharing what a user is asking to update. I'm not sure if this is even possible but I think this information that user is sharing is important and it is related to our Jetpack's Sitemap feature.
JPOP 3911676-zen

#### Is your feature request related to a problem? Please describe.
Over the years Google News has changed how a site is included on the News index.
Now publishers do not need to apply to get listed on Google News,

'Publishers no longer need to submit their site to be eligible for the Google News app and website. Publishers are automatically considered for Top stories or the News tab of Search. They just need to produce high-quality content and
comply with Google News content policies.'

Source: https://support.google.com/news/publisher-center/answer/9607025

Now that the inclusion and ranking is decided by an algorithm. So unlike previous sites which used to get entry with anything, it's risky to submit every content into the News sitemap now. We need to exclude many low-quality articles from the News Sitemap. Jetpack doesn't provide an option for that.

#### Describe the solution you'd like
What we need is two types of exclusion:

- Exclude based on categories
- Exclude per post basis based from post edit sidebar meta

Apart from that the new Google News Publisher Center (https://publishercenter.google.com/) works using RSS Feeds.

Read about the Technical Feed requirements here: https://support.google.com/news/publisher-center/answer/9545420

So please update the Jetpack plugin with new Google News compatible News Sitemap and RSS feeds generation is needed.

Inputs taken from these free WordPress plugins:
https://wordpress.org/plugins/xml-sitemap-feed/
https://wordpress.org/plugins/gn-publisher/

FAQ having outdated link: https://jetpack.com/support/sitemaps/ --> 'Don’t forget to apply to get your posts listed in Google News.' linked to an
invalid page.

Apart from please add support for Bing News (https://pubhub.bing.com/). It has the same technical requirements as Google News.

**Comment by jeherve** [comment]
> What we need is two types of exclusion:
>
> Exclude based on categories
> Exclude per post basis based from post edit sidebar meta

While we do not have any interface for this, it is already possible via the `jetpack_sitemap_news_skip_post` filter:
https://developer.jetpack.com/hooks/jetpack_sitemap_news_skip_post/

One could exclude specific posts, or posts based on their categories, thanks to that filter. One could also add a new UI element in the post editor using that filter behind the scenes.

**Comment by StefMattana** [comment]
The user who shared this initial feedback has followed up with us adding more info and concerns on that: 

>I would like to share my concern about unavailability of Google News compatible RSS Feeds with Jetpack which requires us install a third party plugin called 'GN Publisher'.
Please note, without compatible RSS Feeds we can't submit our content to the new Google News Publisher Center.
Hence Jetpack doesn't fulfill Google News technicial requirements. Please improve your support for Google News technicial requirements so we won't require to install additional plugins for Google News support.

**Comment by jeherve** [comment]
@StefMattana I created this issue to keep track of this: #19556

**Comment by kraftbj** [comment]
Since there is a filter for having a post skip from the News sitemap and we don't have plans to build UI at this time, I'm going to close this issue, leaving 19556 for the RSS feed issue brought up.
