### ISSUE TITLE
Errors on Update: Omnisearch PHP Notice: Undefined property && Fatal error: Maximum function nesting in update-core.php

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1957]
Here is the error detail:
https://dl.dropboxusercontent.com/u/569741/jetpack-error.html

Maybe related to #1812

Reported here:
https://wordpress.org/support/topic/jetpack-raises-fatal-error-because-of-infinite-nesting

**Comment by dereksmart** [comment]
Since the Omnisearch error is not a fatal and doesn't look related to the fatal, I am renaming this issue.  The fatal looks more related to issue #1825.  This could probably be written as two separate issues.

**Comment by dereksmart** [comment]
I think this has been resolved since 3.4 

Please reopen if any more reports with current Jetpack
