### ISSUE TITLE
A/B Test Package: deprecate and / or update to handle new A/B test standards on WordPress.com.

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#19596]
The `/abtest` endpoint in use by the A/B test package is being removed:
D60276-code

https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/packages/abtest/src/class-abtest.php#L99

This effectively renders the package useless. We'll need to either deprecate it to replace it with another (maybe one developed by another a8c team such as Akismet), or update it to handle the new Experiment platform (ExPlat): pbmo2S-j2-p2

Discussion: pbmo2S-IT-p2

Next steps:

- [ ] Add notice to package that it should not be used anymore.

Internal resources:

- +a8cexperiments 
- #a8c-experiments in Slack
- experimentation-platform-gh
- D57687-code

**Comment by jeherve** [comment]
Also in pbtFFM-1sV-p2

**Comment by ilyasfoo** [comment]
Hi, @jeherve! I'm curious if this issue is still relevant?

**Comment by jeherve** [comment]
No, this can be closed now. We retired the package in #38164. It has been replaced in this task: https://github.com/Automattic/jetpack-roadmap/issues/1534
