### ISSUE TITLE
Custom CSS PHP Notice

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#1959]
Just noticed that I am getting a PHP Notice if I have custom css enabled. 

```Notice: Undefined index: action in /wp-content/plugins/jetpack/modules/custom-css/custom-css.php on line 112```

ping @sirbrillig since the notice seems to be coming from the change that you added.

**Comment by sirbrillig** [comment]
Ah, yes, looks like a `issset( $_REQUEST[ 'action' ] )` should be added to this line: 

```php
if ( 'restore' === $_REQUEST[ 'action' ] && false !== strstr( $_SERVER[ 'REQUEST_URI' ], 'revision.php' ) ) {
```
