### ISSUE TITLE
Strict Standards Error in Jetpack Gallery Widget

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#1960]
I am seeing this when I have the Extra Sidebar Widgets enabled on my dashboard. 

```Strict Standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method Jetpack_Gallery_Widget::enqueue_admin_scripts() should not be called statically in /home/enej/public_html/wp-includes/plugin.php on line 496```

**Comment by dereksmart** [comment]
Merged in 5d50411
