### ISSUE TITLE
WooCommerce Upsell Icon - No Logo Appearing

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#19625]
#### Steps to reproduce the issue

1. Install Jetpack beta on an Atomic site where WooCommerce is not installed/deactivated
2. Activate the master branch ("Bleeding Edge")
3. See the WooCommerce upsell icon appear as a white square
4. If you see the WooCommerce logo, try making sure the plugin is deactivated.

![Screen Shot 2021-04-22 at 09 33 25](https://user-images.githubusercontent.com/33553323/115723289-d1a51b80-a34d-11eb-9dff-f0ed9ce330f7.png)

possibly related since it was also reported here: https://github.com/Automattic/jetpack/pull/19364

**Comment by jeherve** [comment]
cc @pablinos who worked on #19364.
