### ISSUE TITLE
Stats: Specify height/width for the smiley image 

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#1963]
Performance tools like GTMetrix don't seem to like the lack of height/width attributes.

Suggested here:
https://wordpress.org/support/topic/specify-heightwidth-for-the-smiley-image?replies=1&view=all

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/width-and-height-for-httppixelwpcomggif

**Comment by harrymilatz** [comment]
Hello,

i think i got it.
In the e-201551.js just add right after this <code>i.src=document.location.protocol+'//pixel.wp.com/'+t+'?'+q+'&rand='+Math.random();</code> the width and height for it: <code>i.width='6';i.height='5';</code>

I tested it and my stats still working:D
I hope i am right and it will be in the next update of the .js file.

Best regards,
Harry

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/stats-pixel-missing-dimensions-on-html?replies=1&view=all

**Comment by egill** [comment]
Fixed the JS, should work once we bump the version in the next JP release.

**Comment by kraftbj** [comment]
The JS version is bumped weekly, so going to mark this as closed. Should self-resolve for everyone within a week.
