### ISSUE TITLE
Safari Reader View - Related Posts Module

### ISSUE THREAD

**Issue by joweber123** [Automattic/jetpack#19647]
#### Steps to reproduce the issue

1. Activate the Related Posts module in Jetpack
2. Pull up a post that is showing the related posts area in Safari.
3. In Safari, click on View > Show Reader
4. Safari Reader will show the date of the last related post in the Reader. 

#### What Happened
There seems to be very little information from Apple on the Reader view in Safari and the best guide I would find was here - https://www.client9.com/designing-html-for-safari-reader-mode/

The issue seems to be that this Reader view is scraping the page looking for the `datetime` attribute.  Most themes I have tested do not use this attribute to display the date, but rather display some element with the class of `post-date`.  This theme in the screenshot is Twenty-Twenty.

![Markup on 2021-04-24 at 12:48:57](https://user-images.githubusercontent.com/24914028/115946331-731da000-a4fb-11eb-9e0b-e0477769ec31.png)

The Related Posts module does have the datetime` attribute and it looks like Safari is using that instead in the Reader view. 
![Markup on 2021-04-24 at 12:49:33](https://user-images.githubusercontent.com/24914028/115946345-87fa3380-a4fb-11eb-9509-4fabdd62cf7d.png)

Here is a screenshot of this same post with a post date of April 24, 2021, showing the related post date of February 4, 2020.
![Markup on 2021-04-24 at 12:51:32](https://user-images.githubusercontent.com/24914028/115946394-d0b1ec80-a4fb-11eb-9f65-3c686fad8e09.png)

I am not really sure of what the solution would be here.  If the html formatting for the related posts module does not need the `datetime` attribute we could simply remove that to not cause this issue in Safari?

**Comment by jeherve** [comment]
> I am not really sure of what the solution would be here. If the html formatting for the related posts module does not need the datetime attribute we could simply remove that to not cause this issue in Safari?

Related Posts are easier to parse by screen readers when they use semantic dates, though. In this case, I believe it would be best if the theme used `datetime` to display the post date? It would be better for everyone, including folks not using the Jetpack plugin.
