### ISSUE TITLE
Defer non-essential javascript setting conflicts with Web Stories stock media

### ISSUE THREAD

**Issue by LuckynaSan** [Automattic/jetpack#19653]
I work on the Google Web Stories plugin (https://wordpress.org/plugins/web-stories/). A user reported Stories that contain stock photos and have animations applied to them do not render if you have Jetpack Boost (Defer Non-Essential Javascript setting) + AMP enabled. I’ve created a GitHub issue document this: https://github.com/google/web-stories-wp/issues/7295

Screen recording: https://jumpshare.com/v/C0nUbGpfw1KnDyrZNqs3

Additional context:
Jetpack plugin version: 1.0.2
Web Stories plugin version: 1.6.0
AMP plugin version: 2.0.11

#### Steps to reproduce the issue

1. Enable Web Stories, AMP & Jetpack Boost setting: Defer Non-Essential Javascript.
2. Add stock photo
3. Add animation
4. Preview story → Image does not display
5. Console error message: https://jmp.sh/BVItuh7

**Comment by jeherve** [comment]
Thanks for the report. We'll take a look and update this issue when we have some news!

**Comment by davidlonjon** [comment]
Hi @LuckynaSan,

Just for info, we have now created in the Jetpack Boost Github repo a PR to fix this which is pending code review and merge. We will let you know when it will get released.

**Comment by jeherve** [comment]
The problem has now been fixed in the development version of the Jetpack Boost plugin, and will be available in the next stable release.

**Comment by LuckynaSan** [comment]
Thank you!

**Comment by davidlonjon** [comment]
Hi @LuckynaSan,

Just to confirm that Jetpack Boost release 1.0.4 including the patch for Web Stories is now live.
