### ISSUE TITLE
Support Core's URL search parameters

### ISSUE THREAD

**Issue by iandunn** [Automattic/jetpack#19657]
#### Steps to reproduce the issue

1. Visit https://jetpack.com/author/robertbpugh/ to see a list of posts that Rob wrote
2. Add a search query to the URL: https://jetpack.com/author/robertbpugh/?s=podcast

#### What I expected

Only posts written by Rob should be searched, like a standard Core search.

#### What happened instead

Posts are not filtered by author, e.g., [a post by Jeremy](https://jetpack.com/2020/05/05/jetpack-8-5-new-podcast-block/) was included.

**Comment by gibrown** [comment]
Duplicate of #17704
