### ISSUE TITLE
Sets which modules get activated by default on subsite connection

### ISSUE THREAD

**Issue by eZwzAEkx** [Automattic/jetpack#19677]

**Comment by jeherve** [comment]
> I checked. This feature was dropped.

Yes, we removed those in Jetpack 2.9, in e303061d561bcb4eaf7165d41cf626bc341419e5. 

If you're looking for something similar, I would recommend that you look into the filters Jetpack offers to achieve similar results. You can check [this post](https://jeremy.hu/customize-the-list-of-modules-available-in-jetpack/) for some ideas, and check the Jetpack codex for a full list of our filters:
https://developer.jetpack.com/
