### ISSUE TITLE
Slideshow: shows hand cursor, but doesn't let drag-swipe

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#19728]
Slideshow block shows hand cursor instead of arrow.

#### Steps to reproduce the issue

1. Go to page Pa8m3Z-WL-p2 or insert a slideshow block with multiple images
2. Look at the frontend of the page
3. Notice how on cursor hover you have hand
4. Try dragging slideshow to sides (as kinda suggested by hand); that doesn't really work. It stays in some kind of drag-state and changes the image when I move the cursor left/right.

#### What I expected
Just arrow cursor.

#### What happened instead

https://user-images.githubusercontent.com/87168/116882667-61d84000-ac2d-11eb-9d45-e77986d18c32.mov

FYI @apeatling I added this to View backlog for triaging

**Comment by glendaviesnz** [comment]
@simison I was only able to replicate this in Firefox, is that the browser you were using? In Chrome and Safari it works as expected with click and drag with the hand moving the images. Will try and work out why firefox is not behaving.

**Comment by glendaviesnz** [comment]
I couldn't work out why this only affects firefox in the frontend but not the editor. https://github.com/Automattic/jetpack/pull/19741 fixes it, but there may well be some other swiper config that could fix it. I tried upgrading to latest swiper but that didn't make any difference.
