### ISSUE TITLE
Jetpack_Google_Analytics has static property $analytics, but it is never set.

### ISSUE THREAD

**Issue by douglas-johnson** [Automattic/jetpack#19755]
#### Steps to reproduce the issue

I am trying to replace the action on `wp_head` in `Jetpack_Google_Analytics_Universal` with my own function in order to connect Google Analytics with my consent mangement.

[Jetpack_Google_Analytics_Universal](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/google-analytics/classes/wp-google-analytics-universal.php#L23) adds an action on `wp_head` ( the function is also called `wp_head` ). That action is added through the constructor.

The instance of that class to which `add_action` refers should be available in the static property `$analytics` in the global instance of [Jetpack_Google_Analytics](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/google-analytics/wp-google-analytics.php#L57).

But, it is instaniated like this: `$analytics = new Jetpack_Google_Analytics_Universal();` without the `self` keyword to indicate that it should be assigned the class property rather than a new variable.

So, when I try to remove the action, `Jetpack_Google_Analytics::$analytics` is always `false`.

Here's what I'm trying to do. Dumping or logging `$jetpack_google_analytics::$analytics` will show that it is false.

```php
function mytheme_replace_google_analytics() : void {
	global $jetpack_google_analytics;

	if ( ! is_a( $jetpack_google_analytics, 'Jetpack_Google_Analytics' ) ) {
		return;
	}

	remove_action(
		'wp_head',
		array( $jetpack_google_analytics::$analytics, 'wp_head' ),
		999999
	);

	add_action(
		'wp_head',
		'mytheme_google_analytics_with_consent_management'
		999999
	);
}
add_action( 'wp_enqueue_scripts', 'mytheme_replace_google_analytics' );
```

**Comment by jeherve** [comment]
Thanks for the report.

Besides the issue you're reporting above, I'm curious if the `jetpack_wga_universal_commands` filter could be helpful for you here. If you're looking to add Google's consent mode to Jetpack's Google Analytics, wouldn't it work to add them there?
Note that I'm not super familiar with Consent Mode so that may not be an option :)

**Comment by douglas-johnson** [comment]
@jeherve Consent Mode is supposed to be supported by Google Analytics, but as far as I can tell the only way to interact with it is to use gtag.js rather than analytics.js. I'm basing that on these two resources, but I would be happy to be prove wrong:

https://support.google.com/analytics/answer/9976101
https://developers.google.com/gtagjs/devguide/consent

I am using https://github.com/kiprotect/klaro for consent managment and all that I need to do is change some attributes on [this script element](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/google-analytics/classes/wp-google-analytics-universal.php#L77).

I had hoped to be able to do that using `script_loaded_tag` but `wp_enqueue_script` was not used here.
