### ISSUE TITLE
Donations: Block is difficult to read when inside a Cover block.

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#19766]
Reported by @desnum :

### Expected behavior
The width of the donations block and the cover block would remain like what is seen in the editor.

### Actual behavior
When the Donations block is used in a Cover block, all of the content appears to become narrow in a column of its own.

![donations-in-cover](https://user-images.githubusercontent.com/43796228/115924878-50817d80-a44e-11eb-9851-5e688a1bd036.jpeg)

### To Reproduce
1. The user had the theme "Purpose" on an AT site, but it appeared to happen in other themes too
2. Create a new page
3. Add a cover block with an image background
4. On top of that cover block, add a Donations block and fill out the info
5. Preview the page
6. Notice the narrow content areas

Chat: 21496483-hc
Slack: p1617476642429200-slack-C03TY6J1A

**Comment by dsas** [comment]
Seems to happen if you have a cover block containing a donations block, and then further cover blocks after the first cover block.
