### ISSUE TITLE
Protect: All IPs are blocked

### ISSUE THREAD

**Issue by tristanleboss** [Automattic/jetpack#1979]
Hello,

I updated JetPack to the latest available version and since then I am unable to login on the 3 blogs I host: every attempt to access the login page results in a direct block (the login page never appears and I get the infamous "Your IP address...").

I had to disable "Protect" because of this issue.

I don't know how Protect works but when I got the first message, I searched for the IP in WordPress database and found nothing. For example, these IPs were blocked: 90.53.123.178, 194.199.216.129, 90.25.177.94. The first one is a genuine IP from the French ISP Orange.

My server uses Varnish but is configured to "pass" every requests to wp-login.php or wp-admin/ folder with code similar to this:

`	if( req.url ~ "^/(allergies/)?wp-admin/" )
	{
			set req.http.X-Varnish-RECV = "pass,admin-media";
			return( pass );
	}`

I am the only one suffering of this issue? How can I help pinpoint the problem on JetPack or in my server's configuration?

Tristan

**Comment by jeherve** [comment]
Thanks for the report!

I believe that's a known issue, and something we're looking at in #1966. Feel free to subscribe to that issue to follow our progress on this.
