### ISSUE TITLE
CLI Generate: Add LICENSE file to templates

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#19802]
Related to https://github.com/Automattic/jetpack/issues/19801, let's add the GPL v2 as a LICENSE file in the skeleton used for all projects.

**Comment by sdixon194** [comment]
I believe this already [exists](https://github.com/Automattic/jetpack/blob/master/tools/cli/skeletons/common/license.txt) in the common skeleton files, unless it needs to be updated?

**Comment by kraftbj** [comment]
You're right; it is there, but doesn't actually include the GPL text. PR incoming.
