### ISSUE TITLE
Jetpack Search: just-in-time message (JITM) shows when user has plan that already includes Jetpack Search

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#19834]
Props to @mdrovdahl for spotting this in p4Kr4c-4bN-p2#comment-18176.

#### Steps to reproduce the issue

1. Create a test site and sign up for Jetpack Complete
2. Go to `/wp-admin/admin.php?page=stats`
3. You may be shown a JITM banner

#### What I expected
As my plan already includes Jetpack Search, I shouldn't be shown an upsell nudge.

#### What happened instead
I was shown an upsell banner for Jetpack Search even though I already have it.

A quick explore in `jitm-engine.php` reveals that the rule is only taking into account monthly and yearly Jetpack addons, and not plans that already include Jetpack Search.

**Screenshots**

<img width="973" alt="Screen Shot 2021-05-13 at 16 15 13" src="https://user-images.githubusercontent.com/17325/118076736-e6357a80-b406-11eb-9d4e-543697d379fc.png">

**Comment by bluefuton** [comment]
@kangzj is working on this in D62298-code.

**Comment by kangzj** [comment]
🚢 Shipped in r226878-wpcom
