### ISSUE TITLE
Images pushing underneath text

### ISSUE THREAD

**Issue by bharper1000** [Automattic/jetpack#19860]
#### Steps to reproduce the issue

1. Go to [](https://artaxis.org/artist/kate-strachan/)
2. Click on an image in the tiled gallery
3. Notice how a horizontal image is way down (have to scroll) and a vertical image is actually underneath the text

#### What I expected
Normally the image is above and sized appropriately over the text

#### What happened instead
The images are pushed way down and below or underneath the image text

**Comment by sdixon194** [comment]
Thanks for the report! I'm having a bit of trouble following the steps to try and reproduce my end. Would you mind clarifying the steps and providing any screenshots where appropriate? 

>The images are pushed way down and below or underneath the image text

Can you clarify what you mean by image text? Is this referring to an image caption or something else?

Any additional info can help us out. Thanks!

**Comment by bharper1000** [comment]
My apologies, we figured out the issue on this end. Thanks for responding, though!
