### ISSUE TITLE
Updating to 3.4.1 caused a strange iframe to appear

### ISSUE THREAD

**Issue by shaunandrews** [Automattic/jetpack#1986]
I just signed in to my site (shaunandrews.com) to update Core and a few plugins, including Jetpack. When I clicked on the update link for Jetpack (on the Plugins page), everything looks normal. The (ugly) status page was doing its thing, and then **boom** an iFrame appeared when it was finished:

![screen shot 2015-04-17 at 12 58 40 pm](https://cloud.githubusercontent.com/assets/191598/7206835/54a36fe2-e503-11e4-8365-ce69ce84ff15.png)

It was a strange experience, to say the least. I'm not sure what other information I can provide. I'm not sure how I would go about reproducing this, but @jeffgolenski asked me to at least drop an issue here.

**Comment by dereksmart** [comment]
Thanks @shaunandrews, you can follow along here though #1840
