### ISSUE TITLE
Tiled Gallery: default style dropdown not working

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/jetpack#19879]
### Steps to reproduce the behavior

1. add the tiled gallery block
2. try to change the style from the default styles dropdown

#### What I expected to happen
the style should change

#### What actually happened
nothing

### Context
empathy testing

#### Is this specific to the applied theme? Which one?
no

#### Does this happen on simple or atomic sites or both?
simple and AT

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
https://www.loom.com/share/ea7f050b00b040c18bdc00e192e6945a

**Comment by simison** [comment]
Moved to Jetpack repo.

cc @WunderBart @fullofcaffeine in case this broke with the latest Gutenberg upgrade.

cc @apeatling can you help triage this?

**Comment by simison** [comment]
Ahh, only now looked the video. Nothing broken here, this works as intended. :-)

@Nic-Sevic the "default styles"  dropdown is meant to define what style should be applied when ever new tiled gallery block is added in the editor.

<img width="376" alt="Screenshot 2021-05-18 at 15 14 05" src="https://user-images.githubusercontent.com/87168/118649001-ae09af80-b7eb-11eb-996c-27b4fcf4c3c3.png">

@mtias was there something planned to make this dropdown little clearer? Maybe a copy change, or moving under "advanced"?

**Comment by Nic-Sevic** [comment]
@simison Ah, TIL! Thanks for clarifying. In this case, I agree with what you say at the end, this is a bit confusing for users
