### ISSUE TITLE
Subscriptions: Show Image when in Subscription Emails when Excerpts Enabled

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#19888]
#### Is your feature request related to a problem? Please describe.

When the Subscriptions feature is set to use excerpts (via Reading > For each post in a feed, include > Summary), images are dropped from the auto-generated excerpt.

#### Describe the solution you'd like

Before the excerpt is displayed, the first image to appear in the post should be displayed.

**Comment by jeherve** [comment]
Closing as duplicate of #2957.
