### ISSUE TITLE
Instant Search: when mobile keyboard is active, modal search input and results are not fully visible

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#19882]
#### Steps to reproduce the issue

1. On an iPad (or simulated iPad via Xcode Simulator) start filling out a search input on a site with Jetpack Instant Search enabled

#### What I expected
When I have the keyboard open, the modal opens scrolled to the top so I can see some results.

#### What happened instead
When I have the keyboard open, only the lower part of the modal is visible so I can't see the modal search input or the first few results.

(Works fine in portrait mode.)

**Screenshots**

<img width="1779" alt="Screen Shot 2021-05-19 at 15 26 28" src="https://user-images.githubusercontent.com/17325/118752214-c7c3f900-b8b6-11eb-9e9b-8484f362b965.png">

**Comment by jsnmoon** [comment]
Apparently, this is a "feature" of [mobile Safari](https://stackoverflow.com/a/66393991).

![dBuYh](https://user-images.githubusercontent.com/4044428/131410042-bd46ad60-4d08-482a-bf22-de8f8e9e44c4.gif)

I really dislike this behavior.
