### ISSUE TITLE
tiled gallery is not centered in the page

### ISSUE THREAD

**Issue by jjgh** [Automattic/jetpack#1989]
When I enable "Display all your gallery pictures in a cool mosaic" the resulting mosaic-styled image gallery is not centered in the page and I can't find a way to do so using the page editor. 

Is this the expected behaviour? Am I doing something wrong? Or is it a bug?

**Comment by jeherve** [comment]
It's most likely because you haven't defined a Content Widget value in your theme. This should help:
http://jetpack.me/support/tiled-galleries/#content-width

**Comment by jjgh** [comment]
Actually `$content_width` is defined, but in CSS I am changing  `.content-width #main` to `width=100%` which originally was 820px. In fact if I set it back to 820px the mosaic gallery is centered. 

I tried setting `$content_width` in functions.php to 900, and setting `.content-width #main` width to 900px, but the gallery will remain centered only up until values of 820px.. could you please advice how can I have a centered gallery in cases like this? Thanks.

How can

**Comment by jeherve** [comment]
Could you post a link to one of your galleries, so I can take a look?

Could you also let me know where I could download a copy of your theme to run some tests?

Thanks!

**Comment by jjgh** [comment]
Sure! I've just sent it through the Jetpack contact form, since I'm having to follow some constraints regarding not making it public before it goes live.... and also.. concerning that.. since I have to put the website from maintenace to online, could you please just give me a rough estimate about when you're going to look at it? If it's now I'll just put it online, otherwise, as soon you will answer here I will. 

This is the theme I'm using: https://wordpress.org/themes/catch-base/
Thanks for your patience and help in advance!

**Comment by jeherve** [comment]
We should get back to you within a day.

**Comment by jjgh** [comment]
Ok! Just tell me what to do and when :)

**Comment by jjgh** [comment]
Got it finally sorted at theme's forums [http://catchthemes.com/support-forum/topic/cant-increase-content_width-in-child-theme/#post-56395]

I had to override a theme function which was setting $content_width (which gets called after my $content_width = x vaiable assignation, I assume).
Thanks for your support though, both here and by mail. :+1:
