### ISSUE TITLE
WordPress plugins JetPack suggestion: About these suggestions link/redirection/page broken

### ISSUE THREAD

**Issue by strarsis** [Automattic/jetpack#19919]
#### Steps to reproduce the issue

1. Search for Jetpack plugin or Jetpack-related feature keyword on a WordPress site with the Jetpack plugin installed + enabled.
E.g. when you search for `facebook` the first result item would be such a Jetpack-suggestion box.
2. Follow the `Learn more about these suggestions.` link.
Notice that the link points to a non-existing resource (Not Found; HTTP 404).

#### What I expected
A page that explains these plugin suggestions, e.g. how they are injected by a WooCommerce plugin, etc.

#### What happened instead
A page not found (HTTP 404) error.
https://jetpack.com/redirect/?source=plugin-hint-learn-support&site=redacted-site-name.localhost
(redirects to)
https://jetpack.com/support/plugin-search-hints?site=redacted-site-name.localhost

**Comment by jeherve** [comment]
Thank you very much for the report. I've now fixed the redirect, the link should now work!
