### ISSUE TITLE
Social Preview: Feature Image does not display on first attempt

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#19916]
#### Steps to reproduce the issue

1. New post, add a featured image.
2. Jetpack menu, Social Preview.
3. Featured image isn't present on the social media cards.
4. Save, leave, etc come back and it works.

#### What I expected
The image to load on the first attempt.

#### What happened instead
It didn't.

**Screenshots**
Of course, I think I saw it once, but having trouble to reproduce it. Not quite sure what's the issue at all yet, but adding it here incomplete for the sake of tracking.

**Comment by glendaviesnz** [comment]
I wasn't able to replicate this.

**Comment by supernovia** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate


📌 FINDINGS/SCREENSHOTS/VIDEO
It works pretty consistently for me (though the [Tumblr preview is squished](https://github.com/Automattic/jetpack/issues/40480)), however I did note it always shows Google Search as the first preview option, which never shows a featured image. Would it make sense to put a different network first?

📌 ACTIONS
- Triaged
- Requested author feedback

📌 Message to Author
@kraftbj do you want us to triage this further? I'm setting it as Triaged for now but leaving it open.

**Comment by kraftbj** [comment]
I'm fine closing it as a fluke; it can always ben opened if there are reports. Given how quiet this issue has been though...

**Comment by kraftbj** [comment]
I'm fine closing it as a fluke; it can always ben opened if there are reports. Given how quiet this issue has been though...
