### ISSUE TITLE
Search: SVG images being served using Photon URL despite being unsupported and displaying as broken links

### ISSUE THREAD

**Issue by eoinsav** [Automattic/jetpack#19925]
#### Steps to reproduce the issue

1. Add a new page and put an SVG image as the first image
2. Publish page
3. Navigate to Jetpack Search and search for this new page
4. See SVG image is being displayed as a broken link

Example: https://eoinbusinesstestsite.com/?s=svg

#### What I expected
The SVG image should not be displayed using a Photon URL since Photon does not support SVG images

#### What happened instead
The SVG image is being served through Photon, which is not supported and therefore displays a broken link

**Screenshots**

<img width="1639" alt="Screenshot on 2021-05-24 at 09-54-33" src="https://user-images.githubusercontent.com/35590156/119381721-1df9b900-bc76-11eb-81ea-aa9ad8ff4a23.png">

<img width="1634" alt="Markup 2021-05-24 at 09 54 11" src="https://user-images.githubusercontent.com/35590156/119381301-05899e80-bc76-11eb-9c28-58e28680fa2a.png">

**Comment by bluefuton** [comment]
Good spot @eoigal!

This is how we handle it in Calypso:

https://github.com/Automattic/wp-calypso/blob/4265ac7786b2331f5c89656650f9b3bd7e3020a6/client/lib/safe-image-url/index.js#L99

**Comment by mdrovdahl** [comment]
Confirmed the fix (deployed today with JP 9.8) here: https://eoinbusinesstestsite.com/?s=svg
![image](https://user-images.githubusercontent.com/474467/120365875-31d39980-c2cc-11eb-8404-fa531479d138.png)

Thanks @bluefuton !
