### ISSUE TITLE
AMP: Slideshow block includes invalid CSS in AMP

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/jetpack#19922]
The slideshow block is including `@media only email` in AMP, which doesn't validate:

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/36432/119376217-8e9dd700-bc70-11eb-90b9-2ec193669ade.png">

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/36432/119376277-9c535c80-bc70-11eb-824b-691426224dcf.png">

The relevant `@media` queries should be stripped out for AMP.

**Comment by jeherve** [comment]
Thanks for the report!

cc @sixhours and @mmtr who worked on #17638, and on improving the styles of blocks in subscription emails in general. Incompatibility with AMP may be an issue with other blocks and may force us to revisit things here.
Internal reference: paYKcK-GA-p2

**Comment by mmtr** [comment]
Yeah, unknown [media types](https://developer.mozilla.org/en-US/docs/Web/CSS/@media#media_types) are ignored by the browser, but they are certainly not valid (I wish we could define custom media types).

As alternative we could replace the `@media only email` invalid media queries, with a selector that is only targeted if an ancestor of the block has a specific class like `is-email`:

```
.is-email .wp-block-jetpack-slideshow {
  
}
```

We'd need then to add the `is-email` class to the body element of the post content when sending emails, instead of removing the `@media only email` line for processing the custom media queries (which was introduced in D51000-code).

**Comment by lakellie** [comment]
Received a user report in 4017709-zen

**Comment by kriskarkoski** [comment]
I believe this is also the cause of the reports on the WP.com side at p1621875444069200-slack-CB0B2G43X

**Comment by jordesign** [comment]
Noting more interactions with users for when this is resolved:

4015770-zd-woothemes
4017590-zd-woothemes
4015563-zd-woothemes
4016319-zd-woothemes
4019202-zd-woothemes
4015748-zd-woothemes
4017577-zd-woothemes
4016523-zd-woothemes

**Comment by pauljacobson** [comment]
I had a report in 3944450-zen too

**Comment by rinazrina** [comment]
Other reports: 

4016360-zd-woothemes
4017054-zd-woothemes
4015297-zd-woothemes

**Comment by geekinthegirl** [comment]
One more report here: 29334842-hc

**Comment by liviopv** [comment]
28397796-hc

**Comment by brucea8c** [comment]
Also on the forums: https://wordpress.org/support/topic/css-syntax-error-in-tag-style-amp-custom-disallowed-media-type-email/

**Comment by lakellie** [comment]
Just noting here we're receiving reports of the same issue for other gallery blocks besides the slideshow block as well - for example, the tiled gallery block.

**Comment by AtrumGeost** [comment]
Got another user with the same issue:

29807268-hc

>CSS syntax error in tag 'style amp-custom'.

The user has an AT site, but I got the same AMP warning on a WordPress.com simple site I own.

**Comment by tanjoymor** [comment]
Another report: 29808173-hc

**Comment by sajmes** [comment]
Another report 4015415-zd-woothemes

**Comment by benchilcote** [comment]
Another report: 22595468-hc

**Comment by sophiegyo** [comment]
Report: 29843238-hc

**Comment by carinapilar** [comment]
Another on 29755177-hc

**Comment by kcswong** [comment]
Follow up 4026998-zen

**Comment by bsanevans** [comment]
Another report: 4025468-zd-woothemes

**Comment by kriskorn** [comment]
29845734-hc

**Comment by mrsjaved** [comment]
Another report here 29026510-hc and a follow-up ticket:
4032155-zd-woothemes

**Comment by hgwaltney** [comment]
Another report: #29893569-hc

**Comment by adelineyaw** [comment]
Another report: 29937201-hc
Follow up: 4039119-zen

**Comment by sdixon194** [comment]
Hey @adelineyaw ! This should have been fixed with Jetpack 9.8 (https://github.com/Automattic/jetpack/pull/19967), which shipped this past Tuesday on 6/1, and I see the site is running the latest version. Do you know if maybe they were looking at an old report? I did some digging and checked a few pages on their site, but didn't see any AMP Validation errors in the console.

I'm not sure how Google Search Console logs those errors, but they may want to see if they can update/re-crawl.

**Comment by adelineyaw** [comment]
Thanks @sdixon194 ! I will follow up to let them know.

**Comment by AtrumGeost** [comment]
Hi folks!

Do you know if the `CSS syntax error in tag 'style amp-custom'.` error is related to this?

I got a user who reported the issue:

![0wJc3q](https://user-images.githubusercontent.com/3696121/122122776-d7b9f480-cdf2-11eb-9002-344291606da2.png)

On this page:

https://belufondart.com.ar/quiensoy/?amp=1

Asked the user to try validating the fix in Google Search Console, but the user got a "cannot validate error".

I tried the AMP Validator but got no errors:

https://validator.ampproject.org/#url=https%3A%2F%2Fbelufondart.com.ar%2Fquiensoy%2F%3Famp%3D1

Offered the user a follow-up here:

4071272-zd-woothemes

**Comment by miguelpeixe** [comment]
I have a user with the same issue. I was not able to reproduce with AMP validators (Google or Amp Project).

30288931-hc
4089669-zen

**Comment by edwinho89** [comment]
4216020-zd-woothemes

AMP Validator shows both affected URLs are working as expected.

https://validator.ampproject.org/#url=https%3A%2F%2Fchinesegoverness.com%2Fconsulting-fees%2F%3Famp%3D1
https://validator.ampproject.org/#url=https%3A%2F%2Fchinesegoverness.com%2Fchinese-nanny%2F%3Famp%3D1

`CSS syntax error` may be a separate issue, as there aren't any errors on web console, nor using http://csslint.net/ as suggested in https://amp.dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors/?format=websites#css-syntax-error

**Comment by kuropixel** [comment]
I have a user with the same issue. I was not able to reproduce with AMP validators, they all said fine. 
The user had the carousel block on the example pages they linked to.
4239495-zd
31221583-hc

**Comment by rw-ye** [comment]
Report of the issue here: 4452926-zd-woothemes

Not sure if it is related, the Google AMP validator showing it working as expected.
