### ISSUE TITLE
Widgets: Facebook to stop supporting Like Box on June 23rd 2015

### ISSUE THREAD

**Issue by ZhangYiJiang** [Automattic/jetpack#1992]
Facebook is officially depreciating the Likebox plugin. The plugin will stop working on June 23rd 2015. https://developers.facebook.com/docs/plugins/like-box-for-pages. 

The plugin is used in the Jetpack widgets module. Facebook recommend transitioning to the Page plugin: https://developers.facebook.com/docs/plugins/page-plugin

**Comment by kraftbj** [comment]
cc: @codebykat

**Comment by jkudish** [comment]
@justinshreve updated this on WP.com today so it just needs to be merged to JP.

**Comment by kraftbj** [comment]
:+1: Noting that the new box has a min-width of 280 so some themes may have issues if the widget area is set to be under that. Not anything we can do about it as it is coming from Facebook.

**Comment by justinshreve** [comment]
Yeah - let's hold off on merging my changes. Trying to figure out a solution.

**Comment by helloari** [comment]
thank you for dealing with this pesky issue!

**Comment by ZhangYiJiang** [comment]
@justinshreve   Hey, just a reminder that this needs to be fixed before deprecation in 5 weeks time. JetPack needs time to be rolled out to the users, so the earlier this happens the better.

**Comment by justinshreve** [comment]
@ZhangYiJiang Yup - It's still on my radar. I still have a patch ready but we are trying to figure out what to do (if we can) about the width issue.

**Comment by georgestephanis** [comment]
@ZhangYiJiang: If need be, we'll push out a point release closer to the expiration.  I'm not going to push out a rushed point release just for this though.  If any other urgent issues come up sooner, this'll get bundled into that.
