### ISSUE TITLE
Story Block: unable to select multiple media items

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#19945]
#### Steps to reproduce the issue

1. On a Jetpack connected site with JP 9.8 active, create a new post and insert a Story Block.
2. Click on the `Select Media` option.
3. Try to select multiple media items by clicking - without using the Shift/Ctrl keys you are only able to select one at a time.

#### What I expected

* When bringing up the media library modal for selecting media items, I should be able to click and select multiple items.

#### What happened instead

* When editing chosen media items, can only select one at a time by clicking.
* If you upload multiple media items at a time, they all show up ok.

**Screenshots**

https://user-images.githubusercontent.com/15803018/119731429-2a2b7500-be34-11eb-81a9-53f0152245d1.mov

**Comment by samiff** [comment]
Also related, when I have selected media items for the Story Block, I would also expect a way to rearrange the ordering of those items say like when editing Gallery block media items:

![Markup on 2021-05-26 at 15:26:37](https://user-images.githubusercontent.com/15803018/119733458-c8203f00-be36-11eb-8a8e-8c7fc85018cf.png)

**Comment by Tug** [comment]
iirc this "select multiple media by default" feature is enabled for galleries only, which are limited to images. Stories can contain both images and videos so we can't have this behavior without updating the media picker component. Would need to investigate into this more in depth

**Comment by Tug** [comment]
This is actually possible with `multiple="add"` (hidden quite deep in the code at the moment), I addressed it with https://github.com/Automattic/jetpack/pull/19996

**Comment by Tug** [comment]
Done in #19996
