### ISSUE TITLE
Connection timeout fails with no error

### ISSUE THREAD

**Issue by koke** [Automattic/jetpack#1994]
I was trying to reproduce a timeout issue as described in http://jetpack.me/support/getting-started-with-jetpack/what-do-these-error-messages-mean/ and I set my php-fpm to use a single server.

When I went to `/wp-admin/admin.php?page=jetpack` and clicked "Connect to WordPress.com", it just loaded the same page after 18 seconds.

I can see that the `jetpackState[error_description]` cookie is set to "Operation timed out after 15001 milliseconds with 0 bytes received", but other than that there was no visible error to the user.

**Comment by oskosk** [comment]
Closing this issue as it's super old and connection flow has changed so much that it may not be happening anymore.
