### ISSUE TITLE
Story Block: having video item in story throws php notice

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#19947]
#### Steps to reproduce the issue

1. On a Jetpack connected site with JP 9.8 active, create a new post and insert a Story Block.
2. Add a video as one of the items to your Story

#### What I expected

* No errors/notices to be generated.

#### What happened instead

* When visiting the published post on the frontend, I see the following notice generated:

```
Notice: Undefined variable: poster_url in /wp-content/plugins/jetpack-dev/extensions/blocks/story/story.php on line 101
```

I used the following video file in my testing:

https://user-images.githubusercontent.com/15803018/119734156-ca36cd80-be37-11eb-8b8d-b649a0b95785.mp4

**Comment by kallehauge** [comment]
As a note to this one, then the notice also appears in the Block Editor if you publish/save the content and refresh but it's the same issue :)

**Comment by Tug** [comment]
Thanks for the report, this should be fixed by https://github.com/Automattic/jetpack/pull/19876
