### ISSUE TITLE
Uncaught SyntaxError: window.WPCOM_site_ID = ; from sharing_add_footer()

### ISSUE THREAD

**Issue by bobbingwide** [Automattic/jetpack#1995]
When running in a local host, with latest version, incl. https://github.com/Automattic/jetpack/commit/55af9979a469790f6ec74f19a28005bd0cc1976b

`Jetpack_Options::get_option( 'id' );` is returning null
This creates invalid JavaScript
`window.WPCOM_site_id = ;`
which produces
`Uncaught SyntaxError: Unexpected token ;`
in Chrome

Workaround:
pass a default value of 0 to Jetpack_Options::get_option('id');
This creates JavaScript
`window.WPCOM_site_id = 0 ;`

Longer term solution:
TBC

**Comment by jeherve** [comment]
cc @aduth

**Comment by aduth** [comment]
@jeherve: Admittedly this should be handled better (it'd be nice to understand the cases in which the `id` option could return null), but I think the change here should have only been applied as part of #1946. As it stands in master, `window.WCPOM_site_id` serves no purpose.

**Comment by samhotchkiss** [comment]
Fixed in 4178c9e92202401b83623ee1b5ab0fe3c3192ff9
