### ISSUE TITLE
Story Block (Android) - Recording Videos Doesn't Work

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#19968]
#### Steps to reproduce the issue

On my device, creating a new story block post and recording a video doesn't work. The video doesn't get uploaded into the post and seems to disappear. Choosing a previously uploaded video works correctly.

**Screenshots**

https://user-images.githubusercontent.com/33553323/119998464-b8bc0580-bf9e-11eb-9c69-c0597999c666.mov

**Device**

- Android Pixel 2XL
- Android 11
- WordPress app 17.3

cc @Tug

**Comment by aforcier** [comment]
Thanks for reporting @sdixon194! I was able to reproduce, and am moving this issue to the WPAndroid repository (https://github.com/wordpress-mobile/WordPress-Android/issues/14787).
