### ISSUE TITLE
Carousel: Large Space Between Image and Description

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#19969]
#### Steps to reproduce the issue

When viewing a gallery using the Jetpack carousel on a mobile device, there's a large gap between the image and the description that wasn't there prior to the refactoring done in https://github.com/Automattic/jetpack/pull/18858

**Screenshots**
**Currently:**

![Screenshot_20210528-103124](https://user-images.githubusercontent.com/33553323/120000495-de4a0e80-bfa0-11eb-8682-db0a7f3ef821.png)
![Screenshot_20210528-103129](https://user-images.githubusercontent.com/33553323/120000496-de4a0e80-bfa0-11eb-94b4-9f7cbcce332f.png)

**Prior to Refactor (Jetpack 9.6)**

![Screenshot_20210528-103217](https://user-images.githubusercontent.com/33553323/120000571-f3bf3880-bfa0-11eb-8045-3e5c73a71e8a.png)
![Screenshot_20210528-103221](https://user-images.githubusercontent.com/33553323/120000575-f3bf3880-bfa0-11eb-82b6-2e863c895288.png)

You can see previously, the image description was visible without scrolling and the gap to click the full size link wasn't so large.

Internal: p8oabR-FS-p2#comment-5324

cc @sgomes

**Comment by sgomes** [comment]
The calculations are done differently than before, but this all it takes is a tweak or two to the CSS.

The info is currently displayed at 85% from the top (0% being the top itself). Should we move it a bit further up to, say, 80%?

**Comment by sdixon194** [comment]
>Should we move it a bit further up to, say, 80%?

Nice! Yeah, let's give that a try first.

**Comment by sgomes** [comment]
@sdixon194 : Created #19986, please give that a try and let me know how it goes!
