### ISSUE TITLE
Image compare block: broken in widget customizer preview

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/jetpack#19963]
On the customizer widgets page the Image compare block can be inserted as a widget fine and appears in widget sidebar as expected, but is broken in the customizer preview.

#### Steps to reproduce the issue
1. In local dev run latest Jetpack and gutenberg master/trunk and latest built of 5.8 core
2. Go to customizer widgets on a non-block theme, eg. tt1 standard and add an image compare block. Notice that preview on right is broken
3. 
#### Steps to reproduce the issue

**Screenshots**
<img width="747" alt="Screen Shot 2021-05-28 at 5 21 57 PM" src="https://user-images.githubusercontent.com/3629020/119934283-a612f200-bfd9-11eb-886c-bfca1df8d255.png">

**Comment by apeatling** [comment]
This will be fixed by https://github.com/Automattic/jetpack/pull/20044
