### ISSUE TITLE
Non-standard `email` CSS media query type causes AMP validation warnings

### ISSUE THREAD

**Issue by westonruter** [Automattic/jetpack#19975]
#### Steps to reproduce the issue

In #17299 and #17705 the use of an `email` media type was introduced:

https://github.com/Automattic/jetpack/blob/9fc01b0b3b9aca686485c4e027f6225b3af7b4f6/projects/plugins/jetpack/extensions/blocks/tiled-gallery/view.scss#L125-L129

https://github.com/Automattic/jetpack/blob/9fc01b0b3b9aca686485c4e027f6225b3af7b4f6/projects/plugins/jetpack/modules/simple-payments/simple-payments.css#L135-L159

As far as I can tell, this `email` media type is non-standard. See [Media Types](https://drafts.csswg.org/mediaqueries/#media-types) in Media Queries Level 4. Because of this, `email` is not included among the media types that [AMP recognizes](https://github.com/ampproject/amphtml/blob/63d8ca9f52bd719880f24248a7c98bbb7c8a56f4/validator/validator-css.protoascii#L770-L780):

```
type: 'all'
type: 'print'
type: 'screen'
type: 'speech'
type: 'tty'
type: 'tv'
type: 'projection'
type: 'handheld'
type: 'braille'
type: 'embossesd'
type: 'aural'
```

And the result is that the AMP Validator issues a validation _warning_ (not a validation error) for the media type, as [reported](https://wordpress.org/support/topic/css-syntax-error-in-tag-style-amp-custom-11/#post-14496377) in the AMP plugin support forum.

What is the purpose of this non-standard `email` media type? How does it work? Is it somehow unwrapped server-side when emails are generated?

AMP's CSS validator spec does include some [non-standard media types](https://github.com/ampproject/amphtml/blob/63d8ca9f52bd719880f24248a7c98bbb7c8a56f4/validator/validator-css.protoascii#L829-L831), so I could open a PR to add `email`. But having some additional background on how it is used would be helpful, and whether there is any popular tooling that makes use of this media type.

#### What I expected

Standard media types should be used in media queries.

#### What happened instead

The non-standard `email` media type was used.

**Comment by jeherve** [comment]
Thanks. This is tracked in #19922. We have a patch for it in #19967.
