### ISSUE TITLE
Story block: doesn't display correctly in customizer preview

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/jetpack#19981]
When used as a block widget the story block doesn't display correctly in the customizer preview page

#### Steps to reproduce the issue

1. In local dev run latest Jetpack and gutenberg master/trunk and latest built of 5.8 core
2. Go to customizer widgets on a non-block theme, eg. tt1 standard and add an story block. Notice that the block doesn't display correctly in the preview window

**Screenshots**
<img width="1122" alt="Screen Shot 2021-05-31 at 10 57 12 AM" src="https://user-images.githubusercontent.com/3629020/120122813-59a8fb80-c1ff-11eb-9356-f9302f67510d.png">

**Comment by apeatling** [comment]
This will be fixed by https://github.com/Automattic/jetpack/pull/20044
