### ISSUE TITLE
Premium content block: subscriber content shows to all when used as widget block

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/jetpack#19982]
When added to a widget area using the new block widgets the subscriber content displays even for logged out users.

#### Steps to reproduce the issue

1. In local dev run latest Jetpack and gutenberg master/trunk and latest built of 5.8 core
2. Go to customizer widgets on a non-block theme, eg. tt1 standard and add a premium content block. Save and view in the front end as logged out user and notice that subscriber only content show by default

**Screenshots**
<img width="1428" alt="Screen Shot 2021-05-31 at 12 27 16 PM" src="https://user-images.githubusercontent.com/3629020/120125219-f96c8680-c20b-11eb-8fa0-b2efd979be2c.png">

**Comment by apeatling** [comment]
On WordPress.com with 5.8 I am not seeing any content load on the front end after saving in the footer widget area.

**Comment by glendaviesnz** [comment]
> On WordPress.com with 5.8 I am not seeing any content load on the front end after saving in the footer widget area.

I am guessing that I experienced this because the premium content block was not fully functional locally, at time of testing I couldn't get running on WPcom, so only tested locally - happy for you to close this if working as expected on WPcom

**Comment by stacimc** [comment]
Confirmed this is working fine on wpcom 👍
