### ISSUE TITLE
Publicize: Google+ adds a "Continue reading →﻿" if the post has an excerpt

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#200]
Steps to reproduce:
1. Create a new post, and add a custom excerpt (note: this does not occur if using the "more" tag)
2. On Google+, the post appears with a "Continue reading →﻿" added to the end of the excerpt

Example:
![screen shot 2013-12-16 at 14 30 15](https://f.cloud.github.com/assets/3676359/2138109/43907068-9330-11e3-83c7-df2e6d4b335d.png)

The "Continue reading" is not a link, and isn't strictly necessary in google+, as the G+ post itself has a clickable link to the WordPress site's post. As well, a user informed me that the text always appears in English, even if the WordPress site is in German.

Additionally, it also adds "continue reading" on a regular post:
![screen shot 2013-12-16 at 13 53 07](https://f.cloud.github.com/assets/3676359/2138123/81ef672e-9330-11e3-9693-bba9114b5499.png)

Ported from https://plugins.trac.wordpress.org/ticket/2087

**Comment by jkudish** [comment]
@richardmtl can you please confirm if this is still an issue and if so re-post it (and link it) on the private io repo

**Comment by richardmtl** [comment]
I can't reproduce anymore, closing.
