### ISSUE TITLE
Admin Page: unhelpful error message without CTA when API requests fail

### ISSUE THREAD

**Issue by keoshi** [Automattic/jetpack#20006]
Today I came across this message while testing some flows. I was using Jurassic Ninja and the server seems to be going through major hiccups, but I'm not sure what the message is trying to communicate.

![image](https://user-images.githubusercontent.com/390760/120473115-97905600-c39e-11eb-84dd-3d4ccd062bd3.png)

**Questions**

- Isn't Jetpack Dashboard a part of my site? If so, why would there be a miscommunication between the two?
- The message isn't that helpful. What's the underlying issue here, and can we explain it better to the customer?
- The next steps are not realistic for the average user, and it seems likely they would get in touch with us ASAP. Could we be sending them to our documentation instead?
- It was my first time seeing this error, but is this common enough that we should spend time on it? How much time?

Code: https://github.com/Automattic/jetpack/blob/ba2dd6c30be137baad96aafb2466d0aed7e182e5/projects/plugins/jetpack/_inc/client/state/site/reducer.js#L143

**Comment by jeherve** [comment]
This will happen when the REST API request used to fetch data that will be used to populate areas of the dashboard fails. 

I don't really know what would be the best suggestion here. In your case, refreshing the page would probably have been enough. On some sites, it may be another plugin that breaks or inserts custom content into the API responses. Maybe we could suggest to try refreshing, and if the problem persists contact support?

**Comment by jeherve** [comment]
Related: #16883 where the messages were introduced.

**Comment by keoshi** [comment]
Ah, that makes sense. Thanks for connecting the dots, Jeremy. And thanks for editing the title, I totally forgot about it.

> Maybe we could suggest to try refreshing

I think that would be a great first tweak. What do you think about this?

> Jetpack encountered an error and was unable to display the Dashboard. Please try refreshing the page. If the problem persists, [get in touch with support](#).

**Comment by jeherve** [comment]
I like it. I gave it a try, using the CTA as its own item to be consistent with the other notices that may be displayed, but that may be a bit long?

![image](https://user-images.githubusercontent.com/426388/120518633-10f56c00-c3d2-11eb-89a1-0533b335d205.png)

What do you think?
