### ISSUE TITLE
Minor language issue: x amount of views singular / plural

### ISSUE THREAD

**Issue by NekoJonez** [Automattic/jetpack#20005]
So, in the stats widget we have a list of the popular posts and pages with the amount of views... 
But, here is the thing that I noticed as a polygot. 

There is no way to put the translation in singular / plural. So, we have to either put the plural between brackets OR have the plural in and have it look a bit strange when it's supposed to be singular. 

This is a permalink to the translation I'm talking about: 
https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/nl-be/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=611393&filters%5Btranslation_id%5D=84519029

So, this should be on stats.php on line 1249. https://plugins.trac.wordpress.org/browser/jetpack/tags/9.7/modules/stats.php#L1249

(Is this correct? Since I don't see the string on said line. But GlotPress says it does)

**Comment by jeherve** [comment]
Thanks for the report! That's indeed something we can improve. The exact line is this one (lines have switched a bit in the last release):

https://github.com/Automattic/jetpack/blob/67f33755ca02981fd12787c3e44853f81990d596/projects/plugins/jetpack/modules/stats.php#L1307-L1308

**Comment by NekoJonez** [comment]
Thx for the fix @coder-karen
