### ISSUE TITLE
External Media: Featured Image ALWAYS asks if I want to use Google/Pexels, but I don't have that activated

### ISSUE THREAD

**Issue by Ipstenu** [Automattic/jetpack#20035]
#### Steps to reproduce the issue

1. Go to make a new post
2. Click on 'Featured Image'
3. Get prompted to use normal upload, google, or Pexels

#### What I expected

Only to get the normal upload

#### What happened instead

I was prompted to use one of three methods to upload. Two of which I don't use and don't want :)

**Screenshots**

![google-pexels](https://user-images.githubusercontent.com/807903/120868596-3b1d6a00-c549-11eb-9901-11f5861b8d77.gif)

I tested this on two sites, one with Jetpack pro, one without, and both have this happen on **featured** images only. Regular inline images are fine.

**Comment by jeherve** [comment]
The feature is indeed active as soon as the site is connected to your WordPress.com account. If you're not interested in it, I would recommend that you deactivate it using a snippet like this one:

```php
/**
 * Remove Jetpack's External Media feature.
 */
add_action(
    'enqueue_block_editor_assets',
    function () {
        $disable_external_media = <<<JS
document.addEventListener( 'DOMContentLoaded', function() {
    wp.hooks.removeFilter( 'blocks.registerBlockType', 'external-media/individual-blocks' );
    wp.hooks.removeFilter( 'editor.MediaUpload', 'external-media/replace-media-upload' );
} );
JS;
        wp_add_inline_script( 'jetpack-blocks-editor', $disable_external_media );
    }
);
```

**Comment by Ipstenu** [comment]
@jeherve Done that but ... your **documentation** says this:

> You can use Pexels for your Jetpack Slideshow Block, Tiled Gallery Block, or Image Compare Block. 

I see it on **featured image**. Which is not listed. So either you need to update your docs OR something's wrong.

https://jetpack.com/support/jetpack-blocks/pexels-free-photo-library/

**Comment by jeherve** [comment]
Good call. I'll update the documentation; the option is meant to be displayed for featured images as well.
