### ISSUE TITLE
Carousel Gallery Lightbox: Broken When Logged In

### ISSUE THREAD

**Issue by snoorev** [Automattic/jetpack#20041]
#### Steps to reproduce the issue

1. Log in as an admin
2. Create post & insert Gallery block
3. Add image to gallery
4. Publish post
5. View post with carousel gallery setting enabled
6. Click on image to open in lightbox
7. Lightbox opens
8. Image does not load

#### What I expected
The image to open in the carousel gallery lightbox.

#### What happened instead
Lightbox opens but image does not load. Cannot close lightbox and have to refresh page to exit the lightbox. Clicking the close X in the upper right does nothing.

**Screenshots**
![jp-screen](https://user-images.githubusercontent.com/85574244/121222691-9f874480-c83b-11eb-9508-1ae1abf67404.jpg)

#### Additional Notes
1. Lightbox works as expected when not logged in.
2. Tested in Brave & Chrome browsers
3. Lazy load is not enabled
3. Deactivated all plugins except Jetpack
4. Tested with Twenty Twenty-One theme
5. Tested on multiple sites (on same VPS server)
6. Issue occurs with Jetpack 9.8
7. Issue resolved after rolling back to 9.7.1

**Comment by jeherve** [comment]
Thanks for the report. The bug was fixed in #20027, and will be available in Jetpack 9.8.1 later today.
