### ISSUE TITLE
Search: Widget settings are not accessible in upcoming widget editor

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#20055]
#### Steps to reproduce the issue

Start from a site using WP 5.8 Beta + Gutenberg, with a site using a Jetpack Search plan.

1. Go to Appearance > Customize > Widgets
2. Go to one of your widget areas.
3. Add a Jetpack Search widget. 
4. Try clicking the "Add filter" button.
5. Nothing happens.

Since the selectors have changed, the widget will need to be updated I believe. 

![image](https://user-images.githubusercontent.com/426388/121479700-97114400-c9ca-11eb-9bad-8d82c3b424b9.png)

**Comment by jsnmoon** [comment]
The core issue seems to be `.jetpack-search-filters-widget` not existing when [`setListeners`](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/widgets/search/js/search-widget-admin.js#L58) is executed.
