### ISSUE TITLE
Widget Visibility: add controls to widget block editor

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#20057]
Related issue: https://github.com/WordPress/gutenberg/issues/31181

Jetpack's [Widget Visibility](https://jetpack.com/support/widget-visibility/) module adds visibility controls to the widgets available in Appearance > Customize > Widgets and Appearance > Widgets

![image](https://user-images.githubusercontent.com/426388/121518801-31847e00-c9f1-11eb-836c-97e4bbc77a80.png)

Those controls are added here:
https://github.com/Automattic/jetpack/blob/41fe374f32d0fa35bb66b4ca492e0b337ee7c6cd/projects/plugins/jetpack/modules/widget-visibility/widget-conditions.php#L12

With the upcoming version of WordPress, the widget UI changes to allow you to insert legacy widgets as well as blocks, in two areas:
- Under Appearance > Customize > Widgets in a refreshed UI.
- Under a new interface at Appearance > Widgets, now loading `themes.php?page=gutenberg-widgets` instead of `widgets.php`.

We'll need to do a few things to ensure that Widget Visibility is compatible with those changes:

- [x] Revisit the changes that were introduced in #17413 to allow the use of Widget Visibility in the block widget editor.
- [x] Update the Widget Visibility JS so it can hook its buttons into the block widget editor as well as the old interface.
- [x] Update its CSS to ensure its layout looks good in the old and the new UI.
- [ ] Ensure that widget visibility controls are displayed for blocks.

*******

Primary issue: #19654 

Related discussion: pbAok1-2dI-p2

**Comment by jeherve** [comment]
Loading the resources in the right screen seems to be possible (I believe something like below should help), but we'll need some extra work to update the JS to target the right elements.

```diff
diff --git a/projects/plugins/jetpack/modules/widget-visibility/widget-conditions.php b/projects/plugins/jetpack/modules/widget-visibility/widget-conditions.php
index 2574690f73..6db2e95047 100644
--- a/projects/plugins/jetpack/modules/widget-visibility/widget-conditions.php
+++ b/projects/plugins/jetpack/modules/widget-visibility/widget-conditions.php
@@ -10,11 +10,13 @@ class Jetpack_Widget_Conditions {
 	static $passed_template_redirect = false;
 
 	public static function init() {
-		if ( is_admin() ) {
+		global $pagenow;
+
+		if ( is_customize_preview() || 'widgets.php' === $pagenow || 'themes.php' === $pagenow ) {
 			add_action( 'sidebar_admin_setup', array( __CLASS__, 'widget_admin_setup' ) );
 			add_filter( 'widget_update_callback', array( __CLASS__, 'widget_update' ), 10, 3 );
 			add_action( 'in_widget_form', array( __CLASS__, 'widget_conditions_admin' ), 10, 3 );
-		} elseif ( ! in_array( $GLOBALS['pagenow'], array( 'wp-login.php', 'wp-register.php' ) ) ) {
+		} elseif ( ! in_array( $pagenow, array( 'wp-login.php', 'wp-register.php' ), true ) ) {
 			add_filter( 'widget_display_callback', array( __CLASS__, 'filter_widget' ) );
 			add_filter( 'sidebars_widgets', array( __CLASS__, 'sidebars_widgets' ) );
 			add_action( 'template_redirect', array( __CLASS__, 'template_redirect' ) );
@@ -22,11 +24,6 @@ class Jetpack_Widget_Conditions {
 	}
 
 	public static function widget_admin_setup() {
-		// Return early if we are not in the block editor.
-		if ( wp_should_load_block_editor_scripts_and_styles() ) {
-			return;
-		}
-
 		wp_enqueue_style( 'widget-conditions', plugins_url( 'widget-conditions/widget-conditions.css', __FILE__ ) );
 		wp_style_add_data( 'widget-conditions', 'rtl', 'replace' );
 		wp_enqueue_script(


```

**Comment by cpapazoglou** [comment]
Reserved for onboarding.

**Comment by cpapazoglou** [comment]
I would suggest limiting the scope of this issue to Legacy Widgets so that it's fully ready and tested when WordPress 5.8 is released and opening (?) a new issue regarding support to blocks which will need a more "Gutenberg" oriented approach rather than using jQuery to inject HTML.

**Comment by cpapazoglou** [comment]
cc: @simison

**Comment by jeherve** [comment]
> I would suggest limiting the scope of this issue to Legacy Widgets so that it's fully ready and tested when WordPress 5.8 is released and opening (?) a new issue regarding support to blocks which will need a more "Gutenberg" oriented approach rather than using jQuery to inject HTML.

That's fair. We can also keep this issue open and add a new item to the task list here.

**Comment by simison** [comment]
Fine by me. 👍 We could even roll with that limited scope and sit back and observe feedback and adjust only later, if ever. Important to consider if it's clear why there's such a difference in UI between different blocks. Please also do inform .com happiness + docs people at pbAok1-2cr-p2 — @jeherve can prolly loop in Jetpack HEs/docs?

**Comment by jeherve** [comment]
> can prolly loop in Jetpack HEs/docs?

@a8ck3n Could you add this to your list for the 9.1.1 release?

In short, Widget Visibility will only work for legacy widgets (i.e. widgets as we know them today) for all folks using the new Widget management screen that will be introduced in WP 5.8. That screen also allows you to add blocks to widget areas, but those will not include any widget visibility controls yet.

Thank you!

**Comment by sdixon194** [comment]
Re-opened because widget visibility settings still need to be addressed for block widgets themselves, especially as more people convert legacy widgets to block, breaking their visibility settings.

**Comment by mtias** [comment]
Should be straightforward to add to the "Advanced" block inspector panel.

**Comment by kathrynwp** [comment]
User in #4191314-zen missing visibility setting on new block widgets. I will try to get them a CSS workaround.

**Comment by kspilarski** [comment]
Block widgets have no visibility options - in 31053707-hc Personal plan

**Comment by yansern** [comment]
Technical discussion on what's involved to add visibility controls to the Advanced panel here:
p1628592283006600-slack-C029WGXE5T4

**Comment by hngdny** [comment]
Affecting Simple Site user on ticket #4211552-zen

**Comment by mzitinfo** [comment]
Another case in 4212591-zen

**Comment by fresatomica** [comment]
Another report here: https://wordpress.com/forums/topic/widget-visibility-on-block-editor/

**Comment by jartes** [comment]
Another report here 29532833-hc. User with a Simple Site with no visibility option (even with Legacy Widgets)

**Comment by simison** [comment]
The fix for legacy widgets got deployed for simple sites (D65412-code, D65394-code)

**Comment by MaxPhilip** [comment]
Another user who needs visibility settings: 4222374-ZD

**Comment by supernovia** [comment]
Another case: https://wordpress.com/forums/topic/hiding-widgets-with-block-editor/

**Comment by mtias** [comment]
@simison is this assigned anywhere yet?

**Comment by simison** [comment]
@mtias No worries, thanks for caring. :-) Another half of these reports were [sorted with the fix](https://github.com/Automattic/jetpack/issues/20057#issuecomment-898233423), and the rest will be sorted by work from Flow patrol.

[Looks like](https://github.com/Automattic/jetpack/pull/20731#issuecomment-900683870) we need design help though, so I've reached out to arrange some eyes for this. (p1629285502046400-slack-dotcom-design)

**Comment by dcoleonline** [comment]
4221429-zen asking for visibility for block widgets

**Comment by mreishus** [comment]
Looking for reviews on https://github.com/Automattic/jetpack/pull/20731

**Comment by the-misha** [comment]
Another request: 28417583-hc

**Comment by jerrysarcastic** [comment]
Request for followup in https://wordpress.com/forums/topic/changing-widget-visibility-in-sidebar/ when visibility is restored

**Comment by simison** [comment]
@mreishus hi! What's the status/timeframe on this?

**Comment by aisajib** [comment]
Another forum post regarding this here: https://wordpress.com/forums/topic/visibility-in-blocks-in-the-widget-area/

**Comment by fresatomica** [comment]
Mentioned here: https://wordpress.com/forums/topic/no-visibility-settings-for-paragraph-block/

**Comment by edwinho89** [comment]
4313215-zd-woothemes

**Comment by sophiegyo** [comment]
Another request came in via 31060326-hc / 4320892-zd

**Comment by mreishus** [comment]
This is scheduled for the next Jetpack release (10.2 on 2021-10-05) and is available on certain WordPress.com plans today (simple). Here's a video of me using the new feature:

https://user-images.githubusercontent.com/937354/134578924-bba9a722-dd30-4657-9d4e-687515e73ef7.mp4

p7DVsv-cIY-p2
