### ISSUE TITLE
Sharing: retire Stumble Upon

### ISSUE THREAD

**Issue by jkudish** [Automattic/jetpack#2005]
Despite supporting https for their script tag, Stumble Upon's sharing badge loads a bunch of http only resources, thus producing mixed-content warnings and not working properly for https sites. Stumble Upon has no plans to update this as per their public documentation. So we've decided to remove support for their service on WordPress.com.

There are definitely way more Jetpack sites still running http so they would be able to continue using Stumble Upon.

I wanted to get your opinion before preparing a PR to remove this from Jetpack as well.

One considerable note: now that we've removed support from WordPress.com, the `https://wordpress.com/sharing/buttons/[site-url]` page on WP.com will no longer allow adding/managing a Stumble Upon sharing button for a Jetpack site either so from now on it will only work from one's wp-admin sharing options page.

My vote is to remove it completely, but still thought it would be good to get the people's opinion first.

**Comment by jeherve** [comment]
Can it be added back via a custom service?

**Comment by jkudish** [comment]
Yes it could, but that of course means that it wouldn't work from an https site and that it couldn't be previewed from the WordPress.com interface.

With that being said, are you okay with me pushing this forward?

**Comment by jeherve** [comment]
Decided in #2005
