### ISSUE TITLE
Subscriptions: Better error message when user has "blocked all emails".

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#2007]
Steps to reproduce.
1. Go to your WordPress.com account Notifications page here: https://wordpress.com/me/notifications
2. Check off "Block all email updates from blogs you’re following on WordPress.com"
3. Try to sign up to any Jetpack connected blog through Subscriptions
4. Get this error:
`There was an error when subscribing. Please try again.`

Problem: That error suggests that there is a problem with Jetpack or our Subscriptions, when really the problem is that they have blocked all emails, so it's *never* going to work.  The `please try again` is deceiving and leads to support emails.

Suggestion: Let's have a better error message!   Something like:
```You are unable to subscribe to this blog right now because you have blocked all emails from your WordPress.com account.  Please enable email notifications by going to your *WordPress.com Notifications page*```

**Comment by richardmtl** [comment]
Note that you can block even without having a WordPress.com account. I suggest directing people to subscribe.wordpress.com instead.

**Comment by jeherve** [comment]
> I suggest directing people to subscribe.wordpress.com instead.

That won't work I'm afraid. If you don't have a WordPress.com account, all subscribe.wordpress.com does is offer you a field where you can enter your email address, and the filed will trigger an email to you with a link to manage your subscriptions.

But since you blocked all emails from WordPress.com, you won't receive that email I guess.

**Comment by richardmtl** [comment]
> But since you blocked all emails from WordPress.com, you won't receive that email I guess.

No, I just tested and even though I blocked all emails from WordPress.com, I *do* still get that email when I enter my test address on subscribe.wordpress.com, so my suggestion still stands. If they have blocked, they will then get an email with a direct link to their settings, which will allow them to unblock.

**Comment by jeherve** [comment]
> even though I blocked all emails from WordPress.com, I do still get that email when I enter my test address on subscribe.wordpress.com

Good to know! :+1:

**Comment by RCowles** [comment]
It would be nice to improve all of the subscription failure messages. See: https://wordpress.org/support/topic/replace-jetpack-error-message-how?replies=1

**Comment by kraftbj** [comment]
The same error is returned when an user has subscribed but not confirmed the pending subscription. We should return a variety of error messages that are user friendly in cases when the potential subscriber can act to resolve.

**Comment by richardmtl** [comment]
This came up again in 2276100-t. It'd be great to get this dealt with.

**Comment by richardmtl** [comment]
again in 2278094-t
