### ISSUE TITLE
Alpha plugin causes hiccup amongst bulk plugin updates on WordPress.com

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#2008]
Edge case for development purposes:

I went to bulk update Jetpack 3.5 via WordPress.com, and got this message:

![screen shot 2015-04-23 at 2 40 35 pm](https://cloud.githubusercontent.com/assets/214813/7305294/dea9f622-e9ca-11e4-9f59-da17b30aaba7.png)

I then realized I had accidentally left a Jetpack Alpha plugin for testing, installed + activated on one of my connected sites. 

Even after I deactivated the alpha plugin, I had to manually update Jetpack 3.5 via wp-admin, because this message would not retreat. 

cc @dereksmart @samhotchkiss can provide more details on the alpha plugin, if necessary.

**Comment by jeffgolenski** [comment]
@beaulebens perhaps you can check to see if this is still an issue. If not, feel free to close.

**Comment by jeherve** [comment]
Closing this, as we don't use this plugin anymore.
