### ISSUE TITLE
Photon: Allow more flexibility for Querystrings in the source URL.

### ISSUE THREAD

**Issue by jbeales** [Automattic/jetpack#2009]
I've got a plugin that displays elements of a Facebook feed on a WP site. I would like to run images in that Facebook feed through Photon to resize them, but the FB CDN hostnames aren't on the approved list of hosts that can have a querystring, (looking at the [Photon repo](https://code.trac.wordpress.org/browser/photon) it seems like graph.facebook.com is the only hostname that's got querystring permission baked in to the code).

Could all hosts be opened up to having querystrings in the source URL?

**Comment by jeherve** [comment]
I'd recommend using the `jetpack_photon_add_query_string_to_domain` and `jetpack_photon_any_extension_for_domain` filters to add your own domains, as it's done here for Facebook:
https://github.com/Automattic/jetpack/blob/4.4.2/functions.photon.php#L230-L234
