### ISSUE TITLE
Identity Crisis check: Unreadable Notice

### ISSUE THREAD

**Issue by desrosj** [Automattic/jetpack#2010]
Upgraded to 3.5 on a staging site. There is a notice at the top of the screen saying the site_url is different than the one set up for the wordpress.com integration. No big deal, however it is not readable unless you highlight it, and the links in the notice do not work.
![GitHub Logo](https://cldup.com/GqqwPFBrJ4.png)
![GitHub Logo](https://cldup.com/q2llQKD8kR.png)

When you go to the Jetpack admin screen, that notice is the same, above all the content, and autohides after a few seconds.
![GitHub Logo](https://cldup.com/0V-Kw1nd6H.png)

**Comment by chuckreynolds** [comment]
also the ignore link and the 3rd link don't do anything. can't get rid of the warning. will look for another issue related to that.

**Comment by dereksmart** [comment]
@desrosj @chuckreynolds - Thanks for the report, we are already working on a fix.  

If disconnecting/reconnecting doesn't resolve the problem or is not an option, you can hide the notice for the time being with a little css: 

```
.jp-identity-crisis {
  display: none;
}
```

**Comment by samhotchkiss** [comment]
Fixed by eb0d2ea322d5482b1816096bdb23d3ddd4f7f2c2
