### ISSUE TITLE
Widgets: Upcoming Events missing from Jetpack 3.5 install

### ISSUE THREAD

**Issue by danyork** [Automattic/jetpack#2011]
Just installed Jetpack 3.5 on a WordPress 4.2 running in MultiSite mode.   Announcement referenced that an "Upcoming Events" widget would now be available, but I can't find it in the list of available widgets:
![jetpack-3-5-no-upcoming-events](https://cloud.githubusercontent.com/assets/41662/7307181/d6f1f00c-e9d8-11e4-9435-5508a487aa4a.png)

Also can't find any mention of "Upcoming Events" on the "Extra Sidebar Widgets" page.

The "announcement" I'm referencing is the ChangeLog  when you go into the details for the Plugin:

![jetpack-3-5-changelog](https://cloud.githubusercontent.com/assets/41662/7307239/794e8e82-e9d9-11e4-8334-09ce44331d04.png)

Was this widget removed from the release and the announcement wasn't updated?

Thanks for all the great work you do!

**Comment by danyork** [comment]
Confirmed on a standalone (_not_ MultiSite) installation of WordPress 4.2 and JetPack 3.5.

**Comment by kraftbj** [comment]
Hi Dan,

Thanks for the report. The changelog was inaccurate; the widget isn't quite ready for primetime. We've updated it to remove reference to it.

Cheers!

**Comment by danyork** [comment]
Ah, too bad.  I was looking forward to using that widget!   If you're looking for beta testers of that I'd be glad to help.  Thanks for the news!

**Comment by newlocalmedia** [comment]
It's still showing up in Jetpack's description.
![screen shot 2015-07-02 at 5 14 47 pm](https://cloud.githubusercontent.com/assets/273554/8489121/ecec9592-20dd-11e5-832e-baeeb971716f.png)

**Comment by kraftbj** [comment]
thanks @newlocalmedia!

@jeherve or @dereksmart can we remove strings after string freeze or does this need to be 3.7?

**Comment by jeherve** [comment]
> can we remove strings after string freeze

Yes, that won't be a problem. d35315453d36fb8dd301ebcb63f57a6548012321

@dereksmart Could you review and add to `master-stable` if you're happy with the change?

Thanks!

**Comment by dereksmart** [comment]
@jeherve done, and will be in 3.6
