### ISSUE TITLE
Mail tracking analysis once post is published 

### ISSUE THREAD

**Issue by PahadiSparrow** [Automattic/jetpack#20112]
#### Is your feature request related to a problem? Please describe.
Hello Jetpack Team, we are unable to track the mail analysis, how many have interacted to the post they received. 

#### Describe the solution you'd like

Better if we have analytics that mail send to like E.G 1000 users received  , 800 have opened and clicked the link.
This should be on per post basis.

**Comment by jeherve** [comment]
Thanks for the report. This is currently tracked in #6513. I'll close this issue as duplicate.
