### ISSUE TITLE
Nova menu order and term_ids

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#2012]
Jetpack's has a custom content type of Nova Menus to provide a way for restaurants to manage their online menus. Yum! Their is also a custom taxonomy of Menu Sections which can be sorted by in any order the admin chooses. The order of the menu sections is stored as an array of term_ids in an wordpress option

With WordPress 4.0's new and improved handling of term_ids, the Menu sections will break. 

Here's how we reproduce:
1. On a testing site, downgrade to WordPress 4.0
2. Install the Confit theme
3. create two menu sections - one called “Drinks”, one called “Desserts”
4. create a post category called “desserts”, and then rename it to “yummy treats” - verify that the menu section was also renamed
5. create a two menu items - one in the “yummy treats” section and one in the “drinks” section
6. go to `wp-admin/edit.php?post_type=nova_menu_item` and reorder the sections so that 'Yummy Treats' are above 'Drinks'
7. Create a page called 'Menu' - view the page and verify the 'Yummy Treats' are above 'Drinks'
8. Upgrade WordPress to 4.2 ( or latest version )
9. Rename the 'Yummy Treats' menu section to 'Desserts'
10. Go to the Menu page, and see that Drinks are now above Desserts - _our order is broken_

This is really edge-case-y, so it may not be worth fixing.  But it is a good example of how the new term handling can cause problems.

To fix, we'd simple need to hook into `split_shared_term` as outlined here:
https://make.wordpress.org/core/2015/02/16/taxonomy-term-splitting-in-4-2-a-developer-guide/

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
