### ISSUE TITLE
Post by email failing to publish images

### ISSUE THREAD

**Issue by StefMattana** [Automattic/jetpack#20132]
The issue has been reported by several users in the forum: 

- https://wordpress.org/support/topic/post-by-email-suddenly-rejects-images
- https://wordpress.org/support/topic/about-blogs-with-images-using-jetpacks-mail-posting-function/#post-14577694

The users report not being able to publish the post at all, or reporting an ` Unknown token` error upon publishing the post. I am running the latest version of Jetpack and WordPress.

I was initially unable to reproduce it, but I did it on my second attempt. Here's the email I received when [the post got published](https://cloudup.com/ck65mLiaHEC):

<img width="711" alt="Screenshot 2021-06-21 at 08 51 08" src="https://user-images.githubusercontent.com/11662998/122726425-e4649f80-d26d-11eb-8ede-c6ca1810783c.png">

That's the same email some users reported as well. Another user in the forum thread reported some PHP logs [here](https://wordpress.org/support/topic/post-by-email-suddenly-rejects-images/#post-14577675). 

I asked the users to share as much info as possible, I hope they can contribute to this thread directly. 

If you need any more info from me, happy to dig into that further.

**Comment by jeherve** [comment]
> I did it on my second attempt

Could you provide some steps you followed, as well as info about the version of Jetpack you use on your site and the specific of the image you used?

Thanks!

**Comment by StefMattana** [comment]
Sure - Worpress v. 5.7.2 - Jetpack v 9.8.1. My test site is hosted at Pressable. I'm working on Chrome Version 91.0.4472.106 MacOS 11.4

I tried posting via email in different ways, and all resulting eventually in the same email subject `Failed attachments for <<date of the post>>` plus `Unknown token` error in the body message. 

I attached first a 2.5MB jpeg file, then I embedded in the email body message a 1MB png file, then I attached another small size (700KB) png file. All my attempts resulted in the posts being published, but also with emails reporting the image file rejection. 

On my second and third attempts, I kept enabled only the Jetpack and Jetpack CRM plugins. 

I then cycled the Jetpack connection, and tried again, this time by attaching a 784KB png image along with the text. Same error. 

Let me know if I can provide something else to help you debug this!

**Comment by bobmatyas** [comment]
Another report on: https://wordpress.org/support/topic/failure-of-posting-images-on-blog-by-email/?view=all

They are using WordPress v5.7.2 and Jetpack v9.8.1

**Comment by JenSwish** [comment]
Post by email issue found in 4081856-zen.

Asking for permission to use creds. Will update here when I know more.

User provided this screenshot: 
![IMG_1760](https://user-images.githubusercontent.com/7818778/122768869-a2d1f580-d269-11eb-93bd-2c8c9ba3dc90.jpg)

Let me know if there's anything else to ask the user to provide.

**Comment by Nic-Sevic** [comment]
This is also happening on AT sites with an associated issue opened in the calypso rep here:
https://github.com/Automattic/wp-calypso/issues/53846#issue-925393065

example user report: 4079323-hc

**Comment by bigbetchannel** [comment]
Wordpress version: 5.5.3
Jetpack version: 9.4

attached screen is the error reported back to my email. same to @StefMattana 
![Screenshot 2021-06-21 at 10 13 35 PM](https://user-images.githubusercontent.com/86244247/122776971-2af1e280-d2de-11eb-924f-0457da212b44.png)

**Comment by kraftbj** [comment]
Crew will look into it to see what changed. At first glace, r227478-wpcom looks very notable.

**Comment by jeherve** [comment]
This is being looked at:

https://github.com/Automattic/wp-calypso/issues/53846#issuecomment-865091509

**Comment by jeherve** [comment]
This should now be fixed. I'll close this issue now.
