### ISSUE TITLE
HTTPS-sourced Images Not Passed to Photon on HTTP Site

### ISSUE THREAD

**Issue by macmanx2** [Automattic/jetpack#2015]
With the release of WordPress 4.2, images uploaded when the Dashboard is HTTPS will be added to the post as `src="https` regardless of what the siteurl is: https://core.trac.wordpress.org/ticket/15928#comment:97

This means that Photon can be met with an HTTPS image on an HTTP page and won't be able to collect the image without the following added to a must-use plugin, a theme's functions.php file, or its own plugin:

`add_filter( 'jetpack_photon_reject_https', '__return_false' );`

You can see an example of the problem at http://macmanx.com/testing-image/ (where the HTTPS-sourced image is not being served from Photon)

Considering that this is now how core operates, that there is a larger push to protect wp-admin via HTTPS, that not as many are forcing HTTPS on the frontend (because caching), and that the whole thing pretty much breaks Photon with no user-friendly way to fix it, perhaps it's time to revisit this?

**Comment by kraftbj** [comment]
I need to look up the history on why we reject HTTPS images by default, but changing the default behavior has a :+1: from me. 

Marking for 3.5.1 initial consideration since it does basically "break" Photon for 4.2 HTTPS users. Okay with punting to 3.6 if too big of a change for a point release or needs further conversation.

**Comment by jeherve** [comment]
[Here is the ticket](https://plugins.trac.wordpress.org/ticket/1653) where the filter was introduced. Related commits are 5ab9318622a2121f8d09916ab2c913c0ad9f6041 and 897ec5e2a86d8f09e35ef9d19c1168d28a094f4a.

We'd have to loop in Systems on that one, since I believe HTTPS being off by default was their decision.

**Comment by macmanx2** [comment]
Oddly enough, the issue only affects single embedded images, not galleries.

**Comment by joemcgill** [comment]
@kraftbj there's a good chance that a piece of the change in https://core.trac.wordpress.org/ticket/15928#comment:97 may get rolled back. The details of that discussion are happening here: https://core.trac.wordpress.org/ticket/32112#comment:23 in case you have any input.

**Comment by macmanx2** [comment]
That would definitely "fix" the immediate problem, but we should still figure out why Photon is refusing to collect and serve images when they're sourced over HTTPS on an HTTP site.

**Comment by macmanx2** [comment]
As of WordPress 4.2.2, this was "fixed" by WordPress now using the siteurl for sourcing media. If it's HTTP, so's the sourced media, which means Photon can collect the image.

I still think maybe we should re-think whether or not Photon should collect HTTPS-sourced media, so I'll leave closing this at your discretion.

**Comment by macmanx2** [comment]
Commenting, because I like to. :)

HTTPS/SSL is becoming a big thing in the web these days. It's the best way to stay secure on public WiFi, extensions like https://www.eff.org/https-everywhere are forcing all sites into HTTPS, new groups like https://letsencrypt.org/ and are providing free SSL certificates to everyone, Google https://support.google.com/webmasters/answer/6073543?hl=en is giving a boost to HTTPS sites, and some hosts are even defaulting to HTTPS.

But, Photon is still disabled by default on HTTPS-sourced images. Even if the entire site is HTTPS and the Photon module is enabled, the above filter must be added for Photon to even attempt storing a copy of an HTTPS-sourced image, effectively crippling the feature and turning Mosaic Galleries into a load time liability (without Photon, the full original image is loaded and scaled by the browser).

With HTTPS practically becoming the lay of the land, perhaps it's time to get rid of this filter, and start supporting HTTPS-sourced images in Photon by default?

**Comment by kraftbj** [comment]
Just need to get the nod for #2992!
