### ISSUE TITLE
Subscriptions block: Improve mobile layout

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#20162]
#### Is your feature request related to a problem? Please describe.
Subscriptions block has an option to display the button on a new or the same line. Having both button and input on the same line tends to look good on desktop, and poorly on mobile (because the button stays on the same line across all screen sizes). This leads to less than ideal situations like this:

![image](https://user-images.githubusercontent.com/4550351/123184244-a28a6200-d4d6-11eb-82a3-36350141f08b.png)

or, if there was more horizontal padding, something more extreme:
![image](https://user-images.githubusercontent.com/4550351/123184315-c6e63e80-d4d6-11eb-987e-aae5473630bf.png)

#### Describe the solution you'd like
Given the limited space on mobile, could we either:
* make the button always be on a new line on mobile? 
* add an option for button placement on mobile?

I like the first option better because forcing the button to be on the same line on mobile leaves considerably less space for the input, making it less accessible as well. Are there any drawbacks to making that default behavior?

**Comment by kwight** [comment]
This was fixed at some point – both setting look good now for an iPhone 6, for example.

| Same line | New line |
| --- | --- |
| <img width="419" alt="Screen Shot 2021-08-17 at 9 54 57 AM" src="https://user-images.githubusercontent.com/349751/129768677-63881813-14fd-4293-b07b-39455e8c68e8.png"> | <img width="434" alt="Screen Shot 2021-08-17 at 9 55 17 AM" src="https://user-images.githubusercontent.com/349751/129768685-b49e7af3-b3d8-4347-840e-f84981790373.png"> |

**Comment by mtias** [comment]
This can still render broken:

<img width="462" alt="image" src="https://user-images.githubusercontent.com/548849/154679122-c8ad871a-fb7c-4442-b12b-8c757981a30b.png">
