### ISSUE TITLE
Full Site Editing Compatibility: Multiple Blocks - "This Block Has Encountered an Error..."

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#20184]
#### Steps to reproduce the issue

- Test a site using FSE (Make sure latest Gutenberg is active and using a block theme, TT1 Blocks)
- Go to the Site Editor
- Add any of the following blocks to a FSE section, like the footer: 
	- image compare block
	- pay with paypal block
	- story block
- See that "This Block Has Encountered an Error and Cannot Be Previewed"
	 - console error: `TypeError: wp.Uploader is undefined` in Firefox
	 - console error: `typeError: Cannot read property 'limitExceeded' of undefined` in Chrome
	 - console error: `TypeError: undefined is not an object (evaluating 'wp.Uploader.limitExceeded')` in Safari
- Add any of the following blocks: 
	- slideshow
	- tiled gallery
- See that "This Block Has Encountered an Error and Cannot Be Previewed"
	- console error: `wp.media.view.settings.attachmentCounts is undefined` in Firefox
	- console error: `TypeError: Cannot read property 'audio' of undefined` in Chrome
	- console error: `TypeError: undefined is not an object (evaluating 'wp.media.view.settings.attachmentCounts.audio')` in Safari

Error occurs even on latest stable, using the beta on Master, on WordPress 5.7.2 and 5.8-beta4.

**Screenshots**

![image comopare](https://user-images.githubusercontent.com/33553323/123476287-7f40df00-d5ca-11eb-9464-25f7fbaf0806.png)

**Comment by jeherve** [comment]
Related:

- [ ] Pay with Paypal: #12801 and its matching PR: #20064 
- [ ] Map Block: #19896 

Internal reference: p1624860512114800-slack-CS0SC36SX

**Comment by jeherve** [comment]
This was fixed in https://github.com/WordPress/gutenberg/pull/33145

**Comment by Greatdane** [comment]
This issue is closed, but I have an encountered it today here; 4293592-zd-woothemes

Turning off the `full-site-editing` plugin fixed the issue for now.

**Comment by inaikem** [comment]
@jeherve just in case the issue reported above by @Greatdane is related to this issue 🙏

**Comment by jeherve** [comment]
@inaikem That's hard to say without any more details. I would suggest checking for Javascript errors on the page, as explained here:
https://wordpress.org/support/article/using-your-browser-to-diagnose-javascript-errors/

Let me know what you find!

**Comment by Greatdane** [comment]
I should have said sorry - I saw no JavaScript errors on the Chrome console.

**Comment by jeherve** [comment]
@Greatdane Are you able to reproduce on another site, by any chance, with that same theme or with another?

**Comment by Greatdane** [comment]
I have not been able to reproduce it, unfortunately. I assume a distinct set of circumstances on that site (a combination of the installed plugins and theme?) caused the issue to appear.

**Comment by jeherve** [comment]
👍 I'll close this issue again, and we can reopen in the future if this happens again.
