### ISSUE TITLE
Milestone Widget: PHP Notice in block widget management page

### ISSUE THREAD

**Issue by spacedmonkey** [Automattic/jetpack#20208]
While testing the new widget editor screen found in WordPress 5.8 / gutenberg, I saw a notice error. See screenshot. See the orignal ticket https://github.com/WordPress/gutenberg/issues/33056

#### Steps to reproduce the issue

1. Install jetpack plugin.
1. Activate plugin
1. Setup wordpess.com account.
1. Jetpack > Settings > Writing > Widgets. Enable widgets.
1. Insert milestone (jetpack) widget.
1. Preview widget.

#### What happened instead

**Screenshots**
<img width="662" alt="Screenshot 2021-06-28 at 23 02 10" src="https://user-images.githubusercontent.com/237508/123717942-ddddb580-d875-11eb-9606-be6f77df1910.png">

**Comment by jeherve** [comment]
Thanks for the report, we'll take a look at this. 

Primary issue: #19654.

**Comment by jeherve** [comment]
This appears to be a Core issue. This is currently tracked here:
https://core.trac.wordpress.org/ticket/53548
