### ISSUE TITLE
Carousel: update paths to images to use CDN

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/jetpack#20221]
### Description

Currently the image icons  in the carousel module are mapped to a local `./images` folder. While this currently works, it may be more efficient, particularly on WPcom, to map these to a CDN instance of the images.

See https://github.com/Automattic/jetpack/pull/20107#discussion_r660519441 for background.

**Comment by ramonjd** [comment]
Just looking around here. I think we could get away with removing the image directory altogether.

Unless I'm missing something, we've entirely switched over to SVGs and the [single reference](https://github.com/Automattic/jetpack/blob/95a7b30c34fcb57eadc352e03b4b21ab49af5446/projects/plugins/jetpack/modules/carousel/jetpack-carousel.css#L296) to `images/` no longer has a corresponding element (`a.jp-carousel-commentlink`).

I'll test this and throw up a PR
