### ISSUE TITLE
Carousel: Add support for smooth scrollTo on mobile when opening/closing comments section

### ISSUE THREAD

**Issue by andrewserong** [Automattic/jetpack#20251]
On mobile we currently don't have support for `behavior: 'smooth'` for [Element.scrollTo](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo), which means that when we open/close the comments of info sections at the bottom of the carousel they snap open / closed instead of smoothly scrolling the viewport to that section of the page.

Let's investigate adding in a JavaScript approach to smooth scroll those sections into view.

#### Steps to reproduce the issue

1. With the Carousel module in Jetpack enabled, go to a post containing an image gallery, using a mobile device
2. Tap on an image to open up the Carousel on mobile
3. Tap on the comments or info icons in the footer

#### What I expected

The viewport to smooth scroll down to the comments area

#### What happened instead
The viewport snaps down to the position of the comments area

**Screenshots**

https://user-images.githubusercontent.com/14988353/124200821-9d05cb00-db19-11eb-8d65-21e4733e4547.MP4

**Comment by ramonjd** [comment]
I've had a hunt around for low-footprint ways to address this.

Based on the size of [this polyfill](https://github.com/iamdustan/smoothscroll/blob/master/src/smoothscroll.js), which attempts to get around this very issue and is recommended about the place, maybe there's no "ideal" solution.

I'm starting with something like this, which seems to go okay (no easing yet):

```js
	var domUtil = ( function () {

		....

		function scrollToElement( el ) {
			// Some touchscreen devices do not support the `behaviour: smooth`
			// option for Element.scrollIntoView().
			if ( util.isTouch() ) {
				smoothScroll( el );
				return;
			}

			...
		}

		function smoothScroll( el ) {
			var elementScrollHeight = el.scrollHeight;
			var container = document.querySelector('.jp-carousel-overlay');
			var increment = 10

			container.scrollTo( 0, container.scrollTop + increment );
			if ( container.scrollTop < elementScrollHeight ) {
				window.requestAnimationFrame( function() { smoothScroll( el ); } );
			}
		}

```

**Comment by andrewserong** [comment]
I thought I might have a go at this one today or next week (but feel free to jump in if anyone else would like to, I know you've been looking at it, Ramon!)

I think there'll be a subtle bit of work to get scrolling _up_ to work on desktop as well as mobile — we probably want to delay hiding the extra footer area until the browser has scrolled up, otherwise the close action will still be a "snap" instead of a smooth scroll.

**Comment by ramonjd** [comment]
> I thought I might have a go at this one today or next week 

Go for it! 

> we probably want to delay hiding the extra footer area until the browser has scrolled up, otherwise the close action will still be a "snap" instead of a smooth scroll.

Good point. In that case it might make sense to invest in a custom JS scroll solution that does it all rather than relying on the native scrollTo method 🤔

**Comment by andrewserong** [comment]
I've made a start on exploring an approach in #20318, and I'll continue exploring this on Monday 🙂
