### ISSUE TITLE
Carousel: Fine tune the icons

### ISSUE THREAD

**Issue by pablohoneyhoney** [Automattic/jetpack#20266]
Perhaps already in consideration for further iterations, but worth looking at a few details now that we are in a better place. For example, icons. 

Tested on desktop Safari 14.0.2, iMac Big Sur 11.1, and mobile iOS iPhone Pro Max 14.6.

Icons seem too thick, the wp/icons are at 1.5 line weight, the below don't seem to match that. Especially how they are rendered in mobile views, not sure what's happening here. 

![Image from iOS](https://user-images.githubusercontent.com/25516611/124509261-a1dbb080-dd9f-11eb-9d13-83955b029db3.png)

The image above also shows arrows that were meant to evolve as well so all UI elements work cohesively together. 

<img width="752" alt="Screen Shot 2021-07-05 at 2 42 07 PM" src="https://user-images.githubusercontent.com/25516611/124509301-b5871700-dd9f-11eb-9304-c4936725bc6d.png">

The comment and info icons also seem to collide with the divider on desktop.

<img width="219" alt="Screen Shot 2021-07-05 at 2 34 45 PM" src="https://user-images.githubusercontent.com/25516611/124509738-6988a200-dda0-11eb-8139-a6711a772dcd.png">

cc @olaolusoga @apeatling

**Comment by apeatling** [comment]
Completely missed the change in next/prev arrows. Will get those fixed up.
