### ISSUE TITLE
Tiled Gallery: Transform From Gallery Doesn't Work

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#20264]
Similar to: https://github.com/Automattic/jetpack/issues/14536

- Add a gallery block and some images
- Transform the block into a tiled gallery block
- See the blank images.
- Save draft or refresh
- The block is now totally blank.

Clicking on the block, the blank images seem to fix themselves, but upon saving and refreshing, the block is blank again.

Surfaced again during internal testing p8oabR-GM-p2#comment-5385

**Comment by rinazrina** [comment]
I can reproduce this issue on my test site. Found the issue during Empathy Testing. 

This issue also happens when transforming an Image block to the Tiled Gallery block. 

Screencast below:

https://user-images.githubusercontent.com/33721365/124580319-94e3bd80-de82-11eb-99cc-99abb28fe88f.mp4
