### ISSUE TITLE
Cannot remove hooks from filter 'jetpack_get_available_modules'

### ISSUE THREAD

**Issue by RavanH** [Automattic/jetpack#2026]
In fact, the title of this bug report is incorrect because removing hooks from that filter can certainly be done. However, it describes the effect of the underlying issue well.

The underlying issue is that after Jetpack::get_available_modules() has been run once, any filter hooks have been applied to the static $modules variable so removing these hooks has no effect anymore. Jetpack::get_available_modules() will still return a filtered modules list!

**Comment by jeherve** [comment]
Fixed in 6960589bce1f2b0917f92cac8445a85c4a817fde
