### ISSUE TITLE
Carousel swiper css overrides other swiper based plugins

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/jetpack#20289]
#### Steps to reproduce the issue

1. On a local test site install newspack blocks and jetpack
2. Turn on jetpack carousel and add a page with the Post Carousel block and a gallery
3. In frontend notice that the Post carousel overflows the page

<img width="1919" alt="Screen Shot 2021-07-07 at 4 37 38 PM" src="https://user-images.githubusercontent.com/3629020/124702490-852cad80-df44-11eb-9fd5-c54b7e45b655.png">

**Comment by ChrisBegley** [comment]
I just came here to report the same issue. I'm having a conflict with a widget on my homepage that also uses Swiper. 

I tried to get around it using this code snippet, but unfortunately it didn't work:

`
> // First, make sure Jetpack doesn't concatenate all its CSS
> add_filter( 'jetpack_implode_frontend_css', '__return_false' );
> 
> // Then, remove each CSS file, one at a time
> function jeherve_remove_all_jp_css() {
> if(! is_single()) {
>   wp_deregister_style( 'jetpack-carousel-swiper-css' );
> }
> }
> add_action('wp_print_styles', 'jeherve_remove_all_jp_css' );
`

**Comment by jeherve** [comment]
@ChrisBegley Thanks for the warning. We're working on a fix in https://github.com/Automattic/jetpack/pull/20290 . Until we release an update, instead of removing the CSS entirely, it may be worth trying to add some additional CSS targeting your widget, like in the example here:
https://github.com/Automattic/wp-calypso/issues/54340

Let us know how that goes!

**Comment by ChrisBegley** [comment]
@jeherve thanks! Unfortunately it's a premium plugin, it's a YouTube gallery widget: https://codecanyon.net/item/youtube-plugin-wordpress-gallery-for-youtube/14115701

**Comment by jeherve** [comment]
Thank you!

If you'd like to give the fix a try, here is how you can go about it:

1. Upload, install, and activate [the Jetpack Beta plugin](https://github.com/Automattic/jetpack-beta/releases/latest/download/jetpack-beta.zip)
2. Go to Jetpack > Beta
3. Search for the following branch: `fix/corousel-css-leakage-bug`
4. Once that branch is active, see if the problem disappears on your site.

Let me know how it goes!

**Comment by ChrisBegley** [comment]
@jeherve That fixed it! You guys are fast. Thanks for the quick fix!

**Comment by jeherve** [comment]
Excellent, thanks for letting us know! Once the new version is out, don't forget to switch back to "stable" in the Jetpack Beta options, and maybe deactivate and delete the Beta plugin after that. :)

**Comment by zdenys** [comment]
AT site with OceanWP theme 4120895-zd-woothemes

**Comment by i11za** [comment]
AT site with cgb-child theme 4121434-zd-woothemes

**Comment by bizanimesh** [comment]
Hey - One related issue is here: https://wordpress.org/support/topic/jetpack-9-9-bug

**Comment by fernandotellado** [comment]
Another issue probably related to this thing:
https://wordpress.org/support/topic/cannot-read-property-split-of-undefined-at-jetpack-carousel-min-js/

**Comment by philnick206** [comment]
Reported in #30506609-hc
AT site with goodz-magazine theme, using Elementor.

**Comment by madhattermattic** [comment]
Also reported in this forum post:
https://wordpress.org/support/topic/galleries-not-opening-to-full-images/#post-14635884

**Comment by bobmatyas** [comment]
Also reported in 4122870-zen

**Comment by AnthonyFaxlandez** [comment]
Also reported in 4122869-zen

**Comment by bobmatyas** [comment]
Another on 4122464-zen

**Comment by apeatling** [comment]
Will be fixed in Jetpack 9.9.1

**Comment by pauljacobson** [comment]
@apeatling Our user in 30530425-hc needs to resolve this issue ASAP. They can't wait for the expected Jetpack 9.9.1 update on ±20 July. Is there an interim solution we can offer our users?

**Comment by jeherve** [comment]
@pauljacobson They could install [the Jetpack Beta plugin](https://jetpack.com/download-jetpack-beta/), go to Jetpack > Beta, and pick the "Release Candidate" option to get the fix on their site.

**Comment by pauljacobson** [comment]
> @pauljacobson They could install [the Jetpack Beta plugin](https://jetpack.com/download-jetpack-beta/), go to Jetpack > Beta, and pick the "Release Candidate" option to get the fix on their site.

Awesome, thank you @jeherve

**Comment by i11za** [comment]
AT site with Chronicle theme 4124906-zd-woothemes

**Comment by bobmatyas** [comment]
Additional reports here:

https://wordpress.org/support/topic/jetpack-9-9-bug/#post-14640238

https://wordpress.org/support/topic/image-carousel-not-functioning-correctly/?view=all

**Comment by jp-imagines** [comment]
Additional report in 29312266-hc. AT site with the Morden theme.

**Comment by bobmatyas** [comment]
Additional report here:

https://wordpress.org/support/topic/my-goodness-the-carousel-is-messed-up-on-v9-9/?view=all

**Comment by sajmes** [comment]
AT with Organization theme 3679546-hc

**Comment by edwinho89** [comment]
30530834-hc for visibility

**Comment by liviopv** [comment]
Another 6437250-hc. Loading the RC using the Beta plugin worked.

**Comment by jp-imagines** [comment]
Another in 14512928-hc, AT site with a third-party theme. CSS workaround resolved the issue.

**Comment by JoshuaGoode** [comment]
After running into a few issues with the latest RC, please do not install Beta plugins on WordPress.com sites.

Please use the CSS method mentioned on https://github.com/Automattic/wp-calypso/issues/54340 instead.

**Comment by sajmes** [comment]
30653475-hc AT site. Used CSS workaround.

**Comment by jp-imagines** [comment]
Another in 30715311-hc. AT site using Elementor for an image slider. Gave CSS workaround.

**Comment by sdixon194** [comment]
Just noting that this should be fixed when 9.9.1 gets shipped tomorrow.

**Comment by hngdny** [comment]
This was still happening on 30733613-hc, AT site - CSS workaround solved the issue for now.

**Comment by sdixon194** [comment]
@hngdny The Atomic release happened quite a bit later yesterday after the interaction, so I'd recommend they check again now, it should be fixed 🤞

**Comment by danielmatthew** [comment]
Hello,

Sadly, the Swiper styles supplied by Jetpack are continuing to overriding my author styles. Per the [advice in the forum post](https://wordpress.org/support/topic/carousel-issues-in-jetpack-v9-9/),  I have [supposedly] disabled the Carousel module, and these styles are still being pumped into `jetpack.css?ver=9.9.1`.

<img width="1055" alt="Screenshot 2021-07-22 at 08 55 42" src="https://user-images.githubusercontent.com/111794/126606619-853e78e5-61ee-4d09-8cb9-b01ca3d763a2.png">
<img width="478" alt="Screenshot 2021-07-22 at 08 57 19" src="https://user-images.githubusercontent.com/111794/126606624-8fddd6c6-7a77-42b1-845b-cc613fb01724.png">
<img width="325" alt="Screenshot 2021-07-22 at 08 59 43" src="https://user-images.githubusercontent.com/111794/126606902-6933ff6c-0d3e-494c-b133-ed82ba497156.png">

Do I need to double-up the specificity of all my selectors (or `!important` them), or is there another technique I can consider?

**Comment by danmaze** [comment]
Jetpack's swiper CSS still overrides another site theme's swiper CSS: 4163919-zd-woothemes

Here's the screenshot they sent:

![image](https://user-images.githubusercontent.com/50293775/126653820-4a52db64-f055-48ae-868b-b47a8734be29.png)

They've had to disable Jetpack's CSS entirely.

**Comment by cornuz** [comment]
On JetPack v.10 there's still the conflict with Swiper integration. Need to disable Carousel in JetPack setting to solve.

**Comment by sdixon194** [comment]
@cornuz Thanks for letting us know - there is a fix that has been merged here: https://github.com/Automattic/jetpack/pull/20599

The fix won't be live until Jetpack 10.1 launches, which should be the first week of September.
