### ISSUE TITLE
Carousel: add option to display "View Full Size" button when Metadata display is disabled in the Jetpack settings

### ISSUE THREAD

**Issue by ChrisBegley** [Automattic/jetpack#20291]
**UPDATE:** Right now the "View Full Size" button only shows up if "Show photo Exif metadata in carousel (when available)" is enabled. It'd be nice if there was a way to have the "View Full Size" button always be visible. Maybe it could be its own button next to the "Info" button. 
--- ----
The new Carousel included in Jetpack 9.9 is great but it's missing a useful feature from the previous Carousel. 

I'd love to see the "View Full Size" button added back so that users can download or view high resolution images. 

<img width="220" alt="Screen Shot 2021-07-07 at 1 19 05 AM" src="https://user-images.githubusercontent.com/7050515/124704014-5caf9f80-dec1-11eb-9945-c3ac44577fd6.png">

**Comment by jeherve** [comment]
You should see the link when clicking on the "Info" bubble while in the Carousel view:


https://user-images.githubusercontent.com/426388/124713647-1c701180-df01-11eb-8b9d-9f0a39e2aa3a.mov


Do you not see it on your end? If so, could you send us a link, so we can take a closer look?

**Comment by ChrisBegley** [comment]
@jeherve Thanks, I see it now! I had "Show photo Exif metadata in carousel (when available)" disabled which hides the "Info" button with the "View full size" link. 

I still think it'd be nice to have the Exif data hidden and still have the "View full size" button available, but it's good to know that it is there. Thanks for letting me know!

**Comment by jeherve** [comment]
> I still think it'd be nice to have the Exif data hidden and still have the "View full size" button available

I've updated this issue's title accordingly. 👍

**Comment by KokkieH** [comment]
We've had a request in the WordPress.com forums to also still have the image description visible, if available. It makes sense to me to also have that under the Info button.

@jeherve should I open a separate feature request for that, or could we hit two birds with one stone here?

**Comment by ricjcs** [comment]
> We've had a request in the WordPress.com forums to also still have the image description visible, if available. It makes sense to me to also have that under the Info button.
> 
> @jeherve should I open a separate feature request for that, or could we hit two birds with one stone here?

I also wanted this feature. I was going to open a new request.

**Comment by sdixon194** [comment]
> We've had a request in the WordPress.com forums to also still have the image description visible, if available. It makes sense to me to also have that under the Info button.

@KokkieH Wow nice find there. I'd definitely open another issue and link this one, since they'll likely require two different fixes.

**Comment by KokkieH** [comment]
@sdixon194 thanks.

I did some testing to make sure, and it appears the description does actually show when the info button is clicked, so if the info button is always available regardless of Exif data settings, that would solve this as well.

But I've opened a separate issue in case we prefer to solve these another way.

**Comment by KokkieH** [comment]
Noting here that adding the following CSS code to Additional CSS in the Customizer makes the View Full Size link visible without needing to click on the info button if image metadata is enabled, and it also makes the link visible if image metadata is disabled. Via p7DVsv-cmU-p2

`.jp-carousel-info-extra,
.jp-carousel-image-meta {
    display: block;
}`

We can offer this as a workaround for now.
