### ISSUE TITLE
Donations: Missing closing div breaks content layout

### ISSUE THREAD

**Issue by nudgeD** [Automattic/jetpack#20309]
#### Steps to reproduce the issue

1. Create a new page
2. Insert Donation block
3. Insert full-width column block right after.

#### What I expected
To see a full-width block after the Donation block.

#### What happened instead
I'm using Twenty Twenty-one theme. There appears to be a missing closing `</div>` in the Donation block's markup which causes the blocks underneath to break. You can see the live version of the screenshot at P5VgET-TS-p2
<img width="462" alt="Donation-full-width" src="https://user-images.githubusercontent.com/978114/124957551-371cb600-dfe7-11eb-9a73-fd362119da7c.png">

Inserting an `HTML` block with only a closing `</div>` after the Donation block fixes the problem temporarily although the div gets removed once you go back into the page. 

Possibly related #19766 and #18165

**Comment by nicolynramos** [comment]
I have another report here: 4192742-zen

In this instance, the block was inside a column which caused issues. Moving the block outside of the columns affected the rest of the page as reported here.

**Comment by jordesign** [comment]
Confirmed this again in further testing - both on Simple and Atomic sites on WPCOM

**Comment by dolgelukkig** [comment]
Another report 4418555-zd
Suggested work around.

**Comment by jordesign** [comment]
Another report in 4450639-zen

**Comment by jromales** [comment]
Another report in 4608087-zd-woothemes

**Comment by inaikem** [comment]
@edequalsawesome would it be possible to put the workaround up on Theme Quirks? From an [earlier report](https://github.com/Automattic/jetpack/issues/20309#issuecomment-942701957): 

> The workaround is adding a custom HTML block after the donation block and adding a closing div tag (i.e. `</div>`) in the custom HTML block

**Comment by jordesign** [comment]
Another report in 33489358-hc
