### ISSUE TITLE
Manage: Activate Now button isn't pretty in smaller viewports

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#2031]
We should make this button look nicer:
![screen shot 2015-04-27 at 8 32 42 am](https://cloud.githubusercontent.com/assets/3220162/7351122/1e48e38e-ecb8-11e4-9471-e9d682ba5173.png)
![screen shot 2015-04-27 at 8 34 00 am](https://cloud.githubusercontent.com/assets/3220162/7351126/2c2f9998-ecb8-11e4-879c-9315ee3c8acd.png)
cc @jeffgolenski

**Comment by jeffgolenski** [comment]
Thanks for finding this. Will look into it tomorrow!

**Comment by georgestephanis** [comment]
needs moar `white-space: nowrap;`

**Comment by mikeyarce** [comment]
Steps to reproduce:
1. Make sure you're connected to WordPress.com and all modules are active.
2. Deactivate Manage module
3. Visit site's Dashboard
4. Tested at 3.5 in Chrome 42.0.2311.90

**Comment by jeffgolenski** [comment]
Fixed in: https://github.com/Automattic/jetpack/pull/2045
