### ISSUE TITLE
JS Packages: add build tasks to composer.json

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#20330]
#### Steps to reproduce the issue

1. Start from a site with an active Jetpack Search subscription, using the Jetpack Beta plugin, and with the branch from #20252 (`add/search-admin-page-footer`) active.
2. Follow the instructions in #20252.
3. You will not see the component used in the footer.

I think that may be because the JS packages do not have `build-production` and `build-development` tasks that would allow them to get built.

@anomiex Could that be it, or is the problem something else here?

**Comment by anomiex** [comment]
1. Created a JN site (profitable-quokka) with that branch and a "Jetpack Complete" license issued.
2. Went to https://profitable-quokka.jurassic.ninja/wp-admin/admin.php?page=jetpack-search&a8ctest
3. Footer is present. Not sure what else I'm supposed to be looking for.

While I see no build steps listed in composer.json in js-packages/connection and js-packages/components, I also see no sign that there are any build steps for either one in package.json or elsewhere.

Sanity check: Did you rebuild Jetpack itself to pick up the new component?

**Comment by jeherve** [comment]
I do see the footer too, now. I must have picked the branch before it was finished rebuilding after its last commit. False alert :)

Thanks for looking. 

> Sanity check: Did you rebuild Jetpack itself to pick up the new component?

It did work for me locally, so it was okay there.
