### ISSUE TITLE
Infinite Scroll: next page doesn't load if there is no scroll bars in the browser. 

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#2034]
In some instances if the height of the browser window doesn't have scroll bars when the page loads. The user is not able to load more posts since the scroll event is never fired. 

One way this could be solved if introduce a slight scroll bars to the browser or just load the next page right way until the browser has scroll bars again.

**Comment by dereksmart** [comment]
Do you have a URL handy where this is happening?  I assume it's on a site that is using a custom implementation of IS, with a low number of posts loaded initially.  By default we load 7 posts, which should be enough to expand beyond viewport height.

**Comment by enejb** [comment]
You can try this by changing the theme to have height:10px on the post div.
Which should result in the no scroll bars after the page loads. 

Let me know if you still have problem replicating this issue.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
