### ISSUE TITLE
Language mix in subscription confirmation email

### ISSUE THREAD

**Issue by knutsp** [Automattic/jetpack#20374]
#### Steps to reproduce the issue

1. Change site language to nb_NO. 
2. Add a subscription widget
2. Enter an email and click on '.Subscribe'
3. Go to your inbox
4. See confirmation email
5. 
#### What I expected

An email in Norwegian only, at least for the main text, instructions and button

#### What happened instead

The confirmation email in both English and Norwegian. As an example, It tells the reader to press a button labelled "Bekreft" (Norwegian for "Confirm"), but there is no such button. Result is lost subscribers.

**Screenshots**

![bilde](https://user-images.githubusercontent.com/1531128/125784619-55647684-0f13-4f35-b534-165e0705aa65.png)

Mixed language email are considered spam here. Internet user are generally advised not to click on links/buttons in email that are either unexpected or not properly spelled i Norwegian, as that's typical for spammers. Pure English is not a problem. There is no way to remove the translations from translate.wordpress.com when first translated. 

I have translated both Jetpack at wordpress.org and wordpress.com trying to fix this for all users in my language, but it doesn't have the expected effect. I build sites, and advise others in finding solutions, and Jetpack Subscriptions has not yet passed as fit for it, as the emails looks hopelessly unprofessional, and I can't control their content and language in any way.

**Comment by jeherve** [comment]
Thanks for the report. That's unfortunately a known issue with subscription emails. It's currently tracked in #1122. I'll close this as duplicate, and mention your issue there.
