### ISSUE TITLE
Subscriptions: Cannot use multiple instances on a single page

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#2038]
Currently, if you add a widget, and use the shortcode (e.g. in a sticky post) to add 2 subscription forms to the page, you can't use the one in the sticky post. The fields end up with the same HTML name/id, and the JavaScript doesn't allow you to submit the one in the sticky post because there's nothing in the first box, which is what it's checking before allowing submission.

- add a subscription widget to your sidebar
- create a sticky post
- add the subscription shortcode to the stick post
- put an email in the sticky post instance of the subscription form
- click submit
- note that the form doesn't submit, and focus goes back to the email field

**Comment by dereksmart** [comment]
Fixed in #2056 :)
