### ISSUE TITLE
Stats: warning on all pages when Stats are active

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#204]
I couldn't reproduce the issue, but this was reported a while ago in [#1830-plugins](https://plugins.trac.wordpress.org/ticket/1830):

---

I got this at the top of my wordpress blog:

```
Warning: array_intersect() [function.array-intersect]: Argument #2 is not an
array in /www/htdocs/w00da800/wp-content/plugins/jetpack/modules/stats.php on
line 117
```

I tried to deactivate all the other plug-ins one by one, but it doesn't work.
I've updated the jetpack plug-in today to the newest release, no failure before
the update.

---

**Comment by LvanProosdij** [comment]
I do have this bug right now, look here : http://blog.van-proosdij.fr

![screen shot 2016-03-23 at 12 12 54](https://cloud.githubusercontent.com/assets/6991846/13983543/a0caf38c-f0f0-11e5-98ea-f423823acd8a.png)

**Comment by jeherve** [comment]
@LvanProosdij Do you use a role or user management plugin on your site? If so, could you try to deactivate it and let me know if it helps?

**Comment by slimndap** [comment]
I also have it:

<img width="1238" alt="screen shot 2016-10-15 at 14 10 18" src="https://cloud.githubusercontent.com/assets/2284714/19410046/3f28ea78-92e2-11e6-9931-eac00a6d23db.png">

Happens in a multi site install, with all other plugins disabled, hosted on SiteGround.

**Comment by jeherve** [comment]
@slimndap Your problem seems different from the one reported here. Could you double check and make sure you're running the most recent version of Jetpack on that site?

If you continue to experience issues, could you [open a new issue](https://github.com/Automattic/jetpack/issues/new), paste the error messages there, and let me know if you use Jetpack's Development mode on that site? If so, how did you enable Dev mode?

Thanks!

**Comment by richardmtl** [comment]
This came up in 3076486-t but have asked for more info

**Comment by michaelryanmcneill** [comment]
I'm able to reproduce this error on my install. I'd like to work to further troubleshoot it with a member of the Jetpack team. Should I open a priority ticket or should we work through it here?

**Comment by michaelryanmcneill** [comment]
Specifically, the error:

```
Warning: array_intersect(): Argument #2 is not an array - wp-content/plugins/jetpack/modules/stats.php:154 

array_intersect() - wp-content/plugins/jetpack/modules/stats.php:154
stats_template_redirect() - wp-includes/class-wp-hook.php:298
do_action('template_redirect') - wp-includes/template-loader.php:12
```

**Comment by jeherve** [comment]
@michaelryanmcneill could you [send us an email](https://jetpack.com/contact-support) with as much information about your site as possible? (version of PHP, active plugins, version of WP and Jetpack)

Thank you.

**Comment by michaelryanmcneill** [comment]
As quickly as it appeared...it disappeared. No more issue now...I'll contact if it reoccurs. Thanks!

**Comment by sereedmedia** [comment]
I currently have this issue on a fresh install with no other plugins active. It's a Dreamhost DreamPress install, everything updates and I just activated the included Jetpack Premium and it is now throwing this error on all front-end pages:

Warning: array_intersect(): Argument #2 is not an array in /home/[redacted]/[redacted]/wp-content/plugins/jetpack/modules/stats.php on line 154

I did just activate WordFence to get some deets in the hope it might help solve the issue. WordFence being activated didn't change anything I could see. 

Please let me know if other information would be useful.

============


<img width="832" alt="jetpack-error-no204-1of6" src="https://cloud.githubusercontent.com/assets/28426780/25734835/9f66d4d6-311b-11e7-8142-0c894d501247.png">
<img width="831" alt="jetpack-error-no204-2of6" src="https://cloud.githubusercontent.com/assets/28426780/25734832/9f65ff0c-311b-11e7-8064-cacdac738a12.png">
<img width="870" alt="jetpack-error-no204-3of6" src="https://cloud.githubusercontent.com/assets/28426780/25734837/9f6e06f2-311b-11e7-9db0-e96a0e290c23.png">
<img width="859" alt="jetpack-error-no204-4of6" src="https://cloud.githubusercontent.com/assets/28426780/25734836/9f681dd2-311b-11e7-9974-e2d0d62cee71.png">
<img width="850" alt="jetpack-error-no204-5of6" src="https://cloud.githubusercontent.com/assets/28426780/25734834/9f66c59a-311b-11e7-990a-9940594795ab.png">
<img width="858" alt="jetpack-error-no204-6of6" src="https://cloud.githubusercontent.com/assets/28426780/25734833/9f6677b6-311b-11e7-8119-d0298eb2b2d0.png">

**Comment by jeherve** [comment]
@sereedmedia Could you tell me more about the different registered users you have on the site? DO you have one admin or more?
Could you also tell me what's selected in your stats options under Jetpack > Settings?

Thanks!

**Comment by sereedmedia** [comment]
There were no other registered users. Only a single admin account. It was a
completely fresh DreamPress install using twenty-fifteen and I activated
Jetpack Premium when it was offered.

I changed some of the settings today and the issue has resolved. i'm not
sure what time it resolved, i wasn't working to resolve it, i was ignoring
it and going about setting up pages and plugins.

I did not change the stats settings at all however.

this site isn't in production yet so if you would like me to, i can turn
back off plugins and try to recreate the error state to retrieve settings.

Thanks,
@sereedmedia


​

**Comment by jeherve** [comment]
Thanks for the extra details! We'll see if we can reproduce on our end as well.

**Comment by jackromano** [comment]
I had the same problem and what seems to have fixed it for me was: Jetpack > Site Stats > Configure > Uncheck all under "Count the page views of registered users who are logged in."

**Comment by chaselivingston** [comment]
Also reported in 3221036-t

**Comment by kraftbj** [comment]
7212 will prevent the error from being thrown, but not whatever is busting the option itself, which is curious. My hypothesis is object caching tripping up. When the stats_option is called, it ends up calling a function to insert in the default options if none set, so an empty string shouldn't be returned. Curious, but the end result will be the same.
