### ISSUE TITLE
Back-end Tracking package doesn't trigger an event on Atomic sites

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/jetpack#20401]
#### Steps to reproduce the issue

In context of https://github.com/Automattic/jetpack/pull/20400 I've tried to add a new tracking event that should trigger on Atomic and WPCOM environments. However, the implementation on Atomic was not triggering, even though the parameters and the event format were correct.

After debugging the issue, I've noticed that the Tracking package is using behind the scenes the [legacy client that calls the pixel](https://github.com/Automattic/jetpack/blob/e40ad6ea30a2ac9f5add8c00c1bfce1c1f567fdb/projects/packages/tracking/legacy/class-jetpack-tracks-client.php#L68). In there we are checking only if the user has agreed to the ToS, meanwhile in the Tracking package [side we also checking if the user is connected or not](https://github.com/Automattic/jetpack/blob/c5a770f7d3a06be3480484fecf70924a5af3378f/projects/packages/tracking/src/class-tracking.php#L224).

#### What I expected

To be able to use the Tracking package on Atomic sites.
#### What happened instead
The tracking is not working since the ToS is not explicitly agreed on AT sites.

**Comment by anomiex** [comment]
Tracking package has been abandoned and merged into the Connection package. See #23448.
