### ISSUE TITLE
Notifications: Update to `v1.1` client

### ISSUE THREAD

**Issue by dmsnell** [Automattic/jetpack#2041]
Tracking https://github.com/Automattic/notifications-client/issues/515

**Comment by dmsnell** [comment]
RIght now the notifications panel is displaying fine in the admin view, but on the front page, it never loads the notes, staying at the blank page.

https://cloudup.com/cCNjgGq-RFh

**Comment by dmsnell** [comment]
In line 18 of `admin-bar-v2.js`, the code isn't seeing `$('#wpnt-notes-panel2')` like it should. Actually, it's not even showing `$('#wpnt-notes-panel')`, but I'm not sure why. Because it doesn't see the element, it doesn't load the iFrame.

Timing issue? Maybe the script is running before the element is loaded?

**Comment by zinigor** [comment]
This is resolved in 3.7, thanks @dmsnell !

**Comment by dmsnell** [comment]
w00t! @zinigor. what's our current status - are we loading the new notes client in Jetpack 3.7 as well?

**Comment by zinigor** [comment]
@dmsnell what do you mean as well? :) Yes, the code will get shipped in 3.7.

**Comment by dmsnell** [comment]
oh cool. @zinigor I just wasn't sure what you were referring to in "This is resolved," whether you meant the bug in the previous comment or the fact that we are shipping the new client in v3.7

**Comment by dmsnell** [comment]
Merged in #2403
