### ISSUE TITLE
VIdeo Player Issue in X Theme + Jetpack v9.9

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#20412]
#### Steps to reproduce the issue

This just needs a site with X theme install and a video embed. 

X theme:
https://theme.co/x

Tested with the default version of X theme (latest version).

#### What I expected

Video player should work in X theme as with previous versions of Jetpack

#### What happened instead

Once you update to Jetpack v9.9 the videos stopping working.

Video player worked without issue in Jetpack v9.8.1. Downgrading from v9.9 fixes the issue. 

**Screenshots**

![x-theme-ZrZYAG_p](https://user-images.githubusercontent.com/45246438/126344639-b9ee1af6-35bb-42bc-bb0a-d5f95be7942b.jpeg)

**Comment by bobmatyas** [comment]
Reported on:

* 4158114-zen
* 4160504-zen

**Comment by bobmatyas** [comment]
There are reports of this on the X theme forums:

* https://theme.co/forum/t/header-video-suddenly-not-displaying/90490/10
* https://theme.co/forum/t/video-player-suddenly-stop-working/90482/7
* https://theme.co/forum/t/background-video-not-playing-anymore/90675/3

**Comment by bobmatyas** [comment]
This issue was not resolved when updating to Jetpack v9.9.1.

**Comment by sdixon194** [comment]
Seems both us and the theme developers [have asked for the same testing](https://theme.co/forum/t/header-video-suddenly-not-displaying/90490/13) - switching to Twenty Twenty One and seeing if the issue persists there. Seems likely something that would need to be fixed on the theme's end, but if the theme devs have more info after running their tests we can take a closer look.

**Comment by lakellie** [comment]
We heard back from the user in 4158114-zen and the issue does _not_ persist after switching to Twenty Twenty One. I asked them to follow up in the X Theme forum thread.

**Comment by sdixon194** [comment]
@lakellie sounds like they're working with the theme devs now. I'll close this issue, and if they come back and notice some specific issue on Jetpack's end that we can address or if we get more reports, we can re-open.
