### ISSUE TITLE
Beta Plugin: Notice when installing a plugin.

### ISSUE THREAD

**Issue by kbrown9** [Automattic/jetpack#20421]
#### Steps to reproduce the issue

1. Install a plugin.
2. See this notice in the error log:

```
Notice: Undefined index: plugin in .../wp-content/plugins/jetpack-beta/src/class-hooks.php on line 118
```

(This doesn't prevent the plugin from being installed.)

**Comment by anomiex** [comment]
Looks like this was fixed by #20491.
