### ISSUE TITLE
Carousel: display image description even if Exif data is hidden

### ISSUE THREAD

**Issue by KokkieH** [Automattic/jetpack#20470]
#### Is your feature request related to a problem? Please describe.

With the redesigned gallery carousel, one has to click an Info button to reveal the image description.

![kokkiestrialtestsite_–_General_testing_and_troubleshooting](https://user-images.githubusercontent.com/11873759/127289797-816dfba0-9ea7-4d0d-bbc8-697850dcf2c9.png)

However, that button is only visible when the media setting to show Exif data is enabled. If Exif data is hidden, the info button itself disappears, leaving no way to view the description. Related: #20291

#### Describe the solution you'd like

Either the description should always be visible, i.e. not hidden behind the Info button. Or else the info button should not be dependent on Exif data visibility settings. The latter option would solve both this issue and #20291

#### Additional context

Requested in the WordPress.com forums in https://wordpress.com/forums/topic/image-description-missing-in-carousel-view/

Internal: p7DVsv-cmU-p2

**Comment by KokkieH** [comment]
Another person looking for the image description in the carousel in https://wordpress.com/forums/topic/re-gallery-block-not-displaying-information/

**Comment by danjjohnson** [comment]
Another two requests via the Jetpack forum:
https://wordpress.org/support/topic/carousel-problem-6/

**Comment by joweber123** [comment]
Another similiar request here - 4187000-zen  

User would like the option to show description without having to click the info button.

**Comment by KokkieH** [comment]
Noting here that adding the following CSS code to Additional CSS in the Customizer makes the description visible without needing to click on the info button if image metadata is enabled, and it also makes the description visible if image metadata is disabled. Via p7DVsv-cmU-p2

`.jp-carousel-info-extra,
.jp-carousel-image-meta {
    display: block;
}`

We can offer this as a workaround for now.

**Comment by mikeicode** [comment]
Another: 4155752-zd-woothemes

We also used the following CSS. The carousel is 100% height by default, so the user needs to scroll to see the text if only the CSS above is used. Example:

![Screen Capture on 2021-08-05 at 06-55-18](https://user-images.githubusercontent.com/10353785/128339227-c089e0ce-1902-4b50-822f-7ddc662dc72c.gif)

```
.jp-carousel-container {
    max-height: 80%;
}
```

That CSS decreased the height so the text was visible without scrolling.

**Comment by rossanafmenezes** [comment]
Another: 31011736-HC

**Comment by samiff** [comment]
Another [request](https://wordpress.org/support/topic/carousel-descriptions-hidden/) from Jetpack forum.

**Comment by cuemarie** [comment]
Another report / request to resolve: 4228518-zen

**Comment by AtrumGeost** [comment]
Got another request here: 4230392-zd-woothemes

**Comment by kelasante** [comment]
Got another request in 31218893-hc

**Comment by sdixon194** [comment]
This should be included in 10.1 launching early September per https://github.com/Automattic/jetpack/pull/20747
