### ISSUE TITLE
WordPress.com profile header shows on jetpack.com when user is unauthenticated

### ISSUE THREAD

**Issue by amustaque97** [Automattic/jetpack#20486]
#### Steps to reproduce the issue

1. Log in to Wordpress.com
2. Navigate to wordpress.com/me 
3. Click on log out button
4. In the URL bar type `jetpack.com` and open

#### What I expected
On jetpack.com, there should be no top header showing gravatar icon and other links. When I click on the profile link. It redirects me to the login page. Perhaps this is happening because of cookies. `wpc_wpc` cookie is showing profile data like username, email and access token even if I'm not authenticated. This should not happen. I have tested this issue in both chrome and firefox.

If you're not able to reproduce. Please let me know. If I can share screen recording.

#### What happened instead
I should not see the top header unless I'm an authenticated user.

**Comment by jeherve** [comment]
I can't seem to be able to reproduce on my end. I tested in Chrome and in Firefox. It would seem like you were not fully logged out indeed.

Could you give us more information about your browser, your setup, and whether you can reproduce when you try in a different browser?

Thank you!

**Comment by amustaque97** [comment]
Hey @jeherve here is the screencast link: https://drive.google.com/file/d/12mzxUYi9CnZU1dJFGlyo6ioGb5pnL2LX/view?usp=sharing

I can reproduce this issue in the firefox browser as well. I'm using latest version of browsers and my operating system is windows 10.

**Comment by jeherve** [comment]
Thank you!

Do you happen to use browser extensions that may have an impact on your cookies?

Do you experience the same issue when trying to follow those steps on a mobile device, when you're not connected to your local WiFi network?

**Comment by amustaque97** [comment]
I think I got your point. I'm not able to reproduce this issue on mobile. 

On my desktop, I'm not using any extension except Wappalyzer and grammerly.

**Comment by jeherve** [comment]
This is odd. I'm not sure what else could cause this on your desktop. I suspect it may impact other sites if the way cookies are stored and deleted is impacted.

Do you experience the issue when on mobile, but still on your home's WiFi network? Checking this may allow us to narrow things down a bit, see if things are linked to your WiFi network and maybe your router settings.

**Comment by amustaque97** [comment]
I'm not able to reproduce this issue on mobile either way: mobile data or wifi. 

I tried it in incognito mode. I'm not getting this issue at all. 

Looks like it is browser-specific. Will observe for some more time. If this issue persists then will update here.

**Comment by amustaque97** [comment]
Not seeing this behavior again. Closing this issue.
