### ISSUE TITLE
Shortcodes: SlideShare has deprecated their Flash embed code, thus breaking all SlideShare embeds

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2048]
https://help.linkedin.com/app/answers/detail/a_id/56328

> Due to security vulnerabilities, SlideShare has deprecated Slideshows and the embed player in Flash format.
>
> If you own a website that has code embedded to a Slideshare deck that was converted to Flash:
> 1. Search for the presentation on SlideShare by entering the presentation title in the search field.
> 2. Click the Embed this presentation icon.
> 3. Replace the old embed code with the new embed code on your site. The old embed code will start with `<div id="__ss_ ...>`

Reported here:
https://twitter.com/jast/status/593439467823833088
https://twitter.com/rscano/status/593300986954911744

**Comment by jkudish** [comment]
The Jetpack version of this embed needs to be updated to match the WP.com version. Can someone from the Jetpack pit crew take care of that?

**Comment by PierreLechelle** [comment]
Same problem here. All my presentations are down :'(

**Comment by kraftbj** [comment]
Hi @PierreLechelle - you can track the solution in #2121. Once that is merged in, it'll be out in the next major version of Jetpack. It is currently scheduled for 3.6, which is targeted for next month.
