### ISSUE TITLE
math-fallback.php need to be more translatable.

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#2050]
More specifically line https://github.com/Automattic/jetpack/blob/master/modules/protect/math-fallback.php#L67 and https://github.com/Automattic/jetpack/blob/master/modules/protect/math-fallback.php#L104

**Comment by samhotchkiss** [comment]
This is going to get changed around pretty heavily in 3.6

**Comment by jeherve** [comment]
Related: #2024
