### ISSUE TITLE
Instant Search: Woo products show in results even after deleting WooCommerce

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#20513]
#### Steps to reproduce the issue

1. Create a new JN site with Jetpack and WooCommerce installed.
2. Give the site a Jetpack search plan.
3. Create/import some Woo products.
4. Verify that the Woo products show up in instant search results.
5. Deactivate or delete the Woo plugin.

#### What I expected

* If the WooCommerce plugin is deactivated or deleted, I wouldn't expect Woo products to show up in instant search results.
* At least an option to hide products from search results (won't show if Woo is deactivated/deleted).

#### What happened instead

Woo products continue to show up in instant search results.

Other info:

* When deleting Woo, the products by default aren't deleted from the db: https://docs.woocommerce.com/document/installing-uninstalling-woocommerce/#uninstalling-woocommerce
* If Woo isn't active on the site, then there isn't an option to hide products from search results: 

![Markup on 2021-07-30 at 12:04:47](https://user-images.githubusercontent.com/15803018/127695966-78d4359c-136b-49a3-9be1-b30cae6e1726.png)

Issue raised during internal JP 10.0-beta testing: p8oabR-HY-p2#comment-5433

**Comment by gibrown** [comment]
This feels like a wont-fix to me. The data is still on the site. The URLs to the products presumably still work right? This behavior is really true for any plugin that registers a custom post type, creates content, and then the plugin is deleted. The user could add some code to filter all posts, but this feels like a rare edge case to me.

**Comment by samiff** [comment]
> This feels like a wont-fix to me.

I think I'm ok with this as well 👍  I'm thinking Woo would only warrant special attention (eg showing a Woo filter option in UI even when deactivated/deleted) if this was driving frequent support requests. And there are straightforward workarounds available here.
