### ISSUE TITLE
Jetpack Search: some interface strings are not being localized

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#20520]
#### Steps to reproduce the issue

1. On your test site with Instant Search enabled, set the site language to 'Français'.
2. Return to the front end of your site and perform a search.

#### What I expected
If the site language is French, all of the interface language in the Instant Search modal should also be in French.

#### What happened instead
The modal shows English strings for "Showing popular results", "Sort" and "clear". Interestingly the sort options themselves are correctly translated (e.g. "Pertinence") so some translations are working as expected.

For example: https://lapidoule.com/?s=bebe

Discovered via 4190269-zen.

**Screenshots**

<img width="1538" alt="Screen Shot 2021-08-02 at 15 03 22" src="https://user-images.githubusercontent.com/17325/127799110-99774a01-f969-466c-a866-763511ebae12.png">

**Comment by bluefuton** [comment]
An earlier related issue with some useful information: https://github.com/Automattic/jetpack/issues/15754

My hypothesis is that this is related to the lazy loading changes in https://github.com/Automattic/jetpack/pull/19049, since the translations from `jp-search-main.bundle.js` appear to be working, but the translations from `jp-search.chunk-main-payload-1a2821bfb803906d5e27.js` are not.

**Comment by sgomes** [comment]
> @sgomes do you know if it's possible to use `wp_set_script_translations()` in combination with lazy loading?

I'm afraid I'm not too familiar with this at all, and the documentation doesn't seem to be particularly helpful 😕

At first glance, I suspect the issue could be that the lazily loaded chunk doesn't get the base script's translations, for some reason. If that's the case, perhaps they could be manually exposed on the base and accessed on the lazily loaded chunk, somehow?

**Comment by bluefuton** [comment]
Thanks @sgomes! Team Global pointed me in the direction of https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4392, which looks fairly complicated (more in pxLjZ-6zp-p2#comment-18415).
