### ISSUE TITLE
Connection prompt for Jetpack Boost?

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#20524]
#### Is your feature request related to a problem? Please describe.

I activated Jetpack Boost on Jurassic.Ninja and was expecting to be prompted to connect it using a JITM or dashboard widget, but didn't see anything like that.

#### Describe the solution you'd like
Prompt to connect after activating Boost.

**Comment by thingalon** [comment]
@mikemayhem3030 -- do you think this could help with our setup / retention pipeline? It does seem kind of like an important missing piece to me :)

**Comment by mikestottuk** [comment]
Yeah I guess so, WP Super Cache do this quite nicely so wouldn't be too hard for us to add (Boost needs to be configured). Especially given it now sits under "Jetpack" top level menu it could leave people not sure where to go (noting we DO have a "Settings" tab) but might not be clear enough.

<img width="1492" alt="Screenshot 2022-07-26 at 12 12 57" src="https://user-images.githubusercontent.com/4077604/180993085-81d51c75-510f-41c9-a729-6588c6a86c7c.png">
