### ISSUE TITLE
Intermittent 503 activating Critical CSS on JN

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#20525]
#### Steps to reproduce the issue

1. Create a new site on JN with just the beta plugin and master version of Jetpack Boost
2. Connect the plugin
3. Activate Critical CSS
4. I got a 503 error. Trying again, it worked.

#### What I expected
No error.

#### What happened instead
503 error

**Screenshots**

This is on the site https://stiff-caracal.jurassic.ninja/

![optimize-css-jn-error](https://user-images.githubusercontent.com/51896/127901507-c1d2bc06-f44e-4d13-91ed-880a3c390e05.png)

**Comment by gravityrail** [comment]
After looking in the logs, these appear to the be relevant lines. Perhaps this is spurious?

```
[Mon Aug 02 17:32:35.454324 2021] [proxy:error] [pid 32615:tid 139691839899392] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /srv/users/user3445e2b2/run/user3445e2b2.php-fpm.sock (localhost) failed
[Mon Aug 02 17:32:35.454390 2021] [proxy_fcgi:error] [pid 32615:tid 139691839899392] [client 73.48.185.181:0] AH01079: failed to make connection to backend: httpd-UDS, referer: https://stiff-caracal.jurassic.ninja/wp-admin/admin.php?page=jetpack-boost
```

**Comment by jeherve** [comment]
That's to be expected, and is a quirk of the JN infrastructure. You'll get 503 errors like this one every time another JN site is being provisioned.
