### ISSUE TITLE
Carousel: add option to disable carousel on per gallery basis

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#20527]
#### Is your feature request related to a problem? Please describe.

Sometimes users may be using Gallery/Tiled blocks to organize their images for display but don't necessarily want to use the carousel lightbox feature. There isn't an easy way to turn this off on a per gallery basis currently.

#### Describe the solution you'd like

For Gallery blocks, add a toggle option for the carousel/lightbox feature.

#### Additional context

Internal: p8oabR-HY-p2#comment-5451

**Comment by jeherve** [comment]
Closing as duplicate of #15946
