### ISSUE TITLE
Jetpack Carousel & Photon combination causes images to be upscaled

### ISSUE THREAD

**Issue by Draikin** [Automattic/jetpack#2053]
Normally when using the Jetpack Carousel, it will display the images in their original size. If they're larger than the browser window, they'll just be resized by the browser. While not ideal, it's better than what Photon does. After activating Photon, I noticed some images suddenly looked really blurry in the Carousel. This only happened with large images (1080P). What apparently happens is that Photon checks if the resolution of the original image is greater than the browser window. If so, it returns an image in the "Large" image setting. This is less than ideal, because the Large image resolution can be a lot smaller than the original image size. The browser then upscales the image, which looks rather terrible. In my opinion, Photon should never serve an image that's smaller than the resolution required for viewing in the Carousel, to avoid it being upscaled. After all, that's the standard behavior for the Carousel when not using Photon.

**Comment by jeherve** [comment]
Could you give us a few examples where you run into this issue, so we can look into this further?

Thanks!

**Comment by Draikin** [comment]
I disabled Photon on my website now because of this issue, but I had a support ticket with Mikey which included more details. It seems easy enough to reproduce though. The Carousel appears to check the browser width the moment it loads, and then determines which image to fetch from Photon. If I display a 1280x720 pixel image on a fullscreen browser on a 1080P display, Photon shows the original image. If I then resize the browser so it only has 1000px width available and reload the page, the carousel will serve the "Large" image version (in my case using "fit=625%2C9999"). The end result is that the image is then upscaled by the browser itself. I included two images that show how it looks in my browser in fullscreen and after I resized
![photon_carousel_halfscreen](https://cloud.githubusercontent.com/assets/12175336/7421232/431df4b0-ef83-11e4-8a33-0cf36c840f72.PNG)
![photon_carousel_fullscreen](https://cloud.githubusercontent.com/assets/12175336/7421233/431ec3c2-ef83-11e4-9555-7a55edd93466.PNG)

 the browser window.

If I disable Photon, the Carousel always uses the original images, regardless of browser width.

**Comment by jeherve** [comment]
Thanks for the extra details!

Can you think of a good alternative to this problem? If we were to use the original images everywhere, like when Photon is deactivated, we would end up loading very large images on mobile devices, which isn't ideal.

**Comment by Draikin** [comment]
Well, I don't know how Jetpack decides which images to serve and if the following is possible, but I do think I have an alternative solution. I think the ideal scenario would be for Jetpack to serve the image by examining the available space for the Carousel to display images like this:

Available width > original image width ? -> serve original image
Available width  < original image width and > Large image width (650px in my case) ? -> serve original image and let browser downscale it.
Available width  < Large image width and > Medium image width ? -> serve Large image and let browser downscale it.
Available width  < Medium image width and > Thumbnail image width ? -> serve Medium image and let browser downscale it.

This setup would prevent the image from ever being upscaled, and would only serve the original image if there are no better alternatives. I'd imagine that for mobile, it would typically end up serving the Large or Medium image rather than the original. In fact, this might also be a good solution for the Carousel without Photon, as at the moment it always serves the original image even for mobile. I didn't take Hi-DPI screens into account here, I guess those could complicate matters.

**Comment by jeherve** [comment]
That's kind of how it works today, but your method would add a new condition:

> Available width < original image width and > Large image width (650px in my case) ? -> serve original image and let browser downscale it.

https://github.com/Automattic/jetpack/blob/master/modules/carousel/jetpack-carousel.js#L962

We'll see if we can add that to Carousel in a future release!

**Comment by Draikin** [comment]
Seeing that code, I would imagine the Carousel should also be serving smaller images when not using Photon. I debugged the Javascript part you linked to on my website and there's something odd going on there. For starters, it seems to be using media settings from my parent theme rather than my main theme (it's using 625 pixels, which I believe is the featured post setting on Twenty Twelve, but I changed that in the child theme I'm using). Secondly, If I'm seeing this correctly it's using regex to fetch the width and height from the Large image url, but something appears to go wrong there (the first index of large_size_parts contains almost the entire url, rather than just the width), so it fails to parse to int and the large-width is set to NaN. I think that explains why it was always returning the original image for me when I was not using Photon. I'll look into this further.

**Comment by Draikin** [comment]
So here I think it tries to get the width and height of the large image:

large_size = args.large_file.replace(/-([\d]+x[\d]+)\..+$/, '$1')

But I don't think that does what it was intended to do. Let's say you have large_file set to "http://.../wp-content/uploads/2015/04/fullhd-625x352.png". The first replace would end up replacing only the "-625x352.png" part. It would return "http://.../wp-content/uploads/2015/04/fullhd625x352".

I imagine what the code was intended to do, is return "625x352" instead. I believe that's what it does with the change I made, there the entire string will be replaced by the match, rather than only the last part. But that said, I think that even with that change, it would still do what I'd want it to do. I don't think it would serve the large image unless either the width or height of the large image is greater than the args.max-width or args.max_height. So I'm not sure what exactly happens when I'm using Photon. I'd have to look into that.

**Comment by Draikin** [comment]
Well, I just tested Photon, and it just uses the same code. And I don't think this can work, Photon doesn't have the same url structure but (aside from what appears to be a bug that I explained above) the code can only deal with regular Wordpress. For Photon, the regex simply doesn't match anything, so it resorts to using a default value for large image width and height. And that default value is actually that of the original image. And that's what explains the whole problem I was seeing with Photon, it serves the large image because it mistakenly thinks that the width of large image is greater than that of the max width available in the browser. If the code worked as intended, it would in fact have done exactly what I wanted it to. I think there are two different problems: one being a bug in the standard Carousel code, and the other being an oversight in the sense that the code was probably never updated to work with Photon image urls. I'd be interested in fixing this, but I'm not sure where to start as I haven't worked with GitHub before. Can anyone contribute code to this?

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/problem-with-image-quality-in-gallery?replies=10&view=all#post-7016690

**Comment by Draikin** [comment]
I haven't had the time to look into how I should contribute a fix here. But I guess I can just work on a fix locally and post my solution here. It's only a few lines of code that need to be changed/added.

**Comment by jeherve** [comment]
> I haven't had the time to look into how I should contribute a fix here.

This could help:
http://jetpack.me/contribute#patch

**Comment by Draikin** [comment]
Thanks, I'll give that a try.

**Comment by Draikin** [comment]
I think I got it working for me, but I did encounter the following issues:
- I need to check whether or not the image is being served by photon. I did that by checking for "?resize" or "?fit=" in the url. Can I assume any photon url will contain those? Or are there better ways to determine whether or not it's a photon image?
- Another problem is that the photon url lists the media setting width and height for the image as a url parameter, rather than the actual width and height like the regular Wordpress does. This is a problem when the value 9999 is used. At the moment, I'm essentially ignoring the 9999 values. Otherwise, those would always be seen as larger than the available resolution. So that means that, if the height is set to 9999, only the width will be used to determine the best image. Not ideal, but in practice this will usually give a good result. To really fix this, I'd basically have to recalculate the actual width and height of the large and medium images based on the media setting retrieved from photon, and the dimensions of the original image. I guess that could work.

**Comment by jeherve** [comment]
> I did that by checking for "?resize" or "?fit=" in the url. Can I assume any photon url will contain those?

Photon images don't always include such parameters if it's not needed.

> Or are there better ways to determine whether or not it's a photon image?

In other parts of Jetpack, use check for the wp.com domain, You can see it in action here:
https://github.com/Automattic/jetpack/blob/master/class.photon.php#L467

**Comment by Draikin** [comment]
Been a while, but I'm still planning on finishing this. I'm assuming nothing has changed about this functionality in 3.6. The check for the wp.com domain would seem like a logical choice to determine if it's a photon url, thanks for linking to that. The thing that I'm still not sure about are the dimensions. Does the photon url always include the width and height? And if they do, are those always the media size settings, rather than the actual image sizes? From what I'm seeing, this appears to be the case. If they are, then it should be possible to calculate the actual size of the image, since we do know the original image size. In that case, it'd be possible to resolve all the issues I mentioned earlier.

**Comment by jeherve** [comment]
> Does the photon url always include the width and height?

No, not always, as such parameters aren't always available. All images, including from external sources, go through Photon when you activate the module. Images from external sources, however, do not always include size parameters.

**Comment by Draikin** [comment]
i'm not entirely sure if there's a way to retrieve the dimensions of the image then... Is there an overview somewhere of the different types of url's that Photon uses?

**Comment by jeherve** [comment]
Photon will accept just about any image URL. Only a few domains are excluded from Photon, as you can see here:
https://github.com/Automattic/jetpack/blob/master/functions.photon.php

**Comment by Draikin** [comment]
Thanks for the link. I think I'll just finish what I have and leave a fallback for cases where I can't determine the width and height based on the url. While not ideal, it should at least be an improvement.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/carousel-poor-image-rendition

**Comment by Draikin** [comment]
I thought this may have been easy to fix, but the way Photon doesn't always include the actual dimensions means the current method of retrieving the image dimensions won't always work. I have a workaround that fixes the problem for me, and while it's better than the current implementation (which doesn't take Photon into account at all), it won't resolve it for every scenario. I also don't have the means to test it on other configurations. What should I do, do I just create a pull request for the changes I made and let you guys take a look at it?

**Comment by jeherve** [comment]
> What should I do, do I just create a pull request for the changes I made and let you guys take a look at it?

Go for it, we can start from there and make more changes later on!

Thank you!

**Comment by Draikin** [comment]
Alright, I'll look into contributing a patch today.

**Comment by jeherve** [comment]
If you're looking for help, you can follow the instructions here:
http://jetpack.me/contribute/#patch

**Comment by Draikin** [comment]
I'm not sure if I'm doing this correctly, but here are the changes that I just committed to the new branch I made:

https://github.com/Automattic/jetpack/compare/master...Draikin:enhance/carousel-photon-support

This appears to fix the problem for me. It resolves one problem I explained earlier where the Carousel doesn't retrieve the width correctly for regular Wordpress image urls, that's just a minor change to the regex. For Photon, I added additional checks and a new function to retrieve the image dimensions. But this only works as long as the url actually contains the image dimensions. Also, for image width or height set to 9999, I have to set it to 0. Otherwise it would always serve the original image. Technically, you could calculate the actual height or width in that case, but I'm not sure if that's worth doing if the width and height aren't always known anyway. I do believe that with these changes, the images should no longer be upscaled. And that was really 

But given the way Photon works, can't we construct the url for Photon on the fly and let it return the ideal image size for the Carousel? Since we have the original image dimension and the available width and height in the browser, I imagine we can also calculate what the exact width and height for the image needs to be to fit the Carousel perfectly. No scaling would take place at all. I think that's basically what Photon is designed to do anyway.

**Comment by jeherve** [comment]
Could you create a Pull Request including those changes, so we can discuss it further there?

Thanks!

**Comment by Draikin** [comment]
Done: https://github.com/Automattic/jetpack/pull/2508
