### ISSUE TITLE
Publicize: Publicized to non-connected accounts

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#2054]
I have a site I use for testing a lot, so I disconnect / reconnect it a LOT.

I made a test post recently and had no Publicize options.  They must have disappeared after a connection cycle.  However, when I published the post, I noticed there was a LinkedIn Share already!  

Turns out Publicize had published to my test LinkedIn account even though nothing was present in my Sharing Settings - but when looking at the blogRC my connections were still there.

site: mikey.press
post that was publicized: http://mikey.press/2015/04/29/kraft-is-awesome/

**Comment by jkudish** [comment]
Sounds like something didn't sync properly between your site and WP.com -- probably not a publicize specific bug even.

Considering this was on a test site, for an Automattician, and a definite edge case, I don't really think it's a good use of our time/efforts to spend time on this. If it happens repeatedly or for non bleeding-edge users/non-Automatticians, I'd reconsider.

**Comment by mikeyarce** [comment]
I agree it's edge case, just wanted to document it here because I've seen it happen on a number of users sites where they disconnected their accounts from Publicize but it just keeps getting Publicized there anyway.

I usually ask them to revoke our access from their networks, but wanted to make a note that this does happen on occasion.

**Comment by jkudish** [comment]
@mikeyarce if this happens to users, please report it with a reproducible case or affected users on the private io repo.

**Comment by mikeyarce** [comment]
@jkudish so far I've seen maybe 2-3 cases like this, but I have not been able to reproduce wittingly - if I see any more cases like this I'll make sure to let your team know.
