### ISSUE TITLE
Shortcode support in Related Posts Entry titles

### ISSUE THREAD

**Issue by wpgaurav** [Automattic/jetpack#20551]
I use shortcodes in Post Titles but as I can see Jetpack Related Posts doesn't render the shortcode and shows [shortcode].

How can I enable shortcode support in RelatedPosts Titles?

**Comment by jeherve** [comment]
Could you tell us more about your setup? How do you process shorcodes in post titles? Do you use a specific plugin for that? If so, could you post a  link here so I could give it a try on my end?

Thank you!

**Comment by wpgaurav** [comment]
Hi @jeherve . I have this plugin https://wordpress.org/plugins/dynamic-month-year-into-posts/ that renders [year], [month] etc. shortcodes in _most_ of the places. One user reported that these don't work in Related Posts' post titles: https://wordpress.org/support/topic/jetpack-related-posts-doesnt-translate-codes/

I was wondering if there was a way. Contextual Related Posts and YARPP both have such support but not Jetpack.
