### ISSUE TITLE
Russian translation issue 

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#2055]
A user repoted a issue with this Russian translation
![image](https://cloud.githubusercontent.com/assets/115071/7400380/563e145c-ee71-11e4-8b01-e7c2ac1c3ea1.png)

He suggested to change word недоступным (wrong logic) at
доступным (its right logic).

cc @zinigor

**Comment by zinigor** [comment]
Yes, right now it says that when checked, it will make the connection *unavailable* for other users.

**Comment by jeherve** [comment]
You can suggest new strings in GlotPress. [Here is the string that can be changed](https://translate.wordpress.com/projects/jetpack/3.5/ru/default?filters[status]=either&filters[original_id]=150918&filters[translation_id]=4379083).

For more information about how translations work on Jetpack, you can check this post:
http://jetpack.me/support/getting-started-with-jetpack/how-can-i-install-jetpack-in-my-language/
