### ISSUE TITLE
Boost: Exclude specific scripts from DeferJS

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#20559]
originally filed by: @danjjohnson 
Requested by a user: https://wordpress.org/support/topic/how-does-jetpack-boost-deals-with-javascript/

Add the ability to exclude specific scripts when deferring JavaScript.

**Comment by thingalon** [comment]
Note: there is an undocumented filter in the guts of Jetpack Boost which could support this: `jetpack_boost_render_blocking_js_exclude_scripts`. It may be enough (at first) to document this filter in a way that users (and support engineers) can leverage, and revisit it with an improved UI later.

**Comment by dragstor** [comment]
Had a user who would benefit from this: 33744149-HC

**Comment by thingalon** [comment]
Closing in favor of: https://github.com/Automattic/jetpack/issues/22235 and 101-gh-Automattic/boost-cloud. This feature will get documented. ;)
