### ISSUE TITLE
Boost: Show Speed Score in Jetpack Debugger

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#20558]
Originally filed by @danjjohnson 

#### Is your feature request related to a problem? Please describe.
When a user reports the score Boost is showing, it would be good if we could verify that with our own tools.

#### Describe the solution you'd like
Add a Boost section to the Jetpack Debugger, which shows the current scores for the site.

Relevant: p1HpG7-bOI-p2

**Comment by dilirity** [comment]
This was implemented some time ago.

Closing.
