### ISSUE TITLE
Boost: Reports of slow Critical CSS generation

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#20567]
We have some reports of slow Crtiical CSS generation on some sites.

- @gravityrail reports upwards of 5 minutes on a test Pressable site. Ping him for access if need be.
- @danjjohnson passed on a user report of 4-5 hours here: https://wordpress.org/support/topic/same-ccss-for-custom-post-type/

The user report of 4-5 hours indicates they have upwards of 18k posts - but that shouldn't be a factor in the process. What should matter are the number of Providers.

We may need to start by logging Critical CSS generation time and provider key counts, or offering some kind of tooling in the Jetpack Boost dashboard for users to give us feedback on the types of sites that can be slow.

One user mentioned https://docs.litespeedtech.com/lscache/lscwp/pageopt/#separate-ccss-cache-uris as a potential cause.

Original thread: 659-gh-Automattic/jetpack-boost

#### TODO
- [ ] Find the circumstances which can cause Critical CSS to take a long time to generate.

**Comment by davidlonjon** [comment]
I did some investigation and findings on my local environment to replicate some slowness in producing Critical CSS but I decided to put this issue on the backburner for now as I believe once we release https://github.com/Automattic/jetpack/pull/21052 it will help us inform much better if this is a real problem and how much of a problem it is.

**Comment by thingalon** [comment]
Closing this, as there have been no reports in a long time.
