### ISSUE TITLE
Stats dashboard widget: settings don't save

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#20575]
#### Steps to reproduce the issue

1. Go to the main WordPress dashboard in wp-admin (Dashboard > Home)
2. In the Jetpack Stats widget, click the Settings icon

![image](https://user-images.githubusercontent.com/1990037/128363602-b720dc4c-9b89-48b1-9a01-50bd4d633d7d.png)

3. Change any settings and click Submit.

#### What I expected

The settings would change.

#### What happened instead

On refresh, the settings were reverted to their original state.

Reported in https://wordpress.org/support/topic/jetpack-dashboard-stats-settings-dont-work/

**Comment by Taruks** [comment]
Hi, same issue here. Any solutions so far? Thanks for your support.
Greetings

**Comment by jeherve** [comment]
@Taruks We have not fixed this yet, but will update this issue when we do!

**Comment by marcodsad** [comment]
Hi, same issue here. WP 5.8.2. Jetpack 10.3.
The problem exists since several months, it would be quite helpful if it could be fixed.

Thanks!

**Comment by muffinpeace** [comment]
Received a report of a user experiencing this on zen-4904189.

**Comment by AnthonyFaxlandez** [comment]
We have another report on zen-5210575.

**Comment by coder-karen** [comment]
This issue has now been fixed in #25039. That fix will make its way to the next Jetpack release, 11.2 (first Tuesday in August), or later this week for WoA sites. It can be used via the [Jetpack Beta Tester plugin](https://github.com/Automattic/jetpack-beta) in the interim though.
