### ISSUE TITLE
Slideshow: add thumbnails below the slideshow

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#206]
Here is a small suggestion for improvement of the Slideshow shortcode:

![screen shot 2014-02-12 at 5 20 33 pm](https://f.cloud.github.com/assets/426388/2150470/a217a094-9401-11e3-8fa6-69f9e83d6f80.png)

Suggested here:
* http://wordpress.org/support/topic/galleries-with-thumbnails?replies=1

**Comment by StaggerLeee** [comment]
Some news about it ?

**Comment by jeherve** [comment]
@StaggerLeee We didn't make any progress on this, but we'll post here when we do.

**Comment by StaggerLeee** [comment]
Thanks. 
Problem with those is responsive view, smartphones mostly. They have some life on its own.

**Comment by jeherve** [comment]
Closing this as `wontfix` since there haven't been any other similar requests in the past 2 years. Will reopen if it ever becomes a popular request.
