### ISSUE TITLE
Boost: Review JavaScript testing strategy and tests

### ISSUE THREAD

**Issue by davidlonjon** [Automattic/jetpack#20615]
Since Jetpack Boost was migrated to the Jetpack Monorepo: 1057-gh-Automattic/jetpack-boost (ref [PR](https://github.com/Automattic/jetpack/pull/20512)), we had to disable the existing [JS integration tests](https://github.com/Automattic/jetpack/tree/master/projects/plugins/boost/tests/integration) because the legacy process to run the test did not fit anymore with the Jetpack Monorepo structure and processes.

Therefore we need to review our JavaScript testing strategy, most likely refactor the existing [JS integration tests](https://github.com/Automattic/jetpack/tree/master/projects/plugins/boost/tests/integration) or start from scratch.

A few pointer in terms of the process to follow and examples:
- Jetpack infrastructure looks for a `test-js` entry in each project's composer.json file. For example https://github.com/Automattic/jetpack/blob/5a876de20cd3d665b4ed20e364373bb4bea7a0a9/projects/plugins/jetpack/composer.json#L61-L65 wich for the case of Jetpack it triggers multiple js test runs as defined in Jetpack plugin's package.json . Here is one of the JS test from Jetpack:
https://github.com/Automattic/jetpack/blob/29ccc2fc37522edf221a2e38363fae87516b7345/projects/plugins/jetpack/package.json#L44
- Look at the existing [Jetpack e2e tests](https://github.com/Automattic/jetpack/tree/master/projects/plugins/jetpack/tests/e2e) to see how they are structured and defined.
- Refer to the CI e2e test workflow at https://github.com/Automattic/jetpack/blob/5605eb656d65149dbeebec31077bc13c8ea1d1a2/.github/workflows/e2e-tests.yml

**Comment by jeherve** [comment]
cc @brbrr and @adimoldovan, who can provide some guidance with the Jetpack e2e tests and the general setup of tests.

**Comment by brbrr** [comment]
> because the legacy process to run the test did not fit anymore with the Jetpack Monorepo structure and processes.

I wonder why it is? Have you tried defining `test-js` script in boost's composer.json? It might just work 🤔 

Conceptually, boost's integration tests might now fit into `test-js` bucket, since they test, well, integration :)
