### ISSUE TITLE
Minileven: can't load custom theme with jetpack_mobile_template or jetpack_mobile_stylesheet

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2061]
Jetpack's Mobile Theme detection includes 2 filters, `jetpack_mobile_template` and `jetpack_mobile_stylesheet`, that allow you to define a custom Mobile Theme instead of the default Minileven:
https://github.com/Automattic/jetpack/blob/77629b6de0a3651b5cff0e6139682c0e8d388369/modules/minileven/minileven.php#L84

Unfortunately, the custom theme still has to be located inside the Minileven module directory. It would be nice if you could use the filters to load a theme from the /themes directory, or from another plugin.

Reported here:
https://wordpress.org/support/topic/custom-mobile-theme-1

**Comment by samhotchkiss** [comment]
Makes sense, but isn't in line with our current goals for Jetpack and isn't high priority enough to focus on right now.  Would be open to PRs from the community addressing this.

**Comment by megamurmulis** [comment]
Losing code changes on each update is obviously bad, so should store mobile theme in uploads or themes dir..

But I can confirm that this workaround is working:
**1.** If your mobile Jetpack theme is located in `/wp-content/themes/mytheme_mobile/`
**2.** Create a new plugin: `jetpack_custom_theme_location.php`
```
<?php
/*
Plugin Name: Jetpack custom mobile theme location
Description: Set custom Jetpack mobile theme location
Version:     1.0.0
*/
add_filter( 'jetpack_mobile_stylesheet', function( $stylesheet, $theme ) {
	return '../../../../../themes/mytheme_mobile';
}, 10, 2);
add_filter( 'jetpack_mobile_template', function ( $template, $theme ) {
	return '../../../../../themes/mytheme_mobile';
}, 10, 2);
```

It does however mean that URLs in css and JS output will be:
`http://domain.com/devdorado/wp-content/plugins/jetpack/modules/minileven/theme/../../../../../themes/mytheme_mobile/style.css`..
