### ISSUE TITLE
Pre-push check: avoid blocking release branch pushes

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#20616]
#### Steps to reproduce the issue

1. While standing on `master`, try creating a release branch: `tools/create-release-branch.sh boost 1.2.0-beta`
2. The branch will be created, but you'll run into the check when attempting to push:
```
Push it now? [y/N] y
husky > pre-push (node v14.16.1)
Checking if changelog files are needed. Just a sec...
Project plugins/boost is being changed, but no change file in projects/plugins/boost/changelog/ is touched!
Use `jetpack changelogger add <slug>` to add a change file for each project.
Guidelines: https://github.com/Automattic/jetpack/blob/master/docs/writing-a-good-changelog-entry.md
husky > pre-push hook failed (add --no-verify to bypass)
error: failed to push some refs to 'git@github.com:Automattic/jetpack.git'
mark@Marks-MacBook-Pro-3 jetpack % git status
On branch boost/branch-1.2.0
nothing to commit, working tree clean
```

I think it would be fine to skip the check in this scenario.

**Comment by sdixon194** [comment]
Do we ever need to check for a changelog when pushing to a release branch? Will we run into this issue when cherry picking as well? I'm wondering if the easiest way would be to have the test skip if we're pushing to a release branch (compared to skipping only when this script is run).

**Comment by jeherve** [comment]
> Do we ever need to check for a changelog when pushing to a release branch?

> Will we run into this issue when cherry picking as well?

I don't think so since cherry-picks include a changelog file.
