### ISSUE TITLE
[Related Posts] Clarify settings for Full Site Editing sites

### ISSUE THREAD

**Issue by stacimc** [Automattic/jetpack#20628]
#### Is your feature request related to a problem? Please describe.

Typically the Related Posts feature is enabled via the Jetpack settings, and results in the feature being automatically appended to the end of posts.

This concept doesn't make sense for an FSE site, since the user should be able to fully control the site's appearance through templates. In an FSE site the user "manually" adds the feature by adding the Related Posts block into their preferred template. As such, toggling the setting doesn't actually do anything (this is also true for wpcom simple sites).

This can obviously be confusing, since a user might see the setting and turn it on, expecting Related Posts to automatically be appended (or likewise shut it off and expect them to stop appearing). Moreover, it can create confusion when a user switches from a classic theme with the feature enabled to a blocks theme. Unless they go add the block to one of their templates, they will silently lose the feature.

#### Describe the solution you'd like

At minimum I suggest removing the setting from the Jetpack Settings as well as the wpcom `Settings -> Reading` page when a blocks theme is enabled.

To address the latter issue with switching themes, maybe we could do something with Jetpack's JITM. When Related Posts are enabled and the user switches from a classic to a blocks theme, we could serve a JITM suggesting the user add the block to their Single Post template.

**Comment by jeherve** [comment]
Previous conversations about this:
- #11021
- #11861

If that's okay, I'll close this issue and copy your post to #11021, to keep the conversation in one place.
