### ISSUE TITLE
Staging Site option doesn't do anything

### ISSUE THREAD

**Issue by wormeyman** [Automattic/jetpack#2062]
https://github.com/Automattic/jetpack/blob/master/class.jetpack.php#L5267

As far as I can tell clicking on "Ignore the difference. This is just a staging site for the real site referenced above." doesn't do anything

**Comment by kraftbj** [comment]
The notice was shipped a bit early. Removed in eb0d2ea322d5482b1816096bdb23d3ddd4f7f2c2 via #2010
