### ISSUE TITLE
Subscription Block doesn't show up.

### ISSUE THREAD

**Issue by benjaminwolkchen** [Automattic/jetpack#20641]
#### Steps to reproduce the issue

1. Install the [Blocksy-Theme](https://wordpress.org/themes/blocksy/) and activate it.
2. In the Widget Area add the Jetpack Email-Subscription Block
3. Preview or save the changes.

#### What I expected

The Email-Subscription Widget should appear in the widget area.

#### What happened instead
The space for the widget is empty and the widget does not appear.

**Screenshots**
Frontend:

![Screenshot 2021-08-11 at 12-23-12 Willkommen auf awesomeBible ](https://user-images.githubusercontent.com/42138517/129013340-dcda53f6-0ffd-49cb-887f-2aeeec9b6788.png)

Backend (the customizer):
![Screenshot 2021-08-11 at 12-23-46 Customizer awesomeBible](https://user-images.githubusercontent.com/42138517/129013392-280a18cd-a984-47ef-83ea-bf3c587d7b47.png)

My WordPress Version is 5.8 and I run the Blocksy Theme in version 1.8.4.5.

The Issue Report on the Blocksy Forum can be found [here](https://wordpress.org/support/topic/jetpack-subscription-widget-doesnt-appear/)

**Comment by jeherve** [comment]
Both the Legacy Subscriptions widget and the Subscription form block appear to work on my end on a brand new site using the Blocksy theme:

![image](https://user-images.githubusercontent.com/426388/129020373-75c5748a-12b0-45b2-a600-35aba1046706.png)

I also see the widget on your own site:
![image](https://user-images.githubusercontent.com/426388/129020843-10d96961-b360-42d9-b280-2b4db4e80b3b.png)


I see that things appear to work for the theme author as well:
https://wordpress.org/support/topic/jetpack-subscription-widget-doesnt-appear/#post-14756722

I'd suggest trying to flush your cache as the theme author suggested there.
