### ISSUE TITLE
https://stats.wp.com/e-202132.js load error

### ISSUE THREAD

**Issue by imlijq** [Automattic/jetpack#20642]
#### Steps to reproduce the issue

1. open chrome developer tool
2. https://stats.wp.com/e-202132.js load error
3. Looking at the source code, the js file is loaded at wp-content/plugins/jetpack/modules/stats.php -> `$script = 'https://stats.wp.com/e-' . gmdate( 'YW' ) . '.js' ;`

#### What I expected
This js file loads fine

**Screenshots**

![2021-08-11_205955](https://user-images.githubusercontent.com/19914442/129032992-27acea7e-6cab-4215-b6fe-73077c754e95.png)

**Comment by jeherve** [comment]
The file appears to load properly for me, from Europe and from the US. We also do not have any outages at the moment.

Do you happen to use a browser extension that may block access to the file? Do you experience the same issue in a different browser, or in an incognito window?

**Comment by imlijq** [comment]
> The file appears to load properly for me, from Europe and from the US. We also do not have any outages at the moment.
> 
> Do you happen to use a browser extension that may block access to the file? Do you experience the same issue in a different browser, or in an incognito window?

Sorry, it was a problem with the proxy I was using, I added stats.wp.com to the whitelist and the problem has been solved, thanks

**Comment by jeherve** [comment]
@imlijq I'm glad you could figure it out. I see you've reopened the issue. Is it okay to close now?

**Comment by imlijq** [comment]
> @imlijq I'm glad you could figure it out. I see you've reopened the issue. Is it okay to close now?

Yes, no more problems now, I turned him off
