### ISSUE TITLE
Contact Form: change [contact-form] shortcode to [contact_form]

### ISSUE THREAD

**Issue by jimmyandrade** [Automattic/jetpack#2065]
While the Jetpack doesn't use wpviews to make the contact form have a visual representation in the editor, as already happens with the galleries and audio and video shortcodes (@georgestephanis set this as "vFuture" on #642), there is a suggestion for now.

Some of you know that @danielbachhuber's [Shortcake (Shortcode UI) plug-in](http://github.com/fusioneng/Shortcake) has been a great solution to visually represent shortcodes in editing screen. I tried to register `[contact-field]` as visual shortcode, but I discovered that shortcodes using hyphen `-` in your slug are not accepted by Shortcake.

Thus, Jetpack could use `[contact_field]` (using an underscore `_` to represent slug) instead of `[contact-field]`. So, if user has Shortcode UI installed & activated, the Contact Form could be visually represented. The user had to make proper registration of the visual shortcode. However, it'd be even better if Jetpack could test if shortcake `function_exists` registry function already existed and did its registration.

PS.: To prevent this update breaking sites that already have the forms generated with `[contact-field]`, both shortcodes could coexist. `[contact-field]` could be an alias for `[contact_field]`.

**Comment by georgestephanis** [comment]
We're planning the embeddable iteration in the near future.

As an aside, though, it feels like not supporting dashes in shortcode names should be an upstream bug in shortcake, no?

**Comment by danielbachhuber** [comment]
> As an aside, though, it feels like not supporting dashes in shortcode names should be an upstream bug in shortcake, no?

Kinda both https://github.com/fusioneng/Shortcake/issues/86

**Comment by jimmyandrade** [comment]
Well... according to Wordpress Codex...
> Take caution when using hyphens in the name of your shortcodes.

We can see several examples in the [Hyphens](https://codex.wordpress.org/Shortcode_API#Hyphens) section on [Shortcode API](https://codex.wordpress.org/Shortcode_API) showing that the use of hyphens as shortcode names is not recommended.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
