### ISSUE TITLE
Dashboard widget: redesign the widget when stats are disabled.

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#2067]
I think the Jetpack Dashboard widget could look better if you don't have stats enabled. 
![image](https://cloud.githubusercontent.com/assets/115071/7423701/be3f0c42-ef4c-11e4-89e1-85ebe2259fb5.png)

cc @jeffgolenski.

**Comment by jeffgolenski** [comment]
@enejb Absolutely. it's on my to-do list to do a design over-haul for this. Just got a few items to accomplish first!

**Comment by enejb** [comment]
My first though was something was wrong, because it l wasn't sure why the stats were missing. I later realized that they were just off.

**Comment by abidhahmed** [comment]
Closing this for now, please feel free to reopen if required.
