### ISSUE TITLE
Jetpack Social Icons widget not saving or displaying

### ISSUE THREAD

**Issue by kuropixel** [Automattic/jetpack#20698]
### Steps to Reproduce

1. Go to widgets in customizer
2. Add the social icons (jetpack) widget
3. Input some links to Facebook, Instagram, etc.
4. Save and view the site.

### What I expected to happen

The social icons widget should display on the web with any input links that were saved.

### What actually happened

None of the social icons appear on the site. Also, when returning to the widgets section, the input links are forgotten even after saving.

### Context

One user reported this behavior on their Atomic site: 4224387-zen
I was able to replicate it on a test Atomic site: https://kuroatomic.wpcomstaging.com/ (Follow section at the bottom is empty despite adding links)
Test simple site had no issues: Pd58NJ-2-p2 (Icons display below Follow)

### Operating System

macOS

### Browser

Chrome/Chromium, Firefox

### Is this specific to applied theme? If so, what is the theme name?

Probably more widespread, but confirmed with Olsen and Dyad 2

### Simple/Atomic

Atomic

### Number of Users Impacted

Some users (<50%)

### Available Workarounds

For now, users should try using the social icons widget (non-Jetpack) as a workaround.

### Reproducibility

Consistent

**Comment by jeherve** [comment]
I cannot seem to be able to reproduce on my end; I can add services as they're displayed properly on the frontend and in the customizer.

Could you try with a different theme, and see if you experience the same issue? 

Could you also check for Javascript errors on the customizer page when adding a new widget, as explained here:
https://wordpress.org/support/article/using-your-browser-to-diagnose-javascript-errors/

Let me know what you find!

**Comment by kuropixel** [comment]
Thank you for getting back to me, @jeherve!

I tried my test site with a different theme (Twenty Twenty One) and the results are the same.
After adding the URLs, I click Update and when I reload the widgets page, nothing is saved.

I tried doing the steps you suggested for javascript errors and these are the only things that stood out on the widgets page:
```jquery-migrate.js?ver=3.3.2:100 JQMIGRATE: jQuery.fn.bind() is deprecated```

```index.min.js?ver=4b27c2cd741d4b9c1613148ded19587a:1 GET https://kuroatomic.wpcomstaging.com/wp-json/wp/v2/types/null?context=edit&_locale=user 404```

I'm also seeing mentions of the widgets/Jetpack in the console for errors.
I see these types:
```[16-Aug-2021 02:43:31 UTC] PHP Notice:  Undefined index: url-icons in /wordpress/plugins/jetpack/10.0/modules/widgets/social-icons.php on line 220```

```[16-Aug-2021 02:43:31 UTC] PHP Warning:  Invalid argument supplied for foreach() in /wordpress/plugins/jetpack/10.0/modules/widgets/social-icons.php on line 220```

Appreciate any info on this, thank you!

**Comment by jeherve** [comment]
> index.min.js?ver=4b27c2cd741d4b9c1613148ded19587a:1 GET https://kuroatomic.wpcomstaging.com/wp-json/wp/v2/types/null?context=edit&_locale=user 404

That's interesting. Do you get the same issue after you launch your site?

> I'm also seeing mentions of the widgets/Jetpack in the CLI for errors.

That's a good point, we can fix that notice. We'll see about it in #20703.

**Comment by kuropixel** [comment]
>That's interesting. Do you get the same issue after you launch your site?

The test site and reported user's site is currently public and not set to private or coming soon. Is that what you meant by launching?

**Comment by katiebethbrown** [comment]
Another report:

29428684-hc

Site is public. They have the Social Icons (Jetpack) widget in the block widget area, and have a link to linkedin added, but nothing is visible on the live site at all. The widget does appear in the HTML though:

<img width="991" alt="socialiconwidget" src="https://user-images.githubusercontent.com/42279181/129793382-1747e431-2c4c-4fae-bcbc-ab3acb53b8ad.png">

**Comment by jeherve** [comment]
> The test site and reported user's site is currently public and not set to private or coming soon. Is that what you meant by launching?

That's what I meant, yes, thanks!

I do see the icons on their site right now:

![image](https://user-images.githubusercontent.com/426388/129914452-b729f4c3-3cd3-4e24-93a8-b62050fa9b0f.png)


> They have the Social Icons (Jetpack) widget in the block widget area, and have a link to linkedin added, but nothing is visible on the live site at all. 

I do see it on my end:

![image](https://user-images.githubusercontent.com/426388/129914185-86beb755-df71-4cab-a191-71ab4efbee00.png)

Would you both happen to be using a browser extension that may impact this? A privacy or ad-blocking extension for example? If not, and if you're using Firefox, could you check if its built-in tracking tools are currently active, and if deactivating them helps in any way?

**Comment by jeherve** [comment]
I wonder if #20703 may play a role here; something to do with how the new block-based widget editor allows you to save data in widgets.

It would be interesting to know if those widgets were created:
- Before WP 5.8, in the old widget editor screen, and then updated since 5.8 was released.
- After WP 5.8, in Appearance > Customize > Widgets
- After WP 5.8, in Appearance > Widgets (the full-screen block-based widget editor).

**Comment by kimerlin81** [comment]
I have a similar issue where the Social Icons Widget (Jetpack) links are only displaying when viewing [the site](https://educationpathfinder.co.uk/) in the customizer. [Screenshot](https://d.pr/i/Vtrv4w)

Visitors to the site are unable to view the icons, but if you [hover over the area they are positioned in within the footer](https://d.pr/i/v0JARp), the links are clickable and redirect visitors to the specified URLS. I tried editing the display properties in CSS, but this is seemingly not affected by CSS and occurs on all browsers I've tested.

**Comment by kuropixel** [comment]
@jeherve  >I do see the icons on their site right now:

I believe that is the non-Jetpack social icons widget. They went that route as a workaround for now.

**Comment by kuropixel** [comment]
>Would you both happen to be using a browser extension that may impact this? A privacy or ad-blocking extension for example?
In my case for my test site, I have uBlock Origin disabled for it and was experiencing issues.

I recorded a video of trying to add a social icon on the test Atomic site and the input not saving when updating and going back to the widgets page. https://d.pr/v/PmiZKJ

**Comment by kbrown9** [comment]
I can reproduce this bug on a Jetpack site. I can successfully add the social icons on the Customize page. However, on the Widgets page, I see the same behavior as @kuropixel.
