### ISSUE TITLE
Widget visibility options don't work with WooCommerce 'Shop' page

### ISSUE THREAD

**Issue by melek** [Automattic/jetpack#20693]
#### Steps to reproduce the issue
1. Enable Jetpack and WooCommerce
2. Enable Widget Visibility options in Jetpack (JP → Settings → Writing → Widget)
3. Add any legacy widget (I used 'Meta') and set it to 'Show' on the 'Shop' page (ensure this is the page set as 'Shop' in Woo)
4. Go to the Shop page, notice that widget does not appear.
5. Repeat test with another page, such as the Homepage (if using a static homepage). Widget appears.

#### What I expected
I expected the shop page to show the widget only on the shop page. 

#### What happened instead
The widget did not appear.

**Additional Info**
There may be special logic needed to account for the Shop page; 
Tested on two sites, my own test site and a client site: 4220508-zen
WordPress 5.8, Woo 5.5.2, Jetpack 10.0

**Comment by jeherve** [comment]
Thanks for the report. This was originally reported in #8343.

> set it to 'Show' on the 'Shop' page (ensure this is the page set as 'Shop' in Woo)

I would recommend using this setting instead:

![screenshot 2017-12-11 at 23 06 37](https://user-images.githubusercontent.com/426388/33856315-06420356-dec8-11e7-8ff1-45c4eae863c8.png)
