### ISSUE TITLE
Comments: Allow reply by email

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#2070]
It would be awesome to be able to reply by email to comment notifications delivered via email and have those inserted as comment replies on the site itself.

**Comment by georgestephanis** [comment]
I'd had thoughts on this before and someone said we already do support that.  Is it just for wpcom at the moment?

**Comment by chaselivingston** [comment]
@georgestephanis Yes, that's my understanding.

**Comment by samhotchkiss** [comment]
This is not in line with our current priorities/roadmap.  We may re-assess down the road, but I'm closing for now.  If there are 3 more requests after this comment, please re-open.
