### ISSUE TITLE
Create a package for adding re-publicize to wp-admin

### ISSUE THREAD

**Issue by allilevine** [Automattic/jetpack#20709]
#### Is your feature request related to a problem? Please describe.

We'd like to fix https://github.com/Automattic/wp-calypso/issues/51435 by adding a new Jetpack package. However, there are a few things we need to research and investigate first.

#### Describe the solution you'd like

Design: RJ2LtGXEt4ZzaZWPo5N8sE-fi-134%3A8070

I. Research the following and comment with solutions:
- [x] Adding a Share button to the posts lists in wp-admin (can we add a post action like in the design?) (@retrofox)
- [x] Opening a modal with sharing options, when the button is clicked (@allilevine)
- [x] Authenticating the sharing connection from wp-admin (@allilevine)
- [x] Reading the post data to share (@retrofox)
- [x] Requiring this package in the posts list package (@retrofox)
- [x] Finding a way to hide the features this package adds behind a feature flag (@allilevine)

II. Create the package:
- [ ] Using the results of our research, create the re-publicize package.

#### Describe alternatives you've considered

See https://github.com/Automattic/jetpack/issues/20545

#### Additional context

See https://github.com/Automattic/jetpack/issues/20545

**Comment by jeherve** [comment]
> adding re-publicize to wp-admin

Some more internal discussion about this:
p1629186558255100-slack-C01VDMPHG69

**Comment by retrofox** [comment]
> Add a Share button to the posts lists in wp-admin (can we add a post action like in the design?) (@retrofox)

We can. There are two hooks that allow extending the [post](https://developer.wordpress.org/reference/hooks/post_row_actions/) and [page](https://developer.wordpress.org/reference/hooks/page_row_actions/) actions:

**Comment by allilevine** [comment]
> Opening a modal with sharing options, when the button is clicked

- Add scripts and [import the modal component](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/modal/README.md)
- Enqueue the scripts as in [the initial PostList example](https://github.com/Automattic/jetpack/pull/20589/files#diff-e625eca622e1fe9c520f352b19697f1b7d720f338b17d10c118a7d99b5f67959R143)

> We can. There are two hooks that allow extending the [post](https://developer.wordpress.org/reference/hooks/post_row_actions/) and [page](https://developer.wordpress.org/reference/hooks/page_row_actions/) actions:

@retrofox What's the best way to trigger a modal open event when our action is clicked? [`querySelector`](https://github.com/Automattic/jetpack/pull/20589/files#diff-5637e511653ce636497102b0f99691580c149d33ba9ad69b24ff7deb244d5f80R27)?

**Comment by retrofox** [comment]
> @retrofox What's the best way to trigger a modal open event when our action is clicked? [`querySelector`](https://github.com/Automattic/jetpack/pull/20589/files#diff-5637e511653ce636497102b0f99691580c149d33ba9ad69b24ff7deb244d5f80R27)?

Nice question. I'll try to explain what I think could be a nice approach here.

As we know, the vision would be to "replace the current app with a single web app". Ambitious but doable. In fact, that's the Calypso idea. But we need to do it progressively, so what we are doing is creating some tiny React components and rendering them in a specific part of the UX.

The key is what should be tackled by the component, and what shouldn't. For instance, for the `Share` link, I'd replace the link with a `<Button />` component (@wordpress/components package).

<img width="853" alt="Screen Shot 2021-08-18 at 1 23 27 PM" src="https://user-images.githubusercontent.com/77539/129935484-7792b1bd-1707-44b8-90dc-51f3cb11d3cb.png">

So we need to find a way to get the placeholder (selected as you pointed above) to render the React component there. If you do that, then we can trigger the modal via the onClick property provided by the Button component.

For instance, we've created a `<FeaturedImage />` that renders the featured image when the post has defined it:

<img width="1477" alt="Screen Shot 2021-08-18 at 1 30 48 PM" src="https://user-images.githubusercontent.com/77539/129936782-98c834a7-9fea-4c5b-abfb-dabf2889a03c.png">

**Comment by retrofox** [comment]
> Reading the post data to share

It's possible to get and propagate post data from the backend to the client without big issues. Something that we alredy do in the FeaturedImage PR

**Comment by retrofox** [comment]
> Requiring this package in the posts list package

If I'm not wrong, and once the package is published, it can be required by another project just by adding it as a dependency of it. Let's say the package name is `automattic/jetpack-re-publicize` and we'd like to add it as a ListPost dependency, it will be enough doing something like...

```bash
composer require @automattic/jetpack-re-publicize`
```

... in the package root folder.

**Comment by allilevine** [comment]
> Authenticating the sharing connection from wp-admin

We can get the site's connections either via a call to the WPCOM API [like in Calypso](https://github.com/Automattic/wp-calypso/blob/dfe93e6d8e240bf88eb7d7df75ef489d21391eed/client/lib/wpcom-undocumented/lib/undocumented.js#L1134), or possibly in [the same way as the Jetpack Publicize module](https://github.com/Automattic/jetpack/blob/380987aa86390382df1c3053d36f6bc20a4198d8/projects/plugins/jetpack/modules/publicize/publicize-jetpack.php#L128).

We'll first need to [check that the user is connected via Jetpack](https://github.com/Automattic/jetpack/blob/380987aa86390382df1c3053d36f6bc20a4198d8/projects/plugins/jetpack/modules/publicize/publicize-jetpack.php#L49). We may also want to check that the site is eligible for re-publicize.

If the site doesn't have any Publicize connections, we can send them to Marketing > Connections in Calypso (as re-publicize in Calypso does now). I'm not sure we'd want to redirect back on a successful connection though, in case users want to add multiple connections. It might be nice to have a "When you're finished, head back here" banner or link.

Once the user is authenticated and connected, we can [share the post](https://github.com/Automattic/wp-calypso/blob/dfe93e6d8e240bf88eb7d7df75ef489d21391eed/client/lib/wpcom-undocumented/lib/undocumented.js#L1233).

**Comment by allilevine** [comment]
> Finding a way to hide the features this package adds behind a feature flag

Looks like in the past we've used a filter: p1533812050000309-slack-CBG1CP4EN
Example: https://github.com/Automattic/jetpack/pull/10008/files#diff-f40c49170deb12cbf9463052741fd623ff2b99151a86cb8efbc7147c7cc8b3fcR7285

We could also limit the feature to internal testing.

**Comment by retrofox** [comment]
> We could also limit the feature to internal testing.

It sounds like we can start to work on the next step ;-)

**Comment by obenland** [comment]
@allilevine Can this be closed now?

**Comment by allilevine** [comment]
> @allilevine Can this be closed now?

Yes thanks! Closing since this change is no longer necessary.
