### ISSUE TITLE
Pay with PayPal Block: Editor gets dirty after post publishing

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#20724]
#### Steps to reproduce the issue

1. Make sure permalinks using a non-plain format (wp-admin > settings > permalinks)
2. Create a post with "Pay with PayPal" block. 
3. Switch to the code editor, note the `href` attribute, which looks like this: `href="https://thoughtful-dingo.jurassic.ninja/?p=64"`
3. Publish the post.
4. Note that post-publish panel is not shown after the publish.
5. Note that the editor has unsaved changes (try to navigate away from the editor, alert will be shown)
6. Switch to the code editor, discover that URL has changed: `href="https://thoughtful-dingo.jurassic.ninja/2021/08/13/64/"`

Apparently, block content gets updated _after_ post is published, basically to update post URL from draft, to actual URL. This leads to few issues:
- Editor become dirty, meaning a user would need to save/update before safely leaving the editor
- Due to the changes in a block, post-publish panel not displayed. 

**Screenshots**

https://user-images.githubusercontent.com/5654161/129692630-9cd188dc-3664-4e7b-9a7b-dbdcb0b89581.mp4

**Comment by brbrr** [comment]
Just a reminder that this issue is still there 😬

**Comment by simison** [comment]
@ianstewart @Copons would this be good for Expand team's maintenance backlog?

**Comment by Copons** [comment]
Thanks @simison; we must have missed this when gathering issues for payment blocks a few months ago.
Adding to the Ajax board! ✨
