### ISSUE TITLE
Enhancement: old Jetpack favicon still displaying via Photon

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#2074]
I've been going through scouring our modules, widget, and features for #trash-pickup, came across this tidbit.

I've got Photon activated, and I'm suing the carousel. When a user clicks to view the full image, the old Jetpack logo display as the favicon. I think it's related to photo, anyway. 

![screen shot 2015-05-01 at 5 06 47 pm](https://cloud.githubusercontent.com/assets/214813/7437402/1b531b70-f025-11e4-9d29-3c7e1b08e334.png)
![screen shot 2015-05-01 at 5 06 58 pm](https://cloud.githubusercontent.com/assets/214813/7437401/1b52ae24-f025-11e4-883f-1d3af0e5e042.png)
![screen shot 2015-05-01 at 5 08 15 pm](https://cloud.githubusercontent.com/assets/214813/7437403/1b55e17a-f025-11e4-95c2-5dec475f7026.png)

**Comment by kraftbj** [comment]
We just need an updated ICO and systems can push it through.

**Comment by jeffgolenski** [comment]
Thanks for the reminder @kraftbj , posting to systems, now!

**Comment by jeffgolenski** [comment]
Remedied.
