### ISSUE TITLE
Boost: Review and if necessary refactor the CSS structure and convention

### ISSUE THREAD

**Issue by davidlonjon** [Automattic/jetpack#20759]
Currently we are preferring to put CSS in the .scss files in assets/src/css/* over embedding styles in each component separately, as that seems to be more flexible and encourages more reuse across files.

But that’s been an ongoing discussion in the team for a while! Annoyingly, there are pros and cons to using component-based styles…

We need to finalize our structure and decide whether or not we want the CSS in components or separate SCSS files and document it in the developer documentation.

We also should take the opportunity to document class notation and whether or not fully embracing the BEM notation

**Comment by thingalon** [comment]
No longer relevant.
