### ISSUE TITLE
CLI: Suggestion: Add a new Jetpack Docker command to run PHPUnit only for a specific project

### ISSUE THREAD

**Issue by davidlonjon** [Automattic/jetpack#20761]
### What

Currently we have a `Jetpack docker phpunit` command that run PHPUnit tests only for Jetpack. Since now the monorepo includes several plugin, it could be good to have a similar command to run PHPUnit tests for a specific project

### How

Currently at least for the Boost plugin PHPunit can be ran in 2 ways:

- from outside Docker using `cd projects/plugins/boost; composer test-php`
- from inside Docker (kind of workaround) `jetpack docker exec -- sh -c "composer -d wp-content/plugins/boost test-php"`

Could it be beneficiary/useful to have a similar command to the `Jetpack docker phpunit` (which is only specific to Jetpack) but for a specific project instead. Maybe the command could be something like

- `jetpack docker plugins/boost phpunit`
 
This would be aligned with the other Jetpack CLI commands for specific projects such as for example:

- `jetpack install plugins/boost`
- `jetpack watch plugins/boost`

This requested suggestion can raise these 2 additional questions:
- What is the advantages to run the PHPunit for projects from Docker? Maybe consistency of environment for developers to run PHPunit tests?
- If we introduce a new command such as `jetpack docker PROJECT/PATH phpunit` what would become of the behaviour of the `Jetpack docker phpunit` command. Should it still carries on to run PHPunit tests only for Jetpack, or run PHPunit tests for ALL projects (maybe difficult to implement...)

Feel free to discard this request if really not relevant or not a priority since there are alternative solutions at the moment.

**Comment by jeherve** [comment]
cc @sdixon194 who's most familiar with the Jetpack CLI command.

**Comment by kraftbj** [comment]
> What is the advantages to run the PHPunit for projects from Docker? Maybe consistency of environment for developers to run PHPunit tests?

That's the gist. I'd have to look back to remind myself of what led in particular to doing so, but consistency plus testing on the same platform as the localhost server was running.

> `jetpack docker plugins/boost phpunit`

My gut reaction is what about `jetpack test {project} {test-type}`? Maybe running inside Docker doesn't make sense for Boost (while it does for Jetpack proper) or running the JS tests wouldn't make sense within Docker, etc etc etc.

**Comment by davidlonjon** [comment]
Hi @kraftbj , @anomiex,

Thank you for the feedback. Yes Jetpack Boost unit tests do not depend on WordPress and as Jetpack Boost does not have many Jetpack Boost unit tests 😬  for the time being they can definitely for now run outside Docker.

Additionally, since we are documenting in Jetpack Boost how to run the unit tests this suggestion can be closed as it may not bring much additional value for now. I'll leave it to you @sdixon194 to decide since you self assign this ticket to you?

**Comment by kraftbj** [comment]
The CLI could have a `test` command that runs the various test scripts defined, and whether it needs docker or not could be behind the scenes.

**Comment by sdixon194** [comment]
> Additionally, since we are documenting in Jetpack Boost how to run the unit tests this suggestion can be closed as it may not bring much additional value for now. I'll leave it to you @sdixon194 to decide since you self assign this ticket to you?

Yup, as Kraft said, I'm working on a CLI command that will run the tests defined in composer.json, but leave it up to the individual projects to determine how the tests should be run.
