### ISSUE TITLE
Your website needs to be publicly accessible: squeezed too quickly!

### ISSUE THREAD

**Issue by bobbingwide** [Automattic/jetpack#2076]
On a WordPress MultiSite installation using subfolders and domain mapped using wordpress-mu-domain-mapping I get the message
`<div class="squeezer">
		<h4>Your website needs to be publicly accessible to use Jetpack: <code>site_inaccessible</code></h4>
		<p>Error Details: The Jetpack server was unable to communicate with your site [HTTP 403].  Ask your web host if they allow connections from WordPress.com. If you need further assistance, contact Jetpack Support: http://jetpack.me/support/</p>
	</div>`

### Expected result
The message gets shown for long enough for me to read it
### Actual result
It goes away too quickly

PS. Whether or not it's telling the truth has yet to be confirmed.
PPS. It would also be nice to see the request it tried.

**Comment by jeherve** [comment]
cc @jessefriedman, since it's related to Jumpstart.

**Comment by jeherve** [comment]
> PS. Whether or not it's telling the truth has yet to be confirmed.
> PPS. It would also be nice to see the request it tried.

Could you go to the Jetpack menu page, scroll down to the bottom of the page, and then click on the "Debug" link? You will then be able to send is detailed information about your site so we can help you solve that issue.

Thanks!

**Comment by bobbingwide** [comment]
ok, BTW, the main site (officialcaravan.co.uk) has also "gotten mixed up!"

On the parked site I get
"XML-RPC is not responding correctly ( 403 )"
I can't test the curl command right now myself
curl -A 'Jetpack by WordPress.com' -d 'demo.sayHello' http:\/\/officialcaravan.co.
uk\/paradisefilter\/xmlrpc.php

but I do know XML RPC is working

http://paradisefilter.com/xmlrpc.php

I'll look at the access logs later.
But off to golf... it's a bank holiday here

**Comment by bobbingwide** [comment]
oops, didn't mean to close

**Comment by jeherve** [comment]
Could you use the Debug page to send us detailed information about both sites? Thanks!

**Comment by bobbingwide** [comment]
main site debug produces
`IDENTITY_CRISIS:
	Your `siteurl` option is set up as `http://officialcaravan.co.uk`, but your WordPress.com connection lists it as `0`!
Your `home` option is set up as `http://officialcaravan.co.uk`, but your WordPress.com connection lists it as `1`!`
AND
`SELF:
	Array
(
    [headers] => Array
        (
            [server] => nginx
            [date] => Mon, 04 May 2015 19:51:50 GMT
            [content-type] => text/plain;charset=utf-8
            [connection] => close
            [x-pingback] => https://jetpack.wordpress.com/xmlrpc.php
            [expires] => Wed, 11 Jan 1984 05:00:00 GMT
            [cache-control] => no-cache, must-revalidate, max-age=60
            [pragma] => no-cache
            [x-hacker] => Jetpack Test
        )

    [body] => {"error":"Could not validate security token","error_description":"We were unable to validate a security token for Jetpack communication. Please try disconnecting Jetpack from your WordPress.com account, and connecting it again."}
    [response] => Array
        (
            [code] => 400
            [message] => Bad Request
        )

    [cookies] => Array
        (
        )

    [filename] => 
)`

**Comment by bobbingwide** [comment]
paradisefilter site produces
`SELF:
	Array
(
    [headers] => Array
        (
            [server] => nginx
            [date] => Mon, 04 May 2015 19:55:58 GMT
            [content-type] => text/plain;charset=utf-8
            [connection] => close
            [x-pingback] => https://jetpack.wordpress.com/xmlrpc.php
            [expires] => Wed, 11 Jan 1984 05:00:00 GMT
            [cache-control] => no-cache, must-revalidate, max-age=60
            [pragma] => no-cache
            [x-hacker] => Jetpack Test
        )

    [body] => {"error":"Jetpack not connected","error_description":"We were unable to find a Jetpack instance on your site. Please connect Jetpack to your WordPress.com account from within your WordPress admin."}
    [response] => Array
        (
            [code] => 400
            [message] => Bad Request
        )

    [cookies] => Array
        (
        )

    [filename] => 
)`

**Comment by bobbingwide** [comment]
I then changed the Domain Options to match those in #2016; previously the checked items were 1., 3., and 4 and reconnected successfully on both sites.

**Comment by jeherve** [comment]
@bobbingwide Could you send us the detailed debug results using the contact form on the debugger page? It contains more information that may help us understand the problem.

Thanks!

**Comment by bobbingwide** [comment]
Hi, not right now on the original sites as they are working and I don't want to break them.
I played with other multisite sites to attempt to reproduce the problem. I think I partially managed it. 

main WPMS: rowlandscastlewebdesign.com
child site: rowlandscastlewebdesign.com/top-10-wp-plugins 
mapped to: top-10-wp-plugins.com

A debug email is now on its way.
BTW. It wasn't immediately obvious that the "click here to contact Jetpack support" link was going to open up the contact form to send the debug info. 


On the subject of Squeezed too quickly
this message also disappeared before I had a chance to read it.

`<div class="squeezer">
		<h4><strong>Is this site private?</strong></h4><br>
		<p>Like your site’s RSS feeds, <strong>Enhanced Distribution</strong>, <strong>Enhanced Distribution</strong>, and <strong>Enhanced Distribution</strong> allow access to your posts and other content to third parties.
<br>
If your site is not publicly accessible, consider <a href="http://rowlandscastlewebdesign.com/top-10-wp-plugins/wp-admin/admin.php?page=jetpack&amp;action=deactivate&amp;module=enhanced-distribution%2Cenhanced-distribution%2Cenhanced-distribution&amp;_wpnonce=xxxxxxxxx" title="Deactivate Enhanced Distribution, Enhanced Distribution, and Enhanced Distribution">deactivating these features</a>.</p>
	</div>
`

**Comment by bobbingwide** [comment]
I've had a response from the hosting company...

It looks like you are hitting a security rule regarding XML parsing. 
I have exempted the domain from this rule, please retest and see if that solves the problem.
Please note that you may hit further rules, as once a rule is triggered the process gets stopped, so we may have to exempt further rules as you retest.
This ruleset has been in place for over a year now, however like many things the rules are continuously updated to cater for new threats.

I've asked for more information.

**Comment by richardmtl** [comment]
Closing as we are communicating via email, and the issue seems to be host-related.

**Comment by bobbingwide** [comment]
Hi, the original problem... *box disappears from view before I get a chance to read* it is still a valid bug.

The fact that my hosting company is blocking the requests is merely one way to cause the messages to be displayed in the first place.

**Comment by jeherve** [comment]
Agreed.

**Comment by bobbingwide** [comment]
I've sent an email reply to @richardmtl with more info on the 403 and a follow up question.
