### ISSUE TITLE
Boost: Critical CSS onload events can increase CLS

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#20762]
### Impacted plugin

Boost

### Steps to Reproduce

1. Create a test site with multiple CSS files which affect the same element - with wildly different styles. e.g.: huge fonts in one, tiny the other.
2. Rig the site so that the CSS files load at different speeds. Maybe host them on different hosts, or rig a PHP sleep before one can be served.
3. Generate Critical CSS for the site.
4. Run a lighthouse report for the homepage.

As each CSS file loads, its `onload` event in its `link` tag will activate, turning the stylesheet on. If each CSS file has wildly different styles, it can cause the page to re-layout and impact the CLS score.

Here is a demo `mu-plugin` which forces it to occur on a site:
```
<?php

/**
 * Load a slow style late in the source (i.e. overrides fast style)
 */
add_action( 'wp_enqueue_scripts', function() {
	wp_enqueue_style( 'slow-style', add_query_arg( 'hack-css', 'slow', site_url() ) );
}, 1000 );

/**
 * Load a fast style early in the source
 */
add_action( 'wp_enqueue_scripts', function() {
	wp_enqueue_style( 'fast-style', add_query_arg( 'hack-css', 'fast', site_url() ) );
}, 1 );

if ( ! empty( $_GET['hack-css'] ) ) {
	if ( 'slow' === $_GET['hack-css'] ) {
		slow_css();
	} else {
		fast_css();
	}
}

function slow_css() {
	sleep( 2 );
	header("Content-type: text/css");

	?>
	        h1 {
		        font-size: 1.125em;
		        margin-top: 20px;
	        }
	<?php
	die;
}

function fast_css() {
	header("Content-type: text/css");

	?>
                h1 {
                        font-size: 300px;
                        margin-top: 100px;
                }
	<?php
	die;
}
```

Props to @eAdnan007 for helping me dig into a user report to diagnose this issue

**Comment by eAdnan007** [comment]
The solution we initially discussed was: Keep all stylesheets disabled until the window load event. While currently, we enable stylesheets as soon as they are loaded.

Implementing the change^ is a change that would affect how critical CSS works currently and affect existing websites. A serious side-effect would be that the page would look broken below the fold and result in a negative user experience. This is likely to happen if there are stylesheets with slow response time and if there are too many stylesheets.

The CLS issue is not a common issue every site will face. We discussed it in slack(p1629866198004000-slack-D029B314SSZ) and it seems that most websites are better off with the current way it is implemented(enable stylesheet when it's loaded). For those sites that are having the CLS issue, we can offer another advance setting option, where they can opt-in to use the alternate loading method(enable stylesheets on window load event).
