### ISSUE TITLE
Widgets: allow setting timeframe for Popular Posts and Pages widget

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#2077]
Add a timeframe for the popular posts and pages widget this will allow the user to adjust the timeframe of the widget. ( adjusting the range from which the popular posts and pages get calculated )

This has already been implemented in something similar has already been implemented in https://wordpress.org/plugins/jetpack-popular-posts/

Currently the user can only adjust the widget timeframe via a filter. The default is 2 days.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
