### ISSUE TITLE
HTTPS support in the Polldaddy shortcode

### ISSUE THREAD

**Issue by kovshenin** [Automattic/jetpack#2079]
Howdy! Looks like http is hard-coded in various places in the Polldaddy shortcode, which prevents javascript from being loaded in many browsers on an HTTPS site.

**Comment by georgestephanis** [comment]
cc: @donnchawp

**Comment by kovshenin** [comment]
I checked the WordPress.com version and it seems to support HTTPS, so this probably just needs to be resynced.
