### ISSUE TITLE
Build Tools: issues following Webpack 5 update

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#20792]
* [x] `WARNING in DefinePlugin` `Conflicting values for 'process.env.NODE_ENV'`
  - This is a calypso-build bug, see Automattic/wp-calypso#56291
* [x] `[DEP_WEBPACK_EXTERNALS_FUNCTION_PARAMETERS] DeprecationWarning: The externals-function should be defined like ({context, request}, cb) => { ... }`
* [ ] `[DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API`
* [x] `[DEP_WEBPACK_CHUNK_MODULES_ITERABLE] DeprecationWarning: Chunk.modulesIterable: Use new ChunkGraph API`
* [x] `[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.`
* [x] `[DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET_PUSH] DeprecationWarning: chunk.files was changed from Array to Set (using Array method 'push' is deprecated)`
* [x] `Using / for division is deprecated and will be removed in Dart Sass 2.0.0.`
  - #21105

**Comment by anomiex** [comment]
Output looks the same to me with pnpm 6.13.0 vs 6.14.2.

The quoted messages seem more likely to be due to the update to webpack 5 in #20730.

**Comment by anomiex** [comment]
Looks like most of these have been fixed since this was filed, except for `DeprecationWarning: Module.issuer: Use new ModuleGraph API`.
