### ISSUE TITLE
Boost: Critical CSS problems with user-agent-dependent content

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#20803]
Based on a [user reported issue](https://wordpress.org/support/topic/jetpack-boost-failure-to-generate-critical-css/), it looks like some sites implement mobile support by serving wholly different HTML content based on the `User-Agent` header.

Using the wrong Critical CSS for the wrong version of a page can worsen page performance.

### Steps to Reproduce

1. Set up a WordPress site whose content renders differently based on the `User-Agent` header. See below for a drop-in `mu-plugin` which simulates a minor version of this behaviour.
2. Generate Critical CSS.
3. Compare Mobile device lighthouse results with CSS enabled and disabled.
4. You should see the performance of the site suffer. The sample below will generally mess up your CLS score specifically.

To reproduce, drop this in your `mu-plugins` directory as a `php` file:
```php
<?php

// If serving to mobile, add a class to the body.
$is_mobile = preg_match( '/(android|avantgo|blackberry|bolt|boost|cricket|docomo|fone|hiptop|mini|mobi|palm|phone|pie|tablet|up\.browser|up\.link|webos|wos)/i', $_SERVER['HTTP_USER_AGENT'] );
if ( $is_mobile ) {
	add_filter( 'body_class', function ( $classes ) {
		return array_merge( $classes, [ 'mobile-hack' ] );
	} );
}

// Always serve css which depends on body class.
add_action( 'wp_enqueue_scripts', function() {
	wp_enqueue_style( 'fast-style', add_query_arg( 'hack-css', 'fast', site_url() ) );
}, 1 );

// Output CSS if get param says to.
if ( ! empty( $_GET['hack-css'] ) ) {
	header("Content-type: text/css");

	?>
		body.mobile-hack h1 {
			padding-top: 300px;
		}
	<?php

	die;
}

```

### Notes

- This was initially reported from mixing WPTouch with Jetpack Boost.
- Some caching plugins do not allow for different caches for different user-agent, [but some do](https://support.wptouch.com/article/1446-configuring-cache-plugins-for-wptouch).
- We may be able to solve this issue by offering a filter / setting for separated Critical CSS by device type, and working with WPTouch to recommend the setting is used when both plugins are used together.

**Comment by eAdnan007** [comment]
WP Touch shows a different theme depending on user agent. We can try to see if they utilize [`wp_is_mobile()`](https://developer.wordpress.org/reference/functions/wp_is_mobile/), in which case we might be able to hook into the filter for detecting the device.

**Comment by thingalon** [comment]
Closing this in favor of 100-gh-Automattic/boost-cloud
