### ISSUE TITLE
Gathering Tweetstorms: Deprecated wp.data.select( 'core/editor' ).getSelectedBlock warning

### ISSUE THREAD

**Issue by tommusrhodus** [Automattic/jetpack#20806]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Setup a default install with Jetpack installed and activated
2. Edit a post and open browser console
3. When clicking on a paragraph element notices will appear in console ```Deprecated wp.data.select( 'core/editor' ).getSelectedBlock``` and ```Deprecated wp.editor.RichTextToolbarButton```

### A clear and concise description of what you expected to happen.

No deprecated errors should appear in console.

### What actually happened

Deprecated errors should appear in console.

### Operating System

macOS

### OS Version

11.2.1

### Browser

Safari

### Browser Version(s)

14.0.3

**Comment by jeherve** [comment]
Thanks for the report.

> Deprecated wp.data.select( 'core/editor' ).getSelectedBlock

I believe this is similar to the issues I faced with the Gathering Tweetstorms feature in https://github.com/Automattic/jetpack/pull/18860/commits/c4dacfa73cc8e4436ac0892c5a7132f31688e164

We'll need to revisit this to solve this issue.

> Deprecated wp.editor.RichTextToolbarButton

This warning comes from code that lives on WordPress.com, so I've opened an issue here to track this:
https://github.com/Automattic/wp-calypso/issues/55682
