### ISSUE TITLE
Protect: allow array of IP addresses in JETPACK_IP_ADDRESS_OK

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2082]
It would be nice if site owners could define multiple IP addresses using the `JETPACK_IP_ADDRESS_OK` constant in wp-config.php.

Suggested here:
https://wordpress.org/support/topic/protect-aka-brute-force-whitelist

**Comment by georgestephanis** [comment]
Comma-seperated list?  Honestly, I believe it's just meant to be a temporary shim so you can get in and set the option.  But constant is probably more useful for multisite.

**Comment by jeherve** [comment]
Related: #1861

**Comment by samhotchkiss** [comment]
I agree with George-- people shouldn't be using `JETPACK_IP_ADDRESS_OK` as a long-term solution, so I'm not inclined to make it easier to do so
