### ISSUE TITLE
Related Posts: display Posts in the cutomizer

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2083]
Steps to reproduce the issue:
1. Enable Jetpack's Related Posts
2. Go to Appearance > Customize in your dashboard.
3. Click on a post
4. The Related Posts aren't displayed on that page.

cc @xyu 

Reported here:
https://wordpress.org/support/topic/jetpack-related-posts-not-displaying-in-live-customizer

**Comment by jessefriedman** [comment]
From what I can tell. related-posts.js is looking to find posts related to the current URL which looks something like: http://jes.se.com/wp-admin/customize.php?return=%2Fwp-admin%2Fthemes.php`

Since it can't find any related posts it simply doesn't load them.

**Comment by kraftbj** [comment]
@jessefriedman is on the right track. Checking the inspector, it makes the call to `https://example.com/wp-admin/customize.php?url=https%3A%2F%2Fexample.com%2F2015%2F05%2Fexample%2F&relatedposts=1&relatedposts_exclude=undefined` which returns the actual customizer page, not the RP callback.

**Comment by jeherve** [comment]
This is now fixed.
