### ISSUE TITLE
Instant Search: remove 'when results loaded' modal trigger option

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#20849]
One of the three overlay trigger options a user can choose is 'when results loaded'. This opens the modal when the first API call with results has returned.

This is not ideal because:
- The timing is based on API speed/network conditions and not user input
- The modal opening can come as a surprise to the user

Furthermore, this option actually feels fairly similar in practice to the "When user starts typing" trigger.

<img width="290" alt="Screen Shot 2021-08-27 at 14 40 19" src="https://user-images.githubusercontent.com/17325/131063316-63635214-35fa-424d-a7c8-886990fd75fd.png">

**Comment by bluefuton** [comment]
This is currently being set as the default option for new users.

**Comment by a8ck3n** [comment]
Just adding my two cents here. I find this behaviour quite frustrating as I typically lose characters to the context switch. This means my results are usually not useful unless I clear the search field and start again. I'd argue this option should either be removed or, at the very least, not be the default option.
