### ISSUE TITLE
Instant Search: investigate first-party endpoint to get around cookie/ITP issues on private simple sites

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#20847]
In certain circumstances, calling the search API on public-api.wordpress.com is problematic. On our internal resource 'Field Guide', a private site on a custom domain, it's not possible to use Instant Search due to cookie/ITP issues in Safari (and higher privacy settings on other browsers).

We should explore delivering search via a first-party endpoint (i.e. on the same domain as the site) to avoid these issues.

**Comment by bluefuton** [comment]
Is this now resolved @jsnmoon?

**Comment by jsnmoon** [comment]
Yes, fixed by https://github.com/Automattic/jetpack/pull/21144.
