### ISSUE TITLE
General: Minimum supported? 4.1 or 4.1.1?

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2085]
In reference to #1827, 4.1 has a bug that would lead to a JP infinite loop. Opening a separate discussion on if we should bump our minimum supported to 4.1.1 to avoid having to patch around a reverted core bug.

IMO, it would be okay to update this, plus updating the existing readme.txt for 3.5.1. It's edge case with core at 4.1.4 for those still on that branch. Reminded of it from a WPEngine customer who hadn't been upgraded off of 4.1 yet.

cc: @samhotchkiss

**Comment by samhotchkiss** [comment]
I'm definitely okay with bumping to 4.1.1, as folks should be on at least 4.1.4 for security.

Maybe we should just bump to 4.1.4?  @georgestephanis ?

**Comment by samhotchkiss** [comment]
(I think I can bump this without needing a new version of jetpack, BTW)

**Comment by samhotchkiss** [comment]
Bumped this to 4.1.1 in 3.5.2

**Comment by jeherve** [comment]
> Bumped this to 4.1.1 in 3.5.2

@samhotchkiss I don't seem to see the changes here, either in the release branch or on master:
https://github.com/Automattic/jetpack/blob/branch-3.5/jetpack.php#L15
https://github.com/Automattic/jetpack/blob/master/jetpack.php#L15

Can I update both?

**Comment by dereksmart** [comment]
Taken care of in 39dd071
