### ISSUE TITLE
Extract Publicize functionality for use in a JS package

### ISSUE THREAD

**Issue by allilevine** [Automattic/jetpack#20879]
**Is your feature request related to a problem? Please describe.**

This is related to fixing Automattic/wp-calypso#51435. We want to create a JS package for Publicize, to be used to add Re-Publicize in a Composer package. The task here is to extract Publicize functionality for use in the JS package, similar to how Publicize works in the editor sidebar.

**Describe the solution you'd like**

An answer to, how difficult is it to extract this Publicize functionality? What does it depend on?

**Comment by jeherve** [comment]
> how difficult is it to abstract Publicize?

I guess it depends how much you want to extract. The Publicize feature depends on quite a few things today:

- It depends on the Redirect package to build Calypso URLs, as well as the Connection package, the Sync package, and the Options package.
- It uses methods from the `Jetpack` class that ships with the Jetpack plugin.
- It registers an admin settings page, that may be removed now (that page has only been including a link to Calypso for a few years now), using the `Jetpack_Admin_Page` class that ships with Jetpack.
- It is used to register an extension in the post editor, so relies on the `Jetpack_Gutenberg` class that ships with Jetpack, among other block-related things.
- It depends on the `Jetpack_Keyring_Service_Helper` class, that ships with the Jetpack plugin.
- It depends on the `Jetpack_Media_Summary` class, that ships with the Jetpack plugin. Although we could move this out of the Publicize feature (see #3004), or move `Jetpack_Media_Summary` into its own package (see #19579)

**Comment by allilevine** [comment]
> I guess it depends how much you want to extract. 

That's a good point, my description was pretty vague. The functionality we need is:
- Check that the site is eligible to re-publicize
- Get the site connections
- Provide a link to Calypso to set up a connection if needed
- Share the post

It looks like that all may have been similarly extracted [to the Publicize block](https://github.com/Automattic/jetpack/tree/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/extensions/blocks/publicize). We want to make all of those components available in a JS package.

> The Publicize feature depends on quite a few things today

We're hoping the PHP we'll be extracting will be minimal, but this is helpful to keep in mind since we are requiring this JS package in a Composer package.

**Comment by jeherve** [comment]
Closing this since we now have a Publicize Components js package.
