### ISSUE TITLE
Facebook share button does not load when site language is set to English (Australia)

### ISSUE THREAD

**Issue by jenhooks** [Automattic/jetpack#2089]
When a blog's language is set to English (Australia), the official Facebook sharing buttons do not show up on posts:

![fbsharebutton_english_au](https://cloud.githubusercontent.com/assets/7585054/7493555/ea644be8-f3cf-11e4-9193-1b00706f03a5.png)

Console error is seen here:

![fbsharebutton_english_au_2](https://cloud.githubusercontent.com/assets/7585054/7493566/004e57aa-f3d0-11e4-9a06-a56c3168b21c.png)

Steps to Reproduce:
1) Go to Settings > General, and change blog language to English (Australia)
2) Enable Facebook sharing under Settings > Sharing > Enabled services.
3) Enable 'Official buttons' under Settings > Sharing > Button style.
4) View any blog post and see Facebook button missing.

Related issue here: https://github.com/Automattic/io/issues/339

Reported in 2171003-t

**Comment by kraftbj** [comment]
We're not returning a facebook_locale here: https://github.com/Automattic/jetpack/blob/master/locales.php#L470-500

which sets the locale to false:
https://github.com/Automattic/jetpack/blob/master/modules/sharedaddy/sharing-sources.php#L695

which sets this to false:
https://github.com/Automattic/jetpack/blob/master/modules/sharedaddy/sharing-sources.php#L728

which causes us to request `http://connect.facebook.net//sdk.js` (the `$locale` should go between the double `//`, which 404s.

r117058-wpcom resolves it.

**Comment by kraftbj** [comment]
#2117 immediately resolve and #2116 (af8e40fbbcf764e04ba458279f7266ea41b4eb47 specifically) provides a fallback to prevent it from happening with other languages in the future.
