### ISSUE TITLE
Blocks: Preview image paths are not correct

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#20898]
### Impacted plugin

Jetpack

### Steps to Reproduce

Start on a WordPress.com Simple site

1. Go to Posts > Add New
2. Click on the block picker in the sidebar
3. Search for "tiled"
4. Check the block preview; the image is missing

Reference: p1630433830156600-slack-CBG1CP4EN

### Other information

![image](https://user-images.githubusercontent.com/426388/131555639-7580410b-06ce-441c-a75d-ca378004801f.png)

### Operating System

macOS

### Browser

Chrome/Chromium

**Comment by jeherve** [comment]
I wonder if this may be a byproduct of #20730

**Comment by inaikem** [comment]
User report: 29817927-hc.

**Comment by devNigel** [comment]
Adding related ticket: 4252941-zen

Informed user that we will follow up once the issue is fixed. Please update the user if the issue is resolved.

**Comment by jeherve** [comment]
Internal reference: p1630700944248800-slack-CBG1CP4EN cc @sdixon194

**Comment by sdixon194** [comment]
This is now fixed for Jetpack sites, but wpcom is still having issues. The fix did update the image URLs, but needs further investigation.

**Comment by jeherve** [comment]
This is now fixed on WordPress.com. I've fixed the issue on WordPress.com by re-committing a fresh set of images. The ones that had been committed a few weeks back were 0KB.
