### ISSUE TITLE
Jetpack Search: Network requests can arrive out-of-order for private simple WPCOM sites

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#20904]
### Impacted plugin

Jetpack

### Steps to Reproduce

Rapidly triggering queries, especially for a site with a large index, can result in search API responses arriving out-of-order. This only occurs when `wpcom-proxy-request` code path is used in our API code.

### Browser

Chrome/Chromium, Firefox

**Comment by jsnmoon** [comment]
Using a first-party API approach will enable us to use `fetch`, which includes support for cancellable requests and makes this issue obsolete.

**Comment by kangzj** [comment]
Hi @jsnmoon So i suppose the issue would be gone after `D67402` is shipped?

**Comment by jsnmoon** [comment]
Correct, this has now been resolved by using first-party/same-origin API requests for simple private sites.
