### ISSUE TITLE
Instant Search: make mobile user experience clearer

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#20908]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. On a site with Instant Search enabled, go to /wp-admin/admin.php?page=jetpack-search-customize.
2. Resize the window to the smallest mobile breakpoint.

### A clear and concise description of what you expected to happen.

It should be clear that we are on this page to update settings. 

### What actually happened

* When you land on the page, you see the modal preview, but you have to discover the cog icon to edit the settings.
* When you're done editing settings, you need to switch back to the modal preview in order to save the changes.

Possible solutions:
* Start the mobile user on the settings pane, and allow them to switch to the modal preview afterwards. The primary purpose of the screen is settings, so let's start them there.
* Add a Save button at the bottom of the settings pane so that is not necessary to switch back to the modal preview to complete the save.
* Add a simple instruction to direct the user towards the cog icon for customization, in case they miss it.

<img width="442" alt="Screen Shot 2021-09-01 at 14 51 34" src="https://user-images.githubusercontent.com/17325/131618157-3a570d90-5a7e-41a1-b4b5-8d899cc6d113.png">

### Browser

Firefox

**Comment by bluefuton** [comment]
cc @keoshi

**Comment by keoshi** [comment]
Ideally we could look into what Core does in these scenarios, but there's not a great solution out there yet and I also reckon our use case is especially unique.

I essentially agree with everything you said:
- **Start them on the settings pane**: people get to this screen by clicking the “Customize search results” so it makes sense to land them on a view that lets them do exactly that. In other words, they have the full context so showing the search preview is secondary, especially if they're familiar with JP Search or they've customized styling/options more than once.
- **Add save button**: +1 to this and I would even suggest we add the button to the very top of the customization pane to match the exact position of the existing Save button. Expecting people to go to the very bottom might be unrealistic, and adding it at the top would mean it's visible from the moment they land on this page. Here's a very quick and dirty draft of the idea:
![image](https://user-images.githubusercontent.com/390760/131641505-835e1933-9b8d-4c5a-a190-e724850c51ad.png)
- **Add instructions**: love this idea too, it's simple but very clear and visible.

**Comment by bluefuton** [comment]
Users are now started on the settings pane on mobile, which resolves most of what's been raised here 🎉

I still reckon we should add a save button on the settings pane, because it's quite difficult to find now (you have to find your way to the preview then Save).
