### ISSUE TITLE
Carousel: time to load first image is glacially slow (10 seconds or more)

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#20929]
### Impacted plugin

Jetpack

Note: the issue has been observed on a WordPress.com Simple site that does not use the main Jetpack plugin.

### Steps to Reproduce

1. Navigate to this site where I document how I'm ruining my garden https://kowhai.blog/2021/08/22/let-it-snow/
2. Open the image carousel
3. Wait for the first image to appear

### A clear and concise description of what you expected to happen.

First image should appear very quickly (within a couple of seconds).

### What actually happened

First image does not load for 10 seconds or so. After that, loading other images in the carousel is very fast.

### Other information

@glendaviesnz was kind enough to do some investigation for me, and says:

> there is something weird going on as it loads 3 x 14MB versions of images in the background, but the actual images in the carousel only seem to be around 800Kb, so something strange is going on with the lazy loading side of things I think

<img width="1260" alt="Screen Shot 2021-09-02 at 9 38 52 AM" src="https://user-images.githubusercontent.com/17325/131776732-4c0c1097-ca7f-465b-9a7f-3f14e4673e5b.png">

I'm not sure why the `w=4000` version is being loaded at all.

I have the image size in the gallery block set to 'Large'. The original photos are uploaded directly from my iPhone 12 mini.

### Browser

Firefox

**Comment by bluefuton** [comment]
Looks to perform well on a Jetpack site:

https://chilly-maple.jurassic.ninja/2021/09/06/carousel-test/

Oddly, seems to be loading well today on the original WordPress.com simple site too 🤔 Can you confirm it's loading speedily for you as well @jeherve?

https://kowhai.blog/2021/08/22/let-it-snow/

**Comment by jeherve** [comment]
It works well for me indeed:

![image](https://user-images.githubusercontent.com/426388/132211936-22a95bfe-e335-4f0c-ab7c-b93a48014f0a.png)

Good to close?

**Comment by bluefuton** [comment]
Yep! Looks fixed to me 👍
