### ISSUE TITLE
Allow stats graph 'Annotations' to be extended

### ISSUE THREAD

**Issue by cklosowski** [Automattic/jetpack#2093]
Would be great if a plugin developer could add 'Annotations' to the stats hover, where Jetpack shows 'Published:'

This would allow tracking spikes and dips in traffic by more than just publishing events.
![image](https://cloud.githubusercontent.com/assets/1390124/7520800/3bd5741a-f49e-11e4-880b-2bac8e1f275e.png)

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
