### ISSUE TITLE
Publicize: Identify new re-publicize components

### ISSUE THREAD

**Issue by allilevine** [Automattic/jetpack#20939]
### Impacted plugin

Jetpack

### What

Create new re-publicize components based on new designs

### How

![republicizedesigns](https://user-images.githubusercontent.com/1689238/132712767-aa045e0d-6256-4cdd-bb71-43dd65a019c1.png)

Create the following components based on the design and add them to Storybook:

- [ ] checkbox + connection icon + username (@allilevine https://github.com/Automattic/jetpack/pull/20957)
- [ ] text area with character limit (@retrofox https://github.com/Automattic/jetpack/issues/21057)
- [ ] Share post | schedule button (@retrofox https://github.com/Automattic/jetpack/issues/21058)
- [ ] Cancel / Preview buttons

**Comment by allilevine** [comment]
I opened a draft PR for the first component, the connection icon: https://github.com/Automattic/jetpack/pull/20957

**Comment by pablinos** [comment]
We have some new designs for this and we're already working on the common components, so this can be closed.
