### ISSUE TITLE
Enhancement: Create plugins folder into extensions folder

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#20943]
### Impacted plugin

Jetpack

### What

Add a plugins folder into the extensions one. Be sure the compiles system will support it.

### How

Try to use a real example that justifies this purpose. For instance, moving sharing into it.

**Comment by jeherve** [comment]
Related: #16816, and #16931.

**Comment by retrofox** [comment]
duplicated here https://github.com/Automattic/jetpack/issues/16931
