### ISSUE TITLE
Enhancement: Fallback image setting for Related Posts

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/jetpack#20959]
### Impacted plugin

Jetpack

### What

A fallback image option for the Related Posts block

### How

In #2220, there is an old discussion on offering a default image option for Related Posts. Since we're moving towards the use of blocks, I think a new issue would be better.

Once **Display thumbnails** is selected, we could display a dropdown with fallback image options:

<img width="272" alt="Captura de Tela 2021-09-04 às 11 57 49" src="https://user-images.githubusercontent.com/1136160/132098899-f297e7d8-6330-4b1b-a63f-700c4752dac4.png">

The dropdown options could be:

1. None as the default. If the post has no featured image, nothing appears and there may be a mix of related posts with and without a featured image
2. The site logo/icon, as pointed out by @jeherve in https://github.com/Automattic/jetpack/issues/2220#issuecomment-109012407
3. The first image in the post. We're already doing something similar in two fronts:
    * In [Publicize](https://jetpack.com/support/publicize/), when the first fallback thumbnail for social media is an inline image  
    * In [WP.com Content Options](https://en.support.wordpress.com/customizer/content-options/). While Content Options is not something on newer themes, the option "Automatically Use First Image in Post" is helpful

Using a dropdown could also benefit plugin and theme developers looking for a way to extend what JP Related Posts offer and add their own options to the list. 

Thanks for considering!

**Comment by jeherve** [comment]
> In #2220, there is an old discussion on offering a default image option for Related Posts. Since we're moving towards the use of blocks, I think a new issue would be better.
