### ISSUE TITLE
Boost: recolour speed score bars based on score

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#20961]
According to the design team, we should be using specific CSS colour variables for various speed score "levels". (i.e.: when the speed score bar shows red / yellow / green for various score levels).

According to the designers, the colours we should use are:
```
Red: #D63638 or Red 50
Orange: #FAA754 or Orange 20
Green: #069E08 or Jetpack Green 40
```

Please update the speed score CSS rules to use the appropriate named variables (a new variable for the orange colour will need to be defined).

**Comment by amustaque97** [comment]
Hey @thingalon, I would love to work on this issue. I have few doubts. I have asked them below
* Color change is only required for these lines or this file specifically?
https://github.com/Automattic/jetpack/blob/6c406daba555108460e5007eca13d7b0c07af968/projects/plugins/boost/app/assets/src/css/components/score.scss#L175-L185
 OR
* I can update variables as a whole throughout the plugin in this file
https://github.com/Automattic/jetpack/blob/6c406daba555108460e5007eca13d7b0c07af968/projects/plugins/boost/app/assets/src/css/main/variables.scss#L2
https://github.com/Automattic/jetpack/blob/6c406daba555108460e5007eca13d7b0c07af968/projects/plugins/boost/app/assets/src/css/main/variables.scss#L7
https://github.com/Automattic/jetpack/blob/6c406daba555108460e5007eca13d7b0c07af968/projects/plugins/boost/app/assets/src/css/main/variables.scss#L39

I hope you understand my question. Looking forward to hearing from you.
Thanks :)

**Comment by thingalon** [comment]
`$jetpack-green` and `$red-50` already have the correct values in them; you should only need to change `score.scss` to use `$red-50` instead of `$color_warning`. `orange-20` is not yet defined; you will need to define that in `variables.scss` (following the existing naming conventions), and use it in `score.scss`.

Hope the explanation helps. If not, ping me on slack and we can talk it through.
