### ISSUE TITLE
Search: Improve Handling of Jetpack Disconnect 

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#20965]
### Impacted plugin

Jetpack

### What

When someone disconnects Jetpack, visiting the Search page should prompt you to connect Jetpack to enable Search.

### How

I'm not too sure what the long term plans for Search/Jetpack connections are, but currently if you disconnect Jetpack and the page refreshes, the link for Search is still available until you navigate away:

![Screen Shot on 2021-09-06 at 11:39:14](https://user-images.githubusercontent.com/33553323/132240222-7bfddb78-7210-4602-87bf-826c89083e66.png)

Clicking on the link, or otherwise visiting `*/wp-admin/admin.php?page=jetpack-search`takes you to this:

![Screen Shot on 2021-09-06 at 11:30:05](https://user-images.githubusercontent.com/33553323/132239225-58cfe0da-3619-4a4b-b548-7a0f0fedccc4.png)

It would be cool if the Search dashboard stayed and prompted you to finish connecting to Jetpack to use or provided better messaging.

Surfaced during internal testing: p8oabR-IS-p2#comment-5488

**Comment by bluefuton** [comment]
I suggested to @kangzj that we just hide the Search menu item for the moment when Jetpack is disconnected - should be fixed by #20973.
