### ISSUE TITLE
Trying to get property 'comment_type' of non-object 

### ISSUE THREAD

**Issue by cfinke** [Automattic/jetpack#20988]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Do nothing.
2. Check your error log at the end of the day and find this:

```
PHP Notice:  Trying to get property 'comment_type' of non-object in /home/[...]/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/modules/class-comments.php on line 215
```

### A clear and concise description of what you expected to happen.

I expected not to see this error.

### What actually happened

I saw this error.

### Other information

It shows up multiple times, but always at either ~8:40pm or ~11:40am.

Jetpack version 10.0, WordPress version 5.8.

### Browser

Firefox

**Comment by amustaque97** [comment]
Hi @cfinke, I would love to work on this issue. I'm not able to reproduce this error locally. I'm not getting any such warnings. I have attached a screenshot for reference.  I have built sync module as a part of the jetpack build command. I'm connected to wordpress.com also.

![Screenshot 2021-09-13 23:48:22](https://user-images.githubusercontent.com/21127788/133136091-050ba630-423a-43d3-b9bf-d1aecb1e24b4.png)

**Comment by cfinke** [comment]
I've added some debugging to my copy of Jetpack in order to grab some more data the next time it happens. When it does, I'll follow up here.

**Comment by cfinke** [comment]
The root trigger for this is Akismet calling the `deleted_comment` action without supplying the `$comment` parameter (because it doesn't have the comment object available when it deletes it).

Jetpack tries to compensate for this (because the `deleted_comment` action did not always supply a comment object) by checking if `get_comment()` returns `false`, but `get_comment()` in this scenario actually returns `null` (and I think never actually returns false). So I think the fix is just to change this line of `vendor/automattic/jetpack-sync/src/modules/class-comments.php`:

```
if ( false !== $comment && ! in_array( $comment->comment_type, $this->get_whitelisted_comment_types(), true ) ) {
```

to

```
if ( is_object( $comment ) && ! in_array( $comment->comment_type, $this->get_whitelisted_comment_types(), true ) ) {
```

You should be able to trigger this error by just calling `do_action( 'deleted_comment', $comment_id_that_doesnt_exist );`

**Comment by cfinke** [comment]
I've created a pull request (#21080) that addresses the lack of confirmation for `get_comment()`'s return value across Jetpack that would fix this issue.

**Comment by amustaque97** [comment]
👋🏻 Howdy! @cfinke  can we close this ticket? PR is merged already. Sometime it looks confusing while going through issues.

**Comment by cfinke** [comment]
Sure.
