### ISSUE TITLE
Twenty Twenty: Duplicated Social Menu locations

### ISSUE THREAD

**Issue by danieldudzic** [Automattic/jetpack#20991]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Activate Twenty Twenty
2. Select the Customizer
3. Open Menus > Locations
4. Notice duplicated Social Menu location
<img width="544" alt="Customize__This_is_a_site_title_super_long_–_This_is_a_site_description_AKA_the_tagline" src="https://user-images.githubusercontent.com/905781/132387965-99954c75-7d44-4e4c-94c7-9caaa33e5ae6.png">

### A clear and concise description of what you expected to happen.

There should be only 1 Social Menu location

### What actually happened

There are duplicated Social Menu locations

### Other information

This is caused by: https://github.com/Automattic/jetpack/blob/ba2dd6c30be137baad96aafb2466d0aed7e182e5/projects/plugins/jetpack/modules/theme-tools/compat/twentytwenty.php#L55

There doesn't seem to be a use for the Jetpack Social menu in Twenty Twenty as it registers its own Social Menu in functions.php and doesn't render Jetpack's Social menu anywhere.

I'd remove support for it in the compat file.

### Browser

Chrome/Chromium

**Comment by jeherve** [comment]
> I'd remove support for it in the compat file.

This sounds reasonable. Created #20993 for it.
