### ISSUE TITLE
CSS Media queries: `min--moz-device-pixel-ratio` instead of `-moz-min-device-pixel-ratio`

### ISSUE THREAD

**Issue by lancewillett** [Automattic/jetpack#2101]
According to [MDN](https://developer.mozilla.org/en-US/docs/CSS/Media_queries#-moz-device-pixel-ratio) specs we should not use `-moz-min-device-pixel-ratio` -- task is to replace with `min--moz-device-pixel-ratio`. (Moved from internal Trac ticket, props Jeremy Herve).

**Comment by zinigor** [comment]
Tested, looks good, no more warnings related to the `-moz-min-device-pixel-ratio` media feature name.
