### ISSUE TITLE
Block Plugins: refactor to offer control over order of Jetpack plugin sidebar panels

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#21036]
### Impacted plugin

Jetpack

### What

Block Plugins: refactor to offer control over order of Jetpack plugin sidebar panels

### How

As discussed https://github.com/Automattic/jetpack/pull/21016#issuecomment-916896465, the way the Jetpack plugin sidebar is organized is very fragile today. You do not have real control over the order of the panels in the sidebar, they're organized by the directory name of the feature.

Ideally, we would refactor this to add a priority allowing one to decide where to insert their panel.

**Comment by retrofox** [comment]
I think we should register all plugins in a single file, probably `./extensions/plugins/index.js`. Also, I wonder whether we should require all plugins from this file, too. It ends up we should remove the autoloading from the webpack config file.

**Comment by jeherve** [comment]
I like that idea, it would certainly be more flexible. It would be nice if this was also filterable, so we can interact with that list if needed.

**Comment by jeherve** [comment]
Closing as duplicate of #16877
