### ISSUE TITLE
Open Graph: add og:image:width and og:image:height Open Graph tags

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2104]
These 2 tags seem useful when pre-caching the image to be used in post previews:
https://developers.facebook.com/docs/sharing/best-practices#precaching

**Comment by twoSeats** [comment]
+1

**Comment by kraftbj** [comment]
This shouldn't be terribly difficult. `JetpackPostImages` should already be providing the `$post_image['src_width']` and `$post_image['src_height']` [example](https://github.com/Automattic/jetpack/blob/master/class.jetpack-post-images.php#L62-69) that we could use along side https://github.com/Automattic/jetpack/blob/master/functions.opengraph.php#L162 .

Need to account for the site_logo, blavatar, gravatar fallbacks, etc, but it looks like all of the data is there, need to rework it to present it and ensure we're pulling the right height/width for the right image.

**Comment by jeherve** [comment]
Reopening this, as we still need to improve `Jetpack_PostImages` to pull width and height data from images in galleries (see `from_gallery` [#](https://github.com/Automattic/jetpack/blob/master/class.jetpack-post-images.php#L84)), and from images inserted into posts without being attached to it, when possible ([#](https://github.com/Automattic/jetpack/blob/master/class.jetpack-post-images.php#L268)).
