### ISSUE TITLE
Enhancement: Include wp_ajax_* hook in Tracking package docs

### ISSUE THREAD

**Issue by kbrown9** [Automattic/jetpack#21059]
### Impacted plugin

Other

### What

The Tracking package docs should include instructions for adding the `wp_ajax_jetpack_tracks` action hook.

### How

Discussion here: p1631533812030500-slack-CBG1CP4EN.

The Jetpack plugin sets the `wp_ajax_jetpack_tracks` hook [here](https://github.com/Automattic/jetpack/blob/7d76353666972a89c43556766acb0edb739cb4ff/projects/plugins/jetpack/src/class-tracking.php#L34).

**Comment by anomiex** [comment]
Tracking package has been abandoned and merged into the Connection package. See #23448.
