### ISSUE TITLE
Boost: Enable JS linting in the Monorepo linting process

### ISSUE THREAD

**Issue by davidlonjon** [Automattic/jetpack#21066]
It seems that the Jetpack Monorepo `pre-commit` hook (and probably the GitHub actions linting process too)doing TypeScript linting on Boost file does not catch the same linting errors that using the boost local listing command (when using the linting fixes being introduced in  https://github.com/Automattic/jetpack/pull/21026).

Also Svelte linting is not enabled on the Jetpack Monorepo `pre-commit` hook  nor the GitHub actions linting process.

As a result, some changes should be done to the Jetpack Monorepo `pre-commit` hook  and the GitHub actions linting process to consistently and fully lint TypeScript and Svelte files for the jetpack Boost plugin

**Comment by jeherve** [comment]
The description is empty: I assume this is for the Boost plugin?

**Comment by davidlonjon** [comment]
> The description is empty: I assume this is for the Boost plugin? Could you add some extra details?

Ha yes sorry, I created this as a placeholder and got diverted to something else before finishing it up. I will complete the description soon.
