### ISSUE TITLE
Enhancement: Update Readme.txt and Plugin Repo Descriptions with Updated Documentation

### ISSUE THREAD

**Issue by JenSwish** [Automattic/jetpack#21081]
### Impacted plugin

Backup

### What

There are now docs for the JPBU plugin. We need to update the Readme and Plugin Repo Desc. with the updated links.

### How

Here's the readme updated with the new documentation links and some adjustments to the copy to match the documentation.

[readme_swish-edits.txt](https://github.com/Automattic/jetpack/files/7163567/readme_swish-edits.txt)

It appears that the plugin desc. is using the same content, so this should cover both.

**Comment by jeherve** [comment]
@JenSwish I opened a PR with your changes here: #21099 Let me know if this looks good!
