### ISSUE TITLE
Carousel: new gallery block format breaks carousel

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/jetpack#21097]
### Impacted plugin

Jetpack

### Steps to Reproduce

- Turn on Jetpack carousel option and the gutenberg gallery experiment (need to install latest gutenberg plugin)
- Add a gallery block with images notice the carousel is not loading as expected in frontend

### A clear and concise description of what you expected to happen.

Expected carousel to load with the new gallery block format

### What actually happened

Carousel did not load when the Gutenberg new gallery block experiment is enabled

### Operating System

macOS

### Browser

Chrome/Chromium

**Comment by sdixon194** [comment]
Hmm I can't seem to reproduce this. [The alignment works for me](https://d.pr/i/0KGRmO) on both Chrome and Firefox using Twenty Twenty One, with the Carousel module enabled on a JN site. Running latest stable and tested with master.

Were there any other conditions I might be missing that's affecting this?

**Comment by glendaviesnz** [comment]
Sorry @sdixon194 turned out the issue is with the new gutenberg gallery format in general. I will see if I can work out why this is.

**Comment by glendaviesnz** [comment]
Have started a draft pull request to fix this, just need to tidy up the [php regex that sets up the carousel data](https://github.com/Automattic/jetpack/pull/21109/files#diff-20a0b22f28fd1f2b380b5df535f70d1bd90cca42606e3ff5c7d57fba2ffcbfc2R759) though as currently a bit broken
