### ISSUE TITLE
Task: Update Google Photos logo

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#21094]
### Impacted plugin

Jetpack

### Steps to Reproduce

Let's make sure the Google Photos logos are up to date, so our app integration continues to adhere to [the UX guidelines](https://developers.google.com/photos/library/guides/ux-guidelines).

See p4hfux-5P7-p2

Within Jetpack I think we need to update two:
* https://github.com/Automattic/jetpack/blob/5f1b0ea6fb37fe59d520f1202a950fe2f8c37aca/projects/plugins/jetpack/extensions/shared/icons.js#L27-L30
* https://github.com/Automattic/jetpack/blob/5f1b0ea6fb37fe59d520f1202a950fe2f8c37aca/projects/plugins/jetpack/extensions/shared/icons.js#L40-L88

They are used in the Select Image button and in the external media modal:
<img width="637" alt="Screen Shot 2021-09-14 at 2 29 50 PM" src="https://user-images.githubusercontent.com/1398304/133336674-2d42d9aa-c9f8-4458-83bc-5708be7b5b0f.png">

<img width="1321" alt="Screen Shot 2021-09-14 at 2 30 04 PM" src="https://user-images.githubusercontent.com/1398304/133336689-9120f0dc-0bf0-4296-9836-20618bd77473.png">

### Browser

Chrome/Chromium, Firefox, Microsoft Edge, Microsoft Edge (legacy), Safari

**Comment by obenland** [comment]
@olaolusoga Could I ask for our help with sourcing these new logos?

**Comment by simison** [comment]
> help with sourcing these new logos?

They have [resource center](https://about.google/brand-resource-center/) but [press material](https://www.blog.google/press/) page still has their old logo. New 2020 logo is visible [on the list](https://about.google/brand-resource-center/logos-list/) but no download. Wikimedia [has the color SVG though](https://commons.wikimedia.org/wiki/File:Google_Photos_icon_(2020).svg).

Might be worth asking directly with the email too.

**Comment by mreishus** [comment]
Created PR: #21106
