### ISSUE TITLE
Publicize: refresh connections once post saves

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#21169]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Create a new post
2. Open the Jetpack sidebar
3. Add social media connections
4. Enable some connections to share the post
5. Publish the post

### A clear and concise description of what you expected to happen.

Get the connections list updated, disabling the connection used to share the post.

### What actually happened

The connections list doesn't show any change. You need to do a hard refresh to get it updated.

### Operating System

macOS

### Browser

Chrome/Chromium

**Comment by tameryldz** [comment]
#9919
