### ISSUE TITLE
Package version tracker: conflicts with third-party plugins

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#21165]
This issue is triggered when using a third-party plugin, Passwords Evolved ([W.org](https://wordpress.org/plugins/passwords-evolved/) / [GitHub](https://github.com/carlalexander/passwords-evolved/)).

#### Steps to reproduce

* On a brand new site, install the Passwords Evolved plugin.
* Then, install, activate, and connect [Jetpack version 10.0](https://downloads.wordpress.org/plugin/jetpack.10.0.zip).
* Then, update from version 10.0 to 10.1.

You'll notice the following fatal on all pages from that point on:

```
PHP Fatal error:  Uncaught InvalidArgumentException: Container doesn't have a value stored for the "password.generator" key. in /wp-content/plugins/passwords-evolved/src/DependencyInjection/Container.php:94
Stack trace:
#0 /wp-content/plugins/passwords-evolved/src/Plugin.php(79): PasswordsEvolved\DependencyInjection\Container->offsetGet('password.genera...')
#1 /wp-content/plugins/passwords-evolved/pluggable.php(60): PasswordsEvolved\Plugin->get_password_generator()
#2 /wp-content/plugins/jetpack/vendor/automattic/jetpack-connection/src/class-client.php(109): wp_generate_password(10, false)
#3 /wp-content/plugins/jetpack/vendor/automattic/jetpack-connection/src/class-client.php(26): Automattic\Jetpack\Connection\Client::build_signed_request(Array, '{"package_versi...')
#4 /srv/users/user6dae in /wp-content/plugins/passwords-evolved/src/DependencyInjection/Container.php on line 94
```

References:

- https://github.com/carlalexander/passwords-evolved/blob/51451a3256b218be692bdcaf415b3a6fd7c35d93/src/Plugin.php#L79
- https://github.com/carlalexander/passwords-evolved/blob/51451a3256b218be692bdcaf415b3a6fd7c35d93/pluggable.php#L55
- https://github.com/Automattic/jetpack/blob/4ae507f6be6b83e7f96a5c7acb51c05b19609d79/projects/packages/connection/src/class-client.php#L109
- https://github.com/Automattic/jetpack/blob/4ae507f6be6b83e7f96a5c7acb51c05b19609d79/projects/packages/connection/src/class-client.php#L26
- https://github.com/carlalexander/passwords-evolved/blob/51451a3256b218be692bdcaf415b3a6fd7c35d93/src/DependencyInjection/Container.php#L91

This tracks back to the requests we added in #20365. @kbrown9 Do you think you could take a look?

Thank you!

********

Originally reported here:

- https://wordpress.org/support/topic/fatal-error-after-jetpack-update/

**Comment by kbrown9** [comment]
Thanks for digging into this issue, @jeherve!

It looks like Passwords Evolved sets the `password.generator` key during the `after_setup_theme` [action](https://github.com/carlalexander/passwords-evolved/blob/51451a3256b218be692bdcaf415b3a6fd7c35d93/passwords-evolved.php#L35), but the Package Version Tracker is sending the request before that action fires. I think I can just hook the request to a later action to resolve this error.
