### ISSUE TITLE
Custom CSS: 404 for blank.css in console when Mode: Replacement active

### ISSUE THREAD

**Issue by allendav** [Automattic/jetpack#2118]
Logged out users will get a 404 on the front side for http://{$domain}/wp-content/plugins/jetpack/modules/custom-css/custom-css/blank.css 

This apparently happens when Mode: **Replacement** is active in http://{$domain}/wp-admin/themes.php?page=editcss#settingsdiv

In some situations, it is necessary to be a logged out user to see it, but on other sites it happens repeatedly.

**Comment by dereksmart** [comment]
This was fixed in c2b5286b80efa4a413ef9a0ef128471de19327e1
