### ISSUE TITLE
Subscription Block: add setting for success message

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#21187]
### Impacted plugin

Jetpack

### What

Add setting to block just like it exists for the widget

### How

The Subscription includes a `success_message` setting that can be customized via the Widget settings. It would be nice if that setting existed for the block as well.

**Comment by amustaque97** [comment]
@jeherve, I would love to work on this issue. Would please share some ideas on how to implement it? If you have some thoughts, inputs or any resources if handy. Or no worries I will figure it out on my own.

**Comment by jeherve** [comment]
@amustaque97 If you're interested in giving this a try, I would recommend that you take a look at past work on the Subscriptions block, like in #15107, to see how we tie existing Subscription feature options (such as the success message widget / shortcode option from `projects/plugins/jetpack/modules/subscriptions/views.php`) to new block attributes.
