### ISSUE TITLE
i18n: Missing translations due to unextractable strings from output JS files

### ISSUE THREAD

**Issue by yuliyan** [Automattic/jetpack#21204]
### Impacted plugin

Jetpack

### Steps to Reproduce

* Inspect the output JS files of v10.0 and v10.1 (e.g. `_inc/blocks/editor.min.js`).
* Translatable strings in the latter no longer have the gettext function name (`__`) preserved in the output bundle files.

### A clear and concise description of what you expected to happen.

Functions name of translatable strings, i.e. gettext `__()` calls, are no longer preserved in the output JS bundles. That causes the strings to no longer be extracted on the plugin directory, since the string extraction process is looking specifically for `__()` function calls in the plugin files. As a result:

* Strings that were previously extracted and translated in GlotPress, became obsolete.
* Language packs for JS files with renamed gettext calls are no longer being generated.

### Other information

There's a babel plugin workaround in `@automattic/calypso-build` - https://github.com/Automattic/wp-calypso/pull/49341.

**Comment by anomiex** [comment]
> There's a babel plugin workaround in `@automattic/calypso-build` - [Automattic/wp-calypso#49341](https://github.com/Automattic/wp-calypso/pull/49341).

That plugin is already in use in the Jetpack build, but seems to not be having the intended effect.

**Comment by anomiex** [comment]
In fact, if I comment out the line loading it in `node_modules/@automattic/calypso-build/babel/default.js` and rebuild, `wp i18n make-pot` starts detecting the strings again.

**Comment by yuliyan** [comment]
> That plugin is already in use in the Jetpack build, but seems to not be having the intended effect.

@anomiex, I think it needs the `concatenateModules` optimization disabled as it is applied for some packages in the linked PR (Automattic/wp-calypso#49341.), i.e.

```
optimization: {
	...webpackConfig.optimization,
	// disable module concatenation so that instances of `__()` are not renamed
	concatenateModules: false,
},
```

**Comment by anomiex** [comment]
Odd that calypso-build doesn't actually set that then. Or maybe not so odd in light of the conversation at https://github.com/Automattic/jetpack/pull/21004#issuecomment-920344436.
