### ISSUE TITLE
customize related posts with shortcode

### ISSUE THREAD

**Issue by ghost** [Automattic/jetpack#2126]
Hi, 
I'm a newbie at this and apologize if this seems redundant and annoying, but i need assistance in customizing related posts on a website, in case it is possible.
what i'm trying to do is customize related posts to work in different categories which correspond to specific pages, so posts with category x1 would appear on a page called x1. 

1) Is this possible through categories, or would i have to use types?  
2) is this possible through shortcodes on the specific pages, or would i have to add the code to the page template? (while the page template is shared by all the pages) 

many thanks for any response or referral.

**Comment by jeherve** [comment]
I'd suggest going through the code snippets we posted here:
http://jetpack.me/support/related-posts/customize-related-posts/

That should help you customize Related Posts to fit your needs. You'll probably need to make use of different [conditional tags](https://codex.wordpress.org/Conditional_Tags) to customize the snippets to your liking.

If there are things you still don't manage to do thanks to the snippets, [send us an email](http://jetpack.me/contact-support/) with more details about your site and we'll help!
