### ISSUE TITLE
WordPress.com Toolbar: Menu links not updating in Firefox

### ISSUE THREAD

**Issue by allilevine** [Automattic/jetpack#21285]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. In Firefox, go to wordpress.com/posts/ for a Simple site and open the Screen Options menu in the upper right. Switch to Classic View.
2. Switch back to Default view.
3. Navigate away from the posts page
4. Navigate back to the Posts page using the unified nav

### A clear and concise description of what you expected to happen.

The Posts menu item should open wordpress.com/posts like it does in Chrome.

### What actually happened

The Posts menu item opens wp-admin / the classic view: https://d.pr/v/zAnrc4

### Other information

See:
- https://github.com/Automattic/jetpack/blob/859f401da5a8aa54103c22a335018bd662ccdbc7/projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js#L89
- https://github.com/Automattic/jetpack/blob/859f401da5a8aa54103c22a335018bd662ccdbc7/projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php#L656

Reported here: p1633373344203400-slack-C01VDMPHG69

### Operating System

macOS

### OS Version

10.15.7

### Browser

Firefox

### Browser Version(s)

93

**Comment by amustaque97** [comment]
:wave: @allilevine, I would love to work on this issue. I went through the recording and will reproduce it locally. I will update you soon with my findings or fixes.

**Comment by allilevine** [comment]
> 👋 @allilevine, I would love to work on this issue. I went through the recording and will reproduce it locally. I will update you soon with my findings or fixes.

Thanks @amustaque97! I'm not sure this bug can be reproduced / fixed without access to internal development environments, but you're welcome to try if you see a solution. 🙌
