### ISSUE TITLE
Beta: Auto-build asset for the release

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#21315]
### Impacted plugin

Beta

### What

Auto-create the asset when creating a new release

### How

For the Jetpack Beta plugin, since it is not distributed via w.org, we have to do some extra work to get it right.

* Tagging the release in the mirror repo (as usual)
* Download a copy of the tagged version, rename the directory to `jetpack-beta`, zip it as `jetpack-beta.zip` and add that to the GitHub Release.

Additionally, OS X is stupid and adds `__MACOSX` folders to zip files, which are annoying to people using a real OS (say, Linux). An automated process wouldn't include anyone needing to zip on their local machines thus removing those folders whenever us on Macs compress via UI.

Let's not have this happen again: p1633554274025400-slack-C7YPW6K40

**Comment by jeherve** [comment]
> Does that also require the same specific structure for the zip file, i.e. it has to be named "jetpack.zip" and contain the folder named as "jetpack" (rather than "jetpack-production-10.2.zip" with a folder named "jetpack-production-10.2" that GitHub already auto-generates)?

Right, exactly.

**Comment by kraftbj** [comment]
> The correct instructions should already be at https://github.com/Automattic/jetpack-beta/#deployment (in the README.md). That seems to me like a good canonical place for them.

Makes sense. When I was looking yesterday, I started in the FG which took me to the outdated wiki. I deleted the wiki content and updated the FG to point to the README.md file.
