### ISSUE TITLE
Subscriptions: Searching through the subscribers doesn't work

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#2132]
If you try to use the search box in your email subscribers ( wp-admin/admin.php?page=stats&blog_subscribers&type=email ), any search simply refreshes the page. Likely the same cause as 4652-wpcom internal Trac ticket.

**Comment by richardmtl** [comment]
This came up again in 2294002-t ; maybe we should remove the search box since it doesn't work?

**Comment by kraftbj** [comment]
:+1: for hiding it (just a `display:none` in CSS or commenting out the form) for now until it has time to be investigated. Marking for 3.7 to hide for now. We should include a link back to this in the code so we know why it is commented out. :)

**Comment by dereksmart** [comment]
Since we're pulling this content in from dotcom, the search is going to be a little tricky.  It works over there though, so I've committed r123044-wpcom that will only hide it for Jetpack sites.  

Leaving this an open to avoid "out of sight, out of mind" - should be fixed properly in the future.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed. Most of our effort goes into the list on WordPress.com now:
https://wordpress.com/people/followers/
