### ISSUE TITLE
Blocks: i18n: Translatable strings from *.min.js

### ISSUE THREAD

**Issue by yuliyan** [Automattic/jetpack#21343]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Download Jetpack from https://wordpress.org/plugins/jetpack/
2. Run `wp i18n make-pot .`
3. Inspect the generated POT file to confirm translatable strings from `*.min.js` files are missing.
4. Remove the `.min` suffix from the filename of any of the JS files that contain translatable strings (e.g. `_inc/blocks/editor.min.js`) and run `wp i18n make-pot .` again.
5. Inspect the generated POT file and confirm the strings from that file are now included in the POT.

### A clear and concise description of what you expected to happen.

AFAIK, the plugin directory is using the same (or pretty similar) approach to `wp i18n make-pot .` to generate POT file for a plugin and import into its translate.wordpress.org project. By default, the `make-pot` command excludes some files and directories from scanning, including `*.min.js` files.
As a result:
* Strings referenced only in such JS files that were previously extracted and translated on translate.wordpress.org, became obsolete.
* Language files for `.min.js` are no longer being generated, because none of the strings have reference to such file.

### Other information

`.min` suffix introduced in: https://github.com/Automattic/jetpack/commit/be80d269a407518138060e8417c522e051d58b9a
Related issue: https://github.com/Automattic/jetpack/issues/21204

**Comment by kraftbj** [comment]
Noting that we switched to the .min.js file extension to prevent the built files from being handled by wp.com's JS minimization script, which started breaking when we dropped IE 11 (thus output into more modern JS).

**Comment by kraftbj** [comment]
This is apparently expected behavior for the make-pot CLI command:
> [--exclude=<paths>]
[...] The following files and folders are always excluded: node_modules, .git, .svn, .CVS, .hg, vendor, *.min.js.

from https://developer.wordpress.org/cli/commands/i18n/make-pot/

I have in my mind that we checked GlotPress and confirmed the strings were there? If so, make-pot isn't the issue (I wouldn't think). If not, then we need to figure out something—either via make-pot or Systems re the wp.com need for .min.js that pushed us this way.

**Comment by kraftbj** [comment]
Confirm, the latter wouldn't happen. I'd not want to ship too much extra to sites in the plugin upgrade routine.

**Comment by yuliyan** [comment]
Do you have any update on this issue?

**Comment by jeherve** [comment]
@yuliyan We've been discussing potential solutions here:
p9dueE-3Gb-p2

We'd be happy to have you chime in on that discussion!

**Comment by anomiex** [comment]
I think that #21748 fixed this entirely after all. As far as I can tell none of the files that were being processed by gulp use `@wordpress/i18n` (and now we've switched them to being processed by Webpack anyway).
