### ISSUE TITLE
Tiled Galleries: Add filter to modify gallery links

### ISSUE THREAD

**Issue by RCowles** [Automattic/jetpack#2134]
We've received a request in #2184208-t to modify the markup for Tiled Galleries. The user would like to use a third party jQuery lightbox plugin which requires a specific `rel` attribute on the thumbnail links. It looks like we could add a filter on L4 in `modules/tiled-gallery/tiled-gallery/templates/partials/item.php` which would allow for this.

**Comment by richardmtl** [comment]
requested in 2266133-t

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
