### ISSUE TITLE
jetpack_client_id is exposed even if the site is disconnected

### ISSUE THREAD

**Issue by koke** [Automattic/jetpack#2137]
I have a site that's not connected to WordPress.com (although it has been), and calling `wp.getOptions` includes `jetpack_client_id`

```xml
...
  <member><name>jetpack_client_id</name><value><struct>
  <member><name>desc</name><value><string>El identificador de cliente/ ID de blog de WP.com de este sitio</string></value></member>
  <member><name>readonly</name><value><boolean>1</boolean></value></member>
  <member><name>value</name><value><int>80608379</int></value></member>
</struct></value></member>
...
```

**Comment by attritionorg** [comment]
Is the jetpack_client_id considered privileged information? e.g. Is this like a username enumeration bug, where you are getting half of a set of credentials?

**Comment by koke** [comment]
I don't think so, you can get the ID from the HTML source if you have stats enabled.

The problem here is that if the site is disconnected it shouldn't have a blog ID. I understand Jetpack doesn't delete it so it can reuse the ID (and keep stats) if the user connects again, but to the apps it should appear as if it was never connected.
