### ISSUE TITLE
Boost: Add consolation note regarding js errors during critical CSS gen.

### ISSUE THREAD

**Issue by eAdnan007** [Automattic/jetpack#21370]
When generating critical CSS. Often, the browser complains about blocked JS execution.

JS execution is not important and we can ignore that during critical CSS generation. However, the user might still find it frustrating and may think something is broken.

So, the idea is to put on a consolation note before the errors would start showing up. This can be something similar to the self xss warning facebook places on browser console.

Message we discussed about placing: "Generating Critical CSS will often leave errors in your console. Most of them are nothing to worry about - just the sounds of your browser complaining about our strict security settings. Check out the following page for more information: [link to a page on jetpack.com which explains which errors are fine to ignore]”

Related support topic: https://wordpress.org/support/topic/blocked-script-execution/

Discussion: p1634020657012900-slack-C0232B8CUHG

**Comment by thingalon** [comment]
We're still getting nudges from users about this. We should prioritize getting it done.
