### ISSUE TITLE
Subscriptions: allow for comment subscription without commenting

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#214]
It would be nice to allow readers to subscribe to comments without commenting.

Suggested here:
- http://wordpress.org/support/topic/why-cant-a-reader-subscribe-to-comments-without-also-commenting?replies=1

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by lschuyler** [comment]
Requested in 3298830-t
