### ISSUE TITLE
PHP Warning reading property related to comment type

### ISSUE THREAD

**Issue by muffinpeace** [Automattic/jetpack#21416]
### Impacted plugin

Jetpack

### Steps to Reproduce

Since migration to PHP 8, customer reported they were getingt this error very frequently :

`
[13-Oct-2021 02:10:17 UTC] PHP Warning: Attempt to read property “comment_type” on null in /srv/data/web/vhosts/blog.gowa.fr/htdocs/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/modules/class-comments.php on line 217`

They've initially had a sync issue that we've fixed.

### Other information

Thread: https://wordpress.org/support/topic/php-8-error-comment_type-property/

p1634216009147400-slack-C8BEWD4QM

### Browser

Other / Not applicable

**Comment by amustaque97** [comment]
I believe this issue will be fixed as soon as https://github.com/Automattic/jetpack/pull/21080 gets merged into master. 
cc @jeherve @muffinpeace
