### ISSUE TITLE
Contact Form: add Jetpack CRM install link 

### ISSUE THREAD

**Issue by tbradsha** [Automattic/jetpack#21439]
### Impacted plugin

Jetpack

### What

We would like users to be able to install Jetpack CRM via the Contact Form block

### How

Currently the block's integration with Jetpack CRM detects various states of the plugin (see #17257). However, it'd be great if it were seamless like the current Newsletter integration:

![image](https://user-images.githubusercontent.com/32492176/137541643-7c2ece97-db85-496e-a85d-e50a3c361e96.png)

**Comment by tbradsha** [comment]
@kbrown9: FYI, as of JPCRM 4.9 one can defer the welcome wizard by setting a `jpcrm_defer_wizard` transient. :^)

**Comment by kbrown9** [comment]
Reopening because we still need to add the install link to the contact form.

**Comment by tbradsha** [comment]
As of JPCRM 4.9.1, we've implemented an even better solution that no longer requires a transient, since the wizard will not show on AJAX requests and will only show on the initial load of a JPCRM admin page.

All that to say: adding the install/activate buttons should now work cleanly. Upon activation, I'd suggest including a link to "manage" CRM that points to `/wp-admin/admin.php?page=zerobscrm-dash`.

**Comment by cleacos** [comment]
It would be great if we can include this one in the next Jetpack version (10.8) since the plugin installation/activation is already working well via API for any CTA (pushing cross-selling!!). Thanks!

cc: @kbrown9 @jeherve

**Comment by cleacos** [comment]
More info: 

- Reintroducing the CTA button in AaG section: https://github.com/Automattic/jetpack/pull/22957
- Original CTA implementation for the AaG section: https://github.com/Automattic/jetpack/pull/21866 using the API method `installPlugin`
