### ISSUE TITLE
Widget Visibility Doesn't Work in Customizer

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#21446]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Turn on Widget Visibility module in Jetpack
2. Add widgets with conditions to restrict their visibility
3. Changes are not reflected in Customizer preview

### A clear and concise description of what you expected to happen.

The Customizer view should reflect what shows on the front-end of the site. 

### What actually happened

At present, widgets show in Customizer regardless of the visibility conditions you setup. By contrast, if you go to the actual site you will see a different view depending on how you have configured the Widget Visibility.

For example, a widget set to display only on the "blog" page will show everwhere in Customizer, while on the frontend it will show only when the criteria is met.

### Other information

Possibly related to:

* Automattic/jetpack/pull/20255

First reported here:

* Automattic/jpop-issues/issues/7024
* https://wordpress.org/support/topic/widgets-visibility-on-customizer/?view=all

### Operating System

macOS

### Browser

Firefox

### Browser Version(s)

v93

**Comment by ParhamG** [comment]
We are experiencing the same issue that the visibility settings are ignored in the customizer preview. I see there is already a pending PR to fix this, is there an update on when that will be released?

**Comment by jeherve** [comment]
@ParhamG We're still working on that fix, so I'm afraid we cannot give you an ETA at the moment.

**Comment by Gustavo-Hilario** [comment]
This issue also reported here: 4442118-zd-woothemes
