### ISSUE TITLE
Jetpack Protect: enhance lockout UX

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#2147]
When an user gets locked out of their site and they see this:

![screen shot 2015-05-19 at 4 38 14 pm](https://cloud.githubusercontent.com/assets/2694219/7713411/93e85996-fe45-11e4-84f3-ed82c7005d69.png)

"Find out more" takes them to http://jetpack.me/support/security-features/

Since the security settings page on wordpress.com has been improved, we should definitley provide a link to https://wordpress.com/settings/security/%site%

And maybe improve the styles

**Comment by samhotchkiss** [comment]
Pinging you on Slack...

**Comment by roccotripaldi** [comment]
Per a slack conversation, we've decided to take an other approach.
When someone gets locked out, instead of seeing that screen, they will have an opportunity to enter a captcha which will give them more chances to login without being locked out.

**Comment by roccotripaldi** [comment]
@samhotchkiss is working on the captcha. there is not currently a PR to reference.

**Comment by richardmtl** [comment]
I think the PR in question is https://github.com/Automattic/jetpack/pull/2282
