### ISSUE TITLE
Old module page unavailable

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#21490]
### Impacted plugin

Jetpack

### Steps to Reproduce

Customer has noted on this point that they can’t access the Jetpack Modules page of sites when it isn’t connected to Jetpack with this version, but previously could with older version: wp-admin/admin.php?page=jetpack_modules

If they set JETPACK_DEV_DEBUG, they can then get to the page above.

### Other information

Internal reference: pbfA90-jV-p2

### Browser

Other / Not applicable

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
