### ISSUE TITLE
Comments need better RTL support

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#215]
There are a few elements in the Comments that aren't properly aligned for RTL:

![screen shot 2014-02-14 at 10 26 01](https://f.cloud.github.com/assets/3676359/2172034/426ffee2-958d-11e3-8253-ac60f0a4e886.png)

In the original Trac ticket: https://plugins.trac.wordpress.org/ticket/1924 the reporter supplied a CSS file and a modified comments.php ; however, as mentioned in that ticket, and according to the reporter,

> In order to fix this, the site must add a parameter to the iFrame content's url indicating whether the site is an RTL site, and if it is, the server on wp.com's end must add a stylesheet that loads after the main stylesheet that corrects the layout for RTL.

**Comment by enejb** [comment]
Updated .com to fix this issue.
