### ISSUE TITLE
Status: update staging checks to support newer WPEngine staging environments

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#21504]
### Impacted plugin

Jetpack

### Steps to Reproduce

Jetpack's default staging setup includes checks to detect WPEngine staging sites:

https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/packages/status/tests/php/test-status.php#L356-L359
https://github.com/Automattic/jetpack/blob/3e14492ded4e756ad0b7824ad31759999171da43/projects/packages/status/src/class-status.php#L192

However, those only account for one type of staging site. WPEngine now includes 2 types of staging environments. As per [their support documentation](https://wpengine.com/support/staging-environments-1-click-staging-different/):

> Legacy 1-Click Staging vs Staging/Development Environments

  | Legacy 1-Click Staging | Staging Environments
-- | -- | --
URL Structure | environment.staging.wpengine.com | environment.wpengine.com
| |  ✅ (supported by Jetpack) | 🔴 (not supported by Jetpack)

We'll need to update Jetpack to support this.

### Other information

Internal reference: 7037-gh-jpop-issues

Reported here:

- https://wordpress.org/support/topic/jetpack-is-going-safemode-on-prod-site-after-copying-site-to-staging/
- 4389012-zen

**Comment by muffinpeace** [comment]
It seems that this could happen often, especially when the Legacy 1-Click Staging feature retires in a couple of months. I am adding the link to a forum thread we've received from a customer: https://wordpress.org/support/topic/safe-mode-disconnected-wrong-site/

**Comment by osmanishahela** [comment]
Our user encountered a similar issue, The user wants to reestablish Jetpack Connection on the production site https://lawfirmanywhere.com/
The Jetpack is now active on the staging site https://lfawstg.wpengine.com/
The Safe Mode prompt appeared on the live site instead of the staging site (https://lfawstg.wpengine.com/), so Jetpack now points to that one. Zendesk Ticket #4677396-zen

**Comment by muffinpeace** [comment]
Another case on the forums: https://wordpress.org/support/topic/trouble-entering-safe-mode/

**Comment by muffinpeace** [comment]
Another case on 5182612-zen.

**Comment by kraftbj** [comment]
WP Engine's new staging environment doesn't seem to have an obvious way to detect it. I've started a conversation with their technical team to determine if there's a way (or if one could be added) to detect their production vs staging vs development envs.

**Comment by kraftbj** [comment]
WP Engine does not have a way to detect this that is reasonable for us. It is planned but on hold. 

The suggestion they offer is to interface with their API, requiring user credentials and all that comes with that. 

Open to hearing other opinions but to me, this would become an overengineered solution for a single host. The time should be, instead, spent on making the hosting agonistic experience better instead.
