### ISSUE TITLE
Boost: Critical CSS prevents any stylesheets from loading when Javascript is disabled

### ISSUE THREAD

**Issue by cbirdsong** [Automattic/jetpack#21545]
### Impacted plugin

Boost

### Steps to Reproduce

1. Enable Critical CSS
2. Disable Javascript[^1]
3. Load a page

[^1]: [This extension](https://github.com/dpacassi/disable-javascript) is a handy way to do this without rendering your entire browser Javascript-less.

### A clear and concise description of what you expected to happen.

All the CSS files to load.

### What actually happened

The only CSS active on the page is Jetpack's inlined critical CSS.

### Other information

The ideal behavior would be if unmodified versions of the `<link rel="stylesheet">` tags were output inside a `<noscript>` tag.

**Comment by thingalon** [comment]
@davidlonjon would you be able to explore some potential solutions to this? I think we can say "wontfix" if it's not really fixable, but if it's as easy as adding styles into the header inside a `<noscript>` tag, it might be fixable.

It's been a long time since I played with `noscript`.

**Comment by cbirdsong** [comment]
The quick test of `<link>` tags inside of a `<noscript>` worked fine in my local test environment, but I was just manually linking the files – I don't know how easily it can integrate with the whole `wp_enqueue_style` system.

**Comment by davidlonjon** [comment]
Thank you for the report and the feedback @cbirdsong. I will start looking into it in more detail.

**Comment by davidlonjon** [comment]
Hi @cbirdsong, I have now fixed the issue in this [PR](https://github.com/Automattic/jetpack/pull/21713/files). Hopefully, this fix should be released soon with Boost v.1.3.1. We expect the release to happen next week. In the meantime, if you want to can try to apply the fix from the PR yourself and let me know if this is also good from your point of view.

**Comment by cbirdsong** [comment]
I likely won't get a chance to check it out until then, but I'll keep an eye out for an update! 👍
