### ISSUE TITLE
Boost: Critical CSS does not respect existing media attributes

### ISSUE THREAD

**Issue by cbirdsong** [Automattic/jetpack#21544]
### Impacted plugin

Boost

### Steps to Reproduce

1. Register/enqueue a stylesheet with a media parameter other than `all` or `print`. (I used `screen`)
2. Enable Critical CSS
3. Load a page

### A clear and concise description of what you expected to happen.

The stylesheet would have the specified media attribute.

### What actually happened

The stylesheet has `media="all"`.

### Other information

This bug totally breaks the "[Cutting the Mustard](https://www.sitepoint.com/cutting-the-mustard-with-css-media-queries/)" technique for progressive enhancement.

**Comment by davidlonjon** [comment]
Hi @cbirdsong, just to let you know that my colleague @karthikax has worked on a [fix](https://github.com/Automattic/jetpack/pull/21665/files) that will solve this issue. It will be bundled within Jetpack Boost v1.3.1 imminent release.

I'll close this issue once the release is done.

**Comment by davidlonjon** [comment]
@cbirdsong Jetpack Boost v1.3.1 has now been released. I will close this issue but feel to provide feedback if you are still experiencing the issue.

**Comment by cbirdsong** [comment]
This looks good! Thanks!
