### ISSUE TITLE
Stats: remove Video Stats card from wp-admin stats when VideoPress is disabled

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#21586]
#### Steps to reproduce

1. Activate the Stats module on your site.
2. Go to Jetpack > Site Stats
3. You'll a video stats card, even though VideoPress is not active on your site.

![stats-video](https://user-images.githubusercontent.com/426388/139426212-41301dd8-d6fb-4e2f-a813-629b3e03678f.png)

- Related: #960 
- Reported: p8oabR-K9-p2#comment-5569

**Comment by amustaque97** [comment]
@jeherve, can I take a look at this if it can be fixed by community? Do you want to share some pointers?
Thank you :)

**Comment by jeherve** [comment]
> can I take a look at this if it can be fixed by community?

I'm afraid that's something we'll need to fix on our end, as the stats are loaded from WordPress.com directly.

**Comment by jeherve** [comment]
I'll close this as duplicate of #11983.
