### ISSUE TITLE
Short URL WP.me doesn't include page break

### ISSUE THREAD

**Issue by odie2** [Automattic/jetpack#2158]
Hello,

I have post with following URL:
`http://zschocianow.nazwa.pl/wordpress/ix-chocianowski-festiwal-futsalu/2/`
where `/2/` is second page (of 4).

I am using WP.me feature to link and also create QR code in footer by `wp_get_shortlink()`.
However, when I am on second page, shortcode pointing to `http://zschocianow.nazwa.pl/wordpress/ix-chocianowski-festiwal-futsalu/` instead.

I am using manual post breaking for categorize for example futball event to intro, girls, boys and institutions.

Greetings

**Comment by kraftbj** [comment]
Thanks for the suggestion. The way wp.me shortlinks work as based on the post ID and the blog ID, so adding something like this would not be trivial. 

I'm going to close this as wontfix as it is not something we'll tackle anytime in the near future. If others would like to see this feature, please do leave comments.
