### ISSUE TITLE
Programmatic Authentication Functionality Outside Multisite

### ISSUE THREAD

**Issue by logoscreative** [Automattic/jetpack#2160]
It would be highly useful to be able to access the one-user-many-sites authentication pattern available to Multisite users *outside* of a Multisite installation.

Having one user (and adding sites via API or something of the sort) would allow us to offer Jetpack in a multitenant environment where customers may not wish to create a new WP.com account, but could benefit from the features requiring authentication.

We could define our user token in a mu-plugin or in a given site's config file. We could also handle an authentication process and store the blog ID if needed, if it would simply return that from an endpoint after sending a user token and URL.

We would love to offer full Jetpack functionality, but the inability to programmatically authenticate people keeps us from being able to do it. I'd love to see this change. :)

**Comment by kraftbj** [comment]
Thanks for the report. Currently, a super admin can authenticate any subsites via Network Admin->Jetpack->Sites and some of the functionality built into that may be able to be leveraged.

`do_subsiteregister` is a `public` function. @georgestephanis is that stable enough to use in a situation like this?

**Comment by logoscreative** [comment]
@kraftbj Edited. Sorry, couldn't figure out how to edit that from my phone. :)

**Comment by jeherve** [comment]
I like the idea. I don't know how we could do that, but ideally I would like seeing a solution using the API Key already in use with Akismet. If the API key can be found, the authentication process would be simpler and not require a WordPress.com connection.

**Comment by logoscreative** [comment]
Now that Jetpack is literally forcing me to use it (and not BruteProtect, which I was peacefully and happily using before), this has become a must. Please let me know what I can do.

**Comment by kraftbj** [comment]
I don't foresee this as something we'll look to do in the near future. The WP.com connection is pretty key to the process and authenticating a wp.com account to a new site without explicit permission will likely be problematic in various ways. I'm going to close this as a wontfix for the time being.

**Comment by logoscreative** [comment]
Can I get a better explanation for closing this, please? The whole point of the request is that forcing explicit authentication is _already_ problematic for people. Plus, connection with WP.com is not needed to many features, so this would allow people to adopt Jetpack is different scenarios. 

This is a serious blocker in many cases. Please reconsider making this more flexible for all the other use cases that exist, especially if Jetpack is going to continue to eat other useful plugins and force adoption.

**Comment by kraftbj** [comment]
This isn't something that we are looking to work on for the foreseeable future. The idea has merit, is interesting, and I could see us looking more into it at some point in the far future.

That said, we don't want to string you or anyone along thinking we may tackle it anytime soon. Depending on your exact needs, there may be other solutions already in place, notably using development mode or filtering the available modules to give you all of the features available without a dotcom connection.
