### ISSUE TITLE
Enhancement: Support TLS 1.3 Jetpack connections

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/jetpack#21609]
### Impacted plugin

Jetpack

### What

Currently, WordPress.com supports up to TLS 1.2 when connecting to any sites. Jetpack/WordPress.com should support sites that run on minimum TLS 1.3 for updated security.

**Comment by jeherve** [comment]
Jetpack should support TLS 1.3 already. You can find out more about this here: pMz3w-cCM-p2
