### ISSUE TITLE
Custom CSS: Additional CSS is being HTML encoded in multisite

### ISSUE THREAD

**Issue by CdrMarks** [Automattic/jetpack#21603]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. On a multisite as the Administrator role
2. Go to Customizer > Additional CSS
3. Enter CSS that includes a `>`, for example:
```
/* Page width code*/
.entry-content > :not(.alignwide):not(.alignfull):not(.alignleft):not(.alignright):not(.is-style-wide) {
	max-width: 960px;
}
```
4. Publish the changes.
5. Browse to the / page of the site
5. View the the CSS source
6. See that the `>` has become HTML encoded:
```
/* Page width code*/
.entry-content &gt; :not(.alignwide):not(.alignfull):not(.alignleft):not(.alignright):not(.is-style-wide) {
	max-width: 960px;
}
```

### A clear and concise description of what you expected to happen.

The `>` in the CSS should remain a greater than symbol.

### What actually happened

The `>` in the CSS should became HTML encoded `&gt;`

### Other information

Found and initially reported at https://wordpress.slack.com/archives/C08M59V3P/p1635532931013500 in #meta-wordcamp.

Affects the wordcamp.org and make.wordpress.org networks.

### Browser

Chrome/Chromium

**Comment by jeherve** [comment]
Closing this as Jetpack's Custom CSS feature is no longer available on self-hosted sites ; it's been replaced with Core's Additional CSS feature.
