### ISSUE TITLE
Add Contact Form Button to Menu Bar in Mobile 

### ISSUE THREAD

**Issue by mrmccarrin** [Automattic/jetpack#2162]
Hi, 
I have removed the search box from my menu bar in jetpack mobile, but left the dropdown menu there. I would like to put a button in the menu bar (where the search used to be) that would open a dropdown contact form.  I have been told this is not currently possible, but I could suggest it here.  Please let me know if this can be developed? 

Just in case you need it. my site is http://www.pearsonkoutcherlaw.com

Thanks!

Megan

**Comment by jeherve** [comment]
Related: #102

**Comment by jeherve** [comment]
It's indeed not easily doable, because you can't insert the contact form into a custom theme template as mentioned in #102. 

I'd suggest that you subscribe to that issue; as soon as it is fixed, you will be able to use `do_shortcode` to insert a contact form wherever you wish in your theme.
