### ISSUE TITLE
Publicize is posting article excerpts to Facebook instead of "Custom Message"

### ISSUE THREAD

**Issue by ChrisBegley** [Automattic/jetpack#2163]
This just started happening today. Publicize is posting article excerpts along with a link to Facebook. It's no longer posting the "Custom Message" from the post screen settings, which usually defaults to the post title and short link.

Here's an example of how Facebook posts started appearing today:
http://i.imgur.com/gDgYvsn.png

And here's how they should look, respecting the "Custom Message" setting. Here's a Facebook post from yesterday:
http://i.imgur.com/Dg7JS9n.png

I know that Jetpack hasn't been updated since earlier this month, so I'm not sure why Publicize would start behaving differently today all of a sudden. Maybe it's something on Facebook's end?

**Comment by jeherve** [comment]
cc @jkudish It seems as if Facebook made some improvements to the way posts are displayed on Facebook Pages. They now look like the posts we publicize to Facebook Profiles.

Related: #565 and Automattic/io#361

**Comment by jeherve** [comment]
Also reported here:
https://twitter.com/ThreeIfBySpace/status/602197691926446080

**Comment by jeherve** [comment]
Also reported here:
https://twitter.com/MatthewSardo/status/601775700434104320

**Comment by jeherve** [comment]
Also reported here:
https://twitter.com/ReneHesse/status/601688010648920064

**Comment by jeherve** [comment]
@ChrisBegley It seems the changes were part of some changes we made on WordPress.com a few days ago. These days consequently did not require any Jetpack update.

For Facebook posts, we now send the custom message (along with the URL) without the excerpt, if a custom message is set. We still send an excerpt if no custom message is set.

If you would like the excerpt not to appear, you'll consequently need to set a custom message in the Publicize box appearing right above the Publish button in the post editor.

**Comment by ChrisBegley** [comment]
@jeherve it doesn't seem to be working like that though. 

The custom message was set to the post title (that's the default value that Jetpack puts in there):
http://i.imgur.com/AUER3Im.png

But when it just got auto-posted to Facebook, it put the excerpt instead of the custom message:
http://i.imgur.com/i2z4do3.png

**Comment by jeherve** [comment]
@ChrisBegley Could you try to define a custom Publicize message instead of the default title? That's what will be posted on Facebook.

**Comment by ChrisBegley** [comment]
@jeherve yep, that worked. I just put up a new post, the custom message defaulted to the post title "Samsung Galaxy S6 'Iron Man Edition' is the coolest phone you can't buy". I just added an exclamation point to the end of that:
"Samsung Galaxy S6 'Iron Man Edition' is the coolest phone you can't buy!"

And that got sent to Facebook. No excerpt this time. So I'll just have to remember to change the default custom message in order to avoid having the excerpt go to Facebook. Thanks for your help!
