### ISSUE TITLE
Remove entry date from related posts

### ISSUE THREAD

**Issue by thenoobi** [Automattic/jetpack#2164]
Thanks to related post jetpack, my blog load faster now.
But I need to removes dates at below list. Please Help me!

Something like this:

``` php
<time class="entry-date" datetime="2011-02-19T09:53:00+00:00">February 19, 2011</time>
```

I want to remove that code, not just hiding from CSS. 
Any tips?

**Comment by jeherve** [comment]
> I want to remove that code, not just hiding from CSS. 

That's not possible at the moment, I'm afraid.

@xyu When we added the date to the Related Posts, you mentioned that we could add a filter to not add any date: https://github.com/Automattic/jetpack/pull/778#issuecomment-47541451

Do you think we could add such a filter?

**Comment by thenoobi** [comment]
Hi @jeherve thanks for your respond,

Yes I think we should add a filter, option to add/remove date entry code.

**Comment by xyu** [comment]
If we add a filter we should also think about if we should also add filters for the context / except / etc. Not sure if it's best to filter on the actual HTML content or simply have this be another option that can be filtered on.

**Comment by kraftbj** [comment]
What about localizing using `wp_localize_script`. Something like this (pseduocode)
```
$defaults = array(
	'title' = '<span class="jp-relatedposts-post-title">%1$s</span>',
	'date'  = '<span class="jp-relatedposts-post-date">%2$s</span>',
	'context' = '<span class="jp-relatedposts-post-context">%3$s</span>',
	);
 
 wp_localize_script( 'jetpack_related-posts', 'jetpack_relatedpostshtml', apply_filters( 'jetpack_related_posts_default_html', $defaults ) );
```
which could be filtered using
add_filter( 'jetpack_related_posts_default_html', 'example' );
```
function example( $html ){
	$html['date'] = '';
	return $html;
}
```

Within the JS, instead of building the html there, pull the strings and strplace the placeholder with the content?

Alternatively, same idea but only allow for the content within the spans to be filtered which would allow people to only change the placeholder or add additional text within e.g. `Posted on %2$s` or whatever.

**Comment by samhotchkiss** [comment]
This seems like useful lowhanging fruit that we should be able to do in 3.8

**Comment by eliorivero** [comment]
Closing since this can the date can now be hidden either in Customizer or using the filter `jetpack_relatedposts_filter_options`:
```php
function jetpack_custom_relatedposts_filter_options( $options ) {
    $options['show_date'] = false;
    return $options;
}
add_filter( 'jetpack_relatedposts_filter_options', 'jetpack_custom_relatedposts_filter_options' );
```
