### ISSUE TITLE
Slideshow 'msie' property with JQuery >= 1.9

### ISSUE THREAD

**Issue by odie2** [Automattic/jetpack#2165]
Hello,

Just wanted try Slideshow of gallery, but error stopped initializing it on page.

I am using own jQuery v1.11.2 enqueued (and deregistered default) in functions.php

I got following error in bug console: `uncaught TypeError: Cannot read property 'msie' of undefined`
And found answer why it is happend on [stackoverflow](http://stackoverflow.com/questions/14793331/uncaught-typeerror-cannot-read-property-msie-of-undefined).

Greetings

**Comment by jeherve** [comment]
I can't seem to reproduce on my end.

> I am using own jQuery v1.11.2 enqueued (and deregistered default) in functions.php

That's most likely what's causing the issue. Could you try to use WordPress' own jQuery library, along with jQuery Migrate? See #372 for more details about the problem.

**Comment by odie2** [comment]
I find "[Why Loading Your Own jQuery is Irresponsible](https://pippinsplugins.com/why-loading-your-own-jquery-is-irresponsible/)" in your comment in #372 and did it.
It takes some time because I had to rewrite my old migrated 532 lines of jQuery where are js functions and events for future DOM events, but did it and now could using WP jQuery version ;)

Thanks
