### ISSUE TITLE
"Activate now" button should not wrap to two lines

### ISSUE THREAD

**Issue by designsimply** [Automattic/jetpack#2166]
UI nitpick: the "Activate now" button falls over to a new line when it shouldn't in the "Centralized Site Management" banner for the plugin on the main dashboard page:

![screen shot 2015-05-24 at sun may 24 2 33 07 pm](https://cloud.githubusercontent.com/assets/1119271/7789092/556ebb5c-0222-11e5-9bfd-dbfba2d425a8.png)
<sup>Seen at http://whyistheseasalty.com/wp-admin/index.php using Firefox 38.0.1 on Mac OS X 10.10.3 setup at Bluehost with WordPress 4.3-alpha-32580 and Jetpack 3.5.3.</sup>

**Comment by dereksmart** [comment]
Thanks @designsimply, we just merged this fix (#2045).  Will be in the next release.
