### ISSUE TITLE
Incosistent use of "website" and "site"

### ISSUE THREAD

**Issue by NekoJonez** [Automattic/jetpack#21662]
### Impacted plugin

Jetpack, Backup, Boost, Beta, Debug Helper, VaultPress

### Steps to Reproduce

While translating, I try to be consistent and I noticed that in Jetpack, the terms "site" and "website" are used for the same thing.

In only 25 of the 451 strings, website is used instead of site. 

To remain consistent in the plugin, I would change all the uses of "website" into "site" so the wording and term use is the same everywhere.

Sometimes, even in the same string, both terms are used. As in this example: 
![image](https://user-images.githubusercontent.com/4569581/140604468-1a49ad70-67c9-4923-ac4d-aaa67a9c3d86.png)

### A clear and concise description of what you expected to happen.

N/A

### What actually happened

N/A

### Other information

N/A

### Operating System

Windows

### OS Version

Win10 21H1

### Browser

Other / Not applicable

**Comment by NekoJonez** [comment]
I tried to start creating a PR for this, but I'm having some trouble. 
Looking for translate.wp.org, I noticed that most of them point to: 

https://plugins.trac.wordpress.org/browser/jetpack/trunk/_inc/build/admin.js#L32

But, I'm unable to see from which files this file comes from...

**Comment by jeherve** [comment]
`_inc/build/admin.js` is a build artifact, that's automatically generated when compiling code from multiple files in `	_inc/client`.

Here is an example:
https://github.com/Automattic/jetpack/blob/39fa657bfe0aaca179275331752fd99a74ac1c41/projects/plugins/jetpack/_inc/client/traffic/seo.jsx#L225

**Comment by NekoJonez** [comment]
I just created a PR and I think I got them all.

**Comment by jeherve** [comment]
closing this issue as wontfix as per the feedback here:
https://github.com/Automattic/jetpack/pull/23891#issuecomment-1103614104
