### ISSUE TITLE
Contact Form: add submitted date to entries in feedback csv file

### ISSUE THREAD

**Issue by richardfrench** [Automattic/jetpack#2169]
Feedback when exported as CSV has no date information for each entry.  I think this would be a useful feature.  I can create a patch for this, but wondered if adding a date should be optional or not, depending on an option within the Feedback page.

**Comment by georgestephanis** [comment]
I'm not sure if there would be any danger in silently changing the csv format -- if anyone has built things on top of it that read it in and wouldn't know what to do with the new column.  I'm certainly up to consider it though, just that we may need to add a way to let folks use a filter to strip it back out.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by formosattic** [comment]
Requested in 3322426-t.

Outdated plugin which could export with date: https://wordpress.org/plugins/jetpack-feedback-exporter/. Tested it but manage to get it working.

**Comment by seejacobscott** [comment]
Requested in 760204-zen. 

This does seem like important info to include on an export, especially if there is a large amount of feedback that is exported. Reopening for now.

**Comment by airdrummer** [comment]
thanx, jacob

**Comment by airdrummer** [comment]
i imagine the date can be added in function get_post_meta_for_csv_export()

**Comment by richardmtl** [comment]
Also requested here: https://wordpress.org/support/topic/include-submission-dates-in-csv-export-for-contact-form-feedback/

**Comment by airdrummer** [comment]
why has this been dropped? feedback date is a primary data point ffs:-\

**Comment by airdrummer** [comment]
in modules/contact-form/grunion-contact-form.php

public function get_post_meta_for_csv_export( $post_id ) 
{
	$md = get_post_meta( $post_id, '_feedback_extra_fields', true );
	$md['feedback_date'] = get_the_date( 'Y-m-d', $post_id );
	return $md;
}

**Comment by jeherve** [comment]
@airdrummer Feel free to open a Pull Request with your changes, we'll be happy to review them!

**Comment by airdrummer** [comment]
sorry i last used git 10yrs ago & don't have time to set up a dev env

**Comment by htdat** [comment]
Should be fixed in https://github.com/Automattic/jetpack/pull/14304
