### ISSUE TITLE
Center alignment using the Markdown module in Jetpack

### ISSUE THREAD

**Issue by ntpixels** [Automattic/jetpack#2171]
A user got in touch because the syntax for centering text is not parsing when the Markdown module is activated.

Steps to reproduce:
1. Enable Markdown module in Jetpack
2. Use the syntax for centering text
`-> center text here yo <-`
3. Publish or preview the text

Expected: the text within that bit of Markdown would appear centered
Actual: the text appeared unaffected with the -> and <- on either side

/cc @mattwiebe

**Comment by jeherve** [comment]
That syntax is specific to some flavors of Markdown, it does not exist in [the original Markdown syntax](https://daringfireball.net/projects/markdown/syntax) or in [Markdown Extra](https://michelf.ca/projects/php-markdown/extra/) and [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown), which Jetpack uses.

We consequently won't change that in Jetpack, at least not until that syntax is added to one of the Markdown flavors used in Jetpack.

**Comment by ntpixels** [comment]
Thank you for the catch. Sorry I missed that in my own research and for the unnecessary Issues post.
