### ISSUE TITLE
Jetpack Stats widget on Screen Options isn't appearing properly

### ISSUE THREAD

**Issue by muffinpeace** [Automattic/jetpack#21761]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Install Jetpack and connect it to a WordPress.com to benefit of Jetpack Stats.
2. Head over to Dashboard > Home and click on **Screen Options**
3. Uncheck or check the box and notice the Jetpack Stats widget appearing and disappearing.

### A clear and concise description of what you expected to happen.

Jetpack Stats, or Jetpack Widget to be correctly named amongst those options.

### What actually happened

Just a checkbox appears and controls the appearance of the Jetpack widget:

Happens on Firefox and Google Chrome on both Windows 10 and Mac OS Monterey.

![image](https://cdn-std.droplr.net/files/acc_1159618/eBBzdm)

### Other information

I've replicated this with three different sites hosted with different hosts running latest release.

### Browser

Firefox

**Comment by jeherve** [comment]
Related: #11400

**Comment by kraftbj** [comment]
@coder-karen is going to look into this, but FYI @bindlegirl that I'm curious if your work re SVGs in the dashboard widget title might accidentally fix this?

**Comment by bindlegirl** [comment]
Yes, I'm working on this as it's the part of the same issue #22669
