### ISSUE TITLE
JSON API: $blog_id of WPcom being used on Jetpack

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2176]
In class.wpcom-json-api-get-site-endpoint.php, we have an instance of using `blog_id` in Jetpack when the value being used is of the WP.com shadow site, causing a PHP notice being thrown by WP_Query as the table does not exist.

[L277](https://github.com/Automattic/jetpack/blob/3.6.1/json-endpoints/class.wpcom-json-api-get-site-endpoint.php#L277) is calling `get_site_url( $blog_id )` on the local Jetpack site.

At that time, `$blog_id` was set by [L71](https://github.com/Automattic/jetpack/blob/3.6.1/json-endpoints/class.wpcom-json-api-get-site-endpoint.php#L71) by `$this->api->get_blog_id_for_output()`.

That function is from [class.json-api.php#L509](https://github.com/Automattic/jetpack/blob/3.6.1/class.json-api.php#L509) which is calling `$this->token_details['blog_id'];` which is set by `Jetpack_Options::get_option( 'id' );`, which is the WP.com Blog ID.

Sample error:

``````
[Tue May 26 12:43:48.558167 2015] 
[client xxx] mod_fcgid: stderr: WordPress errore sul database
Table 'xxx_wordpress.wp_78204201_options' doesn't exist per la query SELECT
option_value FROM wp_78204201_options WHERE option_name = 'siteurl' LIMIT 1
fatta da wp_xmlrpc_server->serve_request, IXR_Server->IXR_Server,
IXR_Server->serve, IXR_Server->call, IXR_Server->multiCall, IXR_Server->call,
call_user_func, Jetpack_XMLRPC_Server->json_api, WPCOM_JSON_API->serve,
WPCOM_JSON_API->process_request, call_user_func_array,
WPCOM_JSON_API_GET_Site_Endpoint->callback,
WPCOM_JSON_API_GET_Site_Endpoint->build_current_site_response, get_site_url,
get_option ```
``````

**Comment by kraftbj** [comment]
Should we set that URL earlier, with a conditional if `is_jetpack`? I'm not that familiar with the API code and best practices for wpcom endpoints? If is_jetpack, return the siteurl for the current site vs using the blog_id?

**Comment by lezama** [comment]
I think this might been solved thanks to SAL, @gravityrail could you confirm?

**Comment by gravityrail** [comment]
@lezama @kraftbj I haven't been able to replicate this and as far as I know the logic in question was completely rewritten, so it's unlikely that this bug still exists.

**Comment by jeherve** [comment]
Closing this for now. @kraftbj Don't hesitate to reopen if this happens again.
