### ISSUE TITLE
Opt In To Comments Site Wide

### ISSUE THREAD

**Issue by mikezielonka** [Automattic/jetpack#218]
As a user, it would make commenting on my favorite sites way easier if I could opt in to comment replies site wide rather than per post.

For example, I follow this random guy's blog: http://ben.lobaugh.net/blog/148156/happy-valetines-from-bella/ and I have to rush to my email everytime after I comment so that I am sure I get an email to his response (he comments fast).

**Comment by samhotchkiss** [comment]
This is not in line with our current priorities/roadmap, so I'm going to go ahead and close (for now)
