### ISSUE TITLE
Enhancement: Add shortcode for Dotsub

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#2182]
A user in 2206420-t requested that we add https://dotsub.com/ to our shortcodes.  Looks like it's a video translation service (aka you add subtitles to videos hosted elsewhere).

**Comment by kraftbj** [comment]
I'd consider this a wontfix. Dotsub already supports oEmbed. If they added an `link rel="alternate" type="application/json+oembed` link on their video pages (e.g. https://dotsub.com/view/15f0467f-d351-4224-acf5-df3f2ba9d5a0 ), then this would auto-embed starting with WordPress 4.4.
