### ISSUE TITLE
Video Wrapper: Add bottom margin

### ISSUE THREAD

**Issue by melchoyce** [Automattic/jetpack#2185]
Every time I add a video, the `.jetpack-video-wrapper` class is applied to the container, and the content always bumps up against the video. Can we add a bottom margin to the wrapper class so there's always space between the video and whatever content appears beneath it? Even something like 1em would be good, across any theme.

**Comment by jeherve** [comment]
cc @thomasguillot

**Comment by melchoyce** [comment]
Thanks!
