### ISSUE TITLE
Deleted user but not disconncted from .com

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#2188]
Currently if a user is connected to .com but gets deleted before disconnecting first, the user is in a limbo state where they can't disconnect Jetpack from Calypso but can't do anything with that site since they don't have permissions, since they are not a valid user anymore. 

I think we need to fix this in Jetpack to help avoid this situation by disconnecting users when they are deleted.

**Comment by beaulebens** [comment]
Sounds like we might need to hook into when users are deleted, and if they're also connected to Jetpack, then fire off a request to WP.com/Jetpack to disconnect them?

**Comment by enejb** [comment]
I have a PR in #2221 that fixes the case for all Linked users but not for the master user. 
Since if I don't quite all the stuff that could go wrong if we disconnect the master user. And how that user is different from the regular linked user.
