### ISSUE TITLE
Unhooking Jetpack_Modules_List_Table::js_templates is not possible

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/jetpack#2189]
[`Jetpack_Modules_List_Table::js_templates` is hooked to `admin_footer`](https://github.com/Automattic/jetpack/blob/master/class.jetpack-modules-list-table.php#L59). I want to remove `Jetpack_Modules_List_Table::js_templates`, and replace it with my own.

**Comment by simonwheatley** [comment]
Some possible approaches:

* Add a filter on the `$function_to_add (callback)` parameter for the `add_action` call
* Add an action immediately after, to allow a `remove_action` call to be made elsewhere AND make the method static (or the class a singleton with a `get_instance` method) so that the `remove_action` call can work

**Comment by dereksmart** [comment]
Merged in filter to address this in #2191 

cc @simonwheatley
