### ISSUE TITLE
VideoPress: Closed caption icon duplicate on core video block

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#21914]
### Impacted plugin

Jetpack

### Steps to Reproduce

- Connect a Jetpack site, don't enable VideoPress 
- Upload a video to a post
- Notice that the core video block now has two icons in the toolbar for adding captions.

### A clear and concise description of what you expected to happen.

There should be just one caption icon. 

### What actually happened

Two caption icons appeared.

### Other information

![Screen Shot on 2021-11-30 at 12:25:34](https://user-images.githubusercontent.com/33553323/144106238-441c11f8-ab0d-4efb-b146-efa1d7400c2d.png)

### Operating System

macOS

### Browser

Firefox

**Comment by jeherve** [comment]
cc @roundhill, who worked on adding caption support to the Video block.

**Comment by roundhill** [comment]
It's also loading the progress bar color settings, which it shouldn't:

<img width="1102" alt="Screen Shot 2021-12-02 at 9 00 14 AM" src="https://user-images.githubusercontent.com/789137/144457636-246a43aa-9a61-4674-86e0-0af1198c3676.png">

cc @thedebian for any insights

**Comment by roundhill** [comment]
Per Slack discussion, we'll fix this as part of https://github.com/Automattic/jetpack/pull/21928
