### ISSUE TITLE
Rewrite Top Posts and Pages Widget to use WP.com REST API

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#2196]
The current widget uses the csv API for determining the top posts. The REST API is much more flexible: https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/stats/top-posts/

There are a number of bugs that occur with the current API. Particularly corner cases where the posts returned are of the wrong post type or for some other reason cannot be displayed. This causes fewer posts than the user specified to be displayed. In these cases multiple queries to the API may be needed, and caching should be added (similar to related posts?) so the page load time does not go up too much.

**Comment by georgestephanis** [comment]
We just rolled in site based authentication to rest api endpoints, so I expect we can likely use that method to query against it -- we'd just need to flag the endpoints wpcom side that it can accept site auth.

**Comment by jeherve** [comment]
@andreabadgley This user is running into this issue: #2369

Unfortunately rewriting the widget to use the REST API won't solve that issue; we'll need to take a different approach.

#2369 is marked as a high priority issue; we'll see if we can fix it in an upcoming major release.
