### ISSUE TITLE
PHPCS: Publicize

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#21968]
### Impacted plugin

Jetpack

### What

PHPCS

### How

```
	"projects/plugins/jetpack/modules/publicize/enhanced-open-graph.php",
	"projects/plugins/jetpack/modules/publicize/publicize-jetpack.php",
	"projects/plugins/jetpack/modules/publicize/publicize.php",
	"projects/plugins/jetpack/modules/publicize/ui.php",
```

@danielpost with your work here, would this be something that might be easier for you to handle?

**Comment by danielpost** [comment]
@kraftbj Yes, I'm mostly done with this actually, caveat being that the files actually change locations. I'll take this one.
