### ISSUE TITLE
Enhancement: Allow admin notes on Plugins > Manage page

### ISSUE THREAD

**Issue by supernovia** [Automattic/jetpack#22018]
### Impacted plugin

Jetpack

### What

Allow admin notes and more details on Plugins > Manage page

### How

A WordPress user in our forums [asked here](https://wordpress.com/forums/topic/plugin-for-tracking-plugins/) for a plugin-management plugin that displays notes from the site admin. [Jetpack has plugin management here](https://wordpress.com/plugins/manage), so perhaps this could be an enhancement?

> I run a site with several other people. We want to keep track of out plugins but the plugins page does not do it. I want to be able to add notes to the information for the plugin. I can see what it does, but I want to be able to make a note of what it does on our site, and whatever information we need to keep track of about it.
>
> There is nowhere in the list of plugins to add notes like this.
>
> I could write the information elsewhere, but then I would have to keep it synchronized with the list of plugins, which is supposed to be what the list of plugins does for me. So, I think I need a plugin that uses the active plugins data and allows one to add information to connect to that.

Super rough sketch via Inspect Element. I left the words in blue so they're easy to see for the mockup. The notes could even display just an excerpt on this page, with more details on the individual plugin page.

<img width="1060" alt="Screen Shot 2021-12-06 at 5 22 55 PM" src="https://user-images.githubusercontent.com/3476361/144943640-3353566e-642c-4836-b045-30d8d4a43742.png">

**Comment by supernovia** [comment]
Just noting in my experience helping users with their own sites, even lone site admins sometimes forget why they installed a plugin, or what part of the site it impacts, etc.  I could imagine them putting links to support requests in their notes as well.

**Comment by jeherve** [comment]
I do like the idea, and I think this would be better implemented in WordPres core itself, as the feature would be useful to anyone, even if they do not use the WordPress.com dashboard to manage plugins on their site. WordPress contributors have worked on improving the plugin update experience in the past few releases, and adding such a field could be a nice further improvement.

I would recommend opening a new ticket on Trac [here](https://core.trac.wordpress.org/tickets/latest) to suggest the feature to core WordPress.

Thanks!

**Comment by supernovia** [comment]
Thanks, if they did implement it, would we consider showing it on our plugins view?

**Comment by supernovia** [comment]
also, posted here: https://core.trac.wordpress.org/ticket/54592#ticket

**Comment by supernovia** [comment]
FYI: .org punted me to a #wontfix that said this should be done with a plugin, but I was able to find something to give the user with comments in the thread:
https://wordpress.org/plugins/plugin-notes-plus/
