### ISSUE TITLE
General: Add Windows Tile RSS Support

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2204]
Copied over from https://github.com/Automattic/jetpack/issues/1715#issuecomment-107546337 to keep 1715 clean.

Windows 8/8.1/10 can display items from your RSS/Atom feed on the tile. Are there any plans to add this functionality? You can check out http://www.buildmypinnedsite.com to find out how to do it but it's a single new meta tag (I have used http://example.com/feed as my RSS feed):

```
<meta name="msapplication-notification" content="frequency=30;polling-uri=http://notifications.buildmypinnedsite.com/?feed=http://example.com/feed&amp;id=1;polling-uri2=http://notifications.buildmypinnedsite.com/?feed=http://example.com/feed&amp;id=2;polling-uri3=http://notifications.buildmypinnedsite.com/?feed=http://example.com/feed&amp;id=3;polling-uri4=http://notifications.buildmypinnedsite.com/?feed=http://example.com/feed&amp;id=4;polling-uri5=http://notifications.buildmypinnedsite.com/?feed=http://example.com/feed&amp;id=5; cycle=1"/>
```

Also you should consider moving to using a browserconfig.xml for Windows support rather than loads of meta tags. People not using Windows 8/8.1/10 will not need to download any extra tags. See <a href="https://realfavicongenerator.net/blog/more-browserconfig-xml-less-html/">realfavicongenerator</a> and <a href="https://msdn.microsoft.com/library/dn320426%28v=vs.85%29.aspx">Microsoft</a> for more information. Here is an example:

```
<?xml version="1.0" encoding="utf-8"?>
<browserconfig>
   <msapplication>
     <tile>
        <square70x70logo src="small.png"/>
        <square150x150logo src="medium.png"/>
        <wide310x150logo src="wide.png"/>
        <square310x310logo src="large.png"/>
        <TileColor>#009900</TileColor>
     </tile>
     <notification>
        <polling-uri  src="http://notifications.buildmypinnedsite.com/?feed=http://example.com/feed&amp;id=1"/>
        <polling-uri2 src="http://notifications.buildmypinnedsite.com/?feed=http://example.com/feed&amp;id=2"/>
        <polling-uri3 src="http://notifications.buildmypinnedsite.com/?feed=http://example.com/feed&amp;id=3"/>
        <polling-uri4 src="http://notifications.buildmypinnedsite.com/?feed=http://example.com/feed&amp;id=4"/>
        <polling-uri5 src="http://notifications.buildmypinnedsite.com/?feed=http://example.com/feed&amp;id=5"/>
        <frequency>30</frequency>
        <cycle>1</cycle>
     </notification>
   </msapplication>
</browserconfig>
```

You can refer to the 'Windows Pinned Tile' plug-in for reference as this already does this.

**Comment by dereksmart** [comment]
Site icon lives in WP Core now
