### ISSUE TITLE
Search: reduce the initial indexing delay

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#22045]
### Impacted plugin

Jetpack

### What

Many of our bulk indexing/sync changes take 5 minutes to start.

### How

We currently delay all bulk indexing jobs by 5 minutes to reduce the risk of overindexing causing problems. We can probably carefully find a better balance for certain cases:
- Currency changes https://github.com/Automattic/jetpack/issues/19906
- New purchases and onboarding https://github.com/Automattic/jetpack/issues/13881 (this could also reduce some hacky indexing we are currently doing).

We definitely need to make sure that we don't overdo it. I wonder if we can build a separate deduping queue that will allow the first bulk index to be very fast, and then fall back to the 5 minute queue if there are multiple requests within an hour or so.

**Comment by bluefuton** [comment]
This would also help with moving from Simple to Atomic, where there's a switch of blog_id: https://github.com/Automattic/jetpack/issues/21693

**Comment by gibrown** [comment]
@mdbitz this is effectively done now since we are bypassing the dedupe queue?

**Comment by mdbitz** [comment]
Correct, I wanted to do another check for all flows but at this time when a site purchases Search we bypass the queue and immediately start the bulk indexing job. At the same time purchase triggers a Sync Checksum that on completion will trigger another bulk index.

This means that on purchase users should see content that already exists in the WP.com Cache populate in results. When the Sync Checksum finishes all content should be available in results.

**Comment by mdbitz** [comment]
Gave this another review as part of debugging activation and I'm comfortable with the current changes. They should give us a good balance of getting the index populated with minimal delay to users and overhead to our infrastructure.

Based on continued monitoring/feedback we can open a new issue if further changes are requested/suggested.
