### ISSUE TITLE
Sharing: add additional sharing options

### ISSUE THREAD

**Issue by Ste-Fantin** [Automattic/jetpack#22076]
### Impacted plugin

Jetpack

### What

more sharing

### How

Hello,
my name is Stefano Fantin and I have 2 ideas.
The first idea is that sharing button of Jetpack have more sharing option as sassy social share. Sassy social share is more complete that  button sharing of Jetpack.
My second idea is that jetpack search results have the share button. Google doesn't have a share button.
The share button in the search results is innovative. I repeat Google and Bing do not have the share button in the search results. You are visionary if you put the share button in the search results.
Best regards,
Stefano Fantin

**Comment by danmaze** [comment]
Their ticket: 4605601-zen

**Comment by sdixon194** [comment]
Thanks for the suggestions to make our plugin better! 

> The first idea is that sharing button of Jetpack have more sharing option as sassy social share. Sassy social share is more complete that button sharing of Jetpack.

Can you clarify a bit more about what Sassy social share has that you would like to see in Jetpack sharing? Is it just the amount of social media sites that you can share to, or some other features that they have you'd like to see? 

> My second idea is that jetpack search results have the share button. Google doesn't have a share button.

I'm not too sure what you mean by this - can you specify a bit more? Are you looking to see sharing icons in Google search results when a Jetpack site is listed, or something else I'm missing?

**Comment by Ste-Fantin** [comment]
Hello,
My two ideas that have many words, can be summed up in three words: "sharing and inclusion".
Sharing is more complete with Sassy, compared to the current Jetpack.
Inclusion is a consequence of sharing, i.e. if I allow sharing, I INCLUDE traffic. Traffic inclusion is important. Inclusion is meant to be word of mouth. Word of mouth is very effective when applied to sharing.
Google does digital divide because it doesn't include sharing in search results. The digital divide means not including in the digital, while my two ideas that have many words, can be summarized in three words: "sharing and inclusion". We must not do digital divide but we must do sharing and inclusion.
Best regards,
Stefano Fantin

**Comment by jeherve** [comment]
> Sharing is more complete with Sassy, compared to the current Jetpack.

Are there specific services (currently included in Sassy) you would like us to add to Jetpack's Sharing feature? Could you give us examples?

> Google does digital divide because it doesn't include sharing in search results.

Could you show us, with a link or a screenshot, where you would like sharing buttons to be displayed on search result pages? Would this be on your website, or on Google's page?

Thank you!

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
