### ISSUE TITLE
VideoPress play button shows emoji

### ISSUE THREAD

**Issue by eurello** [Automattic/jetpack#2208]
A user reported that his play buttons on VideoPress were big and blue. Looking at his site, the CSS for the play button was loading this emoji:

http://s.w.org/images/core/emoji/72x72/25b6.png

Here's the code:

    <div class="play-button"><span style="z-index:2;display:block;position:absolute;top:50%;left:50%;text-    align:center;vertical-align:middle;color:rgb(255,255,255);opacity:.9;margin:0 0 0 -.45em;padding:0;line-    height:0;font-size:500%;text-shadow:0 0 40px rgba(0,0,0,0.5);"><img class="emoji" alt="▶"     src="http://s.w.org/images/core/emoji/72x72/25b6.png"></span></div></code>

I can repro on <a href="http://eurello.wpengine.com/video/">my test site</a>:

![screen shot 2015-06-01 at 2 26 17 pm](https://cloud.githubusercontent.com/assets/8698879/7925784/47bc3678-0886-11e5-9e95-c57a77ac7983.png)

Reported in 165460-chat

Per @pento: 

> For the record, the solution is to add a <code>wp-exclude-emoji</code> class to the play button - this is obeyed as of WordPress 4.2.2.

**Comment by jeherve** [comment]
> For the record, the solution is to add a wp-exclude-emoji class to the play button - this is obeyed as of WordPress 4.2.2.

@pento That doesn't seem to work on my end (running WP Master). I tried adding the class to the div, and then to the span, but no luck:

![screen shot 2015-06-02 at 9 14 40 am](https://cloud.githubusercontent.com/assets/426388/7930355/e66eb814-0907-11e5-8656-360e6df3fcab.png)

**Comment by pento** [comment]
I'm AFK for the next month or so, @azaozz may be able to investigate why this isn't working.

**Comment by kraftbj** [comment]
cc: @nickmomrik, @rauchg
