### ISSUE TITLE
Do not load additional scripts although a feature is not active (not GDPR compliant)

### ISSUE THREAD

**Issue by laundy** [Automattic/jetpack#22125]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Install `WordPress` and `WooCommerce`
2. Install and activate `Jetpack`
3. Choose the `free` plan
4. Open your browser's developer tools (`Network` tab)
5. Refresh the page

### A clear and concise description of what you expected to happen.

Scripts and other dependencies, especially from third-party vendors like PayPal, are not loaded until the user has activated the corresponding feature of Jetpack (e.g. `simple-payments`).

### What actually happened

Jetpack just loads every dependency `before` checking if the feature that requires them is actually active. For `simple-payments`, this happens here: https://github.com/Automattic/jetpack/blob/5eb2645a33829c03d9adb0654efb289a138ff770/projects/plugins/jetpack/modules/simple-payments/simple-payments.php#L63

### Other information

In Germany and other EU countries where GDPR is active, this prevents everyone from using is without risking a fine.
Hence, I propose to move the `register_scripts_and_styles` call to a place which is executed only if the feature is active. This is also what I expected when reading the comment for `simple-payments`: https://github.com/Automattic/jetpack/blob/5eb2645a33829c03d9adb0654efb289a138ff770/projects/plugins/jetpack/modules/simple-payments/simple-payments.php#L3-L5
GDPR basically states (among other regulations): No dependencies from third-parties that are not absolute necessary for the page to work should be loaded before the user opts in. This is mainly because the user cannot prevent that at least her IP address is shared without their approval.

### Operating System

Windows

### Browser

Other / Not applicable

**Comment by jeherve** [comment]
Thanks for the report. We aim to do just that in Jetpack, and only enqueue (load) resources when they are needed on the page.

In the example of the Pay with PayPal feature, we do just that. As you pointed out, the scripts and styles are registered here:
https://github.com/Automattic/jetpack/blob/5eb2645a33829c03d9adb0654efb289a138ff770/projects/plugins/jetpack/modules/simple-payments/simple-payments.php#L63

This registers the resources, but doesn't load them on the site. They are only loaded later, when the Pay With PayPal shortcode is rendered on the page. This happens here:
https://github.com/Automattic/jetpack/blob/5eb2645a33829c03d9adb0654efb289a138ff770/projects/plugins/jetpack/modules/simple-payments/simple-payments.php#L184

In practice, that means the scripts and styles will only be loaded on the site's frontend if the Pay with PayPal button is added.

That's the intended behaviour, but if you experience something else on your own site, do not hesitate to let us know. We'll be happy to look into this with you!

**Comment by laundy** [comment]
Thanks for you fast reply! What you state is true of course, I missed this.
However, in the shop I have implemented that is not using this shortcode at all the dependencies are still loaded.

I moved `$this->register_scripts_and_styles();` to https://github.com/Automattic/jetpack/blob/f8969425fdf4fe2aa08a797ea86d321238436ba4/projects/plugins/jetpack/modules/simple-payments/simple-payments.php#L74-L82 and then reload the page, the dependencies are not loaded anymore. Is there any reason why you are registering the scripts when loading the plugin and not when they are used?

As the shop is run for Germany only, my customer uses the PayPal PLUS with the extension by [inpsyde](https://github.com/inpsyde/paypal-plus-plugin). This extension also uses the same script tag `wp_enqueue_script('paypal-express-checkout', ...)`: https://github.com/inpsyde/paypal-plus-plugin/blob/423c3d0e38de53d67365507603d17e94e78c84ee/src/Assets/PayPalAssetManager.php#L72
My assumption is that WordPress does not allow duplicate tags for scripts, but it seems like there is a interference between Jetpack and the PayPal PLUS plugin. What do you think?

**Comment by jeherve** [comment]
> Is there any reason why you are registering the scripts when loading the plugin and not when they are used?

We opted to register the assets separately because they can be used in 2 different places in the Jetpack plugin:

- In the Pay with PayPal shortcode, as I mentioned earlier.
- In the Pay with PayPal block, here: 
https://github.com/Automattic/jetpack/blob/26db3e436ccca3e16a62d02d95e792a81f38a1e4/projects/plugins/jetpack/extensions/blocks/simple-payments/simple-payments.php#L54

Registering the assets once, and then only enqueuing them later allows us to ensure that the assets are loaded only when necessary, and only once.

> This extension also uses the same script tag

That seems to be the source of the problem here, indeed. We should be able to rename that script tag on our end to avoid that conflict.

**Comment by laundy** [comment]
Thank you very much for the fix!
