### ISSUE TITLE
Cover block: paid-block-media-placeholder sets zero height to block placeholder

### ISSUE THREAD

**Issue by WunderBart** [Automattic/jetpack#22152]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Create a new post on a free WP.com site
2. Add Cover block
3. Add any other block(s)
4. See how they're hidden behind the Cover block placeholder as the `paid-block-media-placeholder` sets the absolute position with 0 heigh.

### A clear and concise description of what you expected to happen.

Other blocks should not be hiding behind the Cover block placeholder.

### Other information

The `paid-block-media-placeholder` was an issue before (#19488), where it was standing in the way of the actual Cover block content. It was fixed in #19489 via the `.paid-block-media-placeholder:not(:only-child)` selector which was correctly intended to not be applied in a placeholder state. At some point (some Gutenberg upgrade) though, a `.components-resizable-box__container` element has been added below the `.paid-block-media-placeholder`, which made the `.paid-block-media-placeholder:not(:only-child)` selector invalid and broke the block's actual placeholder as a result. 

Updating the [current selector](https://github.com/Automattic/jetpack/blob/56dc76f857357bec0bde3c98e8f640eb5d32fd4c/projects/plugins/jetpack/extensions/extended-blocks/paid-blocks/editor.scss#L118-L131) to the following one seems to be fixing the issue:

```css
.wp-block-cover:not(.is-placeholder) .paid-block-media-placeholder { ... }
```

https://user-images.githubusercontent.com/1451471/146987643-362daf33-4a73-4bd8-ac0f-575da3edfabe.mov

cc @ciampo

### Operating System

macOS

### Browser

Chrome/Chromium

**Comment by ciampo** [comment]
Hey @WunderBart , thank you for flagging this issue and adding a detailed explanation (and a potential solution!)

I currently have very limited capacity to work on anything else than Gutenberg components — would it be possible for someone else to work on a fix?

**Comment by amustaque97** [comment]
Hi :wave: if we're okay with the potential solution mentioned above I can work on this issue and will submit a PR. Then anyone can review it.

I'm able to reproduce this problem and potential fix is working. 

cc @ciampo and @WunderBart what do you think?

**Comment by ciampo** [comment]
Sounds good to me, thank you @amustaque97 !
