### ISSUE TITLE
Self-dismissing errors are dismissed too fast

### ISSUE THREAD

**Issue by koke** [Automattic/jetpack#2217]
I've noticed this a couple times when getting an error

![screen shot 2015-06-04 at 16 50 34](https://cloud.githubusercontent.com/assets/8739/7986781/edd733aa-0ad9-11e5-8515-3e232207b72e.png)

This disappeared automatically after 6-7 seconds when I was half way through reading it.

**Comment by kraftbj** [comment]
@koke Are you seeing this on latest master.

Sounds like either a duplicate of now-fixed #2076 or a regression if you're running master.

**Comment by koke** [comment]
I was migrating some of my testing blogs so I don't remember exactly, but I'm almost sure it was 3.5.3. I'll reopen if I catch it again
