### ISSUE TITLE
General: invalid_client_id when trying to connect to JP

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2218]
We've seen an increase of users who get a `invalid_client_id` when trying to connect to Jetpack.

The typical resolution is for them to delete and reinstall Jetpack (thus clearing Jetpack options out of the db).

My hunch is these are users who are deactivating Jetpack in some unexpected way (hence having Jetpack options in the db in the first place) and are then trying to reconnect.

We don't have much more to go on yet. My gut says they've increased solidly since 3.3 or 3.4.

Example user report:

> I installed Jetpack plugin and connected to my Wordpress profile. It worked.
> Yesterday it showed that Jetpack is not connected to my Wordpress profile. When
> I want to connect, I receive this message:
> Invalid request, please go back and try again.
> Error Code: invalid_client
> Error Message: Unknown client_id.

**Comment by kraftbj** [comment]
One report included they were on 3.4.1, disconnected, upgraded to 3.5.3, then had the error until they completely deleted JP.

**Comment by kraftbj** [comment]
One reported that the client ID being sent to us was `1`.

**Comment by kraftbj** [comment]
@dereksmart and I investigated this in detail today. It appears to occur specifically when the `blog_token` is set on the local db. Not sure yet why that happens as all of the code that would disconnect the site would also delete that option.

**Comment by dereksmart** [comment]
A possible patch would be to do something like ```if ( blog_token ) { delete it }``` somewhere around <a href="https://github.com/Automattic/jetpack/blob/1a6804355f55bfd1b43b9715b3df83ff95b05387/class.jetpack.php#L3034">here</a>.  Would stop the errors, but it wouldn't solve whatever is causing the initial problem.

**Comment by fomojola** [comment]
Seeing a very similar error on Wordpress.com, actually. The consent screen appears correctly (so I know I'm using the right client_id) but the access token request phase fails when I try and convert the code using the exact same client_id.

**Comment by felixarntz** [comment]
I encountered this issue too. For some reason no client ID was stored in the options, but a blog token was. I wonder if we can transform https://github.com/Automattic/jetpack/blob/master/class.jetpack.php#L4255 from

```php
if ( ! Jetpack_Options::get_option( 'blog_token' ) ) {
```

into

```php
if ( ! Jetpack_Options::get_option( 'blog_token' ) || ! Jetpack_Options::get_option( 'id' ) ) {
```.

After I had done this, I was able to reregister Jetpack - and then it worked. Maybe we just need to improve this if-clause like above to at least ensure that the user can retry to get a client ID if something goes wrong.

**Comment by kraftbj** [comment]
Thanks @felixarntz. I brought it up in #2661 for discussion. As far as what caused it, are you using memcache or another object caching on your site?

**Comment by kraftbj** [comment]
Discussed this ticket some with @morganestes (of 10up) who has reliably reproduced it on a client site by flushing memcache. I'm suspecting something to do with `alloptions`, perhaps the race conditions in core ( https://core.trac.wordpress.org/ticket/25623 ) and the related ticket to do away with alloptions ( https://core.trac.wordpress.org/ticket/31245 ).

One idea is to think a bit if the Jetpack Private options need to be `alloptions` or not and/or if we can structure them differently to isolate them some from conditions like this.

**Comment by felixarntz** [comment]
@kraftbj yes, Memcache is being used on the site. Thanks for checking by! :)

**Comment by dereksmart** [comment]
@felixarntz ICYMI, I think your suggestion to check for `id` option is the best way to go here.  See comments in #2661

**Comment by buley** [comment]
FWIW object-cache with memached backend was used on our site as well when we ran into this

**Comment by felixarntz** [comment]
@dereksmart looks good! Sorry I have been inactive here for a while

**Comment by kraftbj** [comment]
Another route for reproducing:
A & B .org users same site 
A & B both connected to same wpcom user account "C"
B delinks (as as secondary account), which removes C from both A and the site as a whole, leaving a ghost connection.

Upon recycling, invalid client id is thrown.

**Comment by jenhooks** [comment]
Once of these here: 2691843-t

**Comment by kraftbj** [comment]
Another similar was discovered via our VIP team today p1465408045001093-slack-jpop-support .

**Comment by kraftbj** [comment]
2692361-t

**Comment by buley** [comment]
This happened anew after months of peace and no code change. I can confirm again that fix for us is to disable plugin, `DELETE` the `wp_options` entry for `jetpack_options` and then re-activate the plugin.

**Comment by cena** [comment]
3020761-t

**Comment by eduardozulian** [comment]
3043001-t (pt-br)

**Comment by joendotcom** [comment]
3119202-t

**Comment by gaurav1984** [comment]
3125087-t

**Comment by kraftbj** [comment]
This may be resolved by https://github.com/Automattic/jetpack/pull/6964 .

**Comment by kraftbj** [comment]
If anyone is still seeing this occur actively, please try again after #6964 merged. It's on track for the June release.

**Comment by jeherve** [comment]
> If anyone is still seeing this occur actively, please try again after #6964 merged.

It looks like it's still happening even with that patch. It was reported in p8oabR-3s-p2

**Comment by rachelmcr** [comment]
I ran into this error while testing Pressable with Jetpack. Here were the steps I took:

1. Create a new Pressable site.
2. Log in to the site's WP Admin.
3. Select "Set up Jetpack" in WP Admin.
4. Complete the connection to WordPress.com.
5. Return to the Jetpack dashboard in WP Admin (`/wp-admin/admin.php?page=jetpack#/dashboard`).
6. Select "Manage site connection."
7. Select "Disconnect."
8. In my Pressable dashboard (my.pressable.com), select my site.
9. Select the link at the top of my site's Pressable dashboard: "To finish activating Jetpack Premium, please follow this link."

Result: I see the error described in the original report.

If I return to my site's WP Admin and select "Set up Jetpack" again from there, I can reconnect my site as expected.

**Comment by kraftbj** [comment]
Our changes over the years have effectively resolved this issue so finally putting the issue to bed.
