### ISSUE TITLE
Post Images: exclude Tracking Pixels from being selected by get_images

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2219]
For some reason Jetpack seems to pick up tracking pixels like [this one](http://ir-na.amazon-adsystem.com/e/ir?t=marandang-20&l=as2&o=1&a=0979019710) when looking for images in a post.

It would be nice to exclude these pixels and only select "real" images.

Reported here:
https://wordpress.org/support/topic/jetpack-open-graph-tags-adding-amazon-tracking-pixel-as-ogimage?replies=1&view=all

**Comment by aheckler** [comment]
Same issue in 2215016-t

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
