### ISSUE TITLE
Subscription Form block: Success message text does not update 

### ISSUE THREAD

**Issue by Robertght** [Automattic/jetpack#22193]
**HE Note:**

The custom success message for the Subscription Form block should be functioning on WoA and WPorg sites. The custom success message is not currently applying for WPcom simple sites however - the form still works but will show the default success message (not the customized one).

Feel free to continue using this issue to track additional interactions so they can be followed up on once we have a resolution in place, thanks!

---

### Quick summary

I noticed the Subscription form block success message does not update on WordPress.com websites.

Self-hosted websites are not affected.

cc @jeherve for a second look

### Steps to reproduce

1. Add a Subscription form block on the homepage
2. Change the Success message text from the sidebar
3. Check if the message shows up in the frontend after adding an email addres

### What you expected to happen

To see the custom message

### What actually happened

The default one showed up instead

### Context

4539775-zen

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Tested with 2021 and Hever

### Browser, operating system and other notes

Chrome 96

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by jeherve** [comment]
For reference, the feature was added in #21273

**Comment by zdenys** [comment]
Another case 4539775-zd-woothemes 

I also confirmed this on my test site.

**Comment by cat-og** [comment]
Another case in hc, I followed up with them in 4665936-zd, and confirmed this on my test site. (Tested themes Hever, Bushwick and Russell)

**Comment by samiff** [comment]
It was overlooked that the post-submission behavior differs between WPorg and WPcom simple sites:

https://github.com/Automattic/jetpack/blob/1092ed85efe819b969803c015e241fd6cf48bfd6/projects/plugins/jetpack/modules/subscriptions/views.php#L167-L168

Additionally, it looks like the success status handling differs between the two, with WPcom sites having `confirmed` (for logged in users) and `confirming` (not logged in) states.

I'd think we could apply the custom success message on WPcom sites for the `confirmed` status, but not sure about for the `confirming` status.

What do you think @jeherve ?

**Comment by jeherve** [comment]
Yes, you're right.

Maybe we can only make the success message available on Jetpack sites, since wpcom has more scenarios that we cannot all cover from within the existing UI?

**Comment by samiff** [comment]
> Maybe we can only make the success message available on Jetpack sites, since wpcom has more scenarios that we cannot all cover from within the existing UI?

I think this is probably the safest way to move forward given that WPcom is providing a more tightly managed experience here 👍 

https://github.com/Automattic/jetpack/pull/22283

**Comment by samiff** [comment]
The `Success message text` setting for the block will no longer show on WPcom simple sites, the setting is retained for Atomic/WPorg sites using Jetpack. The change has been deployed to WPcom.
