### ISSUE TITLE
No way to turn off stats smiley

### ISSUE THREAD

**Issue by ryelle** [Automattic/jetpack#22192]
### Impacted plugin

Jetpack

### Steps to Reproduce

I noticed the stats smiley was visible on my site today. I don't know how long it's been visible, since i don't usually visit my own site not-logged-in. When I went to turn it off, I couldn't find the setting for it. I see it was removed in #17499, but the [CSS generated in `stats_hide_smile_css`](https://github.com/Automattic/jetpack/blob/7a92c571a18ee7aa3ee191b18f841b4ee4c2fd7f/projects/plugins/jetpack/modules/stats.php#L841) still checks for that `hide_smile` setting, which was `false` on my site, so it was not being hidden — but now I had no UI to turn it off.

I ended up running `wp eval "stats_set_option('hide_smile',true);"` to hide it, so it's not visible anymore.

You can reproduce by updating `wp option patch update stats_options hide_smile false` and viewing your site. There's no way to hide the smiley without using CLI/PHP or custom CSS.

### A clear and concise description of what you expected to happen.

The CSS in `stats_hide_smile_css` shouldn't check for the option, it should just hide the smiley always.

### Other information

Site: https://ryelle.codes
Jetpack version: 10.4

### Operating System

macOS, Android

### Browser

Chrome/Chromium, Firefox

**Comment by jeherve** [comment]
> The CSS in stats_hide_smile_css shouldn't check for the option, it should just hide the smiley always.

Yeah, you're right. By now we really should be able to get rid of this. We'll take care of this in #22196.
