### ISSUE TITLE
[Boost] Critical CSS "Showstopper" errors exclude self-help steps

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#22205]
When an error only occurs in some areas of a site, we show an Advanced Recommendation with guides for how users can help themselves. For example:

![image](https://user-images.githubusercontent.com/1369626/148018644-6c6379e2-47c7-4b44-b294-581c46545a05.png)

But if a page error occurs so frequently that it prevents the whole Critical CSS process from working, the Showstopper error isn't as informative:

![image](https://user-images.githubusercontent.com/1369626/148018798-33cb8b52-c732-47c8-8a0e-efba23d02c28.png)

Where available, we should ensure that showstopper errors include helpful information.

**Comment by eAdnan007** [comment]
I gave it some time and was not sure how to proceed with actually showing the errors. Do you have something in mind in regards to how it should look and behave? @thingalon

**Comment by thingalon** [comment]
> I gave it some time and was not sure how to proceed with actually showing the errors. Do you have something in mind in regards to how it should look and behave? @thingalon

@eAdnan007 - As a starting point, I would consider using `pages/settings/elements/CriticalCssErrorDescription.svelte` to show an error inside the show stopper error component.

That component was designed with the Critical CSS Advanced Recommendations view in mind - so I would see how it looks in the showstopper context, and think about:

1. Is it reasonable to adapt that component to work alongside the ShowStopper error component?
2. If it's not reasonable, could we just reuse the helpers in `utils/describe-critical-css-recommendations.ts` to provide the text in the showstopper context?

This may require a few iterations and a bit of experimentation. I would avoid duplicating work as much as you reasonably can.
