### ISSUE TITLE
Pinterest Block: deprecate the block as the embed has now been added to Core

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#22223]
WordPress 5.9 will ship with its own Pinterest embed:

- https://core.trac.wordpress.org/ticket/53448

We may consider deprecating our block for folks running WP 5.9+

cc @pento who worked on the core implementation as well as the Jetpack block.

***********

Primary issue: #21322

**Comment by pento** [comment]
Aye, I think this is the way to go. Always be deprecating code in favour of Core where possible. 🙂

**Comment by lakellie** [comment]
Just bumping this as we're doing a review of support docs on the Jetpack site and noticed the duplicate block included in Jetpack.

**Comment by jeherve** [comment]
Working on this now.

**Part 1**: D140210-code

(this ended up not being necessary, since we'll need to keep the endpoint around; it is now used by other blocks as well)

**Part 2**

I originally wanted to remove the whole Jetpack Pinterest block, but when doing so we break existing Jetpack Pinterest embeds since they only display a link at that point:
https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/extensions/blocks/pinterest/save.js#L3

At this point I'm thinking our best scenario for now would be to:

- Keep the Jetpack block around
- disable inserting new Jetpack Pinterest blocks
- disable block transforms to Jetpack Pinterest blocks
- disable editing existing Jetpack Pinterest blocks
