### ISSUE TITLE
Twitter Cards meta: remove or remap photo, gallery, and product card types

### ISSUE THREAD

**Issue by niallkennedy** [Automattic/jetpack#2224]
[Twitter recently announced](https://twittercommunity.com/t/deprecating-the-photo-gallery-and-product-cards/38961 "Twitter Cards deprecation announcement June 2015") the removal of `photo`, `gallery`, and `product` Twitter Card link preview templates effective July 3, 2015. Deprecation fallbacks are in place, but it's better to map against active Twitter Card link preview templates for continued compatibility (and it will save some lookups).

All cards now have a max of one image, specified using the `twitter:image` meta element value.

## Gallery card

The gallery card used to include up to 4 images exposed through `twitter:image[0-3]` meta elements. Twitter will attempt to render a [summary_large_image card template](https://dev.twitter.com/cards/types/summary-large-image) using the `twitter:image0` meta element instead.

Change uses of the `gallery` card to `summary_large_image`. Single image with dimensions above 280x150 and less than 1 MB size.

## Photo card

Twitter will attempt to render a [summary_large_image card template](https://dev.twitter.com/cards/types/summary-large-image) when encountering a `photo` card type.

The `summary_large_image` template has the same minimum image dimension requirements as `photo`. The `summary_large_image` template adds the ability to display an excerpt using the `twitter:description` meta element.

## Product card

Twitter will attempt to render a [summary card template](https://dev.twitter.com/cards/types/summary) when encountering a `product` card type.

Product card minimum required image dimensions were larger than the summary card; no change needed. The label and data meta element data are now ignored.

**Comment by kraftbj** [comment]
Thanks for the fantastic detail. We don't use the Product card type, but do both Photo and Gallery. We'll get them fixed up!
