### ISSUE TITLE
Boost and Backup plugins don't activate with older version of Jetpack

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#22277]
### Impacted plugin

Backup, Boost

### Steps to Reproduce

1- Open Jurassic Ninja to launch new site
2- Click on Want more options
3- Include Jetpack and Jetpack Beta. On Beta, choose master branch of Backup or Boost
4- Try to launch the site

### A clear and concise description of what you expected to happen.

A JN site should launch. 

### What actually happened

The site does not launch.

Fatal error on JN logs:
```
Fatal error: Uncaught Error: 
Call to undefined method Automattic\Jetpack\Assets::alias_textdomains_from_file() 
in /srv/users/usered5bfcfb/apps/usered5bfcfb/public/wp-content/plugins/jetpack-backup-dev/jetpack-backup.php:95 Stack trace: #0 /srv/users/usered5bfcfb/apps/usered5bfcfb/public/wp-admin/includes/plugin.php(2286): include_once() 
#1 /srv/users/usered5bfcfb/apps/usered5bfcfb/public/wp-admin/includes/plugin.php(668): plugin_sandbox_scrape('jetpack-backup-...') 
#2 /srv/users/usered5bfcfb/apps/usered5bfcfb/public/wp-content/plugins/jetpack-beta/src/class-plugin.php(449): activate_plugin('jetpack-backup-...') 
#3 /srv/users/usered5bfcfb/apps/usered5bfcfb/public/wp-content/plugins/jetpack-beta/src/class-plugin.php(512): Automattic\JetpackBeta\Plugin->select_active('dev', true) 
#4 /srv/users/usered5bfcfb/apps/usered5bfcfb/public/wp-content/plugins/jetpack-beta/src/class-admin.php(154): Automattic\JetpackBeta\Plugin->install_and_activate('pr', 'update_backup-s...') 
#5 /srv/users/usered5bfcfb/apps/usered5bfcfb/public/wp-incl in /srv/users/usered5bfcfb/apps/usered5bfcfb/public/wp-content/plugins/jetpack-backup-dev/jetpack-backup.php on line 95
```

### Other information

It may be related to[ this code change](https://github.com/Automattic/jetpack/commit/9f91ba118e9e4ccbde5a2a55f9cb213417d23cfb#diff-b765ebf97a6ccb8a723d6aad0afa038d11cb7a1861274944edd2aabc820e6827). 

### Browser

Chrome/Chromium

**Comment by anomiex** [comment]
After some further testing, it looks like it may even be specific to activation via the Jetpack Beta plugin. If I arrange for a master version of Backup to be present and click "activate" from the plugins page, it doesn't fail.

**Comment by jwebbdev** [comment]
Let's keep this open and test it with the Beta version of the Jetpack Backup Plugin v1.1 when it's available.  As long as we can pull an older version of the Jetpack Plugin like 10.4, and install Jetpack Backup v1.1 after from the repo (probably worth testing some other combinations and activation orders) we can consider this just a Jetpack Beta issue, which is to say probably not an issue, or a different one at the very least.

**Comment by jwebbdev** [comment]
@kbrown9 found that this also causes a problem with the CLI added a check in Jetpack that's already merged.  @nunyvega has two PRs to address it in Jetpack Backup and Boost #22304 and #22306.
