### ISSUE TITLE
Jetpack website images don't scale

### ISSUE THREAD

**Issue by krogsgard** [Automattic/jetpack#2228]
Jetpack.me website images don't scale on small viewports. It doesn't create horizontal scroll, but it does cut them off.

https://cloudup.com/cgzLI_fXP4r

You just need a little 100% max-width and auto height action on the generic `img` tag and probably `.wp-caption` too. :)

**Comment by kraftbj** [comment]
cc: @jeffgolenski

**Comment by georgestephanis** [comment]
Yup, we've actually got an entirely new theme iteration Coming Soon (tm) for the site.  But unless we have a ship date yet (which I don't think we do) I'd like to continue maintaining old as needed.  Jeff, can you hit this at some point this week?

**Comment by jeffgolenski** [comment]
On it!

**Comment by jeffgolenski** [comment]
Good to go.
