### ISSUE TITLE
My Jetpack: Have the Plan Section component show multiple plans or plan if available

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#22290]
Make the component introduced in #22288 be actually functional. 

* Depends on #22289 
* Should be able to show one plan, multiple plans (probably coming from different feature plugins), or lack thereof

Initial basic design suggestions

One plan | Multiple Plans | Lack thereof
----|----|----
![image](https://user-images.githubusercontent.com/77539/149361673-9fbb755c-cee0-4610-9502-76946f12fcf0.png) |  ![image](https://user-images.githubusercontent.com/77539/149361697-07eb841b-cc33-47c3-bd20-07d316d7c2e0.png) | ![image](https://user-images.githubusercontent.com/77539/149361825-32cf1e25-a031-48b4-827f-8383d2033244.png)

**Comment by retrofox** [comment]
Updated the PR description. Not a big deal.
