### ISSUE TITLE
My Jetpack: Implement disconnected user view for Connection Section with prompt for connecting

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#22291]
Implement a status for the Connection Section where we prompt for connecting a user account...

<img width="300" alt="connection" src="https://user-images.githubusercontent.com/746152/149149634-5a0fee7a-85c4-41da-bdc5-74df47df54c3.png">

**Comment by leogermani** [comment]
We have discussed and decided that the My Jetpack page will be completely hidden if the site is not connected.

Discussion in: p1HpG7-dFw-p2#comment-51138

We also implemented the Disconnect redirect in https://github.com/Automattic/jetpack/pull/22067 that will take the user to the top level menu of the "Jetpack" admin menu after disconnecting from the My Jetpack page. (it can be a different page depending on which plugins are active)

Was there any changes to this?

**Comment by oskosk** [comment]
> Was there any changes to this?

No changes. Had that conversation in mind. I may have conflated concerns related to the "Fix missing user connection flow"

![image](https://user-images.githubusercontent.com/746152/149148381-453b19de-f4bb-41b1-b853-2e066ced1742.png)

Just updated the title and the screenshot

**Comment by retrofox** [comment]
Handling purchases when user not connected https://github.com/Automattic/jetpack/pull/22478

**Comment by retrofox** [comment]
First approach for Global Notice https://github.com/Automattic/jetpack/pull/22484

**Comment by retrofox** [comment]
> We also implemented the Disconnect redirect in #22067 that will take the user to the top level menu of the "Jetpack" admin menu after disconnecting from the My Jetpack page. (it can be a different page depending on which plugins are active)
> 
> Was there any changes to this?

It does work the first time the user is disconnected, right? The user still can click on `My Jetpack` item but it won't be redirected.

**Comment by retrofox** [comment]
Probably we'd like to implement these errors at the product level, meaning that, and depending on product conditions, we should reflex these data in the UI in the product card. p1643306716185800-slack-
