### ISSUE TITLE
Boost: Add build steps to e2e tests prerequisites

### ISSUE THREAD

**Issue by karthikax** [Automattic/jetpack#22297]
### Impacted plugin

Boost

### What

Boost: Add build steps to e2e tests prerequisites

### How

Jetpack Boost depends on some build steps to function properly such as npm installs, node builds, and composer installs, etc. 

Changing branch requires us to run these build steps. If we do not run the build steps after checking out a new branch, we may notice warnings or errors on the website. This is easy to detect in a development environment. However, the same may not be easily detected in e2e tests. So we may want to add the build steps as prerequisites to our end-to-end tests.

Investigate whether this is needed and implement it if needed.
Note: This may have unintended effects such as running a build script when our development environment actually should not have one.

Discussion: Slack - archives/C016BBAFHHS/p1641899287009800

**Comment by thingalon** [comment]
@karthikax - I'm doing a bit of a clean-up. What is the issue caused by this? Does it cause errors when we change branches?

Is it still relevant?

**Comment by karthikax** [comment]
By looking at the conversation, I think the issue was to do with `jetpack build`. I think running the command before running the tests is all we need. I think this is a non-existant issue. I think we can close the ticket.
