### ISSUE TITLE
Shortcode [Slideshow]: Update Slideshow jQuery Plugin to Prevent Potential Conflicts

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/jetpack#2231]
The jQuery Cycle plugin used in Jetpack is an older version from 2012. In one example, a theme on WordPress.com, is using a newer version of Cycle, called Cycle2. These two plugins are not meant to be used together, according to the developer. See the [frequently asked questions](http://jquery.malsup.com/cycle2/faq/). So having the two plugins on the same page causes a conflict. So this is an edge case, but something that could come up in other themes.

I'd suggest updating to Cycle2 or, perhaps consider an alternative, like [tCycle](http://jquery.malsup.com/cycle2/tcycle/). It has similar features, and is very lightweight.

**Comment by kraftbj** [comment]
If tCycle meets our needs, I like that it is less than 1 KB and, at first glance, appears that would cause less conflict with cycle-style JS in other themes/plugins.

**Comment by georgestephanis** [comment]
I'm not saying it's necessarily the direction we'll go in, but has anyone talked to the Woo folks about rolling in Flexslider instead?  It's far better w/r/t touch interfaces and such.

http://www.woothemes.com/flexslider/

**Comment by georgestephanis** [comment]
cc: @jeffikus for thoughts on ^^

**Comment by jeffikus** [comment]
Hi @georgestephanis - im afk right now, but will wb first thing in the morning!

**Comment by jeffikus** [comment]
Hi guys

Ok so I thought about it, and FlexSlider would probably handle your case easily, but - it does weigh in at 22kb for the min file -> https://github.com/woothemes/FlexSlider/blob/master/jquery.flexslider-min.js what I was thinking though was could you not get away with a better solution like using jQuery noConflict() to handle multiple instances of the library?

**Comment by georgestephanis** [comment]
Of Cycle, you mean?

**Comment by jeffikus** [comment]
Yes of Cycle.

**Comment by jeffikus** [comment]
Just a question though, some Automattic themes seem to be using FlexSlider already, so shouldn't be a problem to integrate it -> https://sketchdemo.wordpress.com/

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
