### ISSUE TITLE
CSS Generation shouldn't halt silently

### ISSUE THREAD

**Issue by pyronaur** [Automattic/jetpack#22315]
I agree that we shouldn't display errors on critical css generation if the module is suddenly disabled, but I also think it shouldn't necessarily just go silent. Or at the very least - it should update the UI to reflect the new status of the module.

https://github.com/Automattic/jetpack/blob/5fe0db4f6ab042ec3589f37df8e474bd39201269/projects/plugins/boost/app/assets/src/js/stores/critical-css-status.ts#L97-L99

**Comment by thingalon** [comment]
What do you think the UI should show if a user deactivates the Critical CSS module partway through generation?

**Comment by pyronaur** [comment]
Not sure. This is quite an edge case I think. Generally I'd want some reflection that the CSS Has stopped generating because the module was deactivated. 

So perhaps - a "frozen" critical css state and the module toggle button turned off, but that would probably be a bit over the top.

I think the least we can do is flip the toggle to reflect the updated status, and probably makes the most sense UX wise, apart from an explicit notification.

**Comment by thingalon** [comment]
@pyronaur still a bit stuck on this one. When you turn the feature off, the toggle moves to off, and the progress of generating is no longer shown. IMHO as a user this indicates that it's stopped processing based on user action.

Have I missed something?

**Comment by pyronaur** [comment]
A video is worth a thousand words :)

https://user-images.githubusercontent.com/988095/180752083-186dc0e7-5705-426f-847f-a8aafd0b818c.mov

Imagine the user having the left tab open somewhere in the background. After turning boost off, resuming the left tab 2 hours later still shows that files were generated successfully and the toggle remains in the on state.

In addition to that, if they user then decides to turn off the CSS again, we'll re-fetch fresh PageSpeed data one more time.

**Comment by thingalon** [comment]
_OH_ I see. That video does help. Thank you! :)

**Comment by thingalon** [comment]
This is solved.
