### ISSUE TITLE
Related Posts: add filter to allow removal of nofollow attribute

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#2233]
Some users would like to remove the nofollow attribute on the RP for SEO purposes, as described by Matt Cutts (old video from 2010 so I'm not entirely certain that the advice is still valid): https://www.youtube.com/watch?v=4SAPUx4Beh8 

Although there is a way to do it [via javascript](https://winwar.co.uk/2015/03/remove-jetpack-related-posts-nofollow-attribute/), it'd be cleaner and easier if we could include a filter to allow removing them.

**Comment by richardmtl** [comment]
requested in 2218747-t

**Comment by jeherve** [comment]
Also mentioned here:
https://wordpress.org/support/topic/why-related-posts-are-being-nofollowed
