### ISSUE TITLE
Social Media Icon Widget: Add a way to add custom social media sites

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#2234]
We want users to be able to add their own social media sites to the list without having to re-write the entire HTML output.  Couple things to consider: 

- If it's not a social media site that has a genericon, the user would have to also provide the icon as well as the URL
- This widget is shared with wpcom 

Couple possible approaches: 
- pass the html elements as an array (props @kraftbj )
- add another filter filtering everything inside the `ul` (props @jeherve )

**Comment by jeherve** [comment]
> pass the html elements as an array

One more vote for that option in @2447.

**Comment by jeherve** [comment]
Also requested here:
https://wordpress.org/support/topic/social-media-widget-genericons-no-google?replies=1&view=all

**Comment by samhotchkiss** [comment]
resolved by #2367

**Comment by soulseekah** [comment]
This isn't resolved at all, there's no way to add your own configurable service.

The `add_action`s there only allow for hardcoded output; why wasn't the `$instance` passed along at least? There's no way to add a text field to the `form` of the widget, and no clean way of saving this.

Can we reopen this and work some more on it? I'm ready to contribute to this.

**Comment by soulseekah** [comment]
Ah, nvm I see a discussion moved here: https://github.com/Automattic/jetpack/pull/2741
