### ISSUE TITLE
Photon Shrinks Images too Slowly

### ISSUE THREAD

**Issue by TheJeffr0** [Automattic/jetpack#2235]
This is a relatively new issue that's popped up but when browsing http://wptavern.com/ on my Macbook Pro in Firefox, Safari and Chrome, images in the single post view are seen shrinking. IE & Firefox resize to a point, and then stop. Chrome & Safari resize until the image disappears. 

This video shows the bug in action https://cloudup.com/cgQ_ztxtH7W when Photon is disabled, the issue goes away. I've deactivated Photon on the site until we can figure out what's wrong.

**Comment by kraftbj** [comment]
@TheJeffr0 My guess is something with our Retina JS, possibly interacting with other JavaScript on the site. I can't duplicate it on a test site. Would like to be able to see it live somewhere.

**Comment by jeherve** [comment]
I could reproduce on the Tavern, in the last post.

Do you happen to use an image lazy-load plugin, or a plugin handling Retina images on wptavern.com?

**Comment by jeherve** [comment]
cc @josephscott, since you've recently made some changes to `devicepx`. I can't reproduce anymore since Photon is now disabled on wptavern.com, but it seems that the `srcset` value for the image kept changing.

**Comment by josephscott** [comment]
Wow, that is a new one to me.

@TheJeffr0 any chance you can setup a test site and recreate the problem?

**Comment by TheJeffr0** [comment]
I just activated Photon again.

**Comment by jeherve** [comment]
Here is a quick video of the issue:
https://cloudup.com/cX9IiaZFcLO

**Comment by TheJeffr0** [comment]
Photon now disabled again as the team has seen it in action and documented what's going on.

**Comment by josephscott** [comment]
I did the following:
- View http://wptavern.com/introducing-the-wp-tavern-wapuu with Chrome on retina ( I set Chrome to emulate an iPad )
- Chrome dev tools, inspect the IMG element for the wapuu - http://i1.wp.com/wptavern.com/wp-content/uploads/2015/06/wapuu-wptavern.png?zoom=2&resize=406%2C486
- Right click on the IMG element, select 'Break On...' -> 'Attributes Modifications'
- Reload page

Break point hit after the page loaded and the image started shrinking.

There are several references to photon.js and jQuery.  I'm stepping through the break points and did see a reference to devicepx-jetpack.js.

I suspect that this is being triggered by a combination of items.  First step is figuring out how to reproduce it.  Once it can be reproduced then we can test potential fixes.

@TheJeffr0 what Jetpack modules do you have active?

**Comment by TheJeffr0** [comment]
I can confirm that it happens on my iPhone 5s

**Comment by TheJeffr0** [comment]
We have all modules activated on the Tavern except the following:
Infinite Scroll, Manage, Mobile Theme, Photon, Site Icon

**Comment by TheJeffr0** [comment]
We have not installed any new plugins within the past few weeks or made adjustments to the theme.

**Comment by mikeyarce** [comment]
Also reported here (2 users): https://wordpress.org/support/topic/photon-on-mobile?replies=3#post-7054492

One of the sites uses the "Lovecraft" theme: https://wordpress.org/themes/lovecraft/

On the other site (http://50.116.26.160:8080/staging.avelim.co.il/rafaelmemorial/) it only happens when viewing it on a small screen width.

**Comment by josephscott** [comment]
I've been able to reproduce this with the Lovecraft theme.  There is something at play with my recent change to devicepx-jetpack.js and some themes.

In the mean time I've reverted my change to devicepx-jetpack.js, while I figure out what is going on.

**Comment by josephscott** [comment]
I've deployed an update to devicepx-jetpack.js that restores the 'resize' and 'srcset' feature that I'd reverted, with a small change to the logic.  It now only applies if there is no 'srcset' attribute on the img tag.  This fixed the shrinking image issue in my tests.

**Comment by kraftbj** [comment]
@josephscott -- I haven't heard any other reports of issues related to this. I'm going to close this issue.
