### ISSUE TITLE
My Jetpack: Incorporate styles from codepen into my-jetpack package

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#22362]
Originally presented in p9dueE-47u-p2 we can use these as they represent the expected output:

Link: https://codepen.io/keoshi/pen/ZEXRyYV

![image](https://user-images.githubusercontent.com/746152/149623751-c717b314-4684-4778-af5a-7703e194447a.png)

**Comment by renatoagds** [comment]
This won't be needed, since we're moving the styles by piece for each component direct.
