### ISSUE TITLE
Update screenshots on WP.org

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#2236]
Don't know if this issue exists but we should update the plugin screenshots on wordpress.org plugin repo.
See https://wordpress.org/plugins/jetpack/screenshots/. 

CC @jeffgolenski

**Comment by jeffgolenski** [comment]
Great reminder @enejb I'll add it to my list!

**Comment by enejb** [comment]
Thanks, just saw it and though I would make it an issue.

**Comment by dereksmart** [comment]
I will be taking care of this in the 3.8 release
