### ISSUE TITLE
Admin Dashboard: Missing property for UserLicenseActivationNotice component

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#22382]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. With a development version of Jetpack (localhost docker env for example), have a **Backup**  plan for example and visit  the Jetpack dashboard. (Maybe any plan works I was just testing with this one).
2. Open the dev console
3. Expect to see a notice like this: 
  ```
Warning: Failed prop type: The prop `activationNoticeDismissInfo.last_detached_count` is marked as required in `UserLicenseActivationNotice`, but its value is `null`.
    in UserLicenseActivationNotice (created by Context.Consumer)
    in Connect(UserLicenseActivationNotice) (created by JetpackNotices)
  ```
  
  
![image](https://user-images.githubusercontent.com/746152/149918005-769ff52a-60fd-4698-843b-7a0ea7cbc9cd.png)

### Other information

cc @elliottprogrammer . Looks like #21474 introduced this behavior.

**Comment by elliottprogrammer** [comment]
Thanks for catching this and reporting the issue.

Yes it looks like we need to allow for default null values in the ActivationNoticeDismissInfo prop types.

I'll work up a fix for this asap. 👍

**Comment by oskosk** [comment]
Thanks!
