### ISSUE TITLE
Manage: WP Engine users can't update plugins

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#2240]
Originated from this ticket: 2205282-t

Per @roccotripaldi:

> it is definitely a WP Engine issue. WP Engine hooks into the plugin update flow, and comes at you with an “Are you sure…” dialog. This dialog interrupts update actions that we attempt from Calypso. it also will likely interfere with automatic updates.

**Comment by aheckler** [comment]
From the user in the ticket: 

> So working with WPE I have some more info. WPE and I both verified this behavior. We renamed the mu-plugins folder to > disable all WPE-specific plugins, which have the update plugins hook and cause the pop-up you mentioned. After verifying > that all MU Plugins were no longer on the plugins page, I tried updating a plugin via wordpress.com/plugins and I still > get the same very generic error that the plugin could not be updated.
> 
> So we might have ruled out the pop-up as being the culprit. WPE did this troubleshooting and then had me attempt to duplicate, which I did. They wanted me to get back to you guys with this info as they are interested in working with Automattic to get this resolved.

**Comment by roccotripaldi** [comment]
In my comment above, I speculate that this issue would likely interfere with automatic updates. After some testing, I'm eating my words! Automatic plugin updates work just fine on WP Engine

**Comment by octalmage** [comment]
Hey guys! 

This issue is caused by one of our (WP Engine) security features that stops untrusted scripts from writing to files. We're working on making sure Jetpack is trusted, but until that change is pushed we can manually resolve this if you put in a ticket.

**Comment by roccotripaldi** [comment]
thanks @octalmage. let me know if you have any questions about the Jetpack side of updates. We have an endpoint that updates plugins, one that updates themes, and one that updates WordPress core. 

We also have a script that enables automatic plugin / theme updates by hooking into the WordPress automatic updater which runs every 12 hours.  

I initially thought that auto-updates were running properly on WP Engine, but on further digging, it seems like my outdated plugins are not getting updated, even though I've flagged them to do so. My best guess as to why is the security feature you mention above.

**Comment by roccotripaldi** [comment]
@octalmage - i also learned that Jetpack cannot remotely activate / deactivate plugins. Do you know if that is for similar reasons?

**Comment by boogah** [comment]
@roccotripaldi It's for the exact same reason. As soon as we (WPE) can get Jetpack to be trusted on our end — which will require a bit of work from our platform team — this should be a non-issue for our shared customers.

Our Technical Project Manager is bumping up the priority of the bug. I'll work with him to get the fix in as soon as our internal release schedule will allow.

Sorry for any headaches this has caused!

**Comment by roccotripaldi** [comment]
thanks @boogah !

**Comment by boogah** [comment]
We've got a potential fix on our end. It still has to go through testing and then we need to get it in our deploy pipeline, but we're making progress.

**Comment by boogah** [comment]
I've tested the rules one of our developers came up on my personal site and played around with Manage. It appears to be working and debugging looks good...

![_jason_cosper_ _wordpress](https://cloud.githubusercontent.com/assets/216056/8367745/65939bcc-1b56-11e5-8610-3ad771e3faa5.jpg)

We still have to write tests on this end and then get the code that applies said rules into our deploy pipeline. As soon as we have a date for when the fix will roll out en masse, we'll make sure to update y'all.

**Comment by roccotripaldi** [comment]
Great news! Thanks for your help. I look forward to trying it on our end.

**Comment by kraftbj** [comment]
@roccotripaldi I'll leave this open until you give the thumbs up or down. Great stuff!

**Comment by boogah** [comment]
I just did a code review on our proposed fix. Looking good! Now it's in the pipeline.

Because of the upcoming holiday (see: July 4th) we probably shouldn't expect it to ship this week. Still, I'll do my best to make sure it gets out ASAP.

**Comment by roccotripaldi** [comment]
Awesome! Enjoy and be safe on July 4th if you are celebrating!

**Comment by roccotripaldi** [comment]
I can verify that plugin management via WordPress.com is working for multiple WP Engine sites!
I'm going to leave this issue open for an other day or two while I verify that automatic updates are working.

**Comment by jr00ck** [comment]
I'm the original person that reported this issue to both Jetpack and WP Engine to get the ball rolling on this. So glad you guys have made the progress you have. Thanks!

I can also verify that plugin management seems to be working via WordPress.com/plugins (manual updating, turning on automatic updates). However, although I see that automatic updates have been successfully turned on for all plugins on a particular site I'm testing, no plugins have been updated as of yet. I turned automatic updates on Monday, so 2 days so far. I'll check again Friday and report back. Once auto-updates are on, how often are updates supposed to occur?

**Comment by boogah** [comment]
@jr00ck To help test the automatic updater, you might want to install an older version of a plugin that may not be activated on one of your managed sites. One of the easiest ways to do this is to use the [WP Rollback](https://wordpress.org/plugins/wp-rollback/) plugin.

Just make sure whatever plugin you decide to test with hasn't had any [recent security issues](https://wpvulndb.com). :smile:

**Comment by roccotripaldi** [comment]
@jr00ck - autoupdates occur every 12 hours. it is also worth noting that if your site, or any of your plugins are under version control - the autoupdater will show great courtesy and not run at all.
to bypass that, you could include this code somewhere in your install:
`add_filter( 'automatic_updates_is_vcs_checkout', '__return_false'  );`

**Comment by roccotripaldi** [comment]
@boogah - on a number of WP Engine sites, we've confirmed that automatic updates are not running. that is is you go to WordPress.com and flag one of your plugins to automatically update, it will not update during regular automatic updates. 
can you provide any insight?

I'm still deciding if i should close this issue, and open a separate issue for auto-updates.

**Comment by jr00ck** [comment]
I can confirm that not a single auto-update has occurred on a WP Engine site that enabled automatic updates on all of it's 12 plugins 5 days ago via WordPress.com/plugins. WP site shows that auto-update is enabled for all plugins but no updates are occurring on the website.

**Comment by jr00ck** [comment]
Any updates on auto-updating working yet on WP Engine? We haven't heard any updates here for over 3 weeks. Auto-updates are still not working for me.

**Comment by kraftbj** [comment]
There are a few folks working on this as part of troubleshooting a few other edge cases with the plugin updater. They'll post here when they have something notable to pass back up.

**Comment by Aganator** [comment]
Any updates?

I recently found this thread while troubleshooting my failed connection between a WPE-hosted site and WordPress.com using JetPack.

It seems that the above bugs are worked out..... as long as you aren't using an SSL certificate on the site. As soon as SSL is enabled, BAM! JetPack fails to connect to the site. It won't even list my plugins now, much less do anything to them.

**Comment by kraftbj** [comment]
@Aganator -- Item 5, or the cousin of it, is likely the fix. `define( 'JETPACK_SIGNATURE__HTTPS_PORT', XXXXXX );`, replacing XXXXX with the port number of the server.

They probably have HTTPS terminating at the edge, so PHP itself is using a different port number than 443, which is expected for HTTPS site. In the future, reaching out via https://jetpack.me/contact-support/ is a great way to troubleshoot through issues with us.

**Comment by boogah** [comment]
This just got dropped back on my radar. Anything I can do from the WPE side to help?

**Comment by Aganator** [comment]
Hey! Thanks for checking. I actually don't know yet. I've been so slammed
with all the holidays coming up that I've had to put it on the back burner.
I'll try again Wednesday when I'm back in town. It's still important to me,
but I just can't keep working on it at the moment.


––


*Joshua Agan(623) 866-5343*
*JoshuaAgan.com <http://JoshuaAgan.com>*



*“…we look not at the things which are seen, but at the things which are
not seen: for the things which are seen are temporal; but the things which
are not seen are eternal.” 2 Corinthians 4:18*

**Comment by richards1052** [comment]
I installed Easy Updates Manager plugin & it fails to update plugins.  I tried contacting WPE techs and they tried various fixes on their end which haven't worked.  I tried installing Jetpack Manage and it shows all my plugins as not being eligible for auto update.  I see this error msg: "Core autoupdates are explicitly disabled by a site administrator." Troubleshooting tips suggested activating JSON API, which I did.  Jetpack continues to show all plugins as not being auto update-eligible.

If anyone has any suggestions about what's making this happen, please let me know.

**Comment by jeherve** [comment]
@richards1052 Could you send us more information about your site via [this contact form](http://jetpack.me/contact-support/), so we can take a closer look?

Thanks!

**Comment by jr00ck** [comment]
I just wanted to report back, since I was the one who initiated the ticket that started all this :)

Auto-updates are now working on the site we have been testing this on. Thanks a bunch! This issue seems to be resolved. 

A quick side note, a new issue has started where wordpress.com/plugins says it has an error fetching plugins on one of my sites. This is new and I don't know if it's related. The site is on HTTPS, however, I have another site on WPE with HTTPS (same setup/server/etc) and it's working fine with wordpress.com/plugins. So I'm not sure about that one. But I'll come back to that later.

**Comment by roccotripaldi** [comment]
@jr00ck - thanks, that is good to hear regarding autoupdates! I will close this issue now.

If you continue to see the fetching error, please open a new issue!

**Comment by designsimply** [comment]
I tested today and was unable to update plugins for a Jetpack blog hosted at WP Engine:

<strong>Video:</strong> [2m18s](https://cloudup.com/c9fUwng0KhO)
<sup>Tested with alittletestblog.com hosted at WP Engine running WP 5.0-alpha-42199 and Jetpack 5.6-beta-16346-b0f1aa8-master and PHP 5.6.31-4.</sup>

I noticed the following error show up in the WP Engine error logs:

> [Thu Nov 16 16:30:17.037907 2017] [authz_core:error] [pid 963] [client 72.217.158.204:29207] AH01630: client denied by server configuration: /nas/wp/www/sites/designsimply/wp-content/plugins/akismet/akismet.php, referer: http://alittletestblog.com/wp-content/plugins/akismet/akismet.php
