### ISSUE TITLE
Premium Content Block: Transforms Priority

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#22422]
### Impacted plugin

Jetpack

### What

Adjust the priority of the Premium Content suggestion in all blocks' transforms menu.

### How

<img width="322" alt="Screenshot 2022-01-20 at 10 23 39" src="https://user-images.githubusercontent.com/2070010/150320559-f7de8552-7497-45e6-bcb9-1e1705109631.png">

Premium Content seems to always show up as the first suggestion in the transforms menu of all blocks.

Let's explore if there's a way to deprioritize it, especially for presentational blocks (such as the Separator in the screenshot).

We might want to try to increase the priority for content or container blocks, which seem to be a great use case for a Premium Content transformation.

---

This might require a Core Gutenberg change.
Let's determine how time intensive it would be before committing to it.

See: p58i-bIN-p2 (relevant part starts at around minute 9)

**Comment by dsas** [comment]
There is a way of [defining transformation priority](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-transforms/), however it appears to be static - not allowed to be changed depending upon the source block. The premium-content block currently does not set a priority at all.

Steps:
 * See why it ends up always being the most important. It should be equal priority to others as it's not specified.
 * Investigate how to change the priority based upon the source block, ideas:
   * Specify multiple transforms? Not sure if it works, not sure if it works with `isMultiBlock`
   * Look into a core change

**Comment by dsas** [comment]
> Specify multiple transforms? Not sure if it works

Nope. I tried [changing the premium-content transforms](https://gist.github.com/dsas/b2378a59e9c6aa911d680535f74973ea) to see if I could make it differ by adding multiple transforms and setting the [priority field](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-transforms/#block) and it made no difference - the priority field is for selecting from the defined transformations, not for ordering them. See https://github.com/WordPress/gutenberg/blob/trunk/packages/blocks/src/api/factory.js#L366-L397

**Comment by dsas** [comment]
> Premium Content seems to always show up as the first suggestion in the transforms menu of all blocks.

For me it's not the first suggestion, it's usually second. The first suggestion is usually core/group. Looking into how the ordering works it's by 'frecency', see 

https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/store/selectors.js#L1768-L1773

Given this, is there actually anything to do here? _Perhaps_ we could make the frecency algorithm more complex e.g. by making the frequency count specific to the blocks being transformed - if you never transform a core/separator to a premium-content block then the frequency should be zero.

**Comment by Copons** [comment]
Thanks for investigating this @dsas.
I agree with you that changing the whole algorithm is overkill for the purpose of this issue, and could lead to unexpected consequences and inconsistencies.

I've downgraded to low for now, although I'm keeping it as "main focus" in our team's board. We can revisit it at a later date, after tackling more urgent issues. 🙂

**Comment by BogdanUngureanu** [comment]
Instead of changing the priority of the transforms (which is pretty complicated), I've opened a PR that simply disallows the transform to Premium content from markup blocks (e.g. core/separator) since allowing these kinds of transforms don't really make sense to have them.
