### ISSUE TITLE
Premium Content Block: Impossible Transforms

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#22423]
### Impacted plugin

Jetpack

### What

Avoid displaying the Premium Content transform if it's not actionable

### How

<img width="636" alt="Screenshot 2022-01-20 at 10 39 04" src="https://user-images.githubusercontent.com/2070010/150322973-ae6f5e1a-55c5-48c9-b9af-1e932ff12ce5.png">

Premium Content blocks or blocks nested into a Premium Content block cannot be transformed into a Premium Content block.

This is handled by simply _not performing the transform_ if those conditions are met:

https://github.com/Automattic/jetpack/blob/8052f28cd3dad5fe318295b14ab4d4f89ae4a083/projects/plugins/jetpack/extensions/blocks/premium-content/index.js#L85-L94

Though, this means that the Premium Content transform still shows up in the transforms menu for Premium Content; its preview is blank, and clicking on it doesn't do anything.

Let's explore if there's a way to avoid getting there in the first place.

---

This might require a Core Gutenberg change.
Let's determine how time intensive it would be before committing to it.

See: p58i-bIN-p2 (relevant part starts at around minute 9)

**Comment by dsas** [comment]
I've opened #22589 which I think covers all that can be done with Gutenberg < 11.1.0 (i.e. WP 5.8). That PR prevents offering transformations to premium-content blocks from premium-content blocks.

The [API changed in a backwards compatible way in Gutenberg 11.1.0](https://github.com/WordPress/gutenberg/commit/f2de29830423d8c0890add9889ee07d6bf7163f1#diff-88c9889d164b31c659049f4e6323f2c4d50c290c8b73b17dc0fa91102db8609e) - a second parameter is passed to isMatch which is the actual block/block objects being transformed. This means that the exact logic from the current premium-content `__experimentalConvert` method (see OP) can be repeated there. For compatibility with old versions of gutenberg, both `isMatch` and `__experimentalConvert` will have to run the same logic for now.
