### ISSUE TITLE
Premium Content Block: Remove and Keep the Content

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#22424]
### Impacted plugin

Jetpack

### What

Improve the Premium Content block removal action

### How

<img width="739" alt="Screenshot 2022-01-20 at 11 11 23" src="https://user-images.githubusercontent.com/2070010/150328056-f2bc5ed4-ba93-44dd-9b59-19d38e8b7b3d.png">

When removing a Premium Content block, all its content gets deleted as well.

Some users might want to only remove the "premium wrapper", for example, to give all users access to some previously paywalled content.

Let's explore if there's a way to hook into the remove/delete block function in order to perform a block transformation.

#### Note

There are probably two well defined and different user intents when _deleting_ a block (e.g. by backspacing while the block is selected), and when _removing_ it (e.g. by clicking on "remove block" from the toolbar's more menu).

My hunch would be that the former implies deleting the entire block, while the latter (especially when labelled "Remove Premium Content" as in the screenshot) could mean only removing the premium wrapper.

While working on this, let's reach out to previous owners and designers for advice.

---

This might require a Core Gutenberg change.
Let's determine how time intensive it would be before committing to it.

See: p58i-bIN-p2 (relevant part starts at around minute 10)

**Comment by dsas** [comment]
> My hunch would be that the former implies deleting the entire block, while the latter (especially when labelled "Remove Premium Content" as in the screenshot) could mean only removing the premium wrapper.
>
> While working on this, let's reach out to previous owners and designers for advice.

It might be less surprising to be consistent with every other block, and delete the entire block in both cases. Perhaps there should be an extra menu option to 'free' the content.

**Comment by Copons** [comment]
> It might be less surprising to be consistent with every other block, and delete the entire block in both cases. Perhaps there should be an extra menu option to 'free' the content.

What do you think if we started by providing a better transformation strategy?
For example, right now if you transform Premium Content to Group, it simply _inserts_ the Premium Content into a Group, rather than performing any transformations.
This is consistent with how other blocks transform into a Group but feels a bit awkward to me with Premium Content. 🤔 

We could provide a new `transforms.to` setting targeting `core/group` to change this behaviour.
We could discard all the "wrapper" and guest stuff, and only move the paywalled content over to the new Group.

And we can also explore your suggestion: let's see if there's a way to hook into the More menu, where we can append a "remove paywall" option, which would do pretty much the same that I've suggested for the transform. 😄

**Comment by BogdanUngureanu** [comment]
Having a separate Remove option (called, let's say, `Remove block and keep content`) that would be basically an alias to a `core/group` transform makes sense to me too.

**Comment by dsas** [comment]
I think that's a great idea @Copons. 

There might be an edge case for handling multiple selects, e.g. a paragraph block plus a premium content block selected, where _maybe_ it's better to just put both inside the group. I guess it is easily handled by having this new transformation not be multi-select enabled.
