### ISSUE TITLE
Search: Search widget breaks when switching from Instant to Classic search

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#22442]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Purchase a Jetpack Search plan for your site.
2. Ensure that Jetpack Search and Instant Search have been automatically enabled for your site.
3. Add a Jetpack Search widget to your footer (or a sidebar available on all pages).
4. Navigate to `/` and ensure that the widget and the search overlay works as expected.
5. Disable Instant Search.
6. Navigate to `/` or `/wp-admin/widgets.php`.

### A clear and concise description of what you expected to happen.

- For search box and sort selector to render for the Jetpack Search widget.
- For the Jetpack Search widget to preview correctly.

### What actually happened

- Search box and sort selector are absent from the Jetpack Search widget.
![image](https://user-images.githubusercontent.com/4044428/150448319-20f92a2b-48d1-471c-adb3-204444d7dced.png)

- Widget preview is broken.
![image](https://user-images.githubusercontent.com/4044428/150448341-787744c7-75bb-4cd7-ba95-b8cc0ffd521f.png)

### Browser

Chrome/Chromium

**Comment by kangzj** [comment]
Haven't looked into it. Just want to add some information. I deal with a couple of errors with the widgets before. I guess probably because Instant Search and Classic Search widgets aren't really the same widgets but share the same name - with block editor enabled, the drama happened.

**Comment by kangzj** [comment]
I couldn't reproduce the issue anymore. However the checkbox styling issue still persists, which seems to be related to height and width set to auto:

https://github.com/Automattic/jetpack/pull/8734

https://github.com/Automattic/jetpack/pull/8750

Not sure what's the best way to fix it, should we set a fixed height and width? @Automattic/jetpack-search

**Comment by dognose24** [comment]
> Search box and sort selector are absent from the Jetpack Search widget.

Updating the Instant Search footer widget and then disabling Instant Search would reset the displaying of the `search box` and `sort selection dropdown` on the Classic Search footer widget, which also breaks the widget preview.

<img width="810" alt="截圖 2022-08-15 下午10 32 35" src="https://user-images.githubusercontent.com/6869813/184656191-abde78dd-dbde-40cd-ae9e-345e27143c9a.png">

<img width="801" alt="截圖 2022-08-15 下午10 32 42" src="https://user-images.githubusercontent.com/6869813/184656519-dac1a34a-eee7-46df-b9c6-4626ec3f417f.png">
