### ISSUE TITLE
Publicize: Global Account changes being overridden per post

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2246]
Steps to duplicate:
1. User A (the admin, connected JP to their WP.com account) sets up global social media networks.
2. User B writes/saves a draft of a post. (Note: they do not have the ability to uncheck the social media networks)
3. User A edits/saves the post, unchecking any number of global social media networks.
4. User B edits and saves the post—the unchecked social media networks are re-added.

If this occurs when the user publishes, it'll send to all networks.

Possibly related to #1586

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
