### ISSUE TITLE
Open Graph Tags: article:author needs to be a valid user

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2247]
The `article:author` OG tag is populated from a post's [_publicize_facebook_user post meta](https://github.com/Automattic/jetpack/blob/202d1b80e9386aa6ed2dceb6ab9a4f362413e695/functions.opengraph.php#L77) when it is present.

In some cases, this can contained an app_scoped_user URL, e.g. `https://www.facebook.com/app_scoped_user_id/123456789` which will break the FB debugger:
![screen shot 2015-06-11 at 15 02 48](https://cloud.githubusercontent.com/assets/88897/8117023/f2c04502-104a-11e5-8926-5aed06670df4.png)

We should prevent app_scoped_user_id URLs from being used for `article:author`

Reported in 2133571

**Comment by kraftbj** [comment]
Noting that we stopped creating new situations like this in #1944, but for those with existing FB connections like this, it'd continue.

**Comment by jeherve** [comment]
Closing this since it's tracked internally as well.
