### ISSUE TITLE
Enhancement: Add nonce verification on REST endpoints

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#22543]
### Impacted plugin

Boost

### What

Make sure there is a nonce check for all REST Endpoints unless it's an idempotent request.

**Comment by thingalon** [comment]
@eAdnan007 Do you know if this is still relevant, since our big refactor?

**Comment by eAdnan007** [comment]
> @eAdnan007 Do you know if this is still relevant, since our big refactor?

Yes it is

**Comment by haqadn** [comment]
All non-idempotent user-action-based requests are now happening through data-sync.
