### ISSUE TITLE
Stats: add width and height attributes to tracking pixel image

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2254]
> the image g.gif that the stat module of jetpack outputs on the html fails when tested by Gtmetrix because no dimension (6x5) are specified
>
> The following image(s) are missing width and/or height attributes.
>
> http://pixel.wp.com/g.gif?v=ext&j=1%3A3.5.3&blog=22744152&post=3974&tz=2&srv=www.cookingwithpeachy.com&host=www.cookingwithpeachy.com&ref=&rand=0.5116504428442568 (Dimensions: 6 x 5)

Would it be possible to add the width and height attributes to the image?

Suggested here:
https://wordpress.org/support/topic/specify-image-dimension-for-ggif

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/pixelwpcomggif-missing-width-height-attributes?replies=2&view=all

**Comment by jeherve** [comment]
@bhubbard Did you mean to submit a Pull Request for that change you proposed in be81f0f62ba4ca958921260d29b722a1f02ec6d7 ?

If so, could you give it another try?

**Comment by bhubbard** [comment]
@jeherve Sorry was taking a quick look at it, submitted the pull request on accident.

**Comment by kraftbj** [comment]
Closing as a dup of #2856.
