### ISSUE TITLE
Enhancement: Display donations + nudge to users on lower tier plans

### ISSUE THREAD

**Issue by dsas** [Automattic/jetpack#22582]
### Impacted plugin

Jetpack

### What

List the Donations block in the inserter for lower-tier plans but display a nudge to actually use it

### How

The donations block is only available on jetpack / wpcom paid plans. It is not listed in the block inserter on free Jetpack sites though it is on wpcom free tier plans (and prompts an upgrade to use it).

Conversely the Payments block is displayed in the Gutenberg block inserter for all wpcom plans, even though the functionality can only be used for paid wpcom plans or Jetpack personal plans. For users on a free plan they are nudged to upgrade.

Block | Jetpack free | WPcom free
----|-------|------
 Donations | Not possible! | ![image](https://user-images.githubusercontent.com/93301/151886059-caa76fa2-35c4-4327-a0a2-d56634f926a5.png)
Payments | ![image](https://user-images.githubusercontent.com/93301/151885691-fa216466-65d4-4bdd-ab7a-2c02ed99571f.png) | ![image](https://user-images.githubusercontent.com/93301/151886039-c0e465a7-16ba-4311-89d8-31ee28617d25.png)

The donations block ought to be consistent with the Payments block on Jetpack free sites.

**Comment by jeherve** [comment]
This is something we've previously discussed in p1HpG7-aKx-p2

I think this is something we should discuss there again, maybe?

Somewhat related: the Payments block currently uses its own nudge instead of the common nudge used by the other paid blocks: #14893

**Comment by jeherve** [comment]
closing as the Donations block is now free. See #30432.
