### ISSUE TITLE
Publicize: `publicize_checkbox_default` incomplete coverage for non-admin & global accounts

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2258]
The `publicize_checkbox_default` can update the checked status of all services connected to an account. Global social media accounts are always disabled for non-admin users and, thus, always enabled without regard for this filter.

Example Workflow highlighting issue:
1. Add a filter: ` add_filter( 'publicize_checkbox_default', '__return_false' );`
2. Non-admin blogger writes a post. (Global accounts disabled)
3. Admin blogger edits and disables Global accounts (either by hand or already done, doesn't matter)
4. Non-admin blogger finishes and publishes.

Expected: Globals not used.
Actual: Globals used.

This is caused by https://github.com/Automattic/jetpack/blob/6186449af75dbcf1e2455be5a2f79ee89aa83c28/modules/publicize/ui.php#L629-632 which submits the disabled form items of the global connections.

Originally reported in 2222902-t

**Comment by jeherve** [comment]
Related: #1550 #453 #1007
