### ISSUE TITLE
Publicize: Tumblr: Publicized posts are posted from a "WordPress.com" app instead of a "Jetpack" app

### ISSUE THREAD

**Issue by RCowles** [Automattic/jetpack#226]
Publicized posts indicate the post is from WordPress.com even if the post is from a self-hosted WordPress installation using Jetpack. 

Screenshot from Tumblr:
![Tumblr Screenshot](https://i.cloudup.com/0KTPOPpsTx.png)

It looks like this has been improved upon on Facebook (*... an article on WordPress* instead of *... an article on WordPress.com*), but Tumblr still shows WordPress.com, as seen in the screenshot above.

Original Trac ticket:
https://plugins.trac.wordpress.org/ticket/1930

**Comment by jkudish** [comment]
I have renamed the Tumblr app to just `WordPress` and updated its description and URLs to better match the descriptions we use on other services (e.g. Facebook) as well as clarify that WP.com or Jetpack is needed.
