### ISSUE TITLE
Search: Auto-configuration adds extraneous widgets to the overlay sidebar for block-based themes

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#22612]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Spin up a WordPress site using a block-based theme, like 2022.
2. Connect Jetpack and purchase a Jetpack Search subscription for the site.
3. Navigate to `/wp-admin/widgets.php`.

### A clear and concise description of what you expected to happen.

For a Jetpack Search widget to be added to the overlay sidebar. 

### What actually happened

<img width="717" alt="Screen Shot 2022-02-01 at 6 03 54 PM" src="https://user-images.githubusercontent.com/4044428/152077031-a8a3b863-0821-457d-8ec7-ac6b4bc4f8f0.png">

Extraneous widgets are added to the overlay sidebar.

### Browser

Chrome/Chromium

**Comment by bluefuton** [comment]
Fixed by @kangzj in #24824. 👏
