### ISSUE TITLE
Network sub-site override doesn't work

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#2261]
When you un-check this box:

![Network sub-site setting](https://photos-6.dropbox.com/t/2/AACo5AOX3x4yqv3nV3av3bh9g5S162Q6sXGJ37FBHvy5fw/12/254790/png/32x32/1/1434466800/0/2/Screenshot%202015-06-16%2007.44.06.png/CMbGDyABIAIgAyAEIAUgBiAHKAEoAg/vvxJgXfstb8gKBnHdWqssKrfNQW4zpcuropCnJo-Xbo?size=1280x960&size_mode=2)

When you go to a sub-site, you're still presented with:

![Network sub-site setting](https://photos-5.dropbox.com/t/2/AACPvUeAxgV86mQOtZOABQjUSK1vgO2sviibt5SdG43eXg/12/254790/png/32x32/1/1434466800/0/2/Screenshot%202015-06-16%2007.46.33.png/CMbGDyABIAIgAyAEIAUgBiAHKAEoAg/7fwwv26z0oKsSeCJomZwjH4w4bYtlefONLFkEaQzTuw?size=1280x960&size_mode=2)

**Comment by dereksmart** [comment]
Seems to work properly for me.  

@samhotchkiss: your screenshots in that issue are broken now, to confirm - the issue was a regular admin of a sub-site was still able to connect regardless of the sub-site override option, correct?

**Comment by dereksmart** [comment]
actually My Jetpack still allows any admin to disconnect.  patch incoming.

**Comment by samhotchkiss** [comment]
Stupid github!  I don't remember :)
