### ISSUE TITLE
Jetpack Plugin background

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#2266]
In latest Chrome. ( I haven't tested other browsers ) 
I notices that the green clouds don't quite line up nicely. 
See 
![image](https://cloud.githubusercontent.com/assets/115071/8215395/613182b0-14e4-11e5-8731-b2758ac46ad9.png)

More specifically 
![image](https://cloud.githubusercontent.com/assets/115071/8215402/68edca86-14e4-11e5-92ed-1f51437b45d2.png)

cc: @jeffgolenski

**Comment by jeffgolenski** [comment]
good find @enejb 

I've removed that issue in this branch :-) Will roll it out soon! https://github.com/Automattic/jetpack/tree/enhancement/color-consistency

**Comment by enejb** [comment]
Thanks for fixing it :+1:
