### ISSUE TITLE
Admin Performance: Remove duplicate Jetpack SVGs loading in HTML

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#22669]
On `wp-admin/index.php`, the HTML included 5 copies of the same 1.6kb SVG embedded in the code:

![image](https://user-images.githubusercontent.com/7129409/152533440-8a3d099e-dd16-4051-97b9-d27290595fc4.png)

I recommend keeping the Jetpack logo in its own SVG file, so the browser can cache it.

Internal reference: p1HpG7-evU-p2

**Comment by bindlegirl** [comment]
One of the five mentioned SVGs is also mentioned in this PR #22812
