### ISSUE TITLE
Admin Performance: Minify dashboard-widget.css

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#22670]
There is a script; jetpack/css/dashboard-widget.css which loads unminified. It’s a minor detail – but it includes the full MIT license text, an empty Rule, and sourcemap information. It says it’s compiled form SASS, so it’s probably just a matter of updating the SASS settings to minify on compile.

Internal reference: p1HpG7-evU-p2

**Comment by jeherve** [comment]
That style is managed in the old gulp config here:
`projects/plugins/jetpack/gulpfile.babel.js`

It may be worth at least adding some minification I think.
