### ISSUE TITLE
Photon is trying to serve my SVG logo URL, resulting in a broken image

### ISSUE THREAD

**Issue by ChrisBegley** [Automattic/jetpack#22692]
### Impacted plugin

Jetpack

### Steps to Reproduce

I just noticed that the SVG logo on a site that I manage was broken, and it's because it's been converted to a Photon URL. This wasn't happening a few months ago, so could a recent Jetpack update have caused it? Here is the source code:

`<img width="100" height="100" src="https://artidixson.com/wp-content/uploads/2021/08/Arti-Dixon-Signature_K_O.svg" class="custom-logo astra-logo-svg" alt="Arti Dixson" srcset="https://i0.wp.com/artidixson.com/wp-content/uploads/Arti-Dixon-Signature_K_O.svg?w=2000&amp;quality=80&amp;strip=info&amp;ssl=1 2000w, https://i0.wp.com/artidixson.com/wp-content/uploads/Arti-Dixon-Signature_K_O.svg?w=3000&amp;quality=80&amp;strip=info&amp;ssl=1 3000w" sizes="(max-width: 100px) 100vw, 100px" data-attachment-id="1981" data-permalink="https://artidixson.com/arti-dixon-signature_k_o/" data-orig-file="https://artidixson.com/wp-content/uploads/2021/08/Arti-Dixon-Signature_K_O.svg" data-orig-size="100,100" data-comments-opened="0" data-image-meta="[]" data-image-title="Arti Dixon Signature_K_O" data-image-description="" data-image-caption="" data-medium-file="https://artidixson.com/wp-content/uploads/2021/08/Arti-Dixon-Signature_K_O.svg" data-large-file="https://artidixson.com/wp-content/uploads/2021/08/Arti-Dixon-Signature_K_O.svg">`

I tried to exclude the file from Photon as noted here: https://jetpack.com/2013/05/03/skip-a-image-with-photon/ but it didn't help: 

```
function my_photon_exception( $val, $src, $tag ) {

        if ( $src == 'https://artidixson.com/wp-content/uploads/2021/08/Arti-Dixon-Signature_K_O.svg' ) {
                return true;
        }
        return $val;
}
add_filter( 'jetpack_photon_skip_image', 'my_photon_exception', 10, 3 );
```

**Comment by umhan35** [comment]
Similar issue here. It replaced a SVG image in featured image (I used a plugin to upload svg images)

**Comment by ChrisBegley** [comment]
**Are you using the most recent version of WordPress (5.9)?**
Yes, with the Astra theme (version: 3.7.7): https://wordpress.org/themes/astra/
    **Do you use additional plugins that may impact the block editor (Gutenberg for example)?**
I have this plugin active (version Version 1.25.4): https://wordpress.org/plugins/ultimate-addons-for-gutenberg/
    **Do you use a specific plugin to enable SVG uploads on your site?**
Yes, SVG Support (version 2.4.2): https://wordpress.org/plugins/svg-support/
    **Did you use an image block, a specific block, a classic block, or was the image inserted via your theme?**
The image was inserted via the Customizer > Site Identity > Site Title and Logo Settings 
    **If the image is part of your theme, could you let me know what function is calling and diplaying the image in the template file?**
N/A

Hope this helps. Thanks!

**Comment by umhan35** [comment]
- Are you using the most recent version of WordPress (5.9)?
  - Yes, 2021 theme
- Do you use additional plugins that may impact the block editor (Gutenberg for example)?
  - NA
- Do you use a specific plugin to enable SVG uploads on your site?
  - Yes, SVG Support 2.4.2 (I have it and Jetpack both auto-updated. So, it might be either's problem)
- Did you use an image block, a specific block, a classic block, or was the image inserted via your theme?
  - It is the feature image below the post title (other places had the same problem)
- If the image is part of your theme, could you let me know what function is calling and displaying the image in the template file?
  - NA

**Comment by umhan35** [comment]
I just went to the support forum of "SVG Support 2.4.2". Looks like it's that plugin's problem from this post: https://wordpress.org/support/topic/version-2-4-2-svg-no-longer-displayed-with-jetpack-image-optimization/#post-15333069

> First I downgraded to 2.4.1 -> same problem.
> Then I downgraded to 2.4.0 -> here it works!

**Comment by umhan35** [comment]
I've just uploaded 2.4.0 (https://downloads.wordpress.org/plugin/svg-support.2.4.zip) and the problem is solved. So, it's not JetPack's problem.

At the meantime, maybe JetPack can increase its priority to not replace svg?

**Comment by ChrisBegley** [comment]
Thanks @umhan35! Rolling back to SVG Support 2.4.0 fixed it for me too

**Comment by jeherve** [comment]
Thank you both for the extra details. That is indeed a compatibility issue with the SVG Support plugin. We'll aim to fix that issue and better support any other plugins that customize srcset values in the next Jetpack release, via #22808
