### ISSUE TITLE
Color picker hidden behind Instant Search example

### ISSUE THREAD

**Issue by eoinsav** [Automattic/jetpack#22713]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Go to the "Search configuration" page: https://example.blog/wp-admin/admin.php?page=jetpack-search-configure
2. Try to change the highlight color

### A clear and concise description of what you expected to happen.

It should be easy to change the highlight color

### What actually happened

Half of the color picker is hidden

### Other information

<img width="1732" alt="Markup 2022-02-07 at 10 29 50" src="https://user-images.githubusercontent.com/35590156/152849565-82401d27-5f7f-4683-afbf-9c761e26deaf.png">

### Operating System

macOS

### Browser

Chrome/Chromium

**Comment by annacmc** [comment]
This is looking like a z-index issue. Currently, we have the overlay `div.jetpack-instant-search` with a max possible z-index  of `2147483647` which to ensure the overlay is always over top of everything else _(which correct me if I'm wrong, but is less necessary in the customberg display where it's not really overlaying on anything specifically)_

I believe to resolve this, the z-index value for `div.interface-interface-skeleton__sidebar` needs to be the same as, or larger than, that of `div.jetpack-instant-search`

We are currently _(temporarily)_ setting `$z-layers` in `/src/customberg/lib/_base-styles.scss` until ` @wordpress/base-styles` is updated. 

@jsnmoon I believe you wrote this, so before I launched into a PR fix, what do you think about this? Are there wider implications to messing with the z-index/layer values (only in customberg) that I haven't considered?

**Comment by jsnmoon** [comment]
@annacmc: Lowering the z-index value for the overlay within the Customberg context sounds like an appropriate fix! I don't foresee any regressions as long as the change is limited to Customberg.
