### ISSUE TITLE
Internal components are not found when looking for definitions in IDE like VS Code

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#22725]
When working on a file such as `projects/plugins/jetpack/_inc/client/at-a-glance/akismet.jsx`, we import internal components, like here:
https://github.com/Automattic/jetpack/blob/eeff05b677d0b3ae131dbecdba14303bbf6cda9f/projects/plugins/jetpack/_inc/client/at-a-glance/akismet.jsx#L21

Ideally, your IDE should allow you to jump to the definition for that component, but it does not work that way today:

https://user-images.githubusercontent.com/426388/152939196-c0e5dcfc-bb2a-4acd-a487-0a559895c180.mov

Here is an example from the wp-calypso repo, where this works well:

https://user-images.githubusercontent.com/426388/152939246-44697b7c-57f8-4c8e-a226-a6387ca58fc8.mov

*******

Slack discussion:
p1644236369862199-slack-CDLH4C1UZ

**Comment by anomiex** [comment]
Maybe I'm mistaken, but this doesn't seem to have anything to do with ESLint. Just VSCode's finding of the source file for an import.

**Comment by manzoorwanijk** [comment]
> this doesn't seem to have anything to do with ESLint. Just VSCode's finding of the source file for an import.

Yes, that's correct. I have changed the title accordingly.
