### ISSUE TITLE
Twitter unroll doesn't work: 'Sorry, you are not allowed to do that.'

### ISSUE THREAD

**Issue by MichalBrezny** [Automattic/jetpack#22744]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Add Twitter block
2. Paste post URL and click on embed.
3. Click on unroll

### A clear and concise description of what you expected to happen.

I tried to unroll Twitter thread.

### What actually happened

When I try to unroll a Twitter thread, I get an error 'Sorry, you are not allowed to do that.' and nothing else happens.
![twitter_wordpress_unroll](https://user-images.githubusercontent.com/10505475/153075718-a8d366b2-3bf6-409c-a3c7-fbac5563b525.jpg)

### Other information

Current Jetpack Version Option | 10.6:1644261077

</body>
</html>

### Operating System

Windows

### Browser

Chrome/Chromium, Microsoft Edge

**Comment by KokkieH** [comment]
Another report via [Twitter](https://twitter.com/AndyRowell/status/1491255781681147909)

**Comment by pento** [comment]
Confirmed, I suspect related to #22657 being merged to WPCOM: Jetpack sites call the API on WPCOM in the blog context, which (I think) doesn't pass any user info, causing the `current_user_can( 'edit_posts' )` check to fail.

/@jeherve

**Comment by jeherve** [comment]
It is indeed related to that PR (and D74346-code), and consequently causes all unrolling to fail on self-hosted sites at the moment, regardless of the version of Jetpack they're using.

Reverting D45966-code (and matching Jetpack PR #16370 ) would solve this issue, but then the problem with private sites would return. Ideally, I think we should find an alternative way to deal with this. I'm looking into this.

**Comment by MichalBrezny** [comment]
Thank you for quick response and solution. I confirm that it works now.
