### ISSUE TITLE
My Jetpack: Address issues found during walkthroughs

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#22760]
### Not implemented

- [x] #22923
  - [x] Add anti-spam when plugin is absent
  - [x] Add CRM (from product details when plugin is absent)
  - [x] CRM - not redirecting user to welcome page after activation
  - [x] Add VideoPress (from product details when Jetpack plugin is absent)
- [x] #22927

### Bug
- [x] Backup incorrectly reporting plugin_absent when active with Jetpack (Leo working on it) 
  - [x] #22924

## February 14th ( Just osk)

Fresh install on JN. No Jetpack plugin. Just Backup. Connected, no plan

- [x] Anti-spam shows as available but inactive
- [x] Backup shows as absent
  - [x] #22924

![image](https://user-images.githubusercontent.com/746152/153966023-03d9f5fc-ca4c-4a94-b297-e685ff4ec89d.png)

## February 13th (Just Leo)

- [x] #22846
- [x] #22845
- [x] #22842 (CRM - wont work)
  - [x] #22890

### First round - On Jurassic NInja. Bleeding edge - Jetpack present
- [x] #22844
- Search checkout flow is succesful
- Scan checkout flow is succesful... 
- [x] Scan checkout flow is succesful but I have to manually activate then
  - [x] #22820
- [x] #22843
- [x] #22842
  - [x] #22890
- [x] Add Backup fails silently
  - [x] #22790

## February 7th

- [x] Image load is taking too long in Product interstitial ( #22784 )
- [x] For products included in Security bundle, should we present that offer as well on the interstitial?
- [x] #22717
  - [x]  Jetpack Backup shows absent even when the standalone plugin is installed. 
  - [x] Jetpack Boost shows absent even after installing standalone plugin
- [x] Products should inform the link for “Manage”
- [x] Should we remove “Deactivate” from all products?
  - [x] #22802
- [x] #22627
- [x] #22732
  - [x]  Detected a fatal Fatal error: Uncaught Error: Class 'Automattic\Jetpack\Search\Plan' not found inclass-search.php 
- [x] Decision: Scan will only be active when the purchase is made
  - [x] #22820

**Comment by leogermani** [comment]
@oskosk 

> Anti-spam shows as available but inactive

That's expected when the Akismet plugin is installed (and it is pre-installed in WP)

**Comment by oskosk** [comment]
You're right @leogermani . That was the case reported here.

**Comment by retrofox** [comment]
should we close [this one](https://github.com/Automattic/jetpack/issues/22933), then?

**Comment by oskosk** [comment]
yes @retrofox . Closing now
