### ISSUE TITLE
Boost: Potential for fatal error on WordPress.com Private Sites, Improve error messaging

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/jetpack#22773]
### Impacted plugin

Boost

### Steps to Reproduce

Note that this fatal appears to be harmless but there could be room to improve error messages and logging + changes to prevent the fatal. Note that the error does not occur on every attempt.  The related PHP errors were initially reported to me by @ccwalburn.

Start with a WordPress.com site with Jetpack Boost installed.

1) Go to My Site > Settings and set the site to Private
2) Go to My Site > Jetpack > Boost.
3) Observe the following error. **_Note that this initial error is seemingly okay and is expected as the site is protected by Private mode and the required API requests are blocked_**.

```
Failed to load Speed Scores
HTTP 500 error received while communicating with the server.

{
  "code": "unauthorized",
  "message": "User cannot access this private blog.",
  "data": null
}
```

4) Click `Try again` option that is above the desktop/mobile score results and below the error. Or, click the `Refresh` option on the page.
5) Observe if a fatal error message is presented. Click `Try again` if not.
6) Check the site's PHP error logs via WP-CLI, the following error should be present if the error occurred.

```
[09-Feb-2022 19:00:04 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WP_Error::is_error() in /srv/htdocs/wp-content/plugins/jetpack-boost/app/lib/class-speed-score.php:295
Stack trace:
#0 /srv/htdocs/wp-content/plugins/jetpack-boost/app/lib/class-speed-score.php(117): Automattic\Jetpack_Boost\Lib\Speed_Score->prepare_speed_score_response('https://goode-a...', Object(Automattic\Jetpack_Boost\Lib\Speed_Score_Request), Object(WP_Error))
#1 /wordpress/core/5.9/wp-includes/rest-api/class-wp-rest-server.php(1141): Automattic\Jetpack_Boost\Lib\Speed_Score->dispatch_speed_score_request(Object(WP_REST_Request))
#2 /wordpress/core/5.9/wp-includes/rest-api/class-wp-rest-server.php(988): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/jetpack-boost/...', Array, NULL)
#3 /wordpress/core/5.9/wp-includes/rest-api/class-wp-rest-server.php(414): WP_REST_Server->dispatch(Object(WP_REST_Request))
#4 /wordpress/core/5.9/wp-includes/rest-api.php(386): WP_REST_Server->serve_request('/jetpack-boost/...')
#5 /wordpress/core/5.9/wp-includes/class-wp-hook.php(307): rest_api_loaded(Object(WP))
#6 /wordpress/core/5.9/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#7 /wordpress/core/5.9/wp-includes/plugin.php(522): WP_Hook->do_action(Array)
#8 /wordpress/core/5.9/wp-includes/class-wp.php(396): do_action_ref_array('parse_request', Array)
#9 /wordpress/core/5.9/wp-includes/class-wp.php(758): WP->parse_request('')
#10 /wordpress/core/5.9/wp-includes/functions.php(1310): WP->main('')
#11 /wordpress/core/5.9/wp-blog-header.php(16): wp()
#12 /wordpress/core/5.9/index.php(17): require('/wordpress/core...')
#13 {main}
  thrown in /srv/htdocs/wp-content/plugins/jetpack-boost/app/lib/class-speed-score.php on line 295
  ```
### Workaround

Set the WordPress.com site to Coming Soon or Public.

### A clear and concise description of what you expected to happen.

No fatals.

Also, the current error messaging, while accurate, might be confusing to some users fatal.

### What actually happened

Fatal errors can occur when Jetpack Boost attempts to get speed scores on WPCOM Private sites. Potentially on other hosts if certain requests are blocked via a plugin or other similar feature.

### Other information

Internal discussion: p1644432595899629-slack-C3GP81E05

**Comment by thingalon** [comment]
Thanks for reporting this issue.

Quick first round exploration:
- We've moved `app/lib/class-speed-score.php` since the last Boost release - the issue now is in `app/features/speed-score/Speed_Score.php`, line 284 - in `Speed_Score::prepare_speed_score_response`.
- Looks like `prepare_speed_score_response` expects to get two `Speed_Score_Request` objects -- which have an `is_error` method on them.
- `dispatch_speed_score_request` calls `maybe_dispatch_no_boost_score_request` which can return a WP_Error - which can then be sent on to `prepare_speed_score_response` in place of a `Speed_Score_Request`.

TODO:
- Reproduce this issue
- Check for other paths which may cause the wrong value to be passed to `prepare_speed_score_response` -- or adapt that method to accept `WP_Error` objects.

**Comment by JoshuaGoode** [comment]
Nice. My assumption this was only impacting private WPCOM sites was a bit misguided based on what has moved and your notes.  Seems it might appear more often on private sites for some reason but it's not always consistent.
