### ISSUE TITLE
Subscriptions: Notify email-only subscribers when they have too many pending subscriptions

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#2278]
Related changesets:

r119936-wpcom
r119935-wpcom
r119933-wpcom

**Comment by dereksmart** [comment]
@richardmtl do you mean to display it in the widget as an error? Should be easy to do

**Comment by jordwest** [comment]
Once this (and #276) is in place, it would allow us to reduce the current pending invite limits. See discussion on p2UL9c-38b-p2

**Comment by SiobhyB** [comment]
I'd like to add a +1 for some form of notification when there's too many pending subscriptions.

This week, I was testing the subscription options at the bottom of the comment form:

<img width="985" alt="Screenshot 2019-06-12 at 10 45 14" src="https://user-images.githubusercontent.com/2998162/59341204-5c06a800-8cff-11e9-8c17-4308c3418e39.png">

As I didn't receive any emails, I thought there was some form of bug and went down quite a time-consuming rabbit hole of testing. In reality, the reason that I wasn't receiving emails was that I had a number of pending subscriptions. 🤦‍♀️

It would have been really helpful and saved me a lot of time if I'd received a notification that I had pending subscriptions. 

This came after a user request and other HEs got tripped up: p9F6qB-3oD-p2

**Comment by tmmbecker** [comment]
2558374-zen
