### ISSUE TITLE
Gutenberg: Missing editor styles with Firefox

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#22787]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Use a Jetpack with a paid plan or an Atomic site to test.
2. Open the Site Editor.
3. Add the Donations block.

### A clear and concise description of what you expected to happen.

The Donations block and its notice banners are styled appropriately.

![image](https://user-images.githubusercontent.com/2070010/153396114-302ab485-2b59-41ef-bdfa-16d232632551.png)

### What actually happened

The Donations block appears completely unstyled.

![image](https://user-images.githubusercontent.com/2070010/153396020-728e8f22-c03a-4427-ba8e-ac9438349e25.png)

### Other information

_Note: the screenshots come from another test, but the result is virtually the same. Just ignore that it's on a free plan._

This is related to https://github.com/Automattic/jetpack/pull/22640.
That PR fixed this same issue on _most_ browsers on Simple sites by adding JP editor styles with `add_editor_style`.

@sdixon194 noted that the issue persists on Jetpack and Atomic sites, but only when using Firefox.

I could reproduce on Atomic but not on Jetpack (tested locally and on JN).

All things considered, I think it might be worth it to:
- Either use the same `add_editor_style` (using the new `Jetpack_Gutenberg::add_iframed_editor_style()` function) workaround in JP itself.
- Or completely rethink how JP enqueues editor styles to _only_ use `add_editor_style` by default.

I'm not familiar enough with the JP build system to make an educated decision on this, so I'd rather have a bit of a discussion before casually attempting the workaround. 🙂 

### Browser

Firefox

**Comment by BogdanUngureanu** [comment]
I've tried to reproduce this on two Atomic sites using two different themes (Blank canvas and Twenty Twenty-two) and I wasn't able to reproduce it anymore on Firefox. Jacopo, can you confirm that you still have this issues? 🤔

**Comment by BogdanUngureanu** [comment]
yup, the site is Atomic and connected to WPCOM sandbox, but I don't think it matters. Maybe we can try to reproduce it together?

![Screenshot 2022-04-19 at 12 43 17](https://user-images.githubusercontent.com/995955/163978268-e71a430d-1bc3-41a6-90c9-bced9931aa1a.png)

**Comment by Copons** [comment]
This is what I see on a fresh Atomic site on Pro, using Twenty Twenty-Two (tested on Quadrat and Blank Canvas as well):

<img width="1282" alt="Screenshot 2022-04-19 at 12 46 08" src="https://user-images.githubusercontent.com/2070010/163996555-6b1aef43-0c0c-40c5-84b1-a9e24e0e4dc5.png">

**Comment by dsas** [comment]
Works for me
