### ISSUE TITLE
Search: Be more defensive in logic around debug bar panel

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#22801]
### Impacted plugin

Jetpack

### Steps to Reproduce

We have not been able to reproduce. But, choosing to be defensive here will save us future issues in cases where users are interacting in ways that we don't expect.

### A clear and concise description of what you expected to happen.

See report at https://github.com/Automattic/vip-go-mu-plugins/issues/2891

### What actually happened

See report at https://github.com/Automattic/vip-go-mu-plugins/issues/2891

### Other information

p1644522524900439-slack-CDD9LQRSN

### Browser

Other / Not applicable

**Comment by rinatkhaziev** [comment]
It seems that in some cases the Classic_Search may be not initialized properly and then `instance` returns null. 

This works:

```php

		$jetpack_search  = (
			Jetpack_Search\Options::is_instant_enabled() ?
			Jetpack_Search\Instant_Search::instance() :
			Jetpack_Search\Classic_Search::initialize( Jetpack_Options::get_option( 'id' ) )
		);
```

But, personally, I'd still favor a `method_exists` check before calling it.
