### ISSUE TITLE
My Jetpack: Take over current My Jetpack link from Jetpack on the plugins page

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#22879]
Let's take over this link and make it link to My Jetpack

![image](https://user-images.githubusercontent.com/746152/153965707-0990ddf5-9708-4581-a2d7-656b3ddacdb2.png)

 @dereksmart @keoshi Would this make sense?

**Comment by keoshi** [comment]
I like it and it should be a good strategy to land people on the new page. It will be annoying for some customers not to go to the Dashboard (Stats is our most popular benefit), but it will set us up nicely for the user interviews and real-world feedback.

**Comment by retrofox** [comment]
> I like it and it should be a good strategy to land people on the new page. It will be annoying for some customers not to go to the Dashboard (Stats is our most popular benefit), but it will set us up nicely for the user interviews and real-world feedback.

Instead of replacing, could we add and maybe rename the options there?

`My Jetpack | Dashboard | Deactivate`?
