### ISSUE TITLE
My Jetpack: Add CRM Interstitial

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#22889]
We're going to show an interstitial product page for CRM too.

#### Design mock

![image](https://user-images.githubusercontent.com/390760/154059865-3f5cbe84-db27-44b6-9c31-3c68216c0151.png)

#### Copy

> Jetpack CRM
>
> All of your contacts in one place. Build better relationships with your customers and clients.
> 
> - Manage unlimited contacts
> - Manage billing and create invoices
> - Fully integrated with WordPress & WooCommerce
> - Infinitely customizable with integrations and  extensions
> 
> Add Jetpack CRM

#### Illustration

![Illustration - CRM](https://user-images.githubusercontent.com/390760/154061380-8240a7ea-3e03-493b-ba62-218b6dd53471.png)

**Comment by keoshi** [comment]
@retrofox @oskosk Edited the description above to add the mock and the respective copy. Let me know if you need anything else.

**Comment by retrofox** [comment]
> @retrofox @oskosk Edited the description above to add the mock and the respective copy. Let me know if you need anything else.

Thanks!

**Comment by keoshi** [comment]
Doh, forgot the illustration — added at the bottom!
