### ISSUE TITLE
Audio Shortcode: fallback to Jetpack's player for playlists

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#229]
Steps to reproduce:
1. In WordPress 3.5.2, create a new post including the following shortcode:
`[audio http://www.mbird.com/wp-content/uploads/2011/11/01-Ive-Been-A-Bad-Bad-Boy.mp3, http://www.mbird.com/wp-content/uploads/2011/11/02-A-Breath-Taking-Guy.mp3, http://www.mbird.com/wp-content/uploads/2011/11/03-If-Dolphins-Were-Monkeys.mp3, http://www.mbird.com/wp-content/uploads/2011/11/04-I-Told-Her-on-Alderaan.mp3, http://www.mbird.com/wp-content/uploads/2011/11/05-Right-Behind-You.mp3, http://www.mbird.com/wp-content/uploads/2011/11/06-Speedway.mp3, http://www.mbird.com/wp-content/uploads/2011/11/07-Man-Sized-Wreath.mp3, http://www.mbird.com/wp-content/uploads/2011/11/08-Church-On-White.mp3, http://www.mbird.com/wp-content/uploads/2011/11/09-Its-Real.mp3, http://www.mbird.com/wp-content/uploads/2011/11/10-The-Reason.mp3, http://www.mbird.com/wp-content/uploads/2011/11/11-Theres-No-Way-Out-Of-Here.mp3, http://www.mbird.com/wp-content/uploads/2011/11/12-In-No-Resistance.mp3, http://www.mbird.com/wp-content/uploads/2011/11/13-Bad-Blood.mp3, http://www.mbird.com/wp-content/uploads/2011/11/14-The-Neighbor.mp3, http://www.mbird.com/wp-content/uploads/2011/11/15-The-Road-to-Birmingham.mp3, http://www.mbird.com/wp-content/uploads/2011/11/16-Boulder-to-Birmingham.mp3, http://www.mbird.com/wp-content/uploads/2011/11/17-In-The-World.mp3, http://www.mbird.com/wp-content/uploads/2011/11/18-Nothing-Lasts-Forever.mp3|titles=I've Been a Bad Bad Boy, A Breath Taking Guy, If Dolphins Were Monkeys, I Told Her on Alderaan, Right Behind You, Speedway, Man-Sized Wreath, Church on White, It's Real, The Reason, There's No Way Out of Here, In No Resistance, Bad Blood, The Neighbor, The Road to Birmingham, Boulder to Birmingham, In The World, Nothing Lasts Forever|artists=Paul Jones, The Marvelettes, Ian Brown, Neon Neon, Brandon Flowers, Morrissey, R.E.M., Stephen Malkmus, Real Estate, Thunderclap Newman, David Gilmour, Frankie Miller, Crooked Fingers, Dixie Chicks, Mott the Hoople, Emmylou Harris, Ryan Adams, Echo and the Bunnymen]`
2. Jetpack's player inserts a playlist in your post.
3. Update to WP 3.6 (or 3.7 or 3.8)
4. Jetpack's audio player is deactivated, and since the core Audio shortcode doesn't support multiple audio files, the output is an incorrectly linked filename (in 3.9-alpha-27111).
5. Until Core support multiple audio files, it would be nice if Jetpack could detect shortcodes including multiple audio files, and use the Jetpack player.

Reported here:
http://wordpress.org/support/topic/plugin-jetpack-by-wordpresscom-audio-shortcode-is-not-falling-back-to-flash-in-ie9-ff?

Related: https://plugins.trac.wordpress.org/ticket/1794
Ported from: https://plugins.trac.wordpress.org/ticket/1869

**Comment by dereksmart** [comment]
Closing, as this affects a very small percentage of people, even less so as time goes on.  Any audio shortcode that has been added since WP 3.6 will transfer fine to Jetpack.  The solution for those that experience this is to convert the shortcodes to the new format.  If there are still more complaints about this than I though, please reopen.
