### ISSUE TITLE
Activate Product key: help navigating Licensing options

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#22913]
### Impacted plugin

Jetpack

### Steps to Reproduce

Currently, when I create a new jetpack site I end up with this notice. 
<img width="1060" alt="Screen Shot 2022-02-15 at 3 30 29 PM" src="https://user-images.githubusercontent.com/115071/154167774-4f304d61-8be2-4108-9b02-e28d72bf7ee5.png">

Which leads me to 2 screens. 

First link Activate it now. 

<img width="800" alt="Screen Shot 2022-02-15 at 3 34 50 PM" src="https://user-images.githubusercontent.com/115071/154167924-63724040-2933-4d81-8ad6-c7b1e43e4147.png">

or 

<img width="800" alt="WordPress_com" src="https://user-images.githubusercontent.com/115071/154168065-29f15441-c07d-4fe1-b2be-017591558ead.png">

### A clear and concise description of what you expected to happen.

I expected to get a bit more help with the context here. 
1. You should be able to tell me more about what Produce I have the key for. 

2. On the activation screen. Would it be possible to have a drop-down of the different possible keys? 

3. On the Purchases screen can we highlight the pending activation products keys that are there with an easy way to copy the key. 

### What actually happened

It is really hard to know how to find the key that I need to use to activate the product. 
There is a lot of missing contexts here. 

Granted I didn't just buy a key. I bought the key a long time ago. 

### Operating System

macOS

### Browser

Firefox

**Comment by jeherve** [comment]
cc @rcanepa whose team worked on the Licensing UI, and who may have some extra feedback on this.

**Comment by rcanepa** [comment]
Hey @enejb! These are great suggestions. I'm ccing @ederrengifo since he was the design lead behind these changes.

In terms of effort, I would say that number 2 (adding a dropdown with the user's license keys) requires more time than number 1, which should be pretty easy to implement.

**Comment by ederrengifo** [comment]
I love all the suggestions, some more specific comments:

> You should be able to tell me more about what Produce I have the key for.

I agree, I'm thinking we could modify the message based on the use case, if the user only has one license to activate, then we show the name of the product: _"Your < product name > is pending to activate"_, in which case maybe we can even make the activation process more straightforward assuming the available key is for that product. If the user has more than one license to activate, then we can keep the original message.

> On the activation screen. WOuld it be possible to have a drop down of the different possible keys.

I also like this, design-wise is very simple

> On the Purchases screen can we highlight the pending activation products keys that are there with easy way to copy the key.

I also like this idea and it doesn't seem too complicated to implement.

@rcanepa I'm happy to work on these improvements, but how should we handle it? Add them as ideas in the Roadmap, or we can directly work on them as part of the checkout post-project?. What do you suggest?

**Comment by rcanepa** [comment]
> I agree, I'm thinking we could modify the message based on the use case, if the user only has one license to activate, then we show the name of the product: "Your < product name > is pending to activate", in which case maybe we can even make the activation process more straightforward assuming the available key is for that product. If the user has more than one license to activate, then we can keep the original message.

This should not be hard to implement since we are already doing something similar on the pricing page when we should the licensing modal/prompt.

> On the activation screen. Would it be possible to have a drop-down of the different possible keys?

I think we can do this but we need to be careful since the activation UI can also be used for partner licenses, which are not tied to users (i.e., licenses that won't be displayed in the dropdown). So, we need a dropdown component that shows the licenses tied to the user that can also support entering a key manually.

> > On the Purchases screen can we highlight the pending activation products keys that are there with easy way to copy the key.

> I also like this idea and it doesn't seem too complicated to implement.

Exactly. From a development perspective, this is a straightforward task.

In summary, we have three tasks here:

1. Show the name of the product if the user has one available license – exactly how the licensing modal/prompt works on the pricing page.
2. Replace the input box on the Activation UI with a dropdown that shows the user's available licenses and supports entering a license key manually.
3. Highlight products that are pending activation, i.e., linked to a license key that has not been activated.

Tasks 2 and 3 require design work (especially task 2) before we can start working on them.

Finally, I suggest adding all of these tasks as separate cards on our [Maintenance board](1164141197617539-asboard), as they all can serve the purpose of introductory tasks for new hires. @ederrengifo, If you agree with the scope and goal of these tasks, I can add them to the board.

**Comment by ederrengifo** [comment]
@rcanepa sure! I can finish them this week

**Comment by rcanepa** [comment]
Ok. Here are the links to the cards for each of the items:

- [X] 1. Show the name of the product if the user has one available license – exactly how the licensing modal/prompt works on the pricing page (1164141197617539-as-1201858908716168).
- [ ] 2. Replace the input box on the Activation UI with a dropdown that shows the user's available licenses and supports entering a license key manually (1164141197617539-as-1201858908716176).
- [X] 3. Highlight products that are pending activation, i.e., linked to a license key that has not been activated (1164141197617539-as-1201858908716160).

**Comment by formosattic** [comment]
Hi there, the cards links don't load for me, so just wanna chime in.

About the display on the WordPress.com Purchases page. The `Pending activation` is misleading as it sounds like something is happening, so I also agree that rephrasing it in a more action-directed form will help. 
As is, the process is frustrating, and leads users to cancel their plan (5537413-zd-woothemes, 5602162-zd-woothemes).

The message can also link to this guide: https://jetpack.com/support/install-jetpack-and-connect-your-new-plan/#how-can-i-activate-my-license-key-in-my-jetpack-installation

**Comment by rcanepa** [comment]
> Hi there, the cards links don't load for me, so just wanna chime in.

Fixed. Do they work for you now?

> About the display on the WordPress.com Purchases page. The `Pending activation` is misleading as it sounds like something is happening, so I also agree that rephrasing it in a more action-directed form will help. As is, the process is frustrating, and leads users to cancel their plan ([5537413-zd-woothemes](https://href.li/?5537413-zd-woothemes)).

I agree with this.

> The message can also link to this guide: https://jetpack.com/support/install-jetpack-and-connect-your-new-plan/#how-can-i-activate-my-license-key-in-my-jetpack-installation

This is a great suggestion.

Thanks for your comment. I'll add these suggestions to the card.
