### ISSUE TITLE
Restore original in media gallery producing fatal

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/jetpack#22935]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Start from a site that's connected to WordPress.com, where you've uploaded some images in the past. 
2. Go to `https://wordpress.com/media/yoursite.com`
3. Select an image, and click on Edit (you can also upload a new image and produce the same result)
4. Click on "Edit Image" in the right corner of the image.
5. Save your changes.
6. Go back to edit the same image.
7. A "Restore Image" button now appears next to the "Edit Image" button. Click it

<img width="350" alt="Screenshot 2022-02-17 at 11 50 41" src="https://user-images.githubusercontent.com/426388/154461985-b73b58ab-c181-498d-a313-10a2f7328a3e.png">

8. see `We were unable to process this media item.`
9. see fatal in cli `PHP Fatal error:  Uncaught Error: Call to undefined function wpcom_get_private_file() in /wordpress/plugins/jetpack/10.7-a.5/json-endpoints/class.wpcom-json-api-edit-media-v1-2-endpoint.php:314
Stack trace:
#0 /wordpress/plugins/jetpack/10.7-a.5/json-endpoints/class.wpcom-json-api-edit-media-v1-2-endpoint.php(397): WPCOM_JSON_API_Edit_Media_v1_2_Endpoint->build_file_array_from_url('3307', 'https://aacm234...')
#1 /wordpress/plugins/jetpack/10.7-a.5/class.json-api.php(565): WPCOM_JSON_API_Edit_Media_v1_2_Endpoint->callback('/sites/17767759...', 1, '3307')
#2 /wordpress/plugins/jetpack/10.7-a.5/class.json-api.php(542): WPCOM_JSON_API->process_request(Object(WPCOM_JSON_API_Edit_Media_v1_2_Endpoint), Array)
#3 /wordpress/plugins/jetpack/10.7-a.5/class-jetpack-xmlrpc-methods.php(186): WPCOM_JSON_API->serve(false)
#4 /wordpress/core/5.9/wp-includes/IXR/class-IXR-server.php(121): Jetpack_XMLRPC_Methods::json_api(Array)
#5 /wordpress/core/5.9/wp-includes/IXR/class-IXR-server.php(207): IXR_Server->call('jetpack.jsonAPI', Array)
#6 /wordpress/core/5.9/wp-includes/IXR/class-IXR-server.php(109): IXR_Server->multiCall(Array)
#7 /wordpress/core/5.9/wp-includes/IXR/class-IXR-server.php(59): IXR_Server->call('system.multical...', Array)
#8 /wordpress/core/5.9/wp-includes/IXR/class-IXR-server.php(27): IXR_Server->serve('<?xml version="...')
#9 /wordpress/core/5.9/wp-includes/IXR/class-IXR-server.php(35): IXR_Server->__construct(Array, false, false)
#10 /wordpress/core/5.9/wp-includes/class-wp-xmlrpc-server.php(243): IXR_Server->IXR_Server(Array)
#11 /wordpress/core/5.9/xmlrpc.php(87): wp_xmlrpc_server->serve_request()
#12 {main}
  thrown in /wordpress/plugins/jetpack/10.7-a.5/json-endpoints/class.wpcom-json-api-edit-media-v1-2-endpoint.php on line 314`

### A clear and concise description of what you expected to happen.

you should be able to restore the original after editing

### What actually happened

fatals when you try to restore. Allows editing though

### Other information

Zendesk ticket: 4786168-zen

### Browser

Chrome/Chromium

**Comment by jeherve** [comment]
> Edit an image on a site with JP 10.7-a.5
> try to restore after the edit

Could you walk me through the steps you follow to do something like this? Is that in the Calypso media editor, in wp-admin > Upload, in wp-admin > Posts > Add New?

Thank you!

**Comment by Nic-Sevic** [comment]
Sorry @jeherve, I realize now I skipped some details. Will be more explicit in the future. thank you for updating the steps
