### ISSUE TITLE
Jetpack Protect Blacklist

### ISSUE THREAD

**Issue by georgestephanis** [Automattic/jetpack#2293]
Let's consider eventually adding in a local Blacklist as well as the existing Whitelist.

For example, if I've got a personal site with no other users, I may want to source data from something like http://www.ipdeny.com/ipblocks/ to block all of a specific country from attempting to log in by IP Range.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
