### ISSUE TITLE
My Jetpack: Remove Extras card

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#22944]
Just a proposal. Leaving here as a reminder

@keoshi should be just remove it? Keep it to be mildly associated to some Jetpack features?
If we remove it, Which layout you think we adopt for the cards on the bottom line?

**Comment by keoshi** [comment]
Thanks for bringing this up, it's a conversation we should have internally with but I'll share my initial thoughts here:

- **Card**: I think having a dedicated card for all Jetpack features still provides a value in surfacing them and redirecting people to the appropriate path (Settings).
- **Naming**: Totally not sure about “Extras” as an all-inclusive term for other Jetpack features. We'll have to test this out with customers and learn from it.
- **Strategically**: Considering the latest post on the "Why of My Jetpack" — p1HpG7-eUB-p2 — I think having an extra card, regardless of what we name it, is valuable in our long term plan but that might change in the future.

**Comment by oskosk** [comment]
Perfect, then! We just needed confirmation on whether we were keeping it or not ! Thanks @keoshi 

Closing as we're keeping the Extras Card
