### ISSUE TITLE
My Jetpack: Extras always shows as present

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#22943]
Let's doublecheck this issue. ~We may even end up removing this card~

**Comment by retrofox** [comment]
AFAIK and according to this comment, Extras is tied to the Jetpack plugin. It does make sense because it's possible to show the My Jetpack overview without the Jetpack plugin installed. In that case, `Extras` should not be active.

**Comment by oskosk** [comment]
Fixed by https://github.com/Automattic/jetpack/pull/23026
