### ISSUE TITLE
My Jetpack: Double check Beta badge on RTL layouts

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#22962]
![image](https://user-images.githubusercontent.com/746152/154561288-2c4afd70-f446-4517-a101-e6b1b1f8408a.png)
![image](https://user-images.githubusercontent.com/746152/154561337-afd3b22d-fc43-46de-aaa8-b80ef8c3e6b1.png)

This does not seem to happen with the Editor badge on which My Jetpack's was based

![image](https://user-images.githubusercontent.com/746152/154561391-060a10ec-379b-4336-a2f8-71dad942b6d9.png)

**Comment by keoshi** [comment]
We should be able to achieve the same result in RTL languages if we add `display: inline-block` to the beta tag. However, we'd need to adjust the margins, like so:

```diff
+ display: inline-block;
- margin: 8px;
+ margin: 0 8px;
color: #bbb;
```

LTR | RTL
--|--
<img width="348" alt="image" src="https://user-images.githubusercontent.com/390760/155127579-ab6bf22f-b6cc-400a-9e2e-035f793e9bac.png"> | <img width="346" alt="image" src="https://user-images.githubusercontent.com/390760/155127673-65521187-1b51-410c-9fb7-4d434297a785.png">

While investigating this, I also noticed the Editor beta tag is using a different style coming from the `awaiting-mod` class, which seems to have more automated/scalable way of doing this: https://rudrastyh.com/wordpress/notification-counter-bubbles.html

I'll leave it to you all if we'd ever want to use that, but I was under the impression the core “beta” tag also had a much more subtle styling as discussed here: p1HpG7-egt-p2#comment-51752
