### ISSUE TITLE
Subscribe block icon invisible

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#22973]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Simple wp.com site with Quadrat theme
1. In site editor templates or page editor, add subscribe form block
2. Icon is invisible

<img width="699" alt="Screenshot 2022-02-18 at 11 52 16" src="https://user-images.githubusercontent.com/87168/154660984-97534e6a-9939-4f67-ade4-c4c4a9228292.png">
<<img width="940" alt="Screenshot 2022-02-18 at 11 59 51" src="https://user-images.githubusercontent.com/87168/154660959-36fc7336-cdd2-472e-8d6a-b819b6da9859.png">
img width="1013" alt="Screenshot 2022-02-18 at 11 59 36" src="https://user-images.githubusercontent.com/87168/154660973-424e25bd-515b-40dc-8954-2e21e1dc377f.png">

### Browser

Firefox

**Comment by ivan-ottinger** [comment]
Fix is already live on WPCOM and Atomic. It will be also included in the next Jetpack 10.7 release on March 1, 2022.

→ Closing this issue.
