### ISSUE TITLE
Tidy CSS: Enable flex box support

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2297]
http://www.w3.org/TR/css-flexbox-1/

Tidy CSS itself isn't being maintained, IIRC. What is our plan to keep it updated or do we see if there's something else to serve our needs?

Reported in 2236620-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/jetpack-will-always-remove-flexbox-declarations?replies=2&view=all

**Comment by joseluis** [comment]
:+1: I was going to open an issue about this.

Right now the Sass pre-processor discards all `display: flex` rules (vendor-prefixed or not) after the first rule. E.g.:
```
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
```

Results in:
```
  display: -webkit-box;
```

**Comment by lancewillett** [comment]
This was added in https://github.com/Automattic/jetpack/pull/2123
