### ISSUE TITLE
My Jetpack: Handle cosmetic tweaks feedback from Design on the CFT

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#23014]
Context: p1HpG7-ePH-p2#comment-52538

- [x] Jetpack Logo size on `My Jetpack` #23090
- [x] Page heading `weight`.
- [x] `ProductCard` spacing not following `8px` rule.
- [x] `Icons` white space boundary. https://github.com/Automattic/jetpack/pull/23098
- [x] `Buttons` border-radius from `2px` to `4px`.
- [x] `My Plan` text for `no plan` and `manage plans`.
- [x] Link styles #23007

**Comment by retrofox** [comment]
Taking _Jetpack Logo size on My Jetpack_

**Comment by retrofox** [comment]
Closing #23074 in favor of #23090

**Comment by renatoagds** [comment]
- @retrofox I just have a few concerns in how we should follow about the 8px thing on ProductCard and border-radius, mainly on the last one, to avoid rewriting styles from `wordpress/components`. But if you think is ok to discuss that on the all-in-one PR, no problem, otherwise I would suggest to split it.

**Comment by retrofox** [comment]
we can split it up in case it gets big or too confusing
