### ISSUE TITLE
My Jetpack: Trying to activate Backup when Jetpack is inactive shows a weird error on Jurassic Ninja/Beta plugin

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#23031]
From Boost bleeding edge, trying to activate Backup when Jetpack is inactive shows a weird error on Jurassic Ninja/Beta plugin. Not sure what's the right combo for this report. The Backup plugin is not installed there. Only Jetpack

<img width="1536" alt="image" src="https://user-images.githubusercontent.com/746152/155297572-2998fc9b-c647-4b71-bcc4-e4974fabc8d4.png">

1. Launch a JN site with https://jurassic.ninja/create/?jetpack-beta&nojetpack&branches.jetpack-boost=master
2. Install Jetpack from the plugin directory but don't activate it
3. Connect boost and refresh the page
4. Visit My Jetpack
5. Attempt to install backup with the network pane of the dev console open and confirm, you see a red request for activating backup

**Comment by retrofox** [comment]
was it fixed by https://github.com/Automattic/jetpack/pull/23041?

**Comment by oskosk** [comment]
It keeps failing. Added screenshot and reproduction steps

**Comment by retrofox** [comment]
> Install Jetpack from the plugin directory but don't activate it

This point is not needed AFAIK
