### ISSUE TITLE
My Jetpack: menu item shown on WoA Business plan sites

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#23043]
On WordPress.com (Atomic) Business plan sites, the My Jetpack menu item is shown nested under Jetpack `/wp-admin/admin.php?page=my-jetpack`: 

![Markup on 2022-02-22 at 13:33:54](https://user-images.githubusercontent.com/15803018/155214581-bb1d5cd0-138f-4818-9120-2ac753b5e19c.png)

I'm not sure of the overall plans for My Jetpack on such sites, but several of the links direct to `cloud.jetpack.com` which won't work for these WoA sites and could confuse users.

**Comment by oskosk** [comment]
Should be be addressed by 818-gh-Automattic/wpcomsh

**Comment by oskosk** [comment]
No longer showing on WoA. Changeset is deployed now
