### ISSUE TITLE
Unprivileged roles should not see module descriptions

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2305]
Create a subscriber role, log in and visit the Jetpack page.

![screen shot 2015-06-24 at 12 35 54](https://cloud.githubusercontent.com/assets/88897/8336961/a6cd72dc-1a6d-11e5-8223-e136401a40be.png)

The subscriber is able to see the promoted modules and their status. Additionally the Debug link in the footer shouldn't appear.

It'd be better to remove this section completely, or, insert text on what the subscriber would benefit from by connecting their account (SSO if SSO is active on the site).

**Comment by aheckler** [comment]
> insert text on what the subscriber would benefit from by connecting their account (SSO if SSO is active on the site)

Is SSO the only benefit for subscribers who connect Jetpack?

**Comment by georgestephanis** [comment]
They don't need to connect Jetpack to WPCOM for SSO -- they just need to link user accounts from the user profile page.

I think it was there for notifications.  I'd support rolling in to 3.7 a new Subscriber version of that page that just explains what they -- as a Subscriber -- can do.

**Comment by aheckler** [comment]
Independent of what we do on the page re: subscribers, showing the debug link to admins only was a quick fix. PR above.

**Comment by macmanx2** [comment]
I just ran into this with another user today and tested it out myself. I'd be in favor of removing the section entirely for the Subscriber role. As of Jetpack 3.6, the Subscriber role can't do anything but connect and disconnect their WordPress.com account.

**Comment by georgestephanis** [comment]
As the admin page link / unlink has currently nothing to do with the SSO connecting, do we still need it for Notifications to show, or is that now based entirely on authenticated user to wpcom?

**Comment by macmanx2** [comment]
I can't even find a way to switch on Notifications as a Subscriber. This 36-second video shows the entire UX for someone with the Subscriber role: https://cloudup.com/c_0Mcf8G1jU

The only thing that can be done with the Subscriber role is connect and disconnect.

**Comment by jeherve** [comment]
> I'm just wondering if we can drop the admin page entirely for subscribers, or if we need it yet.

I think we can safely drop it once #1216 is fixed.

**Comment by dereksmart** [comment]
Ditto to what Jeremy said.  I have a PR open to fix that issue #2346 

FWIW, linking your account is required to see notifications.  However: 
- useless if the admin has disabled notes module
- since they can't post, the only notes for this site they would get is a reply to one of their comments.  Can't think of anything else that would notify them as just a sub.  

I think dropping it is fine.  We should make sure to hide the notification icon though.

**Comment by jeherve** [comment]
> I suppose they'd be able to receive notes for any other site they have linked though.

You actually already get that even if you haven't linked your account. Visit the [make/core](https://make.wordpress.org/core/) blog while being logged in to your WordPress.org account, for example.

**Comment by dereksmart** [comment]
subs no longer have access to that page since #2441
