### ISSUE TITLE
Enhancement: Redesign + Rebuild banner CTAs within Plugin

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#2306]
Right now the banner CTAs within Jetpack are a little haphazard. the code is bloated and the styling is a little outdated. They also don't play well on smaller screen sizes. 

I'm going to rebuild them so they utlize less code and are more cohesive amongst all screen sizes. 

https://cloudup.com/iJaWz-1RTtQ

**Comment by jeffgolenski** [comment]
This also needs improving: https://cloudup.com/cLDowvYuxGQ

**Comment by dereksmart** [comment]
As discussed in Slack, I'm here to leave reminder here about this inline CSS

a5d57deb765944f207edc6c1c2482a43ede21101

**Comment by dereksmart** [comment]
Also this one 8c215ee700967aff3abb6318be1393851e198a0d

**Comment by justinkropp** [comment]
I've started some initial exploration of these CTA banners and how we might clean these up across DOPS and make them a bit more flexible and succinct. The current banners have a lot going on:

* background colors
* background images
* buttons the same color as the background and with type that's too large

I'd like to take a departure from this and make these and future cta banners consistent across the board. If we need to brand the banner, let's do so with the product's logo. Let's keep the action button the same color and position on every banner; this way the user knows that that button on every banner always executes the action they need/shoudl take.

On this approach, the product logos are always the WP alert red until the user takes the approriate action. The success banners contain updated logo colors (the color of the product's brand) and would be dismissed by the checkmark, which also acts as an icon to reinforce the success.

I'll post further exploration soon. Ideas and feedback are welcome.

![DOPS Alwert Banners](https://cloud.githubusercontent.com/assets/1461798/9017281/eba373ea-37a3-11e5-9003-589a860a5ca8.png)

**Comment by justinkropp** [comment]
The connection screen for Jetpack in wp-admin also needed some attention, as @jeffgolenski pointed out above. I think we can really improve this with a few small-ish visual changes:

- reduce any wasted vertical space by moving the _clouds_ up and removing the Jetpack logo from them
- reduce overall line-length
- remove the icon and bg-color from the button, and use our now standard button styles
- introduce a simple visual cue about what's about to happen (JP + WP)

![jetpack cta long](https://cloud.githubusercontent.com/assets/1461798/9062648/c0f2db54-3a91-11e5-9f81-efeb75f9e117.png)

**Comment by beaulebens** [comment]
I like the consistency update, although the all-red logos feel a bit weird. Seems like we could just use the "normal" logos for each product and it'd still get the consistency you're after.

Note that the connection flow/screen recently got an overhaul, so it already looks different (same as the WP.com OAuth flow):

<img width="552" alt="screen shot 2015-08-04 at 2 37 12 pm" src="https://cloud.githubusercontent.com/assets/108942/9072084/51ac04bc-3ab6-11e5-96d1-82ff10cbabae.png">

**Comment by jeffgolenski** [comment]
@justinkropp Thanks for stepping in to create a new solution to these. I really appreciate it. 

*1) CTA banners*

I really really dig the simplicity and parity of these CTAs. Consistent and way more lightweight than what we currently have. I foresee a great reduction of code from our current banners to these, and I can always appreciate a kb saved. :-D

With that being said, I don't think altering the colors of the brandmarks to signify different message statuses is the best idea. 

**Reasons being:**
A) I think a user would have to be pretty well versed (and very detail oriented) to notice a change between the jetpack green logo and it changing to red. I actually had to look twice and turn up the brightness to notice it on my macbook. I doubt new users would be able to make the distinction at all. They'd probably blow it off.

Also, the VaultPress logo is red to begin with. So if a user has JP, VP, and more installed, it just leaves room for more confusion.

B) Color blind / visual impaired users won't be able to notice the CTA if we're strictly switching between colors. Keeping accessibility in mind, we need to offer more than just color as an indicator to grab the users' attention.

Perhaps we could work in an addition... take what you've done with the checkmarks, but include the other various warning symbols, like on wpcom:

<img width="797" alt="screen shot 2015-08-04 at 4 55 22 pm" src="https://cloud.githubusercontent.com/assets/214813/9072542/c9655090-3ac9-11e5-9c20-fdf0648a8d5e.png">



**2) Connection screen**

Looking much better than what we currently have. The visual relationship you present with the JP & WP logos, I think, is paramount. It's a great transition from the Jetpack dash to the actual connect page that @richardmuscat whipped up:

<img width="1023" alt="screen shot 2015-08-04 at 4 35 01 pm" src="https://cloud.githubusercontent.com/assets/214813/9072061/f5610278-3ac6-11e5-97e4-4bb53aef343c.png">

I think we can certainly remove the Jetpack logo above the text in your rendition and let it breath a bit since the jetpack logo will be sitting in the header on this screen anyway.

@beaulebens Justin is referring to this screen here within the plugin:
<img width="1104" alt="screen shot 2015-08-04 at 4 43 08 pm" src="https://cloud.githubusercontent.com/assets/214813/9072223/fc9aac6e-3ac7-11e5-8c1c-7f3003748801.png">

**Comment by justinkropp** [comment]
@beau and @jeffgolenski Thanks for the feedback. Using the color of the logo to indicate message type was an idea; something to introduce an extra layer of "ah-ha" here. Totally agree with you here @jeffgolenski about issues in contrast and overall accessibility.

> Perhaps we could work in an addition... take what you've done with the checkmarks, but include the other various warning symbols, like on wpcom:

I could see this working for sure. However, perhaps it is worth simply exploring using the wpcom banners here as well. Do you feel those are too generic to use in the contexts above?

**Comment by jeffgolenski** [comment]
@justinkropp 

Totally down for the consistency with wpcom, so long as they remain unobtrusive. I think doing the full color background may be a bit much for the wp-admin dashboard. I also think we should be including the logos in some way though – that way users quickly know exactly which plugin wants them to do what.

**Comment by justinkropp** [comment]
@jeffgolenski 

> I think doing the full color background may be a bit much for the wp-admin dashboard. I also think we should be including the logos in some way though

Totally agree. I'll take another pass at these.

**Comment by justinkropp** [comment]
I took another stab on some CTA banners that could possible work across the board.

- they’re still branded (depending on the service)
- they’re similar to what we’re using in Calypso
- they include an action button (where necessary)
- like the ones in Calypso, they’d still work great if we drop the branding (cor more compact versions)

![cta banners](https://cloud.githubusercontent.com/assets/1461798/9136122/091edb38-3ce2-11e5-9826-fcb9fa46df27.png)

cc @jeffgolenski @richardmtl

**Comment by richardmtl** [comment]
wrong Richard! I think you meant @richardmuscat ! :)

**Comment by justinkropp** [comment]
@richardmtl Dangit! I've done this like 4 times already. Well, anyway... hi :wave: !

**Comment by jeffgolenski** [comment]
@justinkropp These are beautiful. Make it so!

**Comment by justinkropp** [comment]
@jeffgolenski :+1:

**Comment by richardmuscat** [comment]
@justinkropp these are looking lovely. 

Couple of things:
- I _really_ like the "Well done" on the success message! Can we have that on all three? Even just reading it on the screenshot made me feel good :-)
- For the Jetpack text, can we go with "Connect Jetpack to see site stats, protect your site from attacks, speed up images & photos, and more."

**Comment by justinkropp** [comment]
@richardmuscat For sure on both accounts. Thanks for the feedback.

**Comment by jeffgolenski** [comment]
This issues becomes irrelevant for 4.1 - all notices will be redesigned.
