### ISSUE TITLE
Clicking X to exit module description modal resets scroll position

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#2307]
To repro:

1. Visit Jetpack > Settings.
2. Scroll down a bit.
3. Click a module name to open the description modal.
4. Click the X in the upper-right to close the modal.

Your scroll position goes back to the top of the page, but ideally it should stay put?

**Comment by georgestephanis** [comment]
We need either an `event.preventDefault()` in the callback, or to change the link target to `a href="javascript:;"` instead
