### ISSUE TITLE
Search: Instant Search cannot be opened via filter class anymore

### ISSUE THREAD

**Issue by gin0115** [Automattic/jetpack#23091]
### Impacted plugin

Jetpack

### Steps to Reproduce

Using latest version

Enable Jetpack search on a website and add the link to open the modal as documented in https://jetpack.com/support/search/install-search-on-your-site/
```
<a href="#" class="wp-button jetpack-search-filter__link" style="width: 50px;height:46px; border-color: #c8d7e1; border-style: solid; border-width: 1px 1px 2px;">
    <svg style="fill: #2e4453;" class="gridicon gridicons-search" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g><path d="M21 19l-5.154-5.154C16.574 12.742 17 11.42 17 10c0-3.866-3.134-7-7-7s-7 3.134-7 7 3.134 7 7 7c1.42 0 2.742-.426 3.846-1.154L19 21l2-2zM5 10c0-2.757 2.243-5 5-5s5 2.243 5 5-2.243 5-5 5-5-2.243-5-5z"></path></g></svg>
</a>
```

### A clear and concise description of what you expected to happen.

When clicking a link with the `jetpack-search-filter__link` class, the modal should be revealed

### What actually happened

Nothing, but if you inspect the page you will see that is being triggered (both body and link attributes change, but instantly revert back to the current values).

If you look through the event listeners applied to the link, you will see there are 2. 
![image](https://user-images.githubusercontent.com/28779094/155569614-776de35a-b025-48ad-91ca-fde14625964d.png)
One on the link and one on the window. If you remove the event handler on the window itself, it will reveal and work as expected.

### Other information

After a brief chat with George Stephanis and Jeremy Herve, we concluded it's a bug in the current build as this can be seen on other sites we look after.

### Operating System

Linux

### OS Version

POP_OS 21.04

### Browser

Chrome/Chromium, Firefox

### Browser Version(s)

any

**Comment by bluefuton** [comment]
Thanks for the report @gin0115! 

This was a regression caused by https://github.com/Automattic/jetpack/pull/22690 and we have a fix ready for review in https://github.com/Automattic/jetpack/pull/23102.
