### ISSUE TITLE
Add Sharedaddy sharing buttons to Carousel

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#231]
Add the Sharedaddy sharing buttons to the Full-screen Carousel, as mentioned in these threads:

http://wordpress.org/support/topic/plugin-jetpack-by-wordpresscom-add-a-facebook-like-button-to-the-full-screen-carousel-view?replies=6
http://wordpress.org/support/topic/general-improvement-requests-for-jetpack-carousel?replies=1
http://wordpress.org/support/topic/sharing-on-individual-images?replies=1
http://wordpress.org/support/topic/adding-pin-button-to-carousel?replies=2

Ported from: https://plugins.trac.wordpress.org/ticket/1726

**Comment by richardmtl** [comment]
requested in 2366332-t

**Comment by csonnek** [comment]
Also #2367096-t

**Comment by oki87** [comment]
Hi there!

> Hi! I've been searching how I can add some share buttons to my images.
> I'm using the carousel, it's so beautiful, but I'd like to add the posibility of
> share in social networks.

We still have this as an open request:

https://github.com/Automattic/jetpack/issues/231

I've added your request to the issue!

Cheers,


Richard - Happiness Engineer
WordPress.com | Jetpack | Polldaddy | VaultPress

**Comment by oki87** [comment]
When are you going to give solution to this request? How difficult is it?? I believe that users requesting two years ago

**Comment by zinigor** [comment]
@oki87 we can't provide any estimate on if and when this issue will be resolved. You can see the issues that are being currently worked on in the 3.8 milestone. If you feel like this would be a valuable addition to Jetpack, we would really appreciate a pull request from you with the desired code changes. Thanks!

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/social-share-buttons-on-carousel?replies=2&view=all

**Comment by jenhooks** [comment]
Requested in 2586618-t

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/gallery-disable-comments-and-sharing-buttons?replies=1&view=all

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/sharing-buttons-carousel-single-view?replies=1&view=all

**Comment by iseulde** [comment]
Requested in 160764-chat.

**Comment by goblinartificer** [comment]
Requested in #13903215-hc

**Comment by dericleeyy** [comment]
Requested in #2168131-zd

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
