### ISSUE TITLE
Jetpack CLI - Command to Enable/Disable Dev Debug Mode

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#2310]
I recently discovered that jetpack is adding a wp-cli addon which is great. The one command I would love more then anything is the ability to enable or disable jetpack debug mode. The command might look like this:

`wp jetpack dev-debug --true`

`wp jetpack dev-debug --false`

**Comment by kraftbj** [comment]
Dev Mode is all code-activated currently (a PHP constant or a filter), so this would likely take a little reworking of dev mode. I can definitely see the usefulness.

**Comment by bhubbard** [comment]
Would it be possible to simply have the command add/editing the following line to the wp-config.php file? Simply changing the value to true or false? 

` define( 'JETPACK_DEV_DEBUG', true);`

` define( 'JETPACK_DEV_DEBUG', false);`

**Comment by dereksmart** [comment]
It's not that simple, trying to write to the wp-config file like that would be pretty tricky and kind of sketchy.  

I think the best way to do this would be to write a new DB option that would also trigger dev mode.  

I like the idea and will think on it for 3.7

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
