### ISSUE TITLE
My Jetpack: Footer Jetpack link links to nothing. Make it link to jetpack.com

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#23108]
![image](https://user-images.githubusercontent.com/746152/155698985-5e9f7325-2a54-4c90-9014-46c57ef264a5.png)

**Comment by leogermani** [comment]
You mean the Jetpack logo, right?

**Comment by oskosk** [comment]
> You mean the Jetpack logo, right?
Yes, the screenshot I used is misleading cause this issue and https://github.com/Automattic/jetpack/issues/23109 both came came from a single report in  p8oabR-Oy-p2#comment-6033
