### ISSUE TITLE
Enhancement: Don't send Monitor emails after a long period

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#23116]
### Impacted plugin

Jetpack

### What

Don't send Monitor emails after a long period

### How

I got a Monitor email that said "myexamplesite.com is now back online! It appeared offline or unresponsive for approximately 3 months, but everything is back to normal now."

1. It was not down, and especially not for 3 months.
2. And even if it *was* down for that long, it seems silly to send an email after that long, even if it *was* for real. Maybe you should not send these emails after, say, 3 weeks or something?

**Comment by jeherve** [comment]
Hey Richard, long time :) 

> It was not down, and especially not for 3 months.

It would be interesting to figure out what happened there. I wonder if you may have run into this bug: #11928 

Do you think you could contact us via email so we can figure that out together?

> it seems silly to send an email after that long, even if it was for real. Maybe you should not send these emails after, say, 3 weeks or something?

I could see that argument. On the other hand, I think the info may be useful, especially when folks don't pay too much attention to their sites, and miss the "down" emails. When they finally bring their site back up, the duration of the downtime may help them better understand the potential impact of that downtime.

I'll close this issue as "wontfix" for now. We can certainly reconsider if this comes up again in the future.
