### ISSUE TITLE
Related Posts: Add clear to the container

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2312]
If the element before RP floats without clearing itself, then RPs will rest on top of it preventing the cursor from being able to hit those targets.

Adding a clear to our container will allow us to not impede others who float without clearing.

cc: @jeffgolenski who I chatted with today about it.

**Comment by jeffgolenski** [comment]
Visual: 
![screen shot 2015-06-26 at 3 31 07 pm](https://cloud.githubusercontent.com/assets/214813/8385732/770a743a-1c18-11e5-9c53-d59240db7f0c.png)

Example: Without a clear: both; on the container of the related posts, the social media plugin above is floated to the left and not self clearing. Causes overlap and the social media buttons are not click / tappable.

**Comment by jeffgolenski** [comment]
Fixed in: https://github.com/Automattic/jetpack/pull/2317
