### ISSUE TITLE
Admin: module buttons crowd description text a bit

### ISSUE THREAD

**Issue by lancewillett** [Automattic/jetpack#2313]
Small layout fix. If module area is in flux, feel free to ignore and close this one.

On a phone (I tested with iPhone 6 and iPhone 6+) — or just a very narrow desktop browser window, when modules screen in wp-admin goes to one column (`wp-admin/admin.php?page=jetpack` is the URL) — you'll see that the text and button crowd each other a bit.

This can be fixed with a bit of CSS.

`
.configure .button,
.activate .button-primary {
	margin-top: 10px;
}
`

Before:
![screen shot 2015-06-25 at 13 49 03](https://cloud.githubusercontent.com/assets/66797/8365516/784d42ea-1b42-11e5-98c1-601ad1e25628.png)

After:
![screen shot 2015-06-25 at 13 44 22](https://cloud.githubusercontent.com/assets/66797/8365518/7ac40716-1b42-11e5-86e4-c0bb467a5841.png)

I didn't make a patch and PR because the SCSS seems to be in flux a bit right now. :)

**Comment by jeffgolenski** [comment]
Thanks @lancewillett 

Fixed in: https://github.com/Automattic/jetpack/pull/2319
