### ISSUE TITLE
Editor broken after adding a Post Carousel block to a Grid Layout block

### ISSUE THREAD

**Issue by Agepeuve** [Automattic/jetpack#23131]
### Impacted plugin

Jetpack

### Steps to Reproduce

1.- Add or edit a page or a post.
2.- Add a Grid Layout block.
3.- Select 2 or more columns.
4.- Add a Post Carousel block to the first column.

### A clear and concise description of what you expected to happen.

The Post Carousel block should only take the space of the first column as the rest of the blocks do. 

### What actually happened

The Post Carousel block takes the whole width of the editor so you won't be able to manage the blocks from the right columns.

### Other information

This issue only affects the editor. If you manage to add some content to the right column and publish the post/pages, both columns will look as they should in the live version.

### Browser

Chrome/Chromium, Firefox

**Comment by jeherve** [comment]
Neither the Post Carousel block nor the Grid Layout block are part of Jetpack, so I'm afraid we won't be able to help you with this. I'd recommend reporting this in the `[newspack-blocks](https://github.com/Automattic/newspack-blocks)` repo.
