### ISSUE TITLE
Related Posts Block: Angle picker control selection closes background pop-up

### ISSUE THREAD

**Issue by coder-karen** [Automattic/jetpack#23132]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Testing with the 10.7 Beta, add a Related Posts block (after enabling Related Posts from Jetpack > Settings > Traffic) and change the background color. 
2. Select gradient, and select Linear as the type. 
3. Try using the angle picker control to change the gradient angle.

### A clear and concise description of what you expected to happen.

The angle should change, and the background selection pop-up should remain.

### What actually happened

On clicking the angle picker control, the popup-up automatically closes.
This was reported here: p8oabR-Oy-p2#comment-6028
No obvious console errors are shown

### Other information

This demonstration was provided in the original report:
![gradient-block](https://user-images.githubusercontent.com/16754605/155959062-830278d9-22d6-46b5-8cef-7e4a2883f429.gif)

### Operating System

macOS

### OS Version

12.1

### Browser

Chrome/Chromium, Firefox, Safari

**Comment by jeherve** [comment]
I believe that interface is managed by Core itself (or Gutenberg if you have the plugin installed), so that's not something we'll be able to fix in Jetpack itself.

I believe that specific issue is mentioned here:
https://github.com/WordPress/gutenberg/issues/39104
