### ISSUE TITLE
Premium Content Block: Logged in user can't see content.

### ISSUE THREAD

**Issue by rcrdortiz** [Automattic/jetpack#23135]
### Impacted plugin

Jetpack

### Scenario 1: Premium Content isn't being shown.
1. Open a post that has a Premium Content Block.
2. Make sure you aren't subscribed to the Premium Content.
3. Press the login button.
4. Press the subscribe button.

### Scenario 2: No login feedback.
1. Open a post that has a Premium Content Block.
2. Click on the login button without having a subscription.

### Scenario 3: You can try to subscribe again.
1. Open a post that has a Premium Content Block.
2. Make sure you aren't subscribed to the Premium Content.
3. Press the subscribe button.
4. You will see that both the "Subscribe" and "Login" buttons are visible.
5. Click on the "Subscribe" button.

### Scenario 1: Premium Content isn't being shown.
After pressing the subscribe button, and completing the subscription to the Premium Content, I expected to see the Premium Content.

### Scenario 2: No login feedback.
After pressing the login button, and performing the login operation, I expected the login button to not be shown anymore.

### Scenario 3: You can try to subscribe again.
After subscribing, I expected to not be able to subscribe to the same Premium Content again.

### Scenario 1: Premium Content isn't being shown.
After subscribing, you see the same screen as if you didn't subscribe. You can see the subscribe button and the login button.

### Scenario 2: No login feedback.
In this case, nothing at all happened. The screen the user sees is exactly the same as if he didn't press the login button. The user is being redirected to the same URL, but it includes a token parameter. The token doesn't contain the required subscription in this case.

### Scenario 3: You can try to subscribe again.
In this case, the user is presented with the same screen again. The user will see both the "Subscribe" and "Login" buttons. If the user presses the "Subscribe" button he will see an error indicating that he is already subscribed.

### Other information

The main issue is that the underlying architecture isn't correctly updating the user subscription token. When a user subscribes to a Premium Content, the subscription window gets closed but we aren't triggering a token re-generation, therefore the user is forced to press the "Login" button, even if he is logged in, in order to get the updated subscriptions token. 
The other issue is that we are always showing the login button, even if the user is logged in, we could solve this by hiding the "Login" button when we have the necessary cookie set.

### Browser

Chrome/Chromium

### Environments
Simple and Atomic.

**Comment by dsas** [comment]
There's an ongoing discussion about this paYJgx-1Qi-p2

**Comment by DavidRothstein** [comment]
Scenario 1 seems related to this: 458-gh-Automattic/payments-shilling

**Comment by rcrdortiz** [comment]
> Scenario 1 seems related to this: 458-gh-Automattic/payments-shilling

When you fix 458-gh-Automattic/payments-shilling, scenarios 1 and 3 shouldn't be a thing anymore. Regarding scenario 2, it could also be fixed by 458-gh-Automattic/payments-shilling since, in the end, all these issues surface from the problem of how the token cookie is being handled.
We'll wait for your fix of 458-gh-Automattic/payments-shilling, and then re-evaluate the state of the block.

**Comment by DavidRothstein** [comment]
I mainly wanted to flag that issue as a possible duplicate -- but I think it would be OK for you to work on fixing it here if you want to (and close that one if necessary).

**Comment by rcrdortiz** [comment]
> I mainly wanted to flag that issue as a possible duplicate -- but I think it would be OK for you to work on fixing it here if you want to (and close that one if necessary).

Will do, thanks for the clarification.

**Comment by rw-ye** [comment]
I've closed 4789806-zd-woothemes. Please re-open a new ticket and follow up when a fix has been deployed.

**Comment by rcrdortiz** [comment]
> I've closed 4789806-zd-woothemes. Please re-open a new ticket and follow up when a fix has been deployed.
The ticket is now closed. I've tried creating a follow-up ticket, but for some reason, I wasn't able to do so.
