### ISSUE TITLE
Extra Sidebar Widgets: create a widget to show random posts

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#2316]
As suggested in 2240763-t, we could create a widget that lists random posts, with thumbnail support (like the Display Possts widget, maybe?); this widget could potentially use the Random Redirect theme tool.

**Comment by jeherve** [comment]
We should be able to do this with the filter I added in #2209 and a new `rand` option for `Get /sites/$site/posts/`. I mentioned this to +operationapi.

**Comment by dereksmart** [comment]
This sounds like a great community contribution, but no plans for core Jetpack team to implement this.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
