### ISSUE TITLE
Enhancement: Add filter to disable stats dashboard widget

### ISSUE THREAD

**Issue by davidsword** [Automattic/jetpack#23197]
### Impacted plugin

Jetpack

### What

Add filter to disable stats wp-admin dashboard widget

### How

There may be situations where a website owner wants stats on the front end of the site, but does not want the wp-admin stats dashboard widget on the backend, andor, wants to filter the backend stats widgets to not show under certain dynamic circumstances.

Disabling the dashboard widget programatically with `wp_dashboard_setup` is possible of course, but it's several lines of code. Ideally there'd be a single line of code and it would also prevent the execution of the stats widget registering and code running altogether.

https://github.com/Automattic/jetpack-production/blob/ab415a2b6c1acc79696f7ea08024252b236f22f0/class.jetpack.php#L737

https://github.com/Automattic/jetpack-production/blob/ab415a2b6c1acc79696f7ea08024252b236f22f0/class-jetpack-stats-dashboard-widget.php#L28

Maybe adding something like

```diff
+if ( apply_filters('jetpack_disabled_stats_dashboard_widget', false ) )
+    return;
```

Thanks in advance for the consideration!

**Comment by jeherve** [comment]
Thanks for the suggestion!

> does not want the wp-admin stats dashboard widget on the backend, andor, wants to filter the backend stats widgets to not show under certain dynamic circumstances.

Do you have more details about your goals there, and the kind of dynamic conditions you're interested in?

**Comment by jeherve** [comment]
Looking into this some more, I think there is a way to remove the widget that should be simple enough, and where one wouldn't have to play with the `$wp_meta_boxes` global directly:

```php
add_action( 'wp_dashboard_setup', function () {
	remove_meta_box( 'jetpack_summary_widget', 'dashboard', 'normal' );
} );
```

I believe this should be straightforward enough to be implemented, with extra logic if needed.
