### ISSUE TITLE
HTML inside a contact form

### ISSUE THREAD

**Issue by leandroprz** [Automattic/jetpack#232]
Hi,

On the recommendation of Richard regarding <a href="http://wordpress.org/support/topic/is-it-possible-to-add-html-inside-a-contact-form?replies=3#post-5251871">this post in the forum</a> I'm requesting a feature to add HTML inside a Jetpack contact form.

I'm asking this because I needed to add some HTML inside a form (in the shortcode) on my website, where people would click on a text or image and a pop-up with some text inside would open.

Would that be possible on future updates?

Thank you!

**Comment by jimmyandrade** [comment]
:+1:

**Comment by kraftbj** [comment]
I'm going to close this—not as a judgement of the value of the idea, but to reflect that it is not on our roadmap as an enhancement.
