### ISSUE TITLE
Sharing: Disable CSS but JS

### ISSUE THREAD

**Issue by mayeenulislam** [Automattic/jetpack#2321]
Jetpack Sharing icons are well designed. BTW some web layouts demands a newly crafted design there.

So what to do?

Settings > Sharing, and "check" the Advanced. If this option is checked, you must include these files in your theme manually for the sharing links to work. and design your own.

But actually I wanted to disable the CSS only, not the JS.

It would be better having two distinct options:

- Disable JS
- Disable CSS

Thank you.
(after posting in [Jetpack support forum](https://wordpress.org/support/topic/sharing-disable-css-but-js?replies=2#post-7117301))

**Comment by jeherve** [comment]
You can paste the following code in your theme's functions.php file, or in a <a href="https://wordpress.org/plugins/functionality/">functionality plugin</a>, to remove the CSS file only:

```php
// First, do not concatenate Jetpack CSS
add_filter( 'jetpack_implode_frontend_css', '__return_false' );

// Then, dequeue Jetpack's Sharedaddy CSS file
function jeherve_dequeue_sharedaddy_styles() {
        wp_dequeue_style( 'sharedaddy' );
}
add_action( 'wp_head', 'jeherve_dequeue_sharedaddy_styles', 2 );
```
