### ISSUE TITLE
S2.4 Change JP Debug tools to use new search endpoints instead of `jetpack/v4/settings`

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#23237]

**Comment by kangzj** [comment]
By leveraging the WPCOM API `/rest/v1.4/sites/{site-id}/settings`, this should be an easy fix. And 
- I think it is important for HE to see the status of search for sites.
- We should be able to address this before releasing

**Comment by kangzj** [comment]
WIP fix proposed via `D79469-code`.

**Comment by kangzj** [comment]
closed via shipping of `D79469-code`
