### ISSUE TITLE
Form Responses (Feedback) & Akismet: Option to auto-delete feedback spam

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/jetpack#23231]
### What

An option that allows sites to automatically delete contact form response / feedback spam.

Spam comments have auto-delete options but feedback spam does not.

### Why

Sites can accumulate thousands, sometimes millions, of feedback spam entries.

The current `Empty Spam` tool is quite slow, times out often, and makes removing this spam difficult.

**Comment by jeherve** [comment]
We do already have a daily cron task that is set to delete any spam feedback that is older than 100 days:
https://github.com/Automattic/jetpack/blob/8e0dff02179e33e6e7bf357a03e5c18abe2aa08c/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php#L3888-L3893
https://github.com/Automattic/jetpack/blob/8e0dff02179e33e6e7bf357a03e5c18abe2aa08c/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php#L3123-L3126

It would appear that cron tasks are not working on that site, thus causing the spam to keep piling up. Or, those 1.5 million feedback were all logged in less than 100 days. Either way, it may be worth looking into that I think, to ensure that in the future, spam gets deleted regularly.

**Comment by JoshuaGoode** [comment]
Awesome, thank you @jeherve 

I wasn't looking in the right places and missed that.

In this case, the cron job was working but the spam was accumulating rapidly.
