### ISSUE TITLE
Deprecate PHP4 Style Constructors

### ISSUE THREAD

**Issue by rleeson** [Automattic/jetpack#2323]
A recent update of WordPress core shows the PHP 4 compatible method of defining a widget using WP_Widget::WP_Widget( ... ) is being deprecated.  There are several Jetpack widget modules containing these backwards compatible calls:

modules/subscription.php - Line 567
modules/widgets/gallery.php - Line 26
modules/widgets/rsslinks-widget.php - Line 13

My local log is flooding with these errors, so I have locally converted them from $this->WP_Widget( ... ) to parent::__construct( ... ). 

If the intent is to remain PHP 4 compatible, then each of these calls could be wrapped in a PHP version check, otherwise, I suggest updating these to call the constructor directly.  Thanks!

**Comment by kraftbj** [comment]
This is being done for PHP 7 forward-looking compat. PHP 7 will throw a `E_DEPRECATED` (while still work) for the PHP4 method of constructing a class by using the function of the class name and then PHP 8 will remove that method completely.

Core change: https://core.trac.wordpress.org/changeset/32990
PHP change: https://wiki.php.net/rfc/remove_php4_constructors

In addition to the widgets, we need to audit the rest of the codebase for any other PHP4 style constructors.

Marking this as 3.6 (or punted to 3.6.1) so we can aim to be out before 4.3 ships.

**Comment by kraftbj** [comment]
Initial check: Files needing updated in plugin root.
o class.jetpack.php (Jetpack::Jetpack)
o class.jetpack-user-agent.php (Jetpack_User_Agent_Info::Jetpack_User_Agent_Info)
o class.jetpack-signautre.php (Jetpack_Signature::Jetpack_Signature)
o class.jetpack-ixr-client.php (Jetpack_IXR_Client::Jetpack_IXR_Client, Jetpack_IXR_ClientMulticall::Jetpack_IXR_ClientMulticall)

**Comment by georgestephanis** [comment]
Specified ^^'s and a couple others are fixed by #2324 -- I'd sooner hit them all in one go, so waiting until @kraftbj finishes an audit.

**Comment by kraftbj** [comment]
Nothing in json-endpoints.
- [ ] modules/notes.php (Jetpack_Notifications::Jetpack_Notifications)
- [ ] modules/subscriptions.php (Jetpack_Subscriptions::Jetpack_Subscriptions, Jetpack_Subscriptions_Widget::Jetpack_Subscriptions_Widget AND calls `$this->WP_Widget`)
- [ ] modules/custom-css/custom-css.php (safecss:safecss)
- [ ] sharedaddy/sharing-service.php (Sharing_Post_Total::Sharing_Post_Total, Sharing_Service_Total::Sharing_Service_Total)
- [ ] widgets/gallery.php (calls $this->WP_Widget)
- [ ] widgets/rsslinks-widget.php (Jetpack_RSS_Links_Widget::Jetpack_RSS_Links_Widget) AND calls $this->WP_Widget

**Comment by georgestephanis** [comment]
All of the above are rolled into #2324.

                               *It Is So Ordered.*

**Comment by chriscct7** [comment]
Note ```$this->WP_Widget()``` should be ```parent::__construct()```
