### ISSUE TITLE
Atomic: Akismet Anti-spam and Anti-spam items under Jetpack menu load the same page

### ISSUE THREAD

**Issue by zdenys** [Automattic/jetpack#23241]
### Quick summary

It seems that the Akismet Anti-spam plugin creates the related menu item under Jetpack and it loads the same content as Anti-spam menu item. On Atomic sites (WoA), Jetpack plugin and Akismet Anti-spam plugins are always active by default and cannot be deactivated by users. So seeing both items can be confusing.

![image](https://user-images.githubusercontent.com/39308239/154239303-9b44ece6-c339-4d9e-8ee8-52d0b4f17487.png)

### Steps to reproduce

Expand Jetpack menu in the dashboard of an Atomic (WoA) site

### What you expected to happen

See only one Anti-spam menu item (either Akismet Anti-spam or Anti-spam)

### What actually happened

Both Akismet Anti-spam and Anti-spam appear and they load the same content

### Context

Possibly related issue: Automattic/jetpack#22967 (and maybe even https://github.com/Automattic/wp-calypso/issues/53948)

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

No

### Browser, operating system and other notes

macOS Monterrey 12.2.1 with Chrome 98

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by jeherve** [comment]
cc @leogermani who worked on #22628. We may have to add special handling to `projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php`, or to the Admin UI package directly, to handle this.

**Comment by leogermani** [comment]
I'm gonna have a look at this today

**Comment by leogermani** [comment]
https://github.com/Automattic/jetpack/pull/23278 should fix it.

We were not experiencing this in our dev enviroments because Jetpack will only add the "Jetpack Anti-Spam" menu item if the purchase was made via Jetpack. Otherwise the Akismet plugin will move its menu item under the Jetpack menu by itself.

**Comment by samiff** [comment]
The next Jetpack version deployed to WoA sites (10.8-a.3) should include the fix and will likely happen next Tue/Wed.
