### ISSUE TITLE
S2.7 Add standalone plugin to Plugin Directory to allow installation

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#23240]
Requisite assets:

- [x] Listing copy
- [x] Listing images

Requisite processes:

- [ ] Figure out the path for the release file.

**Comment by jsnmoon** [comment]
Posted a marketing request for plugin directory listing. See pbNhbs-2sJ-p2

**Comment by bluefuton** [comment]
@kraftbj has kindly prepared the plugin repo for us: https://plugins.trac.wordpress.org/browser/jetpack-search

**Comment by bluefuton** [comment]
Shipped! 🚢 

https://wordpress.org/plugins/jetpack-search/
