### ISSUE TITLE
My Jetpack: Adding Backup when Jetpack is present fails with a redirection to page=jetpack-backup

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#23252]
Adding Backup when Jetpack is present fails with a redirection to `admin.php?page=jetpack-backup`

1. Have a site connected with Jetpack 
2. Visit My Jetpack
3. Attempt to add Backup
4. Expect it to fail

**Comment by leogermani** [comment]
I could not reproduce this issue with the provided instructions. It worked just fine for me.

Did you mean the flow when there is not a user connection?

**Comment by oskosk** [comment]
I just got the same behaviour 

<img width="832" alt="image" src="https://user-images.githubusercontent.com/746152/157237501-3ae32e9c-b207-4cd8-b244-76e9140418be.png">
This is the combination of plugins in place

<img width="1572" alt="image" src="https://user-images.githubusercontent.com/746152/157237562-e92e45a7-2a1d-4747-9287-2b9335d6107c.png">

![backup](https://user-images.githubusercontent.com/746152/157237820-f5acd42a-d730-4b36-829c-c186c5c59de9.gif)

This seems to be the response for the background request when clicking the interstitial button

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/746152/157238052-eb8a462c-9752-4617-957c-443dbbceee5d.png">
