### ISSUE TITLE
Tools: Check for proper php extension

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#23254]
### Impacted plugin

None / Other

### What

Our `check-development-environment.sh`, monorepo installer, quick start docs, etc, should indicate the required PHP modules

### How

p1646423074599069-slack-CDLH4C1UZ

We need, as reported, `mbstring and xml/simplexml`. I think this may be automatically included in the `brew` PHP package that is installed, but for those on Linux or other systems where the packages provided may not include some "default" PHP extensions, we should still check for them.

**Comment by singerb** [comment]
It was reported as `simplexml` that was missing, but the install ended up doing all the `xml` extensions.
