### ISSUE TITLE
My Jetpack: Improve the resolution of the logos used in the Connection Screen footer

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#23256]
The ones introduced in #23036 are not so good

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/746152/156840834-7d12767f-5b1e-4f05-866f-512fb79a2757.png">

**Comment by jeherve** [comment]
We do have an existing Google logo here:
https://github.com/Automattic/jetpack/blob/6986d984959c80351fdd69e967571ffde07f2175/projects/plugins/jetpack/extensions/shared/icons.js#L252-L258

**Comment by oskosk** [comment]
@renatoagds can you handle Jeremy’s observation?

**Comment by renatoagds** [comment]
@oskosk yes, I could do it

**Comment by renatoagds** [comment]
For now, I just pushed new logos there at #23639 ...

Opened a new issue to create an `Icon` component at `jetpack-components` and push back @jeherve suggestion: https://github.com/Automattic/jetpack/projects/38#card-79693485
