### ISSUE TITLE
Adjust site icon to work with 4.3

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2326]
WP 4.3 is adding a site icon ( https://core.trac.wordpress.org/changeset/32994 ) feature that is based on our feature, plus media modal support.

From the changeset:
> For now, the core-provided icons will be limited to a favicon, an iOS app icon, and a Windows tile icon, leaving .ico support and additional icons to plugins to add.

We should at least detect when core's feature is being active and not double-output Core. If we're providing more than Core, we should still work.

**Comment by kraftbj** [comment]
Initial attempt at using both side by side on the homepage:
Core outputs
`<link rel="icon" href="xxx" />` -- favicon in 32x32
`<link rel="apple-touch-icon-precomposed" href="xxx">` -- apple icon at 180x180
`<meta name="msapplication-TileImage" content="">` -- microsoft icon at 270x270

JP duplicates all three, with Core being superior in my opinion.
1. favicon is outputting a 50x50 png, but specified 32x32
2. apple-touch at 150x150
3. microsoft at 150x150

Ideas:
1. When 4.3 detected gracefully migrate the user to core's module? 
1a. Keep us around for adding new sizes at any point?
1b. Deactivate us and rely only core?

Unknown: Tying into pulling the site icon for wp.com management, etc

**Comment by georgestephanis** [comment]
This is a bit late for 3.6, but I wouldn't mind if some of it made its way into 3.6.1

**Comment by kraftbj** [comment]
Noting that a 192x192 size should be outputted. Core ticket: https://core.trac.wordpress.org/ticket/32964 If Core doesn't adopt this for 4.3, could be our trial run of the Site Icon module's future of adding in newer/additional sizes to Core's functionality.
