### ISSUE TITLE
Jetpack Cloud: Add new question to Pricing page

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#23269]
Add a new question in the Q&A section of the pricing page with a link to the Getting started documentation. (Design)

Viewable under cloud.jetpack.com/pricing

![image](https://user-images.githubusercontent.com/746152/155844568-a6557d63-3bf3-4079-a23d-0884633072a9.png)

**Comment by jeherve** [comment]
This may be best reported in the Calypso repo, where the Cloud features are being built?

**Comment by oskosk** [comment]
I'm leaving it here so it is part of the https://github.com/Automattic/jetpack/projects/39 project and then the PR is there in Calypso indeed. https://github.com/Automattic/wp-calypso/pull/61691
