### ISSUE TITLE
Jetpack Cloud: Add new links at the bottom of the alert view.

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#23270]
For the “Troubleshooting tips” and “Fix connection issues” documentation:
(Design)

Viewable under cloud.jetpack.com/settings

pcKp4R-9E-p2

![image](https://user-images.githubusercontent.com/746152/155844588-26032828-db16-448a-abfc-68d19f0f47cd.png)

**Comment by jeherve** [comment]
This may be best reported in the Calypso repo, where the Cloud features are being built?
