### ISSUE TITLE
Facebook Embeds: Support Videos

### ISSUE THREAD

**Issue by vanndigitalnetworks** [Automattic/jetpack#2329]
I'm loving the Shortcode Embeds tool. But I noticed it don't work for Facebook videos. It'll be nice if you can add that feature.

https://wordpress.org/plugins/jetpack/

**Comment by georgestephanis** [comment]
cc: @codebykat?

**Comment by jeherve** [comment]
Facebook Videos will be handled as of Jetpack 3.6 (see ccdf332d720cbb94ac65e7bde1cc2230bafec48f ).

If you'd like to give it a try today, you can install the Beta Tester plugin:
http://jetpack.me/beta/
