### ISSUE TITLE
Subscription Widget: Hide form field after submit

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#233]
Currently, when subscribing to a site via the widget, upon submit, the form field remains visible with the pending confirmation text above it.

It would reduce confusion to hide the form field as a further visual indicator that the subscription request was received. 

Originally suggested in 1765280-t

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/problems-with-jetpack-blog-subscriptions-widget?replies=1

@DustinHartzler Who worked on the patch? Could you ask them to submit a PR here?
