### ISSUE TITLE
Shortlinks not working for custom poet type

### ISSUE THREAD

**Issue by moutushi82** [Automattic/jetpack#23302]
### Impacted plugin

Jetpack

### Steps to Reproduce

We have added code according to https://jetpack.com/support/wp-me-shortlinks/. But shortlinks are showing for custom post type.

### Browser

Chrome/Chromium, Firefox

**Comment by jeherve** [comment]
Could you contact us via [this support form](https://jetpack.com/contact-support/?rel=support&hpi=1) and tell us more about your site as well as the exact code snippet you used? We'll do our best to help you get this to work.

Thank you.
