### ISSUE TITLE
Mailchimp: Add option to collect names

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/jetpack#23343]
### What

It would improve the block if users could collect a subscriber's first name and last name, in addition to email address. 

### Why

The block is extremely minimal at the moment. Although one can collect all sorts of information through Mailchimp, our block only allows the collection of an email address. A WordPress.com user during a chat said that adding a name to their emails could improve deliverability, as they found that emails without a name in the "To" field were bouncing back when sent to several different email providers, such as Yahoo.

In lieu of that, they asked if we could whitelist Mailchimp form code in the same way we whitelist certain Google embeds, such as maps and calendars.

chat: 34251055-hc

**Comment by Gustavo-Hilario** [comment]
The user on 4857954-zd would also benefit from this possible enhancement.

**Comment by cuemarie** [comment]
There's also an open issue for this here: https://github.com/Automattic/jetpack/issues/14829 that is a bit stale.

This seems like it'd be a great win! Had this same request here: 35200337-hc

The workaround here is to build the form with Mailchimp's HTML form creator instead, but then stylizing that can be more difficult (requires adding CSS). This would be a great change to see in the future!

**Comment by jeherve** [comment]
> There's also an open issue for this here: https://github.com/Automattic/jetpack/issues/14829 that is a bit stale.

Good catch. I'll close this one as duplicate.
