### ISSUE TITLE
VideoPress: update module description to remove link to VideoPress subscription

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2335]
You can't purchase VideoPress subscriptions anymore. We'll need to remove that link and replace it with a link to the WordPress.com Premium plans.

**Comment by aheckler** [comment]
I seem to be able to purchase standalone VideoPress. I followed what I assume to be the usual flow:

1. Activate JP's VideoPress module, click Configure link.
2. Click the "VideoPress subscription" link to: http://store.wordpress.com/premium-upgrades/videopress/
3. Hover over Get VideoPress button at bottom and choose a site.
4. Taken to this screen: https://d.pr/i/1eGaU/VlwfpMCf
5. Click Purchase.

Seems to give me a standalone VideoPress upgrade.

**Comment by jeherve** [comment]
> Hover over Get VideoPress button at bottom and choose a site.

I don't seem to get that option on my end, with an account created in 2015. Nothing appears on hover, and clicking brings me to wordpress.com/plans/

Looking at your screenshot, I see your site is linked to an old account, that still has access to the wp-admin store. That's not the case for everyone.

**Comment by jeherve** [comment]
Reopening, as this is still an issue.

**Comment by samhotchkiss** [comment]
This was closed because VideoPress is being rebuilt, which will address.  I've switched the milestone, so that you can keep visibility on it.

**Comment by dbtlr** [comment]
This is effectively solved by #5326
