### ISSUE TITLE
Shortlinks not working for custom post type

### ISSUE THREAD

**Issue by moutushi82** [Automattic/jetpack#23351]
### Impacted plugin

Jetpack

### Steps to Reproduce

I've followed following instruction from https://jetpack.com/support/wp-me-shortlinks/ to enable shortlinks for custom post type. But shortlinks not showing for custom post type.

### Browser

Chrome/Chromium, Firefox

**Comment by jeherve** [comment]
It seems you've already submitted a similar issue in #23302. Do you think you could contact us via [this contact form](https://jetpack.com/contact-support/?rel=support&hpi=1) instead of here on GitHub, so we can better understand why this is not working on your site?

Thank you.
