### ISSUE TITLE
VideoPress: display the list of connected WordPress.com sites automatically

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2336]
Steps to reproduce:
1. Connect your site to your WordPress.com account
2. Go to WordPress.com and purchase a WordPress.com Premium plan for one of your WordPress.com sites.
3. Go back to your Jetpack site, go to Jetpack > Settings, click on Configure next to the VideoPress module.
   - The WordPress.com site isn't displayed there, I need to click on "Click Here" to refresh the list.

It'd be nice if that list were refreshed when the page is first loaded.

**Comment by dbtlr** [comment]
This functionality is deprecated as of #5326
