### ISSUE TITLE
VideoPress: remove unnecessary options from configuration screen

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2337]
VideoPress [got a refresh](https://en.blog.wordpress.com/2015/07/01/videopress-next/), and some of the options in the VideoPress configuration screen are not useful anymore. We will need to remove them.

**Comment by dereksmart** [comment]
Let's take care of this in 3.7 along with the rest of the VP changes

**Comment by dbtlr** [comment]
This is effectively fixed in #5500
