### ISSUE TITLE
VideoPress: remove branding from VideoPress player

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2338]
[VideoPress got a nice reboot](https://en.blog.wordpress.com/2015/07/01/videopress-next/), but somehow the player is still branded in Jetpack. We'd need to remove that VideoPress logo.

![screen shot 2015-07-02 at 3 37 59 pm](https://cloud.githubusercontent.com/assets/426388/8478252/77a06c26-20d0-11e5-873e-f88f93eae334.png)

Related: #2208

**Comment by kraftbj** [comment]
I think our shortcode is still loading the old player embedded with JP.

**Comment by jeherve** [comment]
Closing, since that's because the new player hasn't made its way to Jetpack just yet.
