### ISSUE TITLE
Omnisearch: include content from Text widgets

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2339]
It would be nice if Omnisearch could search the content of text widgets as well.

**Comment by georgestephanis** [comment]
As in find me a widget that contains blergh?

**Comment by jeherve** [comment]
For example yes. Searching inside the content of each Text Widget and returns a list of widgets containing the string we're searching for.

P.S.: I'm just forwarding a request from a user, so I'll let them comment here if they want to give us more details. :)

**Comment by georgestephanis** [comment]
It feels like something that would be better as a standalone separate plugin to add that functionality to Omnisearch.  I'm certainly willing to have discussion as to why it may be a worthwhile inclusion to core, but I'm not feeling it at the moment.

**Comment by dereksmart** [comment]
I agree with George.  The power of Omnisearch comes from the fact that there could be tens or hundreds of posts, pages, etc.  Doesn't feel worth adding extra UI to the core plugin for a few extra text widgets.

**Comment by kraftbj** [comment]
Closing this as wontfix for now, but if there is more need for something like this, please do comment here and we can always re-evaluate.
