### ISSUE TITLE
Search: Button Appears in Arbitrary Location in Search Modal 

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/jetpack#23401]
### Impacted plugin
Jetpack

### Steps to Reproduce

The search modal form has a search submit hidden by default that shows on :focus, but not in any clear location.

The DOM order of buttons is Clear, Search, Close; but the 'Search' button is only visible on focus.

To see it:
1. Start on jetpack.com/support.
2. Type into the search modal.
3. Tab twice.

There is a hidden `Search` submit button that appears.

![CleanShot 2022-03-11 at 17 19 53](https://user-images.githubusercontent.com/42279181/157994962-cea723e4-3521-4454-80f4-14e4c179ea7f.gif)

**Comment by kangzj** [comment]
Hi @katiebethbrown 

Thanks for reporting this, I can confirm this is a bug. 

The button is intended for screen reader, but shown somehow with the focus status. We'll schedule a fix.

https://github.com/Automattic/jetpack/blob/212b4d7bc0ab2be67b0ed7347f6496454e390052/projects/packages/search/src/instant-search/components/search-box.jsx#L65

Cheers.
