### ISSUE TITLE
Payment Button Block: Turn it into an inline block

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#23418]
### Impacted plugin

Jetpack

### What

Convert the Payment Button block from full-width to inline

### How

Convert the Payment Button block from full-width to inline so that it can be grouped in line with other Payment Button blocks.

**Comment by Copons** [comment]
@dsas Brilliant work, you made it look so... straightforward! :trollface: 😄 

Changing the current block's name gives me pause.
I'm a bit conflicted on this so let me brainstorm a little.

- ✅ Having a single button with a plural name makes it confusing.
- ❌ Although it's not user-facing, so ultimately who cares.
- ✅ The deprecation strategy would be kind of upside down, with the container being responsible for migrating what once was the single button.
- ❌ Although, we could argue that the current button _is_ a container (of JP Button).
- ❔ Is there a case for letting users insert the (child) button block by itself?

**Comment by dsas** [comment]
There's no problem with not changing the name btw, we'd need a new block for the  container instead and would move some of the `recurring-payments` logic there. That just means the child block does the migration of wrapping itself in a container.

I think it's much of a muchness really. Particularly if we put both blocks in the same top level directory.

**Comment by Copons** [comment]
> it's much of a muchness

@dsas I guess you're right. 😄 
Please go ahead with this!

**Comment by dsas** [comment]
So [we're just going to put it inside a row block](https://github.com/Automattic/jetpack/pull/23486#issuecomment-1084773415)..
