### ISSUE TITLE
Payments Block: Add the Single Product pattern

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#23422]
### Impacted plugin

Jetpack

### What

Payment patterns should be suggested by the Payments intro block!

The payments intro block currently suggests payment blocks to be inserted using Gutenberg, it looks like this:
![image](https://user-images.githubusercontent.com/93301/165191456-ba10756a-39af-4694-bda0-c8e1cac2925b.png)

Clicking one of the icons replaces the 'selector' with that block.

You can see a video here pd8D2H-1cl-p2 with links to some background info

Currently there's one pattern, with plans to add another very soon (see https://github.com/Automattic/jetpack/issues/25037), we'd hope in future that there'd be some more.

### How

Unsure, some possibilities:

 * Each pattern could be just another item in the list
   * Do users care whether something is a pattern or a block?
   * Patterns don't have icons so it might look weird
 * Another row or column for patterns?
 * Something else?

**Comment by Copons** [comment]
Note: ask design for pointers on how to integrate patterns into the Payments intro block.

**Comment by dsas** [comment]
@SaxonF, please could we have some design input on how we could add patterns to the existing blocks that can be inserted from the Payments Gutenberg block? There's some context on the issue above. Please let me/Ajax know if you need more context.

**Comment by SaxonF** [comment]
Have we explored other alternatives? I wonder if we could make use of the existing pattern inserter so that it feels a little more native and maintainable? e.g. could we open the pattern inserter with a search term preset so payment patterns show up?

**Comment by Copons** [comment]
> Have we explored other alternatives? I wonder if we could make use of the existing pattern inserter so that it feels a little more native and maintainable? e.g. could we open the pattern inserter via a link with a search term preset so payment patterns show up?

@SaxonF I just gave a look at how the inserter is handled.

We can easily open it, but can't navigate to the Patterns tab, which is handled by the panel's internal state.
I haven't checked if there's a way to programmatically search, because AFAICS pattern categories are not considered by the search. 🤔  (e.g. if you search for `earn`, the "Single Product" pattern doesn't show up).

But, we _could_ integrate in the Payments intro block the same list component used by the inserter ([`BlockPatternList`](https://github.com/WordPress/gutenberg/blob/b99e6688fba7037ccee46cb6b7d70917a5f2c418/packages/block-editor/src/components/block-patterns-list/index.js#L69)), and only provision it with either only the patterns belonging to, say, the Earn category, or even a hardcoded list of patterns if we need maximum control.

**Comment by SaxonF** [comment]
> But, we could integrate in the Payments intro block the same list component used by the inserter ([BlockPatternList](https://github.com/WordPress/gutenberg/blob/b99e6688fba7037ccee46cb6b7d70917a5f2c418/packages/block-editor/src/components/block-patterns-list/index.js#L69)), and only provision it with either only the patterns belonging to, say, the Earn category, or even a hardcoded list of patterns if we need maximum control.

Sorry for the delayed responses @Copons . I was reminded of the query block today which uses a very similar pattern that we can re-use.


https://user-images.githubusercontent.com/1072756/167568163-c8ebc81b-a19e-4e51-b8a4-72e7b3701b90.mp4

**Comment by Copons** [comment]
Thanks @SaxonF! Somehow I marked this notification as read and just noticed it now.
That's nice indeed, and could be quite a simple addition to the intro block!

Off the top of my head, I would probably do something like this:
<img width="682" alt="Screenshot 2022-05-20 at 13 35 59" src="https://user-images.githubusercontent.com/2070010/169529359-dc47ab71-92eb-49ba-aecb-6499f86db20d.png">

**Comment by dsas** [comment]
I think I'll try inverting that, patterns first then blocks. I think otherwise, with blocks having icons, not being hidden behind a click, taking up more screen estate and being presented first, that barely anyone will use the pattern selector. 

Something like:
![image](https://user-images.githubusercontent.com/93301/175542689-e5c47d87-2d7c-496c-8663-7a9a01351d79.png)

(pretend it's the right kind of button and I didn't mess up the font sizes, colours etc)


I'm still uncomfortable with the wording - 'pattern' in Gutenberg is currently inadequately explained jargon for a hidden concept, but I assume this will be addressed in Core at some point.

**Comment by dsas** [comment]
The [`BlockVariationPicker` block editor component](https://github.com/WordPress/gutenberg/blob/9df736c678b2e8ef00c355e6cc9fb8092fe25484/packages/block-editor/src/components/block-variation-picker/index.js#L26) really wants to be the whole dialog:
![image](https://user-images.githubusercontent.com/93301/175563077-1eec5322-237b-4889-952e-2b37e1fef5f5.png)
 

I can't adjust the Gutenberg component to act how I want, as we can't use it in Jetpack until the change has made it to WP-1. Other options are:
 * Forgo using `BlockVariationPicker`, copy and paste the [bits I need](https://github.com/WordPress/gutenberg/blob/9df736c678b2e8ef00c355e6cc9fb8092fe25484/packages/block-editor/src/components/block-variation-picker/index.js#L37-L60) into Jetpack and leave an apologetic comment
 * Ship some CSS which will display:none the bits I don't want
