### ISSUE TITLE
Payment Blocks: Full Tracks audit

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#23423]
### Impacted plugin

Jetpack

### What

Let's double check if we our tracking game is up for the challenge.

### How

Full Tracks audit on the Payment Button block and on (Core Gutenberg) patterns.

**Comment by dsas** [comment]
Kinda related, I just found that there are premium-content tracks event in calypso [`wpcom_block_premium_content_stripe_connect_click`](https://github.com/Automattic/wp-calypso/blob/fb55dd173718474002a6204905974f2d9a669314/apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-premium-content-stripe-connect.js#L12) along with [`wpcom_block_premium_content_plan_upgrade_click`](https://github.com/Automattic/wp-calypso/blob/fb55dd173718474002a6204905974f2d9a669314/apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-premium-content-plan-upgrade.js#L12) which were added in https://github.com/Automattic/wp-calypso/pull/42734 Looking in tracks, it doesn't look like these get fired?

**Comment by dsas** [comment]
We just have one event triggered specifically by the payment button block:

 jetpack_editor_block_stripe_connect_click via  `StripeNudge` and `StripeConnectToolbarButton`. It measures use of the 'Connect stripe' button and has a `block` property, for the type of block that the event was triggered on

jetpack_editor_block_upgrade_click via `withUpgradeBanner`. It measures use of the plan upgrade nudge and has a `block` property, for the type of block that the nudge was clicked on.

There are other relevant gutenberg tracking events
 * wpcom_block_inserted triggered when a block is inserted 
   * filter on the `block_name` property to relevant values
   * use the `pattern_name` property to see if the block was inserted via a pattern
   * use the `insert_method` property to see how the block was inserted - quick inserter, payments intro etc
 *  wpcom_block_publish triggered when a block is inserted - filter on the `block_name` property to relevant values
 * `wpcom_memberships_product_create` creation of a new payment plan

We could add:
 * New property to `wpcom_memberships_product_create` to show which product is triggering the addition of a plan 
 * Probably the same new property added to `wpcom_memberships_product_update`
 * It'd be good to compare the publish rate of payments blocks added via a donations pattern vs the donations form block, which isn't possible at present.

**Comment by dsas** [comment]
@Copons, unsure if this is the kind of thing you wanted.

**Comment by Copons** [comment]
Yes, thanks for looking into this @dsas!

AFAICS the `wpcom_memberships_product_create` and `_update` events satisfy most of our needs. 🤔 

I was actually thinking of adding a product creation event on the management component, but that seems unnecessary, given we track all the things from the back end.

> New property to wpcom_memberships_product_create to show which product is triggering the addition of a plan

Could you clarify "product"? As in, whether it's a block (and which block) or the Calypso Earn screen?
It sounds like a nice addition, although it would require modifying Calypso, JP, and WPCOM, which might need to be scoped out appropriately — i.e. it's not a _quick win_ but likely quite valuable!

@sethmclellana8c do you have opinions on this?
Is there anything else you'd love to track?

> It'd be good to compare the publish rate of payments blocks added via a donations pattern vs the donations form block, which isn't possible at present.

This would be great but I kind of don't think it would be possible. 🤔 
Patterns are just collections of blocks; once they are inserted there is no way (AFAIK) of knowing they were once a pattern.
Although the block insert event has a `pattern_name` property, so we could somehow "funnel" it.

**Comment by dsas** [comment]
> Could you clarify "product"? As in, whether it's a block (and which block) or the Calypso Earn screen?

Yes - and ideally, if the Earn screen, then which card the user clicked through from. Not possible at present, unless we could do it via a funnel.

**Comment by Copons** [comment]
I think we are good here, as any improvement is probably too expensive for its worth.
We can easily proceed with follow up tasks if we determine the need of tracking anything more in detail.
Thanks again @dsas for taking a look at this! ✨
