### ISSUE TITLE
"Gravatar Hovercards" module causes fatal error without internet connection

### ISSUE THREAD

**Issue by odie2** [Automattic/jetpack#2344]
Hi,
I had no internet connection by some days and I prepared localhost work for myself.
I was thinking why my JavaScript is completely stuck after page reload, so I checked developer console and discovered following:
![jetpack1](https://cloud.githubusercontent.com/assets/9401878/8499427/2682733e-2193-11e5-97df-9be34f72b4e9.jpg)

When I switch off "Gravatar Hovercards" module, everything works fine.

I don't think that is hard to fix, so it would be nice to have it fixed for future.

Greetings

**Comment by georgestephanis** [comment]
Yeah, we should test for Gravatar being defined, else cut out.
