### ISSUE TITLE
Premium Content Block: "Add subscription" doesn't open the sidebar on non-post editors

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#23443]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Test on a WordPress.com site with a business plan.
2. Open the site editor.
3. Insert the Premium Content block.
4. Make sure the block sidebar is closed.
5. Click on the subscriptions toolbar control.
6. Click on "Add a new subscription".

<img width="534" alt="Screenshot 2022-03-15 at 12 04 27" src="https://user-images.githubusercontent.com/2070010/158374080-5ad0d3b9-4eee-405f-98ad-5ff538d62989.png">

### A clear and concise description of what you expected to happen.

The block sidebar opens, focused on the new subscription name field.

### What actually happened

The sidebar didn't open.

### Other information

This happens because all different editor variations have their own sidebar name, and Premium Content only targets the post editor's one.

- Post: `edit-post/block`
- Site: `edit-site/block-inspector`
- Widget: `edit-widgets/block-inspector`

The tricky part is that IIRC there's no unified way to know that: `isEditorSidebarOpened` only exists on the post editor, site and widget editors have to come up with their own creative ways.

### Browser

Other / Not applicable

**Comment by dsas** [comment]
I thought the 'Show more settings' toolbar button might have a common implementation, but it has separate implementations for [widget](https://github.com/WordPress/gutenberg/blob/dfd422aade64a4df89b7f6d07c600d0d609bd040/packages/customize-widgets/src/components/block-inspector-button/index.js#L10), [post](https://github.com/WordPress/gutenberg/blob/45c37fb521922b892d4926e90759d3cf674a107d/packages/edit-post/src/components/visual-editor/block-inspector-button.js#L26) and [site editing](https://github.com/WordPress/gutenberg/blob/0ef399d6da5a357c27a9de8665d7e2ec34eb72bc/packages/edit-site/src/components/block-editor/block-inspector-button.js#L26)
