### ISSUE TITLE
SSO: Wrong CTA on user profile page when unlinked 

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#2345]
Currently you'll see this CTA on your profile page if your user account is unlinked: 

https://cloudup.com/cuOs4PfBuIL

Clicking that will give you an missing_token error.  

It should be the same flow as PBE: 
https://cloudup.com/cvvs8-W8slt

**Comment by georgestephanis** [comment]
missing_token?  That sounds like a site specific bug.

**Comment by dereksmart** [comment]
I don't think so - https://github.com/Automattic/jetpack/blob/1cb8b0a0ab0e2e2b826c62a3ec48de62692398be/class.jetpack-client.php#L33

since the user isn't connected, they don't have a token.

**Comment by jeherve** [comment]
Closing as duplicate of #1216
