### ISSUE TITLE
Publicize error after update - paragraphs and text input not working as expected

### ISSUE THREAD

**Issue by StefMattana** [Automattic/jetpack#23462]
### Impacted plugin

Jetpack

### Steps to Reproduce

Posting for a user reporting this in the forum

>After the latest update, the text input in custom message for Facebook and Twitter in post editor is deleting any line breaks. When you save the post, the line breaks disappear and the text shows in one continuous line. That’s how it gets published to given social media.

There are images attached as examples in the forum thread: https://wordpress.org/support/topic/publicize-error-after-update/

Was using the Classic Editor. Can't reproduce by using the Block Editor

Another similar example in #4851006-zen, always by using the Classic Editor: 

>When I type up exactly what I want to say, I then click to schedule the post. After I do that, all of the spacing changes. It looks like once big paragraph, and all of the paragraphs are gone. I tried to edit it to how I want it to look again, and when I save it, it goes to one big paragraph. Oh, and it publishes it to Facebook in the one big paragraph.

### A clear and concise description of what you expected to happen.

Publicize remove line breaks before posting to social media pages/profiles.

**Comment by jeherve** [comment]
cc @danielpost ; I am thinking this may be linked to the PHPCS changes from #22511?

**Comment by danielpost** [comment]
@jeherve It very well might be, thanks for letting me know. I'll take a look today, perhaps something changed with input validation that strips line breaks.

**Comment by danielpost** [comment]
I can confirm this issue happens on all Publicize connections (FB, Twitter, Tumblr and LinkedIn), and I'm 99.9% sure the error is caused by [this line](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/publicize/publicize.php#L1154).

The issue seems to be the usage of `sanitize_text_field` instead of `sanitize_textarea_field`, which causes line breaks to be stripped. I'll be able to fix this tomorrow morning my time 👍🏼

**Comment by danielpost** [comment]
@StefMattana This should be fixed now, thanks for letting us know!

**Comment by StefMattana** [comment]
Fantastic, @danielpost! I'll let the users know. Thanks a lot!
