### ISSUE TITLE
Shortcodes: Add Pinterest from wp.com

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2347]
Synopsis: We want to bring over pinterest oembeds from WordPress.com

Responsible: @georgestephanis (if he accepts this responsibility I've thrust upon him)

User experience: We're going to duplicate the UX from WordPress.com, see: https://en.support.wordpress.com/embed-from-pinterest/

Tl;dr: links to Pinterest profiles or to a specific board or pin turn in to an embed.

Technical approach: This currently exists in `wpcom/mu-plugins/shortcodes/pinterest.php`, so we just need to sync it in from there

Complete: 100%

Last Updated: 2016-10-31 (by @samhotchkiss)

**Comment by kraftbj** [comment]
Requested in 2247067-t

**Comment by samhotchkiss** [comment]
@kraftbj's original message:

WordPress.com adds an oembed handler for Pinterest ( mu-plugins/shortcodes/pinterest.php ). We should add it to the build script and bring it over to Jetpack

(I highjacked it to put it into new master issue format)

**Comment by samhotchkiss** [comment]
Updated status to `100%`
