### ISSUE TITLE
Jetpack CLI: always shows VaultPress as inactive, even if it's active.

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#2348]
Steps to reproduce:
1. `wp jetpack module activate vaultpress`
2. `wp jetpack module list`
3. VaultPress always shows as `Inactive`

**Comment by kraftbj** [comment]
VP should never be in that list, IMO.

**Comment by dereksmart** [comment]
> VP should never be in that list, IMO.
agreed
