### ISSUE TITLE
Payment Button Block: Unable to change plan if current plan does not exist

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#23506]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Open the editor on a premium site with multiple payment plans.
2. Insert the Payment Button block.
3. Switch to the code editor.
4. Edit the block replacing the `planId` with a made-up product ID (e.g. `123456` or something).
  It should be enough to only change the first `planId` attribute which is what affects this issue.
5. Switch back to the visual editor.
6. Open the sidebar and try changing the plan.

### A clear and concise description of what you expected to happen.

For the Payment Button block's plan selection to be updated.

### What actually happened

The plan is not updated.

There is a console error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'price')
    at _.getFormattedPriceByProductId
```
It points to [`getFormattedPriceByProductId`](https://github.com/Automattic/jetpack/blob/61a7b7b81834321d48a060f4e72f786e694775a1/projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx#L309-L314), which on plan selection is called on [both the new and old product](https://github.com/Automattic/jetpack/blob/61a7b7b81834321d48a060f4e72f786e694775a1/projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx#L319-L330).
The old product does not exist, so `product.price` fails.

### Browser

Other / Not applicable

**Comment by rcrdortiz** [comment]
This gets fixed for "free" #23414 gets shipped.
