### ISSUE TITLE
Boost: Redirect users to checkout page on Upgrade action

### ISSUE THREAD

**Issue by karthikax** [Automattic/jetpack#23501]
Project: pc9hqz-iD-p2
Design: p1HpG7-f1L-p2 (please refer to Figma file for details)

The `Upgrade Jetpack Boost` button should redirect the users to the checkout page. This may also require us to send the return URL as a part of the request so that the successful purchase will take the users back to the post-purchase page.

Dependencies: 46-gh-Automattic/boost-hydra, #23319

**Comment by thingalon** [comment]
Handled as a part of 44-gh-Automattic/boost-shield-api
