### ISSUE TITLE
Protect login failure causes a 500 response

### ISSUE THREAD

**Issue by joehoyle** [Automattic/jetpack#2351]
Failing the Protect form on the login page causes a 500 error, which is an incorrect error code. It should probably return a 401. Throwing 500 errors is typically for application errors so is throwing our exceptions detection stuff off!

Thanks

**Comment by jeherve** [comment]
Could you tell me more about your setup? Do you use the latest stable version of Jetpack (3.5.3), or Jetpack 3.6 Beta?

**Comment by joehoyle** [comment]
I'm using 3.5.3. I'm pretty sure this is due to use of `wp_die` without passing a status code.

**Comment by jeherve** [comment]
That's a good point, we probably shouldn't be happy with `wp_die`'s default. Thanks for the feedback!

I created #2352 to address this issue and we'll consider making that change in the next Jetpack release.
