### ISSUE TITLE
nav-unification: JITM request performance issues

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#23519]
#### Steps to reproduce

1. Start with a WoA site, connected to WordPress.com
2. Access `site.com/wp-admin/edit.php`
    * Ensure you see the nav-unification sidebar; it will only appear if the Masterbar module is active (it should be active by default), and if your user is connected to WordPress.com.
3. Examine network requests; the debug panel should highlight one specific request as being slow (**sometimes more than 5 seconds to complete**):
    * `https://public-api.wordpress.com/wpcom/v2/sites/BLOG_ID/jitm/calypso:sites:sidebar_notice?`

That request comes from here:
https://github.com/Automattic/jetpack/blob/921b5c74adace486a1edf3c0c67d20f18d3b1fd1/projects/packages/jitm/src/class-post-connection-jitm.php#L494-L495
https://github.com/Automattic/jetpack/blob/862a3f107ad02346a4571b78f8aea3b9e066f744/projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php#L268-L270

It was added in #19773. 

It would be nice to figure what is causing that request to be so slow; I would assume that one of the JITM rules is taking a bit longer than the others. @Automattic/dinobots Is that something you could look at?

Thank you!

*******

Internal references:

- 7301-gh-jpop-issues
- 4824430-zen

**Comment by tyxla** [comment]
Seems like I started working on this before I knew about it, so assigning it to myself. Thanks, @jeherve for pointing me here!
