### ISSUE TITLE
Markdown: remove _inc/lib/markdown/test.php

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2355]
Our Markdown library includes a file that doesn't seem to be used anywhere:
https://github.com/Automattic/jetpack/blob/master/_inc/lib/markdown/test.php

@mattwiebe Can we just get rid of it?

cc @boiteaweb who reported the issue.

**Comment by mattwiebe** [comment]
Not only can we get rid of it, we *should*. :+1: 

Total oops on having it in there in the first place.
