### ISSUE TITLE
JSON API: get_media_item_v1_1 isset checks

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2356]
https://github.com/Automattic/jetpack/blob/3.5.3/class.json-api-endpoints.php#L1186-1193

If `$metadata = wp_get_attachment_metadata( $media_item->ID )` doesn't return what is expected, we're not checking for that before running through the assigning width/height. We should check the response before making assumptions.

**Comment by PatelUtkarsh** [comment]
Hey @kraftbj 
Does simple empty check will work ? 
``` php
if ( empty( $file_info['extension'] ) )
			return new WP_Error( 'unknown_extension', 'Extension not found', 404 );
``` 

or should we also check extension before start processing ?  
``` php
if ( ! in_array($file_info['extension'], array('jpg', 'jpeg', 'png', 'gif', 'mp3', 'm4a', 'wav', 'ogg','ogv', 'mp4', 'mov', 'wmv', 'avi', 'mpg', '3gp', '3g2', 'm4v' ) ) )
			return new WP_Error( 'unknown_extension', 'Unknown Extension', 404 );
```

Thanks,

**Comment by kraftbj** [comment]
I don't think the problem is the lack of extension, but the response from https://github.com/Automattic/jetpack/blob/3.6.1/class.json-api-endpoints.php#L1072 lacking. 

The video bit of code has the kind of check I'm thinking added since this issue opened https://github.com/Automattic/jetpack/blob/3.6.1/class.json-api-endpoints.php#L1090

I don't think we need to error out, just not include what we don't have.  Thanks!
