### ISSUE TITLE
Payment blocks: Plan name not defaulted after adding plan

### ISSUE THREAD

**Issue by dsas** [Automattic/jetpack#23575]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Be on a wpcom site with a paid plan
2. Add a new post
3. Insert a premium content block
4. In the inspector on the right add a new subscription

### A clear and concise description of what you expected to happen.

After the new subscription has been added, all of the fields ought to be reset to their default values.

### What actually happened

The form gets all of it's fields set to a default value except for the product title

### Other information

https://user-images.githubusercontent.com/93301/159720300-08d42be8-9c34-4f0c-a965-ed83733ac692.mp4

Video was taken while testing #23545 but it also happens on premium-content blocks, I don't think it originated there, more likely #23427

### Browser

Firefox

**Comment by dsas** [comment]
See https://github.com/Automattic/jetpack/blob/49d87789ab0396730ca4fdba9e1421cccd97abd3/projects/plugins/jetpack/extensions/shared/components/product-management-controls/inspector-control.js#L61-L64

**Comment by BogdanUngureanu** [comment]
Closing this since it was handled in https://github.com/Automattic/jetpack/pull/24175. Good job, Lukasz! 🎉
