### ISSUE TITLE
Site Logo & Mobile: Add Site Logo option

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2359]
The mobile theme pulls the custom header from the desktop theme into the mobile theme. It would be great if we used the Site Logo.

One idea: If the Mobile Theme module is active, add support for the site logo giving the user the ability to add a site logo for use in mobile even if the desktop theme doesn't support it.

**Comment by samhotchkiss** [comment]
Makes sense, but isn't in line with our current goals for Jetpack and isn't high priority enough to focus on right now.  Would be open to PRs from the community addressing this.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
