### ISSUE TITLE
Payment Button: Fallback URL breaking in the site editor

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#23595]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Pick a site with a paid plan and an active Stripe connection.
2. Open the site editor.
3. Insert the Payment Button block.

### A clear and concise description of what you expected to happen.

The Payment Button block works as expected, and it's possible to add and select payment plans.

### What actually happened

All the payment plans management doesn't load.

This error shows up in the console:
`An error occurred while running 'mapSelect': Failed to construct 'URL': Invalid URL`

### Other information

This is a regression introduced in https://github.com/Automattic/jetpack/pull/23487:

https://github.com/Automattic/jetpack/blob/c6c27dbf14c3378e15eb892711e0dbbca6651b34/projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx#L528

In the site editor (and I presume in the widget editor too), `getCurrentPost` is empty.
So, `link` is undefined, `new URL()` throws an error, and half of the block doesn't load properly.

This affects both Payment Button and Premium Content blocks (the latter includes the former).

The `postLink` was introduced as a fallback URL for buttons rendered outside site context (e.g. email, RSS feed, notifications) to make them link back to their original post.
It is (nearly) impossible to determine the same link for blocks inserted in a template or widget area; in those cases, the link is not needed, and we can revert to the original behaviour (a simple `href="#"`).

### Browser

Other / Not applicable

**Comment by galakhyati** [comment]
A screencast video of the issue:

https://user-images.githubusercontent.com/7382505/160070324-855e349d-01f5-44d8-a607-2459e6ef817c.mov

**Comment by Copons** [comment]
Fixed by #23545
