### ISSUE TITLE
Beautiful Math: Improve font resolution

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2360]
The font user to render LaTeX doesn't, well, look as beautiful as it could.

Non-retina: 
![screen shot 2015-07-06 at 15 51 27](https://cloud.githubusercontent.com/assets/88897/8532876/e9aba6e0-23f6-11e5-985e-ed9bf6989262.png)

**Comment by samhotchkiss** [comment]
While we're considering some changes to Beautiful Math down the road, at the present time it doesn't align with our internal team goals, but we'd welcome PRs from the community.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
