### ISSUE TITLE
ctype_digit() undefined in some hosting environments

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#23609]
### Impacted plugin

Jetpack

### Steps to Reproduce

- Get hosting without `ctype` extension. Reporter has hosting at Globat
- Install Jetpack
- Run through setup wizard and attempt to install Creative Mail
- Verify 500 error

The error in the logs from reporter is:

```
Call to undefined function ctype_digit()

jetpack_vendor/automattic/jetpack-connection/legacy/class-jetpack-signature.php:217
```

See p1648145485453919-slack-CDLH4C1UZ

### Other information

A recommendation was made that we consider using the `symfony/polyfill-ctype` polyfill here.

### Operating System

macOS

### Browser

Chrome/Chromium

**Comment by jeherve** [comment]
Would it be possible to reach out to the hosting provider and recommend that they enable the ctype extension to solve this issue?

- We do use `ctype_digit` in a few places in Jetpack, have done so for years.
- WordPress Core itself [uses the function in one place](https://github.com/WordPress/WordPress/blob/270f2011f8ec7265c3f4ddce39c77ef5b496ed1c/wp-includes/class-wp-recovery-mode-cookie-service.php#L93), without any safeguard.
- The ctype extension is enabled by default in recent versions of PHP, and must be explicitly disabled.
- We do not currently directly require `symfony/polyfill-ctype`

**Comment by ebinnion** [comment]
I reached out to Globat's chat support today to ask for a technical contact. Was told that support is run over voice or chat. Informed chat that the issue is that ctype_digit() does not exist and it's a function that is used in both Jetpack and for the recovery mode in core WordPress.

Was told to have user contact Globat directly.

I suggest that close this issue as `wontfix` on our side.
