### ISSUE TITLE
Subscriptions: Add Like text

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2361]
On e-mail notifications from WP.com of new posts, there is a Like button that take you to the post and likes it.

Jetpack e-mails don't (I presume due to the Likes being an iframe and harder to interact with wp.com), since r62995-wpcom

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by codestor4** [comment]
Ticket - https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=3209874&noteconfirm=1

**Comment by kurt213** [comment]
Another user facing this issue:
Ticket - 3240034

**Comment by bobmatyas** [comment]
Another report on 4009187-zen

**Comment by druesome** [comment]
Another report: 5247485-zen
