### ISSUE TITLE
Actions: Review "Required Review" check for "VaultPress and Backup"

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#23626]
While working on https://github.com/Automattic/jetpack/pull/23621, [vianasw](https://github.com/vianasw) approved but the check didn't pass. 

According to https://github.com/Automattic/jetpack/blob/master/.github/files/required-review.yaml#L30-L38 that review should have been able to unlock the merge. 

![image](https://user-images.githubusercontent.com/746152/160133000-836fd45d-587e-4f79-b1a2-87e0be18ff2a.png)

**Comment by jeherve** [comment]
I think this may be linked to the recent GitHub Actions failures. Approving again may be enough to fix this.

**Comment by kraftbj** [comment]
https://github.com/Automattic/jetpack/runs/5691208900?check_suite_focus=true
source of the screenshot above

**Comment by oskosk** [comment]
Indeed. Closing
