### ISSUE TITLE
S2.9 Change Jetpack Cloud Search section to use new settings API

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#23620]
![image](https://user-images.githubusercontent.com/1425433/160964633-7389420e-3cac-4d9b-8ae8-da19f63275b6.png)

http://jetpack.cloud.localhost:3000/jetpack-search/<site_url> - This page displays that the Site Connection has failed.

**Comment by kangzj** [comment]
This is closed by `D78351-code`
