### ISSUE TITLE
Payment Blocks: Fix "add new" toolbar control edge cases

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#23633]
This is a follow-up to https://github.com/Automattic/jetpack/issues/23443 which was mostly fixed by https://github.com/Automattic/jetpack/pull/23603.

Payment blocks have an "Add new product" control in the toolbar which automatically opens the block setting sidebar, where the new product form is located, and focus on the product title input field.

<img width="534" alt="Screenshot 2022-03-15 at 12 04 27" src="https://user-images.githubusercontent.com/2070010/158374080-5ad0d3b9-4eee-405f-98ad-5ff538d62989.png">

This behaviour has a couple of minor issues:

#### The Widgets editor in the Customizer

Normally, the sidebar is controlled by the `enableComplementaryArea` Redux action (`core/interface` store).

In the Customizer, that sidebar is controlled by the internal state of the editor instance.
I'm not sure how to work around this limitation, and I'm quite tempted to remove the "add new" control when in the Customizer, and just rely on the "show more settings" button in the toolbar's more menu (which AFAICS is the only way to open the block sidebar).

#### Pre- and post-publish panels

They appear above the block setting sidebar.
When they are open, the block setting sidebar is unavoidably covered, so while the "add new product" button technically works, the UX still feels broken.
We might want to explore if there's a way to programmatically close the pre/post-publish panel, but we'd need to verify if that actually is the desired behaviour.

**Comment by rcrdortiz** [comment]
Found another issue with this. The controls are shared with child blocks, but the sidebar belongs to the parent. It's possible to click on add new from a child block but nothing happens.


https://user-images.githubusercontent.com/1989914/160809012-b80a3817-9fdf-44a6-a583-2402e32e0754.mp4
