### ISSUE TITLE
Add RSS Feed Option to Social Media Icons Widget

### ISSUE THREAD

**Issue by macmanx2** [Automattic/jetpack#2363]
A few folks, including myself, use social links in more of a "Follow Me" manner, listing all of the ways you can follow the blog and other not-blog content. In the spirit of following, it would be awesome if the inclusion of the blog's RSS feed were an option. (Some feed readers, like Newsblur and Feedly, are even social networks in their own way.)

This could be accomplished with minimal complexity on the user end by adding an "Include RSS Feed" checkbox at the bottom of the widget settings and using Genericon's feed icon (f413).

When checked, something like the following would be added to the list of links by the widget:

```<li><a title="Syndicate this site using RSS" href="<?php bloginfo('rss2_url'); ?>" class="genericon genericon-feed" target="_blank"><span class="screen-reader-text">Syndicate this site using RSS</span></a></li>```

**Comment by jeherve** [comment]
Related: #2234

**Comment by samhotchkiss** [comment]
resolved by #2367
