### ISSUE TITLE
Search: old post type settings always override user settings on auto config

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#23645]
### Impacted plugin

Jetpack

### Steps to Reproduce

> Customer is having issues to keep the same settings on the Jetpack Search settings in the Customizer. They want to exclude posts, and only include Courses and Lessons (Sensei LMS) but their settings become the opposite after some time, this happened at least twice. https://github.com/Automattic/jpop-issues/issues/7241

The auto config process always apply old post type setting from widgets to override users settings, which caused user setting to be overridden from time to time.

https://github.com/Automattic/jetpack/blob/b1d9aad9639199d9572c16333b607613f1de04e2/projects/packages/search/src/instant-search/class-instant-search.php#L723

### A clear and concise description of what you expected to happen.

If new config exists, then we should just discard the old settings rather than importing it to override user's new settings. <strike>And old settings should be deleted after converted to new settings.</strike>

### Browser

Other / Not applicable

**Comment by StefMattana** [comment]
Adding the tickets related to the case: 

- [#4706741-zen](https://woothemes.zendesk.com/agent/tickets/4706741)
- [#4871687-zen](https://woothemes.zendesk.com/agent/tickets/4871687)
- [#4899724-zen](https://woothemes.zendesk.com/agent/tickets/4899724)
