### ISSUE TITLE
Widgets: add EU Cookie Law widget

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2364]
The widget is a nice start, and can be ported to Jetpack:
https://en.support.wordpress.com/cookie-widget/

It'd be nice if we could do more, though. We now have [a page on jetpack.me](http://jetpack.me/cookies), so we could pull information from there.

cc @clickysteve

**Comment by kraftbj** [comment]
:+1: The WP.com widget appears to have plenty of options that would make it good to go out of the box for JP users.

**Comment by kriskarkoski** [comment]
Looks like this was added at some point https://jetpack.com/support/extra-sidebar-widgets/eu-cookie-law-widget/

Closing this issue.
