### ISSUE TITLE
Introduce `Icon` component at `jetpack-components`

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#23640]

**Comment by retrofox** [comment]
All these icons, expect the checkmark, are defined by core. For instance, `product-backup` is `cloud`. Should we replace these icons by the core ones? We can create links in order to be more descriptive?
If so and being said that, I think we could get rid of almost all these icons for now.

**Comment by renatoagds** [comment]
@retrofox Just one point is that I miss some icons listed here: https://developer.wordpress.org/resource/dashicons/ ... But no problem to close this and return when we have more examples to list and get.

**Comment by renatoagds** [comment]
Makes sense! Let's close it, we could reopen if needed.
