### ISSUE TITLE
PHP 8.1: the default value of the flags parameter for htmlentities() et all needs to be explicitly set

### ISSUE THREAD

**Issue by GaryJones** [Automattic/jetpack#23693]
### Impacted plugin

Jetpack

### Steps to Reproduce

Running the plugin with PHP 8.1 can give different results compared to using PHP 8.0 and below, particularly if encoded strings contain single quotes.

See https://core.trac.wordpress.org/ticket/53465 for the same issue in WordPress core.

### A clear and concise description of what you expected to happen.

Behaviour around encoding strings into HTML entities should be consistent across all PHP versions.

### What actually happened

`htmlspecialchars()`, `htmlentities()`, `htmlspecialchars_decode()`, `html_entity_decode()` and `get_html_translation_table()` now use `ENT_QUOTES | ENT_SUBSTITUTE | ENT_HTML401` rather than `ENT_COMPAT` by default. This means that `'` is escaped to `&#039;` while previously it was left alone.

Additionally, malformed UTF-8 will be replaced by a Unicode substitution character, instead of resulting in an empty string.

### Other information

Examples of some of the affected PHP functions that need the second argument (`$flags`) explicitly set:

- https://github.com/Automattic/jetpack/blob/60ff8e8f3400ab8e8bf7c68f1377e506d6f1cfd9/projects/plugins/jetpack/modules/sitemaps/sitemap-buffer-fallback.php#L127
- https://github.com/Automattic/jetpack/blob/bf8eb8f02b96ebdec083fab30bdde9ffdb463543/projects/plugins/jetpack/modules/comments/comments.php#L548
- https://github.com/Automattic/jetpack/blob/17516e9da10ef8829e0db62e670f11fdcd906106/projects/plugins/jetpack/modules/tiled-gallery/tiled-gallery/templates/partials/carousel-image-args.php#L28
- https://github.com/Automattic/jetpack/blob/b7331380af3f3755f5955405cf6470e17d026672/projects/plugins/jetpack/_inc/lib/admin-pages/class-jetpack-redux-state-helper.php#L55

Easy enough to find more instances that will need fixing up as well.

### Browser

Other / Not applicable

**Comment by anomiex** [comment]
This wound up being done in #27753 once PHPCompatibility's dev branch added sniffs for it.
