### ISSUE TITLE
My Jetpack: update copy in Your Plan(s) / Connection

### ISSUE THREAD

**Issue by keoshi** [Automattic/jetpack#23694]
Let's update the copy in the two bottom sections of “My Jetpack”.
Reported in p8oabR-PC-p2#comment-6108

## Your Plan(s)
- For empty (no plans), change it to: `Want to power up your Jetpack?`
- For empty (no plans), make sure the text size and color matches a regular `<p>`.*
- When a plan or more exist: remove the descriptive text.

## Connection
- Update description to `Leverages the cloud for more powerful Jetpack features.`
- For site-only connection (no user connection), make sure the text size and color matches a regular `<p>`.*

*This seems to be a wider issue ATM, also visible in the interstitial screens.

**Comment by retrofox** [comment]
> For empty (no plans), make sure the text size and color matches a regular <p>.*

@keoshi, could you confirm it's a _Body_ typography, based on this PbJqbW-8t-p2? `16px` / `24px` - `regular`? thanks

**Comment by keoshi** [comment]
@retrofox:

> could you confirm it's a Body typography
That's it, sorry for the incorrect naming.

> The descriptive text shows only when no plans.
Right, I'd forgotten we changed that already.
