### ISSUE TITLE
Dashboard / WPCOM Atomic: Hide Security upgrade card on new WordPress.com Pro plan

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/jetpack#23735]
### Impacted plugin

Jetpack

Related to the new WordPress.com Pro plan

Another Pro issue https://github.com/Automattic/jetpack/issues/23736

pdgrnI-zG-p2

pdgrnI-xK-p2

### Steps to Reproduce

1. Create a new WPCOM Pro plan site, make site Atomic
2. Visit `/wp-admin/admin.php?page=jetpack#/dashboard`
3. See Security upgrade card

### A clear and concise description of what you expected to happen.

No upgrade card.

### What actually happened

Upgrade card is present. 

![Screen Shot on 2022-03-31 at 13:41:38](https://user-images.githubusercontent.com/4887830/161119005-08ad8db3-c95c-4f66-a195-c3b4dc1f80e2.png)

**Comment by kraftbj** [comment]
I'm marking this for 10.8 for awareness. We may want to cherry-pick to ensure Atomic gets this ASAP.
