### ISSUE TITLE
Dashboard: My Plan page broken on new WPCOM Pro plan 

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/jetpack#23736]
### Impacted plugin

Jetpack

Related to new WordPress.com Pro plan

Another Pro issue: https://github.com/Automattic/jetpack/issues/23735

pdgrnI-zG-p2 

pdgrnI-xK-p2

### Steps to Reproduce

1. Create a new WPCOM Pro plan site, make site Atomic
2. Visit `/wp-admin/admin.php?page=jetpack#/my-plan`
3. See blank, React loading

### A clear and concise description of what you expected to happen.

My Plan should load Jetpack features

![Screen Shot on 2022-03-31 at 13:55:47](https://user-images.githubusercontent.com/4887830/161119417-00a15d2b-a1af-4029-a438-83ceb3b44246.png)

### What actually happened

Nothing loads

![Screen Shot on 2022-03-31 at 13:45:46](https://user-images.githubusercontent.com/4887830/161119502-0b4e668f-69c6-4617-8dd2-401223c9b5b2.png)

**Comment by wpshellbelle** [comment]
Bug looks to be present on Woo Express sites now. Reported here: https://github.com/Automattic/jetpack/issues/33734
