### ISSUE TITLE
2.11 My Jetpack integration

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#23771]
#### The problem

When Jetpack Search runs without Jetpack the plugin:

- The status of Jetpack Search is not correctly reflected by My Jetpack.

| Search Dashboard      | My Jetpack |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/1425433/161466037-8925a992-1534-4cad-8fb4-0e4b4321963a.png)      | ![image](https://user-images.githubusercontent.com/1425433/161466077-5334bdea-6f2c-4370-bf00-e61bd95e55ee.png)       |

- Clicking activating Search module in My Jetpack, Jetpack plugin is activated and then search module is enabled. 
![Screen Capture on 2022-04-04 at 14-53-49](https://user-images.githubusercontent.com/1425433/161466336-43a4823d-dee5-400e-bcbe-4c163bad8af2.gif)

#### Expected bahaviour: 

- My Jetpack only needs to only activate the search module when Jetpack Search already exists.
- My Jetpack should activate/install Jetpack Search plugin instead of Jetpack when clicking button `Activate`

#### Related API

API already added to Jetpack Client:

https://github.com/Automattic/jetpack/blob/2ef743a8e4a3f4012a24b663020a0b0da2c01dfd/projects/js-packages/api/index.jsx#L472-L489

https://github.com/Automattic/jetpack/blob/2ef743a8e4a3f4012a24b663020a0b0da2c01dfd/projects/packages/search/src/class-rest-controller.php#L149-L154

https://github.com/Automattic/jetpack/blob/2ef743a8e4a3f4012a24b663020a0b0da2c01dfd/projects/packages/search/src/class-rest-controller.php#L221-L224

**Comment by kangzj** [comment]
Hey @Automattic/jetpack-agora, Howdy! Wondering if we could get some help on this one. We could potentially work on it as well tho. Just let us know, thanks folks 😄

**Comment by leogermani** [comment]
> Hey @Automattic/jetpack-agora, Howdy! Wondering if we could get some help on this one. We could potentially work on it as well tho. Just let us know, thanks folks smile

Sure! We have to change that behavior in My Jetpack. We only need to sync it with the Search plugin release so we don't release it before the Search plugin is out there. Do you think is ok if we did it now?

**Comment by kangzj** [comment]
That'll be awesome thanks in advance @leogermani 

> Do you think is ok if we did it now?

The API comes with the search package which is available for Jepack too, so it should be all good.

**Comment by leogermani** [comment]
@kangzj I created the PR above kicking off what needs to be done. There's still one missing piece that is activating the Jetpack module when using the Jetpack plugin.

My worry asking about the timeline is because Search is to be considered a Hybrid product. This means it will work with Jetpack plugin as well as its stand alone plugin.

In the situation where Jetpack is already active, My Jetpack will not install/activate the Search plugin. It will use Jetpack. 

If Jetpack is not active, it will favor the Search stand-alone plugin. If Search is not installed, it will try to install it from the plugin directory.

If we release My Jetpack with this change and a person running a site with neither Jetpack or Search installed, we'll try to install Search from the wp,org repo and it must exist there, otherwise we'll have an error.

**Comment by kangzj** [comment]
@leogermani wow that is blazing fast! 👍 👍 👍 

> If we release My Jetpack with this change and a person running a site with neither Jetpack or Search installed, we'll try to install Search from the wp,org repo and it must exist there, otherwise we'll have an error.

For now, could we:

| Scenario   |   Behaviour  |
|-----------|-------------|
|No Jetpack or Search | install Jetpack |
|Only Jetpack | - |
|Only Search | - |
|Jetpack + Search| - |

After Search plugin release:

| Scenario   |   Behaviour  |
|-----------|-------------|
|No Jetpack or Search | install Search |
|Only Jetpack | probably still do nothing |
|Only Search | - |
|Jetpack + Search| - |



Our planned release is at the end of May 2022 btw. Thanks again. ❤️ 

cc @Automattic/jetpack-search

**Comment by leogermani** [comment]
I've updated the PR and we should have this behavior now. We just need to remember to change it once the Search plugin is released.

Would you help me test it thoroughly? We need to test it in the different scenarios and completing the whole flow, making the purchase and everything, both with Jetpack and Search plugins, to make sure all works smoothly.

**Comment by jsnmoon** [comment]
@leogermani: We'd be happy to help test these changes and provide PR reviews! Feel free to ping us at @Automattic/jetpack-search for our attention 🙂
