### ISSUE TITLE
S2.13 Sync Instant Search settings to WPCOM

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#23779]
We probably want the change to go with the first public release, otherwise we'd have to wait for newer versions to roll out to support excluding item from ES index and etc etc based on Instant Search settings on client's sites.

We might want to sync some constants as well.

**Comment by jsnmoon** [comment]
@kangzj: Are you referring to the Instant Search settings as defined [here](https://github.com/Automattic/jetpack/blob/master/projects/packages/search/src/class-settings.php#L33) for use in Customberg?

**Comment by kangzj** [comment]
> @kangzj: Are you referring to the Instant Search settings as defined [here](https://github.com/Automattic/jetpack/blob/master/projects/packages/search/src/class-settings.php#L33) for use in Customberg?

Yes that's right.

**Comment by kangzj** [comment]
Just want to add: we might also want to inspect `active_modules` and `instant_search_enabled` options. Publicize discussion: `p1650887248568409-jetpack-sync-slack`.
