### ISSUE TITLE
Multisite: allow network admins to automatically connect on site creation

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2380]
Right now, super admins can connect a site to their own WordPress.com account from the Network Admin screen, by clicking on Connect.

It'd be nice if the connection could happen automatically, so it's easier for folks with large networks.

Suggested here:
https://wordpress.org/support/topic/automatically-connect-a-new-multisite-site-to-wordpresscom?replies=9&view=all

Related: #2160

**Comment by kraftbj** [comment]
I'm not sure the backstory but the code is in place to do it, but commented out.
UI for the setting: https://github.com/Automattic/jetpack/blob/f4103676bdbe4b5d9105f2439603750307091d77/views/admin/network-settings.php#L20

The actual action to do it: https://github.com/Automattic/jetpack/blob/f4103676bdbe4b5d9105f2439603750307091d77/class.jetpack-network.php#L77

**Comment by lcenvs** [comment]
Thanks for the above. We would also be interested in the ability to connect *existing* sites in a multisite upon network activation of Jetpack...we're setting that up now, manually, for ~100 sites, not impossible but not elegant.

**Comment by ChrisPurves** [comment]
Uncommenting the code in network-settings.php works great for adding a site through the dashboard, but has no effect if creating a site using a plugin and the wpmu_create_blog() function.

**Comment by ChrisPurves** [comment]
To have wpmu_create_blog() automagically connect to jetpack it is necessary for admin (or perhaps any user with jetpack credentials) to be the current user:

> wp_set_current_user($adminID);
> wpmu_create_blog(...);

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
