### ISSUE TITLE
My Jetpack purchase button broken on sites installed in subfolder 

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#23812]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Go to a site installed in subfolder with Jetpack plugin e.g. `https://xxx.com/wp`
2. Navigate to `/wp/wp-admin/admin.php?page=my-jetpack`
3. Choose a product not purchased yet, click `Purchase`
![image](https://user-images.githubusercontent.com/1425433/161894248-3b88e6ff-6714-412d-b4c6-51cea6c6b814.png)
4. Click `Add Jetpack Scan`
![image](https://user-images.githubusercontent.com/1425433/161894311-cbf23154-9a87-46fa-8922-01a76ef15c18.png)

### A clear and concise description of what you expected to happen.

The page should be redirected to the purchase flow of products

### What actually happened

It doesn't and has the following error in console:

![image](https://user-images.githubusercontent.com/1425433/161894546-a19df6ea-b56e-460f-950f-de278e5679b1.png)

@Automattic/jetpack-agora

### Operating System

macOS

### Browser

Chrome/Chromium

**Comment by oskosk** [comment]
Thanks
