### ISSUE TITLE
Enhancement: Google+ isn't a thing anymore, so it shouldn't appear in strings anymore.

### ISSUE THREAD

**Issue by NekoJonez** [Automattic/jetpack#23837]
### Impacted plugin

Social

### What

Google+ remove

### How

I'm creating a PR now to remove Google+ from strings. Maybe somebody who knows the plugin better should add to my PR to remove functionality of old Google+ button(s).

**Comment by jeherve** [comment]
Definitely a valid issue, thank you.

**Comment by NekoJonez** [comment]
It seems like I misclicked myself o.o
I am currently not behind the computer... I'll continue to work on this soon.

**Comment by NekoJonez** [comment]
I wouldnt have been able to find all of them. And why did I close the issue, maybe misclick I think
