### ISSUE TITLE
Related Posts: PHP Warning with AMP post views

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#23841]
Looks like in #22727 we [changed](https://github.com/Automattic/jetpack/pull/22727/files#diff-9105b068cf482dd9007ac0a2ff0985bf13dac7d398fb802678224448b5897841R427-R432) `Jetpack_RelatedPosts->render_block` in part by adding:

```php
$wrapper_attributes = \WP_Block_Supports::get_instance()->apply_block_supports();
```

Though if you check `Jetpack_RelatedPosts->get_server_rendered_html`, (which checks for `Jetpack_AMP_Support::is_amp_request()` ), this doesn't actually register a block, which I assume leads to the following warning on AMP views as mentioned in this [forum thread](https://wordpress.org/support/topic/php-8-1-warning-with-amp/):

```
PHP Warning:  Trying to access array offset on value of type null in /var/www/html/wp-includes/class-wp-block-supports.php on line 94
PHP Warning:  Trying to access array offset on value of type null in /var/www/html/wp-includes/class-wp-block-supports.php on line 96

Backtrace:
require('wp-blog-header.php'),
require_once('wp-includes/template-loader.php'),
include('/themes/twentytwenty/singular.php'),
get_template_part,
locate_template,
load_template,
require('/themes/twentytwenty/template-parts/content.php'),
the_content, apply_filters('the_content'),
WP_Hook->apply_filters,
Jetpack_RelatedPosts->filter_add_target_to_dom,
Jetpack_RelatedPosts->get_server_rendered_html,
Jetpack_RelatedPosts->render_block,
WP_Block_Supports->apply_block_supports
```

Reproduced with:

* Jetpack 10.8 connected on WordPress 5.93
* Jetpack Related Posts module enabled
* AMP plugin v2.2.2 active
* Visit an AMP post view & observe debug log for warning

I'd think we could check if we are doing `get_server_rendered_html` and if so not call the `apply_block_supports`?

cc: @yansern @ivan-ottinger @jeherve

**Comment by napestershine** [comment]
Any updates on it ?

**Comment by ivan-ottinger** [comment]
I am having trouble reproducing the issue. 🤔 

Just to make sure I follow the steps correctly: The warnings are triggered when you access the AMP version of the post at the URL ending with `?amp=1`, right? (e.g. `https://<site-domain>/2022/07/01/related-posts-test/?amp=1`)

**Comment by samiff** [comment]
@ivan-ottinger I'm still able to reproduce, I've opened #24938 with some testing instructions if you'd like to have a look 👍

**Comment by ivan-ottinger** [comment]
Thank you for the fix @samiff! I was AFK and didn't get to test your PR before it was merged unfortunately. Glad to see the issue is fixed now.
