### ISSUE TITLE
Extra Sidebar Widgets - Add width parameter to Facebook Page widget options

### ISSUE THREAD

**Issue by csonnek** [Automattic/jetpack#2386]
With the introduction of the new Facebook Page sidebar widget in 3.6, we provide options for:
- Height
- Show/Hide Faces
- Show/Hide Stream
- Show/Hide Cover Photo

However, looking at the options on <a href="https://developers.facebook.com/docs/plugins/page-plugin">developer.facebook.com</a>, there are additional options available:
- Width (min 180, max 500)
- Use Small Cover Photo (makes the Cover Photo more compact vertically)

There's also an option for `adapt_container_width` - if we're not already using that in our widget, we should also add that. 

I've seen a number of requests that the widget is "too narrow" and people would like a way to configure the width in addition to the height.

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/facebook-like-box-width-issue?replies=1&view=all

**Comment by lancewillett** [comment]
I'm pretty sure this was added quite some time ago: e2eeba8a233467146c03e6f565a219ed0a3378fd
