### ISSUE TITLE
Payment Blocks: Fix incorrect product toolbar control paddings

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#23880]
A [recent Gutenberg update](https://github.com/WordPress/gutenberg/pull/39630) added horizontal paddings to the block toolbar controls.

This interferes with the payment blocks' product toolbar control which displays a little triangle, that's supposed to be absolutely positioned in the bottom-right corner.

With the new paddings, it is now 6px separated from the corner.

<img width="144" alt="Screenshot 2022-04-08 at 17 18 05" src="https://user-images.githubusercontent.com/2070010/162472628-a899fa5a-80fe-43cf-8fed-d8f128868c57.png">
<img width="315" alt="Screenshot 2022-04-08 at 17 18 33" src="https://user-images.githubusercontent.com/2070010/162472654-c370eef7-9d88-467a-bb38-80eb24abf9a3.png">

I'm not sure how to fix this while maintaining backwards compatibility.
E.g. if we move the triangle, it will look good on the most recent Gutenberg, but broken on all previous versions. 

Throwing a random idea: what about removing the triangle altogether?

**Comment by dsas** [comment]
> what about removing the triangle altogether?

It should be removed.

I think the little triangle is a good idea to show that there's more that will happen when using the menu control but if it's a good idea for this drop down menu, it's a good idea for all of them and so `ToolbarDropdownMenu` ought to always display it.

As it is, it's inconsistent with every other gutenberg block.

**Comment by rcrdortiz** [comment]
I've found a rather easy workaround if we want to keep the drop-down indicator. We could just rotate and move it, it would look something like this:
<img width="677" alt="Captura de Pantalla 2022-04-19 a las 13 04 36" src="https://user-images.githubusercontent.com/1989914/163990490-2e9cc3d9-e0a8-43b9-a296-0f7e31250384.png">

**Comment by Copons** [comment]
@rcrdortiz I actually agree with @dsas on this. The Core's `ToolbarDropdownMenu` component doesn't use any triangles, so we should probably avoid it as well.
I think we can go ahead with removing it for now.
