### ISSUE TITLE
Allow Google Map embeds from other sources than maps.google and mapsengine.google.com

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/jetpack#2388]
Currently the Google Maps shortcode is looking for iframes on the domains maps|mapsengine.google.co|com 

`preg_match( '!^https?://(www|maps|mapsengine)\.google(\.co|\.com)?(\.[a-z]+)?/.*?(\?.+)!i'` 

[Source](https://github.com/Automattic/jetpack/blob/202d1b80e9386aa6ed2dceb6ab9a4f362413e695/modules/shortcodes/googlemaps.php#L69)

This prevents other google maps, such as the crisis maps found on google.org from being used with the shortcode. 

For example:
http://google.org/crisismap/a/gmail.com/mappasismica?hl=it&llbox=48.41%2C34.79%2C30.52%2C-4.48&t=HYBRID&layers=4%2C5%2C3%3A34%2C6%2Clayer0%2C1&embedded=tru

**Comment by georgestephanis** [comment]
The regex could probably be significantly simplified --

`^https?://(www|maps|mapsengine)\.google(\.co|\.com)?(\.[a-z]+)?/.*?(\?.+)`

to

`^https?://(www|maps(engine)?)\.google(\.com?)?(\.[a-z]+)?/.*?(\?.+)'`

or something -- possibly further.  Just combining the `maps|mapsengine` to `maps(engine)?` and the `.com|.co` to `.com?`

**Comment by BandonRandon** [comment]
I think @georgestephanis' regex includes support for this, but we should also include localization support like maps.google.co.uk :)

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
