### ISSUE TITLE
2.15 Ensure 'My Jetpack' works with the Search plugin

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#23917]
- [x] 1. Ensure My Jetpack installs the Search plugin when activating Search ([previous discussion](https://github.com/Automattic/jetpack/issues/23771))
- [x] 2. Ensure activating search in My Jetpack only affects the search module and does not deactivate the plugin by hooking into [my_jetpack_search_activation](https://github.com/Automattic/jetpack/pull/24334)
- [x] 3. Reverse the changes for the special redirection behavior from https://github.com/Automattic/wp-calypso/pull/62199 when ConnectScreenRequiredPlan support customized button action. And we need to ensure when the site has a search subscription, we should redirect the user back to the dashboard instead of the checkout page.
- [x] 4. My Jetpack doesn't seem to support tiered pricing. The following is an example of a site with 1001 records:

|Expected pricing|Actual|
|--------------|--------|
|![image](https://user-images.githubusercontent.com/1425433/167318747-9540a91a-130f-4a3d-bff7-c3b6dcf296e4.png)|![image](https://user-images.githubusercontent.com/1425433/167318771-7cd1e610-00a5-4134-8a1e-1827b7e9d5db.png)|

- [x] 5. On disconnection screen, Should there be a list?
![image](https://user-images.githubusercontent.com/1425433/167328248-d9aa3cae-57d3-48df-803d-86f7cb2de8e7.png)
- [x] <strike>6. Would prefer the manage button links to Search dashboard / or add another link?</strike>

**Comment by retrofox** [comment]
> 4. My Jetpack doesn't seem to support our tier-ed pricing. The following is an example for a site with 1001 records:

Addressed here https://github.com/Automattic/jetpack/pull/24337

**Comment by kangzj** [comment]
> 1. Ensure My Jetpack installs the Search plugin when activating Search

Fixed via #24335

**Comment by kangzj** [comment]
> 2. Ensure activating search in My Jetpack only affects the search module and does not deactivate the plugin by hooking into https://github.com/Automattic/jetpack/pull/24334

Resolved by #24443

**Comment by kangzj** [comment]
> 3. Reverse the changes for the special redirection behavior from https://github.com/Automattic/wp-calypso/pull/62199 when ConnectScreenRequiredPlan support customized button action. And we need to ensure when the site has a search subscription, we should redirect the user back to the dashboard instead of the checkout page.

Closed by https://github.com/Automattic/jetpack/pull/24403
