### ISSUE TITLE
action-required-review  Action not finding teams correctly in an organization

### ISSUE THREAD

**Issue by symplr-svc-ctc-ci-user** [Automattic/jetpack#23938]
### Impacted plugin

Jetpack, None / Other

### Steps to Reproduce

1. create team in Github
2. reference team in the 'action-required-review' GH Action.
3. the Action fails with a message similar to below:
```
  Checking reviewers...
    Union of these:
      Union of these, if none are empty:
  Error: Failed to query symplr-software team ce-alloy-qe from GitHub
  WrappedError: Failed to query symplr-software team ce-alloy-qe from GitHub
      at fetchTeamMembers (/home/runner/work/_actions/Automattic/action-required-review/v2.2.2/webpack:/required-review/src/team-members.js:37:1)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

The mitigation to this was I actually had to specify a github token in the Action/yaml with a user PAT.

### A clear and concise description of what you expected to happen.

it should find the team & require review from that team

### What actually happened

the action cannot find the team

### Browser

Chrome/Chromium

**Comment by anomiex** [comment]
It looks like a token is always going to be required, as the default `GITHUB_TOKEN` does not have access to read team membership. The documentation should be updated to reflect that.
