### ISSUE TITLE
Site Icon: Favicon size on Android

### ISSUE THREAD

**Issue by odie2** [Automattic/jetpack#2395]
Hello,

In [Support for theme-color in Chrome 39 for Android](https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android) article we can read:

>In addition, Chrome will show beautiful high-res favicons when they’re provided. Chrome for Android picks the highest res icon that you provide, and we recommend providing a 192×192px PNG file. For example: `<link rel="icon" sizes="192x192" href="nice-highres.png">`

However in my code with "Site Icon" module I can see only:
```
<link rel="icon" href="http://zschocianow.nazwa.pl/wordpress/wp-content/uploads/2015/04/512px-55411bc1v1_site_icon-32x32.png" sizes="32x32" />
<link rel="apple-touch-icon-precomposed" href="http://zschocianow.nazwa.pl/wordpress/wp-content/uploads/2015/04/512px-55411bc1v1_site_icon-128x128.png">
<meta name="msapplication-TileImage" content="http://zschocianow.nazwa.pl/wordpress/wp-content/uploads/2015/04/512px-55411bc1v1_site_icon-128x128.png"/>
```

So seems like should be updated.

By the way, why providing only one size favicon?
Multisize is nice, check [my favicon](http://fundacja.kuzniczysko.pl/wp-content/themes/mlyn/favicon.ico) (in 6 sizes, check in Windows' image browser) generated by [ConvertICO.com](http://www.convertico.com/).

Greetings

**Comment by jeherve** [comment]
Related: #1715

It's worth noting that Core will include its own Site Icon feature in 4.3, so Jetpack's module might be deprecated. Keep an eye on #2326 to find out more.

**Comment by kraftbj** [comment]
Related: Core/4.3's site icon doesn't output this size either (since they used our code as a base). Opened ticket over there at https://core.trac.wordpress.org/ticket/32964 and noted over on #2326.

**Comment by aheckler** [comment]
First peek at the API that core will be using: https://make.wordpress.org/core/2015/07/27/site-icon/

**Comment by kraftbj** [comment]
Going to mark this as closed since the original issue was the lack of 192x192, which was added to Core via https://core.trac.wordpress.org/changeset/33202
