### ISSUE TITLE
Markdown doesn't work for WooCommerce short product descriptions

### ISSUE THREAD

**Issue by ericelliott** [Automattic/jetpack#2396]
## Summary

The Jetpack markdown feature doesn't work for WooCommerce short product descriptions.

## Steps to reproduce

* Activate jetpack and the Markdown extension
* Create a WooCommerce product
* Use Markdown syntax for both the short and long product descriptions
* Save the product

## Expected behavior

The Markdown descriptions should be transformed into HTML for display.

## Actual behavior

* The short description is not converted.
* The long description is converted.

## Screenshot

<img width="994" alt="screen shot 2015-07-11 at 3 26 57 pm" src="https://cloud.githubusercontent.com/assets/364727/8635485/5d8c1aca-27e1-11e5-8bf4-0f575b6c9cc3.png">

**Comment by kraftbj** [comment]
I'm unsure if this is a problem on our end, WooTheme's end, or neither. I'm not familiar enough with WC yet to be sure. Notably, I'm not sure what actually generates the short description and if it is something that Jetpack ever expected to be markdown'd. Currently, we look for the post content in supported post types (WC products having declared support for markdown in their plugin). 

It appears the short description is based on the `excerpt`.

If so, the real request is to enable Markdown conversion on the excerpt for support post types; however, by default, `the_excerpt` strips down to 55 words with no HTML (unless a plugin rebuilds it, which is my initial thought on what WC does). In other words, the average WordPress install wouldn't support non-plain-text excerpts in either case.

Based on https://github.com/Automattic/jetpack/issues/155#issuecomment-33733100, I think this is something that could be raised on WooCommerce's GitHub as an improvement if they'd like to offer Markdown support for short descriptions.

Leaving it open for a second set of eyes, but I think this is a `wontfix` punting to WooCommerce. 

@mattwiebe or @mikejolley, any thoughts?

**Comment by ericelliott** [comment]
> It appears the short description is based on the excerpt.

WooCommerce lets you use anything you want in the short description. Screenshot:

<img width="1378" alt="screen shot 2015-07-11 at 5 56 34 pm" src="https://cloud.githubusercontent.com/assets/364727/8635784/47d72750-27f6-11e5-87c0-5b2dec58936f.png">

Note that I'm using HTML here instead of Markdown.

**Comment by claudiosmweb** [comment]
Done https://github.com/woothemes/woocommerce/commit/eea72552f6237b3781b4eb999d218584900871f7

**Comment by ericelliott** [comment]
Thanks @claudiosmweb. That was quick! =)
