### ISSUE TITLE
Widget Visibility function doesn't work

### ISSUE THREAD

**Issue by mariojram** [Automattic/jetpack#2397]
I am trying to hide a "log in" text in a widget area when users are logged in and show it only on one page when the user is logged out.. The option for "show if" - "user is" - "logged out" shows up and saves but does not hide the the text when the user is logged in. 

www.pureskilltraining.com/rush

**Comment by jeherve** [comment]
Could you contact us via [this form](http://jetpack.me/contact-support/), so we can run some more tests with you?

Thanks!

**Comment by mariojram** [comment]
how do I contact you?
