### ISSUE TITLE
My Jetpack: Make the default purchase flow easier to implement

### ISSUE THREAD

**Issue by leogermani** [Automattic/jetpack#23972]
Originally discussed in https://github.com/Automattic/jetpack/issues/23171

Our `ConnectScreenRequiredPlan` shows the product prices but do not redirect the user to the checkout page. It only connects the user.

We need to make it easier for consumers to implement a flow that will:

* Connect the site
* Redirect the user to the checkout page with `unlinked=1`

This will allow all products to have the same connection/purchase flow, without the need to add special rules to Calypso (as Backup did, and Search is trying to avoid)

We need to decide what intelligence will be bundle inside the component, and what we will leave out for consumers to implement. But in any case, we need to make it easy for developers to find this path.

**Comment by kangzj** [comment]
Hi @leogermani Just want to add, could we know if a site has Search (or backup, Complete etc) plan before connecting? If a site already has a subscription, then a user might still click the `Get xxx product` button where we might only want to connect the site but not to checkout the product.

Search plugin is tracking the issue [here](https://github.com/Automattic/jetpack/issues/24289).

**Comment by leogermani** [comment]
done in https://github.com/Automattic/jetpack/pull/24122
