### ISSUE TITLE
PBE: Shortcode to set post format

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#240]
Add a shortcode to the PBE parser to allow author to set Post Format via e-mail.

Ported from https://plugins.trac.wordpress.org/ticket/2055
See: 2443-wpcom

**Comment by samhotchkiss** [comment]
Our implementation of Post by Email is intended to be very simple and minimal, so, unfortunately, this doesn't align with our development goals and plans at this time, and is not on our roadmap for future development.
