### ISSUE TITLE
Remove payments block from no-editor bundle

### ISSUE THREAD

**Issue by johngodley** [Automattic/jetpack#24031]
### Impacted plugin

None / Other

### Steps to Reproduce

A new payments extension was added in #23118. This uses the `@wordpress/edit-post` module, which causes all Jetpack blocks to not be loaded on wp.com P2 (it's only used in the core WP editor).

I think removing this from the `no-post-editor` bundle should fix the problem, like what happened in https://github.com/Automattic/jetpack/pull/23142

### Browser

Chrome/Chromium

**Comment by jeherve** [comment]
The new Payments extension is not included in the no-editor bundle, so I don't believe that's what's causing the issue. The Payment button block, however, seems to be problematic here. #24076 (and its counterpart D79443-code) should solve this.
