### ISSUE TITLE
Subscriptions: email templates issues -- Primary Issue

### ISSUE THREAD

**Issue by mihpaese** [Automattic/jetpack#24036]
Following the updates to the subscription email templates, here is a collection of the feedback we received about the changes:

- [ ] #24053 
- [ ] #24054
- [ ] https://github.com/Automattic/wp-calypso/issues/62986
- [ ] https://github.com/Automattic/wp-calypso/issues/62989
- [ ] https://github.com/Automattic/wp-calypso/issues/62990
- [ ] https://github.com/Automattic/wp-calypso/issues/62992
- [ ] https://github.com/Automattic/wp-calypso/issues/62994
- [ ] https://github.com/Automattic/wp-calypso/issues/63029
- [ ] https://github.com/Automattic/wp-calypso/issues/63063
- [ ] https://github.com/Automattic/wp-calypso/issues/63152
- [x] https://github.com/Automattic/wp-calypso/issues/62997
- [x] https://github.com/Automattic/wp-calypso/issues/62939
- [x] https://github.com/Automattic/wp-calypso/issues/62996
- [ ] https://github.com/Automattic/wp-calypso/issues/62995
- [ ] https://github.com/Automattic/wp-calypso/issues/63111

**Comment by mihpaese** [comment]
Reported:
- 4963821
- 4961553
- 4961613
- 4962942
- 4962551

**Comment by jeherve** [comment]
> I am opening this issue to concentrate on all the tickets related to the project that reached our support.

Do you think you could open separate issues for each problem? You could still use this issue as the Primary issue where references to each individual issue is gathered.

Thank you!

**Comment by zdenys** [comment]
From 4965948-zd-woothemes (with screenshots):

>Readability is significantly reduced beginning April 20: oversized, boldface title; narrower text block; in the poem, the line spacing doesn't at all reflect the post as seen on the blog.

**Comment by foleynotrose** [comment]
Breaking this issue into separate issues, as requested by @jeherve: 

- [Remove Comment and Like buttons](https://github.com/Automattic/jetpack/issues/24052)
- [Make post title smaller](https://github.com/Automattic/jetpack/issues/24053)
- [Incomplete links at bottom of email](https://github.com/Automattic/jetpack/issues/24054)

**Comment by paxblueribbon** [comment]
hc-32486597

In this as well as a zd ticket I saw in an earlier shift but now can't find, customer reports that new email template no longer contains the correct avatar for the person liking, but a more generic avatar which sounds like the gravatar default.

**Comment by shykonessy** [comment]
Hello... kindly revert the recently updated the email subscription newsletter. It has deleted the tags section, category section and direct link to the post.

**Comment by kspilarski** [comment]
Instead of the WordPress logo on the email, the user prefers to replace it with their site logo.

<img width="903" alt="logo" src="https://user-images.githubusercontent.com/36863633/164977183-8fbf4bb2-d3c6-45e4-8c32-d137a04d6564.png">
 
Report: 33338056-hc

**Comment by yansern** [comment]
> Instead of the WordPress logo on the email, the user prefers to replace it with their site logo.

@kspilarski For this one, user can set a site logo through General Settings and it will be used on their e-mails.

> Breaking this issue into separate issues, as requested by @jeherve:
> 
> * [Remove Comment and Like buttons](https://github.com/Automattic/jetpack/issues/24052)
> * [Make post title smaller](https://github.com/Automattic/jetpack/issues/24053)
> * [Incomplete links at bottom of email](https://github.com/Automattic/jetpack/issues/24054) 

Thanks @foleynotrose. cc @mashikag we've got some duplicate issues to consolidate, the incomplete links is new though.

- https://github.com/Automattic/wp-calypso/issues/62997
- https://github.com/Automattic/wp-calypso/issues/62990

> hc-32486597
> 
> In this as well as a zd ticket I saw in an earlier shift but now can't find, customer reports that new email template no longer contains the correct avatar for the person liking, but a more generic avatar which sounds like the gravatar default.

One more for https://github.com/Automattic/wp-calypso/issues/62996.

**Comment by mashikag** [comment]
Another one in relation to horizontal margin/padding on new email templates opened in gmail client on mobile devices: https://github.com/Automattic/wp-calypso/issues/63111

**Comment by bobmatyas** [comment]
Added a request to remove the app icons to the list above: https://github.com/Automattic/wp-calypso/issues/63152
