### ISSUE TITLE
Google Analytics: audit and update both our Legacy and Universal Analytics solutions to support GA 4.

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#24048]
> [Google Analytics 4](https://support.google.com/analytics/answer/10089681) is our next-generation measurement solution, and is replacing Universal Analytics. On 1 July 2023, Universal Analytics properties will stop processing new hits. If you still rely on Universal Analytics, we recommend that you complete your move to Google Analytics 4.
-- [Reference](https://blog.google/products/marketingplatform/analytics/prepare-for-future-with-google-analytics-4/)

We'll consequently need to make some changes to our existing implementation to support this.

https://github.com/Automattic/jetpack/blob/8898e596b94fc8c0b0b27dcb025f70bdb599ff34/projects/plugins/jetpack/modules/google-analytics/wp-google-analytics.php#L54-L61

******

Related work: #17795

Internal references:

- pau2Xa-48B-p2
- pbNhbs-3ir-p2#comment-9519

******

cc @gmovr

**Comment by gmovr** [comment]
Also, from my testing, and what I've seen online, AMP is still not compatible with GA4 (despite having the `gtag.js` implemented, as this is also used for Google Ads tracking).

Regarding ecommerce tracking, this is also different. Here's some context on ecommerce tracking in GA4 - which is pretty much what we're planning to integrate in Calypso.

https://developers.google.com/analytics/devguides/collection/ga4/ecommerce?client_type=gtag

**Comment by jeherve** [comment]
Related: #9335

**Comment by jeherve** [comment]
This was implemented in #17795. I'll close this now.
