### ISSUE TITLE
Publicize: `publicize_checkbox_default` removes checkboxes but sharing still happens. Doc update needed?

### ISSUE THREAD

**Issue by lschuyler** [Automattic/jetpack#24059]
### Impacted plugin

Jetpack

### Steps to Reproduce

To prevent automatic sharing, I've added this to my theme's functions.php file:

```
if ( class_exists( 'Jetpack' ) && Jetpack::is_module_active( 'publicize' ) ) {
  add_filter( 'publicize_checkbox_default', '__return_false' );
}
```

It removes the checkboxes beside the connected Twitter account(s), but Publicize still fires and the tweet is published.

<img width="278" alt="Screen Shot 2022-04-22 at 12 31 06 PM" src="https://user-images.githubusercontent.com/4307088/164781854-473136c3-4401-4261-b2b2-dbb618daa234.png">

### A clear and concise description of what you expected to happen.

The `publicize_checkbox_default` documentation on https://developer.jetpack.com/hooks/publicize_checkbox_default/ contains a note that says `Important: there are currently some issues with this filter. It is recommended not to use until [this issue](https://github.com/Automattic/jetpack/issues/1550) is solved.`

That [issue](https://github.com/Automattic/jetpack/issues/1550) is solved, however this filter is not currently working as expected.

### What actually happened

It removes the checkboxes beside the connected Twitter account(s), but Publicize still fires.

Without this filter in place, if I manually uncheck the checkmark beside my connected Twitter account, the post is *not* shared on Twitter when published.

### Other information

An example post where I tested this: 
blog_id=106565671
post_id=9022

This happens with the Block editor.

### Browser

Chrome/Chromium

**Comment by coder-karen** [comment]
Can confirm - even just adding `add_filter( 'publicize_checkbox_default', '__return_false' );` via a Code Snippets plugin has the same result (post published to both Twitter and Facebook despite the toggles now being off on the test post). Only worked with the Classic Editor plugin active.

**Comment by BrookeDot** [comment]
@coder-karen @pablinos  I removed the note in the docs as this issue has been closed. Let me know if we need to add it back.
