### ISSUE TITLE
Protect: only show Dashboard widget footer to contributors and above

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2405]
Right now, Core doesn't display the number of comments Akismet blocked to subscribers. Only contributors and above can see that number:
![screen shot 2015-07-15 at 1 56 49 pm](https://cloud.githubusercontent.com/assets/426388/8698030/6c05aca8-2afa-11e5-91f1-4ce70c2246fe.png)

It would be nice if the same rules applied to the numbers appearing below the Jetpack dashboard widget.

Suggested here:
https://twitter.com/user/status/621235395666268160

**Comment by aheckler** [comment]
Why not just limit it to admins only with `current_user_can( 'jetpack_manage_modules' )`? Otherwise custom user roles (such as those set up by WP Job Manager) might be able to see the number as well.

**Comment by jeherve** [comment]
Since the dashboard widget's footer includes Akismet stats as well, it seemed logical to follow Akismet's lead and display the stats when Akismet would display their own footer.

I don't have anything against limiting it to admins, though.

**Comment by jeherve** [comment]
Also requested here:
https://wordpress.org/support/topic/remove-widget-from-user-dashboard?replies=1&view=all

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
