### ISSUE TITLE
Jetpack settings table rows are hidden in views < 782 in WP trunk 

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#2406]
Some CSS changes were made to wp_list_table that is messing with our Settings table.  

https://cloudup.com/cGOHTtSs2JL

You can see the culprit in the console there.

**Comment by jeffgolenski** [comment]
I'm finding it at < 783, but digging deeper... should have a solution today.

**Comment by dereksmart** [comment]
I dunno where I got 768 from... clearly says 782 in the console.

**Comment by georgestephanis** [comment]
`3 x 2^8`, duh.

**Comment by jeffgolenski** [comment]
Repaired in: https://github.com/Automattic/jetpack/pull/2410
