### ISSUE TITLE
Search: Unpredictable behavior, "classic" search loads in place of instant, or instant search missing filters

### ISSUE THREAD

**Issue by xpurichan** [Automattic/jetpack#24067]
### Impacted plugin

Search

### Steps to Reproduce

With Jetpack Instant Search enabled we have experienced behaviors where the "instant" search modal doesn't load and instead displays the classic embedded search. We have also experienced an issue with the filter options (such as "categories") do not load in the instant search modal.

Both issues have been experienced on the same site (`tim.blog` in this example), and there have been similar reports on other sites.

Screenshot of the `tim.blog` site showing console errors during a time when the search filters were not loading in the instant search modal:
<img width="988" alt="162269336-8be8e436-d1ce-482b-b6e5-ddc2e7a00ab5" src="https://user-images.githubusercontent.com/33190975/164799575-49e9141d-6327-4afb-9a96-ecfa89dcdb38.png">

Ongoing Slack discussion in to this matter:
p1650549730114609-slack-jetpack-search-team

Possibly related: 
* https://github.com/Automattic/jetpack/issues/19752
* 4952768-zen - example here is likely a conflict with Cloudflare's Rocket Loader which is **disabled** on the problematic/example site in this issue.
   * p1650447115419289-slack-jetpack-crew - further discussion on Cloudflare and Rocket Loader

### A clear and concise description of what you expected to happen.

Jetpack Instant Search is enabled on this `tim.blog` website and should display the modal and all options upon searching.

### What actually happened

Sometimes the modal doesn't load at all (and the "classic Jetpack" search displays inline on the website instead), other times we see the modal load but filter options such as "categories" are missing.

### Browser

Other / Not applicable

**Comment by jsnmoon** [comment]
Keeping this issue open until we've confirmed that #24068 has resolved the issue with our partner.

**Comment by xpurichan** [comment]
@jsnmoon it looks like that ⬆️ has been merged, but correct me if I'm wrong. Just wanted to check on this issue.

**Comment by jsnmoon** [comment]
@xpurichan: Correct — #24068 has been merged and shipped with Jetpack 10.9 on May 3, 2022. I'd be happy to close out this issue if the issue has been satisfactorily resolved for our partner. Thanks!

**Comment by xpurichan** [comment]
@jsnmoon unfortunately I'm still able to replicate one of these problems. Right now I'm testing search in both Chrome and Safari - Chrome displays JP Instant Search as expected, but Safari displays the old inline search (in a regular and private window):

![Screen Shot 2022-05-12 at 6 13 27 PM](https://user-images.githubusercontent.com/33190975/168176387-36d936f9-b5b4-4933-9f31-1462795746c7.jpg)

Is there any information I can provide that would be helpful to you all?

**Comment by jsnmoon** [comment]
> @jsnmoon unfortunately I'm still able to replicate one of these problems. Right now I'm testing search in both Chrome and Safari - Chrome displays JP Instant Search as expected, but Safari displays the old inline search (in a regular and private window):
> 
> Is there any information I can provide that would be helpful to you all?

I suspect Safari might be loading the old script (without the fix) from its browser cache. If you inspect the network request console in the browser console, you should see a request for `jp-search.js` from `pressablecdn.com`. What `ver` query value is it showing? For example, my request looks like...

`
https://149346886.v2.pressablecdn.com/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-search/build/instant-search/jp-search.js?minify=false&ver=c8894fcbf2245626cfd88d5a4f095d45
`

...with a `ver` query value `c8894fcbf2245626cfd88d5a4f095d45`.

If your Safari is showing a different `ver` value, could you try clearing all website data for `pressablecdn.com` and try loading `tim.blog` again? We might want to loop in someone who has worked on Pressable's CDN infrastructure for a better understanding of the root cause here.

**Comment by xpurichan** [comment]
@jsnmoon Sorry for the delay, I've been AFK.

I'm not seeing anything labeled `ver`, could you confirm where I would find this? Currently in the Network tab of the dev tools and I expected I might find this in the `Name` column (though I didn't spot it in any of the columns).

I'm also not familiar with how to expand the `Domain` column which I believe contains the URL you are looking for. Hovering over the domains or clicking on them gives no response, I also can't expand the column width (only shrink it).

![Screen Shot 2022-05-18 at 11 04 04 AM](https://user-images.githubusercontent.com/33190975/169074099-df502f9b-a79e-4f43-93d0-73cc030d67e4.jpg)

**Comment by jsnmoon** [comment]
> I'm not seeing anything labeled `ver`, could you confirm where I would find this? Currently in the Network tab of the dev tools and I expected I might find this in the `Name` column (though I didn't spot it in any of the columns).
> 
> I'm also not familiar with how to expand the `Domain` column which I believe contains the URL you are looking for. Hovering over the domains or clicking on them gives no response, I also can't expand the column width (only shrink it).

Hi @xpurichan, you're on the right screen! Filter for `jp-search` and select `jp-search.js`; you'll be able to see the full network details like so:

<img width="638" alt="Screen Shot 2022-05-20 at 3 45 38 PM" src="https://user-images.githubusercontent.com/4044428/169621561-76e2b8f8-31d4-4342-b7a5-f9d6282cc307.png">

It looks like the current `ver` value is now `4f32b117c96d367b8ad614ecfa278164`.

--- 

If you need to clear the browser data, you can do so in the Safari privacy settings:

<img width="796" alt="Screen Shot 2022-05-20 at 3 43 48 PM" src="https://user-images.githubusercontent.com/4044428/169621439-7cc10be7-47d4-4e7c-bfc6-c8cbb0fc8975.png">

<img width="796" alt="Screen Shot 2022-05-20 at 3 44 05 PM" src="https://user-images.githubusercontent.com/4044428/169621453-a38aeadd-98fe-4c85-b22f-73aecb30e797.png">

**Comment by xpurichan** [comment]
That did it @jsnmoon ! 🙌 I'm going consider this to be resolved unless we get another report in the future. Thanks for your help on this one.
