### ISSUE TITLE
My Jetpack is missing content.

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#2411]
Maybe this is just my dev site but I came across this 
![image](https://cloud.githubusercontent.com/assets/115071/8736589/ab1649e6-2bce-11e5-8a6c-bbd3bb9ff766.png)

I am not quite sure I am able to replicate how I got here. ( I switched branches from 3.2 to master ).

Resetting everything using the reset link do anything. I am also not able to find the disconnect link that used to be in the footer.

**Comment by jeffgolenski** [comment]
Hm. Strange. Unable to reproduce. @dereksmart can you try and reproduce as well? Might just be a lag from branch switching... 

@enejb if you re-sync master and clear your cache does the issue go away?

**Comment by dereksmart** [comment]
Yeah, @enejb could you please make sure all the code has been <a href="https://github.com/Automattic/jetpack/pull/2402#issuecomment-122012223">properly uploaded to your server</a>?  If it is, please check the console for js errors that may be causing the template to not load.  Thanks!

**Comment by enejb** [comment]
Sorry for the reporting this. It looks like my code was not all up to date and was missing some files. 
I don't think this is an issue any more.
