### ISSUE TITLE
Search Standalone: Add the stats module to the plugin.

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#24111]
### Impacted plugin

Search

### Steps to Reproduce

Install the plugin standalone, and there are not stats being tracked.

### A clear and concise description of what you expected to happen.

A core part of the search algorithm is based off of stats from the site, so the search algorithm won't work very well if we don't have the stats module also in the plugin.

Not really a blocker for launching the standalone plugin, but will need to be supported. I think other standalone plugins may have this same problem. It doesn't really need the UI, we just need the stats pixels on every page load whenever Search is installed or turned on.

cc @ebinnion 

### Browser

Other / Not applicable

**Comment by jeherve** [comment]
This was implemented in #26697.
