### ISSUE TITLE
Jetpack Boost: Timeout error message is too shy with the details

### ISSUE THREAD

**Issue by pyronaur** [Automattic/jetpack#24115]
### Steps to Reproduce

When Cloud CSS Fails, the timeout message isn't very informative for anyone involved.

![Screen Shot 2022-04-27 at 6 42 40 PM](https://user-images.githubusercontent.com/988095/165557828-6a8fb758-03e6-49f9-9cbd-27feeb424aee.jpg)

**Comment by thingalon** [comment]
After a discussion at our team meeting:
- The "timeout" message only occurs when a message has been successfully sent to the back-end, but no response has been received by the UI, so this case doesn't cover all possible "timeout" issues.
- For now, we will just improve the wording of the "timeout" error to include more details. e.g.: "Timeout while waiting for Critical CSS from the Boost Service", to make it clear where the timeout was.
- We will need to document how to investigate this kind of issue for our HEs here: PCYsg-GRe-p2
- We should make sure this will get captured by a Tracks event so we can identify if this is a common problem.
