### ISSUE TITLE
VideoPress: if "Display share menu and allow viewers to embed or download this video" is not checked, videos cannot be embedded on Jetpack sites

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#2412]
In the previous VideoPress iteration, there was an option to limit embedding to certain whitelisted domains. That option no longer exists in the current iteration. This means that if a user decides to uncheck the "Display share menu and allow viewers to embed or download this video" option on their video once it's uploaded to the WordPress.com site with the VideoPress subscription, they cannot embed the videos on their linked Jetpack site.

Note, however, that if a user had previously whitelisted a domain before the change to the new version, it appears that the whitelist is still taken into account if the option is unchecked; this is based on one Livechat conversation with a user, and is not 100% certain. 

cc @spncrb

**Comment by csonnek** [comment]
Also reported in #2221695-t

**Comment by jeherve** [comment]
Closing as this doesn't apply in the new VideoPress implementation.

**Comment by BurlesonBrad** [comment]
is this board still active? https://github.com/Automattic/jetpack/projects/1
The bigger picture question I have here is this:
Does the JP team have any intentions of URL restricting videos so that they can't be viewed outside of the client's site?
@jeherve

**Comment by jeherve** [comment]
cc @pgk who may be able to give us more information about the work he's been doing with VideoPress and private videos.
