### ISSUE TITLE
VideoPress: Editor block error when disabling VideoPress

### ISSUE THREAD

**Issue by coder-karen** [Automattic/jetpack#24144]
### Impacted plugin

Jetpack

### Steps to Reproduce

This issue only occurs when private videos are available (post 10.9).

1. Enable VideoPress.
2. Upload a new video whilst editing a post, and save that post.
3. No need to change the privacy level of the video (default works fine here).
4. Disable VideoPress.
5. Go back to the post editor, and a block error will show in place of the video. 
6. Any videos added prior to this specific release are not affected.

This issue was surfaced during internal testing: p8oabR-QB-p2#comment-6215

### A clear and concise description of what you expected to happen.

I expected to see the video available for editing, instead of a block error.

### Other information

<img width="679" alt="Screenshot 2022-04-28 at 15 27 25" src="https://user-images.githubusercontent.com/16754605/165775385-4c360622-b364-48b7-9391-c209b714ffec.png">

### Browser

Chrome/Chromium

**Comment by jgcaruso** [comment]
Reproduced and working on a fix!
