### ISSUE TITLE
Social Icons Widget: add LinkedIn Groups

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#2415]
As requested in 2265528-t, LinkedIn Groups have a different URL structure and thus can't be used in the Social Icons widget. This is the structure it uses:

https://www.linkedin.com/grp/home?gid=XXXXXXX

**Comment by flammable** [comment]
Thanks Richard, I really appreciate it!

**Comment by jeherve** [comment]
Related: #2234

**Comment by jeherve** [comment]
Also add LinkedIn Company pages:
https://wordpress.org/support/topic/linkedin-username-for-company-page?replies=1&view=all

**Comment by csonnek** [comment]
Another request for company page support in 2506026-t

**Comment by jeherve** [comment]
Closing, as it is now possible to add new widgets thanks to the `jetpack_social_media_icons_widget_array` filter (see #2741)
