### ISSUE TITLE
Portfolios Broken on Simple Sites

### ISSUE THREAD

**Issue by khristiansnyder** [Automattic/jetpack#24157]
### Quick summary

Portfolios are not working on simple sites. Dashboard link doesn't show up in Calypso despite portfolios being turned on. 

The link does show in WP-Admin, but opening an existing project (or creating a new project) leads to a blank page.

The front end shows errors for portfolio shortcodes as well, despite them being enabled and having several projects: `Your Portfolio Archive currently has no entries. You can start creating them on your dashboard.`

![Markup on 2022-04-28 at 10:30:24](https://user-images.githubusercontent.com/41035049/165812739-f1e83d89-c0ba-495f-9e4b-ba9c978b65c3.png)

### Steps to reproduce

1. On a simple site with Portfolios enabled, try to navigate to Calypso's portfolio page
2. Try to navigate to WP-Admin's portfolio page and create a new project.

### What you expected to happen

Portfolio should show as a link in Calypso, and projects should show on the front end using the shortcode. 

### What actually happened

Using a direct link to a Calypso portfolio page gives an error: https://wordpress.com/types/jetpack-portfolio/**Domain**

```
Portfolios are not enabled
Activate custom content types in your site settings
```

Error shows on front end:
![Markup on 2022-04-28 at 10:34:55](https://user-images.githubusercontent.com/41035049/165813468-11e6c17b-b36b-479f-8e6a-4638091f792d.png)
 

### Context

Reported in #8906460-hc and I was able to replicate on a test site. 

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

Most (> 50%)

**Comment by kraftbj** [comment]
Looking at the WP.com side of the change, the function `site_supports_custom_post_type()` was added with the change. @jeherve Could you own confirming and getting the original PR re-applied with the suitable fixes?

**Comment by anomiex** [comment]
D79753-code reverts the revert and brings back the change from r108923-wpcom that had gotten lost, which seems to fix it. Testing and review on that would be welcome.

**Comment by sharonlaker19** [comment]
I had a user report this on 5175772-zen. The above fix seems to have resolved the issue on their site too.

**Comment by jeherve** [comment]
#24150 (which brings the 2 codebases in sync, including @anomiex's fix above) fixes the issue for Jetpack as well.

**Comment by zdenys** [comment]
- [ ] The user in 5175964-zd-woothemes asked to email them once the patch is in place.

**Comment by jeherve** [comment]
> * [ ]  The user in 5175964-zd-woothemes asked to email them once the patch is in place.

The problem reported by this user was fixed in D79780-code (and ported to Jetpack as part of #24150)

**Comment by aleone89** [comment]
The user in 5175964-zd-woothemes has returned from chat ( hc-35324670 ) is reporting that excerpts and tags are showing, when defined in the shortcode to not display - I can replicate this problem on the site.

**Comment by jeherve** [comment]
@aleone89 Sorry for all the back and forth. We should be good to go now, I fixed that last issue.

The problem was fixed in D79785-code, and ported to Jetpack as part of #24150.

**Comment by dragstor** [comment]
Now works in 5175964-ZD.
