### ISSUE TITLE
Add "Disable" Link to Jetpack Monitor Emails

### ISSUE THREAD

**Issue by macmanx2** [Automattic/jetpack#2416]
In support, we get our fair share of "Please disable Jetpack Monitor" requests from site owners who no longer have access to their sites for legitimate reasons (they shut down the site, gave it to someone else, intentionally allowed everything to expire, etc).

These could all be avoided if we gave them a special link at the bottom of the emails to disable the monitor, similar to the subscription email's Manage Subscriptions link.

**Comment by dereksmart** [comment]
duplicate #1614

**Comment by macmanx2** [comment]
Gah, my poor decrepit search skills. :(

**Comment by dereksmart** [comment]
good suggestion tho! :100:
