### ISSUE TITLE
Contact form: error when exporting feedback to csv

### ISSUE THREAD

**Issue by kelasante** [Automattic/jetpack#24170]
### Quick summary

When downloading Form responses in Feedback, a user gets an error **_This site can’t be reached. The webpage page might be temporarily down or it may have moved permanently to a new web address._**

I am able to replicate the issue on my Simple test site 
<img width="857" alt="Markup 2022-04-25 at 11 05 03" src="https://user-images.githubusercontent.com/74204272/165138388-c1b81c06-8b94-4787-af75-c0ed319601f1.png">

This happens in the Chrome and Firefox browser. I tested in Safari and it seems to work. 

### Steps to reproduce

1. Go to My Site > Feedback
2. Click on Download button 
3. Get error message "This site can’t be reached. The webpage page might be temporarily down or it may have moved permanently to a new web address."

### What you expected to happen

To download form entries as CSV

### What actually happened

On my simple site, I got the webpage might be temporarily down error in Chrome and Firefox. Safari works fine. Another HE was able to replicate this on Chrome.

On my atomic site, I got a blank page. However, another HE tested with an atomic site and it works for them. 

### Context

In 35277177-hc, user mentioned they are not able to download form entries. 

### Simple, Atomic or both?

Simple

### Browser, operating system and other notes

The issue seems to happen on Chrome and Firefox 

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by jeherve** [comment]
I cannot seem to reproduce on my end on a self-hosted site, but I can reproduce on a WordPress.com simple site. 

I see no errors in the logs, but the export fails somewhere here:
https://github.com/Automattic/jetpack/blob/8e0dff02179e33e6e7bf357a03e5c18abe2aa08c/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php#L1520-L1553

**Comment by kdevnel** [comment]
Depending how long this takes to get a solution, I would like to share a temporary workaround - it's not fast so wouldn't be recommended in most cases but might help others depending on the specific scenario.

* You can export just the feedback from the standard Calypso exporter as an XML. 
* Then you can convert that to a CSV using a converter tool.
* Open the CSV and remove some of the unneeded empty columns at the start
* Find the page ID for the page you need the feedback
* Using Sheets, Excel or Numbers you can filter the "wp:post_parent" column for only that post ID
* Copy all of that view and paste into a new sheet
* Export as a CSV to share

Labour-intensive but helpful in urgent cases.

**Comment by vishnugopal** [comment]
I seem to have found the cause and the fix, but am uncertain how to deploy this. Please see p1651226424159739/1651215033.747819-slack-C01A60HCGUA and if anybody from the @Automattic/jetpack team can provide guidance, that would be great.

**Comment by vishnugopal** [comment]
Fixed in D79787-code and deployed. This should be fixed now.

**Comment by Robertght** [comment]
cc @Agepeuve about the thing you saw a few days ago.
