### ISSUE TITLE
Search: Redirect customers to the Search dashboard following standalone plugin activation

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#24286]
Reported in p1HpG7-fTB-p2#comment-54307:

> [...] I think that it would be best if the user is automatically redirected to the pre-purchase page after installing the standalone Jetpack Search plugin, rather than having to navigate to it on their own. If the user is automatically redirected to the purchase page for JP Search, it will reinforce that JP search can only be used with a subscription.

**Comment by kangzj** [comment]
we could potentially refer to this one: https://github.com/Automattic/jetpack/pull/24161
