### ISSUE TITLE
Investigate future steps for Lazy Loading

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#24290]
Now that [Safari has native support for lazy loading images](https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/), we can consider whether our implementation of lazy-load can be scaled back / simplified.

[According to caniuse](https://caniuse.com/loading-lazy-attr), all of the major browsers support lazy loaded images natively.

There are a couple of paths ahead of us to consider:

1. We can test that the `loading=lazy` attribute works as well as our custom Lazy Loading method, and simplify the module to use that, or
2. We can add new features to our Lazy Loading module such as placeholder images and fixed image sizing.

As a first step, we need to explore the above two options. This issue involves:

* Investigate if there is a substantial behavior difference between our (Jetpack's) implementating of Lazy Loading, and the attribute-based implementations in major browsers,
* Test the idea of using Placeholder images in Jetpack's Lazy Loading implementation.
* Post a P2 about the above test so that we can decide on the path ahead.

**Comment by samiff** [comment]
> Consider the impact of switching over.

I think core's implementation for native lazy images should work great for the majority of users, and the main reason at this point to keep around our JS based lazy loading would be to provide additional features - the most compelling being custom image placeholders (blurred image, dominant color, etc.).

**Comment by jeherve** [comment]
> the most compelling being custom image placeholders (blurred image, dominant color, etc.).

That's a good point. If we were to keep our custom implementation around though, we would have to make those potential customizations more prominent, because right now most people wouldn't know how to make use of those.

**Comment by thingalon** [comment]
Blurred placeholders are something that we've wanted to investigate for Boost for a while. It may be worth having that feature available for Boost, but not for Jetpack, to encourage more users to install Boost ;)

**Comment by jeherve** [comment]
Closing in favor of #33048.
