### ISSUE TITLE
Search Plugin: Replace post-activation redirection with a one-time notice and a Settings link

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#24354]
Reported by @a8ck3n in p1HpG7-fTB-p2#comment-54337.

Remove the post plugin activation redirect with a notice for better adherence to typical plugin activation UX. In its place, add a one-time notification notice to the top of the Plugins page as well as a "Settings" link for the Search plugin item.

**Comment by kangzj** [comment]
Setting links are added via #25718; And the redirection is pretty good so we tend to leave it for now.
