### ISSUE TITLE
[Boost] Improve messaging if the site score drops

### ISSUE THREAD

**Issue by mikemayhem3030** [Automattic/jetpack#24358]
### Impacted plugin

Boost

### What

Infobox if the Boost Performance Score drops

### How

Sometimes the score reported and displayed by the plugin aren't quite right and hitting refresh will bring them back to what they actually are. 

<img width="1253" alt="Screenshot 2022-05-12 at 07 19 52" src="https://user-images.githubusercontent.com/4077604/168234404-76d93f07-5fad-4f87-8a86-ac62877c0127.png">

Add a fly out if the score drops to prompt to refresh the score, or if the problem continues contact support

**Comment by eAdnan007** [comment]
What if we auto refresh at least once if the score dropped due to enabling boost features?

**Comment by mikemayhem3030** [comment]
> What if we auto refresh at least once if the score dropped due to enabling boost features? 

That's an option too, from chatting to Mark I think we already do a couple of polls before updating the UI. It's a nice issue to cut my teeth on the codebase with.
