### ISSUE TITLE
Publicize: not publishing with Elementor and Jetpack 10.9+

### ISSUE THREAD

**Issue by Netspacer** [Automattic/jetpack#24383]
### Impacted plugin

Jetpack

### Steps to Reproduce

Autopost on facebook page (Publicize ) not working after upgrade to 10.9 on may 3.

Edit:

- Using Jetpack 10.8 and Elementor (free) to publish a post works to Publicize to Facebook.
- Using Jetpack 10.9+, posts published with Elementor do not Publicize to Facebook.

### Browser

Chrome/Chromium, Firefox, Microsoft Edge

**Comment by samiff** [comment]
Hi @Netspacer 👋 

We haven't picked up on any widespread Publicize issues recently. And on my test site, I was able to see a post published to a Facebook Page.

For your site, I'd encourage you to take a look at the troubleshooting information here:

https://jetpack.com/support/publicize/facebook/#troubleshooting-facebook

Sometimes reconnecting the Facebook connection will work if the rest of the site is functioning as expected, but if you still need help please reach out to Jetpack support here:

https://jetpack.com/contact-support/

**Comment by Netspacer** [comment]
Hi.

I already reconnected and deleted according to your troubleshooting guide.

I have 2 sites that currently have this issue.
I use elementor.

When publishing with the block editor, it posts fine, but using elementor it does not.
Something happened may 3 when updating to 10.9

Don’t know if the issue is with is Jetpack or elementor, but the error was introduced exactly when Jetpack updated to 10.9

My sites are https://naestved-bordtennis.dk/ and https://kviknaestved.dk/


Best regards

Thomas

**Comment by samiff** [comment]
Thanks for the details Thomas. I was able to reproduce and will reopen this issue:

- Using Jetpack 10.8 and Elementor (free) to publish a post works to Publicize to Facebook.
- Using Jetpack 10.9+, posts published with Elementor do not Publicize to Facebook.

cc: @ebinnion @spsiddarthan @danielpost 

In Publicize debug, it doesn't look like the post_meta is saved as expected. I quickly tried a revert of #23976 and tested that which seemed to work. Would one of you be able to have a look?

**Comment by spsiddarthan** [comment]
Thanks for your initial investigation, @samiff! Super helpful. 

So, the reason the Publicizing is not working for posts created using elementor [is this line.](https://github.com/Automattic/jetpack/blob/master/projects/packages/publicize/src/class-publicize-base.php#:~:text=!%20did_action(%20%27wp_ajax_press%2Dthis%2Dsave%2Dpost%27%20)) 

It used to work [before this PR merge](https://github.com/Automattic/jetpack/pull/23976) because the filter publicize_should_publicize_published_post used to always return true, so it's a bit of an anti-pattern that it worked before. 

I am working on a solution [here ](https://github.com/Automattic/jetpack/pull/24387)

**Comment by Netspacer** [comment]
Hi.

I already reconnected and deleted according to your troubleshooting guide.

I have 2 sites that currently have this issue.

I use elementor.

 

When publishing with the block editor, it posts fine, but using elementor it does not.
Something happened may 3 when updating to 10.9

Don’t know if the issue is with is Jetpack or elementor, but the error was introduced exactly when Jetpack updated to 10.9

 

My sites are https://naestved-bordtennis.dk and https://kviknaestved.dk

 

 

Best regards

 

Thomas



 

Fra: Samiff ***@***.***> 
Sendt: 16. maj 2022 22:14
Til: Automattic/jetpack ***@***.***>
Cc: Netspacer ***@***.***>; Mention ***@***.***>
Emne: Re: [Automattic/jetpack] Publicize error after v. 10.9 (Issue #24383)

 

Hi @Netspacer <https://github.com/Netspacer>  👋

We haven't picked up on any widespread Publicize issues recently. And on my test site, I was able to see a post published to a Facebook Page.

For your site, I'd encourage you to take a look at the troubleshooting information here:

https://jetpack.com/support/publicize/facebook/#troubleshooting-facebook

Sometimes reconnecting the Facebook connection will work if the rest of the site is functioning as expected, but if you still need help please reach out to Jetpack support here:

https://jetpack.com/contact-support/
