### ISSUE TITLE
Search: "Get Jetpack Search" button in the pre-connection screen should work for all customer types

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#24398]
### Impacted plugin

Jetpack, Search

### What

"Get Jetpack Search" button should be the only call-to-action for all customer types.

### How

<img width="1094" alt="Screen Shot 2022-05-17 at 5 01 48 PM" src="https://user-images.githubusercontent.com/4044428/168931300-ea17bb5b-0938-4226-9420-cf9164ab1a72.png">

- Remove the `Already have a subscription? Log in to get started` snippet
- Modify `Get Jetpack Search` behavior to handle existing customers. If the site already has a search subscription, just perform the connection and redirect back to the Search Dashboard.

**Comment by bluefuton** [comment]
Nice 👍 This would be much simpler.

**Comment by kangzj** [comment]
I'm trying to resolve this `p9dueE-55u#comment-7971`
