### ISSUE TITLE
Soundcloud shortcode embed doesn't accept  percent for dimensions

### ISSUE THREAD

**Issue by jeiseman** [Automattic/jetpack#2445]
When using the shortcode embed for Soundcloud the width and height parameters don't accept percentage values (even though the documentation indicates this is supported). The problem is in modules/shortcodes/soundcloud.php. Here is the fix that is required:

    diff soundcloud.php.org soundcloud.php
    101c101
    <       if (isset( $options['width'] ) && ! preg_match( '/^\d+$/', $options['width'] ) ) {
    ---
    >       if (isset( $options['width'] ) && ! preg_match( '/^(\d+)(%)?$/', $options['width'] ) ) {
    105c105
    <       if ( isset( $options['height'] ) && ! preg_match( '/^\d+$/', $options['height'] ) ) {
    ---
    >       if ( isset( $options['height'] ) && ! preg_match( '/^(\d+)(%)?$/', $options['height'] ) ) {

**Comment by jeiseman** [comment]
I created a patch request for this:
    https://github.com/jeiseman/jetpack/pull/1

Since this is the first time I've created a patch I wasn't sure if I need to merge this pull request into my own branch.
    jeiseman  wants to merge 1 commit into master from jeiseman-patch-1

**Comment by jeherve** [comment]
Could you try to submit a Pull Request against the original repository instead of your clone, here?
https://github.com/Automattic/jetpack/compare/

Thanks!

**Comment by jeiseman** [comment]
Okay, I have made the pull request against the original repository. Hope I did the pull request correctly this time.

Thanks!

**Comment by dereksmart** [comment]
merged in #2446
