### ISSUE TITLE
Jetpack code style: Analyze if we can remove unit test from eslintignore file for Jetpack plugin

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#24452]
File: projects/plugins/jetpack/.eslintignore has
````
# Temporary ignore until Jest is set up
/extensions/**/test/
````

We need to check if we can remove tests from the ignore file. We are going to need to check with the Jetpack crew.

**Comment by anomiex** [comment]
If you're willing to do the work of cleaning up whatever linting issues exist in those files and doing whatever configuration changes are necessary, go for it!

**Comment by Copons** [comment]
@anomiex Ha!
This was a draft item in our team's board that I didn't create but just converted to issue since it didn't contain any private info.
I think the author was @rcrdortiz, he might have more context on this. 😅

**Comment by rcrdortiz** [comment]
I'm happy with fixing the linting errors and configs.

**Comment by anomiex** [comment]
You took too long, I needed linting to help with some other refactoring so I did it. 😀
