### ISSUE TITLE
Instant Search: Selecting sort order "Sort by latest" in WooCommerce makes the Instant Search modal appear

### ISSUE THREAD

**Issue by stronenv** [Automattic/jetpack#24498]
### Impacted plugin

Jetpack, Search, None / Other

### Steps to Reproduce

1. Have Jetpack Instant Search active and WooCommerce with any product/category
2. Navigate to a WooCommerce category archive
3. Select sorting order "Sort by latest" (so `?orderby=date` gets applied to the URL)
4. Jetpack Instant Search modal appears without a search query

Alternatively, navigate to any page on a site with Jetpack Instant Search active and append `?orderby=date` to the URL, and the Jetpack Instant Search modal appears without a search query.

### A clear and concise description of what you expected to happen.

Not expecting the Instant Search modal to appear at all. 

### What actually happened

The Instant Search modal appears with an empty search query and the sorting set to "Newest".

### Other information

Jetpack version 10.9.1
Tested on WordPress.com blogs and self-hosted sites. 

**Jetpack Search Options:**
Default Sort: Relevance (recommended)
Overlay trigger: Open when results are available
Excluded Post types: Media
Additional settings:
Show sort selector: True
Enable infinite scroll: True
Show "Powered by Jetpack": True 

Please let me know if it can be helpful with any more information.

![Screen Capture on 2022-05-25 at 12-25-20](https://user-images.githubusercontent.com/70795294/170241530-c94b0dad-a60b-4c82-b498-cdf5d8ecf2fc.gif)

### Operating System

macOS, iOS

### OS Version

Monterey 12.3.1 (21E258), iOS 15.4.1 (19E258)

### Browser

Chrome/Chromium, Firefox, Safari

### Browser Version(s)

Chrome (101.0.4951.64), Firefox (100.0.2), Safari 15.4 (17613.1.17.1.13)

**Comment by stronenv** [comment]
Playing around with the different settings for the Jetpack Search Options, I noticed that if you select `Newest first` as the `Default sort`, it prevents the Search Modal from appearing when selecting `Sort by latest`.

Switching back to `Relevance (recommend)` the problem reappears.

<img width="291" alt="Screenshot 2022-05-25 at 12 38 22" src="https://user-images.githubusercontent.com/70795294/170244214-9fb0ad06-8099-42ca-94d3-e4b38c1d7dd8.png">

**Comment by bluefuton** [comment]
Thanks for alerting us to this @stronenv! It has been fixed in #24576, which will go out in our next release.

**Comment by stronenv** [comment]
Great! Thanks for the quick turnaround @bluefuton!
