### ISSUE TITLE
My Jetpack Connection Screen: Blurry WordPress.com logo on desktop and logo misalignment

### ISSUE THREAD

**Issue by atanas-dev** [Automattic/jetpack#24500]
### Impacted plugin

Jetpack, Jetpack Protect, and possibly all that use My Jetpack.

### Steps to Reproduce

1. Activate Jetpack.
2. Set up a site connection by bailing out of the connection flow after the first step (before confirming your account). Since Jetpack Protect only uses a site connection, this would be a more common occurrence there.
3. Go to My Jetpack.
4. Click on the "Connect your user account" link.
5. Take a look at the WordPress.com logo at the bottom.
6. The other logos are also top-aligned making the Apple one stick out of the bottom a noticeable amount.

### Other information

![blurry-wordpress-com-logo](https://user-images.githubusercontent.com/22746396/170263444-1d1d5a92-72a6-40a7-b923-e36e513727ba.png)

### Operating System

macOS

### OS Version

11.4

### Browser

Chrome/Chromium

### Browser Version(s)

101.0.4951.64

**Comment by samiff** [comment]
@renatoagds Is this something still on your radar? Saw it come up in Slack previously: p1652820545531009-slack-C02TQF5VAJD

Not related, but also saw a report about blurry Jetpack logo in the email reports: p1653570506592479-slack-CBG1CP4EN

**Comment by renatoagds** [comment]
@samiff yes! I'm currently working on it right now.
