### ISSUE TITLE
Jetpack Comments Missing Google Login

### ISSUE THREAD

**Issue by muffinpeace** [Automattic/jetpack#24522]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Install WordPress to the latest version 6.0
2. Install Jetpack to the latest version 10.9.1 
3. Connected Jetpack using a WordPress.com account
4. Go to Jetpack -> Settings -> Discussion
5. Tick the following box: `Let visitors use a WordPress.com, Twitter, Facebook, or Google account to comment`
6. Save settings and check the comment form on the front-end using incognito (to be logged off). 

### A clear and concise description of what you expected to happen.

Google Account connection option.

### What actually happened

Only Facebook, Twitter and WordPress.com is available.

### Other information

This came through a request in zen-5245691

### Browser

Firefox

**Comment by samiff** [comment]
Thanks for the report @muffinpeace , as mentioned in #24528 it seems like the Google sign-in option was removed recently. The UI will be updated in the next major Jetpack version to reflect that 👍
