### ISSUE TITLE
Enhancement: Slideshow block needs more design & look adjustments in block settings

### ISSUE THREAD

**Issue by w-sky** [Automattic/jetpack#24536]
### Impacted plugin

Jetpack

### What

A handful of more design options for buttons, positioning, colors, etc.

### How

Looking through previous requests here is that more options to control the buttons and how the captions are displayed are pretty common. Here is a list of some options that are missing in Slideshow block settings:
- Control if and when the pause/play button is visible
- Look, colors, opacity and sizes of the buttons
- Positioning of the buttons. E.g. show the pause/play button within the caption bar
- Show captions below pictures instead of overlapping the picture

**Comment by essleeung** [comment]
User shared similar feedback. They wanted to remove the navigation dots or the large pause button in the top right corner when on auto play or edit the prev/fwd buttons at the bottom. 
5435763-zd-woothemes

**Comment by jeherve** [comment]
Since this is tracked in other issues, I will close this one in favor of the issues that are already opened, such as #18324 and #27767.
