### ISSUE TITLE
The Protect IP whitelist should be synced to WordPress.com

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#2455]
Initially, we didn't bother syncing `jetpack_protect_whitelist' because it was a site_option, and we didn't have a mechanism in place for syncing site_options. Now that the option is a true Jetpack Option, we should sync it properly.

**Comment by roccotripaldi** [comment]
On single sites,  `jetpack_protect_whiteliste` is being synced via the heartbeat. On multisite, we'll need to sync `jetpack_protect_global_whitelist` via a mock option.

**Comment by enejb** [comment]
I think this issue is now solved. Since the option can be found on https://github.com/Automattic/jetpack/blob/master/sync/class.jetpack-sync-defaults.php#L372

Can you confirm that it works as expected?

**Comment by roccotripaldi** [comment]
It seems to be working well! Thanks @enejb
