### ISSUE TITLE
Likes: delete social_notifications_like option when module is inactive

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2456]
When the Likes module is activated, we set the `social_notifications_like` option to on.

However, when you deactivate the module later on, the option remains, thus creating issues in other places that may trigger a Like notification (see #7484-wpcom).

I think we should delete the option when the module gets deactivated, but I have no idea where to hook to make sure it's triggered at the right moment.

I wonder if we should create a new function, triggered on each module deactivation, allowing us to automatically delete options and transients that shouldn't persist.
We probably shouldn't delete options and transients set by site owners until the plugin is fully deactivated and deleted (on `uninstall.php`), but default options and transients are all fair game to delete, I think.

**Comment by dereksmart** [comment]
We have a module-specific hook that is run on deactivation: https://github.com/Automattic/jetpack/blob/master/class.jetpack.php#L2169

**Comment by jeherve** [comment]
I didn't know about that one, thank you! I just submitted #2458 to delete the option on deactivation.
