### ISSUE TITLE
Choose the letterboxing colour in Photon

### ISSUE THREAD

**Issue by jbeales** [Automattic/jetpack#2459]
In Photon it would be useful for me to letterbox images in white instead of black. It would be great if we could set a hex colour in the querystring.

**Comment by kraftbj** [comment]
We're dependent on the Photon service for this one (not strictly Jetpack). I'm going to close this request and defer to https://code.trac.wordpress.org/ticket/56 .

**Comment by jbeales** [comment]
Whoops! I screw up the two things with the same name once in a while ;) I've added myself as a CC on that one.

**Comment by kraftbj** [comment]
Noting for those finding this in the future that per https://code.trac.wordpress.org/ticket/56 , this has been launched and dev docs updated.
