### ISSUE TITLE
Related Posts Block Doesn't Work as Expected; Duplicates Related Posts

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#24619]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Install Twenty Twenty Two
2. Turn on Jetpack Blocks
3. Edit Single Post template and observe error that you can't add the Related Posts block
4. Enable Related Posts in Jetpack setting
5. Go back to Single Post template and add Related Posts block
6. View a blog post and you will see two instances of related posts

### A clear and concise description of what you expected to happen.

When using the Related Posts block that should take precedence over the other Related Posts implementation

### What actually happened

Related Posts block doesn't work unless Related Posts is enabled in settings. On that page, we include the text:

> Keep your visitors engaged with related content at the bottom of each post. These settings won’t apply to related posts added using the block editor.

This is confusing as Related Posts needs to be turned on to use the block. However, turning on the block results in duplicated "Related Posts".

### Other information

Trying to use only Related Posts block:

<img width="1900" alt="Screenshot on 2022-06-02 at 10-11-30" src="https://user-images.githubusercontent.com/45246438/171650257-9077a20e-954a-43ff-8f5c-c278039976d6.png">

Result when "Related Posts" is enabled in settings:

<img width="1461" alt="Screenshot on 2022-06-02 at 10-13-10" src="https://user-images.githubusercontent.com/45246438/171650408-5176fcf1-53b3-4657-a043-28a27fbb1c98.png">

### Operating System

macOS

### Browser

Firefox

**Comment by bobmatyas** [comment]
Reported on: https://wordpress.org/support/topic/related-posts-block-is-not-independent/?view=all

**Comment by jeherve** [comment]
Related: #24072, #11021
