### ISSUE TITLE
Share buddypress activities

### ISSUE THREAD

**Issue by ggsalas** [Automattic/jetpack#2461]
Hi
I would like to add an feature request
It would be great to use Jetpack publicize with buddypress activity updates. https://wordpress.org/support/topic/how-to-use-jetpack-publicize-with-buddypress-activity-updates?replies=2#post-7232956

Maybe this helps: https://wordpress.slack.com/archives/buddypress/p1438202709000735

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
