### ISSUE TITLE
Enhancement:control post to social media

### ISSUE THREAD

**Issue by c0derman** [Automattic/jetpack#24623]
### Impacted plugin

Jetpack

### What

control post to social media from jetpack setting

### How

control post to social media like facebook tw etc to post per hour and how many posts to share on soical media

**Comment by c0derman** [comment]
we got banned from facebook when try share cuz jetpack not limted share posts per time or day as facebook guidelines

"We limit how often you can post, comment or do other things in a given amount of time in order to help protect the community from spam. You can try again later. [Learn More](https://www.facebook.com/help/177066345680802)

If you think this doesn't go against our Community Standards [let us know]"

**Comment by jeherve** [comment]
If you'd like to be able to manually trigger Publicize, or schedule posts to be publicized at a specific time, this is something you can do after purchasing a Jetpack plan. You can read more about it here:
https://jetpack.com/support/publicize/#re-sharing-your-content

**Comment by c0derman** [comment]
yeah but i cannot chose if i share or not that not option in jetpack when connect with soical media

**Comment by jeherve** [comment]
When you first publish your post, you should be able to toggle the option if you do not wish to share your post right away. Give it a try!
