### ISSUE TITLE
Form block: required checkboxes do not work inside a checkbox group

### ISSUE THREAD

**Issue by Robertght** [Automattic/jetpack#24625]
### Quick summary

When using the Checkbox group block as required inside a form, the form will not submit.

### Steps to reproduce

1. Create a RSVP form inside a form.
2. Make sure you have a required checkbox group and that has a couple of checbox options
3. Publish the page
4. Try to submit the form with one of the required checkbox fields checkbox

### What you expected to happen

To submit the form successufully.
successfully

### What actually happened

It refreshed the page with an error that the fields need at least one option checked

### Context

#5263018-zen

### Simple, Atomic or both?

Simple

### Theme-specific issue?

No

### Browser, operating system and other notes

Chrome 101

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Use radio buttons instead if you have only two options to select from and it's more of a yes/no question.

---

cc @jeherve as I couldn't find another report for it

**Comment by ccwalburn** [comment]
Another report here:
34096497-hc
Follow up ticket: 5266225-zen

The workaround will not work for this user because they need to allow multiple selections.

I suggested that they turn off the required setting but include "(Required)" on the label that they type and maybe viewers will be more likely to complete the field even though it isn't enforced.

Please notify the user when it is fixed if we are able to do a batch notification.

**Comment by edequalsawesome** [comment]
Also reported in 5263532-zen, will suggest the customer use the Radio button for their forms.

**Comment by thesacredpath** [comment]
Another report here from a long-time user of 11 years. 5260358-zen

Will use the above workaround for now.

**Comment by nerdysandy** [comment]
Reported on #16618019-hc

Workaround: Add individual checkboxes to the form instead of Group checkbox and the value remains selected.

**Comment by cuemarie** [comment]
Reported here: 5267326-zd-woothemes

This user noted that with their form, when the Checkbox group is **not required**, the form can submit, but the answers in the checkbox group are not saved.  When the checkbox group is **required**, they run into the same issue as described above, the form cannot be submitted.

- I was able to replicate both issues on a simple test site - with the checkbox group **not required**, this is the feedback saved (I selected several answers there): 
<img width="678" alt="Markup 2022-06-03 at 17 35 50" src="https://user-images.githubusercontent.com/27249804/171969580-31087f98-d788-43f5-92d1-8b63ea6dbb6d.png">

I'm recommending some workarounds, but they are not as well suited to their goal as the checkbox groups would be, so this is somewhat of a blocker.

**Comment by filipanoscampos** [comment]
- [ ] Reported here: 5265220-zd-woothemes

**Comment by Gustavo-Hilario** [comment]
Another report here: 5262888-zen

**Comment by jeherve** [comment]
Also in https://github.com/Automattic/wp-calypso/issues/64294

**Comment by jeherve** [comment]
I'm thinking this may be caused by #24450, and we would need to fix this before tomorrow's release.

**Comment by formosattic** [comment]
+1 5266622-zd-woothemes
As alternative, suggested using a Google Forms embed, https://wordpress.com/support/google-docs/#forms

**Comment by jeherve** [comment]
The problem should now be fixed on WordPress.com, as of r246875-wpcom.
