### ISSUE TITLE
Tiled Gallery Block loads in hi-res thumbnail images (without native lazy loading support)

### ISSUE THREAD

**Issue by ChrisBegley** [Automattic/jetpack#24636]
### Impacted plugin

Jetpack

### Steps to Reproduce

Create a gallery using the Tiled Gallery Block

### A clear and concise description of what you expected to happen.

The Tiled Gallery Block behaves differently than the Tiled Gallery using the Classic editor. 

The Tiled Gallery Block doesn't load an optimized thumbnail image. For my gallery with hi-res images, each thumbnail is loading in as a 1800px or 2000px image on my laptop and 4K iMac. There isn't 'loading=lazy' support for each thumbnail image either, so this is a pretty big performance issue when it comes to large galleries (or even small galleries with hi-res photos).

A live example is available here, using the default "Tiled Mosaic" style: https://katharinemcphee.net/performs-national-anthem-at-147th-preakness-stakes/

For a Tiled Gallery using the Classic Editor, the thumbnail images are optimized: https://katharinemcphee.net/pictures-katharine-mcphee-performs-at-ggpaa-in-canada-to-honor-david-foster/ (still no native lazy loading support though)

### Other information

Jetpack 10.9.1
WordPress 6.0

**Comment by ChrisBegley** [comment]
Hi @jeherve, Jetpack 12.6 added srcset to the Tiled Gallery today. It is still missing native lazy loading support though. I created an enhancement request: https://github.com/Automattic/jetpack/issues/33247

**Comment by jeherve** [comment]
> Jetpack 12.6 added srcset to the Tiled Gallery today.

Indeed. It was added in #32598. 

> It is still missing native lazy loading support though. I created an enhancement request: https://github.com/Automattic/jetpack/issues/33247

Thanks for creating the issue! I'll close this one and we can track the lack of native lazy loading in that issue you created!
