### ISSUE TITLE
Search: Disabling instant search results in search widget not showing results with Classic themes

### ISSUE THREAD

**Issue by coder-karen** [Automattic/jetpack#24650]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Activate a classic (non-FSE) theme, such as Twenty Fifteen.
2. Make sure there is a search widget on a site, and add a Search plan (if self hosted Jetpack site).
3. Disable instant search:
<img width="980" alt="Screenshot 2022-06-06 at 16 20 10" src="https://user-images.githubusercontent.com/16754605/172192482-e085d6af-713e-421b-8bbc-2bc1a07d1499.png">

4. Try searching for something that should provide results, and nothing will display.

Reported internally: p1654516131426219-slack-C03TY6J1A

### A clear and concise description of what you expected to happen.

Search results should display.

### Other information

D81815-code appears to be the culprit, reported here: p1654528995619999/1654519933.955709-slack-C02FMH4G8

cc. @robfelty 

This is also affecting WoA sites.

### Operating System

macOS

### Browser

Chrome/Chromium

**Comment by tellisbethel** [comment]
- [ ] Encountered user with this here: 5274917-zd-woothemes

Applied workaround. 
Let user know we'd notify them once resolved.

**Comment by marianearchimbaud** [comment]
Same issue here: 35726306-hc
I disabled the Search modules and searches stared working

**Comment by JoshuaGoode** [comment]
This should now be resolved. 

Re: p1654519933955709-slack-C02FMH4G8

**Comment by coder-karen** [comment]
This is fixed for now - D81815-code was reverted: p1654532795289519/1654519933.955709-slack-C02FMH4G8

I'll mark this as closed.

**Comment by JoshuaGoode** [comment]
I've updated the users on the tickets reported.

**Comment by ariel-maidana** [comment]
Reactivated the Jetpack search module and informed these users:
5274487-zd-woothemes
5274482-zd-woothemes
5274388-zd-woothemes
