### ISSUE TITLE
Connection: avoid using deprecated methods

### ISSUE THREAD

**Issue by sergeymitr** [Automattic/jetpack#24654]
### Impacted plugin

- Jetpack
- Backup
- Boost
- WCPay
- Connection Package

### What

Remove/replace using of deprecated methods where possible

### How

- [ ] `Manager::is_active()`: [usage 1](https://github.com/Automattic/jetpack/blob/469703d9770cb30313a5f41c34ea85fa1066f1fa/projects/packages/connection/src/class-manager.php#L1849), [usage 2](https://github.com/Automattic/jetpack/blob/ab8dfcc072195baf918520952e4867e7275241e0/projects/packages/connection/src/class-rest-connector.php#L305), [usage 3](https://github.com/Automattic/jetpack/blob/bb119864a1f32c61091e13712d7e1e596da36ccf/projects/plugins/jetpack/class.jetpack.php#L1567), [test 1](https://github.com/Automattic/jetpack/blob/7ea6b1256a2d3f3522887c19d9629b55493bf4fa/projects/packages/connection/tests/php/test_Manager_unit.php#L91), [test 2](https://github.com/Automattic/jetpack/blob/7ea6b1256a2d3f3522887c19d9629b55493bf4fa/projects/packages/connection/tests/php/test_Manager_unit.php#L104)
- [ ] `Manager::is_registered()`: [Boost](https://github.com/Automattic/jetpack/blob/b647ae72c67d3562acf368282035834a3eb35d08/projects/plugins/boost/app/lib/class-connection.php#L126), [Jetpack](https://github.com/Automattic/jetpack/blob/bb119864a1f32c61091e13712d7e1e596da36ccf/projects/plugins/jetpack/class.jetpack.php#L1588)
- [x] `Manager::get_access_token()`: [test 2](https://github.com/Automattic/jetpack/blob/7ea6b1256a2d3f3522887c19d9629b55493bf4fa/projects/packages/connection/tests/php/test_Manager_unit.php#L88), [test 3](https://github.com/Automattic/jetpack/blob/7ea6b1256a2d3f3522887c19d9629b55493bf4fa/projects/packages/connection/tests/php/test_Manager_unit.php#L101), [test 4](https://github.com/Automattic/jetpack/blob/7ea6b1256a2d3f3522887c19d9629b55493bf4fa/projects/packages/connection/tests/php/test_Manager_unit.php#L199), [test 5](https://github.com/Automattic/jetpack/blob/7ea6b1256a2d3f3522887c19d9629b55493bf4fa/projects/packages/connection/tests/php/test_Manager_unit.php#L218), [test 6](https://github.com/Automattic/jetpack/blob/7ea6b1256a2d3f3522887c19d9629b55493bf4fa/projects/packages/connection/tests/php/test_Manager_unit.php#L235), [test 7](https://github.com/Automattic/jetpack/blob/7ea6b1256a2d3f3522887c19d9629b55493bf4fa/projects/packages/connection/tests/php/test_Manager_unit.php#L510), [test 8](https://github.com/Automattic/jetpack/blob/7ea6b1256a2d3f3522887c19d9629b55493bf4fa/projects/packages/connection/tests/php/test_Manager_unit.php#L546)
- [ ] `Manager::enable_plugin()`: [Backup](https://github.com/Automattic/jetpack/blob/72d7c3b67e282b5b5485a0c1b2b70f28ab362807/projects/packages/backup/src/class-jetpack-backup-upgrades.php#L43), [WCPay](https://github.com/Automattic/woocommerce-payments/blob/95c6c95f73bd68a0bece0baa14c2a81549856496/includes/wc-payment-api/class-wc-payments-http.php#L181)
- [ ] `Manager::is_plugin_enabled()` needs to be deprecated ([link](https://github.com/Automattic/jetpack/blob/469703d9770cb30313a5f41c34ea85fa1066f1fa/projects/packages/connection/src/class-manager.php#L2356))
- [ ] `Plugin_Storage::get_all()`: remove deprecated parameter [1](https://github.com/Automattic/jetpack/blob/469703d9770cb30313a5f41c34ea85fa1066f1fa/projects/packages/connection/src/class-plugin.php#L86), [2](https://github.com/Automattic/jetpack/blob/469703d9770cb30313a5f41c34ea85fa1066f1fa/projects/packages/connection/src/class-manager.php#L2318)

**Comment by chrisbliss18** [comment]
Closing this issue as the bulk of the work has been taken care of in PRs #25300 and #25315. These PRs take care of all the changes need in all Jetpack monorepo code.

There is one lingering call in the WCPay project. I've contacted their team about removing this last remaining call. This can be tracked in [this issue](https://github.com/Automattic/woocommerce-payments/issues/4256).
