### ISSUE TITLE
Twitter Threads: Add an option to include image captions

### ISSUE THREAD

**Issue by coder-karen** [Automattic/jetpack#24687]
### What is the issue

It would be nice to have the option to include image captions in Twitter threads.

### More information

Ideally it could be shown directly below the image in the thread as well.

This was raised in internal testing: p8oabR-Sc-p2#comment-6390

**Comment by jeherve** [comment]
Related: https://github.com/Automattic/jetpack/issues/17149#issuecomment-1084058806

**Comment by jeherve** [comment]
Closing since the feature is no longer available.
