### ISSUE TITLE
Sharing buttons: Reddit official button not working

### ISSUE THREAD

**Issue by KokkieH** [Automattic/jetpack#24733]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Go to Settings ->Sharing (WP-Admin) or Tools ->Marketing ->Sharing buttons (Calypso)
2. Enable the Reddit sharing button
3. Set button style to Official button
4. View a post displaying sharing buttons.

### A clear and concise description of what you expected to happen.

To see the Reddit sharing button displayed along other enabled buttons

### What actually happened

The Reddit button displays as a black box/broken image depending on browser, and it's not clickable

### Other information

**Firefox**
![Cursor_and_Ancient_technology_–_if_all_else_fails…use_a_hammer](https://user-images.githubusercontent.com/11873759/173497193-410d85a3-dedd-4e85-b188-17a727a9878d.png)

**Chrome**
![Cursor_and_Ancient_technology_–_if_all_else_fails…use_a_hammer](https://user-images.githubusercontent.com/11873759/173497627-3093d2ba-8dc4-4f15-a489-5f4cfd9dc1c2.png)

In Chrome the browser console displays the following:

`Refused to display ‘https://www.reddit.com/’ in a frame because it set ‘X-Frame-Options’ to ‘sameorigin’`

Reported via the [WordPress.com forums](https://wordpress.com/forums/topic/reddit-sharing-button-not-displaying-correctly/), but I can replicate on both WordPress.com Simple and a Jetpack-connected Pressable site.

### Browser

Chrome/Chromium, Firefox

**Comment by davipontesblog** [comment]
Another user report in 36106585-hc

**Comment by jeherve** [comment]
The Reddit team acknowledged the issue, and added that bug to their bug tracker. I'll post again here once they reply.

**Comment by csonnek** [comment]
Another report in the forums: https://wordpress.com/forums/topic/unable-to-view-social-media-icons-on-my-blogs/?view=all

**Comment by jp-imagines** [comment]
Another report in 40958879-hc.

**Comment by samiff** [comment]
This was noted in testing JP 11.9-beta internally: p8oabR-16e-p2#comment-7107

**Comment by ghost** [comment]
Another report in 6225267-zd - provided workaround to use Icons Only.
