### ISSUE TITLE
[Boost] Clean up eslint tags

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#24735]
There are a lot of eslint exceptions throughout the Boost JS codebase. There really shouldn't be this many.

e.g.: a lot of [eslint markers to turn off camelcase complaints when accessing the `Jetpack_Boost` global const](https://github.com/Automattic/jetpack/blob/master/projects/plugins/boost/app/assets/src/js/pages/settings/sections/Score.svelte#L117).

We should clean these out - rename variables / clean up code to minimize the number of eslint things we have to turn off.

**Comment by haqadn** [comment]
Since this issue was created, we rewrote the plugin from Svelte to React. Though we still have es-lint ignores, we have fewer, and I think they are essential.
