### ISSUE TITLE
New VideoPress Permalink Feature: Some Reactions & Ideas

### ISSUE THREAD

**Issue by EnigmaSolved** [Automattic/jetpack#2475]
Greetings!

First off, the [new VideoPress](https://en.blog.wordpress.com/2015/07/01/videopress-next/) is [beautiful](http://videopress.com/)!  :)  It's great to see WordPress giving some much-needed attention to this service, and I'm looking forward to the upgrade making it's way into Jetpack.

The main thing I'm having mixed feelings about, however, is the [Permalink to the video](https://videopress.com/v/iQnkO4EL) feature. While on the one hand this feature is nifty and convenient, it nonetheless goes against one of the original selling points of VideoPress (and part of why I chose VideoPress originally)--that being encouraging/facilitating the user remaining on my site. By making the video Permalink so prominent, users are in some ways encouraged to engage with the video via the VideoPress site, and without ever coming to my website (eg, the user would naturally just share the VideoPress Permalink, which then totally cuts out other viewers from having any engagement with my site). This is rather problematic for me because the way I am usually presenting videos I normally provide quite a bit of written text regarding the video (not a transcript mind you, but written companion content meant to be read with, and in many cases prior to, viewing the video). The prominent display of the VideoPress Permalink potentially undermines/interferes with the flow of what I'm trying to achieve.

I realize that customization of the new player is coming (which I'm **really** looking forward to!), and so I could potentially just hide the Permalink in the future (though it would still be visible in the Share menu). But I'd like to propose another solution which I think could be very useful and powerful (and probably would further distinguish VideoPress from other services). I propose adding the ability to define a single blog post or page (basically _any_ url I choose) which the VideoPress Permalink for a specific video will do a `301` redirect to. If I don't define a custom url for a given video, then the VideoPress Permalink simply goes where it normally would go--to the video on VideoPress.com. But if I _do_ define a custom url, then the any attempts to view the video solely on VideoPress.com (via it's Permalink) will automatically redirect to the url I have defined.

I believe there are plans to add oEmbed support to VideoPress links (presumably these same Permalinks I've been talking about), so my hope is that the above proposal would still allow for that somehow (as opposed to if we added the ability to change the Permalink itself to something else, in which case it seems that would very likely cause problems with oEmbed functionality).

Another idea, which could be in addition to the above or possibly an alternative to the above (I'd prefer it as an addition though), would be adding the ability to define a url that would be displayed after a video has been played on any page other than that defined url. So for example, say I define a "Post Play URL" (just trying out terms here) of `www.example.com/my-blog-post-where-I-posted-my-video`. If a visitor views my video on VideoPress.com or in an embed format on some other site (eg, Twitter, Facebook, some other website), then at the end of the video a message (with a clickable link) displays something along the lines of: "View this video in it's original context: `www.example.com/my-blog-post-where-I-posted-my-video`." Perhaps it might be nice to define what text is displayed before (and after) the link, at least on a per-account basis (though inevitably some folks, perhaps even myself, will want to be able to customize that on a per-video basis). This "Post Play URL" idea is a nice companion to my other idea (as well as a good stand-alone feature) in that it encourages the viewer to interact with the original site, even if they are viewing the video embedded in/on another site. I don't think I am alone in presenting videos _and_ text as companion content to each other (ie, meant to be viewed **together**), and so any ways that we can be encouraging/facilitating viewers engaging with the video and text content on the original site would be super-useful (in my opinion).

Thanks in advance for considering my ideas! :) I'm very interested in other's thoughts, reactions, ideas, etc.

Sean

**Comment by kraftbj** [comment]
This is beyond the scope of Jetpack, per se. Leaving it open since there isn't a public bug report platform for the VideoPress platform currently.

cc: @nickmomrik , @rauchg

**Comment by nickmomrik** [comment]
Couple quick things...

Though the new player isn't being used in Jetpack yet, on WordPress.com you can hide the permalink by adding `permalink=0` to a shortcode or as a query parameter to a permalink (if pasting the URL in a post).

Examples:
`[wpvideo kUJmAcSf permalink=0]`
http://videopress.com/v/kUJmAcSf?permalink=0

If you are using the new embed code for a video on a .org site you can also add the `permalink` query param to the src URL in there.

`<iframe width="560" height="315" src="https://videopress.com/embed/kUJmAcSf?permalink=0" frameborder="0" allowfullscreen></iframe>
<script src="https://videopress.com/videopress-iframe.js"></script>`

oEmbed support is already live as well.

**Comment by EnigmaSolved** [comment]
@kraftbj, I agree, and thanks for leaving it open! I'm cool with it being moved, or my re-posting it, if at some point there is a more appropriate context for it.

@nickmomrik, Cool! Good to know! :)

**Comment by dbtlr** [comment]
Hey @EnigmaSolved, I'm not against the idea of providing a way to show a different permalink on a per video basis that points to your own page, however, a redirect would definitely not work, as that permalink is the video page that displays inside the iframe. Recursive loop is recursive type thing. :)

While I am going to close this issue, since it isn't really a Jetpack issue, I am going to take your notes and add them into our internal P2 for VideoPress and look into the viability of adding some more controls to the permalink process in the future.

My immediate thoughts would be to add the following:

1) Jetpack filter that allows permanent permalink=0 on all videopress shortcodes by default.
2) A permalink override field inside the VideoPress metadata, that is user definable to point to whatever url you like.

The first may show up in our next release, but the 2nd may not be for a little while.

Thanks for all your efforts to make VideoPress better. :)
