### ISSUE TITLE
Sharing buttons: Email button cause indexation of status 500 URLs

### ISSUE THREAD

**Issue by RavanH** [Automattic/jetpack#24764]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Configure sharing buttons on a live site and add the Email button.
2. Add the site to Google Search Console.
3. Wait for Google to start indexing page/post URLs with /?share=email appended
4. Check the “Server error (5xx)” errors flooding the Coverage section in Google Search Console.

### A clear and concise description of what you expected to happen.

No errors in Google Search Console and preferably no indexation of URLs with `?share=email` appended.

### What actually happened

It turns out that Google will start indexing post URLs with ?share=email appended, and these URLs indeed return a status code 500 response.

### Other information

Nothing to be found in the logs, not even with WP_DEBUG turned on. The source code of the rendered page, I see an empty wp_die message:

```
<body id="error-page">
	<div class="wp-die-message"></div></body>
```

This seems to be occurring on different servers and different PHP versions. I tested on an Apache and on Nginx, on PHP 8.0 and 7.4…

### Operating System

Linux

### Browser

Chrome/Chromium

**Comment by RavanH** [comment]
Related support topic https://wordpress.org/support/topic/email-share-button-causes-coverage-errors-in-google-search-console/

**Comment by bindlegirl** [comment]
@RavanH Can you please provide some more information about this? In particular, which version of Jetpack are you using, and if pages that report errors were indexed by Google before updating to Jetpack 11.0?

There was a change made to the email sharing button in Jetpack 11.0 where email sharing was changed to use mailto links (see #24040)

**Comment by RavanH** [comment]
Hi @bindlegirl this is Jetpack 11.0 and to my knowledge, posts where not indexed with `?share=email` before. I assume Google extracts these URLs from the email share button/link attributes, either from `data-email-share-track-url="https://xxxx.xx/xxxx/?share=email"` or from the href, which looks like `href="mailto:?subject=%5BPost%20Title&body=https%3A%2F%2Fxxxx.xx%2Fxxxx%2F&share=email"`.

When visiting such a URL with a `share=email` query string in my browser, I get a 500 status response. But with any other `share=xxxx` query value, or when the Email share button is removed from the Sharing Services, there is no 500 error response.

**Comment by jeherve** [comment]
Thanks for the extra details!

This was introduced in #24040. I'll come up with a fix.

Beyond the fatal problem, it's interesting that Google ignores the `nofollow` rel on those links, and follow them anyway.

**Comment by RavanH** [comment]
Hi Jeremy, thanks for picking this up :)

> it's interesting that Google ignores the nofollow rel on those links, and follow them anyway.

I'm not an SEO expert but I don't think nofollow necessarily means the link will not be followed, rather that the origin should not be held accountable for the target in terms of content or reliability?

Anyway, like I said earlier, it might also be harvesting the url from the data-email-share-track-url attribute. It does not start indexing the post pages with a `subject=Post%20Title` argument for example. Or at least: not that I'm aware of.
