### ISSUE TITLE
Why infinite-scroll module require `wp-mediaelements` files?

### ISSUE THREAD

**Issue by sniperwolf** [Automattic/jetpack#2483]
Hi guys,

thank you for this amazing plugin. I was wondering for a simple solution to active on custom theme an Infinite Scroll functionality and I find this much more complete plugin.

The thing that I don't understand is why the **'infinite-scroll'** module require `wp-mediaelements` JS and CSS. I think that this is useful only when you activate the **'Shortcodes'** modules.

The enqueue part is in [this](https://github.com/automattic/jetpack/blob/master/modules/infinite-scroll.php#L214-L223) file.

**Comment by kraftbj** [comment]
My understanding is WordPress Core will enqueue that JS when the native audio/video shortcodes are being used—not Jetpack's, but Core's. In our case, if the initial set of posts loaded on the page did not include an audio/video shortcode, but then a set of posts loaded via IS included them, the required JS would not have been enqueued and we'd have broken posts.

For IS, we always enqueue `wp-mediaelements` to ensure we're not breaking core shortcodes.
