### ISSUE TITLE
Fatal error `Class ...Waf\WP_Error not found` on `wp-json/jetpack/v4/waf`

### ISSUE THREAD

**Issue by iandunn** [Automattic/jetpack#24834]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. `curl -i https://vadodara.wordcamp.org/2019/wp-json/jetpack/v4/waf/`

You'll see error handler is triggered.

### A clear and concise description of what you expected to happen.

A JSON-encoded error message b/c it was called w/out auth.

### What actually happened

`E_ERROR Uncaught Error: Class 'Automattic\Jetpack\Waf\WP_Error' not found in wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-waf/src/class-waf-endpoints.php:74`

Looks like maybe a namespace issue. Might be because it's [not connected to Jetpack](https://jptools.wordpress.com/debug/?url=https://vadodara.wordcamp.org/2019/) ? Or the execution path is different because it was called directly?

The impact here is just that it clutters log files w/ false-positives when bots scan the API.

### Browser

Other / Not applicable

**Comment by jeherve** [comment]
@miguelxpn Do you think you could take a look? 

Thanks!

**Comment by anomiex** [comment]
> Looks like maybe a namespace issue.

Yes. Someone forgot a `use WP_Error;` at the top of the file (or forgot to referring to the class as the fully-qualified `\WP_Error`).
