### ISSUE TITLE
Search: letter spacing inherited from theme causes odd rendering of headers

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#24852]
### Impacted plugin

Jetpack, Search

### Steps to Reproduce

1. Go to https://johnmenadue.com/?s=hi
2. Take a look at the headers for "Showing x results" and "Filter options"

<img width="1367" alt="Screen Shot 2022-06-28 at 11 33 19" src="https://user-images.githubusercontent.com/17325/176058899-f73f21c1-3340-4eb1-aa63-2c78c2a8cf02.png">

### A clear and concise description of what you expected to happen.

Letter spacing should be standard and not inherited from the theme.

### What actually happened

Letter spacing of -2px inherited from the theme and causes odd rendering.

### Other information

I believe we have a Sass mixin to reset default styles, but I'm not sure if it's applied to these headers. I think a `letter-spacing: inherit` would do the trick.

### Browser

Chrome/Chromium, Firefox

**Comment by bluefuton** [comment]
@dognose24 this could be a good first issue!

**Comment by kangzj** [comment]
Me and @dognose24 will work together to fix this in our 1:1 session on Monday next week 🥳

cc @bluefuton

**Comment by bluefuton** [comment]
Sounds like a plan :)
