### ISSUE TITLE
Search: Purchase on Atomic site with standalone doesn't work.

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#24895]
### Impacted plugin

Search

### Steps to Reproduce

1. Create an Atomic site on WP.com by purchasing a Pro plan.
2. Install the standalone Jetpack Search plugin.
3. Purchase a Jetpack Search plan.

### A clear and concise description of what you expected to happen.

I should be able to configure search after the purchase.

### What actually happened

Instead, I am still seeing the upgrade nudge.

<img width="1219" alt="Screen Shot 2022-06-29 at 10 59 27" src="https://user-images.githubusercontent.com/820871/176493949-c47f2b5c-82c9-4a3c-b5bb-e45681139232.png">

### Other information

I bought Pro yearly and Jetpack Search yearly. Note that on wp.com Jetpack Search has a different product slug, so I wonder if we just aren't paying attention to all the product slugs.

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Browser

Chrome/Chromium

**Comment by kangzj** [comment]
This is fixed by `D84757-code`
