### ISSUE TITLE
Contact Form: explicit consent field value not sent in email

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#24898]
When using a Jetpack Contact Form, you can add a `Consent` block to the form, which has the option to ask for explicit permission to email visitors for example:

```html
<!-- wp:jetpack/field-consent {"consentType":"explicit"} /-->
```

This explicit permission acts as a checkbox. When the form is submitted however, this value is not included in the email sent out to the form recipients (it is recorded in the post/feedback data though).

That strikes me as a bit confusing because users may only access the emailed responses rather than digging into the Feedback section, and if I were to add my own custom checkbox field, then that value _would_ be sent off in the email.

Reported via p8oabR-T0-p2#comment-6420

**Comment by coder-karen** [comment]
I believe this was resolved here: https://github.com/Automattic/jetpack/pull/26878
