### ISSUE TITLE
Jetpack WAF detected as threat

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#24903]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Install Jetpack plugin
2. Enable Firewall on the Security tab
3. Run a scan from Jetpack Cloud

![image](https://user-images.githubusercontent.com/1425433/176558831-9571a464-4dcc-4187-8393-52d1ebfc116b.png)

### A clear and concise description of what you expected to happen.

Jetpack WAF shouldn't be detected as threat

### What actually happened

![image](https://user-images.githubusercontent.com/1425433/176559016-e4b6935c-b34b-46ec-8ab8-0d9b0ef61f7f.png)

### Reproducibility

Consistent

### Severity

All

### Browser

Other / Not applicable

**Comment by jeherve** [comment]
@Automattic/yamato-scan Do you think you could take a look? 

Thanks!

**Comment by fioa8c** [comment]
Since this is a Hardening rule (low risk, almost informative), I'm adding our filepath to the safeFiles.

**Comment by kangzj** [comment]
The issue has been fixed by `3210-gh-Automattic/jetpack-backup`.
