### ISSUE TITLE
Jetpack Search: Admin Menu overlaps 'Customize Search Appearance' page

### ISSUE THREAD

**Issue by jordesign** [Automattic/jetpack#24905]
### Quick summary

When viewing the 'Customize Search Results' option for Jetpack Search (/wp-admin/admin.php?page=jetpack-search-configure) the content of the page itself appears overlapped by the WP Admin menu.

This occurs only on WordPress.com sites- it appears to behave normally on self-hosted sites.

<img width="1698" alt="Screen Shot 2022-06-30 at 11 55 08 am" src="https://user-images.githubusercontent.com/1842363/176579685-7a0fd340-1f66-4f18-b544-05541e7ef366.png">

### Steps to reproduce

1. Add Jetpack Search to a WordPress.com site
2. Go to the page for editing the appearance of Search Results - [siteurl]//wp-admin/admin.php?page=jetpack-search-configure

### What you expected to happen

To be able to view the content normally - without issue.

### What actually happened

The WP Admin menu on the left overlapped the content so not all of it was accessible.

### Context

Team Testing of Jetpack Search Record Meter

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by bluefuton** [comment]
Just noting that we auto-collapsed the sidebar until recently: https://github.com/Automattic/jetpack/pull/24399

Reverting that PR is an option.

**Comment by aisajib** [comment]
📌 SCRUBBING

- Tested on AT ✅ 
- Tested on Self-hosted ✅ 
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
It seems to be a consistent issue as I was able to replicate this on an atomic site: 

<img width="1300" alt="Screen Shot 2022-07-10 at 10 39 35 PM" src="https://user-images.githubusercontent.com/2541844/178153745-86c2c859-3967-47ee-b302-00337636de18.png">

Also, for funsies, I tested this on a self-hosted site with Jetpack Search added, and it doesn't seem to be an issue there: 

<img width="1374" alt="Screen Shot 2022-07-10 at 10 41 16 PM" src="https://user-images.githubusercontent.com/2541844/178153815-c51f80a2-a227-4a63-9115-7c290dced258.png">


📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by bluefuton** [comment]
I've just created https://github.com/Automattic/jetpack/pull/25060 which brings back the auto-collapsing sidebar on desktop viewports. This should solve the issue.
