### ISSUE TITLE
Jetpack: Downtime Monitoring Notification Settings Redirect to JP Cloud

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#24937]
### Impacted plugin

Jetpack

### Steps to Reproduce

When a site uses the JP cloud instead of Calypso, the Downtime Monitoring Notifications Settings link is redirecting to JP cloud instead of Calypso.

1. Go to [site url]/wp-admin/admin.php?page=jetpack#/security. Make sure Downtime Monitoring is turned on and that the site in question is using JP Cloud instead of Calypso.
2. Click **Configure your notification settings**.

When I turned off JP cloud briefly, the redirect worked as expected.

### A clear and concise description of what you expected to happen.

It should go here: https://wordpress.com/settings/security/[site url]

### What actually happened

https://cloud.jetpack.com/settings/[site url]

### Reproducibility

Consistent

### Browser

Firefox

**Comment by sdixon194** [comment]
Dug into this a bit, but don't fully grok how cloud vs calypso is supposed to be used, but that link the downtime monitoring seems to be calling the `calypso-settings-security` slug to build the link, which in turn should be using `wordpress.com` as a base. Not sure where it's grabbing the cloud link from yet.

**Comment by jeherve** [comment]
@Automattic/jetpack-genesis What's your take on this? Should we have a Monitor section in Jetpack Cloud, or should we always link to Calypso for Monitor settings?

**Comment by pehaa** [comment]
I tested and noticed that on a website with no backup plan the link from WP Admin > JP > Settings > Security, the Downtime monitoring > Configure your notification settings sends me to https://wordpress.com/settings/security/{site}

Once a backup plan is active - the link redirects to https://cloud.jetpack.com/settings/{site} which does not offer Downtime monitoring settings.

**Comment by vitozev** [comment]
@jeherve, ideally, I think we should have monitor settings implemented in the Jetpack Cloud (similarly to the other settings we have added). But as a short-term fix, we can redirect to WordPress.com.

I'm curious what "When a site uses the JP cloud instead of Calypso" means and how Cloud can be turned off?

**Comment by jeherve** [comment]
> 'm curious what "When a site uses the JP cloud instead of Calypso" means and how Cloud can be turned off?

You can check the `has_access_to_jetpack_cloud` method in fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Swrgcnpx%2Qerqverpgf%2S0%2Qybnq.cuc%3Se%3Q3974s315%231534-og to find out more. 

Typically WoA sites for example would not use the JP cloud.
