### ISSUE TITLE
'Hello Dolly' plugin breaks the Jetpack Search wp-admin page layout

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#24940]
### Impacted plugin

Jetpack, Search

### Steps to Reproduce

1. Create a test site and install the Jetpack Search plugin.
2. Activate the "Hello Dolly" plugin.
3. Visit the Jetpack Search dashboard.

### A clear and concise description of what you expected to happen.

Hello Dolly plugin should not affect Jetpack Search.

### What actually happened

![screen-shot-2022-06-22-at-12 06 39](https://user-images.githubusercontent.com/17325/177076460-0b578419-b5c9-4827-b307-3ab34975a7bd.png)

### Reproducibility

Consistent

### Browser

Firefox

**Comment by bindlegirl** [comment]
Boost plugin has the same problem.
