### ISSUE TITLE
Hookify notices prompting connect

### ISSUE THREAD

**Issue by blobaugh** [Automattic/jetpack#250]
Right now notices live in a big blob at https://github.com/Automattic/jetpack/blob/master/class.jetpack.php#L2880

A bunch of conditionals are run through to decide what to show and it is getting confusing on the flow. Adding a hook to the notice area would be helpful here, as would pulling display code out of the logic code and putting it into the views folder.

**Comment by dereksmart** [comment]
This will be worked on along with the upcoming changes for 4.0
