### ISSUE TITLE
Tiled Gallery block: The Editor has encountered an unexpected error in Bigger Galleries

### ISSUE THREAD

**Issue by carladoria** [Automattic/jetpack#25017]
### Steps to reproduce the behavior

1. Add a Tiled Gallery Block 
2. Add a big number of images, at least 50* images
3. Click the block's pencil icon in the floating toolbar to modify the images 
3. Modify one of the images by selecting a different image from the media library

You will see 

The Editor has encountered an unexpected error /Attempt Recovery Copy Post Text, Copy Error 
<img width="1792" alt="Screen Shot 2021-02-21 at 15 08 15" src="https://user-images.githubusercontent.com/23703267/108635708-2c59ee00-7457-11eb-9d72-dedac7598e51.png">

* I haven't been able to pinpoint the exact number where it breaks. For the customer in 3758951-zen , their gallery has 48 images and it already breaks when trying to modify it. In my test site, I had to add 52 images, so I guess it also depends on the images sizes. 

#### What I expected to happen

To be able to modify one of the images

#### What actually happened

The editor breaks 

#### Current Workaround

Create a separate Tiled Gallery block.

**Comment by louinel** [comment]
Another case here: 5346943-zd-woothemes

**Comment by rw-ye** [comment]
Another report: 5662408-zd-woothemes

**Comment by Robertght** [comment]
Another case in 5720322-zen

**Comment by TimBroddin** [comment]
Closing this as it's stale
