### ISSUE TITLE
Uninstall: update the list of options and transients we delete when the plugin is deleted

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2502]
We've added a few new options to the plugin since `uninstall.php` was created:
https://github.com/Automattic/jetpack/blob/master/uninstall.php

It'd be nice to update that file to include the new options and transients we've added since then.

**Comment by dereksmart** [comment]
We need to be careful which options we delete on uninstall, since we sometimes suggest a uninstalling as a way to debug.

**Comment by lukecav** [comment]
So could these specific Jetpack options be the focus to be removed on uninstall from the options db table?

_transient_timeout_jetpack_https_test
_transient_jetpack_https_test
jetpack_file_data
jetpack_available_modules
jetpack_log

**Comment by jeherve** [comment]
I think we should be able to remove those 5 options, yes.

**Comment by lukecav** [comment]
Something along this lines to remove orphaned data stored in options.

https://plugins.svn.wordpress.org/options-optimizer/tags/1.0/options-optimizer.php

**Comment by jeherve** [comment]
This was fixed in #7834
