### ISSUE TITLE
Form block: cannot remove added string on a date block

### ISSUE THREAD

**Issue by Robertght** [Automattic/jetpack#25026]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/start/ (create a new site - it can be a free plan one) and do not launch the site yet.
2. Create a new Contact page.
3. Add a date block to the form block and check how it looks on the frontend. The field should be empty by default.
4. Go back and add the letter 'S' to the date field and save the changes. Now, you should see the letter right after the day after you picked the date.
5. Go back to the editor and remove that string and save the changes. 
6. Now we're stuck on that site for the date field with that bug regardless of the page we add a form with a date block in. 

I launched the site and tried other things such as adding an ID or a value to it - nothing works.

#### What I expected
To be able to fix my initial mistake on step 4.

#### What happened instead
I was stuck with a date such as 5s Feb 2020

#### Browser / OS version
Chrome 79, macOS Catalina

#### Context / Source
#user-report 

Test site: https://fmr202020aaaaaccc.wordpress.com/contact/

I cannot replicate this on a self-hosted site.

**Comment by jeherve** [comment]
Closing as duplicate of #11251
