### ISSUE TITLE
Feature Request: Pass Donations Block Title to Stripe Modal

### ISSUE THREAD

**Issue by jordesign** [Automattic/jetpack#25030]
### What

Currently the Stripe modal that loads from the Donations block *always* includes 'Donation'

### Why

The use of 'Donation' in all cases is a little limiting. For other purposes like a 'Tip Jar' it would be nice if it could be customized - perhaps using the title used in the Donation Block itself.

<img width="532" alt="Screen Shot 2021-09-03 at 10 00 18 am" src="https://user-images.githubusercontent.com/1842363/131930728-fe7041c7-8786-4b2c-a45d-43498811fe6e.png">

### How

I'm not sure what information we can pass through to that modal - so the first step is probably investigating that.

**Comment by dsas** [comment]
This is reminiscent of paYJgx-2hq-p2#comment-2531

**Comment by mmtr** [comment]
Is there any reason why we cannot simply always say "Pay X once" for both donations and other payment blocks? I think that works for all scenarios given that's what the customer is ultimately doing (to pay for something). I'll open a PR today implementing that proposal to gather extra feedback.

**Comment by mmtr** [comment]
> Is there any reason why we cannot simply always say "Pay X once" for both donations and other payment blocks?

Opened D86063-code implementing this.

**Comment by mmtr** [comment]
Just deployed D86063-code which neutralizes the wording in the checkout form so it works for all plan types. We now display this for both the Donations block and the Payment button block:

One-off | Recurring
--- | ---
![image](https://user-images.githubusercontent.com/1233880/185408351-e8c9e7f3-8278-4cf3-96ea-5d656b87aba6.png) | ![image](https://user-images.githubusercontent.com/1233880/185408421-a1a6c4d8-0ab8-4fe0-87d9-0c8e87bb0422.png)

**Comment by mmtr** [comment]
Reopening since we had to revert the diff above because of a regression (more details in p1661441678719449-slack-C02FMH4G8).

**Comment by mmtr** [comment]
Created D86670-code as a 2nd attempt that also prevents the regression introduced by the previous patch.
