### ISSUE TITLE
fetch_feed / shortcode [youtube] on frontpage from child theme

### ISSUE THREAD

**Issue by dreaddy** [Automattic/jetpack#2504]
Modifying a "store" child theme. 
Created a new content page that calls fetch_feed() on a blogspot rss feed on the frontpage.
fetch_feed returns content with embedded shortcode 
[youtube http://www.youtube.com/watch?v=TFa-v_W07b0] 
The content gets printed but jetpack does not fire.
Any ideas?

Or

How do I force jetpack to recognize shortcodes on the frontpage?

**Comment by kraftbj** [comment]
My initial thought is that you'll need to wrap `fetch_feed` with `do_shortcode`. If you need any assistance, please do drop us a line. https://jetpack.me/contact-support/

**Comment by dreaddy** [comment]
Based on kraftbjs' suggestion. I've come up with the following solution should anyone be interested


							$content = $doc->saveHTML();
after collecting html							
							$pattern = "/\[youtube.*\]/";
							 
							preg_match($pattern, $content, $matches);
search for youtube shortcode							
							if( $matches[0] ){								
								$yt = do_shortcode($matches[0]);		
								$content = preg_replace($pattern, $yt, $content );
							}

if match found replace shortcode with do_shortcode content.

Hope this helps.

**Comment by kraftbj** [comment]
I think you may be overthinking it some. I sent you an e-mail, but do_shortcode will accept whatever content you throw at it and return that same content with any registered shortcodes rendered in place. The above approach, it appears, would only selectively fire for youtube shortcodes.

**Comment by dreaddy** [comment]
"...would only selectively fire for youtube shortcodes..."
Agreed.  this is the current intent.
