### ISSUE TITLE
Publicize: add douban.com, weibo.com and wechat.com

### ISSUE THREAD

**Issue by c3zh** [Automattic/jetpack#2507]
User wants to extend the current social services to a few Chinese ones like douban.com, weibo.com and wechat.com.

**Comment by jeherve** [comment]
Since these are niche social services, targeting specific markets, I don't think we'll add these services to Publicize.

I'll mark as wontfix for now.

**Comment by htdat** [comment]
Just for tracking, another request for Weibo - 1187109-zen
