### ISSUE TITLE
Restaurant menu: Why making certain methods private in `Nova_Restaurant` class?

### ISSUE THREAD

**Issue by webmandesign** [Automattic/jetpack#25077]
### Impacted plugin

Jetpack

### Steps to Reproduce

If you use my theme [Auberge](https://wordpress.org/themes/auberge/) which is compatible with Restaurant Menu custom post type functionality of Jetpack plugin, it does not work as intended anymore.

### A clear and concise description of what you expected to happen.

The theme stopped displaying food menu on-page navigation, heading structure is compromised on front page, and there are possibly other issues.

### What actually happened

This issue happens due to certain methods in [`Nova_Restaurant` class](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/modules/custom-post-types/nova.php) been set as `private` in #24212.

My [Auberge](https://wordpress.org/themes/auberge/) theme [extends `Nova_Restaurant` class](https://github.com/webmandesign/auberge/blob/master/includes/plugins/jetpack/class-nova-restaurant.php) and now I can not change these methods as PHP class extension does not work on private methods. Here are specific methods affected (but could be applied on others):
- `get_menu_item_menu_leaf()`
- `menu_item_loop_header()`
- `menu_item_loop_open_element()`
- `get_menu_item_loop_markup()`

**Can you explain why these methods were set as private?**
**Can these be reverted back to public scope?**

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Workaround details

There seems to be no way for me to "fix" this issue via the theme as I would have to rewrite more methods in the class just because I have to introduce my custom methods replacing the private originals. It does not seem the correct way as I would basically duplicate a lot of code unnecessary.

### Browser

Other / Not applicable

**Comment by kraftbj** [comment]
Seems fine to make these public. @coder-karen could you create a PR for this?

**Comment by coder-karen** [comment]
Just adding here it's not 'completed' as such (the changes not live in the Jetpack plugin), but as soon as the next release is out it will be.

**Comment by coder-karen** [comment]
Jetpack version 11.1.2 is now out which includes the fix.

**Comment by webmandesign** [comment]
@coder-karen Fantastic! Everything works perfectly fine again. Thank you very much for quick help with this!
