### ISSUE TITLE
Analytics: move from internal wrapper to @automattic/jetpack-analytics package

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#25113]
### Impacted plugin

Jetpack

### Steps to Reproduce

In multiple places in the Jetpack plugin, in our block editor bundle as well as our Widget Visibility bundle, we call `_inc/client/lib/analytics` to provide Tracks functionality. 

Now that we have the `@automattic/jetpack-analytics` package, it may make more sense to use that directly instead.

### References

Here are the references as of today:

- [ ] https://github.com/Automattic/jetpack/blob/a43815ecaaeaa8334757e2279c4a1c6a1fa5b08b/projects/plugins/jetpack/extensions/editor.js#L2
- [ ] https://github.com/Automattic/jetpack/blob/a99e0ccac5aeb9092b5c01d75af6846386182738/projects/plugins/jetpack/extensions/blocks/anchor-fm/editor.js#L10
- [ ] https://github.com/Automattic/jetpack/blob/a99e0ccac5aeb9092b5c01d75af6846386182738/projects/plugins/jetpack/extensions/blocks/social-previews/upgrade.js#L4
- [ ] https://github.com/Automattic/jetpack/blob/e7067c4f42dac3539b1548f074088713f3384276/projects/plugins/jetpack/extensions/extended-blocks/paid-blocks/utils.js#L1
- [ ] https://github.com/Automattic/jetpack/blob/a99e0ccac5aeb9092b5c01d75af6846386182738/projects/plugins/jetpack/extensions/plugins/payments/index.js#L8
- [ ] https://github.com/Automattic/jetpack/blob/a99e0ccac5aeb9092b5c01d75af6846386182738/projects/plugins/jetpack/extensions/shared/components/stripe-connect-toolbar-button/index.js#L3
- [ ] https://github.com/Automattic/jetpack/blob/a99e0ccac5aeb9092b5c01d75af6846386182738/projects/plugins/jetpack/extensions/shared/components/stripe-nudge/index.jsx#L4
- [ ] https://github.com/Automattic/jetpack/blob/a99e0ccac5aeb9092b5c01d75af6846386182738/projects/plugins/jetpack/modules/widget-visibility/editor/index.jsx#L8

**Comment by anomiex** [comment]
It looks like `_inc/client/lib/analytics` is already a wrapper for `@automattic/jetpack-analytics`, but it also sets some default values on the returned object. If every use would have to reproduce that default-value setting, the change seems like it would go against DRY and not be worth the trouble.

On the other hand, any that don't need those defaults could be fixed. And if that leaves just one or two then those could do the default setting manually.

**Comment by jeherve** [comment]
> If every use would have to reproduce that default-value setting, the change seems like it would go against DRY and not be worth the trouble.

That's very true.

The original motivation behind this issue for me would be to remove the need for the block editor's bundles to rely on code from the React bundle. Right now those 2 are shipped together, but in the future that may not be the case; the extensions bundle or some of its elements may live in a different package, required by different plugins. This is especially relevant for the use of analytics in Payment-related blocks, for example.

**Comment by jeherve** [comment]
This was done in #27940.

**Comment by jeherve** [comment]
Actually reopening, since it still needs to be implemented for the Widget Visibility bundle:
https://github.com/Automattic/jetpack/blob/51662562c6c5a835102906cf6b6a39074058cc3b/projects/plugins/jetpack/modules/widget-visibility/editor/index.jsx#L8
