### ISSUE TITLE
Notice:  "wp-editor" script should not be enqueued together with the new widgets editor 

### ISSUE THREAD

**Issue by htmgarcia** [Automattic/jetpack#25120]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Enable WP_DEBUG
2. Enable a regular theme to be able to visit Widgets page in admin
3. Go to Appearance > Widgets
4. A notice is displayed
`( ! ) Notice: Function wp_enqueue_script() was called <strong>incorrectly</strong>. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.8.0.) in wp-includes/functions.php on line 5831`

### A clear and concise description of what you expected to happen.

Enqueue 'wp-customize-widgets' or 'wp-edit-widgets' instead of 'wp-edit' in admin Widgets screen

### What actually happened

'wp-edit' seems to be enqueued in admin Widgets screen

### Browser

Mozilla Firefox

### Other information

Jetpack 11.1.1
MacOS Big Sur 11.6

### Reproducibility

Consistent

**Comment by jeherve** [comment]
Thanks for the report. This is already tracked in #20357, so I'll close your issue in favor of the other one.
