### ISSUE TITLE
Enhancement: Allow Group, Row, Stack, Columns, etc. in Form block

### ISSUE THREAD

**Issue by noisysocks** [Automattic/jetpack#25123]
### Impacted plugin

Jetpack

### What

Allow layout blocks such as Group, Row, Stack, Columns, etc. as children in the Form block

### How

It's difficult to build something like this in a block theme using Jetpack's Form block, as you cannot group the Form fields (Date, Text, Select, etc.) into a Row block to have them arranged horizontally. 

<img width="1116" alt="Screen Shot 2022-07-19 at 14 01 01" src="https://user-images.githubusercontent.com/612155/179663569-5cc71591-9791-4368-96f9-b8fe59da5827.png">

You can use Field Width to have up to four items arranged horizontally, but this is obviously pretty limited compared to the layouts you can build using native layout blocks which are only getting more powerful with each Gutenberg release.

<img width="298" alt="Screen Shot 2022-07-19 at 14 18 30" src="https://user-images.githubusercontent.com/612155/179663683-9ad106d3-079c-4ed7-9b53-b1c0b0f0ff29.png">

Ideally Form should not be so restrictive about what children it contain. In my mind Form should be analogous to `<form>` and allow _any_ block as a child **plus** additional Form field blocks.

**Comment by CGastrell** [comment]
Allowing those blocks triggers a buggy behavior where inputs depend on being direct descendants of a form wrapper. We're looking at some alternatives.
