### ISSUE TITLE
De-Fusion: require_lib()

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25159]
```
"$plugin_root/require-lib.php"   => "$wpcom_root/wp-content/mu-plugins/0-jetpacklib.php",
```

**Comment by anomiex** [comment]
See also p9dueE-5EZ-p2

**Comment by anomiex** [comment]
We're close enough that we can move on to the "remove all existing uses" step:

* In Jetpack: #27094
* In wpcom: D90775-code
* The one in wpcomsh: https://github.com/Automattic/wpcomsh/pull/1120

Once the Jetpack and wpcom patches are merged and deployed, we can move on to the next step of removing it from wpcom and adding deprecation warnings to the copy in Jetpack.

After that, we'll wait 2 or 3 Jetpack releases before deleting the function from Jetpack too.

**Comment by anomiex** [comment]
Now we're waiting for 11.6-a.1 to be deployed to wpcom.

**Comment by anomiex** [comment]
Wpcom removal: D91709-code
Jetpack deprecation warnings: #27273

**Comment by anomiex** [comment]
Actual de-Fusioning is done, so let's close this. There's still the final removal to do in March, but no need to keep this open until then.
