### ISSUE TITLE
De-Fusion: 3rd Party Compatability Tools

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25172]
### Impacted plugin

Jetpack

### What

3rd Party compatibility tools

### How

```
"$plugin_root/3rd-party/3rd-party.php"                    => "$wpcom_root/wp-content/mu-plugins/jetpack/3rd-party/3rd-party.php",
"$plugin_root/3rd-party/class.jetpack-amp-support.php"    => "$wpcom_root/wp-content/mu-plugins/jetpack/3rd-party/class.jetpack-amp-support.php",
```

D88774-code to start this work.

**Comment by kraftbj** [comment]
Rerouting existing calls to the file D88774-code
landed in r253477-wpcom

Removal of files in D88860-code
landed in r253480-wpcom

Notable: AMP is no longer supported on WP.com. I didn't remove the compact file on WP.com itself (that called the JP files) until the AMP plugin itself is removed https://github.com/Automattic/wp-calypso/issues/64004
