### ISSUE TITLE
De-Fusion: Build-related

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25174]
### Impacted plugin

Jetpack

### What

Build-related. These are autoloaded by Jetpack

### How

```
"$plugin_root/src/" => "$wpcom_root/wp-content/mu-plugins/jetpack-plugin/src/",
```

**Comment by anomiex** [comment]
Looks like the path was already removed in r234396-wpcom.

**Comment by sdixon194** [comment]
Removed from the list in r249568-wpcom
