### ISSUE TITLE
De-Fusion: Copy Post

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25179]
### Impacted plugin

Jetpack

### What

Copy Post

### How

```
"$plugin_root/modules/copy-post.php" => "$wpcom_root/wp-content/mu-plugins/jetpack/modules/copy-post.php",
```

**Comment by sdixon194** [comment]
Defusion: D86495-code
Cleanup: D86497-code

**Comment by samiff** [comment]
Looks good to go 🚢

**Comment by sdixon194** [comment]
Defusion: r251273-wpcom
Cleanup: r251277-wpcom
Update list: https://github.com/Automattic/jetpack/pull/25832
