### ISSUE TITLE
De-Fusion: Carousel

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25176]
### Impacted plugin

Jetpack

### What

Carousel

### How

```
"$plugin_root/modules/carousel.php" => "$wpcom_root/wp-content/mu-plugins/carousel.php",
"$plugin_root/modules/carousel/"    => "$wpcom_root/wp-content/mu-plugins/carousel/",
```

**Comment by sdixon194** [comment]
Defusion: D86501-code
Cleanup: D86505-code

To test: Copy both branches to your sandbox, enable the carousel on your sanboxed site. Add a gallery and make sure the carousel still works.

**Comment by samiff** [comment]
Tested well for me :shipit:

**Comment by sdixon194** [comment]
Defusion: r251284-wpcom
Cleanup: r251285-wpcom
List update: https://github.com/Automattic/jetpack/pull/25832

**Comment by sdixon194** [comment]
There were some fatals because I missed an area where a deleted file was called in a legacy widget. After action to come:

redeployedin r251373-wpcom
cleanup: r251375-wpcom
