### ISSUE TITLE
De-Fusion Server-side rendered React components library

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25178]
### Impacted plugin

Jetpack

### What

Server-side rendered React components library

### How

```
"$plugin_root/_inc/lib/components.php" => "$wpcom_root/wp-content/lib/components.php",
```

**Comment by anomiex** [comment]
- De-Fusioning: D88232-code
- Jetpack: #26321
- Clean-up stub: TBD

**Comment by anomiex** [comment]
Done! I'll leave the stub cleanup for later, we should probably just do a pass for all such stubs once all the de-Fusioning is done.
