### ISSUE TITLE
De-Fusion: readme.txt

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25187]
### Impacted plugin

Jetpack

### What

readme.txt

### How

```
"$plugin_root/readme.txt" => "$wpcom_root/wp-content/mu-plugins/jetpack/readme.txt",
```

**Comment by coder-karen** [comment]
**What has been done:**

1. Updating the mu-plugin file to make sure all references point to the jetpack production readme.txt: D85985-code 
2. Cleaning up Fusion references, and deleting the `mu-plugins/jetpack/readme.txt` file: D85987-code

**How to test:**

1. Patch D85985-code to sandbox. 
2. You can add an error log to `wpcom/wp-content/mu-plugins/jetpack/jetpack.php` further down the file (such as in the `is_jetpack_site_filter` function) to echo out the result of calling the `get_jetpack_current_version` function (to echo out the stable tag). It should echo out correctly and not result in any errors, if you navigate to a Jetpack dashboard page (WordPress.com) on a sandboxed WordPress.com site.
4. You can then also apply D85987-code as well (or manually add the changes from that diff with the other checked out). With the error log still in place, you should still see the same version output.

**Comment by coder-karen** [comment]
Update changeset: r251199-wpcom
Cleanup changeset (updating the build plugin files list): r251202-wpcom
Second cleanup changeset (... deleting the readme): r251207-wpcom
Build clean-up: #25813
