### ISSUE TITLE
De-Fusion: Featured Content

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25185]
### Impacted plugin

Jetpack

### What

Featured Content

### How

```
"$plugin_root/modules/theme-tools/featured-content.php" => "$wpcom_root/wp-content/mu-plugins/featured-content/featured-content.php",
```

**Comment by anomiex** [comment]
* De-Fusion part 1: D86964-code
* De-Fusion part 2: D86965-code
* List update: https://github.com/Automattic/jetpack/pull/25960
