### ISSUE TITLE
De-Fusion: Filter Embedded HTML Objects (shortcode reversals)

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25188]
### Impacted plugin

Jetpack

### What

Filter Embedded HTML Objects (shortcode reversals)

### How

```
"$plugin_root/modules/shortcodes/class.filter-embedded-html-objects.php" => "$wpcom_root/wp-content/lib/class.filter-embedded-html-objects.php",
```

**Comment by sdixon194** [comment]
Defusion: D87629-code
Cleanup: D87630-code

I don't think the `jetpack_require_lib` steps fit here since we're just replacing a regular require_lib call?

**Comment by samiff** [comment]
Looks like an easy case replacement to me 👍

**Comment by sdixon194** [comment]
Deploy: r252499-wpcom
Cleanup: r252509-wpcom
