### ISSUE TITLE
De-Fusion: Global Functions

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25186]
### Impacted plugin

Jetpack

### What

Global Functions

### How

```
"$plugin_root/functions.global.php" => "$wpcom_root/wp-content/mu-plugins/jetpack/functions.global.php",
```

**Comment by sdixon194** [comment]
There seems to be an issue with the `jetpack_is_mobile` function, which doesn't exist on the wpcom version of the file. We may have to handle https://github.com/Automattic/jetpack/issues/25213 first.

**Comment by anomiex** [comment]
This should be clear to go now.

**Comment by sdixon194** [comment]
Defusion: D91582-code
Cleanup: D91583-code

**Comment by anomiex** [comment]
Looks good :ship:

**Comment by sdixon194** [comment]
Defusion: r255761-wpcom
Cleanup: r255763-wpcom
