### ISSUE TITLE
De-Fusion: Dashboard

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25183]
### Impacted plugin

Jetpack

### What

Dashboard

### How

```
"$plugin_root/_inc/client/lib/analytics/" => "$wpcom_root/wp-content/mu-plugins/jetpack/_inc/client/lib/analytics/",
"$plugin_root/_inc/client/config.js"      => "$wpcom_root/wp-content/mu-plugins/jetpack/_inc/client/config.js",
```

**Comment by coder-karen** [comment]
With this, may be best to wait until #25214 and #25184 are done first.

See this Slack thread for more context: p1662994083864979-slack-C032DVAHMK3

**Comment by anomiex** [comment]
Looks like this may also need to wait for #25245

**Comment by anomiex** [comment]
* Diff: D88734-code

**Comment by anomiex** [comment]
Done!
