### ISSUE TITLE
De-Fusion: WP REST API Extensions

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25199]
### Impacted plugin

Jetpack

### What

WP REST API Extensions

### How

```
"$plugin_root/_inc/lib/core-api/class-wpcom-rest-field-controller.php" => "$wpcom_root/wp-content/rest-api-plugins/centralized/class-wpcom-rest-field-controller.php",
```

**Comment by samiff** [comment]
Update diff: D88846-code (note about `/tests/php/core-api/test_class-wpcom-rest-field-controller.php` in there)
Testing: make sure tests are passing and observe post-deploy statuses; this should be a straightforward swap.

**Comment by sdixon194** [comment]
Unsure how to test this other than making sure the new location is loading, but let's make sure we're around to monitor this one.

**Comment by sdixon194** [comment]
deployed r254212-wpcom
