### ISSUE TITLE
De-Fusion: JSON API

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25198]
### Impacted plugin

Jetpack

### What

JSON API

### How

```
"$plugin_root/class.json-api.php"           => "$wpcom_root/public.api/rest/class.json-api.php",
"$plugin_root/class.json-api-endpoints.php" => "$wpcom_root/public.api/rest/class.json-api-endpoints.php",
"$plugin_root/json-api-config.php"          => "$wpcom_root/public.api/rest/json-api-config.php",
"$plugin_root/json-endpoints.php"           => "$wpcom_root/public.api/rest/json-endpoints.php",
```

**Comment by sdixon194** [comment]
Noting this diff here where they were looking to refactor some functions shared between different parts of the codebase: D86048-code

Don't think that's the approach we'll be able to take with that, but flagging to follow up after defusioning is complete.

**Comment by samiff** [comment]
Jetpack PRs that will need to deploy to wpcom first:

- [x] #26565

- [x] #27064

Update diff: D88937-code

Cleanup diff: leaving stubs since lots of comments link to those locations. Individual `public.api/rest/json-endpoints/$endpoint` defusioning happening in separate issues.

**Comment by samiff** [comment]
`"$plugin_root/class.json-api-endpoints.php" => "$wpcom_root/public.api/rest/class.json-api-endpoints.php",`

- Missing changes from D87463-code , D82754-code , D77654-code

PR to sync: https://github.com/Automattic/jetpack/pull/27064

**Comment by samiff** [comment]
Aside from the #27064 that needs to be deployed to WPcom first (11.6-a.3 likely), update diff D88937-code should be ready to go, though currently hitting a fatal since `class.wpcom-json-api-get-site-endpoint.php` still being worked on in #26772

**Comment by sdixon194** [comment]
Rebased but still failing, assuming we need to wait for 11.5-a.3 to land next week.

**Comment by samiff** [comment]
#27371 merged
D88937-code landed in r256065-wpcom
