### ISSUE TITLE
De-Fusion: Likes

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25205]
### Impacted plugin

Jetpack

### What

Likes

### How

This one might be good to save for last.

```
"$plugin_root/modules/likes.php"                        => "$wpcom_root/wp-content/mu-plugins/likes/jetpack-likes.php",
"$plugin_root/modules/likes/jetpack-likes-settings.php" => "$wpcom_root/wp-content/mu-plugins/likes/jetpack-likes-settings.php",
"$plugin_root/modules/likes/style.css"                  => "$wpcom_root/wp-content/mu-plugins/likes/jetpack-likes.css",
"$plugin_root/_inc/jquery.jetpack-resize.js"            => "$wpcom_root/wp-content/js/jquery/jquery.jetpack-resize.js",
// This file was removed from Jetpack, and will be removed from wpcom once it's synced.
//"$plugin_root/_inc/jquery.inview.js"                  => "$wpcom_root/wp-content/js/jquery/jquery.inview.js",
"$plugin_root/_inc/postmessage.js"                      => "$wpcom_root/wp-content/js/postmessage.js",
"$plugin_root/modules/likes/post-count.js"              => "$wpcom_root/wp-content/mu-plugins/likes/post-count.js",
"$plugin_root/modules/likes/post-count-jetpack.js"      => "$wpcom_root/wp-content/mu-plugins/likes/post-count-jetpack.js",
"$plugin_root/modules/likes/queuehandler.js"            => "$wpcom_root/wp-content/mu-plugins/likes/queuehandler.js",
```

**Comment by sdixon194** [comment]
`$plugin_root/modules/likes.php` is pretty out of sync.

These files seem to be removed from Jetpack but still exist on dotcom. I'm wondering if they can just be removed.
- jquery.jetpack-resize.js
- jquery.inview.js
- postmessage.js

everything else is in sync.

**Comment by anomiex** [comment]
Looking at likes.php, Jetpack missed

* r170101-wpcom
  * Although the widget doesn't seem to be hidden by CSS on Jetpack sites...
* D10021-code
* D10955-code (note the affected code had been moved to a different file in #7175)
* D25102-code and some followups
* D66115-code (although part was later done in #21022)

and wpcom missed

* a8a08451fba74fb7e9cd8af24e3a1683bbe76985
* 5ad7a7208145626efc2d22d5137f1439284dcce6
* e6bb90aad2a3410eacfc22ff67900784a6db14f9
* b9afd0724d0ff6da64b7b25adb9a1c6e154830a5
* 75698bb34d3bde2755a0f4ce147419f3410a1d12
* 0431ff7001e4de3acf6ad4399b2b9d0fec5bed42
* #4987
* #5988
* #7175
* #8329
* #16305
* Parts of #19250

**Comment by anomiex** [comment]
So #27008 will bring in all the stuff Jetpack missed except for r170101-wpcom, since the justification given there for deleting it on wpcom doesn't seem to apply to Jetpack.

**Comment by anomiex** [comment]
After further testing and investigation, this seems like a huge mess and the best option seems to be to just let the two continue going their separate ways.

* p9dueE-64G-p2
* #27062 
* D90671-code
