### ISSUE TITLE
De-Fusion: Minileven

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25208]
### Impacted plugin

Jetpack

### What

Minileven

### How

These are all commented out in build-plugin-files.php anyway, so may not need to update anywhere and can just close out and remove hopefully.

```
//"$plugin_root/modules/minileven/theme/pub/minileven/" => "$wpcom_root/wp-content/themes/pub/minileven/",
//"$plugin_root/modules/minileven/minileven.php"        => "$wpcom_root/wp-content/mu-plugins/wp-mobile.php",
//"$plugin_root/modules/minileven/images/"              => "$wpcom_root/wp-content/mu-plugins/wp-mobile/images/",
```

**Comment by sdixon194** [comment]
These files don't exist in Jetpack anymore. Looking around the code, some other extraneous code on wpcom may reference minileven. I'm thinking we just remove this from the built files list for now but don't remove the minileven folder to ensure we don't accidentally break something hard-wired anywhere.

D88760-code

**Comment by anomiex** [comment]
Sounds good to me, it's not a Jetpack thing anymore so we should let wpcom people deal with it.
