### ISSUE TITLE
De-Fusion: SEO Tools

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25203]
### Impacted plugin

Jetpack

### What

SEO Tools

### How

```
"$plugin_root/modules/seo-tools/jetpack-seo.php"        => "$wpcom_root/wp-content/lib/seo-tools/jetpack-seo.php",
"$plugin_root/modules/seo-tools/jetpack-seo-posts.php"  => "$wpcom_root/wp-content/lib/seo-tools/jetpack-seo-posts.php",
"$plugin_root/modules/seo-tools/jetpack-seo-titles.php" => "$wpcom_root/wp-content/lib/seo-tools/jetpack-seo-titles.php",
"$plugin_root/modules/seo-tools/jetpack-seo-utils.php"  => "$wpcom_root/wp-content/lib/seo-tools/jetpack-seo-utils.php",
```

**Comment by samiff** [comment]
Update diff: D85493-code
Cleanup diff: D85495-code

**To test:**

- Apply D85493-code to sandbox on a simple WPcom site with Business plan.
- Delete `wp-content/lib/seo-tools/` dir to simulate the cleanup diff.
- Verify that SEO Tools features are still working (try changing settings and viewing on frontend), and that no errors are reported on sandbox.
  - `https://wordpress.com/marketing/traffic/__SITE__`

**Comment by samiff** [comment]
Update changeset: r250558-wpcom
Cleanup changeset: r250566-wpcom
