### ISSUE TITLE
De-Fusion: Genericons

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25212]
### Impacted plugin

Jetpack

### What

Genericons

### How

```
"$plugin_root/_inc/genericons.php" => "$wpcom_root/wp-content/mu-plugins/genericons.php",
"$plugin_root/_inc/genericons/"    => "$wpcom_root/wp-content/mu-plugins/genericons/",
```

**Comment by coder-karen** [comment]
I've taken a look at this, and approached this one in the following way:

1. The Jetpack and WPcom files were in sync, so no steps needed here.
2. Updated the main mu-plugin file to point to the new Jetpack plugin path: D85555-code
3. Cleanup obsolete Fusion references: D85556-code


To test this out:

1. Apply D85555-code while sandboxed. 
2. Add a theme like Ryu that includes genericons.
3. Add a social menu. This can be done by going to the customiser and selecting theme options, then adding any link (eg. an email link). 
4. Click on the link icon in the preview - you should be viewing correct icons (and not square boxes indicating the genericon styles aren't being found).
5. You can also test by adding an error log in the wpcom specific file with a message indicating the file is being read - that will also confirm the file is being viewed and then the redirect happening.

**Comment by samiff** [comment]
@coder-karen This tested well for me and is ready to deploy 👍

**Comment by coder-karen** [comment]
Update changeset: r250351-wpcom
Cleanup changeset: r250352-wpcom
