### ISSUE TITLE
De-Fusion: Google fonts

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25219]
### Impacted plugin

Jetpack

### What

Google Fonts

### How

```
"$plugin_root/modules/google-fonts.php" => "$wpcom_root/wp-content/mu-plugins/google-fonts.php",
```

**Comment by samiff** [comment]
wpcom was missing updates done in #24098 so the file is out of sync. From what I read those fonts were intended to be used on wpcom as well, so loading the JP version of the file should be fine.

Update diff: D86621-code
Post-deploy de-fusion reminder: #25850

Testing: 

- Apply D86621-code to sandbox.
- On sandbox site, enable a block theme and open the site editor. Try using the global font styles, make sure no errors are generated.
  - To note, I was able to see the Jetpack plugin version of the file loaded fine via an error log. The actual fonts shown in the dropdown depend on additional logic and filters however.

**Comment by samiff** [comment]
r251403-wpcom
