### ISSUE TITLE
De-Fusion: Podcast Block Helper

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25210]
### Impacted plugin

Jetpack

### What

Podcast Block Helper

### How

```
"$plugin_root/_inc/lib/class-jetpack-podcast-helper.php"  => "$wpcom_root/wp-content/lib/class-jetpack-podcast-helper.php",
```

**Comment by samiff** [comment]
Update diff: D88763-code | r253462-wpcom
Jetpack PR: #26522 (wait for 11.5-a.1 deploy)
Cleanup diff: D88764-code

Testing: after #26520 is sorted, can give the podcast block a thorough testing with all changes.

**Comment by samiff** [comment]
r254302-wpcom
