### ISSUE TITLE
De-Fusion: Open Graph

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25215]
### Impacted plugin

Jetpack

### What

Open Graph

### How

```
"$plugin_root/functions.opengraph.php" => "$wpcom_root/wp-content/blog-plugins/open-graph.php",
"$plugin_root/enhanced-open-graph.php" => "$wpcom_root/wp-content/blog-plugins/enhanced-open-graph.php",
```

**Comment by coder-karen** [comment]
Update diff: D86963-code
Cleanup diff: D87111-code
Update PR (for later): #26011

Testing: While sandboxed, with the first diff applied, create a post on a WPcom site and add some content. Publish the post, then and view the page source. You should see Open Graph tags added underneath `<!-- Jetpack Open Graph Tags -->`.
Then, apply the second diff (or apply the changes in the second diff) as well as the first, to make sure everything is still working properly.

**Comment by coder-karen** [comment]
Update diff deployed: r252122-wpcom

Cleanup diff deployed: r252126-wpcom

Update PR merged.
