### ISSUE TITLE
De-Fusion: Photon

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25217]
### Impacted plugin

Jetpack

### What

Photon

### How

```
"$plugin_root/functions.photon.php" => "$wpcom_root/wp-content/mu-plugins/photon.php",
```

**Comment by samiff** [comment]
Update diff: D86624-code
Post-deploy de-fusion reminder: #25851

Testing: file was in sync, so this is a simple stub replacement.

**Comment by samiff** [comment]
r251405-wpcom
