### ISSUE TITLE
De-Fusion: Media Extraction/Analysis

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25216]
### Impacted plugin

Jetpack

### What

Media Extraction/Analysis

### How

```
"$plugin_root/_inc/lib/class.media-extractor.php" => "$wpcom_root/wp-content/lib/class.wpcom-media-meta-extractor.php",
"$plugin_root/_inc/lib/class.media-summary.php"   => "$wpcom_root/wp-content/lib/class.wpcom-media-summary.php",
```

**Comment by samiff** [comment]
Update diff: D88855-code
Jetpack PR: #26539 (wait for 11.5-a.1 to deploy)
Cleanup diff: D88856-code

Testing: the diffs touch a few files, so will want to manually test on sandbox and really watch post-deploy for any issues.

**Comment by sdixon194** [comment]
I couldn't quite get this to be reproduced consistently, so difficult to say if it's because of this diff, but do you see:

>  Elasticsearch error: {"level":"warning","message":"Deprecation","context":["299 Elasticsearch-7.17.6-f65e9d338dc1d07b642e14a27f338990148ee5b6 \"[interval] on [date_histogram] is deprecated, use [fixed_interval] or [calendar_interval] in the future.\""]}

I think it happened when poking around wp-admin's post list.

**Comment by sdixon194** [comment]
Nevermind this happened elsewhere so I think it's unrelated. Maybe we do this one last and keep an eye out for fatals.

**Comment by sdixon194** [comment]
Defusion: r253874-wpcom
After deploy of 11.5-a.1, cleanup of stubs: r254215-wpcom
