### ISSUE TITLE
De-Fusion: Search

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25229]
### Impacted plugin

Jetpack

### What

Search

### How

```
"$plugin_root/modules/search/class-jetpack-search-customize.php"  => "$wpcom_root/wp-content/mu-plugins/site-search/class-jetpack-search-customize.php",
```

**Comment by samiff** [comment]
`$plugin_root/modules/search/class-jetpack-search-customize.php` doesn't exist in the monorepo (though the file still exists on wpcom).

Cleanup diff: D88843-code

**Comment by samiff** [comment]
r253472-wpcom
