### ISSUE TITLE
De-Fusion: Quiz Shortcode

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25222]
### Impacted plugin

Jetpack

### What

Quiz Shortcode

### How

```
"$plugin_root/modules/shortcodes/quiz.php"     => "$wpcom_root/wp-content/mu-plugins/shortcodes/quiz/quiz.php",
"$plugin_root/modules/shortcodes/css/quiz.css" => "$wpcom_root/wp-content/mu-plugins/shortcodes/quiz/css/quiz.css",
"$plugin_root/modules/shortcodes/js/quiz.js"   => "$wpcom_root/wp-content/mu-plugins/shortcodes/quiz/js/quiz.js",
```

**Comment by coder-karen** [comment]
Update diff: D87027-code
Cleanup diff: D87029-code (includes unit test)
Update PR (for later): #25984

Testing: While sandboxed, with the first diff applied, try adding a Quiz via shortcode (there is a demo that can be used at the [bottom of the page here](https://wordpress.com/support/quiz-shortcode/)). Make sure it works properly.
You can also add an error log in the Jetpack plugin quiz.php file to make sure we're reading the correct files.
Then, apply the second diff (or apply the changes in the second diff) as well as the first, to make sure everything is still working properly.

**Comment by coder-karen** [comment]
Update deploy: r252204-wpcom
Cleanup deploy: r252220-wpcom
Update PR merged.
