### ISSUE TITLE
De-Fusion: Related Posts

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25225]
### Impacted plugin

Jetpack

### What

Related Posts

### How

```
"$plugin_root/modules/related-posts/jetpack-related-posts.php" => "$wpcom_root/wp-content/mu-plugins/related-posts/jetpack-related-posts.php",
"$plugin_root/modules/related-posts/related-posts.css"         => "$wpcom_root/wp-content/mu-plugins/related-posts/related-posts.css",
```

**Comment by coder-karen** [comment]
No syncing needed (all auto-citations code on the WPcom side to be removed: p1666356726611189-slack-C032DVAHMK3) 

To test, apply both diffs and sandbox a WPcom site with related posts, to make sure the functionality still works. You can also add an error log in the jetpack-plugin jetpack-related-posts.php file to confirm everything is being served from Jetpack.

Update diff: D90462-code

Cleanup diff: D90463-code

**Comment by coder-karen** [comment]
Update changeset: r255100-wpcom

Cleanup changeset: r255104-wpcom
