### ISSUE TITLE
De-Fusion: Sharing

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25228]
### Impacted plugin

Jetpack

### What

Sharing

### How

```
"$plugin_root/modules/sharedaddy/admin-sharing.css"   => "$wpcom_root/wp-content/mu-plugins/post-flair/sharing/admin-sharing.css",
"$plugin_root/modules/sharedaddy/admin-sharing.js"    => "$wpcom_root/wp-content/mu-plugins/post-flair/sharing/admin-sharing.js",
"$plugin_root/modules/sharedaddy/recaptcha.php"       => "$wpcom_root/wp-content/mu-plugins/post-flair/sharing/recaptcha.php",
"$plugin_root/modules/sharedaddy/sharing-service.php" => "$wpcom_root/wp-content/mu-plugins/post-flair/sharing/sharing-service.php",
"$plugin_root/modules/sharedaddy/sharing-sources.php" => "$wpcom_root/wp-content/mu-plugins/post-flair/sharing/sharing-sources.php",
"$plugin_root/modules/sharedaddy/sharing.css"         => "$wpcom_root/wp-content/mu-plugins/post-flair/sharing/sharing.css",
"$plugin_root/modules/sharedaddy/amp-sharing.css"     => "$wpcom_root/wp-content/mu-plugins/post-flair/sharing/amp-sharing.css",
"$plugin_root/modules/sharedaddy/sharing.js"          => "$wpcom_root/wp-content/mu-plugins/post-flair/sharing/sharing.js",
"$plugin_root/modules/sharedaddy/sharing.php"         => "$wpcom_root/wp-content/admin-plugins/post-flair/sharing.php",
"$plugin_root/modules/sharedaddy/images/"             => "$wpcom_root/wp-content/mu-plugins/post-flair/sharing/images/",
```

**Comment by samiff** [comment]
`"$plugin_root/modules/sharedaddy/sharing.php" => "$wpcom_root/wp-content/admin-plugins/post-flair/sharing.php",` is quite out of sync.

**Comment by anomiex** [comment]
Looks like everything is in sync to me. Did you accidentally compare with `wp-content/mu-plugins/post-flair/sharing.php` instead of `wp-content/admin-plugins/post-flair/sharing.php`, since all the rest of the files are in mu-plugins?

**Comment by samiff** [comment]
> Did you accidentally compare with `wp-content/mu-plugins/post-flair/sharing.php` instead of `wp-content/admin-plugins/post-flair/sharing.php`

Probably did since they look in sync to me :)

**Comment by samiff** [comment]
Update diff: D90374-code
Cleanup diff: D90378-code

Testing: `example.wordpress.com/wp-admin/options-general.php?page=sharing` can be checked for the admin loaded resources and sharing options.

**Comment by coder-karen** [comment]
Tests well for me 👍

**Comment by samiff** [comment]
Update changeset: r254939-wpcom
Cleanup changeset: r254940-wpcom
