### ISSUE TITLE
De-Fusion: Random Redirect Plugin

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25223]
### Impacted plugin

Jetpack

### What

Random Redirect Plugin

### How

```
"$plugin_root/modules/theme-tools/random-redirect.php" => "$wpcom_root/wp-content/blog-plugins/random-redirect.php",
```

**Comment by anomiex** [comment]
Note there's a "hidden" reference to the file via `wp-content/mu-plugins/admin-plugins.php`. Probably best to leave a stub at `wp-content/blog-plugins/random-redirect.php` instead of deleting it entirely.

**Comment by samiff** [comment]
Update diff: D88752-code

**Testing:**

You could test that the correct production version of the php file is loading with an error log, and test that using `example.com/?random` still works on your site.

**Comment by samiff** [comment]
r253463-wpcom
