### ISSUE TITLE
De-Fusion: Recipes

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25224]
### Impacted plugin

Jetpack

### What

Recipes

### How

```
"$plugin_root/modules/shortcodes/recipe.php"              => "$wpcom_root/wp-content/mu-plugins/shortcodes/recipes/recipes.php",
"$plugin_root/modules/shortcodes/css/recipes.css"         => "$wpcom_root/wp-content/mu-plugins/shortcodes/recipes/css/recipes.css",
"$plugin_root/modules/shortcodes/css/recipes-print.css"   => "$wpcom_root/wp-content/mu-plugins/shortcodes/recipes/css/recipes-print.css",
"$plugin_root/modules/shortcodes/js/recipes.js"           => "$wpcom_root/wp-content/mu-plugins/shortcodes/recipes/js/recipes.js",
"$plugin_root/modules/shortcodes/js/recipes-printthis.js" => "$wpcom_root/wp-content/mu-plugins/shortcodes/recipes/js/recipes-printthis.js"
```

**Comment by coder-karen** [comment]
Update diff: D90243-code

Cleanup diff:  D90132-code

---

To test, apply both diffs and sandbox a WPcom site. Copy the example recipe shortcode from this support doc - https://wordpress.com/support/recipes/ - into a shortcode block. Confirm the recipe shortcode is still working.

**Comment by samiff** [comment]
Tested well for me :shipit:

**Comment by coder-karen** [comment]
Update: r254810-wpcom

Cleanup (including a dummy shortcodes test as the recipe test was the last remaining running test): r254836-wpcom
