### ISSUE TITLE
De-Fusion: Social Menus

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25234]
### Impacted plugin

Jetpack

### What

Social Menus

### How

```
"$plugin_root/modules/theme-tools/social-menu.php" => "$wpcom_root/wp-content/mu-plugins/social-menu.php",
"$plugin_root/modules/theme-tools/social-menu/"    => "$wpcom_root/wp-content/mu-plugins/social-menu/",
```

**Comment by coder-karen** [comment]
Sync PR: #26184 (to be merged and released on WPcom first) - merged.

---

The following is ready for review:

Update diff: D87618-code
Cleanup diff: D87619-code 

Testing instructions: 
* To test, add the Twenty Twenty theme to a Jetpack-connected site and in the `functions.php` file (or via a code snippets plugin) add the following: `add_theme_support( 'jetpack-social-menu', 'svg' );`. This is to make sure we test the `icon-functions.php` file as well.
* Make sure to add a social menu via `wp-admin/nav-menus.php`.
* The icons should display as expected without any errors.
* You can also add an error_log to the Jetpack plugin version of the files to make sure the content is being outputted.

**Comment by samiff** [comment]
The JP PR is now deployed, and these diffs look good to go 👍

**Comment by sdixon194** [comment]
Handling since Karen is AFK:

Defusion: r253203-wpcom
Cleanup: r253210-wpcom
