### ISSUE TITLE
De-Fusion: Social Logos

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25233]
### Impacted plugin

Jetpack

### What

Social Logos

### How

```
"$plugin_root/_inc/social-logos.php" => "$wpcom_root/wp-content/mu-plugins/social-logos.php",
"$plugin_root/_inc/social-logos/"    => "$wpcom_root/wp-content/mu-plugins/social-logos/",
```

**Comment by samiff** [comment]
Internal, approach for this one: p1663348368256779-slack-C032DVAHMK3

- [x] Update diff (defusion and mu stub): D87938-code / r252707-wpcom
- [x] Jetpack PR (wait for wpcom deploy before cleanup): #26267
- [x] Cleanup diff: D88444-code

**Comment by samiff** [comment]
r253143-wpcom
