### ISSUE TITLE
De-Fusion: Simple Payments

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25235]
### Impacted plugin

Jetpack

### What

Simple Payments

### How

```
"$plugin_root/modules/simple-payments/" => "$wpcom_root/wp-content/mu-plugins/simple-payments/",
```

**Comment by samiff** [comment]
Update diff: D88748-code
Cleanup diff: D88750-code

Testing:

Patch with changes and make sure that adding a simple payments block (Pay with PayPal) continues to work as expected.

**Comment by sdixon194** [comment]
Works for me, tested on existing blocks, adding new blocks, and on a FSE site 👍

**Comment by sdixon194** [comment]
Update deploy: r254203-wpcom
Cleanup deploy: r254205-wpcom
