### ISSUE TITLE
De-Fusion: Subscriptions

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25237]
### Impacted plugin

Jetpack

### What

Subscriptions

### How

```
"$plugin_root/modules/subscriptions/views.php" => "$wpcom_root/wp-content/mu-plugins/widgets/blog-subscription.php",
```

**Comment by samiff** [comment]
Update diff: D88834-code

Testing: ensure that the blog subscription widget continues to function as expected.

**Comment by samiff** [comment]
r253465-wpcom
