### ISSUE TITLE
De-Fusion: Sitemaps

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25236]
### Impacted plugin

Jetpack

### What

Sitemaps

### How

```
"$plugin_root/modules/sitemaps/" => "$wpcom_root/wp-content/mu-plugins/jetpack-plugin/modules/sitemaps/",
```

**Comment by sdixon194** [comment]
There's an internal bot that shows when sitemaps goes down that could be worth using to make sure our changes are fine. Internal ref: pcOTDw-hN-p2

**Comment by samiff** [comment]
Update diff: D86605-code
Cleanup diff: D86614-code
Post-deploy de-fusion reminder: #25843

Testing:

* Apply both diffs to sandbox.
* You may need to `return true;` from the top of `is_using_wpcom_sitemaps()` in `.../mu-plugins/sitemaps.php` to see the correct files loaded.
* Try visiting your sandbox `/sitemap.xml` and check for any errors, and that the updated Jetpack plugin file path is being used.

**Comment by samiff** [comment]
Update changeset: r251407-wpcom
Clenaup changeset: r251409-wpcom
