### ISSUE TITLE
De-Fusion: Social Links

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25232]
### Impacted plugin

Jetpack

### What

Social Links

### How

```
"$plugin_root/modules/theme-tools/social-links.php" => "$wpcom_root/wp-content/mu-plugins/social-links/social-links.php",
```

**Comment by samiff** [comment]
Update diff: D87941-code

**Comment by coder-karen** [comment]
Looks like no active WPcom themes use this. I tested with a legacy theme that supports this (just learnt this can be done via the Blog RC) and it continued to work.

**Comment by samiff** [comment]
r253141-wpcom
