### ISSUE TITLE
De-Fusion: Upcoming Events iCalendar Reader (shortcode and widget)

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25244]
### Impacted plugin

Jetpack

### What

Upcoming Events iCalendar Reader

### How

```
"$plugin_root/_inc/lib/icalendar-reader.php" => "$wpcom_root/wp-content/lib/icalendar-reader.php",
```

**Comment by samiff** [comment]
Update diff: D87752-code
Jetpack file changes: #26223
Cleanup diff after JP file changes deploy to wpcom: D87753-code

Testing: test that the upcoming events widget code works without error.

```
[upcomingevents number=3 url="http://www.google.com/calendar/ical/ht3jlfaac5lfd6263ulfh4tql8%40group.calendar.google.com/public/basic.ics"]
```

**Comment by sdixon194** [comment]
Nice and simple

**Comment by samiff** [comment]
Update changeset: r253079-wpcom
Cleanup changeset: r253080-wpcom
