### ISSUE TITLE
De-Fusion: Twitter Cards

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25242]
### Impacted plugin

Jetpack

### What

Twitter Cards

### How

```
"$plugin_root/class.jetpack-twitter-cards.php" => "$wpcom_root/wp-content/blog-plugins/twitter-cards.php",
```

**Comment by samiff** [comment]
Update diff: D85676-code
Cleanup diff: D85679-code

**To Test:**

- Patch update diff to sandbox.
- Paste a link to a Tweet in a post and preview that on frontend.
- Tweet should render as expected, no errors on sandbox.

**Comment by samiff** [comment]
Update changeset: r250552-wpcom
Cleanup changeset: r250553-wpcom
