### ISSUE TITLE
De-Fusion: Tiled Galleries

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25240]
### Impacted plugin

Jetpack

### What

Tiled Galleries

### How

```
"$plugin_root/modules/tiled-gallery/tiled-gallery.php" => "$wpcom_root/wp-content/mu-plugins/tiled-gallery.php",
"$plugin_root/modules/tiled-gallery/math/"             => "$wpcom_root/wp-content/mu-plugins/math/",
"$plugin_root/modules/tiled-gallery/tiled-gallery/"    => "$wpcom_root/wp-content/mu-plugins/tiled-gallery/",
```

**Comment by coder-karen** [comment]
Calypso update PR: https://github.com/Automattic/wp-calypso/pull/68073
Update and cleanup diff: D88056-code (Calypso PR needs merging before this can be deployed).

---

**Testing instructions**

* Apply the above diff, and add a Tiled Gallery block on a WordPress.com site. You can also add an error log within the Jetpack plugin tiled-gallery.php file to confirm the Jetpack files are being viewed.
* The h4 theme functions.php file has also been edited -  this affects WordPress.com landing pages: PCYsg-gWr-p2. The one page I've found with Tiled Galleries that can be checked is https://wordpress.com/support/images/. To sandbox that page, you need to sandbox en.wordpress.com and wordpress.com.

**Comment by sdixon194** [comment]
This works for me, just waiting a Calypso review before merging. Asked here: p1664220732089789-slack-C02DQP0FP

But will go ahead and just merge if no one responds in a day.

**Comment by sdixon194** [comment]
Merged the calypso PR. Updated the diff based on some of Brad's feedback, could use another look before merging.

**Comment by sdixon194** [comment]
Defusion: r253552-wpcom
Cleanup: r253551-wpcom
