### ISSUE TITLE
De-Fusion: Top Posts

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25241]
### Impacted plugin

Jetpack

### What

Top Posts

### How

```
"$plugin_root/class.jetpack-post-images.php" => "$wpcom_root/wp-content/mu-plugins/post-images.php",
```

**Comment by samiff** [comment]
Update diff: D85681-code
Cleanup diff: D85682-code

To Test:

- Patch update diff to sandbox.
- Add error log to `jetpack-plugin/production/class.jetpack-post-images.php`
- Load frontend of site with posts and ensure the new file location is loading ok, no errors on sandbox.

**Comment by coder-karen** [comment]
Works well 👍

**Comment by samiff** [comment]
Update changeset: r250548-wpcom
Cleanup changeset: r250549-wpcom
