### ISSUE TITLE
De-Fusion: Markdown

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25246]
### Impacted plugin

Jetpack

### What

Markdown

### How

```
"$plugin_root/modules/markdown/easy-markdown.php" => "$wpcom_root/wp-content/plugins/easy-markdown/easy-markdown.php",
"$plugin_root/_inc/lib/markdown/"                 => "$wpcom_root/wp-content/lib/markdown/",
"$plugin_root/_inc/lib/markdown.php"              => "$wpcom_root/wp-content/lib/markdown.php",
```

**Comment by coder-karen** [comment]
For more on the process here: p1662732602494379-slack-C032DVAHMK3

- [x] Defusion diff: D87493-code ( done: r252475-wpcom )

- [x] First cleanup diff: D87506-code (done: r252478-wpcom )

Testing: 

- To test, apply the first diff and add the changes from the second (or vice versa). On a WordPress.com site (sandboxed), create a new post draft. In a paragraph block, type '### ' with the space and it should convert to a H3 heading.
- You can also add an error log somewhere in jetpack-plugin/production/modules/markdown/easy-markdown.php to confirm that the error log is being seen.
- Note that one changed file affects easy markdown in all a8C 'o2s'. So if you can sandbox an A8C P2, test that you still use easy markdown following the steps above.

-----

### After the above defusioning: 

- [x] Update PR (updating jetpack-plugin files using jetpack_require_lib to load via JETPACK__PLUGIN_DIR): https://github.com/Automattic/jetpack/pull/26147

Repeat testing first (after applying this PR).
If all tests well, then merge.


-----

### Once the Weekly to WPcom has shipped after the above PR is merged:

(During the week of the 19th Sep)

- [ ] Second cleanup diff: D87494-code

Repeat testing first (after applying this diff).

### After everything: 

- [x] https://github.com/Automattic/jetpack/pull/26142

**Comment by samiff** [comment]
Looks good 👍

**Comment by anomiex** [comment]
Current status: waiting on the weekly release before D87494-code can be done.

**Comment by coder-karen** [comment]
Diff now updated - awaiting follow-up in a comment then it should be ok to merge.

Marking the issue as needs review so that it isn't left if I am unable to follow-up before AFK.

**Comment by sdixon194** [comment]
> Current status: waiting on the weekly release before D87494-code can be done.

Deployed in r253306-wpcom

Marking this one as done since I believe all of the things have been addressed
