### ISSUE TITLE
De-Fusion: Widget Visibility

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25245]
### Impacted plugin

Jetpack

### What

Widget Visibility

### How

```
"$plugin_root/modules/widget-visibility/widget-conditions.php" => "$wpcom_root/wp-content/mu-plugins/widget-conditions.php",
"$plugin_root/modules/widget-visibility/widget-conditions/"    => "$wpcom_root/wp-content/mu-plugins/widget-conditions/",
"$plugin_root/modules/widget-visibility/editor/"               => "$wpcom_root/wp-content/mu-plugins/jetpack/modules/widget-visibility/editor/",
```

**Comment by samiff** [comment]
Update diff: D85327-code
Cleanup diff: D85330-code

**To test:**

- Apply both patches to sandbox.
- Use the widget visibility settings from the block editor and make sure everything still works and their are no errors.

**Comment by sdixon194** [comment]
Tried with multiple themes, block widget editor in wp-admin and customizer, and jetpack search sidebar, multiple conditions, etc. Everything seems to work perfectly fine 👍

**Comment by samiff** [comment]
Update changeset: r250140-wpcom
Cleanup changeset: r250141-wpcom

**Comment by samiff** [comment]
Reopening to investigate some internal reports:

* p1660001585483459-slack-CDLH4C1UZ
* p1660150129712209-slack-C032DVAHMK3

**Comment by samiff** [comment]
Additional cleanup diff: D85770-code

To Test:

- Apply patch to sandbox.
- Open widget editor and add a legacy widget (e.g. Authors).
- Make sure you are able to see and control the `Visibility` setting for the widget.
- Check for any PHP/JS errors.

<img width="787" alt="Screen Shot 2022-08-10 at 12 48 32 PM" src="https://user-images.githubusercontent.com/15803018/183993249-b34e455a-c4d8-4b84-b7b6-730718f8362e.png">

**Comment by samiff** [comment]
r250488-wpcom
