### ISSUE TITLE
De-Fusion: VideoPress

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25248]
### Impacted plugin

Jetpack

### What

VideoPress

### How

```
"$plugin_root/modules/videopress/class.videopress-gutenberg.php"           => "$wpcom_root/wp-content/mu-plugins/videopress/class.videopress-gutenberg.php",
"$plugin_root/modules/videopress/js/"                                      => "$wpcom_root/wp-content/mu-plugins/videopress/js/",
"$plugin_root/modules/videopress/class-videopress-attachment-metadata.php" => "$wpcom_root/wp-content/mu-plugins/videopress/class-videopress-attachment-metadata.php",
```

**Comment by sdixon194** [comment]
Update diff: D86327-code
Cleanup diff: D86329-code

Would appreciate a second pair of eyes on this one. VideoPress seems to be in a weird state where a lot of the work is duplicated on dotcom, but the files aren't fusioned. I can't really delete most of the things in `mu-plugins/videopress` without breaking a lot of other things.

For this defusioning, I just picked the two synced files and the js files and kept it simple. cc @leogermani  in case you want to have a bigger discussion about how to have wpcom run VideoPress directly, specifically from the new package, instead of however it's intwined with dotcom now.

**Comment by coder-karen** [comment]
Giving this a test just now, I notice the functionality in WPcom didn't seem quite right (video upload wouldn't finish for example), and I was noticing warnings when tailing errors. The warnings seemed to be related to the two files that are now being loaded via Jetpack, but the warning is for get.php and put.php within mu-plugins/videopress.php. The console was spitting out 404 GET errors as well.

**Comment by sdixon194** [comment]
Hmm strange I didn't see those but will check again - out of curiosity, did you cherry pick both diffs to the testing branch, or were you just testing the Update diff?

**Comment by leogermani** [comment]
The files listed in the PR description were not moved out from the Jetpack plugin into the package.

Just one file from the js folder were. This one -> https://github.com/Automattic/jetpack/blob/trunk/projects/packages/videopress/src/client/lib/videopress-token-bridge.js#L1

So I'm not sure anything should be done to them...

Now that I'm aware of the process, I'm trying to keep a close look at what's been loaded from the package and making sure it will play nicely in WPCOM...

Not sure what's going on here

**Comment by leogermani** [comment]
> VideoPress seems to be in a weird state where a lot of the work is duplicated on dotcom, but the files aren't fusioned. 

Not everything will be migrated to the package. Many things will remain in the Jetpack plugin module as they are now.

**Comment by coder-karen** [comment]
>  did you cherry pick both diffs to the testing branch, or were you just testing the Update diff?

I applied the cleanup diff then manually added the changes in the update diff. I'm not getting them now though, possibly the tail was picking up the period between me applying one diff and the other. The video upload still doesn't seem to want to finish though for some reason in one instance, though on another it does. So possibly not related here.

**Comment by sdixon194** [comment]
Looks like that video works for me - not sure if there's any kind of flakiness with VP in general. 

> The files listed in the PR description were not moved out from the Jetpack plugin into the package.

That's probably okay, this is just defusioning files that are synced between dotcom and Jetpack, which are the files listed at the top. 

> So I'm not sure anything should be done to them...

Yup, I've updated the paths in `wp-content/mu-plugins/videopress.php` to call from the package in `mu-plugins/jetpack-plugin/production` instead. 

I think this might have been a simpler defusion than anticipated, and I suppose there's a broader discussion to be had on if VideoPress needs to be restructured on dotcom (I'm not too sure about rest of the files in `mu-plugins/videopress` are doing, for example).

**Comment by coder-karen** [comment]
From my testing then this looks good to go, unless we're looking for additional clarity on anything else.

**Comment by sdixon194** [comment]
I think we might be okay, I'll wait until monday to deploy so we have a whole week to catch anything and in case any VideoPress folks want to do some testing to catch any flows we might have missed.

**Comment by samiff** [comment]
> I think we might be okay, I'll wait until monday to deploy

@sdixon194 Still planning on giving this a shot this week?

**Comment by sdixon194** [comment]
Oh yeah thanks for the reminder. It's getting kinda late my time. I'll do it first thing tomorrow.

**Comment by sdixon194** [comment]
Defusion: r251786-wpcom
Cleanup: r251790-wpcom
github PR: https://github.com/Automattic/jetpack/pull/25990
