### ISSUE TITLE
De-Fusion: Twitter Thread Unrolling and Publishing

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25243]
### Impacted plugin

Jetpack

### What

Twitter Thread Unrolling and Publishing

### How

```
"$plugin_root/_inc/lib/class-jetpack-tweetstorm-helper.php" => "$wpcom_root/wp-content/lib/class-jetpack-tweetstorm-helper.php",
```

**Comment by samiff** [comment]
- [x] Update diff: D87076-code
- [x] JP PR (wait for this to deploy to wpcom before cleanup diff): #26002
- [ ] Cleanup diff: D87078-code

**Comment by samiff** [comment]
Stub replace for the lib file: r252240-wpcom
Still working on D87075-code - internal: p1662674234089059-slack-C032DVAHMK3

**Comment by samiff** [comment]
Ran into some trouble landing the cleanup diff; but same publicize test are failing on trunk, internal: p1663878859899209-slack-C032DVAHMK3 

Edit: still having some trouble landing, p1665597598038269-slack-C032DVAHMK3

**Comment by samiff** [comment]
r254300-wpcom
