### ISSUE TITLE
De-Fusion: Widgets

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25253]
### Impacted plugin

Jetpack

### What

Widgets

### How

```
"$plugin_root/modules/widgets/$widget" => "$wpcom_root/wp-content/mu-plugins/widgets/$widget";
```

Widgets:

```
	'class-jetpack-instagram-widget.php',
	'customizer-utils.js', // This isn't a widget, but is a utility that other widgets use.
	'facebook-likebox.php',
	'goodreads.php',
	'google-translate/',
	'google-translate.php',
	'gravatar-profile.php',
	'gravatar-profile.css',
	'milestone/',
	'simple-payments/',
	'simple-payments.php',
	'social-icons.php',
	'social-media-icons/',
	'social-media-icons.php',
	'top-posts.php',
	'top-posts/style.css',
	'twitter-timeline.php',
	'upcoming-events.php',
	'wordpress-post-widget/class.jetpack-display-posts-widget-base.php',
	'wordpress-post-widget/style.css',
```

**Comment by samiff** [comment]
Update diff: D85583-code
Cleanup diff: D85590-code

**To Test:**
* Apply _both_ diffs to sandbox (I checkout both, then just merge one onto the other for testing).
* Try testing a few of the modified widgets to make sure things work ok and no errors are generated.
* Maybe try an error log in one of the jetpack-plugin widget files to verify correct path is being loaded.

**Comment by coder-karen** [comment]
I did pick up on one issue so far in testing: the Google Translate widget didn't work with both diffs applied, but does work without them.
In the console in the widget editor screen (using Twenty Twenty), there was an error showing (when sandboxed and the diffs applied): `GET examplesiteaddress.com/wp-content/mu-plugins/widgets/google-translate/google-translate.js?ver=wpcom net::ERR_ABORTED 404`. The widget does show and you can add a title, but that is all. An error log is the jetpack plugin main google translate php file does indicate that that file is loading.

Moving across to Twenty Nineteen it still didn't work, though the console error was now `google-translate.js?ver=wpcom:9 Uncaught ReferenceError: module is not defined at google-translate.js?ver=wpcom:9:1`. With all of these I was testing with Chrome.

**Comment by samiff** [comment]
@coder-karen Thanks for testing, I've updated the cleanup diff, similar to what was needed in: https://github.com/Automattic/jetpack/issues/25245#issuecomment-1211123807

I'm no longer seeing the 404 on the JS file. Whenever you get a chance could you have another look, thanks!

**Comment by coder-karen** [comment]
Looks good! Well, for the widgets I was able to test with anyway, which was all but the Instagram widget, social media icons (social icons is fine), and Twitter timeline. They don't appear by default - it looks like they've been hidden.

However the widget visibility wasn't working, though a rebase fixed that. I notice there are other failing tests in D85590-code though - left a comment over there.

**Comment by sdixon194** [comment]
I also see:

> PHP Fatal error:  require_once(): Failed opening required '/home/teamcity-2/buildAgent/work/work_build-C03-R25-12-dfw-2_git/trunk/wp-content/mu-plugins/widgets/top-posts.php'

On that failing diff, so I think we may have to merge the first one, rebase, and re-run the tests.

**Comment by samiff** [comment]
Update changeset: r250550-wpcom
Cleanup changeset: r250551-wpcom

**Comment by samiff** [comment]
I messed up the `widgets/customizer-utils.js` path in D85583-code

Fixed in D85905-code / r250629-wpcom
