### ISSUE TITLE
De-Fusion: Currencies lib

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25250]
### Impacted plugin

Jetpack

### What

Currencies Lib

### How

```
$plugin_root/_inc/lib/class-jetpack-currencies.php" => "$wpcom_root/wp-content/lib/class-jetpack-currencies.php",
```

**Comment by samiff** [comment]
Update diff: D87748-code
Jetpack file changes: #26222
Cleanup diff after JP file changes deploy to wpcom: D87749-code

Testing: ensure simple payments & donations block continue to work after changes.

**Comment by sdixon194** [comment]
Works form me!

**Comment by samiff** [comment]
Update changeset: r253076-wpcom
Cleanup changeset: r253078-wpcom
