### ISSUE TITLE
De-Fusion: Endpoints A - E

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25255]
### Impacted plugin

Jetpack

### What

API Endpoints

### How

```
"$plugin_root/json-endpoints/$endpoint" => "$wpcom_root/public.api/rest/json-endpoints/$endpoint";
```

The Endpoints:

```
	"class.wpcom-json-api-autosave-post-v1-1-endpoint.php",
	"class.wpcom-json-api-bulk-delete-post-endpoint.php",
	"class.wpcom-json-api-comment-endpoint.php",
	"class.wpcom-json-api-delete-media-endpoint.php",
	"class.wpcom-json-api-delete-media-v1-1-endpoint.php",
	"class.wpcom-json-api-edit-media-v1-2-endpoint.php",
```

**Comment by sdixon194** [comment]
Everything in sync!

**Comment by anomiex** [comment]
> projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-autosave-post-v1-1-endpoint.php

Confirmed, just phpcs stuff. Specifically, D58564-code.

> projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-edit-media-v1-2-endpoint.php

This _should_ be ok. The wpcom version uses a much older version of [_inc/lib/class.media.php](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/_inc/lib/class.media.php), although it looks like there haven't been any breaking changes between that and the version now in Jetpack.

We might turn `wp-content/lib/class.media.php` into a stub along the lines of
```php
require_once JETPACK__PLUGIN_DIR . '/_inc/lib/class.media.php';
class_alias( 'Jetpack_Media', 'Media' );
```
to make sure the rest of wpcom is on the same page with things.

**Comment by anomiex** [comment]
Landed D58564-code, so class.wpcom-json-api-autosave-post-v1-1-endpoint.php is in sync now.

**Comment by anomiex** [comment]
Syncing Media endpoints is D90466-code and D90467-code.

**Comment by sdixon194** [comment]
Looks like the second diff is actually D90468-code. Can't approve that one, I'm assuming because of the failing build, which I'm assuming is contingent on D90466-code, but both worked for me 👍

**Comment by anomiex** [comment]
Yeah, it won't let you approve if there are failing tests.

**Comment by anomiex** [comment]
Everything here is in sync now.

**Comment by sdixon194** [comment]
Updated comment 👍 Ready for defusioning next week.

**Comment by sdixon194** [comment]
One diff with the stubs: D90744-code

**Comment by anomiex** [comment]
FYI: Looks like there are three endpoints in this group that aren't Fusioned but exist in both.

* `class.wpcom-json-api-add-widget-endpoint.php`: Other than phpcs stuff, it's desynced in that D12352-code for some reason included a declaration of a bulk endpoint that was never on the Jetpack side (but was apparently supported in the code 🤷), and there's a situation with a "widgets" lib similar to the "media" one.
* `class.wpcom-json-api-bulk-restore-post-endpoint.php`: Just phpcs stuff.
* `class.wpcom-json-api-bulk-update-comments-endpoint.php`: Just phpcs stuff.

**Comment by sdixon194** [comment]
Updated the diff with the latter two. 

>  declaration of a bulk endpoint that was never on the Jetpack side (but was apparently supported in the code 🤷)

Should we add this to Jetpack and make sure it gets deployed first before defusioning this one? 

> and there's a situation with a "widgets" lib similar to the "media" one.

What's exactly this issue?

**Comment by anomiex** [comment]
> Should we add this to Jetpack and make sure it gets deployed first before defusioning this one?

Probably, since it's there.

> What's exactly this issue?

There's `wp-content/lib/widgets/widgets.php` on wpcom defining a class named "Widgets", and `projects/plugins/jetpack/_inc/lib/widgets.php` in Jetpack defining a class named "Jetpack_Widgets". The Jetpack version seems to have started out as a copy of the wpcom version and gotten some updates since, while the wpcom version hasn't been touched.

We could probably do like D90466-code did to `wp-content/lib/class.media.php` if we want, then maybe do like D90468-code too.

**Comment by sdixon194** [comment]
> We could probably do like D90466-code did to wp-content/lib/class.media.php if we want, then maybe do like D90468-code too.

This works for me. Do we need to wait for https://github.com/Automattic/jetpack/pull/27094 to land before we do that since I see that referenced there?

**Comment by anomiex** [comment]
Kind of a tricky question. There are two ways we could go:

1. Wait for #27094 to land and be weekly-released so the Jetpack code doesn't go through `jetpack_require_lib()`, then de-Fusion the endpoint without worrying about `wp-content/lib/widgets/widgets.php`.
2. "De-Fusion" `wp-content/lib/widgets/widgets.php` as was done for "class.media", then de-Fusion the endpoint without worrying about the `jetpack_require_lib()` because it'll get the same code either way.

**Comment by sdixon194** [comment]
> to land and be weekly-released so the Jetpack code doesn't go through jetpack_require_lib(), then de-Fusion the endpoint without worrying about wp-content/lib/widgets/widgets.php.

Since the PR is already up and the next weekly is fairly soon, sounds like this might be the cleanest approach. I'll make sure to try and review that PR as best I can today and get it merged so we can get some more testing this cycle. Then the endpoint can be defusioned as part of this diff and I can just land it after the next weekly.

**Comment by sdixon194** [comment]
Updated the last endpoint, gonna wait and land this until after 11.6-a.1 lands on Atomic p9o2xV-2yg-p2

**Comment by sdixon194** [comment]
Deployed in r255822-wpcom
