### ISSUE TITLE
De-Fusion: Divergent Files

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#25251]
### Impacted plugin

Jetpack

### What

Divergent Files

### How

```
// This file should only exist on Dotcom but is within a directory which exists within Jetpack.
// Until we have a better solution for ignoring particular files, we add it here to avoid,
// any attempt to sync it from Jetpack (where it doesn't exist) to Dotcom.
"$plugin_root/modules/masterbar/admin-color-schemes/class-admin-color-schemes-sync.php",
```

**Comment by anomiex** [comment]
Nothing to do here, as far as I can tell. The array this entry is in is for the scripts that make a GitHub PR from a wpcom diff, telling them to ignore this file because it's not in Jetpack.

**Comment by anomiex** [comment]
This wound up getting removed in D88504-code.
