### ISSUE TITLE
Cannot upgrade to Boost Premium on AT

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#25293]
### Impacted plugin

Boost

### Steps to Reproduce

- Create an AT site
- Enable Critical CSS Module
- Click the upgrade prompt and follow the flow

### A clear and concise description of what you expected to happen.

Users should be able to upgrade, as boost-cloud is able to generate for Atomic.

### What actually happened

It fails with a message saying the item is not compatible with WP.com.

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by i11za** [comment]
User report: 5427490-zd-woothemes 

Letting them know this is a known issue, and that we're working on it, but there's no ETA.

**Comment by ariel-maidana** [comment]
Please notify the user in 5427490-zd-woothemes when the issue is fixed.

**Comment by haqadn** [comment]
@ariel-maidana The issue is fixed now: pc9hqz-1sd-p2. I don't know what is the process of notifying on a closed ticket. Will you please take care of notifying/pointing me in the right direction?

**Comment by ariel-maidana** [comment]
Thank you @eAdnan007 ! I'll notify the user.

**Comment by ariel-maidana** [comment]
I notified the user.

**Comment by haqadn** [comment]
Thanks @ariel-maidana! I am closing the issue now.
