### ISSUE TITLE
Like count aka "Star" column styles are broken in 4.3

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#2532]
We were using the comment styles in the list table view for the “Star” column. e.g., `wp-admin/edit.php, which has changed in 4.3, thus breaking the styles like so: 

![screen shot 2015-08-12 at 11 55 22 am](https://cloud.githubusercontent.com/assets/7129409/9228995/0b8e213e-40e9-11e5-8de5-86943455c0aa.png)

**Comment by obenland** [comment]
Removing the `comment-count` class should fix it. Might break back compat thought.

**Comment by dereksmart** [comment]
#2563
