### ISSUE TITLE
Subscription block: customize appearance of confirmation messages in the block editor

### ISSUE THREAD

**Issue by jffng** [Automattic/jetpack#25330]
### Impacted plugin

Jetpack

### What

It would be useful to be able to customize the appearance of the form's confirmation message via the editor

### How

Currently when a user subscribes, the block renders a notification with [some inline styles](https://github.com/Automattic/jetpack/blob/83cc5ec097251a017cd60ba4deff67f3e24b2081/projects/plugins/jetpack/modules/subscriptions/views.php#L304).  This doesn't look great for many themes / layouts: 

![image](https://user-images.githubusercontent.com/5375500/181768314-ac78bbc0-23c6-4e94-80ee-1ba3dd68b21b.png)

If it requires a lot of work to add the ability for the user to change the color and border of this message, a first step could be just removing those inline styles.

**Comment by retrofox** [comment]
> If it requires a lot of work to add the ability for the user to change the color and border of this message, a first step could be just removing those inline styles.

💯

**Comment by retrofox** [comment]
just FYI, these styles are only applied to Simple sites if I'm not wrong.
