### ISSUE TITLE
Sharing: Buttons can't be placed in BuddyPress member-header.php

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#2533]
When trying to place the sharing function in this template part, the buttons are not loaded. The code seems to be in place, but no buttons actually appear:

![screen shot on 2015-08-12 at 13_41_02](https://cloud.githubusercontent.com/assets/831377/9231760/ea577182-40f7-11e5-9a2a-109839dcec52.png)

**Comment by chaselivingston** [comment]
Update: Buttons do appear, but just load a new window with the same page instead of the sharing box.

**Comment by kraftbj** [comment]
@chaselivingston Can you provide any console errors? That sounds like JS is failing. Did you try default theme with only JP and BP installed?

**Comment by jeherve** [comment]
@chaselivingston Did you have the chance to look into this?

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
