### ISSUE TITLE
User meta cache being purged on every wp-admin request

### ISSUE THREAD

**Issue by david-binda** [Automattic/jetpack#25332]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Make sure some persistent cache storage is enabled in your test environment (eg.: memcache)
2. Have Gutenberg the plugin installed
3. Go to /wp-admin screen while having some plugin showing the SQL queries enabled (debug bar, query monitor)
4. Notice that there is a SQL query collecting all user meta during the screen load
5. Go to some other wp-admin screen and notice the SQL query for fetching all user meta is still present

### A clear and concise description of what you expected to happen.

All user meta should be properly cached, and the related SQL query should only happen once and stay cached till the user meta are not changed. Those should only be changed when necessary.

### What actually happened

Jetpack, via the [sync_sidebar_collapsed_state](https://github.com/Automattic/jetpack/blame/b82dce6b08932eae8b31eede5aa8b77b22edc36b/projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php#L435) function unnecessarily updates the user settings on every admin screen load, as it's not checking the currently stored value for the `mfold` setting.

WordPress updates the settings timestap (sets it to a value returned by the `time()` function ) along with each setting set, thus makes the value of the user meta different, which leads to database being updated, as well as user meta cache being purged.

### Other information

Related to https://github.com/Automattic/wp-calypso/issues/66063

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

All

**Comment by jeherve** [comment]
Previous work on this: #19520
