### ISSUE TITLE
Enhancement: Disable instant search when client prefers reduced motion

### ISSUE THREAD

**Issue by sarayourfriend** [Automattic/jetpack#25348]
### Impacted plugin

Search

### What

Disable instance search when client prefers reduced motion. Instant search is extremely disorienting as it moves the text box if you pause to think about your query for even a moment.

### How

Check `window.matchMedia('(prefers-reduced-motion)').matches` and disable instant search when it is true, even if the plugin has instant search disabled.

**Comment by bluefuton** [comment]
Thanks for raising this @sarayourfriend. 

Is it the opening of the modal that is the primary cause of disorientation?

We currently have a PR in the works (https://github.com/Automattic/jetpack/pull/25093) to make 'submit' the default overlay trigger, so you would need to hit Enter or click the submit button before the modal opens. There would be no modal opening during typing or when you pause. 

We could potentially extend this so that users with `prefers-reduced-motion` always get this behavior regardless of what's set in the site configuration.

**Comment by sarayourfriend** [comment]
> Is it the opening of the modal that is the primary cause of disorientation?

The modal opening while you're still typing the query, yes. If the modal waited to open until the user intentionally submits the query then it would solve the problem, at least for me.

The change you've described would solve my problem, but I think this part is critical to me:

> We could potentially extend this so that users with prefers-reduced-motion always get this behavior regardless of what's set in the site configuration.

I interact with dozens of individual WP sites with Jetpack installations and having to request the change on all of them so that searching is comfortable would be frustrating and demoralizing. If a client prefers reduced motion it's a good bet they don't want the box they're typing into to suddenly move out from under them if they pause for a moment while typing.

**Comment by a8ck3n** [comment]
> We could potentially extend this so that users with prefers-reduced-motion always get this behavior regardless of what's set in the site configuration.

This sounds like a really smart improvement. It's fine for the site owner to set their preference but even better if we can cater to the site visitors too.

**Comment by bluefuton** [comment]
Just noting that we shipped the PR to make 'submit' the default overlay trigger today (https://github.com/Automattic/jetpack/pull/25093).

> This sounds like a really smart improvement. It's fine for the site owner to set their preference but even better if we can cater to the site visitors too.

I concur 👍  I've added this issue to our Accessibility project board.
