### ISSUE TITLE
Jetpack + qTranslate-X -> Related post titles are incorrectly shown in multiple languages

### ISSUE THREAD

**Issue by DavideViolante** [Automattic/jetpack#2535]
File: jetpack/modules/related-posts/jetpack-related-posts.php
Function: _get_title

I found a fix on the web: http://miklasnjor.com/2015/jetpack-related-posts-qtranslate-x-fix/
Replace the line:

``` php
return wp_strip_all_tags( $post_title );
```

with:

``` php
return wp_strip_all_tags(__($post_title));
```

and it will shows the correct title depending on the language.

I don't know if this is a "good" fix, I just wanted to report it.

**Comment by jeherve** [comment]
> I don't know if this is a "good" fix

I'm afraid that is not a good fix, as variables cannot be used in translation functions (`__()` in  your example). You cannot translate a variable ([reference](https://codex.wordpress.org/I18n_for_WordPress_Developers#Placeholders)).

There is probably another way to fix this problem, but I'd like to get the opinion of the qTranslate-X plugin author, @johnclause, on that.

@johnclause In [the plugin's FAQ page](https://qtranslatexteam.wordpress.com/faq/), I see something that I think may help us here:

> However, sometimes, they pass a value through `apply_filters()` function before displaying the value, and then you may put that filter name into configuration filed “Custom Filters” to get the value translated properly.

If we were to wrap that variable in a filter, would that help you translate?

**Comment by johnclause** [comment]
>If we were to wrap that variable in a filter, would that help you translate?

Yes, filter wrap would be ok.

@DavideViolante: please, confirm that this is still a problem with the latest QTX, since many things are changed and maybe this problem went away by other meaning? It would be nice to have a reproducing sequence of steps for the original problem here, preferably using one of the standard themes, like "Twenty Fifteen" and the minimum of active plugins.

**Comment by DavideViolante** [comment]
Same as before also with Twenty Fifteen theme and latest Jetpack and QTX. There are no special steps to reproduce, just Jetpack related posts feature + QTX plugin and the titles in related posts are shown in all languages together.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/related-posts-with-qtranslate-x-plugin?replies=1&view=all

**Comment by davoraltman** [comment]
Also reported in 2633195-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/related-posts-does-interfere-with-multilanguage-sites/

**Comment by alexjgustafson** [comment]
2924830-t

**Comment by mikecastrodemaria** [comment]
Same problem here, any news about this ?

**Comment by osarusan82** [comment]
Has any progress been made on this? It sounds like a potential solution might have been found by @johnclause and @jeherve but so far the only solution proposed has been to manually edit the plugin files for Jetpack... which isn't ideal as they will be overwritten with each update.

**Comment by jeherve** [comment]
We have no update yet, but we would welcome any community contribution to solve this issue. We'll be happy to review any patch that would solve the problem without inserting variables inside translation functions as tested in the OP.

Thank you!

**Comment by osarusan82** [comment]
Thanks for the reply! I wish I could help out :( sadly it's about my skill level.

**Comment by tuncbz** [comment]
This solution doesn't work on some themes and last jetpack version.

But it's work:
https://www.reddit.com/r/Wordpress/comments/6hkxc5/wordpress_related_post_titles_are_shown_in_all/

**Comment by StefMattana** [comment]
Another report here: [](https://wordpress.org/support/topic/related-post-function-problem-with-qtranslate-x-plugin/)

**Comment by davidjbrossard** [comment]
It's been over a year. I also have the issue on https://www.delscookingtwist.com/2018/06/27/15-fun-ways-to-use-chickpeas/ Any fix in the future? Thanks

**Comment by shapito27** [comment]
hello, it still doesn't work =(

**Comment by jeherve** [comment]
If anyone is still using qTranslate-X and has this issue, could you try applying the change in #20637 to your own site, and see if that fixes the problem?

Thank you!
