### ISSUE TITLE
Payment Button block: Quotation marks cause display issues

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/jetpack#25371]
### Quick summary

Including quotation marks in Payment Button block text causes display issues on the live site. The text displays correctly in the editor. 

### Steps to reproduce

1. Add a Payment Button block to a site that has a connected Stripe account.
2. Add button text that includes quotation marks, for example: buy "now"
3. Check preview or published page.

### What you expected to happen

The button would display correctly in the live site and preview as it does in the editor. 

### What actually happened

The button displays as several small rectangles.

Screenshot of editor:
<img width="672" alt="appearance in editor" src="https://user-images.githubusercontent.com/30788962/170846325-6e62b35d-24e9-4de0-9de0-02b70a40f911.png">

Screenshot of live site: 
<img width="751" alt="appearance on live site" src="https://user-images.githubusercontent.com/30788962/170846324-d510d65d-9932-4957-9af1-1150055a2252.png">

### Context

User report: 5249717-zd-woothemes

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

As a workaround, remove quotation marks from button text and button will display correctly.

**Comment by dsas** [comment]
I can't reproduce this at all. I've tried on simple and on atomic sites.

On my atomic site, I installed the Tortuga theme from dotorg and it still made no difference.

My test post has this content:
```html
<!-- wp:paragraph -->
<p>Here is some content before the button</p>
<!-- /wp:paragraph -->

<!-- wp:jetpack/recurring-payments {"planId":20,"url":"https://deanprotest3.wpcomstaging.com/2022/08/03/quote-buttons/?recurring_payments=20","uniqueId":"recurring-payments-20"} -->
<div class="wp-block-jetpack-recurring-payments"><!-- wp:jetpack/button {"element":"a","uniqueId":"recurring-payments-20","passthroughAttributes":{"uniqueId":"uniqueId","url":"url"},"text":"this \u0022in quotes\u0022 test","url":"https://deanprotest3.wpcomstaging.com/2022/08/03/quote-buttons/?recurring_payments=20","className":"is-style-fill"} /--></div>
<!-- /wp:jetpack/recurring-payments -->

<!-- wp:paragraph -->
<p>Here is some content after the button</p>
<!-- /wp:paragraph -->
```

@galakhyati, can you provide your post content or invite me to a test site to take a look?

**Comment by dsas** [comment]
A " character will be converted to a “ by WordPress at display time 🤔 .

**Comment by dsas** [comment]
@galakhyati, @jamiepalatnik: Any further clues on reproducing this?

**Comment by jamiepalatnik** [comment]
I checked again but I can no longer reproduce this issue, so I'll go ahead and close for now. The issue can be reopened if anyone is able to reproduce. Thanks for taking a look @dsas!
