### ISSUE TITLE
VideoPress - Mobile screen recordings alignment issues

### ISSUE THREAD

**Issue by sarangsss29** [Automattic/jetpack#25374]
### Impacted plugin

Jetpack

### Steps to Reproduce

VideoPress: Smartphone screen recordings don't align properly, takes up the whole page - Jetpack video or videopress 
I sometimes use the Jetpack Video or VideoPress block in the post editor. I mostly use the mobile screen recordings because my site is tech-based and I mostly have mobile recordings.
Screenshot:
https://i.postimg.cc/qBt4Syz8/Video-Press-test-Google-Chrome-01.jpg
Live Example:
https://www.androidsage.com/2022/03/11/download-green-iphone-13-live-wallpapers-in-highest-resolution/

Scroll to the bottom of the article.

Also, what is the difference between Jetpack Video block and VideoPress?
In the changelog you always mention VideoPress. But in the Gutenberg  Editor, there is no mention of VideoPress. Only Video. Is it the same feature?

### Reproducibility

Consistent

**Comment by sarverse** [comment]
The video's height is way too big! You can't watch the complete video on the screen. You only see like 50% of the video height.
Here is a video. You will get the idea.
https://www.loom.com/share/5911c9fb342d4abe948bf37e51b6e1b7

**Comment by jeherve** [comment]
Thank you for the feedback, we'll take a look!

> what is the difference between Jetpack Video block and VideoPress?
> In the changelog you always mention VideoPress. But in the Gutenberg Editor, there is no mention of VideoPress. Only Video. Is it the same feature?

Jetpack's Video Block allows you to upload videos to the VideoPress service. So the 2 things are indeed linked! We're currently working on some changes to the feature and the different blocks, so things should get clearer in the next few months.

**Comment by thedebian** [comment]
In the block editor, you can resize the video by dragging the handles on both sides.
It should allow you to make your video's height smaller, while keeping the aspect ratio.
I did not see any integrated VideoPress player on the page you mentioned, so I guess you removed it.

**Comment by thedebian** [comment]
Is it still something we need to look into ?

**Comment by thedebian** [comment]
Closing for now, as no further answers were provided.
Feel free to reopen if the issue still exists.
