### ISSUE TITLE
Allow more than one contact form per page

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#254]
If you try to add a second contact form per page using the TinyMCE button, you can't, you can only edit the 1st form. 

If you manually add a new form using the shortcodes, the 2nd one will not appear in the published post if it is different from the first form. If you duplicate the 1st form in the same post, it WILL appear twice, but with the same ID for the form div.

It could be useful to allow more than 1 form per page/post.

Ported from https://plugins.trac.wordpress.org/ticket/1779

**Comment by RCowles** [comment]
Requested here:
https://wordpress.org/support/topic/2-contact-forms-in-the-same-page

**Comment by mikeyarce** [comment]
Requested here:
2191076-t

**Comment by jeherve** [comment]
Also requested here:
https://wordpress.org/support/topic/can-not-use-but-one-time-sucks?replies=1&view=all#post-

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/contact-form-bugs-after-update

**Comment by richardmtl** [comment]
Requested in 2487775-t

**Comment by kymcarlsson** [comment]
Also requested here :)
https://github.com/Automattic/jetpack/issues/254

**Comment by jeherve** [comment]
@kymcarlsson You just linked to this very issue. Did you mean to include a different link?
