### ISSUE TITLE
Multisite: Bulk Connect throws Warning

### ISSUE THREAD

**Issue by bswatson** [Automattic/jetpack#2540]
When attempting to connect sites in a Multisite environment using the bulk actions, a warning is thrown and only one site is connected.

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wordpress/site/wp-includes/formatting.php:4317) in /var/www/html/site/umaine/wp-includes/pluggable.php on line 1196

Full Screenshot of error: http://cl.ly/image/0s2R1G1a1o2i

**Comment by kraftbj** [comment]
I couldn't duplicate this on my multisite. Are you running any other plugins network activated?

**Comment by brocheafoin** [comment]
I'm not the reporter, but I'm experiencing the same issue. Turned off all network-activated plugins, as well as mu-plugins and sunrise.php and I'm still seeing it. Here's the warning:

> Warning:  Cannot modify header information - headers already sent by (output started at /srv/www/phare.desaulniers-simard.com/releases/20150828134914/web/wp/wp-admin/includes/template.php:1981) in /srv/www/phare.desaulniers-simard.com/releases/20150828134914/web/app/plugins/jetpack/class.jetpack.php on line 4956

There is a _setcookie()_ on line 4956, which I suspect is the culprit. Of note: if you use the bulk tool to connect only one site, everything works. It's as soon as you want to connect more than one that the warning appears and subsequent PHP execution is halted.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/multisite-403-on-connecting-to-wpcom

**Comment by jeherve** [comment]
This should be fixed by #3772.

Don't hesitate to let us know if this keeps happening once you've updated to Jetpack 4.0.4, scheduled to be released next week.
