### ISSUE TITLE
Emojis in code editor render broke image icon

### ISSUE THREAD

**Issue by wpgaurav** [Automattic/jetpack#25427]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Have Jetpack activated
2. Go to Theme Editor or any code editor in the backend.
3. Insert an emoji
![k1jwMgLVTt5TFhoRennSP0e3wVnfSVmpPtrm6j9k](https://user-images.githubusercontent.com/3599257/183790030-e89bc914-19c6-4239-804d-5b6088443d36.jpeg)

Possible cause: Jetpack is loading twemoji script from twemoji.maxcdn.com

### A clear and concise description of what you expected to happen.

Broken image icon shouldn't appear

### What actually happened

I cannot edit the "infected" line properly.

### Browser

Google Chrome/Chromium, Mozilla Firefox, Microsoft Edge, Apple Safari

### Reproducibility

Consistent

### Severity

All

**Comment by jeherve** [comment]
> Possible cause: Jetpack is loading twemoji script from twemoji.maxcdn.com

I don't believe this is done by Jetpack. I would recommend that you check the other plugins on your site, or reach out to your hosting provider about this; they're most likely to be the ones making use of a third-party CDN provider (MaxCDN). Jetpack includes its own image CDN, so we do not rely on MaxCDN anywhere.

**Comment by wpgaurav** [comment]
Oh okay. Must be some other plugin.
