### ISSUE TITLE
Instant Search: Prettier error messages

### ISSUE THREAD

**Issue by a8ck3n** [Automattic/jetpack#25434]
### Impacted plugin

Jetpack, Search

### What

Prettier styling for our publicly visible error messages.

### How

Currently the error messages look like this:

![ExampleError](https://user-images.githubusercontent.com/40267301/184067241-3adf9499-965d-4be2-8690-68e322dc1fa1.png)

It would be nice if we separated the icon from the text and cleaned up the layout so that (a) the icon is center-aligned with the first line of text and (b) the left-edge of the text is consistent (meaning it doesn't go under the icon).

**Comment by kangzj** [comment]
I'm reserving the issue for @grzegorz-cp 😃
