### ISSUE TITLE
Instant Search: Results 404 if permalink format is changed

### ISSUE THREAD

**Issue by a8ck3n** [Automattic/jetpack#25439]
### Impacted plugin

Jetpack, Search

### Steps to Reproduce

1. Visit the Search overlay and confirm search is working. — `/?=`
2. Change the permalink style under Settings → Permalinks. — `/wp-admin/options-permalink.php`
3. Bring up the Search overlay again and click on any result.
4. Confirm the browser loads a 404 page.

### A clear and concise description of what you expected to happen.

The overlay should update with the correct permalinks for any freshly loaded results.

### What actually happened

Any clicks on search results will result in 404 pages.

### Browser

Google Chrome/Chromium, Mozilla Firefox, Apple Safari

### Platform (Simple, Atomic, or both?)

Self-hosted

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

The fix for this is to reindex the site. This can be done from the users WordPress.com account under Settings → General → Manage Connection. I had to reindex a few times before the search results started working again.

**Comment by bluefuton** [comment]
Is this potentially the same as https://github.com/Automattic/jetpack/issues/23935?

**Comment by a8ck3n** [comment]
> Is this potentially the same as #23935?

Yes, it looks like. I'm not seeing what Bob is seeing (with redirection) but your comment (about getting 404s) matches what I'm seeing. I'll close this in favour of that Issue.
