### ISSUE TITLE
Publicize: Add Support for New Facebook Pages

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#25444]
Facebook is rolling out a new version of their Pages feature, changing the permissions that apps need to add content.

> For Pages that have been migrated to the New Page Experience, a Page access token is now required for all available endpoints
> —https://developers.facebook.com/docs/pages/overview/permissions-features 

There is some [more information about page access tokens](https://developers.facebook.com/docs/pages/access-tokens), but I think the solution is to adapt the code to get and store these tokens if they’re not available the next time we attempt to call the API on behalf of a given user. Ideally, we would do this in Keyring as an extension of the Facebook service.

We received the following tips from a Facebook contact, maybe we could start with that:
> You should use the (`/feed`)  [Pages Post endpoint](https://developers.facebook.com/docs/pages/publishing/) for performing the creation of posts, using the proper [`pages_manage_posts`](https://developers.facebook.com/docs/pages/overview-1#permissions) permission.
>
> If you have the information to troubleshoot (app ID /token) you can use the [Access Token debugger](https://developers.facebook.com/tools/debug/accesstoken/) to evaluate if your token is active/working, and you can debug the API calls using our [Graph API explorer](https://developers.facebook.com/tools/explorer/), calling to /feed (Pages Post) endpoint.
>
> In case the deprecated permissions aren't working, please test with the new one (`pages_manage_posts`)

For more context: p7fD6U-4lZ-p2

**Comment by jorpdesigns** [comment]
Hi there! I have spotted a reoccurrence of this issue in 6346859-hc

Looks like the user's Facebook page was automatically converted to the new Facebook Page experience and this deleted their Facebook Publicize connection (not sure of the time difference between both actions). 

When they try to reconnect, the process goes smoothly and they even see a "Success" dialog but the Publicize page shows a "Connect" button afterwards instead of the connected Facebook page.

I did suggest changing the Facebook page back to the classic page but the user is wary about losing content. Was hoping I could get a second pair of eyes on this please? Thanks.

- [ ] Follow-up ticket created here: 5341536-zen

**Comment by pablinos** [comment]
This is certainly an odd one! I've checked the access token and it was created today, but there is no associated Publicize connection. This could be related to the new page experience, but it's presenting a bit differently to the problem that caused this issue.

> they even see a "Success" dialog

Reading how they describe this, I'm not sure it's the success dialog we would expect to see as the Publicize connection is created. The Facebook authentication process happens in a pop-up, and it can look like that has completed successfully but then the last test will fail.

The user access token looks valid for the Facebook page they're enquiring about too, but querying against it I see that the `can_post` field is coming back as `false`. Is it possible that the Facebook user they're logged in as, no longer has permission to post to that page?

There is the resulting page token which gives a `can_post` value of `true`. I'll do some more digging and see what I can find as the two `can_post` values should be the same.

**Comment by tmmbecker** [comment]
@pablinos I've been troubleshooting this same issue on https://thefifthestate.com.au/ and I have been able to reliably reproduce this problem as I direct access to the customer's Facebook account. I experienced the exact same problem that @jorpdesigns described. I get all of the [proper](https://d.pr/i/xOvbkd) [steps](https://d.pr/i/MMsaZd) in the flow, the user connection is created and I get a [success message](https://d.pr/i/fayW5C), but after the last step, I still [see the button to **Connect](https://d.pr/i/5B6l8K)**.

They are an admin on the page and the Page is part of the Meta Business Suite and has been updated to "the new Pages experience." They had previously connected the site to the old page but it appears that when they switched the page, it was automatically disconnected. They didn't do anything to disconnect it manually. 

I'm happy to share the details I've got if you'd like to do some more specific troubleshooting.

**Comment by eduardozulian** [comment]
I asked the customer that @jorpdesigns helped if they are an admin but given @tmmbecker's reply, it might be another issue.

@Automattic/dotcom-pa-group would you mind checking this report and see if any extra triaging (including setting a priority) needs to be done?

**Comment by jamiepalatnik** [comment]
Another report: 36037823-hc

**Comment by Robertght** [comment]
@pablinos any updates on this?

**Comment by mxhassani** [comment]
Similar issue here: 5384307-zd-woothemes

**Comment by dcoleonline** [comment]
- [ ] 5427285-zen

I told them to switch to classic pages for now https://web.facebook.com/business/help/664061057662340?_rdc=1&_rdr

**Comment by tmmbecker** [comment]
Update to my [previous comment](https://github.com/Automattic/jetpack/issues/25444). The publisher switched back to classic pages (losing months of posts in the process) and was able to connect publicize with no trouble.

**Comment by tmmbecker** [comment]
@Automattic/dotcom-pa-group or @pablinos could someone please take a look?

**Comment by Robertght** [comment]
5464931-zen

**Comment by Robertght** [comment]
Moved this to Jetpack and cc'ing Reach team as discussed here (p1660219237727029-slack-C01UW7SB411)

@Automattic/jetpack-reach

**Comment by pablinos** [comment]
I've just made a comment on D60013-code, which was the fix for this problem before. There's a chance we can revert that to fix this now. I think Facebook have fixed the bug that caused this problem, but that has broken the workaround.

For now I don't think we should advise people to revert to the classic experience if it means they lose content.

**Comment by ariel-maidana** [comment]
5476376-zd-woothemes
Please notify the user once the fix is released.

**Comment by pablinos** [comment]
I've been discussing this with Facebook and it seems the workaround we were using to avoid the bug in Facebook's API can no longer be used without the `business_management` permission, which we can't easily request for existing users, and is far too permissive.

I've reverted and tweaked the changes from D60013-code in D86348-code, which should hopefully fix the problem. Once it's merged we can ask the people that have reported the problem to try again.

**Comment by thesacredpath** [comment]
@pablinos , has this been merged? Have a user that is having issues connecting to their FB page via publicize. It just keeps coming back to connect and not indicating any errors or anything, and will not connect.

Edit: I've let the user know that I'm checking on when this fix will be merged, and wanting to close the loop and include the follow-up ticket.

5513789-zen

**Comment by csabarakasz** [comment]
Same issue here: 

- [ ] 35539629-hc

Suggested switching back to old Facebook page experience https://web.facebook.com/business/help/664061057662340?_rdc=1&_rdr

**Comment by pablinos** [comment]
> @pablinos , has this been merged?

I've just merged it @thesacredpath. Sorry for the delay, I've been having quite a bit of back and forth with Facebook about this one.

It should now be fixed for pages with and without the New Page Experience. If we could get confirmation from some of the people affected then we can contact all the others.

**Comment by pablinos** [comment]
r251496-wpcom for future reference.

**Comment by thesacredpath** [comment]
@pablinos , thanks a lot for your work and letting me know. I'll have the user try again.

**Comment by bobmatyas** [comment]
@pablinos Now that this change has been made, does that mean that [this part](https://jetpack.com/support/jetpack-social/facebook/) of the Publicize docs:

> A page-only account, a page managed by Facebook Business Manager, or pages using [Facebook’s new page experience](https://about.fb.com/news/2021/01/introducing-the-new-page-experience/) cannot be used with Jetpack Social.

is incorrect? Jetpack Social will now work with the new page experience, correct?

**Comment by pablinos** [comment]
Yes. I think the issue is that pages with the new experience are treated a bit like business entities now, so pages managed by Facebook Business Manager might also work.

We'll have to do a bit of testing, but we can update the docs to remove the new page experience caveat.

**Comment by IoanaAMuresan** [comment]
Another instance here: 5507431-zd-woothemes
 Following previous HE's instructions to post here for info. Letting the customer we're looking into this.

**Comment by pablinos** [comment]
Hi @IoanaAMuresan. Reading through that exchange the customer was definitely affected by this issue but they can now connect and post successfully (which is great news as it shows the fix is working).

There is something involving the deletion of a post, that I don't quite understand, but they seem ok with it. Let me know if there's more I can do to help here.

**Comment by Robertght** [comment]
@pablinos they shared:

>>I just published a test post to the FB page I had designated. It was successful. I don't know why the one that was deleted from FB, then unpublished in WP to be republished didn't then show up on the FB page, but that situation shouldn't ever really occur in normal use. 

I'm guessing this could've been just a case between the time when the fix was added and when things didn't work correctly,  so I'd say we're ok here. Let me know if you think otherwise.

**Comment by IoanaAMuresan** [comment]
Sounds good. I'm now EOD and have to go AFK, but I can follow up with them tomorrow if needed. Would I tell them to check and let us know if they're still seeing issues? Something else? Thank you.

**Comment by pablinos** [comment]
@Robertght Yes, it seems like it, but it also seemed like they were deleting a previous FB post, then setting a WP post to draft  and publishing it again. That won't work as Publicize only runs once against any WP post. 

There is a re-share option, but that is currently only available on paid plans.

**Comment by pablinos** [comment]
Thanks @IoanaAMuresan! It sounds like they're all good currently. We could just get them to confirm that maybe.

**Comment by kraftbj** [comment]
It sounds like this issue is resolved so I'm closing it. @pablinos if there's outstanding work, please do reopen!

**Comment by pablinos** [comment]
Yes, there's been no further reports. Hopefully this is fixed for the long term now.
