### ISSUE TITLE
304 Browser Caching causes partial content issues

### ISSUE THREAD

**Issue by pjohanneson** [Automattic/jetpack#25462]
We've been using WP Super Cache pretty much since we moved to WordPress 3.0. When I updated the plugin to version 1.7.4 yesterday, my site started experiencing issues.

Logged-in users, who bypass the cache, saw no changes. However, any cached page would fail to load.

On my local machine, I tried `curl https://{server-name}/`, and I got the error `curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104`. If I SSHed directly to the server and ran the same command (ie ,`curl https://{server-name}/`), I would get this error instead: `curl: (18) transfer closed with outstanding read data remaining`.

(The difference in error messages may be due to our firewall.)

In both cases, I would consistently receive 7751 bytes of data for any page that was in the cache. If the page *wasn't* in the cache, it would load completely on the first attempt, but any subsequent attempts would get 7751 bytes.

The same happened if I tried various other pages on the server, in any of the sites (we're running WordPress Multisite).

The fix was to uncheck WP Super Cache's **304 Browser Caching** option under the Advanced tab. As far as I know, this option has always worked for us in the past.

Unfortunately, I'm not sure if I updated from 1.7.3 to 1.7.4, or if we were a couple of minor versions behind when I ran the updates (eg, going from 1.7.0 or 1.6.8 to 1.7.4).

## Environment:
* WordPress Multisite 5.7.2
* WP Super Cache 1.7.4, network installed
* Apache 2.4.48
* PHP 7.4.21
* MySQL 5.7.34-0ubuntu0.18.04.1
* Ubuntu 18.04.5
If you need further info, please let me know.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
