### ISSUE TITLE
Preload HTTPS and mobile pages

### ISSUE THREAD

**Issue by marcomarsala** [Automattic/jetpack#25515]
Preload feature won’t Preload any HTTPS or mobile page.

**Comment by Ciantic** [comment]
I think this is same problem as Automattic/jetpack#25516 I'm having same issue, the preload nor garbage colletion does not work. Using HTTPS as well.

**Comment by jeherve** [comment]
Do any of you still experience this issue today?

Thank you!

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
