### ISSUE TITLE
wp super cache keeps turning off by itself

### ISSUE THREAD

**Issue by sean3650** [Automattic/jetpack#25522]
hi 
i am currently using wp supercache and it is great.

but it keeps turning off by itself like almost everyday so i have to keep checking it?

do you guys know what is going on?

btw my version is 1.5.8

**Comment by r-martins** [comment]
The problem stopped in later versions.

**Comment by jeherve** [comment]
> The problem stopped in later versions.

Thanks for letting us know. I'll close this issue now, we can reopen it later if the problem comes back.
