### ISSUE TITLE
My site is HTTPS but non-secure content can still be accessed

### ISSUE THREAD

**Issue by jameswilson34** [Automattic/jetpack#25530]
We want to force HTTPS across our entire website. We have set our home URL to be https://www.............

But since using the WP Super Cache plugin we've noticed that once a page is in the cache, you can then hit it on a non-secure url and it still loads - so no redirect to HTTPS.

We have WP on ubuntu nginx powered server, Is this to blame or is there a setting we're missing?

**Comment by stodorovic** [comment]
Hi @wilsonf1 

I'm guessing that you use nginx custom rules. It could be reason. You need to add properly redirection rules. I'm not too familiar with nginx rules, but I think that following rules should work:
```
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_name example.com www.example.com;
	return 301 https://$server_name$request_uri;
}
```
For port 443, you need to put regular rules - https://codex.wordpress.org/Nginx#WP_Super_Cache_Rules

Similar issue is Automattic/jetpack#25551, You can look it. Also, if you send me more details (or your nginx config), then I can try to give you more precise instructions.
