### ISSUE TITLE
Contact Form: allow pre-filling form fields with URL parameters

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2554]
It would be nice if it were possible to pre-fill a contact form's field by specifying a parameter in the URL. It would allow site owners to create custom links to send people to a pre-filled form.

Suggested here:
https://wordpress.org/support/topic/pass-value-from-url-to-text-field?replies=1&view=all

**Comment by osiux** [comment]
This one can be closed :)

**Comment by mikemayhem3030** [comment]
@jeherve - drive by new use case for this

I really wanted to pass through a tag from a URL with a Jetpack Form on here: https://jexample.com/ so I could email out something like https://example.com/?tag=CRM  (bit.ly'd) and then people who filled in the form from that link would get the CRM tag (same could work with a status)

With our other Jetpack CRM form integrations, we suggest hidden fields and a different form per use - but it'd be an extra step if the URL parameters could be used to make forms dynamic (which then control how the data goes into the CRM) 

I also cannot see how to add hidden fields to the Jetpack Contact Form either

**Comment by jeherve** [comment]
> people who filled in the form from that link would get the CRM tag

This should already be possible. Here is an example:

![image](https://user-images.githubusercontent.com/426388/94127060-bece7500-fe58-11ea-9606-8ba8d71f4cdf.png)

Could you give it a try and let me know how it goes for you?

**Note**: you'll need to be logged out to see the pre-filled fields.

**Comment by mikemayhem3030** [comment]
Thanks :) I'll pass this onto Scott who was using it for one of his projects and circle back

**Comment by scottsweb** [comment]
Tested and is working as suggested above. Will see if we can make use of it with the CRM (closing the issue again)
