### ISSUE TITLE
Issues when using both AMP pages + mobile theme

### ISSUE THREAD

**Issue by talgalili** [Automattic/jetpack#25545]
When using a mobile theme (such as WPtouch Mobile Plugin), we need to add a list of items to “Rejected User Agents” ([see here](https://support.wptouch.com/support/solutions/articles/5000537668-configuring-cache-plugins-for-wptouch)). 
However, when using AMP pages (for example with the amp plugin by automatic), then that page will almost always be visited by a mobile user, but that page would then not be cached (due to the configuration aimed at the mobile plugin).

Possible solutions:
1) Have a separate “Rejected User Agents” fields for regular posts and for AMP posts. 
2) Add an action so that whenever a page is regularly cached by a visitor, it would also create the cache for the AMP page (This way the normal visitors to the site would trigger the amp cache, and the mobile users would benefit from it).

@donnchawp I'd appreciate your help with this.

Thanks,
Tal

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
