### ISSUE TITLE
WPSCFORCEUPDATE is not documented

### ISSUE THREAD

**Issue by htesligte** [Automattic/jetpack#25565]
We have a customer that changes posts frequently to private. This is because sometimes the post need to be visible again but is temporarily hidden. However, the cache is not cleared because wp-cache-phase2.php checks if $post->post_status != "publish". 
I noticed that there is a define 'WPSCFORCEUPDATE' that skips this check, but this isn't documented. 

Can I use this define safely to clear cache in this case?

**Comment by marcomarsala** [comment]
I'm in the same situation, thank you for pointing out this constant, will help me a lot.

Btw, the page cache should be purged when updating private posts, see my issue Automattic/wp-super-cache#941.

**Comment by stodorovic** [comment]
Duplicate of Automattic/jetpack#25571. This issue is most likely fixed in the latest version (1.6.3) of WP Super Cache (PR Automattic/wp-super-cache#577). Could you test it again on latest version?

**Comment by jeherve** [comment]
This should now be fixed. Feel free to reopen if the problem ever comes back.
