### ISSUE TITLE
Cache not deleted when switching to draft

### ISSUE THREAD

**Issue by meserlian** [Automattic/jetpack#25571]
Hi, 

Having an issue when switching a post from published to draft, as it is still visible to unknown users.

Is there a workaround for this?

**Comment by marcomarsala** [comment]
Probably related: Automattic/wp-super-cache#941

**Comment by stodorovic** [comment]
This issue is most likely fixed in the latest version (1.6.3) of WP Super Cache (PR Automattic/wp-super-cache#577). Could you test it again on latest version?
