### ISSUE TITLE
Delete Cache button on Admin Bar not working

### ISSUE THREAD

**Issue by galbaras** [Automattic/jetpack#25594]
I have WP Super Cache installed on a good number of sites and it seems that clicking "delete cache" in the admin bar while on a page has no effect. There are some mentions of this issue on the plugin's support forum on wordpress.org, including some very old ones, but for me, it's a new issue.

If it makes a difference, I use iThemes Security (with .htaccess and wp-config.php made read-only), and my sites are on a LiteSpeed server, not Apache.

**Comment by jeherve** [comment]
Do you still experience issues with this?

Thank you!

**Comment by galbaras** [comment]
Honestly, I don't use WP Super Cache anymore, so couldn't tell you. @marcomarsala or @artursopelnik ?

Why is this in the Jetpack forum?

**Comment by jeherve** [comment]
> Honestly, I don't use WP Super Cache anymore, so couldn't tell you

👍

> Why is this in the Jetpack forum?

We've recently moved WP Super Cache to the Jetpack monorepo, where it can live [with other Automattic plugins](https://github.com/Automattic/jetpack/tree/trunk/projects/plugins), and benefit from the tooling we've developed in this monorepo to automate things like plugin updates, issue management, ...
