### ISSUE TITLE
Frequent Pre-Load stalls.

### ISSUE THREAD

**Issue by bigtomjp** [Automattic/jetpack#25591]
I am getting very frequent preload stalls. Sometimes 5 in two hours. I am not sure what to look for in the logs and I am not sure why this is happening. Only happening with one site. Using WPSC on 4 sites.

I also se this many time in the log:
"Setting up WordPress actionsSupercache caching disabled."
This happens even though Supercache is enabled

**Comment by jeherve** [comment]
Do you still experience issues with this?

Thank you!

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
