### ISSUE TITLE
304 Not Modified browser caching

### ISSUE THREAD

**Issue by aligoren** [Automattic/jetpack#25601]
Hi. Thank you all for WP Super Cache.

I'm get an error:

**304 Not Modified browser caching. Indicate when a page has not been modified since last requested.**

How can I solve?

htaccess file manually, should I add?

i'm sorry for my bad english. thank you :)

**Comment by jeherve** [comment]
Do you still experience issues with this?

Thank you!

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
