### ISSUE TITLE
Protect: Difficulty checking IPv6 addresses

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2565]
Testing Protect on my site that has both A and AAAA records for IPv4 or IPv6 connectivity. If I force my home internet connection to IPv6, I get the math prompt on login (suggesting API failure). If I force my home connection to IPv4, no math question on the form, suggesting API success.

**Comment by kraftbj** [comment]
@samhotchkiss the work done on APIv2 should have resolved this, right?

**Comment by samhotchkiss** [comment]
Most likely-- it would be good to test

**Comment by jeherve** [comment]
@kraftbj Could you test this, and see if this has been resolved? I'm not sure how to test this myself :/

Thanks!

**Comment by gvenk** [comment]
In 3.9.1 the problem still exists.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/protect-and-ipv6/

**Comment by htdat** [comment]
1584262-zen

**Comment by pmciano** [comment]
Another report here 2488078-zen

**Comment by jeherve** [comment]
Possibly related: #17566

**Comment by kraftbj** [comment]
Going to close this based on improving IPv6 work in #17568. We can reopen or open a new issue if it crops back up.
