### ISSUE TITLE
Lazy Images: Woo product image not loading in Safari

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#25659]
There seems to be an issue with Jetpack lazy images + WooCommerce sometimes not displaying the product image correctly in **Safari**.

**Steps used to reproduce:**

* Create a JN site with WooCommerce and Jetpack. I tested with the 'Twenty Twenty' theme.
* Connect Jetpack and make sure lazy loading is enabled at `wp-admin/admin.php?page=jetpack#/performance`
* Activate WooCommerce and publish a test product with a product image included.
* View the published product page in Chrome/Firefox and refresh the page a few times, the product image should always display as expected.
* Next view the product page in Safari, the product image may not load. Note that this seems to be somewhat intermittent. Try refreshing the product page a few times to see.
* Disable Jetpack lazy images and try viewing again in Safari and the product image should always load as expected.

**Other notes:**

* When the image doesn't display, you can hover over the image and the zoomed portion displays okay.
* If you disable the hover zoom effect with the below snippet, the issue seems to go away even with JP lazy images enabled:

```php
function remove_image_zoom_support() {
    remove_theme_support( 'wc-product-gallery-zoom' );
}
add_action( 'wp', 'remove_image_zoom_support', 100 );
```

via: https://github.com/Automattic/jetpack/issues/23553#issuecomment-1215470801

**Comment by jorpdesigns** [comment]
Thanks for looking into this @samiff 

Quick addition: The product image also does not display on archives and other pages that display the product. Basically the product image is missing across the site and not just on the single product page.

**Comment by anomiex** [comment]
Is this the same as https://github.com/Automattic/jetpack/issues/25284?

**Comment by samiff** [comment]
> Is this the same as #25284?

Thanks, didn't see that one. Though I do find it odd in that issue it mentions:

> this gets fixed if Jetpack plugin is active along with Jetpack Boost

Because the issue here seems to occur with Jetpack being active.

**Comment by bizanimesh** [comment]
Found a similar issue on: 5622805-zd-woothemes

**Comment by brinbliss** [comment]
Same issue in 37726415-hc. Disabling Lazy Load solved the issue on Safari with missing product images.

**Comment by jorpdesigns** [comment]
Reported in 39657576-hc. Disabling JP Lazy-loading resolved the issue.

**Comment by jorpdesigns** [comment]
Reported in 38576291-hc
