### ISSUE TITLE
[Photon module] PHP Warning: Illegal string offset 'width'/'height'

### ISSUE THREAD

**Issue by leandroprz** [Automattic/jetpack#2566]
Ever since I enabled the Photon module on my website I started getting this error:

	PHP Warning:  Illegal string offset 'width' in /home/xxxxx/public_html/wp-content/themes/touchfolio/image.php on line 24
	PHP Warning:  Illegal string offset 'height' in /home/xxxxx/public_html/wp-content/themes/touchfolio/image.php on line 25

[Here](https://github.com/dimsemenov/Touchfolio/blob/master/image.php) are the contents of the image.php file. Is it possible that maybe this error comes from the theme and not the module? Since I'm not sure I thought I'd post it and hopefully get a solution.

I have disabled it for now until I can resolve this.

**Comment by kraftbj** [comment]
Could you send us a support ticket at https://jetpack.me/contact-support/ ? I used that theme's code copied/pasted into Twenty Fifteen running WP 4.3 + JP master + Photon and couldn't reproduce. My hypothesis is that is may be either a theme or plugin conflict elsewhere.
