### ISSUE TITLE
VideoPress: fix Fatal error when VideoPress and Jetpack plugins are both active

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#25686]
* Active both Jetpack and VideoPress plugins
* Connect Jetpack

![Image](https://user-images.githubusercontent.com/77539/185203735-fb7b506c-ebc4-4c45-934e-8b72d7ef4a1b.png)

```
Fatal error: Cannot redeclare videopress_is_valid_guid() (previously declared in /srv/users/user9338b8e0/apps/user9338b8e0/public/wp-content/plugins/jetpack-videopress-dev/jetpack_vendor/automattic/jetpack-videopress/src/utility-functions.php:24) in /srv/users/user9338b8e0/apps/user9338b8e0/public/wp-content/plugins/jetpack/modules/videopress/utility-functions.php on line 24
```

![Image](https://user-images.githubusercontent.com/77539/185204477-94071994-ba75-4328-829c-c438542151e8.png)

**Comment by leogermani** [comment]
The autoloader should handle this and only one instance of the VideoPress `Initializer` class should be loaded... I can't reproduce this...

Maybe this happened in a state where the autoloader of each plugin was not up to date? Can you test running composer update for both plugins and see if the error persists?

**Comment by retrofox** [comment]
Tested using JN

**Comment by retrofox** [comment]
It still happening for me, testing with a JN site: 

https://gifted-humboldt.jurassic.ninja/wp-admin/admin.php?page=jetpack

**Comment by leogermani** [comment]
ok, this is happening when running bleeding edge videopress plugin with "old" versions of Jetpack (latest stable). Jetpack will include the function after the package already did it without any checks.

There is no way of preventing that, unless we checked to see if Jetpack is active and what is the Jetpack version... this is not very elegant and I'm afraid this can have some side effects in Atomic, that runs crazy Jetpack versions...

I'm gonna fix this the right way, moving all the functions into a class to avoid conflicts and replacing all the usage of these functions within the package...

**Comment by leogermani** [comment]
https://github.com/Automattic/jetpack/pull/25925
