### ISSUE TITLE
Protect: Leaving math blank results in loop

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2571]
Steps to reproduce:
0. Mock API failure (setting the `JETPACK_PROTECT__API_HOST` constant to something that will fail)
1. At login form, leave the math question blank with valid user/pass.
2. Submit form, `generate_math_page` is fired, resulting in a secondary math question.
3. Answer correctly the secondary math question

Expected:
Login processed successfully.

Actual:
Returned to the regular wp-login.php login form, no notices.

Video: https://cloudup.com/c54wJ6p5gzj

**Comment by samhotchkiss** [comment]
actually, this is the expected behavior.  We don't save the initially submitted username/password, and the messaging on the interstitial page tells them that they're going to have to log in again.

**Comment by kraftbj** [comment]
Gotcha. It seemed odd that answering the question wrong gave you a interstitial that tells the user to use the back button and refresh, when a blank answer gives you an action to take. I expected the same result.

**Comment by samhotchkiss** [comment]
The rationale is that the way people will normally access the interstitial is if they have a custom login form without the math problem in it.  When you answer the math problem on the interstitial page, it disregards math for the next login attempt from that computer
