### ISSUE TITLE
wp.me: Changed domain name, shortlinks are wrong

### ISSUE THREAD

**Issue by odie2** [Automattic/jetpack#2573]
Hello,

I've working on new website at `http://zschocianow.nazwa.pl/wordpress/` and now switched to `http://zschocianow.pl/` (by cpanel - short URL pointing to long as default one).

I updated some `nazwa.pl/wordpress` to `pl` manually in phpMyAdmin, but wp.me still pointing to old long URL.

Example:
```
http://zschocianow.pl/lokalne-szlaki-turystyczne-rajd-rowerowy-2015/

http://zschocianow.pl/?p=8391 (without wp.me module)

http://wp.me/p679Ui-2bl
-> http://zschocianow.nazwa.pl/wordpress/?p=8391
```

Using WP v4.2.4 and JetPack v3.5.3 (can't update at the moment).

Hope to fast help, as website should be available soon, but properly switched. Thanks in advance.
Greetings

**Comment by odie2** [comment]
My fault.
Disabled and re-enabled Jetpack to connect it again with WP.com.

**Comment by kraftbj** [comment]
To explain this issue more for anyone seeing it in the future, the wp.me links are parsed on our end to use the domain—as it is recorded in our database. If you've changed the URL for the site and we haven't processed that change, the old URLs will still be used.

Once the change is applicable on the wp.me side, it'll point to the domain of record for your Jetpack site.
