### ISSUE TITLE
VideoPress components: VideoCard

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#25748]
![Image](https://user-images.githubusercontent.com/1663717/185972156-5fbcdde1-991b-4c99-a149-8d345814ada6.png)

mobile

![image](https://user-images.githubusercontent.com/77539/187682001-52af59a6-9458-445a-94c3-fa9d3cd3394d.png)

**Comment by renatoagds** [comment]
Mobile approach described here: pe4Cmx-9r-p2#comment-64

**Comment by retrofox** [comment]
Partially handled by this PR https://github.com/Automattic/jetpack/pull/25895

**Comment by retrofox** [comment]
Let's name it ~`VideoEditCard`~ `VideoCard`

**Comment by retrofox** [comment]
Related to it https://github.com/Automattic/jetpack/pull/25981

**Comment by retrofox** [comment]
> ...exposes the most common actions such as the primary CTA (edit video details), upload a thumbnail, change privacy definitions, and delete a video.

<img width="454" alt="image" src="https://user-images.githubusercontent.com/77539/187935009-351f71a6-3ee8-4b9d-b74a-5c847e693c33.png">

**Comment by renatoagds** [comment]
@retrofox the quick actions, design requested us to remove it for now: p1661157047489049/1660933240.163389-slack-C03TA48NSUX ... something to be aware of.

**Comment by retrofox** [comment]
![image](https://user-images.githubusercontent.com/77539/187949335-31860440-c184-4f08-b48f-204d9888cc66.png)
