### ISSUE TITLE
Subscriptions: Per-post exclusion debugging data

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2575]
Once #2370 lands, we need to make accessible to HEs whether or not a particular post was excluded for debugging/support purposes.

Pub RC seems like a good place. I'm working with @dereksmart on this one.

**Comment by kraftbj** [comment]
Still on my list, but been pushed down. The support load hasn't really needed it yet, but still want to get it in before it is actually needed day-to-day.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. For now, we should be able to get that data from the post meta in our sandboxes when needed.
