### ISSUE TITLE
Atomic site cannot purchase Jetpack Search plan

### ISSUE THREAD

**Issue by dsas** [Automattic/jetpack#25754]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. On a regular atomic site (it's not a dev site or anything)
2. Go to Settings -> Performance in the menu
3. See 'Enable Jetpack Search' is enabled, click on 'Upgrade your Jetpack Search and get the instant search experience'

### A clear and concise description of what you expected to happen.

To see the wpcom cart with a jetpack search plan added

(Maybe a better sell with more details really but...)

### What actually happened

I got a message saying 'Sorry, that product is not compatible with sites hosted on WordPress.com' along with a 'You have no items in your cart' messages

![sj6G1j.png](https://user-images.githubusercontent.com/93301/185979274-8350e4f9-3958-409d-bc9e-0011d21e1cde.png)

### Browser

Mozilla Firefox

### Other information

https://user-images.githubusercontent.com/93301/185978882-fd238dc8-d7e5-450c-85fe-c7e6ac63b65b.mp4

I've reproduces this on several atomic sites.

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by DavidRothstein** [comment]
That looks pretty bad and affects other ways of buying Jetpack Search too (for example from https://jetpack.com/upgrade/search/ or https://cloud.jetpack.com/pricing).  Seems to be a regression due to https://github.com/Automattic/wp-calypso/pull/66648 -- I'm looking into a quick fix.
