### ISSUE TITLE
VideoPress: Fix initial loading animation

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#25763]
https://user-images.githubusercontent.com/77539/185984068-b8b5381d-dcf3-4c42-b2a6-6fc3b3139bc5.mov

**Comment by renatoagds** [comment]
Did some tests and looks like #25392 fixed it, can you help to confirm @retrofox ?

**Comment by retrofox** [comment]
Confirmed, but fixed with the last migration https://github.com/Automattic/jetpack/pull/25392
