### ISSUE TITLE
 Go to WordPress.com button link destination. 

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#2578]
In Jetpack 3.7 Go to WordPress.com button takes you to the plugins for that particular site on .com 
See
![image](https://cloud.githubusercontent.com/assets/115071/9366710/b3acb2f2-466d-11e5-99a1-15c993c0342a.png)

This is not ideal. Since some sites/users might not even have access to plugins.

**Comment by beaulebens** [comment]
We probably will just want to send them to https://wordpress.com/stats/day or perhaps for the current site, so https://wordpress.com/stats/day/{site-slug}

**Comment by alternatekev** [comment]
That button is in a really weird place. Why is there a toggle for it? Can we use a gray button inside the header?

**Comment by dereksmart** [comment]
> Why is there a toggle for it?

To turn off the module, and so it's consistent with the other module toggles.  

cc/ @jeffgolenski

**Comment by jeherve** [comment]
Right now, you won't see the button unless you have the necessary permissions to manage Jetpack modules on the site (i.e you're an admin on the site and can view, activate, and deactivate plugins).

> This is not ideal. Since some sites/users might not even have access to plugins.

When would that happen? Are there cases when you can't access `wordpress.com/plugins`, although your Jetpack site is connected to WordPress.com and you have the necessary permissions to manage Jetpack modules on the site?

**Comment by kraftbj** [comment]
> Are there cases when you can't access wordpress.com/plugins, although your Jetpack site is connected to WordPress.com and you have the necessary permissions to manage Jetpack modules on the site?

Secondary admin user without their user account linked to WordPress.com?

**Comment by jeherve** [comment]
> Secondary admin user without their user account linked to WordPress.com?

Very good point!

I guess we can add one more check for connected users [here](https://github.com/Automattic/jetpack/blob/master/views/admin/admin-page.php#L129). @dereksmart What do you think?
