### ISSUE TITLE
VideoPress: Tweak focus state of Button component

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#25827]
Raised up in this comment: https://github.com/Automattic/jetpack/pull/25817#pullrequestreview-1084353005

Got some difference in the spacing from `list` and `toggle` button, and is missing the green outline on focus:

_Figma at right_

<img width="66" alt="Screen Shot 2022-08-24 at 15 55 44" src="https://user-images.githubusercontent.com/1663717/186501898-4b689f27-290a-42d1-bfba-bb9dee29353d.png"> <img height="86" alt="Screen Shot 2022-08-24 at 15 55 44" src="https://user-images.githubusercontent.com/1663717/186501904-2ce9edf1-8364-4bc5-876f-bf3753ad5e3b.png">

**Comment by retrofox** [comment]
@keoshi 👋  should we apply these styles by default? and to all variants?

**Comment by retrofox** [comment]
`--jp-green-40` #069E08

**Comment by retrofox** [comment]
![Image](https://user-images.githubusercontent.com/77539/186790473-8101249d-0757-40c3-bb6b-d6a5ae203623.png)

It seems something that we need to apply only for this component.

**Comment by keoshi** [comment]
Good catch — the green outline was supposed to reflect the `active` state, but you're right: it doesn't make sense so maybe we can simply use the existing `focus` style which thickens the black border. Would that work?

**Comment by retrofox** [comment]
> Good catch — the green outline was supposed to reflect the `active` state, but you're right: it doesn't make sense so maybe we can simply use the existing `focus` style which thickens the black border. Would that work?

Although its visual state changes when focusing on the button as it, it isn't visually significant. However, it's something that depends on the background image. If the image is mostly white, the visual changes will be more evident.

**Comment by keoshi** [comment]
Yeah, that's a good point. I'm not sure this is really an issue though, since the menu will pop up, giving way more meaning to that interaction than the outline ever could. What do you think?

**Comment by retrofox** [comment]
> Yeah, that's a good point. I'm not sure this is really an issue though, since the menu will pop up, giving way more meaning to that interaction than the outline ever could. What do you think?

I think we should discard these changes and iterate later :nod:, in case we consider needed.
