### ISSUE TITLE
Stat issue

### ISSUE THREAD

**Issue by haja-rimrubber** [Automattic/jetpack#25822]
### Impacted plugin

Jetpack

### Steps to Reproduce

Hello there,

We have PRD and STA environment. By mistake we recently disconnect jetpack in staging env.
Then it's disconnected from production also. After we know that we reconnect jetpack to both env.

Our sta env stat shown like this
https://ibb.co/K7qBd4c

Our prd env stat shown like this
https://ibb.co/tBRMzFP

How to move sta env stat to prd ?

### A clear and concise description of what you expected to happen.

Our old stat records not displayed in prd we need to get those data.

### What actually happened

Jetpack stat shown different in prd and sta env

### Browser

Google Chrome/Chromium, Mozilla Firefox, Microsoft Edge, Apple Safari, iOS Safari, Android Chrome

### Other information

Our sta env stat shown like this
https://ibb.co/K7qBd4c

Our prd env stat shown like this
https://ibb.co/tBRMzFP

### Platform (Simple, Atomic, or both?)

Simple, Atomic, Self-hosted

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

**Comment by jeherve** [comment]
You seem to be running into what we commonly call an "identity crisis", where 2 sites's connections got mixed up. I would recommend that you contact Jetpack support here with more information about each site:
https://jetpack.com/contact-support/?rel=support&hpi=1

They will be able to sort this out for you.

**Comment by haja-rimrubber** [comment]
Thank you @jeherve
