### ISSUE TITLE
VideoPress Standalone: Research why is it not possible to upload the first video for a free plan

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#25862]
Even when the Module is activated...
![Image](https://user-images.githubusercontent.com/77539/186904078-0a093043-505a-4e18-bf36-9aee21804099.png)

It is not possible to upload the first video in a Site with a Free plan.

![Image](https://user-images.githubusercontent.com/77539/186903843-d40ff794-068c-4ffe-a4ae-fd2eaa0ecbe6.png)

**Comment by retrofox** [comment]
The POST response body:

```
data: {error: "Access Forbidden",…}
error: "Access Forbidden"
message: "You have used your free video. Upgrade to a VideoPress plan to unlock more videos and 1TB of storage."
success: false
```

**Comment by retrofox** [comment]
In fact, I'm not able to upload a video after buying a VideoPress plan either.

**Comment by leogermani** [comment]
The initial options of the cache site are not being properly initialized.

p1661543617150639-slack-C039WR60VDF

Kernel is taking care of it: p1661529083549739-slack-C02NENKA4GN

**Comment by leogermani** [comment]
While Kernel is still looking at the Sync issue, we were able to fix this here:

D86939-code
