### ISSUE TITLE
Make Photon work with custom post types

### ISSUE THREAD

**Issue by leandroprz** [Automattic/jetpack#2588]
Hi,

It would be a nice addition to the Photon module to make it work with custom post types.

For example, my current theme uses a gallery post type with a slider, but Photon doesn't work with those images because it's not page or post content.

**Comment by kraftbj** [comment]
Photon will work with anything that has `the_content` filters applied to it (e.g. `apply_filters('the_content', $content-from-cpt);` or via the `image_downside` filter (usually picks up post thumbnails).

If the CPT could use core's the_content filter or fire `Jetpack_Photon::filter_the_content` it should work.
