### ISSUE TITLE
VideoPress block: Make some errors actionable

### ISSUE THREAD

**Issue by leogermani** [Automattic/jetpack#25888]
We need a way to make some errors present the user with a call to action to fix the issue, or at least with a link where they can find more information.

For example, when they upload a video with a unsupported format, they see:

![Image](https://user-images.githubusercontent.com/971483/186495606-9817677d-80a3-4bc5-ab89-c6226b833bf2.png)

This is added by an exception in the block. We need to add situations like this for more cases, example:

* User needs to buy a plan
* Site is not connected
* The same unsupported format error, but when the user is uploading from the Media Library

**Comment by leogermani** [comment]
@oskosk will check for a pattern we are using in wpcom blocks

**Comment by oskosk** [comment]
Note to self: Doublecheck which messaging pattern we should use in front of these conditions. (So to not show so many red and scary notices).

**Comment by retrofox** [comment]
We've implemented a couple of dialogs that allow the user to fix some issues, for instance, when the site is not connected. Closing this issue.
