### ISSUE TITLE
Highlander Comments: Login tooltip blocks access to login button

### ISSUE THREAD

**Issue by supernovia** [Automattic/jetpack#25904]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Visit a site with Highlander comments.
2. Click Log out.
3. Try to log back in using WordPress.com by clicking the W icon.

### A clear and concise description of what you expected to happen.

I expect to be able to click on the W and log in with WordPress.com

### What actually happened

A tooltip pops up over the icon, preventing anyone from clicking on it:

https://user-images.githubusercontent.com/3476361/187319421-2839e4c1-4948-4f1d-b07f-7372ee50ac00.mov

In Safari, sometimes I can get the tooltip to blink "off" and away depending on how I approach the W icon, but that's not easy, so I'm marking this as _consistent_.

### Browser

Google Chrome/Chromium, Mozilla Firefox, Apple Safari

### Other information

A bit of positioning would fix this:

```
.highlander-tooltip {
    margin-top: 42px;
    margin-left: 75px;
}
```

Reported here: https://wordpress.com/forums/topic/wp-comment-login-blocked-by-popup-image/

### Platform (Simple, Atomic, or both?)

Simple, Atomic, Self-hosted

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Workaround details

It affects all logged-out visitors who want to comment.

**Comment by coder-karen** [comment]
This should now be fixed (WordPress.com diff here: D86830-code). I tested it out (also with the links mentioned in the forum thread) and can confirm the tooltip has moved so all the login buttons are accessible now.
