### ISSUE TITLE
JS Components: Add a Pricing Card component with feature list

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#25916]
Create a Pricing Card component which could be used in our plan comparison page. The existing Pricing Card component could be found at:

https://github.com/Automattic/jetpack/blob/0104f558800dcee071842fb5f3cb78fa21449368/projects/js-packages/connection/components/connect-screen/required-plan/index.jsx

The issue depends on #25914 

![Image](https://user-images.githubusercontent.com/1425433/187350796-317874d7-43d5-4204-8e9e-87d952c6db37.png)

**Comment by oskosk** [comment]
Maybe check if this component suits our Search needs. Was introduced some weeks ago for the Social plugin

https://automattic.github.io/jetpack-storybook/?path=/story/js-packages-components-pricing-table--default

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/746152/188712398-a46c9b02-d441-4488-98ff-eb2426f7734d.png">

**Comment by kangzj** [comment]
@oskosk Thanks for the information. It looks nice 👍 I guess we could reused it. Will have a deeper look and see.

**Comment by kangzj** [comment]
Closing because this is irrelevant now, and we are tracking the page by issue: 
https://github.com/Automattic/jetpack/issues/25915
