### ISSUE TITLE
Search API: Update plan API to support query limit

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#25910]
We want to keep the API as compatible as possible, because we'll have the same code consuming the API for old versions.

Suggested changes to the API:

- Add a flag to identify whether it's on our new pricing or not. e.g. `"pricing": "2022"`
- Add plan allowed maximum usage. e.g. `current_plan: { max_records, max_search_requests, cost }`
- Add how many records indexed and how many search requests made in the current billing cycle. e.g. `records_indexed`, `search_requests_current_month`
- Add the plan the site will be on the next month. e.g. `plan_next_month: {max_records, max_search_requests, cost}`
- Billing cycle from ... to ...
- Any other attributes required

![Image](https://user-images.githubusercontent.com/1425433/187334599-5f46d1bc-4ada-4f34-91b3-f33d19e671e4.png)

P2: `pbtFFM-21I-p2#comment-2747`

**Comment by kangzj** [comment]
`D88792-code`

**Comment by jsnmoon** [comment]
I'll keep an eye on D88792-code and shepherd this issue to closure.

**Comment by jsnmoon** [comment]
D88792-code has been merged.
