### ISSUE TITLE
Search API: Update pricing API to support query limit

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#25913]
We aim to keep the API compatible with the new pricing, meaning we don't change any keys and only add keys when necessary.

`search_request_count` is already added, but which is not functional. The API depends on the new search products on WPCOM.

The API `wp-content/rest-api-plugins/endpoints/jetpack-search-pricing.php` is currently siteless and has its own logic to estimate pricing. I think we should,

- Replace the logic to user WPCOM product logic `pcNPJE-V7-p2`
- Possibly create a site specific API so that we could have the context of a site - previous search requests, records indexed etc
- We should also discuss with @Automattic/jetpack-origin if we could combine some efforts, as the checkout flow might need a similar API

![Image](https://user-images.githubusercontent.com/1425433/187336944-d67e9fea-444a-4d8e-be9c-decf097b5401.png)

**Comment by kangzj** [comment]
`D88792-code`

**Comment by jsnmoon** [comment]
I'll keep an eye on D88792-code and shepherd this issue to closure.

**Comment by jsnmoon** [comment]
D88792-code has been merged.
