### ISSUE TITLE
Search Plugin: Add plans view page

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#25915]
The page is to replace the old [upsell-page.jsx](https://github.com/Automattic/jetpack/blob/0104f558800dcee071842fb5f3cb78fa21449368/projects/packages/search/src/dashboard/components/pages/upsell-page.jsx)

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/4044428/192363224-a4bcdde5-76fd-429c-9b9c-6333c3f18c58.png">

Reference: `p1HpG7-hvT-p2`

**Comment by jsnmoon** [comment]
@dognose24 @kangzj: There's a newly added [PricingTable component](https://github.com/Automattic/jetpack/pull/25377) that we should be able to leverage!

**Comment by kangzj** [comment]
@danielpost and the team is working on this 🎉 

https://github.com/Automattic/jetpack/pull/26253

We probably want to set in a bit and see how we could help.
