### ISSUE TITLE
JS Components: Add a donut meter component

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#25917]
Create a donut meter, design could be found in Figma (follow links in `p1HpG7-hrJ-p2`), which would need the following attributes customizable:

- Size
- Percentage
- Starting point
- Color
- Width of the circle

Preferable not required:

- Animation for donut filling
- Zoom in on hover

The issue only requests the donut component to be created - the issue for whole donut section is [#25943](https://github.com/Automattic/jetpack/issues/25943). Please ensure the component could be previewed by storybook.

![Image](https://user-images.githubusercontent.com/1425433/187353767-2e94e2e1-3541-48f3-b692-c65e780f13d7.png)

**Comment by annacmc** [comment]
>The issue only requests the donut component to be created - the issue for whole donut section is to be created

Thanks for writing this up @kangzj 😄 

Just confirming I understand correctly. So for this issue we want to create ONLY the donut element as the JP component, and *not* show the label "Site Records" and count `310/10,000`, the info link here, right?

**Comment by kangzj** [comment]
> we want to create ONLY the donut element as the JP component, and not show the label "Site Records" and count 310/10,000, the info link here, right?

@annacmc  Yep this is for the reusibility purpose. I'll create another issue for the section. Any questions?

**Comment by annacmc** [comment]
No questions, that's perfect. Thanks @kangzj  🙌  I've got something whipped up this evening as just the chart component _(without any text or labels)_ I am just tidying it up now and shall PR tomorrow 😄  I just wanted to make sure I didn't misunderstand anything.

**Comment by kangzj** [comment]
> No questions, that's perfect. Thanks @kangzj  🙌  I've got something whipped up this evening as just the chart component _(without any text or labels)_ I am just tidying it up now and shall PR tomorrow 😄  I just wanted to make sure I didn't misunderstand anything. 

Nice one! That's fast! 🙌
