### ISSUE TITLE
Payment Buttons Block: Add Dimensions Panel

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#25927]
### Impacted plugin

Jetpack

### What

Add the Dimensions panel to the Payment Buttons block

### How

This will make the Payment Buttons block work like the Core Buttons block.

<img width="277" alt="Screenshot 2022-08-30 at 13 59 15" src="https://user-images.githubusercontent.com/2070010/187443251-80580a91-e76a-4f77-b6ca-26ab835a7f36.png">

_Note: the image above shows the panel with all the optional content enabled._

**Comment by dsas** [comment]
> Note: the image above shows the panel with all the optional content enabled.

@Copons, it doesn't show padding 🤔

**Comment by Copons** [comment]
> > Note: the image above shows the panel with all the optional content enabled.
> 
> @Copons, it doesn't show padding 🤔

Double-checking:

Core Buttons (plural) has margin and block spacing.
Core Button (singular) has only padding.
