### ISSUE TITLE
Payment Button Block: Add Dimensions and Typography Panels

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#25928]
### Impacted plugin

Jetpack

### What

Add the Dimensions and Typography panels to the Payment Button block

### How

This will make the Payment Button block work like the Core Button block.

<img width="277" alt="Screenshot 2022-08-30 at 13 59 15" src="https://user-images.githubusercontent.com/2070010/187443251-80580a91-e76a-4f77-b6ca-26ab835a7f36.png"><img width="275" alt="Screenshot 2022-08-30 at 13 59 04" src="https://user-images.githubusercontent.com/2070010/187443900-6e4f15eb-cdd7-4572-8674-0285135b6509.png">

_Note: the images above show the panels with all the optional content enabled._

**Comment by dsas** [comment]
The dimensions controls are intended for blocks that contain multiple blocks (e.g. columns, image galleries etc). Does adding it to the recurring-payments block which only ever contains one jetpack/button make sense? 🤔 

The typography settings probably make more sense to be added to jetpack/button; it'll be usable for other contexts in which jetpack/button is used and it means text colour and typography will be edited on the same block.

**Comment by rcrdortiz** [comment]
I think it's safe to re-scope this issue to just change the typography settings of the jetpack/button block, for now, we can evaluate later if the dimensions settings are needed for individual buttons.

**Comment by rcrdortiz** [comment]
Closed by: https://github.com/Automattic/jetpack/pull/26108

**Comment by rcrdortiz** [comment]
Created a follow-up to propagate the button controls to the payment block: https://github.com/Automattic/jetpack/issues/26252
