### ISSUE TITLE
NUX landing page: should we hide the manage column when the Manage banner was dismissed

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2594]
We currently have a dismissable Manage banner appearing at the top of the dashboard whenever Jetpack is active, and when the Manage module is not active.

https://github.com/Automattic/jetpack/blob/930df7b30b19cfe70fe9eb48669ca7909fb3248e/class.jetpack.php#L3397

That banner won't appear if you've already dismissed it, or if you've hidden it via the `can_display_jetpack_manage_notice` filter.

Shouldn't we also hide the Manage column from the Jetpack menu when that banner has been dismissed?

**Comment by dereksmart** [comment]
My gut tells me "no", because the column offers much more information about Manage and what it can do for you than the banner does.  Also, I've personally dismissed banners simply because they were there and annoyed me without even reading them first.  

cc @richardmuscat thoughts?

**Comment by richardmuscat** [comment]
I agree with you. Manage is a core Jetpack feature and we want to make sure
it gets as much air time as possible.

The column, unlike the banner, is part of the page layout and is not
blocking users from doing anything with Jetpack/WP-Admin.

**Comment by dereksmart** [comment]
:+1: - the column lives on!
