### ISSUE TITLE
VideoPress block. Bring the loading state back when you select a video from the Media Library

### ISSUE THREAD

**Issue by leogermani** [Automattic/jetpack#25942]
I think this was removed by accident here:

https://github.com/Automattic/jetpack/commit/eb7e4b82d212225815d9fd3337fa93333407888c#diff-5147e04ca543d9b3b50a4c0cb1794fced55443e151ae92c81b3c373fe93504f1L270

**Comment by renatoagds** [comment]
Don't think we should return this `Loading ...` state, reasons explained here: p1661896926081269-slack-C02TQF5VAJD

**Comment by leogermani** [comment]
@renatoagds We need some sort of feedback that we are waiting for an ajax request to complete. That ugly disruptive "Loading..." was just a placeholder. Agree we need something better, but we do need something
