### ISSUE TITLE
VideoPress : Try again and Cancel dont work after insert fails

### ISSUE THREAD

**Issue by leogermani** [Automattic/jetpack#25959]
If the block fails to insert a video, don't find a preview for example, the "Try again" and "Cancel" button dont do anything

Steps to reproduce

* Add a block
* Click "Insert from URL"
* Add a URL with a invalid GUID. ex: https://videopress.com/v/TIlcICLaa
* Wait for the block to fail

![Image](https://user-images.githubusercontent.com/971483/187728921-a21fc39e-47f0-4ecb-8949-feeee89cd554.png)

* Try to click the buttons and see they don't work

**Comment by retrofox** [comment]
addressed by https://github.com/Automattic/jetpack/pull/26819
