### ISSUE TITLE
IDC: banner style issues & automatic dismissal in the Jetpack menu

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2595]
Steps to reproduce:

1. Create an Identity Crisis on your site.
2. Go to the Jetpack menu in your dashboard.
3. The IDC banner isn't styled, and gets dismissed before we can act on it.

https://cloudup.com/cGYNSxXmd59

I also noted other styling issues on other non-Jetpack admin pages (Posts, Plugins):

![screen shot 2015-08-23 at 3 47 38 pm](https://cloud.githubusercontent.com/assets/426388/9428474/251ed444-49af-11e5-9044-bda3dd9509b4.png)

![screen shot 2015-08-23 at 3 06 45 pm](https://cloud.githubusercontent.com/assets/426388/9428481/6a0b35c0-49af-11e5-8d85-13be39476af8.png)

I also got another layout issue on the main dashboard page, but I can't seem to reproduce anymore. It happened after I purposely created an Identity Crisis by deleting Jetpack options from my database:
![screen shot 2015-08-23 at 3 06 15 pm](https://cloud.githubusercontent.com/assets/426388/9428539/93519238-49b1-11e5-87e7-1e5ce91ffe64.png)

**Comment by dereksmart** [comment]
cc @justinkropp - looks like core's `.error` class is overriding ours on pages not dashboard?

Adding `.stay-visible` class to the jetpack-message will stop it from hiding.

**Comment by kraftbj** [comment]
![screen shot 2015-08-26 at 15 42 11](https://cloud.githubusercontent.com/assets/88897/9505692/7d1abd46-4c09-11e5-8cfc-80984cc8a3e5.png)

Still auto-dismissing for me. #2622

**Comment by kraftbj** [comment]
Still seeing 
![screen shot 2015-08-26 at 15 49 48](https://cloud.githubusercontent.com/assets/88897/9505818/2c71c712-4c0a-11e5-92f1-b52e94d84851.png)
