### ISSUE TITLE
VideoPress block: prevent users from uploading if Jetpack is not fully connected

### ISSUE THREAD

**Issue by leogermani** [Automattic/jetpack#25963]
If the site is connected only at a site level, the Block does not show any warning and lets you try to upload, only to show this generic error:

![Image](https://user-images.githubusercontent.com/971483/187737337-91d8251d-2d15-4f6e-a2a1-5915688c6276.png)

Since we know the user connection is missing beforehand, we should warning the user and disable the block for new uploads (but enable it for inserting via URL or existing videos in the media library)

**Comment by retrofox** [comment]
https://github.com/Automattic/jetpack/pull/26819
