### ISSUE TITLE
Publicize: Tumblr: Post Format should be respected

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#260]
When Publicizing a post to Tumblr, Publicize doesn't respect the post format that is selected by the user. Instead, posts will be Publicized to Tumblr with Tumblr's "Text" format.

Steps to repro:
- Create a new post on a site that has an active Publicize connection to Tumblr.
- Set the Format to something other than Standard (Quote, for example).
- Make sure Tumblr is selected under Publicize, and publish the post.

Expected: The post is Publicized to Tumblr, using Tumblr's corresponding post format (i.e., Quote). 

Actual: The post is Publicized to Tumblr, using Tumblr's "Text" post format.
It would be nice if the post format that was set when creating the post was also used on Tumblr if a corresponding post format is available.

Things to note: According to Jetpack's support docs (see below), the post will be Publicized to Tumblr using the "Image" format if the post contains an image within the first 256 characters, or if the post format is set to "Image". This works in most cases, but if a gallery is inserted into the post before publishing, it will Publicize to Tumblr using the "Text" post format, regardless.
From the Jetpack support documentation:
Tumblr Publicize will display an image if your post is an image post format or if there is an image embedded within the first 256 characters of the post.
http://jetpack.me/support/publicize/

Originally ported from https://plugins.trac.wordpress.org/ticket/2048

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
