### ISSUE TITLE
[Bug]: Gardening task is failing when there is no content in the issue

### ISSUE THREAD

**Issue by madhusudhand** [Automattic/jetpack#26006]
### Quick summary

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/1935113/187433446-6303c727-c65a-4b41-baad-055dc1bd3124.png">

### Steps to reproduce

Create an issue without content. Observe that task is failing.

### What you expected to happen

Task should run without errors.

### What actually happened

Task failed with error.
gather-support-references: Getting references from issue body.
Error: main: Task gatherSupportReferences failed with error: TypeError: Cannot read properties of null (reading 'matchAll')

### Reproducibility

Once

**Comment by madhusudhand** [comment]
Also repo shows the following warning, and its not true.

<img width="909" alt="image" src="https://user-images.githubusercontent.com/1935113/188067565-659fabce-a548-4aed-a4b9-62ce299dc71a.png">

**Comment by mikachan** [comment]
@jeherve 👋 Pinging you on this issue as it looks like this is specifically related to the `gatherSupportReferences` task, which seems to come from `automattic/action-repo-gardening`. I'm not sure we can fix this directly in our repo, unless we removed this task I guess.

**Comment by mikachan** [comment]
> Also repo shows the following warning, and its not true.

This notice doesn't seem to be showing for me in this repo. Which page were you on?

**Comment by jeherve** [comment]
> Pinging you on this issue as it looks like this is specifically related to the gatherSupportReferences task

Yep, this needs to be fixed in the action. I'll move this issue to the Jetpack repo, where the action is developed.

**Comment by jeherve** [comment]
> repo shows the following warning, and its not true.

This is a different issue, currently discussed here:
p1662095866154779-slack-C01UW7SB411

**Comment by mikachan** [comment]
Thank you!
