### ISSUE TITLE
Add action bar UI including pop out menu

### ISSUE THREAD

**Issue by roo2** [Automattic/jetpack#26005]
This includes the html/css of the action bar and the hamburger pop out menu 

Includes mobile and desktop UI

see p2: pe7F0s-3h-p2 and figma: 2d7d7-pb
#### Mobile UI
![Image](https://user-images.githubusercontent.com/22446385/188031964-16f4ccac-5683-42f5-9b65-9a3e2ad79667.png)
#### Desktop UI
![Image](https://user-images.githubusercontent.com/22446385/188031963-50bbc4ac-fb99-4410-9359-5aafe3abe876.png)

To start with, I'll only add the link to the current site's homepage shown at the top of the menu. This card is mostly just adding the UI foundation.

### Dev Notes

See prototype 2d7d6-pb
* Implementing in jetpack rather than widgets.wp.com in part so that we can use transpiling etc. 
* Implementing with vanilla JS rather than libraries to keep it lightweight

### Testing notes
Must support all common browsers and be lightweight as it will be loaded on the front end of users blogs

**Comment by anomiex** [comment]
Action Bar has been abandoned and removed from the monorepo. See #34939.
