### ISSUE TITLE
General: Indicate which users are connected via wp-admin/users.php

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2601]
On Core's User List table, we should indicate which users are connected to Jetpack in some way. 

Suggested by @m on the DOPS p2.

**Comment by kraftbj** [comment]
First thought: A Jetpack icon on the user row?

**Comment by chaselivingston** [comment]
Could we use the `manage_users_custom_column` filter to add a custom column and then fill it with a Jetpack icon?

**Comment by m** [comment]
Just wanted to bump this for @beaulebens.

**Comment by beaulebens** [comment]
Something along these lines will definitely be part of a re-thought SSO experience/integration.

**Comment by jeherve** [comment]
Fixed in @3433
