### ISSUE TITLE
Jetpack Social prevents Contributors from saving draft posts

### ISSUE THREAD

**Issue by edwinho89** [Automattic/jetpack#26023]
### Quick summary

Jetpack Social prevents Contributor roles from saving draft posts.

***This bug can lead to content loss as the drafts/revisions are not being saved.  If you encounter a user experiencing this issue, please have them copy ALL blocks they currently have before proceeding with any troubleshooting.  They should paste the content into a save location.***

Initially reported in 33679430-hc

Jetpack version 11.3-beta

Internal (dev chatter): p1662143133231429-slack-C02JJ910CNL
Internal (happy-announce): p1662143779983839-slack-CB0B2G43X

### Steps to reproduce

1. On an Atomic site, invite a user as a Contributor
2. Enable [Jetpack Social](https://jetpack.com/support/jetpack-social/) (Publicize)
3. Login as Contributor, and create a new post
4. Insert contents on to post, save draft post

### What you expected to happen

Contributors can save draft posts as normal

### What actually happened

The unsaved draft posts cannot be saved with "Updating failed. Sorry, you are not allowed to access Jetpack Social data for this post." message.

![image](https://user-images.githubusercontent.com/34882260/188073115-08a4cb39-ddad-47ad-aa50-1e88daf811bd.png)

Reopening the draft post will have a new post titled "Auto Draft" as with blank contents.

By inspecting browser elements, you will also see error 403 forbidden as shown on screenshot.

### Context

Jetpack version 11.3-beta

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

***This bug can lead to content loss as the drafts/revisions are not being saved.  If you encounter a user experiencing this issue, please have them copy ALL blocks they currently have before proceeding with any troubleshooting.  They should paste the content into a save location.***

Deactivate Jetpack Social (Publicize) module

**Comment by edwinho89** [comment]
5526097-zd-woothemes

**Comment by vajrasar** [comment]
Another instance here which was resolved by changing the user role from Contributor to Author.

36741341-hc 

- [ ] 5526461-zen

**Comment by vajrasar** [comment]
Another one.

35886312-hc
- [ ] 5525479-zen

**Comment by JoshuaGoode** [comment]
Thanks, ya'll.

Please reach out to Reactor when Atomic-wide issues like this occur.  In Slack, on the requests P2, and @Automattic/reactor  work for that.

**Comment by JoshuaGoode** [comment]
Additional reports came in to at-help

* p1662141826442199-slack-C03TY6J1A
* p1662065620468649-slack-C03TY6J1A

@samiff mentioned potentially looking into this

**Comment by samiff** [comment]
@JoshuaGoode Currently looking into it 👍 Will likely transfer issue to Jetpack repo.

**Comment by samiff** [comment]
@danielpost @pablinos 

I was able to reproduce this issue on `11.3-beta2` and latest trunk. The issue was not present in Jetpack version `11.3-a.11`. From a quick bisect, the problematic commit appears to be: #24617

**Comment by JoshuaGoode** [comment]
Adding that this has the potential to cause content loss.

Contributors can begin working on a post and an auto-draft gets created; however, revisions are not saved.  If the user attempts to save their draft it will fail.

If they leave the editor, without manually copying all their content, their work will be lost.

**Comment by tvolpert** [comment]
User encountered this issue here:

- [ ] 5527900-zen

Jetpack Social/Publicize is deactivated on their site for now.

**Comment by samiff** [comment]
Jetpack version `11.3-beta3` should correct this issue for WoA sites.

Internal: check p9o2xV-2nq-p2 for when this version will deploy.
