### ISSUE TITLE
Non-Admins can't access the Media Library

### ISSUE THREAD

**Issue by GrantAustin** [Automattic/jetpack#2602]
Users that have the user role "Editor" and can't access the media library. When they press the Add Media button in the editor, the media popup pops up and it would be possible to upload media. When changing to the media library tab, the little waiting symbol right below the two tabs keeps spinning and spinning. The same thing happens when you go to the media page, but only if you're on grid view. 

Seems like contributors and authors can do this though.

**Comment by jeherve** [comment]
I can't seem to reproduce the issue on my end:

https://cloudup.com/c8kxs0KyRp3

Could you check for Javascript errors on the page, as explained here:
http://codex.wordpress.org/Using_Your_Browser_to_Diagnose_JavaScript_Errors

If you don't find any errors there, could you add the following to your `wp-config.php` file:

```
define('WP_DEBUG', true);
define('WP_DEBUG_DISPLAY', false);
define('WP_DEBUG_LOG', true);
```

Then, try to access the Media Library, and once you've triggered the error , check the `debug.log` file appearing in the `wp-content/` folder in your WordPress installation.

If the errors don't help you understand what's happening, could you try to deactivate all other plugins, one at a time, and let me know if you find a conflict with another plugin? If that doesn't help either, could you switch to one of the default themes for a few minutes and let me know how that goes?

Thanks!

**Comment by GrantAustin** [comment]
I have deactivated all plugins and reverted to the twenty fourteen theme
I checked the server to make sure there is enough RAM, Hard Drive space, and other resources.
I checked permissions in apache and all are set to be owned by apache

The only error that I get is:
Invalid argument supplied for foreach() in /public_html/wp-admin/includes/plugin.php on line 1438, referer: /wp-admin/upload.php

I also noticed that I wasn't the only one having the issue. 
https://core.trac.wordpress.org/ticket/33476

**Comment by kraftbj** [comment]
Is there any chance you can run a stacktrace on the server to see all of the functions involved with that call? The error calling plugin.php, by itself, can be a real rabbit hole to debug, so a stacktrace can really be helpful.

**Comment by jeherve** [comment]
> I also noticed that I wasn't the only one having the issue. 
> https://core.trac.wordpress.org/ticket/33476

This user contacted us via the Jetpack support forums as well, and [it turned out to be an issue with one of their plugins](https://wordpress.org/support/topic/media-library-via-post-editor-screen-for-non-admins-stopped-working?replies=7&view=all).

**Comment by GrantAustin** [comment]
Turns out, it was also a plugin as well. I didn't see my other administrator add this. He was trying to remove the Jetpack menu bar from non administrators.

https://wordpress.org/plugins/jetpack-only-for-admins/

**Comment by jeherve** [comment]
> He was trying to remove the Jetpack menu bar from non administrators.
> https://wordpress.org/plugins/jetpack-only-for-admins/

That makes sense! That was actually reported to use a while ago, I forgot about it! Instead of using that plugin, I'd suggest using the code snippet I posted here:
https://github.com/Automattic/jetpack/issues/801#issuecomment-48164142
