### ISSUE TITLE
Enhancement - Search plugin: exclude specific posts, pages

### ISSUE THREAD

**Issue by formosattic** [Automattic/jetpack#26029]
### Impacted plugin

Search

### What

Have an option to exclude specific pages, or posts.

User request: 5530185-zd-woothemes

### How

Two possible options:

* Option 1: have an option in the editor to mark it for exclusing
* Option 2: in Customize, have a way to select the pages or posts to exclude.

A current workaround is to have a special category for those specific posts and pages, then remove that category from Search (see [internal reference](p1615233015062400/1615231978.057400-slack-C02C4GXMY&amp;cid=C02C4GXMY)): 

* https://jetpack.com/support/search/frequently-asked-questions/#results-filter-category

**Comment by bizanimesh** [comment]
PcNPJE-1b6-p2 will cover this.

- Reference: p1676512104708219-slack-C02ME06LF

We will update [this support page](https://jetpack.com/support/search/frequently-asked-questions/#results-filter-post-type) as well.
