### ISSUE TITLE
JS Components: DonutMeter - Follow up on recommendations from #25947

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#26049]
Tracking issue. Recommendations from #25947

@annacmc Consider coming back to address these comments if needed.

### 1 

@a8ck3n https://github.com/Automattic/jetpack/pull/25947#discussion_r961277859

_Should we add some bounds checking on our props here? For example, making sure the segmentCount is less than the totalCount, keeping thickness between 1 & some upper bound, setting a minimum donutWidth?_

### 2

https://github.com/Automattic/jetpack/pull/25947/files#r961280723

_Instead of hiding the chart from screen readers, maybe we can mark it up a bit more?_

- _Wrap the DIV in a FIGURE element._
- _Add ARIA-LABELLEDBY element._
- _Add TITLE & DESCRIPTION elements._
- _Make the TITLE & DESCRIPTION values props._
- _Set the role attribute to IMG._

```
<figure>
  <div class="figure-content">
    <svg width="100%" height="100%" viewBox="0 0 42 42" class="donut" aria-labelledby="beers-title beers-desc" role="img">
      <title id="beers-title">Beers in My Cellar</title>
      <desc id="beers-desc">Donut chart showing 10 total beers. Two beers are Imperial India Pale Ales, four beers are Belgian Quadrupels, and three are Russian Imperial Stouts. The last remaining beer is unlabeled.</desc>
```
_This might eliminate the need for the summary table following the meter as well._

### 3

https://github.com/Automattic/jetpack/pull/25947#discussion_r961283393

_I think we should make the screen reader text more descriptive. As it currently stands, the screen reader is only announcing the meter and the values but without any context. If we have two meters side by side, it might not be clear what they represent. I think these should be strings that are passed to us._

_As noted above, I think it makes sense to put this inline using the TITLE & DESCRIPTION elements instead of in an associated table though. Maybe the table approach was used in the RecordMeter due to it being an inaccessible CANVAS element?_

_Either way, it would then be caller's responsibility to generate the correct localized strings and pass them in via props. We could then remove the dependency on /i18n entirely._

**Comment by a8ck3n** [comment]
Just noting that I'll be tackling these follow-up issues as Anna is AFK for a bit. Cheers!

**Comment by oskosk** [comment]
Thanks @a8ck3n !

**Comment by a8ck3n** [comment]
I believe the main concerns have been addressed. Will circle back to this later in the week once the final tasks for the updated dashboard have been sorted out.

**Comment by oskosk** [comment]
Nice, thank you!
