### ISSUE TITLE
Editor Extensions - Brand Jetpack features in publish flows

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#26048]
Mentioned in p1HpG7-hDK-p2

- [x] #26044
  - [x] #26101
    - Update icon colors and make logo smaller
  - [x] #26162 
- [x] #26064 

  - [x] Brand Jetpack features in post-publish flows
    - [x] #26163
    - [x] #26257

**Comment by pablohoneyhoney** [comment]
It'd be good to make them slightly smaller, and try them dark rather than grey.

**Comment by oskosk** [comment]
![image](https://user-images.githubusercontent.com/746152/189105673-e430c063-216b-4399-91f0-878f591be70b.png)
Updating to this in #26101

**Comment by oskosk** [comment]
Closing as it's been completed
