### ISSUE TITLE
Enhancement: add custom image for Publicize 

### ISSUE THREAD

**Issue by ecairol** [Automattic/jetpack#26042]
### Impacted plugin

Jetpack

### What

I'd like the option to upload a custom image to be used by social media, when sharing via Publicize connections

### How

While using Featured Image makes sense for most of the cases, we give maintenance to a website (https://seths.blog/) that doesn't use Featured Image on their posts very often.

They use Jetpack to publish to different social media and noticed that on LinkedIn this image was empty, but if someone shared the permalink manually, the `og:image` was used by LinkedIn.

It would be great to:
 - Pick up the `og:image` that's going to be rendered in the source code (tricky, I suppose)
 - Upload a default custom image for all posts where Featured Image will be empty.
 

<img width="903" alt="Screen Shot 2022-09-05 at 14 09 18" src="https://user-images.githubusercontent.com/1821060/188508390-1faaa1f6-9ae7-4033-83d6-651d19c86909.png">

**Comment by jeherve** [comment]
If no Featured Image was added to a post, we try to look for other images that may have been added into a post (in a gallery, a slideshow, inserted into the post, ...). If you do not have any other image that can be picked up, we do fallback to a default image. If you'd like to add your own custom fallback image, you can use the `jetpack_open_graph_image_default` filter:
https://developer.jetpack.com/hooks/jetpack_open_graph_image_default/

You'll want that image to be large enough (at least 200x200px) so it can be used by social networks when sharing the post.

Would that help?

**Comment by ecairol** [comment]
Yes, that would work. Thanks @jeherve!
