### ISSUE TITLE
JS Components: Build CUT component

### ISSUE THREAD

**Issue by a8ck3n** [Automattic/jetpack#26053]
A a message component (referred to as a CUT in the designs) that handles presentation and layout of the green box shown here:

![Image](https://user-images.githubusercontent.com/40267301/188564699-8199484d-8f32-4339-bff8-8f2efad3ec31.png)

**Dynamic Properties:**

- localized message string
- border colour
- callback for “action” button

Please ensure the component could be previewed by storybook.

**Comment by kangzj** [comment]
We should be able to reuse: 
https://automattic.github.io/jetpack-storybook/?path=/story/js-packages-components-contextual-upgrade-trigger--default
