### ISSUE TITLE
JS Component: Build Plan Summary component

### ISSUE THREAD

**Issue by a8ck3n** [Automattic/jetpack#26054]
A simple header-type component that lists the plan, rollover date, and a label.

![Image](https://user-images.githubusercontent.com/40267301/188565969-0ae569c9-ddbb-4f55-8947-d6a0d3f866bb.png)

**Dynamic Properties:**

- localized message string
- plan type
- rollover date

**Comment by dognose24** [comment]
This section should be refactored after updating the plan API with the new pricing tier change.

**Comment by dognose24** [comment]
This section should be refactored after updating the plan API with the new pricing tier change (D88792-code).

**Comment by dognose24** [comment]
We could sandbox the plan API to apply changes with `D88792-code` for the plan summary component.
