### ISSUE TITLE
Payment button: upgrade nudge suggesting a wrong plan

### ISSUE THREAD

**Issue by bindlegirl** [Automattic/jetpack#26057]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Try adding a payment button an a JN site with no plans attached.
2. Upgrade plan nudge will add Jetpack Security Daily plan to the cart instead of Jetpack Security (10GB)

Discussion: p8oabR-Vp-p2#comment-6595

### Browser

Mozilla Firefox

### Platform (Simple, Atomic, or both?)

Self-hosted

### Reproducibility

Consistent

**Comment by mmtr** [comment]
Thanks for the report!

> Upgrade plan nudge will add Jetpack Security Daily plan to the cart instead of Jetpack Security (10GB)

The daily plans were discontinued in November 2021 (pbtFFM-XN-p2) so the issue has been present for a long time in the Payment button block (and possibly other blocks like the Pay with Paypal block). It's worth noting that the new Payment buttons block (https://github.com/Automattic/jetpack/pull/25297) also has the same issue given that it carries the same gating logic that the Payment button block.

Considering that the issue has been unnoticed for a few months, I think this is a low priority.

**Comment by mmtr** [comment]
I had some spare time today so decided to prepare a fix for this which is ready for review: D87260-code

**Comment by mmtr** [comment]
Fixed by D87260-code
