### ISSUE TITLE
Notes: New iframe leading to 403 errors on some servers

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#26099]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. On a Plesk server (e.g. Ionos, etc), update to Jetpack 11.3, connect and ensure the Notifications module is enabled.
2. Visit wp-admin

### A clear and concise description of what you expected to happen.

wp-admin to load.

### What actually happened

403 error message.

![2022-09-07 at 4 23 PM](https://user-images.githubusercontent.com/88897/188983850-9410b3a6-53e2-40f5-9967-b968d53485ac.png)

### Other information

Debugging in p1662565776438439-slack-C01U2KGS2PQ

We added an iframe in https://github.com/Automattic/jetpack/pull/25448 to avoid cross-site cookie issues as browsers change their security model, but that iframe is being flagged by (some) modsecurity rules.

### Reproducibility

Consistent

### Available workarounds?

Yes, difficult to implement

### Workaround details

Disable the Notifications module. I'm marking this as difficult since if they can't get to wp-admin, it would require CLI or some other kind of access to disable.

Some have mentioned going to wp-admin/index.php has allowed them access, but I'm not clear if that's an universal solution.

**Comment by anomiex** [comment]
Another potential workaround would be for people to disable the problematic modsecurity rule, as described at https://stackoverflow.com/questions/61098278/modsecurity-rule-214940-warning for example. Since that's in their Plesk dashboard rather than WordPress, it might be easier for them to get to.
