### ISSUE TITLE
Jetpack Search: Secondary admin is presented the upsell admin page ignoring available plan

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#26094]
We show the upsell page to secondary admins even when the site has a Search plan associated

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/746152/188964480-fa1e49a2-d89f-4ae3-8cb3-0a72bd95b99a.png">

#### To reproduce

* Launch a [JN site with Jetpack Search on it](https://jurassic.ninja/create?jetpack-search&nojetpack)
* Connect and purchase a plan
* Create a secondary administrator
* Sign in as a this other administrator
* Visit the Jetpack Search page
* Confirm you're shown the upsell page.

**Comment by kangzj** [comment]
Some of the code was stolen from backup plugin, where probably has the issue too? FYI @jwebbdev 

https://github.com/Automattic/jetpack/blob/70361e56f8fdc79a6fb92b13ef5b7a12b51b78c0/projects/packages/backup/src/js/components/Admin.js#L56

**Comment by oskosk** [comment]
Thanks! I'll double-check the Backup case and file an issue for them if it's doing the same

**Comment by oskosk** [comment]
Pushed https://github.com/Automattic/jetpack/pull/26105 to address the Backup case
