### ISSUE TITLE
VideoPress: implement data handling for filter section

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#26168]
Once https://github.com/Automattic/jetpack/issues/26144 lands

![Image](https://user-images.githubusercontent.com/77539/194126281-a78a93aa-2a20-4e23-b159-5d9a8b5d4461.png)

**Comment by retrofox** [comment]
@fgiannar since filter has been removed, do you know how to achieve these requests?

* filter by uploader
* filter by privacy
* filter by rating

**Comment by lhkowalski** [comment]
Is the `uploader` actually the author of the media attachment post? In this case, since we are relying on the `/media` endpoint, we can use the built-in `author` filter:

```
curl -X GET -u "user:pass" "http://your-site.com/wp-json/wp/v2/media?mime_type=video/videopress&author={ AUTHOR_ID }"
```

**Comment by lhkowalski** [comment]
I tried to expand @fgiannar 's suggestion about filtering using the `rating` or the `privacy_setting`, but seems like we can't query using the `meta_key.meta_value_key.meta_value_sub_key` syntax (ref: p1665140456511769/1665055277.119199-slack-C02NENKA4GN).

We may need to explore some alternatives:

1. move the information that we are interested in filtering by to a "top level" meta field (for example `videopress_privacy_setting` and `videopress_rating`)
2. move all VideoPress meta information to this top level, moving away from the object inside `_wp_attachment_metadata` to a `videopress_*` meta field format
3. query using a `LIKE` condition inside the content of the meta value
4. other forms of filtering on the PHP or the JS side

I am leaning torwards the first one, but we'll discuss it further.

**Comment by lhkowalski** [comment]
I am working on a PR focusing on approach (1), moving the fields that we are interested to their own meta field. The plan is to move it on the storage layer only, keeping the request and response bodies the way they are today. After this, doing the filters using the meta fields is simple using the builtin WP features.
