### ISSUE TITLE
Publicize: Tumblr: Posts losing extra whitespace

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#262]
Example post where the extra whitespace is missing:
http://hermetic.com/files/jetpack-publicize-tumblr-1.png

Example of the original HTML from the post:
http://hermetic.com/files/jetpack-publicize-tumblr-2.png

User reports all Publicized posts to Tumblr is losing the extra whitespace on reblogging. Somewhere in the Publicize process, it appears that the whitespace is being stripped from the HTML. 

ported from https://plugins.trac.wordpress.org/ticket/1932

**Comment by jkudish** [comment]
Hey @kraftbj -- can you verify if this is still an issue, and if so open up a linked issue on the private io repo?
