### ISSUE TITLE
PHP Notice by conditional widgets

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#2620]
Just got this when I tried to view the login ( https://enej.wpsandbox.me/wp-login.php ) screen running the latest master branch 

`Notice: Undefined index: has_children in /home/enej/public_html/wp-content/plugins/jetpack/modules/widget-visibility/widget-conditions.php on line 423`

Which prevented my from logging in.

**Comment by kraftbj** [comment]
It shouldn't prevent you from logging in. In either case, https://github.com/Automattic/jetpack/blob/master/modules/widget-visibility/widget-conditions.php#L423 added by @michaeldcain in #2582.

**Comment by enejb** [comment]
I am seeing this. Cookie could not be set. 
![image](https://cloud.githubusercontent.com/assets/115071/9504536/f9303310-4bf1-11e5-82b3-d066b32fe617.png)

**Comment by dereksmart** [comment]
To reproduce: change the widget visibility rules on a widget that's been there before #2582 was merged.
