### ISSUE TITLE
My Jetpack: Re-enable module-product tests

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#26219]
As part of #26218, I marked the tests in test-module-product.php as skipped due to errors that were surfaced by fixing WorDBless.

We need to re-enable those tests and resolve the errors.

**Comment by lhkowalski** [comment]
Thank you for reporting the issue!

I started to work on this today. I was able to fix the mock issues that were generating errors while running the tests, and now I landed on the scenario where I have some test cases failing. My next step is to check if there is some mock issues generating the failures, or there is some wrong assumptions on the tests as well.

**Comment by lhkowalski** [comment]
This is now solved. The solution was described on the #26227.
