### ISSUE TITLE
Enhancement: Propagate jetpack/button typography controls to payment button block.

### ISSUE THREAD

**Issue by rcrdortiz** [Automattic/jetpack#26252]
### Impacted plugin

Jetpack

### What

The jetpack/button block has typography controls. The payments button block uses a jetpack/button block. We need to add controls to the payments block so that we can update the underlying jetpack/button's typography settings.

### How

Propagate the controls to the payment block.

This is a follow-up for #25928, in this first issue we've added the typography controls to the jetpack/button block.

**Comment by dsas** [comment]
This should really work like the core/buttons typography support. This means that changing a typography setting on the wrapper changes that setting for all of the child blocks that haven't already changed that setting.
