### ISSUE TITLE
Feature Request: Update Cookie and Consent banner for Gutenberg blocks

### ISSUE THREAD

**Issue by tobyw7** [Automattic/jetpack#26279]
### Impacted plugin

Jetpack

### What

Update Cookie and Consent banner to Gutenberg block

### How

The documentation still references the Cookie and Consent banner as being available (see https://jetpack.com/support/extra-sidebar-widgets/cookies-consent-banner/). 

I posted on the support forurm who advised this has not yet been updated. https://wordpress.org/support/topic/cookie-and-consent-banner-on-block-themes/#post-15963247

**Comment by coder-karen** [comment]
Thanks for reaching out about this @tobyw7 !

We're tracking the future of the Cookie and Consent banner in a different GitHub repository ( ref: https://github.com/Automattic/wp-calypso/issues/52100). There are some preliminary discussions but as of yet no implementation plan. 

I'll close this issue as it is being tracked elsewhere however it's helpful having reference of this request here in the Jetpack repository too as it is searchable here, so thanks for taking the time to add this.

I'll also make sure the support page gets edited to be a little more clear that this widget won't currently work on FSE themes such as Twenty Twenty Two.

**Comment by tobyw7** [comment]
Thank you @coder-karen
