### ISSUE TITLE
Backup Plugin: Update UI for connected and disconnected secondary admins in admin page

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#26277]
Follow-up tasks to #26105

* [x] Make sure we don't show links to Cloud for disconnected users
* [x] Make sure we don't show links to Cloud for secondary admins who can't access the cloud dashboard
  ![image](https://user-images.githubusercontent.com/746152/191003739-5db1e139-98f8-43ed-97ba-0357ba3d0f2e.png)

About the progress UI
* [x] Revisit the code to decide if we show the progress UI even when the secondary admins are not owners

**Comment by nunyvega** [comment]
Noting here that I sent a request to the design team so we can get a design for a "connect to wpcom" view without an upgrade prompt. 
Request here:
1199980337313591-as-1203004705036701

**Comment by oskosk** [comment]
Cool, thanks

**Comment by nunyvega** [comment]
About the progress UI:
I can confirm that the progress view is not displayed to non-connected secondary admins:
<img width="1527" alt="Screen Shot 2022-09-22 at 11 56 45" src="https://user-images.githubusercontent.com/16329583/191717631-f872d963-707e-42ea-81ad-0f975b598a69.png">


All tasks are done, closing the issue.
