### ISSUE TITLE
Publicize: simultaneously push to a Facebook Profile Wall and a Facebook Page

### ISSUE THREAD

**Issue by grahamstoney** [Automattic/jetpack#2628]
Jetpack can publish a post to both a Google+ personal page, and a Google+ business page in one hit; but with Facebook you can only publish to your wall or to a Facebook page, not both.

This is discussed in this support forum thread: https://wordpress.org/support/topic/simultaneously-publicize-to-a-facebook-profile-wall-and-facebook-fan-page

The workaround suggested is to create a second Facebook profile, but that violates Facebook's Statement of Rights and Responsibilities (i.e. terms of use). It's one way to get your account disabled. I'd like a technical solution please.

Thanks, Graham

**Comment by dereksmart** [comment]
As of August 1st this year, publishing to facebook profiles via API will no longer be supported by them anyway :( https://developers.facebook.com/docs/graph-api/changelog/breaking-changes/
