### ISSUE TITLE
Tiled Gallery Block: Images resizing when deeply nested in Group blocks

### ISSUE THREAD

**Issue by coder-karen** [Automattic/jetpack#26309]
### Impacted plugin

Jetpack

### Steps to Reproduce

Although I can't reproduce, this issue was originally reported here: https://github.com/Automattic/jetpack/issues/26088
Ungrouping nested Tiled Gallery blocks fixed the issue in that case.

In that case, Tiled Gallery blocks followed image blocks within deeply nested Group blocks (approximately 7 deep in one example of shrinking images). For the images in question, there were dynamically changing height and width variables. It appears that the resizing is taking place in the `tiled-gallery/view.js` file.

This issue may be a quirk of Group blocks rather than Tiled Gallery blocks, but adding this issue as a stub in case it can be reproduced.

This is a screenshot showing how the list view would likely have looked:

<img width="296" alt="Screen Shot 2022-09-21 at 5 05 53 pm" src="https://user-images.githubusercontent.com/16754605/191463843-cc237e02-0bea-4e17-a3e9-9b416d1134bd.png">

### Browser

Google Chrome/Chromium, Mozilla Firefox, Apple Safari

### Reproducibility

Once

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
I tried to reproduce this issue with 7 group blocks, and a couple of images between them, and the images from the Tiled Gallery kept their dimensions: 

| Editor | Front-end |
|---|---|
| ![Image](https://github.com/user-attachments/assets/0389243b-083a-4d2a-ad09-23f6273989e9) | ![Image](https://github.com/user-attachments/assets/1de847c8-84f3-47ae-867d-7e36d7588ea5) |


📌 ACTIONS
- Triaged
- Closed as could not replicate (please reopen if the issue reoccurs)
