### ISSUE TITLE
JS error because of Jetpack calling `setAttribute` on non-existing DOM element

### ISSUE THREAD

**Issue by felixarntz** [Automattic/jetpack#26307]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Use a multisite network.
2. Activate Jetpack network-wide.
3. Go to Plugins screen on one of the sites.
4. See JS error in the console:
```
react-dom.min.js?ver=17.0.1:141 TypeError: Cannot read properties of null (reading 'setAttribute')
    at plugins-page.js?minify=false&ver=0236a4b1a47865236a01:2:55999
```

### A clear and concise description of what you expected to happen.

Jetpack tries to modify some content around its "Deactivate" link in the Plugins list table. It does so without checking whether that link is in fact present though, which results in this error.

The "Deactivate" link is not guaranteed to be present; this is not just an edge case but even something that can happen with WordPress core alone on a multisite (see above). A check should be added in JS to only tweak the DOM element if it was actually found.

### What actually happened

Jetpack JS code assumes that the "Deactivate" link DOM element is always there, while this is not guaranteed.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by coder-karen** [comment]
Thank you @felixarntz for finding and reporting this error, I can replicate it as well.
