### ISSUE TITLE
VideoPress: Fill data based per id on edit page

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#26323]
The single video page doesn't request the initial data in a hard refresh. Find a way to propagate them.

![Image](https://user-images.githubusercontent.com/77539/191575703-f9c6cf65-59ef-434f-a71c-6d9e1694ac8c.png)

**Comment by renatoagds** [comment]
At the current moment, we just get all videos in the `single` video resolver, but we need to be aware of pagination for it, so, we probably need to move this from a control instead of a resolver ...
