### ISSUE TITLE
Subscriber block: Allow editing of placeholder from the editor

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#26377]
Follow-up to #18072

The frontend respects the block attributes, but the block placeholder is not editable from the Editor right now

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/746152/191951929-fb0de6fd-a74c-46e5-b265-94f7f489a33a.png">

<img width="695" alt="image" src="https://user-images.githubusercontent.com/746152/191951957-e5e4bfb7-c087-416a-9d3f-45681b93a99d.png">

Updating by hand from the Code Editor view works, although it warns of a validation. Clicking Attempt Block Recovery works in the end. Seems to be a validation error related to the order of the attributes and the shortcode being rendered, or something like that

**Comment by simison** [comment]
Also important to ensure defaults are consistent between editor & site, currently they're different:

<img width="600" alt="Screenshot 2022-09-27 at 11 32 48" src="https://user-images.githubusercontent.com/87168/192475836-c81645d9-6ab3-4b49-9c77-1387248786ef.png">
<img width="600" alt="Screenshot 2022-09-27 at 11 32 43" src="https://user-images.githubusercontent.com/87168/192475846-7d03e814-c49b-4e21-bc90-dbf91041f46e.png">

**Comment by happychait** [comment]
A customer asked for the ability to customize the placeholder , in 42566521-hc
