### ISSUE TITLE
VideoPress: hide 'add your first video' section when user videos are being fetched

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#26372]
Whenever the VideoPress dashboard is loading, even if the user already uploaded videos, we show the section to upload your first video. 

https://user-images.githubusercontent.com/16329583/191935891-f19c72e0-c0c7-47e9-a811-6c71757d42a6.mov

Hide this section while we are fetching the videos

**Comment by retrofox** [comment]
It'll be fixed when we [expose data in the initial state](https://github.com/Automattic/jetpack/issues/26313).

**Comment by nunyvega** [comment]
fixed in #26313
