### ISSUE TITLE
Action Bar: Move "Manage Subscriptions" options inline

### ISSUE THREAD

**Issue by davemart-in** [Automattic/jetpack#26388]
## Description

We're in the process of redesigning the action bar to make it more engaging. While we're at it, we're making the action bar available to all Jetpack sites in addition to Dotcom sites.

As part of this work, we need to move the manage subscription options for each blog inline.

### Preview

![image](https://user-images.githubusercontent.com/5634774/192009517-1bd22a0a-f83a-4072-bbb1-6ef769753379.png)

**Comment by anomiex** [comment]
Action Bar has been abandoned and removed from the monorepo. See #34939.
