### ISSUE TITLE
Action Bar: Hide comment button when comments are disabled (on site or post)

### ISSUE THREAD

**Issue by davemart-in** [Automattic/jetpack#26386]
## Description

We're in the process of redesigning the action bar to make it more engaging. While we're at it, we're making the action bar available to all Jetpack sites in addition to Dotcom sites.

As part of this work, we need to hide the comment button when comments are disabled.

### Hidden

![image](https://user-images.githubusercontent.com/5634774/192008243-05f182f9-98ef-4d4c-adb0-e37d8e45fd37.png)

### Visible

![image](https://user-images.githubusercontent.com/5634774/192008296-95c33ad2-31d7-4759-941a-1faeb05568d3.png)

**Comment by anomiex** [comment]
Action Bar has been abandoned and removed from the monorepo. See #34939.
