### ISSUE TITLE
Action Bar: Show comment and like counts

### ISSUE THREAD

**Issue by davemart-in** [Automattic/jetpack#26385]
## Description

We're in the process of redesigning the action bar to make it more engaging. While we're at it, we're making the action bar available to all Jetpack sites in addition to Dotcom sites.

As part of this work, we need to include comment and like counts.

### Preview

![CleanShot 2022-09-23 at 12 23 10](https://user-images.githubusercontent.com/5634774/192007581-8c9c51d3-bcae-4fcb-a88f-6127a17c743f.png)

**Comment by eoigal** [comment]
Stashed small bit of work I've done on this at D89937-code

**Comment by anomiex** [comment]
Action Bar has been abandoned and removed from the monorepo. See #34939.
