### ISSUE TITLE
Enhancement: Related Posts dev mode

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#26384]
### Impacted plugin

Jetpack

### What

I would like to see a setting added to related posts to have a preview with dummy data

### How

There is no easy way that I know of to test and style related posts locally, so I would like to see a setting added to display dummy demo data. This data can just live in the plugin or via an API call, and would just be used for the purpose to let theme developers better style related posts. 

For a bonus it might be nice to have an extra setting or randomize it, to deal with different scenarios such as posts without an image.

**Comment by jeherve** [comment]
Thanks for the suggestion. This is currently tracked in #385, so I'll close this issue as duplicate.
