### ISSUE TITLE
Action Bar: Hide like button when likes are disabled (on site or post)

### ISSUE THREAD

**Issue by davemart-in** [Automattic/jetpack#26387]
## Description

We're in the process of redesigning the action bar to make it more engaging. While we're at it, we're making the action bar available to all Jetpack sites in addition to Dotcom sites.

As part of this work, we need to hide the like button when likes are disabled (either on the site or on the individual post)

### Hidden

![image](https://user-images.githubusercontent.com/5634774/192008644-3d3f9ce6-8510-4512-af06-6b5557122d5d.png)

### Showing

![image](https://user-images.githubusercontent.com/5634774/192008692-d8b7de48-4163-4881-948b-011f733a2593.png)

**Comment by anomiex** [comment]
Action Bar has been abandoned and removed from the monorepo. See #34939.
