### ISSUE TITLE
Missing icon and header image

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/jetpack#2639]
I'm switching a family friend over to WP (from the static html site I made them several years back) and I ran into the following issues when connecting to Jetpack:

Missing icon:
<img width="1096" alt="screen shot 2015-08-29 at 11 02 47 am" src="https://cloud.githubusercontent.com/assets/5835847/9562919/3c499e62-4e3f-11e5-94df-33344c3aed2f.png">

Missing header image:
<img width="1060" alt="screen shot 2015-08-29 at 11 06 11 am" src="https://cloud.githubusercontent.com/assets/5835847/9562921/428a8476-4e3f-11e5-86f1-03b4bb8dcf7f.png">

Other info:

- Installed WP via GoDaddy (WordPress 4.3)
- I created a new wp.com username
- I was able to successfully connect
- Using Chrome Version 44.0.2403.157

cc: @jeffgolenski

**Comment by squirk** [comment]
@kellychoffman There's a good chance this is related to a GoDaddy Classic Hosting account, which can be upgraded.  I had a similar issue with accounts not loading SVG files and was able to make some edits to my .htaccess file, but it's still recommended to upgrade.  Have them see if this is the type of account they have as a first step.

**Comment by kellychoffman** [comment]
Yes, the hosting type is indeed `Classic Hosting Linux`. Thanks for the tip.

**Comment by jeffgolenski** [comment]
closing. recognized as a godaddy issue. thank you @squirk + @kellychoffman !
