### ISSUE TITLE
Action Bar: Add persistent "Follow" option to more menu

### ISSUE THREAD

**Issue by davemart-in** [Automattic/jetpack#26393]
## Description

We're in the process of redesigning the action bar to make it more engaging. While we're at it, we're making the action bar available to all Jetpack sites in addition to Dotcom sites.

As part of this work, we need to add a persistent follow button to the more menu when logged in.

### Preview

![CleanShot 2022-09-23 at 12 49 15](https://user-images.githubusercontent.com/5634774/192011943-00ce052a-8aa1-4821-ad50-f6354c492241.png)

**Comment by anomiex** [comment]
Action Bar has been abandoned and removed from the monorepo. See #34939.
