### ISSUE TITLE
Action Bar: If previously followed, hide follow button

### ISSUE THREAD

**Issue by davemart-in** [Automattic/jetpack#26394]
## Description

We're in the process of redesigning the action bar to make it more engaging. While we're at it, we're making the action bar available to all Jetpack sites in addition to Dotcom sites.

As part of this work, we need to hide the follow button once you have followed a site and then reloaded the page. We won't hide it immediately. Just after you reload the page. This will reduce the height of the action bar and prevent people from mistakenly unfollowing a site. We'll also be adding a [persistent follow button under the more menu](https://github.com/Automattic/jetpack/issues/26393).

### Preview

![image](https://user-images.githubusercontent.com/5634774/192012424-24f3db86-ec88-4beb-9669-4ea9bd06e222.png)

**Comment by filipanoscampos** [comment]
I am not sure this is the correct place to share this, and how much of the current text when following/unfollowing will be retained, but we've had a request that may be relevant here.

At the moment, when users follow a website, the text changes to "Following".
A user recently recommended changing the text to "unfollow" to make things clearer.

Kindly let me know if this isn't the best place to share this, and I'll take care of a feature request.
Further context, here pd4QKa-Ed-p2

Thanks!

**Comment by coder-karen** [comment]
@filipanoscampos thanks for sharing the suggestion. For the wording suggestion on all including WordPress.com sites, it looks like there was a generic placeholder issue created here - https://github.com/Automattic/wp-calypso/issues/69995.  Although the Action Bar package work is being added to the Jetpack repository, it may be worth a new issue in wp-calypso if not tagging on to the blank GitHub issue mentioned, as it may mean the feature request may have more developer eyes on it initially.

**Comment by filipanoscampos** [comment]
Thanks, @coder-karen !
I'll work on that.

**Comment by anomiex** [comment]
Action Bar has been abandoned and removed from the monorepo. See #34939.
