### ISSUE TITLE
Action Bar: Congrats screens upon first like, comment, follow

### ISSUE THREAD

**Issue by davemart-in** [Automattic/jetpack#26396]
## Description

We're in the process of redesigning the action bar to make it more engaging. While we're at it, we're making the action bar available to all Jetpack sites in addition to Dotcom sites.

As part of this work, we need to show a celebratory congrats screen the first time you like, comment, or follow. Subsequent likes, comments, and follows will [only show the snack bar notification](https://github.com/Automattic/jetpack/issues/26397).

### Like

![CleanShot 2022-09-23 at 12 54 37](https://user-images.githubusercontent.com/5634774/192012763-273e31c7-6787-4ea4-a7e6-2f056448d255.png)

### Follow

![CleanShot 2022-09-23 at 12 56 16](https://user-images.githubusercontent.com/5634774/192013062-1d81090f-8901-465e-a61c-f50b804e3ad0.png)

### Comment

![CleanShot 2022-09-23 at 12 55 24](https://user-images.githubusercontent.com/5634774/192012908-df18543d-07e4-4c64-afb0-2353fac91855.png)

### Related to

#26397

**Comment by anomiex** [comment]
Action Bar has been abandoned and removed from the monorepo. See #34939.
