### ISSUE TITLE
Action Bar: Ensure keyboard navigation works as expected

### ISSUE THREAD

**Issue by davemart-in** [Automattic/jetpack#26390]
## Description

We're in the process of redesigning the action bar to make it more engaging. While we're at it, we're making the action bar available to all Jetpack sites in addition to Dotcom sites.

As part of this work, we need to make sure that keyboard navigation works as expected.

### Things to watch for

- When modal is open, focus should stay in modal
- All links and buttons should have a visible focus state
- When closing a modal, focus should return to action bar

### Preview

![CleanShot 2022-09-23 at 12 38 06](https://user-images.githubusercontent.com/5634774/192010078-9f53e57b-ea43-4bc4-8f79-d005378b2a06.gif)

**Comment by anomiex** [comment]
Action Bar has been abandoned and removed from the monorepo. See #34939.
