### ISSUE TITLE
Action Bar: Add site-wide show/hide toggle in reading settings

### ISSUE THREAD

**Issue by davemart-in** [Automattic/jetpack#26398]
## Description

We're in the process of redesigning the action bar to make it more engaging. While we're at it, we're making the action bar available to all Jetpack sites in addition to Dotcom sites.

As part of this work, we need to add a reader setting that allows you to toggle the entire action bar on/off across your entire site.

### Preview

![CleanShot 2022-09-23 at 13 07 01](https://user-images.githubusercontent.com/5634774/192014716-86cc1572-75f0-42cb-a04d-8c833cda263f.png)

**Comment by anomiex** [comment]
Action Bar has been abandoned and removed from the monorepo. See #34939.
