### ISSUE TITLE
Action Bar: If previously commented, show commented state

### ISSUE THREAD

**Issue by davemart-in** [Automattic/jetpack#26392]
## Description

We're in the process of redesigning the action bar to make it more engaging. While we're at it, we're making the action bar available to all Jetpack sites in addition to Dotcom sites.

As part of this work, we need to ensure that once you comment on a post, it continues to show as commented on if you refresh the page.

### Preview

![image](https://user-images.githubusercontent.com/5634774/192011563-5575fa11-267b-4a9b-8a49-ebf9156f3a81.png)

**Comment by anomiex** [comment]
Action Bar has been abandoned and removed from the monorepo. See #34939.
