### ISSUE TITLE
Action Bar: Snack bar message on subsequent likes, comments, follows

### ISSUE THREAD

**Issue by davemart-in** [Automattic/jetpack#26397]
## Description

We're in the process of redesigning the action bar to make it more engaging. While we're at it, we're making the action bar available to all Jetpack sites in addition to Dotcom sites.

As part of this work, we need to show a snack bar success message any time someone likes, follows, or comments (assuming it's not their first time, whereupon we'd [show a different success message](https://github.com/Automattic/jetpack/issues/26396)).

Note: This snack bar should hide itself upon click, or automatically within 5 seconds.

### Like

![CleanShot 2022-09-23 at 13 01 49](https://user-images.githubusercontent.com/5634774/192013885-0f86ad9e-34e7-4139-a874-e383d37eb531.gif)

### Follow

![CleanShot 2022-09-23 at 13 02 33](https://user-images.githubusercontent.com/5634774/192013989-8957df2e-79fc-48ac-960e-10e30780851d.gif)

### Comment

![CleanShot 2022-09-23 at 13 03 32](https://user-images.githubusercontent.com/5634774/192014139-faf92d16-4d8a-44e2-a0b9-7de4d2e7a5ab.gif)

### Related to 

#26396

**Comment by anomiex** [comment]
Action Bar has been abandoned and removed from the monorepo. See #34939.
