### ISSUE TITLE
Action Bar: If previously liked, show liked state

### ISSUE THREAD

**Issue by davemart-in** [Automattic/jetpack#26391]
## Description

We're in the process of redesigning the action bar to make it more engaging. While we're at it, we're making the action bar available to all Jetpack sites in addition to Dotcom sites.

As part of this work, we need to ensure that once you like a post, it continues to show as liked if you refresh the page.

### Preview

![image](https://user-images.githubusercontent.com/5634774/192010818-92e6a886-5460-454f-8ca5-b5ef9e3a40ba.png)

**Comment by anomiex** [comment]
Action Bar has been abandoned and removed from the monorepo. See #34939.
