### ISSUE TITLE
Publicize: Conflict with Duplicate Posts plugin

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#264]
Posts created with the Duplicate Post plugin are considered as already published by Publicize, and Publicize is consequently not triggered.
I believe it could be caused by the stored post status copied over from the original post. 

Could we work around this problem for all plugins cloning posts?

Reported here:
http://wordpress.org/support/topic/cloned-posts-also-clones-post-status-trouble-with-jetpack

ported from https://plugins.trac.wordpress.org/ticket/1842

**Comment by kraftbj** [comment]
I haven't heard other reports of this. The third-party plugin's author has a workaround from a year ago: https://wordpress.org/support/topic/cloned-posts-also-clones-post-status-trouble-with-jetpack?replies=7#post-4509286 with promise of adding compat on his end.

Going to close this for now; open to future consideration and collaboration.

**Comment by richardmtl** [comment]
935034-zen :)
