### ISSUE TITLE
Use of undefined constant AUTH_COOKIE

### ISSUE THREAD

**Issue by jaredcobb** [Automattic/jetpack#2640]
It appears that a recent commit here: https://github.com/Automattic/jetpack/commit/e4175cd9d5b950eb35d70f2cbe999539cd13de0b may have introduced a bug. I believe `get_currentuserinfo();` is being called too early.

This bug is pretty easy to reproduce. You can just provision a brand new [VIP Quickstart](https://vip.wordpress.com/documentation/quickstart/#getting-started) environment.

Because xdebug is enabled by default, you will see the following error (also attached a formatted screenshot).  Unfortunately, with xdebug enabled in VIP Quickstart, you can no longer login unless you remove Jetpack: 

( ! ) Notice: Use of undefined constant AUTH_COOKIE - assumed 'AUTH_COOKIE' in /srv/www/wp/wp-includes/pluggable.php on line 801
Call Stack
 	Time	Memory	Function	Location
1	0.0019	151524	{main}( )	../index.php:0
2	0.0041	186548	require_once( '/srv/www/wp/wp-admin/admin.php' )	../index.php:10
3	0.0052	195776	require_once( '/srv/www/wp/wp-load.php' )	../admin.php:31
4	0.0070	207440	require_once( '/srv/www/wp-config.php' )	../wp-load.php:42
5	0.0270	426116	require_once( '/srv/www/wp/wp-settings.php' )	../wp-config.php:102
6	0.3352	9732004	include_once( '/srv/www/wp-content/plugins/jetpack/jetpack.php' )	../wp-settings.php:179
7	0.3921	11373812	require_once( '/srv/www/wp-content/plugins/jetpack/class.jetpack-autoupdate.php' )	../jetpack.php:50
8	0.3921	11373828	Jetpack_Autoupdate::init( )	../class.jetpack-autoupdate.php:282
9	0.3921	11373952	Jetpack_Autoupdate->__construct( )	../class.jetpack-autoupdate.php:28
10	0.3977	11613644	get_currentuserinfo( )	../class.jetpack-autoupdate.php:35
11	0.3977	11613836	apply_filters( )	../pluggable.php:119
12	0.3977	11614612	call_user_func_array ( )	../plugin.php:213
13	0.3977	11614628	wp_validate_auth_cookie( )	../plugin.php:213
14	0.3977	11614772	wp_parse_auth_cookie( )	../pluggable.php:630

![screen shot 2015-08-29 at 3 13 04 pm](https://cloud.githubusercontent.com/assets/329077/9564321/7fb108f4-4e60-11e5-9d17-dc0129063e81.png)

**Comment by dereksmart** [comment]
Thanks for the report @jaredcobb we're working on a patch as we speak :)

**Comment by tazotodua** [comment]
The reason:

You are calling `current_user_can` function too early, till actions are loaded. You should put that function in `init` action:

```
add_action('init', function(){
  if (current_user_can('activate_plugins')) { ..........}
});
```
