### ISSUE TITLE
VideoPress: editing video detail unmounted component warning

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#26429]
* Go to the single video page
* Edit some fields, for instance, the `title`.
* Save the changes
* Go immediately to the dashboard
* Once the video saves, confirm the warning shows up

![Image](https://user-images.githubusercontent.com/77539/192273078-21dbfdad-f490-4bcc-a2d3-65e772db26c0.png)

**Comment by renatoagds** [comment]
Fixed in https://github.com/Automattic/jetpack/pull/26631
