### ISSUE TITLE
VideoPress: expose allowed mime types of the site to the client

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#26468]
Probably, we can get the allowed mime types by using [get_allowed_mime_types()](https://developer.wordpress.org/reference/functions/get_allowed_mime_types/) core function and expose it in [the Initial state global var.](https://github.com/Automattic/jetpack/blob/a0c086638e0018e50d0264ec4312f276d7f3f111/projects/packages/videopress/src/class-admin-ui.php#L124)

**Comment by lhkowalski** [comment]
Today we have a fixed array of allowed video formats here: https://github.com/Automattic/jetpack/blob/trunk/projects/packages/videopress/src/client/state/constants.js#L31

We need to use the `get_allowed_mime_types()` to get this list of extensions from a better (and more maintanable) source of true.

**Comment by lhkowalski** [comment]
`get_allowed_mime_types()` returns a list of extensions and associated mime types ([ref](https://developer.wordpress.org/reference/functions/get_allowed_mime_types/)).

To get a list of possible video extensions, what we need to do is fetch all of them and filter for the `video/*` mimes.
