### ISSUE TITLE
Make simple payment errors from teamcity quieter

### ISSUE THREAD

**Issue by dsas** [Automattic/jetpack#26467]
There are lots of `feature:simple-payments` with an `error_code:SP17` or `error_code:invalid_plan` in the logs. These errors all have a host of *.teamcity* . 

It would be useful to quieten these so that when we're tracking error rates it's not full of false positives. Ideally, we wouldn't log any of the messages being emitted from team city.

The logger is activated from `simple-payments-paypal.php` in wpcom. The logger is defined in `Simple_Payments_Log`

**Comment by dsas** [comment]
We can detect whether TC is running by using `defined( 'ISOLATED_TESTING_ENV' ) && ISOLATED_TESTING_ENV`, we could do similar for `is_sandboxed()`

The tests that are causing the issue are in `SimplePaymentsTest.php`. They are testing that the appropriate plans do/don't get an `invalid_plan` response.

I think that logging to kibana can be useful for debugging tests, so long as we can reliably filter them out for production monitoring. Currently the only way is by looking at the `host` field.

I think ideally, all `log2logstash` should include their environment - production / testing / sandbox for wpcom but currently that's not the case. I think that's a pretty easy change to make in the wpcom `log2logstash` code and will be useful everywhere.

**Comment by mmtr** [comment]
> I think that logging to kibana can be useful for debugging tests

I'm not sure about others, but if I need to debug a test, I usually do it locally (or on my sandbox). I don't need the errors logged in Kibana, since I always use Kibana to debug an actual behavioral error (that happened in either production or a dev environment, but never on a test). So I wonder if we can just avoid logging everything when TC is running which sounds fairly trivial?

**Comment by rcrdortiz** [comment]
> I'm not sure about others, but if I need to debug a test, I usually do it locally (or on my sandbox). I don't need the errors logged in Kibana, since I always use Kibana to debug an actual behavioral error (that happened in either production or a dev environment, but never on a test). So I wonder if we can just avoid logging everything when TC is running which sounds fairly trivial?

I agree with Miguel here, we shouldn't need to rely on logs during tests since we have full control over the execution. Logs are useful for analyzing production errors.

**Comment by BogdanUngureanu** [comment]
I had the impression that when you execute log2logstash on a sandbox the logs are sent to php-errors instead of kibana.

Scratch that, that's just for the Atomic log wrapper.

**Comment by rcrdortiz** [comment]
> So I wonder if we can just avoid logging everything when TC is running which sounds fairly trivial?

> I had the impression that when you execute log2logstash on a sandbox the logs are sent to php-errors instead of kibana.

Not as trivial as it might seem at first glance, the test is actually performing a network request so the endpoint is executed without some constants. 

On the other hand, the `WPCOM_REST_API_V2_Endpoint_Simple_Payments_Paypal` uses a custom logger that isn't test-friendly. Bear in mind this logger also posts the message on the corresponding slack channel, we would need to avoid this too.

We could change the test so that it instantiates the actual API (since we truly believe that the network will work and shouldn't need to test it). If the logger wasn't just a collection of static methods we could easily replace the logger for a different one when testing, but since this isn't an option maybe we could check for test env constants and make the logger bail out if they exist.

**Comment by dsas** [comment]
> I had the impression that when you execute log2logstash on a sandbox the logs are sent to php-errors instead of kibana.

Nope. You can search logstash for host:your.full.sandbox.name and see there are things being logged there via log2logstash.

As you'd expect in a8c there's a real mixture of logging behaviours. Some features log all to elk, some will log sandboxed stuff to a slack channel only, sometimes it varies depending upon the error severity or on other factors like whether you're sandboxing the store.


I must confess I haven't used the kibana logs for debugging test failures either. I have occasionally used it to investigate things on my sandbox. The instrumentation and convenient tooling is already there, so why not use it instead of trying to understand an (often verbose) sandbox log file.



> So I wonder if we can just avoid logging everything when TC is running which sounds fairly trivial?

Absolutely it's trivial, neither option is technically complicated at all. Rather than make a small adjustment to fix our simple-payments problem, I was wondering whether I could make things better for everyone.

**Comment by BogdanUngureanu** [comment]
Maybe we should try to align the behaviour with the Atomic logger?

So we'll need to change \Simple_Payments_Utils::is_sandboxed() to look something like
`( defined( 'WPCOM_SANDBOXED' ) && WPCOM_SANDBOXED ) ||
			( defined( 'MOCK_WP_FUNCTIONS' ) && MOCK_WP_FUNCTIONS );`

And instead of logging directly to log2logstash, maybe we can output it to php-errors?

**Comment by dsas** [comment]
> Maybe we should try to align the behaviour with the Atomic logger?

Why?

**Comment by BogdanUngureanu** [comment]
For one, it'll be a bit more consistent and two, personally I don't see any benefit of logging that error in logstash when running it TC. If I want to debug a test, I'll try to debug it on the sandbox.

**Comment by dsas** [comment]
It'll be consistent with one logger, we have many many more!

What I'll do for now is modify `Simple_Payments_Log` to drop messages when running on teamcity (by checking `ISOLATED_TESTING_ENV`). That solves our immediate problem and is straight-forward to do.

I may pursue logging the environment for all log2logstash calls in 20% time

**Comment by dsas** [comment]
> What I'll do for now is modify Simple_Payments_Log to drop messages when running on teamcity (by checking ISOLATED_TESTING_ENV). That solves our immediate problem and is straight-forward to do.

I've opened D88703-code

**Comment by dsas** [comment]
Deployed r253361-wpcom
