### ISSUE TITLE
VideoPress: polish requesting process in the UI

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#26471]
There are many situations where the app needs to reflect the requesting process to the UI. It requires registering these temporary states in the state and applying the proper styles to the UI:

* Loading media library
* Deleting a video from the media library
* Searching videos
* Filtering videos
* Changing the current page
* Changing video privacy from the media library
* Getting storage used data
* ...

**Comment by retrofox** [comment]
* deleting video: https://github.com/Automattic/jetpack/pull/26506

**Comment by nunyvega** [comment]
I'm leaving this out of milestone 1.0 as it may be too long to tackle it this week next to the other tasks
