### ISSUE TITLE
Publicize: Add StumbleUpon Support

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#265]
Add StumbleUpon as a service for Publicize from user in 1768560-t.

Currently, I can't find an API that we could do into it. Plugins do it currently by a `wp_remote_post` call using the user's credentials saved within the database. I don't like that idea, but fwiw.

**Comment by jkudish** [comment]
StumbleUpon doesn't have an API to do this with. I don't think we'll implement any kind of workaround so marking as closed.
