### ISSUE TITLE
VideoPress: Fetch data for local videos

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#26502]
Fetch local videos, using same API that we use for videopress videos.

**Comment by retrofox** [comment]
pe4Cmx-fL-p2#comment-135

**Comment by lhkowalski** [comment]
As described on the comment linked above, as well as some slack discussion, we found a way to list all the videos using the `/media` endpoint, looking for every media file with `media_type=video`.

To ignore the VideoPress files, we will add a new query string filter `no_videopress`. When present, this filter will force all the returned results to not be a VideoPress file (internally, by making sure all returned results do not have a `videopress_guid` meta key). I will add the PR here as soon as I create it.

So, to request all local videos, we need to do a GET request to `wp-json/wp/v2/media?media_type=video&no_videopress`. The pagination parameters and other usual filters form the `media` endpoint will still work as expected.
