### ISSUE TITLE
VideoPress: Video edit is not persisting empty description

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#26528]
Steps to reproduce:
1 - With at least one uploaded video , go to the VideoPress dashboard
2 - On any video, click `Edit video details`
3 - If the description is empty, add some description and hit `Save`
4 - Back to the video details screen, delete the description and hit `Save`
5 - Check that the empty description is not persisted

**Comment by lhkowalski** [comment]
This applies to the empty `caption` field as well.
