### ISSUE TITLE
VideoPress: Thumbnail update not working on grid/list quick actions

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#26532]
Steps to reproduce:
1 - On the VideoPress dashboard with at least one uploaded video
2 - On the quick actions, click on the first icon (`Update thumbnail`)
3 - Click `Use default thumbnail` or `Select from video`
4 - Check the developer console for an error

Note: those actions work on the edit page.

![Image](https://user-images.githubusercontent.com/8486249/193110529-119f3d80-ec81-4e05-a0c1-c5aedf47f328.png)

**Comment by renatoagds** [comment]
@dhasilva something about use default thumbnail: p1664317174901499-slack-C03TA48NSUX ... maybe we should disable it.
