### ISSUE TITLE
Social Media Icons Widget: enable 'user' as well as 'channel' for YouTube

### ISSUE THREAD

**Issue by donaloflynn** [Automattic/jetpack#2653]
On the social media widget, the option is only available for a YouTube channel
ID not a username. youtube.com/user/username leads to the exact same page as
youtube.com/channel/channelid

The channel ID is unsightly when you hover over the YouTube icon in the widget.
The username looks better.

Simple to implement so please do so promptly.

**Comment by samhotchkiss** [comment]
Hi Donal, this isn't something that is on our roadmap to change, however, we would be happy to accept a pull request that solves this issue from you or anyone else in the community.

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/social-media-icons-jetpack-widget?replies=3&view=all
