### ISSUE TITLE
Jetpack Dashboard “View your site’s backups” Redirects to Jetpack Cloud on Atomic Sites

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/jetpack#26563]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Go to WordPress.com
2. Select your Atomic site in My Site(s)
3. Navigate to Jetpack > Dashboard
4. Click on **View your site’s backups**

### A clear and concise description of what you expected to happen.

I expect to be redirected to https://wordpress.com/backup/exampledomainname.com

### What actually happened

I'm redirected to Jetpack Cloud, which doesn't support Atomic sites:

https://jetpack.com/redirect/?source=my-jetpack-manage-backup&site=exampledomainname.com

### Other information

First reported: p1664559484886309-slack-C03TY6J1A

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Navigate to My Site > Jetpack > Backups.

**Comment by JoshuaGoode** [comment]
More My Jetpack / Cloud additions we may need to adjust or hide on WordPress.com Atomic sites. There are probably more like this, I haven’t checked in the last month or two.

**Comment by kraftbj** [comment]
This comes from projects/plugins/jetpack/_inc/client/at-a-glance/backups.jsx

We can check if it is a WOA site and provide a different target URL. I think that's fine doing on the plugin side. It probably makes sense to see what other ones need to change, at least in that section of the dashboard, whenever updating it.

**Comment by kavyagokul** [comment]
📌 SCRUBBING : RESULT
- Tested on AT - Replicated
- Tested on Self-hosted - Works as expected

📌 ACTIONS
- Marked as Triaged for Quality Squad review


pinging @Automattic/reactor as this only happens on Atomic
