### ISSUE TITLE
Search: Fix redirection for new product purchases

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#26592]
More information: https://github.com/Automattic/jetpack/pull/26573

Redirection after purchasing the new Jetpack Search tiers (both paid and free) is broken, redirecting to https://wordpress.com/admin.php?page=jetpack-search. This is expected for the free tier, but I'm not sure if it is for the paid tier. Note that this is broken for the paid tier before the pricing changes as well.

cc @jsnmoon

**Comment by jsnmoon** [comment]
cc @Automattic/jetpack-origin, who might be able to help us here 🙂
