### ISSUE TITLE
Blueish grey color in the likes column on the Posts screen

### ISSUE THREAD

**Issue by TheJeffr0** [Automattic/jetpack#2659]
Since updating to WordPress 4.3, the likes column on the Posts screen has a bluish grey background color behind the number making it difficult to see. See attached screenshot. 
![jetpacklikescss](https://cloud.githubusercontent.com/assets/6315977/9639901/74762b44-517c-11e5-9cea-0f0ab9ba0a9f.png)

**Comment by TheJeffr0** [comment]
My apologies, I meant WordPress 4.3. I'm getting ahead of myself.

**Comment by kraftbj** [comment]
It'll be resolved when 3.7 is released. 
![screen shot 2015-09-02 at 13 29 32](https://cloud.githubusercontent.com/assets/88897/9640336/bb89d7fc-5176-11e5-8b3c-9ffbbb62638d.png)
