### ISSUE TITLE
VideoPress: delete modal adds an undesired underline to the title

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#26619]
This happens with the current block editor version available in the WordPress app 6.0.2`.

`6.0.2` | Gutenberg trunk
------|------
![Image](https://user-images.githubusercontent.com/77539/193898732-39d71c6a-924a-4541-8800-5a8a7d0dc30f.png) | ![Image](https://user-images.githubusercontent.com/77539/193898777-67d16d33-6ffc-48ab-8881-9030b25096bb.png)

**Comment by dhasilva** [comment]
It seems to be caused by a difference in the version of Gutenberg.
_May be_ related to a change in text alignment on popover items on the video actions.
