### ISSUE TITLE
VideoPress: old thumbnail is showed after update followed by refresh

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#26626]
I am consistently seeing the old poster for a video after I update it to a new frame and refresh the page.

Steps to reproduce:

* Go to `Jetpack > VideoPress` and choose one video as the test subject; remember it's thumbnail (lets call it thumbnail A)
* Click the `Edit video details` for the video
* Click the pencil icon to edit the thumbnail for video, click "Select from video" and then pick a new frame (let's call it thumbnail B)
* Click "Save changes"
* On the library page, thumbnail B is showed (correct behavior)
* Do a page refresh
* The old thumbnail A is back (bug)
* Edit the video details again and set another new frame as the thumbnail (let's call it thumbnail C)
* Click "Save changes"
* On the library page, thumbnail C is showed (correct behavior)
* Do a page refresh
* Now the thumbnail B is finally showed (bug)

This seems to happen no matter how many times I do it:

* when I set thumb B, I see A after the refresh
* when I set thumb C, I see B after the refresh
* when I set thumb D, I see C after the refresh
* and so on

Additional info:

* this seems to happen when I set the thumbnail using the quick actions on the video grid as well
* the thumbnail is wrong just on the VideoPress library; when I include the video on a blog post and check the poster for it, it's the correct one that I just set

**Comment by lhkowalski** [comment]
This may be related to how we save data on the `WPCOM_REST_API_V2_Endpoint_VideoPress::videopress_block_update_poster()` ([code](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/videopress/src/class-wpcom-rest-api-v2-endpoint-videopress.php#L213)) function, without updating the local metadata for the attachment.

**Comment by renatoagds** [comment]
This was already reported in the PR that implemented this feature https://github.com/Automattic/jetpack/pull/26317 ... Thanks for opening a issue for this, forgot to do it.
