### ISSUE TITLE
VideoPress: quick action popover shows disaligned on Chrome

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#26621]
![image](https://user-images.githubusercontent.com/6760046/193907053-b5573e69-b366-41aa-96df-162835ccd2f8.png)

**Comment by lhkowalski** [comment]
I am closing this because it seems solved by now.

**Comment by lhkowalski** [comment]
Reopening because we found a scenario where it's possible to reproduce the issue consistently:

* launch a new JN site
* check it using Chrome

This could be related to the specific versions that are being launched on JN.

**Comment by dhasilva** [comment]
The issue happens when deactivating Gutenberg. On Firefox it happens as well, but not as the screenshot shows. The whole popover moves down.
