### ISSUE TITLE
Not connected Jetpack site gets stats error. 

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#2662]
See
![image](https://cloud.githubusercontent.com/assets/115071/9648311/1e2a5bb4-519c-11e5-8d9e-ff3eeb3f79c2.png)

This site is part of a WP network that is has jetpack network activated

**Comment by kraftbj** [comment]
I couldn't duplicate this. My setup
0. Multisite (subdomain), multinetwork. On site_id=1, JP network activated. Via NA->Jetpack->Sites, not all sites are connected.
1. Visit dashboard of unconnected site.
2. Widget prompts to connect, no stats area visible.

**Comment by enejb** [comment]
I disconnected the site via .com not sure if it has anything to do with it.

**Comment by kraftbj** [comment]
Duplicated. A previously connected site (first glance happens both with remote wp.com disconnect and local). Confirmed it did not happen on a single site.

**Comment by kraftbj** [comment]
Actually narrowed it down more, it's a corner case with the Protect changes to ensure they work network-wide.

To duplicate:
0. Have JP Network Activated.
1. Have Protect enabled on the main site.
2. Have a subsite previously connected, but not currently.

**Comment by jeherve** [comment]
This doesn't seem to be happening anymore on my end. Let's close for now, we can always reopen later if necessary.
