### ISSUE TITLE
Admin page: QR code to download Jetpack app should point to `jetpack.com/app` in assistant summary page

### ISSUE THREAD

**Issue by fluiddot** [Automattic/jetpack#26657]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Start with a site that's connected to WordPress.com (e.g. Jurassic Ninja site with Jetpack connected).
2. Go to `/wp-admin/admin.php?page=jetpack#/recommendations/summary` on desktop.
**NOTE:** _On mobile devices, the link is replaced with the App store download button._
3. Depending on the Jetpack plan, a different download app banner will show up.

Free plan|Jetpack Security plan / Jetpack Backup plan
--|--
<img width="1007" alt="Screenshot 2022-10-06 at 10 31 52" src="https://user-images.githubusercontent.com/14905380/194263054-31c906cd-af39-4260-b54f-a14703c87966.png">|<img width="438" alt="Screenshot 2022-10-06 at 10 32 11" src="https://user-images.githubusercontent.com/14905380/194263197-6d309b9c-f612-4405-b023-2e3e7cb19c6b.png">

4. Scan the QR code displayed in the download app banner with a phone.
5. Observe that it redirects to `jetpack.com/mobile` instead of the App Store (if using an iOS device) or Google Play Store (if using an Android device).

### A clear and concise description of what you expected to happen.

The QR code should redirect the user to the App Store (if using an iOS device) or Google Play Store (if using an Android device) to download the app.

### What actually happened

The QR code redirects to the `jetpack.com/mobile` page. This adds an extra step for the user to download the app.

### Browser

Google Chrome/Chromium

### Platform (Simple, Atomic, or both?)

Self-hosted

### Reproducibility

Consistent

### Severity

All

**Comment by jeherve** [comment]
To clarify, the link should remain `jetpack.com/mobile`, but the QR code should lead to `jetpack.com/app`? Is that the expected behavior?

**Comment by fluiddot** [comment]
> To clarify, the link should remain `jetpack.com/mobile`, but the QR code should lead to `jetpack.com/app`? Is that the expected behavior?

Nope, both elements should point to the same URL. The link should be `jetpack.com/app` and the QR should lead to the same URL `jetpack.com/app`. Sorry for the confusion 🙇 .

To give more context, this change is related to an update we made in the Get Apps card ([reference](https://github.com/Automattic/jetpack/pull/26276)):
<img width="1204" alt="Screenshot 2022-10-06 at 15 24 07" src="https://user-images.githubusercontent.com/2998162/194338768-4c30b74e-3a0f-4cc8-be5a-0f080c2fbf1b.png">
