### ISSUE TITLE
VideoPress: poster is not accessible for private videos

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#26675]
When the video changes its privacy to `private`, the poster is not accessible from the app, even when the user is logged in:

![Image](https://user-images.githubusercontent.com/77539/194394289-3c7c8a15-958b-4077-97e7-ec003ca48a8d.png)

![Image](https://user-images.githubusercontent.com/77539/194394325-73dd1c42-f287-424d-88f3-42cf7813ad7e.png)

**Comment by lhkowalski** [comment]
I am trying to find a reliable way to reproduce the issue. Things that I discovered so far:

* the thumb can be loaded if we provide a valid `metadata_token` with the request
* the broken thumb also breaks the "Select thumbnail from video" feature

**Comment by lhkowalski** [comment]
Ok, just setting the privacy to "Private" is enough to make the thumb go away, using Firefox as the test browser. On Chrome it's more tricky, may be related to some caching or something, so I will focus on testing using Firefox and when I find a solution (if any), I will validate it on Chrome as well.

**Comment by lhkowalski** [comment]
The behavior on the WPCOM media library for the private video thumbnails is to show just a placeholder: 

![image](https://user-images.githubusercontent.com/6760046/195943867-c9d1e6f3-135c-4cb7-bc6a-86aa6af1b804.png)

The first alternative that we have here is to show a "private video" placeholder inside VideoPress media, in the case we can't solve the access to the thumbs.

**Comment by lhkowalski** [comment]
To solve the problem inside the details page, we can rely on generating a `metadata_token` (actually, a VideoPress playback token) and after this be able to load the poster image.

The `metadata_token` is linked to a single video (we send the video GUID when generating the token), so we can't reuse the same for every private video. If we detect the private videos on the grid/list, we can apply this `metadata_token` solution there as well.

**Comment by lhkowalski** [comment]
On the first iteration of the solution, we will:

* [x] work on a better placeholder image for the private videos, with a camera icon the way Calypso does
   * #26898
* [ ] solve the thumbnail issue on the details page, so when we edit the video details all the features work as expected, using a `metadata_token` on the image request
   * this will have some phases:
   * [x] expose an endpoint to generate playback tokens
      * #26974  
   * [x] change the client to fetch playback tokens and use it (researched it, tried three ways and finally got a working implementation using reducers and the local state, will organize the code and then prepare a PR)
      * #26996 
   * expire stored playback tokens when they are near it's expiry time (moved to next release #27070)
