### ISSUE TITLE
need a way to disable function minileven_content_nav from executing

### ISSUE THREAD

**Issue by Frumph** [Automattic/jetpack#2669]
file:  modules/minileven/theme/pub/minileven/inc/template-tags.php

`function minileven_content_nav( $nav_id ) {`

if it outputted as a filter or action I would be able to disable it, but it's a straight function call at location  so cannot be modified or edited outside source

**Comment by georgestephanis** [comment]
How about a class added to the output that you can add css to hide it by?

**Comment by Frumph** [comment]
Good thinking,    `body.single-post-type  #nav-single { display: hidden; }`  will indeed work

**Comment by Frumph** [comment]
well it actually didn't from the navstyle ;/ going to need to figure that one out
