### ISSUE TITLE
Upgrade Triggers: Add Two & Three month warnings

### ISSUE THREAD

**Issue by a8ck3n** [Automattic/jetpack#26692]
Feedback from @jsnmoon in #26656.

We'll also need to add the two months and three months warnings.

<img width="638" alt="image" src="https://user-images.githubusercontent.com/4044428/194396018-5e33fc37-fd78-42e5-bb45-e910ba2be6e5.png">

<img width="641" alt="image" src="https://user-images.githubusercontent.com/4044428/194396058-1048cbe1-b958-4c18-b8d7-da7e5ddadb7f.png">

**Comment by a8ck3n** [comment]
Do we need to have variants of this message for both records and requests? @jsnmoon 

Thanks!

**Comment by jsnmoon** [comment]
Correct, there are variants for both records and requests. I've linked the source Figma file in a Slack thread 🙂
