### ISSUE TITLE
General: Private site notice hard to read

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#2671]
I just came across this in Jetpack. I am not sure why it is even showing up since there is nothing in my site that I would want it to be private. 

I found it really hard to read ( the green on green text ) also I am not sure it even make sense. 
![image](https://cloud.githubusercontent.com/assets/115071/9670719/ab05c3ec-5242-11e5-8ae8-e7dda0c3ebf8.png)

**Comment by kraftbj** [comment]
> I am not sure why it is even showing up since there is nothing in my site that I would want it to be private.

The check is, basically, based on if wp.com can read your site's RSS feed.

**Comment by jeffgolenski** [comment]
@justinkropp Can you take a look at this?

**Comment by justinkropp** [comment]
@jeffgolenski How do I recreate this? From what I can tell just looking at the above screenshot, I would venture to guess that the text  (and icon) have been set at a reduced opacity, making them difficult to read. Changing that opacity should fix the readability issue.

But I agree with @enejb, the content of the actual message doesn't really make a lot of sense. I had to read it a couple times to _kinda_ understand it.

**Comment by jeffgolenski** [comment]
This issues becomes irrelevant for 4.1 - global notices will be restyled to match wpcom. cc @dereksmart
