### ISSUE TITLE
Subscription Widget's title is not wrapped in any html markup

### ISSUE THREAD

**Issue by Kenshino** [Automattic/jetpack#2673]
Hello,

The output of the subscriptions widget doesn't wrap the title output in any html tags. So the title just outputs as a line inside a list item

This makes targeting it with css ambigious.

In subscriptions.php line 608

````
if( ! empty( $instance['title'] ) ) {
			echo $args['before_title'] . esc_attr( $instance['title'] ) . $args['after_title'] . "\n";
		}
````

There is a before title argument but is never instantiated with a default nor is there a filter for me to override that.

Is this something forgotten?

**Comment by jeherve** [comment]
Both `$args['before_title']` and `$args['after_title']` are parameters defined by your theme, and are then given as the first argument provided to the widget method here:
https://github.com/Automattic/jetpack/blob/3.6.1/modules/subscriptions.php#L570

Here is how it's done in Twenty Fifteen, for example:
https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentyfifteen/functions.php#L138

You can read more about it here:
https://codex.wordpress.org/Function_Reference/register_sidebar#Parameters
https://codex.wordpress.org/Widgets_API

I hope this helps.

**Comment by Kenshino** [comment]
Dear @jeherve 

Thanks! I have no idea why I missed something so elementary!

Cheers!
