### ISSUE TITLE
Payment buttons: inconsistent button size between editor and front-end

### ISSUE THREAD

**Issue by adimoldovan** [Automattic/jetpack#26748]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Add 2 payment buttons.
2. Update the size in the right setting panel. Make one Extra small and one Normal.
3. Select the payment buttons block and change the size to Extra small. 
4. Save page and check it in frontend.

### A clear and concise description of what you expected to happen.

Buttons have the selected sizes. One extra small and one normal.

### What actually happened

Buttons have the same size in the front end, but different size (as expected) in the editor.

### Browser

Google Chrome/Chromium

### Other information

<img width="931" alt="editor" src="https://user-images.githubusercontent.com/3854374/195073641-22a6db53-84e2-43b6-87af-88bc872a2863.png">
<img width="927" alt="frontend" src="https://user-images.githubusercontent.com/3854374/195073655-6fc6e63f-d798-418c-9d58-cb88d7ed3313.png">

### Reproducibility

Consistent

**Comment by adimoldovan** [comment]
Related to #26580

**Comment by sdixon194** [comment]
cc @dsas

**Comment by dsas** [comment]
@adimoldovan I can't reproduce this in firefox or chrome, could you provide me with a bit more info please? 

 1. Can you provide access to the test site so I can see? Or:
 2. Could you share the code for your post content? 
 3. Can you confirm that it's the 2021 theme you're working on?
 4. Can you confirm the computed font-size for each of the a.wp-block-button__link ?
 5. What is your test environment? Is it wpcom, atomic or something else?
 6. What is the version of WordPress? If you're using the Gutenberg plugin, what version of that are you using?

Here is a video of it working for me on JN using WP 6.0.2

https://user-images.githubusercontent.com/93301/195165811-e3074a8a-dfaa-4c3b-bd7d-26070ac16051.mp4

Here is my post content:

```
<!-- wp:jetpack/payment-buttons -->
<div class="wp-block-jetpack-payment-buttons"><!-- wp:jetpack/recurring-payments {"planId":9,"url":"https://mute-chimuelo.jurassic.ninja/2022/10/11/5/?recurring_payments=9","uniqueId":"recurring-payments-9"} -->
<div class="wp-block-jetpack-recurring-payments"><!-- wp:jetpack/button {"element":"a","uniqueId":"recurring-payments-9","passthroughAttributes":{"uniqueId":"uniqueId","url":"url"},"text":"Xs","url":"https://mute-chimuelo.jurassic.ninja/2022/10/11/5/?recurring_payments=9","fontSize":"extra-small"} /--></div>
<!-- /wp:jetpack/recurring-payments -->

<!-- wp:jetpack/recurring-payments {"planId":9,"url":"https://mute-chimuelo.jurassic.ninja/2022/10/11/5/?recurring_payments=9","uniqueId":"recurring-payments-9"} -->
<div class="wp-block-jetpack-recurring-payments"><!-- wp:jetpack/button {"element":"a","uniqueId":"recurring-payments-9","passthroughAttributes":{"uniqueId":"uniqueId","url":"url"},"text":"Normal","url":"https://mute-chimuelo.jurassic.ninja/2022/10/11/5/?recurring_payments=9"} /--></div>
<!-- /wp:jetpack/recurring-payments --></div>
<!-- /wp:jetpack/payment-buttons -->
```

**Comment by dsas** [comment]
Oh, I see where I was going wrong as soon as I hit comment, I can reproduce it now and will look at what's going on.
