### ISSUE TITLE
My Jetpack: Update Search Purchase page to handle the pricing update

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#26767]
Location: /wp-admin/admin.php?page=my-jetpack#/add-search
Linked from: My Jetpack —  /wp-admin/admin.php?page=my-jetpack#/

This also resolves the issue of not being able to purchase Jetpack Search when only the Jetpack plugin is installed. Without the Search plugin, the Search Dashboard link on the wp-admin sidebar is not accessible.

**Comment by kangzj** [comment]
To add more information, this also happens with any of our standalone plugins with 'My Jetpack' integrated.

And for Jetpack the plugin specifically, there's another product upsell page which might need to be updated - #26805
