### ISSUE TITLE
Jetpack Social Preview does not render & properly

### ISSUE THREAD

**Issue by devNigel** [Automattic/jetpack#26760]
### Quick summary

The Jetpack Social Preview does not render & symbol properly in Simple sites. It works fine on Atomic Sites. 

### Steps to reproduce

1. Open a simple site and create a new post or page.
2. Add & symbol in the title.
3. Check Jetpack Social Preview

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/33957570/194459816-34843450-cad7-425b-9c2b-ea15625f5159.png">

<img width="903" alt="image" src="https://user-images.githubusercontent.com/33957570/194459842-0cc13a94-9218-4df8-b8b5-68c709e659d2.png">

### What you expected to happen

Social Preview should render & symbol correctly.

### What actually happened

Social Preview rendered & symbol as `&amp;`

### Context

User report: 24756386-hc

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

No

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT 
- Tested on Simple: **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated issue as described. 
- Before publishing the post, when I checked Jetpack Social Preview, the `&` rendered in the title, but not in the content of the post. 
- After publishing the post, the `&` was not rendered in either place. 

*Example: Before Publishing*
![Markup on 2022-10-11 at 10:11:03](https://user-images.githubusercontent.com/27249804/195156999-ec189174-319e-4b20-ad6d-a93ce1f833d1.png)

*Example: After Publishing*
![Markup on 2022-10-11 at 10:12:18](https://user-images.githubusercontent.com/27249804/195157027-d5ce12f5-c3de-4860-9a96-a3f19bafdd66.png)

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by coder-karen** [comment]
Pinging @Automattic/jetpack-reach for this one.

**Comment by sixhours** [comment]
This is an issue with core escaping special characters in the post attributes. I've traced it back to `getEditedPostAttribute` in the plugin, which accesses a core data store; example code for the title:

https://github.com/Automattic/jetpack/blob/5655e5e419c021d216f27382e4df82af979669cc/projects/js-packages/publicize-components/src/components/social-previews/use-post-data.js#L65-L66

If you use the Jetpack advanced SEO tools, the copy doesn't escape the `&`, but if we fall back to core's title/description, it will. Examples:

With Jetpack's advanced SEO title/description set:

![Image](https://github.com/user-attachments/assets/0ca39816-ffa6-4ecf-9f70-594b2d16ba19)

Fallback to core title/description:

![Image](https://github.com/user-attachments/assets/057c96a4-b7eb-44a3-9db6-0a79c1172d12)

It likely needs to be addressed in core, or we need to decode special characters on the Jetpack side explicitly.
