### ISSUE TITLE
De-Fusion: Endpoints M-T

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#26774]
### Impacted plugin

Jetpack

### What

API Endpoints

### How

```
"$plugin_root/json-endpoints/$endpoint" => "$wpcom_root/public.api/rest/json-endpoints/$endpoint";
```
The endpoints:

```
	"class.wpcom-json-api-menus-v1-1-endpoint.php",
	"class.wpcom-json-api-post-endpoint.php",
	"class.wpcom-json-api-post-v1-1-endpoint.php",
	"class.wpcom-json-api-render-embed-endpoint.php",
	"class.wpcom-json-api-render-embed-reversal-endpoint.php",
	"class.wpcom-json-api-render-endpoint.php",
	"class.wpcom-json-api-render-shortcode-endpoint.php",
	"class.wpcom-json-api-sharing-buttons-endpoint.php",
	"class.wpcom-json-api-site-settings-endpoint.php",
	"class.wpcom-json-api-site-settings-v1-2-endpoint.php",
	"class.wpcom-json-api-site-settings-v1-3-endpoint.php",
	"class.wpcom-json-api-site-settings-v1-4-endpoint.php",
	"class.wpcom-json-api-site-user-endpoint.php",
	"class.wpcom-json-api-taxonomy-endpoint.php",
```

**Comment by sdixon194** [comment]
EDIT - looks like everything is in Sync now, proceeding to defusion with stubs.

Out of sync (needs investigation)

```
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-site-settings-endpoint.php
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-site-settings-v1-2-endpoint.php
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-site-settings-v1-3-endpoint.php
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-site-settings-v1-4-endpoint.php
```

**Comment by anomiex** [comment]
> projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-render-endpoint.php

Looks like D59313-code was never copied to Jetpack.

> projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-site-settings-endpoint.php
> projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-site-settings-v1-2-endpoint.php
> projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-site-settings-v1-3-endpoint.php
> projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-site-settings-v1-4-endpoint.php

These seem like they should be grouped with class.wpcom-json-api-get-site-endpoint.php.

Also of note is that D18449-code was supposed to make Fusioning easier, but at least the part touching these files never made it back into Jetpack.

**Comment by anomiex** [comment]
> Looks like D59313-code was never copied to Jetpack.

https://github.com/Automattic/jetpack/pull/26893

**Comment by sdixon194** [comment]
One diff with stubs: D91461-code

I think some test needs to be adjusted. It's failing with:

```
DocumentationEndpointHelperTest

[19:58:16 ](https://teamcity.a8c.com/buildConfiguration/ParallelPatchGit_TemplateRunner0/8928783?buildTab=log&focusLine=19013&logView=flowAware&logFilter=err&linesState=19013)
      test_get_file_name

[19:58:16 ](https://teamcity.a8c.com/buildConfiguration/ParallelPatchGit_TemplateRunner0/8928783?buildTab=log&focusLine=19015&logView=flowAware&logFilter=err&linesState=19015)
        Failed asserting that '/home/teamcity-0/buildAgent/work/work_build-D03-33-dfw-0_git/trunk/wp-content/mu-plugins/jetpack-plugin/production/json-endpoints/class.wpcom-json-api-render-embed-endpoint.php' contains "public.api/rest/json-endpoints/class.wpcom-json-api-render-embed-endpoint.php".

[19:58:16 ](https://teamcity.a8c.com/buildConfiguration/ParallelPatchGit_TemplateRunner0/8928783?buildTab=log&focusLine=19016&logView=flowAware&logFilter=err&linesState=19016)
         /home/teamcity-0/buildAgent/work/work_build-D03-33-dfw-0_git/trunk/bin/tests/isolated/suites/Documentation/EndpointHelperTest.php:68```

**Comment by anomiex** [comment]
Yeah. Middle one is reading the stub file and failing to extract stuff from it, works if we point it at the de-Fusioned file instead. Other two are comparing the file path it gets back from something and failing because the test looks for the Fusioned path while it's getting the Jetpack path now.

**Comment by anomiex** [comment]
Fixed the diff.

Also this will have to wait for 11.6-a.1 to pick up #27059 and #27116.

**Comment by sdixon194** [comment]
Deployed in r255823-wpcom
