### ISSUE TITLE
De-Fusion: Endpoints L

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#26773]
### Impacted plugin

Jetpack

### What

API Endpoints

### How

```
"$plugin_root/json-endpoints/$endpoint" => "$wpcom_root/public.api/rest/json-endpoints/$endpoint";
```
The endpoints: 
```
	"class.wpcom-json-api-list-comments-endpoint.php",
	"class.wpcom-json-api-list-embeds-endpoint.php",
	"class.wpcom-json-api-list-media-endpoint.php",
	"class.wpcom-json-api-list-media-v1-1-endpoint.php",
	"class.wpcom-json-api-list-media-v1-2-endpoint.php",
	"class.wpcom-json-api-list-posts-endpoint.php",
	"class.wpcom-json-api-list-posts-v1-1-endpoint.php",
	"class.wpcom-json-api-list-posts-v1-2-endpoint.php",
	"class.wpcom-json-api-list-post-types-endpoint.php",
	"class.wpcom-json-api-list-post-type-taxonomies-endpoint.php",
	"class.wpcom-json-api-list-roles-endpoint.php",
	"class.wpcom-json-api-list-shortcodes-endpoint.php",
	"class.wpcom-json-api-list-terms-endpoint.php",
	"class.wpcom-json-api-list-users-endpoint.php",
```

**Comment by sdixon194** [comment]
Out of sync (needs investigation)

```
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-list-post-types-endpoint.php
```

**Comment by anomiex** [comment]
> class.wpcom-json-api-list-media-v1-2-endpoint.php

Another one that's the same situation as class.wpcom-json-api-edit-media-v1-2-endpoint.php as described in https://github.com/Automattic/jetpack/issues/25255#issuecomment-1279351845.

> projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-list-post-types-endpoint.php

The desync is due to D17161-code not making it into Jetpack.

**Comment by anomiex** [comment]
> The desync is due to D17161-code not making it into Jetpack.

Took a closer look at that one, and it looks like it only mostly works on wpcom Simple. It'll fail for anything that's not in the "default" textdomain, and it'll probably get the wrong translation for anything that uses `_x()` instead of `__()` too.

But maybe this only makes sense for wpcom Simple anyway. That "rest_api_localize_response" filter doesn't seem to exist anywhere else, and the code I see calling it on wpcom seems very wpcom-specific.

**Comment by anomiex** [comment]
Syncing Media endpoints is D90466-code and D90467-code.

**Comment by sdixon194** [comment]
One diff for the stubs: D90689-code

**Comment by sdixon194** [comment]
r255181-wpcom
