### ISSUE TITLE
De-Fusion: Endpoints U-Z

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#26775]
### Impacted plugin

Jetpack

### What

API Endpoints

### How

```
"$plugin_root/json-endpoints/$endpoint" => "$wpcom_root/public.api/rest/json-endpoints/$endpoint";
```

The endpoints:
```
	"class.wpcom-json-api-update-comment-endpoint.php",
	"class.wpcom-json-api-update-customcss.php",
	"class.wpcom-json-api-update-media-endpoint.php",
	"class.wpcom-json-api-update-media-v1-1-endpoint.php",
	"class.wpcom-json-api-update-post-endpoint.php",
	"class.wpcom-json-api-update-post-v1-1-endpoint.php",
	"class.wpcom-json-api-update-post-v1-2-endpoint.php",
	"class.wpcom-json-api-update-site-homepage-endpoint.php",
	"class.wpcom-json-api-update-site-logo-endpoint.php",
	"class.wpcom-json-api-update-taxonomy-endpoint.php",
	"class.wpcom-json-api-update-term-endpoint.php",
	"class.wpcom-json-api-update-user-endpoint.php",
	"class.wpcom-json-api-upload-media-endpoint.php",
	"class.wpcom-json-api-upload-media-v1-1-endpoint.php",
```

**Comment by sdixon194** [comment]
Out of sync (needs investigation)

```
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-upload-media-v1-1-endpoint.php
```

**Comment by anomiex** [comment]
> projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-upload-media-v1-1-endpoint.php

Can we kick this one over to the team that has been working on VideoPress?

But if not, it looks like it shouldn't be too hard to deal with.
* The `use` and `require` added seem unused. Probably whatever was added using them later got removed.
* There's a block guarded by a check for `VIDEOPRESS_JETPACK_VIDEO_ENABLED`, which doesn't appear anywhere in Jetpack. Could just leave it on the assumption that anyone defining it gets what they deserve, or could add `IS_WPCOM` checks to it too.
* There's adding and removing a filter with a function that doesn't exist. Could wrap both in `if ( function_exists() )` checks.
* And the last block already has an `IS_WPCOM` check.

**Comment by sdixon194** [comment]
Took a try and just getting things in sync myself: https://github.com/Automattic/jetpack/pull/27004

**Comment by sdixon194** [comment]
One update diff: D91577-code

**Comment by anomiex** [comment]
Looks good. Double-checked that the upload media endpoint actually worked, and it seemed to.

**Comment by sdixon194** [comment]
Deployed in r255765-wpcom
