### ISSUE TITLE
De-fusion: Endpoints: G

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#26772]
### Impacted plugin

Jetpack

### What

API Endpoints

### How

```
"$plugin_root/json-endpoints/$endpoint" => "$wpcom_root/public.api/rest/json-endpoints/$endpoint";
```
The Endpoint:

```	
	"class.wpcom-json-api-get-autosave-v1-1-endpoint.php",
	"class.wpcom-json-api-get-comment-endpoint.php",
	"class.wpcom-json-api-get-comment-counts-endpoint.php",
	"class.wpcom-json-api-get-comments-tree-endpoint.php",
	"class.wpcom-json-api-get-comment-history-endpoint.php",
	"class.wpcom-json-api-get-customcss.php",
	"class.wpcom-json-api-get-media-endpoint.php",
	"class.wpcom-json-api-get-media-v1-1-endpoint.php",
	"class.wpcom-json-api-get-media-v1-2-endpoint.php",
	"class.wpcom-json-api-get-post-counts-v1-1-endpoint.php",
	"class.wpcom-json-api-get-post-endpoint.php",
	"class.wpcom-json-api-get-post-v1-1-endpoint.php",
	"class.wpcom-json-api-get-site-endpoint.php",
	"class.wpcom-json-api-get-site-v1-2-endpoint.php",
	"class.wpcom-json-api-get-taxonomies-endpoint.php",
	"class.wpcom-json-api-get-taxonomy-endpoint.php",
	"class.wpcom-json-api-get-term-endpoint.php",
```

**Comment by sdixon194** [comment]
EDIT:
- projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-site-v1-2-endpoint.php is out of sync because it uses `jetpack_require_lib` instead of `require_lib` - I think we can defusion this as normal
- class.wpcom-json-api-get-media-v1-2-endpoint.php needs to be defusioned similar to class.wpcom-json-api-edit-media-v1-2-endpoint.php as described in https://github.com/Automattic/jetpack/issues/25255#issuecomment-1279351845.

----
Old.

Out of sync (needs investigation)

```
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-site-endpoint.php
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-site-v1-2-endpoint.php
```

Fusion doesn't think is on wpcom, but it seems to be, have to check manually:

```
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-comments-tree-v1-1-endpoint.php
projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-comments-tree-v1-2-endpoint.php
```

**Comment by anomiex** [comment]
> projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-autosave-v1-1-endpoint.php

Confirmed, just phpcs stuff. Specifically, D58564-code.

> class.wpcom-json-api-get-media-v1-2-endpoint.php

You don't have this one listed, but it's the same situation as class.wpcom-json-api-edit-media-v1-2-endpoint.php as described in https://github.com/Automattic/jetpack/issues/25255#issuecomment-1279351845.

> projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-site-endpoint.php
> projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-site-v1-2-endpoint.php

These have a bunch of additions on wpcom, and one removal (D74811-code). I have no idea if any of the changes there are wpcom-specific or if we should go ahead and apply them all to Jetpack.

Just checking the functions called, the cases for "is_pending_plan", "launchpad_screen", and "launchpad_checklist_tasks_statuses" call functions that don't exist in Jetpack's version of the `SAL_Site` class. Chances are those would want to be added with a default implementation returning some sort of false or empty value, as is already done in several other cases.

> projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-comments-tree-v1-1-endpoint.php
> projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-comments-tree-v1-2-endpoint.php

Just phpcs differences anyway. May as well de-Fusion them even though they weren't actually in Fusion.

**Comment by anomiex** [comment]
Landed D58564-code, so class.wpcom-json-api-get-autosave-v1-1-endpoint.php is in sync now.

**Comment by anomiex** [comment]
Syncing Media endpoints is D90466-code and D90467-code.

**Comment by sdixon194** [comment]
> class.wpcom-json-api-get-media-v1-2-endpoint.php

Is this now the same situation where we wait for 11.6-a.1 to land and can defuse as normal?

**Comment by sdixon194** [comment]
Diff to defusion everything as normal here, might need to wait for after 11.6-a.1? D91479-code

**Comment by anomiex** [comment]
No, that one was good after D90466-code.

**Comment by anomiex** [comment]
Seems to work, let's do it :ship:

**Comment by anomiex** [comment]
Media endpoint was fine, but it looks like this one needs to wait for 11.6-a.1 to pick up #27059 for the site endpoints.

**Comment by sdixon194** [comment]
Deployed in r255829-wpcom
