### ISSUE TITLE
Verify the "logged-in" cookie generated with subscriptions is correct.

### ISSUE THREAD

**Issue by n3f** [Automattic/jetpack#26842]
### Impacted plugin

Jetpack

### Steps to Reproduce

Create a subscription and verify that the forwarded url sets the appropriate cookie and that all permissions are allowed.

### Reproducibility

Intermittent

**Comment by n3f** [comment]
@artpi, In my testing I'm seeing that the cookie doesn't seem to get applied.  That is after I checkout I can't access https://wordpress.com/me/purchases without getting a new log-in link.

Is the correct behavior such that after checking out, a new cookie for wordpress.com is set so that the user can access that page (or a similar one)?

**Comment by n3f** [comment]
Looks like Artur created a p2 to discuss what the scenarios should be, closing this for now.

pbOQVh-2wm-p2

**Comment by artpi** [comment]
I am talking about this cookie
https://github.com/Automattic/jetpack/blob/b313bd253afdf919adf7a71a866d0ab85b3a7bda/projects/plugins/jetpack/extensions/blocks/premium-content/view.js#L2

This cookie is supposed to store the JWT token generated as part of the checkout / login of newsletter / memberships for future use

**Comment by n3f** [comment]
Also double-check that site-blah.wordpress.com is appropriately responding to that same cookie...

**Comment by n3f** [comment]
- [x] Cookie generated/stored after checkout.
- [x] Cookie generated/stored after login.
- [x] (Fixed by #27282) Site appropriately responds to the same cookie.

Methodology:

1. Added a `debugger;` line to the memberships.js file then verified after checkout that the code was being called and that the token was set with the correct value.
2. Using the same `debugger;` line checked after the login process.
3. Using xdebug verified that the `visitor_can_view_content` processed the token correctly.

**Comment by artpi** [comment]
Looks like this is done!
