### ISSUE TITLE
Jetpack: Contact Form - Update block icon

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#26865]
Current icon

![Image](https://user-images.githubusercontent.com/746152/196156096-c39f8476-54ed-447b-b92e-cc1466025f72.png)

**Comment by CGastrell** [comment]
Do we have an icon "candidate" for this one @digitalwaveride ?

**Comment by digitalwaveride** [comment]
Here is the latest candidate: 

https://www.figma.com/file/HFUS7nx3iQuNZcc61P0jJL/Jetpack-Forms?node-id=2807%3A5575



![Image](https://user-images.githubusercontent.com/5120357/197257813-032bdfe5-e9cc-466c-8b4b-2ec7be7c4c7c.png)

**Comment by CGastrell** [comment]
I'm not sure I exported the right way, I got this on the icon:

![Image](https://user-images.githubusercontent.com/157240/197279754-59a12adb-416f-4fca-a166-0a494e5c2ddf.png)

I selected this on Figma and exported to PNG, is that the correct way?

![Image](https://user-images.githubusercontent.com/157240/197280027-3d6094e3-872c-4694-94b0-6a2f7150a6aa.png)

**Comment by digitalwaveride** [comment]
Here is an svg:

![Form Block](https://user-images.githubusercontent.com/5120357/197282051-0a06e048-ca44-4edf-80f8-f79ae42d3617.svg)

---
And a png:

![Form Block](https://user-images.githubusercontent.com/5120357/197282120-191bbf74-cdf4-4253-8290-1c7a9527eaac.png)
