### ISSUE TITLE
i18n: split sentence used when listing modules for Jump Start

### ISSUE THREAD

**Issue by zinigor** [Automattic/jetpack#2689]
The module listing sentence uses a list of module names that is compiled from different strings and uses an untranslated conjunction:
https://github.com/Automattic/jetpack/blob/master/_inc/lib/admin-pages/class.jetpack-landing-page.php#L127

**Comment by dereksmart** [comment]
can't we just `__()` it?

**Comment by zinigor** [comment]
Sadly, no - we need to create at least a string with placeholders and use `sprintf` to replace module names one by one instead of doing an `implode`. What's worse is that this code seems to be used in other strings, which makes the situation even more interesting. I will work on a proposal in the next few days.
