### ISSUE TITLE
Contact form: Add "tel" and "time" fields

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#269]
As suggested here: http://wordpress.org/support/topic/contact-form-date-and-hour?replies=2

**Comment by boboz** [comment]
I second this request.

Adding tel, time and date fields would greately improve the usefulness to end users.
If you manually add type="date" to a field a datepicker shows, so some work has been done here.

**Comment by boboz** [comment]
:)

**Comment by boboz** [comment]
Thanks for the attention. Much appreciated!

**Comment by boboz** [comment]
:+1:

**Comment by samhotchkiss** [comment]
Modified the title, as "date" is part of 3.4.  Punting on "tel" and "time", this would be a good first patch for someone to pick up if they are interested...

**Comment by jeherve** [comment]
Also requested here:
https://wordpress.org/support/topic/date-time-file-inputs?replies=1&view=all

**Comment by jeherve** [comment]
From #3270, cc @bisko 

> While I was working on #3215 I noticed that the `telephone` field has been partially added to the Contact Form code, but it is not working properly.
>
> It seems the field has no way to be selected and added to the form. It is missing from the dropdown, when creating a new Contact Form, which means that I have to add it by hand in the shortcode.
> 
> If I add it by hand it renders broken HTML - an `input` field, followed by a `textarea`. This behavior is caused by a missing `break` statement [here](https://github.com/Automattic/jetpack/blob/master/modules/contact-form/grunion-contact-form.php#L2007-L2011). 
>
> If saved, the `textarea` value overwrites the `input` field value. 
>
> I see that the field is saved in the post content of the saved feedback form and it is not added as a part of the author meta fields. This can lead to a problem at some point with rendering and/or export of the forms. Currently if the field is saved (and the above mentioned `break` bug gets fixed), there is no way to see it in the admin, without choosing `edit` on the resulting feedback form post.

**Comment by v18** [comment]
2782717-t

**Comment by frank909** [comment]
How is the progress on the date contact-field? When I used type="date" on my form, clicking within the field causes an non-styled calendar to pop-up. but when clicking the right arrow caused the correctly styled calendar to pop-up. Do you know when this will be fixed? It's very close but not good enough for a production site.

**Comment by jeherve** [comment]
@frank909 This issue will most likely be addressed in #3578. We'd need to make sure the date picker is always available, and takes existing values into account.

**Comment by dereksmart** [comment]
Done in #7819!
