### ISSUE TITLE
Disable hide Powered by Jetpack option for free plan

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#26901]
while we ignore value for `Show "Powered by Jetpack"` option, we still allow changing it:

![image](https://user-images.githubusercontent.com/6437642/196325808-3c2f3710-5b3a-4d3b-ac7d-d3384ef429b2.png)

Since it does nothing, I kind of expected it to be hidden or disabled.

**Comment by gibrown** [comment]
Also, it would be good to have an info box with a link to upgrade and explaining why it is grayed out.

**Comment by jsnmoon** [comment]
Going with hiding the controls altogether for now.
