### ISSUE TITLE
Widget Visibility: Notice: Undefined property: WP_Error::$slug`

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2691]
`Notice: Undefined property: WP_Error::$slug in /home/transearch308/public_html/wp-content/plugins/jetpack/modules/widget-visibility/widget-conditions.php on line 524`

I haven't been able to duplicate yet. WP_Error is returned either when the term is empty (via get_term, which get_tag is just a wrapper of) or when the taxonomy is invalid.

**Comment by zinigor** [comment]
Should be fixed by #2714
