### ISSUE TITLE
Jetpack SEO Feature Request: Specify the Page Meta Title 

### ISSUE THREAD

**Issue by kimclow** [Automattic/jetpack#26924]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Login to your website Dashboard 
2. Select Pages 
3. Select any page 
4. Click on the Jetpack Icon next to the settings icon 

### A clear and concise description of what you expected to happen.

This is not a bug report, but a feature request to enhance Jetpack SEO. 

In the SEO page settings on WPCOM Simple sites, you're able to add a page meta description. 

It would be beneficial to add a meta title as well, and allow users to specify meta for both page titles and descriptions. 

<img width="431" alt="Screenshot 2022-10-19 at 13 57 19" src="https://user-images.githubusercontent.com/83212200/196684216-693e7bfc-26e5-4c33-b0e3-5296e9e752ff.png">

### Reproducibility

Consistent

### Severity

One

**Comment by kimclow** [comment]
My apologies for using the incorrect template for a feature request.

**Comment by samiff** [comment]
> It would be beneficial to add a meta title as well, and allow users to specify meta for both page titles and descriptions.

Do you mean the actual page `<title>` element, or something like `<meta name="title"`? If it's the latter, I'm not sure that would offer any real SEO benefits over the `<title>` alone, I'd love to know if there is information that states otherwise.

For a custom per-page `<title>`, that's a great idea and there is currently a draft pull request for that: #27236

**Comment by kimclow** [comment]
Hey @samiff 
Thanks for the response! 

> For a custom per-page <title>, that's a great idea and there is currently a draft pull request for that: https://github.com/Automattic/jetpack/pull/27236

This is 100% what I was talking about. So glad it's happening :-)
