### ISSUE TITLE
JSON API: sync user counts

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#2693]
Sync number of total users and number of total subscribers so it can be included on the /me/sites endpoint.

**Comment by gravityrail** [comment]
All users are synced with the new sync protocol, so the data is now available on the wpcom side (though not yet exposed via API - that would be a separate issue?)

**Comment by roccotripaldi** [comment]
Cool! Awesome job Poseidon. This was is relevent to People Management, which is in the realm of the now deprecated Mercury team. I'll drop a p2 on Mercury so we can track it as part of our cross-team maintenance. And we can discuss it more there.

**Comment by roccotripaldi** [comment]
Actually, People Management no longer needs the data to be exposed on the API. We ended up changing the UI, so user counts are no longer causing a performance issue. We are good to close this without further action.
