### ISSUE TITLE
Search meters: remove the popup tool tips when on Free plan

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#26935]
### Impacted plugin

Jetpack, Search

### Steps to Reproduce

1. "Purchase" a free search plan
2. You'll get this:

![image](https://user-images.githubusercontent.com/820871/196758306-1909a341-f827-4540-a9e2-01fc669eb49e.png)

### A clear and concise description of what you expected to happen.

The designs specify only showing these tips when the user has upgraded panfyZ-1pv#comment-3114

### Reproducibility

Consistent

**Comment by jsnmoon** [comment]
@dognose24: I can take this one 🙂
