### ISSUE TITLE
VideoPress: do not perform requests when the site is not connected

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#26950]
![Image](https://user-images.githubusercontent.com/77539/196812475-5b76d37e-900a-4cd0-b69d-ba2a81cae9ae.png)

**Comment by dhasilva** [comment]
Fixed at some point without mentioning this issue.
![Image](https://user-images.githubusercontent.com/8486249/220428125-3fc5da05-dc91-4654-a752-45caedaaf369.png)
