### ISSUE TITLE
My Jetpack: update the add-search page

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#27018]
### Impacted plugin

Jetpack, Backup, Boost, Protect, Social

### Steps to Reproduce

1. Install any Jetpack plugin that includes My Jetpack (not Search though)
2. Use the store sandbox to get the new Search pricing/plans
3. Go to My Jetpack and click on Search
4. That will take you to /wp-admin/admin.php?page=my-jetpack#/add-search

### A clear and concise description of what you expected to happen.

This upsell page isn't really in the designs any longer. I think we should be redirecting to /wp-admin/admin.php?page=jetpack-search or we should copy all the content from there over into My Jetpack (I'm guessing this is in a separate package).

If we don't want to remove it then we should at least update the text.
- 29 languages => 38 languages
- Add some text about the number of records/queries

But really I think we should replace this upsell page with the one matching what is in the jetpack-search page.

### What actually happened

<img width="1072" alt="Screen Shot 2022-10-23 at 10 07 26" src="https://user-images.githubusercontent.com/820871/197403901-f5be2576-790e-4a7c-ab61-beb47bfb30f8.png">

### Reproducibility

Consistent

**Comment by robfelty** [comment]
In looking into this, I discovered that the "start for free" button also goes to checkout for a paid plan, so I think this is a slightly bigger issue. I am looking into a fix.

**Comment by robfelty** [comment]
Update for 29 => 38 languages here https://github.com/Automattic/jetpack/issues/27018

I think it will be a bit tricky to replace the whole thing here, since the my-jetpack code seems quite different from the search dashboard upsell page code.
