### ISSUE TITLE
Sharing: Add filter to enable disabling of the add_meta_box. 

### ISSUE THREAD

**Issue by andreasnrb** [Automattic/jetpack#2705]
There is no check for whether the post type has sharing enabled or not in function sharing_add_meta_box(). I prefer the metabox is not added unless Show sharing buttons is enabled for the post type.

**Comment by kraftbj** [comment]
This is not quite how this feature works.

The setting indicates which views the sharing buttons show. `Front Page, Archive Pages, and Search Results ` being the first option, the rest being the singular view of those particular post types.

The meta box control determines if sharing posts should be shown for that particular post in any context while the Settings->Sharing determine where should sharing buttons appear _if that particular post_ is set to display it.

I'm proposing a `wontfix` for this as it's dependent on a much larger rewrite of the logic involved. To truly disable a whole post type from using the sharing buttons, I'd suggest using the `sharing_show` filter. 

```apply_filters( 'sharing_show', $show, $post );```

`$show` should be returned as `false`. The `$post` is the post object, so you can call `$post->post_type` as part of a conditional on the filter.

**Comment by kraftbj** [comment]
Changing my tune a bit. Let's add a filter so it's easier to disable the meta box when desired (coupled with the suggested filter in my last comment).
