### ISSUE TITLE
General: allow deep-linking to module modal instead of modules page

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2706]
Right now, it is not possible to link to a specific module modal page, like this one:

![image](https://cloud.githubusercontent.com/assets/1779930/9882525/0e3e0a32-5ba3-11e5-81da-0314948d4c38.png)

You can only link to the module list.

It'd be nice to create links that would open the modal on top of the module list.

cc @aduth

**Comment by jessefriedman** [comment]
I did this back in 3.5 or 3.6.  If you link to the settings page and add ```?info=publicize``` to the end of the URL it will auto popup the modal. Just use the feature slug like this: http://jes.se.com/wp-admin/admin.php?page=jetpack_modules&?info=publicize

**Comment by jeherve** [comment]
Nice, thank you!
