### ISSUE TITLE
Feature Request: The option to include Twitter subscribers in subscriber count. 

### ISSUE THREAD

**Issue by zachspears** [Automattic/jetpack#27075]
### What

Recently subscription blocks were updated to only include followers and email subscribers for a more accurate picture of a user's subscriptions. I had a user in chat who misses the inclusion of their Twitter followers and would like an option to include this. 

37440540-hc

### Why

Users may see their subscription numbers change dramatically and/or prefer to include their Twitter subscribers int heir subscriber count. This would simply provide them with the option to do this. 

### How

I imagine this as an additional setting for the block with something like "Include Twitter subscriptions in subscriber count."

**Comment by cuemarie** [comment]
📌 FINDINGS/SCREENSHOTS/VIDEO
- Thanks for passing along this feedback. As of now, it doesn't seem that this update to the subscriber count will change, but for now I'll mark this as kept in case Quality Squad wants to keep this open as a possible future enhancement.

📌 ACTIONS
- Feature request kept
- noted feature request here: p7DVsv-fDf-p2

**Comment by kelasante** [comment]
Another request in 30685675-hc

**Comment by cuemarie** [comment]
As of earlier today, the change to the Subscriber counts has been reverted, and developers are considering next steps. More info here: p7DVsv-fDf-p2

📌Actions
- 
- Closing as the underlying change this feedback is based on has just been reverted, for now. Feel free to reopen if future users request separate control of showing social media & site subscribers.
