### ISSUE TITLE
bbPress compatibility

### ISSUE THREAD

**Issue by webmandesign** [Automattic/jetpack#2708]
After recent plugins update I got my bbPress topic content not displayed. I was able to track the issue to [`add_action( 'bbp_get_topic_content', 'jetpack_sharing_bbpress' );` line in Jetpack plugin](https://github.com/Automattic/jetpack/blob/c9701cd7871e488c8b3f04ddd75b3c4cc8f86270/3rd-party/bbpress.php#L3). Please note that I don't have Sharing module enabled on my website. Why is this running anyway then? Could you have a look at the issue please? Thanks.

**Comment by jeherve** [comment]
I can't seem to reproduce the issue on my end. I use the most recent version of Jetpack, WordPress, and bbPress, and have looked at bbPress topics when Sharing buttons are enabled, and when the whole sharing module is disabled. Content seems to be displayed properly in both cases.

Could you tell me more about the issue on your site? Could you also post your site URL here, so I can have a look?

If you want it to remain private, you can also contact us via this contact form:
http://jetpack.me/contact-support/

**Comment by kraftbj** [comment]
To explain the why a bit more, the `sharing_display` function that this action calls checks to see if Sharing output should occur (dependent on Settings->Sharing) when the Sharing module is active.

In this case, the function fires in the action, meaning it isn't touching the actual content being displayed, just being hooked to display afterwards.

If the sharing module isn't enabled (and thus the function not available), nothing is outputted.

**Comment by webmandesign** [comment]
Hi guys,

Thanks for explaining.

The issue is actually a bit more specific, indeed. On my support forum (http://support.webmandesign.eu/forums/topic/css/ for example) I use `bbp_get_topic_content` function to display the topic outside the normal bbPress loop. I'm hooking this function via an action hook to display at the very top (the slightly gray area with "Custom CSS" title in above example) of the page content.

I can see where your issue is actually coming from... 

You are using action hook in `add_action( 'bbp_get_topic_content', 'jetpack_sharing_bbpress' );` which is actually a filter hook (that would not be such an issue, I know ;) ) but you are not outputting the filtered content in your [`jetpack_sharing_bbpress` function](https://github.com/Automattic/jetpack/blob/c9701cd7871e488c8b3f04ddd75b3c4cc8f86270/3rd-party/bbpress.php#L16).

[Here is the original bbPress code: `return apply_filters( 'bbp_get_topic_content', $content, $topic_id );`](https://github.com/wp-plugins/bbpress/blob/9e4ea1472124f7628192c7fe74ba5863d7c5e8d3/includes/topics/template.php#L728)

Please fix this.

Regards,

Oliver

**Comment by kraftbj** [comment]
Ah, yes. You're right. I'm checking in #bbpress in w.org slack to verify our hooks and that they're all logical, not duplicative, etc as I don't want to create more problems by fixing this.

**Comment by josephsellers** [comment]
Would this be the same bug that is causing bbPress lead topics not to display? 

If a theme uses add_filter( 'bbp_show_lead_topic', '__return_true' ); then the lead topic doesn't display. 

This only became a problem in 3.7

If this is unrelated let me know and I will open a new issue.

**Comment by kraftbj** [comment]
@josephsellers Possibly. Would the patch in #2710 resolve your issue too?

**Comment by josephsellers** [comment]
@kraftbj, 

Yep, that solves it. Thanks!
