### ISSUE TITLE
Related Posts Block: Add the ability to include a headline within the block itself

### ISSUE THREAD

**Issue by coder-karen** [Automattic/jetpack#27108]
### Impacted plugin

Jetpack

### What

The Related Posts block doesn't appear to allow for a headline to be added above the suggested related posts, within the block itself. If the headline is added outside the block, then if the related posts do not render a post can look a little odd with just the 'Related Posts' headline. If Related Posts are used without the block, a headline can be included and can also be customized in the customizer.

Internal conversation: p1666834512710569-slack-CBG1CP4EN

### How

This is how the related posts look on my test site which doesn't use the block. Ideally the block output (in terms of the headline) could look similar:

<img width="1032" alt="Screen Shot 2022-10-27 at 10 48 34 am" src="https://user-images.githubusercontent.com/16754605/198252515-d9c2d1a4-0f1f-4ed4-9813-921c42634ac9.png">

When testing the block out, I tried with Twenty Twenty, Twenty Twenty One and Two themes. Also the latest Jetpack beta, and 10.9 to be sure there wasn't a regression. There was one main Related Posts regression I could see:

- Related posts don't show by default (not using the block) on FSE themes on newer versions of Jetpack (10.9 was fine - 11.1 appears to be where that issue started - likely here: https://github.com/Automattic/jetpack/pull/24622 - though that was fixing a bug as it seems this functionality should have been in place about a year ago. More content here - pcjTuq-hx-p2. ). Adding headlines to the block (and possibly a clearer explanation on the settings card as well) would allow a smoother transition over for those who weren't using the block before, if the goal is to move away from the site wide feature.
  - PR to follow-up with warnings / JITMS when switching to FSE theme: https://github.com/Automattic/jetpack/issues/27200

**Comment by a8ck3n** [comment]
This is addressed in #30897.

It matches the basic behaviour that exists in the Customizer in that it allows you to enable a headline and provide a string on a per-block basis.
