### ISSUE TITLE
Photon issue and the cdn img url

### ISSUE THREAD

**Issue by Frumph** [Automattic/jetpack#2713]
just using wp_get_attachment_image_src to get the url of the featured image, the ?resize=860%2C1300 part errors out trying to connect to the CDN, but works without it

http://i2.wp.com/www.wartcomic.com/wp-content/uploads/2015/08/page4.jpg?resize=860%2C1300

http://i2.wp.com/www.wartcomic.com/wp-content/uploads/2015/08/page4.jpg

i'm not sure I know how to explain this, but i'm just using the wordpress function wp_get_attachment_image_src and it *was* working, tonight though on some sites, but not all if there's an extra info on the end of the line for the image it errors out

I have no idea where the resize value comes from, but not the first time i've seen this,  is there a way that request can chop off the extra values when making a request so it doesn't error out?

**Comment by jeherve** [comment]
Both images appear to be working fine on my end.

Could you give it another look on your end? It could be because Photon cached a broken version of that image earlier.

**Comment by Frumph** [comment]
working now, and it was with every comic on their site ;/

**Comment by kraftbj** [comment]
I'm going to close this as invalid since it sounds like all is good now. If not, please do comment and we can reopen.
