### ISSUE TITLE
VideoPress: show that the upload is in progress on list view

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#27154]
Add some UI indicator to show that a video is being uploaded or processed on the list view:

![Image](https://user-images.githubusercontent.com/16329583/198692052-eebd19a5-18fb-4f3a-97dd-bf17ca75c8d8.png)

**Comment by dhasilva** [comment]
Already added here: https://github.com/Automattic/jetpack/pull/27098
Closing as duplicate of https://github.com/Automattic/jetpack/issues/27085
