### ISSUE TITLE
VideoPress: FLV video upload fails silently

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#27168]
I tried to upload a FLV video and it got stuck on the "Uploading 0%" placeholder thumb:

![image](https://user-images.githubusercontent.com/6760046/198734763-c5cd54aa-52e6-4b94-a159-746b8eac0ad5.png)

I checked the console, and spotted a failed post request:

![image](https://user-images.githubusercontent.com/6760046/198734896-14321371-01fb-4340-9b47-efbde1b0e641.png)

The response for this is request is a HTTP 403 with the following body:

```
{"success":false,"data":{"error":"Access Forbidden","message":"Invalid Mime"}}
```

From the initial state, this is the allowed extensions and mime-types:

![image](https://user-images.githubusercontent.com/6760046/198735360-d98b25fb-8db6-4910-8154-5388cc1543d1.png)

We may have some limitations on the formats allowed by the WPCOM endpoint, and the allowed formats may be different from the site allowed mime types.

**Comment by lhkowalski** [comment]
Tried to upload a `flv` file directly on the WPCOM media library and it fails there as well:

![Image](https://user-images.githubusercontent.com/6760046/200080826-3cf30c23-9c7c-4a4f-9f60-d69068f7479f.png)

Probably we will need to fetch the list of allowed mimes and extensions from WPCOM itself, not relying on the WP installation data.

**Comment by retrofox** [comment]
> Probably we will need to fetch the list of allowed mimes and extensions from WPCOM itself, not relying on the WP installation data.

So instead of getting the extensions by the [get_allowed_mime_types()](https://developer.wordpress.org/reference/functions/get_allowed_mime_types/) function, we should hit a dotcom endpoint. Probably it's already implemented, or the data is exposed in some site endpoints, too.

**Comment by lhkowalski** [comment]
I am checking why the extension is not supported, because the check of allowed formats is coming from the same `wp_get_mime_types` function that we are using on our end...

**Comment by lhkowalski** [comment]
The same problem happens with a MKV file that I used for testing.

**Comment by lhkowalski** [comment]
[This public support page](https://wordpress.com/support/videopress/#video-requirements-and-specifications) specifies which formats are allowed on VideoPress. The list is different from the list of video formats allowed by WordPress itself. We may need to rely on a fixed list on the backend.
