### ISSUE TITLE
VideoPress: detect when the video has chapters

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#27206]
We want to detect when the video has chapters to show the button, as the following picture shows:

![Image](https://user-images.githubusercontent.com/77539/199484860-27facf8a-46e1-4b21-800f-e0fa91ab989e.png)

When the user clicks on the `Add chapters list to the post` button, the app inserts a VideoChapters block just below to the Video block.

**Comment by chrisbliss18** [comment]
Done. Merged from PR #27240.
