### ISSUE TITLE
? problem in Script and Link rel codes

### ISSUE THREAD

**Issue by sunipeyk** [Automattic/jetpack#2721]
Page tests sites and google insight give warnings about the "?" that you use in Script and Link rel codes. You know we cant change it manually in our wordpress blog while using jetpack. Please change it with the "#63;". 
Thank you very much.

**Comment by jeherve** [comment]
These numbers are automatically added by Core in many cases, and by Jetpack when versioning is important. It doesn't stop you from caching the files with a caching plugin, though, so it's a warning you can ignore if you use a caching plugin on your site.

However, if you'd like to remove these version numbers anyway, you can follow the instructions [here](http://wordpress.stackexchange.com/a/96325/27574).

**Comment by sunipeyk** [comment]
Hi, 
You closed problem. But the problem is not the version number. Its the questionmark before it.

**Comment by jeherve** [comment]
The question mark is added with the version number. Question marks are used to pass parameters in URLs. For example, on any WordPress site, you can use the question mark to pass a search parameter, like so:
`http://jetpack.me/?s=search`
