### ISSUE TITLE
VideoPress: created a `/videos/guid/chapters` to get video chapters

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#27235]

**Comment by lhkowalski** [comment]
Sub-problems I can think of:

* [x] expose a GET endpoint on WPCOM public-api in the form of `/videos/guid/chapters`
* [x] fetch the chapters information for the given video (chapters are a type of `track` with kind = 'chapters')
* [x] fetch the chapter vtt file and parse it
* [x] format the response

**Comment by trakos** [comment]
We've created a diff today: D91445-code

**Comment by lhkowalski** [comment]
It got shipped early this week, I will close this as done. Thanks @trakos for shipping it!
