### ISSUE TITLE
Jetpack Carousel - photo caption & description reversed on iphone/android device

### ISSUE THREAD

**Issue by sauronthedark** [Automattic/jetpack#27255]
### Impacted plugin

Jetpack

### Steps to Reproduce

1) Go to https://opticvoid.com/portfolio/current/#jp-carousel-1915 on desktop chrome
2) go to https://opticvoid.com/portfolio/current/#jp-carousel-1915 on iphone hardware or android hardware device
![carousel](https://user-images.githubusercontent.com/32499306/199798417-864ae9e3-168e-4471-9dd7-faa3643bde9d.png)

### A clear and concise description of what you expected to happen.

Jetpack carousel correctly displays photo caption above the description on chrome desktop/mobile preview. When photo is viewed on mobile hardware such as iphone or android, the caption incorrectly is displayed below the photo description

### Browser

Google Chrome/Chromium, iOS Safari, Android Chrome

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by samiff** [comment]
Hello @sauronthedark 👋 

The website provided in your example appears to be using an older Jetpack plugin version of 9.6.2, while the latest version of Jetpack is 11.5.1 which you can find here:

https://wordpress.org/plugins/jetpack/

The Jetpack carousel feature received some larger updates in 10.0 and 10.1, here is a preview of what it looks like on my test site currently:

![Screenshot 2022-11-03 at 1 12 01 PM](https://user-images.githubusercontent.com/15803018/199813160-c0907379-c2b3-482a-8c67-c19bffcf402e.png)

In this case, I'd encourage you to consider updating your Jetpack version as any additional development work would be focused on the updated version of the carousel feature.
