### ISSUE TITLE
Improve image optimization 

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#2725]
I was surprised to see that our `images/` directory is the 3rd largest in the plugin at 1.8M.  Basically all of that weight comes from the `screenshots/`.  Here are the largest four of those: 

```
100    hovercards.png
104    widgets.png
172    tiled-gallery.png
288    carousel.png
```

I think many of the screenshots could be compressed, as (I think) the max size we display them are at 300 width.  (carousel.png is 740px wide)

whaddya say, @jeffgolenski?

**Comment by kraftbj** [comment]
While we're in there, might as well remove the site-icon screenshot too. The feature is still possible for folks on 3.7 + 4.2 and 3.8 will likely still include 4.2 support. That said, I'm okay removing the screenshot now to reduce the size if we're already paying attention to it.

**Comment by jeffgolenski** [comment]
@dereksmart Thanks for bringing this to my attention. I'll be sure to do a full audit of our images dir this week and remake any screenshots we need redone, and compress the others. Would be nice to get that thing under 1mb!

**Comment by dereksmart** [comment]
@jeffgolenski please add to whatever milestone you think you can get to

**Comment by jeherve** [comment]
Related: #2236

**Comment by jeffgolenski** [comment]
fixed in: https://github.com/Automattic/jetpack/pull/3008
