### ISSUE TITLE
Shortcode [googleapps] width bug in t23

### ISSUE THREAD

**Issue by RavanH** [Automattic/jetpack#27269]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. On WP 6.1 with default Twenty Twenty-Three, go to a page and insert a Shortcode block
2. Enter a Google Apps shortcode like `[googleapps domain="drive" dir="file/d/137o4SVU9iyEdhtni-W4_mNHIRYx9GKMW/preview" width="650" height="480" /]`
3. Save and see the front end.

### A clear and concise description of what you expected to happen.

On the front end, it used to show an iframe embedded file, 650 pixels wide and 480 pixels high.

### What actually happened

The iframe embed has a width of 300 pixels.

### Browser

Google Chrome/Chromium

### Other information

Original WP.org thread https://wordpress.org/support/topic/shortcode-googleapps-width-bug-in-t23/

### Platform (Simple, Atomic, or both?)

Self-hosted

### Reproducibility

Consistent

**Comment by samiff** [comment]
Thanks for the report @RavanH 👍 

We'll take a look at fixing this in #27276

**Comment by RavanH** [comment]
Hi @samiff thanks :) However, I'm not sure changing `isset` for `is_numeric` will fix this particular issue. In my sample shortcode, the numeric parameter `width="650"` is ignored (and replaced by a default iframe width of 300px) while that same shortcode with the parameter `width="650px"` (not numeric) works!

I'm currently using `width="100%"` as a work-around but it looks like checking for `is_numeric` would actually make the work-around fail too...

**Comment by RavanH** [comment]
Ok, looking closer at the code involved I understand the numeric check is done for the theme global `$content_width`. Does t23 return a boolean there? I would not have guessed... Great find! Thanks @samiff for the work and PR :)
