### ISSUE TITLE
Post by Email: Sharing buttons unchecked on all posts sent by PBE

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#2727]
If you send an email to PBE with `[status draft]` the sharing buttons will be unchecked on the post, even if you have it checked for all posts on Settings -> Sharing. If on the other hand you create a draft post from within the dashboard, the sharing buttons will be automatically checked. This came up in 2349724-t.

**Comment by richardmtl** [comment]
Upon further testing, the sharing buttons are unchecked, regardless of the post status. I have edited the Issue title to reflect the new information.

**Comment by richardmtl** [comment]
This came up in 2352716-t

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
