### ISSUE TITLE
Photon doesn't serve the 'background-image:url' on the core Cover block

### ISSUE THREAD

**Issue by ChrisBegley** [Automattic/jetpack#27284]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Enable Jetpack and the Image CDN
2. Add a Cover block to a page
3. Add a background image to the Cover block
4. Turn on "Fixed background" for the Cover block image. Publish.
5. Check out the source code of Cover block
6. Notice that the `background-image:url` is not being served by Photon

Example: `<div role="img" class="wp-block-cover__image-background wp-image-4696 has-parallax" style="background-position:50% 50%;background-image:url(https://example.com/wp-content/uploads/2022/11/hjmpaUo7JDzImgGvsisefIbPrTX-scaled.jpg)"></div>`

### A clear and concise description of what you expected to happen.

Photon to serve the `background-image:url` image

### Other information

WordPress 6.1
Jetpack 11.5.1

### Reproducibility

Consistent

**Comment by coder-karen** [comment]
Thanks for reaching out @ChrisBegley 

The Cover block [adds the images via style attribute on a div directly](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/cover/index.php#L16), which prevents Site Accelerator from being able to find the image (at the moment).

There is an existing issue that also covers the Cover block here - https://github.com/Automattic/jetpack/issues/16396 - so I'll close this in favor of that one.
