### ISSUE TITLE
Boost: speed score refresh continues to fail subsequently after one failure

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#27285]
### Impacted plugin

Boost

### Steps to Reproduce

1. Request speed score using the plugin
2. Do not return speed score for the request from the server (i.e. this should result in a timeout on the plugin)
3. Try to refresh speed score from Boost settings dashboard(plugin)

### A clear and concise description of what you expected to happen.

Trying to refresh the score at this stage should submit a new speed score request to wpcom

### What actually happened

The plugin continues to try to poll for update on the existing request. It does not submit a new request.

### Platform (Simple, Atomic, or both?)

Simple, Atomic, Self-hosted

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

If speed score request fails due to a timeout, set speed score state to failed. This would make sure the next refresh will generate a new request.

**Comment by dilirity** [comment]
Notes: It appears this happens because of the existence of the transient, that holds the first error.
