### ISSUE TITLE
Form Block: Improve Styling/Formatting of Form Submission View

### ISSUE THREAD

**Issue by jcheringer** [Automattic/jetpack#27295]
Currently the submission view looks a bit off.

The feedback to users "Message sent" is shown in a H3 and can depending on the theme be pretty big.
The label of a data field is in the same styling as the response, which makes it hard to read.

![Image](https://user-images.githubusercontent.com/5120357/200317711-c58ec9bb-a503-4a12-b42a-c7e467782482.png)

**Comment by digitalwaveride** [comment]
Here a design draft:

![image](https://user-images.githubusercontent.com/5120357/200416853-e68ffc2a-93d7-436b-b787-3fdc4e1fd9a1.png)

![image](https://user-images.githubusercontent.com/5120357/200416915-345110f8-5316-49d6-9ef7-fc0edb9891ad.png)

**Comment by pablohoneyhoney** [comment]
- The heading could be a tiny bit more explicit and human, like: `Cool, the message has been sent` or `Your message has been sent` or alike. 
- `Go back` doesn't need an arrow left. I could be the case that back is up in certain cases. Or even _close_. 
- The placement of Go back is also odd with a left aligned validation. It could be simply below or above the heading.  
- It doesn't need an arrow if it's underlined either. 
- It doesn't' need a final punctuation. 

<img width="710" alt="Screen Shot 2022-11-19 at 10 16 50 AM" src="https://user-images.githubusercontent.com/25516611/202857851-4565e038-a129-484b-9077-24df11d1b70b.png">

**Comment by digitalwaveride** [comment]
The "Go back" was center aligned with the intention to make the link a bit more prominent after a potentially long data entry. I like the idea of simply putting it even above the headline! 

![image](https://user-images.githubusercontent.com/5120357/203028425-a0dedef2-374c-479a-8f57-bc955411a44d.png)


![image](https://user-images.githubusercontent.com/5120357/203027459-512367a8-3485-4fba-a094-37a942909053.png)
