### ISSUE TITLE
Media: Restoring an edited media results in error for Jetpack sites

### ISSUE THREAD

**Issue by vykes-mac** [Automattic/jetpack#27304]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. In calypso go to `Media` for any jetpack site.
2. Select and crop and image then save.
3. Select the cropped image, edit then click restore button.
4. Resulted error and the original image is not shown

### A clear and concise description of what you expected to happen.

Original image should be shown

### What actually happened

Error message is show 
![image](https://user-images.githubusercontent.com/47489215/200438787-68af1b70-58ea-433b-9867-14d90d065d72.png)

Original image is not restored.

### Browser

Google Chrome/Chromium, Mozilla Firefox, Apple Safari

### Other information

https://user-images.githubusercontent.com/47489215/200438694-c08d9636-0402-4f35-b8e1-1bb50861d752.mov

![image](https://user-images.githubusercontent.com/47489215/200438703-db37d27e-2246-4478-b5e9-f1683ce2f68a.png)

### Platform (Simple, Atomic, or both?)

Self-hosted

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

restore the image from `wp-admin`

**Comment by anomiex** [comment]
I was unable to reproduce this following the given instructions with a JN site.

It would probably help if you can check your logs for the relevant error behind the message.

**Comment by vykes-mac** [comment]
@anomiex strangely I'm not able to reproduce the issue again. I will close the issue and reopen if anyone reports this.
