### ISSUE TITLE
Map block: cannot set height less than 400px

### ISSUE THREAD

**Issue by sophiegyo** [Automattic/jetpack#27302]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Ensure Jetpack is installed/connected
2. Create a new page/post
3. Insert Map block
4. (if self-hosting): Insert Mapbox API token
5. Attempt to set Map block height to less than 400px (eg: 300px)

### A clear and concise description of what you expected to happen.

The map should show at less than 400px.

I could not find anything in the support doc indicating there was a minimum height restriction:
https://jetpack.com/support/jetpack-blocks/map-block/

### What actually happened

The map height field reset to 400px.
On the published page, the map definitely shows at 400px.

Screencast of the resetting height:

https://user-images.githubusercontent.com/36608681/200429394-3761f8ed-9b99-468f-a2f1-1eb2065618a7.mp4

### Other information

This doesn't occur for larger heights than 400px: 500 worked fine, for example.

It's specifically values lower than 400 px which the block won't accept.

Tested on:
Self-hosted WP 6.1, no Gutenberg, Jetpack 11.5.1
WPcom Simple site (WP 6.1, I think? I can't remember if it was updated yet after the hitches with Atomic.), Gutenberg 14.4.0

Browser: Firefox 106.03
OS: Mac 12.6 Monterey

### Platform (Simple, Atomic, or both?)

Simple, Atomic, Self-hosted

### Reproducibility

Consistent

### Workaround details

It looks like the 400px is being defined in inline CSS in the markup, so it can probably be worked around with something this:

```
.mapboxgl-canvas-container.mapboxgl-touch-zoom-rotate.mapboxgl-touch-drag-pan, 
.mapboxgl-canvas-container.mapboxgl-touch-zoom-rotate.mapboxgl-touch-drag-pan .mapboxgl-canvas {
height:  250px!important;
width: auto!important;
}
```

**Comment by anomiex** [comment]
This seems to be an intentional limitation on the block, present since custom heights were added in #14706, so this seems more like an enhancement request than a bug.

**Comment by richtabor** [comment]
I think it's fine that it is set to a minimum of 400px.
