### ISSUE TITLE
VideoPress: Broken thumbnails with 403 status

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#27314]
Steps that caused the problem here:

1 - I was logged in my wpcom account before a scheduled auto-logout

2 - I turned on the `Video Privacy` flag:
![Image](https://user-images.githubusercontent.com/8486249/200588009-95e033d5-70c1-40fa-b430-503cbe25c337.png)

3 - I uploaded a video through the `VideoPress (beta)` block that got stuck on 99%:
![Image](https://user-images.githubusercontent.com/8486249/200588365-6005ee1c-e4d4-450a-9316-a5b54a731ced.png)

4 - On the VideoPress dashboard, that specific thumbnail broke, with a `403` status:
![Image](https://user-images.githubusercontent.com/8486249/200588427-b98d08e1-2b21-4fbb-bbea-585576873f4a.png)

5 - At this point I visited a wpcom link and had to re-login

6 - After login, all thumbnails gave me `403`:
![Image](https://user-images.githubusercontent.com/8486249/200589060-a13469ff-debc-4476-9b4b-4dd20fd2934a.png)

7 - I uploaded another video, from the VideoPress dashboard this time, and the new video immediately got a broken thumbnail (`403`)

8 - I turned off `Video Privacy` and reloaded the dashboard

9 - All thumbnails, including the thumbnail of the video that got stuck on 99%, were displayed correctly

10 - I turned `Video Privacy` on again and the thumbnails still displayed correctly

**Comment by dhasilva** [comment]
It seems the login steps are not relevant. It takes some time to update the backend with the `Video Privacy` flag, so there must have been some cache involved here.
The issue is that the `Video Privacy` global flag is currently not verified before checking if a thumbnail needs an access token or not.

p1667917768090569-slack-C03TA48NSUX

**Comment by lhkowalski** [comment]
Based on https://jetpack.com/support/video-privacy/, we are sure that the site privacy setting takes precedence over the video setting, so if a video is public but the site is private, the video will actually be treated as private. This way, all videos on a private site will need a token.

**Comment by lhkowalski** [comment]
To fix the issue, we are going to change how we decide if the video needs a playback_token, to incorporate a check on the site global setting. To make it possible, we need to:

* [x] make the site-wide video privacy setting available on the client (relates to #26938 because we need to resolve/select the value for the property, and will be my next step on this)
   * PR: #27321
* [x] change the video resolver to check the new `videoIsPrivate` flag while deciding if the video needs a playback token or if the video needs to be fulfilled again
   * PR: #27380

**Comment by lhkowalski** [comment]
Related to the previous comment, I would like to try another approach for how to make the site-wide video privacy setting available on the client: add it to the video data itself.

This would simplify a lot of things on the frontend side. Maybe it's the opportunity to have a centralized point where we state if a video is actually private or not.

So here is the task:

* [x] expose the video privacy information on the VideoPress data, on the media endpoint response, so each video has it's own flag showing if it's private or not; this should take into account that video privacy setting as well as the site privacy setting, that we know will have precedence over the video setting
   * PR: #27349
