### ISSUE TITLE
setFocusOnActiveMenuItem , users need to scroll up to view page's content

### ISSUE THREAD

**Issue by PanosSynetos** [Automattic/jetpack#27311]
`setFocusOnActiveMenuItem` scrolls down to the active menu item.

But, this causes a very irritating side effect, the content of the page, is scrolled down too, and the users need to scroll up (if the menu item is out of the viewport)

This doesn't happen on Calypso pages, like `Settings > General`

Here's the related file, causing the issue

https://github.com/Automattic/jetpack/blame/trunk/projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js#L139

and a screencast

https://user-images.githubusercontent.com/2484390/200532254-17bba3b3-8d50-44e3-a0c4-fe748b37fe8c.mp4

**Comment by anomiex** [comment]
I see this was added in #20262 with reference to https://github.com/Automattic/wp-calypso/issues/51513. Pinging @tjcafferkey and @BogdanUngureanu who were involved in that and may have more information on what the intention here is.

**Comment by PanosSynetos** [comment]
@tjcafferkey is AFK, let's see what @BogdanUngureanu says.
Thank you Brad!

**Comment by BogdanUngureanu** [comment]
@PanosSynetos From what I remember, there was a a11y issue while moving from Calypso to WP-Admin.

To prevent the automatic scroll, HTMLElement.focus() [accepts a `preventScroll` option that](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus), when set to `true`, it will prevent the scroll. This should prevent the page from scrolling to that element.

**Comment by PanosSynetos** [comment]
Thanks, then I guess it's a good first issue for me then (unless there are objections).
