### ISSUE TITLE
Fatal Error: Class 'Jetpack_Subscriptions_Widget' not found during REST API

### ISSUE THREAD

**Issue by dd32** [Automattic/jetpack#27310]
### Impacted plugin

Jetpack 11.5.1

### Steps to Reproduce

The following PHP Fatal error has been occurring occasionally on https://kolkata.wordcamp.org/2022/. I'm unsure why. This seems to only affect the singular site, not network-wide. It occurs when editing a page, or creating a new one.

```
Error:   Uncaught Error: Class 'Jetpack_Subscriptions_Widget' not found in wp-content/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/subscribers.php:68
URL:     https://kolkata.wordcamp.org/2022/wp-json/wpcom/v2/subscribers/count?include_publicize_subscribers=false&_locale=user
Referer: https://kolkata.wordcamp.org/2022/wp-admin/post-new.php?post_type=page
```

1. Edit a page
2. Trigger a REST API request somehow.

### A clear and concise description of what you expected to happen.

No Fatal error

### What actually happened

A Fatal error.

### Platform (Simple, Atomic, or both?)

Self-hosted

### Reproducibility

Consistent

### Severity

One

**Comment by coder-karen** [comment]
Related: https://github.com/Automattic/jetpack/issues/26178

**Comment by dd32** [comment]
Duplicate of #26178

**Comment by dd32** [comment]
re-opening, as #26178 didn't fix this.

**Comment by dd32** [comment]
Possibly related, with `JETPACK_DEV_DEBUG` enabled attempting to render the subscriptions block will cause fatals.
