### ISSUE TITLE
Action Bar: Incompatible with Twenty-Twenty-Three

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#27356]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Activate Jetpack
2. Activate Action Bar
3. Activate Twenty Twenty Three theme
4. View a single post.

### A clear and concise description of what you expected to happen.

The action bar is displayed.

### What actually happened

It does not display.

### Other information

2023 does not set the `--wp--preset--spacing--20` variable (it seems) so it doesn't display anywhere on the viewport. It does work with 2022. h/t @anomiex 

### Reproducibility

Consistent

**Comment by anomiex** [comment]
Action Bar has been abandoned and removed from the monorepo. See #34939.
