### ISSUE TITLE
VideoPress: Selecting the last frame as thumbnail fails

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#27365]
Selecting the last frame always fails to update it.

https://user-images.githubusercontent.com/8486249/201197688-2d2171c9-8c65-49be-aeff-464ba00a7c0b.mp4

**Comment by lhkowalski** [comment]
This is an interesting bug... I tried with a lot of different videos, and for some of them the selection works, while for others it fails.

The thumb selector goes in steps of 100ms, so the last "selectable" frame is a 100 multiple, for example 9600 ms. If the video `duration` is 5312 milliseconds, for example, the last selectable frame will be the 5300ms frame. If the video `duration` is 29568 milliseconds, for example, the last selectable frame will be the 29500ms frame.

There is one thing in common to all the videos that succeed on selecting the last frame as thumb: the selected time (`at_time` parameter) is not too close to the video `duration`, there is always at least 50ms between the selected thumb and the real end of the file.

There is also one thing in common to all the videos that fails: the selected time (`at_time` parameter) is very close to the video `duration`, usually less than 50ms between the selected thumb and the real end of the file.

**Comment by lhkowalski** [comment]
I checked if this would happen when uploading and setting the thumb through the block, and it happens as well.

I still did not find the threshold between the selected frame and the video duration that will prevent the failure, but it's something between 0 and 100ms.

My guess is that we may have a mismatch bettween the calculated video `duration` on the video metadata and the lenght of the file calculated by the tool that generates the thumbs on the backend, so when we send an `at_time` too close to the duration, it falls off the lenght calculated by the thumbnail generator and fails silently.

**Comment by lhkowalski** [comment]
It also happens on the WPCOM video thumbnail selector as well...
