### ISSUE TITLE
Plugins: Respect the all_plugins filter

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#2739]
The all_plugins filter  (https://developer.wordpress.org/reference/hooks/all_plugins/) is being used to remove plugins from view for from certain users. 

So removing it would be or in other situations. We should add the support via the api. 

See https://horizonfeedback.wordpress.com/2015/09/10/test-plugin-browser/comment-page-1/#comment-112 for the idea.

**Comment by gravityrail** [comment]
We now sync the plugins list to WPCOM - @enejb is this ticket still relevant?

**Comment by enejb** [comment]
Yes still relevant. We should only sync the filtered data to .com. Although if the user filters the list per user or user role the data that we have would still show up the same for each user.
