### ISSUE TITLE
Boost: Critical CSS notice still shown even if auto-generate is enabled by the Premium plan

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#27393]
<img width="1614" alt="image" src="https://user-images.githubusercontent.com/746152/201716175-f11e4d82-1bc5-4dbb-8f0a-0140f2dc0640.png">

#### Steps to reproduce

1. Get Boost premium
2. Change the site theme.
3. Expect to see the notice even when you don't need to regenerate

**Comment by thingalon** [comment]
How embarrassing! :)
