### ISSUE TITLE
Plugins: Remove network activated plugins from plugins api list

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#2740]
Currently we are returning the network activated plugins via in the plugins api. 

We should be remove them just like they are on Jetpack wp-admin plugins page for single sites. 

See https://horizonfeedback.wordpress.com/2015/09/10/test-plugin-browser/comment-page-1/#comment-112 for the idea.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by enejb** [comment]
Just want to make a note that we did add default filters to the list of plugins we sync and in the api. So I think this issue should be synced.
