### ISSUE TITLE
Feature Request: Include Mastadon in Jetpack Social

### ISSUE THREAD

**Issue by jkipk** [Automattic/jetpack#27418]
### Impacted plugin

Jetpack

### What

Include a Jetpack Social connection to Mastadon as Twitter is imploding and lots of people are leaving

### How

We use Jetpack Social to connect our Twitter account to our WordPress.org/Jetpack website, but the future of Twitter is becoming more and more unclear. We've just created a Mastadon account to hopefully mitigate any Twitter disaster, but don't have a clear way to connect (ie: auto post) to Mastadon). Please include one.

**Comment by coder-karen** [comment]
Thanks for the suggestion! As there is another thread to capture interest in the suggestion here - https://github.com/Automattic/jetpack/issues/7790 - I'll close this to keep it all in one place.
