### ISSUE TITLE
Carousel: Slide titles set to `display: none` after a certain number of slides

### ISSUE THREAD

**Issue by sixhours** [Automattic/jetpack#2743]
I ran into this issue with a WordPress.com customer who needed users to be able to see the slide filenames, which were set as the Titles of the images.

All of his images had titles in the Media Library, but after about 10 slides in the carousel, the titles were set to `display: none` inline. You can see the gallery in question here: http://kevinjcull.com/valle-academy/

I tried Custom CSS to fix the problem temporarily, but that just gave all the slides the same title after a certain point: 

`.jp-carousel-titleanddesc { display: block !important; }`

I've advised the user to copy each title into the Caption field in the meantime.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
