### ISSUE TITLE
VideoPress: find a way to let users to know about connect status

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#27451]
When the user is not connected to dotcom, it's impossible to get the video.

<img src="https://user-images.githubusercontent.com/77539/202258099-2f41106f-23fb-4db4-b231-d70351139d56.png" width="500px" />

We should prompt them to fix the connection.

### Tentative designs

![Image](https://user-images.githubusercontent.com/77539/213396688-8fb57cf6-5cf0-4143-b3c0-60451d78ce07.png)

![Image](https://user-images.githubusercontent.com/77539/213396718-ac67d22d-e5dd-4dc7-acd6-703df1d68d04.png)

### Slack threads 

p1674063101056379-slack-C02LT75D3

**Comment by retrofox** [comment]
![Image](https://user-images.githubusercontent.com/77539/209140119-72dbdbcd-49a9-4302-a1b6-c91dad6df217.png)

**Comment by retrofox** [comment]
Probably it should be handled by the [useVideoData()](https://github.com/Automattic/jetpack/blob/83e9d8ad12e89a463417b564e822f771949abd6a/projects/packages/videopress/src/client/block-editor/hooks/use-video-data/index.ts#L19) hook.



![Image](https://user-images.githubusercontent.com/77539/209349263-87cce99b-9e7f-4b91-8e63-cef6ecbee878.png)

**Comment by nunyvega** [comment]
Maybe we should start by improving the error messages in the block editor whenever the non-connected user tries to edit video details.

**Comment by retrofox** [comment]
https://github.com/Automattic/jetpack/issues/27370
