### ISSUE TITLE
The "Get Started" button on "Contact Forms for WordPress Sites" page doesn't work.

### ISSUE THREAD

**Issue by StevenDufresne** [Automattic/jetpack#27463]
### Impacted plugin

Jetpack

### Steps to Reproduce

- Go to https://jetpack.com/features/discussion/contact-forms
- Scroll down to "Get Started" button, click
- Anchor tag is appended to url, goes nowhere.

### A clear and concise description of what you expected to happen.

Wanted to see more information on how to get started.

### What actually happened

Nothing.

### Browser

Google Chrome/Chromium

### Other information

<img width="1260" alt="Screen Shot 2022-11-17 at 11 26 51 AM" src="https://user-images.githubusercontent.com/1657336/202339622-573f1ab9-b965-467a-9726-bc73b80dac28.png">

### Reproducibility

Consistent

**Comment by coder-karen** [comment]
Thanks for mentioning this! The button has been removed for now, and the page itself will be added to the list to be reviewed and updated (internal ref: p1668683243134939-slack-C01264051NE).

**Comment by StevenDufresne** [comment]
Another instance of a _dead_ "Get Started" button:

https://jetpack.com/features/growth/related-posts/#get-started

<img width="400" alt="Screen Shot 2022-12-08 at 11 11 59 AM" src="https://user-images.githubusercontent.com/1657336/206339556-2f1a570a-c87f-406c-a938-460b1e8cc691.png">

**Comment by coder-karen** [comment]
Thanks @StevenDufresne , I've passed that on (and removed the buttons for now too).
