### ISSUE TITLE
Create secondary admin view

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#27496]
My Jetpack currently only supports a full experience for the connection owners of a site (primary admins). This would create both connected and disconnected views of My Jetpack for secondary admins, as well as non-admins.

Designs: 

p1HpG7-hKa-p2

**Tasks:**
My Jetpack Admin views:
- [x] Update connection owner Jetpack connected view
- [ ] Update non-connection owner Jetpack connected view

**Comment by renatoagds** [comment]
Asana ref: 1199980337313591-as-1203014844649630/f

**Comment by oskosk** [comment]
@renatoagds @nunyvega can we continue with this one?

**Comment by nunyvega** [comment]
I'll break this into smaller tasks and we can start tackling them tomorrow

**Comment by nunyvega** [comment]
I edited the issue to break it into smaller tasks. I'm starting with the first one now.

While reviewing the designs I see that we have a view for non-admins. How would a non-admin be able to access the My Jetpack page?

**Comment by nunyvega** [comment]
First task completed, tackling the second one now.
