### ISSUE TITLE
IDC: Assuming staging site with local domains

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2753]
We should assume a site is a staging site and instantly kill it at least with typical development URLs, e.g. no dot in the URL (development mode trigger), .`local`, `.dev`, etc. Possibly check against the valid domain check?

Related (but I think this can be a quicker win): #2153
cc: @dereksmart

**Comment by kraftbj** [comment]
Depending on #2997, we can add this through that framework or, if want to use the valid domain check, throw that in.

**Comment by ebinnion** [comment]
This may not be necessary with our new work on IDC mitigation. Local URLs won't be accessibly, so a user wouldn't be able to connect them. And, if the user happened to clone the site from production to local, we'd automatically put the site in staging mode.

I'm going to move this to probably close in the project for now.

**Comment by samhotchkiss** [comment]
#5436

**Comment by ebinnion** [comment]
Closing for now in favor of new IDC work.
