### ISSUE TITLE
Rewrite scss _grid to be a function, not static

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#2754]
Right now the grid within _grid.scss is written out in css. We can reduce the file size by writing it as a function instead so it's dynamically generated.

**Comment by dereksmart** [comment]
@jeffgolenski removing a milestone from this.  Please add to whatever milestone you think you can get to.

**Comment by jeffgolenski** [comment]
This issues becomes irrelevant for 4.1
