### ISSUE TITLE
VideoPress: Disable local video upload for free plan after first upload

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#27561]
It fails silently on the UI, with an uncaught promise on console.

![Image](https://user-images.githubusercontent.com/8486249/203405471-e04ba1ee-7b17-4c3d-9d15-3c4f03e10c83.png)

**Comment by retrofox** [comment]
Is it already tackled?

**Comment by lhkowalski** [comment]
I will test now to check if it's still happening.

**Comment by lhkowalski** [comment]
Yes, it's still happening.

What I did:

- created a fresh site
- uploaded some videos to the local media gallery
- connected the site and selected a free plan
- went to the VideoPress dashboard and uploaded the allowed free video
- went to the list of local videos and clicked the "Upload to VideoPress" button (the buttons are active even after the upload of the free video)
- the upload "started", meaning that I coud see an empty thumbnail on the list of videos:

![Image](https://user-images.githubusercontent.com/6760046/216993555-7b07cb1b-b6f6-4b31-aff7-37a7a272749a.png)

- the upload fails (as expected) but nothing happens on the UI (still seeing "Uploading 0%"), and the exception is logged on the console:

![Image](https://user-images.githubusercontent.com/6760046/216993838-60540958-e03b-4fa7-b644-9d009dbf37aa.png)
