### ISSUE TITLE
Bug: Email form - Subscription module: label for: wrong id

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [Automattic/jetpack#2757]
Hello!

my html validator spits out an error because of wrong label for subscription field. 
Using Jetpack 3.7
file: https://github.com/Automattic/jetpack/blob/master/modules/subscriptions.php
line: 764

https://github.com/Automattic/jetpack/pull/2756

**Comment by jeherve** [comment]
Thanks for the report.  Is duplicate of #2618. Patch submitted in #2632
