### ISSUE TITLE
Portfolio post format

### ISSUE THREAD

**Issue by pixedelic** [Automattic/jetpack#2758]
Hi, I activate the post formats for "jetpack-portfolio" CTP, but is it possible to activate only some formats instead all the list, even if the "post" type allows all the list?

I tried with 

```php
	add_post_type_support( 'jetpack-portfolio', 'post-formats', array(
		'video', 'gallery'
	) );
```

but with no luck. Any advice? 

TIA

**Comment by jeherve** [comment]
I'm afraid that won't be possible. The list of supported formats is defined for the whole site, it's currently not possible to define a different list for each post type.

If you'd like WordPress to handle different supported formats for each post type, I'd suggest that you open an enhancement request on [core.trac.wordpress.org](https://core.trac.wordpress.org/).

**Comment by pixedelic** [comment]
If I create a custom post type from scratch I can decide what formats to enable, I always used this function to do that, before the Jetpack adopted post types as well:

```php
add_action( 'load-post.php','what_portfolio_post_format' );
add_action( 'load-post-new.php','what_portfolio_post_format' );
function what_portfolio_post_format() {
    if ( 'portfolio' == what_current_post_type() )
        add_theme_support( 'post-formats', array( 'video', 'gallery' ) );
}

function what_current_post_type() {
    global $post, $typenow, $current_screen;

    if ($post && $post->post_type)
        return $post->post_type;

    elseif ($typenow)
        return $typenow;

    elseif ($current_screen && $current_screen->post_type)
        return $current_screen->post_type;

    elseif (isset($_REQUEST['post_type']))
        return sanitize_key($_REQUEST['post_type']);

    return null;
}
```

I know it is a workaround, but it worked for CPTs created in the default way... just to let you know it. However thank you for the reply.

Manuel :-)

**Comment by jeherve** [comment]
Oh, nice workaround :+1:
