### ISSUE TITLE
Feature Request: Featured Content block

### ISSUE THREAD

**Issue by RavanH** [Automattic/jetpack#27620]
### Impacted plugin

Jetpack

### What

Trying to create a block theme based on tt3 but inspired by the Gazette theme, I am looking to integrate the Featured Content feature from Jetpack (in a similar fashion as Gazette) where the featured content can be both posts and pages.

### How

Activating the featured content allows an admin to define a custom tag that determines featured content (as expected) except for one thing:

I can add a dedicated Loop block that displays either posts or pages that are assigned to the custom tag but cannot get both pages and posts to show in the same loop…

A dedicated Featured Content block would do just the trick 🙂

For info, what I'm currently applying as a work-around, to show both featured pages and posts in a Query Loop block that is set to filter by the Featured Content tag, and to show pages in tag archives:

```
function my_jetpack_setup() {
	// Add theme support for Featured Content.
	add_theme_support( 'featured-content', array(
		'filter'            => '___return_false', // Not used but must be set.
		'post_types' => array( 'post', 'page' )
	) );
}
add_action( 'after_setup_theme', 'my_jetpack_setup' );

/**
 * Add pages to Query Loop block tag  query
 *
 * @param obj $query Query object.
 * @return obj $query
 */
function add_pages_to_query_loop_block_tag_query( $query ) {
	if ( ! empty( $query['tax_query'] ) ) {
		foreach ( (array) $query['tax_query'] as $tax_query ) {
			if ( isset( $tax_query['taxonomy'] ) && 'post_tag' === $tax_query['taxonomy'] ) {
				$query['post_type'] = array( 'post', 'page' );
				break;
			}
		} 
	}

	return $query;
}
add_filter( 'query_loop_block_query_vars', 'add_pages_to_query_loop_block_tag_query' );

/**
 * Add pages to tag archive query
 * https://css-tricks.com/snippets/wordpress/make-archives-php-include-custom-post-types/
 *
 * @param obj $query Query object.
 * @return obj $query
 */
function add_pages_to_tag_archive_query( $query ) {
	if ( is_tag() && empty( $query->query_vars['suppress_filters'] ) ) {
		$query->set(
			'post_type',
			array( 'post', 'page' ),		
		);
	}
	return $query;
}
add_filter( 'pre_get_posts', 'add_pages_to_tag_archive_query' );
```

**Comment by jeherve** [comment]
Closing this issue since the Featured Content feature has now moved to a separate package.
