### ISSUE TITLE
VideoPress: correct the logic to show space progress bar in WoA

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#27625]
After installing Jetpack VideoPress on a site with the WordPress.com Pro plan, I see this progress bar (0% of 1 B):

![Image](https://user-images.githubusercontent.com/16329583/204268998-c3935a31-d579-4b08-af73-347f5fe85ff9.png)

---

The same happened with a WordPress.com eCommerce plan:
![Image](https://user-images.githubusercontent.com/16329583/204267884-249e9043-bfed-4a2a-9656-879cae1c10cb.png)

Test site: https://testingvideos5.wpcomstaging.com/

Steps to reproduce:
1- Create a WoA site with a Business / eCommerce / Business plan
2- Install VideoPress and addd a video
3- Check the progress bar

**Comment by lhkowalski** [comment]
Do you remember seeing some error on the console, or some network request failing? Maybe it's the space usage request that is failing for some reason.

**Comment by nunyvega** [comment]
I'm sorry for not getting back to you sooner, I missed the notification. 
No errors in the console. I'm testing it at https://nunyvega.com/, using VideoPress 1.2

**Comment by dhasilva** [comment]
https://github.com/Automattic/jetpack/issues/28997
Not only the `1 B` part is wrong, the percentage is also wrong, apparently stuck at 0.

**Comment by dhasilva** [comment]
p1678111760570209-slack-C9W0QF6KA
Tried a different endpoint, without success.

**Comment by dhasilva** [comment]
Storage meter removed from Atomic sites. Further research is needed on how to get the storage space:
p1678803871055059-slack-C03N25JPCE4
