### ISSUE TITLE
Customizer: Theme name fields are cropped

### ISSUE THREAD

**Issue by Clorith** [Automattic/jetpack#27622]
### Impacted plugin

Jetpack, None / Other

### Steps to Reproduce

Using a classic theme, without support for the Site Editor;

- Visit the customzier
- Click to change your current theme
- Observe the theme names being cut short

### Other information

![Image showing the title section of themes being smaller than intended](https://user-images.githubusercontent.com/468735/204154106-e14af006-fa28-4af1-9d0f-ab493540d2a8.png)
A screenshot indicating the shortened theme name fields.

The cause is the following style implemented by `jetpack/_inc/blocks/editor.css`;

```
* {
    box-sizing: border-box
}
```

This only impacts the theme selector within the Customizer, the standalone Themes screen is not showing this behavior.

### Reproducibility

Consistent

**Comment by coder-karen** [comment]
Thanks for this report @Clorith !

To cross-link: Also mentioned here - https://github.com/Automattic/wp-calypso/issues/70329

Internal ref: p1669287540640319-slack-CDLH4C1UZ
