### ISSUE TITLE
VideoPress: tracks with a source language longer than 5 letters don't upload

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#27647]
When uploading tracks to a video, if the Source Language field has more than 5 letters, the upload does not work and returns an error. This limit does not apply to titles using numbers.

---

Example:

https://user-images.githubusercontent.com/16329583/204518463-cc5f726c-8491-4673-a84d-2519bdb5e2dc.mov

---
Steps to reproduce:
1- Upload or select a previously uploaded video
2- Select on the Text Tracks button
3- Select a Vtt file and fill the form
4- Try adding a Source language composed only of letters, and with more than 5 letters
5- Check the console for this error:

![Image](https://user-images.githubusercontent.com/16329583/204519123-0df1b615-0c31-423d-9f9d-d83b89469af5.png)

**Comment by dhasilva** [comment]
Seems to be related only to subtitles. p1669991266781809/1669990121.737919-slack-C03TA48NSUX

**Comment by lhkowalski** [comment]
Is it possible that the plan was to limit the field to strings following a locale format, like `en` or `pt-BR` or `en_UK`? If that is the case, maybe we should reforce this idea on the source language field label, as well as enforce it on the maxlength of the field.
