### ISSUE TITLE
Carousel & TG: Core adds array to image_meta, causing Jetpack notices.

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2765]
Some plugins like [Video Thumbnails](https://wordpress.org/plugins/video-thumbnails/) create images from videos, and in the process create image meta data. Here is an example of Meta data created by that plugin:

```
["image_meta"]=> array(12) {
		["aperture"]=> int(0)
		["credit"]=> string(0) ""
		["camera"]=> string(0) ""
		["caption"]=> string(0) ""
		["created_timestamp"]=> int(0)
		["copyright"]=> string(0) ""
		["focal_length"]=> int(0)
		["iso"]=> int(0)
		["shutter_speed"]=> int(0)
		["title"]=> string(0) ""
		["orientation"]=> int(0)
		["keywords"]=> array(0) {
		}
	}
```
That last item is a problem: it's an array, and in Tiled Galleries we expect all image meta data to be strings:
https://github.com/Automattic/jetpack/blob/3.7/modules/tiled-gallery/tiled-gallery/templates/partials/carousel-image-args.php#L5

That array generates the following notice:

```
[28-Sep-2015 12:00:37 UTC] PHP Notice:  Array to string conversion in wp-content/plugins/jetpack/modules/tiled-gallery/tiled-gallery/templates/partials/carousel-image-args.php on line 5
```

We'd need to transform that array into a string before it's processed by the Tiled Galleries.

**Comment by kraftbj** [comment]
Keywords were added to Core in https://core.trac.wordpress.org/changeset/34374, which is what is tripping us up.

Also needs to be updated in carousel/jetpack-carousel.php .

**Comment by kraftbj** [comment]
Added a bandaid to stop the notices to prevent any support load issues if upstream/JP teams don't have the bandwidth to properly patch before 4.4 is released.

**Comment by thefrosty** [comment]
I still see this PHP notice happening in the latest version _4.4.1_ in PHP _7.0.10_

**Comment by jeherve** [comment]
@thefrosty Do you happen to use the [Video Thumbnails](https://wordpress.org/plugins/video-thumbnails/) plugin I mentioned in the original post, or another plugin that creates or customizes your images' meta data?

If you use another solution, could you tell me more about it, so I can try to reproduce the issue on my end?

Thanks!

**Comment by thefrosty** [comment]
I do not have the Video Thumbnails plugin. Could it be the [Exifography](https://wordpress.org/plugins/thesography/) plugin?

**Comment by jeherve** [comment]
@thefrosty It could be, yes. What happens when you deactivate it, upload new images, and create a gallery? Do you still experience issues?
