### ISSUE TITLE
[Boost] Update onboard dialogues w/a link to add a license key

### ISSUE THREAD

**Issue by ilonagl** [Automattic/jetpack#27670]
![Boost pricing table](https://user-images.githubusercontent.com/100145243/204770799-4dd26501-156c-43ef-a096-65d6a6fceddc.png)

Task: 
- Add a link: "Already have an existing plan or license key? Click here to get started" at the top of right corner in the pricing table.

Flow after pressing the link: 
<img width="15115" alt="Proposed flow-8" src="https://user-images.githubusercontent.com/100145243/204769797-32443b33-70ca-4426-b640-858bc2ef83fa.png">

**Comment by thingalon** [comment]
This has been done thanks to @mattgawarecki :) over here: https://github.com/automattic/jetpack/pull/29443
