### ISSUE TITLE
$origin value defined

### ISSUE THREAD

**Issue by yaronguez** [Automattic/jetpack#2768]
Slider arrows rendered by a CDN loaded custom font were breaking on the front end of our website but not the backend.  WP Engine support tracked the problem to Jetpack and fixed it by modifying Jetpack's files.  Here are their details:

"The JetPack plugin is defining the $origin value in this file:
wp-content/plugins/jetpack/class.json-api.php:181: header('Access-Control-Allow-Origin: *' );
The reason the arrows weren't working is because the $origin value is taking in the wrong value in Jetpack. For now, I've edited this to allow the correct  value. However, if Jetpack is updated, it will break the value again. We recommend contacting Jetpack to see if there's an option to change that somewhere else."

**Comment by kraftbj** [comment]
Could you provide a bit more info so we can duplicate the failure and confirm the fix?

At first glance, it looks like it should only have been set if the path included `help` so like to confirm how to duplicate it on our end.

Thanks!

**Comment by yaronguez** [comment]
We're using Theia Post Slider which you can see here: http://www.collegemagazine.com/7-drugs-millennials-hooked/

The arrows are rendered using a font loaded at this location:
http://2qeyae30zrn91lya8t3kudic.wpengine.netdna-cdn.com/wp-content/plugins/theia-post-slider/fonts/fonts/theia-post-slider-font.woff?h2p4uy

We migrated the site to WP Engine and the font did not load properly and the arrows rendered as boxes.  We contacted WP Engine support and they fixed the problem and replied with the message posted above.  I emailed the details to Jetpack support and was asked to post it  here.

Sorry I can't be more helpful!

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
