### ISSUE TITLE
Boost: z-index of tooltip goes under toggle switch

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#27706]
### Impacted plugin

Boost

### Steps to Reproduce

1. Go to boost settings page
2. Hover on the tooltip next to "Overall Score"

### A clear and concise description of what you expected to happen.

Tooltip should appear above everything else.

### What actually happened

![GcSDep.png](https://user-images.githubusercontent.com/3737780/205052725-b22b90d3-7a28-432b-8e1e-fd573b916f89.png)

### Browser

Google Chrome/Chromium

### Other information

![GcSDep.png](https://user-images.githubusercontent.com/3737780/205052725-b22b90d3-7a28-432b-8e1e-fd573b916f89.png)

### Platform (Simple, Atomic, or both?)

Atomic, Self-hosted

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by dilirity** [comment]
It appears this has been resolved with the 1.6.0 update.

![image](https://user-images.githubusercontent.com/11799079/210565413-d7a301d4-2fd2-4e7c-911e-d8ec29c2c840.png)

**Comment by thingalon** [comment]
Closing since this is apparently resolved.
