### ISSUE TITLE
Better IDC messages

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#2770]
Great feedback from @beaulebens:

> I think it’d make sense to have the options be super explicit, and say something like `{domain} is now my domain | {domain} is still my domain`

![screen shot 2015-09-28 at 4 17 32 pm](https://cloud.githubusercontent.com/assets/426388/10161755/95828bfe-66a6-11e5-86e3-ddcfb9585c93.png)

**Comment by jeherve** [comment]
Reopening this, as we'd need to add the domain name to all the messages, not just the initial one.

e.g. `This is a development environment` could be `{domain}  is a development environment`

**Comment by dereksmart** [comment]
This was totally reworked and is no longer relevant
