### ISSUE TITLE
Enhancement: Move and resize pagination dots in Slideshow Block

### ISSUE THREAD

**Issue by ilonagl** [Automattic/jetpack#27708]
### Impacted plugin

None / Other

### What

Pagination dots can align better in scale, look, and behavior with the carousel example

### How

Pagination dots can align better in scale, look, and behavior with the carousel example.

Main change: 
Improve the pagination dots to mirror the Gallery designs. Please note we also aim to make the spacing between dots 8px.  

Point of contact: @ilonagl
<img width="3180" alt="Designs" src="https://user-images.githubusercontent.com/100145243/205078301-81085758-dca4-498e-9254-312a2cdf4017.png">

**Comment by jeherve** [comment]
Related issue: #27712
