### ISSUE TITLE
Enhancement: Replace pagination dots with numbers when >5 in Slideshow Block

### ISSUE THREAD

**Issue by ilonagl** [Automattic/jetpack#27709]
### Impacted plugin

None / Other

### What

When more than 5, numbers are used instead of dots. Which could be a relevant parity without adding infinite dots.

### How

Main change: 
When more than 5, use numbers instead of dots. 

When more than 5, numbers are used instead of dots. Which could be a relevant parity without adding infinite dots.

Point of contact: @ilonagl
<img width="4172" alt="Designs-2" src="https://user-images.githubusercontent.com/100145243/205078851-fe35a4c9-5b5a-4284-ad2d-ed81dffc99e7.png">

**Comment by jeherve** [comment]
See the Carousel for an implementation of that logic:
https://github.com/Automattic/jetpack/blob/feffc93b2a65f8eee405e0d60e4253dece023b52/projects/plugins/jetpack/modules/carousel/jetpack-carousel.js#L445-L454
