### ISSUE TITLE
Enhancement: Change arrows in Slideshow Block

### ISSUE THREAD

**Issue by ilonagl** [Automattic/jetpack#27710]
### Impacted plugin

None / Other

### What

Arrows can align better in scale, look, and behavior with the carousel example.

### How

Arrows can align better in scale, look, and behavior with the carousel example.
![Designs-3](https://user-images.githubusercontent.com/100145243/205079324-6328e6fe-a078-4e96-a884-7042c419aede.png)

Main change: 
Update arrows to match the current gallery design.

Point of contact: @ilonagl

**Comment by jeherve** [comment]
Related: #27770 #25326

**Comment by lhkowalski** [comment]
I made the change, and it looks nice on a light theme:

<img width="685" alt="Screen Shot 2022-12-13 at 18 25 56" src="https://user-images.githubusercontent.com/6760046/207578879-28af88f7-0ade-449c-954b-5b575a06643c.png">

But I am not sure it looks the right way when the site has a dark theme:

<img width="667" alt="Screen Shot 2022-12-14 at 10 43 05" src="https://user-images.githubusercontent.com/6760046/207577786-fce90e27-975d-4d2b-a1bc-8840a52523be.png">

(This is just for the arrows, the bullets are still in progress)

@ilonagl Is this acceptable, or should we design/rethink a dark version?

**Comment by lhkowalski** [comment]
I chatted with @ilonagl about the style and she thinks the arrows are good but that we could try to improve the position of it so it won't be over the images.

The reference for it is the tiled gallery's carousel, but the carousel has the full screen available for it. Given that the slideshow is always embedded on a post, we have a limited width available when compared to the reference.

The width of the image on my previous example does not help to ilustrate things. Currently the buttons are fixed, so they can be aligned or not with the edges of the image, but they are always on the same place, fixed like the pagination bullets are.

This is how they look like for different images:

<img width="800" alt="Screen Shot 2022-12-14 at 16 10 48" src="https://user-images.githubusercontent.com/6760046/207648354-b600469a-8592-4cbb-b66c-85df25a0f287.png">

<img width="800" alt="Screen Shot 2022-12-14 at 16 11 02" src="https://user-images.githubusercontent.com/6760046/207648367-039df01b-482c-480e-b02f-73c36d527b81.png">

<img width="800" alt="Screen Shot 2022-12-14 at 16 11 19" src="https://user-images.githubusercontent.com/6760046/207648387-51f422b6-179a-40c5-a69f-a629c29cf91c.png">

The arrows may look like randomly positioned on certain images, but they are actually on the borders of the slideshow block. Some of the changes that we are doing related to the navigation bullets will help to "define" these borders.

So I think we could keep the current positioning and re-evaluate after all the changes if everything is sound or if something is off.

@ilonagl what do you think?

**Comment by lhkowalski** [comment]
I got a green light from Ilena (thanks!).
