### ISSUE TITLE
Form Block: Name field block allows for the label multiline input - not rendered in published view

### ISSUE THREAD

**Issue by digitalwaveride** [Automattic/jetpack#27732]
The Name Field block allows multiline input, while on front end though, these new line characters are removed.

![Image](https://user-images.githubusercontent.com/5120357/205278673-6fceb391-e075-4614-9e71-cd93c29cf6ac.png)

Issue was raised here: p8oabR-10q-p2#comment-6836

**Comment by jeherve** [comment]
Closing as duplicate of #20292.
