### ISSUE TITLE
REST API: Missing get_post_permalink_suggestions() method.

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2773]
e0485f2b5bb072573cbcacd42707c428d9d5f637 added a reference to `get_post_permalink_suggestions()` that isn't present in the codebase. Results in fatals when trying to post via the REST API to a JP site.

**Comment by gcorne** [comment]
Is there some way that we can set stuff up so that we have REST API tests that are run? This is something that could have easily be caught via an automated test suite.

**Comment by dereksmart** [comment]
First thought is to add the `/bin/tests/api` suites to our current unit tests / build script, and `svn ignore` the files, but I haven't looked at if it has any wpcom dependencies that would also need to be ported over
