### ISSUE TITLE
VideoPress: show site default privacy in video block control

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#27737]
It would be handy for the users to show the default privacy when setting it in the video block.

![Image](https://user-images.githubusercontent.com/77539/205309625-4bb30155-547f-4642-843c-ee24429162e0.png)

![Image](https://user-images.githubusercontent.com/77539/205309607-a67ee8ae-104d-4536-8d4b-dd46b8ad7efb.png)

**Comment by lhkowalski** [comment]
What do you think about showing the option as "Site Default (public)" / "Site Default (private)" in the cases the setting is public / private?

Alternativelly, it could be a label under the field: "Site Default current setting is X"?

**Comment by retrofox** [comment]
D99262-code exposes relevant field to know the privacy

**Comment by retrofox** [comment]
r260058-wpcom
