### ISSUE TITLE
[bug] Writing Prompts: Pasting block content into the editor "title" does not remove prompt

### ISSUE THREAD

**Issue by roo2** [Automattic/jetpack#27747]
Reported here p1669932017688329-slack-C03NLNTPZ2T when pasting block content into the title field - e.g. if writing a post in google docs and then pasting it into the editor - the writing prompt is not cleared.

https://user-images.githubusercontent.com/22446385/205524656-38cb5b6b-e9e0-4bbd-8063-fcfdeb1c854b.mov

**Comment by davemart-in** [comment]
Looks to be related to: https://github.com/Automattic/wp-calypso/issues/70741

**Comment by roo2** [comment]
should no longer be an issue now that we no longer show the prompt by default https://github.com/Automattic/jetpack/pull/27919. With the quote block, the pasting behavior is more what you'd expect
