### ISSUE TITLE
Enhancement: Add transition controls for lightbox mode in the Gallery block

### ISSUE THREAD

**Issue by ilonagl** [Automattic/jetpack#27762]
### Impacted plugin

None / Other

### What

 There are no transition controls like slide or fade for Gallery block. Slideshow does have them. Please copy the Slideshow behaviour and apply it to the Gallery block.

### How

**Task:** copy the slideshow transition controls settings & behaviour and add it in the gallery settings (after dimensions settings/before Advanced settings). 

Proposed Gallery settings design with transition effects: 
<img width="1440" alt="Gallery block" src="https://user-images.githubusercontent.com/100145243/205891740-8feef875-50f6-448a-aef2-be1520a363fa.png">

Current Slideshow settings: 
<img width="1510" alt="Slideshow settings-2" src="https://user-images.githubusercontent.com/100145243/205892621-a961a223-be42-4a10-82b3-ec104174ba83.png">

**Comment by jeherve** [comment]
Since this is about changes to the Gallery block, I would recommend that you make that suggestion in the Gutenberg repository, where the Gallery block is developed by the WordPress community.
