### ISSUE TITLE
Related Posts: add filter to control _generate_related_post_context

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#278]
Some folks don't really use categories on their sites, but still use one single "Blog" category for example. This results into the category being displayed under all Related Posts.

It would be nice to add a filter to `_generate_related_post_context` to allow people to override the default behaviour.

Suggested here:
- https://twitter.com/ScottBeale/status/439103031079342080

**Comment by yuk75** [comment]
How do we use this exactly? :)

**Comment by jeherve** [comment]
@yuk75 Here is an example:
http://jetpack.me/support/related-posts/customize-related-posts/#nocontext

If you need more help, do not hesitate to post in the [Jetpack support forums](http://wordpress.org/support/plugin/jetpack) or [send us an email](http://jetpack.me/contact-support/)!
