### ISSUE TITLE
Revue block: retire

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/jetpack#27806]
A user reported that Revue is being shut down at the end of the year: 5704548-zd-woothemes

I couldn't find an official announcement from Twitter but I found this link: https://www.theinformation.com/briefings/twitter-will-shut-down-newsletter-product-revue-by-year-end

Sharing this here because it seems a decision will need to be made about supporting the block moving forward.

**Edit**: this is now official, as per an email sent to all Revue users:

**from January 18, 2023, it will no longer be possible to access your Revue account.**

**Comment by simison** [comment]
FYI, product convo p58i-dGf-p2#comment-56530
