### ISSUE TITLE
Lightbox Carousel feature in Jetpack slideshow

### ISSUE THREAD

**Issue by eutravelmag** [Automattic/jetpack#27811]
### Impacted plugin

Jetpack

### What

I would like that, in a Jetpack slideshow, when clicking on an image, it would open in a Lightbox carousel. Just like the photos do in the other gallery types. Oftentimes the images in a slideshow are too small (especially on mobile devices) to be seen properly. A lightbox carousel feature would greatly enhance the user experience

**Comment by jeherve** [comment]
Thanks for the suggestion! I'll close this issue, since we're tracking this issue in #24537 now.
