### ISSUE TITLE
Media Extractor: Mentions fail on PHP 5.2

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2785]
As part of #2784, there was one test failing in 5.2 that I couldn't determine why.

https://github.com/Automattic/jetpack/blob/update/travis-matrix/tests/test_class.jetpack-media-extractor.php#L385-L408

Instead of the expected array, an empty one was being returned. Nothing obviously looked amiss.

**Comment by samhotchkiss** [comment]
@kraftbj: that link isn't working for me-- is this issue still valid?

**Comment by kraftbj** [comment]
Yup, it is. https://github.com/Automattic/jetpack/blob/3.8.0/tests/php/test_class.jetpack-media-extractor.php#L385-L408

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
