### ISSUE TITLE
Subscription block: error warning

### ISSUE THREAD

**Issue by bindlegirl** [Automattic/jetpack#27882]
### Impacted plugin

Jetpack

### Steps to Reproduce

Check the error logs:

PHP Warning: Undefined array key "include_social_followers" in /modules/subscriptions/views.php on line 860

1203451499502244-as-1203529637089977/f

### A clear and concise description of what you expected to happen.

This new error was most likely introduced by https://github.com/Automattic/jetpack/pull/27443

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by bindlegirl** [comment]
@TimBroddin could you check this out? I think it's related to the https://github.com/Automattic/jetpack/pull/27443

**Comment by TimBroddin** [comment]
I created a PR. I'll get someone from my team to review it. 
Thanks for pointing this out, I'll check for PHP warnings in my future PR's 🤝
