### ISSUE TITLE
Remove no-follow on Sharedaddy links?

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#2788]
In 2364911-t the user explained that some SEO-monitoring software says that the no-follow links on anything in a site can lead to penalties from Google. The user requests a way to turn off the no-follow links in the Sharing links. A filter would be the way to go if we want to allow turning them off.

**Comment by jeherve** [comment]
I'm not sure we'd want search engines to follow these links: they're not real pages, they're just placeholders before each Social Network is loaded.

Here is what Google has to say about nofollow links:
[Use rel="nofollow" for specific links](https://support.google.com/webmasters/answer/96569?hl=en)

> Here are some cases in which you might want to consider using `nofollow`:
>
> - Untrusted content
> - Paid links
> - Crawl prioritization

"Crawl prioritization" is relevant here: Search Engines can't share your posts on Social Networks, so there's no reason to invite Googlebot to follow these links. Using `nofollow` on these links enables Googlebot to crawl other pages you'd prefer to see in Google's index

Closing this as `wontfix`.

**Comment by thelasthurdle** [comment]
I am disappointed that isn't a decision left to the user. I am not sure why this stance is taken, having this as an option should be down to the user surely?  But your prerogative... in this instance Jetpack can't give me what I need so will employ a different programme that will, thanks for your consideration.
