### ISSUE TITLE
Form Responses in the email are no longer formatted

### ISSUE THREAD

**Issue by danielk-am** [Automattic/jetpack#27897]
### Quick summary

Form responses in the emails appear to be unformatted, since Dec 1, 2022.

I was able to replicate the issue on Gmail, where the class, `.field-name`, is no longer bold, and each div appears in a new line.

Was there anything that changed on our side?

18229723-hc → 5763907-zen

### Steps to reproduce

1. Add a Form block to a page and publish it.
2. Submit a form.
3. Check the email (I used Gmail).

### What you expected to happen

Each item was previously on the same line, where the `.field-name` was bold.

### What actually happened

The formatting was removed.

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by thekingsprojects** [comment]
Another case here:

- [ ] 5763410-zen

I also tested with my own site and the Apple Mail and Thunderbird email clients; the formatting is gone from recent form response emails, where as it is present in older emails I check.

**Comment by happychait** [comment]
Another report with missing formatting in contact form response notification emails: 5759264-zen

**Comment by danielk-am** [comment]
Another case here:
5765356-zen

**Comment by MaxPhilip** [comment]
Another case:
5762670-zen

**Comment by sophiegyo** [comment]
Another case: https://wordpress.com/forums/topic/an-update-must-have-changed-the-way-i-receive-submited-orders-please-help/?view=all

I was also able to replicate it myself.

**Comment by jorpdesigns** [comment]
Reported in 38307071-hc. The form block labels in notification emails are no longer bold.

- [ ] Follow-up ticket: 5769147-zen

**Comment by kelasante** [comment]
Another report here - 38526270-hc. They say they first noticed the issue around December 1st. Additionally, I am able to replicate on my simple and atomic testing sites in Gmail.

**Comment by hacchism** [comment]
Another report in 5771534-zen.

**Comment by happychait** [comment]
Another report in 38524474-hc

**Comment by danielk-am** [comment]
A user returned to check if there are any updates to this issue.

Tried pointing them to the Feedback Form Responses screen to copy and paste the entries, but they found that it is not a fit for their copy and paste usage.

38512441-hc

**Comment by sguzovskaia** [comment]
Another report in 5779670-zen

First, the user noticed it happening with a form created by using the Classic Editor. Then they tested creating a new form using Form block on a new page. The resulting email is still not formatted according to the previous style.

**Comment by deancroyal** [comment]
Another report in 22018708-hc

**Comment by jordesign** [comment]
I've confirmed that this takes place in Simple, Atomic, and self-hosted sites with the Jetpack block inserted.

Here's an example of the formatting. 

<img width="528" alt="Screen Shot 2022-12-13 at 6 02 35 pm" src="https://user-images.githubusercontent.com/1842363/207248511-2be735d6-2f85-4343-a2e8-373f0b6861e0.png">
 
To mind - this means the potential reach is quite great, even though we've only seen a handful of reports.

**Comment by jeherve** [comment]
We've been actively working on many changes to the feature in the past month. We made changes to the form output in #27392, and that impacted the output of the emails as well. We are on track to make even more changes in the future (see #27752).

So the changes were done on purpose, as you can see. There was an initial bug with the output of the emails (I think that's what's reported in some of the tickets above), but that was fixed in #27723.

That doesn't mean we can't do better though. Maybe we could see about adding bold for the form items again. @donnchawp @digitalwaveride What do you think?

**Comment by digitalwaveride** [comment]
We are looking into a fix, the planned formatting:

![image](https://user-images.githubusercontent.com/5120357/207391355-2e9dbe48-a1e8-43a4-8520-794de5b3143c.png)

**Comment by jorpdesigns** [comment]
- [ ] Reported in 5786313-zen

**Comment by happychait** [comment]
Another report in 21123719-hc
