### ISSUE TITLE
Add HTTP Status Codes and Descriptions to Monitor Emails

### ISSUE THREAD

**Issue by macmanx2** [Automattic/jetpack#2796]
"Your site is down" is helpful, but often not enough information for the site owner, and definitely not enough information for their hosting provider.

Since the Monitor bot itself identifies the HTTP status code, we should pass that along to the site owner in the downtime email. Some may understand what it means, but most will pass it along to their hosting provider who will definitely know what it means.

And, speaking of those who don't know what it means, we should include a short concise definition of the particular HTTP status code, like https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

**Comment by csonnek** [comment]
+1 to this idea.

**Comment by kraftbj** [comment]
Noting that it would require an update to Jetmon itself and to the `class.jetmon-endpoint.php` on wp.com for processing, in addition to language in the e-mail.

**Comment by jeherve** [comment]
Closing as this was implemented.
