### ISSUE TITLE
VideoPress: improve building system

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#28016]
A recent change exposed a problem with the building of the VideoPress plugin. The final bundle is relying on 2 files from the `src/client` directory:

- `$videopress_extensions_file = __DIR__ . '/client/block-editor/extensions/index.json';` on [class-block-editor-extensions.php](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/videopress/src/class-block-editor-extensions.php)
- `$videopress_video_metadata_file = __DIR__ . '/client/block-editor/blocks/video/block.json';` on [class-initializer.php](https://github.com/Automattic/jetpack/blob/01e736f4025a81f25e212e1b97992a1d9dff9d33/projects/packages/videopress/src/class-initializer.php)

This caused the block to not appear on the block editor after we removed `src/client` from the final bundle (#27926).

We [brought back the client source to the bundle](https://github.com/Automattic/jetpack/pull/27979/commits/0480a15211875b033b27c0930300bef2c1566de5) to tentatively solve the issue, but now it's time to fix the building process to:

- make sure we have the mentioned JSON files on the `build` folder
- reference only the `build` code on the final bundle
- not bundle the `src/client` folder

**Comment by anomiex** [comment]
FYI, Jetpack-the-plugin and packages/lazy-images both use [copy-webpack-plugin](https://www.npmjs.com/package/copy-webpack-plugin) to copy some files during the webpack build. If that's the direction you're looking to go, it'd be good to use the same solution.
