### ISSUE TITLE
Jetpack loads unscoped CSS in the editor

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#28038]
### Impacted plugin

Jetpack

### Steps to Reproduce

When Jetpack plugin is active and connected, following CSS gets loaded at the editor:

```css
* {
	box-sizing: border-box;
}

body {
	min-height: 100%;
	margin: 0;
	padding: 0;
	font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen-Sans', 'Ubuntu',
		'Cantarell', 'Helvetica Neue', sans-serif;
}
```

Especially applying `box-sizing: border-box;` so widerly from a plugin is problematic. We discovered (p1671618034894909-slack-CBTN58FTJ) that this was causing "reading time" panel in Gutenberg to break visually:

![image](https://user-images.githubusercontent.com/87168/208912921-4237dedb-c953-4170-aee7-cf8225d29a92.png)

[Protecting the element better](https://github.com/WordPress/gutenberg/pull/46648#issuecomment-1361161221) from such breakage in Gutenberg fixes the issue, but this could still be causing more trouble elsewhere.

The CSS originates from [Jetpack base styles](https://github.com/Automattic/jetpack/blob/2a990efa4b3d7499dbfe8cb461af6064468f8e37/projects/js-packages/base-styles/style.scss#L86-L96) package, imported in blocks related code added [in the PR 3 months ago](https://github.com/Automattic/jetpack/pull/25852):

https://github.com/Automattic/jetpack/blob/a958428a66bf9bf195eaf80a2a8c476642ea5b2f/projects/plugins/jetpack/extensions/index.scss#L1-L3

Typically styles in such packages are wrapped in mixins or functions to avoid outputting CSS on mere import; 
if imported sass file outputs CSS on import, you might end up the same CSS multiple times in bundles, importing more than you intendendent, etc.

Overly global selectors are avoided as well and instead CSS should be applied to more specific wrapper elements. 

See [Gutenberg base styles](https://github.com/WordPress/gutenberg/tree/a03158d8ffd8fa9170925bacbe7ead242925fdb3/packages/base-styles) as an example:
- [Admin schemes mixin](https://github.com/WordPress/gutenberg/blob/299b85e17b564f1f993328fdb46d71e70bec9a2d/packages/base-styles/_mixins.scss#L460-L492) and [usage](https://github.com/WordPress/gutenberg/blob/e5a49dc96c899fbca3ba677770167bb42c3593a3/packages/edit-post/src/style.scss#L100).
- [CSS reset mixin](https://github.com/WordPress/gutenberg/blob/299b85e17b564f1f993328fdb46d71e70bec9a2d/packages/base-styles/_mixins.scss#L404-L439) and [usage](https://github.com/WordPress/gutenberg/blob/e5a49dc96c899fbca3ba677770167bb42c3593a3/packages/edit-post/src/style.scss#L50-L52).
- [CSS wp-admin reset mixin](https://github.com/WordPress/gutenberg/blob/299b85e17b564f1f993328fdb46d71e70bec9a2d/packages/base-styles/_mixins.scss#L404-L439) and [usage](https://github.com/WordPress/gutenberg/blob/e5a49dc96c899fbca3ba677770167bb42c3593a3/packages/edit-post/src/style.scss#L50-L52).
- [CSS ui component reset mixin](https://github.com/WordPress/gutenberg/blob/299b85e17b564f1f993328fdb46d71e70bec9a2d/packages/base-styles/_mixins.scss#L385-L398) and [usage](https://github.com/WordPress/gutenberg/blob/7dbb88da05d84af00f9998ffd5c55c133acbf078/packages/edit-widgets/src/style.scss#L27-L30).

### A clear and concise description of what you expected to happen.

I think there are multiple issues at play:

- Jetpack base styles should be written as mixins, not outputted on import.
- Styles should be scoped more tightly to specific, Jetpack related elements (no `body` and `*`).
- [Further feedback in the original PR](https://github.com/Automattic/jetpack/pull/25852#issuecomment-1361328916)

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by anomiex** [comment]
Note #27622 exists describing the same underlying issue, and already has a PR attached. Let's consolidate discussion there.
