### ISSUE TITLE
Subscribe Block: Button has broken styling if "Place button on new line" is set

### ISSUE THREAD

**Issue by mikachan** [Automattic/jetpack#28037]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Insert a Subscribe block
2. In Settings, set the "Place button on new line" toggle to true
3. The form in the editor looks correct
4. View the form on the front end, and notice how the button styling is broken:

![image](https://user-images.githubusercontent.com/1645628/208909121-8fcb10be-e040-4117-88b9-2b18a911d072.png)

The style tag comes through as the following: `width: calc(100%spx;font-size: 16px;padding: 15px 23px 15px 23px;margin-top: 10px;border-radius: 0px;border-width: 1px;`

It looks like the `width` property has not been calculated correctly, and it's running into the other styles.

Here is some example markup:

```
<!-- wp:jetpack/subscriptions {"subscribePlaceholder":"Email Address","buttonOnNewLine":true,"buttonWidth":"100%","submitButtonText":"Subscribe","buttonBackgroundColor":"black","customTextColor":"#ffe030","fontSize":"1.75rem","customFontSize":"1.75rem","borderRadius":50,"borderWeight":1,"borderColor":"black","padding":24,"spacing":15,"className":"is-style-split"} /-->
```

### A clear and concise description of what you expected to happen.

I expect the form to display the same on the front end as in the editor.

### What actually happened

The styles seem broken on the front end of the button.

### Browser

Google Chrome/Chromium

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

None

**Comment by jeherve** [comment]
@mikachan Do this happen when using a specific theme on your site right now? I cannot seem to reproduce on Twenty Twenty Three, for example, so I wonder if this may be theme-dependent. 

Thank you!

cc @digitalwaveride ; does this ring a bell to you? I'm asking since your team has recently made some changes to the Subscribe block.

**Comment by mikachan** [comment]
Thanks for taking a look! I tested this on Lettre, Muscat, and Twenty Twenty-Three, and I could reproduce it in all three themes. It would've helped if I'd added example markup.. here's the markup I'm seeing it on:

```
<!-- wp:jetpack/subscriptions {"subscribePlaceholder":"Email Address","buttonOnNewLine":true,"buttonWidth":"100%","submitButtonText":"Subscribe","buttonBackgroundColor":"black","customTextColor":"#ffe030","fontSize":"1.75rem","customFontSize":"1.75rem","borderRadius":50,"borderWeight":1,"borderColor":"black","padding":24,"spacing":15,"className":"is-style-split"} /-->
```

**Comment by jeherve** [comment]
Thank you, that helps! #28057 should fix this.

**Comment by mikachan** [comment]
Thank you!
