### ISSUE TITLE
Infinite Scroll: Unable to set "scroll" type if IS disabled for posts

### ISSUE THREAD

**Issue by codebykat** [Automattic/jetpack#2807]
Setup: I'm working on a friend's site; he wants IS for his portfolio but not his posts. He's using a child theme of twentyfifteen. This worked well enough:

``` php
function custom_theme_infinite_scroll_init() {
    remove_theme_support( 'infinite-scroll' ); // unregister twentyfifteen's version :[

    add_theme_support( 'infinite-scroll', array(
        'container' => 'main',
        'type' => 'scroll',
        'footer_widgets' => false,
        'posts_per_page' => 9,
        'render' => 'custom_theme_infinite_scroll_render',
    ) );
}
add_action( 'after_setup_theme', 'custom_theme_infinite_scroll_init', 11 );

function custom_theme_infinite_scroll_render() { ?>
    php while( have_posts() ) {
        the_post();
        get_template_part( 'content', get_post_type() );
    }
}

/**
 * Enable infinite scroll on portfolio page *ONLY* (not on normal posts).
 */
function custom_theme_jetpack_infinite_scroll_supported() {
    return current_theme_supports( 'infinite-scroll' ) && ( is_post_type_archive( 'jetpack-portfolio' ) );
}
add_filter( 'infinite_scroll_archive_supported', 'custom_theme_jetpack_infinite_scroll_supported' );
```

I thought I was very clever, because now my friend can still enable infinite scroll on his posts someday, if he decides he wants to.

However, now there's a problem: whether I set the "type" to `scroll` or `click`, I always end up with `click`, and couldn't figure out why.

Turns out for some reason JP is forcing it to "click" if the infinite_scroll option is disabled??

https://github.com/Automattic/jetpack/blob/master/modules/infinite-scroll/infinity.php#L204

I know we don't technically support this setup, but why, of all the places to check that option and bail, is that happening there?

Making matters worse, JP arbitrarily ignores the `posts_per_page` option if the type is set to `click`: https://github.com/Automattic/jetpack/blob/master/modules/infinite-scroll/infinity.php#L214

The portfolio page is a 3x grid of images, so the end result of this is that the blog posts _also_ have to be a multiple of 3, because I can't use _either_ the portfolio page setting or the alleged "override" in the infinite_scroll setup. Not great.

(Note that <a href="https://jetpack.me/support/infinite-scroll/">the documentation</a> is wrong about this: "If, however, a theme’s layout expects a certain number of posts, the posts_per_page argument will override the defaults discussed in the preceding paragraph. This control is beneficial, for example, in a theme with a three-column layout where greater or fewer than three posts would result in an uneven layout.")

**Comment by codebykat** [comment]
Clobbering the `posts_per_page` argument for the `click` type was introduced in https://github.com/Automattic/jetpack/commit/a2296f96f9d2c3d9f317b2ad41bbb64eabb24915 by @mcsf. Do you remember why??

**Comment by codebykat** [comment]
SO I slept on this and I think I understand what's happening. The "scroll infinitely" option toggles between `scroll` and `click`. If you have the IS module enabled at all, you no longer have pagination ever.

I don't know if it's a bug or just confusing, and I'm not sure how to fix it. It's definitely a weird UI to have a checkbox for something that has three possible states. I think it might make more sense to have that be a dropdown that lets you explicitly choose between "off" (pagination, as if the module is disabled), "scroll" and "click".

CPT support is its own beast, too. I'm pondering whether I can somehow fix up the portfolio module to magically work with IS, because like... I *expected* that to work out of the box. (Although come to think of it I need to re-test it without a custom template for the portfolio page, argh.)

**Comment by codebykat** [comment]
What would be really cool is if we could support the portfolio type and have it use the `posts_per_page` setting for portfolio pages (which is different from the one for posts), but still have everything work properly for IS on posts.

**Comment by kraftbj** [comment]
@codebykat I'd like to break this out into separate tickets so it is a bit easier to grok the individual issues. Would this be a fair summation:

* On 'click' the `add_theme_supports` arg for posts per page is being ignored. Resolved by #2808.
* When the IS module is on, you only have the option for click or scroll, no "neither". (Note: This is the behavior on wpcom last I checked).
* Portfolio (and other JP CPTs): Add (expected at least) IS support out of the box
* Investigate and provide better support for CPTs having CPT-specific IS options(?)

**Comment by codebykat** [comment]
:+1: And we should also port fixes back to WPCOM as appropriate. Thx @kraftbj and sorry for the rambling Sunday-night issue :)

**Comment by kraftbj** [comment]
No problem! Would rather get the issues reported in a rambling state than none at all! Assuming all of the fixes are in files shared between the platforms, it'll be merged back upstream too.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
