### ISSUE TITLE
Blaze: Update Post-publish button icon and size and Blaze block Priority

### ISSUE THREAD

**Issue by paulopmt1** [Automattic/jetpack#28079]
Follow-up task from https://github.com/Automattic/jetpack/pull/27960

<table>
<tr>
	<td><strong>Before</strong></td>
	<td><strong>After</strong></td>
<tr>
	<td>
<img width="317" alt="Screenshot 2022-12-15 at 15 34 20" src="https://user-images.githubusercontent.com/426388/207890303-6eee5807-01bf-4807-9675-2c62da766186.png">
</td>
	<td>
<img width="329" alt="image" src="https://user-images.githubusercontent.com/1044309/209405449-40089738-ce4a-46cd-872f-c20aceec1ba7.png">

</td>
</table>

Icons can be found here: p1671807306084409/1671659354.405879-slack-C04DZ725FEK
Figma is available here: p1671807505718489/1671659354.405879-slack-C04DZ725FEK

## Requirements

- [ ] Update Blaze Icon
- [ ] Update Blaze Post-publish block priority. Discussion started here: p1671740603310119-slack-C04DZ725FEK

**Comment by jeherve** [comment]
> Update Blaze Icon

This is done in #28155.

> This isn't an option just yet. More discussion about it in #16877.
