### ISSUE TITLE
Display Jetpack Connection Info on User Profiles

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#2813]
It is still not very obvious for all users to find the "My Jetpack" page and see all the users connected to Jetpack. This page is a bit hidden:

![](https://www.evernote.com/shard/s1/sh/e37037e3-59cb-46f7-b09a-e332213d32f9/dc114489e74aa3c0/res/58541b00-e7a6-4589-b1f4-5691f896b6ff/skitch.png?resizeSmall&width=832)

How about adding this tool under the user profiles?
![](https://www.evernote.com/shard/s1/sh/46e780e6-0594-461d-83ef-e2843e5ca7ef/b3db34e4fe594ff4/res/1a70d139-10c5-480b-aed2-c064e868f186/skitch.png?resizeSmall&width=832)

**Comment by jeherve** [comment]
Since we've redesigned the Admin Interface, the connection information is now available as soon as you go to Jetpack > Settings in your dashboard.

Closing this for now.
