### ISSUE TITLE
Manage: is_single_user_site needs caching

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2818]
The function `is_single_user_site` ( https://github.com/Automattic/jetpack/blob/a0bc1719b2c847c8e56dec22321f9314367ed865/class.jetpack.php#L1198 ) could use caching. 

We can borrow the technique Core uses for `is_multi_author` ( https://github.com/WordPress/WordPress/blob/d6a1a9655c346973783f1be7d7fdc6377ffce92b/wp-includes/author-template.php#L460-L486 ).

Related: https://github.com/Automattic/jetpack/blob/a0bc1719b2c847c8e56dec22321f9314367ed865/class.jetpack.php#L1357

cc: @enejb h/t @ocean90 for the suggestion.

**Comment by enejb** [comment]
Thanks for the suggestions.
@ocean90 and @kraftbj I am not sure but how does storing it a transient help improve much except in this case except when the data is stored in memory if the servers supports that. 

Transients always do 2 queries, one the expiry time and the other for the data. Currently we only do one which I am think is pretty fast (but I haven't bench marked it). It should return the first 2 results in the user table if they exist.

**Comment by ocean90** [comment]
Some background: https://core.trac.wordpress.org/ticket/22212#comment:51

Like `is_multi_author()` `is_single_user_site()` should use a transient *without* a timeout. Without an external object cache it will be an option with autoload = `yes` and therefore loaded by `wp_load_alloptions()`, so no extra query.

**Comment by enejb** [comment]
Thanks for the info. Will investigate this further.

**Comment by enejb** [comment]
This has been fixed we now cache the output of that function for 12 hours in a transient. See https://github.com/Automattic/jetpack/blob/998329ba56b9bb8d55b91f7745fc6a12a4ef9290/class.jetpack.php#L1057
