### ISSUE TITLE
Enhancement: Add tracks for all boost interactions

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#28192]
### Impacted plugin

Boost

### What

Add tracks events for all clickable actions on Boost dashboard.

### How

Things like Refresh button for speed-score should dispatch tracks events to understand how the plugin is being used.

Discussion: p1672924356129429-slack-C016BBAFHHS

**Comment by thingalon** [comment]
This seems like a very broad ticket :) How will we know when we're done?

**Comment by haqadn** [comment]
I requested for a list. But, Ali U insisted that any clickable interaction should be tracked.
