### ISSUE TITLE
VideoPress: v6 is broken with core@14.9.0

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#28191]
* Download and active Gutenberg @14.9.0 (last one currently)

![Image](https://user-images.githubusercontent.com/77539/210796441-4b0fe44c-19b6-4dbe-98a0-cc7170a1d781.png)

* Go to block editor
* add a new VideoPress video block
* Try to upload a video 
* Confirm the app shows the following error:

![Image](https://user-images.githubusercontent.com/77539/210796572-8353664a-41e5-4777-b17f-868818dbf9df.png)

**Comment by dhasilva** [comment]
It seems that searching for anything when adding a block also causes a problem. Neither issue happens on Firefox, only on Brave (Chromium based).

https://user-images.githubusercontent.com/8486249/210808181-84cbf2d2-62f5-4b1e-b4d4-2642261b4f61.mp4
