### ISSUE TITLE
I want to change the color of the hyperlink and comment text inside the email that Jetpack sends to users

### ISSUE THREAD

**Issue by manaadiar** [Automattic/jetpack#28203]
Hi there.. I use Jetpack for my users to receive notifications.. I would like an option to change the color of the hyperlink and comment text inside the email that Jetpack sends to users..
<img width="567" alt="jetpack color change" src="https://user-images.githubusercontent.com/62034971/211003808-88b26953-758d-4c8d-ad09-df9f6c07343f.png">

**Comment by jeherve** [comment]
Thanks for the suggestion. This is currently tracked in #2437, so I'll close this issue.

**Comment by manaadiar** [comment]
Noted, but that number is from 2015.. Is Jetpack working on it or..?? Will it be allowed..?? 

 

Regards

Info Desk

**Comment by jeherve** [comment]
> Is Jetpack working on it or..?? Will it be allowed..??

We're not working on those emails at the moment, but when we next iterate on those emails, we'll definitely consider it!
