### ISSUE TITLE
Beta blocks: Not available when JETPACK_EXPERIMENTAL_BLOCKS is defined

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#28227]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Start with JN site
2. In `/wp-admin/options-general.php?page=companion_settings` enable `JETPACK_BETA_BLOCKS`
3. Go to a block editor and search for `beta` blocks. There should be few in the list
4. Go back to `/wp-admin/options-general.php?page=companion_settings` and enable `JETPACK_EXPERIMENTAL_BLOCKS`
5. In the block editor, search for beta blocks

### A clear and concise description of what you expected to happen.

I was expecting that both constants could coexist together

### What actually happened

`JETPACK_EXPERIMENTAL_BLOCKS` overrides block variation that was defined by `JETPACK_BETA_BLOCKS`

### Other information

The logic is defined here: https://github.com/Automattic/jetpack/blob/5463f2e0284ca8a634f75deee22db0c1bf1de984/projects/plugins/jetpack/class.jetpack-gutenberg.php#L866

It seems that this behavior is expected, but I feel it confusing, especially from the testing perspective.

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by jeherve** [comment]
> It seems that this behavior is expected

Yes, I would say it is the expected behavior right now, but we could inverse the order, so whenever you have the Beta flag set up, it takes over from any existing experimental flag you may have.

**Comment by jeherve** [comment]
Further discussion about this in p1673872153055239-slack-CDLH4C1UZ

Here are some takeaways:

> I guess I would've expected one constant, `JETPACK_BLOCKS_MODE` , with 'production', 'beta', or 'experimental' as the options. This way, you'd get some notice if it was redefined.
> 
> It's weird that there's some non-obvious hierarchy.

> we could start deprecating those 2 constants now (`JETPACK_BETA_BLOCKS` and `JETPACK_EXPERIMENTAL_BLOCKS`) and update the `blocks_variation` method to rely on a new, common constant

https://github.com/Automattic/jetpack/blob/10190af9e7de2a09e118f4d13c720d7d542b8294/projects/plugins/jetpack/class.jetpack-gutenberg.php#L868-L876

> we could name that constant like the existing filter, `JETPACK_BLOCKS_VARIATION`

**Comment by jeherve** [comment]
To close the loop on this: pdWQjU-cO-p2

1229-gh-wpcomsh remains, but I'll wait until the release is pushed to Woa to make the change.

**Comment by Investmentbusiness** [comment]
Buy Fake Money Online | fake and real passports | Buy Fake Canadian Notes Online | Buy Fake Swiss Francs|Buy Fake USD Bills|Counterfeit Dirhams Online|counterfeit money for sale in USA ..https://migrationdocs.com/


Email :  immigrantsdocs@yahoo.com
WhatsApp number: +1(437)7714426

 <a href="https://migrationdocs.com/">fake and real passports/a><a href="https://migrationdocs.com/">fake and real identity card/a><a href="https://migrationdocs.com/">fake and real drivers license/a><a href="https://migrationdocs.com/">fake and real birth certificate/a><a href="https://migrationdocs.com/">fake and real resident permit card/a><a href="https://migrationdocs.com/">fake and real divorce certificate>  <a href="https://migrationdocs.com/">fake and real death certificate/a><a href="https://migrationdocs.com/">fake and real marriage certificate/a>  
<a href="https://migrationdocs.com/">new identity package today/a><a href="https://migrationdocs.com/">buy us identity cards online now/a><a href="https://migrationdocs.com/">buy social security card online 2023/a><a href="https://migrationdocs.com/">buy birth certificate online now/a><a href="https://migrationdocs.com/">fake and real birth certificate/a><a href="https://migrationdocs.com/">buy a divorce certificate online//a>  <a href="https://migrationdocs.com/">fake and real death certificate///a>  <a href="https://migrationdocs.com/">canadian residence permit card now//a>  <a href="https://migrationdocs.com/">fake and real drivers license//a>  
<a href="https://migrationdocs.com/">buy a belgian passport online now//a><a href="https://migrationdocs.com/">buy germany passport online now//a><a href="https://migrationdocs.com/">buy swiss passport online//a><a href="https://migrationdocs.com/">buy a euroupean passport/a>
<a href="https://migrationdocs.com/">order fake marriage license/a>
<a href="https://migrationdocs.com/">portuguese id cards/a>
<a href="https://migrationdocs.com/">belgium permanent residence card/a>
<a href="https://migrationdocs.com/">where can i get a fake marriage license/a>
<a href="https://migrationdocs.com/">can i get a fake marriage certificate/a>
<a href="https://migrationdocs.com/">fake us identity card/a>
<a href="https://migrationdocs.com/">us citizen identity card/a>
<a href="https://migrationdocs.com/">buy european passport online/a>
<a href="https://migrationdocs.com/">documents fake birth certificates/a>
<a href="https://migrationdocs.com/">buy swiss id card online/a>
<a href="https://migrationdocs.com/">can you get a fake marriage certificate/a>
<a href="https://migrationdocs.com/">buy swiss passport online/a>
<a href="https://migrationdocs.com/">marriage license fake documents/a>
<a href="https://migrationdocs.com/">realistic fake marriage certificate free/a>
<a href="https://migrationdocs.com/">buy swiss passports/a>
<a href="https://migrationdocs.com/">buy fake marriage certificate online buy fake marriage certi/a>
<a href="https://migrationdocs.com/">german passports online/a>
<a href="https://migrationdocs.com/">fake marriage certificate/a>
<a href="https://migrationdocs.com/">fake marriage certificate with seal/a>
<a href="https://migrationdocs.com/">can you get a fake marriage license/a>
<a href="https://migrationdocs.com/">buy real switzerland passport online/a>
<a href="https://migrationdocs.com/">buy real european union passport online/a>
<a href="https://migrationdocs.com/">where to get fake marriage certificate/a>
<a href="https://migrationdocs.com/">novelty marriage certificate/a>
<a href="https://migrationdocs.com/">buy eu passport online/a>
<a href="https://migrationdocs.com/">buy switzerland passport online/a>
<a href="https://migrationdocs.com/">fake marriage papers/a>
<a href="https://migrationdocs.com/">can you fake a marriage certificate/a>
<a href="https://migrationdocs.com/">belgium permanent residence/a>
<a href="https://migrationdocs.com/">novelty marriage certificates/a>
<a href="https://migrationdocs.com/">fake divorce certificate,buy a new social security card/a>
<a href="https://migrationdocs.com/">buy a fake birth certificate online/a>
<a href="https://migrationdocs.com/">apply for divorce certificate online/a>
<a href="https://migrationdocs.com/">lost permanent resident card canada/a>
<a href="https://migrationdocs.com/">how to get a green card in usa/a>
<a href="https://migrationdocs.com/">tn visa to green card/a>

Email :  [immigrantsdocs@yahoo.c](mailto:immigrantsdocs@yahoo.co)om
WhatsApp number: +1(437)7714426
BUY COUNTERFEIT MONEY online, BUY COUNTERFEIT MONEY ,buy 100% undetected counterfeit money €$£,best counterfeit money for sale,fake money for sale california,how can i buy counterfeit money online?,buy fake pounds UK,buy fake dollars,high quality counterfeit money for sale,buy fake euro,buy australian dollars, buy canadian dollars, buy malaysian ringgit,buy fake dinars kuwait and bahrain, buy fake dirhams,where can i BUY COUNTERFEIT MONEY ?,buy top grade counterfeit money online,most legit counterfeit money supplier,buy fake money germany and france,buy fake swiss franc,buy prop money that looks real,fake british pounds for sale,is it illegal to buy counterfeit money?,buy fake money france,buy fake money singapore, buy fake money australia, buy fake money italy,buy fake money new york,buy counterfeit money that looks real,where to buy counterfeit money,how to buy counterfeit money ,can you BUY COUNTERFEIT MONEY ? Where can I buy counterfeit bills this 2019?,Fake Canadian dollars for sale,fake australian dollars for sale,Fake 20 dollar bills for sale,Buy Copy money that looks real amazon,Buy prop canadian and australian money for sale,Fake money for sale in Dubai and Saudi Arabia,buy fake euro that looks real,buy fake pounds that looks real, buy fake dinar that looks real,buy fake money Alaska,buy fake money Arkansas,buy fake money Arizona,buy fake money Alabama,buy fake money Texas,buy fake money Tennessee,buy fake money North carolina,buy fake money south carolina, buy fake money south dakota,buy fake money north dakota,buy fake money virginia,buy fake money west virginia, buy fake money Nevada,buy fake money new jersey,buy fake money indiana,buy fake money iowa,buy fake money kansas,buy fake money kentucky,buy fake money illinois,buy fake money montana,buy fake money new hampshire,buy fake money rhode island,buy fake money colorado,buy fake money connecticut,buy fake money maine, buy fake money louisiana, buy fake money Maryland,buy fake money nebraska,buy fake money florida,buy fake money district of columbia,buy fake money maryland,buy fake money georgia,buy fake money minnesota,buy fake money michigan,buy fake money ohio,buy fake money oregon,buy fake money oklahoma, buy fake money washington,buy fake money wisconsin,buy fake money idaho, buy fake money hawaii,buy fake money missouri,buy fake money mississippi,buy fake money utah,buy fake money luxembourg,buy fake money belgium,buy fake money austria,buy fake money russia,buy fake money spain,buy fake money ireland,buy fake money portugal,buy fake money greece,buy fake oman riyals,buy fake euro counterfeit money, buy fake kuwait dinar,buy fake money australia,fake euro austria,fake euro germany,fake pounds london, fake euro portugal and croatia,fake euro spain,fake money canada,fake canadian polymer bills for sale, fake polymer australian bills for sale, buy fake money in new zealand

High-Quality Undetectable Counterfeit US Dollar (USD)
High-Quality Undetectable Counterfeit Pound Sterling (GBP)
High-Quality Undetectable Counterfeit European Euro (EUR)
High-Quality Undetectable Counterfeit Canadian Dollar (CAD)
High-Quality Undetectable Counterfeit Australian Dollar (AUD)
High-Quality Undetectable Counterfeit South African Rand (ZAR)
High-Quality Undetectable Counterfeit Saudi Riyal (SAR)
Buy CAD notes | Buy Counterfeit Euro Notes | Buy Counterfeit Money | Buy Fake AED Bills | Buy
Fake CAD bills | Buy Fake Dollar | Buy Fake Euro| Buy Fake Money Online | Buy Fake MYR Notes |
Buy Fake Notes Online | Buy Fake Swiss Francs | Buy Fake USD Bills | Counterfeit Dirhams |
Counterfeit Dollar Currency | Counterfeit Euro For Sale | Counterfeit MYR Notes for sale | Fake
20 Euro Notes | Fake 100 CAD | Fake Dollar Bills For Sale | Fake Euro | Fake Malaysian Money For
Sale | Kaufen Falsch Francs |Malay Ringgit | Fake Order USD | Fake Money Order Forged Notes
Online | Buy Counterfeit Money Online | Buy Fake Dollar | Buy Fake EURO Online |
British Pound, Buy Australian Dollars, Canadian Dollars, Euros, Malaysian Ringgit, New Zealand Dollars, United States Dollars
Buy Counterfeit Money Online |Best Quality Counterfeit Currencies |BUY Counterfeit Notes Of All Currencies |Buy Counterfeit Bills Online
Buy fake USD online at best prices, Buy undetectable Dollars Banknotes, buy counterfeit money online
Buying from us is safe with a cheap price.
British Pound
Euros
Canadian Dollars
Malaysian Ringgit
Buy Australian Dollars
New Zealand Dollars
United States Dollars
Multipurpose
Quality Fake Currencies
Email :  [immigrantsdocs@yahoo.c](mailto:immigrantsdocs@yahoo.co)om
WhatsApp number: +1(437)7714426
#Alabama #Alaska #Arizona #Arkansas #California #Colorado #Connecticut #Delaware #Florida #Georgia #Hawaii #Idaho #Illinois #Indiana #Iowa #Kansas #Kentucky #Louisiana #Maine
#Maryland #Massachusetts #Michigan #Minnesota #Mississippi #Missouri #Montana #Nebraska #Nevada #NewHampshire #NewJersey
#NewMexico #NewYork
#North Carolina #North Dakota #Ohio
#Oklahoma #Oregon #Pennsylvania #RhodeIsland
#SouthCarolina #SouthDakota #Tennessee #Texas #Utah #Vermont #Virginia #Washington #WestVirginia #Wisconsin
#Bath #Birmingham #Bradford #Brighton and Hove #Bristol #Cambridge #Canterbury #Carlisle #Chelmsford #Chester #Chichester #Coventry #Derby #Durham #Ely #Exeter #Gloucester #Hereford #Kingston upon Hull #Lancaster #Leeds #Leicester #Lichfield #Lincoln #Liverpool #London #Manchester #Newcastle upon Tyne #Norwich #Nottingham #Oxford #Peterborough #Plymouth #Portsmouth #Preston #Ripon #Salford #Salisbury #Sheffield #Southampton #St Albans #Stoke-on-Trent #Sunderland #Truro #Wakefield #Wells #Westminster #Winchester #Wolverhampton #Worcester #York
