### ISSUE TITLE
[Boost] Improvements to messaging

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#28220]
P2 link: pbNhbs-4Nw-p2

@augurlu has recommended a range of improvements to the copy around Critical CSS, to better explain the differences between the paid and free versions, and to explain to users when to regenerate their CSS.

See the linked P2 post for details.

**Comment by thingalon** [comment]
Note: updated figmas here: pbNhbs-4Nw-p2#comment-12408

**Comment by haqadn** [comment]
Duplicate of Automattic/boost-cloud#216
