### ISSUE TITLE
Form block: Ordering (and display) of fields not always respected on submission. - Field Name Id Issue

### ISSUE THREAD

**Issue by coder-karen** [Automattic/jetpack#28231]
### Impacted plugin

Jetpack

### Issue

There are two issues here but both related to the display of form submissions.

1. In some cases, form fields are re-ordered after the form has been submitted (visible from the submission page, and the feedback export in two instances of testing).
2. In some cases, fields are removed completely after submission, tieing in with reordering of fields (on the submission page, on the Feedback page and in the exported CSV). 

For issue 1, here is an example form

<img width="700" alt="Screen Shot 2023-01-09 at 4 13 53 pm" src="https://user-images.githubusercontent.com/16754605/211354923-25d78dd4-ba4a-4769-995c-7866cf67092c.png">

And example CSV where the fields are in a different order:

<img width="1282" alt="Screen Shot 2023-01-09 at 4 14 44 pm" src="https://user-images.githubusercontent.com/16754605/211355092-9e6ac03c-e48a-44b1-a31e-63901d036b4d.png">

Both of these cases were reported in internal testing - p8oabR-11U-p2#comment-6960 -  the first case I was also able to reproduce. It's not entirely clear at this stage what causes this.

**Comment by donnchawp** [comment]
We figured out this only applies to the Salesforce template that was recently added. The IDs of the input fields were hardcoded to match what Salesforce needs in their API but that stopped the normal duplicating code working which would have changed the name of the ID of a duplicated field.
Having duplicated fields is what caused the issues seen here.

**Comment by digitalwaveride** [comment]
Will be addressed via https://github.com/Automattic/jetpack/pull/30475 and https://github.com/Automattic/jetpack/pull/30260

**Comment by digitalwaveride** [comment]
Issue is fixed via https://github.com/Automattic/jetpack/pull/30475 and https://github.com/Automattic/jetpack/pull/30260
