### ISSUE TITLE
Custom Background Images for WordPress.com "My Sites" page

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#2824]
So once jetpack is connected, sites display on the "My Sites" page on wordpress.com. Currently it pulls in the custom header for the site if it has one. I would love the option to provide a custom image for this background, as not all of my sites support the custom header feature.

![](https://www.evernote.com/shard/s1/sh/3d458083-e53a-4c5c-928d-f3459f42cc55/5eb9e5ed31226959/res/a13a5255-2ad9-422c-a8f7-a2cb1160482e/skitch.png?resizeSmall&width=832)

**Comment by jeherve** [comment]
Wouldn't it be easier to add custom header support to your theme?

```php
add_theme_support( 'custom-header' );
```

You don't have to add support to the frontend, though. You would then have the interface to upload a header in the admin, and it would be easier to upload and edit that header image, even if it's not displayed anywhere on your site.

**Comment by bhubbard** [comment]
I thought about doing that, but I'm a bit considered as it would confuse some of my clients.

**Comment by jeherve** [comment]
Jetpack grabs the Custom Header image data from the `header_image_data` theme mod, so you should be able to overwrite that value, even if Custom Header support isn't defined in your theme, with something like this:

```php
function jeherve_my_default_header_image() {
	$header_img = esc_url( 'https://jeherve.com/wp-content/uploads/2015/10/7.jpg' );

	$header_img_data = array(
		'attachment_id' => '1681',
		'url'           => $header_img,
		'thumbnail_url' => $header_img,
		'height'        => '198',
		'width'         => '940'
	);
	set_theme_mod( 'header_image_data', $header_img_data );
}
add_action( 'init', 'jeherve_my_default_header_image' );
```

I just tested this on a site using a theme with no custom header image support, and it worked.
