### ISSUE TITLE
[Boost] Display issue in Critical CSS dashboard

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#28243]
As noted by @ajaykj, new users sometimes see `%d files generated` under the Optimize CSS Loading heading when first installed & enabled:

![image](https://user-images.githubusercontent.com/1369626/211444218-9d127a17-7d9a-4d38-b06c-b809e09a0489.png)

At first blush, it looks like an `undefined` or a `null` is getting in there somehow.

**Comment by haqadn** [comment]
The implementation related to the data path has been changed, and it doesn't appear the bug would still exist.
