### ISSUE TITLE
[Boost] Image Guide compatibility with Tiled Gallery

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#28246]
As pointed out by @jeherve, [the Image Guide is not showing up properly when used with Jetpack's Tiled Image Gallery](https://href.li/?https://wp.me/pc9hqz-1sC#comment-1081).

Popup information frames are appearing inside individual panes, cutting off most of their content.

We need to ensure that this feature works with other Jetpack features.

**Comment by thingalon** [comment]
The only reliable way I can see to fix this, is to move the information popup to a layer at the document level with a high z-index, and position it absolutely using JavaScript to match the bubble's position.

Other ideas welcome, but I don't see another way for this.

**Comment by pyronaur** [comment]
Fixed in https://github.com/Automattic/jetpack/pull/28026
