### ISSUE TITLE
VideoPress: prevent flash of initialState data when accessing the videos with page or search query parameters

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#28259]
This is a followup from #28064.

When the user lands on the video library with some URL value set for `page` (pagination) or `q` (search), it's possible to see a flash of the original content of the first page (the `initialState` value set by the backend).

We need to prevent this flash.

Some alternatives:

- set the backend `initialState` considering the filters and the pagination
- when there is some filter or pagination, do not set the `initialState` on the backend
- when there is some filter or pagination, immediatelly invalidate the initial state on the frontend
- other

**Comment by dhasilva** [comment]
> - set the backend initialState considering the filters and the pagination
> - when there is some filter or pagination, do not set the initialState on the backend

Not possible, as the hash content is not sent to the server. Here we can see that we have the `page` query argument set to `jetpack-videopress` and the `page` fragment set to `3`. The fragment is ignored in the HTTP request, so the value `3` is not available in the backend:

![2023-01-20_16-52-28](https://user-images.githubusercontent.com/8486249/213793737-c064a62f-8f0d-4f8b-a7a0-8a8049f047c9.png)

> - when there is some filter or pagination, immediatelly invalidate the initial state on the frontend

Seems to be the only solution, as only the frontend knows if there is any fragment.
