### ISSUE TITLE
[Boost] Broken caption with Image Guide enabled on Twenty Twenty-Three theme

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#28256]
### Impacted plugin

Boost

### Steps to Reproduce

1. Load up a website with the Twenty Twenty-Three theme
2. Add an image with a caption to a page
3. Check the image on the page to make sure everything is as expected
4. Enable Image Guide and check the page again - caption should be above the image

### A clear and concise description of what you expected to happen.

Enabling Image Guide shouldn't move the caption above the image.

Image of what it should look like:
![Screenshot 2023-01-10 at 14 50 07](https://user-images.githubusercontent.com/11799079/211557007-145c7650-5810-4e0a-a1f4-39303afb2d2d.png)

### What actually happened

Enabling Image Guide affects images with captions, by moving the caption above the image.

Image of what it looks like:
![Screenshot 2023-01-10 at 14 50 37](https://user-images.githubusercontent.com/11799079/211557082-8aec6009-f1d2-47d8-8b71-c87e06d7de65.png)

### Browser

Google Chrome/Chromium

### Platform (Simple, Atomic, or both?)

Simple, Atomic, Self-hosted

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

None

**Comment by pyronaur** [comment]
Fixed in https://github.com/Automattic/jetpack/pull/28026
