### ISSUE TITLE
My Jetpack: VaultPress Backup shown as inactive when site is on a JPVPBU plan

### ISSUE THREAD

**Issue by lakellie** [Automattic/jetpack#28264]
### Impacted plugin

Jetpack, Backup

### Steps to Reproduce

1. Activate a Jetpack VaultPress Backup plan (both 10GB and 1TB are impacted by the bug)
2. Navigate to My Jetpack

### A clear and concise description of what you expected to happen.

Under "Manage your Jetpack Products",  the "VaultPress Backup" panel should show the feature is active

### What actually happened

The "VaultPress Backup" panel does not show the feature is active and prompts the user to purchase a plan.

![image](https://user-images.githubusercontent.com/17372274/211616761-d8891338-5b65-496e-bea3-3bd76d4b1757.png)

Consistent

### Severity

Some (< 50%)

### Available workarounds?

None

**Comment by lakellie** [comment]
Related Slack discussion: p1673370499867909/1673370090.038319-slack-C02TQF5VAJD

Looks like the card is checking for the presence of the backup standalone plugin, rather than checking for the presence of an upgrade. This is due to the discussion in p1HpG7-jwG-p2#comment-59026

Clicking "Add VaultPress Backup" brings you to this landing page:

![image](https://user-images.githubusercontent.com/17372274/211625081-ffb505e2-960d-4d47-b7a0-94a377872f78.png)

This is a confusing flow for users who have purchased an upgrade, since this looks like an upgrade page, and the word "add" makes it sound like they're purchasing something.

Sounds like we can't change it to "activate" since that's already used to mean something else in a different context on My Jetpack, but I think some design/flow adjustments are needed here to make it clear this flow is installing the standalone plugin and not related to upgrading or purchasing anything.

**Comment by renatoagds** [comment]
This one got fixed with the new updates and project: pedxs5-ck-p2
