### ISSUE TITLE
[Jetpack AI] Fix styling

### ISSUE THREAD

**Issue by artpi** [Automattic/jetpack#28323]
The styling of the AI Image in the editor needs some work:

Per @poligilad-auto 

> 1. The layout of the text field seems a bit off to me. I would expect the text field to go all the way till the edge of the block.

![image](https://user-images.githubusercontent.com/3775068/212101654-31efc496-b1b9-411b-a763-6b69e42820cf.png)

> 2. After submitting the text, while hovering over the 4 options, the content of the block starts to “jitter”. Think this might be just a problem with the first image in the row.

![image](https://user-images.githubusercontent.com/3775068/212101674-56441cdf-84d2-4363-ad55-4de786ddf6a2.png)

Find any other styling issues you could find.

There are more styling issues with flexbox:

![image](https://user-images.githubusercontent.com/3775068/212161326-17de2da6-5686-4726-8e80-5665f902e901.png)

Per @frosty :

> AI Image: It would be nice to be able to preview images in a larger size before choosing which to commit to. I clicked on one of the 4 expecting to see it bigger, but it instantly turns into an image block and the other options disappeared. It’s hard to make a decision about which image to use when they’re all tiny.

So let's make this hover much, much bigger as we have the image data in memory already.

**Comment by millerf** [comment]
Fix height textarea based on @jeherve [comment](https://github.com/Automattic/jetpack/pull/28339#issuecomment-1383910122)
