### ISSUE TITLE
UI glitch on My Plans

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#28335]
### Impacted plugin

Jetpack

### Steps to Reproduce

- Add some jetpack products/plans to your site
- Go to Jetpack Dashboard > My Plans on a mobile device
- Notice the separator lines between products

### A clear and concise description of what you expected to happen.

The lines should be between products

### What actually happened

The lines are between a product and product meta. Meta of one product is mixing up with the next product.

### Browser

Google Chrome/Chromium

### Other information

![image](https://user-images.githubusercontent.com/3737780/212271959-c8b5e51b-f305-4fb7-9ddb-d800fb0d8793.png)

### Platform (Simple, Atomic, or both?)

Atomic, Self-hosted

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by sdixon194** [comment]
Visual design of the page has changed significantly and I don't see the same issue anymore

![Screenshot 2023-07-25 at 4 41 02 PM](https://github.com/Automattic/jetpack/assets/33553323/6715b93b-52ca-4a2c-a8c7-be73e32bcf48)
