### ISSUE TITLE
[Boost] Dynamically loaded images don't have an image guide

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#28344]
### Impacted plugin

Boost

### Steps to Reproduce

1. Install latest trunk version of Boost;
2. Enable Image Guide feature;
3. Install a plugin that allows an infinite load for images (for example Visual Portfolio, Masonry block);
5. Open the page and scroll down so more images get loaded;
6. The new images should not have the image guide bubble.

### A clear and concise description of what you expected to happen.

Image Guide should work for dynamically loaded images as well.

### What actually happened

Image Guide does not work on dynamically loaded images.

First three images are loaded on page load, the rest are on scroll.
![image](https://user-images.githubusercontent.com/11799079/212345734-02cc30ff-3fea-4119-995c-57caa9d3fc99.png)

### Browser

Google Chrome/Chromium, Mozilla Firefox, Microsoft Edge, Apple Safari, iOS Safari, Android Chrome

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Currently, you can go around this by toggling the Image Guide from the admin bar on that page. Doing so will render the Image Guide for the dynamically loaded images.
![image](https://user-images.githubusercontent.com/11799079/212346085-081753b1-c837-4b6e-b847-0bd2ac505270.png)

**Comment by pyronaur** [comment]
I'll tackle this Monday alongside removing the always-on feature for now.

**Comment by pyronaur** [comment]
Ultimately, we might want to use a mutation observer (although we could just use a timer, I'm not too excited about that solution) to see when new images appear on the page and update the image guide accordingly.

But for the first version, I think we can release this as-is and observe how often are lazy images actually a problem for people using the feature.

**Comment by sdixon194** [comment]
Did some more testing and looks like this one has been fixed already. Going to close the issue out, feel free to re-open if you're using it for some other kind of tracking.
