### ISSUE TITLE
Bug in .po translation file of JetPack Boost

### ISSUE THREAD

**Issue by Ruba5913** [Automattic/jetpack#28352]
### Impacted plugin

Jetpack, Boost

### Steps to Reproduce

No steps. 
Occurred at translating page of the official wordpress.org site. 

### A clear and concise description of what you expected to happen.

<retry>Try to generate Critical CSS again<retry> should be changed in <retry>Try to generate Critical CSS again</retry>

### What actually happened

Hello,

I found a bug in the translation file

It refers to app/assets/dist/jetpack-boost.js:9

<retry>Try to generate Critical CSS again<retry> in case the error was intermittent

### Browser

Google Chrome/Chromium, Microsoft Edge

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by kraftbj** [comment]
I don't fully track what is being reported, but I noticed in the originating file ( https://github.com/Automattic/jetpack/blob/587b990d55222eabc140c6eb8f27c93ff36157fb/projects/plugins/boost/app/assets/src/js/utils/describe-critical-css-recommendations.ts ) there is an opening `<retry>` without a `</retry>` (two opening ones).
