### ISSUE TITLE
[Jetpack AI] Work better with lists and fix styling

### ISSUE THREAD

**Issue by artpi** [Automattic/jetpack#28384]
Jetpack AI Paragraph does not keep formatting passed in from OpenAI. Even then line breaks scramble upon saving.

The scope of this task is to:
- Transform the plaintext output from OpenAI to add proper paragraphs, lists and (maybe) code blocks
- Insert those as nested blocks or rawhtml inside our block
- Make sure the transformer makes sense. Using the current transformer to paragraph block nests code inside which makes no sense

### Markdown

I tried the following change, and it worked to an extent. The code was transformed, but I didn't know how to write the save function to save this markdown properly.

```
import MarkdownIt from 'markdown-it';
```

```
		.then( res => {
			setLoadingCompletion( false );
			const content = res.prompts[ 0 ].text;
			// This is to animate text input. I think this will give an idea of a "better" AI.
			// At this point this is an established pattern.
			const tokens = content.split( ' ' );
			const md = new MarkdownIt();

			console.log( md.render( content ) );
			for ( let i = 0; i < tokens.length; i++ ) {
				const output = tokens.slice( 0, i ).join( ' ' ).trim();
				setTimeout( () => setAttributes( { content: md.render( output ) } ), 50 * i );
			}
			setTimeout( () => setAttributes( { content: md.render( content.trim() ) } ), 50 * tokens.length );
		} )
```

**Comment by romarioraffington** [comment]
Hi Artur,

I would like some clarification before going ahead.

<img width="825" alt="Screenshot 2023-01-17 at 16 23 16" src="https://user-images.githubusercontent.com/7076981/213015372-e7abf17c-77ce-42b5-ae48-25360abf78eb.png">

> Transform the plaintext output from OpenAI to add proper paragraphs, lists and (maybe) code blocks

> Insert those as nested blocks or rawhtml inside our block

Should I convert the response to another Gutenberg block ( e.g, paragraph, lists etc ) then insert that block as a child of the AI block?

> Make sure the transformer makes sense. Using the current transformer to paragraph block nests code inside which makes no sense

Can you clarify this statement please

**Comment by artpi** [comment]
> Should I convert the response to another Gutenberg block ( e.g, paragraph, lists etc ) then insert that block as a child of the AI block?

What we ultimately need is for the user to eventually have the output in the form of editable **set** of blocks, each appropriate to the content (paragraph, list, code if this comes up)

We can achieve that outcome in 2 ways as far as I can imagine, but feel free to explore more:

1. We can have the block contain inner blocks that would be populated from GPT output and also be editable. I think I prefer this approach
2. We can have the `content` of the block to be HTML (it is currently plaintext) that produces relevant blocks when **transformed** into other blocks. I think the only reasonable transform target would be the Group block, but maybe we can transform just to a whole set of editable regular blocks? The current transform target is core/paragraph which cannot contain lists.

![Zrzut ekranu 2023-01-18 o 11 50 50](https://user-images.githubusercontent.com/3775068/213152742-df9c2b76-a15f-463c-ae4d-437c36a0e439.png)

**Comment by artpi** [comment]
If we choose to go the Inner blocks route, the block will be editable without triggering the transform.
@divydovy  has pointed out to me that this is not obvious

**Comment by artpi** [comment]
@mtias says it's better for the block to be simple paragraph and we are going to ship it with changes from https://github.com/Automattic/jetpack/pull/28483 that introduce <br/> as the only formatting and transform to make it editable.

For now we are going to keep it without innerblocks, but we would still like to see how it behaves if we had inner blocks.
Depending on how much work it is, we may want to have this PR for testing.

Let's give it 2 more days

**Comment by n3f** [comment]
Current state: p81Rsd-1ba-p2

**Comment by artpi** [comment]
This is not a concern anymore with Jetpack taking over
