### ISSUE TITLE
VideoPress: Private video placeholder is shown in the block editor

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#28399]
Steps to reproduce:
1 - Install VideoPress
2 - Go to the block editor and add a VideoPress block
3 - Upload a video
4 - Change the video privacy to `private`
5 - Check that a message saying `The video is private` is shown
6 - Change any video setting
7 - Check that the message is not shown anymore

~This seems to only happen in Firefox~

**Comment by retrofox** [comment]
I think it works expected. Let's follow an open eye here.

A little bit of context: 
The issue happens at the video player level. It wasn't attaching the token for private videos., while the block did do that. That explains why the block got the data, but the player continued showing the black screen (private video).

Let's try to collect information about the issue when it happens, paying attention to thee requests/responses.

**Comment by lhkowalski** [comment]
I am doing some tests on this, trying somethings locally, to explore some of the items discussed in this slack thread: p1674495709234919-slack-C03TA48NSUX

**Comment by retrofox** [comment]
Following tasks

- [x] https://github.com/Automattic/jetpack/pull/28660
- [x] https://github.com/Automattic/jetpack/pull/28663
- [x] https://github.com/Automattic/jetpack/pull/28664
- [x] https://github.com/Automattic/jetpack/pull/28659/
- [x] use the new token-bridge
- [ ] Find a way to flush the cache in the client (pe4Cmx-K6-p2#comment-350)

**Comment by retrofox** [comment]
Let's close it for now but keep an opened 👁 on it
