### ISSUE TITLE
Release script: check for trunk/ dir in tag

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#28414]
This is a follow-up of #28400.

In some scenarios, we end up tagging a release with a copy of `trunk/` inside the tag. It would be nice if this could be avoided.

************

We also discussed this issue here: p1673891999603519-slack-C01U2KGS2PQ

**Comment by anomiex** [comment]
This is an unfortunate failure mode for the recommended command to create tags in SVN. Unfortunately the recommended way to prevent this is to use a precommit hook, which as far as I can tell we can't set up on the wordpress.org SVN. Someone could create a trac ticket with them to see if they'd be willing to add it.

What we can do is have our manual script warn if someone is using it on a plugin that has auto-publish configured. We can also add a check for whether the tag already exists in SVN, but there would still be the possibility for a race.
