### ISSUE TITLE
Enhancement: Fire `wp_cache_cleared` if “Clear all cache files” is activated

### ISSUE THREAD

**Issue by hirasso** [Automattic/jetpack#28422]
### Impacted plugin

Super Cache

### What

Intuitively, the action `wp_cache_cleared` should be fired if the plugin option “Clear all cache files when a post or page is published or updated.” is selected.

**Comment by anomiex** [comment]
Pinging @Automattic/heart-of-gold for triage

**Comment by thingalon** [comment]
Thanks for the suggestion @hirasso :) You're becoming a regular round these parts.

I've created https://github.com/Automattic/jetpack/pull/28481 to address the issue.

**Comment by hirasso** [comment]
Thanks @thingalon !

**Comment by thingalon** [comment]
@hirasso - this has also been released with Super Cache 1.9.3 :)
