### ISSUE TITLE
[Jetpack AI] Store post ids

### ISSUE THREAD

**Issue by artpi** [Automattic/jetpack#28444]
We need to store Post IDs of posts where jetpack_ai has been used, if ever we want to mark them on the front-end.

1. Let's add post_id to the OpenAI endpoints and pass them to backend, as a non-required argument
2. Let's pass them in the `OpenAI` constructor second argument `new OpenAI( 'openai', [ 'post_id' => 1234 ] )`
3. On the site itself, let's update the post meta as `jetpack_ai_count`. For the sake of simplicity, let's only increment this for now

**Comment by jeherve** [comment]
> posts where jetpack_ai has been used

Out of curiosity, how would you define "been used"? I assume a lot of folks may use the block, get some content back, but not use it (either because they're not happy with it, or because it just gives them an idea and they actually write the content themselves). In such scenarios, would we mark that post as "using AI"?

**Comment by artpi** [comment]
>  I assume a lot of folks may use the block, get some content back, but not use it (either because they're not happy with it, or because it just gives them an idea and they actually write the content themselves). In such scenarios, would we mark that post as "using AI"?

These are very good points and I am currently writing post about this.
As a definite answer is almost impossible due to the fact people can edit the content, we need to at least store the information it has **not** been triggered on this site. What I want is the ability to ensure that AI has not touched a site, similar to Kosher rules.

Clearly the standards work is not keeping up, but I am leaning towards aggressive labeling "This uses AI" because:

- A subset of people will care about this strongly
- We want to avoid contributing to an internet full of AI-generated content of mediocre quality.

**Comment by artpi** [comment]
Here is me going on at length about this: p4vt7e-bh-p2
