### ISSUE TITLE
Subscribe Widget Structure

### ISSUE THREAD

**Issue by craigtommola** [Automattic/jetpack#2847]
The Jetpack subscribe widget uses a paragraph for the input and a separate paragraph for the submit button. The widget should mimic the structure of the Wordpress Search widget (div) so the field and button can be placed side by side and still be responsive. Currently battling to get the submit button position to be responsive in relation to the scaling .secondary and text field width in a twenty fifteen child theme.

Seems there should be more enforced consistency in structure between various Automattic projects, for optimal compatibility.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
