### ISSUE TITLE
JP Forms: Style Variations - glitch when loading the form

### ISSUE THREAD

**Issue by jcheringer** [Automattic/jetpack#28472]
As mentioned here: https://github.com/Automattic/jetpack/pull/28212#issuecomment-1380189289

In the published view, when loading a styling varation of the form block, I see the labels at first without padding, then they jump to the expected place. Happens for me on every page refresh.

https://user-images.githubusercontent.com/5120357/212049274-0a9ead4f-a7bd-4c94-bd79-c320de0262d9.mov

Any chance that we hide the poll, show some "placeholder", till the form is fully loaded?

**Comment by digitalwaveride** [comment]
Fixed with https://github.com/Automattic/jetpack/pull/28473
