### ISSUE TITLE
[Jetpack AI] Why does 3rd paragraph block not get generated?

### ISSUE THREAD

**Issue by artpi** [Automattic/jetpack#28471]
- Fill the title / categories
- Insert the block
- see it write content
- Wait 1 minute
- Insert another one, see it continue
- Wait 1 more minute
- Insert another one, see something going wrong.

We need to debug why the 3rd and subsequent paragraph blocks fail

**Comment by millerf** [comment]
This one is fixed by #28483

**Comment by millerf** [comment]
See this post: https://testjetpackpaidnewsletters.wordpress.com/wp-admin/post.php?post=292&action=edit

<img width="1319" alt="Screenshot 2023-01-23 at 14 34 43" src="https://user-images.githubusercontent.com/790558/214052807-6c38b36f-be82-43a9-bdce-ef3e6b5753f4.png">
