### ISSUE TITLE
Inconsistent Emoticon Sizing in Post Emails

### ISSUE THREAD

**Issue by philiparthurmoore** [Automattic/jetpack#2849]
I'm really not sure if this is Jetpack-related or WordPress.com-related, because I've seen the issue in both the [Reader](https://twitter.com/philip_arthur/status/646185666586394624) and emails, but some emoticons are super-large in email-delivered posts:

<img width="631" alt="2015-10-16_04-41-29" src="https://cloud.githubusercontent.com/assets/28684/10528478/af315b3a-73c0-11e5-99c0-9bd2039a3e26.png">

Feel free to close if this is the wrong location for the bug report. Cheers.

**Comment by jeherve** [comment]
I believe this has now been fixed. Closing.
