### ISSUE TITLE
Social Icons Widget: Mastodon icon not showing up

### ISSUE THREAD

**Issue by candersonjames** [Automattic/jetpack#28513]
### Impacted plugin

Jetpack, Social

### Steps to Reproduce

1. Add the Social Icons (Jetpack) widget.
2. Insert a Mastodon profile URL that isn't on an expected server. I used https://theatl.social/@andyjames
3. Link gets added with a generic link icon, not the Mastodon icon.

### A clear and concise description of what you expected to happen.

Icon should be the Mastodon icon.

### What actually happened

<img width="154" alt="Screenshot 2023-01-20 at 9 50 52 PM" src="https://user-images.githubusercontent.com/112189513/213840606-c3fa1c76-9eac-4268-81a1-614b98ebe2af.png">

### Browser

Apple Safari

### Platform (Simple, Atomic, or both?)

Self-hosted

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by jeherve** [comment]
That's indeed the expected behavior, since as you mentioned, you're linking to a specific instance. To support that instance, I would recommend adding the following code snippet to your site, using [a functionality plugin](https://jetpack.com/support/adding-code-snippets/):

```php
// Add a new Mastodon instance to the list.
add_filter(
    'jetpack_mastodon_instance_list',
    function ( $mastodon_instance_list ) {
        $mastodon_instance_list[] = 'theatl.social';
        return $mastodon_instance_list;
    }
);
```
