### ISSUE TITLE
Sharing: Plus sign appears in Twitter share text

### ISSUE THREAD

**Issue by ChrisBegley** [Automattic/jetpack#2853]
When you click a Twitter share button, it puts a "+" inbetween each word in the URL:
https://twitter.com/intent/tweet?via=photomatt&text=Working+%26+Exercising&url=http%3A%2F%2Fma.tt%2F2015%2F10%2Fworking-exercising%2F

This causes the "+" sign to appear in the share text in iOS 9:
![Image](http://i.imgur.com/7sO2Xty.png)

**Comment by jeherve** [comment]
The issue seems limited to iOS. I couldn't reproduce on Android or on my desktop, regardless of the browser. It seems that iOS doesn't handle `+` in URLs at the moment. Encoding `+` wouldn't help, as it would break all post titles including `+`. 

We should maybe encode spaces using `%20` instead of `+`.

**Comment by sboisvert** [comment]
This is solved by changing urlencode_deep to rawurlencode_deep in sharing-sources.php line 486. See r12345-wpcom. It might be a good idea to look at the instances of urlencode_deep and check if they would be best with rawurlencode_deep. :)

**Comment by jeherve** [comment]
> This is solved by changing urlencode_deep to rawurlencode_deep in sharing-sources.php line 486. See r126103-wpcom. 

Just pushed #2908 to apply that patch to Jetpack as well, thank you!

> It might be a good idea to look at the instances of urlencode_deep and check if they would be best with rawurlencode_deep. :)

I checked all other instances of `urlencode_deep`, and none of them include values with spaces, so we should be good to go.
