### ISSUE TITLE
Jetpack Stats: Views and visitors reported using UTC rather than local site time

### ISSUE THREAD

**Issue by thekingsprojects** [Automattic/jetpack#28557]
### Impacted plugin

Jetpack

### Quick summary

When an Atomic user's site timezone is set to something other than UTC (for example, Los Angeles), the Views chart section of the stats will show the stats' dates as though they're in UTC rather than the site timezone.

### Steps to reproduce

1. On a WordPress.com Atomic site, go to Settings > General.
2. Set the site's "Site timezone" setting to a non-UTC timezone, e.g. Los Angeles.
3. Go to the site's frontend and view a few pages, so Stats can record your views, then wait a few minutes for Stats to update.
4. Go back to the main stats page and check the graph of views and visitors by day to see which date has your views listed.

### A clear and concise description of what you expected to happen.

The views should be added to the chart as part of the same day, and at the same time, as the site's timezone is set to. E.g., if it is 8pm January 24 by the site's timezone, the views should appear on the graph for January 24th.

### What actually happened

The views appear based on UTC time and may appear with the wrong date as a result. E.g., if it is 8pm January 24 by the site's timezone, the views appear on January *25th* (as it is 1am the next day UTC time).

Screenshot of an affected user's stats:

<img width="1080" alt="Markup 2023-01-24 at 20 01 26" src="https://user-images.githubusercontent.com/82622339/214461490-7a2db9d0-0d00-468d-a2e1-68e54537af08.png">

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Ticket with affected user report: 5892100-zen

I tested on a self-hosted site that was set to UTC-5, and didn't see any discrepancy in when the views appeared on the graph (views made on January 24th show up on the graph as January 24th).

**Comment by jeherve** [comment]
I believe this issue is similar to https://github.com/Automattic/wp-calypso/issues/16186

Since the Stats interface is developed in Calypso, I'll close this issue in favor of the other one.

Also somewhat related: https://github.com/Automattic/wp-calypso/issues/47000
