### ISSUE TITLE
[Boost] JavaScript and CSS concatenation and minification

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#28559]
Add a new module to Jetpack Boost: Minify and concatenate JavaScript and CSS.

You can pull code liberally from https://github.com/automattic/page-optimize - our own minification and concatenation plugin for WordPress.

Be careful that it works well with our Defer JS and Critical CSS features. The former is likely not to be an issue, but critical CSS likes to change the `<link>` tags for CSS to defer its loading - make sure this new module is compatible with that.

**Comment by dilirity** [comment]
This has been done here - https://github.com/Automattic/jetpack/pull/28686.

**Comment by dilirity** [comment]
This has been done here - https://github.com/Automattic/jetpack/pull/28686.
