### ISSUE TITLE
Ai Assistant: Move prompt engineering to the backend

### ISSUE THREAD

**Issue by artpi** [Automattic/jetpack#28569]
Currently, the AI Paragraph block is putting together the prompt based on title, content and categories on the frontend, in JavaScript.

I think there is value in sending payload with:
- post_id
- title
- content
- category ids (no need to fetch names, they already are on the backend)

and have the endpoint (on WPCOM end) put together the prompt.

That way, we could:
- Experiment with different prompt variations without having to release jetpack
- experiment with different models (babbage / ada)

I think this can be achieved by:
1. Keeping everything exactly as it is, just add title, content and categories to the payload
2. Introduce a filter in the Jetpack_Ai_helper class that can override prompt based on the above
3. Hook into this filter on WPCOM to tweak the prompt if needed

**Comment by nunyvega** [comment]
This is currently being addressed by @lhkowalski

**Comment by lhkowalski** [comment]
This is done by now. I will close this issue.
