### ISSUE TITLE
Slideshow: loads the editor JS on every page view

### ISSUE THREAD

**Issue by sgomes** [Automattic/jetpack#28561]
### Impacted plugin

Jetpack

### Quick summary

The Slideshow block currently loads the editor JS on every page view. This is a huge amount of JS, which severely affects page performance. The issue appears to have started with #27936, because `view.js` now imports from `slideshow.js`, which imports from the editor.

This is a classic case of insufficient modularity; the function that `view.js` is importing from `slideshow.js` (`paginationCustomRender`) should be split into its own module, that doesn't depend on the editor.

### Steps to reproduce

1. Create a simple page with a slideshow
2. Load the page on a browser, with DevTools open
3. Observe that a large amount of JS gets loaded, including the editor and all of its dependencies (React, moment, etc.)

### A clear and concise description of what you expected to happen.

The editor and its dependencies should not be loaded on a regular page view.

### What actually happened

The editor and its dependencies were loaded on a regular page view.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by sgomes** [comment]
I'll be preparing a fix for this, but if anyone gets to it before I do, please go ahead!

**Comment by sgomes** [comment]
Fix at #28562.

**Comment by sgomes** [comment]
@jeherve: Hey! 👋

IIRC, you were looking into detecting and preventing similar issues in the past, albeit at the PHP level (e.g. depending on the editor by using the wrong WP hook). Do you think it's possible to extend any existing detection techniques to this sort of situation? Perhaps by tracking output JS file sizes?

**Comment by jeherve** [comment]
> IIRC, you were looking into detecting and preventing similar issues in the past, albeit at the PHP level (e.g. depending on the editor by using the wrong WP hook). Do you think it's possible to extend any existing detection techniques to this sort of situation? Perhaps by tracking output JS file sizes?

I haven't made much progress on this, but yeah, we should find a way to detect this, other than PR reviews. Maybe we could have a check that looks at all dependencies declared in `_inc/blocks/*/view.asset.php` files on production builds. If specific dependencies are added (typically `react`, but others too), we'd throw a warning. I'm not sure we'd want this check to be a blocker, because there are some situations where we'll want those dependencies in the frontend, but at least we could throw some kind of warning maybe.

@anomiex What do you think about the idea?

**Comment by anomiex** [comment]
The idea to check the `_inc/blocks/*/view.asset.php` files seems like a good one to me. But it will have to be required or people will likely not pay any attention to it, so instead we should have a whitelist of the files that are allowed to have those deps.

Since it sounds like this is just for Jetpack-the-plugin (and maybe a future "blocks" plugin), we can add the check to the `build-production-extensions` script easily enough.

**Comment by sgomes** [comment]
> because there are some situations where we'll want those dependencies in the frontend

I just found out today that there are a bunch of blocks implemented using React, such as the Story block, the Map block, the Podcast Player block, etc. This is very troubling, we're talking upwards of half a megabyte for a single block, potentially 😞

One of the guiding principles of the block editor is to separate editor code and frontend code, so that the latter can be much smaller, and core blocks try very hard to accomplish this. It seems to me that Jetpack blocks should too.

In any case, while there are blocks intentionally making use of React on the frontend, we can't make the proposed check a requirement 😞

**Comment by anomiex** [comment]
BTW, I don't think checking JS file sizes would help with this issue. `@wordpress/*` packages and `react` aren't included in the relevant bundles, they're loaded separately from WordPress core.

**Comment by sgomes** [comment]
> BTW, I don't think checking JS file sizes would help with this issue. `@wordpress/*` packages and `react` aren't included in the relevant bundles, they're loaded separately from WordPress core.

Good point, yes; we need to check externalised dependencies instead, as @jeherve proposed 👍 Sorry, it's been a while since I touched Jetpack code 🙂

**Comment by jeherve** [comment]
> One of the guiding principles of the block editor is to separate editor code and frontend code, so that the latter can be much smaller, and core blocks try very hard to accomplish this. It seems to me that Jetpack blocks should too.

That's fair, and I believe we've done so for most of our blocks. However, I believe that in some cases, we do need a more complex interface on the frontend as well. I believe that's the case for the blocks you mentioned, and I'd be okay with allow-listing them. I'm happy to be proven wrong though!

**Comment by sgomes** [comment]
> That's fair, and I believe we've done so for most of our blocks. However, I believe that in some cases, we do need a more complex interface on the frontend as well. I believe that's the case for the blocks you mentioned, and I'd be okay with allow-listing them. I'm happy to be proven wrong though!

It may still be worth investigating cutting down on the dependencies. Even just using React directly would be preferable to depending on `@wordpress/element` (which is not designed for frontend use and comes with many extra dependencies, like Lodash and a bunch of other `@wordpress` packages). Do you think that would be doable for these blocks?

**Comment by jeherve** [comment]
> Do you think that would be doable for these blocks?

It may be worth trying, for sure. I don't know offhand if that would be possible for all though.

**Comment by sgomes** [comment]
> > Do you think that would be doable for these blocks?
> 
> It may be worth trying, for sure. I don't know offhand if that would be possible for all though.

I'll be happy to look into it. Thank you for all the context, and for looking into the build-time detection possibility! 🙏

**Comment by anomiex** [comment]
> If specific dependencies are added (typically react, but others too), we'd throw a warning.

Do we have a list of which should be warned about?

**Comment by sgomes** [comment]
`@wordpress/element` might be one to look out for, given that it's not intended to be used on the frontend.

**Comment by jeherve** [comment]
Reopening since we still have to keep track of automating that check.
