### ISSUE TITLE
VideoPress: uploading track doesn't work on Atomic sites

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#28572]
* Go to the block editor
* Create/edit a video block
* Try to upload a track, or generate it automatically form the description

![Image](https://user-images.githubusercontent.com/77539/214635446-0ce6623a-eb05-4069-85b9-1041e17ba04e.png)

![Image](https://user-images.githubusercontent.com/77539/214635497-062eb9dd-9a15-493a-954c-b20f93722690.png)

**Comment by nunyvega** [comment]
Confirming this bug after some testing, I tried uploading different types of tracks, but they all fail in a similar manner:

The network tab shows the `no route found` error:
<img width="1396" alt="Screenshot 2023-01-25 at 18 39 42" src="https://user-images.githubusercontent.com/16329583/214640299-f156e991-e3cb-4c82-9244-b2603f1d55f5.png">

The block keeps showing the 'saving' state, as if it was still uploading it:

![uploading](https://user-images.githubusercontent.com/16329583/214641348-cd399db3-bac2-4f81-b886-d8e1beddfe24.gif)
