### ISSUE TITLE
[Jetpack AI] Pass backend error to the user

### ISSUE THREAD

**Issue by artpi** [Automattic/jetpack#28570]
We see a number of failure states but we are giving very generic feedback in the prompt.

We need to properly recognize errors in the `OpenAI` library on WPCOM and display those messages on the frontend.

The purpose of this Issue is to take the endpoint error message and display it on the frontend for both AI blocks instead of the generic error message.

**Comment by oskosk** [comment]
Closing as it appears to be done by https://github.com/Automattic/jetpack/pull/28617
