### ISSUE TITLE
[Jetpack AI] Allow textarea to grow with user content.

### ISSUE THREAD

**Issue by artpi** [Automattic/jetpack#28595]
Per @millerf 

A PR was done to work with textareacontrol. See p1673883035926339-slack-C45SNKV4Z for reference.
RichText did not work as expected and would center content.

**Comment by sdixon194** [comment]
@artpi just cleaning up stale issues and I'm not too sure what this one was referring to - is this issue still relevant or could be expanded on?

**Comment by millerf** [comment]
That can be closed. Thanks for the ping!
