### ISSUE TITLE
[Paid Newsletter] Connect visibility controls between stock WordPress and Newsletters

### ISSUE THREAD

**Issue by artpi** [Automattic/jetpack#28591]
WordPress allows for following visibility levels
- Public
- Private
- Password Protected

We are introducing new ones:
- All Subscribers
- Paid subscribers only

## Goal of this task

We need to somehow connect those visibility levels so users don't get themselves into a tough spot.
- When users select Private or Password protected in the stock selector, then:
    - Display a Notice in the Newsletter access selector that says "Posts with Private or Password Protected visibility cannot be assigned for Subscribers only"
    - Disable changing the newsletter visibility
- If post is already selected for subscribers and users are trying to switch it for private/pasword-protected in the Gutenberg we have do display some kind of notice as well

Long-term we want to combine the 2 selectors but this will require Gutenberg work.

CC @mtias

**Comment by pablohoneyhoney** [comment]
> Posts with Private or Password Protected visibility cannot be assigned **to** Subscribers only

**Comment by millerf** [comment]
I asked #io because UX is a complex field, and best to discuss before doing... 
Thread: p1676639281837629-slack-C02A41GCS
