### ISSUE TITLE
Block non-wpcom sites from accessing the Ai features from the WPCOM end

### ISSUE THREAD

**Issue by artpi** [Automattic/jetpack#28598]
Hook into `jetpack_ai_enabled` filter and disable it for Jetpack sites

We need to deploy a wpcom patch that would disable AI for JP sites for now. That filter would work this way:

1. Endpoint is called on the JP end, jetpack_ai_enabled is forced by the users to return true, proxies to WPCOM.
2. WPCOM code is loaded, jetpack_ai_enabled has a default value of true because of IS_WPCOM, but we hook into this to return false for JP sites
3. WPCOM_REST_API_V2_Endpoint_AI constructor returns before hooking into rest_api_init
4. WPCOM endpoint returns 404
5. User sees 404 in the editor instead of 403. Still acceptable

**Comment by artpi** [comment]
Prior work https://github.com/Automattic/jetpack/pull/28309

**Comment by romarioraffington** [comment]
Putting this back to prioritize https://github.com/Automattic/wp-calypso/issues/72778

**Comment by millerf** [comment]
D100599-code

**Comment by artpi** [comment]
This is shipped
