### ISSUE TITLE
Widget visibility by page include children doesn't include grandchildren

### ISSUE THREAD

**Issue by emaiero1** [Automattic/jetpack#28614]
### Impacted plugin

Jetpack

### Quick summary

When using the widget visibility controls, when you limit a widget to a specific page and check the "include children" checkbox, it only shows the widget on the referenced page and the page's direct children. Any pages nested deeper (grandchildren, great grandchildren) do not display the widget.

### Steps to reproduce

Create a pages in a structure similar to the following:

```
- Page [A]
  - Page [1]   
    - Page [i]
  - Page [2]
  - Page [3]
```

Applying visibility rules to a widget and selecting `Page [A]` and choosing "Include children" will result in the widget displaying on `Page [A]`, `Page [1]`, `Page [2]`, and `Page [3]` but not `Page [i]`

### A clear and concise description of what you expected to happen.

In the absence of an additional control explicitly specifying all dependent pages, the "include children" option would be expected to fully transverse all levels of child pages to the specified page and display appropriately.

### Impact

All

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by jeherve** [comment]
Thanks for the suggestion. This is already tracked in #2829, so I'll close this issue.
