### ISSUE TITLE
admin-bar-v2.js throws an error

### ISSUE THREAD

**Issue by ramvi** [Automattic/jetpack#2861]
The admin bar throws an error on WP Multi:
 https://app.getsentry.com/share/group/35353336322e3838393036353836/

**Comment by jeherve** [comment]
I can't seem to be able to reproduce the issue at the moment.

Could you tell me more about your setup, as well as where you can see the error? Does it appear regardless of the admin page you're on?

Could you also try disabling other plugins, and pausing CloudFlare, and let me know if the problem remains?

Thanks!

**Comment by kraftbj** [comment]
@ramvi I'm closing this issue since we haven't heard back. Please do let us know specific steps to reproduce if you're still having trouble and/or feel free to reach out to us via https://jetpack.me/contact-support/
