### ISSUE TITLE
Odyssey Stats:  Add a "New" pillbox next to the "Enable a new Jetpack Stats experience" toggle

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#28631]
![Image](https://user-images.githubusercontent.com/4044428/215220871-c0fc7fc3-bf26-421e-9f4f-db68b9a52a78.png)

**Comment by a8ck3n** [comment]
Just wanted to double-check on this but is the gap under the Odyssey Stats toggle intended? I've included a 20px margin there but to my untrained eye it feels a bit weird in the final layout.

<img width="960" alt="SCR-20230202-jeu" src="https://user-images.githubusercontent.com/40267301/216243982-4a9aafcd-296b-4e1a-89ff-864b8dedc592.png">

Also, for reference, these are the CSS attributes used to style the button:

```
.jp-stats-odyssey-badge {
	color: $white;
	background-color: $blue-medium;
	border-radius: 3px;
	font-size: 11px;
	line-height: 12px;
	margin-left: 9px;
	padding: 4px 8px;
}
```

Let me know if any tweaks are needed!

**Comment by jeffgolenski** [comment]
@a8ck3n Yeah that's totally fine Kevin, thank you. Want to make sure it's not lost in the sea of toggles!
