### ISSUE TITLE
VideoPress: value is not correctly propagated in the the v1.1/videos/<guid> response for Atomic sites

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#28636]
The value of the `private_enabled_for_site` field is not updated for Atomic sites. it affects the _Site privacy_ option of the Privacy selector of the video block visually.

<img src="https://user-images.githubusercontent.com/77539/215409283-e31da449-68be-485f-b293-0ca4713e7df7.png" width="400px" />

Related issues: https://github.com/Automattic/jetpack/issues/27737

**Comment by lhkowalski** [comment]
I can confirm that the set value is being set on the backend, so it's a matter of reading it or enabling it on the response. Digging into it now.

**Comment by lhkowalski** [comment]
My test suggests that the code that returns the flag on the endpoint is not working properly for atomic. There are some conditions there checking if the site is atomic, and that is what I am testing now: how this code behaves.

**Comment by lhkowalski** [comment]
I gathered some information, some points of attention and a potential solution for this on this p2: pe4Cmx-IJ-p2.

**Comment by lhkowalski** [comment]
Created a PR to use the site privacy as the default value for the `videopress_private_enabled_for_site` option on VideoPress plugin/package (#28792). Now the next step is to change the VideoPress backend inside WPCOM to treat Atomic sites as a Jetpack one, relying on the value set for `videopress_private_enabled_for_site` for the video privacy, as well as defaulting the value to the site privacy as we did on the plugin/package.

**Comment by lhkowalski** [comment]
I started to work on the WPCOM change today, already have some commits on my sandbox, but need to test it and also ask for help to make sure the point that I identified is the only point that needs to be changed.

**Comment by lhkowalski** [comment]
Tested the WPCOM change today and it worked the way I expected. I will prepare a patch for the change and then ask for a whole review on both changes.

**Comment by lhkowalski** [comment]
We changed how to approach the privacy on Atomic:

- if the site is private, the default privacy for videos will be private as well
- if the site is public, the default privacy can be switched between public or private

I already have the VideoPress backend change in place (D101818-code), and now I will work on #28792 to reflect this new decision.
