### ISSUE TITLE
`contact-form__style-probe` has `visibility: hidden` set but might also need `display: none` to avoid pushing content and creating hidden padding.

### ISSUE THREAD

**Issue by ai2n** [Automattic/jetpack#28635]
### Impacted plugin

Jetpack

### Quick summary

When using the Twenty Twenty-Two theme, if you add a Form block, it also loads `contact-form__style-probe` 
https://github.com/Automattic/jetpack/blob/3bbc3f1944a94da8cd3d937f1dc8efc77e119c18/projects/packages/forms/src/contact-form/js/form-styles.js

since it has `visibility: hidden`, but not `display: none`, in some block configurations, you can see noticeable empty space/padding.

To avoid this, it needs to also have `display: none`

I don't know if there are any unintended consequences to adding `display: none`

Here is the workaround CSS:
`.contact-form__style-probe {
    display: none;
}`

### Steps to reproduce

1) Add Form Block, save, and view permalink for page.
2) Observe `contact-form__style-probe` loading due to https://github.com/Automattic/jetpack/blob/3bbc3f1944a94da8cd3d937f1dc8efc77e119c18/projects/packages/forms/src/contact-form/js/form-styles.js
3) It will add width/height resulting in padding, if you add `display: none` the issue is resolved.

### A clear and concise description of what you expected to happen.

Adding a form block should not move adjacent elements in unexpected and non-obvious ways.

### What actually happened

Adding a form block moved adjacent elements in unexpected and non-obvious ways.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

All sites all browsers, simple and atomic. Impacts anyone using a Form block, hard to say which structure will be more likely to break in an obvious way where padding appears in the footer for example. Adding display: none would insure against all though, assuming it's ok to add.

**Comment by jeherve** [comment]
cc @jcheringer, who recently worked on some of those styles, and may be able to look into this. 

Thank you!

**Comment by jcheringer** [comment]
Thanks, @jeherve!
I can fix this one.

**Comment by syhussaini** [comment]
I have a ticket with a similar issue where the user is using the **Pendant** theme.

5965972-zen

**Comment by digitalwaveride** [comment]
Can be closed, as this gets fixed via  https://github.com/Automattic/jetpack/pull/29178, as mentioned [here](https://github.com/Automattic/jetpack/pull/29132#issuecomment-1453956021).
