### ISSUE TITLE
Question: Should the slideshow swiper-resize function use "snapping" behavior to avoid "jumping photos"?

### ISSUE THREAD

**Issue by twoquarterrican** [Automattic/jetpack#28634]
### Impacted plugin

Jetpack

### Quick summary

A slideshow using jetpack slideshow module is sometimes "jumpy".
I can reproduce the issue when my window.innerHeight is 859 and my window.innerWidth is 1500.

It can be reproduced at some other ratios, but not reliably.

I was wondering if the computation in swiper-callbacks.js (link below) could be made more robust to input changes. My thought is that there are other pieces of javascript adjusting layout on the page. It looks like these adjustments get into a cycle where they constantly jump. For example, when debugging, I found img.clientWidth sometimes 760, which made the buttonTop 253px. This in turn (trying to track down how) somehow made the img.clientWidth come in as 758 on the next invocation. This led to buttonTop being 252px. This made the next invocation have img.clientWidth 760 and the loop started over again.

I was thinking of having some "snapping" behavior. That is, make it so that you get the same results for a wider array of inputs. But as I think about it, I am not even sure that would work. 

This is not necessarily an issue with the swiper-callback.js itself. It seems like an interaction issue between this javascript and the other javascript running on the page. It would be nice if there were a way to make this swiper-callback.js more robust to these kinds of layout adjustment loops. But I don't know how to do this.

https://github.com/Automattic/jetpack/blob/ac0778b124e5fb63c984cd3d5da280aa5abea356/projects/plugins/jetpack/extensions/blocks/slideshow/swiper-callbacks.js#L47
 

In the recording, you can see the height of an image jumping between 506px and 507px.

[jumpy-slideshow.zip](https://github.com/Automattic/jetpack/files/10531322/jumpy-slideshow.zip)

### Steps to reproduce

1. Go to https://marythomasphotography.com
2. Use a viewport 1500px wide, 859 tall
3. Observe the slideshow on the front page

### A clear and concise description of what you expected to happen.

The image widths / positions / heights should be consistently computed so there is no "jumpiness".

### What actually happened

The image height jumps between 506px and 507px many times a second.

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

**Comment by jeherve** [comment]
Thanks for the detailed report! I can definitely see the problem on your site at the moment.

As you mentioned, it may be caused by an interaction issue between this javascript and the other javascript running on the page. I was wondering if your theme offered a way to disable that "Slick" slideshow feature that they offer? I'd be curious to see if that would solve the problem on your site for now, until we find a way to make things more robust on our end.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
