### ISSUE TITLE
Launchpad save modal is blocking the UI during E2E tests

### ISSUE THREAD

**Issue by sharpirate** [Automattic/jetpack#28655]
During a Launchpad flow the E2E tests are stuck on the new modal that shows up once the post is published. We want to refactor the E2E tests so that they are not stuck on the new modal

![2023-01-30 14 21 17](https://user-images.githubusercontent.com/20927667/215619160-82b5e1d9-5a40-4c0c-8362-406cbee9357e.gif)

**Comment by Addison-Stavlo** [comment]
this seems to have been resolved a while back
