### ISSUE TITLE
Contact Form: Email notifications, instructions contradict form building validation?

### ISSUE THREAD

**Issue by osiux** [Automattic/jetpack#2867]
When you are creating a new contact form for a post, the instructions on the left of the "Email notifications" tab say:

> Do I need to fill this out?

> Nope. However, if you’d like to modify where your feedback is sent, or the subject line you can. If you don’t make any changes here, feedback will be sent to the author of the page/post and the subject will be the name of this page/post.

But if you left the "Enter your email address" field empty and try to change tab or clic "Save and go back to form builder", there is an alert stating that "is an invalid email address".

I think this is the wrong behavior?

**Comment by jeherve** [comment]
That seems to be a new bug indeed. Nice catch!

**Comment by dereksmart** [comment]
this is my fault :( should be a quick fix

**Comment by dereksmart** [comment]
@osiux can you checkout patch in #2872

**Comment by osiux** [comment]
@dereksmart Sorry, was sleeping haha but yeah, works perfectly!
