### ISSUE TITLE
Forms - Responses Export - Data columns order is not as expected and data fields from different forms, with different labels, are written into same column

### ISSUE THREAD

**Issue by digitalwaveride** [Automattic/jetpack#28723]
For context discussion here: https://github.com/Automattic/jetpack/pull/28678#issuecomment-1412115413
Post here: pcsBup-K4-p2

Example:

WP ADMIN

https://user-images.githubusercontent.com/5120357/216059899-43c31243-d923-4837-abe7-f6b6eae56f71.png

EXPORT

https://user-images.githubusercontent.com/5120357/216059708-9f7b3260-5fa7-4249-ad06-dd2bb3bef881.png

The order of the columns of the "middle category" [ all columns/values filled on submissions ] seems to not take the structure of the form into account.

It is also different from the structure in the WP-Admin view.

If you compare the /second form in WP-Admin with the Export, the "Website" column comes before the "Please rate our website" ... and there is the known issue of a "Comment" column is containing the content of "How could we improve" ... which should be it's own column.

**Comment by CGastrell** [comment]
FWIW, as part of how the plugin works, there are fixed fields/columns on the export process that will always take precedence as a sort of "normalization" process:
- name
- email
- website
- comment

Getting rid of those will imply some heavy refactoring on the export process and should not be taken lightly, we need to maintain some consistency. Also, this will imply a different way in which multiple form's responses are mixed on the same export.

**Comment by digitalwaveride** [comment]
Will be fixed via: https://github.com/Automattic/jetpack/pull/30475

**Comment by digitalwaveride** [comment]
Fixed via merged issues mentioned above.
