### ISSUE TITLE
Stats: Add a dismissable prompt to the top of the old Stats page to try out Odyssey Stats

### ISSUE THREAD

**Issue by jsnmoon** [Automattic/jetpack#28729]
![Image](https://user-images.githubusercontent.com/4044428/215222140-8154230c-4010-4308-bdd9-538c6abc3217.png)

This prompt should be shown a month after the customer has opted out of Odyssey Stats. Clicking the main CTA should enable Odyssey Stats and refresh the page.

**Comment by jsnmoon** [comment]
@kangzj: I assigned you to this task since you already started work for this in #28794.

**Comment by a8ck3n** [comment]
Do we still want to update this notice to include the image? That is the only part missing from the current implementation.

@jsnmoon @kangzj

**Comment by kangzj** [comment]
> Do we still want to update this notice to include the image? @a8ck3n 

I think so. We should implement the full design to attract users back, shouldn't we? @jsnmoon

**Comment by jsnmoon** [comment]
@a8ck3n @kangzj: Let's add the image! It consists of a screenshot stacked on top of a gradient.

![screens](https://user-images.githubusercontent.com/4044428/221662006-15cf9780-8f5c-47e6-b12b-bc4ca8c30e27.png)
![gradient](https://user-images.githubusercontent.com/4044428/221662016-da2b768b-3345-495f-8f2d-e51742479252.png)

**Comment by a8ck3n** [comment]
I think the nudge is complete now so closing this issue.
