### ISSUE TITLE
Donations block crashes when changing currency

### ISSUE THREAD

**Issue by dsas** [Automattic/jetpack#28724]
### Impacted plugin

Jetpack

### Quick summary

When changing the currency on the donations block there's a whole lot of errors in the browser console and editor representation changes to say:
> This block has encountered an error and cannot be previewed.

### Steps to reproduce

1. Open a new post
2. Insert a donations block
3. Change the currency using the block tools

### A clear and concise description of what you expected to happen.

The currency should be changed inside the block

### What actually happened

The editor representation changes to say:
> This block has encountered an error and cannot be previewed.

The browser console says:
```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    al https://s0.wp.com/wp-content/plugins/gutenberg-core/v15.1.0-rc.1/build/vendors/react-dom.min.js?m=1675272577h&ver=18:1
    enqueueForceUpdate https://s0.wp.com/wp-content/plugins/gutenberg-core/v15.1.0-rc.1/build/vendors/react-dom.min.js?m=1675272577h&ver=18:1
    forceUpdate https://s0.wp.com/wp-content/plugins/gutenberg-core/v15.1.0-rc.1/build/vendors/react.min.js?m=1675272577h&ver=18:1
    forceUpdate https://s0.wp.com/wp-content/plugins/gutenberg-core/v15.1.0-rc.1/build/components/index.min.js?m=1675272577h&ver=d8767a7cbb20a6132665:1
    Wu https://s0.wp.com/wp-content/plugins/gutenberg-core/v15.1.0-rc.1/build/components/index.min.js?m=1675272577h&ver=d8767a7cbb20a6132665:1
    Ur https://s0.wp.com/wp-content/plugins/gutenberg-core/v15.1.0-rc.1/build/vendors/react-dom.min.js?m=1675272577h&ver=18:1
    Jr https://s0.wp.com/wp-content/plugins/gutenberg-core/v15.1.0-rc.1/build/vendors/react-dom.min.js?m=1675272577h&ver=18:1
```

https://user-images.githubusercontent.com/93301/216387660-d6daad55-6fa1-4f2a-98d9-2753c8614ed9.mp4

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement. Just reload the page and the donations block will appear in the selected currency.

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Using a simple site and using gutenberg-edge (i.e. 15.1.0-rc1) via the gutenberg-edge blog sticker, it does not happen otherwise.

**Comment by mgozdis** [comment]
Another report 6044407-zd-woothemes

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: Could not Replicate
- Tested on AT: **Replicated**
- Tested on Self-hosted: **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated the issue on Self-Hosted and AT sites.  Same console error appears in both environments.
- Refreshing the page resolves the block error in both environments as well (though changing the currency again repeats the problem)
- Cannot select the `donations form` at all on my simple sites, which may reflect a separate issue.

**Self-Hosted Example**

https://user-images.githubusercontent.com/27249804/226713240-23d94e6e-5cbb-455f-99a1-58eb1aafe31a.mp4

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by cuemarie** [comment]
📌 ACTIONS
- Assigned to Apex (for lack of a better home)

**Comment by n3f** [comment]
Closing in favor of #30299 .
