### ISSUE TITLE
Subscriptions block: social follower count toggle confusion

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#28725]
> This UI piece confused me. The social count is included, but I can change it. It confused me to even have the option when 1. show subscriber count is disabled and 2. when the Social Sharing feature was disabled.

1. Does it make sense to display the disabled toggle "Include social followers in count" when the "Show subscriber count" toggle is turned off?
2. Does it make sense to display the "Include social followers in count" toggle when the Jetpack Publicize module is deactivated?

Context, internal: p8oabR-13S-p2#comment-7025
CC: @TimBroddin Looks like you worked on the toggle in #27443 do you have any thoughts?

**Comment by TimBroddin** [comment]
Hey @samiff,

I agree on both points. I am adding this to our project board.
