### ISSUE TITLE
Enhancement: Add helpful empty state to Form Responses table

### ISSUE THREAD

**Issue by manospsyx** [Automattic/jetpack#28734]
### Impacted plugin

Jetpack

### What

Add helpful empty state to Form Responses table

### How

As part of our "WooCommerce on DotCom" efforts, different key stakeholders including @that-mike-bal @verofasulo @xristos3490 and myself have pointed out the opportunity to improve the Form Responses empty state to communicate how merchants (and in general DotCom users) can make the most out of Form Blocks.

Here's a very quick example of how we could do it:

<img width="1456" alt="Screenshot 2023-02-03 at 9 24 27 AM" src="https://user-images.githubusercontent.com/1783726/216537799-b7320a1f-b28e-4259-9319-1d4e3bd0c744.png">

The link could point to: https://jetpack.com/support/jetpack-blocks/contact-form/

If there's limited capacity to prioritize this, please let me know and @xristos3490 or I will submit a PR.

**Comment by jeherve** [comment]
You'll be happy to hear that it's something the team currently working on the Contact Form plans on implementing very soon. You can read more about some of the upcoming changes here:
pcsBup-hX-p2

I think this issue can be closed since this is already on their radar, but I'll let @digitalwaveride weigh in and decide about that. :)

**Comment by manospsyx** [comment]
Love that PT! It looks like we are very far from having a solution to this (simple) problem in place, though.

I would ideally like to have something to support our work within the next 2 weeks: We have a top level menu item that fails to communicate why it's there and what it does :)

cc @verofasulo and @that-mike-bal for ideas

**Comment by that-mike-bal** [comment]
@manospsyx can we either just house the "feedback" section under Jetpack until the improvements are released or just implement something like you suggested temporarily? 


We usually just add a header and description with link to docs and I think that's fine for now
<img width="1067" alt="Screen Shot 2023-02-14 at 8 25 02 AM" src="https://user-images.githubusercontent.com/89872780/218766398-9e1802de-c8a8-40d3-82ae-9d51bc203fa5.png">

**Comment by manospsyx** [comment]
Probably yes.

**Comment by jeherve** [comment]
closing as we now have a Landing page view:

<img width="1318" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/85c18637-a733-462c-8a90-6c4f5a56a5e9">
