### ISSUE TITLE
Jetpack: Function amp_is_available was called incorrectly

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#28774]
### Impacted plugin

Jetpack

### Quick summary

PHP Notice:  Function amp_is_available was called **incorrectly**. `amp_is_available()` (or `amp_is_request()`, formerly `is_amp_endpoint()`) was called too early and so it will not work properly. WordPress is currently doing the `init` hook. Calling this function before the `wp` action means it will not have access to `WP_Query` and the queried object to determine if it is an AMP response, thus neither the `amp_skip_post()` filter nor the AMP enabled toggle will be considered. It appears the plugin with slug`jetpack-dev` is responsible; please contact the author. 
```

### Steps to reproduce

1. With Jetpack beta plugin on WoA, select bleeding edge
2. Visit the WordPress Dashboard
3. Expect to the see the notice with the _cli

### A clear and concise description of what you expected to happen.

_No response_

### What actually happened

_No response_

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

_No response_

**Comment by anomiex** [comment]
Instructions here seem incomplete. Try these:

1. With Jetpack beta plugin on WoA, select bleeding edge
2. Also install and activate the AMP plugin.
3. Make sure the Carousel module is enabled.
4. Visit the WordPress Dashboard (`/wp-admin`).
5. Expect to the see the notice with the _cli (go to `/_cli`, then run `wp php-errors`).

Hacking things to get a stack trace gives this:
```
Stack trace:
#0 /wordpress/plugins/amp/2.4.2/includes/amp-helper-functions.php(459): _doing_it_wrong('amp_is_availabl...', '`amp_is_availab...', '(This message w...')
#1 /wordpress/plugins/amp/2.4.2/includes/amp-helper-functions.php(465): {closure}()
#2 /wordpress/plugins/amp/2.4.2/includes/amp-helper-functions.php(806): amp_is_available()
#3 /wordpress/plugins/amp/2.4.2/includes/amp-helper-functions.php(837): amp_is_request()
#4 /srv/htdocs/wp-content/plugins/jetpack-dev/3rd-party/class.jetpack-amp-support.php(115): is_amp_endpoint()
#5 /srv/htdocs/wp-content/plugins/jetpack-dev/modules/carousel/jetpack-carousel.php(128): Jetpack_AMP_Support::is_amp_request()
#6 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(310): Jetpack_Carousel->init('')
#7 /srv/htdocs/__wp__/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#8 /srv/htdocs/__wp__/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#9 /srv/htdocs/__wp__/wp-settings.php(632): do_action('init')
#10 /srv/htdocs/wp-config.php(85): require_once('/srv/htdocs/__w...')
#11 /srv/htdocs/__wp__/wp-load.php(55): require_once('/srv/htdocs/wp-...')
#12 /srv/htdocs/__wp__/wp-blog-header.php(13): require_once('/srv/htdocs/__w...')
#13 /srv/htdocs/__wp__/index.php(17): require('/srv/htdocs/__w...')
#14 {main} in /srv/htdocs/__wp__/wp-includes/functions.php on line 5905
```
The code referenced at #​5 there was added in #25441. Issue #26658 also mentions the same notice and the same line.
