### ISSUE TITLE
Form block - Placeholder view, hover state issue

### ISSUE THREAD

**Issue by digitalwaveride** [Automattic/jetpack#28775]
Original report here: p8oabR-13S-p2#comment-7041

![Image](https://user-images.githubusercontent.com/5120357/217024987-6aff7804-8043-474f-a93b-886228d27b39.png)

> When I chose the form block, the form variation templates, the tooltip on hover was rendered for the first icon for Contact Form–the cursor was not hovering that icon:
When I hovered over other icons, the first tooltip didn’t disappear. It only disappeared when I clicked outside the icon or when hovering over and then outside:

**Comment by jcheringer** [comment]
I believe that's not related to Jetpack (Forms) changes.
I was able to reproduce the same behavior in the Columns block:

![image](https://user-images.githubusercontent.com/7811225/217358769-6c3cc1a8-b4b9-4b9b-b519-77b4eab33e8a.png)

**Comment by jcheringer** [comment]
Reported it here: https://github.com/WordPress/gutenberg/issues/48073
