### ISSUE TITLE
Comments: Add method to allow per-CPT disabling

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2882]
Some plugins add CPTs that have specific comment functionality (e.g. WooCommerce and their use of comments for reviews).

We should provide a relatively simple way to disable JP Comments per CPT.

ref: https://github.com/woothemes/woocommerce/issues/9152

**Comment by BFTrick** [comment]
Just to add on this doesn't have to have UI. Could just be a hook that another plugin could interact with.

**Comment by aheckler** [comment]
Kayako ticket this originated from is # 2210278.

**Comment by claudiosmweb** [comment]
:heart:
