### ISSUE TITLE
Deprecation Warning in PHP 8.1

### ISSUE THREAD

**Issue by hirasso** [Automattic/jetpack#28847]
### Impacted plugin

Super Cache

### Quick summary

With PHP 8.1 enabled, WP Super Cache is throwing a warning:

```
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /wp-content/plugins/wp-super-cache/wp-cache-phase2.php on line 32
```
I know this is not the only [problem with WordPress+PHP 8.1](https://github.com/wp-cli/wp-cli/issues/5623), but it would still be great to solve this IMHO (would take care of it myself if my last jetpack PR experience wouldn't have been so overwhelming 😅)

### Steps to reproduce

- Activate PHP 8.1
- Set `WP_DEBUG` to `true`

### A clear and concise description of what you expected to happen.

No warnings except the ones from WordPress' requests package

### What actually happened

One additional warning from super cache

### Impact

All

### Logs or notes

WP 6.1.1
Super Cache 1.9.3

**Comment by danielbachhuber** [comment]
Created a PR https://github.com/Automattic/wp-super-cache/pull/844
