### ISSUE TITLE
Anchor text does not strip HTML from Related Posts

### ISSUE THREAD

**Issue by ntpixels** [Automattic/jetpack#2884]
The anchor text shown when hovering over a Related Post is not stripping out the HTML, as per the code here: https://github.com/Automattic/jetpack/blob/master/modules/related-posts/jetpack-related-posts.php#L822

This the example from a user's site:
<img width="374" alt="screen shot 2015-10-23 at 12 52 55 pm" src="https://cloud.githubusercontent.com/assets/3965153/10699484/04bf179e-7985-11e5-973d-feea4dd6e687.png">

It may be related to issue https://github.com/Automattic/jetpack/issues/974

reported in 2391052-t

**Comment by jeherve** [comment]
Closing in favor of #3235
