### ISSUE TITLE
pasting a URL over existing content to form a link causes the text to be mis-marked, offset by 1 character.

### ISSUE THREAD

**Issue by heckj** [Automattic/jetpack#28854]
### Impacted plugin

Jetpack

### Quick summary

(This is specifically about the Jetpack iOS app, recently replacing the wordpress mobile app. If this is the wrong place for this report, please redirect me)

On iOS (iPadOS) - I copy URLs from safari, and then transition back to the Jetpack app to create a link with that data. I've typically already written the link text, so I select the link text in the iOS TextField and then do the paste. The result, however, uniformly offsets the linked content.

For example, in the sentence fragment: `linked from the Daring Fireball site.` I tried to paste `https://daringfireball.com` over `Daring Fireball site`, the text that appears to be made into a link is `aring Fireball site.`, missing the initial character (`D`) and incorrectly including the period.

Re-selecting and re-pasting extends the range to what I expected to happen originally, so I suspect this might be something happening on re-activation of the iOS app and tracking the current cursor location in the content.

### Steps to reproduce

1. in the JetPack iOS app, create some text in a blog post draft
2. cmnd-tab to safari, copy a url
3. cmnd-tab back to JetPack, and select a word of content
4. paste

### A clear and concise description of what you expected to happen.

The content I originally selected should be transformed into an `A HREF` link.

### What actually happened

The content that's made into the link is offset by one character

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by jeherve** [comment]
Hi!

I believe the bugs for the Jetpack iOS app are still tracked in the WordPress iOS app repository for now. The bug you found most likely happens in the WordPress app as well.

I searched for an existing issue for that link problem but didn't find any. I think it would be worth opening a new issue here about it:
https://github.com/wordpress-mobile/WordPress-iOS/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

Let me know if you'd rather have me open the issue for you!

Thank you.
