### ISSUE TITLE
Shortcode: Recipe: Embed a QR code

### ISSUE THREAD

**Issue by rothschild86** [Automattic/jetpack#2887]
This would be an awesome way to bring a reader back from a printed material.

Can use google's https://chart.googleapis.com/chart?cht=qr

**Comment by samhotchkiss** [comment]
This is certainly something we'd look at including, but not something that is on our roadmap-- if you'd like to submit a pull request, we'll definitely check it out!

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
