### ISSUE TITLE
When user disconnects Jetpack, WooCommerce Shipping & Tax is not listed as one of the plugins that will stop working

### ISSUE THREAD

**Issue by pehaa** [Automattic/jetpack#28870]
### Impacted plugin

Jetpack

### Quick summary

WooCommerce Shipping & Tax requires the Jetpack plugin activated and connected.
When a user disconnects Jetpack, they see a warning that some of the plugins will no longer work.
WooCommerce Shipping & Tax is not listed, though.

<img width="1188" alt="Markup 2023-02-09 at 14 46 50" src="https://user-images.githubusercontent.com/774920/217863553-1d49fcf5-ce19-4432-aa14-77e268d5a3ec.png">

### Steps to reproduce

1. Start a website, install, activate and connect Jetpack
2. Install WooCommerce and [WooCommerce Shipping & Tax](https://wordpress.org/plugins/woocommerce-services/) plugin
3. Disconnect Jetpack

### A clear and concise description of what you expected to happen.

Users see WooCommerce Shipping & Tax in the list of plugins that will no longer work.

### What actually happened

You will not see WooCommerce Shipping & Tax on the list of plugins that will no longer work

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by sergeymitr** [comment]
Hi there!

All those plugins aren't dependent on Jetpack-the-plugin, but integrate the [Connection package](https://github.com/Automattic/jetpack/tree/trunk/projects/packages/connection) instead.
The list of connected plugins comes from the [Jetpack connection configuration](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/connection/docs/register-site.md#initialize-the-package).

Our approach to the issue pretty much depends on whether you're planning to integrate the Connection package, or will stick to Jetpack-the-plugin being required.
If latter, we could add a filter for you to use to add WooCommerce Shipping & Tax into the list. Is this the way you'd prefer?

**Comment by pehaa** [comment]
Hey @sergeymitr 👋
Thank you for replying so quickly! 

Do I understand correctly that this requires decisions/changes within the WooCommerce Shipping & Tax plugin?
Either way? 
Should I relay this question to the dev team behind WooCommerce Shipping & Tax (internally or create an issue in the plugin's repo and mention this one)? What's the best way to proceed?

Thank you!

**Comment by jeherve** [comment]
@sergeymitr Would #33920 have helped with this issue?

**Comment by sergeymitr** [comment]
Hi @pehaa, @jeherve.
I apologize for such a long delay, I somehow missed the pings.

> Do I understand correctly that this requires decisions/changes within the WooCommerce Shipping & Tax plugin?

That is correct, the changes had to be done on the plugin's side, and they did get implemented.
WCS&T plugin got switched to the Connection package, so it no longer requires Jetpack to be installed: https://github.com/Automattic/woocommerce-services/pull/2439/

The PR also solved the problem discussed here, and the plugin is now displayed in the "Disconnect Jetpack" modal.
<img width="1218" alt="Screenshot 2023-12-06 at 17 19 09" src="https://github.com/Automattic/jetpack/assets/1341249/8804ebe2-7a6f-40d5-b6cb-549383f38f4b">
