### ISSUE TITLE
Enhancement: Option to Hide 7 Day Stat Summary on Stat Dashboard

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#28896]
### Impacted plugin

Jetpack

### What

We've received a few requests from users to hide the 7 day stat summary.

### How

Some folks have requested an option to hide the 7 day stat summary at the top of the stats dashboard.

**Comment by sdixon194** [comment]
Created from this issue here: https://github.com/Automattic/jpop-issues/issues/8068

cc @Automattic/red

**Comment by jsnmoon** [comment]
This is a duplicate of https://github.com/Automattic/wp-calypso/issues/69981; please re-open the ticket if I'm mistaken.
