### ISSUE TITLE
Enhancement: Remove H1 tag

### ISSUE THREAD

**Issue by fentisam** [Automattic/jetpack#28917]
### Impacted plugin

Search

### What

Remove the H1 tag that is being displayed for "Search Results"

### How

Change the H1 tag to another tag as this is affects SEO

**Comment by jeherve** [comment]
Thanks for the suggestion. This is already tracked in #27947 so I'll close this issue as duplicate. Do not hesitate to subscribe to the other issue to be informed of our progress on this.
