### ISSUE TITLE
Replace Sharing Link Text When CSS / JS Disabled

### ISSUE THREAD

**Issue by misfist** [Automattic/jetpack#2892]
I have disabled CSS and JS for the Sharing module, and have 2 services active. They appear everywhere as:

* Click to share on Twitter (Opens in new window)
* Share on Facebook (Opens in new window)

I'd like to change the text (currently inconsistent). Is there a way to do that?

**Comment by jeherve** [comment]
It's currently not possible to change that text. We'll make sure it's consistent, though, and will see about updating the Facebook sharing message to match the other Sharing services.

**Comment by misfist** [comment]
Thanks for the response. It would be nice to have a hook that could be used to change the text. :)

**Comment by jeherve** [comment]
You can already use the `jetpack_sharing_display_text` to do just that! I'd also recommend using the `jetpack_sharing_display_title` filter as well, to change the `title` parameter of the link, like so:

```php
function jetpack_developer_custom_sharing_text( $title, $this, $id, $args ) {
        return 'Spread the word!';
}
add_filter( 'jetpack_sharing_display_title', 'jetpack_developer_custom_sharing_text', 20, 4 );
add_filter( 'jetpack_sharing_display_text', 'jetpack_developer_custom_sharing_text', 20, 4 );
```

**Comment by misfist** [comment]
Great!

I implemented it with the following:

```php
function jetpack_developer_custom_sharing_text( $text, $this, $id, $args ) {

  switch ( true ) {
    case ( 'sharing-twitter-650' == $id ):
      $text = 'Share on Twitter';
      break;
    case ( 'sharing-facebook-650' == $id ):
      $text = 'Share on Facebook';
      break;
    default:
      $text = $text;
  }
  return $text;
}
add_filter( 'jetpack_sharing_display_text', 'jetpack_developer_custom_sharing_text', 20, 4 );
```
