### ISSUE TITLE
Jetpack's Static files CDN broke admin pages of WP Cerber

### ISSUE THREAD

**Issue by benoitfouc** [Automattic/jetpack#28940]
**Impacted plugin**
Jetpack
WP Cerber (https://wpcerber.com/installation/)

**Quick summary**
When we activate the Jetpack static file CDN, the admin and settings pages of the WP Cerber plugin are broken. 
Some files like CSS and JS can't be loaded correctly.

![image](https://user-images.githubusercontent.com/10956350/218698711-5c2ff132-72fb-4ac4-be5a-89f49bb615eb.png)
(here you can see the broken page and the browser console with a lot of errors)

**Steps to reproduce**
Install Jetpack and WP Cerber plugins.
Activate the Jetpack performance option Static CDN files on Jetpack > Settings > Performance > Enable site accelerator > Speed up static file load times
Go to the admin setting page of WP cerber to see the problems

WP Cerber settings page when jetpack static files cdn is **activate** :
![image](https://user-images.githubusercontent.com/10956350/218699744-599294a5-51a3-4829-bf13-b6038cff7736.png)

WP Cerber settings page when jetpack static files cdn is **desactivate** :
![19eec19631f0b0cb7cb1a62379485236](https://user-images.githubusercontent.com/10956350/218700628-7b3fd5e2-4413-4af0-847c-2639d1a2ba61.png)

The errors on the browser console :
![image](https://user-images.githubusercontent.com/10956350/218700087-b9a75202-55bb-4baf-9c88-28b52753834f.png)

regards

**Comment by jeherve** [comment]
Looking at the errors in your browser console, it would seem that the resources cannot be loaded from remote sources (like a CDN) on your site because of custom Content Security Policy rules.

It appears that the WP Cerber plugin implements such rules for all its settings pages, since [its 9.2 release, back in September of  last year](https://wpcerber.com/wp-cerber-security-9-2/):

> Implemented Content-Security-Policy HTTP header as an extra layer of protection for the WP Cerber admin pages. This also means no support for unsecure HTTP connections to WP Cerber admin pages anymore.

As a result, when you try to access any of the WP Cerber admin pages, the calls to WordPress Core static assets (hosted remotely with the CDN) fail, and stylesheets as well as JavaScript files used to style the page are missing.

The WP Cerber team knows about the issue, as it was also reported to them [in the support forums](https://wordpress.org/support/topic/css-formatting-for-the-page-appears-to-be-missing/).

Until this is fixed in the WP Cerber team, you could bypass Jetpack's Asset CDN when you're on a WP Cerber admin page, by adding the following code snippet to your theme's `functions.php` file, or [to a functionality plugin on your site](https://jetpack.com/support/adding-code-snippets/):

```php
/**
 * Filter the core version and locale
 * used for the static assets CDN from Jetpack,
 * when on WP Cerber's admin pages.
 *
 * We'll return a custom version number that we know
 * will never match a public version of WordPress.
 *
 * @param array $version_and_locale array( $version  = core assets version, i.e. 4.9.8, $locale = desired locale )
 *
 * @return array The core version and locale.
 */
add_filter(
	'jetpack_cdn_core_version_and_locale',
	function ( $version_and_locale ) {
		$current_screen = get_current_screen();
		if (
			! empty( $current_screen )
			&& false !== strpos( $current_screen->base, 'cerber' )
			&& ! empty( $version_and_locale )
		) {
			return array( 'cerber_' . $version_and_locale[0], $version_and_locale[1] );
		}

		// Fallback.
		return $version_and_locale;
	}
);

/**
 * Filter the name of the Jetpack plugin
 * returned for the static assets CDN from Jetpack,
 * when on WP Cerber's admin pages.
 *
 * We'll return a custom plugin version that we know
 * will never be used by Jetpack.
 *
 * @param array $jetpack_slug_and_version array( $slug = the plugin repository slug, i.e. jetpack, $version = the plugin version, i.e. 6.6 )
 *
 * @return array The Jetpack plugin slug and version.
 */
add_filter(
	'jetpack_cdn_plugin_slug_and_version',
	function ( $jetpack_slug_and_version ) {
		$current_screen = get_current_screen();
		if (
			! empty( $current_screen )
			&& false !== strpos( $current_screen->base, 'cerber' )
			&& ! empty( $jetpack_slug_and_version )
		) {
			return array( $jetpack_slug_and_version[0], 'cerber_' . $jetpack_slug_and_version[1] );
		}

		return $jetpack_slug_and_version;
	}
);
```

I'll post in that WP Cerber forum thread to let their team know about the work-around too.

**Comment by benoitfouc** [comment]
Hi @jeherve  thanks for all informations, it's very appreciate. And thanks for answer to all posts on the support section of WP Cerber.

I apply your code of my 17 websites and many of them have a fatal error :
```
[14-Feb-2023 13:20:54 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_current_screen() in /home/natureetws/boutique/wp-content/plugins/natureetpartage/natureetpartage.php:353
Stack trace:
#0 /home/natureetws/boutique/wp-includes/class-wp-hook.php(308): {closure}(Array)
#1 /home/natureetws/boutique/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#2 /home/natureetws/boutique/wp-content/plugins/jetpack/modules/photon-cdn.php(71): apply_filters('jetpack_cdn_cor...', Array)
#3 /home/natureetws/boutique/wp-includes/class-wp-hook.php(308): Jetpack_Photon_Static_Assets_CDN::cdnize_assets('')
#4 /home/natureetws/boutique/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#5 /home/natureetws/boutique/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /home/natureetws/boutique/wp-includes/functions.wp-styles.php(57): do_action('wp_print_styles')
#7 /home/natureetws/boutique/wp-includes/class-wp-hook.php(308): wp_print_styles(false)
#8 /home/natureetws/boutique/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#9 /home/natureetws/boutique/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#10 /home/natureetws/boutique/wp-includes/general-template.php(3043): do_action('wp_head')
#11 /home/natureetws/boutique/wp-content/themes/salient/header.php(16): wp_head()
#12 /home/natureetws/boutique/wp-includes/template.php(783): require_once('/home/natureetw...')
#13 /home/natureetws/boutique/wp-includes/template.php(718): load_template('/home/natureetw...', true, Array)
#14 /home/natureetws/boutique/wp-includes/general-template.php(48): locate_template(Array, true, true, Array)
#15 /home/natureetws/boutique/wp-content/plugins/woocommerce/templates/single-product.php(22): get_header('shop')
#16 /home/natureetws/boutique/wp-includes/template-loader.php(106): include('/home/natureetw...')
#17 /home/natureetws/boutique/wp-blog-header.php(19): require_once('/home/natureetw...')
#18 /home/natureetws/boutique/index.php(17): require('/home/natureetw...')
#19 {main}
  thrown in /home/natureetws/boutique/wp-content/plugins/natureetpartage/natureetpartage.php on line 353
```

**Comment by jeherve** [comment]
Ah sorry about that! It seems to be conflicting with your setup, with WooCommerce and the Salient theme.

In this case I'm afraid you'll need to deactivate Jetpack's static file CDN option, as you will not be able to apply the workaround. You could ask the folks at WP Cerber if they would be willing to add a filter in their `crb_admin_headers` function, allowing you to customize the extra Content Security Policy headers they've added to their admin pages.

**Comment by jeherve** [comment]
Coming back to this, and following the reply of the WP Cerber author in the thread, there may be a middle-ground work-around that could help you.

We cannot easily disable the Asset CDN only on WP Cerber admin pages, but we can easily disable it on **all admin pages**. The feature will still work on your site's frontend, but it will not be active in your dashboard, and as a result will not break WP Cerber's admin page.
You can achieve this result with this code snippet:

```php
/**
 * Disable Jetpack's Asset CDN in the wp-admin dashboard.
 *
 * @return bool
 */
add_filter(
	'jetpack_force_disable_site_accelerator',
	function () {
		if ( is_admin() ) {
			return true;
		}
		return false;
	}
);
```

**Comment by benoitfouc** [comment]
hello @jeherve thank you so much for all informations and for you detailled explanation.

I understand and your last solution look good however i try to put this snippet on the functions.php files of the theme of 2 of my websites, and the WP Cerber admin dashboard still broken. It's like the snippet not working good.


regards

**Comment by jeherve** [comment]
> I understand and your last solution look like good however i try to put this snippet on the functions.php files of the theme of 2 of my websites, and the WP Cerber admin dashboard still broken. It's like the snippet not working.

Could you try adding it to a functionality plugin instead, and see if that helps?

**Comment by benoitfouc** [comment]
> > I understand and your last solution look like good however i try to put this snippet on the functions.php files of the theme of 2 of my websites, and the WP Cerber admin dashboard still broken. It's like the snippet not working.
> 
> Could you try adding it to a functionality plugin instead, and see if that helps?

Okay i try to put the snippet on a customize plugin and that working fine ! That's strange

I this snippet will not create fatal error or compatibility problems with others plugins/theme like the previous snippet ?

regards

**Comment by jeherve** [comment]
> I this snippet will not create fatal error or compatibility problems with others plugins/theme like the previous snippet ?

It shouldn't, no.

**Comment by benoitfouc** [comment]
> > I this snippet will not create fatal error or compatibility problems with others plugins/theme like the previous snippet ?
> 
> It shouldn't, no.

Okay thank you, so as you said to the WP Cerber developper : the best way is to include this snippet directly on the WP Cerber plugin. (even more since that the snippet not working on the functions.php files)

This issue is now fixed, thanks again
