### ISSUE TITLE
VideoPress: "Upload to VideoPress" button is shown on disabled local video row on mobile

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#28951]
pe4Cmx-Qm-p2#comment-397

It is necessary to remove or disable the button.

**Comment by nunyvega** [comment]
More details:
On the VideoPress dashboard, whenever a local video has already been uploaded to VideoPress, we hide the button to upload the video.  This is not working on smaller screens.

Currently, you can see the button on smaller screens (tested using Safari):



https://user-images.githubusercontent.com/16329583/218823862-c790fd3b-cc1e-42bc-84fb-54847e1dd940.mov

Expected:
To have no Upload button on smaller screens, similar to how it works on big screens.
