### ISSUE TITLE
VideoPress available storage space in Atomic sites doesn't work

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#28997]
The bar is always showing `0% of 1 B of cloud video storage`

![Image](https://user-images.githubusercontent.com/16329583/219357457-1f5bd090-e8fc-472f-bae1-eae21aa82304.png)

![Image](https://user-images.githubusercontent.com/16329583/219357806-31bdd397-ccbb-48ca-b2e3-aed372233aad.png)

**Comment by dhasilva** [comment]
Merging with https://github.com/Automattic/jetpack/issues/27625 as the problem of the `1 B` and the `storageUsed: 0` probably have the same cause.
