### ISSUE TITLE
Counting stats for other pages

### ISSUE THREAD

**Issue by folgerj** [Automattic/jetpack#2900]
I have one of my websites using Jetpack as http://www.jeff-foliage.com/  which is a normal  wordpress installation. Except for the fact I have started creating newsletters like this http://www.jeff-foliage.com/End-of-Foliage-1.html and attaching them to my site (I'm coding them in dreamweaver) and I have a New England webcam page here: http://www.jeff-foliage.com/webcam-NewEngland.html This wouldn't be bad except for the fact that this summer I've had around 21,000 views on the webcam page and yes I have it counted in Google Analytics you say my Sept numbers are 96,221 views and google analytics says over 102,000. 
I would like to see the ability to capture these webpages in my totals. Or to be able to modify your results with the visitor counters

**Comment by kraftbj** [comment]
Howdy @folgerj - thanks for the suggestion. I don't believe this is something we're going to look to pursue at this time. The stats system is pretty heavily built with the assumption of using WordPress and it wouldn't be trivial to add full-feature support to using the code elsewhere.

Cheers!
