### ISSUE TITLE
Hovercard does not load for post author

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#2904]
I am not 100% certain that the issue description is accurate, but it appears to be. Steps to reproduce:

1) Comment on a post for which you are the post author (or maybe, it's the site admin Hovercard that doesn't load?)
2) Try to view the hovercard for other commenters, and the author.

Expected: 

The hovercard will load for all commenters

Actual:

it fails to load, only for the post author.I see no console errors for it.

Raised in 2394814-t

**Comment by jeherve** [comment]
> 1) Comment on a post for which you are the post author (or maybe, it's the site admin Hovercard that doesn't load?)

Could you make a quick test to clarify whether this applies to the post author, site admin, and/or Jetpack master user?

Thanks!

**Comment by jeherve** [comment]
@richardmtl Did you have the chance to look into this?

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
