### ISSUE TITLE
Jetpack Admin Product views: update product icons in bundle pricing views

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#29045]
### What's happening?

All cards that show Backup + Anti-spam should use the newer (VaultPress and Akismet) logo icons:

![Image](https://user-images.githubusercontent.com/7129409/220127041-2e3529aa-9024-43ad-b459-88079f50c51f.png)

**Comment by jeherve** [comment]
@Automattic/jetpack-design Would it be possible to get a new svg to replace this "combined" one, to use on the right side of the product views?

![combined](https://user-images.githubusercontent.com/426388/220166924-0cbba204-818b-448e-a2bf-3b075695f99a.svg)

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/426388/220167029-d37922a6-7c95-4b38-8ec7-38469b3b7fa1.png">

**Comment by bluefuton** [comment]
Talked to @keoshi in Jetpack Design about this. They let me know we're already using all the correct icons in `trunk` (including the bundle icon) 🙂 And sure enough, here they are:

<img width="1102" alt="Screenshot 2023-03-29 at 10 46 04 AM" src="https://user-images.githubusercontent.com/17325/228374217-622f4c94-3f18-4705-ac82-b08508eceef7.png">

Closing this one.
