### ISSUE TITLE
Jetpack Plugin: Update style of post-activation connection screen.

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#29051]
### What's happening?

Install Jetpack → Click Plugins on the WPA side menu → In the Plugins table, under Jetpack, click Activate → 

1. The page style is old and should be updated to the newer RNA style
2. The page scroll is too long (lots of white space at the bottom)
3. 
![Image](https://user-images.githubusercontent.com/7129409/220124580-a10316bf-c964-4495-b9d0-0fa21ac8327f.png)

**Comment by jeherve** [comment]
Instead of redesigning that screen, I was wondering if we should follow the approach our standalone plugins have been taking, and redirect folks to the Jetpack plugin page on activation, instead of staying on the plugins screen?

This of course may not be the best option for sites where Jetpack is already pre-installed and pre-activated. I assume that would be one reason to keep that screen around.

Edit: I looked into it a bit more in Tracks, and that full-screen prompt remains our 4th most used way to connect Jetpack, if I'm not mistaken. So we need to keep it around :)

**Comment by jeherve** [comment]
Beyond making the button black, I assume we'll want to update the illustrations as well. I'll mark this issue as needing design. Design team, if you have any recommendations as to what should be changed, let us know!

**Comment by jeherve** [comment]
For reference, some prior art when we updated the other banner:

-  #24501
- p6TEKc-6dA-p2

**Comment by eeeeeevon2023** [comment]
Yes, we'll want to bring this in to design  and spruce it up.  This stuff came in while we were at our meetup in Vienna.

**Comment by jeffgolenski** [comment]
Just saw this pop up in the excellence board! Good news is that we already have a design for this that's actually in production @jeherve! 

**Here's the story**
This page in your above issue, was displayed in 2 places after jetpack core activation:
1. `/wp-admin/admin.php?page=jetpack#/`
2. `/wp-admin/plugins.php?plugin_status=all&paged=1&s`

 Then we redesigned it, and it only shipped to one location, I guess. `/wp-admin/admin.php?page=jetpack#/`
 
 We just need to replace this page with the new one!

**Current page**
<img width="1712" alt="Screen Shot 2023-03-17 at 4 23 12 PM" src="https://user-images.githubusercontent.com/214813/226030650-a05f3044-a2b9-4cc0-8ac0-7f1cf5639820.png">

Should be this design from `/wp-admin/admin.php?page=jetpack#/`
<img width="1715" alt="Screen Shot 2023-03-17 at 4 23 25 PM" src="https://user-images.githubusercontent.com/214813/226030737-db4fe623-3f83-4b8f-ace1-57f425a3c28d.png">


cc @dereksmart  @eeeeeevon2023

**Comment by jeherve** [comment]
@jeffgolenski I like the idea! We would have to add a dismiss icon, but other than that it should work just as is. 👍

**Comment by jeffgolenski** [comment]
@jeherve Perfect. We can pull the dismiss icon / text that displays on the Assistant on `/wp-admin/plugins.php` after an account is connected. 

<img width="1711" alt="Screen Shot 2023-03-21 at 11 38 17 AM" src="https://user-images.githubusercontent.com/214813/226659338-76e30346-4975-48fa-8b23-186daf16b0a3.png">

**Comment by jeherve** [comment]
> We can pull the dismiss icon / text that displays on the Assistant

I'm still working on that PR, but I ended up taking a different approach in my PR (#29566). I used Core's existing modal component and its dismiss functionality. Let me know what you think about it!

**Comment by jeffgolenski** [comment]
@jeherve Thank you! responded in the PR!
