### ISSUE TITLE
VideoPress: Core video block does not recognize playsinline attribute for non-VideoPress videos

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#29075]
It seems that a `core/video` (v5) block with a non-VideoPress video breaks when setting the `playsinline` attribute, which works for VideoPress videos.
The attribute works when Jetpack is not installed.

Steps to reproduce: https://github.com/Automattic/jetpack/issues/23953#issuecomment-1217223583

**Comment by andrii-lysenko** [comment]
@dhasilva is this still an issue you would like to proceed with or it's safe to close?

**Comment by dhasilva** [comment]
@andrii-lysenko Safe to close. I just tested it again and the problem does not happen anymore, so it seems to have been fixed at some point.
