### ISSUE TITLE
Module List: CSS applied to sidebar elements as well

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2909]
Note the broken icon appearing right before "Stats" in the module list sidebar:

![screen shot 2015-10-28 at 1 31 33 pm](https://cloud.githubusercontent.com/assets/426388/10788497/3e3d3068-7d78-11e5-9a9d-1fa91f864da3.png)

It seems like we should be more specific with our CSS to avoid this issue.

cc @jeffgolenski

**Comment by jeffgolenski** [comment]
This issues becomes irrelevant for 4.1. Thanks for reporting Jer!
