### ISSUE TITLE
Jetpack: jetpack_oembed_timeout_override() function causing plugin/theme conflicts

### ISSUE THREAD

**Issue by lakellie** [Automattic/jetpack#29159]
### Impacted plugin

Jetpack

### Quick summary

Over the past week or so, I have seen a couple reports of fatal errors caused by the `jetpack_oembed_timeout_override()` function in `jetpack/modules/shortcodes/others.php` where it is conflicting with the timeout functions coded into another plugin or theme. I don't know if something recently changed on our end to make this type of conflict more likely — or if there's even anything we can do about it— but I figured I would report it here just in case there is some way we can improve the Jetpack code.

## First example

Conflict with the Kallyas theme. 

```
[17-Feb-2023 11:26:06 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function jetpack_oembed_timeout_override(), 1 passed in /wordpress/core/6.1.1/wp-includes/class-wp-hook.php on line 308 and exactly 2 expected in /wordpress/plugins/jetpack/11.9-a.1/modules/shortcodes/others.php:29
Stack trace:
#0 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(308): jetpack_oembed_timeout_override(30)
#1 /wordpress/core/6.1.1/wp-includes/plugin.php(205): WP_Hook->apply_filters(30, Array)
#2 /srv/htdocs/wp-content/themes/kallyas/framework/hg-theme-framework/inc/api/ZN_HogashDashboard.php(478): apply_filters('http_request_ti...', 30)
#3 /srv/htdocs/wp-content/themes/kallyas/framework/hg-theme-framework/inc/api/ZN_HogashDashboard.php(76): ZN_HogashDashboard::request('theme_register', Array)
#4 /srv/htdocs/wp-content/themes/kallyas/framework/hg-theme-framework/inc/admin/class-zn-admin.php(82): ZN_HogashDashboard::connectTheme('344AD-7029F-D34...')
#5 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(308): ZnAdmin->ajax_theme_registration_hook('')
#6 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#7 /wordpress/core/6.1.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /wordpress/core/6.1.1/wp-admin/admin-ajax.php(188): do_action('wp_ajax_zn_them...')
#9 {main}
  thrown in /wordpress/plugins/jetpack/11.9-a.1/modules/shortcodes/others.php on line 29
```

Some insight from @kriskorn on this one:

"Jetpack adds an oembed timeout filter for iCloud embeds. It has 2 arguments. However, in the Kallyas theme they have such a variable in **/wp-content/themes/kallyas/framework/hg-theme-framework/inc/api/ZN_HogashDashboard.php**:

`$timeout = apply_filters( 'http_request_timeout', 30 );`

In here, they follow the filter https://developer.wordpress.org/reference/hooks/http_request_timeout/ to the dot, but because Jetpack had 2 arguments, we got a fatal with too few arguments, because in the theme there was only 1."

## Second example

Conflict with the VC Mailchimp plugin. 

```
An error of type E_ERROR was caused in line 29 of the file /wp-content/plugins/jetpack/modules/shortcodes/others.php. Error message: Uncaught ArgumentCountError: Too few arguments to function jetpack_oembed_timeout_override(), 1 passed in /wp-includes/class-wp-hook.php on line 308 and exactly 2 expected in /wp-content/plugins/jetpack/modules/shortcodes/others.php:29
Stack trace: #0 /wp-includes/class-wp-hook.php(308): jetpack_oembed_timeout_override(30)
#1 /wp-includes/plugin.php(205): WP_Hook->apply_filters(30, Array)
#2 /wp-content/plugins/vc-mailchimp/Mailchimp.php(183): apply_filters('http_request_ti...', 30)
#3 /wp-content/plugins/vc-mailchimp/Mailchimp.php(71): VC_Mailchimp_Api->process_request('lists', Array)
#4 /wp-content/plugins/vc-mailchimp/lib/class-vc-map.php(938): VC_Mailchimp_Api->get_lists(Array)
#5 /wp-content/plugins/vc-mailchimp/lib/class-vc-map.php(34): VC_Mailchimp_Map->vc_mailchimp_
```

**Comment by kriskorn** [comment]
> In here, they follow the filter https://developer.wordpress.org/reference/hooks/http_request_timeout/ to the dot, but because Jetpack had 2 arguments, we got a fatal with too few arguments, because in the theme there was only 1."

It seems I am incorrect here. Looking at the hook again, it clearly says: _float_ $timeout_value, _string_ $url. 
Not sure what I saw or why I wrote that.

Jetpack has those two arguments, but the Kallyas theme only has one - the timeout value, but no _string_ for url.
Good explanation by @jeherve  in p1676651275533489-slack-jetpack-crew and I think those _other_ themes/plugins actually have issues with using the filter incorrectly.

**Comment by lakellie** [comment]
Thanks, Kris! In case this is something we can't address on our side, I'm going to document this here in case anyone runs into the same issue in the future and isn't able to fix the offending theme/plugin —

To force Jetpack not to load the others.php file, you can use the following snippet:

```
add_filter(
	'jetpack_tools_to_include',
	function ( $tools ) {
		$index = array_search(
			'shortcodes/others.php',
			$tools,
			true
		);
		if ( $index ) {
			unset( $tools[ $index ] );
		}
		return $tools;
	}
);
```

**Comment by bizanimesh** [comment]
Hey team - we have a [similar issue](https://wordpress.org/support/topic/error-on-jetpack-modules-shortcodes-others-php/) for the Kallyas theme, and the above code snippet is not working, could you please have a look if there is anything that can be done from our side?

**Comment by jeherve** [comment]
If the `shortcodes/others.php` file is still loaded on the site, that means the code snippet you provided them does not run. I would recommend double-checking that.
