### ISSUE TITLE
PHP 8.2 deprecated warning dynamic property

### ISSUE THREAD

**Issue by ipajen** [Automattic/jetpack#29167]
### Impacted plugin

Protect

### Quick summary

Using PHP 8.2 following deprecation warning is given :

`Deprecated: Creation of dynamic property Automattic\Jetpack\Connection\Manager::$error_handler is deprecated in C:\xampp\htdocs\wp\wp-content\plugins\jetpack-protect\jetpack_vendor\automattic\jetpack-connection\src\class-manager.php on line 94`

### Steps to reproduce

1. Install fresh installation of WordPress 6.2 beta2 on PHP 8.2
2.  Enable debug in Wp-config.php with define( ‘WP_DEBUG’, true ); define( ‘WP_DEBUG_LOG’, true ); define( ‘WP_DEBUG_DISPLAY’, true );
3. Install the JetPack Protect version 1.2
4. Activate the plugin and the warning will show.

### A clear and concise description of what you expected to happen.

That no deprecation warning is shown.

### What actually happened

deprecation warning is shown

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by jeherve** [comment]
Thanks for the report!

This is an odd one, I don't understand why `$error_handler` reports a dynamic property error, when it is explicitly declared higher in the class:
https://github.com/Automattic/jetpack/blob/210e75345653abee7954a11d3669cd56175b9ea5/projects/packages/connection/src/class-manager.php#L48-L53

@anomiex Since you worked on #27949, maybe you have an idea here?

**Comment by anomiex** [comment]
The [version of the package included in Protect version 1.2](https://github.com/Automattic/jetpack-protect-plugin/blob/1.2.0/jetpack_vendor/automattic/jetpack-connection/src/class-manager.php) does not include #27968. Version 1.3, currently in beta, [does include the updated package](https://github.com/Automattic/jetpack-protect-plugin/blob/1.3.0-beta/jetpack_vendor/automattic/jetpack-connection/src/class-manager.php). So this is already fixed, it's just waiting for a plugin release.

I note Protect seems to have really long betas: 1.2.0-beta was created 2022-12-05 while 1.2.0 was released over a month later on 2023-01-16, and 1.3.0-beta was created over a month ago on 2023-01-25. Pinging @Automattic/yamato-scan for further comment.

**Comment by nateweller** [comment]
> I note Protect seems to have really long betas: 1.2.0-beta was created 2022-12-05 while 1.2.0 was released over a month later on 2023-01-16, and 1.3.0-beta was created over a month ago on 2023-01-25. Pinging https://github.com/orgs/Automattic/teams/yamato-scan for further comment.

After [some issues](https://github.com/Automattic/jetpack/issues/28819) with the WAF package in Jetpack 11.8 release, we decided to spend some extra time adding more test coverage and error handling to the firewall before releasing 1.3.0 of Jetpack Protect.

I expect to have all of the improvements merged this week, and will likely release next week. Will discuss with @miguelxpn if the WAF package updates warrant a second beta period or not.

More frequent/iterative releases are certainly on our team's radar as well.
