### ISSUE TITLE
Carousel: Uncrawlable link created by jp-carousel on image meta description

### ISSUE THREAD

**Issue by mrekici** [Automattic/jetpack#29168]
### Impacted plugin

Jetpack

### Quick summary

PageSpeed Insights are bringing up an issue with the images on my website. Image meta descriptions create an uncrawlable link both for mobile and desktop. It is only created when there is a cover image, so this code exists only once per page if there is a cover image.

`<a class="jp-carousel-image-download" target="_blank" style="display: none;">`

Example pages:
https://emreekici.com/mixing-template/ -> problem occurs
https://emreekici.com/contact/ -> no problem

Thank you.

### Steps to reproduce

1. Create a page with a cover image.
2. An uncrawlable meta description for the image is created.

### A clear and concise description of what you expected to happen.

A crawlable meta description for the image is created.

### What actually happened

An uncrawlable meta description for the image is created.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

![1](https://user-images.githubusercontent.com/16953982/221357911-5ff41ea6-1dc9-441b-8358-14e7e1e53caa.PNG)
![2](https://user-images.githubusercontent.com/16953982/221357912-1fec123f-6bbd-40d5-a10c-b57a77b574ab.PNG)

**Comment by bobmatyas** [comment]
Reported on https://wordpress.org/support/topic/issue-with-carrusel-and-google-insights
