### ISSUE TITLE
[Boost] Critical/Cloud CSS is not enabled after adding Boost via the `My Jetpack` page

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#29172]
### Impacted plugin

Boost

### Quick summary

Installing Jetpack Boost via `My Jetpack` does not activate Critical/Cloud CSS.

### Steps to reproduce

1. Install Jetpack and setup connection;
2. Make sure Jetpack Boost is not installed;
3. Go to `WP-Admin -> Jetpack -> My Jetpack` and add Boost;
4. Check Boost settings.

### A clear and concise description of what you expected to happen.

Installing and activating boost from anywhere (for the first time), should enable Critical CSS (or Cloud CSS if premium).

### What actually happened

Critical/Cloud CSS is not active after adding boost from `My Jetpack`.

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Self-hosted

**Comment by dilirity** [comment]
@thingalon gave the following suggestion:

> run a plugin activation hook which checks for a) a jetpack connection and b) if you already have cloud css, and turns it on if you do
> when you connect jetpack check again, and enable cloud css if you have the plan

**Comment by haqadn** [comment]
I wasn't able to reproduce it. Is there any consistent way to reproduce it?

**Comment by dilirity** [comment]
Can confirm, this is no longer a problem. Closing.
