### ISSUE TITLE
Newsletter Access level should not be showing with Stripe unconfigured

### ISSUE THREAD

**Issue by artpi** [Automattic/jetpack#29204]
We should **not** be showing the newsletter access level selector in posts if:

1. You don't have Stripe configured
2. You don't have any "Newsletter" plan configured

### Is the filter overriding the display of the newsletter panel?

NO, this is how it supposed to work. From here: https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php

```
function has_newsletter_plans() {
	return (
		/** This filter is documented in class.jetpack-gutenberg.php */
		apply_filters( 'jetpack_subscriptions_newsletter_feature_enabled', false )
		&& class_exists( 'Jetpack_Memberships' )
		&& Jetpack_Memberships::has_configured_plans_jetpack_recurring_payments( 'newsletter' )
	);
}
```

This is the opposite behaviour of https://github.com/Automattic/wp-calypso/issues/72656

**Comment by romarioraffington** [comment]
There are two checks to "enable" this feature, one on the [frontend](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/extensions/blocks/subscriptions/controls.js#L59) and one on [the backend](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php#L101). I'll improve the check on the backend and implement better checks for the frontend. On WPCOM we are overwriting this filter which causes the Newsletter Panel to be displayed on the frontend.

Currently, overriding the `jetpack_subscriptions_newsletter_feature_enabled ` filter will cause the frontend code to be loaded but the backend code may not load as there are additional checks on the backend.

**Comment by millerf** [comment]
> We should not be showing the newsletter access level selector in posts if:

Just curious, on a purely UX POV, wouldn't it be better to display the menu but show an error box explaining the issue? Otherwise users won't even know that there is such a feature...

**Comment by romarioraffington** [comment]
>Just curious, on a purely UX POV, wouldn't it be better to display the menu but show an error box explaining the issue? Otherwise users won't even know that there is such a feature...

This is the next step. In the future, we want to improve the UI that prompts the user to complete these tasks
