### ISSUE TITLE
Clean up CSS styles on wide range normalization

### ISSUE THREAD

**Issue by CGastrell** [Automattic/jetpack#29208]
`body` being something really weird to try and control from the module/package. We need to look for this kind of normalization and remove them

**Comment by sdixon194** [comment]
Is this issue still being tracked, or can we close it for the moment?

**Comment by CGastrell** [comment]
> Is this issue still being tracked, or can we close it for the moment?

It’s not being tracked ATM. Shall we circle back to Forms package I’ll deal try to come up with a more proper description/solution
