### ISSUE TITLE
Forms - datepicker block - if two blocks are on the same page, just one collects data

### ISSUE THREAD

**Issue by digitalwaveride** [Automattic/jetpack#29244]
Originally reported [here](pcsBup-V4-p2#comment-334).

> We had 2 date pickers and the 2nd one was not working. Even when having 2 different forms. This is because the field ID gets duplicated. We decided to change the filed title and this helped to enable the 2nd date picked. So it is not possible to have 2 date pickers on the same page with the same title as this will give them the same ID.

**Comment by anomiex** [comment]
Worked fine now with multiple date fields in a single form. With multiple forms containing date fields on a page the problem still exists.

**Comment by anomiex** [comment]
Looks like #30030 is the same bug, but has a bit more information. I'll close this as a duplicate in favor of that one.
