### ISSUE TITLE
Forms - Multiple Choice Block - inspector sidebar color settings - improve color descriptions

### ISSUE THREAD

**Issue by digitalwaveride** [Automattic/jetpack#29255]
Orignially reported [here](p8oabR-16e-p2#comment-7098).

For the multiple choice block:

> When adjusting styles in the sidebar, I expected “Label” to adjust the styles of the text next to each checkbox. I quickly discovered that “Input Field” is actually what I wanted. This probably makes sense for other types of form fields, but for a list of checkboxes, it’s a bit confusing since the styles apply to the checkbox labels, not the checkbox inputs themselves.

![Image](https://user-images.githubusercontent.com/5120357/222497484-437a384d-277a-4bfd-b37b-839053ada4e2.png)

We might want to keep the "Label text" to keep the consistency with other blocks, as visually it is the same element, but the "Field text" color could be renamed to something like: "Option text" - there is indeed no field.

**Comment by jcheringer** [comment]
Fixed by https://github.com/Automattic/jetpack/pull/30319
