### ISSUE TITLE
VideoPress: set video poster picking a video frame

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#29278]
Currently, It isn't possible to set the poster image by picking a video from the block editor once the video uploads.

Let's add a simple control in the Poster panel to tackle it.

![Image](https://user-images.githubusercontent.com/77539/222733814-b9c7a618-0492-418a-af91-2dcfd3f56457.png)

We use this implementation to continue paving the way for upcoming features like the hover effect.

**Comment by retrofox** [comment]
Tasks list:

- [x] https://github.com/Automattic/jetpack/pull/29358
- [x] https://github.com/Automattic/jetpack/pull/29368
- [x] https://github.com/Automattic/jetpack/pull/29398
- [x] https://github.com/Automattic/jetpack/pull/29439
- [x] https://github.com/Automattic/jetpack/pull/29449
- [x] https://github.com/Automattic/jetpack/pull/29454
- [ ] ...

**Comment by retrofox** [comment]
### `<TimestampControl />`

<img src="https://user-images.githubusercontent.com/77539/222741856-e70f4379-b474-4f4d-abb0-2617b93ac895.png" width="400px" />

#### Props

* showTimeControl
* ...

**Comment by retrofox** [comment]
@evilluendas I wonder if we should implement a `Hover Effect` panel instead of using the `Poster` panel. In some way, the feature can get tricky to find. 

The following video shows the Poster panel functionality so far.


https://user-images.githubusercontent.com/77539/227288412-723ca495-0b78-4ed5-af29-39dfc16058b1.mov

**Comment by evilluendas** [comment]
> I wonder if we should implement a Hover Effect panel instead of using the Poster panel. In some way, the feature can get tricky to find.

Hmmm I agree that it may be a bit hidden but on the other hand we shouldn't add too many panels, and this one feels secondary compared to other more important ones. 

What if we add it to the Poster (which I think conceptually makes sense, since the looping clip will replace the static poster on hover) for now, and see how folks use it? It'll be easier to eventually separate into its own panel than doing it the other way around.

**Comment by retrofox** [comment]
SGTM. Renaming the panel to `Poster / Hover Effect` or something like that could work?

**Comment by evilluendas** [comment]
I think "hover effect" isn't very descriptive, but maybe it could be something like `Poster and preview`?
