### ISSUE TITLE
Duplicate Custom CSS in WP 6.2 Beta

### ISSUE THREAD

**Issue by julsyd** [Automattic/jetpack#29285]
### Impacted plugin

Jetpack

### Quick summary

Custom CSS added through Jetpack is inserted twice in the source code.

### Steps to reproduce

1. Install any of the WP 6.2 Betas.
2. From WP Admin, go to Appearance > Additional CSS and add any custom CSS.
3. Publish the CSS changes and view the site's source code.

### A clear and concise description of what you expected to happen.

I expected the custom CSS to only appear once in the source code.

### What actually happened

The custom CSS appears twice in the source code.

<img width="493" alt="Screenshot 2023-03-03 at 09 58 38" src="https://user-images.githubusercontent.com/29981758/222753245-e42011d8-9ec2-4ca0-a409-01bf5d01798b.png">

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by jeherve** [comment]
I can't seem to reproduce on my end, and I don't see it on your site anymore; did you make any changes to fix things on your end?

********

Primary issue: #27795

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
