### ISSUE TITLE
Photon: allow customizing the img tag with get_image_tag

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2929]
Filters like `get_image_tag` allow you to customize the markup of the images attached to a post:
https://developer.wordpress.org/reference/hooks/get_image_tag/

Unfortunately, such customizations won't work when you use Photon since it modifies the image tag:
https://github.com/Automattic/jetpack/blob/3.7.2/class.photon.php#L329

It'd be nice if we could apply this filter after the image tag was modified, so people can continue to customize the image markup to add specific attributes, like mentioned on the thread where this was suggested:
https://wordpress.org/support/topic/the-filter-hook-for-img-tag-doesnt-work-by-using-the-photon?replies=1&view=all

**Comment by elliott-stocks** [comment]
Is the plan here to include all the parameters on the `get_image_tag` filter? Some aren't directly accessible without additional lookups.

Basic -

`$content = apply_filters( 'get_image_tag', $content );`

All parameters -

```
$attachment_title = get_the_title( $attachment_id );
$alt_text = get_post_meta( $attachment_id, '_wp_attachment_image_alt', true );
if ( empty( $alt_text ) ) {
    $alt_text = $attachment_title;
}
$content = apply_filters( 'get_image_tag', $content, $attachment_id, $alt_text, $attachment_title, 'align', $size );
```

Alignment doesn't seem available unless we use a regex to strip it from the HTML (within `class`).

Thoughts?

**Comment by jeherve** [comment]
Very good remark! We would indeed need to some extra work to get some of that data.

@ethitter What's your take on this?

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
