### ISSUE TITLE
Feature Request: Add custom links to Slideshow Block

### ISSUE THREAD

**Issue by matthaiosalves** [Automattic/jetpack#29305]
### Impacted plugin

Jetpack

### What

A possible solution for the lack of field to insert URL in slides using ACF

### How

You will pass a custom class in the Slide field, and you will create a custom field to receive the URL. Afterwards, it will go to the functions.php file, and insert this code below. Change the name to your preferred class and field name. The javascript will create a list and insert an onclick on the slides with the URL.

`function slideLink_func(){
  $html = '';

  $url = get_field('link_slide_home');

  $html .= '<script>';
    $html .= 'const arrayImage = [];';
    foreach($url as $item) {
      $html .= 'arrayImage.push("'.$item['url'].'");';
    }
  $html .= '</script>';

  $html .= '
  <script>
    !(() => {
      //ADICIONA LINKS PARA AS IMAGENS DO JET
      const query = ".slideHome .wp-block-jetpack-slideshow_slide figure";
      const images = document.querySelectorAll(query);
      
      for(let i = 0; i < images.length; i++) {
        images[i].addEventListener("click", () => goToLink(i));
      }
      
      function goToLink(i) {
        window.location.replace(arrayImage[i]);
      }
    })();
  </script>
  ';
  
  return $html;
}
add_shortcode( 'LinkSlideHome', 'slideLink_func' ); `

**Comment by jeherve** [comment]
Thanks for the contribution. I'll close this issue and refer to it in the original issue, at #13760.
