### ISSUE TITLE
AI paragraph box before submitting

### ISSUE THREAD

**Issue by artpi** [Automattic/jetpack#29310]
We need the AI paragraph to provide the box to tweak the prompt before submitting, instead of submitting right away.

Some inspiration:
p81Rsd-1di-p2

**Comment by millerf** [comment]
Still blocked by https://github.com/Automattic/jetpack/issues/29311

**Comment by millerf** [comment]
Actually not blocked, my bad.

**Comment by artpi** [comment]
Jetpack took this over
