### ISSUE TITLE
Sign up to leave a comment and you're taken to the Reader

### ISSUE THREAD

**Issue by davemart-in** [Automattic/jetpack#29321]
## Description

If you're logged out and you go to leave a comment on a JP or WP.com site you're given a couple of options for authentication. If you choose to create a WP.com account, you're taken through the account creation flow which bypasses the site design steps. Once you've signed up though, you're taken to the reader and something seems to be broken with the code which used to communicate between frames, as now you have to manually refresh the original page with the comment form before it recognizes that you're logged in.

### Expected

- Signup modal should close once you've created an account
- Original tab should authenticate without you needing to refresh the page

### Actual

- Signup modal stays open (taking you to the Reader)
- You have to manually refresh the original screen to show that you're logged in

### Preview

https://user-images.githubusercontent.com/5634774/223220916-f21f17eb-4f32-4df7-9c12-332ce2dfdc3d.mp4

**Comment by eoigal** [comment]
This should be fixed with https://github.com/Automattic/wp-calypso/pull/74205 merged
