### ISSUE TITLE
[Super Cache] Incorrect URL for preload notifications in subdir

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#29328]
When running WordPress out of a subdirectory (e.g.: `http://example.com/foo`), the preload UI is broken. It attempts to load status updates from a URL with the subdirectory duplicated (e.g.: `https://example.com/foo/foo`).

At first glance, it looks like the [code to determine the right path to fetch preload updates](https://github.com/Automattic/jetpack/blob/84eed88a5a70e625209363407f9ebf6a92d19857/projects/plugins/super-cache/inc/preload-notification.php#L11) is using `DOCUMENT_ROOT` and `$cache_path` in a way that makes assumptions about their paths.

It may be better to load preload notifications via a wp-ajax call instead of fetching the `txt` file directly.

**Comment by donnchawp** [comment]
We can close this because the preload notification is done by a wp-admin AJAX request now.
