### ISSUE TITLE
wp-admin: Jetpack icon is incorrect on the sidebar

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#29367]
I just noticed that the Jetpack graphic logo icon on the wp-admin sidebar is incorrect. Notice how the triangles are farther apart in the current graphic, different from the correct logo. 

For reference, I'm seeing this issue on a Jurassic Ninja site.

Please see attached comparison:
![Image](https://user-images.githubusercontent.com/25157638/223265227-3460cd5e-f5b7-41aa-9a4f-e6f94ab7d6c0.png)

Attached is the SVG of the correct Jetpack logo graphic.

![Image](https://user-images.githubusercontent.com/25157638/223265516-d2aba4cf-777e-412d-bec5-7773c741291a.svg)

Below are the screenshot for the 3 states of which the logo appears on wp-admin:
Inactive / Hover / Active

![Image](https://user-images.githubusercontent.com/25157638/223265756-4b11603d-3a54-4909-91c1-59c214cf8271.png)
![Image](https://user-images.githubusercontent.com/25157638/223265757-c73e17c9-1372-45f8-9a26-9517d6a8c49a.png)
![Image](https://user-images.githubusercontent.com/25157638/223265755-136177c6-7396-4635-8c6b-8dc60dbcd5e4.png)

Let me know if you have any questions. Thanks so much.

**Comment by jeherve** [comment]
That's a good catch, thanks @ballio2000.

That specific icon comes from an icon font that was last updated in https://github.com/Automattic/jetpack/pull/8305

@dereksmart Do you remember how you had updated the font back then? Is there a ressource somewhere where we can import an SVG and generate a new set of font files, like in https://github.com/Automattic/social-logos ?

I think another (better?) option would be to start using an SVG file in there instead of an icon font. The font name is "jetpack icons", but as far as I can tell it's only used for the one Jetpack icon in the menu bar.

Maybe getting rid of it would be a better way; I see that `add_menu_page` now allows you to pass a base64-encoded SVG for the `$icon_url` value, maybe we should go with that?

**Comment by dereksmart** [comment]
Oof no memory at all of that, sorry. I agree about it being a better idea to use the same SVG asset in all places logo. What's up with the [jetpack-logo](https://github.com/Automattic/jetpack/tree/trunk/projects/js-packages/components/components/jetpack-logo) JS package? I guess we can't use that in the admin menu since it's a React component?
