### ISSUE TITLE
Broken redirect for existing customers

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#29376]
### Impacted plugin

Search

### Quick summary

While a site which previously had search premium disconnects jetpack and tries to start again, it correctly prevents them from buying and tries to redirect them to the search dashboard. However, the redirect URL is incorrect.

### Steps to reproduce

1. Install only search and get the paid plan
2. Go to My Jetpack and disconnect jetpack
3. Go back to search, it should show the pricing table again
4. On the pricing table, choose premium agian
5. It should take you to authentication, so authenticate Jetpack to establish a user connection
6. You are redirected back to a 404 page

### A clear and concise description of what you expected to happen.

I was expecting to see the search dashboard or the just upgraded screen. Possibly to a URL like `https://example.com/wp-admin/admin.php?page=jetpack-search&just_upgraded=1`

### What actually happened

I see a 404 page with the following type of URL: `https://example.com/wp-admin/https:/example.com/wp-admin/admin.php?page=jetpack-search&just_upgraded=1`

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

Video demo 
https://user-images.githubusercontent.com/3737780/223916881-129a6b7c-2916-403e-946f-0adc8b72b4c7.mp4

**Comment by jeherve** [comment]
@Automattic/red Is that something you could look at? You're probably the most familiar with this flow, and I think it'd be important to get that fixed.

Thank you!

**Comment by kangzj** [comment]
Hi @jeherve I'll take a look today. I filed a similar issue a while ago: https://github.com/Automattic/jetpack/issues/27892 which seems to have to same cause.
