### ISSUE TITLE
Custom CSS: Browser find doesn't work for long stylesheets

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#2940]
For stylesheets that require scrolling, anything past the "fold" is not searched when using the find feature in your respective browser. Find does work for any text above the fold, however.

2396865-t

**Comment by samhotchkiss** [comment]
Addressing this would require a major overhaul in the way that Custom CSS works, and isn't on our roadmap at this time.

I would recommend that, if a user has a highly complex stylesheet, that they store it in their theme instead of using Custom CSS
