### ISSUE TITLE
max-width style crops sharing buttons

### ISSUE THREAD

**Issue by galbaras** [Automattic/jetpack#29408]
### Impacted plugin

Jetpack

### Quick summary

The following style causes sharing buttons to appear cropped:

```
.sd-social-icon .sd-content ul li[class*='share-'] a, .sd-social-icon .sd-content ul li[class*='share-'] a:hover, .sd-social-icon .sd-content ul li[class*='share-'] div.option a {
    max-width: 32px;
}
```

Since the height of these elements is set to 46px, the max-width should be the same, although it seems unnecessary, because unsetting it looks just as good.

This is related to changes in v11.9, likely those aimed at fixing the display of sharing buttons.

### Steps to reproduce

1. Choose some sharing options
2. Select "Icon Only"
3. View a page on the front end

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

The available workaround is to override the max-width styling, which some people can do, but many can't (on their own).

**Comment by jeherve** [comment]
Thanks for the report! The changes are indeed related to the recent changes we've made to the sharing button's design. This specific max-width changes was made in #28961.

Could you post a link to a site where you see some layout issues, and let me know what browser you use? I'm asking because I do not see any layout issues on my end on my own sites.

Thank you

**Comment by galbaras** [comment]
I use Chrome, and a sample page you can look at is https://www.behappyinlife.com/.

Since I've already fixed this, you can see it by disabling the following override style:

```
.sd-social-icon .sd-content ul li[class*='share-'] a, .sd-social-icon .sd-content ul li[class*='share-'] a:hover, .sd-social-icon .sd-content ul li[class*='share-'] div.option a {
    max-width: revert;
}
```

The change will be visible both in the floater bar and in the icons at the bottom of the content section.

**Comment by anomiex** [comment]
You appear to be using a plugin named "Get Business Online Customisations" that [is overriding Jetpack's styles for the sharing buttons](https://www.behappyinlife.com/wp-content/plugins/gbol-custom/gbol-jetpack.css?ver=6.1.1). That plugin apparently needs an update to account for the style changes in Jetpack 11.9.

In the mean time, it appears you've found a workaround for your plugin incompatibility, I'm going to close this.

**Comment by galbaras** [comment]
What the hell? My plugin is doing the overriding, which makes it look correct, and if you disable all of my styling (plugin and themes), you'll still see that the icons are squished. It's not what's causing the problem.

You can get a better view by visiting https://www.behappyinlife.com/?nocache, which disabled caching and minifying, so you can see where styles are coming from.

@jeherve Please reopen and continue to fix.

**Comment by anomiex** [comment]
I see now that what I had thought was a 'workaround' has actually been added to the plugin. Even better in that case.

> and if you disable all of my styling (plugin and themes), you'll still see that the icons are squished. It's not what's causing the problem.

If I disable **all** the style rules that are being provided by your plugin file at https://www.behappyinlife.com/wp-content/plugins/gbol-custom/gbol-jetpack.css?ver=6.1.1, I see this:

![Screenshot](https://user-images.githubusercontent.com/1030580/224505436-c529f060-2295-4fbe-a788-45db26135b3d.png)

The smaller round buttons are how the sharing buttons are intended to display in Jetpack. I see [a stylesheet from your theme "Beautiful Pro"](https://www.behappyinlife.com/wp-content/themes/beautiful-pro/style.css?ver=6.1.1) is removing the spacing Jetpack would have in between the buttons though.

> Since the height of these elements is set to 46px

That is incorrect.  In Jetpack [the font size of 18px](https://github.com/Automattic/jetpack-production/blob/11.9/modules/sharedaddy/sharing.css#L181) and [padding of 7px](https://github.com/Automattic/jetpack-production/blob/11.9/modules/sharedaddy/sharing.css#L568) combine to give a total height of 32px.

Your plugin's styles override the line height and font size to 32px (on lines 14 an 17 in the current version) to give the total height of 46px. Overriding the max-width in your plugin to match your other overrides is the correct thing to do.

**Comment by galbaras** [comment]
Oddly, that's not what I saw, but maybe I missed something. So this styling is consistent within itself, and using an override is appropriate. All good. Thanks for looking into it.
