### ISSUE TITLE
Extend contact forms for use with Campaign Monitor

### ISSUE THREAD

**Issue by marbetschar** [Automattic/jetpack#2941]
I'm trying to extend the contact forms of Jetpack to use together with Campaign Monitor; an e-mail marketing solution.

This should allow users filling out a contact form to additionally check a "Opt in to Newsletter" checkbox.

![cm](https://cloud.githubusercontent.com/assets/392542/10866442/062b7fb8-802f-11e5-8d93-0e1911649d5d.png)

But I'm stuck now; since I have no idea how to proceed best because it seems I have no chance to extend the `Grunion_Contact_Form_Field` classes by using an additional plugin :(

I'd like to keep Jetpack updateable, that's why I've started working on a plugin which should behave as an optional addon to Jetpack.

What's exactly missing is the following:
- Ability to set a checkbox's value
- Ability to add hidden form fields in the form builder
- Ability to add custom attributes to form fields
- Ability to hook into form field rendering
- Ability to hook into form processing after submit

Any Idea on how to proceed best?

**Comment by jeherve** [comment]
While this is not something that's possible with the current interface, the new interface built using editor views should make it easier to extend the form interface.

I'll close this in favour of #642, where the new interface will be introduced.
