### ISSUE TITLE
Shortcode & Mobile Theme: Recipe: wp_title deprecated

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2942]
`wp_title()` is deprecated as of 4.4. ( https://core.trac.wordpress.org/changeset/35294 ). 

Ref: https://make.wordpress.org/core/2014/10/29/title-tags-in-4-1/
https://make.wordpress.org/core/2015/10/20/document-title-in-4-4/
- [ ] [Recipe Shortcode](https://github.com/Automattic/jetpack/blob/8a30daea4c9caea855c24b0ea7e9758d35e01e32/modules/shortcodes/recipe.php#L52)
- [ ] [Mobile Theme: Header](https://github.com/Automattic/jetpack/blob/b5fd4cfc5dff8f59cc60b0fa8a2c8dc0edde6739/modules/minileven/theme/pub/minileven/header.php#L14)

**Comment by dereksmart** [comment]
`wp_title()` has been <a href="https://core.trac.wordpress.org/changeset/35624">reinstated</a>, so let's hold off on doing anything for now.

**Comment by jeherve** [comment]
Closing this since there was no movement on `wp_title()` deprecation. Will reopen if necessary.
