### ISSUE TITLE
Sharing: button markup displayed in ActivityPub requests

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#29435]
### Steps to reproduce

1. On a site that's connected to WordPress.com, go to Jetpack > Settings > Sharing and enable the sharing buttons
2. Go to Plugins > Add New, install and activate the ActivityPub plugin
3. View one of your posts on the frontend, and add `/activitypub` to the end of the post URL.
4. You should see a JSON response, with different fields needed for ActivityPub. 2 of those fields are important for us here: `content` and `contentMap`.
5. You will see the markup from the sharing buttons in those fields.

Related issue: #7361

**Comment by jeherve** [comment]
Here are some pointers, for reference:

Jetpack handles the display of sharing buttons via the `sharing_display` function:
https://github.com/Automattic/jetpack/blob/c784a426963b08d9d34d9951157f03ab0e0503bf/projects/plugins/jetpack/modules/sharedaddy/sharing-service.php#L939-L947
This function is then hooked into `the_content` and `the_excerpt`:
https://github.com/Automattic/jetpack/blob/c784a426963b08d9d34d9951157f03ab0e0503bf/projects/plugins/jetpack/modules/sharedaddy/sharing-service.php#L42-L51
We have a number of checks inside `sharing_display` to ensure that the markup isn't added in specific contexts (AJAX requests, REST requests, on admin, preview, or feed pages...).

On the other side, the ActivityPub plugin builds the JSON object to return on ActivityPub requests here:
https://github.com/pfefferle/wordpress-activitypub/blob/2274bd007493bc4cbc39dcac91c28be9bd8c7d3d/includes/class-shortcodes.php#L192-L201

In #7361, @pfefferle mentioned:

> ActivityPub has a massive use of Content Negotiation... Every Page, Post and the Author URL might be queried with a different Accept Header (`application/activity+json`) what about deactivating the sharing buttons also for mime-types other than `text/html`, or at least disable it for JSON requests (`wp_is_json_request`)?

@pfefferle Considering the above, adding an extra `wp_is_json_request()` check will not help here I'm afraid.

I see that the plugin started filtering `the_content` very early on, in version 0.1.0:
https://github.com/pfefferle/wordpress-activitypub/commit/4e653f5f75d62062cae1bef334cd0bcb590b324a#diff-28c56747da3496a58aa702e51b60e1b36656e0263c4c2d97d0a013a6d2f07a08R34

Do you recall why you added that filter in the first place? Since you filter the content, it is expected that contents from other plugins (such as Jetpack) that hook into `the_content` will be displayed there.

I also tried working around the JSON mime-type, as you suggested, like so:

```diff
diff --git a/projects/plugins/jetpack/modules/sharedaddy/sharing-service.php b/projects/plugins/jetpack/modules/sharedaddy/sharing-service.php
index 6c8fdb9b30..6ea9a2b07d 100644
--- a/projects/plugins/jetpack/modules/sharedaddy/sharing-service.php
+++ b/projects/plugins/jetpack/modules/sharedaddy/sharing-service.php
@@ -964,6 +964,17 @@ function sharing_display( $text = '', $echo = false ) {
 		return $text;
 	}
 
+	/*
+	 * Do not output sharing buttons on requests for other types of JSON requests
+	 * e.g. ActivityPub requests.
+	 */
+	if (
+		! empty( $_SERVER['HTTP_ACCEPT'] )
+		&& false !== stripos( filter_var( wp_unslash( $_SERVER['HTTP_ACCEPT'] ) ), 'json' )
+	) {
+		return $text;
+	}
+
 	// Don't output flair on excerpts.
 	if ( in_array( 'get_the_excerpt', (array) $wp_current_filter, true ) ) {
 		return $text;
```

That didn't work, though, because the ActivityPub request is not a JSON request, it's a regular text/html request it would seem:

```
text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
```

**Comment by pfefferle** [comment]
Hey @jeherve thanks for trying to fix this issues!

The `/activitypub` is only for debugging, most of the users can not run requests with specific `Accept` headers and so I had an easy way to let them debug stuff. ActivityPub uses content negotiation instead:

```
## Request
curl "https://notiz.blog/2023/01/31/2022/" \
     -H 'Accept: application/activity+json'
```

So that's why I thought this might be an option to deactivate the sharing button.

I have added a possibility to disable filters for the content (and add only the relevant, to remove the html-comments used by the block editor for ecample) but I am not sure if users understand that: https://github.com/pfefferle/wordpress-activitypub/blob/master/includes/class-shortcodes.php#L200
