### ISSUE TITLE
VideoPress: audit block data when replacing video

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#29464]
It's possible to replace the video of a block instance. When it happens, we must check which data should be preserved, flushed, or updated:

<img src="https://user-images.githubusercontent.com/77539/225108765-cf811fee-0bb6-4ef7-9de0-8f0c990e2eec.png" width="600px" />

For instance, video tracks should be updated.

**Comment by dhasilva** [comment]
p1678817554894169-slack-C03TA48NSUX

After some deliberation with the team, we concluded that block instance specific data should be copied, but video data (like description, rating, etc) should be reset.

That said, the description is reset, but the chapter file, though not shown in the video, is still listed.
