### ISSUE TITLE
VideoPress: add an upgrade to get an extra TB of space

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#29473]
Related to:
pe4Cmx-QY-p2
1199562518309922-as-1203929225197066

**Comment by sdixon194** [comment]
Looks like this isn't on the roadmap for now, and the solution was to allow HEs to tack on upgrades as needed for people above 1TB of data. I'll close this for now but we can re-open if this is something we'd want to look into again in the future.
