### ISSUE TITLE
VideoPress: store the at_time value when generating poster image

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#29485]
Currently, it isn't possible to know the timestamp of the video poster when it has been selected by picking a video frame.
We could try to address it by:
* storing a `thumbnail_at_time` option in the same way that it stores the `thumbnail_generating` option, for instance.
* exposing the `thumbnail_at_time` in the public `v1.1/videos/<guid>` endpoint response body.

**Comment by dhasilva** [comment]
p1678904653945089-slack-C9W0QF6KA

**Comment by retrofox** [comment]
Let's close this one for now. It isn't a mandatory requirement.
