### ISSUE TITLE
Typo in wp-plugins-jetpack-dev-readme.pot

### ISSUE THREAD

**Issue by ujdhesa** [Automattic/jetpack#2949]
Hello,

Here you are:
msgid "Bug Fix: Shortcodes: Fixed Facebook embeds by placing the scipt in the footer"

It should be:
msgid "Bug Fix: Shortcodes: Fixed Facebook embeds by placing the script in the footer"

**Comment by dereksmart** [comment]
thanks, fixed in 133b2ea653742a7df14f5de92be163eed4bdcfe2
