### ISSUE TITLE
Open Graph: Stop using Flash for og:video

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#2950]
Right now, we have Flash hardcoded: https://github.com/Automattic/jetpack/blob/8a30daea4c9caea855c24b0ea7e9758d35e01e32/modules/publicize/enhanced-open-graph.php#L89

Per Otto, FB accepts mp4, which we should try to use, at least for VideoPress.

Would fix: https://meta.trac.wordpress.org/ticket/1375

**Comment by kraftbj** [comment]
Relevant code from media-summary: https://github.com/Automattic/jetpack/blob/b5fd4cfc5dff8f59cc60b0fa8a2c8dc0edde6739/class.media-summary.php#L60

**Comment by Otto42** [comment]
Actually, per *Facebook*, they accept MP4. I guarantee nothing, and tend to be cynical about their documentation. :)

https://developers.facebook.com/docs/sharing/webmasters#media

**Comment by kraftbj** [comment]
@Otto42 Yup, sorry. I meant more that you said FB said that and I hadn't clicked-thru to read it myself. #lazyweb May the record reflect MP4 *might* be an option and even if it works, it might not. :)

**Comment by zinigor** [comment]
Moving this to 3.9 since the corresponding PR was moved there.
