### ISSUE TITLE
Upgrade from wp-admin [core plugin]: Fix scroll position when upgrading from the dashboard

### ISSUE THREAD

**Issue by grbicsanja** [Automattic/jetpack#29500]
**Fix scroll position when upgrading from the dashboard**

When user clicks on the CTA, the upgrade page is scrolled down (assuming it’s keeping the scroll position from the dashboard).

https://wp.me/p1HpG7-l2l
See task 1

**Comment by anomiex** [comment]
Cannot reproduce. Clicking the link as shown in the video now leads to a My Jetpack page that is scrolled to the top.
