### ISSUE TITLE
Upgrade from wp-admin [core plugin]: My Jetpack - Purchased Backup, Scan, Search, or VideoPress are not reflected in the product cards

### ISSUE THREAD

**Issue by grbicsanja** [Automattic/jetpack#29503]
**My Jetpack: Purchased Backup, Scan, Search, or VideoPress are not reflected in the product cards**

Regardless if the upgrade was performed from the dashboard or My Jetpack, the cards show the ‘add x product’ button, which takes the user to purchase again. However, the purchase is reflected on the My Jetpack page in the list of plans, as well as on the dashboard.

p1HpG7-l2l-p2
**See task 3**

**Comment by anomiex** [comment]
Could not reproduce. It seems this has probably been fixed at some point.
