### ISSUE TITLE
Upgrade flow from My Jetpack [VP Backup stand-alone]: Incorrect product status after purchase

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#29522]
After purchasing VaultPress Backup via My Jetpack, the VP Backup card doesn't reflect the purchase status. It shows a primary CTA saying "Purchase" as well as "inactive"

Flow details + video can be found at task 18: p1HpG7-l2l-p2

![Image](https://user-images.githubusercontent.com/214813/225756286-fcf7ab32-7dc5-4f67-a98b-ac2ade3896ae.png)

* Tested on WPEngine
* User and site already connected
* VP Backup Stand-alone installed. Core present

**Comment by jeherve** [comment]
Is this the same issue as #29503?

**Comment by grbicsanja** [comment]
@jeherve, it's the same type of issue except that #29503 happens within the core plugin, while this one refers to the stand-alone VP Backup. 

@jeffgolenski can you mark which plugin it is in the titles, just like we do for core? 
ie. "Upgrade from wp-admin **[core plugin]**: My Jetpack - Purchased Backup, Scan, Search, or VideoPress are not reflected in the product cards"

**Comment by anomiex** [comment]
It seems like this has been fixed at some point, I could not reproduce following the instructions using Jurassic Ninja. Nor could I reproduce by installing only the Backup plugin without Jetpack-the-plugin.
