### ISSUE TITLE
Readme: update contributor list to only include valid WordPress.org usernames

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2952]
In 61dca3f316cc36736d6679c609c20cc644004fbc, we updated the list of contributors to include more names, but some of these are not valid WordPress.org usernames. A good example is `jasmussen`, when  `Joen` is in fact the valid WordPress.org username.

@zinigor Do you happen to remember how you generated that list? From GitHub usernames?

**Comment by zinigor** [comment]
@jeherve yes, those were github usernames, want me to fix those?
