### ISSUE TITLE
Boost upgrade flow from My Jetpack [stand-alone and core]: Update My Jetpack interstitial with the pricing table design

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#29537]
When adding Boost from My Jetpack, there's an older redundant screen that asks the customer to add jetpack boost, after which they are taken to the pricing table view. 
![Image](https://user-images.githubusercontent.com/214813/225959526-bfd59c88-883f-494f-a0f3-6813a383816f.png)

Instead, let's have all the upgrade links to point to the MyJetpack interstitial:
`/wp-admin/admin.php?page=my-jetpack#/add-boost`

And let's update the interstitial design to show the pricing table:
![Boost_myjetpack_interstitial](https://user-images.githubusercontent.com/90194580/226687011-75b2271b-264d-42b2-ba7d-18cb7e6009d4.png)

Flow visuals and video walkthrough at task 35: p1HpG7-l2l-p2

**Comment by thingalon** [comment]
Un-assigning myself to make it clear others on the the HoG team can pick this up :)

**Comment by nateweller** [comment]
PR here: https://github.com/Automattic/jetpack/pull/29931
