### ISSUE TITLE
Upgrade flow from My Jetpack [VP Backup stand-alone]: After purchase, VP Backup throws an error

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#29531]
After purchasing VP Backup via My Jetpack, I'm immediately brought to the stand-alone UI where I see an error. VP Backup can't backup my site. An email is sent that reports the same, yet cloud.jetpack.com reports the first backup is in progress.

Flow visuals + video walkthrough: see task 19 on p1HpG7-l2l-p2

![Image](https://user-images.githubusercontent.com/214813/225933984-162ab5e8-2f21-4f03-9b24-063c4dc537ed.png)

* Tested on WPEngine
* VP Backup Stand-alone installed. Jetpack Core presently installed
* Users and site already connected

**Comment by jwebbdev** [comment]
@Initsogar - I think this can likely be closed.  We identified this as an actual issue backing up (related to the hosting configuration), not an issue triggered by the upgrade flow.
