### ISSUE TITLE
Backup upgrade flow [Core and stand-alone]: All flows should point to My Jetpack Backup upgrade screen

### ISSUE THREAD

**Issue by grbicsanja** [Automattic/jetpack#29538]
**All Backup upgrade flows (coming from My Jetpack, Dashboard, Settings, and JITMs) should point to the same URL:**
`/wp-admin/admin.php?page=my-jetpack#/add-backup`

Currently, we have several interstitials (upgrade screens) and not all of them are up to date. To align them and make updating them easier, let's have every upgrade button lead to this URL.

**Small visual fixes required:**

Change the gray background on this page to F9F9F6 (currently, it's F0F0F1 I think)
Keep the primary CTA button padding the same as the secondary (right now the button stretches full width and it shouldn't)

This is what the screen should look like:

![backup](https://user-images.githubusercontent.com/90194580/226404631-632fbe9b-dc41-4375-983f-a2a5af238638.png)

p1HpG7-l2l-p2
See task 4

**Comment by grbicsanja** [comment]
Edit: I added plugin installs to the list of places where the upgrade could come from.

**Comment by grbicsanja** [comment]
Let's also:

- Change the gray background on this page to F9F9F6 (currently, it's F0F0F1 I think)
- Keep the primary CTA button padding the same as the secondary (right now the button stretches full width and it shouldn't)

**Comment by oskosk** [comment]
This was partially implemented by https://github.com/Automattic/jetpack/pull/29138 (The bit about upgrading Jetpack's purchase flow for Backup to point to My Jetpack

**Comment by grbicsanja** [comment]
We removed the portion of the task about the plugin page. So this is only about all the upgrade flows pointing to the one URL, no other changes needed.

**Comment by grbicsanja** [comment]
> We removed the portion of the task about the plugin page. So this is only about all the upgrade flows pointing to the one URL, no other changes needed.

Sorry, just edited again, there are two small visual fixes needed, please see the description and image. (button width and background color)

**Comment by Initsogar** [comment]
Thanks @grbicsanja! We will be taking a look today and will let you know any progress.

**Comment by oskosk** [comment]
> Keep the primary CTA button padding the same as the secondary (right now the button stretches full width and it shouldn't)

@grbicsanja note that both buttons are extending up to the full width of their container

**Comment by oskosk** [comment]
Background color was updated in #29568

**Comment by Initsogar** [comment]
Reviewing the different flows, the first 3 have been already addressed in #29138 (merged):
- [x] My Jetpack
- [x] Dashboard
- [x] Settings
- [ ] JITMs -> addressed in D105500-code (needs review)
- [ ] Plugin install -> @grbicsanja could you clarify me which is this flow?

**Comment by grbicsanja** [comment]
@Initsogar about the plugin install, I posted a comment on the P2 and tagged you :) 
p1HpG7-l2l-p2

**Comment by grbicsanja** [comment]
After a conversation with @Initsogar, we decided to remove the Plugin install use case from this issue.

**Comment by Initsogar** [comment]
The update on Jetpack JITMs related to backup are now in production (D105500-code).
All backup flows required are now fixed. There's still pending one visual fix regarding the CTA buttons on the interstitial site which is currently in progress in #29570.

---

- [x] Update upgrade flows pointing to My Jetpack Backup upgrade screen
  - [x] My Jetpack
  - [x] Dashboard
  - [x] Settings
  - [x] JITMs
  ~Plugin install~
- [ ] Small visual fixes
  - [x] Change the gray background on this page to F9F9F6
  - [ ] Keep the primary CTA button padding the same as the secondary
