### ISSUE TITLE
Upgrade flow from My Jetpack [Boost stand-alone]: Remove "go back" link after purchase

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#29539]
After a customer upgrades boost, there's a post-purchase confirmation screen within the plugin. On this page there's a "Go Back" link that should be removed. It doesn't work and doesn't need to be there—no sense in trying to take them back to the cart after they've paid us.

Flow visuals and video walkthrough at task 36 p1HpG7-l2l-p2

![Image](https://user-images.githubusercontent.com/214813/225962317-0339a9b6-2921-48ee-a0e9-edd3580f5904.png)

**Comment by thingalon** [comment]
Un-assigning myself to make it clear others on the the HoG team can pick this up :)
