### ISSUE TITLE
Upgrade flow from My Jetpack [Boost stand-alone]: Fix styling of checklist & button after purchase

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#29540]
Minor detail. The padding of the checklist after purchase is inconsistent with the rest of our checklists. 

- [ ] We just need to adjust the padding of `.jb-checklist li` on this screen to:

`padding-bottom: 2px;`
`padding-top: 6px;`

**Currently**

![Image](https://user-images.githubusercontent.com/214813/225965072-3f9ccf29-b84c-43a2-a85e-b72e8be6a235.png)

**Proposed**

![Image](https://user-images.githubusercontent.com/214813/225965100-2eea0075-7102-40a9-9c58-7e0c9b9321b2.png)

- [ ] The "Continue" button also has text that's smaller than other buttons. I think we need to bump the text size to 16px to match the others. The width of the button is fine though.

![Image](https://user-images.githubusercontent.com/214813/225974546-19122a8c-223d-4da4-9295-5411b78d11b8.png)

Flow visuals and video walkthrough at task 37 & 38 p1HpG7-l2l-p2

**Comment by thingalon** [comment]
Un-assigning myself to make it clear others on the the HoG team can pick this up :)
