### ISSUE TITLE
JITM: CTAs that open new tabs need external link icons

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#29552]
### What's happening?

Certain JITM CTAs open new tabs, those that do, should have an external link icon:

![Image](https://user-images.githubusercontent.com/7129409/220127557-6664e4a8-d1fd-41fb-acb5-b4f41970e652.png)

![Image](https://user-images.githubusercontent.com/7129409/220127604-f47d6498-b74e-4d94-9338-3edb08a96ca1.png)

**Comment by jeherve** [comment]
Related post, and design: p1HpG7-l9I-p2
