### ISSUE TITLE
Jetpack Plugin: Assistant 14-day text overlaps offer cards.

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#29551]
### What's happening?

Activate and connect Jetpack to a new site → In Dashboard Recommendations, click the CTA "View discounted products":

Text is behind the cards in a strange spot. Looks broken.

![Image](https://user-images.githubusercontent.com/7129409/220125191-4979f127-26fc-4dcd-8748-9c9469ac89a1.png)

**Comment by jkguidaven** [comment]
It looks like this has already been fixed in the latest build.

![Image](https://user-images.githubusercontent.com/56598660/232447620-0f4b22ad-4198-4053-99b1-3b8155c9655b.png)

**Comment by mattgawarecki** [comment]
@dereksmart Can you confirm you're seeing the same fix that @jkguidaven pointed out? Checking in case this issue can be closed.

**Comment by dereksmart** [comment]
Thanks! It should be obvious enough to spot if it were still there :) marking as resolved.
