### ISSUE TITLE
Scan upgrade flow [Stand-alone and Core]: All flows should point to My Jetpack Scan upgrade screen

### ISSUE THREAD

**Issue by grbicsanja** [Automattic/jetpack#29558]
**All Scan upgrade flows (coming from My Jetpack, Dashboard, Settings, and JITMs) should point to the same URL:**
`/wp-admin/admin.php?page=my-jetpack#/add-scan`

Currently, we have several interstitials (upgrade screens) and not all of them are up to date. To align them and make updating them easier, let's have every upgrade button lead to this URL.

Small visual fixes required:
- Change the gray background on this page to F9F9F6 (currently, it's F0F0F1 I think)
- Keep the primary CTA button padding the same as the secondary (right now the button stretches full width and it shouldn't)

This is what the screen should look like:

![scan_core](https://user-images.githubusercontent.com/90194580/226404058-a7bbd471-92dc-4ea8-9b79-d3c4f0a8b33e.png)

p1HpG7-l2l-p2
See task 7

**Comment by grbicsanja** [comment]
Let's also:
- Change the gray background on this page to F9F9F6 (currently, it's F0F0F1 I think)
- Keep the primary CTA button padding the same as the secondary (right now the button stretches full width and it shouldn't)

**Comment by oskosk** [comment]
This was implemented by https://github.com/Automattic/jetpack/pull/29138

**Comment by grbicsanja** [comment]
I added a note earlier about a small visual fix on this screen right before it got closed - the button width and the background color. The screenshot and description are updated. Reopening the issue for those two things!

It's hard to cover everything at this scale. I appreciate your patience :)

**Comment by oskosk** [comment]
Ah ok. Sorry then

**Comment by oskosk** [comment]
Background color was updated in #29568

**Comment by anomiex** [comment]
Looks like this was done and closed, then reopened for a color tweak, and then that was done and this was never re-closed? Re-closing.
