### ISSUE TITLE
All Plugins: Confusing error message when login session is expired

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#29553]
The following error message seems to show up when someone's login session is expired (i.e., `invalid_timestamp` from the API), but we really don't explain very well what's going on or why clicking the button we give them is a good idea:

> The timestamp is too old.
> **[[ Restore Connection ]]**

I think there's room here to give our customers a clearer path forward, but I don't know exactly what it is right now. Maybe someone else can pitch in with an idea?

![Image](https://user-images.githubusercontent.com/670067/224726746-6e6525be-5b34-4df6-8af2-a994de4d539d.png)

**Comment by Adibzadeh** [comment]
Maybe something like: "Session ended. Please log in to continue [using our service?]." would be more clear and helpful?.
I'm interested in working on this issue (new to GitHub contributions, so it seems a good start?! maybe) but only if no other person on the team who is more qualified and understand the system is available.

**Comment by anomiex** [comment]
This bug lacks reproduction instructions. Please add some so we can determine if this problem still exists.

**Comment by dereksmart** [comment]
I just now tested by forcing the error in code. It shows better messages now 

<img width="878" alt="image" src="https://github.com/Automattic/jetpack/assets/7129409/bad9ea12-7e02-4342-a04b-0b75d5178ebf">

<img width="890" alt="image" src="https://github.com/Automattic/jetpack/assets/7129409/adac7f74-91d8-4b48-9426-49b08d570d28">
