### ISSUE TITLE
Protect upgrade flow [Stand-alone and Core]: All flows should point to My Jetpack Protect upgrade screen

### ISSUE THREAD

**Issue by grbicsanja** [Automattic/jetpack#29562]
All Protect upgrade flows (coming from My Jetpack, plugin install, and JITMs) should point to the same URL:
`/wp-admin/admin.php?page=my-jetpack#/add-protect`

Currently, we have several interstitials (upgrade screens) and not all of them are up to date. To align and update them easier, let's have every upgrade button lead to this URL.

We must replace the old upgrade screen with the new, table view.

![protect](https://user-images.githubusercontent.com/90194580/226405807-c74442fc-b29d-4f5d-adb8-fbfef644eeb1.png)

p1HpG7-l2l-p2
See task 40

**Comment by singerb** [comment]
Curious about this - https://github.com/Automattic/jetpack/issues/29558 suggest we're aiming to use the screen type on the left, whereas this has us replacing that with the table type. Plus, this issue and that are intertwined as it's all the same upgrades (Scan or Security) whether it comes from Protect or elsewhere.

**Comment by grbicsanja** [comment]
> Curious about this - https://github.com/Automattic/jetpack/issues/29558 suggest we're aiming to use the screen type on the left, whereas this has us replacing that with the table type. Plus, this issue and that are intertwined as it's all the same upgrades (Scan or Security) whether it comes from Protect or elsewhere.

@singerb 
Because scan can't be used for free, everywhere we say 'Get scan', we take the users to the 'Scan or Security' type of screen. 👇
<img width="1151" alt="Screenshot 2023-03-20 at 16 47 30" src="https://user-images.githubusercontent.com/90194580/226393796-bd8a672e-7d04-48fd-a14b-8c6fb595d173.png">

Because Protect has both Free and paid tiers, everywhere we say 'Get Protect', we take the users to the 'Table view' type of screen. 👇
![Protect screen](https://user-images.githubusercontent.com/90194580/226394300-906d650e-e6c7-40de-a575-34bba7da653f.png)

I don't know why we show 'Get scan' or 'Get Protect' in some situations, and which of those cases are bugs or intentional. So for the sake of just focusing on making the flows consistent, the idea is to define what the upgrade screens for Scan and Protect look like, make sure they are on the myjetpack/upgrade URL, and create respective issues. 
You are right that these tasks are connected! Feel free to change them if something is incorrect (ie which plugin is affected) or should be better described. I'd appreciate your help in making them more clear!

**Comment by nateweller** [comment]
> I don't know why we show 'Get scan' or 'Get Protect' in some situations, and which of those cases are bugs or intentional. 

Provided some more info about the scan/protect situation here: https://github.com/Automattic/jetpack/issues/29591#issuecomment-1478966797

**Comment by simonktnga8c** [comment]
![image](https://user-images.githubusercontent.com/79907037/226954339-2170b495-9751-4447-939c-908b6836cb47.png)

I saw this copy when installing the Protect plugin earlier. I would add the following for the WAF feature:

Web Application Firewall (WAF) | Automatic protection and rule updates | Manual rules only

If we're not sure what to say for the CTA, considering they are adding Jetpack Scan, we could say "Upgrade Protect"

**Comment by nateweller** [comment]
> Web Application Firewall (WAF) | Automatic protection and rule updates | Manual rules only

I have [a PR](https://github.com/Automattic/jetpack/pull/29549) currently open for this, though I like your feature descriptions better than what we have 😅
