### ISSUE TITLE
Subscriptions: Embed the featured image, if there is one set for the post

### ISSUE THREAD

**Issue by rothschild86** [Automattic/jetpack#2957]
As the title says :)

**Comment by jeherve** [comment]
Thanks for the report.

I'm going to close this issue as duplicate, as it's something we'll need to implement on WordPress.com first, and we're tracking that issue internally in 4728-wpcom.

I'll comment again here as soon as we make progress on this!

**Comment by richardmtl** [comment]
requested in 2786911-t

**Comment by aheckler** [comment]
Requested in 2869606-t

**Comment by richardmtl** [comment]
Requested in 2921442-t

**Comment by danjjohnson** [comment]
Requested in 2907222-t

**Comment by richardmtl** [comment]
Requested in 3057832-t

**Comment by tmmbecker** [comment]
3151033-t

**Comment by richardmtl** [comment]
946367-zen

**Comment by richardmtl** [comment]
1539238-zen

**Comment by mzakariya** [comment]
1567772-zen

**Comment by enejb** [comment]
requested in 2548760-zen

**Comment by sarahfg** [comment]
Requested in 29549590-hc

**Comment by jeherve** [comment]
This has now been added.
