### ISSUE TITLE
Supercache: Preloading skips posts due to timeout

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#29575]
### Impacted plugin

Super Cache

### Quick summary

While preloading the cache, it takes posts in batches of 100. However, if there is a timeout and the process couldn't finish the whole batch, it skips the remaining items that didn't finish before the timeout.

### Steps to reproduce

1. On a site with a few hundred posts, rig it to timeout before the first batch can finish and a few posts of the batch remain uncached
2. The next batch would start after the first 100 posts and result in skipping some of the posts.

### A clear and concise description of what you expected to happen.

Preloading should continue from where it left off

### What actually happened

Preloading skips the posts that didn't finish before the timeout

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

A users report and analysis of this issue https://wordpress.org/support/topic/preload-mode-skips-caching-pages-or-deletes-already-cached-pages/

Check [`wp_cron_preload_cache()`](https://github.com/Automattic/jetpack/blob/49b143a4c4a58fd99da14cc8852fb7fb33650077/projects/plugins/super-cache/wp-cache.php#L3203) in **super-cache/wp-cache.php** for the responsible code.

**Comment by donnchawp** [comment]
Fixed this in #30450 by reducing the number of posts cached per loop to 10.
