### ISSUE TITLE
Akismet upgrade flow [core] - Visual and copy edits on upgrade screen

### ISSUE THREAD

**Issue by grbicsanja** [Automattic/jetpack#29584]
The Akismet upgrade screen coming from the Dashboard and Settings needs a few visual and copy adjustments:

We should:
- Change title to ‘Akismet Anti-Spam’
- Replace the cloud icon with the Vaultpress icon
- Add back button
- Add the link to add existing license 
- Hide dashboard header

See image:

![Image](https://user-images.githubusercontent.com/90194580/226641333-a9a6f49e-808f-4efe-ba72-7f1d24ed7790.png)

p1HpG7-l2l-p2 - see task 2

**Comment by jeherve** [comment]
Related: #29045 (and its matching PR #29046) which covers the icon.

**Comment by bluefuton** [comment]
The URL for this page is `/wp-admin/admin.php?page=jetpack#/product/akismet`.

I'll get a PR started.
