### ISSUE TITLE
Enhancement: Exclude featured images from Lazy Load in block themes

### ISSUE THREAD

**Issue by RavanH** [Automattic/jetpack#29585]
### Impacted plugin

Boost

### What

When image lazy loading is activated, the featured image in the Twenty Twenty-Three block theme will be lazy-loaded. This is not good for pagespeed.

### How

Wanting to exclude the featured image, displayed at the top of a single post in the Twenty Twenty-Three block theme from being lazy-loaded, I tried to give the featured image block the class `skip-lazy`. This does not have the desired effect. The class is set on the parent FIGURE element, not the IMG element itself and the image is still marked for lazy loading. Same goes for any regular image block, by the way...

To reproduce: install a clean WP 6.2-RC with some demo content with featured images, install Jetpack Boost (or Jetpack) and activate Lazy Image Loading. Open a post with a featured image in your browser, right-click featured image and choose Inspect. Notice the classes `attachment-post-thumbnail size-post-thumbnail wp-post-image jetpack-lazy-image jetpack-lazy-image--handled` indicating that it has been treated by Jetpack Lazy Image Loading.

To "fix" the issue in the Twenty Twenty-three theme, I added this little snippet as a custom plugin.

```
function my_customize_lazy_images( $blocked_classes ) {
    $blocked_classes[] = 'wp-post-image';
    return $blocked_classes;
}

add_filter( 'jetpack_lazy_images_blocked_classes', 'my_customize_lazy_images' );
```

This excludes all featured images from lazy-load. Better than before, but not ideal: also featured images inside a query loop will be excluded even if they are "below the fold".

So my request is actually two-fold:
1. Exclude featured images by default (ideally only the first 3 on each request, which would mean the top image on a single page or the top row in a query loop with three columns).
2. Exclude all child elements of an element with class `skip-lazy`, so that that class can be used on block level.

Thanks for considering :)

**Comment by dilirity** [comment]
Hey @RavanH and thank you for bringing this to our attention! We've added this to our backlog, but please note, that I can't give an estimate of when we'll be able to tackle this.

In the meantime, here's an updated snippet to disable lazy loading for the featured images on single post pages:
```php
function my_customize_lazy_images( $blocked_classes ) {
	if ( is_singular() ) {
		$blocked_classes[] = 'wp-post-image';
	}

	return $blocked_classes;
}

add_filter( 'jetpack_lazy_images_blocked_classes', 'my_customize_lazy_images' );
```

That should fix lazy loading being disabled on a query loop page. However, if the single post page has a custom query loop or a sidebar showing posts and their thumbnails, the snippet would disable lazy loading for those images as well.
