### ISSUE TITLE
Scan upgrade flow [core]: Land users on the recommendations Scan welcome page upon purchase from My Jetpack

### ISSUE THREAD

**Issue by grbicsanja** [Automattic/jetpack#29591]
When users purchase Scan from the Dashboard, we land them on the Scan welcome page inside the assistant. 
When users purchase from MyJetpack, they are brought back to jetpack after checkout.

Let’s have them land on the welcome page instead.

![Image](https://user-images.githubusercontent.com/90194580/226697317-02d16088-a310-401d-9739-fdf8759c4d3c.png)

p1HpG7-l2l-p2
See task 8

**Comment by jeherve** [comment]
I may be missing something, but shouldn't we be installing the Protect plugin here?

**Comment by grbicsanja** [comment]
>I may be missing something, but shouldn't we be installing the Protect plugin here?

@jeherve I'm not sure why Scan is in there, and if it should be or not, we discussed it [here](https://github.com/Automattic/jetpack/issues/29562#issuecomment-1476496779).

**Comment by nateweller** [comment]
Currently, the My Jetpack product grid will show either "Scan" or "Protect". 
* If the user has any standalone plugin already installed on their site, we promote installing the Jetpack Protect standalone plugin.
* If the user only has the Jetpack plugin installed, we promote the Scan upgrade.

This behavior was introduced when we first added the Scan feature to the Protect plugin, prior to this we have always had the Scan card in the product grid. 

For reference: 1201069996155224-as-1203332781722597 and p1HpG7-gFg-p2#comment-55496

If we intend to keep that behavior around, then for this issue we could look into ensuring that users who follow the upgrade from the "Scan" card end up on the welcome page, and users who use the "Protect" card install the plugin and end up on the free/paid screen. :+1:

**Comment by singerb** [comment]
> then for this issue we could look into ensuring that users who follow the upgrade from the "Scan" card end up on the welcome page, and users who use the "Protect" card install the plugin and end up on the free/paid screen. 👍

Sounds good.
