### ISSUE TITLE
TidyCSS: Add support for animation-fill-mode

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#296]
animation-fill-mode is an experimental CSS rule that is currently stripped out by TidyCSS upon save of Custom CSS.

Reported upstream to Team Custom via 6416-wpcom .
Requested in 1772518-t

**Comment by jeherve** [comment]
This was fixed on WordPress.com in r138366-wpcom. The changes now need to be ported to Jetpack.

**Comment by jeherve** [comment]
Fixed in #7166
