### ISSUE TITLE
[Earn] remove reblog function

### ISSUE THREAD

**Issue by millerf** [Automattic/jetpack#29616]
We could use the "disabled_reblogs" option (see context: https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/modules/likes/jetpack-likes-settings.php#L692)

**Comment by romarioraffington** [comment]
> We could use the "disabled_reblogs" option

This disables reblogs for the blogs; looking into how we can disable reblogs for a post 🤔

**Comment by artpi** [comment]
That option would disable reblogs for the entire site.
This is quite a surprising behaviour coming out of the blue. I think we should disable it from the wpcom end in this function:
`wpr_can_reblog_post`

`wp-content/mu-plugins/reblogging.php` line 2255


If status is not "everybody" - disable reblogging of this specific post.

**Comment by romarioraffington** [comment]
Fixed in D106812-code

**Comment by jeherve** [comment]
Related: #29105, where Reblogs appear in the payment overlay.

**Comment by romarioraffington** [comment]
Thanks for sharing. The fix in D106812-code is specific to Paid Newsletters, however, I could look into the issue above in the same patch since the code has yet to be merged.

**Comment by romarioraffington** [comment]
Created a separate fix for  https://github.com/Automattic/jetpack/issues/29105. See D108112-code

**Comment by romarioraffington** [comment]
The fix for this PR is in D106812-code

**Comment by romarioraffington** [comment]
Deployed D106812-code

**Comment by romarioraffington** [comment]
Code was reverted. See D108235-code and more context: p1681856914579699-slack-C01B6KEJ5GE.

An upcoming PR will address the issue

**Comment by romarioraffington** [comment]
Patch with the fixes: D108237-code

**Comment by romarioraffington** [comment]
Deployed on WPCOM
