### ISSUE TITLE
TOS missing on My Jetpack upgrade interstitial [Core, Backup, Scan, Akismet]

### ISSUE THREAD

**Issue by grbicsanja** [Automattic/jetpack#29610]
When a user is not connected, we need to show TOS below the buttons on the plan upgrade My Jetpack interstitials.

![Image](https://user-images.githubusercontent.com/90194580/226868500-e08746af-124a-425f-8b66-51647b876277.png)

p1HpG7-l2l-p2
See task 42 for video walkthrough

**Comment by jkguidaven** [comment]
@grbicsanja I believe there was a new guideline on where to display TOS p1HpG7-_kep-p2. We also made [efforts to update some of the screens](https://github.com/Automattic/jetpack/pull/28403) to comply with the new guidelines.

Is this not applicable to the interstitials?

**Comment by grbicsanja** [comment]
@jkguidaven let me have a look and consult with the design team. I'll move this task back to 'needs design' while I figure this out!

**Comment by grbicsanja** [comment]
Ok I checked the post p1HpG7-jRz and with @eeeeeevon2023, and the designs here are in compliance. Thanks for your input @jkguidaven!

**Comment by jkguidaven** [comment]
Thanks for confirming @grbicsanja 👍
