### ISSUE TITLE
My Jetpack: Add Product Table Component

### ISSUE THREAD

**Issue by nateweller** [Automattic/jetpack#29638]
In support of:
https://github.com/Automattic/jetpack/issues/29562
https://github.com/Automattic/jetpack/issues/29534
https://github.com/Automattic/jetpack/issues/29537

Currently, the standalone plugins are each responsible for rendering their own pricing table, within the plugins themselves. Since we want to integrate the pricing tables into the My Jetpack experience, I propose adding a reusable `ProductDetailTable` component that we can use for all standalone plugins that offer multiple tiers (i.e. free/paid for Protect and Boost, free/basic/advanced for Social).

**Comment by renatoagds** [comment]
@nateweller Added this on the `My Jetpack` [board](https://github.com/orgs/Automattic/projects/464/views/6) from `Agora.` Feel free to add the other ones as soon you request for review.

**Comment by jeffgolenski** [comment]
I can't tell you how much I support this.
