### ISSUE TITLE
Golden token: find a place to serve the video file from

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#29658]
the animation relies on an actual mp4 and needs to get loaded into the UI somehow. Like https://github.com/Automattic/jetpack/pull/29644/files#diff-df2ff696b6ce49f9895d0bb4f4c776c76b1172f7ea4f2c9e20741ff2fba6c736R33

p1679574868247959/1679546968.991729-slack-C04V237FP40

**Comment by nunyvega** [comment]
After discussing this with Greenhouse folks, it looks like we're good to use the file's URL:
p1679576860071729-slack-C9W0QF6KA

I'll see where's the best place to get this file uploaded

**Comment by jeherve** [comment]
> I'll see where's the best place to get this file uploaded

Jetpack.com may be the best place; it's public and linked to that content.

**Comment by nunyvega** [comment]
Thanks for the reply @jeherve 
I added the file to jetpack.com, here's the link:
https://videos.files.wordpress.com/oSlNIBQO/jetpack-golden-token.mp4
Alternatively, if we want to use the VideoPress player instead of the HTML video tag, here’s the code for the embed (with autoplay and hiding controls):
```
<iframe width="560" height="315" src="https://videopress.com/embed/oSlNIBQO?cover=1&autoPlay=1&controls=0&loop=0&muted=1&persistVolume=0&playsinline=1&preloadContent=metadata&useAverageColor=1&hd=1#amp=1" frameborder="0" allowfullscreen allow="clipboard-write"></iframe>
<script src="https://videopress.com/videopress-iframe.js"></script>
```
