### ISSUE TITLE
Jetpack CLI: build command builds something that doesn't exist?

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#29663]
### Impacted thing

`jetpack` cli command

### Quick summary

If the project doesn't exist, it'll communicate that it doesn't exist but goes on to build something anyway. 

A better UX might be to stop the build process and list projects? 
![image](https://user-images.githubusercontent.com/7129409/227287283-e2bd37a4-8d95-4413-99e6-087b9b4cb636.png)

Or maybe error out similar to `watch`
![image](https://user-images.githubusercontent.com/7129409/227283288-8257259a-17dd-402e-8fb7-877c0f5b2c58.png)

### Steps to reproduce
`jetpack build doesnt/exist`

### A clear and concise description of what you expected to happen.
Stop the build process and instead list projects that could be built maybe?

### What actually happened

![image](https://user-images.githubusercontent.com/7129409/227282999-6a3a59d4-6781-4aa8-85f8-aeb19189c7da.png)

### Impact
All who make a typo in the cli build command

### Available workarounds?

No but the platform is still usable

**Comment by kraftbj** [comment]
Discussion: p1679591393900579-slack-CBG1CP4EN

As for the solution, likely around these lines: https://github.com/Automattic/jetpack/blob/9872bc784149790758fcd1d01357fea5b2a7fc16/tools/cli/commands/build.js#L124-L129

For a single-project call, e.g. `jetpack build does/notexist`, we should abort out when the project is not found and present the project selection menu (like `jetpack build` without args does).

For a multiple-project call, e.g. `jetpack build plugins/jetpack does/notexist`, assuming any of them are valid, the current behavior is okay. A stretch goal would be to delay the console error until the end of the build process to make it easier for someone to see that a particular requested project was not built.

My thinking there is if it at the top, where it would be now, and someone had run `jetpack build plugins/jetpack plugins/nopenope --deps`, a lot of things would still be built and the error would likely be not viewable in the window.

By putting the error message at the end, it is a clearer signal to the developer that a particular requested project is not available and to recheck the command (vs try whatever they're doing, have it not be built, perhaps just arrow-up and re-run, etc).
