### ISSUE TITLE
JITM style improvements

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#29672]
Some ajustments are needed for the JITMs.

More context:
p1HpG7-l9I-p2
MrkHtDbIWxPThpI1BbaRhH-fi-3190%3A7430

**Comment by nunyvega** [comment]
Let's also tackle two small issues:

1- On devices with the smallest dimensions like in Galaxy fold the button is not behaving as expected:
![227915621-6a3e29cb-b4e1-4acd-8398-06ba190e9234](https://user-images.githubusercontent.com/16329583/227918405-cc41f545-827a-40cb-a70c-0a4bd84bc11c.png)


Additionally, the cross to hide the JITM is also overflowing when the browser window is at its smallest (similar to the previous comment, it's not related to your PR):
![Screenshot 2023-03-27 at 12 29 21](https://user-images.githubusercontent.com/16329583/227918264-6754df90-ed96-4883-b90f-aada82414a90.png)
