### ISSUE TITLE
My Jetpack: Enrich product card component

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#29675]
We need an enriched version of the product card component.

* When the product has more details to show (it's enriched, for now only VideoPress will be), we show the product name, a metric name and a metric value, following this layout:

![image](https://user-images.githubusercontent.com/6760046/227373276-ef9323f8-dd62-4580-a8e9-96ca3958abb9.png)

The Expand button will not be added on this iteration. The action menu will be necessary so the user can get to the "Manage" option, but it has it's own issue (#29676) so we can just add the button for now.

The Actions menu is always visible on any state of the card (hover, on focus, etc).

The aim is to get a component that is showed this way:

<img width="392" alt="Screen Shot 2023-03-27 at 18 45 57" src="https://user-images.githubusercontent.com/6760046/228279362-e7f968c2-b68b-487e-b3d0-04e56cd2fea3.png">

We can get details about spacing, font size and other layout specs with the design team.

It would be good to have this change on a Story on the Storybook.

**Comment by renatoagds** [comment]
Done in #29787
