### ISSUE TITLE
The "Add Payments" is not showing on the Subscribe block

### ISSUE THREAD

**Issue by artpi** [Automattic/jetpack#29693]
The "Add Payments" is not showing on the Subscribe block when payments not set up on Jetpack 12.0-a.7

Reproduction path:

1. Get a fresh site on wpcom production
2. Ensure you are proxying wpcom
3. Create a post or a page
4.  Insert subscribe block
5. Observe no "Add Payments" in the Subscribe block

**Comment by valash85** [comment]
> The "Add Payments" is not showing on the Subscribe block when payments not set up on Jetpack 12.0-a.7
> 
> 
> 
> Reproduction path:
> 
> 
> 
> 1. Get a fresh site on wpcom production
> 
> 2. Ensure you are proxying wpcom
> 
> 3. Create a post or a page
> 
> 4.  Insert subscribe block
> 
> 5. Observe no "Add Payments" in the Subscribe block
> 
> 
> 

bnb13379unj63096zw5kygyypvvpzwrckgh7mszyjd
