### ISSUE TITLE
Can't activate the plugin. 401: Jetpack: [unknown_token] It looks like your Jetpack connection is broken. Try disconnecting from WordPress.com then reconnecting.

### ISSUE THREAD

**Issue by pelavida** [Automattic/jetpack#29713]
### Impacted plugin

Jetpack

### Quick summary

401: Jetpack: [unknown_token] It looks like your Jetpack connection is broken. Try disconnecting from WordPress.com then reconnecting.

My images are gone.

### Steps to reproduce

Upload plugin
click to activate it
error = 401: Jetpack: [unknown_token] It looks like your Jetpack connection is broken. Try disconnecting from WordPress.com then reconnecting.

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by jeherve** [comment]
Hi there!

Could you contact our support team via [this link](https://jetpack.com/contact-support/?rel=support&hpi=1)? Once we have more information about your site, we should be able to help you with this.

Thank you!
