### ISSUE TITLE
Widgets: Facebook Page Plugin defaults overwrite custom widget settings

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2971]
In db79a2c05cdf625d3210336f1d78a67a9bcf7e65 (#2846), we added default arguments to the Like Box widget settings saved in `$new_instance`, via `wp_parse_args`. It causes some issues with the Like Box settings. To reproduce the problem, try the following:

1. Go to Appearance > Widgets, and drag a new Facebook Like Box widget to your sidebar.
2. Add a URL, save your settings, the box seems to work.
3. Click on the "Show Faces" checkbox to disable Faces.
4. Save your changes.
5. "Show Faces" is checked again.

@dereksmart Could you take a look? Since we already get the default arguments [here](https://github.com/Automattic/jetpack/blob/master/modules/widgets/facebook-likebox.php#L119) and [here](https://github.com/Automattic/jetpack/blob/master/modules/widgets/facebook-likebox.php#L141), we should have all the default args we need when saving the widget settings, don't you think?

Reported here:
https://wordpress.org/support/topic/facebook-like-box-issues

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/problem-with-facebook-widget?replies=2&view=all

**Comment by csonnek** [comment]
Also in 2419919-t

**Comment by dereksmart** [comment]
fixed #3023
