### ISSUE TITLE
Updates Prompt: Clean up spacing a bit

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#2972]
The spacing/design of this message could use a little love to bring it in line with some of our others.

![screen shot 2015-11-06 at 9 29 28 am](https://cloud.githubusercontent.com/assets/108942/11002646/57e39684-846b-11e5-8361-7dd987673560.png)

**Comment by jeffgolenski** [comment]
Fixed in: https://github.com/Automattic/jetpack/pull/3006
