### ISSUE TITLE
Plugins: Make activation link text more accessible and use correct link color

### ISSUE THREAD

**Issue by mattgawarecki** [Automattic/jetpack#29743]
On all plugin pricing and upgrade pages (i.e., the standard interstitial in My Jetpack, plus each plugin's bespoke version), our license activation link uses the phrase "Click here to get started." To make this text more accessible, we can say either "Get started" or remove the imperative all together to make "Already have an existing plan or license key?" the link text.

As well, these links are all colored blue, whereas design mock-ups indicate they should be "Jetpack Black."

For detailed design mock-ups, visit Figma: `TTzDk3dzct551hYWRXPFa3-fi-7065-64108`

First noted in https://github.com/Automattic/jetpack/pull/29443#issuecomment-1485848711.

##### Currently in production

![Image](https://user-images.githubusercontent.com/670067/228239777-4438b24b-9065-463f-b8da-05544b4ef543.png)

##### Design mock-up (missing accessible link text)

![Image](https://user-images.githubusercontent.com/670067/228239914-3e351baf-610a-47a8-b47b-15b575a0fa2a.png)

**Comment by bluefuton** [comment]
Thank you for writing this up @mattgawarecki! I'll try and tackle this as part of the Akismet upgrade work (https://github.com/Automattic/jetpack/pull/29598).

**Comment by bluefuton** [comment]
This was resolved as part of https://github.com/Automattic/jetpack/pull/29598.
