### ISSUE TITLE
WAF check for HTTPS protocol is broken in some configurations

### ISSUE THREAD

**Issue by alexsanford** [Automattic/jetpack#29745]
### Impacted plugin

Jetpack

### Quick summary

Per 6075203-zen, the [check for HTTPS](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/waf/src/class-waf-request.php#L205) specifically checks for a value of `'on'`. However, the PHP doc states that `$_SERVER['HTTPS']` is "Set to a non-empty value if the script was queried through the HTTPS protocol." If some value other than `on` is populated in this variable, the condition fails.

### Steps to reproduce

Using an Apache SSL reverse proxy configured as follows will set a value of `'1'` in `$_SERVER['HTTPS']` instead of `'on'`:

```
 <IfModule mod_setenvif.c>
SetEnvIf X-Forwarded-Proto "^https$" HTTPS
</IfModule>
```

### Impact

One

### Available workarounds?

Yes, difficult to implement

**Comment by jeherve** [comment]
cc @nateweller ; do you think you could take a look?

Thank you!

**Comment by tomfotherby** [comment]
I recommend

```
Changing:    ! empty( $_SERVER['HTTPS'] ) && 'on' === $_SERVER['HTTPS']
To           ! empty( $_SERVER['HTTPS'] ) && 'off' !== $_SERVER['HTTPS']
```
