### ISSUE TITLE
Mobile Theme: Use custom excerpt if available

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#2975]
Right now we construct our own excerpt using `minileven_excerpt()`:

https://github.com/Automattic/jetpack/blob/3.8.0/modules/minileven/theme/pub/minileven/content.php#L37

... which is defined here:

https://github.com/Automattic/jetpack/blob/3.8.0/modules/minileven/theme/pub/minileven/inc/tweaks.php#L15-L23

If the user has set a custom excerpt for their post, it is not displayed. It should be.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/use-manual-excerpt-in-mobile-theme?replies=1&view=all

Related commit: 5f1d2c75e4e082b0aa86b56480b243facfaed0e6
And on WordPress.com: r13539-wpcom-themes

It appears that the change was introduced to address a multibyte truncation issue, as reported here:
https://wordpress.org/support/topic/mobile-theme-read-the-rest-of-the-story-disappearing-at-times-1?replies=6&view=all

I'm not sure how we could fix the bug while still allowing folks to use custom excerpts. @michiecat Do you have any ideas?

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
