### ISSUE TITLE
Subscriptions: Extra PHP closing tag needs removed

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#2976]
Here:

https://github.com/Automattic/jetpack/blob/3.8.0/modules/subscriptions.php#L855

Screenshot:

![screen shot 2015-11-08 at 4 08 48 pm](https://cloud.githubusercontent.com/assets/5512652/11022699/09896d64-8633-11e5-8c95-11b737f1c1b4.png)

**Comment by aheckler** [comment]
Affecting user in 2410396-t.

**Comment by jeherve** [comment]
Related: a94c11fe835f205553f43de51643021398aecb62 and #2632
