### ISSUE TITLE
Function "stats_dashboard_head" not found

### ISSUE THREAD

**Issue by zaerl** [Automattic/jetpack#29773]
### Impacted plugin

Jetpack

### Quick summary

See https://github.com/Automattic/jetpack/pull/29524#issuecomment-1482585113. The `stats_dashboard_head` function is added to `admin_head` action, but it is not always defined.

```
PHP Fatal error:  Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "stats_dashboard_head" not found or invalid function name in /var/www/html/wp-includes/class-wp-hook.php:308
```
@jsnmoon  [this commit](https://github.com/Automattic/jetpack/commit/6b4f97eb18bbe0b43f4f8401ce7474ce96e3aff2) unfortunately seems not to solve the issue.

### Steps to reproduce

1. Run Jetpack locally with the last trunk
2. Access `wp-admin`
3. See the error in `wp-content/debug.log` file

### A clear and concise description of what you expected to happen.

The `wp-admin` page loads in environments where `call_user_func_array()` type errors are fatal errors.

### What actually happened

1. The `wp-admin` does not load and the `There has been a critical error on this website. Please check your site admin email inbox for instructions.` page is shown.
2. The fatal error is logged in the `debug.log` file.

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by anomiex** [comment]
https://github.com/Automattic/jetpack/blob/4555e345b9d9c7ce67101424ebb10a8532071809/projects/plugins/jetpack/class-jetpack-stats-dashboard-widget.php#L56-L57
Looks like that TODO needs to be done. The function is currently in `modules/stats.php`, which is not loaded if the "Jetpack Stats" module is disabled.

Or else the new widget code needs to somehow disable itself when the module is not active.
