### ISSUE TITLE
Stats Widget: data for 'Total blocked spam comments'

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#29797]
Find or create endpoint or use initial state to get the data for 'Total blocked spam comments'.

![Image](https://user-images.githubusercontent.com/1425433/228710716-b9350708-a50d-4b89-be35-183f3cfd6e68.png)

**Comment by jeherve** [comment]
We have `wp-json/jetpack/v4/module/akismet/data`, that maybe you could use?

**Comment by kangzj** [comment]
Ya! Thanks @jeherve for saving us hours time exploring 👍

**Comment by kangzj** [comment]
closed by https://github.com/Automattic/wp-calypso/pull/75637
