### ISSUE TITLE
Stats Widget: data for 'Total blocked login attempts'

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#29796]
Find or create endpoint or use initial state to get the data for 'Total blocked login comments'.

![Image](https://user-images.githubusercontent.com/1425433/228710643-b835ed18-b96a-4d38-b829-9120e80039ba.png)

**Comment by jeherve** [comment]
We have `wp-json/jetpack/v4/module/akismet/data`, that maybe you could use?

**Comment by jeherve** [comment]
We have `wp-json/jetpack/v4/module/protect/data`, that maybe you could use?

**Comment by kangzj** [comment]
Looks good! Thanks @jeherve for saving us hours time exploring 👍

**Comment by kangzj** [comment]
Closed by https://github.com/Automattic/wp-calypso/pull/75637
