### ISSUE TITLE
My Jetpack: Always keep the action button available on the product card

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#29825]
After the last iteration of design, we got an update on the layout of the product card so the action button (bottom left button) is kept visible even for enriched cards like the VideoPress.

This makes normal cards taller to accomodate stats and moves the status of the product back to it's original place, side-by-side with the action button.

![image](https://user-images.githubusercontent.com/6760046/228970204-49f23295-bb7b-414a-a534-91dff1d03914.png)

More details: p1HpG7-ly0-p2#comment-61966

**Comment by renatoagds** [comment]
Closing in favor of https://github.com/Automattic/jetpack/issues/29904 that will handle this one
