### ISSUE TITLE
Jetpack Plugin Visual Refresh: Modules list

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#29836]
Good 'ol `/wp-admin/admin.php?page=jetpack_modules` modules list. Not react. No functionality changes. 

p1HpG7-lx8-p2#module-list-debugger

![Image](https://user-images.githubusercontent.com/7129409/229136786-a6ab5690-3606-4df9-8058-957b2f8109f5.png)

**Comment by nateweller** [comment]
Unassigning myself from this one to prioritize working on https://github.com/Automattic/jetpack/issues/29835. Will pick this back up after I'm done with the settings screens, if it is still available at that time :+1:

The only progress made was some discussion about approach: p1680824155377489-slack-C051H2TQR54
