### ISSUE TITLE
Jetpack Plugin Visual Refresh: Header and nav

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#29838]
The header and nav components should look consistent to My Jetpack. 

There wasn't a specific section or call-out for this, it just intuitive to break it into it's own issue in case someone wants to take it separately. 

p1HpG7-lx8-p2

![Image](https://user-images.githubusercontent.com/7129409/229137816-30ba1c97-2116-4255-961d-676dc006cc01.png)

**Comment by nateweller** [comment]
Just noting that we've partially implemented this header design in Jetpack Protect, if useful: https://github.com/Automattic/jetpack/tree/trunk/projects/plugins/protect/src/js/components/tabs

**Comment by sergeymitr** [comment]
I created a PR (#29980), in progress for now as I need to review a bunch of edge cases myself first.

Here are the screenshots, @jeffgolenski please take a look when you get a minute.

**Desktop screen, notice, WoA menu:**
<img width="1014" alt="Screen Shot 2023-04-06 at 20 22 56" src="https://user-images.githubusercontent.com/1341249/230520985-380f7bf6-f7e6-4015-8ce4-10142e6b214d.png">

**Mobile screen, notice, WoA menu:**
<img width="430" alt="Screen Shot 2023-04-06 at 20 23 15" src="https://user-images.githubusercontent.com/1341249/230521017-cbfce137-ce38-4a0c-8b8d-0917a20f9b97.png">

**Desktop screen, WoA menu:**
<img width="994" alt="Screen Shot 2023-04-06 at 20 24 38" src="https://user-images.githubusercontent.com/1341249/230521036-0cff2c5e-8652-4833-9d76-751d4a2eaa91.png">

**Mobile screen, WoA menu, Settings page:**
<img width="432" alt="Screen Shot 2023-04-06 at 20 25 21" src="https://user-images.githubusercontent.com/1341249/230521155-177af43e-d6f7-467f-948a-2a7ffd863054.png">

**Modules page, desktop screen, WoA-like menu always shows up there:**
<img width="814" alt="Screen Shot 2023-04-06 at 20 26 34" src="https://user-images.githubusercontent.com/1341249/230521220-6a7885fc-45a9-4298-9df5-5f62b6034f78.png">

**Comment by jeffgolenski** [comment]
That was quick @sergeymitr! Thank you. Just a small change request. The inactive links should have a border color of `gray 5` (DCDCDE) from the color studio. 

![Segmented control](https://user-images.githubusercontent.com/214813/230938439-c4852be8-638e-4846-abfc-7619a58adabd.png)

**Comment by sergeymitr** [comment]
Hi @jeffgolenski, thanks for taking a look.
Here's an updated version:
1. The `gray 5` border for the WoA settings
2. Notices moved to under the main nav
3. Replaced the "Connect you WP.com account" banner with the `Notice` component form `@automattic/jetpack-components`

Please take a look when you get a minute.

**Desktop screen**
<img width="1086" alt="Screen Shot 2023-04-12 at 16 23 32" src="https://user-images.githubusercontent.com/1341249/231577036-bab3a952-0e2a-421b-abbd-f65bfd482508.png">

**Mobile screen**
<img width="499" alt="Screen Shot 2023-04-12 at 16 23 44" src="https://user-images.githubusercontent.com/1341249/231577100-21048be1-680d-4da6-8162-9e4d7acff920.png">

**Modules header, desktop screen**
<img width="1096" alt="Screen Shot 2023-04-12 at 16 30 12" src="https://user-images.githubusercontent.com/1341249/231577197-ec9c209f-af8b-4ccb-9feb-281099ec48da.png">

**Comment by jeffgolenski** [comment]
Just one problem @sergeymitr... it's perfect. :-P

Ship away!

**Comment by sergeymitr** [comment]
Awesome, thanks Jeff! 🙂
