### ISSUE TITLE
Jetpack Plugin Visual Refresh: Debugger

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#29837]
The one at `/wp-admin/admin.php?page=jetpack-debugger`. Not react. Just basic style update. 

p1HpG7-lx8-p2#module-list-debugger

![Image](https://user-images.githubusercontent.com/7129409/229137015-d0380c30-c056-4eba-b682-35c8dd1bb9c6.png)

**Comment by sergeymitr** [comment]
Hi @jeffgolenski.
In case of debugger errors, should we style them like regular notices you designed, or we'll do something different?
Currently they're folded by default:
<img width="1069" alt="Screen Shot 2023-04-17 at 20 52 16" src="https://user-images.githubusercontent.com/1341249/232641387-7eb24728-f08b-4552-b27a-31f278091a37.png">
<img width="1069" alt="Screen Shot 2023-04-17 at 20 53 19" src="https://user-images.githubusercontent.com/1341249/232641404-cec47504-fb3b-490f-a77e-eee912d736bb.png">

**Comment by jeffgolenski** [comment]
@sergeymitr ah good find. Yes, please. Let's use the notices. Those look pretty severe / are blocker level warning. Do you think the red error notices are best suited for those?

![Screen Shot 2023-04-18 at 2 58 13 PM](https://user-images.githubusercontent.com/214813/232878186-1a03016b-d0ec-4672-b67a-1eae6b252a6e.png)
