### ISSUE TITLE
Jetpack Monster Widget

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#2984]
It would be awesome if Jetpack offered a monster widget for developers who are testing Jetpack with their theme. Similar to the [Monster Widget Plugin](https://wordpress.org/plugins/monster-widget/).

Also this widget should only be enabled when Jetpack debug mode is enabled.

**Comment by kraftbj** [comment]
Thinking aloud, Monster Widget is an Automattic plugin. I wonder the feasibility of hooking into that in some way to output available Jetpack widgets or if truly best within Jetpack/an add-on plugin, etc.

**Comment by bhubbard** [comment]
I think hooking into the Monster widget would be a great option. Going that route maybe any plugin or theme could add their custom widgets to the monster widget.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
