### ISSUE TITLE
Mobile App: Tablet and Desktop preview not showing.

### ISSUE THREAD

**Issue by nomad-skateboarding-dev** [Automattic/jetpack#29858]
### Impacted plugin

None / Other

### Quick summary

# When trying to preview a page in Jetpack Mobile app and switch to Tablet or Desktop view, it doesn't switch.

https://user-images.githubusercontent.com/78917704/229266891-1c8132fb-9e7d-4774-a052-2076314ccf73.mp4

### Steps to reproduce

1. Open Jetpack Mobile app
2. Select "Pages"
3. Select any page
4. Select "Preview"
5. Select "Tablet" or "Mobile"
6. Select any navigation link
7. Select "Tablet" or "Desktop", they now work when clicked
8. Go back to original page. Select "Tablet" or "Desktop", they now work when clicked

### A clear and concise description of what you expected to happen.

I expected a tablet or desktop preview of the page I was viewing.

### What actually happened

A green circle began spinning and never stopped.

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by jeherve** [comment]
I would recommend creating this issue in this repository, where the Jetpack app is developed:
https://github.com/wordpress-mobile/WordPress-Android

**Comment by nomad-skateboarding-dev** [comment]
Thank you kindly @jeherve 🙂
