### ISSUE TITLE
Subscription confirmation email has slightly misleading Subject.

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#2985]
From 2412077-t:

> Right now it says  '[Subscribe] Confirmed Subscription to Posts...' But I think it should not say 'Subscribe' which is confusing being that the user just subscribed and are now receiving confirmation. So it should say something like [Subscribed] Confirmed Subscription to Posts...

If I'm not mistaken, the [Subscribe] part comes the name of the site at http://subscribe.wordpress.com, so the email templates would have to be modified, I presume.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
