### ISSUE TITLE
My Jetpack: Update product endpoint for standalone

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#29903]
We have the [product endpoint ](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/my-jetpack/src/class-rest-products.php#L53-L60) that activates (and installs if needed) the plugin.

This endpoint calls the [`activate`](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/my-jetpack/src/products/class-product.php#L390-L407) method, which looks if the [plugin is installed](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/my-jetpack/src/products/class-product.php#L366).

But as soon we return to hybrid, this [method is overridden](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/my-jetpack/src/products/class-hybrid-product.php#L46-L48), and look for the `Jetpack` plugin too.

We need to change or add an option to look only for the standalone plugin on this call.

**Comment by lhkowalski** [comment]
I was checking why both plugins are checked here, and seems like it's intended to fix a 'plugin_absent' status for Backup when only Jetpack is installed.

Since we are fixing the status handling, seems safe to remove the check for Jetpack installation. Makes sense?

**Comment by renatoagds** [comment]
> Since we are fixing the status handling, seems safe to remove the check for Jetpack installation. Makes sense?

Yes. My only concern is `class-extras`, if it works as expected (installing Jetpack plugin), I think it is worth removing it, since we want to push user to install standalone

**Comment by lhkowalski** [comment]
Seems like `class-extras` is a product, not a hybrid-product, so changing the check on the `class-hybrid-product` would not affect it.

**Comment by lhkowalski** [comment]
@renatoagds Thinking about it, we are going to offer two options to the user:

**1) activate the product**

If the standalone plugin is present, we activate it. If it's not present, we activate the module inside Jetpack.

**2) install the standalone plugin for the product**

This will trigger the plugin installation + activation, in the case it's absent.

Is this description correct? If so, what we need are:

- change the activation endpoint to make sure it only activate what is present, without sideloading any standalone plugin
- create an endpoint to install and activate the standalone plugin

Does it makes sense?

**Comment by renatoagds** [comment]
> Does it makes sense?

Yes, it makes sense. It could be good to split the endpoints. It will already fix a point that we're pushing the user for interstitial in this case, and we shouldn't. With this one, we don't need to push the user for another page to use the same endpoint, we just install it based on the new endpoint.

**Comment by lhkowalski** [comment]
I was reviewing the code for the `Hybrid_Product`:

> change the activation endpoint to make sure it only activate what is present, without sideloading any standalone plugin

There is no need to change anything. This is how it works currently.

> create an endpoint to install and activate the standalone plugin

This is the action that we need to implement. I am going to focus on this.
