### ISSUE TITLE
My Jetpack: Move products back to Hybrid

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#29906]
Reverts the changes applied in the following PRs, to return the card to be reflected and based on the Jetpack plugin.

This one will try to move out of the confusion made and related in #28264.

We will push the user to install standalone plugins using the new menu in Product Card.

---

- [x] Search - https://github.com/Automattic/jetpack/pull/28113 - Revert: #29946 
- [x] VideoPress- https://github.com/Automattic/jetpack/pull/28097 - Revert: #29918 
- [x] Social - https://github.com/Automattic/jetpack/pull/28074 - Revert: #29935
- [x] VaultPress Backup - https://github.com/Automattic/jetpack/pull/28022 - Revert: #29928

**Comment by lhkowalski** [comment]
We moved all the products that have a standalone plugin back to hybrid products. Now we are going to work on the other issues to proper handle the status.
