### ISSUE TITLE
Automated plugin updates notice should not always be shown

### ISSUE THREAD

**Issue by fjarrett** [Automattic/jetpack#2993]
The automated plugin update notice introduced with the Manage module in #2778 should not be displayed to users when:

* The `auto_update_plugin` filter is set to `false`

OR

* The `AUTOMATIC_UPDATER_DISABLED` constant is set to `true`.

If either of these flags are set it should be an indication that the installation has explicitly opted-out of the [Automatic Background Updates](https://codex.wordpress.org/Configuring_Automatic_Background_Updates) behavior for plugins. It seems to me that Jetpack should inherit that preference and not display an opt-in notice that could create confusion.

**Comment by jeherve** [comment]
cc @jessefriedman
