### ISSUE TITLE
VideoPress: enqueue VideoPress IFrame API only when required

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#29934]
Currently, the asset file of the VideoPress IFrame API is enqueued by default, independently if the post has or hasn't VideoPress video instances. Let's try to optimize this by enqueuing the file when it's required.

**Comment by jeherve** [comment]
Related: #24765.

**Comment by retrofox** [comment]
One idea is/was not to enqueue the file when the modulo/plugin is inactive.
Something that is incorrect since even when the module/plugin is inactive, a post with a video instance in its content should still handle the video behavior.

So the idea of enqueuing the script only when the page contains a video instance came up, for instance, using the [has_block()](https://developer.wordpress.org/reference/functions/has_block/) function. However, this approach is not 100% reliable since it could be possible to create a page (website) containing a video block not recognized by the has_block() function, for instance, inserting a video in the site header.
