### ISSUE TITLE
Houzz Icon

### ISSUE THREAD

**Issue by vbrockway** [Automattic/jetpack#2994]
There are number of Houzz users who want to be able to add the Houzz badge alongside their other social icons via JetPack.  

Can the Houzz social icon be added?  We would just need to add our username or profile URL to connect.

**Comment by kraftbj** [comment]
Related: #449 (with how to enable it as an oembed provider, which I don't know would still be needed even after 4.4 ships), #1749.

@vbrockway - Do you mean as a sharing button to click to share the current post on Houzz or like along side the Social Media Widget?

**Comment by samhotchkiss** [comment]
Since this has a pretty narrow use-case, i'm less inclined to include this out-of-the-box, although it can easily be added on a per-site basis using the `jetpack_social_media_icons_widget_array` filter
