### ISSUE TITLE
Jetpack Social: fatal error when using Gutenberg 15.4

### ISSUE THREAD

**Issue by liviopv** [Automattic/jetpack#29940]
### Impacted plugin

Jetpack

### Quick summary

When Jetpack Social is installed, opening any post or page in the editor will trigger a fatal error if the site has the Gutenberg plugin on version 15.4 (I haven't tested it with Gutenberg 15.5 RC) installed.

Error:

```
PHP Fatal error:  Uncaught Error: Call to undefined method Automattic\Jetpack\Publicize\Publicize::is_social_image_generator_enabled() in /wordpress/plugins/jetpack/12.0-a.7/class.jetpack-gutenberg.php:750
```

Deactivating any of those plugins fixes the conflict.

### Steps to reproduce

1. Install Jetpack Social
2. Install Gutenberg 15.4
3. Open the editor for any post or page

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

### Logs or notes

PHP Fatal error:  Uncaught Error: Call to undefined method Automattic\Jetpack\Publicize\Publicize::is_social_image_generator_enabled() in /wordpress/plugins/jetpack/12.0-a.7/class.jetpack-gutenberg.php:750

Internal chatter: p1680709352566489-slack-C02JJ910CNL

**Comment by liviopv** [comment]
- [ ] 6177159-zd-woothemes
- [ ] 36063509-hc

**Comment by essleeung** [comment]
- [ ] 6174788-zd-woothemes

**Comment by ghost** [comment]
27027149-hc

**Comment by ClassicRKR27** [comment]
Another report here: 38070719-hc
User is complaining about the fact that we have installed an alpha on their site.

Edit: User rolled-back their site and disabled automatic updates so that `Jetpack Social` stays on v1.8 which has resolved the issue for them.

**Comment by csabarakasz** [comment]
41520883-hc same

**Comment by edwinho89** [comment]
Similar issue on 27784245-hc

**Comment by mdtanjid0** [comment]
Another one: 

- [ ] 6177898-zen ( needs to follow up ).

**Comment by zdenys** [comment]
@spsiddarthan is there a timeline on when the fix https://github.com/Automattic/jetpack/pull/29952 will land for WoA users on WP.com? I have a user in 6178769-zd-woothemes who is asking about this and would love an email sent to them to inform them once the fix is in place. Thank you!
