### ISSUE TITLE
VideoPress block: Privacy setting remains available even when it's not usable

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/jetpack#29964]
### Impacted plugin

Jetpack, VideoPress

### Quick summary

After adding a VideoPress public video (e.g. https://videopress.com/v/OcobLTqC), it's possible to access the **Privacy and rating** panel under the VideoPress block's settings, even though it's not possible to actually change the block's privacy. 

If you attempt to change the privacy, an uninformative error message appears, but that error message is only visible upon scrolling.

It is unlikely that many users will go through this flow, but would still be ideal if we could either improve the error message or hide the privacy setting when it can't be used.

### Steps to reproduce

1. Go through the steps to add a VideoPress block to a post.
2. Select the option to **Insert from URL**.
3. Add a VideoPress public video (e.g. https://videopress.com/v/OcobLTqC).
4. Navigate to the **Privacy and rating** panel in the block's settings.
5. Change the block's privacy from public to private and then save the post.

### A clear and concise description of what you expected to happen.

It's not actually possible to change the privacy of the public video. As such, I would ideally expect to not even have access to the **Privacy and rating** panel. If the panel has to remain, I would at least expect an informative error message to guide me on why it's not possible to tweak the video's privacy.

### What actually happened

I have to scroll up in the settings to see that there was an error. Even after seeing the error, it's not very informative or helpful:

<img width="1458" alt="Screenshot 2023-04-06 at 11 53 51" src="https://user-images.githubusercontent.com/2998162/230357452-874f740f-09b2-4a8d-8f4d-115501393671.png">

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by ntsekouras** [comment]
I think we can close this one since https://github.com/Automattic/jetpack/pull/30443 has landed. Feel free to reopen if that's not the case.
