### ISSUE TITLE
VideoPress: return `null` when saving the VideoPress video block

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#29987]
Probably we should render the block markup dynamically (server-side). If so, and to avoid block validation errors, we may return null in the block save() function.

**Comment by chriscoyier** [comment]
Is this why I get the "Block has encountered an error" on all VideoPress blocks when I go back to edit a post that has one? It looks fine upon first upload, just not after a page refresh. 

<img width="778" alt="Screenshot 2023-04-11 at 1 25 12 PM" src="https://user-images.githubusercontent.com/69156/231280223-6ed32dfa-2e45-4f6a-86a4-fc69c9d7d69c.png">

**Comment by retrofox** [comment]
I don't think so, but I'm really interested to see what errors you are getting. Could you provide more information about the error?

**Comment by chriscoyier** [comment]
There are two JavaScript errors:

1. caught ReferenceError: edButtons is not defined
1. TypeError: Cannot read properties of undefined (reading 'replace')
  
<img width="684" alt="Screenshot 2023-04-13 at 6 12 47 AM" src="https://user-images.githubusercontent.com/69156/231769637-51000c30-9eca-4453-9b8b-120fb8966fa2.png">
