### ISSUE TITLE
My Jetpack: investigate why site with Jetpack Professional is asking to get a Jetpack Backup plan

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#29998]
A site with Jetpack Professional is asking the user to add a Backup plan, but it should not because it's already included in the plan. This is what the site shows:

![Image](https://user-images.githubusercontent.com/16329583/230741747-a9c80b5e-cff5-4f0f-bf14-ad7781d478ec.png)

Discussed here:
p1680801315035299-slack-C0299DMPG

**Comment by nunyvega** [comment]
I was not able to replicate it on a fresh test site with Jetpack Professional. 

What I can see from their second screenshot is that the date for the Jetpack Professional subscription is not shown. This is what happens in the reported site:
![image](https://user-images.githubusercontent.com/16329583/230742810-d1369412-1600-4503-9257-cbbbda54fe1d.png)

And normally we show the expiration date under the plan's name:
<img width="310" alt="Screenshot 2023-04-08 at 23 15 25" src="https://user-images.githubusercontent.com/16329583/230742821-43864642-eec5-4b6b-9cf6-83ecb7f77a88.png">

**Comment by lhkowalski** [comment]
A request to the `v1.1/sites/$site/features/` endpoint returns a list that includes backups and other backup-related features as active:

```
{
    "active": [
        "akismet",
        "antispam",
        "backups",
        "backups-daily",
        "calendly",
        "cdn",
        "search",
        "cloudflare-analytics",
        "cloudflare-cdn",
        "core\/audio",
        "core\/cover",
        "core\/video",
        "donations",
        "full-activity-log",
        "google-analytics",
        "google-my-business",
        "jetpack-dashboard",
        "opentable",
        "polldaddy",
        "premium-themes",
        "priority_support",
        "real-time-backups",
        "recurring-payments",
        "republicize",
        "scan",
        "security-settings",
        "seo-preview-tools",
        "send-a-message",
        "simple-payments",
        "social-previews",
        "social-shares-1000",
        "subscriber-unlimited-imports",
        "support",
        "upload-audio-files",
        "upload-video-files",
        "vaultpress-automated-restores",
        "vaultpress-backup-archive",
        "vaultpress-backups",
        "vaultpress-security-scanning",
        "vaultpress-storage-space",
        "video-hosting",
        "videopress",
        "videopress\/video",
        "videopress-unlimited-storage",
        "whatsapp-button",
        "wordads",
        "wordads-jetpack",
        "set-primary-custom-domain"
    ],
   ...
}
```

**Comment by nunyvega** [comment]
I can also see that the site does show the capabilities as expected in the RWDB

**Comment by nunyvega** [comment]
Moved the discussion of this issue to this post:
p1HpG7-lTc-p2

**Comment by nunyvega** [comment]
Marking this as resolved since it is not related to the plan nor the site (see thread above for more context)
