### ISSUE TITLE
Boost: Blank page when printing ticket in WC Box Office

### ISSUE THREAD

**Issue by ahegyes** [Automattic/jetpack#30008]
### Impacted plugin

Boost

### Quick summary

WC Box Office makes a call to `exit` after including the template for printing tickets. This causes the page to be blank probably because of a buffer that is opened by Jetpack Boost which never gets outputted.

Here is the "offending" `exit`: https://github.com/woocommerce/woocommerce-box-office/blob/4b9993aa9c563c3df49b8c6a87f7cc0cd05bd8e4/includes/class-wc-box-office-ticket-frontend.php#L145

### Steps to reproduce

1. Install, activate, and configure Jetpack Boost
2. Install, activate, and configure WC Box Office
3. Purchase a ticket powered by WC Box Office
4. Try to print the said ticket (URL should look like `<domain>/my-ticket/?token=<token>&print=true`)
5. The page will now be blank instead of the ticket showing up

### A clear and concise description of what you expected to happen.

The ticket contents should show up ready for printing instead of a blank page.

### What actually happened

A blank page showed up.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by thingalon** [comment]
I have reproduced the issue, and am investigating. First observation: the issue appears to occur when the "Defer Non-Essential JavaScript" feature in Boost is enabled.

**Comment by thingalon** [comment]
Ok, I've tracked it down a bug in our "defer js" feature which is triggered on pages with incredibly tiny HTML outputs - such as the ticket printing view in WC Box Office.

Fix here: https://github.com/Automattic/jetpack/pull/30025

If this gets 👍 quickly enough, we can squeak it into the upcoming 1.8.0 release.
