### ISSUE TITLE
Some loading state needs to be implemented while plans are fetching

### ISSUE THREAD

**Issue by millerf** [Automattic/jetpack#30001]
Context:

https://github.com/Automattic/jetpack/pull/29989 introduced a small "lag" when loading the newsletter panel. See p1681059414009909/1681053294.810209-slack-C01B6KEJ5GE

Task:

Add a "loading" state while the plans are loading (probably [here](https://github.com/Automattic/jetpack/pull/29989/files#diff-eba2301ede604e2450a0b3ea7d13cdc88d427f67d0f1777028aa9e2e154623c3R100-R105)
The store resolver has a state, but I cannot remember where exactly. 

So the panel does not "flicker".

**Comment by romarioraffington** [comment]
@millerf, it appears that this task is blocked by https://github.com/Automattic/jetpack/pull/29989?

**Comment by millerf** [comment]
> @millerf, it appears that this task is blocked by #29989?

You can implement the solution directly in https://github.com/Automattic/jetpack/pull/29989, or branch out from it also...
