### ISSUE TITLE
Jetpack "Like" button on Pages has improper line-height

### ISSUE THREAD

**Issue by jekkilekki** [Automattic/jetpack#3002]
Actually, there is no `line-height` value assigned to the "Like" button which causes the text to float lower than all the other links in the `wpadminbar`. 

Here's a reprint of [my Gist that details this issue:](https://gist.github.com/jekkilekki/f1673a0c8f486f279e8f)

With Jetack "Likes" turned on, when logged in, in the `wpadminbar`, the "Like" button text doesn't line up:

![Like text out of line](http://www.aaronsnowberger.com/wp-content/uploads/2015/11/like-button-error.png)

To fix it, add:
`line-height: inherit;`

To:
`#wpadminbar .quicklinks li#wp-admin-bar-wpl-like > a { ... }`

![Like text fixed](http://www.aaronsnowberger.com/wp-content/uploads/2015/11/like-button-fixed.png)

**Comment by jeherve** [comment]
I can reproduce.

Thanks for the report!

**Comment by jekkilekki** [comment]
Glad to help~ Looking forward to the fix~

**Comment by lancewillett** [comment]
Fix: https://github.com/Automattic/jetpack/commit/8ff66302ab38062b67feeac45e1e50176fc471ba

**Comment by lancewillett** [comment]
CSS fixes are in on WP.com, r128381-wpcom and r128382-wpcom

Pull request bumps cache buster string.
