### ISSUE TITLE
Jetpack-mu-wpcom: Update Launchpad endpoint for misc/remaining tasks

### ISSUE THREAD

**Issue by edanzer** [Automattic/jetpack#30042]
### Impacted plugin

Jetpack-mu-wpcom

### What

Ensure launchpad endpoint returns correct misc task status

### How

Follow up on: https://github.com/Automattic/jetpack/pull/30023
Addresses: https://github.com/Automattic/wp-calypso/issues/75504

We added scaffolding for a new Launchpad checklist endpoint. We need to update the logic to be sure that endpoint return the correct checklist, with the correct statuses (complete, enabled) for each task, for remaining tasks not covered by other issues.

Don't think these need anything, but check: 'setup_free', 'setup_general', 'setup_write'
Others; 'domain_upsell', 'verify_email', 'stripe_account_connected'

**Comment by jeyip** [comment]
After more discussion with @edanzer and @mattwiebe, the verify email task completion status will be left to be defined in the client for the time being. Apparently, the information isn't already exposed on Atomic sites, and it would take about two weeks of drafting a PR, exposing an endpoint, discussion with Jetpack folks, waiting on the next JP release cycle, incorporating the changes into our refactor, and then waiting on the subsequent jetpack-mu-wpcom release.

We have the rest of the task definitions and their completion statuses migrated to the backend, and are still able to leverage most of the benefits of the refactor without committing to the extra complication of migrating the verify_email task
