### ISSUE TITLE
Invisible blocks when animation is added (Slideshow, Tiled Gallery..)

### ISSUE THREAD

**Issue by mxhassani** [Automattic/jetpack#30073]
### Quick summary

Adding an animation from Gutenberg to some blocks makes said blocks invisible (but still clickable).

Tested and confirmed with Slideshow, Tiled Gallery

The issue appears to be the class `zoomIn` (or similar) isn't added to the block while the class  `coblocks-animate` is added, which leaves the block with the propriety `opacity: 0;` in:

```
body:not(.amp) .coblocks-animate {
  animation-fill-mode: forwards;
  animation-timing-function: ease-in;
  opacity: 0;
}
```

### Steps to reproduce

1. On an Dotcom Atomic site
2. Open the Editor
3. Add a Slideshow or Tiled Gallery block
4. Add an animation from the block toolbar
5. Save and check

### What you expected to happen

To see the block after it plays an animation

### What actually happened

The blocks remain transparent but clickable. No animation is played.

### Context

39140943-hc

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

No

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Add one of the following CSS codes:

**Code 1** - Catch-all but may make some other block animations a bit janky: 
```
/* fix animation bug */
body:not(.amp) .coblocks-animate{
   opacity: 1 !important; 
}
```

**Code 2** - But you'd want to get specific if you want to keep the same type of animation picked by the user:

```
/* fix animation bug */
body:not(.amp) .coblocks-animate{
  animation-duration: .75s;
  animation-name: zoomIn;
}
```

You can replace `zoomIn` with one of the following:

```
fadein
slidein
slidein
spin
spinner__animation
loading__animation
coblocks-ellipsis
fadeIn
zoomIn
slideInLeft
slideInRight
slideInBottom
clipHorizontal
clipVertical
pulse
```

**Comment by kavyagokul** [comment]
📌 ACTIONS
- Await author feedback

📌 Message to Author
- Hey @mxhassani, These animations are part of Coblocks, which is a third-party plugin. Do you  think that it would be better to report this directly to them?

**Comment by mxhassani** [comment]
@kavyagokul thank you for the review. On the site's plugins list, it's mentioned for CoBlocks: "This plugin was installed by WordPress.com and provides features offered in your plan subscription."
Not sure where we stand in terms of how or where to report in that context.

**Comment by vajrasar** [comment]
@mxhassani we can submit issue [here](https://github.com/godaddy-wordpress/coblocks/issues) with CoBlocks.

**Comment by mxhassani** [comment]
@kavyagokul @vajrasar - [I've moved the issue to Coblocks](https://github.com/godaddy-wordpress/coblocks/issues/2495) but it appears to be a DotCom only issue. I am not able to replicate on self-hosted, but I am able to consistently replicate on DotCom.

**Comment by cuemarie** [comment]
Hey @mxhassani , as you noted on the other issue, the blocks you mentioned here are both Jetpack blocks, which seems to be the specific area where the conflict appears. I am able to replicate this on a Jetpack-connected self-hosted site with Jetpack blocks as well.

📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – Replicated
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- Animation from CoBlocks applied to Jetpack Blocks like the Slideshow result in the block being invisible on the live site, though still clickable.

**Screenshots/Recordings**

https://user-images.githubusercontent.com/27249804/231597576-75a9e3f0-7c36-462c-a1e5-898a02d6a1b0.mov

📌 ACTIONS
- Assigned to Apex 
- Transferred to Jetpack

📌 Message to Devs
- An issue was also raised in CoBlocks here: https://github.com/godaddy-wordpress/coblocks/issues/2495 but that was closed with a fix for a slightly different issue (animations not working on a block when it's the only one on the page)
- With that in mind, there might be more to look at specifically with Jetpack blocks here?

**Comment by jeherve** [comment]
I'll close this in favor of the issue in the Coblocks repo, where I've added a comment to discuss this conflict in more detail:
https://github.com/godaddy-wordpress/coblocks/issues/2495#issuecomment-1506698931
