### ISSUE TITLE
Remove docs from plugin beta branch builds

### ISSUE THREAD

**Issue by tbradsha** [Automattic/jetpack#30104]
Currently when a Live Branch beta build is created, we copy `docs/testing/testing-tips.md` into the plugin folder. Said file points users to `/projects/plugins/beta/docs/testing/testing-tips.md`, which doesn't exist. Can we remove the line in the build to keep builds clean?

https://github.com/Automattic/jetpack/blob/6a1d8254e1c9aa89513d7b4825671d2a7f24fad4/.github/workflows/build.yml#L200

Also, perhaps we should just chop the `docs/testing/testing-tips.md` file altogether if it's not being used.

**Comment by anomiex** [comment]
Looks like the link was broken in #27023, I guess the people involved there didn't realize the file was copied into the plugins.

But I agree there doesn't seem much benefit in keeping the file copied into the builds anymore, it has been a pointer since #18536 in 2021.
