### ISSUE TITLE
My Jetpack: change video-plays stats endpoint on WPCOM to skip Stats module requirement

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#30108]
We are using a WPCOM `v1.1` `/sites/$site/stats/video-plays` endpoint to fetch the stats related to VideoPress, but it has a check for the presence of the `Stats` module on the site being requested that is causing some troubles.

We tried to embed and enable `Stats` module inside the VideoPress plugin to pass the check (#29668), but it caused problematic side-effects (#29960) and we reverted it (#29966).

To solve it in another way, we are proposing to bypass the check entirely. VideoPress does not depends on the Stats module to collect the stats related to video consumption, so not having it is not a blocker for the stats to be collected (more info on this here: p1HpG7-lHv-p2#comment-62164).

The class responsible for handling the endpoint is `WPCOM_JSON_API_V1_1_Stats_Video_Plays_Endpoint`. The `callback` method on this class handles the request processing and uses the `$this->validate_stats_user( $site_id );` method to check for permissions.

The `validate_stats_user` method does the check for the `Stats` module and already supports a way to short-circuit the check, using the second parameter `$check_stats_module` (that is `true` by default).

So what we need to do is change the `$this->validate_stats_user( $site_id );` call to `$this->validate_stats_user( $site_id, false );` and we can by-pass the check.

My proposal is to make this bypass an optional one. We add a `check_stats_module` `GET` parameter that is set to `no` when the requester wants to bypass the check and defaults to `yes`. This way, every existing application keeps working the same way.

**Comment by renatoagds** [comment]
Implemented at: D108216-code

**Comment by lhkowalski** [comment]
Added my approval there. Nice work!

**Comment by renatoagds** [comment]
Done: r265288-wpcom
