### ISSUE TITLE
Social Media Icons Widget: YouTube channel URL change?

### ISSUE THREAD

**Issue by csonnek** [Automattic/jetpack#3011]
User reported in 2417058-t that in the plugin, the channel ID or user ID entered in the widget settings parses a link of:

`https://www.youtube.com/user/UserName`

Which should be changed to:

`https://www.youtube.com/c/UserName`

I tried to find some information on when this change occurred, but had no luck finding anything concrete online or in the YouTube development documentation.

**Comment by kraftbj** [comment]
See https://github.com/Automattic/jetpack/pull/3012#issuecomment-156910317 -- it doesn't look like to be a change to me, but various options depending on the setup of specific accounts.

**Comment by lancewillett** [comment]
See also 7286-wpcom

**Comment by lancewillett** [comment]
Committed: 4d581ed — seems fixed in my testing with both channels and bare usernames.
