### ISSUE TITLE
REST API: themes 'pre_get_posts' filter not working properly

### ISSUE THREAD

**Issue by bAmpT** [Automattic/jetpack#3013]
I have this code in my themes function.php:

function exclude_category( $query ) {
set_query_var('cat', '-444'); // v1
$query->set('cat', '-444' ); //  v2
} 
add_filter( 'pre_get_posts', 'exclude_category');

v1 doesn't filter out the category,  v2 doesn't filter out any category...
What is going on there? I tried to play around with the priority of the filter, but it has no effect.

**Comment by jeherve** [comment]
I think you meant to report this issue here:
https://github.com/WP-API/WP-API

This repository is home for the Jetpack plugin, not the WP REST API I'm afraid.

**Comment by bAmpT** [comment]
No, I'am talking about the jetpack plugin on my self hosted website...

**Comment by jeherve** [comment]
Could you let us know what you're trying to achieve? The code you posted above is used to customize the main WordPress query that is run in the loop of your active theme. I'm not sure I understand how it is related to Jetpack at the moment.

Are you having trouble with a specific Jetpack module?

**Comment by bAmpT** [comment]
Yes the Jetpack JSON API
https://public-api.wordpress.com/rest/v1.1/sites/xxx/posts/?category=111
I don't want posts with the category 444 to appear anywhere..

**Comment by bAmpT** [comment]
How can I customize the query of jetpack otherwise? What filter should I use?

**Comment by jeherve** [comment]
I see. I'm afraid you can't use filters like `pre_get_posts` to customize the response of Jetpack's REST API. That filter can only be used to customize the query on your own site.

If you'd like to customize a query made using Jetpack's REST API, you'll need to customize the query itself, using the parameters listed here:
https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/posts/

As you can see, the endpoint doesn't include any parameter allowing you to exclude a specific category from a query. You could, however, use the `category` parameter to query for posts belonging to a comma separated list of categories, excluding the category you want to exclude.

I hope this helps.

**Comment by bAmpT** [comment]
But that seems troublesome if you have many categories, isn't a catgory=cat1,-cat2 query parameter worth considering?

**Comment by jeherve** [comment]
> that seems troublesome if you have many categories

You should be able to generate that list of categories with another API call, using the `categories` endpoint:
https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/categories/

However, I can see how a parameter like `category__not_in` could be useful, much like in `WP_Query`. We'll consider adding that parameter to the posts endpoint.

Thanks for the feedback!
