### ISSUE TITLE
Enhancement: Add wp-admin toggle to disable Blaze feature

### ISSUE THREAD

**Issue by cyaburt** [Automattic/jetpack#30163]
### Impacted plugin

Jetpack

### What

Toggle Switch for Blaze

### How

Please create a toggle switch in the JetPack dashboard which can disable Blaze rather than having to update code to remove. Many of us manage multiple websites and we do not want our end users having this function.

**Comment by jeherve** [comment]
Thanks for the feedback. That's not something we're planning to implement at the moment, but I've linked to this issue in #29294, where we first discussed this toggle. If we ever implement this I'll update this issue to let you know.
