### ISSUE TITLE
Slideshow Block: Lazy loading causes the slideshow's height to be wrong

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/jetpack#30190]
### Impacted plugin

Jetpack

### Quick summary

Jetpack's slideshow block displays too tall when lazy loading is enabled.

### Steps to reproduce

1. Under Jetpack > Settings > Performance, enable Lazy Loading
2. Create a new post or page, and add several paragraphs of text - the goal is to make a sufficiently tall page to push the slideshow way out of view. 
3. Add a slideshow block and publish.
4. View the post/page on the front end, and scroll to where the slideshow is. 

### A clear and concise description of what you expected to happen.

I expected the slideshow's height to reflect the aspect ratio of the images inside of it. 

### What actually happened

Extra space was adding above and below the slideshow images; the slideshow appears to make each image's space square, even when they're not. 

![image](https://user-images.githubusercontent.com/177561/233125898-3ff2a670-1698-4315-8083-bf0119b82a3b.png)

Placing the slideshow further up the page, or turning off lazy loading, fixes the issue. 

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

### Logs or notes

Recreated with both the [Newspack theme](https://github.com/Automattic/newspack-theme/) on Atomic, and Twenty Twenty Three on a Jurassic Ninja site.

**Comment by ha-un** [comment]
Another case in: 6573625-zd-woothemes

**Comment by margaretschneider** [comment]
This appears to be improved since the 6.3 release, at least on one Newspack publisher site.

**Comment by jeherve** [comment]
Closing this since the Lazy Loading feature is no more.
