### ISSUE TITLE
Widget Visibility for "All taxonomy pages" and "All [custom tax] pages" not working

### ISSUE THREAD

**Issue by anmar** [Automattic/jetpack#3020]
The widget visibility option for taxonomies is not working in two cases:
1. The  "Taxonomy" => "All taxonomy pages" entry.
2. The "Taxonomy" => "All [custom tax] pages" entry in custom taxonomies

Conditions for specific taxonomy terms work ok though.

Related to #2170.

**Comment by jeherve** [comment]
Fixed in #6326
