### ISSUE TITLE
Deleting Jetpack plugin via Plugins page deletes database entries used by plugins using Jetpack connection

### ISSUE THREAD

**Issue by jessepearson** [Automattic/jetpack#30243]
### Impacted plugin

Jetpack

### Quick summary

If another plugin is using the Jetpack connection, like Woo Payments, and Jetpack is Deactivated and then Deleted from the WordPress Plugins page, database entries related to the connection are removed, as well.

In my testing, the merchant would be able to go through the WCPay setup process again to relink their account, but they may not realize they are disconnected from WCPay for hours, days, etc.

Is there something other developers should be doing to prevent this from happening?

### Steps to reproduce

1. Create a new Jurassic Ninja site with Jetpack, WooCommerce, WooCommerce Payments, and WCPay Dev Tools installed.
2. Go to WCPay Dev Tools and disable the _Enable API request redirection_ setting.
3. Click on _Payments_ in the main WordPress navigation.
4. Proceed through onboarding a new account.
5. Once onboarded go to the Plugins page in WordPress.
6. Deactivate Jetpack.
7. Delete Jetpack.
8. Go to WCPay Dev Tools and click to _clear_ the account data.
9. Once cleared, you will see there is no more Jetpack connection.

### A clear and concise description of what you expected to happen.

I would expect that connection database entries would be left for the remaining plugins using them to use.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by jeherve** [comment]
Thanks for the report. This is similar to #28540, so I'll close this issue as duplicate.

Related: #28870
