### ISSUE TITLE
Invalid Facebook language codes

### ISSUE THREAD

**Issue by pento** [Automattic/jetpack#3026]
As much as it pains me to acknowledge this, Facebook doesn't support `en_AU` (or `en_CA`, for that matter) as language codes in OG tags.

For example, if you Fetch Fresh Scrape Information in [this Facebook OG Debug Tool link](https://developers.facebook.com/tools/debug/og/object?q=http%3A%2F%2Fpento.net%2F2015%2F11%2F17%2Freplacing-rdio%2F), you'll get the error:

> Object at URL 'http://pento.net/2015/11/17/replacing-rdio/' of type 'article' is invalid because the given value 'en_au' for property 'og:locale:locale' could not be parsed as type 'enum'.

The full list of locales that Facebook supports is here: https://www.facebook.com/translations/FacebookLocales.xml

**Comment by kraftbj** [comment]
Being done here https://github.com/Automattic/jetpack/blob/master/functions.opengraph.php#L193
https://github.com/Automattic/jetpack/blob/master/locales.php#L557
Vs https://glotpress.trac.wordpress.org/browser/trunk/locales/locales.php#L572

**Comment by jeherve** [comment]
Related: #2791, #2821, #2707

**Comment by jeherve** [comment]
Fixed for the Like Box in #3160

**Comment by richardmtl** [comment]
Related: https://github.com/Automattic/jetpack/pull/3347

**Comment by jeherve** [comment]
Fixed in #3160.

Better fallbacks should still be implemented, as explained in #5468
