### ISSUE TITLE
Likes count is misaligned in the posts list on mobile

### ISSUE THREAD

**Issue by pento** [Automattic/jetpack#3027]
The out-of-place (and strangely highlighted) "1" in the post details I'd the like count, but it didn't fit in with the new post details style on mobile.

![screenshot_20151117-235226](https://cloud.githubusercontent.com/assets/352291/11211933/ff29f964-8d86-11e5-9fc4-dd7612d324b0.png)

**Comment by kraftbj** [comment]
The highlight I thought was fixed, at least at full width. @jeffgolenski something I can throw onto your plate?

**Comment by kraftbj** [comment]
Ah, bet the responsive list table stuff tripped us up. The highlight is copying the comment bubble on full. 
![image](https://cloud.githubusercontent.com/assets/88897/11212407/39541700-8cfb-11e5-98f1-a6a3ee4f3340.png)

**Comment by pento** [comment]
This goes away when I updated Jetpack, I guess it was just my janky old version.
