### ISSUE TITLE
Jetpack Plugin: Swap to using Plans\Current_Plan for plan checks

### ISSUE THREAD

**Issue by pablinos** [Automattic/jetpack#30288]
We started doing making the change to using the Plans package in [this PR](https://github.com/Automattic/jetpack/pull/23789). We're already using it for our plan checks in Jetpack Social, and have implemented [the heartbeat to refresh the plan data](https://github.com/Automattic/jetpack/blob/d8e48e7e9ec0c05b631a2ccd847de3b11b9dcc5f/projects/plugins/social/src/class-jetpack-social.php#L192) but it might be good to implement Configure for the package, so this is standardised.

Initially, it would be good to retire Jetpack_Plan, so the Jetpack plugin is using the package.

After that, we should migrate the other plugins to use it too. [VideoPress](https://github.com/Automattic/jetpack/blob/d8e48e7e9ec0c05b631a2ccd847de3b11b9dcc5f/projects/packages/videopress/src/class-options.php#L57) and [Protect](https://github.com/Automattic/jetpack/blob/d8e48e7e9ec0c05b631a2ccd847de3b11b9dcc5f/projects/plugins/protect/src/class-plan.php#L101) look to be already using it, but Search is using their own mechanism and I'm not sure about Backup etc. but we can create follow-up tasks for each plugin.

**Comment by jeherve** [comment]
Not quite fixed yet, we still need #31213.

**Comment by jeherve** [comment]
This should now be fixed.
