### ISSUE TITLE
Payments block: cannot change currency

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#30299]
### Impacted plugin

Jetpack

### Quick summary

When using the payments block, changing currency breaks the block.

### Steps to reproduce

1. On Simple site (didn't check Atomic/Jetpack sites)
2. In the page editor (could happen also in other editors)
3. Add payments block
4. Pick donations
5. In the block toolbar, change currency to any other from the default USD
    <img width="688" alt="Screenshot 2023-04-26 at 11 40 49" src="https://user-images.githubusercontent.com/87168/234521306-266753a6-5fc3-4b81-b306-fbdaf6301d1b.png">
6. Observe crash and error in console

<img width="597" alt="Screenshot 2023-04-26 at 11 40 39" src="https://user-images.githubusercontent.com/87168/234521358-1ce6fe79-0323-40dd-8447-2e884f8ab3c3.png">

https://user-images.githubusercontent.com/87168/234521391-a9098b08-c2d2-490a-90f1-60a099d0891f.mov

<img width="824" alt="image" src="https://user-images.githubusercontent.com/87168/234521646-1107b8c8-32ac-4deb-b2d8-643f34d80f48.png">

Not sure if this warning is related, but its in the console:

<img width="847" alt="image" src="https://user-images.githubusercontent.com/87168/234521697-71c825f7-0d33-4715-8324-50c48cd51feb.png">

### A clear and concise description of what you expected to happen.

Should be able to change currency.

In fact, since I'm in Lithuania, I expected the default pre-selected currency to be Euros.They should

### What actually happened

Block crashed.

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

- Chrome browser

**Comment by simison** [comment]
Pinged Team Gold in p81rsd-1hl-p2/#comment-1437

**Comment by karenroldan** [comment]
📌 REPRODUCTION RESULTS

- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO

**Steps to reproduce:** exactly as described above

### Atomic

The Donations Form is not loading at all from the Payments block.

![Screenshot 2023-04-26 at 11 18 33](https://user-images.githubusercontent.com/67279475/234531669-4893dea0-2073-4bcc-8daa-d1121a1e7bfe.png)

However, when you add the Donations Form block directly, you can replicate the issue where you cannot change the currency and the block will throw an error. 

📌 ACTIONS
- Escalated here: p1682501502607509-slack-C02FMH4G8

**Comment by dsas** [comment]
On dev I get this output when changing currency:
```
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
Amount@webpack-internal:///./extensions/blocks/donations/amount.js:28:7
div
div
Tab@webpack-internal:///./extensions/blocks/donations/tab.js:27:7
div
div
div
Tabs@webpack-internal:///./extensions/blocks/donations/tabs.js:27:7
Edit@webpack-internal:///./extensions/blocks/donations/edit.js:35:7
TweetDivider@webpack-internal:///../../js-packages/publicize-components/src/components/twitter/tweet-divider.js:32:1
```

Even without changing currency there are repeated calls to the `/wpcom/v2/memberships/status` endpoint, which must come from the donations edit block.

https://github.com/Automattic/jetpack/blob/437dd78efaa59d3aee1fcf094eb0d8fdbc94e3e9/projects/plugins/jetpack/extensions/blocks/donations/edit.js#L83-L87

**Comment by romarioraffington** [comment]
Unassigning this from me to focus on higher priority tasks. @millerf, I see that this was assigned to me by you, let me know if this task is more urgent than the other tasks I'm currently working on

**Comment by susanjanec** [comment]
I just got a chat (37046375-hc) where the user was getting this error on an Atomic site. They were trying to add the Donations block to their posts. 

Provided them to create a reusable block to a donate page to add to their posts as a workaround for now.

**Comment by janmckell** [comment]
- [ ] 6215710-zd-woothemes

Issue reported here.

**Comment by n3f** [comment]
For those HE's leaving comments, the issue should be resolved shortly, but there is an immediate workaround. Opening the gutenberg code editor and immediately exiting it should resolve the issue too...
