### ISSUE TITLE
Payments block: Stripe connection button visually broken

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#30300]
### Impacted plugin

Jetpack

### Quick summary

At least in Lettre theme, the Stripe banner has visually broken "connect" button:

![image](https://user-images.githubusercontent.com/87168/234529285-49dcd631-ff58-42cc-af08-c5f299f301ad.png)

### Steps to reproduce

1. on site with stripe disconnected, and Lettre theme
1. add payments block in the page editor
1. Note how stripe banner is broken

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

- Chrome

I've pinged Team Gold in p81Rsd-1hl-p2#comment-1436

**Comment by romarioraffington** [comment]
Hey @simison,

I was unable to reproduce this bug on my test site. Can you share the test site you were able to reproduce this on?

<img width="913" alt="Screenshot 2023-04-26 at 5 00 54 PM" src="https://user-images.githubusercontent.com/7076981/234712796-12d404da-9aac-435d-9627-737803deb82d.png">

**Comment by romarioraffington** [comment]
It appears that the issue only surfaces when the block is adding to the header

<img width="514" alt="Screenshot 2023-04-26 at 5 12 14 PM" src="https://user-images.githubusercontent.com/7076981/234714399-f1732325-20ef-4d18-a4cb-5d952945d344.png">
