### ISSUE TITLE
JP Forms - Ellipsis menu on the dashboard not working

### ISSUE THREAD

**Issue by ice9js** [Automattic/jetpack#30351]
### Impacted plugin

Jetpack

### Quick summary

During the review of #30213 we noticed the ellipsis menu on the response list in the new JP Forms dashboard isn't working as expected anymore, but it wasn't related to the PR itself as the same issue happens on `trunk` now. I'm not entirely sure where the regression might've been introduced.

### Steps to reproduce

Enable the forms package and new dashboard with:

```
add_filter( 'jetpack_contact_form_use_package', '__return_true' );
add_filter( 'jetpack_forms_dashboard_enable', '__return_true' );
```

1. Go to `admin.php?page=jetpack-forms`. If you don't have any responses, create a post with a contact form and add some first.
2. It seems the ellipsis menu in response list items only shows on certain screen sizes, between 660px and 1024px width, so make sure to adjust your view so you can see it.
3. Click on the ellipsis menu.

### A clear and concise description of what you expected to happen.

When you toggle the ellipsis menu, the menu should show.

### What actually happened

Instead of the ellipsis menu being shown, you'll go to the response view. When you go back to the list, then you can see the ellipsis menu.

### Impact

One

### Available workarounds?

Yes, easy to implement

**Comment by digitalwaveride** [comment]
This was fixed via https://github.com/Automattic/jetpack/pull/30409 .
