### ISSUE TITLE
Carousel: Ampersands in title and description failed duplication check

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#3036]
Carousel usually checks to see if the description and the title are the same. If so, it does not display the title.

If there is an ampersand is the duplicated text and description, we still display both. I couldn't quite track where the failure is occurring, but https://github.com/Automattic/jetpack/blob/3.8.0/modules/carousel/jetpack-carousel.js#L1090 is on my watchlist.

I don't think it is actually related to #2401, but same part of the neighborhood. Marking as a Good First Bug since it very well may be pretty direct for someone more proficient in JavaScript.

2418231-t

**Comment by NathanLawrence** [comment]
I have a sneaking suspicion that this has to do with the way title and description escape ampersands. I'll look into it further.
