### ISSUE TITLE
Allow markdown in "Post by Email"

### ISSUE THREAD

**Issue by claudiosmweb** [Automattic/jetpack#3039]
One of our users requested this feature.

Adding a new command:

```
[markdown on] (default would be off)
```

**Comment by kraftbj** [comment]
@claudiosmweb Did you test that Markdown didn't work? As of #164, it did and there hasn't been changed that I know about have touched that (with #454 noted as a `wontfix` known issue).

**Comment by claudiosmweb** [comment]
@kraftbj I just tested on wp.com and didn't work.

**Comment by claudiosmweb** [comment]
Closing because we need to look on wp.com.
