### ISSUE TITLE
Enhancement: [Boost]. Promote Jetpack Boost from within the Performance tab.

### ISSUE THREAD

**Issue by ecairol** [Automattic/jetpack#30429]
### Impacted plugin

Boost

### What

Add a link to Jetpack Boost from within the Performance tab

### How

To increase awareness and attract potential users, we should add a link to the Jetpack > Performance tab letting the users know that there are additional options like Critical CSS and Defer JS in Jetpack Boost.

<img width="1101" alt="Screen Shot 2023-05-03 at 10 42 56" src="https://user-images.githubusercontent.com/1821060/235984144-fa66cbab-d2ae-4f40-819d-7fef3e283d33.png">

**Comment by haqadn** [comment]
A prompt to install Boost was added to the performance tab.
