### ISSUE TITLE
My Jetpack: Introduce better approach to handle data update

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#30423]
We have been adding reloads across the application to fetch new data.

Right now, we do this at these places:

- Installing/Activating plugins/modules.
- Activating a license.
- Installing/Activating standalone plugins.

Probably we need to introduce endpoints to fetch new data.

**Comment by renatoagds** [comment]
Moving to on hold.

**Comment by dhasilva** [comment]
The endpoints already exist on `my-jetpack/v1/site/products` (`REST_API_SITE_PRODUCTS_ENDPOINT`) and `REST_API_SITE_PRODUCTS_ENDPOINT/<product-slug>`.

What needs to be done here is to check how to use the store to trigger the data re-fetch at the points where we are refreshing the page.
If at some point it is not possible to know which product needs to be updated then a second action needs to be added to call the general products endpoint. This would involve some refactoring to invalidate the state of all individual products.

**Comment by renatoagds** [comment]
Thinking better about this one, we should check if without reloading, we can introduce the new menu item in WP sidebar. I forgot about this UX requirement before creating the issue.

**Comment by dhasilva** [comment]
Stale issue. Jetpack Martech is handling My Jetpack now.
