### ISSUE TITLE
Jetpack Disconnect Weirdness

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#3045]
I get this screen after disconnection Jetpack.
<img width="909" alt="screen shot 2015-11-19 at 3 41 14 pm" src="https://cloud.githubusercontent.com/assets/115071/11287927/2b3872bc-8ed4-11e5-919f-951efb02c8b1.png">

The white text on white says 
You are currently running a development version of Jetpack. Submit your feedback

Hope that helps with the debugging. 

CC @jeffgolenski

**Comment by dereksmart** [comment]
@enejb I can't reproduce this.  Which browser/branch are you running?  If you can get it to happen again, can you paste the HTML structure from the inspector?  Thanks!

**Comment by eliorivero** [comment]
Another report at p7bje6-71-p2

**Comment by enejb** [comment]
Just saw this message again. To reproduce it: disconnect jetpack while running a beta version of the plugin. 
the message says 
> You are currently running a development version of Jetpack. Submit your feedback

**Comment by jeherve** [comment]
Closing this, as the connection notices have been redesigned.
