### ISSUE TITLE
Publicize: add Bluesky

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#30460]
It would be nice to add Publicize (aka Jetpack Social) support for [Bluesky](https://blueskyweb.xyz/), since the platform is getting more and more popular and already offers developer tools to publish there.

Related: #7790

**Comment by Ipstenu** [comment]
Does this include adding it to the sharing or should that be a separate ticket?

**Comment by jeherve** [comment]
@Ipstenu That would be separate, but you're right that we should add both. I created #32708 to keep track of this.

**Comment by formosattic** [comment]
+1 6748425-zd-a8c

**Comment by supernovia** [comment]
We have a request for Bluesky (and Threads) here:
https://twitter.com/jonathanwthomas/status/1720491100635377779

**Comment by vinnykaur** [comment]
One more here: 7252862-zd-a8c

**Comment by kpossibles** [comment]
Commenting to request for Bluesky! It would be super helpful since Twitter share was discontinued last year.

**Comment by tehjaymo** [comment]
Co-signed. Bluesky sharing would be great.

**Comment by salromano** [comment]
Co-signed. There's no other good auto-posting solution for Bluesky yet, so this would be a great addition.

**Comment by eduardozulian** [comment]
I'm adding another +1 here. With Twitter/X currently banned in Brazil, [many people are moving to Bluesky](https://www.theverge.com/2024/8/30/24232561/brazil-x-ban-sending-people-bluesky).

**Comment by EmpressEm** [comment]
+1 for Jetpack Social Bluesky connection / integration.

**Comment by mbnn** [comment]
+1 Please add support for Bluesky social 🙏

**Comment by pehaa** [comment]
+1 [via X request](https://twitter.com/ShoshinZen/status/1843634526838501833)

**Comment by ldaggett-godaddy** [comment]
+1 ESPECIALLY now.

**Comment by tehjaymo** [comment]
I actually see this in my Jetpack Social connections page already. It connected fine. No idea why this ticket wasn't updated

![Image](https://github.com/user-attachments/assets/2c81a9a5-0b5c-4365-8692-1aca7fee3990)

**Comment by ldaggett-godaddy** [comment]
Oh, thank you! I will have to see if I am missing an update with JetPack or soemthing.

**Comment by jeherve** [comment]
This issue can indeed be closed. We added Bluesky support in yesterday's release!

**Comment by salromano** [comment]
Is there a rollout period for this? I'm not seeing Bluesky under connections at all yet unfortunately.

**Comment by ldaggett-godaddy** [comment]
I had to manually update it, and it's there now. Yay and thank you!

**Comment by jeherve** [comment]
> Is there a rollout period for this? I'm not seeing Bluesky under connections at all yet unfortunately.

If you use the latest version of the Jetpack plugin, you should be able to connect your Bluesky account right from the post editor, or from your site's Social settings under Jetpack > Settings > Sharing.

**Comment by salromano** [comment]
Thanks, I got it working now. My Jetpack plugin wasn't showing that an update was available, so I had to do it manually.

Is there any way to have the featured image actually attach to the Bluesky post, like how Jetpack used to operate with Twitter?

**Comment by jeherve** [comment]
> Is there any way to have the featured image actually attach to the Bluesky post, like how Jetpack used to operate with Twitter?

@spsiddarthan Is that something you looked at when building the Bluesky implementation? Would that be an option?

**Comment by tehjaymo** [comment]
Second this! Just tried this for the first time. Auto publicise is just putting the raw link into the bluesky post, oEmbed/rich content isn't showing up.

**Comment by agk4444** [comment]
Also, hashtags are not working in Blue Sky publicize. Looks like Blue Sky 'Facets' need to be adapted

**Comment by jeherve** [comment]
> Auto publicise is just putting the raw link into the bluesky post, oEmbed/rich content isn't showing up.

I created this issue to keep track of the problem:

https://github.com/Automattic/jetpack/issues/40244

We can continue the conversation there.

> hashtags are not working in Blue Sky publicize

That's a good point. I created #40243 to keep track of that.
