### ISSUE TITLE
Feature Request: sharing button addition "Truth Social"

### ISSUE THREAD

**Issue by sophiegyo** [Automattic/jetpack#30476]
### Impacted plugin

Jetpack

### What

User requested a sharing button (not an automatic social share AFAIK) for the 'social media' website 'Truth Social'. Thread: https://wordpress.com/forums/topic/truth-social/?view=all

**Comment by anomiex** [comment]
Absent anything happening here, https://jetpack.com/support/sharing/ has instructions on adding buttons for additional services in the blog's wp-admin (look for "How do I create my own custom sharing buttons?" near the end).

**Comment by jeherve** [comment]
Given how popular the service is, I'll mark this issue as "won't fix". One can add their own custom sharing button instead, as @anomiex mentioned above.
