### ISSUE TITLE
Domain mismatch in 'change of domain' admin notice

### ISSUE THREAD

**Issue by ollietreend** [Automattic/jetpack#3047]
Hi,

I've just setup a development version of a live website, and have noticed that the domain names are the wrong way around in the 'change of domain' admin notice which is displayed.

In this example, the existing domain is `existing-domain.org.uk` however the CTA link in the admin notice says "`existing-domain.org.uk` is **now** my domain".

Whereas for the new domain, the CTA link reads "`new-domain.dev` is **still** my domain".

These links appear to be the wrong way around. I was expecting to see "`existing-domain.org.uk` is **still** my domain" rather than "**now**".

<img alt="Jetpack change of domain" src="https://cloud.githubusercontent.com/assets/7735945/11297857/0fc6e244-8f73-11e5-8a1b-fd21571eb9bd.png">

This is confusing, since it is unclear which action the link will take. I don't know whether to trust the domain name which is used in the link, or the wording around it.

**Comment by kraftbj** [comment]
We've removed this prompt in the in-beta 3.8.1 since it is throwing a lot of unexpected situations into the mix, so closing as invalid on those grounds.

If/when it returns, the prompts will probably be completely rewritten. That said, looks to be the wrong language as shown.
