### ISSUE TITLE
Responsive videos display Warning

### ISSUE THREAD

**Issue by vladolaru** [Automattic/jetpack#3048]
I've had several of our customers that use one of our themes that activates responsive videos, report back that after the latest Jetpack update (3.8.0) they started seeing this on their sites (multiple times):

`<b>Warning</b>:  Missing argument 2 for jetpack_responsive_videos_maybe_wrap_oembed() in <b>[...]/public_html/wp-content/plugins/jetpack/modules/theme-tools/responsive-videos.php</b> on line <b>53</b><br />`

From looking at things it seems that there is a weird case when the jetpack_responsive_videos_maybe_wrap_oembed() function doesn't receive the second parameter ($url).

I think it would be best to have that parameter default to null so we would be a little safer, considering that the function logic doesn't even execute if $url is empty.

Thanks,
Vlad
PixelGrade

**Comment by kraftbj** [comment]
Thanks for the report Vlad. That sounds like a reasonable solution. @michaeldcain IIRC, this is your wheelhouse, right?

**Comment by michaeldcain** [comment]
on it.

**Comment by Vuzz74** [comment]
Hello Michael, 
how does your work go on? My blog spotbehind.com still shows up the errors although I tried Vlad's tip - look at http://www.spotbehind.com/page/2/. Is there any change to roll back Jetpack to the former version?

**Comment by vladolaru** [comment]
@michaeldcain How are things going? I've managed to track down some specifics regarding when the $url came in null:
- when using the [audio] shortcode like this
```
[audio http://silk.dev/wp-content/uploads/2012/07/originaldixielandjazzbandwithalbernard-stlouisblues.mp3]
```

**Comment by richardmtl** [comment]
This came up again in 2411504-t

**Comment by michaeldcain** [comment]
Sorry, lost track of it with other work. I wasn't able to reproduce the warning in my own environment, so it'd be helpful if you could take a look, @vladolaru.

**Comment by danjjohnson** [comment]
Had a report of this warning again in 1277637-zen

Looks like the fix made here: https://github.com/Automattic/jetpack/commit/fd8615773ca7fe3f888eed8e3e90834a21a9bf35#diff-83570ff973606769aa818c6f920db7bb

... was subsequently reverted here: https://github.com/Automattic/jetpack/commit/ab7f2e0d3619bfc483723727bb427656e1581898#diff-83570ff973606769aa818c6f920db7bb

Was that intentional? If not, can we get it fixed again?
