### ISSUE TITLE
Dashboard: add a link to the Activity Log

### ISSUE THREAD

**Issue by yolih** [Automattic/jetpack#30490]
### Impacted plugin

Jetpack

### What

I would like a button or link to the Jetpack Activity Log

### How

**This request is specifically for the Jetpack dashboard for self-hosted WordPress sites.**

The Jetpack Activity Log for a self-hosted site is located on a cache site hosted on WordPress.com. For users that manage a large quantity of WordPress sites (e.g. many WPVIP customers) it is cumbersome for them to sort through their connected sites via the WordPress.com admin.
It would be beneficial if users could directly access the Jetpack Activity Log for a self-hosted site by clicking on a button located in the Jetpack Dashboard of the self-hosted site. 

Thank you! Let me know if I can be of further help for this request.

cc: @JenSwish

**Comment by jeherve** [comment]
Related: #20948.

**Comment by jeherve** [comment]
This was implemented in #34174.
