### ISSUE TITLE
Allow Granular Control of Custom Content Types on Settings > Writing

### ISSUE THREAD

**Issue by mrwweb** [Automattic/jetpack#3050]
Splitting off from #3044, my expected behavior for the Custom CPT module is the following:

> - Disabling Custom Content Types Module unregisters all CPTs.
> - Settings > Writing allows for granular control of each CPTs, add_theme_support() or no.
> - `add_theme_support( 'jetpack-{cpt}' )` defaults a CPT to checked on Settings > Writing the first time the module is enabled or Jetpack is installed.

The use-case for this expected behavior is the following:

> If there are plans to add more post types to the Custom Content Types Module in the future, I think it's more likely that you'll have people who want one theme-supported post type or another but not all.

Currently, Settings > Writing looks like this:

![image](https://cloud.githubusercontent.com/assets/1238696/11308956/e7b431be-8f75-11e5-919e-9a85507912b6.png)

I'd propose that:
1. ALL post types have check boxes to enable/disable
2. Theme-supported CPTs are enabled by default when A) Jetpack is enabled the first time or B) The Custom Content Module is enabled the first time (which is usually the same as A, but not always)
3. Theme-supported CPT checkboxes on Settings > Writing have a message explaining that the theme supports the CPT (like it does now). The wording here matters quite a bit I think, and I don't have any great suggestions. ("Your theme supports the design and layout of this content type."?)
4. Non-theme-supported CPTs are disabled by default.

One edge-case is what happens when a new theme is activated. Does that essentially reset the post types that are supported? What if someone is using that type already? What if the theme supported a different type or doesn't support a previously-supported one?

Maybe a pointer should be generated for the new Content Type's menu item the first time it's enabled and a site-wide info message should be generated should one [with posts?] be removed.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if this is brought up again or if a patch is submitted.
