### ISSUE TITLE
Latex Path Not Specified

### ISSUE THREAD

**Issue by gwwar** [Automattic/jetpack#3052]
When embedding latex into posts, the following notice `latex path not specified` appears.

To reproduce:
Navigate to the [Calypso WordPress.com editor](https://wordpress.com/post)
Select a site if prompted.
In the html tab, type in:
```
$latex i\hbar\frac{\partial}{\partial t}\left|\Psi(t)\right&gt;=H\left|\Psi(t)\right&gt;$

$latex (82,000)_{10}$
```
Publish the post.

Expected: Pretty formulas appear
Actual:
![latex path not specified](https://cloud.githubusercontent.com/assets/1270189/11315722/dc553cec-8fab-11e5-989d-10a606dae414.png)

Possibly fixed by #2685

**Comment by shawnajean** [comment]
I have several users reporting similar errors in the WP.com forums:

http://en.forums.wordpress.com/topic/latex-path-not-specified-errors-1

The errors are inconsistent - it seems due to caching.

**Comment by tsaomao** [comment]
Emptying out all caches (DNS, browser, proxy, etc., OS reboot) seemed to make the error show up consistently for me.

**Comment by tsaomao** [comment]
A very small amount more of additional information (comparing QuickLatex plugin to Jetpack's Beautiful Mathematics component) on the Wordpress.org support forum here: https://wordpress.org/support/topic/latex-path-not-specified-errors?replies=1#post-7685268

**Comment by richardmtl** [comment]
Closing; this was fixed on the WordPress.com side.
