### ISSUE TITLE
WP.org !== WordPress.org

### ISSUE THREAD

**Issue by pento** [Automattic/jetpack#3053]
This is probably the most minor bug I've ever reported, but there are [a couple of comments](https://github.com/Automattic/jetpack/search?utf8=%E2%9C%93&q=%22wp.org%22&type=Code) that reference WP.org, a URL that doesn't actually point to WordPress.org.

**Comment by kraftbj** [comment]
w.org is the way to go. @pento Keep trying, I'm sure there something more minor out there.
