### ISSUE TITLE
Update Jetpack AI My Jetpack interstitial

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#30553]
Add a My Jetpack interstitial to enable the AI features, starting with the current block

#30543 introduced the skeleton for the product interstitial but we still need to make the PHP product class be correct.
Skeleton introduced:
![image](https://github.com/Automattic/jetpack/assets/16329583/955f12d5-1fb4-4a69-9b24-8fe5377d4497)

* A new image is needed
* New marketing highlight are needed
* A new real product in the backend is needed (task https://github.com/Automattic/jetpack/issues/30723)

**Comment by keoshi** [comment]
Here's a quick mock of what it could look like:

![image](https://github.com/Automattic/jetpack/assets/390760/df089304-5a14-4539-9153-c0508ced5a54)

gG1smMHbNGas0qwP9y6RwK-fi-3660_12984

**Comment by nunyvega** [comment]
Two notes on this:
1- Not sure if we should use the install word here, since this is enabling a feature without installing an extra plugin
2- The block is Jetpack AI Assistant, but the plan is Jetpack AI, so maybe we should talk about Jetpack AI in the interstitial

**Comment by ederrengifo** [comment]
In the past, we used "Add" which I think is more generic, but with the latest update, we changed to "install" for all the standalone which is more accurate. If that's the new logic, maybe we can use "Get" for this one? That could help to reduce some potential friction and we are aligned with the latest update for My Jetpack. Here is a preview with the other change included:

![Image](https://github.com/Automattic/jetpack/assets/10525007/b152b272-8033-4395-84ca-e892e5a0bd6c)

**Comment by renatoagds** [comment]
> Not sure if we should use the install word here, since this is enabling a feature without installing an extra plugin

We will install `Jetpack` plugin in this case, so I think we should keep it. Since the user could be using only some standalone plugin and doesn't have the core plugin.

**Comment by renatoagds** [comment]
Closing since the Interstitial was implemented. Let's jump, test and provide new issues with feedback.

**Comment by nunyvega** [comment]
Reopening as the interstitial needs to be updated with cc @renatoagds 

* Features
* Background images
* Front image
