### ISSUE TITLE
Plugin banner: create rtl version

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3055]
It would be nice to create an RTL version of our plugin banner, as explained here:
https://make.wordpress.org/plugins/2015/11/11/making-better-banners-for-your-plugins/

It seems to me that it would only be a matter of moving the Jetpack logo a bit, to avoid that kind of overlay:
https://he.wordpress.org/plugins/jetpack/

cc @jeffgolenski

**Comment by beaulebens** [comment]
I'm not sure this is relevant any more, now that the main banner has been changed to an illustration, which doesn't really have a specific orientation?

**Comment by jeherve** [comment]
That's a very good point. Closing.
