### ISSUE TITLE
Adding Subtitles to a 'regular' video block causes Block Recovery

### ISSUE THREAD

**Issue by Ipstenu** [Automattic/jetpack#30571]
### Impacted plugin

Jetpack

### Quick summary

With https://jetpack.com/support/jetpack-blocks/ activated, I can no longer include subtitles

### Steps to reproduce

1. Create a post with a video (remote or local, doesn't matter)
2. Upload VTT file to WordPress
3. Edit the block to add text tracks 
4. Save the post
5. Refresh the editor

### A clear and concise description of what you expected to happen.

Video should have subtitles. Yay!

### What actually happened

Block Validation Fails :( 

![Screenshot 2023-05-09 at 3 41 06 PM](https://github.com/Automattic/jetpack/assets/807903/6df53c8a-538b-4226-85cc-9592acc5b4d1)

```
Block validation: Block validation failed for `core/video` (Object).

Content generated by `save` function:

<figure class="wp-block-video"><video controls src="https://example.com/video.mp4"></video></figure>

Content retrieved from post body:

<figure class="wp-block-video"><video controls src="https://example.com/video.mp4"><track src="https://example.local/wp-content/uploads/2023/05/video.vtt" label="English" srclang="en" kind="subtitles"/></video></figure>
```

I reproduced this on a clean site without any plugin except Jetpack, as well as with a bunch more plugins, different themes, ec.

The only fix is to disable the blocks. :( 

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by jeherve** [comment]
cc @Automattic/jetpack-agora Do you think you could take a look?

Thank you!
