### ISSUE TITLE
VideoPress: Add a VideoPress video v6 block when user drops video file in the editor

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#30584]
Currently dropping a file creates a `core/video` block even if v6 is available, immediately showing a prompt for conversion.

p1683658923915969-slack-C02LT75D3

**Comment by oskosk** [comment]
@dhasilva I think this one was addressed alrady, no ?

**Comment by oskosk** [comment]
Yup, fixed in #32084 it appears

**Comment by dhasilva** [comment]
Yes. I edited the PR description now to point to this issue for consistency.
