### ISSUE TITLE
My Jetpack: fix offline mode experience

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#30629]
My Jetpack does not recognize Offline Mode, and asks users to connect:

![Image](https://user-images.githubusercontent.com/16329583/237646521-3a4664a2-2525-446f-8f2d-7c552a0e5928.png)

We could do the following:

- Replace the “Connect your site” top notice with the “Offline Mode” one, similar to the one we have in Jetpack.

- Instead of “Jetpack is not connected”, we could say “Connection is not available in [Offline Mode](https://href.li/?https://jetpack.com/support/development-mode/)“.

Reported by @sergeymitr 
More context in p9dueE-7eT-p2

**Comment by nunyvega** [comment]
@vianasw for awareness

**Comment by jeherve** [comment]
This should be fixed as of #35807.
