### ISSUE TITLE
AI Assistant: show predefs when the user already received the answer

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#30632]
Currently, we show this whenever a user already received a reply:

![Image](https://user-images.githubusercontent.com/16329583/237675393-6f0d016a-65ad-4b47-bdb9-30146c417869.png)

We should also show the predefs that can help improve the answer (change tone, summarize,etc)

**Comment by retrofox** [comment]
I'll add the `Tone` dropdown.
