### ISSUE TITLE
Jetpack seems to ignore WP_PLUGIN_DIR

### ISSUE THREAD

**Issue by gouch** [Automattic/jetpack#3064]
I've set an alternate directory for plugins using the WP_PLUGIN_DIR constant. Jetpack seems to ignore that and instead tries to load resources from the default wp-content/plugins/ directory.

![jetpack-plugins-path](https://cloud.githubusercontent.com/assets/38445/11381160/65a202e0-92c8-11e5-9133-dc89027b9e8d.png)

**Comment by kraftbj** [comment]
Noting that twentyfifteen is enqueued using `plugins_url`: https://github.com/Automattic/jetpack/blob/master/modules/theme-tools/compat/twentyfifteen.php#L25

as is genericons: https://github.com/Automattic/jetpack/blob/master/_inc/genericons.php#L11

Haven't checked the others. 

`plugins_url` uses the `WP_PLUGIN_URL` constant, which by default is `WP_CONTENT_URL . '/plugins`.

@gouch Could you provide the steps/code/etc you used to define `WP_PLUGIN_DIR` and in which files, etc, in order for us to attempt to duplicate?

**Comment by gouch** [comment]
Steps for bug reproduction:

1. Brand new WordPress install
2. Add `define('WP_PLUGIN_DIR', dirname(__FILE__) . '/wp-content/plugins-custom');` as first line in wp-config.php
3. Activate the Jetpack plugin
4. Activates successfully, but admin pages generate 404 network errors because of Jetpack-related requests to wp-content/plugins

**Comment by kraftbj** [comment]
I'm still tracking it, but I believe this is a core bug.

Add this to a functionality plugin:
```
add_action('admin_head', 'bk_test_wheremyplugins');
function bk_test_wheremyplugins(){
echo "<h1>" . plugins_url() . "</h1><br><h2>" . WP_PLUGIN_URL . "</h2>";
}
```

Expected: `/wp-content/plugins-custom` mentioned in both.
Actual: `/wp-content/plugins`.

I'll track it to an existing ticket and/or try to isolate the issue and create one shortly. Will update this issue with a link, but closing as it isn't a Jetpack bug.

**Comment by kraftbj** [comment]
Actually, I misspoke. There are two constants.

`WP_PLUGIN_DIR` changes the file system directly.
Separately, the `WP_PLUGIN_URL` is needed to set the URL, if the default URL doesn't point to the WP_PLUGIN_DIR. Once you set the `WP_PLUGIN_URL` constant as well, you'd be set.

**Comment by gouch** [comment]
Thanks for that troubleshoot. I didn't know the plugin url was a separate constant unaffected by changing the path constant.
