### ISSUE TITLE
AI Assistant: keep focus in text input box when the response is received

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#30640]
Whenever the response is received, the focus is not anymore in the text box. We should keep the focus in the input box:

![Image](https://user-images.githubusercontent.com/16329583/237723014-1309f106-3840-413b-9782-10ce69e6091b.png)

**Comment by retrofox** [comment]
I think we should focus in the text input also when the user clicks on the block, too

**Comment by nunyvega** [comment]
Same when a request is unclear:


![Image](https://github.com/Automattic/jetpack/assets/16329583/4ec721e9-203e-41a5-98b8-0f767e15663a)

**Comment by nunyvega** [comment]
@renatoagds moved this to backlog so we can focus on testing
