### ISSUE TITLE
[Super Cache] Exclude key Woocommerce page endpoints from caching by default

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#30672]
Related: p6q8Tx-2Yy-p2

Ensure that WooCommerce's pages and relevant API endpoints are excluded from Super Cache by default. Caching them has been shown to cause issues / inconsistent data shown to users.

Quick skim, this includes: 
- Shop
- Cart
- Checkout
- My Account

plus any APIs they hit.

**Comment by A-Printer** [comment]
Isn't it already the case?

The official WooCommerce documentation [states](https://woocommerce.com/document/configuring-caching-plugins/#wp-super-cache):

> WooCommerce is natively compatible with WP Super Cache. WooCommerce sends information to WP Super Cache so that it doesn’t cache the Cart, Checkout, or My Account pages by default.

This is confusing.

**Comment by thingalon** [comment]
Yes, the documentation you have read is correct. When this issue was raised, a member of the WooCommerce team pointed out to me that it's not needed.

I just lost track of this ticket and didn't close it out. Apologies. :)
