### ISSUE TITLE
Donations block :: invalid amounts don't block saving/updating/publishing

### ISSUE THREAD

**Issue by n3f** [Automattic/jetpack#30670]
### Impacted plugin

Jetpack

### Quick summary

Putting an invalid amount in the donations block is silently ignored. Found while working #30530.

### Steps to reproduce

1. Add a donations block
2. Enter a value below the currencies minimum.
3. Save the block.

### A clear and concise description of what you expected to happen.

An error message or notice blocking the save.  Alternately return the amount value to the one saved to the database (the last good amount entered).

### What actually happened

The last good amount entered is saved.

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by millerf** [comment]
Closing this one as we are soon going to use Team 51 front for the donation block.
