### ISSUE TITLE
Jetpack AI Assistant: add a stop button

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#30717]
Add a way to stop a response that is being generated.

**Comment by keoshi** [comment]
Here's a potential solution that:

- Reuses the same logic as in https://github.com/Automattic/jetpack/issues/30835
- Replaces the Send icon + copy for the Stop icon + button
- For mock completion purposes we're adding the loading icon which we'll document in https://github.com/Automattic/jetpack/issues/30716

![image](https://github.com/Automattic/jetpack/assets/390760/71cee9d7-7e67-4cc4-b7ca-237fad80cb87)
