### ISSUE TITLE
Ai Assistant: modify inactive submit button color so it is visible on dark backgrounds

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#30719]
~~Whenever the block is used on a dark background, the text is not visible:~~

~~https://github.com/Automattic/jetpack/assets/16329583/6f1d2745-c6af-4cfe-84b8-67089cc646d3~~

 The submit button and button on hover when not active are not too visible.

https://github.com/Automattic/jetpack/assets/16329583/c6e15041-b47a-4e2d-9d97-9a88b318a6bf

**Comment by dhasilva** [comment]
What theme is that, @nunyvega?

**Comment by nunyvega** [comment]
Good question. I think that it was Videomaker.

**Comment by nunyvega** [comment]
I just tested it again and now the text looks good, but not the submit button and submit button on hover when not active. I'll update the issue.

https://github.com/Automattic/jetpack/assets/16329583/c6e15041-b47a-4e2d-9d97-9a88b318a6bf
