### ISSUE TITLE
AI Assistant: rethink dall-e shared 1 month image generation caching

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#30740]
The current endpoint for generating images has a 1-month caching mechanism for a given prompt. The same cache is shared between users on WPCOM or between users on the Jetpack site running it.

<img width="561" alt="Screen Shot 2023-05-15 at 15 24 00" src="https://github.com/Automattic/jetpack/assets/6760046/a633c90b-66e5-49cf-a08e-d07cd62a304a">

<img width="1138" alt="Screen Shot 2023-05-15 at 15 24 48" src="https://github.com/Automattic/jetpack/assets/6760046/4bd68467-ca15-427d-85ab-8f8d9de61397">

This means, for WPCOM users, that the result for "boat" is cached and shared between all WPCOM users for a full month, returning always the same "boat" for all requests.

This may not be the expected behavior for the users and we need to rethink it as soon as we focus our attention on the image generation side of the block.

**Comment by nunyvega** [comment]
changing this to On hold because we'll be disabling image generation for the moment:
https://github.com/Automattic/jetpack/issues/30874

**Comment by lhkowalski** [comment]
I will close this as not necessary anymore. We moved beyond cached results for both text and image, and the endpoint in question is not being used by any relevant piece of the product.
