### ISSUE TITLE
Enhancement: More Design Tools for Subscribe Block Input Field and Button

### ISSUE THREAD

**Issue by dhanson-wp** [Automattic/jetpack#30772]
### Impacted plugin

Jetpack

### What

Create design tool parity between Jetpack Form block styles for input fields, labels, and buttons and the Subscribe Block. Users should be able to create designs that can style the email input field separately from the submit button. For instance, decoupling border radius so you can have a square border in the email input field but rounded corners in the submit button.

### How

Current Subscribe Block
<img width="1086" alt="Markup 2023-05-17 at 08 04 59" src="https://github.com/Automattic/jetpack/assets/83921778/5a82e5ca-5f41-418d-9bb4-4cc5ddedb59d">

Jetpack Forms Blocks
<img width="980" alt="Markup 2023-05-17 at 08 05 42" src="https://github.com/Automattic/jetpack/assets/83921778/047e84d2-26c1-4463-9a48-abcb10ca5bc3">

Desired Design Options
<img width="818" alt="Screenshot on 2023-05-17 at 08-06-26" src="https://github.com/Automattic/jetpack/assets/83921778/85cd42ab-d46b-40fd-abb0-aa4bb93cb382">

**Comment by simison** [comment]
Discussed in slack p1684485827678269/1684329415.710989-slack-C052XEUUBL4:

> The block is designed for the input and button to have a single radius control, we wouldn’t want to change that as it adds a lot more complexity to the controls
> if you have a specific need on the design you should force it with CSS
> you can use the blockType specific CSS control in GS to add it

**Comment by dhanson-wp** [comment]
Just sharing a little bit of the rationale for why I think this is still a valuable enhancement.

> if you have a specific need on the design you should force it with CSS

@simison that's not an optimal design experience for someone who does not know how to code.

> you can use the blockType specific CSS control in GS to add it

This is for very advanced users. The proposal to add design controls is meant to make more design options accessible to users within the product and not need extra coding knowledge.

Just things to consider.

**Comment by simison** [comment]
@mtias FYI feedback
