### ISSUE TITLE
Payment Button Block: Toolbar inserter is disabled because there are no child blocks supported

### ISSUE THREAD

**Issue by dpasque** [Automattic/jetpack#30785]
### Impacted plugin

Jetpack

### Quick summary

In short: if focus is ever on the Payment Buttons block, the block insterter button in the top toolbar is disabled. This seems to be because there are no child blocks that can be added to the Payment Buttons block (the block inserter sidebar is completely empty).

The consequences of this are...
1. Right after you insert a Payments Button block from the sidebar, you can't close the block inserter sidebar unless you focus elsewhere on the editor.
2. If you have a Payments Button block focused, you can't open the block inserter.

### Steps to reproduce

1. Start a page/post
2. Open block inserter sidebar
3. Click on the Payments Button block to insert it.
4. Try to close the block inserter

### A clear and concise description of what you expected to happen.

You can -- it's not disabled!

In addition, showing a completely empty block sidebar doesn't seem particularly helpful here... Is there a way to just show all blocks, like we do for other blocks like Paragraph?

### What actually happened

The sidebar is empty, the block inserter button disabled. 
![payment_button_inserter](https://github.com/Automattic/jetpack/assets/26772342/ffb15629-05f6-4788-bfde-b529ed0824c7)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

This seems related to this Gutenberg Bug that was recently fixed: https://github.com/WordPress/gutenberg/issues/43090

But, I'm starting here, because it seems like the core issue is there being no blocks available, which seems like we should be avoiding?

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described on both Simple and AT

#### Screenshots/Recordings

**Atomic Site**

https://github.com/Automattic/jetpack/assets/27249804/4bc62a50-171f-4832-b774-c15883d7df79

**Simple Site**

https://github.com/Automattic/jetpack/assets/27249804/6018b0c7-6216-4c9a-a200-d626e83641d8

📌 ACTIONS
- Assigned to Other
- CC @jeherve

**Comment by worldomonation** [comment]
@jeherve FYI the Payments block _was_ partially covered by E2Es in the Calypso repo until this issue. This test case is currently disabled, as you can see [here](https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/blocks/blocks__jetpack-earn.ts#L25-L31).

In pdWQjU-rL-p2 this feature was noted as Must Cover. Can we get some attention on this issue?

**Comment by jeherve** [comment]
I believe this is triggered by Core, because the inner block is locked; you cannot remove / replace the button block, it would cause the payment block functionality to break:

<img width="399" alt="Screenshot 2023-08-28 at 12 25 09" src="https://github.com/Automattic/jetpack/assets/426388/9869a9c2-c1ae-408c-9ed1-a951e0283546">

Related:

- https://github.com/Automattic/jetpack/pull/25384
- https://github.com/WordPress/gutenberg/issues/43090
- https://github.com/WordPress/gutenberg/pull/47926

cc'ing @mmtr on this, since he's more familiar with this behavior than I am.

**Comment by Robertght** [comment]
This is now fixed. I'm attaching a demo here:

https://github.com/user-attachments/assets/f595457d-fdc3-4b0c-aa71-e65cae8cd353

Closing this for now, but reopen if you still see the issue.
