### ISSUE TITLE
Boost: Minify breaks website on specific servers

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#30791]
### Impacted plugin

Boost

### Quick summary

pedxs5-eK-p2#comment-109

Link to the whole debugging thread p1684395317660539-slack-C016BBAFHHS.

To summarize - when testing with Page Optimize, everything works as expected, because it relies on `file_get_contents`. In Boost Minify, however, we moved to WP's File System in https://github.com/Automattic/jetpack/pull/29352 to make the linter happy. I'm not sure why, but WP decides to use `WP_Filesystem_FTPext` instead of `WP_Filesystem_Direct` and this causes the cache service to fail with an error 500.

On Jurassic Ninja test sites, the filesystem instance is of `WP_Filesystem_Direct` and everything works.

### Steps to reproduce

Unsure why this happens, it was discovered while testing Boost 1.9 beta 1.

### Impact

One

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by donnchawp** [comment]
We figured out what was happening here. We need to call request_filesystem_credentials() before calling WP_Filesystem, just in case they're needed.
This is described in https://developer.wordpress.org/apis/filesystem/
