### ISSUE TITLE
[Site Logo] Stop changing the section name into Site Title, Tagline & Logo

### ISSUE THREAD

**Issue by vladolaru** [Automattic/jetpack#3082]
WordPress has changed that section to Site Identity since 4.3 so you shouldn't mess with it anymore as the new name is more inclusive. At least you shouldn't do this for 4.3 or newer.

@https://github.com/Automattic/jetpack/blob/master/modules/theme-tools/site-logo/inc/class-site-logo.php#L78

**Comment by kraftbj** [comment]
I'm open to this. The next version of Jetpack would require 4.3+, so would be set there. @michaeldcain Any thoughts on this idea from the themers' side?

**Comment by michaeldcain** [comment]
I missed this ping back in the noise of changing teams - the issue is still applicable and could be easily addressed with a small PR.
