### ISSUE TITLE
AI Assistant: update submit button

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#30835]
### Current design:

![Image](https://user-images.githubusercontent.com/16329583/239927776-b05d601c-28cd-407c-823f-2fcf1d8381df.png)

![Image](https://user-images.githubusercontent.com/16329583/239927775-4eca4553-c050-4b54-a1c5-2bad4569a31c.png)

### Proposed design:

![Image](https://user-images.githubusercontent.com/16329583/239928303-f5b92348-72b9-427a-a75b-4eaa89adc712.png)

![Image](https://user-images.githubusercontent.com/16329583/239928302-6237ef84-0caf-4618-95b8-e29d82275d98.png)

**Comment by keoshi** [comment]
Hey @nunyvega — adding a new proposal here that uses an icon that isn't yet part of the core library. Would that be ok, or should we restrict ourselves to existing icons?

![image](https://github.com/Automattic/jetpack/assets/390760/bc9a1709-57ce-4f5d-b1b9-f13526a0a0db)

**Comment by retrofox** [comment]
@keoshi do we have that icon?

**Comment by keoshi** [comment]
@retrofox As mentioned above, we created it for this purpose, so it's not yet part of the core library. Does that matter, or can we include the SVG?

Link is here: gG1smMHbNGas0qwP9y6RwK-fi-3774_14343

**Comment by retrofox** [comment]
let's include it
