### ISSUE TITLE
Debugger: add more troubleshooting depending on your site setup

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3083]
It would be nice if the Debugger could include more troubleshooting steps depending on your site setup.

Here are a few examples:
- If your site uses SSL, recommend `$_SERVER['SERVER_PORT'] = 443;`
- If you've enabled Manage, some tips about why auto-updating plugins might not be an option (version control, subsite in Multisite, ...)

Related:
https://github.com/Automattic/wp-calypso/pull/872/

**Comment by kraftbj** [comment]
Noting that `If your site uses SSL, recommend $_SERVER['SERVER_PORT'] = 443;` is no longer needed.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
