### ISSUE TITLE
AI Assistant: Update tooltips text

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#30838]
i3 came with a proposal to provide/update the tooltip text for the icons

<img width="556" alt="Screenshot 2023-05-22 at 16 29 48" src="https://github.com/Automattic/jetpack/assets/16329583/6494eb55-ac3c-4a60-9e50-0542c56a88fc">

- [ ] Get tooltip text for each icon (from @keoshi / @ederrengifo )
- [ ] Update text

More context:  
p1HpG7-mtU-p2#comment-63284
gG1smMHbNGas0qwP9y6RwK-fi-3720-12834

**Comment by ederrengifo** [comment]
My suggestion here is to make the tooltips a bit more actionable:

![Image](https://github.com/Automattic/jetpack/assets/10525007/7a043937-5e04-4e5c-8f4a-07113a3df73d)

@keoshi please, feel free to suggest any improvement here 🙏

**Comment by retrofox** [comment]
It's funny [More](https://github.com/Automattic/jetpack/blob/f83a7fc19a7e8b70e0a561fe4e9006e2857da677/projects/plugins/jetpack/extensions/blocks/ai-assistant/ai-control.js#L170) wasn't translated
