### ISSUE TITLE
AI Assistant: Show upgrade notice when user runs out of requests

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#30842]
Modify the upgrade prompt added in #30736 so it is visible once the user runs out of requests.

~This issue is blocked by #30727~

Tasks list

- [x] Create an endpoint to get AI Assistant feature data [30926](https://github.com/Automattic/jetpack/pull/30926)
- [x] Show upgrade banned based on the endpoint response [30936](https://github.com/Automattic/jetpack/pull/30936)
- [ ] Check the feature availability when requesting JWT [30984](https://github.com/Automattic/jetpack/pull/30984)
- [x] Check the feature availability when streaming [30989](https://github.com/Automattic/jetpack/pull/30989)
- [x] Tweak the UI/UX [31004](https://github.com/Automattic/jetpack/pull/31004)

**Comment by retrofox** [comment]
There is a patch D111358-code and a PR https://github.com/Automattic/jetpack/pull/30813 that handles the issue. Anyway, we are still blocked by https://github.com/Automattic/jetpack/issues/30727
