### ISSUE TITLE
Enhancement: Update Boost to not use file_get/put_contents

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#30861]
### Impacted plugin

Boost

### What

Update Boost to not use file_get/put_contents

**Comment by haqadn** [comment]
Is this still relevant? Can you add more details?

**Comment by dilirity** [comment]
No idea. Judging by the related PR, I'd say this was suppose to replace said functions with the WP File system. However, the WP File system Direct that we will probably use uses said functions directly, so I think this is unnecessary.

Closing.
