### ISSUE TITLE
Twitter widget overlapping content

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#3086]
This was reported in 2439671-t and I reproduced it with iOS Simulator. Can't be reproduced using Chrome's or Safari's mobile emulation.

<img width="285" alt="overlapping-widget" src="https://cloud.githubusercontent.com/assets/1041600/11504068/42584524-9822-11e5-80c9-ef3077098302.png">

Only found this issue with the Adventure Journal theme. Most responsive themes change the layout into a single column so it's not visible. I tried TwentyTen that is not responsive but the column is larger so it doesn't exhibit this issue.

With Safari inspector, I used this CSS in style attribute to solve it

``` css
iframe.twitter-timeline.twitter-timeline-rendered {
    min-width: 100%;
    width: 50px;
}
```

User entered `50px` in width, which was output as `max-width: 50px` so I wrote that as `width`, set the `min-width: 100%` and it did the trick. Not sure if this should be implemented in a stylesheet or written inline (or if this will be even solved) so I'm opening this issue. I can create a PR later according to the proper method.

Tagging @jeffgolenski since it's a CSS issue.

**Comment by lancewillett** [comment]
> Only found this issue with the Adventure Journal theme.

I'd suggest fixing this in the one theme itself and not adding cruft to the widget and plugin CSS overhead for all other users.

This theme has been retired on WordPress.com so it's also low priority and we'd only make bug fixes for emergencies like security risks.

So I therefore recommend closing as "won't fix."
