### ISSUE TITLE
Enhancement: Provide an option to disable Blaze links in Dashboard

### ISSUE THREAD

**Issue by happenpappen** [Automattic/jetpack#30892]
### Impacted plugin

Jetpack

### What

I would like to have a checkbox which let's me decide for each website if i would like to have "Blaze" links.

**Comment by jeherve** [comment]
Thank you for your feedback. This is currently tracked in #29294, so I'll close this issue.

While there is no checkbox yet, you can use code to disable the Blaze feature on your site today. To do so, you'll want to add the following code snippet to [a functionality plugin on your site](https://jetpack.com/support/adding-code-snippets/):

```php
add_filter( 'jetpack_blaze_enabled', '__return_false' );
```
