### ISSUE TITLE
alert_identity_crisis doing remote request on every admin page load

### ISSUE THREAD

**Issue by tristanleboss** [Automattic/jetpack#3090]
Hello,

Isn't there a way to improve the "alert_identity_crisis" function in "class.jetpack.php" in order not to make a remote request to the "https://jetpack.wordpress.com/xmlrpc.php?for=jetpack
&wpcom_blog_id=XXXXXXXX" on every admin page load? Indeed, this request is taking 1/4 of a second to be processed and so, slow down the page load a bit.

Here is the call stack which is produced on every admin page:

    wp_remote_request()
     wp-includes/http.php:155
    Jetpack_Client::_wp_remote_request()
     wp-content/plugins/jetpack/class.jetpack-client.php:162
    Jetpack_Client::remote_request()
     wp-content/plugins/jetpack/class.jetpack-client.php:118
    Jetpack_IXR_Client->query()
     wp-content/plugins/jetpack/class.jetpack-ixr-client.php:34
    Jetpack->get_cloud_site_options() <---------------
     wp-content/plugins/jetpack/class.jetpack.php:5613
    Jetpack::check_identity_crisis()
     wp-content/plugins/jetpack/class.jetpack.php:5658
    Jetpack->alert_identity_crisis()
     wp-content/plugins/jetpack/class.jetpack.php:5962
    do_action('admin_notices')
     wp-includes/plugin.php:503

Regards,

Tristan

**Comment by kraftbj** [comment]
@tristanleboss - Can you confirm the version of Jetpack you're on? 3.8.1 removed the prompt from all admin pages and, unless you're running a development version, disables the check completely.

**Comment by tristanleboss** [comment]
@kraftbj I was using 3.8.0, I didn't saw there was a new version. After updating, the problem seems to be gone.

I don't know if it's normal but the comment block of the "check_identity_crisis" states that "Will cache the results for up to 24 hours." but I fail to find how it does the caching. There is a "get_transient( 'jetpack_has_identity_crisis' )" call but I failed to find where was the "set_transient" call. I even grepped the whole "jetpack" dir to no avail.

**Comment by kraftbj** [comment]
That's an old function, all in all. Looks like the setting of the transient was removed in https://github.com/Automattic/jetpack/commit/995ff014efeec073c605d9e68fe234f4c336f1a2

I'll open a new issue to address this. Thanks!
