### ISSUE TITLE
`jetpack_has_identity_crisis` transient not set

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#3091]
In `check_identity_crisis`,  we inline doc that the value is cached for 24 hours and have multiple references to `jetpack_has_identity_crisis` transient.

The function that set the transient was removed in quite a long time ago in https://github.com/Automattic/jetpack/commit/995ff014efeec073c605d9e68fe234f4c336f1a2

We need to reconcile this. My suggestion: Re-add the transient for a shorter amount of time (24 hours is a long time if the problem is resolved after first notification).

Discovered via #3090.

**Comment by ebinnion** [comment]
This should be a non-issue with our new work towards IDC mitigation since we're completely changing how we check for IDC. I'm going to leave this open for now and file in the project as probably close.

**Comment by dereksmart** [comment]
This will be solved by #5414

**Comment by samhotchkiss** [comment]
#5436

**Comment by ebinnion** [comment]
Closing for now in favor of new IDC work.
