### ISSUE TITLE
When I authorize Twitter to use publicize on a staging sites, I get redirected to prod site

### ISSUE THREAD

**Issue by nicoladj77** [Automattic/jetpack#3092]
I've a staging site which I marked as staging. 
I activate publicize and I'm trying to connect to Twitter. 
After I authorize the app on Twitter, I get redirected to the prod site, not to the staging site.

Dirty Fix: when you get redirected, change the http address of the prod site with the address of the staging site in the Browser bar and press "return"

**Comment by kraftbj** [comment]
Can you contact us at https://jetpack.me/contact-support/ ? This is a specific issue with your setup and not a bug per se (though there are enhancements planned to handle this situations better).
