### ISSUE TITLE
AI Assistant: remove correct spelling and grammar option as follow-up

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#30932]
This option does not make sense as a follow up option:

![Image](https://user-images.githubusercontent.com/16329583/240885966-1abcb116-cc93-4aaa-98a8-5048422eaafe.png)

**Comment by keoshi** [comment]
Agreed! We should be careful about this one, because it could communicate that whatever comes from AI-land needs spelling and grammar fixing.

Are we able to only show this option in case a regular block is selected? It should never be visible in a Jetpack AI block, right? At least by default.
