### ISSUE TITLE
AI Assistant: maybe add padding to response box

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#30931]
The left of the response text is almost overlapping with the blue border:

![Image](https://user-images.githubusercontent.com/16329583/240884037-53468cfc-65ce-4194-9597-88444837fcb3.png)

**Comment by keoshi** [comment]
Don't disagree, but I wonder if this is a problem we should solve. 🤔 

Core seems to behave the same way (see image below) so maybe we shouldn't change what's default behavior, and instead inherit whatever Gutenberg does.

<img width="704" alt="image" src="https://github.com/Automattic/jetpack/assets/390760/5a10ebd3-8fdb-4fd6-9c61-080355f53bad">

@retrofox and I had a similar conversation yesterday about supporting light/dark themes (in the context of the [loading icon](https://github.com/Automattic/jetpack/issues/30716)) when Core itself has hard defaults for the way it presents certain elements in the editor; e.g.: setting a white background.

**Comment by retrofox** [comment]
Agree with Filipe here. Core has the same behavior. Adding padding will change the layout, generating more discrepancy once the AI Assistant block is transformed into paragraph blocks, for instance.

Going to close it for now.
