### ISSUE TITLE
iframe of vimeo is not wrapped in a div.

### ISSUE THREAD

**Issue by torounit** [Automattic/jetpack#3093]
Write vimeo's video url in editor , replace iframe. but not wrapped by div.
Should be wrapped by div.embed-vimeo.

in editor.
```
https://www.youtube.com/watch?v=TSvTcNLHQnw

https://vimeo.com/9940327
```

output
```
<p><span class='embed-youtube' style='text-align:center; display: block;'><iframe class='youtube-player' type='text/html' width='640' height='390' src='http://www.youtube.com/embed/TSvTcNLHQnw?version=3&#038;rel=1&#038;fs=1&#038;autohide=2&#038;showsearch=0&#038;showinfo=1&#038;iv_load_policy=1&#038;wmode=transparent' frameborder='0' allowfullscreen='true'></iframe></span></p>
<p><iframe src="https://player.vimeo.com/video/9940327" width="500" height="281" frameborder="0" title="Last Address" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></p>
```

**Comment by torounit** [comment]
I was fix the issue in this code.

```php
if(function_exists('vimeo_embed_to_shortcode')) {
	add_filter( 'the_content', 'vimeo_embed_to_shortcode', 99, 1 );
	add_filter('the_content', function( $content ){
		return do_shortcode( $content );
	}, 100);
};
```

But, I think that it is not a good solution.

**Comment by jeherve** [comment]
For reference, here is how it's done for Youtube:
https://github.com/Automattic/jetpack/blob/3.8.1/modules/shortcodes/youtube.php#L310

**Comment by voldemortensen** [comment]
I'm not sure this is an issue. Just pasting the url would use the generic video embedding. Using the shortcode is supposed to wrap it in a div.
i.e.
`[vimeo https://vimeo.com/9940327]`

I confirmed that using the shortcode does wrap the iframe in a div.

**Comment by torounit** [comment]
Of course, there is no problem when using the shortcode.
If only not using the shortcode, HTML of vimeo is wrong.

In the case of youtube, 
URL and shortcode are replaced to the same HTML.

However, it differs in the case of vimeo.

**Comment by kraftbj** [comment]
Follow up in #3332
