### ISSUE TITLE
Subscription block: improve looks for already subscribed user

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#30955]
Currently if you're already subscribed, we just show the same block with your email prefilled — it's actually unclear if you're already subscribed or not:

![Image](https://github.com/Automattic/jetpack/assets/87168/2e57a52e-d976-4c10-aad6-d0b9552c94be)

Suggestion from @jeremyanderberg 

> in Substack I like how it shows just as a checkmark with “subscribed” when you visit the page again and you’re already on the list.
> Then it darkens when you hover over it, and you can click it to manage your subscription.
>
> ![Image](https://github.com/Automattic/jetpack/assets/87168/56eda9c8-6f04-4ae9-9903-276eedb98cf4)

**Comment by pkuliga** [comment]
Closing this one since we already showing:

<img width="550" alt="Screenshot 2024-02-29 at 10 51 06" src="https://github.com/Automattic/jetpack/assets/4068554/2da91b28-35d2-446b-99be-71d0e76f94c0">

for subscribed users.
