### ISSUE TITLE
SEO: issues with updated automattic/social-previews package v2.0.0 in Jetpack plugin

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#30959]
In #29803 it looks like `@automattic/social-previews` was [updated](https://github.com/Automattic/jetpack/pull/29803/files#diff-e298497770aa55653aa165f96930107a79540384a79cef081d531171b88af9b9R60) to v2.0.0 in Jetpack the plugin.

The package is being used on dashboard page `Jetpack > Settings > Traffic > Search engine optimization (section)`: /wp-admin/admin.php?page=jetpack#/traffic

To show "previews" for the home page of a site. With the updated package version, that section could use a review:

- Twitter preview no longer showing at all, is an array of Tweets required now?
- Facebook preview is a bit odd to have post & link preview when intending to show the preview for a homepage URL share.

@manzoorwanijk Would you be able to take a look at this Jetpack dashboard section?

**Comment by manzoorwanijk** [comment]
Thanks. I will look into it.

**Comment by manzoorwanijk** [comment]
Tracking here 1204479765123387-as-1204665149016898/f
