### ISSUE TITLE
Protect: add option to reset blocked_attempts in API

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3096]
> I was wondering if it's possible to clear the results of protect?
> What I mean is after the number of "blocked malicious login attempts" in the stats section has reached a high number, then I'd like to reset it to 0.

A good first step would be to offer this option to Happiness Engineers, before to make that option available in Jetpack itself.

Suggested here:
https://wordpress.org/support/topic/is-there-a-way-to-clear-results-of-the-protect-module?replies=4&view=all#post-7729389

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/blocked-malicious-login-attempts-stats?replies=5&view=all#post-7859105

**Comment by richardmtl** [comment]
Also requested in 2741656-t

**Comment by chaselivingston** [comment]
Also requested in 3237847-t

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by jeherve** [comment]
Also in 821822-zen

**Comment by codestor4** [comment]
for the same ticket 821822-zen, the user responded with:

> Hi there. 
This gives a monthly or quarterly information of attacks on the blog. 
Thank you

for Jeremy's question:

> Those counters cannot be reset right now. We can see about adding such an option to Jetpack and Akismet in the future though. Could you let us know why you would need to reset those counters?

**Comment by jenhooks** [comment]
Requested in 2034361-zen

**Comment by jeherve** [comment]
Also suggested in #16718.

**Comment by bobmatyas** [comment]
Requested here: https://wordpress.org/support/topic/feature-suggestions-for-protect/?view=all
