### ISSUE TITLE
Photon: Resize is always used

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#3098]
In 3.8.1, when asking for a specific size, if it doesn't exist, we fallback to the full-size image. In doing so, the logic will always assign the `resize` parameter to the Photon URL, never the `fit`, even though that may be a better arg to use.

We should use fit when we fail to get an intermediate size.

Will tack this onto #3089.

**Comment by dereksmart** [comment]
Fixed via #3089
