### ISSUE TITLE
Newsletter: "undefined" displayed instead of subscribers count

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#30986]
#### Steps to reproduce

1. Start with a site running Jetpack trunk and connected to WordPress.com.
2. Go to Pages > add New, create a new subscribe page with a subscribe block, and add a payment plan there.
3. Go to Posts > Add New, and create a new post.

You'll see the following (note the "undefined") displayed in the different subscriptions panels:

<img width="304" alt="Screenshot 2023-05-26 at 12 39 52" src="https://github.com/Automattic/jetpack/assets/426388/386d1bba-2ccd-43f1-a5ca-db7daba7f9f6">
<img width="401" alt="Screenshot 2023-05-26 at 12 38 46" src="https://github.com/Automattic/jetpack/assets/426388/bee7c81f-294d-4cae-990d-a49ba6d2a3ed">

**Comment by n3f** [comment]
~~I haven't been able to duplicate this on my site yet.~~ Needed to have a WoA site.

<img src=https://github.com/Automattic/jetpack/assets/6354169/c865ac5f-8878-4b88-b3bb-e0fefb129610 width=200>
