### ISSUE TITLE
Newsletter: can access blog post content without confirming my subscription

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#30985]
### Steps to reproduce

1. Start with a site running Jetpack `trunk` and connected to WordPress.com.
2. Go to Pages > add New, create a new subscribe page with a subscribe block, and add a payment plan there.
3. Go to Posts > Add New, and create a new post. Limit it to subscribers and publish.
4. In an incognito window, access that post.
5. Enter an email address to subscribe to the site.
6. Upon submission, a confirmation email is sent to your email address, and the post contents appear on the page.

**That seems problematic.** You have access to the contents, but you have not confirmed your subscription yet. You may read the post and never subscribe.

**Comment by romarioraffington** [comment]
@jeherve, I believe this is only when subscribing to a free plan?

Potential Solution:

1. Do not unlock the post after the user subscribes to a free plan
2. Send an email to the user to confirm their email and view the post

**Comment by jeherve** [comment]
Yes, I think we should only unlock once the user has confirmed their subscription.

**Comment by romarioraffington** [comment]
This took a bit longer than expected as I played around with different workflows.  It's also been some time since I touched this code. I created   D112247-code and https://github.com/Automattic/jetpack/pull/31054. I think https://github.com/Automattic/jetpack/pull/31054 is the better approach

**Comment by romarioraffington** [comment]
Noting here that this flow was created intentionally in the past. See https://github.com/Automattic/wp-calypso/issues/69664. In terms of improving the subscription confirmation flow. Zap is looking into this: p1685436666862699-slack-C052XEUUBL4
