### ISSUE TITLE
AI Assistant: remove prompt templates from follow-up options

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#30997]
These actions don't make sense as follow-up options, only as initial prompts. 
Let's not show them when a response is received

![Image](https://user-images.githubusercontent.com/16329583/241284383-50c8dc00-c651-4963-95e3-60488d778497.png)

**Comment by renatoagds** [comment]
Addressed in: https://github.com/Automattic/jetpack/pull/31074
