### ISSUE TITLE
AI Assistant: investigate why context is not sent in cases where it should

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#31010]
When the post has content but there's a manual prompt sent, the post content is not sent with it.
![Image](https://user-images.githubusercontent.com/16329583/241417256-5f03e6f3-587a-48cb-8990-0e203df96e61.png)

**Comment by worldomonation** [comment]
@nunyvega Hi, I see this is for Jetpack AI project - does this need to be triaged? It's been raised to `[Status] Escalated` and pinged in the #dotcom-escalations channel.
