### ISSUE TITLE
AI Assistant: make the block aware of the title on manual requests

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#31015]
The Assistant should send the title as part of the context

![Image](https://user-images.githubusercontent.com/16329583/241531249-949e3e6d-97d0-4cc1-9ccd-b99fdaeeaecc.png)

**Comment by lhkowalski** [comment]
I think #31073 solved this.

- The block is now capable of telling the post title:

<img width="500" alt="Screen Shot 2023-05-30 at 15 32 05" src="https://github.com/Automattic/jetpack/assets/6760046/a7f88ac2-f23d-40fb-a92d-9ef4cb822fb0">

- It is talking a lot about the content, but it's aware of the specific scope of the title:

<img width="500" alt="Screen Shot 2023-05-30 at 15 34 13" src="https://github.com/Automattic/jetpack/assets/6760046/6f6b2e33-f7f2-4265-9944-52ac598c8259">

---

Edit: I Forgot to include the post per se on the captures:

<img width="500" alt="Screen Shot 2023-05-30 at 15 37 09" src="https://github.com/Automattic/jetpack/assets/6760046/3ada7275-f667-4903-9676-bf6a6c1c621c">
