### ISSUE TITLE
AI Assistant: move Write with AI to the right of the menu to a different section

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#31042]
Current design:

![Image](https://user-images.githubusercontent.com/16329583/241783505-783d7c8a-9caf-4ab1-9eb7-00c85fa0e936.png)

Move it to the right and to a different section like in this menu:

![Image](https://user-images.githubusercontent.com/16329583/241783570-523368a7-e9ce-4363-9c9e-4415446b316a.png)

**Comment by renatoagds** [comment]
Addressed in https://github.com/Automattic/jetpack/pull/31051
