### ISSUE TITLE
AI Assistant: investigate how to get Gutenberg syntax

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#31048]
Let's try to modify the current rules to get Gutenberg syntax

p1685374959002679/1685372460.272169-slack-C02TQF5VAJD

**Comment by lhkowalski** [comment]
To play with the response, just changed the following line:

```
- Output the generated content in markdown format.
```

To:

```
- You only reply in Gutenberg HTML format including HTML comments for WordPress blocks. All responses must be valid Gutenberg HTML.
- Don't make any remarks about what you're doing, just give me the Gutenberg code.
```

And it started returning blocks:

<img width="600" alt="Screen Shot 2023-05-30 at 16 17 56" src="https://github.com/Automattic/jetpack/assets/6760046/29785fa0-62ea-4f4c-8e2f-fd8bb3a01cf6">

We may need to tweak how we use the returned HTML, maybe appending it to the editor already, or some other way to add it rendered to the block.

**Comment by nunyvega** [comment]
we need to keep in mind sanitization for this

**Comment by dhasilva** [comment]
I'm documenting the progress on this issue here: p1687288837071399-slack-C054LN8RNVA

**Comment by retrofox** [comment]
We've completed the task at hand. Although there is room for improvement, the application can currently generate content using Gutenberg syntax.
