### ISSUE TITLE
AI Assistant: sidebar options should show when an upgrade is needed

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#31049]
Instead of failing silently, let the user know that an upgrade is needed

![Image](https://user-images.githubusercontent.com/16329583/241788345-de1d2871-3ca2-439f-a9de-83a62dea57dd.png)

**Comment by retrofox** [comment]
I believe it would be best to refrain from displaying upgrade notices for non-Jetpack AI blocks.
