### ISSUE TITLE
AI Assistant: remove repeated menu options

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#31041]
Remove repeated options like 'Write a summary based on title' in this screenshot. 

![Image](https://user-images.githubusercontent.com/16329583/241783169-f0683b57-d119-41f8-80b0-ba0c3706674b.png)

Additionally, don't show 'summarize' and 'make shorter' together ( in case they do the same)

**Comment by renatoagds** [comment]
Addressed in: https://github.com/Automattic/jetpack/pull/31074 and https://github.com/Automattic/jetpack/pull/31051

**Comment by nunyvega** [comment]
We're missing one more change to complete this task:
![image](https://github.com/Automattic/jetpack/assets/16329583/5f8b3c45-e2bb-4253-b7e2-d1e46ab0b227)

**Comment by nunyvega** [comment]
After some discussion we'll leave both options.
