### ISSUE TITLE
AI Assistant: Improve prompts, try to use the system/assistant/user format

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#31070]
Iterate over our prompts and use the _system, assistant and user_ format to improve responses
[OpenAI API request formatting doc](https://help.openai.com/en/articles/7042661-chatgpt-api-transition-guide)
Additionally we can revisit sending previous questions/ responses.

Related work

D112325-code

https://github.com/Automattic/jetpack/pull/31104

**Comment by retrofox** [comment]
I'm working on it. We can collect and store the prompt history in the block attributes.
Some concerts:

* How many items should we store? I guess 20 is more than fine
* It will increase the request payload enormously. We'll have to check it, and remove items in case it gets too long.

**Comment by retrofox** [comment]
https://github.com/Automattic/jetpack/pull/31416
