### ISSUE TITLE
AI Assistant: catch bolded JETPACK_AI_ERROR responses

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#31071]
Sometimes it gets bolded in markdown format and we don't treat it as an error

![Image](https://user-images.githubusercontent.com/16329583/241970552-4f95f605-6b5d-4b67-89bd-106fe2a9c3e6.png)

**Comment by lhkowalski** [comment]
It's catching the errors as expected. I tried to break it by requesting a different number of invalid things and it still managed to work properly.

<img width="600" alt="Screen Shot 2023-05-30 at 13 35 17" src="https://github.com/Automattic/jetpack/assets/6760046/1d5dd080-a2d7-4398-b347-9d1e9ba168ff">
