### ISSUE TITLE
Better Responsive Video Display

### ISSUE THREAD

**Issue by mikemcalister** [Automattic/jetpack#3107]
Howdy folks, 

Writing in to see if we can do anything about the display of responsive videos on smaller screens. As you can see in this [screenshot](http://cl.ly/e0O2), the video is responsive, but it has large black bars at the top and bottom of the video, which take up a good amount of vertical space. This behavior is also seen in videos from YouTube, etc.

Compare that to fitvids, another responsive video script, and you can see in this [screenshot](http://cl.ly/e06u) the video fits as it should, with the same proportions as you would see on desktop view. This also is more mindful of the vertical space on mobile.

**Comment by kraftbj** [comment]
First screenshot
![image 2015-12-04 at 11 12 19 am](https://cloud.githubusercontent.com/assets/88897/11596607/b15646fa-9a7b-11e5-87fa-701720122e32.png)

Second screenshot
![image 2015-12-04 at 11 10 59 am](https://cloud.githubusercontent.com/assets/88897/11596620/c68deabe-9a7b-11e5-98b9-521ecca351bc.png)

**Comment by mindctrl** [comment]
Another report of this: https://premium-themes.forums.wordpress.com/topic/embedding-videos?replies=1#post-100713

**Comment by thomasguillot** [comment]
Closing... I am unable to replicate the issue anymore.
