### ISSUE TITLE
Subscriptions: Entering a subscribed email in a site's subscription form returns an opted out message

### ISSUE THREAD

**Issue by lschuyler** [Automattic/jetpack#3110]
When an email address is entered into a website's "Blog Subscriptions (Jetpack)" widget, but they are already subscribed, a message is displayed saying:

"The email address has opted out of subscription emails. 
You can manage your preferences at subscribe.wordpress.com"

A user in #2443637-t found this confusing when troubleshooting her subscriptions. Should it instead say a user is already successfully subscribed? Or does that open a potential privacy issue?

**Comment by Quanitha** [comment]
I too have the same issue as mentioned by lschuyler , how to fix it?

**Comment by jeherve** [comment]
@Quanitha [Send us an email](http://jetpack.me/contact-support/), we'll help!

**Comment by ntpixels** [comment]
also noted in 2567703-t

**Comment by lschuyler** [comment]
Also reported in 2626188-t

**Comment by lschuyler** [comment]
Also reported in 2643369-t

**Comment by lschuyler** [comment]
Also reported in 2644023-t

**Comment by davoraltman** [comment]
Reported in 3095979-t

The user also suggested a fix which worked for them. They added a `break;` for the case `active` at:

https://github.com/Automattic/jetpack/blob/master/modules/subscriptions.php#L533

cc @jeherve who assisted
