### ISSUE TITLE
AI Assistant: Figure out what gets rendered in the frontend if the post is saved having an AI Assistant block with content

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#31100]
This bit of code is wrong https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/extensions/blocks/ai-assistant/ai-assistant.php#L48

`$content` is always empty. It should be replaced by `$attr['content']` BUT we store markdown there, not HTML so this behavior needs to be revisited before fixing it.

**Comment by lhkowalski** [comment]
I just started a conversation about this on Slack, because I think we should not do it right now, while we don't generate HTML Gutenberg markup as a result of the prompts.

Link: p1686086042667839-slack-C054LN8RNVA

**Comment by lhkowalski** [comment]
I am closing this in favor of #31244, as per p1686086042667839-slack-C054LN8RNVA conversation.
