### ISSUE TITLE
JS errors on dashboard conflicting with other plugins

### ISSUE THREAD

**Issue by ambroseya** [Automattic/jetpack#3112]
On every site that I am running 3.8.1, I am getting these errors in the dashboard console.

s0.wp.com/wp-includes/charts/flot/jquery.flot.selection.js:40 Uncaught TypeError: Cannot read property 'plugins' of undefined

jquery.flot.retina.js:3 Uncaught TypeError: Cannot read property 'plugins' of undefined

Original problem was that on sites where I upgraded this and then upgraded Yoast SEO, one of the Yoast admin notices won't "go away" because of the timing of javascript error.

**Comment by jeherve** [comment]
I can reproduce:

![screen shot 2015-12-08 at 11 52 16 am](https://cloud.githubusercontent.com/assets/426388/11653946/2a0885f8-9da2-11e5-99a8-51ec39825447.png)

That seems to be coming from the Stats dashboard widget.

> one of the Yoast admin notices won't "go away" because of the timing of javascript error.

Until we fix that issue, removing the Stats widget should allow you to remove the Yoast notice. You can do so by going to Jetpack > Settings, and clicking on Configure next to the Stats module.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/site-stat-module-causing-uncaught-typerrors?replies=1&view=all

**Comment by eliorivero** [comment]
In progress at 7668-wpcom

**Comment by eliorivero** [comment]
Patch deployed in r-130228-wpcom
