### ISSUE TITLE
AI Assistant: sometimes the block generates lists with broken markup

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#31125]
When the assistant is prompted to generate a list of items, sometimes the result in the editor looks like this:

<img width="600" alt="Screen Shot 2023-05-31 at 18 35 06" src="https://github.com/Automattic/jetpack/assets/6760046/3f3ff45e-dc96-4bb5-adf9-904be91a5cdd">

Exploring the markup for the inserted content, I found `<p>` elements inside `<li>` elements, what can explain the broken visualization.

<img width="600" alt="Screen Shot 2023-05-31 at 18 35 44" src="https://github.com/Automattic/jetpack/assets/6760046/c70e2015-f5bd-4d01-b367-39d56c98f081">

**Comment by lhkowalski** [comment]
I checked the content returned by the completion endpoint and found it including empty new lines between each element:

<img width="600" alt="Screen Shot 2023-05-31 at 18 34 49" src="https://github.com/Automattic/jetpack/assets/6760046/9d2bebde-7038-4d33-8a55-5c62c93d1bd6">

This is probably confusing the markdown parser.

**Comment by lhkowalski** [comment]
Tried adding specific instructions regarding the markdown syntax and the result was different:

<img width="600" alt="Screen Shot 2023-05-31 at 18 41 02" src="https://github.com/Automattic/jetpack/assets/6760046/aecbe529-a881-4955-9736-69fcac5a4ed7">

The raw markdown response:

<img width="600" alt="Screen Shot 2023-05-31 at 18 41 45" src="https://github.com/Automattic/jetpack/assets/6760046/699982db-9f81-435e-9b59-923a4a1c2171">

The inserted content:

<img width="600" alt="Screen Shot 2023-05-31 at 18 41 11" src="https://github.com/Automattic/jetpack/assets/6760046/c8dee98a-56fe-430d-999a-ed6790b61e5a">

And the markup for it:

<img width="600" alt="Screen Shot 2023-05-31 at 18 41 31" src="https://github.com/Automattic/jetpack/assets/6760046/f0edc925-de62-41e1-9fe9-1e30eb35abf8">

**Comment by lhkowalski** [comment]
Probably [#31048](https://github.com/Automattic/jetpack/issues/31048) can fix this issue on a solid way. We can also change the prompt to state more strongly that the markdown syntax needs to be followed strictly.

**Comment by lhkowalski** [comment]
Until we get to Gutenberg syntax usage, we may find a way to prevent this from happening by tweaking the prompt.

**Comment by dhasilva** [comment]
This is a markdown parsing issue. The Markdown library is inserting `p` tags in the list, and then the newline gets added when parsing HTML to the block.
