### ISSUE TITLE
Newsletters panel: update wording in post-publish panel for scheduled posts

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#31135]
### Impacted plugin

Jetpack

### Steps to reproduce

1. Go to Posts > Add New
2. Write a post and save as draft.
3. Set a publishing date to the future
4. Schedule your post	

### A clear and concise description of what you expected to happen.

I would expect a message telling me the post **will be** delivered to my subscribers upon publication	

### What actually happened

The message tells me the post was already delivered.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

**Comment by simison** [comment]
@millerf wanna grab this quickie? Added to Zap backlog as well so it's not lost.

**Comment by millerf** [comment]
Interesting, @romarioraffington worked on something very similar this week: https://github.com/Automattic/gold/issues/46, but we missed this use-case.

@simison We will tackle it today. Thanks!

**Comment by millerf** [comment]
I put this one on the our "iteration 2" project
