### ISSUE TITLE
Contact Form: Showing duplicate "Add Contact Form" buttons in Woo product editor on Atomic

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#31151]
### Impacted plugin

Jetpack

### Quick summary

Two "Add contact form" buttons when viewing product editor on Atomic sites. 
It does not seem to be reproducible on self-hosted with WooCommerce installed. 

### Steps to reproduce

- Spin up an Ecommerce site on wordpress.com with an Ecommerce plan 
- Click on "Products -> Add new", or manually navigate to `/wp-admin/post-new.php?post_type=product` 
- Observe: 
![image](https://github.com/Automattic/jetpack/assets/7129409/f3089780-5097-4a61-ba48-9a1678d915f0)

### A clear and concise description of what you expected to happen.

Only one button 

### What actually happened

Two buttons! 

### Impact

All Ecommerce sites with contact forms enabled

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by john-legg** [comment]
📌 REPRODUCTION RESULTS

Tested on Simple – Not applicable
Tested on Atomic – **Replicated** 
Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO

I was able to replicate this on all browsers (Chrome, Firefox, and Safari) with the Commerce plan and the Business plan for good measure. Self-hosted sites with WooCommerce don't appear to have the duplicate contact form issue. 

Also, I noticed that the second "add contact form" button overflows off the screen on mobile.

**Desktop**
<img width="1007" alt="Contact Form Duplicate" src="https://github.com/Automattic/jetpack/assets/96805492/39888309-dc2d-4c24-af2d-d4c044eb4c57">

**Mobile**
<img width="414" alt="Contact Form Mobile" src="https://github.com/Automattic/jetpack/assets/96805492/b1e02f5e-0ff3-484d-8d53-0def5aa45ed8">



📌 ACTIONS

Assigned to `Other` column for Jetpack
