### ISSUE TITLE
Contact Form: Undefined Index when not using expected content template on Feedbacks CPT

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#3115]
Reported in 2446131-t

```
Notice: Undefined index: _feedback_author in
/var/www/clients/client0/web3/web/wp-content/plugins/jetpack/modules/contact-form/admin.php
on line 290

Notice: Undefined index: _feedback_author_email in
/var/www/clients/client0/web3/web/wp-content/plugins/jetpack/modules/contact-form/admin.php
on line 291

Notice: Undefined index: _feedback_author_url in
/var/www/clients/client0/web3/web/wp-content/plugins/jetpack/modules/contact-form/admin.php
on line 292

Notice: Undefined index: _feedback_ip in
/var/www/clients/client0/web3/web/wp-content/plugins/jetpack/modules/contact-form/admin.php
on line 293`

Notice: Undefined index: _feedback_subject in
/var/www/clients/client0/web3/web/wp-content/plugins/jetpack/modules/contact-form/admin.php
on line 327
```

I have not tested nor confirmed this (I don't have access to a site with PHP7)

**Comment by sybrew** [comment]
Happens in page `/wp-admin/edit.php?post_type=feedback` On each Post.

No plugin/theme conflict found. PHP7 RC6.

**Comment by kraftbj** [comment]
This occurred on w.org at least once, so I don't think (at this point) it is PHP7-related.

@sybrew Can you send me a link to the contact form for the site impacted by this, the shortcode used on that page, and a screenshot of the Edit page for an impacted Feedback post (e.g. a screenshot of the https://example.com/wp-admin/post.php?post=318&action=edit page, completed with the "meta" info, like the following:)
![screen shot 2015-12-08 at 21 04 34](https://cloud.githubusercontent.com/assets/88897/11675435/5fdce118-9def-11e5-8a35-b06c9c767956.png)

Looking to gather information to be able to duplicate the bug.

**Comment by sybrew** [comment]
Dashboard:
http://i.imgur.com/BkCXHMv.png

Front-end is 404, on Genesis default and WordPress 2016 and 2014.

The edit page outputs no errors.

Users are tainted with bbPress/BuddyPress data.

**Comment by eliorivero** [comment]
@kraftbj I've replicated the issue locally using PHP 5.5 in a fresh WP installation and fresh Jetpack.
1. Enabled Contact Form
2. published a Feedback entry
3. went back to Feedback and all notices were displayed.
If you haven't beat me by tomorrow I'll submit a PR as soon as possible.

**Comment by kraftbj** [comment]
Ah, I got it now. I think there are a few different things here:
1. We assume all Feedback posts came in via a Contact Form, and aren't confirming that we have all of the data we assume we have (the quickest fix).
2. We allow you to create a Feedback via wp-admin. It is supposed to be a holding pin for contact form submissions; I'm leaning toward the fact you can create one is a bug too that should be spun off as a separate conversation.
3. The contact form parses text from html to mock post meta data without actually saving it as post meta.

@eliorivero I'll defer to you on whatever you have in mind (I assume for point 1) and I'll spin off a new tickets for 2 and 3.
