### ISSUE TITLE
AI Assistant: Reconnect Jetpack button does not work for non-admin users

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#31165]
If the user is not connected to WordPress.com, we prompt they to reconnect:

![Image](https://user-images.githubusercontent.com/6760046/242893050-d1881507-d725-46cb-90fe-cbf3b051d76c.png)

This button works fine for admin users, but it will fail when the user does not have acccess to the given Jetpack dashboard page:

![Image](https://user-images.githubusercontent.com/6760046/242893195-d1b63b37-0f8b-46a6-b381-06baaf6f367f.png)

This is the case for `author` users, for example.

---

It's possible to connect users of any role to WordPress.com, we just need to send them to the rigth connection page.

For authors, for example, the button on the Jetpack dashboard led me to `wp-admin/admin.php?page=jetpack&from=unlinked-user-connect#/connect-user`.

We need to detect which role the user has and show the correct link to them, or then link to a place that will work for any user role.

**Comment by lhkowalski** [comment]
Just tested and the same is true for the upgrade path: an user that can't access `/wp-admin/admin.php?page=my-jetpack#/add-jetpack-ai` will not be able to follow the upgrade path.

To access the given page, `manage_options` capability is required, so only admins can follow the upgrade path.

I think it would be good, in this scenario, to change the message to something like "You have reached the limit of free requests.
Reach out to the site administrator to upgrade and keep using Jetpack AI."

**Comment by dhasilva** [comment]
This is what I see:
![2023-09-12_14-58-45](https://github.com/Automattic/jetpack/assets/8486249/1d8fd283-19ce-4919-8c11-cc8faf1f0c24)

The input is not deactivated for me.

But I can connect:
![2023-09-12_14-21-50](https://github.com/Automattic/jetpack/assets/8486249/59cf5fd2-8967-4ce9-84be-d19dbc63aa51)
