### ISSUE TITLE
AI Assistant: review block description

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#31176]
The block description has the following text:

![Image](https://user-images.githubusercontent.com/6760046/242958317-a65d2a16-7baf-46ac-8b0d-af987e8ee1ab.png)

We are mentioning that we could remove it at any time, but this was there during the experimental phase. We need to review to prevent scaring away potential long term customer.

**Comment by retrofox** [comment]
p1686258649980909-slack-C054LN8RNVA
