### ISSUE TITLE
Contact Form: Use proper post meta

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#3118]
The Contact Form's Feedback CPT mocks meta data by parsing the html for certain content, which can cause issues when not present ( #3115 ). We should use proper post meta instead.

Any updates here would need to be backwards-compat. A short-term partial fix would be #3117 to prevent new ones from being creating, breaking form.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
