### ISSUE TITLE
AI Assistant: make buttons visible in FSE dark themes

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#31181]
buttons are not visible in dark themes of Full site editing:

https://user-images.githubusercontent.com/16329583/243058427-9a6a5615-1e0c-424e-8499-414d3111f795.mp4

https://user-images.githubusercontent.com/16329583/243058511-ac5a5bfc-4c26-4381-aa2e-7cfe4651fdc3.mov

These tests were done in https://premiumtestv6vidblock.wordpress.com/

Reported by @bizanimesh and @samiff here:
p1HpG7-mHr-p2#comment-63651

**Comment by dhasilva** [comment]
`hold` - It _seems_ to be an issue with cached old CSS clashing with updated CSS. This only applies to wpcom simple on the site editor.
ref: p1686070217660749-slack-CBG1CP4EN

**Comment by lhkowalski** [comment]
This got solved by the new UI shipped by pe4Cmx-1Zr-p2. I will close this as done, and we can re-open it in case something new comes up.
