### ISSUE TITLE
Feature Request: Make instant search markup filterable

### ISSUE THREAD

**Issue by webelaine** [Automattic/jetpack#31194]
### Impacted plugin

Search

### What

Allow end users to customize the markup in the Instant Search overlay.

### How

The markup is currently powered by JSX: https://github.com/Automattic/jetpack/blob/e326028fa7a981ed95fbae9238a7cb8f87b21d2a/projects/packages/search/src/instant-search/components/overlay.jsx#L100

I would like some way to change the `<h1>` tag so that I can adjust my overall HTML5 outline. In my case, I'm trying to ensure older screen readers do not have trouble parsing multiple `<h1>` tags per page. Any method to change the markup would be fine - a JS filter hook, PHP filter, plugin setting, etc.

**Comment by jeherve** [comment]
Thanks for the contribution. This is already tracked in #27947, so I'll close this issue as duplicate.
