### ISSUE TITLE
AI Assistant: Fix "Accept title" action on P2, site editor and widgets

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#31192]
ref pe4Cmx-1km-p2#comment-651

On P2, when using "Accept title", the block is removed but the title is gone. That happens because the title of a P2 post is defined in its content.

It is necessary to check and fix or disable for:

- P2 post
- P2 comment
- Site editor
- Widgets

**Comment by justaraby** [comment]
yareet
