### ISSUE TITLE
Premium content block is showing newsletter plans

### ISSUE THREAD

**Issue by romarioraffington** [Automattic/jetpack#31199]
|  Screenshots | 
| ------------- |
| <img width="729" alt="Screenshot 2023-05-30 at 2 40 23 PM" src="https://github.com/Automattic/wp-calypso/assets/7076981/f8b66fe7-0cc8-4314-95d5-6c4ce9d10270">  | 
<img width="1323" alt="Screenshot 2023-05-30 at 2 40 27 PM" src="https://github.com/Automattic/wp-calypso/assets/7076981/4d7b3cd5-941a-442a-ae95-b74e006930aa">|

**Comment by millerf** [comment]
Do we have any way to prevent Newsletter plans to be used for premium content (and vice-versa) in the back-end?

**Comment by romarioraffington** [comment]
> Do we have any way to prevent Newsletter plans to be used for premium content (and vice-versa) in the back-end?

I would have to check. For now, we could filter this on the frontend since the products will already be in the state. We already do this for Paid Newsletters
