### ISSUE TITLE
AI Assistant: show basic stats panel in the block sidebar

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#31225]
<img src="https://user-images.githubusercontent.com/77539/243825268-19e1a30d-1014-4246-89e4-d8d35596fca1.png" width="300px" />

**Comment by ederrengifo** [comment]
We would need to show something different for free users and communicate clearly:
- The free requests they have left
- A CTA to upgrade
Here is an idea:
<img width="731" alt="jetpack-ai-stats" src="https://github.com/Automattic/jetpack/assets/10525007/5e6bfe55-9c2a-4dd6-84c5-037952b6a186">
(Small thing; I think we can keep it all black, less noise)

Does this work?

**Comment by retrofox** [comment]
Let's close it for now p1686164926817549/1686147682.537239-slack-C054LN8RNVA
