### ISSUE TITLE
Function/Filter to check Primary user?

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#3122]
Hey guys,

So I wrote a function for a plugin we use on our client sites. The job is to present a notice in wp-admin to our team user if the jetpack primary user is not set to the client's user account. 

If possible I would also like to make sure our team user account `imforza-dev` is always connected to our wordpress.com account. Any suggestions or help on how I can check the jetpack user connections?

```php

/**
 * Check if imforza-dev is the primary jetpack user. If so prompt imforza-dev to switch to client account.
 *
 */
function imforza_jetpack_masteruser_check() {

		if ( username_exists( 'imforza-dev' ) ) {

		$imforza_user_id = username_exists( 'imforza-dev' );

		$jetpack_options = get_option('jetpack_options');

		$jetpack_master_id = $jetpack_options['master_user'];

		$current_user = wp_get_current_user();

		if ( $current_user->user_login == 'imforza-dev' && $imforza_user_id == $jetpack_master_id ) {

	   ?>
    <div class="error">
        <p><?php _e( 'Currently <strong>imforza-dev</strong> is assigned as Jetpack\'s <a href="https://jetpack.me/support/primary-user/" target="_blank">primary user</a>. Please use the <a href="admin.php?page=my_jetpack">My Jetpack</a> page to set the <strong>client user</strong> as the primary user for Jetpack. The <strong>imforza-dev</strong> user should be connected to our WordPress account <strong>imforzadevelopers</strong>.', 'imforza-news' ); ?></p>
    </div>
    <?php
	    }

	}

}

add_action('admin_notices', 'imforza_jetpack_masteruser_check');
```

**Comment by dereksmart** [comment]
We have a function that checks if a user id is connected <a href="https://github.com/Automattic/jetpack/blob/4325a1eb7481b4bfc260797c64e28c58d57b3755/class.jetpack.php#L1459">`is_user_connected( $id )`</a>.  You can check against any user ID.  

So you can get the master user ID with `Jetpack_Options::get_option( 'master_user' )`, and pass that into is_user_connected().  Does that help?

**Comment by bhubbard** [comment]
That should work for me, thanks!
