### ISSUE TITLE
AI Assistant: mark posts with accepted AI content as AI assisted

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#31235]
Jetpack's AI Helper includes a `mark_post_as_ai_assisted` method:
https://github.com/Automattic/jetpack/blob/a086e60c733cff40b8c28365f47f3047c50e8b04/projects/plugins/jetpack/_inc/lib/class-jetpack-ai-helper.php#L106-L112

We used to mark all posts as AI assisted with the old blocks, e.g. here:
https://github.com/Automattic/jetpack/blob/a086e60c733cff40b8c28365f47f3047c50e8b04/projects/plugins/jetpack/_inc/lib/class-jetpack-ai-helper.php#L210

I think posts using the new AI Assistant should get marked the same way as well.

Related issues:

- #28444 
- p4vt7e-bh-p2

**Comment by lhkowalski** [comment]
I was working on this in the context of [30738](https://github.com/Automattic/jetpack/issues/30738#issuecomment-1552006233) but postponed it at the time. Thank you for bringing it up.

**Comment by oskosk** [comment]
Why is this needed?

**Comment by jeherve** [comment]
> Why is this needed?

The references in the issue should provide more background about why this was added in the first place. This post in particular:

p4vt7e-bh-p2

**Comment by oskosk** [comment]
These references there are vague. Why do you think it makes sense here? Anyone can copy paste from ChatGPT and if word goes about about us tagging posts as "not purely authored by the author" it's not going to be great. Also what does it means if we tag a post? The user generated what content? What if the user never remembers having inserted our block, we tag that and then forever remains blamed as an AI-cheater?

We need to understand that there is no point in differentiating AI generated content. It renders the content useless. Imagine how many posts you've read where the author starts like "This post was written by AI:"

I'm closing this issue

**Comment by jeherve** [comment]
Also suggested here:
https://twitter.com/adityakane/status/1668902225882791936
