### ISSUE TITLE
Jetpack Mobile: Add support for jetpack/slideshow block

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#31257]
### Quick summary

In 6360212-zd-woothemes, the user reports that the `jetpack/slideshow` block is not supported in the mobile app. I have confirmed this on my personal blog.

### Steps to reproduce

1. Start with a site that is simple, atomic, or Jetpack
2. Create a draft post and add a slideshow
3. Open the post in the Jetpack app
4. Verify the unsupported block message

![IMG_5902B7995C4C-1](https://github.com/Automattic/wp-calypso/assets/1126811/5976125c-510b-45f6-989e-5eddf43754c4)

### What you expected to happen

A Jetpack block to be supported.

### What actually happened

The block was not supported.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described. The tooltip for the message states:

```
'jetpack/slideshow' is not fully-supported
You can edit this block using the web version of the editor.
```
#### Screenshots/Recordings

<img width="550" alt="screenshot" src="https://github.com/Automattic/wp-calypso/assets/27249804/1c86b00d-a29f-4795-8ebc-affb468a9e6f">

Clicking "Edit using Web Editor" opens an in-app browser window where the slideshow is editable:

<img width="550" alt="screenshot" src="https://github.com/Automattic/wp-calypso/assets/27249804/5ab4caa5-ebfa-4533-aaee-e7a7f98c5238">

📌 ACTIONS
- Changed to Feature Request
- Assigned to `Other` (Jetpack)
- CC: @jeherve

**Comment by cuemarie** [comment]
Transferred this to Automattic/jetpack, but feel free to transfer back/elsewhere if there's a better place for Jetpack Mobile App issues.

**Comment by jeherve** [comment]
@SiobhyB Where would you prefer to track such requests for blocks in the mobile apps? Do you track them somewhere already?

**Comment by fluiddot** [comment]
Hey @jeherve 👋 ! We usually track issues related to Jetpack and affecting the native mobile version of the editor in [the Gutenberg Mobile repository](https://github.com/wordpress-mobile/gutenberg-mobile/issues). In fact, for this one, we already have it reported there, so I'll cross-reference them: https://github.com/wordpress-mobile/gutenberg-mobile/issues/5801.

**Comment by SiobhyB** [comment]
@jeherve, thanks for pinging and sorry for the late reply, just got back from AFK! As Carlos has mentioned, we currently track these requests in the Gutenberg Mobile repo, but I think this discussion highlights an opportunity for us to improve the way we categorise/monitor demand for new blocks. Thank you for raising :)

**Comment by ebinnion** [comment]
@Automattic/kitkat - Just noting this issue as I used bugomattic to figure out where to report the issue.
