### ISSUE TITLE
Add tracking to Newsletter CTA in Post Publish Panel

### ISSUE THREAD

**Issue by romarioraffington** [Automattic/jetpack#31287]
Based on the comments [here](https://github.com/Automattic/jetpack/pull/31224#issuecomment-1582434031).

We need to add track events for the CTA in the following tasks:

1. "Turn on paid newsletter" in https://github.com/Automattic/jetpack/issues/31219
2. "Upgrade Plan" in https://github.com/Automattic/jetpack/issues/31302

**Comment by romarioraffington** [comment]
Putting this back as this is a bigger task that requires more time. Focusing on closing https://github.com/Automattic/jetpack/issues/31302

**Comment by millerf** [comment]
It is getting really hard to track anything...

**Comment by romarioraffington** [comment]
Putting this on hold as requested by Fab. 

See p1687187852858469/1687187149.097789-slack-C01B6KEJ5GE

**Comment by millerf** [comment]
Add leftover work in https://github.com/Automattic/jetpack/issues/31287
