### ISSUE TITLE
Comments: Only allow logged in users from all types (+social) to comment

### ISSUE THREAD

**Issue by vrocks** [Automattic/jetpack#313]
Currently it seems that I have the option inside wordpress itself to force somebody to login to comment. But this is restricted to my blog. It would be better if Jetpack could completely take over the comment form and do two things:

1) Force the user to login to SOMETHING to comment. Whether it be the blog, wordpress.com, or social media.
2) Do away with the email, name, URL form, and more importantly, not accept it from bots that would still "post" to it for spam.

**Comment by RCowles** [comment]
Requested in 2154581-t

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by lejeczek** [comment]
as a user I can say - That would be a great! feature to have. And maybe those who log in via social/wordpress could get automated approval, maybe with some option in settings.
many thanks, L.

**Comment by StefMattana** [comment]
Another user mentioned it as a nice new feature in [here](https://wordpress.org/support/topic/comments-only-if-authenticated/#post-9779104)
