### ISSUE TITLE
Feature Request: Allow a "code" block

### ISSUE THREAD

**Issue by dennisfrancisblewett** [Automattic/jetpack#31306]
### Impacted plugin

Jetpack

### What

I would like to be able to have a code block

### How

So far, I have only seen a shortcode block available when I search for the code block. I want to use a code block in order to layout syllogisms and various kinds of deductive arguments. I have a preference for formatting those kinds of arguments in that way because I think it looks pretty. I used the shortcode block last night, but it did not provide the formatting that I had hoped for.

**Comment by jeherve** [comment]
Jetpack does not include a code block, but WordPress itself does; this may be the "shortcode" block you're mentioning. However, WordPress' code block does not include any syntax highlighting, it only displays code.

We're not currently planning on adding a code block to the Jetpack plugin, so if you're interesting in syntax highlighting for your code, I would recommend that you enable one of the following plugins on your site:

- https://wordpress.org/plugins/syntaxhighlighter/
- https://wordpress.org/plugins/code-syntax-block/

I hope this helps!
