### ISSUE TITLE
Contact Form: Export to CSV option doesn't always include all fields

### ISSUE THREAD

**Issue by ryanmarkel** [Automattic/jetpack#3130]
Some contact form constructions don't appear to be exporting the correct amount of data. A contact form that we've created for a site skips including questions 3 through 12 in output - they just don't appear, in the CSV header or otherwise. I'm including source for the contact form that provides the incomplete export. (Slightly sanitized to not reveal the source.)

```[contact-form][contact-field label='Which of the following best describes your primary role at work? ' type='radio' required='1' options='Developer,3D artist,Technical Artist,Visual Effect Specialist,Animator,Designer,Producer,Executive,Other'/][contact-field label='If other role, please specify' type='text'/][contact-field label='Which discipline are you most interested in learning more about?' type='radio' required='1' options='Development,Design,Art,Production,Other'/][contact-field label='If other area, please specify' type='text'/][contact-field label='Which kind of app would you be most interested in seeing our teams develop? (required, check all that apply)' type='checkbox-multiple' options='Game,Productivity,Shopping,Business,Education,Entertainment,News %26amp; Weather,Social / Communications,Travel'/][contact-field label='How would you prefer to learn about making apps during the build phase? (required)' type='checkbox-multiple' options='Watching weekly videos,Participating in live streams,Participating in live chats with developers,Reading blog posts,Participating in daily scrum meetings,Participating in weekly build reviews,Another way'/][contact-field label='If another way, please specify' type='text'/][contact-field label='How often do you think you will come back to this website to watch this app be built?' type='radio' options='More than once a day,Once a day,A couple times a week,Once a week,A couple times a month,Once a month,Less than once a month'/][contact-field label='What is your interest in app development?' type='radio' options='To start a business,To grow/extend an existing business,Simply to explore a new technology'/][contact-field label='Do you have suggestions for how our team could help you better understand how to develop apps?' type='textarea'/][contact-field label='With which of the following development platforms are you familiar?' type='checkbox-multiple' options='Unity,Havok,CryEngine,Unreal,Windows,iOS,Android,C,C#,C++,Java,JavaScript,Oculus,Facebook,Web/HTML,None of these,Other'/][contact-field label='If other development platforms, please specify' type='text'/][contact-field label='Have you applied for the Development Edition?' type='radio' options='Yes,No,Not yet'/][contact-field label='The following represents who I intend to work with on an application' type='radio' options='Alone,With one other person,With two to four other people,With five or more people,N/A - I do not intend to build an app'/][contact-field label='Have you ever had a demo before?' type='radio' options='Yes; I had a demo in the city specified below,Not yet; please come to the city specified below'/][contact-field label='Specify the city for the demo:' type='text'/][/contact-form]```

The first question that fails to be included in the export is the first `checkbox-multiple` question.

**Comment by kraftbj** [comment]
Initially marking as 3.9 as this is impacting VIP Go.

**Comment by bisko** [comment]
I think I saw where the problem lies and I will make a fix for it.

**Comment by zinigor** [comment]
Should be fixed by #3215
