### ISSUE TITLE
Contact Form: checkbox-multiple and required option for field don't jibe

### ISSUE THREAD

**Issue by ryanmarkel** [Automattic/jetpack#3131]
If you assign a `checkbox-multiple` field in a contact form as a required element, any answer to that field will not register as completed and the form will never submit.

To reproduce:

1. make contact form
2. create a `checkbox-multiple` field
3. make it required
4. save contact form
5. try to fill it out and submit
6. you can't :)

**Comment by kraftbj** [comment]
VIP Go.
