### ISSUE TITLE
AI Assistant: Consider to add AI Assistant transform

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#31319]
We may want to consider adding an "AI Assistant" transformation to other blocks if it is appropriate.

**Comment by lhkowalski** [comment]
When the block gets transformed, it will actually means that the generated content will be placed on a real content block, like paragraph or list or heading, right?

I see it getting trickier when, for example, the generated content contains complex elements like 2 or more paragraphs, or a list, or a table. What should be the behavior when the user asks to transform to paragraph and the content is a list, for example?
