### ISSUE TITLE
AI Assistant:  Add simplify action in paragraph extension

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#31324]
Introduce the `Simplify` option in paragraph AI toolbar option.

Depends on #31321

**Comment by ederrengifo** [comment]
Here are the designs of the dropdown where this action is displayed:

<img width="567" alt="jetpackai-gh-2" src="https://github.com/Automattic/jetpack/assets/10525007/c72df18a-9ae1-483a-a7ac-274b0f04664e">
