### ISSUE TITLE
AI Assistant:  Add change tone action in paragraph extension

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#31328]
Introduce the `Change Tone` option in paragraph AI toolbar option.

Depends on #31321

**Comment by ederrengifo** [comment]
Here are the designs of the dropdown where this action and its sub-menu are displayed:

<img width="775" alt="jetpackai-gh-3" src="https://github.com/Automattic/jetpack/assets/10525007/06304883-0cdc-46a2-a337-713ad1ca322f">
