### ISSUE TITLE
AI Assistant:  Add correct spelling and grammar action in paragraph extension

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#31323]
Introduce the `Correct Spelling and Grammar` option in paragraph AI toolbar option.

Depends on #31321

**Comment by ederrengifo** [comment]
Here are the designs of the dropdown where this action is displayed:

<img width="567" alt="jetpackai-gh-2" src="https://github.com/Automattic/jetpack/assets/10525007/ace262c1-ef4b-462d-8262-1421bfe80d33">
