### ISSUE TITLE
AI Assistant: Add translate action in paragraph extension

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#31329]
Introduce the `Translate` option in paragraph AI toolbar option.

Depends on #31321

**Comment by ederrengifo** [comment]
Here are the designs of the dropdown where this action and its sub-menu are displayed:

<img width="775" alt="jetpackai-gh-4" src="https://github.com/Automattic/jetpack/assets/10525007/cfdf06c6-4cb6-433b-8d9b-7f4e699de271">

**Comment by retrofox** [comment]
@renatoagds, we've merged the PR that implements [ToneDropdownMenu](https://github.com/Automattic/jetpack/blob/24a36efef52e9e450b62d9d792c11416f1696915/projects/plugins/jetpack/extensions/blocks/ai-assistant/components/tone-dropdown-control/index.tsx#L151) component, just FYI.
