### ISSUE TITLE
AI Assistant:  Add summarize action in paragraph extension

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#31325]
Introduce the `Summarize` option in paragraph AI toolbar option.

Depends on #31321

**Comment by ederrengifo** [comment]
Here are the designs of the dropdown where this action is displayed:

<img width="567" alt="jetpackai-gh-2" src="https://github.com/Automattic/jetpack/assets/10525007/4b5dd18c-3233-41f8-9859-96d2c04c7541">
