### ISSUE TITLE
AI Assistant: Add expand action in paragraph extension

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#31326]
Introduce the `Expand` option in paragraph AI toolbar option.

Depends on #31321

**Comment by ederrengifo** [comment]
Here are the designs of the dropdown where this action is displayed:

<img width="567" alt="jetpackai-gh-2" src="https://github.com/Automattic/jetpack/assets/10525007/291cb111-9e4e-4605-8e97-1b4bd8d8a413">
