### ISSUE TITLE
Paid Stats: Add purchase screen to Calypso

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#31344]
Create a new purchase screen for Jetpack Stats. This screen should:

- Enable customers to select between Personal and Commercial sites.
- Enable the selection of a user-selected price for personal plans.
- Enable the purchase of both personal and commercial plans via Calypso's checkout flow.

> ![SCR-20230621-jbvn](https://github.com/Automattic/jetpack/assets/112354940/12601f47-86b2-4180-b99c-35cae276943d)

> Free|Paid
> -|-
> <img width="1170" alt="image" src="https://github.com/Automattic/jetpack/assets/4044428/807728a4-147a-43db-bd70-4eebc20b4912"> | <img width="1055" alt="image" src="https://github.com/Automattic/jetpack/assets/4044428/5aa23497-fbf5-4ada-93a1-880676b28b0f">

> <img width="1169" alt="image" src="https://github.com/Automattic/jetpack/assets/4044428/efa46f74-57c8-42f0-a808-6284cb0ffb31">

```[tasklist]
### Tasks
- [x] Create the personal flow. Note that `1. Personal Site` is clickable.
- [x] Create the commercial flow. Note that `1. Commercial Site` is clickable.
```

**Comment by kangzj** [comment]
The task depends on #31342

**Comment by grzegorz-cp** [comment]
The screen got an updated design in the newest iteration.

![SCR-20230621-jbvn](https://github.com/Automattic/jetpack/assets/112354940/12601f47-86b2-4180-b99c-35cae276943d)

**Comment by jsnmoon** [comment]
I updated the original task with our latest designs 🙂

**Comment by kangzj** [comment]
Hi @grzegorz-cp, ICYMI

Our awesome designer @keoshi created a prototype which we could refer to for styling, layouts and animations: https://codesandbox.io/s/pnt3yv?file=/App.svelte

**Comment by keoshi** [comment]
FWIW, that prototype is no longer working for some reason. I suspect something to do with codesandbox.io or how Svelte is being built with Vite. A working prototype can be found here: https://jetpack-stats-pwyw.vercel.app/

All styles and code remain unchanged though.

**Comment by jsnmoon** [comment]
@grzegorz-cp: I think we can mark this task as complete!
