### ISSUE TITLE
Paid Stats: Add Stats Product for My Jetpack with mocked WPCOM product

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#31342]
Add Stats product in https://github.com/Automattic/jetpack/tree/52b0b88b8588e3b53702b8b2b2a61bb28159e458/projects/packages/my-jetpack/src/products

We could reference Jetpack AI as it's also sold as a Jetpack module 

https://github.com/Automattic/jetpack/blob/52b0b88b8588e3b53702b8b2b2a61bb28159e458/projects/packages/my-jetpack/src/products/class-jetpack-ai.php

We could take a look at Akismet as well. However, I don't think the PWYW is implemented on site tho.

https://github.com/Automattic/jetpack/blob/52b0b88b8588e3b53702b8b2b2a61bb28159e458/projects/packages/my-jetpack/src/products/class-anti-spam.php

As the WPCOM product might not be ready yet, we could mock the response for now. More information: pbNhbs-6YI-p2.

**Comment by jsnmoon** [comment]
~Jetpack MarTech is handling this, see pbNhbs-6ZT-p2~ 🙂

EDIT: See Jasper's comment below.

**Comment by kangzj** [comment]
Hey @jsnmoon I think they are working on the WPCOM side, and the issue is about the product setup in My Jetpack which would support the frontend product card and purchase flow - pricing, features, activating etc.

Are you sure they are going to build this as well? I'm more than happy to close the issue if they do. 😄

**Comment by jsnmoon** [comment]
Oh, I misunderstood the intent of this card -- thanks for clarifying! I think this is a valid task for us to work on in that case 🙂
