### ISSUE TITLE
Paid Stats / Components: Pricing Slider

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#31345]
Please refer to the implementation on Akismet to accelerate the development: https://akismet.com/plan/personal/

Typical props would include: `defaultValue`, `value`, `minStep`, `minValue`, `maxValue`, `onChange`, `sliderColor` etc.

![Image](https://user-images.githubusercontent.com/1425433/245351006-e4fc91e2-8d9c-4bf1-a1b1-fd5746060a52.png)

**Comment by dognose24** [comment]
I have searched for the slider component and found out the [Gutenberg Range Control](https://wordpress.github.io/gutenberg/?path=/docs/components-rangecontrol--default) is partially adapted to our needs.
However, as I use more hacks to fit the complete need, the changes seem more challenging to understand and maintain.

So, applying the third-party library [ReactSlider](https://zillow.github.io/react-slider/#reactslider) seems to be a better choice. I will tackle the component with it on Jetpack Storybook later.
