### ISSUE TITLE
Carousel: after exiting a Carousel permalink on a site's index view, scrolling doesn't work

### ISSUE THREAD

**Issue by lancewillett** [Automattic/jetpack#3136]
Raised by @zandyring 

Tested in P2 theme and Twenty Fifteen with Jetpack 3.8.2-alpha and and WP 4.5-alpha-35776-src. Happens in Firefox, Safari, and Chrome.

**Steps to repeat:**
1. With Carousel setting active in Jetpack, publish a new post with a gallery in it.
2. Go to the post permalink. Click an image in the gallery, copy the permalink from your browser address bar.
3. Paste that URL into a new tab.
4. Hit Esc or click the X at top left of Carousel view to exit.
5. Scroll with your mouse.

These steps should work as expected.

Now, do the same thing with this change: **in step 2 — access the site home page instead of the post permalink.** Paste the Carousel permalink (in this format `#jp-carousel-1731`) and repeat steps 3-5 again.

**What I expected to happen**

I expected to hit Esc key, exit the Carousel, and scroll normally on the index page.

**What actually happened**
In Safari, the Esc key doesn't work.

In all browsers: you cannot scroll because the `body` element has a lingering inline style that isn't removed: `style="overflow: hidden;"`

Notes from @rachelmcr 

> There’s inline CSS on the body element (I assume to keep the background from scrolling behind the carousel when it’s open) - `style="overflow: hidden;"` and that doesn’t go away when you close the carousel
> 
> Normally that switches to hidden when the carousel is open and switches back to visible when you close the carousel

**Comment by samiff** [comment]
Testing with the upcoming Jetpack 9.9 release, I was unable to reproduce the issue in Chrome or Safari.
