### ISSUE TITLE
[Jetpack] Broad translation / i18n issues in WP Admin

### ISSUE THREAD

**Issue by lakellie** [Automattic/jetpack#31365]
### Impacted plugin

Jetpack

### Quick summary

On a default installation of Jetpack, the WP Admin menu shows the following subitems under the Jetpack menu:

- Dashboard
- Settings
- Stats
- Search
- My Jetpack

When the site is set to a language besides English, the Stats page appears to be the only page that is translated. The Dashboard, Settings (and all its subpages/tabs), Search, and My Jetpack are completely in English.

Additionally, the submenu labels themselves are not translated. 

### Steps to reproduce

1. Create a test site
2. Set test site to a language besides English. HEs tested with Spanish and German.
3. Connect Jetpack
4. Visit and browse various Jetpack submenu items in WP Admin

### A clear and concise description of what you expected to happen.

To see the content in my site's language

### What actually happened

Content was all in English

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

There are a couple of different things I tried to see if they would make a difference:

- I tried changing the site language before and after connecting Jetpack. No difference
- I tried changing my WordPress.com account language interface, in case Jetpack was pulling from that instead of the site language. No difference

**Comment by jeherve** [comment]
I cannot seem to reproduce on my end; each menu item is translated. Here is how it looks in French for example:

<img width="202" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/44886fe7-c9ff-4edf-bbcb-0dd602165395">

Could you try going to Dashboard > Updates, and ensuring that there are no pending translation updates there? 

I would also ensuring that the language you picked has a full language pack. You can check that here:
https://translate.wordpress.org/projects/wp-plugins/jetpack/

**Comment by lakellie** [comment]
Thanks @jeherve, updating the translations under Dashboard > Updates worked. I didn't anticipate that would be needed on a fresh testing site—that's my bad! 
I do wonder how frequently this is happening since me and another HE bumped into it but I guess all we can do at this point is add a pointer to check for translation updates to this [support doc](https://jetpack.com/support/getting-started-with-jetpack/how-can-i-install-jetpack-in-my-language/) as a troubleshooting tip.
Thanks again :)

**Comment by jeherve** [comment]
> I do wonder how frequently this is happening since me and another HE bumped into it

The translations are automatically updated on each site every 12 hours at most, and whenever a plugin is installed or updated. That usually helps avoid such issues, but sometimes you still need to update manually :)
