### ISSUE TITLE
AI Assistant: show errors in the UI when something fails

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#31382]
We need to show the errors in the UI when something fails.
We can offer a message similar to what we do for the AI Assistant block, but we also should keep in mind that we are extending other blocks. It could be intrusive.

**Comment by lhkowalski** [comment]
Should we add a "Needs design" status?

**Comment by lhkowalski** [comment]
We are going to use Notices (https://developer.wordpress.org/block-editor/reference-guides/components/notice/) to display this, as a non-intrusive way to show the messages.
