### ISSUE TITLE
AI Assistant: handle editing when selecting multiple blocks

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#31380]
It should be possible to edit the content when the user selects multiple blocks.

**Comment by ederrengifo** [comment]
Here is the design reference for this issue

<img width="726" alt="jetpackai-gh-1" src="https://github.com/Automattic/jetpack/assets/10525007/b2252a46-8e23-4cb6-953f-a46782ebd14b">

**Comment by renatoagds** [comment]
Closing, since it was implemented.
Context: p1686838445413539-slack-C054LN8RNVA
