### ISSUE TITLE
Connection Banner: Replace Midnight Shift Photo image

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#31439]
### Impacted plugin

Jetpack

### What

Currently, there's a connection banner that displays a Midnight Shift Photography image. This is one of my personal sites and I'm not comfortable with having it in the banner. I didn't add this, and I don't want it to appear as though I'm promoting my work. I'm attaching an image with the same dimension ratio so we can quickly swap it out. 

**Current:**
![Screen Shot 2023-06-19 at 11 18 10 AM](https://github.com/Automattic/jetpack/assets/214813/4b2154d2-8791-4aba-a2a5-49a3c56ba409)

**Image to swap:**
<img width="412" alt="connection banner replacement" src="https://github.com/Automattic/jetpack/assets/214813/012f52a1-8f3c-4eeb-8dd2-7347c7be8ae3">

**Comment by jeffgolenski** [comment]
@kraftbj Is this something we could squeeze in before the next release? Sorry for the short notice. Just a quick image swap.

**Comment by kraftbj** [comment]
@jeffgolenski Yup, we'll get it swapped out ASAP.
