### ISSUE TITLE
Jetpack Photon returned an unexpected status code (400)

### ISSUE THREAD

**Issue by iuzairjan** [Automattic/jetpack#31433]
### Impacted plugin

Jetpack

### Quick summary

A widespread issue is affecting multiple users who are consistently encountering a 400 error while utilizing the Jetpack Photon image service within the WordPress Jetpack plugin. This error, denoted by an HTTP status code of 400 Bad Request, suggests a problem with the requests being sent to the server.

Despite the varied configurations and environments of affected users, the error persists universally. The identical nature of the issue implies that the root cause is likely not specific to individual setups but rather a common factor affecting the Jetpack Photon service as a whole.

### Steps to reproduce

Upload images on jetpack-enabled photon-enabled websites

### What actually happened

We cannot complete this request, remote server returned an unexpected status code (400)

### Impact

All

### Available workarounds?

No, but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by jeherve** [comment]
> A widespread issue is affecting multiple users who are consistently encountering a 400 error while utilizing the Jetpack Photon image service within the WordPress Jetpack plugin. 

Could you post a few links to Photon-hosted images that return such an error on your end, so we can take a closer look with you?

Could you also let me know if you experience the same issue with some test images like those:

- https://i0.wp.com/jeremy.hu/wp-content/uploads/watson-5818-1.jpg?strip=info&w=1024&ssl=1
- https://i0.wp.com/www.google.com/logos/doodles/2023/juneteenth-2023-6753651837109890-2x.png?w=1024&ssl=1

If this is happening with all images you try to load from your machine, could you [run a traceroute](https://wordpress.com/support/browser-issues/advanced-browser-troubleshooting/) for the `i0.wp.com` domain, and post the results here, or [send them to us via email](https://jetpack.com/contact-support/?rel=support&hpi=1)?

Thank you!

**Comment by iuzairjan** [comment]
https://i0.wp.com/www.nooraks.com/wp-content/uploads/2023/06/DUPATTA-5-3.jpg?resize=768%2C768&ssl=1
https://i0.wp.com/www.nooraks.com/wp-content/uploads/2023/06/6.1-kaftan.jpg?resize=768%2C768&ssl=1

The issue was from Saturday, Morning


while these images working fine,

https://i0.wp.com/jeremy.hu/wp-content/uploads/watson-5818-1.jpg?strip=info&w=1024&ssl=1
https://i0.wp.com/www.google.com/logos/doodles/2023/juneteenth-2023-6753651837109890-2x.png?w=1024&ssl=1

**Comment by jeherve** [comment]
Thanks for the extra details.

Those images will not load when using Jetpack's Image CDN, because the original image does not load either:

- https://www.nooraks.com/wp-content/uploads/2023/06/DUPATTA-5-3.jpg
- https://www.nooraks.com/wp-content/uploads/2023/06/6.1-kaftan.jpg

Both of those images return a 415 (Unsupported media) response:

```sh
$ curl -I https://www.nooraks.com/wp-content/uploads/2023/06/6.1-kaftan.jpg
HTTP/2 415
content-type: image/jpeg
expires: Tue, 18 Jun 2024 17:00:20 GMT
cache-control: public, max-age=31557600
x-qc-cache: hit
date: Mon, 19 Jun 2023 13:42:02 GMT
server: LiteSpeed
x-qc-pop: EU-FR-NTE-51
alt-svc: h3=":443"; ma=2592000, h3-29=":443"; ma=2592000, h3-Q050=":443"; ma=2592000, h3-Q046=":443"; ma=2592000, h3-Q043=":443"; ma=2592000, quic=":443"; ma=2592000; v="43,46"
```

If you're the admin of the site, I would recommend that you look at any changes you may have recently made to your server settings. Once the images can be accessed again, image CDNs like Jetpack's should be able to access and cache the images again.

I hope this helps.

**Comment by iuzairjan** [comment]
But the Original images are loading

**Comment by jeherve** [comment]
They may be loading for you, but they're not available to the rest of the world I'm afraid, as you can see in the copy of the response I included above.

Here is a screenshot as well, if that can help:

<img width="1503" alt="Screenshot 2023-06-19 at 15 53 57" src="https://github.com/Automattic/jetpack/assets/426388/eb7c200d-70c9-4e48-936b-7c914b83746a">
