### ISSUE TITLE
Boost Image Size Analysis: Don't track stats when generating reports

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#31455]
### Impacted plugin

Boost

### Quick summary

Generating a report, causes a spike in Jetpack Stats.

### Steps to reproduce

1. Make sure you have Jetpack and the Boost Image Size Analysis set up and running.
2. Generate an Image Analysis report
3. Check Jetpack Stats - there should be a spike in site visits.

### A clear and concise description of what you expected to happen.

Running the Image Analysis report shouldn't affect Jetpack Stats.

### What actually happened

This was caused by a report.

<img width="1273" alt="CleanShot 2023-06-20 at 13 07 14@2x" src="https://github.com/Automattic/jetpack/assets/11799079/8462b075-fd40-4ec6-94c4-0cb58f2bbac8">

### Impact

One

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by thingalon** [comment]
Feels like a dupe of https://github.com/Automattic/boost-cloud/issues/176

**Comment by dilirity** [comment]
You're right! Closing :)
