### ISSUE TITLE
Paid Stats: Add purchase status support to Odyssey

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#31477]
Calypso needs to know whether the site purchased Stats, so we'll need to add purchase data to Odyssey, probably related:

https://github.com/Automattic/jetpack/blame/60ad7fd2f35a5dc6f449e75c627064430961721e/projects/packages/stats-admin/src/class-odyssey-config-data.php#L85

**Comment by jsnmoon** [comment]
I figure this will be much easier to implement after https://github.com/Automattic/wp-calypso/issues/78653 and https://github.com/Automattic/wp-calypso/issues/78654, so I'll put this back on the todo list for now 🙂 

EDIT: Would assigning the results of `CurrentPlan::get()` to `config.intial_state.sites.items.${site_id}.plan` be sufficient?

**Comment by kangzj** [comment]
> EDIT: Would assigning the results of CurrentPlan::get() to config.intial_state.sites.items.${site_id}.plan be sufficient?

I think we'll need `config.intial_state.sites.items.${site_id}.plan` and `config.intial_state.sites.items.${site_id}.products`. I'm not very sure about the format - we could probably checkout how it's generated on WPCOM. Here's what they are like:


![Image](https://github.com/Automattic/jetpack/assets/1425433/da7623d9-e9b4-47b5-8edd-bd3cf6c5efd2)
