### ISSUE TITLE
Jetpack Docker: sftp container fails

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#31498]
### Impacted plugin

None / Other

### Quick summary

When starting up the `jetpack docker up`:

```
jetpack_dev-sftp-1        | [/usr/local/bin/create-sftp-user] Parsing user data: "wordpress:wordpress:1001"
jetpack_dev-sftp-1        | cat: '/home/wordpress/.ssh/keys/*': No such file or directory
jetpack_dev-sftp-1        | /usr/local/bin/create-sftp-user: Error on line 90: cat "$publickey" >> "$userKeysAllowedFileTmp"
jetpack_dev-sftp-1        | /entrypoint: Error on line 60: create-sftp-user "$user"
```

### Steps to reproduce

1. Fresh Docker
2. `jetpack docker up`

See error. Confirm in Docker Desktop or tool of choice that everything else is running while sftp is exited.
![2023-06-21 at 4 56 PM](https://github.com/Automattic/jetpack/assets/88897/0eb0a22a-d328-483d-b1e1-448e548ce684)

### A clear and concise description of what you expected to happen.

SFTP should load

### What actually happened

It didn't.

### Impact

All

### Available workarounds?

There is no user impact

**Comment by anomiex** [comment]
It's an upstream issue. Filed https://github.com/atmoz/sftp/issues/377 about it.

There's a way or two we could work around, but they're kind of ugly so it'd be nicer if upstream will fix.

**Comment by kraftbj** [comment]
Cool. At least a workaround for us could be to add our public key to the directory. I'm okay saying that is the workaround for now vs us doing something hacky to work around the upstream.

**Comment by anomiex** [comment]
Yeah. An empty file would also work if you don't want to generate a key.

The least hacky workaround to commit to the monorepo would be similar, include an empty file (that's not a dotfile) in the repo or generate one on `jetpack docker up` so the container has something to find. The file could also contain `#`-prefixed comments I think. The downside being we'd have some weird extra file in there, of course.

**Comment by kraftbj** [comment]
A `README.md` describing the folder's purpose enough to work around the bug? That could be a way to both work around and improve it to explain what should go there, when it is used etc.

**Comment by anomiex** [comment]
If it's in the folder itself, every non-empty line would have to begin with `#` so sshd sees it as a comment when it gets dumped into `~/.ssh/authorized_keys` inside the container.

There's already [mention in the tools/docker readme](https://github.com/Automattic/jetpack/blob/trunk/tools/docker/README.md#sftp-keys).

**Comment by bluefuton** [comment]
I also ran into this one today and it cost me a fair bit of time. The workaround worked well.

No sign of movement on the upstream fix, so maybe we could consider the README.md idea that @kraftbj suggests?

<img width="1024" alt="Screenshot 2023-08-03 at 3 07 01 PM" src="https://github.com/Automattic/jetpack/assets/17325/a8dcbd6e-abe9-4a01-b39d-5f9c7360604e">
