### ISSUE TITLE
AI Assistant: improve JETPACK_AI_ERROR error detection

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#31507]
We need to keep polishing the process to detect the JETPACK_AI_ERROR error detection.

https://github.com/Automattic/jetpack/assets/77539/90b1682e-7e2b-4bd0-b87f-1f5ca7303157

**Comment by dhasilva** [comment]
Fixed here: https://github.com/Automattic/jetpack/pull/31518/files#diff-b220faa6b9ab83e6204db50283e09b04e59cb5c34a5ba74f37f2ca8650f3fe24L170

**Comment by dhasilva** [comment]
Closing as it should be fixed (though it needs to be applied in the Jetpack AI Client package as well). Feel free to reopen if that keeps happening on `trunk`.
