### ISSUE TITLE
Boost: Image Size Analysis - improve error reporting in UI

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#31505]
### Impacted plugin

Boost

### Quick summary

The reporting in the UI is currently showing the whole object. Reference - https://github.com/Automattic/jetpack/pull/31234/files#diff-d95de1504d73d554c3533b3c4e32f4dbbc5ddd99a0b82b94261b6e440b5c57f7R55

**Comment by thingalon** [comment]
Handled as a part of https://github.com/Automattic/jetpack/pull/31674

Now errors are expected to have unique statuses per error type. So far the only one is `error_stuck`. We can build on this as needed.
