### ISSUE TITLE
[Sync] Enhancement: Support HPOS orders for WooCommerce in sync package

### ISSUE THREAD

**Issue by vedanshujain** [Automattic/jetpack#31508]
### Impacted plugin

Jetpack Sync

### What

Add support to sync WooCommerce orders when HPOS is enabled

### How

WooCommerce's HPOS feature will soon be generally available and will be enabled by default. Currently, Jetpack's sync package only supports the post tables, which will stop working on the sites which have HPOS enabled but are not backing the data to posts (for WooCommerce orders data).

To support HPOS we would need to:

### Potentially add a new module for orders on various WooCommerce order lifecycle actions 

In [class-posts.php](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/sync/src/modules/class-posts.php) we are [listening on various posts lifecycle events](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/sync/src/modules/class-posts.php#L135-L156), we would need to add a similar listener for orders and listen to order lifecycle events as well. Perhaps, this should be done in a new module connecting it to the [JP Sync's listener](https://github.com/Automattic/jetpack/blob/bca061f2bc37d0384a8c093096896ba3d53ecfdc/projects/packages/sync/src/class-listener.php#L85).

Depending upon what makes most sense, this can be done either:
1. Using the posts events itself, but sending order data in post data compatible format.
2. Create new events and send order data with WC_Order structure.

### Create corresponding HPOS tables on the backup sites 

If earlier we chose to create new events for orders, in WP.COM infra, we would need to create HPOS replica tables which can handle the new events.

**Comment by jeherve** [comment]
cc @Automattic/jetpack-kernel

**Comment by zinigor** [comment]
This is now shipped with #32530 and related diffs.
