### ISSUE TITLE
Boost: Getting Started flow loop on plugin deactivation/activation

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#31540]
### Impacted plugin

Boost

### Quick summary

After installing Boost on a website, setting it up and deactivating and activating it, when setting it up again the "getting started" page keeps showing up despite it's set up.

### Steps to reproduce

1. Install Boost;
2. On the getting started screen, choose the free option (haven't tested with premium);
3. After being redirected to the Boost UI, go to Plugins and deactivate Boost;
4. After that, activate it;
5. From the getting started screen, choose the free option again (haven't tested with premium);
6. After being redirected to the Boost UI, this time refresh the page;
7. You will be presented with the Getting started screen again;
8. From this point forward, what ever you do, opening the Boost UI, would present the Getting started screen.

### A clear and concise description of what you expected to happen.

Once the plan is chosen, the getting started screen shouldn't show up.

### What actually happened

The getting started screen kept showing up.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

If you completely remove the plugin after deactivating, installing and activating it again will not cause the getting started screen to show up.

**Comment by thingalon** [comment]
You know, I suspect this is the cause:

https://github.com/Automattic/jetpack/blob/c1677fb0c1ac69d1739d0e23d3299a1c7a95fa0c/projects/plugins/boost/app/class-jetpack-boost.php#L206-L231

We delete settings en masse directly from the database on deactivation. We can expect this to cause issues in heavily cached environments like Atomic.
