### ISSUE TITLE
Boost: Image Size Analysis - UI not updating after subsequent analysis report requests w/o page refreshing

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#31545]
### Impacted plugin

Boost

### Quick summary

When an analysis report finishes and another is requested, there are no more summary requests for the new (pending) report.

### Steps to reproduce

1. Setup Boost with Image Size Analysis;
2. Enable Image Size Analysis and generate a report;
3. After that, don't refresh the page and request another report;
4. Wait for that to finish and for the UI to reflect that;
5. After the second report is done, request another report;
6. Check the Network requests and there will be no requests to `image-size-analysis-summary` - just one;
7. Wait a bit and refresh the page - the report will show as finished (it actually is).

### A clear and concise description of what you expected to happen.

Requesting a report should update the UI accordingly.

### What actually happened

The UI didn't get updated. A page refresh was necessary, to see the report progress.

### Impact

One

### Available workarounds?

There is no user impact

**Comment by thingalon** [comment]
Duplicate of #31459
