### ISSUE TITLE
AI Extension: Implement a way to cancel the current suggesting process.

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#31590]
At the moment, it's not feasible to cancel the request process within the AI Extension. Let's brainstorm solutions to address this issue.

**Comment by nunyvega** [comment]
Moving this to on hold because we'll be trying a different approach:
pe4Cmx-1p7-p2#comment-685

**Comment by retrofox** [comment]
PR moved too

**Comment by lhkowalski** [comment]
I am closing this since this is not a problem anymore. All the actions now trigger the Assistant component, that does provide a cancel button to cancel any type of suggestion.
