### ISSUE TITLE
Republishing problem with publicize

### ISSUE THREAD

**Issue by 7zxkv** [Automattic/jetpack#31651]
### Impacted plugin

Jetpack, Social

### Quick summary

Publicize no longer publishes news from WP to facebook since June 29 (cet+2)

### Steps to reproduce

-

### A clear and concise description of what you expected to happen.

Hello,

From one day to the next, the news (articles) I automatically repost from wp to facebook via publicize no longer work (June 28 cet+2 = ok, June 29 = no).

I had exactly the same problem a year before and it had been solved by itself (a priori something in facebook had changed and I assume that publicize had perhaps been adapted but I don't know). 

So I didn't touch anything, no update of any kind was made. On the other hand, I saw this commit (https://github.com/Automattic/jetpack/commit/1be8506fa0a86d559a6bbf43369bf4562f708aa9) and I'm wondering if there isn't a connection given the date, but as nothing has changed (wp/jetpack version and overnight it doesn't work anymore...) I'm not sure. Anyway, I'm reporting it here because I don't know if it's "normal".

Best regards
(sorry for my broken English).

### What actually happened

It worked perfectly on June 28 (and all the days before), and from June 29 it didn't work anymore. There was no change on my part at any level (I insist).

### Impact

Most (> 50%)

### Available workarounds?

No and the platform is unusable

**Comment by jeherve** [comment]
> On the other hand, I saw this commit (https://github.com/Automattic/jetpack/commit/1be8506fa0a86d559a6bbf43369bf4562f708aa9) and I'm wondering if there isn't a connection given the date

Those changes haven't yet been released, so that cannot be impacting your experience. The problem must lie elsewhere. Could you contact us via [this contact form](https://jetpack.com/contact-support/?rel=support&hpi=1) and give us more details about your site in your email? We'll be happy to take a closer look and try to understand what happened.

Thank you.
