### ISSUE TITLE
Likes: Label in toolbar is mis-aligned in WP 4.4

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#3167]
I just did a fresh testing install of WP 4.4, and activated everything in Jetpack. I noticed the Like button in the toolbar is pretty misaligned:

![screen shot 2015-12-16 at 3 26 04 pm](https://cloud.githubusercontent.com/assets/108942/11855803/986c8b9e-a409-11e5-8eec-1f25f50c3a0a.png)

That's loaded as an iframe from wp.com, so it'll need to be fixed there, but I believe it's only used for Jetpack sites now, which is why I'm creating this issue here.

**Comment by beaulebens** [comment]
In case it's relevant, that was in Chrome/latest.

**Comment by kraftbj** [comment]
Duplicate, I believe, of #3002
