### ISSUE TITLE
Jetpack Boost 1.9.3: Images and other elements not loading unless logged in

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/jetpack#31672]
### Impacted plugin

Boost

### Quick summary

Initial report in 6493580-zd-woothemes (**Requested a follow-up in 6493764-zd-woothemes when this is resolved.**)

With Jetpack Boost active and updated to 1.9.3, images on the site fail to load unless logged in. User and I confirmed this was replicated in multiple browsers and devices (though only when un-proxied).

**EDIT:** Other reports have come in where this has affected other elements, including slideshows/carousels, mobile menus, and the cookie and consent banner widget.

### Steps to reproduce

1. Activate Jetpack Boost 1.9.3 on an Atomic site
2. View the site

### A clear and concise description of what you expected to happen.

Images should load as expected.

### What actually happened

Images all fail to load. Browser console showed a few repeated errors for a `/_jb_static/...` file failing to load. 

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**EDIT:** Clearing the site's cache in CLI has been shown to resolve issues. Deactivating Jetpack Boost is a temporary solution otherwise. There is no need to downgrade to a previous version except for troubleshooting purposes. 

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

I've been unable to replicate this myself so far, including on an AT test site using the same `Seedlet` theme and similar plugins. The customer did report that the issue started today (July 3) and was resolved on deactivating Jetpack Boost.

Checking with this customer now to see if they'll consent to us reactivating Boost on their site temporarily to get more details. Creating this issue early in case other reports come in before we hear back.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Atomic – **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- I'm so far unable to replicate this; tested unproxied, with Jetpack Boost 1.9.3 and Gutenberg versions 16.0.0 and 16.1.0 - in all instances, images load for a logged out viewer, in Chrome and Firefox. 

📌 ACTIONS 
- Requested author feedback

📌 Message to Author
- @jp-imagines any chance you are seeing this already resolved on your side as well? I see you were able to repro with the customer - I'm wondering if this was a temporary issue. Thanks for taking another look!

**Comment by darcie** [comment]
Possibly in 6494092-zen, difficult to reproduce but seeing the same missing images on Safari and Chrome iOS. AT site. The same missing `_jb_static/jquery-ui-styles.css.map` and `_jb_static/index.min.js.map` appear in the console.

This appears to impact selecting variations and adding them to the cart in WooCommerce.

**Comment by thingalon** [comment]
@jp-imagines can you please include a link to the user's site in this issue? We don't have access to the zendesk ticket.
@darcie - also can't view your ticket either.

Thanks for trying to reproduce, but we need to find an instance of the issue to examine.

**Comment by thingalon** [comment]
@jeherve sent me the URLs. For posterity, they are:
- https://loveforgardens.com/ (WoA)
- https://relaxjoga.com/termekkategoria/hangrelaxacio-esemenyek/ (also WoA)

I've taken a preliminary look at both sites, and can't spot anything that might explain the behaviour they've seen. Once we have the user's permission, I would like to turn on Jetpack Boost (I can do it myself using the wp-cli interface in WoA), take some measurements and run some tests, then turn Boost back off for them. Their site should only have a short period of time with Boost enabled while I gather information.

Also, thanks for testing Atomic in general to confirm that this isn't a problem affecting all WoA users. I've also tested, and could not reproduce. I can sleep soundly tonight knowing that we haven't set all of WoA on fire 🔥

**Comment by filipanoscampos** [comment]
Another case here 6496178-zd-woothemes

**Comment by jp-imagines** [comment]
> any chance you are seeing this already resolved on your side as well? I see you were able to repro with the customer - I'm wondering if this was a temporary issue.

Still waiting to hear back from the initial customer to see if we can temporarily reactivate Boost on their site to try reproducing again. I'll update here when we hear back.

It seemed pretty clear-cut while I was chatting with them, but I haven't been able to replicate any issues on my own sites.

**Comment by jp-imagines** [comment]
Just came across some similar behavior on another WoA site (chat: 6496484-zd-woothemes; follow-up: 6496639-zd-woothemes). In this case, images were loading, but the homepage's carousel area was broken with Boost active (and the customer confirmed the issue started yesterday). Only one image appears with no auto-scrolling or options to move to the next image, and all overlaid text is invisible:

Boost inactive, or while logged in: 
![sOkPfi.png](https://github.com/Automattic/jetpack/assets/5630717/bc4f97ca-a90e-4b96-b615-9abbc37936a0)

Boost active, or logged out:
![9Ho99M.png](https://github.com/Automattic/jetpack/assets/5630717/5a163253-8008-4857-85b5-7fb8e75a2317)

Browser console error:
```
GET https://theoverclockingpage.com/_jb_static/??-eJyVkd1OwzAMRl+IrIJpU7lAPApykyxzk9hR7a6Up1/Gz0DruOilP5/j2MpUjGVST9qUNAYkaXqvBWw0HbPoT/V28uR4aGBUzqCK9sphhuCNddQ4rMK13PTyMC3HW+4S2yhfdP8bGKDqKvJ6U5FmmbD4wSChIiT88MPqMQnDUTt+Xy2GGtxIevTZV3QGZ54uMMEJw73zFqRELHUXiubAdhRzwNuNlkpCG78hJJtGV9s1//wMSQzOu01GuoNkEKZh/tP995WQuINUqdf88rhv2+1+1z5vzzde2ag= net::ERR_HTTP2_PROTOCOL_ERROR 200
```

Customer reported that images were initially not loading and did eventually get images to load again, though they're not sure how. They did note that "some script was taking more than 30s to load; after it loads, the images loads too."

In case it helps, their current Boost settings:
* Optimize CSS on
* Defer non-essential JS on
* Lazy loading off (customer reports this wasn't working properly and was causing issues with image loading, so they disabled it)
* Image Guide off
* Concatenate JS on
* Concatenate CSS on
* Image CDN on

Theme: `Dyad 2`

Edited to add: customer reports their mobile menu wasn't opening with Boost active. It works again now that it's been deactivated.

**Comment by jp-imagines** [comment]
Making a quick note here that this is being further discussed in p1688477218221409-slack-C016BBAFHHS.

**Comment by dilirity** [comment]
**For now - if a user reports a problem with the images not loading or JS problems in general, try clearing the website cache first.**

There's no proper solution yet, but it might be related to Atomic cache not clearing after (auto) updating to Boost 1.9.3.

---

Some notes after spending several hours debugging (cc @thingalon).

---

### Summary

After taking a look at the sites reported having the issue, it seems they all had Boost 1.9.1 running with JS or CSS concatenation enabled. Some reports, noted, that images were missing and mobile menus weren't working. Photon and lazy loading were mentioned several times and it was reported that enabling/disabling them didn't change anything. This was mixed with reports that things were working while proxied and logged in.

### Investigating

Some back and forth between slack threads (p1688458302159019-slack-C03TY6J1A, p1688477218221409-slack-C016BBAFHHS and p1688463992541799-slack-C0CMN0V97) and debugging done by fellow a12s, I pinpointed the problem to Atomic cache. For some reason, cache wasn't cleared after updating to Boost 1.9.3.

### Reproducable? Somewhat.

I managed to reproduce the issue by doing the following (I did it manually via filezilla and the plugins UI):
- disabled Boost auto updates;
- downgraded to 1.9.1;
- visited a few pages to make sure everything worked (both proxied and not);
- after that, I updated to latest Boost (1.9.3);
- I visited a page with Jetpack Slideshow (reported as not working) while proxied and it was working. However, unproxied (personal PC), I got this:

![image](https://github.com/Automattic/jetpack/assets/11799079/f230ca6a-70cf-427f-a66a-588320644c7a)

Adding a get param to the URL confirmed that the page is cached. I cleared it via wp-cli (thanks for the tips @jp-imagines) and everything fell into place.

Now the weird part is, that I wasn't able to reproduce this multiple times after that.

I tried doing the same via WP-CLI, but for some reason it didn't work. I suspect cache got cleared somehow while I was doing this.

Steps provided by @jp-imagines:

- Install the latest version (method doesn’t matter)
- wp plugin auto-updates disable jetpack-boost
- wp plugin install jetpack-boost --version=1.9.1 --force

**Comment by davipontesblog** [comment]
Reported here 6497434-zen.

**Comment by the-misha** [comment]
Another user report: 6497372-zd-woothemes

**Comment by mgozdis** [comment]
Another user report: 6497324-zd-woothemes

**Comment by jp-imagines** [comment]
Another report in 6497822-zd-woothemes:

* Mobile menu wouldn't open
* Legacy "Cookies and Consent Banner" widget wouldn't close

Clearing cache fixed their issues.

**Comment by mgozdis** [comment]
Another report here: 6497828-zd-woothemes
Mostly mobile experience broken where clearing cache fixed their issue temporarily. They had Jetpack Boost and Page Optimize active. Deactivating Jetpack Boost resolved issue.

**Comment by csabarakasz** [comment]
6495045-zd-woothemes

Post Carousel is not working because of Jetpack Boost v 1.9.3

Force installed version 1.9.1, flushed cache. -> Carousel works again. Installed v1.9.3 -> Carousel still works.

**Comment by jp-imagines** [comment]
Another in 6498099-zd-woothemes. Clearing cache fixed the issue.

Added the known workaround (clearing cache) to the main issue report up top. (cc @csabarakasz: you shouldn't need to downgrade to `1.9.1`. Just a simple cache flush should hopefully do the trick.)

**Comment by csabarakasz** [comment]
@jp-imagines Yes, thank you. First, I did downgrade, but then I upgraded again, and after the cache flush things worked as expected. Thanks

**Comment by hacchism** [comment]
Another report in 6494877-zd-woothemes

Clearing cache fixed their issues.

**Comment by Greatdane** [comment]
6498581-zd-woothemes

**Comment by Greatdane** [comment]
6498644-zd-woothemes

Had to disable the plugin, we cleared cache yesterday in 6495045-zd-woothemes but it only seemed like a temporary fix.

**Comment by retnonindya** [comment]
6498800-zd-woothemes

Deactivated the plugin Jetpack Boost and Smush -- and cleared site cache

URL: https://rel8.app/

Update: Thanks, @thingalon, for the nudge. I rechecked the site and reactivated Jetpack Boost. The image stays.

**Comment by thingalon** [comment]
Can HEs posting links to zendesk tickets here _also please include the site url?_

We on the boost team do not have access to these zendesk tickets.

**Comment by rw-ye** [comment]
6498522-zd-woothemes

Site: https://amysenter.com/

Deactivated the Jetpack Boost plugin and cleared the site cache.

**Comment by thingalon** [comment]
Hi all.

A fix is on its way: https://github.com/Automattic/jetpack/pull/31692

I think I have isolated the issue to an odd corner of the caching layer on atomic.

**Comment by thingalon** [comment]
Ok I believe I have a fix - https://github.com/Automattic/jetpack/pull/31692 - there are testing instructions in there that anyone with access to an atomic site of their own and the jetpack beta plugin can test!

I'd love feedback to ensure this fixes it

If it does I want to get it reviewed by another dev, and get a patch release out ASAP

**Comment by Greatdane** [comment]
6499045-zd-woothemes - https://sptraining.org

**Comment by csabarakasz** [comment]
6496417-zd-woothemes

The slider not working. `cache flush` worked.

**Comment by zyousafi** [comment]
6499177-zd-woothemes

I had to disable the plugin, we cleared the cache yesterday for them but it only seemed like a temporary fix

Site URL: https://charlottepeacock.co.uk

**Comment by csabarakasz** [comment]
6499174-zd-woothemes

Seems related. Site loads broken. After flushing the cache site loads well again. 

Update: flushing the cache didn't solve it. The issue returned when loading the site again. Deactivating Page Optiimze and letting JP Boost update to v1.9.3 solved it.

**Comment by csabarakasz** [comment]
6499316-zd-woothemes

Images are not loading while not proxied. Clearing the cache only solved it temporarily. Force downgrade JP Boost solved it.

**Comment by i11za** [comment]
Another report here: 6499557-zd-woothemes
Deactivating Jetpack Boost resolved the issue.

**Comment by csabarakasz** [comment]
6499470-zd-woothemes

I am also noticing more sites having conflicts with Page Optimize as well. This user's site would not load when JP Boost was deactivated, but when I deactivated Page Optimize as well, it worked. Running JP Boost, but not Page Optimize also broke the site. (Broke means the theme's site loading graphic would never go away and just kept "loading")

**Comment by filipanoscampos** [comment]
Another one, here: 6499657-zd-woothemes

**Comment by Gustavo-Hilario** [comment]
Another report: 6499693-zen

**Comment by marutim** [comment]
Another report here: 6499174-zd-woothemes

Had to deactivate the JP Boost plugin and clear the site cache to fix the issues with the site images.

Following up with the user here: 6499896-zd-woothemes

**Comment by csabarakasz** [comment]
6499888-zd-woothemes

I deactivated Jetpack boost.

**Comment by Gustavo-Hilario** [comment]
Another report: 6499885-zen

**Comment by Gustavo-Hilario** [comment]
Another report: 6499660-zen

I needed to deactivate Jetpack Boost and clear the site's cache.

**Comment by thingalon** [comment]
I just released Jetpack Boost 1.9.4 with a fix for this. Please encourage affected users to upgrade.
If they don't immediately see results, please flush their cache - as they may be rocking out-of-date files.

pc9hqz-1QQ-p2

**Comment by jorpdesigns** [comment]
Initially reported in 6496795-zd-woothemes

I just cleared the cache and confirmed the missing elements now load (after the fix mentioned in the comment above).

**Comment by wojtekn** [comment]
Another report: 6497295-zd-woothemes
