### ISSUE TITLE
Add Skype share button to Jetpack

### ISSUE THREAD

**Issue by paunikar** [Automattic/jetpack#3170]
Hello, I am following up on a twitter request by one of your users. We recently launched the Skype Share button. The configuration page is available here: https://www.skype.com/en/create-share-buttons/

We offer a JS button with SDK. We also offer a raw URL option. The URL is: 
https://web.skype.com/share?url=<urlencoded_url_to_share>&lang=en-US&flow_id=<GUID>&source=JetPack

Expected usage, with ideal window size: 
function shareUsingSkypeRawLink() {
window.open('https://web.skype.com/share?url=<urlencoded_url_to_share>&lang=en-US&flow_id=<GUID>&source=JetPack’, ‘_blank', 'toolbar=no, scrollbars=yes, resizable=yes, width=305, height=665');
              return false;
}
 <a href=‘javascript:void(0)' onclick="shareUsingSkypeRawLink()"> Share using link </a> 

Asset available here: 
Skype logo file is available here: https://swx.cdn.skype.com/skypewebsdk/shareButton/v/latest/assets/images/s_logo.svg

We also have a WP plugin: https://wordpress.org/plugins/skype-share-button/

Please let me know if you need any other information. 
Thanks, 
Amit Paunikar
Product@Skype

**Comment by paunikar** [comment]
@jeherve any update on this? let me know if you need any additional information to move this forward.

**Comment by jeherve** [comment]
@paunikar See #3171. The Pull Request was reviewed, and will be included in the next Jetpack release.

**Comment by paunikar** [comment]
Thanks @jeherve Any approximate timing on that, so we can be ready at our end and monitoring metrics?

**Comment by jeherve** [comment]
It should be released before the end of the month, after we go through a Beta testing phase, and if we find no bugs during testing.
