### ISSUE TITLE
Paid Stats: product activation/deactivation

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#31712]
@dognose24 brought this up because he found Jetpack site has a great latency to reflect the purchase/removal of Stats products.

- We should at least force the update of plan/products for Jetpack. Example: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Sjcpbz%2Qovyyvat%2Scebqhpgf%2Swrgcnpx%2Qfbpvny.cuc%3Se%3Q0s7ss045%2354-og
- Also consider if there are any other initialization or termination process we want to add
  - Refresh the latest purchases via Jetpack API endpoints for Odyssey Stats: https://github.com/Automattic/wp-calypso/pull/79314

cc @jboland88 @Automattic/martech

**Comment by dognose24** [comment]
I found that **_synchronization should be done_** (fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Swrgcnpx%2Spynff.wrgcnpx%2Qchepunfrf.cuc%3Se%3Q1nooq468%2344-og) after the **_activation/deactivation is made_** (fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Sjcpbz%2Qovyyvat%2Sfgber%2Qfhofpevcgvba.cuc%3Se%3Qs4087q04%233927-og). But still have no idea about the latency of synchronization on the Jetpack side.

**Comment by kangzj** [comment]
Nice sleuthing 👍 I believe we can mark the task as done now.

> But still have no idea about the latency of synchronization on the Jetpack side.
Requests could fail under some circumstances, we'll still have [the async purchase update](https://github.com/Automattic/wp-calypso/pull/79314) mechanism anyway. 

Thanks for figuring all these out. Great job 👍
