### ISSUE TITLE
AI Assistant: add error handling when a request is too long

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#31728]
When the request is too long, the API will respond with a `400 Bad Request` status code, with the following body:

```
{
  error: {
    message: "This model's maximum context length is 4097 tokens. However, your messages resulted in 30808 tokens. Please reduce the length of the messages.",
    type: 'invalid_request_error',
    param: 'messages',
    code: 'context_length_exceeded'
  }
}
```

We need to handle this case and map it to a friendly error for the user.

**Comment by nunyvega** [comment]
We should also merge the change so the [query request is a POST request](https://github.com/Automattic/jetpack/pull/31128)

While not directly related, it will help us not fail to send the request from the editor when the post content is long.

**Comment by nunyvega** [comment]
Now that the post requests PR was merged I'm getting a 503 on long posts, getting the error message
> Jetpack AI services are currently unavailable. Sorry for the inconvenience.

**Comment by dhasilva** [comment]
@lhkowalski Is this still happening as we updated to longer models?

**Comment by dhasilva** [comment]
Tested with a very long lorem ipsum text, we get a `503` response as Álvaro said.
