### ISSUE TITLE
Feature Request: static brotli support *or* callout hook

### ISSUE THREAD

**Issue by donbowman** [Automattic/jetpack#31724]
### Impacted plugin

Super Cache

### What

i have switched to brotli compress from gz. static is more efficient on server

### How

Today wp super cache creates /dir/index-https.html. W/ brotli dynamic enabled (nginx plugins), this works, but is a bit hard on the server.
I also have brotli static enabled in nginx. If i compress /dir/index-https.html to /dir/index-https.html.br, the server prefers the file, and serves the pre-compressed. Much more efficient, much faster.

In wp-super-cache, if either:
a) there was a callback or hook called when a file was cached, i could implement in functions.php
b) wp-super-cache natively supported brotli like it does w/ gzip, it could create the static file automatically, creating both /index-https.html and /index-https.html.br

**Comment by jeherve** [comment]
Thanks for the suggestion. This is currently tracked here: Automattic/wp-super-cache#906 

Closing this issue as duplicate.
