### ISSUE TITLE
AI Assistant: Parse Gutenberg syntax and not only markdown

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#31723]
Initially we won't use streaming mode.

Related initial changes:
[AI Assistant Gutenberg experiment](https://github.com/Automattic/jetpack/pull/31708/files)

**Comment by retrofox** [comment]
Let us handle this situation in the most effective manner. It would be best to progressively display the content upon receiving the endpoint response. However, if this is not feasible, we could incorporate an animation or similar feature to notify users that the content is being generated.
