### ISSUE TITLE
AI Assistant: Work on new prompt system to request gutenberg syntax instead of markdown

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#31721]
This will only be used internally. The goal is to have the assistant replies using blocks so we can also generate layouts
Related initial changes:
[AI Assistant Gutenberg experiment](https://github.com/Automattic/jetpack/pull/31708/files)

**Comment by retrofox** [comment]
It's done. Currently, and beyond it requires enhancements, the apps is able to generate content based on Gutenberg syntax.
