### ISSUE TITLE
Enhancement: Boost ISA - add tracking events

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#31741]
### Impacted plugin

Boost

### What

Add tracking events when interacting with the Image Size Analysis.

### How

- See full report/View report in progress button;
- Analyze again link
- Group links
- Clicking the "Edit page" or "Fix on page" buttons.
- expanding collapsing issues?
- total issues found per report (individual groups also).

**Comment by thingalon** [comment]
Search for `recordBoostEvent` in the codebase.

**Comment by thingalon** [comment]
Things worth tracking: 
- Number of issues found (track from wpcom)
- Requests for an image analysis (track from wpcom) in the API endpoint for kicking off a report.
- Clicking edit page (do it in javascript - `recordBoostEvent`)

**Comment by dilirity** [comment]
This was done in #31840.
