### ISSUE TITLE
Social: remove Twitter logo from dashboard splash banner

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#31753]
When you first install and activate the Social plugin, you're greeting with a screen inviting you to connect your site to WordPress.com. The image on that screen includes a Twitter logo. Given that we've had to remove Twitter features from the plugin, maybe that logo should be removed, and replaced by another.

**Comment by pablinos** [comment]
@keoshi, @ilonagl & @jeffgolenski Is this something one of you could help us with please? This is the splash screen Jeremy is talking about:

![Image](https://github.com/Automattic/jetpack/assets/96462/da6cefcc-d148-4977-9590-602a80057439)

and this is the image used:

![Image](https://github.com/Automattic/jetpack/assets/96462/2d3f420b-bf7f-4101-a56e-882c4c768af5)

I suppose we could simply swap the logo for Tumblr or something?

**Comment by keoshi** [comment]
We can probably use the same we have on jetpack.com/social — that way everything is aligned.

https://s0.wp.com/wp-content/themes/a8c/jetpackme-new/images/social/hero-social-2x.png

![image](https://github.com/Automattic/jetpack/assets/390760/77cc95c7-17e3-4b82-b552-fecdf6167ba6)

**Comment by jeffgolenski** [comment]
I second @keoshi's idea. What do you think @pablinos? something something "two birds, one stone" something something.

**Comment by pablinos** [comment]
Excellent plan! Thank you @keoshi and @jeffgolenski. We'll get this updated
