### ISSUE TITLE
Jetpack Stats showing incorrect data

### ISSUE THREAD

**Issue by advwebin** [Automattic/jetpack#31775]
### Impacted plugin

Jetpack

### Quick summary

We have been using Jetpack stats for years.
The views almost always are close to the number of pageviews from Google Adsense Pageviews ~5% less in Google Adsense.

Since updating to 12.2 we are seeing a disparity of over 60% in the views number.

And when I updated to 12.2 the connection was showing an error.
I rolled back to 12.1.1 and the stats were fine.

After updating to 12.3 the stats views were down again by 1/3 again.
And this time there were no connection errors showing up in the Jetpack Debug page.

But when I checked the same in somethreads, I was checking https://jptools.wordpress.com/debug/

Could not fetch your site data

We were unable to fetch the data from your Jetpack-powered site, the communication channel seems to be broken.

### Steps to reproduce

https://jptools.wordpress.com/debug/

Could not fetch your site data

We were unable to fetch the data from your Jetpack-powered site, the communication channel seems to be broken.

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by jeherve** [comment]
Thanks for the feedback. Could you contact us via [this contact form](https://jetpack.com/contact-support/?rel=support&hpi=1) and give us more details about your site, so we can take a closer look at the issue with you and investigate?

Thank you.

**Comment by advwebin** [comment]
Hello Jeremy,

I have submitted the contact form.
Please let me know if you need anything else. 

Note: I have disconnected and reconnected the site as well. That didn't work either.
