### ISSUE TITLE
Boost: Image guide is broken in trunk

### ISSUE THREAD

**Issue by anomiex** [Automattic/jetpack#31788]
### Impacted plugin

Boost

### Quick summary

Image guide is not functioning in trunk when Jetpack is also installed.

### Steps to reproduce

1. Install Boost trunk and Jetpack (e.g. using JN). Activate both with free plans.
2. Enable the image guide feature.
3. Create a post using an image block with a Pexels image. Publish it.
4. Visit the post.

### A clear and concise description of what you expected to happen.

Image guide should work.

### What actually happened

Image guide does not show any UI on the image.

In the browser console, I see
```
Uncaught (in promise) TypeError: t is null
```
with reference to what appears to be code generated from https://github.com/Automattic/jetpack/blob/9d4b8438027a44f34be36c0b49849f8737f479ce/projects/plugins/boost/app/modules/image-guide/src/index.ts#L134

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

Bisect points to https://github.com/Automattic/jetpack/pull/31504 as the first commit with the problem. I note that commit dropped a `.filter( image => image !== null )`. After some subsequent refactors, that should probably be restored to this function: https://github.com/Automattic/jetpack/blob/9d4b8438027a44f34be36c0b49849f8737f479ce/projects/js-packages/image-guide/src/find-image-elements.ts#L58-L90
The doc block for that function claims it returns `MeasurableImage[]`, but as written some elements of the array can be null.

**Comment by anomiex** [comment]
Ping @donnchawp @thingalon @dilirity as people who were involved with that PR.

**Comment by thingalon** [comment]
Thanks for testing and investigating this @anomiex.

Though I was unable to reproduce the issue with the instructions:
![image](https://github.com/Automattic/jetpack/assets/1369626/eb33d84e-ede3-4383-8826-4d33be481919)

I agree with your analysis that the code appears to be missing an important filter to remove nulls. Looks like that code-path is for handing broken background-image urls.

**Comment by anomiex** [comment]
Confirmed that it's fixed in the JN site I was using for testing after updating to trunk.

Taking a closer look, on my test JN site the null was coming from a `<span id="wpnt-notes-unread-count" class="wpnt-loading wpn-read">` that has `background-image` set to a gradient via [a stylesheet](https://s0.wp.com/wp-content/mu-plugins/notes/admin-bar-v2.css?ver=12.3-202328-lite). 🤷
