### ISSUE TITLE
Invalid HTML tags in translations cause the render error on jetpack-subscriptions

### ISSUE THREAD

**Issue by lee-heejin** [Automattic/jetpack#31793]
### Impacted plugin

Jetpack

### Quick summary

I've found an invalid HTML tag usage in Jetpack Korean translations:

### English:
`<postPublishedLink>%1$s</postPublishedLink> was sent to <strong>%2$s %3$s</strong>.`

### Korean:
`<postPublishedLink>%1$s</postPublishedLink>이(가) %3$s</strong> <strong>%2$s명에게 발송되었습니다.` (invalid usage of strong tags)

https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/ko/default/?page=2

and it causes the render error for jetpack-subscriptions in the editor:
![image](https://github.com/Automattic/jetpack/assets/53720982/7e159062-67c4-4c76-9cb2-a3d44126c928)

### Steps to reproduce

1. Set the site language to Korean
2. Open the editor
3. jetpack-subscriptions error will appear

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by jeherve** [comment]
I see the translation was edited yesterday, so things should start working again once translations will be updated on your site. Could you go to Dashboard > Updates, update translations if necessary, and let us know if things start working again?

Thank you.

**Comment by lee-heejin** [comment]
It's fixed now. Thanks!
