### ISSUE TITLE
Subscription block: allow modify button label

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#31799]
### Impacted plugin

Jetpack

### What

Allow modify button's "subscribe" label

### How

<img width="678" alt="Screenshot 2023-07-11 at 10 57 27" src="https://github.com/Automattic/jetpack/assets/87168/6a0e7dbb-f8fa-4abc-a363-83a3172676bc">

**Comment by pkuliga** [comment]
Closing this one since changing it is already possible.

![2024-03-06 21 31 22](https://github.com/Automattic/jetpack/assets/4068554/cee489e5-d2ca-4efd-bec3-7bd74429fb4e)
