### ISSUE TITLE
Add Telegram SVG Icon

### ISSUE THREAD

**Issue by navjotjsingh** [Automattic/jetpack#3181]
Telegram allows to link via profile urls (https://telegram.me/userid ). Can you please add support for Telegram via the Genericons library?

SVG Icon available: https://commons.wikimedia.org/wiki/File:Telegram_logo.svg

**Comment by navjotjsingh** [comment]
Telegram also allows you to share posts. Format is

https://telegram.me/share/url?url=<url>&text=<text>

So if sharing support for it can be added, it would be great.

**Comment by jeherve** [comment]
> Can you please add support for Telegram via the Genericons library?

If you'd like to see a new Telegram icon added to Genericons, I'd recommend opening a new issue here:
https://github.com/Automattic/Genericons/issues/new

> if sharing support for it can be added, it would be great.

I created #3181 to track your suggestion.

Until we add Telegram support to Jetpack, I'd recommend installing this plugin:
https://wordpress.org/plugins/telegram-sharing-button-for-jetpack/

**Comment by navjotjsingh** [comment]
I would have asked at Genericons but they have stopped taking any more requests.

**Comment by navjotjsingh** [comment]
Is there any way of disabling Jetpack's version of Genericons? I created my own custom copy but can't Jetpack's copy is taking precedence.

**Comment by georgestephanis** [comment]
Sure, you can always deregister a stylesheet and reregister your own.

https://github.com/WordPress/WordPress/blob/77e365efbf2e499e2ed11d29c101ea466cf1ceed/wp-includes/functions.wp-styles.php#L119-L132

That being said, why do you need to call your custom font 'genericons' ?  Why not just have make `navjotjsinghicons` or something with the custom icons you want to use and run it beside canonical genericons?

**Comment by jeherve** [comment]
> I would have asked at Genericons but they have stopped taking any more requests.

I just talked with the current maintainer of Genericons, and he pointed me to this GitHub issue:
https://github.com/Automattic/Genericons/issues/54

It looks like you're right. In order to keep Genericons light, we won't be able to keep adding icons. Luckily, you can fork the project and create your own set.

> Is there any way of disabling Jetpack's version of Genericons?

Sure thing. Something like this should do the trick:
https://gist.github.com/georgestephanis/6106105
