### ISSUE TITLE
Newsletter heading appears in post list - even when newsletter not used

### ISSUE THREAD

**Issue by edent** [Automattic/jetpack#31831]
### Impacted plugin

Jetpack

### Quick summary

I do not use JetPack's "Newsletter" service. This morning, my posts page received an extra `<th scope="col" id="newsletter_access" class="manage-column column-newsletter_access"><span>Newsletter</span></th>`

![Screenshot showing the newsletter heading.](https://github.com/Automattic/jetpack/assets/837136/f01c241e-3e01-4a9c-a004-4f5319664506)

I have searched through all the JetPack options and I cannot see a way to disable it. 

### Steps to reproduce

1. Wake up one morning, the sun is shining, everything seems fine.
2. Open your blog to see what delightful posts you have scheduled.
3. Stare in bemusement at this new entry on the posts list
4. Search in vain for a way to disable it 
5. Post on GitHub.

### A clear and concise description of what you expected to happen.

I should have been asked if I wanted to enable something new.

### What actually happened

This was forcibly put on my website. There is no way to disable it.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

Appears to be caused by

https://github.com/Automattic/jetpack/blob/3cc7ad93d98d6ac3e19dc9cc2ebe2d17f21f5295/projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php#L117

**Comment by jeherve** [comment]
Thanks for the report. Is this happening on your personal site? I'm asking because you mention that you do not use Jetpack's Newsletter, but I do see the subscription widget in the sidebar in your site's footer, as well as the subscription options under the comment form. 

The new "Newsletter" column is an extension of the Subscriptions feature, which is why you would see it on your site if you have activated the Subscriptions feature.

That said, if you do not use any of the newsletter options of the Subscriptions feature, the "Newsletter" column definitely won't be useful to you. For now, you should be able to remove it in the "Screen options" tab:


https://github.com/Automattic/jetpack/assets/426388/351eefd9-350c-469c-ab61-cd583fa9e8e1

**Comment by jeherve** [comment]
Thinking further, I wonder if we should hide that column until we can detect that one has started using the "Newsletter" feature. @Automattic/zap What do you think about adding that tab only if one has used the feature once (basically by setting the Newsletter option to anything but the default for at least one post)?

**Comment by edent** [comment]
Thanks @jeherve - I can always count on you for a speedy and accurate response.
Yes, this is my personal site. I've had "subscribe by email" since before it was a JetPack feature. As you can see, there's no newsletter enabled.
![Screenshot showing a set of subscription settings](https://github.com/Automattic/jetpack/assets/837136/8dd34b94-e5a8-46a7-b148-cb779ec0e81d).

I can confirm that it can be removed from the "screen options". But can I recommend that it is not enabled until the feature is actually activated by the user?

**Comment by jeherve** [comment]
> can I recommend that it is not enabled until the feature is actually activated by the user?

Yes, that would be my suggestion as well. The feature is part of Subscriptions and is available to be used in the post editor, but I think we could opt to not display the column until one actually used the feature.

We'll keep discussing this on this issue, thanks again for bringing this up!

**Comment by lezama** [comment]
cc @Automattic/gold

**Comment by millerf** [comment]
Thanks for the ping. 

@jeherve This is a fairly easy fix, but I don't think we have any flag to know if the "feature was activated" (outside of the whole "Subscriptions" feature) ...

**Comment by jeherve** [comment]
> I don't think we have any flag to know if the "feature was activated" (outside of the whole "Subscriptions" feature) ...

Right, that's the issue. We would have to flag when post visibility is first toggled.

**Comment by crisbusquets** [comment]
> Thanks for the ping.
> 
> @jeherve This is a fairly easy fix, but I don't think we have any flag to know if the "feature was activated" (outside of the whole "Subscriptions" feature) ...

**Comment by crisbusquets** [comment]
> Right, that's the issue. We would have to flag when post visibility is first toggled.

While reading all the comments I came to the same conclusion. The moment someone writes and publishes a post and modifies this radio button to `Anyone subscribed` or `Paid subscribers only`, we could display that column in the post pages.

<img width="545" alt="Screenshot 2023-07-18 at 09 41 37" src="https://github.com/Automattic/jetpack/assets/25607244/d6ce9626-3997-40af-a9dc-58273ad0e997">

Is this feasible?

**Comment by otterbit** [comment]
Is there a way to remove this column through a code snippet?

I've tried 
`    add_filter('manage_post_posts_columns', function($columns) {
    	unset($columns['newsletter_access']);
    	return $columns;
    });`

Which used to work before, but now it doesn't.

**Comment by jeherve** [comment]
@otterbit This is the right snippet, but you would need to specify a different priority:

```php
add_filter(
	'manage_post_posts_columns',
	function( $columns ) {
		error_log( print_r( $columns, true ) );
		unset( $columns['newsletter_access'] );
		return $columns;
	},
	11
);
```

**Comment by millerf** [comment]
While working on some other issue, I realized there is [this function](https://github.com/Automattic/jetpack/blob/2e3f55334a11b45108a09fa685d86e466b4d8074/projects/plugins/jetpack/modules/memberships/class-jetpack-memberships.php#L515) that could be helpful.

```
has_configured_plans_jetpack_recurring_payments('newsletter')
```
would make sure the plugins is enabled and a paid-newsletter has been set...

**Comment by millerf** [comment]
@otterbit I spun up [this PR](https://github.com/Automattic/jetpack/pull/31960). 

Would it be possible for you to test it? I am swamped at the moment and cannot properly spin proper test instructions...

CC @jeherve
