### ISSUE TITLE
Jetpack Plugin: Undefined array key 'date' PHP warning

### ISSUE THREAD

**Issue by vitozev** [Automattic/jetpack#31836]
### Impacted plugin

Jetpack

### Quick summary

A user reported that they encounter the following PHP warnings on their website:

```
PHP Warning: Undefined array key 'date' in /home//public_html/wp-content/plugins/jetpack/json-endpoints/class.wpcom-json-api-list-posts-v1-1-endpoint.php on line 483
```

### Steps to reproduce

Reported by one of our customers; the exact repro steps are unknown.

### Impact

One

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

This was reported in 6499678-zd-woothemes

**Comment by anomiex** [comment]
Looks like you can reproduce by hitting something like `https://public-api.wordpress.com/rest/v1.1/sites/$site/posts/?http_envelope=1&fields=ID%2Ctitle`, i.e. using `fields` to specify a list of fields that includes "ID" but does not include the field used for `order_by` (which, by default, is "date").
