### ISSUE TITLE
AI Extensions: Verify that transformed headers keep their heading level

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#31841]
When converting to the AI Assistant, we're not keeping the heading level:

https://user-images.githubusercontent.com/16329583/253027358-7c0062e7-61f8-49f7-8981-bdf4184cce98.mov

**Comment by retrofox** [comment]
First, we must ensure the proper transform **from** the extended blocks to the AI Assistant block instances. It should (🤞 ) guarantee the proper response from the AI response.

**Comment by nunyvega** [comment]
Makes sense, that's the part that we can control.
