### ISSUE TITLE
Photon: wp_get_attachment_metadata() doesn't always give us an array. 

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#3184]
As reported:
```
Warning: Illegal string offset 'width' in /home/public_html/wp-content/plugins/jetpack/class.photon.php on line 466

Warning: Illegal string offset 'height' in /home/public_html/wp-content/plugins/jetpack/class.photon.php on line 466
```

It appears that Core may not create size meta for an attachment, or at least it can break. Need to investigate why/how this would happen, as well as ensure we know the h/w is present before continuing on.

2442460-t

**Comment by dereksmart** [comment]
Couple of thoughts.  
- could be possible that someone is changing the output of the meta for the image.  Should we skip the filters with `wp_get_attachment_metadata( $attachment_id, true )` to ensure we always get the raw metadata? 
- We could also make sure it's an array, or do some isset checks

**Comment by kraftbj** [comment]
I'm hesitant to skip the filters in case someone is using them correctly. The array check seems safer, though we'd need three of them at least without refactoring anything.

**Comment by dereksmart** [comment]
> I'm hesitant to skip the filters in case someone is using them correctly.
:+1:

**Comment by RCowles** [comment]
Also reported here:
https://wordpress.org/support/topic/started-getting-photon-error?replies=2

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/photon-not-working-8?replies=1&view=all
