### ISSUE TITLE
"Download" button for Feedback > Form Responses to download CSV file is not working

### ISSUE THREAD

**Issue by retnonindya** [Automattic/jetpack#31855]
### Impacted plugin

Jetpack

### Quick summary

The user wants to download the CSV file from their Feedback > Form Responses:
https://countertraffickingalliance.com

However, the button "Download" for CSV file is not responsive:
<img width="735" alt="Screenshot 2023-07-13 at 3 39 27 PM" src="https://github.com/Automattic/jetpack/assets/44726232/d56fd834-721d-4154-85d6-a9047374fe46">

I tested on my test Simple site, and I can replicate it. The problem is, this seems sporadic/inconsistent.

See Slack discussion here: p1689212150356039-slack-C03TY6J1A

### Steps to reproduce

1. SU as the user.
2. Go to Feedback > Form Responses.
3. Click the "Export" button.
4. See popup modal to download the Form Responses in CSV format or export to Google Sheet.
5. Click the "Download" button to download the responses in CSV format.
6. The "Download" button is unresponsive.

### A clear and concise description of what you expected to happen.

For the CSV file to be downloaded.

### What actually happened

The "Download" button is unresponsive.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

The user's site is WoA, and my test site is a Simple site. In case you need access/details for SU-ing to the user's site, feel free to ping me!

**Comment by hideandgeek404** [comment]
Just to add some of the important bits from the conversation above

`PHP Fatal error:  Uncaught Error: Cannot assign an empty string to a string offset in /wordpress/plugins/jetpack/12.4-a.3/jetpack_vendor/automattic/jetpack-forms/src/contact-form/class-contact-form-plugin.php:1275`

`$md['90_consent'] = $all_fields['email_marketing_consent'];`

It would seem that if 'email_marketing_consent' is a blank string, PHP doesn't like it and throws a 500 because the original variable was set as a string and not an array in the first place. Or something similar.

**Comment by happychait** [comment]
Re-opening as I still can't Download Form Responses on an Atomic site. I get the following error. Added a video of the issue after the following error message.

```jquery.min.js?ver=3.6.4:2     POST https://countertraffickingalliance.com/wp-admin/admin-ajax.php 500
send @ jquery.min.js?ver=3.6.4:2
ajax @ jquery.min.js?ver=3.6.4:2
(anonymous) @ jquery-migrate.min.js?ver=3.4.0:2
e.<computed> @ jquery-migrate.min.js?ver=3.4.0:2
S.<computed> @ jquery.min.js?ver=3.6.4:2
(anonymous) @ grunion-admin.min.js?ver=12.4-a.4:1
dispatch @ jquery.min.js?ver=3.6.4:2
y.handle @ jquery.min.js?ver=3.6.4:2
jquery.min.js?ver=3.6.4:2     POST https://countertraffickingalliance.com/wp-admin/admin-ajax.php 500
send @ jquery.min.js?ver=3.6.4:2
ajax @ jquery.min.js?ver=3.6.4:2
(anonymous) @ jquery-migrate.min.js?ver=3.4.0:2
e.<computed> @ jquery-migrate.min.js?ver=3.4.0:2
S.<computed> @ jquery.min.js?ver=3.6.4:2
(anonymous) @ grunion-admin.min.js?ver=12.4-a.4:1
dispatch @ jquery.min.js?ver=3.6.4:2
y.handle @ jquery.min.js?ver=3.6.4:2
jquery.min.js?ver=3.6.4:2     POST https://countertraffickingalliance.com/wp-admin/admin-ajax.php 500
send @ jquery.min.js?ver=3.6.4:2
ajax @ jquery.min.js?ver=3.6.4:2
(anonymous) @ jquery-migrate.min.js?ver=3.4.0:2
e.<computed> @ jquery-migrate.min.js?ver=3.4.0:2
S.<computed> @ jquery.min.js?ver=3.6.4:2
(anonymous) @ grunion-admin.min.js?ver=12.4-a.4:1
dispatch @ jquery.min.js?ver=3.6.4:2
y.handle @ jquery.min.js?ver=3.6.4:2
?v=2.0:16 WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: 
v @ ?v=2.0:16
D @ ?v=2.0:16
O @ ?v=2.0:16
?v=2.0:16 WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: 
v @ ?v=2.0:16
D @ ?v=2.0:16
O @ ?v=2.0:16
```


https://github.com/Automattic/jetpack/assets/1519466/fbebfb51-9fa2-443f-bd39-22003607f7e5

**Comment by happychait** [comment]
Getting a similar error with Google Sheet Export too:

![CleanShot 2023-07-18 at 14 32 23](https://github.com/Automattic/jetpack/assets/1519466/3862f76e-0038-4472-9228-d8fcb0d5a27c)

https://github.com/Automattic/jetpack/assets/1519466/9419cf95-7566-4953-99f1-1e51efac5b9a

**Comment by jeherve** [comment]
@happychait The fix hasn't been released to Atomic yet, hence why the bug still exists there. It should be offered to Atomic later today.
