### ISSUE TITLE
Boost: It's possible to run multiple speed score requests in parallel

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#31864]
This and https://github.com/Automattic/jetpack/issues/31543 can probably be fixed together.

![Image](https://user-images.githubusercontent.com/11799079/253293482-e552ebe3-47bc-4b11-831e-0a9cb072bb55.png)

Easiest to observe with the Inspector opened to the Network tab, listening for XHR requests.

Add the following snippet to your `mu-plugins` folder. This will cause the speed scores request to finish slower, which will allow you to easily spot the problem.

```php
add_filter( 'rest_pre_dispatch', 'jb_force_slow_page_speed_requests', 10, 3 );
function jb_force_slow_page_speed_requests( $result, $server, $request ) {
	error_log($request->get_route());
	if ( '/jetpack-boost/v1/speed-scores' !== $request->get_route() ) {
		return $result;
	}

	// In seconds. For longer wait, increase this.
	sleep(5);

	return $result;
}
```

To reproduce:
- Go to Boost settings page;
- Wait for the speed scores to load;
- Toggle an option and wait for the `merge` request to finish and then the `refresh` to show up and finish as well;
- As soon as the `refresh` request finishes, toggle another option (or the same one);
- Repeat the process as many times as you want;
- You should see multiple speed score requests as pending.

**Comment by haqadn** [comment]
I am unsure if it's worth the time, considering it doesn't impact our back end, and it happens in a very specific scenario. Let me know what you think.

**Comment by dilirity** [comment]
Oh, it doesn't impact the cloud? Thanks for checking.

In that case it may not be worth it, yes.
