### ISSUE TITLE
Stats: unable to activate module on Atomic sites with Commerce Plan

### ISSUE THREAD

**Issue by liviopv** [Automattic/jetpack#31860]
### Impacted plugin

Jetpack

### Quick summary

We've been receiving reports that customers are unable to see Stats or enable the module on their sites with the WordPress.com Commerce Plan and I was able to reproduce on a new site.

https://github.com/Automattic/jetpack/assets/14153300/96a248e4-1e0b-44cc-a992-d0ba832efed7

Stats can't be turned on from Calypso, CLI or internal tools

### Steps to reproduce

1. Create a new site on WordPress.com
2. Select the Commerce Plan
3. Navigate to Jetpack > Stats
4. Click on "Enable Jetpack Stats"

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by jeherve** [comment]
This is currently discussed and being fixed. Related:

- p1689246986539009-slack-C02FMH4G8
- D115581-code
- 1430-gh-Automattic/wpcomsh

**Comment by IanRamosC** [comment]
Fixed in Automattic/wpcomsh#1434 and Automattic/wpcomsh#1435
