### ISSUE TITLE
Map block: Selecting the Map block in the editor is very difficult

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/jetpack#31870]
### Impacted plugin

Jetpack

### Quick summary

Clicking on a Map block causes you to interact with the map itself, rather than the block, which makes it nearly impossible to select the block without using the List View or the "select" tool.

### Steps to reproduce

1. Insert a Map block on a post or page.
2. Click on any other block (or the post/page title).
3. Click on the Map block again.

### A clear and concise description of what you expected to happen.

The Map block should be selected, with the block toolbar visible, so that it can be edited, moved, or deleted.

### What actually happened

Focus doesn't seem to move to the Map block and remains on the previously selected element. Clicking around the Map block interacts with the map itself.

https://github.com/Automattic/jetpack/assets/5630717/59332383-f955-4143-8ded-ab28de41b9ff

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Only replicated on WoA so far, but I imagine it affects Simple too.

Workarounds:

* Use the List View to select the block.
* Use the "select" tool (instead of "edit") to click on the block.
* Depending on content layout, you can click on the block above/below the Map block, then tap down/up on your keyboard (respectively) and move your cursor over the map to cause the block toolbar to display.

**Comment by jeherve** [comment]
That's something I had experienced as well when first testing this:
https://github.com/Automattic/jetpack/pull/29098#pullrequestreview-1400220652

It'd be nice to improve on that behavior.

**Comment by coder-karen** [comment]
The issue does appear to be due to how Mapkit is rendered on the Map block.
It is replicable on WoA and Simple sites as they use Mapkit instead of Mapbox, but can be replicated on self-hosted and for local testing by setting the cookie in your browser console with `document.cookie = "map_provider=mapkit";`.

Adding these notes as I started looking into it but haven't identified a solution just yet.
