### ISSUE TITLE
AI Extensions: extend List Block

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#31875]
We stopped extending List Items now that we convert the extended blocks to the AI Assistant block whenever a request is sent. This is because an AI Assistant can't be nested inside a List block. 

Let's work in extending the List block so lists can be modified using our extension.

**Comment by danielbachhuber** [comment]
Will this also add the little AI assistant icon to the list item toolbar?

<img width="662" alt="image" src="https://github.com/Automattic/jetpack/assets/36432/c7fd04d9-98e2-4ae5-b5a7-d6262fbbf6de">

**Comment by dhasilva** [comment]
The idea is to add it only to the list, but that can be discussed.

**Comment by nunyvega** [comment]
@danielbachhuber not for the moment at least. Whenever a request to the AI Assistant is sent from an extended block, it is converted to the AI Assistant. This happens so the user has all the interface to interact with it (iterate, accept, reject the proposal, error, etc).
This conversion is not possible from a list item because the list block does not accept a Jetpack AI Assistant as a child block, that's why we're working on extending the list block.
