### ISSUE TITLE
AI Assistant: Keep text formatting

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#31878]
ref p58i-eRJ-p2#comment-58814

Right now we are losing text formatting and concatenating multiple blocks content, which makes them blend together. We need to find a way to keep different block's contents separated and keep the text formatting.

**Comment by nunyvega** [comment]
@dhasilva are we good to close this or something else is missing?

**Comment by nunyvega** [comment]
Adding a video to show how it's working now after your last PR:

https://github.com/Automattic/jetpack/assets/16329583/7f9b5ed6-e0f8-4624-92e4-0c6a4fbf9b01

**Comment by dhasilva** [comment]
I think we may need some prompt tweaks to keep the formatting when making more significant changes. Some more tests are need before closing this issue.

**Comment by nunyvega** [comment]
What would be an example of a formatting issue that needs fixing?

**Comment by dhasilva** [comment]
Before:
![2023-07-18_16-31-05](https://github.com/Automattic/jetpack/assets/8486249/dd9123e8-8c39-45a6-aa4d-1a198f10da2e)

After grammar correction:
![2023-07-18_16-31-42](https://github.com/Automattic/jetpack/assets/8486249/00e47fc6-23a5-4755-a9ab-4124c42d8489)

Bold and italics are kept, but things like underline and strikethrough are not. And partial word formatting is lost as well.

**Comment by dhasilva** [comment]
Closing as partially done. The underline style seems to be unsolvable in pure Markdown as there is no underline Markdown syntax. This is a spec issue, unfortunately.
