### ISSUE TITLE
Infinite Scroll: Entities in code samples are encoded multiple times

### ISSUE THREAD

**Issue by wojtekn** [Automattic/jetpack#31889]
### Impacted plugin

Jetpack

### Quick summary

Some code samples on https://jetpack.com/support/infinite-scroll/ page have HTML entities encoded multiple times:

```
function twenty_twelve_infinite_scroll_init() {
 add_theme_support( 'infinite-scroll', array(
 'container' =&amp;amp;amp;amp;amp;amp;gt; 'content',
 ) );
}
add_action( 'after_setup_theme', 'twenty_twelve_infinite_scroll_init' );
```

### Steps to reproduce

1. Open https://jetpack.com/support/infinite-scroll/
2. Check different code samples

### A clear and concise description of what you expected to happen.

Entities are not encoded multiple times, and the code is ready to use when copypasted.

### What actually happened

Entities are encoded multiple times, and the code needs to be fixed manually before it's used.

### Impact

All

### Available workarounds?

Yes, easy to implement

**Comment by jeherve** [comment]
I fixed it, it should be good to go now.
