### ISSUE TITLE
Sharing / Publicize: Add Spoutible

### ISSUE THREAD

**Issue by zanzaboonda** [Automattic/jetpack#31900]
### Impacted plugin

Social

### What

I'd like to be able to link my Spoutible account for sharing and also have it for social sharing

### How

Similar to other social shares.

Thanks!

**Comment by jeherve** [comment]
Given how popular the service is, I'll mark this issue as "won't fix". One can add their own custom sharing button instead:
https://jetpack.com/support/sharing/#customization-faqs
