### ISSUE TITLE
Comments: add option to customize the comment reply heading level

### ISSUE THREAD

**Issue by eclipses** [Automattic/jetpack#31913]
### Impacted plugin

Jetpack

### What

Allow the user to choose the tag for the comment section, currently hardcoded as H3

### How

Hi, 

I'm working to improve the accessibility of my pages and facing an issue as the section fo the comments uses H3 tag and in my pages I do not have any H2 tag. I would like if you could allow the user to choose in the setting which tag to be used. 
In Jetpack -> Settings -> Discussions
you can cusomize the "Comment form introduction" but not the tag that it is hardcoded as H3. I would like to use a normal paragraph <p> where to apply my style

**Comment by jeherve** [comment]
For reference, this heading tag is currently created here:
https://github.com/Automattic/jetpack/blob/c88270a2bbb509e75f6e223c555ba7d930c6fbe4/projects/plugins/jetpack/modules/comments/comments.php#L397-L399

I think we could add a filter there, so one can change the heading level to match their needs.

**Comment by eclipses** [comment]
As far as I read online there is a filter already in Wordpress for this but in this case Jetpack is overriding that code. Filter or a configuration in the settigs are both possible solutions.
