### ISSUE TITLE
Like button / Sharing buttons: Make them be blocks

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#31920]
I know this comes as duplicate of #19659 but I'd like to have a conversation about this now with the editor being fully in place in Core as that issue is 2 years old.

I just found #27243 as a draft, implementing sharing buttons. 
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/jetpack/issues/19659
- [ ] https://github.com/Automattic/jetpack/issues/19694
```

PT: pf5801-8d-p2

**Comment by jeherve** [comment]
Also in #19694 for sharing.

https://github.com/WordPress/gutenberg/pull/51449 would also possibly be helpful for our implementation.

**Comment by oskosk** [comment]
> https://github.com/WordPress/gutenberg/pull/51449 would also possibly be helpful for our implementation.

Thanks. I was actually testing this PR in conjunction with Jetpack, then came here to note the issue 😄

**Comment by simison** [comment]
Team 51 has found likes & sharing block really useful to do designs for their customers, so there's real need.

They even went as far as implement their own solution, see p9MPsk-3Zr-p2

**Comment by jeherve** [comment]
Marking this one as done so we now have both a Like block and a sharing block.
