### ISSUE TITLE
# AI Client: migrate 'askQuestion' to AI Client package

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#31945]
It involves relocating the 'askQuestion' library from the Jetpack plugin to the AI Client package.
Following this migration, we'll need to update the Jetpack plugin code to import and utilize this library from its new location.

**Comment by renatoagds** [comment]
Bringing back the point discussed here: p1689704654233179-slack-C054LN8RNVA

Makes sense to stop expose `SuggestionsEventSource` as soon this one is done.

**Comment by retrofox** [comment]
I have a comment regarding the current implementation of the [askQuestion()](https://github.com/Automattic/jetpack/blob/45589fb9ed8a62f5b555b1b4263b408ce3ac8cbe/projects/plugins/jetpack/extensions/blocks/ai-assistant/lib/suggestions/index.js#L46) function in the Jetpack plugin. I suggest removing the biz parameter from its API ([requiredUpgrade](https://github.com/Automattic/jetpack/blob/45589fb9ed8a62f5b555b1b4263b408ce3ac8cbe/projects/plugins/jetpack/extensions/blocks/ai-assistant/lib/suggestions/index.js#L50)).
In my opinion, this parameter is not essential to the purpose of the function, which should only focus on retrieving suggestions from the AI endpoint.
