### ISSUE TITLE
Publicize: scheduled posts are not shared to social media

### ISSUE THREAD

**Issue by foleynotrose** [Automattic/jetpack#31967]
### Impacted plugin

Social

### Quick summary

With scheduled posts, if you add a new connection after the post is created, that post will be skipped to be shared for that connection. There is a bug on the UI where it shows that it will be shared to that connection, but in fact it will get skipped.

### Steps to reproduce

1. Create a post that will be scheduled to be published later. 
2. Create a fresh Social connection for a social network (e.g. Facebook). 
3. Return to post and check Jetpack sidebar for Social Connections 

### A clear and concise description of what you expected to happen.

If Facebook connection is seen as selected as an optoin to be shared, I expect the post to be shared to Facebook. 

### What actually happened

In fact, the post does not get shared to Facebook. The connection gets skipped. 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

Discussed here on Slack: p1689334208877489/1689333035.555969-slack-C02JJ910CNL

**Comment by bobmatyas** [comment]
6507382-zen

**Comment by bobmatyas** [comment]
6589805-zen

**Comment by formosattic** [comment]
+1 6757784-zd-a8c

**Comment by bobmatyas** [comment]
6733619-zen

**Comment by formosattic** [comment]
6779135-zd-a8c

**Comment by bobmatyas** [comment]
6798061-zen

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Could Not Replicate

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)
