### ISSUE TITLE
Google Analytics compatibility with WooCommerce HPOS

### ISSUE THREAD

**Issue by rrennick** [Automattic/jetpack#31974]
### Impacted plugin

Jetpack

### Quick summary

Both Google Analytics Legacy and Universal use `get/update_post_meta()` with WooCommerce orders. Both classes have similar code. The `postmeta` table is not used when Woo HPOS is authoritative and the posts sync is disabled. `$order->get_meta()` and `$order->update_meta_data()` should be used for compatibility with both datastores. 

https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/modules/google-analytics/classes/wp-google-analytics-universal.php#L122:L189

Optional fixes:

```
$order          = new WC_Order( $order_id );
```

should be the loader function which will return false when the order doesn't exist

```
$order          = wc_get_order( $order_id );
```

`$order->get_total_shipping()` is deprecated, use `$order->get_shipping_total()` instead.

### Steps to reproduce

1. I found this using the following bash script:

```
for P in wpdb get_post metadata_exists post_exists _post_meta _metadata 'wp_(insert|update|delete|trash|untrash|transition)_post' '_post[a-zA-Z]*_cache' shop_order; do grep -nRE "$P" ./ | grep 'order' | grep -vE '\.js' ; done | sort -u
```

### A clear and concise description of what you expected to happen.

`*post_meta` functions would not be used

### What actually happened

They are

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

This is primarily an issue when sync is disabled.

**Comment by kraftbj** [comment]
@rrennick:
> not used when Woo HPOS is authoritative and the posts sync is disabled

What's the best way to determine this in code? I assume we need the existing setup for other Woo sites where HPOS is not enabled (or at least post sync is disabled).

**Comment by rrennick** [comment]
@kraftbj This snippet will return true when HPOS is authoritative. You should write to the HPOS tables whether or not sync is enabled.

```
$bool = \Automattic\WooCommerce\Internal\Features\FeaturesController::feature_is_enabled( 'woocommerce_custom_orders_table_enabled' );
```
