### ISSUE TITLE
Feature request: Contact form post-submit redirect

### ISSUE THREAD

**Issue by pnaw10** [Automattic/jetpack#3197]
1st time poster, was referred here by Lisa from Jetpack Support after I initially sent this idea via email.

I'm currently using a third-party contact form plugin on one of my websites.  I like almost everything about Jetpack's Contact Form module better, but it's missing just one feature: when users submit a form, it stays on the same page.  The only reason I continue to use my third-party plugin is because it allows me to specify a "confirmation / thank you" page where users are redirected after a form is submitted. 

Therefore, I am proposing that Jetpack's Contact Form module be enhanced to give users the option to redirect their visitors to a different page once a form has been submitted.  

While I am not familiar with current coding, I used to program years ago.  I would imagine there could be an "if/then" kind of check when a form is submitted,  If no redirect page is specified by the site admin, then the module acts as it currently does (providing backward compatibility for existing users who choose not to use [or aren't aware of] the redirect function).  If a redirect page is specified, then the visitor is redirected to that page.  The site admins could either be given a blank field to enter the full URL for the redirect, or they could be given a choice of Pages on the same site (similar to the site Menu setup screen within WP-admin).

Thank you all for being such an awesome community!

**Comment by aheckler** [comment]
@pnaw10: You can do this using Jetpack's `grunion_contact_form_redirect_url ` filter shown here:

https://github.com/Automattic/jetpack/blob/3.8.2/modules/contact-form/grunion-contact-form.php/#L1734

Here are two examples:

https://gist.github.com/kraftbj/0238a0bbef3526c32f27
