### ISSUE TITLE
Connect to Stripe - Change Learn More URL

### ISSUE THREAD

**Issue by donalirl** [Automattic/jetpack#31982]
### Impacted plugin

Jetpack, mu wpcom

### Quick summary

When inserting any payments type block on WordPress.com, there is an incorrect "learn more" link in the Stripe connection box.

### Steps to reproduce

Reproducible on any WordPress.com site that _does not have Stripe connected yet_:

1. Open the editor 
2. Insert a Payment Buttons block or Donations block
3. In the Stripe section, click "Learn more about the block and fees"

<img width="692" alt="Screenshot 2023-07-20 at 10 08 55 am" src="https://github.com/Automattic/jetpack/assets/30727666/644f5cc7-c714-481d-b5a2-85255a5392fc">

Self-hosted sites with Jetpack are not affected - the learn more link correctly leads to a Jetpack doc.

### A clear and concise description of what you expected to happen.

I expected to arrive on the support doc for all payments features: https://wordpress.com/support/wordpress-editor/blocks/payments/

OR to arrive at the relevant doc for each payment feature:

* Donations https://wordpress.com/support/wordpress-editor/blocks/donations/
* Paid Content https://wordpress.com/support/wordpress-editor/blocks/paid-content-block/
* Payment buttons: https://wordpress.com/support/wordpress-editor/blocks/payments/

### What actually happened

I arrived at the Paid Content doc https://wordpress.com/support/wordpress-editor/blocks/paid-content-block, regardless of which variation of the payments block I'm using.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described - thanks for the detailed notes!

📌 ACTIONS
- Assigned to Other as @jeherve 's already on the case 👍
