### ISSUE TITLE
Jetpack AI Assistant: Navigating to another tab stops content generation

### ISSUE THREAD

**Issue by aisajib** [Automattic/jetpack#31994]
## Summary 
While testing Jetpack AI on a personal site, I noticed that if I were navigating away while the text generation was underway, it would stop generating text. 

I also noticed that when I was back on the tab, it started producing content from the beginning instead of resuming where it stopped. 

Ideally, it should keep producing content even if I navigate to another tab, as that's how most people might be familiar with when using other tools. :)

## Steps to reproduce
1. On a new post editor, insert the AI block
2. Ask it to write something long "Write a long blog post about fishing"
3. Navigate to another tab just as the text generation starts
4. Navigate back to the editor

## What I expected to happen
* Either the text generation continues in the background
* Or it resumes where it paused when I navigated to another tab

## What happened instead
* Text generation stopped when I switched to another tab
* Text generation started from the beginning (in addition to the existing text in the block) when I switched to the editor tab

## Tested on
Both WordPress.com Simple and self-hosted WordPress.org sites.

Slack convo: p1689860483061449-slack-C054LN8RNVA

**Comment by oskosk** [comment]
The request is re-triggered. I think at the very least, this shouldn't happen.
