### ISSUE TITLE
Give the option to automatically include Newsletter sign up block at the end of posts / pages.

### ISSUE THREAD

**Issue by mikestottuk** [Automattic/jetpack#31991]
To help with adoption of Newsletter sign ups (sites gaining subscribers) we should consider the option of showing the subscribe block at the bottom of posts & pages.

With an option to turn on / off individual posts and pages.

![Image](https://github.com/Automattic/jetpack/assets/4077604/9bcb3fe3-c6d4-4cb2-8d40-94c24f090d69)

Should be relatively easy via `the_content` filter on Classic Themes, Block based themes might need some further consideration.

**Comment by pkuliga** [comment]
Closing this one since we are currently working on it as a part of the peKye1-EA-p2.

Related links:
- https://github.com/Automattic/jetpack/pull/35458
- https://github.com/Automattic/jetpack/issues/36021

Feel free to post your ideas under the linked PT or issue, thanks!
