### ISSUE TITLE
Enhancement: Better srcset/sizes support in Tiled Image Gallery

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#32006]
### Impacted plugin

Jetpack

### What

Define a more appropriate `sizes` attribute in the Jetpack Tiled Gallery component.

### How

Extra examples and context: pc9hqz-1TV-p2

When using the Tiled Gallery component, images generally have a range of sizes in the `srcset` attribute, but browsers use the `sizes` attribute to guess which image to load as soon as the `img` tag is parsed in the HTML.

The problem is that the Tiled Gallery seems to use WordPress' default `sizes` attribute for each image. On some sites, that appears to be missing. On others it appears to be a guess based on the `$content_width` and the width of the original image. For example (missing sources):

![image](https://github.com/Automattic/jetpack/assets/1369626/ac8964f0-df1e-409d-a27c-f522605e3a32)

Given the Tiled Gallery knows how many images it expects to appear in each row, it should be able to set up a better `sizes` attribute based on a percentage of the screen width the image ought to consume on smaller displays.

For example, for a 1024px original image which should consume approximately 1/3rd the display on a page with a `$content_width` set to 1280:
```
`sizes="(max-width: 1280px): 33vw, 426px"`
```

(i.e.: for displays up to content_width, use 1/3rd of the display. Otherwise use 1/3rd of content_width).

You can check which image your browser is using by shift-refreshing the page (to load without cache), and selecting the img element in the Browser dev tools. Either hover over the image's srcset and compare the "Intrinsic size" to the "Rendered size" to see if it's selecting an appropriate image (as in the above screenshot), or by selecting the element and running `$0.currentSrc` in the console to see which src URL is being selected.

One gotcha to watch out for: Your browser will use a higher-res image if it already has one from the srcset cached. So be sure to shift-reload to tell it not to use its cache.

I also think it's worth double-checking the `IMG_SRCSET_WIDTH_MIN` value in the Tiled Gallery. It seems to be 600 at the moment; making that the smallest image it will include in the srcset. That seems a bit large for a 3rd of a mobile screen. I'd recommend 300 as a decent minimum.

**Comment by jeherve** [comment]
This was done in #32598.
