### ISSUE TITLE
Boost: Image Guide (free) showing up on adminbar avatar

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#32037]
### Impacted plugin

Boost

### Quick summary

<img width="199" alt="CleanShot 2023-07-24 at 18 08 22@2x" src="https://github.com/Automattic/jetpack/assets/11799079/b1c3f47b-9d92-42d0-915e-447185507d11">

### Steps to reproduce

1. Setup latest (2.0.0) Boost;
2. Enable Image Guide;
3. Check any page in the front-end.

### A clear and concise description of what you expected to happen.

Bubble shouldn't show up for avatars.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by dilirity** [comment]
Opening this, as it's still an issue.

Managed to find a way to reproduce it consistently:
- open any page in a new tab using middle mouse button or command click (a background tab);
- navigate to tab to see the bubble show up.

**Comment by dilirity** [comment]
Freeing this up for someone else.

**Comment by pyronaur** [comment]
Fix incoming.
