### ISSUE TITLE
Publicize: specify custom image

### ISSUE THREAD

**Issue by rescasol** [Automattic/jetpack#32036]
### Impacted plugin

Social

### What

Add a way to use a picutre diferent han the one form the post

### How

It would be great if there was an option to create a post (for example on Instagram) using a picture different that the one used in the post.

At least a hook or similar that allows to interact and choose another picture to be used in the final post. Like setting a fix image for all the posts, without taking in account the one that the post has as featured image.

**Comment by jeherve** [comment]
> an option to create a post (for example on Instagram) using a picture different that the one used in the post.

This should already be possible, when using our Jetpack Social Advanced plan. This is currently described here:
https://jetpack.com/support/jetpack-social-organic-content-sharing/#engagement-optimizer

I hope this helps!
