### ISSUE TITLE
Monitor -- Offer filter to temporarily disable

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#3205]
Hey Guys,

The monitor feature is great, however many times the clients will get the email notifications when we are performing a scheduled maintenance on the site. It would be useful to offer a hook/filter for any hosting provider/developer to temporarily disable the feature for a set time window, such as:

* 5 mins
* 10 mins
* 15 mins
* 30 mins
* 1 Hour
* 3 Hour
etc

Maybe even let developers provide a message that can be used in the emails or displayed somewhere if needed.

**Comment by kraftbj** [comment]
This would require some refactoring on our end, or you can use the module activation/deactivation hooks already in place. Monitor runs completely on our systems—when the module is activated it triggers adding the site to our monitor system and deactivation triggers removing the site. An ongoing filter would likely be problematic, so I'd suggest crafting something that deactivates the module when needed and reactivates at the end of the process.

I'm going to `wontfix` this without prejudice for a future enhancement.
