### ISSUE TITLE
Add External Link icons to the "Manage" buttons that link to Calypso Green

### ISSUE THREAD

**Issue by kallehauge** [Automattic/jetpack#32057]
"Manage" buttons in My Jetpack that links to Calypso Green or another external website doesn't include "external link" icon(s):

![Image](https://github.com/Automattic/jetpack/assets/3846700/b3aad68a-8c70-477f-98f3-1684e8edf007)

Jetpack Emerald also includes how the buttons are supposed to look (I haven't checked if it's already part of our RNA components).

TTzDk3dzct551hYWRXPFa3-fi-2393_17487:

![Image](https://github.com/Automattic/jetpack/assets/3846700/ee0fe509-4f8a-437c-b49f-07c4ff635fef)

**Comment by jeherve** [comment]
I think this is now solved with the new UI, it can be closed.
