### ISSUE TITLE
Newsletters: Add option to log in to view content for logged out paying subscribers

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/jetpack#32062]
### Impacted plugin

Jetpack

### What

When a paying subscriber is logged out of WordPress.com and tried to view content inside a post, they only see the option to subscribe. 

![Screenshot 2023-07-29 at 12 18 14](https://github.com/Automattic/jetpack/assets/2540430/a5a00066-bf85-4ee1-94a3-361710977c09)

### How

By adding something like:

"Already a subscriber, please [log into WordPress.com to read the content](https://wordpress.com/log-in)". or similar to our Paid Content block.

**Comment by cuemarie** [comment]
@filipanoscampos just to check in - are you referring to the Newsletter paywall, or the Paid Content Block itself?

The Paid Content block's guest view is editable in the editor, and contains a Subscribe & Login button by default, as shown in this example:

![Markup on 2023-07-25 at 10:32:11](https://github.com/Automattic/jetpack/assets/27249804/c4de06a4-4475-4090-bdd6-e2715dcab627)

By comparison, here's the logged out view of a Paid Newsletter post, which matches your description a bit more:

![Markup on 2023-07-25 at 10:30:36](https://github.com/Automattic/jetpack/assets/27249804/75aecaf0-6f7e-4bcc-8f34-7b2c58e1d41a)

📌 ACTIONS
- Requested author feedback

**Comment by filipanoscampos** [comment]
Thanks Marie!
Updated the Feature request to make things clearer. Sorry about the confusion.

**Comment by pkuliga** [comment]
Are you referring to the Paywall block or a Subscribe block? We have it already in the Paywall block:

<img width="639" alt="Screenshot 2024-02-29 at 10 39 28" src="https://github.com/Automattic/jetpack/assets/4068554/183dbc25-2db7-4b1b-890c-751afb6dba7f">

**Comment by filipanoscampos** [comment]
To the Subscribe block in cases where content is only available to paying newsletter subscribers.

**Comment by simison** [comment]
The paywall indeed used not to have the login link, but now it's there since quite few months ago, like shown in above screenshot. :-)
