### ISSUE TITLE
Likes broken on Firefox & Safari

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#32083]
### Impacted plugin

Jetpack

### Quick summary

_Likes_ auth popup seems broken. The popup handles the authentication, thus allowing functioning regardless of blocked 3rd party cookies.

### Steps to reproduce

1. Be logged in at .com, and go to a post with likes https://wordpress.org/news/2023/07/wordpress-6-3-release-candidate-2/
2. Like the post with Firefox or Safari.
3. Allow popup if needed
    ![image](https://github.com/Automattic/jetpack/assets/87168/4b2ab53f-f3e9-4f24-b1f5-0900fc33ed7b)
4. Observe white modal open and freeze.
    
    ![image](https://github.com/Automattic/jetpack/assets/87168/ab08cd12-15e6-4998-8b61-05e3a1dc1251)

6. Modal has a console error:

```
Uncaught DOMException: Permission denied to access property "commentFooter" on cross-origin object
```
    
<img width="1334" alt="Screenshot 2023-07-26 at 14 43 27" src="https://github.com/Automattic/jetpack/assets/87168/eec6b82f-b7df-4b28-b2b3-0934ceee3410">

Seems to work on Chrome just fine.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by anomiex** [comment]
This does not seem to be due to Jetpack itself. Likely it's due to D116474-code on the wpcom side which appears to have introduced some accesses on `window.opener.commentFooter`, pinging @alshakero.

**Comment by Addison-Stavlo** [comment]
reverted in D117120-code, this should be working as it previously was.
