### ISSUE TITLE
AI Client: Add AiIcon component

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#32150]
This component is an [AI Assistant icon](https://github.com/Automattic/jetpack/pull/32079) wrapper but with the ability to show different states:

```jsx
<AiIcon status="is-suggesting" />
```

**Comment by renatoagds** [comment]
Can you elaborate more the need of this one? Don't get the reasons and the use cases to have this component.

**Comment by retrofox** [comment]
To simplify its usage and guarantee its behavior among all instances.

**Comment by renatoagds** [comment]
Sorry, but I still not getting if we need this component, since I'm not seeing the use cases for it.

**Comment by retrofox** [comment]
p1687347197727109/1687302104.930509-slack-C054LN8RNVA

**Comment by retrofox** [comment]
p1691047868739479-slack-C054LN8RNVA
