### ISSUE TITLE
Photon displays extremely small images in some cases

### ISSUE THREAD

**Issue by bradyvercher** [Automattic/jetpack#3216]
I've received some reports over the past few days that some images are no longer appearing after updating to the latest version of Jetpack. After a bit of debugging, this is what I've been able to gather:

If a theme calls `the_post_thumbnail( array( 800, 800 ) )` using an array for the size that happens to be larger than the original image (say 500 x 500 for this example), Photon appends `fit=1,1` to the image URL.

[This particular line](https://github.com/Automattic/jetpack/commit/64653779381340214660481593de50d202651719#diff-71f62265b9fb89148ee4f42b3c900faeR540) seems to be where the issue pops up. `image_resize_dimensions()` [will return false](https://github.com/WordPress/WordPress/blob/d03333735f21669c58a3a4574f343891a261854a/wp-includes/media.php#L550-L553) if the resulting dimensions are the same size or larger than the original image.

**Comment by kraftbj** [comment]
Good catch. I haven't verified but reads well. Need to update our unit tests as well (new test after https://github.com/Automattic/jetpack/blob/3.8.2/tests/php/test_class.jetpack_photon.php#L602 ) to account for this.

**Comment by kraftbj** [comment]
Related: #3186

**Comment by kraftbj** [comment]
Verified via unit test on `fix/photon-39` branch. @zinigor I'd like to fix this up in time for 3.9. I'm playing catch up from being off for two weeks, but will PR if I get to it before anyone else.
