### ISSUE TITLE
Adding initial state several times results in deprecation notices.

### ISSUE THREAD

**Issue by zinigor** [Automattic/jetpack#32184]
### Impacted plugin

Jetpack

### Quick summary

Deprecation warnings are displayed if WP_DEBUG is enabled while creating a new post. 

It looks like the issue is that `Automattic\Jetpack\Connection\Initial_State::render()` is being called twice, and its output is being fed directly into `wp_add_inline_script` both times. The second time it’s called it returns `null`, which is not a valid value to pass to `wp_add_inline_script`.

It’s being called from:

1.  jetpack_vendor/automattic/jetpack-videopress/src/class-block-editor-extensions.php first, then
2. class.jetpack-gutenberg.php.

Each time the script has a different $handle, but I’m not sure if that matters. IMHO either:

1. Each caller should check for a null return before calling wp_add_inline_script, or
2. We could move the logic for enqueuing the script into Initial_State::render() so it can make sure it is only enqueued once.

### Steps to reproduce

1. Install the latest Jetpack RC using Jetpack Beta (Version 12.5-a.1-5731444981-g41d0db20)
2. Turn on WP_DEBUG.
3. Click on Posts > New Post.

### A clear and concise description of what you expected to happen.

No debug output expected.

### What actually happened

Lots of debug output / deprecation warnings:

![image-1](https://github.com/Automattic/jetpack/assets/374293/84ca99ca-50d8-463a-8ddb-90d597ad42f2)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement. Turn off WP_DEBUG to remove deprecation warnings.

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

### Logs or notes

p8oabR-1hi-p2#comment-7484

**Comment by anomiex** [comment]
A quick fix might be to return an empty string instead of `null`. `wp_add_inline_script()` will treat that in the same way, while not triggering the deprecation warning about passing null to `stripos` along the way.

**Comment by anomiex** [comment]
Looks like this was fixed in #32932.
