### ISSUE TITLE
Ability to filter content of posts sent via subscriptions

### ISSUE THREAD

**Issue by jb510** [Automattic/jetpack#3219]
We'd like the ability to filter content sent via JetPack Subscriptions.  Specifically in this case to add a unique post footer when a post is delivered via email.

By comparison MailChimp's RSS to Email grabs the content from the RSS feed (obviously), so modifying the RSS template affects this content.

The ability to filter both post content and the post title should be considered.  

I could see others using that to do preg_replace specific content (SSL'ing urls on the fly for example).  

ref: https://wordpress.org/support/topic/how-to-filter-the-content-sent-via-jp-subscription?replies=6#post-7831931

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/add-sharing-option-to-jetpack-subscriptions-1?replies=1&view=all

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
