### ISSUE TITLE
Gallery: Disable Hovers on Mobile Devices

### ISSUE THREAD

**Issue by TwisterMc** [Automattic/jetpack#3221]
When I add a gallery to my blog, it looks great on mobile devices, but the interactions are a bit off. 

Example:
On an iOS or Android Device visit http://www.twistermc.com/42148/big-thrill-factory/ and scroll down to the gallery. Tap on an image and notice nothing happens. Tap again and it'll open the image bigger.

Ideal Solution:
Detect mobile devices and take out the hover state which is happening on the first tap. That way the first tap just opens the image bigger.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
