### ISSUE TITLE
AI Extension: show assistant messages

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#32214]
We should provide feedback to the user as needed. I recommend utilizing the Notice core component for this purpose.

**Comment by nunyvega** [comment]
What do you mean with feedback specifically? the errors that we already show on the AI Assistant? or something else?

**Comment by retrofox** [comment]
Sorry, I didn't see your message at the time. Closing this issue for now. Pretty sure we will talk about it soon.
