### ISSUE TITLE
AI Extension: implement upgrade prompt message for contact form

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#32216]
Currently, the form extension beta feature is not providing any way to upgrade whenever a user is out of free requests. Let's add an upgrade path.

**Comment by ederrengifo** [comment]
I think we can reuse the same prompt we already have for the AI block cc @madebynoam 
<img width="1440" alt="upgrade-promt" src="https://github.com/Automattic/jetpack/assets/10525007/f5bbd287-a795-4a5e-82f6-82def23c1298">

**Comment by renatoagds** [comment]
Can we follow this way @nunyvega ? I'm taking this one.

**Comment by retrofox** [comment]
The upgrade banner, or any notification, shouldn't be tied to Block representation (canvas) or the assistant bar.

**Comment by renatoagds** [comment]
Which is your proposal @retrofox ?

**Comment by retrofox** [comment]
We talked here: p1691051547492309-slack-C054LN8RNVA. Better going there to cathing up :-)

**Comment by nunyvega** [comment]
Closing this as the upgrade banner is now in place.
