### ISSUE TITLE
Jetpack Social / Publicize: add support for Threads

### ISSUE THREAD

**Issue by aisajib** [Automattic/jetpack#32215]
### Impacted plugin

Social

### What

We got a request coming in on the WordPress.com forum for auto-sharing posts to Threads. 

### How

~~I understand that there isn't an API yet for us to use, but I'm opening an issue to track user requests.~~

The API is now available here:

- https://developers.facebook.com/docs/threads/

**Comment by aisajib** [comment]
Request came in here: https://wordpress.com/forums/topic/facebook-meta-threads-will-does-wordpress-support-auto-posting-to-threads/

**Comment by pablinos** [comment]
Currently there isn't a public API to post to Threads. We've asked about it, and if/when they add ActivityPub support, we'll be able to add support for posting to it.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept

**Comment by formosattic** [comment]
+1 
6693335-zd-a8c
7161530-zd-a8c

**Comment by formosattic** [comment]
+1 https://wordpress.org/support/topic/threads-3/

**Comment by StefMattana** [comment]
+1 https://wordpress.org/support/topic/add-threads-to-the-share-addtoany-got-it/

**Comment by jeherve** [comment]
It looks like the API is now open, so we may be able to progress on this:

- https://www.threads.net/@zuck/post/C8WQyIVOd8t
- https://developers.facebook.com/docs/threads/

**Comment by pablinos** [comment]
We're launching this with the new version of Jetpack.

**Comment by pablinos** [comment]
This has just been released. Support is available in Jetpack 13.6 and Jetpack Social 4.5.2
