### ISSUE TITLE
PHP fatal error sometimes from Jetpack REST API calls to my site

### ISSUE THREAD

**Issue by sc0ttkclark** [Automattic/jetpack#32232]
### Impacted plugin

Jetpack

### Quick summary

So I have an interesting bug here that only happens when Jetpack makes API requests. I only know about this bug because I have my site set up to email me any PHP fatal errors that happen so I'm always ready to jump on fixing something.

This same exact PHP fatal error happened four times in a row so I assume the endpoint calls had a retry mechanism being used.

### Steps to reproduce

I believe all I did was logged into WordPress.com and had loaded up the WP.com panel for that particular site. I didn't perform any other actions on that site at the time.

### A clear and concise description of what you expected to happen.

I don't know what WP.com was doing, perhaps this was trying to pull admin menu items from my site and display links to those. But I at least expected the PHP fatal error wouldn't occur as that was coming from Jetpack's plugin side.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

**Path:** /?rest_route=%2Fwpcom%2Fv2%2Fadmin-menu&_for=jetpack&token=TOKENHERE&timestamp=1690934017&nonce=NONCEHERE&body-hash&signature=SIGNATUREHERE

**PHP fatal error:**

```
Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class Post_Content_Shortcodes does not have a method "admin_menu"
```

<details>
<summary>Stacktrace</summary>

```
Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class Post_Content_Shortcodes does not have a method "admin_menu" in /chroot/home/myusername/[mysite.com/html/wp-includes/class-wp-hook.php:308](http://mysite.com/html/wp-includes/class-wp-hook.php:308)
Stack trace:
#0 /chroot/home/myusername/[mysite.com/html/wp-includes/class-wp-hook.php(332)](http://mysite.com/html/wp-includes/class-wp-hook.php(332)): WP_Hook->apply_filters(NULL, Array)
#1 /chroot/home/myusername/[mysite.com/html/wp-includes/plugin.php(517)](http://mysite.com/html/wp-includes/plugin.php(517)): WP_Hook->do_action(Array)
#2 /chroot/home/myusername/[mysite.com/html/wp-admin/includes/menu.php(155)](http://mysite.com/html/wp-admin/includes/menu.php(155)): do_action(\'admin_menu\', \'\')
#3 /chroot/home/myusername/[mysite.com/html/wp-admin/menu.php(420)](http://mysite.com/html/wp-admin/menu.php(420)): require_once(\'/chroot/home/a7...\')
#4 /chroot/home/myusername/[mysite.com/html/wp-content/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php(92)](http://mysite.com/html/wp-content/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php(92)): require_once(\'/chroot/home/a7...\')
#5 /chroot/home/myusername/[mysite.com/html/wp-includes/rest-api/class-wp-rest-server.php(1181)](http://mysite.com/html/wp-includes/rest-api/class-wp-rest-server.php(1181)): WPCOM_REST_API_V2_Endpoint_Admin_Menu->get_item(Object(WP_REST_Request))
#6 /chroot/home/myusername/[mysite.com/html/wp-includes/rest-api/class-wp-rest-server.php(1028)](http://mysite.com/html/wp-includes/rest-api/class-wp-rest-server.php(1028)): WP_REST_Server->respond_to_request(Object(WP_REST_Request), \'/wpcom/v2/admin...\', Array, NULL)
#7 /chroot/home/myusername/[mysite.com/html/wp-includes/rest-api/class-wp-rest-server.php(442)](http://mysite.com/html/wp-includes/rest-api/class-wp-rest-server.php(442)): WP_REST_Server->dispatch(Object(WP_REST_Request))
#8 /chroot/home/myusername/[mysite.com/html/wp-includes/rest-api.php(410)](http://mysite.com/html/wp-includes/rest-api.php(410)): WP_REST_Server->serve_request(\'/wpcom/v2/admin...\')
#9 /chroot/home/myusername/[mysite.com/html/wp-includes/class-wp-hook.php(308)](http://mysite.com/html/wp-includes/class-wp-hook.php(308)): rest_api_loaded(Object(WP))
#10 /chroot/home/myusername/[mysite.com/html/wp-includes/class-wp-hook.php(332)](http://mysite.com/html/wp-includes/class-wp-hook.php(332)): WP_Hook->apply_filters(NULL, Array)
#11 /chroot/home/myusername/[mysite.com/html/wp-includes/plugin.php(565)](http://mysite.com/html/wp-includes/plugin.php(565)): WP_Hook->do_action(Array)
#12 /chroot/home/myusername/[mysite.com/html/wp-includes/class-wp.php(399)](http://mysite.com/html/wp-includes/class-wp.php(399)): do_action_ref_array(\'parse_request\', Array)
#13 /chroot/home/myusername/[mysite.com/html/wp-includes/class-wp.php(780)](http://mysite.com/html/wp-includes/class-wp.php(780)): WP->parse_request(\'\')
#14 /chroot/home/myusername/[mysite.com/html/wp-includes/functions.php(1334)](http://mysite.com/html/wp-includes/functions.php(1334)): WP->main(\'\')
#15 /chroot/home/myusername/[mysite.com/html/wp-blog-header.php(16)](http://mysite.com/html/wp-blog-header.php(16)): wp()
#16 /chroot/home/myusername/[mysite.com/html/index.php(17)](http://mysite.com/html/index.php(17)): require(\'/chroot/home/a7...\')
```

</details>

**Comment by cuemarie** [comment]
Not quite sure how best to repro this, so just starting by looping @jeherve in to see where we should take this.

**Comment by sc0ttkclark** [comment]
Currently happening on this site: pods.io

When I go to this URL on WordPress.com it triggers those fatal errors through the resulting REST API endpoint calls to the site.

https://wordpress.com/stats/day/pods.io

I can reproduce it every time I refresh that page.

**Comment by jeherve** [comment]
The error message seems to point to the Post Content Shortcodes plugin, currently installed on pods.io. The plugin includes a `Post_Content_Shortcodes` class, but that class does not have any `admin_menu` method, even though it is called here:

https://github.com/cgrymala/post-content-shortcodes/blob/ab84bf6d85d7031478428e7d7e6fd86763f92353/classes/class-post-content-shortcodes.php#L156-L157

As a result, any plugin that hooks into `admin_menu`, like Jetpack, may run into conflicts with that plugin.

I opened an issue here to let the plugin author know about the problem:
https://github.com/cgrymala/post-content-shortcodes/issues/6

Until that is fixed in the plugin, I'm afraid I can only recommend that you patch the plugin on your own or deactivate it on that site.

**Comment by sc0ttkclark** [comment]
Appreciate that, that was above and beyond what you probably had to do. I'll get that tweaked.
