### ISSUE TITLE
VideoPress Block: CSS file is loaded on all pages, even when the block isn't used

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#32235]
### Steps to reproduce

1. Start with a site using a classic theme, like Twenty Twenty
2. Install and activate the Jetpack plugin.
3. Connect your site to WordPress.com.
4. Check the source files loaded on your site's home page
    * You'll note that the `jetpack_vendor/automattic/jetpack-videopress/build/block-editor/blocks/video/view.css` is loaded, even though the VideoPress module isn't active or used on the site.

The CSS file appears to be loaded as part of the block registration:

https://github.com/Automattic/jetpack/blob/cfb79d61b24146312fd07c3872add2435686e171/projects/packages/videopress/src/class-initializer.php#L373-L375

I'm not sure if that means we should find a way around `register_block_type_from_metadata` in this case, to improve performance.

**Comment by CGastrell** [comment]
I think we could just skip the block registration if the module is not active, shouldn't we? As far as I've tested, if the module is disabled you don't get VideoPress blocks rendered at all.

**Comment by jeherve** [comment]
> we could just skip the block registration if the module is not active, shouldn't we?

@retrofox Could you weigh in on this?

**Comment by retrofox** [comment]
we'll work on it this week

**Comment by CGastrell** [comment]
Happens on 2020 and 2021, but not on 2022 or 2023

**Comment by jeherve** [comment]
Yes, the problem is limited to classic themes, as I mentioned in the original issue. You will not run into the issue when using a block theme.

**Comment by CGastrell** [comment]
We had to revert the PR that fixed this one, working on a new one.

**Comment by CGastrell** [comment]
Reopen as we had to revert #33672
