### ISSUE TITLE
Subscriptions Block: extra resources loaded every time the block is loaded on a page

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#32237]
This issue is similar to https://github.com/Automattic/wp-calypso/issues/71048, but I wanted to log it here in the Jetpack repo because of the following changes:

1. The Subscriptions modal is now used for all subscription blocks.
2. This change's impact on performance is significant, since subscription blocks are often loaded on every page of a site.

*************

The Jetpack Subscription block now relies on the Thickbox library:
https://github.com/Automattic/jetpack/blob/a1ad934e39d33cfc741f8c310d01820b87a010cd/projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php#L431-L435

This is problematic because the Thickbox library comes with its own set of dependencies, thus potentially significantly impacting the loading speed on a site. Here is a preview of the different items that get added when adding a Subscribe block to your site:

- The block's CSS file.
- Thickbox's js
- Thickbox's css
- Thickbox's loading gif
- jQuery
- jQuery Migrate
- Dashicons' CSS.

<table>
<tr>
 <td><strong>Without the Subscribe Block</strong></td>
 <td><strong>With the Subscribe block</strong></td>
<tr>
 <td>
<img width="449" alt="Screenshot 2023-08-02 at 17 37 26" src="https://github.com/Automattic/jetpack/assets/426388/fa63ffcb-994f-486c-aa88-75d68d78e675">
</td>
 <td>
<img width="401" alt="Screenshot 2023-08-02 at 17 36 54" src="https://github.com/Automattic/jetpack/assets/426388/e122e4a3-b858-46d5-939c-92e40fd6ffca">
</td>
</table>

**Comment by jeherve** [comment]
@millerf @simison I was thinking about adding this to a project board, but I'm not sure which one. Team Gold's? Newsletter? Zap's?

**Comment by millerf** [comment]
@jeherve That would be Gold's. I'll add it.

**Comment by jeherve** [comment]
Thank you!

**Comment by millerf** [comment]
@n3f Do you remember how far we moved that task and why we never ended up removing it?

**Comment by jeherve** [comment]
You had worked on #28318 at some point, which would address some of those problems!

**Comment by n3f** [comment]
The piece I did was https://github.com/Automattic/wp-calypso/issues/71048, which "worked", but the consensus was a different approach was needed.  To save you from reading, I re-used a gutenberg modal component, but Matias pointed out the HTML spec `<modal>` was a better option.  I think priorities shifted and haven't been pointed back to working that...

**Comment by simison** [comment]
We could abstract and improve the modal wrapper from [subscription modal feature](https://github.com/Automattic/jetpack/tree/e1fa34ed985e4a7cc83eefc8262a46c8ec6107e7/projects/plugins/jetpack/modules/subscriptions/subscribe-modal) and use that as a shared component for all these modals.

Later on we could collaborate with Frontity team on being able to use core's interactivity API (pbWTxM-1KG-p2) to replace that abstraction with core version (which doesn't exist yet). That'll then be accessible, performant, and shared with the rest of plugins in WP.

**Comment by liviopv** [comment]
📌 ACTIONS
- Marking as triaged
