### ISSUE TITLE
AI Extension: teach AI to create nested compositions

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#32244]
When it creates nested composition, the suggestions generate validation issues because the sub tree is incomplete:

```
<col>
```

```
<col><row>
```

```
<col><row>1</row>
```

The example above generates validation errors.

It should be nice if we can:

1 - teach/ask the AI to permanently close the opened wrapper element, even when suggesting
2 - adjust the markup when getting the suggestion

**Comment by lhkowalski** [comment]
About the item `#1`, do you mean it could generate something like this?

`<col></col>`

and then 

`<col><row>1</row></col>`

and then

`<col><row>1</row><row>2</row></col>`

**Comment by dhasilva** [comment]
I don't think it is possible to do this by tweaking the prompt, because the stream happens in chunks. We'll need to autoclose tags on our end.
