### ISSUE TITLE
AI Extension: toggle AiExtensionBar doesn't work

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#32243]
Clicking on the Toolbar button doesn't hide the assistant bar

https://user-images.githubusercontent.com/77539/257899809-d5d92f94-d866-40bf-92d1-fcc3104f8a9f.mov

**Comment by lhkowalski** [comment]
I remember it was working before, maybe a day ago. Checking now.

**Comment by lhkowalski** [comment]
Confirmed that it happens. The popover can be dismissed when you click on the form block itself or outside the block, so it's probably something with the toggle button.
