### ISSUE TITLE
Boost: Clean up first year discount tags

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#32251]
Discussion: pc9hqz-1Xn-p2

Boost's "Getting Started" page shows two tags indicating the discount for the first year of Boost, which can line-break weirdly. It doesn't match the original designs - but we do need to be clear that the discount applies to the first year only.

We need to return to the original design, and indicate the discount applies to the first year using the grey "per month" copy, like so:

“per month for the first year, billed yearly” 
![Image](https://github.com/Automattic/jetpack/assets/1369626/35bf5232-5ea2-47e7-9732-47fca911b286)

**Comment by dilirity** [comment]
On hold, as making this change affects other JP products since they share the same component.

Discussion here pc9hqz-1Xn-p2#comment-1549

**Comment by dilirity** [comment]
Ready to move forward - pc9hqz-1Xn-p2#comment-1567
