### ISSUE TITLE
AI Extension: research an approach to update Form content progressively

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#32278]
Oddly, we start from zero each time, even when the difference is minor. A suggestion would be to intercept the streamed response somehow, compare it with the existing version, and only update the blocks that are different (at a block level, any block with even a slight difference would be entirely updated)

Let's research a way to try to improve this process

**Comment by dhasilva** [comment]
Closing as duplicate of https://github.com/Automattic/jetpack/issues/32609
