### ISSUE TITLE
Carousel: make comment form visible on mobile

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3229]
It seems that we purposely hide the comment form in the Carousel view on smaller devices:
https://github.com/Automattic/jetpack/blob/3.8.2/modules/carousel/jetpack-carousel.css#L1130

It would be nice if mobile readers could leave comments on images as well.

Reported here:
https://wordpress.org/support/topic/carousel-comments-on-mobile?replies=1&view=all

**Comment by fresatomica** [comment]
Also reported here: https://wordpress.org/support/topic/comment-form-not-showing-in-mobile-view/

**Comment by apeatling** [comment]
This will be addressed in https://github.com/Automattic/jetpack/pull/20139
