### ISSUE TITLE
AI Extension: Introduce a warning message

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#32296]
Let's introduce a simple but important section to warn usage of something, for example when something gets wrong.

Context: p1691152309918619/1691144250.247699-slack-C054LN8RNVA

![Image](https://user-images.githubusercontent.com/1663717/258523512-da8fab02-9752-45c0-8cf6-94c85e61c6f5.png)

**Comment by dhasilva** [comment]
[Backlog] - Not a priority for the moment, we'll continue for now with the current warning.

**Comment by dhasilva** [comment]
Closing as the UI has changed since then.
