### ISSUE TITLE
AI Extension: Avoid showing the block placeholder when requesting

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#32299]
When we're requesting for the first time, the placeholder is shown.

Context: p1691164924081289/1691144250.247699-slack-C054LN8RNVA

**Comment by retrofox** [comment]
> one more thing that I’m pretty sure we discussed it yesterday but I want to be sure is recorded here. When I iterated on a created form, we show the “block placeholder” for a second, but I don’t see the value on showing the options there, besides, it interrupts the experience. Is there a way to tweak this so we have a “loading” placeholder until the first block is generated?



https://github.com/Automattic/jetpack/assets/77539/20794166-5777-494c-83f9-d6b48566ff08
