### ISSUE TITLE
JITM styling is off if there's a secondary button 

### ISSUE THREAD

**Issue by mikestottuk** [Automattic/jetpack#32345]
### Impacted plugin

Jetpack

### Quick summary

See the video for the behaviour. The external link icon is white on a white background and will need fixing.

https://github.com/Automattic/jetpack/assets/4077604/aba68bdb-f84d-49d0-9b51-f01f5c684607

### Steps to reproduce

1. You'll need to be able to see the Newsletter JITM
2. For that, see code diff D118239

### A clear and concise description of what you expected to happen.

I expected to see the external link icon - to test this you'll need to look at code diff D118239 - there's more testing instructions there.

### What actually happened

I did not see it because it's white on white but it does show up when you hover.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by CodeyGuyDylan** [comment]
@mikemayhem3030 I see you moved this from In Progress to In Review, did you mean to put this in "Needs Review" instead?
