### ISSUE TITLE
Subscriber block: present large subscriber numbers more elegantly

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#32373]
### Impacted plugin

Jetpack

### What

Present these large numbers more elegantly in subscriber block.

### How

![image](https://github.com/Automattic/jetpack/assets/87168/9956672a-4364-451d-af15-524ddb227800)

> we should present these large numbers more elegantly, like on social media platforms
> 100M instead of writing the whole number, which looks like a geocities visitor counter

Let's also check that the number formats are localized correctly. 

Other places to check and ensure everything is consistent:

- [x] Stats (no need to do anything, see https://github.com/Automattic/jetpack/issues/32373#issuecomment-1878590689)
- [x] Reader https://github.com/Automattic/wp-calypso/pull/85984
- [x] Subscriber management https://github.com/Automattic/wp-calypso/pull/86038
- [x] In the editor the block rendering itself, and the sidepanel
    - [x] Server-side (PHP) https://github.com/Automattic/jetpack/pull/32651
    - [x] Editor side (JS) sidebars https://github.com/Automattic/jetpack/pull/34887
    - [x] Editor side (JS) the block at canvas https://github.com/Automattic/jetpack/pull/34919

<img width="280" alt="image" src="https://github.com/Automattic/jetpack/assets/87168/1be43137-efb8-4197-af9a-fe5e9915257f">

<img width="281" alt="image" src="https://github.com/Automattic/jetpack/assets/87168/d5ed9f27-4da6-4646-8cb7-dc4334b0ec43">

<img width="729" alt="image" src="https://github.com/Automattic/jetpack/assets/87168/3b0d0cfc-c307-4fbc-9013-c2e98a87f7f5">

<img width="1287" alt="image" src="https://github.com/Automattic/jetpack/assets/87168/3271261d-c6c7-480c-904e-47f6787234e4">

<img width="1146" alt="image" src="https://github.com/Automattic/jetpack/assets/87168/adff48d1-c842-4a5f-b362-0d3830742149">

<img width="357" alt="Screenshot 2024-01-03 at 16 35 12" src="https://github.com/Automattic/jetpack/assets/87168/8cc20114-8121-4971-833d-afb0a88545a0">
<img width="252" alt="Screenshot 2024-01-03 at 16 34 52" src="https://github.com/Automattic/jetpack/assets/87168/a06378a6-7e7f-41ad-97a2-23c70797010b">

Slack ref p1691598746482899-slack-C052XEUUBL4

**Comment by pkuliga** [comment]
I'm assigning it to me since @lezama is on sabbatical.

**Comment by pkuliga** [comment]
It seems the stats are already looking fine:

<img width="972" alt="Screenshot 2024-01-05 at 13 26 44" src="https://github.com/Automattic/jetpack/assets/4068554/7b2eff0d-7c13-4e48-bad2-a4be4ef032a6">

I am marking it as resolved.

**Comment by simison** [comment]
@pkuliga I added a todo for "Editor side (JS) the block at canvas":

<img width="1295" alt="Screenshot 2024-01-09 at 14 29 14" src="https://github.com/Automattic/jetpack/assets/87168/a19c7e08-40b3-4afb-a3bf-ba14975d0c54">

**Comment by pkuliga** [comment]
> @pkuliga I added a todo for "Editor side (JS) the block at canvas":

PR for it https://github.com/Automattic/jetpack/pull/34919

**Comment by pkuliga** [comment]
Closing it since all tasks are done here.
