### ISSUE TITLE
AtD: Incorrectly modifies pre tag content

### ISSUE THREAD

**Issue by turtlepod** [Automattic/jetpack#3237]
When i was writing a tutorial with several code, I found that Spelling and Grammar will mess up my pre tag.

How to replicate the issue:
1. Paste this content in the text editor : https://dl.dropboxusercontent.com/u/32880842/etc4/spell-grammar-test.txt
2. Switch to visual/text back and forth (it will work fine, no error in the content).
3. Click the Proofread Writing editor toolbar icon https://dl.dropboxusercontent.com/u/32880842/etc4/Proofread-writing-icon.jpg
4. Now the code is messed up.
5. Here's the final content after Proofread Writing: https://dl.dropboxusercontent.com/u/32880842/etc4/spell-grammar-test-failed.txt

Note: I was writing directly in visual editor (not in text editor) but In the example above I use txt file to explain easier and to make sure github will not change anything.

Ideas to fix this: I'm not sure, I think spell check should not modify anything inside code and pre tag.

Many thanks.

**Comment by kraftbj** [comment]
Possibly related to #3220. Something else very similar was reported to us last night via WordPress.com VIP too ( poqVs-bBt-p2 ); @azaozz will be taking a look soonish.
