### ISSUE TITLE
General: Timezone string not synced properly when UTC offset is used

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#3238]
When setting the timezone on a site, using a city/location-based timezone syncs that timezone string over to WordPress.com successfully, but if a user sets a UTC-based offset instead, the timezone string is empty in the blog settings on WordPress.com.

**Comment by jeherve** [comment]
I can't seem to reproduce the issue anymore. Closing. Feel free to reopen if needed.
