### ISSUE TITLE
Enhancement: Mailchimp Block – Double Opt-in Support

### ISSUE THREAD

**Issue by asafm7** [Automattic/jetpack#32406]
### Impacted plugin

Jetpack

### What

Mailchimp Block – Double Opt-in Support

### How

Does the Mailchimp Block support double opt-in?

According to my testing, it doesn't.

A different text message would also be needed ("A confirmation email was sent...")

**Comment by jeherve** [comment]
> According to my testing, it doesn't.

Could you walk us through the steps you followed to test this, so we can try to reproduce?

Thank you.

**Comment by jeherve** [comment]
Closing as duplicate of #14828
