### ISSUE TITLE
Super Cache: plugin clears cache when updating or publishing a post. Regardless of settings

### ISSUE THREAD

**Issue by Kuuuzya** [Automattic/jetpack#32418]
### Impacted plugin

Super Cache

### Quick summary

Few months I can not overcome the problem. I have disabled the setting to clear the cache when publishing. Moreover, I generally only have the mobile caching option enabled (I tried turning it off, it doesn’t help). But the plugin does not care about all the settings and resets the entire cache when publishing or updating a post.

I have over 20,000 posts on my site and it’s just killer. Can you please tell me if there is any way to disable it?

### Steps to reproduce

Just using the plugin

### A clear and concise description of what you expected to happen.

Plugin clears cache every time when I update or post new article

### What actually happened

Cache is totally cleared

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by donnchawp** [comment]
Replied on the support forum, looking for more info: https://wordpress.org/support/topic/plugin-clears-cache-when-updating-or-publishing-a-post-regardless-of-se/#post-16970197

**Comment by donnchawp** [comment]
@Kuuuzya - you never replied on the forum. Did you solve this problem? Was it another plugin causing this issue?

**Comment by Kuuuzya** [comment]
Hi. Yes, it was another plugin, sorry --Отправлено с iPhone22.02.2024, 10:57, "Donncha Ó Caoimh" ***@***.***>:
@Kuuuzya - you never replied on the forum. Did you solve this problem? Was it another plugin causing this issue?

**Comment by donnchawp** [comment]
Closing issue as problem wasn't in WP Super Cache.
