### ISSUE TITLE
Photon: filter_image_downsize should return an array with 4 elements

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3242]
In #3029, we added image dimensions to the `$image` returned by `filter_image_downsize`, and hooked into core's `image_downsize` filter.

`$image` is now an array with 3 different elements:

```php
$image = array(
		jetpack_photon_url( $image_url, $photon_args ),
		$width,
		$height
);
```

We'd need to return a fourth element as well:

> Array containing the image URL, width, height, and boolean for whether the image is an intermediate size. False on failure.

- https://codex.wordpress.org/Function_Reference/image_downsize#Return_Values
- https://github.com/WordPress/WordPress/blob/master/wp-includes/media.php#L193

Reported here:
https://wordpress.org/support/topic/conflict-with-ngfb?replies=4&view=all

**Comment by dereksmart** [comment]
I can look more into this later, but popping in to point out that `$image has been 3 elements since the beginning of Photon.  <a href="https://github.com/Automattic/jetpack/commit/d16147442668e17d9023f0ba67ff2d1e264266ec#diff-71f62265b9fb89148ee4f42b3c900faeR319">#</a>
