### ISSUE TITLE
AI Extension: assistant bar doesn't place correctly, on mobile, when a Jetpack Form instance just creates.

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#32451]
* Go to the block editor
* Ensure that you are in mobile view.
* Create an instance of a Jetpack Form block. 
* **Unexpected**: Check that the assistant bar is placed on the editor canvas.

![Image](https://user-images.githubusercontent.com/77539/260398006-a6dae14d-3f00-4f6d-8ead-242cb5fdbf0a.png)

It should be placed next to the Block toolbar.

**Comment by nunyvega** [comment]
possibly related:

https://github.com/Automattic/jetpack/assets/16329583/ce8c87ac-ca3c-46b0-956d-02db801bd8f8
