### ISSUE TITLE
Carousel: Direct link to individual image stopped working

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#3248]
You used to be able to link directly to individual images in a Carousel, but changeset #3033 seems to have broken that behaviour ( @dereksmart confirmed it by reverting that PR) . We should fix it as some users depend on that behaviour. First reported in 2482864-t.

**Comment by richardmtl** [comment]
I misunderstood; the issue still exists when that changeset is reverted, so more investigation is needed.

**Comment by dereksmart** [comment]
this problem was introduced by #3128
