### ISSUE TITLE
AI Plugin: Long Text Breaks the feedback feature

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#32487]
### Impacted plugin

Jetpack

### Quick summary

When trying to use the Jetpack assistant with a long paragraph of at least 1750 words, the Jetpack AI assistant tells you the service is unavailable (but works when you remove a few words)

![Screenshot 2023-08-15 at 10 37 02 AM](https://github.com/Automattic/jetpack/assets/33553323/3a967ad8-5f97-482d-8470-90d2662937fb)

### Steps to reproduce

1. Add a paragraph block
2. Paste a large bit of text that's at least 1750 words long (this isn't the exact cutoff, not sure what is)
3. Try to use the AI assistant to summarize the text.
4. See the failure.		

### A clear and concise description of what you expected to happen.

If it can't summarize the text because it's too long, I'd expect an error message letting me know the paragraph is too large rather than a more generic failure that the entire service was unavailable.
				

### What actually happened

The screenshot above.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by ederrengifo** [comment]
Here is a Design suggestion to solve this issue. We could reuse some warning components to show this information in this way:

<img width="810" alt="Screen Shot 2023-08-15 at 13 25 48" src="https://github.com/Automattic/jetpack/assets/10525007/089cda52-e56e-448f-9bad-dbd1f92def3d">

This could work as a better way to notify users, however, we should focus on expanding the length of the posts so users can generate feedback from. Also, free requests shouldn't count if this error appears.  cc @madebynoam

**Comment by dhasilva** [comment]
Fixed on https://github.com/Automattic/jetpack/pull/33157.
This is what happens now:
![2023-10-10_10-09-48](https://github.com/Automattic/jetpack/assets/8486249/9799d7ed-4b46-42c7-b60c-d9d0e1b3b5bd)

I'll go ahead and close this issue as solved, but feel free to reopen it or, better, create another issue if you feel this needs a design change.
