### ISSUE TITLE
Testing Enhancement: add Companion plugin to pre-configured testing sites

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#32494]
### Impacted plugin

None / Other

### What

Add the Companion plugin, or similar functionality, to pre-configured test sites

### How

With the pre-configured test sites we offer for the monthly testing, let's add https://github.com/Automattic/companion or something similar to give easy access to enabling testing flags. This plugin is currently available on JN or Ephemerial sites, but our testers are hitting frustration when they're not able to trigger these flags.

context: p1692115311153109-slack-CBG1CP4EN

**Comment by sdixon194** [comment]
Testing sites are now enabled with the companion plugin, closing the issue.
