### ISSUE TITLE
Infinite Scroll: WP_Scripts::print_inline_script is deprecated ( WP 6.3 )

### ISSUE THREAD

**Issue by carolinan** [Automattic/jetpack#32501]
### Impacted plugin

Jetpack

### Quick summary

I am using WordPress 6.3 and Jetpack Version 12.4.
The theme I am using is Simone, which adds:

```
function simone_jetpack_setup() {
	add_theme_support( 'infinite-scroll', array(
		'container' => 'main',
		'footer'    => 'page',
	) );
}
add_action( 'after_setup_theme', 'simone_jetpack_setup' );
```

I don't have a link to this error since it is on my localhost.

When I enable the jetpack settings for infinite scroll, either "Load more posts in page with a button" or "Load more posts as the reader scrolls down",the feature is not working:
- No button for loading more posts is visible
- No additional posts are loaded

In the console of the browser developer tools, I see the following:

```
VM2863:1 Uncaught SyntaxError: Unexpected token '<', "<br />
<b>"... is not valid JSON
    at JSON.parse (<anonymous>)
    at xhr.onload (infinity.js?ver=12.4-is5.0.1:372:24)

```

`VM15370:1 Uncaught SyntaxError: Unexpected token '<', "<br />
<b>"... is not valid JSON
    at JSON.parse (<anonymous>)
    at xhr.onload (infinity.js?ver=12.4-is5.0.1:372:24)
xhr.onload @ infinity.js?ver=12.4-is5.0.1:372
load (async)
Scroller.refresh @ infinity.js?ver=12.4-is5.0.1:371
(anonymous) @ infinity.js?ver=12.4-is5.0.1:85
setInterval (async)
Scroller @ infinity.js?ver=12.4-is5.0.1:78
jetpackInfinityModule @ infinity.js?ver=12.4-is5.0.1:893
infinity.js?ver=12.4-is5.0.1:359 XHR finished loading: POST "http://localhost:10019/?infinity=scrolling".
Scroller.refresh @ infinity.js?ver=12.4-is5.0.1:359
(anonymous) @ infinity.js?ver=12.4-is5.0.1:85
setInterval (async)
Scroller @ infinity.js?ver=12.4-is5.0.1:78
jetpackInfinityModule @ infinity.js?ver=12.4-is5.0.1:893
`

This seems to be because of a deprecation in 6.3 that is not addressed in the infinite scroll module:
```
<br />
<b>Deprecated</b>:  Function WP_Scripts::print_inline_script is <strong>deprecated</strong> since version 6.3.0! Use WP_Scripts::get_inline_script_data() or WP_Scripts::get_inline_script_tag() instead. in <b>/wp-includes/functions.php</b> on line <b>5453</b><br />
<br />
```

In jetpack/modules/infinite-scroll/infinity.php lines 1176 and forward:
```
					// Provide basic script data
					$script_data = array(
						'handle'        => $handle,
						'footer'        => ( is_array( $wp_scripts->in_footer ) && in_array( $handle, $wp_scripts->in_footer, true ) ),
						'extra_data'    => $wp_scripts->print_extra_script( $handle, false ),
						'before_handle' => $wp_scripts->print_inline_script( $handle, 'before', false ),
						**'after_handle'**  => $wp_scripts->print_inline_script( $handle, 'after', false ),
					);

```

I chose "available workarounds -easy to implement" Since replacing the deprecated method should solve the issue.

**This is not a support request** :) I understand that I can turn the display of the PHP warning off and that this solves the issue temporarily.

### Steps to reproduce

First, please ensure that your WordPress test install has enough content so that the infinite scroll has additional content to show.

Activate a theme that supports infinite scroll
Enable either infinite scroll options in the jetpack plugin
View the front of the website and confirm that the feature is not working. Only the spinner shows.

### A clear and concise description of what you expected to happen.

I expect the feature to work.

### What actually happened

There is a JavaScript error.

### Impact

One

### Available workarounds?

Yes, easy to implement

### Logs or notes

Chrome, macOS
No other plugins are active

**Comment by jeherve** [comment]
Thanks for the report!

This was fixed in #32454. The fix will be included in the next Jetpack release, 12.5, scheduled to be released on August 25.
