### ISSUE TITLE
AI Extension: Allow per-field updates for forms

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#32518]
ref pedxs5-i3-p2#comment-132

We have design proposals showing the AI extension toolbar on individual form fields. This could help when only one field needs changes, as asking for single field changes in the form as a whole can be inconsistent.

**Comment by retrofox** [comment]
It will require design feedback. We've added a toolbar button to form children's blocks. https://github.com/Automattic/jetpack/pull/32540

**Comment by dhasilva** [comment]
At the field level we show the assistant. It is still required to ask for the specific field change, but the user can do that and it works.
