### ISSUE TITLE
VideoPress: Allow non-admin roles to upload videos

### ISSUE THREAD

**Issue by julsyd** [Automattic/jetpack#32511]
### Impacted plugin

Jetpack, VideoPress

### What

Allow non-admin user roles (Editor, Author, etc) to upload videos.

### How

For sites with multiple authors, often with Editor or Author roles, it would be good if those users had the ability to upload videos, just like they can upload other media. Site admins don't necessarily want to grant those users access to all admin capabilities, which is currently required in order to upload videos.

> I do wish there was a way to partition off the rest of the admin functions of the site in this account of the “video person”.

Requested in 6643742-zen.

**Comment by jeherve** [comment]
Somewhat related: #21610

**Comment by CGastrell** [comment]
There is no restriction for editors/authors, upload is possible from those roles.

**Comment by davherr** [comment]
That's great news CGastrell - I'll give it a try!

**Comment by CGastrell** [comment]
After testing, I can confirm that all these roles can add videos through the VideoPress block as expected.
A limitation that I can see that non admins can’t access the WP Admin VideoPress Dashboard, which seems fine as an admin only area. Shall someone need to allow a team member to access it, it’s only logical to just grant the team member administrative rights. This is how most wp-admin areas work. Can you please ask the user why they thought that editors and authors can’t add videos? They may be facing a different issue that we are not aware of. Please ask for more details so we can better assist them.


Context: pe4Cmx-1ET-p2#comment-860

**Comment by davherr** [comment]
On this VideoPress doc page is the admin-only reference:
https://jetpack.com/support/jetpack-videopress/uploading-a-video-to-jetpack-videopress/

"Only Jetpack-connected users with the Administrator role can upload videos to a VideoPress-powered site. All Administrators can view all the uploaded videos on the site’s Media Library, irrespective of which Administrator uploaded the video."

**Comment by CGastrell** [comment]
Should we close this then? Do you wanna follow up on the user?

**Comment by davherr** [comment]
Sure, I’ll let the Jetpackians know; I originally asked them the question about the admin requirement.

**Comment by CGastrell** [comment]
Closing as this has been troubleshoot
