### ISSUE TITLE
AI Extension: Validation errors printed on console

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#32517]
ref pedxs5-i3-p2#comment-129

Validation errors happen while streaming and are expected, but they are still shown in the console, which gives the impression that things are unintentionally breaking.

**Comment by retrofox** [comment]
Let's try to address this, but it's expected. Even more, it's useful.

**Comment by retrofox** [comment]
I'd suggest simply closing the issue:

I don’t think there is a straight way to handle this, and I believe there isn’t anything wrong here.
Validation errors are reported by the core, and it isn’t easy to catch them. It’s possible in a hacky way, though. 

The thing is the goal on the horizon is in the opposite direction: `Let’s create blocks without validation errors.`
