### ISSUE TITLE
AI Extension: Keep the form extension toolbar visible when selecting child fields

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#32524]
ref p8oabR-1jo-p2#comment-7512

In the AI Assistant block the changes are made to the inner blocks, so the assistant toolbar is visible even when selecting a specific child block.
That does not happen in the form block, so it can be confusing for users.

**Comment by retrofox** [comment]
Part of p8oabR-1jo-p2#comment-7512:

> I first had trouble figuring out how to revise the form after I created it, but then found it after a minute. Maybe if someone starts creating with AI, keep that box persistent until the form is done to their liking?
> 
> Rob

> I think what @robertbpugh  refers to is that the AI Assistant input box disappears if you click on a child element of the form:
>
> Ali


https://github.com/Automattic/jetpack/assets/77539/1b30ee13-5fda-4afc-a057-fdcddbe9aeed

> Yes, in my example I had to click the form to view the contents of a drop down menu and then the AI box went away. Would be nice to pin it until I’m done. Although I don’t know if that makes sense considering other use cases.
>
> Rob

**Comment by retrofox** [comment]
Changing priority. It affects the UX considerably. From `1:06`, the extension bar gets tricky to find for the user.
