### ISSUE TITLE
AI Extension: AI assistant doesn't iterate over the default field text values

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#32537]
When the default values define the inputs, the AI assistant cannot iterate over them because, from its point of view, they are invisible.

* Create a simple contact form
* Ask for translation to another language
* The new Form doesn't update all text:

![Image](https://github.com/Automattic/jetpack/assets/77539/f44575c7-9aa8-48c8-b654-739783688747)

 Let's find out a way to address this issue.

**Comment by CGastrell** [comment]
Yeah, default values are not actual values I think, they are not there for translation. Maybe we can convince the AI to use default values when the attribute is empty on the particular case of labels?

**Comment by dhasilva** [comment]
Fixed on D123462-code
