### ISSUE TITLE
Comments are erroring out after recent deploy

### ISSUE THREAD

**Issue by buley** [Automattic/jetpack#3254]
<img width="1415" alt="screen shot 2016-01-11 at 3 34 49 pm" src="https://cloud.githubusercontent.com/assets/86985/12250124/859ac59c-b879-11e5-8b01-cee43266aa01.png">

**Comment by chaselivingston** [comment]
Thanks for the report @buley, we're working on getting this resolved ASAP.

**Comment by buley** [comment]
Appreciated @chaselivingston
