### ISSUE TITLE
AI Extension: multiple buttons on the toolbar when using the block on a query loop block

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#32554]
When using the full site editor, if I place the form block on a location that is inside a query loop block, the assistant toolbar button will be repeated multiple times.

How to reproduce:

- test on a site with some published posts
- go to the full site editor
- add a Jetpack Form block on a location inside the frontpage query loop; this is a `twenty twenty-three` example location:

<img width="600" alt="Screenshot 2023-08-17 at 12 32 19" src="https://github.com/Automattic/jetpack/assets/6760046/47c270e6-7e3a-4c78-b8a4-644aa7f61fbc">

- confirm the toolbar button is repeated multiple times:

<img width="600" alt="Screenshot 2023-08-17 at 12 32 53" src="https://github.com/Automattic/jetpack/assets/6760046/e0201d02-6956-4ad1-af9f-54eec530549b">

**Comment by dhasilva** [comment]
Reopening so we can track the investigation to enable it back without the multiple buttons.
