### ISSUE TITLE
AI Extension: consider reducing field labeling for cleaner forms

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#32559]
Our current iteration generates forms that are too verbose. Note how many elements are created to annotate the name input in this image:

![Image](https://user-images.githubusercontent.com/6760046/261408666-1767591b-0c78-43a8-8b89-360975ba98bf.png)

- “Your Name” label
- “Please enter your name” sublabel
- “Enter your name” placeholder

Unless we’ve already aligned on this elsewhere, we could make do with a significantly simplified form that preserves the label and transforms the placeholder into example values appropriate for that input type.

Example:

![Image](https://user-images.githubusercontent.com/6760046/261408776-427160cb-6d71-4a4a-b076-84f643c12c87.png)

More context: pedxs5-i3-p2#comment-136

**Comment by dhasilva** [comment]
The text besided the label is the required text.
Required field fixed here: https://github.com/Automattic/jetpack/pull/32543
