### ISSUE TITLE
AI Extension: the assistant will not start a new form if it is requested as a follow up change

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#32566]
How to replicate:

- add a form block and ask for some form (example: "a car rental form")
- after the form is ready, ask the assistant for another type of form (example: "a contact form")
- the assistant will repeat the previous form without changing it

It's an edge case, asking for a new form over the old one, but we may tweak the prompt to make it clear to GPT that it can start the form over again if the user asks for it.

---

Context: pedxs5-i3-p2#comment-143

Video: https://video.wordpress.com/v/wlkJihA2

**Comment by retrofox** [comment]
From my PoV, it isn't an issue per sé. 

I created a `Pizza form`, and then ask a new form, but explicitly asked to replace it with a new one.


![Image](https://github.com/Automattic/jetpack/assets/77539/de31c878-e1f2-4d3e-b428-b90948ea300b)

![Image](https://github.com/Automattic/jetpack/assets/77539/8dedb24f-b597-4a55-98f3-3ba07a3583c0)

**Comment by lhkowalski** [comment]
So it's just a matter of asking on the right way, or then deleting the existing form an starting over. I am ok with closing the issue. We can always reopen it and rethink the prompt in case a large amount of users start complaining about this, or if we discover this is the modus operandi of a large amout of users.
