### ISSUE TITLE
AI Extension: form generated on FSE contains HTML left-overs

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#32561]
Using the extension on a form inside FSE may result on forms with HTML left-overs:

![Image](https://user-images.githubusercontent.com/6760046/261411344-82db6979-5833-4abf-a011-5604d6dc532d.png)

Another example:

![Image](https://user-images.githubusercontent.com/6760046/261411472-3ef04502-9140-4648-843a-35d198f9be46.png)

**Comment by dhasilva** [comment]
@retrofox Are you working on this one or can I take it?
