### ISSUE TITLE
Form block: Changing the style throws an error while the preview window is loading.

### ISSUE THREAD

**Issue by rakshitwesley** [Automattic/jetpack#32582]
### Impacted plugin

Jetpack

### Quick summary

While changing the styles on "Form block", the editor throws an error: "The editor has encountered an unexpected error."
![JkfSAY.png](https://github.com/Automattic/jetpack/assets/95758851/37d260c1-1043-4dd1-bd50-e76a2a5fac80)

### Steps to reproduce

1. Add a form block
2. Select the "Form block" and navigate to the Styles tab on the right sidebar: ![P5qXN6.png](https://github.com/Automattic/jetpack/assets/95758851/6118742c-9d85-4682-a327-7fdd6a7a8fcd)
3. Move the cursor to one of the options listed under "Styles section" and stay there while the preview loads.

### A clear and concise description of what you expected to happen.

You would expect the preview to load and select one of these options

### What actually happened

The editor throws an error: 
https://github.com/Automattic/jetpack/assets/95758851/3d9fe83a-03b8-46d3-b8dd-326a45d1c19f

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

The issue can be replicated only on simple sites. With both site editor and classic themes.

_No response_

**Comment by rakshitwesley** [comment]
6687607-zd-a8c

**Comment by andrii-lysenko** [comment]
Thanks @rakshitwesley. Unfortunately, this doesn't reproduces for me. Any chance you have error logs for this one? Thanks!

**Comment by rakshitwesley** [comment]
@andrii-lysenko Thanks for looking into this! It appears to have resolved now.
