### ISSUE TITLE
WP Super Cache: Deprecation message since v1.10 with PHP 8.1

### ISSUE THREAD

**Issue by unitb-ore** [Automattic/jetpack#32580]
### Impacted plugin

Super Cache

### Quick summary

After updating WP Super Cache from 1.9.4 to 1.10, a deprecation message is thrown using PHP 8.1:

> Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/wordpress/wp-content/plugins/wp-super-cache/wp-cache-phase2.php on line 54

The changelog states "Fix null/false warning in PHP8.1", but prior to this update I had no issue.

### Steps to reproduce

Open a page of your WordPress, when WP Super Cache 1.10 is activated, using PHP 8.1.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by youbrokesomething** [comment]
A fix for this issue has been completed and will be included in v1.10.1.

**Comment by unitb-ore** [comment]
> A fix for this issue has been completed and will be included in v1.10.1.

When will v1.10.1 be released?

**Comment by jeherve** [comment]
cc @donnchawp

**Comment by donnchawp** [comment]
We're aiming to get a bugfix release out this week.

**Comment by donnchawp** [comment]
I'll need to leave this go for about 10 days. We have a meetup next week when we're going to be extra busy. If anything major breaks in a new release we may not get to fix it quickly. Better safe than sorry.

**Comment by MickaelViaud** [comment]
Hello here, any news about this update ?

**Comment by donnchawp** [comment]
The latest release of WP Super Cache, 1.11.0, fixed this problem.
