### ISSUE TITLE
Enhancement:Newsletter settings

### ISSUE THREAD

**Issue by mikestottuk** [Automattic/jetpack#32656]
### Impacted plugin

Jetpack

### What

Enhance the Newsletter settings page

### How

The current settings for Newsletter shows the following. 

<img width="1107" alt="Screenshot 2023-08-24 at 10 49 29" src="https://github.com/Automattic/jetpack/assets/4077604/ecb60572-5722-405f-b473-2c62c371c225">

I wonder if "subscribe to comments" should be moved and separate the settings between:-
- Discussion: comments - where these settings were prior
- Newsletter: subscribe to new posts ~~and comments~~ via email

There's also additional settings for Newsletter on dotcom that we should sync with Jetpack (e.g. modal settings when release) and confirm subscription messaging etc.

<img width="1353" alt="modal-setting" src="https://github.com/Automattic/jetpack/assets/4077604/baf3e64b-31a8-4920-8354-a4bd91a89d6e">

**Comment by simison** [comment]
The missing settings should now be mostly in Jetpack.
