### ISSUE TITLE
Visual focus indicator seems to be getting cropped on JP Comment Block

### ISSUE THREAD

**Issue by kimclow** [Automattic/jetpack#32657]
### Impacted plugin

Jetpack

### Quick summary

The visual indicator is being ever-so-slightly cropped on the Jetpack post comment block. 

<img width="684" alt="Screenshot 2023-08-24 at 12 14 40" src="https://github.com/Automattic/jetpack/assets/83212200/9c65de8b-0fe7-4d6a-a96e-81581180f781">

### Steps to reproduce

- Go to https://dubechoes2023.wpcomstaging.com/crew/
- Press tab to reach the buttons

### A clear and concise description of what you expected to happen.

I would expect the visual indicator to be fully visible. 

### What actually happened

The bottom few pixels are cropped. 

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

Initially reported here: https://github.com/a8cteam51/dub-echoes/issues/11

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Self-Hosted – **Replicated**
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
My dotcom sites show a redesigned version of these options, but my self-hosted site shows the slight crop under the focus indicator as described:

![Markup on 2023-08-24 at 15:54:00](https://github.com/Automattic/jetpack/assets/27249804/0c4aba25-46f4-4f57-a56d-c12067968868)

📌 ACTIONS
- Triage complete
- lowered priority to Low

**Comment by jeherve** [comment]
cc @alshakero, who worked on some comments improvements lately with his team.

**Comment by alshakero** [comment]
Hi! Closing this as no longer relevant. This UI was highlander, it is now fully replaced by Verbum.
