### ISSUE TITLE
JetPack doesn't recognize Elementor's custom "Thumbnails"

### ISSUE THREAD

**Issue by alphavaletec** [Automattic/jetpack#32694]
### Impacted plugin

Jetpack

### Quick summary

JetPack doesn't recognize Elementor's custom "Thumbnails"

When using custom image size in Elementor, JetPack does not load on CDN.

![image](https://github.com/Automattic/jetpack/assets/115041212/aa562a4d-6c54-4cd5-82d2-d63c69c2cda0)

Image path that Elementor adds:
wp-content/uploads/elementor/thumbs/b4piNJ-qbed0kbr48bqq9f2t3guri6mpnkkub7olndc9l8tl4.jpeg

### Steps to reproduce

Wordpress + Elementor
wp-content/uploads/elementor/thumbs/name-image.jpg

### A clear and concise description of what you expected to happen.

Custom images are loaded on the CDN

### What actually happened

JetPack seems to ignore custom image path

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

Jetpack - 12.5
Wordpress - 6.3
Elementor - 3.15.3

**Comment by jeherve** [comment]
Thanks for the report! We're tracking a somewhat similar issue in #22052. This may be fixed by this change in the Elementor plugin:
https://github.com/elementor/elementor/pull/17181

I'll consequently close this issue as duplicate.

**Comment by alphavaletec** [comment]
Thank you for your attention!

However, the problem still persists.

The "JetPack" replaces the "custom" image with the wordpress thumbnail.

Your code didn't work for me.

**Comment by jeherve** [comment]
> Your code didn't work for me.

Thanks for the feedback. Do you mean that you've tried the Elementor patch I submitted in https://github.com/elementor/elementor/pull/17181 ? It's been a few years unfortunately, so my patch wasn't up to date anymore. I've just updated that Pull Request with the latest version of Elementor, and including changes we've made to Jetpack's Image CDN feature in the past few years. Do you think you could give it another try?
If it still doesn't work, would you mind commenting on the Pull Request there, so the Elementor team knows someone gave it a try and would be interested in getting this issue fixed?

Thank you!
