### ISSUE TITLE
Contact Form: telephone field not working properly

### ISSUE THREAD

**Issue by bisko** [Automattic/jetpack#3270]
While I was working on #3215 I noticed that the `telephone` field has been partially added to the Contact Form code, but it is not working properly.

It seems the field has no way to be selected and added to the form. It is missing from the dropdown, when creating a new Contact Form, which means that I have to add it by hand in the shortcode.

If I add it by hand it renders broken HTML - an `input` field, followed by a `textarea`. This behavior is caused by a missing `break` statement [here](https://github.com/Automattic/jetpack/blob/master/modules/contact-form/grunion-contact-form.php#L2007-L2011). 

If saved, the `textarea` value overwrites the `input` field value. 

I see that the field is saved in the post content of the saved feedback form and it is not added as a part of the author meta fields. This can lead to a problem at some point with rendering and/or export of the forms. Currently if the field is saved (and the above mentioned `break` bug gets fixed), there is no way to see it in the admin, without choosing `edit` on the resulting feedback form post. 

@jeherve @chaselivingston Can you shed some light on the issue and on the design behind the field?

**Comment by jeherve** [comment]
Related: #1562, #955.

I'll close this issue in favour of the original issue about this, #269, that was never closed because the implementation was never completed, as you discovered.

I'll copy your comment there, as it includes some useful information for whoever wants to pick this up.
