### ISSUE TITLE
Sharing: add Bluesky option

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#32708]
### Impacted plugin

Jetpack

### What

When the new Bluesky platform offers sharing URLs, let's add a Bluesky sharing button to our list of options

### How

See #31537 for prior art (this is the last button we added).

Related: #30460 for Jetpack Social (née Publicize).

**Comment by benharri** [comment]
compose intent is now available:
https://bsky.app/profile/bsky.app/post/3kmjboaopvn2f

url is this format:
`https://bsky.app/intent/compose?text=""`

**Comment by csonnek** [comment]
A request in: https://wordpress.com/forums/topic/social-media-sharing-buttons-for-bluesky/?view=all

Edited to add: I didn't realized the request was made before it was implemented. I'll let them know it'll be out soon!

**Comment by jeherve** [comment]
@csonnek Since we release a new version of Jetpack to WordPress.com Simple every day, the Bluesky button is already available on WordPress.com, no need to wait for it there!

**Comment by csonnek** [comment]
TIL for Simple sites! Thanks @jeherve
