### ISSUE TITLE
Embed Blocks: some block names have a strange unicode square character in front.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/jetpack#32704]
### Quick summary

Some embed services such as Instagram have a square character in front of the name, like so: `" Instagram"`

![image](https://github.com/Automattic/wp-calypso/assets/6549265/54b6e167-287c-4489-b792-398082973c81)

### Steps to reproduce

1. start a post.
2. open the block inserter sidebar.
3. open F12.
4. using accessibility inspector, look for the Instagram block.

### What you expected to happen

Instagram block name is "Instagram".

### What actually happened

Instagram block name is " Instagram"

### Impact

All

### Available workarounds?

Yes, easy to implement

**Comment by jeherve** [comment]
This is interesting. Those blocks are provided by the Jetpack plugin, so this issue may belong in the Jetpack repo.

What's odd is that this doesn't happen for all Jetpack embed blocks. Loom for example does not have the issue.

I may have something to do with the icons we use for those:

https://github.com/Automattic/jetpack/blob/3a3c4adc1c0913bac224ddb832713bd6101fe1ab/projects/plugins/jetpack/extensions/extended-blocks/core-embed/instagram.js#L10
https://github.com/Automattic/jetpack/blob/3a3c4adc1c0913bac224ddb832713bd6101fe1ab/projects/plugins/jetpack/extensions/extended-blocks/core-embed/facebook.js#L9
https://github.com/Automattic/jetpack/blob/3a3c4adc1c0913bac224ddb832713bd6101fe1ab/projects/plugins/jetpack/extensions/blocks/instagram-gallery/index.js#L16

It may be worth using an SVG instead, like Gutenberg does for its own embeds:
https://github.com/WordPress/gutenberg/blob/12c60c785c2a34dce782b5f674b58ed54a8eaca1/packages/block-library/src/embed/variations.js#L120
