### ISSUE TITLE
Create with voice: research MVP design for the WP Admin content

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#32735]
We want to approach this in a way that is platform-agnostic, meaning that it would be possible to use the feature from the posts list block of the WP Admin page, for example.

If we have the time, it would be worth giving it a shot.ng it a shot.

`Low` priority, just in case.

**Comment by lhkowalski** [comment]
Closing this since the focus is now on P2. We can reopen it in case we start looking to Jetpack sites again, in the near future.
