### ISSUE TITLE
Cleanup JS config

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#32779]
There is a `Automattic\Jetpack_Boost\Admin\Config` that provides some config options to the JS app. However, with the data-sync, many of these configurations are no longer in use. Possibly, the remaining configuration can be migrated to data-sync as well.

So,
- See if there are alternatives to these configurations in data-sync, if yes, use the data-sync version.
- Check if there are configurations that are no longer in use. If there are any, remove them.
- Evaluate if the remaining options are possible to be migrated to data-sync. If they are, migrate them.

**Comment by thingalon** [comment]
Seems like something we can touch on since we're tinkering on datasync as a part of the migration.
