### ISSUE TITLE
Voice to Content: ensure proper error handling (UI)

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#32770]
We need to let the user know about some errors that could happen in the process.
For instance, when the mic is not enabled by the client.
Let's figure out how we can implement a message in the UI. I suggest the editor notice.

**Comment by nunyvega** [comment]
- If the site is not safe, not using a safe origin, for example not on an HTTPS connection, Google Chrome does not allow you to use the microphone, nor offers you a setting to do so. This happens in the case of a JN site.
- When this is the case, the button does not work, does not change the state when clicked and does not throw an error
- There is an experimental feature in chrome that allows you to add an exception, you can find it in chrome://flags/#unsafely-treat-insecure-origin-as-secure
- Once the site is added as an exception, the button work as expected

Similar issue on Safari, but I did not research how to fix it.

**Comment by lhkowalski** [comment]
The design includes a very simple error message style that we can leverage to show any errors we need to show:

![Image](https://github.com/Automattic/jetpack/assets/6760046/488669ff-4749-46f6-8c31-dc0cdbb9963f)
