### ISSUE TITLE
Protect: Login link from Bluehost causes PHP errors

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#3279]
I think this also involves SSO but I'm not sure.

In 2489890-t the site owner says that, to log in to her site, she first logs in to Bluehost's control panel. From there, she has a green button that says "Log into my site". If Jetpack is active, she then gets the following error (but it logs her in if Jetpack is deactivated):

*Warning*: Missing
argument 2 for Jetpack_Protect_Module::log_successful_login() in
*/home7/XXXXXXX/public_html/wp-content/plugins/jetpack/modules/protect.php* on
line *315*

*Warning*: Cannot modify header information - headers already sent by
(output started at
/home7/XXXXXXX/public_html/wp-content/plugins/jetpack/modules/protect.php:315)
in*/home7/XXXXXXX/public_html/wp-includes/pluggable.php* on line *1228*

The URL for this error is:

domain.com/wp-admin/admin-ajax.php?action=sso-check&nonce=(nonce_goes_here)

If she goes to wp-login.php she has no error and no trouble logging in.

Is this a bug in how Bluehost sends users to the login, or is it something in Protect?

**Comment by kraftbj** [comment]
I checked the Bluehost code (mu-plugins/sso.php on a BH install) and it is on their end. do_action in core has 2 args, their version has 1. I'll report it up to them.

**Comment by kraftbj** [comment]
Bluehost has applied the patch to resolve this and it is in their QA process now. It should be live on their end soon. I informed the OP.
