### ISSUE TITLE
Carousel / Tiled Galleries: review w3c validator output

### ISSUE THREAD

**Issue by tripsoverpoland** [Automattic/jetpack#32819]
### Impacted plugin

Jetpack

### Quick summary

How can this be disabled from the code generated in the jetpack-carousel.php file:

**data-image-meta="{"aperture":"0","credit":"","camera":"","capti**on":"","created_timestamp":"0","copyright":"","focal_length":"0","iso":"0","shutter_speed":"0","title":"","orientation":"0"}"

The W3C validator displays errors for this section - Please check e.g. the website: https://blog.tripsoverpoland.pl/2023/07/26/malbork-15-06-2023-zmiany-wokol-zamku-i-w-panoramie-zza-nogatu/

Error: Attribute aperture":"0","credit":"","camera":"","caption":"","created_timestamp":"0","copyright":"","focal_length":"0","iso":"0","shutter_speed":"0","title":"","orientation":"0"}" not allowed on element [img](https://html.spec.whatwg.org/multipage/#the-img-element) at this point.

[From line 36, column 9638; to line 38, column 212](https://validator.w3.org/nu/?doc=https%3A%2F%2Fblog.tripsoverpoland.pl%2F2023%2F07%2F26%2Fmalbork-15-06-2023-zmiany-wokol-zamku-i-w-panoramie-zza-nogatu%2F&showsource=yes#l38c212)

age/webp"><img width="1280" height="674" src="https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Ma…ation":"0"}" data-image-title="Malbork 15.06.2023" data-image-description="<p>Malbork 15.06.2023</p>↩" data-image-caption="<p>Malbork 15.06.2023</p>↩" data-medium-file="https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-650x34…large-file=["https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-1000x527.jpg"](https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-1000x527.jpg)></pict

in source code:
in source code:

    <picture><source srcset=["https://blog.tripsoverpoland.pl/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2023/07/23_Malbork_003.jpg.webp 1280w, https://blog.tripsoverpoland.pl/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2023/07/23_Malbork_003-650x342.jpg.webp 650w, https://blog.tripsoverpoland.pl/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2023/07/23_Malbork_003-1000x527.jpg.webp 1000w, https://blog.tripsoverpoland.pl/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2023/07/23_Malbork_003-150x79.jpg.webp 150w, https://blog.tripsoverpoland.pl/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2023/07/23_Malbork_003-768x404.jpg.webp 768w"](https://blog.tripsoverpoland.pl/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2023/07/23_Malbork_003.jpg.webp1280w,https://blog.tripsoverpoland.pl/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2023/07/23_Malbork_003-650x342.jpg.webp650w,https://blog.tripsoverpoland.pl/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2023/07/23_Malbork_003-1000x527.jpg.webp1000w,https://blog.tripsoverpoland.pl/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2023/07/23_Malbork_003-150x79.jpg.webp150w,https://blog.tripsoverpoland.pl/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2023/07/23_Malbork_003-768x404.jpg.webp768w) sizes="(max-width: 1280px) 100vw, 1280px" type="image/webp"><img width="1280" height="674" src=["https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003.jpg"](https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003.jpg) class="attachment-post-thumbnail size-post-thumbnail wp-post-image webpexpress-processed" alt="Malbork 15.06.2023" decoding="async" style="object-fit:cover;" fetchpriority="high" srcset=["https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003.jpg 1280w, https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-650x342.jpg 650w, https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-1000x527.jpg 1000w, https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-150x79.jpg 150w, https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-768x404.jpg 768w"](https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003.jpg1280w,https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-650x342.jpg650w,https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-1000x527.jpg1000w,https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-150x79.jpg150w,https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-768x404.jpg768w) sizes="(max-width: 1280px) 100vw, 1280px" data-attachment-id="337183" data-permalink=["https://blog.tripsoverpoland.pl/23_malbork_003/"](https://blog.tripsoverpoland.pl/23_malbork_003/) data-orig-file=["https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003.jpg"](https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003.jpg) data-orig-size="1280,674" data-comments-opened="1" data-image-meta="{"aperture":"0","credit":"","camera":"","caption":"","created_timestamp":"0","copyright":"","focal_length":"0","iso":"0","shutter_speed":"0","title":"","orientation":"0"}" data-image-title="Malbork 15.06.2023" data-image-description="<p>Malbork 15.06.2023</p>↩
    " data-image-caption="<p>Malbork 15.06.2023</p>↩
    " data-medium-file=["https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-650x342.jpg"](https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-650x342.jpg) data-large-file=["https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-1000x527.jpg"](https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-1000x527.jpg)></picture>
    
    I created a thread on the forum:

https://wordpress.org/support/topic/html-code-non-compliance-with-w3c/

Since the reported problems do not only affect me, but probably all Jetpack users, I kindly ask you to take a look at the html codes generated by Jetpack and correct them so that the W3C validator does not diagnose such errors again.

Despite turning off the options related to showing meta tags for photos, Jepack still shows them in the html code. I described it in this passage:

How can this be disabled from the code generated in the jetpack-carousel.php file:

data-image-meta=”{“aperture”:”0″,”credit”:””,”camera”:””,”caption”:””,”created_timestamp”:”0″,”copyright”:””,”focal_length”:”0″,”iso”:”0″,”shutter_speed”:”0″,”title”:””,”orientation”:”0″}” The W3C validator displays errors for this section – Please check e.g. the website: https://blog.tripsoverpoland.pl/2023/07/26/malbork-15-06-2023-zmiany-wokol-zamku-i-w-panoramie-zza-nogatu/

Error: Attribute aperture":"0","credit":"","camera":"","caption":"","created_timestamp":"0","copyright":"","focal_length":"0","iso":"0","shutter_speed":"0","title":"","orientation":"0"}" not allowed on element [img](https://html.spec.whatwg.org/multipage/#the-img-element) at this point.

I know I don't have a paid Jetpack plan, but the W3C and other bugs described are not befitting such a serious company that makes its interesting solutions available to a large number of users. So I hope you fix them soon.
I myself recently replaced redundant "/>" tags with ">" in the Jetpack source codes on my blog, but as I'm sure you know, this is not a good target solution for this and other similar problems.

In addition, the following disabled options in the plugin settings do not cause the lack of these parameters in the html code generated by the plugin:
<img width="760" alt="image" src="https://github.com/Automattic/jetpack/assets/143954937/9704bd6f-8c73-414c-813d-b4ccfca8a8e8">

### Steps to reproduce

1.Use the W3C validator at: https://validator.w3.org/

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by jeherve** [comment]
Thanks for the report. We'll take a look at those notices when we next iterate on the Carousel and Tiled Gallery features. Until then, you can rest assured: such notices will not break anything on your site, nor will they impact the display of images and galleries in different browsers.

**Comment by anomiex** [comment]
Can't reproduce with the links given, [apparently](https://wordpress.org/support/topic/html-code-non-compliance-with-w3c/#post-17000465) the user has edited the code themselves.

Further, I see nothing in Jetpack that would product the `<picture>` and `<source>` tags quoted in the report:
```
<picture><source srcset="https://blog.tripsoverpoland.pl/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2023/07/23_Malbork_003.jpg.webp 1280w, https://blog.tripsoverpoland.pl/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2023/07/23_Malbork_003-650x342.jpg.webp 650w, https://blog.tripsoverpoland.pl/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2023/07/23_Malbork_003-1000x527.jpg.webp 1000w, https://blog.tripsoverpoland.pl/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2023/07/23_Malbork_003-150x79.jpg.webp 150w, https://blog.tripsoverpoland.pl/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2023/07/23_Malbork_003-768x404.jpg.webp 768w" sizes="(max-width: 1280px) 100vw, 1280px" type="image/webp"><img width="1280" height="674" src="https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image webpexpress-processed" alt="Malbork 15.06.2023" decoding="async" style="object-fit:cover;" fetchpriority="high" srcset="https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003.jpg 1280w, https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-650x342.jpg 650w, https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-1000x527.jpg 1000w, https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-150x79.jpg 150w, https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-768x404.jpg 768w" sizes="(max-width: 1280px) 100vw, 1280px" data-attachment-id="337183" data-permalink="https://blog.tripsoverpoland.pl/23_malbork_003/" data-orig-file="https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003.jpg" data-orig-size="1280,674" data-comments-opened="1" data-image-meta="{"aperture":"0","credit":"","camera":"","caption":"","created_timestamp":"0","copyright":"","focal_length":"0","iso":"0","shutter_speed":"0","title":"","orientation":"0"}" data-image-title="Malbork 15.06.2023" data-image-description="<p>Malbork 15.06.2023</p>↩
" data-image-caption="<p>Malbork 15.06.2023</p>↩
" data-medium-file="https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-650x342.jpg" data-large-file="https://blog.tripsoverpoland.pl/wp-content/uploads/2023/07/23_Malbork_003-1000x527.jpg"></picture>
```

I see they mention also using a plugin called WebP Express. That plugin [does indeed produce `<picture>` and `<source>` tags](https://github.com/rosell-dk/dom-util-for-webp/blob/618d8cb26e744135934b6837e6b0ed9acc925f1e/src/PictureTags.php#L270-L273), and when it [creates the attribute strings](https://github.com/rosell-dk/dom-util-for-webp/blob/618d8cb26e744135934b6837e6b0ed9acc925f1e/src/PictureTags.php#L180-L182) for that output it appears to lack proper encoding of attributes.

I'd suggest you file a bug with the WebP Express plugin, as it seems to be mangling the correct HTML generated by Jetpack.

**Comment by tripsoverpoland** [comment]
Yes, I actually commented out a few lines in the jetpack-carousel.php file so that you don't see the snippet in the source code of the page:
"data-image-meta="{"aperture":"0","credit":"","camera":"","caption":"","created_timestamp":"0","copyright": "","focal_length":"0","iso":"0","shutter_speed":"0","title":"","orientation":"0"}".
Now only a small fragment of data-image-meta="" is visible in the code of the page, and the point is that the settings in the plugin's control panel do not display the exif data of the photos in the code at all. It does not work according to these settings.
I asked how can I do it effectively by changing something in the code of the jetpack-carousel.php file, because my changes are not entirely effective. So I kindly ask you to take into account the plugin settings in generating the code regarding the visibility or not of the exif parameters. In the case of my photos, I have been deleting all exif parameters for many years to make the size of the photos as small as possible and I do not want these parameters to be visible in the website code.

Just to clarify, the picture../picture code is created by another WEBP Express plug-in and it does not generate the code related to the exif parameters of the photos. So this issue is still related to the Jetpack plugin..

**Comment by anomiex** [comment]
It sounds like you're trying to talk about two separate issues here.

The first and more serious is the bug that WebP Express is mangling the valid attributes generated by Jetpack. There's nothing we can do about that, despite your belief that "this issue is still related to the Jetpack plugin". Any other plugin that adds properly-escaped attributes with values containing `"` (and possibly also `>` and certain other characters) to an `<img>` will similarly be broken by WebP Express.

The second and more trivial is the enhancement request that you want turning off the "Show photo Exif metadata in carousel" option to prevent the generation of the `data-image-meta` attribute in the HTML. I'd recommend you file that as a separate issue rather than trying to tack it on to this one.

**Comment by tripsoverpoland** [comment]
I have reported here an issue with the errors/warnings detected by the W3C validator, but they are due to my e.g. According to Jetpack plug-in malfunction with exif settings for photos. So I covered it in one submission.
If necessary and it will be helpful, I can create a new report in this regard, but it seems to me that then the picture of these errors will not be complete.

The author of the WEBP EXPRESS plugin has already analyzed this problem and in his opinion, his plugin only creates an alternative to jpg files by creating the picture.. srcset...picture code, in which it adds an additional webp photo format. The rest is code created by Jetpack.

**Comment by anomiex** [comment]
There's already https://github.com/Automattic/jetpack/issues/32818 about any errors actually due to Jetpack, no need to file another issue about that.

> The author of the WEBP EXPRESS plugin has already analyzed this problem and in his opinion, his plugin only creates an alternative to jpg files by creating the picture.. srcset...picture code, in which it adds an additional webp photo format. The rest is code created by Jetpack.

:shrug: He might try comparing the input he's getting from Jetpack compared to the output his plugin is generating to realize why he's wrong.

**Comment by tripsoverpoland** [comment]
I don't know which plugin creates the first code for embedded images and which one modifies it and creates the final code.
The following actions were performed on the indicated entry:
1. Uploading photos to the blog's media and then WEBP creates their equivalents in webp format for jpg files in a separate folder
2. Creating a new blog entry
3. Adding content and several tiled galleries containing a dozen/dozens of photos downloaded from the blog's media - this is the moment for Jetpack to work and insert its code. Whether WEBP EXPRESS adds its code before or after Jetpack is hard for me to determine.

**Comment by alinclamba** [comment]
@tripsoverpoland provided some more details today in the public forum, adding this here so it might help: 
https://wordpress.org/support/topic/html-code-non-compliance-with-w3c/#post-17026340

**Comment by anomiex** [comment]
Thanks for the link. Other than the list of some additional plugins they use it seems a rehash of their comments here above.

I still recommend someone file a separate issue for the feature request part of the complaint.

**Comment by tripsoverpoland** [comment]
> Thanks for the link. Other than the list of some additional plugins they use it seems a rehash of their comments here above.
> 
> I still recommend someone file a separate issue for the feature request part of the complaint.

The problem with showing or not exif data in the html code according to the plugin settings does not seem to me to be a request for new functionality, but rather relates to a currently non-working functionality.

**Comment by anomiex** [comment]
> The problem with showing or not exif data in the html code according to the plugin settings does not seem to me to be a request for new functionality, but rather relates to a currently non-working functionality.

I should have said "enhancement request" rather than "feature request". Sorry.

But here's the bottom line on that: you can keep arguing here and _not_ have your enhancement request get any attention because there's no GitHub issue to track it, or you can create the enhancement request.

**Comment by tripsoverpoland** [comment]
For ease, I restored the original jetpack-carousel.php file from 24/08/2023 on the blog and the number of errors/warnings increased from 553 lines to over 1000 lines (more W3C validator no longer shows) - see: [https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fblog.tripsoverpoland.pl%2F2023%2F07%2F26%2Fmalbork-15-06-2023-zmiany-wokol-zamku-i-w-panoramie-zza-nogatu%2F]
Multiple repeating rows for each photo:

Error: No space between attributes.

[At line 217, column 748](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fblog.tripsoverpoland.pl%2F2023%2F07%2F26%2Fmalbork-15-06-2023-zmiany-wokol-zamku-i-w-panoramie-zza-nogatu%2F#cl217c748)

-image-meta="{"aperture":"0","

Error: Quote " in attribute name. Probable cause: Matching quote missing somewhere earlier.

[At line 217, column 756](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fblog.tripsoverpoland.pl%2F2023%2F07%2F26%2Fmalbork-15-06-2023-zmiany-wokol-zamku-i-w-panoramie-zza-nogatu%2F#cl217c756)

eta="{"aperture":"0","credit":

Error: Quote " in attribute name. Probable cause: Matching quote missing somewhere earlier.

[At line 217, column 758](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fblog.tripsoverpoland.pl%2F2023%2F07%2F26%2Fmalbork-15-06-2023-zmiany-wokol-zamku-i-w-panoramie-zza-nogatu%2F#cl217c758)

a="{"aperture":"0","credit":""

Error: Quote " in attribute name. Probable cause: Matching quote missing somewhere earlier.

[At line 217, column 760](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fblog.tripsoverpoland.pl%2F2023%2F07%2F26%2Fmalbork-15-06-2023-zmiany-wokol-zamku-i-w-panoramie-zza-nogatu%2F#cl217c760)

"{"aperture":"0","credit":"","

Error: Quote " in attribute name. Probable cause: Matching quote missing somewhere earlier.

[At line 217, column 762](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fblog.tripsoverpoland.pl%2F2023%2F07%2F26%2Fmalbork-15-06-2023-zmiany-wokol-zamku-i-w-panoramie-zza-nogatu%2F#cl217c762)

"aperture":"0","credit":"","ca

Error: Quote " in attribute name. Probable cause: Matching quote missing somewhere earlier.

[At line 217, column 769](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fblog.tripsoverpoland.pl%2F2023%2F07%2F26%2Fmalbork-15-06-2023-zmiany-wokol-zamku-i-w-panoramie-zza-nogatu%2F#cl217c769)

re":"0","credit":"","camera":"

Error: Quote " in attribute name. Probable cause: Matching quote missing somewhere earlier.

[At line 217, column 771](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fblog.tripsoverpoland.pl%2F2023%2F07%2F26%2Fmalbork-15-06-2023-zmiany-wokol-zamku-i-w-panoramie-zza-nogatu%2F#cl217c771)

":"0","credit":"","camera":"",

Error: Quote " in attribute name. Probable cause: Matching quote missing somewhere earlier.

[At line 217, column 772](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fblog.tripsoverpoland.pl%2F2023%2F07%2F26%2Fmalbork-15-06-2023-zmiany-wokol-zamku-i-w-panoramie-zza-nogatu%2F#cl217c772)

:"0","credit":"","camera":"","

Error: Quote " in attribute name. Probable cause: Matching quote missing somewhere earlier.

[At line 217, column 774](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fblog.tripsoverpoland.pl%2F2023%2F07%2F26%2Fmalbork-15-06-2023-zmiany-wokol-zamku-i-w-panoramie-zza-nogatu%2F#cl217c774)

0","credit":"","camera":"","ca

Error: Quote " in attribute name. Probable cause: Matching quote missing somewhere earlier.

[At line 217, column 781](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fblog.tripsoverpoland.pl%2F2023%2F07%2F26%2Fmalbork-15-06-2023-zmiany-wokol-zamku-i-w-panoramie-zza-nogatu%2F#cl217c781)

dit":"","camera":"","caption":

Error: Quote " in attribute name. Probable cause: Matching quote missing somewhere earlier.

[At line 217, column 783](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fblog.tripsoverpoland.pl%2F2023%2F07%2F26%2Fmalbork-15-06-2023-zmiany-wokol-zamku-i-w-panoramie-zza-nogatu%2F#cl217c783)

t":"","camera":"","caption":""

Error: Quote " in attribute name. Probable cause: Matching quote missing somewhere earlier.

[At line 217, column 784](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fblog.tripsoverpoland.pl%2F2023%2F07%2F26%2Fmalbork-15-06-2023-zmiany-wokol-zamku-i-w-panoramie-zza-nogatu%2F#cl217c784)

":"","camera":"","caption":"",

Error: Quote " in attribute name. Probable cause: Matching quote missing somewhere earlier.

[At line 217, column 786](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fblog.tripsoverpoland.pl%2F2023%2F07%2F26%2Fmalbork-15-06-2023-zmiany-wokol-zamku-i-w-panoramie-zza-nogatu%2F#cl217c786)

"","camera":"","caption":"","c

Fatal Error: Too many messages.

https://blog.tripsoverpoland.pl/2023/07/26/malbork-15-06-2023-zmiany-wokol-zamku-i-w-panoramie-zza-nogatu/
 
**or earlier:**

Warning: Attribute aperture":"0","credit":"","camera":"","caption":"","created_timestamp":"0","copyright":"","focal_length":"0","iso":"0","shutter_speed":"0","title":"","orientation":"0"}" is not serializable as XML 1.0.

[From line 209, column 183; to line 211, column 215](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fblog.tripsoverpoland.pl%2F2023%2F07%2F26%2Fmalbork-15-06-2023-zmiany-wokol-zamku-i-w-panoramie-zza-nogatu%2F#l211c215)

age/webp"><img width="120" height="120" src="https://blog.tripsoverpoland.pl/wp-content/uploads/2017/05/17_Mal…orientation":"0"}" data-image-title="Pałac Mała Wieś" data-image-description="<p>Pałac Mała Wieś</p>↩" data-image-caption="<p>Pałac Mała Wieś</p>↩" data-medium-file="https://blog.tripsoverpoland.pl/wp-content/uploads/2017/05/17_Mala_Wies_122-500x…arge-file="https://blog.tripsoverpoland.pl/wp-content/uploads/2017/05/17_Mala_Wies_122-600x413.jpg"></pict

Error: Attribute aperture":"0","credit":"","camera":"","caption":"","created_timestamp":"0","copyright":"","focal_length":"0","iso":"0","shutter_speed":"0","title":"","orientation":"0"}" not allowed on element [img](https://html.spec.whatwg.org/multipage/#the-img-element) at this point.

[From line 209, column 183; to line 211, column 215](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fblog.tripsoverpoland.pl%2F2023%2F07%2F26%2Fmalbork-15-06-2023-zmiany-wokol-zamku-i-w-panoramie-zza-nogatu%2F#l211c215)

age/webp"><img width="120" height="120" src="https://blog.tripsoverpoland.pl/wp-content/uploads/2017/05/17_Mal…orientation":"0"}" data-image-title="Pałac Mała Wieś" data-image-description="<p>Pałac Mała Wieś</p>↩" data-image-caption="<p>Pałac Mała Wieś</p>↩" data-medium-file="https://blog.tripsoverpoland.pl/wp-content/uploads/2017/05/17_Mala_Wies_122-500x…arge-file="https://blog.tripsoverpoland.pl/wp-content/uploads/2017/05/17_Mala_Wies_122-600x413.jpg"></pict

**Comment by tripsoverpoland** [comment]
> > The problem with showing or not exif data in the html code according to the plugin settings does not seem to me to be a request for new functionality, but rather relates to a currently non-working functionality.
> 
> I should have said "enhancement request" rather than "feature request". Sorry.
> 
> But here's the bottom line on that: you can keep arguing here and _not_ have your enhancement request get any attention because there's no GitHub issue to track it, or you can create the enhancement request.

OK I've submitted an issue https://github.com/Automattic/jetpack/issues/32862

**Comment by tripsoverpoland** [comment]
Today I turned off WEBP EXPRESS for a while and checked the page in W3C Validator - I printed the result to PDF, which is available here:
[https://tripsoverpoland.pl/ftp/WEBP_EXPRESS-OFF-NuHtmlChecker.pdf](https://tripsoverpoland.pl/ftp/WEBP_EXPRESS-OFF-NuHtmlChecker.pdf)
Unfortunately without WEBP EXPRESS there are also over 1000 errors/warnings.
It's just that the code generated when creating an entry by WEBP EXPRESS has already remained in this entry. So disabling this plugin doesn't change much in the W3C error picture.

**Comment by anomiex** [comment]
> It's just that the code generated when creating an entry by WEBP EXPRESS has already remained in this entry.

This would seem to invalidate your test. Either you didn't really disable WebP Express, or you need to clear caches somewhere.

**Comment by tripsoverpoland** [comment]
> > It's just that the code generated when creating an entry by WEBP EXPRESS has already remained in this entry.
> 
> This would seem to invalidate your test. Either you didn't really disable WebP Express, or you need to clear caches somewhere.

In fact, I didn't notice and the Litespeed cache was still caching the page. I disabled this plugin as well as WEBP EXPRESS, re-validated W3C - the result is in a new PDF file approx. 3MB smaller., at the same address:
[https://tripsoverpoland.pl/ftp/WEBP_EXPRESS-OFF-NuHtmlChecker.pdf](https://tripsoverpoland.pl/ftp/WEBP_EXPRESS-OFF-NuHtmlChecker.pdf)
I made sure not to cache tags in both the page header and snow there are only 543 lines with errors/warnings.ource code (LS Cache adds a line or two at the end of the code) :-)

**Comment by anomiex** [comment]
I see in your latest pdf that many of the specific errors you were complaining about in this task are no longer present with WebP Express disabled: the "no space between attributes", "quote in attribute name", complaints about bogus attribute names like "aperture", etc. This is because WebP Express, being disabled, is no longer mangling attribute values that Jetpack has generated with correctly encoded `"` characters.

True, there are still some errors relevant to Jetpack's Carousel and/or Tiled Galleries features (e.g. "Duplicate attribute" and "srcset without sizes") and other more generic errors (e.g. "trailing slash"), but those seem better covered under #32818 or in yet-to-be-created subtasks that focus on those issues without the confusion in this task over all the errors caused by WebP Express's mangling of Jetpack's output.

**Comment by tripsoverpoland** [comment]
Thanks for the quick analysis - I let the Author of WEBP Express know to look into this thread (https://github.com/Automattic/jetpack/issues/32819):
[https://wordpress.org/support/topic/errors-and-warnings-from-the-w3c-validator-for-plug-in-generated-code/#post-17030437](https://wordpress.org/support/topic/errors-and-warnings-from-the-w3c-validator-for-plug-in-generated-code/#post-17030437)
PDF with WEBP EXPRESS Enabled:
[https://tripsoverpoland.pl/ftp/WEBP_EXPRESS-ON-NuHtmlChecker.pdf](https://tripsoverpoland.pl/ftp/WEBP_EXPRESS-ON-NuHtmlChecker.pdf)

**Comment by tripsoverpoland** [comment]
UPDATE (June 2026):

It has been nearly three years since this issue was officially reported, and unfortunately, nothing has changed upstream.

I recently contacted Jetpack support regarding this severe performance and architectural bottleneck. They officially confirmed that the option "Show photo EXIF metadata in carousel" does NOT stop the server from processing and injecting thousands of lines of redundant HTML/layout data into the source code – it merely hides it on the front-end using CSS/JS. Support suggested treating this as a backlogged "feature request" with no timeline.

For years, websites with massive image catalogs have been forced to manually patch jetpack-carousel.php after every single update (specifically commenting out the meta_data arrays around line 474 and $attr['data-image-meta'] around line 950) just to keep the DOM size and page weight under control.

We are living in the era of AI. Refactoring these legacy, inefficient structures and moving the carousel_display_exif check upstream would take the engineering team just a few hours using modern LLM development tools. Leaving an optimization bug ignored for nearly three years is a huge oversight for a plugin as massive as Jetpack.

I truly hope the developers will finally clean up this legacy code instead of pushing it down the road indefinitely.
