### ISSUE TITLE
Stats: the smiley face tracking pixel is showing

### ISSUE THREAD

**Issue by formosattic** [Automattic/jetpack#32816]
### Impacted plugin

Jetpack

### Quick summary

Users have reported the stats smiley face showing up again:
* 6732438-zd-a8c
* https://wordpress.org/support/topic/smiley-face-2/

A CSS workaround:

```
img#wpstats{
  display:none
}
```

### Steps to reproduce

Unable to reproduce

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

By default, the smiley option shouldn't show by default. 
https://github.com/Automattic/jetpack/pull/22196

**Comment by jeherve** [comment]
> again

Do you know when the site was first connected to WordPress.com? Do you know if the smiley was ever hidden, or if it was hidden and started appearing again after the site owner took a specific action on the site?

It may be good for them to look into any CSS concatenating options on their site; it may be what's stopping the CSS hiding the smiley from loading.

**Comment by formosattic** [comment]
Thanks @jeherve. 

Closing this as the issue is likely due to CSS concatenating happening.  Else, the smiley can be easily hidden with the CSS workaround (one of the user opted for that).
