### ISSUE TITLE
[Jetpack Search + WPML] - Search shows results from both languages

### ISSUE THREAD

**Issue by diiegopereira** [Automattic/jetpack#32811]
### Impacted plugin

Search

### Quick summary

Hi there, this is Diego from the WPML Compatibility team.

When doing a Jetpack Search on a site with WPML, it will show results for all languages instead of just results in the current language.

We got a report in support for this issue [here](https://wpml.org/forums/topic/wpml-chat-support-ticket-by-manuel-1692000974/).

We checked to see if there is anything we could do on the WPML side, but It seems that the content is indexed on the WordPress servers.

When we search on the site, direct REST requests are made to the WordPress server. To fix this, we would need to have different indexes per language or manage to include a language parameter to the search.

### Steps to reproduce

* Setup WPML
* Setup Jetpack and Jetpack Search
* Create some posts and translate
* Go on front and try a search in both languages
* Both language posts/pages are showing

### A clear and concise description of what you expected to happen.

Show results for current language only.

### What actually happened

Search results for all languages are displayed instead of just results for the current language.

### Impact

Some (< 50%)

### Available workarounds?

No

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by jeherve** [comment]
Thanks for the report. This is currently tracked in #8766.
