### ISSUE TITLE
Voice to Content: implement `jetpack-ai-transcriptions` endpoint

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#32829]
We need to create a backend endpoint to transform the audio into text using the Whisper method from the OpenAI class.

It needs to be reacheable from the frontend. Let's keep using the `jetpack-ai-*` format, and the JWT auth schema. Suggestion: `jetpack-ai-transcription`.

The implementation is similar to the `jetpack-ai-query` and `jetpack-ai-image` endpoints, but will use the `OpenAI::request_audio_transcriptions` method. An example can be found on D132527-code.

---

_Old description:_

https://openai.com/research/whisper

We'll need a few endpoints to send the audio file from the client to the server side (dotcom) and from the server dotcom to the Open AI side, in the similar way we do for AI suggestions.

Whisper [transcription endpoint](https://platform.openai.com/docs/api-reference/audio/createTranscription).

https://platform.openai.com/docs/guides/speech-to-text/speech-to-text

https://platform.openai.com/docs/api-reference/audio

**Comment by retrofox** [comment]
Let's add a `POST` `jetpack/v4` endpoint to upload and process the audio file to dotcom side but in My Jetpack package.

**Comment by tommyshellberg** [comment]
If it helps, I've shipped a diff to add a helper to the OpenAI class (it was mostly written by @retrofox, many thanks! ):

D132527-code

**Comment by lhkowalski** [comment]
Will be closed by D137767-code.

**Comment by lhkowalski** [comment]
Was closed by D137767-code.
