### ISSUE TITLE
Subscribe block: Spaces are automatically removed when editing the button text.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/jetpack#32837]
### Impacted plugin

Jetpack

### Quick summary

When editing the button text to words that contain spaces (eg. `I'm in!`) the experience is frustrating as the space is automatically removed.

### Steps to reproduce

1. launch the editor, FSE or post doesn't matter.
2. insert the Subscribe block.
3. click on the button text.
4. attempt to enter text that has spaces (eg. `I'm in!`).

### A clear and concise description of what you expected to happen.

Button text should reflect what user entered.

### What actually happened

Spaces are automatically removed.

https://github.com/Automattic/jetpack/assets/6549265/c41c02ff-6026-4811-ac98-e8b779b94972

### Impact

All

### Available workarounds?

Yes, easy to implement

**Comment by jeherve** [comment]
I cannot seem to be able to reproduce. I tried with an admin and an editor role account, on WordPress.com Simple and on self-hosted, but the spaces always remain for me.

Does this still happen for you? Do you see this happening in a specific browser?

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**
- Tested on Atomic – **Replicated** 

📌 FINDINGS/SCREENSHOTS/VIDEO

I was able to repro in **Firefox 117.0 (64-bit)**, but not in Chrome:

https://github.com/Automattic/jetpack/assets/27249804/4c7588dc-c5aa-485c-aada-f4a1aa277cfa

https://github.com/Automattic/jetpack/assets/27249804/c5cd433e-2cd0-40f7-9a7f-5e0232a92006

**Comment by worldomonation** [comment]
@jeherve Sorry for late response, it seems @cuemarie narrowed it down to Firefox only - which makes sense, as I only use Firefox. 

Apologies for not noting this fact.

**Comment by gikaragia** [comment]
The issue is still reproducible on Firefox.
