### ISSUE TITLE
Assets: switch to registering scripts with `async` and `defer` attributes introduced in WordPress 6.3

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#32852]
> WordPress 6.3 introduces support for registering scripts with async and defer attributes as part of an enhancement to core’s existing Scripts API. 

Source: https://make.wordpress.org/core/2023/07/14/registering-scripts-with-async-and-defer-attributes-in-wordpress-6-3/

When Jetpack requires WordPress 6.3, we should consider updating our methods in Assets to take advantage of that.

*****

Primary issue: #32865

**Comment by adamsilverstein** [comment]
Thanks for working on this @jeherve - I dropped by to open a similar issue only to discover that you already had it covered! Bravo. Happy to help with review, I'll take a look at the linked issue and feel free to request review on the PR as well!

**Comment by adamsilverstein** [comment]
@jeherve - I started in on this in https://github.com/Automattic/jetpack/pull/34072
I didn't see any use of async, and functions like `add_async_script` actually add the defer attribute.

I tried to keep my change-set as small as possible. In the future it would be good to consider moving deferred scripts using the new approach to the header where they can be discovered earlier.
