### ISSUE TITLE
Code modernization: Replace usage of substr with `str_starts_with` and `str_ends_with`

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#32864]
Source: https://core.trac.wordpress.org/ticket/58220

Let's follow Core's lead once Jetpack requires WordPress 6.3.

Primary issue: #32865

**Comment by anomiex** [comment]
Note we can only do that in contexts that run under WordPress. Code that is intended to be useful outside of WordPress won't have WordPress's polyfill.
