### ISSUE TITLE
Feature Request: Display/Sync Google Calendar events to the tasks calendar

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/jetpack#32935]
### Impacted plugin

CRM

### What

The ability to sync with Google Calendar and display google calendar events in the Task Calendar in Jetpack CRM.

**Comment by dericleeyy** [comment]
Requested by 6781394-zen

**Comment by tbradsha** [comment]
Closing in favor of Automattic/zero-bs-crm#269.
