### ISSUE TITLE
AI Chat block: Configurable prompt

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#32949]
There should be a UX for configuring the prompt. Either as an override or otherwise more "comprehensive" way in wpcom. 

Right now the override is customizable, but only through a filter `jetpack_ai_chat_answer_prompt`. 

See also peGwbA-BB-p2#comment-1111

**Comment by artpi** [comment]
D121589-code
https://github.com/Automattic/jetpack/pull/32994

**Comment by dereksmart** [comment]
merged #32994
