### ISSUE TITLE
AI Chat block: Style and design

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#32945]
It needs to look good: 
- Copy response button 
- Feedback buttons and response field
- Response area in general
- Editor settings panels? 
- Icon/branding?

**Comment by artpi** [comment]
I have chated with Matt Walker about this and he will work on designs.

**Comment by artpi** [comment]
There is more nuance here because if somebody inserts this block on a page with more content, it will be pushing it around - so we need to think about that as well

**Comment by artpi** [comment]
Figma designs:
pdtkmj-1OZ-p2#comment-3330
