### ISSUE TITLE
Debugger: the support request subject string shouldn't be translated

### ISSUE THREAD

**Issue by zinigor** [Automattic/jetpack#3294]
We have introduced a new translated string in 3.9, and it only came to me when I began translating it into Russian that we don't need it. The string is meant to be only read by Happiness Engineers:

https://github.com/Automattic/jetpack/blob/master/class.jetpack-debugger.php#L218

We need to remove the translation function.

**Comment by jeherve** [comment]
Users will see that string as well, when they receive a reply to an email they sent to us via the debug form. I think it should be translated, so email subjects are in the user's language when we reply to them.
