### ISSUE TITLE
AI Chat block: Tracks events

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#32954]
The Block should probably fire off client-side Tracks events.  Note that tracks will only work in the admin area for connected users. 
- Block added 
- Purchase flows
- Customization settings?

**Comment by artpi** [comment]
Arent tracks events for added blocks and purchase flows triggered by default for any block?

**Comment by dereksmart** [comment]
Maybe! It needs to be tested and verified to close the issue.

**Comment by artpi** [comment]
Some tracks added here: D124243-code

**Comment by artpi** [comment]
- [x] Funnels for block inserts confirmed, funnel id 46854

**Comment by artpi** [comment]
- [x] Purchases tracked as well, funnel 46858

**Comment by artpi** [comment]
I think that satisfies the scope of this task. Other funnels are in D124243-code
