### ISSUE TITLE
AI Chat block: Upgrade/purchase prompt

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#32955]
Whether the feature is behind the search plan or has it's own billing, the block should use an upgrade prompt to notify them of the required thing that is needed to use. The upgrade prompt should not show on the front end. 

Similar UX of the following, but imagine "this block requires a _____ plan": 

<img width="665" alt="image" src="https://github.com/Automattic/jetpack/assets/7129409/a0cdbb06-8167-439c-8aa8-2dd9b947176d">

**Comment by artpi** [comment]
No, it cannot be similar, because that UX in AI Assistant is site owner facing.

Our usage will be generated by site visitors, who have no interest nor way to upgrade.

We want to probably alert the site owner that the limit has been reached.

**Comment by dereksmart** [comment]
I updated the description to be more clear that the upgrade prompt should not be shown on the front-end.

**Comment by artpi** [comment]
Ok, there is more checks:
- Jetpack connected
- Search enabled
- Whatever plan we have ?
