### ISSUE TITLE
Map block: private sites show a form to enter map access token.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/jetpack#32991]
### Impacted plugin

Jetpack

### Quick summary

When the site is set to private **(not private post)**, Map blocks show a different input form stating an access token is required. This only happens on AT, and not on Simple private sites.

I searched internally and in closed issues but it does not appear the "why" is not documented anywhere.

### Steps to reproduce

1. set a site to private.
2. start a new post.
3. add the Map block.

### A clear and concise description of what you expected to happen.

Map block asks for the coordinates like with when the site is public.

### What actually happened

Map block requests a token.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by worldomonation** [comment]
![image](https://github.com/Automattic/jetpack/assets/6549265/16c95896-df1a-4c55-bbce-217ed1a4a986)

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to replicate this on a reset AT site, set to Private.

https://github.com/Automattic/jetpack/assets/27249804/ba3c18ad-8235-4a22-b5a6-b3b7ada22273


During testing, I first tried setting up a Map Block while the site was Public, then switching to Private - in this case, the "access token" wasn't needed, and I could continue to set up more Map Blocks. - so this issue appears to only happen when the site is Private the "first" time the map block is set up.

**Comment by jeherve** [comment]
That's interesting. It seems the map provider switches from mapkit back to mapbox when you switch your site to private. cc'ing @Automattic/apex who worked on the Mapkit implementation.

**Comment by TimBroddin** [comment]
I'll look into this!

**Comment by TimBroddin** [comment]
Hmmm, for some reason I'm getting Mapbox as mapping provider in the editor on my Atomic site (both private and public). On the frontend it's Mapkit.

It seems like  `window.Jetpack_Maps?.provider` is no longer set.

**Comment by TimBroddin** [comment]
The same on Simple. It seems something broke the code inserting that.
