### ISSUE TITLE
Sync + HPOS: Update purging logic

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#33016]
### Impacted plugin

Jetpack

### Quick summary

Ensure that the disconnect purging logic on the WP.com side accounts for the new table.

### Steps to reproduce

p1694548518971039-slack-CBG1CP4EN

### Impact

All

### Available workarounds?

There is no user impact

**Comment by mdbitz** [comment]
As a follow-up notes purges are logged in irc to #jetpack-purge which is where I saw the errors.

**Comment by zinigor** [comment]
Thank you, this was fixed in D121812-code
