### ISSUE TITLE
Related Posts Block not available on Atomic and not showing when added on Simple

### ISSUE THREAD

**Issue by janmckell** [Automattic/jetpack#33010]
### Impacted plugin

Jetpack

### Quick summary

The 'Related Posts' Block is only available for Free, Personal and Premium plan (Simple sites) and when it's added, no related posts content is showing on the front end. It is not an option on Atomic sites.

### Steps to reproduce

Atomic:
I went to Appearance → Editor → Templates → Single Posts
I tried to add a Related Posts Block after the 'Content' block and it is not available. Only the 'Related Products' Block shows up.

![Markup on 2023-09-12 at 12:31:22 PM](https://github.com/Automattic/jetpack/assets/84089207/26106e81-6a07-4f6c-b9f2-e6d887b24684)

Simple:
I went to Appearance → Editor → Templates → Single Posts
I tried to add a Related Posts Block after the 'Content' block and it is available. 
I add it, but it is not showing any content on the front end and in the Editor, says 'Preview unavailable in site editor'

![Markup on 2023-09-12 at 12:31:01 PM](https://github.com/Automattic/jetpack/assets/84089207/78f4f240-f3ca-44ed-b781-117ade71ac42)

I tested this with the Jetpack 'Related Posts' setting toggled on as well as off. The same happens regardless.

![Markup on 2023-09-12 at 12:31:53 PM](https://github.com/Automattic/jetpack/assets/84089207/e7ea0a4f-7786-40be-af8a-9456be577de0)

### A clear and concise description of what you expected to happen.

I expect to be able to add the 'Related Posts' Block regardless of the plan on my site. Instead, I can only add it on Free, Personal and Premium and when I do, it doesn't work on the front end.

### What actually happened

The 'Related Posts' Block is only available for Free, Personal and Premium plan (Simple sites) and when it's added, no related posts content is showing on the front end.  It is not an option on Atomic sites.

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by cuemarie** [comment]
Hey @janmckell ! Ran a quick triage test on this, and wasn't able to replicate quite the same - I have a couple follow up questions!

- On your Simple Test site, does your site meet the requirements noted here? https://wordpress.com/support/related-posts/#requirements 
     - if your site does not meet these requirements, then the related posts will not appear on the site's front end, and the basic block will appear on the template itself.
- On my Atomic Site, I'm able to add the Related Posts block as expected. Could you share the blog ID of your test site, so I can take a look at your site and check for differences between our tests?  Thanks!

**Comment by janmckell** [comment]
Sure thing, I can answer these. Thank you for taking a deeper look.

**My Atomic test site blog ids are:**
202901042
202991132

**My Simple site blog ids are:**
202980216 - is Public, has posts with more than 100 words, and not using a theme with a related posts feature - is using Appleton - does not show here, although available in the Editor, when added to the Simple Post template
202990564 - is Public, has posts with more than 100 words, and not using a theme with a related posts feature - is using Creatio - does not show here, although available in the Editor, when added to the Simple Post template

**I tested at least one free site:**
https://wordpress.com/home/freedomfido.wordpress.com - it works here

**Comment by janmckell** [comment]
I should mention. This is the interaction that prompted further testing:

6805768-zd-a8c

**Comment by jeherve** [comment]
@janmckell None of your test sites have more than 10 posts. When you have little content, chances are that no related posts can be found just yet. I would recommend that you publish more posts.

On the site reported in 6805768-zen we definitely have more than 10 posts though. The Related Posts module isn't enabled on the site at the moment so I cannot test everything, but at a first glance I do not see anything that would stop the related posts from appearing. There are enough posts in the search index. 
Could they try to turn on the module once again, under Jetpack > Settings > Traffic on their site, and then see if something changes?

**Comment by janmckell** [comment]
@jeherve I had tested these scenarios when I first interacted with the customer and then afterward, again, while testing it on theirs and my test sites. The customer had given permission to test this, since it wasn't working anyway.

1. Related Post setting on, add Related Posts Block via Single Posts template, not available for adding.
2. Related Post setting on, looked for this in posts on the front end, without it being set inside a template, not showing.
3. Related Post setting off, add Related Posts Block via Single Posts template, not available for adding.

**Comment by janmckell** [comment]
@jeherve Note: The requirement of having more than 10 posts is not listed here in 'Requirements':
https://wordpress.com/support/related-posts/#requirements

**Comment by jeherve** [comment]
Any chance you could enable the module again on the site, so we can see if related posts can be found for each post?

> The requirement of having more than 10 posts is not listed here in 'Requirements'

It isn't, no. You will be able to toggle the feature on and off even if you do not have enough posts yet. But for related posts to appear below your posts, you will need content, so we can find content on a site.

**Comment by janmckell** [comment]
@jeherve Okay, sure, I've just enabled 'Related Posts' on their site at Settings → Reading on their site, and I've let them know that it is enabled, for now, for testing and we will share any further updates with them.

**Comment by jeherve** [comment]
Excellent, thank you!
I can see we return related posts for some of their posts, so that part is wired properly 👍

Here is an example with their latest posts:

<img width="858" alt="Screenshot 2023-09-13 at 15 08 06" src="https://github.com/Automattic/jetpack/assets/426388/f91c04f1-0a3a-4de3-8c25-414b476c2418">

Now you should find a Related Posts block when going to Appearance > Site Editor and editing a template like the Single Posts template. If you do not see the Related Posts block, could you paste the following in your browser's JavaScript console and let me know the output:

`Jetpack_Editor_Initial_State.available_blocks['related-posts']`

https://github.com/Automattic/jetpack/assets/426388/73182bc5-30f5-4242-993a-9a95426e7336

Could you give that a try and let me know what you see?

Thank you!

**Comment by janmckell** [comment]
@jeherve I can give that a try, but have to ask about something first. Upon checking the users site to run the test, I noticed that they installed and activated a plugin, '[Related Posts for WordPress] related-posts-for-wp last evening at 7:41pm (UTC -4) ~ Sep 11.

How will this impact the current test, and how has it impacted what you've already tested?

**Comment by jeherve** [comment]
It will not have any impact, since that's a completely different plugin, and that plugin doesn't interact with Jetpack in any way. 👍

**Comment by janmckell** [comment]
Thanks @jeherve  
It didn't show. I still only see 'Related Products' when I search or type in '/related'.

![Markup on 2023-09-13 at 9:08:22 AM](https://github.com/Automattic/jetpack/assets/84089207/4be8afe6-4cb7-4c33-87bb-3321e0b3b7e1)

**Comment by jeherve** [comment]
@janmckell It looks like the module is still deactivated right now. When you have some time, could we sync up on Slack and debug this together?

**Comment by janmckell** [comment]
@jeherve I didn't realise that you were talking about the Related Posts module in Jetpack, as I wasn't aware that there was a module to turn on or off for it in Jetpack Modules. I thought you'd been referring to the setting at Settings → Reading. I've enabled the Jetpack module, and now I see 'Related Posts' as an available Block in their Editor.

![Markup on 2023-09-14 at 7:20:52 AM](https://github.com/Automattic/jetpack/assets/84089207/dabfdab3-f230-4224-932f-a3be42b0bcf4)
![Markup on 2023-09-14 at 7:21:47 AM](https://github.com/Automattic/jetpack/assets/84089207/f6f21c5e-d642-4623-853d-0a6300ca10bd)

If this is what you meant, we may not need to meet on Slack, and I can update the customer about it. Thank you for walking this through.

**Comment by jeherve** [comment]
Good news!

You'll also be happy to hear that this is going to be a lot less confusing very soon as we're about to ship some improvements to the Related Posts Block to avoid that confusion: #32930
