### ISSUE TITLE
Related Posts block: WordPress.com eCommerce plan users do not have access to the block.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/jetpack#33062]
### Impacted plugin

Jetpack

### Quick summary

Related Posts block is not available for those on WordPress.com eCommerce plans. 

This block is available to those on WordPress.com Business plans, pre- or post-AT.

### Steps to reproduce

1. set up an eCommerce-plan site.
2. start a new post.
3. look for the `Related Posts` block.

### A clear and concise description of what you expected to happen.

The block is available.

### What actually happened

Block is not available.

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic

**Comment by jeherve** [comment]
The block was available while testing on a site using wpcom eCommerce on my end. Could you let me know if the Related Posts feature was active on that site (see Jetpack > Settings > Traffic)?

**Comment by worldomonation** [comment]
Voilà! It is available now, thanks for the heads up! I'll note this in in our codebase.

**Comment by jeherve** [comment]
Excellent! Another bit of good news: we'll soon improve UX there, by always displaying the block, even when the module is deactivated. The block will have an additional placeholder state with a button one can click to enable the module:

#32930
