### ISSUE TITLE
Subscribe Block: Infinite loading spinner when email token is invalid

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/jetpack#33107]
### Impacted plugin

Jetpack

### Quick summary

When you provide an invalid token such as `sometext@t` in the subscribe field, the confirmation modal for subscription never appears and the page is stuck infinitely on with loading spinner. I could also spot the 500 error in the Network tab in the browser:

<img width="1220" alt="Screenshot 2023-09-15 at 2 27 07 PM" src="https://github.com/Automattic/jetpack/assets/25575134/cf5d67aa-f2f9-40f0-b885-aea857799547">

### Steps to reproduce

1. Open a post or page editor to add `Subscribe` block
2. Add `Subscribe` block to either a Simple or Atomic site
3. Publish your page or post
4. Navigate to the page as if you were a user
5. Type an invalid email address such as `kk@k`
6. Click `Subscribe`
7. Observe that the page is stuck in an infinite loading state

https://github.com/Automattic/jetpack/assets/25575134/b940e490-9ccd-4679-9152-34d3f5a39171

### A clear and concise description of what you expected to happen.

I expected to either have an error message appearing when I clicked on `Subscribe` button or to have a similar token validation to when you would type something like `k`:

<img width="841" alt="Screenshot 2023-09-15 at 2 32 53 PM" src="https://github.com/Automattic/jetpack/assets/25575134/2f4648eb-50b3-4a5b-ad20-f8c32a28a0d0">

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by simison** [comment]
This now passes without error, but since the email wouldn't be valid email they would never be able to confirm it.

We use the browser's own email input validation for validating emails, and I don't think it's worth sending more JS to the clientside to do our custom validation for an edge cases like these.
