### ISSUE TITLE
Sitemaps: for larger sites, adopt approaches from msm-sitemap to scale sitemap building

### ISSUE THREAD

**Issue by ethitter** [Automattic/jetpack#3314]
The current Sitemaps implementation works for most sites, but for large sites, content will either be missing (only the latest 1,000 published entries in supported content types are included) or the process will fail before it completes. Automattic's [msm-sitemap](https://github.com/Automattic/msm-sitemap) plugin, designed for large WordPress.com VIP sites, offers one solution to these scaling issues and may provide useful approaches for supporting larger sites in Jetpack.

**Comment by jeherve** [comment]
Fixed in #5503, although it would be nice to do some additional testing on very large sites, so we can use Jetpack Sitemaps on VIP Go as well.

Continued discussion here: p6jPRI-ST-p2
