### ISSUE TITLE
VideoPress: Dashboard unresponsive when navigating to second page or searching

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#33159]
This report came from a user interview, so there's not a lot of details

The console shows an error. This error appears immediately after a failed request to `GET /wp-json/wp/v2/media` coming back with a `401` status

```
Cannot read properties of undefined (reading 'map')
at index
at async
```

![image](https://github.com/Automattic/jetpack/assets/746152/af66f970-bb9c-426b-909d-8ebd77e411f9)

**Comment by oskosk** [comment]
Must be related to user role

**Comment by CGastrell** [comment]
> Must be related to user role

Unlikely, only admins allowed on that section. But I will try with a second admin and see what happens

**Comment by oskosk** [comment]
Can’t repro anymore
