### ISSUE TITLE
Likes: make plugin available in editor, even when the module is not active yet

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#33163]
See Primary issue: #32401

**Comment by andrii-lysenko** [comment]
So both, Likes and Sharing are lying under one tab. They are both controlled by separate modules. How do we want to tackle them. Should we show only one button, or should it be separate for each module? @jeherve what do you think?

<img width="279" alt="Screenshot 2023-09-21 at 12 43 31" src="https://github.com/Automattic/jetpack/assets/60262784/19050e6b-5821-4587-be0d-9abec3f8e409">

**Comment by jeherve** [comment]
That's a good question. Would it be too confusing to have 2 buttons, one to enable each module? I think it could work.

**Comment by andrii-lysenko** [comment]
@jeherve yes, I think having 2 separate buttons is a way to go. I will add both, following the same pattern as we did with other modules. I assume though, that this would look a bit bulky, so we could iterate on the design in the future. Maybe like having `Activate plugin` and `Info` link in a single like.
