### ISSUE TITLE
Lazy images: deprecate from Jetpack Boost

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#33170]
WordPress 6.4, scheduled to be released on November 7, 2023, will start conflicting with our Lazy Images functionality. Let's aim to have it removed from the Boost plugin by then.

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/jetpack/issues/33953
- [x] Remove the feature from Boost UI
```

*********

Primary issue: #33048 
Related issue for the Jetpack plugin: #33049

**Comment by jeherve** [comment]
cc @haqadn Leaving that one to you :) Feel free to ping me for any coordination with the Jetpack plugin!

**Comment by haqadn** [comment]
Thanks for creating the issue. @ederrengifo is helping us remove the feature while not leaving the users at a state of confusion.

**Comment by jeherve** [comment]
Noting that in #33208, I'm poking at some of Boost' internals to address some of that confusion. I'll be happy to have your opinion on this!

**Comment by ederrengifo** [comment]
Explored designs for the notifications to show and an idea for emailing `p1HpG7-oTQ`

**Comment by ChrisBegley** [comment]
Hello, the Tiled Gallery block doesn't currently support native Lazy Loading: https://github.com/Automattic/jetpack/issues/33247

Without the Lazy Loading feature of Jetpack, there won't be any way to lazy load Tiled Galleries. That'll add a lot of "weight" to pages with galleries.

**Comment by jeherve** [comment]
> Without the Lazy Loading feature of Jetpack, there won't be any way to lazy load Tiled Galleries. That'll add a lot of "weight" to pages with galleries.

That's correct. However, we must still proceed with deprecating Jetpack's Lazy Images implementation, as it conflicts with some recent changes in the Gutenberg plugin, that will come to WordPress in version 6.4, scheduled for next month.

#32598 already improved the performance of tiled galleries. Adding native lazy loading should help too, and we'll close #33247 when that's implemented.

**Comment by haqadn** [comment]
Closing the issue as this is now complete
