### ISSUE TITLE
Jetpack: Cannot purchase VideoPress upgrade

### ISSUE THREAD

**Issue by anomiex** [Automattic/jetpack#33222]
### Impacted plugin

Jetpack

### Quick summary

Trying to purchase the VideoPress upgrade via My Jetpack never offers a way to purchase.

### Steps to reproduce

With Jetpack-the-plugin installed and connected but not the VideoPress standalone,

1. Go to My Jetpack.
2. Click "Manage" on the VideoPress card. This opens Jetpack's Settings screen.
3. Click "Upgrade" in the settings to try to buy more videos and 1TB of storage. This brings me to a page at `/wp-admin/admin.php?page=my-jetpack#/add-videopress` prompting to install VideoPress.
4. Click "Install Jetpack VideoPress". This brings me back to My Jetpack without ever giving an option to purchase the upgrade.

### A clear and concise description of what you expected to happen.

The "Install Jetpack VideoPress" would do that and then go to an order screen.

### What actually happened

I wind up back at My Jetpack without ever being able to purchase.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

Manually installing the standalone VideoPress plugin (e.g. using the ⋮ button in My Jetpack or using the Plugins page) partially fixes things, as at step 2 it goes to VideoPress's page instead of Jetpack's settings.

If I start from Jetpack's settings screen, that Upgrade button still goes to the "Install Jetpack VideoPress" page (even though VideoPress is definitely installed!), which goes back to My Jetpack. But then the Manage button there goes to VideoPress's page where I can buy the upgrade, so it's a bit of a confusing runaround but eventually works.

**Comment by anomiex** [comment]
It's possible this is similar to #31653.

**Comment by jeherve** [comment]
Also in #33409

**Comment by CGastrell** [comment]
Reopen as #33410 had to be reverted
