### ISSUE TITLE
Remove translations from plugin

### ISSUE THREAD

**Issue by grappler** [Automattic/jetpack#3322]
As plugin language packs are released can the language files be removed as they are nearly 6 MB?

**Comment by jeherve** [comment]
We do remove all language files for languages that are fully translated (the list is available [here](https://github.com/Automattic/jetpack/blob/3.9.0/tools/export-translations.php#L11)):
https://plugins.svn.wordpress.org/jetpack/tags/3.9.0/languages/

We must leave the other language files in place though, as a language pack only becomes available once the plugin is fully translated into that language.

I hope this clarifies things a bit!

**Comment by grappler** [comment]
Ah, thanks for explaining it :smile:
