### ISSUE TITLE
Admin Menu: focus does not match when My Jetpack is not displayed

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#33243]
### Impacted plugin

Jetpack

### Quick summary

Our logic to set focus on the Jetpack Dashboard submenu items does not take into account situations where "My Jetpack" may not be available: (ie.- when Multisite)
https://github.com/Automattic/jetpack/blob/a33dd9ffaf813ef0dea07b17e06a9390b2f44fef/projects/plugins/jetpack/_inc/client/main.jsx#L954

### Steps to reproduce

You must have a site that's part of a Multisite network to reproduce this. On such sites, the "My Jetpack" link is not displayed.

https://github.com/Automattic/jetpack/blob/b0c967a9b1a6a3461def0148512e461a69e6f042/projects/packages/my-jetpack/src/class-initializer.php#L266-L268

1. Go to Jetpack > Dashboard

### A clear and concise description of what you expected to happen.

Look at the navigation menu:

<img width="1362" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/286f1d00-efe9-44c7-842c-542359ae17a0">

### What actually happened

Although I'm on `wp-admin/admin.php?page=jetpack#/dashboard`, the menu focusses on "Settings". If I click on Settings, the focus will be on "Subscribers":

<img width="1340" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/bb7afa32-1aa5-4996-b965-ca7e04ce11b7">

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by jeherve** [comment]
cc @elliottprogrammer who worked on #32385.

**Comment by elliottprogrammer** [comment]
Thanks @jeherve I've added this to the Jetpack Martech Maintenance board, priority: high. 👍
