### ISSUE TITLE
AI Chat block: Button text overflows the button background.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/jetpack#33242]
### Impacted plugin

Jetpack

### Quick summary

When more than 3-4 characters are present in the button for the AI Chat block, the text visually overflows from the button background.

Example page: https://e2eflowtesting1678738625684240896.blog/2023/09/20/version-12-6-6240849897-g0eae74ad/

<img width="740" alt="image" src="https://github.com/Automattic/jetpack/assets/6549265/12fa423d-3d63-458b-9a92-b2d6a2ec5847">

### Steps to reproduce

1. start a new post.
2. insert the AI Chat block.
3. click on the button to edit the text.
4. insert longer text (eg. Ask me anything).
5. publish and view the post.

### A clear and concise description of what you expected to happen.

The button text should not overflow.

### What actually happened

Button text overflows from the button height.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by jeherve** [comment]
The block is still being developed and marked as experimental, so this may happen. More styling improvements will happen in the next releases. I expect the button may actually be switched to a Jetpack Button block so we can get all the customization options without too much work.

cc @dereksmart

**Comment by artpi** [comment]
I was sure I fixed this in https://github.com/Automattic/jetpack/pull/33178 :( 
Uhh this button

**Comment by dereksmart** [comment]
This was solved #33516
