### ISSUE TITLE
In SSO "what info is being shared" there is no value when Two-Factor is disabled.

### ISSUE THREAD

**Issue by georgestephanis** [Automattic/jetpack#3325]
It looks like this:

![screen shot 2016-01-20 at 10 40 49 am](https://cloud.githubusercontent.com/assets/426388/12485679/a897f72a-c05f-11e5-8983-48ddd3633c22.png)

and without a "No" or some entry below it, it looks like it's falsely indicating that Two-Factor is turned on.

**Comment by kraftbj** [comment]
When it is enabled, it isn't much better:
<img width="174" alt="screen shot 2016-02-02 at 10 37 28" src="https://cloud.githubusercontent.com/assets/88897/12756357/055540f2-c999-11e5-96b4-1aff3bfd2f14.png">

Proposed patch in D986-code .

**Comment by kraftbj** [comment]
@ebinnion - Can you take a look at the wp.com diff when you get a chance. Should be easy to knock this one out.

**Comment by ebinnion** [comment]
This should be fixed in r136706-wpcom.
