### ISSUE TITLE
"Learn More" link is giving 404 in offline development mode

### ISSUE THREAD

**Issue by i-am-chitti** [Automattic/jetpack#33275]
### Impacted plugin

Jetpack

### Quick summary

In local development offline mode, the 'Learn More' link in respective notice under `Setting` page is directing to a 404 page.

Here it's highlighted in red border.

![Screenshot 2023-09-25 at 1](https://github.com/Automattic/jetpack/assets/60139930/e91794d7-267e-406f-ae7e-fbba8a9e8c6c)

This is the link it's directing to - https://jetpack.com/redirect/?source=jetpack-support-development-mode&site=mydev-manager.local

### Steps to reproduce

1. Start a WordPress site in local development mode. I'm using WP Local by Flywheel.
2. Install Jetpack
3. Visit `Settings`. 
4. Look for admin notice on top saying "Currently in [Offline Mode](https://jetpack.com/redirect/?source=jetpack-support-development-mode&site=mydev-manager.local) (some features are disabled) because:"

### A clear and concise description of what you expected to happen.

It should direct the user to a valid page

### What actually happened

Got 404 page.

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by jeherve** [comment]
Thank you for the report! This should now be fixed!
