### ISSUE TITLE
Block registration: Directory separator bug on Windows servers

### ISSUE THREAD

**Issue by timotheemoulin** [Automattic/jetpack#33331]
https://github.com/Automattic/jetpack/blob/24863620a13bdfb323a49d6a203010d69dd75d0b/projects/packages/blocks/src/class-blocks.php#L46

This line fails to detect the right namespace on a Windows hosting.
Directory separators are `\` instead of the hardcoded `/`.

We should change this condition to be OS agnostic.

```php
if ( 0 !== strpos( $slug, 'jetpack/' ) && 0 !== strpos( $slug, '/' ) && ! strpos( $slug, '/' ) ) {
```
should be
```php
if ( ! preg_match('#.*jetpack[\/].*#', $slug) && 0 !== strpos( $slug, '/' ) && ! strpos( $slug, '/' ) ) {
```

Moreover not every Jetpack block use the `jetpack/` prefix. Business Hours block use the full path to the block directory and not just a prefix. (Which btw also triggers another error when the path contains uppercase like in `C:\www\my-project\...`).
```php
function register_block() {
	Blocks::jetpack_register_block(
		__DIR__,
		array(
			'render_callback' => __NAMESPACE__ . '\render',
		)
	);
}
```
So we should allow the prefix to not "begin with" jetpack, but only contain it.
```[tasklist]
### Tasks
```

**Comment by anomiex** [comment]
I have a feeling you're looking at the wrong part of that condition. The part you're trying to change is not looking at paths at all, it's looking at the block's name.

Was the real problem you had already fixed by https://github.com/Automattic/jetpack/pull/33318?

> Moreover not every Jetpack block use the jetpack/ prefix.

It does: https://github.com/Automattic/jetpack/blob/bb885061dc3ee7a80a78a5f0116ab3fcebfddb09/projects/plugins/jetpack/extensions/blocks/business-hours/block.json#L4

**Comment by timotheemoulin** [comment]
I'll have a deeper look at the pull request regarding the Windows path.

For the prefix issue. The PHP code I referred to does use the full path instead of the prefix. This is the one that triggers the error.

**Comment by anomiex** [comment]
Yes, the registration call from the business-hours block does pass a path. In that case the name and other data are read from the block.json file at that path.

#33318 fixed a problem where Windows paths were not being recognized as such by the checks that are looking for absolute paths. You are instead focusing on code that's supposed to check a prefix on a block name, thinking it's supposed to be doing anything at all with a path beyond determining "nope, not a block name with the jetpack/ prefix".

**Comment by jeherve** [comment]
@timotheemoulin Let us know if the problem persists for you after https://github.com/Automattic/jetpack/pull/33318.

**Comment by jeherve** [comment]
Closing this now since the problem should now be fixed.
