### ISSUE TITLE
Sitemaps: use Jetpack_PostImages for regular sitemaps as well

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3333]
In 57571c1818a64478459c747063991038db95a2a8, we started using `Jetpack_PostImages` to look for an image to be used in the News sitemap.

I think we should follow the same method for regular sitemaps as well, instead of relying on code that ignores all images that aren't attached to the post:
https://github.com/Automattic/jetpack/blob/3.9.1/modules/sitemaps/sitemaps.php#L284

Reported here:
https://wordpress.org/support/topic/sitemap-and-featured-image?replies=1&view=all

**Comment by richardmtl** [comment]
another report in 2520507-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/jetpack-sitemapxml-featured-image-boolean-incorrect?replies=1&view=all
