### ISSUE TITLE
Beta block: setting block title suffix bug in the site editor context

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#33346]
There is an issue when the app extends the beta blocks to add the ` (beta)` suffix and the `beta` keyword:

* Use a Jetpack testing site (JN, for instance)
* Connect the site
* Enable `beta` extensions
* Go to the site editor 

<img src="https://github.com/Automattic/jetpack/assets/77539/5e6424e9-1cd9-41b1-aae4-dcb16fdd61b1" width="300px" />

* Open the console dev tool
* There is an error when the app tries to set the title suffix 

<img src="https://github.com/Automattic/jetpack/assets/77539/d01459c8-9362-4f14-a843-cf131863ad46" width="800px" />

For some reason, some blocks don't have defined their title—for instance, the AI Chat block.

**Comment by retrofox** [comment]
threads

p1695826562812239-slack-CBG1CP4EN
p1695770860268139-slack-CDLH4C1UZ
p1695780240881509/1695664978.633309-slack-CBTN58FTJ

**Comment by jeherve** [comment]
This should be fixed as of #33350.
