### ISSUE TITLE
AI Assistant Feedback feature does not show upgrade path

### ISSUE THREAD

**Issue by pehaa** [Automattic/jetpack#33378]
### Impacted plugin

Jetpack

### Quick summary

When the free usage limit is reached, the AI Assistant Feedback does not show any notification. It only shows recently generated feedback.

### Steps to reproduce

1. Ask AI Assistant for feedback (Jetpack sidebar) multiple times to exceed the free usage limit.
![Annotation on 2023-09-28 at 13-53-03](https://github.com/Automattic/jetpack/assets/774920/a286e242-6019-4a32-b678-33ddda4a9560)
times

### A clear and concise description of what you expected to happen.

You should see the `Congratulations on exploring Jetpack AI and reaching the free requests limit! Upgrade now to keep using it.` notice

### What actually happened

Feedback stops being regenerated without any notice.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by pehaa** [comment]
Note that when the page is saved and reloaded the AI Assistant shows: `You have reached the limit of 20 free requests. Upgrade to continue generating feedback.`  and the Generate button is disabled 👍 

![Markup on 2023-09-28 at 14:40:13](https://github.com/Automattic/jetpack/assets/774920/cbfdd34d-a547-4ef0-9b48-53595c5b1280)

**Comment by renatoagds** [comment]
Closed it, since we already have it with usage bar.
