### ISSUE TITLE
"Notify me of follow-up comments by email" produces PHP Warning

### ISSUE THREAD

**Issue by cfinke** [Automattic/jetpack#3339]
Checking the "Notify me of follow-up comments by email" checkbox when commenting produces a PHP Warning on the next pageload:

```Notice: Trying to get property of non-object in [...]/wp-content/plugins/jetpack/modules/subscriptions.php on line 730```

Running Jetpack 3.9.1, WP 4.4.1. Happy to provide any additional debugging information that you need.

**Comment by kraftbj** [comment]
Line in question: https://github.com/Automattic/jetpack/blob/master/modules/subscriptions.php#L730

Looks like we're calling the global `$post`, but probably not set based on the error.

**Comment by cfinke** [comment]
Reporting that this bug still exists in 4.2.1.

**Comment by salmankamran** [comment]
http://www.infobag.in/c-programs-examples/

**Comment by MeganGregory** [comment]
Hi, this article is very good to read I found easier. It seems like you resolve the issue successfully.
I am waiting to read your next article. Download the plunging part I easily done. Whereas with the 
there is no way for users to know if someone replied to their comment on  <a href="https://mightyessays.com/">Wordpress website </a>
Try to write an article about this issue and also to notify users only on replies  to their Wordpress comment?

**Comment by abidhahmed** [comment]
@MeganGregory ~ if you're experiencing a problem similar to what's reported here, please elaborate it so we can figure out what's happening. Alternatively, you can file a new issue and we'll help take a look.

Thanks!
