### ISSUE TITLE
Upgrade path goes in circles

### ISSUE THREAD

**Issue by CGastrell** [Automattic/jetpack#33409]
Ref: p1694186109802399-slack-C03TA48NSUX

Basically:

- My Jetpack -> VideoPress (active, plugin not installed) -> Manage
- Jetpack Settings @ Performance -> Media (VideoPress active, used freeupload) -> Upgrade
- VideoPress promo/CTA -> Install Jetpack VideoPress
- Back at My Jetpack, VideoPress active, plugin not installed

**Comment by anomiex** [comment]
Same as #33222?

**Comment by CGastrell** [comment]
> Same as #33222?

Apparently so
