### ISSUE TITLE
Boost: Update dismissed score prompt to use dismissed alerts data store

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#33402]
Use Dismissed Alerts DS introduced in #33133.

**Comment by haqadn** [comment]
It may no longer be relevent after the React migration. If you see this ticket after the migration has completed, see if the alert is using the react-data-sync library to achieve this.

**Comment by thingalon** [comment]
We're late in the React migration. Time to check if this is resolved. :)
