### ISSUE TITLE
VideoPress block: videos not displayed on classic and hybrid themes on blog homepages

### ISSUE THREAD

**Issue by jartes** [Automattic/jetpack#33417]
### Impacted plugin

Jetpack

### Quick summary

When a VideoPress block is added to a post, and the homepage is set to display the latest posts, the video is not displayed (the site should be displaying all the post content). This is happening with Hibryd and Classic themes like "Independent Publisher 2" or "Balasana".

Interestingly, this is only happening on the front page, but not on archives or pagination pages. And also, this only happens when the video is not the first post in the list.

### Steps to reproduce

1. Create a new post, and add a VideoPress block. Publish it.
2. Publish another post with any content on it.
3. Use a Hybrid or Classic theme, like "Independent Publisher 2" or "Balasana".
4. Set "Your latest posts" on the "Homepage Settings" from the Customizer. 
6. Check the home page. 

### A clear and concise description of what you expected to happen.

We should see the post listed on the site homepage with the video on it.

### What actually happened

The video is not there in the post, and the HTML code from the block is stripped. 

### Impact

Some (< 50%)

### Available workarounds?

Yes, transforming the VideoPress block in to a Video block from the editor.

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Chat: 7090266-zd-a8c
Follow-up: 7090403-zd-a8c

**Comment by CGastrell** [comment]
This should be fixed since #33701 was fixed. Confirm?

**Comment by monsieur-z** [comment]
Confirming I was no longer able to reproduce the issue following the above steps.
