### ISSUE TITLE
Image block: media library only appears on the 10th click.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/jetpack#33444]
### Spec file

specs/blocks/blocks__media.ts

### TeamCity ID

10915858

### Logs

```
======= Failed test run Automattic/wp-calypso#1 ==========
  frame.setInputFiles: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for locator('input[type="file"][multiple]')
  ============================================================
  at ImageBlock.uploadThroughMediaLibrary (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/blocks/image-block.ts:92:3)
      at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/blocks/blocks__media.ts:100:4)
======= Failed test run Automattic/wp-calypso#2 ==========
  frame.setInputFiles: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for locator('input[type="file"][multiple]')
  ============================================================
  at ImageBlock.uploadThroughMediaLibrary (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/blocks/image-block.ts:92:3)
      at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/blocks/blocks__media.ts:100:4)
```

https://github.com/Automattic/wp-calypso/issues/80730

**Comment by worldomonation** [comment]
![image](https://github.com/Automattic/wp-calypso/assets/6549265/eebe1737-3c45-4a69-a549-ac8a1965deef)

**Comment by worldomonation** [comment]
Recording important investigation data here (copied from Slack thread p1696309647951369-slack-C01U2KGS2PQ):

- this fails on both Simple and AT sites running pre-release Jetpack;
- this does not fail on production Jetpack+WPCOM+Calypso.
- this particular test started failing on the September 30, 2023 run of the Jetapck Simple E2E tests.
- this failure occurs on both Desktop and Mobile viewports.

**Comment by worldomonation** [comment]
The Calypso media gallery only appears on the 10th click. Verified in the video below.

https://github.com/Automattic/wp-calypso/assets/6549265/a48390a6-6ad4-419f-b6ff-8dacecd9ff29

**Comment by jeherve** [comment]
This should be fixed with this change:
https://github.com/Automattic/jetpack/pull/33431

**Comment by worldomonation** [comment]
Thanks @jeherve! I'll close this issue once I confirm the E2Es pass again.

**Comment by worldomonation** [comment]
Looks to be passing now with Jetpack 12.7-a.5.

![image](https://github.com/Automattic/jetpack/assets/6549265/13f9de0e-48f7-4cf3-aba3-a6ba60b47330)
