### ISSUE TITLE
Theme Tools: Not available/don't work when Jetpack is disconnected

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#3345]
The site logo feature in Jetpack doesn't work when Jetpack is fully disconnected, but does work when development mode is enabled. It seems that this is one of the features that should work regardless.

Here are a couple of screenshots to illustrate.

Jetpack Connected:
![screen shot on 2016-01-26 at 10-46-07](https://cloud.githubusercontent.com/assets/831377/12585869/e69e165c-c41b-11e5-97a6-cdd9caecd2d8.png)

Jetpack Disconnected:
![screen shot on 2016-01-26 at 10-46-38](https://cloud.githubusercontent.com/assets/831377/12585884/f61e7f90-c41b-11e5-84a9-6444940ad83c.png)

**Comment by philiparthurmoore** [comment]
Related: https://github.com/Automattic/jetpack/issues/3269.

**Comment by jeherve** [comment]
This seems to apply to all theme tools. I think they should be available whether you're connected to WordPress.com or not. Unfortunately, Jetpack has to be connected for the file to load at the moment:
https://github.com/Automattic/jetpack/blob/3.9.1/class.jetpack.php#L1731

**Comment by kraftbj** [comment]
FTR: Site Logo is now in Core.

**Comment by jeherve** [comment]
Closing this as this was fixed.
