### ISSUE TITLE
Contact Form: avoid conflicts when using the old version of the Contact Form feature

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#33464]
This is a follow-up to #33050.

Right now, the contact form feature is loaded from the Contact Form package by default:
https://github.com/Automattic/jetpack/blob/0173104f84c1c325fdfeeef6afc664a3baea9390/projects/plugins/jetpack/modules/contact-form.php#L23-L36

Some site owners may decide to continue to load the contact form feature from the old codebase instead:

```php
add_filter( 'jetpack_contact_form_use_package', '__return_false' );
```

When you do so, you run into issues with how the blocks are registered, as discussed in  p1696362451002639-slack-CDD9LQRSN

Related Epic: #32401 

**********

Related Epic: the old form code will eventually be removed in #30551

**Comment by chrisbliss18** [comment]
Could we ask the reporter of this issue why they are using the old version? Maybe we can help them fix their specific issue so that it is no longer a conflict.

It would be nice to trigger a [_doing_it_wrong()](https://developer.wordpress.org/reference/functions/_doing_it_wrong/) warning to indicate that this is deprecated functionality and will be removed in a future version.

**Comment by jeherve** [comment]
> Could we ask the reporter of this issue why they are using the old version? Maybe we can help them fix their specific issue so that it is no longer a conflict.

Discussion is happening here:
p1697469538876579/1696362451.002639-slack-CDD9LQRSN

It seems it may not be an issue anymore. 👍

> It would be nice to trigger a [_doing_it_wrong()](https://developer.wordpress.org/reference/functions/_doing_it_wrong/) warning to indicate that this is deprecated functionality and will be removed in a future version.

The work behind the deprecation is currently tracked in #30551.

**Comment by jeherve** [comment]
> It seems it may not be an issue anymore. 👍

Given where we stand, I'll close this issue as "won't fix", and we can focus on proper deprecation instead.
