### ISSUE TITLE
Subscriptions module: Critical error when enabled on plugin enabled site

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/jetpack#33465]
### Impacted plugin

Jetpack, Boost

### Quick summary

Our customer reported errors in Jetpack Boost relating to CSS for single posts. I investigated the error, and noticed a list of posts in Boost's "Critical CSS advanced recommendations", along with the following message:

>It looks like these pages do not contain any relevant CSS in their external style sheet(s)

I tried to load the posts listed, and was presented with a critical error on the post. I checked for errors in our logs, and saw the following:

```
[04-Oct-2023 10:33:41 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "Automattic\Jetpack\Extensions\Subscriptions\META_NAME_FOR_POST_LEVEL_ACCESS_SETTINGS" in /wordpress/plugins/jetpack/12.7-a.3/modules/subscriptions/subscribe-modal/class-jetpack-subscribe-modal.php:182
Stack trace:
#0 /wordpress/plugins/jetpack/12.7-a.3/modules/subscriptions/subscribe-modal/class-jetpack-subscribe-modal.php(62): Jetpack_Subscribe_Modal->should_user_see_modal()
#1 /wordpress/core/6.3.1/wp-includes/class-wp-hook.php(310): Jetpack_Subscribe_Modal->enqueue_assets('')
#2 /wordpress/core/6.3.1/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#3 /wordpress/core/6.3.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /wordpress/core/6.3.1/wp-includes/script-loader.php(2225): do_action('wp_enqueue_scri...')
#5 /wordpress/core/6.3.1/wp-includes/class-wp-hook.php(310): wp_enqueue_scripts('')
#6 /wordpress/core/6.3.1/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#7 /wordpress/core/6.3.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /wordpress/core/6.3.1/wp-includes/general-template.php(3053): do_action('wp_head')
#9 /wordpress/core/6.3.1/wp-includes/template-canvas.php(17): wp_head()
#10 /wordpress/core/6.3.1/wp-includes/template-loader.php(106): include('/wordpress/core...')
#11 /wordpress/core/6.3.1/wp-blog-header.php(19): require_once('/wordpress/core...')
#12 /wordpress/core/6.3.1/index.php(17): require('/wordpress/core...')
#13 {main}
  thrown in /wordpress/plugins/jetpack/12.7-a.3/modules/subscriptions/subscribe-modal/class-jetpack-subscribe-modal.php on line 182
```

Disabling the Subscriptions module in Jetpack clears the error and the post otherwise loads for me. The site only has a few plugins and these are either WordPress, Jetpack or WooCommerce plugins. The site also uses the Twenty Twenty-Three theme.

### Steps to reproduce

1. Browse to one of the posts identified in the Jetpack Boost message (in this case, https://beatsmith.org/green-in-blue/ ) with the Subscriptions Jetpack module enabled;
2. Observe a critical error for the post;
3. Disable the Subscriptions module and load the post again;
4. The post loads.

### A clear and concise description of what you expected to happen.

Based on the site's current configuration, I would not expect to see a critical error when loading the post.

### What actually happened

A critical error appears when the Subscriptions module is enabled.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Report: 7098332-zen

**Comment by jeherve** [comment]
@Automattic/zap Could you take a look at this? I'm afraid you would need to require the constants in that file too.

**Comment by lezama** [comment]
I think ☝️  should do it for now
