### ISSUE TITLE
Assets: PHP notices (script registered incorrectly)

### ISSUE THREAD

**Issue by Enchiridion** [Automattic/jetpack#33477]
### Impacted plugin

Jetpack

### Quick summary

The Javascript asset 'wp-jp-i18n-state' is registered incorrectly, causing PHP 8.1 deprecation notices in 3rd party plugins, specifically Gravity Forms.

### Steps to reproduce

1. Start a site running only Jetpack and Gravityforms.
2. View any page.
3. See PHP deprecation notices in the php error log

### A clear and concise description of what you expected to happen.

There should be no deprecation notices

### What actually happened

Deprecation notices appear.

The issue is in jetpack-assets/src/class-assets.php:512

`$wp_scripts->add( 'wp-jp-i18n-state', null, array( 'wp-deprecated', 'wp-jp-i18n-loader' ) );`

The `$wp_scripts->add()` call specifies the 2nd arg must be a string or false, it can't be a null.  The deprecation errors happens in Gravity Forms because they're passing the src arg (the 2nd arg) to basename() which now throws a deprecation notice if `null` is passed to it in PHP 8.1.

I know this issue is also on Gravity Forms for the missing guard and have submitted a ticket to them too.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by jeherve** [comment]
It feels like we could switch to `false` in this case. Nice catch, thank you for the report!

cc'ing @anomiex who worked on #22061, to get his opinion on this.

**Comment by anomiex** [comment]
Yeah, false should be used. I don't know why I did null in the first place.
