### ISSUE TITLE
Newsletter Edit/Preview modal - stuck and cannot save

### ISSUE THREAD

**Issue by janmckell** [Automattic/jetpack#33496]
### Impacted plugin

Jetpack

### Quick summary

When trying to edit the Newsletter Edit/Preview modal, it is buggy in allowing me to add a new block, and once I do, I cannot save.

When I opened the modal, I added a Block, the same way I would for all other pages or posts. This Block only showed up when I clicked to exit the Block selection modal. If I click it several times, it adds the Block but I don't see the Block added until I close the Block selection modal.

![Annotation on 2023-10-08 at 11-27-33](https://github.com/Automattic/jetpack/assets/84089207/ea40ccdd-b49c-4791-a700-ca5ca0bc4137)

![Markup on 2023-10-08 at 11-39-21 AM](https://github.com/Automattic/jetpack/assets/84089207/780b7818-5203-48a9-9794-9ca202c1aa54)

![Annotation-Annotation on 2023-10-08 at 11-26-20 png](https://github.com/Automattic/jetpack/assets/84089207/83cedeb0-7046-411c-af20-8454efffa546)

Also, I'm not allowed to save, as the 'Save' button remains darkened, and unclickable.

### Steps to reproduce

Start at Newsletter → Settings
Scroll down to 'Enable subscriber pop-up'
Click on 'Preview and edit the popup'
Try to add a Subscribe Block, or any Block, actually.
Then, try to 'Save'.

### A clear and concise description of what you expected to happen.

I expected to be able to design my Newsletter pop-up modal, and then save it, to close out and return to Newsletter settings.

### What actually happened

I could not add the Block seamlessly, since I was selecting the Block and it was only showing as having been added, after I close the Block selection modal.

Additionally, I could not 'Save' this change/update/created layout.

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

I also noticed a 'Null' in the Browser tab for the page's title.

![Markup on 2023-10-08 at 11-39-44 AM](https://github.com/Automattic/jetpack/assets/84089207/554121b9-e3ed-4f9b-9f2d-f745d11199fe)

**Comment by janmckell** [comment]
Identified originally, here:
7075158-zd-a8c

**Comment by connorhipps** [comment]
There appears to be another instance of this bug here: 7262049-zd-a8c

**Comment by jcortx** [comment]
Another reported here: 7270162-zd-a8c

**Comment by sixhours** [comment]
I haven't been able to reproduce this even when logged in as the users, and since all reports happened within the same month, I'm thinking it was a transient bug with either the editor or Jetpack that was fixed.
