### ISSUE TITLE
Bug: Jetpack Search results show no matches for browsers running on iOS version 14 or 15

### ISSUE THREAD

**Issue by securityjedi** [Automattic/jetpack#33495]
### Impacted plugin

Search

### Quick summary

While attempting to use Jetpack Search on a site using an older iOS device (_specifically running iOS versions 14 or 15_), Jetpack Search does not return any results. 

I've tested this for both Safari and Chrome.

**Impact: For anyone running an older iOS device, it will appear as though Jetpack Search is not working.** 

### Steps to reproduce

Using BrowserStack or a physical device running iOS versions 14 or 15, 
Visit the following sites:
- https://jetpack.com/?s=creative

During my testing, I could replicate the issue across both Safari and Chrome in BrowserStack. 

### A clear and concise description of what you expected to happen.

BrowserStack - iPhone 15 (iOS 17) {screenshot below}

As expected Jetpack Search returns results, as the keyword appears in multiple places. 

<img width="1237" alt="Jetpack iOS 17 - iPhone 15" src="https://github.com/Automattic/jetpack/assets/37530482/b5d37515-2099-48c2-950a-e927ef3529b4">

### What actually happened

BrowserStack - iPhone 13 (iOS 15) {screenshot below}

On older devices (iOS 14 or 15), Jetpack Search does not return any results. 

<img width="1233" alt="Jetpack iOS 15 - iPhone 13" src="https://github.com/Automattic/jetpack/assets/37530482/e8fc3fe1-e450-4e8b-9dc7-3172258c0859">

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

This bug does not appear to affect iOS versions > 16. 

Could not test iOS versions less than 14.

**Comment by xpurichan** [comment]
Adding that this may actually affect _all_ iOS version 15 and older. I tested with a _very old_ iPhone 6 earlier today which was on iOS 11 and was able to replicate the issue.

**Comment by jeherve** [comment]
cc @Automattic/red Is that something you could look at?

Thank you!

**Comment by kangzj** [comment]
Hi @jeherve @xpurichan I'll take a look today.

**Comment by kangzj** [comment]
Hi all, It seems like this is intentional - only latest 2 iOS versions are supported by WordPress config which we extend for Instant Search. Maybe @anomiex has some insights? Thanks

<img width="711" alt="image" src="https://github.com/Automattic/jetpack/assets/1425433/55e4b6c7-e4bb-4fb4-958e-75074cb825d7">

https://make.wordpress.org/core/handbook/best-practices/browser-support/

----EDIT-----

I'll take a look why classic search is not returning any results.

**Comment by kangzj** [comment]
> I'll take a look why classic search is not returning any results.

Classic Search is only initialized when Instant Search is not.

https://github.com/Automattic/jetpack/blob/ec7456ffa6ffd12f1f5ff46932d102b11f12d0d3/projects/packages/search/src/initializers/class-initializer.php#L121

Should we enable Classic Search for older iOS devices, support more old versions of iOS or simply ignore this one? I kinda lean to support more versions of old browsers. What are your ideas moving this forward?

@Automattic/jetpack-data-team @Automattic/red

**Comment by robfelty** [comment]
I have been using Jetpack Search on iOS with Safari for at least 3 years without problems. So something must have changed is my feeling. 

It appears that over 80% of iOS users worldwide are currently on iOS 16. Given that, I am not sure I would give this a high priority. If it is a simple fix, let's do it. If not, I would encourage users to upgrade. 
https://www.statista.com/statistics/1118925/mobile-apple-ios-version-share-worldwide/
<img width="1212" alt="Bildschirmfoto 2023-10-11 um 01 56 32" src="https://github.com/Automattic/jetpack/assets/19924/da7935af-b695-4b3e-9977-f263b21727f6">

**Comment by jeherve** [comment]
>  only latest 2 iOS versions are supported by WordPress config which we extend for Instant Search. 

> It appears that over 80% of iOS users worldwide are currently on iOS 16. Given that, I am not sure I would give this a high priority.

That's very true. I don't use iOS so hadn't realized that 14 and 15 are old versions. Thank you both!

> I would encourage users to upgrade.

That seems like the best course of action indeed. Given that Core doesn't support those old versions, I don't think Jetpack should either.

**Comment by anomiex** [comment]
> Hi all, It seems like this is intentional - only latest 2 iOS versions are supported by WordPress config which we extend for Instant Search. Maybe @anomiex has some insights?

On that point, only that if you did want to support more versions, you'd probably want to start by adjusting https://github.com/Automattic/jetpack/blob/b61446387065b5100665995179faaa77799baf5b/projects/packages/search/package.json#L100-L102 in whatever manner matches your intent. Details on the syntax can be found [here](https://github.com/browserslist/browserslist#queries).

**Comment by xpurichan** [comment]
Given that this impacts iOS 15 and older we could expect this 15.6% of iOS users. If we look at just versions 14 and 15 this impacts 13.4% of iOS users. I'd personally favor showing classic search to this volume of users rather than _nothing_ (appearing broken).

@jeherve I do understand the idea of using WP Core's backwards compatibility planning for JP (Search) as well, but our partner's website isn't non-functional on these older iOS versions (tested on iOS 11, 14, and 15) - but Jetpack Search **is** non-functional.

**Comment by jeherve** [comment]
> I'd personally favor showing classic search to this volume of users rather than nothing (appearing broken).

I like that idea. We'd have to detect the os version (or the version of Safari) as the page loads, but maybe that's something worth doing.

**Comment by kangzj** [comment]
I tried to add support for older iOS versions like the following.

<img width="351" alt="image" src="https://github.com/Automattic/jetpack/assets/1425433/d6528ff9-5ee8-48a6-858d-a338255a350f">

The approach increases the size of the main bundle from `8k` to `25k` which isn't ideal. We could enqueue different versions of asset for different browsers, but that'll end up with similar amount work if not more as enabling Classic Search in these cases.

>   I'd personally favor showing classic search to this volume of users rather than nothing (appearing broken).

So I agree this might be a better idea. I'll propose a fix next week or the week after if nobody gets on it before me.
