### ISSUE TITLE
Publicize: editor panel jumps position when activating module

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#33507]
Follow-up to #33149

### Impacted plugin

Jetpack, Social

### What

When activating the "Jetpack Social” feature from the Jetpack Sidebar, the feature panel shifts to the bottom after clicking “Activate.” 

### How

There should be a more graceful positioning after activating the feature to prevent users from being disoriented and losing their place.

Surfaced during internal testing: p8oabR-1mw-p2#comment-7630

******

Epic: #32401

**Comment by jeherve** [comment]
Ideally this would be solved if #16877 were to become available. Since that doesn't seem to be happening any time soon, we'll need to find another solution.
