### ISSUE TITLE
Boost in Jetpack Manage: Loading state for wpcom sites disappears

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#33510]
### Impacted plugin

Boost

### Quick summary

Boost was just recently added to the Jetpack Manage Dashboard in this project: pedEI5-Zt-p2

When adding Boost to a WordPress.com site, the loading state (clock icon) temporarily displays, but then reverts back to "Get Score" within about 10 seconds. Shortly after that, my actual score displayed, as expected.

Below, notice how "DesignTactician.blog" changes...

Step 1: "Get Score"
<img width="1428" alt="Screen Shot 2023-10-09 at 1 37 22 PM" src="https://github.com/Automattic/jetpack/assets/214813/8bacc383-3d9b-446e-b409-5f93fed83d3b">

Step 2: "Start with Free"
<img width="1708" alt="Screen Shot 2023-10-09 at 1 37 36 PM" src="https://github.com/Automattic/jetpack/assets/214813/bddc1e46-a300-4d36-bd08-34e335e762b1">

Step 3: Loading state
<img width="1724" alt="Screen Shot 2023-10-09 at 1 37 58 PM" src="https://github.com/Automattic/jetpack/assets/214813/ce2cb7c0-0d27-439a-ba6b-526e04fe8b58">

Step 4: "Get score shows again
<img width="1705" alt="Screen Shot 2023-10-09 at 1 38 20 PM" src="https://github.com/Automattic/jetpack/assets/214813/2601c85f-ca3d-4382-a2f1-9cce70894e13">

Step 5: Actual score displays after another delay
<img width="1712" alt="Screen Shot 2023-10-09 at 1 45 51 PM" src="https://github.com/Automattic/jetpack/assets/214813/fb7b1076-7552-42f4-be4e-a51c8ce0dbcc">

### Steps to reproduce

1. Make sure you have a WordPress.com site in your dashboard
2. Click "Get score"
3. Add a free Boost plan
4. Notice the loading state. It'll jump after a little time. 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by cuemarie** [comment]
📌 ACTIONS
- Lowered priority to Normal
- Triaged

**Comment by vitozev** [comment]
Patch: D124839-code

**Comment by rcanepa** [comment]
I'm closing this issue since it has been fixed by @vitozev.
