### ISSUE TITLE
IP Detection: header lists domain name instead of IP address

### ISSUE THREAD

**Issue by jackton1** [Automattic/jetpack#33520]
I added a debug line and the current_user_ip is returning my cloudfront domain instead of the user's IP

<img width="1279" alt="Screenshot 2023-10-09 at 2 42 51 PM" src="https://github.com/Automattic/jetpack/assets/17484350/1ec53122-19c6-45e4-8125-4e2487fec42c">

### Source
https://github.com/Automattic/jetpack/blob/56b54838cc84542519b57cef24d4d213c7261994/projects/packages/status/src/class-visitor.php#L23

### Calling code: https://github.com/Automattic/jetpack/blob/52517df4847cd4e3a2d1991a9d1829ce84882d60/projects/packages/stats/src/class-main.php#L224

Changing `get_ip( true );` to `get_ip( false );` returns the correct IP

![Screenshot 2023-10-09 at 2 46 06 PM](https://github.com/Automattic/jetpack/assets/17484350/780ea7d7-fc2a-4904-9d98-e21ce7eafb19)

**Comment by jeherve** [comment]
Thanks for the report!

Could you check the different headers listed here, and let me know if one of them returns your domain instead of an IP?
https://github.com/Automattic/jetpack/blob/d19049e08efdf0551d02825d552399b9d3b284d2/projects/packages/status/src/class-visitor.php#L25-L32

**Comment by monsieur-z** [comment]
Feel free to reopen the issue with additional details should it still be relevant.
