### ISSUE TITLE
Add AMP Support

### ISSUE THREAD

**Issue by camaran** [Automattic/jetpack#3354]
add support for amp techology

**Comment by kraftbj** [comment]
We'll discuss how/if to add AMP support to Jetpack, but for now, you can use one of our (Automattic's) other plugins: https://wordpress.org/plugins/amp/

**Comment by camaran** [comment]
yes i know but give problem with like and share modules, for example https://rosolina.chatme.im/2015/07/13/ecco-come-non-si-fa-una-newsletter/amp/

**Comment by jeherve** [comment]
It looks like you found the right place to report this issue!
https://github.com/Automattic/amp-wp/issues/144

**Comment by kraftbj** [comment]
Noting that AMP will provide Jetpack Stats support.

**Comment by bcampeau** [comment]
Is there a projected timeframe for share tools support for AMP? Doing a bit too much manual work in that regard lately. Thanks.

**Comment by kraftbj** [comment]
Not a specific one yet, no. This is currently slated for our next major release (4.0).

**Comment by kraftbj** [comment]
I'm closing this as @gravityrail has worked in other issues/PRs to bring AMP helpers into Jetpack from the AMP plugin.
