### ISSUE TITLE
Fix connection flow when adding credentials

### ISSUE THREAD

**Issue by andrii-lysenko** [Automattic/jetpack#33563]

**Comment by kraftbj** [comment]
Checking if this issue is considered done and should be closed or if there is something outstanding? More details on the original issue would be helpful.

**Comment by jeherve** [comment]
I believe this is fixed as of https://github.com/Automattic/wp-calypso/pull/82677. @andrii-lysenko Could you confirm?

**Comment by andrii-lysenko** [comment]
Yes, sorry, this issue is closed. It is clearly seen that the number of errors users experience is much lower now. I'm planning to continue iterating on that page, to make it even more straightforward.


![Image](https://github.com/Automattic/jetpack/assets/60262784/79f15cdc-11f6-45b1-94ba-41a6032347fc)
