### ISSUE TITLE
Stats + Carousel: Record individual image hits

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#3356]
On WordPress.com, page hits are recorded for each image viewed full-screen in the Carousel. In Jetpack, we do not collect that.

Enhancement: Collect these stats :)

Requested in 2509419-t

**Comment by dcgavril** [comment]
Unfortunately that's a bad idea, it messed up all the website analytics, because now the stats, are showing thousands of views, even if in fact you could actually have just couple of visitors, that just scroll through a gallery... the plugin records all the #images links...

**Comment by jeherve** [comment]
> in fact you could actually have just couple of visitors, that just scroll through a gallery

These visitors are doing more than just scrolling, though: they're actively viewing images in your gallery. This new tracking also allows you to see if some images are more popular than others in a gallery. They're also a good way to find out if people are interested in your images, or if they're just scrolling through your content.

**Comment by dcgavril** [comment]
Yes, I perfectly understand what you are saying, but the problem is that in the analytics view it shows everything put together so "pageviews" in fact is pageview+photo_views... so you cannot actually see the real - for example the total is shown as 17.000 views and in fact it was ±2.000 actual pageviews ... so, the total counter and graph shouldn't reflect the image views.

**Comment by jeherve** [comment]
Reopening this as removal of this feature was also requested here:
https://wordpress.org/support/topic/remove-stats-tracking-for-carousel-photos/

@jonathansadowski Could we have your opinion here, on whether this should be a part of Jetpack Stats or not?

Thanks!

**Comment by kraftbj** [comment]
A filter would be ideal. This, as is in 4.3, brings parity to the WP.com package, which can simplify how we present what WP.com stats record.

**Comment by kraftbj** [comment]
Added a quick filter in 5154. Thoughts?

**Comment by jeherve** [comment]
> Thoughts?

I like that option. I commented there.

**Comment by jonathansadowski** [comment]
I think using a filter would be great, but I'd lean toward off by default. I've never seen anybody not confused by this behavior. I don't think it's what you'd expect to happen.
