### ISSUE TITLE
Publicize: Allow users with publishing rights to set non-global publicize connections

### ISSUE THREAD

**Issue by csonnek** [Automattic/jetpack#3357]
In troubleshooting an issue with a user ( 2508124-t ), I discovered that Authors no longer have the ability to set non-global Publicize connections and see those connections in the post editor. 

Changed in: https://github.com/Automattic/jetpack/commit/11ca809dbf3ed3f0eafca3196502269022b02ff6#diff-97d5ac2c621e87d3e66143fdf56329c3R21 

While Authors can't publish other user's articles, they can publish their own and should have the ability to set up and manage Publicize for their own posts.

**Comment by dereksmart** [comment]
Will be fixed by #3258

**Comment by csonnek** [comment]
Thanks @dereksmart - but it looks like it's getting fixed in #3341 ?

Regardless, I think this can be closed.

**Comment by dereksmart** [comment]
:100:
