### ISSUE TITLE
Social doesn't post Scheduled articles to Mastodon

### ISSUE THREAD

**Issue by Ipstenu** [Automattic/jetpack#33571]
### Impacted plugin

Social

### Quick summary

If you schedule a post, it properly pushes to social media **except** for Mastodon.

Everything is fine on a post you publish right away, but nothing seems to work for a scheduled post.

Go to my profile - https://tech.lgbt/@ipstenu - and you'll only see ONE entry for my latest post ( https://tech.lgbt/@ipstenu/111218015139603180 ) -- there should have been one via Jetpack. It worked fine on my Tumblr.

### Steps to reproduce

1. Have a blog connected to Mastodon via Social
2. Write a new post and schedule it
3. Wait for the post to be published

### A clear and concise description of what you expected to happen.

The post should be sent to Mastodon.

### What actually happened

Nothing is posted to Mastodon.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment]
@jeherve FYI  -  I don't have Mastadon so I'll be slower in trying to repro this one

**Comment by jeherve** [comment]
I gave it a try on a test site of mine and it seemed to work properly; the scheduled post was pushed to Mastodon, Tumblr, and Facebook in my test.
Looking at that specific post on your site, it was indeed not sent to Mastodon. Here is what I pulled from our Publicize logs for that post:

`Determined that this mastodon connection (@ipstenu@tech.lgbt) has been marked as skipped for this post.`

Is it possible that you unchecked the box in the block editor sidebar, at some point when writing the post?

Could you give this another try with your upcoming post and let me know if it works this time?

Thank you!

**Comment by Ipstenu** [comment]
> Is it possible that you unchecked the box in the block editor sidebar, at some point when writing the post?

100% confirmed I did NOT.

That said... all these were written _prior_ to the creation of the Mastodon-posting via Jetpack. Historically, when a new method was added, it was back-ported to all other scheduled posts. Is it possible that this backport is no longer working?

**Comment by jeherve** [comment]
> Historically, when a new method was added, it was back-ported to all other scheduled posts. Is it possible that this backport is no longer working?

That... is possible that it got broken for Mastodon. If you look at one of your upcoming posts today, do you see the Mastodon logo colored or grayed out?

**Comment by Ipstenu** [comment]
Checked the next 3 scheduled and they're all colored. I recall there was a comment on how we'd have to re-schedule to get those picked up?

Weirdly it works fine for another site, but all those posts were written _after_ Mastodon was added.

**Comment by jeherve** [comment]
I gave this a try with some of my old drafts, created and saved last year, and they were correctly published to Mastodon when I scheduled them. What I could not test, however, were posts that were scheduled then and only getting published now. I do not have such scheduled posts on my test sites I'm afraid.

To be on the safe side, I think it may indeed be best if you re-scheduled your future posts to avoid any potential issues.

**Comment by Ipstenu** [comment]
I wanted to loop back.

Guess what it is?

_ModSecurity_.

This is the ONLY site on the network that had it on for some reason, and lo and behold, if I disabled it, everything worked. No idea how you'd catch that one, but I think it's safe to close this.
