### ISSUE TITLE
Super Cache: Cache rebuild not working for post archives

### ISSUE THREAD

**Issue by hirasso** [Automattic/jetpack#33590]
### Impacted plugin

Super Cache

### Quick summary

With `$cache_rebuild_files=1`, post type archive pages will still be completely deleted

### Steps to reproduce

1. Have a WP install with WP Super Cache active (expert mode in my case)
2. Have "Cache rebuild. Serve a supercache file to anonymous users while a new file is being generated." active:
![image](https://github.com/Automattic/jetpack/assets/869813/e52cb02a-8591-4121-b94e-c1179b66cbd1)
4. Have a custom post type registered on your site (e.g. "person") with an archive page (e.g. "people")
5. Have existing cache files for at least the front page and the post type archive page:
```shell
# tree inside wp-content/cache/supercache
.
├── example.com
│  ├── index-https.html.gz
│  ├── index-https.html
│  ├── people
│  │  ├── index-https.html.gz
│  │  └── index-https.html
│  │  └── test-person-1
│  │     ├── index-https.html.gz
│  │     └── index-https.html
│  │  └── test-person-2
│  │     ├── index-https.html.gz
│  │     └── index-https.html
└── index.html
```
6. Update one of the test posts (e.g. "test-person-1") in the admin
7. Observe that the post archive's index files have completely gone.

### A clear and concise description of what you expected to happen.

I would expect the post type archive's index to stay there, with appended `.needs-rebuild`, just like the other files:

```diff
  .
  ├── example.com
  │  ├── index-https.html.gz.needs-rebuild
  │  ├── index-https.html.needs-rebuild
  │  ├── people
+ │  │  ├── index-https.html.gz.needs-rebuild
+ │  │  └── index-https.html.needs-rebuild
  │  │  └── test-person-1
  │  │     ├── index-https.html.gz.needs-rebuild
  │  │     └── index-https.html.needs-rebuild
  │  │  └── test-person-2
  │  │     ├── index-https.html.gz.needs-rebuild
  │  │     └── index-https.html.needs-rebuild
  └── index.html
```

### What actually happened

The index files for the post type archive are missing:
```diff
  .
  ├── example.com
  │  ├── index-https.html.gz.needs-rebuild
  │  ├── index-https.html.needs-rebuild
  │  ├── people
- │  │  ├── index-https.html.gz
- │  │  └── index-https.html
  │  │  └── test-person-1
  │  │     ├── index-https.html.gz.needs-rebuild
  │  │     └── index-https.html.needs-rebuild
  │  │  └── test-person-2
  │  │     ├── index-https.html.gz.needs-rebuild
  │  │     └── index-https.html.needs-rebuild
  └── index.html
```

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by hirasso** [comment]
I just tested the bug on a clean install (WP 6.3.2 and WP Super Cache 1.10.0) and with the default `post` post type. It's reproducible there, as well.

**Comment by hirasso** [comment]
Could the solution be as simple as replacing `wpsc_delete_files` with `wpsc_rebuild_files` in `wpsc_delete_url_cache()`?

https://github.com/Automattic/jetpack/blob/e9a3163a2b2b11ac241ad838e2dc720b8a0baced/projects/plugins/super-cache/wp-cache-phase2.php#L1313-L1317

**Comment by thingalon** [comment]
@donnchawp I think this one slipped through the cracks.

**Comment by donnchawp** [comment]
@hirasso your fix does seem to solve the problem, but then I see the prune_super_cache below it. That deletes paged archives, which isn't great, but it's not a deal breaker. Chances are, on a busy site, it's the blog posts that are getting hammered with updates because of comments.

**Comment by donnchawp** [comment]
@hirasso https://github.com/Automattic/jetpack/pull/35032 will fix the problem. Thanks for reporting this issue and supplying a fix!
