### ISSUE TITLE
Carousel: Slide title is cut off in landscape view of iPhone and iPad

### ISSUE THREAD

**Issue by rads** [Automattic/jetpack#336]
When the carousel is loaded in landscape view in Mobile Safari on an iPhone or iPad, the title is partially cut off on the bottom of the screen. Maybe the font size and padding could be scaled differently for short viewports.

![photo 1](https://f.cloud.github.com/assets/11401/2387075/2c82afe4-a933-11e3-9759-a94715bb2f87.PNG)
![photo 2](https://f.cloud.github.com/assets/11401/2387077/2df7eea2-a933-11e3-99c5-ff49a48eeb62.PNG)

**Comment by dereksmart** [comment]
@jeffgolenski was unable to reproduce this issue (almost 2 years later!), so it looks like it's been fixed.  Please reopen if it comes up again.
