### ISSUE TITLE
[A11y] Carousel Code Has Empty Headings

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/jetpack#33617]
### Impacted plugin

Jetpack

## Issue
The carousel code includes three empty headings, which are reported as errors when evaluating accessibility:

```
<h2 class="jp-carousel-photo-title"></h2>
<h2 class="jp-carousel-photo-caption"></h2>
<h3 class="jp-carousel-caption" itemprop="caption description"></h3>
```

## Why It Matters
Some users, especially keyboard and screen reader users, often navigate by heading elements. An empty heading will present no information and may introduce confusion.

## How to Fix It
Ensure that all headings contain informative content.

## Standards and Guidelines
[1.3.1 Info and Relationships (Level A)](https://webaim.org/standards/wcag/checklist#sc1.3.1)
[2.4.1 Bypass Blocks (Level A)](https://webaim.org/standards/wcag/checklist#sc2.4.1)
[2.4.6 Headings and Labels (Level AA)](https://webaim.org/standards/wcag/checklist#sc2.4.6)

### Steps to reproduce

Visit a site with the carousel enabled. Run a check with the A11y tool of your choice.

WAVE a11y check:
https://wave.webaim.org/

### Impact

All

### Logs or notes

Noted on atomic sites. Surfaced via QA testing on multiple Team51 partner sites.

**Comment by stronenv** [comment]
Also reported here, possible duplicate: https://github.com/Automattic/jetpack/issues/29141
