### ISSUE TITLE
RichText: replace deprecated multiline prop with simple multiple instances (Donations block)

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#33642]
See https://github.com/WordPress/gutenberg/pull/54310

Primary issue: #32865

**Comment by anomiex** [comment]
Looks like the only place we use this, we're setting it to false anyway?
https://github.com/Automattic/jetpack/blob/8849299b7135c9ef783b1723407a93786c1caa03/projects/plugins/jetpack/extensions/blocks/donations/amount.js#L106
