### ISSUE TITLE
Publicize: option can't be unchecked for Custom Post Type

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3365]
Steps to reproduce:
1. Go to Posts > Add New on a Jetpack site where you've added at least one Publicize connection
2. Write a draft, save it.
3. Click on Publicize's "Edit Details" link right above the Publish button
4. Disable Publicize for that post.
5. Hit Publish
6. Check your connected Social Media profile; your post was publicized there anyway.

I can't reproduce when posting from Calypso.

Reported here:
https://wordpress.org/support/topic/cannot-uncheck-publicize-checkbox-on-custom-post-type?replies=1&view=all

**Comment by jeherve** [comment]
cc @aduth in case you have some ideas as to what could cause this.

**Comment by aduth** [comment]
Having trouble reproducing the original steps with a Facebook connection. Could you provide more detail about the connection itself (which service) and the post (anything specific besides having a title entered?)

**Comment by jeherve** [comment]
It was a connection to a Facebook Page, and I had entered a title and some random content. I'd be happy to give you access to my test site if that can help. Email is on the way!

**Comment by aduth** [comment]
>It was a connection to a Facebook Page, and I had entered a title and some random content.

Tested it on your site and not seeing the published post on your Facebook feed (unless it's been restricted by privacy settings I'm not privy to?)

Would you mind doing some testing to verify whether this occurs for you on a Facebook profile (not a page), and whether the connection was originally established with the same user account used to publish the post?

**Comment by jeherve** [comment]
> Tested it on your site and not seeing the published post on your Facebook feed

It seems it wasn't published:

![screen shot 2016-02-03 at 10 25 51 pm](https://cloud.githubusercontent.com/assets/426388/12797616/238b3108-cac5-11e5-9b92-0801addd143a.png)

> Would you mind doing some testing to verify whether this occurs for you on a Facebook profile (not a page)?

I.. can't reproduce anymore. :( Marking it as skipped really ships it now, whether for a Page or for a Profile.

> the connection was originally established with the same user account used to publish the post?

Yes.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/publicize-edit-options-grayed-out-for-duplicated-posts?replies=1&view=all

**Comment by jeherve** [comment]
@aduth I seem to be able to reproduce now. Can you check my site again, and try to publish new events?

**Comment by aduth** [comment]
>Can you check my site again, and try to publish new events?

Okay, I can reproduce now. Do you think this is specific to custom post types then?

**Comment by jeherve** [comment]
Yes. I can't seem to reproduce with posts.

**Comment by Rykus0** [comment]
I have this issue with a user who is an Author.   I am admin, and also the one connected to jetpack.  She can see the options but can't uncheck them.  I created an author account of my own to see, and was unable to modify the checkboxes with my author account as well.  Clicking on the settings link showed as if there was no publicize settings and that the user needed to connect with their wordpress account.  Not sure if that helps debug the issue, but it seems to be connected with account levels.
