### ISSUE TITLE
VideoPress: Block videopress/video is not enqueued properly on feed pages

### ISSUE THREAD

**Issue by tommusrhodus** [Automattic/jetpack#33660]
### Impacted plugin

Jetpack, VideoPress

### Quick summary

On a feed page, if the most recent post does not include the videopress/video block, all other posts in that feed will not render the block. 

- Single views are unaffected.
- The active theme needs to be a classic theme, and not a P2

See here:

https://github.com/Automattic/jetpack/blob/4fb0a07fc0de617b5ac336d27953d2016db72154/projects/packages/videopress/src/class-initializer.php#L375-L396

`get_the_content()` in this context only returns the most recent post object, if this doesn't contain the block, the block is not enqueued on the front-end. This creates an inconsistent experience on the front-end of a feed page.

### Steps to reproduce

1. Use a non-blocktheme to create a new site, recommended: twenty-thirteen
2. Create a post with a videopress/video block in the content (along with any other content) and publish.
3. Observe on the homepage (index.php) that the video will show in the post content.
4. Now publish another post without this block in the content.
5. On re-visiting the homepage, observe that the now second post in the feed, containing the video block, the video block no longer appears.

### A clear and concise description of what you expected to happen.

The videopress/video block should render in the post feed.

### What actually happened

The block disappears once the most recent post in a feed does not contain this block.

### Impact

All

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

Here's a workaround, but it requires code editing and feels fragile:

```php
/**
 * Drop-in to ensure that the VideoPress block is always available on the frontend.
 *
 * @return void
 */
function prefix_always_load_videopress_on_frontend() {

	// Exit early if not on the frontend.
	if ( is_admin() ) {
		return;
	}

	// Exit early if VideoPress block is already registered.
	if ( WP_Block_Type_Registry::get_instance()->is_registered( 'videopress/video' ) ) {
		return;
	}

	// Ensure VideoPress block is always available by manually registering it.
	if ( class_exists( 'Automattic\Jetpack\VideoPress\Initializer' ) && method_exists( 'Automattic\Jetpack\VideoPress\Initializer', 'enqueue_block_assets' ) ) {

		$videopress_video_metadata_file        = WP_PLUGIN_DIR . '/jetpack-dev/jetpack_vendor/automattic/jetpack-videopress/build/block-editor/blocks/video/block.json';
		$videopress_video_metadata_file_exists = file_exists( $videopress_video_metadata_file );

		// Exit early if VideoPress block metadata file does not exist.
		if ( ! $videopress_video_metadata_file_exists ) {
			return;
		}

		// Register the block.
		Automattic\Jetpack\VideoPress\Initializer::enqueue_block_assets( $videopress_video_metadata_file );
	}
}
add_action( 'wp_enqueue_scripts', 'prefix_always_load_videopress_on_frontend', 20 );
```

**Comment by jeherve** [comment]
@Automattic/jetpack-agora Is that something you could take a look at?

Thank you!
