### ISSUE TITLE
Jetpack AI Search button responsive styling

### ISSUE THREAD

**Issue by cagrimmett** [Automattic/jetpack#33673]
### Impacted plugin

Jetpack

### Quick summary

The Ask button in the Jetpack AI Search needs style changes on mobile. The text currently flows outside of the button on mobile. The fix is adding `white-space: nowrap;` to `.jetpack-ai-chat-question-button`

I reproduced the issue and the fix on two separate themes on different hosts.

### Steps to reproduce

Load the Jetpack AI Search block on a page.
View that page on mobile.
See the text flowing outside of the button.

### A clear and concise description of what you expected to happen.

The Ask button should look the same on desktop and mobile.

### What actually happened

The Ask button text flows outside of the button.

![EE121E88-4CB6-4754-8716-0275080C7EA2_4_5005_c](https://github.com/Automattic/jetpack/assets/8738771/f42a2657-b35e-4276-a84d-9978b8486814)

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

The fix is adding `white-space: nowrap;` to `.jetpack-ai-chat-question-button`

**Comment by monsieur-z** [comment]
The button now looks the same on mobile and desktop, with either a short or long label. Closing.
