### ISSUE TITLE
Media Summary: get_the_excerpt filter is used too early

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3370]
WordPress uses paging in `get_the_content()`, called by `wp_trim_excerpt()` when you didn't create any custom excerpt. 

Unfortunately, paging is not well-defined in the header, before the loop begins, where we actually use the `get_the_excerpt` filter to filter our excerpt content:
https://github.com/Automattic/jetpack/blob/3.9.1/class.media-summary.php#L260

Steps to reproduce:
1. Install WordPress.
2. Install and activate and connect Jetpack.
3. Configure Publicize: Twitter, approve Twitter credentials.
4. Optional: Put `define('WP_DEBUG', true);` in wp-config.php.
5. Edit `wp-includes/post-template.php.`
   Around line 269 is this line:
   `$content = $pages[$page - 1]`

After that line, add

```
print("<pre style='background: white; color: black;'>DEBUG: page=$page, count(pages)=" . count($pages) ."</pre>\n");
print("<pre style='background: white; color: black'>DEBUG: strlen(content)=" . strlen($content) ."</pre>\n");
```
1. Go to the Hello World post WP created on installation.

Expected results:

```
DEBUG: page=1, count(pages)=1
DEBUG: strlen(content)= [ about 85? ]
```

Actual results:

```
DEBUG: page=0, count(pages)=0
DEBUG: strlen(content)=0
```

More details here:
https://wordpress.org/support/topic/undefined-index-warnings-due-to-jetpack_media_summaryget

**Comment by kitchin** [comment]
I reported this. Slightly modified STR:
3. When Jetpack asks to "Jump Start your site," click "skip." Configuring Twitter is not necessary.

For the test you want Publicize active, but nothing else that would try to create an excerpt for the post.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
