### ISSUE TITLE
Sharing: Undefined array key "id" warning

### ISSUE THREAD

**Issue by tubiz** [Automattic/jetpack#33728]
### Impacted plugin

Jetpack

### Quick summary

I have been getting multiple errors in the error log for the error below

```
PHP Warning:  Undefined array key "id" in /public_html/wp-content/plugins/jetpack/extensions/plugins/sharing/sharing.php on line 41
```

### Steps to reproduce

This is triggered when checking if sharing is enabled for a post when making an API request.

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by jeherve** [comment]
@tubiz Thanks for the report, we'll take a look and get this fixed!

@andrii-lysenko Do you think you could take a look? Looks like we introduced it in #33226. 

Thank you!

**Comment by jeherve** [comment]
@tubiz We're having a bit of trouble reproducing the issue at the moment. Could you tell us more about your setup? Do you happen to use a specific Custom Post Type on your site?

**Comment by tubiz** [comment]
@jeherve these are 11 registered CPTs on the sites.

These are the list of all the post types on the site.

- post
- page
- attachment
- product
- report
- bp-plus
- featured
- company-event
- staffs-profile
- exhibition-booth
- events
- event-speaker
- mwac-booth
- oxy_user_library

**Comment by andrii-lysenko** [comment]
@tubiz Sorry for a late response, but we are handling a large number of tasks at the moment. Could you please additionally share the approximate query you are using? 
From the error you shared it seems like there's no 'post' data present which shouldn't be the case, so would help to have some more context. Thank you.
