### ISSUE TITLE
Add Social Tracking, after the initial post

### ISSUE THREAD

**Issue by captbrando** [Automattic/jetpack#3376]
The Social plugin from Mailchimp does (or used to do) this where once a post was pushed to social media, any replies or retweets/reshares were captured as comments inside of the post history. Love how I can capture discussions on my post in one place!

**Comment by jeherve** [comment]
I'm afraid that's not something that's on our radar right now. If you'd like to add that feature to your site, I'd recommend a plugin like this one:
https://wordpress.org/plugins/gplus-comments/

You can use it alongside Jetpack's Comments module, and it will allow you to capture content that's posted to Facebook and Google+. 

The [Social plugin](https://wordpress.org/plugins/social/) does indeed do something similar, but was retired.

Thanks for the feedback!
