### ISSUE TITLE
VideoPress: Block is not displayed on emails

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#33787]
When sending subscription emails, VP blocks are not displayed. A fallback image should be rendered there.

![Image](https://user-images.githubusercontent.com/8486249/278122488-0add835c-ae2c-4b2f-9361-2ebe464df87e.png)

**Comment by dhasilva** [comment]
Issue reported in #6713198-zen

**Comment by jeherve** [comment]
Related: p1693899247991939-slack-CBG1CP4EN

**Comment by dhasilva** [comment]
Fixed by D126650-code
