### ISSUE TITLE
Jetpack AI: Consolidate upgrade UI implementation

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#33780]
The Jetpack AI panel shows (as long beta extensions are enabled) two sections to upgrade the plan.
Let's consolidate showing only one section for it, and probably based on the same `<UpgradeBanner />` component:

![Image](https://user-images.githubusercontent.com/77539/278053643-aee953b9-e1e2-48d8-846e-c88194c9c4aa.png)

**Comment by lhkowalski** [comment]
Keep in mind that the upgrade button should be visible everytime, even before reaching the limit, so the messaging should not mention the limit being reached.

Also, this button will be used in the near future to sell the plan upgrades on the tiers, with call-to-actions like "Get 200 requests", as designed in p1HpG7-oMv-p2.

I think the upgrade banner can be tweaked to fit all this cases, just wanted to mention the future plans for the button :)

**Comment by retrofox** [comment]
### Free plan / Still free requests available


<img src="https://github.com/Automattic/jetpack/assets/77539/50945adb-7235-4e0f-a45b-7a4c72fc9ba5" width="300px" />


### Free site / requests limit achieved

<img src="https://github.com/Automattic/jetpack/assets/77539/0131362f-d400-48ac-ad24-3dd8301e3e2a" width="300px" />

**Comment by lhkowalski** [comment]
I think we can probably drop the upgrade banner being showed by the "Generate feedback" feature to focus only on the usage panel. Makes sense?

**Comment by retrofox** [comment]
Yes, it does. So we should

1. Remove the following part:


<img src="https://github.com/Automattic/jetpack/assets/77539/541c18c3-ca4d-4c27-968d-81786f9668f4" width="300px" />

2. Continue with the UsagePanel part



<img src="https://github.com/Automattic/jetpack/assets/77539/6246ddac-0cb0-4945-b014-727326fef4b5" width="300px" />
