### ISSUE TITLE
Gallery block: images don't scale vertically in emails

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#33798]
### Impacted plugin

Jetpack

### Quick summary

When adding images via core gallery block, the images scale well to screen size in desktop.

In the email images scale only horizontally, not vertically.

[Example post](https://jpcomplete.mystagingwebsite.com/2023/10/24/new-2/). [User report.](https://wordpress.org/support/topic/images-to-appear-distorted-in-the-email-showing-the-post/#post-17142060)

**Desktop**

https://github.com/Automattic/jetpack/assets/87168/812d7ac7-cbc7-4c93-b33f-671d5703b58c

**Email**

![image](https://github.com/Automattic/jetpack/assets/87168/1ce13df1-9896-425b-8c3a-5c02c99f1665)

Reported at p1698133168065399-slack-C02NQ4HMJKV

### Steps to reproduce

—

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by sunipeyk** [comment]
Thank you @simison. And a little advice/request for those whom writing the codes; please avoid using inline css. It's a terrible idea. Thank you again.

**Comment by sunipeyk** [comment]
The description of the problem is incorrect/ and/or incomplete.  note: I think I explained the situation more clearly in my comments below.

**Comment by sunipeyk** [comment]
I reviewed an older post of mine. ( **sep, 18 2023**) The inline css of the images of that post email is normal, as expected. However, those images were not deformed. The problem was not with the width:46% used inline. For your information. 
And let me add one more thing. When I look at the problematic e-mails on iPhone, single images in the text are problematic, too. I think there was a problem after the date I gave above and it continues.

**Comment by sunipeyk** [comment]
Hello again, It is clearly seen that the required for the image to be responsive "height : auto;"  is not included in the relevant inline css code.
If you don't want to use "height : auto;" in inline css code , you must not use "...<img **width="500" height="650"** src..." ( the bolds that width and height ) either. Those ruins the responsiveness of images. For your information.

**Comment by sunipeyk** [comment]
5 months have passed and no one is doing anything. Great, really great!

**Comment by sunipeyk** [comment]
You did not fix this problem in version 6.5. I wonder why? Anyway, I give up, no one cares anyway.

**Comment by Potato3142** [comment]
I seem to have this or a similar problem. Images in email are being squeezed vertically

**Comment by simison** [comment]
Update here: we deployed some changes to email rendering images in D147624-code (internal reference), [external reference](https://github.com/Automattic/jetpack/issues/35464) but the issue here needs additional checks likely. cc @Automattic/zap

**Comment by simison** [comment]
With some work done for this and no further reports here, I'm moving future similar problems to separate issues.

**Comment by Potato3142** [comment]
> With some work done for this and no further reports here, I'm moving future similar problems to separate issues.

It's not fixed, though.
