### ISSUE TITLE
Network: Missing cache invalidation for Jetpack_Network::wp_get_sites()

### ISSUE THREAD

**Issue by ocean90** [Automattic/jetpack#3379]
In `Jetpack_Network::wp_get_sites()` https://github.com/Automattic/jetpack/blob/8a30daea4c9caea855c24b0ea7e9758d35e01e32/class.jetpack-network.php#L799 the results are cached based on the query. If the query remains the same but new sites are added the method will return old results because the cache never gets deleted.

**Comment by georgestephanis** [comment]
Honestly, I'm fine with just deleting this function and migrating to the core implementation, as noted in the phpdoc.

I doubt we use it heavily enough to necessitate the caching, and would prefer to defer to the core implementation.
