### ISSUE TITLE
AI Assistant: consider to avoid requesting AI Assistant feature in initial rendering

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#33839]
> we can check if it's possible to not set an initial state at all for the AI Assistant as a follow-up.

**Comment by CGastrell** [comment]
This is a tough one. We rely on the backend payload for a lot of things that need to be ready at render time. 

Removing the error check from `projects/plugins/jetpack/extensions/blocks/ai-assistant/extensions/lib/can-ai-assistant-be-enabled.ts` helps delay the request a bit:

```js
// removing this check should not be critical
  const { errorCode } = select( 'wordpress-com/plans' )?.getAiAssistantFeature?.() || {};
  if ( errorCode ) {
    return false;
  }
```

but then it is immediately needed by the sidebar, where the feature data is not optional: it's used to determine if the entire set of AI features should be rendered on the panel and if the user needs an upgrade or not.

While that chunk is not vital, it does pose a condition (`canAiAssistantBeEnabled`) which can be disruptive down the ladder. 

I've thought about adding loading states and perform the request async, but that would degrade the UX, specially considering that, sooner or later, the payload will be needed/requested.

EDIT: this is the suggested change - https://github.com/Automattic/jetpack/pull/40172
