### ISSUE TITLE
My Jetpack: Manage Jetpack AI Subscription Confusion

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#33848]
### Impacted plugin

Jetpack

### Quick summary

In the "My Jetpack" section of the plugin, when a user has a Jetpack AI plan, we present a greyed-out CTA:

![Annotation on 2023-10-28 at 09-32-36](https://github.com/Automattic/jetpack/assets/45246438/2a47fc88-6d9f-4750-ae7f-edb366105274)

When you mouse over greyed-out CTA, it has a strange style:

![Annotation on 2023-10-28 at 09-32-09](https://github.com/Automattic/jetpack/assets/45246438/c48a6fc7-95de-4805-a2be-82db0020096a)

### Steps to reproduce

1. Add a Jetpack AI plan to a site
2. Navigate to "My Jetpack"
3. See the ambiguous "Manage" text.

### A clear and concise description of what you expected to happen.

Since there isn't anything that a user can manage, it would be better not to show a button at all here. The "Active" text indicates when the feature is activated.

### What actually happened

The "Manage" CTA is confusing and the hover state changes but is unclickable, which adds to the confusion.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by monsieur-z** [comment]
I could no longer reproduce the issue.
<img width="364" alt="Screenshot 2024-05-06 at 3 46 07 PM" src="https://github.com/Automattic/jetpack/assets/1620183/b2e0f017-bf01-43c7-acf3-289a672d5475">
