### ISSUE TITLE
Payment Buttons block doesn't honor width setting

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/jetpack#33849]
### Impacted plugin

Jetpack

### Quick summary

When you add a Payment Buttons block and set the width on the button it isn't honored.

### Steps to reproduce

1. Add the Payment Buttons block
2. Set the width to 100%
3. Save
4. (Need to have a Stripe account connected)

### A clear and concise description of what you expected to happen.

I expected the button to display on the live site at 100% of the content area width.

### What actually happened

The width of the button doesn't change. It's also worth nothing that regardless of the width setting, in the editor the button displays as full-width.

![5OKyUw.png](https://github.com/Automattic/jetpack/assets/42655541/f40e41b3-3c9a-44f0-a7b2-8b8b79fda63c)

![cXWUii.png](https://github.com/Automattic/jetpack/assets/42655541/8685fb9e-b7ae-4b9f-b2e3-ce9c7996e5e2)

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

I've tested this on Atomic, Simple, and Pressable with various themes including Classic and Block and all with the same result.

I spent a fair bit of time trying to come up with some CSS to override it and wasn't able to.

**Comment by tanjoymor** [comment]
Customer report 7229965-zen

**Comment by msilbers** [comment]
also reported in 7216676-zen

**Comment by radtechgh** [comment]
7294455-zen

**Comment by jp-imagines** [comment]
Another report in 7587931-zd-a8c.

This user has a page with some newer Payment Buttons blocks that are structured differently than older ones, and only the new ones are affected. (Older buttons are `Payment Button > Button`, newer ones are `Payment Buttons > Payment Button > Button`.)

Some CSS can be used to force the buttons to 100% as needed:

```
/* Force payment buttons to 100% width | xxx -zen */
.wp-block-jetpack-payment-buttons-is-layout-flex a.wp-block-button__link {
    width: 100%;
}

.wp-block-jetpack-payment-buttons.is-layout-flex.wp-block-jetpack-payment-buttons-is-layout-flex {
    display: block;
}
/* /end xxx -zen */
```

**Comment by millerf** [comment]
Closing as duplicate of https://github.com/Automattic/jetpack/issues/38747
