### ISSUE TITLE
Twitter Card Images which are set by jetpack_twitter_cards_image_default filter can never be 'summary_large_image'

### ISSUE THREAD

**Issue by alecmuffett** [Automattic/jetpack#33861]
### Impacted plugin

Jetpack

### What

A filter or other means to externally set the OpenGraph tag for 'twitter:card'

### How

In `class.jetpack-twitter-cards.php` around line 172 we find:

```php
                if ( empty( $og_tags['twitter:image'] ) && empty( $og_tags['twitter:image:src'] ) ) {
                        /** This action is documented in class.jetpack-twitter-cards.php */
                        $image = apply_filters( 'jetpack_twitter_cards_image_default', '' );
                        if ( ! empty( $image ) ) {
                                $og_tags['twitter:image'] = $image;
                        }
                }
```

...but this occurs well after any code (e.g. around lines 116..158) which coulld mutate the value of `$og_tags['twitter:card']` to a card-type/value of `summary_large_image`, which means that any customisation using that filter CANNOT generate large cards on Twitter.

There are a bunch of ways this could be addressed, e.g. building a revised version of jetpack_twitter_cards_image_default which returns both the image URL and card-type, or maybe by providing a last-ditch filter which can edit/replace $og_tags in its entirety.  I am not sure which of these would be most desirable.

But it would be nice for people like me who use `jetpack_twitter_cards_image_default` to be able to generate large cards on Twitter.

Thanks!

**Comment by jeherve** [comment]
You should be able to do that with the `jetpack_images_get_images` filter, like so:

```php
/**
 * Define a default fallback image to be used when no other image can be found in the post.
 *
 * @param array $media Array of images that would be good for a specific post.
 * @param int $post_id Post ID.
 * @param array $args Array of options to get images.
 */
function jeherve_default_image( $media, $post_id, $args ) {
	if ( empty( $media ) ) {
		$media[] = array(
			'type'       => 'image',
			'from'       => 'large_fallback',
			'src'        => esc_url( 'https://jeremy.hu/wp-content/uploads/watson-5818-1.jpg' ),
			'src_width'  => 1024,
			'src_height' => 683,
			'href'       => get_permalink( $post_id ),
			'alt_text'   => 'Alt text description for this image',
		);
	}
	return $media;
}
add_filter( 'jetpack_images_get_images', 'jeherve_default_image', 10, 3 );
```

Just make sure your image is large enough (at least 300x157px), and it should work.

Let me know how that goes!

**Comment by alecmuffett** [comment]
So, to check my understanding: if I use this filter instead I will be passing-in data "higher up" in the code, where the result will be filtered by existing code for large-image cards, and everything will just drop out automatically?

If so that's awesome; though I presume it's wise to leave my other / existing filters in the code anyway, as a fallback?

**Comment by jeherve** [comment]
> if I use this filter instead I will be passing-in data "higher up" in the code, where the result will be filtered by existing code for large-image cards, and everything will just drop out automatically?

That's correct.

> though I presume it's wise to leave my other / existing filters in the code anyway, as a fallback?

You could, but if you were previously filtering on `jetpack_twitter_cards_image_default`, you just won't get to that fallback anymore, because you'll always have a fallback image before you even get to that filter.

**Comment by alecmuffett** [comment]
It took a little refactoring but I got it working just fine, and it allows me to do AltText too - wonderful!  Thank you ever so much.  Maybe there's something we can do to turn this issue into documentation for future people like me?

**Comment by jeherve** [comment]
> Maybe there's something we can do to turn this issue into documentation for future people like me?

The filter is documented here today:
https://developer.jetpack.com/hooks/jetpack_images_get_images/

It has a similar code snippet as the one I posted above, although without the `alt` as it didn't exist back when I created this snippet. I'll update it right now!

**Comment by alecmuffett** [comment]
I'd like to suggest adding something to `jetpack_open_graph_image_default` and `jetpack_twitter_cards_image_default` documentation, along the lines of:

> If you are considering using this filter, you may find it more impactful to modify your approach and use `jetpack_images_get_images` instead, which offers much more customization and support for multiple tags to be defined in one group

...?

**Comment by jeherve** [comment]
That's a good point. I've just done that. 👍 

Thanks for the feedback!
