### ISSUE TITLE
WP Stats Image Pixel Creates Gap Under Site Footers

### ISSUE THREAD

**Issue by VR51** [Automattic/jetpack#3390]
Noticed this issue a couple of times. The 1px image/Smiley Face used by WP Stats sits below the footer of a website and thereby causes a gap between the footer and browser's bottom edge. This gap appears to show more frequently in Chrome and Safari than in Firefox.

I'm using the following fix:

```
#wpstats {
	position:absolute;
	top:0;
}
```

Can anyone suggest a reason to not use this fix?

If there are no reasons to not do this can this fix be added to the WP Stats module to ensure the issue no longer affects users of the module.

**Comment by jeherve** [comment]
> The 1px image/Smiley Face used by WP Stats sits below the footer of a website and thereby causes a gap between the footer and browser's bottom edge. 

That will most likely depend on how images are styled in your theme.

> Can anyone suggest a reason to not use this fix?

That could work indeed, although I can't seem to reproduce the issue on my own test sites.
Could you post your site URL here, so I can have a look?

If you want it to remain private, you can also contact us via this contact form:
http://jetpack.me/contact-support/

**Comment by VR51** [comment]
The pixel is currently hidden within the site so you will need to counteract the above mentioned CSS. The site is https://mundolanugo.com.

The theme is Genesis with Dynamik (from Cobalt Apps). The file cache is currently disabled. I use the Genesis/Dynamik combination frequently. Have noticed the same stats smiley face/pixel displayed under the footer many times with this combination.

Thanks for looking at this.

**Comment by jeherve** [comment]
How about adding the following:

```css
.site-footer {
    position: absolute;
}
```

It would make sure your theme's footer is really the last element on the page, and the Stats smiley wouldn't get hidden.

The Stats smiley is actually hidden by default, and has been since 2014 (#656). If you're working on an old site, where the default was still set to display the widget, you can hide it by going to Jetpack > Site Stats > Configure in your dashboard.
It might be easier to do so than to add CSS to each one of your sites.

**Comment by VR51** [comment]
Had forgotten the smiley face could be hidden in the settings.

Good idea to set the footer position to absolute.

Thank you Jeremy.

**Comment by keepsmilyn** [comment]
Unfortunately the option to hide the smiley in the settings didnt work for me. I used CSS to move and and hide it instead.
