### ISSUE TITLE
Gallery Widget: Javascript error when using slideshow type and Carousel option

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3391]
Steps to reproduce:

1. In Appearance > Widgets, create a new Gallery widget with the following settings:
![screen shot 2016-02-09 at 7 06 11 pm](https://cloud.githubusercontent.com/assets/426388/12925838/ac42199a-cf60-11e5-9b06-2558cacf9cdd.png)
2. Activate Twenty Sixteen
3. Load your home page. You won't be able to use the slideshow, and the following error will be displayed:

`Uncaught TypeError: Cannot read property 'opened' of undefined`
jetpack-carousel.js:1485

![screen shot 2016-02-09 at 7 10 39 pm](https://cloud.githubusercontent.com/assets/426388/12925887/db558f00-cf60-11e5-8139-6af6c3e4e4e4.png)

Reported here:
https://wordpress.org/support/topic/jetpack-carouseljs-hashtag-issues

Related: #3128 and #3250

**Comment by jenhooks** [comment]
I have a user in 2583402-t with a related issue, using the Divi theme. These are the Divi modules they report using on the page where they're getting the error:

Side Bar
Weather Widget
Buttons Module
Accordion Module
Blog Module
Video Module
Gallery Module

**Comment by jeherve** [comment]
Fixed in #3737
