### ISSUE TITLE
VideoPress: Video listing endpoint returns poster URLs different from the video poster endpoint

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#33916]
After manually updating a video's poster image, sometimes there is an URL conflict resulting in broken thumbnails, like this:

![Image](https://github.com/Automattic/jetpack/assets/8486249/062faf66-9cec-45cd-ad1b-b40de8151352)

That comes from the `wp/v2/sites/<site_id>/media?mime_type=video/videopress` endpoint, and the wrong URL is in the video's `media_details.videopress.poster` string value.

Using the `/rest/v1.1/videos/<guid>/poster` endpoint, however, we get the correct URL in the `poster` string value.

The difference seems to be the lack of a `-<number>` suffix, like `https://videos.files.wordpress.com/gapCdVFi/rabbits-7_mp4.scrubthumb.jpg` instead of `https://videos.files.wordpress.com/gapCdVFi/rabbits-7_mp4.scrubthumb-1.jpg`.

This _may_ be related to a problem with poster images on newsletter emails as well.

**Comment by rickmgithub** [comment]
📌 REPRODUCTION RESULTS
Need .org site with VideoPress installed
– Tested on .org Could Not Replicate 

📌 ACTIONS
– Requested author feedback

Hello @dhasilva Did you find any sequence that made the error appear? You mentioned that it only happens sometimes. I tried to replicate it but couldn't. Any other thoughts on how to see it? I'll close for now but if you can replicate it please do feel free to re-open this.
