### ISSUE TITLE
VideoPress: Email uses video poster image when the block instance has another poster image

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#33914]
Steps to reproduce in a blog you are subscribed to:

1 - Add a VP video block to a post
2 - Use the poster image panel do select a different poster image from, say, pexels
3 - Publish the post

Check the email you'll receive about the post and notice that the video poster is not the one set in the block instance.

**Comment by bobmatyas** [comment]
I confirmed this behavior.

**Comment by simison** [comment]
PR at D161889-code

**Comment by simison** [comment]
In prod since Sep 26
