### ISSUE TITLE
Jetpack AI: fix bug that allows 21 requests on a free site instead of 20

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#33922]
Currently, the real limit when the site does not have a plan is 21. The user can make 21 requests before being prompted to upgrade.

This causes undesireable results on the UI like (notice the "21 / 20" label):

![Image](https://github.com/Automattic/jetpack/assets/6760046/7cc01820-db8c-4f52-adcc-ebc0981e3aa3)

We need to check the code that does the limit enforcement to fix this behavior.

**Comment by dhasilva** [comment]
Moved to Done on Nov 6, 2023
