### ISSUE TITLE
AI Tiered Plans: Usage Helper fails to load data when BLOG_ID = 1

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#33926]
The usage helper is timing out when BLOG_ID = 1, causing issues while using the editor on WordPress.com. The root cause is related to fetching purchase information for this blog ID. We need to fix it.

**Comment by lhkowalski** [comment]
New information: it may be related to using a bad-performance `WPCOM_Store_API::get_site_purchases` call. We can try to use the suggested alternative to check it works as expected. Reference: panfyZ-2XW-p2#comment-7153

**Comment by lhkowalski** [comment]
I tested running the suggested alternative on `wpsh` and it works nicely, not hanging for BLOG_ID = 1. We may choose this path.

**Comment by CGastrell** [comment]
Solved on #33937
