### ISSUE TITLE
Photon: do not parse images using the `ng-src` attribute instead of `src`

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3393]
AngularJS's `ngSrc` directive ([#](https://docs.angularjs.org/api/ng/directive/ngSrc)) allows you to use Angular markup in images' `src` attribute. Unfortunately, Photon doesn't play with such image src URLs.

We should probably update our regex to make sure images using the `ng-src` attribute instead of `src` are not parsed by Photon.

Reported here:
https://wordpress.org/support/topic/compatibility-of-photon-with-angularjs

**Comment by thingalon** [comment]
Tested with AngularJS and post-#3396 Jetpack. This issue is fixed. Props to @ccprog.
