### ISSUE TITLE
AI Tiered Plans: ensure the ai-assistant-feature endpoint exposes the usage and tier data we need

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#33937]
We had some problems in the last days regarding performance on the `ai-assistant-feature` endpoint:

- first, slow results and database overload due to using `srtm = true` on the database
- after, very slow loading time for the editor when BLOG_ID = 1 (probably linked to using a very slow `WPCOM_Store_API::get_site_purchases ` call: panfyZ-2XW-p2#comment-7152)

We need to revisit the endpoint to make sure it returns all the data we need (take some time to think what data is needed), and also provide it considering performance implications.

So far, the data we need is:

- current period usage
- when the current period started
- when the next period will start
- which tier the given site has
- which tiers are available, the limits for each one, proper slugs, etc

---

Related:

- https://github.com/Automattic/jetpack/issues/33824
- https://github.com/Automattic/jetpack/issues/33792
- https://github.com/Automattic/jetpack/issues/33926

**Comment by CGastrell** [comment]
> which tiers are available, the limits for each one, proper slugs, etc

Except for "proper slugs" this one was addressed on #33939 But the slugs there are consistent and usable until we get or map the real ones

**Comment by lhkowalski** [comment]
I am closing this as done, since the change is already in production and we got the API response to a point where it's usable and reliable.
