### ISSUE TITLE
JSON API: sites endpoint needs to include both `home_url` and `site_url`

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#3395]
Currently the /sites/$site endpoint includes a `URL` in the response, and URL = home_url().  But in cases where the home_url() and site_url() are different, it will cause the post editor on wordpress.com to fail. 

We'll probably should add `site_URL` and `home_URL` to the API response, while also maintaining `URL` for backward compatability.

cc: @lezama

**Comment by jeherve** [comment]
@roccotripaldi Does #4011 fix this?

**Comment by roccotripaldi** [comment]
No sir #4011 relates to the connection process only.

**Comment by gravityrail** [comment]
Site URL is returned as "site->options->unmapped_url". Closing this.
