### ISSUE TITLE
Boost: update readme to no longer recommend lazy-loading.

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#33953]

**Comment by thingalon** [comment]
Note: I am marking this as a part of the React migration, as I want to deprecate Lazy Loading in the same release.

**Comment by haqadn** [comment]
> Note: I am marking this as a part of the React migration, as I want to deprecate Lazy Loading in the same release.

I think we are ready to remove the module as well. Do you agree?

@thingalon

**Comment by thingalon** [comment]
Yes I agree :)
