### ISSUE TITLE
VideoPress: Playback bar colors setting not working with custom colors

### ISSUE THREAD

**Issue by CGastrell** [Automattic/jetpack#33976]
Forum entry: https://wordpress.org/support/topic/playback-bar-colors-setting-not-working-with-custom-colors/

**Comment by maciejpilarski** [comment]
@CGastrell just wanted to double-check if you would like PA’s to triage that issue as usual.
If yes, do you have any specific steps to reproduce that we can follow?

**Comment by CGastrell** [comment]
> @CGastrell just wanted to double-check if you would like PA’s to triage that issue as usual. If yes, do you have any specific steps to reproduce that we can follow?

Hey, thanks! Sadly all I have is what the forum entry reads, not sure if it's an issue at all

**Comment by davemart-in** [comment]
Single request. No updates in about a year. Going to mark this as "Won't fix".
