### ISSUE TITLE
Boost: Fix e2e page speed mock

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#34015]
e2e instance has an error caused by mocking page speed requests, while trying to fetch history page speed scores:

![Image](https://github.com/Automattic/jetpack/assets/11799079/42d66196-011d-46d2-af0c-fdfda6ced025)

To reproduce, run the e2e WP instance and access the Jetpack Boost dashboard.

**Comment by thingalon** [comment]
I see we don't currently have E2E errors. Does that mean this has been fixed, or have I misunderstood the problem?

**Comment by thingalon** [comment]
@dilirity - is this still relevant?

**Comment by dilirity** [comment]
It appears this has been fixed. Closing.
