### ISSUE TITLE
Enhancement: Allow disabling of transition_post_status action in Jetpack_Sync_Module_Posts module.

### ISSUE THREAD

**Issue by plainviewp1206** [Automattic/jetpack#34024]
### Impacted plugin

Social

### What

Allow disabling of sync most posts transition_post_status action via code

### How

Previously to version 12.7, one could disable the Jetpack_Sync_Module_Posts _transition_post_status_ action in the module by using the following code:

```
    global $wp_filter;
    $hook = 'transition_post_status';
    $filters = $wp_filter[ $hook ];
    if ( is_object( $filters ) )
        $filters = $filters->callbacks;
    else
        return;

    foreach( $filters as $priority => $callbacks )
    {
        foreach( $callbacks as $callback )
        {
            // We're looking for a class.
            $function = $callback[ 'function' ];
            if ( ! is_array( $function ) )
                continue;
            $callback_class = $function[ 0 ];
            if ( ! is_object( $callback_class ) )
                continue;
            // We are looking for Jetpack.
            if ( get_class( $callback_class ) != 'Jetpack_Sync_Module_Posts' )
                continue;
            $function_name = $function[ 1 ];
            // And this specific function.
            if ( $function_name != 'save_published' )
                continue;

            // Found it. Remove it.
            $this->debug( 'Removing transition_post_status action for the post sync module.' );
            remove_action( $hook, $callback[ 'function' ], $priority, $callback[ 'accepted_args' ] );
        }
    }
```

It worked with 12.4 but no longer works in 12.7

How would one disable the action nowadays?

(This issue is related to https://wordpress.org/support/topic/disable-jetpack_sync_module_posts-action/)

**Comment by jeherve** [comment]
I'm surprised this has worked for so long, we moved away from that `Jetpack_Sync_Module_Posts` class 4 years ago, in Jetpack version 7.5.

That code now lives in [the Jetpack Sync package](https://packagist.org/packages/automattic/jetpack-sync), under the `Automattic\Jetpack\Sync\Modules` namespace:
https://github.com/Automattic/jetpack/blob/0cdc4131c3c01ac1d0f56803d23652ed3fc43e7f/projects/packages/sync/src/modules/class-posts.php#L146C56-L146C70

Could you tell us more about what problem you're trying to solve by customizing the behavior of Sync that way? Is there an issue that we could solve on our end to help you so you wouldn't have to make changes to the default Sync behavior?

Thank you!

cc @fgiannar fyi

**Comment by plainviewp1206** [comment]
I am the author of the [Broadcast](https://wordpress.org/plugins/threewp-broadcast/) plugin. It duplicates posts between sites on a WP Network.

It works by switching to each site, and wp_insert_post the original post.

If broadcasting the post to, say, 5 sites, the problem is that jetpack users have the original post posted to facebook 6 times (original + 5 copies).

Previously I used to disable the transition_post_status action in the social module, but users report that my code no longer disables the action and users are again getting the 5 dupes to their facebooks.

What I need to do is tell jetpack to not post anything anywhere for the rest of the request. Stop reacting to wp_insert_post.

**Comment by jeherve** [comment]
Thanks for the extra details!

If you'd like to disable Publicize (auto-posting when a post is published), you should be able to do it without having to make any changes to the Sync process. That may be easier. You could try using the `publicize_should_publicize_published_post` filter for example:
https://developer.jetpack.com/hooks/publicize_should_publicize_published_post/

Would that work for you?

**Comment by plainviewp1206** [comment]
The filter worked excellently! Exactly what the doctor ordered.
