### ISSUE TITLE
Feature Request: Disable newsletter emails on a post by post basis 

### ISSUE THREAD

**Issue by websitehelperuk** [Automattic/jetpack#34061]
### Impacted plugin

Jetpack

### What

Disable Jetpack newsletter emails  on a post by post basis 

### How

There is no way to stop emails being sent out every time a new post is published. This is highly irritating for us managing busy publications. Please implement or provide a workaround so that not every post ends up in our subscribers inboxes.

**Comment by jeherve** [comment]
Thanks for the suggestion. This is currently tracked in this issue: #10876.

I'll consequently close this one as duplicate.
