### ISSUE TITLE
Nova menus: PHP notices when no Labels or Sections are defined

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#3407]
- Menus throw a lot of PHP notices in list view in admin:
```
Notice: Trying to get property of non-object in /jetpack/modules/custom-post-types/nova.php on line 736
Notice: Trying to get property of non-object in /jetpack/modules/custom-post-types/nova.php on line 740
Notice: Trying to get property of non-object in /jetpack/modules/custom-post-types/nova.php on line 753
Notice: Trying to get property of non-object in /jetpack/modules/custom-post-types/nova.php on line 754
Notice: Trying to get property of non-object in /jetpack/modules/custom-post-types/nova.php on line 758
Notice: Trying to get property of non-object in /jetpack/modules/custom-post-types/nova.php on line 759
Notice: Trying to get property of non-object in /jetpack/modules/custom-post-types/nova.php on line 762
Notice: Trying to get property of non-object in /jetpack/modules/custom-post-types/nova.php on line 768
Notice: Trying to get property of non-object in /jetpack/modules/custom-post-types/nova.php on line 491
Notice: Trying to get property of non-object in /jetpack/modules/custom-post-types/nova.php on line 732
```

To reproduce, you need to have `WP_DEBUG` set to `true`:
1. make sure you don't have any Section or Label
2. create a new menu clicking Add One Item
3. go back to Menu Items and the notices will appear

- Additionally, when `WP_DEBUG` is not set to `true`, no notices are displayed but the buttons UP and DOWN both lead to a blank page with the text
```
Are you sure you want to do this?

Please try again.
```

- Finally, when editing a menu, you can't deselect the first category, even if there is another category already checked. You can select/deselect others but the first one is fixed.

**Comment by nimatg** [comment]
Hey, @jeherve I am using Jetpack version 4.5 and this issue still exists xD

**Comment by jeherve** [comment]
@nimatg Thanks for the report!

Are the notices the same, referring to the same lines?

Could you also let us know the steps to reproduce the issue? Are they different from the ones reported above?
