### ISSUE TITLE
AI Free requests: enable GPT-4 Turbo with limited context window

### ISSUE THREAD

**Issue by p3ob7o** [Automattic/jetpack#34102]
To increase the quality of the free AI experience, activate GPT-4 Turbo, but with a context window limited to 8k for free requests.

 This is not a blocker to launching the AI Tiered Plans and can be done just after.

**Comment by CGastrell** [comment]
Under testing: D131493-code

**Comment by lhkowalski** [comment]
Closed by D131493-code.
