### ISSUE TITLE
Sharing block: ensure that we do not load resources on the frontend unless needed

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#34108]
The Sharing Buttons block currently requires the `Sharing_Service` class:
https://github.com/Automattic/jetpack/blob/bb1b509ebab88c7f355d8ec8611b699b5e171c04/projects/plugins/jetpack/extensions/blocks/sharing-buttons/sharing-buttons.php#L15

As a result, the sharing buttons' CSS gets enqueued, even if you haven't set up any buttons yet.
https://github.com/jeherve/jetpack/blob/193e017dbfbfbdd2b78dd5f843357d1d04892c38/projects/plugins/jetpack/modules/sharedaddy/sharing-service.php#L907-L908

As we continue to iterate on the new block, we'll need to ensure we do not needlessly enqueue those styles.

********

Epic: #19694

**Comment by andrii-lysenko** [comment]
Fixed in https://github.com/Automattic/jetpack/pull/34181
