### ISSUE TITLE
Contact Form: get_compiled_form() does not check if $feedback is a WP_Post object

### ISSUE THREAD

**Issue by barryceelen** [Automattic/jetpack#34125]
### Impacted plugin

Jetpack

### Quick summary

The [Automattic\Jetpack\Forms\ContactForm\get_compiled_form()](https://github.com/Automattic/jetpack/blob/d3136e54fe4733f5a63ef8125e28bbe44b45fce6/projects/packages/forms/src/contact-form/class-contact-form.php#L502) function assumes that [$feedback is a WP_Post object](https://github.com/Automattic/jetpack/blob/d3136e54fe4733f5a63ef8125e28bbe44b45fce6/projects/packages/forms/src/contact-form/class-contact-form.php#L529). This is not necessarily the case. eg. for legal reasons we're deleting feedback posts if they are not marked as spam and sent out via email. The `get_compiled_form()` function in that case does not actually find a post, triggering a PHP `Warning: Attempt to read property "post_content" on null`.

### Steps to reproduce

```
// Delete feedback post after sending a message.
add_action(
	'grunion_after_message_sent',
	'prefix_remove_sent_message',
	99
);

function prefix_remove_sent_message( $post_id ) {

	$post = get_post( $post_id );

	if ( is_a( $post, '\WP_Post' ) && 'feedback' === $post->post_type ) {

		// If the message is spam, then don't delete the message.
		if ( 'spam' === $post->post_status ) {
			return;
		}

		wp_delete_post( $post_id, true );
	}
}
```

### A clear and concise description of what you expected to happen.

The `get_compiled_form()` function should check if the `$feedback` variable is a `WP_Post` object before using `$feedback->post_content`.

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by jeherve** [comment]
Thanks for the report!

Could you let me know if #34129 fixes the issue for you?

**Comment by barryceelen** [comment]
Hi @jeherve this works great, thank you!
