### ISSUE TITLE
Blocks: Use `apiVersion: 3`

### ISSUE THREAD

**Issue by fabiankaegy** [Automattic/jetpack#34120]
### Impacted plugin

Jetpack

### What

Update `apiVersion` of every Jetpack block to version 3

### How

Currently the blocks primarily still use `apiVersion` 1 which blocks usage of the iFramed blocke editor on the edit post screen.

**Comment by jeherve** [comment]
Thanks for the suggestion!

Related projects: #32602 and #17099.

We were just talking about this a few days ago here:
https://github.com/Automattic/jetpack/pull/33883#discussion_r1379250337

Right now, all new blocks are set to use `apiVersion` version 1, but we should definitely consider changing that to version 3.

On the to-do list to make that happen:

- [x] Edit the `save` and `edit` functions in the templates to include `useBlockProps();`: https://developer.wordpress.org/block-editor/reference-guides/block-api/block-edit-save/
- [x] Complete #17099 so block views can be handled with `apiVersion` version 3.

**Comment by anomiex** [comment]
> Complete [Block Infrastructure: allow building blocks separately #17099](https://github.com/Automattic/jetpack/issues/17099) so block views can be handled with `apiVersion` version 3.

We may not need to wait for that. As long as we make sure that the `editor.js` monolith (and any other relevant styles/scripts, if any) does get loaded in the iframe it should be ok.

**Comment by fabiankaegy** [comment]
For what it's worth (this is not thorough QA but just light clicking arround)

I appleid this filter here: 

```js
import { addFilter } from '@wordpress/hooks';

addFilter('blocks.registerBlockType', 'namespace/change-api-version', (settings, name) => {
	return {
		...settings,
		apiVersion: 3,
	};
});
```

And the Jetpack blocks I testes all worked as they should... So I think the API version can get incremented before the full migration over to the hooks based approach. But I might totally be wrong :) So testing is definitly required

**Comment by fabiankaegy** [comment]
Especially with some of the enhancements in WordPress 6.5 I'd really love to see this get prioritized. Jetpack is blocking the adoption of the iFramed editors for a lot of our sites :(

**Comment by ellatrix** [comment]
Would be great if this is prioritised.

**Comment by kraftbj** [comment]
I'm hesitant to get this in before Wednesday's release, but it sounds like it creates a soft incompatibility with WP 6.5. I'm going to upgrade this to `blocker` so we can ensure we consider it for the Wednesday release, add in a "planned" point release, or if we get it in the May release.

Changing from enhancement to bug for the same compatibility rationale.

**Comment by ellatrix** [comment]
Nothing changed with 6.5, this was relevant for previous releases as well. But it still means activating Jetpack removes the iframe around the content and introduces styling issues. Jetpack is a super popular plugins so imo this should be fixed asap.

**Comment by jeherve** [comment]
Closing, as this project is now complete ; all blocks have been updated.

**Comment by fabiankaegy** [comment]
Thank you all for taking this on :)
