### ISSUE TITLE
Blaze off toggle

### ISSUE THREAD

**Issue by Back2Front** [Automattic/jetpack#34133]
### Impacted plugin

Jetpack

### What

Blaze should be able to be easily switched off in UI.

### How

Some modules of Jetpack are not needed. Can no longer even find the modules list with toggles. Blaze is especially crowding the already crowded post/page lists.

**Comment by jeherve** [comment]
If you'd like to disable the Blaze feature, you can go to Jetpack > Settings, and either search for "Blaze" or go to the Traffic tab. You will be able to turn off the Blaze feature there.
