### ISSUE TITLE
Paywall block: frontend popup shows paid plans that cannot be selected

### ISSUE THREAD

**Issue by edanzer** [Automattic/jetpack#34140]
### Impacted plugin

Jetpack

### Quick summary

Discussion of this issue on slack: p1699901671466339/1699898012.697669-slack-C052XEUUBL4

If you have paid plans on a newsletter site, and add a paywall block requiring paid subscription, you get the popup that allows you to select a paid plan. We noticed that we're showing some plan options that the reader cannot select. 

Looks like: 
<img width="1489" alt="subscribe-pay-modal" src="https://github.com/Automattic/wp-calypso/assets/21228350/ab2eb3fd-38ea-46e5-ab96-9a5a20b0443b">

### Steps to reproduce

1. On a test site, connect stripe and set up paid plans. Create a mix of plans with different tiers.
2. Add a paywall block to a post and set it to be limited to paid subscribers. Set the required plan to be a higher plan. 
3. Go to frontend in incognito browser, click to gain access, and you will get the popup. 
4. You'll see lower tier plans that you cannot select in the payment popup. 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by edanzer** [comment]
Update: The design of this (showing unselectable plans) was intentional based on prior discussions. Talking now about whether that should be changed, but would require some design discussion. 

See convo on slack: p1700070549210769/1700069976.526509-slack-C01B6KEJ5GE

**Comment by lsl** [comment]
Closing stale, not a bug per above.
