### ISSUE TITLE
Contact Form Submission Success message is mostly blank for users that aren't logged in

### ISSUE THREAD

**Issue by Andrewpk** [Automattic/jetpack#342]
On successful submission of a contact form, for users that aren't logged in they will not see the details of their contact form submission due to the `wp_nonce_field()` only being executed on `if ( is_user_logged_in() )`.

This leads users who aren't logged in to believe that their contact form has been submitted improperly or possibly hasn't been submitted at all.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. The problem was not reported again. We can always reopen in the future if needed.
