### ISSUE TITLE
Image Size Analysis: Add "Analyze Again" Option to Image Size Analysis Report

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#34200]
### Impacted plugin

Boost

### What

I would like to be able to trigger a new analysis from the report view

### How

We present the new analysis option in the Boost settings:

![Annotation on 2023-11-18 at 09-52-53](https://github.com/Automattic/jetpack/assets/45246438/5c9e4c89-bfcd-44f7-93ca-ee0b5f243ba0)

I would like to be able to trigger this from the Image Size Analysis Report:

![Annotation on 2023-11-18 at 09-53-34](https://github.com/Automattic/jetpack/assets/45246438/2d1e8a07-ee3b-44ea-ad63-65c6f4ac6e28)

**Comment by thingalon** [comment]
🤔 If we add this option, what would happen when you click it? Would it send you back to the Boost dashboard while the process warms up and begins again?

Just thinking it through.

**Comment by bobmatyas** [comment]
I imagined it would trigger a re-run of the process. Could the same component be used on that page as the dashboard?

![Screenshot on 2024-01-29 at 05-39-10](https://github.com/Automattic/jetpack/assets/45246438/9183a892-d34d-4751-986a-31593d5bf19e)

**Comment by haqadn** [comment]
It was added.
