### ISSUE TITLE
PBE attachment + Protect deactivate = Some attachments were rejected from the following WordPress.com Post by Email

### ISSUE THREAD

**Issue by MuhammadMahdiHusayni** [Automattic/jetpack#3422]
When using PBE from Gmail, image attachment are rejected
I have turned off Protect module and the image size is 6kb. I also turned off all other security wp plugin. 
Instead, the following errors show up:

Some attachments were rejected from the following WordPress.com Post by Email:
http://iclub-kpmi.com/wp/?p=115
 - test.jpg - Invalid response from the Jetpack site

im using wordpress 4.4.2, theme morning monday lite 1.07

**Comment by jeherve** [comment]
I can't seem to access your site at the moment.

Can you please use Jetpack's Debugger module to send us some more information about your site?

1. Go to the Jetpack page in your dashboard.
2. Click on the Debug link appearing at the bottom of the page.
3. Click the link that says "click here to contact Jetpack support."
4. Fill in the description box and your name and email address.
5. Click the "Contact Support" button.

Thanks!
