### ISSUE TITLE
Status > Modules: update module checks to be aware of WordPress.com Simple

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#34231]
The Status package includes a `Modules` class that can be very handy to check whether a specific Jetpack module is active:
https://github.com/Automattic/jetpack/blob/c100a09efb6c4c59029fc3e16ac0560bd1cf978c/projects/packages/status/src/class-modules.php#L21-L27

Unfortunately, those tools are not compatible with WordPress.com, where modules are always active and where you do not need to check for Jetpack options (nor should you, that won't work).

Today, we work around that problem by adding a condition along with the module check, like in #34229. 
Ideally, that condition should be baked in the Module class.

**Comment by pgk** [comment]
@jeherve if #34248 addresses this, I can abandon #34229 in favor of the more generic solution.
