### ISSUE TITLE
Related Posts: add list of post IDs to WP REST API Post responses

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3424]
The WordPress.com REST API includes the `/sites/$site/posts/$post/related` endpoint, that we use to get related post IDs for a specific post. We then use the `_jetpack_related_posts_cache` post meta to store the IDs of each Related Post locally.

It's useful, but that data can't be accessed by the core WP REST API.

It would be nice if we could register a new field in the API to expose these post IDs, maybe in a `jetpack-related-posts` array under `wp-json/wp/v2/posts/$post`.

This would make it easier for folks developing themes using the WP REST API, and wanting to use Jetpack Related Posts without having to do remote queries to the WordPress.com REST API and handling caching themselves.

**Comment by ziyafenn** [comment]
Hey guys, don't know if this is related, but seems to be related custom post types are not added to the REST API when related default post types are.
@zinigor
