### ISSUE TITLE
Multiple "activate photon" messages when uploading media

### ISSUE THREAD

**Issue by robfelty** [Automattic/jetpack#3426]
> What I expected
On my self-hosted site, when I upload some images, I see several "activate photon" boxes. I would expect at most to see 1

> What happened
I see several "activate photon" buttons

> Steps to reproduce the issue
Start a new post, add media, see multiple buttons
![screen shot 2016-02-18 at 10 34 41](https://cloud.githubusercontent.com/assets/19924/13152255/7c14ff22-d62b-11e5-8d8d-957626bc0a13.png)

I am using WP 4.4.3 and Jetpack 3.9.1

### Are you in the right place?

- This issue tracker is not for support. If you have questions about Jetpack, you can [start a new thread in the Jetpack support forums](http://wordpress.org/support/plugin/jetpack#postform), or [send us an email](http://jetpack.me/contact-support/).

- Do not report potential security vulnerabilities here. For responsible disclosure of security issues and to be eligible for our bug bounty program, please submit your report via [the HackerOne portal](https://hackerone.com/automattic).

Screen recording here: https://cloudup.com/cZNoBIk2ICZ

**Comment by jeherve** [comment]
Fixed in #3351. The fix will be part of the next Jetpack release.
