### ISSUE TITLE
Google Fonts failing to load on WoA with a certain theme

### ISSUE THREAD

**Issue by rinazrina** [Automattic/jetpack#34288]
### Quick summary

Selecting one of Google Fonts, such as Cormorant or Texturina for a Paragraph block doesn't change the font style on the editor and on the live page. 

### Steps to reproduce

1. On a WoA site, activate Bitácora theme
2. Add some text to a Paragraph block in a post or a page
3. Select one of Google Fonts for that paragraph, such as Cormorant or Texturina
4. The font doesn't change on the editor and on the published version

Note that I can not reproduce this on my test sites. But I can reproduce the issue on the user's site with only Jetpack and Bitácora theme active. When the theme is switched to Twenty Twenty, the font displays as expected. 

This issue might be related to this one: p1699560154373519-slack-C02FMH4G8

### What you expected to happen

The selected font will display 

<img width="752" alt="Screenshot on 2023-11-24 at 11-31-02" src="https://github.com/Automattic/wp-calypso/assets/33721365/ec9a3e52-d311-4138-81ba-b77219370fd6">

### What actually happened

The selected font is not displaying. It's showing a default Serif font instead. 

**Screenshot of the editor version:** 

<img width="1352" alt="Markup 2023-11-24 at 11 27 02" src="https://github.com/Automattic/wp-calypso/assets/33721365/5714b9d7-353f-453c-8a16-6d319c9fe66b">

**Screenshot of the published version:** 

<img width="724" alt="Screenshot on 2023-11-24 at 11-28-13" src="https://github.com/Automattic/wp-calypso/assets/33721365/f3300f95-b82f-44e8-880f-192fae15920b">

### Impact

Some (< 50%)

### Available workarounds?

~No but the platform is still usable~ edited by @Nic-Sevic 25/11

a functional workaround seems to be to just import the font via custom css, like so:

```
/* fix missing font bug {ticket #} {HE name}*/
@import url('{font link from google}');
```

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Only reproducible on the user's site with Bitácora theme active. 
User report: 7349464-zd-a8c

**Comment by Nic-Sevic** [comment]
related issue: https://github.com/Automattic/themes/issues/7507

Also @Robertght  shared two other cases: 
7352539-zd-a8c Theme: Munchies
7337833-zd-a8c Theme: Vivre

**Comment by liviopv** [comment]
Moved here https://github.com/Automattic/wp-calypso/issues/84611#issuecomment-1830104305

**Comment by arthur791004** [comment]
We merged https://github.com/Automattic/jetpack/pull/34306 and it will be included in the next release of Jetpack. In addition, we also synced the changes to https://github.com/Automattic/wpcomsh/pull/1587 so the issue should be resolved now 🎉

**Comment by liviopv** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/84611
