### ISSUE TITLE
Twitter Cards: Add "player" card type

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#3428]
We could use the `player` card type to present posts with media a bit better on Twitter. For example, if the post format is something like `video` or `audio` Jetpack could scan the post content for links to such files and present them in the Twitter tags.

Not sure how feasible this is, but it came up in #2542017-t, so just throwing it out here.

**Comment by kraftbj** [comment]
The `player` type requires approval with [some special requirements over other types](https://dev.twitter.com/cards/types/player/approval). My first thought is add some filters to make this easier/trivial for folks who are good jumping through the hoops.

https://github.com/Automattic/jetpack/blob/3.9.1/class.jetpack-twitter-cards.php#L49-L84

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
