### ISSUE TITLE
Subscriptions: allow posting only to a certain category

### ISSUE THREAD

**Issue by vporton** [Automattic/jetpack#34296]
### Impacted plugin

Jetpack

### What

I would like post to email only a certain category

### How

The “Subscribe to blog” widget should have an optional category selector with the purpose to send emails only for posts in this category.

I am going to generate many posts with AI, but sending all of them in email list would be an overwhelm. I want to send only manually created posts.

**Comment by jeherve** [comment]
Thank you for your suggestion!

You'll be happy to hear that we're working on such a functionality, nicknamed "Newsletter Categories". We'll post on the Jetpack Blog and mention it in the plugin's release logs as soon as this feature becomes available.

*******

Somewhat related: #10876

**Comment by braddalton** [comment]
Is this done already? Or do i need code?

**Comment by simison** [comment]
Hi! Yes, it's now possible to allow subscribers to subscribe specific categories only. See Jetpack -> Settings -> Newsletter for how to set this up.

You can also write blog posts and not have them send as emails at all, [see this documentation for details.](https://jetpack.com/support/newsletter/#post-email-vs-post-only-options)
