### ISSUE TITLE
Uses deprecated APIs

### ISSUE THREAD

**Issue by halilesen** [Automattic/jetpack#34304]
Hi,
When I analyze the page, I get the warning "Uses deprecated APIs" (CSSValueAppearanceNonStandard). When I look, I see this: The keyword 'push-button' specified to an 'appearance' property is not standardized. It will be removed in the future.

Is this related to Jetpack and how do I solve it?

**Comment by jeherve** [comment]
Could you give us more details about the issue? On which page do you see that warning, what do you use to "analyze the page"?

Could you also post your site URL here, so I can have a look?

If you want it to remain private, you can also contact us via this contact form:
http://jetpack.com/contact-support/?rel=support

Edit: looking at #34301, maybe the tool you're using is Google Pagespeed insights?

**Comment by halilesen** [comment]
Yes, Google Pagespeed insights.

**Comment by jeherve** [comment]
I also saw your forum thread here:
https://wordpress.org/support/topic/uses-deprecated-apis-4/

> The keyword ‘push-button’ specified to an ‘appearance’ property is not standardized. It will be removed in the future.

Jetpack doesn't use `push-button` for `appearance` anywhere, so this warning must come from a different plugin or your theme on your site. I would recommend investigating further.
Jetpack does use `push-button` in one place, when using the Ads feature, but we only use it with a vendor prefix, as expected:
https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/scss/cleanslate.scss#L285
