### ISSUE TITLE
[Boost] Add caching headers to concat/minified CSS/JS

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#34303]
When we serve concatenated/minified JS, we can (and probably should) supply headers which tell the browser to cache the content for a long time.

**Comment by dilirity** [comment]
We're already providing cache headers when serving concatenated content:

https://github.com/Automattic/jetpack/blob/f2f883c2efbf40d1aff04ec4f41e04e1b8ddfd6d/projects/plugins/boost/app/lib/minify/functions-service.php#L94-L95

For subsequent requests, if there's no change in content (for example, cache file doesn't get deleted), we send 304:

https://github.com/Automattic/jetpack/blob/f2f883c2efbf40d1aff04ec4f41e04e1b8ddfd6d/projects/plugins/boost/app/lib/minify/functions-service.php#L76

**Comment by dilirity** [comment]
@haqadn bringing you in the loop. I think we can close this as it's already handled.
