### ISSUE TITLE
Related Posts: add option to customize heading level

### ISSUE THREAD

**Issue by halilesen** [Automattic/jetpack#34301]
### Impacted plugin

Jetpack

### What

related posts titles...

### How

When I analyze the page with PageSpeed ​​Insights, an error appears: Title elements are not sorted in descending order.

![image](https://github.com/Automattic/jetpack/assets/73847687/c698e20a-e679-46e0-921a-32b6b69759bb)

The reason for this is that related posts names are `<h4....`

Converting them to div seems like the solution. Which file should I edit to do this manually?

**Comment by halilesen** [comment]
Okey. edit line 1962 in /wp-content/plugins/jetpack/modules/related-posts/jetpack-related-posts.php file. Problem solved. The only problem is if you don't support it I will have to repeat it every update.

**Comment by jeherve** [comment]
As you can see on the line you highlighted, there is a filter you can use to change the heading level to match your site's needs.

You can use that filter in a functionality plugin, as explained here:
https://jetpack.com/support/adding-code-snippets/

You can read more about the filter and find an example on how it can be used here:
https://developer.jetpack.com/hooks/jetpack_relatedposts_filter_post_heading/

**Comment by halilesen** [comment]
Thank you...
