### ISSUE TITLE
Sharing: add notice in Calypso Sharing settings to explain that this doesn't impact the sharing block

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#34327]
In Calypso > Tools > Marketing > Sharing buttons, when the sharing module is active and the site uses a block-based theme, we should gray out sharing settings and display a notice inviting folks to go to the site editor to configure sharing on their site using the new sharing block.

<img width="1089" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/43891f9c-27ff-491a-a57d-4a6368d0ffa5">

Related: #34326 

Epic: #19694

**Comment by keoshi** [comment]
Awaiting for the discussion on https://github.com/Automattic/jetpack/issues/34326 so we know how to proceed here.

**Comment by keoshi** [comment]
Sorry for the delay @jeherve — was feeling unwell yesterday.

What do you think about this?

![image](https://github.com/Automattic/jetpack/assets/390760/6c6ea540-7937-48e7-b6ef-cc1ac440dd27)

Not liking it as much as https://github.com/Automattic/jetpack/issues/34326 to be honest. It's fine for a first iteration, but I really believe we have to do a much better job at guiding the user through the necessary steps.

Perhaps we could add a very short video to these pages in the future so they at least have a frame of reference.

**Comment by andrii-lysenko** [comment]
I'm planning to use `config feature flags` to have this shown up only when we need it.

**Comment by andrii-lysenko** [comment]
@keoshi hey, wanted to ask if you use Figma for this or some other tool?

**Comment by keoshi** [comment]
@andrii-lysenko Yeah, it's all Figma — do you need the link to the file?

**Comment by andrii-lysenko** [comment]
>do you need the link to the file?

Yeah, it could be helpful. Thanks!

**Comment by andrii-lysenko** [comment]
@keoshi With the buttons, is it ok to follow color pattern of other UI, or we want it blue?

![Image](https://github.com/Automattic/jetpack/assets/60262784/d533237c-c737-4c7b-a7da-ba802d2fa593)

Also, @jeherve, am I understanding correctly
`Go to site editor` button - Navigate to `/wp-admin/site-editor.php`?
`Learn how to add Sharing Button` button - dummy for now?

**Comment by jeherve** [comment]
> Go to site editor button - Navigate to /wp-admin/site-editor.php?

Yes. In #34619 I actuallly made it `site-editor.php?path=%2Fwp_template`

> Learn how to add Sharing Button button - dummy for now?

Yup. We'll have a doc at some point, see tracking issue here: #34621.

**Comment by keoshi** [comment]
> With the buttons, is it ok to follow color pattern of other UI, or we want it blue?

Let's follow the color of the active color scheme, the blue was just an example.

**Comment by andrii-lysenko** [comment]
Calypso PR: https://github.com/Automattic/wp-calypso/pull/85180
