### ISSUE TITLE
Sharing Block: switch new block to production

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#34324]
Epic: #19694.

**Comment by chrisbliss18** [comment]
Ensure that we communicate this change to Garage to ensure that testing is added.

**Comment by andrii-lysenko** [comment]
@jeherve @chrisbliss18 maybe we will first roll these out as `Experimental`, what do you think? Or `prod` but adding (Experimental) to the name?

**Comment by jeherve** [comment]
I'd go with `production` out of the box, as soon as the block is ready.

**Comment by andrii-lysenko** [comment]
We are holding off on this until we are done with Call For Testing.
