### ISSUE TITLE
Don't use site icon as fallback if it's less than requested size

### ISSUE THREAD

**Issue by ethitter** [Automattic/jetpack#3432]
The site icon I've set is 360px square (https://s2.e15r.co/wp-content/uploads/sites/2/2016/01/erick-bio.jpg). When choosing an image to use for OG tags, and perhaps in other places, the site icon is considered as a fallback if a post has no images. In the case of OG tags, the requested size is 512px. Core returns the URL for the sub-512px image, and Jetpack passes it on as a 512px square, causing distortion. Hint: no one wants to see my face _that_ closely. ;)

https://github.com/Automattic/jetpack/blob/80df2a3638e72a84ba225231d12713385470f5be/functions.opengraph.php#L340

> What I expected

Jetpack wouldn't use an image that was less than 512px when it wanted one that was 512px. Or that it would, at least, check that the image's size met its request.

> What happened

Jetpack told Facebook that a 360px image was actually 512px. Fortunately my parents are probably the only ones who saw the posts.

> Steps to reproduce the issue

Set a site icon less than 512px and share a post to Facebook that contains no other images. Bask in the pixelation.

**Comment by kraftbj** [comment]
Thanks! I was under the impression that Core didn't allow for sub-512 sizes, but haven't checked it out since Site Icon was midway through Core dev. We'll work it up and get it fixed.

**Comment by ethitter** [comment]
> I was under the impression that Core didn't allow for sub-512 sizes, but haven't checked it out since Site Icon was midway through Core dev.

That requirement must've been dropped, because I use the image linked in the issue with two or three sites on my network. ¯\_(ツ)_/¯
