### ISSUE TITLE
AI Logo Generator: Extend the logo block with base component under the beta flag

### ISSUE THREAD

**Issue by dhasilva** [Automattic/jetpack#34377]
The logo generator should be available as an extension of the logo block, just as the other extensions, under the beta flag.

ref kJj8rPzRgHXAMHzhsmrfpy-fi-3822_4345

Depends on https://github.com/Automattic/jetpack/issues/34376

**Comment by lhkowalski** [comment]
This is the idea illustrated on the Figma file:

<img src="https://github.com/Automattic/jetpack/assets/6760046/c39c0d65-88f0-48e7-8ded-0f9372e79011" width="200" />

When clicked, the AI icon will trigger the logo generator window. When the logo is ready, the user can set it on the block.

**Comment by lhkowalski** [comment]
Closing this in favor of smaller tasks on the board. The main epic is being tracked on the roadmap dashboard, item `1707`.
