### ISSUE TITLE
REST API Constant: 500 error when activating Monitor, error when logging in via SSO

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3443]
cc @enejb 

It looks like #3412 broke part of Jetpack's connection process. From the point that PR was merged, 2 things appear not to be working properly in Jetpack:

1. Trying to activate Jetpack's Monitor module returns a 500 error (nothing in the logs, unfortunately).
2. Trying to log in via Jetpack SSO returns the following error: 

> Error: This site's Jetpack connection is currently experiencing problems.

I was able to reproduce on 4 different sites, and `git bisect` pointed f305380f5b433e77a1f1c4b35e57feb6075765aa as the first problematic commit.

Could you take a look?

Thanks!

**Comment by kraftbj** [comment]
It appears that wp.com returns a 404 when a Host header is sent.

**Comment by dereksmart** [comment]
see #jetpack slack scrollback for discussion

**Comment by kraftbj** [comment]
Fixed via #3449

**Comment by kraftbj** [comment]
Confirmed able to activate `monitor` once again.

**Comment by enejb** [comment]
Thanks for double checking @kraftbj
