### ISSUE TITLE
Mastodon embed results in poorly formatted post lacking adequate styling

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/jetpack#34453]
### Impacted plugin

Social

### Quick summary

When embedding a Mastodon post using the post link, the resulting embed contains oversized logos and icons, in addition to the embedded post text. It looks like CSS is not being applied correctly to the elements of the embed.

### Steps to reproduce

1. Open a post or page in a WordPress.com site (I tested a free site)
2. Paste the link of a Mastodon post (I used [this link](https://mastodon.social/@wpcommaven/111527454567020216#.))
3. Observe the formatting

### A clear and concise description of what you expected to happen.

When embedding a Mastodon post, I'd expect to see an embed that more closely resembles the source post in terms of the proportions of the elements in the embed.

### What actually happened

Instead, this is what occurs:

![CleanShot 2023-12-05 at 16 36 04](https://github.com/Automattic/jetpack/assets/2912202/9a41e37c-8eac-482c-854a-1bf4c3b88429)

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Browser: Firefox Developer Edition v121.0b6 and Microsoft Edge
OS: macOS 14.1.2

**Comment by jeherve** [comment]
Those embeds are part of WordPress itself; they're not provided by WordPress.com or Jetpack. This specific issue is currently tracked here:
https://core.trac.wordpress.org/ticket/58120
