### ISSUE TITLE
Subscriber Pop-up Doesn't Trap Focus and Allows Background Scrolling

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#34461]
### Impacted plugin

Jetpack

### Quick summary

When enabled, the "Newsletter Settings > Subscriptions > Enable subscriber pop-up" allows you to navigate and scroll outside of the modal. 

### Steps to reproduce

1. Enable the subscriber pop-up
2. Visit site in a new private window and scroll until you see the newsletter pop-up
3. Scroll using mouse or keyboard and see that it scrolls the background
4. Tab through and see that it doesn't trap focus within the modal. 

### A clear and concise description of what you expected to happen.

- I expect the subscription pop-up would trap focus until dismissed

### What actually happened

You can use the mouse to scroll the page while the modal is open:

<img width="1734" alt="Screenshot 2023-12-05 at 14 26 17" src="https://github.com/Automattic/jetpack/assets/45246438/b1add681-7a26-4665-9ac7-4851fc3cd597">

![Screenshot_at_December_5th_2023_-_2 26 32_pm](https://github.com/Automattic/jetpack/assets/45246438/9546e3e1-5a05-4282-a54e-b6a8d4acd484)

The modal doesn't trap focus and you can tab out of it, which isn't expected behavior:

<img width="1361" alt="Screenshot 2023-12-05 at 14 27 12" src="https://github.com/Automattic/jetpack/assets/45246438/d6799382-73f9-4547-9c63-ed956fc31230">

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by bobmatyas** [comment]
@Automattic/zap Is this something you all can take a look at?

**Comment by simison** [comment]
Yep! We'll fix. Thanks for the heads up.
