### ISSUE TITLE
Site Logo: ensure compatibility with Core Site Logo feature

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3447]
Jetpack's [Site Logo](http://jetpack.me/support/site-logo) theme tool might be added to Core in WordPress 4.5.:
[#33755-core](https://core.trac.wordpress.org/ticket/33755)

If that happens, we'll need to make sure we handle fallback nicely, like we did for Site Icon.

**Comment by jeherve** [comment]
> If that happens

It happened in [r36698-core](https://core.trac.wordpress.org/changeset/36698)

Changing the milestone to 3.9.2, as we need to address this or we'll break the Customizer for all people using 4.5 Beta.

**Comment by kraftbj** [comment]
Quick notes. Our site-logo implementation uses options, core's uses `theme_mod`. The functions seem to do the same thing (e.g. core's `has_site_logo` returns bool like `jetpack_has_site_logo`, core's `the_site_logo` echos out the img tag like `jetpack_the_site_logo`.

If we can check `jetpack_has_site_logo` && `get_the_site_logo` exists (in core but not in Jetpack at all) then migrate the jetpack variant from the option to theme_mod, remove the option. If `get_the_site_logo` exists, then kill off our UI piece.

**Comment by westonruter** [comment]
FYI: I had to add a mu-plugin that does the following to fix the conflict between the Jetpack feature and the site logo in now core, by short-circuiting the Jetpack feature:

```php
add_action( 'after_setup_theme', function() {
	remove_action( 'init', 'site_logo_init' );
} );
```

**Comment by kraftbj** [comment]
Thanks Weston. We'll need to add a bit to transition the setting between the old and new (as we did with Site Icon). With Beta 2 tomorrow, we need to get on this pretty soon :).
