### ISSUE TITLE
Jetpack Social: failure with logging in to Nextdoor

### ISSUE THREAD

**Issue by foleynotrose** [Automattic/jetpack#34481]
### Impacted plugin

Jetpack

### Quick summary

When trying to log in to Next door, I get the error of: 

`Failed to load your request token while connecting to Nextdoor. Please try again in a moment.`

I try again several times and always get the same error. 

I was able to log in to my Nextdoor account in a browser without any problem. 

### Steps to reproduce

1. Activate Jetpack Social in Sharing Sessions 
2. Select "Connect accounts" 
3. Attempt to connect a Nextdoor account by entering username and password 

### A clear and concise description of what you expected to happen.

Either my Nextdoor account connects to Jetpack Social OR I get a clearer error message of what I can do to troubleshoot 

### What actually happened

Failed to load your request token while connecting to Nextdoor. Please try again in a moment.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by foleynotrose** [comment]
Update: I tried to test this with the Jetpack Social plugin only, but Nextdoor is not included as a connection for the standalone plugin. Is that expected?

**Comment by foleynotrose** [comment]
Update: I can connect with Nextdoor now; perhaps this was just a temporary glitch. (It was persisting for more than 10 minutes, so I filed the bug report.)

**Comment by jeherve** [comment]
> Update: I can connect with Nextdoor now; perhaps this was just a temporary glitch.

👍 Closing this issue now, we can reopen later if it starts happening again.
