### ISSUE TITLE
Top Posts Block: handle sites where Stats is inactive

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#34484]
Since the block relies on the Stats module, we would need to only make the full block available when the Stats module is enabled, and offer a way to turn on the module from the block settings when it is inactive.
We can check the different Pull Requests in #32401 to figure out examples of how this can be done.

*********

Epic: #32937

**Comment by Aurorum** [comment]
Thanks! I thought I did that though - am I misunderstanding the issue?

<img width="761" alt="0F3872FD-22A7-4A13-9E6F-D683C04F14F0" src="https://github.com/Automattic/jetpack/assets/43215253/c9d33bae-93b2-4d89-a4bf-d02387782079">

**Comment by jeherve** [comment]
Oh awesome, I had missed that you implemented it! 💥
