### ISSUE TITLE
Critical Error with Jetpack Social + Jetpack 12.9 

### ISSUE THREAD

**Issue by foleynotrose** [Automattic/jetpack#34486]
### Impacted plugin

Jetpack, Social

### Quick summary

With Jetpack 12.9 activated, activating Jetpack Social causes a critical or fatal error. 

### Steps to reproduce

1. Activate Jetpack 12.9 on a site 
2. Install and activate Jetpack Social 

### A clear and concise description of what you expected to happen.

It should be possible to use both Jetpack and the Jetpack Social plugins together 

### What actually happened

For me: 
1. a critical error appeared when I activated Jetpack Social. 
2. When I clicked back to plugins, Jetpack Social was shown as active, but if I tried to click on Settings, I was brought back to the Critical Error page. 
3. If I deactivated Jetpack, Jetpack Social Plugin works fine 
4. Another HE tested with Jetpack 13.0 beta and got a fatal error: 

![image](https://github.com/Automattic/jetpack/assets/26651984/45af55d3-06ca-4def-8c34-07690412105f)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by manzoorwanijk** [comment]
It's because the currently released version of Jetpack Social expects those methods in Jetpack plugin but those were removed in the last Jetpack release.
So, a new release of Jetpack Social should fix the issue.

**Comment by jeherve** [comment]
> those were removed in the last Jetpack release.

Related PR: #34241

Maybe those methods should be brought back and kept around for a few releases, with a deprecation notice, to avoid those kinds of conflicts? Folks running different versions of the 2 plugins is bound to happen, so I don't think we can expect everyone to be running the latest version of the 2 plugins at all times.

**Comment by anomiex** [comment]
I see a few things going wrong here.

1. The PR removed functions without considering that the current version of a plugin still used them. A deprecation process should have been followed, making sure not to remove the functions until no supported plugin versions use them anymore.
2. The PR flagged the change to the package as a "patch" semver bump. Deprecation of public API features needs at least a "minor" bump, while removal of public API functions needs to be "major".
3. Even if we had done a major bump, the package hasn't had its 1.0 release yet so it would have come out as 0.x anyway.
4. Even if we had had a major version number bump, the autoloader wouldn't do anything to try to give a useful error for the situation (see also #17221).
   * OTOH, making that actually work seamlessly in practice seems like it could be complex as we'd probably need a plugin release with a "^1.0 || ^2.0" dep to be compatible with the other plugin still having only a "^1.0" dep.

**Comment by pablinos** [comment]
> The PR removed functions without considering that the current version of a plugin still used them

This is the main thing. We didn't consider the conflicts in package versions and thought it was safe to remove as the correct package version would be alongside the plugin installed, but having a different version of Jetpack causes the issue.

> Maybe those methods should be brought back and kept around for a few releases, with a deprecation notice, to avoid those kinds of conflicts?

Perhaps, but with Jetpack having the most recent version of the packages, I don't think it would help that much until another Jetpack release. @kraftbj is doing a Jetpack Social release currently, so affected users will be able to upgrade to fix the problem.

**Comment by kraftbj** [comment]
Resolved via a new release (3.0.0, stable via https://plugins.trac.wordpress.org/changeset/3006232/ )
