### ISSUE TITLE
Enhancement: Customize Mastodon auto-share output

### ISSUE THREAD

**Issue by bixfrankonis** [Automattic/jetpack#34507]
### Impacted plugin

Social

### What

I would like to be able to suppress sending the post title

### How

Since the post title will already be viewable in the link card on Mastodon, I’d like to be able to set my auto-sharing to just use the excerpt, not the title and excerpt, so that the auto-shares present more conversationally. (Maybe this currently is possible using a custom function, but I had no response to that inquiry in the support forums.)

**Comment by jeherve** [comment]
Thanks for the feedback! Being able to customize the default shared message for all posts at once, to remove or add some items, is a popular request for the Jetpack Social feature. It's currently only possible via code snippets or manually for each one of your posts thanks to the Jetpack Social panel in the block editor sidebar, but one day we may add the option to change that default message for all posts at once via a new settings interface.
This potential improvement is tracked in #261, so I'll close this issue as duplicate.
