### ISSUE TITLE
Top posts: Title length limit

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#34505]
We should limit the length of the title and possibly wrap it too.

<img width="1132" alt="image" src="https://github.com/Automattic/jetpack/assets/1425433/bab38360-aa84-4a33-bed7-fa0e5c8e0d7b">

**Comment by Aurorum** [comment]
this also needs fixing - will try to push a fix tomorrow! 

<img width="683" alt="Screenshot 2023-12-06 at 23 38 24" src="https://github.com/Automattic/jetpack/assets/43215253/530515f8-3f3f-4c65-97a5-6d32ed435627">
