### ISSUE TITLE
Feature Request: Subscriber Options for Post Notifications

### ISSUE THREAD

**Issue by jcortx** [Automattic/jetpack#34513]
### Impacted plugin

Jetpack

### What

Allow a subscriber to change how often they receive emails from site/new content.

### How

From User: 

Currently, there is no option for a subscriber to choose when they receive emails from a site - the subscriber will receive emails immediately after a post is published. A subscriber should be able to change their preference via a link in the email that is sent like "manage your email preferences".

**Comment by jeherve** [comment]
You should be able to manage your subscription settings on this page:
https://wordpress.com/subscriptions/sites/en

There, you'll be able to choose whether you want to receive updates instantly, daily, or weekly:

<img width="548" alt="Screenshot 2023-12-07 at 15 35 28" src="https://github.com/Automattic/jetpack/assets/426388/a0ea6f48-907d-4c83-8e7e-1bc9a19c96ba">

If you'd like more options, you can also sign up for a WordPress.com account. Once you're logged in with WordPress.com and if you subscribe to a site using your WordPress.com account email address, you'll also have the option to not receive any email, but instead read the new posts in the WordPress.com Reader.

I hope this helps!
