### ISSUE TITLE
Feature Request: Option to Send Blog Notification Emails for Re-Published Posts

### ISSUE THREAD

**Issue by t-pabla** [Automattic/jetpack#34528]
### Impacted plugin

Jetpack

### What

Option to Send Blog Notification Emails for Re-Published Posts

### How

Currently the automated Blog Subscriber Notification Emails are not being sent out when a post is updated.

As a blogger myself, I find this very puzzling. Many of my blog posts 15 years old. In these 15 years, almost all my subscribers are new. But they don't get notified whenever I update and re-publish any of them.

It is common practice among bloggers to rewrite/update content and subscribers should be receiving the updated articles in the notification emails. It’s very frustrating to not have the option/control.

There seems to be no reason to why a republished/updated blog does not send a notification email to the subscribers.

This is an absolute must. If the blog is updated and then republished as a refresh it should be able to have the email to go along with it, just as any other post.

Hope jetpack consider adding this essential feature to the plugin.

**Comment by jeherve** [comment]
Thanks for the suggestion! We've purposefully avoided sending emails multiple times in the past, to avoid anyone accidentally triggering the emails multiple times when importing content, for example, or site owners spamming subscribers by sending the same email multiple times in a short period of time.

However, we are currently working on several improvements to the subscription flow, including #34321. This may help you in the future, by giving you control over whether a post notification should be sent directly in the block editor.

Thanks again for the feedback. I would recommend monitor the Pull Request above, and trying it out when it is eventually included in a future version of the Jetpack plugin!
