### ISSUE TITLE
Warning: Attempt to read property 'id' on null in Jetpack Forms

### ISSUE THREAD

**Issue by alexmigf** [Automattic/jetpack#34538]
### Impacted plugin

Jetpack

### Quick summary

An user reported an issue with a conflict between one of our plugins and Jetpack Forms, which I think you should fix on your side. 

This is the error:

> Warning: Attempt to read property 'id' on null in .../jetpack-forms/src/contact-form/class-admin.php on line 475

This is the affected line: https://github.com/Automattic/jetpack-forms/blob/40dba57b663df150cb83b9d89b0e703c4d69fac6/src/contact-form/class-admin.php#L475

And I think you should add a check for the screen object like you do here: https://github.com/Automattic/jetpack-forms/blob/40dba57b663df150cb83b9d89b0e703c4d69fac6/src/contact-form/class-admin.php#L452

### Steps to reproduce

One of our plugins opens a tab where the screen is not available, which triggers the error above.

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by jeherve** [comment]
Thanks for the report! Could you let me know what plugin I could use to reproduce the issue? It would help me test the fix in #34576

On your end, do not hesitate to test the fix and let me know if that works for you.

Thank you!

**Comment by alexmigf** [comment]
Hi @jeherve 

Actually it's a paid plugin, but I will test on my own and provide a PR if necessary then.

Thank you!

**Comment by alexmigf** [comment]
Thank you @jeherve !
