### ISSUE TITLE
Possible issue when writing long text in Jetpack Comments ? (contentWindow . size)

### ISSUE THREAD

**Issue by MisterWP** [Automattic/jetpack#3453]
Hi!
#### What I expected

Write a long comment in a website "http" using Jetpack Comments in Google Chrome.
#### What happened instead

Finally, the textarea truncate the text and the submit button comes hidden.
#### Steps to reproduce the issue

I obviously check everything about my website (css,...), not max-width / overflow:hidden / ... defined, but, curiously, without any update in my website, the problem happened overnight :-o so, I think, maybe an issue good to report you.

During my test to solve the issue, I discovered that maybe, the self-hosted website cannot get the "contentWindow".size inside the Jetpack Comments "iframe". Maybe a conflict of mixed content HTTP/HTTPS ? I don't know.
Here a screenshot : 
https://pbs.twimg.com/media/CbvnakKUMAAbMl4.png

I hope do not make you lose your precious time.

Good day & Kisses, all the team ! :+1:

**Comment by jeherve** [comment]
Thanks for the detailed report. We'll run some more tests.

Related: #2841

**Comment by mpeshev** [comment]
I can definitely reproduce the same problem on my blog. Recently, I've received several different reports for the same problem as well. Absolutely identical to what MisterWP has reported in the original issue.

**Comment by jeherve** [comment]
I believe this is now fixed with the last round of improvements to the Comments feature. Closing.
