### ISSUE TITLE
Daily Writing Prompts not translating on the Jetpack App

### ISSUE THREAD

**Issue by OmarFPG** [Automattic/jetpack#34556]
### Impacted plugin

Jetpack

### Quick summary

The daily writing prompts are shown in English even though the interface language is in another language.

This doesn't happen in the My Home section on WPcom sites, where if you switch the interface of your WPcom account to another language the prompt is shown in said language.

### Steps to reproduce

Open the Jetpack App, switch language to other than English, go back to "My Site" and check the Prompt section.

### A clear and concise description of what you expected to happen.

The prompt should show up in the interface language.

### What actually happened

The prompt still shows in English

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by jeherve** [comment]
Thanks for the report!

The Jetpack app is developed in other GitHub repositories, so it may be better to report the problem elsewhere:

- https://github.com/wordpress-mobile/WordPress-iOS
- https://github.com/wordpress-mobile/WordPress-Android

Do you think you could open a new issue in one of those repositories to let the team know about the problem? It would also be useful if you could add what version of the app you are currently using.

Thank you!

**Comment by OmarFPG** [comment]
Thanks for the heads-up! I'm opening this in the relevant repository! 🙂 (only the [Android](https://github.com/wordpress-mobile/WordPress-Android/issues/19769) one, I just installed the app on my iPhone and it works fine).

**Comment by bobmatyas** [comment]
It was reported here: https://github.com/wordpress-mobile/WordPress-Android/issues/19769
