### ISSUE TITLE
Publicize: Sharing to Facebook fetches wrong images

### ISSUE THREAD

**Issue by alex02** [Automattic/jetpack#3458]
#### What I expected
When Jetpack posts to Facebook to show the correct image from the post.

#### What happened instead
Since Facebook doesn't fetch the og:image for the first time, the share doesn't show the post image, but fetches an image from previous posts.

#### Steps to reproduce the issue
Lets say you have a cooking blog and obviously your recipes are with photos. Today you write a recipe for pizza. Tomorrow you write a recipe for soup and when you publicize it to Facebook you see your soup recipe with photo from the pizza post.

Maybe the plugin can first load the new post in the Facebook debugger and then share it so the corrent image is used.

**Comment by jeherve** [comment]
> Facebook doesn't fetch the og:image for the first time

Facebook can fetch the `og:image` the first time it visits the page. It's the default behaviour, and it can be improved by "pre-caching" images:
https://developers.facebook.com/docs/sharing/best-practices#precaching

We implemented this in Jetpack's Open Graph Meta Tags in #2104.

If you use a different plugin to manage Open Graph Meta tags on your site, I'd recommend getting in touch with them, and ask them if they can implement `og:image:width` and `og:image:height` Open Graph tags, if they don't already.

If you use Jetpack's OG tags and still experience issues with Publicize, could you [start a new thread in the WordPress.org support forums](http://wordpress.org/support/plugin/jetpack#postform) with more info about your site and some examples, or [send us an email](http://jetpack.me/contact-support/)?

Thanks.
