### ISSUE TITLE
Sharing Block: publish CfT

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#34596]
Publish Call For Testing for the block, to test on both wpcom simple and self-hosted.

Epic: #19694

**Comment by andrii-lysenko** [comment]
We are waiting on https://github.com/Automattic/jetpack/issues/34326 and https://github.com/Automattic/jetpack/issues/34325 prior to releasing a P2

**Comment by andrii-lysenko** [comment]
Call For testing P2 published: pdtkmj-2dQ-p2
