### ISSUE TITLE
Contact Form: Export to CSV loads a blank page

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/jetpack#3460]
**Expected:** I clicked the "Download" button to download my feedback form submissions and I expected to see a csv containing this data. 

**What happened:** Instead I was directed to a blank page in my browser window. However if I modified the contact form to include a checkbox and then submitted it and after this the download proceeded as normal. 

**Steps to reproduce the issue:**

1. Create a contact form with just two items: Name, Email Address.
2. Submit the form.
3. Export the data - a blank page appears.
4. Add a new field to the form so that it has a checkbox.
5. Submit the form again.
6. Export the data again. It works this time. 

The export also fails on WordPress.com sites.

**Comment by dereksmart** [comment]
likely suspect #3215
