### ISSUE TITLE
Enhancement: Add (recover?) the icon for Discord in the social icon block

### ISSUE THREAD

**Issue by mjaragon** [Automattic/jetpack#34626]
### Impacted plugin

Jetpack, Social

### What

I would like to have the Discord logo also available in the Social Icons block

### How

In the Social Icons Block, we have icons for most social platforms, but I can't find the one for Discord (see [their branding](https://discord.com/branding))

It looks like this was already added before (see #11093), but when searching for it in the block, nothing comes up: 
![Add-Discord-to-Social-Icons](https://github.com/Automattic/jetpack/assets/30312698/1625944d-0ac2-4108-b0e4-fd0bf7b64687)

**Comment by jeherve** [comment]
The Social Icons block is part of WordPress itself, and the Discord icon has not been added to that block yet. There is a tracking issue here though:
https://github.com/WordPress/gutenberg/issues/35487

I would recommend adding your vote to that issue! 👍
