### ISSUE TITLE
Connecting with 2FA enabled WordPress.com account leads to dead end

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#3465]
#If you try to connect Jetpack, and you login with 2fa wpcom account, you'll end up in this bleak wasteland:

![screen shot 2016-02-26 at 2 43 49 pm](https://cloud.githubusercontent.com/assets/2694219/13363516/cc099ce6-dc97-11e5-8231-283c822d876a.png)

Steps to reproduce:
1. logout of your wordpress.com account
2. On a non-connected site, click "Connect Jetpack"
3. On the following screen login with a 2FA enabled WordPress.com account
4. Confirm your 2FA.  ( I clicked the 'Confirm' button in the WordPress iOS app )
5. Wasteland

**Comment by jeherve** [comment]
Could you add a list of the steps you followed to get to that screen?

We fixed that same bug a couple of years ago, and I didn't know it was back.

**Comment by roccotripaldi** [comment]
Sure thing @jeherve - i added steps to the description.

**Comment by roccotripaldi** [comment]
I've found that this issue is limited to 2FA verifications via push notifications, and I have a fix in the works!

**Comment by roccotripaldi** [comment]
Fixed in r-135894

**Comment by jeherve** [comment]
cc @georgestephanis: @roccotripaldi just closed a `Whisky Ticket`. ;)
