### ISSUE TITLE
Subscribe pop-up Continue Reading link causes visitors to jump back to the top of the page

### ISSUE THREAD

**Issue by philnick206** [Automattic/jetpack#34684]
### Impacted plugin

Jetpack

### Quick summary

When visitors click on the Continue Reading link they are sent back to the top of the page, rather than being able to continue reading where they were on the page/post.

### Steps to reproduce

1. Visit any page/post with the subscribe pop-up enabled
2. Scroll down to see the pop-up
3. Click Continue Reading

### A clear and concise description of what you expected to happen.

I expected the pop-up to go away and to be in the same location on the post

### What actually happened

I was brought back to the top of the post and had to scroll back down. 

https://github.com/Automattic/jetpack/assets/51966986/4288d440-05ac-4e03-9986-38cbc25d7054

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by philnick206** [comment]
Reported originally in 7114710-zd-a8c

**Comment by pkuliga** [comment]
Closing it since it's already fixed: https://github.com/Automattic/jetpack/pull/34963
