### ISSUE TITLE
Payments Block: Payment Plan Deselected Upon Page Update

### ISSUE THREAD

**Issue by donalirl** [Automattic/jetpack#34686]
### Impacted plugin

Jetpack, mu wpcom

### Quick summary

When updating a page with a Payment button block on it, the payment plan gets deselected, and therefore the button disappears. 

### Steps to reproduce

1. Create a page with some text.
2. Add a Payment button block.
3. Select a payment plan.
4. Publish the page. Notice the payment button appears publicly.
5. Go back and make an edit to the text on the page.
6. Update the page. Notice the payment button is now gone from the public page.
7. Check the payment button block toolbar and the payment plan has been deselected.

Video of these steps below.

### A clear and concise description of what you expected to happen.

I expected my payment plan to stay selected and the button to stay on the page.

### What actually happened

The button disappears when making an edit on the page unrelated to the button. Video:

https://github.com/Automattic/jetpack/assets/30727666/f75b75a5-28ce-456f-90e5-d1e8e7052917

### Impact

All

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Encountered in #7430454-zen and recreated on a simple site on WordPress.com.

**Comment by retnonindya** [comment]
I got the same issue on a chat here: 7525853-zen -- The user requested to be followed up when the bug is fixed.

**Comment by hngdny** [comment]
Another report here: 7529473-zen

**Comment by connorhipps** [comment]
This may be a similar report: 7518082-zen

The user reports that when editing the Payment Block, all plan options disappear, and they have to restart each time. The button doesn't disappear, but the plans are erased. The timeframe seems to align.

**Comment by hacchism** [comment]
Another similar report here: 7554711-zen

The user requested to be followed up when the bug is fixed.

**Comment by jp-imagines** [comment]
Another report in 7559459-zd-a8c, and I was able to replicate this on a test site myself. (Edited to add: user is requesting a follow-up once fixed.)

This is a particularly irritating issue. Every time you make changes to a page, all payment buttons have their plan removed – for pages with multiple buttons, it's a headache to re-add the right payment plan every time. 

Escalating here: p1704820006645499-slack-C02FMH4G8
