### ISSUE TITLE
Jetpack: "Update Now" JITM Brings User to Dead End

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#34681]
### Impacted plugin

Jetpack

### Quick summary

The "Update Now" JITM brings a user to the Jetpack pricing page rather than updating the Jetpack plugin.

### Steps to reproduce

1. Install an outdated version of Jetpack
2. Click on "Update Now" JITM when it appears
3. Observe that the plugin isn't updated and that the user is stuck on the pricing page.

_Note: Jetpack was connected before clicking the JITM_

### A clear and concise description of what you expected to happen.

I expected the Jetpack plugin to be updated.

### What actually happened

JITM:

<img width="1485" alt="Screenshot 2023-12-15 at 17 28 07" src="https://github.com/Automattic/jetpack/assets/45246438/37b08314-2bc1-4d35-8969-087b2665b888">

Pricing page:

![Screenshot_at_December_15th_2023_-_5 28 52_pm](https://github.com/Automattic/jetpack/assets/45246438/951a7c72-ad14-4da3-bc10-53e0584cf836)

Users are prompted to add a plan, but there is no way to upgrade the plugin.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by jeherve** [comment]
Fixed in D132327-code.
