### ISSUE TITLE
WP classic style admin bar is broken when Jetpack “Notifications” module is off

### ISSUE THREAD

**Issue by rghedin** [Automattic/jetpack#34685]
### Impacted plugin

mu wpcom

### Quick summary

I have to use Jetpack since it's mandatory on WP.com, but I don't use any of its modules except for VaultPress, so I deactivated all of them. When I tried to change the WP admin bar to the classic one, it showed completely broken.

Later on, I found out that this happens when Jetpack “Notifications” module is off. If I turn it on, classic style admin bar shows as expected.

### Steps to reproduce

1. Open Jetpack modules page: `[site]/wp-admin/admin.php?page=jetpack_modules`.
2. Turn off “Notifications” module.
3. Go to hosting settings: `https://wordpress.com/hosting-config/[site]`.
4. Scroll to the bottom, change `Admin interface style` to “Classic style”.

### A clear and concise description of what you expected to happen.

A perfect admin bar, like this:

<img width="579" alt="Captura de Tela 2023-12-17 às 08 19 43" src="https://github.com/Automattic/jetpack/assets/19216581/8a290fd3-e81f-4361-a6df-77eac3d171da">

### What actually happened

A broken one, like this:

![Captura de Tela 2023-12-10 às 16 21 11](https://github.com/Automattic/jetpack/assets/19216581/0509d7e1-080e-4cfa-bf95-e0e24e2b63fd)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by OmarFPG** [comment]
Thanks for reporting and providing a workaround!
7431659-zen

**Comment by jeherve** [comment]
@Automattic/yolo Could you take a look at this?

Thank you!

**Comment by wojtekn** [comment]
@jeherve sure, I've opened a PR with a fix earlier today.
