### ISSUE TITLE
How to disable the Jetpack CDN ?

### ISSUE THREAD

**Issue by oix29** [Automattic/jetpack#34683]
Hello

I have a big problem with the images on my site, and it comes, after checking, from Jetpack.

The majority of the images on the products of my e-commerce store do not appear, after checking, they are hosted on https://i0.wp.com. 

I've deactivated everything in the settings, in boost, I've emptied my cache several times, and it's still the same thing!

The only time all my images appear correctly is when I deactivate Jetpack.

Is there any way to remedy this?

Thanks in advance.

**Comment by jeherve** [comment]
Hi there,

> they are hosted on https://i0.wp.com/.

That domain is indeed the one used by Jetpack's Image CDN. The feature can be disabled under Jetpack > Settings > Performance if you use the Jetpack plugin, or Jetpack > Boost if you use the Jetpack Boost plugin.

If the images do not appear when the feature is active, it may mean that something else on your site, or in your server settings, is blocking the CDN feature from accessing your images. It may be worth investigating to try to understand what's causing the issue.

Could you contact us via [this contact form](https://jetpack.com/contact-support/?rel=support&hpi=1)? Once we have more details about your site (what plugins you use, what are your Jetpack plugin settings, ...), we should be in a better position to help.

Thank you.
