### ISSUE TITLE
WPCOM's gallery-settings.js script is registered and enqueued on WPMS Dashboard pages (404/500 > internal recursion error)

### ISSUE THREAD

**Issue by renatofrota** [Automattic/jetpack#3468]
#### What I expected

Proper WPORG gallery script (from _inc directory) registered & enqueued instead of WPCOM's (or no script enqueued at all, as the page do not seems to need this particular .js file at all).
#### What happened instead

The WPCOM's gallery-settings.js is enqueued on various Dashboard pages, like Network Settings page in a WPMS enabled WP install (just an example, it happens on other pages).

The full Apache's backtrace:

---

[Sun Feb 28 03:34:24.252256 2016] [core:error] [pid 10357:tid 140704328181504] [client XXX.XXX.XXX.XXX:XXXXX] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://xxxxx.com/wp-admin/network/settings.php
[Sun Feb 28 03:34:24.252321 2016] [core:debug] [pid 10357:tid 140704328181504] core.c(3613): [client XXX.XXX.XXX.XXX:XXXXX] AH00121: r->uri = /wp-content/plugins/jetpack/gallery-settings/gallery-settings.js, referer: http://xxxxx.com/wp-admin/network/settings.php
[Sun Feb 28 03:34:24.252383 2016] [core:debug] [pid 10357:tid 140704328181504] core.c(3620): [client XXX.XXX.XXX.XXX:XXXXX] AH00122: redirected from r->uri = /wp-content/plugins/jetpack/gallery-settings/gallery-settings.js, referer: http://xxxxx.com/wp-admin/network/settings.php
[truncated - other 9 lines identical]

---

See function wp_enqueue_media() on functions.gallery.php (line 34).
#### Steps to reproduce the issue

Install WPMS
Install Jetpack
Enable it on a site(? not sure if necessary to reproduce)
Access Network Settings page (or other pages in Network's Dashboard - couldn't reproduce on subsite Dashboards).

**Comment by renatofrota** [comment]
I have further checked this and found the issue is my theme calling wp_enqueue_media() on Dashboard pages where jetpack-gallery-settings script is not registered yet (nor will be).

I know the theme is the culprit, but perhaps this can be prevented by including an additional check (for IS_WPCOM, maybe) before registering and enqueueing the WPCOM's .js file?

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
