### ISSUE TITLE
Update HTTPS debugging and "known issues" documentation

### ISSUE THREAD

**Issue by ntwb** [Automattic/jetpack#3469]
When debugging Jetpack via https://example.com/wp-admin/admin.php?page=jetpack-debugger a link is included to a "known issues" document, currently this is out of date in relation to HTTPS protocol usage.

#### What I expected

I expected to see up to date information regarding the use of HTTPS protocol with Jetpack:

Such as this from https://jetpack.me/support/getting-started-with-jetpack/troubleshooting-tips/

> 5. Do you use an SSL certificate on your site? Try adding the following to your site’s wp-config.php file:
> 
>> `define( 'JETPACK_SIGNATURE__HTTPS_PORT', 80 );`
>
> This works on hosts that have SSL terminate on a reverse proxy and the server itself is still listening on port 80 or something similar.
> 
> Alternatively, you could add this to your wp-config.php file (please not both!):
> 
>> `$_SERVER['SERVER_PORT'] = 443;`

> This sets the server port to 443 for the whole site.

#### What happened instead

The following is via the linked "known issues" document http://jetpack.me/support/getting-started-with-jetpack/known-issues/ and is **not** up to date:

> Web servers using ports other than 80
> 
> Jetpack expects your site’s web server to be listening on port 80. This is about 99.99% of the web servers in the world. Websites using ports other than 80 appear in this format:
> 
>> http://example.com:8080/
> 
> If your website does not use port 80, you will not able to use the full functionality of Jetpack.

**Comment by jeherve** [comment]
Good point. I updated our docs.

Thanks!

**Comment by ntwb** [comment]
Thanks :+1:
