### ISSUE TITLE
VideoPress: Fatal error with paid posts

### ISSUE THREAD

**Issue by richards1052** [Automattic/jetpack#34728]
### Impacted plugin

Jetpack

### Quick summary

Jetpack restricts access to the homepage.  Any links to post pages from the homepage generate a "critical error" message.  Disabling Jetpack restores full access.  THis is the error log my web host sent me:

I see Jetpack errors in the php log:
[17-Dec-2023 11:11:05 UTC] PHP Fatal error: Uncaught Error: Class ‘Automattic\Jetpack\Extensions\Premium_Content\Subscription_Service\Token_Subscription_Service’ not found in /home/virtualmin/richardsilverstein.com/public_html/wp-content/plugins/jetpack/modules/subscriptions/subscribe-modal/class-jetpack-subscribe-modal.php:193
Stack trace: 0 /home/virtualmin/richardsilverstein.com/public_html/wp-content/plugins/jetpack/modules/subscriptions/subscribe-modal/class-jetpack-subscribe-modal.php(62): Jetpack_Subscribe_Modal->should_user_see_modal() 1 /home/virtualmin/richardsilverstein.com/public_html/wp-includes/class-wp-hook.php(324): Jetpack_Subscribe_Modal->enqueue_assets() 2 /home/virtualmin/richardsilverstein.com/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() 3 /home/virtualmin/richardsilverstein.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action() 4 /home/virtualmin/richardsilverstein.com/public_html/wp-includes/script-loader.php(2262): do_action() 5 /home/virtualmin/richardsilverstein.com/public_html/wp-i in /home/virtualmin/richardsilverstein.com/public_html/wp-content/plugins/jetpack/modules/subscriptions/subscribe-modal/class-jetpack-subscribe-modal.php on line 193

### Steps to reproduce

go to homepage
click on any post link on the homepage
instead of brining up the post, you see a "criticial error" message

### A clear and concise description of what you expected to happen.

On clicking the post link I expected the post to display instead of the error

### What actually happened

critical error msg

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

Happens on all browsers

**Comment by jeherve** [comment]
Thanks for the report, and sorry for the trouble! We're working on a fix in #34723, and will release a new version of the plugin with that fix when it's been reviewed and tested.

If you feel comfortable editing PHP files, do not hesitate to test the patch and let us know if it fixed the problem for you (the file can be found under `wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-videopress/src/class-access-control.php` on your site)

**Comment by sdixon194** [comment]
Reopening until the fix is out. I've cut Jetpack 12.9.2 which should fix the issue, and it's available on SVN, but the stable tag hasn't been updated yet.

**Comment by richards1052** [comment]
Does the bug rpt have the patch?

**Comment by richards1052** [comment]
My big has nothing to do with videos or paid subscription services or a
token. Are you sure this is the right bug? Also could not tell where the
patch is if it's on the linked pg.

**Comment by chrisfromthelc** [comment]
@richards1052 I believe the fix is more likely https://github.com/Automattic/jetpack/pull/34718. There are a few fixes concerning the Token Subscription Service class name, so it looks like perhaps the wrong issue was posted here for you.

As @jeherve mentioned, feel free to implement the fixes directly if you're comfortable doing so; otherwise, this should be out on the next update.

(edited to include correct link)

**Comment by richards1052** [comment]
> @richards1052 I believe the fix is more likely #34718. There are a few fixes concerning the Token Subscription Service class name, so it looks like perhaps the wrong issue was posted here for you.
> 
> As @jeherve mentioned, feel free to implement the fixes directly if you're comfortable doing so; otherwise, this should be out on the next update.
> 
> (edited to include correct link)

I've updated to the new version and the bug is fixed.  But a Jetpack Plugin Author said in the Support forum that Jetpack site stats would be restored in the plugin update. Not only are they entirely blank, they're not recording stats since I installed the new version. So there appears to be something still amiss.  Let me know if and how I should report this if this isn't the correct place.

**Comment by jeherve** [comment]
I'll close this issue since the bug fix has now been shipped.

>  they're not recording stats since I installed the new version. So there appears to be something still amiss. Let me know if and how I should report this if this isn't the correct place.

Could you [contact us via email](https://jetpack.com/contact-support/?rel=support&hpi=1) so we can take a closer look at your stats with you?

Thank you!
