### ISSUE TITLE
Sharing Block: In wp-admin Sharing settings suggest deactivating sharing module and use block instead

### ISSUE THREAD

**Issue by andrii-lysenko** [Automattic/jetpack#34727]
Context: https://github.com/Automattic/jetpack/pull/34673#pullrequestreview-1786354226

**Comment by andrii-lysenko** [comment]
@jeherve After additional thought, I think maybe having this be more confusing, as clicking the link to disable module will actually Remove the Sharing Settings from menu and probably page will just disappear? Maybe instead we just have a proper support page that explains the connection and from there we navigate users to disable the module?
What do you think?

**Comment by jeherve** [comment]
> as clicking the link to disable module will actually Remove the Sharing Settings from menu and probably page will just disappear?

The page would only disappear on the next page load, if you do not have the Publicize or Likes modules enabled. But I can see how confusing this would be, though.

> Maybe instead we just have a proper support page that explains the connection and from there we navigate users to disable the module?

Maybe the module deactivation should happen in the site editor, as part of the Sharing block? 

Another option would be to link to the React Jetpack Settings page (Jetpack > Settings > Sharing) where folks would be able to deactivate the module?

@keoshi What's your take on this?

**Comment by keoshi** [comment]
Seems more conservative to direct people to the actual page — Jetpack > Settings > Sharing — so they can see where that option lives and retrace their steps later if they need to.
