### ISSUE TITLE
[Boost] My Jetpack -> Boost Getting Started flow shown twice

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#34764]
When installing Jetpack Boost from the My Jetpack dashboard, its "Getting started" page can be shown twice if you select the free plan.

See the video:
https://github.com/Automattic/jetpack/assets/1369626/637e77cb-bb6d-49aa-8d35-2a55e76a79cd

**To replicate**
1. Set up a new JN site with Jetpack installed (not Boost)
2. Go to My Jetpack and select "Learn more" on Boost.
3. You will be shown Boost's "Getting started" flow.
4. Click "Start for Free". It will then install Boost
5. You will be shown the Getting Started page again.

**What I think is going on**
I suspect that the first time the page is shown, Jetpack is showing the Jetpack Boost getting started component itself directly. The second time it shows, it is Jetpack Boost itself.

I think we need to keep an option somewhere indicating that the option to use the free version has already been selected, so we skip this screen after installing Boost.

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##

- Tested on Jurassic Ninja (as per OP) - Replicated  
https://github.com/Automattic/jetpack/assets/13706336/6404ad51-c063-40ee-900b-b1d9711bb59b

- Replicable outside of JN – No
Tried on Pressable and it goes through although it does hang for a second or two before the process begins causing me to press the button twice on my first test site.

So it only seems to be an issue on JN created sites, although the delay on .org sites might cause peopel to press twice

## 📌 ACTIONS ##
Triaged

**Comment by haqadn** [comment]
This seem to be no longer an issue. However, I have discovered a separate issue while looking into it.

https://github.com/Automattic/jetpack/issues/37207
