### ISSUE TITLE
Enhancement: WAF enclosure for NEEDS_UPDATE_OPTION_NAME update

### ISSUE THREAD

**Issue by ovidiul** [Automattic/jetpack#34765]
### Impacted plugin

Jetpack

### What

I would like for the check_for_updates WAF initialiser to properly enclose the update_option

### How

Looking at this line https://github.com/Automattic/jetpack/blob/d1b0594007fef579f424b1acf79765243c754d10/projects/packages/waf/src/class-waf-initializer.php#L202 , that update_option is now being called on each `check_for_updates` function call within each admin_init hook request. 

This translated to an additional UPDATE MySQL query on each WordPress backend request, which is not ideal.

<img width="1476" alt="Screenshot 2023-12-22 at 09 57 00" src="https://github.com/Automattic/jetpack/assets/537751/b672288b-1f04-4d73-94a1-d29e63ab41aa">

Would it make sense to move that update_option within the IF clause the the top so it only updates itself when the value is different?

```
if ( get_option( self::NEEDS_UPDATE_OPTION_NAME ) ) {
  ...
  update_option( self::NEEDS_UPDATE_OPTION_NAME, 0 );
}
```
CC @nateweller as this is related to this original PR https://github.com/Automattic/jetpack/pull/28899 where that was introduced.

Happy to submit a PR if needed. Thanks

**Comment by nateweller** [comment]
Thank you for submitting this @ovidiul!

I had thought at the time that `update_option` would not run the database update if the values were the same ([here](https://github.com/WordPress/wordpress-develop/blob/6.4/src/wp-includes/option.php#L795)), but that doesn't appear to be the case based on the details you've provided here. 🤔

I will open a PR to address this!
