### ISSUE TITLE
Modules/Features page - can't activate "Action Bar (Experimental)"

### ISSUE THREAD

**Issue by formosattic** [Automattic/jetpack#34811]
### Impacted plugin

Jetpack

### Quick summary

On the [Features/Modules page](https://jetpack.com/support/control-jetpack-features-on-one-page/), the feature "Action Bar (Experimental)" cannot be activated.

### Steps to reproduce

1. Connect site to Jetpack
2. Go to the Modules/Feature page
3. Activate "Action Bar (Experimental)"

### A clear and concise description of what you expected to happen.

Feature should be activated and its button should switch to `Deactivate`.

### What actually happened

Nothing, the feature stays inactivated.

![screenrecording](https://github.com/Automattic/jetpack/assets/15944096/26546cb9-d1cd-47be-8d4e-3943ec23d827)

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

- Not sure if there are workarounds
- Ran into this while doing some docs work

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO

https://github.com/Automattic/jetpack/assets/14153300/0d903af8-c73b-46ca-a203-2ec8edcbfb70

📌 ACTIONS
- Triaged

**Comment by jeherve** [comment]
This module is not yet ready for prime-time, so it cannot be enabled just yet:

https://github.com/Automattic/jetpack/blob/c6d63a7de39d88a23caf1b2257a8aef264cb8359/projects/plugins/jetpack/modules/action-bar.php#L19

**Comment by formosattic** [comment]
@jeherve , if the module isn't ready, could we do something to remove the misleading **Activate** button? For example:
- Remove the feature until it's ready, or
- Remove the **Activate** button and grey out the module, similar to **Backups and Scanning** or **WooCommerce Analytics**, maybe with a note that it's not ready yet.

![image-1](https://github.com/Automattic/jetpack/assets/15944096/e57bbddf-38dd-4571-899f-2e8cf146636a)

**Comment by jeherve** [comment]
To be honest, I think we may be able to remove the module entirely at this point, since we haven't worked on it in more than a year.

@davemart-in What's your take on this? Do you have the action bar on your roadmap for 2024, or should we drop the project for now?

For reference, here are the open issues about it:

https://github.com/Automattic/jetpack/labels/%5BPackage%5D%20Action%20Bar

Current status: pe7F0s-1U-p2#comment-274

**Comment by davemart-in** [comment]
@jeherve Yeah, we can remove this module. Is this easy for you to do, or would it be helpful for someone on Loop to take a look?

Moving forward, if we make changes, we'll just continue to make changes to the existing action bar code (like pe7F0s-1iU-p2 to update the styles).

**Comment by jeherve** [comment]
I opened #34939 to remove the module. I'd be happy for a review! :)

> Moving forward, if we make changes, we'll just continue to make changes to the existing action bar code

I should note that the existing code is only loaded on WordPress.com simple sites. This was why we had started working on a Jetpack module that would be loaded on WoA and self-hosted sites. But that module was still marked as experimental so we're not losing much by removing it from the Jetpack plugin today.

**Comment by davemart-in** [comment]
Awesome. We'll get you a review sometime in the next 24 hours.

> I should note that the existing code is only loaded on WordPress.com simple sites. This was why we had started working on a Jetpack module that would be loaded on WoA and self-hosted sites. But that module was still marked as experimental so we're not losing much by removing it from the Jetpack plugin today.

Understood. Thanks!
