### ISSUE TITLE
_jetpack_featured_image metadata not being updated properly

### ISSUE THREAD

**Issue by darssen** [Automattic/jetpack#34828]
### Impacted plugin

Jetpack

### Quick summary

When [featured images](https://wordpress.com/support/featured-images/) are created, updated, or removed in existing posts, `_jetpack_featured_image`  doesn't seem to be syncing the value in WPCOM properly the first time. If you update the post again, it will pick the change.

### Steps to reproduce

You will need access to a WPCOM sandbox
1. In your test site, create a post.
2. Edit the post, add a featured image, and update the post (Check the post_id in the url)
3. Go to your sandbox and in `wpsh` run 

``` bash
switch_to_blog($YOUR_BLOG)
print_r( get_post_meta( $_post_id, '_jetpack_featured_image' ))
```

### A clear and concise description of what you expected to happen.

It should return an array with one element with a URL pointing to the featured image.

### What actually happened

An empty array is returned

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

### Logs or notes

From an initial look into it, looks like when syncing the post, the value `_jetpack_featured_image` relies on metadata `_thumbnail_id` which has not been updated properly yet.

**Comment by liviopv** [comment]
📌 FINDINGS/SCREENSHOTS/VIDEO
Testing requires a sandbox, so marking this as triaged and keeping the PRI.

📌 ACTIONS
- Triaged

**Comment by darssen** [comment]
Moved to blocked since there are some internal discussions about not using this meta and only sync the base upload URL, so that it can be used for many different media.

**Comment by fgiannar** [comment]
Tracked in https://github.com/orgs/Automattic/projects/778/views/2?pane=issue&itemId=52988471
