### ISSUE TITLE
Publishing Failed - no useful error message

### ISSUE THREAD

**Issue by Ipstenu** [Automattic/jetpack#34833]
### Impacted plugin

Social

### Quick summary

When publishing a post that auto-posts to social media (instagram, facebook, and mastodon only), my posts fail with "Publishing failed"

there is NO error in my debug.log, there is NO error in the server error.log

The host (DreamHost) suggested it was the WAF from Jetpack, but there's nothing I've seen in the error logs that coincides with the time of those warnings (someone's hitting us with a lot of SQL injection attacks today).

I tried disabling the Mastodon publish only, as that is something that can be touchy with modSecurity, but it still fails.

### Steps to reproduce

1. Connect site to social media  (instagram, facebook, and mastodon)
2. Write post
3. Publish

### A clear and concise description of what you expected to happen.

Post should safely publish.

### What actually happened

JSON error "Publishing Failed" and the post is published, but it does not post to social media.

The only thing in Console Log is this:

`[Error] Failed to load resource: the server responded with a status of 500 () (89114, line 0)`

and it links to https://lezwatchtv.com/wp-json/wp/v2/show/89114?_locale=user

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Could Not Replicate
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
- tested on a WordPress.com site and could not replicate
- tested on a self-hosted site on Pressable with only Jetpack Social installed and could not replicate

https://github.com/Automattic/jetpack/assets/14153300/d5e2d450-416a-45c0-85e4-2152cbb96e96

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
@Ipstenu I couldn't reproduce it on two of my sites, so it doesn't seem widespread enough to justify the open bug report. I'm asking for the Jetpack Support team to reach out to you via email to troubleshoot.

**Comment by Ipstenu** [comment]
@liviopv If it helps, this is on DreamPress with Nginx. So it's POSSIBLE it's endemic to this specific situation.

Quirks I can think of:

1. Nginx server
2. Posts to Facebook BUSINESS
3. Posts to mstdn.social
4. Posts to Tumblr

I'm fairly sure it's a server issue, but I wanted to do due diligence.

Is there any way I can turn on more errors for Jetpack to try and diagnoise?

**Comment by JenSwish** [comment]
Hey @Ipstenu, I'm looking into this now. I'll email you shortly.
