### ISSUE TITLE
Jetpack don't see CPTs on Featured posts request in functions.php

### ISSUE THREAD

**Issue by vovkasolovev** [Automattic/jetpack#3484]
Trying to get all featured items with sugested in docs code (http://jetpack.me/support/featured-content/) with little modification — trying to get featured posts form all post types.

For example, I create by Plugin my new cusom post type "my-cpt" with default Post_tag taxonomy on it.
Jetpack will get Featured posts only from _Post_ and _Pages_, and not from _My-cpt_ on this request in _functions.php_:

```
function featured_content_support() {
	add_theme_support( 'featured-content', array(
		'filter'     => 'my_get_featured_posts',
		'max_posts'  => 7,
		'post_types' => array( get_post_types( array( 'public' => true,), 'names' ) ),
		'sort_column' => 'ID',
		'orderby' => 'menu_order',
		'order'=> 'ASC',
		'sort_order' => 'ASC',
	) );
}
add_action( 'after_setup_theme', 'featured_content_support' );
```

In the same time I can get all featured posts from all post types in _index.php_ with
`array( get_post_types( array( 'public' => true,), 'names' ) )`

As workaround i just add my CPT with hardcode in _functions.php_, This will work:

```
function featured_content_support() {
	add_theme_support( 'featured-content', array(
		'filter'     => 'my_get_featured_posts',
		'max_posts'  => 7,
		'post_types' => array( get_post_types( array( 'public' => true,), 'names' ), 'my-cpt'),
		'sort_column' => 'ID',
		'orderby' => 'menu_order',
		'order'=> 'ASC',
		'sort_order' => 'ASC',
	) );
}
add_action( 'after_setup_theme', 'featured_content_support' );
```

I think there is some bug in hooks order or in Plugins initalisation order.

**Comment by jeherve** [comment]
Could you try to test ` get_post_types( array( 'public' => true ) )` outside of the `add_theme_support` call, and make sure it returns your CPT then?

**Comment by vovkasolovev** [comment]
I made a test. This code in _index.php_ will return all my CPTs :
```
foreach ( get_post_types( array( 'public' => true ) ) as $post) {
	echo $post.' ';
};
```

**Comment by vovkasolovev** [comment]
I forgot to mention: it's on WP multisite installation. If that matters.

**Comment by jeherve** [comment]
Could you try using `array_values( get_post_types( array( 'public' => true ), 'names' ) );`, to avoid returning a multidimensional array?

Let me know if it helps.

**Comment by jeherve** [comment]
Closing this, do not hesitate to comment again if that didn't work!
