### ISSUE TITLE
Performance: minify all .js files

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3487]
[We already use Grunt](https://github.com/Automattic/jetpack/blob/master/Gruntfile.js) for several aspects of the Jetpack codebase: sass, concat, jshint, ...

It would be nice if we could use it to generate minified versions of each one of the .js files included in Jetpack, thus improving performance a bit.

Suggested here:
https://wordpress.org/support/topic/please-minify-js?replies=1&view=all

**Comment by jeherve** [comment]
Also suggested here:
http://jetpack.com/2016/07/06/4-1-sso-sharing-buttons-more/#comment-20370

**Comment by zinigor** [comment]
This issue is pretty broad, let's close this, because we have lots of work going on in Standalone plugins that work for decreasing the bundle size. The main plugin itself is also much more minified compared to the time the issue was created.
