### ISSUE TITLE
Transforming a Tiled Gallery block into a WP Gallery block and vice versa

### ISSUE THREAD

**Issue by tripsoverpoland** [Automattic/jetpack#34880]
### Impacted plugin

Jetpack

### What

Transforming the specified Tiled Gallery block into the WP Gallery block and vice versa

### How

If we already use Tiled Gallery (Jetpack), we would sometimes like to be able to change such a gallery into a typical Wordpress gallery block in some entries.
When editing an entry, select a block from Tiled Gallery (Jetpack) and then the option "convert into Wordpress Gallery" should appear somewhere (e.g. in the block menu).
Similarly, after selecting a block with a Wordpress gallery, the option "replace in Tiled Gallery (Jetpack)" should appear somewhere (e.g. in the block menu).

**Comment by jeherve** [comment]
I have good news: that's already possible :) 

You can use WordPress' "transform" option in the block editor to switch from one gallery type to another. Here is how it looks:

https://github.com/Automattic/jetpack/assets/426388/25a286a0-fd8e-4893-b3b7-62cee2957fd2

**Comment by tripsoverpoland** [comment]
Thank you for pointing out this possibility - I actually hadn't noticed it until now. Thank you for creating this opportunity with Jetpack.
