### ISSUE TITLE
Feature: a member login block

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#34884]
- Simple block that renders a link for members to login, and otherwise indicates that they are logged in and links to subscription management page for that page:
    <img width="700" alt="Screenshot 2024-01-08 at 11 15 53" src="https://github.com/Automattic/jetpack/assets/87168/e6b7fdc4-0783-4eb8-9f1d-b138aad38d28">

- It's important to be able to insert the block under "navigation block" as well as anywhere else on the page.

- It's very important the name of the block is clear, so to separate it clearly from regular site's own login block, as well as paywall and other paid membership blocks and features. Also has to translate well.
    - @crisbusquets worth thinking this name through, and defaulf copy of logged-out/logged-in state of the block. 
    - Woo might have some similar "customer login" block, and perhaps other member plugins like Buddypress?

After initial block scaffolding (at which point block might be good enough for v1 release), good follow-ups:

- Allow rendering the block as a link as well as a button. Good way would be offering two styles variations. Check button and navigation blocks for inspiration. Woo's cart blocks might have good examples as well.

- Allow changing the copy directly inline in the block itself (see jetpack subscribe block button, or gutenberg button block as examples).

- Allow changing logged in label from sidebar settings

### Tech notes

- @crisbusquets to include some designs here, and otherwise keep in loop for testing/UX.

- There's a script to scaffold a block, see https://github.com/Automattic/jetpack/tree/trunk/projects/plugins/jetpack/extensions#readme

- In https://github.com/Automattic/jetpack/pull/33781 I explored having separate `get_subscriber_login_link` function which might be helpful here too.

#### Business logic

- [x] The "Log in" link should work like in the Paywall block, taking the user to https://wordpress.com/log-in/link with a redirect URL to the initial page https://github.com/Automattic/jetpack/pull/34981
- [x] The "Log out" link should log the user out, clear the premium content cookie and redirect to the initial page page https://github.com/Automattic/jetpack/pull/34981
- [x] The "Manage subscriptions" link should be renamed to "Manage subscription" and point to the specific subscription, not to the list of them. We could point to https://wordpress.com/read/subscriptions?s={blogUrl} as a workaround https://github.com/Automattic/jetpack/pull/36193
- [x] Add some styling settings, like padding, margin, or align. Check the Login/out block and do it in a similar way https://github.com/Automattic/jetpack/pull/35085
- [x] Add an icon (icon needed, cc @crisbusquets) https://github.com/Automattic/jetpack/pull/35221
- [x] Add a description (copy needed, cc @crisbusquets) https://github.com/Automattic/jetpack/pull/35221
- [x] Allow to change the link labels https://github.com/Automattic/jetpack/pull/35179
- [ ] #36268
- [x] Allow to add it to the navigation block https://github.com/Automattic/jetpack/pull/35410
- [x] Checking if the user is logged in by using `is_user_logged_in()` is probably not enough. Investigate it, we probably need to add an additional check for the premium cookie presence https://github.com/Automattic/jetpack/pull/35113
- [x] Add the "Redirect to current URL" setting to keep consistency with the Login/out block https://github.com/Automattic/jetpack/pull/35161
- [x] Allows transforming to/from Login/out block keeping the "Redirect to current URL" setting https://github.com/Automattic/jetpack/pull/35161
- [x] Always redirect to the blog home page when the "Redirect to current URL" toggle is off https://github.com/Automattic/jetpack/pull/35221
- [x] Move it to production https://github.com/Automattic/jetpack/pull/35332
- [x] Request docs https://github.com/Automattic/en.support-docs-content/issues/2370
- [ ] #36269
- [ ] #36270
<img width="855" alt="Screenshot 2024-02-01 at 22 17 32" src="https://github.com/Automattic/jetpack/assets/4068554/1fce16a1-e7ef-41f2-8d99-ef7a317ad7b4">

#### Technical stuff

- [ ] #36267
- [x] Make sure the custom class names work in the editor https://github.com/Automattic/jetpack/pull/35085
- [x] Remove the CSS file if not needed https://github.com/Automattic/jetpack/pull/35085
- [x] Ensure that `Abstract_Token_Subscription_Service` and `Jetpack_Memberships` classes exist before using it https://github.com/Automattic/jetpack/pull/35085
- [x] Fix the simple sites login URL making the token not visible in the URL https://github.com/Automattic/jetpack/pull/35371
- [x] Fix clearing all the cookies when logging out https://github.com/Automattic/jetpack/pull/35441

**Comment by crisbusquets** [comment]
@simison @pkuliga 

> It's very important the name of the block is clear, so to separate it clearly from regular site's own login block, as well as paywall and other paid membership blocks and features. Also has to translate well.

I think `Subscriber login` could work.

> @crisbusquets to include some designs here, and otherwise keep in loop for testing/UX.

I'll work on the flow. Clicking the button will open the `https://wordpress.com/log-in/link`, right?

**Comment by simison** [comment]
@crisbusquets Yes, everything otherwise exactly like from paywalls in the posts:

<img width="595" alt="image" src="https://github.com/Automattic/jetpack/assets/87168/54e5a322-3cc5-4535-bb58-53b2405839c3">

Let's try "Subscriber login". 👍 

Block will need icon and description, too.

**Comment by dhanson-wp** [comment]
This looks great! Logging in should ideally keep the subscriber on the page or post in which they login. Having the logged in state show something like `Manage Subscription` or `My Subscription` would be great, even better if each state is editable by site owners.

**Comment by katiebethbrown** [comment]
> I'll work on the flow. Clicking the button will open the https://wordpress.com/log-in/link, right?

Is the button display conditional on the existence (or lack therof) of the premium content cookie, or the WordPress.com cookies?

What happens if a visitor clicks the login option and they have a WPcom account but not a subscription to this site?

They'll be able to click on `Log in` and get a WPcom login link, and that will redirect them back to the site (like it would for a subscriber) with the WPcom cookies. They just won't get the premium-content cookie, and still won't have access. 
- We've not clarified that they don't actually have a sub or prompted them to start one, right?
- Will they still see the `Manage Subscription` link in the nav in this state? If they do see the manage link, what's the state of the subscription management page in the reader for a site you aren't actually subscribed to? Is it possible to start a new sub from there?

**Comment by pkuliga** [comment]
There is a similar block in Gutenberg already:

<img width="484" alt="Screenshot 2024-01-12 at 11 39 59" src="https://github.com/Automattic/jetpack/assets/4068554/ba72d29b-2095-4c40-af9b-6e2cf4304124">

https://github.com/WordPress/gutenberg/tree/7fce392ac694f4dc66ba6300f7b3356e9cdc2123/packages/block-library/src/loginout

We could take some ideas from it.

**Comment by simison** [comment]
Yep! Study the block and see if there's anything to model after it, e.g. "supports" attributes, settings, or anything else. Let me and @crisbusquets know what you found.

BTW Block name can be sentence-case; "Subscriber login".

For now you can steal the icon from login/logout block, but we'll likely replace with our own later.

**Comment by simison** [comment]
> Clicking the button will open the https://wordpress.com/log-in/link, right?

Correct.

> They'll be able to click on Log in and get a WPcom login link, and that will redirect them back to the site (like it would for a subscriber) with the WPcom cookies. They just won't get the premium-content cookie, and still won't have access.

Yes, but they'll be logged in at the site. This might need more work but they should gain access to things like liking and commenting. They can also subscribe to posts without entering their email.

**Comment by pkuliga** [comment]
> BTW Block name can be sentence-case; "Subscriber login".

Not sure about this, all blocks I checked are title-cased. I prefer to be consistent with the rest of the platform 😄 

<img width="269" alt="Screenshot 2024-01-12 at 12 44 17" src="https://github.com/Automattic/jetpack/assets/4068554/a11f771f-19e5-44c0-a725-ae0529c8a8d9">

**Comment by simison** [comment]
Oh that's weird, Gutenberg has been moving to sentence case in UIs and so has WordPress.com everywhere in UIs, but looks like not in Blocks.

Agree on keeping consistent!

**Comment by crisbusquets** [comment]
> Oh that's weird, Gutenberg has been moving to sentence case in UIs and so has WordPress.com everywhere in UIs, but looks like not in Blocks.
> 
> Agree on keeping consistent!

I asked this on Slack p1705061961499709-slack-C9EJ7KSGH
But yes, let's be consistent.

**Comment by dhanson-wp** [comment]
> For now you can steal the icon from login/logout block, but we'll likely replace with our own later.

An `Account`or `My account` icon would work well and differentiate it from the core Login block. Something like a profile icon.

**Comment by pkuliga** [comment]
I merged the first iteration of it and added some TODOs for the further iterations (need to scroll to the top to see it). Feel free to modify it if needed!

Added some screenshots to the PR https://github.com/Automattic/jetpack/pull/34981 to better present how it works in comparison to other subscription blocks.

**Comment by simison** [comment]
One feature that is important to add is ability to add the block to the navigation block:

<img width="436" alt="Screenshot 2024-01-19 at 12 25 31" src="https://github.com/Automattic/jetpack/assets/87168/aecf2e91-0f48-47aa-b2fe-d2984e75a683">

Meanwhile transforms between core login/member login blocks can be helpful especially in navigation block, where managing blocks can be a bit complicated:

<img width="323" alt="Screenshot 2024-01-19 at 12 24 34" src="https://github.com/Automattic/jetpack/assets/87168/ddb40666-fec3-46f6-a878-0626aea0ce01">
<img width="324" alt="Screenshot 2024-01-19 at 12 24 28" src="https://github.com/Automattic/jetpack/assets/87168/6c7ef8a6-6874-4925-9252-a361b8584395">

**Comment by pkuliga** [comment]
> One feature that is important to add is ability to add the block to the navigation block:

Added it to TODOS, thanks!

**Comment by crisbusquets** [comment]
For the description: Show links for subscribers to login, logout, or manage their subscription.

For the icon, we can reuse this: `block-comment-author-gravatar`. It implies "account avatar".

<img width="740" alt="Screenshot 2024-01-24 at 13 28 44" src="https://github.com/Automattic/jetpack/assets/25607244/ddb32093-4e02-4b72-a63d-c31e0adbb9e3">

However, I'd rather design a new one. This will take time, so I'd go with the one suggested above.

**Comment by pkuliga** [comment]
Hi folks, before releasing it would be nice to have some testing.

To do that you need to have access to the Beta blocks. You can enable it like this https://github.com/Automattic/jetpack/tree/trunk/projects/plugins/jetpack/extensions#beta-extensions.

**Comment by pkuliga** [comment]
Closing this one since the block has already been released. Further work will be done under separate issues.
