### ISSUE TITLE
Simple Sites: Slideshow block shows 'The Swiper Library could not be loaded' and breaks on front-end

### ISSUE THREAD

**Issue by cuemarie** [Automattic/jetpack#34954]
### Impacted plugin

Jetpack

### Quick summary

On several Simple WordPress.com sites, dding Slideshow Block + Media results in `The Swiper Library could not be loaded` in the editor and broken slideshow features on the front end.

Customers impacted mentioned this just started happening today: p1704926606890569-slack-C03TY6J1A

### Steps to reproduce

1. On a simple WordPress.com site, add a page
2. Add a slideshow block
3. Add media to the block
4. Publish and view page

Note: If testing on a wpcom sandbox, you'll need to define `FORCE_CONCAT` and comment out the two lines at fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Swfpbapng.cuc%3Se%3Qqp26s2on%23110%2Q111-og to reproduce (or, for the frontend only, append `?concat_js=yes` to the URL).

### A clear and concise description of what you expected to happen.

Slideshow should appear in the editor and on the front end

### What actually happened

Editor:

![image](https://github.com/Automattic/jetpack/assets/27249804/1d86e145-ec3f-46c1-bde3-8403a6bde55c)

Live site: 

![image](https://github.com/Automattic/jetpack/assets/27249804/d0ad7c5e-e8c1-45fc-a260-637ced0d73e4)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Presented on Starter and Explorer plan sites.  

Customer report: 

- 7567041-zen

---

Reported internally here: p1704928597989799-slack-CBG1CP4EN

**Comment by sdixon194** [comment]
I reverted the wpcom release today which seems to have fixed this issue. I haven't had a chance to investigate further, but when testing I wasn't able to reproduce this on my sandbox, only the live site.

Here are the dotcom changes that were reverted, so one of these PRs is the likely culprit: https://github.com/Automattic/jetpack-production/compare/00a7f53...ea3c17d

**Comment by jeherve** [comment]
#34923 seems to be the most likely cause of the problem.

**Comment by Joshgrygiel** [comment]
Initial user report: #7565954-zen 

I did follow up with them already and let them know the issue has been reverted for now

**Comment by mreishus** [comment]
I think these could be broken again. See: p9X8ns-4lG-p2 and p73Jol-3QW-p2 (no slideshows on either)

**Comment by anomiex** [comment]
Whatever is going on there, it doesn't seem to be this bug. I see neither the error in the editor nor the display like this
![image](https://github.com/Automattic/jetpack/assets/27249804/d0ad7c5e-e8c1-45fc-a260-637ced0d73e4)
on the live site.

Followup at p1705608756533359-slack-CBG1CP4EN (TL;DR: It's something in P2)
