### ISSUE TITLE
Can't find the Top Posts & Pages Block anywhere

### ISSUE THREAD

**Issue by sarangsss29** [Automattic/jetpack#34977]
### Impacted plugin

Jetpack

### Quick summary

Just updated to Jetpack 13 stable and can't find the Top Posts & Pages widget block anywhere. How do I access that? I have been looking forward to this feature since teh alpha.

### Steps to reproduce

- Go to site editor
- Click on any sidebar section
- Add a new widget

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by jeherve** [comment]
We're currently working on implementing a Top Posts block that will replace the legacy widget in the next few weeks. Until then, you can continue to use the legacy Top Posts & Pages widget, but to do so you will need to install the Classic Widgets plugin:
https://wordpress.org/plugins/classic-widgets/

Let me know if it helps.

**Comment by liviopv** [comment]
Another request for a Top Posts and Pages Block 7715016-zd-a8c This user has a Block Theme, which can use the shortcode, but the shortcode doesn't have any customization options (that I'm aware of).

**Comment by jeherve** [comment]
> the shortcode doesn't have any customization options (that I'm aware of).

The shortcode offers the same customization options as the widget:

- title: the title
- count: number of posts to display, defaulting (and maximum) to 10.
- types: a comma-separated list of post types, defaulting to listing both posts and pages.
- ordering: can be `views` or `likes`
- display: can be `text`, `grid`, or `list`

**Comment by annacmc** [comment]
I'm going to go ahead and close this up, as I'm not sure there's anything that needs action here. 

More importantly, however - it's from the beginning of the year, and I see that there was both a workaround proposed (to use the legacy classic widgets) as well as a new top posts & pages block available now (https://jetpack.com/support/jetpack-blocks/top-posts-pages-block/)
