### ISSUE TITLE
Related Posts: Headline conflicts with page outline

### ISSUE THREAD

**Issue by monsieur-z** [Automattic/jetpack#34973]
### Impacted plugin

Jetpack

### Quick summary

The _Related Posts_ block has an optional _Headline_ setting, which is rendered as a `h3` heading in the site.

A clear document outline is essential to communicate the organization of the content on a page. Heading levels shouldn't be skipped, and the behavior described above assumes that a page has `h1` and `h2` headings.

If set, the headline should respect the page heading structure instead of choosing a level arbitrarily.

<img width="282" alt="Screenshot 2024-01-11 at 2 58 20 PM" src="https://github.com/Automattic/jetpack/assets/1620183/87d34524-6585-40d9-b3ba-fc5d40a5be4a">

### Steps to reproduce

1. Create a new post
2. Add a _Related Posts_ block
3. In the settings panel, add a headline
4. Open the preview
5. Notice the headline is rendered in a `h3`

### A clear and concise description of what you expected to happen.

A straightforward solution is to let the user set the heading level. Maybe the most "Gutenberg-like" way of doing this is to remove the headline from the settings panel and add a `core/heading` as a child block instead.

A more involved option is automatically setting the heading level based on the current page structure, on updating the page.

### What actually happened

The headline is rendered in a `h3`.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple – Replicated 
- Tested on Atomic – Replicated 

- Steps are as above.
