### ISSUE TITLE
get_post() returns null when called inside functions hooked with 'save_post' when Jetpack version is above 12.7.1

### ISSUE THREAD

**Issue by Imran92** [Automattic/jetpack#34979]
### Impacted plugin

Jetpack

### Quick summary

You can read the details of the issue we were facing because of this here - https://github.com/Automattic/sensei-pro/issues/2517 .

A change was introduced here https://github.com/Automattic/jetpack/pull/33384 in Jetpack - this filter was attached to the post enqueue hook during post saves https://github.com/Automattic/jetpack/blob/286ee70e8ff08425a707bf2fb27da2b30abc3895/projects/packages/sync/src/modules/class-posts.php#L152. Inside the hooked filter, the global $post object was [getting](https://github.com/Automattic/jetpack/blob/286ee70e8ff08425a707bf2fb27da2b30abc3895/projects/packages/sync/src/modules/class-posts.php#L430-L432) overridden. Because of it, inside the functions attached to the '`save_post`' hook, if `get_post()` function is called, it is returning null instead of the current post. `get_post` starts working as expected if we deactivate Jetpack or Comment out the aforementioned line of code. `get_post` is a very commonly used function and is also being used in other important global functions like `get_post_type` etc. So a change in the behavior of the `get_post` function can probably affect other places.

It was introduced in 12.8 beta a1 (https://github.com/Automattic/jetpack-production/releases/tag/12.8-a.1) and wasn't present in 12.7.1. So this forum issue also seems related https://wordpress.org/support/topic/jetpack-12-8-1-and-get_post_meta-returning-null/.

### Steps to reproduce

1. Create a site with Jetpack connected, with version > 12.7.1
2. Add a snippet with a functoin that's hooked to  `save_post` hook. Inside that function, `error_log ` the `get_post` function's output.

### A clear and concise description of what you expected to happen.

To log the current post

### What actually happened

Logged null instead

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

**Comment by jeherve** [comment]
cc @fgiannar, who originally worked on #33384.

**Comment by fgiannar** [comment]
Trying to reproduce but no luck so far. Left a corresponding comment [here](https://github.com/Automattic/sensei-pro/issues/2517#issuecomment-1889081578)

**Comment by Imran92** [comment]
Hi @fgiannar 👋 I've shared some site creds with you here where you can see it reproduced https://github.com/Automattic/sensei-pro/issues/2517#issuecomment-1889132843. Hope this'll help.
