### ISSUE TITLE
Boost: Missing tooltip for Manual Critical CSS regeneration

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#34987]
Did we intentionally do this, or did we miss adding it back?

### Boost production

![Image](https://github.com/Automattic/jetpack/assets/11799079/52854a5c-3193-44a4-a82a-3b2a8119cc9b)

### Boost trunk

![Image](https://github.com/Automattic/jetpack/assets/11799079/6967ba23-5584-46eb-9e76-3cabff715f2a)

**Comment by thingalon** [comment]
This was not deliberate, and needs to be fixed.

**Comment by thingalon** [comment]
Should be fixed in https://github.com/Automattic/jetpack/pull/35022.
