### ISSUE TITLE
[Boost] Improve DataSync debug capabilities.

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#35011]
**Note:** this is an important maintainability tidy-up, but is not a blocker to a React release.

@pyronaur please add details here. Migrated from trello.

**Comment by pyronaur** [comment]
Phase 1: https://github.com/Automattic/jetpack/pull/35062

**Comment by pyronaur** [comment]
Phases 2 and 3:

https://github.com/Automattic/jetpack/pull/35114

https://github.com/Automattic/jetpack/pull/35325

This is now done.
