### ISSUE TITLE
[Boost] Remove Svelte from build process entirely

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#35016]
Now that our code is in React, we need to update our build process to no longer use Svelte tools at all, and switch our root component from Svelte to React.

**Comment by dilirity** [comment]
Isn't that going to be a problem with Image Guide (free) as part of Boost? It still uses svelte.

**Comment by dilirity** [comment]
Oh, ignore my last. I just saw https://github.com/Automattic/jetpack/issues/35017
