### ISSUE TITLE
[Boost] Add CSS transitions back

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#35015]
Svelte transitions were removed during the migration.

@dilirity compiled a list of animations that need to be reviewed and re-added:

- [x] **Won't be added. Doesn't make much difference.** Critical CSS advanced recommendations more pages list and link ([code - items](https://github.com/Automattic/jetpack/blob/a0c67ad7b644093c501a09b8232e865384eb9102/projects/plugins/boost/app/assets/src/js/elements/MoreList.svelte#L40), [code - link](https://github.com/Automattic/jetpack/blob/a0c67ad7b644093c501a09b8232e865384eb9102/projects/plugins/boost/app/assets/src/js/elements/MoreList.svelte#L46))
![CleanShot_2024-01-12_at_16 08 57](https://github.com/Automattic/jetpack/assets/1369626/68cf3754-7d1b-4edc-b0b9-ea74fd79609c)

- [x] https://github.com/Automattic/jetpack/pull/35036 Dismissing a notice collapse ([code](https://github.com/Automattic/jetpack/blob/9293fdc33d97ac0e011bbe6c8baef4c05b2cc829/projects/plugins/boost/app/assets/src/js/elements/Notice.svelte#L45))
![poZY4lZYKi2C5qFyiSQN60wms8Y5n3kYASxZIqiq](https://github.com/Automattic/jetpack/assets/1369626/41f8058e-30bf-406e-b69a-9e8369b7d8cf)

- [x] **Already present** ISA: Hero fade in ([code](https://github.com/Automattic/jetpack/blob/9da46fea715e6ae89ab53410994752830b7272e2/projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/recommendations/Hero.svelte#L27))
![CleanShot_2024-01-12_at_16 16 43](https://github.com/Automattic/jetpack/assets/1369626/d872938b-fa31-42f9-8493-5099099b7c61)

- [x] **Already present** ISA: Table rows fade in ([code](https://github.com/Automattic/jetpack/blob/c58fa0ea528dec57289c08eb8c12be299f5abcdf/projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/recommendations/row-types/TableRow.svelte#L25))
![CleanShot_2024-01-12_at_16 18 41](https://github.com/Automattic/jetpack/assets/1369626/9fa9d2fb-4e8b-489c-9180-4d6ffab48b73)

- [x] **Won't be added. Doesn't make much difference.** Critical CSS advanced recommendations raw error collapse/expand ([code - 1](https://github.com/Automattic/jetpack/blob/a2ccfb7978184e306211292a66ed49dcf38a517f/projects/plugins/boost/app/assets/src/js/pages/settings/elements/CriticalCssErrorDescription.svelte#L103), [code - 2](https://github.com/Automattic/jetpack/blob/a2ccfb7978184e306211292a66ed49dcf38a517f/projects/plugins/boost/app/assets/src/js/pages/settings/elements/CriticalCssErrorDescription.svelte#L108))
![CleanShot_2024-01-12_at_16 28 35](https://github.com/Automattic/jetpack/assets/1369626/0181044e-3bae-427c-b5de-0045a492c75e)

- [x] https://github.com/Automattic/jetpack/pull/35069 Critical CSS Show Stopper Error collapse/expand ([code](https://github.com/Automattic/jetpack/blob/a2ccfb7978184e306211292a66ed49dcf38a517f/projects/plugins/boost/app/assets/src/js/pages/settings/elements/CriticalCssShowStopperError.svelte#L44))
![NMJjYPAzs6ndnyDuNoBe0pVAgSNDZUMYZNKACQ5Y](https://github.com/Automattic/jetpack/assets/1369626/d5153af1-392f-451f-8fb0-35e343d81bd9)

- [x] Score increase slide in ([code](https://github.com/Automattic/jetpack/blob/4d516b2e439ca39a2bfcaff8ae32876d741b8ef4/projects/plugins/boost/app/assets/src/js/pages/settings/elements/PopOut.svelte#L31)) This might already be added
![CbWtLuwjoqe4FwJlzmQFWRAnB21e9qTqmAIfKle8](https://github.com/Automattic/jetpack/assets/1369626/f7ed0d09-0c4e-4508-b491-dc974f3a2746)

- [x] Rating card - unused component? ([code](https://github.com/Automattic/jetpack/blob/a0c67ad7b644093c501a09b8232e865384eb9102/projects/plugins/boost/app/assets/src/js/pages/settings/elements/RatingCard.svelte#L28))

- [x] Score drop slide in ([code](https://github.com/Automattic/jetpack/blob/a0c67ad7b644093c501a09b8232e865384eb9102/projects/plugins/boost/app/assets/src/js/pages/settings/elements/ScoreDrop.svelte#L32)) This might already be added
![evaKBz5UNS75gVXzedFVtKZP6o0IpSkEEH3aZatj](https://github.com/Automattic/jetpack/assets/1369626/a8b9678b-cd34-4b6e-9bfb-029e59d5a849)

- [x] https://github.com/Automattic/jetpack/pull/35122 Critical CSS advanced recommendations collapse/expand ([code - panel](https://github.com/Automattic/jetpack/blob/a2ccfb7978184e306211292a66ed49dcf38a517f/projects/plugins/boost/app/assets/src/js/pages/settings/sections/AdvancedCriticalCss.svelte#L79), [code - link (no transition?)](https://github.com/Automattic/jetpack/blob/a2ccfb7978184e306211292a66ed49dcf38a517f/projects/plugins/boost/app/assets/src/js/pages/settings/sections/AdvancedCriticalCss.svelte#L56))
![sTEjOFhzm6fxZwD05WHsaBWEuWj7zhLvo5bISZ0w](https://github.com/Automattic/jetpack/assets/1369626/af0ed0fb-8efe-48d9-8810-3ffe6df2a207)

**CSS transitions**
- [x]  Progress bar transition ([code](https://github.com/Automattic/jetpack/blob/316dd5a3915ac23b3f43da9ca26a2dd52a580cea/projects/plugins/boost/app/assets/src/js/elements/ProgressBar.svelte#L32))
![CleanShot_2024-01-12_at_16 33 11](https://github.com/Automattic/jetpack/assets/1369626/deb3411d-d156-41f9-9692-0383a6257e9a)

**Not sure if they don’t complement svelte transitions**
https://github.com/Automattic/jetpack/blob/d51f12c16c8a89ebe0b6d7b0ca7439c26400f794/projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/recommendations/Table.svelte#L100

https://github.com/Automattic/jetpack/blob/c58fa0ea528dec57289c08eb8c12be299f5abcdf/projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/recommendations/row-types/TableRow.svelte#L65

**Comment by dilirity** [comment]
We've added all the transitions that make sense.
