### ISSUE TITLE
Sharing Block: Improve colour style configs

### ISSUE THREAD

**Issue by andrii-lysenko** [Automattic/jetpack#35044]
There are several suggestions on improving styling around the block. We want to address colour configs within this task.
Context (list items 1,3): pdtkmj-2dQ-p2#comment-4081 and pdtkmj-2dQ-p2#comment-4097

**Comment by andrii-lysenko** [comment]
@keoshi what do you think about this one? So I see 2 ways, we could have these controls over every button, or the placeholder block. On one hand, every block gives us the precision (like with button for example). On the other, Social Links core block has control only over the placeholder, well, which eliminates the possibility to have every button in different color.

**Comment by keoshi** [comment]
@andrii-lysenko Thanks for the ping!

To be honest I'd be more than happy if we follow the lead of the Social Links core block. That seems like a decent level of customization for right now. What are your thoughts?

Edit: limiting it at this level also helps prevent some crazy designs with different colors on each button, so it's also a way to curate how the block is perceived to a wider audience.

**Comment by andrii-lysenko** [comment]
@keoshi Thanks. Implemented behavior similar to Social Links block in PR: https://github.com/Automattic/jetpack/pull/35354
