### ISSUE TITLE
[Boost] Detect caching blockers

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#35059]
The plugin must add the following to enable caching:
1. a file called wp-content/advanced-cache.php which will load the caching engine in the plugin.
2.  `define( 'WP_CACHE', true );` to the site wp-config.php to enable caching.

Detect if an `advanced-cache.php` file already exists when trying to enable the module. Show an error message if you cannot.

This depends on the UI being together - https://github.com/Automattic/jetpack/issues/35054 and possibly its related design thread - pc9hqz-2sW-p2

**Comment by donnchawp** [comment]
Working on this in https://github.com/Automattic/jetpack/pull/35042

**Comment by thingalon** [comment]
Now that we no longer want this to be Premium-only, we no longer have a drive to ship with this enabled by default. We can turn it on after we ship MVP 1.

As such, the only thing left in this ticket is about relaying errors to the UI, so I will close this as a duplicate of https://github.com/Automattic/jetpack/issues/35215
