### ISSUE TITLE
[Boost] Delete cached content on edit.

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#35055]
Whenever the user performs an action which should invalidate cached content, delete the relevant cache files. Here is a starting point, though we should check Super Cache's codebase for additional cases where we should invalidate the cache:

- [ ] On page/post edit
- [ ] When you change your theme
- [ ] When you edit your page templates

Note that you shouldn't just invalidate the page being edited, it should also invalidate views which may show the relevant page.

**Comment by thingalon** [comment]
@donnchawp I am assigning this to you as I believe you're already on the case with https://github.com/Automattic/jetpack/pull/35397 - right?

**Comment by donnchawp** [comment]
In #35397 it does the first two, but not template editing. I'm not sure what hook to use for that.

**Comment by donnchawp** [comment]
Since logged in users don't see a cached page, they can edit the template, knowing that at least some of their pages will still be using the old design. It might be better for them to delete the cache when they're done, through the Boost Settings page.
