### ISSUE TITLE
[Boost] Cache complete HTML pages created by WordPress.

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#35052]
MVP feature for Boost Cache - provide basic page caching for WordPress. Includes:
- Implemented as a Boost Module which we can activate through code (for now).
- Only caches GET requests.
- Does not cache `wp-admin`.
- Hidden behind a feature-flag constant (using the Module class' `is_available` method to check for a constant).

Does not include:
- Any UI at all. Tip: during dev, you can force this module on by making its `Module` class `implement` the `Is_Always_On()` interface. See `Image_Size_Analysis.php` for an example.
- Any kind of invalidation, cleanup, etc.

**Comment by donnchawp** [comment]
Working on this in https://github.com/Automattic/jetpack/pull/35042

**Comment by thingalon** [comment]
This seems to be done to me.
