### ISSUE TITLE
[Boost] Disable cache for URLs by pattern

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#35057]
This does not include the UI (that is in #35054); this issue is about implementing the feature.

Make Boost Cache support bypassing pages based on entered Regular Expression patterns. The setting is already defined in `get_excluded_urls()` which returns an array of strings.

Strings should be treated as regular expressions and the current URL should be checked against each one. If we exclude a URL based on its pattern, it's worth throwing a line in the debug log about it.

This ticket really just involves taking the existing setting, and updating `is_cacheable` to check for regexp patterns.

**Comment by donnchawp** [comment]
Some discussion here: p1HpG7-r0o-p2

We will disable caching for some URLs like wp-.*\.php and index\.php as WP Super Cache does, but there's no need to show them in the config.
