### ISSUE TITLE
Forms block: Single Choice (Radio) Block does not display the "buttons" variation on the front end

### ISSUE THREAD

**Issue by tvolpert** [Automattic/jetpack#35089]
### Impacted plugin

Jetpack

### Quick summary

The Single Choice (Radio) Block has two options under `Styles` in the settings sidebar: `List` and `Buttons`. Selecting the `buttons` style works in the editor, but on the front end these are still shown as radio buttons (IE the `list` option) rather than regular buttons.

### Steps to reproduce

1. add a Form block to any page or post
2. add a Single Choice (Radio) Block to that form, and create some options
3. select the `Buttons` style on the block settings sidebar. You will now see buttons in the editor, like so:

<img width="1222" alt="Screenshot 2024-01-17 at 10 35 43 AM" src="https://github.com/Automattic/jetpack/assets/34486913/0ff23ec3-1791-45d1-90d2-08025588a6de">

but if you either Preview in new tab, or save the page and view it live, they are shown as radio buttons instead:

<img width="1228" alt="Screenshot 2024-01-17 at 10 36 24 AM" src="https://github.com/Automattic/jetpack/assets/34486913/40755100-142f-4e68-971c-ea3ef117a853">

### A clear and concise description of what you expected to happen.

the styling on the front end should match the editor

### What actually happened

the styling on the front end does _not_ match the editor

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by tvolpert** [comment]
reported in 7599145-zd-a8c

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Atomic – Replicated 


📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce the issue:
![Markup on 2024-01-17 at 21:17:34](https://github.com/Automattic/jetpack/assets/9025643/4806cc2b-dbed-4513-8581-9c3dd3aa6a8e)

📌 ACTIONS
- Triaged

**Comment by taipeicoder** [comment]
This is the same issue as described in p1705518325332349-slack-C05Q5HSS013 and https://github.com/Automattic/jetpack/issues/34992. Essentially, the concatenated stylesheet contains not up-to-date styles.

The PR https://github.com/Automattic/jetpack/pull/35091 by @monsieur-z fixes this issue. I've verified by using the PR branch via Jetpack Beta Tester
 For reference, here are the results:

| Before | After |
| --- | --- |
| ![Screenshot 2024-01-18 at 11 54 44 AM](https://github.com/Automattic/jetpack/assets/797888/d819c2b9-da4d-4257-9b28-945961cc3dd6) | ![Screenshot 2024-01-18 at 11 55 47 AM](https://github.com/Automattic/jetpack/assets/797888/38007513-d064-433f-ac12-8eb80c50eb8f) |

**Comment by taipeicoder** [comment]
While the stylesheet concatenation is fixed as mentioned in https://github.com/Automattic/jetpack/issues/35089#issuecomment-1897755285, the styles don't look quite right. @jcheringer do you know what might be wrong here?

EDIT: Seems that the HTML structure has been changed in a way that some CSS rules are not being applied anymore.
This is the current HTML:

![Screenshot 2024-01-18 at 2 28 14 PM](https://github.com/Automattic/jetpack/assets/797888/3a992346-26ef-42e3-8d5f-8fc1790ea661)

As a result, the following CSS rule will not be applied:

https://github.com/Automattic/jetpack/blob/cbbc34423f7d7dbe383a522124a892f7d47a860f/projects/packages/forms/src/contact-form/css/grunion.css#L633

**Comment by jcheringer** [comment]
@taipeicoder, it's been some time since I was moved to a different team/division, and I'm not actively maintaining Jetpack Forms.
I'm afraid I won't be able to help much here, sorry!
But, based on your comments above, I'd say your insights are correct, and there might be some necessary CSS adjustments.

**Comment by taipeicoder** [comment]
@jcheringer thanks for the notice! 
This seems to be related to pf5801-87-p2 cc: @jcheringer

**Comment by jeherve** [comment]
> Seems that the HTML structure has been changed in a way that some CSS rules are not being applied anymore.

@monsieur-z Do you think you could take a look at this?

Thank you!
