### ISSUE TITLE
Jetpack Forms: Dropdown form element has broken styling on live site

### ISSUE THREAD

**Issue by tellisbethel** [Automattic/jetpack#35094]
### Impacted plugin

Jetpack

### Quick summary

Dropdown form elements added to a form in the editor look fine, but they appear unstyled on the live site. So far I've only seen this on FSE themes.

### Steps to reproduce

1. Activate an FSE theme.
2. Add a Form block (e.g. Registration Block) to a page/post
3. Update and view page and the issue should be visiblw

### A clear and concise description of what you expected to happen.

Form should look like:

<img width="909" alt="Screen Shot 2024-01-17 at 18 14 18" src="https://github.com/Automattic/jetpack/assets/1767799/b047e22a-a5cf-4175-9d23-f7b6d4d96df2">

### What actually happened

On the live site the form looks like this:

![ShcIFe.png](https://github.com/Automattic/jetpack/assets/1767799/3c3dcf6f-eaf7-43ad-a14a-fc5dfb91d365)

### Impact

All

### Available workarounds?

No but the platform is still usable
(Using an alternate form plugin would be a workaround on Atomic sites.)

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by tellisbethel** [comment]
First noticed this here: 7594468-zd-a8c

**Comment by taipeicoder** [comment]
Should be fixed via https://github.com/Automattic/jetpack/pull/35091.

**Comment by kelasante** [comment]
Another report in 7572189-zen

**Comment by taipeicoder** [comment]
@tellisbethel could you see if this issue is still reproducible? Thanks!

**Comment by tellisbethel** [comment]
> @tellisbethel could you see if this issue is still reproducible? Thanks!

@taipeicoder I can confirm the issue has been resolved. :) Thank you!
