### ISSUE TITLE
Publishing in Vkontakte

### ISSUE THREAD

**Issue by david-berg** [Automattic/jetpack#3513]
Will the ability to publish posts in Vkontakte (vk.com) ??
Mainly for Public and groups

**Comment by kraftbj** [comment]
Howdy,

As of now, VK isn't popular enough worldwide for us to put it on our roadmap, but we'll keep our eyes on it.

Related: #849 (Sharing)

**Comment by devcoar** [comment]
@kraftbj Uh, not popular enough? I know that it's far from Facebook (~1,5 bln?), but it has 380 million users worldwide. 
While supported google+ has ~25m. No logic in that.

**Comment by jeherve** [comment]
@devcoar While overall number of users matters, it's not the only factor we take into account. VK, while popular with Russian-speaking users, isn't widely used elsewhere for example. Google+, on the other hand, is.

As @kraftbj mentioned above, we'll keep an eye on this request and revisit this later if needed.

**Comment by artifex404** [comment]
+1

**Comment by artemlime** [comment]
Similar problem with free and premium themes. Everything connected with social networks, a very big problem for Russian and Ukrainian users, because more than 90% of the time they spend in VK.COM.

+1
