### ISSUE TITLE
Sharing Block: Investigate option to have plus button always visible

### ISSUE THREAD

**Issue by andrii-lysenko** [Automattic/jetpack#35143]
We want to investigate if it's possible to have a button that would allow adding additional blocks that will be always visible to the users.
Context: pdtkmj-2dQ-p2#comment-4122

**Comment by jeherve** [comment]
I think I would leave this to Core to improve. We're using Core's tools to build this parent / child block, and we'll automatically benefit from any improvements Core may do to this in the future.

Here are some related discussions:

https://github.com/WordPress/gutenberg/issues/56259
https://github.com/WordPress/gutenberg/issues/39076
https://github.com/WordPress/gutenberg/issues/35261
https://github.com/WordPress/gutenberg/issues/26404
