### ISSUE TITLE
Boost: Jittering when using Image CDN quality slider

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#35151]
![Image](https://github.com/Automattic/jetpack/assets/11799079/f6b76dff-a002-44ac-8f71-c8a85b8acbf3)

Moving the slider every time creates a new request to the server.

![Image](https://github.com/Automattic/jetpack/assets/11799079/1befba66-6991-47e8-ba17-63bac069ff7d)

**Comment by thingalon** [comment]
Fixed by https://github.com/Automattic/jetpack/pull/35222
