### ISSUE TITLE
Add a guide to build jetpack locally

### ISSUE THREAD

**Issue by AjkP** [Automattic/jetpack#3516]
When I tried to venture onto open source contributing to jetpack, it was not clear how I would go about building / running a local development version of jetpack / reproducing issues, or if this is even possible.

#### What I expected
A clear guide to help newcomers get started.

#### What happened instead
There was no clear guide on how to build / run a local dev version of jetpack.

#### Steps to reproduce the issue
Have a newcomer try to come contribute to the project.

**Comment by kraftbj** [comment]
Howdy again @AjkP,

Our most expansive guide is located http://jetpack.me/contribute/

Generally, though, Jetpack requires a connection to WordPress.com for the vast majority of the functionality. While it's possible to setup local environments with [Development Mode](http://jetpack.me/support/development-mode/) or a [Staging Site](http://jetpack.me/support/staging-sites/), it's probably best to setup a test site that can connect to WordPress.com.

I'll update the Contribute link to reflect this. Cheers!
