### ISSUE TITLE
Newsletter Popup: Scrolls to the top on clicking "Continue reading"

### ISSUE THREAD

**Issue by marutim** [Automattic/jetpack#35169]
### Quick summary

You need to have the Newsletter popup enabled for this.

Go to a post and when the newsletter popup appears, scroll the page to the bottom and then click on "Continue reading". You will see the post scrolling to the top and not staying where the post was scrolled to.

Video: 

https://github.com/Automattic/bugomattic/assets/3498917/d62c6a17-20b3-48b2-a300-f082bc9edc9d

### Steps to reproduce

1. You will need Newsletter popup enabled for this. You can do that from WordPress.com > My Sites > Settings > Newsletter > Subscriptions > Enable Subscription Pop-up
2. Go to a new post and wait till the newsletter pop up appears.
3. Scroll the post  and then click on the "Continue reading" link
4. The post scrolls to the top of the post and does not stay where the post was scrolled to

### Browser

Google Chrome/Chromium, Mozilla Firefox, Mac Safari

### Other notes

I can only replicate this in AT sites and not in Simple sites.

**Comment by danjjohnson** [comment]
Also reported here: https://wordpress.org/support/topic/subscriber-popup-button/

**Comment by pkuliga** [comment]
Closing this one since it has been fixed a couple of weeks ago.

https://github.com/Automattic/jetpack/pull/34963

Please reopen if needed.
