### ISSUE TITLE
AI Assistant: error banner can render outside viewport

### ISSUE THREAD

**Issue by CGastrell** [Automattic/jetpack#35162]
When generated content is large enough so the top of the block is not visible, a failing request would be invisible to the user.

Ref: p1705776341148269-slack-C02TQF5VAJD

- I enter something to generate the content, it gets generated.
- I adjust the request and it’s now nonsense AI cannot generate content for.
- The block returns an error, but the error is too high and cannot be seen because there’s too much content in the block already. So users might be confused why the request doesn’t go through, and don’t see why.

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
Tested on Atomic – Could Not Replicate

## 📌 ACTIONS ##
- Author feedback

##Message to author##
Thanks so much for the report @CGastrell 

I couldn't replicate the issue. Are you still able to produce this on a number of sites? Feel free to reopen if you can still replicate and if possible share a screenshot or screencast. This was what I saw.

![Image](https://github.com/Automattic/jetpack/assets/13706336/7681fc7e-cc4b-46e5-b757-0198cffdc914)

**Comment by lhkowalski** [comment]
@rickmgithub thank you for taking the time to test it further. I think the bug will only be visible when the generated content is long enough so the block height becomes higher than the available screen height. This way, the error message gets out of viewport. I will try to reproduce with a prompt asking for "5 long paragraphs about [something]" and get back here.

**Comment by lhkowalski** [comment]
Reopening since I was able to reproduce the issue when the content is longer than the viewport.
