### ISSUE TITLE
Featured Content: Allow setting get_posts suppress_filters

### ISSUE THREAD

**Issue by sketchbuch** [Automattic/jetpack#3517]
How can you change the arguments supplied to get_posts() in get_featured_posts() in the class Featured_Content?

I need to set 'suppress_filters' => false.

A theme that I uses uses the featured content of jetpack and sometimes the content shows the wrong content. I'm also using WPML.

The devs at WPML suggested I set 'suppress_filters' => false in the call to get_posts() in featured_content so I need a away of being able to set additional arguments.

How can this be done?

**Comment by kraftbj** [comment]
Notes: get_posts defaults `supress_filters`to true, which Featured Content uses without modification. 

@sbtypo3 - I don't believe there's a way to modify this behavior at this time. I've made this ticket an enhancement request to be considered in the future.

**Comment by kraftbj** [comment]
The `suppress_filters` concern was addressed and fixed in #8625.
