### ISSUE TITLE
Boost: Toggling modules on/off quickly results in a lot of requests to the server

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#35188]
I went a bit crazy, because I was trying to reproduce the "flipping back and forth between module states" bug, but it's simple to reproduce just by clicking on a single toggle multiple times and observing the network tab.

![Image](https://github.com/Automattic/jetpack/assets/11799079/e2e868ed-79ab-4b27-8426-50eb8d4fafd1)

**Comment by pyronaur** [comment]
Beautiful ❤️

**Comment by haqadn** [comment]
This is related to image CDN quality settings. Ones we have a proper solution for that, we can replicate it here. #35151

**Comment by thingalon** [comment]
Now that https://github.com/Automattic/jetpack/pull/35222 is out and working, the same fix can be applied to this, right?

**Comment by haqadn** [comment]
Yes

**Comment by haqadn** [comment]
Addressed via #35253
