### ISSUE TITLE
Payment blocks not working

### ISSUE THREAD

**Issue by dolgelukkig** [Automattic/jetpack#35191]
### Impacted plugin

None / Other

### Quick summary

The Payment block is not working

### Steps to reproduce

Open your site at WordPress.com
Create a page and add a payment block to the page
Set up a payment plan and connect Stripe
Publish the page and try to make the payment. 

### A clear and concise description of what you expected to happen.

I expected the payment block to open a popup with he option to make the payment. 

### What actually happened

Nothing

https://d.pr/v/zgzkE6

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Tested on the Starter and Explorer plan and also tested multiple themes. 

Reported here: 7626754

**Comment by kerrynicl** [comment]
I have a user that is unable to add the Paypal block. I'm not sure if this is related. 7599026-zen

**Comment by OgeAmadi** [comment]
The user's description 👉 "_when you click on the button on my website, the card payment button doesn't work._" - 7627577-zen

**Comment by samiff** [comment]
Thanks for the report! This should have been fixed by: https://github.com/Automattic/jetpack/pull/35192

Which has now been deployed to simple wpcom. Please let us know if there are any additional issues 👍
