### ISSUE TITLE
gist oEmbeds broken

### ISSUE THREAD

**Issue by CFXd** [Automattic/jetpack#3519]
#### What I expected
When I embed one specific file from a gist (e.g. `[gist file="create_date_column_for_issues.php"]https://gist.github.com/CFXd/8e7927848100d4cd4d6d[/gist]`) then the gist should output and embed.

#### What happened instead
Resulting markup from the above example:

```html
<style>.gist table { margin-bottom: 0; }</style>
<div class="gist-oembed" data-gist="CFXd/8e7927848100d4cd4d6d.json?file=create_date_column_for_issues.php"></div>
```

#### Steps to reproduce the issue
Follow the example above on any gist with multiple files and specify one file in your embed code.

#### Last known working version
3.7

#### Interesting to note
If I simply enter the gist URL in my post content then all of the previous gist with file arguments embeds work, but it then also displays the entire gist's files yet again.

**Comment by eliorivero** [comment]
Hi @CFXd thanks for the report! I've just added a patch at #3520 that it's awaiting review so this will be fixed soon (although not in maintenance version 3.9.3 that we're about to release).
Feel free to test the code of the pull request and let us know how it goes. Cheers!

**Comment by CFXd** [comment]
Looks good to me so far, thanks for the quick fix!

**Comment by CFXd** [comment]
This worked when I first tried it, however I just added an SSL to my server and now it does not. There are no console errors, no insecure sources being loaded, or any readily apparent issues with the SSL implementation and it passes [Quality SSL Labs's test](https://www.ssllabs.com/ssltest/index.html) with an A rating.

**Comment by eliorivero** [comment]
<img width="606" alt="gistssl" src="https://cloud.githubusercontent.com/assets/1041600/13703984/2e6835f6-e778-11e5-9af4-3422bc4e8fb6.png">
Hi @CFXd this was tested in a SSL server and I could load different gists including yours, both a specific file and the complete gist. Can you verify in Chrome Dev Tools > Network > JS and see if you have something odd for the gists?

**Comment by CFXd** [comment]
The gists aren't even there unfortunately. No console errors either.

**Comment by eliorivero** [comment]
Oh, so you don't even get the entry in Network panel? Then perhaps there's an error happening before the shortcode is run? Do you have `WP_DEBUG` enabled in `wp-config.php` [to see the errors](https://codex.wordpress.org/Debugging_in_WordPress#Example_wp-config.php_for_Debugging)? You could try enabling `WP_DEBUG_LOG` and check for errors in `/wp-content/debug.log`

**Comment by CFXd** [comment]
My mistake, it does seem to work. I was installing and patching it with Composer but editing the file manually did the trick. Thanks again!

**Comment by eliorivero** [comment]
Oh that's great! I'm glad you figured it out, thanks for confirming it works!
