### ISSUE TITLE
Heartbeat API for Custom CSS

### ISSUE THREAD

**Issue by alexphelps** [Automattic/jetpack#352]
As a multisite multi-team custom css user I sometimes step on the toes of someone else editing the same style sheet. 

It would be great if the Custom CSS module used the heartbeat api to let a user know if someone else was editing the stylesheet and block/request permission to take over just like posts.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
