### ISSUE TITLE
[Boost] Pass errors back to the Cache UI when setup fails

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#35215]
When Boost Cache is enabled, it must interact with the filesystem. That may fail if FS permissions don't allow wp-config.php to be modified or a file to be created in wp-content.
The setup function must be able to signal to the settings page UI that an error has occurred, and offer advice on how to fix it.

**Comment by thingalon** [comment]
This seems to be tackled by https://github.com/Automattic/jetpack/pull/35568 so I will assign this to @dilirity  and mark as in-progress. It can be closed when https://github.com/Automattic/jetpack/pull/35568 and the UI that shows errors is finished.

**Comment by dilirity** [comment]
As @thingalon mentioned, this was addressed in https://github.com/Automattic/jetpack/pull/35568.
