### ISSUE TITLE
Premium Blocks: Audio and Cover don't show the premium indicator

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/jetpack#35213]
### Impacted plugin

Jetpack

### Quick summary

Related to https://github.com/Automattic/jetpack/pull/16611 https://github.com/Automattic/jetpack/pull/16696

It's only affecting free users. 

The Audio and Cover blocks don't show the premium indicator when they should because uploading audio files or, in the case of the Cover block, a video background is only available for paid customers.

<img width="643" alt="Screenshot 2567-01-24 at 14 31 43" src="https://github.com/Automattic/jetpack/assets/1881481/a1d85d3f-e489-4fe1-92b3-b312697c0a16">

<img width="638" alt="Screenshot 2567-01-24 at 14 31 26" src="https://github.com/Automattic/jetpack/assets/1881481/80979b9d-29d4-4ee7-9919-0647909343ae">

### Steps to reproduce

On a WordPress.com free site, search for the Cover and Audio blocks on the editor's block inserter.

### A clear and concise description of what you expected to happen.

Audio and Cover blocks should show the premium indicator (a red dot) as the other paid blocks.

### What actually happened

They don't show the premium indicator.

<img width="189" alt="Screenshot 2567-01-24 at 14 00 55" src="https://github.com/Automattic/jetpack/assets/1881481/2a89e9cc-4893-4e9d-916a-305470cf43f3">

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
Replicated as per OP description. I can't see any differentiator either.

## 📌 ACTIONS ##
Triaged

**Comment by jeherve** [comment]
This was done on purpose when the upgrade nudges were redesigned in #16611. Here is the specific commit:
https://github.com/Automattic/jetpack/commit/46be44963170982f94b9fb2cf6c1bd8f8106569a

I believe the intent is to let site owners know they can still use those blocks with a free plan. We want to only show the nudge when they are trying to upload content that needs an upgrade.

I would be tempted to close this as won't fix, but would be happy to get other opinions on this before I do so. We can certainly revert that change if that's confusing.

**Comment by miksansegundo** [comment]
@jeherve I get your point for the Cover block because it's still usable without a video background on free sites. For the Audio block, which audio format is supported on free sites?

**Comment by jeherve** [comment]
None as far as I know, but you can use the block to insert an audio file hosted elsewhere. That's something quite common for folks running podcasts, for example.

**Comment by jeherve** [comment]
I'll close this one for now, as I believe there isn't much we can do right away. We could see about improving the nudge mechanism to take such "special" use-cases into account, but that will require design and planning I think.
