### ISSUE TITLE
Subscriptions: Email address is ignored if you're signed into WordPress.com with a different email

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#35245]
### Impacted plugin

Jetpack

### Quick summary

If you're signed into WordPress.com and try to subscribe to a site using a different email address, it will ignore the address you enter and subscribe you using your logged in WordPress.com address instead.

### Steps to reproduce

1. Sign into WordPress.com with email address A.
2. Subscribe to any site by entering email address B.
3. The confirmation will show that you have been subscribed as email address A.

### A clear and concise description of what you expected to happen.

I expected to be subscribed with the email address I entered.

### What actually happened

The email address I entered was ignored and I was instead subscribed as the email address I was logged into WordPress.com as.

<img width="747" alt="image" src="https://github.com/Automattic/jetpack/assets/1990037/65838a8c-2eef-41a8-95cc-35ff3826c80f">

<img width="745" alt="image" src="https://github.com/Automattic/jetpack/assets/1990037/cbd37044-846d-4a76-a258-d3782ff953cf">

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by anomiex** [comment]
I note that the change in #34982, coming in Jetpack 13.1, has already addressed this by not allowing the entry of a different email address when logged in to WordPress.com.

**Comment by pkuliga** [comment]
Closing it since https://github.com/Automattic/jetpack/pull/34982 is already merged and the issue has been fixed.
