### ISSUE TITLE
Dynamically create Photon URL transformation params for lazy loaded images

### ISSUE THREAD

**Issue by asafm7** [Automattic/jetpack#35242]
### Impacted plugin

Jetpack

### What

Dynamically create Photon transformation URLs for lazy loaded images

### How

This [new feature plugin](https://en-gb.wordpress.org/plugins/auto-sizes/) made me think of this option:

What if Photon could dynamically change the transformation params in the `src` of a lazy loaded image in accordance with its actual current size (if I understand correctly, for lazy loaded images, this information is already available).

This can be done either on page load (but the question is if the `src` change will force loading the image even if it is still out of the viewport. ChatGPT and Bard gave me conflicting answers), or when the image scrolls into view (assuming it is possible to make sure it kicks-in before the native HTML lazy loading mechanism).

Benefits:
- Precise resizing vs `srcset` list of predefined sizes. (Sometimes the closest `srcset` size can be twice the actual size of the image).
- No need for size registrations and calculations.
- It can be mostly independent of the method the image was added to the HTML (Blocks/Classic Editor/PHP code etc.).
- I assume the above can make a lot of code redundant, possibly improving performance and simplifying the plugin?

Of course, eagerly loaded images would still need to be treated.

**Comment by jeherve** [comment]
I do not believe that may be very useful, since the images themselves do not get loaded when the image tag uses the `loading` attribute. The exact URL of those images consequently does not matter much until the image gets loaded.

The image size attributes can matter as the HTML Standard discussion in https://github.com/whatwg/html/issues/4654 points out. I believe that will be handled by that featured plugin, and Jetpack's image CDN may not get into play here.

cc @Automattic/heart-of-gold who may have additional ideas on this.

**Comment by asafm7** [comment]
Thanks @jeherve.

I just want to make sure we understand each other.

> since the images themselves do not get loaded when the image tag uses the loading attribute. The exact URL of those images consequently does not matter much until the image gets loaded.

That is true. But it does matter when they are finally loaded: smaller, better-optimized images would be loaded - resulting in a lighter and snappier page experience. 

Did you mean it won't matter to the page loading speed?

This is true, as it is being taken care of by `loading="lazy"`.

But, Google seems to be moving away from just measuring the page load, to 'measurement of responsiveness throughout the page lifecycle':
https://web.dev/articles/inp#:~:text=careful%20measurement%20of%20responsiveness%20throughout%20the%20page%20lifecycle%20is%20important.%20This%20is%20what%20the%20INP%20metric%20assesses

Taking this into consideration, loading optimized images, even if not loaded on page load, can be a great improvement.

(Also, maybe not consuming unnecessary bandwidth can help the environment. I'm not an expert though.)

**Comment by pyronaur** [comment]
Hey @asafm7 - I've self-assigned this, I'll take a closer look at the idea and get back to you in a couple of days. This does seem an interesting idea, but there are quite a few unknowns for me at this point.

**Comment by asafm7** [comment]
Thanks @pyronaur. Looking forward to hearing your thoughts!

**Comment by asafm7** [comment]
@pyronaur do you have any thoughts on this by any chance?

**Comment by pyronaur** [comment]
Sorry, this fell off my radar. I'll have a look next week!

**Comment by asafm7** [comment]
Thanks, @pyronaur.

**Comment by pyronaur** [comment]
Howdy! I apologize for taking so long to get here 😅.

I've reviewed the new specification and did a bit of brainstorming with the team, I think this makes sense. The question that still remains is what kind of performance impact would this have on a page and user experience.

One point I wanted to highlight though is this:

> No need for size registrations and calculations.

I think this isn't a realistic expectation - as you mention - these are needed for eagerly loaded images, - but also for browsers that have JavaScript disabled. Both of those would still benefit from defining sizes, so this wouldn't really make defining proper sizes obsolete. But it could help sites that have sub-optimal image size configuration.

More to come - I need to set-up a prototype to see how well this could perform and if it's worth pursuing as a Jetpack Boost module.

**Comment by asafm7** [comment]
Thanks, @pyronaur.

> But it could help sites that have sub-optimal image size configuration.

I might be wrong, but I think no site has an optimal image size configuration. I don't think it's possible.

The simplest example is an image that is supposed to stretch to the full width of the screen on mobile: there are many possible screen sizes and widths, so the registered size will seldom be the actual width of the screen.

The most common mobile screen resolution is 360×800 with 11.01%. But 414×896 and 412×915 have a combined popularity of 10.55%. (https://www.browserstack.com/guide/ideal-screen-sizes-for-responsive-design)

So, assuming we don't register an image size for every possible mobile screen size, we'll probably opt for registering a size for mobile which is _at least_ 414px wide.

For a square image, this is **32% bigger** than required for the most common screen size of 360×800: (414x414)/(360x360).

I think this can add up to significant bandwidth.

> The question that still remains is what kind of performance impact would this have on a page and user experience.

Considering the bandwidth, maybe there is also an environmental aspect?

Thanks again.

Looking forward to updates.

**Comment by pyronaur** [comment]
> I might be wrong, but I think no site has an optimal image size configuration. I don't think it's possible.

You're spot on. But optimal is different from perfect 😉. 

> Considering the bandwidth, maybe there is also an environmental aspect?

If you're optimizing single site by hand, there's a lot you can do to get closer to perfect. However, for a performance plugin - we have to find a delicate balance between where we can have the largest impact.

For example, is it worth optimizing 32% of a the average 50kb image size for 5000 sites, or is it better to spend that time developing a solution that reduces 5mb to 50kb for 50 sites. (the numbers work out to 80mb saved in the first scenario, and ~250mb in the second - they're completely imaginary numbers, just to illustrate that we need to think in unintuitive ways when considering these things from a plugin standpoint)

**Comment by asafm7** [comment]
Oh, sure. Prioritization is always essential. Just trying to advocate the benefits of the feature :)

**Comment by pyronaur** [comment]
All good, I'm already sold on the idea - I just need a bit of time to validate it.

**Comment by pyronaur** [comment]
👋  Hey @asafm7 - just an update. I'm moving forward to implement this in the Jetpack Boost CDN module. I don't have an ETA yet, and it's not guaranteed to see the light of day at this stage - but I just wanted to let you know that we agree, this looks like a good idea and we're going to try to pursue this further.

**Comment by asafm7** [comment]
That's great, @pyronaur. Thanks for the update!

BTW, I'm using the main Jetpack plugin for the CDN, not Jetpack Boost. Do they have different CDN features and capabilities?

**Comment by pyronaur** [comment]
Yes - Jetpack Boost is a performance plugin. The CDN doesn't currently have different CDN features - but anything that's new and performance related we're building into Boost.

**Comment by asafm7** [comment]
Thanks, @pyronaur.

**Comment by asafm7** [comment]
@pyronaur, is this the feature?

https://github.com/Automattic/jetpack/commit/84584b1ce67b740ab1ee78cdbd44f878457f781c

**Comment by pyronaur** [comment]
@asafm7 👋  Sorry, I missed the ping. Yes - that's the feature. Thank you for recommending it. Because this puts an extra burden on the CDN, we couldn't roll this into the free tier. Do you have premium Jetpack Boost subscription?

**Comment by asafm7** [comment]
@pyronaur, it's great to see the feature has been implemented.

Unfortunately, I don't have a Jetpack Boost subscription, so I won't be able to use it.

**Comment by pyronaur** [comment]
Can you send us a mail to jetpackboost@automattic.com and we can work something out 🙂 (reference this issue in the mail).

**Comment by pyronaur** [comment]
Marking as resolved. Thank you @asafm7 for the suggestion 🙏
