### ISSUE TITLE
Forms block: "submit" button text can't be centered

### ISSUE THREAD

**Issue by tvolpert** [Automattic/jetpack#35268]
### Impacted plugin

Jetpack

### Quick summary

The "submit" button on the Jetpack form is rendered as `inline-flex` on the font end of the site, but not in the editor. The CSS doesn't have a `justify-content: center` in place (it does have an `align-items: center` but of course this is only going to create _vertical_ centering on a flexbox set to row...), so on the live site the button text is left-aligned, even though it is centered in the editor. This is most noticeable when the button is set to 75 or 100% width and you have a huge empty space to the right of your text

<img width="1058" alt="Screenshot 2024-01-25 at 4 12 47 PM" src="https://github.com/Automattic/jetpack/assets/34486913/20b87c28-0b08-4a14-87ea-e44ad9bd7733">

### Steps to reproduce

1. insert a Form block to any page or post
2. set the "submit" button width to 100%
3. save your changes and view the live page
4. your button text will be all the way over on the left

### Impact

All

### Available workarounds?

Yes, difficult to implement

### Logs or notes

The snippet of CSS below will correct the problem. My question would be why we're making the _button_ itself a flexbox when it's literally only going to contain a single text node? But assuming there's some reasoning behind that, this will center the text at least:

```
/* center contact form button text | 7640536-zen tcrv */
.contact-form :is([type=submit],button:not([type=reset])) {
    justify-content: center;
}
/* End | 7640536-zen tcrv */
```

**Comment by tvolpert** [comment]
reported in #7640536-zen

**Comment by cat-og** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated 
- Tested on Atomic – Replicated


📌 FINDINGS/SCREENSHOTS/VIDEO
- Form while editing:
<img width="1290" alt="Markup 2024-01-25 at 21 03 04" src="https://github.com/Automattic/jetpack/assets/86028337/82d7b176-fd8e-4db6-bfa0-b700b0daedb5">



- Form on live site: 
<img width="1254" alt="Markup 2024-01-25 at 21 01 36" src="https://github.com/Automattic/jetpack/assets/86028337/54830b56-5b4f-4e68-a53a-42e543b56c26">


📌 ACTIONS
- Triaged

**Comment by jerrysarcastic** [comment]
Reported in https://wordpress.com/forums/topic/center-text-within-form-button

**Comment by monsieur-z** [comment]
This should be fixed by https://github.com/Automattic/jetpack/pull/35319.

> My question would be why we're making the button itself a flexbox when it's literally only going to contain a single text node?

The content is not always textual only. For instance, the submit button shows a spinning loader on submitting the form.
