### ISSUE TITLE
Class "Automattic\Jetpack\Backup\Package_Version" not found when updating via WP-CLI

### ISSUE THREAD

**Issue by rilwis** [Automattic/jetpack#35270]
### Impacted plugin

Backup

### Quick summary

When updating Jetpack from version 12.9.1 to version 13.0 via WP-CLI, I got this error message:

```bash
PHP Fatal error:  Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class "Automattic\Jetpack\Backup\Package_Version" not found in /var/www/wpautolistings.com/wp-includes/class-wp-hook.php:324
Stack trace:
#0 /var/www/wpautolistings.com/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#1 /var/www/wpautolistings.com/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-connection/src/class-package-version-tracker.php(45): apply_filters()
#2 /var/www/wpautolistings.com/wp-includes/class-wp-hook.php(324): Automattic\Jetpack\Connection\Package_Version_Tracker->maybe_update_package_versions()
#3 /var/www/wpautolistings.com/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#4 /var/www/wpautolistings.com/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /var/www/wpautolistings.com/wp-includes/load.php(1260): do_action()
#6 [internal function]: shutdown_action_hook()
#7 {main}
  thrown in /var/www/wpautolistings.com/wp-includes/class-wp-hook.php on line 324
```

### Steps to reproduce

1. Use CLI to `cd` to a site with Jetpack 12.9.1 installed
2. Run `wp plugin update --all`
3. Got the error message

### A clear and concise description of what you expected to happen.

It should shows the update success message instead of the fatal error.

### What actually happened

The fatal error above.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

Server is using Ubuntu 22.04, Apache, PHP 8.1

**Comment by anomiex** [comment]
Internal discussion reference: p1705089030985119-slack-CBG1CP4EN

What's going on is that 12.9 registers a shutdown function during start-up, then the upgrade happens which happens to rename the class containing the registered function. So by the time the shutdown runs the class can no longer be found.

**Comment by bhoop** [comment]
@jeherve was it intentional that this was assigned to the Scan team and not the Backup team?

**Comment by jwebbdev** [comment]
We've resolved this in a new version of the backup package in Jetpack 13.1.3 and Jetpack VaultPress Backup 2.5 so it shouldn't be a problem going forward.
