### ISSUE TITLE
Boost: Multiple track events to CTA called just by opening admin page

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#35275]
This is on 3.0.0-beta just by refreshing the page. I have set up free Boost.

![Image](https://github.com/Automattic/jetpack/assets/11799079/460e0e2a-3173-43ae-8b77-c881c9ace1ad)

**Comment by thingalon** [comment]
Reviewing the events, you see:
- `boost_view_upsell_cta_in_settings_page_in_plugin` twice, and
- `boost_page_view_settings`.

The only problem I see is that the first is called twice. One tracks the upsell being shown in the settings page, the other tracks that you viewed the settings page.

**Comment by dilirity** [comment]
Is this something we should fix or is it okay?

**Comment by thingalon** [comment]
It seems like something worth investigating / fixing. It wasn't a blocker to the 3.0.0 release, but it'd be nice to avoid double events.

**Comment by dilirity** [comment]
I decided to remove `boost_view_upsell_cta_in_settings_page_in_plugin` in #36216, as it doesn't make sense to have such an event.

The name also suggests that the user views it, which might not always be the case, as users might see the top one, but not the bottom one. It's always triggered when the upgrade CTA is mounted (which in our case is 2 times in the main Settings page).
