### ISSUE TITLE
Image CDN: unserialize(): Unexpected end of serialized data

### ISSUE THREAD

**Issue by asafm7** [Automattic/jetpack#35284]
### Impacted plugin

Jetpack

### Quick summary

This is just a PHP notice, but it may be a sign of another issue:

wp-includes/functions.php:650
unserialize()
wp-includes/functions.php:650
maybe_unserialize()
wp-includes/meta.php:661
get_metadata_raw()
wp-includes/meta.php:574
get_metadata()
wp-includes/post.php:2526
get_post_meta()
wp-includes/post.php:6464
wp_get_attachment_metadata()
wp-includes/media.php:776
image_get_intermediate_size()
wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-image-cdn/src/class-image-cdn.php:760
Automattic\J\I\Image_CDN->filter_image_downsize()
wp-includes/class-wp-hook.php:324
apply_filters('image_downsize')
wp-includes/media.php:207
image_downsize()
wp-includes/media.php:970
wp_get_attachment_image_src()
wp-includes/media.php:1049
wp_get_attachment_image()
wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php:1987
WC_Product->get_image()
wp-content/plugins/woocommerce/src/Blocks/BlockTypes/ProductImage.php:165
Automattic\W\B\B\ProductImage->render_image()
wp-content/plugins/woocommerce/src/Blocks/BlockTypes/ProductImage.php:218
Automattic\W\B\B\ProductImage->render()
wp-content/plugins/woocommerce/src/Blocks/BlockTypes/AbstractBlock.php:88
Automattic\W\B\B\AbstractBlock->render_callback()
wp-includes/class-wp-block.php:258
WP_Block->render()
wp-includes/blocks.php:1484
render_block()
wp-includes/blocks.php:1522
do_blocks()
wp-includes/blocks/block.php:49
render_block_core_block()
wp-includes/class-wp-block.php:258
WP_Block->render()
wp-includes/class-wp-block.php:244
WP_Block->render()
wp-content/plugins/woocommerce/src/Blocks/BlockTypes/ProductTemplate.php:88
Automattic\W\B\B\ProductTemplate->render()
wp-content/plugins/woocommerce/src/Blocks/BlockTypes/AbstractBlock.php:88
Automattic\W\B\B\AbstractBlock->render_callback()
wp-includes/class-wp-block.php:258
WP_Block->render()
wp-includes/class-wp-block.php:244
WP_Block->render()
wp-includes/blocks.php:1484
render_block()
wp-includes/blocks.php:1522
do_blocks()
wp-includes/class-wp-hook.php:324
apply_filters('the_content')
wp-includes/blocks/post-content.php:48
render_block_core_post_content()
wp-includes/class-wp-block.php:258
WP_Block->render()
wp-includes/class-wp-block.php:244
WP_Block->render()
wp-includes/blocks.php:1484
render_block()
wp-includes/blocks.php:1522
do_blocks()
wp-includes/block-template.php:260
get_the_block_template_html()
wp-includes/template-canvas.php:12

### Steps to reproduce

Trace provided.

### Impact

One

### Available workarounds?

There is no user impact

### Logs or notes

- Theme: Loudness By [Automattic](https://wordpress.org/themes/author/automattic/)

**Comment by jeherve** [comment]
Do you use a caching plugin on your site, and / or another plugin that may impact image metadata? If so, could you see if you still experience the issue when you remove those plugins, with freshly uploaded images?

Thank you!

**Comment by asafm7** [comment]
Thanks @jeherve 

It isn't cache, as cache is disabled on my staging environment.

It is weird though. When Jetpack is active, Query Monitor associates the error with Jetpack.

But, I was able to reproduce it with only WooCommerce, Query Monitor, and a default theme active. In this case, the issue is associated with WooCommerce.

I don't know what it is, but Jetpack is probably not the culprit.

Sorry for the bother.
