### ISSUE TITLE
Jetpack AI Search block doesn't appear with Jetpack Search plugin only 

### ISSUE THREAD

**Issue by foleynotrose** [Automattic/jetpack#35289]
### Impacted plugin

Search

### Quick summary

When a site has the standalone Jetpack Search plugin installed (and not the Jetpack plugin), Jetpack AI Search block is not available. 

### Steps to reproduce

1. Install Jetpack Search plugin (make sure Jetpack Plugin is NOT installed) 
2. Create a new post or page
3. Type `/search` to add a new block 

### A clear and concise description of what you expected to happen.

Jetapck AI search block should appear as an option. 

### What actually happened

Jetpack AI search block does not appear unless Jetpack Plugin is activated. 

### Impact

All

### Available workarounds?

Yes, easy to implement

**Comment by jeherve** [comment]
That's indeed expected for now; the block is only built in the Jetpack plugin. That should definitely be fixed as we keep working on the AI Chat block though.

**Comment by gibrown** [comment]
The current plan is to remove Jetpack AI chat, so closing this
