### ISSUE TITLE
[Boost] Can't purchase Boost after abandoning flow

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#35285]
If you cancel out of the Boost purchase flow after connecting your user to Jetpack, then try again you get errors on checkout:

![image](https://github.com/Automattic/jetpack/assets/1369626/6994e9cd-79d9-43b0-a0d9-4d77b5b59e0e)

This problem occurs both on the latest stable release, and on the upcoming 3.0.0-beta release.

**Steps to reproduce**
1. Get a new JN site. (Also works on non-JN sites).
2. Activate Jetpack Boost (doesn’t matter if Jetpack is active or not).
3. Go to the admin.php?page=jetpack-boost#/getting-started and click “Get Boost”. Connect the user, but don’t go through with Checkout.
4. Go to “My Jetpack” and disconnect the site.
5. Go to admin.php?page=jetpack-boost#/getting-started once more and click on “Get Boost” again.
6. You should see the checkout error from the screenshot above.

**Thoughts**
- After disconnecting the site (step 4 above), the second attempt to purchase Boost does *not* take users to the connection screen first.
- The errors on the checkout are to do with permission - the kind you might see if that checkout page requires a user connection.
- However, the checkout flows on wpcom have been updated recently to allow purchases both before or after a user connection has been setup. Could we be sending users to an outdated checkout page/process?
- If user connections are no longer required to buy Jetpack products, do we need a user connection at all?

**Comment by haqadn** [comment]
Fix deployed to Calypso https://github.com/Automattic/wp-calypso/pull/88538
