### ISSUE TITLE
[Boost] Info message not visible on mobile

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#35296]
Clicking the “i” button results in some info text that falls outside the screen bounds.

![Image](https://github.com/Automattic/jetpack/assets/3737780/da7ce92a-77c8-4aa2-a716-2781a45ee313)
![Image](https://github.com/Automattic/jetpack/assets/3737780/ac38522d-cccc-43ab-9297-89c9643f770e)

**Comment by dilirity** [comment]
The first part is addressed https://github.com/Automattic/jetpack/pull/35290

**Comment by dilirity** [comment]
Looking at the resolution again - is this a normal device? I though resolutions like this are no longer available.

What's the minimum we support?
