### ISSUE TITLE
[Boost] Disable caching for logged in users by default

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#35301]
Caching works best when a cache file can be shared among visitors, so it makes sense to not cache pages for logged in users.

However, many sites depend on using cached pages because they have slow servers, even for logged-in users, so we should offer this setting:
1. Cache requests for all visitors.
2. Disable caching for visitors with a local cookie set.
3. Disable caching for logged in visitors.

**Comment by donnchawp** [comment]
We could use a setting called "excluded_visitor" that returns a string matching the excluded visitor type.

```
	/*
	 * Returns a visitor type that should not be cached.
	 * Logged in users will not be cached by default.
	 *
	 * @return string
	 */
	public function get_excluded_visitor() {
		return $this->get( 'excluded_visitors', 'logged_in' ); // logged_in, cookie, none
	}
```

**Comment by thingalon** [comment]
I think for the MVP we should just not cache pages for logged-in users, then add an option in a future release.
