### ISSUE TITLE
[Boost] Add a debug log to Cache module

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#35305]
Make it easier for site owners to debug problems with caching by logging what the plugin does when it is operating.
This will log activities like checking and creating advanced-cache.php, adding WP_CACHE to wp-config.php, getting and saving cache files, etc.

Some discussion here: p1HpG7-r0o-p2

When displaying or downloading the logs, hide requests for wp-admin and wp-json as those requests are never cached.

**Comment by thingalon** [comment]
From our discussion at the team call:

- Log to files with the date in them `YYYY-MM-DD-log.php`
- Prefix the files with `<?php die();`
- Look at the logging function in WP Super Cache -- it uses `error_log` with special parameters to output it to a file.
- We can make the Garbage collector delete the older cache files.
