### ISSUE TITLE
Schema Support for Upcoming Events Widget

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#3531]
Support Schema on the Upcoming Events Widget.

https://schema.org/Event

**Comment by bhubbard** [comment]
Started to take a first crack at this. Found the right file:
https://github.com/Automattic/jetpack/blob/master/_inc/lib/icalendar-reader.php#L719

Update the code to the following:
```php
	if ( 'widget' == $args['context'] ) : ?>
		<ul class="upcoming-events">
			<?php foreach ( $events as $event ) : ?>
			<li itemscope itemtype="http://schema.org/Event">
				<strong class="event-summary" itemprop="name"><?php echo $this->escape( stripslashes( $event['SUMMARY'] ) ); ?></strong>
				<span class="event-when" itemprop="startDate"><?php echo $this->formatted_date( $event ); ?></span>
				<?php if ( ! empty( $event['LOCATION'] ) ) : ?>
					<span class="event-location" itemprop="location" itemscope itemtype="http://schema.org/Place">
						<meta itemprop="name" content="<?php echo $this->escape( stripslashes( $event['SUMMARY'] ) ); ?>">
							<span class="address" itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
								<span itemprop="streetAddress"><?php echo $this->escape( stripslashes( $event['LOCATION'] ) ); ?></span>
							</span>
					</span>
				<?php endif; ?>
				<?php if ( ! empty( $event['DESCRIPTION'] ) ) : ?>
					<span class="event-description" itemprop="description"><?php echo wp_trim_words( $this->escape( stripcslashes( $event['DESCRIPTION'] ) ) ); ?></span>
				<?php endif; ?>
			</li>
			<?php endforeach; ?>
		</ul>
		<?php endif;
```

**Results**
![example-results](https://cloud.githubusercontent.com/assets/3837/13754184/4127488c-e9d3-11e5-99f8-f3e291c2b272.png)

So far it validates, however the problem is the location information. I tired several feeds, some use addresses, some use city/state, etc. Not sure of the best approach yet. Also, while not required, Google highly recommends supporting offers with events and displays a notice about it.

Lastly I tried to test for the shortcode, however it appears the shortcode doesn't work at the moment. Can someone confirm this? @eliorivero

For the shortcode, starting at line 745, there are several titles for the table that also need to be updated to support translations. Although I would also recommend updating the shortcode to display using the same code as the widget.

**Comment by jeherve** [comment]
> it appears the shortcode doesn't work at the moment. Can someone confirm this?

The Upcoming Events Widget is here on GitHub, but it isn't shipped or enabled in Jetpack, as it is not ready for prime time just yet.

**Comment by jeherve** [comment]
#5493

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
