### ISSUE TITLE
UI Issue: Jetpack Newsletter Setting Missing in WP Admin

### ISSUE THREAD

**Issue by JenSwish** [Automattic/jetpack#35310]
### Impacted plugin

Jetpack

### Quick summary

In the WP Admin Settings for Jetpack Newsletters, there is not an option to turn enable/disable featured images from being included in newsletters. This setting does exist in WordPress.com.

Discovered via #7547978-zen.

### Steps to reproduce

**In WP Admin**

1. Go to Jetpack > Settings > Newsletter
2. There is not a toggle switch for turning the featured image on/off for newsletter sends.

**In WordPress.com Dashboard**

1. Go to Settings > Newsletter
2. There is a toggle switch for turning the featured image on/off for newsletter sends.

### A clear and concise description of what you expected to happen.

There should be feature parity between both UI.

### What actually happened

There is not featured parity between both UI.

### Impact

All

### Available workarounds?

Yes, easy to implement

**Comment by jeherve** [comment]
somewhat related: #32007

**Comment by simison** [comment]
This will be sorted with the next JP release, thanks @Automattic/apex 🙌
