### ISSUE TITLE
[Boost] Create a util function for writing cache/config files

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#35331]
On a live site, it's safer to write data to a temporary file and then rename it to the final filename than write the data to a file with the final filename. The rename process is "atomic" and can't be interrupted. If a file is being written to, and another file tries to read from it at the same time the reader may only get a portion of the file.

We need a "write_file" function in the Util class that does this job because it's being used to write the config file as well as cache files.

**Comment by thingalon** [comment]
This is done, right?
