### ISSUE TITLE
Enhancement: Show play button icon for VideoPress videos in Newsletter emails

### ISSUE THREAD

**Issue by dhanson-wp** [Automattic/jetpack#35346]
### Impacted plugin

Jetpack, VideoPress

### What

When an email with a video is delivered, the VideoPress thumbnail is displayed in the email. However, it is not obvious that the email includes a video because you only see an image.

It would be better to include a `Play` icon over the video thumbnail so email recipients can know visually that the emial includes a video. 

### How

Here is a simple mockup of how the email could look.

<img width="650" alt="Markup 2024-01-30 at 11 27 15" src="https://github.com/Automattic/jetpack/assets/83921778/26e1a44a-3e91-4f8a-8a86-06990d4c57c5">

**Comment by simison** [comment]
This is shipped in https://github.com/Automattic/jetpack/issues/37970#issuecomment-2361251144 and the block now has play button in emails 👍
