### ISSUE TITLE
Social: editors- cannot connect their local account to their WordPress.com account

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#35367]
### Impacted plugin

Social

### Quick summary

Non-admins (authors, editors) should be able to connect their own account to WordPress.com on a site that uses the Jetpack Social plugin. It would allow them to connect their own social networks when they write posts on the site. 

### Steps to reproduce

Start with a site where you've installed the Social plugin, and where you've connected that site to your WordPress.com account.

1. Go to Users > Add New and create a new "editor" user.
2. Note down the username and password.
3. In a new browser, access the site's admin using the new credentials.
4. In that browser, go to WordPress.com and log in using a different WordPress.com account.
5. In wp-admin, you will not see a Jetpack > Social menu item; that may be fine since you're not an admin, and should not be able to manage features available in the Social plugin.
6. Go to Posts > Add New
7. There, you will have access to the Social plugin panel.
8. Click on the Connect prompt in that panel to connect one of your social networks.

### A clear and concise description of what you expected to happen.

I expected to be redirected to Jetpack Cloud, where I would complete the connection between my local account and my WordPress.com account, and then be redirected to `https://cloud.jetpack.com/jetpack-social/mysite.com` to connect a Social Network.

### What actually happened

I am redirected to that page, but only see the following prompt:

<img width="861" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/2a8e2796-fe16-4eb1-8d12-d97f8ede485f">

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by manzoorwanijk** [comment]
Editor needs to have a user connection set up in My Jetpack, was that done in those steps?

**Comment by jeherve** [comment]
> Editor needs to have a user connection set up in My Jetpack, was that done in those steps?

No. Should the block editor sidebar UI be updated to offer to connect their account first maybe?

**Comment by manzoorwanijk** [comment]
> > Editor needs to have a user connection set up in My Jetpack, was that done in those steps?
> 
> No. Should the block editor sidebar UI be updated to offer to connect their account first maybe?

Yes, that should be the behaviour.
