### ISSUE TITLE
Admin Bar Stats Graph Broken Image - Extra Bytes At Start of Header Corrupt The Image

### ISSUE THREAD

**Issue by quid246** [Automattic/jetpack#35406]
### Impacted plugin

Jetpack

### Quick summary

Stats graph in the WP Admin bar shows a broken image icon.  The generated image has three extra spaces at the beginning of the file before the PNG header, or "ICAg" if viewed in Base 64.

### Steps to reproduce

1.  Login to Wordpress
2.  Visit Homepage.

### A clear and concise description of what you expected to happen.

Stats should display in the admin bar.

### What actually happened

A broken image icon appears in the admin bar.  This appears due to three extra bytes (spaces) at the beginning of the PNG header, or "ICAg" if Base 64 encoded.
![wp-stats-broken](https://github.com/Automattic/jetpack/assets/1429611/138e9cd8-68c5-4437-974e-81801f4efd6d)
![png-hex-broken](https://github.com/Automattic/jetpack/assets/1429611/fef2fdfe-d44f-451d-87e1-142b58f63eee)
![png-base64-broken](https://github.com/Automattic/jetpack/assets/1429611/65e5e6de-c613-493d-91e3-c45fa6e07432)

### Impact

One

### Available workarounds?

No and the platform is usable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

I tried disabling all plugins, no difference.  This seems to have appeared after most recent update, but only one of my sites is affected.

**Comment by jeherve** [comment]
It may be worth looking at other places where those extra bytes may have been added. It could be whitespace in your site's `wp-config.php` file, for example, if you edited it and left whitespace or saved it with a file editor using the wrong format.
Such whitespace could also be part of your theme.

Could you try switching to a different theme for a few minutes and see if that helps? 

If it doesn't, could you check your `wp-config.php` file and let us know how that goes?

**Comment by quid246** [comment]
Thanks for the prompt reply.  Unfortunately I cannot switch the site completely to another there, as it is a high-traffic production server.  There was a theme update that also happened around the time of the Jetpack update (plus the WP security update), so I did change back to the older version of the theme with no change in the behaviour.

If I attempt to call the image generation PHP file directly in it's own window...  ie.  https://mysite.com/wp-admin/admin.php?page=stats&noheader&proxy&chart=admin-bar-hours-scale  it also displays a broken image.  I would believe at that point that there was little to no interaction with the theme.

Checked through my wp-config.php, did not see any extraneous spaces there, there was no change to this file between when the bar chart was working fine and when it started to display a broken image.  I did remove a couple extra blank lines at the end of the file... but it too did not rectify the behaviour.

**Comment by jeherve** [comment]
Could you contact us [via this contact form](https://jetpack.com/contact-support/?rel=support&hpi=1), so we can look into this some more with you, on your site?

Thank you.

**Comment by quid246** [comment]
Thanks.  I have sent the form with the information and a link back to this Github issue.

**Comment by jos22** [comment]
Resolved in `7682390-zen`
