### ISSUE TITLE
Using portfolio post type locally

### ISSUE THREAD

**Issue by pixedelic** [Automattic/jetpack#3541]
Is there any workaround to use Portfolio locally: I have some clients who ask to see locally how your site will look like before putting it online, and it is impossible for this limitation. 

TIA

**Comment by jeherve** [comment]
You can use [Jetpack's Development mode](http://jetpack.me/support/development-mode/) to work with the plugin in a local environment.

**Comment by pixedelic** [comment]
I'm using it, but I don't see portfolio items anywhere... am I missing something?

**Comment by pixedelic** [comment]
Sorry, shame on me, was using the wrong method! Many apologies
