### ISSUE TITLE
Sharing Buttons: Add SMS sharing button

### ISSUE THREAD

**Issue by andrii-lysenko** [Automattic/jetpack#35426]
Context: pdHDFB-J-p2

**Comment by andrii-lysenko** [comment]
@keoshi @jeherve  What do you think about this behavior?

https://github.com/Automattic/jetpack/assets/60262784/3361d923-4c94-498f-98c4-e864cbad599c

As per hiding the button for unsupported devices, we are actually might not be able to distinct this accurately. I remember someone mentioned that maybe, the way to go in such situations, is to have a separate block or feature (like a group that will be shown on one devices and hidden for others). What do you think?

**Comment by keoshi** [comment]
That looks great to me and what I would expect to happen.

**Comment by andrii-lysenko** [comment]
We decided to close this for now as we can't insure 100% quality of this feature.
More details: pf5801-GC-p2
