### ISSUE TITLE
Jetpack Social: Can't dismiss CTA to connect Instagram

### ISSUE THREAD

**Issue by jenhooks** [Automattic/jetpack#35433]
### Impacted plugin

Social

### Quick summary

In the Jetpack settings for a post in WP Admin, the call-to-action to connect Instagram to Jetpack Social is not dismissible.

### Steps to reproduce

1. Install and connect Jetpack with Jetpack Social activated
2. Create a new post
3. Open the Jetpack settings in the post editor
4. Attempt to close the prompt to connect Jetpack Social to Instagram
5. You should observe that the box will not close

### A clear and concise description of what you expected to happen.

I expected the call-to-action to connect Jetpack to close when I click the X. 

### What actually happened

Clicking the X to dismiss the box does nothing. 

https://github.com/Automattic/jetpack/assets/7585054/6c2f1cd8-ba42-49c3-ad96-b4e37b901a07

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by liviopv** [comment]
📌 ACTIONS
- Marking as Triaged since it's already on Reach's board.
