### ISSUE TITLE
Feature Request: Release post stats block

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#35436]
### Impacted plugin

Jetpack

### What

The block is currently in beta. We'll need to test it more thoroughly, fix issues and then release it.

![image](https://github.com/Automattic/jetpack/assets/1425433/b8740ebd-f50f-485c-ac9f-2d18542d8a66)

### How

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/jetpack/pull/34557
- [ ] https://github.com/Automattic/jetpack/issues/35437
```

cc @Aurorum

**Comment by Aurorum** [comment]
Feel free to ping me for any bugs or if there’s anything I can do to help. :)

**Comment by kangzj** [comment]
Thanks everyone for making this possible! 👍

**Comment by Aurorum** [comment]
Always wanted to work on a Gutenberg block, so this has been really fun - thank you @kangzj!
