### ISSUE TITLE
monitoring in multisite 

### ISSUE THREAD

**Issue by camaran** [Automattic/jetpack#3544]
In multisite installation is possible to permit enable monitoring only for one site?

**Comment by jeherve** [comment]
You could deactivate Monitor manually on all sites but one, or force-deactivate it manually with a network-activated plugin.

Something like this should do the trick:

```php
/**
 * Deactivate Monitor on all sites but one.
 */
function jeherve_deactivate_monitor() {
	if (
		( class_exists( 'Jetpack' ) && Jetpack::is_module_active( 'monitor' ) )
		&& ( ! '5' == get_current_blog_id() )
	) {
		Jetpack::deactivate_module(  'monitor' );
	}
}
add_action( 'init', 'jeherve_deactivate_monitor' );
```

Once the modules are deactivated on all sites but one, you can get rid of that code.
