### ISSUE TITLE
Images appear out of scale on Newsletter Emails

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/jetpack#35464]
### Impacted plugin

None / Other

### Quick summary

Customer is experiencing inconsistencies in image sizes in their newsletter. They mentioned that the images look great on their website, but some appear big and others appear small in the newsletter. This issue started a few weeks ago and they have not made any changes to their process. It seems to happen randomly too.

![IMG_2338](https://github.com/Automattic/jetpack/assets/31009008/61bd7dc4-2d3c-4086-87a9-091cdd96d190)

![IMG_2337](https://github.com/Automattic/jetpack/assets/31009008/7126d4c6-5c48-40f8-b655-05af6c1f31ab)

User report at 7699203-zen.

### Steps to reproduce

1. On a WordPress.com "simple" site, ensure the site Newsletter feature is enabled and set up under My Site > Settings > Newsletters
2. Create a blog post with Image blocks.
3. Publish the post.
4. Check the email sent out from Newsletter module.

### A clear and concise description of what you expected to happen.

Images should all show as set up on the post, at proper scale.

### What actually happened

Some images are scaled down, showing like Thumbnails, almost.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by jeherve** [comment]
Related: #34517

**Comment by katiebethbrown** [comment]
Just adding a +1, running into this on a 51 partner site.

**Comment by lezama** [comment]
Noting that the big first image in these emails is the featured image and that's why it shows bigger than the others in this case. Said that images should respect better their post attributes.

**Comment by lezama** [comment]
The 🙃  images in the ticket are "single image galleries", that's why they render particularly 🙃 

Said that I am working on D147624-code to improve rendering of galleries inside emails.

**Comment by lezama** [comment]
improvement to how Galleries are rendered was shipped!
