### ISSUE TITLE
SetCookie headers jetpackState results in 500 errors with Nginx in request path (including CloudFlare)

### ISSUE THREAD

**Issue by joshkoenig** [Automattic/jetpack#3546]
#### What I expected

JetPack installation works. 
#### What happened instead

On final authorization, an error is delivered from the webserver (not WordPress).

Nginx and Varnish users have both reported issues that appear to be occurring due to the number of `SetCookie: jetpackState[some_state]` headers. These headers duplicate `SetCookie` directives for a number of `some_state` values, meaning they will not be reliably interpreted by browsers, and are likely not necessary.

For example, this is the root cause of this failure under roots.io's nginx setup: h

https://github.com/roots/trellis/issues/323

It's also easily replicable on Pantheon (where I have an interest in things working smoothly.) It occurs when installing JetPack fresh, and can also be replicated by bulk-enabling a large number of features. 
#### Steps to reproduce the issue

Install JetPack on a fresh WP site on Pantheon (it's free!). You'll get a 503 error on activation at the end. Captured headers look like:

https://gist.github.com/joshkoenig/7c436c4f158b106eb8e2

Disabling and re-enabling will replicate. You can also replicate by bulk-enabling features. 

However, JetPack installation is ultimately successful (e.g. if you releoad it works).  We're looking into why this loop is happening, but generally speaking on the JetPack side the setting of these state cookies could probably be smarter.

**Comment by jeherve** [comment]
This also happens when using CloudFlare, as discussed internally in p1HpG7-38V-p2

**Comment by BFTrick** [comment]
This issue is just over a year old. Any movement on it? Would be nice to take it off of the [known issues list here](https://pantheon.io/docs/unsupported-modules-plugins/#jetpack). 

Not sure on exact numbers but I imagine there's quite a few people on Pantheon and their first experience of Jetpack is an error. :(

**Comment by joshkoenig** [comment]
Anyone running JetPack with Nginx as their webserver has this experience, so it's much bigger than us.

**Comment by jenhooks** [comment]
3168063-t

**Comment by beaulebens** [comment]
I see this on a new server running Plesk Onyx as well (which uses a combination of nginx and Apache). It shows up in the logs as;

`16042#0: *115095 upstream sent too big header while reading response header from upstream`

and during the connection flow I see this:

![screen_shot_2017-05-02_at_12_56_35_pm](https://cloud.githubusercontent.com/assets/108942/25634345/7d0a53b2-2f37-11e7-8855-15c1a7e27431.png)

Clicking the Try Again button works, and takes me through to wp-admin, where it says "Your Jetpack is already connected".

**Comment by cbovis** [comment]
We're experiencing this issue after trying to activate the Jetpack plugin on a Pantheon site, the workaround that @joshkoenig mentioned is not working for us. Can you confirm if the workaround is no longer valid @joshkoenig?

**Comment by joshkoenig** [comment]
@cbovis - in my testing before JetPack would install, but the success message causes nginx to bite the dust because it contains a million cookie headers. I don't have a "workaround" per-se.

However, I have not tested this recently. If you're now saying you _cannot install_ JetPack, that could be a new or separate issue.

**Comment by kraftbj** [comment]
We push out what fixes this in our tests in #7322 by, basically, just not trying to set the whole batch of cookies we were during the connection that process that we think aren't actually needed (going to sleep on it to make sure we're not missing anything) if anyone is game for testing it.
