### ISSUE TITLE
Jetpack Connection: feature list in connect account page is not read as such by VoiceOver

### ISSUE THREAD

**Issue by monsieur-z** [Automattic/jetpack#35485]
In the "Connect Account" page, the feature list is not read as such with VoiceOver, which makes it harder to parse/skip. The CSS rule `list-style-type: none;` [prevents VoiceOver from identifying unordered lists](https://href.li/?https://gerardkcohen.me/writing/2017/voiceover-list-style-type.html). Adding the attribute role="list" should fix it.

Issue reported in p1HpG7-qVW-p2.

<img width="434" alt="Screenshot 2024-02-13 at 2 53 31 PM" src="https://github.com/Automattic/jetpack/assets/1620183/d9b4bf05-3b77-4d2a-aee6-e5a587820a9e">

---

- Let's see if we can spot similar issues in the rest of the plugin

**Comment by monsieur-z** [comment]
That doesn't seem to be an issue anymore, which is strange. The code has not changed, and the probability of VoiceOver having remedied that since I logged the issue looks low. It might depend on the browser used as well. I'll do some research.

**Comment by jeherve** [comment]
Could it be that the 2 versions of that list behave differently?

- https://github.com/Automattic/jetpack/blob/7028f5660e8584f47fc301fb4ac0586619718b76/projects/plugins/jetpack/_inc/client/main.jsx#L453-L454 at `wp-admin/admin.php?page=jetpack#/`
- https://github.com/Automattic/jetpack/blob/426aa5a9546a03a1b1aec7b929f9a4dff83a2d62/projects/packages/my-jetpack/_inc/components/connection-screen/index.jsx#L65-L66 at `wp-admin/admin.php?page=my-jetpack#/connection`

Makes you wonder why we have 2 versions at this point, this may be a possible improvement.

**Comment by monsieur-z** [comment]
> Could it be that the 2 versions of that list behave differently?

It happens with the VoiceOver/Safari combination, but not VoiceOver/Chrome.

> Makes you wonder why we have 2 versions at this point, this may be a possible improvement.

Yes. It's worth adding the content in the connection package and importing it from Jetpack and My Jetpack. I'll handle that separately.
