### ISSUE TITLE
Subscriptions: improve media+text block rendering in email

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#35503]
In the post:
![image](https://github.com/Automattic/jetpack/assets/87168/a457cf50-f88c-472d-bd17-38609552dca9)

In the email:

![image](https://github.com/Automattic/jetpack/assets/87168/d6fa481a-ea9b-4ddb-860d-edbb8005fffb)

Example post https://wordpress.org/news/2024/02/the-month-in-wordpress-january-2024/ (blog id 14607090, post id 16837)

**Comment by filipanoscampos** [comment]
📌 TRIAGE NOTES

Already reproduced and reported to the relevant team. Replicated https://github.com/Automattic/jetpack/issues/35530.
Marking as triaged and assigning priority.

**Comment by simison** [comment]
This could make sense to render as "columns" once we support those. Slack convo p1707251028245239-slack-C0316THTWTX

**Comment by jp-imagines** [comment]
User reported this in 7853205-zd-a8c as well. They're requesting a follow-up when this is fixed (7853574-zd-a8c).

**Comment by toncijajic** [comment]
@simison, quick check if we have an ETA for this fix in mind?

**Comment by simison** [comment]
This has been improved in D155585-code cc @toncijajic

**Comment by toncijajic** [comment]
Thanks @simison!
