### ISSUE TITLE
Jetpack Form Block: cannot undo to remove the block

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/jetpack#35505]
### Impacted plugin

Jetpack

### Quick summary

When the Jetpack Form Block is inserted shows the list of available forms, a user cannot undo that action, and they have to find a workaround to remove that block.

https://github.com/Automattic/jetpack/assets/1881481/2f7893ed-051f-47c0-842b-0b9570e8e550

A similar issue happens when the Donations Form block is inserted. See https://github.com/Automattic/jetpack/issues/25035

https://github.com/Automattic/jetpack/assets/1881481/7a455edd-ab25-4b6e-a119-3a1a54a81492

### Steps to reproduce

1. Create a new post or edit a template in the Site editor
2. Add the `Form` block
3. Click undo
4. Verify the block is not removed

### A clear and concise description of what you expected to happen.

The block should be removed as other blocks do, see how the Payments or the Video block do it.

https://github.com/Automattic/jetpack/assets/1881481/0c7e7a33-cba1-4347-baec-c7faf7183603

https://github.com/Automattic/jetpack/assets/1881481/e2db7d52-ce93-41d7-9cb9-e82038b38cf3

### What actually happened

The undo button doesn't remove the block.

Something interesting is that when a form is inserted, the undo reverts what seems to be internal actions, like making fields required.

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

No console errors.

**Comment by jeherve** [comment]
I seem to be able to undo forms, but not the Donations block on my end, on a site running WP 6.4 + Jetpack (no Gutenberg):


https://github.com/Automattic/jetpack/assets/426388/db8d340f-fcf4-42ff-82e9-b9956c6d8f70

Are you able to consistently reproduce the problem with the Form block?

**Comment by miksansegundo** [comment]
You are right, the issue with the Form block is only reproducible when Gutenberg 17.6.3 or 17.6.4 is enabled.

**Comment by coder-karen** [comment]
Closing this issue out as I've now created a new issue for the Donations block specifically, along with some debugging notes:  https://github.com/Automattic/jetpack/issues/37185
