### ISSUE TITLE
Memberships: Donation Button Not Updating with Custom Amount

### ISSUE THREAD

**Issue by Aurorum** [Automattic/jetpack#35500]
### Impacted plugin

Jetpack

### Quick summary

The Donation button is not updating when a custom amount is entered.

### Steps to reproduce

I tried testing this, but I don't have a Stripe account. From what it seems on the user's site, the issue is this:

1. Add a Donations form 
2. View that form on the front end
3. Select a contribution amount that's different to the initial amount
4. Note that the button's value doesn't change 

<img width="468" alt="Screenshot 2024-02-07 at 09 10 48" src="https://github.com/Automattic/jetpack/assets/43215253/d93dd142-4fbb-4d9c-bf0d-68f8bf5af7f3">

### A clear and concise description of what you expected to happen.

It should say "Donate $20.33" 

### What actually happened

It's stuck on "Donate $10" 

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Logs or notes

7703804-zen

**Comment by chrismccluskey** [comment]
Fix: D141855-code

**Comment by chrismccluskey** [comment]
Deployed D141855-code
