### ISSUE TITLE
Sharing Button Block: add "Web share" button

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#35533]
I think it would be nice to add a mobile "Web share" button that would open the native sharing dialog (and thus all the sharing options available on one's phone). We had attempted to build something similar for the legacy sharing buttons: #24473

Here is how the option looked like from that PR, on an Android phone and in the Firefox browser. The native sharing options can of course look different depending on your browser and OS:

https://github.com/Automattic/jetpack/assets/426388/f550e2f2-b0f2-4b90-b54d-5b62b595fe03

@keoshi What do you think about this? And if we added such an option (only visible on mobile devices on the frontend), how do you think it should look like in the site editor interface when adding the button?

**Comment by andrii-lysenko** [comment]
Mentioning [this article](https://set.studio/simplify-sharing-with-built-in-apis-and-progressive-enhancement/) shared by @monsieur-z
