### ISSUE TITLE
WooCommerce Analytics: Uncaught exception 'Error' with message 'Call to a member function get_id()

### ISSUE THREAD

**Issue by gedex** [Automattic/jetpack#35562]
### Impacted plugin

Jetpack

### Quick summary

The handler that tracks order confirmation page can throws an error because it's always assume order item is an instance of `WC_Order_Item_Product`. If the product is deleted, this triggers the error.

The issue is in https://github.com/Automattic/jetpack/blob/e49db6b9261d36fad4dc1f49a5e4af3806c92db5/projects/plugins/jetpack/modules/woocommerce-analytics/classes/class-jetpack-woocommerce-analytics-trait.php#L66-L71

`$this->get_product_details()` assume passed `$product` is always an instance of `WC_Product`, thus when `$item['data']` is a bool (i.e. the product is deleted) it triggers error

### Steps to reproduce

1. Create a product A
2. Make a purchase of product A until `/checkout/order-received/<order-id>/`—this fires `capture_order_confirmation_view` https://github.com/Automattic/jetpack/blob/e49db6b9261d36fad4dc1f49a5e4af3806c92db5/projects/plugins/jetpack/modules/woocommerce-analytics/classes/class-jetpack-woocommerce-analytics-checkout-flow.php#L35-L37
3. Delete product A
4. Visit again `/checkout/order-received/<order-id>/`
5. See the error

```
Uncaught exception 'Error' with message 'Call to a member function get_id() on bool'
```

### A clear and concise description of what you expected to happen.

It shouldn't throws an error.

### What actually happened

It throws an error

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

Stack trace:

```
 in Jetpack_WooCommerce_Analytics_Checkout_Flow::get_product_details called at /var/www/wp-content/mu-plugins/jetpack-13.0/modules/woocommerce-analytics/classes/class-jetpack-woocommerce-analytics-trait.php (71)
 in Jetpack_WooCommerce_Analytics_Checkout_Flow::format_items_to_json called at /var/www/wp-content/mu-plugins/jetpack-13.0/modules/woocommerce-analytics/classes/class-jetpack-woocommerce-analytics-checkout-flow.php (99)
 in Jetpack_WooCommerce_Analytics_Checkout_Flow::capture_order_confirmation_view called at /var/www/wp-includes/class-wp-hook.php (324)
 in WP_Hook::apply_filters called at /var/www/wp-includes/class-wp-hook.php (348)
 in WP_Hook::do_action called at /var/www/wp-includes/plugin.php (517)
 in do_action called at /var/www/wp-content/themes/woo/woocommerce/checkout/thankyou.php (35)
 in include called at /var/www/wp-content/plugins/woocommerce/includes/wc-core-functions.php (345)
 in wc_get_template called at /var/www/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php (333)
 in WC_Shortcode_Checkout::order_received called at /var/www/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php (63)
 in WC_Shortcode_Checkout::output called at /var/www/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php (72)
 in WC_Shortcodes::shortcode_wrapper called at /var/www/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php (95)
 in WC_Shortcodes::checkout called at /var/www/wp-includes/shortcodes.php (433)
 in do_shortcode_tag called at ? (?)
 in preg_replace_callback called at /var/www/wp-includes/shortcodes.php (273)
 in do_shortcode called at /var/www/wp-includes/class-wp-hook.php (324)
 in WP_Hook::apply_filters called at /var/www/wp-includes/plugin.php (205)
 in apply_filters called at /var/www/wp-includes/post-template.php (256)
 in the_content called at /var/www/wp-content/themes/woo/page-templates/template-fullwidth.php (47)
 in include called at /var/www/wp-includes/template-loader.php (106)
 in require_once called at /var/www/wp-blog-header.php (19)
 in require called at /var/www/index.php (17)
```

**Comment by jeherve** [comment]
@gedex Thank you for the report! If you still have your site set up, do you think you could test and see if #35566 is enough to solve the issue for you?

Thank you!
