### ISSUE TITLE
Map block: marker position inconsistent with the actual results from Google

### ISSUE THREAD

**Issue by Robertght** [Automattic/jetpack#35567]
### Impacted plugin

Jetpack

### Quick summary

I've found two cases this week where users reported the marker not showing up where Google Maps is.

### Steps to reproduce

1. Use this address as an example: 1128 Olive Avenue, Novato, CA 94945 or [this](https://www.google.com/maps/place/1128+Olive+Ave,+Novato,+CA+94945,+USA/@38.1127676,-122.5706872,16.88z/data=!4m15!1m8!3m7!1s0x8085bb64d6ffacb9:0x47a77c3a70fcbc11!2s1128+Olive+Ave,+Novato,+CA+94945,+USA!3b1!8m2!3d38.1124216!4d-122.5707021!16s%2Fg%2F11c4nc2vq2!3m5!1s0x8085bb64d6ffacb9:0x47a77c3a70fcbc11!8m2!3d38.1124216!4d-122.5707021!16s%2Fg%2F11c4nc2vq2?entry=ttu)
2. Insert this as a marker in the Map block inside a page or a post.
3. Compare the results

### A clear and concise description of what you expected to happen.

To display like [Google](https://www.google.com/maps/place/1128+Olive+Ave,+Novato,+CA+94945,+USA/@38.1127676,-122.5706872,16.88z/data=!4m15!1m8!3m7!1s0x8085bb64d6ffacb9:0x47a77c3a70fcbc11!2s1128+Olive+Ave,+Novato,+CA+94945,+USA!3b1!8m2!3d38.1124216!4d-122.5707021!16s%2Fg%2F11c4nc2vq2!3m5!1s0x8085bb64d6ffacb9:0x47a77c3a70fcbc11!8m2!3d38.1124216!4d-122.5707021!16s%2Fg%2F11c4nc2vq2?entry=ttu).

### What actually happened

It displayed like this:

![eYOl52.png](https://github.com/Automattic/jetpack/assets/6737345/cb8d97e7-e700-4e57-8bc8-50bada292de7)

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Happens on both environments, Simple and Atomic. 

The only workaround I could think of is by using a adjacent address although that could throw off users.

Ticket: 7699816-zd-a8c

**Comment by jeherve** [comment]
That is to be expected, since the map block does not display a Google map. In your case, it's an Apple map so geolocation is handled by Apple. At times, there may be discrepancies.

**Comment by Robertght** [comment]
Thanks @jeherve ! TIL on that. I think we need to make this clear in our documentation. I'll ping the docs folks.
