### ISSUE TITLE
W3C Feed Validator reports "Use of unknown namespace: com-wordpress:feed-additions:1"

### ISSUE THREAD

**Issue by abid76** [Automattic/jetpack#35589]
### Impacted plugin

Jetpack

### Quick summary

After activating Jetpack (and activated site accelerator options) I noticed a change in the rss feed. There are some `post-id` elements included.
```
<post-id xmlns="com-wordpress:feed-additions:1">27392</post-id>
```
This leads to a warning in the W3C feed validator.
> Use of unknown namespace: com-wordpress:feed-additions:1

I'm not sure if this is something to worry about. Only thing which is important for us that this **should not result in any issues regarding our ranking in Google News**.

This seems to be related to https://github.com/Automattic/jetpack/issues/996

### Steps to reproduce

Open W3C feed validator: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fapollo-news.net%2Ffeed%2Fgn

The warning should be reported there.

### Impact

One

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by jeherve** [comment]
It is indeed related to the issue you found. As you saw there, the implementation respects the XML specifications and should not have any impact on your Google News rankings. No worries there, you can safely ignore this.
