### ISSUE TITLE
My Jetpack: display Jetpack plugin status in Extras card

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#35595]
My Jetpack used to include an "Extras" card that was removed in #30988, and that displayed the extra features you could get when installing the Jetpack plugin. It would be nice to bring it back, so folks who miss the Jetpack plugin can install it back.

Related discussion: p1707692575049899-slack-C0299DMPG

Also see #30728, where we discussed the removal of the "Extras" card.

**Comment by jboland88** [comment]
@jeherve might this become moot with some of this discussion: p1HpG7-r96-p2?

**Comment by jeherve** [comment]
Yes, I think it may need to change once we start making progress on that project.
