### ISSUE TITLE
My Jetpack: Popover CTA does not look correct

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#35594]
The CTAs appearing when clicking on the small popover for My Jetpack cards uses a button design that doesn't fit in the popover:

<img width="378" alt="Screenshot 2024-02-12 at 09 35 46" src="https://github.com/Automattic/jetpack/assets/426388/a0e2dbb4-9ecb-4419-adac-4276a245f37f">

Reported here:
p1707692575049899-slack-C0299DMPG

**Comment by jboland88** [comment]
We are moving towards removing that three-dot menu all together since plugins are automatically installed if needed when you choose to start using one of the products (either choosing a plan or starting for free).

We'll keep this issue around until that gets resolved.

**Comment by jboland88** [comment]
These CTAs have been removed in https://github.com/Automattic/jetpack/pull/35829.
Closing this one.
