### ISSUE TITLE
Stats/Search: wpcom/v2 API returning 403 for private Atomic sites

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#35615]
![image](https://github.com/Automattic/jetpack/assets/1425433/3ffb5020-525f-4dc9-a9d1-dc2a56897583)

Asked here: p1707773826922599-slack-CBG1CP4EN

The specific API shown here is https://xx.xx.com/wp-json/jetpack/v4/search/plan?_cacheBuster=1707778652538 which is forwarded to https://public-api.wordpress.com/wpcom/v2/sites/$site/jetpack-search/plan

I found out that the error is thrown at fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Spragenyvmrq%2Spragenyvmr.cuc%3Se%3Q34q631o3%23693-og, because the token is empty fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Serfg%2Qncv%2Qcyhtvaf%2Spragenyvmrq%2Spragenyvmr.cuc%3Se%3Q34q631o3%23726-og.

**Comment by kangzj** [comment]
Hi @fgiannar, please let me know if you need more information. Thanks 👍

**Comment by fgiannar** [comment]
Fixed via D139268-code
