### ISSUE TITLE
Custom CSS: SVG Filters stripped out when saving

### ISSUE THREAD

**Issue by fabiangigler** [Automattic/jetpack#3561]
#### What I expected

Jetpack to return the same string entered in the custom css input:

```
.class-name {
filter: url("data:image/svg+xml;utf8,<svg xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'grayscale\'><feColorMatrix type=\'matrix\' values=\'0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0\'/></filter></svg>#grayscale");
}
```
#### What happened instead

get css output like this (broken):

```
.class-name {
filter: url("data:image/svg+xml;utf8,#grayscale");
}
```
#### Steps to reproduce the issue

see above

I understand that it might be important to strip html code from the css input, however in this situation it breaks standard expected behaviour.

**Comment by annezazuu** [comment]
In the meantime, a user in 2746878 suggested we add some sort of notification/error message when we sanitize the CSS. I think this would be a great feature to add in to at least save folks time.

**Comment by oskosk** [comment]
As Jetpack is currently adding to core's custom css functionality, looks like it's not possible anymore to add markup. 

![image](https://user-images.githubusercontent.com/746152/36222853-5af12aec-11a1-11e8-8b33-aaf24b0ba681.png)


closing for now. Please reopen it it's necessary
