### ISSUE TITLE
[Boost] Update Page Cache error notice to match designs

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#35626]
There are several things we need to do:
- Update the notice visually, to match designs - p1HpG7-r9A-p2;
- Incorporate the retry button in a way that makes sense. The one https://github.com/Automattic/jetpack/pull/35568 added is just for debugging purposes;
- Make sure all errors we're showing make sense. https://github.com/Automattic/jetpack/pull/35568 added error codes, but there are no proper messages for them.

Here's an example:

![Image](https://github.com/Automattic/jetpack/assets/11799079/5599782f-e15c-44e7-a9ad-b34c39af68fa)

**Comment by thingalon** [comment]
For integrating the button, I recomend making it a clickable link in the text of the error message. 

e.g.: 

> This feature cannot be enabled because <ins>wp-content/advanced-cache.php</ins> was found on your site. It was created by another plugin, or your hosting provider. Please remove it to use this module.
> 
> <ins>Learn more</ins> <ins>Try again</ins>

@ederrengifo  in case you have other ideas :)

**Comment by dilirity** [comment]
@ederrengifo, @thingalon I've updated https://github.com/Automattic/jetpack/pull/35678 to include a list of the error messages we show in the notice.
