### ISSUE TITLE
Newsletter: WordPress logo barely visible in dark mode Gmail app on iOS

### ISSUE THREAD

**Issue by pkuliga** [Automattic/jetpack#35623]
### To reproduce

1. Have the Gmail app installed and dark mode enabled on iOS (I reproduced it on iPhone 12)
2. Subscribe to a blog
3. Receive a newsletter email with the new post
4. Notice the WordPress logo in the email footer is barely visible and there are huge margins above and below the footer content

![Image](https://github.com/Automattic/jetpack/assets/4068554/af7d7024-1f49-4852-ba98-83c2eb7fe6cd)

### Expected result

1. The WP logo is visible in dark mode
2. The amount of space above and below the footer content is lowered (keep the same amount of space as we have on the right/left side?)

**Comment by pkuliga** [comment]
This is how the WP logo looks in emails I receive from wordpress.com:

<img width="572" alt="Screenshot 2024-02-13 at 13 06 43" src="https://github.com/Automattic/jetpack/assets/4068554/8e526dcf-b5db-4df9-97a1-aa67e7db825d">

**Comment by simison** [comment]
Maybe there's a way to show different image on dark mode with CSS?

**Comment by simison** [comment]
Tho if I would have to guess, email client support isn't great:

- https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme
- https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by pkuliga** [comment]
Fixed by D139631-code
