### ISSUE TITLE
Markdown: Generate heading IDs

### ISSUE THREAD

**Issue by carlalexander** [Automattic/jetpack#3562]
#### What I expected

I expected the markdown module to create HTML IDs for post headings.
#### What happened instead

All headings don't have an ID when you view the post.
#### Steps to reproduce the issue
1. Create a post with a heading
2. Publish post
3. Inspect heading with developer tools
#### Discussion

I noticed this recently. When writing in markdown, the jetpack doesn't generate HTML IDs for the headings. This isn't the same behaviour as the standard WordPress editor. It makes impossible to create internal links inside your posts without manually creating the heading in the WYSIWIG.

**Comment by jeherve** [comment]
I don't believe this is part of the general Markdown standard:
https://daringfireball.net/projects/markdown/dingus

It is not implemented in the 2 Markdown parsing libraries we use in Jetpack either:
- [Markdown Extra](https://michelf.ca/projects/php-markdown/dingus/)
- Github Flavored Markdown

That said, I can see how useful this could be. it would become very easy to create anchors without having to write HTML. If you're interested in that feature, we would welcome a patch!

**Comment by carlalexander** [comment]
Yup, I think it would be useful! Let me see what I can cook up :)

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by crmckenzie** [comment]
I think this would be useful too. I use it to create some jump-links at the top of my blog post so that people can navigate to the matching header. I'm having to revert to traditional HTML. Ewwww. :)

**Comment by aybassiouny** [comment]
+1

**Comment by phillipjohnston** [comment]
The underlying library *does* support generation of ids, but this does not work in the block:

https://michelf.ca/projects/php-markdown/extra/

**Comment by phillipjohnston** [comment]
Is there a reason this is still "inactive"? Given that the underlying library supports this feature.

**Comment by jeherve** [comment]
PHP Markdown Extra is used in the legacy Markdown feature available in the classic editor, but Jetpack uses a different library for the block, `markdown-it`. At first glance, that library does not seem to support heading IDs.

**Comment by blakewatson** [comment]
> PHP Markdown Extra is used in the legacy Markdown feature available in the classic editor, but Jetpack uses a different library for the block, `markdown-it`. At first glance, that library does not seem to support heading IDs.

Just to make it super obvious for anyone looking (like me) if you _are_ using Markdown in the classic editor then you can use PHP Markdown Extra's [special attributes](https://michelf.ca/projects/php-markdown/extra/#header-id) feature to generate heading IDs.
