### ISSUE TITLE
My Jetpack: Backup, Protect, and VideoPress status not correct when using a Jetpack bundle plan

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#35639]
### Steps to reproduce

1. Start with a fresh new site
2. Connect it to WordPress.com and purchase a Complete plan during the connection process.
3. Back in wp-admin, go to the "My Jetpack" page

I would expect the Backup, Protect, and VideoPress cards to indicate that I have an active purchase. Instead it is marked as "inactive", invites me to "learn more" and purchase a standalone plan that I will not have to / be able to buy.

<img width="1163" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/39b54a85-912f-43e7-97b1-df80595543af">

I would expect the card to be more like the Akismet card.

**Comment by bobmatyas** [comment]
I've had two instances of customers confused by this today.

7750555-zen

**Comment by bobmatyas** [comment]
7706547-zen

**Comment by bobmatyas** [comment]
7780498-zen

**Comment by robertsreberski** [comment]
It is fixed by the same PR @elliottprogrammer merged: https://github.com/Automattic/jetpack/pull/39816
