### ISSUE TITLE
[Boost] Make sure site uses non-plain permalinks to use cache

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#35638]
To use the caching system, the website needs to use a permalink structure other than "Plain" which is the default on a new site. 

**Mark edits to add:**
This ticket just involves updating the setup steps to ensure that we check the site's permalink structure during the plugins' setup step (where we alos check if wp-content is writable), and display an appropriate error message if not, in the same style as the other setup error messages.

Should probably be tackled after https://github.com/Automattic/jetpack/issues/35626 is done.

**Comment by thingalon** [comment]
Is it the default? New site from a freshly downloaded WordPress:
![Image](https://github.com/Automattic/jetpack/assets/1369626/cdeafdb4-4f32-4d51-af33-90a76b0b4c68)

**Comment by donnchawp** [comment]
Interesting. When I reinstalled the Jetpack docker it was set to plain. I'll have another look.

**Comment by donnchawp** [comment]
Thanks for pointing that out. I just replicated that. Nice. I guess this can be put on the "do it when we have time to" pile.

There are older WP sites out there with plain permalinks, and probably new ones that downgrade to plain, so it would be worth checking for those outliers.
