### ISSUE TITLE
[Boost] When toggling the module off, don't remove WP_CACHE and advanced-cache.php

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#35644]
On a multisite all the sites share the same directories, so this would disable caching completely for all sites.

If caching is toggled by changing a setting in config.php then that will affect all sites too, but we could index the settings by blog_id.. Easiest time to do it is before release.

**Comment by thingalon** [comment]
Closing this in light of this discussion - pc9hqz-2Ac-p2

@donnchawp please let me know if it still needs discussing.
