### ISSUE TITLE
[Boost] Add an admin notice to clear cache when "site changes" are detected

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#35640]
If we notice that the site admin has modified settings that are displayed site-wide such as the description or blog title then we should display an admin notice that links to the Boost settings page where they can clear the cache.

A site owner may be experimenting with names, or whatever, and may not want their cached pages deleted all the time.

**Comment by thingalon** [comment]
🤔 I'm not sure I agree. Deleting their cache isn't terribly high cost. If we're going to detect changes like site title, I think we should just delete the cache on change for simplicity.

**Comment by thingalon** [comment]
Moving this to inbox pending further discussion.

**Comment by haqadn** [comment]
Since we are invalidating cache based on when we think it's needed and the fact that there are so many things in the inbox. I am closing this now. Feel free to open it again and discuss if you feel this is important.
