### ISSUE TITLE
Comments: Submitting form from safari results in a non-secure form warning

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/jetpack#3565]
#### What I expected

I expected when using Safari to submit a comment it would be submitted with no warnings
#### What happened instead

When submitting a pop up warning was displayed

> This is a non-secure form.
> This form will be sent in a way that is not secure. Are you sure you want to send it?

<img width="873" alt="non-secure" src="https://cloud.githubusercontent.com/assets/1326294/13879861/6ea7d8c6-ecf8-11e5-9785-81fc356a2980.png">
#### Steps to reproduce the issue
- Go to a site using Jetpack comments in Safari.
- I'm using Mac OS 10.11.3
- Safari version 9.0.3
- Tried on two separate sites both non SSL

**Comment by jeherve** [comment]
The problem seems to be limited to HTTP sites.

Possibly related to #3521

**Comment by dotnet-onestop** [comment]
Is there any way to vote for this to be prioritised? It keeps getting bumped back to later milestones.

**Comment by jeherve** [comment]
@dotnet-onestop We'll see about addressing this in the next major Jetpack release!

**Comment by ntpixels** [comment]
noted in #3001809-t

**Comment by jeherve** [comment]
Fixed in #7205
