### ISSUE TITLE
[Boost] Don't cache jb_static and favicon

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#35669]
We seem to currently cache `favicon.ico` and `/jb_static` which is part of the JS and CSS minify features and is already stored as static files. These should not be cached using boost-cache.

Related: #35057

**Comment by donnchawp** [comment]
Was the favicon you saw a redirect to the default WordPress one at wp-includes/images/w-logo-blue-white-bg.png ? I thought we had fixed that, by not caching 0 byte buffers.

We'll need to define "DONOTCACHEPAGE" for the jb_static files to stop those caching.

**Comment by haqadn** [comment]
I am not sure, it was request to the `/favicon.ico`. I think the content was 0 bytes. So, looks like it was fixed as I don't see it anymore.

**Comment by thingalon** [comment]
https://github.com/Automattic/jetpack/pull/35745 should fix the remaining issue; caching _jb_static links.
