### ISSUE TITLE
Subscriptions: "Read More" link in Newsletter's email lead to blank page

### ISSUE THREAD

**Issue by StefMattana** [Automattic/jetpack#35679]
### Impacted plugin

Jetpack

### Quick summary

We have a number of users (mostly all free users) who have reported an issue happening on the “Read More” link of the email newsletter feature. 

Upon clicking on the "Read More" button, the link doesn’t work and actually sends people to a blank page.

### Steps to reproduce

Ticket reference: 7736164-zen. Tested on different browsers (Chrome, FF, Safari, and Brave) with and without browser extensions. Also tested on incognito windows. 

- Upon opening an email sent by the Newsletter feature, you get the "Read More" button
- Click on the read more button.
- The link leads you to a blank page: 
<img width="1973" alt="Screenshot 2024-02-14 at 13 26 18" src="https://github.com/Automattic/jetpack/assets/11662998/fba103c1-49f4-441d-8dd4-741262939660">
There are no errors for this link/example; we previously found some 403 forbidden errors likely related to ads and ad blocks.

### A clear and concise description of what you expected to happen.

The issue started to be reported about three weeks ago, when [also this GH issue was created](https://github.com/Automattic/wp-calypso/issues/86037). 
Pinging @Automattic/apex ^^

The problem appears to be temporary, as many reported links eventually worked okay, and the following emails sent had worked "Read More" links. 

@bobmatyas and I tried to replicate the problem on our test sites with no success. 

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by samiff** [comment]
Possibly another report: https://wordpress.org/support/topic/newsletter-52/

**Comment by ivan-ottinger** [comment]
Investigation details: p1707926077740849/1707917929.392189-slack-C02TCEHP3HAl

Looks like the issue is caused by third-party speed optimization plugins that lazy load iframe responsible for the redirect.

- for the 7736164-zen, the plugin is likely FlyingPress
- for https://wordpress.org/support/topic/newsletter-52/, the plugin is likely Ezoic

If possible, users could try to adjust the plugin settings to avoid lazy loading of the iframe with `id="user-content-link-redirection"` or disable it for the page that includes the `?action=user_content_redirect` URL parameter.

We can also take a look whether there is something we can do about the issue from our side.

**Comment by StefMattana** [comment]
Thanks @ivan-ottinger! @bobmatyas that's how you guess 👏 
I will ask the user on 7736164-zen if they can deactivate that (also via host); I will update you on the results  🤞 
Also followed up with the user on thread: https://wordpress.org/support/topic/newsletter-52/

**Comment by StefMattana** [comment]
@ivan-ottinger you genius! the user in the ticket added the `action=user_content_redirect ` URL parameter to disable cache for that specific path and the link works now. ⭐ 🚀

**Comment by ivan-ottinger** [comment]
Thank you, @StefMattana! 🙂 I am happy it worked for the user. 😌

**Comment by StefMattana** [comment]
I shared this solution with the users who reported the issue in the following threads: 
- https://wordpress.org/support/topic/jetpack-subscribers-email-read-more-of-this-post-link-issue/
- https://wordpress.org/support/topic/link-read-more-in-the-subscription-mail-break-the-database-access/
