### ISSUE TITLE
Verbum Comments: Comment lost when submitted on a password-protected page or post in Chrome

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/jetpack#35716]
### Impacted plugin

Jetpack

### Quick summary

Under some circumstances, submitting comments does not work.

### Steps to reproduce

In Chrome:

1.  On a WordPress.com Atomic site, activate a classic theme like Twenty Twenty-One
2. Create a password-protected page or post with comments open and unmoderated
3. Submit a comment

### A clear and concise description of what you expected to happen.

Expected to see the comment appear on the page or post

### What actually happened

Comment disappears
<img width="1004" alt="Test_Post_–_Jupiter_Woo_Testing" src="https://github.com/Automattic/jetpack/assets/7662449/7da8fe80-0c1b-4bca-9dd8-fef25b61e600">

Screencast: 

https://github.com/Automattic/jetpack/assets/7662449/7b87a880-a948-41de-b1b1-6abbe3bb51c1

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

### Logs or notes

The bug occurs in Chrome 121.0.6167.184
Works OK in Firefox 122.0.1
Have not tested other browsers

Was **not** able to replicate in a block theme or a Simple site.

User follow-up ticket in: 7746553-zd-a8c

**Comment by bobmatyas** [comment]
I tested this and was able to confirm the behavior on a self-hosted Jetpack as well. After posting a comment, I get a blank iframe:

![Screenshot on 2024-02-15 at 05-55-10](https://github.com/Automattic/jetpack/assets/45246438/54657dcf-b077-4627-a7b7-e430de7ecdc5)

When I reload the page, the comment doesn't appear nor is it in the comments dashboard.

**Comment by heavyweight** [comment]
On atomic sites comments are posted via iframe.
The iframe points to `https://jetpack.wordpress.com/jetpack-comment...`
When the comment is submitted there is an inline js that submits the form near the bottom of the file `class.jetpack-renderer.php`.
This js form submission happens from `https://jetpack.wordpress.com/jetpack-comment/` and posts to the comment post endpoint of the atomic site. If the cookie `wp-postpass_...` is missing from this then we get `comment_on_password_protected` error.
We need to either set this cookie for the https://jetpack.wordpress.com/ domain or set it to SameSite=None when it is set for the atomic site.

**Comment by ccwalburn** [comment]
Hi @heavyweight 

I have a reply that this is still not working for the user who originally reported the issue:
7746553-zd-a8c

**Comment by heavyweight** [comment]
Hi.
The fix is part of v13.2 and should be picked up and deployed tomorrow.
Will keep an eye on things.
Sorry for the confusion.
