### ISSUE TITLE
[Boost] Remember to invalidate cache when other modules are changing output

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#35748]
Some Boost modules can change the HTML output. Boost cache should play nicely with Boost's own modules. 

Examples:
- Critical CSS
- Minify JS/CSS
- Image CDN
- Deferred JS

**Comment by haqadn** [comment]
cc @thingalon for input

**Comment by thingalon** [comment]
👍 Yes, this is something we'll ned to take care of. Basically any time a setting changes that may affect the front of the site we'll have to flush the cache.
