### ISSUE TITLE
Subscriptions: Allow More Control over Timing of Newsletter Popup 

### ISSUE THREAD

**Issue by Aurorum** [Automattic/jetpack#35743]
### Impacted plugin

Jetpack

### What

The user would like more control over when the subscription pop-up appears. 

### How

> Can I change the default time before the Newsletter subscription pop-up appears? Can I make it a longer delay?

<img width="560" alt="Screenshot 2024-02-18 at 10 41 03" src="https://github.com/Automattic/jetpack/assets/43215253/09fbb9ac-d6f6-499f-aee1-e2c24af3027f">

Might be nice to add a setting which makes this possible.

7756649-zen

**Comment by simison** [comment]
Open to contributions on this one. :-)

There would be a filter, which adds a global variable when the JS gets enqued:

https://github.com/Automattic/jetpack/blob/bcae064ed6f3bdc8dccb7cc4fa3704d1e564a34c/projects/plugins/jetpack/modules/subscriptions/subscribe-modal/class-jetpack-subscribe-modal.php#L64

And then gets used in the JS:

https://github.com/Automattic/jetpack/blob/bcae064ed6f3bdc8dccb7cc4fa3704d1e564a34c/projects/plugins/jetpack/modules/subscriptions/subscribe-modal/subscribe-modal.js#L20-L24

...with fallback being the current 300ms.

**Comment by Danrancan** [comment]
I'm trying to make my newsletter signup popup from jetpack be delayed as well. How can I do this in the jetpack plugin?
