### ISSUE TITLE
[Boost] Wrap-up Cache UI

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#35768]
* [x] https://github.com/Automattic/jetpack/issues/35783
* [x] https://github.com/Automattic/jetpack/pull/35984;
* [x] Update exclude description to include example tooltip and link for "learn more" (https://github.com/Automattic/jetpack/pull/35903).
* [x] Add toast notification when saving excludes (https://github.com/Automattic/jetpack/pull/35808);
* [x] https://github.com/Automattic/jetpack/pull/35899;
* [x] Make sure styles match designs.

**Comment by pyronaur** [comment]
Added toasts in https://github.com/Automattic/jetpack/pull/35808

**Comment by thingalon** [comment]
is it worth adding subtle horizontal lines to the multiline text entry to make it clear that each line is a separate entry?

We should detect what look like complete URLs with domains, and make it clear to users that they should be path only. 

See: pedxs5-oQ-p2#comment-291

**Comment by dilirity** [comment]
@thingalon what are the conditions under which we show an error for the Exceptions field if the user entered an invalid pattern?

~I'm looking to add that to https://github.com/Automattic/jetpack/pull/35903 and wanted to have a clear picture.~

From what I recall, we only accept:
- valid regexes;
- partial URLs.

For the regexes - do we accept full regexes like `/file\/example\.html/gm` (note the wrapping `/`, flags and the escaped `/` and `.`? Or should we omit the wrappers and flags?

### WP Rocket

They seem to support the wildcard (though always wrapped in brackets - `(.*)`.

![CleanShot 2024-02-23 at 14 11 07](https://github.com/Automattic/jetpack/assets/11799079/1954c247-20fc-480d-bb51-7b8828de0844)

If an item doesn't start with a slash, it's removed.
For example:
- `path/` -> `/`
- `/path` -> `/path/`
- `/path/.*` -> `/path/(.*)`

### LiteSpeed

Somewhat supports regular expressions https://docs.litespeedtech.com/lscache/lscwp/cache/#do-not-cache-uris

I like their docs giving a list of URLs and then an example to say what it would match.

### TotalCache

Has its own dictionary - https://github.com/BoldGrid/w3-total-cache/wiki/FAQ:-Usage#which-textareas-for-file-entries-support-regular-expressions

**Comment by thingalon** [comment]
We should definitely show an error if:
- The user enters an invalid Regular Expression. e.g.: a mismatched bracket.
- It looks like there's a domain on the front of the path (unless we can auto-strip those on save)

I like the idea of requiring a slash on the front too. I think that helps to make it clearer that it's a path not a full URL.

> For the regexes - do we accept full regexes like /file\/example\.html/gm (note the wrapping /, flags and the escaped / and .? Or should we omit the wrappers and flags?

I think we should omit the wrappers and flags. `/` is going to be a very common component of URL exclusions, so we shouldn't confuse the matter by including them. :) 

I was tempted to suggest that we make users mark Regular Expressions by surrounding the line with `@` - like `@/foo/.*/bar@` and treat other lines like exact matchers, but I think that would be even more confusing to users. 

99% of users will never go beyond having `(.*)` as their wildcard.

**Comment by dilirity** [comment]
Closing this, as everything from the checklist was completed - yay!
