### ISSUE TITLE
[Boost] Logger should log to one file and rotate old log files

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#35779]
The Logger in the Cache module logs to a file with today's day of the month in it, and log files older than 24 hours will be deleted.

I would like to make some changes to that:
* Log to a single file.
* Instead of deleting, rotate the logs and keep 3 days worth of files. Or make deleting a manual process for the user.

**Comment by thingalon** [comment]
One question: What's the advantage of logging to a single file instead of one based on today's date?

**Comment by donnchawp** [comment]
The main reason is that the site owner might need offline access to the logs, just in case there's a problem with WordPress. Logging to one filename makes it predictable, so it can be easily scripted, or even make it simple to run `tail -f` on it from the terminal, just by tapping up-arrow to get at a previous entry in the shell history.

The WPSC log is logged to a file with an md5 string as a filename, but the viewer doesn't need WordPress to load.

Besides, it's convention that logs are rotated daily, and usually 7 days logs are kept, with older ones gzipped. I wouldn't bother gzipping ours.

**Comment by haqadn** [comment]
Hey @donnchawp! Seems like this is low priority. In the spirit of what I said earlier, I am closing this issue. If you think this is important, feel free to reopen and discuss.
