### ISSUE TITLE
[Boost] make sure Cache module is active before saving cache

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#35771]
On a multisite install of WordPress, if Boost Cache is enabled on one site, it will start caching for all sites. Unfortunately, there will be no way for the other sites to delete the cache unless they activate Boost as well.

The plugin should check that the Cache module is enabled, or at the very least, that Boost is activated, before saving the new cache file for a page.

That will stop pages being cached on websites where Boost isn't activated.

**Comment by thingalon** [comment]
This seems like it would go along nicely with keeping WP_CACHE defined until plugin uninstallation. I just realized that our discussion in yesterday's team meeting landed us right back at the behaviour you recommended in the first place.

:)
