### ISSUE TITLE
[Boost] Unify Cache namespaces

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#35782]
Currently we have two namespaces under the page cache feature code:

```php
use Automattic\Jetpack_Boost\Modules\Cache\Pre_WordPress\Filesystem_Utils;
use Automattic\Jetpack_Boost\Modules\Page_Cache\Pre_WordPress\Boost_Cache_Utils;
use Automattic\Jetpack_Boost\Modules\Page_Cache\Pre_WordPress\Logger;
```

With the introduction of `Pre_WordPress`, we could just replace `Cache` with `Page_Cache`.

Adding to a ticket, as I don't wanna mess up existing PRs. We should do this at the end.

**Comment by haqadn** [comment]
The cache module should also be moved to optimizations directory.
