### ISSUE TITLE
[Boost] Add Cache Actions to clear cache

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#35784]
The Boost_Cache::delete_cache() function deletes the entire cache of files. We should provide a simple to use action that a site owner can fire to do this, rather than forcing them to know how it's implemented. Same for other cache clearing functionality. I'm going to make the action names fairly generic with an eye to using them in WP Super Cache too, and maybe it might encourage other page cache plugins to use it too.

```
do_action( 'clear_page_cache_all' ); // delete entire cache
do_action( 'clear_page_cache_url', $url ); // delete cache for URL, including paged archive pages
do_action( 'clear_page_cache_post', $post_id ); // delete cache for a post, including comment archives.
do_action( 'clear_page_cache_home' ); // delete cache files for homepage and paged archives.
```

The nice thing about exposing the functionality like this, is that it doesn't cause a fatal error if Boost isn't installed, so it can be easily used by other plugin authors.

These actions should be configured as early as possible in Boost_Cache, so other code can call them on "init".

**Comment by thingalon** [comment]
This is functionality that can be done post-release. However, it's a very small task so I will leave it in the TODO list. :)
