### ISSUE TITLE
Notice: Use of undefined constant JETPACK__WPCOM_JSON_API_HOST

### ISSUE THREAD

**Issue by bobbingwide** [Automattic/jetpack#3579]
#### What I expected
Not to see any Notice:s

#### What happened instead
Notice: Use of undefined constant JETPACK__WPCOM_JSON_API_HOST - assumed 'JETPACK__WPCOM_JSON_API_HOST' in /home/oikplugi/public_html/wp-content/plugins/jetpack/class.jetpack-signature.php on line 11

#### Steps to reproduce the issue
Install update 3.9.4 with WP_DEBUG true.

**Comment by kraftbj** [comment]
Added via https://github.com/Automattic/jetpack/commit/174ba0799f5134e26c61d2e20c322ad9ebccdb2a

The constant is defined in `jetpack.php` https://github.com/Automattic/jetpack/blob/f30b9cad7a74cf2db46082c4aed4cac4575b32be/jetpack.php#L28 , which I'd expect to have been loaded before `class.jetpack-signature.php`

@bobbingwide Can you confirm that `JETPACK__WPCOM_JSON_API_HOST` is defined in your jetpack/jetpack.php file?

cc: @enejb

**Comment by bobbingwide** [comment]
Hi, the constant is defined in 3.9.4 but not in 3.9.1.
The problem occurred during shutdown processing, after the plugin was updated. 
The jetpack.php file that was loaded was v3.9.1
The version of class.jetpack-signature.php was v3.9.4

Here's a backtrace.
```
0. bw_lazy_backtrace /home/oikcouk/public_html/wp-content/plugins/oik-lib/libs/bwtrace.php:72 0
1. bw_backtrace /home/oikcouk/public_html/wp-content/plugins/oik-bwtrace/includes/bwtrace-actions.php:224 0
2. bw_trace_error_handler(8,Use of undefined constant JETPACK__WPCOM_JSON_API_HOST - assumed 'JETPACK__WPCOM_JSON_API_HOST',/home/oikcouk/public_html/wp-content/plugins/jetpack/class.jetpack-signature.php,112,array) /home/oikcouk/public_html/wp-content/plugins/jetpack/class.jetpack-signature.php:112 5
3. sign_request(gi4VmE&ae3R)M)l#f6k@gsi0cSfDLskw:1:1,1458808908,69iu07MuQa,jLGjv+ScJ4u8cayXkP6RG/N+1x4=,POST,https://jetpack.wordpress.com/xmlrpc.php?for=jetpack&wpcom_blog_id=41155174,<?xml version="1.0"?>
```
a ton of XML data removed
```
4. remote_request(array,<?xml version="1.0"?>
 /home/oikcouk/public_html/wp-content/plugins/jetpack/class.jetpack-ixr-client.php:34 2
5. query(system.multicall,array) /home/oikcouk/public_html/wp-content/plugins/jetpack/class.jetpack-ixr-client.php:118 2
6. query /home/oikcouk/public_html/wp-content/plugins/jetpack/class.jetpack.php:5511 0
7. xmlrpc_async_call() /home/oikcouk/public_html/wp-content/plugins/jetpack/class.jetpack.php:0 1
8. call_user_func_array(array,array) /home/oikcouk/public_html/wp-includes/plugin.php:503 2
9. do_action(shutdown) /home/oikcouk/public_html/wp-includes/load.php:611 1
10. shutdown_action_hook /home/oikcouk/public_html/wp-includes/load.php:0 0
```

BTW: I then get another error gzinflate: data error.

class-jetpack.signature.php is loaded after class-jetpack-ixr.client.php, 
so it would be the 3.9.4 version, referring to the constant that was not defined in 3.9.1

I can send/attach a full trace file if needed.

**Comment by enejb** [comment]
Thanks @bobbingwide for digging deeper into this. https://github.com/Automattic/jetpack/pull/3584 should fix it.
