### ISSUE TITLE
Widget visibility: Unable to specify post types author visibility should apply to

### ISSUE THREAD

**Issue by sketchbuch** [Automattic/jetpack#3581]
It would be good if there was more control over what post types the author visibility applies to. A list of checkboxes would be good. Currently I have the gravatar widget showing if the author matches a certain user, I thought this would just apply to posts but it also applies to pages.

At the very least, if you don't want to support custom post types, you should be able to specify if posts, pages, or both should show the gravatar profile.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
