### ISSUE TITLE
[Boost] Invalidate matched cache files after updating Exceptions

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#35872]
Currently, updating the Exceptions field doesn't delete cached pages that match the patterns.

pedxs5-oQ-p2#comment-288

**Comment by thingalon** [comment]
Alternately we could check whether the current URL is cacheable before serving cached content and let the garbage collector deal with it.

**Comment by dilirity** [comment]
It turns out, we do check the exclusion list before serving cache. Garbage collection also will take care of old cached pages.

I assumed that this doesn't work, but it appears it was caused by using a full URL.

We'll be stripping the hostname, so things should work as expected.
