### ISSUE TITLE
Form block: 50% field width (two columns) doesn't grow on mobile 320px screens

### ISSUE THREAD

**Issue by seanconklin** [Automattic/jetpack#35881]
### Impacted plugin

Jetpack

### Quick summary

Hello,

Using any Block Theme and the latest Jetpack plugin v13.1.3 I reproduce a problem on 320px mobile screens where the 50% contact form block fields do not expand to screen size after they break the row. I'll attach screenshots of 320px and 375px as tested using Google Chrome Web Tools.

### Steps to reproduce

1. Setup a sandbox using any Block Theme.
2. Install Jetpack main plugin.
3. Enable the Contact Form block (maybe visit Modules page to do this).
4. Setup a contact form on any page with two 50% fields, e.g. Name and Email.
5. Using Chrome browser and F12 developer tools, enter responsive mode and switch to 320px (smallest) screen width.

### A clear and concise description of what you expected to happen.

I expect the fields to expand to full width since 50% of 320px (plus margins) is too small to see what you're typing. At 375px screen size they are also rather small to maintain their 50%, but at least it looks better at this size.

### What actually happened

Fields show at 50% width on smaller mobile screens, which is too small to see what you're typing.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

![Screenshot 2024-02-20 at 5 04 37 PM](https://github.com/Automattic/jetpack/assets/19829621/160a12e9-6a96-424b-924f-aefbb578106b)
![Screenshot 2024-02-22 at 10 56 25 AM](https://github.com/Automattic/jetpack/assets/19829621/1e167a7e-22b3-48e0-85d9-e1dfb0b67edb)
![Screenshot 2024-02-22 at 10 56 38 AM](https://github.com/Automattic/jetpack/assets/19829621/51d26f22-f549-4bc6-a823-5490fff67763)

**Comment by bobmatyas** [comment]
@seanconklin  While we investigate this, you could use Custom CSS as a temporary solution to set the fields to full-width on smaller screen sizes.

**Comment by bobmatyas** [comment]
@Automattic/jetpack-vulcan Is this something you can take a look at?
