### ISSUE TITLE
[Boost] Disable Page Cache feature if setup fails

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#35896]
Suggested in pedxs5-oQ-p2#comment-294

Currently, the feature stays on, but we show an error notice if setup fails. This might be confusing to some users.

We can address that by toggling the feature off if there's an issue with the setup! This would also eliminate the "try again" button, as users would just have to toggle the feature back on again.

**Comment by dilirity** [comment]
Currently blocked by an upcoming PR by @pyronaur

**Comment by thingalon** [comment]
Which PR is the blocker?

**Comment by thingalon** [comment]
Also: The error box is now feedback from trying to turn the feature on. Does that imply we don't need a separate datasync store for the status/error of the cache, and instead should make it a response to the attempt to enable it?

**Comment by dilirity** [comment]
@thingalon this is the blocker PR https://github.com/Automattic/jetpack/pull/35962

**Comment by pyronaur** [comment]
There's a P2 comment related to this here:  pedxs5-oQ-p2#comment-335

**Comment by pyronaur** [comment]
Created a PR that addresses this: https://github.com/Automattic/jetpack/pull/36022
