### ISSUE TITLE
Jetpack Protect: screen header widow

### ISSUE THREAD

**Issue by allilevine** [Automattic/jetpack#35920]
There’s a widow on the Jetpack Protect screen header when scanning.

Context: pfsHM7-fU-p2

![Image](https://github.com/Automattic/jetpack/assets/1689238/41957d73-e087-4f50-91df-db0f7e8d322e)

**Comment by arthur791004** [comment]
Proposed https://github.com/Automattic/jetpack/pull/35935 to prevent text orphans 🙂
