### ISSUE TITLE
[Boost] Improve ISA throttling

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#35944]
If you request two subsequent ISA reports within a short period of time, you will see a 500 error like the image below. This is happening because ISA is throttled and the throttled message turns into a 500 error by the time it reaches the plugin via wp.com. We should do two things to improve it:

1. Relax the throttling a bit. Two consecutive requests aren't too many.
2. Forward the 429 response properly to the client and properly explain what's going on.

![Image](https://github.com/Automattic/jetpack/assets/3737780/e6d8abd9-4a5c-4a60-b818-5dc9d23d4a18)

**Comment by haqadn** [comment]
This was addressed

**Comment by dilirity** [comment]
@haqadn I don't think this part was done:

> Forward the 429 response properly to the client and properly explain what's going on.

Was it?
