### ISSUE TITLE
WPML issue : can't analyse strings of WooCommerce using Jetpack

### ISSUE THREAD

**Issue by benoitfouc** [Automattic/jetpack#35945]
### Impacted plugin

Jetpack

### Quick summary

If you try to analyze the "WooCommerce" plugins via the plugin translation changes analysis tool in "String translation" of WPML and you encounter a never-ending loading problem with a number of files Negatively, this may be due to a WordPress bug related to mixed collation in the WPML channel table.

Following the WPML support it's caused by a Jetpack String "Sorry! We couldn't contact Jetpack just now 😭. " cause of the emoji, that create a mix collaction for columns in database.

They found a workaround by applie this SQL request : 
`ALTER TABLE `wp_icl_strings` CHANGE `context` `context` VARCHAR(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL, CHANGE `name` `name` VARCHAR(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL, CHANGE `domain_name_context_md5` `domain_name_context_md5` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;`

regards
[screencapture-wpml-org-fr-forums-topic-chargement-infini-lors-de-lanalyse-des-composants-string-translation-page-2-2024-02-26-11_24_26.pdf](https://github.com/Automattic/jetpack/files/14403139/screencapture-wpml-org-fr-forums-topic-chargement-infini-lors-de-lanalyse-des-composants-string-translation-page-2-2024-02-26-11_24_26.pdf)

### Steps to reproduce

-install a fresh website in French
-install WooCommerce, WPML, WPML String translation and Jetpack plugins
-wait the next update of WooCommerce 
-try to analyse new translation on WPML String translation

### A clear and concise description of what you expected to happen.

All translation load correctly and we can edit them

### What actually happened

Translation loading stuck, loop.

### Impact

All

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple

**Comment by jeherve** [comment]
Since the string is part of the WooCommerce plugin, I would recommend posting in the WooCommerce repo instead:
https://github.com/woocommerce/woocommerce/blob/caedd5ce91ba9ac82d9a42c6c136d68a839b530a/plugins/woocommerce/includes/admin/class-wc-admin-setup-wizard.php#L2187

However, it may be worth noting that other plugins may include emoji in their strings, so just getting rid of that one string may not be the best approach to solve this problem.
