### ISSUE TITLE
Beta: cannot manage standalone plugin branches from Multisite admin interface

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#35949]
Jetpack Beta does not allow selecting custom branches from its interface on multisite.

> Both are activated network wide, but when I click on the Manage button for Boost it takes me to /wp-admin/network/admin.php?page=jetpack-beta&plugin=jetpack-boost which shows the generic “Sorry, you are not allowed to access this page.”
> 
> The Jetpack Beta settings page itself shows at /wp-admin/admin.php?page=jetpack-beta – without the “network” bit.

Reference: pedxs5-oQ-p2#comment-311

**Comment by anomiex** [comment]
Looks like this was probably broken by #27997, which switched from direct registration of admin pages to using our admin-ui package.

It may be that all we need is to also hook 'network_admin_menu' at https://github.com/Automattic/jetpack/blob/37300ce811d57955115df59d62ed5b35ca3b4cff/projects/packages/admin-ui/src/class-admin-menu.php#L41
That seems to work in a quick test, although I don't know if there are any other side effects.
