### ISSUE TITLE
[Boost] Update Jetpack.com pages to show Boost Cache

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#36010]
Update the Boost page on Jetpack.com to show Boost Cache as a feature. See: pbNhbs-9V7-p2#comment-20823 for guidelines.

**Comment by thingalon** [comment]
This should be done right after release. :)

**Comment by dilirity** [comment]
Patch ready - D141517-code

**Comment by dilirity** [comment]
Patch deployed by @donnchawp today.

Page looks good - https://jetpack.com/boost/

Closing this.
