### ISSUE TITLE
Subscription Site: Polishing Subscription block after the post placement

### ISSUE THREAD

**Issue by pkuliga** [Automattic/jetpack#36021]
Related to peKye1-EA-p2

We would like to release the Subscription block after the post placement toggle. Here is a list of things that still need to be done or reconsidered:

- [x] prevent the Subscribe block from appearing when the Paywall block is visible https://github.com/Automattic/jetpack/pull/36045
- [x] render the Subscribe block before the Share / Like blocks https://github.com/Automattic/jetpack/pull/36240
- [x] add some nudge p1HpG7-rgv-p2#comment-70287 before the block (design needed, cc @crisbusquets) p1HpG7-rgv-p2#comment-70289 https://github.com/Automattic/jetpack/pull/36107
- [x] consider removing the nudge for classic themes since users won't be able to edit it (we decided to leave it there p1709283358476459-slack-C052XEUUBL4)
- [x] polish the Jetpack Newsletter Settings to look good with only one toggle (design needed, cc @crisbusquets) p1HpG7-rrt-p2#comment-70336 https://github.com/Automattic/jetpack/pull/36177
- [ ] Automattic/wp-calypso#88462
- [x] wrap static texts with `__` when we have a final copy https://github.com/Automattic/jetpack/pull/36107 https://github.com/Automattic/jetpack/pull/36177
- [x] add support for inherit anchor bock layout https://github.com/Automattic/jetpack/pull/36107
- [x] add a link to the single post template editor for block themes https://github.com/Automattic/jetpack/pull/36218
- [x] remove custom styles from the `<h2>` element (and make it `<h3>` instead?) https://github.com/Automattic/jetpack/pull/36107#issuecomment-1981464914 https://github.com/Automattic/jetpack/pull/36240

**Comment by simison** [comment]
> what about Calypso Newsletter settings? Do we need this toggle to be added there as well?

Let's hold from this for now, the Calypso page might get ditched pretty soon and we'll rely only on Jetpack version. If by the end of the project that's not the case, we can add it there too.
