### ISSUE TITLE
Goodreads block: star ratings not displayed on frontend

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#36055]
When inserting the Goodreads block, there is a "Show rating" option in the block settings that shows star rations. But looks like there is some CSS hiding the ratings on the frontend.

This URL can be used for testing: https://www.goodreads.com/user/show/1176283-matt-mullenweg

Raised via internal testing: p8oabR-1t3-p2#comment-7876

CC: @Aurorum in case you wanted to have a look.

**Comment by Aurorum** [comment]
Thanks! Out of interest, did you have the Legacy Widget also on your site? It calls some CSS which matches the classes of the Goodreads block. 

Proposed fix in https://github.com/Automattic/jetpack/pull/36059
