### ISSUE TITLE
WooCommerce Support

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#3609]
Out of the box, WooCommerce does not output `the_content`, so things that we tack onto `the_content`, like Likes and Sharing are not displayed by default.

We should add compat for Likes and Sharing, at least. There is a `woocommerce_share` action we can tack it onto, something like 

```
add_action( 'woocommerce_share', 'bk_sharing_display');

function bk_sharing_display(){
echo apply_filters('the_content', null);
}
```
noting that we should do it better than the above, though, since Related Posts would be added as well, which would look strange given the default location.

Idea: 
o PR for Add a "sharing block" function to hook onto `woocommerce_share` that filters null, adding `sharing_display` and `post_likes`
o PR/issue for adding Related Posts to woocommerce_output_related_products (after Woo's output? In place of?). Would also need to whitelist the CPT for the JSON API.

**Comment by BFTrick** [comment]
Hey @kraftbj WooCommerce product pages do indeed display the content. It's just beneath the main content area.

![sharing-icons-bottom-product-page](https://cloud.githubusercontent.com/assets/1065372/14157018/8a00cf50-f686-11e5-9b10-08a7c392f355.png)

A made a little mini plugin that does this for WooCommerce products:

``` php
add_action( 'woocommerce_share', 'patricks_woocommerce_social_share_icons', 10 );
function patricks_woocommerce_social_share_icons() {
    if ( function_exists( 'sharing_display' ) ) {
        remove_filter( 'the_content', 'sharing_display', 19 );
        remove_filter( 'the_excerpt', 'sharing_display', 19 );
        echo sharing_display();
    }
}
```

You can see the outcome here:
http://speakinginbytes.com/2014/12/social-media-icons-woocommerce-products/

> We should add compat for Likes and Sharing, at least.

I agree. I think we should add this to Jetpack. We can wait on related products as that's a much more complicated issue.

I've been meaning to write a PR for this for a while. Mind if I send in a PR?

**Comment by kraftbj** [comment]
Patches welcome! My test product didn't have a description, which led to no content output, including no share buttons. All makes sense now.

For a third-party compat, could you throw it into a PR in the `3rd-party` folder? https://github.com/Automattic/jetpack/tree/master/3rd-party and add to include it in `3rd-party/3rd-party.php`?
