### ISSUE TITLE
Stats block: frontend rendering when stats module disabled

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#36105]
If you've previously inserted the Stats block, then disabled the Jetpack Stats module which is required by the block, the frontend will still render something like `0 hits`. Perhaps the frontend should not render and/or provide a message about requiring the stats module to be active? 

Via Jetpack 13.2 internal testing: p8oabR-1t3-p2#comment-7891

**Comment by Aurorum** [comment]
Should be handled by #36108! :)
