### ISSUE TITLE
[Boost] Broken error messages on cache setup

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#36101]
When cache setup fails, the error message display has become broken. This must've happened in a recent change, as they were working as of yesterday. 

![Image](https://github.com/Automattic/jetpack/assets/1369626/3cc05cd3-08bd-47e0-983b-52382be25f55)

**Comment by haqadn** [comment]
I couldn't reproduce it on trunk

**Comment by dilirity** [comment]
Closing this, as it's not reproducible in latest beta (3.1.1-beta) and on trunk.
