### ISSUE TITLE
[Boost] Critical CSS generation failure CF

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#36110]
I noticed in a [tastewp](https://tastewp.com/#) site that critical CSS generation does not work. They use Cloud Flare and that may have something to do with it. The post request to `set-provider-css` is giving a 302 response, which I think might be related to what's going on.

![Image](https://github.com/Automattic/jetpack/assets/3737780/cd822f88-1f01-42b5-933b-7889707e7c2b)

![Image](https://github.com/Automattic/jetpack/assets/3737780/232a9968-78d3-4d8a-9891-8fc7562a83f9)

**Comment by haqadn** [comment]
This might be related to the C.CSS issues @dilirity

**Comment by dilirity** [comment]
After some investigating, any endpoint ending with `css` has a 302 redirect. Even if you do a `GET` request.

It appears to be either a server configuration or cloudflare that's causing this.

**Comment by dilirity** [comment]
I've reached out to support for more information on this, as it appears it isn't something we can address on our end.

For our end, we could present this error in a way that makes sense. It's still a show stopper, however, the expanded message makes little sense to the user.

**Comment by dilirity** [comment]
tastewp responded and they have fixed the issue.

> We have internal caching in place to decrease out traffic bandwidth and speed up sites out of the box, so users won’t need any plugin to optimize their sites.
CSS is one of 30 extensions that we cache automatically but regex was configured to match any URL that ends with „css" not with „.css”.
> 
> We adjusted it and now the REST API from your example works properly, we updated it for all sites at TasteWP.

Tested and confirm that it works. Closing this.
