### ISSUE TITLE
API: Add AcceptLanguage header to XMLRPC call

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#3613]
In #2606973-t, a user is reporting the following:

> Our server admin told me there's a protection against brute force/DoS attacks and the curl call hast to send an AcceptLanguage Header to work.
> Is there a possibility to do so?

Is it possible for us to add that header to the call sent to XMLRPC? If not, is this something we would consider adding?

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
