### ISSUE TITLE
[Boost] Instead of garbage collection of cache data, refresh it

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#36149]
A WPSC user suggested refreshing cached files rather than deleting them when doing garbage collection [here](https://wordpress.org/support/topic/how-to-distribute-the-prealoding-workload-over-time/).

In a reply, I pointed out that doing so would put a strain on a server, but it might be worth looking into. After all, if a page is cached, it means it was recently visited, so it may well be visited again soon.

**Comment by haqadn** [comment]
There is a slight difference between WPSC GC and Boost in that Boost stops serving cached files immediately when they expire and then refreshes the cache. So, most of the time, if a page is getting traffic, it will refresh before GC can even run.
When GC will finally run, it will find a new file and will not delete it. On the other hand, if we let GC refresh the cache, we will never clear the cache for rarely requested pages, which doesn't seem optimal. So, I don't think we need to do it.

**Comment by haqadn** [comment]
I am closing this as it seems that the cache rebuild feature you are working on might already cover that. Feel free to open it if you want to discuss it further.
