### ISSUE TITLE
Vimeo videos being inserted for any number string used in a comment

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#3615]
A number string in a comment should show up as typed

 A random Vimeo video was inserted in place of the number string

1. Create a comment using Jetpack Comments and insert any number.
2. Note that the number is converted into an embedded Vimeo video, but the rest of the comment is fine.

**Comment by chaselivingston** [comment]
Test comment: This is a 734 comment

**Comment by kraftbj** [comment]
Confirmed.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/update-to-395-major-issue-adding-un-wanted-video-to-comments

**Comment by jeherve** [comment]
For reference, it looks like the issue was introduced in #3535, to fix [another Vimeo bug](https://github.com/Automattic/jetpack/issues/3534).

**Comment by robneu** [comment]
This actually seems like a feature, not a bug. :100:

**Comment by kraftbj** [comment]
@robneu Something something time zones something something April Fools' Joke.
