### ISSUE TITLE
[Boost] Upload documentation to Jetpack.com/support

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#36166]
Alin made some docs for Boost Cache, which @dilirity and I have commented on. They need to be finalized and uploaded to jetpack.com/support - put it under the [performance page](https://jetpack.com/support/performance/) as a page unto itself (or a few pages if that makes more sense)

Draft here: pedxs5-oQ-p2#comment-344

**Comment by dilirity** [comment]
This is done - p1710173612452299/1710155148.769409-slack-C1T3N5AMR. Closing.
