### ISSUE TITLE
Boost: Cache should clear on module setting changes

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#36172]
If you toggle a module that can change page output, we clear the cache. This is great. But, there are settings which we don't clear cache for. For example, if you change minify css/js settings or change image CDN quality, we are currently not clearing cache. Cache clearing should happen automatically in these scenarios.

**Comment by haqadn** [comment]
Thoughts @thingalon ?

**Comment by thingalon** [comment]
Yep, seems like we should clear cache in those circumstances. Can we just add an action for clearing the cache that we trigger whenever we change something that might warrant it?

**Comment by haqadn** [comment]
> Yep, seems like we should clear cache in those circumstances. Can we just add an action for clearing the cache that we trigger whenever we change something that might warrant it?

Something like this? https://github.com/Automattic/jetpack/blob/b1b7351538bac679b6d8475194e05c8c5dbdca95/projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/Boost_Cache_Actions.php#L10-L42
