### ISSUE TITLE
Widget Visibility: Compatibility issues with WPML

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/jetpack#3617]
With WPML installed Widget Visibility does not work as expected.

You can save the visibility for the widget for one language, but if you then switch languages and then add or edit visibility rules the previous rule is broken.

This is likely because of how WPML separates settings like these for different languages and not sure if it is something Jetpack should resolve or WPML.

Here is a gif describing what happens.
![wpml-widget-visibility](https://cloud.githubusercontent.com/assets/1326294/14188667/29ab8ab6-f760-11e5-86e6-5e014dcf4fa0.gif)

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by kokomomtl** [comment]
Sorry for reviving an old thread, but we'd love for this to work with WPML!
