### ISSUE TITLE
[Super Cache] refresh pages rather than delete when doing garbage collection

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#36179]
As suggested [here](https://wordpress.org/support/topic/how-to-distribute-the-prealoding-workload-over-time/), it may be worth it refreshing cache files rather than deleting them when doing garbage collection.

Garbage collection happens on stale pages, but those pages are ones that were visited, so there is a good chance they will be visited again in the future.

The plugin can only refresh pages generated by anonymous visitors, so that excludes any logged in visitors or visitors with a cookie set.

It might even be a better than preloading, as specific pages could be scheduled to be refreshed or preloaded, instead of refreshing all pages.

See also: #36149

**Comment by haqadn** [comment]
Closing this as well following #36149. I think the cache rebuild covers this. Please reopen if this needs further discussion.
