### ISSUE TITLE
Top Bar Refinements: Remove gradient and text shadow from debug button

### ISSUE THREAD

**Issue by eoigal** [Automattic/jetpack#36189]
The gradient and text shadow makes this button feel dated.

Proposed change:

<img width="501" alt="Screenshot 2024-03-05 at 17 45 27" src="https://github.com/Automattic/jetpack/assets/5560595/d34d2fbe-fc25-46a9-9dfa-343c6d6db755">

Project Thread - pfsHM7-oC-p2

**Comment by eoigal** [comment]
Still trying to work out the workflow on this. The debug-bar is a plugin that is included on atomic mu-plugins.

https://github.com/WordPress/debug-bar

I suspect I will need to update the plugin and let core automatically update but need to confirm. Also, not sure how to develop yet.

**Comment by eoigal** [comment]
Discussion here on how to test/install changes on atomic site - p1709738256008539-slack-C7YPW6K40

**Comment by eoigal** [comment]
Looks like I need to fork the repo, create a branch and push a PR to that branch.

This is inline with the how WordPress.org PRs are handled through GitHub - https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/#in-github

https://github.com/WordPress/debug-bar/pull/8

**Comment by eoigal** [comment]
The CSS changes to debug bar have been merged in the debug bar github repo. Waiting on those changes to show up on SVN repository and version to be bumped. When that is done, we can request simple/atomic sites use the latest version with the CSS changes in place.

**Comment by eoigal** [comment]
Debug bar has been updated to 1.1.5 - Atomic are going to test and update if works ok - p9o2xV-3Zv-p2

**Comment by davemart-in** [comment]
Marking this as closed.
