### ISSUE TITLE
Top Bar Refinements: Reduce size of help icon

### ISSUE THREAD

**Issue by eoigal** [Automattic/jetpack#36191]
The help icon should be reduced from 24px by 24px down to 20px by 20px to better map to the size of the other icons in the top bar

<img width="221" alt="Screenshot 2024-03-05 at 17 53 22" src="https://github.com/Automattic/jetpack/assets/5560595/91b481e5-f720-45e0-9d81-8bb15edf5502">

Project Thread - pfsHM7-oC-p2

**Comment by Addison-Stavlo** [comment]
https://github.com/Automattic/wp-calypso/pull/88253 should resolve this. Note this code lives in the calypso repository in the editing toolkit plugin.
