### ISSUE TITLE
Top Bar Refinements: Convert “Proxied” banner to button

### ISSUE THREAD

**Issue by eoigal** [Automattic/jetpack#36190]
We can probably just convert the proxied banner to look similar tot he “debug” button in https://github.com/Automattic/jetpack/issues/36189

<img width="483" alt="Screenshot 2024-03-05 at 17 51 30" src="https://github.com/Automattic/jetpack/assets/5560595/f20eb500-7a2a-46b1-832c-24a798a2f463">

Project Thread - pfsHM7-oC-p2

**Comment by fushar** [comment]
This "Proxied" banner is also shown in some places where the top bar is not present, e.g. the Site Editor:

<img width="1263" alt="image" src="https://github.com/Automattic/jetpack/assets/1525580/ca7c29e4-23f3-4796-91b3-d7e4af995e2f">

What is the plan for this case?

**Comment by davemart-in** [comment]
Calling in @lucasmendes-design to see if he has any thoughts.

**Comment by davemart-in** [comment]
Perhaps we forget about transitioning the banner to a button and instead just leave the banner where it is, but reduce the visual weight and update the color:

## Before

![before](https://github.com/Automattic/jetpack/assets/5634774/457f9bcb-59b8-408e-8ad1-6ee2ea744736)

## After

<img width="1050" alt="CleanShot 2024-03-10 at 06 17 27@2x" src="https://github.com/Automattic/jetpack/assets/5634774/d0d6bf1b-5053-4b30-a031-87589599f2b8">

## CSS
```
#atomic-proxy-bar {
	background: #3858E9;
	border-bottom-left-radius: 2px;
	border-bottom-right-radius: 2px;
	color: #fff;
	font-family: 'Helvetica Neue', Arial, Helvetica, sans-serif;
	font-size: 10px;
	font-weight: bold;
	height: 1.4em;
	left: 50%;
	letter-spacing: 0.2em;
	line-height: 1.4em;
	padding: 2px 8px;
	position: fixed;
	text-align: center;
	text-shadow: none;
	transform: translateX(-50%);
	top: 0;
	z-index: 100001;
}
```

**Comment by roo2** [comment]
Created an atomic P2 post for this, it looks like they have to change it p9o2xV-3YV-p2

**Comment by roo2** [comment]
this will be included in the next atomic platform release p9o2xV-3YV-p2#comment-8984

**Comment by davemart-in** [comment]
This has shipped.
