### ISSUE TITLE
Missing Reblog button

### ISSUE THREAD

**Issue by rosepajaroja** [Automattic/jetpack#36207]
### Impacted plugin

None / Other

### Quick summary

Reblog button is missing, even when enabled in Tools → Marketing → Sharing buttons

![Screen Shot on 2024-03-06 at 17:12:19](https://github.com/Automattic/jetpack/assets/9984867/97d33dd6-8836-44be-a83a-1b95699264e9)

Things I tried: 
1. Disabled and enabled again. 
2. Tested on Incognito window. 
3. Tested on another browser. 
4. Tested on my two test simple sites. 

### Steps to reproduce

1. Enable Reblog in Tools → Marketing → Sharing buttons
2. Visit a post and look for the "Reblog" button. 

### A clear and concise description of what you expected to happen.

See and use the "Reblog" button. 

### What actually happened

"Reblog" button is missing. 

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

**Comment by jeherve** [comment]
I cannot seem to reproduce on my end at the moment. Could you give me a few more details:

- Does this happen regardless of the site status (public, private)?
- Does this happen when using the Like block, or the Legacy likes added to the content automatically?
- Does this happen in different browsers, or just one?

Thank you!

**Comment by rosepajaroja** [comment]
Hello @jeherve, 

>Does this happen regardless of the site status (public, private)?

Yes, I tested both. 

>Does this happen when using the Like block, or the Legacy likes added to the content automatically?

Yes, I also tested both. 

>Does this happen in different browsers, or just one?

I tested on Chrome and Firefox. 

I tested them on my test simple site with Explorer plan. Recorded my screen here:

https://videopress.com/v/wiUdRhnM

Thank you!

**Comment by jeherve** [comment]
Looking at your site, I see you had added the Like block, but did not enable the Reblog option in the sidebar:

<img width="335" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/c9a1f715-c5cc-4167-b771-00ed1310868c">

I enabled it and now I can see the Reblog option on your site. 

Could you check this on the customer's site too?

Note: I took the opportunity to remove the external link you had added to your previous comment. More info here: pbg9X-fWF-p2

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
