### ISSUE TITLE
I want Publicize to share just only the TITLE above my Post with no Excerpt & Link in it.

### ISSUE THREAD

**Issue by dannyraja** [Automattic/jetpack#3623]
Hello there,

As per instruction, I have set Publicize to publish on a Facebook Page, I should get the post title only and a link, like so: http://i.wpne.ws/bCho but I am getting excerpt in it as well.

I want publicize to share just only the TITLE above my post.

Please guide me what to do. Thanks a lot in advance.

**Comment by jeherve** [comment]
To customize the message sent to Facebook, you can use the custom Publicize message box appearing right above the Publish button in your post editor. If you set a custom message there, it will replace the title and the automated excerpt.

![image](https://user-images.githubusercontent.com/15944096/192178903-b9f77919-b8ea-4a76-a13f-0d24a685ae23.png)

**Comment by dannyraja** [comment]
Thank you for the support. Automated excerpt has been removed using custom message option but how can i remove permalink in the post. It is still showing in the published post. I don't want to show the link url in the published post. I just want to show the Title of the post above the featured image.

**Comment by jeherve** [comment]
> how can i remove permalink in the post. 

That's not possible at the moment. Facebook needs that link to generate the post preview that's displayed below the message, along with the featured image, the post title, and the post excerpt.
