### ISSUE TITLE
[Boost] Update Minify/Concat CSS/JS UI

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#36274]
Boost Cache's UI set some new standards for Boost's dashboard UI styling. @ederrengifo has made some UI tweaks to the  Concatenate CSS/JS UI that we can apply easily to keep them consistent.

Ref: p1HpG7-r9A-p2#comment-70457

**Comment by donnchawp** [comment]
Changes:
* Remove the Cancel button
* Use up/down chevron for show/hide link. Change the text "Exclude X Strings" to "Hide" for hiding the options.
* Show snackbar when changes saved. Do that in #36330.
* The options for more recent modules use a grey background for the options. These modules should do the same.

Unsaved changes to the exclude lists will still show when the form is hidden, where it is reset back to the saved value in the Cache Site Pages and Cornerstone Pages form. We will update that so the value is reset.
