### ISSUE TITLE
AI Excerpt: switch to using the PluginPostExcerpt Slot Component

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#36317]
WordPress 6.5 introduces the PluginPostExcerpt Slot Component. This enhancement allows for the extension of the Post Excerpt panel. It may be something we may be able to use for the AI Excerpt feature:

https://github.com/Automattic/jetpack/blob/bdd7a51869b8328712b4a34707e5ce6f220bb94a/projects/plugins/jetpack/extensions/plugins/ai-content-lens/extend/ai-post-excerpt/index.tsx#L46

https://github.com/WordPress/gutenberg/pull/55200

**Comment by retrofox** [comment]
we are considering to deprecate the plugin: https://github.com/WordPress/gutenberg/pull/61188

**Comment by retrofox** [comment]
Confirmed. Closing the issue.
