### ISSUE TITLE
Blog Stats and Top Posts blocks: rendering in email newsletter

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#36336]
Should the `blog-stats` and `top-posts` blocks be rendering outside of the frontend context (e.g. they show in email newsletters)? Since the data for both blocks should be dynamic in nature, I'm not sure if it makes sense to have these rendering outside the frontend 🤔 

<img width="788" alt="Screenshot 2024-03-11 at 1 58 16 PM" src="https://github.com/Automattic/jetpack/assets/15803018/98049be8-0354-4a3c-b0e1-9158c5a2c45f">

CC: @jeherve @kangzj @Aurorum who worked on these blocks recently.

**Comment by Aurorum** [comment]
Thanks @samiff! 

What’s the best way to handle this sort of thing? Is it preferable to render nothing at all, or a message telling the user they’d need to check the site for the block?

**Comment by jeherve** [comment]
> I'm not sure if it makes sense to have these rendering outside the frontend 🤔

I don't think so.

> What’s the best way to handle this sort of thing?

You can add a `jetpack_is_frontend()` in the rendering method.

**Comment by samiff** [comment]
> Is it preferable to render nothing at all, or a message telling the user they’d need to check the site for the block?

@Aurorum Rendering nothing at all should work here. [Here](https://github.com/Automattic/jetpack/blob/26ad4f85364575f381df4dc7e970f3122c57e26e/projects/plugins/jetpack/extensions/blocks/sharing-buttons/sharing-buttons.php#L36) is an example.

**Comment by Aurorum** [comment]
Done in #36372 but I'm having some issues testing - would appreciate some guidance on if I'm doing something wrong!
