### ISSUE TITLE
Boost: Show confirmation when enabling/disabling features

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#36330]
> [!NOTE]
> This is blocked by:
> https://github.com/Automattic/jetpack/issues/28192
> https://github.com/Automattic/jetpack/issues/38169
> https://github.com/Automattic/jetpack/issues/36274

We should utilize the snackbar more, to give more feedback to the user.

We also clear the cache when toggling some modules on or off, but we don't tell that to the user.

**Comment by dilirity** [comment]
This is blocked by:
https://github.com/Automattic/jetpack/issues/28192
https://github.com/Automattic/jetpack/issues/38169
https://github.com/Automattic/jetpack/issues/36274

**Comment by haqadn** [comment]
The  note mentioning the issue is blocked by other issues. Is this accurate? I don't think those issues block it.

**Comment by dilirity** [comment]
It is blocked. We're doing this last to reduce conflicts when changing components.

**Comment by donnchawp** [comment]
Progress on blockers:
This is a PR ready to be reviewed for the Tracks issue at https://github.com/Automattic/jetpack/issues/28192
https://github.com/Automattic/jetpack/issues/36274 is closed, and the UI has been updated.
