### ISSUE TITLE
Subscription Site: Improve toggle copy

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/jetpack#36342]
### Impacted plugin

Jetpack

### What

Improve copy so they're more concise and easy to skim.

### Current implementation
https://github.com/Automattic/jetpack/pull/36218

![image](https://github.com/Automattic/jetpack/assets/25607244/72d94ef5-3762-4924-9dd5-c5f8aadf7340)

### Proposal

- Allow visitors to subscribe to your site
- Add the Subscribe Block at the of each post. Preview and edit
- Subscription pop-up when scrolling a post. Preview and edit
- Enable the “subscribe to site” option on your comment form
- Enable the “subscribe to comments” option on your comment form

<img width="1098" alt="Screenshot 2024-03-12 at 12 39 08" src="https://github.com/Automattic/jetpack/assets/25607244/55dd4368-69ae-4da2-a048-bb43503b4b58">

**Comment by pkuliga** [comment]
@simison are you ok with those changes?

I'm not sure about "Subscription pop-up when scrolling a post.", maybe "Show subscription pop-up when scrolling a post." instead?

**Comment by crisbusquets** [comment]
> @simison are you ok with those changes?
> 
> I'm not sure about "Subscription pop-up when scrolling a post.", maybe "Show subscription pop-up when scrolling a post." instead?

Good catch, @pkuliga! Yes, let's add the verb :)

**Comment by simison** [comment]
Looks good! I think we can fine-tune copy around enable/show/drop the verb later down the road if need. It feels a bit repetitive now but no strong opinion on this.
