### ISSUE TITLE
Sharing: Button style "Only Icon" hiding text

### ISSUE THREAD

**Issue by gugaalves** [Automattic/jetpack#3634]
Configuring sharing buttons at /wp-admin/options-general.php?page=sharing , when I choose "Only Icon", this HTML is used on front-end on a Facebook button, for example:

`
<li class="share-facebook">
<a rel="nofollow" data-shared="sharing-facebook-1413" class="share-facebook sd-button share-icon no-text" href="[post permalink]" target="_blank" title="Click to share on Facebook">
<span>
<span class="share-count">2</span>
</span>
<span class="sharing-screen-reader-text">Click to share on Facebook(open on a new window)<span class="share-count">2</span></span>
</a>
</li>
`

HTML text 'Click to share on Facebook' is still there and Google Search Console now is saying that "Click", "Share" and social network names are the most important words on my content. I believe this is really bad for SEO purposes and a conditional tag must be used to hide this span tag with sharing-screen-reader-text css class when 'Only Icon' option is selected on Publicize.

**Comment by macmanx2** [comment]
Screen reader text isn't really about SEO, it's about accessibility. When a visually impaired visitor navigates down to the sharing buttons, they'll hear "Click to share on Facebook (open on a new window)" (and etc for the other buttons) so that they can share content even if they can't see the icons themselves.

If you remove the screen reader text, you'll essentially remove sharing buttons for visually impaired visitors.

**Comment by gugaalves** [comment]
I know it's about accessibility, but the link title is read by this systems too, so if we remove it we'll not prejudice it..

**Comment by macmanx2** [comment]
We do have to consider older screen readers which do not read the link title.

**Comment by samazgor** [comment]
@macmanx2 How to use custom text instead of "Click to share on Facebook" ??

**Comment by jeherve** [comment]
@samazgor Jetpack currently doesn't include any option to allow you to customize this text. You could, however, use a plugin like [Say What?](https://wordpress.org/plugins/say-what/) to customize the strings on your site.
