### ISSUE TITLE
Should allow for "const WP_CACHE" in wp-config.php durlig setup

### ISSUE THREAD

**Issue by knutsp** [Automattic/jetpack#36358]
### Impacted plugin

Boost

### Quick summary

In case "define" followed by "WP_CACHE" is found the wp-config.ph file, the line
`define( 'WP_CACHE', true ); // Boost Cache Plugin`
is added.

It should not be added if
`const WP_CACHE = true;`
can be found.
See Page_Cache_Setup.php

### Steps to reproduce

1. Ensure wp-config.ph contains `const WP_CACHE = true;`
2. Install and activate Jetpack Boost
3. Turn on Page Cache in Jetpack Boost dashboard
4. Inspect PHP error_log and observe massive amount of error messages about WP_CACHE already being defined

### A clear and concise description of what you expected to happen.

1 No added line i wp_config.php
2 Noe PHP errors as mentioned above

### What actually happened

Massive amount of PHP error messages about WP_CACHE already being defined

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by haqadn** [comment]
Thanks for reporting the issue. It's currently in our TODO.

**Comment by dilirity** [comment]
@knutsp hey! Just dropping by to mention that we've fixed this and it will be shipped in the next version of Boost that should go out this week.
