### ISSUE TITLE
Multisite: can't connect from the network admin when Jetpack is not active in sub-site

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#3641]
#### What I expected
I wasn't able to connect a site though the network admin even though the was a button that I could click in the network admin.

#### What happened instead
Nothing I forwarded to an error page.

#### Steps to reproduce the issue
Create a new site. 
Jetpack is not enabled on the site yet . 

Go to Network -> Jetpack 
Click on the connect link next to the site. 

I was able to connect Jetpack by activating the plugin first on the site that I wanted to connect. 

I think the link should know if the plugin is activated in the site or not. Maybe show the button to activate Jetpack instead.

**Comment by jeherve** [comment]
I can't seem to reproduce at the moment.

![screen shot 2016-04-11 at 4 00 48 pm](https://cloud.githubusercontent.com/assets/426388/14429661/9d6fa7e2-fffe-11e5-9af7-9b4ee6f06d89.png)

> an error page.

What was the error? Did you have anything in your logs about this issue?

Possibly related: #2540 and #3506

**Comment by enejb** [comment]
When I click the connect button this is what I get

![screen_shot_2016-04-12_at_15_50_44](https://cloud.githubusercontent.com/assets/115071/14477956/688ce666-00c6-11e6-9253-abc8708c6020.png)

Just to confirm. Jetpack is not network activated on my end. How can I still see it on the network admin if it is not network activated? 

To get the activation working I need to first activate the jetpack plugin. 
I think this needs to be fixed by only showing the network admin for Jetpack when it is network activated.

**Comment by jeherve** [comment]
> Jetpack is not network activated on my end. How can I still see it on the network admin if it is not network activated?

Right, that seems to be the issue here.

> I think this needs to be fixed by only showing the network admin for Jetpack when it is network activated.

That seems reasonable. Another alternative would be to show an "Activate" button instead of "Connect".

**Comment by jeherve** [comment]
This is still an issue, even when #3772 is applied.

Steps to reproduce:

1. Make sure Jetpack is not network activated in your network.
2. Find a site where Jetpack is not activated.
3. Go to Network > Jetpack.
4. Find that site in the list.
5. You'll see a "Connect" button.
6. Click on it.

![screen shot 2016-06-09 at 3 22 29 pm](https://cloud.githubusercontent.com/assets/426388/15931050/3dcce5b2-2e56-11e6-9e0b-c1b86f46687e.png)

I think the "Connect" button shouldn't appear when Jetpack isn't active on the site. Instead, we could show an "Activate and Connect" button, or a link to the individual site's plugins screen to activate the plugin.
