### ISSUE TITLE
Attempt to read property "ID" on null

### ISSUE THREAD

**Issue by knutsp** [Automattic/jetpack#36422]
### Impacted plugin

Boost

### Quick summary

`PHP Warning:  Attempt to read property "ID" on null in .../wp-content/plugins/jetpack-boost/app/modules/image-size-analysis/Image_Size_Analysis_Fixer.php on line 103
PHP Warning:  Attempt to read property "ID" on null in .../wp-content/plugins/jetpack-boost/app/modules/image-size-analysis/Image_Size_Analysis_Fixer.php on line 133`

### Steps to reproduce

1, Install and activate Jetpack Boost
2. Upgrade Boost or have Jetpack Complete product

### A clear and concise description of what you expected to happen.

No such log warnings, especially when Image Guide and fix is not enabled

### What actually happened

Log entris as mentioned above

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by bobmatyas** [comment]
Report on 8162693-zen
