### ISSUE TITLE
Slideshow Block: Navigation (Dots and Numbers) is left-aligned

### ISSUE THREAD

**Issue by hacchism** [Automattic/jetpack#36494]
### Impacted plugin

Jetpack

### Quick summary

Navigation below a slideshow should be centered by default as far as I can see in the following support guide from DotCom and Jetpack:

https://wordpress.com/support/wordpress-editor/blocks/slideshow-block/
https://jetpack.com/support/jetpack-blocks/slideshow-block/

However, it currently shows up with left-aligned.

### Steps to reproduce

1. Create a page.
2. Add the Slideshow Block.
3. Publish the page.

### A clear and concise description of what you expected to happen.

Navigation is centered as follows:

![Screen Shot on 2024-03-21 at 14:09:00](https://github.com/Automattic/jetpack/assets/32432463/cb8ca0dc-9596-40a0-b5f7-ecf4b54d90d5)

### What actually happened

Navigation is left-aligned as follows:

![Screen Shot on 2024-03-21 at 14:09:44](https://github.com/Automattic/jetpack/assets/32432463/f091a16d-3ad1-4d5c-94ca-1424331fd82d)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

CSS workaround.

For dots navigation:
```
.wp-block-jetpack-slideshow_pagination.swiper-pagination.swiper-pagination-white.swiper-pagination-custom {
    justify-content: center;
}
```

For number navigation:
```
.wp-block-jetpack-slideshow .wp-block-jetpack-slideshow_pagination.swiper-pagination-custom .swiper-pagination-simple {
    text-align: center;
}
```

**Comment by jeherve** [comment]
This was done on purpose, so the design better matches Jetpack's Carousel feature. You can read more about it here: #27708
