### ISSUE TITLE
Subscriptions: scroll is visible when loading modals

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/jetpack#36497]
### Impacted plugin

Jetpack

### Quick summary

While doing my annual support rotation I noticed that the scrollbar is visible on the following (and it shouldn't):

- subscription confirmation modal
- tier selection
- payment form (although in this case is debatable)

See screenshots below:

![Roy-Mustang-The-Flame-Alchemist-–-Full-Metal-Alchemist-Brotherhood](https://github.com/Automattic/jetpack/assets/25607244/4f3cdb9c-a260-4ed6-b681-803aada06eda)
![KABOM-BIKERS-BLOG-»-Contact-»-VÅRT-LIVS-ÄVENTYR-](https://github.com/Automattic/jetpack/assets/25607244/321bcef2-05f7-4903-a10d-d846cc92c6fc)
![Roy-Mustang-The-Flame-Alchemist-–-Full-Metal-Alchemist-Brotherhood (1)](https://github.com/Automattic/jetpack/assets/25607244/18961dc7-99d1-4212-bac8-faf58e95ede2)

### Steps to reproduce

1. Subscribe to any blog with newsletters to see the subscription confirmation modal
2. Subscribe to any blog with a Newsletter Tier

### Impact

All

### Available workarounds?

There is no user impact

**Comment by pkuliga** [comment]
Fixed by D143098-code
