### ISSUE TITLE
Unsubscribe links doesn't seem to work

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/jetpack#36504]
### Impacted plugin

Jetpack

### Quick summary

Some users have reported that they (or their subscribers) can't unsubscribe when clicking the "Manage subscription" button on emails.

7880108-zd-a8c
7917880-zd-a8c

### Steps to reproduce

1. Open any newsletter email
2. Click "Manage subscription"
3. The Subscription Management page is empty / "Subscription not found"

This is a screenshot one user shared (a subscriber shared this with them):

![2-no-way-to-unsubscribe](https://github.com/Automattic/jetpack/assets/25607244/57c693ba-2e7f-426a-8fef-83c738b3189c)

### A clear and concise description of what you expected to happen.

Subscribers should be able to easily unsubscribe from any blog they're subscribed to.

Related to the first site (South Coast View) I tried to subscribe and it wasn't possible.
I've subscribed to the other site (Jardinier Paresseux), once I receive an email I'll be able to test the complete flow.

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Logs or notes

I choose "Yes, difficult to implement" because users should be able to search for that site within Subscription Management and access the specific site (although I'm not sure if this would work).

**Comment by cat-og** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated 


📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate this, but not consistently. 
- I was indeed able to manage the subscription by going to 'Manage All Subscriptions' and searching for the site URL, but I noticed that when I did, the url and subscription number were different than where the link from the email had tried to send me. 

📌 ACTIONS
- Triaged

**Comment by jeherve** [comment]
Could it be that those folks were logged in with a different WordPress.com account, like in #5407?

**Comment by crisbusquets** [comment]
> Could it be that those folks were logged in with a different WordPress.com account, like in #5407?

Good point @jeherve. I'm not sure about the behavior here: shouldn't the link have prominence over the logged-in account? Or at least ask to log in / let them know that they're logged-in on a different account?

cc @Automattic/zap (this is the GH issue related to what we were discussing in the P2 (peKye1-Mf-p2)).

**Comment by foleynotrose** [comment]
@crisbusquets or @Automattic/zap are there any updates about this? We've still got the ticket on hold.

**Comment by chatoxz-wp** [comment]
@crisbusquets or @Automattic/zap, are there any updates on this? I put the ticket on hold again.

**Comment by jenhooks** [comment]
I've put this on hold again.

**Comment by danjjohnson** [comment]
@crisbusquets Any update here? It looks like a 'switch accounts' link has been added? My concern is that unless they realise they are logged into the wrong account, they might not think to use that link. Is there a way we can explain the issue better if they click an unsubscribe link in an email that was sent to an account other than the one they are logged into?

I agree with what you mentioned above:

> I'm not sure about the behavior here: shouldn't the link have prominence over the logged-in account? Or at least ask to log in / let them know that they're logged-in on a different account?

**Comment by danjjohnson** [comment]
Ah I've just seen https://github.com/Automattic/wp-calypso/issues/90460

Looks like that should help 👍 

I'll leave this open for now, so we can reply to the affected users once that context has been added.

**Comment by crisbusquets** [comment]
> I'll leave this open for now, so we can reply to the affected users once that context has been added.

Thanks @danjjohnson ! Let us know if there's feedback related to that.

**Comment by simison** [comment]
I'll close this as the solution we made seems to be working to clear confusion, and if there are more cases they're about something else and new issue would be good then.
