### ISSUE TITLE
Fix the CSS for the "Sharing Settings" page on Simple sites

### ISSUE THREAD

**Issue by DustyReagan** [Automattic/jetpack#36507]
On a WPCOM Simple site the CSS is missing for "Sharing Settings"

<img width="1724" alt="Screenshot 2024-03-21 at 12 15 48 PM" src="https://github.com/Automattic/jetpack/assets/140841/627e51b5-24b8-4165-bf66-530738bb6589">

It should look closer to this (as seen on an Atomic site):

<img width="1725" alt="Screenshot 2024-03-21 at 12 20 09 PM" src="https://github.com/Automattic/jetpack/assets/140841/6cb99506-3d0a-4ef2-b736-8f9dcdf0ce2a">

Check the styling on "Sharing Settings" when a block based and non-block based theme is applied to the site.

**Comment by taipeicoder** [comment]
Proposing a fix via D142875-code.

**Comment by DustyReagan** [comment]
Fix merged! 🚀
