### ISSUE TITLE
Static Analysis: throw error if using a function newly in the latest WP version

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#36514]
### Impacted plugin

None / Other

### What

We should throw if new code is attempting to use a brand new WP function.

### How

The Jetpack repo has a general WP stable -1 minimum support version policy, so currently both 6.3 and 6.4 are supported. If new code is using a function that was first defined in WordPress 6.4, it needs some type of gating—function exists, version check, etc.

To help ensure that happens, let's throw an error. If we can detect the gating, that would be cool, but I think it's acceptable that we can suppress it via notation.

Example of a situation that I'd like to prevent:
https://github.com/Automattic/jetpack/pull/35277 patched via https://github.com/Automattic/jetpack/pull/36511

**Comment by anomiex** [comment]
Fixed in #36530, I believe?
