### ISSUE TITLE
Custom CSS: Excessive memory usage with many revisions

### ISSUE THREAD

**Issue by adamfranco** [Automattic/jetpack#3651]
One of my users is a significant user of the Jetpack Custom CSS editor in his site, making over 9,000 revisions to his CSS over the course of year. As the number of Custom CSS revisions has grown, the Custom CSS editor has begin crashing due to excessive memory usage caused by the revisions meta-box.
#### What I expected

The Custom CSS Editor (theme.php?page=editcss) continues to load no matter how many revisions are made.
#### What happened instead

The Custom CSS Editor (theme.php?page=editcss) uses more than 1GB of memory loading all 9,000 revisions, exceeding PHP's `memory_limit`.
#### Steps to reproduce the issue

Repeatedly edit custom CSS many many times (in our case the css content is also approximately 7,000 lines long).

There are two related issues when many Custom CSS revisions exist:
1. The revisions meta-box doesn't limit the number of 'posts_per_page' when checking if any revisions exist. It should limit the number of results to 1 as a simple existence check. (I have a pull request ready for this portion of the issue.)
2. The "show all" view of revisions will hit resource limits and should likely be reworked to paginate results.

**Comment by kraftbj** [comment]
Cleaning up some old tickets. I'm going to close this as a invalid since we're on Core's CSS editor now.
