### ISSUE TITLE
Enhancement:Add WC Category pages to the built-in Jetpack sharing functionality

### ISSUE THREAD

**Issue by CMCTX** [Automattic/jetpack#36531]
### Impacted plugin

Social

### What

I want to add share buttons on WC product category pages, but this is not an option I can select in my Jetpack Sharing Buttons settings

### How

I want to add share buttons on WC product category pages, but this is not an option I can select in my Jetpack Sharing Buttons settings. Included options are Front Page, Archive Pages, and Search Results, Posts, Pages, Media and Products. It would be helpful if, in a future update, you could add WC Category pages to the built-in Jetpack sharing functionality.

**Comment by jeherve** [comment]
Thank you for the feedback. Jetpack's Sharing feature doesn't currently support sharing archive/category pages, as you discovered. That's a potential improvement we're tracking in #16130. I'll consequently close this issue as duplicate.
