### ISSUE TITLE
`search-widget.js` is loaded despite instant search turned off

### ISSUE THREAD

**Issue by swissspidy** [Automattic/jetpack#36555]
### Impacted plugin

Jetpack, Search

### Quick summary

I disabled instant search, but for some reason Jetpack still loads `search-widget.js` on the frontend that is only relevant for the checkboxes in the search modal. It is not relevant for regular search experience and thus should not be enqueued by default.

### Steps to reproduce

1. Enable search, disable instant search
2. Visit frontend
3. See the JS file being unnecessarily loaded on every page

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

- Twenty Twenty-Four theme

**Comment by jeherve** [comment]
The widget is useful when Instant Search is off ; it allows you to display custom filters alongside a search form, allowing visitors to filter their search results down to specific results.

That said, if you are not interested in the custom Search Widget provided with Jetpack's Search feature, you can use a regular Search widget instead. If Jetpack's Search widget is not added to your site, the related script will not be enqueued:

https://github.com/Automattic/jetpack/blob/d880a621e9a9d1376df37744fad257e7bd066bf7/projects/packages/search/src/widgets/class-search-widget.php#L166-L168

I hope this clarifies things a bit.

**Comment by swissspidy** [comment]
> If Jetpack's Search widget is not added to your site, the related script will not be enqueued

@jeherve I have the regular Search block in my block theme, no Jetpack search widget whatsoever.

**Comment by jeherve** [comment]
Can you check the contents of the "Jetpack Search Sidebar" sidebar area on your site? Do you happen to have the Jetpack Search widget in there?

**Comment by swissspidy** [comment]
Twenty Twenty-Four is a block theme, there are no sidebar areas anymore and no widgets.

Anyway, I just completely disabled the Search module

**Comment by jeherve** [comment]
> Twenty Twenty-Four is a block theme, there are no sidebar areas anymore and no widgets.

Yes, that's something that needs to be improved in the Search feature. This is outlined in #28426 and #24594. Until that is improved, and if you're interested in using Jetpack Search without Instant Search, you should still be able to go to Appearance > Widgets (you'll find the menu item is available even when using a block-based theme like Twenty Twenty Four) and remove the Jetpack Search widget from the "Jetpack Search Sidebar" sidebar area.

Let me know how that goes!

**Comment by swissspidy** [comment]
> you should still be able to go to Appearance > Widgets (you'll find the menu item is available even when using a block-based theme like Twenty Twenty Four)

No I am not.

The menu item doesn't exist, nor does it in the customizer. If you visit `/wp-admin/widgets.php` directly you get an error message:

> The theme you are currently using is not widget-aware, meaning that it has no sidebars that you are able to change. For information on making your theme widget-aware, please [follow these instructions](https://developer.wordpress.org/themes/functionality/widgets/).

<img width="832" alt="Screenshot 2024-03-25 at 13 15 05" src="https://github.com/Automattic/jetpack/assets/841956/0e791ea7-ab94-4c55-a7f8-287ed42e3193">

**Comment by jeherve** [comment]
That's interesting. I would expect it to be there, and it does appear on my end when testing with Twenty Twenty Four, WP 6.4.3, and whether I use Jetpack or the Jetpack Search standalone plugin:

<img width="1396" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/25b99dd0-4998-4f54-90da-561548963fde">

I do not use any other plugins on that site.

Could you tell me more about your site? Do you use Jetpack or the Jetpack search plugin? If you were to enable Instant Search for a minute, does the Widgets menu then appear, maybe?

**Comment by swissspidy** [comment]
OK weird, on my personal site that doesn't happen, but I'm now unable to reconnect the Search feature somehow. So I just tried to reproduce this on another site:

1. Enabled search module
2. Widgets page is accessible, with Jetpack sidebar editable
3. Do not change widgets at all
4. Disable Instant search
5. Widgets page is no longer visible/accessible
6. `search-widget.js` is still loaded

After changing to a classic theme, I noticed Jetpack just added its own Search widget to one of the sidebars, where the website previously didn't have a Search widget at all. And I was unable to replace that with the normal Search widget unless I turned off Jetpack search.

All in all I'm not sure how to reproduce the original issue from my personal site again (as I can't connect right now), but it's weird that this widget was ever added on my site where I only use a block theme and was never able to customize widgets

**Comment by jeherve** [comment]
Thank you! I think part of the problem is this:

> Disable Instant search
> Widgets page is no longer visible/accessible

I believe the page should be available even when Instant Search is inactive, since we set the widget with classic search too. @Automattic/red Do you recall on this is supposed to work?

**Comment by jeherve** [comment]
> I'm now unable to reconnect the Search feature somehow

Do you get a specific error when trying to connect your site to WordPress.com?

**Comment by swissspidy** [comment]
> Do you get a specific error when trying to connect your site to WordPress.com?

It's stuck in a loop here:

https://github.com/Automattic/jetpack/assets/841956/77539c6f-2db9-4f96-84c2-2787c9a1801f

**Comment by jeherve** [comment]
> It's stuck in a loop here:

It may be worth deactivating, then deleting the plugin entirely, and then installing it again and reconnecting. Let me know how that goes!

**Comment by swissspidy** [comment]
Just did that, and after a couple of hiccups was able to set up Search again (without Instant Search). `search-widget.js` is 
**not** loaded now.
