### ISSUE TITLE
WordAds: issues dismissing the GDPR Consent Management banner

### ISSUE THREAD

**Issue by ghost** [Automattic/jetpack#36579]
### Impacted plugin

Jetpack

### Quick summary

Wordpress Plugin Jetpack with Wordpress WordAds:
The Cookies & Consent Banner is showing every page. On click Accept nothing happens.
On the next page the Banner is also showing.
Look at www.smartinfo.me/blog

 

### Steps to reproduce

1. on visit the wordpress site www.smartinfo.me the cookie banner is showing
2. on klick Accept cookies the wordpress file admin-ajax.php is calling.
3. the js file cmp.bundle.js calls this: https://smartinfo.me/wp-admin/admin-ajax.php 
4. wordpress is on folder /blog/ installed 
5. the link to admin-ajax.php after klick ok in cookie banner is wrong
6. Now the cookies not set und banner is showing on every page
7. 

### A clear and concise description of what you expected to happen.

Please help how can i fix this bug.
Screenshot: https://smartinfo.me/cookiebanner.png

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by jeherve** [comment]
> the link to admin-ajax.php after klick ok in cookie banner is wrong

That seems to be the source of the problem on your site. Could you tell us more about your site setup?

- What are your site URL and WordPress URL settings under Settings > General in your dashboard?
- Is your WordPress installation all situated in the `/blog` directory on your server, or do you use a specific plugin to move that location?

Thank you!

**Comment by jeherve** [comment]
cc @Alameen688 and @cphilleo who worked on #35165 ; you may have to make changes to how the AJAX URL is built in the CMP script so it uses the site URL defined on the site.

Thank you!

**Comment by Alameen688** [comment]
Thanks a lot, @jeherve.

Thanks for reporting @FranzHabegger, this issue has been fixed and the banner should work correctly on your site now.
