### ISSUE TITLE
Jetpack content template of infinite scroll with get_theme_mod

### ISSUE THREAD

**Issue by abouolia** [Automattic/jetpack#3657]
As you know Infinite Scroll module hooked into `init` with priority 20, Unfortunately that didn't give any chance to the preview filters of the customizer to alter the values on render function that holds content template part, according to the my experience the only solution for this issue hook infinite scroll into `wp_loaded` hook, i'm waiting some suggestions for this issue. Thanks :)

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
