### ISSUE TITLE
SSO: Can't link users on MU installs

### ISSUE THREAD

**Issue by lezama** [Automattic/jetpack#3661]
#### What I expected
Users on mu install should be able to link their accounts to SSO.

#### What happened instead
Nothing ¯\_(ツ)_/¯.
The "link" button does exactly nothing.

#### Steps to reproduce the issue
* Go to your user profile on a MU install.
* Try to link your user.

**Comment by dereksmart** [comment]
no bueno.  Running master (or current beta)?

**Comment by lezama** [comment]
master

**Comment by kraftbj** [comment]
For me, it returned an AYS, I believe this one: https://github.com/Automattic/jetpack/blob/master/modules/sso.php#L615 when clicking the button on the user profile.

The result leaves me logged out too. The nonce on the URL from wp.com and the initial one match, so my initial thought is we're being logged out so the current user is 0, thus the nonce fails.
