### ISSUE TITLE
PHP Notice when accessing Dashboard > Updates

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3662]
> I have WP_DEBUG on and I see the following notice being thrown by Jetpack when accessing the Admin Updates screen.

```
Notice: Undefined property: stdClass::$plugin in /path/to/wp-content/plugins/jetpack/class.jetpack-autoupdate.php on line 43
```

Reported here:
https://wordpress.org/support/topic/php-notice-being-thrown-on-wp-contentupdate-corephp?replies=1&view=all

**Comment by lezama** [comment]
I am not being able to reproduce this in 4.1

**Comment by jeherve** [comment]
I can't reproduce anymore either. Closing.
