### ISSUE TITLE
Update "Subscribed" link to individual subscription page

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/jetpack#36631]
Update the [✔  Subscribed] button so it opens the individual subscription page instead of the generic one:

![Image](https://github.com/Automattic/jetpack/assets/25607244/63c9eae5-9279-4834-9cd0-d73849c4c8a8)

**Comment by pkuliga** [comment]
Not sure how to approach this. Right now after the "Subscribed" button is clicked the form is posted to the `https://wordpress.com/email-subscriptions` which redirects the user to the subscriptions list `https://wordpress.com/read/subscriptions` if subscribed.

Should we just change the redirect URL or post this form directly to the individual subscription page if subscribed?

@Automattic/zap WDYT?

This is where this form is created https://github.com/Automattic/jetpack/blob/9ff8a8998ceeb12ca28b5e385e6867b0b1bda328/projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php#L689

**Comment by simison** [comment]
Both work for me:

- Change the redirect to correct place
- Unwrap the "subscribed" button from form and turn it into a simpler link, instead of a form
