### ISSUE TITLE
Publicize: Allow contributors to setup accounts

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#3664]
Currently, Publicize can be used by users with `publish_posts` capability. Per request in 2559459-t, allowing this for `edit_posts` would allow contributors to setup accounts that it would publish to once an user of higher role publishes the post.

In addition to Jetpack modifications, similar ones would need to be made to Calypso.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
