### ISSUE TITLE
Enhancement: consider displaying the UI of 3rd party widgets in site language

### ISSUE THREAD

**Issue by monsieur-z** [Automattic/jetpack#36646]
### Impacted plugin

Jetpack

### What

Jetpack includes blocks that render a 3rd party widget (OpenTable, Eventbrite, Calendly). When possible, we should ensure the UI of these widgets is rendered in the site language.

### How

Platforms that support multiple languages usually accept the language as query parameter when embedding the widget.

**Comment by simison** [comment]
Embeds from PocketCasts would be interesting to check since we can improve it in-house.

**Comment by coder-karen** [comment]
For now after investigating each of the widgets I'll close this issue as for each there is either a translation option available or an obvious way to pass the locale hasn't been found (eg. access to developer accounts / docs online explaining the possible params / experimenting with passing locales manually in different forms).

Some notes:

- Calendly itself (in it's UI) has a setting to show which language the UI should display in, and it does display in that language.
- OpenTable has a setting within the block settings itself to change the language.
- EventBrite - the block UI itself has a language dropdown for events. 
- Tock - while we can define 'data-tock-locale' in three places within our code, changing these makes no difference from my testing, nor manually adding query params to any URLs.

For PocketCasts, I'll move any conversation elsewhere. Slack ref: p1714750949869969-slack-C06EHRAPW12
