### ISSUE TITLE
Enhancement: Blogging Prompt - link to the answers page in the site language

### ISSUE THREAD

**Issue by monsieur-z** [Automattic/jetpack#36648]
### Impacted plugin

Jetpack

### What

No matter the site language, the Blogging prompt block links to the same URL on wordpress.com

### How

Adding the site language as a query parameter to the URL could probably load the site in the correct language, when users are not authenticated to WordPress.com.

_The link_ Ver todas las respuestas _directs unauthenticated users to a page in English instead of Spanish._
<img width="500" alt="Screenshot 2024-03-28 at 1 55 55 PM" src="https://github.com/Automattic/jetpack/assets/1620183/6a63bb43-82e4-42cc-a2f8-61e08239a090">

**Comment by DustyReagan** [comment]
@jeherve 👋 I see there are a couple of proposed solutions to this issue that have "staled" waiting for a [more centralized solution](https://github.com/Automattic/jetpack/issues/2707#issuecomment-2036701663). Do you think we'll have a centralized solution soon, or can we revive one of the proposed PRs to move this issue forward?

**Comment by jeherve** [comment]
I'm afraid no one has made any progress on that centralized solution. It's not currently on any team's roadmap, but if your team has the bandwidth, it would allow everyone to make progress on this.

If you cannot pick this up, I think reviving #36730 may be an acceptable workaround for now.

**Comment by DustyReagan** [comment]
Thanks, @jeherve! I'm keen to move forward with #36730. @Automattic/loop has this issue in a short CANI sprint before our next project. I fear it might get put back on ice otherwise. 😅
