### ISSUE TITLE
Cookie Consent: changes to the copy aren't reflected in the site

### ISSUE THREAD

**Issue by monsieur-z** [Automattic/jetpack#36645]
### Impacted plugin

Jetpack

### Quick summary

Users can edit the text of the Cookie Consent block in the site editor. However, the banner on the site keeps displaying the default text.

### Steps to reproduce

- Select a test site on WordPress.com
- If the theme supports it, you should be able to access the site editor under `Appearance > Editor`
- Choose a page and add the Cookie Consent block
- Edit the copy and save the changes
- Open the preview
- You should see the default text instead of the updated one

### A clear and concise description of what you expected to happen.

Changes should be reflected on the site.

### What actually happened

On the site, it seems that the block keeps displaying the default text.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

_Editor_
<img width="1622" alt="Screenshot 2024-03-28 at 11 13 56 AM" src="https://github.com/Automattic/jetpack/assets/1620183/c4df0b95-c7e2-42d7-86e1-70fccd6b1b66">

_Site_
<img width="1899" alt="Screenshot 2024-03-28 at 11 14 01 AM" src="https://github.com/Automattic/jetpack/assets/1620183/367c3984-e690-4bfd-8541-95bea1a401f4">

The text in the editor is `Privacy and Policy...`. The text on the site is `Privacy & Policy...`.

**Comment by jeherve** [comment]
I can't seem to be able to reproduce this:

**Editor**

<img width="1478" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/b2725534-8afa-450d-a318-8cd53d866f18">


**Frontend**

<img width="1440" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/0c100d87-5a8d-485d-ba4a-7c8395edc838">

Interestingly, the banner displayed on your second screenshot looks exactly like the old cookie consent banner displayed when using the Cookie & Consent Legacy widget. Could it be that you had activated that widget using classic widgets at some point?

**Comment by monsieur-z** [comment]
> Could it be that you had activated that widget using classic widgets at some point?

That's possible; I've noticed the issue on my usual test site, so I don't remember. With a brand new site, I don't see the issue either.
