### ISSUE TITLE
Blocks: attributes defined in `blocks.json` are not localized properly

### ISSUE THREAD

**Issue by monsieur-z** [Automattic/jetpack#36649]
### Impacted plugin

Jetpack

### Quick summary

Some Jetpack blocks (e.g., Donations, Jetpack AI Search) define their attributes in `block.json` directly. Strings defined in the `attributes` property are not localizable.

_The text_ Make a one-time donation _is defined in `block.json`_.
<img width="500" alt="Screenshot 2024-03-28 at 2 10 35 PM" src="https://github.com/Automattic/jetpack/assets/1620183/c14eb17f-94d8-4c63-9fc4-98534a2ed18f">

### Steps to reproduce

- Spin up a self-hosted Jetpack site and connect it to Jetpack
- Set the user language in another language than English
- Create a new post or page
- Add a Donations block
- Notice some texts are shown in English instead of the user language

### A clear and concise description of what you expected to happen.

All the texts should be in the user language.

### What actually happened

Some texts are not localized.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by simison** [comment]
Could we temporarily move attributes back to PHP for affected blocks, just temporarily? 

I'd prioritize this "high" as customer's localized sites have regressed as a result for multiple blocks.

**Comment by monsieur-z** [comment]
Sure thing @simison. Unless someone beats me to it, I'll try to submit a PR tomorrow.

**Comment by monsieur-z** [comment]
Referencing [the workaround for the Blocks subscription](https://github.com/Automattic/jetpack/pull/36695), for the record.
