### ISSUE TITLE
Cannot Delete uses from Multisite Network (via Network Admin)

### ISSUE THREAD

**Issue by trepmal** [Automattic/jetpack#36682]
### Impacted plugin

Jetpack

### Quick summary

Error received when deleting users via Network Admin.

### Steps to reproduce

0. Enable SSO module
1. In multisite, go to Network Admin
2. delete user

### A clear and concise description of what you expected to happen.

Should proceed to "confirm deletion" screen

### What actually happened

Nonce error. ("The link you followed has expired.")

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable.
(edit: probably should have selected "yes" as the SSO module could be disabled)

### Logs or notes

Jetpack checks for a `bulk-users` nonce [here](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/modules/sso/class.jetpack-sso-user-admin.php#L638). However, the [Network users page does not set a bulk-users nonce](https://github.com/WordPress/WordPress/blob/3fa06d8fbd127b16af6e031bd9d0848d3078ad1c/wp-admin/includes/class-wp-ms-users-list-table.php#L536)

In the non-network Users (for subsites or non-multisites) page, the link is made [here](https://github.com/WordPress/WordPress/blob/3fa06d8fbd127b16af6e031bd9d0848d3078ad1c/wp-admin/includes/class-wp-users-list-table.php#L487), which includes the `bulk-users` nonce.

WP-CLI deletion still works when that is available.

**Comment by kraftbj** [comment]
~@escapemanuele — would Vertex be able to get a quick fix in for this?~

p1712004416350259/1712004306.550689-slack-C02T4NVL4JJ

@agrullon95 will take a look at it.

**Comment by agrullon95** [comment]
Thanks for raising this issue @trepmal 
Can you provide a detailed set of instructions for reproducing this (a video works well too)?
I have set up WordPress Multisite, enabled Jetpack SSO, added a new user, then removed that user via `wp-admin/network`. I did not see the same error in this issue. 
Did I miss a step here?

**Comment by trepmal** [comment]
Your steps appear correct.
Here's a video demo on 2 completely separate sites https://wp.me/a9GBOq-72j

**Comment by jeherve** [comment]
@agrullon95 What do you think about completely disable the feature on multisite, since user management is very different on multisite? #36690 would do it.

**Comment by agrullon95** [comment]
>@agrullon95 What do you think about completely disable the feature on multisite, since user management is very different on multisite? https://github.com/Automattic/jetpack/pull/36690 would do it.

@jeherve - That makes sense to me. I didn't get a chance to look into this issue today since I was out, but I approved the PR you linked above.
