### ISSUE TITLE
My Jetpack: can't upgrade Jetpack AI from 100 to 200 requests

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#36698]
Steps to replicate:

- launch a fresh site
- upgrade from free to 100 requests, will work properly
- go to the Jetpack AI product page and click the "Get more requests" button, to start the upgrade to 200 requests
- on the pricing page, click upgrade

Expected result:

- land on the checkout page to buy the 200 requests plan

Actual result:

- redirected back to the Jetpack AI product page, stuck on the loop between product page and pricing page

**Comment by robertsreberski** [comment]
We do not offer tiered AI plans anymore.
