### ISSUE TITLE
Subscribers: /followers endpoint returns more subscribers than total count

### ISSUE THREAD

**Issue by staskus** [Automattic/jetpack#36696]
### Impacted plugin

Jetpack

### Quick summary

`/sites/221216735/stats/followers?type=wpcom` returns 11 `subscribers` although `total_wpcom` and `total` is 10. 

### Steps to reproduce

The issue comes from an older mobile report https://github.com/wordpress-mobile/WordPress-iOS/issues/21876 and p58i-fHk-p2 where an app shows less WordPress.com subscriber count than subscribers in the list. I checked that the app doesn't do any manipulations of the data and displays what is returned from the API. API indeed returns a different subscriber number than subscribers in the list:

1. Check `/sites/221216735/stats/followers?type=wpcom`
2. Notice there're more subscribers than total

I haven't noticed it on other sites, so it may be related to some specific configuration on this site.

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by jeherve** [comment]
This was a caching issue. After clearing cache, things match again:

<img width="605" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/42a6cab8-b34c-4cbe-9794-7f01a4f046fe">
