### ISSUE TITLE
Markdown: parse content inside shortcodes as well

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#367]
Markdown on Save improved used to parse content inside shortcodes, like so:

```
[one-half-first]
**This is bold**
[/one-half-first]
[one-half]
## This is a heading
[/one-half]
```

Jetpack's Markdown module, however, does not parse this content. It'd be nice if this could be changed.

Reported in 1783529-t

**Comment by duncandoo** [comment]
+1.

I've got jetpack markdown and shortcodes enabled. I can write posts in markdown, and can insert a \[presentation\] with \[slides\] successfully.

What I would like to do is to use markdown to write the contents of the slide, or whole presentation. This would correspond to [markdown](https://github.com/hakimel/reveal.js/#markdown) and [external markdown](https://github.com/hakimel/reveal.js/#external-markdown) in reveal.js.

**Comment by drkirmani** [comment]
+1 to markdown within shortcodes

**Comment by lpar** [comment]
+1. Just hit this limitation after defining a custom shortcode.

**Comment by samhotchkiss** [comment]
While I agree that this would be nice, it does present some technical hurdles that would take our development team away from our core focuses at the moment, and, as such, is not something that we see on our roadmap.  If this is crucial to your site, I would recommend investigating alternate solutions

**Comment by GaryJones** [comment]
While it may not be added to Jetpack itself, is there any pointers on how to go about adding this locally?

**Comment by jeherve** [comment]
@GaryJones `WPCom_GHF_Markdown_Parser `, used by Jetpack to transform your text, includes a `$preserve_shortcodes` class variable:
https://github.com/Automattic/jetpack/blob/master/_inc/lib/markdown/gfm.php#L25

I haven't run any tests, but you should be able to use that.

**Comment by lkraav** [comment]
> WPCom_GHF_Markdown_Parser, used by Jetpack to transform your text, includes a $preserve_shortcodes class variable:

Thank you, this works. Two things:

1. `public $preserve_shortcodes` class variable is misleading, because it gets blatantly overriden in the constructor by `function_exists( 'get_shortcode_regex' )

2. may we get a simple `apply_filters()` call for this value? That would enable knowledgeable people to get an enhanced workflow via an `mu-plugin` or whatnot for cheap.
