### ISSUE TITLE
Boost: Add a critical CSS troubleshooting support page

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#36714]
Add a support page for solving common critical CSS issues that cannot be solved automatically. This page can be referred to from critical CSS recommendations in case of errors instead of sending users to support directly.

Common issues based on analysis of support tickets pfhLfK-9c-p2#comment-109
- Explain that sometimes plugins add pages which aren’t meant to be available to all users. It's ok if critical CSS is not generated for them.
- If there is a 301/302 redirect removing the `jb-generate-critical-css`, sometimes plugins do so. We have added compatibility files to prevent Yoast, and AIO SEO removing the parameter. But, there may be more. In this case, it's important to figure out what's causing the redirect stop it from removing the parameter.
- Cloud CSS: A broken jetpack connection will prevent the site from receiving generated critical CSS.

There might be more common errors worth listing in the page.

**Comment by foleynotrose** [comment]
Howdy thanks for kicking this off! 

As a reminder, we have style guides for support documentation and screenshot creation: 

PeoG4N-4D-p2
PeoG4N-4l-p2

Please feel free to ping @jenhooks or @alinclamba if you need any help reviewing a draft.

**Comment by foleynotrose** [comment]
@haqadn just pinging for any updates on this. Do you want any help with getting a draft together?

**Comment by haqadn** [comment]
> @haqadn just pinging for any updates on this. Do you want any help with getting a draft together?

Yes, yes, yes!! Thank you so much for coming forward. @foleynotrose

**Comment by foleynotrose** [comment]
@alinclamba will you be able to collaborate with @haqadn to start this page about specific CCSS errors? this has been on my mind this week anyway because of playing into a handful of tickets recently that are just about a CCSS error, but not much more context or info. I would love to improve the self-help options for users who are encountering these types of errors.

**Comment by alinclamba** [comment]
@foleynotrose I'm already working on some materials for HEs and was also planning to create a user-faced support page as well. Yes, I'm happy to work on this.

**Comment by dilirity** [comment]
Support page is live - https://jetpack.com/support/jetpack-boost/troubleshooting-critical-css-issues/

Thanks for taking care of this @alinclamba
