### ISSUE TITLE
Notifications - unseen notes indicator does not appear on load.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/jetpack#36725]
### Impacted plugin

Jetpack

### Quick summary

When loading a site (front end or wp-admin), the unseen notifications indicator does not appear when unseen notifications are present.

### Steps to reproduce

1. Have an unseen notification. 
2. Load a jetpack site with notes module enabled.
3. Notice there is no unseen notifications indicator on loading the site front end.

NOTE - if you recieve a new notification after initial load, the indicator will still appear as expected. This just seems to be related to initial load.

### A clear and concise description of what you expected to happen.

The unseen notification indicator to be shown:

<img width="112" alt="Screenshot 2024-04-03 at 2 41 01 PM" src="https://github.com/Automattic/jetpack/assets/28742426/0372a096-7d58-4811-80bb-6545e922a6d3">

The notes count element is initialized it should have the `.wpn-unread` class as expected when in this state:

<img width="462" alt="Screenshot 2024-04-03 at 2 39 13 PM" src="https://github.com/Automattic/jetpack/assets/28742426/074af779-ebe1-46f6-81f0-149406249dfc">

### What actually happened

No unseen notes indicator is shown:

<img width="296" alt="Screenshot 2024-04-03 at 2 40 46 PM" src="https://github.com/Automattic/jetpack/assets/28742426/d3f8a989-2922-4727-96a8-d0844ff4dfdb">

Inspecting the dom we can see the count element is initialized with the `.wpn-read` class.

<img width="469" alt="Screenshot 2024-04-03 at 2 39 04 PM" src="https://github.com/Automattic/jetpack/assets/28742426/96d0c857-8237-4974-a368-0706cf9f0def">

### Impact

Uncertain. Everyone with notifications module enabled?

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

### Logs or notes

This works as expected on simple and p2, and only seems to have an issue on jetpack and atomic sites.

<s>Note that there seem to be other issues with stale js files for notes being served on jetpack and atomic here as well. I mentioned this in more depth here pe7F0s-1LH-p2</s> EDIT - this has since been resolved.

**Comment by ezebecke** [comment]
Another report on 8229524-zd

**Comment by suyogyashukla** [comment]
Another report in 8189860-zd

**Comment by taipeicoder** [comment]
@Addison-Stavlo was this fixed by https://github.com/Automattic/wp-calypso/pull/91308?

**Comment by Addison-Stavlo** [comment]
> was this fixed by https://github.com/Automattic/wp-calypso/pull/91308?

Unfortunately no, that was a separate issue within calypso's use of the notes panel component. Here I think is a separate issue with Jetpack's setup of using the full standalone notes app (iframed) version. The bug from this issue should be seen from a jetpack site's front end or wp-admin masterbar notifications.
