### ISSUE TITLE
Optimization: Unnecessary queries with get_option

### ISSUE THREAD

**Issue by kokers** [Automattic/jetpack#3676]
Jetpack is making unnecessary queries with each page refresh trying to get options that do not exist in database. All queries are triggered by get_option with this option_name and return 0 rows:

WHERE option_name = 'embed_autourls'
WHERE option_name = 'jetpack_sync_non_public_post_stati'
WHERE option_name = 'jetpack_sso_remove_login_form'
WHERE option_name = 'jetpack_testimonial'
WHERE option_name = 'jetpack_relatedposts'
WHERE option_name = 'gravatar_disable_hovercards'
WHERE option_name = 'sharedaddy_disable_resources'
WHERE option_name = 'safecss_revision_migrated'
WHERE option_name = 'safecss'

+ 1 SELECT to posts

SELECT c5gh4s_posts.ID
FROM c5gh4s_posts 
WHERE 1=1 
AND c5gh4s_posts.post_type = 'safecss'
AND ((c5gh4s_posts.post_status = 'publish')) 
ORDER BY c5gh4s_posts.post_date DESC
LIMIT 0, 1

Some of those queries, won't be triggered if related module will be disabled/enabled. For example if I disable "related posts" the query "WHERE option_name = 'jetpack_relatedposts'" won't be called. Re-enabling "Related posts" will make this query to show up again. If this option is needed on each page, I think it should be added to database and autoloaded.

Topic first started here: https://wordpress.org/support/topic/fewer-queries-with-each-page-refresh?replies=2

**Comment by gravityrail** [comment]
This has been at least partially addressed in #4281, so I think we can close it for now.

The safecss query wasn't yet optimised away, but I couldn't find a straightforward and reliable way to do that yet.
