### ISSUE TITLE
Meta / Facebook Sharing Cards not picking up Featured Images

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/jetpack#36777]
### Impacted plugin

Jetpack, Social

### Quick summary

When posts on simple sites are shared to Facebook, either no image appears or the first image within the post is used rather than the featured image. However, the problem is inconsistent. 

The case which prompted this report is p2EDhh-2bL-p2

In that case, we tested the site with Facebook debugger as no image was appearing. We then re-scraped it and this time the first image in the post appeared instead of the featured image. 

A warning appeared saying 
```
Invalid Image Content Type
Provided og:image URL, [URL]?w=1200 could not be processed as an image because it has an invalid content type.

```
The content type seems to be .jpg. Could the ?w=1200 be doing something to interfere with the ability to pick up the featured image?

The featured image was re-uploaded but this didn’t change anything. 

There have been a number of reports in the past few days. 

# Additional conversation around the issue #
p1712216112369169-slack-C02AVAR9B
p1712343794015979-slack-C02FMH4G8
pd4QKa-Wk-p2

### Steps to reproduce

1. Publish a post on a simple site with a featured image and another image at the top of the post
2. Go to Facebook debugger and scrape the URL for the post.
However, replicating the error is inconsistent.

### A clear and concise description of what you expected to happen.

The correct featured image to show up reliably in the Facebook scraper. 

### What actually happened

No image appears at first, then the first image in the post appears.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Additional reports.

7965743-zen
7983729-zen
7983549-zen
7971042-zen
7989722-zen
7970699-zen
7991524-zen
7939510-zen
7976967-zen
7994716-zen
7995053-zen
8000795-zen
8007559-zen
8005419-zen
8008137-zen
8008243-zen
8007559-zen

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##

The reports suggest this is related to Simple sites only

- In new testing, we were unable to replicate it but due to the number of reports we've left this open.

**Comment by jeherve** [comment]
cc @devicenull who recently worked on some changes to image management on the WordPress.com platform.

**Comment by jorpdesigns** [comment]
Reported in 7975209-zen. Issue also occurs on LinkedIn and X.

**Comment by mariammcWP** [comment]
8008324-zen

**Comment by AnjanaV93** [comment]
Another report here: 8008522-zen (Issue occurs on LinkedIn)

**Comment by brinbliss** [comment]
Another report from 7976691-zen, happens on Twitter, Bluesky, and Threads specifically.

**Comment by anthcodes** [comment]
8009738-zen

**Comment by cat-og** [comment]
7991672-zd-a8c

**Comment by jorpdesigns** [comment]
Reported in 8014264-zen (simple site). Issue also occurs on X.

**Comment by pauljacobson** [comment]
The merged issue above is for 8015896-zen . There are screenshots of what I observed in that issue too.

**Comment by daria2303** [comment]
8014933-zd-a8c

**Comment by ebinnion** [comment]
I did some more debugging and published a systems request here: pMz3w-jH1-p2

**Comment by mgozdis** [comment]
8017567-zd-a8c

**Comment by desnum** [comment]
8010163-zen

**Comment by chekle** [comment]
7964985-zd-a8c

**Comment by AnjanaV93** [comment]
8005932-zen

**Comment by AnjanaV93** [comment]
8007658- zen

**Comment by druesome** [comment]
8016586-zen

**Comment by jerren1327** [comment]
8019378-zen

**Comment by philnick206** [comment]
8021790-zd-a8c

**Comment by tvolpert** [comment]
8023237-zen

**Comment by Aurorum** [comment]
7966168-zen

**Comment by Aurorum** [comment]
7991672-zen

**Comment by Aurorum** [comment]
8021531-zen

**Comment by ebinnion** [comment]
See systems request. This should be addressed.

**Comment by mgozdis** [comment]
8023150-zd-a8c

**Comment by jerren1327** [comment]
8020987-zen
8022430-zen

**Comment by Aurorum** [comment]
I’ve asked a couple users to confirm, and they’re also stating that this should be resolved now, so I expect any new reports such as the ones above might be outdated and that it’s worth letting them know that they can try again.

Thanks @ebinnion!

**Comment by Neha93517** [comment]
8002641 - Zen
The user reached out on Saturday, and asked for an update today

**Comment by AnjanaV93** [comment]
8018020-zen

**Comment by AlexanderSky** [comment]
8018180-zen

**Comment by ezebecke** [comment]
7940923-zen

**Comment by rickmgithub** [comment]
7968615-zd-a8c

**Comment by daria2303** [comment]
7989605-zd-a8c

@jeherve could you please let us know if this is already shipped to production and the issue should not be present anymore? If so, I can still see it on http://efrainmartinezfigueroa.com, seems there are more reports above. Should it be reopened? 
Are we going to send a mass notification to the users?

**Comment by jeherve** [comment]
@daria2303 The problem should be addressed as of this comment:
https://github.com/Automattic/jetpack/issues/36777#issuecomment-2045723726

If you still experience issues, I would recommend posting on the p2 listed there to report the issue you found.

> Are we going to send a mass notification to the users?

I believe that's something the WordPress.com Product ambassadors typically do, yeah. I'd encourage you to reach out to them to coordinate things.

Edit: additional context: p1713188322781979-slack-C03TY6J1A

**Comment by daria2303** [comment]
@jeherve the issue was closed without any message, could you please explain what is the resolution directly? 

The comment doesn't say much and the link gives me only 404. 

Regarding posting to the p2 please bear in mind that we also have many HCs handling the tickets and they don't have access to most of the p2s. We would appreciate at least a short info on what the status is.

**Comment by daria2303** [comment]
> This was corrected, and is working properly again.

**Comment by rickmgithub** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-pa-group have finished following up with affected users reported in this thread.

Thanks for all the reports!

**Comment by OgeAmadi** [comment]
I observed a new case today on LinkedIn
8052233-zen

**Comment by devicenull** [comment]
@OgeAmadi I don't think that's related - that user has hidden their blog from search engines, which indirectly blocks linkedin from generating previews - you can test with https://www.linkedin.com/post-inspector/

**Comment by OgeAmadi** [comment]
Okay...thanks for pointing this out...I'll send a follow-up message to the user explaining this.

**Comment by inaikem** [comment]
@rickmgithub, to confirm, how many users did we reply to in total? The checklist shows 43.

**Comment by rickmgithub** [comment]
@inaikem  I ticked each person I checked. Some didn't require a response as they had already been told.

**Comment by inaikem** [comment]
Thanks @rickmgithub! Please ignore my Slack ping, let's keep the thread here. I've been altered to two related issues:

https://github.com/Automattic/wp-calypso/issues/89271
https://github.com/Automattic/wp-calypso/issues/89207

Can you please use your next direct support slot to check the interaction IDs and sent updates to any that were not on the bulk reply?

**Comment by OgeAmadi** [comment]
I ran into another case here:
8056410-zen 
I just put it on hold for now...it's an X issue....can someone please take a look? I would like to know if the issue is still recurring or if it's something with the user's site.

**Comment by devicenull** [comment]
Are you able to reproduce it at all?  I can't seem to find any failures in the last 24h there (but twitter makes it difficult because it's all paywalled these days)

**Comment by mariammcWP** [comment]
> Are you able to reproduce it at all? I can't seem to find any failures in the last 24h there (but twitter makes it difficult because it's all paywalled these days)

It works for me: [https://prnt.sc/GHL8fPAWPO8R](https://prnt.sc/GHL8fPAWPO8R)
This is the same post they shared.

**Comment by devicenull** [comment]
I've now concluded the work that's been going on here, so this should be working fine.  Please reopen this if it's still broken.
