### ISSUE TITLE
Jetpack masterbar causes fatal when submenu items return false

### ISSUE THREAD

**Issue by hideandgeek404** [Automattic/jetpack#36780]
### Impacted plugin

Jetpack

### Quick summary

An example of this is outlined in p9F6qB-eMr-p2 where installing the `Ditty News Ticker` plugin on a site with PHP 8.0 active caused a fatal error 

```
[08-Apr-2024 11:51:44 UTC] PHP Fatal error:  Uncaught TypeError: array_values(): Argument #1 ($array) must be of type array, bool given in /wordpress/plugins/jetpack/13.3-beta/modules/masterbar/admin-menu/class-base-admin-menu.php:514
```

This refers to the `hide_parent_of_hidden_submenus()` function in the Jetpack masterbar. 

### Steps to reproduce

1. Have a site with the latest Jetpack installed, running PHP 8+
2. Install the `ditty-news-ticker` plugin
3. Fatal should occur

### A clear and concise description of what you expected to happen.

The site should load and the menus and submenus should appear

### What actually happened

Fatal error shown below appears

```
[08-Apr-2024 11:51:44 UTC] PHP Fatal error:  Uncaught TypeError: array_values(): Argument #1 ($array) must be of type array, bool given in /wordpress/plugins/jetpack/13.3-beta/modules/masterbar/admin-menu/class-base-admin-menu.php:514
Stack trace:
#0 /wordpress/plugins/jetpack/13.3-beta/modules/masterbar/admin-menu/class-base-admin-menu.php(514): array_values(false)
#1 /wordpress/core/6.5/wp-includes/class-wp-hook.php(324): Automattic\Jetpack\Dashboard_Customizations\Base_Admin_Menu->hide_parent_of_hidden_submenus('')
#2 /wordpress/core/6.5/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /wordpress/core/6.5/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /wordpress/core/6.5/wp-admin/includes/menu.php(161): do_action('admin_menu', '')
#5 /wordpress/core/6.5/wp-admin/menu.php(422): require_once('/wordpress/core...')
#6 /wordpress/plugins/jetpack/13.3-beta/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php(95): require_once('/wordpress/core...')
#7 /wordpress/core/6.5/wp-includes/rest-api/class-wp-rest-server.php(1230): WPCOM_REST_API_V2_Endpoint_Admin_Menu->get_item(Object(WP_REST_Request))
#8 /wordpress/core/6.5/wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wpcom/v2/admin...', Array, NULL)
#9 /wordpress/core/6.5/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch(Object(WP_REST_Request))
#10 /wordpress/core/6.5/wp-includes/rest-api.php(428): WP_REST_Server->serve_request('/wpcom/v2/admin...')
#11 /wordpress/core/6.5/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#12 /wordpress/core/6.5/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#13 /wordpress/core/6.5/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#14 /wordpress/core/6.5/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#15 /wordpress/core/6.5/wp-includes/class-wp.php(813): WP->parse_request('')
#16 /wordpress/core/6.5/wp-includes/functions.php(1336): WP->main('')
#17 /wordpress/core/6.5/wp-blog-header.php(16): wp()
#18 /wordpress/core/6.5/index.php(17): require('/wordpress/core...')
#19 {main}
  thrown in /wordpress/plugins/jetpack/13.3-beta/modules/masterbar/admin-menu/class-base-admin-menu.php on line 514
```

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

**Comment by anomiex** [comment]
As far as what's happening here, what seems to be going on is this:

* On initial install, Ditty's capabilities are not set up yet. At a quick grep, it seems that Ditty will add them in the 'admin_init' hook, but 'admin_menu' runs first.
* The 'admin_menu' hook runs to try to add all the menus, but since the user lacks the capabilities to see these pages Core's `add_submenu_page()` exits early without adding them.
* Then Ditty's [`ditty_dashboard_custom_menu_classes`](https://plugins.trac.wordpress.org/browser/ditty-news-ticker/tags/3.1.34/includes/hooks.php#L210) runs on 'admin_menu' priority 99. With none of its submenus having been successfully added, this incorrectly winds up setting `false` into the `$submenu` global.
