### ISSUE TITLE
Top Posts Widget: allow non-square image sizes

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3682]
As explained in [this tutorial](https://jetpack.com/2013/08/20/custom-thumbnails-top-posts-widget/), the `jetpack_top_posts_widget_image_options` filter allows one to change the size of the image used in the Top Posts widget.

Unfortunately, `$get_image_options['avatar_size']` only accepts a single integer, and a square image is built from that value.

It would be nice if one could define an array of image width and image height instead, so the Top Posts images could be rectangular.

Suggested here:
https://wordpress.org/support/topic/chnage-size-of-post-thumbnails-jetpack-popular-post-widget?replies=1&view=all

**Comment by jb510** [comment]
Related: The image sizing option here: https://jetpack.com/2013/08/20/custom-thumbnails-top-posts-widget/ seems to only apply to the grid layout ('grid'), not the image list ('list') view.  I swear I forked this widget 6 months ago to overcome that...  but frankly this widget is such a mess I'd recommend starting from scratch.

**Comment by jeherve** [comment]
@jb510 As per our Slack chat, the CSS on that post was indeed outdated. I've updated it; thanks for the warning and for the help!

**Comment by lamdayap** [comment]
2886292-t
