### ISSUE TITLE
Plugin configuration: missing redirect on activation

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#36844]
A lot of our plugins rely on the `activated_plugin` hook to redirect the site owner to a configuration screen upon activation. Unfortunately, that is no longer an option starting in WordPress 6.5. We may have to adjust our flows accordingly, if that core change is not adjusted.

Related Core ticket:

https://core.trac.wordpress.org/ticket/60992

*****

Internal report:

- p1HpG7-rYC-p2#comment-71125

**Comment by cat-og** [comment]
I tested this on my sites; version 6.5.2. I wasn't able to replicate the issue, can you provide an example of some of the plugins affected?

**Comment by jeherve** [comment]
@cat-og Yes, see the labels added to this issue. You can also see the video in the internal reference attached for an example.

**Comment by jeherve** [comment]
A workaround was implemented and released with WordPress 6.5.3.

**Comment by jeherve** [comment]
Reopening this, since we'll need to make changes following the new filter that may be introduced here:
https://core.trac.wordpress.org/ticket/61269

**Comment by jeherve** [comment]
Closing this for now since the new filter is not happening yet, and the redirect was reverted in WordPress 6.5.4.

Any upcoming changes to plugin onboarding (tracked [here](https://core.trac.wordpress.org/ticket/61040)) can be discussed in another issue.
