### ISSUE TITLE
JITMs: don't show backup message if VaultPress is running

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#3685]
Whether VaultPress has been activated as a regular plugin or a mu-plugin, catch all cases and don't show it.
Maybe it's better to check if the `VaultPress` class is available and even then, call the method `$vaultpress->contact_service( 'plugin_data' )`.

Note: JITMs are being disabled starting in version 4.0. This issue will be addressed when they are enabled back in a future version.

**Comment by jeherve** [comment]
I believe this has now been fixed.
