### ISSUE TITLE
Tiled Gallery: Rounded corners setting doesn't work

### ISSUE THREAD

**Issue by vinnykaur** [Automattic/jetpack#36938]
### Impacted plugin

Jetpack

### Quick summary

The Rounded Corners settings in the tiled gallery block doesn't work.

### Steps to reproduce

1. Add a tiled gallery block to a new post.
2. Adjust the rounded corners settings in the tiled gallery block settings.
3. Save the changes and preview the post.

### A clear and concise description of what you expected to happen.

The edges of the images should have rounded corners.

### What actually happened

It did not make the images' corners round.

https://github.com/Automattic/jetpack/assets/49183855/5cc96335-6f27-4f2b-8921-2af3e1fb17ec

### Impact

One

### Available workarounds?

Yes, easy to implement

I gave the below CSS to the user as a workaround:

```
tiled-gallery__gallery img {
    border-radius: 20px;
}
```

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by vinnykaur** [comment]
Reported here: 8055730-zd-a8c

**Comment by jeherve** [comment]
@monsieur-z Looks like the added level in #36854 breaks the CSS. Do you think you could take a look?

Thank you!

**Comment by monsieur-z** [comment]
Thanks for catching this! Apologies, I must have made a late change and forgot to check that setting again.

**Comment by chekle** [comment]
Reported here: 8058612-zd-a8c - I applied the CSS workaround, thank you!
