### ISSUE TITLE
VideoPress: embedding videos on own Wordpress without iframe?

### ISSUE THREAD

**Issue by bluepuma77** [Automattic/jetpack#3693]
We have a publisher that users VideoPress with JetPack on a self-hosted WordPress installation. We found that the VideoPress video is embedded using an iframe. This prohibits us to access the video object and get the video's currentTime. Is it possible to embed VideoPress videos without iframe?

**Comment by jeherve** [comment]
When embedding VideoPress videos on a Jetpack site, you can either use the oEmbed link on a separate line in the editor, or use the `wpvideo` or `videopress` shortcodes.

You can control things like the starting time with shortcode parameters, as referenced here:
https://github.com/Automattic/jetpack/blob/3.9.6/modules/videopress/shortcode.php#L41

Both methods output an iFrame, though.If you'd rather not use the iFrame, you can get a direct link to the video file by clicking on the Share button in the player. You can then use your own local player, where you'll be able to customize everything.

I hope this helps.
