### ISSUE TITLE
Newsletter Settings: Add "Paid Newsletters"

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/jetpack#36958]
## Design

![Image](https://github.com/Automattic/jetpack/assets/25607244/61d6c72f-180a-44f2-b731-f9d1ef0a57f8)

Figma file: 0M7MyVuvpKh77jgYX6O6R9-fi-4384_3171

- The `Set up` button should open https://cloud.jetpack.com/monetize/payments/{site}
- It should be disabled if the main toggle for Subscriptions isn't enabled

We should have a **Tracks** so we can monitor the usage and create a _Tracks Funnel_ that allows us to:
1. People who access Settings > Newsletters
2. How many people click the `Set up`
3. How many access Cloud > Monetize and create and save a plan

**Comment by pkuliga** [comment]
Closing it since all the work has been done.

Funnel is here: PeKye1-3e-p2

Thanks @crisbusquets for creating it!
