### ISSUE TITLE
Slideshow block: Autoplay not working on the front-end

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/jetpack#36973]
### Impacted plugin

Jetpack

### Quick summary

On WordPress.com SImple sites, the Autoplay setting of the Slideshow isn't applying.
It works in the Editor, but not on the live page.
The pause button is also missing.

### Steps to reproduce

1. On a Simple site, add a Slideshow block to a page or template
2. Set it to Autoplay
3. Notice how the setting applies in the Editor but not the live pages.

### A clear and concise description of what you expected to happen.

The Slideshow to autoplay with a pause button on the live site as it does in the Editor

Slideshow in the Editor:

https://github.com/Automattic/jetpack/assets/2540430/c934fdd8-1e88-471a-a7e2-f8c1a144a5ff

### What actually happened

The Slideshow does not autoplay and the pause button is missing.

Slideshow in the live site:

https://github.com/Automattic/jetpack/assets/2540430/f37d1b41-5ad4-4083-8379-cf65823d677d

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Reported in 8060882-zd-a8c

**Comment by Aurorum** [comment]
8057525-zen
8054016-zen
8058429-zen 

(From Automattic/wp-calypso#89654)

**Comment by bobmatyas** [comment]
This does not affect self-hosted sites.

EDIT from @foleynotrose: 

Looks like it does, @bobmatyas : https://github.com/Automattic/jetpack/issues/36973#issuecomment-2107455375

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple – Replicated 
- Tested on Atomic – Could Not Replicate

## 📌 FINDINGS/SCREENSHOTS/VIDEO ##
I also see that the images in the Slideshow block seem to move with the mouse, even when the mouse is not over the block itself.

Note simple sites. Couldn't replicate on quick test on Atomic. However, I could replicate the editor issue where the images in the block appear stuck to the mouse on both Atomic and simple.

https://github.com/Automattic/jetpack/assets/13706336/a22955df-dc0b-448a-bb20-628600ac8655


## 📌 ACTIONS ##
Triaged

**Comment by mosesmedh** [comment]
Another report is here: 8066235-zen

**Comment by mariammcWP** [comment]
User from 8066235-zen shared this: 

![image0](https://github.com/Automattic/jetpack/assets/152675349/e83a1abd-7441-4f47-80fd-f7280cfbc13f)

**Comment by rickmgithub** [comment]
8079755-zen

**Comment by rajwpdev117** [comment]
8080367-zen

**Comment by rinazrina** [comment]
Another report: 8082999-zd-a8c 

Spiel theme.

**Comment by jromales** [comment]
8058141-zd-a8c

**Comment by kriskarkoski** [comment]
8091261-zd-a8c

**Comment by kriskarkoski** [comment]
8092132-zd-a8c

**Comment by Mfarroq1** [comment]
8098206-zen

**Comment by RafaelFunchal** [comment]
pt-BR forum topic: https://wordpress.com/pt-br/forums/topic/problema-no-slideshow/

**Comment by supernovia** [comment]
I have another case here.
8105089-zd-a8c

Noting a console error in Safari in case it's related:
`Failed to load resource: https://s0.wp.com/wp-content/plugins/gutenberg-core/v18.1.2/build/escape-html/index.min.js.map the server responded with a status of 404 ()`

**Comment by nazilya06** [comment]
8124207-zd-a8c

**Comment by the-misha** [comment]
8126021-zd-a8c

User requests follow-up: 8126178-zd-a8c

**Comment by supernovia** [comment]
Another case: 8100341-zd-a8c

**Comment by supernovia** [comment]
Another
8092550-zd-a8c

**Comment by sanjeev00733** [comment]
Another report in 8126178-zd-a8c

**Comment by davipontesblog** [comment]
8153035-zen

**Comment by davipontesblog** [comment]
8153370-zen

**Comment by ezebecke** [comment]
8153499-zen

**Comment by Greatdane** [comment]
8154751-zd-a8c

**Comment by jorpdesigns** [comment]
8156652-zen

**Comment by lizswafford** [comment]
8160005-zd-a8c (Works in site editor, not live site. AT)

**Comment by rajwpdev117** [comment]
8143128-zd-a8c (Works in site editor, not live site. AT).

**Comment by saginpj** [comment]
- [ ] 8160243-zen
- [ ] 8171845-zen

**Comment by wiesenhauss** [comment]
8165547-zen

**Comment by mosesmedh** [comment]
8143631-zen

**Comment by rajwpdev117** [comment]
8172079-zen

**Comment by cselamor** [comment]
8180552-zen

**Comment by cat-og** [comment]
- 8141888-zd-a8c (Atomic site)
- 8143290-zd-a8c (Atomic site)

**Comment by mosesmedh** [comment]
8181037-zen

**Comment by rinazrina** [comment]
8181466-zd-a8c

**Comment by nazilya06** [comment]
8182689-zd-a8c

**Comment by coder-karen** [comment]
Adding here that I am able to replicate the autoplay issue on the front-end on a local development site, a Jurassic Ninja site (both self hosted), a WoA development site, and simple test site. I've tracked the issue back to this PR where the API version was updated to V3: https://github.com/Automattic/jetpack/pull/36858

**Comment by jp-imagines** [comment]
Another report in 8166879-zd-a8c (Simple site).

**Comment by sanjeev00733** [comment]
Another report in 8064030-zd-a8c

**Comment by mxhassani** [comment]
8187945-zen

**Comment by Jaccuse** [comment]
8189601-zen

**Comment by AminMehrani** [comment]
8154432-Zen

**Comment by masifdev** [comment]
8154432-Zen (Atomic site)

**Comment by chekle** [comment]
8195557-zd-a8c

**Comment by silvio-meter** [comment]
8196210-zen (simple site)

**Comment by foleynotrose** [comment]
8172304-zd-a8c (self-hosted Jetpack site)

**Comment by ahmadbaig1** [comment]
8196872-zd-a8c

**Comment by coder-karen** [comment]
This issue (autoplay not working) is now resolved on Simple sites. For the changes to show on the front-end, with any block changes like this people will need to re-save the affected posts / pages (that might mean toggling a setting and changing it back again just to make the save button clickable). Then the pages / posts on the front-end will pick up the change and autoplay should now work.

I'll add another update once AT sites are also updated. Jetpack self-hosted will be in the next Jetpack release.

**Comment by coder-karen** [comment]
The fix will now also be live on AT sites .

**Comment by rw-ye** [comment]
Hey @coder-karen  👋 

On my AT site, I added a new page and slideshow block with Autoplay enabled, however, the autoplay is currently not working on the front end.

A user also reported the same issue in 8226682-zd-a8c

**Comment by coder-karen** [comment]
@rw-ye thanks for the report. 

It looks like the recent Atomic release was reverted for a separate reason (internal ref p9o2xV-4fO-p2#comment-9350), so I'll close this again and leave another comment once the next release is out.

**Comment by coder-karen** [comment]
As I'll be unable to follow up next week when the next Atomic release will now go out, for anyone looking for updates I'd suggest following posts with the tag 'jetpack-weekly-atomic-releases' on this (internal) P2 - 9o2xV-p2

Edit to add - the release went out on the 27th May.

**Comment by airdrummer** [comment]
same issue on bostoncamerata.org, toggling pause/play kicks it off

**Comment by airdrummer** [comment]
fixed by adding this to end of footer.php right before < / body >

```
<script> <!-- unstick scroller -->
window.onload = function () 
{
  let slideshowActivated = false;

  const waitForSlideshow = () => 
  {
    const slideshow = document.querySelector(".wp-block-jetpack-slideshow");
    const toggleButton = document.querySelector(".wp-block-jetpack-slideshow_button-pause");

    if (!slideshowActivated 
        && slideshow && toggleButton
      	&& slideshow.offsetHeight > 0 
      	&& slideshow.offsetWidth > 0 ) 
    {
        toggleButton.click();
        toggleButton.click();
        slideshowActivated = true;
    }
    else if (!slideshowActivated) 
    {
        setTimeout(waitForSlideshow, 200);
    }
  };
  waitForSlideshow();
};
</script>
```
edit: changed to window.onload & wait for s.s. loaded...boost defer & concatenate js also cause problems.
