### ISSUE TITLE
Connect: Links in banner are underlined

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#3709]
#### What I expected
Within the connection banner, the links are underlined, which looks weird, especially since one of them is a button. I expected them not to have underlines.

#### What happened instead
<img width="510" alt="screen shot 2016-04-21 at 2 38 26 pm" src="https://cloud.githubusercontent.com/assets/108942/14723541/d24b1000-07ce-11e6-9e4d-b5d36ea8b20c.png">

#### Steps to reproduce the issue
I'm seeing it in Chrome on OSX, and the underline appears to be a default browser style. Might just need to define `text-decoration: none;` explicitly here.

**Comment by jeffgolenski** [comment]
Thanks for reporting! These will be completely redone for 4.1 (working on them right now actually!) , so I'm closing this!
