### ISSUE TITLE
Boost: Update Image CDN configuration UI

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#37171]
A better UI is proposed for Image CDN configuration: pc9hqz-2R5-p2

This will Improve consistency and clarity.

**Comment by dilirity** [comment]
Oops, I missed that there's already a ticket for this. This is the one I created instead - https://github.com/Automattic/jetpack/issues/37262

There are a few differences between the design and what was implemented. For example, the icons for collapse/expand are different. I kept those the same, to have a consistency between the existing collapse/expand sections in the UI.

**Comment by haqadn** [comment]
Closing as this is already implemented.
