### ISSUE TITLE
Tiled Gallery block does not respect the `Circle` setting on live pages

### ISSUE THREAD

**Issue by ClassicRKR27** [Automattic/jetpack#37194]
### Impacted plugin

Jetpack

### Quick summary

Initially reported here: 8138345-zd-a8c

The user has set the `Tiled Gallery` block to display as `Circles` in the block styles as shown here: ![t5tX3V.png](https://github.com/Automattic/jetpack/assets/51870544/7895af9b-33f7-4d6a-b35c-5c63eccd6d3a)

But when viewing the live page, they still show as squares/rectangles: ![3Njc0Y.png](https://github.com/Automattic/jetpack/assets/51870544/6d297f3a-51d3-4d22-a459-e4255f26ab4d)

I have not been able to find a workaround - tested on two of my own sites (Simple & AT) and could replicate on both, so the plan/themes don't seem to be a contributor.

### Steps to reproduce

1. Add a `Tiled Gallery` block to any page/post
2. Set the `Styles` for the block to `Circles`

### A clear and concise description of what you expected to happen.

The images should get cropped to be circles.

### What actually happened

The images are still showing as squares.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by jeherve** [comment]
@monsieur-z Do you think you could take a look? I suspect this was caused by #36854.
Thank you!

**Comment by chatoxz-wp** [comment]
@jeherve @monsieur-z Thanks for working on this; an affected user is asking when the fix will be released. Do we have a date or a version in which this will be included? 8170498-zd-a8c

**Comment by jeherve** [comment]
@chatoxz-wp We're planning on releasing a new version of the Jetpack plugin early next week, if all testing goes well. The fix will be included in that release.

**Comment by supernovia** [comment]
@jeherve  is there any possibility the same underlying bug is affecting tiled galleries? Last week I spotted a user whose old circle-galleries worked fine until they were edited. Today I've got a user whose tiled galleries are fine until they edit them, then their borders get messed up with uneven spacing.  It sounded like it could be related... any thoughts?
8069210-zd-a8c
![Screenshot 2024-05-13 at 4 40 54 PM](https://github.com/Automattic/jetpack/assets/3476361/b68bc2a5-2cc1-4d01-a60d-f11d16315e5f)

**Comment by jeherve** [comment]
@supernovia I suspect it is a different issue. The post in this example seems odd: it uses the HTML block, and `image-big` span tags are added for each image. I wonder how the post was created in the first place. Maybe via a third-party tool, or maybe a mobile app? It would be interesting to find out. 

I wasn't able to reproduce the issue on a simple site; were you?
