### ISSUE TITLE
Development mode notice mixed in with disconnect notice

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#3720]
After I disconnected one of my sites today, I noticed this:

<img width="875" alt="screen shot 2016-04-22 at 3 42 14 pm" src="https://cloud.githubusercontent.com/assets/1126811/14754528/9ac6bd22-08a1-11e6-8921-09739907aa71.png">

After highlight the white area, here's the text:

<img width="866" alt="screen shot 2016-04-22 at 3 42 23 pm" src="https://cloud.githubusercontent.com/assets/1126811/14754533/a2c4dbe4-08a1-11e6-903c-a75d7d41a8fa.png">

#### What I expected

The development mode notice to be below the disconnect notice, or to at least be able to read the text in the development notice.

#### Steps to reproduce the issue

On a site where you have the `master` branch, disconnect.

**Comment by dereksmart** [comment]
should be fixed by #3663

(originally reported in #3045, but thanks @ebinnion!)

**Comment by ebinnion** [comment]
I promise I searched before posting. 😅
