### ISSUE TITLE
Make the sharing buttons that show up on posts/pages an FSE block

### ISSUE THREAD

**Issue by arinoch** [Automattic/jetpack#37229]
### Impacted plugin

Jetpack

### What

Separate the sharing buttons from the content of a post/page, and make them able to be relocated, by making them an FSE block. This should allow users the ability to place them anywhere on their page, as attempted by a user in 7875379-ZD

**Comment by jeherve** [comment]
This is already a block that's available today, you should be able to use that:
https://wordpress.com/support/wordpress-editor/blocks/sharing-buttons-block/
