### ISSUE TITLE
Boost: Make it possible to switch between WPSC and Boost Cache without disabling them

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#37227]
Both plugins use wp-content/advanced-cache.php, and add WP_CACHE to wp-config.php to load their caching systems.

Both plugins already recognise the advanced-cache.php file created by the other, but they show a warning, and the site owner must disable the plugin entirely from the Plugins page to remove the advanced-cache.php file.

The plugins should remove the advanced-cache.php file generated by the other plugin. If the Cache module for Boost is enabled, show a warning in WP Super Cache if the site owner tries to enable caching. Confirming that dialog will enable caching.

If WP Super Cache is enabled, and it has the basic features that Boost supports, allow the site owner to enable the Cache module without interruption.

**Comment by donnchawp** [comment]
Fixed by the PRs above.
