### ISSUE TITLE
WordPress MU blogs can't be managed from wordpress.com any more

### ISSUE THREAD

**Issue by mqudsi** [Automattic/jetpack#3723]
For a while now, I've been unable to manage any of my WPMU self-hosted blogs via WordPress.com

The xmlrpc interface works fine (tested with an external utility), but WordPress.com always says to check my JetPack installation when attempting to manage posts or comments. The stats module works fine on WordPress.com for these same sites.

Installation is WordPress 4.5, JetPack is 4.0.2 and JetPack master. This same configuration used to work (but a while back).

**Comment by jeherve** [comment]
I can't seem to reproduce on my end.

Can you please use Jetpack's Debugger module to send us some more information about one of the sites in the network?

1) Go to the Jetpack page in your dashboard.
2) Click on the Debug link appearing at the bottom of the page.
3) Click the link that says "click here to contact Jetpack support."
4) Fill in the description box and your name and email address.
5) Click the "Contact Support" button.

Thanks!
