### ISSUE TITLE
Position of the line is deviated for Twenty Sixteen

### ISSUE THREAD

**Issue by gouten5010** [Automattic/jetpack#3724]
Oh! I forgot to make issue.

![share-button-area](https://cloud.githubusercontent.com/assets/3461188/14762537/b79a35ac-09b7-11e6-9ed9-743fcad5aebb.png)

* Select the official share button in the Sharing.
* if you have activated the  Twenty Sixteen.
* Displayed in one column in Firefox.

Position of the line after official share button is deviated.

Already they send a pull request, please make sure it.

Already I have sent a pull request #3722
Please check it.

**Comment by jeherve** [comment]
Fixed in #4292
