### ISSUE TITLE
Jetpack widgets errors on 

### ISSUE THREAD

**Issue by pixedelic** [Automattic/jetpack#3725]
Since the recent updates I have two js errors in the customizer related with the widgets:
customizer-utils.js:11 Uncaught ReferenceError: wp is not defined
contact-info-map.js:34 Uncaught TypeError: wp.customizerHasPartialWidgetRefresh is not a function

I'm sure they also depend on some customization I made on my part, but I'd be glad to understand why they happened suddenly and if you have a clue to fix that.

TIA, Manuel :-)

**Comment by pixedelic** [comment]
@eliorivero maybe you're the best person here to provide this kind of help. Thank you in advance.

**Comment by jeherve** [comment]
Closing as duplicate of #3716

**Comment by eliorivero** [comment]
Hi @pixedelic please see https://github.com/Automattic/jetpack/issues/3716#issuecomment-213632186 for a solution. We'll include this in the next Jetpack version.

**Comment by pixedelic** [comment]
Thank you!

**Comment by pixedelic** [comment]
Sorry, hasn't been the fix released yet?

**Comment by jeherve** [comment]
@pixedelic Not yet. It will be part of the next release.
