### ISSUE TITLE
Boost: Update pricing table to mention LIAR

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#37279]
There are a few other places we should update as well.

I'm not sure what those are however.

We need a list.

**Comment by alinclamba** [comment]
Hope this helps: pc9hqz-2Xr-p2#comment-2173

**Comment by dilirity** [comment]
Pricing page was updated in 3.4.2 which shipped today.

**Comment by dilirity** [comment]
Closing this as it was done in 3.4.2.
