### ISSUE TITLE
Custom CSS: problem stripping / replacing quotes

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3727]
Steps to reproduce the issue:

1. Add the following CSS to the custom CSS editor:
```css
@import url("fineprint.css") print;
@import url("bluish.css") projection, tv;
@import 'custom.css';
@import url("chrome://communicator/skin/");
@import "common.css" screen, projection;
@import url('landscape.css') screen and (orientation:landscape);
```

2. Save your changes.
3. The following is saved in the editor:

```css
@import  '"fineprint.css' print;
@import  '"bluish.css' projection, tv;
@import  "'custom.css'";
@import  '"chrome://communicator/skin/';
@import  "common.css" screen, projection;
@import  ''landscape.css' screen and (orientation:landscape);
```

Reported here:
https://wordpress.org/support/topic/saving-stylesheet-via-css-stylesheet-editor-double-quotation-is-increased?replies=1&view=all

**Comment by jeherve** [comment]
@cfinke Could this be caused by #3599?

**Comment by cfinke** [comment]
No, I broke this four long years ago in 234e068c224b6e68b312159466fcfb1c50754b5d.  I don't know how it could have been broken that badly this long without somebody noticing, but apparently, it was.  I'll work on a fix.

**Comment by cfinke** [comment]
Actually, I take that back; it is caused by #3599.

**Comment by richardmtl** [comment]
This is causing some major annoyances with WordCamp sites (among others, I'm sure).

**Comment by stephenfleming6** [comment]
I think it may have been reported here, but not connected...

[https://wordpress.org/support/topic/css-editor-not-working-with-google-fonts](https://wordpress.org/support/topic/css-editor-not-working-with-google-fonts)

**Comment by Kenshino** [comment]
I faced this on a WordCamp site with 
background: url('some_url');

It would add in additional single quotes ;/

**Comment by iandunn** [comment]
> It would add in additional single quotes ;/

[It sounds like that was fixed](https://wordpress.slack.com/archives/meta-wordcamp/p1464621689000663) by applying #3751
