### ISSUE TITLE
My Jetpack: Typo for Connection Flow

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/jetpack#37288]
### Impacted plugin

Jetpack

### Quick summary

Upon connecting a site within My Jetpack, `Conecting` is displayed.

https://github.com/Automattic/jetpack/blob/65c44e4239590772edc148a150699d6b01433253/projects/packages/my-jetpack/_inc/hooks/use-notification-watcher/use-site-connection-notice.tsx#L107

cc @IanRamosC 

At a meetup or I'd do a quick PR as it's just a typo.

### Steps to reproduce

Disconnect site, try reconnecing within My Jetpack

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

**Comment by IanRamosC** [comment]
Thanks, y'all 🙇🏾‍♂️
