### ISSUE TITLE
Tiled Gallery circle setting not working

### ISSUE THREAD

**Issue by robfelty** [Automattic/jetpack#37331]
### Impacted plugin

Jetpack

### Quick summary

Since Jetpack 13.4, the circles setting for tiled galleries is not working. When selecting the option in the block editor, it looks correct. However, after publishing a post, the published post has square images instead of circles. 

I tested this with Jetpack 13.3.1 and it works as expected. 

Please see attached screenshots illustrating the issue
<img width="1075" alt="Bildschirmfoto 2024-05-09 um 22 37 10" src="https://github.com/Automattic/jetpack/assets/19924/dcea169d-59ce-4e35-ba5d-c4ac6d377081">

<img width="1123" alt="Bildschirmfoto 2024-05-09 um 22 35 58" src="https://github.com/Automattic/jetpack/assets/19924/13818b90-f391-4a05-bce7-a2222ef34e92">

### Steps to reproduce

1. Create a new post
2. Insert a tiled gallery
3. Select the "circles" option from the styles dropdown at the top left of the block
4. Publish the post

### A clear and concise description of what you expected to happen.

I expect all the images to be cropped to a circle shape when I publish the post.

### What actually happened

The images show as circles in the post editor, but the images on front end do not.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

**Comment by StefMattana** [comment]
Also reported on 8170007-zen

**Comment by jeherve** [comment]
Closing in favor of #37194.
