### ISSUE TITLE
Contact Form: Email validation regex needs updating

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#3734]
A sharp-eyed user has noticed that the email validation regex here:

https://github.com/Automattic/jetpack/blob/4.0.2/modules/contact-form/js/grunion.js#L502

... no longer matches the one specified here:

http://www.regular-expressions.info/email.html

Perhaps we should update? This also applies to WP.com's version of `grunion.js`.

2635373-t

**Comment by salomestarbuck** [comment]
Hi, just wondering if the decision was made to update this? I'm wondering if it is what is causing me to have so much trouble modifying the 'required' text and the text on the 'Submit' button on the contact form. Whatever is going on with the regex is causing the rest of the code to be unrecognized as JS in the editor. Thanks!

**Comment by jeherve** [comment]
@salomestarbuck We haven't made any changes to that feature yet.

> modifying the 'required' text and the text on the 'Submit' button on the contact form. Whatever is going on with the regex is causing the rest of the code to be unrecognized as JS in the editor

It's worth noting that you can use the `jetpack_required_field_text` filter to change the "required" text:
https://jetpack.com/2016/03/18/hook-of-the-month-customizing-contact-forms/

To change the submit button text, you can use a custom shortcode parameter, `submit_button_text`, as explained here:
https://jetpack.com/support/contact-form/#customize-submit

**Comment by salomestarbuck** [comment]
Thank you!!!


On Mon, May 2, 2016 at 12:02 AM, Jeremy Herve <notifications@github.com>
wrote:

> @salomestarbuck <https://github.com/salomestarbuck> We haven't made any
> changes to that feature yet.
>
> modifying the 'required' text and the text on the 'Submit' button on the
> contact form. Whatever is going on with the regex is causing the rest of
> the code to be unrecognized as JS in the editor
>
> It's worth noting that you can use the jetpack_required_field_text filter
> to change the "required" text:
> https://jetpack.com/2016/03/18/hook-of-the-month-customizing-contact-forms/
>
> To change the submit button text, you can use a custom shortcode
> parameter, submit_button_text, as explained here:
> https://jetpack.com/support/contact-form/#customize-submit
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Automattic/jetpack/issues/3734#issuecomment-216127668>
>



-- 
Salomé

**Comment by salomestarbuck** [comment]
So, would I place that code into the functions.php file of my theme?

On Mon, May 2, 2016 at 7:06 AM, Salome Starbuck <salomestarbuck@gmail.com>
wrote:

> Thank you!!!
>
>
> On Mon, May 2, 2016 at 12:02 AM, Jeremy Herve <notifications@github.com>
> wrote:
>
>> @salomestarbuck <https://github.com/salomestarbuck> We haven't made any
>> changes to that feature yet.
>>
>> modifying the 'required' text and the text on the 'Submit' button on the
>> contact form. Whatever is going on with the regex is causing the rest of
>> the code to be unrecognized as JS in the editor
>>
>> It's worth noting that you can use the jetpack_required_field_text
>> filter to change the "required" text:
>>
>> https://jetpack.com/2016/03/18/hook-of-the-month-customizing-contact-forms/
>>
>> To change the submit button text, you can use a custom shortcode
>> parameter, submit_button_text, as explained here:
>> https://jetpack.com/support/contact-form/#customize-submit
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Automattic/jetpack/issues/3734#issuecomment-216127668>
>>
>
>
>
> --
> Salomé
>



-- 
Salomé

**Comment by jeherve** [comment]
@salomestarbuck The `jetpack_required_field_text` filter function has to be placed in your theme's functions.php file, or in a [functionality plugin](https://wordpress.org/plugins/code-snippets/).

The `submit_button_text` shortcode parameter has to be included in the contact form shortcode that appears in your page editor.
