### ISSUE TITLE
Newsletter: allow customizing "From" name

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#37354]
### Impacted plugin

Jetpack

### What

Newsletter: allow customizing "From" name.

As a newsletter user I want to set the name that appears in the newsletter email.
This helps with branding of the newsletter. 

<img width="857" alt="Screenshot 2024-05-14 at 8 56 26 AM" src="https://github.com/Automattic/jetpack/assets/115071/d3b3477c-f5e2-4195-9ddf-230ac8ad4b36">

[
Figma](https://www.figma.com/design/pifmSe1ASeLVr3NTphbJVY/Jetpack-Project-(Copy)?node-id=4384-3677&t=eyl4pF434QzCfLCO-0)

### How

We will be adding a new option that is text input that will allow our users to send emails with that as the newsletter name. 

Currently we use the blogname ( site name) as the newsletter name in the out going emails. 

```

Add it above the reply-to
Copy the same structure (heading = Email sender name for example) and an input with a save button?
```

**Comment by simison** [comment]
Edited issue to be about "From" name, not "Reply to" name. :-)

**Comment by simison** [comment]
@enejb I added this to Jetpack happiness inbox at Jetpack projects, can you open docs requests with `en.support-docs-content` too? The two docs teams can probably collaborate.
