### ISSUE TITLE
Allow "reply to" as blog comments for Jetpack and WP.com Atomic sites

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#37369]
WP.com simple sites can have replies to subscription emails go to their blog as public comments:

<img width="741" alt="Screenshot 2024-05-14 at 12 48 55" src="https://github.com/Automattic/jetpack/assets/87168/cce15db6-65ba-4e54-95f1-33af9c73162b">

<img width="471" alt="Screenshot 2024-05-14 at 12 51 08" src="https://github.com/Automattic/jetpack/assets/87168/f7e8252a-3611-4a46-8378-69690d330489">

For Jetpack and WP.com Atomic sites, this isn't possible currently and needs fixing.

See discussion in D134063-code

**Comment by jeherve** [comment]
Also in #1483. I'll let you decide which issue you'd like to keep!

**Comment by simison** [comment]
@jeherve that's different issue, and we actually just shipped a feature which allows setting "reply to" as blog author's email. [Closed and commented in above issue](https://github.com/Automattic/jetpack/issues/1483#issuecomment-2111810939).

This issue is about allowing "reply to as blog comment" to function across all types of sites; they currently work just for WP.com simple sites.

**Comment by simison** [comment]
Shipped!

![image](https://github.com/Automattic/jetpack/assets/87168/994020ec-62ca-45d4-abd3-88aca951e835)
