### ISSUE TITLE
Stats: Insights Traffic grid and the monthly main graph don't report the same numbers for the same month

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#37388]
### Impacted plugin

Jetpack

### Quick summary

The /stats/insights/ and /stats/month/ pages don't report the same number of views for the same month. On jetpack.com for instance the first has 364.9k for March and the second has 365.2k. For at least one customer (8154696-zen) the difference is 3-4%.

### Steps to reproduce

Open the /stats/insights/ and /stats/month/ pages for a site and compare the numbers.

### A clear and concise description of what you expected to happen.

The underlying API calls are slightly different and my guess is that the insights page is either more heavily cached or that the counting is less accurate to make the queries faster. Seems like it would be better to have the counting be accurate but also have good caching on each month. Probably need to invalidate the caching at the end of each month.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

**Comment by jeherve** [comment]
This seems somewhat similar to #36660. I'll close this issue as duplicate
