### ISSUE TITLE
Instagram Latest Post Block image sizes on video thumbnail

### ISSUE THREAD

**Issue by ezebecke** [Automattic/jetpack#37383]
### Impacted plugin

Jetpack

### Quick summary

When using the Instagram Latest Post Block to embed insta posts, some rows display a different aspect ratio (if the rows includes a post that's a video)

### Steps to reproduce

1- Connect a Instagram account and add it with the block
2- Make sure one of the post includes a video.
3- The row containing the post with the video will now change the aspect ratio.

### A clear and concise description of what you expected to happen.

To have all the posts with the same aspect ratio

### What actually happened

Here's an example where the user has a video post on the 3rd element and the 30.

https://github.com/Automattic/jetpack/assets/24919469/20867d9a-e4fe-4ddc-8f53-4d50185ecc3b

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by chatoxz-wp** [comment]
I believe this is already tracked in [Automattic/jetpack/issues/22241](https://github.com/Automattic/jetpack/issues/22241).
@jeherve is that correct?

**Comment by jeherve** [comment]
Yup, that sounds right.
