### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by sfxxx** [Automattic/jetpack#37448]
### Impacted plugin

VideoPress

### What

Upload audio files to VideoPress

### How

Dear Jetpack team,

I have a substantial number of large audio files that I'd like to upload to my site. For the same reasons as for videos, using my pretty limited webspace is not a good option.

It'd be great to be able to upload audio to VideoPress, and play it back with the VideoPress block. Right now I can use a workaround and create a blank video using ffmpeg, but that's somewhat stupid.

Kind regards,

Stefan

**Comment by jeherve** [comment]
Thank you for the suggestion. This is already tracked in #10125 so I'll close this one in favor of the other one.
