### ISSUE TITLE
Jetpack AI: open upgrade path on a new tab

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#37458]
We want all the editor upgrade call to actions to open on a new tab when clicked. We have upgrade call to actions on:

- the usage panel - #37457
- upgrade prompt from the block (and it's light colors version) - #37460
- upgrade message from the AI Control component - #37629
- other places on sidebar beyond usage panel - #37630

**Comment by lhkowalski** [comment]
Closing this as done.

**Comment by dhasilva** [comment]
ref p1715802181217389-slack-C0299DMPG
