### ISSUE TITLE
Stats: Dates have a `0` appended

### ISSUE THREAD

**Issue by pjohanneson** [Automattic/jetpack#37468]
### Impacted plugin

Jetpack

### Quick summary

In the Jetpack stats on my site's backend, all the dates seem to have a `0` appended to the day of the month. eg. `May 21` is displayed as `May 210`. I've attached a couple screenshots.

![Screenshot showing the issue - Stats date](https://github.com/Automattic/jetpack/assets/21602/dc8669f0-e489-4e41-8deb-e89ddaeff7b9)

![Screenshot showing the issue - Mouseover on a column](https://github.com/Automattic/jetpack/assets/21602/52889989-8e43-46c1-bdc7-21320eb58541)

### Steps to reproduce

View the Jetpack stats screen in a self-hosted WordPress site.

### A clear and concise description of what you expected to happen.

I expected the dates to be formatted correctly.

### What actually happened

A `0` is added to the day of the month on most instances of the date.

### Impact

One

### Available workarounds?

There is no user impact

**Comment by jeherve** [comment]
Thanks for the report!

Could you go to Settings > General in your dashboard, and let us know what the date format settings are there? is there a `0` appended to the date format there maybe?

**Comment by jeherve** [comment]
Potentially related: #37444

**Comment by pjohanneson** [comment]
My site's date settings are `F jS, Y`. 
![Screenshot 2024-05-21 at 09-18-27 General Settings ‹ Patrick Johanneson — WordPress](https://github.com/Automattic/jetpack/assets/21602/3c2326bc-3c00-4273-939c-1defcca29537)

**Comment by jeherve** [comment]
Thank you! We'll take a  look at this!

**Comment by pjohanneson** [comment]
> Potentially related: #37444

Yeah, I noticed this issue before I posted mine, and when I noticed the `0` in the mouseover dates shown in #37444 I wondered if it might be somehow related. Thanks!

**Comment by a8ck3n** [comment]
Hey @pjohanneson 👋 — Are you still able to reproduce this?

I'm not able to reproduce in my testing so I'm wondering if it's possibly been fixed in recent updates to the Stats dashboard as there have been many. If you are still seeing it, can you please let me know the version of the Jetpack plugin you have installed and the language setting from Settings → General → Site Language?

Thanks!

**Comment by a8ck3n** [comment]
Notes:

1. The date is generated based on the URL params. Either `startDate=YYYY-MM-DD` or `undefined`.
2. If undefined, a date is generated based on the current period and the `gmt_offset` from the site options.
3. When formatting the date for output, we do not respect the user preference in Settings → General. We currently default to the `LL` format as provided by Moment.js.

**Comment by pjohanneson** [comment]
It looks like a recent update has fixed the issue. I had noticed it sometime last week when I checked my stats, but today the dates appear normal (ie, "September 26", not "September 260"). I'm closing this now as it's been fixed. Thanks!
