### ISSUE TITLE
SSO: Recent changes breaks Two-Factor plugin

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#3747]
@ebinnion - I believe your recent changes borks the Two Factor feature plugin ( https://wordpress.org/plugins/two-factor/ ).

Typically, after either using SSO or entering your local user/pass, you're prompted to enter your 2fa code. After the recent changes, it results in a blank space:

<img width="477" alt="screen shot 2016-04-27 at 20 55 26" src="https://cloud.githubusercontent.com/assets/88897/14874155/b4dd10f4-0cba-11e6-9565-6b2f97998c66.png">

Removing the `jetpack-sso-body` body class resolved it. I haven't dug in, but is there a way to be more specific on when to hide the login elements or should we amend the 2fa plugin to give us something else to work with?

cc: @georgestephanis as the 2fa plugin guru.

**Comment by ebinnion** [comment]
Nice catch sir. I'll take a look.

**Comment by ebinnion** [comment]
@kraftbj – I haven't tested yet, but I believe that #3744 might fix this. In #3744, we only add the SSO form and enqueue styles/scripts when we're actually going to show the form. Which should just be `login`/`logout` action and `jetpack-sso` action (if the SSO fails).

I'll get that setup a bit later to confirm.

**Comment by ebinnion** [comment]
I tested and verified that #3744 does fix the visual regression. That being said, I'm getting this error when using Jetpack SSO and the 2fa feature plugin:

`Error, invalid response data.`

I narrowed it down to here:

https://github.com/Automattic/jetpack/blob/master/modules/sso.php#L645-L647

It looks like what happens is that the 2fa plugin hooks after we first called `handle_login()`. Then, when 2fa is finished it redirects back to the SSO url which calls `handle_login()` again.

At this point, if I just go to `wp-admin` I am logged in fine. But, we need to probably either:

- If we're going to error there, probably check if the user is logged in before erroring.
- Filter the 2fa redirect URL perhaps?

Ping @georgestephanis for thoughts.

**Comment by jeherve** [comment]
@georgestephanis How do you think we should proceed here?

**Comment by mohamadhegazy** [comment]
same issue with jetpack sso, but i can choose login with backup keys and again choose login with TOTP at that time i can enter the code and sign in normally, hope it helped

**Comment by georgestephanis** [comment]
Huh, didn't see this until just now.  Will try to do some testing later today or this weekend to narrow it down.

**Comment by mohamadhegazy** [comment]
great, let me know if you need me for testing!

**Comment by KZeni** [comment]
I also experienced the issue where the Two-Factor plugin's Authenticator Code label & input on the login form are hidden by Jetpack's CSS.

It appears the p element within the form which contains the Authenticator code label & input is hidden due to Jetpack SSO CSS hiding the p element since it has the Jetpack SSO CSS being applied to the page (simply disabling the “display:none;” style on the .jetpack-sso-form-display #loginform > p, .jetpack-sso-form-display #loginform > div rule for the Two-Factor login form elements shows the label & input without issue).

**Comment by KZeni** [comment]
Looks like the Two-Factor plugin has officially added CSS to prevent this issue on its end: https://github.com/georgestephanis/two-factor/pull/196 (ideally, this workaround CSS wouldn't need to be present though)

**Comment by kraftbj** [comment]
Going to close this out for now. If the two-factor plugin picks back up as an active feature plugin, we can work more to determine the issues involved.
