### ISSUE TITLE
Add Image Lightbox

### ISSUE THREAD

**Issue by TwisterMc** [Automattic/jetpack#375]
Quite often users link images to themselves. This then opens the image in the browser without the site look and feel. Instead, a lightbox would be much more convenient. Not only would site authors keep their branding, but it'd also be better for users. I have a feeling a number of users wonder what happened to the site they were on.

Currently I use plugins like Lightbox 2 to auto lightbox images. https://wordpress.org/plugins/wp-lightbox-2/ Where as this works, it sometimes conflicts with JetPack galleries as they're both tryign to control where linked images go.

I'd love to see JetPack have the option to automatically add lightboxes to images that are linked to themselves.

https://cloudup.com/cU3FB3Ja2q5

**Comment by aheckler** [comment]
Requested in 2062532-t.

**Comment by richardmtl** [comment]
Also requested in 2219567-t

**Comment by jeherve** [comment]
Also requested here:
https://wordpress.org/support/topic/please-enable-carousel-view-from-single-image-posts-2?replies=1&view=all

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/carousel-lightbox-on-single-image?replies=1&view=all
