### ISSUE TITLE
Video Sitemap

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#3750]
It would be great if the xml sitemaps offered a video xml sitemap. Especially useful for sites that use the videopress features in jetpack.

https://developers.google.com/webmasters/videosearch/sitemaps

**Comment by kraftbj** [comment]
cc: @georgestephanis wrt VideoPress.

Generally, may make sense to spin off a video sitemap based on the video post format?

**Comment by jeherve** [comment]
This has now been implemented. Closing.
