### ISSUE TITLE
Classic Editor: Add Support for Double-Tilde Strikethrough.

### ISSUE THREAD

**Issue by gitjeff2** [Automattic/jetpack#3752]
#### What I expected

With Markdown support enabled it appears that enclosing text in double-tilde (~~) in a Wordpress post or article does not result in ~~strike-through~~ text. There is a certain irony in reporting this bug as it works fine in GitHub's editor.
#### What happened instead

Instead of getting strike-through text the pair of tildes are rendered as text. Thus:

```
some text ~~I want a strike-through here~~ but I don't get it.
```
#### Steps to reproduce the issue

Create a Wordpress post with Markdown enabled and enclose a word in double-tilde like so: `~~word~~` and it won't be rendered as strike-through.
#### Additional Notes

I've grown accustom to GitHub flavored Markdown and would like to see the feature included in Jetpack. Including tilde strike-through support won't conflict with plain vanilla markdown or common Markdown extensions like [Markdown Extra](https://michelf.ca/projects/php-markdown/extra/).

Also, it's worth noting that several markdown editors support this usage including [dillinger.io](http://dillinger.io), and [stackedit.io](http://stackedit.io) so it seems support for double tilde has entered common usage.

**Comment by kraftbj** [comment]
We use Markdown Extra, which is why it doesn't work. I've used similar styling in Slack and agree it is nice to have.

**Comment by snarfed** [comment]
Hi @kraftbj et al! [You all migrated to the markdown-it parser, right?](https://jetpack.com/support/jetpack-blocks/markdown/#markdown-implementation) Looks like it's pretty easy to enable strikethrough in markdown-it while still staying in CommonMark mode: https://github.com/markdown-it/markdown-it/issues/892#issuecomment-1230480428 . That would be nice to have!

**Comment by kraftbj** [comment]
Actually, @snarfed I think when we moved to Markdown-It for the block, it now just works.

If you're using the Classic Editor, that is still using the PHP-based Markdown Extra package.

I'll update this ticket to reflect the Classic Editor.

**Comment by snarfed** [comment]
Ah true, good point! Damn rich old ecosystem of not-yet-blocks tools, sigh. Thanks for the nudge.

**Comment by kraftbj** [comment]
@snarfed It didn't seem too bad to add it to the classic editor. I added a PR to this issue if you want to give it a test drive.

**Comment by snarfed** [comment]
Oh wow, thank you, awesome!
