### ISSUE TITLE
Jetpack: VaultPress Upgrade Nudge Showing via JITM when Site Already has Backup

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#37535]
### Impacted plugin

Jetpack

### Quick summary

Jetpack sometimes shows an upgrade nudge for a feature that is already included in bundled plan

### Steps to reproduce

I'm unsure of the JITM logic, but with a bundle plan, browsing around the Jetpack dashboard should trigger the JITM

### A clear and concise description of what you expected to happen.

I would expect that any JITM shown would not reference a duplicate service

### What actually happened

I tested this on a site with Jetpack Premium:

![Screenshot on 2024-05-24 at 10-03-33](https://github.com/Automattic/jetpack/assets/45246438/e3198df5-0b32-4c4d-8ded-877b4c579e26)

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by jeherve** [comment]
Could you clarify what type of plan is currently active on your site, and what your site URL (or even better, site ID) is?

> I'm unsure of the JITM logic

It is defined here:

fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Sjcpbz%2Qovyyvat%2Spynff.jcpbz%2Qfgber.cuc%3Se%3Q9rr45p57%231107-og

**Comment by bobmatyas** [comment]
@jeherve It's a Jetpack Premium plan. Blog ID: 190112353

**Comment by jeherve** [comment]
Thank you! That would explain things, it would seem legacy plans are not well handled in our logic.

@Automattic/jetpack-martech Is that something you would be interested in taking on? Maybe `get_jetpack_backup_products` should be updated to include all types of plans, including personal, premium, and professional, like we do here for example?
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Snqzva%2Qcyhtvaf%2Sjcpbz%2Qovyyvat%2Spynff.jcpbz%2Qfgber.cuc%3Se%3Q9rr45p57%231830-og

**Comment by CodeyGuyDylan** [comment]
> @Automattic/jetpack-martech Is that something you would be interested in taking on?

I'll add this to maintenance, thank you for the ping!

> Maybe get_jetpack_backup_products should be updated to include all types of plans, including personal, premium, and professional, like we do here for example?

I'd be hesitant to do that not knowing all of where that is used, perhaps in the JITM itself we can just get the backup products from that function and merge them with `get_jetpack_premium_plans` and `get_jetpack_personal_plans`, etc.

**Comment by CodeyGuyDylan** [comment]
> I'd be hesitant to do that not knowing all of where that is used, perhaps in the JITM itself we can just get the backup products from that function and merge them with get_jetpack_premium_plans and get_jetpack_personal_plans, etc.

I changed my mind on this, they are Backup products so I don't see how that would have any negative effects. Working on this now

**Comment by CodeyGuyDylan** [comment]
Diff opened here: D150628-code

**Comment by CodeyGuyDylan** [comment]
Fix has been shipped, this JITM should no longer show in the case of a user having a plan with backups
