### ISSUE TITLE
Disconnection prompt mentions "1 question", vs. 2 questions in the survey

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3753]
Steps to reproduce:

1. Start connecting a Jetpack site to your WordPress.com account
2. Click on "Deny" instead of "Approve" when connecting the site to WordPress.com
3. You will be redirected to the Jetpack menu in your dashboard, and this message will appear:

> Would you mind telling us why you did not complete the Jetpack connection in this [1 question survey](http://jetpack.com/cancelled-connection/)?

4. When clicking on the link, I get redirected to a Polldaddy page including 2 questions:

![screen shot 2016-05-02 at 11 02 22 am](https://cloud.githubusercontent.com/assets/426388/14950906/a72f665c-1055-11e6-9a05-b312614c75c2.png)

Maybe we should change the wording of the Jetpack menu message to mention that there will be 2 questions?

cc @richardmuscat

**Comment by richardmuscat** [comment]
@jessefriedman I think you put this survey up right? I believe the thinking is that the "email" question is not a question about the product but the headline definitely should reflect that.

**Comment by jessefriedman** [comment]
@richardmuscat @jeherve I fixed this on the survey side. It consistently says 1 question now and the email bit doesn't ask a question anymore. 

<img width="722" alt="screen shot 2016-05-24 at 9 58 30 am" src="https://cloud.githubusercontent.com/assets/1749986/15506800/f6ffa14a-2196-11e6-99ae-17f001d5bde1.png">
