### ISSUE TITLE
Photon overriding links to images in different domains.

### ISSUE THREAD

**Issue by pabloselin** [Automattic/jetpack#3754]
#### What I expected

I'm uploading a thumbnail in my content with a link to an image in another website. And I'm expecting Photon to convert only the little thumbnail to his service. 

#### What happened instead

But when I load the page in the frontend I notice that the link to the image of the external service is replaced with a custom link from WordPress CDN overriding my custom link. In this fashion: https://i1.wp.com/[original-domain.com]/97568973.jpg

#### Steps to reproduce the issue

To reproduce the error you have to put an image in the editor with no link, and then link the image to another image (could be the same at full size) in another domain. In the backend everything will look normal but when you serve the page you will notice the replaced domain.

If you put an image in the editor, with no link, and then add a link manually to an external website you should be able to get the original url, not the Photon generated one.

I don't know if this is intentional, but in my opinion photon should respect the different domain when you link in this way.

Thanks.

Reference URLS:

https://i2.wp.com/archive.org/download/pn043/pn043large.jpg?ssl=1
https://pueblonuevo.cl/2009/05/05/synco-soundtrack/

**Comment by jeherve** [comment]
That does indeed seem like an issue.

Here is the HTML from your post.

```html
<a href="https://i2.wp.com/archive.org/download/pn043/pn043large.jpg?ssl=1" target="_blank" class="no-border">
    <img class="aligncenter wp-image-615 size-full" src="https://i1.wp.com/pueblonuevo.cl/wp-content/uploads/2016/05/mailing-synco-cover.jpg?resize=700%2C347&amp;ssl=1" alt="" width="624" height="309">
</a>
```

Could you paste the image markup as it appears in your post editor, so we can investigate further?

Thanks!

**Comment by pabloselin** [comment]
Hi, here is the original markup:

`<a href="https://archive.org/download/pn043/pn043large.jpg" target="_blank"><img class="aligncenter wp-image-615 size-full" src="https://pueblonuevo.cl/wp-content/uploads/2016/05/mailing-synco-cover.jpg" alt="" width="700" height="347" /></a>`

**Comment by jeherve** [comment]
Thanks! It looks like Photon works as intended in this case.

Photon was designed to change the markup for all image links. If your link were to be anything but an image, it wouldn't be touched by Photon.


> in my opinion photon should respect the different domain when you link in this way.

**Comment by pabloselin** [comment]
Thanks for the quick reply! I thought Photon only cared for images inside wp-content folder. Now I'm more clear about how it works.
