### ISSUE TITLE
New Icon: VK

### ISSUE THREAD

**Issue by serzhenko** [Automattic/jetpack#37543]
Could you please consider adding a VK icon 

[Official EPS logo](https://vk.com/doc1515904_438101546?hash=40ece2f39973f572c1&dl=5bd713c10299b5a34a) could be downloaded here

**Comment by tbradsha** [comment]
Potential logo source:
https://ru.m.wikiquote.org/wiki/%D0%A4%D0%B0%D0%B9%D0%BB:VK_Compact_Logo_(2021-present).svg
