### ISSUE TITLE
New Icon: git

### ISSUE THREAD

**Issue by BrookeDot** [Automattic/jetpack#37548]
The GitHub "Octocat" icon has been in the font for some time now. However, for those using git from another source (BitBucket, GitLab, running their own git instance) the generic git icon would be handy much like the generic RSS logo is. 

Here's the logo from [git-scm.com](https://git-scm.com):
![logo 2x](https://user-images.githubusercontent.com/150348/42299088-13e55e94-7fbe-11e8-945b-45d7f79af0d1.png)

**Comment by tbradsha** [comment]
Assets: https://git-scm.com/downloads/logos
