### ISSUE TITLE
New Icon: Bloglovin

### ISSUE THREAD

**Issue by KokkieH** [Automattic/jetpack#37547]
Requested in https://en.forums.wordpress.com/topic/social-icons-9?replies=2

**Comment by tbradsha** [comment]
I did find some assets here: https://www.bloglovin.com/widgets

That said, I'm closing this for now:

* We've only had one request in 6 years.
* The status of the service is unclear:
    * It rebranded in April 2018 to Activate.
    * The original name does seem to exist, but with no recent indication of actual popularity/activity (e.g. the Android app shows "100+" downloads).
* Given the above, the current icon is more apt to confuse than add value.

Feel free to reopen if things change.
