### ISSUE TITLE
Sharing: Add vk.com 

### ISSUE THREAD

**Issue by davoraltman** [Automattic/jetpack#3760]
Found this in vk.com docs:

http://vk.com/dev/share_details

There's also this plugin - https://wordpress.org/plugins/vkontakte-api/

per 2645847-t

**Comment by SPEC1AL1ST** [comment]
Very nice idea!

**Comment by jeherve** [comment]
Closing as duplicate of #849

> There's also this plugin - https://wordpress.org/plugins/vkontakte-api/

If you'd like to add the VK.com button to Jetpack's Sharing module, you're better off using this plugin:
https://wordpress.org/plugins/vk-sharing-jetpack/
