### ISSUE TITLE
Custom Content Types: admin UI is not responsive

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3764]
![chlrxw3w0aenvtb](https://cloud.githubusercontent.com/assets/426388/15009779/bfef7f4e-11e8-11e6-8757-2c99e6618063.jpg)

> it's best to leave "Title" (primary) as first column (move thumbnail column)

Reported here:
https://twitter.com/turtlepod/status/727730865254576128

**Comment by turtlepod** [comment]
Hi @jeherve,
thank you for creating this thread. Several notes:
1) even though you can "css-hack" it to add thumbnail in first column, i think it just make things complicated.
2) no table head title, i think it's best to have a title (maybe for accessibility purpose?) and it look better in mobile (WP use that in mobile view)

Here's an example of mobile view of my <a href="https://wordpress.org/plugins/fx-photo-tag/">f(x) Photo Tag</a> plugin (thumbnail in last column).

<img src="https://dl.dropboxusercontent.com/u/32880842/etc5/thumbnail-column-photo-tag.png"/>

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
