### ISSUE TITLE
Classic Block / Classic Editor: Gallery settings Link To "None" not reflected in front end

### ISSUE THREAD

**Issue by mxhassani** [Automattic/jetpack#37645]
### Quick summary

When adding a gallery with the classic editor or inside the Gutenberg classic block, or using the shortcode `[gallery link="none" ids="1,2,3....` , the images are still clickable and show the lightbox.

### Steps to reproduce

1. Add the Classic Block, or enable the Classic Editor
2. Add a gallery to it
3. Set Link To "None" in the gallery settings
4. Save, and check in front end.
5. Click the images and notice the images are clickable and open a lightbox.

### What you expected to happen

Expected the image to not be clickable

### What actually happened

When clicking an image a lightbox shows up.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

It seems related to this one https://github.com/Automattic/jetpack/issues/11264

Issue not happening on Simple sites.

### Workaround:

```
.jp-carousel-overlay{
  display: none;
}
[class*=gallery-item] *{
  cursor: default !important;
} 
```

This code will affect almost all galleries in the site. Consider custom classes when implementing.

**Comment by mxhassani** [comment]
8236853-zen

**Comment by jeherve** [comment]
Transferring to the Jetpack repo, where the Carousel feature lives.

**Comment by jeherve** [comment]
> It seems related to this one https://github.com/Automattic/jetpack/issues/11264

That is indeed the same issue. Closing this one as duplicate.
