### ISSUE TITLE
IDC: Remove IDC checks

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#3766]
In 3.8, we attempted an UI to auto-detect, notify, and resolve all IDCs. The support load due to problems in how the tool worked, in day-to-day life, led us to comment it out for stable releases as of 3.8.1.

In conversations since and the development of the is_staging_site checks, a one-patch-to-fix-it-all approach doesn't seem to be the best. We should remove the code as I don't believe we have any intention of using it forward.

In addition to gutting the code, we should clean the settings still left over from 3.8 (as seen in is_staging_site).

**Comment by kraftbj** [comment]
The notice itself being removed in #4272.

**Comment by jeherve** [comment]
Fixed in #4272. @kraftbj Are you okay with closing this, or would you rather leaving this open until we take care of the settings as well?
