### ISSUE TITLE
Classic Theme Helper: Warning filemtime(): Assets not being registered properly.

### ISSUE THREAD

**Issue by darssen** [Automattic/jetpack#37666]
### Impacted plugin

Jetpack, mu wpcom

### Quick summary

When going through Featured content flow this Warning is showing.

> [31-May-2024 15:09:06 UTC] PHP Warning:  filemtime(): stat failed for /srv/htdocs/wp-content/plugins/jetpack-mu-wpcom-plugin-dev/vendor/automattic/jetpack-classic-theme-helper/src/../build/featured-content/suggest.js in /srv/htdocs/wp-content/plugins/jetpack-dev/jetpack_vendor/automattic/jetpack-assets/src/class-assets.php on line 381

Warnings can be seen in 137f23f5e94093e0802a9c9ebd0dae11-logstash

Introduced with https://github.com/Automattic/jetpack/pull/37515

### Steps to reproduce

- Go into a test atomic site.
- Change to Dara Theme.
- Go Into Customizer (Featured Content should appear)

### A clear and concise description of what you expected to happen.

There should be no Warnings

### What actually happened

Warning.

### Impact

All

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Atomic

**Comment by darssen** [comment]
@anomiex could you provide some insight on what is wrong here? 
When creating the build manually it creates the file as per the comment [here](https://github.com/Automattic/jetpack/pull/37515#pullrequestreview-2076146805). But it seems to not be the case for wpcomsh or the `jetpack-mu-wpcom-plugin-dev` in my tests

**Comment by anomiex** [comment]
Looks like someone forgot to add a line like this
https://github.com/Automattic/jetpack/blob/4a55f3c47ca492fd2802113eec2acbea360153b2/projects/packages/my-jetpack/.gitattributes#L8
in https://github.com/Automattic/jetpack/blob/trunk/projects/packages/classic-theme-helper/.gitattributes, so none of the built files wind up in [the mirror repo](https://github.com/Automattic/jetpack-classic-theme-helper).
