### ISSUE TITLE
Boost: Update Cloud CSS UI to include debug steps

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#37679]
> [!Note]
> This is using the updated error UI. The old version had the same issue.

The UI should include the debug steps similar to the free version.

The free UI:
![Image](https://github.com/Automattic/jetpack/assets/11799079/a8a765bd-12ad-45ae-aa5c-09d3293deacc)

The current (premium) UI:

![Image](https://github.com/Automattic/jetpack/assets/11799079/245031d1-5ecf-43ff-a3a3-8dca77e76ac8)

The reason we don't have the steps is the response from boost cloud. More info here pc9hqz-2TQ-p2

**Comment by haqadn** [comment]
Based on my recollection and a quick scan of the code, I think this was addressed. Please re-open if not.
