### ISSUE TITLE
Stats: day info popup fails when browser edge is too near

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#37696]
### Impacted plugin

Jetpack

### Quick summary

Anywhere with popups, popup fails to work when browser's lower edge is near.

- WP.com simple site in Calypso.
- Jetpack site in wp-admin
- Stats widget at wp-admin dash

### Steps to reproduce

1. Have days without visitors on stats
2. At the traffic tab, hover over 0 days and see a popup appear
3. Scroll so the browser's lower edge is near, and try hovering again. Popup doesn't appear or appears flickering.

https://github.com/Automattic/jetpack/assets/87168/ab12983d-c2ba-4620-ae36-eddec4b727dd

<img width="481" alt="image" src="https://github.com/Automattic/jetpack/assets/87168/528a7f0e-6cbd-4200-9748-d6d2af1508af">

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

- Chrome

**Comment by simison** [comment]
cc @kangzj  can your team take a look?

**Comment by kangzj** [comment]
The bar chart has a few issues and we are looking to replace bar charts with line charts (https://github.com/Automattic/jetpack-roadmap/issues/492) starting in about two weeks  and we'll fix any issues if they still persist.

**Comment by simison** [comment]
Nice, even better! 👍
