### ISSUE TITLE
Debugger: Add Jetpack Footer

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#3770]
On the Debug page within the plugin, we do not have the Jetpack footer. It'd be nice to keep that consistent.

**Comment by htdat** [comment]
Closing this issue as it seems to be fixed. This is what I am seeing in 7.4: 

![Screen Shot on 2019-06-07 at 16:07:25](https://user-images.githubusercontent.com/10045087/59093542-6828e900-893e-11e9-8891-f980b5b64835.png)
