### ISSUE TITLE
Super Cache: Update WPSC admin banner per design

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#37744]
As part of the migration, update the banner on the settings page and add a button to allow the WPSC user to install Boost and jump to the Boost settings page. 

Check if Boost is new enough, and hide banner if not.

* If Boost is installed, take user to Boost.
* If Boost is not installed, only install Boost and take the user to the Boost Getting Started page.
* Learn more action will point a future public post pending to be published.

Depends on https://github.com/Automattic/jetpack/issues/37742

ref: p1HpG7-sfQ-p2

**Comment by pyronaur** [comment]
Done in #37963
