### ISSUE TITLE
Boost: handle "jb_cache_moved_to_boost" flag set as part of WPSC migration

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#37745]
WPSC will record a transient user option called jb_cache_moved_to_boost to inform Jetpack Boost that the site owner migrated their site from that plugin to Boost. Boost will track this event.

The value identifies how the user came to Boost:
* Admin notice (notice): install/switch to Boost and enable the Page Cache module. Disable WPSC.
* Admin banner (banner): install/switch to Boost only. Do not enable Page Cache module.
* "Try Jetpack Boost" button (try_button): install/switch to Boost only. Do not enable Page Cache module.

Ref: #37742

**Comment by pyronaur** [comment]
Ready: https://github.com/Automattic/jetpack/pull/37963
