### ISSUE TITLE
Super Cache: Add secondary "Try Jetpack Boost" button next to "Update Status" button on settings page

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#37747]
On the Easy settings page, add a secondary button "Try Jetpack Boost" next to the "Update Status" button.

This button will sideload Jetpack Boost if required, set a transient option to tell Boost that the user came from Super Cache.

Check that Boost is new enough. If not, then hide the button.

* If Boost is installed, take user to Boost.
* If Boost is not installed, only install Boost and take the user to the Boost Getting Started page.

Depends on: #37742

ref: p1HpG7-sfQ-p2

**Comment by donnchawp** [comment]
Use the JavaScript in inc/admin.js as a base for this.

**Comment by pyronaur** [comment]
Addressed in #37963
