### ISSUE TITLE
Conflict Jetpack Boost and Avada Theme

### ISSUE THREAD

**Issue by cuemarie** [Automattic/jetpack#37768]
### Impacted plugin

Boost

### Quick summary

When sites using the theme Avada are running Jetpack Boost, the Avada editor throws the error: `TypeError: jQuery.AWB_Color is not a function`

Full error log from one customer report here: p1717983450706039/1717983442.879519-slack-C040W2SD4HE

### Steps to reproduce

Avada is a paid theme not available in the WordPress.org themes list, so the best way to test may be to SU/SSP into any of the sites listed below, then:

1. Open a page in the editor
2. Click on the Live Editor
3. Find the error 
4. Deactivate Jetpack Boost
5. Refresh the editor to see the error cleared

### A clear and concise description of what you expected to happen.

The editor to work even while Jetpack Boost is active

### What actually happened

![CleanShot 2024-06-09 at 18 39 55@2x](https://github.com/Automattic/jetpack/assets/27249804/d4070bd6-9489-40a9-9b32-b8c25422f1c7)

These sites must turn off Jetpack Boost to edit their content.

### Impact

Some (< 50%)

### Available workarounds?

~No and the platform is unusable~

_Update: Users can deactivate Jetpack Boost prior to editing any pages or posts as a workaround._

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

### Logs or notes

Customer Reports, all using Avada and Jetpack Boost

- June 9: 8306831-zen -- blogid: `107259224`
- June 8: 8301072-zen -- blogid: `07507605`
- June 2: 8262381-zen -- blogid: `233698552`
- Apr 30 (and previously on Mar 18): 8127032-zen -- blogid: `162739117`
- March 28: https://wordpress.com/it/forums/topic/errore-generato-da-plugin-boos-di-jetpack/ -- blogid: `176579440` (self-hosted)
- March 20: 7895912-zen -- blogid: `229795699`

**Comment by cuemarie** [comment]
Flagged here: p1717983442879519-slack-C040W2SD4HE

**Comment by cuemarie** [comment]
Updated the workaround and priority label – given the small number of reports I'm not sure it would even be that high, just didn't want it to be flagged as a huge blocker 🔴  😄 Thanks!

**Comment by liviopv** [comment]
📌 ACTIONS
- Marking as Triaged based on the investigation and possible fix coming soon p1717983442879519-slack-C040W2SD4HE

**Comment by cuemarie** [comment]
Update from the thread linked above:

> We already have a fix ready due to a similar issue with woocommerce and it will be resolved in our next release(expected this week). Until then, a workaround is to exclude `wp-codemirror` from concatenation

![image](https://github.com/Automattic/jetpack/assets/27249804/b5bc5b08-3bec-478c-b18f-c511ba7fd5cb)

**Comment by haqadn** [comment]
We have replaced the minification library, and the issue should be fixed now. Please ask the users to update to latest version of Boost (3.4.4).
