### ISSUE TITLE
My Jetpack: Upgrade Nudge Showing when Stats Plan Present

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#37762]
### Impacted plugin

Jetpack

### Quick summary

On the Stats cards in "My Jetpack", we are nudging to "Upgrade" when a plan is present and there is no need to upgrade.

### Steps to reproduce

1. Add a Stats plan to a site
2. View "My Jetpack" to see the issue

### A clear and concise description of what you expected to happen.

Upgrade notice should only be shown when there is an upgrade need

### What actually happened

**Initial view after installing Jetpack:**
---

![Screenshot on 2024-06-06 at 10-09-15](https://github.com/Automattic/jetpack/assets/45246438/4c89d5e7-1de2-4fdb-a74c-d4d3945fb506)

**After Reloading:**
---

Card is replaced by stats view. An "Upgrade" button stays though:

![Screenshot on 2024-06-06 at 10-00-24(1)](https://github.com/Automattic/jetpack/assets/45246438/652bc566-04d0-4ea3-a3c5-d6b434e3800c)

If I click on that, it asks me to purchase the next highest tier, even though I'm nowhere near that level of use:

![Screenshot on 2024-06-06 at 10-00-46](https://github.com/Automattic/jetpack/assets/45246438/445096e5-384c-41e5-9fbe-a8b3d7c93d0d)

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

v13.5

**Comment by lsl** [comment]
@kangzj Is this still an issue?

**Comment by kangzj** [comment]
@lsl I think so, and I believe it's already on the Jetpack Martech's radar.

**Comment by lsl** [comment]
Thanks, no movement since Jun tells me this automated high priority label isn't accurate. Moved to normal.

**Comment by kangzj** [comment]
> Card is replaced by stats view. An "Upgrade" button stays though:

This is expected as users should always be able to upgrade tiers when needed.
