### ISSUE TITLE
Feature Request: Independent Social Media Scheduling for Jetpack Social

### ISSUE THREAD

**Issue by jos22** [Automattic/jetpack#37772]
### Impacted plugin

Social

### What

 Allow users to schedule social media posts independently of WordPress post scheduling

### Summary: 

Allow users to schedule social media posts independently of WordPress post scheduling, providing increased flexibility and control over posting times and frequencies on social media.

It's a known fact [posting times](https://blog.hubspot.com/marketing/best-times-post-pin-tweet-social-media-infographic) on social media have impact on engagement numbers, and this added feature will give users precise control over social media posting schedule that's independent from their post publishing scheduling.

**Comment by coder-karen** [comment]
Closing as there is a similar request here: https://github.com/Automattic/jetpack/issues/27077
