### ISSUE TITLE
Twitter cards will never load when jetpack_disable_twitter_cards filter is in use regardless of true or false

### ISSUE THREAD

**Issue by dpegasusm** [Automattic/jetpack#3778]
Twitter tags are never added to the site when the jetpack_disable_twitter_cards filter is present due to a true false clause in the files related to twitter card loading.

in file class.jetpack.php on line 1940 there is a true/false clause: 

`		if ( apply_filters( 'jetpack_disable_twitter_cards', true ) ) {
			require_once JETPACK__PLUGIN_DIR . 'class.jetpack-twitter-cards.php';
		}
`

which checks that the twitter cards are not disabled which is the default. Setting this to true should load cards but it does not because it hits another if/then check in class.jetpack-twitter-cards.php on line 21 which is looking for true as well. when this find true it exits the function and only displays the og tags

`		/** This action is documented in class.jetpack.php */
		if ( apply_filters( 'jetpack_disable_twitter_cards', false ) ) {
			return $og_tags;
		}
`

Which causes a catch 22 situation. If the first reference to disable twitter cards is false the twitter cards will end without the class being loaded, but if you set it to true it will load the twitter card class but never proceed beyond line 22 of the function ttwitter_cards_tags and will short circuit to return the OG tags only. So regardless of true or false to the disable clause twitter cards never load as it will either short circuit before loading the class or at line 22 of the twitter_cards_tags function.

**Comment by kraftbj** [comment]
Good find @dpegasusm!

**Comment by jeherve** [comment]
@dpegasusm I created #3782 to open a Pull Request with your patch.
