### ISSUE TITLE
Jetpack AI Assistant Expand Rewrites Existing Content

### ISSUE THREAD

**Issue by ha-un** [Automattic/jetpack#37807]
### Impacted plugin

Jetpack

### Quick summary

When using the "Expand" option in Jetpack AI, users are expected to see additional content added to the existing paragraph. Jetpack re-scans the existing text and only re-writes what was already there, not adding new content.

### Steps to reproduce

1. Write a paragraph in a new post
2. Highlight the paragraph and click on the AI Assistant icon
3. Click on "Expand"

### A clear and concise description of what you expected to happen.

For Jetpack AI Assistant to extend the existing paragraph by adding new content.

### What actually happened

Jetpack AI Assistant scans the written paragraph and then re-writes what was already written without changing or adding any content. This issue is replicable both on Simple and Atomic sites.

https://github.com/Automattic/jetpack/assets/96960321/037867bd-64ab-48e6-b912-7a30d2b83007

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

8254897-zd-a8c

**Comment by pehaa** [comment]
Reported also in 8297694-zd-a8c

**Comment by mpkelly** [comment]
> Dogs are renowned as loyal companions, earning them the title "man's best friend". They come in various breeds, each with distinct characteristics and traits. 

This may be fixed already. I tried using the same sentence in the video and a different one. In both cases, the text was expanded. 

https://github.com/user-attachments/assets/b0dc49e3-f27d-4a3a-9848-3f3ca1c4bbdf

https://github.com/user-attachments/assets/ffc3cec7-ca7b-404e-8830-cf1263b5c05a

Actions:

- Lower priority
- Tag @ha-un for a retest

**Comment by gikaragia** [comment]
I have verified that this is indeed fixed now. More context here: p1718224587600109/1717742494.254509-slack-C054LN8RNVA
