### ISSUE TITLE
Unable to change publish date on Jetpack Mobile

### ISSUE THREAD

**Issue by ricklabsdotn8** [Automattic/jetpack#37851]
### Impacted plugin

Jetpack

### Quick summary

The publish date cannot be update on Jetpack Mobile

### Steps to reproduce

1. Create a post on Jetpack or on the dashboard
2. Go to Jetpack Mobile
3. Update the publish date for the post then save

### A clear and concise description of what you expected to happen.

- The publish date should be updated

### What actually happened

- The change reverts to the original publish date

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Logs or notes

Workaround - update publish date on WP-Admin

8323256-zen

**Comment by jeherve** [comment]
Since this bug report is about the mobile Jetpack apps, I would recommend creating a new issue in the matching GitHub repo here:
https://github.com/wordpress-mobile

**Comment by ricklabsdotn8** [comment]
@jeherve, since it affects both iOS and Android, should I create two tickets?

**Comment by jeherve** [comment]
Yes, you can.

**Comment by alinclamba** [comment]
@ricklabsdotn8 I couldn't find the other issues so I opened them: 
- For Android: https://github.com/wordpress-mobile/WordPress-Android/issues/21001 and 
- For iOS: https://github.com/wordpress-mobile/WordPress-iOS/issues/23369
