### ISSUE TITLE
Multiple Modules: Deprecated jQuery size() calls

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/jetpack#3786]
publicize uses deprecated jQuery size() calls, causing warnings:

```
<script type="text/javascript">
jQuery( function($) {
	var wpasTitleCounter    = $( '#wpas-title-counter' ),
		wpasTwitterCheckbox = $( '.wpas-submit-twitter' ).size(),
		wpasTitle = $('#wpas-title').keyup( function() {
```

and
```
	$('#publicize-form-edit').click( function() {
		$('#publicize-form').slideDown( 'fast', function() {
			wpasTitle.focus();
			if ( !wpasTitle.text() ) {
				var url = $('#shortlink').size() ? $('#shortlink').val() : '';
```

**Comment by paulschreiber** [comment]
Also spotted in gravatar-hovercards, likes, jetpack-related-posts.

**Comment by kraftbj** [comment]
I think your report in #3785 is valid too: https://github.com/Automattic/jetpack/blob/127f0fe6778eb14af3802ecef51f8f52c4fb9d72/modules/after-the-deadline/atd-nonvis-editor-plugin.js#L113

I'll make this a master thread to track PRs to update. Thanks!

**Comment by kraftbj** [comment]
Per https://api.jquery.com/size/ , swapping out `size()` for `length` should return the same results.  Deprecated as of jQuery 1.8, which merged into Core 4 years ago https://core.trac.wordpress.org/changeset/21590/ . No issue with swapping over and our supported version set.
