### ISSUE TITLE
VideoPress: Add Ability to Make Videos Clickable with Link

### ISSUE THREAD

**Issue by kelasante** [Automattic/jetpack#37912]
### Impacted plugin

VideoPress

### What

Ability to add links to videos 

### How

User on 8297353-zen, has a portfolio site with VideoPress videos. They would like a feature that allows them to add links to uploaded videos so that users can click on the video and be redirected to a specific page. 

It looks like third-party page builders, and plugins that have lightbox settings for videos have this feature.

**Comment by jeherve** [comment]
I'm not quite sure I understand. Where would the link be displayed? In a description below the video, like in the video description on YouTube?

**Comment by kelasante** [comment]
> I'm not quite sure I understand. Where would the link be displayed? In a description below the video, like in the video description on YouTube?

Thanks for taking a look at this user feature request. The link would not be displayed, but instead, it would be linked to the video so you could click on the video and be redirected to the linked page. Similar to adding links to images. 
<img width="1070" alt="Markup 2024-06-18 at 13 21 45" src="https://github.com/Automattic/jetpack/assets/74204272/486c52eb-b35a-486b-8fa3-7239c50ca24e">


For the user specifically, they have videos on loop with no controls showing and they want the video to be redirected to a page when you click on it. 

Not sure if this causes any accessibility issues or if this can be done since the standard setting is to pause the looped video when clicked on. Maybe if there is a link, then the video gets redirected to the page instead of being paused?

**Comment by jeherve** [comment]
Ah, I see what you mean, thanks for clarifying. It would indeed be quite confusing to have a video behave like a linked image. When clicking on a video, one would expect the video to play, and would not expect for a new page to load.

If you'd like to have clickable looped videos, I would recommend creating animated GIFs instead. Such images can be clickable, and can then lead to another page.
