### ISSUE TITLE
Enhancement: Caching of get_ai_assistance_feature function

### ISSUE THREAD

**Issue by mdbitz** [Automattic/jetpack#37936]
### Impacted plugin

Jetpack

### What

Expand the AI Assistance feature Cache Timeout

### How

The cache time on get_ai_asistance_feature function is too short and contributes to a large number of public-api requests. 

Please review the timeout (currently 10 seconds) and increase to a reasonable value.

In addition non 200 responses need to be cached to minimize public-api calls to WP.com
see line 423 of lib/class-jetpack-ai-helper.php. These should possibly have longer timeout lengths to ensure to minimize traffic if WP.com is unable to respond to requests.

**Comment by anomiex** [comment]
> These [non-200 response caches] should possibly have longer timeout lengths to ensure to minimize traffic if WP.com is unable to respond to requests.

Error caching is a hard one to balance. While hammering a struggling server isn't good, you also don't want a transient error from the server to turn into a long outage on the client due to the error being cached.

**Comment by CGastrell** [comment]
@mdbitz  A couple things we can do here:

- extend the transient/cache for 200 responses to 60 seconds. It could be longer, but we need to consider the roundtrip to checkout as a max, so free users don't get stuck with the cached response after purchasing an upgrade
- keep a transient/cache of 10 seconds for errors, allowing for a faster recovery
- extend timeout for slow connections (?), but I'm unaware of the default value there. Would 30 seconds timeout be too much?
