### ISSUE TITLE
Super Cache: Do not show admin migration notice if using an outdated version of Boost

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#37932]
If a site is running a particularly old version of Boost that doesn't have the Cache module, we should not show the admin notice that recommends migrating.

That notice enables the Cache module which will do nothing on an old version of the plugin.

**Comment by dilirity** [comment]
Note - we added the cache module in 3.1.1 - https://github.com/Automattic/jetpack-boost-production/releases/tag/3.1.1

**Comment by pyronaur** [comment]
Done in #37963
