### ISSUE TITLE
My Jetpack : 404/400 requests to json api when Jetpack is disconnected.

### ISSUE THREAD

**Issue by mdbitz** [Automattic/jetpack#37935]
### Impacted plugin

Jetpack

### Quick summary

When Jetpack is activated but not connected the My Jetpack page is making unnecessary API calls repeatedly.

If no connection exists there should not be any api requests to load data. In addition the code needs to be hardened so that it recognizes 400 and 404 responses and does not attempt to retry the requests.

 

### Steps to reproduce

1. Install and Activate jetpack
2. Visit the wp-admin
3. open Dev Tools to the "network" tab
4. Visit My Jetpack

![image](https://github.com/Automattic/jetpack/assets/5784663/2da9dff1-b1c5-4353-91f3-4ea6e5e050f4)

### A clear and concise description of what you expected to happen.

When Jetpack is activated but not connected we should not be making these api requests. At a minimum we should only be making them once.

### What actually happened

4 requests are triggered that return 404/400 responses. These requests are retried twice for a total of 12 requests.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

**Comment by obenland** [comment]
@BogdanUngureanu Are you still working on this?

**Comment by BogdanUngureanu** [comment]
@obenland I forgot to remove myself from the assignees, sorry!

**Comment by rcrdortiz** [comment]
Shipped a fix for this issue.
