### ISSUE TITLE
Contact Form: Thank You Message and/or redirect URL

### ISSUE THREAD

**Issue by chad1008** [Automattic/jetpack#3794]
There are times when users want to send users to a secondary page after a form is submitted - a PDF they're giving away, or simple thank you page, or at the very least have a customized message display along with the 'message sent' notification so they can customizer their visitor's experience.

This came up in 372933-chat recently

**Comment by jeherve** [comment]
This is already possible via the `grunion_contact_form_redirect_url` filter, as explained here:
https://jetpack.com/2016/03/18/hook-of-the-month-customizing-contact-forms/
