### ISSUE TITLE
VideoPress: Missing script dependency for `videopress-editor-view`

### ISSUE THREAD

**Issue by ocean90** [Automattic/jetpack#3799]
Since https://github.com/Automattic/jetpack/commit/0d10323a12959b19e6d91fbc628db8be4d3e7f90 `editor-view.js` is using `wp.media.coerce`, but the script handle doesn't define `media-editor` as a dependency, see https://github.com/Automattic/jetpack/blob/bd639c2bf4d68e9fcf31b775dbc6bcd8535c3a92/modules/videopress/shortcode.php#L153.

#### What I expected
No JavaScript errors.

#### What happened instead
A JavaScript error occurs on wp-admin/post.php:
```
Uncaught TypeError: Cannot read property 'coerce' of undefined
https://make.wordpress.org/core/wp-content/plugins/jetpack/modules/videopress/js/editor-view.js?ver=4.6-alpha-37439 line 17
```

#### Steps to reproduce the issue
* Activate the VideoPress module
* Add `define('SCRIPT_DEBUG', true);` to wp-config.php
* Edit a post

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/v-402-causes-tinymce-editor-problems-for-contributor-role-w-shortcode-embeds

**Comment by Lewiscowles1986** [comment]
A solution to this is on #4044 use-it, don't use it. I couldn't care less
