### ISSUE TITLE
Blaze unable to handle non-200 api responses

### ISSUE THREAD

**Issue by nickpagz** [Automattic/jetpack#38030]
### Impacted plugin

None / Other

### Quick summary

In the `get_blaze_posts()` method, the API response is [handled here](https://github.com/Automattic/jetpack/blob/64517a4d93245a6492c5f65a270c627f1068fdf3/projects/packages/blaze/src/class-dashboard-rest-controller.php#L341-L355). It only checks if the response is a WP_Error. However, in the `request_as_user()` method, the check for [non-200 responses](https://github.com/Automattic/jetpack/blob/64517a4d93245a6492c5f65a270c627f1068fdf3/projects/packages/blaze/src/class-dashboard-rest-controller.php#L829-L831) gets a [WP_REST_Response](https://github.com/Automattic/jetpack/blob/64517a4d93245a6492c5f65a270c627f1068fdf3/projects/packages/blaze/src/class-dashboard-rest-controller.php#L876) in the `get_blaze_error()` method. As a result, this causes a fatal error when the response is not a 200:

```
PHP message: Fatal error: Uncaught Error: Cannot use object of type WP_REST_Response as array in /var/www/wp-content/mu-plugins/jetpack-13.5/jetpack_vendor/automattic/jetpack-blaze/src/class-dashboard-rest-controller.php:351
```

### Steps to reproduce

I'm not able to replicate at will as I'm unsure how to trigger a non-200 response. I came across this issue on plugin installation on helloyumi.com. A thread exists here: p1719257216906619-slack-C06SG526V6X

### A clear and concise description of what you expected to happen.

I expected no PHP fatal messages in the error logs.

### What actually happened

PHP fatal messages in the error logs.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

VIP

**Comment by jeherve** [comment]
@sbarbosa @therocket-gr Do you think you could take a look at this?

Thank you!
