### ISSUE TITLE
Admin Page: Sidebar overlays admin page on tablet layout

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#3815]
When I set my viewport size to something like 820 px I see this:

![screen shot 2016-05-16 at 8 36 05 pm](https://cloud.githubusercontent.com/assets/1126811/15308768/536ac5c8-1ba6-11e6-9125-3eccad8c6dad.png)

If I click the button to expand the sidebar, I see this:

![screen shot 2016-05-16 at 8 36 23 pm](https://cloud.githubusercontent.com/assets/1126811/15308782/6857a49c-1ba6-11e6-982a-1ba282e1dad2.png)

#### What I expected

I would expect the sidebar not to overlay the Jetpack admin page. Notice how a regular WordPress admin page looks:

![screen shot 2016-05-16 at 8 41 19 pm](https://cloud.githubusercontent.com/assets/1126811/15308806/9d6dfd20-1ba6-11e6-8703-1ebcc72e56ad.png)

**Comment by jeffgolenski** [comment]
@ebinnion eek. good find. I also discovered this is an issue with the current jetpack dashboard as well. Digging into it!

<img width="932" alt="screen shot 2016-05-20 at 5 07 48 pm" src="https://cloud.githubusercontent.com/assets/214813/15442056/a6f62fa8-1eac-11e6-8710-b138ba8673ba.png">

**Comment by jeffgolenski** [comment]
Just making a note. Found the problem, will revisit soon. We have a style that's overriding a core style that gives `wpcontent` a shorter left margin

<img width="1225" alt="screen shot 2016-05-20 at 5 31 09 pm" src="https://cloud.githubusercontent.com/assets/214813/15442542/e8f589d2-1eaf-11e6-8d6e-d3c75f6246de.png">
