### ISSUE TITLE
Site stats not tracking clicks on shortened external url's

### ISSUE THREAD

**Issue by Lozula** [Automattic/jetpack#3817]
#### What I expected

I have a website with a number of shortened links to Amazon, using the Amazon link shortener which creates an "amzn.to" shortened url. I expect to be able to track these clicks in the Jetpack site stats page, under the "clicks" area.

When clicked on, these links don't appear in the external clicks report.

#### What happened instead

I don't think any shortened link shows up in the external clicks report.

#### Steps to reproduce the issue

Add shortened URL to blog post
Click external URL
Visit site stats page, see no clicks being tracked to shortened URL's

**Comment by jeherve** [comment]
Some URL shorteners indeed won't appear in your stats' clicks and referrer sections. This doesn't happen for all shortlinks, but will happen for shortlinks that are known to be used to insert malicious / spam links in stats.

If you'd like to track those links on your site, I'd suggest that you use a different URL shortener. You can use a tool like [Bitly](https://bitly.com/pages/tour) or [Yourls](https://yourls.org/) to use your own custom domain, for example.

**Comment by samiff** [comment]
@jeherve Just wanted to clarify if not tracking any `amzn.to` click stats is intentional then? Also if you happen to know where that is done, it'd be much appreciated thanks!

**Comment by jeherve** [comment]
@samiff That's correct.

Internal reference: p10gg3-2pj-p2
