### ISSUE TITLE
Enhancement: Add Learn.WordPress.org data to sync

### ISSUE THREAD

**Issue by adamwoodnz** [Automattic/jetpack#38186]
### Impacted plugin

None / Other

### What

New taxonomy and post meta added to sync to fix search

### How

Hi, we're currently building a new theme for Learn.WordPress.org and some specific searches aren't working. The site uses Jetpack search. These problems are summarised in 2 issues:

1. [Learning Pathway searches broken](https://github.com/WordPress/Learn/issues/2576)
2. [Filtering search results by language is broken](https://github.com/WordPress/Learn/issues/2577)

I've read that the first one might not be working due to data not getting pushed to the ES index because the taxonomy isn't listed in `mu-plugins/jetpack/sync/class.jetpack-sync-module-search.php`, however I'm not able to view that file. We're interested in getting the [`learning-pathway` taxonomy](https://github.com/WordPress/Learn/blob/trunk/wp-content/plugins/wporg-learn/inc/taxonomy.php#L535) added if that is the cause though.

The other field which is problematic is filtering a search on a [post meta field `language`](https://github.com/WordPress/Learn/blob/trunk/wp-content/plugins/wporg-learn/inc/post-meta.php#L195).

Please comment on the issues directly if that's better. Thanks in advance.

**Comment by darssen** [comment]
Hi!
> I've read that the first one might not be working due to data not getting pushed to the ES index because the taxonomy isn't listed in mu-plugins/jetpack/sync/class.jetpack-sync-module-search.php, however I'm not able to view that file. We're interested in getting the [learning-pathway taxonomy](https://github.com/WordPress/Learn/blob/trunk/wp-content/plugins/wporg-learn/inc/taxonomy.php#L535) added if that is the cause though.

You can follow the steps in the following link pcNPJE-182-p2 to add the taxonomy.

> The other field which is problematic is filtering a search on a post meta field language.

Folks from @Automattic/jetpack-reach should be able to help with this one.

**Comment by adamwoodnz** [comment]
Thanks for responding

> You can follow the steps in the following link pcNPJE-182-p2 to add the taxonomy.

Sorry, but was there supposed to be a link here @darssen?

**Comment by jeherve** [comment]
> was there supposed to be a link here

@adamwoodnz I've reached out in Slack to help with that!

**Comment by adamwoodnz** [comment]
Closing this as I've received help on the linked issues, thanks!
