### ISSUE TITLE
Tabindex of 6 on the "Notify me of new comments via email" subscribe checkbox

### ISSUE THREAD

**Issue by RRWD** [Automattic/jetpack#3819]
Hi, 

Bart Simons reported this issue to me, I hope this is the correct place to file the issue:

On the comment form of wp.com posts there is a checkbox "notify me of new comments”. This checkbox has a tabindex of 6, which is messing up the natural taborder kind of drastically.

```
<input type="checkbox" name="subscribe" id="subscribe" value="subscribe" style="width: auto;" tabindex="6"/>
<label class="subscribe-label" id="subscribe-label" for="subscribe" style="display: inline;">
Notify me of new comments via email.</label>
```
It would be most convenient if this tabindex was just removed.

#### What I expected
A natural tab order

#### What happened instead
The taborder is hijacked by a tabindex  = 6 of the subscribe checkbox

#### Steps to reproduce the issue
Remove the tabindex and everything works fine

**Comment by jeherve** [comment]
Thanks for the report!

Since this is specific to WordPress.com sites, I'll close this issue and have opened a new report on our internal bug tracker (7743-wpcom) to track this. We'll get it fixed, and I'll comment again here as soon as this is fixed.

**Comment by RRWD** [comment]
@jeherve thank you :-)

**Comment by jeherve** [comment]
@RRWD tabindex was removed.
