### ISSUE TITLE
Where is devicepx-jetpack.js located on github?

### ISSUE THREAD

**Issue by zcuric** [Automattic/jetpack#3820]
#### What I expected
I was expecting to find `devicepx-jetpack.js` on github to make a contribution to fix a small issue regarding adding `zoom` query var if the `resize` query var is present.

#### What happened instead
I couldn't find it.

#### Steps to reproduce the issue
Search `Automattic/jetpack` for `devicepx-jetpack.js`

**Comment by kraftbj** [comment]
It isn't on GitHub; it's hosted on WP.com. You can drop the patch here and I'll relay it to the internal Trac.
