### ISSUE TITLE
PHP8.4 alpha 1 warnings - nullable is deprecated, the explicit nullable type must be used instead

### ISSUE THREAD

**Issue by ipajen** [Automattic/jetpack#38226]
### Impacted plugin

Protect

### Quick summary

PHP warning in PHP 8.4 alpha 1.

`Deprecated: Automattic\Jetpack\Connection\Manager::setup_xmlrpc_handlers(): Implicitly marking parameter $xmlrpc_server as nullable is deprecated, the explicit nullable type must be used instead in C:\wamp64\www\wp\wp-content\plugins\jetpack-protect\jetpack_vendor\automattic\jetpack-connection\src\class-manager.php on line 171`

[nullable-deprecated](https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated)

### Steps to reproduce

1. Use PHP 8.4 alpha 1 and WordPress 6.5 RC2 with Debug enabled
2. Install and activate plugin Jetpack Protect 2.2.0

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

### Environment
- WordPress: 6.6-RC2
- PHP: 8.4.0alpha1
- Server: Apache/2.4.59 (Win64) PHP/8.4.0alpha1 mod_fcgid/2.3.10-dev
- Database: mysqli (Server: 8.3.0 / Client: mysqlnd 8.4.0alpha1)
- Browser: Edge 126.0.0.0 (Windows 10/11)
- Theme: Twenty Twenty-Four 1.1
- MU-Plugins:
- Plugins:
  * Jetpack Protect 2.2.0
  * WordPress Beta Tester 3.5.5

**Comment by anomiex** [comment]
We're already aware of this, but we've decided not to do anything about it until we drop support for PHP 7.0 since it's not possible to use `?Class` in that version. At the latest that will come when WordPress 6.7 is released, at which time we'll drop support for WordPress 6.5.

**Comment by fgiannar** [comment]
@anomiex Thanks for the update! If that's the case I guess we can remove it from Vulcan's board and add it in Garage's one as a future task to serve as a reminder?

**Comment by anomiex** [comment]
That works, although I may forget this task exists when I fix the issue as part of the general dropping of PHP 7.0 and 7.1 support and/or enabling 8.4 in CI. 😀

Once we drop 7.0 we can remove what #36673 added to `.github/files/phpcompatibility-dev-phpcs.xml` and then CI will have us fix all these.

**Comment by jeherve** [comment]
@anomiex I created #38296 so we can keep track of all those. Feel free to add to it.

**Comment by tbradsha** [comment]
Resolved in #40147.
