### ISSUE TITLE
Jetpack Stats: Legacy Commercial Plans Show 1 View Available

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#38238]
### Impacted plugin

Jetpack

### Quick summary

When a user has a legacy Jetpack Stats Commercial package (before tiers), the plan displays as only having "1 views per month" on WordPress.com

### Steps to reproduce

1. Add a Jetpack Stats Commercial plan (without tiers)
2. View the plan at https://wordpress.com/me/purchases

### A clear and concise description of what you expected to happen.

The views should show as unlimited or not be displayed

### What actually happened

![Annotation on 2024-07-08 at 10-35-03](https://github.com/Automattic/jetpack/assets/45246438/d46090a6-4d89-4c50-85ec-03d7cf50df2a)

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by bobmatyas** [comment]
This is similar to https://github.com/Automattic/jetpack/issues/38237

**Comment by fgiannar** [comment]
@Automattic/jetpack-martech Should we add this issue in your maintenance board so it gets triaged?

**Comment by robertsreberski** [comment]
@fgiannar Adding this one as well, we'll handle it both with the same PR (that is almost ready - https://github.com/Automattic/wp-calypso/pull/92528).
