### ISSUE TITLE
My Jetpack: Jetpack AI Card Links to Dead-end with Legacy Plan

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#38239]
### Impacted plugin

Jetpack

### Quick summary

If a user has a legacy Jetpack AI Assistant plan, clicking on the "View" button in the AI card on My Jetpack leads to a dead-end (see screenshot below)

### Steps to reproduce

1. Add a Jetpack AI Assistant plan (non-tiered)
2. Click the "View" button on the AI card in My Jetpack

### A clear and concise description of what you expected to happen.

I would expect the user to be taken to a screen like this:

![Screenshot on 2024-07-08 at 10-49-08](https://github.com/Automattic/jetpack/assets/45246438/4be9a9c5-817f-427c-8431-cfb23c821785)

### What actually happened

Clicking "View" brings a user to this screen:

![Screenshot on 2024-07-08 at 10-47-44](https://github.com/Automattic/jetpack/assets/45246438/2c63000e-d891-43ca-8d98-66f291dd0685)

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by fgiannar** [comment]
@Automattic/jetpack-martech Should we add this issue in your maintenance board so it gets triaged?

**Comment by robertsreberski** [comment]
@fgiannar Thanks for the ping! I'm adding that one to our board.

**Comment by robertsreberski** [comment]
Hello @bobmatyas !

I'm struggling to recreate the issue on my side:
1. I create a plain JN site
2. Add "Jetpack AI Monthly USD 2023-05-17" non-tiered plan to it

![Image](https://github.com/user-attachments/assets/59b8a679-f9f2-44da-b4f6-039c10b186a9)

3. Go to My Jetpack and click "View" on Jetpack AI card
4. I'm presented the following (correct) view:

![Image](https://github.com/user-attachments/assets/96e78c74-eaab-496b-af95-87055803e229)


Could you confirm the issue still persists for you? Thank you!

**Comment by bobmatyas** [comment]
@robertsreberski Sorry for missing the ping here. It looks like this is no longer happening. I'll close this out.
