### ISSUE TITLE
Admin Page: 3 Akismet calls on page load

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3824]
When loading Jetpack's new Admin Page, 3 Akismet calls are made:
- https://MY_KEY.rest.akismet.com/1.1/verify-key
- https://MY_KEY.rest.akismet.com/1.1/get-stats, `[body] => blog=http%3A%2F%2Fmysite.com&key=MY_KEY&from=6-months`
- https://MY_KEY.rest.akismet.com/1.1/get-stats, `[body] => blog=http%3A%2F%2Fmysite.com&key=MY_KEY&from=all`
  
  Could we reduce this to 2 calls, or do the 2 last calls have to be made separately?

**Comment by dereksmart** [comment]
We should be able to cut this down to just two.  Love that you're checking the http requests :) :)

**Comment by dereksmart** [comment]
This no longer happens on the /dashboard nor /settings routes.
