### ISSUE TITLE
Clarify Language for Newsletter Settings

### ISSUE THREAD

**Issue by foleynotrose** [Automattic/jetpack#38260]
### Impacted plugin

Jetpack

### What

Clarify what toggling "Let visitors subscribe to this site" on/off does

### How

If I have already activated the Jetpack Newsletter in the past, and I want to update the settings so that new posts no longer trigger an email to be sent, it is not clear to me that toggling this setting off will do that: 

<img width="612" alt="Screenshot 2024-07-09 at 15 17 15" src="https://github.com/Automattic/jetpack/assets/26651984/4fdf5a17-5eff-4303-a449-bc5a649e6e99">

 Perhaps this language can be clarified so that people know turning it off will prevent all subscription emails from being sent in the future. 

Maybe something like: 

> Let visitors subscribe to this site and send emails to your subscribers when you publish a post.

**Comment by pkuliga** [comment]
It makes sense!

@crisbusquets WDYT?

**Comment by crisbusquets** [comment]
> It makes sense!
> 
> @crisbusquets WDYT?

Works for me! Thanks for the ping :) and thanks @foleynotrose for the suggestion.

**Comment by pkuliga** [comment]
What about the copy?

"Let visitors subscribe to this site and receive emails when you publish a post." feels a bit more clear to me instead of "Let visitors subscribe to this site and send emails to your subscribers when you publish a post."?

**Comment by crisbusquets** [comment]
I don't have a strong opinion. Both options seem clear to me, although I lean towards the shortest version possible.

**Comment by foleynotrose** [comment]
> "Let visitors subscribe to this site and receive emails when you publish a post." feels a bit more clear to me instead of "Let visitors subscribe to this site and send emails to your subscribers when you publish a post."

yes, that's probably better. i _think_ it gets across the message that toggling this setting to OFF will STOP sending out emails.
