### ISSUE TITLE
Admin: add welcome notices

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#3831]
- [x] after brand new connection
- [x] after Jumpstart

**Comment by jeffgolenski** [comment]
Once the global notice functionality is built in, we'll use one to display a short, but sweet welcome message after jumpstart, that'll look something like this:
![notices-context-helper](https://cloud.githubusercontent.com/assets/214813/15441913/bb9aa52a-1eab-11e6-89a8-00ce1cab3b6a.jpg)

**Comment by jeffgolenski** [comment]
Will be fixed in: https://github.com/Automattic/jetpack/pull/3974
