### ISSUE TITLE
Jetpack: Multisite License Activation Error has Typo

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#38324]
### Impacted plugin

Jetpack

### Quick summary

When getting an error about activating a Jetpack plan on unsupported multisite, the error has a typo due to encoding issues:

> Jetpack: [multisite_incompatibility] We&#039;re sorry, Jetpack Complete is not compatible with multisite WordPress installations at this time.

### Steps to reproduce

1. Purcahse a siteless JP Complete plan
2. Try to activate a license on a multisite WordPress install
3. See the typo

### A clear and concise description of what you expected to happen.

Character encoding should work properly

### What actually happened

![Annotation on 2024-07-12 at 14-42-05](https://github.com/user-attachments/assets/f7a31a1d-985a-4566-b4dd-5adccf5a1686)

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by jeherve** [comment]
Fixed in D155225-code

<img width="574" alt="image" src="https://github.com/user-attachments/assets/801249ab-cd62-47b1-ba11-2678fab85810">
