### ISSUE TITLE
WP Super Cache: call to undefined function is_utf8_charset() in WordPress 6.6

### ISSUE THREAD

**Issue by tom-knight** [Automattic/jetpack#38358]
### Impacted plugin

Super Cache

### Quick summary

Update to WordPress 6.6 gives `Call to undefined function is_utf8_charset()` error when Super Cache enabled.

I'm unable to share a URL due to company policy.

### Steps to reproduce

1. Visit site with Super Cache enabled and updated to WordPress 6.6.

### A clear and concise description of what you expected to happen.

Blog homepage should display

### What actually happened

Error shown (see below)

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

Disabling the cache removes the error but is far from ideal.

Error message shown (I've blanked out the path):

```
Fatal error: Uncaught Error: Call to undefined function is_utf8_charset() in /----------/wp-includes/compat.php:179
Stack trace:
#0 /----------/wp-includes/compat.php(152): _mb_strlen('<!DOCTYPE html>...', '8bit')
#1 /----------/wp-content/plugins/wp-super-cache/wp-cache-phase2.php(268): mb_strlen('<!DOCTYPE html>...', '8bit')
#2 /----------/wp-content/plugins/wp-super-cache/wp-cache-phase1.php(194): wp_cache_serve_cache_file()
#3 /----------/wp-content/advanced-cache.php(22): include_once('/----------/...')
#4 /----------/wp-settings.php(97): include('/----------/...')
#5 /----------/wp-config.php(102): require_once('/----------/...')
#6 /----------/wp-load.php(50): require_once('/----------/...')
#7 /----------/wp-blog-header.php(13): require_once('/----------/...')
#8 /----------/index.php(17): require('/----------/...')
#9 {main} thrown in /----------/wp-includes/compat.php on line 179
```

**Comment by tom-knight** [comment]
Clearing the cache did not make any difference.

**Comment by tom-knight** [comment]
WP Super Cache  1.12.3

**Comment by slyall** [comment]
I got the same error. Fixed by disabling Wp Super Cache

This appears to be the change that probably caused this:

https://core.trac.wordpress.org/ticket/61182

```
[Wed Jul 17 10:48:12.068500 2024] [php:error] [pid 3188270] [client 1.1.1.1:38506]
PHP Fatal error: Uncaught Error: Call to undefined function is_utf8_charset() in html/wp-includes/compat.php:179\n
Stack trace:\n
#0 html/wp-includes/compat.php(152): _mb_strlen()\n
#1 html/wp-content/plugins/wp-super-cache/wp-cache-phase2.php(268): mb_strlen()\n
#2 html/wp-content/plugins/wp-super-cache/wp-cache-phase1.php(194): wp_cache_serve_cache_file()\n
#3 html/wp-content/advanced-cache.php(22): include_once(‘…’)\n
#4 html/wp-settings.php(97): include(‘…’)\n
#5 html/wp-config.php(77): require_once(‘…’)\n
#6 html/wp-load.php(50): require_once(‘…’)\n
#7 html/wp-blog-header.php(13): require_once(‘…’)\n
#8 html/index.php(17): require(‘…’)\n
#9 {main}\n thrown in html/wp-includes/compat.php on line 179`\
```

**Comment by luckcfm** [comment]
Im having the same issue as well. Disabling WP Super Cache made my site back up!

**Comment by donnchawp** [comment]
Thanks for reporting this. This is caused by a small bug in WordPress introduced when `is_utf8_charset()` was moved around. I'll get a compatibility fix in place, but it will hopefully be fixed in the next release of WP too.

**Comment by donnchawp** [comment]
FYI - You can also fix it by installing the mbstring extension on your webserver. 
https://www.php.net/manual/en/mbstring.installation.php

**Comment by donnchawp** [comment]
If you disable compression in the plugin that will probably fix it too, until we get a fix out.

**Comment by dmsnell** [comment]
Core-61680 Tracking in Core

**Comment by slyall** [comment]
Upgraded to the new Super Cache 1.12.4 and that is working with no errors. 
Thank you for the very quick fix.

**Comment by tom-knight** [comment]
Great, I can confirm this is working for me too on version 1.12.4. Thanks for the quick fix.

**Comment by maiorano84** [comment]
We got hit with this one too. Upgrading did not immediately fix the issue, but once we deleted the server cache everything was fine.
