### ISSUE TITLE
Newsletter: Enhance email preview

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/jetpack#38370]
Last year we launched the ability to send email previews: https://github.com/Automattic/jetpack/pull/31021 .

If we compare it it to our competitors, our current solution is far from ideal.

How we can improve it?

**P2 with more context**: peKye1-Wa-p2

**Comment by crisbusquets** [comment]
P2 with design i1 posted here: p1HpG7-tAi-p2

**Comment by simison** [comment]
i2 designs p1HpG7-tEm-p2

**Comment by StefMattana** [comment]
@crisbusquets 👋 I see this is going on today's [JP 13.7 release](https://github.com/Automattic/jetpack-production/blob/trunk/CHANGELOG.md). Is there anything we should document for the customers to know? I don't see any documentation request but I thought of asking anyway. Thanks!

**Comment by simison** [comment]
Nope, this is still behind a feature flag.

@lezama can give heads up before this will be released [with dotcom](https://github.com/Automattic/en.support-docs-content/issues) and I put this to the Jetpack happiness inbox meanwhile, too.

**Comment by crisbusquets** [comment]
Wrap-up post: p1HpG7-tIv-p2

**Comment by foleynotrose** [comment]
@StefMattana i know this is already on your radar... not sure when it got added to our inbox; i might have missed the review last week.

**Comment by StefMattana** [comment]
@foleynotrose Not sure if I assigned it to myself or you did it, but the most important thing is that it's here: https://github.com/orgs/Automattic/projects/702/views/12?sliceBy%5Bvalue%5D=Stef+Mattana
:)

**Comment by lezama** [comment]
🙌
