### ISSUE TITLE
Form block: Unexpected Contact Form Checkbox Block Size on Twenty Twenty and Twenty Twenty One

### ISSUE THREAD

**Issue by mxhassani** [Automattic/jetpack#38392]
### Quick summary

Adding a contact form checkbox anywhere shows a rectangular shape instead of a square:

![image](https://github.com/user-attachments/assets/759536b4-46e5-4827-ab00-61a17d4aeb1f)

### Steps to reproduce

1. Create any new post/page.
2. Add a Form block
3. In that form, add a Checkbox block.

### What you expected to happen

To see a square shape:

![image](https://github.com/user-attachments/assets/a632cf2f-ae79-4ea3-956f-a5e6a3390bf6)

### What actually happened

The shape is rectangular

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Context

8473493-zen

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Other notes

It appears to be caused by this CSS: 

```
.contact-form .grunion-field {
  padding-left:max(var(--jetpack--contact-form--input-padding-left,16px),var(--jetpack--contact-form--border-radius));
  padding-right:max(var(--jetpack--contact-form--input-padding-left,16px),var(--jetpack--contact-form--border-radius))
}
.contact-form input[type="checkbox"], .contact-form input[type="radio"] {
  height: 1rem;
}
```

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

CSS:
```
/* Fix checkbox size */
.contact-form input[type="checkbox"].grunion-field {
  padding: 0;
  height: 1.5rem;
}
```

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- I'm able to reproduce this as well on self-hosted, and with the Twenty Twenty One theme:
![checkbox-twenty-twenty-one](https://github.com/user-attachments/assets/efbdbd1e-e67e-49ac-b0b1-37da173e4509)

📌 ACTIONS
- Triaged
- Transferred to the Jetpack repo.
- Expanded steps to reproduce to make it more clear.

📌 Message to Author
Thansk for reporting this, @mxhassani! I'm moving this one to the Jetpack repo, as it seems the CSS is coming from the plugin, and is not dotcom specific.
