### ISSUE TITLE
Post by email signature stripping is too greedy

### ISSUE THREAD

**Issue by fncll** [Automattic/jetpack#384]
Post by email is resulting in truncated posts at the first instance of
 multiple hyphens. This is particularly problematic if one uses Markdown
 formatting.

 Not all the time, but in predictable cases.

 For instance, the following email message results in a post truncated
 after line 1:

```
A header
--------

Then some more
```

Similarly, the following gets truncated at the first "row" divider of hyphens:

```
A markdown table

| Fruit       | Color           | Note        |
| ----------- | --------------- | ----------- |
| Bananas     | Yellow          | Monkeys!    |
```

 Note: not ALL instances of multiple hyphens are problematic, the following
 email post works fine:

```
Some stuff followed by a hard rule

---

Bam.
```

I assume this is related to the code to delete email signatures. However,
 multiple hyphens occur in markdown text frequently (headers, hard rules,
 em and en dashes, etc), and Markdown is an explicit option with Jetpack!

Seems to me the best option would be for signature stripping to be limited to ONLY two dashes at the BEGINNING of a line followed by an EOL and leave other instances alone.

**Comment by kraftbj** [comment]
I'm open to this, the suggestion is atomic enough and logical. It is, though, not on our current roadmap. Moving to vFuture.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
