### ISSUE TITLE
wp_insert_post No such file or directory’

### ISSUE THREAD

**Issue by Enkirch** [Automattic/jetpack#38404]
### Impacted plugin

Super Cache

### Quick summary

When I create a post, you seem to try to delete something that is not there. Since the post has just been created.

### Steps to reproduce

This Code 

       $my_post = array(
            'post_title'   => $label, // Label wird als Titel verwendet
            'post_name'    => $titelform, // Titelform wird als Slug verwendet
            'post_status'  => 'publish',
            'post_type'    => 'manufacturer'
        );

        $result = wp_insert_post($my_post);

end in this error 

{key: ‘9225f6221f2528d68389b274d5f16ba5’, type: ‘warning’, message: ‘rmdir(D:\\xampp-8-1-25\\htdocs\\xxxx/wp-content/cache…ost/xxxx/marke/vespa/): No such file or directory’, file: ‘wp-content/plugins/wp-super-cache/wp-cache-phase2.php’, line: 3209, …}
component: “Plugin: wp-super-cache”
file: “wp-content/plugins/wp-super-cache/wp-cache-phase2.php”
key: “xxxxx”
line: 3209
message: “rmdir(D:\\xampp-8-1-25\\htdocs\\xxxx/wp-content/cache/supercache/localhost/xxxx/marke/vespa/): No such file or directory”
stack: (9) [‘rmdir()’, ‘wp_cache_post_id_gc()’, ‘wp_cache_post_change()’, ‘wp_cache_post_edit()’, “do_action(‘clean_post_cache’)”, ‘clean_post_cache()’, ‘wp_insert_post()’, ‘import_manufacturer_from_acf_list_callback()’, “do_action(‘wp_ajax_import_manufacturer_from_acf_list_callback’)”]
type: “warning”

The path “D:\xampp-8-1-25\htdocs\xxxx/wp-content/cache/” ist existing and caching is working. the post is also created without any problems

### A clear and concise description of what you expected to happen.

That no attempt is made to delete a non-existent file and that no error message appears.

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by donnchawp** [comment]
Forum thread: https://wordpress.org/support/topic/wp_insert_post-9/

I think this might be an XAMPP issue with how it logs warnings and errors. This [comment](https://www.php.net/manual/en/language.operators.errorcontrol.php#85042) on the PHP errorcontrol page says that suppressing a command sets the "reporting level to 0" so no warnings or errors should be reported.
The error shown in the logs is a custom one, so perhaps XAMPP is using `error_get_last` to return the last warning, even if it's supposed to be ignored.

**Comment by Enkirch** [comment]
For completeness. the error was actually only shown to me in “Query Monitor - The developer tools panel for WordPress” plugin, not in the debug.log of WordPress itself.

If I search in the plugin for error_get_last I even find 2 places where this is used.  

Apparently you can turn this off if you define something in the wp-config.

Thank you very much for your effort!
