### ISSUE TITLE
Feature Request: Allow All AI Features to be Disabled

### ISSUE THREAD

**Issue by soatok** [Automattic/jetpack#38427]
### Impacted plugin

Jetpack

### What

I would like to be able to disable all AI features, permanently.

### How

![generate-with-ai-2](https://github.com/user-attachments/assets/c673c52a-bcc9-40cb-b6b6-1cb78668d647)
This "Generate with AI" feature is offensive. Please let us remove it through a Preferences setting.

**Comment by jeherve** [comment]
Thank you for the feedback. This is something that's already tracked in #37059. I'll consequently close this issue as duplicate.
