### ISSUE TITLE
Jetpack Contact form: dropdown arrow from the dropdown field missplaced 

### ISSUE THREAD

**Issue by alinclamba** [Automattic/jetpack#38470]
### Impacted plugin

Jetpack

### Quick summary

A user reported that the dropdown arrow in the dropdown field is misplaced. I couldn't fully replicate this issue; however, during my testing, the dropdown arrow appears misaligned for a brief moment when the page loads, but then it corrects itself.

User's screenshot: 
![3JzA4z.png](https://github.com/user-attachments/assets/ec24f2c7-0444-465a-8079-5458706915fa)
From this site: https://www.cscistok.eu/csc-uebersicht/csc-eintragen/

My test site (it's a GIF, wait for the page refresh to see the arrow "movement"):
![Pop1G0.gif](https://github.com/user-attachments/assets/62d50160-8b0e-4808-bb96-58390a8d4d29)

I tested with Jetpack 13.6 similar to the user's plugin version, but also with beta version of 13.7. Tested with Twenty Twenty-Four and Twenty Twenty-Three.

### Steps to reproduce

1. Insert a contact form in a post or page
2. Use the dropdown field
3. Check the contact form on the live site and see the position of the dropdown arrow. 

### Impact

All

### Available workarounds?

No and the platform is unusable

### Logs or notes

Issue has been initially reported here: https://wordpress.org/support/topic/form-block-dropdown-menu-down-arrow-misplaced/#post-17894696

**Comment by jeherve** [comment]
I posted in the thread asking the site owner for more information.

> I was wondering if you could let me know what your Form block layout settings are on this specific page? Do you have custom line height and / or size values for that block?

**Comment by coder-karen** [comment]
Adding a link to this PR comment that was tackling part of this same issue, to note the suggestions there for a future follow up: https://github.com/Automattic/jetpack/pull/40206#issuecomment-2485132681
