### ISSUE TITLE
Widget visibility rules won't apply to HTML block

### ISSUE THREAD

**Issue by shelb-elliott** [Automattic/jetpack#38484]
### Impacted plugin

Jetpack

### Quick summary

When placing an HTML widget with Jetpack's Widget Visibility feature turned on, the visibility rules don't apply. They do, however, apply for other widget types.

### Steps to reproduce

1. Turn on Widget Visibility in Jetpack Settings
2. Go to Appearance > Widgets and add an HTML widget to any area that appears across the site
3. Apply rules such as Show this Widget if page is "Home"
4. Visit the page where it should appear and visit a page where it should not - see that it appears everywhere. 
5. Repeat the process with a paragraph block & see that it obeys the visibility rules

### A clear and concise description of what you expected to happen.

HTML blocks in widgets should obey the visibility rules

### What actually happened

HTML blocks appear on every page/post, regardless of rules.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by jeherve** [comment]
That seems to be a known issue with the HTML block in the block-based widget editor: custom block attributes aren't saved there for that block. This is currently tracked here:
https://github.com/WordPress/gutenberg/issues/35266

I'll consequently close this issue as duplicate. 

Until the root problem is fixed, I would recommend making the HTML block part of group, and applying widget visibility rules to that group. This would allow one to display or hide the HTML block on different pages.
