### ISSUE TITLE
AI Proofread: Remove star for first release

### ISSUE THREAD

**Issue by madebynoam** [Automattic/jetpack#38502]
Some users might want to target a different grade score instead of 8-12. And it's not clear what it is.
Relevant discussions:

puPv3-lot-p2#comment-27666

**Comment by grbicsanja** [comment]
Thred to clarify the task is here:
p1721840488321699-slack-jetpack-ai

**Comment by renatoagds** [comment]
Figma: ySZWRpzAHOrLjFzkoSuYN7-fi-4545_488

**Comment by grbicsanja** [comment]
![image](https://github.com/user-attachments/assets/f413ec0b-f172-4a62-acef-5ec09be4da7c)
