### ISSUE TITLE
Add Support Link to Block Description for Subscriber Login Block

### ISSUE THREAD

**Issue by ktyfuller604** [Automattic/jetpack#38592]
### What

Add a "Learn more" link (similar to https://github.com/Automattic/wp-calypso/issues/67293) that links to the new Subscriber Login block support doc: 

https://wordpress.com/support/wordpress-editor/blocks/subscriber-login-block/

### Why

This will help WordPress.com users easily discover our comprehensive resources on how to use each block in the editor. With these support docs, users can learn about blocks more quickly, figure out the settings themselves, and reduce their likelihood of contacting support for basic editing tasks.

**Comment by simison** [comment]
@pkuliga can you check this one? Should be simple, although I'm not sure we do these links anymore when we moved to block.json where the description is just text, not HTML.
