### ISSUE TITLE
Admin: StatsViews - current view should not be a link color

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#3871]
Minor Issue: At the top of the stats area we have the different view links "days, weeks, months"

![screen shot 2016-05-20 at 7 30 07 pm](https://cloud.githubusercontent.com/assets/214813/15444617/b13d10da-1ec0-11e6-8842-face58ebc667.png)

We just need to make the current view appear as though it's not a link, and more like a "current state" (non-link color)

**Comment by eliorivero** [comment]
How about this?
<img width="769" alt="captura de pantalla 2017-02-09 a las 15 57 06" src="https://cloud.githubusercontent.com/assets/1041600/22798368/74f21738-eee0-11e6-8404-14f86df3ae4e.png">
Or without the underline:
<img width="759" alt="captura de pantalla 2017-02-09 a las 15 58 50" src="https://cloud.githubusercontent.com/assets/1041600/22798412/b6581434-eee0-11e6-9f43-2a1e0f274266.png">
I personally like the one without the underline but the one with the underline is more in line with the nav bar.

Let me know and I'll create a PR with this.

**Comment by jeffgolenski** [comment]
@eliorivero Without the underline please! Nice find. The dark color for the "current page" is pretty standard across the board.

**Comment by eliorivero** [comment]
PR created https://github.com/Automattic/jetpack/pull/6418
