### ISSUE TITLE
Admin: Stats - make best overall day more readable

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#3872]
The date below the total amount of views is in a format that doesn't allow quick visual stats. Would be nice if we could change it from all numerics "year-month-day" to a mix of words and numerics, like "May 5, 2015"

Before:
![screen shot 2016-05-20 at 7 33 43 pm](https://cloud.githubusercontent.com/assets/214813/15444659/1221ce18-1ec1-11e6-92c2-ae525b54400d.png)

After: 
![screen shot 2016-05-20 at 7 36 41 pm](https://cloud.githubusercontent.com/assets/214813/15444688/58dfb874-1ec1-11e6-8171-abe95f815952.png)

**Comment by timmyc** [comment]
Not sure if you all are using moment.js or not, but you can utilize their date i18n shortcuts for that date format as we have done in calypso: https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/stats/all-time/index.jsx#L35

**Comment by dereksmart** [comment]
@timmyc nice yeah we have calypso's i18n [now](https://github.com/Automattic/jetpack/pull/3805)! 💯

**Comment by timmyc** [comment]
Excellent - there was some funky-ness with moment translations getting from glotpress into Calypso - so not sure how you all are pulling in the locale files, but if you use the standard moment.js [codes](http://momentjs.com/docs/#/i18n/) they all should be translated.  So cool to see this happening in JP, nice work!

**Comment by dereksmart** [comment]
> not sure how you all are pulling in the locale files

yeah we're still discussing that for the rest of the strings..  we've been talking about a few options over in p1HpG7-3cy-p2

**Comment by dereksmart** [comment]
fixed in #3894
