### ISSUE TITLE
Admin: Stats - Weird numbers displaying within weeks view

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#3873]
Still seeing some strange number formatting within the weeks view of the stats area within my sandbox.

![screen shot 2016-05-20 at 7 38 03 pm](https://cloud.githubusercontent.com/assets/214813/15444719/a29fcdbe-1ec1-11e6-8a15-4f6031df2349.png)

**Comment by timmyc** [comment]
The API returns date periods for weeks in that format.  In wp-calypso we parse that data out [here](https://github.com/Automattic/wp-calypso/blob/master/client/lib/stats/stats-list/stats-parser.js#L169)
