### ISSUE TITLE
Admin: SectionNav - doesn't function on small screens

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#3874]
I know this is a dops-component, but we're keeping to-do issues here...

The section nav needs a few visual adjustments:

**Search needs to occupy entire space**
![screen shot 2016-05-20 at 7 41 52 pm](https://cloud.githubusercontent.com/assets/214813/15444754/1b96568e-1ec2-11e6-8331-a000f97526a4.png)

Should be:
![screen shot 2016-05-20 at 7 46 19 pm](https://cloud.githubusercontent.com/assets/214813/15444788/b31b1076-1ec2-11e6-9cc1-1eaa470821fa.png)

**"at a glance" link needs visual divider between settings link**
Currently: 
![screen shot 2016-05-20 at 7 43 44 pm](https://cloud.githubusercontent.com/assets/214813/15444764/52896d0c-1ec2-11e6-94c1-542c1672e0e0.png)

Should be: 
![screen shot 2016-05-20 at 7 44 36 pm](https://cloud.githubusercontent.com/assets/214813/15444772/76d3bcf8-1ec2-11e6-99ae-506ad482505a.png)

**Nav isn't visible on smaller screens**

Currently:
![screen shot 2016-05-20 at 7 56 15 pm](https://cloud.githubusercontent.com/assets/214813/15444885/216ff00e-1ec4-11e6-80d0-719d7fc2287a.png)
![screen shot 2016-05-20 at 7 56 59 pm](https://cloud.githubusercontent.com/assets/214813/15444895/38152b30-1ec4-11e6-9ff8-26c48e6e52d5.png)
![screen shot 2016-05-20 at 7 57 29 pm](https://cloud.githubusercontent.com/assets/214813/15444900/41332b72-1ec4-11e6-8333-f9a67cdd3355.png)

**Comment by beaulebens** [comment]
Also: figure out a better approach to "focus/active" state. We need something that works when using keyboard navigation for accessibility purposes, but something that's less visually extreme when using a mouse. The current outline is a bit too much.

![screen shot 2016-05-23 at 7 33 22 pm](https://cloud.githubusercontent.com/assets/108942/15489466/3b78e91e-211d-11e6-9c46-480df9ca73fa.png)

**Comment by beaulebens** [comment]
The same outline issue (above) is also really obvious when opening/closing FoldableCards using the arrow on the right-hand-side.
