### ISSUE TITLE
Admin: DashSectionHeader - elements dont stack on smaller screens

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#3875]
The elements within the `jp-dash-section-header` dont' stack on smaller screens. Note: They seem to function properly within chrome's inspector, but on the iphone 5s (with the latest chrome), I see them improperly:

![photo may 20 19 42 47](https://cloud.githubusercontent.com/assets/214813/15444868/c84fb5cc-1ec3-11e6-8ec8-8b0c535139cf.png)
![photo may 20 19 45 17](https://cloud.githubusercontent.com/assets/214813/15444869/c8525106-1ec3-11e6-94aa-0862d9bb7f9c.png)

In chromes inspector on my macbook:

![screen shot 2016-05-20 at 7 54 57 pm](https://cloud.githubusercontent.com/assets/214813/15444876/e5112e7a-1ec3-11e6-9564-11d860d8ca61.png)

**Comment by dereksmart** [comment]
They do now! https://cloudup.com/cS5t1-jGi-i
