### ISSUE TITLE
Admin: Settings - headlines should be h2s and have a place for descriptions below them

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#3876]
Right now the headers for the different section areas are massive h1s, just need to turn those into smaller h2s:

![screen shot 2016-05-20 at 8 06 21 pm](https://cloud.githubusercontent.com/assets/214813/15444975/a393a76e-1ec5-11e6-8645-43d2c137187e.png)

Should look more like:
(ignore the design of everything here besides the h2 and description)
![screen shot 2016-05-20 at 8 08 45 pm](https://cloud.githubusercontent.com/assets/214813/15444993/d96c9e86-1ec5-11e6-8509-253024133033.png)

**Comment by jeherve** [comment]
#5461

**Comment by dereksmart** [comment]
This is all irrelevant now with the new settings card designs.
