### ISSUE TITLE
Development Mode: Allow “Related Posts” feature with recent/placeholder posts

### ISSUE THREAD

**Issue by phoenixenero** [Automattic/jetpack#3880]
Currently this feature is not enabled on Development Mode. Main reason is that it needs to connect to WordPress.com to analyze the posts for their... "related-ness".

In my opinion, when developing a site in my local dev server, I *really don't care* if the Related Posts section has actual related posts or not. I’m a starting theme developer and I want the Related Posts section to show up so I can style it with my theme. The defaults look nice but I still want it to look unified.

I can work around this by taking one of the WordPress.com sites and copying the “Related Posts” HTML, but it would still be convenient to have that feature built-in.

Showing the Recent Posts is a good enough for development purposes.

**Comment by jubstuff** [comment]
Hello @phoenixenero,
it seems that this is a duplicate of #385

**Comment by phoenixenero** [comment]
Ah, didn't notice. Closing issue in favor of #385
