### ISSUE TITLE
Sharing: inline JS script's comments create issue when page source is minified

### ISSUE THREAD

**Issue by lazharichir** [Automattic/jetpack#3882]
If you look at a single post when sharing is activated, the source code towards the end has some inline Javascript.

`		<script type="text/javascript">
			var windowOpen;
		jQuery(document).on( 'ready post-load', function(){
			jQuery( 'a.share-facebook' ).on( 'click', function() {
				if ( 'undefined' !== typeof windowOpen ){ // If there's another sharing window open, close it.
					windowOpen.close();
				}
				windowOpen = window.open( jQuery(this).attr( 'href' ), 'wpcomfacebook', 'menubar=1,resizable=1,width=600,height=400' );
				return false;
			});
		});
		</script>
				<script type="text/javascript">
			var windowOpen;
		jQuery(document).on( 'ready post-load', function(){
			jQuery( 'a.share-twitter' ).on( 'click', function() {
				if ( 'undefined' !== typeof windowOpen ){ // If there's another sharing window open, close it.
					windowOpen.close();
				}
				windowOpen = window.open( jQuery(this).attr( 'href' ), 'wpcomtwitter', 'menubar=1,resizable=1,width=600,height=350' );
				return false;
			});
		});
		</script>
				<script type="text/javascript">
			var windowOpen;
		jQuery(document).on( 'ready post-load', function(){
			jQuery( 'a.share-google-plus-1' ).on( 'click', function() {
				if ( 'undefined' !== typeof windowOpen ){ // If there's another sharing window open, close it.
					windowOpen.close();
				}
				windowOpen = window.open( jQuery(this).attr( 'href' ), 'wpcomgoogle-plus-1', 'menubar=1,resizable=1,width=480,height=550' );
				return false;
			});
		});
		</script>`
The problem is that I want to minify my html source so I ouput only one line. I can't, because the comment will break the rest of the script.

Could you fix this using a simple /* */ comment instead of // ?

**Comment by jeherve** [comment]
> Could you fix this using a simple /* */ comment instead of // ?

Wouldn't it be easier for you to remove comments when miniyfing all JavaScript? It would help you reduce file size even more. Much like space and empty lines, comments aren't really useful when looking at minified code.

That also seems to be what most js minifiers do. [If you want to keep the comments, it's suggested to insert line breaks when a comment is present.](http://stackoverflow.com/a/9467997/1045686)
