### ISSUE TITLE
Boost: Fix My Jetpack vs Boost pricing table discrepancy

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#38947]
Reference pbNhbs-aae-p2#comment-23173

Currently, My Jetpack and Boost both have their own copy of the pricing table for Boost. This often causes My Jetpack to lag behind. We should only have one copy of the pricing table, hosted in My Jetpack. Boost should reuse the same component. This way, the pricing tables will stay in sync.

**My jetpack page** (http://jetpack-boost.test/wp-admin/admin.php?page=my-jetpack#/add-boost):

![image](https://github.com/user-attachments/assets/71208afe-e1c2-49c7-91ac-c7d9d791107d)

**Boost's getting started page** (http://jetpack-boost.test/wp-admin/admin.php?page=jetpack-boost#getting-started):

![CleanShot 2024-08-19 at 12 17 51](https://github.com/user-attachments/assets/44e721a0-66a0-4b63-8bd1-bb6b7c6c6e67)

**Comment by dilirity** [comment]
~Unfortunately, updating Boost to use the component My Jetpack is using, means that we would have to move that component outside of My Jetpack.~

~Based on my knowledge of react, I'm not sure it's going to be easy.~

~For now, I'm just going to sync the pricing tables until someone with more expertise in react can check this out.~

It appears I was wrong. The component is [exported](https://github.com/Automattic/jetpack/blob/fe2a3d1e65e8e8bd3a4488c719ae2de61b05f026/projects/packages/my-jetpack/package.json#L51) already 🥳
