### ISSUE TITLE
Widgets: Social Icons Jetpack not Working in 13.7

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#38959]
### Impacted plugin

Jetpack

### Quick summary

The "Social Icons (Jetpack)" widget in Jetpack v13.7 isn't loading the icons

### Steps to reproduce

1. Install Jetpack 13.6
2. Add the "Social Icons (Jetpack)" widget (may need to add classic-widgets plugin)
3. Add social links and see the icons work
4. Upgrade to 13.7
5. See that the icons no longer work

### A clear and concise description of what you expected to happen.

Social icons should be working

### What actually happened

13.6: 

![Annotation on 2024-08-19 at 16-55-02](https://github.com/user-attachments/assets/eda50e05-0aec-44ee-b23a-32107b877939)

13.7:

![Annotation on 2024-08-19 at 16-55-15](https://github.com/user-attachments/assets/bf010208-fb4e-4548-9219-1df2fca5e987)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by bobmatyas** [comment]
Reported on: https://wordpress.org/support/topic/social-icons-not-visible-since-last-few-days/

**Comment by coder-karen** [comment]
Re-opened as further investigation may be needed, see https://github.com/Automattic/jetpack/pull/38965#issuecomment-2298351469
