### ISSUE TITLE
AI Assistant block: Button says 'reconnect Jetpack' when Jetpack has never been connected.

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#39019]
### Impacted plugin

Jetpack

### Quick summary

Before connecting Jetpack, if you try to use the AI Assistant block, the button says 'Reconnect Jetpack', which is confusing, as Jetpack has never been connected:
<img width="771" alt="image" src="https://github.com/user-attachments/assets/5fdec1b5-e931-42c3-826e-5cde1f4bc69a">

### Steps to reproduce

1. Install and activate Jetpack, but don't connect it.
2. Add a post and add the AI Assistant block.

### A clear and concise description of what you expected to happen.

The button should say "Connect Jetpack".

### What actually happened

The button says "Reconnect Jetpack".
<img width="771" alt="image" src="https://github.com/user-attachments/assets/4a79694f-289c-417a-9619-860b4151790c">

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

The button still works, it's just confusing wording.

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by jeherve** [comment]
cc @dhasilva who had worked on #31001 a while back.
