### ISSUE TITLE
Jetpack AI "Number of requests" tooltip is cut off on smaller screens.

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#39017]
### Impacted plugin

Jetpack

### Quick summary

On smaller screens, the tooltip for "Number of requests" is cut off:
<img width="1154" alt="image" src="https://github.com/user-attachments/assets/6d24df4a-e3f5-467e-9c80-1cad5d2c4d4b">

### Steps to reproduce

1. Start at My Jetpack
2. Click the 'Learn More' button on the Jetpack AI card
3. Click the "i" information icon to open the tooltip
4. Adjust screen width to see the issue

### A clear and concise description of what you expected to happen.

The whole tooltip should always be visible.

### What actually happened

The tooltip is cut off on the left on smaller screens:
<img width="1154" alt="image" src="https://github.com/user-attachments/assets/1549a661-7b87-4ef5-86c1-b0577bccf7e2">

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Increase the screen width to see the whole tooltip.

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

Chrome browser on Mac.

**Comment by robertsreberski** [comment]
We don't supported tiered AI plans anymore
