### ISSUE TITLE
Sharing: Update Google Plus Logo

### ISSUE THREAD

**Issue by annezazuu** [Automattic/jetpack#3913]
<img width="702" alt="capture d ecran 2016-05-23 a 18 00 51" src="https://cloud.githubusercontent.com/assets/11266471/15487196/54305ff4-2119-11e6-9eb9-901523f0fe74.png">

A user wrote in requesting we update the Google Plus logo for sharing. Right now, we still show the old version on posts:

<img width="82" alt="screen shot 2016-05-23 at 9 04 32 am" src="https://cloud.githubusercontent.com/assets/426388/15496785/7d3cda3e-2197-11e6-8b94-c1e2ef01ad8f.png">

**Comment by Risengan** [comment]
Not resolved in the last update.
<img width="356" alt="capture d ecran 2016-06-20 a 22 39 08" src="https://cloud.githubusercontent.com/assets/11879201/16209569/e03f7c12-3737-11e6-9cf3-9a882c020eba.png">

<img width="343" alt="capture d ecran 2016-06-20 a 22 37 02" src="https://cloud.githubusercontent.com/assets/11879201/16209497/a041daba-3737-11e6-93dd-dc8b2e6398e3.png">

**Comment by jeherve** [comment]
@Risengan No, we didn't fix that issue yet. We'll update this issue once we make progress on this.

**Comment by jeherve** [comment]
Fixed in #4096
