### ISSUE TITLE
Feature Request: Add option to exclude IPs from being counted in the site statistics

### ISSUE THREAD

**Issue by StefMattana** [Automattic/jetpack#39151]
### Impacted plugin

Jetpack

### What

Add rule to exclude some IPs form Stats count

### How

This has been requested in ticket 8664548-zen

>I would like to ensure that visitors and/or page views from a specific IP address are not included on the statics. Is there a setting for that? If not I would recommend that be added to your plugin as our internal staff uses our website as an information resource and will make our stats inaccurate.

**Comment by jeherve** [comment]
Closing as duplicate of #3570.

As noted there, you can use a filter to achieve that behavior:

https://developer.jetpack.com/hooks/jetpack_stats_excluded_ips/
