### ISSUE TITLE
Inconsistencies between "VaultPress Backup" and "VaultPress" text in WP Admin 

### ISSUE THREAD

**Issue by foleynotrose** [Automattic/jetpack#39165]
### Impacted plugin

Jetpack, Backup

### Quick summary

In the WordPress Admin sidebar, whether it says "VaultPress Backup" or "VaultPress" varies based on which plugin you have installed. This should be consistent regardless of if you have the Jetpack or Jetpack Backup plugin installed. 

![image](https://github.com/user-attachments/assets/03376bf3-e7bd-4373-9a2d-68d3b01c3358)

![Screenshot 2024-08-30 at 16 50 42](https://github.com/user-attachments/assets/8ce33030-d61e-4de0-8aee-d606067a73e4)

### Steps to reproduce

1. Install the Jetpack plugin on a site. 
2. Install the standalone Jetpack Backup plugin on a site. 
3. Install both plugins on a site. 
4. Check the Jetpack Sidebar of your WP Admin area. 

### A clear and concise description of what you expected to happen.

It should say "VaultPress Backup" whichever combo of plugins you have installed. 

### What actually happened

I see the text variations as per which plugin is installed on the site:
- "VaultPress Backup" for [Jetpack VaultPress Backup](https://wordpress.org/plugins/jetpack-backup/) plugin
- "VaultPress" for [Jetpack](https://wordpress.org/plugins/jetpack/) plugin
- "VaultPress Backup" if both are installed.

### Impact

All

### Available workarounds?

There is no user impact

### If the above answer is "Yes...", outline the workaround.

Only user impact might be confusion about the product and branding.

**Comment by anomiex** [comment]
~~I was not able to reproduce this following the instructions provided. Installing only Jetpack (13.7 or 13.8-a.7) on a JN site did not show any Backup-related menu entry until I added a Backup plan, at which point it showed "VaultPress Backup".~~

**Comment by foleynotrose** [comment]
Interesting. I just tested adding a Jetpack Backup plan to my site https://totally-amazing.jurassic.ninja/. 

With Jetpack 13.8-a.7 only: 

<img width="695" alt="Screenshot 2024-09-02 at 17 05 42" src="https://github.com/user-attachments/assets/661fba16-c367-40ad-8837-430ae576a955">

---

With Jetpack VaultPress Backup 2.7: 

<img width="695" alt="Screenshot 2024-09-02 at 17 14 35" src="https://github.com/user-attachments/assets/25e345dc-17b0-46ec-9e9f-2b04758423ec">

---

With both: 

<img width="695" alt="Screenshot 2024-09-02 at 17 16 37" src="https://github.com/user-attachments/assets/635839b7-ab50-46c9-a07a-0dbbc8e19a60">

---

@anomiex I wonder what accounts for these different results?

**Comment by anomiex** [comment]
Ah ha. It looks like when I bought the Jetpack Backup plan for my JN site, it auto-installed the Backup plugin for me and I didn't notice. If I disable that, I can reproduce.

The relevant code appears to be
https://github.com/Automattic/jetpack/blob/7c988d4687b4a7f8915f14ea87ff0360a11138a1/projects/plugins/jetpack/modules/scan/class-admin-sidebar-link.php#L94-L103

**Comment by Initsogar** [comment]
Hey there 👋🏽

Trying to recap, the use of “VaultPress” with the external link icon instead of "VaultPress Backup" is related to this:

![CleanShot 2024-09-03 at 10 04 30@2x](https://github.com/user-attachments/assets/bcd75abb-5b92-40d8-813e-e504f45c708d)

When the user don't have the backup standalone plugin, we need to point that link to Jetpack Cloud, and the external icon makes the submenu to break into a new line 😢. After discussing a bit, we agreed of using just “VaultPress :external-icon:” for those cases.

One option could be to remove the external-icon, but I am not convinced that's a good practice in terms of UX, as we are expected to add the external icon anytime we are moving the user to a new URL/domain. Any thoughts @keoshi?

Link of the previous discussion: p1675266641666369/1675212089.013999-slack-C0D96691V

**Comment by foleynotrose** [comment]
Thanks for the extra context @Initsogar ! I figured there might be a good reason it was this way, i just didn't remember what it was. 

What's the downside of both scenarios saying just `VaultPress`? 

The Full plugin can still show the arrow indicating that clicking will take you to Jetpack Cloud. 

My concern here is that having them labeled as different things can cause confusion for the users, especially those who might have one site with the standalone plugin, and another with the full plugin, and even another with both. 

It's also harder to keep documentation clear, with instructions and screenshots being slightly different based on which plugin you have. 

Yes, we might be doing away with Backup features in the full plugin, but that's still a long way off I'm guessing?
