### ISSUE TITLE
Admin: No JS view is broken

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#3917]
I turned off JS in my browser (Chrome), and don't get anything displaying at all. I think something went wrong in a recent merge or something.

**Comment by dereksmart** [comment]
@beaulebens #3806 hasn't been merged yet.

**Comment by beaulebens** [comment]
LOL, my bad. I even checked for it, but I think it was off the page of issues I was looking at :)

I'll leave this here and link them up just for reference.

**Comment by richardmuscat** [comment]
Closing as being dealt with here: #4080
