### ISSUE TITLE
Admin: React/JS warning in console

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#3918]
I see this warning in the console:

`warning.js:45 Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.`

Based on a quick search, I don't actually know where it's coming from though.

**Comment by oskosk** [comment]
Appears to be coming from inside `dops-components`

**Comment by dereksmart** [comment]
opened this issue in https://github.com/Automattic/dops-components/issues/21
