### ISSUE TITLE
All-time insights showing blank data

### ISSUE THREAD

**Issue by Greatdane** [Automattic/jetpack#39180]
### Impacted plugin

Jetpack

### Quick summary

In **Jetpack Stats > Insights > All-time insights, Total views**, the data is blank. 

Actually, it looks to be there when you hover, but the graph is not showing; 

![CleanShot 2024-09-02 at 14 32 10@2x](https://github.com/user-attachments/assets/aa603fc2-b9bb-49e4-a944-14bf56f3b336)

### Steps to reproduce

Go to Stats > Insights > All-time insights, Total views

### A clear and concise description of what you expected to happen.

View graph/chart should show

### What actually happened

View graph/chart does not show

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Not sure about self-hosted

**Comment by Greatdane** [comment]
Reported by user here: 8679804-zd-a8c

Slack thread: p1725255562477589-slack-CDLH4C1UZ

**Comment by jos22** [comment]
I can't replicate this for self-hosted sites when accessing `Total views` via WP Admin. However, the `Total views` dashboard for the same self-hosted site on WordPress.com runs into the same problem.

**Comment by aisajib** [comment]
I had another report of this here: 8677659-zd-a8c - but I was unable to replicate it. I'm guessing that fix ^^ is live now.

**Comment by dognose24** [comment]
> I'm guessing that fix ^^ is live now.

Yes, I [proposed a quick fix](https://github.com/Automattic/wp-calypso/pull/94098) and already deployed it.

**Comment by jorpdesigns** [comment]
Reported a few days ago in 8675168-zen and 8674304-zen. Couldn't replicate on either site so the fix does appear to be working. Thanks!

**Comment by Addison-Stavlo** [comment]
Closing since this appears to be resolved.
