### ISSUE TITLE
Admin: Dev Mode

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#3919]
With `JETPACK_DEV_DEBUG` enabled, I'm still able to view all settings/everything, and even turn things on and off. Should we have some disabled mode that prevents interaction with things that don't work in dev mode?

**Comment by beaulebens** [comment]
The Connect button also renders incorrectly (URL contains the string `[object Object]`, and throws a few JS errors about not being able to hit internal API endpoints.

**Comment by beaulebens** [comment]
![screen shot 2016-05-23 at 7 07 09 pm](https://cloud.githubusercontent.com/assets/108942/15489052/92b0d93e-2119-11e6-9ca1-fd107f970d29.png)

**Comment by beaulebens** [comment]
Actually, the error about the Failed propType is showing even in normal mode, although the URL appears correct for the button.

**Comment by eliorivero** [comment]
Some items covered by https://github.com/Automattic/jetpack/pull/4026

**Comment by eliorivero** [comment]
@beaulebens the PR #4076 solves the connection button issue.
