### ISSUE TITLE
Admin: Old Settings Pages

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#3920]
"Old" settings pages are being maintained for now for legacy/linking purposes.

The header/general styles of the pages should be brought in line with the new style, so that they at least look similar (remove clouds, update header).

I also noticed that at least the Related Posts config page isn't currently working, due to a JS error (perhaps because of changes to the DOM?). At this URL: `/wp-admin/admin.php?page=jetpack&configure=related-posts#/?_k=fl0rvu` I get this error:

`invariant.js:46Uncaught Invariant Violation: _registerComponent(...): Target container is not a DOM element.`

The top-nav links on these pages, where they link to "Jetpack by WordPress.com" need to also be updated/changed to link back to `/wp-admin/admin.php?page=jetpack` and not `/wp-admin/admin.php?page=jetpack_modules`

**Comment by richardmuscat** [comment]
Closing as being dealt with here: #4080
