### ISSUE TITLE
Admin: Header: Currently either too tall, or too short

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#3921]
Due to the position of the Jetpack item in the sidebar menu, combined with the height of the green header, you get a weird effect currently where the green ends right in the middle of the "active menu" cutout/arrow:

![screen shot 2016-05-23 at 7 03 47 pm](https://cloud.githubusercontent.com/assets/108942/15489016/3042f0ca-2119-11e6-845b-1be6e02a3af0.png)

We should make the header either taller or shorter, to avoid this issue.

**Comment by jeffgolenski** [comment]
. @MichaelArestad is working on masthead changes within https://github.com/Automattic/jetpack/tree/update/navigation, which should change the green and eliminate this visual issue.

**Comment by beaulebens** [comment]
Design is changing, will no longer be an issue.
