### ISSUE TITLE
Map Block: Inability to Add Locations

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/jetpack#39217]
### Impacted plugin

Jetpack

### Quick summary

I'm running into issues trying to add a location in a map block.

- Pasting in a place name or address offers no auto-resolution.
- Typing in a place name offers auto-complete, but the place name never populates as an option.
- Typing in an address in full does not correctly resolve. At some points during typing the correct option appears but disappers if you type the rest of the address.
- Some addresses resolve with the full word `Street` and some only with the abbrevation `St`. 

For testing, I'm trying to add a pin for Salesforce Park in San Francisco.

425 Mission St
San Francisco, CA

### Steps to reproduce

1. Add a map block.
2. Start typing a place name or address in the input field.

### A clear and concise description of what you expected to happen.

For my desired place to appear via auto-complete.

### What actually happened

I was only able to get the correct place to populate when using address, and only at certain partial input points.

Entering the place name or address in full and pressing enter to submit has no effect. The only way to place a pin is when the option is choosen from the suggested results. 

When the results never suggest the correct place the block becomes unusable.

Pasting in and Trying Different Address Variations
<img width="600px" src="https://github.com/user-attachments/assets/3705c5b6-9e5b-4998-bf93-b0865f2a0a4f">

Using Place Name
<img width="600px" src="https://github.com/user-attachments/assets/d33c4f66-b596-4bd1-8aee-7bc1934bc4a2">

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by jeherve** [comment]
I'm afraid there is little we can do about this. The places and place names are all created and managed via Apple in your example, and the data displayed in the block comes straight from Apple's Mapkit. If a place is missing in Apple Maps, you won't find it in the Map block. I'm afraid I can only recommend that you report the missing place / add the new place via the Apple Maps.

**Comment by katiebethbrown** [comment]
@jeherve - The place/address is a very common park in a major urban area. It's not missing - it's already listed on Apple Maps. When I When I search Apple Maps on desktop for Salesforce Park it comes right up:

![CleanShot 2024-09-04 at 09 58 57@2x](https://github.com/user-attachments/assets/07fdb0e8-c11e-4ade-aa98-4f5566a03b49)

And when I was finally able to get a version of the address that the input recognized you can see it listed next to the actual address pin in the block:

![CleanShot 2024-09-04 at 10 02 31@2x](https://github.com/user-attachments/assets/48383657-5c1a-49b1-a384-54c551b8309e)

**Comment by kraftbj** [comment]
This is something that I'm not sure the best way to try to fix it. The map block when using Apple is directly querying the Apple API, e.g. `https://api.apple-mapkit.com/v1/searchAutocomplete?q=salesforce tower&lang=en&searchRegionPriority=Default&resultTypeFilter=Address,Query&mkjsVersion=5.78.87` and it isn't returning that as an address point. I don't immediate see anything notable in the MapKit API docs, but I agree, it is annoying. :)
