### ISSUE TITLE
Admin: Pre-Connect: Revert intro text

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#3922]
Before you're connected, we currently show a "Please Connect Jetpack" heading. The very next thing you read is the same thing. I think we should just get rid of the heading, unless there's something more informative/useful we can put there. If anything, maybe just bold the first part of the statement in the connection box?

![screen shot 2016-05-23 at 7 11 20 pm](https://cloud.githubusercontent.com/assets/108942/15489114/27b0920e-211a-11e6-9771-025770514800.png)

![screen shot 2016-05-23 at 7 11 46 pm](https://cloud.githubusercontent.com/assets/108942/15489121/3664ebec-211a-11e6-84f8-a7226aaefb57.png)

**Comment by jeffgolenski** [comment]
@jessefriedman @richardmuscat Would love your feedback on this & the Jumpstart content ([PR here](https://github.com/Automattic/jetpack/pull/3967)). I'd like to keep them consistent whether we decide to remove the headers or not.

**Comment by richardmuscat** [comment]
@jeffgolenski: I think we should keep the heading and replace the text with what we currently have, ie:

> Connecting Jetpack will show you **stats** about your traffic, **protect** you from brute force attacks, **speed up** your images and photos, and enable other traffic and security features.
