### ISSUE TITLE
Enhancement: Change "Contribution Amount" to "Amount" on payment modal

### ISSUE THREAD

**Issue by supernovia** [Automattic/jetpack#39239]
### Impacted plugin

Jetpack

### What

Can we remove the word "Contribution" so the variable payment option works for cases that aren't donations?

### How

Our payments plan screen has this option:
- Enable customers to pick their own amount (“Pay what you want”)

If that's toggled, the payment screen says _**Contribution** Amount_, even if the site admin doesn't intend for it to be a contribution but just an easier way for clients to pay an agreed-upon price online.  If we remove the word Contribution, it works for donations as well as other payments.

![Screenshot 2024-09-04 at 1 03 51 PM](https://github.com/user-attachments/assets/91a000b2-9f97-4bf0-b528-bab2d7d52175)

**Comment by jeherve** [comment]
Fixed in D160563-code
