### ISSUE TITLE
Enhancement: Silence unnecessary warnings for wpcomsh

### ISSUE THREAD

**Issue by ajaykj** [Automattic/jetpack#39236]
### Impacted plugin

mu wpcom

### What

Be careful about the warning messages about wpcomsh plugin

### How

The following warning messages were filling up server logs for a WoA site (blog id: 236564587)

```PHP Warning:  Undefined array key "ignore_search_engines_discouraged_notice" in /wordpress/plugins/wpcomsh/5.8.0-alpha+rolling.32cb4fc/feature-plugins/full-site-editing.php on line 96```

@jmdodd traced the source to the WPSEO plugin options in the options table. Removing those options solved the issue.

Can we silence these notices?

**Comment by jmdodd** [comment]
In this case, it was only reasonable to remove the option because the WPSEO plugin was not in use. A more universal fix would be checking to see if the array key exists before referencing it.
