### ISSUE TITLE
Admin: Jump Start: Update to reflect Jump Start in the current Jetpack

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#3924]
- [x] Remove the Happiness card at the bottom
- [x] List of features should be the same as current Jetpack ()
- [x] Make sure we're actually activating the list we're saying we are
- [ ] Can probably just remove the "Jump Start your Website" heading here as well
- [x] Links on/next to each listed feature to find out more (link to support docs)

![screen shot 2016-05-23 at 7 30 20 pm](https://cloud.githubusercontent.com/assets/108942/15489416/d03010b0-211c-11e6-8f28-f3baf9a128f8.png)

**Comment by jeffgolenski** [comment]
Fixed in: https://github.com/Automattic/jetpack/pull/3967
