### ISSUE TITLE
Admin: Notices: Collection of tweaks/improvements

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#3925]
The notices that we're using within the new admin UI (and the HTML/CSS clones used elsewhere) have some tweaks to get them ready to roll:

- [ ] When they contain an action/"button", they should match the style of Calypso, which puts it explicitly over to the right in a tinted color section (see https://wpcalypso.wordpress.com/devdocs/design, search "notices")
- [x] The close/cross icon is misaligned. Should be vertically centered for a single line of text, and "pinned" towards the top of the notice for multiline notices.
- [ ] When you click a notice to dismiss it, it seems that we wait for an API response before removing it. We should optimistically just remove it as soon as you click it.
- [x] Notices are not "full width" -- they are padded in from the left/right compared to the rest of the content area (specifically, the Nav block immediately below them).
- [ ] Need to suppress the old-style notices for enabling/disabling modules (and probably more), because otherwise if you activate something, then reload the page, you get something like this; https://cloudup.com/cXW3HwIxQ92
- [ ] Need a "static HTML/CSS" version of our notices which can be used throughout wp-admin, where we can't use the React component from our main UI.
- [ ] All Jetpack-related notices through-out wp-admin need to be updated to use the above "static" version of our notices.

Apart from these ones, there are a couple of other Notice-related things:

- The "Development Version" notice is pretty in-your-face, and feels a bit like a punishment for someone running a dev version, which is hopefully doing us a favor. Can we tone it down somehow, or don't display it, and just display something else in the header, or _something?_
- Need to figure out how to handle if someone else is setting a global notice, which would appear on this page (currently forces down the header + content)

**Comment by jeffgolenski** [comment]
Repairing notices in: https://github.com/Automattic/dops-components/pull/22
