### ISSUE TITLE
Admin: Force refresh of site list in Calypso

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#3927]
When we link through to pages/views in Calypso, we can run into a bug where the current (newly-added) site hasn't been cached in the users data yet. They hit Calypso, which doesn't see the site in their site list, so it redirects them to either some other page, or a site-selection list. This makes for a pretty confusing experience.

We need to either figure out a way to make Calypso handle the situation automatically, or else pass some manual parameter to force a refresh of the site list before attempting to access a route.

**Comment by beaulebens** [comment]
Also being tracked automattic/wp-calypso/#5571

**Comment by richardmuscat** [comment]
hey @roccotripaldi -- you were looking into this a while back. any joy?

**Comment by roccotripaldi** [comment]
No joy yet. Still on my list.

**Comment by samhotchkiss** [comment]
Just connected a new site-- 5+ minutes later, it's still not accessible in calypso :-(

**Comment by dereksmart** [comment]
This is being worked on in https://github.com/Automattic/wp-calypso/pull/7250

**Comment by samhotchkiss** [comment]
Closing this out in favor of the issue being tracked in Calypso
