### ISSUE TITLE
AI Excerpt: Missing from Post Editor

### ISSUE THREAD

**Issue by retnonindya** [Automattic/jetpack#39289]
### Impacted plugin

Jetpack

### Quick summary

AI Excerpt is missing from post editor. Before, Excerpt feature is visible on the right sidebar on the post editor with the option of generating excerpt using AI visible.

<img width="556" alt="create-excerpt-ai-excerpt-settings" src="https://github.com/user-attachments/assets/4734793d-d298-401e-9c4d-f6917b93c198">

Now, the Excerpt feature has moved to under the Featured Image and is missing the option to generate it using AI.

<img width="710" alt="Screenshot 2024-09-09 at 11 21 13 AM" src="https://github.com/user-attachments/assets/c73d5f50-09cd-4698-94b3-aac7f9898e68">

### Steps to reproduce

1. Open a post editor by creating a new post or edit existing post that has no excerpt
2. Find the Excerpt tool. It is located under Featured Image.
3. Click it to add excerpt.

### A clear and concise description of what you expected to happen.

The option to create manual excerpt _and_ AI-helper tool

### What actually happened

I can only see the option to create manual excerpt

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

This is from user report that I can replicate on my personal blog.

**Comment by retnonindya** [comment]
I wonder if this is related: https://github.com/Automattic/jetpack/issues/39247

**Comment by arthur791004** [comment]
I'm taking a look on this issue 🙂

**Comment by arthur791004** [comment]
It's related to https://github.com/Automattic/jetpack/pull/39245/files#r1749640655 cc @dhasilva

**Comment by arthur791004** [comment]
Proposed https://github.com/Automattic/jetpack/pull/39292 to resolve the issue!
