### ISSUE TITLE
Admin: FoldableCard: Make clickable

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#3928]
When a FoldableCard is closed, clicking anything on it except the toggle should open the card. Specifically, clicking the title or subtitle should open it, not just the arrow on the far right.

![screen shot 2016-05-23 at 8 15 57 pm](https://cloud.githubusercontent.com/assets/108942/15490194/5e9e01da-2123-11e6-9a26-2ab2624857df.png)

**Comment by jeffgolenski** [comment]
Fixed in: https://github.com/Automattic/dops-components/pull/20
