### ISSUE TITLE
Admin: FoldableCard: Jerky animation

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#3929]
I'm not sure if the animation on opening/closing the FoldableCards intentionally has some physics/easing to it, but it has a weird jerkiness at the end of opening and closing which doesn't feel right. It's a little hard to see in this animation, but just opening/closing any card will show it to you. Can we just eliminate that 

![card-animation](https://cloud.githubusercontent.com/assets/108942/15490276/d52eeb66-2123-11e6-8a91-10c41ad359a0.gif)

by comparison, here's a Calypso card:

![calypso-card](https://cloud.githubusercontent.com/assets/108942/15490309/141c62e0-2124-11e6-97b8-4edbb5ce961a.gif)

**Comment by dereksmart** [comment]
This has been fixed along with the most recent settings designs.
