### ISSUE TITLE
Jetpack: improve Search option checking

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#39352]
### Impacted plugin

Jetpack, Search

### What

Do not check options needlessly.

### How

`has_jetpack_search_product` and `instant_search_enabled` are both options that are checked on the front end. It is likely that if `has_jetpack_search_product` is false, then `instant_search_enabled` is not needed. Examine the search loading process to ensure it is optimized for the frontend.

pdWQjU-Qx-p2#comment-924

**Comment by oskosk** [comment]
I think users on the free tier still get Jetpack instant search even if there's no product. But then maybe the free tier on Search was implemented as a product 🤔

**Comment by kraftbj** [comment]
It was setup as a product on the WP.com side. `jetpack_search_free`. The usual `Current_Plan` classes, though, do not see it as a product. The search code itself looks for the response from WP.com (`Automattic\Jetpack\Search\Plan->update_search_plan_info`) and sets the `has_jetpack_search_product`

```
/srv/htdocs$ wp option get has_jetpack_search_product
1
/srv/htdocs$ wp option get instant_search_enabled
1

```

Adding some optimizations and will continue testing to ensure it removes the extra calls.

**Comment by oskosk** [comment]
Ah cool then
