### ISSUE TITLE
Linkedin followers count not fetched and updated 

### ISSUE THREAD

**Issue by jartes** [Automattic/jetpack#39400]
### Impacted plugin

Social

### Quick summary

Linkedin followers for a connected account in Jetpack Social are not updated or fetched (when there is a new connection).

### Steps to reproduce

**Connecting a new Linkedin account**
1. On Jetpack Social, connect a new LinkedIn account.
3. Add a Subscribe block if it's not added to the site.
4. Enable the `Include social followers in count` option.
5. Check the followers numbers, and see that Linkedin followers are not added.

**With a current LinkedIn account connected**
1. Add a Subscribe block if it's not added to the site.
2. Enable the `Include social followers in count` option.
3. Check the followers numbers, and see that Linkedin followers are not added.

### A clear and concise description of what you expected to happen.

See the followers count taking into account the Linkedin followers.

### What actually happened

LinkedIn followers are not counted. 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Also, in JP Social RC the followers count is not updated

**Comment by jartes** [comment]
8721281-zd-a8c

**Comment by spsiddarthan** [comment]
Seeing the latest comment on the ticket, I see that the issue is solved. I am opening an internal issue to find out more about follower counts.

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 ACTIONS
- Triaged
- Lowered priority from High to Normal.

@spsiddarthan While I was testing this, I added the Subscribe block to [my site's footer](https://joanartes.com/) with the option to include social followers count. I connected my LinkedIn account with 2,500 followers, and they have not been added. Also, the follower count is not reflected on the Jetpack Social RC. 

Feel free to DM me via Slack if you need anything else to test this further :)

**Comment by spsiddarthan** [comment]
Thanks @jartes ! That's clear enough. We will debug and get back on it. We have a bit of AFK this week, so it could be till the end of next week before getting back on this.

**Comment by spsiddarthan** [comment]
I have a solution D162349-code in the works for this, somehow a bug has crept in there, although we haven't touched this bit of code in years.

Couple of things to note:
- LinkedIn, Mastodon and Facebook are the only services we fetch the social followers count for. I am not sure how accurate the Facebook count is, I will open a separate issue to track that.
- LinkedIn followers count is actually the number of connections you have and not the number of followers. For individual profiles, LinkedIn doesn't let you fetch the followers count, they only let you get the connections count. It has always been this way. 

I will get my fix merged and ping again on this issue in the coming days.

**Comment by spsiddarthan** [comment]
@jartes, this is done (or so I think 😃 ). Do you want to give it a test when you can?
