### ISSUE TITLE
Fatal error when $submenu is NULL for cetain user roles

### ISSUE THREAD

**Issue by ecairol** [Automattic/jetpack#39423]
### Impacted plugin

Jetpack, ~CRM~
Initially reported for a CRM user, but this seems to happen for other sites without Jetpack CRM.

It could be related to users using SSO but needs more debugging.

### Quick summary

This error is happening for users with the role `zerobs_admin` (aka as `Jetpack CRM Admin (Full CRM Permissions)`), but I suspect it could happen to other custom user roles as well.

**The error**
> PHP Fatal error: Uncaught TypeError: array_column(): Argument #1 ($array) must be of type array, null given in /wordpress/plugins/jetpack/13.9-a.3/jetpack_vendor/automattic/jetpack-masterbar/src/admin-menu/class-atomic-admin-menu.php:333
Stack trace:
#0 /wordpress/plugins/jetpack/13.9-a.3/jetpack_vendor/automattic/jetpack-masterbar/src/admin-menu/class-atomic-admin-menu.php(333): array_column(NULL, 3)
#1 /wordpress/plugins/jetpack/13.9-a.3/jetpack_vendor/automattic/jetpack-masterbar/src/admin-menu/class-admin-menu.php(40): Automattic\Jetpack\Masterbar\Atomic_Admin_Menu->add_jetpack_menu()
#2 /wordpress/plugins/jetpack/13.9-a.3/jetpack_vendor/automattic/jetpack-masterbar/src/admin-menu/class-atomic-admin-menu.php(76): Automattic\Jetpack\Masterbar\Admin_Menu->reregister_menu_items()
#3 /wordpress/core/6.6.2/wp-includes/class-wp-hook.php(324): Automattic\Jetpack\Masterbar\Atomic_Admin_Menu->reregister_menu_items('')
#4 /wordpress/core/6.6.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#5 /wordpress/core/6.6.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /wordpress/core/6.6.2/wp-admin/includes/menu.php(161): do_action('admin_menu', '')
#7 /wordpress/core/6.6.2/wp-admin/menu.php(412): require_once('/wordpress/core...')
#8 /wordpress/core/6.6.2/wp-admin/admin.php(158): require('/wordpress/core...')
#9 /wordpress/core/6.6.2/wp-admin/index.php(10): require_once('/wordpress/core...')
#10 {main}
thrown in /wordpress/plugins/jetpack/13.9-a.3/jetpack_vendor/automattic/jetpack-masterbar/src/admin-menu/class-atomic-admin-menu.php on line 333

This is happening for all Jetpack CRM Admin users that login via SSO.

The bug was added [back in March](https://github.com/Automattic/jetpack/pull/37459/files#diff-49661f625194f9a0604aecd4f8723215bdf82e9d63d7cbfefbbf977a90bebe5c), when adding the `Scan` option to the Jetpack submenu:

**Potential fix**
Here's a potential fix to the problem: [Pull Request #39424](https://github.com/Automattic/jetpack/pull/39424) 

### Steps to reproduce

Team 51 can provide you access to the error logs on one of our partner's sites.

1. Login to the site as an Admin
2. Create a user with the role Jetpack CRM Admin
3. On another browser, try to login with this new user using SSO
4. The new user is unable to login, and sees: _There has been a critical error on this website. Please check your site admin email inbox for instructions._

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

**Comment by jartes** [comment]
📌 ACTIONS
- Triaged
- Lowered priority from Blocker to High.

📌 Message to Author
Thanks for reporting and proposing a PR for this one @ecairol!

**Comment by mgozdis** [comment]
User report: 8764375-zd-a8c

**Comment by mgozdis** [comment]
Another user report: 8774878-zd-a8c
