### ISSUE TITLE
Boost: Relative URLs break critical css generation

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#39455]
p1726628647463949-slack-C016BBAFHHS

If a source provider has a relative URL, the URL constructor throws an error because it's an invalid URL and breaks the whole generation process. It shouldn't - it should probably show the error under advanced recommendation but it should not break the whole process.

The PHP side that makes sure a relative URL doesn't end up in the source providers will be handled in #39456.

We still need to update the UI to not show a fatal error if a malformed URL reaches critical css. In other words, handle exceptions when the URL is attempted to be created before passing it to the generator (or is it the css generator that throws the error?).

**Comment by 1234abd** [comment]
maybe this will help
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)

**Comment by haqadn** [comment]
If I understand this correctly, the PHP side will make sure there are no relative URLs. In that case, it should be ok to skip updating the UI to handle relative URLs.
