### ISSUE TITLE
Admin: Dops-Section-Header label and action container stack in IE10

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#3947]
The dops-section-header label and actions stack within the "at a glance" dashboard.

![screen shot 2016-05-24 at 5 39 10 pm](https://cloud.githubusercontent.com/assets/214813/15520696/9322abf6-21d5-11e6-8514-322fa82e3ad1.png)

**Comment by richardmuscat** [comment]
Since we're not supporting IE10 is this still relevant/important?

**Comment by jeffgolenski** [comment]
@richardmuscat nope! cleaning up
