### ISSUE TITLE
Page stats don't work...

### ISSUE THREAD

**Issue by grapheine** [Automattic/jetpack#39492]
### Impacted plugin

Jetpack

### Quick summary

Hello, 

Impossible to load this kind of url : admin.php?page=stats#!/stats/year/posts/www.mywebsite.com?startDate=2024-01-01

It's the same for : admin.php?page=stats#!/stats/post/21299/www.mywebsite.com

Any ideas ? Thanks.

Mathias

### Steps to reproduce

Hello, 

Impossible to load this kind of url : admin.php?page=stats#!/stats/year/posts/www.mywebsite.com?startDate=2024-01-01

It's the same for : admin.php?page=stats#!/stats/post/21299/www.mywebsite.com

Any ideas ? Thanks.

Mathias

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by anomiex** [comment]
I think this will need more information. What exactly happens when you try to load those URLs? Do you see any errors in your browser's console? Which browser are you using?

When I tried it on a test site, similar URLs loaded fine for me in Firefox 130.

cc: @Automattic/red

**Comment by kangzj** [comment]
Same as @anomiex here, I'm not able to reproduce. 

> I think this will need more information. What exactly happens when you try to load those URLs? Do you see any errors in your browser's console? Which browser are you using?

It'll be great if the information could be provided for us to further investigate. Thanks!

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple –  Could Not Replicate 
- Tested on Atomic – Could Not Replicate 
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
- N/A

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)


📌 Message to Author
@grapheine please reopen if you have more details for us, including steps on how to replicate this.
