### ISSUE TITLE
Infinite Scroll: Requires connection to WordPress.com

### ISSUE THREAD

**Issue by cameronjonesweb** [Automattic/jetpack#3957]
Infinite Scroll doesn't work in development mode without having connected to WordPress.com.

Steps to reproduce:
- Install & activate Jetpack
- Turn on development mode via filter in theme functions.php
- Turn on infinite scroll module
- Add theme support in theme functions.php

At this stage nothing is working. Scripts and styles are not enqueued at all
- Remove development mode filter
- Connect to WordPress.com
- Add development mode filter again

Now it works as intended

This is 100% unnecessary. Infinite Scroll is available in development mode and there is no connection to wp.com required for it to work and hoops should not have to be jumped through

**Comment by jeherve** [comment]
Could you try to apply the patch available in #3635 on your site, or use the filter in a plugin instead of in your theme's functions.php file?

Let me know if it helps.

**Comment by cameronjonesweb** [comment]
I deleted all the Jetpack settings from the database (as once a connection has been made, it works in dev mode), uninstalled and reinstalled Jetpack, applied the patch, and unfortunately still the same result. However moving the filter to a new plugin did fix the issue, but only with the patch applied.

**Comment by jeherve** [comment]
> However moving the filter to a new plugin does fix the issue, with and without the patch.

Excellent, that's a start.

> applied the patch, and unfortunately still the same result. 

That means we still need to run some more tests with #3635, as it didn't catch your use case. Feel free to subscribe to that GitHub issue to follow our progress on this. You can also comment there with the steps you followed to try to enable Jetpack's Development mode using the patch, without success.

Thanks!
