### ISSUE TITLE
¿Bug in https://s0.wp.com/_static/??/wp-content/js/jquery/jquery.autoresize.js?

### ISSUE THREAD

**Issue by artprojectgroup** [Automattic/jetpack#3959]
TypeError: jQuery(...)[0] is undefined
	target: jQuery( '#googleplus-sign-in' )[0].contentWindow,
??/wp-c...457903j (línea 369, col 14)

This is the function:
`// Comment area auto-sizing and tab handling
		jQuery( 'textarea#comment' )
			.autoResize({
				animate: false,
				animateCallback: HighlanderComments.resizeCallback
			})
			.css( 'resize', 'none' )
			.trigger('change.dynSiz')
			.focus( function() { HighlanderComments.hideLabels( jQuery(this) ); } )
			.blur( function() { HighlanderComments.showLabels( jQuery(this) ); } )
			.keydown( function( e ) {
				if ( 'undefined' != typeof e.keyCode && 9 == e.keyCode ) { // TAB key
					e.preventDefault();
					if ( 'guest' == jQuery( '#hc_post_as' ).val() ) {
						if ( 1 == HighlanderComments.comment_registration ) {
							jQuery( '#postas-wordpress' ).focus();
						} else {
							jQuery( '#email' ).focus();
						}
					} else {
						jQuery( '#comment-submit' ).focus();
					}
				}
			} )
			.keyup( function( e ) { HighlanderComments.fillShareText( jQuery(this) ); } )
			.one( 'focus', function() {
				pm( {
					target: jQuery( '#googleplus-sign-in' )[0].contentWindow,
					type: 'googlePlusLoadJS',
					data: 0,
					url: 'https://public-api.wordpress.com'
				} );
			});`

We detected a big problem with nested comments on https://www.dolcacatalunya.com, because sometimes, not always, sometimes aren't published on commented comment, and this is the unique bug detected.

Any idea?

Kind regards

**Comment by jeherve** [comment]
I can't seem to be able to reproduce the issue, on your site or on mine. Could you walk me through the steps I could follow to reproduce the problem?

Thanks!

**Comment by artprojectgroup** [comment]
Just press reply on one comment and then, after AJAX load, you can see that error.

Kind regards.

**Comment by jeherve** [comment]
I still can't reproduce, whether I'm logged in or logged out of WordPress.com and Google+, in Chrome or in Firefox.

Could you try in a different browser, and while being logged out of your local admin account, and let me know if it changes anything?

Thanks!

**Comment by artprojectgroup** [comment]
I'm going to check it in Safari, Chrome and Opera, but the problem with the nested comments? Do you know why they having that problem?

Kind regards.

**Comment by jeherve** [comment]
>  the problem with the nested comments? Do you know why they having that problem?

I'm not sure, since I haven't run into any issues on your site. It might be worth switching to one of the default themes like Twenty Fifteen for a few minutes, to make sure the problem isn't linked to your theme.

Let me know how it goes.

**Comment by artprojectgroup** [comment]
There's no bug, just in Mozilla Firefox. I tried Mozilla Firefox Developer Edition, Opera, Safari, Google Chrome and Brave without this JS bug :-(

Sorry, maybe any bug on my Mozilla Firefox.

We can't try another template in this website. It has a heavy traffic and owner don't want to change it, sorry. I'll open a support thread on WordPress.org with this specific problem.

Thank you for your help, and I'm sorry for this issue :-(

Kind regards.
