### ISSUE TITLE
Infinite Scroll: checkbox under Settings > Reading doesn't explain the differences between "scroll infinitely" and click.

### ISSUE THREAD

**Issue by jessefriedman** [Automattic/jetpack#3960]
#### What I expected

To be able to use this checkbox to enable / disable Infinite Scroll 
![screen shot 2016-05-25 at 9 35 48 am](https://cloud.githubusercontent.com/assets/1749986/15541767/14de27ca-225c-11e6-9e62-f4b798ae2928.png)

That checkbox is essentially an enable switch to turn on or off Infinite Scroll. It's found in the Reading Settings. 

#### What happened instead

This checkbox seems to be independent of the setting found in the JPR app. Disabling it here has no effect on it's state in JPR

#### Steps to reproduce the issue
https://cloudup.com/cJlwIlaYeLN

**Comment by jeherve** [comment]
Looking at this again, I realize I was wrong in our Slack discussion about this option.

It doesn't actually disable Infinite Scroll. It only changes Infinite Scroll behaviour from `scroll` to `click`. When using `click`, the new posts don't automatically load, you have to click on a button to load more posts.

We could probably make this clearer though, by changing the wording of that option.
