### ISSUE TITLE
Enhancement: Improve Jetpack Anti-Spam Installation Instructions

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#39609]
### Impacted plugin

Jetpack

### What

When purchasing Jetpack Anti-Spam, we can simplify the instructions that we email to users

### How

This is the current email we send when someone purchases a siteless Jetpack Anti-Spam license:

![Annotation on 2024-10-01 at 14-31-27](https://github.com/user-attachments/assets/c11c4352-8e52-43b1-836a-859f9bf4cb37)

After testing this, I found that we install the Akismet plugin when a Jetpack Anti-spam license is activated, so the first step in the instructions is no longer needed. I suggest we eliminate that step (it isn't accurate anyway, as there is no "Jetpack > Add new plugin" menu.

**Comment by bobmatyas** [comment]
@Automattic/jetpack-martech Is this something that your team can fix?

**Comment by elliottprogrammer** [comment]
> @Automattic/jetpack-martech Is this something that your team can fix?

@bobmatyas yes, I'll add this to our maintenance board. 👍

**Comment by CodeyGuyDylan** [comment]
This email is used for all Standalone products. I tested them all and only Anti-Spam and Boost install the plugin upon activation. Social, VideoPress, Backup, Protect, and Search did not.

It's a bit hacky but the quickest solution to this would be to manually check for Anti-Spam and Boost and only remove that step for those products.

A good long-term solution would be to auto-install the other 5 standalone plugins when activating a license as well. I'm not sure of what all that entails, but then we could just remove it from the email entirely. @elliottprogrammer what do you think?

**Comment by elliottprogrammer** [comment]
> It's a bit hacky but the quickest solution to this would be to manually check for Anti-Spam and Boost and only remove that step for those products.
> 
> A good long-term solution would be to auto-install the other 5 standalone plugins when activating a license as well. I'm not sure of what all that entails, but then we could just remove it from the email entirely. [@elliottprogrammer](https://github.com/elliottprogrammer) what do you think?

Yes, I agree that's probably the best long term solution.  Although Social, VideoPress, Backup, Protect, and Search products work with onlyJetpack (plugin) installed, but they also work with only the corresponding standalone plugin installed too, right?  So I guess we would probably want some logic to detect if the user's site already has Jetpack installed or not. If Jetpack is already installed, we don't do anything (in regard to auto-installing anything). I guess we would also check if the standalone plugin already installed or not too.  If neither are already installed, we auto-install the product's standalone plugin. What do you think? Does that sound right, @CodeyGuyDylan?

**Comment by CodeyGuyDylan** [comment]
> Although Social, VideoPress, Backup, Protect, and Search products work with onlyJetpack (plugin) installed

Hmmm I didn't think about it that way. In this case, maybe just filtering out Boost and Anti-Spam for this email is acceptable because they are different in that way. I only proposed the other solution because I don't like exceptions without reason, but if there's a good reason I think we could probably go that route! Does that sound okay? I know we're iffy on continuing to march forward into the standalone plugins universe so maybe it'd be best not to do that for now

**Comment by elliottprogrammer** [comment]
@CodeyGuyDylan Yeah, and I didn't consider the iffyness of our marching forward into the standalone plugin space, so that sounds good to me! 👍
In that case, this will be a pretty straightforward fix then. 🙂

**Comment by robertsreberski** [comment]
Adding my 2 cents here, I think it's a good route to not install a standalone plugin when unnecessary. We will actually merge the Boost functionality back into the main plugin in the upcoming months.

Take a look at the recent update regarding "Standalone plugin strategy": pfwV0U-ji-p2

**Comment by CodeyGuyDylan** [comment]
This issue has been solved. Boost and Anti-Spam no longer show the instruction to install the standalone plugin, and the other standalones that do include the instructions have been corrected to show going to `Plugins > Add New Plugin` rather than `Jetpack > Add New Plugin`. Additionally I updated the instructions to activate the license to send them to My Jetpack instead of the Dashboard
