### ISSUE TITLE
Fatal error for plugin_action_links_ when using strict strong typing

### ISSUE THREAD

**Issue by antondrob** [Automattic/jetpack#39654]
### Impacted plugin

Jetpack

### Quick summary

A fatal error occurs when the Tokenpay Payment Gateway plugin is used alongside the Jetpack plugin, specifically due to using a null parameter instead of an array in the plugin_action_links_ hook.

### Steps to reproduce

1. Install and activate the Tokenpay Payment Gateway plugin.
2. Install and activate the Jetpack plugin.
3. Navigate to the plugins overview page in the WordPress admin dashboard.
[tokenpay-payment-gateway.zip](https://github.com/user-attachments/files/17274788/tokenpay-payment-gateway.zip)

### A clear and concise description of what you expected to happen.

The action links for the Tokenpay Payment Gateway plugin should display without any errors.

### What actually happened

A fatal error is thrown, preventing the admin dashboard from loading properly.

### Impact

All

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Yes, the issue can be temporarily resolved by removing strict typing from the affected code.

**Comment by jeherve** [comment]
> A fatal error is thrown, preventing the admin dashboard from loading properly.

I cannot seem to be able to reproduce the error right now, on a site using WooCommerce, Jetpack, and Tokenpay Payment Gateway. Looking at the 2 plugins, they all seem to use the filter as is expected, with an array.

Could you copy the error you're seeing on your own site, and paste it here?
Could you also let me know what version of each plugin is currently installed on your site?
Is it also possible that you use another plugin that uses `add_plugin_action_links` and returns that null parameter?

Thank you!

**Comment by anomiex** [comment]
> Looking at the 2 plugins, they all seem to use the filter as is expected, with an array.

I did notice two locations where Jetpack code is calling the filter with a null value rather than the documented array for the `$plugin_data` parameter.
https://github.com/Automattic/jetpack/blob/3f185ff8001cd5d65fb9418c526f95d7c531dfda/projects/packages/sync/src/modules/class-callables.php#L399
https://github.com/Automattic/jetpack/blob/3f185ff8001cd5d65fb9418c526f95d7c531dfda/projects/packages/sync/src/modules/class-callables.php#L405

**Comment by antondrob** [comment]
The error was reported by one of the merchants. But personally I didn't manage to replicate either. Here is the error log from the merchant:
```
Ein Fehler vom Typ E_ERROR wurde in der Zeile 50 der Datei /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-content/plugins/woocommerce-gateway-tokenpay-main/includes/Admin/Main.php verursacht. Fehlermeldung: Uncaught TypeError: Onepix\Tokenpay\Admin\Main::add_plugin_action_links(): Argument #3 ($plugin_data) must be of type array, null given, called in /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-includes/class-wp-hook.php on line 324 and defined in /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-content/plugins/woocommerce-gateway-tokenpay-main/includes/Admin/Main.php:50
Stack trace:
#0 /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-includes/class-wp-hook.php(324): Onepix\Tokenpay\Admin\Main->add_plugin_action_links()
#1 /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#2 /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/modules/class-callables.php(405): apply_filters()
#3 /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-includes/class-wp-hook.php(324): Automattic\Jetpack\Sync\Modules\Callables->set_plugin_action_links()
#4 /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#5 /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-admin/includes/class-wp-screen.php(424): do_action()
#7 /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-admin/includes/screen.php(243): WP_Screen->set_current_screen()
#8 /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-sender.php(530): set_current_screen()
#9 /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-sender.php(632): Automattic\Jetpack\Sync\Sender->get_items_to_send()
#10 /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-sender.php(487): Automattic\Jetpack\Sync\Sender->do_sync_for_queue()
#11 /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-sender.php(362): Automattic\Jetpack\Sync\Sender->do_sync_and_set_delays()
#12 /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-actions.php(742): Automattic\Jetpack\Sync\Sender->do_sync()
#13 /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-actions.php(682): Automattic\Jetpack\Sync\Actions::do_cron_sync_by_type()
#14 /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-includes/class-wp-hook.php(324): Automattic\Jetpack\Sync\Actions::do_cron_sync()
#15 /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#16 /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-includes/plugin.php(565): WP_Hook->do_action()
#17 /mnt/customers/customers-1xb2b8/ddfeb870-60f0-4dee-a0b9-175b4a57e03a/wp-content/wp-cron.php(191): do_action_ref_array()
#18 {main}
  thrown
```
