### ISSUE TITLE
Enhancement: Add UI to Disable Individual Blocks

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#39682]
### Impacted plugin

Jetpack

### What

As a site owner, I would like to be able to disable specific blocks via the UI rather than via custom code

### How

The UI only allows a user to enable/disable all Jetpack blocks. It doesn't allow for disabling blocks individually. Ideally, once blocks are enabled, a user should be able to toggle individual blocks on and off.

**Comment by bobmatyas** [comment]
Requested on 8825395-zen

**Comment by jeherve** [comment]
Would disabling each block via the built-in UI in WordPress be an acceptable solution? It was built for that purpose:

https://github.com/user-attachments/assets/2cd593f0-71c8-4722-a782-28774a5441df

**Comment by bobmatyas** [comment]
@jeherve In this case, the customer reported that isn't sufficient. They wanted to deactivate all specific Jetpack blocks for all users on the site without needing custom code.
