### ISSUE TITLE
Site icon (blavatar) not removed on WP.com after removed on self-hosted Jetpack-powered WP site

### ISSUE THREAD

**Issue by lamosty** [Automattic/jetpack#3969]
If you remove previously added site icon on self-hosted Jetpack powered WP site, it is not removed from the corresponding WP.com site and stays the same as the old site icon. The bug was originally reported on [Calypso GitHub](https://github.com/Automattic/wp-calypso/issues/1857).

#### What I expected

After clicking on 'Remove' button in the Customizer -> Site Identity -> Site icon, I expected the site icon to be removed from the connected WP.com site too.

#### What happened instead

The `jetpack_site_icon_url` option on the connected WP.com site has the value of the removed site icon.

#### Steps to reproduce the issue

On a self-hosted WP site that is connected to WP.com through Jetpack, add a site icon first. Look into the Network Admin (A8c only) of the WP.com site for 'Jetpack site icon url'. It should point to the site icon. Now, remove the site icon from the self-hosted WP site and look into the Network Admin in WP.com again. There should be no 'Jetpack site icon url' or at least should be an empty string.

#### Solution

I played a bit with the Jetpack code and found out that in [class.jetpack.php](https://github.com/Automattic/jetpack/blob/master/class.jetpack.php#L525-L526), if I edit the code to look like this:

```php
} else if ( empty( $url ) ) {
    Jetpack_Options::delete_option( 'site_icon_url' );
}
```

it works. It's a quick'n'dirty solution (maybe) but I wanted to make sure I'm in the right place.

Thanks!

**Comment by rralian** [comment]
@lamosty It's probably best to submit your fix in a PR and gather feedback there.

**Comment by jeherve** [comment]
Related: #3156, where we're planning on removing all traces of the old Jetpack Site Icon.
