### ISSUE TITLE
Boost: Bullet notification not displaying correctly on Atomic sites

### ISSUE THREAD

**Issue by alinclamba** [Automattic/jetpack#39715]
### Impacted plugin

Boost

### Quick summary

The Jetpack Boost menu item shows a plain "1" instead of a red bullet notification when an alert needs to be addressed.

This happens on Atomic sites only. 

![Image](https://github.com/user-attachments/assets/437f274c-e8b2-40d7-a78b-cf0693219cb7)

### Steps to reproduce

1. On an Atomic site, install and activate Jetpack Boost.
2. Perform an action that triggers Jetpack Boost to require attention, such as changing the WordPress theme, which will prompt Boost to regenerate Critical CSS.
3. Navigate to the WordPress admin dashboard.
4. In the sidebar, locate the Jetpack menu, then observe the notification for Jetpack Boost.
5. Notice that instead of a red bullet or dot (indicating an alert), a plain number "1" is displayed next to "Boost."

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated 

📌 ACTIONS
- Triaged
- @jeherve, should we move this to Calypso and have it fixed there instead? I can't seem to trigger that notification bullet on self-hosted.

**Comment by jeherve** [comment]
> should we move this to Calypso and have it fixed there instead?

No, the logic lives here in the Jetpack repo. 👍
