### ISSUE TITLE
Travis CI: PHPUnit no longer runs multisite tests

### ISSUE THREAD

**Issue by ntwb** [Automattic/jetpack#3975]
Travis CI is no longer running multisite tests 😞 

It was removed in the switch from Grunt to Gulp https://github.com/Automattic/jetpack/commit/3b52571e90949154f272ffb96be6e12f5c85c0b8

Multisite testing functionality was added to Travis CI in https://github.com/Automattic/jetpack/commit/ad7720439867afe004bf7b7cda1729fbc4b8f545

Related: #3965

**Comment by ntwb** [comment]
Also #3955

**Comment by kraftbj** [comment]
This was fixed at some point, at least by https://github.com/Automattic/jetpack/pull/12662
