### ISSUE TITLE
Subscriptions: add a floating subscribe button

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#39772]
Add a floating subscribe button, which, when pressed, opens the subscribe modal:

<img src="https://github.com/user-attachments/assets/1c8ff61e-0a22-46ad-bab1-5e56ccdac16d" width="400"/>
<img src="https://github.com/user-attachments/assets/c25f6762-ce92-4ed4-93de-183ee1bcef70" width="600"/>

We now can render "button only" subscribe block variation, and the email will be asked in a modal.

The floating button would be enabled via "Jetpack -> Settings -> Newsletter" alongside popups and other placements:

<img src="https://github.com/user-attachments/assets/c8f3560a-8a32-4a34-b53c-93cb1d99f52d" width="400"/>

The button should be pulled from a template part, so that we can let folks jump in and modify the button's appearance, add some copy around it if they wish, etc.

Currently, this would clash with the "action bar" on WP.com sites:

<img src="https://github.com/user-attachments/assets/b7bce9a8-89fc-493e-978b-eb1fbb4a2cd3" width="600"/>

We should keep showing the button even when subscribed when site has paid subscriptions; the button should then nudge to upgrade.

**Comment by simison** [comment]
Follow-up to add tracking to floating button:

- D164339-code
- https://github.com/Automattic/jetpack/pull/39860

Whitelisting option on sync and adding to site-profiles:

- D164347-code

**Comment by StefMattana** [comment]
@simison that hasn't been shipped yet, correct? 
Asking as we need to update the docs here: https://jetpack.com/support/newsletter/

**Comment by simison** [comment]
@StefMattana the feature will ship in the next Jetpack v14 release on Nov 5th.

**Comment by simison** [comment]
WP.com/Calypso counterpart: 
- https://github.com/Automattic/wp-calypso/pull/96022
- D165358-code
- 2964-gh-Automattic/en.support-docs-content
