### ISSUE TITLE
Related Posts showing up on pages on Classic Themes

### ISSUE THREAD

**Issue by vinnykaur** [Automattic/jetpack#39783]
### Impacted plugin

Jetpack, None / Other

### Quick summary

The Related Posts section is showing up at the bottom of pages on sites using Classic themes or themes like Kadence and Divi. 

### Steps to reproduce

1. Activate a classic theme.
2. Enable the Related Posts feature from Settings → Reading.
3. Check the Homepage (set as static page) or any other page. 
4. The Related Posts section shows up on pages right above the footer. 

### A clear and concise description of what you expected to happen.

When enabling the related posts feature on a classic theme, the section show up only on posts and not pages. 

### What actually happened

The Related Posts section shows up on pages right above the footer. 

![Image](https://github.com/user-attachments/assets/3964528e-f061-4b8e-bc08-997956fb1bef)

![Image](https://github.com/user-attachments/assets/e73e9d6f-5ad6-477b-8e39-a8bbb0778abd)

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Currently, the 3 workarounds, I shared for the user are:

1. If the user doesn't want Related posts on either pages or posts, they should disable it using [this setting](https://wordpress.com/support/related-posts/#related-posts-classic-themes).
2. If they want to hide it from the pages, this CSS should help on premium plan and above as a temporary measure.
```
.page .jp-relatedposts {
    display: none !important;
}
```
3. For personal or below, the CSS won't work. However, they (or any plan) can try switching to a theme that uses a site editor.

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Affected tickets so far:

8871500-zd-a8c- Pique Theme
8873487-zd-a8c- Kadence
8873519-zd-a8c - Divi
8880771-zd-a8c - Venture

Also, tested on my test site with Pique and Twenty Nineteen, I could replicate the issue.

**Comment by inaikem** [comment]
📌 REPRODUCTION RESULTS
– Tested on Simple – Replicated
– Tested on Atomic – Replicated
– Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
– As described above.

📌 ACTIONS
– Bumping priority and pinging Groundskeepers.

**Comment by Neha93517** [comment]
8887265-zen
Hello-elementor theme

**Comment by jeherve** [comment]
This was done on purpose in #39730. @kraftbj We may have to revert.

I'm not sure what the best UX would be here, that would support both classic themes and block-based themes. Maybe we should expand the logic to support both, like #39784?

**Comment by jeherve** [comment]
Also reported in p1729063559535729-slack-CBG1CP4EN

**Comment by inaikem** [comment]
Oh, interesting! Is there an opt-out/in similar to the discussion checkboxes in the editor? I feel like this should be opt-in for Pages.

Reported here, too: p1729064879996949-slack-CB0B2G43X

**Comment by sajjadsaeed** [comment]
8888937-zen
Hello-Elementor theme

**Comment by nazilya06** [comment]
Another report: 8893132-zd-a8c

Katen Child theme

**Comment by nazilya06** [comment]
8886722-zd-a8c
Twenty Twenty theme

**Comment by kraftbj** [comment]
Fix is merged. It'll be deployed to Simple once the build processes finishes.

**Comment by supernovia** [comment]
Thanks @kraftbj  - any idea when it'll get to Atomic sites?
8893649-zd-a8c

**Comment by sajjadsaeed** [comment]
8892942-zen
Twenty Seventeen

**Comment by kraftbj** [comment]
@supernovia I tagged a new release for Atomic and would expect it to go out tomorrow during the US business day. internal ref: p9o2xV-4Ne-p2#comment-10295

**Comment by ricklabsdotn8** [comment]
@kraftbj Will this turn off the setting, and the users would need to re-enable it?

**Comment by kraftbj** [comment]
This is rolling to Atomic now.

@ricklabsdotn8 There isn't a setting. This will restore the previous behavior for sites using Classic Themes. For Block Themes, site administrators could already insert a Related Post block in templates for other CPTs, which with the original patch and maintained in this latest evolution of the fix, will now work properly.
