### ISSUE TITLE
Super Cache: How to exclude a page/post from caching programmatically

### ISSUE THREAD

**Issue by tapan-thapa** [Automattic/jetpack#39808]
Dear Team,

I am using "WP Super cache" and would like to exclude a page/post from caching programmatically.

I can use any shortcode or any other way like headers etc to return from single.php.

Please suggest if this is possible with Wp Super Cache.

Thanks

BR
Tapan Thapa

**Comment by haqadn** [comment]
You can define `DONOTCACHEPAGE` constant to `true` while serving any request and the page will be skipped from being cached.

https://github.com/Automattic/wp-super-cache/wiki/Developers-Start-Here#do-not-cache-this-page

**Comment by tapan-thapa** [comment]
Thanks.. It worked.
