### ISSUE TITLE
Connect: Can't connect my jetpack site. 

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#3984]
I am running the latest master. 

#### What I expected
To be able to connect.

#### What happened instead
Instead I am in a strange place where the UI gives me conflicting messages. And I don't acally seem to be connected 

#### Steps to reproduce the issue
I am not sure how I ended up in this place. My guess is that I deactivated the plugin while I was connected and this resulted in a this strange state. 

See this video https://cloudup.com/crSaSOlKPOP

**Comment by dereksmart** [comment]
Some things don't look right about your current master.  Have you re-built the client lately?  `npm run build-client` 

- The view should be much narrower
- The connect banner on plugins.php should be styled

**Comment by enejb** [comment]
I updated the build of the js. 
This is what I see now https://cloudup.com/cjyzt5TUOAh

**Comment by dereksmart** [comment]
@enejb that looks like the same video, or is it just a coincidence that your battery was at 6% in both videos?

**Comment by enejb** [comment]
@dereksmart no its the same video. Try this one https://cloudup.com/cYCQp2DsfUf.

**Comment by dereksmart** [comment]
@enejb try clearing `calypso_store` https://cloudup.com/cz7MTaBs38o

cc @johnHackworth

**Comment by enejb** [comment]
The indexDB seems to be clear https://cloudup.com/cL7g_eOFWQZ

**Comment by dereksmart** [comment]
you should see it when you're on the auth page (or anywhere else in calypso).  It won't be found in wp-admin

**Comment by enejb** [comment]
Yes that did the trick 👍 Thanks @dereksmart
