### ISSUE TITLE
Enhancement: Ability to clear content cache manually

### ISSUE THREAD

**Issue by anonemusic** [Automattic/jetpack#39852]
### Impacted plugin

Boost

### What

Need ability to clear content cache manually

### How

Hi,
When I update the content, I need to be able to clear the content cache manually so the changes will reflect immediately.

How long does Boost take to update the content updates, and is there any way to clear the cache manually? Any feedback would be appreciated.

**Comment by haqadn** [comment]
The page cache expires after 1 hour. Boost removes the expired files automatically. If you want to clear the cache manually, you can use the "Clear Cache" button. ![reYebt.png](https://github.com/user-attachments/assets/fc7f6a74-708e-4a5c-a980-e0f259c024b9)
