### ISSUE TITLE
Admin: Hello Dolly pushes masthead over

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#3986]
ensure hello dolly isn't interrupting our design flow :-)

![hello-dolly](https://cloud.githubusercontent.com/assets/214813/15587124/d29bbb3e-2355-11e6-8eed-3ca4741799fb.png)

**Comment by richardmuscat** [comment]
Is this still relevant with the new masthead design?

**Comment by eliorivero** [comment]
<img width="1151" alt="dolly1" src="https://cloud.githubusercontent.com/assets/1041600/17182332/7fdb223e-53f9-11e6-9474-e32bc148ad6c.png">
<img width="673" alt="dolly2" src="https://cloud.githubusercontent.com/assets/1041600/17182333/7fde7646-53f9-11e6-8062-811d95e5d9d8.png">
Still relevant.

**Comment by jeffgolenski** [comment]
@richardmuscat @eliorivero will be fixed in https://github.com/Automattic/jetpack/tree/fix/hello-dolly-positioning

**Comment by jeffgolenski** [comment]
Fixed in: https://github.com/Automattic/jetpack/pull/4565
