### ISSUE TITLE
Feature Request: Bluesky Autopost?

### ISSUE THREAD

**Issue by hansollkim** [Automattic/jetpack#39875]
### Impacted plugin

Social

### What

Please support automatic posting to Bluesky.

### How

Currently, Jetpack supports automatic posting to Facebook, Instagram, Mastodon and Threads. If you add Bluesky to this, you can support many social networks except for X (which is inevitably unusable). That means I can copy and paste one less time, and I believe many others will do the same.

**Comment by tehjaymo** [comment]
Related #30460

**Comment by jeherve** [comment]
That is indeed a duplicate of #30460. I'll consequently close this issue.
