### ISSUE TITLE
Form block: Proposal to add Prosopo as a captcha vendor option

### ISSUE THREAD

**Issue by light-source** [Automattic/jetpack#39890]
### Impacted plugin

Jetpack

### What

add Prosopo as a captcha vendor option for the form block

### How

Hello Jetpack Team!

We hope this message finds you well.

We are the team behind [Prosopo](https://prosopo.io/), a CAPTCHA solution focused on providing a privacy-friendly alternative to Google reCAPTCHA. We believe our solution would be a great addition to your plugin, offering users a more privacy-conscious choice. (We’re talking about your Forms feature).

We appreciate your time and understand that your capacity for implementing new features may be limited. That’s why we’d like to propose a collaboration: our WordPress expert could add the integration, and submit a pull request for your review.

Would you be open to reviewing and accepting a pull request that adds Prosopo as an available vendor option for your Form block?

The PR will adhere to WordPress Coding Standards and align seamlessly with your plugin’s existing architecture.

Look forward to hearing your thoughts.

Best regards,
The Prosopo Team

**Comment by mikestottuk** [comment]
@jeherve related WordPress.org forum ticket with my reply: https://wordpress.org/support/topic/proposal-to-add-prosopo-as-a-captcha-vendor-option-9/#post-18093769

**Comment by jeherve** [comment]
Related: #25019

Just like for this related issue suggesting adding reCAPTCHA, this is a feature that would be best added via an additional plugin. Folks can use the Jetpack plugin to add the contact form feature to their site, and can then use another plugin to handle protecting all forms on the site, whether they are contact forms or comment forms.

If folks want to use Akismet to protect their forms, they can enable [the Akismet plugin](https://wordpress.org/plugins/akismet/). If they want to use reCAPTCHA, they can use [this plugin](https://github.com/DevriX/jetpack-recaptcha). Maybe you could develop a Procaptcha plugin for WordPress, that would protect all forms installed on a site, whether they are Jetpack contact forms, comment forms, or even contact forms created with other plugins.

**Comment by light-source** [comment]
@jeherve Thank you for the reply. We'll follow the suggested approach and add support for Jetpack forms to the master plugin.
