### ISSUE TITLE
Form goes with the wrong email in some sites.

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/jetpack#39909]
### Impacted plugin

Jetpack

### Quick summary

On some sites, a Form block with a destination address different than the site owner address is set, form submission notifications go to the site owner.

### Steps to reproduce

On one of the affected sites:
1) Open the page containing the form in the editor.
2) Check the Form settings and the email set in the "Email to send to" field.
3) Visit the page containing the form on the Live sire.
4) Send a test submission.
5) Check the email logs.

For the workaround:
1) Edit the form and add the site owner's address along with the original address.
2) Test again.
3) Check email logs again, for both addresses.

### A clear and concise description of what you expected to happen.

The email should go to the email address set in the set in the "Email to send to" field.

### What actually happened

The email went to the site owner instead.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Workaround: add the site owner address along with the address initially set. When both addresses are there, the notification is sent to both.

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Context:
- 8857128-zd-a8c
- 8867031-zd-a8c
- p9F6qB-gom-p2#comment-63143
- p1729189094650399-slack-C03TY6J1A

**Comment by jeherve** [comment]
I am not able to reproduce the issue at the moment. I asked for more details in p9F6qB-gom-p2#comment-63217

**Comment by ariel-maidana** [comment]
Thank you @jeherve! I asked for the user's permission to run additional tests. Once they authorize us, I'll run the tests and document the results.

**Comment by ariel-maidana** [comment]
The user hasn't replied for now. I sent them a follow-up.

**Comment by supernovia** [comment]
@jeherve  we have another case here, but with a twist: this user updated the owner email address. All forms work except for the one on the front page, and that goes to the old email. Any ideas on what I can clear to fix that?
9084181-zd-a8c

**Comment by jeherve** [comment]
Closing as duplicate of #40108, which now has more information about the bug behind this. 

@supernovia I would recommend checking the front page's block attributes to see what is saved as the `to` attribute for that home page block. You can do so from the 'code' view in the editor. You can also edit that attribute from there.

**Comment by supernovia** [comment]
@jeherve  I've found that:
- the email address to: setting is not included in code view, even if I specify it in the form
- the only way to get it to show in the code view is to include the old site owner's email address, too
- then I can edit the code and change it to just the one email address, and that works ...
- however, it reverts if I make any changes to the front-page template

I also noticed in this case that the user is setting up a static website but using a Home template that is supposed to be based on posts, so it's counting the "origin" of the from as their Hello World post. I am not sure whether that's making any difference.
