### ISSUE TITLE
New UI settings links not taking me to the right place.

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#3990]
In the new UI Some of the links that me to the wrong place. 

#### What I expected
When I clicked on VaultPress Settings it should take me to the VaultPress settings page. 
Also the UI should know if I have VaultPress installed already and if that is not the case include not show the links but maybe links to install the plugin. ?

<img width="572" alt="screen shot 2016-05-26 at 13 37 33" src="https://cloud.githubusercontent.com/assets/115071/15589287/085bb01c-2347-11e6-81d4-2470950b9b39.png">

#### What happened instead
Instead of being taken to https://example.com/aaa/wp-admin/admin.php?page=vaultpress
I get taken to https://example.com/wp-admin/admin.php?page=vaultpress Which is not right.

#### Steps to reproduce the issue
In current master. Go to the UI and click on the settings links.

**Comment by eliorivero** [comment]
Should be fixed by #4057 
Can you please confirm?

**Comment by beaulebens** [comment]
Confirmed that @eliorivero's PR above fixes this issue.
