### ISSUE TITLE
Twitter timeline: remove widget ID requirement

### ISSUE THREAD

**Issue by niallkennedy** [Automattic/jetpack#3993]
Twitter no longer requires a widget ID generated through [twitter.com/settings/widgets](https://twitter.com/settings/widgets) to display a Twitter embedded timeline for a user, list, likes, or collection. A widget ID may still be provided by a Twitter user generating an ID for an embedded search timeline or from someone with a previously configured widget.

Treat widget id (`id` shortcode attribute) as optional when generating markup. Do not include a `data-widget-id` attribute when no widget ID provided. Provide an input for the expected datasource (e.g. Twitter username) in the widget config.

Remove "you need to create a widget at Twitter.com" help text for the Twitter embedded user timeline widget.

An [oEmbed API](https://dev.twitter.com/web/embedded-timelines/oembed) is available for generating markup for the provided Twitter profile URL given the widget options.

**Comment by kraftbj** [comment]
Marking this for 4.1, but we're getting late in that cycle, so fair warning that it might shift some. Thank you, as always, for alerting us @niallkennedy! 

P.S. If you could nudge anyone over there on https://github.com/twitter/twitter-text/pull/118/ ... ;-)

**Comment by nylen** [comment]
I just deployed support for widgets without IDs on WordPress.com - for now supporting user profiles only, as that is the most common use case.  You can get a feel for how it works by reading the updated [documentation page](https://en.support.wordpress.com/widgets/twitter-timeline-widget/).

I'll put together a PR with these changes in the next few days.

**Comment by jeherve** [comment]
@nylen Could you take a look at #3283 at the same time? If width and height aren't necessary, you may add that to your PR, maybe? It might be easier than having to rebase that other PR.
