### ISSUE TITLE
Embed block names with same name as the social icon blocks are causing confusions and also E2E failure

### ISSUE THREAD

**Issue by Imran92** [Automattic/jetpack#39965]
### Impacted plugin

Jetpack

### Quick summary

We've recently change the name of YouTube, Twitter etc blocks to YouTube Embed and Twitter Embed, here https://github.com/WordPress/gutenberg/pull/63371/files .

However, the name of the embedding block for Facebook and Instagram has not been changed. Because these two embed blocks are variations of embed blocks added by Jetpack introduced here https://github.com/Automattic/jetpack/pull/17192 .

So it looks confusing for users. Also causd E2E test failures because we couldn't select the correct Embed by name which we temporarily fixed by https://github.com/Automattic/wp-calypso/pull/95282.

To have these properly fixed, we should be changing the name to Instagram Embed so the intention and functionality are more easily understandable.

#### Insta has two blocks with same name and icon
![Image](https://github.com/user-attachments/assets/9db97f3f-8045-4c90-8bf8-dbcad3fa21ec)

#### Facebook has three!
![Image](https://github.com/user-attachments/assets/73867710-2290-4596-a2e2-45bba908a445)

The issue was initially created on the [Gutenberg repo](https://github.com/WordPress/gutenberg/issues/66087). But it turned out to be a Jetpack issue. So we are creating here with more details

### Steps to reproduce

1. Create a fresh simple site
2. Create a new post
3. Go to block inserter and search by either Instagram or facebook.

### A clear and concise description of what you expected to happen.

Easily understand which one is an Embed block

### What actually happened

Multiple blocks with same name

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by Robertght** [comment]
@Imran92 I can see you've assigned yourself to this so I'll mark this triaged on our board as well.
