### ISSUE TITLE
Boost: image cdn + redirection plugin causes 404s on JP Carousel gallery images

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#39971]
If a Jetpack Boost site has the Image CDN enabled, the [Redirection plugin](https://wordpress.org/plugins/redirection/) active, and they use a Jetpack Carousel gallery, they will see 404 errors when requesting an image in the gallery.

An extra /null request is made each time an image is loaded.

It also happens when the image CDN is enabled through Jetpack, so it's not only a Boost issue.

ref: https://wordpress.org/support/topic/tiled-mosaic-causing-null-404s/

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Replicable outside of Dotcom – No (Used a JN site)

📌 ACTIONS
- Triaged > In Triage
- Requested author feedback

📌 Message to Author
👋🏻 @donnchawp Are you still able to reproduce this? I [used a JN site for this](https://dreamily-pleased.jurassic.ninja/gallery-test/), and I was not able. Added the Redirection plugin, and activated the JP CDN

**Comment by donnchawp** [comment]
I can't replicate it any more. Something got fixed in the last 3 weeks.

The customer's site is still showing the problem but I'll reply on their ticket and ask them to update their plugins and WordPress. Let's leave this ticket open until I hear back from them. Maybe they can add more detail about their settings.

**Comment by tanjoymor** [comment]
@donnchawp Just checking to see if you've heard back from the customer on this yet and if this issue can be closed now?

**Comment by donnchawp** [comment]
No, there hasn't been a reply from the user. I'll try to replicate this again tomorrow and if I can't, I'll close this ticket.

**Comment by chatoxz-wp** [comment]
@donnchawp They sent a new reply:

> Thanks, I have updated all plugins and wordpress, clear the cache, and retested the above URL, and got the same null 404 entries in the redirect plugin i’m afraid

**Comment by alinclamba** [comment]
For DA: pinged devs on Slack: p1733741543040719-slack-C016BBAFHHS

**Comment by donnchawp** [comment]
I was able to replicate this problem again.
