### ISSUE TITLE
Site Editor: list view layout in Data Views is not displayed correctly

### ISSUE THREAD

**Issue by jartes** [Automattic/jetpack#39981]
### Impacted plugin

Jetpack

### Quick summary

When going to any listing with the List View option, like Templates or Pages, the layout is off: 

![Image](https://github.com/user-attachments/assets/912e0dcd-4eb3-4c41-b587-141df1787c72)

I'm able to reproduce this on Simple Sites, and with a JN site with the GB plugin active (v 19.5.0), and Jetpack connected. 

### Steps to reproduce

1. Start with a site with the latest GB plugin version 19.5.0, and JP connected. You can use a Dotcom Simple Site, too. 
2. Go to Appearance → Editor → Templates (or Pages)
3. Change the display view option to List. 
4. Check the listing.

### A clear and concise description of what you expected to happen.

Seeing the list with its correct layout.

### What actually happened

The listing doesn't have the correct layout.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by jartes** [comment]
Escalation: p1730370103566939-slack-C02FMH4G8

**Comment by jeherve** [comment]
@manzoorwanijk It seems that the import in #39230 (see e63e6cf68474bed79b8aef556de02e97e70f386e) bled over to the styles in the site editor. Do you think we could do without it? Could you take a look at it?

Thank you!

**Comment by manzoorwanijk** [comment]
> [@manzoorwanijk](https://github.com/manzoorwanijk) It seems that the import in [#39230](https://github.com/Automattic/jetpack/pull/39230) (see [e63e6cf](https://github.com/Automattic/jetpack/commit/e63e6cf68474bed79b8aef556de02e97e70f386e)) bled over to the styles in the site editor. Do you think we could do without it? Could you take a look at it?

I am looking into it. Will report back when I find a solution.

**Comment by manzoorwanijk** [comment]
#39991 should fix the issue. Please help test that PR.
