### ISSUE TITLE
Post By Email setting creates a confusing state

### ISSUE THREAD

**Issue by jessefriedman** [Automattic/jetpack#3998]
PBE settings include an unnecessary button to disable the feature creating a 3rd state. 
![screen shot 2016-05-27 at 10 24 58 am](https://cloud.githubusercontent.com/assets/1749986/15610986/2edc8c7a-23f6-11e6-8964-f0ed9b485e21.png)

The "Disable Post by Email" button seen above turns off PBE functionality but leaves the feature enabled. Resulting in the existence of these three states:
“On and Enabled” 
“On and Disabled” 
“Off”

We should remove this button from the settings area.  Once we do that we should also consider how we would handle it for anyone who has already clicked the button. Possibly just disabling the PBE feature all together.

**Comment by jeherve** [comment]
Coming back to this; could you test what happens when you click on "Disable Post by Email"? Does it disable PBE for everyone on the site, or just for your user?

**Comment by abidhahmed** [comment]
The UI has since changed a lot since this issue was created, and the button no longer exists. I'll go ahead and close this, please feel free to reopen if required. Thanks!
