### ISSUE TITLE
Gutenberg v19.6.0-rc.2 Removes getCanvasMode()

### ISSUE THREAD

**Issue by holdercp** [Automattic/jetpack#39997]
### Impacted plugin

mu wpcom

### Quick summary

**This is a defect discovered during testing the upcoming Gutenberg 19.6.0 release. It is not live.**

The Gutenberg[ v19.6.0-rc.2 release](https://github.com/WordPress/gutenberg/releases/tag/v19.6.0-rc.2) removes the `getCanvasMode()` API in Wordpress/gutenberg#66213 from the `edit-site` store. The `wpcom-block-editor-nux` plugin is using this API and is now unable to load with this GB version installed.

This plugin should be updated to determine the canvas state from the URL params as suggested in the GB PR:

Using the URL for this state is compatible with older GB releases so this can be deployed before v19.6.0 lands.

Related to Automattic/calypso#95960

### Steps to reproduce

1. Install GB v19.6.0-rc.2 on a site
2. Install a Full Site Edit theme
3. Navigate to Appearance -> Editor
4. Check console logs and notice errors relating to the `help-center`, `wpcom-block-editor`, and the Jetpack `wpcom-block-editor-nux` plugins
6. Click into the canvas to edit
7. Notice the errors in the UI

### A clear and concise description of what you expected to happen.

The mentioned plugins load as normal.

### What actually happened

- Visible UI errors
- Console errors

![Image](https://github.com/user-attachments/assets/bce9a436-a4f5-4356-b20b-b0e53b47827f)

### Impact

All

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by jeherve** [comment]
cc @Automattic/lego who worked on bringing the WordPress.com block editor NUX to mu-wpcom a few months ago. Is that something you could look at?

Thank you!
