### ISSUE TITLE
Facebook Embed Block Fails to Display Facebook Post on Mobile Devices

### ISSUE THREAD

**Issue by bizanimesh** [Automattic/jetpack#40022]
### Impacted plugin

Jetpack

### Quick summary

The Jetpack's Facebook embed block is not showing posts from Facebook when we check it from the browser on mobile devices (the issue is at both Android and iOS devices).

Previous discussion: p1730708070109379-slack-C02JJ910CNL

### Steps to reproduce

1. Connect the Jetpack plugin to the site.
2. Create a new post and add the Facebook embed block.
3. Add a post link from Facebook to that Block.
4. Publish the post and check the post from the browser on a Mobile device.

We can notice the post from Facebook on mobile device is not appearing, but we can see the post if we will check it from the browser on a desktop device.

### A clear and concise description of what you expected to happen.

The Facebook embed block should show the post on mobile devices as well.

### Impact

All

### Available workarounds?

No, but the platform is still usable.

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

**Comment by jeherve** [comment]
Are you able to access Facebook.com in that browser? Do you see the embed when logged out of Facebook, or logged in?

**Comment by bizanimesh** [comment]
> Are you able to access Facebook.com in that browser?

Yes, I can access Facebook.com on the mobile device browser.

> Do you see the embed when logged out of Facebook, or logged in?

No, I don't see the embed on the site when logged out of Facebook, or logged in on mobile device browser.

**Comment by jeherve** [comment]
Do you see this embed on your phone?
https://jeherve.com/fb.html

**Comment by bizanimesh** [comment]
No, I can't see it on a mobile device ([screenshot](https://github.com/user-attachments/assets/c084e21d-b1c5-49d6-a8d2-41bec90c458c)), but I can see it on a desktop device.

**Comment by jeherve** [comment]
Ok. This seems to point towards a problem with Facebook themselves, since that embed happens outside of WordPress. I also tried with a regular iFrame copied directly from Facebook.com (see embed code below) and experienced the same issue. At this point, I would recommend contacting Facebook about this, since this seems to be an issue with their platform directly. This is not something we will be able to fix or work around on our end:
https://developers.facebook.com/support/bugs/

```html
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fjetpackme%2Fposts%2Fpfbid027XsD2VfjeEC8uQFXwr8rHsjcth8nk6ukfFNT89ynC7BnJew4QWb5LyARdJJ9He9il&show_text=true&width=500" width="500" height="250" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
```

**Comment by manzoorwanijk** [comment]
I looked into this a bit and it seems like Facebook stopped supporting that for mobile devices:

> The Embedded Posts and Page Plugin are exclusively available for Web.

[Facebook Social Plugins FAQs](https://developers.facebook.com/docs/plugins/faqs#faq_1585575021764180)

Here are a few issues users reported to Facebook:
- https://developers.facebook.com/community/threads/1044180407107320/
- https://developers.facebook.com/community/threads/550478830783215/

**Comment by supernovia** [comment]
Thank you @jeherve !
