### ISSUE TITLE
Boost: Expand cornerstone pages UI on first load

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#40037]
Since Cornerstone Pages is a big deal for Boost, presenting it expanded by default will draw the user's attention to it. It's less likely they will glance over it.

**Comment by haqadn** [comment]
We can decide to do it later based on the metrics.

**Comment by dilirity** [comment]
I think it makes the most sense to have this in the initial version. I don't see any benefit if we add it later.

**Comment by dilirity** [comment]
After discussing this with @haqadn we decided to not do it.
