### ISSUE TITLE
Activating Google Analytics generates "error undefined failed to activate. Api404Error" on WordPress.com sites

### ISSUE THREAD

**Issue by philnick206** [Automattic/jetpack#40039]
### Impacted plugin

Jetpack

### Quick summary

When clicking Activate Google Analytics from the Jetpack Dashboard (/wp-admin/admin.php?page=jetpack#/my-plan) the following error is displayed: `error undefined failed to activate. Api404Error`

![Image](https://github.com/user-attachments/assets/90dae4d0-7c44-41bc-b8c1-2bd8c2facfd2)

### Steps to reproduce

1. On an Atomic site on WordPress.com, navigate to Jetpack Dashboard > My Plans
2. Click on Activate Google Analytics

### A clear and concise description of what you expected to happen.

Not sure, but not expecting an error

### What actually happened

Error message is shown

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Reported in 8986774-zd-a8c

**Comment by jeherve** [comment]
Related discussion: p1730741711536659-slack-C0299DMPG
