### ISSUE TITLE
External Media: Adapt image selection

### ISSUE THREAD

**Issue by bogiii** [Automattic/jetpack#40038]
Project thread: pcmemI-3sx-p2
Related PR: https://github.com/Automattic/wp-calypso/pull/95880

**Comment by jeherve** [comment]
@bogiii Is there any chance you could add some extra context for this issue (contents, labels)?

Thank you!

**Comment by bogiii** [comment]
Hey @jeherve 👋 

For more context, here is the Project Thread with all the details: pcmemI-3sx-p2
