### ISSUE TITLE
Incompatible block(s?) with latest Gutenberg trunk: Site editor crashes

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#40055]
### Impacted plugin

Jetpack

### Quick summary

Some changes were made in https://github.com/WordPress/gutenberg/pull/63401 that causes one or some of the Jetpack blocks to crash the site editor. 

Honestly I'm not sure if it's a bug with how Jetpack is registering blocks, or if there needs to be more defensive code in Gutenberg. I'm having trouble tracking down the specific block that is causing the error to get minimal reproduction steps. 

### Steps to reproduce

1. Activate the Jetpack plugin
2. Checkout and build gutenberg commit [48341a1](https://github.com/WordPress/gutenberg/commit/48341a13f7ca383830fecc328b3e7e3131ba831a)
3. Visit `/wp-admin/site-editor.php`

### A clear and concise description of what you expected to happen.

No crash.

### What actually happened

Blank page. With console error 

![Image](https://github.com/user-attachments/assets/8ecf7dd0-8e9f-48ef-84d9-9d97845fac98)

```
process-block-type.js:153 Uncaught TypeError: Cannot set property supports of #<Object> which has only a getter
    at process-block-type.js:153:25
    at Array.map (<anonymous>)
    at process-block-type.js:151:46
    at thunk-middleware.js:4:11
    at index.js:24:12
    at promise-middleware.js:20:9
    at Object.dispatch (resolvers-cache-middleware.js:45:10)
    at Object.apply (index.js:228:12)
    at private-actions.js:34:30
    at thunk-middleware.js:4:11
```

### Impact

All

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Turn off Jetpack Blocks module. 

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by jeherve** [comment]
@Automattic/jetpack-vulcan Is that something you could check? This is something we'll need to fix (or report to the Gutenberg plugin) before the next Gutenberg release.

Thank you!

**Comment by coder-karen** [comment]
I've created a PR to fix the issue from our end (the issue being related to the behavior of the object that the `supports` property is exported in), but it would still affect anyone with an older version of Jetpack. I've [left a comment](https://github.com/WordPress/gutenberg/pull/63401#discussion_r1832394335) on the Gutenberg PR to see if something can be put in place as this would likely affect other plugins too.

**Comment by andrewserong** [comment]
A fix has landed in Gutenberg trunk: https://github.com/WordPress/gutenberg/pull/66849 (thanks again @coder-karen for flagging!)

I believe that covers the issue reported here, but please open another issue in Gutenberg if anyone encounters any further issues!

**Comment by coder-karen** [comment]
Thanks again @andrewserong for the fix! Also thank you @dereksmart for spotting and reporting the breakage as well.
