### ISSUE TITLE
Subscribe Block: cannot edit submit button label

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#40072]
### Impacted plugin

Jetpack

### Quick summary

When editing an existing Subscribe block in the site editor, we can only edit the submit button text one letter at a time.

### Steps to reproduce

1. Start with a site that's connected to WordPress.com.
2. Go to Jetpack > Settings > Newsletter and enable Subscriptions.
3. Go to Appearance > Editor and add the Subscribe block to one of your templates.
4. Click on the subscribe block and check the block sidebar settings. 
5. There, open the "Settings" panel, and click to update the "submit button label"

### A clear and concise description of what you expected to happen.

I would expect to be able to delete and then type in some next text.

### What actually happened

When tying some text, only one letter is added to the field, and then it goes out of focus. We must click on the field again to enter another single letter.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by lezama** [comment]
> When tying some text, only one letter is added to the field, and then it goes out of focus. We must click on the field again to enter another single letter.

I tried both locally and using jurassic.ninja and I couldn't repro!
Any js console errors?

**Comment by simison** [comment]
Knowing Gutenberg/WP version would be helpful.

**Comment by jeherve** [comment]
I am able to reproduce with the latest version of WordPress, latest Jetpack Stable, and no Gutenberg:

https://github.com/user-attachments/assets/91f1608e-87fa-4d99-9c42-e26a0415d78d

**Comment by lezama** [comment]
hmm, maybe it is a browser thing? Same versions, no plugins and no errors for me in Chrome

https://github.com/user-attachments/assets/81fa6e37-0cde-4f44-981c-353bd10943ab

**Comment by jeherve** [comment]
Interesting! I was using Firefox (133.0b2 (aarch64)) in that test. I'm not able to reproduce in Chrome either.

**Comment by lezama** [comment]
Curious if it is something particular to the Subscribe block or if it happens with a core button too.

**Comment by lezama** [comment]
I was able to reproduce this issue in Firefox. In parallel I learned that core button's text can’t be changed from the block settings 😊.

I propose we align with core by removing the setting: https://github.com/Automattic/jetpack/pull/40099
