### ISSUE TITLE
Boost: ISA UI not updating even though requests are coming in

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#40082]
Related https://github.com/Automattic/jpop-issues/issues/9206#issuecomment-2461464109

For some reason the UI doesn't update on that site. You can start the analysis, but the UI reverts to the initial state. Polling for data is working, but the UI never updates

![Image](https://github.com/user-attachments/assets/481ceb95-2ef3-4627-8fda-2f1f1fcb8e16)

**Comment by dilirity** [comment]
The issue has been identified.

The UI doesn't update because Boost is expecting a static home page set.

This website only has a posts page set.

![Image](https://github.com/user-attachments/assets/aefe0529-ee69-46fd-88e2-2890d67ed042)

Fix will be created today and shipped in the upcoming 3.6.0 release.

**Comment by StefMattana** [comment]
That is ref ticket 9003990-zen
@dilirity, should we ask the user to change those settings so the feature works, or can the user try another workaround meanwhile? 

Do we have an ETA for the new Boost release I missed seeing? Thanks for your help with this one ⭐

**Comment by dilirity** [comment]
@StefMattana hey!

The next Boost release is probably going to happen either next week or the week after that.

As for the settings, that will allow them to use the feature, but I don't know if they would be okay with having a static front page since their home page lists posts.

**Comment by chatoxz-wp** [comment]
I updated the user about this. I didn't ask them to change the homepage but mentioned that the issue was related. To make the experience better, I gave them a complementary month.
