### ISSUE TITLE
Serve all Jetpack js files through Photon/WP.com

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#401]
Would it be possible to serve all Jetpack js files through Photon/WP.com when Photon is activated? If Jetpack requires Photon to be enabled before to do, we would make sure that people know about this and can opt out if they want to deregister some of these resources to load their own instead.

We already serve quite a lot of resources through WordPress.com:
- devicepx-jetpack.js (Retina)
- e-201306.js (stats)
- gprofiles.js (Gravatar Hovercards)
- s.gravatar.com/css/services.css (Gravatar Hovercards)
- noticons.css (notifications)
- admin-bar-rest.css (notifications)
- mustache.js (notifications)
- postmessage.js (notifications)
- notes-rest-common.js (notifications)
- admin-bar-rest.js (notifications)
- videopress.js (VideoPress)

Wouldn’t it make sense to load the rest of the resources from WordPress.com?

- jetpack-carousel.js (Carousel)
- tiled-gallery.js (Tiled Galleries)
- sharing.js (Sharedaddy)
- sharing.css (Sharedaddy)
- jquery.spin.js
- spin.js
- infinity.js (Infinite Scroll)
- infinity.css (Infinite Scroll)
- widget-grid-and-list.css (Widgets)
- widgets.css (Widgets)
- slideshow-shortcode.css (Widgets)

Ported from plugins.trac:
- https://plugins.trac.wordpress.org/ticket/1826

Related:
- #400 (for the opposite argument)

**Comment by samhotchkiss** [comment]
We've decided not to address this as the development resources required would take focus away from our current goals.

**Comment by biitlog** [comment]
Hey guys,

If you are using a CDN, have you ever tried to disconnect Photon? See what happens at PingDom or PageSpeed Insights. ;-)

Best
Carlos
[TekTuts](https://tektuts.com)

**Comment by jeherve** [comment]
Noting that this was addressed in #10102
