### ISSUE TITLE
My videos stopped uploading to media [wordpress org & VideoPress]

### ISSUE THREAD

**Issue by perr124** [Automattic/jetpack#40138]
### Impacted plugin

VideoPress

### Quick summary

Hi everyone, The issue I am experiencing is that video files specifically are failing to upload to WordPress, even though other media types, like images, upload without any problems. It appears to be a restriction or error isolated to video files, not a general media upload issue. The only difference here is that video uploads using VideoPress. which hasn’t been an issue till a few days ago. Video upload just stalls without any message (attached Image)

I verified that the server has ample disk space and memory, so resource limitations aren’t the issue. Also updated reqconfig and php.ini seems to be fine.![Image](https://github.com/user-attachments/assets/4630f775-913b-4a11-bb7a-51d94e5bbaf7)

### Steps to reproduce

1. Click media in wordpress dashboard
2. try uploading new video

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to upload a video to an Atomic site without issues.

📌 ACTIONS
- Triaged
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
👋🏻 @perr124 thanks for reporting this, but I could not replicate this. I'd suggest contacting our Jetpack Support team if you are still having issues when uploading videos to VideoPress: https://jetpack.com/contact-support/?rel=support
