### ISSUE TITLE
Notice functionality updates needed

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#4014]
<img width="761" alt="welcome-notice" src="https://cloud.githubusercontent.com/assets/214813/15656670/b2677dba-2677-11e6-9720-92193b5d040e.png">

- [ ] Ensure "Welcome Notice" is only displayed after a user connects and surpasses Jumpstart (doesn't matter if they utilize or skip it)
- [ ] Ensure "Welcome Notice" is only displayed **once** on the dashboard after a user connects

originally outlined in: https://github.com/Automattic/jetpack/pull/3974

**Comment by richardmuscat** [comment]
Closing: We're not showing any welcome notices.
