### ISSUE TITLE
Admin page: New navigation

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/jetpack#4019]
Need to finalise and implement an information architecture for the navigation we're happy with for v1 of the new Admin page.

Decisions
- [x] decide what the nav is: need to decide on actual text and groups
- [x] decide whether there's an "all settings" page vs "only split up"
- [x] decide whether settings are organised alphabetically or otherwise
- [x] decide on the feature sub groups
- [x] decide where the 'general settings' live

Tasks
- [ ] build out new header (dev)
- [ ] update the nav items and contents (dev)

**Comment by MichaelArestad** [comment]
Ad per our discussion, it looks like we're willing to try this concept:

![image](https://cloud.githubusercontent.com/assets/1123119/16048289/b987b778-3210-11e6-9ff1-919f5599773a.png)

The biggest change is the removal of the header. The way to navigate between settings and the JP dash will be via the WP side nav (reactified, of course).

I created a separate issue for the rearranging of settings to along with this: https://github.com/Automattic/jetpack/issues/4116

* I think we can try not having an All section at first.
* Settings should not be alphabetized, but instead, ordered by importance and popularity.

**Comment by richardmuscat** [comment]
@MichaelArestad looks good to me. I would only suggest calling the sub-nav item "Dashboard" not "Jetpack" otherwise its "Jetpack, Jetpack, Settings" (cc @dereksmart )

**Comment by jessefriedman** [comment]
@MichaelArestad what happens when you hit the search icon on the right?

**Comment by MichaelArestad** [comment]
Yep. Jetpack should be Dashboard and the search shouldn't exist on the Dashboard views (for now).

![image](https://cloud.githubusercontent.com/assets/1123119/16089221/5d052fb2-32e7-11e6-966e-69d0ae46cea2.png)

**Comment by richardmuscat** [comment]
@MichaelArestad / @dereksmart 

So to be clear about other items:
- We are **removing Omnisearch** from the sidebar
- We are **removing Stats** from the sidebar

We haven't clarified:
- Akismet (if installed)
- Vaultpress (if installed)

I'm of the opinion that we keep Akismet and Vaultpress (below settings) in the side nav as they are now.

**Comment by MichaelArestad** [comment]
As I mentioned in our recent hangouts, I'm of the opinion that VaultPress and Akismet should be moved out of the subnav and put as a top level item as they are when JP isn't installed. Once we integrate them, something like Antispam and Backups might make their way into the sidebar, but we'll see when we get there. Thoughts?

**Comment by dereksmart** [comment]
> I'm of the opinion that we keep Akismet and Vaultpress (below settings) in the side nav as they are now.

+1 until they are better represented in the Jetpack UI

**Comment by richardmuscat** [comment]
@michaelarestad can you explain the benefit of that to users? For everyone using VaultPress and Jetpack already we're just confusing them.

**Comment by richardmuscat** [comment]
Closing in favour of this: https://github.com/Automattic/jetpack/pull/4306
