### ISSUE TITLE
Admin Page: Design changes to "At a Glance"

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/jetpack#4020]
Various changes are required to the At a Glance view to make it richer and more useful to the user.

Small(ish) layout things
- [x] Remove "Site health" section and merge its contents with "Site security"
- [x] Call "Site security" "Security"
- [x] Call "Traffic Tools" "Performance" and have it only contain the Photon block
- [x] Add a block for "Automated fixes"
- [x] Review text snippets

Bigger design things
- [x] "Collapsed" design for when stats has nothing to show
- [x] Much more prominent CTAs for inactive items (toggles?)
- [x] A compelling design for the in/active versions of Photon using images in media library
- [x] If we don't have useful info to show for the large boxes let's make them smaller?

**Comment by jeffgolenski** [comment]
See jpop design for mockups at this point.

**Comment by jeffgolenski** [comment]
@richardmuscat " Add a block for "Automated fixes" what is this?

**Comment by MichaelArestad** [comment]
@jeffgolenski In the future, let's just have mockups and discussion here.

**Comment by richardmuscat** [comment]
> "Add a block for "Automated fixes" what is this?

@jeffgolenski the "Security Scanning" feature does both the scanning as well as the automatic fixing of certain security flaws.

As of this week this feature has now been split such that if you're on the Premium plan ($99) you get security scanning _but you only get the automated fixing functionality in the Pro plan ($299)_.

(Previously the scanning part was only available in Pro at $299.)

So I was originally thinking that we need (somewhere) another card to highlight this 'new' feature. But actually its an 'upgrade' of the security scanning so maybe it can just be dealt with in the way we are doing with Akismet. Ie: even though you have it with the 99 plan there is still an upgrade available.

**Comment by jeffgolenski** [comment]
There have been a lot of design changes to the AAG dashboard within the past few weeks, which are located here: 

https://cloudup.com/cedmx-z4lLK

@dereksmart The design master thread on our p2 has a lot of explanation for you. Instead of reposting that here, just check that out under the "i7" link. Feel free to ping me with any questions!

**Comment by richardmuscat** [comment]
Haz PR: https://github.com/Automattic/jetpack/pull/4440
