### ISSUE TITLE
Search / My Jetpack: Search card shows upsell even though the site already uses Jetpack Complete

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#40225]
### Impacted plugin

Jetpack

### Quick summary

Ref: p1HpG7-uVU-p2

Search card: Says “Get plan” / “needs plan” when it’s already owned via Complete.[5:20—5:30]

![Image](https://github.com/user-attachments/assets/32f7e593-dd62-4de3-9ffb-d365c075ebfa)

### Steps to reproduce

1. Start with a site where you've installed Jetpack
2. Purchase Jetpack Complete
3. Go back to wp-admin > Jetpack > My Jetpack

-> You'll see an invitation to "Get plan" on the Search card, even though Jetpack Complete is installed on the site.

> [!NOTE]
> Is it possible to have to purchase an additional Search plan on top of Complete on sites with a large number of records?

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by jeherve** [comment]
Related: #39762

**Comment by robertsreberski** [comment]
It is fixed by the same PR @elliottprogrammer merged: https://github.com/Automattic/jetpack/pull/39816
