### ISSUE TITLE
Newsletter: Disabling Newsletter Doesn't Remove It from Post Editing

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#40230]
### Impacted plugin

Jetpack

### Quick summary

When you disable Newsletter in the Jetpack Settings, it still displays in the post editing and publishing UI

### Steps to reproduce

1. Disable Newsletter in settings
2. Add a new post and see that the newsletter preview still displays

### A clear and concise description of what you expected to happen.

If I elect to disable Newsletter, I expect the elements to be removed from the UI.

### What actually happened

![Image](https://github.com/user-attachments/assets/674c7daa-ece5-4160-a98c-7097a8596ae0)

![Image](https://github.com/user-attachments/assets/cd225b29-c220-4dd9-be91-a231798378ba)

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

Tested in Jetpack v14

**Comment by bobmatyas** [comment]
Originally reported here: https://wordpress.org/support/topic/how-to-completely-disable-jetpacks-newsletter/

**Comment by bobmatyas** [comment]
@Automattic/zap Could y'all take a look at this one? I moved it to your board.

**Comment by simison** [comment]
Yep! PR in progress: https://github.com/Automattic/jetpack/pull/39802

**Comment by simison** [comment]
I'll actually close this as duplicate of https://github.com/Automattic/jetpack/issues/39800
