### ISSUE TITLE
Publicize to Bluesky: support hashtags in Publicized posts

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#40243]
### Impacted plugin

Jetpack, Social

### Quick summary

Bluesky supports hashtags, just like Twitter does. Hashtags in posts are automatically linked and allow for a search:

![Image](https://github.com/user-attachments/assets/2e562ba6-fa7d-4af5-a26f-7b591b1369c6)

However, hashtags posted via Publicized posts are not auto-linked:

![Image](https://github.com/user-attachments/assets/06a8beff-3b9c-43d9-84b8-d98668c814b5)

### Steps to reproduce

1. Start with a site that's connected to WordPress.com.
2. Go to Jetpack > Settings > Social
3. Connect your site to your Bluesky account.
4. Go to Posts > Add New
5. Write a new post
6. Hit publish
7. In the pre-publish panel, customize your Publicize message to include a hashtag.
8. Confirm publish

### A clear and concise description of what you expected to happen.

I would expect the post that gets posted to Bluesky to include a linked hashtag.

### What actually happened

The hashtag is not linked.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

This was also reported in https://github.com/Automattic/jetpack/issues/30460#issuecomment-2483597566

**Comment by spsiddarthan** [comment]
https://docs.bsky.app/docs/advanced-guides/post-richtext#rich-text-facets

**Comment by gmjuhasz** [comment]
Hastags are now supported with D167094-code
