### ISSUE TITLE
Premium Content Block: Button outline style not working

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#40292]
### Quick summary

Applying "outline" style to buttons inside the Premium Content Block doesn't work as expected - it doesn't match the active theme's outline style for buttons.

### Steps to reproduce

Simple Sites:

1. Activate Illustratr theme
2. Add standard Buttons block to page, and set style to Outline.
3. Add a Premium Content block, and set one of the style of one of the buttons to Outline. Note the text color changes to gray, but the background is not transparent, which makes the text unreadable.

![Image](https://github.com/user-attachments/assets/6a319cdb-a5a1-4942-ad73-1e33de7a349d)

Also replicated in Assembler and TT4 themes - in that case there was no visual difference after applying style "Outline" to one of the buttons.
This was originally reported in https://github.com/Automattic/themes/issues/7958 but I moved it here after investigating.

### What you expected to happen

I expected the outline style to be applied the same way it works for core Buttons block as per theme style.

### What actually happened

After changing a button style to "outline" it either doesn't change appearance at all (TT4, Assembler), or looks unreadable (Illustratr).

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by jeherve** [comment]
Moving this to the Jetpack repo, where the Premium content block is developed.

**Comment by chrisfromthelc** [comment]
https://github.com/Automattic/jetpack/pull/40638
