### ISSUE TITLE
Write Brief availability in other languages

### ISSUE THREAD

**Issue by bizanimesh** [Automattic/jetpack#40315]
### Impacted plugin

Jetpack

---

We'd love to see the Write Brief feature supporting languages other than English.

We have seen some users requesting that, so this is a GitHub issue to gather interest and see if this is something to prioritise due to popular requests.

Project reference: https://github.com/Automattic/jetpack/pull/39828

_The original issue is at https://github.com/Automattic/jpop-issues/issues/9292 - transferred the issue to this repo for better tracking of the requests._

**Comment by bizanimesh** [comment]
- 8920929-zd-a8c - Requested in Italian
- 9042128-zd-a8c - German

**Comment by jeherve** [comment]
I'll close in favor of #40029, and move the ticket references there.
