### ISSUE TITLE
Shortcode: Polldaddy JS 404

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#4032]
When using an Infinite Scroll enabled theme with the PD shortcode, a 404 for `modules/shortcode/js/polldaddy-shortcode.js` is seen in the console.

690c9baae8046f448f8b05b242372cdac694a882 seemed to add reference to the file, but didn't include it.

**Comment by oskosk** [comment]
Closing as this is no longer an issue. See gif below


**JS file loaded properly in the console**

![polldaddyworking](https://user-images.githubusercontent.com/746152/31821954-3deccfa8-b57d-11e7-9870-732900b34975.gif)

**Comment by kraftbj** [comment]
The file referenced ( https://github.com/Automattic/jetpack/blob/master/modules/shortcodes/polldaddy.php#L306 ) is still not present and still causing a 404.

Steps to reproduce:
1. Twenty Fifteen, ensure IS is set to load on scroll.
2. Add in a post that would appear after the scroll (not sure this is required, but what I did).
3. In the post, add a poll using the shortcode like `[polldaddy poll="7721710"]`
4. Console: 
![screen shot 2017-10-23 at 17 34 28](https://user-images.githubusercontent.com/88897/31916466-78fd70fa-b818-11e7-9609-78e6a4855df4.png)

**Comment by oskosk** [comment]
Alright, thanks for the details @kraftbj. Will re-check. Thought I was testing the same conditions. Sorry for having closed it!

**Comment by designsimply** [comment]
Tested and confirmed using the testing steps provided.

![screen shot 2018-04-05 at thu apr 5 10 37 06 pm](https://user-images.githubusercontent.com/1119271/38403604-f35e8bce-3921-11e8-8691-97b304738544.png)
<sup>Seen at https://design5279.wordpress.com/page/2/ using Firefox 59.0.2 on macOS 10.13.3.</sup>

The console error in Firefox says:

> TypeError: _$(...) is null
> PDV_go7721710
> https://static.polldaddy.com/p/7721710.js:81:13774
> &lt;anonymous&gt;
> https://static.polldaddy.com/p/7721710.js:81:17192

**Comment by jeherve** [comment]
This was fixed in #11814
