### ISSUE TITLE
Array to string conversion in sharedaddy/sharing-service.php on line 1243

### ISSUE THREAD

**Issue by galbaras** [Automattic/jetpack#40338]
### Impacted plugin

Jetpack

### Quick summary

I'm seeing lots of the following messages on PHP 8.2:

`PHP Warning:  Array to string conversion in [ROOT]/wp-content/plugins/jetpack/modules/sharedaddy/sharing-service.php on line 1243`

On GitHub, it's line 1247: `return $text . $sharing_markup;`, which implies that `$text` is passed as an array to `sharing_display()`, and its type isn't confirmed.

### Steps to reproduce

Not sure. I think this just happens when posts/pages are rendered.

### A clear and concise description of what you expected to happen.

No warning. Maybe check the input

### Impact

One

### Available workarounds?

There is no user impact

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by jeherve** [comment]
> which implies that $text is passed as an array to sharing_display(), and its type isn't confirmed.

It does indeed. While we certainly can be more defensive in Jetpack, it would be interesting to figure out why that's happening on your site, and if you use a third-party plugin or a code snippet that may customize the output of the sharing display function and cause that error.

Could you let me know if you use any other plugin or code snippet to customize Jetpack's sharing buttons?

**Comment by galbaras** [comment]
I've done some more testing and found out that the issue only appears when [the home page](https://www.tsoofbaras.com/) is rendered for page caching for guest users. The site runs Genesis, and the home page is made up of sidebars & widgets, so I don't think there is any `the_content`.

Sharing display is included on that page via a shortcode in one of the widgets, which simply runs the function `sharing_display()`.

Just to be clear, there are 2 instances of the sharing display on the page, one of which (the side floater) is OK. The other one, at the bottom of the page, shows the word "Array", followed by the correct sharing display.

As far as custom code, it runs successfully on all of my sites, and all other pages of this site. Here's everything that applies to this site:

```add_filter( 'gbol_exclude_from_sharing', 'gbol_exclude_from_sharing_default', 1 );
function gbol_exclude_from_sharing_default( $exclude ) {
	return ( ! function_exists( 'sharing_display' ) ||
			 is_archive() ||
			 ( function_exists( 'is_woocommerce' ) && is_woocommerce() && ! is_product() ) ||
			 gbol_is_woo_special_page() );
}

function gbol_echo_sharing_display() {
	if ( function_exists( 'sharing_display' ) ) {
		echo sharing_display();
	}
}

function gbol_sharing_floater() {
	$output = sharing_display();
	if ( '' === $output ) {
		return;
	}

	echo '<div class="sharing-floater">';
	echo $output;
	echo '</div>';
}

add_action( 'wp', 'gbol_remove_jetpack_sharing' );
function gbol_remove_jetpack_sharing() {
	remove_filter( 'the_excerpt', 'sharing_display', 19 );
	if ( apply_filters( 'gbol_exclude_from_sharing', 0 ) ) {
		add_filter( 'sharing_enqueue_scripts', '__return_false' );
		remove_filter( 'the_content', 'sharing_display', 19 );
	} else {
		if ( function_exists( 'is_product' ) && is_product() ) {
			remove_filter( 'the_content', 'sharing_display', 19 );
		}
		remove_action( 'woocommerce_share', 'jetpack_woocommerce_social_share_icons', 10 );
		add_action( 'woocommerce_after_main_content', 'gbol_echo_sharing_display', 1 );
		add_action( 'wp_footer', 'gbol_sharing_floater', 99 );
	}
}

/* Enable adding sharing buttons in content */

add_shortcode( 'sharing_display', 'sharing_display' );

/* Remove Jetpack ads */

add_filter( 'jetpack_just_in_time_msgs', '__return_false' );

/* Split up the concatenated Jetpack stylesheet to enable dequeuing */

add_filter( 'jetpack_implode_frontend_css', '__return_false', 99 );```

**Comment by jeherve** [comment]
What would happen if you were to replace

```php
function gbol_echo_sharing_display() {
	if ( function_exists( 'sharing_display' ) ) {
		echo sharing_display();
	}
}
```

by 

```php
function gbol_echo_sharing_display() {
	if ( function_exists( 'sharing_display' ) ) {
		sharing_display( '', true );
	}
}
```

*****

On another note, you can safely remove the `jetpack_implode_frontend_css` filter from your code snippet. That functionality is deprecated, Jetpack no longer concatenates the different modules' CSS into one file.

**Comment by galbaras** [comment]
This change makes sense, but didn't help 😞  This is possibly because the shortcode still calls `sharing_display()` with no arguments, and an array sneaks in there somehow 🤔 

Thanks for the implode bit. I will remove the filter.

**Comment by galbaras** [comment]
I think I've found a workaround:

```
function gbol_return_sharing_display() {
	if ( function_exists( 'sharing_display' ) ) {
		return sharing_display( '', false );
	}
}
add_shortcode( 'sharing_display', 'gbol_return_sharing_display' );
```

**Comment by galbaras** [comment]
This seems like a really marginal case of a widget with a shortcode instead of page content, so I'm going to close this issue.

Thank you for your help, Jeremy.
