### ISSUE TITLE
Publicize: 500 error when editing posts that have been previously shared

### ISSUE THREAD

**Issue by jordesign** [Automattic/jetpack#40335]
### Impacted plugin

Jetpack

### Quick summary

I've had 2 separate reports on WPCOM of sites getting Fatal errors when editing _certain_ posts. In both of these cases - investigation has led to the realisation this only happens for posts that have previously been shared.

PHP error reported is:

`Cannot access offset of type string on string in /wordpress/plugins/jetpack/14.1-a.5/jetpack_vendor/automattic/jetpack-publicize/src/class-publicize.php:781`

The only common Social Network between the two sites was Facebook - so I'm led to believe it is related to that.

### Steps to reproduce

I've been unable to recreate this in testing so far - but based on sites reporting the issue.

1. publish a post and share to Facebook using Publicize.
2. Try and load the post to edit it again.

### A clear and concise description of what you expected to happen.

I expect the post to load in the editor.

### What actually happened

PHP 500/Fatal Error

`Cannot access offset of type string on string in /wordpress/plugins/jetpack/14.1-a.5/jetpack_vendor/automattic/jetpack-publicize/src/class-publicize.php:781`

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by jordesign** [comment]
Examples:
* 9089975-zd-a8c
* 9089688-zd-a8c

**Comment by manzoorwanijk** [comment]
I tried to reproduce the issue but I couldn't.

#40337 should fix it but I don't know if we can test that PR on any of those sites using Jetpack Beta Tester plugin
