### ISSUE TITLE
Twitter and 4.6 alpha

### ISSUE THREAD

**Issue by sterndata** [Automattic/jetpack#4035]
With WordPress version 4.6-alpha-37597, the jetpack twitter widget does not display tweets.

See https://www.stevenstern.me

#### What I expected
tweets, like on my 4.5.2. site

#### What happened instead
no tweets

**Comment by kraftbj** [comment]
Did you make any changes on that site? It is working for me.

![screen shot 2016-05-31 at 22 52 27](https://cloud.githubusercontent.com/assets/88897/15697707/65f7e058-2782-11e6-8f84-e586b0e842ce.png)

**Comment by jeherve** [comment]
Works for me too. It might be worth checking that you're not blocking Twitter resources with a browser extension / add-on. Privacy and ad-blocking extensions can sometimes do that.

**Comment by sterndata** [comment]
Working for me now, also. It may have been a twitter thing or something fixed in a nightly.
