### ISSUE TITLE
Activity Log: Add clarity to the "users logged in" event

### ISSUE THREAD

**Issue by formosattic** [Automattic/jetpack#40427]
### What

Change the wording so it reflects the correct number of users and logins.

In the below example, it's one user who logged in twice, but the text say `2 users logged in`.

![image](https://github.com/user-attachments/assets/d0ae3f9c-2f16-49ec-be05-e660391b3b63)

### Why

The current wording is misleading, and without expanding the details, it can trigger an impression of security concern as we're led to think that some unknown users accessed the site.

Ticket: 8746618-zd-a8c

### How

If we're just tracking login events, should we remove the word `users` and keep it to something like `2 logins`?

**Comment by Robertght** [comment]
@formosattic I'm unable to replicate this on my sites, but I did see today one case where two logged in events were recorded in the activity log.

I'm moving this to Jetpack but I'm in need of help of how we can replicate this consistently and find a source.

@jeherve do you know what team can investigate this further?

**Comment by jeherve** [comment]
I couldn't replicate either. I'd offer to leave this open, and investigate further if we get more reports.

**Comment by jwebbdev** [comment]
@mavegaf took a look and found you can reproduce by logging in again to the site in a private / incognito window

![Image](https://github.com/user-attachments/assets/f39a06a0-949c-4407-a634-935f565be0f8)

**Comment by jwebbdev** [comment]
@formosattic Do you think this would resolve things?

![Image](https://github.com/user-attachments/assets/742e2be4-e31d-462f-9f5b-e25a8a22f9cb)

**Comment by formosattic** [comment]
Thanks for the ping @jwebbdev. The `2 logins by 1 user` provides enough clarity, looks good!

**Comment by jwebbdev** [comment]
This change is now live.
