### ISSUE TITLE
Boost: check that URLs are not 404s when added to Cornerstone Pages

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#40423]
We are not checking if a page exists when we're adding it to the Cornerstone Pages list. When the list is saved, it should do that check, and make sure it gets a 200 response code.

Bonus: mark the broken URL so it won't be used, and display it in red or other visible means to differentiate it from the other URLs. Broken URLs should still count towards the URL limit.

**Comment by haqadn** [comment]
Seems like a nice to have. Closing this for now.
