### ISSUE TITLE
SSO: Login with WP.com button styling

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#4043]
During a walkthrough of SSO today, @beaulebens and @rickybanister mentioned that the "Login with WordPress.com" button looked a bit awkward.

That button looks like this:

![screen shot 2016-06-01 at 5 23 30 pm](https://cloud.githubusercontent.com/assets/1126811/15727646/a4e830b0-281d-11e6-98de-ae74d3d4382a.png)

It was mentioned that we could maybe center the "W" icon along with the text within the button. 

cc @MichaelArestad who might be able to help as well.

**Comment by beaulebens** [comment]
For the sake of comparison, here's a quick look at it left or center aligned:

![left-aligned](https://cloud.githubusercontent.com/assets/108942/15729354/a439ce00-2820-11e6-83aa-84a69c87115e.png)
![centered](https://cloud.githubusercontent.com/assets/108942/15729355/a61d156a-2820-11e6-8a64-a8bac8bccab6.png)

I think I lean towards center?

**Comment by rickybanister** [comment]
Center looks better. We likely also have to account for very long translations here—perhaps doing a text overflow ellipsis thing?

**Comment by MichaelArestad** [comment]
I agree with Rick. I planned on #3 with everything centered.

**Comment by ebinnion** [comment]
Fixed in #4097.
