### ISSUE TITLE
Manage: Error installing {Plugin} on {Blog}. Plugin doesn't exits in the plugin repo.

### ISSUE THREAD

**Issue by sahin** [Automattic/jetpack#4045]
#### What I expected
Installing a plugin.
#### What happened instead
Error
#### Steps to reproduce the issue

Go to any pluing page
https://wordpress.com/plugins/contact-form-7
and then click "Install" in Available sites

**Comment by jeherve** [comment]
Thanks for the report! We'll take a closer look and keep you updated of our progress.

cc @enejb @lezama @gravityrail

**Comment by jeherve** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/5138

**Comment by enejb** [comment]
I was able to install the plugin on my WP with an issue on my site.
<img width="741" alt="screen shot 2016-06-01 at 16 38 29" src="https://cloud.githubusercontent.com/assets/115071/15729279/94ce0584-2817-11e6-9d35-c31c1a5b3801.png">

Are there any php error that you are seeing on your end.

**Comment by sahin** [comment]
https://www.youtube.com/watch?v=IYiOFf6zmxM

**Comment by sahin** [comment]
All 10 sites are using cloudflare ssl.

**Comment by jeherve** [comment]
I'm able to reproduce on a single WordPress installation, running latest WP and latest Jetpack, that does not use CloudFlare. Here is the error you outlined in your video:

```
code: 400, headers: [{name: "Content-Type", value: "application/json"}],…}
body : {error: "no_package", message: "Download failed."}
error : "no_package"
message : "Download failed."
code: 400
```

**Comment by sahin** [comment]
@jeherve when I go to wordpress admin /wp-admin, I can install any plugin totally fine.

**Comment by enejb** [comment]
@sahin Thank you very much for the video, it really helps to see the console and the response that you get from the API. 

We can fix this without make a change to Jetpack.

**Comment by enejb** [comment]
This should be fixed in calypso and the fix has also been deployed.
