### ISSUE TITLE
Admin Page: Initial load state graphics

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/jetpack#4052]
Need to build out and implement placeholder styles for UI elements while data is loading.

**Comment by jeffgolenski** [comment]
Thinking something like what wpcom does, but with the Jetpack logo. 

<img width="1280" alt="screen shot 2016-06-14 at 1 55 02 pm" src="https://cloud.githubusercontent.com/assets/214813/16053421/bc3dde36-3236-11e6-98af-1549d8901836.png">

**Comment by MichaelArestad** [comment]
I'm still thinking if we should show the pulsing animation that shows when we're loading things in Calypso. This kind of thing:

![image](https://cloud.githubusercontent.com/assets/1123119/16235626/d2be4694-3792-11e6-9031-3e9e30e8ae0b.png)

Here's a super rough example using old sketch files (sorry Jeff):

![image](https://cloud.githubusercontent.com/assets/1123119/16236225/d1b83726-3794-11e6-9ac4-4880ed309ea8.png)

That said, I think this could be trickier than I think. I don't know if dops-components has any loading states built into it yet (basically just a set of classes). We'd need to duplicate some HTML that looks Dashboard-ish and Settings-ish (possibly more). So! In the meantime, let's go with a much simpler to implement version as suggest by @jeffgolenski 

Maybe one of these:
![image](https://cloud.githubusercontent.com/assets/1123119/16239433/0b624b08-37a2-11e6-8883-7449de7ab8ff.png)

![image](https://cloud.githubusercontent.com/assets/1123119/16239439/14d75a48-37a2-11e6-8cea-ef3fb30410bb.png)

**Comment by jeffgolenski** [comment]
Good stuff Michael. 

This:

> That said, I think this could be trickier than I think. I don't know if dops-components has any loading states built into it yet (basically just a set of classes). We'd need to duplicate some HTML that looks Dashboard-ish and Settings-ish (possibly more). So! In the meantime, let's go with a much simpler to implement version as suggest by @jeffgolenski

As we discussed in slack, I'm all about having the more robust, pulsating block animations, so long as it's not a massive endeavor. In the meantime for a v.1, if we can roll out a faded logo / icon (perhaps with simple animation), I'm all for that – with the notion that we'll enhance down the line with the animated gray blocks.

**Comment by richardmuscat** [comment]
We also need a similar design/capability for when the plans page is loading

**Comment by eliorivero** [comment]
Done for Plans https://github.com/Automattic/jetpack/pull/4566

**Comment by eliorivero** [comment]
The `.is-placeholder` CSS class can now be used for the elements involved in the skeleton loading.
