### ISSUE TITLE
Jetpack does not exit secure mode after cloning the site.

### ISSUE THREAD

**Issue by lgdelai** [Automattic/jetpack#40531]
### Impacted plugin

Jetpack

### Quick summary

After cloning my site, I was only able to reconnect one of them to the jetpack, the clone site. 

When trying to connect the original site as a new site, I am unable to do so. 

It appears that the jetpack servers are preventing the connection.

### Steps to reproduce

Jetpack does not exit maintenance mode after cloning the site.

I cloned my website. 

**01 When logging into the clone site,** the jetpack went into safe mode, and asked me what I wanted. 
I chose the option on the left. that the CLONE SITE (With new domain) maintained the connection with the jetpack. Disconnecting the ORIGINAL SITE. 

**02 - When accessing the original website,**
I chose the option on the right. that I WANTED EACH SITE TO REMAIN INDEPENDENT, THAT IS: The original Site would start from scratch. without affecting the CLONE SITE. 

However, when trying to connect the ORIGINAL SITE to the jetpack, I receive a message: "An error occurred - Try again". 

**And I can never connect.**

**I already tried** disconnecting and uninstalling jetpack, deleting all jetpack tables, and then reinstalling jetpack, and it didn't work. 

**I tried** deactivating all plugins and themes, and it didn't help. 

It appears that something on the **jetpack servers** is preventing my domain from connecting after cloning the site. 

This looks like a bug.

### A clear and concise description of what you expected to happen.

I would like to connect my Original Site, as a new Jetpack connection.

### What actually happened

The original site does not connect to Jetpack.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

![Image](https://github.com/user-attachments/assets/d3b17433-05a1-4111-94fd-835ea66ee5fa)

**Comment by lgdelai** [comment]
An update:

This link:

https://mysite.com/site/xmlrpc.php

It's working.

I received the message:
**XML-RPC server accepts POST requests only.**

Correctly.

**Comment by lgdelai** [comment]
When I go to the WordPress diagnostic screen, this error appears:

**Blog token validation failed**

![Image](https://github.com/user-attachments/assets/6614a353-5335-4821-9348-9aceeb7cf260)

**Comment by jeherve** [comment]
Thanks for the report. It will be easier to investigate if we know more about your site. Could you contact us via this contact form, and give us as many details as you can about your site and its clone?
https://jetpack.com/contact-support/?rel=support&hpi=1

Thank you!

**Comment by lgdelai** [comment]
> Thanks for the report. It will be easier to investigate if we know more about your site. Could you contact us via this contact form, and give us as many details as you can about your site and its clone? https://jetpack.com/contact-support/?rel=support&hpi=1
> 
> Thank you!

Thanks, 

**I just did this.**

Have a great day.

**Comment by jeherve** [comment]
Thanks! I'll close this issue now, we can continue the conversation via email.
