### ISSUE TITLE
Admin Page: Build components

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/jetpack#4053]
From the design Trello board, we have a list of components that need porting over and/or finalising:
- [ ] Textarea
- [x] Info popover
- [x] Sharing settings
- [x] Publicize settings

**Comment by richardmuscat** [comment]
We've decided sharing and publicize won't be ported over this time round.

**Comment by MichaelArestad** [comment]
So will the link to the Calypso dashboard or what?

**Comment by beaulebens** [comment]
@MichaelArestad they'll link to the version that's in wp-admin for now.

**Comment by jeffgolenski** [comment]
Info popover: https://wpcalypso.wordpress.com/devdocs/design/info-popover

**Comment by richardmuscat** [comment]
Being handled here: https://github.com/Automattic/jetpack/pull/4004
