### ISSUE TITLE
Feature suggestion: Image optimization

### ISSUE THREAD

**Issue by greg-raven** [Automattic/jetpack#4054]
I think it would be great if Jetpack could include image optimization -- either automatic or semi-automatic. Maybe even offer the option of lossy or lossless optimization.

**Comment by jeherve** [comment]
The [Photon module](https://jetpack.com/support/photon/) is just what you're looking for: it optimizes all your images for you, [you can use filters to manipulate your images](https://developer.wordpress.com/docs/photon/), and [you can choose your own level of image compression](https://developer.wordpress.com/2015/02/04/lossy-image-compression-with-photon/).
