### ISSUE TITLE
i18n: Icon for Feedback menu item is awkward in RTL language

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#4059]
![screen shot 2016-06-02 at 12 20 14 pm](https://cloud.githubusercontent.com/assets/1126811/15754244/e9e72ce4-28bc-11e6-84dd-fcb1870179a0.png)

To reproduce:

- In wp-admin of site, go to Settings
- Set language to any RTL language
- Notice the Feedback icon appears "ghosted"

I tested on WP.com by setting the site language to Hebrew as well as my user's language to Hebrew, and I didn't notice the same issue. So, this seems to be isolated to Jetpack.

**Comment by jeherve** [comment]
> I tested on WP.com by setting the site language to Hebrew as well as my user's language to Hebrew, and I didn't notice the same issue. So, this seems to be isolated to Jetpack.

Could you try to install and activate the Polldaddy plugin on your self-hosted site, to replicate a situation similar to WordPress.com, and let me know if the problem remains?

**Comment by eliorivero** [comment]
@ebinnion @jeherve I've replicated the issue and pushed a fix in #4067
