### ISSUE TITLE
Design break in long wordpress descriptions

### ISSUE THREAD

**Issue by sahin** [Automattic/jetpack#4062]
#### What I expected
Design
#### What happened instead
Design
#### Steps to reproduce the issue
Long wordpress description

![unspecified](https://cloud.githubusercontent.com/assets/2508980/15764913/fd300f38-28e3-11e6-884d-65aa563c21aa.jpg)

**Comment by sahin** [comment]
@enejb @lezama @gravityrail @jeherve

**Comment by jeherve** [comment]
Since that's a layout issue on WordPress.com, it might be best for you to reopen that issue in the dedicated repository, here:
https://github.com/Automattic/wp-calypso/issues

Thanks!
