### ISSUE TITLE
Admin page: All external links should be new tabs (calypso, support, etc)

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/jetpack#4065]
When clicking on a link that takes you out of wp-admin, such as "view stats", any calypso-related link, learn more links, and support links, the page should open up in a new tab. 

The experience feels disjointed of going from wp-admin to Calypso or JP.com and then needing to click back, back, back to get back to my dashboard.

**Comment by dereksmart** [comment]
Cool, I was unclear on whether Calypso was considered `external`

**Comment by MichaelArestad** [comment]
I don't think we should do this for a few reasons. This article sums it up pretty nicely (and briefly): https://marco.org/2014/01/10/target-blank

Though this one expands a bit more on it: https://css-tricks.com/use-target_blank/

**Comment by richardmuscat** [comment]
@MichaelArestad 

> To avoid disturbing an important session in progress for a temporary digression, such as FAQ/documentation links in the sidebar when you’re doing online banking.

The above, which Marco describes as "justifiable", is why I believe we should do it this way.

**Comment by MichaelArestad** [comment]
> The above, which Marco describes as "justifiable", is why I believe we should do it this way.

No one has justified it yet.

**Comment by richardmuscat** [comment]
Closing after discussion in Zoom.
