### ISSUE TITLE
Admin page: Very often, wp.com links just don't work

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/jetpack#4066]
In a lot of cases while a Calypso link may initially try to take me to say wordpress.com/plans/my-site-url.com or wordpress.com/plugins/my-site-url.com, what actually happens is that the user sees loading placeholders and is then redirected to wordpress.com/plans or wordpress.com/plugins from where they are expected to pick a site.

**Comment by beaulebens** [comment]
This is also being tracked [here](https://github.com/Automattic/wp-calypso/issues/5571).

I believe fixing it in Calypso itself is going to be the best way of doing it.

**Comment by beaulebens** [comment]
Duplicate of #3927
