### ISSUE TITLE
Sharing: Custom Excerpts not included in Publicize action

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/jetpack#40663]
From 4242-GH-jpop-issues, site is not sharing custom excerpt due to what appears to be a timing issue. The post seems to have been published before we could save meta data to it in the editor (i.e. before an autosave or a manual save as a draft).

Scheduling and resharing work fine as does saving as a draft and then publishing. But creating a post and immediately publishing and sharing prevents the custom excerpt from being included in the share. 

We were not able to replicate and this seems, for now, to be specific to one site. They do not have this problem with other sites on the same server.

**Comment by jeherve** [comment]
Closing as this should now be fixed as of https://github.com/Automattic/jetpack/pull/17838
