### ISSUE TITLE
Press This sharing tool only posts to main blog

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#407]
When using Sharing in a multisite environment, PressThis only returns the first blog associated with an user, without presenting an option to select the blog when an user has multiple blogs on the same multisite.

Enhancement: Add dropdown of which blog to post to when user has multiple blogs.

Code reference: https://github.com/Automattic/jetpack/blob/2.9.2/modules/sharedaddy/sharing-sources.php#L798-L809

**Comment by kraftbj** [comment]
After building on Press This more, I would defer to https://core.trac.wordpress.org/ticket/12017 as a future core enhancement since this is really a limitation of PT, IMO.

**Comment by samhotchkiss** [comment]
@kraftbj - leaning toward tagging this as `wontfix` - opinion?

**Comment by kraftbj** [comment]
`wontfix` without prejudice, so willing to take it up later as PT evolves. The current core thought that this would be better in a browser extension rather than a bookmarklet for native PT. Since it is leaning in that direction (away from the /wp-admin/press-this.php page), it would be nice to figure out something that works in Sharing. But, I wouldn't want to go through a lot of work until that leaning of Core develops more.

Closing for now.
