### ISSUE TITLE
Sync: Move sync details to the debugger

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#4071]
@gravityrail - with the ?page=jetpack-sync details, since the new UI isn't on track for the same release as Sync, how about we move that information to ?page=jetpack-debugger?

The old sync reindex button is there already, so it needs to be removed (right?) in any event.

**Comment by ebinnion** [comment]
@lezama - I think you may have recently addressed this. Can we close this issue?

**Comment by jeherve** [comment]
Reopening this, as Sync details aren't available on the Debug page yet.

**Comment by enejb** [comment]
@jeherve I can see them at the bottom? What info are you missing?

**Comment by jeherve** [comment]
I don't see any Sync details on the Debug page in my dashboard at the moment.

**Comment by lezama** [comment]
Users can sync from their site settings page in Calypso.
