### ISSUE TITLE
Display Posts Widget: add filter to customize the output

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4075]
It would be nice if folks could change the display of the widget themselves, if we added a filter around everything that's outputted by `widget`:
https://github.com/Automattic/jetpack/blob/4.0.3/modules/widgets/wordpress-post-widget.php#L724

Suggested here:
https://wordpress.org/support/topic/changing-jetpack-display-remote-posts-up-a-little

**Comment by thingalon** [comment]
Fixed in #5883, merged.
