### ISSUE TITLE
Remove all welcome notices after Jumpstart for first time connections.  

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#4082]
**edit:** 
As it stands now (see this issue comment thread), we will remove all welcome notices for first-time connections.  

<strike>#4039 Introduced the ability to show custom "Welcome" text based on whether or not the site was Jumpstarted.  We need this text to be audited.  Right now the text is as follows: 

Jumpstarted: 
![screen shot 2016-06-07 at 3 01 36 pm](https://cloud.githubusercontent.com/assets/7129409/15871156/1eba6708-2cc1-11e6-929f-d092f813bbc5.png)

Skipped Jumpstart: 
![screen shot 2016-06-07 at 3 02 16 pm](https://cloud.githubusercontent.com/assets/7129409/15871161/26e4cfc2-2cc1-11e6-89d8-8af3f7b079a3.png)

You can test yourself by clicking "reset options" link in the footer.  

cc @richardmuscat </strike>

**Comment by richardmuscat** [comment]
For Skipped Jumpstart:

> Welcome to your Jetpack dashboard. Use this page to get an overview of your site's stats and status. Click "Settings" to enable and configure individual features.

I'm of the opinion that we don't need a separate message for Jumpstart.

cc @jessefriedman

**Comment by jessefriedman** [comment]
The more I look at it, I don't think we need a notice at all. The new at a glance view gives you a lot to look at and very clearly helps you understand that Jetpack is on and working. 

To be clear I'm talking about a welcome message of any time, Jump Start or otherwise.

**Comment by dereksmart** [comment]
@jessefriedman if you say so, that's fine with me.  I have renamed and re-described this issue :)

**Comment by jessefriedman** [comment]
@richardmuscat unless you have an red flags to throw up here, I think we should just delete the welcome messages. If in the future we want to add them back we can always do that.

**Comment by richardmuscat** [comment]
Agreed.
