### ISSUE TITLE
Sync Admin: Test logged out behavior

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#4086]
I'm unsure on this, so an issue for testing.

When using the new sync dashboard, leave the browser window open while deleting that admin account through a different manner.

For me, there were a massive spike in failed Protect-caught login attempts at that same time.

**Comment by lezama** [comment]
@roccotripaldi is this a bug on protect or the expected behavior?

**Comment by roccotripaldi** [comment]
hmm. that does not seem expected. will try to replicate.
