### ISSUE TITLE
Publicize: Custom Messages being trimmed to 100 characters on Twitter

### ISSUE THREAD

**Issue by raamdev** [Automattic/jetpack#411]
This issue is related to the Publicize Twitter functionality. I've looked through the docs and through the code and was unable to find anything that would explain the behavior I'm seeing.

The maximum tweet length is 140 characters and Twitter's t.co URL shortener currently creates 22-character URLs, which means that I should have 117 characters to work with when creating a custom tweet message for publicizing via Twitter (140 - 22 - 1 (space before the URL) = 117).

However, in my testing I've found that Custom Messages longer than 100 characters automatically show up on Twitter trimmed to 100 characters with an ellipsis at the end of the 100 characters, followed by the URL.

For example, let's say that I use the following (repeated sentence) as the Publicize Custom Message:

> Good enough is not perfect, but perfect is not published. Good enough is not perfect, but perfect is not published.

That's 115 characters. 

I would expect Publicize to use that 115 character Custom Message and then append the link to the post when posting to Twitter (t.co-generated links are currently 22-characters long, so a 115-character custom message + a space + 22-character link = 138 characters, which is under the 140-character limit).

However, that's not what happens. Instead, the following gets tweeted by Publicize:

> Good enough is not perfect, but perfect is not published. Good enough is not perfect, but perfect is… http://t.co/UXLkWAvhLM 

Which is 124 characters total (including the link). The length of 124 characters is well below the 140-character limit that should be available when posting a message to Twitter. 

I've looked through the Jetpack code and I cannot find anywhere this is happening, so I'm guessing that it has something to do with what's happening with the API on the WordPress.com-side. Or is this something that Twitter's API is doing?

**Comment by nkeat12** [comment]
how do you customize the pre-populated message for the jetpack twitter sharing button

**Comment by jeherve** [comment]
@nkeat12 See this tutorial:
https://jeremy.hu/jetpack-add-hashtags-to-the-twitter-sharing-button/
