### ISSUE TITLE
Admin Page: reorganize settings

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#4116]
After some deliberation, we have come up with a slight reorg of settings to be as follows:

```
# General
Manage (will be gone in 4.1?!?)
Notifications
Jetpack Addons
Jetpack Connection Settings
Omnisearch (can we remove?)
That Snow Module™
JSON API

# Engagement
Site Stats
Sharing (Content Sharing?)
Publicize
Related Posts
Comments
Likes
Subscriptions
Gravatar Hovercards
Sitemaps
Enhanced Distribution
Site Verification

# Security
Security Scanning
Brute Force Protection
Monitor
Akismet
Site Backups
Single Sign On

# Appearance
Tiled Galleries
Photon
Carousel
Extra Sidebar Widgets
Widget Visibility
Custom CSS
Infinite Scroll
Mobile Theme

# Writing
WP.me Shortlinks
Shortcode Embeds
VideoPress
Contact Form
Spelling & Grammar
Markdown
Post by Email
Beautiful Math
Custom Content Types
```

Now we just need @oskosk or @dereksmart to do the Settings Shuffle.

**Comment by richardmuscat** [comment]
Manage will be gone and "Jetpack Addons" is getting its own page so doesn't need to be there.

**Comment by dereksmart** [comment]
@MichaelArestad Are these listed in nav order from left -> right? 

Like 

General | Engagement | Security | etc...

**Comment by richardmuscat** [comment]
> Are these groupings listed in nav order from left -> right?

@MichaelArestad, Derek made a good point that if these are left -> right then the default view for users is the "General" tab which is a bit uninspiring. Should we put General at the end?

**Comment by MichaelArestad** [comment]
@richardmuscat I was planning on them being from left to right. That's one of the reasons I had stats in it. If we move it to the right, let's call it something else.

**Comment by dereksmart** [comment]
@MichaelArestad is this also the proposed order of features within each tab?

**Comment by richardmuscat** [comment]
I think for General we should go:

Keep:
- <del>Jetpack</del> Connection
- Notifications
- JSON API
- That Snow Module™

Remove:
- Jetpack Addons
- Omnisearch (can we remove?)
- Manage (will be gone in 4.1?!?)

**Comment by MichaelArestad** [comment]
@richardmuscat Works for me.

@dereksmart Yep.

**Comment by dereksmart** [comment]
Done in #4306
