### ISSUE TITLE
Admin Page: Stats time filters can be focused on twice each

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#4122]
Right now, it's possible to tab to Days, Weeks, and Months twice each. To clarify, there is a `tabindex="0"` added to each `li` element that wraps the `a`. That means when tabbing through, I tab to the outer `li` first and then the `a`.

![image](https://cloud.githubusercontent.com/assets/1123119/16059109/d532ead2-323e-11e6-9d0d-ade2b6966e71.png)

We need to fix this probably by removing focus from the `li` and making the `a` fire the action.

CC @dereksmart

**Comment by crunnells** [comment]
The markup here has changed, but it surfaced an issue where the current tabs don't have very good `:focus` styles. Closing this issue.
