### ISSUE TITLE
CSSTidy PHP7 compatibility

### ISSUE THREAD

**Issue by fgilio** [Automattic/jetpack#4127]
#### What I expected
Jetpack to run perfectly on PHP7.

#### What happened instead
I get some Notices and Deprecated messages.

#### Steps to reproduce the issue
PHP 7.0.4
WordPress 4.5.2
Jetpack 4.0.3

I'm using `Jetpack_Custom_CSS::minify()` method to process a .scss file and get this messages:

<img width="1504" alt="screenshot 2016-06-06 09 41 53" src="https://cloud.githubusercontent.com/assets/6857732/15822502/7694c338-2bcc-11e6-89c6-6a5dae0e4f3a.png">

I've been diggin arround and it seems like Jetpack is currently shipping with CSSTidy 1.3.1, [while the project is at 1.5.5](https://github.com/Cerdic/CSSTidy) and in that version the errors are fixed.
Is there any special reason for using this version?

Thanks!

**Comment by kraftbj** [comment]
My initial thought with looking too closely is 1.3.1 may be the newest that maintains 5.2 support, which we'd need to work around in some form.

Related #2206

**Comment by fgilio** [comment]
Hmmm yeah...
I've read what you propose of selectively using different versions, seems like a good idea. But I image it would not be an easy task to do right.

**Comment by gravityrail** [comment]
I believe this was fixed by #4268 - closing.
