### ISSUE TITLE
PHP Error on WooCommerce Setup page

### ISSUE THREAD

**Issue by BinaryMoon** [Automattic/jetpack#4129]
Just enabled WooCommerce and am getting a PHP error on the setup screen.

![screen shot 2016-06-15 at 16 34 35](https://cloud.githubusercontent.com/assets/1004130/16086353/25234b1c-3317-11e6-93d7-64c8fcd00afd.png)

Looking at the code it's happening because get_current_screen() is returning null - so I guess it could be a problem with WC not setting the current screen object.

I fixed it locally by setting line 364 of wp-content/plugins/jetpack/modules/related-posts/jetpack-related-posts.php to the following:

		if( $current_screen && 'options-reading' != $current_screen->id )

**Comment by jeherve** [comment]
Fixed in #3688
