### ISSUE TITLE
Enabling Extra Sidebar Widgets Interferes With Storefront WooCommerce Customizer Plugin Functionality

### ISSUE THREAD

**Issue by pmciano** [Automattic/jetpack#4134]
If **Extra Sidebar Widgets** is enabled, several Customizer items (e.g., **Homepage**, **Shop**), no longer appear in the Customizer when using the Storefront WooCommerce Customizer plugin, [as documented here](https://docs.woothemes.com/document/storefront-woocommerce-customiser/).

![Homepage](https://cldup.com/cCXkCLc6U9.thumb.jpg)

![Errors](https://cldup.com/uDhuIiDOtD-3000x3000.jpeg)

Tested with WordPress 4.5.2, Jetpack 4.0.3, and Storefront WooCommerce Customizer 1.9.0.

**Comment by jeherve** [comment]
This should be fixed by #3738. The fix will be included in the next Jetpack release.

If you'd like, you can test the fix by installing [Jetpack Beta](http://jetpack.com/beta).
