### ISSUE TITLE
Jetpack Extra Sidebar Widgets causes JavaScript error in Customizer

### ISSUE THREAD

**Issue by jessepearson** [Automattic/jetpack#4153]
This error appears to happen only when **Extra Sidebar Widgets** is active. [This screencast](http://cld.wthms.co/1jbQ8/3CvHjPcT) gives a brief intro into the issue. It shows me activating Extra Sidebar Widgets, then refreshing the Customizer to get the error.

Errors are:

> Uncaught ReferenceError: wp is not defined customizer-utils.js?ver=4.5.2:11 
> Uncaught TypeError: wp.customizerHasPartialWidgetRefresh is not a function contact-info-map.js?ver=20150127:34 

#### Steps to reproduce the issue

1. Install Jetpack and connect it.
1. By default Extra Sidebar Widgets is active.
1. Go into Customizer and view the console.

**Comment by jeherve** [comment]
This will be fixed in Jetpack 4.0.4, scheduled to be released next week. You can find the patch here:
#3738
