### ISSUE TITLE
Sharing: functionality not showing in development mode

### ISSUE THREAD

**Issue by BlueUrbanSky** [Automattic/jetpack#4162]
I am hoping to move the share buttons that are prepended to the content. I would like to do this is a safe carefree development environment. I have put Jetpack into dev mode and enabled the sharing module but it does not introduce its settings menu item. This I feel is a bug as the item is available to turn on but doing so is functionally pointless as the module itself can't be turned on.

#### What I expected
The 'sharing' item to appear under settings after enabling it in the Jetpack settings.
#### What happened instead
No option to alter the settings is given and the icons are not shown on the page
#### Steps to reproduce the issue
On a local installation put Jetpack into development mode.
Activate the sharing feature.
Try to turn on the feature via the settings.

Thanks
Sam.

**Comment by jeherve** [comment]
I can't seem to reproduce on my end. As soon as I activate the Sharing module under Jetpack > Settings, the Sharing menu appears under Settings > Sharing in my dashboard.

Could you tell me more about how you activated Development mode on that site?

Thanks!

**Comment by BlueUrbanSky** [comment]
added 
define( 'JETPACK_DEV_DEBUG', true);
to wp-config.php

I am running a multisite if that would make a difference

**Comment by jeherve** [comment]
Thanks!

Could you post a screenshot of the whole Jetpack Settings page as it appears in your dashboard right now?

Thanks!

**Comment by BlueUrbanSky** [comment]
![jetpack settings mind tools blog wordpress](https://cloud.githubusercontent.com/assets/15956836/16199704/8ae8d130-3702-11e6-88de-4eb57fb19f1a.png)
<img width="925" alt="screen shot 2016-06-20 at 16 14 35" src="https://cloud.githubusercontent.com/assets/15956836/16199727/9727d716-3702-11e6-9840-08742131fc0a.png">
<img width="168" alt="screen shot 2016-06-20 at 16 18 32" src="https://cloud.githubusercontent.com/assets/15956836/16199747/a83e5d68-3702-11e6-912f-ea90b81d1a92.png">

**Comment by jeherve** [comment]
hm, that's interesting. Could you try to deactivate other plugins, one at a time, and let me know if you find a conflicting one?

Thanks!

**Comment by BlueUrbanSky** [comment]
Shut down all but Jetpack and disabled/enabled the sharing with no effect.

<img width="364" alt="screen shot 2016-06-20 at 16 26 17" src="https://cloud.githubusercontent.com/assets/15956836/16200087/cb76bd1a-3703-11e6-83de-89ef102069af.png">

**Comment by jeherve** [comment]
Could you try to network deactivate Jetpack, and then activate it only on one site? I wonder if there could be a bug in how we handle plugin activation checks.

**Comment by BlueUrbanSky** [comment]
Sorry for the delay, I have deactivated the network section and enabled the local with no change. I have also deleted the jetpack files and then re installed the plugin again with no change.

**Comment by jeherve** [comment]
Thanks for giving that a try. Could you try to deactivate all other plugins on your site, one at a time, and let me know if you find a conflicting plugin?

**Comment by BlueUrbanSky** [comment]
It was the only plugin at the time of reinstalling

**Comment by BlueUrbanSky** [comment]
Ok found the issue
define( 'JETPACK_DEV_DEBUG', true);
was below
require_once(ABSPATH . 'wp-settings.php');
in wp-config.php

Sorry for the run around.
