### ISSUE TITLE
Add features to Display WordPress Posts Widget

### ISSUE THREAD

**Issue by angelacevans** [Automattic/jetpack#4186]
Request to add features to the Display WordPress Posts Widget.

Features:
- Display post by category
- Display post by tag

This would be helpful for adding a featured post to a page in a widget area and selecting that post by category or tag.  In conjunction with JetPack visibility, this would allow a featured post in a widget area on a page to match the category or tag that the page is related to.

**Comment by jeherve** [comment]
You can use the `jetpack_display_posts_widget_posts_params` filter to do just that.

You can check [the documentation](https://developer.jetpack.com/hooks/jetpack_display_posts_widget_posts_params/) to find an example of how to select posts belonging to a specific tag.

You can find out how to insert code snippets on your site here:
https://developer.jetpack.com/customize-jetpack-actions-filters/
