### ISSUE TITLE
Customize the message body for the email button

### ISSUE THREAD

**Issue by jotele** [Automattic/jetpack#419]
It would be nice being able to choose the body of the message when a visitor wants to share content via email.

**Comment by dartiss** [comment]
The ability to modify the email layout has been requested by a WordPress VIP client. I think this makes more sense as a requirement, as you can imagine large businesses would want to have the layout more in-keeping with their own branding, etc.

**Comment by StefMattana** [comment]
Another user asking for that too: 693786-zen

**Comment by jeherve** [comment]
This can now be closed since we now use mailto instead of a custom email sharing button (see #24040).
