### ISSUE TITLE
Contact Form: PHP notice following #4108

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4197]
After applying #4108, I receive the following notice in my logs:

```
PHP Warning:  Invalid argument supplied for foreach() in /wp-content/plugins/jetpack/modules/contact-form/grunion-contact-form.php on line 204
```

cc @eliorivero

**Comment by eliorivero** [comment]
Can you tell me how can I reproduce it? I checked both `master` and `branch-4.0` and I don't get it. By the time `current_screen` is called the admin menu is already well defined.

**Comment by jeherve** [comment]
It doesn't seem to happen on every admin load, so I'm having a hard time reproducing, unfortunately. 😞

**Comment by eliorivero** [comment]
Closing for now to clean the milestone. Feel free reopen when you can reproduce it. Thanks!

**Comment by jeherve** [comment]
This was reported again here:
https://wordpress.org/support/topic/jetpack-error-message?replies=1&view=all

**Comment by pawawat** [comment]
I have this error too
