### ISSUE TITLE
PHP Notice: Constant VIDEOPRESS_MIN_WIDTH already defined 

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#4204]
Fresh install of WordPress & Jetpack, activated all the modules, got this notice:
```
PHP Notice: Constant VIDEOPRESS_MIN_WIDTH already defined in /nas/content/live/cloudsrvr/wp-content/plugins/jetpack/modules/videopress.php on line 20, referer: https://www.cloudsrvr.com/wp-admin/admin.php?page=jetpack_modules
```

**Comment by jeherve** [comment]
@dbtlr Could you take a look? This seems like it could be caused by ba4af49ab73e429b0e8ec2448ea964ed61df1bd5, and I think we should be able to just add a `if ( ! defined( 'VIDEOPRESS_MIN_WIDTH' ) )`?

Thank you!
