### ISSUE TITLE
VideoPress: add option to select video thumbnail

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#422]
Update: This issue remains but the workaround below is no longer valid due to the refactor of VideoPress. Leaving the text for historical reference.

Original Post:
At the moment, if you want to change the video thumbnail of a video you just uploaded to VideoPress, you have to follow these steps:
1. Log in to WordPress.com
2. Go to the WordPress.com site where you've purchased the VideoPress upgrade
3. Go to Media > Library in your dashboard
4. Select a video you want to edit
5. Change the thumbnail.

It'd be nice if this option were available under Media > VideoPress in dashboards where the VideoPress module is active.

Suggested here:
- https://twitter.com/kbfl/status/448500159194726400

**Comment by kriskarkoski** [comment]
On AT sites it is not possible to change the thumbnail as the WordPress.com library cannot be accessed

**Comment by jeherve** [comment]
@kriskarkoski Correct. It's not possible on any other Jetpack site either since VideoPress videos are now linked to the Jetpack site, and not to a WordPress.com site using a VideoPress upgrade.

Luckily the work we've done in #6631 will soon allow one to change a video poster directly from Calypso, once this PR will be complete and merged:
https://github.com/Automattic/wp-calypso/pull/11653

**Comment by seejacobscott** [comment]
requested here: 3265255-t

**Comment by aheckler** [comment]
634025-zen

**Comment by codestor4** [comment]
634025-zen

**Comment by danjjohnson** [comment]
Looks like this is now possible via https://github.com/Automattic/jetpack/pull/6631 but I've just found that it doesn't seem to show the selected thumbnail in Safari. Or rather it shows it briefly, then reverts back to the  first frame of the video.

Steps to reproduce:
1. Upload a video to a page/post and select a frame to use as the thumbnail, via https://wordpress.com/media/
2. View the page/post in Chrome and you'll see the selected frame.
3. View the page/post in Safari and you'll see the selected frame for a second, then the first frame.

cc: @donnapep as you worked on the PRs for this I believe.

Reported in 701879-zen

**Comment by aheckler** [comment]
cc @dbtlr here ^^^ since that sounds a lot like the issue you just dug into for me.

**Comment by dbtlr** [comment]
@danjjohnson This is due to the removal of autoplay from Safari for ads. We've removed most of the VideoPress interface from Safari at the moment while I investigate how we can be compliant with this change in Safari and elsewhere. You can find more in 43-guardians

**Comment by jeherve** [comment]
Also in 937460-zen

**Comment by sdixon194** [comment]
Brought up for an AT site in 1255946-zen

**Comment by kriskarkoski** [comment]
5456690-hc

**Comment by dartiss** [comment]
At the moment the only solution to modify the thumbnail is via WordPress.com, and not in WP Admin. Is there a possible option here to add this capability (particularly with the introduction of Gutenberg)?

A WordPress.com VIP client is querying (they don't use Calypso). Ticket - #83274-z

**Comment by jeherve** [comment]
@dartiss That is not yet possible, no. As you mentioned the only workaround at the moment would be to use the Media editor on WordPress.com.

**Comment by jeremypaavola** [comment]
1862405-zen

**Comment by sarahcada** [comment]
12090515-hc

**Comment by jeherve** [comment]
Closing as the option is now available in the post editor:

![image](https://user-images.githubusercontent.com/426388/76105813-fd443580-5fd5-11ea-99cd-3d14bc241fb0.png)
