### ISSUE TITLE
Stats: Allow displaying stats on front-end to site visitors (not logged in)

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#423]
Some users would like a way of displaying site stats to visitors who aren't logged in, whether by SHortcode or widget or otherwise.

On WordPress.com there is the Blog Stats Widget, which shows the total # of hits.

This post showed a way of rendering stats : http://wpgr.org/2013/03/02/rendering-jetpack-stats/

It'd be nice if we could implement something similar, natively to Jetpack. 

Requested here: http://wordpress.org/support/topic/site-stats-24?replies=1

**Comment by jeherve** [comment]
Also suggested here:
http://jetpack.me/2015/07/06/jetpack-3-6-updated-social-widgets-jetpack-cli-and-more/comment-page-1/#comment-17933

**Comment by kraftbj** [comment]
Agreed this is plugin territory with the right setup (caching that would store these in memory instead of the db, etc).

Psuedocode:
```function bk_jp_stats_by_post( $post_id ){
  $post_id = intval( $post_id );
  if ( false === ( $value = get_transient( 'bk_jp_stats_post_' . $post_id ) ) ) {
    $args = array(
      'post_id' => $post_id,
      );
    $value = stats_get_csv( 'postviews', $args );
    set_transient( 'bk_jp_stats_post_' . $post_id, $value[0]['views'], HOUR_IN_SECONDS );
  }
  echo number_format( get_transient( 'bk_jp_stats_post_' . $post_id ) );
}```

**Comment by richardmtl** [comment]
926803-zen

**Comment by jeherve** [comment]
@richardmtl We do have a Blog Stats Widget in Jetpack now:
https://jetpack.com/support/extra-sidebar-widgets/blog-stats-widget/
