### ISSUE TITLE
Sync: Fatal errors caused by get_plugins()

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4233]
@enejb #4229 causes Fatal Errors when loading my site:

```
PHP Fatal error:  Call to undefined function get_plugins() in /wp-content/plugins/jetpack/sync/class.jetpack-sync-functions.php on line 66
```

While you're looking into this, it would be good to add docblocks to all new hooks.

**Comment by enejb** [comment]
I tried replication this fatal error and I wasn't able to. Are you able to reproduce it?
