### ISSUE TITLE
 Is there a way to see which article an external

### ISSUE THREAD

**Issue by DJDoena** [Automattic/jetpack#424]
OK, so I have WordPress stats. On the left side I have the external referrers. On the right side I have today's called articles.

But is there a way to find out to which particular article a site linked to?

Sure I could visit the referring page and check it out, but sometimes it's generated content as well and there's no link for me to find.

from http://wordpress.org/support/topic/wordpresscom-forums-»-support-is-there-a-way-to-see-which-article-an-external

**Comment by kraftbj** [comment]
I'm closing this item. It is a good suggestion, but not something currently on JP's roadmap.
