### ISSUE TITLE
Contact Info Widget - Google Maps require API Keys

### ISSUE THREAD

**Issue by annezazuu** [Automattic/jetpack#4240]
Google made updates to their Map API as of June 22nd, 2016.

https://developers.google.com/maps/pricing-and-plans/standard-plan-2016-update
https://developers.google.com/maps/documentation/javascript/get-api-key
https://developers.google.com/maps/documentation/javascript/error-messages#deverrorcodes

It appears this will only impact impact domains that weren't using it before June 22nd. Here's what this problem looks like in the console: 

<img width="1228" alt="screen shot 2016-06-28 at 2 48 59 pm" src="https://cloud.githubusercontent.com/assets/11266471/16432369/d94d3970-3d41-11e6-9823-8c2c38e72429.png">

This is what displays on the page as well:

<img width="389" alt="screen shot 2016-06-28 at 3 05 53 pm" src="https://cloud.githubusercontent.com/assets/11266471/16432377/e26cc0ca-3d41-11e6-88e0-f08355cd6761.png">

At this point, we either need to kill the feature or offer a place for users to add their API keys. Otherwise, this feature will continue to run into problems.

**Comment by kraftbj** [comment]
I think we're too late for 4.1, but need to handle it in some way soonish.

**Comment by lukecav** [comment]
So would there be an API key option in Jetpack then, if a user was using the contact info widget?

**Comment by kraftbj** [comment]
@lukecav Probably. 4.1 is closed, so trying to still squeeze in a filter into 4.1 to give us some option while fleshing out something long-term for 4.1.1.

Google grandfathering existing sites gives us a little breathing room... a little.

**Comment by jeherve** [comment]
Reopening this, as the offered solution will be confusing for many users. Read more here:
https://github.com/Automattic/jetpack/pull/4242#issuecomment-234895699

**Comment by petrk94** [comment]
Hello, 
I have found maybe a interesting issue, when Im using my webserver URL its working as widget correctly. But if I use instead webserver URL, the domain for my website, I get the "Something get wrong" error. Ayn idea why that is happening?

**Comment by kraftbj** [comment]
If you're not using a key, that domain may have been grandfathered in by Google. If you're using a key, it's likely that the other domain isn't associated with the key from Google. If you look in the browser's console, there is usually an error message from Google that you can use to search Google's docs for the specific cause.

**Comment by petrk94** [comment]
Yes, I get the error message in the console, that the Google API key is missing. But how/where I can insert the key into the Jetpack plugin? I dont have the Google maps API Key field in the jetpack widget,

**Comment by jeherve** [comment]
@petrk94 This should help:
https://github.com/Automattic/jetpack/pull/4562#issuecomment-239681393

If you need more details, you can follow the instructions here:
https://developer.jetpack.com/hooks/jetpack_google_maps_api_key/#comment-19
