### ISSUE TITLE
Button location issue when manage is disabled

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#4243]
In 4.1, if manage is not enabled (either it's an upgrade from a version when manage was turned off or they disable it via wpcli or other means), this happens:

<img width="465" alt="6_gmlm9w5e" src="https://cloud.githubusercontent.com/assets/574752/16435020/6e098a5e-3d93-11e6-91e3-122566f325d6.png">

**Comment by jeherve** [comment]
Fixed in #4245
