### ISSUE TITLE
Publicize - Add Facebook Send Button

### ISSUE THREAD

**Issue by annezazuu** [Automattic/jetpack#4253]
Feature request from a user to add support for Facebook's Send Button:

https://developers.facebook.com/docs/plugins/send-button

**Comment by annezazuu** [comment]
Requested in 2713308-t

**Comment by jeherve** [comment]
Closing as `wontfix`. The `jetpack_sharing_facebook_official_button_output` filter can help changing the output of the default Facebook button added by Jetpack, to add the Send button as well for example.
https://developer.jetpack.com/hooks/jetpack_sharing_facebook_official_button_output/
