### ISSUE TITLE
Publicize - Add Support for Telegram

### ISSUE THREAD

**Issue by annezazuu** [Automattic/jetpack#4255]
In 2716957-t user has asked us to consider adding telegram to the publicize options. It seems like this should work based on their [API documentation](https://core.telegram.org/methods) and [this plugin](https://wordpress.org/plugins/telegram-for-wp/). Not positive though but adding here as a feature request :)

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
