### ISSUE TITLE
Deprecated functions in Jetpack

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4257]
- `like_escape` in `class.jetpack.php`. It's been replaced by `wpdb::esc_like()`
- `get_theme` and `get_current_theme` in `modules/infinite-scroll/infinity.php`, `modules/theme-tools/inifinite-scroll.php`, `modules/custom-css/custom-css.php`, and `modules/module-info.php`. We should use `wp_get_theme()`
- `is_comments_popup()` in `modules/likes.php`
- `screen_icon()` in `modules/videopress/videopress.php`. We should now use `get_screen_icon()`

**Comment by kraftbj** [comment]
`$is_comments_popup` in likes.php is wrapped in a 4.5 conditional. Once 4.5 is the minimum version (the JP major version after ~August), [that whole block can be removed.](https://github.com/Automattic/jetpack/blob/4.0.4/modules/likes.php#L1025-L1031)

**Comment by briancolinger** [comment]
Closing this issue now because the deprecated functions listed have already been fixed in previous releases.
