### ISSUE TITLE
Sharing button does not appear in bbPress forums

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#426]
The user has bbPress 2.5.3 and says that even though have enabled "Forum" and "Topic" in the "Show buttons on" in Settings -> Sharing, the buttons still do not appear. 

Originally requested here: http://wordpress.org/support/topic/sharing-button-does-not-appear-in-forums?replies=3

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/share-in-the-forums-do-not-show-up?replies=1

**Comment by chaselivingston** [comment]
Also requested in 2219115-t

**Comment by kraftbj** [comment]
I'm okay adding this in before the refactoring, depending on how long that is projected to do. Added the provided code in #2245 to get this moving.

**Comment by richardmtl** [comment]
Requested in 2275062-t
