### ISSUE TITLE
Testimonials: Allow for comments on testimonial items

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#4261]
User in 2717547-t requests that it be possible for comments to be made on testimonial items.

**Comment by eliorivero** [comment]
For now, to provide a response, user can enable testimonials using this code that can be placed in the theme's `functions.php`:
```php
/**
 * Allow comments in Testimonials for Jetpack.
 *
 * @param array  $args      Arguments for post type registering.
 * @param string $post_type Name of custom post type being registered.
 *
 * @return array
 */
function jetpack_allow_comments_on_testimonials( $args, $post_type ) {
	if ( 'jetpack-testimonial' === $post_type ) {
		$args['supports'][] = 'comments';
	}
	return $args;
}
add_filter( 'register_post_type_args', 'jetpack_allow_comments_on_testimonials', 10, 2 );
```
Here it is [as a plugin](https://gist.github.com/eliorivero/3f567186576bb05b89e46c62bb4b5319/raw/29f0fdeb32c8a3205e6f617456f97a4f551da064/jetpack-testimonial-comments.php) that user can upload.

**Comment by jeherve** [comment]
Closing this as `wontfix`, as we're unlikely to add comment support to Testimonials in Jetpack in the future; Testimonials typically aren't something one should be able to comment on. @eliorivero's solution above is the best for someone who would need comments.
