### ISSUE TITLE
Make jetpack_is_mobile() filterable

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/jetpack#4275]
Some setups, such as WordPress instances behind a Varnish cache, can put clients into different cache buckets depending on their UA, and those cache buckets don't necessarily line up with what `jetpack_is_mobile()` returns, which leads to inconsistent behavior.

For these situations, it would be useful to allow filtering, both `pre_` and after, of the `jetpack_is_mobile()` results to align the algorithm with the chosen bucket from the caching layer. 

It also allows custom mobile detection rules.

**Comment by kraftbj** [comment]
Makes sense and should be simple enough. 4.1 is closed for enhancements, so adding it to the 4.2 cycle.
