### ISSUE TITLE
Move Carousel Close Button to Right

### ISSUE THREAD

**Issue by mrwweb** [Automattic/jetpack#4285]
#### Steps to reproduce the issue

Open Jetpack image carousel.
#### What I expected

Close button ("X") is on the right.
#### What happened instead

Close button is on the left.

![image](https://cloud.githubusercontent.com/assets/1238696/16541696/d82f9e48-403e-11e6-8a55-1f2998f4e6d3.png)
#### Research

I found this [list of 15 lightbox scripts](https://codegeekz.com/responsive-jquery-lightbox-libraries/) (first result, only about a year old) and went through all the demos I could find (14) looking for the default close button.

**Close button on right: 11**
Close button on left: 1
No close button: 2

Given the above, I believe my expectation is based on standard practice for popup/modal/lightboxes and Jetpack should follow that.

**Comment by jeherve** [comment]
cc @MichaelArestad We'll need input from a designer on this, since this change would affect all WordPress.com sites as well.

Related: https://github.com/Automattic/jetpack/pull/798#issuecomment-48068532

**Comment by MichaelArestad** [comment]
As I previously stated, it probably should be on the right. Since I'm unaware of any current redesign of Carousel, let's just move it over.
