### ISSUE TITLE
Admin: Apps landing page

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#4303]
The Apps landing page within Jetpack React!

![image](https://cloud.githubusercontent.com/assets/214813/16599448/58354faa-42d0-11e6-8878-93e340015107.png)

(layered files available in .sketch format - just ask me for them if you need them!)

Perhaps this week it would be wise for me to export all necessary jpgs, pngs, and svgs, so you devs don't have to dig around within sketch and slow your workflow down. 

note: content in these screenshots are not finalized at this time.

cc @dereksmart @eliorivero

**Comment by richardmuscat** [comment]
Closing this as there's a PR now: https://github.com/Automattic/jetpack/pull/4345
