### ISSUE TITLE
Admin: Plans landing page(s)

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#4304]
The landing pages to be utilized within Jetpack React:

**1) FREE: Jetpack user on free "plan"**

![image](https://cloud.githubusercontent.com/assets/214813/16599652/501f068e-42d1-11e6-83b5-0926d65694cf.png)

**2) PREMIUM: Jetpack user on premium plan**

![image](https://cloud.githubusercontent.com/assets/214813/16599664/6556b4b6-42d1-11e6-9ed6-de36fa68bffc.png)

**3) PRO: Jetpack user on pro plan**

![image](https://cloud.githubusercontent.com/assets/214813/16599679/75476474-42d1-11e6-85fa-3ac4ccf55753.png)

Will try and get all the pngs, jpgs, and svgs primed and ready before the end of the week. 

_note: content in these screenshots are not finalized at this time._ 

cc @dereksmart @eliorivero

**Comment by richardmuscat** [comment]
One PR to rule them all: https://github.com/Automattic/jetpack/pull/4345
