### ISSUE TITLE
Enable the Subscriber role to receive email updates at time of registering

### ISSUE THREAD

**Issue by markx2** [Automattic/jetpack#431]
Add a checkbox to the User registration to enable Subscribers to get email updates.

This removes the need for the new user to complete site registration and then also request email updates separately.

Requested as a result of this suggestion:

http://wordpress.org/support/topic/subscribing-wp-users-members?replies=7

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/jetpack-49

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/subscriptions-do-site-members-also-recieve-new-post-notifications?replies=1&view=all

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by rachelmcr** [comment]
This was raised again in 1083165-zen. (Leaving this closed for now as I'm not sure one request is enough to reopen it.)
