### ISSUE TITLE
Admin page: Internal beta testing plan

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/jetpack#4314]
Come up with a testing list and plan for testing 4.3 and reporting bugs.

**Comment by richardmuscat** [comment]
Plan from discussion yesterday:
- @jeherve is prepping master-stable and handing me instructions + possible screen cast
- @samhotchkiss making sure beta plugin runs on pressable 
- @richardmuscat writing announcement post including project goals and what to focus feedback/reports on

**Comment by jeherve** [comment]
> master-stable and handing me instructions + possible screen cast

Done, done, and done. 👍
