### ISSUE TITLE
Admin Page: I get a blank page if the hash route does not match any of the routes defined in the Router

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#4325]
#### Steps to reproduce the issue

1. Try to load an URL with a weird route after the `#` (hash) like [$yoursite/wp-admin/admin.php?page=jetpack#/more]($yoursite/wp-admin/admin.php?page=jetpack#/more) in `master`.
2. Refresh the page with CMD+R  to get a full render  and get to see the blank page

_I reached this as I had the `#/more` route working on a branch but `master` does not handle it anymore_.

#### What I expected

I don't really know. But maybe a default landing on the dashboard or a 404-ish page.

#### What happened instead

Blank page

**Screenshot of the issue happening with the console open** 

![image](https://cloud.githubusercontent.com/assets/746152/16639257/2e3ce448-43c4-11e6-8ad4-5763599b4c41.png)

**Comment by richardmuscat** [comment]
Being handled here: https://github.com/Automattic/jetpack/pull/4438
