### ISSUE TITLE
Fonts: Admin menu fonts change when entering Jetpack admin menu on 4.6 trunk

### ISSUE THREAD

**Issue by getsource** [Automattic/jetpack#4333]
#### Steps to reproduce the issue
- Install 4.6 trunk with Jetpack
- Click on Jetpack menu
- Watch admin menu fonts change

#### What I expected
- Admin menu fonts to remain the same

#### What happened instead
- Admin menu fonts changed

I'd guess this is connected to the [Font Natively](https://make.wordpress.org/core/features/font-natively/) change.
https://cloudup.com/cCibJSruD1c

**Comment by Ipstenu** [comment]
Confirmed on 4.6 trunk and JP 4.1.1 . It's really a subtle change but it's most noticeable to me in the Toolbar :)

**Comment by jeherve** [comment]
Thanks for the report! This should be fixed in Jetpack 4.3, as we are getting rid of Open Sans like Core did.

Related Pull Request: #4322.
