### ISSUE TITLE
Admin: Jetpack React Search MVP

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#4335]
As we've discussed several times in the past, we know that launching a search feature with jetpack react v.1 is going to be paramount with such a big UI update to the plugin. 

For sake of getting an MVP out into the wild, I've created a pretty basic search flow that allows users to get around. 

1) User is somewhere within the Jetpack settings area. In this example, it's the security settings tab
![01-user-in-settings](https://cloud.githubusercontent.com/assets/214813/16665969/9049af92-4453-11e6-8938-17c8c4e622bd.jpg)

User clicks / taps the search icon...

2) Focus is placed on the search area. Letting the user know they can search for any feature / settings area from anywhere.
![02-user-clicks-search-icon](https://cloud.githubusercontent.com/assets/214813/16665985/aa68b6e8-4453-11e6-85b1-02228ff2eb8b.jpg)

_(if the user clicks the X to dismiss the search area, they'll be returned to where-ever they were browsing. ie. If they clicked the search icon in the security settings area, that area will return to them)_

3) Example: User searches something, but it's not found.
![03-nothing-found](https://cloud.githubusercontent.com/assets/214813/16666084/1ba54b6e-4454-11e6-9d8d-16157f038a50.jpg)

_Support block will be displayed below the "nothing found text." for a v.2, we can tailor this area a little better, offering suggestions, links to jetpack.com to learn about our features in case they don't know what we offer, etc)_

4) Example: User searches something and it's found
![04-feature-found](https://cloud.githubusercontent.com/assets/214813/16666185/7d63312c-4454-11e6-878c-1ca29a6f3e7e.jpg)

If there's only a single search result, like in this example, the card should be open. In the event multiple results are found we should keep the cards closed.

Note: Designs are a little outdated here @dereksmart so you'll just be following the calypso design patterns we've been using!

**Comment by richardmuscat** [comment]
Agreed but this is public beta not internal at this stage.

**Comment by jeherve** [comment]
This is now fixed.
