### ISSUE TITLE
Nova CPT: add multiple prices option to single menu item

### ISSUE THREAD

**Issue by rvpatel** [Automattic/jetpack#4341]
I need suggestion for this for menu item.

How we can add multiple prices for item?
**Sizes (for ice-cream) :**
Mini -$1.25
Small – $2.00
Medium – $3.00
Large – $5.00

**\- Restaurant  menu item prices:**
Item name : Carne Quesada / Beef Stew
Prices:  $3 / $5 / $8 / $12

**Comment by jeherve** [comment]
I'm afraid that can't be done with Nova right now. You'll need to create multiple items.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
