### ISSUE TITLE
Sharing: Option to use shortened URLs while sharing

### ISSUE THREAD

**Issue by vinitraje** [Automattic/jetpack#4355]
In case of Unicode characters in URL, the address can get quite long while sharing it. There should be an option to use wp.me shortened URLs also.

Example of URL: https://satyashodhak.com/2016/01/29/%e0%a4%86%e0%a4%b5%e0%a5%8d%e0%a4%b9%e0%a4%be%e0%a4%a8-%e0%a4%a7%e0%a4%b0%e0%a5%8d%e0%a4%ae%e0%a4%b8%e0%a4%a4%e0%a5%8d%e0%a4%a4%e0%a5%87%e0%a4%b2%e0%a4%be-%e0%a4%85%e0%a4%a8%e0%a5%8d-%e0%a4%b0/

It would be very convenient if option to use shortened URLs is offered.

**Comment by jeherve** [comment]
You can use the `sharing_permalink` filter ([reference](https://developer.jetpack.com/hooks/sharing_permalink/)) to customize the link used by Jetpack's sharing buttons. This plugin uses that filter to replace the full permalink by a shortlink:
https://wordpress.org/plugins/jetpack-shortlinks-for-sharing-buttons/
