### ISSUE TITLE
PHP Warning: Missing argument 2 for wp_kses()

### ISSUE THREAD

**Issue by m-e-h** [Automattic/jetpack#4357]
Getting this in the WP Engine error logs.
`PHP Warning: Missing argument 2 for wp_kses(), called in /.../wp-content/plugins/jetpack/modules/sitemaps/sitemap-xsl.php on line 93 and defined in /.../wp-includes/kses.php on line 525, referer: https://....org/sitemap.xml`

And the same warning for line 94 of the same file.
`wp_kses( sprintf( ent2ncr( __( 'You can find more information on XML sitemaps at <a href="%s" target="_blank">sitemaps.org</a>', 'jetpack' ), 'http://sitemaps.org' ), array( 'a' => array( 'href' => true, 'title' => true ) ) ) )`

Looks like the `sprintf()` is also wrapping the $allowed_html argument.
https://github.com/Automattic/jetpack/blob/master/modules/sitemaps/sitemap-xsl.php#L93-L94

**Comment by jeherve** [comment]
Thanks for the report! Could you give #4362 a try, and let me know if that fixes the problems for you?
