### ISSUE TITLE
Photon: Featured images are upscaled to fill content area

### ISSUE THREAD

**Issue by iandunn** [Automattic/jetpack#436]
Photon is resizing featured images to fill the theme's content area, even if it has to upscale them past their original image dimensions.

Steps to reproduce:

1. Activate TwentyThirtween or TwentyFourteen (it may happen in all themes, but those are the two I tested).
1. Create new page and set a featured image. Upload a small image (e.g., 200x200).
1. View the page, it will look normal.
1. Activate the Photon module and refresh the page. The featured image will be
upscaled to fill content area and will be heavily pixelated.

**Comment by kraftbj** [comment]
Need to test this one again. I think we may have solved this through the work for WP 4.4 support.

**Comment by kraftbj** [comment]
Twenty Fourteen works for now. Marking as resolved.
