### ISSUE TITLE
SAL: error on PHP 5.2 sites

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4361]
On a site running PHP 5.2.17:

```
PHP Parse error: syntax error, unexpected T_STATIC in /wp-content/plugins/jetpack/sal/class.json-api-links.php on line 10
```

Introduced in eb1ab752f5250c1aa9bbc8686773ce311cc915e9
cc @gravityrail 

Reported in 2727380-t

**Comment by gravityrail** [comment]
Fixed in #4364 (waiting for tests)
