### ISSUE TITLE
Admin Page: Settings and dashboard same for non-admin user

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#4365]
Today I noticed that the "Dashboard" and "Settings" routes are identical for non-admin users.

To test:

- Checkout latest Jetpack master
- Make sure it's built
- Log in to site with a user that has any non-admin role (`editor`, `author`, `subscriber`, etc.)
- Go to `$site/wp-admin`
- Click "Dashboard"
- Click "Settings"
- Verify that there is no visual change other than happiness engineer gravatar and URL changing

What I would expect is:

- For there to be a separate UI
- Or for there to only be a "Dashboard" link in the navigation

Here's a demo video:

![settings_dashboard_same](https://cloud.githubusercontent.com/assets/1126811/16736732/e9c4bad2-4753-11e6-92eb-f43b1ee017fb.gif)

**Comment by dereksmart** [comment]
thanks @ebinnion! A more complete non-admin solution is currently being reviewed in #4320, feel free to test it out! :)

**Comment by dereksmart** [comment]
taken care of in #4320
