### ISSUE TITLE
Admin Page: Feature Settings - Monitor - Setting "Emails will be sent to admin address" is not saving

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#4377]
We need to find the option key for "Emails will be sent to admin address" and make it save against the API

For the moment we can hide this option until it works.

**Comment by richardmuscat** [comment]
I'm going to move this to the next milestone. Let's consider it a bug to fix for public beta since its not a high priority feature and we can hide it until it works.

**Comment by oskosk** [comment]
Was not an issue. We were not needing a setting, but a link to WordPress.com email edit screen ( https://wordpress.com/settings/account/ )

Closing in favor of #4620
