### ISSUE TITLE
Admin Page: Feature Settings - Find a more elegant way to define Form Components used here

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#4387]
Currently the file `components/form/index.jsx` defines a few components that were ~~copypasted~~ imported from Calypso. This could be handled in a more tidier way as in separate files for each component or finding a `dops-components` alternative.

**Comment by richardmuscat** [comment]
I'm going to move this to the next milestone. Let's consider it a fix for public beta since its an enhancement.

**Comment by dereksmart** [comment]
I don't think we're going to get to this anytime soon.
