### ISSUE TITLE
Spelling and Grammar Module: error in script URL prevents TinyMCE script from loading

### ISSUE THREAD

**Issue by josiahsprague** [Automattic/jetpack#4406]
When the Spelling and Grammar module is activated, the text in the visual editor of post edit pages is not visible. The cause is an incorrect script URL being requested and failing to load.

#### Steps to reproduce the issue
Activate Jetpack's Spelling and Grammar module and go to the post edit page. Seen on WordPress 4.3.5 with Jetpack 3.9.6 and PHP 5.5.37.

#### What I expected
The script `/wp-content/plugins/jetpack/modules/after-the-deadline/tinymce/plugin.js` should be included on the page.

#### What happened instead
The page tries to request `/wp-content/plugins/jetpack/modules/after-the-deadline/tinymce/plugin.jsv` instead, and since that returns a 404, the JS doesn't load and the editor text is hidden.

The issue is that the call to `plugins_url()` on https://github.com/Automattic/jetpack/blob/master/modules/after-the-deadline.php#L134 returns the wrong value. I will open a PR to resolve the issue shortly.

**Comment by jeherve** [comment]
Related thread:
https://wordpress.org/support/topic/error-with-query-string-added-to-after-the-deadline-plugin-script?replies=2&view=all

As mentioned there, I'm not able to reproduce at the moment, and wonder if this may be caused by a conflict with another plugin.

**Comment by josiahsprague** [comment]
I've disabled all other plugins, and the current code doesn't follow the docs here: https://developer.wordpress.org/reference/functions/plugins_url/
