### ISSUE TITLE
sharedaddy_disable_resources being queried when sharing module not active

### ISSUE THREAD

**Issue by chuckreynolds** [Automattic/jetpack#4409]
#### Steps to reproduce the issue
Currently only have `widget visibility` enabled, everything else off. Load single post page.

#### What I expected
jetpack not to query things that are disabled

#### What happened instead
jetpack queried `sharedaddy_disable_resources`. 
`not_cached` `SELECT option_value FROM wp_options WHERE option_name = 'sharedaddy_disable_resources' LIMIT 1`

possibly related to: #1074, #4281

**Comment by jeherve** [comment]
That could indeed by solved by #4281. Could you try to install [Jetpack Beta](http://jetpack.com/beta), and let me know if it helps?

**Comment by chuckreynolds** [comment]
...can't reproduce now. v4.2-b3

**Comment by jeherve** [comment]
Excellent. Closing then.
