### ISSUE TITLE
Pull Request Template - Add header prompting for Testing Instructions 

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#4413]
* Testing instructions add a lot of value to a PR, providing any contributor with a simple step-by-step mini-guide which could confirm the PR's code is at least making its intention work as expected.
* Providing testing instructions helps non-developers to be able to review a PR hopefully speeding up the review process for everyone 

#### Steps to reproduce the issue

Create a new PR.

#### What I expected

To be prompted with a header for adding some testing instructions

#### What happened instead

I can create PRs without testing instructions

**Comment by oskosk** [comment]
cc @jeherve for triage

**Comment by jeherve** [comment]
I like that idea 👍  I just submitted #4419 to add that.
