### ISSUE TITLE
Youtube embeds (and probably other embeds) incorrect size

### ISSUE THREAD

**Issue by BinaryMoon** [Automattic/jetpack#4418]
Hi - when I enable shortcode embeds on my site youtube videos shrink in size and don't honor the content_width property set in my theme.

I have done some debugging and it seems the issue is down to the embed_size_w option. When I deleted this option through mysql the videos started using the content_width value. This option was deprecated 4 years ago - https://core.trac.wordpress.org/ticket/21719 - and so there is no way in the WordPress admin to remove/ change the option.

My suggestion is to stop using the embed_size_w option and instead to rely on the content_width. Alternatively I would at least make the content_width take precedence since that should be more up to date than the old option.

**Comment by jeherve** [comment]
> make the content_width take precedence since that should be more up to date than the old option.

This does indeed seem like a good solution.

YouTube seems to be the only place where `embed_size_w` is more important than `$content_width`. I'll create a PR to change that.
