### ISSUE TITLE
JSON API: notice when fetching media in Calypso

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4423]
#### Steps to reproduce the issue
1. Go to https://wordpress.com/post/
2. Create a new post on a site running Jetpack
3. Click to Add Media.

```
PHP Notice:  Undefined index: extension in /wp-content/plugins/jetpack/class.json-api-endpoints.php on line 1171
```

**Comment by enejb** [comment]
I wasn't able to reproduce this error. Can you provide more info? Are you still able to reproduce it?

**Comment by jeherve** [comment]
I can't seem to reproduce anymore, sorry!
