### ISSUE TITLE
Admin Page: react-router and hash conflicts

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#4436]
If you're in the JPR screen and click the Query Monitor button in Admin Bar, a JS warning shows up in console:
```
Warning: [react-router] Location "/qm" did not match any routes
Warning: [react-router] Location "/qm-php_errors" did not match any routes
```
<img width="683" alt="hash-conflict" src="https://cloud.githubusercontent.com/assets/1041600/16930716/d7ae4726-4d13-11e6-921d-0f7f6c565895.png">

Note the hash in the URL in the image above.

**Comment by richardmuscat** [comment]
Haz PR: https://github.com/Automattic/jetpack/pull/4438
