### ISSUE TITLE
Jetpack SSO not working as expected on Safari when site has clef active.

### ISSUE THREAD

**Issue by simplysaru** [Automattic/jetpack#4446]
#### Steps to reproduce the issue

Have the Clef plugin activated. Try to login to the site with Jetpack SSO instead of Clef.
#### What I expected

Login should work on safari browser. It logs into the site fine on chrome and firefox, but not on Safari.
#### What happened instead

The url changes to a success message and redirects back to the login page asking for login credentials again.

**Comment by jeherve** [comment]
Related: #2836

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
