### ISSUE TITLE
Jetpack + Plans Purchase Flow & config error within wp-admin

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#4457]
<img width="678" alt="screen shot 2016-07-20 at 12 34 00 pm" src="https://cloud.githubusercontent.com/assets/214813/16994420/4a6fd8f8-4e75-11e6-9670-8b33df96f590.png">

To Replicate:

1) My self-hosted sandbox with jetpack was on the free plan
2) Purchased Professional plan within calypso (free version of akismet was already installed)
3) Enabled manage via wp-admin, brought back to calypso
4) Auto-config began installing + configuring plugins
5) VaultPress install error - "folder already exists - try manual install", akismet and polldaddy 
6) Navigated back to wp-admin to find this error within functions.php

`Notice: Jetpack_Sync::sync_options is deprecated since version jetpack-4.2! Use jetpack_options_whitelist filter instead. in /home/jeffgole/public_html/wp-includes/functions.php on line 3706`

_This error may be limited to my sandbox, haven't tried an actual site just yet. Will report back when I do._ 

Not exactly sure what this error is all about so I'm pinging a few folks who may be involved in the design and build: @dereksmart @ryelle @rickybanister 

Also, as a sidenote @eliorivero, After I completed the purchase flow from free to pro, the professional landing page no longer displays:

![screen shot 2016-07-20 at 12 40 43 pm](https://cloud.githubusercontent.com/assets/214813/16994621/1fb1af96-4e76-11e6-805f-bb78fd83efac.png)

**Comment by jeffgolenski** [comment]
Also related:

Within calypso, when I click the button to return to my dashboard...

![screen shot 2016-07-20 at 12 49 27 pm](https://cloud.githubusercontent.com/assets/214813/16994874/5316ffac-4e77-11e6-86c9-d41c4258a4e8.png)

I get this error...

![screen shot 2016-07-20 at 12 49 19 pm](https://cloud.githubusercontent.com/assets/214813/16994880/5c5465b4-4e77-11e6-91d9-82558045430b.png)

**Comment by ryelle** [comment]
What version of all the plugins mentioned are you running? You already had VaultPress... at least half-installed for that error to happen, does that sound right?

**Comment by jeffgolenski** [comment]
My setup at the time of purchase and auto-config was as follows!

- VaultPress - was not installed - at least it wasn't showing in my plugins list and I can't ever remember installing it on this sandbox. now at 1.8.3
- Akismet - 3.1.11
- PollDaddy - was not installed
- Jetpack - 4.2.0-alpha

**Comment by ryelle** [comment]
So you got the VaultPress error, but it still correctly installed version 1.8.3, or you went and added that yourself?

I see that sync_options was deprecated in 4.2, but we have code in Polldaddy and VaultPress checking the JP version before trying to use it, and it's not used in Akismet. 

Are you seeing this warning on every page in the admin? Do you have any other plugins installed?

**Comment by jeffgolenski** [comment]
@ryelle The auto-config partially / mostly installed VP, I believe. It's in my plugins list and appears to be working, except for that aforementioned error at the top of wp-admin.

When I deactivate VP the error goes away and everything is fine. 

When I reactivated VP the first time, I got this...

![screen shot 2016-07-20 at 2 47 07 pm](https://cloud.githubusercontent.com/assets/214813/16998540/ddf9b578-4e87-11e6-88b4-5e0ebfce1ddc.png)

I then deactivated VP again, and reactivated it and get this...

![screen shot 2016-07-20 at 2 48 55 pm](https://cloud.githubusercontent.com/assets/214813/16998575/107743da-4e88-11e6-9e1b-0db67bd42f69.png)

**Comment by ryelle** [comment]
Apparently the version check is only in VaultPress trunk currently. This is a VaultPress issue, and you're only seeing it because you're beta testing 4.2 (and you have debug on). Once 1.8.4 is released you shouldn't see this anymore.

I'm still interested in what happened to install VP but still give you the `folder_exists` error, but I'm not sure how to recreate or debug it, since Polldaddy installed just fine.

**Comment by jeffgolenski** [comment]
I'll keep an eye out in case it ever happens again. Thanks Kelly!
