### ISSUE TITLE
Comments: Fallback for when site is inaccessible

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#446]
For when a site's Jetpack connection is inaccessible (e.g. a problem with the Jetpack connection or an issue accessing xmlrpc.php), add a more graceful fallback.

Currently, in such a situation, the error from the failed connection is thrown and the commenter loses the comment completely. Idea: Jetpack hold the comment for X time waiting for the site's connection to become accessible again.

**Comment by kraftbj** [comment]
Another situation to handle is when the connection is working, but when the native WP site is down. An example on a site today:
1. Site loads
2. Visitor writing comment while the native site goes down
3. Submits comment
4. Error shown (comment lost) in the iframe space when the frame passes from wpcom to local install.

**Comment by samhotchkiss** [comment]
Based on the conversation here, it seems like this is a pretty rare issue-- since this is not in line with our current priorities/roadmap, I'm going to go ahead and close.  If there are 3 more requests after this comment, please re-open.
