### ISSUE TITLE
Database contention occurs during a multi-node rolling upgrade (4.0.3 to 4.0.4 -and- 4.0.4 to 4.1.1)

### ISSUE THREAD

**Issue by borgstrom** [Automattic/jetpack#4468]
Hi,

We operate a multi-node WordPress cluster in AWS.  The cluster has 3 nodes spread across 3 AZs and receives a decent amount of traffic (~1500 active users at most times).  When we deploy to the cluster we build a zip of WordPress on our build machines and then we deploy it in a rolling fashion, where for each node we:

* Deregister from the load balancer, wait for connections to drain
* Unpack the zip & update a symlink to make it the active version
* Register with the load balancer

Recently we were doing some work to our deployment mechanism that caused us to take one of our 3 nodes out of the load balancer for an extended period of time while we manually fiddled with the tooling and tested the node in a way where only a handful of engineers had access to it (by modifying their hosts file).  During this time we manually deployed a zip payload that contained an upgrade from Jetpack 4.0.3 to 4.0.4 and as soon as we accessed the instance running 4.0.4 (while the other two instances, still taking production traffic, were running 4.0.3) we began to notice massive contention on our database, specifically we saw a huge spike in "UPDATE" queries (our average for updates is <1qps and during this time we saw upwards of >100qps):

<img width="613" alt="screen shot 2016-07-20 at 11 06 44 am" src="https://cloud.githubusercontent.com/assets/1594130/17000842/5f312590-4e79-11e6-8deb-c2d4ffff2528.png">

We also saw a massive spike of traffic to jetpack.wordpress.com:

![screen shot 2016-07-18 at 4 52 06 pm](https://cloud.githubusercontent.com/assets/1594130/17000855/6e02718c-4e79-11e6-8d21-e7118e0c7c5b.png)

Even after we rolled back the node that had the upgraded version the traffic to jetpack.wordpress.com continued.  It was until we went into the admin interface, disabled the plugin and then re-enabled it that the traffic finally subsided.  (You can see this in the above two screenshots by the duration of the UPDATE queries vs the duration of the calls to jetpack.wordpress.com).

When we did the fully automated rolling upgrade from 4.0.3 to 4.0.4 the next day we again noticed the contention, albeit for a much shorter time this time because the automated deploy happened quickly:

<img width="616" alt="screen shot 2016-07-20 at 11 17 15 am" src="https://cloud.githubusercontent.com/assets/1594130/17000876/8295691a-4e79-11e6-8476-b5d10eb82438.png">

We also saw the jump in queries to jetpack.wordpress.com, but this time it recovered on it’s own:

<img width="1171" alt="screen shot 2016-07-20 at 11 19 19 am" src="https://cloud.githubusercontent.com/assets/1594130/17000882/8867cb3a-4e79-11e6-8050-c38e9ab28e31.png">

We believe that the contention stems from the two different versions Jetpack are racing each other to update something in the database, but we don’t understand why this occurs.  We also haven’t seen this on any other plugin, and don’t have specific data on our previous Jetpack upgrades.

Can someone help provide insight on what might be causing this contention with UPDATES and why we would have vastly increased connections to jetpack.wordpress.com still happening after we were rolled back to 4.0.3 in the first case, where it took us disabling and re-enabling the plugin?  We’d be happy to collaborate on a solution so that we don’t face this contention during future rolling upgrades of Jetpack.

Thanks!

CC @MickeyKay @BraadMartin

**Comment by kraftbj** [comment]
Are you seeing the same thing going from 4.0.4 to 4.1.1? Initially, the issue may be #4269.

**Comment by borgstrom** [comment]
Thanks, @kraftbj.   We'll update to 4.1.1 and report back.

**Comment by borgstrom** [comment]
Hey @kraftbj.  We did the upgrade to 4.1.1 yesterday evening and the same issue occurred: A skip in traffic to jetpack.wordpress.com and a spike in UPDATE queries that caused some contention in the database.

Let me know what else I can provide in the way of info or specifics.

Thanks.

**Comment by jeherve** [comment]
cc @lezama, since you're working on #4456 right now.

**Comment by jeherve** [comment]
Also possibly related: #4105

**Comment by jeherve** [comment]
@borgstrom Is this still an issue with the most recent version of Jetpack? We've made several changes that may address this issue in 4.2 and 4.3.

Let us know!
