### ISSUE TITLE
Admin Page: Extensive string review

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/jetpack#4472]
Lets make a plan for reviewing all text to
- ensure consistency
- remove typos and grammatical errors
- say the right things

- [x] Disconnected landing page
- [x] Jump Start
- [x] At a Glance (different modules states)
- [x] Plans landing page (including name)
- [x] Apps landing page (including name)
- [x] Feature short descriptions
- [x] Feature long descriptions
- [x] Change wording holiday snow (related: https://github.com/Automattic/jetpack/issues/4615)
- [x] Monitor downtime (https://github.com/Automattic/jetpack/issues/4474) 
- [ ] Notices

**Comment by richardmuscat** [comment]
- [ ] Disconnected landing page
- [ ] Jump Start
- [ ] At a Glance (different modules states)
- [ ] Plans landing page (including name)
- [ ] Apps landing page (including name)
- [ ] Feature settings

**Comment by oskosk** [comment]
Looks like #4683 solved most of the list items.

**Comment by gravityrail** [comment]
This feature is removed in Jetpack 6.0.
