### ISSUE TITLE
Enabling Monitor Shows Downtime

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4474]
Reported by @annezazuu 

I enabled monitor on my pressable staging site and it immediately showed me a message about downtime which was a bit concerning:

<img width="387" alt="screen shot 2016-07-20 at 9 56 24 pm" src="https://cloud.githubusercontent.com/assets/11266471/17011660/e984373c-4ec4-11e6-9870-d47ebe3c1210.png">

I think the "empty state" should definitely not show this.

**Comment by samhotchkiss** [comment]
So, I think the "4.3.0" version of this is going to be to just hide "Last downtime..."

We can get this working robustly for 4.3.1 or 4.4

**Comment by richardmuscat** [comment]
We can probably handle this here: https://github.com/Automattic/jetpack/issues/4472

**Comment by eliorivero** [comment]
Closing since it's handled in #4472 and has patch in #4683
