### ISSUE TITLE
Admin Page: Backups and Anti-spam can't be disabled from the dashboard

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4480]
![number-format-security](https://cloud.githubusercontent.com/assets/426388/17027280/93a22ec4-4f63-11e6-86fa-69521b9bfda6.png)

> it’s not totally obvious why I can toggle “Protect” but don’t have the option for “Backups” and “Anti-spam.”

**Comment by jeffgolenski** [comment]
This is intentional since they are paid upgrades and we don't want folks to accidentally shut them off from the dash.

**Comment by jeffgolenski** [comment]
Also - there should be "pro" labels next to their names. hmmmm
