### ISSUE TITLE
Admin Page: Akismet and VaultPress are always marked as off

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4481]
#### Steps to reproduce the issue

1. Enable and configure Akismet and VaultPress on your site.
2. Head to Jetpack > Settings > Security.
3. Both options are marked as off

![screen shot 2016-07-21 at 5 10 47 pm](https://cloud.githubusercontent.com/assets/426388/17027997/5def647e-4f66-11e6-8b3d-96c6f2f2522b.png)

**Comment by dereksmart** [comment]
Fixed by #4500
