### ISSUE TITLE
Admin Page Stats: Right aligned tooltips have the arrow misplaced

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4486]
![xmy6k-ktrs thumb](https://cloud.githubusercontent.com/assets/426388/17029442/865a1d8c-4f6b-11e6-8184-9304317974a8.png)

**Comment by eliorivero** [comment]
<img width="402" alt="rtl" src="https://cloud.githubusercontent.com/assets/1041600/17105296/09dd761a-525d-11e6-82f9-ab6d8f3a8cc3.png">

**Comment by jeffgolenski** [comment]
The arrow is visible, so I don't think we need this for beta. But will be good to have for actual release

**Comment by richardmuscat** [comment]
Step 1: hide the arrow
