### ISSUE TITLE
Add Houzz Shortcode from WordPress.com

### ISSUE THREAD

**Issue by cliffordp** [Automattic/jetpack#449]
http://www.houzz.com/buttonsAndBadges#shortcode

**Comment by alexgodlex** [comment]
@georgestephanis SO i just have to create a file (where ?) houzz.php and put that code in it ? But i don't have to make that file load from WP somehow ?

Not possible to make that code working inside Jetpack, just to be able to make all the social icons look the same and at the same place ?

**Comment by jeherve** [comment]
@alexgodlex We'll see about adding the shortcode to the next version of Jetpack. In the meantime, you can apply the patch in #3435 to enable Houzz embeds.

That patch creates a new file, `houzz.php`, under `modules/shortcodes/houzz.php`. That's all you need to do :)
