### ISSUE TITLE
Admin Page: Stats layout issues in Dev Mode

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4490]
When in Jetpack Development mode, the Stats screen is populated with dummy data. However, that data doesn't appear to be styled properly. Note the tooltip and the graph axis:

![screen shot 2016-07-21 at 6 32 44 pm](https://cloud.githubusercontent.com/assets/426388/17030994/57fb23d0-4f72-11e6-967d-94dd80e9e2b2.png)

**Comment by eliorivero** [comment]
<img width="779" alt="notindevmode" src="https://cloud.githubusercontent.com/assets/1041600/17105983/d23581f0-525f-11e6-9fcf-3f5c520d9760.png">
Stats are no longer displayed in Dev mode. Instead, a message is displayed.

**Comment by jeherve** [comment]
@eliorivero I don't seem to get that message on my end:

![screen shot 2016-07-25 at 7 08 52 pm](https://cloud.githubusercontent.com/assets/426388/17110073/4b1d6ce6-529b-11e6-9c21-c6a88de7cdca.png)

I used the constant in my `wp-config.php` file to enable Development mode.
