### ISSUE TITLE
Admin Page: connection settings layout issues

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4493]
#### Steps to reproduce the issue

1. Connect your site to WordPress.com
2. Log out. of your site.
3. Log back in with another admin user.
4. Go to Jetpack > Settings > Connection Settings

![screen shot 2016-07-21 at 6 50 52 pm](https://cloud.githubusercontent.com/assets/426388/17031363/12bad94e-4f74-11e6-8f81-d9a0f0e11574.png)

**Comment by jeffgolenski** [comment]
@jeherve hey man – having a little trouble reproducing this given the instructions above. I can't get to the same screen you're seeing.

If I'm not connected to wpcom, I always see the connection landing page...
<img width="1112" alt="screen shot 2016-07-30 at 3 16 37 pm" src="https://cloud.githubusercontent.com/assets/214813/17272605/cc52347e-5668-11e6-9d98-cd5602e5431f.png">


And if I click "link to WordPress.com" the only thing I see in the connection card is this...
<img width="757" alt="screen shot 2016-07-30 at 3 18 29 pm" src="https://cloud.githubusercontent.com/assets/214813/17272614/fad8b2a0-5668-11e6-8ed7-43838d7c6e58.png">


Any insight on how to see these buttons together?

**Comment by jeherve** [comment]
@jeffgolenski From the looks of your admin menu bar, I think the secondary user you logged in with is not an admin; it's an editor, and as such won't have access to the Jetpack Settings screen.

That said, even when logging in as another admin, I can't seem to access the Settings screen anymore, unless my account is linked to WordPress.com. It seems that behaviour changed in the past few days.

@eliorivero Since you're working on something related in #4607, could you take a look? I think other admins should be able to activate / deactivate modules, even when they're not connected to WordPress.com. That's the current behaviour in Jetpack 4.2.
