### ISSUE TITLE
Admin Page: can't install / activate Akismet & VaultPress from the admin page

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4495]
![jetpack43-bubel1](https://cloud.githubusercontent.com/assets/426388/17033719/be6f9bd4-4f7f-11e6-8711-d7237e587276.gif)

Switching the toggles on should allow one to turn on the plugins, and configure them maybe?

**Comment by ryelle** [comment]
I'm having the same issue. I try to toggle on Akismet, but it only flashes blue for a second before going back to inactive. In my console I see:

`PUT http://myurl.com/wp-json/jetpack/v4/module/akismet/activate 404 (Not Found)`

And the request itself returns `The requested Jetpack module was not found`

I have akismet installed but inactive.
