### ISSUE TITLE
Rename Publicize settings

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4498]
Link to old settings sounds not so great. Can we change it to something like the following?

- Link to Settings
- Settings
- Configure Publicize
- Connect Accounts

There's no reason to say these are old settings!

<img width="746" alt="screen shot 2016-07-20 at 9 58-1 22 pm" src="https://cloud.githubusercontent.com/assets/11266471/17030812/249ffffc-4f26-11e6-935a-52379adea19c.png">

**Comment by oskosk** [comment]
This could apply to all the other settings like this. I'm starting a PR for further discussion
