### ISSUE TITLE
Contact Form: allow users to upload media via the form

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#450]
It would be nice to add a new option to the contact form to allow users to submit images via the form.

Originally request here: http://wordpress.org/support/topic/contact-form-79?replies=

Ported from https://plugins.trac.wordpress.org/ticket/1810

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/file-uploading-for-jetpack-contact-form?replies=1&view=all

**Comment by RCowles** [comment]
Also suggested here:
https://wordpress.org/support/topic/contact-form-163?replies=2

**Comment by lamdayap** [comment]
suggested here: 2900098-t

**Comment by dac2020** [comment]
Interesting that this is not added considering the importance of allowing users to upload files in this day of everything being media. Guess I have to get rid of jetpack and go with something else.

**Comment by coder-karen** [comment]
Also suggested here: 1379218-zen

**Comment by StefMattana** [comment]
Also suggested here: 1453908-zen

**Comment by coder-karen** [comment]
Also suggested here: 1551785-zen

**Comment by tmmbecker** [comment]
2014256-zen

**Comment by anaemnesis** [comment]
Requested here https://jetpack.com/2020/07/07/87-easier-reach-customers/#comment-199718

**Comment by danmaze** [comment]
Recently suggested here: 4101831-zen

**Comment by jeherve** [comment]
Internal references:

- pb5gDS-2vm-p2
- pb5gDS-gt-p2

**Comment by ariel-maidana** [comment]
Another request here: 6711210-zd-a8c
