### ISSUE TITLE
Font stack / Dashboard Widget: remove Proxima Nova since it is not enqueued anywhere.

### ISSUE THREAD

**Issue by wolffe** [Automattic/jetpack#4508]
On WordPress 4.4, 4.5 and 4.6-beta, the "Please Connect Jetpack" dashboard widget uses Proxima Nova, a commercial font family. As very few users have that font installed as a .ttf on their computers, the box defaults to Arial.

The font family should not be declared, as it is inherited from `admin.css`.

Before:

![before](https://cloud.githubusercontent.com/assets/910240/17063023/4dc17386-502d-11e6-89d2-e66300dacfce.png)

After:

![after](https://cloud.githubusercontent.com/assets/910240/17063032/54132162-502d-11e6-9663-b4c0eb1c734e.png)

By changing `/jetpack/css/dashboard-widget.css` at line 13:

`font-family: "proxima-nova", "Open Sans", Helvetica, Arial, sans-serif;`

with:

`font-family: inherit;`

or completely removing it, the problem would be solved.

**Comment by jeherve** [comment]
Thanks for the report.

Related: #4322
