### ISSUE TITLE
SSO: broken link in Single Sign On 2FA prompt

### ISSUE THREAD

**Issue by designsimply** [Automattic/jetpack#4512]
The "Two-step Authentication" link in the the Single Sign On 2FA prompt is broken (<a href="https://cloudup.com/clymdia6cF2" rel="nofollow">1m35s</a>).

Steps to reproduce:

<ol>
<li>Start with a Jetpack blog connected to a WordPress.com account without 2FA enabled</li>
<li>Go to wp-admin > Jetpack > Settings > Security</li>
<li>Enable Single Sign On</li>
<li>Check the the options for "Match By Email" and "Require Two-Step Authentication"</li>
<li>Click the Save button</li>
<li>Log out of the blog</li>
<li>Try to log back in to the blog by clicking the "Log in With WordPress.com" button</li>
<li>Click the "Security Settings" link (should work)</li>
<li>Go back and click the "Two-step Authentication" link (doesn't work)</li>
</ol>

<strong>Result:</strong> clicking on the "Two-step Authentication" link results in an error:

<blockquote>
  Error, invalid response data.
</blockquote>

![screen shot 2016-07-21 at thu jul 21 7 13 16 pm](https://cloud.githubusercontent.com/assets/1119271/17065470/3b2b1296-4fff-11e6-8e53-bf8bb4cf6e7c.png)

![screen shot 2016-07-21 at thu jul 21 7 12 44 pm](https://cloud.githubusercontent.com/assets/1119271/17065391/cffb8b90-4ffe-11e6-88af-d6fdcfbaa17c.png)
<sup>Seen at http://alittletestblog.com/wp-login.php?action=jetpack-sso&result=success&user_id=4507313&sso_nonce=fqttdf78nugjlfwgkjtd using WP 4.5.3, Jetpack Version Beta (Build 1736028) with Single Sign On enabled, tested with Safari 9.1.1 on Mac OS X 10.11.5</sup>

See #4502 /ht @ebinnion

**Comment by jeherve** [comment]
Fixed in #4502
