### ISSUE TITLE
Admin Page: No option to dismiss Stats prompt after disabling the module

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4514]
#### Steps to reproduce the issue
1. Go to Jetpack > Dashboard.
2. See the Stats.
3. "I'm not interested in Stats, I already use x".
4. Look for a way to remove the Stats module from that screen, but there is no way to dismiss it, nor any links to settings.
5. See the Settings submenu. Click it.
6. Deactivate Stats.
7. Go back to the Dashboard page:

Get this non-dismissable notice:

![screen shot 2016-07-22 at 8 04 10 pm](https://cloud.githubusercontent.com/assets/426388/17066478/81702b18-5047-11e6-8abe-292d1ff1a09d.png)

I'd like to be able to get rid of that, it takes valuable space in my Jetpack Dashboard. I also expect it to be dismissable, since other notices can be dismissed.

**Comment by dereksmart** [comment]
I think this is very much intentional, and I actually disagree that we should remove it.  

If we make this dismissible, why not make every other card on the dashboard dismissible if it's not being used?  

Over 95% of Jetpack sites have stats enabled already.
