### ISSUE TITLE
Poor quality animated gifs after resizing with Photon

### ISSUE THREAD

**Issue by joeyblake** [Automattic/jetpack#4528]
#### Steps to reproduce the issue

1. Attempt to resize this animated gif. https://i1.wp.com/fivethirtyeight.vip.10uplabs.com/wp-content/uploads/sites/9/2016/07/538-opioids-big.gif?strip=all

2. Example size resizing to 1024px wide https://i1.wp.com/fivethirtyeight.vip.10uplabs.com/wp-content/uploads/sites/9/2016/07/538-opioids-big.gif?strip=all&w=1024

Another example

1. Original gif, 1200px wide https://i2.wp.com/fivethirtyeight.vip.10uplabs.com/wp-content/uploads/sites/9/2016/07/riddler_4x3_default.gif?strip=all

2. Resizing only 50px smaller results in jagged edges in the gif. https://i2.wp.com/fivethirtyeight.vip.10uplabs.com/wp-content/uploads/sites/9/2016/07/riddler_4x3_default.gif?strip=all&w=1150

#### What I expected

An image returned of comparable quality to the original, but at the new size.

#### What happened instead

Photon returned an animated gif of the correct size. But with pretty bad artifacts in the gif.

**Comment by kraftbj** [comment]
Howdy Joey! This is part of the server-side bits of Photon ( https://code.trac.wordpress.org/browser/photon/ ). cc: @darthhexx for informed response.

**Comment by kraftbj** [comment]
From the dev docs, `Some animated gifs break if resized or transformed via Photon.`. Most software, when resizing gifs, resamples the whole image, which can take prohibitively long for a real-time service like Photon. Photon seeks to find a fair compromise between speed and quality, which doesn't fare well for some animated gifs.

I'm marking this as `wontfix` since it is a known issue in the docs. Improving the compromise is on the system's team radar for when there's new technique/libraries available.

**Comment by MarceloPedra** [comment]
Hey guys. Is there any way to exclude .gif files from Photon in order to circumvent this issue?

**Comment by jeherve** [comment]
> Is there any way to exclude .gif files from Photon in order to circumvent this issue?

@MarceloPedra This issue should now be fixed, as per this ticket:
https://code.trac.wordpress.org/ticket/44

If you still have some issues with some of the images on your site, could you contact us via [this form](https://jetpack.com/contact-support/?rel=support) and give us a few examples, so we can take a closer look?

You can also use this filter to exclude some of your images from being processed by Photon:
https://developer.jetpack.com/hooks/jetpack_photon_skip_for_url/
