### ISSUE TITLE
Admin Page - Protect: not saving comma separated IPs

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#4532]
#### Steps to reproduce the issue
- go to Admin Page, and try to add a new IP like this:
`1.2.3.4`
- save
Reload, and the IP is there. Now add one separated by a comma so it looks like:
`1.2.3.4,5.6.7.8`
- save and reload

#### What I expected
- after reloading the page, I expected both IPs to be in the text box

#### What happened instead
- only the first one was in the text box

Note: saving when IPs are separated on their own line works.

**Comment by oskosk** [comment]
I'm gonna need to add formatting on output because the current value for this Protect settings is arriving as an array and I was not taking this in account.
