### ISSUE TITLE
Admin Page: wrong cursor for Akismet and VaultPress info links

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4536]
The “Learn more” link in the screenshot above shows the “text select” cursor, not the “link pointer” cursor.

![screen-shot-2016-07-25-at-16-17-50](https://cloud.githubusercontent.com/assets/426388/17111275/109bdc0a-52a1-11e6-9abe-54aa829070fe.png)

Similar for the same link in the Akismet panel of the settings.

**Comment by eliorivero** [comment]
Not a design issue. They weren't pointing to any URL. I've added a PR solving this pointing them to 
https://akismet.com/jetpack/ and https://vaultpress.com/jetpack/
