### ISSUE TITLE
Admin Page: include filter to disable promotion tabs and boxes

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4537]
The current version of Jetpack includes the `can_display_jetpack_manage_notice` filter to hide the Manage banners everywhere in the dashboard:
https://developer.jetpack.com/hooks/can_display_jetpack_manage_notice/

It would be nice to offer a similar filter to remove all promotion materials from the new Jetpack Interface.

**Comment by richardmuscat** [comment]
Hmmm. Why would we want to do that? :-)

**Comment by jeherve** [comment]
> Why would we want to do that?

In some environments (like large multisite networks for example, or managed WordPress solutions), network admins or sysadmins build a WordPress solution that works out of the box for their users, with their own set of plugins, their own backup solution, ...  Users can't install additional plugins, can only enable a specific set of plugins, Jetpack features, or core features; the whole installation is built to just work, customized thanks to home-made plugins, and everything that the user can't use or shouldn't use is hidden, to avoid confusion.

In those cases, network admins and sysadmins would like to be able to customize the look of the Jetpack interface as well. Until 4.3, they were able to customize the list of modules thanks to filters. The interface now includes a lot more information, and potentially a lot of options that shouldn't be displayed to their users.

Instead of relying on CSS to hide that information, it would be nice if it could be removed via filters.

**Comment by samhotchkiss** [comment]
This is also something that WordPress.org uses for the make.wordpress.org sites, I do think that it's important to maintain this functionality
