### ISSUE TITLE
Admin Page: change Akismet link to go to auto-config when site has a plan, but not Akismet yet

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4539]
#### Steps to reproduce the issue

1. Purchase a Professional plan for your Jetpack Site.
2. Do not install or activate Akismet or VaultPress.
3. In your Jetpack dashboard, go to the `Professional` tab.
4. You'll see this link:

![screen shot 2016-07-25 at 8 20 01 pm](https://cloud.githubusercontent.com/assets/426388/17112162/310559a4-52a5-11e6-93e0-bfb2492ecc58.png)

Akismet isn't active, so that button redirects me to an error page.

It would be nice to link to the new Plan auto config page instead.

**Comment by richardmuscat** [comment]
@ryelle can we easily hook into the plugin auto-config in the scenario above?

**Comment by ryelle** [comment]
Yep -- in my original suggestion I mentioned that Jetpack could detect if the plugins are not active, and add a button or link to `/plugins/setup/$site`. That's all that's needed to start the flow.
