### ISSUE TITLE
Multiple hyphens causes content to be truncated

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#454]
If you post this via Post By Email, the contecnt after the hyphens gets truncated.

```
A header
--------

Then some more
```

Originally posted here: http://wordpress.org/support/topic/post-by-email-broken-with-multiple-hyphens?replies=1

**Comment by samhotchkiss** [comment]
Our implementation of Post by Email is intended to be very simple and minimal, so, unfortunately, this doesn't align with our development goals and plans at this time, and is not on our roadmap for future development.
