### ISSUE TITLE
Admin: AAG dashboard action inconsistencies with plan type

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#4540]
**Akismet**

While testing https://github.com/Automattic/jetpack/pull/4500 I discovered that if I have a pro plan and I uninstall akismet, I'm prompted to upgrade via the anti-spam card on the AAG dashboard. 

![screen shot 2016-07-25 at 2 34 29 pm](https://cloud.githubusercontent.com/assets/214813/17112726/4a95f0ac-5275-11e6-8a36-2995f438ff0c.png)

This should say "install" instead of "upgrade" since the plan is already purchased. 

**VaultPress:**

Secondly, if I have the pro plan and _delete_ VP, on the dashboard the VP cards prompt me to "activate" backups and security scan, rather than "install"

![screen shot 2016-07-25 at 5 08 34 pm](https://cloud.githubusercontent.com/assets/214813/17117738/923c15d8-528b-11e6-8186-fdb166c6c37d.png)

(possibly issue for premium plan too)

**Comment by jeherve** [comment]
Related: #4538

**Comment by jeffgolenski** [comment]
Updated the description. two part issue
