### ISSUE TITLE
Stats: Quickly moving mouse across bar graph leaves ghost tooltips

### ISSUE THREAD

**Issue by Viper007Bond** [Automattic/jetpack#4541]
See https://github.com/Automattic/wp-calypso/issues/7003

Affects Jetpack dashboard too.

**Comment by oskosk** [comment]
Was able to confirm on current Stats Graph with Firefox 47.0

![tooltipbars](https://cloud.githubusercontent.com/assets/746152/17446620/7486b8fc-5b20-11e6-9b6e-e775d6e7f1aa.gif)

**Comment by Viper007Bond** [comment]
This was fixed in Calypso (https://github.com/Automattic/wp-calypso/pull/7217) so we just need to port over that code.

**Comment by eliorivero** [comment]
Fixed in https://github.com/Automattic/dops-components/pull/63
