### ISSUE TITLE
Admin Page: better consistency with VaultPress links

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4548]
![screen-shot-2016-07-25-at-16-45-33](https://cloud.githubusercontent.com/assets/426388/17131021/acfdf5b8-531b-11e6-9575-2abcbbdb0ae0.png)

“View details at VaultPress.com” links to https://dashboard.vaultpress.com/

But “View your security dashboard” links to Calypso.

![screen-shot-2016-07-25-at-16-46-30](https://cloud.githubusercontent.com/assets/426388/17131042/c28463e0-531b-11e6-8ea7-2cbc8520c375.png)

It would be nice if all links leaded to the same page to avoid user confusion, or phrase things differently to make it clear that one link is for settings, while the other is for backup / security threat management.

**Comment by richardmuscat** [comment]
We should send everyone to dashboard.vaultpress.com

**Comment by eliorivero** [comment]
It's done in #4585
