### ISSUE TITLE
Admin Page: add link to Plugin Management in Calypso

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4549]
Right now, the plugin management box in the Jetpack dashboard may include a link to `wordpress/plugins/yoursite.com`, but only if you haven't enabled auto updates yet:

![screen-shot-2016-07-25-at-8-38-38-pm](https://cloud.githubusercontent.com/assets/426388/17131161/7e509eb8-531c-11e6-85c9-60e7333603a7.png)

![screen shot 2016-07-26 at 10 35 24 am](https://cloud.githubusercontent.com/assets/426388/17131200/b3125290-531c-11e6-8316-148c7970b14a.png)

It would be nice to make it clear that you can always manage your plugins there.

**Comment by keoshi** [comment]
A quick win for the up-to-date view would be to add “***Manage your plugins***" link.

**Comment by rickybanister** [comment]
Something like this would be a nice reuse of our patterns:

![image](https://user-images.githubusercontent.com/437258/37726260-59e8ff96-2d0b-11e8-87d0-12ffaaf181d2.png)

Those dashboard cards need a bigger rethink, but for now if we could do something similar to this it would be v nice.
