### ISSUE TITLE
WP.me Shortlinks: URL expander & GET param preservation

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#455]
I've noticed that URL arguments are NOT preserved when a URL is expanded, ie. `http://wp.me/p1w6tN-kqf?something=1`. We (10up) have a couple clients who would like to make use of persistent URL arguments so we can perform actions AND analytics. Is there a reason that URL arguments are NOT preserved or is this a bug?

Ported from trac:
- https://plugins.trac.wordpress.org/ticket/2187

**Comment by yuk75** [comment]
You need it for Analytics, SEO stuff....which is not wise to ignore.

"When users click one of the custom links, the unique parameters are sent to your Google Analytics account, so you can identify the URLs that are most effective in attracting users to your content."

Googles URL builder:
https://support.google.com/analytics/answer/1033867?hl=en

**Comment by c3zh** [comment]
Also requested in Requested in Requested in 2256260-t

**Comment by samhotchkiss** [comment]
After internal discussion, we've decided that this is outside the scope of how we see wp.me URL shortening.  For clients who need the ability to add on URL params, we would recommend that they either use the full URL, roll their own URL shortening service, or use an alternate shortening service
