### ISSUE TITLE
JSON API: `sites/%site%/posts` endpoint returns full post content, including hooked content like sharing buttons

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4601]
![screen shot 2016-07-18 at 3 15 14 pm](https://cloud.githubusercontent.com/assets/426388/17254351/ce7e6740-55b4-11e6-84bf-4a2a8c3f24a5.png)
#### Steps to reproduce the issue
1. Go to Posts > Add New.
2. Create a new post with the title `Testing a post` and the post content `Some content. Not much.`.
3. Publish the post right away.
4. Head over to wordpress.com/posts/yoursite.com

![screen shot 2016-07-19 at 10 37 28 pm](https://cloud.githubusercontent.com/assets/426388/17254374/f17ccc1e-55b4-11e6-85fd-78502cd7eb36.png)

**Comment by enejb** [comment]
I wasn't able to replicate this bug. 
We did a few fixes such disabling the sharing filters when we sync data so this shouldn't show up in the api any more. 

Feel free to reopen this issue if you can still replicate this bug.

**Comment by lancewillett** [comment]
Definitely still happening.

See also https://github.com/Automattic/wp-calypso/issues/1292 and https://github.com/Automattic/wp-calypso/issues/8491

**Comment by lancewillett** [comment]
@enejb One easy way to duplicate is to enable the o2 plugin and activate the P2 Breathe theme on a Jetpack-connected site. You'll then see `Reply` text in each post preview in the Calypso post list. (This same bug doesn't happen with a WP.com site running the P2 Breathe theme.)

**Comment by enejb** [comment]
@lancewillett I tried replicating this but wasn't able to. :( 

Any other tips to replicate this. I can invite you to my test site if that would help. 
Do you have a post and site ID I can take a look at.

Do you see a difference between 
/me/posts and /sites/$site_id/posts GET endpoints for the post that this is affected.

**Comment by lancewillett** [comment]
@enejb Added you to my Pressable Jetpack test site (using your Gmail address).

Here's the dev console output example for blackedoutrims.com for `sites/$site_id/posts`

![screen shot 2017-01-16 at 16 27 00](https://cloud.githubusercontent.com/assets/66797/22002350/a70f9ffa-dc08-11e6-822b-1b55aa4d8410.png)

Both `content` and `excerpt` have the Sharedaddy code inserted in it.

The `/me/posts` returned content *does not* have the unwanted filtered content.

**Comment by lancewillett** [comment]
@jeherve Still happening on your Jetpack sites also?

**Comment by enejb** [comment]
I was able to replicate this. It turns out my site's api endpoint was always returning from the shadow site. 

This PR should fix the issue for the Jetpack plugin but I think the O2 plugin issue that also happens should be fixed in the O2 plugin.
