### ISSUE TITLE
Admin Page: mark all paid modules as paid

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4603]
It'd be nice to add a little "pro" label next to premium features, on both the dashboard and the settings cards.

<img width="739" alt="screen shot 2016-07-29 at 2 25 02 pm" src="https://cloud.githubusercontent.com/assets/214813/17259165/477b9a04-5598-11e6-823e-b7fd6f1d171a.png">

**Comment by jeherve** [comment]
Closing in favor of #3989

**Comment by jeffgolenski** [comment]
Actually this specific issue is still relevent so we make sure it's not missed. cc @dereksmart

**Comment by jeffgolenski** [comment]
Just kidding. Realized this was fixed in https://github.com/Automattic/jetpack/pull/4500

Goodbye!
