### ISSUE TITLE
Admin Page: consider removing Holiday Snow feature

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4615]
> The `Miscellaneous Settings` section says `Manage Snow and other fun things for your site.`, but the only thing in there is snow. Where are my other fun things?

I can think of 2 different ways to solve this issue:

1. Change wording and avoid mentioning "other fun things" if the section only includes Holiday Snow.
2. Remove Holiday Snow from Jetpack. Related issue: #1349

**Comment by richardmuscat** [comment]
Jesse and I will deal with this over here: https://github.com/Automattic/jetpack/issues/4472

**Comment by gravityrail** [comment]
Closed because feature is removed in Jetpack 6.0.
