### ISSUE TITLE
Jetpack Error API

### ISSUE THREAD

**Issue by blobaugh** [Automattic/jetpack#462]
This come from an internal discussion with @kraftbj and Mark Riley.

The basic idea is to have the wporg site ping the Jetpack server if it encounters an error. The wporg site will include the error number and the Jetpack server will return details relevant to that error such as possible solutions. See @kraftbj original list below.
- We codify error numbers for the various things that we see in Jetpack.
- The site pings jetpack.me for the support text for that error number.
- If found, return the error message (troubleshooting suggestions, links to other tools as needed)
  *If not, return the contact form (basically what we have now)
- If errors out on the attempt to ping jetpack.me, return troubleshooting tips regarding their server blocking outbound HTTP connections, etc.
- If using outdated Jetpack, suggest upgrade before allowing them to contact us.

**Comment by jeherve** [comment]
Closing this in favor of #2534
