### ISSUE TITLE
Parent relationship between the terms of the nova_menu taxonomy

### ISSUE THREAD

**Issue by implenton** [Automattic/jetpack#4632]
The `nova_menu` is registered as hierarchical thus giving the possibility to set parent terms.
1. Activate Simple Food Menus
2. Create at least two Menu sections (ex. Drink and Food)
3. Create a third one and set the parent (ex. Fish and set the parent to be Food)
4. Add Menu Items to the Menu Sections

![screenshot 2016-08-02 20 15 50](https://cloud.githubusercontent.com/assets/19433935/17338039/43b356b0-58ee-11e6-9e42-277f1c39d35f.png)

On the Add/Edit Menu Item using the `menu-checkboxes.js` Jetpack overwrites the default functionality of the taxonomy form. You can only select _one_ Menu Section for an item, can't select two or both parent and children.

On the Menu Items listing screen Menu Sections can be ordered in any way, no relation whatsoever with the parent relationships set on terms.

![screenshot 2016-08-02 20 15 45](https://cloud.githubusercontent.com/assets/19433935/17338040/43b67138-58ee-11e6-9b90-8b942bb878f3.png)

There is a filter called `setup_menu_item_loop_markup__in_filter` attached to the `template_include` which starts the build process for the Menu Sections markup rendering and it does not take into account any hierarchical relationships.

```
<section class="menu-items">
    <header class="menu-group-header">
        <h1 class="menu-group-title">Food</h1>
    </header>
    salmon
</section>

<section class="menu-items">
    <header class="menu-group-header">
        <h1 class="menu-group-title">Drink</h1>
    </header>
    Vodka orange
</section>

<section class="menu-items">
    <header class="menu-group-header">
        <h1 class="menu-group-title">Fish</h1>
    </header>
    test
</section>
```
### Assumption from my part

I believe the `nova_menu` is registered as hierarchical to make it easier for the user to select the corresponding Menu Sections - at least, I prefer the "category style", instead of the tags - and to use the `menu_order` for ordering.
### What I see as a problem

Since there is no support and consideration given to the hierarchical relationship between the terms I suggest to remove the parent dropdown because it induces user error and/or confusion.
### Solution

`wp-admin/edit-tag-form.php` there is no filter for individual inputs elements, only actions are supported to prepend elements, etc.

There is no way actually to remove from the form, but using CSS it can be hidden.

_If this is considered as a valid bug/suggestion I can make a pull request for it._

**Comment by jeherve** [comment]
cc @mdawaffe, who originally worked on Nova. What do you think of the idea?

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
