### ISSUE TITLE
Admin page: Jump Start shows after skip

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/jetpack#4637]
Upon connecting Jetpack, if you choose to "skip" the Jump Start step, then navigate to a Calypso page via one of the links, and then hit "Back" (browser), you will be shown the Jump Start step.

This does not happen if you refresh the wp-admin page.

Screencast: https://cloudup.com/c2qwoyFf5g9

**Comment by samhotchkiss** [comment]
Bumping to 4.3 as it's not a beta-blocker
