### ISSUE TITLE
Admin Page: Checkbox styles

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#4655]
The Admin Page Settings checkboxes look as just boxes with an displaced blue border when checked instead of showing the ✓ inside the box

#### Steps to reproduce the issue

I'm not sure. but @eliorivero and I started experiencing this today. 

Get to Admin Page, Settings, open the **Site Stats** card and look at the checkboxes

#### What I expected

To see regular checkboxes with dops-components styles

#### What happened instead

They look like this 

![image](https://cloud.githubusercontent.com/assets/746152/17405166/d2068bfc-5a34-11e6-8202-d96be29c248a.png)

**Comment by MichaelArestad** [comment]
I tried reproducing on Chrome for Mac with no luck. I'm on master for both repos. Ideas?
