### ISSUE TITLE
Admin Page: Add eCommerce Promotion Tab

### ISSUE THREAD

**Issue by allendav** [Automattic/jetpack#4659]
Add a tab to the Jetpack admin page promoting eCommerce features. In addition to promotional copy and an appropriate background/visual design, there would be a button (buttons?) on the tab to install and/or activate WooCommerce and install and/or activate Connect for WooCommerce.

@kellychoffman will be working with @MichaelArestad and @jeffgolenski on mocks that fit in with the other existing tabs.

Note that Connect will be the sort of behind-the-scenes tech powering eCommerce services for WooCommerce, but that we don’t want customers to know/care about it as a brand.

Instead, we’ll promote the specific services as features and eventually (as a future issue) roll those features into plans.

cc @avivapinchas @johnHackworth

**Comment by MichaelArestad** [comment]
I'm wondering if this should be it's own tab or if we should combo it with Apps or Plans. Is this a paid service?

**Comment by allendav** [comment]
> I'm wondering if this should be it's own tab or if we should combo it with Apps or Plans. Is this a paid service?

It is not a paid service at this time and it will always have some free features. We provide real-time shipping rates for USPS and Canada Post at no charge.  It does collect on-demand payments for shipping labels. Down the road we do want to have premium features associated with plans, but that is not in the initial offering.

I also personally don't think I'd intuitively expect eCommerce features on our Professional tab, aka the Plans tab.  Heck, I still miss that we even have a nav bar there.  If we were to not have a separate eCommerce tab, I'd recommend renaming the Professional tab to something like "Professional and eCommerce"

But, if we don't rename the tab, I'd recommend making it possible someway to tell a little bit about what's in the tab without having the user have to open the tab, otherwise I think they may never look inside either the Apps nor the Professional tab for eCommerce (or Security or etc), e.g. something like this (admittedly this is vertical)

![img_0783](https://cloud.githubusercontent.com/assets/1595739/17564496/52d8704e-5ee8-11e6-98c5-2a2e5e394764.JPG)

**Comment by avivapinchas** [comment]
> While I do think makes sense to plug eCommerce features in with "Plans", that tab isn't explicitly named as such.

The long term view is to align connected features with plans, but we're not there yet. I'd prefer we don't make a connection between these features and Jetpack plans as we don't know how they'll come together in future, if they'll come together, etc. 

> I'm wondering if this should be it's own tab or if we should combo it with Apps or Plans.

What we have to promote is two eCommerce features (real time rates, shipping labels) that 'power up' your WooCommerce store. So the question is: where does it make the most sense to promote these WooCommerce-specific added features, which are not part of any plan? 

Apps would make sense, but agree with @allendav that having more visibility would be great. Do we have any data on how much visibility the different tabs get? Perhaps there's a way to call out the eCommerce bits in a special way within a tab? Just thinkin' out loud there.

**Comment by MichaelArestad** [comment]
> Apps would make sense, but agree with @allendav that having more visibility would be great.

We're going to have to really prioritize which things we're promoting and how visible they are. There are already a few thing competing for attention including setting up various JP items, promoting plans, promoting apps, and promoting Calypso. We'll have to figure out where on the list of priorities we find it makes sense for our users. Let's also figure out more context-specific promotions. 

> Do we have any data on how much visibility the different tabs get?

We don't know yet. It's still in alpha (and beta soon).

> Perhaps there's a way to call out the eCommerce bits in a special way within a tab? Just thinkin' out loud there.

We were discussing the possibility of calling out these things during our NUX flow including a way to install the plugin automatically.

**Comment by avivapinchas** [comment]
> We're going to have to really prioritize which things we're promoting and how visible they are. 

Makes total sense & to be expected :) I defer to you guys on what you think makes sense for the full Jetpack experience and where you can fit us in. 

> We were discussing the possibility of calling out these things during our NUX flow including a way to install the plugin automatically.

That would be awesome! 

With Connect specifically, keep in mind that what we're launching is really two relatively small features (compared to the full Woo-niverse) - they're only useful for stores selling physical goods, and only in the US/Canada. Big deal for us because we've built an architecture that we can use for lots of things relatively soon, but not mega-huge for our users _yet_. 

So it's a balance of wanting to put it in front of more eyeballs, but not making it seem like such a huge deal that the features themselves fall short of those expectations.

**Comment by MichaelArestad** [comment]
> So it's a balance of wanting to put it in front of more eyeballs, but not making it seem like such a huge deal that the features themselves fall short of those expectations.

Right. I suspect we'll lean on pitching Woo as a whole and using Woo Connect to delight people as they start in on the Woo setup process by making those two things (at least to start) painless.

**Comment by allendav** [comment]
OK, it is unclear to me how we should proceed. Are we agreed on adding a tab for eCommerce to the Jetpack dashboard at least?  If so, how about we start with this quick mock based on the Professional tab and ask @avivapinchas for copy? (Quick inspector and GIMP hack - don't blame @kellychoffman)

The install button would ideally install and activate WooCommerce and connect in some manner (if they weren't already installed). We'll try to minimize the # of clicks the merchant will need to do to accomplish all this.

Are you ok with reassigning this issue to you @avivapinchas for copy? I think getting marketing copy right away for things like this will help clear up a lot of positioning confusion for connect.

<img width="1044" alt="empty-ecommerce" src="https://cloud.githubusercontent.com/assets/1595739/17859042/f6421b06-683c-11e6-8386-995a551762c1.png">

**Comment by avivapinchas** [comment]
Sure thing! [Draft here. ](https://docs.google.com/a/a8c.com/document/d/1JN7jHI8LefLNq-z21H8pieAddoc9_9I75k1C8bTHOP4/edit?usp=sharing) I've edited this with @nicoleckohler and @MarinaWoo, so they can help out while I'm AFK. Feel free to leave comments in the doc for us to review / think about!

**Comment by allendav** [comment]
@avivapinchas - this doesn't promote the (connect powered) services we're bundling at all? I wasn't expecting that :(

cc @nicoleckohler @MarinaWoo

**Comment by avivapinchas** [comment]
@allendav I don't think we need to get customers bought in to Connect as a platform/idea. Rather, it makes more sense to me to sell them on WooCommerce and have Connect be part of what you're installing. Then you see the Connect-ed options when setting up shipping and so on. 

I don't think having Connect or not would tip the scales on deciding to install WooCommerce or not.
