### ISSUE TITLE
Sharing: Need to ensure jQuery loads earlier

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#4661]
To reproduce:
* Use a theme like `_s` without any other plugins active. _s, out of the box, does not enqueue jQuery.
* Run Sharing

Expected:
No JS errors in the console

Actual:
jQuery not defined error.

What's happening is we're enqueuing sharing.js in the footer (with jQuery as a dependency) here: https://github.com/Automattic/jetpack/blob/4.1.0/modules/sharedaddy/sharing-service.php#L536

Within that same function, we're then calling the `display_footer` for each enabled function:
https://github.com/Automattic/jetpack/blob/4.1.0/modules/sharedaddy/sharing-service.php#L548

`display_footer` is calling `js_dialog` for that service. Example: https://github.com/Automattic/jetpack/blob/4.1.0/modules/sharedaddy/sharing-sources.php#L727

`js_dialog` is printing JS straight to the OB, including the jQuery call: https://github.com/Automattic/jetpack/blob/4.1.0/modules/sharedaddy/sharing-sources.php#L331

This is all being outputted before the initial function closes, so WordPress enqueues sharing.js (and thus, right before it when it hasn't already been enqueued, jQuery) _after_ we've printed the JS calling jQuery.

Original report: https://wordpress.org/support/topic/jquery-not-defined-10

**Comment by Otto42** [comment]
Suggestion: check for the wp_add_inline_script function (WP 4.5 and later) and switch to using that instead, so that you can have the output sure to happen after jQuery. 

For earlier versions of WP, probably simply put that script output into its own action hooked to wp_footer, with a lower priority.

**Comment by jeherve** [comment]
Related: #1223

**Comment by kraftbj** [comment]
Thanks @Otto42! 4.5 will be our minimum version supported once 4.6 ships, so that'll be the way to go.

**Comment by Nitin-Prabhakar** [comment]
First of all, sharedaddy injecting inline scripts is not a correct way to add content. Can't it be loaded as an external resource? so it can be cached, and loads deferred? 
If you HAD to inject them, why cant the module sharedaddy, add a very very very basic domcontent loaded check?
what if If jQuery is deferred?

**Comment by georgestephanis** [comment]
@Nitin-Prabhakar I'm going to be picking up the discussion on the other issue then, as while the symptoms may be similar, the causes are different.  Also, notifications can sometimes be wonky and easy to miss on closed issues.

**Comment by Nitin-Prabhakar** [comment]
Sure! Thanks Much for the attention it needs :+1: 
cheers!
