### ISSUE TITLE
Publicize: I somehow was able to create 2 connections for my 1 twitter account

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#4662]
One was a legacy connection and the other was regular publicize connection. 
In the UI there is no indication that there are 2 connection for the one twitter account. 

The problem that there was that when I created a post with image 2 tweets would show up. 
This is because we were sending 2 messages to twitter, and the messages are different in content. Since images get unique urls, this doesn't happen with text messages because twitter knows that the same messages was posted just a few seconds ago. 

I am not able to replicate how I was able to create these 2 accounts.

I think this is a low priority bug since it can be easily fixed by removed the connections and re-adding it.

**Comment by jeherve** [comment]
> I am not able to replicate how I was able to create these 2 accounts.

What's the site URL? (You can also send that to me privately :) )

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
