### ISSUE TITLE
Share buttons on HTTPS blog cause insecure (HTTP) scripts to load

### ISSUE THREAD

**Issue by arcivanov** [Automattic/jetpack#4665]
#### Steps to reproduce the issue
1. Have site URL be an HTTPS URL. 
2. Turn on Jetpack. 
3. Turn on Sharing Buttons. 
4. Observe share button scripts load with insecure HTTP URLs. 

#### What I expected
Jetpack needs to take site URL protocol into account and load social scripts with HTTPS where appropriate.

#### What happened instead
* Mixed Content: The page at 'https://domain/2016/06/blog/' was loaded over HTTPS, but requested an insecure script 'http://platform.tumblr.com/v1/share.js'. This request has been blocked; the content must be served over HTTPS.

* Mixed Content: The page at 'https://domain/2016/06/blog/' was loaded over HTTPS, but requested an insecure script 'http://platform.linkedin.com/in.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by jeherve** [comment]
I can't seem to reproduce the issue on my end. Both Tumblr and LinkedIn resources are loaded via HTTPS on my HTTPS site.

In fact, both resources use protocol relative URLs, so they should use the protocol set on the page:
- https://github.com/Automattic/jetpack/blob/4.1.1/modules/sharedaddy/sharing-sources.php#L1387
- https://github.com/Automattic/jetpack/blob/4.1.1/modules/sharedaddy/sharing-sources.php#L831

Could you post your site URL here, so I can have a look?

If you want it to remain private, you can also contact us via this contact form:
http://jetpack.com/contact-support/

**Comment by arcivanov** [comment]
Link submitted via JP contact form. Thanks!

**Comment by kraftbj** [comment]
I'm not sure at initial look why the protocol relative links are using http instead of https, but 4682 could skip past the rabbit hole since we can use https all the time.

**Comment by arcivanov** [comment]
@kraftbj That's because it's not JetPack's sharing buttons. I'm a dumbass, sorry for all the trouble - it's my theme that is screwing up.
