### ISSUE TITLE
SSO: "Back to xx" uses HTTPS instead of HTTP

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#467]
Steps to reproduce:

1. Enable SSO on your Jetpack, and then log out.
2. Access your log in page.
3. Click on "Log in with WordPress.com"
4. A confirmation form appears, inviting you to log in with your WordPress.com account. Instead of clicking on "Log in" click on "Back to SITE_NAME"

That link uses HTTPS, regardless of your site settings.

Initially reported in 1810749-t

**Comment by dereksmart** [comment]
Looks like this has been fixed?  I'm seeing "back to SITE_NAME", which uses the url in my settings.

**Comment by jeherve** [comment]
Looks fixed on my end as well :+1:. Closing.
