### ISSUE TITLE
Admin - Plans: add Polldaddy card if user is on Professional plan

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#4670]
Need copywriting, button label, button link

**Comment by richardmuscat** [comment]
@rickybanister, can you provide @eliorivero with the headline, copy, and CTA for PollDaddy based on what you put together for the plans page? (the one we show after auto-config is done)

**Comment by rickybanister** [comment]
Here's what we currently have on the My Plan page:

<img width="727" alt="screen shot 2016-08-06 at 6 29 58 pm" src="https://cloud.githubusercontent.com/assets/437258/17459403/ccb7267c-5c03-11e6-8953-d2f328205171.png">
