### ISSUE TITLE
After the Deadline - do not strip code when proofreading posts

### ISSUE THREAD

**Issue by HardeepAsrani** [Automattic/jetpack#468]
Hey folks,

I use Jetpack's After the Deadline feature and I love it, but there's one small problem in it. If there's some php code (like 10-15l lines) it will most-likely mess with my code & will completely destroy it. ;(

After the Deadline shouldn't check for spellings on the <code>&lt;code&gt;</code> tag.

Thank you!

**Comment by jeherve** [comment]
Closing as duplicate of #156
