### ISSUE TITLE
VaultPress setup notice moves settings down

### ISSUE THREAD

**Issue by zinigor** [Automattic/jetpack#4693]
#### Steps to reproduce the issue
- Get a Jetpack site with no VaultPress installed.
- Get a professional plan for that site.
- Follow the "Install" button in the dashboard to install and activate VaultPress on WordPress.com.
- Go back to the dashboard and observe:
![screenshot from 2016-08-09 12-06-27](https://cloud.githubusercontent.com/assets/374293/17511074/8e02de9a-5e32-11e6-912e-515356765b14.png)

**Comment by dereksmart** [comment]
Not specific to VaultPress.  Any [`jetpack_notices`](https://github.com/Automattic/jetpack/blob/master/_inc/lib/admin-pages/class.jetpack-react-page.php#L138) action will be displayed above the app currently.

**Comment by samhotchkiss** [comment]
For further investigation...

**Comment by eliorivero** [comment]
If we do something like this:
```js
jQuery( '.vp-notice' ).each( function() { jQuery(this).addClass( 'dops-notice is-basic' ).removeClass( 'wrap' ).prependTo( jQuery( '#jp-plugin-container .jp-lower' ) ) } );
```
we can put the notice in the area with the other Jetpack notices

<img width="782" alt="captura de pantalla 2016-08-15 a las 17 02 23" src="https://cloud.githubusercontent.com/assets/1041600/17677337/bd04b6de-6308-11e6-9a5d-f36370df20e6.png">

Alternatively, we could add some styles in our Jetpack styles to add some margin to the VP notice:

<img width="1281" alt="captura de pantalla 2016-08-15 a las 17 06 27" src="https://cloud.githubusercontent.com/assets/1041600/17677482/57903d7c-6309-11e6-951e-9815521cc32c.png">

What do you think @jeffgolenski @MichaelArestad?

The issue can be quickly reproduced in a local server after activating VaultPress.

**Comment by MichaelArestad** [comment]
If we show a notice on this view, it should be where we show our JP notices. We should hide all other notices, in my opinion.

**Comment by jeffgolenski** [comment]
<img width="1281" alt="ugh-notices" src="https://cloud.githubusercontent.com/assets/214813/17705135/5385f586-63a5-11e6-8226-8a7b1e695244.png">


This is horrendous. Is there anyway we can have these notices moved in our jetpack admin area (to sit near the development version notice), which I think is what you're talking about @eliorivero ?
