### ISSUE TITLE
Related Posts Issue with WPML

### ISSUE THREAD

**Issue by KTPH** [Automattic/jetpack#4716]
#### Steps to reproduce the issue
Using Wordpress with WPML and Jetpack Related Posts Module (Latest version for all installed)

#### What I expected
I expected when I had the English version of my site selected it would only show related posts in English, and the same for French and any other languages I add.

#### What happened instead
Related Posts were showing a mixed results of French and English posts (My site is set to English with French translations)

**Comment by KTPH** [comment]
Below code has resolved the issue. Please confirm. Thanks.

```
// Filter Related Posts by Language
// Get the current language then filter posts to return those in current language
function jetpackme_filter_by_lang( $filters ) {

     $my_current_lang = apply_filters( 'wpml_current_language', NULL );
     $filters[] = array( 'term' => array( 'lang' => $my_current_lang ) );
     return $filters;

}
add_filter( 'jetpack_relatedposts_filter_filters', 'jetpackme_filter_by_lang' );
```

**Comment by chaselivingston** [comment]
2765494-t

**Comment by jeherve** [comment]
That's indeed to be expected, as Jetpack Related Posts show related posts from all other posts by default. If WPML stores the language as a custom taxonomy, the code you posted above will indeed help.
