### ISSUE TITLE
Settings: Writing / Ignored Phrases token field component

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack#4719]
**Currently** the token field seems half styled, has a strange :focus state on the wrapper (the green glow seems like a legacy thing?), and has a redundant inner input style. Also it doesn't submit on typing a comma—there's no affordance telling you to hit 'enter'. This generally made for a bad experience.

<img width="709" alt="screen shot 2016-08-10 at 12 34 01 pm" src="https://cloud.githubusercontent.com/assets/437258/17562015/c9aa4982-5ef6-11e6-84f9-c4219a56c88a.png">

**Ideally** we would port over Calypso's token field. The wrapper acts as the visual input and gets the proper Calypso :focus style. It splits tags when you type a comma or enter. The lack of nested input/focus styles make it more intuitive that you can hit 'delete' to remove a previous token.

<img width="488" alt="screen shot 2016-08-10 at 11 20 11 am" src="https://cloud.githubusercontent.com/assets/437258/17562025/d3579020-5ef6-11e6-8a7f-c174226880cb.png">

I wasn't sure which milestone was correct, feel free to edit the issue, or let me know how to triage properly.

cc @MichaelArestad

**Comment by oskosk** [comment]
At the time I had to balance how much was being introduced by token-field if ported over here.

Trying to bring in Calypso's token field resulted in a hell of unmet child dependencies, old data paradigms from early Calypso times and the same went for the styles which dependend on several other styles from other child components. 

I wish it could've been straightforward but it looked like bringing this component in, allowed more flexibility for styling

**Comment by oskosk** [comment]
Regarding the token-field comma behaviour, I saw it at first, but these are phrases, not tags. So, making the comma be a submit character was not an expected behaviour for me (at least IMO regarding the usage here).

**Comment by MichaelArestad** [comment]
@oskosk That makes sense. I would like us to ultimately use the Calypso version. If that can't make it in for this release, that's fine. We can flag it for the next release if you think it's going to take too much time (or not get done by next Thursday amongst the other issues you're tackling).

**Comment by rickybanister** [comment]
@MichaelArestad should we just close this issue for now—it appears you made an incremental improvement. How is the comparison of the token field now?

**Comment by MichaelArestad** [comment]
@rickybanister It's terrible. We shouldn't feel the need to close out issues that we still want to get to. That gives us a false sense of completion.

**Comment by MichaelArestad** [comment]
After the Deadline is no longer part of Jetpack (for now). Closing.
