### ISSUE TITLE
Settings: Writing / Post by Email layout

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack#4720]
The label should be `font-weight: 600;`
The label should have `margin-bottom: 5px;`
The input should match Calypso's border and focus styles
The input should be full width on its own line (I believe @MichaelArestad is already working to migrate the input styles from calypso)
A 'fieldset' should have a bottom margin of 20px

<img width="732" alt="screen shot 2016-08-10 at 12 49 51 pm" src="https://cloud.githubusercontent.com/assets/437258/17562464/045e0fbc-5ef9-11e6-9fa3-7b9a82f13013.png">

The (i) icon is in a bad place in all the settings cards that have a right-floating save button, but I'll address that in a separate issue.

cc @MichaelArestad

**Comment by MichaelArestad** [comment]
Yep. I think we also might try something like this https://wpcalypso.wordpress.com/devdocs/design/clipboard-button-input

as suggested by @eliorivero https://github.com/Automattic/dops-components/pull/42#issuecomment-238980182
