### ISSUE TITLE
Settings: Writing / VideoPress settings button inconsistency

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack#4721]
The 'SETTINGS' button for VideoPress is a compact button instead of a regular button and is floated left rather than right like all the submit buttons in Settings. 

Currently:
<img width="735" alt="screen shot 2016-08-10 at 12 54 31 pm" src="https://cloud.githubusercontent.com/assets/437258/17562682/e1e51c40-5ef9-11e6-98b0-285c1e55e243.png">

I wonder if that should instead be a link with an external icon, or at least be a non-compact button floated to the right?

What about:
<img width="730" alt="screen shot 2016-08-10 at 12 59 37 pm" src="https://cloud.githubusercontent.com/assets/437258/17562785/5963b010-5efa-11e6-8d22-f62b5ed34e83.png">

cc @MichaelArestad

**Comment by rickybanister** [comment]
This is also the case for Extra Sidebar Widgets

<img width="734" alt="screen shot 2016-08-10 at 1 15 26 pm" src="https://cloud.githubusercontent.com/assets/437258/17563264/8e5a5ef2-5efc-11e6-82f5-7b672dbd3542.png">

**Comment by MichaelArestad** [comment]
It originally was a link like that. We can actually fairly trivially switch it back and add a positioned Gridicon like your example, now. I thought it felt a bit abrupt and less refined than at least having a button. Say the word and I'll flip em back over to something like your mockup.

**Comment by rickybanister** [comment]
What does @jeffgolenski think?

**Comment by jeffgolenski** [comment]
@MichaelArestad Now that we've switched the "learn more" to the ? icon, I think the text with the external link feels more suitable. The settings button by itself looks a little strange to me (opinion). Overall I like the longer phrase of "edit your [something] settings."
