### ISSUE TITLE
Settings: Engagement / Comments improved layout

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack#4723]
I was confused by the current layout of the Comments settings. It was hard to tell that this would be user-facing. 

Currently:

<img width="741" alt="screen shot 2016-08-10 at 1 40 25 pm" src="https://cloud.githubusercontent.com/assets/437258/17564043/0443efb8-5f00-11e6-967b-a8bc50d2f9e9.png">

**I suggest we do a layout more like this:**

<img width="731" alt="screen shot 2016-08-10 at 1 38 30 pm" src="https://cloud.githubusercontent.com/assets/437258/17564029/f266aec0-5eff-11e6-90c7-d8c7b7de1df4.png">

And also consider adding a 'preview' like Related Posts so you can see your changes on a simulated front-end.

cc @MichaelArestad

**Comment by MichaelArestad** [comment]
I dig. Let's do it.
