### ISSUE TITLE
Add Support for Instant Browser Notifcations

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#4730]
Would love to see Jetpack support this feature:
https://en.blog.wordpress.com/2016/08/10/instant-browser-notifications/

**Comment by kraftbj** [comment]
Jetpack already supports it. If you enable WordPress.com IBNs, the notifications piped through the Notifications module normally would be pushed to you the same way.

Leaving this open to remind us to update the Notifications docs.

**Comment by kraftbj** [comment]
Added mentioned at http://jetpack.com/support/notifications/ that could be fleshed out further.
