### ISSUE TITLE
Photon: Add support for the .dev extension used with DesktopServer development

### ISSUE THREAD

**Issue by lschuyler** [Automattic/jetpack#4747]
DesktopServer adds a .dev extension when a site is developed locally.

When a live site is moved to DesktopServer, these .dev extensions break all Photon images.

Idea: Photon should recognize the .dev extension, and it should just work, either by ignoring the .dev extension so the Photon images can display, or using the presence of .dev as a trigger to engage Jetpack's development mode.

Complication: .dev is a valid gTLD now (or soon? May just be for Google's use)

Issue raised here: https://wordpress.org/support/topic/using-jetpack-with-a-dev-local-site

**Comment by kraftbj** [comment]
We already support JP Development Mode and, when enabled, skips Photon. But, we can validate URLs a bit better to at least prevent Photon from getting involved.

Could use the banned domain function or a similar one on the same filter https://github.com/Automattic/jetpack/blob/master/functions.photon.php#L259-L273

**Comment by jeherve** [comment]
> we can validate URLs a bit better to at least prevent Photon from getting involved.

@kraftbj Another thing we could do is see with DesktopServer if they have a constant we may take into account, and trigger staging? If that's not an option, maybe DesktopServer could just add the `JETPACK_DEV_DEBUG` constant?

**Comment by jeherve** [comment]
I just got in touch with the DesktopServer folks here:
https://twitter.com/jeherve/status/773825144003371008

@DesktopServer Would there be a way for your tool to add a constant to `wp-config.php` when a new offline site is generated or cloned from a live site? That constant would be used to inform Jetpack that the site is in fact not a live site.

If you already have your own constant, we can add it to Jetpack in a future release.

**Comment by GreggFranklin** [comment]
Currently in DesktopServer you can add the JETPACK_DEV_DEBUG to a Blueprint for a newly created site, but also we have a DesktopServer plugin called Clean Import that will add it to imported sites as well.

**Comment by jeherve** [comment]
> we have a DesktopServer plugin called Clean Import that will add it to imported sites as well.

@GreggFranklin I'm not really familiar with DesktopServer; does this apply to sites that are created by doing a backup of a live site?

Would you consider adding that constant by default to all local sites?

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by kraftbj** [comment]
Added on that they don't suggest .dev anymore ( https://docs.serverpress.com/article/232-how-to-change-top-level-domain-dev-extension-google-chrome-users ).
