### ISSUE TITLE
Update short description in content section to use .form-setting-explanation styles

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#4762]
I'm not sure how or where this info is coming from, though I hear @dereksmart might have some idea.

I want to change it from this:
![image](https://cloud.githubusercontent.com/assets/1123119/17626674/35bdbbaa-607c-11e6-9208-c284293b32c6.png)

To this:
![image](https://cloud.githubusercontent.com/assets/1123119/17626680/3cba1f16-607c-11e6-9f20-3b94fcbd404f.png)

**Comment by MichaelArestad** [comment]
Needs to have the `.jp-form-setting-explanation` class on those descriptions.

**Comment by eliorivero** [comment]
Maybe the class should also be added to the message shown in Sitemaps, Enhanced Distribution, Photon when site isn't publicly accessible. Example
https://github.com/Automattic/jetpack/blob/master/_inc/client/appearance/index.jsx#L39

**Comment by MichaelArestad** [comment]
@eliorivero Yep! Instead of the small/other stuff, can just use that class.

**Comment by dereksmart** [comment]
@eliorivero can you please add your suggestions that to this branch? #4854
