### ISSUE TITLE
Sitemaps: PHP errors for sitemap-xsl.php

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/jetpack#4763]
In lines 93 and 94  of jetpack/modules/sitemaps/sitemap-xsl.php the function wp_kses is called:
https://github.com/Automattic/jetpack/blob/8677a5852c88103a613776e75703d09f33f21bbf/modules/sitemaps/sitemap-xsl.php

According to the function reference for wp_kses, the first two parameters are required:
https://codex.wordpress.org/Function_Reference/wp_kses

We currently only pass an argument for $string , nothing for $allowed_html , and this leads to a PHP error.

cc: @ebinnion

**Comment by eliorivero** [comment]
Closing since this was fixed in https://github.com/Automattic/jetpack/pull/4362
The blog you're pointing to is from Jun 7 and this was [fixed in Jul 11](https://github.com/Automattic/jetpack/commit/1faf069dca4c0864c3beddded1a1db9e03f026e2).
