### ISSUE TITLE
Admin Page: How do I disconnect non-admin?

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#4764]
When I was looking to disconnect one of my test users today, I noticed that I couldn't find the disconnect option for my non-admin user (editor).

I expected there to be a connection settings section in the "General" tag like with my admin user, but there wasn't.

<img width="757" alt="screen shot 2016-08-12 at 10 28 36 am" src="https://cloud.githubusercontent.com/assets/1126811/17627661/a27d4a76-6077-11e6-9b03-43758989c432.png">

**Comment by dereksmart** [comment]
fixed in #4796 you will see a "Connection settings" card
