### ISSUE TITLE
Admin Page: Deactivate protect toggle shows for non-admins

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#4765]
When I view the admin page dashboard, I see the protect enable/disable toggle. And when I click it, I get this:

![screen shot 2016-08-12 at 10 31 09 am](https://cloud.githubusercontent.com/assets/1126811/17627812/28f64a44-6078-11e6-8f76-837d04a40cfa.png)

We're properly checking permissions in the API to make sure that non-admins can't deactivate the module, but we should probably update the UI so that non-admins don't even see the toggle.

**Comment by eliorivero** [comment]
Fixed in #4798
