### ISSUE TITLE
Jetpack Comments: add hooks to allow third-party plugin authors to insert elements into form

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#477]
The Jetpack comment form is hosted on WordPress.com, and added to any Jetpack site via an iFrame. When active, it replaces the standard comment form, and it also removes elements that may have been hooked into the standard comment form by other plugins.

It would be nice to make the Jetpack Comment Form more flexible, to continue to display anything that might have been hooked after the comment form via `comment_form_after_fields `, or to the comment form via `comment_form`.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/spam-user-registration-wp-spamshield-works-but-conflicts-with-jetpack-comments?replies=2&view=all#post-7044479

**Comment by jeherve** [comment]
Also requested here:
https://wordpress.org/support/topic/disable-default-comment-css?replies=1&view=all

**Comment by beaulebens** [comment]
Jetpack Comments is supposed to provide a "packaged", simple solution to allowing users to use their social accounts to leave a comment. It's not really intended to be a whole platform for commenting (in its current state), and I think the complexity of trying to allow for customization within the form (passing things to WordPress.com presenting them there, handling them, etc) is going to get well beyond the current scope of the feature. If people want to customize things this much, they're probably better off either building it into their theme, or exploring some of the other comment-centric plugins out there.

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/pictures-in-comments-1?replies=3&view=all

**Comment by richardmtl** [comment]
requested CSS in 2519778-t

**Comment by jeherve** [comment]
Requested CSS here:
https://wordpress.org/support/topic/style-post-comment-button?replies=1&view=all

**Comment by jeherve** [comment]
Also suggested here:
https://jetpack.com/2016/08/31/the-all-new-jetpack-lets-see-how-you-react/#comment-20453

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/add-bbcodetinymce-button-in-comment-form/

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/jetpack-not-compatible-with-comment-images/

**Comment by jeherve** [comment]
This was also suggested in #15510 (cc @nicosmaris).
