### ISSUE TITLE
Admin Page: layout of Protect for non admin users is broken

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#4774]
#### Steps to reproduce the issue
- log in as a editor user with no access to other stuff like Stats

#### What I expected
- layout to be ok

#### What happened instead
- layout is broken as shown below

<img width="741" alt="editor-no-access" src="https://cloud.githubusercontent.com/assets/1041600/17635073/e804c1b2-60ab-11e6-8092-6b0baef4d8e7.png">

**Comment by ebinnion** [comment]
Related: #4765
