### ISSUE TITLE
Carousel: do not enqueue scripts and styles on pages without a gallery

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4777]
#### Steps to reproduce the issue

0. Activate the Carousel module, and deactivate Infinite Scroll on a site.
1. Create a few posts that do not include a gallery.
2. Load your home page, and view source.
3. Carousel CSS and JS files are enqueued, although they aren't used on the page.

**Comment by rcoll** [comment]
@jeherve I can't repro this. Is there perhaps some other element?

**Comment by jeherve** [comment]
I actually can't reproduce either at the moment.  ¯\_(ツ)_/¯ 

Closing. Will reopen if needed.
