### ISSUE TITLE
Admin Page: add link to Settings in page header

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4821]
> It would be useful to have a link to the settings from the main React dashboard like there used to be in the previous version

![settings](https://cloud.githubusercontent.com/assets/426388/17703276/63fcc53a-63d1-11e6-8f22-e0461bcdf76d.png)

**Comment by jeffgolenski** [comment]
cc @MichaelArestad

**Comment by samhotchkiss** [comment]
Hey @jeherve -- there's been a lot of discussion about this, and for this release, we're going to keep the settings in the sidebar.

**Comment by jeherve** [comment]
Reopening, as this was brought up in #5147.

> There is no link in the header that show you the setting page. You have to go into the WordPress menu Bar to find that settings link and then click on to find the Jetpack modules that you want to edit.

cc @robertdall

**Comment by jeherve** [comment]
Also related, for more discussion about navigation items: #4482

**Comment by robertdall** [comment]
Where is the setting link that use to be on the top of the page. I clicked all three links that are their. One is the dashboard, but you call also call it at a glance? Lets call it one thing and stick to it ok? It can be "at a glance" or it can be "dashboard" but it can't be both.

There is no link in the header that show you the setting page. You have to go into the WordPress menu Bar to find that settings link and then click on to find the Jetpack modules that you want to edit.

Also Apps and Plans links start with large adds for WordPress apps and WordPress.com Advertisements and not related Jetpack Functionality.

So out of three links on the front page one has a confusing title that doesn't show all that jetpack is actually capable of and two are glorified adds for Automattic projects.

Disappointing to say the least.

**Comment by aisajib** [comment]
I believe that having a link to the settings page on the dashboard will make for a much smoother experience, especially for the new user. I say that because I just tested this as a new user and in my flow I was missing the link to the settings in the dashboard/main area of Jetpack's settings. I admit it's not super hard to discover that the settings page is there, but it feels limiting and some people might even miss that there's a settings page that can be visited from the link in the menu bar.

**Comment by MichaelArestad** [comment]
@samhotchkiss can we have a developer implement the settings in the header like @jeffgolenski showed above?

**Comment by MichaelArestad** [comment]
It looks like maybe ButtonGroup would be a good component to use here: https://wpcalypso.wordpress.com/devdocs/design/button-group

I'm not sure if it's in `dops-components` yet.

**Comment by jeffgolenski** [comment]
@samhotchkiss I second michael's thoughts. Let's build it.

**Comment by jeffgolenski** [comment]
Continuing the conversation over here, but there's been a bit of chatter over at: https://github.com/Automattic/jetpack/issues/5688

@samhotchkiss Can we get this built out for 4.4 or 4.4.1 as we mentioned above?

**Comment by eliorivero** [comment]
Fixed in #6407
