### ISSUE TITLE
Admin Page: disable save button when  changes have been saved

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4822]
Would it be possible to disable the Save button when changes have been saved?

For example:

As entering screen (disabled – no changes)

![on-enter](https://cloud.githubusercontent.com/assets/426388/17703903/887b5186-63d3-11e6-8c36-11a3fe824404.png)

After changes made (enabled)

![on-change](https://cloud.githubusercontent.com/assets/426388/17703915/90ad5480-63d3-11e6-844a-d4b4fb3ae6c2.png)

After changes saved – not sure why it’s still enabled – did my changes save?

![on-save](https://cloud.githubusercontent.com/assets/426388/17703930/9a85c6ea-63d3-11e6-9711-7af95d34d2dd.png)

**Comment by dereksmart** [comment]
This is outdated view, current master looks like this: 

![grav-hover](https://cloud.githubusercontent.com/assets/7129409/17711494/e568fc4a-63bf-11e6-96d5-c42051f05392.gif)
