### ISSUE TITLE
Photon: Possibly Remove ssl=1

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#4857]
Right now Photon adds the `ssl=1` to force pulling images with https, found in #3298. 

However many performance check tools suggest to remove query strings from static resources as this allows for better caching. Would it possible to have photon pull from https but not use the query string to better support caching?

**Comment by jeherve** [comment]
You can rest assured: the images are cached, the query string doesn't have an impact in this case.

In fact, that's how all Photon images are built: [query arguments](https://developer.wordpress.com/docs/photon/) are added to the original image URL to get a specific version of the image. That specific version of the image is cached on our end, though.

**Comment by danicotillas** [comment]
Hi, as you can see on this [WordPress thread](https://wordpress.org/support/topic/title-repeated/#post-8980178) it causes certain problems for the RSS.
Would there be anyway to remove that ssl=1 so i don´t have to deactivate Photon?
Thanks

**Comment by kraftbj** [comment]
@danicotillas Can you enable Photon so we can see the failure in place? The SSL one tells Photon to look for the image under https. Without it, it would check http, then https, taking longer and less performant. If we're doing something that is invalidating the feed, then that's something else we can fix.

**Comment by danicotillas** [comment]
Now it´s enable and you can see the error here: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.comunicacionabierta.net%2Ffeed%2F

As you can see in the link above maybe it has more to do with "RSS with images" plugin than with Jetpack. Let me know if I can do anything from my side.

**Comment by kraftbj** [comment]
Yup, it's that plugin. Let me grab the line and function they need to update.

**Comment by danicotillas** [comment]
All right, this is of interest of @endifmedia as well.

**Comment by kraftbj** [comment]
https://plugins.trac.wordpress.org/browser/rss-with-images/tags/1.3.6/feeds/mailchimp-feed-rss2.php#L96

On this line, it is directly outputting the URL of the image without escaping it for the XML content. While the ampersand is a valid URL character, it is a special character in XML and needs to be escaped.

Wrapping the `echo $image[0];` with `esc_url()` is good, both for security to ensure a well-crafted URL couldn't do something fishy, but will also convert `&` to `&#038;`, which will pass XML's spec.

**Comment by danicotillas** [comment]
I´m not very proficient at code so i wouldn´t know how to wrap that... could you specify me how should I write that line please?

**Comment by endifmedia** [comment]
i thought i moved that into a hook rather than using those old templates like the premium version. i'll double check and release a fix if not. thanks for finding this bug!

**Comment by kraftbj** [comment]
@endifmedia I didn't look close enough to confirm that code is still firing or not, just looking for filenames that looked interesting and that line would cause it. If that ends up not being it and would like me to take a closer look, happy to help!

**Comment by endifmedia** [comment]
New version released (1.4.0) with the change suggestions above.

**Comment by bhubbard** [comment]
@jeherve @kraftbj Can we revisit this idea? At least offer a filter to remove the ssl=1, many of the pagespeed tools continue to report it as an issue. I understand that its not really a big technical issue for performance, but giving developers the option to disable this to get better scores would be nice.

GT Metrix Example:
![gtmetrix](https://cloud.githubusercontent.com/assets/3837/26612288/b7b90714-4568-11e7-8f37-d9198c316755.png)

Pingdom Tools Example:
![pingdom-tools](https://cloud.githubusercontent.com/assets/3837/26612290/b97998fc-4568-11e7-89dd-8560983c9a6f.png)

**Comment by jeherve** [comment]
> many of the pagespeed tools continue to report it as an issue. I understand that its not really a big technical issue for performance

No worried there: this has zero impact on performance. The warnings displayed by those tools are not relevant anymore. You can learn more about this here:
https://github.com/Automattic/jetpack/issues/5618

**Comment by chaintng** [comment]
I have problem when enable photon on https wordpress site.

Wordpress tried to request to this 
https://i2.wp.com/www.witcastthailand.com/wp-content/uploads/2017/12/unnamed-2.jpg?resize=272%2C182&ssl=1

and it return `Sorry, the parameters you provided were not valid`

All of the below URL work fine
https://i2.wp.com/www.witcastthailand.com/wp-content/uploads/2017/12/unnamed-2.jpg?resize=272%2C182
https://www.witcastthailand.com/wp-content/uploads/2017/12/unnamed-2.jpg
http://www.witcastthailand.com/wp-content/uploads/2017/12/unnamed-2.jpg

Could you please check if there is any bug in jetpack?

**Comment by kraftbj** [comment]
I replied to @chaintng's comment, which was also posted in https://github.com/Automattic/jetpack/issues/9690
