### ISSUE TITLE
Stats: Adding <a> tags to Title breaks layout in stats

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/jetpack#4868]
#### Steps to reproduce the issue
1. Create a new post and wrap the title in <a> tags.
2. Publish the post and view it a few times so it shows up in the stats under Top Posts & Pages.
3. View the stats in wp-admin - under Top Posts & Pages the title is all the way over to the right.

![title](https://cloud.githubusercontent.com/assets/7946521/17767828/7b907da0-6529-11e6-9fb9-c125a401eb67.png)

**Comment by jeherve** [comment]
Closing this issues since the Stats screen was recently redesigned.
