### ISSUE TITLE
Undefined index notice and header warning

### ISSUE THREAD

**Issue by scarstocea** [Automattic/jetpack#4871]
#### Steps to reproduce the issue
Turn on DEBUG mode via wp-config.php on the affected website.
#### What I expected
No warnings/notices.
#### What happened instead
A notice and a warning related to Jetpack show up and prevent the wp-login.php form from being loaded while DEBUG mode is turned on.

```
Notice: Undefined index: in /home/jazbatco/public_html/wp-content/plugins/jetpack/class.jetpack-user-agent.php on line 97

Warning: Cannot modify header information - headers already sent by (output started at /home/jazbatco/public_html/wp-content/plugins/jetpack/class.jetpack-user-agent.php:97) in /home/jazbatco/public_html/wp-includes/pluggable.php on line 1174

```

These notices and warnings are showing up on the /wp-admin/ page with Jetpack active and all other plugins disabled. Jetpack version is 4.2.1, and WordPress version is 4.6.

They were suppressed by turning off WP_DEBUG in this case. If we release a patch for the notices, they can be tested (and triggered again) on https://jazbat.com/ owned by Rajeev Singh, a kind VaultPress and Jetpack client. 

Reference: https://www.olark.com/transcripts/show/ejgYH7adN1aJttLf3Y9pJ87nDJMgpZAo

**Comment by jeherve** [comment]
Fixed in #4616
