### ISSUE TITLE
Settings cards for Backups and Akismet show a blank space when plugins not installed

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#4885]
#### Steps to reproduce the issue

1. Deactivate akimset and/or Vaultpress plugins
2. Get to the Settings page under the **Security**
3. Expand Akismet or Backups card
4. See a blank card content

#### What I expected

It's expected that the cards for these modules in Admin Page's settings show a descriptive text instead of a blank space when the plugins are not active. 

#### What happened instead

A blank content shows in the cards when the plugins are not active

**Comment by eliorivero** [comment]
This also happens with Security Scanning.
We will need three short texts for Security Scanning, Akismet and Site Backups cards.
@jessefriedman can you write them? We had one for Backups in the previous Jetpack but you might want to revisit it:
> With a monthly subscription, the VaultPress plugin will backup your site’s content, themes, and plugins in real-time, as well as perform regular security scans for common threats and attacks.

**Comment by jessefriedman** [comment]
@eliorivero Here is the copy for the three cards:

**Security Scanning**
> Upgrade Jetpack and our state-of-the-art security scanner will hunt out malicious files and report them immediately so that you’re never unaware of what is happening on your website.

**Akismet**
> Let search engines and visitors know that you are serious about your websites integrity by upgrading Jetpack. Our anti-spam tools will eliminate comment spam, protect your SEO, and make it easier for visitors to stay in touch. 


**Site Backups**
> Real-time offsite backups with automated restores deliver peace-of-mind, so you can focus on writing great content and increasing traffic while we protect every aspect of your investment. Upgrade today.
