### ISSUE TITLE
Publicize: Twitter tags missing when Notifications disabled 

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/jetpack#4895]
#### Steps to reproduce the issue

Enable these modules only on a Jetpack-connected site:

Carrusel
Enhanced Distribution
Monitor
Protect
Publicize 
Spelling and Grammar

View a post on the site - there are no Twitter tags in the Open Graph Tags. 

Now enable the Notifications module and view the same post again - Twitter tags have returned.

**Comment by lezama** [comment]
Added the "Sync" label just in case 😛

**Comment by jeherve** [comment]
Looks like this may have been caused by #4281. 

Related: #4631 and #4866.

It might be good to review all options that now use `get_option_and_ensure_autoload`, to avoid this issue.

**Comment by jeherve** [comment]
Possibly related: [#2998465-org](https://wordpress.org/support/topic/portfolio-disappeared?replies=2#post-8784892) and the `jetpack_portfolio` option.

**Comment by kraftbj** [comment]
bisecting leads to 6bea5ac9c26ebfd56ed22eee5de72d676f7b16e4 . Previously, the Publicize module called `sync_posts_init` on the `init` hook, which fired the old `Jetpack_Sync::sync_posts` ( https://github.com/Automattic/jetpack/commit/6bea5ac9c26ebfd56ed22eee5de72d676f7b16e4#diff-bf42e6574fdf58459a9b48a27250b377L64 )

That function called `Jetpack::init()` so, basically, any module that expected to sync posts would have triggered `Jetpack::init()` at some point during the `init` hook, which we lost in that commit ( https://github.com/Automattic/jetpack/commit/6bea5ac9c26ebfd56ed22eee5de72d676f7b16e4#diff-c115b29ed4655d4706982c37969c266eL46 )
