### ISSUE TITLE
PHP Coding Standards: create ruleset.xml file for Jetpack

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4898]
While some of us probably have the [WordPress coding standards sniffs](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards) enabled by default in our code editors, this might not be the case for all contributors, and they might not want to enable those rules for all their projects.

To solve this issue, we could create a `ruleset.xml` file for Jetpack, that would be used by code editors to pull the WordPress coding standards sniffs when you open the Jetpack project in the editor. You can read more about custom ruleset files here:
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml

Brought up in #4894

**Comment by lkraav** [comment]
Thanks to this ticket, I just discovered https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#replacing-tabs-with-spaces

I think this might take care of one of the biggest logspam in one shot.

**Comment by jeherve** [comment]
This has now been fixed.
