### ISSUE TITLE
Publicize + Press This: Publishing directly from PT fails to Pub

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#4906]
#### Steps to reproduce the issue

1. Setup JP, Publicize, etc and publish a post via Press This

#### What I expected

Post to Publicize.

#### What happened instead

No joy.

**Comment by RCowles** [comment]
Reported in 2784711-t

**Comment by chaselivingston** [comment]
2787430-t

**Comment by chaselivingston** [comment]
2760207-t

**Comment by lamdayap** [comment]
2794479-t

**Comment by ebinnion** [comment]
Should be fixed in #4992.
