### ISSUE TITLE
Notifications block UI, don't auto-close

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#4921]
#### Steps to reproduce the issue

One of the first things I like to do after installing Jetpack is go in and enable a bunch of modules. In the old version this could either be done in bulk, or by a quick and easy bunch of "activate" clicks.

In this version I have to go from tab to tab searching for what I want, and activating pops up a bunch of notifications that don't autoclose. This means every time I activate a module I have to wait for it to be activated and then close the green pop-up, because otherwise the pop-ups quickly block the UI right over the top of the "activate" buttons.

<img width="1430" alt="notifications-block-ui" src="https://cloud.githubusercontent.com/assets/51896/17902008/65de2878-691a-11e6-866d-da100240483b.png">

It seems like it would be easier just to display some kind of success status within the module that I just activated, or even just to have the toggle move immediately and only display a message in a red pop-up if there was an error.

**Comment by dereksmart** [comment]
This could use some feedback by the Design/UX teams

@MichaelArestad @jeffgolenski @jessefriedman @richardmuscat

**Comment by MichaelArestad** [comment]
Do they ever auto close in Calypso? If so, how is it handled? Could we instead just replace the previous message instead of spawning a new one?

**Comment by dereksmart** [comment]
@MichaelArestad That's definitely a possibility!

**Comment by MichaelArestad** [comment]
Another possibility would be to fade the oldest out after a set amount of time (like macOS notifications), but that seems more complex maybe.

**Comment by jeffgolenski** [comment]
> Another possibility would be to fade the oldest out after a set amount of time (like macOS notifications), but that seems more complex maybe.

I just went to update some plugins on a non-auto update jetpack site of mine. The global notices there act a little differently than ours in a bad way. they cover each other and then the last one remains.

![plugin-notices-02](https://cloud.githubusercontent.com/assets/214813/17910825/94cf1f00-6958-11e6-9982-c4e2be42ce1d.gif)


I agree that we should fade them out after a certain time if they're good notices (success or just info), but maybe keep the error notices until users click / tap them away? Last thing I would want is for an important error message to disappear while I'm in the middle of reading about it!
