### ISSUE TITLE
Two feedback links that go to different places

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#4922]
#### Steps to reproduce the issue

1. Install a development version of jetpack
2. Visit jetpack settings page
3. Observe there are two "send us feedback" links close together which go to different places

<img width="770" alt="two-feedback-links" src="https://cloud.githubusercontent.com/assets/51896/17902371/f7b514a4-691b-11e6-9d3e-b4f253ab60bf.png">

I suggest we just have one Feedback link, and adjust where it takes the user depending on whether they are using a development or stable version.

**Comment by dereksmart** [comment]
True, I think if on a dev version both should link to the beta support form

**Comment by eliorivero** [comment]
@dereksmart maybe we can check if the Jetpack version has an `alpha` or `beta` in it and link it to the beta support forum.

**Comment by dereksmart** [comment]
@eliorivero yeah we already have `isDevVersion()` state selector available to us

**Comment by eliorivero** [comment]
On a second thought, maybe this is something that @jessefriedman or @richardmuscat should define. Maybe it's useful to growth purposes.

**Comment by richardmuscat** [comment]
The one in the notice is specific to beta feedback so maybe we should call it "Submit Beta feedback"
