### ISSUE TITLE
Paid plugins link label and URL changes several seconds after load

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#4925]
#### Steps to reproduce the issue

1. Load the Jetpack /security page
2. Scroll down to see paid plugins, e.g. Akismet
3. Note that button next to feature says "Set Up"
4. Wait a few seconds...
5. Button now says "Upgrade" (and links to a plans page, rather than setup page)

#### What I expected

Button either says Set Up or Upgrade, not one and then the other...

#### What happened instead

Button flipped states several seconds after loading

**Comment by dereksmart** [comment]
taken care of in #4959
