### ISSUE TITLE
Admin: Auto-dismiss global notices for activating/deactivating modules

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#4929]
Had a few reports/requests that the global notices for activating/deactivating modules and updating settings should be auto-dismissed after a little bit. 

Let's do that.  How long should we wait before auto-dismissing? 

![auto-dismiss](https://cloud.githubusercontent.com/assets/7129409/17904909/2fd23b1e-693f-11e6-955b-e2d483dc9b9c.png)

**Comment by gravityrail** [comment]
Not to sound like a broken record, but do we really need those notices at all?

**Comment by dereksmart** [comment]
Right! Where is my mind.  This is a duplicate of #4921
