### ISSUE TITLE
Admin: Activating/Deactivating many modules without clearing notices results in unusable interface.

### ISSUE THREAD

**Issue by rcoll** [Automattic/jetpack#4936]
This is not a major bug, but could definitely be tidied up a bit.

When activating and deactivating modules, if you do not proactively close the notice bubbles that appear, the entire right side of the page will fill with them until you cannot reach any settings that are under them. This just feels like a suboptimal UX.

It might be better to limit a max of X-number of bubbles, and programmatically close them as more appear. Perhaps they could even be closed on a timer.

#### Steps to reproduce the issue

1. Visit settings page
2. Attempt to activate/deactivate many modules

![screen shot 2016-08-23 at 4 09 04 pm](https://cloud.githubusercontent.com/assets/5528445/17908590/191f4d7a-694f-11e6-9c60-df12340d7d14.png)

**Comment by dereksmart** [comment]
Duplicate (Sorry @rcoll!) of #4921 -- let's keep the discussion going there
