### ISSUE TITLE
[youtube] oembed missing some markup leading to errors in Google's schema testing tool

### ISSUE THREAD

**Issue by rothschild86** [Automattic/jetpack#4939]
To replicate, go to https://search.google.com/structured-data/testing-tool/u/0/#url=http%3A%2F%2Frothschildportraiture.com and expand the Video Object in the right pane.

The way I see it, if the required fields are not provided, maybe it is better not to include the Video Object schema at all?...

Just a thought :)

**Comment by jeherve** [comment]
That markup isn't added by Jetpack. I suspect it's added by another one of your plugins, or by your theme.

**Comment by rothschild86** [comment]
hm... interesting... my bad, then.
