### ISSUE TITLE
AtD displays Clich&eacute;s instead of Clichés as title in the replace menu

### ISSUE THREAD

**Issue by azaozz** [Automattic/jetpack#494]
Caused by a hack in atd.code.js: https://github.com/Automattic/jetpack/blob/master/modules/after-the-deadline/atd.core.js#L230

As this string is used directly in JS, best would be to have the actual utf-8 char there, not HTML entity. Also, it should probably be translatable.

**Comment by eliorivero** [comment]
Closing as this was fixed in https://github.com/Automattic/jetpack/commit/2ba625dd2375ac336bd63837c5bb0d99833584b3#diff-290e6c7210ad4c18a672f4b4844313d4
