### ISSUE TITLE
Admin Page: toggles' design review

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4941]
> I noticed that when opening/closing the settings accordions, the animation is super jumpy (I know, animated height can be hard), and the margin between the open and next card is too small when opened.

![strange](https://cloud.githubusercontent.com/assets/426388/17928351/92b49342-69fa-11e6-9a05-52a410ea1a02.gif)

> After turning off the toggle, its a little confusing that there’s still a blue border:

![state](https://cloud.githubusercontent.com/assets/426388/17928367/a8325be6-69fa-11e6-96d4-07a214e71882.png)

> This is the toggles focus state, so once you click something else it goes away. Just looks strange to still see blue, when blue is so closely associated with “on” in this context.

**Comment by MichaelArestad** [comment]
Looking at fixing the margin. Might change the toggle in the future. For now, it works.

**Comment by jeherve** [comment]
Closing as this will be fixed in 4.6
