### ISSUE TITLE
Admin Page: contrast issues

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4942]
Some of the design elements can't be seen, and some of the text is sometimes hard to read:

![contrast](https://cloud.githubusercontent.com/assets/426388/17928619/e004a5c8-69fb-11e6-891b-b2d63c62a61d.png)
![contrast-2](https://cloud.githubusercontent.com/assets/426388/17928626/e1c150dc-69fb-11e6-8f88-d54c445c73ae.png)

**Comment by MichaelArestad** [comment]
Yep. It's a known issue with Calypso. I don't know if we'll have time to take care of them in this release since it will require a bit more work to make the changes (in both repos). :/
