### ISSUE TITLE
Admin Page: ? icon doesn't offer tooltip

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4943]
> At some point I clicked a little ? icon and ended up on https://vaultpress.com/jetpack — not to bad, but not really what I expected. 
> 
> I hovered over the ? icon, hoping to see a tooltip-like explanation (since that’s what Calypso has taught me to do) and nothing happened. Then I clicked it, and was taking to Jetpack.com in my existing browser tab. It little jarring, since I wasn’t aware it was going to take me out of my wp-admin.

**Comment by MichaelArestad** [comment]
We don't have tooltips quite yet, but we can look at adding them if we have time.

**Comment by jeffgolenski** [comment]
> Then I clicked it, and was taking to Jetpack.com in my existing browser tab. It little jarring, since I wasn’t aware it was going to take me out of my wp-admin.

Great point. Definitely don't want to take users away and have them get lost.

**Comment by jeherve** [comment]
Also suggested in 2935055-t

**Comment by dereksmart** [comment]
We've got tooltips now that work!

**Comment by MichaelArestad** [comment]
@dereksmart 💥
