### ISSUE TITLE
Admin Page: module description disappears when module is active.

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4944]
#### Steps to reproduce the issue

1. Go to Jetpack > Settings > Engagement
2. Scroll down to Enhanced Distribution.
3. Expand the card.

![screen shot 2016-08-24 at 13 11 24](https://cloud.githubusercontent.com/assets/426388/17928714/6048be68-69fc-11e6-8595-1b981ec50565.png)

4. Activate the module.
5. The explanation text disappears.

![screen shot 2016-08-24 at 13 12 29](https://cloud.githubusercontent.com/assets/426388/17928724/6d25d756-69fc-11e6-8838-ad23744d599b.png)

> I’m not sure what Enhanced Distribution means, so I clicked on the disclosure arrow to expand the card and got the above. It doesn’t really say anything.

**Comment by dereksmart** [comment]
I think this was by design @MichaelArestad @richardmuscat

**Comment by MichaelArestad** [comment]
On that one, we can keep the string, but I don't know how to fix. :/

**Comment by samhotchkiss** [comment]
Agreed that we like it like it is :)
