### ISSUE TITLE
Admin Page: horizontal scrollbar in Stats graph

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4945]
- Firefox Developer Edition 50.0a2 (2016-08-22)
- Go to Jetpack > Dashboard

https://videopress.com/v/KHzdnn2R

**Comment by MichaelArestad** [comment]
Looks like it's not a horizontal scrollbar, but a rendering issue. I wonder if it's showing the stats tooltip before the data is there? Testing.

**Comment by MichaelArestad** [comment]
Confirmed. It's a tooltip. Not sure why. Needs fixing.
![image](https://cloud.githubusercontent.com/assets/1123119/18017942/137f51ee-6ba2-11e6-8f69-7ca1f6283b34.png)

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/new-stats-well-stink/page/2/#post-8157236
