### ISSUE TITLE
Admin Page: flashing non-styled dashboard when loading the page

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4946]
#### Steps to reproduce the issue

1. Go to Jetpack > Dashboard

When loading the page, you'll see this for a second:

![styled](https://cloud.githubusercontent.com/assets/426388/17929307/e534b6ba-69ff-11e6-81af-9e2c53bd2369.png)

**Comment by ebinnion** [comment]
This is still an issue for me after updating to 4.3-rc1.

If I go to `$site/wp-admin/admin.php?page=jetpack#/dashboard` and then `cmd + shift + r`, I see unstyled content like the above.

**Comment by eliorivero** [comment]
I can't reproduce this by checking `master-stable` branch.

**Comment by ebinnion** [comment]
I can reproduce this pretty reliably with rc1, which I assume is `master-stable` as of this morning. 

The site is on Pressable and I'm using Macnchrome Version 52.0.2743.116 (64-bit) if that helps.
