### ISSUE TITLE
Multisite: Network admin does not accurately reflect the activation/connection state of sites

### ISSUE THREAD

**Issue by rcoll** [Automattic/jetpack#4956]
Possibly related: https://github.com/Automattic/jetpack/issues/4957

#### Steps to reproduce the issue

1. Fresh install WP and create a network and several sites
2. Install and network activate Jetpack-4.3-beta2
3. Connect Jetpack on several (or all) sites
4. Navigate to http://testsite.com/wp-admin/network/admin.php?page=jetpack

#### What I expected

Sites to appear active in the list.

#### What happened instead

Sites do not appear to be active/connected in the list.

![screen shot 2016-08-24 at 10 10 18 am](https://cloud.githubusercontent.com/assets/5528445/17933825/90742c3a-69e3-11e6-96f3-1c6b98e9f40c.png)

**Comment by kraftbj** [comment]
That's interesting. My production multisite isn't having that issue.

**Comment by rcoll** [comment]
@jeherve WP 4.6 and Jetpack 4.3-beta2.

After updating to beta3, this issue has resolved itself. Closing.
