### ISSUE TITLE
Multisite: "Protect cannot keep your site secure" message

### ISSUE THREAD

**Issue by rcoll** [Automattic/jetpack#4957]
Possibly related: https://github.com/Automattic/jetpack/issues/4956

#### Steps to reproduce the issue

1. Fresh install WP and create a network and several sites
2. Install and network activate Jetpack-4.3-beta2
3. Connect Jetpack and activate protect on all sites
4. Navigate to a site's dashboard and notice the Protect error message

![screen shot 2016-08-24 at 10 23 12 am](https://cloud.githubusercontent.com/assets/5528445/17934309/62509274-69e5-11e6-8e65-164daa0d67be.png)

After adding an error_log() call to check_login_ability() it appears that protect is actually working.

**Comment by jeherve** [comment]
It's almost as if Jetpack wasn't detected as network-activated, although it is, on your network. What other plugins do you run on that instance? Is there anything that could change the way plugins get activated / network activated?

**Comment by samhotchkiss** [comment]
@rcoll -- are you sure that jetpack was network activated, not just individually activated on each individual site?

**Comment by rcoll** [comment]
@jeherve - This was a brand new fresh default install of WP, with no other plugins or themes.

@samhotchkiss - I am certain, I triple checked on two separate networks.

Good news though, after updating to beta3 this issue has resolved itself. I'm going to go ahead and close this.
