### ISSUE TITLE
Admin Page: is_usable_domain error is not very clear

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4973]
In 4.2.2:

![inaccessible](https://cloud.githubusercontent.com/assets/426388/17968855/4b5dbd4a-6acf-11e6-91de-a5aa90ccc429.png)

> After updating to 4.3-beta3, the error is much less readable, it’s all in developer-speak. I was also hoping that there would be a link to developer mode instructions, since I always forget the constant name.

![react](https://cloud.githubusercontent.com/assets/426388/17968824/1cc501c8-6acf-11e6-9c41-1eabd45d1f42.png)

Related: #2534

**Comment by dereksmart** [comment]
stripslashes too

**Comment by dereksmart** [comment]
@jeherve I'm sort of confused at this.  There are two separate error messages there triggered by (maybe) different things.  The latter of the two messages is actually more descriptive than the first.  

Regardless, it can be cleaned up a bit.

**Comment by dereksmart** [comment]
This is what my error looks like 
![screen shot 2016-08-29 at 8 04 18 pm](https://cloud.githubusercontent.com/assets/7129409/18071450/d2a14fb8-6e23-11e6-86e4-90866557f5bb.png)

**Comment by dereksmart** [comment]
That said, the ugly error message in the PR screenshot is coming from a dotcom error message.  OG search for `The Jetpack server was unable to communi` string to find where.  We can fix that message there.  

In the meantime, I think what is shown in the PR screenshot is a very edgy case, and can/should be tackled in the next release.  (or if we can just make the change dotcom during beta.)

**Comment by jeherve** [comment]
Another report here:
https://twitter.com/pixolin/status/775348694963089408

**Comment by dereksmart** [comment]
@jeherve can you please reopen if this is still valid?
