### ISSUE TITLE
Admin Page / Apps: Android icon is a bit smaller than Apple

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#4985]
> We’re also a couple pixels off on the iOS and Android logos there. Each SVG is 32px tall. But the Android one has what looks like an extra 1 or 2 pixels of white space around it.

![svgs](https://cloud.githubusercontent.com/assets/426388/18001304/68356162-6b82-11e6-825b-1afe9ee0ecfd.png)

**Comment by jeffgolenski** [comment]
Fixed in: https://github.com/Automattic/jetpack/pull/5023
