### ISSUE TITLE
Admin Page / Omnisearch: missing submenu, missing card, extra settings Link

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5026]
It seems there are a few issues with Omnisearch in 4.3:
1. The only way to find the Omnisearch card, and activate / deactivate the module is to search for it. The card isn't available in any of the tabs.
2. There is no Omnisearch submenu in the Jetpack menu anymore. The only way to search using Omnisearch is to use the admin bar searchform.
3. The Omnisearch card includes a link to Omnisearch settings:

![screen shot 2016-08-30 at 12 40 29](https://cloud.githubusercontent.com/assets/426388/18086195/f72a6bc2-6eae-11e6-8bd1-ce04fdb1949d.png)

There are no such settings, though. Omnisearch doesn't include any configuration options.

Could we remove that configuration link, add an Omnisearch searchform to the card, and add the card to one of the tabs (General maybe?)?

**Comment by macmanx2** [comment]
This is still an issue under Jetpack 4.3.1, so considering that #3645 exists, it would be nice to get some confirmation/backstory on the decision.

**Comment by samhotchkiss** [comment]
This is intentional, as Omnisearch is being phased out
