### ISSUE TITLE
Error 32601 when trying to connect a social network in Publicize

### ISSUE THREAD

**Issue by kabo** [Automattic/jetpack#504]
I'm running WP 3.9 Multisite using nginx and php-fpm. Whenever I try to connect a social network (facebook, twitter, g+, etc) under socialize I get error 32601.

I did a dump of the post that was sent to xmlrpc.php and made a manual post to see the reply and the reply my server was sending back to the jetpack-server was:

`````` xml
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
  <fault>
    <value>
      <struct>
        <member>
          <name>faultCode</name>
          <value><int>-32601</int></value>
        </member>
        <member>
          <name>faultString</name>
          <value><string>server error. requested method jetpack.verifyAction does not exist.</string></value>
        </member>
      </struct>
    </value>
  </fault>
</methodResponse>```

I tried deactivating the Jetpack plugin and then activate it again but that didn't help. I'd love to help out figuring out what's wrong. What should I try next?
``````

**Comment by seedprod** [comment]
Whats the solution to this? Having the same error.

**Comment by jeherve** [comment]
@seedprod Could you use the contact form @kraftbj linked to earlier to send us more details about your site?
