### ISSUE TITLE
Admin: Search icon sits above global notification

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#5042]
The user has to be on a particular position on the page, but I noticed that the search icon is visible above the global notifications. 

<img width="401" alt="screen shot 2016-08-31 at 11 00 18 am" src="https://cloud.githubusercontent.com/assets/214813/18133830/1e4f4b94-6f6a-11e6-82cb-ae64a0853f23.png">

cc @MichaelArestad

**Comment by eliorivero** [comment]
This is fixed by this PR in dops-components 
https://github.com/Automattic/dops-components/pull/56

**Comment by eliorivero** [comment]
For changelog:
Admin: search icon no longer overlaps the global notices.
