### ISSUE TITLE
Admin Page: Do not show arrow for modules without configuration options

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5047]
Currently there are several modules that do not have any configuration options available once the card has been toggled. A few of these are `Contact Form`, `Shortcode Embeds`, `WP.me Shortlinks`.

![screen shot 2016-08-31 at 1 32 22 pm](https://cloud.githubusercontent.com/assets/1126811/18141608/c7a455d0-6f7f-11e6-82cd-43531967150c.png)

For modules that don't have configuration options, would it make sense to just use a card instead of a foldable card? Then, within the card, we could just show the module name, a short description, and the toggle.

![screen shot 2016-08-31 at 1 35 40 pm](https://cloud.githubusercontent.com/assets/1126811/18141657/fda707ea-6f7f-11e6-9c7a-a70d86f56558.png)

**Comment by jeherve** [comment]
We would miss the support doc link though, so we'd probably have to find a way to always display the ? icon in these cases.

**Comment by MichaelArestad** [comment]
Moving to 4.3.2 milestone for now.

**Comment by jeherve** [comment]
#5461

**Comment by dereksmart** [comment]
This has been fixed along with the new settings design.
