### ISSUE TITLE
Admin Page: Link to automattic.com in footer is http

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5048]
I realize this is low priority, but I figured that we should still make a not of it.

The "An Automattic Airline" link that is displayed in the footer is non-https.

![screen shot 2016-08-31 at 1 40 55 pm](https://cloud.githubusercontent.com/assets/1126811/18141895/e1500924-6f80-11e6-9cc4-ac2240ba800f.png)

**Comment by eliorivero** [comment]
Nice catch. Also in Privacy link at the bottom.
