### ISSUE TITLE
Admin Page: Should we warn users that there are unsaved settings changes?

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5051]
If I change a module's configuration options and then reload the page, I am not shown a nag to remind me to save settings. We do this in Calypso in the `/me` section. 

![screen shot 2016-08-31 at 2 24 31 pm](https://cloud.githubusercontent.com/assets/1126811/18143201/a9cc621c-6f86-11e6-86d5-ae76d2ec5307.png)

Should we do this in Jetpack?

**Comment by jeherve** [comment]
This should have been fixed in #5032. Are you running the latest version of `master-stable`?

**Comment by dereksmart** [comment]
@jeherve it's possible that it doesn't take browser navigation into account, only route changes.  @ebinnion you should be seeing a confirm if you try and navigate to another tab in the app. 

cc @oskosk is there something we can do for browser navigation as well?

**Comment by ebinnion** [comment]
@jeherve I updated with the beta plugin and am on `rc1`.

@dereksmart I can confirm that I get the prompt if I change a setting and then click another tab within the Jetpack app. But, if I refresh the page or click the main `Comment` admin link for example, I don't see the prompt.

**Comment by dereksmart** [comment]
We will get this fix into the first point release

**Comment by oskosk** [comment]
I've pushed this #5085 which adds a new and different confirm box for confirming if unsaved settings are present when

* Refreshing the page
* Closing the browser tab/window
* Navigating away Jetpack Admin Page.

The messages when doing any of these actions will differ from the message when switching a route handled by `react-router`  as [custom messages for the `beforeunload` event are no longer supported](https://developers.google.com/web/updates/2016/04/chrome-51-deprecations?hl=en#remove-custom-messages-in-onbeforeload-dialogs)
