### ISSUE TITLE
Publicize: Wrong Configure URL

### ISSUE THREAD

**Issue by KienTrong** [Automattic/jetpack#5060]
#### Steps to reproduce the issue

WP Setup: WordPress in a folder of cPanel account.

![image 2016-09-01 at 11 06 06 pm](https://cloud.githubusercontent.com/assets/426388/18202601/6a398ff8-7111-11e6-84a1-6e0043040c34.png)

**Comment by samhotchkiss** [comment]
@KienTrong Thanks for the report and for helping us test!

We'll get a fix in for the right away 👍
