### ISSUE TITLE
RSS Widget: load images via SVG or Genericons

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5074]
In #4995, we removed all images used in the RSS widget, causing issues with that widget:

<img width="302" alt="screen shot 2016-09-02 at 9 59 17 am" src="https://cloud.githubusercontent.com/assets/426388/18211913/9297ba54-7140-11e6-9650-1e213722da58.png">

If we don't want to keep the images, maybe we should edit the CSS to use genericons instead?

cc @jeffgolenski

**Comment by jeffgolenski** [comment]
Gah - I did a search and scoured the plugin and it said the rss images weren't being used. I'll get the back, pronto @jeherve

**Comment by jeffgolenski** [comment]
For now let's get them back in as-is, but we should consider svgs or something for a future release. @MichaelArestad

**Comment by jeffgolenski** [comment]
Fixed in: https://github.com/Automattic/jetpack/pull/5075

**Comment by jeherve** [comment]
@jeffgolenski Thanks! I'll reopen this issue and add it to 4.4, so we can revisit the way the icons are loaded.

**Comment by lancewillett** [comment]
I think if we need an enhancement open it as another ticket... (I personally think it's fine as they are now, and works this way still on WP.com side).
