### ISSUE TITLE
ULB argument broken in Photon

### ISSUE THREAD

**Issue by annezazuu** [Automattic/jetpack#5078]
User in 2814845-t brought up that our ULB option isn't working anymore with photon. You can see this in our example image here:

http://i0.wp.com/developer.files.wordpress.com/2012/11/black-letterboxing-example.jpg?ulb=true

Here's the page:

https://developer.wordpress.com/docs/photon/api/#ulb

I'm not sure what's causing this to not work but posting here as a next step.

**Comment by jeherve** [comment]
Nice catch! Moved to [#64-code](https://code.trac.wordpress.org/ticket/64), where Photon's code lives.

**Comment by jeherve** [comment]
The bug was fixed in [r413-code](https://code.trac.wordpress.org/changeset/413).
