### ISSUE TITLE
Prevent redirect by Jetpack::activate_default_modules() in Jetpack_Network::do_subsiteregister()

### ISSUE THREAD

**Issue by ocean90** [Automattic/jetpack#5081]
#### Steps to reproduce the issue

For a WP-CLI command have code like this:

```
function connect_new_site( $blog_id ) {
    $network = Jetpack_Network::init();
    $current_user_id = get_current_user_id();
    $user_id = 999999;
    wp_set_current_user( $user_id );
    $result = $network->do_subsiteregister( $blog_id );
    wp_set_current_user( $current_user_id );
}
```
#### What I expected

No URL redirect.
#### What happened instead

Using WP-CLI I get this output:

```
Warning: Some code is trying to do a URL redirect. Backtrace:
#0  WP_CLI\Utils\wp_redirect_handler(https://de.wordpress.org/team/wp-admin/admin.php?page=jetpack)
#1  call_user_func_array(WP_CLI\Utils\wp_redirect_handler, Array ([0] => https://de.wordpress.org/team/wp-admin/admin.php?page=jetpack)) called at [/wp-includes/plugin.php:237]
#2  apply_filters(wp_redirect, https://de.wordpress.org/team/wp-admin/admin.php?page=jetpack, 302) called at [/wp-includes/pluggable.php:1158]
#3  wp_redirect(https://de.wordpress.org/team/wp-admin/admin.php?page=jetpack, 302) called at [/wp-includes/pluggable.php:1264]
#4  wp_safe_redirect(https://de.wordpress.org/team/wp-admin/admin.php?page=jetpack) called at [/wp-content/plugins/jetpack/class.jetpack.php:2379]
#5  Jetpack::activate_default_modules() called at [/wp-content/plugins/jetpack/class.jetpack-network.php:529]
#6  Jetpack_Network->do_subsiteregister(451) called at [/wp-content/mu-plugins/rosetta-network/jetpack-settings.php:49]
#7  WordPressdotorg\Rosetta\Jetpack_Settings\connect_new_site(451)
#8  call_user_func_array(WordPressdotorg\Rosetta\Jetpack_Settings\connect_new_site, Array ([0] => 451)) called at [/wp-includes/plugin.php:602]
// …
```

`Jetpack::activate_default_modules()` has a `$redirect` argument which should be set to `false` IMO.

**Comment by nickdaugherty** [comment]
There is actually a bigger issue here, not specific to just the mentioned `Jetpack_Network::do_subsiteregister()`.

A redirection can be attempted via `Jetpack::activate_default_modules()` on `init` of all requests regardless of type. This means that when new JP default modules are added, the first request will get redirected. This happens on all requests via `Jetpack::activate_new_modules()`, which is hooked on `init`.

https://github.com/Automattic/jetpack/blob/706cdfdd1b2f3133305c7fc326928d5b5c6cbe64/class.jetpack.php#L403

This means all requests - frontend, backend, WP CLI, REST API, etc, will be redirected when new default modules are first activated.

**Comment by GaryJones** [comment]
As an example of the problem this can cause, a client with a Node app that serves GraphQL derived from a response from a WP site's REST API, had the following error:

```
Error: GraphQL error: invalid json response body at https://example.com/wp-login.php?redirect_to=https%3A%2F%2Fexample.com%2Fwp-admin%2Fadmin.php%3Fpage%3Djetpack&reauth=1 reason: Unexpected token < in JSON at position 0
```

This unexpected redirection when calling the REST API means that their GraphQL data was broken, albeit temporarily.

**Comment by nickdaugherty** [comment]
Upgraded VIP Go to 7.6 today and all sites experienced this redirection when new default modules were activated.

It's not highly visible (just first request), but _is_ highly suboptimal since even frontend requests (regular visitors) can get sent to the JP Dashboard, which usually means they end up on a WP login page when visiting random frontend pages.

Is there anything we can do to get this onto a shortlist? cc @jeherve

**Comment by nickdaugherty** [comment]
Also cc @gravityrail for visibility.

**Comment by jeherve** [comment]
Would it be enough to force no redirect for `activate_default_modules` in some conditions? Something like this?

```diff
diff --git a/class.jetpack.php b/class.jetpack.php
index 346b85c6e..1042597c6 100644
--- a/class.jetpack.php
+++ b/class.jetpack.php
@@ -2800,6 +2800,18 @@ class Jetpack {
 			}
 		}
 
+		// Only redirect when in wp-admin.
+		if (
+			! is_admin()
+			|| ( defined( 'REST_REQUEST' ) && REST_REQUEST )
+			|| ( defined( 'XMLRPC_REQUEST' ) && XMLRPC_REQUEST )
+			|| ( defined( 'WP_CLI' ) && WP_CLI )
+			|| ( defined( 'DOING_CRON' ) && DOING_CRON )
+			|| ( defined( 'DOING_AJAX' ) && DOING_AJAX )
+		) {
+			$redirect = false;
+		}
+
 		if ( $deactivated && $redirect ) {
 			Jetpack::state( 'deactivated_plugins', join( ',', $deactivated ) );
 
```
