### ISSUE TITLE
Stats Chart tooltip/popover: Match Calypso styles and data

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#5084]
I would like to update what we show to match Calypso. I believe the styles are mostly in place. It should just be a matter of populating the data in the appropriate format.

What we should be showing:
![image](https://cloud.githubusercontent.com/assets/1123119/18255625/61c7334c-7379-11e6-87d8-1353539942c1.png)

What we are showing:
![image](https://cloud.githubusercontent.com/assets/1123119/18255632/7346c9c0-7379-11e6-877c-dce8c0edcfa8.png)

**Comment by eeeeevon13** [comment]
This issue appears to be out of date, the css has changed since this was put in
