### ISSUE TITLE
Facebook and Open Graph

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#5087]
It looks like Facebook's Open Graph API v2.0 is no longer available.

![image](https://cloud.githubusercontent.com/assets/1123119/18257015/33322f2a-738b-11e6-87d4-ec3b019aee2a.png)

After chatting with @stephdau a bit, it seems our content used to be a bit more integrated when showing up in Facebook. It used to show more than one image for galleries, etc. I think we should do our best to make experiences with our content as good as they were.

Facebook seems to really be pushing Facebook Stories. ([link](https://developers.facebook.com/docs/sharing/opengraph))

> Let people share stories about your app on Facebook through a structured, strongly typed API.

[Facebook's Open Graph Reference](https://developers.facebook.com/docs/reference/opengraph/)

I don't know if that's the way to go or how much work is involved here, but I wanted to make sure we didn't lose sight of this.

**Comment by jeherve** [comment]
> It looks like Facebook's Open Graph API v2.0 is no longer available.

We use v2.2 for Publicize, so we should be okay [for a little longer](https://developers.facebook.com/docs/apps/changelog#versions).

> Facebook seems to really be pushing Facebook Stories.

That's what Publicize uses, when that's available (i.e. when publicizing to a Facebook Profile). 

> It used to show more than one image for galleries, etc. 

That still works.

Gallery posts, for example, will be publicized and upload each image on Facebook, thus creating a Facebook Gallery Here is how it looks:

![screen shot 2016-09-06 at 10 47 19](https://cloud.githubusercontent.com/assets/426388/18267443/69db4bda-741f-11e6-8e29-4a5315c4546b.png)

Clicking on a single image opens Facebook's Carousel view, and a link to the post is added in the description of each image:

![screen shot 2016-09-06 at 10 48 27](https://cloud.githubusercontent.com/assets/426388/18267475/870ddc22-741f-11e6-8093-67389ba4d050.png)

Posts we consider as "Image Posts" will upload a single image, like so:

![screen shot 2016-09-06 at 10 49 24](https://cloud.githubusercontent.com/assets/426388/18267507/a68db194-741f-11e6-9235-774692b02798.png)

> I don't know if that's the way to go or how much work is involved here, but I wanted to make sure we didn't lose sight of this.

Facebook API updates are tracked by the IO Team in https://github.com/Automattic/io/issues/330 

Related issue: #565
