### ISSUE TITLE
Fatal Error upon updating to Jetpack 4.3

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5091]
```
Fatal error: Cannot find a library with slug admin-pages/class.jetpack-landing-page. in /home/SITENAME/public_html/wp-content/plugins/jetpack/require-lib.php on line 35
```

Reported here:
- https://wordpress.org/support/topic/latest-update-breaks-jetpack/
- https://wordpress.org/support/topic/fatal-error-cannot-find-a-library/

**Comment by jeherve** [comment]
Maybe we should add the file back, but empty, to avoid such errors?

**Comment by eliorivero** [comment]
It looks like the file `class.jetpack-admin.php` wasn't updated for some reason when users download the plugin to their installations, but the file is properly updated in the repo, and after downloading it and checking it I found that it's also ok.

**Comment by jeherve** [comment]
Updating `class.jetpack-admin.php` manually didn't help, unfortunately.

To see if this could be related to #3699, we tried deactivating all modules, and then updating. That didn't help either. :(

**Comment by jeherve** [comment]
Related: #5097
