### ISSUE TITLE
Admin Page: Post By Email Card is not expanding and errors when attempting to do it.

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#5094]
Currently, an error which is fixed by Automattic/dops-components#58 makes it impossible to see the **Post By Email** module settings. 

#### Steps to reproduce the issue

1. Get to the **Writing** Tab
1. Try to unfold the **Post By Email** module Card

#### What I expected

1. To see the **Post By Email** module settings

#### What happened instead

1. UI crashed with a Javascript Error

**Comment by kraftbj** [comment]
@oskosk What's the JS error? Would be helpful to have it so we can easily cross-reference with this ticket any support requests coming in.

**Comment by dereksmart** [comment]
@kraftbj the error that would be shown in production is a beautifully vague 

> admin.js?ver=4.3:1Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.

**Comment by oskosk** [comment]
@kraftbj the users will be seeing `admin.js?ver=4.3:1 Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.` only if the dev console is open when trying to Enable **PBE**. 

Otherwise the symptom is that the card does not expand and navigation between tabs may break after that.
