### ISSUE TITLE
Don't use `jetpack_require_lib()` when `require_once()` is better.

### ISSUE THREAD

**Issue by georgestephanis** [Automattic/jetpack#5097]
We currently have a lot of places in the codebase where we're using `jetpack_require_lib()` to include files in  the `_inc/lib/` directory.

This isn't the best idea in the world, for primarily performance reasons: [`jetpack_require_lib()`](https://github.com/Automattic/jetpack/blob/master/require-lib.php) does a lot more than a simple `require_once()` call would.  It fires off a filter, defines arrays to iterate through checking, etc.  Ditching it in many places in favor of `require_once()` would save some CPU cycles.

So why do we even use `jetpack_require_lib()`?  It's a compat file from WordPress.com that simplifies locating files which are in a common lib directory, but the lib directory is different places in WPCOM and Jetpack.  In these cases, it's totally worth keeping.  That's what it's there for.

However, when we're including Jetpack-specific admin page templates (for example) that will never be synced to WordPress.com, we should be using the far simpler (and easier for IDEs and busy developers to parse when skimming) `require_once()` command.

**Comment by anomiex** [comment]
FYI, we're now looking at deprecating and removing `jetpack_require_lib()` entirely due to changes we're working on related to how Jetpack's code is shipped to WordPress.com.

Internal reference: p9dueE-5EZ-p2

**Comment by jeherve** [comment]
Closing now since #28866 was merged.

**Comment by mehdi-nexstar** [comment]
The alternative way of using libraries :  
`require_once JETPACK__PLUGIN_DIR . '_inc/lib/LIB_NAME';`
