### ISSUE TITLE
JSON API: build interface allowing you to whitelist CPTs for the wpcom REST API

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5102]
One can use the `rest_api_allowed_post_types` filter to whitelist a specific CPT, and thus manage it from WordPress.com:
https://developer.jetpack.com/hooks/rest_api_allowed_post_types/

However, to be able to use that feature, you need to find the code snippet, and add to your theme's functions.php file or in a functionality plugin. What if we had an interface, in wp-admin, allowing you to whitelist any of the CPTs currently active on your site? It would help people discover another aspect of Calypso.

@rickybanister suggested adding this interface to Settings > Writing, when there are active CPTs.

Related Discussion: p6TEKc-Ey-p2

**Comment by beaulebens** [comment]
This feels like it belongs somewhere along with the existing "Custom Content Types" UI, which looks like this right now:

<img width="806" alt="screen shot 2016-10-05 at 3 42 34 pm" src="https://cloud.githubusercontent.com/assets/108942/19132764/629b8cf4-8b12-11e6-94bf-6a08c9515f3b.png">

We could just list out the locally-registered custom post types (and taxonomies?) and allow the user to check a box next to them (or a toggle, or whatever) to whitelist them.

Love this idea.

**Comment by zinigor** [comment]
Since we're refactoring the Settings UI, can we move it to 4.6 where the rest of the Settings API belongs?

**Comment by jeherve** [comment]
cc @aduth @lezama @mtias who worked on #5487

**Comment by mtias** [comment]
I think the setting change would be in addition to the other change, right? It seems we can improve the experience in some ways without having to add an option for CPT to appear.

**Comment by samhotchkiss** [comment]
This would be cool for 4.6 with the settings UI

**Comment by jeherve** [comment]
Fixed in #5487
