### ISSUE TITLE
Sharing: add filter to customize number format for sharing counts

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5107]
Right now, sharing counts can have 3 different formats:
1. If less than 1,000, we just return the number as is.
2. If between 1,000 and 10,000, we return `xK+`.
3. If more than 10,000, we return `10K+`

It would be nice if this could be customized for each site, and maybe per language.

Suggested here:
https://wordpress.org/support/topic/facebook-share-count-format/

**Comment by eduardozulian** [comment]
We had a request on 2989339-t.

The user was wondering why their post has more than 19k likes, shares, and comments and we only display `10k+`.

As a reference, they used https://www.sharedcount.com/ to check their stats.

**Comment by spsiddarthan** [comment]
Facebook has removed support for sharing count with non-official buttons, and we can't customize the values returned in the official buttons, since Facebook wholly controls that. 

Closing this issue.
