### ISSUE TITLE
Sync: delete all options when deleting the plugin

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5115]
It would be nice to delete all sync options when the plugin is deleted, thanks to the `uninstall.php` file.

**Comment by gravityrail** [comment]
I believe we already do that.

https://github.com/Automattic/jetpack/blob/master/sync/class.jetpack-sync-sender.php#L344

**Comment by gravityrail** [comment]
Found a couple of things we don't delete ^^
