### ISSUE TITLE
Admin Page: Link legacy browser notification to BrowseHappy

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5127]
While testing 4.3.1 earlier today, I noticed the following notice when browsing with IE10.

<img width="1131" alt="screen shot 2016-09-07 at 2 01 51 pm" src="https://cloud.githubusercontent.com/assets/1126811/18328109/0be22e96-7513-11e6-8871-aa2d1fee6436.png">

Should we link to [BrowseHappy](http://browsehappy.com/) in the notice?

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
