### ISSUE TITLE
Admin Page: Fix header layout for legacy browsers

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5128]
While testing 4.3.1 earlier today, I noticed that the Jetpack header styles were off. Specifically, the Jetpack logo and the links are all centered instead of Jetpack being on the left and the links on the right.

<img width="1131" alt="screen shot 2016-09-07 at 2 01 51 pm" src="https://cloud.githubusercontent.com/assets/1126811/18328109/0be22e96-7513-11e6-8871-aa2d1fee6436.png">

I know that it's not priority, but hopefully it's not a hard fix and would look nicer for our IE users.

**Comment by dereksmart** [comment]
this has been fixed along with the new design https://cloudup.com/cbl1AWwBcrk
