### ISSUE TITLE
Admin Page: Stats tooltip positioning is off for RTL

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5129]
When the site is using an RTL language, hovering over a stat column positions the detail tooltip in a weird spot.

![screen shot 2016-09-07 at 2 20 26 pm](https://cloud.githubusercontent.com/assets/1126811/18328435/6c98cf00-7514-11e6-8876-5e79f48e4114.png)

https://cloudup.com/cPyaD26E2Vd

**Comment by jeherve** [comment]
Related: #5360

**Comment by samhotchkiss** [comment]
This isn't an issue in 4.5, it was fixed at some point...
