### ISSUE TITLE
Admin Page: Toggling expandable card can create navigation confirmation in IE11

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5130]
In IE11, if I got to the `Settings > Security` tab and then toggle the `Protect` card, then navigate to say `Appearance`, I am shown the "You have unsaved changes, are you sure you want to..." confirmation.

I would expect to only see that if I have made changes.

Of note, I do not get the confirmation in Chrome.

@oskosk mentioned that it could be because IE fires `onChange` when the placeholder is set.

**Comment by jeherve** [comment]
Closing as this will become irrelevant in 4.6.
