### ISSUE TITLE
Re add Icons to list of Moduals

### ISSUE THREAD

**Issue by robertdall** [Automattic/jetpack#5134]
In the latest UI update Jetpack decided to remove the icons from the list of moduals available. 

This is a really bad idea in terms of a UI standpoint. 

The Icons along with text have long become a standard both in the WordPress world and Web Design in general and you have decided to remove them for reasons of who knows. It was just a bad implementation and a step back to the previous UI which had both.

Now if we look at WordPress core for example which has a better user experience. The menu with out the icons or with the icons? 

<img width="296" alt="screen shot 2016-09-07 at 4 08 36 pm" src="https://cloud.githubusercontent.com/assets/1909677/18331709/dd6e7828-7515-11e6-87d8-c150afa2ada0.png">

It's both a better system and faster because people who recognize options via visual icon reference and people who reference through text are both served.

**Comment by MichaelArestad** [comment]
Hi @robertdall! I was working on the design team that worked on the latest update to Jetpack. I'm sorry this is causing you confusion as is. I'm actually working on seeing what I can do to iterate further on the way settings are interacted with for the next major release. I'm not sure we'll need the icons after this update, but will definitely do some mockups with them in mind. If we end up having a large module list as we have had in the past, we'll probably resurrect the icons.

**Comment by robertdall** [comment]
Michael can you please teach me why if we have a large module list why we don't need icons? 

Even looking at [https://make.wordpress.org/](https://make.wordpress.org/) even all of their headlines have logos associated with them. 

I am sincerely try to understand the rational behind drop the icons.

**Comment by MichaelArestad** [comment]
> I am sincerely try to understand the rational behind drop the icons.

We didn't initially start with a large list during this redesign. We were pulling them in line with Calypso's styles and components so we implemented a minimum viable product. Now that we have that in place, we can iterate and work on making things much better.

I also would like to point out that icons are often slower for people to read than faster upon the first several impressions. Considering a modules list (or settings) aren't visited often by the majority of our users, they weren't essential for the first build since they take longer to initially recognize and associate with an idea or location.

**Comment by robertdall** [comment]
> since they take longer to initially recognize and associate with an idea or location. 

Your statement would make sense if they weren't already originally associated with modules, but ( and correct me if I am wrong )  hasn't their always been iconography associated with each Jetpack modules.

**Comment by MichaelArestad** [comment]
> Your statement would make sense if they weren't already originally associated with modules,

That's true, but one of our goals for the upcoming iteration was to move away from a module focus and while this initial release didn't quite make the leap, the next one just might. And again, we completely rebuilt the UI to match another sister project and I can tell you there was much to keep track of. Fear not, we're working on iterating and improving on the interface.

> but ( and correct me if I am wrong ) hasn't their always been iconography associated with each Jetpack modules.

You know, I'm not sure. I definitely added some a few versions ago, but there might have already been icons in place before that (three years ago). That work predates my work on the project. I can say that even when I started work on it we had enough icons that there were repeats and enough modules that icons weren't particularly easy to memorize.

**Comment by robertdall** [comment]
> That's true, but one of our goals for the upcoming iteration was to move away from a module focus

But this at the core of my issue with Jetpack. There is a always going to be modules that are needs for some builds and not other. While bundling might help some people others will be asking. Why do I get this and this when all I want is this. 

Bundling has a lot of draw backs as well.

**Comment by jeherve** [comment]
#5461

**Comment by dereksmart** [comment]
As @MichaelArestad said, we are moving away from this type of thinking and made the decision that we will not be adding icons back to the UI.
