### ISSUE TITLE
4.3 locked me out of dashboard

### ISSUE THREAD

**Issue by janbtucker** [Automattic/jetpack#5135]

**Comment by janbtucker** [comment]
my blog is www.janbtucker.com/blog  I can't log in since updating Jetpack

**Comment by jeherve** [comment]
I'm sorry to hear you've run into issues. 

Could you try to follow the instructions [here](https://jetpack.com/support/getting-started-with-jetpack/known-issues/updating-to-jetpack-4-3/) to solve the problem?

If that doesn't help, you can contact us via [this contact form](http://jetpack.com/contact-support/).

Thanks!
