### ISSUE TITLE
Review $wp_filter usage

### ISSUE THREAD

**Issue by pento** [Automattic/jetpack#5137]
WordPress 4.7 [includes changes to the `$wp_filter` global](https://make.wordpress.org/core/2016/09/08/wp_hook-next-generation-actions-and-filters/), which can cause problems for code that directly manipulates it.

The following two methods need to be reviewed, as they may not work correctly any more:
https://github.com/Automattic/jetpack/blob/33ad09de0cca6c7c2bc0c07a9b565282630d54db/class.jetpack.php#L5385
https://github.com/Automattic/jetpack/blob/afc37d716b1bb74377bc1881bec4b3171f08e60a/class.json-api-endpoints.php#L1474

**Comment by kraftbj** [comment]
Relabeling as a bug since using `$wp_filter` directly can lead to fatals in 4.7 in certain circumstances per @pento's make/core post linked above until we're sure we don't fall into that camp. :)
