### ISSUE TITLE
Site verification links all point to Google

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#5138]
In the Site Verification section, where it says "Enter your meta key "content" value to verify your blog with Google Search Console, Bing Webmaster Center and Pinterest Site Verification."

All the links point to Google.

![image](https://cloud.githubusercontent.com/assets/1990037/18341230/f4cf1df2-75a0-11e6-87e8-971c0761ee1d.png)

**Comment by jeherve** [comment]
Fixed in #5106
