### ISSUE TITLE
Getting Jetpack to automatically play nice with offline .dev Desktop Server sites

### ISSUE THREAD

**Issue by paaljoachim** [Automattic/jetpack#5139]
Hey

I have earlier mentioned that Photon does not work offline with a dev site so I had to turn off Photon to see the images again (The issue is somewhere in here. I could not locate it with a quick search.) I am also noticed that the Facebook widget is not showing up in the offline mode.

What would be great is to create a backup of an online site taking it offline creating a dev site through DeskStop Server seeing all the Jetpack modules work as they should.

Thanks.

**Comment by jeherve** [comment]
> Photon does not work offline with a dev site so I had to turn off Photon to see the images again (The issue is somewhere in here. I could not locate it with a quick search.)

Here it is: #4747

> I am also noticed that the Facebook widget is not showing up in the offline mode.

The Widget appears to work properly on my end, as long as Facebook is accessible.

> What would be great is to create a backup of an online site taking it offline creating a dev site through DeskStop Server seeing all the Jetpack modules work as they should.

I'm afraid that's not possible, as a lot of Jetpack modules rely on a communication with WordPress.com to work.

That said, we could work with DesktopServer to add support for [Jetpack's Staging mode](https://jetpack.com/support/staging-sites). I got in touch with them to see if we can make that happen. You can follow our progress on the other issue!

**Comment by paaljoachim** [comment]
Great! Thank you Jeremy!
