### ISSUE TITLE
Admin Page Stats: do not show link to WordPress.com when user isn't linked

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5145]
#### Steps to reproduce the issue
1. Start with a Jetpack site with 2 admin users.
2. Log in with the first user, connect Jetpack to WordPress.com.
3. Log out.
4. Log back in with the second user, go to the Jetpack dashboard.
5. You'll see the message inviting you to link your account to WordPress.com. You'll also see the stats graph, with 2 buttons: 'Old Stats', and the button to view the stats on WordPress.com.

Since that account isn't linked to WordPress.com, that second button is confusing, as it won't work.

I'd suggest removing the second button until the user is linked to WordPress.com.

**Comment by jeherve** [comment]
We'll probably need to remove the clicks inside the graph as well.

**Comment by dereksmart** [comment]
Instead of removing, I'd rather a different button "Link to WordPress.com to view enhanced stats"

**Comment by samhotchkiss** [comment]
I like that @dereksmart

**Comment by samhotchkiss** [comment]
@MichaelArestad -- you good with Derek's solution?

**Comment by MichaelArestad** [comment]
@samhotchkiss Yeah. We might want to tweak it eventually, but it seems like a decent interim solution.

**Comment by MichaelArestad** [comment]
Oooooooor we could try an upgrade banner of some sort attached to the button.

**Comment by MichaelArestad** [comment]
I would lean toward the latter. It seems more reusable.

**Comment by samhotchkiss** [comment]
@MichaelArestad -- we're not trying to get them to upgrade, we're trying to get them to connect

**Comment by MichaelArestad** [comment]
I know. It's the name of a component. Not always call to upgrade.

**Comment by MichaelArestad** [comment]
@dereksmart or @samhotchkiss ^ thoughts?

**Comment by samhotchkiss** [comment]
@MichaelArestad -- I'm fine with the "upgrade banner" solution.  Can you mock it up?

**Comment by MichaelArestad** [comment]
After some discussion with @rickybanister, it would be better to use the First View pattern that encourages users to link their account on the At a Glance section if they want to see/use stats or anything else on that view: p6TEKc-Zk

**Comment by rickybanister** [comment]
This relates to the proposed connection screen discussed in #6067

**Comment by rickybanister** [comment]
This one was labeled 'needs design' so here is a design:

Using the clickable card pattern we are using elsewhere (PBE, etc) let's show a clickable card below the stats card letting the user know they should connect their account to WordPress.com to view more stats.

Something like this please (the language was better articulated in the other issues related to the unlinked user stuff):

<img width="782" alt="screen shot 2017-03-23 at 12 04 23 pm" src="https://cloud.githubusercontent.com/assets/437258/24257338/fbce4258-0fc0-11e7-8b0a-fff997d18079.png">

**Comment by MichaelArestad** [comment]
@rickybanister I thought we had agreed to use the first look view that Jeff implemented in #6067

**Comment by rickybanister** [comment]
There has been discussion the last couple days about wanting to avoid 'bricking the screen' for unlinked users since there are other settings and things they should have access to—I'd recommend us implementing the above as a persistent solution for unlinked users and perhaps showing the 'bricked' screen just once for them with a dismiss button. Does that make sense?

**Comment by MichaelArestad** [comment]
@rickybanister makes sense to me!
