### ISSUE TITLE
Publicize + WP User Frontend: Publishing from WP User Frontend fails to Pub

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5146]
> When I used the native wordpress editor, the post is shared to Twitter and FB correctly. How ever, when a post is posted using WP Userfront end, it is not posted to Twitter and FB.

Related: #4906
Reported here:
https://wordpress.org/support/topic/publicize-not-working-using-wp-user-frontend/

**Comment by kraftbj** [comment]
https://wordpress.org/plugins/wp-user-frontend/

I agree 4906 is related. A very very quick look at the code looks like it may use AJAX, which Pub only works for whitelisted endpoints.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
