### ISSUE TITLE
Admin Page: Custom Content Types card has incorrect URLs.

### ISSUE THREAD

**Issue by robertdall** [Automattic/jetpack#5148]
Turned on featured content / Custom Content Types or whatever you guys are calling it now to the automattic theme Dyad. 

Clean Install WordPress 4.6.1 
WordPress Theme Unit Test Data
Jetpack 4.3

When to configure the portfolio and got **Oops! That page can't be found.**

See weblink: 

http://sandbox.robertdall.com/wp-admin/wp-admin/edit.php?post_type=jetpack-portfolio

Or Screenshot: 

<img width="1378" alt="screen shot 2016-09-08 at 9 37 43 am" src="https://cloud.githubusercontent.com/assets/1909677/18358006/f8799f02-75a7-11e6-977c-1d5d49476953.png">

**Comment by kraftbj** [comment]
There's a double "wp-admin" in there. Where was that link located?

**Comment by robertdall** [comment]
When to configure the portfolio and got Oops! That page can't be found.

Both those buttons have a double wp-admin in it.

http://sandbox.robertdall.com/wp-admin/admin.php?page=jetpack#/writing

<img width="714" alt="screen shot 2016-09-08 at 9 46 16 am" src="https://cloud.githubusercontent.com/assets/1909677/18358276/2dab6380-75a9-11e6-95b6-822e5a1aa23d.png">

**Comment by kraftbj** [comment]
Confirmed. Thanks for the report!
