### ISSUE TITLE
Sync : Skipped Publicized connections are not saved

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5149]
#### Steps to reproduce the issue

1. Create a Publicize connection to Twitter or Facebook.
2. Go to Posts > Add New
3. Create a draft.
4. Click on "Edit Details", and uncheck Publicize to the connection you just created.
5. Save Draft.
6. The checkbox status is saved properly.
7. Hit Publish.
8. The post is sent to that skipped Publicized connection anyway.

Reported here:
- https://wordpress.org/support/topic/publicise-and-share/
- https://wordpress.org/support/topic/publicize-auto-posting-to-social-despite-checkbox_default-__return_false/

**Comment by annezazuu** [comment]
Reported 2822240-t This is happening even with this added:

`// uncheck publicize box for jetpack by default
add_filter( 'publicize_checkbox_default', '__return_false' );`

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/publicize-ignores-settings-forgets-status/

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/after-updating-to-4-3-1-publicize-no-longer-works/#post-8163363

**Comment by davoraltman** [comment]
2823363-t

**Comment by gravityrail** [comment]
I was able to reproduce this, working on it now.

**Comment by gravityrail** [comment]
@jeherve this should be fixed with the deploy I just made to wpcom. There are no changes necessary on the jetpack side. This was caused when we began enforcing whitelists for private meta on wpcom, but we failed to allow for private meta prefixed with `_wpas_skip_*`.
