### ISSUE TITLE
Jetpack should flush memcache/opcache on update.

### ISSUE THREAD

**Issue by macmanx2** [Automattic/jetpack#5150]
Jetpack 4.3.1 added more items to the Security tab, but these were not visible until after running `wp cache flush` via WP-CLI. We'll need to flush the cache on update at least.

Pre-flush: 
<img width="742" alt="screen_shot_on_2016-09-08_at_09_52_21" src="https://cloud.githubusercontent.com/assets/4856235/18359173/827d2fac-75ad-11e6-9c01-2f45ac941e64.png">

Post-flush:
<img width="735" alt="screen_shot_on_2016-09-08_at_09_56_20" src="https://cloud.githubusercontent.com/assets/4856235/18359179/89c6a658-75ad-11e6-92e2-76ae12547c3e.png">

**Comment by dereksmart** [comment]
I wonder if this is still a problem...? @macmanx2 @jeherve have you seen any reports of this?

**Comment by jeherve** [comment]
I haven't seen any reports about this for a while. Let's close and reopen if it comes back.

**Comment by macmanx2** [comment]
I haven't heard any reports either.
