### ISSUE TITLE
post by gmail image issue

### ISSUE THREAD

**Issue by pavan98801** [Automattic/jetpack#5155]
![error](https://cloud.githubusercontent.com/assets/22101100/18391095/6da47874-76ca-11e6-862e-b1a876466d92.png)
this is the error i'm facing whille sending posts from my gmail to wordpress through jetpack in  above image ( inline image1) please help with this issue.

thanks

**Comment by jeherve** [comment]
This could be an issue with your Jetpack connection.

Could you contact us [via this contact form](http://jetpack.com/contact-support/), and send us a few examples of posts where the images appear broken, so we can take a closer look?

Thanks!
