### ISSUE TITLE
Social Media Icons Widget: Add WordPress.org Profile

### ISSUE THREAD

**Issue by annezazuu** [Automattic/jetpack#5159]
Chatting with Mika Epstein at WordCamp LA and this came up. Request to basically add a link to a WordPress.org profile for the Social Media Icons :) 

Example: https://profiles.wordpress.org/annezazu/

**Comment by jeherve** [comment]
Until this gets added to Jetpack, the `jetpack_social_media_icons_widget_array` filter will help:
https://developer.jetpack.com/hooks/jetpack_social_media_icons_widget_array/
