### ISSUE TITLE
Site Stats: Creative browsing puts Jetpack Site Stats in a loop, crashing browsers

### ISSUE THREAD

**Issue by Digiover** [Automattic/jetpack#5177]
By coincidence I found that Jetpack Site Stats starts to loop in Ajax requests, loading only the Dashboard sidebar over and over, when you put a #<number> in the address bar, on a specific place.
#### Steps to reproduce the issue

Steps to reproduce (Jetpack statistics must be enabled):
1. Log on to your WordPress Dashbaord, click through to your daily Site Stats
2. You now have `wp-admin/admin.php?page=stats&day=2016-09-15` in your address bar
3. replace `2016-09-15` with `#1`, making the URL `wp-admin/admin.php?page=stats&day=#1`, and hit [ENTER]

(you'll notice the `=` is removed from the URL)
#### What I expected

I would expect a default Site Stats page like what happens when you enter a `;` as the value for the `day` parameter, or an error message stating "Sorry, you are not allowed to access this page."
#### What happened instead

Jetpack Site Stats is put in a loop -through Ajax calls- loading the WordPress Dashboard sidebar over and over again. Ultimately crashing your browser.
#### Tested with:

Jetpack version: 4.3.1
WordPress 4.7-alpha-38610 and 4.6.1.
Browsers: Google Chrome 55.0.2859.0 dev (64-bit), Firefox 48.0.1

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
