### ISSUE TITLE
Sharing: add new variables for custom share buttons

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [Automattic/jetpack#5184]
Hello JetPack guru`s! 
I ask you to add support of additional variables (now only supports %post_title%, %post_url%, %post_full_url%, %post_excerpt%, %post_tags%), such as %post_id%, %posrt_label% , %my_site_root_url%  in JP Sharing plugin.
Thank you.

**Comment by ysupr** [comment]
Hi, I got for %post_Id% and %my_site_root_url%.  
  
but i missed about post label, what is it? what should i see when use %post_label% it?

**Comment by Aleksey-Maksimov** [comment]
Hi. I attach screenshot.
![screen](https://cloud.githubusercontent.com/assets/17614847/19218481/4b1c0c0a-8e0c-11e6-8d66-208ca27ab86e.png)

**Comment by ysupr** [comment]
Ah it's called slug, will try to check and found what i can help with that

**Comment by jeherve** [comment]
Yep, `%post_slug%` would probably be more appropriate, although I'm not sure how it would be useful, since the complete slug is already available in `%post_full_url%`.

@Aleksey-Maksimov Could you let us know what you would use this value for?

**Comment by Aleksey-Maksimov** [comment]
I installed Read Offline plugin in my WP site https://wordpress.org/plugins/read-offline/
This plugin I need to add the ability to export the blog entries in PDF
But I do not like the buttons that this plugin adds.
I want to use your JP Share plug-in buttons for this task (export blog-post to PDF).
I want to create a custom JP Share button that would have launched a URL in the following formula:

%my_site_root_url%/read-offline/%post_Id%/%post_slug%.pdf

for example:

https://blog.it-kb.ru/read-offline/15914/install-ovirt-4-0-part-5-how-to-setup-virtual-watchdog-device-and-guest-os-ubuntu-server-16-04-service-watchdog-linux-daemon-for-high-availability-and-restarting-unresponsive-vm.pdf

(real blog-post full url is https://blog.it-kb.ru/2016/09/16/install-ovirt-4-0-part-5-how-to-setup-virtual-watchdog-device-and-guest-os-ubuntu-server-16-04-service-watchdog-linux-daemon-for-high-availability-and-restarting-unresponsive-vm/)

**Comment by ysupr** [comment]
Ah sorry, i didn't realize the notifications. 

@jeherve what do you think? is it good to have these 3 new variables? 

1. %post_id% for getting post id
2. %site_url% for getting root url
3. %post_slug% for getting slug

**Comment by jeherve** [comment]
That works for me.

**Comment by ysupr** [comment]
Hi @Aleksey-Maksimov it might be really late, but i have send pull request, and adding those 3 new variables in above list. What do you think? Hopes it good enough to be merged.

**Comment by Aleksey-Maksimov** [comment]
Hi Yoga. I'm still waiting.

**Comment by jeherve** [comment]
This was fixed in #5832
