### ISSUE TITLE
Admin Page Stats: Black bar echos on quick mouse movements

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#5191]
#### Steps to reproduce the issue
On both Firefox 49 (stable) and 50 (dev/aurora channel), moving the cursor quickly over the stats chart results in some echos of what looks like the tool tip.

https://cloudup.com/c0TV8nQwDGF

Reported 2835684-t

**Comment by jeherve** [comment]
Closing as duplicate of #4541
