### ISSUE TITLE
Admin Page: Stats tooltip layout with longer dates/months

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5196]
![screen shot 2016-09-23 at 5 27 02 pm](https://cloud.githubusercontent.com/assets/1126811/18803132/0d249328-81b3-11e6-945d-12855373528f.png)

Notice how the `12th` is show with the `1` on a line and the `2th` on the second line in the above screenshot. Changing the CSS from `break-all` to `break-word` gives us this, so we'd need some more layout work as well. Of note, [there is a library in Calypso to handle orphaned words](https://github.com/Automattic/wp-calypso/blob/master/client/lib/formatting/index.js#L50-L80), which we may find useful here for keeping the month and date together?

![screen shot 2016-09-23 at 5 30 04 pm](https://cloud.githubusercontent.com/assets/1126811/18803195/6ce9c922-81b3-11e6-888d-b6c315a5291b.png)

**Comment by jeherve** [comment]
Should be fixed by https://github.com/Automattic/dops-components/pull/57
