### ISSUE TITLE
JSON API activation error message

### ISSUE THREAD

**Issue by davoraltman** [Automattic/jetpack#5202]
The Jetpack connection got interrupted and the user was trying to activate the JSON API module. The error message he received was:

`JSON API failed to activate. Error: This module requires your site to be set to
publicly accessible.`

The site was public the whole time and the error message is a bit misleading. Would be nice to check whether a change to the logic behind this is needed or just a change to the wording. If it's the latter, I suggest:

`JSON API failed to activate. Error: Jetpack is not properly connected. Please make sure to disconnect and then reconnect Jetpack.`

Came up in 2846252-t

**Comment by kraftbj** [comment]
Noting that this could be returned if the site's RSS feed does not validate as proper XML.

**Comment by oskosk** [comment]
Closing as the issue reported here would be really difficult to confirm for that particular case, being a year-old report. Also, we don't allow people to turn the JSON API module off anymore. Feel free to reopen if there's evidence that this behaviour persists.
