### ISSUE TITLE
Logged out Jetpack Stats widget needs design love

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#5211]
![image](https://cloud.githubusercontent.com/assets/1123119/18894110/e72ad00e-84c5-11e6-8477-bc4a27c15726.png)

Yep. Needs some design love.

**Comment by jeffgolenski** [comment]
@dereksmart @eliorivero @oskosk Any reason this stats data is displaying when Jetpack is disconnected? This screen should only be the connect prompt.

**Comment by oskosk** [comment]
I can't reproduce. Which version is that ?

Here's how I see it in a Pressable site with 4.3.1
![image](https://cloud.githubusercontent.com/assets/746152/18970280/06c69bee-8667-11e6-9390-715fe2edac76.png)

@MichaelArestad you mention "logged out" in the issue title. Did you mean "disconnected" or there's some other condition I'd need to check for reproducing ?

**Comment by MichaelArestad** [comment]
I disconnected on the latest master. went to the dashboard.

**Comment by oskosk** [comment]
:( Couldn't reproduce with latest master either. 

![image](https://cloud.githubusercontent.com/assets/746152/18970622/56c731de-8668-11e6-842c-3d5c9ef0f7f0.png)

**Comment by MichaelArestad** [comment]
Note: I'm experiencing this on a multisite as a super admin. Specifically, I am not on the primary network site. I disconnected, reconnected, and navigated to the Dashboard to see the widget as shown above.

**Comment by MichaelArestad** [comment]
I can't reproduce.
