### ISSUE TITLE
Admin: Not able to hide security modules in new UI with jetpack_get_available_modules

### ISSUE THREAD

**Issue by RCowles** [Automattic/jetpack#5212]
A user in the forums reported that he's unable to remove VaultPress from the new UI using the `jetpack_get_available_modules` filter:

> That functionality is no longer working for for a couple items under the Security Tab (security scanning and site backups specifically) in the new React interface. Previously I could block “vaultpress” in the modules list using that code, but it’s not working anymore. Is there a different module name in the latest version?

Original report:
https://wordpress.org/support/topic/hide-modules-in-react-interface/

**Comment by jeherve** [comment]
Related: #4537

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/several-modules-appear-not-to-be-suppress-able/

**Comment by eliorivero** [comment]
Moving to Settings UI so we can address it.
