### ISSUE TITLE
Add Portfolio content in the Customizer

### ISSUE THREAD

**Issue by samikeijonen** [Automattic/jetpack#5214]
Testimonials have it's own Customizer section where you can edit Archive Title and Content, and Featured image.

![testimonials](https://cloud.githubusercontent.com/assets/1820415/18923641/b513cdf0-85b5-11e6-815b-4568abc246e6.png)

Have you considered doing the same with Portfolio for consistent?

**Comment by jeherve** [comment]
Portfolios also include a customizer section:

![](https://cloud.githubusercontent.com/assets/426388/18348986/fd56fd5e-75ce-11e6-97d7-7f8c6630ec7f.png)

If you don't see it, you might be running into the problem that's discussed in #5143. Could you post some details about your setup there?

Thanks!

**Comment by samikeijonen** [comment]
Oh, I only had `add_theme_support( 'jetpack-portfolio' );`. 

When setting `add_theme_support( 'jetpack-testimonial' );` it enables Testimonials in the Customizer. That's what I thought it would be enough for Portfolios also.

Thanks for this code which enables Portfolio section in  the Customizer.

```
    // Add theme support for portfolios.
	add_theme_support( 'jetpack-portfolio', array(
		'title'          => true,
		'content'        => true,
		'featured-image' => true,
	) );
```
