### ISSUE TITLE
Show connect Jetpack banner on all JP views

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#5215]
As reported by @rickybanister:

> Something I just noticed in passing—if you properly disconnect Jetpack from the Jetpack dash footer in wp-admin and then visit the plugins page you do not see a ‘connect jetpack’ notice. Only on the dash do you see a connect message. We should see if we can get a banner everywhere if you have Jetpack active, but disconnected.

Let's start by making sure it's visible on all JP views.

**Comment by jeherve** [comment]
@jeffgolenski Does #5473 appear on all JP Views, or just the Plugins screen? What should we do with this issue?

**Comment by jeffgolenski** [comment]
@jeherve Right now it'll only appear on the plugins list screen. We need to analyze and tailor different connection banners for different areas within the dashboard. ie. The widget area on wp-admin before a user connects.

**Comment by jeherve** [comment]
Ok, thanks. Punting to 4.5 for now then. 👍

**Comment by dereksmart** [comment]
since #7603 we're also showing the banner on the dashboard as well as the plugin screen
