### ISSUE TITLE
Admin Page: Use /index.php/wp-json/ when using index permalinks

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#5216]
WP has three styles of permalinks:
Pretty Permalinks:
example.com/wp-json/whatever/

Index Permalinks:
example.com/index.php/wp-json/

Default:
example.com/?rest_route=/whatever/

It appears that within the Admin Page, we're not using index permalinks when they're set.

**Comment by chaselivingston** [comment]
Reported in 2826152-t

**Comment by kraftbj** [comment]
This is a core bug. See https://core.trac.wordpress.org/ticket/38182

In the mean time, we could probably default to using the `?rest_route=/jetpack/v4/whatever` method tacked onto the `home_url`, roughly what `rest_url()` in core uses for sites without permalinks set.

**Comment by richardmtl** [comment]
2848569-t

**Comment by annezazuu** [comment]
2849996-t

**Comment by kraftbj** [comment]
Fixed in Core via https://core.trac.wordpress.org/changeset/38790 for 4.7. I'm checking if it'll be backported to older branches of WP.

**Comment by annezazuu** [comment]
2897017-t
