### ISSUE TITLE
Reader: Improve namespacing for RSS feeds

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#5219]
From https://github.com/Automattic/jetpack/issues/996#issuecomment-250291434

> @blowery wrote this, but it doesn't seem like anyone took him up on the advice:

> >The namespace here is something I just made up, so feel free to use something more sane.

> The way the namespace is defined makes it the default namespace and can break parsers (as was my case with a Drupal module recently). Can this namespace be defined with a proper prefix? Something like: 
xmlns:automattic="com-wordpress:feed-additions:1"

**Comment by blowery** [comment]
I left a comment back on #996, I don't think this bug report is valid, but I'm happy to be proven wrong. The way we declare the namespace is in accordance with the XML + namespaces spec and should only put the site and post-id elements into our custom namespace.

**Comment by kraftbj** [comment]
Based on 996, marking as invalid and closing.
