### ISSUE TITLE
Enhancement: Slideshow button to launch Carousel

### ISSUE THREAD

**Issue by ersaloz** [Automattic/jetpack#5220]
Assuming Carousel is active, Slideshow controls could (optionally) include a fourth 'Full Window' button that launched the Carousel with same items.
This feature would address a bunch of use cases while not being, I hope, hard to implement.

**Comment by richardmtl** [comment]
Requested in 744153-zen

**Comment by jenhooks** [comment]
[Requested in the forums here.](https://wordpress.org/support/topic/jetpack-slideshow-as-full-screen-carousel/
)

**Comment by jeherve** [comment]
I'll close this issue, since we're tracking this issue in #24537 now.
