### ISSUE TITLE
is_ssl() doesn't work for https admin-bar-hours-scale unless FORCE_SSL_ADMIN is true

### ISSUE THREAD

**Issue by cliffordp** [Automattic/jetpack#524]
Re: https://github.com/Automattic/jetpack/blob/master/modules/stats.php

The admin bar's site stats image gets loaded via HTTP instead of HTTPS or protocol relative img src (example: /wp-admin/admin.php?page=stats&noheader&proxy&chart=admin-bar-hours-scale ) unless FORCE_SSL_ADMIN is true.

However, if I have a page that is forced to HTTPS via a plugin or other method, is_ssl() isn't working to correctly detect HTTPS (I'm guessing because it's looking at /wp-admin/admin.php and not /index.php)

Ideally, I'd like to see it changed to protocol relative img src.

ty

**Comment by scottsweb** [comment]
I am unable to replicate this in Jetpack 7.2.1. On a `https` without `FORCE_SSL_ADMIN` set, the stats img is loaded from:

```
https://example.com/wp-admin/admin.php?page=stats&noheader&proxy&chart=admin-bar-hours-scale
```

Given the age of this issue and the result of these tests, I think we are good to close.
