### ISSUE TITLE
Admin Page: Manage settings card is still shown under some conditions

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#5244]
#### Steps to reproduce the issue
1. On the settings tab, using the search box, look for "Manage" the **Manage** card will show.
2. Deactivate the Manage module
3. Check the **General** tab and see that the 
#### What I expected

It's expected that user is not able to deactivate manage.
#### What happened instead

The user can deactivate manage.

**Comment by samhotchkiss** [comment]
Closing as this should be handled with the new settings UI in 4.6
