### ISSUE TITLE
Social Media Icons: Add 500px

### ISSUE THREAD

**Issue by davoraltman** [Automattic/jetpack#5249]
We can add [500px](https://500px.com/) social media icon. Would be a nice addition!

**Comment by jeherve** [comment]
We don't have a 500px icon in Genericons, so we most likely won't add support to Social Media Icons just yet.

I would suggest the `jetpack_social_media_icons_widget_array` filter to site owners interested in adding 500px to their site:
https://developer.jetpack.com/hooks/jetpack_social_media_icons_widget_array/
