### ISSUE TITLE
SSO: Extend session length when SSO is used

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#5252]
When someone uses WP.com SSO on their Jetpack site, we should provide the same experience as they have on WP.com. Right now, if I use SSO, I'm logged into the Jetpack site for as long as the site specifies auth cookies (I think 1 day by default?). On WP.com we've extended the cookies to last for 3 years, or effectively "forever", until you intentionally log out. This has resulted in a much better experience for folks, so we should do the same on Jetpack sites.

**Comment by kraftbj** [comment]
Should we highlight or make easier to find the `Log Out All Sessions` field on the profile page? Or pick up any of the core work previously to list all sessions there? Has wp.com wrestled with folks being logged in too long and having someone else jump on a computer in awhile and having surprise access?

**Comment by beaulebens** [comment]
You don't need to "log out all sessions" in this case, since all SSO does technically, is log you in locally. So the normal "log out" link (any of them) within WP will log you out completely. I haven't heard of there being any specific problems on WP.com with account hijacking, since if people are in a shared-machine environment, they should hopefully be explicitly logging out already (and I'm definitely not proposing changing how log out works).
