### ISSUE TITLE
Development Mode: New UI produces errors

### ISSUE THREAD

**Issue by bekarice** [Automattic/jetpack#5254]
#### Steps to reproduce the issue

When in development mode (Jetpack freshly installed), I'm seeing errors while trying to activate any JP module available in dev mode:

```
{Module name} failed to activate. SyntaxError: Unexpected token < in JSON at position 0
```

Disabling javascript in the browser to use the old interface allows the modules to be activated, re-allowing javascript produces the same activation errors.

Another site on the same VPS has no issues with Jetpack in live mode / connected to wp.com.

**Comment by jeherve** [comment]
I can't seem to reproduce the issue on my end. Could you let me know what other plugins are active on that site?

**Comment by bekarice** [comment]
@jeherve found it -- looks like having [Restricted Site Access](https://wordpress.org/plugins/restricted-site-access/) enabled is causing the issue. I have it restricting visitors by login / IP (my current IP is added) and sending them to the login screen -- perhaps a remote / cURL request that's being blocked when modules are toggled?

Would be great to see these play nicely, the reason I use JP dev mode in the first place is when a site is in restricted mode since it can't phone home 😸

**Comment by jeherve** [comment]
That seems to be the expected behaviour with Restricted Site Access: it blocks all REST API queries, including those used to change the status of a Jetpack module.

I found 2 different work-arounds to allow REST API queries with Restricted Site Access:
- https://wordpress.org/support/topic/i-cant-use-rest-api/
- https://philipnewcomer.net/2016/05/allow-rest-api-restricted-site-access/

I haven't tested them though. Let me know how it goes!

**Comment by bekarice** [comment]
@jeherve gotcha, didn't realize it was using the REST API for these settings changes, figured it was just custom ajax calls to save module options. Will just deactivate RSA for now while configuring and look into working around it on that side 👍

**Comment by jeherve** [comment]
> Will just deactivate RSA for now while configuring and look into working around it on that side

Another alternative would be to use the old Settings interface; it's still around and doesn't use the REST API.

You can get to it by deactivating JavaScript on the Jetpack admin page, or by accessing the old URL: `yoursite.com/wp-admin/admin.php?page=jetpack_modules`

**Comment by nicomollet** [comment]
I had the same issue.

REST API plugin was activated. Disabling REST API plugin removed the error message and I managed to enable JP modules.

**Comment by jeherve** [comment]
@nicomollet Which REST API plugin are you referring to? I've tried reproducing the issue with [this plugin](https://wordpress.org/plugins/rest-api/), but everything works well for me.

**Comment by nicomollet** [comment]
@jeherve I am talking about https://wordpress.org/plugins/rest-api/ yes.
I thought it was worth mentioning. 

When I had the issue (failed to activate. SyntaxError: Unexpected token < in JSON at position 0), the Jetpack debugger page didn't show an errors or warning. Updating to JP 4.3.2 didn't help.

**Comment by jeherve** [comment]
Did you have any other plugins active on the site at that time? Can you still reproduce today?

**Comment by nicomollet** [comment]
Yes I have many other plugins:
* WP Rocket
* Yoast SEO 
* Woocommerce
* GravityForms
* Redirection

I activated again REST API v2.0-beta15 and Jetpack breaks again.
Disabling them didn't change a thing.

**Comment by jeherve** [comment]
Could you try the following:

<ol>
	<li>Open the dashboard page.</li>
	<li><a href="https://codex.wordpress.org/Using_Your_Browser_to_Diagnose_JavaScript_Errors#Step_3:_Diagnosis">Open your browser console</a></li>
	<li>Click on the Network tab</li>
	<li>Refresh the page.</li>
	<li>Try to activate a module.</li>
	<li>If you see any lines in red inside the browser console, click on them. A new panel should appear on the right.</li>
	<li>Click on the "Response" tab in that new panel.</li>
	<li>Copy the message displayed there.</li>
	<li>Paste it here.</li>
	<li>If no red lines appeared in the browser console, click on the "Console" tab of the browser console.</li>
	<li>Copy any errors displayed there, and paste them here.</li>
</ol>

**Comment by nicomollet** [comment]
@jeherve 
Sorry my theme was responsible for this too.

I isolated a function that was randomizing `global $wp_version` for security reasons.
