### ISSUE TITLE
Stats: Only two authors shown

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#5255]
#### Steps to reproduce the issue

Check the stats for a multi-author (more than 2) Jetpack site, and click on Days, Weeks, Months, Years. Scroll down to the Authors section.
#### What I expected

I expected to see each author whose posts had had visits.
#### What happened instead

I saw an author for the site admin, and another author with no name and an anonymous gravatar, containing the posts of all the other authors combined.
![image](https://cloud.githubusercontent.com/assets/1990037/19070107/a04b676e-8a21-11e6-91c3-3fad08a5b6f3.png)

2853363-t

**Comment by jeherve** [comment]
Is this specific to stats on WordPress.com, or do you get the same problem when viewing old stats in the dashboard?

**Comment by kraftbj** [comment]
That will only break out authors who have connected their local accounts to WordPress.com, IIRC. Are there any other connected WordPress.com accounts for that site besides the master user?

**Comment by timmyc** [comment]
We had another recent report of this at p3hLNG-Kc-p2 - @kraftbj's response seems to make sense to me, but odd that this has come up twice now in a few days.

**Comment by jeherve** [comment]
Closing this for now, let's reopen if we get a reply.
