### ISSUE TITLE
Sharing via Email: improve name field validation

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5271]
There are currently different issues with the values that are accepted in the name field:

- Apostrophes (as described below)
- URLs (as described in #14221)
- field length (as described in #14667)

This should all be addressed by a better validation of this field, when submitting the form but also when trying to POST directly.

#### Steps to reproduce the issue
1. Activate Jetpack and its sharing module.
2. Go to Settings > Sharing, and enable the Email button.
3. Open your site in an incognito window.
4. On one of your posts, click the email button, enter your own email address, and a name including an apostrophe, e.g. `Jeremy O'Testing`.
5. Check the email you receive:

> Jeremy O\’Testing (***_@**_***.com) thinks you may be interested in the following post:

We'd need to get rid of that extra slash.

**Comment by chaselivingston** [comment]
This also seems to happen with the email subject that's created. 2336158-zen

**Comment by frederickding** [comment]
8b585279ec9ad72abc3a55eb91de515de903f5f2 added some detection of unsafe characters, but [the solution was to MIME-encode them](https://github.com/Automattic/jetpack/blob/241671d60d80fd78a1fb3753eb919eb542b5f520/modules/sharedaddy/sharedaddy.php#L25-L46). However, the plugin passes whatever the Name input is unsanitized into the body of the email:

https://github.com/Automattic/jetpack/blob/335ccaf7f2469ccafd313a879bcd48ab4ea9e6b0/modules/sharedaddy/sharedaddy.php#L103-L111

Although the name field is sent to Akismet, it doesn't look like Akismet is recognizing this pattern of abuse yet.

https://github.com/Automattic/jetpack/blob/335ccaf7f2469ccafd313a879bcd48ab4ea9e6b0/modules/sharedaddy/sharedaddy.php#L77-L85

The proper thing to do is probably to cap the length of the name field so it is far shorter and less useful for sending a spammy message.

**Comment by fresatomica** [comment]
A user also reported that spammers can use the `From` field:

`-----Mensaje original----- 
From: PAYOUT: + 9041 dollars >>> http://tour-may.ru/ZWttYW5uZW44MkB5YWhvby5zZQ== 
Sent: Thursday, May 7, 2020 6:41 PM 
To: deleted_mail@yahoo.se 
Subject: [Entrada compartida] Published title 
`

Reported in: https://wordpress.org/support/topic/sharing-email-abused-for-spam/

**Comment by StefMattana** [comment]
4857925-zen seems to have the same issue (chat link attached in the ticket)

**Comment by formosattic** [comment]
Internal discussion at p9F6qB-8Pz-p2

**Comment by jeherve** [comment]
This can now be closed since we now use mailto instead of a custom email sharing button (see #24040).
