### ISSUE TITLE
Contact Form: Allow value in drop-down item to differ from label text

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/jetpack#5280]
Currently the values in the drop-down menu in the Contact Form can't differ from what's displayed to the user. But it might be necessary to send specific values to the server - codes for instance - which don't make sense to the user. 

For example, it may be necessary to send three-character airport codes as values but at the same time display the full airport name to the user. 

[contact-field label='airport' type='select' value='LHR, TYO, NYC' options='London Heathrow, Tokyo,New York City'/][/contact-form] 

Reported in #2853430-t

**Comment by ysupr** [comment]
How should user set the value? on popup contact form builder? or directly in shortcode?

**Comment by jeherve** [comment]
> directly in shortcode

Directly in the shortcode, but the option will only be available once it's implemented in Jetpack.

**Comment by ysupr** [comment]
Ok, I will try to handle this task.

**Comment by ysupr** [comment]
Hi @jeherve i am on this issue, and i found that to set the value for dropdown fields can be used for other similar field ( radios, checkbox-multiples ).

Should i add this setting valued into those other fields too? or just for dropdown?

**Comment by jeherve** [comment]
Adding the option to other fields as well would work 👍

**Comment by ysupr** [comment]
Ok will add to other similar fields ( radios, checkbox-multiples ).

Since it will add as 'value' attribute for multiple answers fields, it won't work at regular field (text, email, etc).

**Comment by briancolinger** [comment]
Fixed in #5351.
