### ISSUE TITLE
Photon + Lazy Load doesn't load Retina versions

### ISSUE THREAD

**Issue by ChrisBegley** [Automattic/jetpack#529]
When I have Photon enabled and the Lazy Load plugin from the VIP team, Retina versions of the lazy loaded images aren't being served.
http://wordpress.org/plugins/lazy-load/

The Lazy Load plugin changes the markup to look something like this:

```
<img src="http://example.com/wordpress/wp-content/plugins/lazy-load/images/1x1.trans.gif" data-lazy-src="http://i0.wp.com/example.com/wordpress/wp-content/uploads/2014/05/example.jpg" />
```

Could the issue be that the Photon script: http://s0.wp.com/wp-content/js/devicepx-jetpack.js is only looking at the "src" attribute and not the "data-lazy-src" attribute, where the actual image is?

**Comment by gravityrail** [comment]
There is a new Lazy Load module included with Jetpack which works well with Photon: https://github.com/Automattic/jetpack/pull/8093

**Comment by adib** [comment]
This issue is resurfacing again as per JetPack 8.6.1.

**Comment by jeherve** [comment]
@adib Thanks for the report. Could you contact us via [this contact form](https://jetpack.com/contact-support/?rel=support) and give us more details about your site as well as some examples of pages where you experience the issue, so we can take a closer look?

Thank you!
