### ISSUE TITLE
Featured Content broken on WP Nightlies

### ISSUE THREAD

**Issue by BinaryMoon** [Automattic/jetpack#5292]
Hi - Jetpack Featured Content is currently white screening when using Featured content.

Strangely there's no php errors - but I did a bit of debugging and the problem seems to be happening in the wp_loaded method in the Featured_content class. If I comment that out then everything works as before.

**Comment by BinaryMoon** [comment]
Done a bit more digging and it seems to be line 367 where you call get_term_by in the hide_featured_term method.

Looks like there's been quite a few taxonomy changes and it seems one of those is affecting this.

**Comment by BinaryMoon** [comment]
Am quite concerned about this bug. I just updated to 4.4 and the issue is still breaking my dev site entirely.

![screen shot 2016-11-21 at 20 54 04](https://cloud.githubusercontent.com/assets/1004130/20500277/b0d8fba6-b02c-11e6-9c30-eaf0983bd289.png)

I foresee people updating WP before Jetpack and their sites being broken. I imagine it will need to be fixed for wordpress.com anyway before 4.7 is merged so hopefully it can be solved soon.

**Comment by jeherve** [comment]
@BinaryMoon Thanks for the update. We'll address this in 4.4.2, our WordPress 4.7 compatibility release.

**Comment by bradyvercher** [comment]
We just ran into this issue with WP 4.7 RC1. As far as I can tell, it's probably [related to this change in core](https://github.com/WordPress/WordPress/commit/324748a854d5d52d4a19a0a30671a22fa02fd7ff#diff-efd15818123d55a117706670be80c15aR967). `get_term_by()` now calls `get_terms()`, so when `Featured_Content::hide_featured_term()` calls `get_term_by()`, it creates an infinite loop.
