### ISSUE TITLE
Admin Page: style VaultPress error messages

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5301]
Whenever there is an issue with your VaultPress subscription, the following message appears in your dashboard:

![screen shot 2016-10-11 at 14 02 55](https://cloud.githubusercontent.com/assets/426388/19269622/dda0ed7e-8fbb-11e6-8671-f4cf55f9c560.png)

Once you load the Jetpack menu, things aren't super pretty:

![screen shot 2016-10-11 at 14 02 45](https://cloud.githubusercontent.com/assets/426388/19269627/ea23936c-8fbb-11e6-8d13-c23b4ec7cf91.png)

**Comment by dereksmart** [comment]
Took care of this in #7688
