### ISSUE TITLE
Jetpack Comments - clashes with cloudflare also when Rocket Loader is turned off

### ISSUE THREAD

**Issue by talgalili** [Automattic/jetpack#5312]
I can't seem to leave a specific type of comment on my blog here:
https://www.r-statistics.com/2016/06/r-3-3-1-is-released/

Here is the text of the comment:

> A comment sent by email:
> ==================
> 
> 
> For linux simply got to the ubuntu page for your local repository (e.g.):
> https://cran.curtin.edu.au/bin/linux/ubuntu/ 
> 
> Then it is simply a matter of adding, say, "deb https://cran.curtin.edu.au/bin/linux/ubuntu precise/" to /etc/apt/sources.list, and then sudo apt-get update && sudo apt-get upgrade
> 
> Note that 12.04 precise will not be supported in six months time, after which you will either have to upgrade your distro, or start building R from source if you wish to stay current.
> 
> I figured it would help you out next time you have a dumbass linux user ask questions on a blog for windows upgrades ... :)
> 
> Kind Regards
> Ro
> -- 
> Rohan Sadler, PhD, AStat.
> Director, Data Scientist
> Pink Lake Analytics
> 
> www.pinklake.com.au
> 

Whenever I try and submit a comment, I am redirected to a cloudflare's "The page you are looking for cannot be found." error.
![image](https://cloud.githubusercontent.com/assets/976006/19305685/c8f74d36-907a-11e6-8d01-aca4d4685f10.png)

I see here: https://jetpack.com/support/getting-started-with-jetpack/known-issues/
That CloudFlare’s Rocket Loader should be off, and indeed it now is. I refreshed the cache of cloudflare, and I'm still getting this error.

When I try to add the comment manually through the "add comment" inside the post edit, I get the following error:

`(function(html){html.className = html.className.replace(/\bno-js\b/,'js')})(document.documentElement); Nothing found for Wp Admin Admin Ajax Php window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/2\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/2\/svg\/","svgExt":".svg","source":{"concatemoji":"https:\/\/www.r-statistics.com\/wp-includes\/js\/wp-emoji-release.min.js?ver=4.6.1"}}; !function(a,b,c){function d(a){var c,d,e,f,g,h=b.createElement("canvas"),i=h.getContext&&h.getContext("2d"),j=String.fromCharCode;if(!i||!i.fillText)return!1;switch(i.textBaseline="top",i.font="600 32px Arial",a){case"flag":return i.fillText(j(55356,56806,55356,56826),0,0),!(h.toDataURL().length<3e3)&&(i.clearRect(0,0,h.width,h.height),i.fillText(j(55356,57331,65039,8205,55356,57096),0,0),c=h.toDataURL(),i.clearRect(0,0,h.width,h.height),i.fillText(j(55356,57331,55356,57096),0,0),d=h.toDataURL(),c!==d);case"diversity":return i.fillText(j(55356,57221),0,0),e=i.getImageData(16,16,1,1).data,f=e[0]+","+e[1]+","+e[2]+","+e[3],i.fillText(j(55356,57221,55356,57343),0,0),e=i.getImageData(16,16,1,1).data,g=e[0]+","+e[1]+","+e[2]+","+e[3],f!==g;case"simple":return i.fillText(j(55357,56835),0,0),0!==i.getImageData(16,16,1,1).data[0];case"unicode8":return i.fillText(j(55356,57135),0,0),0!==i.getImageData(16,16,1,1).data[0];case"unicode9":return i.fillText(j(55358,56631),0,0),0!==i.getImageData(16,16,1,1).data[0]}return!1}function e(a){var c=b.createElement("script");c.src=a,c.type="text/javascript",b.getElementsByTagName("head")[0].appendChild(c)}var f,g,h,i;for(i=Array("simple","flag","unicode8","diversity","unicode9"),c.supports={everything:!0,everythingExceptFlag:!0},h=0;h div.socialicons{float:left;display:block;margin-right: 10px;line-height: 1;}div.socialiconsv{line-height: 1;}div.socialicons p{margin-bottom: 0px !important;margin-top: 0px !important;padding-bottom: 0px !important;padding-top: 0px !important;}div.social4iv{background: none repeat scroll 0 0 #FFFFFF;border: 1px solid #aaa;border-radius: 3px 3px 3px 3px;box-shadow: 3px 3px 3px #DDDDDD;padding: 3px;position: fixed;text-align: center;top: 55px;width: 68px;display:none;}div.socialiconsv{padding-bottom: 5px;} img#wpstats{display:none}	.recentcomments a{display:inline !important;padding:0 !important;margin:0 !important;} body.custom-background { background-color: #f2f2f2; } #wpadminbar { display:none; } html { margin-top: 32px !important; } * html body { margin-top: 32px !important; } @media screen and ( max-width: 782px ) { html { margin-top: 46px !important; } * html body { margin-top: 46px !important; } } #wpadminbar .quicklinks li#wp-admin-bar-stats { height: 28px; } #wpadminbar .quicklinks li#wp-admin-bar-stats a { height: 28px; padding: 0; } #wpadminbar .quicklinks li#wp-admin-bar-stats a div { height: 28px; width: 95px; overflow: hidden; margin: 0 10px; } #wpadminbar .quicklinks li#wp-admin-bar-stats a:hover div { width: auto; margin: 0 8px 0 10px; } #wpadminbar .quicklinks li#wp-admin-bar-stats a img { height: 24px; padding: 2px 0; max-width: none; border: none; } /* */ Skip to content R-statistics blog Statistics with R, and open source stuff (software, data, community) Menu Home About All articles Contact me Oops! That page can’t be found. It looks like nothing was found at this location. Maybe try a search? Search for: Search Search for: Search e-mail subscription	(adsbygoogle = window.adsbygoogle || []).push({}); Recent Posts	Presidential Election Predictions 2016 (an ASA competition) The reproducibility crisis in science and prospects for R Using 2D Contour Plots within {ggplot2} to Visualize Relationships between Three Variables R 3.3.1 is released heatmaply: interactive heat maps (with R) Archives	Archives Select Month August 2016 July 2016 June 2016 May 2016 March 2016 January 2016 December 2015 August 2015 June 2015 April 2015 March 2015 November 2014 August 2014 July 2014 April 2014 March 2014 December 2013 September 2013 August 2013 July 2013 June 2013 May 2013 April 2013 March 2013 February 2013 January 2013 December 2012 November 2012 August 2012 May 2012 April 2012 March 2012 January 2012 December 2011 November 2011 October 2011 August 2011 June 2011 April 2011 March 2011 February 2011 January 2011 December 2010 October 2010 September 2010 August 2010 July 2010 June 2010 May 2010 April 2010 March 2010 February 2010 December 2009 October 2009 September 2009 July 2009 March 2009 Categories	Guest Post R R and the web R bloggers R community R links R programming Reproducible Research statistics ubuntu Uncategorized visualization TagsANOVA blogging cloud computing code data frame deducer dendextend Dendrogram featured ggplot2 GUI Hadley Wickham installr interfaces LaTex machine learning Open source package packages plyr R R and the web R code R community R GUI R links R package R packages RStudio stackoverflow statistics sweave syntax highlight tables tutorial tutorials Uncategorized update upgrade upgrading R useR visualization windows wordpress youtube Recent CommentsWhy I use data.table. Part 1 – Practical R on A speed test comparison of plyr, data.table, and dplyrpatrick on R 3.3.1 is released[R] Actualizando la versión de R fácilmente en Windows – Infinitos Contrastes on Updating R from R (on Windows) – using the {installr} packageDyn on Exporting R output to MS-Word with R2wd (an example session)rjgamesJose on R 3.3.1 is released R-bloggersR heroes unite – The starting gun for the eRum 2016 will be fired tomorrowcorrr 0.2.1 now on CRAN7th MilanoR Meeting: October 27RTutor: The effect of air pollution on house pricesAnimate maps with mapmate: R package for map- and globe-based still image sequencesMake ggplot graphics2 interactive with ggiraphMapping (historic) tracks in ggplot2The yarrr package (0.0.8) is (finally!) on CRAN	Home About All articles Contact me R-statistics blog Proudly powered by WordPress /* */ /* */ _ga.trackSocial(); (function() { var request, b = document.body, c = 'className', cs = 'customize-support', rcs = new RegExp('(^|\\s+)(no-)?'+cs+'(\\s+|$)'); request = true; b[c] = b[c].replace( rcs, ' ' ); b[c] += ( window.postMessage && request ? ' ' : ' no-' ) + cs; }()); Skip to toolbar About WordPress About WordPress	WordPress.org	Documentation	Support Forums	Feedback	R-statistics blog Dashboard	Themes	Widgets	Menus	Background	Header	Customize	11 Plugin Update	00 comments awaiting moderation	New Post Media	Page	User	var src;if(typeof(window.devicePixelRatio)=='undefined'||window.devicePixelRatio<2){src='https://www.r-statistics.com/wp-admin/admin.php?page=stats&noheader&proxy&chart=admin-bar-hours-scale';}else{src='https://www.r-statistics.com/wp-admin/admin.php?page=stats&noheader&proxy&chart=admin-bar-hours-scale-2x';}document.write('');	SEO Upgrade To Pro	Edit SEO	Performance	Feature Manager	Delete Cache Search	Howdy, Tal Galili Tal Galilitheshadow	Edit My Profile	Log Out	Notifications	Log Out`

When I try other comments, they are accepted without a problem!

I'm using the latest WP and plugins.

What should be done?

Thanks.

**Comment by jeherve** [comment]
I can't seem to reproduce the issue on another site using CloudFlare, regardless of whether I enable Rocket Loader or not.

The issue most likely specific to your setup. Could you send us more details about your site [via this contact form](http://jetpack.com/contact-support/), so we can take a closer look?

Thanks!

**Comment by talgalili** [comment]
Thanks.
1) What other information do you require?
2) Can you copy paste the text from above and post it to the comment of that post? If so - does it go through, or do you get the same error?
(I got it from two different computers)

**Comment by jeherve** [comment]
> 1) What other information do you require?

We'd need as much information as you can give us about your site, its plugins, its setup. To make things easier, you could actually use the built in Jetpack Debugger to send us detailed information about your setup, like so:

1. Go to the Jetpack page in your dashboard.
2. Click on the Debug link appearing at the bottom of the page.
3. Click the link that says "click here to contact Jetpack support."
4. Fill in the description box and your name and email address.
5. Click the "Contact Support" button to send us the debug results privately. It's best not to post this information here, as it contains private details about your site.

Thanks!


> 2) Can you copy paste the text from above and post it to the comment of that post? If so - does it go through, or do you get the same error?

I get the same error. I don't get it on my own test site, though.

**Comment by talgalili** [comment]
Sent.
