### ISSUE TITLE
Protect warning message on login screen

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#5314]
A user added this to their login page:
![image](https://cloud.githubusercontent.com/assets/1990037/19309749/b9504fa0-907e-11e6-8a89-44034a93c17e.png)

@jeherve suggested it might be a good idea to customize the "wrong password" error message to add a similar kind of suggestion, to warn users to use the lost password link, not to just keep guessing their password.

**Comment by ysupr** [comment]
so how should it works? should creating new text field entry at jetpack > settings > security ?

**Comment by jeherve** [comment]
@ysupr I don't think we need to add any kind of UI for that new custom error message. It should just change if Protect is active.

**Comment by ysupr** [comment]
@jeherve oh i see, i think user can set their own message.

So when Protect is active, the defined warning message will replaced the original WordPress warning message. 

then, what the message? exactly like the @danjjohnson above?

**Comment by jeherve** [comment]
> what the message? exactly like the @danjjohnson above?

Something like that, yes. @jessefriedman Could you weigh in on wording, and the overall idea here?

**Comment by jessefriedman** [comment]
I would prefer something much shorter like: "Can't remember your password? Let's [reset it]" but that doesn't inform them that they will be locked out.  

I think the better solution would be to be smarter about unlocking ip's that reset the password.  @samhotchkiss could we do something like that?  If someone requests and successfully resets their password that we go ahead and lift the lock out on them?

**Comment by ysupr** [comment]
Hi, @jessefriedman i think that's possible. but i didn't find where jetpack store the list of lock out IP on database. if i found it, then maybe i just need to delete the record when successfully reset their password.

**Comment by samhotchkiss** [comment]
Closing per outcome of #6329
