### ISSUE TITLE
Misaligned double icon on "updates needed"

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#5325]
#### Steps to reproduce the issue
1. Installed 4.3.2 from scratch
2. Connected Jetpack
3. Looked at my dashboard
#### What I expected

Pure beauty
#### What happened instead

![image](https://cloud.githubusercontent.com/assets/574752/19337051/66463838-90ce-11e6-8f78-987ae6d58d5e.png)

**Comment by samhotchkiss** [comment]
Also: 
![image](https://cloud.githubusercontent.com/assets/574752/19337072/ae57d9ba-90ce-11e6-9b93-28b436aadf04.png)

**Comment by dereksmart** [comment]
This looks to be the suspect: https://github.com/Automattic/dops-components/commit/4dd11bd34579660666b591cd3dd1616098a0aa31

**Comment by rcoll** [comment]
I've also seen this is several places throughout the UI lately.

**Comment by eliorivero** [comment]
Also here
<img width="394" alt="icon" src="https://cloud.githubusercontent.com/assets/1041600/19352814/a10c6316-9137-11e6-9ee1-7dec1308db10.png">

**Comment by eliorivero** [comment]
Opened a PR that fixes this https://github.com/Automattic/dops-components/pull/68
It fixes it but would love @MichaelArestad and @jeffgolenski feedback. We don't want to break anything else 😱
