### ISSUE TITLE
IDC: Add auto-staging notice everywhere

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5340]
In [this comment](https://github.com/Automattic/jetpack/pull/5278#issuecomment-253839430), @simonwheatley suggested showing the IDC auto-staging notice everywhere in wp-admin.

I'm creating this issue to address that separately so that we can get design feedback on that.

cc @rickybanister @MichaelArestad @jeffgolenski @keoshi

**Comment by samhotchkiss** [comment]
#5436

**Comment by ebinnion** [comment]
After some design feedback, I'm going to close this in favor or smaller issues since we'll need to add the UI and then handle AJAX actions.

![screen shot 2016-10-28 at 9 49 14 am](https://cloud.githubusercontent.com/assets/1126811/19815101/ee500080-9d06-11e6-9053-19979f24eafd.png)
