### ISSUE TITLE
IDC: Possibly change wording in IDC notice

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5343]
Brought up in [this comment](https://github.com/Automattic/jetpack/pull/5278#issuecomment-252259445).

> Separately, we're finding the term "staging site" is loaded and also quite specific. Can we rephrase to something like "The Jetpack connection for this site has been suspended, so it does not interfere with the active Jetpack connection at example.com. More information".

We should probably get some design input on what wording to use and the general flow.

cc @rickybanister @MichaelArestad @jeffgolenski @keoshi

**Comment by samhotchkiss** [comment]
#5436

**Comment by ebinnion** [comment]
Closing this now that we've got design feedback. Here is a rough mock of what we'll be moving forward with.

![screen shot 2016-10-28 at 9 49 14 am](https://cloud.githubusercontent.com/assets/1126811/19815131/1592cf2e-9d07-11e6-99c2-80fba021c044.png)
