### ISSUE TITLE
VaultPress: do not copy `jetpack_options` and `jetpack_private_options` when restoring to alternate site

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5344]
> restores to alt site need to remove live Jetpack blog ID to prevent Identity Crisises
> https://twitter.com/user/status/786981221007962112

Related: #5227

**Comment by ebinnion** [comment]
Looks like you worked on something similar in #5227 as well.

**Comment by jeherve** [comment]
@thingalon Is there a filter we could hook into, from Jetpack, to tell VaultPress not to copy specific options when running an alternate restore, or is that something we could do on VaultPress' end?

**Comment by ebinnion** [comment]
For what it's worth, with our IDC mitigation work and detecting cloned sites, it might be preferable to go ahead and sync the connection details over so that we put the site in auto-staging mode as opposed to the site ended up with a separate connection.

**Comment by thingalon** [comment]
@jeherve: Alternate restores do not run WordPress to do it; we upload a custom PHP script to handle the migration. I have no problem with adding a step to the end of our migrations to delete jetpack options if need be, but it sounds like @ebinnion is suggesting that we shouldn't? 

Either way, let me know and we can make it happen on the VP end. :)

**Comment by samhotchkiss** [comment]
#5436

**Comment by jeherve** [comment]
@ebinnion Should we close this as well, like we did for #5227?

**Comment by ebinnion** [comment]
That sounds reasonable to me. 👍
