### ISSUE TITLE
Subscriptions: Add import option for subscribe by email

### ISSUE THREAD

**Issue by manovotny** [Automattic/jetpack#535]
It's no secret that Google is ending support for some of its services. Some more publicly than others. One of the more recent, silent casualties seems to be FeedBurner's subscribe by email feature.

Some of my clients (and others around the internet) have reported that FeedBurner has stopped sending out emails to readers who have signed up to receive posts by email.

While [MailChimp is a viable alternative](http://blog.mailchimp.com/moving-your-subscriber-list-from-feedburner-to-mailchimp/), I would love to stick with the WordPress ecosystem, as it's the least likely to change on itself, and use Jetpack's subscribe by email option. 

Sadly, from everything I read, it appears that the ability to import subscribers was intentionally left out of Jetpack. 

Would you kindly reconsider adding this feature as I am sure many a trying to flee from FeedBurner and / or Google ending some critical services.

Thanks for the consideration.

And if I am overlooking an import option, please let me know. I'd be happy to be mistaken. :)

**Comment by bradonpurpose** [comment]
Just want to put my vote in for a way to import emails from older services. I'd like to use only Jetpack for my blogs and get away from the cumbersome Subscribe2 plugin.  In the meantime, I appreciate the workaround to create a Subscribe page and have subscribers resubscribe.  
BRAD

**Comment by samhotchkiss** [comment]
I would love to hear some ideas from folks on how to import lists without opening JP up as a platform for spammers to spam for free.

**Comment by bradonpurpose** [comment]
I'm hardly a web guru on such subjects but seems like you could use the same kind of Captcha options to prevent most spammers. Truthfully, I don't understand how JP works enough to know how spammers would take advantage of it. If someone with JP could start by explaining that, maybe we could collectively come up with some ideas.

**Comment by samhotchkiss** [comment]
Hey @bradonpurpose, 

The issue would be that someone could take a list of, say, 100,000 email addresses that they obtained in a non-kosher way (say, they bought a list of stolen email addresses, or they collected them in some way not approved by CAN-SPAM), then send spam/marketing emails to them using the WordPress.com servers.  This would both put us in a questionable position legally and make the WordPress.com mail servers more likely to have emails sent out by our legitimate users land in spam boxes.

Does that help clarify the issue?

**Comment by jeherve** [comment]
Also suggested here:
http://gretchenlouise.com/simplify-email-lists/

**Comment by chaselivingston** [comment]
Suggested in 2260855-t

**Comment by dereksmart** [comment]
@samhotchkiss's has a great point. not something that we will be supporting.

**Comment by mackaaij** [comment]
Hmm maybe you could think about this again. I expect Google to switch of Feedburner as well and then people come looking for a solution. Maybe you could offer an automatic link between Feedburner and WordPress for addresses that went through double opt-in? Or limit the number of addresses one can import [like Aweber does](https://help.aweber.com/hc/en-us/articles/204405938-How-Do-I-Import-Subscribers-Without-Confirmation-)? Or offer to send all subscribers a link to reconfirm?

**Comment by kraftbj** [comment]
If Google kills Feedburner completely and offers an API to export subscribers, that's something on the table. Generic e-mail importing, though, is something we're not going to support at this time.

**Comment by mackaaij** [comment]
Early switchers at disadvantage :) Let's see how long it will take Google to switch off Feedburner indeed.

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/transfer-existing-users-to-subscribers?replies=2&view=all#post-7578833

**Comment by RCowles** [comment]
Requested in 2405993-t

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/import-followers-from-csv?replies=1&view=all

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/importer-adresse-mail-dans-abonnement?replies=1&view=all

**Comment by jeherve** [comment]
Also suggested here:
http://jetpack.com/2016/03/09/5-years-in-jetpack-is-soaring-higher-than-ever/#comment-20205

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/plugin-to-integrate-subscription-with-jetpack?replies=4&view=all

**Comment by jeherve** [comment]
Also Suggested Here:
https://wordpress.org/support/topic/migrate-my-wordpress-users-to-jetpack-subscribers-1?replies=1&view=all

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/importing-a-list-of-subscribers/

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/import-subscriber-from-excel-file/

**Comment by jeherve** [comment]
Also reported here:
https://meta.trac.wordpress.org/ticket/2439

**Comment by jeherve** [comment]
Also suggested here:
https://jetpack.com/2017/02/22/share-it-again-new-social-media-features-for-premium-and-professional-customers/#comment-20903

**Comment by jeherve** [comment]
Also suggested here:
https://jetpack.com/2017/03/27/jetpack-affiliate-program/#comment-21070

**Comment by jeherve** [comment]
Also suggested here:
https://jetpack.com/2017/04/30/jetpack-the-ideal-small-business-plugin/#comment-21324

**Comment by seejacobscott** [comment]
requested here: 3265145

**Comment by csonnek** [comment]
requested in 3321124-t

**Comment by yustinnovita** [comment]
http://pribadidermawan.org/

**Comment by gracie** [comment]
Requested in 754301-zd

**Comment by jeherve** [comment]
Also in 775475-zen

**Comment by StefMattana** [comment]
Also suggested in 886106-zen

**Comment by jeherve** [comment]
Also in 948160-zen

**Comment by StefMattana** [comment]
Related and suggested something very similar in https://wordpress.org/support/topic/jetpack-blog-subscription-2/

**Comment by kvvsi** [comment]
Mentioned in HC: 27263149

**Comment by leogermani** [comment]
Also in 3908903-zd-woothemes

**Comment by erricgunawan** [comment]
Another request from 3980575-zen:

> am I able to add email addresses myself to receive my blog posts? I have a number of people who signed up a while ago on feedburner and I’d like to add them to Jetpack.

**Comment by t-pabla** [comment]
Since FeedBurner will be turning down email subscription feature, how can I import subscribers from FeedBurner into Jetpack?

**Comment by jeherve** [comment]
I wanted to close the loop on this by pointing out that this feature is now available. Here is how you can use it:
https://wordpress.com/support/launch-a-newsletter/import-subscribers-to-a-newsletter/
