### ISSUE TITLE
Stats + Carousel: Add Carousel views toggle to Stats settings 

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/jetpack#5353]
In 4.2 we added carousel views to site stats.([#](https://github.com/Automattic/jetpack/pull/3638)) In 4.3.2 these were set to disabled by default and a filter added to enable them. ([#](https://github.com/Automattic/jetpack/pull/5154/files))

We already provide toggles on  `/admin.php?page=jetpack#/engagement` for several options, could we also include a toggle for enabling Carousel stats collection?

**Comment by jeherve** [comment]
@jonathansadowski Do you think it would be worth making this a user-facing option, or should it remain a filter only?

**Comment by alexjgustafson** [comment]
2874474-t

**Comment by jonathansadowski** [comment]
@jeherve, I'm leaning toward filter only. If we surfaced it as a user-facing option, I don't believe there'd be enough users making the change to justify having it as an option.

**Comment by jeherve** [comment]
@jonathansadowski Thank you. That's confirming what I had in mind.

@alexjgustafson I'll close this as `wontfix`. Site owners interested in that feature can use the filter, as explained here:
https://developer.jetpack.com/hooks/jetpack_enable_carousel_stats/
