### ISSUE TITLE
IDC: Make syncing of home/siteurl more immediate when using constants

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5358]
Currently, if a user changes the URL of their site via the `WP_HOME` or `WP_SITEURL` constants, it could take a few minutes to sync those values. This is because we only sync callables every few minutes.

We should find a way to sync those more real-time. We already send the `home` and `siteurl` values with every sync request. Perhaps we can rely on that?

**Comment by samhotchkiss** [comment]
#5436
