### ISSUE TITLE
Admin: Popover alignment issues

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#5360]
#### Steps to reproduce the issue

First, set site to RTL.
- Roll the mouse over Stats. Assert that the Popover tip is offset from where it should be.
  Quick fix for this issue could be hiding the tip, as we did before the Popover refactoring.
- Also, check that when mouse is at the far right, the content is moved towards right, thus causing it to be clipped. Likewise, when mouse is at the far left, content is moved towards left.
  
  It's like the edge detection is inverted as can be seen in the following images.
  <img width="269" alt="towards left" src="https://cloud.githubusercontent.com/assets/1041600/19453144/56fa8ad6-948a-11e6-86c8-4c7073e01c31.png">
  <img width="313" alt="towards right" src="https://cloud.githubusercontent.com/assets/1041600/19453145/57008e4a-948a-11e6-9141-f11d2f63ea56.png">

**Comment by ebinnion** [comment]
Of note - When I test with my site in Hebrew and on IE11, the tooltip doesn't even show. On hover, a scrollbar appears on the bottom as well, which makes me think the tooltip is being positioned off screen.

**Comment by samhotchkiss** [comment]
This appears to be fixed now.
