### ISSUE TITLE
IDC: Verify permissions for auto-staging UI

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5361]
Only admins should be able to change settings that affect auto-staging, such as forcing sync, disconnecting, dismissing the notice, etc. But should we show the auto-staging notice to other users? 

My assumption is not. But, let's be sure to check that.

**Comment by dereksmart** [comment]
If non-admins can't do anything about it, then I'd say we shouldn't show it to them

**Comment by samhotchkiss** [comment]
#5436

**Comment by ebinnion** [comment]
This was handled in #5475.
