### ISSUE TITLE
IDC: Add tracks to auto-staging notice

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5363]
First, can we even add tracks for a site that's in staging mode? If not, can we figure out a work-around?

Second, let's make sure that we've added some sort of tracking so that we understand how our users are using the auto-staging UI. It would be very valuable to understand how many sites simply dismiss the notice, how many disconnect/reconnect, and how many force the sync.

**Comment by dereksmart** [comment]
We can still track in staging 👍 .  As of late, all staging does is block sync. 

However, there are some things to consider: 
- We're currently only allowing tracks from Jetpack for linked users.  This can be changed to use an anonymous ID for unlinked/logged out users, though it will take some refactoring, experimenting and testing.  
- We will also need to be sure that the site has already been exposed to the privacy policy.  This happens during the connection process, so as long as Jetpack isn't disconnected or in dev mode, I don't think we'll have any problems here.

**Comment by ebinnion** [comment]
> We're currently only allowing tracks from Jetpack for linked users. This can be changed to use an anonymous ID for unlinked/logged out users, though it will take some refactoring, experimenting and testing.

I hope that this will be mostly a non-issue. We should probably only show the notice to admins. So, that plus the push to SSO in the future where we'll promote SSO and auto-connect, we should handle this.

**Comment by samhotchkiss** [comment]
#5436

**Comment by ebinnion** [comment]
Fixed in #5499.
