### ISSUE TITLE
IDC: WPCOM: Figure out rate-limiting of WPCOM side IDC

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5364]
For sites that define home and siteurl via constants, let's come up with some rate limiting to make sure that we're not constantly changing options for silly sites.

**Comment by roccotripaldi** [comment]
@kraftbj raised this issue during a Zoom hangout the other day. Can you remind me of the use case here? Why doe sites often change their URL constants?

**Comment by ebinnion** [comment]
Some hosts/sites dynamically define their home/siteurl. For example, on a default installation of WordPress by ServerPilot, my sites include this code:

```php
define('SP_REQUEST_URL', ($_SERVER['HTTPS'] ? 'https://' : 'http://') . $_SERVER['HTTP_HOST']);
define( 'WP_SITEURL', SP_REQUEST_URL );
define( 'WP_HOME', SP_REQUEST_URL );
```

**Comment by samhotchkiss** [comment]
#5436

**Comment by ebinnion** [comment]
For what it's worth, I'm working on a PR in #5433, that will handle cases like the above where the protocol is dynamically changed. But, that PR does not handle cases where the host is changed dynamically.

Maybe we just decide to not automatically fix the WPCOM side IDC once per day/hour/etc.?

**Comment by ebinnion** [comment]
Deployed in r145465-wpcom.
