### ISSUE TITLE
General: IDC: Remove XMLRPC dependency in Jetpack::check_identity_crisis()

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5367]
Now that we are relying to sync to determine whether we are in IDC, we should be able to remove the XMLRPC calls out of `Jetpack::check_identity_crisis()`. We should be able to replace that with this:

https://github.com/Automattic/jetpack/blob/882c585e5ae2a21f9dd1fa1e1d3b578ca016dbab/class.jetpack.php#L5322-L5344

Perhaps, we could remove `check_identity_crisis()`? Or maybe, take all of the validation logic from `validate_sync_error_idc_option()` and stuff it inside of `check_identity_crisis()`?

**Comment by samhotchkiss** [comment]
#5436
