### ISSUE TITLE
Infinite Scroll: not loaded on static home page (Genesis Blog template)

### ISSUE THREAD

**Issue by galbaras** [Automattic/jetpack#5373]
I've enabled infinite scroll on a test site and it works OK on category pages, but I want it to work on the home page, which is a static page that loads the posts (don't ask).

I've found the jetpack_infinite_scroll_load_scripts_and_styles filter and tried different things - is_front_page, is_home and even simply returning "true", but the scripts and styles are not included in the page.

Conversely, when my filter returns "false", infinite scrolling continues happily on archive pages, and still doesn't work on the home page, so it looks like the filter is not having any effect.

The site is based on the Genesis Framework, the home page uses the Blog template and is set as the blog's front page, with nothing set for the posts page.

Feel free to check the HTML output on http://dev.get-business-online.com/ronitbaras/. I've disabled caching and minification to take them out of the equation.

**Comment by jeherve** [comment]
I'd suggest using the `infinite_scroll_archive_supported` filter to add Infinite Scroll support to that page:
https://developer.jetpack.com/hooks/infinite_scroll_archive_supported/

That should help.

If you run into more issues, don't hesitate to send us an email so we can take a closer look and run some tests with you.
http://jetpack.com/contact-support/

Thanks!
