### ISSUE TITLE
Manage: Strange design on landing page when enabling via Calypso

### ISSUE THREAD

**Issue by roundhill** [Automattic/jetpack#5380]
#### Steps to reproduce the issue
1. Connect a site that doesn't have Jetpack manage enabled.
2. Visit `/plugins` for the site in Calypso.
3. Click the button to enable Manage.
4. You'll be taken to this page in wp-admin:
   <img width="626" alt="screen shot 2016-10-19 at 1 25 34 pm" src="https://cloud.githubusercontent.com/assets/789137/19541477/7555b89c-961b-11e6-9b4a-ac3d20956a5d.png">
#### What I expected

A nice shiny message that follows the new design standards.
#### What happened instead

I saw a very basic message in wp-admin.

Safari on macOS Sierra.

**Comment by enejb** [comment]
I think this is fixed. 
This is how it looks in master now.

cc @jeffgolenski feel free to reopen this issue. 

<img width="689" alt="screen shot 2017-01-14 at 17 19 38" src="https://cloud.githubusercontent.com/assets/115071/21959489/bd203dd6-da7d-11e6-991a-5eafada811c0.png">
