### ISSUE TITLE
Gracefully handle the deletion of the master user

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#5393]
In Jetpack, the "site owner" or the local account that connected the site to WordPress.com is known as the master user. If another admin deletes the master user, Jetpack still uses the now-deleted ID as the master user which may result in odd activity on the Jetpack side.

On the WordPress.com side, the user is not disassociated so still has access to Calypso. Actions changing the local site (new post, grabbing settings, plugins, etc) will fail as the user authentication on the local end will fail, but they still have access to Stats, Plans, etc.

Marking as 4.4 as it impacts our plans for greater parity between wp.com and Jetpack

**Comment by kraftbj** [comment]
This is too big to get to this late in 4.4 cycle.

**Comment by jeherve** [comment]
Related discussion: p1HpG7-3qB-p2

**Comment by jeherve** [comment]
This was fixed, we now have a notice inviting you to switch master users when you try to delete the master user in the Users menu.

#13322
