### ISSUE TITLE
无法启用插件，因为它引起了一个致命错误（fatal error）。

### ISSUE THREAD

**Issue by TChenQuan** [Automattic/jetpack#5400]
_**无法启用插件，因为它引起了一个致命错误（fatal error）。**_
**Fatal error: Cannot redeclare jetpack_require_lib() (previously declared in /home/latskyxy/public_html/wp-content/plugins/wp-markdown-editor/jetpack/require-lib.php:3) in /home/latskyxy/public_html/wp-content/plugins/jetpack/require-lib.php on line 36**

**Comment by jeherve** [comment]
You seem to be using another plugin, [WP Markdown Editor](https://wordpress.org/plugins/wp-markdown-editor/). That plugin is a copy of [Jetpack's Markdown module](https://jetpack.com/support/markdown/). You can consequently disable that plugin since you already use Jetpack.
