### ISSUE TITLE
Admin Page: improve ease of getting to Calypso Stats page for a site

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5403]
> In the Jetpack settings page, where we can see the status of “Connection Settings”, you need to include a link or button link to go to our WordPress Management Page, and this will open in a new window.

Suggested here:
https://wordpress.org/support/topic/needs-addition-link-to-wordpress-management-account/

cc @MichaelArestad

**Comment by MichaelArestad** [comment]
@jeherve Thanks for the heads up. What is the WordPress Management Page?

**Comment by jeherve** [comment]
Since we're talking about the connection settings card, `wordpress.com/me` makes sense to me.

**Comment by MichaelArestad** [comment]
But is that what the user is referring to?

**Comment by jeherve** [comment]
I've asked, will let you know when they reply :)

**Comment by jeherve** [comment]
Seems I was wrong.

> Its the same link that exists on the Dashboard button – “View More Stats On WordPress.com”.
>
> Yes, it would be duplicating this same link, but it is lessening the clicks necessary to get to it if we first go to the Settings page instead of the dashboard page.
>
> Maybe a main menu idea that appears on all pages of the JetPack interface where this main menu method would take care of that, even the “View more Stats on WordPress.com” button.

**Comment by MichaelArestad** [comment]
So it would go to the dotcom stats page. Noted.

**Comment by samhotchkiss** [comment]
#5461
