### ISSUE TITLE
Comments: jQuery is not defined

### ISSUE THREAD

**Issue by fgiasson** [Automattic/jetpack#5411]
[I think] since the last Jetpack update, comments are broken because jQuery doesn't looks like to be defined.

Here is an example:
 
   http://fgiasson.com/blog/index.php/2016/10/24/create-a-domain-text-classifier-using-cognonto/

Probably that some loading issues are going on, maybe because of interacting with my theme (Satellite).

Is there an easy fix to this issue?

**Comment by jeherve** [comment]
Everything appears to be working properly on your site right now. Did you manage to solve the issue by yourself? Did you by any chance use another plugin to change the way js libraries were loaded / concatenated on your site?

**Comment by fgiasson** [comment]
Hi @jeherve,

Sorry, I forgot to check with other browser and to specify that it was happening with latest FireFox. I confirm that it is not a problem in Chrome nor Edge but is still an issue with FireFox.


Thanks,

Fred

**Comment by jeherve** [comment]
I can't reproduce the issue in Firefox. Do you happen to use browser add-ons that may interact with JavaScript in Firefox? Could you try to start Firefox in safe mode, without the add-ons, and see if it helps?

**Comment by fgiasson** [comment]
@jeherve thanks; you were right, the issue was with the Privacy Badger (from EFF) plugin.

Thanks!
