### ISSUE TITLE
Publicize: Post shared to social media networks when connection is not globally enabled

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/jetpack#5427]
#### Steps to reproduce the issue
1. Connect a site to Facebook and make sure the connection is not shared with other users.
2. Sign into the site as a different user and publish a post. 
#### What I expected

I didn't expect the post to be shared to Facebook since it wasn't connected for the user who published the post.
#### What happened instead

The post was shared to Facebook. It correctly showed in the Publish module, "Publicize: Not Connected" but it was still shared to Facebook.

Reported in #2875545-t

**Comment by jeherve** [comment]
cc @enejb Could this be sync related?

**Comment by enejb** [comment]
Would very well be :/

**Comment by huntleyta** [comment]
Yes, twitter and tumbler also happen the same.

**Comment by huntleyta** [comment]
Now ver.4.4 released and I updated but the problem still exist..

**Comment by seejacobscott** [comment]
Reported here: 2975765-t

**Comment by seejacobscott** [comment]
Reported here: 2963335-t

**Comment by gravityrail** [comment]
This has been fixed in wpcom-149019
