### ISSUE TITLE
Add single image lightboxes

### ISSUE THREAD

**Issue by bwilczek** [Automattic/jetpack#5431]
## Synopsis

Currently, Jetpack only shows lightboxes for gallery carousels, the goal of this project is to extend that functionality to single images. This issue is a formalized approach to implement requirements requested in #375.
## Visitor's experience

In post view nothing changes for the reader. Image is displayed the same way as always and can be surrounded with text.
![Post view](https://i2.wp.com/puu.sh/rUVWE/fc27c9df05.png?resize=711%2C483&ssl=1)

What does differ is the view when the image is clicked. Instead of "Attachment Page" reader can see the image in a Lightbox view.
![Lightbox view](https://i2.wp.com/puu.sh/rUVZN/f5e87abf08.png?resize=728%2C500&ssl=1)

**IMPORTANT**: change is planned only for images linking to "Attachment Page". The original "Attachment Page" **WILL NOT BE ACCESSIBLE** when this feature is turned on.
## Editor's experience

Application behavior on image click (assuming that it is clickable and links to "Attachment Page") is configured using newly introduced field in "Settings > Media". This setting affects both existing and new posts/images and appears only when Jetpack/Carousel is enabled.

![Configuration](https://i1.wp.com/puu.sh/rXvjE/6cd922a7f7.png?resize=510%2C156&ssl=1)

With this checkbox ticked all single images linking to"Attachment Page" will open Lightbox instead of that page. This behavior CANNOT be overriden for individual images.
#### Disabling the feature

Since content of the post is not modified in any way turning Jetpack/Carousel or this newly added feature toggle checkbox off and on does not cause any side effects that would need any special attention.
#### Settings

Add a checkbox to "Settings > Media", visible when Jetpack/Carousel is enabled. Mind the translations.
#### Post page

When Jetpack/Carousel and feature toggle are on launch JavaScript that will process all images present on page with logic ~ like this:

```
foreach( images as img ) {
  if( img.links_to_attachment_page ) {
    img.click(function() {
      create carousel gallery for that single image
      open this gallery
    })
  }
}
```
#### Add Media/Image Settings modals

No actions needed.

Complete: 100% - development and local tests completed

**Comment by samhotchkiss** [comment]
Sounds good to me!  @MichaelArestad, any further input?

**Comment by MichaelArestad** [comment]
I dig where this is going!

I don't think we need to have a setting for this at all. It seems like it should just work. If they have Carousel enabled, it should just work. It's a really specific potentially confusing setting even if it was phrased differently.

**Comment by jeherve** [comment]
> It seems like it should just work. If they have Carousel enabled, it should just work. 

I would agree. After all, Carousel also takes over the click behaviour for your galleries, so I think it's fine to have it do the same thing for single images as well.

We can of course add a filter so folks can disable it easily, while keeping it on for galleries.

**Comment by bwilczek** [comment]
Code ready. Tested on linux, windows and Android. According to comments above configuration checkbox replaced by filter, by default feature is on. Relevant PR: https://github.com/Automattic/jetpack/pull/5469

**Comment by samhotchkiss** [comment]
Tested latest updates-- Works well!

**Comment by s-a-s-k-i-a** [comment]
Would love to see this for WooCommerce product images/gallery on single product page as well.

**Comment by s-a-s-k-i-a** [comment]
Was there an update here? It doesn't seem to work for single images anymore.

**Comment by jeherve** [comment]
@s-a-s-k-i-a Could you give us an example of a post where this does not work for you, so we can run some tests?

**Comment by s-a-s-k-i-a** [comment]
@jeherve Thanks for your reply :)
Sure: check out this post f.e.: https://www.saskialund.de/yoast-seo-plugin-optimal-einstellen-so-gehts/
Most of the images added, are plain images without being linked to anything.

But there are a few images, where I tried to get the jetpack carousel to work. I tried both linking them to their attachment page and linking them to their mediafiles. But neither option worked to get carousel up for them. Example images are in paragraph below title "geben sie sich mühe!". Please do strg+f to find that .. its a really long post :D

**Comment by s-a-s-k-i-a** [comment]
Ok, one sec....

Done.. but as mentioned in my last post: I tried this also, and still.. no carousel coming up.

**Comment by jeherve** [comment]
Thank you. I can see the issue on your site now. I can't, however, reproduce on a test site of mine. Everything seems to work for me.

It looks like those images miss the attributes Carousel needs to open the overlay. Could you try to deactivate any other plugin that may interact with images on your site, and let me know if you find a conflict?

Thank you!

**Comment by s-a-s-k-i-a** [comment]
You are welcome and thank you , too :)

It wasn't a plugin conflict,  but a theme conflict. I switched to twentyseventeen for a moment, and jetpack carousel worked for single images.
So I need to dig in to my theme code...

Thanks again for investing time!
