### ISSUE TITLE
IDC: Create support documentation on jetpack.com

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5448]
Near the end of this project, let's be sure to coordinate with HEs and @jessefriedman to create some documentation to help explain what an IDC is, what "Safe Mode" is, and what the different actions actually mean.

**Comment by samhotchkiss** [comment]
Changed priorities around-- this needs to get done, but isn't a blocker for release

**Comment by dereksmart** [comment]
https://jetpack.com/support/safe-mode/
