### ISSUE TITLE
New and Improved VideoPress

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#5457]
Synopsis: Recreate the VideoPress interface to remove the requirement that users have a WordPress.com site.

Responsible: @dbtlr, @rcoll 

User experience: This attempts to fix 2 major parts of the user experience. First, this removes the idea of a connected WPCOM blog for VideoPress and instead uses the Jetpack plan itself. Second, it removes the extra interface for VideoPress uploading and instead moves the uploader into the standard media library uploader.

Technical approach: The main points on the technical approach here is that, in order for uploading to work properly with the WPCOM API (where VideoPress processing occurs), an empty media item needs to be generated on the Jetpack blog along with a one-time authentication token. These two items are used to upload the media to the WPCOM API, where transcoding occurs and the media is attached to the associated media id on the shadow blog. Once this is done, Jetpack is instructed to update its metadata for the VideoPress item via an XMLRPC callback.

Designs: This should be screenshots of the design

Complete: 100%

Difficulty:  5

Last Updated: 2016-10-31 by @samhotchkiss

**Comment by jeherve** [comment]
Noting that we'll need to update documentation once this gets merged:
- The VideoPress support page will need a refresh.
- The Plans page on Calypso will need a refresh.
- The WP Cli support page will need a refresh.
