### ISSUE TITLE
Slideshow: Only display error message when Slideshow can't be used

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5458]
#### Steps to reproduce the issue

1. Enable the Shortcodes module.
2. Go to Posts > Add New, create a new post, include a gallery.
3. Choose the Slideshow gallery type.
4. Publish your post.
5. Load the post. If your site isn't super fast, you'll see the following message appear for half a second, before the slideshow JavaScript gets loaded.

`This slideshow requires JavaScript`

Could we make sure this doesn't happen?

Suggested here:
https://wordpress.org/support/topic/slideshow-brief-this-slideshow-requires-javascript-flash-in-gallery/

> it feels like the js is not kicking in soon enough to prevent this message from showing. Any reason not to just wrap the warning in `<noscript>` tags?

**Comment by Mcp-1701** [comment]
Hi, I'm having the same issue, but it isn't loading the images

**Comment by jeherve** [comment]
@Mcp-1701 Could you contact us via [this contact form](https://jetpack.com/contact-support/?rel=support) and let us know your site URL there, so we can take a closer look?

**Comment by brbrr** [comment]
I'm going to close this since there are no plans for extending shortcodes functionality. Feel free to reopen this.
