### ISSUE TITLE
Widgets: Add ability for Instagram shortcode to show latest photo

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#5459]
It would be neat if the Instagram shortcode could just pull your latest photo. So instead of having to specify one like this:

`[instagram url=LINK]`

... maybe you could just do:

`[instagram user=USERNAME]`

... to pull in the latest photo taken by that user.

2897650-t

**Comment by jeherve** [comment]
Related: #1319

**Comment by brbrr** [comment]
Closing this since there are no plans to extend current shortcode functionality and with upcoming Gutenberg, it's priority becoming even lower.
