### ISSUE TITLE
Update Settings UI for better unity with Calypso

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#5461]
Synopsis: Continue improvements on the Jetpack UI to better align with Calypso designs and create a unified experience

Project: https://github.com/Automattic/jetpack/projects/3

Responsible: @zinigor and @MichaelArestad 

User experience: This should go into detail on what the user should experience using this feature/enhancement/fix

Technical approach: TBD

Designs: TBD

Complete: 80

Difficulty:  30

Last Updated: 2016-12-28 (by @zinigor)

**Comment by dereksmart** [comment]
Closing as this doesn't get used or referenced anymore.
