### ISSUE TITLE
Reimplement JITMs

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#5462]
Synopsis: Turn Just In Time Messaging back on

Responsible: @jessefriedman 

Complete: 100%

Difficulty:  1

Last Updated: 2016-11-01 (by @samhotchkiss)

**Comment by jessefriedman** [comment]
Here's a PR for review https://github.com/Automattic/jetpack/pull/5479

**Comment by jeherve** [comment]
@jessefriedman Could you come up with a testing plan so we can ask Beta testers to make sure each JITM is displayed properly?

Thanks!
