### ISSUE TITLE
Upload themes and plugins endpoints

### ISSUE THREAD

**Issue by lezama** [Automattic/jetpack#5466]
Synopsis: Add endpoints to install themes and plugins via .zip files

Responsible: @enejb, @seear

Complete: 100%

Difficulty: 8

- [x] upload theme
- [x] upload plugin

**Comment by seear** [comment]
Theme upload: #5467, plus D3215-code.

Currently working, though the only means of testing it is to manually fire in complex POST requests.

**Comment by enejb** [comment]
❤️
