### ISSUE TITLE
Admin Page: Do not use the feed to verify public accessibility

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#5481]
When activating modules that require the site to be accessible, we are relying on a remote WP.com call that checks the site's feed for validity. This is too fragile.

Could we check the homepage for a 200 response instead? Why are we relying specifically on the feed?

Details: p1HpG7-3v8-p2

**Comment by zinigor** [comment]
Once 4.7 is out we can make a REST API request to see the posts, which should work for the majority of sites out there. And if it doesn't, then we can probably check the homepage as you said, or leave the feed check as it is.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/photon-failed-to-activate-2/

**Comment by kraftbj** [comment]
Backing up some, why do we care if a site is accessible? If the user wants to activate the module, why would we stop them?

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/photon-failed-to-activate-error-this-module/
