### ISSUE TITLE
Add additional widgets to Jetpack

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#5493]
Synopsis: We need to move some additional widgets from WordPress.com over into Jetpack so that users can more easily move from WordPress.com to WordPress.org

Responsible: @jeherve for Blog Stats, @georgestephanis for Milestone, Authors, and Upcoming Events

- [x] Milestone (https://en.support.wordpress.com/widgets/milestone-widget/) #5805
- [x] Authors (https://en.support.wordpress.com/widgets/authors-widget/) #5806
- [x] Blog Stats (https://en.support.wordpress.com/widgets/blog-stats-widget/) #5497
- [ ] Upcoming Events (https://en.support.wordpress.com/widgets/upcoming-events/) (already included in Jetpack, but not shipped, not tested)
- [ ] Instagram (https://en.support.wordpress.com/instagram/instagram-widget/) #1319
- [x] Follow (https://en.support.wordpress.com/widgets/follow-blog-widget/) #5615

The Instagram widget presents the highest level of complexity, as it will rely on WordPress.com's connection to Instagram

Complete: 20%

Difficulty:  14
(1 each for Milestone, Authors, Blog Stats, Upcoming Events, 10 for Instagram)

Last Updated: 2016-12-08 (by @dereksmart)

**Comment by samhotchkiss** [comment]
Original Post:
```
Synopsis: We need to move some additional widgets from WordPress.com over into Jetpack so that users can more easily move from WordPress.com to WordPress.org

Responsible: TBD

 Milestone (https://en.support.wordpress.com/widgets/milestone-widget/)
 Authors (https://en.support.wordpress.com/widgets/authors-widget/)
 Blog Stats (https://en.support.wordpress.com/widgets/blog-stats-widget/)
 Upcoming Events (https://en.support.wordpress.com/widgets/upcoming-events/)
 Instagram (https://en.support.wordpress.com/instagram/instagram-widget/)
The Instagram widget presents the highest level of complexity, as it will rely on WordPress.com's connection to Instagram

Complete: 0

Difficulty: 14

Last Updated: 2016-11-2 (by @samhotchkiss)
```

**Comment by lancewillett** [comment]
Just a few drive-by anecdotes for adding in Follow widget. Was browsing friends sites today and came across https://jeremy.hu/ (and https://jeremy.hu/subscribe/) — I wanted to follow it in the WP.com Reader and sort of expected a follow button there already.

Later I was setting up a new site, and in the Customizer looking for the Follow button — forgot we hadn't added it yet. :)

![add-follow-reader-widget-to-jetpack](https://cloud.githubusercontent.com/assets/66797/20843764/e835bef4-b879-11e6-99c9-f4923c28262a.png)

**Comment by jeherve** [comment]
@samhotchkiss What's our plan for the Upcoming Events Widget? Will it be shipped in a future release?

**Comment by samhotchkiss** [comment]
I believe that @dereksmart removed it from the SVN Ignore

**Comment by jeherve** [comment]
I'm afraid it's still there:
- https://github.com/Automattic/jetpack/blob/master/.svnignore#L18
- https://github.com/Automattic/jetpack/blob/master/.svnignore#L21

@dereksmart Want me to create a PR for this, or do you have this ready somewhere?

We'll probably also need to remove `modules/shortcodes/upcoming-events.php` when #6059 ships.

**Comment by dereksmart** [comment]
@jeherve I was going to do that after I tested 6059 (doing now), but you're more than welcome to 👍
