### ISSUE TITLE
Jetpack plans: Incorrect plugins provision redirection

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/jetpack#5498]
The Problem
==========

The new jetpack dashboard has some links where premium plans owners can click to go to calypso to autoconfigure their plans. The button that should configure Vaultpress is adding the wrong slug to the redirection link, so it doesn't do anything once in calypso.

The correct slug should be "vaultpress", instead of "backups".

This is a video of the problem:
https://cloudup.com/cfWn0M57pUd

There's a patch already in calypso for this problem (https://github.com/Automattic/wp-calypso/pull/9113) , but I think we should fix it in jetpack too and remove the calypso patch as soon as the new jetpack version is released.

**Comment by dereksmart** [comment]
Closing, we'll be leaving the feature-specific slugs going forward as discussed in p6TEKc-Jv-p2
