### ISSUE TITLE
Image Widget : Apply link url to caption

### ISSUE THREAD

**Issue by fabienlege** [Automattic/jetpack#5510]
When "Link URL" is used in a image widget, Link work normaly if visitor click on Image, but the is no link on the caption of this image.

It would be usefull this link is applied to image AND is caption

**Comment by jeherve** [comment]
I don't think we'll implement this, as captions themselves can include links.

The same works for images you may insert into a post with the WordPress editor; if you add a link to that image, the caption isn't part of the link. 

If you want the caption to be clickable, I'd recommend adding a link to the caption text. That will have the same effect.
