### ISSUE TITLE
Custom CSS / Core Customizer Compatibility

### ISSUE THREAD

**Issue by georgestephanis** [Automattic/jetpack#5539]
Synopsis: Core has merged in Custom CSS to the Customizer using a different CPT.  Let's redo our implementation to enhance the Core version.

Responsible: @georgestephanis

User experience: User experience should be roughly similar to the existing Jetpack UX, but using the underlying Core data structure.

Core Ticket for reference: https://core.trac.wordpress.org/ticket/38672

Technical approach: 

Transition our data over to Core’s data structure, and let Core do the heavy lifting. Change Jetpack’s implementation to just layering stuff like LESS, Sass, Syntax Highlighting, CSSTidy, Revisions on top of Core’s existing implementation.

We would also need to change the permission check for the Core Custom CSS Editor to allow non-Superadmins on a multisite install (like WordCamp.org) to edit CSS — basically remap it to edit_theme_options.

This would have some interesting implications, but the general gist is that without Jetpack Custom CSS, permissions simply revert to superadmins only. If we choose to respect the initial cap for unfiltered_css there could be some problems if a superadmin modifies the css, it saves unfiltered, then a Regular admin edits it and strips out the changes.

Designs: Unsure how many (if any) are needed.  Mirroring existing Jetpack and WPCOM ui.

Complete: 100%

Difficulty: 15/40

Last Updated: 11/7 by @georgestephanis

**Comment by MichaelArestad** [comment]
Do you have a link to the Core ticket?

**Comment by samhotchkiss** [comment]
@MichaelArestad: https://core.trac.wordpress.org/ticket/38672

**Comment by MichaelArestad** [comment]
I think this approach makes sense. I'll tackle the designs if you want. What is the timeline for this?

**Comment by folletto** [comment]
@MichaelArestad the designs should be the "same" as Core's future proposal — with an extra due to the advanced panel. See [⌗38707](https://core.trac.wordpress.org/ticket/38707) and p1HpG7-3Ea-p2, but reposting for reference:

![customizer-css-i3](https://cloud.githubusercontent.com/assets/4389/20530552/a9ff0826-b0cb-11e6-88e6-d448bf2eacb7.png)

**Comment by georgestephanis** [comment]
@MichaelArestad @folletto -- Any chance either of y'all could take a quick look at what I've got together and give me explicit direction on what does and doesn't pass muster?  We don't have time to fully implement all of @folletto's (excellent) designs (sadly), but I'd like to make sure I'm not doing something notably ugly.  Happy to talk through what I've got so far at any point.

**Comment by MichaelArestad** [comment]
@georgestephanis taking a look now. Just needs to be on trunk using the JP branch `custom-css-in-customizer`, right?

**Comment by folletto** [comment]
@MichaelArestad I think it's #5527 → `core/custom-css-4.7`

**Comment by folletto** [comment]
Today's screenshot:

![screen shot 2016-11-30 at 12 34 12](https://cloud.githubusercontent.com/assets/4389/20752451/682a65b0-b6f9-11e6-8499-29ad5aebac51.png)

**Comment by folletto** [comment]
With this extra CSS (to be properly adapted, I just tested it added on top), we get this, which is already better:

```
#sub-accordion-section-custom_css .customize-control {
  margin: 12px 0;
}

#sub-accordion-section-custom_css .customize-control-jetpackCss {
  margin: 0 -12px;
  width: auto;
}

.CodeMirror {
  border-top: 1px solid #ddd;
  border-bottom: 1px solid #ddd;
}

.css-help {
  right: 0;
}
```

![screen shot 2016-11-30 at 12 52 22](https://cloud.githubusercontent.com/assets/4389/20752953/dd80fbe2-b6fb-11e6-9a1c-316a06dbe7bd.png)

**Comment by folletto** [comment]
Any chance could we move "CSS Help" and "CSS Revisions" (`#css-help-links`) below the CodeMirror editor (and re-label them as the screenshot)? Would allow us to do this already, so it's aligned with the upcoming design:

![screen shot 2016-11-30 at 13 16 36](https://cloud.githubusercontent.com/assets/4389/20753648/3ddf8582-b6ff-11e6-9e76-9a6cdf92a201.png)

CSS:

```
.css-help {
  border-bottom: 1px solid #ddd;
  background: #ffffff;
  padding: 12px;
  left: 0;
}

.css-help a {
  float: none;
  text-decoration: none;
  color: #555d66;
  padding: 0 12px 0 0;
}

.css-help a:before {
  display: inline-block;
  position: relative;
  font-family: dashicons;
  font-size: 20px;
  padding-right: 3px;
  top: 5px;
  line-height: 1px;
}

.css-help a#revisions-link:before {
  content: "\f321";
}

.css-help a#help-link:before {
  content: "\f223";
}
```

**Comment by folletto** [comment]
I'm keeping the design comments on this thread and just referring in the other so the code and design conversation can happen in parallel. Let me know if it's instead better if I simply contribute there.

I tested https://github.com/Automattic/jetpack/commit/7f48364abb1f1675a6c9cbec8a6aae163147556f so for visual record here's how it looks:

![screen shot 2016-12-01 at 14 40 50](https://cloud.githubusercontent.com/assets/4389/20797774/2f6fe3d6-b7d4-11e6-98c7-e218f4614716.png)

**Comment by folletto** [comment]
Ok so here some final suggestions and then I think it's shippable. 

This is the updated design: 

![screen shot 2016-12-01 at 15 20 38](https://cloud.githubusercontent.com/assets/4389/20799353/cd6c6f50-b7d9-11e6-9345-89efe13923e2.png)

With this sample CSS (always to be adapted to the existing one as this is just an override):

```
.CodeMirror {
  margin-bottom: 0;
}

.css-help {
  padding: 0;
}

.css-help a {
  display: inline-block;
  border-bottom: 4px solid transparent;
  padding: 7px 10px 5px;
  transition: .15s color ease-in-out,.15s background-color ease-in-out,.15s border-color ease-in-out; 
}

.css-help a:hover {
  color: #0073aa;
  background-color: #f3f3f5;
}

.css-help a:focus {
  color: #0073aa;
  background-color: #f3f3f5;
  border-bottom-color: #0073aa;
  box-shadow: none;
}
```

Which basically removes the bottom margin of CodeMirror, attaching the white bar to it, and adding proper hover styles aligned with customizer, and accessible too with the marker.

Hover/Focus states: 

![screen shot 2016-12-01 at 15 24 29](https://cloud.githubusercontent.com/assets/4389/20799507/53f79824-b7da-11e6-9b4f-dce1123a07d6.png)

![screen shot 2016-12-01 at 15 24 37](https://cloud.githubusercontent.com/assets/4389/20799517/5825dd16-b7da-11e6-8f22-4bba3b8260a9.png)


So the changes are:

1. Attach the bar and introduce hover/focus styles (CSS above).
2. Change label to "See full history"
3. Change lable to "Help"

The next step to be in an ideal place from the changes above would be to add the whole blocks under the editor (Media Width, Start Fresh, Preprocessor) to a sub-panel triggered by the cog — but I'm aware we're short on time, so I consider this shippable for this release.

**Comment by samhotchkiss** [comment]
Merged
