### ISSUE TITLE
Sharing: ReCaptcha error for email if Recaptcha is loaded but not on page

### ISSUE THREAD

**Issue by simplystuart** [Automattic/jetpack#5546]
#### Steps to reproduce the issue
- ReCaptcha is loaded on page
- No ReCaptcha object/widget exists

#### What I expected
- Have email sharing work w/ Recaptcha on page

#### What happened instead
- Console error: "recaptcha__en.js:288 Uncaught Error: Invalid ReCAPTCHA client id: undefined(…)"

**Comment by jeherve** [comment]
I can't seem to be able to reproduce the issue. Did you happen to use another Recaptcha plugin on that site?

**Comment by simplystuart** [comment]
Yes there is another recaptcha plugin loaded site wide so:

`<script src='https://www.google.com/recaptcha/api.js'></script>`

is in `<head></head>`.

**Comment by jeherve** [comment]
Thanks for the extra details!

**Comment by dereksmart** [comment]
@simplysaru Hi, can you help me reproduce as well?  I'm trying to manually add the script to the head like so 

```add_action( 'wp_enqueue_scripts', 'enqueue_it' );
function enqueue_it() {
	wp_enqueue_script( 'recaptch', 'https://www.google.com/recaptcha/api.js' );
}

and can confirm is loading in <head>, though the email sharing still works.  What plugin are you using?

**Comment by simplysaru** [comment]
I think I was pinged incorrectly here. @simplystuart this one is for you. ^
