### ISSUE TITLE
Allow user to link from the wp-admin dashboard widget

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#5560]
#### What I expected
To be able to link my user account from `/wp-admin/index.php`.

#### What happened instead
Just this view as an unlinked user: 
![screen shot 2016-11-09 at 9 19 54 am](https://cloud.githubusercontent.com/assets/7129409/20141307/bb8e1190-a65d-11e6-8bb8-b3725439e331.png)

We should add a button, link, or something there promoting the user to link their account.

**Comment by MichaelArestad** [comment]
@jeffgolenski I'm adding you optimistically as the assignee to try to get this done by next Thursday. (I know you're on vacation right now) I'll take a stab at it if I have time before then.

**Comment by jeffgolenski** [comment]
@dereksmart @MichaelArestad Can't we just mod this with the proper verbiage? 

<img width="553" alt="screen shot 2016-12-07 at 2 04 32 pm" src="https://cloud.githubusercontent.com/assets/214813/20982374/4234fc3e-bc86-11e6-9c85-6c8f2c978105.png">

**Comment by dereksmart** [comment]
@jeffgolenski sure but that doesn't show when Jetpack is connected, so we'll have to put it above the content that is in the widget when it's connected.

**Comment by jeffgolenski** [comment]
@dereksmart Yeah of course. Sorry I should have specified - I meant just borrowing that style / format and placing it where it needs to go

**Comment by dereksmart** [comment]
@jeffgolenski okay, so for an unlinked admin, it will look like this 
![screen shot 2016-12-07 at 3 25 14 pm](https://cloud.githubusercontent.com/assets/7129409/20985200/7573190e-bc91-11e6-919f-f8c88b854674.png)

**Comment by jeffgolenski** [comment]
Hm, well that isn't exactly the best. I forgot that the stats could actually show. Perhaps we could left align the text and remove the Jetpack logo there?

**Comment by beaulebens** [comment]
Can we do this directly via a JITM now?

**Comment by rickybanister** [comment]
I agree with @beaulebens here. A JITM style banner would be better here. 

Something like this:

![image](https://user-images.githubusercontent.com/437258/37726976-0e9c842a-2d0d-11e8-8fb2-d6cd3089dc26.png)

**Comment by MichaelArestad** [comment]
Resolved. Here's what it looks like now:

![image](https://user-images.githubusercontent.com/1123119/60373614-9e91db00-99b5-11e9-93f4-d382fd18ab1f.png)
