### ISSUE TITLE
Dashboard widgets can't handle long titles and wide buttons

### ISSUE THREAD

**Issue by zinigor** [Automattic/jetpack#5565]
#### Steps to reproduce the issue
* Use a language with longer words, like Russian
* Optionally switch to Pro to see the Setup button
* Open the dashboard
* Observe the broken widget

![vaultpress](https://cloud.githubusercontent.com/assets/374293/20147239/c5daec5a-a6c0-11e6-9a98-5997b43c5e41.png)

cc @jeffgolenski @MichaelArestad

**Comment by jeffgolenski** [comment]
We should definitely do some work here to have the buttons drop to the next line below the header titles when things are unruly and super long.
