### ISSUE TITLE
Request for ability to stagger the cron schedule

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#5595]
From 2902421-t

Cron was running every minute (or after the code in the ticket, every however many minutes, but at the same time) and it seemed to have a high overall load on his server, causing issues (he has 55 installs). The user requests the ability to stagger out when Jetpack's cron actions are run to avoid everything running at the same time.

**Comment by jeherve** [comment]
See this comment to find out how:
https://github.com/Automattic/jetpack/issues/5513#issuecomment-258791292

Also worth noting that things will change a lot in 4.4, so it might be worth trying to Beta before to make any changes to Cron schedules.
