### ISSUE TITLE
Admin Page: fallback to the old Settings page when WP REST API is inactive

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5596]
One can use [plugins](https://wordpress.org/plugins/disable-json-api/) to fully disable WP REST API in WordPress. This causes error on our Admin page.

It would be nice to fallback to the old Settings page when the REST API isn't available.

**Comment by ebinnion** [comment]
To add some context, that plugin seems to be calling these filters:

```
   // Filters for WP-API version 1.x
    add_filter( 'json_enabled', '__return_false' );
    add_filter( 'json_jsonp_enabled', '__return_false' );

    // Filters for WP-API version 2.x
    add_filter( 'rest_enabled', '__return_false' );
    add_filter( 'rest_jsonp_enabled', '__return_false' );
```
