### ISSUE TITLE
Jetpack Icon Missing

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#5597]
#### Steps to reproduce the issue

1. Load Jetpack 4.4-beta2
2. Look for the Jetpack menu item logo

#### What I expected

1. To see it in all its' beautiful glory

#### What happened instead

![image](https://cloud.githubusercontent.com/assets/574752/20224137/45b0d090-a7fa-11e6-8590-bf20fa928ba4.png)

:-(

**Comment by jeherve** [comment]
Fixed in Beta 4.
