### ISSUE TITLE
Carousel: Next image overlaying scrollbar

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#56]
Reopening [this bug](http://plugins.trac.wordpress.org/ticket/1599) since it seems the problem reappeared.

I was able to reproduce the issue on Windows only, on all carousel pages. Here is an example:
http://en.support.wordpress.com/images/gallery/

![bug-carousel-scrollbar](https://f.cloud.github.com/assets/426388/1860558/5396bc88-77b5-11e3-993e-8492185727f0.jpg)

Reported here:
- http://wordpress.org/support/topic/carousel-overlay-image-on-scrollbar?replies=2

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/carrusel-impossible-to-use-browser-scroll-bar?replies=1&view=all

**Comment by kriskarkoski** [comment]
If I understand this issue correctly I can see it in Chrome 52 on OS X 10.11.6 now as well on http://en.support.wordpress.com/images/gallery/

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
