### ISSUE TITLE
Admin Page: Confirmation pop-up when no changes were made

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5610]
#### Steps to reproduce the issue

1. Start in your dashboard, in Jetpack > Settings > Engagement
2. Expand the Site Stats module
3. Uncheck and recheck the first checkbox
4. Expand the Sharing module
5. Click “Configure your sharing settings”

You'll get this popup from Firefox:

![screen shot 2016-11-11 at 23 24 08](https://cloud.githubusercontent.com/assets/426388/20232043/f8df485c-a865-11e6-9a6e-eabeea4ab0ea.png)

There isn't anything to save, though, since the box was unchecked / rechecked.

**Comment by ebinnion** [comment]
Related: #5130.

**Comment by jeherve** [comment]
Closing as this will become irrelevant in 4.6.
