### ISSUE TITLE
Admin: if the plan is downgraded, deactivate modules that are no longer covered

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#5612]
For example, SEO Tools is on the Professional plan, and if the plan is downgraded to Premium, the module is still active locally.

#### Steps to reproduce the issue
1. add Professional to your account in Store Admin
2. in Jetpack admin, activate SEO Tools
3. downgrade to Premium in Store Admin
4. go to Jetpack admin, SEO Tools is still active, although the card texts correctly reflect that the site no longer has the correct plan. Can be verified with WP-CLI: 
    ```
    wp jetpack module list
    ```
    The module `seo-tools` is marked as active.

#### What I expected
Module SEO Tools to be deactivated.

#### What happened instead
Module SEO Tools is still active.

**Comment by samhotchkiss** [comment]
Elio is tackling this in the AM
