### ISSUE TITLE
Standardize on spelling `email` as `email`, not `e-mail`

### ISSUE THREAD

**Issue by ntwb** [Automattic/jetpack#5619]
#### Steps to reproduce the issue

Translate Jetpack at https://translate.wordpress.org/projects/wp-plugins/jetpack

#### What I expected

I expected to _not_ see `e-mail`

#### What happened instead

I saw `e-mail` 

See the following for more on this:
• https://make.wordpress.org/core/handbook/best-practices/spelling/#terminology

**Comment by eliorivero** [comment]
Closing as it has a patch on #5773
