### ISSUE TITLE
Connection banner: bottom align buttons

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5624]
Can we bottom-align the buttons in it, so that they don’t jump around between panels? 

#5473

p2JiWH-1tm-p2

**Comment by jeffgolenski** [comment]
@jeherve Well, I know this might be a slight annoyance, but it's not an easy fix that we can accommodate a ton of screen sizes with unless we add a bunch of css (nested flexboxing) or js. I can work on a fix, but I don't want to rush through it for 4.4 – I'd like to be methodical about whether the code we add is worth it. Can you assign this to me for 4.4.1? cc @samhotchkiss

**Comment by jeherve** [comment]
> I don't want to rush through it for 4.4 – I'd like to be methodical about whether the code we add is worth it. Can we do this for 4.4.1

Works for me. 👍

**Comment by jeffgolenski** [comment]
@jeherve Just kidding. whipped up a quick fix in this PR ^^
