### ISSUE TITLE
PHP Warnings in jetpack master 

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#5634]
Warning: getimagesize(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/enej/public_html/aaa/wp-content/plugins/jetpack/functions.opengraph.php on line 353

Warning: getimagesize(https://enej.wpsandbox.me/aaa/wp-content/uploads/2016/06/cropped-cd87f5b8-7f23-3e1b-acfb-e631996f89d8-270x270.jpg): failed to open stream: no suitable wrapper could be found in /home/enej/public_html/aaa/wp-content/plugins/jetpack/functions.opengraph.php on line 353

#### Steps to reproduce the issue
I am not sure yet. Thought I would create an issue first. 

#### What I expected
To not see the php warning.

**Comment by enejb** [comment]
I am closing this since it seems to be fixed when I got the very latest version master branch of Jetpack 👍

**Comment by eliorivero** [comment]
This was fixed here https://github.com/Automattic/jetpack/pull/5602
