### ISSUE TITLE
Publicize: add filter to disable enhanced custom stories / embedded images

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#565]
Publicize changes the look of your Facebook updates if you publish Image Posts, or posts including very little text and only an image. When you do so, the image is uploaded to Facebook, and the Publicized post looks like an image you'd have directly uploaded to Facebook.

While this is great since it generates more Likes and Comments on Facebook, it doesn't bring as much traffic to your site as a regular shared link.
Some people also don't feel comfortable having their images uploaded to Facebook.

Would it be possible to add a filter allowing blog owners to use the default link format in their Facebook Publicized posts?

Suggested in 1844983-t

**Comment by astralbodies** [comment]
:heart:

**Comment by jeherve** [comment]
Also requested here:
https://wordpress.org/support/topic/publicize-ignoring-custom-text-on-facebook/page/2?replies=55&view=all#post-7004734

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/jetpack-posts-full-text-on-facebook?replies=27&view=all#post-7004438

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/publicize-not-working-right-since-may-22nd?replies=3&view=all

**Comment by mikeyarce** [comment]
Also suggested here: 2223806-t

**Comment by chaselivingston** [comment]
Also suggested in 2223024-t

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/publicize-posting-quirks-to-facebook-and-twitter?replies=6&view=all

**Comment by jeherve** [comment]
Also suggested here:
https://twitter.com/meyerweb/status/657230138850025472

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/how-do-i-use-publicize-to-tweet-with-a-featured-image?replies=6&view=all#post-7671980

**Comment by kraftbj** [comment]
Also in 2462468-t

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/publicize-publish-new-post-as-a-image-on-facebook-wall-not-as-a-link?replies=1&view=all

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/jetpack-publicize-to-facebook-question?replies=1&view=all

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/twitter-images-in-publicize-posts?replies=1

**Comment by RCowles** [comment]
Suggested in 2788597-t

**Comment by nocean** [comment]
Any movement on adding a filter for more control of the output? Even a simple checkbox in the Publicize settings that allows you to disable sending anything other than a link/title -- and not the excerpt + [ ### more word ] (should be "words" right?)

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/how-to-remove-featured-images-for-twitter/

In this case, the added image cuts off tweets.

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/publicize-share-my-post-at-facebook-as-photo-not-link/

**Comment by antermoia** [comment]
As far as I can see, this isn't limited to "short" posts with a single image. It applies to posts with a gallery as well. Also, this post has 4 paragraphs of "real" text.

The entire gallery is uploaded to Facebook here, and what's more, the feature image (which is part of the gallery as well) is duplicated, appearing TWICE on Facebook. Not ideal.

Example: http://www.shuwenwu.com/2016/10/rush-creek-trail/ (my wife's site)

Resulting FB post: https://www.facebook.com/shulisawen/posts/1403113116384677:1?pnref=story

**Comment by ysupr** [comment]
How about make it follow the post format? if it text then just post the title and shared link, and if it photo it will post the photo with caption the title of post and link as text, and of course applied to other post format too.

**Comment by jeherve** [comment]
> As far as I can see, this isn't limited to "short" posts with a single image. It applies to posts with a gallery as well. Also, the example post below has 4 paragraphs of "real" text.

That's correct. Publicize supports 4 types of posts: images, galleries, videos, and standard.

> As far as I can see, this isn't limited to "short" posts with a single image. It applies to posts with a gallery as well. Also, the example post below has 4 paragraphs of "real" text.

I can't seem to reproduce that issue on my test site at the moment. Did your wife upload the Featured Image separately, in addition to the image that's included in the gallery? If you'd like you can contact us via [this form](http://jetpack.com/contact-support/) so we can take a closer look.

@ysupr While that would be great in theory, unfortunately a lot of themes don't actually support Post Formats. That would consequently make the feature only available to a subset of Jetpack users.

**Comment by antermoia** [comment]
Hello Jeremy, the featured image was not uploaded separately, in WP's Media Library it is the same photo that also appears in the gallery (ie. not a duplicate).

My guess would be that the two files are treated as different (by Facebook? by Jetpack?) because the featured image is a resized version (per the theme's media settings), while the other (in the gallery) is the original upload.

A simple switch for the user to enable/disable the enhanced stories would be most helpful to avoid these issues.

**Comment by jeherve** [comment]
Also requested here:
https://wordpress.org/support/topic/sharingpublicize-not-working-anymore/#post-8415480

**Comment by jeherve** [comment]
Also requested here:
https://wordpress.org/support/topic/publicize-twitter-summary/

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/twitter-post-text-below-image/

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/facebook-share-format/#post-9522088

**Comment by codestor4** [comment]
suggested here 703420-zen 
plus I vote for this!

**Comment by lamdayap** [comment]
858135-zen

**Comment by markjaquith** [comment]
Just adding some info from `858135-zen` which was my report:

When sending to Twitter, the post's featured image is included. This prevents Twitter Cards from working. Cards take a link, and if it has the right metadata, expands it into a rich media card (with the featured image, but also some more information). It also makes the click target bigger, and increases engagement. But you can't have an image attachment AND card. Best, I think, would be for Jetpack to realize that the site is properly set up to display Twitter Cards and then skip the featured image. But if it can't do it automatically, there should be a setting.

**Comment by jeherve** [comment]
Also requested in 877647-zen

**Comment by dadiocoleman** [comment]
It's been 3 years now.
The answer is always "we're looking into it" or "it'll be added at some point".
At this point, I don't think it'll ever be done.

**Comment by KokkieH** [comment]
Another request in https://wordpress.org/support/topic/publicize-post-excerpt-to-twitter/

**Comment by antermoia** [comment]
Four years now. :-1:

**Comment by KokkieH** [comment]
Request via [Twitter](https://twitter.com/ZL2KEJ/status/1004956261685706752)

**Comment by KokkieH** [comment]
Another on [Twitter](https://twitter.com/Dvolatility/status/1012577658180382720)

**Comment by donalirl** [comment]
Another request for Twitter cards here #1357535-zd

**Comment by tmmbecker** [comment]
1645823-zen

**Comment by htdat** [comment]
1660971-zen - Twitter Card request

**Comment by KokkieH** [comment]
Twitter card request: https://en.forums.wordpress.com/topic/twitter-sharing-and-card-image-integration/

**Comment by BrookeDot** [comment]
This is also being discussed in 82800-zd-wordpressvip

**Comment by KokkieH** [comment]
Via [Twitter](https://twitter.com/realkosiso1/status/1148511616733995008)

**Comment by almendron** [comment]
Proposal: Publicize module must do the same as the Sharing Debugger (Facebook) - Card validator (twitter).
Now, the Publicize and Sharing modules work differently. See images:
1) [Publicize: Wrong. Horrible](https://www.almendron.com/compartir/jetpack/error-module/Publicize.jpg). Please change the behavior of Publizie on Twitter.
2) [Sharing: All right. Perfect](https://www.almendron.com/compartir/jetpack/error-module/Sharing.jpg). This is how the Publizie module should work.
3) [Card validator](https://www.almendron.com/compartir/jetpack/error-module/card.jpg) (twitter).

**Comment by jeherve** [comment]
Also in p9dueE-Cz-p2

**Comment by htdat** [comment]
2393223-zen - the user wants to display Twitter Summary Card.

**Comment by tmmbecker** [comment]
2419752-zen - wants to display Twitter Card.

**Comment by htdat** [comment]
2510275-zen wants to display Twitter Summary Card.

**Comment by jenhooks** [comment]
2864769-zen Twitter Card request.

**Comment by jeherve** [comment]
Also in pbAAop-lT-p2
