### ISSUE TITLE
SEO Tools: offer option to upgrade

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5652]
#### Steps to reproduce the issue

1. Go to Jetpack > Settings > Engagement on your site.
2. Activate the SEO Tools module.
3. I'm not exactly sure what to do now, so I'll click on the little toggle.

![screen shot 2016-11-15 at 14 08 10](https://cloud.githubusercontent.com/assets/426388/20306894/1ef14bf6-ab3d-11e6-9d9c-ae726ac969f6.png)

4. I don't know how to buy a plan, though. Shouldn't there be a link allowing me to buy a plan in there?

Our other paid module, VideoPress, takes a different approach. You have to upgrade before you can activate the module.

![screen shot 2016-11-15 at 14 10 01](https://cloud.githubusercontent.com/assets/426388/20306924/46db4b12-ab3d-11e6-9c44-027d82dbb86f.png)

We should probably follow the same approach for all paid modules.

cc @vindl

**Comment by jeherve** [comment]
##5307

**Comment by richardmuscat** [comment]
@jeherve:
- text changes in https://github.com/Automattic/jetpack/pull/5667
- the card should function in the way all the other premium features do (ie: toggle button only visible if user is on the plan, otherwise we show upgrade button) -- I'm not the best person to implement that

**Comment by samhotchkiss** [comment]
This is going to be handled by @rcoll tomorrow

**Comment by vindl** [comment]
@jeherve If it's of any help, that was working when I added it initially -https://github.com/Automattic/jetpack/pull/5307/commits/a3775900c2a9a3ab4e2b2ff2f5f680c48b46e2da. I'm guessing it was dropped after some rebase or reverting the `Traffic` tab modules to `Engagement`.
