### ISSUE TITLE
Import and Export Jetpack module state

### ISSUE THREAD

**Issue by lamdayap** [Automattic/jetpack#5656]
Adding an option to allow users to export and import Jetpack's active modules. The use case is to make it easier for administrators who run multiple sites to be able to import a template of their activated Jetpack modules from one site to another.

2913175-t

**Comment by jeherve** [comment]
You can use the `jetpack_get_default_modules` filter ([#](https://developer.jetpack.com/hooks/jetpack_get_default_modules/)) to choose what filters to enable by default in Jetpack. You could consequently have an array of the modules you need, and they'll be automatically enabled as soon as you connect Jetpack to WordPress.com.
