### ISSUE TITLE
Stats: Defer or async JS to improve site performance

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#566]
Currently, the stats JS loads in a standard way. If we changed it to use `defer="defer"` or  `async="async"`, it could speed up rendering for sites using Stats.

Originally requested in http://wordpress.org/support/topic/defer-statswordpresscomjs?replies=2

**Comment by jeherve** [comment]
Also see #1487 with some suggestions.

**Comment by tillkruss** [comment]
Using just `defer` or `async` won't work, because the script on `stats.wp.com` uses `document.write` in the called `st_go()` function, which if executed after a page finished loading, would overwrite the entire document with the content it outputs, e.g. the smiley image.

**Comment by hubertnguyen** [comment]
If the wp_stats script was enqueued, we could intercept it, and move it to another location. Alternatively, it would be nice if the core wp enqueue process would let developers choose in which browser event the script should be loaded at (load, complete etc)

**Comment by khahina** [comment]
Any resolve in futur ? if dequeue and requeue in defer is your solution perhaps apply it in native will be a better solution ?

**Comment by jeherve** [comment]
@khahina We haven't made progress on this, but you can follow our discussion about this in #8891.
