### ISSUE TITLE
VideoPress: can't access Media > Add New when VideoPress is active.

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5665]
#### Steps to reproduce the issue

1. Install Jetpack 4.4 Beta 4
2. Purchase a Plan for your site.
3. Go to Media > Add New

The Media > Library page is loaded instead. The Media > New page doesn't seem to be accessible anymore.

**Comment by zinigor** [comment]
This was done on purpose in #5590, will need to be investigated and fixed if possible.

**Comment by jeherve** [comment]
Punting to 4.5 for now, but it needs to be fixed, as this will most likely cause conflicts with other plugins that insert content / tools into the uploader. The 2 WordPress media uploaders should remain available imo, even if VideoPress isn't supported in one of them.

**Comment by jeherve** [comment]
This was fixed.
