### ISSUE TITLE
Incorrect links for CTA buttons for VideoPress and SEO tools in plans page

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/jetpack#5668]
See: https://github.com/Automattic/jetpack/pull/5470 for background

On the plans tab, if a user is on the Premium or Professional plan we show a card for VideoPress (in both cases) and a card for SEO Tools (just Pro).

Like backups, spam, and scanning these cards have a button to either configure/setup the feature or else to access it.

For VideoPress and SEO Tools these buttons are currently labelled "To Do" and have incorrect links. 

To do for both:
- If the module is not activated, button needs to activate the feature
- If activated, button needs to link to the appropriate place for using the feature

**Comment by jeherve** [comment]
Assigning back to 4.4; while VideoPress doesn't need to be done right now, SEO Tools should be updated before the release.

**Comment by samhotchkiss** [comment]
Done in #5703
