### ISSUE TITLE
Have images at right stay in the same place horizontally

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#5677]
![image](https://cloud.githubusercontent.com/assets/574752/20368731/8dd067f2-ac12-11e6-9b54-0d4a69e54b1d.png)

**Comment by jeffgolenski** [comment]
@samhotchkiss I don't know what you mean here.

**Comment by samhotchkiss** [comment]
![jumpingjetpacks](https://cloud.githubusercontent.com/assets/574752/20399792/89016044-acaf-11e6-815d-45abb4524351.gif)

**Comment by jeffgolenski** [comment]
Got it. I'm going to experiment with adding a max width to the entire banner though. It doesn't make sense to limit the width of the content but let the entire banner continue on. I'll link the PR shortly.
