### ISSUE TITLE
Add call to action to bottom of plans page

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#5679]
Master Issue: https://github.com/Automattic/jetpack/issues/6135

Plzthx.

**Comment by richardmuscat** [comment]
What? :)

**Comment by samhotchkiss** [comment]
Beau and I were walking through Jetpack, and realized that it seemed a bit
odd that, after reading through the whole plans page in the plugin, you
have to scroll back to the top in order to actually purchase anything

**Comment by MichaelArestad** [comment]
@richardmuscat ideas?

**Comment by richardmuscat** [comment]
@MichaelArestad -- simple version would be to add the same button we have at the top at the bottom.

Better idea might be to redesign the plans page?

**Comment by MichaelArestad** [comment]
@jeffgolenski Let's tackle this in 4.6.

**Comment by dereksmart** [comment]
The most recent design of the plans page includes a CTA to compare plans at the top and bottom of the page.
