### ISSUE TITLE
Change toggle highlight style

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#5681]
The way things work now:
![jetpacktoggle](https://cloud.githubusercontent.com/assets/574752/20369454/4318a4e6-ac16-11e6-8086-a2619bf5a649.gif)

This feels kinda janky, because you get this odd outline that goes away when you click away, then, when you activate/reactivate a feature it gets extra biggened until you click away.

Maybe just changing the outline to a different color would help, says @beaulebens

**Comment by jeherve** [comment]
Closing as duplicate of #4941
