### ISSUE TITLE
calling Jetpack init more then once during load.

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#5684]
It looks like we are calling Jetpack::init() twice in jetpack.php
See https://github.com/Automattic/jetpack/blob/master/jetpack.php#L122
and https://github.com/Automattic/jetpack/blob/master/jetpack.php#L105

I am not sure that is really needed. 

cc: @lezama, @jeherve and @eliorivero 

I am not sure this that the ^ breaks anything. I just wanted to point it out since I kind of things it is a new in 4.4 and it doesn't quite make sense to me. 

I would want to remove 
`add_action( 'init', array('Jetpack', 'init') );`

**Comment by jeherve** [comment]
This was introduced in #4900 (cc @lezama).

The other init was added to fix #3697 (see #3700).

@lezama Could you take a closer look, so we make sure we don't create any big issue when releasing this?

Thanks!

**Comment by lezama** [comment]
I think it won't change the behaviour or performance, as it works like a singleton. Just that we won't  be calling twice `plugin_upgrade();`, I am not sure why we have that call outside of the constructor.

**Comment by lezama** [comment]
Let's remove it for 4.5, so we have more time to detect if it breaks something.

**Comment by eliorivero** [comment]
Yeah, I don't think it won't break anything either but agree with doing it for 4.5. There's also a sentence inside `Jetpack::plugin_upgrade()`:
```
add_action( 'init', array( __CLASS__, 'activate_new_modules' ) );
```
which is quite odd, what is happening now when this action is added inside the action it's supposed to be hooked to as it currently is?

**Comment by jeherve** [comment]
Also reported in #19166, with updated reference links:

--------

First `Jetpack::init` is hooked to `init` action

https://github.com/Automattic/jetpack/blob/c95c00fcb42e2329525e7d2c39bcc75b2e3468ff/projects/plugins/jetpack/load-jetpack.php#L77

then in that method something is hooked into `plugins_loaded`

https://github.com/Automattic/jetpack/blob/c95c00fcb42e2329525e7d2c39bcc75b2e3468ff/projects/plugins/jetpack/class.jetpack.php#L418

As `plugins_loaded` is fired **before** `init`

https://codex.wordpress.org/Plugin_API/Action_Reference#Actions_Run_During_a_Typical_Request

that method will **never** be executed. 😿

**Comment by lezama** [comment]
never say never!
