### ISSUE TITLE
Autoconfiguring akismet works but "fails" if akismet is already installed but not active

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#5685]
Here's what happens: (and it's reproduceable)
![jetpackakismetsadrobot](https://cloud.githubusercontent.com/assets/574752/20370011/83054e58-ac19-11e6-8631-85f3cdb24921.gif)

As you can see, it's working, but it's giving an error message

**Comment by samhotchkiss** [comment]
Similar issue with VaultPress-- it installed and configured successfully, but then gave an error in Calypso

:-(

**Comment by jeherve** [comment]
This seems like the same error that was reported here:
https://github.com/Automattic/wp-calypso/issues/9354

I'll let @ryelle decide which one to keep :)

**Comment by ryelle** [comment]
This should be fixed by this Calypso PR: https://github.com/Automattic/wp-calypso/pull/9485
