### ISSUE TITLE
SEO Tools: title isn't correct on yearly or daily archive pages

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5698]
#### Steps to reproduce the issue

0. Start from a Jetpack site using Jetpack 4.4, a Professional Plan, and the SEO Tools module being active.
1. Go to https://wordpress.com/settings/seo/
2. Pick your site.
3. Add some custom titles.
4. For the archive pages, try the following settings:

![screen shot 2016-11-17 at 14 55 18](https://cloud.githubusercontent.com/assets/426388/20391929/e93198b4-acd5-11e6-9c04-13c2c8eb9718.png)

5. Save your changes.

Let's now check how things look like on your site:
1. Go to `yoursite.com/2012/` -> Your title will be set to `Archives for | My Site Name`
2. Go to `yoursite.com/2012/10` -> Your site title will be set to `Archives for October 2012 | My Site Name`
3. Go to `yoursite.com/2012/10/28/` -> Your site title will be set to `Archives for October 2012 | My Site Name`

While 2) is the expected result, 1) and 3) aren't correct; they should include the date and the year.

cc @vindl

**Comment by samhotchkiss** [comment]
Talked to @vindl, he's going to check it out in a little bit
