### ISSUE TITLE
Protect: Provide a method for logging in when blocked because of a false positive 

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#5705]
Recently, we have been seeing many users with one particular host being locked out of their site, and we also daily respond to other users with other hosts who are also locked out because of server configuration issues. These users then need to contact us so that we can change things on our end. Being locked out of their site is a very frustrating situation for them!

One idea that's been raised before is to create some method for people to get around the block and still log in to their site. One suggestion was to send them an email with a one-time login link, or something along those lines. This issue is being opened to discuss some ideas. So.... discuss! :)

**Comment by jeherve** [comment]
This has now been implemented.
