### ISSUE TITLE
Protect: Wording on blocked screen is unfriendly

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#5707]
I find the wording used to tell someone that they are blocked is unfriendly:

> Your IP (x.x.x.x) has been flagged for potential security violations.

I'd like some suggestions on how to make it friendlier, since often-times it's our users who are blocked because of a false positive. 

This is tangentially-related to https://github.com/Automattic/jetpack/issues/5705

**Comment by jeherve** [comment]
Closing as duplicate of #4216
