### ISSUE TITLE
Make Security Threat UI "Clickable"

### ISSUE THREAD

**Issue by annezazuu** [Automattic/jetpack#5714]
For the security threat UI flow, the current option isn't clickable leaving it very unactionable:

https://cloudup.com/c-C9TDn7T-e

From @rickybanister: "In calypso the compact-notice pattern has the option of a notice-action. In this case I feel like we should add to the notice a ‘fix it’ or ‘get help’ action next to threats found.

If that doesn’t fit within that header we could move it into the body of the card. We could also consider using a red left border on the card like the ‘nudge’ style to indicate that feature requires attention."

**Comment by eliorivero** [comment]
Added in #5714. This will be shipped in the upcoming new settings UI.
