### ISSUE TITLE
Publicize Feature Erasing Post Meta

### ISSUE THREAD

**Issue by BFTrick** [Automattic/jetpack#5718]
When you have the Publicize feature enabled and you create a new WooCommerce coupon it erases all WooCommerce post meta. That means all details about WooCommerce orders are lost.

# Steps to reproduce the issue

1. Install JetPack & WooCommerce
1. Make sure Publicize is on
1. Create a order in WooCommerce
1. Create a new WooCommerce coupon

**All WooCommerce order data is lost.** :(

Screen recording: https://youtu.be/2G1uhZirQM4

If you skip to 1:19 you can see the bug.

You can DM me on the WordPress.org Slack for login details if need more info.

### WordPress Environment ###

Home URL: --see the video for the url--
Site URL: --see the video for the url--
WC Version: 2.6.8
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.9-1ubuntu4.20 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.8
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (2) ###

Jetpack by WordPress.com: by Automattic – 4.3.2
WooCommerce: by WooThemes – 2.6.8

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #11 - /shop/
Cart: #47 - /cart/
Checkout: #52 - /pay/
My Account: #48 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: --I removed this - it's a custom theme--
Version: 1.0
Author URL: --I removed the theme author's website. It's a custom theme--
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 2.4.2
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ❌ Not Declared

### Templates ###

Overrides: –

**Comment by BFTrick** [comment]
I forgot to switch to a default theme in the video. I switched to Twenty Sixteen and the bug is still present.

**Comment by jeherve** [comment]
We add some meta data to posts before it is processed for Publicize, but I'm not sure why this would happen to posts that belong to a Post Type that does not support Publicize.

Just to be sure, could you try to remove `publicize` from the array [here](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-post-types.php#L286), and let me know if it helps?

Thanks!

**Comment by BFTrick** [comment]
Good news! This seems to have been fixed in version 4.4

I updated to 4.4 and couldn't reproduce the bug. I rolled back to 4.3.2 and experienced the bug. Not sure exactly what did it - just encourage people to update to 4.4 and you should solve any potential problems before they happen. 👍

**Comment by jeherve** [comment]
Great news, thanks for the update!

**Comment by BFTrick** [comment]
Just to be thorough - looks like it was fixed with #5381 . 

Hattip @mindsize for finding the commit.
