### ISSUE TITLE
General: Users list layout issues in IE11

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5725]
![screen shot 2016-11-19 at 11 11 32 am](https://cloud.githubusercontent.com/assets/1126811/20457205/840ffd50-ae4b-11e6-8247-1c935a907a19.png)

#### Steps to reproduce the issue

Open IE11 browser. Ensure your site is on latest beta or 4.4-rc2. Go to users list. If your user is connected the row is much taller.

#### What I expected

The row to be the same height as the other rows. Like this:

![screen shot 2016-11-19 at 11 31 01 am](https://cloud.githubusercontent.com/assets/1126811/20457215/b5273656-ae4b-11e6-8fc1-36a1714243ef.png)

#### What happened instead

Tall rows for JP connected users.

**Comment by jeherve** [comment]
Related: #4273

**Comment by MichaelArestad** [comment]
@ebinnion my suspicion is that the SVG needs a width and, more importantly, a height set. You could try either `height: auto` on the SVG or something more explicit.

**Comment by jeffgolenski** [comment]
Yes, it's definitely the height. I'll open a PR for this now.

**Comment by jeffgolenski** [comment]
Fixed in: https://github.com/Automattic/jetpack/pull/5822
