### ISSUE TITLE
Changelog: release post link isn't correct.

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5730]
The changelog includes a link to the release post:
![screen shot 2016-11-21 at 18 02 31](https://cloud.githubusercontent.com/assets/426388/20492358/b2e3df96-b014-11e6-8858-4ab16937ab76.png)

That's not the correct changelog link. We'll want to use `http://wp.me/p1moTy-3FE` when we release 4.4.1

**Comment by zinigor** [comment]
Fixed in 4872f2c, thank you!
