### ISSUE TITLE
Infinite Scroll - type=click - infinity-end not added on last post 

### ISSUE THREAD

**Issue by smutek** [Automattic/jetpack#5737]
#### Steps to reproduce the issue

Working on a custom theme, JetPack infinite scroll is active and set to type=click.

#### What I expected

I expected the `infinity-end` class to be added to the body tag when the last post is loaded, so that I'm able to style my footer appropriately based on the state of the infinite-handle button. 

#### What happened instead

On page load JetPack adds the `infinite-scroll` class to the body tag, on first click of the load more button JetPack adds the `infinity-success` class to the body tag, but on the final post Jetpack does not add the `infinity-end` class.

WordPress: 4.6.1
Active Plugins:
Jetpack by WordPress.com (v4.4) by Automattic
Gravity Forms (v2.1.1) by rocketgenius
Advanced Custom Fields PRO (v5.4.8) by Elliot Condon
Soil (v3.7.0) by Roots
WP Migrate DB Pro CLI (v1.3) by Delicious Brains
WP Migrate DB Pro Media Files (v1.4.6) by Delicious Brains
WP Migrate DB Pro (v1.7) by Delicious Brains

**Comment by georgestephanis** [comment]
Fixed by #6246
