### ISSUE TITLE
Better module icons?

### ISSUE THREAD

**Issue by georgestephanis** [Automattic/jetpack#574]
@MichaelArestad -- @ipstenu reported in the beta group that three modules may be better off with different icons --

* The icon for ‘stats’ is the WP icon. I think dashicons-chart-bar or one of the graph ones would be a better choice. Less repeat.
* Spelling and Grammar icon: dashicons-editor-spellcheck
* Single Sign on – dashicons-groups ?

Thoughts?

**Comment by samhotchkiss** [comment]
Let's just get rid of modules, how about?
