### ISSUE TITLE
Jetpack.com new Personal Plan webpage doesn't look good on mobile

### ISSUE THREAD

**Issue by daniloercoli** [Automattic/jetpack#5741]
I've just received on my mobile device the promo email about the new Personal Plan feature, and the .blog availabilty.  Subject: "Brand new Jetpack features, a much cheaper backup solution, and .blog availability!".
The email contains the link to the new Personal plan page in it - https://jetpack.com/install/personal/ - Unfortunately that page doesn't look good on my mobile browser.
![2016 11 22 21 55 25](https://cloud.githubusercontent.com/assets/518232/20543817/988efae2-b107-11e6-8f44-14755dc3e818.png)
![2016 11 22 21 55 12](https://cloud.githubusercontent.com/assets/518232/20543819/989dd332-b107-11e6-87ac-4081f37c6fda.png)
![2016 11 22 21 55 16](https://cloud.githubusercontent.com/assets/518232/20543818/988f5096-b107-11e6-94d0-b514bd94d781.png)

**Comment by jeherve** [comment]
Thanks for the report!

Closing, as this is related to the Jetpack.com website, and not the Jetpack plugin itself.  This is now tracked internally.
