### ISSUE TITLE
Jetpack doesnt work with qtranslate and default lang prefix enabled

### ISSUE THREAD

**Issue by eitzenbe** [Automattic/jetpack#5743]
#### Steps to reproduce the issue
Install Qtranslate plugin and configure it to not use prefix for default language
connect to jetpack
activate prefix for default language

#### What I expected
still being able to change jetpack settings
and turn off safe mode (actually it shouldnt come up at all)

#### What happened instead
Sharing failed to activate. Error: No route was found matching the URL and request method
and i can not turn off safe mode at all (no option sworks all result in similar error)

interestingly if i hide the prefix jetpack starts workign again without any issue

**Comment by jeherve** [comment]
> Sharing failed to activate. Error: No route was found matching the URL and request method

It seems that Qtranslate also changes the REST API route URLs.

Could you try the following:

<ol>
	<li>Open the Jetpack dashboard page.</li>
	<li><a href="https://codex.wordpress.org/Using_Your_Browser_to_Diagnose_JavaScript_Errors#Step_3:_Diagnosis">Open your browser console</a></li>
	<li>Click on the Network tab</li>
	<li>Refresh the page.</li>
<li>Try to activate a module.</li>
	<li>If you see any lines in red inside the browser console, click on them. A new panel should appear on the right.</li>
	<li>Click on the "Response" tab in that new panel.</li>
	<li>Copy the message displayed there.</li>
	<li>Paste it here.</li>
<li>Also paste the URL used for the request. Does that request URL match your WordPress installation URL, or does it use the language prefix?</li>
</ol>

Possibly related: https://github.com/qTranslate-Team/qtranslate-x/issues/427

**Comment by richardmtl** [comment]
Another report regarding Safe Mode in 2932219-t (and I think there have been others recently, but I haven't handled them personally).

**Comment by jeherve** [comment]
Closing in favor of #5793
