### ISSUE TITLE
API: Fatal Error since 4.4

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5746]
cc @seear I believe this may have been introduced in #5392, since you changed the arguments passed to `wp_remote_request()`.

In [this forum thread](https://wordpress.org/support/topic/updated-jetpack-to-latest-version-now-errors/), the site owner reported the following fatal error:

```
Fatal error: Uncaught TypeError: Argument 1 passed to Requests_Cookie_Jar::register() must be an instance of Requests_Hooker, instance of Requests_Hooks given, called in /home/ridestok/public_html/wp-includes/class-requests.php on line 592 and defined in /home/ridestok/public_html/wp-includes/Requests/Cookie/Jar.php:120 Stack trace: #0 /home/ridestok/public_html/wp-includes/class-requests.php(592): Requests_Cookie_Jar->register(Object(Requests_Hooks)) #1 /home/ridestok/public_html/wp-includes/class-requests.php(363): Requests::set_defaults(‘https://jetpack…’, Array, ‘<?xml version=”…’, ‘POST’, Array) #2 /home/ridestok/public_html/wp-includes/class-http.php(369): Requests::request(‘https://jetpack…’, Array, ‘<?xml version=”…’, ‘POST’, Array) #3 /home/ridestok/public_html/wp-includes/http.php(153): WP_Http->request(‘https://jetpack…’, Array) #4 /home/ridestok/public_html/wp-content/plugins/jetpack/class.jetpack-client.php(187): wp_remote_request(‘https://jetpack…’, Array) #5 /home/ridestok/public_html/wp-content in /home/ridestok/public_html/wp-includes/Requests/Cookie/Jar.php on line 120
```

**Comment by seear** [comment]
@jeherve I'm taking a look

**Comment by seear** [comment]
It doesn't _seem_ to be related to the change in #5392, which allowed two additional keys in the args array accepted by `Jetpack_Client::remote_request()`.

The actual Fatal is interesting:
```
Fatal error: Uncaught TypeError: Argument 1 passed to Requests_Cookie_Jar::register() must be an instance of Requests_Hooker
, instance of Requests_Hooks given
```

Yet `Request_Hooks` is [declared in core](https://github.com/WordPress/WordPress/blob/98e8bf7ba276bd661909bcde9f08775ed49a6deb/wp-includes/Requests/Hooks.php#L15) as implementing `Request_Hooker`. Possibly something external is interfering with that?

**Comment by zinigor** [comment]
It looks like this is not an issue with Jetpack according to the linked forum thread. Please reopen if there are additional suspicions.
