### ISSUE TITLE
Sharing: Email pop-up in an off position on RTL sites.

### ISSUE THREAD

**Issue by lamdayap** [Automattic/jetpack#5752]
#### Steps to reproduce the issue

- Set site to RTL
- Click on the email sharing button
- Popup will come on aligned to the far right, outside of the content area, this is causing users with lower resolutions not being able to see the popup as it's cut-off. 

#### What I expected

The popup to align on the right, inside the content area

**Comment by lamdayap** [comment]
Related #5360 and #5129

**Comment by FreedomFighterSparrow** [comment]
This is still occurring - I'm currently running WordPress 4.7.5–he_IL with JetPack. The related issues mentioned by @lamdayap seem to be resolved.
Is there some update on this?

**Comment by jeherve** [comment]
@FreedomFighterSparrow No updates, but we'll comment here as soon as we make progress on this.

**Comment by jeherve** [comment]
This can now be closed since we now use mailto instead of a custom email sharing button (see #24040).
