### ISSUE TITLE
Add Twitch to the Social Media Icons widget

### ISSUE THREAD

**Issue by davoraltman** [Automattic/jetpack#5755]
Would be nice to add Twitch to the [list](https://github.com/Automattic/jetpack/blob/master/modules/widgets/social-media-icons.php#L49).

Requested in 2931171-t

**Comment by nabaxo** [comment]
I can literally just give you the code. It's just two lines that I have to patch in manually every time you update.

**Comment by AjkP** [comment]
Made a PR for this.
