### ISSUE TITLE
Multisite/Protect: Missing padding on MS admin banner

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#5758]
If you activate Protect on a single site within a Multisite network, you'll get a banner within the admin telling you that you need to activate Jetpack/Protect on all sites. It's missing padding, so it looks pretty ugly:

![screen shot 2016-11-19 at 5 01 04 pm](https://cloud.githubusercontent.com/assets/108942/20645514/cc1f2ba0-b42e-11e6-9380-6210ad441807.png)

**Comment by jeherve** [comment]
Closing as duplicate of #4794
