### ISSUE TITLE
Content within recipe shortcode does not obey site language.

### ISSUE THREAD

**Issue by jenhooks** [Automattic/jetpack#5768]
On WordPress.com, the "Servings", "Time", "Difficulty", and "Print" options (and a few others) in the recipe shortcode obey the site language, as seen in the screenshot below. I made this post on my WordPress.com blog, initially in English. Then, I set the site language to French:

![wpcom_recipe](https://cloud.githubusercontent.com/assets/7585054/20682791/67581a20-b577-11e6-9618-fa141086b0de.png)

However, on a Jetpack site, switching to a different language doesn't change these options - they remain in English:

![jetpack_recipe](https://cloud.githubusercontent.com/assets/7585054/20682802/7deff58c-b577-11e6-8ff8-c4b459162f7a.png)

Reference: 2936993-t

**Comment by jeherve** [comment]
I can't seem to reproduce on my end. 

![screen shot 2016-12-02 at 14 30 34](https://cloud.githubusercontent.com/assets/426388/20835717/4ed90838-b89c-11e6-9333-a2a1d9b079c0.png)
![screen shot 2016-12-02 at 14 31 28](https://cloud.githubusercontent.com/assets/426388/20835718/510c2770-b89c-11e6-982d-1d8eb72ac67f.png)


Closing as `invalid`.
