### ISSUE TITLE
Admin Page: can't unset subscription options

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5769]
#### Steps to reproduce the issue

1. Go to Jetpack > Settings > Engagement.
2. Open the Subscriptions card.
3. Uncheck the 2 subscription options:

![screen shot 2016-11-28 at 22 27 07](https://cloud.githubusercontent.com/assets/426388/20686644/d0663118-b5b9-11e6-8e37-79df08f4c335.png)

4. Save changes. You'll get a success message, it's all good.
5. Reload the page. The options are back.

![screen shot 2016-11-28 at 22 28 03](https://cloud.githubusercontent.com/assets/426388/20686682/f10cd7b4-b5b9-11e6-82d8-938f2149cc9c.png)

Reported here:
https://wordpress.org/support/topic/unable-to-disable-show-a-follow-blog-in-subscriptions/

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/unable-to-disable-follow-blog/

**Comment by eliorivero** [comment]
I can't reproduce this in latest master.

**Comment by jeherve** [comment]
It's still a problem for me:

![screen recording 2016-12-15 at 03 03 pm](https://cloud.githubusercontent.com/assets/426388/21226837/a9ea5a48-c2d7-11e6-9e29-0836da74d4c2.gif)

**Comment by katykeck** [comment]
Is there any timeframe for this update? I am having the same problem disabling the follow blog field - I use mailchimp and don't want to add subscribers via wordpress.org. I do want Follow Comments however. Thx.

**Comment by jeherve** [comment]
@katykeck We don't have a fix yet, but until it's fixed you can go to Settings > Discussion in your dashboard. If you scroll down to the bottom of the page, you'll find the same 2 options and will be able to disable them from there.

**Comment by katykeck** [comment]
Thanks - that worked!

KATY KECK


#PalatePassionPurpose
Here: 212-246-2171
There: 616-296-9048
Everywhere: 917-209-4801
Blog: PalatePassionPurpose.com <http://katykeck.com/blog/>
Web: KatyKeck.com

**Comment by jeherve** [comment]
Fixed in #5461
