### ISSUE TITLE
Admin Page: Hovercard configuration description not correct

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5771]
#### Steps to reproduce the issue
- Go to Jetpack admin page

#### What I expected

The "Gravatar Hovercards" card to point me to where I could configure hovercards to work or not work. I was able to find the settings on the `Settings -> Discussion` page.

![screen shot 2016-11-28 at 4 48 25 pm](https://cloud.githubusercontent.com/assets/1126811/20689393/d18a32d0-b58a-11e6-8934-d14ab0aa3a49.png)

#### What happened instead

Jetpack lied to me. 😄 

![screen shot 2016-11-28 at 4 48 42 pm](https://cloud.githubusercontent.com/assets/1126811/20689404/dce1fea6-b58a-11e6-8a9e-4af3e8bb917e.png)

**Comment by jeherve** [comment]
@ebinnion I believe this was done on purpose, as you don't need 2 forms for the same setting: #4997

Could you confirm that the Gravatar Hovercards can be activated or deactivated without having to touch the setting under Settings > Discussion?

**Comment by samhotchkiss** [comment]
Closing as this should be handled with the new settings UI in 4.6
