### ISSUE TITLE
Verification Tools: strip meta tag and only keep verification code on save.

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5782]
#### Steps to reproduce the issue

<ol>
	<li>Log in to <a href="https://www.google.com/webmasters/verification/home?hl=en">https://www.google.com/webmasters/verification/home?hl=en</a> with your Google account.</li>
	<li>Click on "Add a property"</li>
	<li>Enter your blog address.</li>
	<li>Click the <strong>Continue</strong> button.</li>
	<li>Click on the "Alternate Methods" tab.</li>
	<li>The option you want is "HTML Tag."</li>
	<li>You'll see a line of&nbsp;HTML code like this:
<code>&lt;meta name="google-site-verification" content="rc2RXSkjV5rz9P2s2hTwdDsnwTu4tD-gmruKUrqBGjs" /&gt;</code></li>
	<li>Copy the entire code.</li>
	<li>Leave the verification page open and go to your blog dashboard (in a new tab/window).</li>
	<li>Open the <strong>Jetpack → Settings → Engagement</strong> page&nbsp;and look for the <strong>Site Verification</strong> card.</li>
	<li>Paste the code into the <strong>Google</strong> field.

<img width="793" alt="google-search-console-verification" src="https://cloud.githubusercontent.com/assets/426388/20750228/0b2c2a36-b6f6-11e6-87d3-13c41d8dc741.png">

</li>
	<li>Click on <strong>Save Changes</strong>.</li>
</ol>

#### What I expected

I expected `<meta name="google-site-verification" content="rc2RXSkjV5rz9P2s2hTwdDsnwTu4tDgmruKUrqBGjs" />` to be stripped to just `rc2RXSkjV5rz9P2s2hTwdDsnwTu4tDgmruKUrqBGjs`, just like it's done under the Tools menu in your dashboard, in the old Site Verification Tools fields.

#### What happened instead

The whole meta tag was saved, instead of just the code.

**Comment by csonnek** [comment]
I had a report from another user in 3163848-t confused by the instructions in the module to enter the entire code when it will only work when pasting only the content key. 

Our support documentation already refers to only pasting the content key from the meta tag, but fixing this in the administration screens itself would be a huge improvement.

**Comment by joendotcom** [comment]
Customer made same error in 3170879-t.

**Comment by csonnek** [comment]
Had two tickets today where the user was trying to enter the full meta tag into the field instead of the content value: 779530-zen and 781135-zen

**Comment by csonnek** [comment]
Another: 875979-zen

**Comment by jeherve** [comment]
Fixed in #10040
