### ISSUE TITLE
IDC / WPML: need to exclude WPML sites from current IDC process

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5793]
The way WPML maps domains is a little different to the way WPMU / multisite maps domains. The way a site is configured with WPML is:

1. Install a single non-multisite version of WordPress.
2. Install WPML
3. Decide whether WPML separates different language sites as subdomains,
subdirectories or mapped domains.
4. Even if you choose to handle each site through a different domain, you still manage each site from a single dashboard. This causes IDC issues.

Related ticket: 2940901-t

**Comment by jeherve** [comment]
Until this is fixed, one can disable our IDC checks with the following:

1. `define( 'JETPACK_SYNC_IDC_OPTIN' , false );` in wp-config.php
2. `add_filter( 'jetpack_sync_idc_optin', '__return_false' );` in a functionality plugin.

**Comment by jeherve** [comment]
This also applies to Qtranslate X sites.

**Comment by ebinnion** [comment]
Related: #5852

**Comment by jeherve** [comment]
Also reported in 2964257-t

**Comment by ebinnion** [comment]
#5852 should fix this. The idea behind that PR is that we'll begin syncing the raw value (direct from DB or from constant) to WPCOM. Then, we can add filters to the home and siteurl that we sync back to provide first-class support for some number of plugins. That PR adds support for two domain mapping plugins. But, we should be able to test WPML and Qtranslate to see if they're supported as well.

**Comment by vukvukovich** [comment]
Hi guys,

Any news related to this issue?

**Comment by ebinnion** [comment]
Hi @vukvukovich –

I'm on vacation until next week. When I get back, I intend on testing #5852 to verify that it fixes this issue.

**Comment by madhattermattic** [comment]
I have a user who is having a similar issue, but they are using a plugin called "Sublanguage."

#3020744-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/jetpack-conflict-with-qtranslatex-plugin/

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/jetpack-safe-mode-2/

**Comment by lamdayap** [comment]
3116412-t

**Comment by aheckler** [comment]
Came up in 3148287-t. This user originally had a plan here:

https://wordpress.com/wp-admin/network/sites.php?s=122498853&submit=Search+Sites

... but then they cycled the connection and got a new shadow site here:

https://wordpress.com/wp-admin/network/sites.php?s=126986204&submit=Search+Sites

... but without a plan. :(

**Comment by jenhooks** [comment]
Reported in 3189677-t.

**Comment by oskosk** [comment]
Closing as #5852 is merged already.
