### ISSUE TITLE
Customizer: Background color disappears when clicking preview responsive icons in Chrome

### ISSUE THREAD

**Issue by briancolinger** [Automattic/jetpack#5797]
#### Steps to reproduce the issue
Using the Chrome browser, go to the Customizer screen and click on Additional CSS.
Change the background color of the site and save the changes.
Click on the preview responsive icons, doesn't seem to matter which one.
The background color disappears.

#### What I expected
I expected that the background color would stay the same.

#### What happened instead
The background color disappeared.

This is not limited to the background color, if you change font sizes you can see the same behavior.

If you disable the Jetpack plugin this issue does not happen.

This only seems to happen in Chrome. Testing in Firefox and Safari works as expected.

![jetpack disappearing css](https://cloud.githubusercontent.com/assets/8125655/20869385/70c42884-ba3f-11e6-8e60-0e4fff126d46.gif)

**Comment by oskosk** [comment]
Closing as this seems to be working now. (See gif below)

![background](https://user-images.githubusercontent.com/746152/31896661-b9912fb8-b7ea-11e7-9e0f-4c54f3154452.gif)
