### ISSUE TITLE
Dashboard: All "Help" links hidden in wp-admin when Jetpack is active

### ISSUE THREAD

**Issue by csonnek** [Automattic/jetpack#5800]
User in 2944012-t reporting that WordPress Help links are being hidden wp-admin wide when Jetpack is active. 

With Jetpack deactivated (wp-admin dashboard): 
<img src='http://d.pr/i/9aky+'>

With Jetpack activated (same screen):
<img src='http://d.pr/i/kexQ+'>

All help links are being hidden due to this CSS in Jetpack: 

`#contextual-help-link-wrap {
	display: none;
}`

If this is meant to hide the Help links on Jetpack Admin pages, please fix it so it's not hiding the links elsewhere - like on Media pages or the Dashboard, for example.

**Comment by dereksmart** [comment]
Will be fixed in 4.4.2 via #5783
