### ISSUE TITLE
Jetpack conflicts with WP All Export.

### ISSUE THREAD

**Issue by jenhooks** [Automattic/jetpack#5802]
There appears to be a conflict between Jetpack and the [WP All Import](https://wordpress.org/plugins/wp-all-import/) and [WP All Export](https://wordpress.org/plugins/wp-all-export/) plugin.

Some Jetpack users have reported `cURL error 28: Operation timed out after 1000 milliseconds with 0 bytes received jetpack` [here](https://wordpress.org/support/topic/jetpack-could-not-contact-wordpresscom-register_http_request_failed-10/#post-8225692) and [here](https://wordpress.org/support/topic/jetpack-sync-filling-up-the-wp_options-table/#post-8255491). This problem is also reported in 2923574-t.

The current hypothesis is that this plugin is causing Jetpack to fill up the `wp_options` table, perhaps by blocking the rows from being deleted as new ones are added?

**Comment by enejb** [comment]
Any ideas how we can reproduce this bug?

**Comment by jenhooks** [comment]
@enejb - I saw that you'd tried to reproduce, but were unsuccessful. I've reached out to the user in 2923574-t to see if they could give us more details or guidance on how to reproduce.

**Comment by alexjgustafson** [comment]
User's explanation:

> I ran into the cURL problem when I tried to connect Jetpack to
> WordPress.com while WP All Export (and Import) were activated. Once I
> deactivated WPAE(&I) I no longer got the error and was able to connect.

Steps therefore seem to be: 
1) Activate WPAE(&I)
2) Attempt to connect Jetpack to WordPress.com

May be more of a Team Luna question?

They've also stopped using Jetpack on the site in question citing business concerns; so from here on it seems like this issue is more for posterity's benefit.

**Comment by hellosubscription** [comment]
i don't have any hypotheses but I can confirm this conflict on my site as well.

**Comment by Genyus** [comment]
Likewise, I was able to resolve this error by disabling the WPAE/I plugins

**Comment by bradydan** [comment]
I've just had the same issue, and deactivating WP All Export removed the error (WP All Import remained activated)

**Comment by aheckler** [comment]
3115513-t

**Comment by nicholasdrayer** [comment]
I had the same problem, I deactivated WP Allimport and All export, Jetpack connected again. I then Re-activated WP allimport, and it is still working.  I have not re-activated WP allexport.
I did look at the debug of Jetpack, and it contained an erroneous error message, saying that the site's A record could not be resolved. Which is rubbish :-).

**Comment by joendotcom** [comment]
3169556-t

**Comment by aheckler** [comment]
3188084-t

**Comment by aheckler** [comment]
possibly 3102583-t

**Comment by aheckler** [comment]
possibly 3239833-t

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
