### ISSUE TITLE
Holiday Snow: Needs notifications when activating/deactivating

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/jetpack#5807]
When the Holiday Snow module is activated or deactivated, there are no notifications like there are for other modules

#### Steps to reproduce the issue

1) Visit `admin.php?page=jetpack#/appearance`
2) Activate or deactivate "Holiday Snow" module
3) Note that no notifications appear in the top-right corner of the screen

#### What I expected

To see a notification that the module was activating or deactivating

#### What happened instead

No notification like what I get with other modules.
Example:
![snow-nonotif](https://cloud.githubusercontent.com/assets/933450/20942588/faf54d68-bbc9-11e6-9382-11e22f4b2aef.gif)

Tested on 4.4.2-beta

**Comment by samhotchkiss** [comment]
Closing as this should be handled with the new settings UI in 4.6

**Comment by gravityrail** [comment]
This feature is removed in Jetpack 6.0.
