### ISSUE TITLE
PHP Warning:  Illegal string offset 'id' in grunion-contact-form.php:1288

### ISSUE THREAD

**Issue by slaFFik** [Automattic/jetpack#5810]
> [06-Dec-2016 20:58:42 UTC] PHP Warning:  Illegal string offset 'id' in /wp-content/plugins/jetpack/modules/contact-form/**grunion-contact-form.php on line 1288**
> [06-Dec-2016 20:58:43 UTC] PHP Warning:  Illegal string offset 'id' in /wp-content/plugins/jetpack/modules/contact-form/**grunion-contact-form.php on line 1288**

https://github.com/Automattic/jetpack/blob/master/modules/contact-form/grunion-contact-form.php#L1288

**Comment by jeherve** [comment]
I can't seem to reproduce on my end. Could you tell me more about your setup, as well the steps you follow to trigger that warning on your site?

**Comment by slaFFik** [comment]
The only thing I did - tried to upgrade to WordPress 4.7 (has some issues
with Siteground and their SuperCacher, more details here:
https://twitter.com/slaFFik/status/806231426085560320).
Then visited several pages on front-end (including the one, that has the
form).

**Comment by jeherve** [comment]
Do you still see the errors today? If so, could you try to deactivate each one of your plugins, starting with SuperCacher, and let me know if you find a conflicting plugin?

Thanks!

**Comment by neo22s** [comment]
Hello,

same issue here... disabled all plugins except woocommerce and jetpack. Still error :(


Warning: Illegal string offset 'id' /wp-content/plugins/jetpack/modules/contact-form/grunion-contact-form.php on line 1288


PHP 7.1

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/contact-forms-in-4-4-2-not-working/

**Comment by neo22s** [comment]
Using contactform7...

**Comment by jeherve** [comment]
It appears the bug is limited to PHP 7.1. We'll see about including #6102 in Jetpack 4.5.1 to fix this.

**Comment by jeherve** [comment]
#6106

**Comment by jeherve** [comment]
Fixed in #5821
