### ISSUE TITLE
Customizer: Subscriptions widget has weird layout when selected

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5811]
#### Steps to reproduce the issue
- Update to WordPress 4.7
- Update to Jetpack 4.4.2

#### What I expected
- The subscriptions widget to stay within the widget sidebar.

#### What happened instead

The subscriptions widget popped out on to my site content.

![screen shot 2016-12-06 at 3 38 39 pm](https://cloud.githubusercontent.com/assets/1126811/20944938/fa588c0c-bbca-11e6-9c4b-2b942aeeab11.png)

I wondered if it was just because the widget was at the top of the list, but when I put a different widget at the top, that widget stayed inline as I expected.

![screen shot 2016-12-06 at 3 38 49 pm](https://cloud.githubusercontent.com/assets/1126811/20944971/16789238-bbcb-11e6-81e2-0256ba36454e.png)

**Comment by jeffgolenski** [comment]
I honestly thought this was intentional when I saw it as well. My screen wasn't tall enough so I thought things moved to the side when that occurred.

**Comment by eliorivero** [comment]
Taking this over. Working on a few fixes for the widgets.
