### ISSUE TITLE
Custom CSS / Mobile Theme: CSS is not added to minileven

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5815]
#### Steps to reproduce the issue

0. Start with a site using WP 4.7, JP 4.4.2, and the Mobile Theme is enabled.
1. Go to Appearance > Edit CSS.
2. Add some custom CSS.
3. Save your changes.
4. Notice the CSS loaded on your site.
5. Load your site on mobile. Jetpack's Mobile Theme is loaded.
6. The Custom CSS isn't loaded anywhere on mobile.

Although Minileven calls `wp_head`, I assume there might be a problem with the way we define the active theme with the `option_stylesheet` and `option_template` filters.

This is a big issue for all site owners who previously used Jetpack's Custom CSS module to customize the look of the Mobile Theme, thanks to the option that was provided in the Custom CSS editor to load Custom CSS on mobile as well.
Right now, the only options they have to customize that mobile theme is to edit core plugin files or create their own plugin to load a custom stylesheet.

Until this gets fixed, a quick fix is to install this little plugin:
https://github.com/jeherve/jetpack-addons/archive/mobile-custom-css.zip

Reported here:
https://wordpress.org/support/topic/site-title-color-on-jetpack-mobile-changed-after-update-it-is-not-invisible/

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/in-web-page-website-is-working-but-in-mobiles-css-is-not-working-css-and-images/

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/additional-custom-css-and-jetpack-mobile-theme/

**Comment by pmciano** [comment]
Reported here: 2977121-t

**Comment by ebinnion** [comment]
Reported in 3039118-t as well.

> Although Minileven calls wp_head, I assume there might be a problem with the way we define the active theme with the option_stylesheet and option_template filters.

This is happening because, with the WordPress 4.7 update, custom CSS is now stored theme specific. So, when we switch the theme to `minileven` WordPress is now looking for CSS changes to `minileven` instead of the site's usual active theme.

**Comment by danjjohnson** [comment]
Reported in 3072574-t

**Comment by brbrr** [comment]
Re-tested with Jetpack 6.1. Issue is still there.

**Comment by jeherve** [comment]
Also reported in 1844995-zen

**Comment by patsar** [comment]
Any update? The problem still exists in Jetpack 7.8.

**Comment by jeherve** [comment]
We do not have any updates at the moment, but we'll update this issue whenever we next iterate on the Mobile Theme feature in Jetpack.

Until then, I would recommend switching to a responsive theme if possible, and deactivating Jetpack's Mobile Theme feature.

**Comment by KokkieH** [comment]
Another question related to this in https://wordpress.org/support/topic/customizing-mobile-tag-style/
