### ISSUE TITLE
Admin Page: Infinite Scroll: Add notice when current theme does not support infinite scroll

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5824]
Should we add a notice to the Infinite Scroll card when the current theme does not support infinite scroll?

When I updated to WordPress 4.7 and then tried to use Infinite Scroll, I noticed that TwentySeventeen doesn't support IS. 😢 

The issue I ran into is that I thought Jetpack was broken for 15+ minutes while I figured out what was wrong. Especially since I assumed infinite scroll would be supported in a core theme.

**Comment by jeherve** [comment]
+1. That's a regression, as we used to display a notice in the old Settings screen:
https://github.com/Automattic/jetpack/blob/8d13e90a72b1afad48a6d3c380019c4834c922f3/modules/module-info.php#L561-L581

**Comment by jeffgolenski** [comment]
Yes, we should be displaying that notice that Jeremy mentioned above!
