### ISSUE TITLE
Sharing: add Google+ sharing counts

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#584]
Twitter, Facebook, and LinkedIn have their own custom sharing counts displayed when using one of the non-official sharing buttons:
https://github.com/Automattic/Jetpack/blob/master/modules/sharedaddy/sharing.js#L7

It'd be nice to do the same with Google+ if possible.

Edit: it is possible to get sharing counts from Google+, but you need an API key:
https://gist.github.com/jonathanmoore/2640302

Reported [here](http://wordpress.org/support/topic/google-like?replies=2)

**Comment by jenhooks** [comment]
Also requested in #2153079

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/jp-v35-sharing-pinterest-button-overlay?replies=3&view=all#post-6866778

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/facebook-share-shows-0-even-after-2-shares?replies=3&view=all

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/google-facebook-share-buttons-not-showing-count?replies=5&view=all#post-6913213

**Comment by jeremeylduvall** [comment]
Also requested here:

https://en.forums.wordpress.com/topic/facebook-connection-fails-to-show-the-number-of-shares?replies=9

**Comment by clifgriffin** [comment]
+1

**Comment by samhotchkiss** [comment]
Moved into internal tracking system for further attention

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/sharing-counters-on-share-buttons-not-working?replies=1&view=all

**Comment by jeherve** [comment]
Also suggested in 2433381-t

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/count-share-not-work-until-latest-update?replies=5&view=all#post-7751114

**Comment by kristianserrano** [comment]
If we can't get counts consistently across share icons, can we at least have an option to disable counts?

**Comment by jeherve** [comment]
@kristianserrano This should help you:
http://jeremy.hu/jetpack-remove-the-share-counts-from-the-sharing-buttons/

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/jetpack-sharing-button-issue

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/jetpack-doesnt-show-count-of-google-and-twitter?replies=1&view=all

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/sharing-social-share-counts-are-gone/

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/google-problems/
