### ISSUE TITLE
Translation minor issue with subscriptions

### ISSUE THREAD

**Issue by d8vjork** [Automattic/jetpack#5848]
In jetpack-es_ES.po I can see:

> Success! An email was just sent to confirm your subscription. Please find the email now and click activate to start subscribing.

And in modules/subscriptions.php (at line 984):

> Success! An email was just sent to confirm your subscription. Please find the email now and click 'Confirm Follow' to start subscribing.

So, the translation can't show correctly.

**Comment by jeherve** [comment]
We don't really use the .po files anymore, as Jetpack now uses translation packs. You can contribute translations [here](https://translate.wordpress.org/locale/es/default/wp-plugins/jetpack).

If you'd rather use custom translation files, you can also download a fresh .po file from the page above.
