### ISSUE TITLE
Sync: Can cause fatal errors related to object unserialization protection

### ISSUE THREAD

**Issue by dd32** [Automattic/jetpack#5858]
#### Steps to reproduce the issue
Install & configure the SupportFlow plugin, or another plugin such as <a href="https://gist.github.com/dd32/c7b1e603b43323e8b0f76b7921f08724">this minimal untested example</a> and do something to trigger a taxonomy sync.

Jetpack Sync will attempt to store a serialized version of the output of `get_taxonomies()` into the database, upon deserialization, it'll attempt to re-create the objects and hit the magic `__wakeup()` methods and cause the process to die. It appears that this process is related to `jetpack_sync_callable` (whatever that is).
I suspect this also applies to other Sync processes; but I haven't run into them yet.

This currently causes make.wordpress.org/training to be unavailable often due to the site using the SupportFlow plugin, resulting in something like this: https://cloudup.com/cFv1lr6WVda (Note: The trace is what I've added to `wp_die()` to work out where it was coming from).

#### What I expected

I expected that Sync would not store a massive blog of data which includes PHP callbacks into the database. I expected that Sync would only store a reference to the data it needs to know in order to sync the change. I expected that Sync would not need to persist data such as `$taxonomies` between pageloads, as WordPress should be handling that for it.

**Comment by iandunn** [comment]
I'm still seeing this happen on WordCamp.org. For example, if I run `wp cron event run jetpack_sync_cron --url={site that has SupportFlow active}`

Backtrace summary: `shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, Jetpack_Sync_Sender->do_sync, Jetpack_Sync_Sender->do_sync_and_set_delays, Jetpack_Sync_Sender->do_sync_for_queue, Jetpack_Sync_Queue->checkout_with_memory_limit, maybe_unserialize, unserialize, SupportFlow->__wakeup`

**Comment by enejb** [comment]
@iandunn Can you see if this has been fixed with Jetpack now. I think it was should have been fixed with https://github.com/Automattic/jetpack/commit/14220c75baaf074ce7d1556060596790976db11c 
Feel free to reopen it if this is not the case.
