### ISSUE TITLE
Related Posts: display Customizer options after default options

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5885]
Right now, The "Related Options" is displayed above Menus, Widgets, Static Front Page, and Additional CSS.

![screen shot 2016-12-15 at 15 29 38](https://cloud.githubusercontent.com/assets/426388/21227721/68ad0446-c2db-11e6-8738-c459de413617.png)

Since Related Posts are not handled by Core, I expected the option to appear after all the core options.

@eliorivero What do you think?

**Comment by eliorivero** [comment]
Makes sense, done here https://github.com/Automattic/jetpack/pull/5915
