### ISSUE TITLE
Related Posts: Customizer headline label is not translated

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5886]
#### Steps to reproduce the issue

1. Enable Related Posts on a site using a localized version of WordPress, e.g. French, but where your user uses WordPress in English in the dashboard.
2. Go to Appearance > Customize
3. Open the Related Posts tab.
4. Although I didn't expect the text to be translated yet, the headline label ("Related") should match what's actually displayed on the page, i.e. the translated string.

cc @eliorivero

**Comment by eliorivero** [comment]
I'm not sure if I understand what you mean. Both strings are available for translation
https://github.com/Automattic/jetpack/blob/master/modules/related-posts/class.related-posts-customize.php#L163
https://github.com/Automattic/jetpack/blob/master/modules/related-posts/jetpack-related-posts.php#L277
I tested having english theme in front end, and spanish WP Admin. The string that I see in the preview is the same than in the input field.
Can you explain it further?

**Comment by jeherve** [comment]
I guess a screenshot should have made things easier :) Sorry about that.

- Site language set to French.
- Profile language set to English US

![screen shot 2016-12-16 at 15 07 15](https://cloud.githubusercontent.com/assets/426388/21265365/5cc8c626-c3a1-11e6-8b1c-8fb1256e27a7.png)
