### ISSUE TITLE
Milestone Widget: date field is not formatted properly

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5889]
#### Steps to reproduce the issue

1. Go to Appearance > Widgets in your dashboard.
2. Drag the Milestone widget into the sidebar.

![screen shot 2016-12-15 at 16 09 56](https://cloud.githubusercontent.com/assets/426388/21229223/1f53687a-c2e1-11e6-94b0-68579fd184c0.png)

Now repeat the same operation in the customizer:

![screen shot 2016-12-15 at 16 11 46](https://cloud.githubusercontent.com/assets/426388/21229241/32b829e6-c2e1-11e6-93fa-60843c9ba85f.png)

cc @dereksmart

**Comment by eliorivero** [comment]
I'll take over this. I spotted it and I'm working on a few fixes for the widgets.

**Comment by dereksmart** [comment]
Deployed styling fixes to wpcom in r147417-wpcom

Jetpack patch incoming
