### ISSUE TITLE
Authors Widget: add default styling

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5891]
By default, the Authors Widget doesn't look great. It looks kinda broken:

![screen shot 2016-12-15 at 16 25 43](https://cloud.githubusercontent.com/assets/426388/21229839/31aaa9fa-c2e3-11e6-828f-3ae0f6bb9a72.png)

**Comment by dereksmart** [comment]
If we add custom styles to these, we'll need to be careful in overwriting css that themes may have already (like in twentyfifteen), and also that we don't overwrite any styles that have been customized for dotcom sites.

**Comment by lancewillett** [comment]
Could the widget ship with its own default styles? I don't think it needs to be theme-specific. At least getting rid of bullets and basic spacing should be in the widget itself — not theme-dependent.

**Comment by lancewillett** [comment]
@jeherve Can you indicate which theme you were using? (Does it look OK on other themes?)

**Comment by eliorivero** [comment]
@lancewillett the theme in Jeremy's image is TwentyEleven. Looks good now with the new general styles, feel free to test them.

**Comment by lancewillett** [comment]
Nice work, @eliorivero. 👍 :shipit:
