### ISSUE TITLE
VideoPress: no feedback when uploading a video via Media > Library

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5899]
#### Steps to reproduce the issue

0. Start with a site running Jetpack Professional
1. Go to Jetpack > Settings, and enable VideoPress
2. Go to `/wp-admin/upload.php?action=add-new`
3. Either drag a video, or click on the "Select Files" button.
4. Nothing happens. My video is not uploaded.
5. Try again.
6. Try again.
7. Give up. Go to Posts > Add New, start writing a post.
8. Go to Add Media to upload the video from there.
9. See 3 VideoPress videos in my library. It turned out it worked, but I had no way of knowing it from the Media Library page.

**Comment by dbtlr** [comment]
Don't use `action=add-new` it causes weird things to happen.

**Comment by dbtlr** [comment]
I cannot replicate this error right now. This is the behavior I see normally when there is a JavaScript error on that page. Could you check the console logs for any errors that may be occurring?

**Comment by jeherve** [comment]
I can't reproduce anymore either :(

Closing.
