### ISSUE TITLE
Ads: "View your earnings" link is marked as external but opens in same window

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5902]
#### Steps to reproduce the issue

0. Start from a Jetpack site with an active Ads module.
1. Go to Jetpack > Settings > Engagement
2. Open the Ads card:

![screen shot 2016-12-15 at 19 16 09](https://cloud.githubusercontent.com/assets/426388/21236342/f42dc1a8-c2fa-11e6-9207-0e49e49aca30.png)

3. Although the link is marked as external, if you click on it it opens in the same window.

**Comment by jeherve** [comment]
The same applies to VaultPress links under Security.

**Comment by dbspringer** [comment]
This uses the module `ExternalLink from 'components/external-link'`, perhaps we should consider updating it to open in a `target="_blank"` or change the icon?

**Comment by dereksmart** [comment]
This happens in a few other places around the admin as well: 

![screen shot 2017-01-12 at 10 11 43 am](https://cloud.githubusercontent.com/assets/7129409/21895155/ad0e312a-d8af-11e6-8f4e-68c80e918f9b.png)

@MichaelArestad suggestions on a different icon? I know how you feel about new tabs ;)

Either way, punting to 4.5.1

**Comment by MichaelArestad** [comment]
Let's just let it be a link. No need for the external icon or really any if it's not external.

**Comment by dbspringer** [comment]
Do we consider a link to Calypso external? IMO, I still think we should consider this:

https://github.com/Automattic/jetpack/issues/5902#issuecomment-267421955

**Comment by MichaelArestad** [comment]
@dbspringer I lean toward no. I also find there's almost no great reason to use `target="_blank"`. Here's a good article on it: https://css-tricks.com/use-target_blank/

**Comment by eliorivero** [comment]
Closing this since we no longer have this issue in new settings UI
