### ISSUE TITLE
Plans: Premium / Pro features should be automatically activated when plan was purchased for that feature

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5909]
#### Steps to reproduce the issue

1. Start from a free Jetpack site.
2. Go to Jetpack > Settings, browse features.
3. Find a feature you like, like "Ads".
4. Click on Upgrade because you're interested in the feature.
5. Go through the purchase flow.
6. Once completed, you still have to go back to the Settings screen and activate the module. Ideally, it would be activated for you since that's why you bought the plan in the first place.

**Comment by jeherve** [comment]
Related: #7362

**Comment by beaulebens** [comment]
I think we should handle this for now by adding inline settings in the welcome splash screen for new plans, as in https://github.com/Automattic/jetpack/pull/8700

Will be handled even better with the new checklist work that @joanrho is doing.
