### ISSUE TITLE
WordAds appears underneath header on Twenty Seventeen

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#5918]
#### Steps to reproduce the issue
1. Enable WordAds, and check the "Display an ad unit at the top of each page." box
2. Switch to Twenty Seventeen
3. View the home page

#### What I expected
To seen an ad unit at the top of the screen

#### What happened instead
Ad unit is hidden under header image, AND pushes the site title text and arrow prompt below the fold.

Probably the ad unit should go inside the `.site-content-contain` in this theme, since otherwise it's battling against the fancy static header and would look strange.

Screenshots:

With WordAds disabled:

<img width="924" alt="wordads-disabled" src="https://cloud.githubusercontent.com/assets/51896/21245469/6d77c85c-c2d7-11e6-9559-4d5fe7712945.png">

With WordAds enabled:

<img width="922" alt="wordads-enabled" src="https://cloud.githubusercontent.com/assets/51896/21245474/72fc13fa-c2d7-11e6-8585-de5e0d942517.png">

**Comment by eliorivero** [comment]
Can you check with https://github.com/Automattic/jetpack/pull/5919?

**Comment by jeherve** [comment]
Closing as this should be fixed with #5919, as Elio mentioned. 👍
