### ISSUE TITLE
Infinite scroll not working with Twenty Seventeen

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#5920]
#### Steps to reproduce the issue
1. Activate Twenty Seventeen theme
1. Activate Infinite Scroll module
1. Scroll on home page

#### What I expected
Infinite scroll

#### What happened instead
Finite scroll :)

Regular pagination appears at bottom of page, as if the module isn't even activated.

**Comment by ebinnion** [comment]
Related: #5878
