### ISSUE TITLE
Multiple issues enabling and configuring SEO tools

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#5921]
#### Steps to reproduce the issue
1. Enable SEO tools module
1. Expand SEO tools drop-down and click the link to Calypso
1. Message on screen says SEO tools module is not enabled - so I click the link that says "Enable"
1. It redirects back to my site, but with `https://` instead of `http://`. This results in a 404.
1. Returning to my Jetpack settings manually, I see that the SEO module now says "Upgrade" (before I was allowed to enabled it, now I have the Upgrade button) - note that I am on the Professional plan.

#### What I expected
1. To be able to configure SEO tools after I enabled it
1. To be able to enable SEO tools from Calypso if it's not enabled
1. For SEO tools to be available to me, as I'm on a Professional plan

#### What happened instead
None of those things ^^^

By the way, some of this could be my site - I'm on very low-end Dreamhost shared hosting, so sometimes it randomly 404's due to exceeding whatever tiny horsepower they give me (_imagines Dreamhost being powered by a tiny horse, giggles_), but even if that wasn't the case it wasn't failing in informative ways.

**Comment by gravityrail** [comment]
Interestingly, after going back to Calypso and my site a few minutes later, these issues were cleared up, could have been a caching thing. Though the broken link to my site from Calypso definitely wasn't.

**Comment by jeherve** [comment]
This all looks similar to https://github.com/Automattic/wp-calypso/issues/8404

Unfortunately, those caching issues happen really often; we just see them a lot more now that we have folks wanting to use Calypso right after they purchased a feature. That's definitely something that should be fixed sooner rather than later.

> It redirects back to my site, but with https:// instead of http://. This results in a 404.

Tracked in https://github.com/Automattic/wp-calypso/issues/9655

**Comment by jeherve** [comment]
Closing this in favor of #7001
