### ISSUE TITLE
Jetpack Network excludes site with id 1

### ISSUE THREAD

**Issue by hajekj** [Automattic/jetpack#5926]
#### Steps to reproduce the issue
I have a regular multisite deployment of WordPress and when I list all Jetpack sites (https://sitename/wp-admin/network/admin.php?page=jetpack), I am unable to see the main site listed there.

#### What I expected
I expected to see all the sites under the network visible there.

#### What happened instead
See above.

This might have something to do with https://github.com/Automattic/jetpack/blob/master/class.jetpack-network-sites-list-table.php#L30 or is it expected behavior?

**Comment by kraftbj** [comment]
This is generally expected behavior. For the Network Admin page to list sites, the main site needs to be already connected. Jetpack's MS uses the main site's connection as a basis for connecting subsites, so it can't be disconnected from there.
