### ISSUE TITLE
Tweet shortcode: remote request for numeric tweet attribute

### ISSUE THREAD

**Issue by niallkennedy** [Automattic/jetpack#5936]
Question about the newly added `[tweet]` shortcode.
https://github.com/Automattic/jetpack/blob/master/modules/shortcodes/tweet.php#L55

Is the check for a numeric Tweet ID in `[tweet tweet="20"]` just to create a URL suitable for `wp_oembed_get`? Would constructing a valid Tweet URL from a base string solve that need without the transient and remote get?

A Tweet URL has an author username component and a Tweet ID component. If you have just a Tweet ID you could construct a full Tweet URL by appending to a base string.

Something like:

```php
$id = null;
if ( ctype_digit( $attr['tweet'] ) ) {
	$id = 'https://twitter.com/_/status/' . $attr['tweet'];
} else {
	preg_match( '/^http(s|):\/\/twitter\.com(\/\#\!\/|\/)([a-zA-Z0-9_]{1,20})\/status(es)*\/(\d+)$/', $attr['tweet'], $urlbits );
	if ( isset( $urlbits[5] ) && intval( $urlbits[5] ) ) {
		$id = 'https://twitter.com/' . $urlbits[3] . '/status/' . intval( $urlbits[5] );
	}
}
if ( ! $id ) {
	return '<!-- Invalid tweet id -->';
}
```

The oEmbed endpoint then returns the full URL in the response JSON's `url` property if another function might use the `jpt_20` transient.

**Comment by jeherve** [comment]
Related: #5838, #5518

**Comment by eliorivero** [comment]
Thanks @niallkennedy for pointing out this! It will be introduced in https://github.com/Automattic/jetpack/pull/5945
