### ISSUE TITLE
Admin: Need "Pro" labels changed to "Paid" & directly actionable.

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#5949]
Master Issue: https://github.com/Automattic/jetpack/issues/6135

3 things we need to do for be better UX regarding the paid sectionHeader labels. 

- [x] In an effort to prohibit customer confusion, we need to change the "Pro" label to say "Paid."
- [ ] "Paid" labels should also link to more actionable feature blocks on the plans landing page.
- [ ] Content blocks on the Free plan landing page need actionable CTAs... 

**1. Paid Labels**
Currently:
<img width="375" alt="pro-label" src="https://cloud.githubusercontent.com/assets/214813/21327996/b5bce13a-c5ff-11e6-9588-1be177d7a8d4.png">

After:
<img width="387" alt="screen shot 2016-12-19 at 3 27 31 pm" src="https://cloud.githubusercontent.com/assets/214813/21328008/c054f3bc-c5ff-11e6-9e98-c6ddedd1d5fd.png">

At a glance, the Pro label communicates that these features are only included in our Professional plan. Where-as they as also available in our personal and premium plans. 

**2 + 3) Paid labels need to Link to more actionable feature blocks.**

As @rickybanister pointed out, When a user clicks / taps on one of these labels, it simply drops them into the Plans landing page. We should adjust this so if the user is on a free plan, and they click the "Anti-spam" Paid label, it brings them to the plans landing page, but scrolls them specifically down to the "Spam Protection" feature block. That feature block should have a specific CTA to help the user upgrade. 

Current example:

User click "Pro" label on "Anti-spam" feature within the AAG dash and they are just dropped into the landing page.

![free-plans-landing-full](https://cloud.githubusercontent.com/assets/214813/21328484/29c73f9c-c602-11e6-9d1f-45db44440d38.png)

There's no headline or anything pointing out "anti-spam" here, it's hidden in the security block. Let's break out all the features into separate blocks like we do for our paid plans landing pages, and offer up more specific learn more CTAs like "Upgrade to a paid plan for amazing spam protection"

Paid plans landing... 

<img width="767" alt="screen shot 2016-12-19 at 3 47 14 pm" src="https://cloud.githubusercontent.com/assets/214813/21328559/90287a6c-c602-11e6-9f1f-ad9b6d30e1e5.png">

cc @richardmuscat

**Comment by jeffgolenski** [comment]
As a sidenote: After speaking with @eliorivero in-depth in slack a week ago, I discovered that simply creating `hrefs` that link to different anchors within the same page, is not an easy task within react like it is in plain html. (example `href="#bacon"` going to `id="bacon"`). So we'll have to have a conversation about how to implement. In the meantime, I'm opening a PR to start working on the label changes at least. 

cc @rickybanister

**Comment by jeffgolenski** [comment]
Label change made in: https://github.com/Automattic/jetpack/pull/6034

**Comment by brbrr** [comment]
Hey @jeffgolenski 
There is a PR which will remove 'Paid' labels completely: #9732. Is this ticket still needed?

**Comment by jeherve** [comment]
Closing as the labels are now gone. #9732
