### ISSUE TITLE
AAG Stats: Timeout on first page load

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#5952]
#### Steps to reproduce the issue
On my site (dentedreality.com.au), pretty much every time I go to the Jetpack AAG/Dashboard view, my stats timeout. As soon as I refresh the page, they load the second time. Maybe due to some caching somewhere in the request stack?

I finally remembered to have my console open _before_ I got to the page, so that I could see what the console reported, and found this:

![screen shot 2016-12-19 at 5 08 04 pm](https://cloud.githubusercontent.com/assets/108942/21333748/739221b6-c60f-11e6-84c2-49d2b8ffbcd2.png)

So I don't know where that timeout is coming from exactly, but I think it's coming from the request back to WP.com to get the actual stats.

**Comment by beaulebens** [comment]
This is still happening, so I'm bumping to see if there's anything we can do to fix it.

**Comment by jeherve** [comment]
Also in https://wordpress.org/support/topic/connection-problems-2/

**Comment by jeherve** [comment]
This should now be fixed, with the Stats redesign.
