### ISSUE TITLE
Admin: Add CTA button to visit WordPress.com from top of apps landing page

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#5955]
Currently, the free landing page header offers no CTA button to bring users to download the apps without them having to scroll. I shall fix that, by adding a CTA that brings them to choose an app to download.

<img width="748" alt="screen shot 2016-12-19 at 9 47 17 pm" src="https://cloud.githubusercontent.com/assets/214813/21336646/c690e062-c634-11e6-894c-81c25ed7b9f2.png">

cc @dereksmart for tracks stuffz when its done.

**Comment by jeherve** [comment]
Closing as duplicate of #5679

**Comment by jeffgolenski** [comment]
@jeherve I'm reopening this because these issues are actually referencing two different landing pages

**Comment by jeffgolenski** [comment]
Fixed in: https://github.com/Automattic/jetpack/pull/6009
