### ISSUE TITLE
Unit Tests: add PHP 7.1

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5959]
It would be nice to add PHP 7.1 to our list of Unit Tests, as it includes a few breaking changes from PHP7, and is getting more and more popular with site owners.

**Comment by zinigor** [comment]
There's already a PR #5821 for that, but we are held back by 4.6 not being compatible with PHP 7.1.

**Comment by jenhooks** [comment]
There's a report of a problem here: 2960769-t
