### ISSUE TITLE
Custom CSS: PHP notice on upgrade to 4.5 beta and WP core 4.7

### ISSUE THREAD

**Issue by lancewillett** [Automattic/jetpack#5964]
#### Steps to reproduce the issue
I updated core WP to 4.7 my Jetpack self-hosted site via wp-admin/update-core.php page, and when it was finished I was redirected to wp-admin/about.php

At the time I ran the update, the site was running Jetpack 4.5-beta2.

#### What I expected

No PHP warnings in debug log.

#### What happened instead

Several warnings appeared:

```
NOTICE: wp-content/plugins/jetpack/modules/custom-css/migrate-to-core.php:191 – Trying to get property of non-object
require_once('wp-admin/admin.php'), do_action('admin_init'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, Jetpack_Custom_CSS_Data_Migration::do_migration,  Jetpack_Custom_CSS_Data_Migration::get_all_revisions
```

and 2 more similar ones, see screenshots.

<img width="1672" alt="screen shot 2016-12-20 at 11 21 06" src="https://cloud.githubusercontent.com/assets/66797/21364115/afaf70a2-c6ac-11e6-946f-9a1846b30f11.png">

<img width="1440" alt="screen shot 2016-12-20 at 11 21 14" src="https://cloud.githubusercontent.com/assets/66797/21364120/b41f2a56-c6ac-11e6-81ce-e07c25555545.png">

**Comment by lancewillett** [comment]
See also previous: https://github.com/Automattic/jetpack/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20non-object

**Comment by jeherve** [comment]
Could you check and see if #5944 fixes the issue on your site?

Thanks!

**Comment by lancewillett** [comment]
Yes, that addresses it perfectly. Thanks. Closing.
