### ISSUE TITLE
More shortcode support for Jetpack

### ISSUE THREAD

**Issue by danstramer** [Automattic/jetpack#5980]
There is an extensive list of shortcodes used in wordpress.com, for example:
https://en.support.wordpress.com/list-pages-shortcode/

Most of these shortcodes are not supported in Jetpack.
May I request you consider adding these to Jetpack?
From my experience these can help alot for users and also for web-site builders / designers.

Thanks
Dan

**Comment by jeherve** [comment]
Until this gets added to Jetpack, you can install [this plugin](https://wordpress.org/plugins/list-pages-shortcode/) on your site to replicate the functionality available on WordPress.com.

**Comment by danstramer** [comment]
Thanks for your response Jeremy. I thought it would be better having everything centralized, rather than having to install a few more plugins (as there are some more shortcodes available on wp.com which are not available on JP).

Dan
