### ISSUE TITLE
Track Jetpack-powered Twitter embeds

### ISSUE THREAD

**Issue by niallkennedy** [Automattic/jetpack#5984]
Twitter supports tracking discovery and publishing tools powering the embed experience by adding a `partner` data attribute to embed markup. If Twitter's widgets JavaScript runs on the page and sees markup such as `<blockquote class="twitter-tweet" data-partner="jetpack">` or `<a class="twitter-timeline" data-partner="jetpack">` it's very likely Jetpack helped a site publish an embed and Jetpack's reach could be better understood from an embed provider's perspective. Knowing reach helps prioritize future code contributions.

Sound interesting? In the [tweet shortcode](https://github.com/Automattic/jetpack/blob/master/modules/shortcodes/tweet.php) a new query argument would be added in the extra_args function: `partner=jetpack`. In [twitter_timeline_shortcode](https://github.com/Automattic/jetpack/blob/master/modules/shortcodes/twitter-timeline.php) the string builder would add `data-partner="jetpack"` in the anchor element.

The `jetpack` attribute value is freeform and could similarly be `wpcom` depending on the environment.

You can see the partner data attribute in action when generating embed HTML through [TweetDeck](https://tweetdeck.twitter.com/).

**Comment by jom** [comment]
I can work on this. Do we want to distinguish between `jetpack` and `wpcom`? Is `IS_WPCOM` the best way to determine this?

**Comment by jeherve** [comment]
@jom Sounds like a good plan!
