### ISSUE TITLE
Sharing via Email: allow the URL to be filterable

### ISSUE THREAD

**Issue by sumobi** [Automattic/jetpack#5989]
I'd love the post URL sent via email to be filterable:
https://github.com/Automattic/jetpack/blob/master/modules/sharedaddy/sharedaddy.php#L71

The other sharing icons (Twitter, Facebook etc) already have a filter which is very handy:
https://github.com/Automattic/jetpack/blob/master/modules/sharedaddy/sharing-sources.php#L57

___

My specific use case:

We're creating a plugin for AffiliateWP (https://affiliatewp.com) that allows an affiliate (while logged in) to click the sharing buttons and share the URL with their username/ID appended.

It would be neat if https://github.com/Automattic/jetpack/blob/master/modules/sharedaddy/sharedaddy.php#L71 could call `get_share_url()` (https://github.com/Automattic/jetpack/blob/master/modules/sharedaddy/sharing-sources.php#L45) and pass `$data['post']->ID` to the method.

**Comment by rvdsteege** [comment]
**+1** — I was going to open an issue with the same request. In our opinion, it's more like a bug than an enhancement though. And preferably, would be nice if the post title can also be filtered (https://github.com/Automattic/jetpack/blob/master/modules/sharedaddy/sharedaddy.php#L70).

Our use case: our pages exist of multiple tabs (first tab is post content, additional tabs are added on the post edit page and are NOT separate posts). By appending `?tab=tab-slug`, we're making sure that the correct tab is displayed on page load. So we include the `tab` parameter in the sharing URL through the `jetpack_sharing_display_link` and `sharing_permalink` filters:

```
/**
 * Jetpack sharing link
 */
function issue_5989_sharing_link( $url ) {
	$tab = filter_input( INPUT_GET, 'tab', FILTER_SANITIZE_STRING );

	if ( ! empty( $tab ) ) {
		$url = add_query_arg( 'tab', $tab, $url );
	}

	return $url;
}

add_filter( 'sharing_permalink', 'issue_5989_sharing_link', 10, 2 );
```

This works as expected for Facebook, Twitter and LinkedIn, but not for sharing via email. And these pages _do_ get shared by email.

Any chance on getting this issue assigned to an other milestone than the [Not Currently Planned](https://github.com/Automattic/jetpack/milestone/4), @jeherve ? Thanks :-)

**Comment by jeherve** [comment]
@rvdsteege It's not on our roadmap right now, but we'll be happy to review any Pull Request about it!

**Comment by sumobi** [comment]
👍
