### ISSUE TITLE
Admin Page: paid module status takes a long time to appear

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#5990]
#### Steps to reproduce the issue

0. Start with a site using a Jetpack plan.
1. Go to Jetpack > Settings
2. Click on the Writing tab.
3. You'll need to wait for a bit before the VideoPress toggle shows up:

![screen recording 2016-12-23 at 08 17 pm](https://cloud.githubusercontent.com/assets/426388/21460900/274c5b96-c94d-11e6-9339-5bf88a6f2be6.gif)

4. Same thing will happen when trying to access other Paid modules:

![screen recording 2016-12-23 at 08 21 pm](https://cloud.githubusercontent.com/assets/426388/21460954/978e6de0-c94d-11e6-92ef-329e3aa1b2a5.gif)

![screen recording 2016-12-23 at 08 20 pm](https://cloud.githubusercontent.com/assets/426388/21460957/9b501d70-c94d-11e6-98c4-7411faffbb36.gif)

Can we avoid this?

**Comment by samhotchkiss** [comment]
Closing as this should be improved with the new settings UI in 4.6
