### ISSUE TITLE
JSON API: plugin endpoint breaks node-wpapi

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#5994]
[WP-API's node client](https://github.com/WP-API/node-wpapi) lets users autogenerate a list of endpoints to make it aware of all available endpoints without having to go autodiscover them itself ([Docs](https://github.com/WP-API/node-wpapi#bootstrapping)).

The client fails parsing that list because of an "Invalid group" in the regex of the plugin endpoint.
<img width="344" alt="screen shot 2016-12-26 at 3 09 14 pm" src="https://cloud.githubusercontent.com/assets/1398304/21483092/52558bc8-cb7d-11e6-95f5-602fb2245b9f.png">

See error in "What happened instead".

#### Steps to reproduce the issue
1. Create the json file using the [`lib/data/update-default-routes-json.js`](https://github.com/WP-API/node-wpapi/blob/master/lib/data/update-default-routes-json.js) script. I used: ```$ ./node_modules/wpapi/lib/data/update-default-routes-json.js --endpoint=https://wordpress.org/plugins-wp/wp-json  --output=./client```
1. Import it into a JS app that uses `WPAPI` and [pass it to the constructor](https://github.com/WP-API/node-wpapi#bootstrapping). 
1. Try running the JS API to encounter parse error.

#### What I expected
Flawless import of the script, working WPAPI client

#### What happened instead
Encountered an uncaught Syntax Error:
<img width="1261" alt="screen shot 2016-12-26 at 3 05 34 pm" src="https://cloud.githubusercontent.com/assets/1398304/21483062/d4c38426-cb7c-11e6-9973-3a734c3afcef.png">

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
