### ISSUE TITLE
Mobile Theme: Minify CSS in build script

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#600]
Since the mobile theme's CSS should only be seen in mobile environments, minifying it as part of the Grunt tools would be an easy win for users.

https://www.npmjs.org/package/grunt-contrib-cssmin

**Comment by samhotchkiss** [comment]
Since this isn't in line with our current goals, I'm going to `wontfix`, although if someone were to submit a PR, we'd definitely consider it
