### ISSUE TITLE
JS Error: TypeError: this.notes[0] is undefined

### ISSUE THREAD

**Issue by Dartui** [Automattic/jetpack#6001]
WordPress Version: 4.7
Jetpack Version: 4.4.2

After installation and connecting site with Jetpack, JS console keeps throwing errors:
![JS Errors](http://screenshooterusnortheu.blob.core.windows.net/engine4files/jjubagixcsqwmrlambmgjzrogihgtfyzfqleobvksvnsfajeinnzrcgnxdpzthkwiqeykdtfihhjuacctglinclmlkukshwselms)

Disabling all plugins with leaving only Jetpack active does not solve problem. Deactivating and activating Jetpack also. Each error appear after XHR request, so here are request and response data:

![Request values](http://screenshooterusnortheu.blob.core.windows.net/engine4files/qmalmlkpjvvsnqavywwabkunseszujcxvzehpxepglpqvnedqufgjztyyjlqmotjukxayvdybmydovjlouvfdqifercmhjkabqwx)

![Response](http://screenshooterusnortheu.blob.core.windows.net/engine4files/vqylmzfehtmfiohqunjvcukfbuucgkicibflrqvuemzcutyzwttveksphjdvfrvlrrvdnnwrhymamizpdehmfwdghlmrtbaiioje)
(notes in response is an empty array)

**Comment by itklif** [comment]
same here ...     :-(

**Comment by jeherve** [comment]
I can't seem to reproduce on my end. Could you both use Jetpack's Debugger module to send us some more information about your site, as the problem might be specific to your Jetpack connection?

<ol>
<li>Go to the Jetpack page in your dashboard.</li>
<li>Click on the <strong>Debug</strong> link appearing at the bottom of the page.</li>
<li>Click the link that says <strong>"click here to contact Jetpack support."</strong></li>
<li>Fill in the description box and your name and email address.</li>
<li>Click the "Contact Support" button to send us the debug results privately. <strong>It's best not to post this information here, as it contains private details about your site.</strong></li>
</ol>
Thanks!
