### ISSUE TITLE
Holiday Snow: Make location-aware

### ISSUE THREAD

**Issue by tyxla** [Automattic/jetpack#6007]
I recall we were once discussing with @oskosk that having a holiday snow does not make sense in some locations. For example, in South America, December holidays are practically in the summer, which makes the Holiday snow totally inappropriate there. 

Can we solve this by making the Holiday Snow aware of the location? At a first glance I see two possible ways to achieve this (one does not exclude the other):

* The location of the user that is visiting the site.
* The location of the site owner / or their timezone.

The above can be configurable options that each site owner would be able to configure and/or prioritize.

I realize that it might be arguable where geographically it would make sense to have the Holiday Snow enabled, but in any case I believe it's worth a discussion.

**Comment by gravityrail** [comment]
Closed because feature is removed in Jetpack 6.0.

**Comment by jeherve** [comment]
Reopening as snow is back: #9110

**Comment by zinigor** [comment]
#9110 is not going to be merged, closing.
