### ISSUE TITLE
Slow attachment_url_to_postid() in jetpack_og_get_image()

### ISSUE THREAD

**Issue by sboisvert** [Automattic/jetpack#6017]
#### Steps to reproduce the issue

Use OpenGraph on a site with thousands of images (example site has ~100,000 ) 

#### What happened 

Slow queries in the style of `SELECT post_id FROM wp_postmeta WHERE meta_key = ? AND meta_value = ?`
these can take up to 40s

**Comment by sboisvert** [comment]
https://github.com/Automattic/jetpack/compare/master...jetpack_og_get_image_caching?quick_pull=1

**Comment by jeherve** [comment]
@sboisvert I don't see a PR for this yet. Did you create one, or did you just push the fix in a new branch? If the branch is ready, feel free to create a PR!

Thanks!
