### ISSUE TITLE
Admin: add notice in Widgets screen informing users about widget enhancements

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#6028]
Extra Widgets and Widget Visibility will be always on in 4.6 so we'll display some notice in the Widgets screen about the new widgets and widget visibility.

**Comment by MichaelArestad** [comment]
@jeffgolenski How reusable is your connection message banner thingy? Think a single page version of it could be used for this (with different copy and image)?

**Comment by jeffgolenski** [comment]
@MichaelArestad I'm having a hard time visualizing what you mean, but we can use it as necessary. It's not built in react, but in the atomic design portion of jetpack outside of the react portion. I coded it to be super modular so we can take it and mod it, for sure.

**Comment by MichaelArestad** [comment]
@jeffgolenski Ah. I'll see if I can find a react thing version of it in Calypso maybe.

**Comment by jeffgolenski** [comment]
@MichaelArestad Well I built it specifically for Jetpack, so I don't think you'll find the same thing in Calypso. But there are a few components I borrowed the idea from

**Comment by MichaelArestad** [comment]
@jeffgolenski totally. Just wanted to make sure I'm not reinventing a wheel.

**Comment by MichaelArestad** [comment]
Loosely related: https://github.com/Automattic/jetpack/issues/6227

Might do something similar here.

**Comment by rickybanister** [comment]
A JITM would work just fine here. How's this:

![image](https://user-images.githubusercontent.com/437258/37728531-dfbcda66-2d10-11e8-86fe-1556d5a20ab1.png)

**Comment by MichaelArestad** [comment]
Widgets and Widget visibility are no longer on by default. I'm going to close this for now.
