### ISSUE TITLE
Admin: Inactive Card SectionHeader needs color adjustment

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#6032]
[In a previous PR](https://github.com/Automattic/jetpack/commit/29ec8a1fce9984cb8b5f71fe17733ada06562c06), the SectionHeader fade was accidentally changed on the inactive sectionHeader titles like so...

![screen shot 2017-01-03 at 1 37 38 pm](https://cloud.githubusercontent.com/assets/214813/21618656/ff4d78d0-d1b9-11e6-8ae3-4d7712fb77ca.png)

Just need to change it to match the proper color for inactive cards.

cc @MichaelArestad

**Comment by MichaelArestad** [comment]
Ah. Thought I fixed that. Will take care of after lunch if you don't get to it. Should be straightforward.

**Comment by jeffgolenski** [comment]
Already done!
