### ISSUE TITLE
Settings: Related Posts: use a single toggle

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack#6037]
Currently we had planned to rely only on the related posts settings in customizer going forward, HOWEVER, that gets us out of step with WordPress.com. It is also a missed opportunity to make related posts discoverable in settings while a user explores other settings.

So we need to bring that setting back, and update the interface slightly.

Previously we used a radio button with two different and opposite labels to control related posts:

**Before (screenshot from WordPress.com):**
<img width="724" alt="screen shot 2017-01-03 at 4 25 00 pm" src="https://cloud.githubusercontent.com/assets/437258/21623717/d4a5aefa-d1d1-11e6-8b6b-d941482cd869.png">

This isn't the most efficient way to display this setting. The user has to fully read both options to understand which choice they want to make. 

Additionally we are not hiding the preview or the sub-options when this feature is turned off. They simply have reduced opacity and can still be interacted with (you can toggle on/off options even if you have related posts disabled on your site, that's a bug). 

Let's use a single toggle instead.

**After:**
![off](https://cloud.githubusercontent.com/assets/437258/21623771/0f257588-d1d2-11e6-8ff9-ac7eda9766ec.jpg)
![on](https://cloud.githubusercontent.com/assets/437258/21623770/0f235028-d1d2-11e6-8a90-06e26ab72bc3.jpg)

Let's hide the sub options and preview if the feature is turned off.

cc @MichaelArestad @eliorivero @zinigor 

h/t @ashleighaxios for doing the mockups

Also see the corresponding WordPress.com issue: https://github.com/Automattic/wp-calypso/issues/10391

**Comment by eliorivero** [comment]
Nice, this looks very good.

**Comment by eliorivero** [comment]
Nice, this looks very good.
The PR #6036 I opened is only to bring back the previous settings, 4.5 settings, that is. Will be later working on these new settings for 4.6 that use a different data handling under the hood.

**Comment by tyxla** [comment]
Related WordPress.com PR: https://github.com/Automattic/wp-calypso/pull/10423

**Comment by eliorivero** [comment]
Introduced in #6039
