### ISSUE TITLE
Edit default email addresses for Contact notifications

### ISSUE THREAD

**Issue by terrycloth** [Automattic/jetpack#6044]
Being able to change the Feedback notification recipients for each Contact form is cool. But it seems to me that plenty of sites would want all or most emails to go to the same people, and the intended email recipients might not be just the person whose WP.com account is connected to the Jetpack plugin. It would be nice if the Jetpack Contact Form settings could add an option to change the default email recipients.

**Comment by jeherve** [comment]
> It would be nice if the Jetpack Contact Form settings could add an option to change the default email recipients.

By default, if you don't specify a custom email recipient, the emails are sent to the post/page author. That could be an efficient way for you to send all emails to a specific email address; make sure the posts are authored by a user with the email address you're interested in.

I hope this helps.

**Comment by terrycloth** [comment]
> [...] it wouldn't be a useful option for most Jetpack users.

You really don't think so? I don't have any data on the Jetpack userbase, but changing the global default recipient doesn't seem like such an unusual feature to me. But I guess there are definitely two broad categories of use cases: Individual users running a personal blog, and multi-person organizations. 

I suppose it's reasonable to assume that there are many more installations for one-person operations, and keeping things as simple as possible for them makes Jetpack more useful to a greater number of WordPress instances. But websites managed by or representing multi-person groups might *use* the various WP/Jetpack features more *often*.

> [...] make sure the posts are authored by a user with the email address you're interested in.

Well, for a contact form that has already been created, this means having to delete the page, and telling someone else to redo it just so they can be the original "author." It would work, but it's hardly ideal.

Moreover, in my case, I design and maintain the website, *mostly* by myself, for a small business. My partner talks to all the clients and provides the business's actual service *entirely* by himself, so I need him to be the one receiving email notifications about new contact form submissions. I could just manually enter his email as the recipient for all contact forms, but this doesn't seem ideal either. WordPress is an ever increasingly viable option for running a real business website, so I imagine there's a significant portion of the userbase that's similar to my own case, even if it's not a majority. The fact that Jetpack provides premium features and services for a subscription fee suggests to me that Jetpack is interested in courting more professional WP users.

Or do you see your target audience as just bloggers?

**Comment by jeherve** [comment]
> for a contact form that has already been created, this means having to delete the page, and telling someone else to redo it just so they can be the original "author." It would work, but it's hardly ideal.

You don't have to recreate the page. You can change its author, either in the page editor or using the bulk edit tools if you want to change the author for multiple pages at once.

> I design and maintain the website, mostly by myself, for a small business. My partner talks to all the clients and provides the business's actual service entirely by himself, so I need him to be the one receiving email notifications about new contact form submissions.

In this case, the easiest solution might be to go to the Pages menu in your dashboard, select all pages that include a contact form by clicking on the checkbox next to them, and then choose "Edit" in the "Bulk Actions" dropdown at the top of the page. You will then be able to change the author for all pages at once.
