### ISSUE TITLE
Tonesque assumes wp-content prefix

### ISSUE THREAD

**Issue by joehoyle** [Automattic/jetpack#6056]
See https://github.com/Automattic/jetpack/blob/master/_inc/lib/tonesque.php#L49, it's hardcoded to use `wp-content` which is less than ideal, as this isn't necessarily the content prefix. It should probably use `WP_CONTENT_DIR` / `WP_CONTENT_URL`.

**Comment by kraftbj** [comment]
Good catch. Definitely needs to use something better.
