### ISSUE TITLE
Where is Tonesque used?

### ISSUE THREAD

**Issue by joehoyle** [Automattic/jetpack#6057]
While reviewing Jetpack for some security related stuff, I came across Tonesque that does some slightly dubious with fetching remote files, however I can't see that it's actually used anywhere, except if the theme supports it, but even then no calls are made to it.

**Comment by kraftbj** [comment]
It's a theme tool, so available for themes/plugins to use like https://wptavern.com/color-posts-plugin-extends-jetpack-to-add-intuitive-background-color-matching and https://ryelle.codes/2015/01/using-tonesque-sass-to-generate-color-schemes/ .

I'm not aware of the history of when it was added if there was other reasons for it.
