### ISSUE TITLE
Widget Visibility: Retired plugin-handling erroneously defines it twice

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6064]
In [class.jetpack.php](https://github.com/Automattic/jetpack/blob/master/class.jetpack.php#L69-L70), we handle incompatible plugins by detecting them and then disabling our modules which conflict.

`widget-visibility` is defined in the array twice, but since that's the key, only the last one will actually remain (the first will be overwritten). We need to handle that somehow differently.

**Comment by jeherve** [comment]
Closing as duplicate of #3198
