### ISSUE TITLE
Holiday Snow: remove settings from Admin Page when the tool isn't loaded

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6065]
#### Steps to reproduce the issue

1. Add the following to a functionality plugin on your site:

```php
/**
 * Stop Holiday Snow from loading.
 *
 * @param array $tools Array of theme tools available in Jetpack.
 */
function jeherve_rm_holiday_snow_tool( $tools ) {
        $index = array_search( 'holiday-snow.php', $tools );
        if ( false != $index ) {
                unset( $tools[ $index ] );
        }

        return $tools;
}
add_filter( 'jetpack_tools_to_include', 'jeherve_rm_holiday_snow_tool' );
```
2. The Holiday Snow file isn't loaded anymore on your site.
3. Go to Jetpack > Settings > Appearance.
4. The Holiday Snow card still appears, although you can't turn it on.

`{"code":"some_updated","message":"Invalid option: false.","data":{"status":400}}`

**Comment by jeherve** [comment]
Reported here:
https://wordpress.org/support/topic/several-modules-appear-not-to-be-suppress-able/

**Comment by georgestephanis** [comment]
I wonder if it may be worth having the admin setting for it be viewable for maybe a week before and after the snow would actually fall?  Maybe I'm just bikeshedding though.

**Comment by jeherve** [comment]
@georgestephanis I think it would make sense. After all, the old settings (under Settings > General) are only visible during the holiday snow period.

**Comment by MichaelArestad** [comment]
@jeherve is this an issue with the new UI. There currently is no Holiday Snow UI in favor of maybe something like this: https://github.com/Automattic/jetpack/issues/6260

**Comment by jeherve** [comment]
#6260 should have fixed this, nice catch. Closing. :+1:
