### ISSUE TITLE
Infinite scroll: Only picking up the first category on archive when browsing multiple categories

### ISSUE THREAD

**Issue by daco** [Automattic/jetpack#6066]
When navigating to /category/catA+catB+catC/ only the first category is filtered when scrolling down.
I expected the exact same archive (number of posts, order etc) as I would have with IS off, but this archive is showing only all posts having *only* catA.

**Comment by jeherve** [comment]
I believe you were right to comment in #4087. That seems to be the same issue.

Closing this as duplicate.
