### ISSUE TITLE
Comments: Message to "Please enter a URL." when uncommon TLDs used in Website field

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/jetpack#6072]
An error message to "Please enter a URL." when uncommon TLDs, for example test.blog or hello.de, are used in the comment form's Website field prevents comments being submitted.

#### Steps to reproduce the issue

1. Enable Jetpack comments on a self-hosted site or enable comments on a WordPress.com site.
2. View a post or a page on the site while logged out of WordPress.com.
3. The default comment form will include a Website field, as shown in the following screenshot:

<img width="790" alt="screen shot 2017-01-11 at 19 22 23" src="https://cloud.githubusercontent.com/assets/2998162/21862968/6d02e106-d833-11e6-8a4d-94971f04cc58.png">

4. Enter information into each of the form's fields and include a URL ending in an uncommon TLD, such as .blog or .de.

#### What I expected

I expected the comment to be submitted correctly, as a correct URL had been entered.

#### What happened instead

I was not able to submit my comment and, instead, was given an error next to the Website field telling me to "Please enter a URL."

<img width="845" alt="screen shot 2017-01-11 at 19 33 20" src="https://cloud.githubusercontent.com/assets/2998162/21863331/e8f458f2-d834-11e6-9028-dd0fbc0161ae.png">

This was reported in 2990688-t.

**Comment by kraftbj** [comment]
That looks like browser verification, not something we can control. If you try https://siobhan.blog, does it work?

**Comment by SiobhyB** [comment]
@kraftbj: D'oh! It seems so obvious now that you've pointed it out. :) Thank you!

**Comment by lnovitz** [comment]
> [@kraftbj](https://github.com/kraftbj): D'oh! It seems so obvious now that you've pointed it out. :) Thank you!

Thanks for raising this issue, I had the same problem hehe
