### ISSUE TITLE
`jetpack_photon_domain` filter value is forced https

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/jetpack#6073]
Given a filter:

```
add_filter( 'jetpack_photon_domain', function( $domain ){
	return 'http://photon.dev';
});
```

Since 0fa10d4288b383429114926f5327f676366bb345, `http://photon.dev` is forced to be `https` when I'd expect it to remain `http`.

If a custom domain is provided through the `jetpack_photon_domain` filter, it doesn't make sense to force a scheme.

**Comment by jeherve** [comment]
cc @aduth

**Comment by aduth** [comment]
The behavior previously would likely have been incorrect as well, in the case that I'm running an HTTP site, provide a HTTPS domain in the `jetpack_photon_domain` filter, I imagine it would have forced it back to HTTP (on the `is_ssl` check). The downgraded URL would probably still have worked in most cases, but same argument applies.

In any case, I'll have a fix prepared shortly.
