### ISSUE TITLE
Shorten font url for "social-logos" font family. Causes 414 errors on some hosts.

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#6076]
This line of code can cause some hosts to throw `HTTP Error 414: Request URI too long` errors when trying to load the "social-logos":
https://github.com/Automattic/jetpack/blob/master/_inc/social-logos/social-logos.css#L15

This issue is more of a question: Is it possible to make that URL shorter?

Reported in 2997478-t

**Comment by jeherve** [comment]
cc @jasmussen who will be able to tell us more. afaik we can't make that URL shorter, as it's the only way to declare the fonts in a way that will work for all browsers.

**Comment by jasmussen** [comment]
Ugh. Yes, this is a tricky one indeed. 

The URL that's too long, is the one that contains the base64 encoded version of the font. We could remove that in favor of a plain URL to the font, but the problem with this is that all modern browser block fonts from being loaded across domains. This becomes a problem as soon as someone installs a caching plugin which puts files on CDNs for caching and performance. Base64 works around that by always being on the same domain as the CSS that loads it.

You can add access control headers in .htaccess to allow fonts to load across domains. But this is not something we can fix in Jetpack, the user has to do this themselves.

I propose the fix should be migrating to SVG. Social Logos already comes with SVG files, so we're partially there.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/414-error-request-uri-too-long/

**Comment by jeherve** [comment]
This should be fixed as of #28849.
