### ISSUE TITLE
Sync: filter the post content to fix broken links before to send out subscription emails

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6080]
Consider the following scenario:
- I use relative paths on my WordPress site. All images look like `<img src="/wp-content/bla.jpg" />`.
- Whenever I publish a new post, that post content is synced with WordPress.com and then sent to my email subscribers.
- As you can imagine, an image tag like the one above doesn't display any image as soon as we're outside of the site.

I was wondering if:

1. We could try to support this use case out of the box on WordPress.com, by checking the links and adding the root domain when it's missing from post content before to send out subscription emails. This way, we would also fix the issue for the very few WordPress.com sites that may choose to have images with relative paths in their posts.
2. If we don't support this scenario ourselves, we could add a filter allowing someone to filter the post content before it's synchronized back to WordPress.com.

Suggested here:
https://wordpress.org/support/topic/jetpack-subscription-and-relative-links-bug/

**Comment by gravityrail** [comment]
Fixed in r149122-wpcom
