### ISSUE TITLE
Carousel: provide option to hide gallery behind a link

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6081]
> It would be very beneficial to be able to launch a mobile-friendly swipe gallery from a single link... either a text link, a button, or the link applied to a single image. And of course having the option of doing this while the tiled thumbnail gallery is hidden. As a photographer, it would be nice to show a few strong images in the post, then have a link to the rest of the images in the story.

> here's how I envision it working. It's simple... in the window where you create a gallery, a "Hide Thumbnail Gallery?" checkbox would be great. If this is checked, then a window could provide a URL to be used to create the link that would specifically launch that gallery. The reason I think this would be a good option is that a photographer (or any information source, really) might want to show a few strong images in a post to support a story, but then follow up with a link to the rest of the images, without the distraction of the thumbnail gallery.

Originally suggested in #6069 

cc @humanfiles

**Comment by humanfiles** [comment]
Here's an update... it occurred to me that I hadn't tried copying the gallery url produced by Jetpack Carousel, and applying that to a text link... I had only tried that with Photoswipe and it didn't work. So I tried it with Jetpack and it launched a gallery! Then I just hid the gallery with css. The only thing is if you launch the gallery with that link, then close the gallery, that link won't relaunch the gallery again unless you refresh the page. Visitors are going to wonder why the link only works once.

If you want to see what I'm talking about, you can go here:  http://david-mcgowan.com/skelletones/

I still like how Photoswipe displays images full-screen better, but I need to be able to display a post the way it is in the skelletones link. You win this round for now!

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
