### ISSUE TITLE
VideoPress: Poorly positioned "processing" image in Media Library

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6088]
I tried uploading a video via VideoPress:

- Media Library > Add New (link/button next to page title)
- drag/drop an mp4 onto the page
- video uploads
- this is displayed in the grid of media:

![screen shot 2017-01-12 at 5 10 06 pm](https://cloud.githubusercontent.com/assets/108942/21913579/69deb722-d8ea-11e6-8a1f-f6edf2038c07.png)

![screen shot 2017-01-12 at 5 14 22 pm](https://cloud.githubusercontent.com/assets/108942/21913647/ddc91704-d8ea-11e6-9c76-8b25266b4780.png)

There are similar problems when you are uploading video via creating a new post:

![screen shot 2017-01-12 at 5 15 17 pm](https://cloud.githubusercontent.com/assets/108942/21913654/e9b39fbc-d8ea-11e6-84f0-226aa7e683c5.png)
![screen shot 2017-01-12 at 5 15 57 pm](https://cloud.githubusercontent.com/assets/108942/21913656/e9b7f29c-d8ea-11e6-81c3-84271a0c5ed4.png)

**Comment by beaulebens** [comment]
Normally when one of these thumbnails renders, the image is behind the filename overlay (at the bottom). Based on the Inspector highlighting, it looks like that's not happening, which is probably what's throwing things off so much. This was in Chrome, don't know if it's the same in other browsers.

**Comment by beaulebens** [comment]
This seems to be due to an incorrect CSS `translate` being applied to `.wp-core-ui .attachments-browser .attachment .thumbnail .centered img.icon`. It's using `-50%,-70%`, but it should be `-50%,50%` (which matches "normal" thumbnail images).

Once that's corrected, we see that we should probably adjust the src image as well, so that it's not obscured by the filename overlay:

![screen shot 2017-01-12 at 5 24 58 pm](https://cloud.githubusercontent.com/assets/108942/21913835/451f60c4-d8ec-11e6-8b34-c0b3747182c2.png)

The same fix applies to Add New Post > Add Media:

![screen shot 2017-01-12 at 5 28 08 pm](https://cloud.githubusercontent.com/assets/108942/21913861/89df8d10-d8ec-11e6-86bd-658a08e0d295.png)

**Comment by MichaelArestad** [comment]
@beaulebens is there already a ticket/patch in core or should I make one?

**Comment by jeffgolenski** [comment]
@beaulebens thanks for digging into this beau. @dereksmart and I have been chatting and working on a fix. The css you outlined will do it, but we're also tweaking the image slightly as well.

**Comment by jeffgolenski** [comment]
Just kidding, we don't want to mess with core's css, and since that's whats being utilized for the videopress thumbnails, derek is deploying an updated image

**Comment by rickybanister** [comment]
Did an updated image get deployed? @jeffgolenski @dereksmart ?

**Comment by dereksmart** [comment]
It has!
