### ISSUE TITLE
Holiday Snow: remove settings outside of Holiday Snow period

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6090]
Site owners have 2 ways to activate or deactivate Holiday Snow on their site:

1. The first option is available under Settings > General; the option only appear during the holiday snow season, between December 1st and January 4th.
2. In Jetpack 4.3 we added another way to activate / deactivate Holiday Snow, directly from the Admin Page settings, under Jetpack > Settings > Appearance. That setting is displayed all year long, even though it can't be used for most of the year. It would be nice to remove it outside of the holiday season.

Another alternative, as suggested by @georgestephanis in #6065, would be to have the admin setting for it be viewable for maybe a week before and after the snow would actually fall.

Related: #6065

**Comment by MichaelArestad** [comment]
Related: https://github.com/Automattic/jetpack/issues/6260
