### ISSUE TITLE
Admin Page Stats: tooltip missing in IE11

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6092]
> In IE11, tooltips aren’t showing when hovering over a bar on the stats view.

![screen-shot-2017-01-12-at-9-14-38-pm](https://cloud.githubusercontent.com/assets/426388/21928765/f275c150-d98c-11e6-9427-37c175b7888d.png)

**Comment by oskosk** [comment]
Closing as this looks fixed now. (See gif below)

![working](https://user-images.githubusercontent.com/746152/31797080-cb855e50-b502-11e7-9adc-e837e9c3baec.gif)
