### ISSUE TITLE
Admin Page Plans: images/SVGs pop out of the container

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6093]
> In IE11, there are some layout issues where the images/SVGs pop out of the container.

![screen-shot-2017-01-12-at-9-18-01-pm](https://cloud.githubusercontent.com/assets/426388/21928841/66b35fc8-d98d-11e6-82bc-287d67afa945.png)

Here is how it looks in Chrome:

<img width="388" alt="screen-shot-2017-01-12-at-9-17-51-pm" src="https://cloud.githubusercontent.com/assets/426388/21928851/71de1794-d98d-11e6-8595-bd2cfee9d022.png">

**Comment by jeffgolenski** [comment]
Fixed in: https://github.com/Automattic/jetpack/pull/6109
