### ISSUE TITLE
Show or send example Monitor downtime alert message

### ISSUE THREAD

**Issue by markjaquith** [Automattic/jetpack#610]
I don't know what Monitor downtime e-mails are going to look like. It would be nice to have an example of the subject and the sender so people could do things like set rules to never-mark-as-spam or forward to phone as push notification, etc.

Alternatively (and this is probably better), provide a "Send downtime test e-mail" feature.

With something like this, you want to be sure it's all working _before_ your site goes down.

**Comment by dereksmart** [comment]
No plans to add any options to send a test email. I feel it should be enough to have it documented as it is on the support page.
