### ISSUE TITLE
PHP 7.1 Warning: show_subscribers_total

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#6101]
```PHP Warning:  Illegal string offset 'show_subscribers_total' in /home/public_html/wp-content/plugins/jetpack/modules/subscriptions.php on line 1049```

**Comment by kraftbj** [comment]
Nudge that we need to ensure we get #5821 moving too.

**Comment by enejb** [comment]
I tried replicating this but I wasn't able to. Do you have any more hints how I can replicate this. Do I need to be running PHP 7.1?

**Comment by jeherve** [comment]
#6106

**Comment by jeherve** [comment]
>  Do I need to be running PHP 7.1?

Yes.
