### ISSUE TITLE
stripos() expects parameter 1 to be string, array given in....

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#6125]
I have at least two reports so far of this error:

`Warning: stripos() expects parameter 1 to be string, array given in /home1/XXXXXXXX/public_html/wp-includes/formatting.php on line 3774`

Both users say that the error appears only on the Jetpack settings pages, not on the front end. They also say that that don't have any other plugins active.

3013046-t
3012753-t

What can we do to dig into this more? Any info that would be useful?

**Comment by richardmtl** [comment]
Possibly related:

3011946-t

`Warning: stripos() expects parameter 1 to be string, array given in
/home1/XXXXX/public_html/wp-content/plugins/jetpack/modules/shortcodes/class.filter-embedded-html-objects.php
on line 92

Warning: stripos() expects parameter 1 to be string, array given in
/home1/XXXX/public_html/wp-content/plugins/jetpack/modules/shortcodes/class.filter-embedded-html-objects.php
on line 98.`

> These two lines repeated one after the other for the entirety of the screen.
> I tried installing an earlier version of jetpack, and it began working normal
> again...then a few hours later the same error code reappeared.

If this is a different bug, I'll open a new issue, though.

**Comment by richardmtl** [comment]
3014487-t

**Comment by richardmtl** [comment]
3016212-t

**Comment by richardmtl** [comment]
I've asked users to try disabling modules, but they're saying they can't as the JP settings pages don't work with this error.

**Comment by chaselivingston** [comment]
3009935-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/latest-update-crashed-my-sites-css-in-chrome-browser/

**Comment by richardmtl** [comment]
Slightly different first errors:

`Notice: Undefined offset: 0 in
/home/XXXXXXXX/public_html/wp-content/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-react-page.php
on line 233
Warning: stripos() expects parameter 1 to be string, array given in
/home/XXXXXXX/public_html/wp-includes/formatting.php on line 3774
Notice: Array to string conversion in
/home/XXXXXXX/public_html/wp-includes/formatting.php on line 3717`

3011637-t

**Comment by richardmtl** [comment]
Another one, again slightly different:

`Notice: Undefined offset: 0 in
/var/www/vhosts/XXXXXX/httpdocs/wp-content/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-react-page.php
on line 233`

`Warning: stripos() expects parameter 1 to be string, array given in
/var/www/vhosts/XXXXXXX/httpdocs/wp-includes/formatting.php on line 3774`

`Notice: Array to string conversion in
/var/www/vhosts/XXXXXXX/httpdocs/wp-includes/formatting.php on line 3717`

3018288-t

**Comment by richardmtl** [comment]
3018393-t

**Comment by richardmtl** [comment]
3018800-t

**Comment by richardmtl** [comment]
3019304-t

**Comment by richardmtl** [comment]
#3019845-t

**Comment by richardmtl** [comment]
3020829-t
3020814-t
3021080-t

**Comment by aheckler** [comment]
3017053-t

**Comment by aheckler** [comment]
3017152-t

**Comment by richardmtl** [comment]
Interim solution for this issue: publish a post (but don't delete it or make it a draft after, it has to remain published).

**Comment by ntpixels** [comment]
3018571-t

**Comment by makemakeai** [comment]
Same result  following my deletion of Hello World!  

Warning: stripos() expects parameter 1 to be string, array given in /wp-includes/formatting.php on line 3774.  

Re-published so as to have at least one post, but then excluded posts from the XML SiteMap in effort to hide the post from search engines since the site is comprised of just "pages".

**Comment by richardmtl** [comment]
@makemakeai You can try the patch if you'd like:

https://github.com/Automattic/jetpack/pull/6142/files

Or wait until Jetpack 4.5.1 is released. If you do try it, let us know if that does it for you! :)

**Comment by estebangj1984** [comment]
Need help

Warning: stripos() expects parameter 1 to be string, array given in /var/www/vhosts/XXXXXXX/httpdocs/wp-includes/formatting.php on line 3774

**Comment by richardmtl** [comment]
@estebangj1984 Try publishing a new post, that should get rid of the error.

**Comment by WPprodigy** [comment]
523141-zd-woothemes

**Comment by lschuyler** [comment]
Also reported in 3009776-t

**Comment by eduardozulian** [comment]
3025732-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/stripos-expects-parameter-1-to-be-string/

**Comment by pmciano** [comment]
Reported 3020200-t

**Comment by tmmbecker** [comment]
3028341-t

**Comment by danjjohnson** [comment]
One user said that reinstalling VaultPress fixed the error. Worth a try ¯\_(ツ)_/¯

**Comment by richardmtl** [comment]
For what it's worth, publishing a post has worked 100% of the time for my users. Also, the patch will likely be in 4.5.1

**Comment by aheckler** [comment]
Just checked all tickets and thread here, and we've replied to them all up to this point. 👍

**Comment by rajchappeta** [comment]
Same problem with my site [sakalam.org](http://sakalam.org)--- stripos() expects parameter 1 to be string, there was no post but when i restore the post it was solved..

Thankyou.

**Comment by eliorivero** [comment]
Just an update that this is now fixed in the 4.6 beta that was released yesterday.

**Comment by aheckler** [comment]
@rajchappeta Yep, as long as you have one published post, this error can be avoided. It'll be fixed altogether in the next Jetpack release.

**Comment by Developer-K** [comment]
Hi - we are getting this error on a client's site. New project with latest WP, JetPack and add-on's. The new post addition did not work. Any help would be appreciated. In our case it may have to do with the google map parameters. 

Warning: stripos() expects parameter 1 to be string, array given in /XXXX/XXXX/public_html/wp-content/plugins/jetpack/modules/shortcodes/class.filter-embedded-html-objects.php on line 98

Warning: stripos() expects parameter 1 to be string, array given in /XXXX/XXXX/public_html/wp-content/plugins/jetpack/modules/shortcodes/class.filter-embedded-html-objects.php on line 92

**Comment by taupikrr** [comment]
I'm nothing
