### ISSUE TITLE
JITMs: Restyle to match calypso banners

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#6134]
Master Issue: https://github.com/Automattic/jetpack/issues/6135

> Right now there are only 3 JITMs and they are all marketing related. In the future we might want to create a styling differentiation based on whether its a marketing JITM or a feature or important notice JITM.
> 
> Currently JITMs are simple one-liners with a brand mark, an action button and a dismiss “x”.
> 
> I’d like to maintain the semi-inconspicuous look of the JITMs so they aren’t too “in your face” but I think the banner styles will do that well.

Current design:
<img width="782" alt="jitm-design" src="https://cloud.githubusercontent.com/assets/214813/22120986/13a5f26a-de50-11e6-904f-f84c8e18ef8c.png">

Proposed style changes to match calypso will be a slightly tailored design based on:
![screen shot 2017-01-19 at 11 58 26 am](https://cloud.githubusercontent.com/assets/214813/22120952/e4916180-de4f-11e6-88ae-7600ee1fb8ce.png)

cc @jessefriedman

**Comment by MichaelArestad** [comment]
@jeffgolenski are those currently implemented in Calypso?

**Comment by jeffgolenski** [comment]
Taken care of a while back in https://github.com/Automattic/jetpack/pull/7058#pullrequestreview-40390729
