### ISSUE TITLE
Design Polish for February

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#6135]
Synopsis: This master issue is to keep track of all the small—medium sized design janitorial issues to be cleaned up in the 4.6 release. 

Responsible: @jeffgolenski @MichaelArestad 
 
User experience: Various improved experience throughout Jetpack
  
Designs: Varied. See sub issues

Complete: 25%

Difficulty: 20
 
Last Updated: January 19, 2017

**Comment by rickybanister** [comment]
@jeffgolenski does this issue need to stick around?

**Comment by jeffgolenski** [comment]
Nope!
