### ISSUE TITLE
Warnings when print_r() is disabled for security reasons

### ISSUE THREAD

**Issue by jimmyandrade** [Automattic/jetpack#6141]
#### Steps to reproduce the issue
* I am using WordPress 4.7.1 with a custom theme;
* I have Jetpack 4.5 enabled with Development Mode via the ```JETPACK_DEV_DEBUG``` constant;
* I created a page with a Jetpack/Grunion contact from;
* I sent a message via this page;
* I received the message in my inbox.
#### What I expected
* Message would be sent and I could see the success message on my browser
#### What happened instead
I see the following on my browser:

Warning: ```print_r()``` has been disabled for security reasons in ```plugins/jetpack/modules/contact-form/grunion-contact-form.php``` on line 2043

Warning: Cannot modify header information - headers already sent by (output started at ```plugins/jetpack/modules/contact-form/grunion-contact-form.php:2043```) in ```wp-includes/pluggable.php``` on line 1179

**Comment by jimmyandrade** [comment]
Ok, it's not currently planned. Now I'm getting this error in a production environment.
What could I do to avoid this? My hosting provider doesn't allow me to "reenable" the print_r function...

👎

**Comment by jeherve** [comment]
@jimmyandrade While this is not on our roadmap right now, we may add it to our roadmap for a future release.
Until then, we accept Pull Requests from the community and will be happy to review and merge a request from you if you find a way to fix this in the Jetpack codebase.

Alternatively, do you know why your hosting provider doesn't allow you to use `print_r`? We could see about using an alternative solution in Jetpack, like `var_export`, but I'm afraid it would be blocked by your hosting provider as well.

**Comment by jimmyandrade** [comment]
# One possible idea to use in Pull Request

I think we could do something like this:

```php
function get_disabled_functions() {
   return explode( ',', ini_get( 'disable_functions' ) );
}
function fn_is_enabled( get_disabled_functions() ) {
   return !in_array( $function_name, $disabled );
}
if ( fn_is_enabled( 'print_r' ) ) {
   print_r(); // does the print_r stuff
}
elseif ( fn_is_enabled( 'var_export' ) ) {
   var_export(); // does the var_export stuff
}
else {
   // What else we can do?
}
```

It would be interesting if there were some automated way of looking for these functions in the Jetpack codebase so that we ensure that no insecure function is being called without ```fn_is_enabled()``` or similar.

# About disabled functions in the hosting provider.

Apparently, it's for security reasons. Locaweb, one of the most common hosting providers in Brazil - which is the provider I'm using - disables the following functions, in addition to print_r:

* apache_child_terminate
* crack_check
* crack_closedict
* crack_getlastmessage
* crack_opendict
* dl
* escapeshellarg
* escapeshellcmd
* exec
* fpassthru
* ini_restore
* leak
* pclose
* popen
* posix_getpwuid
* posix_kill
* posix_mkfifo
* posix_setpgid
* posix_setsid
* posix_setuid
* proc_close
* proc_get_status
* proc_nice
* proc_open
* proc_terminate
* psockopen
* shell_exec (shell-exec)
* symlink
