### ISSUE TITLE
Widgets: Namespace or change widget class names

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#6145]
In 3016571-t, a user reported a conflict with [this plugin](https://codecanyon.net/item/timetable-responsive-schedule-for-wordpress/7010836/comments).

The issue is that Jetpack and this plugin both define an `Upcoming_Events_Widget` class. Perhaps we should rename ours to be `Jetpack_Upcoming_Events_Widget`?

**Comment by jeherve** [comment]
Nice catch!

Until Jetpack 4.5.1 is out, one can remove the new Jetpack Upcoming Events Widget by adding the following to a functionality plugin:

```php
// Search for the Upcoming Events Widget.
function jeherve_upcoming_events_search( $widget ) {
	return strpos( $widget, 'upcoming_events_register_widgets' ) === false;
}

// Remove the Upcoming Events Widget.
function jeherve_remove_upcoming_events_widget( $widgets ) {
	$widgets = array_filter( $widgets, 'jeherve_upcoming_events_search' );
	return $widgets;
}
add_filter( 'jetpack_widgets_to_include', 'jeherve_remove_upcoming_events_widget' );
```
