### ISSUE TITLE
Module filtering is not always obvious

### ISSUE THREAD

**Issue by markjaquith** [Automattic/jetpack#615]
When you're playing with the module filters, it's easy to get into a state where you don't realize you're looking at a filtered view. It might be nice to offer a simple way (other than reloading the page) of returning to the default views. Maybe when you've filtered, there should be a section at the top of the control section that shows the filters you have, and offers a clear button.
## Prior art

Mint.com:
![Mint.com filtering](https://cloud.githubusercontent.com/assets/353790/3136231/491ac2b8-e83f-11e3-85a6-f30da250af94.png)

**Comment by eliorivero** [comment]
Closing since the new UI doesn't have filtering and the fallback at `admin.php?page=jetpack_modules` applies the filters instantly (without reloading) and is clear which ones are applied.
