### ISSUE TITLE
VideoPress: Different shortcodes used in the documentation and UI

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#6150]
We currently support both of these shortcodes:

`[wpvideo]`

and 

`[videopress]`

However our [current documentation](https://jetpack.com/support/videopress/) uses [wpvideo], whereas the media upload modal uses [videopress]. 

<img width="254" alt="slack-imgs" src="https://cloud.githubusercontent.com/assets/3676359/22223176/e9998cb2-e187-11e6-838a-06427f700223.png">

I guess we'll have to continue supporting both going forward, but which should we be using in the UI and the documentation?

**Comment by jeherve** [comment]
> which should we be using in the UI and the documentation?

I'd vote for updating the support docs, they're easier to update.

**Comment by dbtlr** [comment]
Given that we're starting to look at removing the branding for VideoPress as a whole, switching to wpvideo, while not the easier solution, might be the better one.

From a code perspective, this change isn't hard, it just requires getting bundled into a release.

**Comment by dbtlr** [comment]
While I'm not prepared to make this sort of change, as I'm not able to commit the time to supporting any updates, this would be a fantastic first issue for someone to hop in on and rack up a quick win.

**Comment by formosattic** [comment]
Closing this.  The screenshot and doc now both show `wpvideo`.

That's also the case on the WordPress.com doc: https://wordpress.com/support/videopress/#set-a-video-size-using-a-shortcode

![image](https://github.com/Automattic/jetpack/assets/15944096/04e543f0-53ec-476b-82d3-b9c71a1d7b76)
