### ISSUE TITLE
Ads: Downgrading from Premium or Business to Personal/Free should deactivate the WordAds module

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#6168]
#### Steps to reproduce the issue
1. Purchase Premium/Business and activate Ads on your site
2. Downgrade to Personal or Free.
3. Notice that the `wordads` module is still active and blank ad spaces are shown.

3026584-t

**Comment by aheckler** [comment]
3042269-t, turns out this also happens when you cancel your plan altogether

**Comment by jeherve** [comment]
Fixed in #6242
