### ISSUE TITLE
Publicize: Secondary users can't access Publicize settings

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#6169]
### Description of the problem
When a secondary user is logged in, but not connected to WordPress.com they are unable to see the publicize settings, but instead see a confusing message: 

Screenshot: https://cloudup.com/c6QwBRAjQXa

"To use Publicize, you’ll need to link your Jacobsjetpack account to your WordPress.com account using the link below.
If you don’t have a WordPress.com account yet, you can sign up for free in just a few seconds.
Link account with WordPress.com"

In this case, my primary user account is "Jacobsjetpack" and it IS connected to my WordPress.com account JacobSHere. The user I'm logged in with here is "Test User." If I attempt to connect this user to the same WP.com account it doesn't stay connected (as expected) If I connect it to a different WP.com account it connects, and I'm able to see the Publicize connections as expected. 

Steps to reproduce issue: 

1. Start with a normally connected Jetpack site
2. Create and login to secondary user account. 
3. Visit Settings → Sharing

I'm testing with my own site: 
- Site URL: https://jacobshere.wpsandbox.me/
- Jetpack Debug URL: http://jetpack.me/support/debug/?url=https%3A%2F%2Fjacobshere.wpsandbox.me%2F

User that reported this: 
- Site URL: http://www.ginterparkbc.org/
- Jetpack Debug URL: http://jetpack.me/support/debug/?url=http%3A%2F%2Fwww.ginterparkbc.org%2F
- Ticket ID / Forum thread ID / Chat ID: 3017366-t

copy-pasta'ed from @seejacobscott cc @jeherve

**Comment by oskosk** [comment]
Closing as this report looks confusing now.

About the wording in the notice

> To use Publicize, you’ll need to link your Jacobsjetpack account to your WordPress.com account using the link below

Currently what's shown there is the Site's title, not the username. This is what a secondary account on the site sees (Administrator too). This user is not connected to .com

![image](https://user-images.githubusercontent.com/746152/31899740-d1be8fa6-b7f2-11e7-9612-fad849132aeb.png)

This is what a user with a secondary account connected to WordPress.com (a different .com account from the one used by the connection's owner ) sees currently:

![image](https://user-images.githubusercontent.com/746152/31900797-0817cd44-b7f6-11e7-9006-be5cd807b791.png)

**Comment by Uranbold** [comment]
That Seconday Users need to configure it again?

I think admin will only configure it once and it will be available to all registerd users. Any User Roles?

Thanks.
