### ISSUE TITLE
Change checkboxes to toggles

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#6173]
These checkboxes should all be converted into toggles.

- [x] Every checkbox in the spelling and grammar advanced options (Fancy options)
- [x] The metadata checkbox in the media section to show meta info in carousel
- [x] The infinite scroll checkboxes (do we even need the first checkbox setting there?)
- [x] Sub-settings for the mobile theme
- [x] The Subscriptions checkboxes
- [x] The WordPress.com login checkbox.
- [x] All the sub-settings for Site Stats.

CC @tyxla to do the same in Calypso (if not done already)

**Comment by tyxla** [comment]
Thanks for the ping, @MichaelArestad! Here is the progress of those in Calypso:

> Every checkbox in the spelling and grammar advanced options (Fancy options)

We haven't started implementing these yet.

> The metadata checkbox in the media section to show meta info in carousel

This PR is in progress - #10925, cc @oskosk to verify it's done there.

> The infinite scroll checkboxes (do we even need the first checkbox setting there?)

✅ 

> The Subscriptions checkboxes

✅ 

> The WordPress.com login checkbox.

Does that refer to the "Stay signed in" checkbox in https://wordpress.com/wp-login.php ?

**Comment by beaulebens** [comment]
@tyxla that last one (WordPress.com login checkbox) refers to these 2 (only exists in Jetpack):

![screen shot 2017-01-26 at 4 26 54 pm](https://cloud.githubusercontent.com/assets/108942/22354806/490514f6-e3e4-11e6-9f5a-a6514e13d4c6.png)

**Comment by beaulebens** [comment]
Updated the checklist to include a few more.

**Comment by eliorivero** [comment]
Done in Jetpack in https://github.com/Automattic/jetpack/pull/6237 awaiting review.

**Comment by eliorivero** [comment]
Closed in #6237
