### ISSUE TITLE
Admin: Jetpack Disconnection dialog

### ISSUE THREAD

**Issue by keoshi** [Automattic/jetpack#6184]
We currently have a few endpoints were users can disconnect Jetpack, and each of those leads to a different exit experience.

The biggest problem, however, is that none of those surface the benefits when it most matters. Disconnecting Jetpack does not simply deactivate the plugin — it breaks the connection with WordPress.com, and that could mean breaking the editorial flow, that their site is no longer protected, parts of site can stop working, and even the site could stop responding, among others.

Ideally in the dialog below, we would be able to pull the top three most important features a site uses regularly (from a prioritized list we maintain), and show them to our users, making sure the value of Jetpack is mirrored.

![image](https://cloud.githubusercontent.com/assets/390760/22356438/719ece48-e3d5-11e6-9c6b-adb32d4ed7f5.png)

Related: https://github.com/Automattic/jetpack/pull/6159

cc @eliorivero

**Comment by keoshi** [comment]
cc @ashleighaxios for design/copy review — thank you!

**Comment by ashleighaxios** [comment]
Love this idea. 

**Current Content (for easy reference):**
> Disconnect Jetpack
> You're about to disconnect Jetpack and WordPress.com from your website.
> This means features offered by WordPress.com will be missing. Read carefully before proceeding.
> Your custom domain will no longer work
> Premium plan benefits won't be available
> Your team won't be able to manage the site using WordPress.com
> [button] Stay Connected
> [button] Proceed
> Read More about Jetpack benefits

**Suggested Content (italicized where there are changes from the above):**
> Disconnect Jetpack
> You're about to disconnect Jetpack and WordPress.com from your website.
> _If you disconnect, you will experience the following changes:_
> Your custom domain will no longer work
> _Your <link - open in new tab>premium plan</link> benefits won't be available_
> Your team won't be able to manage the site using WordPress.com
> [button] Stay Connected
> [button] _Disconnect_
> _Read more about Jetpack benefits_

**Design:**
I like it. Small thoughts:
- I might make the icons a grey so that those don't appear clickable.
- The link below the buttons is a subtle grey. In this case, I might make it blue since we do want to discourage the customer from selecting it. I might even place it above the buttons since we want them to consider the implications first.

**Comment by eliorivero** [comment]
I'm working on this on #6729.
Before I move forward, what would the texts would be for Jetpack free users?

**Comment by eliorivero** [comment]
As per a convo in slack with @rickybanister we're going with https://github.com/Automattic/wp-calypso/pull/11972

**Comment by samhotchkiss** [comment]
Fixed by #6729
