### ISSUE TITLE
Settings: Discusion > Comments; wrap text away from help icon

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6195]
Make sure to wrap text in cards away from the (?) in the top right corner, to avoid situations like this:

![screen shot 2017-01-27 at 1 40 38 pm](https://cloud.githubusercontent.com/assets/108942/22386857/34b75984-e496-11e6-95bb-63456c18c4bb.png)

**Comment by eliorivero** [comment]
Fixed in #6392
