### ISSUE TITLE
Settings: Discussion > Comments; align help icons better

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6196]
Line up the (?) icons properly with the labels they are about:

![screen shot 2017-01-27 at 1 41 21 pm](https://cloud.githubusercontent.com/assets/108942/22386895/5ac3b0c8-e496-11e6-97e4-31d5b547904b.png)

**Comment by beaulebens** [comment]
Related: #6273

**Comment by MichaelArestad** [comment]
Closing this as it's a duplicate of #6273.
