### ISSUE TITLE
Settings: Discussion > Comments label change for Jetpack Comments

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6197]
To make the most sense in the most places, I think the label on this toggle should just be

"Let readers use WordPress.com, Twitter, Facebook, or Google+ accounts to comment"

![screen shot 2017-01-27 at 1 42 37 pm](https://cloud.githubusercontent.com/assets/108942/22386968/a686872e-e496-11e6-89f8-de35c103f403.png)

**Comment by eliorivero** [comment]
Fixed in #6258
