### ISSUE TITLE
Settings: Update (?) help icons to work like Calypso

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6198]
First, in Jetpack we have:

![screen shot 2017-01-27 at 1 49 19 pm](https://cloud.githubusercontent.com/assets/108942/22387140/6a4e8ea4-e497-11e6-9a36-b6ee952fb874.png)

while in Calypso, it's:

![screen shot 2017-01-27 at 1 49 35 pm](https://cloud.githubusercontent.com/assets/108942/22387147/7433896a-e497-11e6-9a88-21c4121345ce.png)

More importantly though, in Calypso when you click one, they always open a tooltip, which then either directly tells you about what you need to know, or offers you a link to an external help document, in a new window (also notice the clicked/active state of the (i) ):

![screen shot 2017-01-27 at 1 49 47 pm](https://cloud.githubusercontent.com/assets/108942/22387171/94ca6748-e497-11e6-9b0e-5499afa33bf6.png)

Ideally we could probably explain most of these settings directly within the tooltip, but for now we can just introduce the tooltip, and have a link to the support doc in there.

**Comment by eliorivero** [comment]
Fixed in #6430
