### ISSUE TITLE
Settings: Remove toggle outlines unless using keyboard navigation

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6199]
Match Calypso by removing the outlines which appear on toggles, unless you're using the keyboard to navigate. Currently looks like this:

On/off:
![screen shot 2017-01-27 at 1 52 43 pm](https://cloud.githubusercontent.com/assets/108942/22387243/e3b66f78-e497-11e6-8b2e-d0eb8505feb3.png)

On/off, when clicked:
![screen shot 2017-01-27 at 1 53 01 pm](https://cloud.githubusercontent.com/assets/108942/22387256/f8f80ffe-e497-11e6-8a54-6511780d289b.png)
![screen shot 2017-01-27 at 1 53 06 pm](https://cloud.githubusercontent.com/assets/108942/22387257/f90006e6-e497-11e6-94f9-58176b27239d.png)

**Comment by zinigor** [comment]
Looks like this has been fixed either with compact toggles update, or with a dops-components updating the outline navigation.
This is what I see now only when I tab navigate to the toggle:
![enabled](https://cloud.githubusercontent.com/assets/374293/23066254/f8773310-f532-11e6-8f10-612d29b3f841.png)

...and this is when it's disabled:
![disabled](https://cloud.githubusercontent.com/assets/374293/23066257/fe6f1062-f532-11e6-98f0-0ee8e2478fca.png)

Please reopen if you still experience the issue.
