### ISSUE TITLE
Likes: Like notifications sent to the blog owner instead of the post author

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#620]
Steps to reproduce:
1. Install and activate Jetpack, and connect it to your WordPress.com account
2. Log out of both your WordPress and WordPress.com account
3. Log back in with another account, an editor on the site for example
4. Link that account to another WordPress.com account
5. Write and Publish a Post
6. Log out of both accounts.
7. In another browser, Like that post
   - The Like notification is sent to the first account that was used to make the connection, not to the posts author.

**Comment by oskosk** [comment]
I've just tested this and confirmed this is no longer an issue. Got a notification on my poster account instead of the blog owner's one.
