### ISSUE TITLE
Settings: Remove "external" icon from some links to avoid confusion

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6202]
Remove icon from link, which can be reasonably confused with "this will open a new window" (but it doesn't):

![screen shot 2017-01-27 at 1 56 41 pm](https://cloud.githubusercontent.com/assets/108942/22387361/724e170e-e498-11e6-95c5-138f3c5ec5b5.png)

- [x] Discussion > Subscriptions
- [x] Security > Backups and security scanning
- [x] Traffic > Search engine optimization

**Comment by eliorivero** [comment]
Closed in #6252
