### ISSUE TITLE
Settings: Discussion > Subscriptions; change checkboxes for toggles, and remove SAVE button

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6203]
Checkboxes should be toggles, and then remove the SAVE SETTINGS button, since the toggles will save immediately.

![screen shot 2017-01-27 at 1 58 34 pm](https://cloud.githubusercontent.com/assets/108942/22387401/b59db596-e498-11e6-94c8-3ac5f7bb6817.png)

**Comment by eliorivero** [comment]
Closed in #6237
