### ISSUE TITLE
Success notices in the admin should disappear automatically

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6204]
We fire notices for a lot of things within the admin UI:

![screen shot 2017-01-27 at 2 00 05 pm](https://cloud.githubusercontent.com/assets/108942/22387457/f53174cc-e498-11e6-908d-6097d2d0aba9.png)

![screen shot 2017-01-27 at 2 00 14 pm](https://cloud.githubusercontent.com/assets/108942/22387458/f5339798-e498-11e6-80df-1c37be1bd5e4.png)

Success messages should just fade out/go away after a second or 2. I don't think we even need the "progress" type ones most of the time ("Updating settings...").

**Comment by eliorivero** [comment]
Closed in #6285.
