### ISSUE TITLE
Settings: Discussion > Subscriptions; disable, but show sub-settings

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6205]
Disable, instead of hiding the sub-settings for Subscriptions. Currently:

![screen shot 2017-01-27 at 2 05 13 pm](https://cloud.githubusercontent.com/assets/108942/22387610/a6279b12-e499-11e6-8437-63a7be18795c.png)
![screen shot 2017-01-27 at 2 05 18 pm](https://cloud.githubusercontent.com/assets/108942/22387611/a628ac78-e499-11e6-8f94-d14a927e965e.png)

**Comment by eliorivero** [comment]
Fixed in #6237
