### ISSUE TITLE
Settings: Security > Antispam; API Key field required (and remove other option)

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6206]
We don't need the "show number of approved" option here at all, just enable it and remove the UI for it.

![screen shot 2017-01-27 at 2 11 37 pm](https://cloud.githubusercontent.com/assets/108942/22387787/89aa8bd8-e49a-11e6-8467-165511f4363b.png)

What we _do_ need though, is a field where you can access/change your API key.

Normally I'd say that it should be behind an "Advanced Options" link, but since it will be the only thing in this card now, it can probably just be there?

**Comment by MichaelArestad** [comment]
Redundant: https://github.com/Automattic/wp-calypso/issues/12195

**Comment by MichaelArestad** [comment]
Not redundant. It should look like what @ashleighaxios proposed for Calypso.

![image](https://cloud.githubusercontent.com/assets/1123119/24050264/ef3de4fc-0af3-11e7-9dbe-3626447944ed.png)

**Comment by eliorivero** [comment]
Closed in #6696
