### ISSUE TITLE
Settings: Security > WordPress.com log in label updates

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6209]
Change label to "Allow users to log into this site using WordPress.com accounts."

Change two-step label to "Require accounts to use WordPress.com Two-Step Authentication."

![screen shot 2017-01-27 at 2 18 40 pm](https://cloud.githubusercontent.com/assets/108942/22387994/84e8f5d4-e49b-11e6-8ba3-02e9202be0ab.png)

**Comment by eliorivero** [comment]
Fixed in #6258
