### ISSUE TITLE
Stats: show the stats chart in the admin bar in the Dashboard

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#621]
We currently have an option to include a chart that contains the last 48 hours of stats in the admin bar. It currently only shows on the front end of the site. 

If the user has this option enabled under Jetpack > WordPress.com Stats > Configure, we should also show the chart while logged in to the Dashboard.

Original ticket in Trac:
- https://plugins.trac.wordpress.org/ticket/1951

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/48hrs-stats-graph-missing-in-admin-bar?replies=3&view=all

**Comment by roccotripaldi** [comment]
This has been pending for awhile, any movement, or should we close?

**Comment by jeherve** [comment]
It is still a problem, especially since the sparkline is one of the slowest elements of Jetpack in the dashboard, and some of us had done quite a lot of work to improve it (see #1416).

I think it'd be nice to finalize #1416 and ship it soon, it'd be a huge win for Jetpack, it would help beat the performance hit the sparkline adds to a site as soon as you enable the Stats module.

**Comment by roccotripaldi** [comment]
@dereksmart: I'm adding this to 3.8 milestone. could we re-open #1416 and assign it to an appropriate person?

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
