### ISSUE TITLE
Settings: Spacing/font-size on some cards is off

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6210]
- [ ] Weird spacing at the top of the card should be consistent with others (this space looks too big, I think because the first tag is a `p`, and they have top and bottom margins currently).

![screen shot 2017-01-27 at 2 24 33 pm](https://cloud.githubusercontent.com/assets/108942/22388161/559e0d4a-e49c-11e6-89cb-8434b8e938cd.png)

`font-size` is also too small here. Its computed value is 13px, vs 14px elsewhere.

**Comment by beaulebens** [comment]
Same spacing and font size issues can be seen on Traffic > Site verification:

![screen shot 2017-01-27 at 2 33 32 pm](https://cloud.githubusercontent.com/assets/108942/22388419/a818af48-e49d-11e6-8868-d99a95ab9d09.png)

**Comment by beaulebens** [comment]
Also Writing > Custom Content Types:

![screen shot 2017-01-27 at 2 43 26 pm](https://cloud.githubusercontent.com/assets/108942/22388689/f9e2643a-e49e-11e6-95c0-c65e949e7344.png)

**Comment by eliorivero** [comment]
First two fixed in #6377
Last one in #6389
