### ISSUE TITLE
Settings: Traffic > Site stats; better layout/labels for the advanced options

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6211]
Better layout on the headings of Advanced Options.

Currently;
![screen shot 2017-01-27 at 2 28 52 pm](https://cloud.githubusercontent.com/assets/108942/22388250/f0b7f688-e49c-11e6-99d5-26e818dacbb3.png)

Proposed;
![screen shot 2017-01-27 at 2 31 50 pm](https://cloud.githubusercontent.com/assets/108942/22388356/5bbaa50c-e49d-11e6-856f-1042e2f7761b.png)

**Comment by eliorivero** [comment]
Fixed in #6390
