### ISSUE TITLE
Settings: Writing > Composing; fix the layout/headings of the advanced options

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6213]
Layout of the Advanced Options (especially the headings used) could use some cleanup, or maybe some better/different spacing would be enough to make it all make sense:

![screen shot 2017-01-27 at 2 36 17 pm](https://cloud.githubusercontent.com/assets/108942/22388502/0e8a1ae6-e49e-11e6-9560-673f6317a134.png)

I think it should be:

- [toggle] Automatically detect which language you're using
- Automatically proofread content when
  - [toggle] A post or page is first published.
  - [toggle] A post or page is updated.
- Enable proofreading for
  - [toggle] Bias language
  - [toggle] Cliches
(etc)

Note I changed the order and some wording/labels to try to make it a bit clearer, but having that toggle at the top level (Automatically detect language) might still be awkward since the next 2 are really headings on top of "lists" of options.

**Comment by beaulebens** [comment]
Just realized that I "dropped" the information about which languages are supported, so that might need to be moved to a (?) bubble or something perhaps?

**Comment by eliorivero** [comment]
Fixed in #6391
