### ISSUE TITLE
Settings: Writing > Custom content types spacing

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6215]
When both custom content types are enabled, the spacing between the Configure Testimonials button and the Portfolio label is too small:

![screen shot 2017-01-27 at 2 45 12 pm](https://cloud.githubusercontent.com/assets/108942/22388735/526a75e8-e49f-11e6-8a99-d6248dc72bbf.png)

**Comment by eliorivero** [comment]
<img width="735" alt="captura de pantalla 2017-02-01 a las 20 13 08" src="https://cloud.githubusercontent.com/assets/1041600/22530568/df5ed0d8-e8ba-11e6-9487-94db352b826e.png">

They look like this now in latest `feature/settings-overhaul`.
