### ISSUE TITLE
Settings: Should be firing Tracks stats on most UI interactions

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6217]
We need to go through the entire settings UI, and make sure that toggles/inputs/etc are instrumented properly for Tracks.

**Comment by zinigor** [comment]
### Trackable interactions:
- [ ] Page changes
- [ ] At a Glance widget toggles
- [ ] Tab changes
- [ ] Settings page toggles
- [ ] Settings page checkboxes
- [ ] Settings page submit buttons
- [ ] Settings search terms
- [ ] Settings search zero results occurences
- [ ] Users leaving for Calypso
- [ ] Users leaving for WP Admin settings

@beaulebens I have compiled this list based on what possible interactions I could come up with. Can you please take a look and tell me if I have missed something and if maybe some of these don't make sense.

**Comment by beaulebens** [comment]
That's a good starting list.

I *think* page/tab changes should be handled by a global "view change" event already, if not then we should be able to bring that across from Calypso, which definitely does.

For the last 2, we should ideally add Tracks to all links in the UI (header down to footer), so that we know when someone clicked on any specific link, and then that'll tell us what they were trying to do. Again, there are examples of how this works in Calypso. Along these lines, pages like "Apps" and "Plans" should have all of their buttons/links instrumented, so that we can tell what people are actually using there, to prioritize things in the future. Also don't forget any feedback/help links that appear in headers etc.

Remember what we're measuring here is, broadly "how are people interacting with the UI", so that we can use that information to help guide improvements etc, and make them targeted to how people actually interact with things, rather than how we think they might.

**Comment by dereksmart** [comment]
> I think page/tab changes should be handled by a global "view change" event already, if not then we should be able to bring that across from Calypso, which definitely does.

Yep, page/tab views will automatically be tracked via https://github.com/Automattic/jetpack/blob/feature/settings-overhaul/_inc/client/main.jsx#L155

**Comment by dereksmart** [comment]
Tracks has been scattered throughout :)
