### ISSUE TITLE
Remove footer disconnect link

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6219]
To keep flows consistent:

- [x] Remove the "Disconnect Jetpack" link from the footer of the UI
- [x] On the "Debug" page, add a "Disconnect from WordPress.com" link

The preferred way of disconnecting will be through the main UI (General tab within settings).

![screen shot 2017-01-27 at 3 54 17 pm](https://cloud.githubusercontent.com/assets/108942/22390576/13343a4e-e4a9-11e6-81cb-9d844a6710b6.png)
![screen shot 2017-01-27 at 3 55 41 pm](https://cloud.githubusercontent.com/assets/108942/22390577/1334449e-e4a9-11e6-9477-6426c077533f.png)

**Comment by eliorivero** [comment]
Closed in #6255
