### ISSUE TITLE
Notices: update styles to match Calypso, specifically max width

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6221]
Currently, you can get some wild notices appearing like this:

![screen shot 2017-01-27 at 3 59 47 pm](https://cloud.githubusercontent.com/assets/108942/22390698/e6ff2a0a-e4a9-11e6-94db-c1af61fa5b90.png)

Ideally we should never throw an error that long, but at least we should wrap them to a reasonable width. Styles are already updated in Calypso, so we just need to port them over.

**Comment by rickybanister** [comment]
I think a good short-term solution is to get a list of these unwieldy errors and rewrite some of them. Even if this notice had a max-width, that's still pretty rough to read. 

Notices in Calypso have had their markup changed a bit recently and styles updated with many improvements to the responsive/narrow styles for them. 

Could I get some assistance, perhaps @eliorivero can help me take a look at getting things copied over?

**Comment by eliorivero** [comment]
On one side, these errors were rewritten in https://github.com/Automattic/jetpack/commit/c08ae01e7e3cfbfa17d8c9a6bf84d81daef4f065#diff-2ccec9069213650359171727de9a2471
Here (I forced this error) is a sample of the same error.
<img width="859" alt="captura de pantalla 2017-02-02 a las 14 55 08" src="https://cloud.githubusercontent.com/assets/1041600/22561626/c4f39448-e957-11e6-874f-880e08d84364.png">
I'll look into porting the notice updates to dops.

**Comment by rickybanister** [comment]
That error has quite a bit of redundancy. Couldn't we just say `We couldn't enable the after-the-deadline module`

Better yet we would say why we can't enable it so the user has some kind of path forward.

**Comment by samhotchkiss** [comment]
Fixed by Elio already (PR has been lost to the ages)
