### ISSUE TITLE
Settings: Move connection information to dashboard

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6222]
We currently have a "General" tab in the Settings:

![screen shot 2017-01-27 at 4 07 05 pm](https://cloud.githubusercontent.com/assets/108942/22390848/d12f4cfe-e4aa-11e6-8763-ae7646c60bac.png)

Those 2 cards should be moved to the bottom of the Dashboard (with the heading "Connection") and the "General" tab should be removed completely from Settings.

**Comment by MichaelArestad** [comment]
Generally speaking, I'll be glad to see General retired.

**Comment by eliorivero** [comment]
I agree with moving it to dashboard. It's a tab with elements that are not settings like the others.

**Comment by MichaelArestad** [comment]
@eliorivero The design will remain the same. These will be moved just below the Performance section in their own "Connection" section.

**Comment by eliorivero** [comment]
Fixed in #6287
