### ISSUE TITLE
Settings: Security > Backups and scanning card re-think

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6223]
We need to rethink this card a bit to make sure it's hitting all the requirements (API keys, status, etc), and also think through the different states it can exist in:

1. User has no plan, so we don't show the card at all, we show a banner telling them about purchasing a plan
2. A plan is purchased, but this service is not configured/installed properly. Help the user get set up properly
3. Everything is set up and working properly, so just showing current status, and any useful information, plus the ability to modify API key.

![screen shot 2017-01-27 at 4 19 21 pm](https://cloud.githubusercontent.com/assets/108942/22391098/616c9e92-e4ac-11e6-9964-ef9e178eaa94.png)

**Comment by MichaelArestad** [comment]
Closing in favor of #6405
