### ISSUE TITLE
Settings: Add updated Ads card under Traffic

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6224]
Need to add in a card for controlling Ads (when appropriate plan is purchased). It goes between the Related Posts and Site Verification cards.

Note: if the user doesn't have a plan which enables Ads, then we will not display this, and will have a banner promoting this service (separate issue will be created for that)

![image](https://cloud.githubusercontent.com/assets/1123119/22391964/e3e93ed4-e4b1-11e6-9404-4904e00ded87.png)

Note the TOS link goes to `https://wordpress.com/automattic-ads-tos/`, earnings link goes to `https://wordpress.com/ads/earnings/{site-slug}` and the help link should go to `https://jetpack.com/support/ads/`

**Comment by MichaelArestad** [comment]
My bad on this. The disabled state should be visible. Not hidden. The ToS thing should go away on activation, though.

**Comment by MichaelArestad** [comment]
CC @dbspringer

**Comment by dbspringer** [comment]
@beaulebens @MichaelArestad Is there a thread somewhere I can follow with the plan for the UI updates? Timelines, examples in progress, etc?

**Comment by beaulebens** [comment]
[The project](https://github.com/Automattic/jetpack/projects/3#card-1520962) this issue is a part of is the most complete version, and if you check out the `feature/settings-overhaul` branch, you'll see the latest. Timeline is "hopefully next major release" :)

**Comment by MichaelArestad** [comment]
@dbspringer I believe this and the banner (upgrade notice) are the last two immediate things required for WordAds for now. The next steps with it will likely be seeing if we can iterate on the WordAds section in Calypso, but that's not planned or in the timeline yet.

**Comment by dbspringer** [comment]
Is this already being worked on? I'm fine with picking it up, just out of the loop with who is working on what.

**Comment by MichaelArestad** [comment]
@dbspringer Nope. All yours if you want to tackle it. @eliorivero or @zinigor can help you with whatever you need to jump in to the code.

**Comment by eliorivero** [comment]
@dbspringer we're currently working creating small branches against `feature/settings-overhaul`. Feel free to ping me in Slack for anything you need.

**Comment by dbspringer** [comment]
@MichaelArestad @eliorivero First cut at the new Ads setting card. https://github.com/Automattic/jetpack/pull/6319

Is there any UI/logic for gating paid features similar to the current Jetpack release? A la
<img width="793" alt="screen shot 2017-02-07 at 3 13 10 pm" src="https://cloud.githubusercontent.com/assets/273708/22715898/027171e8-ed48-11e6-8052-5b5a70e956fc.png">

**Comment by dbspringer** [comment]
Also, what is the status of upgrade notices? Is there a design/plan I can take a look at?

**Comment by eliorivero** [comment]
Looking great @dbspringer!

I think it's ok where you placed them, right below SEO in Traffic tab.

The upgrade notices will be implemented using the new Banner component from Calypso. Here's the PR that @zinigor has been working at.
https://github.com/Automattic/jetpack/pull/6189

**Comment by MichaelArestad** [comment]
@dbspringer 

#### Re: gating
If you're referring to the paid buttons, we're no longer using them in favor of using upgrade banners.

#### Re: notices
There is a PR open for them [ https://github.com/Automattic/jetpack/pull/6189 ], but the component itself is already available.

**Comment by eliorivero** [comment]
Added in #6319
