### ISSUE TITLE
Settings: Writing > Media needs an option for Video

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6225]
We need a single toggle to enable/disable video upload/hosting on WordPress.com.

Suggestion is under the Writing > Media group.

Note that this toggle would not be included until someone purchases a plan which includes video hosting. They would see a banner promoting the plan instead.

**Comment by MichaelArestad** [comment]
It should be on by default when plan is purchased. When available (purchased), it should probably be the first thing in the media group in a section above Photon. The label should be something like this:

> Use WordPress.com's unbranded customizable premium video player

**Comment by dereksmart** [comment]
Solved in #6655
