### ISSUE TITLE
Settings: Update Monitor DashItem to link to notification settings in Calypso

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6226]
Design TBD.

This is pending addition of downtime notification options to the notification settings area. https://github.com/Automattic/wp-calypso/issues/11021

**Comment by MichaelArestad** [comment]
This could be as simple as this:

![image](https://cloud.githubusercontent.com/assets/1123119/22530062/35d87c3a-e897-11e6-893c-e19ecebbfa92.png)

Alternatively, the button could say "Configure"

**Comment by eliorivero** [comment]
Fixed in #6433
