### ISSUE TITLE
Settings: Writing; need a prompt of some sort for Tiled Galleries

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6227]
We should have a prompt (JITM?) of some sort telling people about Tiled Galleries.

Could have it when they create a new post/insert media/create a gallery?

Something that tells them they have these new gallery options (which will be enabled by default). Note that their use is tied to Photon/"Speed up images and photos", which needs to be turned on for galleries to work.

Needs some more thought/possibly design.

**Comment by MichaelArestad** [comment]
Quick initial thought:

![image](https://cloud.githubusercontent.com/assets/1123119/22530636/b82d9556-e899-11e6-836f-495c8fe8f1e5.png)

The banner would have a different icon (probably `camera`) and a dismiss button.

We could also squeeze it in the column to the right (it's a responsive banner) much closer to the controls.

**Comment by beaulebens** [comment]
Nice, I think something like this could work.

@dbtlr / @georgestephanis I know you've both dabbled pretty heavily in the media modal; do you know how possible something like this is in here? I seem to recall it not being super flexible/hookable.

**Comment by dbtlr** [comment]
@beaulebens Overriding the media modal in my experience is difficult because you need to override the entire template in many circumstances. While this is possible, it makes Jetpack more brittle to downstream WordPress changes, as if the underlying template changes, we need to now support templates for each version of WordPress.

I think @georgestephanis had greater success with this than I did though, so he might know of an additional technique.

**Comment by georgestephanis** [comment]
@beaulebens Yup, it's totally doable.

Basically what we do is make an intermediate function that calls the original function instead, and then add our custom code.  So, something like ...

```js
var oldRenderMethod = wp.mce.whatever;
wp.mce.whatever = function(){
    // do things before
    oldRenderMethod.call( this );
    // do things after to what the render just output on the page
}
```

**Comment by jeffgolenski** [comment]
@MichaelArestad Yes, excellent. All our JITMs everywhere need to be built to follow this format. Looks great. Also, the camera icon should be used, as you mentioned.

**Comment by simison** [comment]
I don't think is valid anymore since we have Gutenberg blocks now.

There's a wider generic issue of nudging users about blocks but this can be closed.
