### ISSUE TITLE
"Jump Start" feature is broken

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#6229]
#### Steps to reproduce the issue
1. Install and activate Jetpack 4.5
2. After connecting, on the Jump Start page, click "Skip this step" 
3. Nothing happens
4. Open the JS console, there will be a JS error - "Cannot read property 'views_today' of undefined"
5. Try clicking Activate Recommended Features
6. Still nothing
7. Try clicking Settings under the Jetpack menu
8. ... nope.

#### What I expected
Clicking "skip this step" would skip to the settings page

#### What happened instead
JS errors!

#### Browser
Chrome 55 on OS X Sierra 10.12.3

Video: https://cloudup.com/c6SiPuIGvEq

**Comment by dereksmart** [comment]
Closing this, the duplicate issue in #6646 has more details and we can track there.
