### ISSUE TITLE
README: Add instructions and details about the testing environment needed for running the Jetpack PHP test suite.

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#6236]
It's cumbersome to figure out that one needs an specific WordPress environment for running Jetpack test suite depending on `phpunit`. 

#### Steps to reproduce the issue

1. Clone this Repo.
1. Run `phpunit` on the Jetpack directory.
1. Confirm that tests fail and don't run appropriately.
2. Find PHP testing instructions in the README file.
3. Exactly.

#### What I expected

To be at least informed of the details provided by something like this post:

https://jetpack.com/2013/08/20/unit-tests/

#### What happened instead

People has to figure it out on their own.

**Comment by jeherve** [comment]
I pushed f0db4b803e5b2b510c7df7fcc33042e39256b7c0 to #5985 to include some basic information about Unit Tests to the future documentation.

If you'd like to add more details, let me know or commit to the branch directly.

Thanks!
