### ISSUE TITLE
Bug: Random, site crashing exception

### ISSUE THREAD

**Issue by EatonZ** [Automattic/jetpack#6238]
Hi, Jetpack Monitor informed me that my site was down. I wasn't doing anything with it at the time, so I checked logs and this is in PHP errors multiple times:

`[31-Jan-2017 03:57:00 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_bloginfo() in C:\home\site\wwwroot\wp-includes\class-http.php:184
Stack trace:
#0 C:\home\site\wwwroot\wp-includes\class-http.php(593): WP_Http->request('https://jetpack...', Array)
#1 C:\home\site\wwwroot\wp-includes\http.php(170): WP_Http->get('https://jetpack...', Array)
#2 C:\home\site\wwwroot\wp-content\plugins\jetpack\class.jetpack.php(5514): wp_remote_get('https://jetpack...')
#3 C:\home\site\wwwroot\wp-content\plugins\jetpack\class.jetpack.php(5429): Jetpack::validate_sync_error_idc_option()
#4 C:\home\site\wwwroot\wp-content\plugins\jetpack\class.jetpack-idc.php(50): Jetpack::check_identity_crisis()
#5 C:\home\site\wwwroot\wp-content\plugins\jetpack\class.jetpack-idc.php(41): Jetpack_IDC->__construct()
#6 C:\home\site\wwwroot\wp-content\plugins\jetpack\class.jetpack-idc.php(692): Jetpack_IDC::init()
#7 C:\home\site\wwwroot\wp-content\plugins\jetpack\jetpack.php(93): require_once('C:\\home\\site\\ww...')
#8 C:\home\site\wwwroot\wp-settings.php(304): inclu in C:\home\site\wwwroot\wp-includes\class-http.php on line 184`

Any idea what happened here? Unfortunately I have no steps on reproducing it, since it just kind of happened out of nowhere.

**Comment by jeherve** [comment]
That's odd, since `get_bloginfo()` is a core WordPress function:
https://developer.wordpress.org/reference/functions/get_bloginfo/

If it's not defined, it would mean something is wrong with your WordPress installation.

Did you manage to get your site back up? If so, what did you do to solve the issue?

**Comment by EatonZ** [comment]
@jeherve A WordFence scan indicates no immediate problems.

Restarting the site's app pool resolved it.

PHP 7.0.7
WinCache 2.0.0.6
IIS 8.5

**Comment by jeherve** [comment]
Thanks! If this happens again let us know!
