### ISSUE TITLE
Debugger: Include additional information

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#624]
Broad ticket to determine what aspects of a site would be helpful to add to the debugger contact support system.

Inspired by http://wordpress.org/plugins/send-system-info/

Related: #391 

cc: @jeherve, @richardmtl

**Comment by kraftbj** [comment]
I'm going to propose including the entire `$_SERVER` variable. If other things are specifically helpful, they should be under new tickets.

**Comment by jeherve** [comment]
I'm not sure we'd want to do that, since some people store private site credentials in their `$_SERVER` variables.

**Comment by kraftbj** [comment]
@jeherve +1 I'll update the branch to be more surgical in the request.
