### ISSUE TITLE
Related Posts: Incompatible with WP-Minify

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#625]
The [WP-Minify](https://wordpress.org/plugins/wp-minify/) breaks Related Posts. Should we force ourselves to work around it?

While the plugin has an option to exclude URLs including "relatedposts" (e.g. `?relatedposts=1`), it seems to lack a filter for us to add this ourselves.

It does include an option to exclude a URL through a `wp-minify-off=1` GET parameter. 

Could we add this when the `WPMinify` class is present and do we want to handle conflicts like this?

cc: @xyu

**Comment by kraftbj** [comment]
@xyu With the infrastructure to create routes in 4.4, is this something you are interested in pursuing?

**Comment by xyu** [comment]
I'm thinking a even better way to go about it is to not use any of the rewrite paths. Instead just always append query parameters to `index.php?p=123&...` for the ajax calls which would be backwards compatible and not require new routes to be created.

**Comment by cena** [comment]
WP Minify hasn't been updated in [7 years.](https://wordpress.org/plugins/wp-minify/)
