### ISSUE TITLE
Add WordPress.com toolbar navigation module to Jetpack (aka Masterbar)

### ISSUE THREAD

**Issue by vindl** [Automattic/jetpack#6254]
Improves the experience for Jetpack authors when they've transferred their WordPress site from WordPress.com to a self-hosted plan by providing a similar experience to the front-end navigation on WordPress.com.

**Comment by lancewillett** [comment]
This type of functionality greatly improves the experience of managing multiple WordPress sites because with the core WP toolbar you can only see and manage one site at a time.

The improved toolbar would enable a site owner or site manager to get back to the Calypso UI easily to manage my site and other Jetpacks and WP sites.

**Comment by jeherve** [comment]
When implementing this, would we keep the existing admin bar below the master bar? I'm asking because a lot of plugins (Jetpack included) add extra labels in the admin bar, and losing those would be quite confusing for a lot of people.

**Comment by vindl** [comment]
@jeherve that's not the case - our current plan is to replace it completely with WordPress.com master bar. It's worth pointing out that this would only happen when the master bar module is active (it will be turned off by default). There is an ongoing discussion about it here p3fqKv-4kf-p2 - any suggestions and feedback would be greatly appreciated.

**Comment by eliorivero** [comment]
We no longer have the General tab in the new settings UI so we'll need to have a discussion with @MichaelArestad if we're going to add this in the new UI and where.

If you want to see the new UI, check `feature/settings-overhaul` and build it.

**Comment by MichaelArestad** [comment]
I want to wait on any decisions about this until we have a better idea of what is implemented. I don't think there should be a setting if we can avoid it.

**Comment by vindl** [comment]
Resolved in https://github.com/Automattic/jetpack/pull/6413.
