### ISSUE TITLE
Add JITM for Holiday snow activation/deactivation

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#6260]
In the new settings UI, there is no way to enable/disable Holiday snow. Let's see if we can use the Banner component or something to enable/disable it when nearing the holiday season. (maybe even something fancy like a notification)

**Comment by gravityrail** [comment]
Closed because feature is removed in Jetpack 6.0.

**Comment by jeherve** [comment]
Reopening as snow is back: #9110

**Comment by jeherve** [comment]
#9110 is not going to be merged, closing.
