### ISSUE TITLE
Remove `module-headings.php` from version control

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#6265]
`module-headings.php` is an automatically compiled file which occasionally results in some pretty weird stuff if people forget to build it when changing headers. Let's just remove it from git.

- [ ] We should probably move the built file to the build folder
- [ ] We should also add it's build to the watch task

**Comment by dereksmart** [comment]
> pretty weird stuff
What kind of weird stuff?

Moving this out of the Settings UI milestone
