### ISSUE TITLE
Move the support links inline at the end of each label

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#6273]
This should only be for the second group of controls in the Comments settings group:
![image](https://cloud.githubusercontent.com/assets/1123119/22570485/b8d43d1a-e958-11e6-861a-0998a652ce0f.png)

Alternatively, we could just remove the support links for these in favor of a regular ol' link like in Calypso (probably the better solution here): 
![image](https://cloud.githubusercontent.com/assets/1123119/22570547/147fdcfa-e959-11e6-9f8a-f96024f1a7a0.png)

**Comment by eliorivero** [comment]
Is this strictly necessary? Give how the toggle works now (if click the label, it toogles), we can't put the icon or clickable text in the toggle label without refactoring the `CompactFormToggle` dops component.
These buttons are now aligned in https://github.com/Automattic/jetpack/pull/6430 so if it's ok, I'd rather not update the toogle in dops but of course if it's necessary, we can do it.

**Comment by eliorivero** [comment]
props to @dsmart for finding out that a plan link in the label didn't trigger the toggling.

I've made the change of adding the text link in #6273

**Comment by eliorivero** [comment]
Fixed in #6430
