### ISSUE TITLE
Sync: Sync wait time conditionals comparing seconds to microseconds

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#6282]
In `Jetpack_Sync_Sender`, it appears that there are some conditionals that are comparing seconds to microseconds.

For example, check out this line: https://github.com/Automattic/jetpack/blob/master/sync/class.jetpack-sync-sender.php#L90

Now, if we check how `set_next_sync_time` is called:

Here's an example that is called [here](https://github.com/Automattic/jetpack/blob/master/sync/class.jetpack-sync-sender.php#L113): 

```php
$this->set_next_sync_time( time() + $this->get_sync_wait_time(), $queue->id );
```

Notice how we're adding seconds to a value and then passing that to `set_next_sync_time.

**Comment by enejb** [comment]
So I think this is probably working as intended. 
@ebinnion Do you remember what issues this might be causing? 


```
print_r(  [ time(),  microtime( true ) ] );
Array
(
    [0] => 1522970363
    [1] => 1522970363.3332
)
```

**Comment by ebinnion** [comment]
@enejb unfortunately I don't. From memory, I don't think it was an actual bug, but something that seemed a bit off at the time. If you're fine with how things are now, I'd say we just close.
