### ISSUE TITLE
Twitter Widget: refactor widget settings for easier setup and less confusion.

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6290]
2 things could be improved:

1. *To use the No Scrollbar” option, you should not specify a number of tweets in the widget settings, and check the “No Scrollbar” option.*  We could make this more obvious in the UI by greying out the noscrollbar option when you specify a number of tweets, for example.
2. The "Widget Type" and the "Username" settings could be higher in the settings since they're required for the widget to work.

cc @jeffgolenski

**Comment by welenofsky** [comment]
I tried to tackle this in this PR #13853. Let me know if I was off base or could make any improvements. Saw the Hacktoberfest label and wanted to give it a try.
