### ISSUE TITLE
Notifications: JavaScript error in 4.6 beta

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#6294]
In the 4.6 beta, and in latest master as of writing this, I'm getting JS errors for notifications.

The notes script that's being loaded is:

http://s1.wp.com/wp-content/mu-plugins/notes/notes-common-v2.js?ver=4.6-beta1-201705

I only notice the JS error when I'm on the Jetpack react pages.

When those pages load, I get this error:

`Uncaught TypeError: _.contains is not a function`

Then, if I click the notifications button, I get more errors such as:

`Uncaught TypeError: this.currentMasterbarActive.addClass is not a function`

I'm not sure how to milestone this since all of the milestones were deleted. cc @samhotchkiss cc @dereksmart 

![screen shot 2017-02-03 at 11 51 43 pm](https://cloud.githubusercontent.com/assets/1126811/22616139/45e08448-ea6c-11e6-86a7-c5185e2df798.png)

**Comment by ebinnion** [comment]
It looks like this might still be an issue for multisite installations, so reopening.

**Comment by eliorivero** [comment]
Can you test with latest dops again? I pushed [a change that might solve this](https://github.com/Automattic/dops-components/commit/86fb970390f89ec1647d58e1737bbb66373e4de0) to fix other places with lodash imports that were overwriting the `_` object.
