### ISSUE TITLE
Related Posts is permanently disabled if you edit settings via Customizer

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#6323]
#### Steps to reproduce the issue

1. On a fresh install (or with freshly-deleted jetpack_relatedposts options), enable the Related Posts module
2. Go into the customizer and edit Related Posts settings (e.g. disable show date)
3. Save

#### What I expected

Date is hidden

#### What happened instead

Related Posts is permanently disabled and there's no way to re-enable it!

#### Suggested solution

If we haven't enabled the UI which shows the "toggle" option for whether RP's are enabled, they should ALWAYS BE ENABLED since otherwise there's no way to switch them on. 

Right now the only workaround is for users to implement something like this in an mu-plugin:

```php
<?php

add_filter( 'jetpack_relatedposts_filter_allow_feature_toggle', 'enable_rp_feature_toggle' );

function enable_rp_feature_toggle( $val ) {
	return true;
}
```

and then manually re-enable RP's in the Reader settings every time they change a setting.

**Comment by richardmtl** [comment]
At least two more reports today:

3052392-t
3052572-t

**Comment by lezama** [comment]
great finding sir

**Comment by graylaurenm** [comment]
Worked for me! Thanks to Paul (ticket #3034557) for directing me here.

**Comment by aheckler** [comment]
3054180-t

**Comment by lschuyler** [comment]
3050277-t

**Comment by aheckler** [comment]
3087199-t
