### ISSUE TITLE
Improve the support block in JP dashboard

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/jetpack#6334]
The support block at the bottom of the settings tabs is due an iteration. Things to consider:
- Rethink copy
- Reduce links to one CTA
- Make CTA a button?
- Reinforce to paid customers that they're entitled to priority support
- Pitch an upgrade to a paid plan to get priority support
- Possibly revisit use of avatars 

cc @MichaelArestad @jeffgolenski

**Comment by ashleighaxios** [comment]
Conversation and comps here: https://jpopdesignp2.wordpress.com/2017/02/09/improve-the-support-block-in-jp-dashboard

**Comment by jeffgolenski** [comment]
Fixed in: https://github.com/Automattic/jetpack/pull/6387
