### ISSUE TITLE
Sharing: can't add custom sharing services anymore

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6348]
In #5832 we added more custom variables to the Jetpack custom sharing button. Unfortunately, it seems we've also broken sharing buttons in the process.

#### Steps to reproduce the issue

1. Go to Settings > Sharing
2. Click on "Add New Service"
3. Paste the following values in the sharing modal:
`technorati`
`http://technorati.com/faves?add=%post_url%`
`http://icons.iconarchive.com/icons/fasticon/social-bookmark/256/Technorati-icon.png`
4. Create the share button.
5. Drag it to the active sharing buttons area.
6. Save your changes. As the page reloads, you'll notice that the service title has disappeared.

Reported here:
https://wordpress.org/support/topic/add-new-service/

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/added-new-sharing-service-buttons-not-working/

**Comment by aldobelus0** [comment]
Please, solve it as soon as possible. We want to have this buttons working...
