### ISSUE TITLE
VideoPress closed caption support

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#6350]
VideoPress supports subtitles / closed captions (see: https://videopress.com/v/AHz0Ca46) but it is not currently exposed by the Jetpack VideoPress UI. The feature does have a UI on http://wordpress.tv/, but it is custom for that platform.

Since this feature already exists in the back end, it would be great to offer it to users.

**Comment by jeherve** [comment]
cc @kovshenin and @iandunn, who may know why the feature is currently limited to only a few WordPress.com sites.

**Comment by iandunn** [comment]
I'm not really sure. My best guess would be that is was opened for WPTV to get some real-world testing, and that the plan was to eventually offer to it all sites.

IIRC, @nickmomrik worked on it, so he might have some insight.

**Comment by nickmomrik** [comment]
I touched it a bit to get the subtitles working for the new player for WPTV. If I recall, the code and UI would need some love before we'd want to open it up for all users. Not sure if it's on the roadmap at all. cc @dbtlr

**Comment by dbtlr** [comment]
@nickmomrik In terms of roadmap, 99% of all Jetpack related VideoPress updates are now being handled by the Pitcrew. Our only roadmap for right now is to make sure that a thumbnail chooser exists in Calypso. Otherwise, VideoPress is now Jetpack Video and the only thing I'll be maintaining is the player itself and the plumbing.

Regarding subtitles, this is the first time I've heard it come up. You may know more about what is needed here as I have yet to see any code related to this feature.

**Comment by StefMattana** [comment]
User asking about this on #1837248-zen

**Comment by joker1541** [comment]
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script> <script>   (adsbygoogle = window.adsbygoogle || []).push({     google_ad_client: "ca-pub-2563103144365406",     enable_page_level_ads: true   }); </script>

**Comment by jeremypaavola** [comment]
User asking in 2247788-zen

**Comment by coder-karen** [comment]
Requested in 2478823-zen

**Comment by mikeicode** [comment]
Requested 2496408-zen

**Comment by bikedorkjon** [comment]
2504976-zen

**Comment by joweber123** [comment]
Requested by user here as well 18415306-hc

**Comment by juliasydnor** [comment]
requested by 2791655-zen

**Comment by samhodge** [comment]
Three years? What is people have no sound? They get nothing from my video, I have been burning in subtitles, I will look into wordpress.tv

**Comment by jeherve** [comment]
@samhodge Until this is implemented in Jetpack, I would recommend using this workaround:
https://jeremy.hu/wordpress-subtitles-video/

Another alternative could be to try a different video provider; I believe YouTube for example allows one to add subtitles to a video.

**Comment by snowmads** [comment]
Requested in 2828600-zen

**Comment by kognat-docs** [comment]
> @samhodge Until this is implemented in Jetpack, I would recommend using this workaround:
> https://jeremy.hu/wordpress-subtitles-video/
> 
> Another alternative could be to try a different video provider; I believe YouTube for example allows one to add subtitles to a video.

I tried that approach, the edit icon is no longer available.

Can you update the documentation?

Sam

**Comment by jeherve** [comment]
> the edit icon is no longer available.

Once you click on the video, the Edit button should appear, like so:

![Screen Recording 2020-04-01 at 08 45 AM](https://user-images.githubusercontent.com/426388/78107229-5c3e7400-73f5-11ea-96b0-9c3be0a5940d.gif)

**Comment by kognat-docs** [comment]
![nodice](https://user-images.githubusercontent.com/62274503/78190766-2a441500-74bc-11ea-9fa4-acbb91439981.gif)
Being on the same side of the screen as me there is a different perspective.

**Comment by jeherve** [comment]
@kognat-docs Could you try following the instructions in the post here?
https://jeremy.hu/wordpress-subtitles-video/

You'll want to use a Classic block, and not a Video block like on your Gif.

**Comment by kognat-docs** [comment]
![C061BA01-0A61-4282-819F-733129530A4C](https://user-images.githubusercontent.com/62274503/78295666-06dca100-7574-11ea-99bd-49da2c2bf0b8.png)

Missed steps 4-6 altogether so sorry for being a dunce

**Comment by andrepetrini** [comment]
Any updates on having subtitles for VideoPress videos?

**Comment by jeherve** [comment]
@andrepetrini No, not at the moment, but we'll update this issue when we start working on that part of the Jetpack product again.

**Comment by jenhooks** [comment]
Requested in 3243896-zen

**Comment by rickmgithub** [comment]
Requested - 3849756-zen.

**Comment by StefMattana** [comment]
+1 4091073-zen

**Comment by jeherve** [comment]
This was implemented in #21578
