### ISSUE TITLE
Quick Edit on Post saves all in html instead of Markdown syntax

### ISSUE THREAD

**Issue by shihkuang** [Automattic/jetpack#636]
When using the quick edit function on post list, the content will be saved as html instead of Markdown syntax.

It happens when I updated the post title and slug.

**Comment by synapticism** [comment]
I'm also experiencing this... glad to know what the root cause is (using quick edit) so at least I can avoid destroying the Markdown content for any more of my posts.

**Comment by blueliquiddesigns** [comment]
Had the same issue and submitted a PR to fix the problem (I can't believe a problem like this has been left open for over a year?!).

**Comment by shprink** [comment]
+1

**Comment by jeherve** [comment]
Fixed in #2978.

@shprink I'd suggest updating 3.8.1 and see if that helps!
