### ISSUE TITLE
Carousel- Slides moves - page scrolling to top -	jQuery carouFredSel 6.2.1

### ISSUE THREAD

**Issue by prabhumachismo** [Automattic/jetpack#6361]
#### If carousel banner is visible on the screen, when slides are rolling then the page is scrolling to top of the page, please help me out on this issue.

Jquery plugin:
jQuery carouFredSel 6.2.1

Reference link:
http://www.resmed.com/us/en/index.html

**Comment by jeherve** [comment]
I'm afraid we won't be able to help, as you don't seem to be using WordPress or the Jetpack plugin on that site.

I can only recommend that you get in touch with the authors of that js library or the person who developed your site about this.
