### ISSUE TITLE
Sync Queue: Don't Fatal when an SimpleXmlObject is passed to it

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#6373]
We had a user report that a custom plugin was producing this error

Message: 'Serialization of 'SimpleXMLElement' is not allowed'
File:'/wp-content/plugins/jetpack/sync/class.jetpack-sync-queue.php'

To reproduce the error 
$x = simplexml_load_string( '<x></x>');
var_dump( serialize( $x ) );

Lets make sure that plugins can pass us simleXMLElements without the queue braking.

**Comment by csonnek** [comment]
Noting user email reference here: 3053278-t

**Comment by enejb** [comment]
Closing this since it didn't come up since more then a year ago.
