### ISSUE TITLE
Publicize: Update comment to indicate WP.com function

### ISSUE THREAD

**Issue by chmac** [Automattic/jetpack#6379]
https://github.com/Automattic/jetpack/blob/master/modules/publicize/publicize.php#L263

	/**
	* Fires when a post is saved, checks conditions and saves state in postmeta so that it
	* can be picked up later by @see ::publicize_post()
	*/

I've grep'd the whole codebase like crazy, but I can't find the `publicize_post()` method. If I'm grepping correctly, then this comment wants removing.

**Comment by kraftbj** [comment]
It is correct-ish. Publicize is spread out across a couple of codebases with a shared base, then Jetpack- and WordPress.com-specific bits.

That file is shared between the two and publicize_post() is only in WP.com. When a post is published either on WP.com or Jetpack, meta is saved to indicate if a post should be Publicized. On a Jetpack site, the post and meta are sent to WP.com. Then, on WP.com, publicize_post() is ran and checks that meta as part of an asynchronous job.

The comment should be updated to reflect which codebase that function lives in.

**Comment by chmac** [comment]
OK, makes sense. Of course the requests end up being pushed to wp.com servers, didn't think about that aspect.

I'm happy to submit a PR with a tweaked comment if that's helpful.
