### ISSUE TITLE
Shortcode Embeds: Breaks embeds of previously published posts

### ISSUE THREAD

**Issue by seejacobscott** [Automattic/jetpack#6380]
When the Jetpack module "Shortcode Embeds" is active links to previously published posts are not embedding the preview, but instead showing the URL. 

Replication steps: 

1. Disable Shortcode Embeds
2. Add new post, paste URL for an already published post into visual editor
3. You should see something like this, with an embedded preview of the post: https://cloudup.com/cZlcPgtuT8H
4. Enable Shortcode embeds
5. Repeat step 2. 
6. Now, when pasting the link, it will not expand and offer the preview, but instead keep it as a plain URL: https://cloudup.com/cjtSDSkYQOO

What I expected: 
Post preview embeds to work regardless of that module's activation. 
What happened instead: 
Post preview embeds failed with it active. 

Reported in 3056403-t and https://wordpress.org/support/topic/embed-articles-suddenly-doesnt-work-anymore/

**Comment by richardmtl** [comment]
3035636-t

**Comment by csonnek** [comment]
Another one: 3030216-t

**Comment by csonnek** [comment]
3066483-t

**Comment by chaselivingston** [comment]
3073224-t
