### ISSUE TITLE
SSO: Occasional missing token errors when logging in with WP.com

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#6388]
It has been reported by some users that email us directly, so no ticket reference, that they occasionally get missing token errors.

I'm creating this issue to help gather information about when/why the issue happens.

**Comment by kevinfodness** [comment]
I have experienced this issue as well. It is intermittent, occurs on both cached and non-cached sites, and happens even though the nonce changes each time. I've confirmed this on multiple sites, one of which is running latest WP/Jetpack/etc with the Twenty Sixteen theme and very few other plugins active.

The specific error message is "Invalid Nonce."

**Comment by csonnek** [comment]
@kevinfodness noting your internal ticket number here for reference: 3073652-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/error-invalid-nonce-for-all-jetpack-connected-sites/

**Comment by amitmalewar** [comment]
I have experienced this issue as well. **Error: Invalid Nonce.** 
Sometimes clearing browser cookies helps.

**Comment by jeherve** [comment]
#6571 seems to fix the issue for me.

**Comment by jeherve** [comment]
Reopening as the problem seems to keep happening.

**Comment by madhattermattic** [comment]
Also present in 3099339-t

**Comment by lolux** [comment]
I'm seeing `Error: Invalid nonce` returned regularly on multiple sites running on different hosts. 

This error is returned *sometimes* on initial login attempts and *almost* every time on re-login attempts. To reproduce the latter:

1. assuming Jetpack SSO is activated, log in via Jetpack SSO button on wp-login.php
1. log out
1. attempt to log back in via Jetpack SSO button

Expected result: log in; actual: invalid nonce error.

**Comment by richardmtl** [comment]
Another report in 3099772-t ; any information we can ask for that can help?

**Comment by amitmalewar** [comment]
**CloudFlare** users can add page rule for: `https://*domain.com*`
**Rules:**

- Cache Level: Bypass
- Disable Performance

**Comment by rralian** [comment]
Can we re-test this? We've made a fix on the wpcom side which should address many if not all of these issues. It was an issue where one particular server (out of many) was not correctly setting memcache values. Hence it was intermittent.

**Comment by lolux** [comment]
@rralian re-tested SSO logins on my sites this morning. All is working normally. 💥

**Comment by rralian** [comment]
Awesome! I'm closing this for now, but if it comes up again we can re-open.

**Comment by richardmtl** [comment]
Fixed for 3099772-t. 👍
