### ISSUE TITLE
Carousel: carousel opens even if clicking around/near an image in a gallery

### ISSUE THREAD

**Issue by cristianfrumusanu** [Automattic/jetpack#6397]
Testing with WordPress 4.7.2, Jetpack 4.6, Twenty Seventeen theme, Chrome Version 56.0.2924.87 (64-bit), macOS 10.12.3.

#### Steps to reproduce the issue
I created a **thumbnail grid** gallery in a **regular post**. Then I went to see the post.

#### What I expected
To click near an image in the gallery or between the gallery images and nothing to happen.

#### What happened instead
The carousel opened by clicking near the image, on any `figure.gallery-item`'s padding area.
Furthermore, the first image opens in carousel regardless of what `figure.gallery-item` padding area is clicked.

The correct behavior occurs only when clicking directly on the image.

Here's a screen recording: https://cloudup.com/cp9K9idnhgg

**Comment by jeherve** [comment]
I cannot seem to reproduce this issue anymore. I'll close it, since there haven't been any other reports. We can always reopen in the future if needed.
