### ISSUE TITLE
Content Options Comment Link

### ISSUE THREAD

**Issue by dmtrmrv** [Automattic/jetpack#6398]
Hey, guys! Was working on implementing _Content Options_ to my latest theme today and noticed that  _Post Details_ section doesn't have an option to show/hide comment count link. (https://monosnap.com/file/QJ4PEWy6LYj9qvNM9CSJMFOHNL4a7g)

Is there a specific reason for not including it? Many themes (including Twenty Sixteen) are using it. Also noticed that Twenty Seventeen doesn't.

Do you plan on adding this feature? Any clarification would be awesome. Thanks!

**Comment by jeherve** [comment]
cc @thomasguillot

**Comment by thomasguillot** [comment]
Hi @dmtrmrv, we never really thought about the comments link but that's a great idea and we will definitely add the option in a near future. Thanks!

**Comment by dmtrmrv** [comment]
Sounds great! Thanks for replying so quickly. Let me know if I can somehow help make it happen.

**Comment by thomasguillot** [comment]
This has been added to Content Options a while ago

**Comment by dmtrmrv** [comment]
@thomasguillot I know this issue is closed, but it doesn't look like this feature was added. It doesn't work if I add the code related to comments to the theme: `'comment' => '.comments-link'` as suggested in the [article](https://jetpack.com/support/content-options/). Am I missing something? Thank you!

**Comment by pratikshrestha** [comment]
I confirm as this not working as described here: [Content Options](https://jetpack.com/support/content-options/)

**Comment by thomasguillot** [comment]
I apologise. I thought we added the functionality to Jetpack a while ago. But we didn't. I have a pending PR to fix the issue :)

**Comment by thomasguillot** [comment]
The functionality was merged to Jetpack with https://github.com/Automattic/jetpack/pull/7023
