### ISSUE TITLE
Update design of the Security and Backups group

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#6405]
The proposal is to move the status into the header as a compact notice. They will need to remain ultra short.

There will also be some copy added:

```
Don't worry about data loss, downtime, or hacking. Jetpack <PLAN> scans for malicious code and backs up all your data.
```

(where <PLAN> is the current plan like: "Jetpack Premium") We could also just drop the plan reference.

![image](https://cloud.githubusercontent.com/assets/1123119/22937896/4da13652-f2da-11e6-9c83-555d25fadc63.png)

**Comment by eliorivero** [comment]
Closed in #6687
