### ISSUE TITLE
Settings UI: no way to activate sharing or publicize

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#6411]
#### Steps to reproduce the issue
`wp jetpack module deactivate sharedaddy`
`wp jetpack module deactivate publicize`

#### What I expected
I expected there to be some UI to allow me to activate these features

#### What happened instead
The sharing tab disappears and there's no clear way to activate them. 

![screen shot 2017-02-14 at 2 39 42 pm](https://cloud.githubusercontent.com/assets/7129409/22945804/73e9f946-f2c3-11e6-869c-0a44595bb04b.png)

**Comment by MichaelArestad** [comment]
I have two proposals depending on how far along moving the [sharing settings in Calypso is](https://github.com/Automattic/wp-calypso/issues/11023). Basically, just add a toggle that enables and disables each section (module) to each section.

## Proposal for current Sharing UI:
![image](https://cloud.githubusercontent.com/assets/1123119/23143892/31cbd224-f781-11e6-8e9b-ffb44735c89e.png)

![image](https://cloud.githubusercontent.com/assets/1123119/23143889/2883b844-f781-11e6-94cd-fabedad17a41.png)

## Proposal for proposed Sharing UI [[#](https://github.com/Automattic/wp-calypso/issues/11023)]:
![sharing-proposal](https://cloud.githubusercontent.com/assets/1123119/23143962/ac0dfabc-f781-11e6-9713-7ced7b877d9f.jpg)

**Comment by eliorivero** [comment]
What happens on Jetpack's side? Will we have the Sharing tab always visible? Social buttons are until now available in dev mode, will they continue to be? Because a site in dev mode doesn't have a shadow site in wpcom.

**Comment by MichaelArestad** [comment]
>Will we have the Sharing tab always visible?

What are the alternatives?

I lean toward leaving them visible unless they are filtered off (still need filters to be made).

>Social buttons are until now available in dev mode, will they continue to be?

Currently, yes since we can fall back to the old one. In the future, until we get the social/sharing stuff into JP's settings, we may have to keep the old one around.

**Comment by dereksmart** [comment]
> I lean toward leaving them visible unless they are filtered off

FWIW I'm totally on board with this

**Comment by MichaelArestad** [comment]
@dereksmart just to recap after our hangout Friday, we are going to leave these visible unless they are filtered off. Even if they are disabled in JP previously, they should be visible in Calypso. If a user starts trying to use one of the two modules in Calypso, we'll enable it for them.

**Comment by dereksmart** [comment]
@MichaelArestad 

> If a user starts trying to use one of the two modules in Calypso, we'll enable it for them.

That sounds nice.  Is this behavior already possible? Do we still need to rely on a toggle? If it's not ready yet, who is responsible for making that happen?  Is there an issue for it?

**Comment by MichaelArestad** [comment]
> That sounds nice. Is this behavior already possible?

I don't know. CC @tyxla and @oskosk 

> Do we still need to rely on a toggle?

> If it's not ready yet, who is responsible for making that happen?

@tyxla and @oskosk

**Comment by tyxla** [comment]
@MichaelArestad I'd be happy to create those! Have we decided which one from the suggestions we'll go with?

**Comment by MichaelArestad** [comment]
@tyxla The plan in Calypso is:

* Show the sharing/publicize settings whether the module is on or off.
* If the module is off and a user tries to use the sharing or publicize settings, it should be automatically turned on.
* There is no way to disable them via UI.
* There will be a way to disable them via filter in which case we wouldn't show it at all.

Does that make sense?

**Comment by tyxla** [comment]
@MichaelArestad I think what you suggest here contradicts to the mockups above, but I might be misunderstanding something, so please correct me if I'm wrong. I've also asked a couple of questions in p6TEKc-HQ-p2. I also think it makes sense to continue discussing the Calypso-related implementation in an issue in Calypso - feel free to create one under the Jetpack Settings in Calypso milestone.

**Comment by dereksmart** [comment]
Closing.  The solution is going to be that we're always showing the sharing tab, and they will be able to activate/deactivate either sharing/publicize from that interface.
