### ISSUE TITLE
Settings UI: no way to deactivate sharing or publicize

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#6412]
With Sharing/publicize active, you get kicked to calypso to manage your settings for the modules.  However, there is no way in either UI to deactivate the features completely.  

Related #6411

**Comment by MichaelArestad** [comment]
Proposal here: https://github.com/Automattic/jetpack/issues/6411#issuecomment-281197534

**Comment by dereksmart** [comment]
Closing.  The solution is going to be that we're always showing the sharing tab, and they will be able to activate/deactivate either sharing/publicize from that interface.
