### ISSUE TITLE
Settings UI - Search: make state when field is cleared always consistent

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#6416]
When you start searching, all setting cards are visible. If you reload or follow a link straight to `#search`, no setting cards are visible.

To make it consistent, we should never display any card while in search mode and when the field is empty. This is how the settings search in iPhone and Android works so some people will be familiar.

**Comment by zinigor** [comment]
While I agree about making it consistent with other search experiences, but disappearing content when you have just clicked a search button is not a very good thing for a settings interface, is it? We can go the other way and just redirect a user to `/settings` when they open a page with no history and no search term.

**Comment by eliorivero** [comment]
> We can go the other way and just redirect a user to /settings when they open a page with no history and no search term.

Yes, I'm ok with that 👍  Just keep in mind that when you reload, there is history, but no search term.

**Comment by dereksmart** [comment]
Fixed in #6424
