### ISSUE TITLE
Contact Form: improve workflow for editing existing forms

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#642]
Right now, if you want to edit an existing contact form, you have to click on "Add Contact Form", make your changes, and then click on "Add this form to my post" to replace the existing form on the page.

To avoid any confusion, would it be possible to change the wording of the 2nd link to "Update form"?

Suggested in 1856847-t

**Comment by jimmyandrade** [comment]
@georgestephanis using wpviews to let someone edit a shortcode would be great. Following...

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/cant-edit-contact-form?replies=3&view=all

**Comment by davoraltman** [comment]
I didn't find this reported anywhere and just wanted to share my two cents. It's currently confusing how to edit a form and I am definitely in favor of updating the wording for both buttons.

**Comment by jeherve** [comment]
Related project to bring editor views to the Contact Form module:
https://github.com/Automattic/gm2016-grunion-editor
