### ISSUE TITLE
Upgrade banner finesse

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#6449]
As promised, let's go ahead and fine-tune these banners to be as perfect as can be. For "ease of review," I have screenshots of each of the banners and which plans they are visible for.

There are four plans that step up in this order: Free, Personal, Premium, Professional

We should be reviewing placement, copy, and deciding whether to use a button instead of an arrow. 

**Note:** There is a display bug that will be addressed elsewhere with the arrow overlapping the text.

### Premium video
![image](https://cloud.githubusercontent.com/assets/1123119/23142933/bbedc526-f77b-11e6-9ead-f6022a1b3e66.png)

**Visible for:** Free, Personal

### SEO 1
![image](https://cloud.githubusercontent.com/assets/1123119/23142984/0c43f4d2-f77c-11e6-83a9-ccefc36d5a3e.png)

**Visible for:** Free, Personal

### SEO 2
![image](https://cloud.githubusercontent.com/assets/1123119/23143087/a8c41b34-f77c-11e6-8910-5ae2af0bc53b.png)

**Visible for:** Premium

**Difference:** No longer shows Ads selling point

### Backups and security 1
![image](https://cloud.githubusercontent.com/assets/1123119/23142996/1ddabc94-f77c-11e6-9c33-ef34b4d83593.png)

**Visible for:** Free

### Backups and security 2
[NOT IMPLEMENTED YET]

**Visible for:** Personal

**Difference:** No longer shows Akismet selling point

### Backups and security 3
This is up for debate. We could still offer a nudge to those on the premium plan to upgrade to get real time scanning and unlimited/realtime backups. I lean towards not having it.

CC @richardmuscat @ashleighaxios @rickybanister

**Comment by richardmuscat** [comment]
Quick feedback @michaelarestad:
- overall great way of outlining these
- the video upgrade is tiered (13Gb premium / unlimited Pro) so we need two versions of that
- why do you lean towards not upwelling the Pro plan on the realtime scanning and backups (and auto fixes)? what's the reason?

Will review text separately. How would you prefer me to do that? Commit against branch? Something else?

**Comment by MichaelArestad** [comment]
> why do you lean towards not upwelling the Pro plan on the realtime scanning and backups (and auto fixes)? what's the reason?

@richardmuscat I think it's largely because we're selling a premium product. I wouldn't expect my premium product to upsell me unless necessary (size limitations for example). It's because of this I don't think we need the video nudge until they are somewhat close to running out of space. I think it'll feel more timely to kind of bundle things like that when it makes sense for the user to upgrade from premium. For example: "You are getting low on video storage space. Upgrade to Pro to get unlimited space, realtime backups, one click threat resolution, and priority support." That seems more welcome to me and shows we're keeping the customer's best interest in mind.

> Will review text separately. How would you prefer me to do that? Commit against branch? Something else?

Either a PR or an issue work well. I'll edit my original issue with links to those discussions as they arise. Discussion here is also fine.

**Comment by richardmuscat** [comment]
Agreed!

**Comment by rickybanister** [comment]
Where are we with the clickable card vs call-to-action button? WordPress.com has only used the clickable card style so far to some success. Since this is ready should we get it merged, continue to wrap up settings, and make adding a button our next priority after settings is otherwise ready to launch?

**Comment by MichaelArestad** [comment]
@richardmuscat Any update on changes to this?

**Comment by zinigor** [comment]
Please see updated versions of banners in #6659

**Comment by eliorivero** [comment]
Closed in #6659
