### ISSUE TITLE
Banner component: arrows (and probably more) collide with content

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#6450]
The actions are colliding with the info. I suspect it's a missing class or something similar.

#### Steps to reproduce the issue
* switch to `feature/settings-overhaul`
* be on a free or personal plan
* go to settings
* maybe resize viewport

#### What I expected
![image](https://cloud.githubusercontent.com/assets/1123119/23143370/58bd7598-f77e-11e6-8d39-235c493d90d3.png)

#### What happened instead
![image](https://cloud.githubusercontent.com/assets/1123119/23143330/0f06e1be-f77e-11e6-968b-ce505d9edf3c.png)

**Comment by zinigor** [comment]
Fixed by https://github.com/Automattic/dops-components/pull/98, the arrow seems to collide with text only on very narrow screen widths. Please reopen if that's a problem.

**Comment by MichaelArestad** [comment]
@zinigor that is the exact problem and it will be an even bigger one when we start using buttons instead of the arrow.

**Comment by zinigor** [comment]
@MichaelArestad actually I was confused, I have left a comment for you on the dops-components PR. There's a problem with style precedence that if solved would make text behave properly.

**Comment by MichaelArestad** [comment]
Fixed here https://github.com/Automattic/dops-components/pull/98
