### ISSUE TITLE
Showing Toolbar to non-owner WordPress.com users

### ISSUE THREAD

**Issue by vindl** [Automattic/jetpack#6453]
Prior to transfer to self-hosted site: every logged-in WordPress.com user would see the Toolbar when viewing the front-end of a site that is going to be transferred.

After transfer to self-hosted site: When viewing the front-end of a transferred site, only site owners will be able to see the Toolbar that we are now introducing in Jetpack.

Do we need to make it work for all WordPress.com logged-in users? If so - we need a way to detect them, and also to fetch some of the data that is needed to render the My Sites and Me submenus correctly (e.g. their primary blog, blavatar, avatar, number of blogs etc).

**Comment by roundhill** [comment]
I've explored our options with this, and haven't found anything that I think will solve this problem. Suggesting we get to this at a later time.

There's an admin-ajax script that we use for the forums to load the admin bar via JS, but I think we'd be much better off if the Jetpack code could handle the rendering for these visitors. We can't access the wp.com logged in cookie, so we'd probably need some other way of determining if a user is signed in to wp.com.

**Comment by vindl** [comment]
We are not going to implement this in the first version of WordPress.com Toolbar.
