### ISSUE TITLE
SVG in Social Menus: missing CSS

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6469]
I seem to be missing the stylesheet to style the SVG icons added in #6096. I believe we'll need to add it to `gulpfile.js` to make sure it gets bundled in the concatenated file:
https://github.com/Automattic/jetpack/blob/master/gulpfile.js#L279

@thomasguillot Could you take a look at this?

Thanks!

**Comment by dereksmart** [comment]
> I believe we'll need to add it to gulpfile.js

Yes this should be all you need to do

**Comment by thomasguillot** [comment]
Oh dear, I'm sorry I've just submitted a fix in 124e6c8. I messed up and committed it to `Master`.

**Comment by jeherve** [comment]
@thomasguillot 124e6c8285bfb1dee6c7a0b4668e90597b9782bd won't be enough I'm afraid. Now both stylesheets are enqueued on every Jetpack site, all the time. As a result, icons are displayed twice:

![double-social](https://cloud.githubusercontent.com/assets/426388/23206433/eefbbc52-f8ed-11e6-976e-e458f8a1655f.png)

Maybe we would need to change the HTML markup of the menu items so we can add either SVG or Genericons, but not both?

Another alternative could be to hide the genericons via CSS when SVGs are included, maybe?

**Comment by jeherve** [comment]
Fixed in #6473
