### ISSUE TITLE
Settings UI: non-admins need love too

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#6475]
#### Steps to reproduce the issue
Activate all modules `wp jetpack module activate all` & sign in as an editor.

#### What I expected
I expected to see the settings available at the user level.  These include: 
- Publicize
- After the Deadline
- Post by email

![screen shot 2017-02-22 at 10 31 11 am](https://cloud.githubusercontent.com/assets/7129409/23218390/270efdf6-f8ea-11e6-973b-642a22fa2b90.png)
![screen shot 2017-02-22 at 10 31 38 am](https://cloud.githubusercontent.com/assets/7129409/23218394/286f46f6-f8ea-11e6-8ac8-8eff7a13f3b1.png)

#### What happened instead
I don't see any settings. 

![screen shot 2017-02-22 at 10 32 21 am](https://cloud.githubusercontent.com/assets/7129409/23218411/36c35e40-f8ea-11e6-95f8-ffc9d7736f0d.png)

**Comment by eliorivero** [comment]
Fixed in #6559
