### ISSUE TITLE
Update leafo.net/scssphp version [Request]

### ISSUE THREAD

**Issue by drrobotnik** [Automattic/jetpack#6476]
#### What I expected
JetPack is using a very old version of leafo/scss compiler for jetpacks css preprocessing (0.0.9 released Dec 23, 2013, current version is 0.6.6). There have been a bunch of releases that fix scss compiling bugs. I think you could safely upgrade to v0.4.0. The release after 0.4.0 raises the PHP requirements to 5.4.0, which I believe is above WP requirements.

**Comment by jeherve** [comment]
Thanks for the report!

This is currently tracked in #2206.
