### ISSUE TITLE
Create a custum buton sharing doesn't work

### ISSUE THREAD

**Issue by costalfy** [Automattic/jetpack#6479]
Hi, 
I'm on WP 4.7.2 with Jetpack 4.6 and i want to create a custom button to share on Diaspora.
![capture d ecran 2017-02-22 a 21 06 49](https://cloud.githubusercontent.com/assets/1092544/23230406/1117e378-f944-11e6-8e0d-18368f6aa454.png)

![capture d ecran 2017-02-22 a 21 07 29](https://cloud.githubusercontent.com/assets/1092544/23230404/1111832a-f944-11e6-822a-f51049ba83c0.png)

When i click on save, my custom button lost her config and it doesn't work
![capture d ecran 2017-02-22 a 21 07 46](https://cloud.githubusercontent.com/assets/1092544/23230405/11121c2c-f944-11e6-8364-bb52af2bfd2b.png)

**Comment by jeherve** [comment]
This will be fixed in the next Jetpack release, that will be available in a couple of weeks. Until then, you can apply this patch if you feel comfortable edit PHP files on your site: #6355
