### ISSUE TITLE
Settings UI: What do we do about non-admin view when site is not connected?

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#6483]
When the Jetpack site is installed but not connected nor in dev mode (which is likely to be the case for many bundled host installs), What do we do with the Jetpack tab/page for non-admins?  

Right now The Jetpack admin menu is there, but loads only a broken admin page: 
<img width="1528" alt="screen shot 2017-02-22 at 6 01 31 pm" src="https://cloud.githubusercontent.com/assets/7129409/23236874/f89910e4-f928-11e6-9cb9-0825dd155335.png">

I think the easiest approach is to simply hide the admin menu from non-admins, since they can't connect the site anyway.

**Comment by eliorivero** [comment]
I addressed this somehow in #6470 but I agree that we should remove the menu entry. We do that already when site is in dev mode and you log in with a non admin user.

<img width="364" alt="captura de pantalla 2017-02-24 a las 12 58 19" src="https://cloud.githubusercontent.com/assets/1041600/23310327/f7b6579a-fa90-11e6-9ccd-07ed43265b8b.png">

**Comment by eliorivero** [comment]
Fixed in #6559
