### ISSUE TITLE
Wrong custom share buttons generation

### ISSUE THREAD

**Issue by RDCH106** [Automattic/jetpack#6487]
When a new service is configured to be shown as sharing service behing the post, the service does not appear correctly since the last update.

Service information during the creation:

**Service Name**: Diaspora
**Shared URL**: https://sharetodiaspora.github.io/?title=%post_title%&url=%post_full_url%
**URL icon**: http://mascandobits.es/blog/wp-content/uploads/2017/01/diaspora-icon-16.png

![image](https://cloud.githubusercontent.com/assets/1483414/23254021/dbe6ee9c-f9b6-11e6-9ed3-fd7280003684.png)

After shre button creation:

![image](https://cloud.githubusercontent.com/assets/1483414/23254189/8093ca82-f9b7-11e6-8421-5c0be5902676.png)

But when I go to website, the share button is not correctly created:

![image](https://cloud.githubusercontent.com/assets/1483414/23254263/bf35909a-f9b7-11e6-8683-823f01906f9e.png)

**Wordpress version**: 4.7.2–es_ES
**Jetpack version**: 4.6

I created previously services without problems and they have been working until **Jetpack 4.6** version update.

**Comment by jeherve** [comment]
This will be fixed in the next Jetpack release, that will be available in a couple of weeks. Until then, you can apply this patch if you feel comfortable edit PHP files on your site: #6355
