### ISSUE TITLE
Request a patch for subscriptions shortcode to work with pop-ups.

### ISSUE THREAD

**Issue by freefincal** [Automattic/jetpack#6494]
Hi, I was using Jetpack subscription shortcode for email sign ups with thriveleads plugin pop ups. For some reason, it stopped working. I contacted thriveleads in this regard and they request you to add a small patch to line 892 of subscriptions.php

`<input type=”hidden” name=”jetpack_subscriptions_widget” value=”submitted”>
and change to name of the submit field, example:
<input type=”submit” value=”<?php echo esc_attr( $subscribe_button ); ?>” name=”jetpack_subscriptions_widget_submit” />`

Reason given by them:
In order for Thrive Leads to successfully count conversions, we need to trigger the form submission from javascript (not triggered by the user) – in the case of JetPack subscriptions, this will cause jetpack to not recognize the form data being sent – thus not recording the subscription.

They have added this patch in my jetpack. But if I update it will be lost. Would you please consider add this patch in Jetpack? Thank you.

**Comment by jeherve** [comment]
We've now started working on this, and are tracking progress in #31862. I'll close this issue as duplicate.
