### ISSUE TITLE
Add place to manually update API keys

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#6500]
Right now, antispam and backups/security both need a place to manually update API keys.

I'm wondering if the debug menu might be a good place for these, but that doesn't exist on the Calypso side. I'm open to suggestions on this one.

**Comment by jeffgolenski** [comment]
I think getting that into calypso would be #1. I'm not sure hiding that behin a debug menu is a logical place for that. What are you thoughts / reasoning for that idea?

**Comment by MichaelArestad** [comment]
@jeffgolenski I think it should probably be there as well as in Jetpack. Any ideas where?

There are a few reasons I was thinking it should be in the Jetpack debug area:
* You can have an Akismet or VP account and not be connected to Calypso
* Often times they are really only needed when something is messed up (to fix something that went wrong)
* Other debugg-y stuff is in the debug page that doesn't require JS or anything too fancy

The downside is that the debug page needs a bit of a makeover.

**Comment by rickybanister** [comment]
Quick sketch for the backups card in #6668
