### ISSUE TITLE
Move all of stats settings into a foldable card

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#6503]
#### Current
![image](https://cloud.githubusercontent.com/assets/1123119/23376175/72b4c32e-fce8-11e6-876c-b8e576463e95.png)

#### Proposed

Foldable card:

Card title: Site stats
Card description: TBD

All of the settings should be in the current order, but in the expanded view only.

**Comment by eliorivero** [comment]
Closed in #6550
