### ISSUE TITLE
Move brute force protection into a foldable card

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#6504]
This is similar to https://github.com/Automattic/jetpack/issues/6503

#### Current
![image](https://cloud.githubusercontent.com/assets/1123119/23376206/91a98472-fce8-11e6-870c-83d209cd8afe.png)

#### Proposal
Card title: Prevent brute force login attacks
Primary setting: `Block suspicious-looking login activity from unknown IP addresses`

Only the child settings should be in the expanded view.

**Comment by eliorivero** [comment]
Closed in #6597
