### ISSUE TITLE
Create upgrade banner for those with Akismet/VP plans

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#6506]
We need to create upgrade banner specifically for those who already have Akismet or VaultPress plans to upgrade them to JP plans.

@richardmuscat Can you get some copy for this going? We should see how it relates to the other banners we've got so far: https://github.com/Automattic/jetpack/issues/6449

**Comment by MichaelArestad** [comment]
@richardmuscat do we need these for the next release? If so, let's get them going.

**Comment by richardmuscat** [comment]
@MichaelArestad -- I'm not sure what we're doing here. What's the upgrade plan?

**Comment by MichaelArestad** [comment]
@richardmuscat You brought this up in our call at some point. It sounded like you were interested in upgrade prompts for those who already have a VP or Akismet plan, but not a JP plan.

**Comment by richardmuscat** [comment]
Hmmmm. If I did I was probably referring to upgrading from a Personal/Premium to a Premium/Pro plan. 

I don't think we currently have a one-click upgrade mechanism for either right now though so we shouldn't be prompting people to do something they can't do. 

Unless they can? @thingalon might know better on the original question of the issue.

**Comment by rickybanister** [comment]
Does this issue even relate to Jetpack? Folks with Jetpack already installed are being auto-transferred by @thingalon. 

Anyone with a bundle, but not Jetpack would need to see a banner that is shipped inside of the VaultPress or Akismet instead. Should we track this elsewhere or close?

**Comment by MichaelArestad** [comment]
I think we can close this and open a new one for something more along the lines of what @richardmuscat mentioned.

**Comment by richardmuscat** [comment]
@MichaelArestad -- bear in mind that we should only do a new one along the lines I suggested when we have the ability to apply pro-rated upgrades which is something still in progress with @johnHackworth
