### ISSUE TITLE
Move all spelling and grammar settings into a foldable card

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#6507]
#### Current
![image](https://cloud.githubusercontent.com/assets/1123119/23377059/b4d54fb4-fceb-11e6-88a0-a69a952b2388.png)

#### Proposal
This will be a similar solution to https://github.com/Automattic/jetpack/issues/6504

Card title: none
Primary setting: Check your spelling, style, and grammar

The rest of the settings should remain as is, but in the expanded view instead of advanced options.

**Comment by eliorivero** [comment]
Closed in #6550
