### ISSUE TITLE
Protect: IP addresses disappear when collapsing Protect module

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#6511]
To repro:

1. Jetpack > Settings, activate Protect.
3. Click the dropdown, add two IPs, click save
6. Collapse dropdown.
7. Expand dropdown.
8. The IPs are gone.
9. Navigate to Dashboard (**not** Jetpack > Dashboard).
10. Go back to Jetpack > Settings and expand the Protect dropdown.
11. The IPs are there.

**Comment by richardmtl** [comment]
3094707-t

**Comment by dereksmart** [comment]
This has been fixed in `feature/settings-ui` branch
