### ISSUE TITLE
Subscriptions: offer stats on email openings and link click-through

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6513]
Some subscription services offer built-in stats about email openings and other data. It would be nice to leverage Jetpack Stats to offer that information about Jetpack's Subscription emails as well.

Suggested here:
http://jetpack.com/2017/02/22/share-it-again-new-social-media-features-for-premium-and-professional-customers/#comment-20916

**Comment by PahadiSparrow** [comment]
![post_by_email](https://user-images.githubusercontent.com/86050497/122545516-8e181680-d04b-11eb-87f1-4928b0fffa68.PNG)
My concern for mail analysis track of each post is here Post By Email. Its should be shown in jetpack, why I will use third party when I have purchased jetpack. 
I just need the post mail track analysis data of how many users have actually clicked the link or came through email.

**Comment by simison** [comment]
This has been shipped, the UI is available in Calypso for but also hoping to get show up for Jetpack stats.
