### ISSUE TITLE
Admin UI: Make sure changes on the page are "visible" for screen readers

### ISSUE THREAD

**Issue by ryelle** [Automattic/jetpack#6534]
Tested with VoiceOver on Safari, the screen reader doesn't know when the page content has changed. This is usually achieved with aria live regions, [see this article](http://webaim.org/techniques/aria/). I want to do a little investigation to make sure this is the right approach for our content, so this issue is more about information tracking for now.

Page content changes when

- navigating between tabs: "Security" to "Engagement", or "Dashboard" to "Settings"
- opening or closing a settings card
- enabling/disabling a module (shows/hides the module's settings)
- searching settings
- notices appear on screen (we can use [`wp.a11y.speak`](https://make.wordpress.org/accessibility/2015/04/15/let-wordpress-speak-new-in-wordpress-4-2/) or something similar?)

**Comment by ryelle** [comment]
Notices also fall into this, but perhaps we can use [`wp.a11y.speak`](https://make.wordpress.org/accessibility/2015/04/15/let-wordpress-speak-new-in-wordpress-4-2/) or something similar for them.

**Comment by dereksmart** [comment]
Fixed in #6682
