### ISSUE TITLE
REST API: Module settings are not being updated

### ISSUE THREAD

**Issue by Stoyan0v** [Automattic/jetpack#6539]
#### Steps to reproduce the issue
* Open Jetpack and activate Custom Content Types module
* Enable Portfolio Projects

#### What I expected
* To see that Portfolio Projects checkbox in Settings->Writing is checked
* To be able to add new portfolio.

#### What happened instead
* I see a success message upon save: "Updated Custom Content Types settings."
* The post type is actually not enabled.
* Clicking on "Configure Portfolios" button takes me to "Invalid Post Type" page.

This is the same for all modules that have sub options. It can be tested with "Infinite Scroll" and "Markdown" modules for example.

It appears that this issue has been introduced in 8f584fdfe1d795cd8b7e18f7788fc7394bf81957 where @roccotripaldi changed the param filtering logic to support older PHP versions. It seems that when @roccotripaldi was refactoring this, he used `is_string` to filter parameters, but `array_filter` filters the values, and not the keys as it was initially supposed to. This PR changes the logic to filter the keys, and not the values.

cc @roccotripaldi @tyxla

**Comment by tyxla** [comment]
cc @eliorivero @zinigor
