### ISSUE TITLE
Admin UI: Connection Settings Card Needs Default Image If Avatars Are Disabled

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/jetpack#6545]
#### Steps to reproduce the issue
1) Connect Jetpack
2) Visit wp-admin > Settings > Discussion
3) Disable the Show Avatars setting
4) Visit Jetpack > Settings > Connection Settings
5) Note how the default blank image is ugly

![image](https://cloud.githubusercontent.com/assets/933450/23483227/12c663aa-fea0-11e6-8969-516a14febf26.png)

#### What I expected

Some kind of default image

#### What happened instead

A blank circle; `img` tag with no `src` attribute

**Comment by alexjgustafson** [comment]
2823573-t

**Comment by danjjohnson** [comment]
Noting that when I tested disabling "Show Avatars" my gravatar still appeared there. You may need to disable that setting before connecting JP to see the issue.

**Comment by eliorivero** [comment]
This has been fixed in #6592 and will be included in the new settings UI.
