### ISSUE TITLE
Settings UI - Dev Mode: notice needs padding

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#6551]
#### Steps to reproduce the issue
1. put site in Dev Mode
2. reduce screen size

#### What happened

<img width="470" alt="captura de pantalla 2017-03-02 a las 15 52 15" src="https://cloud.githubusercontent.com/assets/1041600/23522061/5feed7be-ff60-11e6-80d4-4dc78df11654.png">

**Comment by MichaelArestad** [comment]
Why is the reason on a different line?

Couldn't it just say:

> Your site is in Development Mode and some features have been disabled because your site URL lacks a dot. Example: http://localhost

**Comment by eliorivero** [comment]
This is an enhancement that was introduced by @singerb in https://github.com/Automattic/jetpack/pull/6360 since a site can be in Dev Mode for more than one reason.

**Comment by singerb** [comment]
Yup, there's a list there now. Was mentioned in the original thread that it could be moved to a foldable thing if people complained, but didn't need to happen at the time.

**Comment by MichaelArestad** [comment]
@singerb Gotcha. I do think we need to make them less technical and point to specific docs. Many people who end up in these situations aren't developers (yet) and I want to make sure we're giving them a nice way out of it rather than expecting them to know what a constant is and where to find it. That kind of thing.

**Comment by singerb** [comment]
Hmm. At least when I made my change, the `Development Mode` text (from `Currently in Development Mode...`) was a link to some docs about development mode. If that's still the case, it looks like there's some styling needing so that's obvious; if it's not the case, that link can be added again.

**Comment by eliorivero** [comment]
Fixed in #6619
