### ISSUE TITLE
Subscriptions: WP.com subscribe count is wrong

### ISSUE THREAD

**Issue by HardeepAsrani** [Automattic/jetpack#6553]
Saw this on our WordCamp site first, but can't touch code there so tried to reproduce on my personal site.

If you enable Subscription module on your site and then more than few people subscribe using their WordPress.com email, it appears fine on backend. All the users appear properly but the count on the table is always 1, regardless of the number of users. Reproduced it on multiple sites, and here's a screenshot to better explain the issue:

![Jetpack Subscriber View](https://box.everhelper.me/attachment/794227/623cb6ed-c20c-499d-ba86-1243d19d09f9/542868-UKdnMQQX9yxWGQEb/screen.png)

And the email subscriber count is working just fine. Wanted to send a patch but React isn't my domain so was lost in the code. :)

**Comment by jeherve** [comment]
It was a caching issue. I refreshed the cache for that site and you should be all set now!
