### ISSUE TITLE
Settings: toggles are not positioned correctly

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#6554]
Toggles are like this in At a Glance

<img width="378" alt="captura de pantalla 2017-03-03 a las 11 00 28" src="https://cloud.githubusercontent.com/assets/1041600/23553801/1a045412-0001-11e7-9d22-42c871362d45.png">

Probably due to this https://github.com/Automattic/dops-components/commit/982ecf16e9bdf82e17a3dea064a26ff7b1f25ebd#diff-d8783ec4987010d013a8709b0e0f8ff3

which also affected toggles in current UI in a worse way

<img width="748" alt="captura de pantalla 2017-03-02 a las 16 20 56" src="https://cloud.githubusercontent.com/assets/1041600/23553863/5bddd746-0001-11e7-8e32-061adbb32651.png">

**Comment by MichaelArestad** [comment]
@eliorivero I can't reproduce. I did a `yarn distclean` and a `yarn build` on master. Are you npm linked to the latest dops-components? If so, that might do it.

**Comment by eliorivero** [comment]
Seems to be gone now in master. However, I still see this in `feature/settings-overhaul` even after a `distclean` and a `build`

<img width="367" alt="captura de pantalla 2017-03-07 a las 11 53 09" src="https://cloud.githubusercontent.com/assets/1041600/23661896/b0b308d0-032c-11e7-95a8-bb92bd085c4b.png">

**Comment by dereksmart** [comment]
The reason it's not in master after a distclean is because we haven't yet upgraded master's yarn.lock to include the recent changes pushed to dops-components for the settings.  

You could probably reproduce if you built fresh in feature/settings-overhaul, and then checked out to master and simply build there without a distclean.

**Comment by MichaelArestad** [comment]
@eliorivero got it. I'll still fix it for `feature/settings-overhaul`, but master should be good with yarn's lock.

**Comment by eliorivero** [comment]
Fixed in #6664
