### ISSUE TITLE
Jetpack CLI: add --format=json support for `wp jetpack options get`

### ISSUE THREAD

**Issue by voldemortensen** [Automattic/jetpack#6569]
#### Steps to reproduce the issue
$ wp jetpack options get active_modules --json
Error: Parameter errors:
 unknown --format parameter

#### What I expected
A JSON object containing the active_modules option, similar to:
$ wp option get active_plugins --json
["jetpack\/jetpack.php"]

#### What happened instead
$ wp jetpack options get active_modules --format=json
Error: Parameter errors:
 unknown --format parameter

**Comment by kraftbj** [comment]
Not to sidestep the request, but for active modules, you can use: `wp jetpack module list --format=json` to get a full list with active/inactive status.

For the issue at hand, https://github.com/Automattic/jetpack/blob/master/class.jetpack-cli.php#L599 and the following area would likely need love from https://make.wordpress.org/cli/handbook/internal-api/wp-cli-utils-format-items/

**Comment by voldemortensen** [comment]
That's a good work around, thanks for sharing.

I've moved on from the company who needed this in a project and, besides that, I don't have the bandwidth to do much of anything currently. I'm fine if this is closed as a `maybelater` kind of thing since there's a good work around.

**Comment by jeherve** [comment]
👍 Closing for now, we can always come back to this later if needed.
