### ISSUE TITLE
Widget Visibility: can't select any option

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6574]
#### Steps to reproduce the issue

1. Install Jetpack 4.7 Beta.
2. Go to Appearance > Customize > Widgets
3. Select a Widget.
4. Try to apply the following rules:

![screen shot 2017-03-06 at 23 13 53](https://cloud.githubusercontent.com/assets/426388/23632558/95c69538-02c2-11e7-82d7-db540d501c1a.png)

The Front Page rule will disappear as the customizer refreshes.

This happens wither other options as well.

This doesn't happen with Jetpack 4.6.

Possibly caused by #6333, #6327, #3406, or #6326

**Comment by dereksmart** [comment]
I've confirmed that this was the breaking change 0c510aaa0c8fb362657ec8ca6f0195506e214fe2
