### ISSUE TITLE
VideoPress files saved in the wrong folder

### ISSUE THREAD

**Issue by davoraltman** [Automattic/jetpack#6583]
#### Steps to reproduce the issue
When I upload a video, the file will end up inside the folder uploads/2017/01.
#### What I expected
The file should be uploaded in the correct folder depending on the time of upload. If I upload it in March, the file should be in uploads/2017/03.

cc @jeherve 
The issue was mentioned in 133-gh-jpop-issues
3083320-t

**Comment by jeherve** [comment]
Fixed in #6590
