### ISSUE TITLE
VideoPress: do not store videos on local site anymore

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6588]
Discussion: p7kMJG-1nJ-p2

While VideoPress videos are currently uploaded to both WordPress.com and the local site, we should be able to only upload videos to WordPress.com.

When doing so, we'll need to make sure we do not break core features such as [Video Headers](https://make.wordpress.org/core/2016/11/26/video-headers-in-4-7/).

Related #6583

**Comment by georgestephanis** [comment]
I think we should include a filter for all videos, if the user would like to keep a local copy at all times, and a per-video "grab a local copy in my media library" button, but yeah -- by default, let's avoid redownloading all the videos by default.

While the bigger benefit of VideoPress from my perspective is the bandwidth saved, the storage savings of not having to have a local copy of the video is worth considering as well.

Also, when downloading a local copy, maybe give them an option between the original uploaded format, and a web-optimized version that may be much smaller in filesize?
