### ISSUE TITLE
Jetpack Connection Banner CTAs should be fixed for all tabs. 

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#6593]
The content boxes and CTAs should be the same for all tabs.  Right now they jump around. 

![jump-around](https://cloud.githubusercontent.com/assets/7129409/23667449/e0fa35a0-032b-11e7-86dc-75e7429d0a89.gif)

**Comment by rickybanister** [comment]
@jeffgolenski could I ask you to take a quick peek at this issue, could we triage the copy and see if we can shorten it up a little bit? 

I can't think of a good solution to ensure the same height across all cards irrespective of translation however. 

Can we think of a small tweak that won't cause height issues?

This issue also corresponds to #7109 as adding ToS acceptance will increase the amount of text.

**Comment by jeffgolenski** [comment]
@rickybanister @dereksmart 

can we just write some quick JS to ensure each card will have the same height as the tallest content area? I remember this being discussed a few months ago with @samhotchkiss @georgestephanis in a quick plugin UX walkthrough. The banner dimensions should revolve around the content, not the other way around.

**Comment by rickybanister** [comment]
That might be possible, but it will have to recalculate the height if the browser window changes size. Fixed height is still kind of a tricky thing in a browser.

**Comment by jeffgolenski** [comment]
> but it will have to recalculate the height if the browser window changes size. Fixed height is still kind of a tricky thing in a browser.

Precisely why modifying the content to try and be a consistent height isn't a solution here. Even if all the lines end up being the same on a large screen, due to word wrapping and left alignment, on smaller screens (not necessarily mobile screen, but small laptops and such) they may still jump around a bit. That's why we need to dynamically calculate it on render and match the heights then.

**Comment by oskosk** [comment]
@dereksmart I'm closing this as it looks like it's totally fixed no. See gif below

![fixed](https://user-images.githubusercontent.com/746152/31735129-521d750c-b417-11e7-8bd9-0a1c31d533cb.gif)
