### ISSUE TITLE
Body class not updated with infinity-end when ajax response is empty

### ISSUE THREAD

**Issue by efc** [Automattic/jetpack#6594]
There seem to be two ways that an infinite scroll ends. One is described in issue #3549, when a clean `response.lastbatch` is received and the scroll wraps up nicely. But I have found another situation that arises from time to time in a way I can't predict (perhaps related to queries with a bit more complexity, like taxonomy and meta-query components?). In this case the scroll ends without `response.lastbatch` ever being set to `true`. In this case the scroll ends with an empty response and exits out with a [quick return](https://github.com/Automattic/jetpack/blob/master/modules/infinite-scroll/infinity.js#L252).

When this happens, the `<body>` tag never gets a class update, and consequently the theme designer never has a chance to clean up elements that should change when the scroll is over.

#### Steps to reproduce the issue

Create a query that may result in an empty response instead of a clean last batch. This is a hit and miss thing, I have not identified how to guarantee a situation like this.

#### What I expected

The `<body>` tag to get a class of `infinity-end` added.

#### What happened instead

No change to the `<body>` tag.

#### Recommendation

When an empty response is received, treat it as though a last batch has been received so that themes can update the UI.

**Comment by efc** [comment]
I have tried removing my `pre_get_posts` action which was adding the `meta_query` but still am seeing an infinite scroll ending in an empty response. Note, this is on a taxonomy page, so the query is still somewhat complex.

**Comment by jeherve** [comment]
@efc We're actually about to release Jetpack 4.7, that will include a few changes that may address this issue.

Could you give it a try when it comes out, and let us know if that helps?

Thanks!

**Comment by efc** [comment]
@jeherve Indeed! I should have thought of that. I just installed the current master branch and my problem goes away. Looking forward to 4.7. Thanks for the great work.

**Comment by jeherve** [comment]
Excellent, glad to hear that! I'll close this issue now that Jetpack 4.7 is available. Don't hesitate to comment here if the problem appears again.
