### ISSUE TITLE
Custom CSS: font-face embedding doesn't work

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#66]
Steps to reproduce:
1. Activate the Custom CSS module
2. Under _Appearance > Edit CSS_, try to embed a font using font-face, like so:

`@font-face {
font-family: 'amertype_md_btmedium';
src: url('http://mysite.com/wp-content/uploads/2013/12/american_typewriter-webfont.eot');
src: url('http://mysite.com/wp-content/uploads/2013/12/american_typewriter-webfont.eot?#iefix') format('embedded-opentype'), url('http://mysite.com/wp-content/uploads/2013/12/american_typewriter-webfont.woff') format('woff'), url('http://mysite.com/wp-content/uploads/2013/12/american_typewriter-webfont.ttf') format('truetype'), url('http://mysite.com/wp-content/uploads/2013/12/american_typewriter-webfont.svg#amertype_md_btmedium') format("svg");
font-weight: normal;
font-style: normal;
}`

Load your site and look for an element that should be using the new font. You'll notice that the embedded font is not loaded.

Reported here:
- http://wordpress.org/support/topic/font-embedding?replies=3

**Comment by RavanH** [comment]
Just ran into the same issue and found that when using "src:" TWO times (as in the suggested CSS by FontSquirrel for example, same as on http://wordpress.org/support/topic/font-embedding?replies=3) then Jetpack will strip out the second instance in the compressed output while on the Custom CSS settings page, the full CSS is still visible.
