### ISSUE TITLE
Removed routes must use forwarding to avoid broken bookmarks.

### ISSUE THREAD

**Issue by zinigor** [Automattic/jetpack#6601]
The refactoring of Settings leads to some routes that were previously used becoming no longer available. In case someone has a bookmark for that page or just an open tab with that route, people may see an empty page.

#### Steps to reproduce the issue
* Go to Jetpack admin and modify the fragment to read `#/general`.

#### What I expected
* To see the admin page

#### What happened instead
* I got a blank page.

**Comment by dereksmart** [comment]
Closed via #6656
