### ISSUE TITLE
Markdown tables changed to HTML inside the editor after updating to v4.7

### ISSUE THREAD

**Issue by leandroprz** [Automattic/jetpack#6605]
Before updating to Jetpack v4.7 this is what I was seeing inside the post editor:
  
```
| Resolución | FPS | Codec | ID | Proxy |
|:----------------:|:---:|:----------:|:-----------:|:-------------------------:|
| 2048x1152 @ 16:9 | 25 | ProRes 422 | 12-2014_007 | <a href="https://leandroperez.com.ar/sample/12-2014_007.mp4" title="Descargar clip con marca de agua en baja calidad" download="12-2014_007-h264-leandroperez.com.ar.mp4">Descargar clip</a> |
```
  
Now this is what I see:
  
```
<table>
<thead>
<tr>
  <th align="center">Resolución</th>
  <th align="center">Proporción</th>
  <th align="center">FPS</th>
  <th align="center">ID</th>
  <th align="center">Proxy</th>
</tr>
</thead>
<tbody>
<tr>
  <td align="center">720p, 1080p, 2K</td>
  <td align="center">16:9</td>
  <td align="center">25</td>
  <td align="center">12-2014_007</td>
  <td align="center"><a href="https://leandroperez.com.ar/sample/12-2014_007.mp4" title="Descargar clip con marca de agua en baja calidad" download="12-2014_007-h264-leandroperez.com.ar.mp4">Descargar clip</a></td>
</tr>
</tbody>
</table>
```
  
The markdown table converted to HTML somehow. Is there a way to change it back?

**Comment by jeherve** [comment]
What happens if you publish the same table in a new post? Does the Markdown syntax remain visible in the text editor after publishing?

**Comment by leandroprz** [comment]
This is getting stranger. I pasted the markdown table in a new post, published it and the table isn't getting converted to HTML, I see the markdown code as it was pasted in the text editor.

So I checked my Jetpack settings and the Markdown module is enabled.

**Comment by jeherve** [comment]
Thanks for giving it a try!

Could you go to Settings > Writing in your dashboard and make sure the Markdown option is checked there?

**Comment by leandroprz** [comment]
The module is enabled.

I tried turning it off and on again but that didn't work.

**Comment by jeherve** [comment]
Is the checkbox checked under Settings > Writing?

**Comment by leandroprz** [comment]
[Yes](http://i.imgur.com/zpoDwrQ.png).

**Comment by jeherve** [comment]
@leandroprz Could you check the checkbox under Settings > Writing as well?

**Comment by leandroprz** [comment]
I'm sorry, I thought you meant the Jetpack settings.

In Settings > Writing > Markdown I have it enabled for "Use Markdown for posts and pages."

**Comment by jeherve** [comment]
Excellent. Could you now try to publish a new post, and let me know how it goes?

**Comment by leandroprz** [comment]
I saved the settings, then updated the post I was testing earlier on and now I see markdown in the text editor and a HTML table in the post.

Also, the posts where I had markdown tables went back to markdown code instead of HTML (in the text editor).

**Comment by jeherve** [comment]
Perfect, thanks for trying all this. We have a patch in #6608, we'll run some more tests and see if we can include it in the next Jetpack release.

Thanks for the report!

**Comment by leandroprz** [comment]
Thank you for your hard work!
