### ISSUE TITLE
Mobile theme: Enable Infinite Scroll on mobile theme

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#6616]
Can we enable infinite scroll on the mobile theme?

Requested in 3092923-t

**Comment by chaselivingston** [comment]
Also requested in 1985768-hc

**Comment by talgalili** [comment]
Is there at least an easy way to change the default "show only 5 posts" in the theme?

**Comment by jeherve** [comment]
@talgalili You can use a functionality plugin like this to overwrite that number:
https://gist.github.com/kraftbj/1aaf623fdd6aba9e25d2

**Comment by talgalili** [comment]
Worked like a charm, thanks @jeherve

**Comment by BrookeDot** [comment]
@jeherve Can this be closed now that the mobile theme will be removed in a few months?

**Comment by jeherve** [comment]
> Can this be closed now that the mobile theme will be removed in a few months?

Yes, I'll close all related issues when the module is removed from the codebase. 👍
