### ISSUE TITLE
Mobile theme: Share by email form position on mobile

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#6617]
#### Steps to reproduce the issue

- Enable mobile theme and sharing by email.
- View a post on mobile and tap the share by email icon.

#### What I expected

The form should display within the screen boundary and should not affect the rest of the page.

#### What happened instead

On Android (Google Pixel), the form reduces the size of the rest of the page in order to fit on the screen:

![image](https://cloud.githubusercontent.com/assets/1990037/23756234/ef1e4030-04da-11e7-932f-8a31d317a34f.png)

On iOS, it seems that the form just overlaps the boundaries of the screen, requiring horizontal scrolling:

![image](https://cloud.githubusercontent.com/assets/1990037/23756293/17320a16-04db-11e7-8f59-eb8387d242b5.png)

Reported in 3092923-t

**Comment by jeherve** [comment]
Another instance in #12235 (cc @cyphix333)

**Comment by cyphix333** [comment]
Wow... not fixed after 2 years; simple issue like this, shows how much they care about fixing this one. Guess it's up to us to fix it ourselves?

**Comment by jeherve** [comment]
@cyphix333 We're not currently working on the Email sharing button so we have no ETA for a fix right now, but if you want to contribute a fix, we'll be happy to review a Pull Request!

**Comment by bikedorkjon** [comment]
This came up in 2482774-zen
