### ISSUE TITLE
Comments: Does not respect the sites locale for the "Submitting Comment" string

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#662]
When a site has a non-Enligh locale, submitting a comment will first show the "Submitting Comment" string which then changes to the localized version of the string. The English version appears to come from the jetpack.wordpress.com iframe, which is not respecting the locale of the site in this particular instance.

Reported here: http://wordpress.org/support/topic/jetpack-comments-problem-with-some-submission-message?replies=6

**Comment by fredy31** [comment]
Any update on the matter?

**Comment by samhotchkiss** [comment]
Flagged this for 3.5, we'll get it knocked out with the next release, @fredy31

**Comment by alexingles4u** [comment]
Still a problem - very frustrating as it means we have to disable jetpack commentaries on our SPANISH language site - Any updates on a fix for this?

**Comment by alexingles4u** [comment]
Im using latest jetpack 3.5.3

**Comment by georgestephanis** [comment]
I wonder if this would be simpler to resolve by just swapping to a spinner instead with no verbiage.  Or would that be a UX issue and potentially confusing to users?

**Comment by alexingles4u** [comment]
Im actually quite surprised this bug is still unresolved because there are hundreds of thousands of non english jetpack installations out there, all of them flashing english text when their millions of users post a comment.

Is there any chance of it being put into the next jetpack release?

**Comment by georgestephanis** [comment]
If it's swapped to a spinner, that would happen wpcom server side, and affect all versions of Jetpack instantly.  Not tied to a release cycle.

**Comment by kraftbj** [comment]
:+1: to swap to a spinner on wp.com. With the comment flow, since the always-English appears immediately, then switches to the language-specific one once it is passed to the local site, the end result would be Submit->::spinner::->localized "Submitting Comment"->page reload. It would reduce the support load, be nice for other languages, and be relatively efficient for dev resources.

**Comment by alexingles4u** [comment]
Sounds like a good idea to me.

**Comment by dereksmart** [comment]
string replaced by a spinner in dotcom - in r-120598

You should now see a spinner followed by "Submitting Content" in whatever locale you have set.
