### ISSUE TITLE
Recent Comments Widget: Not showing Facebook profile photo alongside the comment

### ISSUE THREAD

**Issue by chaitanyamsv** [Automattic/jetpack#6628]
After commenting using Facebook account, user's Facebook profile photo is not shown with the comment on the Recent Comments widget.

#### Steps to reproduce the issue
Add a comment to a page or post using Facebook account. 

#### What I expected
Facebook profile photo is shown along with the comment. 

#### What happened instead
Facebook profile photo is not shown on the comment and on the Recent Comments widget. 

#### Screenshots
Chrome shows broken image icons in the widget: ​https://cloudup.com/ctuZGly_-a7 and in the Comments Section: ​https://cloudup.com/c5CSGkLowBf

Firefox shows blank image: ​https://cloudup.com/c2p24IVcJ1G 

218583-hc
3088847-t

**Comment by jeherve** [comment]
That widget isn't part of Jetpack, it's available for WordPress.com sites only. I would recommend opening a trac ticket on WordPress.com.

Thanks!
