### ISSUE TITLE
Admin Page: PHP Warning in Multisite

### ISSUE THREAD

**Issue by bobbingwide** [Automattic/jetpack#6645]
#### Steps to reproduce the issue
- Activate Jetpack in subdomain install
- My local development environment is http://jetpack.wp.a2z, 
- PHP 7.0 / PHP 7.1
- Visit http://jetpack.wp.a2z/wp-admin/admin.php?page=jetpack

#### What I expected
No Warnings.

#### What happened instead
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/home/bworguk/public_html/wp-content/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-react-page.php</b> on line <b>212</b><br />

### Analysis
- This is what $wp_roles contains
```
wp_roles WP_Roles Object
(
    [roles] => 
    [role_objects] => Array
        (
        )

    [role_names] => Array
        (
        )

    [role_key] => wp_4_user_roles
    [use_db] => 1
)
```

Assuming that's a valid `$wp_roles` for Multisite then it would appear that the code should cater for null being returned from `get_editable_roles()`. i.e. It should check `is_array()` outwith the foreach loop.

**Comment by drkibitz** [comment]
@bobbingwide @jeherve 
I have the same error. I edited this file `wp-content/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-react-page.php` starting on line `207` to look like this:
```php
// Collecting roles that can view site stats
$stats_roles = array();
$enabled_roles = function_exists( 'stats_get_option' ) ? stats_get_option( 'roles' ) : array( 'administrator' );
$editable_roles = get_editable_roles();
if (is_array($editable_roles)) {
	foreach( $editable_roles as $slug => $role ) {
		$stats_roles[ $slug ] = array(
			'name' => translate_user_role( $role['name'] ),
			'canView' => is_array( $enabled_roles ) ? in_array( $slug, $enabled_roles, true ) : false,
		);
	}
} else {
	$stats_roles[ 'administrator' ] = array(
		'name' => translate_user_role( 'Administrator' ),
		'canView' => true,
	);
}
```
Probably not the right fix, but hey, hope this helps!

**Comment by drkibitz** [comment]
BTW, this warning is actually a symptom of errant behavior.
Meaning, if you actually try to look at the **Traffic** tab, with this warning in play, it won't work, and breaks the UI completely until a reload, and as long as the **Traffic** tab is not the thing reloaded. So priority-wise, might need to be a little higher IMO.

**Comment by jeherve** [comment]
> Assuming that's a valid `$wp_roles` for Multisite

I am not sure it is, though. `get_editable_roles()` should always return an array.

Could you both try the patch in #6957, and let me know if it helps?

**Comment by bobbingwide** [comment]
Jeremy, your fix doesn't check the result of get_editable_roles(). 
I'll still be getting `null` since that's the value of $all_roles in get_editable_roles().
So you still need to perform an is_array() test on the result from get_editable_roles().

Meanwhile, I'll check the value of wp_roles in a site that wasn't cloned

**Comment by jeherve** [comment]
> that's the value of $all_roles in get_editable_roles()

Right, but that seems like a bug to me. Something is either messing things up with `get_editable_roles()` on your site, or adding wrong data via the `editable_roles` filter.

**Comment by bobbingwide** [comment]
Hi Jeremy, whatever the problem is it's before get_editable_roles(). In another sub-domain $all_roles does have sensible values. Investigating.

**Comment by drkibitz** [comment]
If you do not have any roles beyond administrator, regardless if you are currently on the main site as the administrator, get_editable_roles will be empty. Maybe it shouldn't be `null`, but it will still be logically empty, as nothing is actually editable.

So look at my snippet a little closer, and you will see it's doing more than just removing the warning.

**Comment by bobbingwide** [comment]
I've resolved my problem. 

- The Jetpack sub-domain is site ID 4. 
- In the wp_4_options table there was no entry for option_name `wp_4_user_roles`.
- There was an entry for `wp_2_user_roles`.
- I updated the option_name of this entry to `wp_4_user_roles`.
- I don't get the messages any more.

No idea how/when the data got corrupted.
Over to @drkibitz ?

**Comment by jeherve** [comment]
@drkibitz I can see what your patch offers, but I'm still not sure how I can get to that point so I can reproduce the issue. How did you remove all other roles in the first place?

**Comment by drkibitz** [comment]
@jeherve I just thought that's how it was supposed to be. I've never installed a role plugin, or edited the DB, so whatever did it, did it silently. This all happened around the time I was disabling and reenabling both Jetpack and iThemes security (I have since deleted iThemes sec).

**Comment by drkibitz** [comment]
This is also a very old site, taken through the upgrade process since the early days of MU, so... there's that.

**Comment by drkibitz** [comment]
I see I might have something similar, where I see I have an option `1_user_roles`, not `wp_1_user_roles`

**Comment by drkibitz** [comment]
What should this option name be for MU? Because It seems it has been named `1_user_roles` for quite a while.

**Comment by drkibitz** [comment]
apparently `1_user_roles`, should be `wp_user_roles`.

**Comment by jeherve** [comment]
> I see an option 1_user_roles, not wp_1_user_roles

Apart from using the old WP MU back in the day, did you ever use role management plugins or create new subsites using a third-party plugin?

**Comment by drkibitz** [comment]
@jeherve no

**Comment by jeherve** [comment]
Closing, since this appears to be an issue linked to migration issues when moving from WP MU to Multisite. Looking at Core, such migration issues are most likely creating other issues across the WP dashboard, even when not using the Jetpack plugin.

**Comment by bobbingwide** [comment]
drkibitz's issue may have been to do with migration. Mine was more likely to be a problem with a cloning plugin or import.
In my opinion there was no need for Jeremy's change.
