### ISSUE TITLE
Sharing through e-mail icon - how to select image included? -

### ISSUE THREAD

**Issue by paaljoachim** [Automattic/jetpack#6663]
Hi

My client asked me today how to adjust the image that is included with clicking the e-mail icon.
(Here is how the e-mail looks when I get it in my inbox.)

![screen shot 2017-03-15 at 15 25 46](https://cloud.githubusercontent.com/assets/5323259/23953048/c5b70598-0993-11e7-944d-1c19a775510b.png)

I do not see a good visible place to where I can select which image to be included.
It would be nice to get this adjusted. Thanks.

**Comment by jeherve** [comment]
Jetpack doesn't send any image; it only sends the text you see at the top of the email, and the link. I believe the image and the preview may be added by your email client, most likely by scraping the URL found in the email body. I'm not sure how they select the image that's going to be used, though. I would recommend that you get in touch with your email client's support team to find out!

**Comment by paaljoachim** [comment]
Thank you Jeremy!
