### ISSUE TITLE
Settings > Security: backups api key field

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack#6668]
Here's a somewhat rough mockup for the backups block with a space for the API key:

<img width="752" alt="screen shot 2017-03-15 at 12 32 36 pm" src="https://cloud.githubusercontent.com/assets/437258/23959469/a95aed8c-097b-11e7-9fc5-bd0d0cef5ab7.png">

cc @MichaelArestad @ashleighaxios

**Comment by jeherve** [comment]
Closing since this most likely won't be implemented now.
