### ISSUE TITLE
Featured Content: Reword checkboxes for clarity

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/jetpack#6670]
Users are often confused about what the second checkbox in the Featured Content panel means, and despite seeing the checkbox, they don't quite understand what it does.

> Display tag content in all listings

What about something more descriptive, like:

> Display tagged posts outside the Featured Content area

I only hesitate at the word "posts" because FC can incorporate portfolio projects that might be affected by this option as well.

While we're at it, on the first box, "post meta" is not a term commonly used on WordPress.com or understood by its users. Could we perhaps switch that to "post details" instead, which would make it more easily understood by all WordPress users.

![customize_ toujours 1 0 7 by automattic tagline](https://cloud.githubusercontent.com/assets/7662449/23969600/6797fbac-099d-11e7-997a-193e4ed0c495.png)

Open to other suggestions as well!

**Comment by markarms** [comment]
Great suggestions Kathryn! The second one still stumps me -- what is a Featured Content area? Could we link to a definition?

**Comment by kathrynwp** [comment]
@markarms - Featured Content is a Jetpack feature that allows you to tag certain posts to appear in special area in a theme, such a a slider. I think given the context -- i.e. this whole panel is about Featured Content -- I'm not sure we need a link.

Revised wording that I think makes things clearer was already suggested by @clucasrowlands over here and it's been merged: https://github.com/Automattic/jetpack/pull/6684#issuecomment-287157265 So I think we're all good to go now!
