### ISSUE TITLE
Media > Speed up images indent needed

### ISSUE THREAD

**Issue by ashleighaxios** [Automattic/jetpack#6672]
Please indent the description. In more detail, the `jp-form-setting-explanation` should be in a fieldset `jp-form-fieldset`.

Before and after in this animated GIF:
![jp_media_indent](https://cloud.githubusercontent.com/assets/22752103/23970224/83e13a10-099f-11e7-824f-0435d22c49c0.gif)

Cc @MichaelArestad

**Comment by eliorivero** [comment]
Fixed in #6664
