### ISSUE TITLE
LinkedIn: Allow posting to Groups

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#668]
As requested in 1857594-t, the user would like to post to only their LinkedIn groups, and not to their Profile.

**Comment by Cornelisboreas** [comment]
Dear all, is this already resolved?

**Comment by jeherve** [comment]
@Cornelisboreas No, We're not working on this at the moment. We'll post here as soon as make progress.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
