### ISSUE TITLE
Site icon control in customizer throws error in template due to full image size being undefined

### ISSUE THREAD

**Issue by westonruter** [Automattic/jetpack#6683]
This is cross-posting from a WordPress.org ticket [#40010](https://core.trac.wordpress.org/ticket/40010). Essentially, when Jetpack is active (and presumably Photon) the `full` image size is not defined in `wp.customize.settings.controls.site_icon.attachment.sizes` and the template then throws an error when attempting to obtain the `url` property of an undefined value.

There is a patch on the core Trac ticket with a fix for the symptom, by falling back to use the original `attachment.url`, but I wanted to loop in the Jetpack team to help with identifying the root cause. The issue is observed by the reporter on WordPress.com VIP and also on VIP Quickstart.

**Comment by jeherve** [comment]
I can't seem to be able to reproduce the issue on my end, when using Jetpack on a local installation of WordPress, running latest trunk, and with all available Jetpack modules enabled.

Were you able to reproduce the issue?

I've subscribed to the trac ticket as well, hopefully we can nail down the problem once we have more info!

**Comment by lukecav** [comment]
@jeherve 

It might well be in one of the Jetpack modules that can not be used if on local dev.

**Comment by jeherve** [comment]
@lukecav I couldn't reproduce on a live sandbox either (that's where I first tried), but the trac ticket mentions a local development site so I think we can rule out anything that requires a connection to WordPress.com (that includes Photon).

**Comment by westonruter** [comment]
@jeherve note that they reproduced the issue on WordPress.com production (VIP):

> I've managed to reproduce this issue on both WordPress.com VIP and also our custom docker environment based on VIP quickstart.
https://core.trac.wordpress.org/ticket/40010#comment:7

So it may not be Jetpack itself but some WPCOM extensions to Jetpack?

**Comment by jeherve** [comment]
I can't seem to reproduce on WordPress.com Production (VIP) either, but let's see once we get more details!

**Comment by georgestephanis** [comment]
@westonruter I believe WPCOM unregisters image sizes as everything on wpcom is dynamically generated via the file server.

**Comment by westonruter** [comment]
Conclusion: Not a Jetpack bug.
