### ISSUE TITLE
REST API: Add Akismet module status to readable settings endpoints

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#6695]
It would be useful to have a boolean value representing the availability of these plugins through the settings endpoint. 

1. Add `akismet` key to readable settings endpoint representing with `true` an installed and active  state and with `false`, an inactive or not installed state.
1. ~Add `vaultpress` key to readable settings endpoint representing with `true` an installed and active state and with `false`, an inactive or not installed state.~

But let's discuss if this is useful or not @elio what do you think ?

**EDIT**: I got confused, there's already a `vaultpresss` key among settings  returned by the endpoint.

**Comment by oskosk** [comment]
In the readable modules rendpoint, we are sending `vaultpress` as a module, and with an inactive state if it's not installed . But we're not doing the same for akismet. Even when it's installed, it's not among the module items coming from the API.

**Comment by eliorivero** [comment]
Closed in #6693
