### ISSUE TITLE
Plugin stylesheets enqueued incorrectly

### ISSUE THREAD

**Issue by galbaras** [Automattic/jetpack#6703]
Jetpack enqueues its stylesheets on wp_print_styles (see https://github.com/Automattic/jetpack/blob/eb93995e9ea4ee718e121f7c8492c831859a6978/class.jetpack.php#L596).

It should enqueue them on wp_enqueue_scripts, possibly with a high number for the priority.

This will allow other plugins and the theme that "do it the WordPress way" to manipulate things, e.g. ensuring the theme's stylesheet is loaded last or optimising things for minification.

**Comment by jeherve** [comment]
That's done on purpose. You can find out more about it here: #1500

You'll also find a filter allowing you to deactivate Jetpack's CSS concatenation in that issue. Once this is done, you'll be able to dequeue any of the Jetpack scripts and styles.
