### ISSUE TITLE
WP.com Toolbar: Misaligned SiteIcon

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6724]
With the new toolbar merged, I am seeing the Site Icon in there misaligned:

![screen_shot_2017-03-22_at_3_34_18_pm](https://cloud.githubusercontent.com/assets/108942/24221750/3b489bf6-0f15-11e7-88fe-45dc4eafb4c8.png)

This is in Chrome, on a Mac.

Removing these 2 CSS rules fixed it for me, but I didn't look to see what other issues that might cause:

![screen_shot_2017-03-22_at_3_36_49_pm](https://cloud.githubusercontent.com/assets/108942/24221812/74d768b6-0f15-11e7-9271-669162fa38de.png)

**Comment by dereksmart** [comment]
FIxed in #6782
