### ISSUE TITLE
WP.com Toolbar: People > Add doesn't work

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6725]
With the new toolbar activated, if I click the "Add" button next to "People", the window refreshes back to `about:blank` and nothing happens. Appears to be broken.

![jetpack_ _jp5_ _wordpress_and_wp_com_toolbar__people___add_doesn_t_work_ _issue__6725_ _automattic_jetpack](https://cloud.githubusercontent.com/assets/108942/24222076/77467b2c-0f16-11e7-9dce-7eeb875ef3db.png)

**Comment by vindl** [comment]
@beaulebens I wasn't able to reproduce this on my test site. Clicking `Add` opens up `wp-admin/user-new.php` in my case. Could you think of any additional details that might be helpful for reproducing this bug?

**Comment by dereksmart** [comment]
fixed in #6779
