### ISSUE TITLE
WP.com Toolbar: Clicking the Site Icon/Name/URL should go to the homepage

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6727]
Currently, you cannot click on the Site Icon/Name/URL at the top of the My Sites menu to go to the homepage of the site. This is a critical navigation element to allow users to be able to get to their site.

![screen_shot_2017-03-22_at_3_53_18_pm](https://cloud.githubusercontent.com/assets/108942/24222439/b6eb6430-0f17-11e7-9fa1-ab93aca0b4be.png)

(screenshot to indicate the area I'm talking about. On WP.com the entire icon+name+url are clickable)

**Comment by dereksmart** [comment]
Fixed in #6782
