### ISSUE TITLE
Ensure that we have support pages on jetpack.com for all links

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#6733]
Walk through all the "learn more" links in the new settings UI and ensure that there are corresponding support pages

**Comment by beaulebens** [comment]
I walked through and they're all looking good except for:

- Settings > Security > Backups and security scanning points to https://help.vaultpress.com/get-to-know/, but I think it should point to a page on jetpack.com that explains the security offerings
- Settings > Security > Antispam points to https://akismet.com/jetpack/, but I think it should point to a page on jetpack.com that explains Akismet

**Comment by jeherve** [comment]
This can now be closed.
