### ISSUE TITLE
Close to my limit?

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#6734]
Upon upgrading to Jetpack Premium, I immediately get a banner under VideoPress telling me that I should "Get more space. You're close to your limit."

I just upgraded, and I haven't uploaded anything.  So this feels like a slap in the face

Right now the logic says to always show this banner to premium users.  I think we should disable this banner until we're able to rework it with more involved logic to actually know that they're using at least X% of their space.

Also, in the current flow, there's no visibility to the storage space I've used, nor to the amount of space I'm allowed.

**Comment by samhotchkiss** [comment]
cc: @richardmuscat

**Comment by richardmuscat** [comment]
The intention behind that text was only to show it if _they are actually close to the limit_ not across the board. If we can't actually do that then we either kill it or change the text to "Upgrade for unlimited storage space if 13Gb is not enough" or something to that effect.

**Comment by samhotchkiss** [comment]
👍 

I figured that was the intention, but wanted to confirm.

Let's kill it for this release, then we can work out a better conditional when we're doing our JITM improvements.

**Comment by samhotchkiss** [comment]
Closed by #6740
