### ISSUE TITLE
Calls to upgrade are unclear

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#6735]
When you have an insufficient account and click "Activate" for a feature like SEO or Google Analytics, it takes you to the plans page.

![image](https://cloud.githubusercontent.com/assets/574752/24282428/f6e0f2ae-1024-11e7-8374-d3c804a2a9a4.png)

A couple things:
* Should this say "Upgrade" rather than "Activate" so a user understands what's about to happen?
* Can we show a notice on the plans page along the lines of "You need a Business plan to use SEO", highlight that plan, and fade the others?

Also, we do use "Upgrade" when talking about VaultPress:
![image](https://cloud.githubusercontent.com/assets/574752/24282445/0edb2a8c-1025-11e7-9f3e-32cb544fd9dd.png)

**Comment by samhotchkiss** [comment]
cc: @richardmuscat

**Comment by richardmuscat** [comment]
I'm happy to go with "Upgrade" everywhere.

There will be custom landing pages explaining what's needed.

**Comment by samhotchkiss** [comment]
Closed by #6741
