### ISSUE TITLE
REST API: Switching settings to be boolean values, broke update of these settings from Calypso

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#6737]
Commit [7bbd680eca8683e061a5169a795ed74723dde574](https://github.com/Automattic/jetpack/commit/7bbd680eca8683e061a5169a795ed74723dde574) updated the mobile settings to be boolean values instead of `enabled/disabled`.

#### Steps to reproduce the issue

1. Checkout the feature/settings-overhaul on your connected jetpack site
1. get to calypso settings/writing page.
1. try to update any of the Theme Enhancements settings related to the mobile theme.
1. See the red notice.
1. Check the network panel and confirm that your site's API is rejecting the values for the `wp_mobile_excerpt` and `wp_mobile_featured_images ` setting.

![image](https://cloud.githubusercontent.com/assets/746152/24287205/7f9c963e-1057-11e7-9e55-c00797a762ce.png)

Props to @tyxla who originally reported this

cc @elio as you authored that commit.

What can we do here? If we keep this change, we will need to start checking for Jetpack versions on the calypso side and conditionally behave differently for versions. And we're already doing this for other reasons, so it could get messy as technical debt at some point.

I would vote for a rollback of the new boolean type if we can do that without much harm but we can also decide to break things related to these two settings for users which will be using Jetpack < 4.8.

**Comment by tyxla** [comment]
My two cents: I'm not much into having to version check in order to determine whether to sanitize the field values before POSTing them to the REST API. I realize that this is done for consistency reasons in Jetpack, but in Calypso we'll have to end patching a case that's already patched another case, which I'm not a proponent of.

**Comment by dereksmart** [comment]
Yeah, it's either going to be messy in Jetpack or Calypso.  What I like about Calypso is that we can simply remove the version checks when 4.8 is minimum supported version.  (we only support current versions of Jetpack -1)

**Comment by eliorivero** [comment]
Closing since this will be handled in Calypso

**Comment by oskosk** [comment]
> But these types of workarounds in the API will likely stay there forever if we're always sending a different value from Calypso.

So, probably this needs a de-workaround too:

`gravatar_disable_hovercards` is handled with enabled/disabled too

https://github.com/Automattic/jetpack/blob/feature/settings-overhaul/_inc/lib/class.core-rest-api-endpoints.php#L1115

**Comment by oskosk** [comment]
This is not fixed yet so I'm re opening this until it gets fixed somehow even when it could be in Calypso. 

Other things could have been broken by the same kind of updates so I'm retitling this for reference as: `REST API: Switching settings to be boolean values, broke update of these settings from Calypso.`

**Comment by jeherve** [comment]
@oskosk Did you mean to close this issue as well?

**Comment by oskosk** [comment]
yes @jeherve

**Comment by jeherve** [comment]
Perfect thank you!
