### ISSUE TITLE
Create a sharing page in settings

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack#6745]
As per the walk-through today we would like to create a placeholder page for Sharing in settings. 

This will alleviate the current issue where an unlinked or logged out user tries to click on the external 'sharing' link in the settings navigation and cannot successfully navigate to the sharing page on WordPress.com. It can also be frustrating/jarring to click through all the tabs looking for something and accidentally be taken to a different site.

The page will include descriptive text for publicize connections and sharing buttons and then use the clickable card pattern (or external link pattern) to link them over. 

Also note the position of the tab—now that it's not external, let's make it the second tab. First a user writes something, then publicizes it, then it is discussed, etc. It follows the lifespan of the user.

Unlinked users will see the `Connect your account to WordPress.com to use this feature >` text instead of the configure/connect text.

<img width="795" alt="screen shot 2017-03-24 at 2 01 59 pm" src="https://cloud.githubusercontent.com/assets/437258/24307528/eac23b92-109a-11e7-9c6c-3d9fd047f482.png">
 
cc @MichaelArestad

**Comment by rickybanister** [comment]
Text (subject to change):

`Publicize connections`
`Publicize lets you connect your site to various social networking services. Once connected to a service, you can share your posts with that service automatically.`
`Connect your social media accounts`

`Sharing buttons`
`Sharing and like buttons can be added to your posts so that your users can share your content to their social networks and show their support. Learn more.`
`Configure your sharing buttons`

**Comment by eliorivero** [comment]
Added in #6750
