### ISSUE TITLE
Backups/Security: VaultPress subscription not recognized properly

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6763]
On my site, I have a VaultPress subscription (not a Jetpack Plan), and so the UI gets confused about what to show me:

![screen_shot_2017-03-24_at_4_59_32_pm](https://cloud.githubusercontent.com/assets/108942/24364182/2f20cebc-12cf-11e7-9445-64491fa83a5b.png)

Longer term my VP sub will be converted to a Jetpack Plan, but in the meantime is there something simple we can do to recognize it in this UI, or handle it a bit better?

**Comment by dereksmart** [comment]
Yes, we're doing this correctly for akismet I think.  I'll write up a quick patch
