### ISSUE TITLE
Tweak wording in Support card

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6764]
Current Card
![screen shot 2017-03-24 at 5 02 16 pm](https://cloud.githubusercontent.com/assets/108942/24364310/9ae36812-12cf-11e7-9074-e0275a88baa1.png)

Proposed wording:

> **We're here to help**
> Jetpack comes with free, basic support for all users.

(note no period on the title, to match card titles elsewhere)

cc @richardmuscat and @rickybanister in case you have preferences.

**Comment by richardmuscat** [comment]
LGTM
