### ISSUE TITLE
Sharing: Site Icon doesn't show when sharing to WhatsApp

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/jetpack#6776]
A WordPress.com user reported that when they shared links from their site with WhatsApp, their site icon was no longer displayed with the link.

They reported this started when they tried to change their SEO settings, and ran into this issue: https://github.com/Automattic/wp-calypso/issues/11720. This was about two and a half weeks ago at this point, roughly the week of March 6th.

@gracie helped me test, and I can confirm that links to WordPress.com and my test site did not show an icon, but Facebook did. 

Ticket: 3126894-t

#### Steps to reproduce the issue

Steps to reproduce:

1. Add Share icons to your site, and make sure WhatsApp is included in the list. 
2. Add a site icon to the site.
3. On a mobile device, start a chat with someone in WhatsApp.
4. In Safari, navigate to the test site. Click the WhatsApp share icon.

#### What I expected

That the link would be shared with my current WhatsApp conversation, and include my site icon.

#### What happened instead

The link shared fine, with the site's URL, site title and tagline. The site icon just didn't appear.

Screenshot of a Facebook link:
![Example of Facebook link](https://cldup.com/WrnPHYfugp-3000x3000.jpeg)

Screenshot of both WordPress.com, and a specific test site:
![Example of WordPress.com links](https://cldup.com/t9lQ0j6jSE-3000x3000.jpeg)

**Comment by jeherve** [comment]
This will be fixed in #6632
