### ISSUE TITLE
New features are required for JetPack. Sharing: add new buttons

### ISSUE THREAD

**Issue by DeadLift1975** [Automattic/jetpack#6792]
I would like to have the social buttons VKontakte (VK), Odnoklassniki (OK),
LiveJournal, Blogger added to the 'Share' module. 

The same buttons "Share" are present in the service of YouTube and they are often used by people. These social networks are very popular and give good traffic to new visitors to the site. There is a need for such buttons to be accessible and on sites in one block. I do not want to add separate plug-ins for some buttons.

Thank you!

**Comment by jeherve** [comment]
VKontakte (VK) Odnoklassniki (OK), and LiveJournal are only used in specific countries (like Russia) and are not widely used all over the world, so we most likely won't be adding them to the default Jetpack sharing buttons.

Blogger, on the other hand, doesn't seem to offer an official sharing button.

Instead, I would recommend that you use the "Add New Service" option in Settings > Sharing to add your own custom sharing buttons. Here is [a tutorial](https://ryanmarkel.com/2968/adding-a-custom-sharing-service-to-wordpress-com/), as well as [some examples](https://ryanmarkel.com/3004/adding-specific-sharing-services-to-sharedaddy-or-jetpack/).

If you'd like to add the VK.com button to Jetpack's Sharing module, you can also use this plugin:
https://wordpress.org/plugins/vk-sharing-jetpack/

**Comment by DeadLift1975** [comment]
1. Russia, Ukraine, Belarus and other countries of the former USSR are 
millions of users. It seems to me that this is a sufficient audience in 
order to make a positive decision regarding the addition of a few 
buttons in the pack. 2. The "Share" button in the Blogger is available 
in Youtube, from which I can conclude that there is a public button.


28.03.2017 16:04, Jeremy Herve пишет:
>
> VKontakte (VK) Odnoklassniki (OK), and LiveJournal are only used in 
> specific countries (like Russia) and are not widely used all over the 
> world, so we most likely won't be adding them to the default Jetpack 
> sharing buttons.
>
> Blogger, on the other hand, doesn't seem to offer an official sharing 
> button.
>
> Instead, I would recommend that you use the "Add New Service" option 
> in Settings > Sharing to add your own custom sharing buttons. Here is 
> a tutorial 
> <https://ryanmarkel.com/2968/adding-a-custom-sharing-service-to-wordpress-com/>, 
> as well as some examples 
> <https://ryanmarkel.com/3004/adding-specific-sharing-services-to-sharedaddy-or-jetpack/>.
>
> If you'd like to add the VK.com button to Jetpack's Sharing module, 
> you can also use this plugin:
>



---
Это сообщение проверено на вирусы антивирусом Avast.
https://www.avast.com/antivirus

**Comment by jeherve** [comment]
> 2. The "Share" button in the Blogger is available in Youtube, from which I can conclude that there is a public button.

It doesn't appear to be an official sharing button, but you can add it as a custom sharing service by using the parameters detailed here:
http://stackoverflow.com/a/22583473/1045686
