### ISSUE TITLE
Pagination not working properly with 2 post type

### ISSUE THREAD

**Issue by victorquete** [Automattic/jetpack#6793]
#### Steps to reproduce the issue
Update the query with action 'pre_get_posts' and filter 'infinite_scroll_query_arg' to get 2 post type.

```php
add_action( "pre_get_posts", "function_pre_post" );
function function_pre_post( $query ) {
    if ( $query->is_main_query() && $query->is_home() ) {
        $query->set( "post_type", array( "post", "critica" ) );
    }
}
function jetpack_infinite_scroll_query_args( $args ) {
    $args["post_type"]   = array( "post", "critica" );
    return $args;
}
add_filter( "infinite_scroll_query_args", "jetpack_infinite_scroll_query_args", 100 );
```

#### What I expected / What happened instead

Infinite scroll working properly and loading 48 times, but only loaded 8 times. As if was getting posts from only one post type and ignoring the second.

**Comment by jeherve** [comment]
Could you give us more details about how Infinite Scroll support is added to your site? Do you use a custom function for the `render` parameter? If so, could you paste it here or contact us [via email](http://jetpack.com/contact-support/) about it?

Thanks!

**Comment by victorquete** [comment]
Sure!
Im using default render:

add_theme_support(
			'infinite-scroll',
			array(
				'type'           => 'scroll',
				'footer_widgets' => false,
				'container'      => 'content',
				'wrapper'        => false,
				'render'         => false,
				'posts_per_page' => get_option( 'posts_per_page' )
			)
		);

**Comment by jeherve** [comment]
Is there somewhere where we could download a copy of your theme to run some tests? If you'd like, you can send it to us via [this contact form](http://jetpack.com/contact-support/).

Thanks!

**Comment by victorquete** [comment]
Okay, I have sended an email

**Comment by jeherve** [comment]
Thank you. I'll close this issue, and we can continue this conversation via email.

**Comment by victorquete** [comment]
That is my answer:

"We're not able to help troubleshoot themes specifically, however, where did you add that function? Did you add it to your theme's functions.php file or somewhere else?"

Not even tested if was a bug or not...

**Comment by jeherve** [comment]
Don't hesitate to reply to the email with more information, we'll help you further!

**Comment by victorquete** [comment]
I did it.. I ll keep trying to talk with them..
thanks @jeherve
