### ISSUE TITLE
SSO: Conflict with rename-wp-login plugin

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#6806]
#### Steps to reproduce the issue

When using https://wordpress.org/plugins/rename-wp-login/ to change the url of the login page, Jetpack SSO results in a "too many redirects" error when trying to log in using wp.com

cc: @iseulde (the plugin author)

Reported in 3130858-t

**Comment by lukecav** [comment]
Seems like Rename wp-login.php uses.
https://github.com/iseulde/rename-wp-login
https://plugins.svn.wordpress.org/rename-wp-login/trunk/rename-wp-login.php

**new_login_url()**

**Comment by lamdayap** [comment]
reported here 3235942-t

**Comment by chaselivingston** [comment]
Similar issue reported in 725136-zen.

**Comment by bikedorkjon** [comment]
Similarly in 889129-zen

**Comment by kraftbj** [comment]
The best we could maybe do is sync the result of the wp_login_url function ( https://developer.wordpress.org/reference/functions/wp_login_url/ ) so we can pick up the filtered value.

It's not an option, so not sure the best way to handle it if this value changes often.

Either case, appears to be hard-coded to wp-login.php on the wp.com side via mu-plugins/jetpack/jetpack-sso.php#194

**Comment by iseulde** [comment]
If there's anything I can do, let me know. The plugin page warns about plugins that have wp-login.php hardcoded.

**Comment by jenhooks** [comment]
943126-zen

Also noting that this was previously reported in #1511 -- but that was closed in Feb. 2017.

**Comment by alshakero** [comment]
Since the last report on this issue was 6 years ago and the [plugin is now dead](https://wordpress.org/plugins/rename-wp-login/). I'm closing this issue.
