### ISSUE TITLE
Authentication: Problem with Wordpress.com Account Authentication

### ISSUE THREAD

**Issue by viraljetani** [Automattic/jetpack#6807]
#### Steps to reproduce the issue

Trying to connect Jetpack to my wordpress.com account and its been in a loop. Let me explain below using screenshots:

After activating jetpack i got the below screen:
![screen shot 2017-03-29 at 8 15 33 pm](https://cloud.githubusercontent.com/assets/1935495/24460907/457e8fce-14bd-11e7-9aa0-b9a104385404.png)

By clicking on Connect I am redirected to the below page:
![screen shot 2017-03-29 at 8 15 54 pm](https://cloud.githubusercontent.com/assets/1935495/24460942/5e4e32fc-14bd-11e7-9c7e-21c4aac40dd7.png)

As I am already logged in to wordpress.com it connects me automatically and shows i am connected But when I click on Return to your Website it takes me to the:
![screen shot 2017-03-29 at 8 16 15 pm](https://cloud.githubusercontent.com/assets/1935495/24460977/7697ad34-14bd-11e7-8ee9-0c5abf51bf6b.png)

And when i click on Select Free it takes me to the 1st step where I started:
![screen shot 2017-03-29 at 8 16 35 pm](https://cloud.githubusercontent.com/assets/1935495/24461072/b2a3bd54-14bd-11e7-972a-53810690426f.png)

And its asking me to connect again..
This happens everytime i am connecting and I am not able to connect..

**Comment by jeherve** [comment]
Can you please use Jetpack's Debugger module to send us some more information about your site?

<ol>
<li>Go to the Jetpack page in your dashboard.</li>
<li>Click on the <strong>Debug</strong> link appearing at the bottom of the page.</li>
<li>Click the link that says <strong>"click here to contact Jetpack support."</strong></li>
<li>Fill in the description box and your name and email address.</li>
<li>Click the "Contact Support" button to send us the debug results privately. <strong>It's best not to post this information on public forums, as it contains private details about your site.</strong></li>
</ol>
Thanks!
