### ISSUE TITLE
Masterbar: can't access local dashboard from admin bar anymore

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6818]
I think it would be important to add a WP-Admin link to the masterbar, so folks can continue to access their local dashboard when the Masterbar module is active. It's important as many plugins, including Jetpack, include some settings that can't be found in Calypso. There needs to be a way for site owners to access their dashboard without having to type `wp-admin` at the end of the URL when looking at the site's front-end.

Related: https://github.com/Automattic/wp-calypso/issues/11108

**Comment by vindl** [comment]
It was shown originally, but during PR review someone requested its removal :smile:, in 3rd point here:
https://github.com/Automattic/jetpack/pull/6413#issuecomment-285756882

Anyway, I'll bring it back soon. :)

**Comment by jeherve** [comment]
Huh, sorry about that! I'm not quite sure what I meant there.
