### ISSUE TITLE
Masterbar: support document doesn't exist yet.

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6820]
@vindl Could you prepare a draft, or let me know the kind of information you would like to include in the upcoming `/support/masterbar` support doc?

Thanks!

**Comment by vindl** [comment]
@jeherve sure, we'll prepare a draft for it.

**Comment by roundhill** [comment]
This doc could be improved, but I'll use it as the base: https://en.support.wordpress.com/admin-bar/

**Comment by roundhill** [comment]
@jeherve I sent a link to the draft to you via Slack.

**Comment by jeherve** [comment]
Support doc is now published. Thanks @roundhill!
