### ISSUE TITLE
Settings UI: navigating through tabs breaks the navigation

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6825]
#### Steps to reproduce the issue

1. Go to your site's dashboard.
2. Click on Jetpack > Settings.
3. Click on the different tabs to discover new settings.
4. After clicking a few times, it stops working.

https://videopress.com/v/B3Z51tuT

Here are the errors I get in my console:

```
admin.js?ver=4.8-alpha:80960 Uncaught TypeError: Cannot read property 'data' of null
admin.js?ver=4.8-alpha:7454 Uncaught (in promise) TypeError: Cannot read property 'componentWillReceiveProps' of null
admin.js?ver=4.8-alpha:5549 Uncaught TypeError: Cannot read property '_currentElement' of null
admin.js?ver=4.8-alpha:73840 Uncaught TypeError: _analytics2.default.tracks.recordJetpackClick is not a function
admin.js?ver=4.8-alpha:7454 Uncaught TypeError: Cannot read property 'componentWillReceiveProps' of null
```

**Comment by dereksmart** [comment]
> _analytics2.default.tracks.recordJetpackClick is not a function

That tells me that you're somehow running an older dops-components dependency.  Are you running the built version of the plugin?  Or does this happen in a manually-built version?

**Comment by eliorivero** [comment]
I think this is invalid. I went through the tabs clicking up to 30 times and it's still switching fine. Maybe like Derek says you've an outdated dops.
Will close for now.

**Comment by jeherve** [comment]
I was running a manually built version, so I'll try to start from scratch. Thank you both! 👍
