### ISSUE TITLE
Settings UI: can't activate or configure Sharing and Publicize when it's deactivated

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6837]
#### Steps to reproduce the issue

1. Start from a Jetpack site where both Sharing and Publicize are deactivated (you can do so in the old module list).
2. Go to Jetpack > Settings > Sharing.
3. I see no indication that the modules are off, nor any link to turn them on:

![screen shot 2017-03-30 at 20 16 30](https://cloud.githubusercontent.com/assets/426388/24519525/cabe908a-1585-11e7-8c2e-1b6d1da28943.png)

4. I click on the links to "Connect your social media accounts" and "Configure your sharing buttons": I'm redirected to the Stats page in Calypso. That's confusing; I guess I'll use another plugin to handle sharing then.

**Comment by dereksmart** [comment]
This is supposed to be handled in Calypso, as it should always show a UI there regardless of module status.  I suppose it's not done yet cc @oskosk 

> Ideally we need those UIs to work regardless of if the modules are enabled remotely, but I'm filing this here as well because currently the broken flow is initiated here in Jetpack.

Reported in #6762

**Comment by dereksmart** [comment]
Can track the issue in Calypso here https://github.com/Automattic/wp-calypso/issues/11676

**Comment by jeherve** [comment]
This has been fixed since the link doesn't appear if the module isn't active anymore:

![screenshot 2017-06-02 at 13 06 18](https://cloud.githubusercontent.com/assets/426388/26723326/56abdff4-4794-11e7-8425-52859208c382.png)
