### ISSUE TITLE
Post by email: mp3 files not supported.

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#684]
Steps to reproduce:
1. Activate post by email.
2. Send email containing an mp3 file as an attachment. 
3. Receive an email saying that mp3 file is an 'Invalid file type'

Expected behaviour or result: 
- The mp3 file should be playable withing the post. The same way if you added it via the post editor.
  Actual behavior or result: 
- the file is not being sent as an attachment to the blog. 

Screenshots:
http://d.pr/i/pT6E.png

**Comment by hoverduck** [comment]
@jeherve - We get the same problem if attempting to add an mp3 file from inside Calypso.  The file-picker doesn't allow choosing mp3 files, but if you do manage to trick it into taking the file you get the same "invalid file type" error.  Do you know if this is actually being worked elsewhere, or is it just in limbo?

**Comment by jeherve** [comment]
> Do you know if this is actually being worked elsewhere, or is it just in limbo?

No one works on Post By Email right now, so "limbo" is probably a good way to describe things :)

**Comment by hoverduck** [comment]
Ha.  That doesn't surprise me.  Since it's Calypso too should we re-route the issue somewhere else?  I'm not sure who handles that stuff.  I could also write a new issue if that's easier

**Comment by jeherve** [comment]
It might be best to create a new issue in the wp-calypso repo, and add the "Editor" label. Team IO might be able to work on that, and it might fix the Post By Email issue at the same time since it also relies on the REST API.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/cannot-post-by-email-with-mp3-or-audio-files/

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
