### ISSUE TITLE
Sitemaps fail to activate properly on sites with many posts.

### ISSUE THREAD

**Issue by zinigor** [Automattic/jetpack#6854]
When you have a site with lots of posts (I tried around 1600), sitemaps fails to activate from the settings. It gets a timeout from the server and displays an `Invalid JSON` error in the notice. When I tried to generate them using cron, it ran for 20 minutes, got the load average to about 11, I had to kill it.

#### Steps to reproduce the issue
* Create a ton of posts, maybe even two tons.
* Activate the sitemaps feature.

#### What I expected
* Sitemaps to be activated.
* Message about the sitemaps being generated to disappear.

#### What happened instead
* I saw an error message, sitemaps did not activate until page reload.

cc @eliorivero @dereksmart

**Comment by eliorivero** [comment]
In progress in branch `fix/sitemaps-initial-generation`
