### ISSUE TITLE
Admin Page: spaces appear encoded in search form.

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6858]
#### Steps to reproduce the issue

1. Go to Jetpack > Settings.
2. Search for "Contact form"

![screen shot 2017-04-03 at 12 07 32](https://cloud.githubusercontent.com/assets/426388/24604790/938d0a5e-1866-11e7-98dd-7c999a49acb1.png)

**Comment by eliorivero** [comment]
It's always useful to add the browser this feature was tested in. It's fine for me in Chrome and Safari but it's failing as you describe in Firefox.

**Comment by jeherve** [comment]
It was in Firefox. Sorry about that, will mention it next time.
