### ISSUE TITLE
Would like to see contact form ajax'ed

### ISSUE THREAD

**Issue by EvanHerman** [Automattic/jetpack#686]
Most contact forms have an ajax option. It's more of a UX thing, but it's much nicer than having a page reload after submitting a form.

This is especially important when submitting contact forms from within a modal.

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/contact-form-through-ajax?replies=1&view=all

**Comment by kymcarlsson** [comment]
It would really be fantastic to see this make its way in..
If the ajax implementation also allowed for multiple ajax forms on a single page, I (and i'm guessing lots of others using premium contact form plugins) would be able to use jetpack exclusively for contact forms!

**Comment by ptasker** [comment]
This _can_ be accomplished just with JS/jQuery. https://gist.github.com/ptasker/7606fac1f75cfa99dc7d25dc178479f4

I posted a quick blog post about it. It's not bulletproof, if anything internal in the Jetpack API changes, but it works for now.

https://petetasker.com/jetpack-contact-forms-submitting-via-ajax/

**Comment by jeherve** [comment]
@ptasker 👍🏻  If you're interested in including this feature in Jetpack itself, feel free to submit a patch!

**Comment by ptasker** [comment]
@jeherve good point. It would likely be a bit more involved to get this into Jetpack. But when I have a few minutes I'll take a look and see what it would take. It may also help with 
https://github.com/Automattic/jetpack/issues/254

**Comment by kraftbj** [comment]
I'm going to close this for now—not a statement on the usefulness of the idea, but a reflection that it is not on our roadmap as an enhancement.
