### ISSUE TITLE
Admin Page: improve user experience with buttons to save settings

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6860]
#### Steps to reproduce the issue

1. Go to Jetpack > Settings.
2. Make changes to options, toggle features on and off.
3. I can see the "Save settings" buttons at the top of each card, but they stay grey. Why are they here if they're not meant to be used?

**Comment by dereksmart** [comment]
The save button should only appear for cards that have more types of settings than toggles.  Toggles automatically save the settings, whereas every other type (radio, input field, select dropdown, etc...) should enable the save button.

**Comment by jeherve** [comment]
Thanks for the explanation. I figured it was something like this, but I found it confusing for some cards where it's not obvious at first which setting will trigger a "Save Settings" button. The Carousel background color dropdown, for example, is one of the settings that requires a save, but I didn't expect it.

**Comment by jeherve** [comment]
I'll reopen this issue as it seems confusing to others as well. Maybe we could try to review this and see if it can be made more user-friendly.

> What’s up with the inactive save buttons on each setting section? Easily mistaken as broken or only half styled.
-- https://twitter.com/mikemcalister/status/862374953445982218

> When I change something, it gets saved via JS. Inactive button doesn’t change and remains despite the auto save.
-- https://twitter.com/mikemcalister/status/862377119787229184

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
