### ISSUE TITLE
Admin Page: some modules are not visible through the settings UI or the search form

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6861]
Since the Tiled Galleries module is now merged into the Photon module, maybe we should return the Photon toggle when someone searches for Tiled Gallery keywords?

![screen shot 2017-04-03 at 12 27 58](https://cloud.githubusercontent.com/assets/426388/24605403/fc5c9944-1868-11e7-9961-e02cd80681c7.png)

**Comment by dereksmart** [comment]
Here's a lost of other keywords that do not return results, though we provide these features: 

- json
- enhanced 
- shortlinks
- shortcode embed
- beautiful
- extra (sidebar widgets)
- widget visibility
- contact form
- monitor

This is because there is no more UI supporting any of these features.  Should we be returning some sort of helpful result in these cases? 

cc @MichaelArestad

**Comment by csonnek** [comment]
I was coming here to open an issue for Widget Visibility not returning any result. 

If the new UI doesn't have an "entry" for the feature, the result that should pop up is the "old" module list URL:

`.../wp-admin/admin.php?page=jetpack_modules`

Then, at least when searching for something, the user will be directed to the proper location to enable or disable the feature.

**Comment by jeherve** [comment]
Related: #6788

**Comment by zoonini** [comment]
Since my other ticket was closed, I'd like to add my specific suggestion here, since it didn't relate to search, which seems to be the focus of this ticket.

> As a temporary workaround for now, could we please consider adding something like this to each settings screen, maybe just above the "We're here to help" section:

**Looking for more features? See all modules**

> ...with a link to all the modules?

> This will prevent a lot of frustration.

**Comment by tmmbecker** [comment]
I just replied to a user with this exact same concern/frustration regarding shortlinks.
3167309-t

We should also update the documentation for all of these now hidden modules to indicate a direct link to toggle them.

**Comment by jeherve** [comment]
Let's continue the conversation in #6788, since there are some ideas to solve this issue there.
