### ISSUE TITLE
Admin Page: need to click twice to remove searchform

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6862]
#### Steps to reproduce the issue

1. Go to Jetpack > Settings.
2. Click on the search icon.
3. Launch a search. Find what you're looking for, make changes.
4. Click on the X icon to remove the searchform.
5. Where are the tabs I'd like to use to navigate to different settings? They're still hidden, I need to click once more on X to fully remove the searchform.

![screen recording 2017-04-03 at 12 39 pm](https://cloud.githubusercontent.com/assets/426388/24605808/9dae01c4-186a-11e7-87b9-bfd9881955df.gif)

**Comment by zinigor** [comment]
@eliorivero had a good idea to fix that problem by introducing a different icon for the close button. Because once you have filled the search bar it acts as a clear button, not as a close button. Do yout think it would be a more appropriate solution?

**Comment by eliorivero** [comment]
I voiced my concerns about this when this was being implemented:

https://github.com/Automattic/jetpack/pull/6424#pullrequestreview-25359217

> I like that the second click in the x exits the search mode. Maybe the first one should be a different symbol? One that indicates that clicking it will erase the field?

It feels broken having to click twice to close the field and without any change after the first click. It must be addressed using for example the ⌫ icon or something similar that indicates that the input field will be cleared. If we don't have the icon, maybe even the `Clear` word nicely composed will be enough.
