### ISSUE TITLE
Admin Page: Disconnection prompt mentions "WordPress support"

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6864]
#### Steps to reproduce the issue

1. Go to Jetpack > Dashboard.
2. Scroll down to the bottom of the page and click on "Manage site connection".
3. The modal mentions "Priority WordPress and security support". Since we only provide Jetpack support, we should probably change the wording here.

![screen shot 2017-04-03 at 13 53 53](https://cloud.githubusercontent.com/assets/426388/24608096/3661c7fc-1875-11e7-93fd-f66a2583e8b3.png)

**Comment by eliorivero** [comment]
@richardmuscat what should we say? ^

**Comment by richardmuscat** [comment]
@eliorivero / @jeherve -- this looks like its for a user on the Personal Plan, in which case its correct as it is. We _do_ offer priority support to personal plan users.

**Comment by jeherve** [comment]
@richardmuscat Sorry if I was unclear. My problem wasn't with *priority*, it was with *WordPress*. We do not offer general WordPress support.

**Comment by richardmuscat** [comment]
Ah. Then I guess we should say what we say elsewhere since it should be the same for all plans:

> Priority support

If we don't say that in other places we probably should :)

**Comment by eliorivero** [comment]
@richardmuscat PR at https://github.com/Automattic/jetpack/issues/6895
