### ISSUE TITLE
Admin Page: AtD style review

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6868]
<img width="388" alt="screen-shot-2017-04-03-at-13-29-57" src="https://cloud.githubusercontent.com/assets/426388/24611785/8720589e-1883-11e7-9e5e-396812e54e53.png">

Some styles could use some refining, namely:

- [x] Spacing in between subsections (Proofreading; Automatic Language Detection; etc.)
- [x] The “spelling” card is expanded, but it still has a border between the card title and options. No question the indenting helps, but my brain still sees three different sections at times in the screenshot above.
- [x] The “Ignored Phrases” sections seems to have an input inside an input?

**Comment by beaulebens** [comment]
For the Ignored Phrases section, it is indeed an input within an "input", which is correct, but it shouldn't be styled as such. Here's what it looks like with some tokens in there;

![screen shot 2017-07-27 at 2 51 10 pm](https://user-images.githubusercontent.com/108942/28691746-3c93df46-72db-11e7-820f-03fce8f75b63.png)

So the input should be there, but it shouldn't have an outline or shading, it should just appear as the prompt to click/type there to add another one.

**Comment by keoshi** [comment]
Missed this PR, sorry about that — I'm on it and should have a PR out soon.

**Comment by keoshi** [comment]
PR created in https://github.com/Automattic/jetpack/pull/7557
