### ISSUE TITLE
Admin Page: add intermediary state when changing options

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6869]
> The change confirmation is not immediate and leaves me hanging for a bit at times wondering whether my request was sent or not. Would be great if we can add an intermediary state, that would be replaced by the confirmation state once it loops back. This gets especially confusing in slower connections, when quick changes between the tabs happen

<img width="388" alt="screen-shot-2017-04-03-at-14-08-01" src="https://cloud.githubusercontent.com/assets/426388/24612510/c3a12a3a-1885-11e7-9b88-2700566d544c.png">

**Comment by dereksmart** [comment]
cc @MichaelArestad, this is the feedback I was worried about with removing the transitional notices.

**Comment by eliorivero** [comment]
Yes, this is a serious usability concern for users on slow connections.
