### ISSUE TITLE
Admin: Intelligently change the support link dependent on plan

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#6874]
![2017-04-03 12_10_06-jetpack brandon kraft wordpress](https://cloud.githubusercontent.com/assets/88897/24621271/8bc59a66-1866-11e7-81bd-577301bb9533.png)

For sites with an AT plan, we should use WP.com support links: https://wordpress.com/help/contact/ and https://wordpress.com/help/ respectively. 

cc: @kriskarkoski

**Comment by eliorivero** [comment]
Thanks for the report. I've started a PR to solve this in #6903
