### ISSUE TITLE
Settings UI: Toggles' hover styles only apply when moving your mouse over the toggle

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6878]
> Each block that has a toggle assigned to it is clickable, but the toggles don’t display the `:hover` behavior unless the cursor is on the toggle itself. It got me confused at first, thinking if the entire block was clickable or not.
>
> In my mind, if a block is clickable, then the elements that provide that change should always behave the same way, no matter which one you interact with.

Instead, it would be nice if this `hover` behaviour were to happen when moving your mouse anywhere on the text next to a toggle.

**Comment by rickybanister** [comment]
You're right, in Calypso hovering a label activates the checkbox and radio hover state, but not the toggle. We'll need to do this in Calypso as well.

**Comment by sirreal** [comment]
Proposed fix via dops-components: https://github.com/Automattic/dops-components/pull/108
