### ISSUE TITLE
Jetpack: secrets expiration

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/jetpack#6879]
There's a problem that is causing a recurrent error showing up in calypso's jetpack stats. We are generating the authorization-related secrets when the user visit the non-connected page. So if the user waits more than 10 minutes before they click on the "connect" button, or if they, for example, open the page again in another tab, and then click on connect on the first one, we are starting the authorization flow with an already outdated secret (which have been overwritten by another one). 

How to replicate:
============
a)
1. Get an unconnected site and open the jetpack tab.
2. Wait 10 minutes
3. Connect. You will get a connection error, then calypso will reattempt the connection and it should be successful on a second try
b) 
1. Get an unconnected site and open the jetpack tab.
2. Open the jetpack tab in a different tab
3. Go back to the first tab and connect. You will get a connection error, then calypso will reattempt the connection and it should be successful on a second try

**Comment by beaulebens** [comment]
Seems like instead of doing this, we should create a link within the UI, which points back to the local site anyway (that's how it already works I believe), and when we hit that URL, we generate secrets/set up the connection, then send them off. That would avoid this issue entirely, right?

**Comment by johnHackworth** [comment]
yeah, that's pretty much what we do when we start the connection from calypso ... so yeah, (I believe) it would solve the issue
