### ISSUE TITLE
Connection screen: merge support explanation with support block

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6883]
Before you connect Jetpack to your WordPress.com account, you'll see the following when going to the Jetpack menu in your dashboard:

![screen shot 2017-04-03 at 22 17 56](https://cloud.githubusercontent.com/assets/426388/24630025/68e1a53a-18bb-11e7-8c61-50381146b161.png)

And at the bottom of the page:

![screen shot 2017-04-03 at 22 18 21](https://cloud.githubusercontent.com/assets/426388/24630043/76f47e18-18bb-11e7-85aa-c2b6d1f37c2a.png)

There are a few issues with this:
1. The image used in the support description block is quite large; removing it would be a performance gain.
2. We've moved away from using faces in the support block; we should probably do the same in the support description.
3. The upgrade prompt appearing at the bottom of the support block doesn't work, since the site isn't connected to WordPress.com yet.
4. It's a bit odd to have 2 support blocks on the same page.

@beaulebens suggested the following 2 options:
> Just don’t include the banner on the support block before connection

> Could possibly just put the 2 buttons from the bottom block directly into the support block within the pre-connect screen.

**Comment by dereksmart** [comment]
> The image used in the support description block is quite large; removing it would be a performance gain.

it would decrease the size of the plugin by ~500Kb

**Comment by rickybanister** [comment]
I'm happy to remove the image.

Hiding upgrade banners, or their not working before connection seems like a straight-up bug. We should be able to offer premium services to folks as a big incentive to connect. Is there a simple-ish solution for that?

cc @richardmuscat

**Comment by rickybanister** [comment]
Let's resurface this one. 

Now that we have the support footer, let's get rid of the other support block entirely and make sure the upgrade banner functionality is working properly. I think it's 100% desirable to be able to advertise paid features to non-connected users, but we need them to function properly. 

@dereksmart can we prioritize this for 5.2?
