### ISSUE TITLE
Tiled galleries: Use radio buttons instead of dropdown for types

### ISSUE THREAD

**Issue by ilincaroman** [Automattic/jetpack#6886]
I've recently done some User Testing on adding and editing galleries that come with the _Tiled Galleries_ from Jetpack. 

In one of the tasks I asked the subject to change the type of the gallery from the default (**Thumbnail Grid**) to **Circles**. I observed how the users usually couldn't find anything related to what the task described, telling me they can't see any "Circles" option. They weren't actually reading the label, just trying to figure it out while browsing around. Afterwards they would navigate back to the editor, add a new gallery and get blocked again, until they decide to click around and actually discover the option was in the dropdown.

My conclusion was that the dropdown is hiding one of the most important information related to the gallery: it's type. So, as a suggestion, I would represent the **Type** option as radio buttons instead of a dropdown menu:

![radio_buttons](https://cloud.githubusercontent.com/assets/15910943/24656759/5c7ea504-194c-11e7-936e-803d54bc52dd.png)

This may cut some of the back-and-forth navigation I've seen and also encourage faster exploration of the options (also, less clicks 😁  )

It would be nice to hear more about this and the reasoning behind choosing a dropdown for the option and also thoughts on my suggestion :)

**Comment by mcsmithers** [comment]
I'd like to try this out if that's okay.  I am fairly new to helping with bugs on open source so feedback would be appreciated.

**Comment by jeherve** [comment]
> I'd like to try this out if that's okay.

Of course, feel free to give it a try!

> I am fairly new to helping with bugs on open source so feedback would be appreciated.

I would recommend checking our contributing guides to help you get started. 

- Here is how to set up your development environment: https://github.com/Automattic/jetpack/blob/master/docs/development-environment.md
- Here is how to start working on your patch and submit it to us: https://github.com/Automattic/jetpack/blob/master/docs/guides/submit-patch.md

Once you've created a Pull Request, we'll review it and give you feedback on your work.

Thank you!

**Comment by sdixon194** [comment]
Closing out as a wontfix since the block editor, we're not actively looking to make improvements to features available only in the classic editor, but would be glad to review a PR if anyone wanted to take another look at this.
