### ISSUE TITLE
Jetpack_Sync_Module_Options initializes options_whitelist too soon

### ISSUE THREAD

**Issue by nabsul** [Automattic/jetpack#6888]
Related to #6887 

At least in the case of `Jetpack_Sync_Module_Options`, the full-sync is relying on `$options_whitelist` to get the list of options to sync. However, this value is set at startup, before `Jetpack_Sync_Module_WooCommerce` can add itself to the options whitelist hook.

I'd recommend removing this private variable altogether and relying directly on `Jetpack_Sync_Defaults::get_options_whitelist()`. The only issue would then be that some unit tests will probably need to be redesigned.

**Comment by enejb** [comment]
@nabsul Is this still an issue that should get addressed? 
Feel free to open it if you think this is the case.

**Comment by nabsul** [comment]
I barely remember what this is about any more. I say close it, and if it's a problem for someone else maybe they'll write a new issue and fix it.
