### ISSUE TITLE
Settings > Security > Backups and scanning: confusing banner/CTA state

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6902]
I have a test site which is on the Personal plan, with VaultPress installed but _not active_. When I go to Settings > Security > Backups and scanning I see this:

![screen shot 2017-04-04 at 1 24 28 pm](https://cloud.githubusercontent.com/assets/108942/24675516/ab69cef6-193c-11e7-8fcf-de26be23d28a.png)

The best "next step" in this scenario is to complete the set up of the plan I've already purchased, so I think we should hide the banner at the bottom until set up is complete.

Once VaultPress is fully configured, then we can show the banner again, which is actually promoting the next tier of service.

**Comment by dereksmart** [comment]
fixed in #7211
