### ISSUE TITLE
Double back arrow in plugins section

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#6912]
Sending from phone, sorry for external photo link and poor formatting. 

https://goo.gl/photos/aQggfpvfNBEVB9UT6

Note two back arrows in the plugin interface for jetpack sites, when navigating to a single plugin. 

Makes it hard to know which to click. 

Solution may be something like breadcrumb navigation.

**Comment by gravityrail** [comment]
Note this is on Android 7, Chrome 56

**Comment by eliorivero** [comment]
Hi Dan, this should be added as a [new issue on Calypso](https://github.com/Automattic/wp-calypso/issues/new) instead of this repo.
