### ISSUE TITLE
Monitor email subject adds a leading slash to https URLs

### ISSUE THREAD

**Issue by cfinke** [Automattic/jetpack#6913]
I got two Monitor emails today; these were the subjects:

```
[Jetpack Monitor] /www.chrisfinke.com is not loading!
```

and

```
[Jetpack Monitor] /www.chrisfinke.com is back up!
```

Note the leading slashes on my URL.  I suspect that somebody somewhere did not account for https URLs and did something like this:

```
$home_url_no_scheme = substr( $home_url, 7 );
```

but that's just a guess. ;-)

**Comment by jeherve** [comment]
@lezama Could you take a look? Looks like it's just one line down from yesterday's changeset, r153892-wpcom :)

**Comment by lezama** [comment]
ooops, fixed in r153959-wpcom
