### ISSUE TITLE
No account info and no way to sign out of site when WordPress.com toolbar enabled

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#6916]
#### Steps to reproduce the issue

Log in without SSO
Enable WordPress.com toolbar
Try to sign out of site

#### What I expected

Logged out

#### What happened instead

Nothing, also profile information seems to be missing

Screenshot:

https://goo.gl/photos/nod4YitLwLGjPpKD7

**Comment by gravityrail** [comment]
Jetpack 4.8, chrome 56 on Android 7

**Comment by dereksmart** [comment]
> no way to sign out of site

I can't reproduce this one -- the `sign out` button in the toolbar signs me out of wp-admin, even when I force the missing wpcom user data.  

Oh, this actually sounds like both problems may be coming from something weird that is happening with your local user ID.  Both signing out and retrieving the wpcom data depends on `get_current_user_id()` -- do you have any idea what, if anything, could be mangling that or cause it to return inconsistent data?

**Comment by jeherve** [comment]
> Both of these rely on the Jetpack::get_connected_user_data() method that will return false and cause this bug if the xml request to get the wpcom user data fails for some reason.
>
> We're caching this result, and the transient key is based on the local user ID, so I guess you're viewing this as a user who has never logged into wp-admin Jetpack dashboard before?

**Comment by gravityrail** [comment]
Actually I'm viewing as the user i always log in as. But possible this isn't affecting many people. But this has been a Jetpack site for years, admittedly one that had a lot of weird branches of jetpack loaded on it ;)

**Comment by jeherve** [comment]
Could you try to start from scratch after disconnecting / reconnecting to WordPress.com, and see if the problem remains?

Thanks!

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
