### ISSUE TITLE
Array dereferencing in Jetpack 4.8 sitemap module breaks sites running PHP < 5.4

### ISSUE THREAD

**Issue by cfinke** [Automattic/jetpack#6918]
#### Steps to reproduce the issue

1. Have a site running a version of PHP lower than 5.4. Mine is running 5.2.17.
2. Install Jetpack 4.7.
3. Activate the Sitemap module.
4. Attempt to upgrade to Jetpack 4.8.

The site will now be inaccessible due to PHP 5.2's inability to parse the array dereferencing on line 87 of `modules/sitemaps/sitemap-state.php`:

```
$state['max'] = get_option( 'jetpack-sitemap-state', self::initial() )['max'];
```

wp-admin reported that the update failed, but it apparently still succeeded far enough to break the site.  The failure report may have just been because the AJAX endpoint was broken too, so the still-loaded front end interpreted that as an update failure.

#### Steps to prevent this issue in the future.

On a host running the bare minimum version of PHP that will be supported, this command will list any PHP files that cannot be parsed by this version of PHP:

```
for file in `find . -name "*.php"`; do php -l "$file" | grep -v "No syntax errors detected"; done
```

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/jetpack-4-8-on-multisite-white-screens-some-but-not-all/
https://wordpress.org/support/topic/problems-after-update-jetpack/
https://wordpress.org/support/topic/jetpack-4-8-renders-site-unavailable/
https://wordpress.org/support/topic/500-error-with-jetpack-4-8-update/
