### ISSUE TITLE
Module activation and deactivation broken in Jetpack >= 4.8 when PHP < 5.4

### ISSUE THREAD

**Issue by cfinke** [Automattic/jetpack#6932]
The `Jetpack_Core_API_Module_Toggle_Endpoint::activate_module()` method in Jetpack 4.8+ begins like this:

```
$module_slug = isset( $request['slug'] )
    ? $request['slug']
    : $request;
```

Sometimes (and I'm not sure exactly what determines this), `$request` is a string, and its value is the slug of the module being activated. Other times (presumably, based on the code), `$request` is an array.  When it's a string (which happens at least when clicking the activate/deactivate toggles in wp-admin), neither activation nor deactivation will work.

One of PHP's fun little quirks is that in older versions of PHP, using `isset()` to treat a string like an array would return `true` if the string is at least one character long. ([Fixed in PHP 5.4](http://php.net/manual/en/function.isset.php#refsect1-function.isset-changelog)) So in this example, the code checks whether `$request['slug']` is set. `'slug'`, somewhere, gets cast to `0`, and then PHP checks if `$request[0]` is set, and it is -- it's the first letter of the string.  So `$module_slug` ends up getting set to the first character of the real module slug, causing the rest of the activation sequence to fail, because the next line:

```
if ( ! Jetpack::is_module( $module_slug ) ) {
```

is actually checking whether a module exists using the first character from the module slug, and this will always fail.

A possible fix: change the code at the beginning of the function to:

```
$module_slug = is_array( $request ) && isset( $request['slug'] )
    ? $request['slug']
    : $request;
```

This change would also apply to the `Jetpack_Core_API_Module_Toggle_Endpoint::deactivate_module()` method.

**Comment by aheckler** [comment]
3148171-t

and probably some folks in this thread:

https://wordpress.org/support/topic/markdown-no-longer-working-in-jetpack-4-8-1/
