### ISSUE TITLE
Jetpack's auto-update service should have been disabled for WooCommerce 3.0

### ISSUE THREAD

**Issue by arjenlentz** [Automattic/jetpack#6933]
#### Steps to reproduce the issue

Hindsight required.

#### What I expected

WooCommerce 3.0 is a major update, likely to break a site unless all other plugins are compatible, and other factors. Thus, it's way too dangerous to auto-update.
Since Jetpack and WooCommerce essentially come from the same company, some internal communication should have occurred, with the Jetpack auto-update service getting disabled for ALL sites for WooCommerce, so that there would not be any accidental updates to 3.0

#### What happened instead

Some sites will have updated. Kaboom.

That's a lot of sites around the planet. Really must be more careful with these things, people! We have the tech to prevent this.

Backups are wonderful, of course.
This is perhaps a good time to implement a "oops, downgrade" option to the upgrade service. Naturally, that's only possible if the db schema hasn't already been upgraded also - luckily he WC 3.0 doesn't do that, otherwise way more people would be crying now.

**Comment by arjenlentz** [comment]
ping @mattyza

**Comment by arjenlentz** [comment]
Perhaps the auto-update service should also automatically click itself off when the major version# increments. I realise this is not a catch-all and depends on plugin devs using a sane versioning system, but at least it'll catch some which is way better than none.

**Comment by mattyza** [comment]
Thanks for posting this, @arjenlentz.

I'll watch this issue and keep an eye on feedback from the Jetpack team.

**Comment by jeherve** [comment]
Since the auto-update service lives in Calypso, it might be best to open an issue [there](https://github.com/Automattic/wp-calypso/issues); I don't think we'd be able to stop auto-updates from Jetpack itself

**Comment by arjenlentz** [comment]
@jeherve, total fail.
From a user's perspective, everything Automattic is one organisation. One would presume that developers there care for their users, and when notified of a serious issue such as these would INTERNALLY take whatever action is required to rectify that issue and prevent it from happening in the future, which might indeed include passing on information to another dev team.
Tossing that back at a user who bothers to report the problem... they might think you don't actually care.

How about, if you do care, you get it sorted out. Don't give users the procedural runaround because really, it doesn't impress me at all.

**Comment by jeherve** [comment]
@arjenlentz I moved your issue to the wp-calypso repository:
https://github.com/Automattic/wp-calypso/issues/13794

**Comment by arjenlentz** [comment]
Thank you @jeherve, that is most helpful.
I also understand from @mattyza that other conversations and work is happening internally to improve the processes so that upgrade problems such as these can be avoided. That's an excellent outcome.
Thanks
