### ISSUE TITLE
Bug: Dashboard / Settings resulting in error 500 on 4.8.x

### ISSUE THREAD

**Issue by cameronterry** [Automattic/jetpack#6943]
I upgraded to 4.8.0 version upon release on 4th April 2017 on my music website, DemonsZone.com, and noticed that the Dashboard and Settings area of Jetpack in the WordPress admin area were issuing a 500 error. The following is the entire output of the page;

```
<!DOCTYPE html>
<!--[if IE 8]>
<html xmlns="http://www.w3.org/1999/xhtml" class="ie8 wp-toolbar"  lang="en-GB">
<![endif]-->
<!--[if !(IE 8) ]><!-->
<html xmlns="http://www.w3.org/1999/xhtml" class="wp-toolbar"  lang="en-GB">
<!--<![endif]-->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Jetpack &lsaquo; DemonsZone &#8212; WordPress</title>
<script type="text/javascript">
addLoadEvent = function(func){if(typeof jQuery!="undefined")jQuery(document).ready(func);else if(typeof wpOnload!='function'){wpOnload=func;}else{var oldonload=wpOnload;wpOnload=function(){oldonload();func();}}};
var ajaxurl = '/wp-admin/admin-ajax.php',
	pagenow = 'toplevel_page_jetpack',
	typenow = '',
	adminpage = 'toplevel_page_jetpack',
	thousandsSeparator = ',',
	decimalPoint = '.',
	isRtl = 0;
</script>
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<link rel='dns-prefetch' href='//s0.wp.com' />
<link rel='dns-prefetch' href='//s.w.org' />
<link rel='stylesheet' href='https://demonszone.com/wp-admin/load-styles.php?c=1&amp;dir=ltr&amp;load%5B%5D=dashicons,admin-bar,common,forms,admin-menu,dashboard,list-tables,edit,revisions,media,themes,about,nav-menus,widgets,site-icon,&amp;load%5B%5D=l10n,buttons,wp-auth-check&amp;ver=4.7.3' type='text/css' media='all' />
<!--[if lte IE 7]>
<link rel='stylesheet' id='ie-css'  href='https://demonszone.com/wp-admin/css/ie.min.css?ver=4.7.3' type='text/css' media='all' />
<![endif]-->
<link rel='stylesheet' id='acf-global-css'  href='https://demonszone.com/wp-content/plugins/advanced-custom-fields-pro/assets/css/acf-global.css?ver=5.5.11' type='text/css' media='all' />
<link rel='stylesheet' id='yoast-seo-adminbar-css'  href='https://demonszone.com/wp-content/plugins/wordpress-seo/css/adminbar-450.min.css?ver=4.5' type='text/css' media='all' />
<link rel='stylesheet' id='yoast-seo-admin-global-css'  href='https://demonszone.com/wp-content/plugins/wordpress-seo/css/admin-global-450.min.css?ver=4.5' type='text/css' media='all' />
<link rel='stylesheet' id='yoast-seo-dismissible-css'  href='https://demonszone.com/wp-content/plugins/wordpress-seo/css/wpseo-dismissible-450.min.css?ver=4.5' type='text/css' media='all' />
<link rel='stylesheet' id='AtD_style-css'  href='https://demonszone.com/wp-content/plugins/jetpack/modules/after-the-deadline/atd.min.css?ver=20150715' type='text/css' media='screen' />
<link rel='stylesheet' id='jetpack-icons-css'  href='https://demonszone.com/wp-content/plugins/jetpack/css/jetpack-icons.min.css?ver=4.8.1' type='text/css' media='all' />
<link rel='stylesheet' id='genericons-css'  href='https://demonszone.com/wp-content/plugins/jetpack/_inc/genericons/genericons/genericons.css?ver=3.1' type='text/css' media='all' />
<link rel='stylesheet' id='jetpack-admin-css'  href='https://demonszone.com/wp-content/plugins/jetpack/css/jetpack-admin.min.css?ver=4.8.1-20121016' type='text/css' media='all' />
<link rel='stylesheet' id='dops-css-css'  href='https://demonszone.com/wp-content/plugins/jetpack/_inc/build/admin.dops-style.css?ver=4.8.1' type='text/css' media='all' />
<link rel='stylesheet' id='components-css-css'  href='https://demonszone.com/wp-content/plugins/jetpack/_inc/build/style.min.css?ver=4.8.1' type='text/css' media='all' />
```

Strangely the PHP and NGINX error logs provide no errors. Debugging the code, I have noticed that if I comment out the following line - the Dashboard works again;

https://github.com/Automattic/jetpack/blob/4.8.1/_inc/lib/class.core-rest-api-endpoints.php#L2109

Following the code a bit further, it seems to be caused specifically by this line and the "Monitor" module;

https://github.com/Automattic/jetpack/blob/4.8.1/_inc/lib/class.core-rest-api-endpoints.php#L2279

It seems for some reason, it is attempting to include the "Monitor" module twice on my website. The 4.8.1 release exhibits the same problem.

I thought I would report this as I noticed that the "Monitor" module [doesn't have the same kind of checks](https://github.com/Automattic/jetpack/blob/4.8.1/modules/monitor.php) as the other modules such as [Stats](https://github.com/Automattic/jetpack/blob/4.8.1/modules/stats.php#L17-L24).

Apologies for the opaque description, I couldn't acquire enough knowledge of Jetpack's codebase to provide more clarity.

**Comment by rickalee** [comment]
Confirming this same issue with blank Settings screen on our multisite with Montior enabled.

**Comment by todeveni** [comment]
Just upgraded from 4.7.1 to 4.8.1. Same problem.

`Fatal error: Cannot declare class Jetpack_Monitor, because the name is already in use in /.../wp-content/plugins/jetpack/modules/monitor.php on line 15`

**Comment by eliorivero** [comment]
Hi everyone, thanks for the detailed reports. I wonder if you could test this pull request where we're attempting to solve this issue

https://github.com/Automattic/jetpack/pull/6944

If you use Git, you can fetch the branch
`git checkout fix/monitor-maybe-instanced-twice`
and upload to your server the files
`jetpack/_inc/lib/class.core-rest-api-endpoints.php`
`jetpack/modules/monitor.php`
placing them in the corresponding folder.

You can also download the files directly from GitHub
https://raw.githubusercontent.com/Automattic/jetpack/6e5da8b8c856a00321a272630d7ea8ce6ac1bb4d/_inc/lib/class.core-rest-api-endpoints.php
https://raw.githubusercontent.com/Automattic/jetpack/6e5da8b8c856a00321a272630d7ea8ce6ac1bb4d/modules/monitor.php
and upload them to the right location in the server.

**Comment by dereksmart** [comment]
It might be worth checking if `@include_once` rather than `include` solves it here?

https://github.com/Automattic/jetpack/blob/4.8.1/_inc/lib/class.core-rest-api-endpoints.php#L2279

**Comment by dereksmart** [comment]
We have been unable to reproduce this bug on our end, so for anyone experiencing this to test one of the suggestions above, we would be very grateful!

**Comment by eliorivero** [comment]
PR that uses `include_once` is here https://github.com/Automattic/jetpack/pull/6945
If you could test it as well, it would be great since we're not able to reproduce it. We were able to track this issue down to this area yesterday but after solving it in the affected site, it never reappeared again.
Thanks!

**Comment by cameronterry** [comment]
@eliorivero thanks for the response. PR #6944 resolved the issue for me on my music website after putting the two changed files on.

**Comment by eliorivero** [comment]
Thanks @cameronterry for confirming it works!

**Comment by todeveni** [comment]
I'm unable to reproduce after I backed out to 4.7.1 and tried to update again. Now 4.8.1 works as it should.

Oh well. ¯\_(ツ)_/¯

**Comment by eliorivero** [comment]
@todeveni do/did you have some cache plugin installed and active?

**Comment by todeveni** [comment]
@eliorivero "Memcached Redux" object cache plugin.

**Comment by eliorivero** [comment]
Thank you 👍

**Comment by kevinlisota** [comment]
I see the same error with 4.8 and 4.8.1

**Comment by dereksmart** [comment]
@kevinlisota Thanks for the report.  We're planning on including the #6944 in the next release to resolve this.  If you're able to test it out let us know how it goes!
