### ISSUE TITLE
Support for multiple og:image values

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/jetpack#695]
Open Graph supports multiple og:image values — it would be nice if Jetpack did as well.

Specifically, if I were to return an array for og:image in the `jetpack_open_graph_tags` filter, Jetpack would gracefully output multiple images.

**Comment by GhostToast** [comment]
@jeherve I'm not seeing where `$max_images` is actually used in `jetpack_og_get_image()`, a function which appears to only return one `$image`, regardless of how many it receives.

**Comment by jeherve** [comment]
@GhostToast You're right, it isn't used anywhere.

Are you trying to use that function somewhere else at the moment, and facing issues? If so, it might be best to start a new issue, as this one is closed.

**Comment by GhostToast** [comment]
@jeherve Yea I think multiple image support may have regressed, if it was ever supported, without having Publicize active. There are certainly enough hooks to work around this, however, so I'm just building a workaround. It does seem weird that all the images are processed though and then discarded in favor of using exactly the last one found in the stack. Might as well just stop after 1 in that case.

**Comment by jeherve** [comment]
> Yea I think multiple image support may have regressed, if it was ever supported, without having Publicize active. 

It was never supported when Publicize was deactivated. I'm actually not sure why, I think we could make that available to everyone, even when Publicize isn't active. I opened #3004 to discuss that option.

Thanks for the report!
