### ISSUE TITLE
Content-type set to "text/plain" for contact form emails

### ISSUE THREAD

**Issue by nalroff** [Automattic/jetpack#6951]
#### Steps to reproduce the issue

Send a contact form message and look at it in an email client.

#### What I expected

Formatted HTML email

#### What happened instead

HTML code displayed as plain text. There were some changes made to the `wp_mail` function that might have caused the issue:

https://github.com/WordPress/WordPress/commit/41666b5e0cda1508f541f1bd2bd166fb67c4274e

To prevent the dependency on `wp_mail` and PHPMailer to continue functioning as-is, wouldn't it be easier just to add the `Content-type` to the list of headers?

Note: I am also using the [GMail SMTP Plugin](https://wordpress.org/plugins/gmail-smtp/), but that doesn't seem to be causing the problem.

**Comment by jeherve** [comment]
> HTML code displayed as plain text.

Could you post a screenshot of how this looked like in your email client? Jetpack's Contact Form emails are meant to be sent as text/plain, because they don't usually include any HTML content. All they include is the content submitted by your readers.

Thanks!

**Comment by nalroff** [comment]
Thanks for the quick reply! Here ya go:

![contact-email-issue](https://cloud.githubusercontent.com/assets/770757/24828050/3a561adc-1c23-11e7-937c-f990f1a90f7a.png)

The issue also shows up for unverified users.

**Comment by jeherve** [comment]
That's odd. I can't seem to reproduce. Do you happen to have a different site where you could test and see if you can reproduce? I believe the problem may be caused by your email setup on that site.

**Comment by nalroff** [comment]
I do. I will give it a shot and post here. Thanks.

**Comment by nalroff** [comment]
Interesting. Somehow, the [GMail SMTP plugin](https://wordpress.org/plugins/gmail-smtp/) is messing with things. Screenshots from each scenario follow, if you're interested. It's obviously not Jetpack causing the problem, so I'll close the issue.

With GMail SMTP Plugin enabled:

![image](https://cloud.githubusercontent.com/assets/770757/24828336/8412b162-1c28-11e7-9d07-6b033247ddf6.png)

Without GMail SMTP Plugin enabled:

![image](https://cloud.githubusercontent.com/assets/770757/24828363/3561b800-1c29-11e7-82f5-951b5ee2874e.png)
