### ISSUE TITLE
Disable SEO module upon installation of Yoast, AIO SEO, & others.

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/jetpack#6953]
When the SEO module is active on a Jetpack site, it should be auto-disabled when another major SEO plugin package is installed and activated, to prevent conflicts.

Steps to reproduce:

1. Install Jetpack, activate, and activate the SEO module.
2. Install Yoast, All In One SEO, or another major SEO plugin, and activate.
3. Jetpack's SEO remains active.

Both sets of SEO metadata will be populated into the site.

<img src="https://cldup.com/5lhEVLCgzp.png" alt="" />

<img src="https://cldup.com/TSyJwvbLE3.png" alt="" />

**Comment by chrisfromthelc** [comment]
These would probably be good ones to start with, as they duplicate the Jetpack SEO features:

- Yoast
- All In One SEO
- SEO Ultimate
- SEO Framework

**Comment by jeherve** [comment]
Yep. For reference here is our current list for the opposite action (not enable Jetpack SEO Tools when one of those plugins is already active on the site):

```
		'seo-tools' => array(
			'WordPress SEO by Yoast'               => 'wordpress-seo/wp-seo.php',
			'WordPress SEO Premium by Yoast'       => 'wordpress-seo-premium/wp-seo-premium.php',
			'All in One SEO Pack'                  => 'all-in-one-seo-pack/all_in_one_seo_pack.php',
			'All in One SEO Pack Pro'              => 'all-in-one-seo-pack-pro/all_in_one_seo_pack.php',
		),
```

**Comment by chrisfromthelc** [comment]
The owner of this site: https://notanothermillennial.com/ is having this issue as well.

**Comment by chrisfromthelc** [comment]
I'm going to close this in favor of https://github.com/Automattic/automated-transfer/issues/180 as the issue seems to only be happening on AT sites, not all JP sites.
