### ISSUE TITLE
Calypso "Full Sync" Settings Enhancement

### ISSUE THREAD

**Issue by deancroyal** [Automattic/jetpack#6954]
If you head to WordPress.com for a Jetpack connected site and go to Settings > General, you'll see the option to perform a full sync:

![screen shot 2017-04-08 at 11 42 56 am](https://cloud.githubusercontent.com/assets/426388/24830887/d70be38c-1c8e-11e7-9213-124c0bd6e4bd.png)

The problem is there is no explanation for what it is that we are syncing. 

Enhancement request - include a link to this post (will rely on design for this):

https://jetpack.com/support/what-data-does-jetpack-sync/

**Comment by rickybanister** [comment]
We are working on a new design for this area. 

The sync card will look more like this:

![image](https://cloud.githubusercontent.com/assets/437258/24919491/e6801ab6-1eb1-11e7-9f4f-c9f5b26bdd0f.png)

And we can include an info icon that links to a support doc or similar there.

This issue should likely live in the wp-calypso repo however.

**Comment by jeherve** [comment]
Closing as that settings area lives in Calypso, and that screen has changed a bit. 

Feel free to open an issue in the Calypso repo if you still have some ideas for improvement.
