### ISSUE TITLE
Widget Visibility: memory issues on sites with lots of authors / editors

### ISSUE THREAD

**Issue by samvthom16** [Automattic/jetpack#6955]
For large user base (more than 25K), get_user() on line 55 of https://github.com/Automattic/jetpack/blob/master/modules/widget-visibility/widget-conditions.php exhausts the memory, causing a blank screen on the widgets page.

**Comment by jeherve** [comment]
This should have been fixed in #6699. Could you tell me more about your user base? Do you have a large amount of authors or editors on your site, or do they have a different role?

**Comment by samvthom16** [comment]
Yes we do have a large amount of authors because the platform is open for publishing like medium

**Comment by jeherve** [comment]
Thanks for the extra details! That's indeed something we need to look into, to improve scaling.

**Comment by kriskarkoski** [comment]
Suspected case of this in #2100667-zen (6,565 users, 6,560 with Customer role)
