### ISSUE TITLE
Facebook Page Plugin falls back to English for German formal (de_DE_formal)

### ISSUE THREAD

**Issue by Zodiac1978** [Automattic/jetpack#6956]
#### Steps to reproduce the issue
Adding the FB Page Plugin extra sidebar widget and set your blog to "Deutsch (Sie)" (German formal language)

#### What I expected
FB Page Plugin in German formal or German (maybe FB just supports German in general)

#### What happened instead
FB Page Plugin is using English

Related #2789

**Comment by jeherve** [comment]
Closing as duplicate of #5468
