### ISSUE TITLE
Add fallback default image for Related Posts when no image exists in posts

### ISSUE THREAD

**Issue by csonnek** [Automattic/jetpack#696]
When users have the Related Posts feature with the image display enabled and they do not have a featured image or an image in a post, the area where the image would be is empty. 

I recommend we have a set default fallback image (like Gravatar has a default image) that can be updated/replaced by the user with their own default image. Would like to see an upload/crop workflow similar to how the Header image upload in WordPress works. You upload an image, then proceed to a crop screen where the uploaded image is cropped to the set dimensions required by Related Posts (350px wide by 200px tall). 

Then, that default image would be used in the instances when the Related Post does not have a set featured image or any image in the post and fill in that empty space for a more balanced layout.

**Comment by jeherve** [comment]
Closing this issue, as adding a default image is already possible, thanks to the `jetpack_images_get_images` filter:

http://jetpack.me/2013/10/15/add-a-default-fallback-image-if-no-image/
