### ISSUE TITLE
Feature request: Move blocking external requests on post save to cron

### ISSUE THREAD

**Issue by mboynes** [Automattic/jetpack#6967]
On a news website I maintain, editors reported that post publishing was taking a long time. I looked through New Relic data for this site and found that Jetpack and VaultPress are making blocking requests on post save, and the Jetpack requests are relatively slow. On average, these requests combined add over a second to the save process, and on occasion, the Jetpack request takes upwards of 10 seconds. Here is a New Relic screencap from the last 7 days, ending today:

![jetpack-last-week](https://cloud.githubusercontent.com/assets/465154/24977716/fafc1f36-1f9b-11e7-8156-6c00681edeb2.png)

Looking at the four outlier transaction traces at the bottom, the requests to `jetpack.wordpress.com` took 10.0s, 10.3s, 4.7s, and 9.7s, respectively. Worth noting that the VaultPress request, while still blocking, was never more than 0.3s in these four traces (and from what I can tell, it's pretty much always within a 30ms range of the 280ms average).

I suggest moving these requests to run via wp-cron if possible, so they don't block the page load.

For what it's worth, this site is on WordPress.com VIP. Therefore, if any Automatticians look into this and want to dig deeper into the New Relic data, that's available :-).

**Comment by mjangda** [comment]
Probably should look into speeding up the requests themselves on the WP.com side too :)

**Comment by kraftbj** [comment]
Poseidon -- before digging, I'm going to venture it may be something with sync, though I thought that was already all cron'd.

**Comment by kraftbj** [comment]
For testing purposes, the modules enabled on this site: 
```
Array
(
    [0] => manage
    [1] => monitor
    [2] => protect
    [3] => sso
    [4] => stats
    [5] => vaultpress
    [6] => related-posts
    [7] => omnisearch
    [8] => publicize
    [9] => after-the-deadline
    [10] => verification-tools
    [11] => sharedaddy
    [12] => enhanced-distribution
    [13] => shortcodes
    [14] => notes
    [15] => subscriptions
)
```

**Comment by designsimply** [comment]
Because optimizing outliers may not impact overall performance ([ref](https://blog.newrelic.com/2017/12/18/transaction-traces-uses/)), and because this issue has not had any activity for over a year, I would like to remove the `[Pri] High` label. @Automattic/poseidon would you be willing to do a review of this issue in terms of priority?

@mboynes may I ask if the outlier transaction traces you noted from last year have improved? May I also ask what you're seeing in the average segment times in the transaction overview?

**Comment by mboynes** [comment]
@designsimply the site where I noticed this is no longer in operation. I did check another site hosted on WordPress.com VIP and did not see similar issues, so perhaps this was resolved.

**Comment by lezama** [comment]
we have iterated on Sync and VP a lot since this issue has been open, let's close it for now :)
