### ISSUE TITLE
Find another home for Plans

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#6973]
We still need a place to mange and view your current plan.

* Does it need to be in Jetpack?
* Does Jetpack needs its own plans view or can we send users to specific landing pages? (I think we already do to an extent. CC @richardmuscat )
* If it does need to be in JP, is there a better place than on the dashboard on the top nav (which we could utilize for deeper stats integration or something if we remove the Plans view since we already removing the Apps view). 

![image](https://cloud.githubusercontent.com/assets/1123119/25023258/6d3f98c4-2056-11e7-9184-56648a5bc499.png)

**Comment by jeherve** [comment]
Closing in favor of #6310
