### ISSUE TITLE
Stats: Respect Site Language

### ISSUE THREAD

**Issue by shield-9** [Automattic/jetpack#698]
I'm running WordPress site. The WP's language is Japanese. But in `wp-admin/admin.php?page=stats`,  the stats is shown by English.
Please respect *the site language setting* or *WP.com account language setting*.

**Comment by shield-9** [comment]
It seems stat is not working well with language config...

A Japanese user reported at forum: https://ja.forums.wordpress.org/topic/152324?replies=1

**Comment by shield-9** [comment]
Ping: @dereksmart

**Comment by jeherve** [comment]
@shield-9 Would you mind asking for their site URL, so we can take a closer look, or ask them to [send us an email](http://jetpack.me/contact-support/)?

Thanks!

**Comment by dereksmart** [comment]
@shield-9 thanks for the report.  I was able to reproduce and pushed a fix to dotcom.  All languages should be translating properly now.
