### ISSUE TITLE
Remove legacy stats views

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#6982]
Since we are putting some effort into making the Jetpack Dashboard super useful and a gateway to all the cool things including stats, we should remove the legacy stats views. We are going to need some redirects for those who bookmarked it or navigate to it via URL. The redirects should take the user to the JP dashboard.

CC @martinremy @gibrown

Note: this is non-urgent. We should implement any improvements to the dashboard before focusing on this.

**Comment by jeherve** [comment]
This can now be closed since the page was redesigned.
