### ISSUE TITLE
Social Menu: Add Bandcamp and Soundcloud icons

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/jetpack#6984]
@thomasguillot Are the Bandcamp and Soundcloud icons available in SVG format so we could add support to the social menu? These are helpful for music-related sites.

https://github.com/Automattic/jetpack/tree/49d35f8c4b6a5a0e32bbfd13460bbaed6a7a09c2/modules/theme-tools/social-menu

Suggested in: http://en.forums.wordpress.com/topic/theme-team-a-suggestion

**Comment by thomasguillot** [comment]
Bandcamp and Soundcloud are both already available in SVG (see https://raw.githubusercontent.com/Automattic/jetpack/49d35f8c4b6a5a0e32bbfd13460bbaed6a7a09c2/modules/theme-tools/social-menu/social-menu.svg) so themes using the SVG version of Social Menu will display these 2 icons.

**Comment by kathrynwp** [comment]
Ah, thanks @thomasguillot! It wasn't in the documentation, but @laurelfulford just updated it.
