### ISSUE TITLE
Replace WordPress logo on full screen connection page

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#6985]
The inline svg of the WordPress logo on the full-screen jetpack connection screen (viewable on the plugins list page) is based off an older gridicon that has improper dimensions. It needs to be updated to display a correct WordPress logo.

<img width="1280" alt="screen shot 2017-04-17 at 3 32 16 pm" src="https://cloud.githubusercontent.com/assets/214813/25101684/27bb2482-2383-11e7-90de-3846aa486ac5.png">

to test:
1) disconnect jetpack from wpcom
2) deactivate jetpack
3) reactivate jetpack and view the plugins list page within wp-admin

cc @rickybanister cc @mattmiklic

**Comment by rickybanister** [comment]
The version of the logo in the social-logos repo is correct so perhaps we need a social-logos component in Jetpack.

**Comment by MichaelArestad** [comment]
@rickybanister is the social-logos repo a gridicons component (inline SVG?)

**Comment by rickybanister** [comment]
The social-logos repo is exactly the same as gridicons (external, open, has a calypso component) 

Here's the repo (the readme explains usage): https://github.com/Automattic/social-logos

**Comment by MichaelArestad** [comment]
@rickybanister perfect.

**Comment by crunnells** [comment]
This issue isn't relevant anymore. This is the current connection screen:

<img width="1469" alt="Screen Shot 2019-04-23 at 11 44 47 AM" src="https://user-images.githubusercontent.com/4297811/56618242-b74cd180-65bd-11e9-950e-15bb54b951bd.png">
