### ISSUE TITLE
Sharing: Facebook managed page options limited to 25 results

### ISSUE THREAD

**Issue by cianciabella** [Automattic/jetpack#6988]
I have a single Facebook account that manages about 150 pages currently and growing. When I go to connect to Facebook using Jetpack, I'm only able to choose from the first 25 pages returned. I'm not able to choose from the full list of managed pages. 

I assume you are using the GET /{user_id}/accounts function. This comes with a default limit of 25 results. 

Looks like a fix could be either A. use ?limit=999 to show all results on a single page or B. include Next/Previous links so we can get to the other pages of results.

Thanks!!

**Comment by jeherve** [comment]
Looks like you found the original issue in #1659. I'll close this, we can continue the conversation there.
