### ISSUE TITLE
Masterbar: Switch Site broken for single site user

### ISSUE THREAD

**Issue by designsimply** [Automattic/jetpack#6989]
Steps to reproduce:

1. Log in to a WordPress.com account that only has one site that is a Jetpack site.
1. Go to WP Admin > Jetpack > Settings.
1. Confirm that the "WordPress.com toolbar" option is enabled.
1. Go to Calypso > My Site and confirm that there is no "← Switch Site" option.
1. View the site front end.
1. On the front end, go to My Site > "← Switch Site".
1. Check to see if there's a redirect or any odd behavior.

<strong>Result:</strong> trying to switch sites using the "← Switch Site" option in the WordPress.com Masterbar for a WordPress.com account that has a single Jetpack site only results in a redirect and no option to select a site.

![20316c88-1aa7-11e7-9fe5-069093f8b794](https://cloud.githubusercontent.com/assets/1119271/25155263/6baaf4f0-2451-11e7-92bb-c28df9204596.png)
<sup>Seen at https://user336-automated-transfer-1.blog/ using Firefox 52.0.2 on Mac OS X 10.12.4 logged in as user336 unproxied.</sup>

/hat tip @kriskarkoski for the original report (internal ref: 114-gh-automated-transfer).

**Comment by vindl** [comment]
@designsimply This was resolved in https://github.com/Automattic/jetpack/pull/6766. If I remember correctly, AT sites were updated to Jetpack 4.8 which includes this fix on 10th of April. Prior to that, WordPress.com toolbar was served via `wpcomsh` and that version was still affected by this issue. 

I've tested this on my AT site now (running Jetpack 4.8.2) and it shows `Add New WordPress` instead of `Switch Site`.

**Comment by designsimply** [comment]
@vindl! I should have double checked it before moving the issue. I tried testing to confirm but was blocked by https://github.com/Automattic/jetpack/issues/6993

**Comment by vindl** [comment]
Hi Sheri! :wave: I've looked at the video from the linked issue, and this problem at least seems to be resolved. It worked fine in `wp-admin`, and the front page renders it the same way (it correctly showed singular `My Site` there, instead of plural, which depends on the same condition).
