### ISSUE TITLE
Tiled Galleries not working while in DEV mode.

### ISSUE THREAD

**Issue by kopepasah** [Automattic/jetpack#6991]
Seems like this issue was already addressed in #427, but I am wondering if there was a regression. The [current support doc](https://jetpack.com/support/development-mode/) states Tiled Galleries should still be enabled while in development mode.

#### Steps to reproduce the issue

- Ensure Photon is set to inactive (locally, this should never be set active).
- Enable Jetpack Dev Mode.
- Go to post to add a gallery. 

#### What I expected

- Option to set gallery type.

#### What happened instead

- No option was include to set a gallery type.

##### Info

__WP Version:__ Tested on 4.7.3 and Trunk
__Jetpack Version:__ 4.8.2

**Comment by jeherve** [comment]
That's indeed a side-effect of the new Settings UI in Jetpack, that now requires one to activate Photon to be able to use Tiled Galleries.

You should, however, still be able to activate the Tiled Galleries module in dev mode through the old full module list. Could you go to this page and try to activate the Tiled Galleries module?
`http://yoursite.com/wp-admin/admin.php?page=jetpack_modules`

Let me know how it goes.

**Comment by kopepasah** [comment]
@jeherve yes, I was able to activate using the old full module list.

**Comment by jeherve** [comment]
Related: #6861 #6788
