### ISSUE TITLE
Discussion: problems with avatar when user logs using facebook

### ISSUE THREAD

**Issue by RoccoMarco** [Automattic/jetpack#6992]
The problem is quite simple. It seems like photon (used by jetpack) is unable to fetch facebook user profile image. The result is a broken image.

Opening the photon link the result is a message witch says
"We cannot complete this request, remote data could not be fetched"

Removing the suffix "https://i0.wp.com/" from the url the avatar seems to be accessible.

I have the latest version of Wordpress with the latest stable version of Jetpack

**Comment by jeherve** [comment]
This will be fixed in #6872
