### ISSUE TITLE
Masterbar: "jQuery is not defined" error causes the masterbar to be unresponsive

### ISSUE THREAD

**Issue by designsimply** [Automattic/jetpack#6993]
Steps to reproduce:

1. For a new Jetpack install with Jetpack enabled, go to WP Admin > Jetpack > Settings.
1. Find the "WordPress.com toolbar" option and enable it.
1. Go to the site's home page.
1. Try to use any option in the masterbar.

<strong>Result:</strong> the following error appears in the console and the masterbar is unresponsive:

> ReferenceError: jQuery is not defined
> https://s0.wp.com/wp-content/mu-plugins/admin-bar/masterbar-overrides/masterbar.js:1:1

<img width="1280" alt="screen shot 2017-04-19 at wed apr 19 8 34 15 am" src="https://cloud.githubusercontent.com/assets/1119271/25185831/9ec06782-24db-11e7-91fc-f8325628d1e7.png">
<sup>Tested using Firefox 52.0.2 on Mac OS X 10.12.4 with WP 4.7.3 and Jetpack 4.8.2 on Pressable (brand new site, standard install).</sup>

Should the masterbar assume jQuery is on? Is jQuery loading early enough? As a user, I don't even know what that is or how to turn it on or why it's off for my site.

**Comment by jeherve** [comment]
I can't seem to be able to reproduce on my end. Is this limited to sites with a specific theme, or with a specific plugin installed?

**Comment by designsimply** [comment]
In the examples above, watchingstormsrollby.me (Pressable, WP 4.7.3, JP 4.8.2) is using the Twenty Sixteen theme and madefortesting.com (Bluehost, WP 4.7.3, JP 4.8.2) is using the Twenty Fifteen theme. I tried testing other themes and found the same problem happening:

![screen shot 2017-04-19 at wed apr 19 12 11 56 pm](https://cloud.githubusercontent.com/assets/1119271/25195110/cfce4538-24f9-11e7-9994-9e15385af653.png)
<sup>Seen at http://madefortesting.com/# using Safari 10.1 on Mac OS X 10.12.4 hosted at Bluehost running WP 4.7.3, JP 4.8.2, Twenty Twelve.</sup>

![screen shot 2017-04-19 at wed apr 19 12 14 17 pm](https://cloud.githubusercontent.com/assets/1119271/25195122/d5a7fa30-24f9-11e7-8031-c86391f7157e.png)
<sup>Seen at https://watchingstormsrollby.me/# using Firefox 52.0.2 on Mac OS X 10.12.4 hosted at Pressable running WP 4.7.3, JP 4.8.2, Twenty Seventeen.</sup>

They are each fairly vanilla installs (using whatever plugins were included by the host at setup time). Here are the plugins currently in use for each:

* watchingstormsrollby.me
 1. Akismet
 1. Jetpack
 1. VaultPress
* madefortesting.com
 1. Akismet
 1. Hello Dolly
 1. Jetpack

**Comment by vindl** [comment]
I've tried this on several test sites and couldn't reproduce. Tested on Chrome 57.0.2987.133/Firefox  53.0 and Ubuntu 16.04 LTS.

1. AT site on Pressable running WordPress 4.7.4 and Jetpack 4.8.2.
Plugins: Akismet, AMP, Contact form 7, VaultPress, Yoast SEO. 
Theme: Intergalactic.

2. Local Jetpack site running WordPress 4.7.4 and Jetpack 4.9-alpha. 
Plugins: none except Jetpack. 
Theme: Twenty Sixteen. 

3. Non-AT Jetpack site on Pressable, WordPress. 4.7.4 and Jetpack 4.8.2.
Plugins: none except Jetpack.
Theme: Twenty Sixteen.

**Comment by designsimply** [comment]
I re-tested and found it works fine with WordPress 4.7.4 but fails for 4.7.3. 

Closing as it appears to be fixed in WordPress 4.7.4.

**Comment by designsimply** [comment]
A similar issue (unresponsive masterbar links) was reported at #7529.

I re-tested using the original steps to reproduce from this issue and was able to reproduce the problem again using WP 4.9-alpha-41035 & JP 5.1-beta-12231-810ad1a-master hosted at WP Engine:

![screen shot 2017-07-25 at tue jul 25 11 22 41 am](https://user-images.githubusercontent.com/1119271/28585534-b1f34e66-712d-11e7-98a8-c4851aff45f5.png)
<sup>Tested using Chrome 59.0.3071.115 on Mac OS X 10.12.5</sup>

**Comment by designsimply** [comment]
I also re-tested with a site running latest stable versiosn, WP 4.8 and JP 5.1 (Bluehost), and I see the same jQuery error there as well:

> ReferenceError: Can't find variable: jQuery
> masterbar.js:1

![screen shot 2017-07-25 at tue jul 25 12 04 51 pm](https://user-images.githubusercontent.com/1119271/28586594-93b6df54-7131-11e7-8f54-1f564ffc62d6.png)
<sup>Seen at http://madefortesting.com/# using Safari 10.1.1 on Mac OS X 10.12.5.</sup>

**Comment by vindl** [comment]
Hey @designsimply! I created a PR that might resolve this bug: https://github.com/Automattic/jetpack/pull/7708. 
Could you apply it to one of your test sites and see if it resolves the issue?
