### ISSUE TITLE
Personal plan set up: "You have paid for backups but they're not yet active" message without a "set up" button to activate and configure VaultPress

### ISSUE THREAD

**Issue by sirreal** [Automattic/jetpack#6995]
#### Steps to reproduce the issue

1. Connect a new Jetpack site.
1. Upgrade to Personal plan on connect.
1. Checkout
1. Set up the plan (via button). This installs and activates VaultPress and Akismet.
1. When complete, return to Jetpack Settings > Security (`/wp-admin/admin.php?page=jetpack#/security`)
1. You should see the following confusing message, but there's no "Set Up" to click on:

   > Backups and security scanning
   > Learn more
   > You have paid for backups but they're not yet active. Click "Set Up" to finish installation.

#### What I expected

Everything works and is set up.

#### What happened instead

I'm confused! Where's the "Set Up" button? It's not clear what I'm supposed to do.

![where-set-up](https://cloud.githubusercontent.com/assets/841763/25191233/48a2db42-252f-11e7-97ec-2eaf1ec0368a.png)

Related: #6902 

cc @rickybanister

**Comment by aheckler** [comment]
Also in 3151031-t and the associated P2 thread.

**Comment by rickybanister** [comment]
cc @dereksmart 

I was going to suggest an interface improvement to add a notice here with a call to action to set up backups, but that doesn't appear to be the real issue.

Do we need to append something to the url to make sure there's some kind of refresh of the data? If backups are working normally we need to reassure the user that they are backed up.

**Comment by jeherve** [comment]
Also reported in p8oabR-2x-p2

**Comment by jeherve** [comment]
Also in 3174024-t (cc @tmmbecker)

**Comment by vduke** [comment]
Having the same issue.

**Comment by tmmbecker** [comment]
3199342-t

**Comment by jeherve** [comment]
Also in 3219609-t and 3219119-t

**Comment by aheckler** [comment]
3223374-t also

**Comment by joendotcom** [comment]
3229571-t
