### ISSUE TITLE
Add Upgrade banners to At a Glance items

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#6997]
I propose we try something a bit more attention-grabbing and less disabled-feeling for the At a Glance items that encourage upgrades.

Here is the current dashboard:
![dashboard - current](https://user-images.githubusercontent.com/1123119/35017534-7009e654-fada-11e7-89ac-ced52d375275.jpg)

And is here are the proposals for the dashboard with Banners instead:

![dashboard with banners - buttons](https://user-images.githubusercontent.com/1123119/35017535-701e153e-fada-11e7-98b3-e7baf5b0e3a1.jpg)

![dashboard with banners - caret](https://user-images.githubusercontent.com/1123119/35017536-702dbc82-fada-11e7-8610-8ba45381fa9f.jpg)

I would like to A/B test these two versions (with and without the button) for a month if you can swing it, Derek. 

Bonus points if you update the Banner component to be the same as Calypso (formerly UpgradeNotice). If not, just do the same thing with what we've got.

These particular boxes only show up for administrators so editors/etc won't see the banners. We also will only show them until someone purchase _any_ plan. Then they will be gone from the dashboard.

**Comment by richardmuscat** [comment]
This is looking really nice. For the others, we could go simple like:

> Automatically back up your site.

> Automatically protect against malware.

**Comment by jeffgolenski** [comment]
Agreed. I like the consistent use of our upgrade nudges/banners here!

**Comment by MichaelArestad** [comment]
@richardmuscat @nicoleckohler I updated the screenshots and copy for these. Would love your input. Try to keep em super short since space is tight here.

**Comment by nicoleckohler** [comment]
@MichaelArestad "backup" should be two words -- "back up" :) So "Upgrade to back up your site" or "Upgrade to back up your content."

For the spam one, let's keep it consistent and do something like "Upgrade to banish spam"?

I like 'em.

**Comment by crunnells** [comment]
This was resolved recently in the At a Glance tune-up project. See: 

- https://github.com/Automattic/jetpack/pull/12836
- https://github.com/Automattic/jetpack/pull/12835
- https://github.com/Automattic/jetpack/pull/12839
- https://github.com/Automattic/jetpack/pull/12600
