### ISSUE TITLE
Publicize: Add filter to allow plugins to bypass Publicize

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#7]
Add a filter that plugins can use to allow auto-generated posts not to trigger Publicize. Two use cases I've seen: a community site that uses an RSS aggregator to pull in headline/excerpts of members posts and an exercise app-connected plugin posting a new post after exercise.

https://github.com/Automattic/Jetpack/blob/master/modules/publicize/publicize.php#L221

**Comment by jeherve** [comment]
Reopening since 2beb14cce962d53a05df0f655f5db47d5fdbaad3 was reverted in e34c644533d98af5a83108c3b5af5f2cf7d3eeea

**Comment by jeherve** [comment]
Also requested here:
https://wordpress.org/support/topic/disable-publicize-by-category?replies=1&view=all

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/wpas_submit_post-hook

**Comment by mikeyarce** [comment]
Also requested here: 2225022-t

**Comment by jeherve** [comment]
Also requested here:
https://wordpress.org/support/topic/publicize-is-sharing-on-other-post-types

**Comment by jeherve** [comment]
Also requested here:
https://twitter.com/occasio/status/631158437905235968

**Comment by samhotchkiss** [comment]
What we may want to do is add a post meta field that opts out of publicizing.  This would require third-party plugins to create the post as a draft, set the meta, then publish.

Alternately, adding a filter that is checked on post creation that allows that meta to be added before it's sent onwards.

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/can-publicize-publish-only-certain-categories?replies=1&view=all

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/only-publish-some-category-publisize?replies=1&amp;view=all#post-8105298

**Comment by RCowles** [comment]
Also requested here:
https://wordpress.org/support/topic/publicize-actions-to-use-along-with-wp_insert_post?replies=5

**Comment by jeherve** [comment]
Here is how one could use this new filter. In the example below, we won't publicize any post using the `private` tag:

```php
/**
 * Do not trigger Publicize if the post uses the `private` tag.
 */
function jeherve_control_publicize( $should_publicize, $post ) {
	// Return early if we don't have a post yet (it hasn't been saved as a draft)
	if ( ! $post ) {
		return $should_publicize;
	}

	// Get list of tags for our post.
	$tags = wp_get_post_tags( $post->ID );

	// Loop though all tags, and return false if the tag's name is `private`
	foreach ( $tags as $tag ) {
		if ( 'private' == $tag->name ) {
			return false;
		}
	}

	return $should_publicize;
}
add_filter( 'publicize_should_publicize_published_post', 'jeherve_control_publicize', 10, 2 );
```

**Comment by chrisaldrich** [comment]
<a href="http://stream.boffosocko.com/2016/this-is-hopefully-a-simple-but-useful-feature-requesti-appreciate" class="u-in-reply-to"></a><a href="https://github.com/automattic/jetpack/issues/7#issuecomment-220964940" class="u-in-reply-to"></a>@kraftbj already responded, but for completeness: also suggested here: http://stream.boffosocko.com/2016/this-is-hopefully-a-simple-but-useful-feature-requesti-appreciate
(This also relates to jetpack_allow_per_post_subscriptions for email and alternate posting methods to WP including via email and [micropub](https://github.com/snarfed/wordpress-micropub) with clients like [Quill](https://quill.p3k.io/) 

Glad to know that JetPack is on GitHub :)
