### ISSUE TITLE
Include Image Size options in Post by Email

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#700]
It would be useful to be able to specify the size of the image to be displayed, such as being able to specify the thumbnail/small/medium/large size for an image. 

Requested in 1864219-t

**Comment by samhotchkiss** [comment]
Our implementation of Post by Email is intended to be very simple and minimal, so, unfortunately, this doesn't align with our development goals and plans at this time, and is not on our roadmap for future development.
