### ISSUE TITLE
SEO Tools: Can't enable in 4.8.2

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#7001]
#### Steps to reproduce the issue
1. Purchase and setup a Jetpack Professional plan for your site.
2. Visit Jetpack > Settings > Traffic in your site's Dashboard.
3. Click to configure your SEO settings - http://cld.wthms.co/R0yp
4. That redirects to https://wordpress.com/settings/traffic/[YOUR SITE URL] which then shows a message that the SEO module is not enabled. - http://cld.wthms.co/h2kG
5. Click "Enable" and you're redirected to /wp-admin/admin.php?page=jetpack#/engagement which doesn't exist anymore.
6. Now you end up at /wp-admin/admin.php?page=jetpack#/dashboard
7. Go back to https://wordpress.com/settings/traffic/[YOUR SITE URL] and the module is still disabled.

#### What I expected
The module to be activated upon clicking the "Enable" button.
#### What happened instead
I had to visit the old modules page at /wp-admin/admin.php?page=jetpack_modules to activate the SEO Tools module.

cc @rickybanister

**Comment by jeherve** [comment]
Related: #6544 Where we talked about similar issues with the Google Analytics module.

**Comment by jeherve** [comment]
Closing this issue in favour of https://github.com/Automattic/wp-calypso/issues/13255
