### ISSUE TITLE
Contact Form: emails sent as text/plain and including HTML tags

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#7003]
In #6658 we added HTML tags to all emails sent via the Contact Form module.

@iandunn It looks like our changes are not compatible with most plugins that overwrite `wp_mail()` to send emails via third-party email servers; the emails get sent with `Content-Type: text/plain` and yet include the HTML tags we've added in the PR above.

Would there be a way to avoid those issues by force-setting the content type, as discussed a bit in #6671?

Originally reported in 198-gh-jpop-issues

**Comment by iandunn** [comment]
Hmmmm, I'll play around with it and see what I can come up with.

**Comment by iandunn** [comment]
Yup, you and George are right, `wp_mail_content_type` should be used instead of relying on PHPMailer.

cbbe89b fixed the issue for me with the Postman SMTP and Gmail SMTP plugins. Let me know if any other reports come in using different plugins, and I'd be happy to test with them too.

**Comment by chaselivingston** [comment]
Also reported in 3168734-t.

**Comment by passegua** [comment]
I'm still having problem with Postman plugin, please have a look at: https://wordpress.org/support/topic/wrong-html-format-in-email-sent-by-wp/
Should I wait for a new Jetpack release?
Thanks.

**Comment by lschuyler** [comment]
Forums user confirmed the proposed patch solved the issue with the Gmail-smtp plugin:
https://wordpress.org/plugins/gmail-smtp/

https://wordpress.org/support/topic/4-8-2-the-contact-form-shows-html-tags/#post-9058122

**Comment by passegua** [comment]
@iandunn which patch are you referring to? I thought it was a bug in Jetpack, isn't it? Please help me in understanding this issue and how to solve it. Many thanks.

**Comment by iandunn** [comment]
It'd be https://github.com/Automattic/jetpack/pull/7018.diff

But, since it's been merged now, the easiest way to apply it might be to just install [the Jetpack Beta  plugin](https://jetpack.com/beta/). @jeherve, is that right?

**Comment by jeherve** [comment]
That's correct. The patch is included in the Beta version of Jetpack that was released yesterday.
