### ISSUE TITLE
Masterbar: missing "Menus" external icon link

### ISSUE THREAD

**Issue by designsimply** [Automattic/jetpack#7010]
The Calypso My Sites menu has an external icon indicator and Jetpack Masterbar does not.

![screen shot 2017-04-19 at wed apr 19 6 52 35 pm](https://cloud.githubusercontent.com/assets/1119271/25208782/06e4b9c8-2534-11e7-9122-fb3ddd784c47.png)
<sup>Seen at https://wordpress.com/types/jetpack-portfolio/alittletestblog.com and http://alittletestblog.com/wp-admin/edit.php?post_type=jetpack-portfolio (click on My Sites) using Safari 10.1 on Mac OS X 10.12.4.</sup>

Tested with WordPress 4.7.3 and Jetpack Beta (Build 1736160) on WP Engine.

**Comment by jeherve** [comment]
Also worth noting that the link is different. On WordPress.com we link to the customizer; in the Masterbar we link to Calypso's menu page.

**Comment by jeherve** [comment]
The "menu" item is now gone from the Masterbar. Closing.
