### ISSUE TITLE
Jetpack Infinite scroll on mobile bugged

### ISSUE THREAD

**Issue by victorquete** [Automattic/jetpack#7016]
Hello,
On mobile (Iphone) the infinite scroll is loading multiples times without doing scroll only one time(http://mobiletest.me/iphone_5_emulator/?u=http://setcenas.com.br/).
The type is configured to Scroll.

**Comment by jeherve** [comment]
Do you experience similar issues when switching to one of the default themes, like Twenty Sixteen, for a few minutes?

**Comment by victorquete** [comment]
No

**Comment by jeherve** [comment]
This would indicate issues with your theme; I would recommend that you get in touch with your theme author to let them know about the issue; if they're having issues understand what went wrong with their implementation of Jetpack's [Infinite Scroll](https://jetpack.com/support/infinite-scroll/), they can contact us here:
http://jetpack.com/contact-support/
