### ISSUE TITLE
Site Verification: Still visible in settings when disabled

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#7021]
If a user disables the 'Site Verification' module on the full modules list (/wp-admin/admin.php?page=jetpack_modules), they expect the Site Verification options to disappear from the Jetpack -> Settings -> Traffic page, but they do not.

Reported here: https://wordpress.org/support/topic/important-hidden-options-feature-toggles-and-doesnt-work-properly

**Comment by dereksmart** [comment]
I suppose we add a one-way activation banner here? @MichaelArestad

**Comment by MichaelArestad** [comment]
@dereksmart yep. Let's one-way it.
