### ISSUE TITLE
How to check if the Post is published via Rest API?

### ISSUE THREAD

**Issue by manzoorwanijk** [Automattic/jetpack#7042]
I'm using [save_post](https://developer.wordpress.org/reference/hooks/save_post/) hook in my plugin and I have to verify the `nonce` field set in the post edit screen. How do I check (inside the `save_post` callback function) if the post is published by Jetpack REST API? So that I verify the nonce field only if it's not published by REST API. Especially the posts published using **"Post by Email"**. May be any global variable is set or a meta value...??

**Comment by jeherve** [comment]
I'm not sure that's going to be possible, short of adding a custom taxonomy or post meta to separate posts posted via the API and the other posts. You would then be able to short-circuit your function when the taxonomy or post meta is present.

I hope this helps!
