### ISSUE TITLE
Widget Visibility breaks the widgets page and the Customizer

### ISSUE THREAD

**Issue by andreilupu** [Automattic/jetpack#7054]
#### Steps to reproduce the issue
For some reason when I activate the HTML minification on my hosting, it also applies to the Dashboard pages. I know this kind of behavior is not perfect and I already asked them for a solution in this case but still, there are lots of users unaware of this fact, and they will have this issue:

The Dashboard widgets page is broken because in the source page there are lots of HTML tags like this:
`<divclass="widget-conditionalwidget-conditional-hideconjunction">`

I've done some research and it seems that the widget's HTML isn't following the WordPress coding standards, especially [here](https://github.com/Automattic/jetpack/blob/86a84c642a50f904135b7de5f221ca71f138d41f/modules/widget-visibility/widget-conditions.php#L187-L205) where a newline is used as a separator instead of space.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
