### ISSUE TITLE
Contact Form: no way to disable module

### ISSUE THREAD

**Issue by bmiller-practis** [Automattic/jetpack#7056]
#### Steps to reproduce the issue

Install JetPack and connect to WordPress.com. 

Note: This issue does not appear to be occurring on sites that are already running JetPack and upgrading to the latest version.

The Feedback post type appears in the sidebar. The Add Contact Form button appears above the Content editor.

There is no way to disable this module through the settings pages.

#### What I expected

I expected to find a way to disable the Contact Form module using the settings pages.

#### What happened instead

I did not find a way to disable the Contact Form module.

**Comment by jeherve** [comment]
Thanks for the report. You can disable the module on this page:
`https://yoursite.com/wp-admin/admin.php?page=jetpack_modules`

We're tracking this issue in #6788
