### ISSUE TITLE
Feature request: Ability to lock down site domain to avoid false automatic repeating "Safe Mode" activations

### ISSUE THREAD

**Issue by archon810** [Automattic/jetpack#7061]
This has been happening to Jetpack for a long time, and I'm finally filing an official ticket to get it resolved. The premise:
- we have 4 web servers, serving the same WP site on www.domain.com
- each server has a name, and also a ServerAlias so that it can be accessed directly. Wordpress actually handles this really well. So I can go to server1.domain.com, and everything still works
- from time to time, sometimes rarely sometimes several times in a few days, Jetpack puts itself into safe mode because it thinks the domain has moved (from www to server1 or server 2, etc). Each time I convince it to migrate the stats back to www, but inevitably it happens again

So with this in mind, there has to be a way to lock down the domain, just like Wordpress does in its own settings and keep it as, say, www.domain.com.

Thoughts? Solutions?

Thank you.

**Comment by jeherve** [comment]
> there has to be a way to lock down the domain, just like Wordpress does in its own settings and keep it as, say, www.domain.com.

It might be worth trying to use the `WP_HOME` and `WP_SITEURL` constants in your wp-config.php ([reference](https://codex.wordpress.org/Changing_The_Site_URL#Edit_wp-config.php) to force the domain in use by WordPress. Jetpack should respect those settings. If it doesn't, let us know!

**Comment by archon810** [comment]
Hi @jeherve, thanks for replying.

In order for the individual server alias to also work and be accessible, we have this in our wp-config:
```
define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] . '/wordpress');
```

Is there a hook for overriding this just for Jetpack?

**Comment by jeherve** [comment]
Such change will indeed cause issues, as your WordPress installation constantly changes URLs. This is most likely causing other issues with other plugins on your site, in fact, if you happen to use plugins that expose your WordPress site URL to the outside world.

Could you try to add the following to your site's `wp-config.php` file?

```php
if ( $_SERVER["HTTP_HOST"] == "server1.domain.com" || $_SERVER["HTTP_HOST"] == "server1.domain.com" ) {
    define( 'JETPACK_STAGING_MODE', true );
}
```

It should get rid of the safe mode problem, but you won't be able to use some Jetpack features (like Secure Sign On) when accessing your dashboard from one of your subdomains.

Let me know if it helps.

**Comment by archon810** [comment]
@jeherve Awesome, thanks for the tip. I used the inverse, and it works great.

```
/**
 * Disable Jetpack production mode on individual production servers - make sure it's only enabled when accessed via www.
 * @link https://jetpack.com/support/staging-sites/
 * @link https://github.com/Automattic/jetpack/issues/7061
 */
if ($_SERVER["HTTP_HOST"] !== "www.domain.com") {
  define('JETPACK_STAGING_MODE', true);
}
```
