### ISSUE TITLE
Contact Form: Change button text from "Add" to "Modify" when form already exists

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#7063]
If you've created a contact form and have already added it to your page, and then later want to edit it, the button still says "Add Contact Form". That can be confusing; we should change the button to say "Modify Contact Form" if there's already a form inserted in the post or page. Currently we can't add a new form, as per #254

**Comment by jeherve** [comment]
Will be fixed by #7063

**Comment by jeherve** [comment]
I'll close this issue as it's similar to #642
