### ISSUE TITLE
Disable Protect when WP Cassify is being used on a site.

### ISSUE THREAD

**Issue by jenhooks** [Automattic/jetpack#7066]
Jetpack Protect appears to be conflicting with the [WP Cassify](https://wordpress.org/plugins/wp-cassify/) plugin, after upgrading to PHP 7.1. A user in 3145412-t is reporting the following fatal error when they log into WordPress with both Jetpack Protect and WP Cassify active:

`[error] [client IPAddress] PHP Fatal error: Uncaught ArgumentCountError:
Too few arguments to function
Jetpack_Protect_Module::log_successful_login(), 1 passed in
/wp-includes/class-wp-hook.php on line 298 and exactly 2 expected in
/wp-content/plugins/jetpack/modules/protect.php:314\nStack trace:\n#0
/wp-includes/class-wp-hook.php(298):
Jetpack_Protect_Module->log_successful_login('UserName')\n#1
/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)\n#2
/wp-includes/plugin.php(453): WP_Hook->do_action(Array)\n#3
/wp-content/plugins/wp-cassify/classes/wp_cassify_utils.php(225):
do_action('wp_login', 'UserName')\n#4
/wp-content/plugins/wp-cassify/classes/wp_cassify_plugin.php(459):
wp_cassify\\WP_Cassify_Utils::wp_cassify_auth_user_wordpress('UserName')\n#5
/wp-includes/class-wp-hook.php(298):
wp_cassify\\WP_Cassify_Plugin->wp_cassify_grab_service_ticket('')\n#6 in
/wp-content/plugins/jetpack/modules/protect.php on line 314`

Deactivating Protect makes the error go away.

**Comment by jeherve** [comment]
This will be fixed in the next version of Jetpack, thanks to #6892
