### ISSUE TITLE
UI: improve success message upon bulk module activation / deactivation

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#707]
When enabling or disabling multiple modules at the same time we should provide a better success message. Currently in 3.0 branch we only see a message for the last module being 
set. 

ping @MichaelArestad for ui suggestions.

**Comment by MichaelArestad** [comment]
Is this still needed with the new interface?

**Comment by jeherve** [comment]
Not really, as you can't bulk activate or deactivate modules anymore :(

Related: #4534

Closing this.
