### ISSUE TITLE
VideoPress: allow users to upload videos in Media > Add New

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#7073]
#### Steps to reproduce the issue
0. Start from a Jetpack site with an active Professional upgrade.
1. Go to Jetpack > Settings in your dashboard, and enable the VideoPress feature.
2. Go to Media > Library in your dashboard, and try to upload a Video: VideoPress works just fine.
3. Go to Media > Add New in your dashboard, and try to upload a video: VideoPress doesn't work. It's not supported there.

It would be nice if we could find a way to make VideoPress work there as well.

In #5911, we added a notice to help folks understand that this screen doesn't support VideoPress, but the notice is easy to miss or ignore, and can cause confusion when folks try to upload videos there, only to find that VideoPress doesn't work.

Here is an example of a screen where the notice is easy to miss:

![screen shot 2017-04-27 at 10 23 58](https://cloud.githubusercontent.com/assets/426388/25479025/bbc22be0-2b43-11e7-8fc4-9b3df56108f0.png)

Also reported in 212-gh-jpop-issues

**Comment by lamdayap** [comment]
3172165-t

**Comment by aheckler** [comment]
3236170-t

**Comment by kraftbj** [comment]
3281417-t

**Comment by druesome** [comment]
Are there updates on this issue?  This affects AT sites as well.  AT sites are bundled with a Jetpack Professional Plan.  Thank you!

**Comment by kraftbj** [comment]
@druesome Nope. This is the latest AFAIK.

**Comment by htdat** [comment]
985758-zen

**Comment by iamgabrielma** [comment]
1616552-zen

**Comment by iamgabrielma** [comment]
10141458-hc

**Comment by iamgabrielma** [comment]
1788083-zen

**Comment by gpmw** [comment]
#1849188-zen

**Comment by dereksmart** [comment]
The notice in #5911 has been broken for an unknown amount of time. I have a patch ready in D27505-code that fixes the JITM for this. 

When that is merged, I believe we should close this. If we want it actually fixed, let's re-open the issue in VideoPress repo.

**Comment by dereksmart** [comment]
The patch mentioned in my last comment has been merged. There will now be a notice displaying for all Jetpack sites running a plan with VideoPress active on this page directing them to `/wp-admin/upload.php` where the upload will work. 

It looks like this 
![image](https://user-images.githubusercontent.com/7129409/57474702-b58f3900-7260-11e9-945e-07f91cac6feb.png)

**Comment by apeatling** [comment]
@kwight & @mmtr This is affecting all Atomic sites, see: p7DVsv-6C7 Let's fix it up and close that gap.

**Comment by kwight** [comment]
From p7DVsv-6C7-p2:

_You can force Atomic sites to use VideoPress upon uploading by:_

- _Making sure the VideoPress Jetpack module is enabled_
- _Having the user upload directly to the media section in WP-Admin_
- _Making sure they are using Grid View instead of List View, as List View still uploads the video without VideoPress_

**Comment by lancewillett** [comment]
@kwight @apeatling Checking in on this one again as it came up in a recent Happiness report of top pain points.

**Comment by kwight** [comment]
@lancewillett Yep, still working on it 👍

**Comment by kwight** [comment]
(@lancewillett paYKcK-f0-p2 to follow along.)

**Comment by mmtr** [comment]
The "Media > Add New" page uses an older and different uploader than "Media > Library":

https://github.com/Automattic/jetpack/pull/5911#issue-98216664
https://github.com/Automattic/jetpack/pull/5911#issuecomment-267520880

I wonder if we could take a more pragmatic approach here and redirects users from `/media-new.php` to `/upload.php?mode=grid`, so uploads will happen with the already customized uploader.

**Comment by kwight** [comment]
I've done this with the JITM that displays on `media-new.php` in D33120-code.

The concern I have more aggressive forwarding is that the older uploader on `media-new.php` is usable without JS (and the new uploader is not), and this feels like an option we wouldn't want to completely remove from users.

**Comment by kwight** [comment]
D33120-code gives users a reliable path to a working uploader, while leaving `media-new.php` for any users relying on an older uploader that doesn't require JS. We're also close with [VideoPress working for Video blocks](https://github.com/Automattic/jetpack/pull/13682). Closing; anyone feel free to re-open if they don't think this is all good enough, and have another path forward to suggest 👍
