### ISSUE TITLE
VideoPress: Shortcode inserted differently in Chrome on Windows that breaks preview

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/jetpack#7079]
#### Steps to reproduce the issue

1. From wordpress.com/post insert a video in Chrome on Windows (confirmed in Chrome 57 on Windows 10)
2. The shortcode is inserted as `[video src="URL" height="undefined" width="undefined"]` compared to `[wpvideo ZTq0tBRo]` in Chrome on Mac. The Windows shortcode does not render a preview in the editor.

#### What I expected
The video preview to appear in the Editor on Windows and the shortcode to be inserted in the same format.

#### What happened instead
The preview is broken and the shortcode is different on Windows.

**Comment by jeherve** [comment]
> From wordpress.com/post

Since you experienced the issue when using the WordPress.com post editor, it's probably best if you report the issue in the wp-calypso repo.

Thanks!
