### ISSUE TITLE
Contact form: add a redirect option

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#708]
Jetpack’s contact form should need an option to redirect to a thank you page so that form conversions can be measured in popular analytics software like Google Analytics. Another option would be to fire a trackable event on the form submission so that an “event” is tracked in Google Analytics.

Here is a Jetpack add-on that adds such features:
- http://wordpress.org/plugins/42u-jetpack-booster/

Also suggested here: 
- http://wordpress.org/support/topic/jetpack-contact-form-click-submit-and-redirect-to-thank-you-page?replies=3

**Comment by aheckler** [comment]
Requested in 2063664-t.

**Comment by aheckler** [comment]
Request in 2176249-t.

**Comment by Christopher-Rose** [comment]
Any update on this?

A re-direct really ought to be a core function of any contact form and the 42U Jetpack Booster seems to be unmaintained as it is " Last Updated: 3 years ago Untested with your version of WordPress" My version being WP4.2.2

I hope this functionality can be expedited. Based upon the explanation in 42U, it doesn't seem very complex to implement: "To add a redirect to your Jetpack Contact Form, just add a text field named "redirect" to your form. It will be hidden on display.

From the HTML view, set the default value to the location where you would like the form to redirect after submission.

[contact-field label="redirect" type="text" default="/thanks/" /]

Note: you must replace the default each time after editing the form with the Jetpack WYSIWYG editor. The value is not saved by Jetpack.

Thanks

**Comment by kraftbj** [comment]
@Christopher-Rose - Updates will be posted here. There's a few folks who are planning on a larger review of the Contact Form, so not putting energy into enhancements deferring to the review.

**Comment by kraftbj** [comment]
This can be done programatically.

```
// Option 1: Redirect all forms to the same page.

add_filter('grunion_contact_form_redirect_url', 'jetpack_redirect_all_forms' );

function jetpack_redirect_all_forms(){
	return home_url( 'page_on_your_site' ); // e.g. 'thanks' for http://example.com/thanks. User wp_safe_redirect.
}

// Option 2: Selectively redirect forms to various pages.

add_filter('grunion_contact_form_redirect_url', 'jetpack_redirect_some_forms', 10, 3 );

function jetpack_redirect_some_forms( $redirect, $id ){ // $id represented the contact form's ID, found via the id attribute on the form.
	
	$redirects = array(
		'123' => home_url( 'page_on_your_site' ),
		'456' => home_url( 'another_page' ),
		'789' => home_url( 'page_on_your_site' ),
		);
		
	foreach ( $redirects as $origin => $destination ){
		if ( $id == $origin ) {
			return $destination;
		}
	}
	
	return $redirect; // None found, so do the default redirect.
}```

**Comment by TonyRidgway** [comment]
Hand slap to the forehead moment when I saw how easy this was - Thank you.

**Comment by jeherve** [comment]
This is being worked on in #13745
