### ISSUE TITLE
Flickr Widget: display images on a grid

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#7089]
> I expected the Flickr widget thumbnails to be in a grid but they are showing one per line:

![screen shot 2017-04-28 at 15 41 30](https://cloud.githubusercontent.com/assets/426388/25531186/2cb21c4e-2c29-11e7-9669-420e3c38d0c1.png)

**Comment by dmtrmrv** [comment]
Came here looking if there were open issues on this widget as at the moment it wraps all images with a table ... And then does that again :) Also the double `<br><br>`, making it a bit perky to style it :) See the screenshot: https://monosnap.com/file/UKXEpnYADxE40dewxf0WMJia4W5Dqo

**Comment by daniellecrobinson** [comment]
Came here also looking to fix this, the default one per line looks sad on my site - thanks @dmtrmrv
