### ISSUE TITLE
Send email to site owner when the site gets a new email subscriber

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#709]
It'd be useful to include an option to send an email to the site owner whenever the site gets a new email subscriber using the subscription widget. 

Originally requested here:
http://wordpress.org/support/topic/notifications-on-self-hosted-1?replies=1

Ported from https://plugins.trac.wordpress.org/ticket/1849

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/notifications-subscribers?replies=1&view=all

**Comment by samhotchkiss** [comment]
This isn't something that we'll handle within Jetpack, but may be handled from the wordpress.com side.

**Comment by richardmtl** [comment]
This was requested in 2371264-t

**Comment by richardmtl** [comment]
Requested in 2482921-t

**Comment by annezazuu** [comment]
requested in 2485678-t

**Comment by richardmtl** [comment]
requested in 2490644-t

**Comment by annezazuu** [comment]
requested in 2489646-t

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/email-notifications-of-new-subscribers?replies=1&view=all

**Comment by rachelsquirrel** [comment]
Another request: #2634784-t

**Comment by seejacobscott** [comment]
Requested in 2648893-t

**Comment by RCowles** [comment]
Requested in 2793085-t

**Comment by davoraltman** [comment]
2931390-t

**Comment by csonnek** [comment]
3038881-t

**Comment by aheckler** [comment]
3053538-t

**Comment by chaselivingston** [comment]
Requested in 3271191-t.

**Comment by RCowles** [comment]
Requested in 3330053-t.

**Comment by cecoates** [comment]
612459-zen

**Comment by htdat** [comment]
One more: 
666552-zen

**Comment by chaselivingston** [comment]
Also requested in 700082-zen.

**Comment by htdat** [comment]
756067-zen

**Comment by richardmtl** [comment]
833607-zen

**Comment by lamdayap** [comment]
811123-zen

**Comment by donalirl** [comment]
1460177-HC

**Comment by gsmumbo** [comment]
880252-zen

**Comment by csonnek** [comment]
949945-zen

**Comment by csonnek** [comment]
914860-zen

**Comment by htdat** [comment]
> At least it's doable using Calypso.

Yeah, we've just implemented this feature for some days. 

To make it clear, you can toggle on/off this feature under WordPress.com -> Settings -> Discussions -> The `Someone follows my blog` option. 

![screen shot on 2018-04-13 at 09_50_54](https://user-images.githubusercontent.com/10045087/38714632-59cfc5e6-3f01-11e8-911e-c24b24dfe261.png)

---- 

Internal ref: p9o2xV-3Q-p2

**Comment by jeherve** [comment]
The feature is now available, as @htdat mentioned, but the wp-admin setting is not. This needs to be fixed.
https://github.com/Automattic/jetpack/issues/709#issuecomment-47785500

**Comment by htdat** [comment]
1266829-zen

**Comment by richardmtl** [comment]
1874856-zen

**Comment by davoraltman** [comment]
11429511-hc

**Comment by chickenn00dle** [comment]
The option to toggle emails for followers is still not in wp-admin as of JP 7.9-alpha.
