### ISSUE TITLE
General: make sure get_file_data is always unserialized

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#7097]
**The Error:**
Jetpack displays a 500 PHP error (Blank Screen) when you first activate the plugin and click ‘Connect Jetpack’.

**In the Log:**
[Tue Apr 25 17:22:49 2017] [error] [client 208.70.247.145] FastCGI: server stderr: PHP message: PHP Warning: Illegal string offset ‘4.8.2’ in /var/…./wp-content/plugins/jetpack/class.jetpack.php on line 2323, referer: /wp-admin/plugins.php?plugin_status=all&paged=1&s

**The Cause:**
For some reason the variable $file_data_option was not recognized as array when running line 2322. Not sure what happened there but we were able to fix that by adding a conditional check to make sure it only runs when $file_data_option is an array.

Out of curiosity, I tried dump out $file_data_option and realize this variable was an serialized string (!!) instead of an array.

One thing to note is that we did upgrade Jetpack from 3.8.x to 4.x, so there could be some old data that just won’t work under the new version.

Reported here:
https://wordpress.org/support/topic/500-error-illegal-string-offset-4-8-2-in-class-jetpack-php-on-line-2323/

cc @samhotchkiss, who worked on `get_file_data` in the last release in #6637

**Comment by jeherve** [comment]
Bumping the priority on this one since it fatals some sites, and just happened to someone else in #7986

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/jetpack-not-activated-due-to-fatal-error/

**Comment by jeherve** [comment]
cc @zinigor There are some extra details in the thread above:

> the problem occurred on an export and import of data between two different versions of MySql.
>
> old version 5.5.57-38.9
> new version 5.6.36-82.1
>
> Exported entire site via export tool in phpmyadmin. I saved the SQL file on my pc. I imported the sql file on the new database.
> Note: The sql file exceeded 100 Mb and I divided it into various parts, through the “insert” commands already in the file.

**Comment by zinigor** [comment]
Let's see if we have any more reports after #8056 goes out. Please reopen the issue if there are.
