### ISSUE TITLE
VideoPress: stats aren't displaying in Calypso

### ISSUE THREAD

**Issue by mbhthompson** [Automattic/jetpack#7102]
This issue was reported in 3188809-t, and I was able to reproduce on my own site.

Reproduce: Viewed the stats from a day that I posted a video.

Expected: Stats for the video plays in both my self-hosted WP dashboard as well as in Calypso.

Actual: Able to view video stats in my self-hosted WP dashboard, but they don't show up in Calypso.

**Comment by jeherve** [comment]
Since this is an issue with Calypso Stats, I'd recommend opening this issue in the wp-calypso repo:
https://github.com/Automattic/wp-calypso/issues

Related: 
https://github.com/Automattic/wp-calypso/issues/1964
