### ISSUE TITLE
Sharing: Ability for users to define their own email templates

### ISSUE THREAD

**Issue by dartiss** [Automattic/jetpack#7106]
A WordPress VIP client has requested an ability to modify the layout of the sharing email via a simple templating method.

> We’d like to be able to edit a template, that would let us customize how the email looks when the user shares it. Right now, when they share it – it looks very “bloggy” and we’d like to be able to customize it a bit more.

#65279-z

**Comment by jeherve** [comment]
Closing as duplicate of #419
