### ISSUE TITLE
Connection banner and page: add TOS + share detail links

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#7109]
Not sure how I missed this while building them out so many months ago, but we need to add the _terms of service_ and _share details_ links within the connection banner and the connection page (the full connection page).

example of the proper string with links:
![screen-shot-2017-05-02-at-09-19-131](https://cloud.githubusercontent.com/assets/214813/25637509/369f704e-2f53-11e7-87aa-b287a2a827d3.png)
(as displayed on the full-screen connection prompt on the plugins list page. displayed right after the plugin is installed+activated)

current connection banner:
![screen-shot-2017-05-02-at-09-19-341](https://cloud.githubusercontent.com/assets/214813/25637545/56d3c158-2f53-11e7-9fac-2c0ce335a837.png)
(we can place the string below the buttons)

current connection block on the full screen connection page:
<img width="1267" alt="screen shot 2017-05-02 at 4 24 08 pm" src="https://cloud.githubusercontent.com/assets/214813/25637685/d40480c2-2f53-11e7-8155-bf3c0d3a25a1.png">

There are 2 connection blocks on this page. One at the top and one at the bottom. We'll need to add the links to both areas. 

cc @rickybanister

**Comment by ebinnion** [comment]
Do we need to add them there since we display it on WordPress.com?

**Comment by dereksmart** [comment]
This has been done!
