### ISSUE TITLE
Mismatch between Jetpack Sync woocommerce_order_status_changed and wp_insert_post

### ISSUE THREAD

**Issue by nabsul** [Automattic/jetpack#7119]
It appears that when I edit an order (which is a type of post) in WooCommerce, saving the order results in the old values of the order getting sent out to Jetpack Sync. This means that the Jetpack backup is always going to be one snapshot behind.

#### Steps to reproduce the issue

- Create a WooCommerce order
- Set the order (in admin panel) from "processing" to "complete"

#### What I expected

Jetpack should send the following events:
- woocommerce_order_status_changed: "processing", "complete"
- wp_insert_post: { .... post_status":"wc-complete... }

#### What happened instead

Jetpack is sending:
- woocommerce_order_status_changed: "processing", "complete"
- wp_insert_post: { .... post_status":"wc-processing ... }

@lezama @enejb @westi

**Comment by lezama** [comment]
This fixes the problem: https://github.com/Automattic/jetpack/compare/update/sync-expand-insert-post?expand=1

It is a hack, that solution will mix things if the queue doesn't get processed on the same change that fires the `wp_insert_post`

A proper solution is to do a similar treatment as we do for "published_post"
https://github.com/Automattic/jetpack/blob/a8c8e34007bd74a1da3e2feb93ac1ffa6f5f60a7/sync/class.jetpack-sync-module-posts.php#L39

**Comment by nabsul** [comment]
Great! When you have a PR that's ready for review I'd be happy to test it.

**Comment by zinigor** [comment]
@bisko since you have worked with Sync correctness, you probably know if this is still an issue. Can we close this for now and reopen if it's still a problem?
