### ISSUE TITLE
Change the colour of the like button iframe.

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#713]
Sometimes the blogs colour scheme doesn't work well with the colours in the like button. 
For example http://meetcutemonologues.com/2014/04/23/test-post/
'Be the first to like this.' is hard to read. 

It would be great if we could overwrite this via filters or some other way. 

Related enhancment
https://github.com/Automattic/jetpack/issues/603

**Comment by dereksmart** [comment]
Closing, please reopen if this ever gets more requests.
