### ISSUE TITLE
General: merge Jumpstart and default activated modules

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#7133]
Now that we've updated Jetpack's connection flow and admin interface, Jetpack's module status right after the connection can be a bit confusing imo. Consider the following:

1. Install and activate the Jetpack plugin on your site.
2. Go to the Jetpack menu, and click on the Connect button.
3. Go through the connection flow.
4. Once you've connected, you're redirected back to your site's Jetpack dashboard. 
5. On the updated Jetpack dashboard screen, you see a confirmation that your site is connected, and an invitation to run Jumpstart:

![screen shot 2017-05-05 at 18 21 13](https://cloud.githubusercontent.com/assets/426388/25754478/a4716eb0-31bf-11e7-87d7-d8779f366184.png)

Hm, I'm not quite sure what I want to use yet, and when I googled around for Jetpack reviews, I read that it was a heavy plugin. I'll click "Skip this step" for now, review the features myself, and decide what I want to enable.

6. I'm redirected to the Jetpack dashboard, and it turns out that although I opted out of Jetpack choosing what to enable for me, it still activated 21 features for me!

This can be very confusing, and I would expect Jetpack not to enable anything for me when I refuse its recommendations.

Should we not enable any modules when someone skips the recommended features (Jumpstart)?

**Comment by dereksmart** [comment]
Accidental close of this issue

**Comment by jeherve** [comment]
This isn't really relevant anymore with the new UI. Closing.
