### ISSUE TITLE
Sync: PHP notice on module-posts

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#7156]
```
PHP Notice: Trying to get property of non-object in /../wp-content/plugins/jetpack/sync/class.jetpack-sync-module-posts.php on line 126
```

Reported here:
https://wordpress.org/support/topic/property-of-non-object-in-class-jetpack-sync-module-posts-php/

**Comment by mataiand** [comment]
I'm getting the same error, however on different line: 
PHP Notice:  Trying to get property of non-object in .../wp-content/plugins/jetpack/sync/class.jetpack-sync-module-posts.php on line 204

**Comment by visser** [comment]
Getting this on line 204 also, I've de-activated Jetpack in the interim as it's flooding the debug.log on one of my staging sites, running latest release of Jetpack and WP
