### ISSUE TITLE
Minimum version: Readme says 4.6, but activating plugin says 4.7

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#7158]
First reported in 3204230-t

The current 4.9 readme says:

> Stable tag: 4.9
Requires at least: 4.6
Tested up to: 4.7

However, this screenshot is from a network running 4.6.4:

![00002062](https://cloud.githubusercontent.com/assets/3676359/25870721/2175b4dc-34d3-11e7-8f90-563863afef4c.png)

So, which is it? 4.6 or 4.7?

**Comment by jeherve** [comment]
Good call. It's 4.7. We'll fix that in Jetpack 5.0 (c1c6db85fd66b8d7bc705ca8eea051f763066943).
