### ISSUE TITLE
No refresh option for broken sitemaps

### ISSUE THREAD

**Issue by Ruppsel** [Automattic/jetpack#7161]
Since pictures had unescaped characters in their name, an image sitemap was generated which wasn't parseable by google (XML error, not well formed).

#### Steps to reproduce the issue

Have an imagetitle e.g. with an & in the title, resulting in the xml error described above. Once created, the sitemap does not get rewritten, even after changing the title. Deactivating/reactivating the sitemap feature does not work.

#### What I expected

Best case: the sitemap gets updated after i fix the error-creating image title.
Second best: the sitemap gets updated after i deactivate/activate the sitemap module.

#### What happened instead

The erroneous title keeps appearing in the sitemap and mages it unparseable by google.

**Comment by jeherve** [comment]
Related: #6822

**Comment by jeherve** [comment]
Closing as duplicate of #7204
