### ISSUE TITLE
Use of undefined constant HOUR_IN_MINUTES

### ISSUE THREAD

**Issue by dmtrmrv** [Automattic/jetpack#7162]
This error appears if you add an Upcoming Events widget to the sidebar:

`Notice: Use of undefined constant HOUR_IN_MINUTES - assumed 'HOUR_IN_MINUTES' in /srv/www/counter/htdocs/wp-content/plugins/jetpack/_inc/lib/icalendar-reader.php on line 99`

After searching through all files it looks like this is indeed the only occurrence of this constant.

**Comment by jeherve** [comment]
Thanks for the warning. We'll get this fixed in the next release with #7163

Until then, you can solve the issue on your site by adding the following to your site's `wp-config.php` file:

```php
define( 'HOUR_IN_MINUTES', 3600 );
```
