### ISSUE TITLE
Fatal Error trying to connect

### ISSUE THREAD

**Issue by withinboredom** [Automattic/jetpack#7164]
#### Steps to reproduce the issue
Not sure, but a simple fix

#### What I expected
Connection flow

#### What happened instead
Fatal error:

Incorrect usage of `$this`: https://github.com/Automattic/jetpack/blob/master/class.jetpack.php#L4140

This function is called statically as well as an instance method across the codebase, but mostly as an instance method.

```
Fatal error: Uncaught Error: Using $this when not in object context in /var/www/html/wp-content/plugins/jetpack/class.jetpack.php:4140 Stack trace: #0 /var/www/html/wp-content/plugins/clef-wordpress/includes/class.clef-wind-down.php(184): Jetpack::build_connect_url(true, true, 'wpclef') #1 /var/www/html/wp-includes/class-wp-hook.php(298): ClefWindDown::handle_requests('') #2 /var/www/html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #3 /var/www/html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /var/www/html/wp-settings.php(449): do_action('init') #5 /var/www/html/wp-config.php(95): require_once('/var/www/html/w...') #6 /var/www/html/wp-load.php(37): require_once('/var/www/html/w...') #7 /var/www/html/wp-admin/admin.php(31): require_once('/var/www/html/w...') #8 {main} thrown in /var/www/html/wp-content/plugins/jetpack/class.jetpack.php on line 4140
```

**Comment by dereksmart** [comment]
@withinboredom I'm not seeing where it's called statically in our codebase, but if it is, it should be changed. I see your logs are showing being called statically from clef `#0 /var/www/html/wp-content/plugins/clef-wordpress/includes/class.clef-wind-down.php(184): Jetpack::build_connect_url(true, true, 'wpclef')`

**Comment by withinboredom** [comment]
Ah, there's another function in a different class that's calling it statically ... my bad, closing this :)
