### ISSUE TITLE
Connection banner: conflict with Akismet connection banner

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#7173]
#### Steps to reproduce the issue

1. Install the Akismet plugin on your site. Do not configure it. You'll see this banner in the Plugins page:

![screen shot 2017-05-11 at 22 15 54](https://cloud.githubusercontent.com/assets/426388/25970004/6b83e344-3697-11e7-8414-1ca5bec6520b.png)

2. Install and activate the Jetpack plugin.
3. Some of the text from the Akismet banner appears in Jetpack's full connection banner.

![screen shot 2017-05-11 at 22 13 39](https://cloud.githubusercontent.com/assets/426388/25969994/633512d0-3697-11e7-820f-1f008748c733.png)

**Comment by ashleighaxios** [comment]
Good catch. Seems like it's just a z-index issue in need of a code adjustment. The Akismet banner text should appear below the activation overlay, background and all.

**Comment by jeffgolenski** [comment]
on it!
