### ISSUE TITLE
Module Settings: Add "Enable" to VideoPress module toggle

### ISSUE THREAD

**Issue by sirreal** [Automattic/jetpack#7176]
Update the VideoPress module toggle to read:

> Enable fast, ad-free video hosting

This will match the soon-to-be deployed toggle in Calypso.

Calypso:

![enable](https://cloud.githubusercontent.com/assets/841763/25957253/297fdd6e-366e-11e7-9e92-5d32a8503c79.png)

Jetpack:

![jp](https://cloud.githubusercontent.com/assets/841763/25987840/fa518dca-36f5-11e7-9cf6-e0c7438d68aa.png)

From [this and following comments](https://github.com/Automattic/wp-calypso/pull/13857#issuecomment-300758619).

cc @rickybanister

**Comment by jeherve** [comment]
What should happen when the module is active? Should the word "Enable" disappear?

**Comment by sirreal** [comment]
> What should happen when the module is active? Should the word "Enable" disappear?

No, "Enable fast, ad-free video hosting" is the new label for the toggle. It's really not any different from the other toggles. "Display images and galleries in ..." also has a verb up front, but we understand that the toggle `off` means "_Don't_ display..." and the toggle on means "_Do_ display...".

It would be good for @rickybanister to chime in too

**Comment by rickybanister** [comment]
Yes, exactly—the toggle is the indicator of the status. It dictates whether the label next to it is true or false. 

Like in this situation:

![image](https://cloud.githubusercontent.com/assets/437258/26063248/7173a430-395b-11e7-901c-6a9829178255.png)

All the labels are actions that will be performed when the toggle is on. When the toggle is off those actions are ignored.

**Comment by jeherve** [comment]
This has now been implemented:

![image](https://user-images.githubusercontent.com/426388/76105735-d5ed6880-5fd5-11ea-9eb5-29e8a007652a.png)
