### ISSUE TITLE
Subscriptions: excerpt emails include 2 read more links

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#7178]
#### Steps to reproduce the issue

1. Enable the Subscriptions module on your site.
2. Go to Settings > Reading, and switch your feed settings to Summary, to send only an excerpt of your posts to your subscribers.
3. Enable a theme like [Button 2](https://wordpress.com/theme/button-2), that filters `excerpt_more` to add extra text. See the `button_2_auto_excerpt_more ` function here:
https://wpcom-themes.svn.automattic.com/button-2/inc/template-tags.php
4. Subscribe to that site.
5. Publish a post.
6. Notice the extra read more link (added by the theme) is also added to the email body, creating a double read more link.

![screen shot 2017-05-12 at 15 13 23](https://cloud.githubusercontent.com/assets/426388/25999566/f28601ae-3725-11e7-87bc-384164e00bbb.png)

Reported in 3196378-t

**Comment by andrewarthurdawson** [comment]
I definitely am getting this error every day now since Jetpack 4.9. I am hoping someone from Jetpack will fix this for the next release of Jetpack as it really makes my email subscription look sloppy. :(

**Comment by andrewarthurdawson** [comment]
Is anyone going to get assigned this bug? :(

**Comment by kraftbj** [comment]
Noting that this bug does not occur on WP.com, so it is unique to Jetpack.

**Comment by andrewarthurdawson** [comment]
I'm unsure what you mean?

**Comment by jeherve** [comment]
@andrewarthurdawson It means the problem only happens for subscription emails sent from Jetpack sites. WordPress.com sites do not experience this issue.

**Comment by andrewarthurdawson** [comment]
Isn't my site a Wordpress site too? I guess I don't understand what you mean by a Jetpack site and a WP site? Since I am using WP and publish through WP? Please elaborate ok?

**Comment by jeherve** [comment]
@andrewarthurdawson Your site uses the self-hosted version of WordPress, and is linked to the WordPress.com service thanks to the Jetpack plugin. Sites such as yours are affected by the bug reported here.

Sites hosted on WordPress.com are not affected by the issue.

You can learn more about the differences between WordPress.com and the self-hosted version of WordPress here:
https://en.support.wordpress.com/com-vs-org/

**Comment by andrewarthurdawson** [comment]
This issue has now been opened a month and no one has been assigned? Is this something that's just going to remain a problem now with no end? :(

**Comment by ebinnion** [comment]
Should be fixed in r158391-wpcom.
