### ISSUE TITLE
Contact form ham triggers email with raw HTML

### ISSUE THREAD

**Issue by iandunn** [Automattic/jetpack#7179]
@dd32 noticed that contact form submission will show the raw HTML if they get stuck in the Spam queue, and then are later approved and sent.

I don't have time to verify this right now, but I'm pretty sure that I introduced the problem in #6658, and missed a chance to fix it in #7018. I think that `grunion_ajax_spam()` needs to be updated to wrap `wp_mail()` calls in the same 2 filters that are set in `Grunion_Contact_Form::process_submission()`.

#### Steps to reproduce the issue

I haven't verified these yet, but it should be:

1) Submit a contact form with content that will cause it to get stuck in the spam filter
2) Approve the comment so that the email is sent
3) Open the email

#### What I expected

1. The `content-type` header should be `text/html`
1. The message body should contain rendered HTML

#### What happened instead

I haven't verified these yet, but I'm guessing that:

1. The `content-type` header is `text/plain`
1. The message body should contain HTML tags displayed as text symbols

**Comment by dd32** [comment]
To confirm, the email in which the raw HTML is displayed indeed carries a `Content-Type: text/plain; charset=UTF-8` header.

Here's a quick snapshot of the relevant headers / body:
<img width="933" alt="screen shot 2017-05-13 at 9 54 45 am" src="https://cloud.githubusercontent.com/assets/767313/26020503/7f42c658-37c2-11e7-9c72-c13b9b4f3cbe.png">
