### ISSUE TITLE
New Feature: Add text box controls for WordPress generic emails

### ISSUE THREAD

**Issue by marktimemedia** [Automattic/jetpack#7186]
In reference to this thread: https://twitter.com/jetpack/status/864210079649865728

Email is a huge pain point when it comes to managing sites, and there are many current solutions that make it easier when dealing with complex sites (ecommerce, membership, etc). However, nothing has really been done about basic core WordPress user notices that are sent via email.

WordPress automatically sends several emails (new user accounts, password changes/updates, etc) to users signing up for an account, and the content of these emails are not currently accessible by a typical site admin. It also uses a **default "from" email and name** that may not be inline with the website brand.

Currently there are ways to programmatically update some of these things (via filters, etc) but these are obviously only accessible to developers, and must be updated by developers if an admin wants any text changes.

Jetpack added a simple interface to manage the text/content of blog and comment subscription emails which works well. I think it would make sense to extend this to include a similar interface to manage the body text, "from" email and name, and maybe even add a site logo to these generic WordPress emails that are currently obfuscated from the site admin. That way, all emails generated by WordPress core (and who they appear to be from) have a simple place to be edited.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
