### ISSUE TITLE
Remove outputting 'meta name="title"' since <title> is standardized.

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/jetpack#7190]
#### Steps to reproduce the issue

On any WPCOM site, Jetpack seems to be outputting site titles like`<meta name="title" content="Test Page | Test Site on WordPress.com" />` (slightly different on AT sites). The title format also tends not to match the user's intended set title in Settings > General.

Since all major search engines and other reputable social sites and tools use the standardized `<title>` tag (and we output correctly there), we should omit this.

[It's also not listed on W3C](https://www.w3schools.com/tags/tag_meta.asp), so it doesn't appear to even be valid HTML.

**Comment by jeherve** [comment]
This is handled by the SEO module.

> The title format also tends not to match the user's intended set title in Settings > General.

The title format matches what's set under Settings > Traffic on WordPress.com:
https://wordpress.com/settings/traffic/

cc @vindl: should we ignore and not output that meta title when in the loop here?
https://github.com/Automattic/jetpack/blob/4.9/modules/seo-tools/jetpack-seo.php#L252

**Comment by vindl** [comment]
@jeherve yes, I think we can remove that. I'll spin up a PR for that.
