### ISSUE TITLE
Settings UI: Info popover contents differ from Calypso

### ISSUE THREAD

**Issue by tyxla** [Automattic/jetpack#7195]
As discussed in p1495025546143993-slack-jpop-design, contents of info popovers for settings UI cards differ between Jetpack and Calypso. As @keoshi clarified, these need to be updated accodingly to match Calypso.

For example, see the VideoPress setting info popover:

Calypso:
![](https://cldup.com/4zthFKHjXz.png)

Jetpack:
![](https://cldup.com/YS-srnNz_D.png)

/cc @eliorivero

**Comment by tyxla** [comment]
cc @MichaelArestad @rickybanister for awareness

**Comment by rickybanister** [comment]
The Calypso design is obviously preferred.

**Comment by eliorivero** [comment]
Addressed in https://github.com/Automattic/jetpack/pull/9137 for Jetpack and https://github.com/Automattic/wp-calypso/pull/23612 in Calypso
