### ISSUE TITLE
Jetpack_Sync_Module_Options::get_all_options() sends non-existing options

### ISSUE THREAD

**Issue by nabsul** [Automattic/jetpack#7199]
In the case of the the WordPress option  `woocommerce_force_ssl_checkout`, the `get_all_options()` function will return a value of false even if that option isn't in the database. This is because WordPress's `get_option()` function returns false if the variable doesn't exist.

This results in jetpack sync sending a value of false for woocommerce_force_ssl_checkout even though it's not in the options. This should be fixed so that if the variable doesn't exist, the value is not sent.

@westi

**Comment by westi** [comment]
I think a good plan of attack here is to pass a random string as the default value to the `get_option` calls and if we get that random string back we can reasonably safely assume the option doesn't exist and we can skip the full sync of it.
