### ISSUE TITLE
Add option for "edit post" link to point to the calypso editor

### ISSUE THREAD

**Issue by rralian** [Automattic/jetpack#7207]
For users who prefer the calypso editor it can be jarring to click on the "edit post" link from a site front-end and have it load the wp-admin editor. They should have the ability to point that link to the calypso editor instead, possibly as a jetpack option. /cc @beaulebens

**Comment by beaulebens** [comment]
Yep, this is definitely something we've talked about recently as a broader Jetpack option. Something along the lines of a "WordPress.com mode" for running a site, where you get the masterbar + this option, most likely.

Somewhat related to [this](https://jpopdesignp2.wordpress.com/2017/05/10/deep-integration-with-wordpress-com-for-jetpack-userssites/) conversation. cc @ashleighaxios and @rickybanister

**Comment by jeherve** [comment]
Related: #6848

**Comment by rickybanister** [comment]
Agreed with all of the above. More and more the lack of the action bar for Jetpack sites is a problem.

**Comment by gwwar** [comment]
Is there any work remaining? 

@vindl landed https://github.com/Automattic/jetpack/pull/7702 and
https://github.com/Automattic/jetpack/pull/7732

**Comment by jeherve** [comment]
@gwwar 👍  The only thing left would be #6848.

**Comment by jeherve** [comment]
Fixed in #7702 and #7732
