### ISSUE TITLE
Sharing: Disable WhatsApp button on desktop browsers/devices

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#7220]
The WhatsApp share URL we're using only works if there is a WhatsApp client installed on the device it appears, and so clicking the button from a desktop device simply leads to a blank page. We should probably only show that button if the site is being viewed on a mobile device that can handle the share URL.

**Comment by jeherve** [comment]
This was done on purpose, as per this comment:
https://github.com/Automattic/jetpack/pull/4096#r67836344

Closing as `wontfix`. A work-around would be to hide the button with CSS on your site if needed.
