### ISSUE TITLE
Testimonials: taxonomies support 

### ISSUE THREAD

**Issue by davidsherlock** [Automattic/jetpack#7222]
It would be extremely useful to have support for testimonial taxonomies such as categories and tags to allow more specific filtering on a per post/page basis. For example on my website I have author and customer testimonials, but no way to group them without using custom code.

**Comment by jeherve** [comment]
You can use the `register_taxonomy_for_object_type` function ([reference](https://developer.wordpress.org/reference/functions/register_taxonomy_for_object_type/)) to add support for your own taxonomies, like so:

```php
/**
 * Add Category support to the Testimonial Post Type available in Jetpack.
 *
 * @see https://github.com/Automattic/jetpack/issues/7222
 * @see https://jetpack.com/support/custom-content-types/
 */
function davidsherlock_categories_testimonials_support() {
	register_taxonomy_for_object_type( 'category', 'jetpack-testimonial' );
}
add_action( 'init', 'davidsherlock_categories_testimonials_support' );
```

That should help!

**Comment by davidsherlock** [comment]
Thanks @jeherve, will give this a go! :)

**Comment by davidsherlock** [comment]
Quick question @jeherve, once registered can the taxonomies be used within the shortcodes?

**Comment by jeherve** [comment]
Do you mean displaying those taxonomies within the shortcode? No, that won't automatically happen. You'll need to build your own custom shortcode, based on the default one available here:
https://github.com/Automattic/jetpack/blob/master/modules/custom-post-types/testimonial.php#L531

**Comment by just-us** [comment]
Would you be able to add an option to the array so that it would include it in the prebuilt shortcode section, or would it be better to create the page and add in the options you need? How would you need to save the file in your child theme if you were to do the latter?

**Comment by jeherve** [comment]
> Would you be able to add an option to the array so that it would include it in the prebuilt shortcode section

That is not something we can easily add in, as the format used in each custom taxonomy can be different. That is something you will need to do on your own, by creating your own shortcode. You can add that custom shortcode in your child theme files indeed.

**Comment by jeherve** [comment]
> how to alter the shortcodes to isolate the testimonial categories that this function adds?

I am not sure I understand what you are trying to change. Could you give me more details, or email us via [this contact form](https://jetpack.com/contact-support/?rel=support) to tell us more if this is not related to the addition of custom taxonomies to Testimonials?

Thank you!

**Comment by stripedrhino** [comment]
Hello @jeherve 

Thank you for your quick reply. I would like to create categories of my testimonials so I can embed them onto relevant pages. I have some questions about the above, however:

1. To what file do I add the code you provided for the register_taxonomy_for_object_type function?
2. How do I alter the shortcodes to include the category? I didn’t understand your link above. 

Please let me know if this is more clear. 

Thanks.

**Comment by jeherve** [comment]
> To what file do I add the code you provided for the register_taxonomy_for_object_type function?

You would have to add this to your own plugin, or via a plugin like the one mentioned [here](https://jetpack.com/support/adding-code-snippets/).

> How do I alter the shortcodes to include the category? I didn’t understand your link above.

You can't alter the existing shortcode to do that. You would have to create your own shortcode, based on the Jetpack shortcode but with a different query to get different posts.

Another alternative, if you don't feel comfortable doing this yourself, is to use another plugin that will allow you to build your own query. Here is an example:
https://wordpress.org/plugins/display-posts-shortcode/

**Comment by stripedrhino** [comment]
Noted, thank you.

**Comment by bazeboiee** [comment]
I'm a little nonplussed as to why testimonials doesn't have access to standard taxonomies such as tags and categories. I can't imagine that it would take that much to bake them in as normally seen for other items. As one of the posters commented above, it's nice to be able to have relevant testimonials for certain pages. Or could you add this discussion or the code snippet menationed above to the jetpack testimonials page so that people can easily find this and implement it themselves. It took me a minute to find this page and I can imagine there are a lot of people who want to implement this to their site as well.

**Comment by jeherve** [comment]
@bazeboiee Thanks for the feedback! I've added the code snippet to the support documentation, hopefully that will help others.
