### ISSUE TITLE
Priority Support upgrade banner is broken

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack#7235]
Currently:
The priority support card and its upgrade banner are showing for a test user of mine that is:
1. a 'subscriber' so not an admin
2. is not connected to a WordPress.com account
3. this site has a professional plan and no one should see any upgrade banners at all

<img width="757" alt="screen shot 2017-05-25 at 5 58 30 pm" src="https://cloud.githubusercontent.com/assets/437258/26472588/d2a2bebe-4174-11e7-9bd7-56bb774aea8d.png">

I expected not to see much if anything on the Jetpack dashboard for a subscriber. Certainly not a prompt to buy a plan.

cc @ashleighaxios and @MichaelArestad as this relates to the 'warm welcome' stuff. The non-owner and non-admin experience is basically not-at-all considered.

**Comment by rachelmcr** [comment]
I ran into this while testing. I see this upgrade nudge both for a non-admin (contributor) user that is not connect to a WordPress.com account and a non-admin (author) user that _is_ connected to a WordPress.com account. However, the site has a Jetpack Premium plan and shouldn't get this nudge to upgrade.

**Comment by rickybanister** [comment]
@dereksmart something we could look into for 5.4?

**Comment by dereksmart** [comment]
@rickybanister that's an easy fix.  Opened a PR #7721
