### ISSUE TITLE
Settings UI: add more prominent link to Advanced Settings, i.e. full module list

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#7239]
Long-time Jetpack users and folks trying out Jetpack after reading tutorials online may expect to find a page where they can see which modules are enabled, and which one are not. That page is also useful when bulk-activating or deactivating modules, as per #4534.

Right now, the only way to get to such a page is through a link at the bottom of the Jetpack Debug page(see #6770). This link is too hidden to be useful. I personally don't even point site owners to that link when they need to access the full module list, as it's easier to give them the link than to help them navigate through 2 pages to get to the link.

I believe we should be able to add a more prominent link to the existing full module list. We could add something like a cog icon linking to "advanced settings", in the top bar on Jetpack > Settings next to the Search icon. It could also be next to the Settings link in the header menu. I'm no designer though :)

I've received good feedback about [this little plugin](https://github.com/jeherve/advanced-settings-for-jetpack) I created, although it's obviously not pretty. :)

See the threads here for more context:
https://github.com/Automattic/jetpack/issues/6788#issuecomment-304275238

**Comment by jeherve** [comment]
Also suggested here:
https://twitter.com/backtofrontco/status/932581232113729539

**Comment by Back2Front** [comment]
Thanks for logging this request here. 
There are so many useful functions available to users that are being hidden by the Jetpack > Settings screen, and its so much faster to enable / disable them from wp-admin/admin.php?page=jetpack_modules.

Eg. Contact Form, Monitor, Manage, Custom CSS.

Even when they are accessible through the settings tabs, I always have to click atleast a few times to find where they are.

Apart from wanting to turn them off/on, I wouldn't even know that a really useful module like 'Monitor' was there from the settings tabs. Then if the site never went offline, the site owner wouldn't know that the module was there. 

Or they might not have got the memo that they could update software using Manage, or other useful modules, but if they see it in the list at wp-admin/admin.php?page=jetpack_modules they could click and find out.

IMO the settings screen is so over-simplified its selling a really great plugin short.

**Comment by jeherve** [comment]
Also mentioned here:
https://www.lireo.com/how-to-view-jetpacks-modules-in-one-list/

**Comment by MichaelArestad** [comment]
This is already done: 
![image](https://user-images.githubusercontent.com/1123119/60372658-2f66b780-99b2-11e9-863b-fa474a654222.png)
