### ISSUE TITLE
Admin Page: add Widgets card.

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#7242]
Since a lot of site owners expect to find the Widgets setting in the new Jetpack Settings page, maybe we should consider adding a new card under Jetpack > Settings?

Related: https://github.com/Automattic/jetpack/issues/6788#issuecomment-304275503

**Comment by MichaelArestad** [comment]
@jeherve Which widgets setting are you referring to? Also, is it for activation, deactivation, both?

**Comment by zinigor** [comment]
@MichaelArestad judging by the context I'd say that it's about the extra widgets module enable card. Since we have Widgets Visibility in that list as well, we may want to enable WV together with widgets.

**Comment by dereksmart** [comment]
We've added the ability for this card to surface via `search`, where you can enable from there.
