### ISSUE TITLE
Sync: Fatal Error -- Serialization of Closure is not allowed

### ISSUE THREAD

**Issue by codercurious** [Automattic/jetpack#7252]
```
Fatal error: Uncaught exception 'Exception' with message 'Serialization of
'Closure' is not allowed' in wp-content/plugins/jetpack/sync/class.jetpack-sync-queue.php:53
Stack trace: #0`
`wp-content/plugins/jetpack/sync/class.jetpack-sync-queue.php(53):
serialize(Array) #1`
`wp-content/plugins/jetpack/sync/class.jetpack-sync-listener.php(218):
Jetpack_Sync_Queue->add(Array) #2`
`wp-content/plugins/jetpack/sync/class.jetpack-sync-listener.php(116):
Jetpack_Sync_Listener->enqueue_action('jetpack_sync_ca...', Array,
Object(Jetpack_Sync_Queue)) #3 [internal function]:
Jetpack_Sync_Listener->action_handler('post_types', Array) #4`
`wp-includes/class-wp-hook.php(298):
call_user_func_array(Array, Array) #5`
`wp-includes/class-wp-hook.php(323):
WP_Hook->apply_filters('', Array) #6`
`wp-includes/plugin.php(453): WP_Ho in
wp-content/plugins/jetpack/sync/class.jetpack-sync-queue.php
on line 53
```

Checking `class.jetpack-sync-queue.php` shows error at this line:

```
$rows_added = $wpdb->query( $wpdb->prepare(
'INSERT INTO $wpdb->options (option_name,
option_value, autoload) VALUES (%s, %s,%s)',
$this->get_next_data_row_option_name(),
serialize( $item ),
'no'
) );
```

Reported in 3231883-t

**Comment by enejb** [comment]
Any idea how I can replicate this? Googleing `WP_Ho` doesn't return meaningful php results and from the plugin list I am not able to find the plugin that might be adding that class name.

**Comment by jeherve** [comment]
@enejb It most likely meant `WP_Hook` but got cut off.

**Comment by enejb** [comment]
@jeherve and @codestor4 Any ideas how to replicate this is this? is it still an issue? 
Feel free to reopen this if it has not been addressed.

**Comment by danjjohnson** [comment]
Reopening this as there are several people still reporting this error here:
https://wordpress.org/support/topic/fatal-error-uncaught-exception-serialization-of-closure-is-not-allowed/

Unfortunately, we still don't know how to replicate it, and it only happens intermittently.

**Comment by mdbitz** [comment]
Initial guess is that we are dealing with a plugin/theme conflict In that the plugin/theme is using an anonymous function within a hook added to the callables.

https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/packages/sync/src/class-defaults.php#L278

To resolve 

1) we can wrap the serialize to catch this exception - the caveat being we'll not have the data transmitted to WP.com 
2) we can utilize a serializable library to allow for serializing of closures.
  https://github.com/opis/closure
  https://github.com/jeremeamia/super_closure
