### ISSUE TITLE
Comments: Add an option for viewers to sort comments

### ISSUE THREAD

**Issue by seejacobscott** [Automattic/jetpack#7262]
It could be useful for some users with very active comments sections on their blogs for their viewers to be able to sort comments from newest to oldest, as well as the standard oldest to newest. 

This way users revisiting a post to read the discussion don't necessarily have to scroll through the full site. 

I'm not sure how this would work with nested comments, either a full thread would show sorted by the most recent comment, or it would be placed chronologically by the age of the parent comment. 

Definitely something to think about, but seems like it would be a useful option for some of our readers with more discussion heavy sites. 

requested in 3235567-t

**Comment by kraftbj** [comment]
As I understand the feature request, that is within the theme's domain to control, e.g. https://github.com/WordPress/WordPress/blob/master/wp-content/themes/twentyseventeen/comments.php#L56 for Twenty Seventeen.

`wp_list_comments` can take args of `reverse_top_level` and `reverse_children` to get the effect sought ( https://developer.wordpress.org/reference/functions/wp_list_comments/ ) and can be filtered (untested):

```add_filter( 'wp_list_comments_args', 'bk_reverse_top_level' );
function bk_reverse_top_level( $args ) {
$args['reverse_top_level'] = true;
return $args;
}
```

I'm going to close this, but please reopen if I misunderstood the request.
