### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Skyepose** [Automattic/jetpack#7264]
Hello, when I try to active recommended features, this error shows:
**Recommended features failed to activate. SyntaxError (DOM Exception 12): The string did not match the expected pattern.**

**Comment by jeherve** [comment]
Could you try the following:

<ol>
	<li>Open the dashboard page.</li>
	<li><a href="https://codex.wordpress.org/Using_Your_Browser_to_Diagnose_JavaScript_Errors#Step_3:_Diagnosis">Open your browser console</a></li>
	<li>Click on the Network tab</li>
	<li>Refresh the page.</li>
	<li>Go to the Jetpack Dashboard and try to activate the recommended features.</li>
	<li>If you see any lines in red inside the browser console, click on them. A new panel should appear on the right.</li>
	<li>Click on the "Response" tab in that new panel.</li>
	<li>Copy the message displayed there.</li>
	<li>Paste it here.</li>
	<li>If no red lines appeared in the browser console, click on the "Console" tab of the browser console.</li>
	<li>Copy any errors displayed there, and paste them here.</li>
</ol>

Could you also let me know what other plugins are currently active on your site?

Thanks!

**Comment by Skyepose** [comment]
It looks that I found the problem, all things are failed to load resource.

12:41:46.697 /wp-json/jetpack/v4/connection/url?_cacheBuster=1496140906466 Failed to load resource: the server responded with a status of 404 ()
12:41:46.698 /wp-json/jetpack/v4/plugins?_cacheBuster=1496140906473 Failed to load resource: the server responded with a status of 404 ()
12:41:46.699 /wp-json/jetpack/v4/site?_cacheBuster=1496140906474 Failed to load resource: the server responded with a status of 404 ()
12:41:46.699 /wp-json/jetpack/v4/module/stats/data?range=day&_cacheBuster=1496140906478 Failed to load resource: the server responded with a status of 404 ()
12:41:46.699 /wp-json/jetpack/v4/module/protect/data?_cacheBuster=1496140906492 Failed to load resource: the server responded with a status of 404 ()
12:41:46.699 /wp-json/jetpack/v4/module/akismet/key/check?_cacheBuster=1496140906499 Failed to load resource: the server responded with a status of 404 ()
12:41:46.699 /wp-json/jetpack/v4/module/akismet/data?_cacheBuster=1496140906503 Failed to load resource: the server responded with a status of 404 ()
12:41:46.699 /wp-json/jetpack/v4/updates/plugins?_cacheBuster=1496140906505 Failed to load resource: the server responded with a status of 404 ()
12:41:46.700 /wp-json/jetpack/v4/connection/data?_cacheBuster=1496140906511 Failed to load resource: the server responded with a status of 404 ()
12:41:48.876 /wp-json/jetpack/v4/jumpstart Failed to load resource: the server responded with a status of 404 ()
12:41:49.757 /wp-json/jetpack/v4/jumpstart Failed to load resource: the server responded with a status of 404 ()
12:41:50.626 /wp-json/jetpack/v4/jumpstart Failed to load resource: the server responded with a status of 404 ()
12:43:00.810 /wp-json/jetpack/v4/jumpstart Failed to load resource: the server responded with a status of 404 ()
12:43:01.584 /wp-json/jetpack/v4/jumpstart Failed to load resource: the server responded with a status of 404 ()
12:43:02.272 /wp-json/jetpack/v4/jumpstart Failed to load resource: the server responded with a status of 404 ()
12:43:02.948 /wp-json/jetpack/v4/jumpstart Failed to load resource: the server responded with a status of 404 ()
12:43:05.950 /wp-json/jetpack/v4/jumpstart Failed to load resource: the server responded with a status of 404 ()

**Comment by jeherve** [comment]
Are you able to access the WP REST API on your site?

`https://yoursite.com/wp-json/`

**Comment by Skyepose** [comment]
Finally I found the solution, add these to wp-cofig file and reconnect jetpack. It's a old problem because of SSL certification. I found jetpack can not recognize the local SSL, I hope you can add no-SSL option for blogs without SSL.

```
define('FORCE_SSL_ADMIN', false);
define( 'JETPACK_CLIENT__HTTPS', 'NEVER' );
```

**Comment by jeherve** [comment]
I'm glad to hear you could figure it out.

> I hope you can add no-SSL option for blogs without SSL.

Jetpack already supports sites that do not use SSL, but you will indeed experience issues if you use a self-signed SSL certificate. Browsers and services like Jetpack can't trust that certificate and consequently won't work properly.
