### ISSUE TITLE
Stats: Respect the DNT (Do not Track) header

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#727]
The stats module does not currently respect the Do Not Track (DNT) header. It should.

Original trac ticket:
- https://plugins.trac.wordpress.org/ticket/1921

**Comment by bubel** [comment]
#8075 adds a filter for honoring DNT and is ready to go. I think we should expose it as a formal setting in the settings UI, as well, but we can handle that in a follow-up PR.
