### ISSUE TITLE
Subscriber email too big beaucuse of images

### ISSUE THREAD

**Issue by Klooven** [Automattic/jetpack#7273]
Hello.

I run a photo blog, so I post about 30 pictures in a post. I use the blog follow option in Jetpack, so that my users get an email when I publish a new post.

The problem is that **all** of the photos are inserted in the email. And it makes the email too big. The photos are also **oversized** (email gets too wide).

The photos are attached to the blog post using WordPress gallery feature.

Could this be fixed by letting the user limit the amount of pictures in the mail?

**Comment by jeherve** [comment]
> The photos are also oversized (email gets too wide).

Could you forward us some examples via [this contact form](http://jetpack.com/contact-support/) so we can take a closer look, and make sure images never break the layout of the emails?

Thanks!

> Could this be fixed by letting the user limit the amount of pictures in the mail?

You can already customize the content of the subscription emails, like so:

1. If you go to Settings > Reading in your dashboard, you can change your Feed Settings to "Summary". Once you save your changes, all subscription emails will only include an excerpt of your post, with a link to continue reading on the site.
2.  If your Feed settings are set to "Full Post", you can split the content of each one of your blog posts in 2 parts thanks to the More tag (`<!--more-->`). Everything that is above the More tag will appear on your home page and in the subscription emails, followed by a link inviting users to click to continue reading; everything that is below that tag will only appear on the post's page.
You can read more about it here:
http://en.support.wordpress.com/splitting-content/more-tag/

**Comment by Klooven** [comment]
> Could you **forward** us some examples...

How? Didn't find an email adress... (_sorry if I missed something_)

> You can already customize the content of the subscription emails...

I've actually changed my Feed Settings to "Summary", but all the pictures are still being included in the email.

**Comment by jeherve** [comment]
> How? Didn't find an email adress... (sorry if I missed something)

You can use the contact form I linked to above:
http://jetpack.com/contact-support/

> I've actually changed my Feed Settings to "Summary", but all the pictures are still being included in the email.

That shouldn't happen, but if you send us some example via email, we'll be able to take a look. Thanks!

**Comment by Klooven** [comment]
@jeherve Just so you know, I've sent the mail now. I checked the email in my **webmail** instead of **Outlook 2016**, and there the photos weren't too wide.

**Comment by jeherve** [comment]
> I've sent the mail now.

Thank you! I'll close this issue now. We'll take a look at your email and reopen the issue once we can gather more details about the problem

> I checked the email in my webmail instead of Outlook 2016, and there the photos weren't too wide.

That's good to know, thank you!
