### ISSUE TITLE
Contact form notification emails fail on SiteGround sites

### ISSUE THREAD

**Issue by iandunn** [Automattic/jetpack#7276]
Sites hosted on SiteGround no longer receive email notifications for contact form submissions. It may also happen with Flywheel and a few other hosts. Most hosts appear to be unaffected.

This was probably introduced by #6657 (version 4.9). Initially tracked in 385-gh-jpop-issues.

When testing the fix, it'll be important to verify it on a variety of hosts.

#### Steps to reproduce the issue

1. Install/configure Jetpack and WP Mail Log on a SiteGround site
1. Add a contact form to page
1. Submit the form
1. View the corresponding WP Mail Log entry and check the recipient's inbox

#### What I expected

The email should be received, and there shouldn't be any errors in the log.

#### What happened instead

The email is not received, and the log shows an error: `Could not instantiate mail function.`

**Comment by iandunn** [comment]
Hmm, this actually doesn't look like it's a Jetpack bug. It seems like their Exim server is rejecting any message with a display name, even though those are completely valid according to RFC5322.

* https://tools.ietf.org/html/rfc5322#section-3.4 (see the `name-addr` and `display-name` parts)
* https://tools.ietf.org/html/rfc5322#appendix-A.1.1
* https://tools.ietf.org/html/rfc5322#appendix-A.1.2

This mu-plugin is a minimal test case:

```
$result = mail( '"foo@jetpack.com" <foo@jetpack.com>', 'test from sg - php mail() full addy', 'this should work but doesnt' );
var_dump( $result );
die();
```

That would be really unusual, though, and I'd be surprised if we were the first ones to encounter it, so maybe something else is going on?

Either way, at the moment things seem to point to something at the server layer, so I'm going to try and reach out to them and see what they say.

**Comment by iandunn** [comment]
Ah, nevermind, it looks like the `@` character needs to be escaped in the `display-name`, since it's a special character in atoms.

Sending to `"foo\@jetpack.com" <foo@jetpack.com>` works.

I'll send a PR for that tomorrow.

**Comment by seejacobscott** [comment]
Has there been any more forward momentum on this? User reported in 3254177-t, site is hosted on SiteGround.

**Comment by iandunn** [comment]
Not yet, sorry, I've been swamped this week. I won't have any time next week either, but I'm hoping to get this wrapped up the week after that.

If anyone wants to take it over so they can get it done sooner, let me know and I can push the code I already have to a WIP branch.

**Comment by adrearubin** [comment]
Hi, been tracking this on another forum.  We were just upgraded to WP 4.8 by our hosting provider and we're running jetpack plugin v5.  We just started experiencing the same issue.  Our hosting provider is Bluehost, they don't see any issues on their end.  We installed Email-Log plugin which shows the contact forms being submitted.  We also installed WP-Mail-SMTP to see if the issue was with wp_mail() but that sent emails with no problems.  Right now all form submissions are getting logged in the Feedback & in the Email-Log but is no one is receiving them.  Quite a few people have on other forums have said that they have experienced the same issue.

Any help or updates would be great.

Thank you for all your work and effort into getting this resolved.

**Comment by chaselivingston** [comment]
Also reported in 3264915-t.

**Comment by chaselivingston** [comment]
@adrearubin Sorry for the trouble! Can you contact us with more details here? http://jetpack.com/contact-support/

It sounds like there may just be an issue with wp_mail() on your server, so I don't think this is related.

**Comment by csonnek** [comment]
Another reported in 3245022-t (on SiteGround)

**Comment by csonnek** [comment]
Another: 3262015-t (SiteGround)

**Comment by seejacobscott** [comment]
3282597-t

**Comment by madhattermattic** [comment]
Also seeing in 3287037-t (SiteGround)

**Comment by titanzrule32** [comment]
Is there any update to this? If not, we will need to change from Jetpack to a functioning contact form.

**Comment by chaselivingston** [comment]
@titanzrule32 Our developers are working on a fix. You can follow along at #7367 if you'd like!

**Comment by splitinfinities** [comment]
We at Flywheel have this same issue, #7350.

**Comment by chaselivingston** [comment]
@splitinfinities Thanks for the heads up, I'm working to see if we can get this fixed sooner rather than later :)

**Comment by aheckler** [comment]
@iandunn Any progress on this? Just ran across this in another ticket. 619508-zen

**Comment by iandunn** [comment]
@aheckler: I think @dereksmart was going to take it over since I'm doing a Calypso rotation for the next few months.

**Comment by seejacobscott** [comment]
626795-zen

**Comment by annezazu** [comment]
660563-zen (Bluehost - want to confirm it's related[ here](https://github.com/Automattic/jpop-issues/issues/385#issuecomment-326610303)).

**Comment by chaselivingston** [comment]
Sounds like this may have reappeared in 5.7. Could someone look into it again? 

896031-zen

**Comment by georgestephanis** [comment]
@chaselivingston Can you ask the user to install a plugin like https://wordpress.org/plugins/wp-mail-logging/ or similar so we can inspect the emails getting sent out after the fact and attempt to determine why Siteground may be nerfing them, and bring the data to them directly?

**Comment by gsmumbo** [comment]
The user replied in 896031-zen with two logs. One of the failed contact form, one of the successful new user email.

**Comment by danjjohnson** [comment]
Another affected user in 896031-zen

According to Siteground, the issue appears to be that the from address is e.g.`wordpress@www.example.com` (including the `www.` in the email address, resulting in:

> SITEGROUND: AUTHENTICATED Sorry ... The "MAIL FROM" email address _wordpress@www.example.com / www.example.com_ you are using is not hosted on this server. Sending mails from addresses not hosted on our server is not allowed. Please check the "MAIL FROM" settings of your mail client and make sure you set the "MAIL FROM" address to an email account which is hosted on the server.

But it's not possible to set up an email address using `@www.example.com`, only `@example.com`

**Comment by tmmbecker** [comment]
The brilliant @jeherve found a solution: changing the email address used by the mail function:

```
add_filter( 'wp_mail_from', 'kentraynet_wp_mail_from' ); 
function kentraynet_wp_mail_from( $original_email_address ) { 
return 'wordpress@kentraynet.org'; 
}
```
User in 896031-zen was able to get the form to work by adding that code.

**Comment by StefMattana** [comment]
On another note on 896031-zen as the user followed up: looks like the folks at SiteGround worked on that as well and implemented a fix somewhere into their WordPress site. The user has no idea what they did in detail, but they reported the email SiteGround sent to them, in case we want to take a look at it.

**Comment by jeherve** [comment]
No new reports since January. I'll close this one, and we can reopen if this starts happening again.

Worth noting that in any case, the work-around above may help.
