### ISSUE TITLE
Admin Page: do not display links to Calypso's Security page to non-connected users

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#7279]
> Editors are unable to click these links (nothing happens when you click the wp-admin link and we probably should not show the WordPress.com link to a non-connected user), but the links appear nonetheless:

<img width="388" alt="screen-shot-2017-05-31-at-9-41-36-am" src="https://cloud.githubusercontent.com/assets/426388/26655732/53a653a4-465c-11e7-9985-bfa64eb1456f.png">

Reported in p8oabR-3s-p2

Related: #6972

**Comment by zinigor** [comment]
This was fixed in #7720
