### ISSUE TITLE
Admin Page: menu item not selected after jumpstarting

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#7280]
#### Steps to reproduce the issue

1. Start from a site that is not connected to WordPress.com yet.
2. Go to the Jetpack menu, and connect the site to WordPress.com.
3. When you get back to wp-admin after the connection, you should see a card offering you to jumpstart the site.
4. Click to Dismiss the offer.
5. You get redirected to the dashboard, but "At A Glance" is not underlined. The Dashboard / Settings link isn't correct either:
<img width="388" alt="screen-shot-2017-05-31-at-15-40-18" src="https://cloud.githubusercontent.com/assets/426388/26656153/3b7ff2c4-465e-11e7-9afc-4e87762b6683.png">

**Comment by sirreal** [comment]
> Click to Dismiss the offer.

Same behavior if you _do_ click the jumpstart button.

**Comment by sirreal** [comment]
You can reproduce by just entering the Jumpstart route:

`/wp-admin/admin.php?page=jetpack#/jumpstart`

It will be rewritten as `/wp-admin/admin.php?page=jetpack#/dashboard` with the incorrect menus.

**Comment by jeherve** [comment]
Fixed in #7685
