### ISSUE TITLE
The EU cookie law widget is cached by WP Super Cache

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#7285]
The EU cookie law widget sets a cookie to hide it when the user dismisses it. The cookie is set by Javascript code which is not cached by WP Super Cache, but the check on that cookie is in PHP which can be cached. When this happens the widget shows on the next reload because the PHP code hasn't run and checked.

To make matter worse, if a page is not cached, but the visitor has dismissed the widget already on another page, that page will be cached WITHOUT displaying the widget. Future visitors to that page won't see the widget at all.

The check at https://github.com/Automattic/jetpack/blob/master/modules/widgets/eu-cookie-law.php#L249 needs to be moved into [eu-cookie-law.js](https://github.com/Automattic/jetpack/blob/master/modules/widgets/eu-cookie-law/eu-cookie-law.js) instead so that it will run even on cached pages.

**Comment by jeherve** [comment]
Reported here:
https://wordpress.org/support/topic/jetpack-eu-cookie-law-widget-wp-super-cache-problem/

**Comment by popforce** [comment]
This issue still persists without jetpack.
