### ISSUE TITLE
Move Plans link

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#7287]
We should move the plans link from the At a Glance tab bar to the top nav:

![image](https://cloud.githubusercontent.com/assets/1123119/26693244/c34f1eca-46c0-11e7-9ddf-334c98b8cc13.png)

We probably should be a little more semantic with the markup as well, nesting it in a `nav` and using list elements.

This will remove the last blocker for us reclaiming the tab bar for time-specific navigation for At a Glance and stats.

**Comment by MichaelArestad** [comment]
CC @richardmuscat

**Comment by richardmuscat** [comment]
It makes sense as long as we are willing to revert the decision should we see a drop in sales :)

Also, if you're moving it there it seems like a couple of things would make sense:
- call it "My Plan" ? 
- add it to the left-hand nav (the core wp-admin one)

**Comment by MichaelArestad** [comment]
We can definitely revert if we see that.

> call it "My Plan" ?

I'm open to suggestions here. I think @ashleighaxios had another alternative for it.

> add it to the left-hand nav (the core wp-admin one)

Definitely

**Comment by ashleighaxios** [comment]
I also was leaning towards "My Plan." Thanks!

**Comment by jeherve** [comment]
Closing in favor of #6310
