### ISSUE TITLE
PHP Warning thrown in sync/class.jetpack-sync-module-updates.php

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#7297]
In 3240829-t, the user is seeing this PHP warning in her dashboard:

`Warning: Invalid argument supplied for foreach() in /home/insoyum/public_html/wp-content/plugins/jetpack/sync/class.jetpack-sync-module-updates.php on line 131`

The code:

https://github.com/Automattic/jetpack/blob/4.9/sync/class.jetpack-sync-module-updates.php#L131

Maybe we should make sure it's an array first?

**Comment by kraftbj** [comment]
Alternatively, if we want to still expose the problem (if it suggests a theme or another plugin is doing it wrong), we can check for an array and output a more helpful error message.

`Warning:` Your theme appears to be outputting XYZ unexpectedly. Please inform your theme developer xyz....`

to avoid it appearing that Jetpack is the problem.
