### ISSUE TITLE
VideoPress: Loop should not be set to match autoplay

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#7303]
In https://github.com/Automattic/jetpack/blob/master/modules/videopress/shortcode.php#L130 , we set `loop` to true if either the `autoplay` or `loop` setting is true. In cases where the post author wants a video to autoplay, but not loop, we do not allow for that via the shortcode.

We should update this in some way to at least account for a specific `[wpvideo ... loop=false]` should respect that without regard to the autoplay setting.

cc: @dbtlr

**Comment by dbtlr** [comment]
I'm okay with a change like this. Seems like a weird thing to couple together anyway.

**Comment by vparkhere** [comment]
Reported/follow-up in 637954-zen
