### ISSUE TITLE
Change "Photon" in jumpstart

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#7308]
![image](https://user-images.githubusercontent.com/1123119/26840462-748f733e-4aa3-11e7-8394-c4d79b9d0463.png)

We should probably change it to "Speedy images" or "Faster images"

You can find it in the Jumpstart "Learn More" section.

![image](https://user-images.githubusercontent.com/1123119/26840483-8a8a2a8a-4aa3-11e7-8f82-b349888d4e6e.png)

CC @rickybanister and @ashleighaxios

**Comment by rickybanister** [comment]
Yeah, this should align 100% with the way it's referred to in settings.

**Comment by ashleighaxios** [comment]
In settings, it's just "Speed up images and photos" under "Media" with a Learn More link in the info tooltip. I think we can say just a bit more here without going wild. It's worth noting that "Photon" isn't mentioned in settings, though it is the header of the page you land on when you select the Learn More link. 

To better match, how about:

> **Media**
> Put less pressure on your host and deliver images to your readers faster.

or

> **Media**
> Load images to your readers faster while putting less pressure on your host.

Minor note to help us in ordering these things. The images aren't faster, our delivery or loading of them is. It might also make sense to update settings language to "Load images and photos faster"

**Comment by annatly2** [comment]
Hi! I am very new to contributing, but I would like to assist with this edit. Just to make sure I'm following, are you referring to the text under Photon in the jetpack/modules/module-headings.php file?

**Comment by jeherve** [comment]
@annatly2 Ideally we would want to make that change everywhere in the interface, to update all mentions of Photon at once.

**Comment by annatly2** [comment]
Thanks @jeherve ! That makes more sense.
So the request is to change the information tied to "Photon" to
"Media" and include the text that @ashleighaxios suggested?

**Comment by jeherve** [comment]
In one place, yes, but I suspect that in other places of the UI, like in `wp-admin/admin.php?page=jetpack_modules`, we'll need to come up with a new name for Photon.

@ashleighaxios Do you have any suggestions here?

Also cc'ing @tmmbecker since we discussed about this a little while ago in #8370

**Comment by rickybanister** [comment]
We've most recently been much more explicit in our language around this feature:

![image](https://user-images.githubusercontent.com/437258/35758654-1e62a662-0843-11e8-93e1-3e16a7e7de5c.png)

We definitely want to move away from 'branding' individual features and be more descriptive about their purpose. In this case we come right out and say 'speed up your site by serving images from our servers'. 

I think 'serve images from our servers' would work in the module list as the feature's title.

**Comment by tmmbecker** [comment]
That's a lot of serving in this short phrase - it reads a bit awkwardly. Can we use something as an alternative to either of these? Maybe "deliver" instead of "serve"?

**Comment by eliorivero** [comment]
Closing since wording is very different now

<img width="457" alt="Captura de Pantalla 2019-05-06 a la(s) 16 15 22" src="https://user-images.githubusercontent.com/1041600/57248991-301a4780-701a-11e9-9400-9e930858c49d.png">
