### ISSUE TITLE
Hide Dashboard/Settings navigation during jumpstart

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#7309]
I'm wondering if we should hide the dashboard and settings navigation in the top and side nav until the user completes or skips the jumpstart screen. Alternatively, we could be smart about it and if they head into settings and start turning things on, just silently dismiss the jumpstart view?

![image](https://user-images.githubusercontent.com/1123119/26840628-f6aaed1c-4aa3-11e7-8962-1ee7eee4b4c4.png)

What do you think @jeffgolenski @richardmuscat

**Comment by keoshi** [comment]
Yes, please!

**Comment by dereksmart** [comment]
Bonus points for hiding the wp-admin menu Settings link as well 

<img width="184" alt="screen shot 2017-06-06 at 12 48 06 pm" src="https://user-images.githubusercontent.com/7129409/26841129-8bea9f32-4ab6-11e7-8e1b-627bc9d123b3.png">

**Comment by dereksmart** [comment]
> if they head into settings and start turning things on, just silently dismiss the jumpstart view?

This already happens, if the user touches any settings manually, Jumpstart will no longer be shown.

**Comment by dereksmart** [comment]
This has been fixed! 

![screen shot 2018-02-22 at 10 52 02 pm](https://user-images.githubusercontent.com/7129409/36577100-13826bd4-1823-11e8-9f6b-9c15c5236ed5.png)
