### ISSUE TITLE
Widget visibility: is_active_sidebar always returns true

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#731]
When using "Widget Visibility", I'm having issues with is_active_sidebar always returning true, even if there are no visible widgets in the sidebar for a given page.

In my current theme, this results in blank space down the right hand side of the page.

Steps to reproduce (using Twenty Thirteen theme):
1. Activate Jetpack and the Widget Visibility module
2. Configure a single widget that is visible on only one page
3. Go to any other page

I've had a look at the source, I'm guessing this kind of filtering should be done by the following line in [wp_get_sidebars_widgets](http://codex.wordpress.org/Function_Reference/wp_get_sidebars_widgets):

```php
$sidebars_widgets = apply_filters('sidebars_widgets', $sidebars_widgets);
```

My PHP skills are pretty ordinary and I'm not overly familiar with WordPress, so I didn't dig much beyond finding the sidebars_widgets function in widget-conditions.php which looks like it should be doing this kind of filtering.

Originally reported here:
* https://plugins.trac.wordpress.org/ticket/2063

**Comment by dereksmart** [comment]
Looks like this was fixed?  Tested with 2015 and 2013 and worked as expected.

**Comment by jeherve** [comment]
Yep, it seems fixed on my end as well. w00t! Closing this issue.
