### ISSUE TITLE
Comments: preapproved user's comments not approving

### ISSUE THREAD

**Issue by artpi** [Automattic/jetpack#7310]
#### Steps to reproduce the issue

1. Create a user with contributor role using invites
2. Turn on this option
![zrzut ekranu 2017-06-06 o 16 10 06](https://user-images.githubusercontent.com/3775068/26846360-bad4500c-4af9-11e7-8fdc-5bc0438cebd4.png)
3. Log in as a created user
4. Comment under a post
5. Approve that comment
6. Comment as a new user under a different post

#### What I expected

For comment to skip moderation queue

#### What happened instead

Comment was pending moderation
![zrzut ekranu 2017-06-06 o 16 09 29](https://user-images.githubusercontent.com/3775068/26846429-eeb74370-4af9-11e7-8b4f-49844bc6000c.png)

**Comment by zinigor** [comment]
@aduth  can you please take a look yourself and/or ping someone who has more recent experience working with Comments? Thanks!

**Comment by aduth** [comment]
I won't claim to have any expertise in this area. Is this a Jetpack bug though, or a core one? The "previously approved comment" moderation flow is a core feature.

**Comment by artpi** [comment]
I suspect the problem isnt the flow itself but maybe the fact that user was created via the invite flow?
https://github.com/Automattic/jetpack/pull/7072

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
