### ISSUE TITLE
Create a General tab in settings and more

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#7312]
It looks like we could use a sort of General tab with information specifically about WordPress.com stuff. I am hesitant to call it General in favor of something more specific to WordPress.com, but have not come up with anything better. I am open to ideas.

Things to potentially move into General:
* Connection DashItems
* WordPress.com toolbar
* WordPress.com sign in
* ???

CC @rickybanister

**Comment by rickybanister** [comment]
To create parity with WordPress.com it'd be good to move our disconnect links here as well. Any other links in the interface can direct people to the General settings page to manage their connection. 

It may also be valuable to provide a nice pathway to WordPress.com so they can access their site profile info, and anything else in the wp.com General tab.

**Comment by tyxla** [comment]
Seems like there are cases that can benefit from having a general tab -
see https://github.com/Automattic/wp-calypso/issues/16631

**Comment by rickybanister** [comment]
There is some rethinking of calypso's settings happening right now so we might want to be slightly wary of making changes to jetpack at the moment.

**Comment by MichaelArestad** [comment]
@keoshi This is loosely tied to some of the work you have put together on improving disconnecting/debug flows.

**Comment by tyxla** [comment]
This is still an active issue; Jetpack still lacks a General tab, contrary to WP.com.

**Comment by keoshi** [comment]
This is still an active issue. Jetpack is missing parity with dotcom because it still lacks a General settings tab.

**Comment by MichaelArestad** [comment]
@scottsweb I know during the copy sprint, we expressed the need to better align our tab navigation in settings with Calypso. Is something y'all have already created an issue for or tackled?

The focus of this issue might be too narrow as it is only focused on General versus the holistic view of the tabs.

**Comment by scottsweb** [comment]
@MichaelArestad I didn't discover the lack of tab consistency in the copy sprint but it is pretty obvious now I look over both dashboards. 

Keeping the tabs in sync now is going to be quite difficult. On the Calpyso side some of the settings have been moved into the marketing section causing a bit of a disconnect to what we have in wp-admin. I don't feel we will be able to mirror that hierarchy very easily.

**Comment by eeeeevon13** [comment]
Because of the efforts with Jetpack Cloud and the issue mentioned above by Scott (keeping parity between calyspo) this seems like a non-starter. Going to close it for now.
