### ISSUE TITLE
JPC: Unable to connect with default nginx configuration

### ISSUE THREAD

**Issue by withinboredom** [Automattic/jetpack#7317]
#### Steps to reproduce the issue
Install nginx/php-fpm and map a real domain to your localhost so that you can connect. (I used ngrok.) Configuration for nginx:

```
server {
	listen 80 default_server;

	# Doesn't really matter because default server, but this way email doesn't throw errors
	server_name localhost;

	access_log   /var/log/nginx/access.log;
	error_log    /var/log/nginx/error.log;

	root /var/www/html;
	index index.php;

	if (!-e $request_filename) {
		rewrite /wp-admin$ $scheme://$host$uri/ permanent;
		rewrite ^(/[^/]+)?(/wp-.*) $2 last;
		rewrite ^(/[^/]+)?(/.*\.php) $2 last;
	}

	location / {
		try_files $uri $uri/ /index.php?$args;
	}

	location ~ \.php$ {
		try_files $uri =404;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;

		include /etc/nginx/fastcgi_params;
		fastcgi_pass phpfpm:9000;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}

	location ~* ^.+\.(ogg|ogv|svg|svgz|eot|otf|woff|mp4|ttf|rss|atom|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf)$ {
		access_log off;	log_not_found off; expires max;

		add_header Access-Control-Allow-Origin *;
	}

	# This should match upload_max_filesize in php.ini
	client_max_body_size 100m;
}
```

Try and connect Jetpack, will get a 502 error during connection flow, with this in the nginx logs:

```
upstream sent too big header while reading response header from upstream, client: 172.18.0.1, server: localhost, request: "POST /xmlrpc.php?for=jetpack HTTP/1.1"
```

Jetpack will not be connected. Adding this to the nginx config will fix it:

```
# Copy pasta from slack overflow, so not recommended for production: see https://gist.github.com/magnetikonline/11312172#determine-fastcgi-response-sizes for appropriate configuration
fastcgi_buffers 16 16k;
fastcgi_buffer_size 32k;
```

#### What I expected

A connected Jetpack

#### What happened instead

An unconnected Jetpack

**Comment by kraftbj** [comment]
I think this is the same as https://github.com/Automattic/jetpack/issues/3546 . Marking as a duplicate for now, but please do reopen if that's not accurate.

**Comment by kraftbj** [comment]
FTR, I have this in my Nginx settings:
`	fastcgi_buffer_size 128k;
	fastcgi_buffers 8 256k;
	fastcgi_busy_buffers_size 256k;

	proxy_buffer_size   128k;
	proxy_buffers   8 256k;
	proxy_busy_buffers_size   256k;`

**Comment by zinigor** [comment]
@withinboredom are you sure that Jetpack is not getting successfully connected? Because the duplicate issue as specified by @kraftbj results in a successful connection.

**Comment by withinboredom** [comment]
It used to until something was merged into master between a week and two weeks ago, I can bisect if you'd like. @zinigor

**Comment by zinigor** [comment]
For the record, continuing development in #7322
