### ISSUE TITLE
Post Creation: Add ability to add location to posts

### ISSUE THREAD

**Issue by seejacobscott** [Automattic/jetpack#7321]
In WordPress.com currently there is an option to add your location to a post or page at the time of publishing: 
https://cloudup.com/c-5iOknrL_S

Currently there is no way to add that into posts or pages from Jetpack connected or self-hosted sites. Many users would like to have this feature so they can better map out their locations for their readers. 

Suggested in 3250892-t

**Comment by iamgabrielma** [comment]
https://github.com/Automattic/wp-calypso/issues/4099

**Comment by kraftbj** [comment]
Previously: https://github.com/Automattic/jetpack/issues/857

**Comment by seejacobscott** [comment]
3275180-t

**Comment by rapsli** [comment]
I have read through the various issues, but couldn't figure out whether or not this will be incorporated into Jetpack. So are there any plans for making this part of Jetpack?

**Comment by kraftbj** [comment]
@rapsli This issue is to track that. A long-existing goal is to have parity between WordPress.com and Jetpack, so this is a gap, but uncertain if/when it would be added.
