### ISSUE TITLE
Widgets: Twitter Timeline Widget does not respect height setting

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#733]
The '''height''' setting for the Twitter Timeline widget does not work.

Steps to repro:
1. From Appearance > Widgets, add a Twitter Timeline (Jetpack) to your sidebar
2. Fill out the options, making sure to enter a value for '''height''': https://i.cloudup.com/vnOqDOVzzQ.png
3. Follow the instructions to create a widget at Twitter.com, again making sure to input a value for height: https://i.cloudup.com/PPPDh9aYKk.png
4. Enter the Widget ID, and save your widget
5. View your site: https://i.cloudup.com/B8F9pdoRAP.png

**Expected**: The Twitter Timeline Widget shows, and is constrained to the height set by the user.

**Actual**: The Twitter Timeline Widget shows, but its height is determined by the amount of Tweets, as opposed to the height settings input by the user.

Original trac ticket:
* https://plugins.trac.wordpress.org/ticket/2001

**Comment by samhotchkiss** [comment]
Fixed by #1406
