### ISSUE TITLE
Connection of Jetpack to WordPress.com creates error message

### ISSUE THREAD

**Issue by miso293** [Automattic/jetpack#7331]
#### Steps to reproduce the issue
Hello Jetpack Team,

after upgrading Jetpack to 4.8 and connecting Jetpack to WordPress.com, I get the following error message:

Warning: array_merge() [function.array-merge]: Argument #1 is not an array in /kunden/376952_52064/webseiten/wp-content/plugins/jetpack/modules/sharedaddy/sharing-service.php on line 214 Catchable fatal error: Argument 2 passed to Share_Facebook::__construct() must be an array, null given, called in /kunden/376952_52064/webseiten/wp-content/plugins/jetpack/modules/sharedaddy/sharing-service.php on line 214 and defined in /kunden/376952_52064/webseiten/wp-content/plugins/jetpack/modules/sharedaddy/sharing-sources.php on line 872

i think the problem is, that  get_option( 'sharing-options' ); would return data saved from the "All in One SEO Pack" Plugin.

Your team fixed it for the "Yoast SEO" Plugin here:

https://github.com/Automattic/jetpack/pull/6122 

But with the  "All in One SEO Pack" plugin it stills throws an error.  I think the reason  is that " $this->get_global_options();" on linenumber 183 can return "Null".

I fixed it temporarily when i changed the code of sharing-service.php on linenumber 219 

From this:

if ( isset( $services[$service] ) ) {

To:

if ( isset( $services[$service])  and is_array($global) ) {

Maybe it helps you....

Best Regards 

Michael

**Comment by zinigor** [comment]
Hello Michael!

Thank you for the bug report!

Can you please tell us more about the settings with which you use All in One SEO Pack? I can't seem to reproduce the problem on my test site.

If you still can reproduce it, can you try logging what `$global` happens to be in your case?

**Comment by miso293** [comment]
Hello Igor,

thanks for your Repley to this Bug. Your Fix would help us much.

Tomorrow i send u the Log from $global.

Have a nice Day 

Greetings

**Comment by miso293** [comment]
Hi Igor,

the Problem is that the Problem come to a Project from a Friend. I create a Testproject an try also to reproduce it but without Success. 

If my Friend have the Problem again i will create a new Issue ok ?

Thanks...

**Comment by zinigor** [comment]
I'll close this one for now as not reproducible, but if anyone has a way to reproduce or send more verbose logs, please do so and reopen. Thanks!
