### ISSUE TITLE
Photon: Disabling Jetpack does not disable Photon

### ISSUE THREAD

**Issue by mzakariya** [Automattic/jetpack#7334]
#### Steps to reproduce the issue
- Install Jetpack and enable Photon
- Disable Jetpack

#### What I expected
- Images stop being served via Photon and revert to default

#### What happened instead
- Images continue being served by Photon

Internal: **3254415-t** (includes site, along with link to WordPress.org forum where another user had same issue)

**Comment by kraftbj** [comment]
This sounds like a caching bug outside of Jetpack. If Jetpack is deactivated, none of JP's code is running and so there's no code running to filter the URLs.

If Photon URLs remain, either they were inserted into the post directly as a Photon link or caching is stuck. The OP site has a splash page now. I'm going to close as invalid, but if we have more information, we can reopen.

**Comment by datsabk** [comment]
There is no caching issue. It appears that Jetpack over-rides all the image URLs and does not revert it when disabled. I am facing the same issue on the domain abhishekkothari.in
