### ISSUE TITLE
Sync: send comment author's user_id for comment actions

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#7338]
For comment actions: trashed, deleted, approved, unapproved, content modified, the comment author's id is not being sent properly via sync.

To replicate:
- Have a logged in, non-connected make a comment
- Check that ES gets the incorrect actor ( master user )

**Comment by zinigor** [comment]
Do you think #7310 can be related to this?

**Comment by roccotripaldi** [comment]
@zinigor - On the surface, this seems to be unrelated. As I dig into it, I'll keep #7310 in mind. Thanks for the heads up!

**Comment by roccotripaldi** [comment]
No longer able to replicate. It was perhaps fixed during a clean-up sprint, but I cannot recall.
