### ISSUE TITLE
Invalid argument supplied for foreach() in class.jetpack-sync-module-updates.php

### ISSUE THREAD

**Issue by defries** [Automattic/jetpack#7340]
#### Steps to reproduce the issue
Visible at the bottom of all the Jetpack pages

#### What I expected
No errors

#### What happened instead
The following error displayed: `Warning: Invalid argument supplied for foreach() in /public_html/wp-content/plugins/jetpack/sync/class.jetpack-sync-module-updates.php on line 203`. 

This happens to be a multisite environment and only appears to be showing on the root site where Jetpack is activated in network mode.

I've already tried deleting and reinstalling, but alas.

**Comment by kraftbj** [comment]
Fixed by #7326

**Comment by defries** [comment]
Apologies, I did search, but did not find that issue.
