### ISSUE TITLE
Notice: wpcom-connect notice on plugin page doesn't dismiss for multisite

### ISSUE THREAD

**Issue by lamdayap** [Automattic/jetpack#7343]
In a multisite install the wp-com connect notice doesn't dismiss when clicking the 'x' on the plugin page, it instead redirects you to the Jetpack Dashboard of that site.

![](https://drops.azureedge.net/drops/files/acc_495411/hMwgY6?rscd=inline%3B%20filename%3DScreen%2520Shot%25202017-06-14%2520at%252009.23.39.png)

#### Steps to reproduce the issue

1) Network Activate Jetpack
2) View the plugin page of one of your subsites before connect Jetpack
3) Attempt to dismiss the notice

**Comment by gititon** [comment]
I deactivated Jetpack from my Network Admin Plugins page, and when I reactivated it I saw a Jetpack related message/notice on my Subsite's Plugins page in wp-admin. I clicked the X to the right of the message/notice, and it dismissed/closed/disappeared as expected. 

Please feel free to reopen if anyone is able to reproduce this issue.
