### ISSUE TITLE
Sync: Provide check to ensure theme object present

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#7348]
```
Fatal error: Uncaught Error: Call to a member function get() on boolean in /srv/www/html/wp-content/plugins/jetpack-dev/sync/class.jetpack-sync-module-themes.php:171
Stack trace:
#0 /srv/www/html/wp-includes/class-wp-hook.php(298): Jetpack_Sync_Module_Themes->check_upgrader(Object(Theme_Upgrader), Array)
#1 /srv/www/html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#2 /srv/www/html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /srv/www/html/wp-admin/includes/class-theme-upgrader.php(407): do_action('upgrader_proces...', Object(Theme_Upgrader), Array)
#4 phar:///usr/local/bin/wp/php/WP_CLI/CommandWithUpgrade.php(308): Theme_Upgrader->bulk_upgrade(Array)
#5 phar:///usr/local/bin/wp/php/commands/theme.php(641): WP_CLI\CommandWithUpgrade->update_many(Array, Array)
#6 [internal function]: Theme_Command->update(Array, Array)
#7 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#8 [internal function] in /srv/www/master/html/wp-content/plugins/jetpack-dev/sync/class.jetpack-sync-module-themes.php on line 171
```

Line 171 is expecting the `$upgrader->theme_info` to return a `WP_Theme` object. `false` is a valid return from this function and we should account for that.

**Comment by kraftbj** [comment]
https://github.com/Automattic/jetpack/blob/5.0/sync/class.jetpack-sync-module-themes.php#L171

**Comment by lamdayap** [comment]
same issue with fatal error returned when this user's theme was updated via it's own bespoke method:

https://wordpress.org/support/topic/fatal-error-during-premium-theme-upgrade/

**Comment by demitri2004** [comment]
Hi, did anyone find solution how to resolve this issue?

**Comment by demitri2004** [comment]
Same issue when updating theme: 
Fatal error: Uncaught Error: Call to a member function get() on boolean in /home2/happymal/public_html/wp-content/plugins/jetpack/sync/class.jetpack-sync-module-themes.php:171 
Stack trace: 
#0 /home2/happymal/public_html/wp-includes/class-wp-hook.php(298): Jetpack_Sync_Module_Themes->check_upgrader(Object(Theme_Upgrader), Array) 
#1 /home2/happymal/public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) 
#2 /home2/happymal/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) 
#3 /home2/happymal/public_html/wp-admin/includes/class-theme-upgrader.php(407): do_action('upgrader_proces...', Object(Theme_Upgrader), Array) #4 /home2/happymal/public_html/wp-admin/update.php(213): Theme_Upgrader->bulk_upgrade(Array) 
#5 {main} thrown in /home2/happymal/public_html/wp-content/plugins/jetpack/sync/class.jetpack-sync-module-themes.php on line 171
