### ISSUE TITLE
Contact-Form quotes "To:" and "Reply-To:" fields when PHP documentation does not

### ISSUE THREAD

**Issue by michaelherold** [Automattic/jetpack#7350]
#### Steps to reproduce the issue

Read or run any of these tests:

* [pre_test_process_submission_sends_correct_single_email](https://github.com/Automattic/jetpack/blob/31818315b48a8a867d259c9de91287940763d930/tests/php/modules/contact-form/test_class.grunion-contact-form.php#L331)
* [pre_test_process_submission_sends_correct_multiple_email](https://github.com/Automattic/jetpack/blob/31818315b48a8a867d259c9de91287940763d930/tests/php/modules/contact-form/test_class.grunion-contact-form.php#L368)

#### What I expected

According to the [PHP documentation for `mail`](http://php.net/manual/en/function.mail.php), the "name" part of the mailbox should not be quoted, even when there is whitespace (note the fourth example, where `Another User <anotheruser@example.com>` is represented without quotes. This implies that their "RFC2822-compliant formatting" is actually not compliant, but that's what we're playing with here.

Given that PHP's mail function only gives examples without quotes, I expect that there should be no quotes around the `display-name` portion of the the mailbox.

This matters because somewhere between Jetpack and the `mail` function, the double-quote gets mangled into a form that gets communicated incorrectly. You can see how this looks in GMail in the following screenshot.

![Example mangled To and Reply-To](https://user-images.githubusercontent.com/424833/27144750-ac6fe7ba-50f8-11e7-98b9-f36d9b4fef87.png)

_NB: Since the "name" part of the mailbox is a `dot-atom` according to RFC2822, it should not be represented as a `quoted-string` (see the first paragraph of [section 3.4.1 of RFC2822](http://www.faqs.org/rfcs/rfc2822.html)). This means that the contact form implementation of RFC2822 is incorrect as well since `john@example.com` is a dot-atom._

#### What happened instead

The contact form _always_ uses the `quoted-string` version of name, i.e. `"Sally User" <sally@example.com>`. This gets mangled into the following: `To: \"\\\"Sally User\\\"\" <sally@example.com>`, which is unparsable by the mail agent.

I have attached [an output of an `strace`](https://github.com/Automattic/jetpack/files/1078042/strace.txt) showing what it looks like when sent to the mail agent.

The root cause is in two places:

* [add_name_to_address](https://github.com/Automattic/jetpack/blob/0ff86590990c28b185e959fd9aed9fca0b4db85e/modules/contact-form/grunion-contact-form.php#L2249-L2256)
* [headers concatenation](https://github.com/Automattic/jetpack/blob/0ff86590990c28b185e959fd9aed9fca0b4db85e/modules/contact-form/grunion-contact-form.php#L2019-L2020)

/cc @splitinfinities

**Comment by jeherve** [comment]
Related: #7733

cc @seear and @iandunn who have done some work on the contact form fields in the past few releases.

**Comment by tactuschris** [comment]
I am hoping to get this ticket noticed again, it is still present and causing issues for my team.

The double-quotes that are added in the 'To:' and 'Reply-To:' fields are getting oddly escaped.
Removing them from the 2 places that @michaelherold suggested seems to have fixed the issue for me, I am just hoping that could be done in a more permanent way.

Thanks

**Comment by annezazu** [comment]
Mentioned by customer in 2650266-zd

**Comment by KevWal** [comment]
This issue is being seen on my site currently, and causing sending of jetpack contact forms via send in blue to fail.  Please see issue as documented by send in blue:

![Capture-3](https://user-images.githubusercontent.com/2286500/115862394-01c2ec00-a42c-11eb-85db-0752b7f72e69.JPG)

I have asked send in blue to confirm as requested by Jetpack support.

Thanks, Kevin
