### ISSUE TITLE
Masterbar: missing WP Admin toggle for responsive styles

### ISSUE THREAD

**Issue by lancewillett** [Automattic/jetpack#7368]
On WordPress.com sites, when navigating wp-admin screens we add in a small toggle button to allow viewing the WP Admin sidebar menu. Without it, you can't access the menus such as Plugins, Posts, Appearance when you have enabled the Jetpack setting for "Enable the WordPress.com toolbar".

I think we should add this toggle in for usability in small screens.

A few screenshots to illustrate (testing with Nexus 6P in both portrait and landscape mode).

1 - Jetpack site, WordPress.com toolbar on (note, no menu toggle) — small screen
<img src="https://user-images.githubusercontent.com/66797/27366186-528862a8-55f9-11e7-8613-af704cd19a26.png" width="480" />

2 - Jetpack site, WordPress.com toolbar off — small screen
<img src="https://user-images.githubusercontent.com/66797/27366190-52902a10-55f9-11e7-8f22-e7203558ff27.png" width="480" />

3 - WordPress.com site, small screen
<img src="https://user-images.githubusercontent.com/66797/27366188-5289fdde-55f9-11e7-8d9d-3d60fbf1501c.png" width="480" />

4 - WordPress.com site, small screen -- menu open
<img src="https://user-images.githubusercontent.com/66797/27366187-528904ec-55f9-11e7-9bef-41bacb4b8723.png" width="480" />

5 - WordPress.com site, medium size screen
<img src="https://user-images.githubusercontent.com/66797/27366191-529742e6-55f9-11e7-9904-63e2cf330ac3.png" width="480" />

6 - WordPress.com site, medium screen, menu open
<img src="https://user-images.githubusercontent.com/66797/27366189-528a2de0-55f9-11e7-98f4-e369f98b4c8b.png" width="480" />

7 - Jetpack site, medium screen size, WordPress.com toolbar turned off
<img src="https://user-images.githubusercontent.com/66797/27366193-52a10f1a-55f9-11e7-95db-5d8eeaaab076.png" width="480" />

8 - Jetpack site, medium screen, WordPress.com toolbar turned on
<img src="https://user-images.githubusercontent.com/66797/27366192-529ef2f2-55f9-11e7-936c-01ebfccbb623.png" width="480" />

**Comment by lancewillett** [comment]
This might be already addressed by https://github.com/Automattic/jetpack/commit/828a34eaca051064a5b4fa57e0826cc169dbfa13

**Comment by lancewillett** [comment]
w00t! That change did bring it back.

Tablet (medium size screen) needs some love. I'll spin up a PR for that.

<img width="803" alt="screen shot 2017-06-20 at 20 56 44" src="https://user-images.githubusercontent.com/66797/27366450-ffc8bc50-55fa-11e7-8c03-552e10b88289.png">

<img width="792" alt="screen shot 2017-06-20 at 20 56 49" src="https://user-images.githubusercontent.com/66797/27366451-01359e50-55fb-11e7-87b5-64c56957295b.png">

**Comment by lancewillett** [comment]
Closing as fixed — I've made a few WP.com side CSS changes that should help fix the tablet size issue (Jetpack loading might need to include a cache-busting string, though).

r158057-wpcom
r158058-wpcom
r158059-wpcom

**Comment by vindl** [comment]
Thanks for catching and fixing that @lancewillett! I did notice similar positioning issues in tablet view and attempted to solve it in https://github.com/Automattic/jetpack/commit/828a34eaca051064a5b4fa57e0826cc169dbfa13, but might have missed a few cases.

**Comment by lancewillett** [comment]
@vindl Cool. You could probably remove those CSS rules, since they duplicate the WP.com CSS that the masterbar loads (or if anything different, merge them back to WP.com to have them in one place).

**Comment by vindl** [comment]
@lance I think we'll need to merge them back in WP.com. Here is the diff D6125-code and the removal PR https://github.com/Automattic/jetpack/pull/7388.

**Comment by lancewillett** [comment]
Sounds good, thanks for doing those extra two patches. I'm AFK this week, but can test more once I get back if you still need a look.
