### ISSUE TITLE
Post sync: Undefined offset notice thrown in expand_wp_insert_post()

### ISSUE THREAD

**Issue by ericnicolaas** [Automattic/jetpack#7372]
Since June 9 I have been seeing the following notice in my debug log every minute or so: 

```
PHP Notice:  Undefined offset: 3 in /path/to/wp/wp-content/plugins/jetpack/sync/class.jetpack-sync-module-posts.php on line 157
```

I spent a bit of time trying to trace this issue back to its source and it seems like the issue is that the `wp_insert_post` items `Jetpack_Sync_Sender::get_items_to_send()` loops over never has a [3] index. Screenshot pictured below from my log showing a dump of what a typical item looks like:

![screenshot 2017-06-22 11 13 29](https://user-images.githubusercontent.com/676582/27423006-57d7900e-576f-11e7-8bc7-8fbbe374fc1c.png)

Let me know if you need any more specific details about my set up. Happy to provide whatever details I can here, or more sensitive details through a support email.

**Comment by zinigor** [comment]
Thanks for a very detailed bug report, we'll take a look!

**Comment by gititon** [comment]
Hi @ericnicolaas,

I'm looking into this for you, but I haven't been able to reproduce the issue you're observing yet. Can you please provide the following information to help me get to the bottom of it for you?

1. Which version of Jetpack you're running
2. Which plugins you have installed
3. The specific frequency you're observing the notice. Every minute? Every 5 minutes?
4. Whether you can correlate the appearance of the notice with any actions you or others take on your site?

Thanks!

**Comment by ericnicolaas** [comment]
Hi @gititon, 

Thanks for the quick reply. Details below.

> Which version of Jetpack you're running

`5.0`

> Which plugins you have installed

Akismet Anti-Spam: 3.3.2
All In One SEO Pack: 2.3.13.2
Analytics for WordPress — by Segment.io: 1.0.13
Automatic Download: 1.35
Disable Emojis: 1.5.3
Documentation Post Type: 0.1.0
Easy Digital Downloads: 2.7.11
Easy Digital Downloads - Auto Register: 1.3.9
Easy Digital Downloads - Custom prices: 1.5.1
Easy Digital Downloads - Downloads As Services: 1.0.6
Easy Digital Downloads - Invoices: 1.1.2
Easy Digital Downloads - Mail Chimp: 2.5.6
Easy Digital Downloads - Manual Purchases: 2.0.3
Easy Digital Downloads - Recurring Payments: 2.6
Easy Digital Downloads - Segment: 0.1.0
Easy Digital Downloads - Software Licenses: 3.4.12
Easy Digital Downloads - Stripe Payment Gateway: 2.5.5
Easy Digital Downloads - Taxamo Integration: 1.6.4
Easy Digital Downloads - Version API: 0.1.0
EDD Metrics: 0.6
EDD Sale Price: 1.0.2
HubSpot Marketing Free (formerly Leadin): 6.1.2
iThemes Security Pro: 4.0.0
iThemes Sync: 2.0.1
Jetpack by WordPress.com: 5.0
Mailgun: 1.5.8.2
Make Plus: 1.8.2
Monarch Plugin: 1.3.6
Ninja Forms: 3.1.5
Ninja Forms - Mail Chimp: 3.0.0
oEmbed Gist: 4.8.0
Postmatic & Postmatic Labs: 2.1.1
Query Monitor: 2.13.4
Replyable - Subscribe to Comments & Reply by email: 2.2.1
Retina Logo: 0.1.0
SEO Data Transporter: 1.0.0
Simple Image Widget: 4.4.1
WP All-in-one Tracking: 0.1.0
WP API Categories+Tags: 1.0
WPCharitable - Click To Tweet: 1.0
WPCharitable - Custom: 0.3.0
WPCharitable - Social Sharing Tracker: 1.0
WP Migrate DB: 0.9.2
WP REST API: 2.0-beta15
WP REST API - OAuth 1.0a Server: 0.3.0
WP Rocket: 2.10.3 (needs update - 2.10.4)

> The specific frequency you're observing the notice. Every minute? Every 5 minutes?

Just about every minute.

> Whether you can correlate the appearance of the notice with any actions you or others take on your site?

Not as far as I can tell. I've been developing locally and notice that it's happening continuously, regardless of whether I'm actively clicking around or doing anything on the site. So I would suggest it's getting triggered by AJAX or Cron.

**Comment by gititon** [comment]
Hi @ericnicolaas, 

While I wasn't able to reproduce your issue, I made a change that should prevent it from happening for you.  It's been merged to Master and will be part of a future Jetpack release. Here is the changed function for your reference:

https://github.com/Automattic/jetpack/blob/233cfb982dd80db16774d02d052ea3dce0e16bd4/sync/class.jetpack-sync-module-posts.php#L157

Regards!
