### ISSUE TITLE
Update Jumpstart UI

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#7373]
This would be the first implementation of our Warm Welcome project. Here is the current plan for implementation. The content grid will remain with the same content as before, but we're building a sort of warm welcome framework we can use for more than just this.

CC @ashleighaxios and @richardmuscat for copy suggestions

![image](https://user-images.githubusercontent.com/1123119/27437793-9aafb0c2-5720-11e7-90da-afe6f9affac0.png)

Original thread: p6TEKc-1hL

**Comment by MichaelArestad** [comment]
To clarify, there are plans to update the grid content in a future iteration. We are keeping it as is for expediency. We will then iterate.

**Comment by ashleighaxios** [comment]
I might make the heading "Your Jetpack site is ready to go!" and remove that line from the paragraph below. I say this thinking the current line may give folks the impression they should wait for confirmation before selecting the "Activate recommended features" button.

Some thoughts on Photon language here: https://github.com/Automattic/jetpack/issues/7308

_For a full sweep of content, it might be best to transfer to a Google doc and move it back after, but I'll leave that on Richard to decide._

**Comment by richardmuscat** [comment]
A few suggestions:

*Heading*
_Jetpack is now powering your site_

*Main text*
_Welcome aboard! Jetpack is already collecting traffic stats, blocking brute force attacks, and speeding up your images._

_The make the best of Jetpack we suggest turning activating our recommended features and pretty soon your Jetpack dashboard will be able to tell you everything that's going on with your site._

*Button*
As is.

*Sub heading*
_Jetpack's recommended features are:_

*Features grid*
- Are these the actual features? Mostly asking because its odd SEO Tools is in there being a Pro feature.
- How much leeway do I have to change this text?

**Comment by rickybanister** [comment]
You have all of the leeway. @MichaelArestad simply copied the existing text.

I think we should 100% be aligning this content with our new feature suite groupings instead of as discreet features.

**Comment by MichaelArestad** [comment]
@rickybanister can you drop a quick outline (just bullets or keywords) of what you're envisioning. I was thinking of mocking this up this afternoon.

**Comment by rickybanister** [comment]
@MichaelArestad sorry, my comment was directed toward @richardmuscat. 

As a start I think you could literally lift the phrasing and grouping from here:

https://jetpack.com/features/

Perhaps with some of our new illustrations where they're appropriate.

**Comment by MichaelArestad** [comment]
> How much leeway do I have to change this text?

@richardmuscat as much as you like. I will also take suggestions for a future iteration where we dispose of the grid. We're going for speed in implementation by reusing it for the first iteration.

**Comment by MichaelArestad** [comment]
> Are these the actual features? Mostly asking because its odd SEO Tools is in there being a Pro feature.

I think so. I think @jeffgolenski was the last one to work on the original grid and might have more insight.

**Comment by rickybanister** [comment]
It could be interesting or valuable to populate the jumpstart UI with the proposed plans feature API so it would always be up to date.

**Comment by MichaelArestad** [comment]
> It could be interesting or valuable to populate the jumpstart UI with the proposed plans feature API so it would always be up to date.

Can you elaborate with an example? I don't understand which parts you're envisioning. The grid content?

**Comment by rickybanister** [comment]
Sorry, not the grid content, but there is currently talk of Jetpack and the mobile apps collaborating on a plans/features api so wherever we are presenting features or checking which features a user has access to it is standardized and centralized.

I guess I was just curious if we can eventually pull the jumpstart features from that api.
