### ISSUE TITLE
Add Update Introduction view for major updates

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#7375]
The idea would be to inform our users of larger changes and cool new features in a bit more beautiful and noticeable way than just in a changelog. We don't need to do this every release, but we would want to do it each time we change something used regularly or each time we add something super cool.

It's similar in concept to the warm welcome, but instead of welcoming users to Jetpack, we're welcoming them to an updated and improved version of Jetpack.

It should a similar modal/dialogue view that was proposed in #7374 and #7373, but will need some design consideration. We will want to present a bit more copy, I think. Perhaps, when we iterate on #7373, we can utilize the more content-centric (pleasant to read like an article) styles to match. CC @rickybanister since I know you had some ideas about this.

**Comment by MichaelArestad** [comment]
Mockup of what this could look like:

![change-intro](https://user-images.githubusercontent.com/1123119/27881901-aa90c708-6187-11e7-9597-e9c29ad0a5d3.jpg)

And here's what it could look like if a user skips several releases before updating:

![ricks-kitchen](https://user-images.githubusercontent.com/1123119/27881904-af3b3d2e-6187-11e7-9c20-3444474540a8.jpg)

**Comment by rickybanister** [comment]
I love it.

The only change I would suggest is to keep the treatment of the 'read the full release post' the same for current release and past releases (meaning don't switch to using the non-primary button, just keep it a link down below).

I'm very curious to read the release about my kitchen—it's missed the release train for many months.

**Comment by MichaelArestad** [comment]
@dereksmart Are there any upcoming projects that are major changes that impact the users of active JP sites (UI changes/etc) that would warrant this view? If so, which release should we aim to get at least a basic version of this in to align with that project.

I'm also wondering if we should build this to get the data via API (not sure how translations work if we did this) so we could send edits/changes independently of releases. (may not be necessary)

**Comment by dereksmart** [comment]
@MichaelArestad I don't think there are any "major" new changes or features coming any time soon.  Most big ongoing projects are outside of Jetpack plugin.  However it might be a good idea to have a basic version of this to outline some of the "bigger" changes in each release, even if they're not huge. 

Using an API for this is an interesting idea, and I can see the value of doing that for releases that just list the most important parts of the changelog.  But for the "major" features that include screenshots and whatnot, I think it might be simpler to bake it right into the plugin.  The thing is that we're only showing one of these per release anyway, so might not be much value in using an API /shrug

**Comment by MichaelArestad** [comment]
@dereksmart well for the API I was thinking it might be useful to show an update when something major like the Activity Log comes to Calypso.

**Comment by dereksmart** [comment]
@MichaelArestad Ah yes, for that it totally makes sense and it feels like we can use the Jumpstart API to achieve that.

**Comment by MichaelArestad** [comment]
@dereksmart since we're likely to have the updated contact form in the next release, here's a version done with the contact form in mind. The only difference is the image.

![cf-1](https://user-images.githubusercontent.com/1123119/28554617-4666c71e-70af-11e7-89aa-8d2a8de3b25c.jpg)
![cf-2](https://user-images.githubusercontent.com/1123119/28554618-4674285a-70af-11e7-8708-eed4d15f22cd.jpg)

@jeffgolenski or @ashleighaxios could one of you (if you're around) make sure this gets attention so we can get it in within the next few days. I'll jump in when I can.

**Comment by ashleighaxios** [comment]
Can keep an eye out. I might also make the image a closer crop so that it doesn't repeat the WordPress sidebar, giving that endless mirror appearance to the page. Something like this:
![contactform](https://user-images.githubusercontent.com/22752103/28583352-dcb139e8-7136-11e7-8b80-9afaea74ddf8.jpg)
