### ISSUE TITLE
Tiled Galleries: 4 images not showing in mosaic

### ISSUE THREAD

**Issue by Jstachurski** [Automattic/jetpack#7376]
#### Steps to reproduce the issue

In a post or page, insert media. 
Choose 4 images(only happens with 4)
Select Tiled Mosaic from the gallery type

#### What I expected
The nice tiled mosaic of the 4 images to show up

#### What happened instead
All four images show together in a single line.

Something to note, is this doesn't happen EVERY time. There is also a workaround to fix this. If you reorder the images, they will go into the mosaic. However, if you have a specific order you would like the images, this won't fix the issue. 

NOTE: I tried resizing the images, adding captions, deleting the whole gallery and adding it again. Nothing fixed it except reordering the images.

Reported by a user in 465627-hc

This was on their site: https://villafontmerle.com/about/ (the kitchen photos - to fix I swapped the first and second photo).

**Comment by kraftbj** [comment]
Does this happen with any four images or four specific images? There is a set of calculations that attempt to determine what order an image should go in. I'm not sure there's much room we can do to adjust it. Tiled Galleries.

**Comment by kraftbj** [comment]
Moving this to 7906-wpcom since this is impacting at WP.com site and the JP team doesn't maintain Tiled Galleries.
