### ISSUE TITLE
Photon CDN breaks APNG animated images

### ISSUE THREAD

**Issue by dolske** [Automattic/jetpack#7378]
(Apologies if I'm not filing this is the right place)

I was checking an old post of mine, and noticed some animated images are no longer animated:

https://dolske.wordpress.com/2008/02/11/capital-n-small-y/

The first 7 images in the page are Animated PNGs (https://en.wikipedia.org/wiki/APNG). The original post content links to (e.g.) http://dolske.net/blogimg/throbber-nn-win.png, but the published post ends up linking to https://i1.wp.com/dolske.net/blogimg/throbber-nn-win.png?zoom=2

If you view the original dolske.net links in a current modern browser (Firefox, Chrome, Safari), you see an animated image. (Edge/IE do not yet support APNG, and just show a static fallback image.)

The i1.wp.com links appear to have stripped out the animation. Presumably something is trying to optimize the PNG and is stripping out the chunks it doesn't recognize. It should either preserve APNG-related chunks, or at least use their presence to just serve the original image in lieu of breaking it by optimizing.

**Comment by kraftbj** [comment]
The server-side code of Photon is open-sourced with a Trac instance at code.trac.wordpress.org. I've re-posted your bug report over at https://code.trac.wordpress.org/ticket/72

Closing this ticket to defer to that. Thanks for reporting it!

**Comment by javiergutierrezchamorro** [comment]
After 4 years issue is still there. Any update?
