### ISSUE TITLE
[Question] Do Not Track

### ISSUE THREAD

**Issue by dannycolin** [Automattic/jetpack#7382]
Hi, 

I would like to know if there's an option in Jetpack that enables users to opt out of tracking. In other words, is Jetpack compliant with donottrack.us? If not, I definitely think it would be a great feature to add to Jetpack.

Thanks

**Comment by zinigor** [comment]
@dannycolin there is work in progress that covers some of DNT compatibility here: #3798 
If you feel there is something missing from that implementation please feel free to open an issue or propose a pull request.
