### ISSUE TITLE
Social Media Buttons: Add NextDoor.com

### ISSUE THREAD

**Issue by seejacobscott** [Automattic/jetpack#7389]
NextDoor.com is a neighborhood/city/town based social media platform for connecting with neighbors about neighborhood news. Many sites would likely benefit from the ability to easily share to their neighborhood message boards regarding posts or issues for things like PTA announcements, neighborhood watch updates, HOA updates, etc. 

Requested here: 3276625-t

**Comment by kraftbj** [comment]
Sent NextDoor an e-mail. My guess is we probably wouldn't add this to Jetpack, but would be nice to have a tutorial on the support site on how to do this if they support it. Their docs don't give me anything to go on.

**Comment by kraftbj** [comment]
No response from Nextdoor. Closing as wontfix but can reopen if we hear back or if they have docs suggesting this is possible.
