### ISSUE TITLE
`/media/new` endpoint returns a fatal error

### ISSUE THREAD

**Issue by justinshreve** [Automattic/jetpack#7401]
The [`/media/new`](https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/media/new/) endpoint doesn't seem to work.

https://github.com/Automattic/jetpack/blob/73e9052394b8427b047cecb52ccf287ac82f01c3/json-endpoints/class.wpcom-json-api-upload-media-v1-1-endpoint.php#L31

`Jetpack_Media_Sync` doesn't seem to exist anywhere. I get the following error when trying to use the `/media/new` REST API endpoint:

`PHP Fatal error:  Uncaught Error: Class 'Jetpack_Media_Sync' not found in jetpack/json-endpoints/class.wpcom-json-api-upload-media-v1-1-endpoint.php:31`

**Comment by kraftbj** [comment]
Duplicate of https://github.com/Automattic/jetpack/issues/7339
