### ISSUE TITLE
Widgets: Top Posts & Pages deletes own title in wp-admin

### ISSUE THREAD

**Issue by spncrb** [Automattic/jetpack#7402]
#### Steps to reproduce the issue
1. Add the Top Posts & Pages widget to your site via wp-admin
2. Leave the default title, Save
3. The title disappears
4. Try any other title, including 'top posts & pages' or 'Top Posts and Pages'
5. They save, as you'd expect.
6. Try "Top Posts & Pages" again
7. Disappears

#### What I expected
To be able to use the default title without it disappearing

Note that on the site it still shows the correct title.

#### What happened instead

Title disappears from wp-admin

Because this is a pretty obscure bug that doesn't harm the site itself, I can see this getting low priority, but still worth reporting.

Gif:
![toppostspagesdisappers](https://user-images.githubusercontent.com/8921630/27662603-53e94994-5c13-11e7-8612-0ba6dc2e6086.gif)

**Comment by jeherve** [comment]
This is indeed done on purpose, mostly to avoid displaying a default title in English if you decide to switch to a different language later. It will only happen when the title you enter matches the default title.

#7763 should solve that display problem.
