### ISSUE TITLE
WordPress.com Toolbar: hamburger icon overlapping issue on tablet view

### ISSUE THREAD

**Issue by vindl** [Automattic/jetpack#7413]
#### Steps to reproduce the issue

1. Use a test Jetpack site with WordPress.com Toolbar module enabled.
2. Navigate to `/wp-admin/users.php` for example.
3. Switch to tablet view size (between 480px and 782px).
4. Click on WordPress icon on top to open up the My Sites menu.

#### What I expected

Hamburger icon should not be visible in front of the menu.

#### What happened instead

Hamburger icon overlaps the My Sites menu.

<img src="https://cldup.com/Kz0qbUQfdI.png" alt="hamburger" width="400px">

Also, the hamburger icon overlaps the page content if there is no main heading on the page.

**Comment by eliorivero** [comment]
I haven't found this issue. However, I do fixed the issue of the icon overlapping the Jetpack logo here 
https://github.com/Automattic/jetpack/pull/7418

**Comment by vindl** [comment]
Thanks @eliorivero! I'm still able to reproduce this on Ubuntu 16.04 LTS and Chrome Version 57.0.2987.133 though (tried busting the cache too).

**Comment by vindl** [comment]
The previous description was not entirely correct since this only happens on tablet view size (in this case between 480px and 782px).

**Comment by vindl** [comment]
Resolved in D6245-code.

**Comment by zinigor** [comment]
Fixes the problem for me!
