### ISSUE TITLE
Comment likes: no notifications after liking a comment

### ISSUE THREAD

**Issue by vindl** [Automattic/jetpack#7420]
After liking a comment no notifications are generated. This should work in a similar way that post likes do.

#### Steps to reproduce the issue

1. Use a test Jetpack sites with Comment Likes module enabled.
2. Open up a test post whit a few comments that you've written.
3. Like a comment, and observe that no new notifications are shown.

**Comment by vindl** [comment]
Resolved in D6248-code.

**Comment by aheckler** [comment]
3307962-t

**Comment by vindl** [comment]
@aheckler fix for this has been deployed, should be working fine now. Please note that notifications dispatched prior to this fix will not be shown.

**Comment by aheckler** [comment]
@vindl I tested this just now on my sandbox:

http://adamkheckler.wpsandbox.me/8214

You can see there that some of those comments have been liked, but none of us received notifs. Am a testing incorrectly, or is there some "gotcha" that I'm not aware of?

**Comment by aheckler** [comment]
Re-opening after some discussion with @vindl in Slack.

**Comment by vindl** [comment]
Updated proposed in D6331-code.

**Comment by vindl** [comment]
@aheckler new update deployed.
