### ISSUE TITLE
Cannot login to services such as IFTTT that integrate with WordPress

### ISSUE THREAD

**Issue by cecoates** [Automattic/jetpack#7430]
#### Steps to reproduce the issue
Login to or create an IFTTT account.

Visit the WordPress service page:

https://ifttt.com/wordpress

Click "connect":

![download](https://user-images.githubusercontent.com/10121835/27890967-08eaa8bc-61bc-11e7-8a47-d340032e36a0.png)

Error: "Unable to verify Wordpress credentials. Please try again."

![screen shot 2017-07-05 at 19 57 24](https://user-images.githubusercontent.com/10121835/27890987-4632300a-61bc-11e7-9c1d-9f5675bddc0f.png)

#### What I expected

Logging in via a WordPress.com only site, or WordPress.org only site, works. AT sites and Jetpack sites cannot login.

#### What happened instead

Presented with error: "Unable to verify Wordpress credentials. Please try again."

![screen shot 2017-07-05 at 19 57 24](https://user-images.githubusercontent.com/10121835/27890987-4632300a-61bc-11e7-9c1d-9f5675bddc0f.png)

**Comment by kraftbj** [comment]
I couldn't duplicate the issue (and use IFTTT one of my Jetpack sites in production). This is using old XMLRPC, so would need the wp-admin user/pass. WP.com login shouldn't be used (nor should ever be entered on a third party site).
