### ISSUE TITLE
Subscriptions: emails not sent (cron conflict?)

### ISSUE THREAD

**Issue by kristarella** [Automattic/jetpack#7431]
#### Steps to reproduce the issue
1. Subscribe via email to http://quotes.justdharma.com/
2. Confirm subscription via email link

#### What I expected
To receive new post emails when they are published

#### What happened instead
No emails received

I've checked logstash. Emails are definitely not being sent.

Is it possible these settings in WP Crontrol are messing things up?
![image](https://user-images.githubusercontent.com/2031017/27898149-ed6ec5e4-6267-11e7-9127-dc46eb93b99a.png)
![image](https://user-images.githubusercontent.com/2031017/27898158-f2489946-6267-11e7-9dd1-2232600861be.png)

3277844-t

**Comment by kraftbj** [comment]
I'm going to close this. It's been a long time and something we would handle today via jpop-issues. The cron job in and of itself looks fine.
