### ISSUE TITLE
Social icons widget: use `social logos` for the svg icons 

### ISSUE THREAD

**Issue by drw158** [Automattic/jetpack#7433]
Question:

Currently we have a repo of social logos and icons for use in the Calypso UI. I believe the icons are also being used on the frontend of the site via Sharing:

https://github.com/Automattic/social-logos

![screen shot 2017-07-06 at 11 48 35 am](https://user-images.githubusercontent.com/618551/27922562-1174db12-6241-11e7-8620-ff3e525ad3b5.png)

Social Logos is published NPM as a module.

Could Jetpack use the same svgs for the [Social Icons Widget](https://en.blog.wordpress.com/2017/07/06/social-icons-widget/)? Found [here](https://github.com/Automattic/jetpack/blob/master/modules/theme-tools/social-menu/social-menu.svg) in the code. 

This would make sure all of our products use the same source svgs, and if there is an update to a logo, we could do that easily.

cc @thomasguillot

**Comment by drw158** [comment]
Looks like the social logos webfont is located here in Jetpack:

https://github.com/Automattic/jetpack/tree/master/_inc/social-logos

It would be great if we didn't have to update here every time there is an update to Social Logos. Is it possible to install Social Logos here as an npm module?

**Comment by jeherve** [comment]
Closed #4250 as duplicate.

Related: #6055
