### ISSUE TITLE
Plugin conflict with SiteOrigin Panel (breaking Leaflet Maps Marker / Maps Marker Pro maps as a result)

### ISSUE THREAD

**Issue by robertharm** [Automattic/jetpack#7440]
I am the developer of the mapping plugins Leaflet Maps Marker (https://wordpress.org/plugins/leaflet-maps-marker/) and Maps Marker Pro and users reported a plugin conflict involving Jetpack - I hope you can help, although this seems to be a tricky issue:

my plugins are shortcode based, maps get created if you add a shortcode like [mapsmarker layer="1"] to posts or pages. The issue now reported is, that if such a shortcode is added to a "SiteOrigin Editor" widget and if Jetpack is active with the option "Add sharing buttons to your posts" (wp-admin/admin.php?page=jetpack#/sharing) active, then maps break. See example at https://dev.mapsmarker.com/free/2017/07/09/siteorigin-jetpack-issue-with-maps/ - the issue is, that somehow Jetpack is duplicated the JS output created by my mapping plugins if this option is enabled.

This issue only happens though if my shortcode is used within a "SiteOrigin Editor" widget - if I use the same shortcode with the regular Wordpress editor, everything works fine. See example at https://dev.mapsmarker.com/free/2017/07/09/layer-1-regular-usage/

It would really be great if you could have a look, as for me this seems like a general issue with SiteOrigin & Jetpack.

#### Steps to reproduce the issue
1. Install Leaflet Maps Marker
2. Install Jetpack
3. Install "Page Builder by SiteOrigin" + "SiteOrigin Widgets Bundle"
4. add a new map using Leaflet Maps Marker
5. create a new post
6. switch to PageBuilder
7. add "SiteOrigin Editor" widget
8. add map shortcode into this widget, e.g. [mapsmarker marker="1"]
9. save post

#### What I expected
map should be displayed when viewing the published post

#### What happened instead
map is broken instead. maps work again, if the Jetpack option "Add sharing buttons to your posts" is disabled.

**Comment by jeherve** [comment]
Could you point us towards the code filtering the post content and adding the shortcode (with `add_shortcode`) in your plugin, so we can take a closer look at what could cause this conflict?

Thanks!

**Comment by robertharm** [comment]
@jeherve thanks for your reply - we are currently preparing a major rewrite and the issue cannot be reproduced anymore since we tested with our current dev version - so issue can be closed.
