### ISSUE TITLE
Don't deactivate Jetpack when closing the Connection Banner 

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#7447]
"can we stop the ‘x’ in the corner of the connection banner from deactivating Jetpack in 5.2? I’m curious to see what kind of effect that might have. If we are showing a big banner on the plugins page and folks don’t want to deal with it in that moment, they end up deactivating and then never getting a second chance to explore what Jetpack can do for them by visiting the pre-connection dashboard page."

- @rickybanister

**Comment by jeherve** [comment]
Fixed in #7603
