### ISSUE TITLE
Publicize: import Facebook comments from Publicize posts

### ISSUE THREAD

**Issue by kristarella** [Automattic/jetpack#7448]
Suggestion from 3316405-t to import the comments on a Facebook post back to the WordPress post.

My suggestion, if it's viable at all, would be to only do this for the Publicize post where the Facebook post ID is stored in the Publicize RC, so that it's definitely the comments on the site owner's facebook page, and not any other shares of the same post.

**Comment by ststonenet** [comment]
There was a plugin called Social (https://github.com/crowdfavorite/wp-social) who exactly offered this:

**Broadcast Published Posts**

Through use of a proxy application, you can associate your Twitter and Facebook accounts with your blog and its users. Once you publish a new post, you can then choose to automatically broadcast a message to any accounts authenticated with the overall blog or your current logged-in user.

- Automatically broadcast posts to Twitter and/or Facebook
- Supports multiple accounts associated per user and per blog
- Customize the broadcast message using tokens

**Pull in Tweets and Replies as Comments**

When publishing to Facebook and Twitter, the discussion is likely to continue there. Through Social, we can aggregate the various mentions, retweets, @replies, comments and responses and republish them as WordPress comments.

- Automatically polls Twitter and Facebook for mentions of your post
- Displays mentions inline with comments
- Filter comments by originating source (Facebook, Twitter, or your blog as comments)
- Allow users to reply to the offsite responses

You should also add Linkedin

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
