### ISSUE TITLE
How to unload specify shortcode?

### ISSUE THREAD

**Issue by tranlamnhatnam** [Automattic/jetpack#7449]
Hi guys!

I have a website and I recently installed Jetpack for it, but there are some shortcode of Jetpack that coincides with my shortcode.

I've seen instructions to remove Jetpack's shortcode but no way to succeed (all method are in theme's functions.php).

**Method 1:**
```
function my_remove_shortcode_function( $shortcodes ) {
    $jetpack_shortcodes_dir = WP_CONTENT_DIR . '/plugins/jetpack/modules/shortcodes/';
     
    $shortcodes_to_unload = array( 'recipe.php', );
 
    foreach ( $shortcodes_to_unload as $shortcode ) {
        if ( $key = array_search( $jetpack_shortcodes_dir . $shortcode, $shortcodes ) ) {
            unset( $shortcodes[$key] );
        }
    }
         
    return $shortcodes;
}
add_filter( 'jetpack_shortcodes_to_include', 'my_remove_shortcode_function' );
```

**Method 2:**
```
function jeherve_no_slideshow_for_you( $shortcodes ) {
    unset( $shortcodes['recipe'] );

    return $shortcodes;
}
add_filter( 'jetpack_shortcodes_to_include', 'jeherve_no_slideshow_for_you' );
```

I tried installing a new Wordpress and only installed Jetpack for testing.

- **Wordpress: v4.8**
- **Theme: Twenty Seventeen v1.3**
- **Jetpack: v5.1**

Activate Shortcode Embed at:
Http: // {my_site} /wp-admin/admin.php?page=jetpack_modules

**More information**
I open `plugins/jetpack/modules/shortcodes.php` and tried to print a list of Jetpack shortcodes right below [apply_filters](https://github.com/Automattic/jetpack/blob/90a253bd7363c46a8bb7d38d9132b1a07c6f5b67/modules/shortcodes.php#L66), but it seems that no shortcode was unset.

**Comment by phuclh** [comment]
I have the same problem.

**Comment by kraftbj** [comment]
You'll need to add that code to a plugin. The shortcodes are included when the modules are loaded, which happened at the `plugins_loaded` hook, which fires before theme code is executed.
