### ISSUE TITLE
Optimise/minify CSS

### ISSUE THREAD

**Issue by matthumphreys** [Automattic/jetpack#7450]
#### Steps to reproduce the issue

FYI: Below are two render-blocking CSS files loaded by http://metro.co.uk/. Automattic (wordpressvip.zendesk.com) have advised that the files are served up by Jetpack.

1. Open (using curl or any browser) 
https://s1.wp.com/_static/??-eJx9j90KwjAMhV/IGqoD9UJ8lq7GLJI2Ze2217cyJg5/7s7hfF8gMCXjNRaMBcJgkgzEMcPEV8KSIatnJ4Yrsi5bn/MGGKKWeVzCPHy/SqhG1LvCGlfF3MRx/0/tsRWlGgkq9VY/pNJhwAxdAyTaOvkFjJzg9W4yyRFGNzIswVTv6V7C2Tanw+5o7d7eH34fcQQ=

2. Note that the CSS includes selectors such as .jetpack_widget_social_icons

3. Open (using curl or any browser) 
https://s1.wp.com/_static/??-eJx9jtEKgzAMRX9oWSlszj2MfYvWoNVGg0mpn78o+DZ8CTfhHHJdYQjLrDirowycch9ncSlOKG5E5SZMcGz3IHJz//GwrGh34kZ3grCLDSYkw660Erse1XQ5MyhulwpxdT7a42D1LpsVNhrallcUAZsUM4EO1u3wvvTxj3dVv3z99OMP7qJkMw==

4. Note that the CSS includes selectors such as div.jetpack-likes-widget-wrapper

#### What I expected

I expected the CSS to be optimised:
1. Minified (this would reduce the file size by 30%)
2. and/or, bundled with other CSS (to avoid the overhead of additional http requests)

#### What happened instead

1. Two unminified Jetpack CSS files were served. 

Render-blocking CSS really slows pages down, which is bad for users and bad for Google (as highlighted by Google's page speed recommendations).

The Metro.co.uk development team is happy to contribute if you can point us in the right direction - we haven't contributed to Jetpack before. 

Thanks

**Comment by kraftbj** [comment]
Thanks for the report! The minification process isn't part of Jetpack proper (the CSS mentioned is shared between both platforms) so I'm cross-posting this to the right team internally.

Cheers!

**Comment by matthumphreys** [comment]
I've just realised that inlining the CSS would be a bigger gain than minifying
https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery

We are going to investigate... we'll keep you posted. Thanks!

**Comment by wpgaurav** [comment]
Any progress on this, guys?

**Comment by jeherve** [comment]
@wpgaurav Things have changed quite a bit in the past few years, so the issue above may not be valid anymore. Could you expand on the issue you're running into, let us know the URL of the site where this is happening, so we can take a closer look?

Thank you!
