### ISSUE TITLE
Stats: Non-admins have empty Jetpack dashboard, no stats

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#7462]
To repro:

1. Jetpack > Settings > Traffic > Site Stats card.
2. Enable Editors to view stats reports.
3. Create a test user on your site, set role as Editor.
4. Log in as Editor user.
5. Go to Jetpack > Dashboard. Nothing displays.

We should probably show the fancy new Site Stats section:

<img width="785" alt="screen shot 2017-07-13 at 11 47 28 am" src="https://user-images.githubusercontent.com/5512652/28175039-200c1444-67c1-11e7-93f0-6abddc9ed3bc.png">

Jetpack > Site Stats still works, but if that eventually goes away, I don't know if there's any other place for other user roles to see the stats.

Even if we don't want to or can't put the Site Stats section under Jetpack > Dashboard, we should at least put *something*. Right now it's just awkwardly empty:

<img width="1424" alt="screen shot 2017-07-13 at 11 49 34 am" src="https://user-images.githubusercontent.com/5512652/28175142-61c3e20e-67c1-11e7-9d1d-8f07a937457a.png">

3264355-t

**Comment by rachelmcr** [comment]
I just encountered this on my Jetpack site with non-admin users, and I also noticed this console error when I viewed the dashboard:

`admin.js?ver=5.1:36 Uncaught TypeError: this.props.getOptionValue is not a function`

I expected to be able to visit the Jetpack dashboard to manage the connection between the user account on the self-hosted site and their WordPress.com account (either to create a connection if the user isn't connected or see/manage an already connected account).
