### ISSUE TITLE
VideoPress: Need to RTL Editor CSS

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#7464]
When using VideoPress on a RTL site:
`Failed to load content css:
http://www.example.com/wp-content/plugins/jetpack/modules/videopress/css/videopress-editor-style-rtl.css`

We're not automatically processing to RTL that file.

Originally reported in 3321926-t

**Comment by seejacobscott** [comment]
User is reporting the error goes away after removing the Farsi language plugin Parsi Date (https://wordpress.org/plugins/wp-parsidate/), seems to be some conflict there. 

Taking a look at that plugin, they appear to be present to test with updated WP versions, but doesn't appear to be in active development, and no support queries are answered. 

I've reached out to one of the plugin contributors `wp_ehsaan935` on the Core WP slack to see if we can work together on the issue. I'll report back once I hear back from them.

**Comment by danjjohnson** [comment]
Couple of reports here:
https://parequests.wordpress.com/2017/07/03/jetpack-css-error-in-wp-admin-editor/

I also have one in 3326278-t

They don't have the Parsi Date plugin installed.

**Comment by amirhkhadem** [comment]
i am having the same problem in my website and i have the parsi date plugin, 
i have to go manually rename the file "videopress-editor-style-rtl.css" to "videopress-editor-style" 
and with every update i have to do this again, 
i hope jetpack finds a solution for this, its very unfortunate to remove jetpack because i really need the other plugin which is a calendar for iranian websites.

**Comment by amirhkhadem** [comment]
still there is no response to this issue and we are all having it continued

**Comment by jeherve** [comment]
@amirhkhadem We will update this issue as soon as we find a way to fix this. I've also upped the priority of this issue to make sure we get to it sooner rather than later.

**Comment by jenlynnemc** [comment]
User reported this error here: 731548-t
Receiving error: Failed to load content css: https://example.com/wp-content/plugins/jetpack/modules/videopress/css/videopress-editor-style-rtl.css
