### ISSUE TITLE
Unit Tests: Contact form now fails in WP trunk

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#7471]
All PRs are failing:

```1) WP_Test_Grunion_Contact_Form::test_parse_contact_field_escapes_things_inside_a_value_and_attribute_and_the_content
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'[contact-field label='Name' type='name' required='1'/][contact-field label='Email' type=&#039;&#039;email&#039;&#039; req&#039;uired=&#039;1&#039;/][contact-field label='asdasd' type='text'/][contact-field id='1' required &#039;derp&#039; herp asd lkj]adsasd[/contact-field]'
+'[contact-field label='Name' type='name' required='1'/][contact-field label='Email' type=&#039;&#039;email&#039;&#039; req&#039;uired=&#039;1&#039;/][contact-field label='asdasd' type='text'/][contact-field id='1' required derp herp asd lkj]adsasd[/contact-field]'
```

A core change ( https://core.trac.wordpress.org/changeset/41026 ) is the cause.

Failing test is https://github.com/Automattic/jetpack/blob/5.1/tests/php/modules/contact-form/test_class.grunion-contact-form.php#L528-L537 , specifically this string of text: `[contact-field id='1' required 'derp' herp asd lkj]adsasd[/contact-field]`

We're expecting that to return as `[contact-field id='1' required &#039;derp&#039; herp asd lkj]adsasd[/contact-field]` which is instead returning as `[contact-field id='1' required derp herp asd lkj]adsasd[/contact-field]`

Are we okay expecting the single-quotes are dropped? My read is this test should be modified since the actual behavior of the shortcode isn't impacted. Thoughts?

**Comment by dereksmart** [comment]
I agree, all that needs to be updated here is the test
