### ISSUE TITLE
Double Quoted URLs in jetpack.css cause 404

### ISSUE THREAD

**Issue by caleblloyd** [Automattic/jetpack#7488]
In the Jetpack 5.1 release there are 2 URLs that cause 404s in `jetpack.css` because they are double quoted:

```
@font-face{font-family:Noticons;src:url('"https://wordpress.com/i/noticons/Noticons.woff"')}

@font-face{font-family:"Open Sans";src:url('"https://fonts.googleapis.com/css?family=Open+Sans"')}
```

These appear in the minified CSS.  They should either be quoted with single quotes or double quotes, but not both.  Since they are quoted with both, we get the following 404:

```
GET
http://example.com/wp-content/plugins/jetpack/css/%22https:/fonts.googleapis.com/css?family=Open+Sans%22
404
```

**Comment by kraftbj** [comment]
Thanks for the report! This was previously reported in https://github.com/Automattic/jetpack/issues/7435
