### ISSUE TITLE
Social Menu: Add Snapchat support

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#7492]
We received user request to add Snapchat icon to the Social Menu. That sounds like a good idea to me, given Snapchat's popularity.

**Comment by timnolte** [comment]
I think until the [Social Icons](https://github.com/Automattic/social-logos/pull/72) are updated with the Snapshat icon this can't be properly completed. Once that PR is accepted I can work on this.

**Comment by torres126** [comment]
I believe Jetpack now supports Snapchat already, tested with the Social Menu and the Social Icons Widget and it appeared as expected. Support doc mentions it too.

![gsdfgfdsgfsdg](https://user-images.githubusercontent.com/43215253/52509278-74e73b80-2bef-11e9-991c-96ffd3720662.png)

**Comment by jeherve** [comment]
Yup, that is correct. Closing.
