### ISSUE TITLE
Show Themes card in Plans tab when site is on Professional pla

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/jetpack#7493]
Currently, if a site is on the Professional plan, we do not show a card about Premium themes:

<img width="1280" alt="fullscreen_20_07_2017__11_18" src="https://user-images.githubusercontent.com/2287740/28412786-24b3d1c2-6d3d-11e7-8cd0-3cbeda722b87.png">

We should.

**Comment by dereksmart** [comment]
Will be fixed by #7472

**Comment by eliorivero** [comment]
Fixed in #7472
