### ISSUE TITLE
Share buttons cause invalid Instant Articles in Automattic iA plugin

### ISSUE THREAD

**Issue by jeremyclarke** [Automattic/jetpack#7496]
Hi, this is a copy of a ticket from the Instant Articles for WP plugin tracker, since it involves both plugins and maybe working together the importance of the problem will be clearer. 

https://github.com/Automattic/facebook-instant-articles-wp/issues/732

# Steps required to reproduce the problem

1. Enable Jetpack
2. Enable "Add sharing buttons to your posts" setting in "Sharing" section of Jetpack settings
3. Enable iA plugin and get to the point where the validation box shows on posts.

# Expected Result

Both plugins are created by Automattic, and the iA plugin already has several fixes related to Jetpack, so:

* I expect everything to work and there to be no errors, so I can use both iA and Jetpack sharing at the same time

# Actual Result

* Transformation error: "No rules defined for `<div class="sharedaddy sd-sharing-enabled">` in the context of InstantArticle"

i.e. " This post will not be submitted to Instant Articles because the transformation raised some warnings." and " This post was transformed into an Instant Article with some warnings [Learn more | Transformer rule configuration | Toggle debug information]"
<img width="897" alt="screen shot 2017-07-19 at 15 08 10 pm" src="https://user-images.githubusercontent.com/139995/28384849-1cb3b9b4-6c94-11e7-9d84-d8ee9de76aae.png">

---

**Version Info**

* Plugin version: 4.0.2
* WordPress version: 4.8
* PHP version: 7.x

---

Is it possible this just hasn't been addressed yet? I can't find ANY references to the problem on the forums or here on GitHub, which seems outrageous considering how many people must be using both these plugins (and the fact that it would affect wordpress.com???)

I'm hoping something is wrong with my setup, but figured a ticket here was appropriate either way for future reference of others who might run into the problem.

**Comment by kraftbj** [comment]
I haven't investigated yet, but the FBIA plugin may need something like https://github.com/Automattic/amp-wp/blob/master/jetpack-helper.php#L19-L21

**Comment by jeherve** [comment]
Closing this, as this seems like something we can fix in the iA plugin, as discussed here:
https://github.com/Automattic/facebook-instant-articles-wp/issues/732#issuecomment-316833037

**Comment by Fitrametrosidik** [comment]
Help me Tampilkan tombol berbagi.
Buka panel: Facebook Instant Articles
Facebook Instant Articles
 This post will be available as Instant Article once it is published and shared on Facebook.

 This post was transformed into an Instant Article with some warnings [Learn more | Transformer rule configuration | Toggle debug information]

No rules defined for <div class="sharedaddy sd-sharing-enabled"> in the context of InstantArticle

**Comment by Fitrametrosidik** [comment]
This post was transformed into an Instant Article with some warnings [Learn more | Transformer rule configuration | Toggle debug information]

No rules defined for <div class="sharedaddy sd-sharing-enabled"> in the context of InstantArticle

**Comment by jeherve** [comment]
@Fitrametrosidik I would recommend that you share the issue here instead:
https://wordpress.org/support/plugin/fb-instant-articles

**Comment by vivienlee123** [comment]
This is my rules
{

"rules":

[

{ "class": "IgnoreRule", "selector" : "div.fb-like" },

{ "class": "IgnoreRule", "selector" : "div.sharedaddy" },

{ "class": "IgnoreRule", "selector" : "div.jp-relatedposts" }

]

}

**Comment by fiqz90** [comment]
Hi,

i'm using the Jetpack features which is **Adding a Related Posts Block** within the article. however when it transform into an instant article, there is problem with it. It shows like this -> No rules defined for <nav class="jp-relatedposts-i2"> in the context of InstantArticle. I've done some searching on this but not found any. i've try the <div class> solution but nothing change because the problem I encounter is <nav class>. Somebody who expert on this please help. I have no knowledge on coding

regards,
Affiq

**Comment by jeherve** [comment]
> Adding a Related Posts Block within the article. however when it transform into an instant article, there is problem with it. It shows like this -> No rules defined for
Noting that this is now tracked in #13462
