### ISSUE TITLE
Typo on Jetpack string 

### ISSUE THREAD

**Issue by kant** [Automattic/jetpack#7498]
#### Steps to reproduce the issue
On this permalink:  [https://translate.wordpress.org/projects/wp-plugins/jetpack/stable-readme/es/default?filters%5Boriginal_id%5D=4159391](https://translate.wordpress.org/projects/wp-plugins/jetpack/stable-readme/es/default?filters%5Boriginal_id%5D=4159391)
#### What I expected
the word `Multi`
#### What happened instead
I found `Mutli`

**Comment by zinigor** [comment]
Nicely spotted, thank you! Feel free to submit a PR that fixes that typo, or we can do it ourselves.

**Comment by zinigor** [comment]
The line that needs to be changed is here:
https://github.com/Automattic/jetpack/blob/c515ae4a3909530bcb471a9c1f66311d895220c3/changelog.txt#L277
