### ISSUE TITLE
Omnisearch: "Page not found" error when attempting to view support documentation

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/jetpack#7504]
A "Page not found" error comes up when attempting to view the support documentation for Omnisearch via some browsers/WordPress.com accounts.

#### Steps to reproduce the issue

1. Navigate to Jetpack > Settings and search for "Omnisearch".
2. Click on the "Learn more" link:

<img width="801" alt="screen shot 2017-07-24 at 11 18 50" src="https://user-images.githubusercontent.com/2998162/28519035-00521a8c-7062-11e7-8f58-fe8353f6965e.png">

3. View [the Omnisearch support document](https://jetpack.com/support/omnisearch/
).

#### What I expected

I expected to be able to view the content at the following URL: https://jetpack.com/support/omnisearch/

#### What happened instead

I received a "Page not found" error when viewing the page:

<img width="805" alt="screen shot 2017-07-24 at 11 24 13" src="https://user-images.githubusercontent.com/2998162/28519314-fcc36ac8-7062-11e7-9f1b-44034d7c57cd.png">

I'm able to view the content okay when viewing from my Super Admin account:

<img width="1247" alt="screen shot 2017-07-24 at 11 28 51" src="https://user-images.githubusercontent.com/2998162/28519395-4bdbdf82-7063-11e7-9ab8-9c2623edf685.png">

**Comment by jeherve** [comment]
I published the page back, so there won't be any 404 anymore.

It's worth noting that Omnisearch has now been sunset. It is not part of Jetpack anymore. (ref: #7590)

Anyone looking to work with Omnisearch can use [this separate plugin](https://github.com/georgestephanis/Omnisearch) instead.
