### ISSUE TITLE
WordPress.com Toolbar: Most links unclickable on touch devices.

### ISSUE THREAD

**Issue by bisko** [Automattic/jetpack#7529]
### How to reproduce:

1. Have a Jetpack site with WordPress.com toolbar enabled
2. Open a page
3. Open the toolbar
4. Try to click on Blog posts/Pages and Add

### What's happening:

Nothing :(

### What should be happening:

The link should be followed and the specified section opened.

### Notes:

* Happens on Touch enabled devices (or touch events emulation enabled in Chrome)
* Sometimes it does nothing, sometimes it opens the notifications panel
* Reproducible on iOS, Android and Chrome on macOS with touch emulation enabled
* Seems to be happening only on Jetpack enabled sites, WordPress.com sites are not affected.

![out](https://user-images.githubusercontent.com/184938/28581126-1ab865ee-716a-11e7-938b-c8caf57d70cb.gif)

( There is no cursor, but you can notice the items tapped get highlighted )

cc @michaeldcain @lancewillett @designsimply @marekhrabe @folletto

**Comment by designsimply** [comment]
Possibly related: #6993 cc @vindl

**Comment by jeherve** [comment]
Could you give this another try with the current Bleeding edge version of the Jetpack plugin, thanks to the [Beta plugin](https://jetpack.com/beta/)?

I wonder if the issue may have been fixed by the different fixes we've made to the masterbar recently.

Thank you!

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
