### ISSUE TITLE
Contact forms: set Name and Website fields to their right type when form is first created

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#7543]
@nicoleckohler reports:

> Something I noticed: the default contact form has fields for Name, Email, and Website, but the Name and Website fields are initially set to the Text field type instead of their corresponding types:
<img width="575" alt="screen-shot-2017-07-26-at-4-46-45-pm" src="https://user-images.githubusercontent.com/1041600/28644174-df522204-722e-11e7-9ba7-877c14a8fe3c.png">

> Obviously they would still work but I’m guessing that the field type at least for websites converts any inputted text into a clickable URL in the submission confirmation page/email or something like that.

**Comment by designsimply** [comment]
I noticed the "Website" field type doesn't stick if you update the default Website field or for any new field types either.

Steps to reproduce:

1. Go to Pages > Add New.
1. Click the "Add Contact Form" button.
1. Click the form and click the pencil icon to edit.
1. Note which field type the Website field is set to.
1. Click the "Add Field" button at the bottom.
1. Add a label and select "Website" for the field type.
1. Click the "Update Form" button.
1. Edit the form again. 
1. Check to see if the new form field just added still has the "Website" field type.

<strong>Result:</strong> saving any form field as type "Website" doesn't stick when you save and re-open the form.

Tested using WordPress 4.9-alpha-41159 and Jetpack 5.2-beta-12385-77e06aa-master with Safari 10.1.1 on Mac OS X 10.12.5.

**Comment by georgestephanis** [comment]
Looking at this now.
