### ISSUE TITLE
Comments: http can possibly be used for Twitter/Facebook comments despite site's https status

### ISSUE THREAD

**Issue by mzakariya** [Automattic/jetpack#7548]
#### Steps to reproduce the issue
- Have a secure/https WordPress installation
- Install Jetpack and use it for comment forms
- Respond using a facebook or twitter account
- View page in a browser that uses the default 'src' attribute instead of 2x/Retina variant
- Default 'src' image is served from http:// instead of https://
- Breaks padlock/security in modern browsers, as site's contents are not fully secure

#### What I expected
- Use https:// whenever available

#### What happened instead
- Used http:// on an https:// site

**Internal, including specific links/examples:** 606687-zen

https://github.com/Automattic/jetpack/blob/master/modules/comments/comments.php#L164

**Comment by seejacobscott** [comment]
reported here: 611559-zen
