### ISSUE TITLE
Changing Jetpack.com's favicon to transparent background

### ISSUE THREAD

**Issue by codestor4** [Automattic/jetpack#7550]
608674-t (ZD)

Jetpack.com's favicon could be changed to have transparent background instead of white. Currently it displays like this:

<img width="197" alt="screen shot 2017-07-25 at 4 25 41 pm" src="https://user-images.githubusercontent.com/20779676/28665940-fe07fe8a-72e2-11e7-8787-02a97793dba7.png">

**Comment by jeherve** [comment]
This has now been fixed.
