### ISSUE TITLE
Protect: Multisite Warning needs better styles.

### ISSUE THREAD

**Issue by georgestephanis** [Automattic/jetpack#7551]
<img width="620" alt="9aa66973e02b8f7bd663164797d24d67" src="https://user-images.githubusercontent.com/941023/28675760-c274d7fc-72b6-11e7-8a43-1c11a71ea2cf.png">

#### Steps to reproduce the issue

Activate Jetpack on a subsite instead of network activate.

#### What I expected

Some padding in my notice.

#### What happened instead

Sad Christmas.

**Comment by jeherve** [comment]
Closing in favor of #4794, since it looks like all the notices would need some love there.
