### ISSUE TITLE
Markdown: backticks nested inside shortcodes aren't converted

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#7560]
#### Steps to reproduce the issue
1. add this code somewhere:
```php
add_shortcode( 'test', function( $atts, $content ) {
	return "Output: $content";
} );
```
2. add a post and add
```
[test]Text with `code` in it.[/test]
```

#### What I expected
The word code, within backticks, to be wrapped in `<code>` tags.

#### What happened instead
The word code was rendered as plain text wrapped in backticks.

#### Notes
This doesn't happen if the text isn't wrapped in shortcodes.

**Comment by pento** [comment]
That seems like the expected behaviour to me. Does it parse correctly if you add this code?

`add_filter( 'jetpack_markdown_preserve_shortcodes', '__return_false' );`

See: https://github.com/Automattic/jetpack/blob/master/_inc/lib/markdown/gfm.php

**Comment by eliorivero** [comment]
Ah yes, adding that makes it parse correctly.
Thanks Gary!
