### ISSUE TITLE
Content Options: Writing a Post in Japanese with Blog Display Set to Excerpt Doesn't Respect More Tag

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/jetpack#7562]
#### Steps to reproduce the issue

1. Activate Independent Publisher 2 or Button 2, both of which have the Blog Display option in Content Options.
2. Set it to Post Excerpt.
3. Write a post in Japanese.
4. View archive page.

#### What I expected

I expected to see the post in Japanese display the more link on archive pages as well.

#### What happened instead

I saw other posts with the more link, but not the Japanese one.

I tested a few other themes without Content Options to make sure it didn't have issues displaying the link for a post written in Japanese. All worked as expected.

cc: @thomasguillot since you've worked on Content Options.

**Comment by iamtakashi** [comment]
Adding an observation. Paragraph breaks aren't respected either. 

Thanks for looking into it.

**Comment by thomasguillot** [comment]
I've done some testing on this and if you were to change your site's language setting to Japanese, then the Japanese excerpts should work as expected.

Japanese and English excerpts are treated differently by WordPress due to the different character sets, and the treatment follows the site's overall language setting.

**Comment by iamtakashi** [comment]
Thanks for looking into it.

We don't have to set site's language setting to Japanese to make more tag works though. Wouldn't this mean this issue is caused by how the plugin (not core) treat more tag?

**Comment by thomasguillot** [comment]
@iamtakashi The plugin treats the more tag the same way Core does as the custom excerpt function is a replica of Core with the same filtering option.
