### ISSUE TITLE
Contact Forms: warning in console in Firefox

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#7563]
Reported by @gititon 

#### Steps to reproduce the issue
1. in Firefox, add a Contact Form
2. in Console, you'll see `Empty string passed to getElementById().`

When I click the reference given in Console, it takes me to 
```js
if ( window.history.replaceState ) {
			window.history.replaceState( null, null, document.getElementById( 'wp-admin-canonical' ).href + window.location.hash );
}
```
Which it's not a CF code. Actually, CF doesn't use `getElementById` in any of its JS code, at least in the surface.

**Comment by georgestephanis** [comment]
Yeah, I'd seen it and tried backtracing it to the cause but got somewhat flummoxed.  Not sure what's causing it, but it seems to just be a warning, not an error -- nothing seems to actually break.

**Comment by jeherve** [comment]
I can't seem to see the warning anymore. closing.
