### ISSUE TITLE
Contact Forms: pre-fill field to send emails

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#7564]
Suggested by @SiobhyB 

> In WordPress.com, the field for the email address contact form submissions go to is pre-filled with the default address:
> Pre-filling with the default (and allowing users to change that default if necessary) could be convenient for users and save them a little bit of time (assuming most users want submissions to go to the address on file for their WordPress account).
    It could also be useful to pre-fill the “What would you like the subject of the email to be?” form with the default.

**Comment by jeherve** [comment]
Should we then prefill the form with the first site admin's email address, WordPress' `admin_email` option, or the email address of the author of the post / page?

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
