### ISSUE TITLE
PHP 7.0 + Advanced Custom Fields conflicts with Jetpack

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#7565]
I'm still collecting details on this, but wanted to start tracking it.

To duplicate:
1. Jetpack connected to WordPress.com
2. Using Advanced Custom Fields
3. PHP 7.0

Expected:
ACF-based custom fields save

Actual:
ACF-based custom fields are dropped.

Reported via 612525-zen

**Comment by seejacobscott** [comment]
User reporting that disabling Contact-Form and Markdown did not stop the issue, but it did work as expected after disconnecting from wp.com. 

Deactivating Jetpack was not necessary, just disconnecting.

**Comment by dereksmart** [comment]
This may happen if the site does not have any widgets.  There is a current bug #7595 in our widget migration script that causes it to run on every admin page load if there are no widgets, and it's possible that the wp_insert_post() part of the script is conflicting here.  There is a fix in place, but for now if the user could try and manually set the migration flag, it should fix the problem. 

`Jetpack_Options::update_option( 'image_widget_migration', true );`

**Comment by dereksmart** [comment]
This should be fixed by #7605
