### ISSUE TITLE
Publicize: Unable to edit custom message until post is saved

### ISSUE THREAD

**Issue by dartiss** [Automattic/jetpack#7566]
#### Steps to reproduce the issue

Create a new post on WordPress.com (issue does not occur on self-hosted sites) using WP Admin. Don't save it yet. Go to change the custom Publicize text. You'll find it's greyed out and if you try and click into the box the content clears. If you don't change this and save the post, say as a draft, then you still can't edit the text, only clear the text and start from scratch. If, however, you change this custom text and save then the new text is editable.

#### What I expected

As per how self-hosted works, you should be able to edit the default custom text.

#### What happened instead

The default text can only be cleared from the text box. As this default to the post title, if this is long and the user wishes to make a minor change, this is inconvenient as they have to click into the box and type all the text out again.

I reproduced this on my own test account but this was reported by a VIP client, hosted on wp.com.

**Comment by kraftbj** [comment]
To confirm, this is only for a site fully hosted on WordPress.com (or WP.com VIP)? It is not happening for a Jetpack site or a VIP Go site?

**Comment by dartiss** [comment]
That's correct @kraftbj

**Comment by kraftbj** [comment]
@dartiss Cool, Publicize itself is in IO's sphere so I opened an issue in their repo and tagged you on it.
