### ISSUE TITLE
Show the connection banner in the wp-admin dashboard instead of the jetpack widget

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack#7567]
After a conversation with @jessefriedman and @jeffgolenski we would like to show the larger tabbed connection banner on the wp-admin dashboard in place of the Jetpack widget (which has been neglected). 

The tabbed widget includes all relevant feature information, will include acceptance of the Terms of Service, and generally is more helpful to users. 

So this:

![image](https://user-images.githubusercontent.com/437258/28843723-39b8fc86-76d0-11e7-9880-4896f056eea0.png)

Over this:

![image](https://user-images.githubusercontent.com/437258/28843744-490399bc-76d0-11e7-9d3f-cb2b2829b2a2.png)

We should be mindful of the WordPress welcome banner, however:

![image](https://user-images.githubusercontent.com/437258/28843762-5a0f0d0e-76d0-11e7-8f25-facf63497378.png)

Ours should either go below that or make some other consideration if that is present. (@jeffgolenski  if you have thoughts please share)

**Comment by dereksmart** [comment]
As part of this, let's also make sure to NOT disable Jetpack when dismissing via the `x`

**Comment by jeffgolenski** [comment]
> We should be mindful of the WordPress welcome banner, however:

That's a great point, @rickybanister Let's keep an eye on how much our banner over-takes that welcome banner once we build it in.

Another thing I'm concerned about is the relationship between our fill sized connection banner and our jetpack widget within the dashboard. If we implement this connection banner, we should ensure the jetpack stats widget _isn't displayed_ at all until a user connects—having too connection prompts will be too much. 

But then we need to think about non-admins and the connection prompt to link their account to WordPress.com. Right now if an admin is connected, but a non-admin isn't, this is all that displays: 

<img width="546" alt="screen shot 2017-08-02 at 3 20 31 pm" src="https://user-images.githubusercontent.com/214813/28890797-4b2a525a-7796-11e7-83de-c7bcb818918f.png">

Should we modify the connection banner to tailor to non-admins? 

cc @dereksmart

**Comment by rickybanister** [comment]
Yes, we definitely should have something for non-owners or non-connected users. They don't need to be sold on Jetpack's features since the site is connected, they just need to know that they aren't seeing the whole experience.
