### ISSUE TITLE
Add brand illustrations to tabbed connection banner

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack#7569]
Currently we use gridicons in a large, horsey circle like this:

![image](https://user-images.githubusercontent.com/437258/28844023-4131f034-76d1-11e7-9803-6499f0188a97.png)

Now that we have lovely custom illustrations, let's see if we can swap the icons out for the illustrations in the banner.

While doing so, it might be good to make sure we're using them in the same way in Jumpstart and on the connection banner if applicable. Perhaps we have a 'learn more about features' link on the full screen banner that could pop in the tabbed banner content? Perhaps that's for another issue, but please consider.

**Comment by jeherve** [comment]
We added illustrations a while ago. Closing.
