### ISSUE TITLE
Subscriptions: Allow activate/deactivate subscription emails per post

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#757]
On several occasions this has been requested: a toggle to turn on or off email subscriptions for an individual post, just like you can check/uncheck Publicize connections per post.

Original trac ticket:
* https://plugins.trac.wordpress.org/ticket/1709

**Comment by samhotchkiss** [comment]
@dereksmart - are you still working on this?  I'm punting to 3.5

**Comment by jeherve** [comment]
Also requested here:
https://wordpress.org/support/topic/notification-publication-based-permissions?replies=1&view=all
