### ISSUE TITLE
Widget saving fails with Jetpack 5.2

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/jetpack#7570]
#### Steps to reproduce the issue
On a site running Jetpack 5.2 add a widget from WP Admin or the Customizer (tested with a text widget and category widget), make a change to the widget such as adding a title, and click Save or allow auto-save to run. The changes will then disappear. This happens without error in WP Admin, but in the Customizer the error "Invalid value" is shown. The widget does appear to be added to the location it is set to, but no changes can be made to it besides location.

#### What I expected
Widgets settings to be saved properly.

#### What happened instead
Changes are lost on manual save (WP Admin) or auto save (Customizer).

WP Admin screencast:

![screen capture on 2017-08-01 at 22-10-22](https://user-images.githubusercontent.com/1900444/28854621-49f69d16-7706-11e7-9a17-5845d3492849.gif)

Customizer screenshot:

![screen shot 2017-08-01 at 10 11 53 pm](https://user-images.githubusercontent.com/1900444/28854641-755964ac-7706-11e7-9fe4-5289b7a8c5a8.png)

**Comment by roccotripaldi** [comment]
I can reproduce. Noting ( in case it helps debug ) that it is only happening with new widgets, and not widgets that were already in the sidebar.

**Comment by chad1008** [comment]
Another report on somerandomlady.com with multiple widgets.

In this case I _was_ able to add a widget through wp-admin. Site owner will use this as a workaround for now.

**Comment by DHWP** [comment]
Trying to add a valid username to Jetpacks Twitter  Timeline widget is also producing the "Invalid value." error

**Comment by aheckler** [comment]
614913-zen

**Comment by nagpai** [comment]
615283-zen

**Comment by kraftbj** [comment]
Since we can reproduce and actively worked on, we don't need to report impacted tickets here.

**Comment by mycircleuk** [comment]
I have been literally trying to find a solution to this for the last 8hrs - I have been going crazy! How long do these bugs normally take to resolve? Thanks everyone #feelnormal #newtothis

**Comment by kraftbj** [comment]
@mycircleuk The fit is in for testing right now and we're planning on release a bug fix into production soon.

**Comment by eduardozulian** [comment]
551729-hc

**Comment by eliorivero** [comment]
Jetpack 5.2.1 has been released and it fixes this issue.
https://jetpack.com/2017/08/02/jetpack-5-2-1-fixes-a-sidebar-widget-bug/
