### ISSUE TITLE
Conflict with Black Studio Tiny MCE plugin

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#7573]
Steps to reproduce:

1. On a Jetpack connected site, install and activate the [Black Studio Tiny MCE plugin](https://en-gb.wordpress.org/plugins/black-studio-tinymce-widget/).
2. In Appearance > Widgets add a Visual Editor widget to any widget area.
3. Try to add text to the widget. You can add a title, but no content.

I see these errors in the console, suggesting it may be related to the new contact form:

![image](https://user-images.githubusercontent.com/1990037/28875349-318c9096-778d-11e7-9819-c5eefc2725d6.png)

4. Deactivate Jetpack. The issue is resolved.
5. Activate Jetpack. The issue is still resolved.
6. Reconnect Jetpack. The issue returns.

Reported in 614913-zen

**Comment by seedprod** [comment]
See the same issue on anything that uses the wp_editor on a non page or post.

**Comment by danjjohnson** [comment]
Moving this to https://github.com/Automattic/jetpack/issues/7598
