### ISSUE TITLE
Allow ability to select type of tiled gallery to the tiled gallery suboption

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#7577]
This is a followup to https://github.com/Automattic/jetpack/issues/7576

Assuming 7576 is implemented, it would be great if we allowed folks to customize which type of gallery they want to apply everywhere. Here's what this could look like:

![image](https://user-images.githubusercontent.com/1123119/28887835-d55df488-777b-11e7-9b37-82df040bcbf9.png)

It would also need to be implemented in Calypso.

**Comment by danjjohnson** [comment]
Would this just be the default, and could still be overridden on a per-gallery basis?

**Comment by MichaelArestad** [comment]
Good question. I honestly don't know. I know it overrides the normal galleries. I'm not sure if it can be overridden on a per-gallery basis. 

On my test site it seemed to be overridden when I previewed other gallery types.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
