### ISSUE TITLE
Connection Banner: add themes slide + illustrations

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#7581]
We need to add a themes section to the connection banner in order to inform users who haven't connect yet that this jetpack feature exists. p6TEKc-1uC-p2

![themes-connection-banner](https://user-images.githubusercontent.com/214813/28891542-df5ff540-7798-11e7-995e-eba9f7decd52.png)

**Comment by MichaelArestad** [comment]
This is getting pretty huge. Perhaps we can slim it a down a bit or make it full screen?

**Comment by jeherve** [comment]
This was added to Jetpack already.
