### ISSUE TITLE
Confirm Safe Mode throws 404 Not found

### ISSUE THREAD

**Issue by mikaelz** [Automattic/jetpack#7589]
Clean WordPress 4.8.1 install with Akismet 3.3.4, Jetpack 5.2.1, qTranslate-X 3.4.6.8

Disabled Little Snitch (firewall) still persists.

![screen shot 2017-08-03 at 11 27 34](https://user-images.githubusercontent.com/454800/28915323-107862a6-783f-11e7-96b1-a9f4828204cc.png)
![screen shot 2017-08-03 at 11 19 00](https://user-images.githubusercontent.com/454800/28915324-1078f770-783f-11e7-8ebf-6898f4d8664b.png)

**Comment by mikaelz** [comment]
Deactivating qTranslate-X fixed the issue. Plugin rewrote the URL. How could we prevent it? API URL should not be translated

**Comment by kraftbj** [comment]
@ebinnion I'm tagging you since you are neck deep with language plugins.

@mikaelz My first thought is this may be a bug with the other plugin since we just ask Core for the REST API URL.

**Comment by mikaelz** [comment]
What I don't understand now is what/when is changing the REST API URL `idcL10n.apiRoot`

![screen shot 2017-08-06 at 13 52 33](https://user-images.githubusercontent.com/454800/29002984-c9ed6968-7aae-11e7-965e-1ea6a51623ed.png)

**Comment by mikaelz** [comment]
The AJAX URL gets redirected

![screen shot 2017-08-06 at 15 47 40](https://user-images.githubusercontent.com/454800/29003856-dce5985a-7abe-11e7-8ea8-f74dc57ee948.png)

**Comment by eliorivero** [comment]
Hi @mikaelz thanks for opening this issue. You can solve this on your installation with this filter:
```php
<?php
function jetpack_no_qtranslate_rest_url_redirect( $url_lang, $url_orig, $url_info ) {
	if ( false !== strpos( $url_info['wp-path'], 'wp-json/jetpack' ) ) {
		return false;
	}
	return $url_lang;
}
add_filter( 'qtranslate_language_detect_redirect', 'jetpack_no_qtranslate_rest_url_redirect', 10, 3 );
```
This will check if the url is a REST one, and if so, returning false will prevent the redirection.

**Comment by mikaelz** [comment]
Thanks @eliorivero. Checked the solution in the mentioned PR and I like it. Didn't know why the [3rd-party](https://github.com/Automattic/jetpack/tree/master/3rd-party) dir exists. Learned something new today :)
