### ISSUE TITLE
Deregistered styling works only if SCRIPT_DEBUG true

### ISSUE THREAD

**Issue by mikaelz** [Automattic/jetpack#7592]
I have the following in theme's `function.php`
```
function remove_grunion_style() {
    wp_deregister_style('grunion.css');
}
add_action('wp_print_styles', 'remove_grunion_style');
```
With `define('SCRIPT_DEBUG', true);` the styling works on localhost, but not in prod env with `define('SCRIPT_DEBUG', false);`

`jetpack.css` is concatenated, but not on demand, when for example a style was deregistered. After style deregistration `jetpack.css` should be recreated.

Am I missing something why is not as described?

**Comment by kraftbj** [comment]
jetpack.css isn't automatically concatenated. You'd want to return true to the `jetpack_implode_frontend_css` filter and then remove the style specifcally to Grunion.

jetpack.css includes, more or less, all of the frontend CSS used by Jetpack to produce a faster load vs a file for each module. The process could probably be smarter, sure, but that's where it is at right now and at least until HTTP 2.0 server push is to a point where that is more available.
