### ISSUE TITLE
jetpack_migrate_image_widget runs on all page loads

### ISSUE THREAD

**Issue by sboisvert** [Automattic/jetpack#7595]
It seems that 
Jetpack_Options::update_option( 'image_widget_migration', true );  https://github.com/Automattic/jetpack/blob/30cf0fa6188c4981ccd4323ad3cb4055a9d42093/modules/widgets/migrate-to-core/image-widget.php#L201

Is only run if the option is changed https://github.com/Automattic/jetpack/blob/30cf0fa6188c4981ccd4323ad3cb4055a9d42093/modules/widgets/migrate-to-core/image-widget.php#L186

This means that if the site had no image widget this code will never not run.

#### Steps to reproduce the issue

load a wp-admin page on a site with no image widget (the site had no sidebars and no widgets)

#### What I expected

Code to migrate images runs once

#### What happened instead

Code runs on every wp-admin page load.

**Comment by kraftbj** [comment]
At first read, the report sounds good. Tagging @dereksmart and @eliorivero to evaluate.

**Comment by dereksmart** [comment]
This will be fixed in #7605
