### ISSUE TITLE
Multiple errors when loading TinyMCE in other contexts

### ISSUE THREAD

**Issue by nylen** [Automattic/jetpack#7598]
First, [install Gutenberg](https://wordpress.org/plugins/gutenberg/).

Then either comment out [this workaround](https://github.com/WordPress/gutenberg/blob/v0.7.1/lib/compat.php#L84-L87) or change the [Jetpack version number](https://github.com/Automattic/jetpack/blob/a48f98b721f6f92a20a048d9275285a84202d458/jetpack.php#L17) to 5.2.2 or higher.  We worked around this first issue in the latest version of Gutenberg (https://github.com/WordPress/gutenberg/pull/2229).

Then, open a new post in Gutenberg and add a "Classic Text" block to it.

## First error

[This line](https://github.com/Automattic/jetpack/blob/cf1a73c7b0670678d99d47d46519f2027a2fc5c7/modules/contact-form/js/tinymce-plugin-form-button.js#L7) in the new contact-form code throws an error, and either leaves the editor a totally blank screen or breaks the newly added "Classic Text" block as in this screenshot:

![2017-08-04t16 42 22-0400](https://user-images.githubusercontent.com/227022/28988247-d969715c-793c-11e7-995c-09b23d755362.png)

This is because the script that initializes `grunionEditorView` is [only loaded on the `post` screen](https://github.com/Automattic/jetpack/blob/19b0eec0c298c6029995539ab02796ffa78bf776/modules/contact-form/grunion-editor-view.php#L54-L61), but TinyMCE (with external plugins) can be loaded in other contexts too, such as Gutenberg.

## Second error

Once that is fixed, we see the following additional error in the console, which doesn't appear to be actively breaking anything:

<img src="https://user-images.githubusercontent.com/227022/28988095-445978e6-793c-11e7-8298-492c15c50197.png" width="450">

<img src="https://user-images.githubusercontent.com/227022/28988094-445951c2-793c-11e7-88c9-9e731948c365.png" width="450">

**Comment by programsgulf** [comment]
I have the same issue <img src="https://www.programsgulf.com/issue.png">

 but I resolve it by remove this line form this file  [ https://www.programsgulf.com/](https://www.programsgulf.com/)wp-content/plugins/jetpack/modules/contact-form/grunion-editor-view.php
`
if ( ! isset( $current_screen->id ) || $current_screen->base !== 'post' ) {
	return;
`

a quick fix would be to remove this code  (which would force the javascript stuff to be loaded on all the admin pages).

**Comment by nylen** [comment]
Related: #7490

**Comment by kraftbj** [comment]
I think this the same issue as #7600 as well.

**Comment by danjjohnson** [comment]
Another case of this in 624508-zen

**Comment by danjjohnson** [comment]
And another: 623561-zen (Live Composer)

**Comment by cena** [comment]
Reported in [614048-zen](https://woothemes.zendesk.com/agent/tickets/614048)

[Workaround by Black Studio TinyMCE author](https://wordpress.org/support/topic/5-2-breaks-text-and-tinymce-widgets/#post-9379121)

**Comment by kraftbj** [comment]
To add to the impacted plugins, VIP Liveblogging plugin.

**Comment by cena** [comment]
627427-zen

**Comment by danjjohnson** [comment]
Black Studio Tiny MCE plugin: https://github.com/Automattic/jetpack/issues/7573

**Comment by tyxla** [comment]
I think a better temp workaround would be to not load any grunion scripts/styles, includng tinyMCE buttons, see the latest revision of this gist for how this can be done: https://gist.github.com/tyxla/1ff7abb1ba484ee25200a41e1df4d0c8/revisions

**Comment by lschuyler** [comment]
615710-zen - Reporting this issue with Visual Composer

**Comment by georgestephanis** [comment]
@danjjohnson @tyxla: Simplest workaround for users will be to just install this plugin --

https://github.com/georgestephanis/disable-grunion-editor-view

**Comment by tyxla** [comment]
Nice one @georgestephanis. That'll probably be the case for most of the users.

Still, in case folks want to use the contact form editor, they'll probably need to go with the other workaround, which doesn't fully disable it, but just improves it to not load its scripts unless necessary.

**Comment by NicoleA** [comment]
I've added the filter but it didn't seem to solve the problem for me. I see a fix is moving along, and I thank you for that.

**Comment by lamdayap** [comment]
Reported here 639661-zen conflicting with event espresso plugin

**Comment by lamdayap** [comment]
adding 660475-zen - so we can keep track of users to notify after the fix is shipped.

**Comment by lamdayap** [comment]
660598-zen

**Comment by robertharm** [comment]
Any idea when a fix/new release will be shipped? this issues is breaking a core functionality of our plugins (see #7600 reported about a month ago) and we fear that we will are likely to loose a lot of new users which do not turn to our support so that we can inform them about the available workarounds :-/

**Comment by jeherve** [comment]
@robertharm The fix was released this past Tuesday. Everything should now work. Let us know if you continue to experience issues with the current version of Jetpack.

**Comment by robertharm** [comment]
thanks - issues cannot be reproduced anymore since the jetpack update.
