### ISSUE TITLE
Jetpack 5.2.1 breaks TinyMCE editors in Leaflet Maps Marker & Maps Marker Pro

### ISSUE THREAD

**Issue by robertharm** [Automattic/jetpack#7600]
Hi,

I am the developer of the mapping plugins Leaflet Maps Marker and Maps Marker Pro.

Users reported a plugin conflict with the latest Jetpack 5.2.1: our plugins add a tinyMCE editor to marker edit pages and if Jetpack 5.2.1 is active, the visual editor breaks with the following error in the browser console: ReferenceError: grunionEditorView is not defined – caused by tinymce-plugin-form-button.js:7:5

It seems other plugin developers are having the same issue too, see https://wordpress.org/support/topic/5-2-breaks-text-and-tinymce-widgets/#post-9379121 for example where also a possible solution is posted:

> So a quick fix would be to remove that snippet (which would force the javascript stuff to be loaded on all the admin pages).
>A more robust fix would be to add the widget.php screen to the conditions that trigger the inclusion of the scripts, and/or provide a filter hook to allow other devs to change that behavior based on custom conditions.

A quick fix/new bugfix release would be much appreciated!

**Comment by seedprod** [comment]
Yep seeing the same in error in my plugin, or anything that uses wp_editor

**Comment by kraftbj** [comment]
@georgestephanis

**Comment by nylen** [comment]
Yep, this is a duplicate of #7598.
