### ISSUE TITLE
Social Media Icons: open link in a new tab

### ISSUE THREAD

**Issue by dromero20** [Automattic/jetpack#7601]
**Changes proposed**

Including an option for opening the social media networks in a new tab instead of redirecting visitors to the social media's site in the same one.

Requested on: 617940-t

**Comment by rantoncuadrado** [comment]
The link was for kayako ;) It's https://woothemes.zendesk.com/agent/tickets/617940

**Comment by lancewillett** [comment]
A +1 vote from @MindyPostoff 

> With the Social Icons widget, users can easily add links to their social networks, and they appear as clickable icons. It would be great if when visitors click on those links, the social network page opens in a new tab, if the user sets that option. Basically, there could be a checkbox in the widget Customizer that can be set to open in new tabs, and that would add a `target = “_blank”` element to the link.
