### ISSUE TITLE
Contact Form: editor-style.min-rtl.css fails to load

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#7608]
To repro:

1. Activate Contact Form.
2. Settings > General. Switch site lang to Hebrew.
3. Open new page editor.
4. Notice error:

`Failed to load content css: https://yourdomain.com/wp-content/plugins/jetpack/modules/contact-form/css/editor-style.min-rtl.css`

That URL 404's if you try to go directly to it.

615115-zen and repro'ed on my sandbox site

**Comment by codestor4** [comment]
627355-zen

someone has suggested a temporary fix here - 
https://wordpress.org/support/topic/failed-to-load-content-css-style-min-rtl-css/

> I had a similar problem with Jetpack. For me the way to solve it was to copy the stylesheet file by using these commands on the server:

> cd /<path_to_my_blog>/wp-content/plugins/jetpack/modules/contact-form/css/
sudo cp editor-style-rtl.min.css editor-style.min-rtl.css

**Comment by bisko** [comment]
Also reported in 631573-zen

**Comment by codestor4** [comment]
633034-zen

**Comment by 007me** [comment]
any expected time for solution?

**Comment by csonnek** [comment]
Also in 633828-zen

**Comment by bisko** [comment]
And in 636697-zen

**Comment by cecoates** [comment]
597134-hc as well.

**Comment by X901** [comment]
Any solution ?

**Comment by lamdayap** [comment]
reported here: https://wordpress.org/support/topic/upgrade-causes-editor-errors/

**Comment by lamdayap** [comment]
reported here: https://wordpress.org/support/topic/failed-to-load-content-css-editor-style-min-rtl-css-2/

**Comment by jamilabreu** [comment]
Reported: https://woothemes.zendesk.com/agent/tickets/665794

**Comment by chaitanyamsv** [comment]
Reported in 624666-hc

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/rtl-issue-with-wp-editor/
