### ISSUE TITLE
Contact Form: Form added to post when Yoast "Focus Keyword" is added

### ISSUE THREAD

**Issue by seejacobscott** [Automattic/jetpack#7610]
Originally reported here: 620933-zen, I'm able to reproduce on a test site. 

When creating a new post or editing an existing one, with Yoast active, if you add a "Focus Keyword" in Yoast it adds a default contact form to the post: 

Steps to reproduce: 
1. Have a site with JP 5.2+
2. Have Yoast installed and active
3. Create new post, add a Focus Keyword from the Yoast options below
4. See that Contact form is added to the post content. 

Gif capture of this occurring: 
![yoast-contact form weirdness](https://user-images.githubusercontent.com/16127063/29090012-e4c96868-7c43-11e7-8dd2-4b3cc178dfbc.gif)

**Comment by cturner24** [comment]
I am developing a site for a client and have run into this same issue.  Is there a solution yet to this bug?

**Comment by jeherve** [comment]
> Is there a solution yet to this bug?

Unfortunately not. Until this is fixed, I would recommend that you deactivate the new Jetpack Contact Form interface like so:
https://github.com/georgestephanis/disable-grunion-editor-view

**Comment by georgestephanis** [comment]
This is ... interesting.

Does it still happen if you're in Text mode, instead of the Visual editor?

**Comment by georgestephanis** [comment]
So, tested it and confirmed that hitting enter in the field does trigger insertion of a contact form, even in quicktags, non-tiny-mce mode.

**Comment by georgestephanis** [comment]
Oh, so that's interesting.  On Yoast's `#yoast_wpseo_focuskw_text_input` input, if you hit enter on it, it submits the entire post form and does a page reload if you don't have the new grunion visual shortcode enabled.

If grunion is enabled, it just inserts the form instead.

I'm not 100% sure why it's resulting in adding a form  to the post yet, but my first thought is that I'll check with the Yoast folks if it's intended that they don't have an event catcher to handle `enter` keystrokes in that input field.

**Comment by cturner24** [comment]
Interesting.  We are doing everything from the visual builder.  I'm not sure I even know how to see the code you are referring to.  Thank you for pursuing this!


________________________________

**Comment by georgestephanis** [comment]
It could just be the case of a `<enter>` on any text input field that would otherwise trigger a form submission instead adds a contact form -- which feels strange, but I'm attempting to duplicate it now and confirm.

**Comment by georgestephanis** [comment]
Confirmed that this behavior duplicates with any uncaught `<enter>` on a input field on the post editor.

Yoast is irrelevant to the situation, apart from their not happening to catch enter keypresses on the input field.

Here's a simplified version of a meta box that results in the same behavior:

https://gist.github.com/georgestephanis/ebc24e80caf10cdc498468bab39da2c2

**Comment by georgestephanis** [comment]
It seems when `<enter>` is hit in the input field, a `click` event is registered on this button:

https://github.com/Automattic/jetpack/blob/a64eb3cc3b822a426dfc6c110c6e8bc214008254/modules/contact-form/grunion-editor-view.php#L33-L36

which triggers this code:

https://github.com/Automattic/jetpack/blob/a64eb3cc3b822a426dfc6c110c6e8bc214008254/modules/contact-form/js/editor-view.js#L223-L232

It seems to be that the browser parses the button as being the submit button for the form for some reason, unless the `<button>` element has a `type="button"` attribute on it -- which ours currently doesn't.  I'm making a PR right now to add it in.
