### ISSUE TITLE
Contact form CSS over-rides user-specified editor-style.css

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#7611]
Reported in 621978-zen

> After updating to Jetpack 5.2.1, the Contact Form module of Jetpack appears to 
be overwriting my chosen editor-style.css with its own file 
(/wp-content/plugins/jetpack/modules/contact-form/css/editor-style.min.css). 

Anything more to ask from the reporter? Assigning to you for now @georgestephanis :)

**Comment by georgestephanis** [comment]
It shouldn't be overriding editor style, it should be adding a secondary editor style on.  Checking ...

**Comment by richardmtl** [comment]
I have asked the user for how the register it. Meanwhile, note that they installed https://github.com/georgestephanis/disable-grunion-editor-view/archive/master.zip and it fixed it for them for now.

**Comment by silentdragoon** [comment]
Hello, user in question here! I added the following line to my theme's functions.php file:

add_editor_style('http://xsreviews.co.uk/wp-content/themes/independent-publisher/editor-style.css');

The CSS from that file is still being added, but the contact form's CSS is overwriting it... I guess I could fix this by making my CSS more specific, but I didn't need to do this previously :-)

**Comment by jeherve** [comment]
Related: #7662

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
