### ISSUE TITLE
Grunion Contact Form suggestion: make input fields and "push button" class filterable

### ISSUE THREAD

**Issue by jimmyandrade** [Automattic/jetpack#7613]
Often, my themes use a framework such as Bootstrap - which have input & button-specific classes - and it is not good to change the CSS code to change the appearance of the Grunion Contact Form elements.

So my proposal would be to make the `class` attribute of inputs and buttons filterable, so that I can add the classes I want without having to hack the WordPress core or my CSS framework.

On the inputs, this line is responsible for the class:
https://github.com/Automattic/jetpack/blob/7b8015902901fc9c3a83307208b842185647a0b0/modules/contact-form/grunion-contact-form.php#L2555

In the case of the button, we would need to change this line mainly:
https://github.com/Automattic/jetpack/blob/7b8015902901fc9c3a83307208b842185647a0b0/modules/contact-form/grunion-contact-form.php#L1548

I want to submit a PR, but I'm posting this issue here to collect opinions.

**Comment by rodruiz** [comment]
Could you add the new attribute 'submit_button_class'? 
Then:
```php
$r .= "\t\t<input type='submit' value='" . esc_attr( $form->get_attribute( 'submit_button_text' ) ) . "' class='" . esc_attr( $form->get_attribute( 'submit_button_class' ) ) . "'/>\n";
```

**Comment by jeherve** [comment]
also suggested here:
https://twitter.com/wavetree/status/941390483829547009
