### ISSUE TITLE
Image attribute texts need translator context.

### ISSUE THREAD

**Issue by zinigor** [Automattic/jetpack#7627]
Everywhere where we have image attribute texts translated, i.e. [here](https://github.com/Automattic/jetpack/blob/6fe625a8f89af89f9987f77b5668ad32503eed4f/_inc/client/components/upgrade-notice-content/index.jsx#L59), we need to add translator comments to make translations easier. Props to @yoavf for reporting this one.

**Comment by jeherve** [comment]
This was handled as part of #16481.
