### ISSUE TITLE
Likes: Do we need Open Sans?

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#7631]
In #7435 and fixed in #7446, we are using Open Sans in the Likes module. Front-end loading of a font can slow sites down (reported in https://wordpress.org/support/topic/problem-with-the-5-2-version-release/ ) so opening a ticket to determine if we want to keep Open Sans or if we're okay knocking it out for native fonts.

cc: @MichaelArestad who weighed in on the previous PR.

**Comment by jasmussen** [comment]
Ah, nice! No we don't. I think we did at the time, can't recall the details, but today I'd be inclined to go with system fonts. I.e. `-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif;`

**Comment by kraftbj** [comment]
Cool, let's burn it down. Pushed 7645.
