### ISSUE TITLE
Can't Use Special Characters (<) in Radio Buttons in Contact Form

### ISSUE THREAD

**Issue by BFTrick** [Automattic/jetpack#7632]
When you use certain symbols in your contact form it doesn't show the form. And instead shows another form (or a default form?). 

I tested it with `<`. I assume `>` might also break.

#### Steps to reproduce the issue

I made a [gif you can watch](http://d.pr/i/LVgCuW).

Here are the steps written out:

1. Have a form with radio buttons
2. One of the options should include a `<` character
3. Load the page with the form

#### What I expected

To see my form

#### What happened instead

I saw a default form or another form on my site

**Comment by BFTrick** [comment]
I believe this has been taken care of. Can someone confirm and then close the issue?

**Comment by jeherve** [comment]
I can't seem to reproduce the issue anymore, so it does indeed seem to be fixed. Closing.

Thank you!
