### ISSUE TITLE
Can't Use Commas in Radio Button Options in Contact Form

### ISSUE THREAD

**Issue by BFTrick** [Automattic/jetpack#7633]
#### Steps to reproduce the issue

![jetpack-contact-forms-commas-bug](https://user-images.githubusercontent.com/1065372/29293423-540e87bc-8108-11e7-818e-a4c92be55154.gif)

1. Create a form with radio buttons
2. Create an option with a comma. Such as `$1,000`
3. Click `Update Form`
4. View the form (on the backend) 

#### What I expected

To see the option that I set earlier (`$1,000`)

#### What happened instead

My option get's split on the comma. So I see `$1` in on option and `000` in the other.

See the gif I created.

#### What should change

Either prevent users from using commas & display a helpful error message.

Or allow users to use commas (this seems like the better option by far) and encode the commas so they don't mess up the shortcode.

**Comment by BFTrick** [comment]
This is still an issue with the latest version of Jetpack. Can anyone look into this?

**Comment by jeherve** [comment]
Worth noting that this applies to both the form block and the form shortcode.

> Can anyone look into this?

We'll update this issue when we start working on this 👍

**Comment by BFTrick** [comment]
Will this be looked into? At a glance it seems like a pretty easy bug to fix.

**Comment by jeherve** [comment]
@BFTrick We're not working on the contact form at the moment, but whenever we do we'll comment here!

**Comment by BFTrick** [comment]
> We're not working on the contact form at the moment

Does that mean you're not planning on working on the contact form for the foreseeable future (until priorities change)?

**Comment by jeherve** [comment]
We're just not touching this specific part of Jetpack right now, but we'll most likely come back for another iteration in the future. I just don't have any ETA for that right now.

**Comment by catrymer** [comment]
I got a report of this from a user in #16055886-hc

**Comment by thesacredpath** [comment]
Another report from a user in #12984910-hc

**Comment by susanjanec** [comment]
Another report from a user in 19330716-hc

**Comment by scosgro** [comment]
Another request for an update on this in 19361724hc

**Comment by ryelle** [comment]
This is also an issue in the select input, as reported at https://github.com/WordPress/wordcamp.org/issues/418 / https://github.com/WordPress/gutenberg/issues/21356

**Comment by caimin-j** [comment]
I came across a new report of this today ( 3143860-zen ). A comma is not only disappearing, but adding a new line:

<img width="302" alt="Screenshot 2020-07-15 at 14 20 32" src="https://user-images.githubusercontent.com/37620825/87550151-a5fe5200-c6a6-11ea-83fa-9a13a30b4dea.png">

<img width="314" alt="Screenshot 2020-07-15 at 14 19 28" src="https://user-images.githubusercontent.com/37620825/87550184-aeef2380-c6a6-11ea-8052-d960ac0885d6.png">

**Comment by BFTrick** [comment]
This bug has been active for 3 years. Can someone look into it? It's probably a few lines to properly encode a comma.

**Comment by liviopv** [comment]
New report on 23505699-hc

![Screenshot](https://d.pr/i/Ri2y5O+)
Screenshot: https://d.pr/i/Ri2y5O
