### ISSUE TITLE
Contact Form: Unique email titles

### ISSUE THREAD

**Issue by scottsweb** [Automattic/jetpack#7638]
#### Steps to reproduce the issue

Have multiple people fill out the contact form on the same day. In certain email clients (Gmail for example) the messages will be grouped due to them all having the same title. 

If the enquiries are for business purposes it is sub-optimal having unrelated enquiries grouped together.

This behaviour can be changed within the email client but it is often desired behaviour to have emails grouped based on the title.

#### What I expected

Emails from unrelated parties to appear as separate threads in an email client inbox.

#### What happened instead

Emails from unrelated parties were grouped together.

#### Possible solution

Ideally a unique identifier would be added to each email title (a timestamp, first name or hash) ideally filterable and with the ability to use data from the submitted form.

**Comment by jeherve** [comment]
> Ideally a unique identifier would be added to each email title (a timestamp, first name or hash) ideally filterable and with the ability to use data from the submitted form.

This is already possible as explained here:
https://jetpack.com/support/contact-form/#customize-subject

The screenshots need to be updated though. I added that to our to-do list.

**Comment by scottsweb** [comment]
TIL! Thanks for the info.
