### ISSUE TITLE
Twitter Sharing Doesn't Work (Account Suspended)

### ISSUE THREAD

**Issue by nabsul** [Automattic/jetpack#7639]
I can't share to twitter from the post view. The AddToAny plugin works fine, so it's not that my account is suspended.

![image](https://user-images.githubusercontent.com/11143071/29326130-3b1dfce6-819f-11e7-89a7-3b271186114d.png)

#### Steps to reproduce the issue

- Enable sharing buttions
- Open a blog post
- Try to share it on twitter

#### What I expected

- Not an account suspended message (I checked, my account is not suspended)

#### What happened instead

- I get an account suspended message

**Comment by eliorivero** [comment]
I was able to share normally from my post
https://elio.blog/2017/06/the-colorful-nicaragua/

**Comment by nabsul** [comment]
I wonder if it has to do with the fact that I've disconnected Jetpack from my twitter account? I decided that I wanted to use the share feature but not the publicize feature.

**Comment by eliorivero** [comment]
Nope. Unlike Publicize, Sharing doesn't need that connection.

**Comment by nabsul** [comment]
Well, I'm glad it's at least not broken for everyone. Could you try sharing via twitter at this link:

https://nabeel.us/2017/08/11/instrumenting-php/

**Comment by eliorivero** [comment]
Yeah, it's not working. You're sharing through this account
https://twitter.com/nibbletz
which is suspended. This is the request to Twitter:
```
https://twitter.com/intent/tweet?via=nibbletz&text=Instrumenting%20PHP%3A%20A%20Minimalist%20Approach&url=https%3A%2F%2Fnabeel.us%2F2017%2F08%2F11%2Finstrumenting-php%2F
```
Closing this now since that account is indeed suspended and that's the root of this issue.

**Comment by nabsul** [comment]
Why is it sharing via nibbletz? I'm logged in as nabsul.

**Comment by kraftbj** [comment]
The `via` attribute is added to the tweet at the end, e.g. "title of the post [link] via @[user]". This can be adjusted via Settings->Sharing within wp-admin.
