### ISSUE TITLE
Notifications: the panel looks broken after logging out from WP.com

### ISSUE THREAD

**Issue by vindl** [Automattic/jetpack#7643]
#### Steps to reproduce the issue

1. Enable WordPress.com Toolbar on your test Jetpack site.
2. Log out of WordPress.com.
3. Open up the Notifications panel.

#### What I expected

 - We should probably shown an option here to log in again instead of spinner.

#### What happened instead

![screenshot-from-2017-07-26-15-52-30](https://user-images.githubusercontent.com/1182160/29336744-11ea864e-820f-11e7-9f35-cdcf575ccb1c.png)

**Comment by jeherve** [comment]
Closing as duplicate of #682

**Comment by baeby** [comment]
Add
