### ISSUE TITLE
Add Themes JITMS on themes 

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#7649]
We need to get rolling and add some JITMS to direct users to being able to find and use jetpack themes from the themes page within `wp-admin` for 5.3!

**For free, personal, or premium plan users.**
![jetpack-themes-free-user](https://user-images.githubusercontent.com/214813/29383483-9429138e-829e-11e7-8320-a6eb078d2905.png)

**For professional plan users.**
![jetpack-themes-pro-user](https://user-images.githubusercontent.com/214813/29383498-a34a79ac-829e-11e7-8daf-77c1eee58fe5.png)

The main difference between the two is the verbiage. Both JITMS will direct the user to their theme showcase within calypso. 

**Initial copy for free, personal, or premium plan users JITM**
Title: Looking for your Jetpack themes?
Description: Browse 100+ themes included with Jetpack at WordPress.com
CTA: Browse Jetpack themes

**Initial copy for professional plan users JITM**
Title: Looking for your Jetpack themes?
Description: Browse 200+ premium themes included with Jetpack Professional at WordPress.com
CTA: Browse Jetpack themes

(the "your" within the title is suggestive of them already having them)

Details p6TEKc-1tW-p2

cc @jessefriedman @richardmuscat & @nicoleckohler for copy

**Comment by nicoleckohler** [comment]
Copy changes:

- Don't capitalize "themes" in any instance
- Don't capitalize "premium" (unless it's the name of the plan) -- so it'd be "Browse 200+ premium themes"
- Don't capitalize "plan," and really I'd suggest dropping the word entirely. "Browse 200+ premium themes included with Jetpack Professional" sounds a bit smoother :)
- Unless we use "over at" in other CTAs re: location, I'd be in favor of changing this to simply say "at WordPress.com" -- but the rest of you would know better on this one!

**Comment by jeffgolenski** [comment]
@nicoleckohler Perfect. Thanks for the quick response! I made the changes in the PR description above. cc @withinboredom

**Comment by richardmuscat** [comment]
@jeffgolenski / @nicoleckohler -- can we split off Free from Personal/Premium and in the latter two promote an upgrade to Professional rather than the free themes?

**Comment by nicoleckohler** [comment]
Since I think the purpose of these JITMs is to let users know that the themes are available -- otherwise they're not currently visible/easily accessible within Jetpack -- an upgrade promotion wouldn't be the right fit IMO.

If we had a way to make the themes accessible outside of the JITM (maybe there is one in the works?/one I'm not aware of?) I think that'd be fine :)

**Comment by richardmuscat** [comment]
@nicoleckohler -- not sure why we would have defined the purpose of these JITMs to not sell upgrades :)

That said, we can combine them. Sending people to the theme showcase will automatically give them the option to view premium themes and upgrade if they want to use them.

So really, we should split like this:
- Professional: as @jeffgolenski originally suggested
- Free / Personal / Premium: a more combined message

**Professional plan users JITM**
Title: _Looking for your Jetpack themes?_
Description: _Use any of the 200+ premium WordPress themes included with Jetpack Professional._
CTA: _Browse Jetpack Themes_

**Other plan users JITM**
Title: _Looking for your Jetpack themes?_
Description: _Use any of our free themes or upgrade for unlimited access to 200+ premium WordPress themes._
CTA: _Browse Jetpack Themes_

@withinboredom -- wfy?

**Comment by withinboredom** [comment]
Note from @beaulebens -- do not show on multi-site

**Comment by withinboredom** [comment]
Deployed in r161920-wpcom
