### ISSUE TITLE
Re-think plugin descriptions in the Repo 

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#7659]
@beaulebens suggested 

> I’d like to see some more thought go into these (plugin description in repo/plugins admin page) both, and make sure we’re tying our branding/messaging together throughout the entire product experience.

He's referring to these: 
![image](https://user-images.githubusercontent.com/7129409/29468938-420f574e-8414-11e7-8241-c028a9ebe433.png)
![image](https://user-images.githubusercontent.com/7129409/29468944-460303be-8414-11e7-9127-c8deaa8c15bc.png)

**Comment by beaulebens** [comment]
@nicoleckohler has some suggestions in #7634

**Comment by jeherve** [comment]
Fixed in #7715
