### ISSUE TITLE
Make the stats config more visible

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#766]
Right now to get to the stats configuration page you need to 
go to Jetpack -> Settings -> click on the config link (that is only visible when you are hovering over the stats). This makes the settings page really hard to find. I knew about them but didn't know about the config link. The only way I found it was by looking at the code. 

I propose that we add a link on the stats page to the stats settings or even remove the stats settings page. Decisions, not Options.

**Comment by kraftbj** [comment]
All of the modules with settings have a config link, some only via that link (SSO another). Tagging for design feedback.

**Comment by jeherve** [comment]
This was fixed in cb5404e96e040e152e7b97122c857d2c47a76f09
