### ISSUE TITLE
Contact Form: System Fonts set aggressively

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#7662]
The body selector used here https://github.com/Automattic/jetpack/blob/master/modules/contact-form/css/editor-inline-editing-style.css#L10 can impact other editor CSS being loaded by the theme.

Is there a more restrictive selector that we can use instead?

Reported in 634819-zen

**Comment by zinigor** [comment]
Can you think of an example of a theme that might get harmed by that? Usually these things are handled by theme reset stylesheets, AFAIK, since `body` is a pretty low-priority selector and will be overridden by any class selector.

**Comment by kraftbj** [comment]
I'm asking the developer who wrote into support for an example.

Notable though, if there is no editor style sheet, the Jetpack Contact Form will override the TinyMCE defaults, changing the editor view for all text, so we should fix that.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
