### ISSUE TITLE
Shortcodes: Several not working, crashes post loading

### ISSUE THREAD

**Issue by bwilbur1** [Automattic/jetpack#7663]
Hello everyone. I am having an issue using the shortcodes included with JetPack. Several of the shortcodes are working as expected (e.g. YouTube, contact form), but other shortcodes (e.g. recipe, quiz) refuse to display. When one fails to display, it appears to break the page loading - no comments, footer, or anything after the post content (view source, cuts off at <div class="entry-content">). I reverted to the default Twenty Seventeen theme, and deactivated all other plugins and that did not fix anything.

For example, I am using the recipe shortcode directly from the documentation. I am testing this is in an empty (other than the code below) post:

```
[recipe title="Summer Pasta with Basil, Tomatoes and Cheese" servings="4-6" time="2hr 30mins" difficulty="easy" image="https://en-support.files.wordpress.com/2014/01/food-dinner-pasta-broccoli.jpg" description="A fresh, light, Italian-inspired pasta recipe perfect for a late summer dinner."]

Put your recipe here. Tip: use ordered and unordered lists, headings, images, and links to improve the look of your recipe. You can also use special tags to format notes, ingredients, and directions.

[recipe-notes]
Credit: allrecipes.com
[/recipe-notes] [recipe-ingredients]
- 2 pounds vine ripened tomatoes
- 3 cloves garlic
- 1/2 cup chopped fresh basil
[/recipe-ingredients] [recipe-directions]
1. In a medium bowl, toss together tomatoes, garlic, basil, mint, salt and black pepper.
2. Cook and drain pasta.
3. Mix together.
[/recipe-directions]
[/recipe]

```

Any advice? Thanks!

**Comment by kraftbj** [comment]
Can you access your server's error logs and include any fatal errors here? From the description, it sounds like something on the server is fataling, resulting in the remainder of the page failing to render.

**Comment by bwilbur1** [comment]
Sorry for the delayed reply. I am getting this error:

**Comment by bwilbur1** [comment]
Just found my issue - didn't have php-xml installed. Thanks for the help!
