### ISSUE TITLE
Jumpstart: Dismiss button could be made more obvious

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#7666]
#### Steps to reproduce the issue
1. Install Jetpack on a new site that has never been connected before.
2. Connect Jetpack to WordPress.com.
3. Navigate back to /wp-admin/ and [notice](http://cld.wthms.co/LTjEFk) how far away the dismiss button is on the Jumpstart CTA

![screen shot 2017-08-18 at 11 57 22](https://user-images.githubusercontent.com/831377/29534819-74f5b356-8685-11e7-945c-efdfdd6290a0.jpg)

#### What I expected
The `x` to be more noticeable.

#### What happened instead
It's practically hidden.

I do understand that we want users to use these features as they're our best representation of what Jetpack offers, however, I think there are cases to be made that some (many?) users may already know what they do and don't want and prefer to skip that Jumpstart step. We should make it easier for them to do that.

**Comment by beaulebens** [comment]
Let's just move the [x] to the top-right corner of the white box, like we did in #8697
