### ISSUE TITLE
Masterbar: better override for when a user profile hides the WP toolbar

### ISSUE THREAD

**Issue by lancewillett** [Automattic/jetpack#7667]
Core WP has a filter for `show_admin_bar` to override the various reasons why it'd be hidden. One reason is in their user profile an author might have toggled that option off.

URL such as:
`example.com/wp-admin/profile.php`

<img width="1093" alt="screen shot 2017-08-21 at 15 52 29" src="https://user-images.githubusercontent.com/66797/29541425-c15b6b98-8688-11e7-918d-4ba3e967ca7f.png">

Where you'd toggle of the core WP toolbar by unchecking "Show Toolbar when viewing site" — which saves in your user meta value as `false` for `show_admin_bar_front`.

When Jetpack's option is on for "Enable the WordPress.com toolbar" and loading the Masterbar module, we should override that option so even if the user turned off that option, the WP.com masterbar will show up anyway.

<img width="841" alt="screen shot 2017-08-21 at 15 52 43" src="https://user-images.githubusercontent.com/66797/29541429-cad533ca-8688-11e7-9cd9-4ea446de27a0.png">

(Found via dogfooding moving a site from WP.com to Jetpack, and my user profile info that came over had `show_admin_bar_front` set to false.)

**Comment by vindl** [comment]
@lancewillett After giving this some more thought, I don't think we should override this option in Masterbar. Maybe there is a legitimate need for users to display this bar only in `wp-admin` and not on site's front end.

Looking at it from AT perspective - I'd expect my dotcom settings to be preserved after installing a plugin for example. I think it would be weird and look like a bug if the Masterbar, that was removed from front end on purpose, suddenly reappeared after AT.

**Comment by lancewillett** [comment]
@vindl For AT: we don't honor this setting any more on WP.com, so it's the opposite effect — you'd hide something that isn't hidden before the transfer.

**Comment by vindl** [comment]
I see, in that case we can maybe honor it for Jetpack sites in general, and override it just for AT?

**Comment by lancewillett** [comment]
Yes, that's OK with me.

**Comment by vindl** [comment]
@lancewillett two occurrences of what seems to be the same issue were also reported in p8yzl4-yN-p2. Since there were no similar reports of this before, I wonder if there was some recent change in AT for transferring these meta fields and options that caused this to appear recently (and possibly some other issues that are not as noticeable and might seem unrelated).

**Comment by lancewillett** [comment]
@vindl Yes, it could be related to user age on WP.com also (if they set that option many years ago before it was deprecated.

**Comment by vindl** [comment]
> it could be related to user age on WP.com also (if they set that option many years ago before it was deprecated.

Yes, that's the most likely explanation that was the basis of proposed fix. I just wanted to present another less likely option. :) I'll try to find users for sites in question and see if they are indeed old ones as we suspect.
