### ISSUE TITLE
Admin: JS Error while using RTL locale 

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#767]
When the local is set to ru_RU, the following errors are reported in the console:
`Uncaught SyntaxError: Unexpected token ; admin.php?page=jetpack_modules:558`
`Uncaught TypeError: Cannot read property 'modules' of undefined jetpack-modules.js:137`

The first error is found at:
`<script type='text/javascript'>
/* <![CDATA[ */
var jetpackModulesData = ;
/* ]]> */
</script>`

Confirmed on `master` reported in 1871775-t.

**Comment by kraftbj** [comment]
Claimed fix by 1437, needs testing.

**Comment by jeherve** [comment]
I can't seem to reproduce the issue anymore. Closing.
