### ISSUE TITLE
Reconnecting non-master user after unlinking account displays plans page and error

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#7687]
#### Steps to reproduce the issue

- On a connected Jetpack site, SSO-login as any non-master user
- On the Jetpack Dashboard, unlink your account by clicking "Unlink me from WordPress.com"
- Click "Link to WordPress.com" to reconnect
- Click "Approve" to approve the connection
- Am taken to plans selection page with error "You don't have any WordPress sites yet"

THEN

- disconnect, reconnect again
- this time taken to plans page at https://wordpress.com/plans/my-plan/(mysiteurl), which shows actual plan of site, all good.

#### What I expected

- Taken back to wp-admin, fully logged-in, on first attempt

#### What happened instead

Ended up on `https://wordpress.com/jetpack/connect/plans/(mysiteurl)` with this error

<img width="642" alt="no-wp-sites-yet" src="https://user-images.githubusercontent.com/51896/29682805-2976b702-88c1-11e7-98d6-500c43c5eed7.png">

**Comment by jeherve** [comment]
This seems to be fixed now. closing.
