### ISSUE TITLE
Adjust copy in Jumpstart

### ISSUE THREAD

**Issue by nicoleckohler** [Automattic/jetpack#7689]
As referenced in #7682 @dereksmart 

Copy edits for the rest of the Jumpstart features:

- **Sharing**: Start this description with the word "Add"; add a comma after "Facebook"
- **Subscriptions**: Remove "you can display" (think this goes without saying).
- **Carousel**: Change "navigable" to "browsable."
- **Photon**: Remove "Mirrors and" (just start with "Serves your...").
- **Monitor**: Change description to: "Receive immediate email alerts if your site goes down, no matter when it happens."
- **Related Posts**: "Posts" in the title should be capitalized; change "on" to "with" in the description ("engaged _with_ your blog")
- **SEO Tools**: Change description to: "Get better results on search engines with automatically generated XML sitemaps." The SEO tools we provide for free (sitemaps) don't affect social media results and I'd prefer to be clearer by specifying what is offered vs. saying SEO and having users potentially expect the Professional tools. :)

**Comment by jeherve** [comment]
This can now be closed since we have no Jumpstart modal anymore.
