### ISSUE TITLE
Shortcode Embeds: Instagram oEmbeds not displaying properly in wp-admin editor

### ISSUE THREAD

**Issue by emrikol** [Automattic/jetpack#7690]
#### Steps to reproduce the issue

Enable "Shortcode Embeds" and add an Instagram oEmbed (ex: `https://www.instagram.com/p/BYMDTB5g95n/`)

#### What I expected

I expect to see the rendered embed in the editor:

![image](https://user-images.githubusercontent.com/3060583/29690054-6492eaa4-88f3-11e7-814e-de9d095648d6.png)

#### What happened instead

Instead, I see a broken Instagram embed:

![image](https://user-images.githubusercontent.com/3060583/29690085-87cb089e-88f3-11e7-88d1-70cab1266e5f.png)

This can also be fixed by removing the Jetpack embed provider and re-adding the core provider, in a pinch:

```
add_action( 'init', 'add_core_oembed_provider' );
function add_core_oembed_provider() {
    wp_embed_unregister_handler( 'jetpack_instagram' );
    wp_oembed_add_provider( '#https?://(www\.)?instagr(\.am|am\.com)/p/.*#i', 'https://api.instagram.com/oembed', true );
}
```

**Comment by BrookeDot** [comment]
We are also seeing this with WordPress 5.3 with the Block Editor enabled. As with WP-Admin disabling `jetpack_instagram` and re-enabling core's provider does workaround the problem.

**Comment by jeherve** [comment]
Good point. I'll close this issue in favor of #9331, where we track the issue within the Block editor.
