### ISSUE TITLE
Stats: Nonce Error When Plugin Uses Stronger Password

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/jetpack#7701]
This user identified this issue with the ActiveMember360 plugin, but it would apply to any plugin that replicates the behavior here.

#### Steps to reproduce the issue
1. Install and Activate the ActiveMember360 plugin (link in the ticket).
2. Go to Jetpack -> Site Stats

The error message is:

```
We were unable to get your stats just now. Please reload this page to try again. If this error persists, please contact support. In your report please include the information below.

	User Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"
	Page URL: "https://tracyspress.net/wp-admin/admin.php?page=stats&noheader"
	API URL: "https://dashboard.wordpress.com/wp-admin/index.php?noheader=true&proxy&page=stats&blog=122094231&charset=UTF-8&color=fresh&ssl=1&j=1:5.2.1&main_chart_only"
invalid_signature: "The required "nonce" parameter is malformed."
```

The user was able to do some digging and found this:

```
The issue is that when creating the nonce, Jetpack calls wp_generate_password.

In class.jetpack-client.php line 64, there are these lines:

if( function_exists( 'wp_generate_password' ) ) { 
$nonce = wp_generate_password( 10, false ); 
} else { 
$nonce = substr( sha1( rand( 0, 1000000 ) ), 0, 10); 
}

The issue is that Wordpress uses the filter random_password in the wp_generate_password function, and I have a plugin, ActiveMember360, which uses the random_password filter to return a stronger password, including special characters.

And of course, Jetpack checks to make sure there are no special characters in the nonce, which that check will fail.
```

For now, he's made sha1 default, so it will be fine until the next update. 

Can we give him an option of which method to use, or even a configuration constant, or a filter, or anything else like that that would give the choice to use the sha1 method of generating the nonce instead of wp_generate_password?

Internal ref: 639503-zen

**Comment by butlerblog** [comment]
As already noted, this creates a problem for any "password" plugin that filters the wp_generate_password() result and ends up creating a value that is not valid as a nonce.  

But why is `wp_generate_password()` being used for nonce generation instead of using `wp_create_nonce()`?  It seems like the wrong function is being used here.

Changing the use of `wp_generate_password()` to `wp_create_nonce()` solved the issue for me.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
