### ISSUE TITLE
Hook for staging sites?

### ISSUE THREAD

**Issue by blobaugh** [Automattic/jetpack#771]
More and more hosts (and plugins) are offering one click staging sites. Jetpack has issues with the database being direct copied to the staging site due to how the tokens are stored (See http://jetpack.me/2014/06/25/top-5-best-practices-when-using-jetpack-on-client-websites/#5-staging). This is a common issue with plugins requiring tokens for 3rd party services.

I want to open discussion on how we can provide hooks for the hosts to help with staging, and how technically possible that is.

Currently I am seeing a couple things
* Have an action that disconnects Jetpack by erasing the tokens from the db (to prevent the production site disconnect) and puts up a big banner letting the site admin know to reconnect. This could fire from an mu-plugin on the staging site itself
* If the to staging script loads WP we could toss in a hook the host could tap into.

The first idea seems more feasible. What are thoughts on a good design for this?

**Comment by dereksmart** [comment]
Great idea, and should be added to the new <a href="https://github.com/Automattic/jetpack/blob/master/class.jetpack.php#L5722">staging site method<a/>, which stops syncing from happening.  Marking to get this into 3.8.

**Comment by kraftbj** [comment]
I'm going to close this to defer to the work being done and already done on the IDC prompt and is_staging_site.
