### ISSUE TITLE
Contact Form promo shows even when disabled

### ISSUE THREAD

**Issue by tomjn** [Automattic/jetpack#7714]
#### Steps to reproduce the issue

Disable the contact form module, then update Jetpack. Then visit the Jetpack dashboard in WP Admin to see the following screen:

<img width="327" alt="screen shot 2017-08-29 at 21 59 24" src="https://user-images.githubusercontent.com/58855/29843922-7774a0c0-8d05-11e7-9db7-ea0b3ab39adf.png">

Then click try it now

#### What I expected

To either not see this as i have that module/feature disabled, or to have the module enabled temporarily so that I can test it out when I clicked the button. Perhaps an activation button instead

#### What happened instead

I was sent to create a new post where the advertised feature was not present

**Comment by jeherve** [comment]
Closing as this splash page has now been updated.
