### ISSUE TITLE
VaultPress: add notes to existing backups

### ISSUE THREAD

**Issue by mzakariya** [Automattic/jetpack#7743]
#### Steps to reproduce the issue
- Something notable happens around the time VaultPress takes a backup of my site
   - host downtime
   - major site changes
   - something about this backup is critically important, noteworthy

#### What I expected
- I want the ability to add notes to a specific VaultPress backup

#### What happened instead
- I cannot do this 

Internal note: 666313-zen

**Comment by jeherve** [comment]
@mzakariya Could you reopen this issue in the Calypso repo, since this option would be added to the Activity Log interface if it were implemented.

Thank you!
