### ISSUE TITLE
Stats Activity Doesn't Always Find a User

### ISSUE THREAD

**Issue by Ipstenu** [Automattic/jetpack#7749]
I'm not sure how else to explain this so I'm including a picture:

![screen shot 2017-09-05 at 3 16 23 pm](https://user-images.githubusercontent.com/807903/30085920-973ae016-924d-11e7-94ff-087cfe700e85.png)

Starting from the bottom up, we have a scheduled post, a regular post I updated, a WP update, and then two spam comments. All of those should have some personal indicator, but the scheduled post is the big one.

#### Steps to reproduce the issue

Schedule a post to publish. Once it's done, check the activity.

#### What I expected

The activity would be either "Mika's scheduled post was published..." or "A scheduled post was published."

#### What happened instead

I got a headless, incomplete message.

**Comment by philipjohn** [comment]
I'm also seeing this on a Jetpack site, with just the comments missing an author. The dates don't quite match up with the dates in wp-admin but it looks like the author info is all there.

**Comment by enejb** [comment]
Thanks for the bug report.

**Comment by jeherve** [comment]
Closing this for now as we are tracking it internally.

@Ipstenu I'll get back to you here as soon as the problem gets fixed.

**Comment by jeherve** [comment]
This should now be fixed. All existing activity won't be fixed, but all new one should be displayed properly.
