### ISSUE TITLE
Spam Comments Listed as Awaiting Approval in Activity Log

### ISSUE THREAD

**Issue by macmanx2** [Automattic/jetpack#7750]
Comments which were marked as spam immediately by Akismet 3.3.4 are listed in the Activity Log as awaiting approval under Jetpack 5.3.

I can confirm this problem on 3 separate sites across 2 different hosting providers, all running WordPress 4.8.1, Jetpack 5.3, Akismet 3.3.4, under PHP 7.0.14 and 7.0.23.

In the below screenshot, all of the following comments were immediately marked as spam by Akismet on https://macmanx.com

<img width="1046" alt="screen shot 2017-09-05 at 3 18 05 pm" src="https://user-images.githubusercontent.com/4856235/30086014-064b72ae-924e-11e7-84c2-deeb636bb6e9.png">

**Comment by enejb** [comment]
Thanks for the bug report.

**Comment by jeherve** [comment]
Closing this as this is now tracked internally.
