### ISSUE TITLE
Social Menu & Social Media Icons: Add Behance support

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#7758]
> Add behance icon please 😃
-- https://github.com/Automattic/jetpack/pull/2230#issuecomment-309546616

Related: #2230 #7318

**Comment by rickcurran** [comment]
Hi, a Behance icon appears to have been added so it seems like this issue could be closed now.

**Comment by jeherve** [comment]
You're right, we do have Behance now, this was added in https://github.com/Automattic/social-logos/pull/26

This can now be closed.
