### ISSUE TITLE
Schedule post social sharing for Twitter/Facebook not working

### ISSUE THREAD

**Issue by sgwatgit** [Automattic/jetpack#7762]
#### Steps to reproduce the issue
Set up Sharing for Facebook and Twitter for all user accounts (Shared) as outlined here
https://jetpack.com/support/publicize/twitter/
and here
https://jetpack.com/support/publicize/twitter/#connect-twitter

#### What I expected
Scheduled post with Facebook and Twitter checked under Publicize would get posted to both Facebook and Twitter once published to my site.

#### What happened instead
Post is published once publish date/time arrives but nothing is posted via "WordPress.com by Automattic" app on Twitter or Facebook.

Posts that I publish immediately (not scheduled) result in content being published to Facebook and Twitter correctly - it seems scheduled posts are having the issues.

Both Social media accounts are 'shared' (Settings -> Sharing -> (Shared) appears next to both accounts).

I went through the process of removing the accounts, deleting cookies, revoking access to the Apps, re-connecting the accounts and then re-scheduling a post. Immediately published posts work as expected, scheduled posts do not.

My web host has my site configured to use linux cron instead of wp-cron, but this configuration has been in place for several months while the issue I'm seeing has been occurring for only a few days. I tried updating to `v5.3` in hopes that it would resolve my issue, but it did not.

I'm happy to try any suggestions and I will also be questioning my web host to see if they made any changes recently.

Thanks!

**Comment by kraftbj** [comment]
Hi @sgwatgit 

The systems are running fine, so this is likely an issue with your specific site. Can you contact us via https://jetpack.com/contact-support/ if you have a paid plan or via https://wordpress.org/support/plugin/jetpack if you do not, and please include your site's URL.

Thanks!
