### ISSUE TITLE
Gutenberg - Publicize integration

### ISSUE THREAD

**Issue by jonathanbossenger** [Automattic/jetpack#7766]
I know its early days yet, but at the moment Jetpack Publicize is not supported on Gutenberg. So one has to write the post in Gutenberg and then publish it in the regular edit Post view to have it shared socially.

It would be awesome if by the time Gutenberg is shipped with core this is implemented for Gutenberg. So I'm just raising it now.

**Comment by kraftbj** [comment]
We haven't started exploring this yet, but we absolutely will before it is shipped in Core.

**Comment by jonathanbossenger** [comment]
100% @kraftbj just doing what I can to help test Gutenberg ;-) exciting times ahead.

**Comment by jeherve** [comment]
Closing this issue in favor of #9039, since the newer issue includes more info.
