### ISSUE TITLE
Jetpack Adds Data Attributes to Page/Post Images When Carousel Is Enabled

### ISSUE THREAD

**Issue by pmciano** [Automattic/jetpack#7771]
If Carousel is enabled, Jetpack adds data attributes to page and post images, regardless of whether or not the images are part of a Carousel Gallery. I have replicated the issue using Twenty Seventeen `1.3` and Jetpack `5.3`.

![Data Attributes](https://www.evernote.com/l/AtiNAPc68XpJR5Cs2AOLwXr4fnnkVvWW3jwB/image.png)

As per @jeherve, this appears to be a bug.

3255391-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/carousel-meta-information-removal/

**Comment by jeherve** [comment]
Closing as duplicate of #13428
