### ISSUE TITLE
Custom CSS: Re-use CodeMirror bundled in Core and the new code editor API

### ISSUE THREAD

**Issue by westonruter** [Automattic/jetpack#7776]
CodeMirror has just landed in WordPress 4.9-alpha: https://core.trac.wordpress.org/changeset/41376

The Custom CSS extensions in Jetpack should be updated to build on top of the new code editor APIs rather than include separate copies.

For previous Custom CSS work which moved the feature into the Customizer with WordPress 4.7, see #5539.

/cc @georgestephanis

**Comment by westonruter** [comment]
I need to improve the extensibility of the control in core first.

**Comment by westonruter** [comment]
As noted by @BinaryMoon, Jetpack and core's Custom CSS currently conflict and cause an error: https://twitter.com/binarymoon/status/909028797504217088

This is not the fault of Jetpack but it is the fault of core not adding the code editor to the control in a way that makes it extensible. I'm going to introduce a `WP_Customize_Code_Editor_Control` which Jetpack can then extend. See https://core.trac.wordpress.org/ticket/41897

**Comment by westonruter** [comment]
I've opened an initial pull request for core to introduce `WP_Customize_Code_Editor_Control` in PHP and `wp.customize.CodeEditorControl` in JS. I'll try adding a PR to get Jetpack to make use of them when available.

Please review: https://github.com/xwp/wordpress-develop/pull/257

**Comment by georgestephanis** [comment]
Resolved in #8028
