### ISSUE TITLE
Publicize: Posts with Featured Images Publicize without a Post Title

### ISSUE THREAD

**Issue by sixhours** [Automattic/jetpack#7785]
#### Steps to reproduce the issue

1) Publish a post with some content, title, and without a Featured Image and Publicize it to your Facebook account
2) Publish a second post with some content, title, and with a Featured Image and Publicize it to your Facebook account.

Note that in the first case, both post title and excerpt are displayed on Facebook, but in the second case, only the post excerpt and the Featured Image are displayed.

#### What I expected

For the second post to show the excerpt, post title, and the Featured Image.

#### What happened instead

The second post shows the excerpt and the Featured Image, but no post title.

In both cases, the Facebook debugger shows the title information is there, but it doesn't display on the Facebook page itself. Is this display controlled by Facebook, or something we can change in Publicize?

Originally reported in 678912-zen

**Comment by jeherve** [comment]
I believe that was done on purpose, as images get a special treatment when we push them to Facebook.

#261 would help customize the default behaviour for each site.
