### ISSUE TITLE
Jetpack Signature: Support X-Forwarded-Port HTTP header

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#779]
In some circumstances, when php is executing on a server behind a caching layer or another intermediate server, if the server is on a different port than the public version, the Jetpack signature will be created using the php server's port instead of the public port.

Suggest supporting the X-Forwarded-Port header as one way to handle this.

Further details in 1835697-t

**Comment by kraftbj** [comment]
@joshkoenig Long ago, but do you have any sites setup not using the constants and using `X-Forwarded` that you could help test #3402 using?

**Comment by joshkoenig** [comment]
I worked around this internally, but can probably re-break it in a test environment so see if it works.

Thanks for getting to this @kraftbj! I'll be able to take a look later this week and will report back.

**Comment by jeherve** [comment]
Fixed in #3402
