### ISSUE TITLE
SSO & Publicize should both create the WordPress.com connection

### ISSUE THREAD

**Issue by blobaugh** [Automattic/jetpack#78]
I created a new user through SSO, then I attempted to test a Publicize feature. Publicize is asking me to connect the new user account to WordPress.com. This is sort of confusing as the user should be able to connect either SSO or Publicize and have their account linked with WordPress.com.

Less clicks and less places requiring connections

**Comment by ebinnion** [comment]
SSO now relies on the regular WP.com connection.
