### ISSUE TITLE
Blog auth token

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#7813]
Users should not need to log in to wp.com in the mobile apps to access Jetpack features. We would need to figure out a protocol for the app to request an oAuth2 token from the Jetpack site, and for the site to request it from WordPress.com. This token would only allow access to the specific Jetpack site and not any other sites or account details.

The is related to p77Llu-75F-p2.

To see where the list come from see p9c7Jx-d-p2.

**Comment by jeherve** [comment]
Not sure what that is. @enejb I realize you're creating this to track things in your project, but I think it would be nice if you provided some explanations so anyone jumping in understands what the issue is about.

Thanks!

**Comment by enejb** [comment]
The is related to p77Llu-75F-p2. 

To see where the list come from see p9c7Jx-d-p2.

**Comment by elibud** [comment]
Regarding this one we should have a meeting next week once @koke is back to see if it's absolutely necessary, how it would look like, and where does it stands in our priorities. It was originally listed as high priority but I'm not 100% sure I know why.

**Comment by koke** [comment]
Edited description to add a small summary of the feature

**Comment by elibud** [comment]
We are not tackling this one as part of #betterjetpackxp It might be a good-to-have feature for some users but it's not aligned with the medium term strategy for Jetpack growth.
