### ISSUE TITLE
Jetpack setup improved experience

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#7814]

**Comment by enejb** [comment]
Related p77Llu-75F-p2

**Comment by lezama** [comment]
> Can we request a blog-only oAuth2 token to a self hosted with Jetpack via XML-RPC?

**Comment by lezama** [comment]
@elibud @koke could you explain us what do you need from us here?

**Comment by lezama** [comment]
is it something different than https://github.com/Automattic/jetpack/issues/7813?

**Comment by elibud** [comment]
Yep it's different, this one would be for the installation and setup flows that Luna will be working on.

**Comment by brbrr** [comment]
Hi @enejb @elibud.
There isn't much activity here/linked P2, so I'd like to check with you is this ticket is still up-to-date (and worth `[Pri] High`) or it might be closed/downgraded?

**Comment by designsimply** [comment]
Related p7rd6c-1nm (internal reference) - includes notes about the wpcom endpoint for Jetpack remote installs.

**Comment by elibud** [comment]
This one is ok to close, the new flow has been integrated in the apps.
