### ISSUE TITLE
Activating a theme not working for some users

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#7815]

**Comment by enejb** [comment]
Related: https://github.com/wordpress-mobile/WordPress-iOS/issues/7758

**Comment by elibud** [comment]
I've been looking into this one with @oskosk and @eliorivero, it looks like there's a 403 somewhere that should not be happening, we will have to debug it together, just ping me when someone is available to start a sandbox that I can hit from the clients.

**Comment by oskosk** [comment]
@elibud @enejb @eliorivero please, check p1HpG7-4b0-p2 as there's a probable explanation of what's happening here.

**Comment by elibud** [comment]
Fixed by @oskosk patch deployed earlier today by @lezama
