### ISSUE TITLE
Jetpack Fails to Connect with High[er] Security

### ISSUE THREAD

**Issue by expphoto** [Automattic/jetpack#7818]
#### Steps to reproduce the issue
Enable Mod_Security OR Redirect HTTP to HTTPS via .htaccess

#### What I expected
Jetpack debug to give me an A-OK with either of these or both of these enabled. To note. It works with Mod_Security OFF and no HTTP >> HTTPS redirect.

#### What happened instead
SELF:
							Array
(
    [headers] => Requests_Utility_CaseInsensitiveDictionary Object
        (
            [data:protected] => Array
                (
                    [server] => nginx
                    [date] => Wed, 20 Sep 2017 03:37:07 GMT
                    [content-type] => text/plain;charset=utf-8
                    [expires] => Wed, 11 Jan 1984 05:00:00 GMT
                    [cache-control] => no-cache, must-revalidate, max-age=60
                    [x-hacker] => Jetpack Test
                    [x-ac] => 3.bur _bur
                    [strict-transport-security] => max-age=15552000
                )

        )

    [body] => {"error":"Communication error","error_description":"We were unable to make an XML-RPC request to your website. Please make sure that XML-RPC is turned on and that Jetpack is installed, activated and connected with your WordPress.com account. If the error persists, try disconnecting and connecting Jetpack again."}
    [response] => Array
        (
            [code] => 400
            [message] => 
        )

    [cookies] => Array
        (
        )

    [filename] => 
    [http_response] => WP_HTTP_Requests_Response Object
        (
            [response:protected] => Requests_Response Object
                (
                    [body] => {"error":"Communication error","error_description":"We were unable to make an XML-RPC request to your website. Please make sure that XML-RPC is turned on and that Jetpack is installed, activated and connected with your WordPress.com account. If the error persists, try disconnecting and connecting Jetpack again."}
                    [raw] => HTTP/1.1 400 Bad Request
Server: nginx
Date: Wed, 20 Sep 2017 03:37:07 GMT
Content-Type: text/plain;charset=utf-8
Transfer-Encoding: chunked
Connection: close
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Cache-Control: no-cache, must-revalidate, max-age=60
X-hacker: Jetpack Test
X-ac: 3.bur _bur
Strict-Transport-Security: max-age=15552000

{"error":"Communication error","error_description":"We were unable to make an XML-RPC request to your website. Please make sure that XML-RPC is turned on and that Jetpack is installed, activated and connected with your WordPress.com account. If the error persists, try disconnecting and connecting Jetpack again."}
                    [headers] => Requests_Response_Headers Object
                        (
                            [data:protected] => Array
                                (
                                    [server] => Array
                                        (
                                            [0] => nginx
                                        )

                                    [date] => Array
                                        (
                                            [0] => Wed, 20 Sep 2017 03:37:07 GMT
                                        )

                                    [content-type] => Array
                                        (
                                            [0] => text/plain;charset=utf-8
                                        )

                                    [expires] => Array
                                        (
                                            [0] => Wed, 11 Jan 1984 05:00:00 GMT
                                        )

                                    [cache-control] => Array
                                        (
                                            [0] => no-cache, must-revalidate, max-age=60
                                        )

                                    [x-hacker] => Array
                                        (
                                            [0] => Jetpack Test
                                        )

                                    [x-ac] => Array
                                        (
                                            [0] => 3.bur _bur
                                        )

                                    [strict-transport-security] => Array
                                        (
                                            [0] => max-age=15552000
                                        )

                                )

                        )

                    [status_code] => 400
                    [protocol_version] => 1.1
                    [success] => 
                    [redirects] => 0
                    [url] => https://jetpack.wordpress.com/jetpack.testsite/1/?url=https://example.com/xmlrpc.php
                    [history] => Array
                        (
                        )

                    [cookies] => Requests_Cookie_Jar Object
                        (
                            [cookies:protected] => Array
                                (
                                )

                        )

                )

            [filename:protected] => 
            [data] => 
            [headers] => 
            [status] => 
        )

)

**Comment by jeherve** [comment]
Can you please use Jetpack's Debugger module to send us the full debug info about your site, so we can run some more tests? It would also help if you told us more about the mod security rules you've set up.

<ol>
<li>Go to the Jetpack page in your dashboard.</li>
<li>Click on the <strong>Debug</strong> link appearing at the bottom of the page.</li>
<li>Click the link that says <strong>"click here to contact Jetpack support."</strong></li>
<li>Fill in the description box and your name and email address.</li>
<li>Click the "Contact Support" button to send us the debug results privately. <strong>It's best not to post this information here, as it contains private details about your site.</strong></li>
</ol>
Thanks!

**Comment by JustinAntony143** [comment]
I have the same issue and i found 
Wordpress Admin panel. 
General - > Set the right Site URL if you have SSL check the url starts with https:// instead of http://
This resolved the wordpress jetpack issue of RPC

pls visit: www.sqlpublic.com
