### ISSUE TITLE
html 5 notifications

### ISSUE THREAD

**Issue by camaran** [Automattic/jetpack#7820]
You consider to add html5 notifications

**Comment by kraftbj** [comment]
Could you provide some more detail on what you'd expect to see through this enhancement?

**Comment by camaran** [comment]
this https://www.html5rocks.com/en/tutorials/notifications/quick/ for when submit new post, now i have social share, email, add this html5 notifications

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
