### ISSUE TITLE
Fatal error if gzdeflate() is undefined

### ISSUE THREAD

**Issue by seejacobscott** [Automattic/jetpack#7832]
A user recently reached out indicating they were seeing the following fatal error on multiple sites on their server: 

```
Fatal error: Call to undefined function gzdeflate() in 
/home/.../public_html/.../wp-content/plugins/jetpack/sync/class.jetpack-sync-json-deflate-array-codec.php on line 17
```

It seems we should fail a little softer here, since we seemingly can't always rely on gzdeflate being present.

**Comment by seejacobscott** [comment]
[Chat with Kraft](https://a8c.slack.com/archives/C0CMN0V97/p1506017424000030) | 694824-zen

**Comment by kraftbj** [comment]
PHP 7 needs the php7-zip libraries installed, so we can't always rely on it. We should have some kind of check and admin_notice or error out in a softer way.
