### ISSUE TITLE
VideoPress: Add shortcode attribute or option to disable sound

### ISSUE THREAD

**Issue by seejacobscott** [Automattic/jetpack#7839]
After a discussion with a suer they would like to have a video that autoplays in a large format when the page loads, but find it obnoxious with the sound autplaying right away. After doing a little digging I was unable to find a way to autodisable audio with a video plays automatically. 

It would be fantastic to add either an UI option, or a shortcode attribute that can be used to disable sound by defaut, either compeltely on a specific video, or to mute when the video loads initially.

**Comment by jeherve** [comment]
I like that idea, but since the player doesn't support this yet, that's most likely not going to happen soon since we'll need to update the player first.

**Comment by spncrb** [comment]
Noting here that Chrome no longer allows autoplay with sound, per:
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

Adding the ability to hard-mute VideoPress videos would also allow the autoplay flag to become usable again in Chrome. Right now autoplay only works in non-Chrome browsers.

**Comment by damiannep** [comment]
Request for video autoplay in 1246946-t

**Comment by jeherve** [comment]
Closing this, as the option is now available in the Video Block when using Jetpack Videos:

![image](https://user-images.githubusercontent.com/426388/76105701-be15e480-5fd5-11ea-8be3-e4140f3f6ea1.png)
