### ISSUE TITLE
i18n: language ID not being set on a new site using nb_NO

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#784]
I'm not sure exactly what the issue is; opening this to report what I've learned so far.

Testing conditions:
Start a new WordPress site using the nb localization: http://nb.wordpress.org/
Activate subscription
Subscribe to the site.

Expected:
Follow e-mail to be in nb

Actual:
Follow e-mail is in English.

When checking Settings->Reading, the correct nb language is being used in the default follow and the WPCOM site settings completely lack a lang_id setting.

If I visit Settings->Reading and simply save it without changes, the default nb langauge that was pre-filled will be used for subscription e-mails and the lang_id is set as expected.

At first glance, it appears the language ID isn't being set for a new site, at least with the nb localization.

Originally reported: http://wordpress.org/support/topic/subscription-confirmation-email-not-translated-properly

**Comment by jeherve** [comment]
Closing this in favor of #2791, which covers other languages were the language code on WordPress.org doesn't match the options available on WordPress.com.
