### ISSUE TITLE
connect to your WordPress.com receives "That site does not seem to be accessible or no longer has the Jetpack plugin installed." 

### ISSUE THREAD

**Issue by BentleyDavis** [Automattic/jetpack#7844]
#### Steps to reproduce the issue
Followed normal steps in introduction to hook of this Google Docs plugin to my wordpress site. It worked for BentleyDavis.com but not for ProTruthPledge.org . I looked through the issues on this site and tried all the ideas and none seemed to work. I confirmed that jetpack JSON API is on and the wordpress api is working. I also turned off all my other plugins and it still did not work. I turned them back on for now. Wordpress.com shows the site is hooked up properly and the jetpack plugin is having no issues. Any other suggestions?

#### What I expected
The site to show up on the list in the plugin

#### What happened instead
Got the red box saying "That site does not seem to be accessible or no longer has the Jetpack plugin installed."

**Comment by jeherve** [comment]
Can you please use Jetpack's Debugger module to send us some more information about your site?

<ol>
<li>Go to the Jetpack page in your dashboard.</li>
<li>Click on the <strong>Debug</strong> link appearing at the bottom of the page.</li>
<li>Click the link that says <strong>"click here to contact Jetpack support."</strong></li>
<li>Fill in the description box and your name and email address.</li>
<li>Click the "Contact Support" button to send us the debug results privately. <strong>It's best not to post this information on public forums, as it contains private details about your site.</strong></li>
</ol>
Thanks!

**Comment by BentleyDavis** [comment]
@jeherve Ay suggestions if the debug button doesn't work?
![image](https://user-images.githubusercontent.com/1606382/30876870-83f02c34-a2bd-11e7-814f-06b27f002826.png)

**Comment by jeherve** [comment]
Well that's odd! Could you try to deactivate Jetpack, delete it, and reinstall it from scratch?

**Comment by somprabhsharma** [comment]
Any update on this? I am also facing similar issue.

**Comment by BentleyDavis** [comment]
Agree further research (I think on a separate ticket) my domain https and http were different in the website config it the address was slightly off. You might see if there are other tickets.

**Comment by BentleyDavis** [comment]
From my solution communication "Just looking over your debug, it appears your Site url and Home url are different, with one set to https and the other set to http. Would you mind updating that so they're both the same? You can do that through your site's Dashboard > Settings."

**Comment by jeherve** [comment]
@somprabhsharma Could you send us more details about your site via this form, so we can take a closer look?
https://jetpack.com/contact-support/?rel=support

Thank you!

**Comment by iampraba** [comment]
@jeherve Can you please post the possible reason for this issue? Also, what's the solution or work around for this?

**Comment by jeherve** [comment]
@iampraba I can't really say without looking at your site; the cause and the solution will differ based on the site. 
I would recommend using the form I posted in my last comment to contact us and send us more details about your site; we'll investigate with you there.
