### ISSUE TITLE
Add support for core Gallery widget

### ISSUE THREAD

**Issue by westonruter** [Automattic/jetpack#7845]
A gallery widget has been introduced in core (4.9-alpha). See [#41914](https://core.trac.wordpress.org/ticket/41914) on Trac.

Something will likely need to be done with the Gallery widget in Jetpack, either to deprecate or migrate.

Additionally, the Tiled Galleries module and slideshows in Jetpack should work properly with core's Gallery widget, but this is [reported](https://wptavern.com/new-core-gallery-widget-targeted-for-wordpress-4-9) to not be working right:

> For example, with Jetpack enabled, users can choose between a thumbnail and a slideshow gallery, but the slideshow option doesn’t seem to work correctly in the widget.

**Comment by jeherve** [comment]
Thanks for reaching out! I'll close this issue in favor of #7830.
