### ISSUE TITLE
Jetpack Gallery Widget - Conflict with SiteOrigin Page Builder (No event on 'Choose Image' button)

### ISSUE THREAD

**Issue by lamdayap** [Automattic/jetpack#7847]
Had a report that when adding Jetpack's Gallery Widget via SiteOrigin's Page Builder, the 'Choose Images' button doesn't work. I was able to replicate this on my test site on both Chrome and Safari:

![screen capture on 2017-08-17 at 16-02-07](https://user-images.githubusercontent.com/18111588/29398123-08de0168-8366-11e7-9a50-d4911eec5743.gif)

Steps to reproduce:

1) Install SiteOrigin Page Builder
2) Add New Post and and make sure you're in the Page Builder editor, click on 'Add Widget' and select the Jetpack Gallery Widget.
3) Hover over the edit button to bring up the Widget Options
4) Click on 'Choose Images'

What I expected to happen:

The Media Library box to pop-up

What Happens:

Nothing and no error codes in console.

**Comment by jeherve** [comment]
Closing this for now since there is now a core Gallery widget instead.
