### ISSUE TITLE
Jetpack sites can't be set to "Private" in the same way WPCOM sites are.

### ISSUE THREAD

**Issue by georgestephanis** [Automattic/jetpack#7857]
Missing functionality that we should probably merge over, especially for Atomic sites.

WPCOM source is `WPCOM/wp-content/mu-plugins/private-blog.php` -- but that file will need to be cleaned up and some wpcom-specific stuff extracted before it can be synced to Jetpack.

**Comment by ehti** [comment]
This is coming up in context of AT as well.

People with existing private sites (plus viewers on top if, which are wpcom-specific) aren't being able to go ahead. If they do go ahead, they'll lose their viewers.

Any work planned? @georgestephanis @jeherve

**Comment by catrymer** [comment]
Just posting here to say this is still a problem for users. I got another request to make an Atomic site private today in chat. Transcript here: https://mc.a8c.com/support-stats/happychat/transcript.php?id=5346520

**Comment by joendotcom** [comment]
+ 1752328-zen

**Comment by jeherve** [comment]
I'll keep this issue as closed, since we eventually decided that we would not add the feature to Jetpack sites. It could be added to Atomic sites though, so I think we can keep tracking requests in https://github.com/Automattic/wp-calypso/issues/43919
