### ISSUE TITLE
Sharing: og:video improvement

### ISSUE THREAD

**Issue by joshbetz** [Automattic/jetpack#7863]
It looks like Youtube includes two og:video URLs, `https://www.youtube.com/embed/s1nFuAST4TM` and `http://www.youtube.com/v/s1nFuAST4TM?version=3&autohide=1`, and Facebook prefers the first. We only include the second URL and my browser downloads s1nFuAST4TM.swf instead of playing the video.

I've included links to the Facebook debugger for the two pages in question as well, in case that's helpful.

Good: https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Ds1nFuAST4TM

Bad: https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fjosh.blog%2F2017%2F09%2Frestless-dream

#### Steps to reproduce the issue

Post to Facebook with an embedded Youtube video.

#### What I expected

The video preview should be playable from Facebook.

#### What happened instead

My browser downloads a .swf file.

**Comment by emilyatmobtown** [comment]
It appears that inline video playback in Facebook is no longer guaranteed or supported in the news feed, even with the proper meta tags.

See: https://developers.facebook.com/support/bugs/1963535797258090

I tested a patch with updated tags following Facebook's og:video documentation (https://developers.facebook.com/docs/sharing/webmasters#media) and confirmed via the debugger that playback wasn't available.

@jeherve - This issue can probably be closed.
