### ISSUE TITLE
MCE Model z-index issue with  

### ISSUE THREAD

**Issue by ppilalas** [Automattic/jetpack#7866]
#### Steps to reproduce the issue
Online 383 of /jetpack/modules/after-the-deadline/tinymce/plugin.js the z-index makes the model behind the cover div when editing in the Wordpress editor.

#### What I expected
I expected the model to be in front of the model div.

**Comment by jeherve** [comment]
Could you add a screenshot of what you see, as well as some details about your browser?

Thanks!

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
