### ISSUE TITLE
SEO Tools can be enabled from module list

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#7867]
In 3302536-t the user was seeing duplicate meta description tags on his post. One from Yoast, and another which disappeared when Jetpack was deactivated.

The debug tool showed that SEO Tools was enabled even though the user has never had a Professional Plan.

After some digging, I found that even without a Professional Plan, you can activate the SEO Tools module from the full modules list, which causes meta descriptions to be output in posts.

Should that module only be in the list if you have a Pro Plan? (Or show an upgrade prompt there?)

**Comment by beaulebens** [comment]
I suggest we just disable the ability to activate any modules in this list associated with paid plans unless you have that plan (or higher).

**Comment by beaulebens** [comment]
We already have some code in the Search module that removes the ability to activate the module unless you have the appropriate plan.
