### ISSUE TITLE
Disable "Require Two-Step" checkbox when option is filtered

### ISSUE THREAD

**Issue by joshbetz** [Automattic/jetpack#7868]
When the `jetpack_sso_require_two_step` option is filtered and therefore not dependent on the options table, we should disable the toggle.

https://github.com/Automattic/jetpack/blob/6219689790419c7266a9f94664c3522c1586c4b6/_inc/client/security/sso.jsx#L84-L96

**Comment by xpurichan** [comment]
Bumping this request up, as it threw us for a bit of a loop when we found 2FA was disabled according to Calypso and WP Admin settings:

![Screenshot 2024-05-03 at 1 09 36 PM](https://github.com/Automattic/jetpack/assets/33190975/8b9d2748-2077-4a3d-b662-b4805b4e684c)

Only to identify that 2FA was set as required via the available filter:
https://developer.jetpack.com/hooks/jetpack_sso_require_two_step/

A solution would be to disable the toggle and show that the feature is forced on.

**Comment by georgestephanis** [comment]
Noting that the filter may now be `jetpack_force_2fa` from https://github.com/Automattic/jetpack/pull/33259 -- or may also need to take effect? -- I'm not entirely sure offhand precisely how the two filters interact as they're both still in existence?

cc: @kraftbj

**Comment by xpurichan** [comment]
Hi @kraftbj I wanted to check in and see if you were still the right person to tag ⬆️ . If not, could you point us in the right direction for who or which team would be a good fit to engage on this issue?

**Comment by jeherve** [comment]
@chrisbliss18 I think this may be a good addition to Vulcan's backlog maybe?

**Comment by monsieur-z** [comment]
> Noting that the filter may now be jetpack_force_2fa from https://github.com/Automattic/jetpack/pull/33259 -- or may also need to take effect? -- I'm not entirely sure offhand precisely how the two filters interact as they're both still in existence?

Looking at [the changes](https://github.com/Automattic/jetpack/pull/33259/files) in that PR, it seems that enabling `jetpack_force_2fa` will enable `jetpack_sso_require_two_step` in any case. I could use another set of eyes from someone familiar with Jetpack SSO.

**Comment by jeherve** [comment]
> it seems that enabling jetpack_force_2fa will enable jetpack_sso_require_two_step in any case.

Yup, that's correct.
