### ISSUE TITLE
Recipe Shortcodes: Add additional schema details

### ISSUE THREAD

**Issue by seejacobscott** [Automattic/jetpack#7878]
I recently talked to a user that wanted to see some additional schema details added to the recipes shortcode. The specific requests were: 

The specific data they would like to see are:

1. Preparation Time
2. Cook Time
3. Author
4. Rating
5. Nutrition

These are pretty standard details for a recipe, so would be a great addition to the existing details.

**Comment by seejacobscott** [comment]
Originally posted to Automattic/jpop-issues#637

**Comment by s2r** [comment]
I agree, adding them would be important to make if fully compliant, as of now its really too basic to use seriously.

**Comment by s2r** [comment]
I don't understand why priority is low, since this just makes google give an error that there is a bad implementation and that hurts everyone that uses wordpress recipe shortcode...

**Comment by kraftbj** [comment]
Thanks @s2r for the additional information regarding how Google is validating it. From the original report, it reads that they would be nice to have things to add, hence low. Thanks again.

**Comment by jeremypaavola** [comment]
Requested in 1434548-zen

**Comment by ChaosExAnima** [comment]
Closed by #13841.
