### ISSUE TITLE
Sharing Buttons: Email sharing message not translating correctly.

### ISSUE THREAD

**Issue by seejacobscott** [Automattic/jetpack#7880]
When a site is using a different language using the Email sharing button is still sending the message in English.

Taking a look the string itself should be translated. The reporting used does have their site in French.

Checking the code here, it indicates the translation string should work as expected:
https://github.com/Automattic/jetpack/blob/e3f3e408b55aef08a04a14508d551e8272faa0ac/modules/sharedaddy/sharedaddy.php#L94

The translated string can be seen here: https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/fr/default?filters%5Bterm%5D=be+interested&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

User reported in 3318004-t that they're site is set to use the French language, but sharing is sending out the following:

![image](https://user-images.githubusercontent.com/16127063/30941235-0e34e636-a3aa-11e7-8607-d221a09b2952.png)

@danjjohnson was able to confirm this by testing on his own site in French: 

> Confirmed. My site is in French, but the email came through in English, and the success message was also English:
> ![image](https://user-images.githubusercontent.com/16127063/30941281-46249a64-a3aa-11e7-8b88-9225caa070f2.png)

**Comment by tmmbecker** [comment]
User has inquired about the status of this in 725600-zen

**Comment by pierrefrance** [comment]
I see this has been set as a low priority, and still not fixed in the latest release. Unfortunately, it's a bigger priority than this for every media not in english as main language, it really sends an unprofessional message.

**Comment by cena** [comment]
Any movement on this?  882780-zen

**Comment by pierrefrance** [comment]
Lots of Jetpack versions afterwards and still no movement on this issue.

**Comment by pierrefrance** [comment]
Is there a way to correct this issue ?

**Comment by jeherve** [comment]
@pierrefrance Unfortunately not, but we'll update this issue once we find a way to fix this.

**Comment by pierrefrance** [comment]
Other part are not translated, for example comment subscription : 
http://www.clipular.com/c/6632536768512000.png?k=uuAjVN_7NfP02RL3WV81NKrATFA

**Comment by jeherve** [comment]
@pierrefrance This text is translated if your site is set to French and if you have downloaded the French language pack for Jetpack. This can be done by going to Tableau de Bord > Mises à jour.

<img width="1194" alt="123a4bd3329fa98c4b197073310d770e _screenshot 2018-09-04 at 12 27 29" src="https://user-images.githubusercontent.com/426388/45026251-06012780-b03e-11e8-8a04-e4de27973529.png">


<img width="807" alt="screenshot 2018-09-04 at 12 25 01" src="https://user-images.githubusercontent.com/426388/45026163-ca665d80-b03d-11e8-91e3-41b4ade1baf4.png">

**Comment by pierrefrance** [comment]
Confirmed ! Thank you so much (at last). 

Now we need an editor for all these transactionnal e-mails. :-) For exemple, we'd like to add teasers and call to subscribe, discounts, etc.

**Comment by jeherve** [comment]
This can now be closed since we now use mailto instead of a custom email sharing button (see #24040).
