### ISSUE TITLE
Contact Form / Date Picker: use date format as defined in Settings > General

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#7885]
![screenshot 2017-09-28 at 15 12 22](https://user-images.githubusercontent.com/426388/30969918-12f2d880-a464-11e7-8e4a-b2be43dad3c6.png)

> I would like to customize the date format. I would really prefer a dd/mm/yyyy date format — my site’s language is UK English and uses the dd/mm/yyyy date format for posts, and I’d like that consistency with the contact form.

**Comment by jeherve** [comment]
Switching to a more rigid format would also allow us to remain consistent across platforms. Right now, the HTML5 date input format matches your country / language in the editor and on the site's frontend in some browsers, but always uses yyyy/mm/dd in the email sent to the site owner.

**Comment by rclations** [comment]
I believe this should be fixed in https://github.com/Automattic/jetpack/pull/7890/commits/d33533d56fdf7f0980f95f3ad4369d5d4e654de2

**Comment by jeherve** [comment]
Yep, looks good now, thank you!
