### ISSUE TITLE
Contact Form / Date Picker: missing arrow indicator in FF / Safari

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#7889]
> The dropdown picker appeared in all three browsers I tested when I clicked in the date field. However, the arrow inside the right edge of the input only appeared in Chrome. Firefox and Safari showed a blank field.

Chrome:

![screenshot 2017-09-28 at 15 52 22](https://user-images.githubusercontent.com/426388/30970291-099b1ddc-a465-11e7-9240-1efe8a7e68f8.png)

Firefox:

![screenshot 2017-09-28 at 15 51 53](https://user-images.githubusercontent.com/426388/30970269-fce558fa-a464-11e7-8812-23be62f5374a.png)

**Comment by rclations** [comment]
All arrow indicators were removed in #7890, so I think this is fixed?

**Comment by jeherve** [comment]
Yup, thanks!
