### ISSUE TITLE
Settings UI: initial Stats message still allows to choose weeks or months

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#7899]
On connection, Stats shows a message saying that stats are being collected but the days/weeks/months bar at the top right allows to switch to other date ranges. Maybe this bar should be hidden?

![stats](https://user-images.githubusercontent.com/1041600/31020306-fb25bbaa-a508-11e7-8ad8-22d751528458.gif)

**Comment by dmsnell** [comment]
Why is this a problem? Won't the weeks/months views also hold the immediate data pouring in on the site?

**Comment by eliorivero** [comment]
It looks like only Days is waiting for data. This placeholder is meant to be displayed when the user first connected the site and there's not Stats data yet. However, right now it looks like if it was missing data for Days only.
