### ISSUE TITLE
Admin Page: no option to dismiss Warm Welcome

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#7904]
Warm Welcome was added in #7837.

Unfortunately the screen cannot be dismissed. These are the only actions one can take.

![screenshot 2017-09-29 at 23 20 12](https://user-images.githubusercontent.com/426388/31036501-c4c8ae8c-a56c-11e7-9c89-e315e12c70cb.png)

Could we add an option to dismiss?

**Comment by MichaelArestad** [comment]
@jeherve There is a dismiss X in the top right (or should be), but I think we can add something more noticeable.

**Comment by dereksmart** [comment]
Note that it's the same location as the jumpstart dismiss

**Comment by jeherve** [comment]
> It took me a minute to find the X in the top right corner of this page, which is almost the same color as the background. 

p8oabR-8W-p2

**Comment by gravityrail** [comment]
Also, clicking esc should close it
