### ISSUE TITLE
Social Icons Widget

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#7915]
Hey guys,

So I manage 100s of WordPress sites, and I'm always looking for ways to optimize and streamline the sites as a whole. I notice that many of our sites are using a plugin called simple social icons, even though we have Jetpack installed and activated on every single one. 

The main reason is it just gives a few more options to customize the look and feel of the icons, such as size. Would love to see this widget get a bit more love so I can replace the simple social icons plugin on our sites, and have one less plugin to manage.

https://wordpress.org/plugins/simple-social-icons

**Comment by jeherve** [comment]
We plan on making improvements to our [Social Media Icons Widget](https://jetpack.com/support/extra-sidebar-widgets/social-media-icons/) very soon. You can follow our progress in #7454.

Others have also suggested additional options to the existing widget in #7917 so it looks like just what you would need. I'll close your issue in favor of that other one.
