### ISSUE TITLE
Contact Form: Option to have checkbox checked by default

### ISSUE THREAD

**Issue by aschweigert** [Automattic/jetpack#7921]
#### Steps to reproduce the issue

- Create a contact form
- Select the checkbox field type
- Observe that there is no way to have the box checked by default

#### What I expected

- It would be nice to have a way to set the default state of the checkbox, perhaps by passing a `checked=1` parameter or something similar in the shortcode.

#### What happened instead

- The only option appears to be having the box unchecked by default.

**Comment by jeherve** [comment]
Closing in favor of #14912
