### ISSUE TITLE
Update Plans icon in the Masterbar to match WP.com

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#7923]
On WP.com, we use a Jetpack logo as the icon for the Plans menu item, since Jetpack is what provides all of the premium features. We've never updated the Masterbar in Jetpack to match:

WP.com/Calypso:
![screen shot 2017-10-03 at 11 02 24 am](https://user-images.githubusercontent.com/108942/31138040-5c744fce-a82a-11e7-99d8-60245f0bbbcf.png)

Jetpack:
![screen shot 2017-10-03 at 11 02 46 am](https://user-images.githubusercontent.com/108942/31138054-69561bd2-a82a-11e7-8f69-e05e9c4e7cef.png)

And the front-end of WP.com also needs to be updated:

WP.com frontend/blog-side:
![screen shot 2017-10-03 at 11 06 10 am](https://user-images.githubusercontent.com/108942/31138189-e3b4d7b0-a82a-11e7-9643-67e9d855d77f.png)

**Comment by lancewillett** [comment]
Good eye.

**Comment by jeherve** [comment]
Related: https://github.com/Automattic/gridicons/issues/240

**Comment by vindl** [comment]
Resoved in D7647-code.

**Comment by vindl** [comment]
Fix deployed.
