### ISSUE TITLE
Update comment form icons, especially G+

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#7925]
The G+ icon especially needs some updating, as it's not even retina.  Let's update it to something more Google and get it crisp.  

There are more up-to-date icons we could be using for the other services as well.

![](https://jetpackme.files.wordpress.com/2017/10/screen-shot-2017-10-03-at-2-24-02-pm.png)

**Comment by MichaelArestad** [comment]
Will see what we can do with Gridicons (probably) or SVG.

**Comment by beaulebens** [comment]
Note this will actually need to be done on WP.com (and thus for all sites), since this form is embedded directly from there.

**Comment by enejb** [comment]
Could we use the https://github.com/Automattic/social-logos here?

**Comment by MichaelArestad** [comment]
@enejb Yes. Should we inline them or link to the SVGs? If we inline them, our users will be able to style them as they please. Perhaps we could make them pick up dark/light theme styling.

**Comment by MichaelArestad** [comment]
Let's take a stab at making it look like this:

![image](https://user-images.githubusercontent.com/1123119/37105046-6ae9bb30-21eb-11e8-9229-8851133af805.png)

[Here are the SVGs.](https://cloudup.com/cmtAX8cuUC7) I'll take a stab at implementation shortly.

**Comment by MichaelArestad** [comment]
This is beyond me to implement. I started changing the images out with SVG and all was going (fairly) well when I realized the image for Google is coming from somewhere else in an iframe within an iframe. SOS!

**Comment by MichaelArestad** [comment]
CC @stephanethomas

**Comment by stephanethomas** [comment]
@MichaelArestad, how can I help exactly? Do you want me to find the image source file for the Google+ icon? Do you have a Phabricator patch where I could provide that type of information?

**Comment by MichaelArestad** [comment]
@stephanethomas I'm not even sure where the icon for google plus is or why it's in its own iframe. I was hoping you had some insight on either or both of those things.

**Comment by MichaelArestad** [comment]
It looks like the google icon needs to be updated in a different way than the other icons. It would be ideal if the code could be changed so all the icons are presented in the same format. It looks like the last people to work with the code are @enejb and @lezama. I would really love either of your help with this and I will of course do what I can to help. Thanks!

**Comment by MichaelArestad** [comment]
The code itself is not in the Jetpack or Calypso codebase. Please ping me for a link.

**Comment by enejb** [comment]
@MichaelArestad I can try to fix this during next weeks fix the flows

**Comment by enejb** [comment]
D11041-code fixes this issues. But needs more testing.

**Comment by enejb** [comment]
![screen shot 2018-03-19 at 3 45 42 pm](https://user-images.githubusercontent.com/115071/37626301-b2c58a6a-2b8c-11e8-9aa2-5310d41f425c.png)

**Comment by designsimply** [comment]
Can you check the post-login versions of the icons? Most of them look okay to me, except for Facebook:

![screen shot 2018-03-19 at mon mar 19 5 32 06 pm](https://user-images.githubusercontent.com/1119271/37627763-9962120a-2b9b-11e8-8023-363dd7a967a2.png)
<sup>Seen at https://design5279.wordpress.com/2018/03/12/chewie/ (sandboxed with D11041-code applied) using Firefox 59.0.1 on macOS 10.13.3.</sup>

**Comment by designsimply** [comment]
Re-applied D11041 and re-tested and the FB icon looks ace on a WP.com Simple site after logging in now. [[screenshot](https://user-images.githubusercontent.com/1119271/37668310-c920a130-2c29-11e8-9bf1-4884551b9705.png)]

**Comment by designsimply** [comment]
Note/aside: while logged in to wp-admin I don’t see the option for social media sign-in for comments. This seems like expected behavior.

![screen shot 2018-03-20 at tue mar 20 10 42 55 am](https://user-images.githubusercontent.com/1119271/37669677-16956b8c-2c2d-11e8-8033-58df6b47755f.png)
<sup>Seen at https://convenient-cuban.jurassic.ninja/2018/03/20/anila-quayyum-agha/ using Firefox 59.0.1 on macOS 10.13.3.</sup>

**Comment by designsimply** [comment]
I tried testing this on a Jetpack site after updating the setting for comments:

* Go to WP Admin > Jetpack > Settings > {search for "comments"} and enable the option for "Let readers use WordPress.com, Twitter, Facebook, or Google+ accounts to comment."

But the WP, Twitter, and Facebook icons still look outdated there. I tested using Jetpack 6.0-beta-17959-cda31ab-master and WordPress 4.9.4. Should I be able to see the updated icons with that beta version or is there something else I need to do before I can test on a Jetpack site?

![screen shot 2018-03-20 at tue mar 20 10 55 59 am](https://user-images.githubusercontent.com/1119271/37669808-60912e06-2c2d-11e8-833d-efa88d9239f2.png)
<sup>Seen at https://fancy-finfoot-485.jurassic.ninja/2018/03/20/hello-world/ using Opera 51.0.2830.62 on macOS 10.13.3.</sup>

**Comment by enejb** [comment]
I think you might have missed mapping the jetpack.wordpress.com domain to point to your sandbox. 
Since the whole form is coming from there.

**Comment by simison** [comment]
Does this also fix https://github.com/Automattic/jetpack/issues/5242: _"Google+ sign in button is not keyboard accessible"_ ?

**Comment by designsimply** [comment]
Note: I re-tested with a Jetpack site and it looked 👍

Nitpick: the icons are a bit hard to see on the the dark color scheme. [#](https://user-images.githubusercontent.com/1119271/37856136-7009fa74-2eb8-11e8-8cc8-5c4232e364bb.png)


![screen shot 2018-03-23 at fri mar 23 4 31 50 pm](https://user-images.githubusercontent.com/1119271/37856139-73cf4cb8-2eb8-11e8-8925-bbffac291b33.png)
<sup>Seen at https://romantic-reindeer-75.jurassic.ninja/2018/03/23/hello-world/ using WordPress 4.9.4 and Jetpack 6.0-beta-18073-c123353-master with Firefox 59.0.1 on macOS 10.13.3.</sup>

**Comment by enejb** [comment]
I updated the icons so that they look good with the dark colour scheme. 
![screen shot 2018-03-26 at 10 32 07 am](https://user-images.githubusercontent.com/115071/37928762-d6970a2a-30f2-11e8-8348-73698ce247fb.png)

As well as tested the transparent one. 
![screen shot 2018-03-26 at 11 38 23 am](https://user-images.githubusercontent.com/115071/37928772-da2dffe0-30f2-11e8-9e3d-de7fbb63bf03.png)
![screen shot 2018-03-26 at 11 40 40 am](https://user-images.githubusercontent.com/115071/37928778-dc927a36-30f2-11e8-9a47-48e8bef80c35.png)

I wasn't able to replicate the issue on IE9 win7. 
See 
![screen shot 2018-03-26 at 12 42 12 pm](https://user-images.githubusercontent.com/115071/37928861-25ae5a46-30f3-11e8-932d-1ef5933ac519.png)

**Comment by enejb** [comment]
This is how it looks like on IE 8
![screen shot 2018-03-26 at 12 43 24 pm](https://user-images.githubusercontent.com/115071/37928929-54a97ba0-30f3-11e8-9ac9-e28f945cb275.png)

**Comment by enejb** [comment]
Thanks @designsimply 
I am able to replicate this issue as well. Just not sure yet how to fix it. :/

**Comment by enejb** [comment]
I got it working. So it turns out that IE9 has an issue with the number of style sheets that can be loaded. Adding ?concat_css=yes to the url fixes this issue. 

![screen shot 2018-03-27 at 11 56 07 am](https://user-images.githubusercontent.com/115071/37988542-031b669a-31b6-11e8-978e-d978a0a104cb.png)

**Comment by enejb** [comment]
The change is now live!
