### ISSUE TITLE
Fatal Error with "Top Posts & Pages (Jetpack)" widget when using WPML

### ISSUE THREAD

**Issue by kareldonk** [Automattic/jetpack#7931]
#### Steps to reproduce the issue

On a website with the WPML plugin and Jetpack installed, use the "Top Posts & Pages (Jetpack)" widget in the side bar, and do a search (using the search widget for example) that gives no results (i.e. no posts found). The page will then not load properly, and viewing the HTML source you will find the following error:

> <b>Fatal error</b>:  Cannot use object of type WP_Error as array in <b>/.../wp-content/plugins/jetpack/3rd-party/wpml.php</b> on line <b>33</b><br />

This only happens when a page loads without any posts in the main query it seems, such as a search page without results.

#### What I expected

I expected no errors to occur.

#### What happened instead

See steps to reproduce.

#### A temporary fix

I was able to narrow the problem down to the following line in the file "wp-content/plugins/jetpack/3rd-party/wpml.php":

`$lang_information = wpml_get_language_information( $post['post_id'] );`

It seems that when the main query has no results (no posts) the WPML plugin can't seem to determine the language and returns a WP_Error object in the $lang_information variable which then cannot be used as an array in the following line: 

`$post_language    = substr( $lang_information['locale'], 0, 2 );`

I made the following changes to make this work:

````php
        foreach ( $posts as $k => $post ) {
		$lang_information = wpml_get_language_information( $post['post_id'] );
		if (!is_wp_error($lang_information))
		{
			$post_language    = substr( $lang_information['locale'], 0, 2 );
			if ( $post_language !== $sitepress->get_current_language() ) {
				unset( $posts[ $k ] );
			}
		}
	}
````

As you can see I only added one line to check for an error.

Would be nice if you investigated and included a fix in your next release.

**Comment by kareldonk** [comment]
Also see: https://wpml.org/forums/topic/php-fatal-error-uncaught-error-cannot-use-object-of-type-wp_error-as-array-in/

**Comment by jeherve** [comment]
Looking at the `wpml_get_language_information` function in WPML, your patch seems like our best course of action and accounts for all possible outputs for the function. I've consequently created #7938 with your patch.

Thanks a lot for the report and for your contribution!
