### ISSUE TITLE
Publicize - Strip Visual Composer Shortcodes 

### ISSUE THREAD

**Issue by csonnek** [Automattic/jetpack#7932]
Related to #869 

We've put some fixes in place to remove the shortcodes from popular plugins from being output in Subscriptions and Publicize. 

I've been seeing an increase in reports of Visual Composer (VC) shortcodes getting sent out via Publicize and via our Subscriptions. A few examples of code that is sent:

```
[vc_row]
[vc_column]
[vc_column_text]
```

As we're seeing an increase in the use of VC, it would be great to add the default VC shortcodes to the ones added back in [this PR](https://github.com/Automattic/jetpack/pull/6030). I've tried to hunt down the list of default shortcodes in VC, but haven't been able to locate one. Might need input from the developer to get this list?

717672-zen for the idea

cc: @gravityrail as you worked on the other PR and may have some insight.

**Comment by gravityrail** [comment]
We currently replace `vc_row` with a `<div>` tag and `vc_column` with a `<p>` tag, and we replace the `vc_column_text` with its inner content (no surrounding tag)

If these are going out via subscriptions then somehow it's bypassing our replacement shortcodes. If you could provide an example blog_id/post_id that was showing these shortcodes, I would appreciate it so I can reproduce.

**Comment by csonnek** [comment]
The original ticket had examples - publicized posts on LinkedIn: https://www.linkedin.com/in/hanlie-van-der-vyver-54736512/detail/recent-activity/

All blog ID 129317590:

- Post 4221
- Post 4222
- Post 4223
- Post 4226

I'm not sure if this site is using Subscriptions, but I've seen another site where the VC code is being output when Publicized to Google+ (blog ID 135989513 - 716436-zen ):

![screen_shot_2017-10-03_at_2_38_18_pm](https://user-images.githubusercontent.com/2814452/31242973-66d062e6-a9ce-11e7-92ef-31319d42abde.png)

Facebook and Twitter Publicize doesn't seem to be affected.

**Comment by pmciano** [comment]
Reported here 824848-zen for Tumblr

**Comment by SimonVetterli** [comment]
I am facing the same issue, with all latest versions of plugins, an example get found here: https://plus.google.com/u/0/116290060426071516618

**Comment by jeherve** [comment]
This should now be fixed as of r174225-wpcom.

Feel free to comment if this happens again!

**Comment by designboxcom** [comment]
This happens again on my side....

**Comment by zinigor** [comment]
@designboxcom could you please contact support with examples of how this issue affects your site, and mention this issue? This would help us debug. Thank you!

**Comment by designboxcom** [comment]
I am still new to all this and still a bit lost.
How to contact the support?
I published today a new article on my Wordpress website and again Publicize inserted the Visual Composer Short codes into the Google+ Article.

**Comment by jeherve** [comment]
@designboxcom You can contact support [via this contact form](https://jetpack.com/contact-support/?rel=support).

Thank you!

**Comment by StefMattana** [comment]
Reported on 1501545-zen
I wonder if there's a good fix for this? The user has good examples on the ticket we could work on :)
