### ISSUE TITLE
Bug: milestone widget is broken since the last update (no countdown and wrong language)

### ISSUE THREAD

**Issue by SuddenH4X** [Automattic/jetpack#7940]
Since the last update the milestone widget isn't working correctly. The countdown isn't displayed and also the configured language isn't read anymore.

Before the update: "Noch 12 Tage." (German)
After the update: "to go." 

Screenshot:
![milestone-widget-issue](https://user-images.githubusercontent.com/12644263/31233162-45703888-a9ec-11e7-864e-c093d9361b57.PNG)

I added different milestones with the option "Until your milestone" and "Since your milestone" selected, but I wasn't able to get a number or the correct language.

Used Theme: Lovecraft

**Comment by zinigor** [comment]
@donnapep @supernovia can you please fix translatable strings according to what Alex [reported here](https://github.com/Automattic/jetpack/pull/7782#issuecomment-334496088)?

**Comment by codestor4** [comment]
similar issue reported here: 751085-zen
milestone widget does not display count!
was not able to reproduce this on twenty-seventeen with french site language

**Comment by jeherve** [comment]
Also in 761829-zen

**Comment by SuddenH4X** [comment]
Now the time is displayed correctly, thank you! :) Unfortunately the translation isn't working:

![screenshot-2017-11-16 willkommen bei den pfalzer guggeglucke e v guggemusik aus rulzheim](https://user-images.githubusercontent.com/12644263/32920611-39169ffa-cb2a-11e7-93b0-6cec770d16bd.png)

It's configured the German language as before, but the string is displayed in english. I've looked up the translation with the loco translate plugin and it seems to exist the correct translation:

![screenshot-2017-11-16 editing jetpack-de_de po in jetpack by wordpress com plugin translations loco willkommen bei de](https://user-images.githubusercontent.com/12644263/32920735-c14857e2-cb2a-11e7-909a-985e1ce5c0c3.png)

**Comment by jeherve** [comment]
@SuddenH4X It seems that the new translation hasn't been approved yet:
https://translate.wordpress.org/projects/wp-plugins/jetpack/dev/de/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=5241713&filters%5Btranslation_id%5D=52772389

Once it is approved it should become available on your site!

**Comment by SuddenH4X** [comment]
@jeherve Thank you!
