### ISSUE TITLE
BUG: Markdown Comment Disappeared after Submit

### ISSUE THREAD

**Issue by mashirozx** [Automattic/jetpack#7957]
Hello, I got a problem when using Markdown comment. I find I can comment in Markdown normally as Keymaster, but if I comment in Markdown as a un-logined passers-by (name & email) only, what I submitted will become blank (all text in Markdown disappeared, and also I can only see a blank comment in wp-admin background). I have tried this in the default Twenty Seventeen theme, and all other plugins have been closed. 

You may test it on my mirror site:
[Test only mirror site](https://demo.2heng.xin/comment/)

Newest WordPress 4.8.2. and newest jetpack, thank you.

**Comment by mashirozx** [comment]
PS. description doesn't exactly, I should say the Markdown part of comment will become blank. 
eg:
```markdown
hello world

![DONATE](https://2heng.xin/wp-content/uploads/2017/09/do.png)

```

you may only see hello world after Submit.

**Comment by jeherve** [comment]
Does this happen with any Markdown, or just when trying to insert images? Readers are not allowed to insert images in comments in WordPress, so that would explain why images get stripped.

**Comment by mashirozx** [comment]
@jeherveoh
 Oh yes, you are right. Wrong with pictures only.
