### ISSUE TITLE
Comment Likes: Like counts are not translated

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#7958]
#### Steps to reproduce the issue

1. Start on a site where Jetpack and its comment Likes modules are active.
2. Switch the site language to French.
3. Note that the strings for Comment Likes are translated into French:
https://translate.wordpress.com/projects/wpcom/fr/default/?filters%5Bterm%5D=Liked+by&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc
4. While the translation appears properly when a comment hasn't been liked yet, it is not correct for comments that have been liked at least once:

![screenshot 2017-10-09 at 10 51 48](https://user-images.githubusercontent.com/426388/31330741-e25b4bf6-acdf-11e7-91b2-9221a50cfba2.png)

Reported in 693464-zen

**Comment by vindl** [comment]
@jeherve I'm not sure why this is happening since the output of this is wrapped in `i18n.translate()` just as `Like` is. You can verify that in `getCommentLikeFeedback()` function of `likes/likes-rest.js`.

Could it be that we don't have a translation for this string?

**Comment by vindl** [comment]
Searched for it in GlotPress and that doesn't seem to be the case. We have a translation for this string available since 2014-06-09.

**Comment by vindl** [comment]
@yoavf or @akirk any ideas what could be causing this?

**Comment by hewsut** [comment]
The strings in question are not in `json-strings.php` so the translations never get generated into the appropriate json file for `translate` to pull from.

I've added the strings [new ones actually] tonight and redeployed `fr` so people can test against that ["Liked by you" is only currently translated variant].

**Comment by vindl** [comment]
> The strings in question are not in json-strings.php so the translations never get generated into the appropriate json file for translate to pull from.

TIL :+1:  
For anyone interested here is the actual change r165811-wpcom.
Just out of curiosity, is the process for generating that json file automated?
