### ISSUE TITLE
Duplicate Meta Descriptions on Atomic Sites+Woocommerce+Yoast

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/jetpack#7962]
#### Steps to reproduce the issue

1. Install WooCommerce on WordPress.com Business site, or use the Calypso Store beta to start a new WooCommerce installation.
2. Install core Yoast WordPress SEO plugin.
3. Add products to WooCommerce store.
4. Add a custom meta description to Yoast settings in the product edit page.

#### What I expected

Other WordPress.com SEO settings are automatically disabled by Jetpack on installation of major SEO plugins. WooCommerce's base SEO settings should be overridden by Yoast.

#### What happened instead

Both meta descriptions, from Yoast and from the generated product are shown in the HTML markup.

<img width="916" alt="screen shot 2017-10-10 at 10 11 48 am" src="https://user-images.githubusercontent.com/8002138/31400192-8caa0444-ada3-11e7-9bcd-3b15d037ac4d.png">
<img width="645" alt="screen shot 2017-10-10 at 10 12 00 am" src="https://user-images.githubusercontent.com/8002138/31400194-8f138b56-ada3-11e7-9a87-3e4178d7eb64.png">

**Comment by jeherve** [comment]
I can't seem to be able to reproduce the issue on my end. 
- I've added a custom meta description in my Yoast settings:
![screenshot 2017-10-11 at 15 00 12](https://user-images.githubusercontent.com/426388/31441909-e848314e-ae94-11e7-93e4-7bc5960e5218.png)
- I added a product description:
![screenshot 2017-10-11 at 15 00 29](https://user-images.githubusercontent.com/426388/31441927-fa0e2bfe-ae94-11e7-841d-6886d3ad1d88.png)

Still, I only see the Yoast meta tag on my product page.

Did you make any other changes that are missed? What do you see when trying to edit the Jetpack SEO tags in Calypso? All I see is this:

![screenshot 2017-10-11 at 15 02 09](https://user-images.githubusercontent.com/426388/31441975-2ee19c9e-ae95-11e7-9af6-16f1dc86cb07.png)

**Comment by chrisfromthelc** [comment]
Here is the test product page using the Storefront Beta: https://chriswsmithbusinesstest.blog/product/wordpress-diversity-t-shirt-test-product/ showing multiple meta descriptions. 

Here is a test product page with a fresh site using the WooCommerce plugin installed from the plugin directory: https://woobusinesstest-chriswsmith.blog/product/test-product/ (only WC + Yoast)

Both are showing multiple meta descriptions.

I also checked the page in your screenshot: https://jeherve.com/product/proruct-m/ and it also shows multiple meta descriptions.

<img width="552" alt="screen shot 2017-10-11 at 10 00 50 am" src="https://user-images.githubusercontent.com/8002138/31454700-1bfe0b82-ae6b-11e7-948f-e4221af678fc.png">
<img width="596" alt="screen shot 2017-10-11 at 10 00 40 am" src="https://user-images.githubusercontent.com/8002138/31454703-1c8fceb4-ae6b-11e7-84f7-357b8f95fb5c.png">

**Comment by jeherve** [comment]
uh, cache... Thank you!

#7976 should hopefully fix that.
