### ISSUE TITLE
Jetpack comment form: submit with `command + return` keyboard combo

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#7966]
This isn't urgent or a must-have, but it would be nice to be able to submit comments using `command + return` (or `control + return` on PC). Many other services use this common hotkey including Facebook and Twitter.

**Comment by roccotripaldi** [comment]
In progress: D11132-code

**Comment by roccotripaldi** [comment]
resolved in 172218-r-wpcom
