### ISSUE TITLE
Allow media attachment options for galleries via Post by Email

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#797]
A user requested the ability to specify the type of attachment link (attachment page, file, or none) for his galleries that he sends via post by email. It might be tricky to do so using the [gallery] shortcode, however. I sent the following email to my test site, and attached two images to the email as well:

```
[gallery link="file"]

attaching 2 images to this email
```

and here is what was published in my site:

```
[gallery link=&quot;file&quot;]

attaching 2 images to this email

[gallery include="1111,1112"]
```

but unexpectedly to me, the actual gallery showed up twice in my post (because of the 2 shortcodes that ended up being used)

Requested in 1882577-t

**Comment by samhotchkiss** [comment]
Our implementation of Post by Email is intended to be very simple and minimal, so, unfortunately, this doesn't align with our development goals and plans at this time, and is not on our roadmap for future development.
