### ISSUE TITLE
Connect Button: Malformed href.

### ISSUE THREAD

**Issue by georgestephanis** [Automattic/jetpack#7988]
When viewing the connect button, the markup looks something like this:

```html
<div data-reactid=".0.0.1.2.0.1.2:1">
<noscript data-reactid=".0.0.1.2.0.1.2:1.0"></noscript>
<a href="&amp;from=landing-page-top" type="button" class="is-primary jp-jetpack-connect__button dops-button" data-reactid=".0.0.1.2.0.1.2:1.1">Connect Jetpack</a>
<noscript data-reactid=".0.0.1.2.0.1.2:1.2"></noscript>
</div>
```

Specifically the `href="&amp;from=landing-page-top"` bit is caused by this code here:

https://github.com/Automattic/jetpack/blob/ec47f76a72737af10334481c569b54da8dc09394/_inc/client/components/connect-button/index.jsx#L119-L122

being triggered by

https://github.com/Automattic/jetpack/blob/ec47f76a72737af10334481c569b54da8dc09394/_inc/client/components/jetpack-connect/index.jsx#L32

There is no `this.props.connectUrl` specified, so the link appends `&from=${ this.props.from }` onto an empty variable, resulting in the malformed href.

#### Steps to reproduce the issue

Visit the connect page and inspect the button.

#### What I expected

A valid url in the href attribute.

#### What happened instead

A malformed url.

**Comment by georgestephanis** [comment]
I'm investigating further -- this may actually be not an issue.

**Comment by oskosk** [comment]
@georgestephanis this seems related: #7979

**Comment by georgestephanis** [comment]
I'm running a distclean and reinstall right now.

Also this is in a multisite install, so that could potentially affect it as well.

Checking ...

**Comment by oskosk** [comment]
is it domain based multisite or subdir-based ?

**Comment by georgestephanis** [comment]
subdomain

**Comment by oskosk** [comment]
fwiw, when visiting the Jetpack admin page, there should be a background request to the plugin's rest endpoint `/connection/url`. If the response of that endpoint is not a single string between quotes, then there's a problem similar to the one reported in 7979.

**Comment by georgestephanis** [comment]
Nevermind, this was a duplicate of an unrelated thing I was working on -- https://wordpress.org/support/topic/domain-mapping-connect-issue/
