### ISSUE TITLE
Featured Content: hidden Featured tags also hidden in API calls

### ISSUE THREAD

**Issue by MindyPostoff** [Automattic/jetpack#7996]
#### Steps to reproduce the issue
1. Go to the Customizer and add a tag name for the Featured Content section.
2. Add a new post from the Calypso dashboard and link the featured tag to the post; publish the post.
3. Go back to the Featured Content section of the Customizer and toggle the “Do not display tag in post details and tag clouds.” setting, and Save & Publish the changes.
4. Refresh the Edit Post screen of the post you just published in Calypso.
5. Repeat steps 3 & 4 by changing the “Do not display tag in post details and tag clouds.” setting.
6. Notice that when the “Do not display tag” setting is disabled, the tag disappears from the Post Settings of the post.

#### What I expected
I expected to see the featured tag continue to display in the Edit Post page, regardless of the setting in the Featured Content of the Customizer.

#### What happened instead

The featured tag in the post from the Calypso dashboard is removed from view. However, the tag remains linked to the post and can be seen through the WP-Admin dashboard.

Screencast: http://recordit.co/b0RC2GxBij

**Comment by jeherve** [comment]
Since the editor lives on WordPress.com, Jetpack does not control the list of tags in the WordPress.com editor. I would recommend opening this issue here:
https://github.com/Automattic/wp-calypso/issues

Thank you!

**Comment by kevmarsden** [comment]
@jeherve this is also an issue in the mobile apps, so I think this is the correct repo to report this issue.  

When the featured content tag is hidden on the front end, it no longer appears in the list of tags in API calls, so all remote editors are affected.  

Related code:  https://github.com/Automattic/jetpack/blob/master/modules/theme-tools/featured-content.php

**Comment by jeherve** [comment]
> this is also an issue in the mobile apps

Good to know, thanks. That definitely makes it something we need to fix at the root, in Jetpack. 👍

**Comment by galakhyati** [comment]
A user reported the issue of tags from featured posts being removed randomly. They have not edited the posts after they were published.

Following the steps @MindyPostoff shared, that made the posts to re-apprear on the featured slider.

Live chat: #6131233-hc

Can anyone give an update on this issue?

**Comment by jeherve** [comment]
> Can anyone give an update on this issue?

We haven't worked on this lately, but will update this issue when we do.

**Comment by lakellie** [comment]
Had a complaint from a user about this bug today. They had disappearing tags and I was able to fix it by unchecking the "Do not display tag in post details and tag clouds." setting. Chat - #7106105-hc

**Comment by kraftbj** [comment]
This should be resolved in the next version of Jetpack, due out the first week of November and on WP.com Simple sites starting now.

**Comment by fstath** [comment]
I got the same issue reported in the Shoreditch support forum when using Gutenberg to compose and edit the post.

These are the steps taken by the user that reported it:

> 1. Create a new post, type a paragraph and then give that post the associated “featured” tag
> 2. Save the post and notice the tag field goes blank, but reloading the page will show that the tag been properly attributed to that post (confusing but not the real issue)
> 3. Now select the paragraph and edit some of the block properties like background color in the Block settings context bar on the right
> 4. Without switching back to Document context bar, save the post again
> 5. Go back to the Document context bar and notice the “featured” tag has gone missing, reloading the page will show that the tag has been stripped from the post.

I was able to replicate it on the same theme on my test site.

**Comment by jeherve** [comment]
@fstath Could you confirm that you are using Jetpack 6.9 on your site?

**Comment by fstath** [comment]
Yes, I'm using the 6.9 version and WordPress is on 5.0.3. Thanks!

**Comment by jeherve** [comment]
Also quite a lot of other reports in 7859-wpcom

**Comment by jacoswan** [comment]
Added a new incidence of the issue to 7859-wpcom#comment:98

**Comment by zdenys** [comment]
Another report here  #1807477-zen (initially here #10478789-hc) where the user shared a screencast.

**Comment by liviopv** [comment]
Another report in #1831233-zen. "featured" tag goes missing after editing posts.

**Comment by selectedselections** [comment]
User returned to report that their featured tag took 8 hours to update today and seems to still be experiencing the issue they reported before (disappearing tags) #1830950-zen

**Comment by sophiegyo** [comment]
I encountered something which may be related this week: #10752334-hc

Essentially, the user reports that they published posts that were tagged as featured, but that the tag was then spontaneously removed.

**Comment by goblinartificer** [comment]
Still an issue: #11287945-hc , possibly #1877821-zd

**Comment by carladoria** [comment]
Also reported on 12109288-hc

**Comment by goblinartificer** [comment]
Still in #11383112-hc
