### ISSUE TITLE
Widget Visibility: support custom post type archive pages

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#80]
It would be nice to add a new `is_post_type_archive` condition to Widget Visibility, to allow blog owners to display or hide widgets on Custom Post Type Archive pages.

cc @cfinke

**Comment by keeslina** [comment]
Anyone with a quick hack to temporarily solve this issue , until it is fixed in an official update? 
I really need this asap for a client :)

**Comment by richardmtl** [comment]
@keeslina: there's an open Pull request in #1599 ; it hasn't been reviewed yet so use at your own risk. Maybe you can test it and report back if it worked for you?

**Comment by keeslina** [comment]
Thanks! Works for me!

**Comment by beckyresler** [comment]
Has this been scheduled for a release yet (the PR said [almost a month ago] that it was added to the roadmap)? I really need this functionality for a project I am currently working on. If it won't be added within the next month, I'll be forced to find a new widget visibility plugin (which I'd rather not do). 

Thanks.

**Comment by richardmtl** [comment]
@beckyresler we've changed the milestone to 3.7 now, as the UX needs more review and the whole thing needs more testing. https://github.com/Automattic/jetpack/pull/1599#issuecomment-113709156

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/widget-visibility-wont-hide-on-woocommerce-shop-page?replies=1&view=all
