### ISSUE TITLE
Subscriptions: include Publicize numbers in follower count

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#800]
On WordPress.com, we include the number of Facebook and Twitter followers in the subscriber counts. in Jetpack, we don't.
It'd be nice if both services behaved the same way.

Suggested in 1883051-t

**Comment by richardmtl** [comment]
Another request in 2092656-t

**Comment by jenhooks** [comment]
Another request here: 2110200-t

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/jetpack-publicize-7?replies=1&view=all

**Comment by jenhooks** [comment]
Also here: 2353649-t

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/move-stats-to-my-new-domain?replies=1&view=all

**Comment by jenhooks** [comment]
Also 2358699-t

**Comment by alexjgustafson** [comment]
2846067-t

**Comment by jeherve** [comment]
Also in 2943045-t

**Comment by richardmtl** [comment]
3059735-t

**Comment by kriskarkoski** [comment]
3211264-t

**Comment by formosattic** [comment]
381483-hc

**Comment by sjaved87** [comment]
Another report of similar issue 3227171-t

**Comment by formosattic** [comment]
3233202-t

**Comment by rralian** [comment]
@jeherve and @kraftbj can you help me understand the scope of this issue? I see us describing the problem in lots of issues and posts, but I haven't yet seen links or screenshots that show specifically in the UI where this issue manifests itself.

The only place I can find where we show this count differently from wpcom sites is in the Jetpack subscriptions widget where we say "Join X other subscribers". We [set the value in a transient called wpcom_subscribers_total](https://github.com/Automattic/jetpack/blob/master/modules/subscriptions.php#L959), and I don't see us using that value anywhere else. Is there any other usage or effects of this that I'm missing? I believe I can fix this with a simple change, but I want to make sure I'm not screwing up anything else in the meantime.

Also, do we need to communicate this change ahead of time? Many of these users are going to see a huge bump in their stats that's probably going to be confusing and/or seem a little shady.

**Comment by kraftbj** [comment]
@rralian Correct. It's just a matter of what's included in that number. AFAIK, that count includes Publicize global accounts on wp.com while it is only subscribers on Jetpack sites.

Regarding if we need to communicate this, I'll check with the team. I would lean that majority of folks would be happy with this, but I'll ask for more input.

**Comment by kraftbj** [comment]
To follow up on the above, we're a go for this change. The intent of the number is to convey the reach of the site owner through subscriptions, which in modern day usage is multi-channel. Including the verified/connected accounts will give a more accurate impression of the site's reach than the current number.

**Comment by dcoleonline** [comment]
530645-t AT: another push for this. It feels like a downgrade for users on the WordPress.com Business plan who have previously seen a larger follower number before upgrading.

**Comment by carinapilar** [comment]
Got a user on live chat questioning this too: 540921-hc. They had 4k+ followers and after ATing the site it's showing only 200+.

**Comment by rachelmcr** [comment]
@kraftbj You mentioned that we're a go for this change; do you know if this is slated to be worked on for an upcoming Jetpack release? (We received another request from an Atomic site owner in 199696-h.)

**Comment by kraftbj** [comment]
No, as far as I know. It is likely a two or three line change on WP.com and won't need a JP release.

/mu-plugins/jetpack/class.jetpack-xmlrpc-server.php#479 is using `wpcom_subs_total_for_blog`. I think we can use  `wpcom_reach_total_for_blog` from /mu-plugins/subscriptions.php#1096 if we changed it to accept a blog_id arg and only do the current behavior if not present.

I hadn't deeply researched it until now. I can put together a patch but need a WP.com committer to review/commit.

**Comment by tmmbecker** [comment]
617232-zen

**Comment by rralian** [comment]
I've been sitting on this fix for way too long, my apologies. I just committed the fix today (it's in wpcom code). The value gets cached, so users may not notice the change immediately. Probably within a day. Going to close now tho.

**Comment by KokkieH** [comment]
Just a note that we had a request via [Twitter](https://twitter.com/KevinMuldoon/status/898514719774035969) to make showing the combined total optional. I've explained the rationale behind this, though, as per @kraftbj's comment above.

**Comment by StefMattana** [comment]
Also in here, something similar: 904483-zen
