### ISSUE TITLE
"Custom CSS" module does not allow searching in the invisible section of "Additional CSS"

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#8000]
### Steps to reproduce the issue

* Enable Jetpack and the Custom CSS module. 

* Add a long CSS code. You can try to the CSS code below, do not care about the duplicate CSS code. There are two strings: `special-keyword-above` and `special-keyword-below`: 

```
/*
You can add your own CSS here.

Click the help icon above to learn more.

special-keyword-above 

*/

@media screen and (min-width: 900px) {
    .share-jetpack-whatsapp {
        display: none !important;
    }
}


@media screen and (min-width: 900px) {
    .share-jetpack-whatsapp {
        display: none !important;
    }
}


@media screen and (min-width: 900px) {
    .share-jetpack-whatsapp {
        display: none !important;
    }
}


@media screen and (min-width: 900px) {
    .share-jetpack-whatsapp {
        display: none !important;
    }
}


@media screen and (min-width: 900px) {
    .share-jetpack-whatsapp {
        display: none !important;
    }
}


@media screen and (min-width: 900px) {
    .share-jetpack-whatsapp {
        display: none !important;
    }
}


@media screen and (min-width: 900px) {
    .share-jetpack-whatsapp {
        display: none !important;
    }
}



@media screen and (min-width: 900px) {
    .share-jetpack-whatsapp {
        display: none !important;
    }
}


@media screen and (min-width: 900px) {
    .share-jetpack-whatsapp {
        display: none !important;
    }
}


@media screen and (min-width: 900px) {
    .share-jetpack-whatsapp {
        display: none !important;
    }
}


@media screen and (min-width: 900px) {
    .share-jetpack-whatsapp {
        display: none !important;
    }
}


@media screen and (min-width: 900px) {
    .share-jetpack-whatsapp {
        display: none !important;
    }
}

@media screen and (min-width: 900px) {
    .share-jetpack-whatsapp {
        display: none !important;
    }
}


@media screen and (min-width: 900px) {
    .share-jetpack-whatsapp {
        display: none !important;
    }
}

@media screen and (min-width: 900px) {
    .share-jetpack-whatsapp {
        display: none !important;
    }
}

/* 
special-keyword-below
*/ 
``` 
* Open Customizer -> Additional CSS, try to search `special-keyword` by using the browser search function (I am using Chrome). There will be just one result. 

### What I expected

* There are two results. 

### What happened instead

* There is just one result. 

### Other tests: 

* If I disable the Custom CSS module, do the same steps above, I will have 2 results as expected. 

### Workaround. 

* The workaround is to disable the Custom CSS module of Jetpack - https://jetpack.com/support/control-jetpacks-modules-on-one-page/ 

* However, there will be no highlight syntax CSS editor if this module is inactive. 

### Other notes: 

* Ticket: 737590-zen

**Comment by htdat** [comment]
### Screenshot - with "Custom CSS" active 

![2017-10-17_11-55-20](https://user-images.githubusercontent.com/10045087/31647406-2e5e3a1a-b332-11e7-9e79-dd7313aade57.png)

### Screenshot - without "Custom CSS" 

![2017-10-17_11-53-52](https://user-images.githubusercontent.com/10045087/31647408-308d9bf0-b332-11e7-81a0-72f642298e63.png)

**Comment by jeherve** [comment]
Closing as this area is managed by core itself now.
