### ISSUE TITLE
Open Graph: The logo set in the customizer for Site Identity is not taken in account

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#8008]
The Site icon or Jetpack-provided Theme Logo work as images to use here but it's not the case for core's Logo set through the customizer.  

#### Steps to reproduce the issue

1. Using Twenty Seventeen on a site without a configured site icon 
1. Set up a log in Customizer -> SIte Identity -> Logo (Save & publish)
1. get to the homepage of your site.
1. Check the source HTML and find `og:image`. 
1. It should be pointing to `blank.jpg` instead of the image you chose.

#### What I expected

I expected the logo to be used as `og:image.`

#### What happened instead

The `og:image` tag links to `https://s0.wp.com/i/blank.jpg`

**Comment by jeherve** [comment]
For reference:
- What we support now: https://jetpack.com/support/site-logo-2/
- What we should support as well: https://codex.wordpress.org/Theme_Logo

**Comment by oskosk** [comment]
Closing as old
