### ISSUE TITLE
PHP 7.2 compatibility: create_function() is deprecated

### ISSUE THREAD

**Issue by todeveni** [Automattic/jetpack#8010]
PHP 7.2 throws a deprecation notice for `create_function()`.

**Deprecated**: Function `create_function()` is deprecated in `/modules/stats.php` on line 669

This shows up at least on admin dashboard stats widget and in `/wp-admin/admin.php?page=stats`.

**Comment by jeherve** [comment]
Thanks for the report. We use `create_function()` in a few other places so we will need to do a bit of cleanup.

**Comment by jeherve** [comment]
Master issue: #8156
