### ISSUE TITLE
Search: add UI for triggering a bulk reindex of a site, and status

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#8024]
We should add a Calypso UI for triggering a reindex of the site. There is already an endpoint for doing this for Related Posts, so the Related Posts UI should be moved over.

In addition we should be able to provide some basic status and an estimate of how long indexing will take. The status/estimate can just be based off of the memcache keys we set to prevent duplicate indexing jobs.

If the site has a VIP index, then the status should show the status for both indices since they are independent processes.

**Comment by jeherve** [comment]
We had moved the reindex button to Calypso a few releases ago when Sync was added; maybe that's where the Search UI should live, too:

![screenshot 2017-10-20 at 13 40 05](https://user-images.githubusercontent.com/426388/31819265-38906910-b59c-11e7-9d6b-b5417352af7f.png)

**Comment by gravityrail** [comment]
@jeherve and @gibrown I think we should just tell users to use the "resync" feature as a way of reindexing their site.

Since we can't always know if the issue is syncing or indexing, and since syncing does BOTH, this seems like a more reliable (if slow and expensive) way to address issues.

**Comment by gibrown** [comment]
@gravityrail that sounds reasonable. Closing this. @jeherve as things roll out we can see how this all goes and reopen.
