### ISSUE TITLE
Jetpack not compatible with PHP 7.1

### ISSUE THREAD

**Issue by ankurshva** [Automattic/jetpack#8031]
Site cannot be accessed with PHP 7.1

**Comment by jeherve** [comment]
Jetpack should be compatible with PHP 7.1, as we've worked to solve compatibility issues in the past few releases (see #6106).

Would you be able to run some additional tests on a site using the most recent version of the plugin, so we can find our more? Could you add the following to your site's wp-config.php file? 

`
define( 'WP_DEBUG', true );

if ( WP_DEBUG ) {

        @error_reporting( E_ALL );
        @ini_set( 'log_errors', true );
        @ini_set( 'log_errors_max_len', '0' );

        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', false );
        define( 'CONCATENATE_SCRIPTS', false );
        define( 'SAVEQUERIES', true );

}
`

Your `wp-config.php` file may already include a line that says "define('WP_DEBUG', false);". You can remove it, and replace it by the code above.

Once you've done so, try to reproduce the issues and then check the `wp-content/debug.log` file for errors, and paste the results here. You can then replace `define('WP_DEBUG', true);` by `define('WP_DEBUG', false);` in the code above.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
