### ISSUE TITLE
Sharing: Enable Featured Image regardless of the theme

### ISSUE THREAD

**Issue by timdream** [Automattic/jetpack#8040]
#### Steps to reproduce the issue

0. Using a custom WordPress theme that didn't opt-in Featured Image
1. Turn on Jetpack sharing
2. Inspect the source code of a post page

#### What I expected

1. Somewhere in the wp-admin editor allowing me to set `og:image`.
2. There are various Open Graph tags being generated, including og:image when a feature image is set.

#### What happened instead

1. There are various Open Graph tags being generated, but there is no og:image.
2. There is no way to set a feature image in the wp-admin editor.

#### Note

Calypso allow you to set a feature image in post editor regardless of theme support. I did that and `og:image` shows up. According to [here](https://developer.wordpress.org/themes/functionality/featured-images-post-thumbnails/#enabling-support-for-featured-image) featured image is something that needs to be opt-in by the theme.

Given that Jetpack is using Featured Images irrespective of the theme, it should opt-in the feature in wp-admin editor.

**Comment by timdream** [comment]
I wonder if this should be filed on the Core instead since there aren't obvious way to do this in Jetpack alone. Maybe a new filter is needed?

**Comment by jeherve** [comment]
I think we should be able to fix this by declaring support for post thumbnails as soon as we have to output Open Graph tags:
`add_theme_support( 'post-thumbnails' );`

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
