### ISSUE TITLE
PWA: Localhost is a secure origin

### ISSUE THREAD

**Issue by caraya** [Automattic/jetpack#8044]
#### Steps to reproduce the issue
I checked out the add/pwa branch and compiled Jetpack (yarn distclean && yarn build) then opened Jetpack settings and tried to activate "Enable Progressive Web App (PWA) features"

#### What I expected
I expect to be able to activate PWA features group and individual features in my local development system. 

#### What happened instead
I get this message: _SSL not detected. Progressive Web Apps require that your web site is served using HTTPS._ This is not necessary when you're working in localhost for development.  According to MDN:

> In order to facilitate local development, localhost is considered a secure origin by browsers as well.

Since Jetpack is already testing whether I'm in localhost it should allow Service Workers and PWA features when working in localhost

**Comment by jeherve** [comment]
Thanks for the feedback!

Since this is still a work in progress, I would recommend that you add your comments and suggestions on the related PR: #7963
