### ISSUE TITLE
Sync: use the API to update wp_options instead of accessing the database directly

### ISSUE THREAD

**Issue by cena** [Automattic/jetpack#8048]
mySQL INSERT IGNORE not valid syntax on Microsoft SQL

SQL: Microsoft SQL
server: Azure
WP install: [Project Nami](http://projectnami.org/)

PHP_VERSION: 5.6.31 
WORDPRESS_VERSION: 4.8.2 
JETPACK__VERSION: 5.4 

ZD: 750590-zen

User reported ability to connect Jetpack with the following error:
```
[body] => {'error':'Jetpack not connected','error_description':'We were 
unable to find a Jetpack instance on your site. Please connect Jetpack to your 
WordPress.com account from within your WordPress admin.'} 
[response] => Array 
( 
[code] => 400 
[message] => Bad Request 
```

He later replied that he'd fixed the issue, which was caused by Microsoft SQL not recognizing the INSERT IGNORE syntax.

Error:
```
[23-Oct-2017 01:08:30 UTC] WordPress database error [Microsoft][ODBC Driver 11 for SQL Server]
[SQL Server]Incorrect syntax near the keyword 'INTO'. Code - 156 for query INSERT IGNORE
 INTO wp_options ( option_name, option_value, autoload )
 VALUES ( 'jetpack_secrets',
```

I've asked the user if he would share the code that fixed this, and will update accordingly.

**Comment by jeherve** [comment]
Related:
https://github.com/Automattic/jetpack/commit/47d337874ffce75245816f1c343a390262f7adc6

Here's the issue detailed on the ProjectNami repo:
https://github.com/ProjectNami/projectnami/issues/237

**Comment by lezama** [comment]
Fixed in https://github.com/Automattic/jetpack/pull/7875

Users hitting issues with Jetpack accessing the DB directly are going to be able to force Jetpack to use the core API by setting `JETPACK_DISABLE_RAW_OPTIONS`

**Comment by jeherve** [comment]
@cena Could you let the site owner know that they can solve the issue by adding the following to their site's `wp-config.php`?

```php
define( 'JETPACK_DISABLE_RAW_OPTIONS', true );
```

Thanks!
