### ISSUE TITLE
Stats request: Allow contributors see their own post stats only

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#8057]
As `I’m a Contributor, Writer or other non-Admin role on the site and now can’t see stats` in https://jetpack.com/support/wordpress-com-stats/ , non-admin roles can see the stats for the whole site. 

It's great to have the option let contributors see their own post stats only. 

### Note: 

On WordPress.com sites, this is slightly different. Currently, there is no option to control this like Jetpack sites. 

> All of your site’s user roles can see the stats: Administrators, Editors, Authors, and Contributors.
> (Quote from https://en.support.wordpress.com/user-roles/#summary)

--- 

Ticket: 756259-zen

**Comment by jeherve** [comment]
Closing as duplicate of #5387
