### ISSUE TITLE
Stop adding hacky shortcode implementation to widgets and let Core do the work.

### ISSUE THREAD

**Issue by georgestephanis** [Automattic/jetpack#8059]
Contact Form should stop messing with how Text Widgets process shortcodes in WP4.9+ since @westonruter committed https://github.com/WordPress/WordPress/commit/84d2c511537c70ea7063d5a2d31ce419a23c0450

We currently do:

https://github.com/Automattic/jetpack/blob/a64eb3cc3b822a426dfc6c110c6e8bc214008254/modules/contact-form/grunion-contact-form.php#L99-L102

but the core implementation is on a different action -- `add_filter( 'widget_text_content', 'do_shortcode', 11 );`

We should add a caveat there.

**Comment by westonruter** [comment]
It could simply add a version check since it is not needed in ≥4.9:

```php
if ( version_compare( get_bloginfo( 'version' ), '4.9', '<' ) && ! has_filter( 'widget_text', 'do_shortcode' ) ) { 
```
