### ISSUE TITLE
Likes: Add "Likes" support for CPTs

### ISSUE THREAD

**Issue by seejacobscott** [Automattic/jetpack#8074]
Currently, when using a plugin like WooCommerce or some recipe plugins there is seemingly no way to have the "Likes" option display under the content, but in the post editor, you do still have the option to display likes along with the sharing buttons. 

Steps to reproduce: 

1) Create a product, recipe or other custom content type
2) Enable likes in the "Likes and Shares" screen option. 
3) Publish custom post
4) No like button appears. 

Reported in 762213-zen

**Comment by jeherve** [comment]
Likes should already appear in CPT, as long as the option is set under Settings > Sharing to display posts for that CPT. Here is an example:
https://jeremy.hu/watched/janet-and-michael/
