### ISSUE TITLE
"Schedule Consultation" banner gets overlapped by Gutenberg toolbar

### ISSUE THREAD

**Issue by cfinke** [Automattic/jetpack#8080]
Running WordPress 4.9RC, Jetpack 5.4, and Gutenberg 1.6.0.

<img width="1078" alt="screen shot 2017-10-31 at 2 24 54 pm" src="https://user-images.githubusercontent.com/435369/32249892-c5efb8d4-be47-11e7-80f7-4acb8d503fe6.png">

**Comment by jeherve** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/issues/3214
