### ISSUE TITLE
Press This: remove button from Multisites running WP 4.9 and where the plugin is not installed

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#8097]
In WordPress 4.9, Press this will disappear from Core and will require a plugin:
https://make.wordpress.org/core/2017/11/02/press-this-in-4-9/
https://wordpress.org/plugins/press-this/

Since we offer a "Press This" button that relies on `/wp-admin/press-this.php` in Jetpack (for Multisite networks only), I think we should only make the sharing service available if:
- The site does not use WP 4.9 yet.
- The site uses 4.9 and the plugin is network activated.

@kraftbj Does that seem reasonable?

**Comment by kraftbj** [comment]
Damn, forgot about Jetpack's usage. The way Jetpack uses it right now, it won't work even with the plugin installed (the bookmarklet is deprecated). I'll push up an immediate patch to remove it that would be safe for 5.5 to not delay/keep compat while looking at a better solution.
