### ISSUE TITLE
Carousel: comment text is not wrapping around the avatar

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#8110]
> comments appear a little weird – comment text is not wrapping properly around the avatar:

![q_vyrmmlgu](https://user-images.githubusercontent.com/426388/32377710-d0d55b4c-c0a8-11e7-8402-d6bdfb697893.png)

**Comment by scottsweb** [comment]
Just tested this in 2019 and I am seeing a much smaller gap:

![Screenshot 2019-04-25 at 16 52 22](https://user-images.githubusercontent.com/411945/56749915-92518d80-677a-11e9-9e1e-c3c56fdf706a.png)

I appreciate this is quite an old issue now, do you happen to know what theme this was tested in?

In 2017 the gab seems quite a bit bigger:

![Screenshot 2019-04-25 at 16 53 59](https://user-images.githubusercontent.com/411945/56750046-d6dd2900-677a-11e9-9392-f9802aa2041f.png)

Different again in 2016:

![Screenshot 2019-04-25 at 16 55 15](https://user-images.githubusercontent.com/411945/56750085-f2e0ca80-677a-11e9-8977-c12d66f595fe.png)

So we look to be inheriting quite a bit of style here from the actual theme.

This makes me think we might need to be more deliberate in providing styles that work in both the light and dark themes? Either that or a #wontfix :)

What do you think @MichaelArestad?

**Comment by MichaelArestad** [comment]
> This makes me think we might need to be more deliberate in providing styles that work in both the light and dark carousel themes? Either that or a #wontfix :)

I think the carousel themes are long overdue for a rewrite. They're particularly bad on mobile. For now, we could attempt to harden the styles against theme style collisions. I'm open to ideas on that front. Probably the simplest would be to include an ID in each selector like `#jetpack-carousel .comment-content {}` etc. It won't stop everything, but would help a little. There's also going to be some property bleed unless we write some sort of reset.
