### ISSUE TITLE
Search: using tag/category directly in searches is probably broken

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#8114]
I don't think this is yet affecting anyone, I found it while looking at something else (but I could be wrong).

We have previously used the "index_name" mapping setting as an alias mechanism to allow querying the "tag.name" field with just the field name of "tag". "index_name" was removed in ES 2.4: https://www.elastic.co/guide/en/elasticsearch/reference/2.4/breaking_20_mapping_changes.html#_literal_index_name_literal_and_literal_path_literal_removed

I think there may still be some cases where this will not work properly. Most likely for VIPs.

Need to audit the code and make sure we won't break anyone. It is possible that VIPs are explicitly filtering/aggregating by "tag".

cc @nickdaugherty

**Comment by nickdaugherty** [comment]
To be sure I understand, if a site _were_ using `tag` as the aggregation, the fix would be to switch to `tag.name` instead?

**Comment by gibrown** [comment]
Yes

**Comment by gibrown** [comment]
@nickdaugherty erased my previous response. you can't actually run an aggregation on tag.name because it is an analyzed field. The aggregation should run on tag.slug or tag.term_id (I think this is what it does).

This more affects searching against tags and categories where we should search against tag.name and category.name (for VIP indices), and tag.name.<lang> and category.name.<lang> for global index.

**Comment by gravityrail** [comment]
@nickdaugherty I made the necessary changes on WPCOM and shipped, as per linked PR, but could you take a look and make sure I didn't break anything?

**Comment by nickdaugherty** [comment]
We should be good to go as far as existing uses of this are concerned. 👍
