### ISSUE TITLE
Copy on plans page: change "Marketing Automation" to "Automated Social Sharing"

### ISSUE THREAD

**Issue by nicoleckohler** [Automattic/jetpack#8122]
**To see this currently:**
- visit jetpack.com/plans/yoursiteurl.com (where "yoursiteurl.com" is any site currently connected to Jetpack, ex. nicoleckohler.com)
- look at the copy in the Premium section:

<img width="332" alt="screen shot 2017-11-06 at 2 25 31 pm" src="https://user-images.githubusercontent.com/11754291/32471784-1202edec-c32d-11e7-8ae1-49071c3a6b24.png">

I think this screenshot is from another page/view -- can't remember how I found it, but basically:

**What should change:**
Let's please change "Marketing Automation" to "Automated Social Sharing" -- if that doesn't fit, "Social Scheduling" might work (but let me know). This applies both to the URL I shared above and anywhere else the phrase might pop up (if anywhere).

Marketing automation as a term is a) something Jetpack doesn't really provide, and b) confusing some users, since they expect more than Publicize. :)

Also, when viewing the tooltip for this item (on the same page) it's coming up as empty for me. Not sure if it's because of a previously reported bug or because there is just no content provided. **If there's no content, let me know and I'll write some ASAP.**

cc and hat tip to @sageBrownell who spotted this!

**Comment by jeherve** [comment]
Could you open this issue in [the Calypso repo](https://github.com/Automattic/wp-calypso/issues), since that's where the plans pages live? We will not be able to change the content here.

Thanks!
