### ISSUE TITLE
Integrate PHPCompatibility sniffs into CI toolchain

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/jetpack#8126]
The [PHPCompatibility sniffs](https://github.com/wimg/PHPCompatibility) help to identify PHP compatibility issues between versions. It would be helpful to integrate into the CI toolchain so Jetpack developers know when code changes have/introduce incompatible code.

In a [data analysis project I'm doing right now](https://github.com/danielbachhuber/php-compat-command/), Jetpack is the most common failed plugin. The failure is caused by use of removed `$HTTP_RAW_POST_DATA` ([explanation](https://github.com/danielbachhuber/php-incompatibility/blob/master/RemovedGlobalVariables.http_raw_post_dataDeprecatedRemoved.md)):

* https://github.com/Automattic/jetpack/blob/edddd6bd8e02f383dc0a0bedc65ecdec09cda7f4/modules/markdown/easy-markdown.php#L660
* https://github.com/Automattic/jetpack/blob/2d531cad637deb97548eccfa532093096ae21231/class.jetpack.php#L5478
* https://github.com/Automattic/jetpack/blob/32e2d44d1aa94a6154bac115c77ddaf7b548ca34/class.jetpack-signature.php#L65

For further reference, [here's a cache of Jetpack v5.4 scan results](https://github.com/danielbachhuber/php-compat-cache/blob/master/plugins/jetpack/jetpack.5.4.json).

Related #4346

**Comment by zinigor** [comment]
This is great, thanks for letting us know about this! But I have a question: we have been looking at `$HTTP_RAW_POST_DATA` before when we were figuring out the changes needed to make Jetpack compatible with PHP 7.1. And it turns out that in these cases that global variable warning is a red herring - we repopulate `$HTTP_RAW_POST_DATA` to make sure we're compatible with PHP versions that still use it.

Do you know if there's a way to mark such occurences as false positives?

**Comment by danielbachhuber** [comment]
> And it turns out that in these cases that global variable warning is a red herring - we repopulate `$HTTP_RAW_POST_DATA` to make sure we're compatible with PHP versions that still use it.

I see this only happening in `Jetpack->wp_rest_authenticate()`:

https://github.com/Automattic/jetpack/blob/2d531cad637deb97548eccfa532093096ae21231/class.jetpack.php#L5350

To my understanding, the two other contexts I identified (`jetpack/modules/markdown/easy-markdown.php`) and (`jetpack/class.jetpack-signature.php`) don't necessarily follow this codepath. Is this not the case?

Also, is there a reason you don't simply switch to `file_get_contents( 'php://input' );`?

> Do you know if there's a way to mark such occurences as false positives?

Yes, you have two options:

* `// @codingStandardsIgnoreLine` to ignore a single following line.
* `// @codingStandardsIgnoreStart` and `// @codingStandardsIgnoreEnd` to ignore multiple lines.

**Comment by brbrr** [comment]
Fixed in https://github.com/Automattic/jetpack/pull/9905
