### ISSUE TITLE
Widgets: Port the WordPress.com "My Community" widget

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#813]
A user requested this widget be available for Jetpack:

http://en.support.wordpress.com/widgets/my-community/

Requested in 1885769-t

**Comment by chaselivingston** [comment]
2101541-t

**Comment by samhotchkiss** [comment]
:+1:

**Comment by ntpixels** [comment]
Another user in 2219966-t

**Comment by csonnek** [comment]
2503672-t

**Comment by jeherve** [comment]
Fixed in #3358
