### ISSUE TITLE
Show all widgets in development mode

### ISSUE THREAD

**Issue by dsifford** [Automattic/jetpack#8131]
This is sort of a huge issue IMHO. 

I understand that widgets won't function properly if the site is not connected to a network, but at the very least they should render with dummy content so that developers can ensure that the widgets are styled appropriately and do not conflict with whatever else they might be working on.

Please, please... Please..... Consider changing this behavior.

#### Steps to reproduce the issue
1. Open up any jetpack site on localhost

#### What I expected

All widgets that are set in production to show up in development.

#### What happened instead

Subscription widget and top post widget gone.

Thanks in advance for your hard work on the plugin. No disrespect at all. But pleeeeeeeeeeeeeeeeease change this behavior. I can not stress this enough. This is creating in a sense two sources of "truth" and causing headaches.

**Comment by jeherve** [comment]
Thanks for the feedback. It does indeed make local development more difficult, as you then need to have a live sandbox to be able to style those elements.

It has been discussed in the past in #385, so I'll close this issue as a duplicate. Feel free to chime in on the other issue if you'd like.

Thanks again for the feedback.
