### ISSUE TITLE
Publicize: change custom message length to 280 chars now that Twitter supports it

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#8134]
#### Steps to reproduce
1. Starting in Posts > Add New.
2. If you use Publicize on your site, you will see the following box:

![screenshot 2017-11-09 at 13 37 59](https://user-images.githubusercontent.com/426388/32605811-398f391a-c553-11e7-9357-4be7f9642ceb.png)

Since Twitter now supports more characters, it would be nice to expand the limit accordingly:
https://blog.twitter.com/official/en_us/topics/product/2017/tweetingmadeeasier.html

Related:  https://github.com/Automattic/wp-calypso/issues/19630

**Comment by richardmtl** [comment]
Mentioned in https://wordpress.org/support/topic/publicize-chops-post-titles-on-twitter-despite-their-new-280-character-limit/

**Comment by lizkarkoski** [comment]
A request for Jetpack to match the new Twitter characters has come through to us on Twitter: 
https://twitter.com/ChrisWCPowell/status/930494131050352640

**Comment by jeherve** [comment]
Related: D8438-code
