### ISSUE TITLE
Search: Create UI for selecting which CPTs to filter and auto detect

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#8139]
Right now all public CPTs are included in search results. For many plugins this is not the best default user experience.

Although there is a filter that let's the user manage this, it is a core enough detail that we should built some UI into Calypso.

A good example is for WooCommerce where if we detect that it is enabled, we should disable showing some things in search: "CPTs for Wish Lists and Testimonials"

Or maybe we should just deprioritize those. Needs some experimentation and feedback.

I think the UI for this should just be a listing of all of the public CPTs we see on the site and then most of them are enabled by default.

**Comment by douglsmith** [comment]
I would prefer that only a few known safe types are pre-selected (posts, pages, products) and the rest have to be specifically whitelisted. So many plugins can add a variety of CPTs at any time that a mostly-enabled, blacklisting approach has too many opportunities for unintentional content to be exposed publicly.
