### ISSUE TITLE
Masterbar: Logging out Redirects to undefined Page

### ISSUE THREAD

**Issue by sageBrownell** [Automattic/jetpack#8142]
Title is rather self-explanatory -- when logging out of a site that has the WordPress.com Toolbar active, the user is redirected to /wp-admin/undefined (404) instead of the Login form for their site.

Once the WordPress.com Toolbar has been deactivated, the user is redirected as expected.

Reported here: 769871-zen

**Comment by jeherve** [comment]
cc @vindl

**Comment by ehti** [comment]
Was experiencing it on Atomic & thought it's my browser. 😅 
User report in #800324-zen

I see a PR is ready - that's awesome
