### ISSUE TITLE
Photon: Conflict with WooCommerce's product image zooming

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#8150]
#### Steps to reproduce the issue
1. Activate Photon on a Jetpack connected site.
2. Visit a WooCommerce product page and attempt to hover over the product image to zoom in.
3. Notice that the image just layers over itself but doesn't zoom.

![screen capture on 2017-11-13 at 09-39-54](https://user-images.githubusercontent.com/831377/32731604-485aef18-c858-11e7-9d42-06409fec5df8.gif)

760456-zen

**Comment by jeherve** [comment]
I can't seem to be able to reproduce anymore. Closing. Feel free to reopen if this becomes relevant again.
