### ISSUE TITLE
Sharing buttons: Javascript issue with official Google+ button

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#8151]
Originally reported here: https://wordpress.org/support/topic/5-5-official-google-button-not-showing/

![vuqmhpy](https://user-images.githubusercontent.com/3676359/32735476-d7c442f8-c862-11e7-9bb8-3c29056d4760.png)

I was able to reproduce, though I don't get quite the same javascript errors on my test site.

**Comment by jeherve** [comment]
Closing as duplicate of #8129
