### ISSUE TITLE
Email Sharing error "Post was not sent - check your email addresses!"

### ISSUE THREAD

**Issue by jjaureguiberrry** [Automattic/jetpack#8154]
![selection_191](https://user-images.githubusercontent.com/10959263/32757247-484caa2e-c8bd-11e7-83ce-92dc23cee44a.png)

This only happens when there is more than one instance of the sharing buttons in the same page. i.e. when sharing buttons are rendered before and after post content. 

I tested this in Chrome Version 56.0.2924.87 (64-bit) / Linux Mint

I debugged the code and I can see that the problem relies on the jQuery selector for source and target email inputs, which is returning an array of objects since the same element ID is used twice (not compliant). 

I solved this by modifyig the file /jetpack/modules/sharedaddy/sharing.js and changing the selecctor on the submit handler (from line 381) from this:
$( '#sharing_email input[name=source_email]' )
to this:
form.find( 'input[name=target_email]' )

Of course, this needs to be done for both, source and target email inputs.

I would love to see this fix in the core soon.

Thanks!

**Comment by jeherve** [comment]
Thanks for the report!

> I would love to see this fix in the core soon.

If you'd like you can submit a patch by following the instructions here:
https://github.com/Automattic/jetpack/blob/master/.github/CONTRIBUTING.md#write-and-submit-a-patch
