### ISSUE TITLE
sync : init_full_sync_listeners() redeclare multiple time.

### ISSUE THREAD

**Issue by Umangvaghela** [Automattic/jetpack#8155]
In sync, multiple files use the same function name to call add action.

https://github.com/Automattic/jetpack/blob/master/sync/class.jetpack-sync-module-callables.php#L48
https://github.com/Automattic/jetpack/blob/master/sync/class.jetpack-sync-module-comments.php#L74
https://github.com/Automattic/jetpack/blob/master/sync/class.jetpack-sync-module-constants.php#L17
https://github.com/Automattic/jetpack/blob/master/sync/class.jetpack-sync-module-full-sync.php#L23
https://github.com/Automattic/jetpack/blob/master/sync/class.jetpack-sync-module-options.php#L27

#### What I expected 
Use the different function name to achieve the functionality.

If its call callable function so  use "callables" like ( ** init_full_sync_listeners_callables()** ) so we overcome the problem.
https://github.com/Automattic/jetpack/blob/master/sync/class.jetpack-sync-listener.php#L43

#### What happened instead
get Fatal error: Cannot redeclare init_full_sync_listeners()

**Comment by oskosk** [comment]
@Umangvaghela could you provide more information on how to reproduce?. These functions you mention that have the same name are all class methods and shouldn't overlap. Anything, PHP version, WP version, or better if possible, a stack trace would be helpful.

**Comment by Umangvaghela** [comment]
@oskosk 

Sir, Thanks for the reply. Normally we couldn't  define the same function multiple time. when I see the sync code and there I found this bug.

**Comment by enejb** [comment]
@Umangvaghela Can you give us an example of how you are using the sync code that is causing the error?

**Comment by Umangvaghela** [comment]
@oskosk, @enejb 

Thanks for all.

I understand the issue and I want to close this issue and PR as well as. When I get an error another time after I will post issue.

Thanks
