### ISSUE TITLE
Warning: filemtime() stat failed

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#8162]
There seems to be an issue with `implode_frontend_css()` and `filemtime()`:

![screen shot 2017-11-14 at 9 59 39 am](https://user-images.githubusercontent.com/349751/32796162-c1ac9068-c922-11e7-8db0-d931bf40a861.png)

**Comment by jeherve** [comment]
Could you make sure the plugin is built on your end? These errors usually happen when the plugin has not been built.

**Comment by kwight** [comment]
Yep, looks like that was it – thanks @jeherve !
