### ISSUE TITLE
Jetpack: Concierge popup/tooltip appears under the WordPress editor.

### ISSUE THREAD

**Issue by bisko** [Automattic/jetpack#8163]
#### Steps to reproduce the issue
Open a post for editing while having a Jetpack site with Premium plan.

#### What happens

Concierge popup appears under the WordPress editor toolbar. 

<img width="1306" alt="screen shot 2017-11-14 at 14 01 05" src="https://user-images.githubusercontent.com/184938/32797071-47708938-c979-11e7-9da7-4994b560eab0.png">

#### Notes:
* WordPress 4.8.3
* I have Gutenberg installed if that will help with debug

**Comment by jeherve** [comment]
Closing in favour of https://github.com/Automattic/jetpack/issues/8080
