### ISSUE TITLE
Fatal error in admin - plugin_action_links

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#8164]
Originally reported here: https://wordpress.org/support/topic/jetpack-causing-error-in-admin-page/

Fatal errors in admin with Jetpack 5.5; one user said:

> all errors seems to track to `plugin_action_links` filter.

Likely related to #7944

**Comment by jeherve** [comment]
@enejb Do you think you could take a look at this?

Thanks!

**Comment by enejb** [comment]
Do we have an idea what PHP version this is causing problems for.
I wasn't able to replicate the issue just yet.

**Comment by enejb** [comment]
@richardmtl and @jeherve any idea how to replicate this issue?

**Comment by richardmtl** [comment]
@enejb one user replied with their list of plugins (a lot!); they also confirm that they are using PHP 7.0.25:

```
24liveblog
Above The Fold Optimization
Accelerated Mobile Pages
Activity Log
Ad Inserter
Advanced Ads
Advanced AMP ADS
Akismet Anti-Spam
ARVE Advanced Responsive Video Embedder
Autoptimize
Column Shortcodes
Contact Form 7
Crayon Syntax Highlighter
Dashboard Site Notes
Disqus Comment System
Easy HTTPS (SSL) Redirection
Feedzy RSS Feeds Lite
FooBox Image Lightbox
FooGallery
Google Analytics for WordPress by MonsterInsights
Google Authenticator
Lightweight Social Icons
NextScripts: Social Networks Auto-Poster
Nofollow for external link
P3 (Plugin Performance Profiler)
Page Links To
Regenerate Thumbnails
Related Posts By Taxonomy
Restrict Widgets
Shield
Shortcake (Shortcode UI)
Simple Breaks
SSL Insecure Content Fixer
Table of Contents Plus
TablePress
TinyMCE Advanced
TwentyTwenty
User Role Editor
W3 Total Cache
Widget Context
WP Editor
WP Mail SMTP Plugin by Mail Bank
WP Maintenance Mode
WP Missed Schedule
WP Smush
WP User Avatar
WP-Optimize
WPSSO Core
Yoast SEO
```

Other than that, no idea how to reproduce it, it's only been mentioned on that thread, with 3 reports.

**Comment by enejb** [comment]
Can we ask the user to confirm if master stable now fixes the issues for them?

**Comment by michaeltorbert** [comment]
If I'm not mistaken, it's in both Jetpack and Akismet and is causing a fatal error our users are attributing to us: https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1353

**Comment by jeherve** [comment]
@enejb I've asked them to try.

@michaeltorbert Thanks for the report, and sorry for the trouble! We'll get this fixed on our end as well.

**Comment by michaeltorbert** [comment]
@jeherve Awesome! We're releasing a workaround this morning as well. 
No apologies needed, these things happen. I appreciate you all being on top of it. :)

**Comment by csonnek** [comment]
Reported in 802459-zen - advised them that the fix will be in the next JP release.

**Comment by jeherve** [comment]
Closing this as #8167 seems to help.

The patch will be part of 5.5.1, scheduled to be released in the next couple of days

**Comment by jeherve** [comment]
Reopening as the problem still exists in some scenarios.

- 1105162-zen

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
