### ISSUE TITLE
EU Cookie Law Widget - not always floating/sticking to bottom of viewport

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#8166]
This might be a theme issue. Originally reported in https://wordpress.org/support/topic/eu-cookie-law-widget-doesnt-show-up/

For default themes, the widget output "floats" at the bottom of the viewport. However, for some themes (in this case, [Kahuna](https://wordpress.org/themes/kahuna/) and [Graphene](https://wordpress.org/themes/graphene/)), the widget output is not floating / sticking to the bottom of the viewport. Instead, it is showing up in the widget area in the footer of the site (if that's the widget area where it was placed), so site visitors would need to scroll all the way down the site in order to see it. Is this something that we can fix in the widget, or will certain themes always cause this problem?

**Comment by richardmtl** [comment]
CSS suggested by the user:

```
.widget-container.widget_eu_cookie_law_widget {
    margin: 0 auto;
    padding: 0;
	position: fixed;
	bottom: 0;
	width: 100%;
	z-index:1000;
}
```

**Comment by rsjazz** [comment]
I have the same problem. I am hosted on wordpress.com. How can I inject CSS?

**Comment by rsjazz** [comment]
I shall provide some more details. My blog http://rsjazz.wordpress.com runs an a minimally customized out of the box theme. I configured the EU Cookie Law Widget. 

It shows up but only on the bottom of the pages. There is basically no chance for any user to see the widget to show up that way. The chance that a user will ever be able to see the widget is not existent since the use would have to scroll way down on the main page. 

The cookie should show on the bottom of the visible canvas similar to the administration widget. Can that be achieved?

I am not sure where and how I would be able to inject css like the above in the case of running my blog on wordpress.

**Comment by jeherve** [comment]
@rsjazz Thank you for the report. That is something we will need to fix in your theme directly I believe. 

@laurelfulford Do you think you could take a look, since you've been looking at GDPR and WordPress.com themes?

Thank you!

**Comment by laurelfulford** [comment]
@jeherve It looks like some of the EU Cookie Law widget styles rely on there being a `.widget` class on each widget area:

https://github.com/Automattic/jetpack/blob/552aaa7ec64b39d9ad594318262ab98e4c25b26a/modules/widgets/eu-cookie-law/style.css#L1-L12

This is something that would be set on a theme-by-theme level, so it's not guaranteed to be in every theme. `.widget` is included in _s, which is probably why we're not seeing this on a lot of newer themes on WordPress.com: 

https://github.com/Automattic/_s/blob/master/functions.php#L111

... but in the affected themes listed above, Kahuna, Graphene don't use `.widget` at all, and Twenty Ten only uses it in the footer widget areas, but not the sidebar widget areas. I'd bet this is pretty representative of other themes out there.

I think the quickest fix would be to remove `.widget` from the EU Cookie Law Widget styles (assuming it's not there for some reason I can't think of!).

**Comment by rsjazz** [comment]
I was able to solve this finally. Here the steps I followed.

1. Checked my theme. Found out it was no longer supported.
2. Looked for a similar theme that is now supported.
3. Applied the theme
4. Re-selected the banner image

Done. 

Now the (renamed today) Cookies and Consent Banner I put in my Main Widget Sidebar works as expected.
