### ISSUE TITLE
Sync: PHP Warning: Creating default object from empty value

### ISSUE THREAD

**Issue by dd32** [Automattic/jetpack#8175]
On WordPress.org I noticed a PHP warning triggered by Jetpack Sync code.

`*E_WARNING: /wp-content/plugins/jetpack/sync/class.jetpack-sync-module-users.php:85 - Creating default object from empty value*`

Upon digging into it, it looks like it's being called from `Jetpack_Sync_Module_Users->expand_logout_username()`.
It seems both `expand_logout_username()` and `sanitize_user()` include checks to ensure that `$user` is an object, but https://github.com/Automattic/jetpack/commit/1cbd3cd579bb18c04747ef11a37a08f6085d4d48 added a line to `sanitize_user()` which fails to take into consideration that scenatio.

**Comment by jeherve** [comment]
@enejb Do you think you could take a look at this since you worked on #7937?

Thanks!

**Comment by enejb** [comment]
Looking into this now!
