### ISSUE TITLE
UI for Lazy Images

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#8193]
Lazy Images doesn't currently have a UI, and can only be enabled via the Jetpack Modules page.

There was a prototype UI baked into the old PWA branch: #7963

**Comment by rickybanister** [comment]
It sounds like there's an opportunity to improve the UI for Photon as we build the UI for this.

Currently we are very vague about how photon works:

![image](https://user-images.githubusercontent.com/437258/33294287-f124af12-d39d-11e7-8c6c-be4d656f34d0.png)

It might be nice to do something more like this:

![image](https://user-images.githubusercontent.com/437258/33294395-6479fa44-d39e-11e7-8ed7-8f96e598ede6.png)

What do you think @gravityrail 

cc @MichaelArestad and @michelleweber for a copy review of my proposal (it's always been really tough to talk about Photon and these techy things in a plain way).

**Comment by rickybanister** [comment]
Another note, we can also work on making the main labels shorter and adding more helpful explanatory text to the italic descriptions, I'm just fine with that.

**Comment by rickybanister** [comment]
Perhaps we could use a shared label for both settings like 

```Speed up images
[-0] Serve images from our global content delivery network
some broader explanation of what that means
[-o] Lazy load only images currently on the screen
some broader explanation of what that means```

**Comment by michelleweber** [comment]
Yeah, this is a toughie. The issue I have with the language in your mockup is that it's easy for someone who doesn't understand the specifics or what it means to serve an image (e.g., most people) to read it as "Jetpack has a network of available photos, and I can use those on my site."

I kind of want to not get into the details, and just focus on the broad strokes and the result, like: **Use Jetpack's servers to speed up image loading on your site (recommended)**

Alternatively, you could drop some of the detail into the smaller text, like:

**Speed up image loading on my site.**
_Jetpack will use its servers to boost image load speeds on your site. This feature must be enable to use Jetpack's Tiled Gallery options. Learn more. (LINK)_

**Comment by rickybanister** [comment]
@michelleweber I like your final suggestion above, my only concern is that 'speed up image loading on my site' is not exclusive to enabling the photon feature. Lazy loading has a similar effect—increasing the speed of the entire site loading by only displaying visible photos. Do you think you could take one more pass on this with an attempt to include both features and differentiate between them a bit?

**Comment by rickybanister** [comment]
We might consider (a bit down the road) a master setting for 'make my site faster', but I think in its nascent stages it's probably important to be able to turn this setting on and off (in the event there are collisions with themes or infinite scroll or other debugging issues). Perhaps @gravityrail can comment further to that effect, but we haven't necessarily made people the happiest when we make things on by default. We also don't get the benefit of explaining to folks how Jetpack makes their site faster if it does it invisibly.

**Comment by michelleweber** [comment]
@rickybanister, understood. So I'd say, let's just name the options right in the main text, and use the subtext to explain, e.g.:

Speed up image loading with Photon
With Photon, Jetpack will use its servers to boost image load speeds on your site. This feature must be enable to use Jetpack's Tiled Gallery options. Learn more. (LINK)

Speed up image loading with "lazy loading"
Normally, opening a web page causes it to load every image it contains, even those that a reader hasn't yet scrolled down to see. "Lazy loading" means that only the images _actually_ visible on the screen will load.

**Comment by rickybanister** [comment]
I think that is getting close @michelleweber—my only concern is that we've de-emphasized the 'photon' sub-branding. To fix that issue, what if we re-introduce a heading that covers both settings again:

**Speed up your site**
 
**Serve images from our servers**
Jetpack will optimize your images and serve them from the server location nearest to your visitors. Using our global 'content delivery network' will boost the loading speed of your site.  Learn more. (LINK)

**"Lazy load" images**
Normally, opening a web page causes it to load every image it contains, even those that a reader hasn't yet scrolled down to see. "Lazy loading" means that only the images actually visible on the screen will load.

Note: I've removed the reference to `This must be enable to use Jetpack's tiled gallery options.` because we should mention that loading images via CDN is required _from_ the tiled gallery setting instead. 

I know what you mean @MichaelArestad about not having a ui, but I can think of about a million reasons why someone might not want to lazy load images and adding a UI (even if lazy load is part of jumpstart) seems safer.

cc @oskosk

**Comment by michelleweber** [comment]
I think that works really well. And I think you can lose the quote marks around content delivery network.

**Comment by gravityrail** [comment]
@MichaelArestad - we need a setting for it because it could break your theme, and we want people to be able to turn it off. Or perhaps you have your own existing lazy images solution and you don't want to turn it on. Either way - we need a setting.

My thoughts on a UI:
- We need to accommodate the possibility that we will add a Javascript / CSS CDN in the future (or possibly at the same time as shipping this UI, who knows?)
- We perhaps could include some data about how much faster it will make their home page or blog pages load (using remote detection) - though not necessary, this could be cool.

For right now, I really like @rickybanister's suggestion, I just wanted to add those as possibilities so we can navigate towards a concept that accommodates this stuff without too many changes.

**Comment by beaulebens** [comment]
When we ship this UI, we probably want to have some conflict avoidance code included as well, to make sure we don't directly conflict with any other popular lazy-load plugins (assuming there is at least one?)

**Comment by ebinnion** [comment]
To make sure I understand correctly,

We want to create a new section in the "Writing" tab that is named "Speed up your site", and within that section, we want to put the photon and lazy images toggles with the copy that @rickybanister suggested. Is that correct?

@beaulebens - We have a few plugins added to the `$conflicting_plugins` array in `class.jetpack.php`. I'll be sure to test these in the next few days though.

**Comment by rickybanister** [comment]
Yes, that's it for now @ebinnion.

As we ramp up our performance work we'll want to do a bigger rethink, but for now it's just rewording the photon setting card and expanding it.
