### ISSUE TITLE
Subscriptions: Apostrophe converts to unicode in emails when post is created in Gutenberg

### ISSUE THREAD

**Issue by seejacobscott** [Automattic/jetpack#8194]
After publishing a post using Gutenberg the subscription email that is sent will convert apostrophes to `&#x27;`

Steps to reproduce the issue:

1. Make sure Jetpack is connected and subscriptions are active
2. Create a post with Gutenberg that includes apostrophes/single-quotes
3. When published, check the email. 

What I expected:
Apostrophe/single quote characters to display

What happened instead
`&#x27;` displays in the character's place. 

Reported by a user in 778397-zen

Screenshot (from user):

<img width="795" alt="aposgutenberg2" src="https://user-images.githubusercontent.com/16127063/32909572-85135dfc-cacc-11e7-94ae-4167b0696eab.png">

The ticket also contains raw email contents, which also include the `&#x27;` character. 

Seems related to https://github.com/WordPress/gutenberg/issues/3353#issuecomment-342223315

**Comment by gravityrail** [comment]
Fixed in 165646-wpcom.

This was occurring because our regex to "autofix" unescaped &'s in URLs was not properly detecting unicode chars of the form `&#xNN(NN);`

**Comment by austinginder** [comment]
Thanks so much! Much appreciated.
