### ISSUE TITLE
Related Posts: Canonical header for images

### ISSUE THREAD

**Issue by ajonit** [Automattic/jetpack#821]
It looks like the images are indexed and served from WP CDN for "Related Posts" functionality in JetPack.

However I noticed that the images doesn't return rel="canonical" header pointing to the original image. This may create a duplicate content(image) issue with search engines. [Here is a link](http://reviewofweb.com/wordpress/what-is-a-cdn-and-how-to-set-up-under-10-minutes/), in case you wish to have a quick look using a Developer tool.

Please let me know if you need some more information.

**Comment by kraftbj** [comment]
This was added in https://code.trac.wordpress.org/changeset/357/photon back in Sept 2014.
