### ISSUE TITLE
Search: Multiple Search Forms with diff filtering

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#8214]
Often a site has multiple section: WooCommerce store, bbPress forums, main home page. We should make it easy to configure separate search sections on a site, and define default filtering for each.

Different filtering methods:
- Taxonomies
- CPTs

At a minimum, we should have filters for the filter definitions and maybe a search form function these so they can be built in code. At some point having some UI would be nice also.

See discussion: https://twitter.com/douglsmith/status/932635801996943361

**Comment by gibrown** [comment]
An additional plugin: wpjobmanager. There are almost certainly a bunch of plugins we should magically detect and just work with.

**Comment by douglsmith** [comment]
bbPress is extra tricky because it has one custom post type for topics and another for replies. But the content of the replies is only displayed under the given topic. So a search hit on reply content should be attributed to the parent topic.

**Comment by gibrown** [comment]
Once #8471 lands, this may be working, but needs a lot of testing.

**Comment by gravityrail** [comment]
We think this is fixed.

cc @ebinnion
