### ISSUE TITLE
Using the REST API instead of xmlrpc.php to avoid hosting blocks

### ISSUE THREAD

**Issue by webdados** [Automattic/jetpack#8230]
Nowadays a lot of hosting providers are simply blocking xmlrpc.php due to regular attacks.

Are there plans for Jetpack to move away from xmlrpc.php and use, for example, the REST API?

**Comment by jeherve** [comment]
We've started working on this; right now if XML-RPC is blocked we fall back to the REST API for the connection process. You can learn more about it here: #7740

Once the site is connected, most requests still rely on XML-RPC though. We will continue to add more fallbacks in other areas of Jetpack in the future. Keep an eye on our blog!

**Comment by webdados** [comment]
Thanks for the clarification.
