### ISSUE TITLE
Admin Page: Click Enter on jetpack dashboard page and it redirect to login page.

### ISSUE THREAD

**Issue by Umangvaghela** [Automattic/jetpack#8234]
#### Steps to reproduce the issue

- Active jetpack plugin for local development.
- Click on dashboard menu.
- Press Enter Key OR open dashboard link in new tab.

#### What I expected

Do not redirect to login page.

#### What happened instead

The user automatically logout and redirect to login page.
In setting page, everything is working fine.

**Comment by jeherve** [comment]
> Active jetpack plugin for local development.

Do you use Jetpack's Development mode on that local site?
https://jetpack.com/support/development-mode/

> Click on dashboard menu.

Is that the Jetpack Dashboard, under Jetpack > Dashboard?

**Comment by Umangvaghela** [comment]
@jeherve 
Do you use Jetpack's Development mode on that local site?
Yes, I use it.
Is that the Jetpack Dashboard, under Jetpack > Dashboard?
Yes.
Jetpack->Dashboard.
http://localhost/your-projectname/wp-admin/admin.php?page=jetpack#/dashboard
when you click enter key that time this happen.

**Comment by jeherve** [comment]
I can't seem to be able to reproduce on my end. Nothing happens when I hit the Enter key while in the Jetpack Dashboard, or when opening the dashboard in a new tab.

This would seem to point towards issues with cookies on your end. Does this happen on other pages of your dashboard?
