### ISSUE TITLE
Jetpack Images: consider including images even when we don't know their size

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#8237]
- Facebook requires large images (more than 200x200px) to create its post previews.
- Related Posts require images that are at least 350x200px.

We take that into account in Jetpack when we parse posts to look for representative images, thanks to the `width` and `height` parameters one can use when calling `Jetpack_PostImages::get_image` or `Jetpack_PostImages::get_images`. 

Behind the scenes, `Jetpack_PostImages` looks for representative images everywhere:
- In slideshows
- In galleries
- In featured images
- In images attached to the post
- In images inserted into the post, regardless of where they are actually hosted.

When the image is stored in WordPress, we can easily look at the image meta data to figure out its size and decide whether it's a representative image or not. 
For images hosted somewhere else, however, it is not that easy.

That's why until #6636, we did not look for any size parameters for images hosted somewhere else; we just returned them and included them in Open Graph meta tags and elsewhere, regardless of their size.

In #6636, we became more strict; we would only return those images if we knew their size. To know that, we would look at the post HTML and look for `width` and `height` attributes in the image tags.

That works well when one uses WordPress to insert that image, like so:
![screenshot-2017-11-23-at-21-07-32](https://user-images.githubusercontent.com/426388/33188003-7397a02c-d096-11e7-9a86-5b5318bc6f9b.png)
![screenshot-2017-11-23-at-21-08-04](https://user-images.githubusercontent.com/426388/33188004-76c6c002-d096-11e7-8ca5-3c56b737f58d.png)

But if one uses a separate app to post, that doesn't add any `width` and `height` attributes, the image is not selected, even if it may be big enough to use.

Should we consider reverting #6636 to avoid such issues, even if that means smaller images will make it through?

Let's look at what impact this has on support in the next few weeks to figure that out.

**Comment by jeherve** [comment]
790622-zen

**Comment by lbthomsen** [comment]
A simple pseudo-logic would be:

1. If you can detect the size then do so and apply strict logic
2. If you can NOT detect the size, assume the user knows what they are doing and post anyway.

**Comment by jeherve** [comment]
819065-zen

**Comment by lbthomsen** [comment]
I do wonder why this one was listed as an "enhancement".  It is a result of an enhancement that broke a number of production systems and these production systems are left in a limbo unable to update jetpack or broken if they updated.

**Comment by jeherve** [comment]
We'll need to collect more feedback before we can act on this; we should then be able to decide if the change we implemented in #6636 should stay, or if it qualifies more as a bug and should be reverted. We'll keep updating this issue in the next few weeks as we get more feedback from other users.

In the meantime, if this was very much an issue on your own site, I would suggest checking if you can actually bring `width` and `height` parameters with the images you add to your site; that would solve the issue on all new posts.

**Comment by lbthomsen** [comment]
Well, I'd say in this day and age I'd prefer to let the stylesheet/theme deal with sizing of images rather than hard coding them in the contents.  I might want to switch to another theme later, so I'd think it would be more productive to stick with the jetpack version before this bug was introduced :)

**Comment by KokkieH** [comment]
This came up in https://wordpress.org/support/topic/top-pages-widget-featured-image-not-showing/ and https://wordpress.org/support/topic/top-posts-and-pages-not-showing-images/

**Comment by jeherve** [comment]
One can now use the `jetpack_postimages_ignore_minimum_dimensions  ` filter to ignore the size check added by Jetpack. For more information about the filter, see #9834.

Closing.
