### ISSUE TITLE
Markdown : if a paragraph begins with a link, p tags are not added

### ISSUE THREAD

**Issue by nicolinuxfr** [Automattic/jetpack#8247]
#### Steps to reproduce the issue

If you begin a paragraph directly with a link, the Jetpack Markdown won't add p tags around the paragraph on the site, breaking the theme.

#### What I expected

This paragraph : 

```
[This is a link](http://ndd.com) to a webpage. 
```

Should be render within p tags, like so :  

```
<p><a href="http://ndd.com">This is a link</a> to a webpage. </p>
```

#### What happened instead

This is what Jetpack 5.5.1 (using latest WordPress) currently outputs : 

```
<a href="http://ndd.com">This is a link</a> to a webpage. 

```

**Comment by zinigor** [comment]
As far as I can see, the bug is not present in the Gutenberg editor, unless this is a very high priority issue for you, can we close this?
