### ISSUE TITLE
Workaround needed for "wpautop" on author bio

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#8255]
This change in Core:

https://core.trac.wordpress.org/ticket/40040

... makes `wpautop()` process the output of `the_author_meta( 'description' )` here:

https://github.com/Automattic/jetpack/blob/5.5.1/modules/theme-tools/content-options/author-bio.php#L53

... which results in broken HTML, since we already have the `the_author_meta()` wrapped in `p` tags. This is broken in lots of themes and Jetpack, and it's being reverted here:

https://core.trac.wordpress.org/ticket/42578

In the meantime, we should add a workaround for affected versions of Core.

cc @jeherve

**Comment by Mika56** [comment]
Temporary fix: 
```php
if(has_filter('get_the_author_description', 'wpautop')) {
	remove_filter('get_the_author_description', 'wpautop');
}
```

**Comment by chaselivingston** [comment]
Also reported in 846547-zen.

**Comment by oskosk** [comment]
The behaviour mentioned here seems to not be present since WordPress 4.9.2 (January 16th, 2018). I'm closing this issue now.
