### ISSUE TITLE
Plans: User is prompted to connect Google Analytics even though already connected

### ISSUE THREAD

**Issue by allendav** [Automattic/jetpack#8256]
#### Steps to reproduce the issue

One way:
* Enter your Google Analytics Tracking ID in the Google Analytics section of https://wordpress.com/settings/traffic/{DOMAIN} and Save Settings
* Navigate to https://wordpress.com/plans/my-plan/{DOMAIN}
* Note that you are prompted to connect to Google Analytics
* However, note that your tracking ID is present in the Source of the front side (e.g. home) of the site

<img width="1429" alt="screen shot 2017-11-28 at 8 33 31 am" src="https://user-images.githubusercontent.com/1595739/33332070-22c832da-d418-11e7-92f5-67c88749eb4f.png">

<img width="1428" alt="screen shot 2017-11-28 at 8 33 11 am" src="https://user-images.githubusercontent.com/1595739/33332071-22f673c0-d418-11e7-969f-4a7344f2ec72.png">

**Comment by jeherve** [comment]
Nice catch!

Could you open this issue in the `wp-calypso` repo, since that is where the problem will need to be fixed?

Thanks!
