### ISSUE TITLE
Remove VaultPress references in At a Glance (Jetpack Dashboard)

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#8262]
Let's tackle a few of these string changes (maybe not all in one PR):

## Backups

I imagine quite a bit of the Backups DashItem needs to be reworked to use Activity Log data. Bonus points if you remove all mentions of VaultPress in this component.

<img width="377" alt="image" src="https://user-images.githubusercontent.com/1123119/33349446-4f0476bc-d457-11e7-8d65-199efe05962b.png">

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/1123119/33349381-0af7fc3c-d457-11e7-8725-52d88be4038f.png">

https://github.com/Automattic/jetpack/blob/master/_inc/client/at-a-glance/backups.jsx#L51

Let's direct the link to the Activity Log and make sure the text "Last backed up..." is coming from the Activity Log and is accurate.

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/1123119/33349275-a2222f34-d456-11e7-97a9-856bf7f102e1.png">

https://github.com/Automattic/jetpack/blob/master/_inc/client/at-a-glance/backups.jsx#L63

Let's change it to:

> To automatically back up your entire site, please <a href="link-to-setting">add your server credentials</a>.

## Scan

VaultPress is linked to a few times here when issues are detected and also when it needs to be installed/activated. Please double check to make sure we're not getting any strings from VaultPress in this one either.

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/1123119/33349513-a51df06e-d457-11e7-883a-67df79da6cd3.png">

https://github.com/Automattic/jetpack/blob/master/_inc/client/at-a-glance/scan.jsx#L70

Let's change remove the "View details..." bit and instead send the user right to support in WordPress.com. HappyChat if possible.

<img width="994" alt="image" src="https://user-images.githubusercontent.com/1123119/33349687-7845482a-d458-11e7-955e-15bfffc4bb02.png">

https://github.com/Automattic/jetpack/blob/master/_inc/client/at-a-glance/scan.jsx#L102

Let's change it to:

> For automated, comprehensive scanning of security threats, please <a href="link-to-setting">add your server credentials</a>.

### Threat count

I'm not entirely sure where it's coming from in JP, but we need to make sure the data comes from the Activity Log.

## Misc

VaultPress is referenced in these related files:

- [ ] `_inc/client/state/at-a-glance/actions.js`
- [ ] `_inc/client/state/at-a-glance/reducer.js`

**Comment by eliorivero** [comment]
Fixed in https://github.com/Automattic/jetpack/pull/8387 and https://github.com/Automattic/jetpack/pull/8389
