### ISSUE TITLE
Remove VaultPress references from Security settings

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#8264]
We need to modify the Backups and Security settings group to play nicely with the Activity Log. Here's it's current state:

<img width="740" alt="image" src="https://user-images.githubusercontent.com/1123119/33350498-54b7bb78-d45c-11e7-845a-f0c8d9ce2531.png">

And it changes to reflect security threats/etc. 

Here's what I propose in three states:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/1123119/33351163-a7ecf9fe-d45f-11e7-8457-66ca526bc361.png">

<img width="747" alt="image" src="https://user-images.githubusercontent.com/1123119/33351264-20f5ed88-d460-11e7-97c9-3a10e3af001d.png">

<img width="747" alt="image" src="https://user-images.githubusercontent.com/1123119/33351138-8a256ba4-d45f-11e7-9fb0-a47c57e8d42c.png">

It will no longer have any status other than Needs Upgrade, disconnected, or connected.

**Comment by eliorivero** [comment]
Fixed in https://github.com/Automattic/jetpack/pull/8382
