### ISSUE TITLE
Masterbar: Site link from wp-admin is undefined

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#8272]
#### Steps to reproduce the issue
1. Enable the WP.com toolbar (masterbar)
2. Go to any page in wp-admin
3. Click "My Sites" in the top-left
4. Click the SiteIcon or label of the site at the top of the menu to visit the site (correct URL is shown in the browser status bar)
5. Instead, land on `/wp-admin/undefined`

Note that clicking the same icon/link from the frontend of the site works correctly, and returns you to the homepage of the site.

![screen shot 2017-11-29 at 9 39 44 am](https://user-images.githubusercontent.com/108942/33386938-5be6a912-d4e9-11e7-8ed7-ee9a3eb10717.png)

cc @vindl

**Comment by jeherve** [comment]
For reference, this site runs 5.6-alpha.

**Comment by vindl** [comment]
@rodrigoi any chance your latest analytics changes to Masterbar could have caused this?

**Comment by rodrigoi** [comment]
@vindl yep. Working on a fix right now.
