### ISSUE TITLE
Module list: missing border due to max width for page layout

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#8278]
> Missing right border on jetpack_modules page on Chrome / MacOS & Firefox / Ubuntu & Safari / MacOS

![screenshot 2017-11-30 at 9 31 40](https://user-images.githubusercontent.com/426388/33421111-575b69e6-d5b1-11e7-9d0d-0a2593a3bd1c.png)

**Comment by MichaelArestad** [comment]
Is this still an issue? I couldn't reproduce on FF or Chrome for Mac?
