### ISSUE TITLE
Search: Add UI to the search box that let's the user change how results are sorted

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#8289]
The end user should be able to click to sort by date or by relevance. Relevance should be the default.

I guess this should be in the search widget, but I'd really like us to have a search box that sits at the top of the results where we can add search refinement settings such as:
- selecting the sorting
- showing if we autocorrected the search ala #7924 
- any filters that have been added via faceting

Bonus points if we remember the last time the end user selected date or relevance and just use whatever they used last.

**Comment by gravityrail** [comment]
Fixed by #8542
