### ISSUE TITLE
Holiday Snow: Improve accessibility

### ISSUE THREAD

**Issue by pento** [Automattic/jetpack#8309]
There are many arguments about the holiday snow script, see #1349. Instead of getting into the remove/global disable/performance/etc arguments, here are some things we can do now.

A useful step for screen readers would be to add `aria-hidden="true"` and `role="presentation"` attributes to the [SnowFlake](https://github.com/Automattic/jetpack/blob/master/modules/holiday-snow/snowstorm.js#L243), so that the elements aren't added to the screen reader DOM.

Another useful step is to disable it entirely with the `prefers-reduced-motion` [media query](https://css-tricks.com/introduction-reduced-motion-media-query/). Thanks to the magic of `matchMedia()`, the snow script can bail early if this is true: `window.matchMedia( '(prefers-reduced-motion: reduce)' ).matches`.

This media query currently only works in Safari 10.1 (MacOS and iOS), though it is in the [CSS draft process](https://drafts.csswg.org/mediaqueries-5/#prefers-reduced-motion), so will likely be available in all browsers in the future.

**Comment by gravityrail** [comment]
Closed because feature is removed in Jetpack 6.0.

**Comment by gravityrail** [comment]
Closed because feature is removed in Jetpack 6.0.

**Comment by oskosk** [comment]
Note that the `aria-hidden` and `role` attributes where actually implemented by #8421 and released with Jetpack 5.9

**Comment by jeherve** [comment]
Reopening as snow is back: #9110

**Comment by zinigor** [comment]
#9110 is not going to be merged, closing.
