### ISSUE TITLE
Holiday Snow: Couldn't Find Snow Setting

### ISSUE THREAD

**Issue by BFTrick** [Automattic/jetpack#8310]
#### Steps to reproduce the issue

I'm currently recording a screencast and I show my site in that screencast. I don't want to show the snow so the screencast makes sense all year round.

I go to disable the snow feature (temporarily - otherwise it's great) and look through the Jetpack menus unable to find it. I Googled the setting & couldn't find it. Eventually I found a [WP.org forum post that mentions where the setting is](https://wordpress.org/support/topic/why-is-jetpack-making-snow-on-my-website/).

It's under Settings -> General.

#### What I expected

I assumed it would be under Jetpack -> Settings where all of the other settings are.

#### What I suggest

Since you already have Jetpack settings I recommend moving the snow feature under those settings.

**Comment by jeherve** [comment]
This was removed as part of the Settings UI change in #6299.

I don't know if it was removed on purpose, or just forgot during the switch. @MichaelArestad Do you happen to know?

**Comment by MichaelArestad** [comment]
@jeherve I do! We removed it in favor of implementing this: https://github.com/Automattic/jetpack/issues/6260

Doesn't look like it happened. @samhotchkiss got a dev who's up for a quick (hopefully) side project today?

**Comment by MichaelArestad** [comment]
It looks like it's available on WordPress.com for now in General settings.

**Comment by jeherve** [comment]
> It looks like it's available on WordPress.com for now in General settings.

It's also available under Settings > General in wp-admin. I think what @BFTrick expected to find was a toggle to activate the feature under Jetpack > Settings, where most of the other Jetpack settings live.

**Comment by BFTrick** [comment]
^ Correct. I assumed it would be with the other Jetpack settings.

**Comment by jeherve** [comment]
Reopening as snow is back: #9110

**Comment by jeherve** [comment]
#9110 is not going to be merged, closing.
