### ISSUE TITLE
WooCommerce Analytics: Activate module by default for Woo users

### ISSUE THREAD

**Issue by psealock** [Automattic/jetpack#8315]
Activate WooCommerce Analytics module if WooCommerce is active.
* On initial setup
* If Woo is added at a later date
* Deactivate if Woo is deactivated

It would be great if we could treat this as a feature flag and have it hidden, allowing us to incrementally pull request to master.

**Comment by jeherve** [comment]
Closing this one as this is how WooCommerce Analytics now works.
