### ISSUE TITLE
Related Posts: Changing the context text

### ISSUE THREAD

**Issue by shelleyphant** [Automattic/jetpack#8319]
Hi,

I can't seem to edit the text that shows up with my "context" markers (ie, categories and tags). I'd ideally like to remove the In "" from the string, so it only displays the name of the category.

Thanks

**Comment by jeherve** [comment]
You can use 2 filters to customize that context:
- `jetpack_relatedposts_post_category_context` https://developer.jetpack.com/hooks/jetpack_relatedposts_post_category_context/
- `jetpack_relatedposts_post_tag_context` https://developer.jetpack.com/hooks/jetpack_relatedposts_post_tag_context/

You can use those filters to only return the category or the tag. I have not tested the following, but it should work:

```php
/**
 * Only display the term name in Jetpack's Related Posts context.
 *
 * @see https://github.com/Automattic/jetpack/issues/8319
 *
 * @param string $post_term_context "In x" line displayed in the post context below each Related Post.
 * @param array  $term              Array containing information about the term (category or tag).
 */
function jeherve_relatedposts_context_just_term( $post_term_context, $term ) {
    return esc_html( $term->name );
}
add_filter( 'jetpack_relatedposts_post_category_context', 'jeherve_relatedposts_context_just_term', 10, 2 );
add_filter( 'jetpack_relatedposts_post_tag_context', 'jeherve_relatedposts_context_just_term', 10, 2 );
