### ISSUE TITLE
Lazy load not working on archive pages

### ISSUE THREAD

**Issue by galbaras** [Automattic/jetpack#8320]
#### Steps to reproduce the issue

Visit archive pages on https://dev.get-business-online.com/ronitbaras/ and look at the code.

#### What I expected

Lazy loading attributes on IMG tags.

#### What happened instead

No lazy loading attributes and no lazy loading behavior. WooCommerce archives are OK and so are posts and pages, but archives just load their images normally.

#### Environment

Genesis Framework with custom child theme - no relevant image or thumbnail filters. No caching and no other plugins involved in serving images that I can think of.

On another site, which isn't based on Genesis, lazy loading works OK on archive pages.

**Comment by jeherve** [comment]
This does not seem to be a regular archive page; it is a static page that uses a custom page template, `blog.php`.

I assume that custom page template is then set to create a loop that displays the most recent posts. Could you check that page template file and see how the featured images are displayed there? What is the function used to return the featured images?

**Comment by galbaras** [comment]
Jeremy, it's the same on category and tag pages, which use the normal loop.

Also, the page_blog.php template is the default one from Genesis, which only contains a call to genesis().

**Comment by jeherve** [comment]
Could you let me know how the regular loop calls the featured images?

**Comment by galbaras** [comment]
Looks like it uses this code in genesis_do_post_image():

`		$img = genesis_get_image( array(
			'format'  => 'html',
			'size'    => genesis_get_option( 'image_size' ),
			'context' => 'archive',
			'attr'    => genesis_parse_attr( 'entry-image', array ( 'alt' => get_the_title() ) ),
		) );
`

Which, in turn, calls get_post_thumbnail_id() or genesis_get_image_id() to determine the thumbnail ID and then wp_get_attachment_image() and wp_get_attachment_image_src() to construct the HTML.

The whole thing is run via this action:

`add_action( 'genesis_entry_content', 'genesis_do_post_image', 8 );`

Which runs just before genesis_entry_content().

This could mean that the Jetpack filter on 'the_content' has no effect, because the image is rendered outside of the content, and the filter on 'post_thumbnail_html' has no effect, because Genesis doesn't call get_the_post_thumbnail().

Consider adding a filter on 'wp_get_attachment_image_attributes' for this to work.

**Comment by jeherve** [comment]
Thanks for all the details!

@gravityrail Could you take a look at this? Thanks!

**Comment by ebinnion** [comment]
I'm looking into it

**Comment by ebinnion** [comment]
Thanks for the report @galbaras. I've created #8336 to address this.

I did not test on a Genesis them, but I did write unit tests to ensure that we handle the images properly with the filter you recommended.
