### ISSUE TITLE
Remove link to VaultPress on the Settings -> Security page for Rewind sites

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#8323]
Ticket: 832501-zen

Site is a Rewind site, but the user tried to set up VaultPress because they followed a link from here (Configure your security scans):

![pastedimage](https://user-images.githubusercontent.com/3676359/33683919-7cbd02f6-da9a-11e7-879a-1e585b30738a.png)

**Comment by jeherve** [comment]
Closing as duplicate of #8264
