### ISSUE TITLE
Sharing: increase twitter title character limit to 280

### ISSUE THREAD

**Issue by rinatkhaziev** [Automattic/jetpack#8325]
Twitter has recently bumped up character limit to 280, however the change has not been reflected in Twitter sharing source: 
https://github.com/Automattic/jetpack/blob/master/modules/sharedaddy/sharing-sources.php#L716

PR incoming.

**Comment by lancewillett** [comment]
Looks like https://github.com/Automattic/jetpack/pull/8326 does the trick.
