### ISSUE TITLE
Comments: make comment submission ajax'ed

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#833]
As requested here:

http://wordpress.org/support/topic/i-was-expected-some-other-fu?replies=2

> The post made by the comments button should be ajax in order to avoid a page load in each comment.

**Comment by tareq1988** [comment]
It's possible with one trick:
1. Submit the form via ajax
2. Ajax handler handles the comment and inserts it
3. On success, grab the current page and replace the entire comment DOM. So in-theory, you are loading the next page via ajax, and replacing the comment section with updated content.

```JS
jQuery.get( window.location.href + " #comments", function(data) {
    jQuery("#comments").replaceWith( jQuery(data).find( '#comments' ) );
});
```

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/feature-request-351?replies=1&view=all

**Comment by rahil471** [comment]
Love Jetpack comment system, Ajax'ed commenting would be a really good addition. Looking forward.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by georgestephanis** [comment]
Just some comment on this -- it's not as simple as just adding ajax handlers, because the way Jetpack comments works is it displays the actual comment form cross-domain in an iframe on the page -- so direct communication is tricky at best.
