### ISSUE TITLE
Gallery Widget: Link Type not working since update

### ISSUE THREAD

**Issue by mermel** [Automattic/jetpack#8332]
#### Steps to reproduce
1. Add gallery widget (new core widget)
2. Select link type (you'll see carousel is not an option)
3. Select any link type
4. Save
5. View site normally (not customizer)
6. click on an image in gallery widget
7. carousel pops up

#### What I expected
The link type specified to be used.

I also think another filter needs to be added to the carousel as a valid link type.

#### What happened instead
Carousel overrides all settings.  Oddly though when you view in the customizer the settings are maintained somewhat, if you click on an image in the gallery the carousel will pop up briefly then redirect to the correct link type.

**Comment by jeherve** [comment]
Closing this for now since there is now a core Gallery widget instead.
