### ISSUE TITLE
PWA Support

### ISSUE THREAD

**Issue by grupie001** [Automattic/jetpack#8335]
hi there,

having troubles to activate the PWA module. Have I missed something, I can see the module is there (only two files and one "image" folder), but I can't figure out how I can activate it.
Using Lighthouse, it says that there is no pwa, no manifest and no serviceWorker there.
Any advice?
Thanks and please, I am just a user who will keep up with all the new technologies out there.
Cheers Gerhard

**Comment by jeherve** [comment]
This module is still under active development. You can follow our progress on this in #7963. The module appearing in the old module list right now only adds a manifest, as per #8078. As we add more features, we will add an interface in the Jetpack plugin settings, and will mention our work on [the Jetpack blog](https://jetpack.com/blog/).

I hope this clarifies things a bit!

**Comment by grupie001** [comment]
Thanks a lot for the description. I will follow it.
