### ISSUE TITLE
After the Deadline: better wording needed for the AtD prompt

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#835]
> There have been at least a couple of instances where I have pressed OK thinking that the After The Deadline spell checker would Update my post with the necessary corrections or, allow me to actually update the errors in the post but instead, end up publishing the post. I think the most important wording that needs to be changed is the part that says “Press OK To Update Your Post“. 

![](http://i2.wp.com/www.wptavern.com/wp-content/uploads/2013/08/ATDPrompt.jpg)

Instead of "OK" and "Cancel", it might be best to offer 2 options to the writer:
1. Automatically update and publish
2. Review the suggestions and do the changes yourself

Suggested here:
- http://www.wptavern.com/better-wording-needed-for-after-the-deadline-prompt

**Comment by dereksmart** [comment]
Closing as wontfix for now, as this seems to be the only report of the message being confusing. Please reopen if we get more reports.
