### ISSUE TITLE
Contact form: Option to reorder items in dropdown, checkbox, etc

### ISSUE THREAD

**Issue by codestor4** [Automattic/jetpack#8353]
At the moment we have the following setup in Jetpack:

<img width="622" alt="screen shot 2017-12-13 at 6 57 08 pm" src="https://user-images.githubusercontent.com/20779676/33941121-7561ac76-e037-11e7-8105-e9c7809543e7.png">

It'd be great to have an option to drag and rearrange items in there. 

reported in 844382-zen

**Comment by perbjo** [comment]
I totally agree!

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
