### ISSUE TITLE
Protect: Link in mail sent by the recovery service always uses https as the final schema for the site

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#8368]
The link present in the mail received to recover login to one's site using the Recovery Feature of Protect redirects eventually to a version of my site's URL enforcing `https` as the schema for the `wp-login.php` URL even when the site is not using SSL.

#### Steps to reproduce the issue

* Get a connected Jetpack site without SSL available. (That is, running over `http://`).
* Define the constant for forcing the recovery service.
* Attempt to login into the site.
* Enter the user's email address on the recovery screen.
* Check your mailbox.
* Click the blue button.
* Wait for the redirects to land on your site's domain with the wrong schema in the URL.

#### What I expected

* To be dropped in my site using the same schema it is actually using

#### What happened instead

* Got redirected to an non-existent `https://` version of the `wp-login.php` URL.

![image](https://user-images.githubusercontent.com/746152/34047774-1df7c290-e190-11e7-9848-3c66eb2d005b.png)

**Comment by oskosk** [comment]
@enejb do you think this could be addressed before 5.7 is released ?

**Comment by oskosk** [comment]
Looks like the fix should com from the .com side of things. Removing this from the `5.7` milestone.

**Comment by oskosk** [comment]
@ebinnion put a fix for this in D10129-code

**Comment by ebinnion** [comment]
I've figured out how to test the patch finally and have added testing instructions. I intend on rolling it out this coming Monday.

**Comment by ebinnion** [comment]
Deployed in r170283-wpcom.

**Comment by oskosk** [comment]
Thank you @ebinnion ! ❤️
