### ISSUE TITLE
Image CDN referred to as Photon

### ISSUE THREAD

**Issue by cena** [Automattic/jetpack#8370]
User reports in /wp-admin/admin.php?page=jetpack_modules, Image CDN is still referenced as 'Photon'.

Confirmed in 5.6.1.

**Comment by jeherve** [comment]
Is this a problem? Would you like to change that name to something else?

**Comment by jeherve** [comment]
Thanks for the clarification!

We'll discuss this internally and update this issue accordingly. 

Internal reference: p93VbO-1L-p2

**Comment by zinigor** [comment]
From what I'm seeing in `master` currently, this is no longer the case. Language is updated to only refer to the service as CDN. Feel free to reopen if I missed something.
