### ISSUE TITLE
Search: filtering by post type is not working

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#8371]
http://gibrown.wpsandbox.me/main/?s=images&post_type=page

vs

http://gibrown.wpsandbox.me/main/?s=images

Both return the same results.

Should probably do more testing of all public query vars: https://codex.wordpress.org/WordPress_Query_Vars

props @ebinnion

**Comment by ebinnion** [comment]
@gravityrail offered to take this on in our call yesterday so I've assigned him to the issue
