### ISSUE TITLE
Contact Form: Emails are sent as plain text

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#838]
In [this thread](http://wordpress.org/support/topic/jetpack-contact-from-email-is-not-set-for-right-to-left-languages?replies=1), he user explained that the emails sent by the Contact Form are sent in Plain Text, and thus are misaligned in the email client. The user suggests sending them as HTML to fix the alignment for RTL language.

Original trac ticket:
- https://plugins.trac.wordpress.org/ticket/1903

**Comment by dereksmart** [comment]
This was done in #2651
