### ISSUE TITLE
Sharing: add shortcode to display sharing buttons anywhere in the post content

### ISSUE THREAD

**Issue by StefMattana** [Automattic/jetpack#8383]
A user asked if it'd be possible to add the functionality of the [Sharing buttons shortcode for Jetpack plugin](https://wordpress.org/plugins/jetpack-sharing-butttons-shortcode/) in the Jetpack plugin itself. The reason why they're asking is mainly because the plugin isn't being updated recently, so I reckon they think that by adding it into the JP plugin it'll stay up to date.

I see that the plugin [got another feat request lately](https://wordpress.org/support/topic/idea-13/), meaning people actively use it, so that addition would be nice in my opinion :)

**Comment by brbrr** [comment]
Since Gutenberg is approaching quite fast (where shortcodes won't work), and due to lack of activity on this, I going to close it. Feel free to reopen it if needed.
