### ISSUE TITLE
Social media icons: add email button

### ISSUE THREAD

**Issue by ghost** [Automattic/jetpack#8384]
It would be nice to have a clickable icon (an envelope or something) in the list of social media icons which has a mailto link to a custom email address.

**Comment by arunsathiya** [comment]
Doesn't Jetpack already have "Email" as a sharing button option? It's not in the format you specify though: mailto link. So, it's mostly redo of the current email button, right?

**Comment by jeherve** [comment]
@arunsathiya This issue refers to the Social Media Icons Widget, as opposed to the sharing buttons:
https://jetpack.com/support/extra-sidebar-widgets/social-media-icons/

**Comment by kathrynwp** [comment]
cc @thomasguillot

**Comment by torres126** [comment]
Was this resolved or am I missing something?

![sgfdsgfdgsfdgf](https://user-images.githubusercontent.com/43215253/52508435-9d216b00-2bec-11e9-8d36-6c20792bec1b.png)

**Comment by jeherve** [comment]
@torres126 Yes you're right; it was added when we switched to the new version of the Social Icons widget. Closing!
