### ISSUE TITLE
Infinite Scroll: infinite_scroll_settings filter does not override a number of posts per page

### ISSUE THREAD

**Issue by dashkevych** [Automattic/jetpack#8385]
#### Steps to reproduce the issue

I am trying to override a number of posts per page in Jetpack infinite scroll using `infinite_scroll_settings` filter. Here is a code that I am using:

```
function themeslug_jetpack_products_per_page( $settings ) {
    global $wp_query;

     if ( is_array( $settings ) && $wp_query->is_post_type_archive( 'product' ) ) {
            $settings['posts_per_page'] = 12;
     }
   
     return $settings;
}
add_filter( 'infinite_scroll_settings', 'themeslug_jetpack_products_per_page' );
```

#### What I expected

I've expected that it will load 12 posts every time I scroll.

Here is what I mean:
Start: 12;
Scroll: 12;
Scroll: 12;
Scroll: 12;
ect...

#### What happened instead

The code works fine but only when the page is loaded, meaning it displays 12 posts in the begining but when I start scrolling the next set of posts displays 7 posts per page (a default Jetpack's value) instead of 12.

Here is what I mean:
Start: 12;
Scroll: 7;
Scroll: 7;
Scroll: 7;
ect...

I've found that the filter ignores some conditions in the if statement in the function: `&& $wp_query->is_post_type_archive( 'product' )`

Any ideas how to solve it?

**Comment by zinigor** [comment]
We have introduced some changes to Infinite Scroll in Jetpack 6.0, and now you should be able to both use your method, as well as filter the number of posts per page using the new `infinite_scroll_posts_per_page` filter. Please let us know if you're still unable to change the setting. I'm closing this issue for now.
