### ISSUE TITLE
Undefined version string in loading screen.

### ISSUE THREAD

**Issue by zinigor** [Automattic/jetpack#8393]
Thanks to a report by @eliorivero we now know that the loading screen version string is malformed:
<img width="338" alt="captura de pantalla 2017-12-19 a la s 18 46 32" src="https://user-images.githubusercontent.com/374293/34202164-006dcb38-e588-11e7-82b5-3e0c6f2e2f19.png">

**Comment by eliorivero** [comment]
Fixed in https://github.com/Automattic/jetpack/pull/8395
