### ISSUE TITLE
Adjust tiled gallery height to one big image

### ISSUE THREAD

**Issue by DonTimo** [Automattic/jetpack#84]
Would be great if the height of the tiled gallery could be adjusted, so that one can has full width gallery, but e.g. on the left side one image and the others on the right side of it, smaller and all together maximum the height of the big one. Think that would look great if you can have an article heading above the gallery and under it goes the main article text. Look at this scribble to see what I mean...
![tiled-gallery-width](https://f.cloud.github.com/assets/5662013/1943814/68053d72-7fb0-11e3-97c0-624243a4dd06.png)

**Comment by dzver** [comment]
Very nice idea. I have a question though. What happens if I have 154 images in my gallery?

The implementation of this isn't hard at all, but it wouldn't scale beyond 5-10 photos and the first one cannot be landscape.

**Comment by DonTimo** [comment]
Thanks for your reply. I thought that this would be an option for small galleries nice to have, as you said. Currently you cannot set a fixed height value for the gallery (especially with smaller ones) right? So this might be the answer, to have one photo to which the others around are adjusting. Depends on how wide the landscape would be. Than there is the option to only show the landscape image in one line and below the others that aren't landscape. It would be great if you could implement this function.

**Comment by dzver** [comment]
Could you give an example of a theme that will benefit of this kind of galleries?

If you fix the height, the width will become variable. So the screen will need to be infinitely wide.

**Comment by DonTimo** [comment]
A problem I experience sometimes with the fixed width is that Jetpack creates very high images but meanwhile puts some images in another line that would fit in one row if some images would be smaller in a whole. Maybe you know a solution to this issue?

**Comment by dzver** [comment]
When #1799 gets merged, the mosaic tiles will be way more balanced.

**Comment by DonTimo** [comment]
Okay, looking forward to new version. Thank you for replying!

**Comment by jeherve** [comment]
Closing this issue since #1799 was added to Jetpack 3.5.

**Comment by s-a-s-k-i-a** [comment]
In what way was this added?
I am trying to adjust height of a gaööery to be always the height of the gallery containing container.. any tips?

**Comment by zinigor** [comment]
As you can see here, it wasn't really added in the way it was initially requested. The galleries just got more diverse in shapes. They are pretty predictable, and if you keep a certain amount of images in them, they will stay the same height. How are you trying to have them the same height as the container, though?

**Comment by s-a-s-k-i-a** [comment]
Well that is exactly my question.. would be a good thing to be able to set them to container height value automatically...

**Comment by s-a-s-k-i-a** [comment]
It would be a js solution I suppose and I think this would be the most handy solution for anyone who'd love to fit the jetpack gallery into a certain "box".
A simple "force to fit surrounding container"-skript - no matter the viewport sizing.

The size (height and width) of the container could vary, depending on given theme css.
