### ISSUE TITLE
Contact Form: add reCaptcha Support

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#840]
Jetpack's Email sharing button supports [Google reCaptcha](http://www.google.com/recaptcha) (see documentation [here](http://jetpack.me/support/sharing/#captcha)). It would be nice to add Recaptcha support to the Contact Form as well.

Suggested here:
- http://wordpress.org/support/topic/captcha-needed-for-grunion-contact-form?replies=14#post-2501163

Original trac ticket:
- https://plugins.trac.wordpress.org/ticket/1880

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/suggestion-recaptcha-integration-to-jetpack?replies=1&view=all

**Comment by 44ug3n** [comment]
this is a good idea (y)

**Comment by v18** [comment]
2782717-t

**Comment by kraftbj** [comment]
2993133-t

**Comment by lschuyler** [comment]
#2986514-t

**Comment by richardmtl** [comment]
3028198-t

**Comment by lezama** [comment]
1456153-t

**Comment by aheckler** [comment]
611506-zen

**Comment by danyork** [comment]
I'll note that someone has now created a plugin with this functionality:

https://wordpress.org/plugins/recaptcha-for-jetpack/

The code is on Github at https://github.com/elhardoum/jetpack-recaptcha

**Comment by Bachsau** [comment]
Why is this marked as "Wontfix"?

**Comment by jeherve** [comment]
@Bachsau That is because this will not be added to Jetpack. If you'd like to add such a feature to Jetpack, I would recommend using a plugin like this one:
https://wordpress.org/plugins/recaptcha-for-jetpack/
