### ISSUE TITLE
#3489 XHTML compliance regression

### ISSUE THREAD

**Issue by eligrey** [Automattic/jetpack#8415]
There is a regression of the issue fixed in #3489. On my site, when stats are enabled, Jetpack emits a script tag with `async defer` instead of `async="" defer=""`.

**Comment by dsamarin** [comment]
I propose creating a new test which performs XHTML validation in order to prevent future regressions which break XHTML sites.

**Comment by eligrey** [comment]
@jeherve Could you take a look at this issue again?
