### ISSUE TITLE
Suggestion: Toggle off the selected website from Jetpack debugging tool's dropdown list when another website is typed manually

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/jetpack#8416]
Visit [Jetpack's debugging tool](https://jetpack.com/support/debug/) and login with your WordPress.com account.

You have an option to choose the website you want to debug, from the dropdown list, or enter the website in the text field right below. 

**Problem**: There could be a confusion when a website is chosen from the list and another website is typed on the text field. _(like shown below)_

![image](https://user-images.githubusercontent.com/18581859/34321412-b31eb298-e834-11e7-896f-f880ad42bed5.png)

**Suggestion**: Here is what can be done. Toggle off the selection from the list when a website is typed manually in the text field.

There's nothing wrong in the current working process of the debugger. The website entered on the text field clearly takes precedence over the one chosen from the dropdown list, but the process could be improved to communicate the process better.

**Comment by jeherve** [comment]
Thanks for the feedback. I am going to close this issue but we are tracking this internally! We will update this issue when things change.
