### ISSUE TITLE
Sharing: improvements to the "More" dropdown

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#843]
Steps to reproduce:
1. In Settings > Sharing, drag services to the "hidden services" area, to create a "More" dropdown on your site
2. Open one of your posts, and move your mouse over the Dropdown menu
   - The menu opens
3. Click outside of the "More" area
   - The menu doesn't retract.

Would it be possible to retract the menu when you click outside of it?

Suggested here:
- http://wordpress.org/support/topic/nonstandard-behavior-in-share-drop-down-menu-feature?replies=1

Original trac ticket:
- https://plugins.trac.wordpress.org/ticket/1844

**Comment by dereksmart** [comment]
This appears to have been fixed. The dropdown disappears when you're no longer hovering over the `more` button
