### ISSUE TITLE
Markdown: add support for `target` extra attribute

### ISSUE THREAD

**Issue by JamesMackerel** [Automattic/jetpack#8437]
[

#### Steps to reproduce the issue
1. Install JetPack and enable markdown mode
2. new post, input those text:
```markdown
[Test link](https://example.com){target=_blank}
```
3. show preview
#### What I expected
```markdown
<a href="https://example.com" target="_blank">Test link</a>
```
see documentation: <https://michelf.ca/projects/php-markdown/extra/>
#### What happened instead
```markdown
<a href="https://example.com">Test link</a>
{target="_blank"}
```
Software Version:
- JetPack 5.6.1
- Wordpress 4.9.1–zh_CN

My plugin list is here:

![Snipaste_2017-12-31_01-27-00.png](https://i.loli.net/2017/12/31/5a47cd4b98bb5.png)

**Comment by jeherve** [comment]
Our version of Markdown Extra only supports .class and #id extra attributes so far. It would need to be updated to support target.

It looks like the original parser does not support target yet either:
https://github.com/michelf/php-markdown/blob/lib/Michelf/MarkdownExtra.php#L189-L204

**Comment by JamesMackerel** [comment]
Thank you for replying me. 

Yet there is another feature to be supported：
```markdown
- [ ] foo
- [ ] bar
```
should be rendered to:
- [ ] foo
- [ ] bar

but it was rendered to:
```html
<ul>
<li>[ ] foo</li>
<li>[ ] bar</li>
</ul>
```

**Comment by jeherve** [comment]
While Jetpack's Markdown includes some of the syntax from GitHub-Flavoured Markdown, it does not support checkboxes. Doing these well would require some front end interaction, and Jetpack Markdown does not do that; it is strictly a writing tool and does not add anything to the front end of your site. We most likely won't be adding that feature to Jetpack Markdown.
