### ISSUE TITLE
RSS Issue

### ISSUE THREAD

**Issue by EditorAtSoapbox** [Automattic/jetpack#8448]
Hi,

I have tried to upload my RSS feed to several readers but seem to be having some issues. I have this line highlighted as the problem...
site xmlns="com-wordpress:feed-additions:1">115107705</site

#### Steps to reproduce the issue

You can reporduce the issues by clicking the link. It will take you through to the RSS checker results.
https://validator.w3.org/feed/check.cgi?url=https%3A//www.sp-bx.com/feed/

Any suggestions?
Thanks

**Comment by jeherve** [comment]
That namespace is indeed added by Jetpack. It does not invalidate your RSS feed though. As you can see in the validator, the feed is still valid:

![screenshot 2018-01-03 at 13 51 30](https://user-images.githubusercontent.com/426388/34521270-32c74162-f08d-11e7-80b0-7ac43d9d6ad9.png)

I tried adding your feed to my own RSS reader and did not experience any issues, it seems to work:

- Adding the feed
![screenshot 2018-01-03 at 13 52 24](https://user-images.githubusercontent.com/426388/34521339-901c0c94-f08d-11e7-8804-4f6f66a2085d.png)
- Listing recent entries
![screenshot 2018-01-03 at 13 53 04](https://user-images.githubusercontent.com/426388/34521341-9285e630-f08d-11e7-99b0-1245431da7df.png)
- Displaying an entry
![screenshot 2018-01-03 at 13 53 13](https://user-images.githubusercontent.com/426388/34521351-9526b52c-f08d-11e7-93a9-9f382f7e20a1.png)

If your RSS feed can't be used in a different RSS reader, I would recommend that you get in touch with the team developing that reader to find out more.

I hope this helps.
