### ISSUE TITLE
Contact Form: notifications duplicated when using Gutenberg

### ISSUE THREAD

**Issue by TheJeffr0** [Automattic/jetpack#8451]
I'm using Gutenberg 1.9.1 with Jetpack 5.7 and WordPress 5.0 Alpha. When adding or editing posts or pages in the Gutenberg editor, there are two notification bubbles next to the Feedback Menu item. 

![twofeedbacknotifications](https://user-images.githubusercontent.com/6315977/34535445-ca36cac0-f08f-11e7-97fb-c4643ccb14bf.png)

**Comment by jeherve** [comment]
To reproduce the issue:

1. Install Jetpack and Gutenberg.
2. Create a new contact form in one of your posts.
3. Submit a form to create a notification bubble.
4. In your dashboad, go to Gutenberg > Demo.

The notification bubble will then be duplicated.

**Comment by MichaelArestad** [comment]
@jeherve is this still an issue?

**Comment by jeherve** [comment]
No, not anymore. I can't seem to reproduce the issue now. Closing.
