### ISSUE TITLE
Jetpack Dashboard: Query Performance

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#8457]
Currently when you load the Jetpack dashboard, we update the file_data transient, we do that in a loop which causes rapid updating of the DB. 

#### Steps to reproduce the issue
Enable the query monitor plugin. Notice that the queries are slow on the Jetpack dashboard.

#### What I expected
To just update the DB once. 

#### What happened instead
We update the DB transient many times.

**Comment by jeherve** [comment]
Related: #8268

This was implemented in #8056

**Comment by jeherve** [comment]
Also discussed in #19823

**Comment by archon810** [comment]
Can we please raise the priority to High? It's a very serious issue.

**Comment by maciejmackowiak** [comment]
The transient `_transient_jetpack_file_data_` is used just to cache the jetpack modules data, right?

Wouldn't be better to store it as a PHP variable, why do you need to hit the DB to retrieve this data if it is basically static?

I understand that the transient is used to avoid reading all the files on every page load but you could generate the PHP variable in a build process when releasing new plugin version.

**Comment by jeherve** [comment]
> Can we please raise the priority to High?

We'll take another look at this and update this issue as soon as we have some news.

Internal reference: p1620899993127900-slack-CBG1CP4EN

**Comment by archon810** [comment]
https://github.com/Automattic/jetpack/issues/19823#issuecomment-858438997

**Comment by SeBsZ** [comment]
Please give this the highest priority. Thank you!

**Comment by archon810** [comment]
@kbrown9 Glad to see this issue is finally getting some attention. Can you please clarify that the solution will also address and resolve https://github.com/Automattic/jetpack/issues/19823? Specifically, that these `_transient_jetpack_file_data_X.X` db queries will not be triggered by regular site visitors and DDoS the site as a result?

**Comment by kbrown9** [comment]
> @kbrown9 Glad to see this issue is finally getting some attention. Can you please clarify that the solution will also address and resolve #19823? Specifically, that these `_transient_jetpack_file_data_X.X` db queries will not be triggered by regular site visitors and DDoS the site as a result?

Hi @archon810 - yes, the solution I'm proposing for this issue will address issue #19823, and the `_transient_jetpack_file_data_X.X` db queries won't be necessary. The proposed solution in Pull Request #20183 is basically the same as the one proposed [in this comment](https://github.com/Automattic/jetpack/issues/8457#issuecomment-840443245).

**Comment by archon810** [comment]
Our sites got taken down by this bug yet again today. Any idea when the bug fix will be released, as I have no choice but to disable Jetpack until a fix is released.

**Comment by sdixon194** [comment]
@archon810 Best intentions are always subject to change, but once the PR https://github.com/Automattic/jetpack/pull/20183 gets approved and merged, the fix will likely be included when Jetpack 10.0 releases, which is scheduled for August 3rd, 2021. Thanks for your patience, I know this has been a long standing issue for you.
