### ISSUE TITLE
Top of each page Ads 'Error updating settings'

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/jetpack#8460]
#### Steps to reproduce the issue

I have only been able to reproduce the issue on one site. Internal reference: p8yzl4-15R-p2

#### What I expected

I expected being able to select 'Top of each page' option in JetPack ads settings

#### What happened instead

You get an 'Error updating settings' error and the settings arent updated.

Steps I followed on the site to try to figure out what's happening
- I reconnected jetpack 
- I deactivated the only aditional plugin adsense-plugin (Even uninstall it)
- I changed the theme
- NO chance with Kibana

**Comment by rantoncuadrado** [comment]
![screencast 2018-01-04 11-35-19](https://user-images.githubusercontent.com/6404071/34562158-736ed354-f14d-11e7-90d6-12ca2671a3ca.gif)

**Comment by jeherve** [comment]
Closing this, as this seems to be a one-off and I've followed up on the internal thread.

**Comment by benjaminaaron** [comment]
I get the exact same error-behaviour on kunstevent.net. Any tips from your internal thread that I could try?

**Comment by jeherve** [comment]
@benjaminaaron Could you try the following:

<ol>
	<li>Open the dashboard page.</li>
	<li><a href="https://codex.wordpress.org/Using_Your_Browser_to_Diagnose_JavaScript_Errors#Step_3:_Diagnosis">Open your browser console</a></li>
	<li>Click on the Network tab</li>
	<li>Refresh the page.</li>
	<li>Try to make changes to any of the settings, including the Ads settings.</li>
	<li>If you see any lines in red inside the browser console, click on them. A new panel should appear on the right.</li>
	<li>Click on the "Response" tab in that new panel.</li>
	<li>Copy the message displayed there.</li>
	<li>Paste it here.</li>
	<li>If no red lines appeared in the browser console, click on the "Console" tab of the browser console.</li>
	<li>Copy any errors displayed there, and paste them here.</li>
</ol>

**Comment by benjaminaaron** [comment]
Thanks for your response @jeherve, much appreciated. I was about to following your suggestions, but now it works all of a sudden - changes I make get saved instead of that error message. 
Should the error occur again I'll follow your steps.
