### ISSUE TITLE
Search: Allow reordering of filters in widget

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#8467]
While a filter can be added after any other filter, a user can not currently reorganize filters by dragging and dropping or some other simple UI.

It would be nice if we could provide a simple way for users to order their filters.

Originally reported in #8372

**Comment by gibrown** [comment]
An additional problem here is that the location of the "Add" link makes it non-obvious what it is going to do. Feels like that link should be in between the items, or we should only allow adding at the end and then let the user reorder them all.

![screen shot 2018-01-16 at 6 24 47 pm](https://user-images.githubusercontent.com/820871/35020770-ea29efbe-faea-11e7-8acf-1da33df64c1b.png)

**Comment by gravityrail** [comment]
I do believe this is done!
