### ISSUE TITLE
Search: Admin: Prompt users to get professional for search functionality

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#8468]
Currently, we do not show UI to turn on search in the react admin if the site does not have a professional plan.

Instead of hiding search, perhaps we should tell users about the benefits of search and suggest they upgrade?

We hide the search setting here:

https://github.com/Automattic/jetpack/blob/master/_inc/client/traffic/search.jsx

Where we return null if the site does not have a professional plan.

Reported in #8372

**Comment by gibrown** [comment]
The bigger deal is probably including search in Calypso when users are comparing plans, and on the pricing pages.
