### ISSUE TITLE
Verification Tools: Update example text

### ISSUE THREAD

**Issue by csonnek** [Automattic/jetpack#8485]
Related to #5782 - the example code we have listed for each service is incorrect: 

![siteverification](https://user-images.githubusercontent.com/2814452/34690159-aa62bafa-f47d-11e7-811e-50082cd01cbf.png)

Users continue to try and copy and paste the full meta tag in the field, which generates an error message as that's the wrong data we're expecting for those fields. 

Our [support documentation](https://jetpack.com/support/site-verification-tools/) does clarify that we only need the `content` variable, but updating the text to reflect how we used to show in previous versions of Jetpack would be a huge help in reducing user questions and problems: 

![siteverification2](https://jetpackme.files.wordpress.com/2014/05/site-verification-tools.png)

**Comment by UP-Nguyen** [comment]
Hi csonnek! I'd like to take a crack at this problem! This will be my first time contributing to WordPress, and I'm unsure where to find this file. I looked in jetpack's tools, but couldn't really find anything. Any tips and pointers?

**Comment by UP-Nguyen** [comment]
Oh! I have found the file I should edit:

https://github.com/Automattic/jetpack/commit/a27b57082c48da0bb5572c3322836693c1d3d59c

**Comment by UP-Nguyen** [comment]
Never mind! I have found the issue!

**Comment by jeherve** [comment]
Fixed in #10040
