### ISSUE TITLE
Sharing: Add VK.com sharing button

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#849]
VK.com is a popular Russian Social network, offering sharing and Like buttons.

Suggested here:
- http://wordpress.org/support/topic/add-vkcom-with-number-of-times-the-post-to-sharing

Original trac ticket:
- https://plugins.trac.wordpress.org/ticket/2016

Here is a Jetpack add-on I released in the meantime:
- http://wordpress.org/plugins/vk-sharing-jetpack/

If that plugin becomes popular, it will be a good indicator that VK.com is a good candidate to be included. But so far the plugin doesn't seem very popular.

**Comment by VadymVolos** [comment]
Yes need. vk.com popularity.

**Comment by annezazuu** [comment]
requested 2486150-t

**Comment by SPEC1AL1ST** [comment]
Yes please add publicize to vk.com. Its very important for russian speaking communities

**Comment by davoraltman** [comment]
requested 2655061-t

**Comment by lamdayap** [comment]
requested 2689862-t

**Comment by lschuyler** [comment]
requested in 3069603-t . Recommending this plugin in the meantime:
https://wordpress.org/plugins/vk-sharing-jetpack/

**Comment by wpadmin** [comment]
В блочном редакторе нет этих возможностей :(
