### ISSUE TITLE
Caching Ajax Requests

### ISSUE THREAD

**Issue by davidbarratt** [Automattic/jetpack#850]
Is there a way to cache some of the Ajax Requests made by Jetpack?

I noticed that Infinite Scroll, Related Posts, and Carousel make some heaven / often Ajax Requests. I use https://wordpress.org/plugins/w3-total-cache/ but it appears that Ajax Requests in Infinite Scroll & Related Posts are not cached because of their query string. I can use Memcache for those (http://wordpress.org/support/topic/plugin-w3-total-cache-enable-cache-uris-with-query-string-variables#post-1916553). However, Carousel seems to go to admin-ajax.php which is never cached. How can that request be cached?

Thanks!

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
