### ISSUE TITLE
Module List: Lazy Images item reloads page instead of linking to support

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#8502]
#### Steps to reproduce the issue
1. Open the full module list at `/wp-admin/admin.php?page=jetpack_modules`
2. Click on the Lazy Images title text.

#### What I expected
It should link to its corresponding support page as the other modules do - https://jetpack.com/support/lazy-images/ in this case

#### What happened instead
It reloads the module list in a new tab

**Comment by jeherve** [comment]
Fixed in #8463
