### ISSUE TITLE
Feedback CSV export fields not in same order as form fields

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#8512]
#### Steps to reproduce the issue

1. Add a contact form to a page, with some fields e.g. Name, Email, Message. Save the form.
2. Submit feedback through the new contact form.
3. Export the feedback as CSV. Fields (columns) are in the correct order.
4. Edit the form and add a new field e.g. Last Name.
5. Change 'Name' to 'First Name' and drag 'Last Name' into position below 'First Name'. Save the form.
6. Submit feedback through the form.
7. Export the feedback as CSV.

#### What I expected

The 'Last Name' column should be next to the 'First Name' column.

#### What happened instead

The 'Last Name' column is on the far right, after the 'Message' column, and the 'First Name' column is still called 'Name'.

895379-zen

**Comment by jeherve** [comment]
Related: #2738

**Comment by jeherve** [comment]
Also reported in #25024.

**Comment by digitalwaveride** [comment]
Issue will be fixed via: https://github.com/Automattic/jetpack/pull/30475

**Comment by digitalwaveride** [comment]
Issue is fixed via https://github.com/Automattic/jetpack/pull/30475
