### ISSUE TITLE
Integrate plugin to improve readability for stats 

### ISSUE THREAD

**Issue by 00travelgirl00** [Automattic/jetpack#8519]
Hey folks, 

I have read a question from a WordPress user how to change the font-sizes and colors in the stats section, because she had problems to read it (to small, to light, ...) 

So I wrote a plugin for her to increase the readability and I would be great, if you could implemented in the plugin. 
You can find the plugin here: 

https://github.com/00travelgirl00/a11y-jetpack

I also can write a pull request, if you are fine with the design changes. 

Thank you

**Comment by jeherve** [comment]
Are those changes applied to the old Stats page under Jetpack > Site Stats in the dashboard?

Could you make a few before / after screenshots of your changes so we can see what they are?

Thank you!

**Comment by jeherve** [comment]
Related: #1796

**Comment by 00travelgirl00** [comment]
The Changes applies to the current Jetpack Plugin at the repository for Jetpack > Stats. 

Their are all small changes, put improves the readability for users. 


<img width="1124" alt="1_improvemtent" src="https://user-images.githubusercontent.com/21318377/35090957-987cf272-fc3b-11e7-9a65-e126897901bc.png">
<img width="1124" alt="1_original" src="https://user-images.githubusercontent.com/21318377/35090960-997b8d96-fc3b-11e7-80f8-8f4f962e65be.png">
<img width="1126" alt="2_improvment" src="https://user-images.githubusercontent.com/21318377/35090961-99dd30aa-fc3b-11e7-88be-53dd979d1926.png">
<img width="1126" alt="2_original" src="https://user-images.githubusercontent.com/21318377/35090962-9a21735a-fc3b-11e7-9046-7e5ea8d2ed53.png">

**Comment by jeherve** [comment]
Thank you. I will let one of our designers weigh in on the changes 👍 

cc @rickybanister

**Comment by 00travelgirl00** [comment]
I would really like to see this plugin to be merged, as it includes simple changes, that improves readability and accessibility. Are there any blockers, why it is not merged so far?

**Comment by jeherve** [comment]
This should now be fixed, as the Stats page was recently redesigned.

We're aware of some more accessibility improvements to that new page, and will be taking care of them as part of this issue:
https://github.com/Automattic/wp-calypso/issues/74321
