### ISSUE TITLE
Widget Visibility: add an AND condition

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#852]
Use case: I want to display a widget when viewing single posts, but only if they belong to a specific category.

To do so, I would need to combine 2 conditions:
- Show if Page is Post
- Show if Category is X

![](http://i.wpne.ws/RtUR/content)

At the moment, you cannot combine 2 conditions: it's either one or the other. it would be nice to add an AND condition to solve this issue.

Suggested here:
- http://wordpress.org/support/topic/problem-with-widget-visibility-with-tags

Original trac ticket:
- https://plugins.trac.wordpress.org/ticket/1987

**Comment by fgilio** [comment]
+1
georgestephanis, that would be a really nice improvement!

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/widget-visibility-w-and-instead-of-or?replies=1&view=all

**Comment by jeherve** [comment]
Fixed in #6327
