### ISSUE TITLE
Plan Upgrade links: wrong url for site resulting in "not valid url" for sites with a path

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#8524]
When trying to upgrade my JP site using one of the many "Upgrade links", I get to a screen where the site url is displayed as "gibrown.wpsandbox.me%3A%3Atest0" and get a message "not a valid url".

![screen shot 2018-01-14 at 9 14 08 pm](https://user-images.githubusercontent.com/820871/34927068-c9cdf6e6-f970-11e7-86aa-980a68cbfaac.png)

If I replace the mess with a slash everything is fine.

The link for the upgrade buttons all seem to be something like: https://jetpack.com/redirect/?source=support&site=gibrown.wpsandbox.me::test0

When I get into Calypso I see urls like: https://wordpress.com/jetpack/connect?url=gibrown.wpsandbox.me%253A%253Atest0

I'm not sure if the link here needs to change, or calypso needs to reinterpret that string.

This is with the current version of master.

**Comment by jeherve** [comment]
Do you happen to remember what upgrade link you clicked in the dashboard to get there?

**Comment by gibrown** [comment]
Happens with all of them in the dashboard and settings I think. I tried a couple, but at the very least it happened on the search settings one.

**Comment by beaulebens** [comment]
@gibrown I think this is maybe fixed with some recent changes in how the redirection system works; can you please reconfirm if this is still happening?

**Comment by gibrown** [comment]
I can't get this fail in at all the same way anymore, so going to mark it as closed. The flow has definitely changed here, so probably is fixed.
