### ISSUE TITLE
Widget Visibility Module shows "setup" button, when it should be "activate"

### ISSUE THREAD

**Issue by rebeccahum** [Automattic/jetpack#8525]
#### Steps to reproduce the issue

I haven't been able to consistently reproduce the issue to track exactly what is causing it, but going to wp-admin > Jetpack > Settings and searching for the "Widget Visibility" module are the steps to produce it.  

#### What I expected

<img width="750" alt="screen shot 2018-01-08 at 2 19 14 pm" src="https://user-images.githubusercontent.com/16962021/34945977-4c74ceac-f9c2-11e7-98f8-90c7466d1237.png">

#### What happened instead

![image](https://user-images.githubusercontent.com/16962021/34946019-775b79fe-f9c2-11e7-916e-fce271588e3c.png)

VIP Ticket for reference: #72898-z

**Comment by keoshi** [comment]
Actually, after re-reading the issue, this seems to be expected behavior.

This is what is displayed if the module is not activated:

<img width="750" alt="screen shot 2018-01-08 at 2 19 14 pm" src="https://user-images.githubusercontent.com/16962021/34945977-4c74ceac-f9c2-11e7-98f8-90c7466d1237.png">

This is what is displayed when the module is active:

![image](https://user-images.githubusercontent.com/16962021/34946019-775b79fe-f9c2-11e7-916e-fce271588e3c.png)

Though I'm not seeing the “Set up” button at all.

Can one of you confirm please, @samhotchkiss @dereksmart ?

**Comment by jeherve** [comment]
> Though I'm not seeing the “Set up” button at all.

That seems to be the issue here, yeah.

**Comment by rebeccahum** [comment]
@keoshi @jeherve That is correct, the "Set up" button should not be there I think.  On clicking it, it brings me to this page:
![image](https://user-images.githubusercontent.com/16962021/36916163-5d4ace76-1e10-11e8-8e1e-4aa82c81bfd7.png)

**Comment by rcoll** [comment]
@rebeccahum I'm having trouble reproducing this on a normal Jetpack site. Where were you able to reproduce this? I'm assuming VIP GO - or was it somewhere else?

**Comment by oskosk** [comment]
After some digging, got to realize that this problem should pop up when:

* seeing modules that are not paid features
* testing with a paid plan

Apparently the set up/activate/active button is part of a `ProStatus` component which is supposed to guide paid customers . So it shouldn't show for anything other than backup-related or spam-related things IMO.

**Comment by eliorivero** [comment]
Following this URL takes me to that landing page
https://wordpress.com/plugins/setup/undefined?only=akismet

and the only place where something like that is located is in 
https://github.com/Automattic/jetpack/blob/master/_inc/client/pro-status/index.jsx#L138

which is consistent with the "Set up" label.

This is just the diagnose of where this is coming from. I'm still digging what are the conditionals that took to reach this point.

**Comment by eliorivero** [comment]
@rebeccahum https://github.com/Automattic/jetpack/pull/9091 should fix this and would be great if you could test it.

The issue was that there was a checking for a plan and that it wasn't a free Jetpack plan, but it could be any plan. So a VIP plans meets these conditions.

**Comment by oskosk** [comment]
There are two fixes for this now :P.  #9091 and #9096

**Comment by rebeccahum** [comment]
@rcoll That is correct, it was occurring on VIP Go.

@oskosk @eliorivero Tested #9096 and it works!  Thank you for your hard work.
