### ISSUE TITLE
Search: Sticky posts should be excluded from search results

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#8534]
Building off of #8471

I have a feeling that this is how core treats sticky posts, but it feels really strange. It is especially a problem when the post_type is set to page, but a post is also shown.

Try at http://gibrown.wpsandbox.me/main/?s=post&post_type=page

**Comment by Viper007Bond** [comment]
Fixed in 84c39273984a02f66a84127f9d72fad222ade929 via `ignore_sticky_posts`.
