### ISSUE TITLE
Sitemap: Needs more informative message when being generated

### ISSUE THREAD

**Issue by catchmyfame** [Automattic/jetpack#8549]
We just updated Jetpack, and when checking out sitemap.xml file saw a nearly empty page with the text: 

> "No sitemap found. Maybe it's being generated. Please try again later."

After several hours there was still no sitemap (and the same message was displayed), but at some point (> six hours) the sitemap was generated. 

We were close to opening a support ticket since we weren't sure if there was a problem or if things were working as expected. It would be _far_ more helpful if there was some actual status information provided, rather than "Maybe it's being generated". What determines when the sitemap is generated and is there a way to check the status so that it can be displayed?

**Comment by zinigor** [comment]
Thank you for reporting this issue! You are right, we could explain the situation a little better here, we'll try to fix that in one of the next releases. Judging by what you say, your sitemaps are fine now. If not, please do contact support.

**Comment by kraftbj** [comment]
I think this may be related to the issue fixed by #10274 where it could be a decent amount of time before the sitemap was initially created. For admins, though, we should display the next generation time which should give more context than we report now.
