### ISSUE TITLE
Comments: add an option to log in to self-hosted WP account

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#855]
At the moment, JP Comments allow you to log in via WordPress.com, FB, Google+, and Twitter. It would be nice to allow users to log in to their self-hosted WordPress installation through there.
Suggested here:
- http://wordpress.org/support/topic/click-an-icon-to-log-in-add-local-wp-login?replies=1

Original trac ticket:
- https://plugins.trac.wordpress.org/ticket/1807

**Comment by cambiatufisico** [comment]
Please, this issue was released several months ago... I do not understand why the option is not allowed...

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/comments-via-local-account?replies=1&view=all

**Comment by cambiatufisico** [comment]
"enejb removed their assignment"

Hummm... this looks bad...

**Comment by jeherve** [comment]
@cambiatufisico Enej works on other parts of Jetpcak now, but don't worry:  if that suggestion becomes popular we'll consider adding it to Jetpack!

**Comment by samhotchkiss** [comment]
This is not in line with our current priorities/roadmap.  We may re-assess down the road, but I'm closing for now.  If there are 3 more requests after this comment, please re-open.

**Comment by aheckler** [comment]
request number 1: 3120773-t
