### ISSUE TITLE
Search: If filter has no name, don't show heading

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#8554]
Currently, if a filter doesn't have an actual name, we set it to a key that we used to generate the ES aggs. Let's not do that.

<img width="452" alt="screen shot 2018-01-17 at 2 54 46 pm" src="https://user-images.githubusercontent.com/1126811/35066531-8dc30aa6-fb96-11e7-999e-da3e9e93924f.png">

**Comment by Viper007Bond** [comment]
Rather than not displaying it, why not pull it from the registration?

```
$taxonomy= get_taxonomy( $tax_slug );
echo esc_html( $taxonomy->labels->name );
```

**Comment by ebinnion** [comment]
ahh, Ahh, I dig that. So, for:

- "post_type" filters, we'd just use `__( 'Post Type', 'jetpack' )`
- "date_histogram", we'd use something like "Posts by month", "Post by year", etc.
- "taxonomy", we'd use the taxonomy name
