### ISSUE TITLE
Post By Email: Add alt text for images

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#856]
As requested in this thread: http://wordpress.org/support/topic/post-by-email-no-alt-for-image?replies=1

Include a shortcode for adding alt text to images sent via Post By Email, or automatically create an alt text from EXIF or the file name.

Original trac ticket:
- https://plugins.trac.wordpress.org/ticket/1939

**Comment by samhotchkiss** [comment]
Our implementation of Post by Email is intended to be very simple and minimal, so, unfortunately, this doesn't align with our development goals and plans at this time, and is not on our roadmap for future development.
