### ISSUE TITLE
Search: max_offset is wrong in multiple ways

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#8560]
We have a hardcoded max offset of 200: https://github.com/Automattic/jetpack/blob/master/modules/search/class.jetpack-search.php#L12

This is wrong in a couple of ways:
- The current max in the API is actually 50 for JP Search
- The max for VIP indices is 10,000
- There is no max_page_size implemented even though the max for JP Search is 15 and the max for VIP is undefined
- ES has a maximum of 10,000 for size+from

API docs: https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/search/

So I think we should make the following changes:
- Set the max based on whether this is VIP or not. I think we should probably have a define that indicates that the site has a VIP index. JETPACK_SEARCH_VIP_INDEX = true
- JP Search limits: size <= 100, from <= 1000
- VIP limits: size <= 1000, from <= 10,000 (and also check that size+from < 10,000

This will require some changes to the APIs and docs but I was thinking to increase these limits already.

**Comment by ebinnion** [comment]
API side shipped in r169043-wpcom
