### ISSUE TITLE
Add Geolocation options to Jetpack

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#857]
Carousel already supports Geolocation, the REST API can also include this data, and it's enabled on WordPress.com. It'd be nice to have it in Jetpack too.

Original trac ticket:
- https://plugins.trac.wordpress.org/ticket/2021

> http://wordpress.org/plugins/geolocation-plus/ hasn't bee updated since 3.4.2; it could be updated and brought in as a Jetpack Module.

**Comment by camaran** [comment]
+1

**Comment by jeherve** [comment]
Closing as `wontfix` as we haven't received any other requests.

**Comment by jeherve** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/4099
