### ISSUE TITLE
Contact Form: Different contact form recipients based on form choice

### ISSUE THREAD

**Issue by cafenoirdesign** [Automattic/jetpack#8572]
One of our VIP clients requested a way to send the Jetpack contact form to different recipients (different organization departments) based on what the visitor chooses in a pull-down menu built into the form. That way sales leads would go to the sales department, support to the support department, etc. This would be a great feature for the community.

The Jetpack contact form does have the `contact_form_to` filter. 
https://github.com/Automattic/jetpack/blob/3.9.4/modules/contact-form/grunion-contact-form.php#L1836

However, it doesn't have the form context to be able to do what the client needs. Please consider this for a future release. Thanks!

**Comment by jeherve** [comment]
Closing as duplicate of #1613
