### ISSUE TITLE
Stats: add a bar graph next to each post on the Posts > All Posts screen

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#858]
On WordPress.com, you will find a "Stats" column under Posts > All Posts:

![](http://i.wpne.ws/SSIJ/content)

It would be nice to add the same feature to Jetpack sites.

Suggested here:
- http://wordpress.org/support/topic/jetpack-stats-per-post-1?replies=1

Original trac ticket:
- https://plugins.trac.wordpress.org/ticket/2039

**Comment by mitchellkrogza** [comment]
Any chance this will ever be implemented? Should not be too difficult and would be an extremely valuable add on to jetpack.

**Comment by jeherve** [comment]
That's not on our roadmap right now, but we'll update this issue as soon as we make progress on this.
