### ISSUE TITLE
Image Widget: pull images from Media Library

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#859]
The Jetpack image widget allows you to add an image URL by copying it from an outside source or from your Media Library.
It would be nice to offer an option to search the Media Library for an image directly from the widget settings.

Suggested here:
- http://wordpress.org/support/topic/great-features-but-missing-the-finishing-touch

Original trac ticket:
- https://plugins.trac.wordpress.org/ticket/1829

**Comment by jeherve** [comment]
Related: https://core.trac.wordpress.org/ticket/32417

**Comment by lancewillett** [comment]
Agree on focusing on core widget for this. Closing.
