### ISSUE TITLE
Sharing: Email share button producing error "Email check failed, please try again" 

### ISSUE THREAD

**Issue by donalirl** [Automattic/jetpack#8602]
#### Steps to reproduce the issue

1. Use the Email share button on any post, such as this: https://eatkibbeling2.wordpress.com/2018/01/15/new-post-%F0%9F%8E%89/
2. Input an email address and press 'Send Email'

#### What I expected

I expected the post to be shared by email.

#### What happened instead

The error `Email check failed, please try again` appeared in a red box: 
<img width="452" alt="dir2gpczjv-3000x3000" src="https://user-images.githubusercontent.com/426388/35326128-f690f64c-00f5-11e8-8ac9-711b027def88.png">

The result is the same after testing multiple, valid email addresses.

**Comment by jeherve** [comment]
I can't seem to be able to reproduce; the problem appears to be limited to WordPress.com sites only, and may be linked to our implementation of Google Recaptcha there: as you can see there is space for the Recaptcha challenge box but it does not appear in the window. We can also see a JavaScript error on the page:

`Uncaught TypeError: Cannot set property 'innerHTML' of null`

Here is the line that is concerned:
`e("recaptcha_challenge_field_holder").innerHTML = "<input type='hidden' name='recaptcha_challenge_field' id='recaptcha_challenge_field' value='" + d.challenge + "'/>";`

I would suggest that you create a new ticket on wpcom.trac to keep track of this issue.

Thank you!
