### ISSUE TITLE
Search: use AJAX (or React?) to refresh search results instead of page reload

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#8631]
Dan and @gibrown both got excited about the possibility of porting the react app we use in one of our tools. Perhaps we can revisit that.

As for functionality, I would expect filtering/updating the search would behave similar to infinite scroll where it updates the view without a refresh. We'll need to mock this up and how it can function on slow speeds.

**Comment by gibrown** [comment]
Closing this since the instant search prototype has implemented this. Yay!
