### ISSUE TITLE
Conflicting Vaultpress notices

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#8633]
![image](https://user-images.githubusercontent.com/1123119/35458966-a5840666-029b-11e8-91a7-68c4e214ae20.png)

I believe this one might already be resolved if Pressable is no longer installing Vaultpress. @ebinnion can you confirm?

Reported 9 days ago by @keoshi on p9rlnk-3m-p2

**Comment by ebinnion** [comment]
Jetpack Start no longer installs Pressable. I can confirm that. Just created a new site, connected Jetpack, did not get VaultPress installed.

**Comment by MichaelArestad** [comment]
You're the boss. Thanks @ebinnion!

**Comment by MichaelArestad** [comment]
Reopening because this is still going to be a problem for initial release unless @dereksmart has already worked his magic on it.

**Comment by dereksmart** [comment]
VaultPress no longer shows their messages at all.  All messaging is handled through Jetpack so there will be no conflicts
