### ISSUE TITLE
Search: UX adjustments

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#8635]
Pulling out a few easy-ish issues from @kellychoffman's walk through:
- Change "Title" to "Title (optional)"
- Have "Show search box" enabled by default
- Change "Show sorting controls" to "Show sort selection dropdown"
- Change "Default sort order" to have "Relevance (recommended)" as the default option.
- Change "Show extra filtering options" to just a button "Add a filter"
- Prefill the title of each filter based on the selected taxonomy. Maybe reorder them so the name is the third option?
- Don't show the help text "Where are my ..." when on the widgets page, only in customizer

cc @MichaelArestad

**Comment by MichaelArestad** [comment]
Nice!

**Comment by gibrown** [comment]
> Change "Show extra filtering options" to just a button "Add a filter"

I think that because we can now reorder filters, we could just have a single big button at the end of the list that lets the user add a new filter and we don't need to handle inserting filters in between.

**Comment by gibrown** [comment]
Should all be fixed in #8637
