### ISSUE TITLE
Lazy Images: Exclude some kinds of images from Lazy Images

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#8640]
#### Feature Request 

Exclude widgets, post thumbnails and Gravatars from Lazy Images. 

#### Info

From the forum 
https://wordpress.org/support/topic/lazy-images-issues-and-suggestions/

**Comment by Volnus** [comment]
I disagree with the idea to outright exclude all of these as they would cause major performance issues, particularly on posts with many comments or BuddyPress, installs where there are a large number of Gravatars. 

However, I do agree we need a better system to add exclusions for images or to start adding more exclusions.

To solve this issue we could build out the UI for Lazy Load so it escapes the current modules page and then when it's enabled we should have other options show below it for certain use cases to disable it for Gravatars, etc etc. While this adds more to the UI it won't sacrifice the performance benefits for everyone, and we don't have to start requiring everyone to add several filters to filter out what images they wanted lazy loaded or not. I think once we have a UI built for Lazy Load then selectively enabling or disabling like widgets, gravatars, etc.

**Comment by jeherve** [comment]
I don't think we'll add additional options in the UI; it would make the feature more confusing for some people.

> we don't have to start requiring everyone to add several filters to filter out what images they wanted lazy loaded or not

I agree that using several filters for one change seems overkill.

Overall, I think #8641 would be a good way to address this, by giving everyone control over the images they want to exclude.

I'll close this issue and we can continue this discussion in #8641.
