### ISSUE TITLE
Lazy Images: Add CSS classes, which is excluded from Lazy Images 

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#8641]
#### Feature Request 

Allow CSS class exceptions. 

For example, if I wanted to skip a particular image from being lazy loaded, I would love to add something like `class="nolazy"`. 

There are cases when we have to use other tools and plugins that simply won’t work with lazy images, so this will make it work

#### Info

* From https://wordpress.org/support/topic/lazy-images-issues-and-suggestions/
* Maybe related to #8640, PR - https://github.com/Automattic/jetpack/pull/8232

**Comment by ebinnion** [comment]
Hey @htdat – I've added this ability in #8787. That PR is not yet merged, but it _should_ make it to `5.9.0`.
