### ISSUE TITLE
Implement PageSpeed Recommendations for VideoPress JS (SSL)

### ISSUE THREAD

**Issue by EnigmaSolved** [Automattic/jetpack#865]
When the VideoPress Javascript (https://v0.wordpress.com/js/videopress.js?ver=1.09) is served via SSL Google PageSpeed indicates that a "cache validator" is missing.

**Specify a cache validator:**

```
The following resources are missing a cache validator. 
Resources that do not specify a cache validator cannot be refreshed efficiently. 
Specify a Last-Modified or ETag header to enable cache validation for the following resources:
https://v0.wordpress.com/js/videopress.js?ver=1.09
```

https://developers.google.com/speed/docs/best-practices/caching?csw=1#LeverageBrowserCaching

Unlike the `gzip` issue (https://github.com/Automattic/jetpack/issues/864) the above occurs for both Firefox and Chrome (and so is probably unrelated to the `gzip` issue).

PageSpeed also recommends the below (and the below is not specific to SSL VideoPress), but this seems less important than the above (and less likely to be changed as it likely gets into many other considerations).

**Remove query strings from static resources:**

```
Resources with a "?" in the URL are not cached by some proxy caching servers. Remove the query string and encode the parameters into the URL for the following resources:
https://v0.wordpress.com/js/videopress.js?ver=1.09
```

https://developers.google.com/speed/docs/best-practices/caching?csw=1#LeverageProxyCaching

Sean

**Comment by jeherve** [comment]
This is now fixed:

```
curl -I https://v0.wordpress.com/js/videopress.js\?ver\=1.09
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 21 Mar 2017 09:57:19 GMT
Content-Type: application/x-javascript
Connection: keep-alive
Vary: Accept-Encoding
Etag: W/"54dcf279-4290"
Expires: Wed, 21 Mar 2018 09:57:19 GMT
Cache-Control: max-age=31536000
X-ac: 1.vie _dca
Strict-Transport-Security: max-age=15552000
```
