### ISSUE TITLE
Search: Make WooCommerce Products searchable

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#8662]
Starting this ticket to track what we need to index to make Woo search better.

There are a bunch of fields to add from different post meta fields:
- reg price
- sale price
- review count
 - count
 - average rating
- featured
- product type
- SKU
- shipping info?
- stock status
- upsell ids (hardcoded list, could also auto gen a list from orders)
- cross sell ids (hardcoded list, could also auto gen a list from orders)

Content should also be indexed:
- all reviews should be attached to the post so that we can use the reviews as additional search criteria
- purchase notes
- could index reviews as comments so we can search reviews and do filtering on reviews

**Comment by StefMattana** [comment]
Possibly related in 1047772-zen. 
Dropping the reference ^^ here for future checkins with this user.

**Comment by spoyntersmith** [comment]
I am very keen to see this implemented, compatibility is needed with the different product types too (variable, grouped products etc...)

**Comment by gibrown** [comment]
> Woocommerce fields are generally private meta fields

@jenkoian ya, I'm working on doing this indexing, but this is definitely something that is giving me pause right now. I can index them, but then they won't really be private anymore. But technically they aren't really "private". They are "protected", and end up getting displayed on the front end anyways. Really I need to look more into how WooCommerce handles these in its public apis I think.

**Comment by alicam** [comment]
@jenkoian Ian, any chance you could share a little of that in a gist, for the inspiration of others. I'm seeing so little docco on ElasticSearch in Jetpack, so slow going!

**Comment by jenkoian** [comment]
@alicam yep! Which bit, the price range aggregations or..?

**Comment by gibrown** [comment]
Many of these fields should work (SKU and product categories at the least) in the new instant search experience, but we haven't done much testing and are needing to delay further work so we can ship.

**Comment by bizanimesh** [comment]
Hi team, Just want to confirm if it is possible to display product prices in Jetpack Search if the user has installed WooCommerce. 🙂

For Ticket [#3728749](https://woothemes.zendesk.com/agent/tickets/3728749)

**Comment by jeherve** [comment]
@bizanimesh No, it is not yet possible. This is currently being worked on, but the feature is not yet available. We will close this issue when it is available.

**Comment by JenSwish** [comment]
Hi team, Does JP Search index correctly for products that have custom permalinks? For example, using /puppies/ instead of /products/ in the product permalink.

For 3730322-zd-woothemes

**Comment by gibrown** [comment]
@bizanimesh fyi this is (one of) the PR where it is actively being worked on: https://github.com/Automattic/jetpack/pull/18225

**Comment by JoshuaGoode** [comment]
Seems like this shifted away from the base search module and to Instant Search.  Issues with the base search module and Woo still remain.

I recently reviewed that the base Jetpack Search module (not Instant Search) seems to prevent the use of WooCommerce filters within Woo product searches. To get this working properly, the module has to be deactivated.

***Example***
Here's a search string for a product titled TestProduct that has a color attribute of blue.  Woo lets us filter that attribute.

`?s=TestProduct&post_type=product&filter_color=blue`

This will only work if the Jetpack search module is disabled.  If enabled, the product search will return `No products were found matching your selection.`

This will also prevent WooCommerce extensions such as https://woocommerce.com/products/product-filters/ from working properly when paired with a search. 

---
I can open a separate report or report elsewhere if necessary.

---

An internal example was discussed on p9F6qB-6wy-p2

**Comment by gibrown** [comment]
@JoshuaGoode ya the "base search" is really deprecated and won't ever be getting updated to support things like woocommerce filters. It is being actively worked on for instant search though.

**Comment by gibrown** [comment]
I'm going to mark this as done. From an indexing perspective it is complete. There is still some ongoing cleanup of ensuring sync always works correctly (see #15672 and the related PR), but I don't think I've yet seen it fail. Displaying the results is being handled in some other issues and PRs but all seems to be working so keeping this open doesn't seem to help.
