### ISSUE TITLE
Search: default filter name in customizer is wrong

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#8670]
The widgets page in wp-admin is working ok, but in the customizer I am seeing one of the user's display names (this is test data) getting autofilled into every field.

<img width="547" alt="screen shot 2018-01-30 at 10 51 24 am" src="https://user-images.githubusercontent.com/820871/35582312-b5bbd4c4-05ab-11e8-8df5-40ba687198ff.png">

**Comment by gravityrail** [comment]
Try again? We've made some changes to how template selectors are scoped.

**Comment by gibrown** [comment]
OK, I can't reproduce anymore. Closing this.
