### ISSUE TITLE
Search: Fatal Error when used with the Debug bar plugin

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#8673]
When installing Jetpack's latest master on a test site running the Debug bar plugin, I ran into this issue:

```
[30-Jan-2018 20:45:34 UTC] PHP Fatal error:  Class 'Jetpack_Search' not found in wp-content/plugins/jetpack-dev/3rd-party/debug-bar/class.jetpack-search-debug-bar.php on line 34
```

This looks like something we should fix.

Related: #8615

cc @ebinnion

**Comment by ebinnion** [comment]
Can you give me any more information? I don't get a fatal and I tried a few different flows:

- search module on and off
- query monitor and debug bar plugin install
- only debug bag installed (no query monitor)
- loaded frontend and backend

**Comment by jeherve** [comment]
I can't always reproduce either, so I may not be super helpful:

- Jetpack was not connected to WordPress.com
- Search was consequently not active.
- Debug bar installed, as well as Log Viewer (not Query Monitor)
- Using Jetpack's Beta plugin, and running Bleeding Edge.
- Happened when loading both the backend and the frontend.
