### ISSUE TITLE
Connection banner spacing on wide-screen 

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#8677]
Spacing of images in connection banner is janky on wide screen.  Is there something we can do about this? cc @jeffgolenski maybe? 

![screen shot 2018-01-30 at 1 09 51 pm](https://user-images.githubusercontent.com/7129409/35597076-c45cb360-05ea-11e8-88f2-938342417341.png)

**Comment by jeffgolenski** [comment]
@dereksmart Well, my guess is that the amount of folks who actually see this isn't all too high. The fluidness of the connection banner stays consistent with the rest of the design patterns within /wp-admin/ . 

They all pretty much scale infinitely. But if you want to append a `max-width: 1200px;` or something to the container, feel free. But it may look even weirder with a big empty space to the right of the connection banner on super large screens.

**Comment by joanrho** [comment]
hey @dereksmart @rickybanister @jeffgolenski here's a gif mockup of what expanding that container's width could look like (here, set to 1250px). Thoughts?

![1250px width of jp connect content container](https://user-images.githubusercontent.com/204742/36801034-33ef4942-1c6e-11e8-9a38-b48eda5f55ac.gif)

**Comment by MichaelArestad** [comment]
I think we should just add a max width to the content inside each tab and center it horizontally.
