### ISSUE TITLE
Better default location for dashboard stats widget

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#8678]
Noticed that the stats dashboard module is at the end/bottom of the WP Dashboard — can we bump that to the top-left?

![screen shot 2018-01-30 at 6 31 49 pm](https://user-images.githubusercontent.com/7129409/35597325-e117ce08-05eb-11e8-950f-96caecdba894.png)

Also, the spacing between the two columns at the bottom needs to be fixed.

**Comment by keoshi** [comment]
Styling issue addressed in this PR: https://github.com/Automattic/jetpack/pull/8975

**Comment by rickybanister** [comment]
Yes, we can bump it up to top left. @dereksmart can you make that happen?

**Comment by dereksmart** [comment]
It's possible to do, but would require a hard-coding of all of the widgets' orders so a consequence would be that they could not drag/drop things where they want.

**Comment by rickybanister** [comment]
I don't think that's a viable solution. If we can't insert it into the first position by pre-setting its index or something then we should close this ticket.

**Comment by dereksmart** [comment]
Yeah, unfortunately it's just an array of things that you can either set forcefully, or let it ride.
