### ISSUE TITLE
Add context to welcome splash screen after newly purchased plan

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#8680]
Generic splash screen welcoming me to my plan which is nice, but doesn’t do much to reinforce that I bought this via a prompt for backups. 

A "full" implementation of this would require a lot of param juggling from a lot of different CTA's for a lot of features scattered about jetpack.com, the plugin, and calypso.  BUT, we can still do this in small parts, starting with the most impactful areas, like our JITMs. 

- [ ] JITMs
- [ ] CTA's on the `/plans` page
- [ ] CTA's on the upgrade banners

**Comment by rickybanister** [comment]
I think the checklist work we do for the My Plan page will largely deprecate this splash screen.

**Comment by jeherve** [comment]
Closing this as this now happens in Calypso.
