### ISSUE TITLE
Visited style on dops-button looks weird in green

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#8688]
#### Steps to reproduce the issue
- Try to connect Jetpack in a way that will fail (e.g. from localhost), from the Jetpack dashboard
- Note that when you are returned to the connection screen with an error, the button has black text instead of white

#### What I expected
- button not to look distractingly weird

#### What happened instead
- subtly broken-seeming button

<img width="663" alt="dops-button-visited-weird" src="https://user-images.githubusercontent.com/51896/35639842-4fc56156-0670-11e8-98cf-473fea7a0726.png">

**Comment by jeherve** [comment]
cc @joanrho who worked on some of the changes in #8544

**Comment by joanrho** [comment]
Ah yes, that text should be white, not black.
