### ISSUE TITLE
Jumpstart: remove SEO Tools

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#8693]
Here is the current list of recommended features as of Jetpack 5.8:

![screenshot 2018-01-31 at 21 29 01](https://user-images.githubusercontent.com/426388/35645906-c77aa51e-06cd-11e8-900d-3104866886a9.png)

SEO Tools being a paid feature, I don't think it should be on that list.

**Comment by beaulebens** [comment]
I believe this is properly activating for free users as well, cc @gravityrail
