### ISSUE TITLE
Warm Welcome: add the Search feature

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#8694]
I think it would be nice to add Search to the list of features we promote in Warm Welcome:

![screenshot 2018-01-31 at 21 42 40](https://user-images.githubusercontent.com/426388/35646681-3ab29ada-06d0-11e8-9679-a68462c83467.png)

cc @richardmuscat since you've worked on some readme changes lately.

**Comment by richardmuscat** [comment]
yup

**Comment by Viper007Bond** [comment]
I can take care of this if we get some copy and/or artwork for it.

**Comment by gibrown** [comment]
@Viper007Bond proposed copy changes:

In the first paragraph (https://github.com/Automattic/jetpack/blob/2f970044424dd9d5362086cbc61c0427f5a69b9b/_inc/client/components/welcome-new-plan/professional.jsx#L46), change to:

> Thanks for choosing Jetpack Professional. Jetpack is now backing up your content in real-time, indexing your content for search, scanning for security threats, and granting access to premium themes.

Add an extra paragraph after the themes paragraph (https://github.com/Automattic/jetpack/blob/2f970044424dd9d5362086cbc61c0427f5a69b9b/_inc/client/components/welcome-new-plan/professional.jsx#L51) of:

> Give your visitor's a great search experience by letting them filter and sort fast, relevant search results.

Add a card prompting the user to "Add the Search (Jetpack) widget to your sidebar" in https://github.com/Automattic/jetpack/blob/2f970044424dd9d5362086cbc61c0427f5a69b9b/_inc/client/components/welcome-new-plan/professional.jsx#L89
