### ISSUE TITLE
Admin Page: update links to SEO and GA settings in Calypso

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#8704]
#### Steps to reproduce the issue

1. Go to Jetpack > Settings > Traffic in your dashboard on a site using Jetpack Professional.
2. The SEO configuration link points to https://wordpress.com/settings/seo/yoursite which redirects to https://wordpress.com/settings/traffic/yoursite.
3. The Google Analytics one points to https://wordpress.com/settings/analytics/yoursite which redirects to https://wordpress.com/settings/traffic/yoursite.

![image-2018-01-31-12-47-00](https://user-images.githubusercontent.com/426388/35673342-91396a8e-0741-11e8-8d77-43b330569f0a.png)
![image-2018-01-31-12-47-10](https://user-images.githubusercontent.com/426388/35673343-916a8bf0-0741-11e8-8b62-b6e978a9798a.png)

It would be nice if both links were updated so no redirection has to happen. We could also add an anchor to the links to make sure you are redirected to the right section.

**Comment by tyxla** [comment]
I like the suggestion to add anchors to make linking more precise (the Traffic settings page is pretty huge). https://github.com/Automattic/wp-calypso/pull/23030 takes care of that, and we'll only need to update #8986 accordingly.

**Comment by jaswrks** [comment]
I added the `#seo` and `#analytics` anchors. 👍

**Comment by tyxla** [comment]
#23030 has landed, and IMHO #8986 is ready to go 🚢
