### ISSUE TITLE
Hovercards: Secondary E-mails fail to load hovercard

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#871]
Gravatar hovercards will not load when used for secondary e-mail addresses belonging to a Gravatar account, instead infinite spinner.

Steps to repo:
Set user e-mail address to a secondary e-mail address on a Gravatar account
Visit Settings->Discussion to test the hovercard

Expected: Hovercard is appear.
Actual: Spinner.

When a hovercard appears for the primary address, a file, like this, is returned: http://en.gravatar.com/6e238edcb0664c975ccb9e8e80abb307.json?callback=Gravatar.fetch_profile_callback

When it fails, it appears this isn't requested.

**Comment by kileytoo** [comment]
I totally agree that you don't want to display the name, bio, etc, from your primary email/gravatar (or any other gravatar) when you are using a secondary one. However, I don't see why you are not allowed to set the display name, bio, etc. for all secondary email/gravatar combinations?
