### ISSUE TITLE
Show total number of posts/pages viewed per day

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#872]
A user requested the following:

> I'm looking to know how many DIFFERENT posts are viewed on a given day. 
> 
> I have written 240 posts. So each day I'm curious to know how many of those were viewed. Rather than me counting each title to get a total, I'd love to have that number generated for me and included at the bottom of the list.

1892093-t

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
