### ISSUE TITLE
Warm Welcome: appears twice and causes error

### ISSUE THREAD

**Issue by alisterscott** [Automattic/jetpack#8723]
#### Steps to reproduce the issue

1. Upgrade a site to a higher plan in Calypso
2. Click start exploring your features
3. wp-admin appears with overlay - close overlap
4. Use a link to visit an external page - eg. WordPress.com stats
5. Use back button to return to wp-admin

#### What I expected

Overlay to not appear again as I've already dismissed it

#### What happened instead

Overlay appears again. Closing it creates a red error. See sceen recording attached.

#### Versions

Tested 5.7.1 and 5.8 in Firefox and Chrome

#### Screen recording

![upgrade](https://user-images.githubusercontent.com/128826/35720528-cbd7d34e-0839-11e8-8cc2-205850df3173.gif)

**Comment by alisterscott** [comment]
This bug also appears during the screen recording: https://github.com/Automattic/wp-calypso/issues/22018

**Comment by alisterscott** [comment]
This bug also appears during the screen recording: https://github.com/Automattic/wp-calypso/issues/22034 (I pressed refresh)

**Comment by alisterscott** [comment]
@jeherve I'm not sure what labels to add for this, I couldn't find a `plans` one?

**Comment by jeherve** [comment]
Related: #7837

@alisterscott There is no Plans label yet (I jus added one so we can use it in the future), but "Warm Welcome" (the name of the feature) should do the trick. I added it.

**Comment by designsimply** [comment]
Tested and confirmed using the steps provided. 

I also noticed the following request and response related to the 400 error that shows up when you dismiss the overlay the second time:

> Request URL: https://convenient-cuban.jurassic.ninja/wp-json/jetpack/v4/settings
> Response payload: `{"code":"some_updated","message":"","data":{"status":400}}`

![screen shot 2018-03-08 at thu mar 8 3 25 27 pm](https://user-images.githubusercontent.com/1119271/37180113-18d1fcf4-22e5-11e8-8069-db6123d39275.png)
<sup>Seen at Developer Tools > Network panel for https://convenient-cuban.jurassic.ninja/wp-admin/admin.php?page=jetpack#/dashboard using Firefox 58.0.2 on macOS 10.13.3.</sup>

The error for reference:

> Error updating settings. (Status 400)

![screen shot 2018-03-08 at thu mar 8 3 35 51 pm](https://user-images.githubusercontent.com/1119271/37180483-703d1aea-22e6-11e8-8d19-7b577df7566c.png)
<sup>Seen at https://traditional-titi.jurassic.ninja/wp-admin/admin.php?page=jetpack#/dashboard running WordPress 4.9.4 and Jetpack 5.9 using Firefox 58.0.2 on macOS 10.13.3.</sup>
