### ISSUE TITLE
Personal and Premium plan incorrectly showing Premium themes card

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/jetpack#8730]
When looking at the My Plan page in wp-admin, we are currently showing the Premium themes feature as available to sites on a Personal or Premium plan which is incorrect:

<img width="746" alt="jetpack_ _jetpack_security_ _wordpress" src="https://user-images.githubusercontent.com/2287740/35734242-5850d036-0818-11e8-9aa7-1173032b46ac.png">

<img width="746" alt="jetpack_ _jetpack_security_ _wordpress" src="https://user-images.githubusercontent.com/2287740/35734252-63b3d5e0-0818-11e8-8397-a9aab5c934b1.png">

**Comment by zinigor** [comment]
This is because this block is controlled independently of the current plan setting available from the state. Usually it happens when you switch the plan using the developer toolbar in the footer. A user without premium themes actually enabled will not see this block.
