### ISSUE TITLE
Related posts: "try it out" -action is not noticeable

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#8736]
In *"Related posts"* setting panel (at wp-admin) there's a text: _"You can now also configure related posts in the Customizer. Try it out!"_ —

![image](https://user-images.githubusercontent.com/87168/35740394-51eab048-083d-11e8-9cbe-c2abfefa41ae.png)

That _"Try it out!"_ link to **Customizer** feels rather un-noticeable — it could be something like this instead:

![image](https://user-images.githubusercontent.com/87168/35740406-610212ec-083d-11e8-8360-5af141ec7aa1.png)

In Calypso the link to customizer is missing:

![image](https://user-images.githubusercontent.com/87168/35740871-d981fe66-083e-11e8-97a0-7aaa285346a6.png)

Opened an issue about that, too: https://github.com/Automattic/wp-calypso/issues/22095

**Comment by jeffgolenski** [comment]
@simison 

Can we also change that ancient text that read "use a large and visually striking layout" to something that's more literal? "Display post featured images above titles"

**Comment by zinigor** [comment]
@jeffgolenski great suggestion! You'll be happy to know that this is already fixed in https://github.com/Automattic/jetpack/issues/9568
