### ISSUE TITLE
No way to schedule concierge from wp-admin after closing notification

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#8739]
On wp-admin, if I close this notification:
![image](https://user-images.githubusercontent.com/87168/35742135-3eed12ce-0842-11e8-9bdd-0cd3df32f967.png)

I don't have a way to press that **"Schedule now"** call-to-action anywhere anymore.

It could be at dashboard together with other help-actions:
![image](https://user-images.githubusercontent.com/87168/35742186-5909c800-0842-11e8-8e60-4961e117ed98.png)

At Calypso I can find it from plans page:
![image](https://user-images.githubusercontent.com/87168/35742199-645e0ee6-0842-11e8-975c-f6296ae340ab.png)
`https://wordpress.com/plans/my-plan/:site`

At Calypso I cannot find it via support page: https://wordpress.com/help

On a side note; _concierge_ is rather special term and non-native speakers might have trouble understanding it without reading the description.

**Comment by beaulebens** [comment]
@jamilabreu What's your take on this? Happy to have the "We're here to help" block supplemented with the inclusion of Concierge info for folks who should have access to it? Or is the desire to only have it appear in a way that we can easily control remotely for scheduling/load control (which is the case in the JITM)?

**Comment by jamilabreu** [comment]
@beaulebens Is there a way we can conditionally show the button in the "We're here to help" block?  (i.e. we only show the JITM to customers within 6 weeks after purchase).

> On a side note; concierge is rather special term and non-native speakers might have trouble understanding it without reading the description.

I agree - "Get 1-on-1 help from a Jetpack Concierge" or something along those lines would be a more internationally friendly headline.

**Comment by beaulebens** [comment]
@jamilabreu Yeah I believe we can do that, but it'll be controlled by logic that is shipped in the plugin itself, so whatever we ship with, that version of Jetpack will forever and always follow those rules (vs JITMs which we can change whenever we want).

**Comment by jamilabreu** [comment]
@beaulebens Hmm - adding it sounds good to me, as long as it's ok with the team :)

**Comment by beaulebens** [comment]
OK - I propose we follow the timing that we're using currently in the JITM then, and **for 6 weeks after purchase of an appropriate plan**, we display a message + button as part of the "We're here to help" block.

> Book a complimentary one-on-one consultation with a Jetpack expert
> [Schedule Now]

**Comment by tyxla** [comment]
It seems that right now Jetpack doesn't know the date when the site plan was purchased. Turns out we also don't have an endpoint to obtain that information (in WP.com it's accessible through the `/me/purchases` endpoint). So, before being able to build this message and have it be displayed only during the first 6 weeks after a plan has been purchased, we'll need to work on:

* A JSON API endpoint for purchases
* Redux infrastructure for that endpoint (actions, reducer, selectors)
* Tests for ☝️ 

So I think it's safe to say this task is bigger the HACK week.

**Comment by beaulebens** [comment]
Given the work involved in this, I'm going to close for now. This doesn't seem super high priority or impact right now.
