### ISSUE TITLE
Search: Improve theme look and feel

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#8742]
There are a number of specific themes that don't look very good with search enabled. Opening this issue to track them. (Just edit and add to this list)

- [x] Hemmingway (ugly filtering styling)
- [ ] Storefront (layout in mobile looks terrible, very confusing with the built in search in the theme)
- [ ] 2017 (search results are really ugly)
- [x] Zerif Lite (wide checkboxes)

**Comment by gravityrail** [comment]
Hemingway fixed in https://github.com/Automattic/jetpack/pull/8734

**Comment by Viper007Bond** [comment]
Let's open individual tickets for specific issues now that we've launched.
