### ISSUE TITLE
Jumpstart: Can't dismiss jumpstart modal on mobile phones

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/jetpack#8744]
#### Steps to reproduce the issue

1. On a mobile phone, log in to your site's WP Admin.
2. Install, activate, and connect Jetpack with a Free plan.
3. Complete the connection flow, returning to your site's WP Admin.

#### What I expected

I expected to see the jumpstart modal ("Your Jetpack site is ready to go!") with the option to activate recommended features or dismiss the modal and return to the Jetpack dashboard.

#### What happened instead

I don't see the "x" to dismiss the modal and can't find any other way to dismiss it. The only way to proceed is to activate the recommended features.

#### Screenshot

![2018-02-02 17 43 53](https://user-images.githubusercontent.com/8658164/35747257-868b1226-0841-11e8-822c-9f6e73abc46b.png)

Tested on iPhone 6, Safari, iOS 11.2.5. Also reproduced in Chrome using the dev console's device toolbar to simulate various phone views.

#manual-testing

**Comment by jeherve** [comment]
Related: #8726

**Comment by beaulebens** [comment]
Let's just move the [x] to the top-right corner of the white box, like we did in https://github.com/Automattic/jetpack/pull/8697

**Comment by gravityrail** [comment]
Fixed by #8961

**Comment by brbrr** [comment]
This one seems to be good to close since the fix was already merged and re-tested by Flow Patrol here: https://github.com/Automattic/jetpack/pull/8961#issuecomment-370590260
