### ISSUE TITLE
Ability to connect Jetpack user accounts via wp.com

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#875]
Right now there is no way to add users that are already WordPress.com members to your Jetpack connected site. This feature would be useful if you want to manage your users via WordPress.com

**Comment by zinigor** [comment]
Moving to NCJ milestone to maybe start the ball rolling from dotcom side.

**Comment by lancewillett** [comment]
This came up again recently — added to Calypso task list with https://github.com/Automattic/wp-calypso/issues/11107

**Comment by lancewillett** [comment]
See https://github.com/Automattic/wp-calypso/pull/15357
