### ISSUE TITLE
Admin page: confusing how to close Warm Welcome splash without taking suggested actions

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#8753]
When coming back to wp-admin after purchasing Premium or Pro plans, I see Warm Welcome splash. (Added in https://github.com/Automattic/jetpack/pull/7837)

I choose not to take any of the actions:
![image](https://user-images.githubusercontent.com/87168/35796924-c7030a80-0a66-11e8-9c17-79a9803520ef.png)

Closing this splash isn't very obvious because close-button is quite hidden: 
- it’s small
- it’s far in the corner (esp. on big screen)
- it doesn't have much contrast

![image](https://user-images.githubusercontent.com/87168/35796865-95667dcc-0a66-11e8-84d5-5373ba227168.png)

**Comment by jeherve** [comment]
#8697 should address this issue by making it easier to close. 👍
