### ISSUE TITLE
Jetpack Manage: skip "Jetpack Manage Enabled" confirmation

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#8754]
_"Jetpack Manage Enabled"_ confirmation message feels like an extra step we could skip to make following flow more enjoyable —

I want to adjust security settings, so I go to the tab in Calypso...
![image](https://user-images.githubusercontent.com/87168/35798619-fbfbc5e2-0a6b-11e8-89fe-172e9fbaa8d5.png)

Yes...
![image](https://user-images.githubusercontent.com/87168/35798613-f5c8d200-0a6b-11e8-9447-0e22dda5fabc.png)

Confirmation @ wp-admin...
![image](https://user-images.githubusercontent.com/87168/35798636-1192c662-0a6c-11e8-9952-fc675143d677.png)

Confirmation confirmed @ wp-admin...
![image](https://user-images.githubusercontent.com/87168/35798707-49085152-0a6c-11e8-8a1f-ea4968bd419e.png)

...only then:
![image](https://user-images.githubusercontent.com/87168/35798730-56f66100-0a6c-11e8-93ac-319be231402f.png)

- Could be the message could be less repetitive?
- Could be there's a way to take at least last confirmation away? Since we started at Calypso, we could just redirect to Calypso at this point.
- Even better if we can remotely activate this without ever leaving Calypso.
Maybe we could just toggle that module on remotely, even without questions?
- As a DIY customer I'm missing a "more info"-balloon at first step that would explain to me what is going to happen and why I have to do this.

**Comment by jeherve** [comment]
👍  #7114 should tackle that. 

> Maybe we could just toggle that module on remotely, even without questions?

That's the idea, yes. That's also what we do for most users today.

**Comment by dereksmart** [comment]
@simison I'm curious how you *manage*d to get that flow ;) 

Manage is basically hard-coded as an automatic activated module for new sites and sites that have updated from older versions.  Was it for a brand new site? Or a site that had filtered manage out?

**Comment by MichaelArestad** [comment]
This seems like a few issues combined, but at the root, I think skipping the success screen makes a ton of sense.

Let's try:
* Removing the confirmation screen
* Replacing the confirmation screen with a global notice: "Jetpack Manage is now enabled"
* Change the view to load the view the user was originally trying to access

**Comment by dereksmart** [comment]
> Making activation work from Calypso if possible

Can't remotely enable manage without manage enabled!
