### ISSUE TITLE
Likes: two like toggles

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#8755]
At Jetpack settings I can see "Sharing" and "Like" toggles:

![like-and-sharing](https://user-images.githubusercontent.com/87168/35799417-4e4b1954-0a6e-11e8-8084-5a3b94398fbc.png)

When I configure sharing buttons, I can see another like-toggle (in Calypso):

![sharing](https://user-images.githubusercontent.com/87168/35799448-65c03f56-0a6e-11e8-8fdc-c00e353322ae.png)

Toggling the like-toggle in Jetpack and like-toggle in Calypso don't seem to be connected. I can toggle these on/off independently. 

In Calypso, I don't see that original "like buttons"-toggle anywhere.

**Comment by simison** [comment]
Related: https://github.com/Automattic/wp-calypso/issues/11023 _"Move sharing settings into settings"_

**Comment by beaulebens** [comment]
Technically that "Show like button" checkbox should be a toggle these days as well.

Just to clarify @simison -- were you refreshing the pages between toggling, and/or waiting any amount of time? I'm wondering if there truly is some disconnect, or if it's more specifically a case of a delay between data/caching in each UI.

**Comment by keoshi** [comment]
The like toggle appears to be synced between Jetpack and Calypso for me, but it takes a bit to update (and probably a page refresh).

**Comment by simison** [comment]
Confirming that now that I tested both like-buttons seem to be synced — this was a while back so I can't tell what exactly happened when I was testing. I might've had several tabs open mixing things up.

At any rate, this is either UI issue (checkbox should be a toggle) or UX issue (the same switch is double in two different places).

**Comment by oskosk** [comment]
Couldn't reproduce @simison. Should we close this one ?

**Comment by simison** [comment]
Closing: I double tested now again and toggles are indeed synced.

My initial problem seemed to be that checkbox at Calypso has default setting `[x]` before the actual state even loads, so if I have it disabled in Jetpack and Calypso is still loading data, it seems like it’s _on_ in Calypso and _off_ in Jetpack.

Then when the data arrives, checkbox goes `[ ]`. Seems like a problem on slow internets.

Additionally:
- The setting is double in two different places from Jetpack point of view.
- Like button is an old-school checkbox, not a toggle like all other such switches in Calypso.
