### ISSUE TITLE
Disconnect Jetpack from wp.com, shows up as connected at wp-admin

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#8757]
- I connected a self-hosted WP-network site with Jetpack to wp.com on a free plan.
- I disconnected Jetpack from Calypso
- I go to Jetpack dashboard and see this:
    ![image](https://user-images.githubusercontent.com/87168/35802755-fe54ee46-0a79-11e8-9641-ea6a8d73ca1e.png)
- I press Manage and disconnect, end up to this state:
    ![image](https://user-images.githubusercontent.com/87168/35802771-0de4f39c-0a7a-11e8-9b08-887f6e0391fc.png)
- I repeat the same, page refreshes, Jetpack seems now disconnected but I get:
    ![image](https://user-images.githubusercontent.com/87168/35802784-1c578124-0a7a-11e8-8576-000eafc0a3ea.png)
- By pressing "Connect" now again, I get white page with:
    ```
    Invalid request, please go back and try again.
    Error Code: invalid_client
    Error Message: Unknown client_id.
    ```
    ... in the URL `https://jetpack.wordpress.com/jetpack.authorize/1/?response_type=code&client_id=....`

**Comment by jeherve** [comment]
> I disconnected Jetpack from Calypso

Could you walk us through the steps you followed to disconnect the site there?

**Comment by simison** [comment]
>Could you walk us through the steps you followed to disconnect the site there?

Hmm, good question. I wasn't really paying attention because I wasn't looking for bugs while getting familiar with flows.

I tested quickly again but couldn't reproduce. I'll try again a bit later. :-)
