### ISSUE TITLE
Connect Jetpack button: confusing without WordPress.com account

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#8759]
![image](https://user-images.githubusercontent.com/87168/35803366-42d62592-0a7c-11e8-9c5c-dd775aa83d09.png)

The connection button itself doesn't really tell I need a WordPress.com account at this point.

By reading text above the button customer will understand they will need an account which they can create in the next step:

> Please connect to or create a WordPress.com account to start using Jetpack. This will enable powerful security, traffic, and customization services.

It would be better to indicate this already in the button itself.

However, in the next step I see this:

![image](https://user-images.githubusercontent.com/87168/35803456-91433d50-0a7c-11e8-8e3a-15c58e33b6c0.png)

I cannot create a new account here.

Even if I thought this is now the way to create a new user, I just end up seeing a warning:

![image](https://user-images.githubusercontent.com/87168/35803580-f558019a-0a7c-11e8-8c83-ec5d35c93900.png)

The only way I can navigate this flow is to read and understand I need to press this link under the button:

>No account? Create one for free

## Improvement ideas
- Add "Create new account" to login screen
- Add "Create new account" link to "user does not exist" error
- Make "No account / create one" -link much more visible (a button?)

**Comment by jeherve** [comment]
Noting that the flow is different when your site's admin email address matches an existing WordPress.com account (that's the case above).

If your admin email address was not linked to any WordPress.com account, you would be offered the option to create a new account. 

Related discussion: p1HpG7-4P7-p2

This flow should be improved by https://github.com/Automattic/wp-calypso/pull/21901

**Comment by oskosk** [comment]
The new dialog looks like this. Does not say "connect" in the button anymore:

![image](https://user-images.githubusercontent.com/746152/35976087-bd505db8-0cbd-11e8-8db9-f1063580afb3.png)

This is how the following Calypso screen looks for an user of the site that has an email not associated with a .com site

![image](https://user-images.githubusercontent.com/746152/35976385-b3e82c50-0cbe-11e8-9cfe-3c64ea935225.png)

I'm closing the issue now as:

1. The "set up Jetpack" looks less confusing in this regard.
2. The login screen proposald could be reported to the Calypso repo. 

Thank you!

**Comment by oskosk** [comment]
Forgot to say that you can reopen if you still think is confusing enough for users. I do have second thoughts about the lack of sign up button. but it was there before and it removed for some reason maybe.

**Comment by simison** [comment]
Thanks @oskosk -- I believe @johnHackworth has todos regarding Calypso side of things triaged already somewhere. 👍

**Comment by oskosk** [comment]
niceee!
