### ISSUE TITLE
Search: Implicitly activate search when widget added

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#8763]
Rather than forcing the user to activate search and then go to the widget section to add it to the sidebar, let's:
1. Load enough code to always show the widget as long as they are on a JP Pro plan
2. Activate the search module when the user adds the widget to the sidebar

The downside is how to handle cases where the user then removes the widget. In those cases the module will still be on, and the user may not know where to deactivate it.

**Comment by Viper007Bond** [comment]
> The downside is how to handle cases where the user then removes the widget. In those cases the module will still be on, and the user may not know where to deactivate it.

I think that's fine. Some people may want to remove the widget without disabling our search. I mean, the whole idea is that our search is always going to be better, right? At least ideally.
