### ISSUE TITLE
Search: Emoji searches do not return results

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#8765]
### Steps to reproduce:

1.First ensure the “Jetpack (Search)” widget settings have Posts, Pages, and Media checked for “Post types to search.”
2. Create and publish a post with 🌯 in the title.
3. Go to the home page and search for “🌯” using the “Jetpack (Search)” widget.

**Comment by gibrown** [comment]
Just noting that this requires better Elasticsearch analyzers that can handle properly tokenizing handle emoji. Right now they all strip the emoji.

It looks like ES 6.0 has finally upgraded the ICU analyzer: https://github.com/elastic/elasticsearch/issues/21425

I think ICU (which we use) probably has better emoji support, but haven't tested it. Also, we would need to upgrade to ES 6.0.

**Comment by gibrown** [comment]
https://github.com/jolicode/emoji-search would probably be the best solution.

**Comment by muffinpeace** [comment]
Reviving this as it looks like we have a user who needs this feature with Jetpack Search, as WordPress was initially handling it before.

4017603-zen

**Comment by robfelty** [comment]
I am happy to report that emoji search now works! Here's an example from whatemoji.org
<img width="1160" alt="Bildschirmfoto 2022-03-25 um 15 34 36" src="https://user-images.githubusercontent.com/19924/160189597-a1adcfdd-2e95-485f-b4b3-1548e59b3303.png">

I think we can probably finally close this ticket.

**Comment by gibrown** [comment]
Woohoo! Closing.
