### ISSUE TITLE
Backups and security settings not showing up

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#8768]
When attempting to test on SiteGround, I went through the old setup flow. Vaultpress was installed magically, but when I went to security settings withing Jetpack, the backups and security card was missing.

Note: I was not on the Jetpack beta yet.

Ideas?

**Comment by dereksmart** [comment]
@MichaelArestad you may have caught it at an awkward time when the Rewind API was made "available" to a12s while the logic in the plugin was meant to hide that card if that were true.  

It should not be hidden now, instead you should expect to see it as normal until Rewind is "active" then we show custom stuff.  aka never hidden

**Comment by dereksmart** [comment]
Please reopen if you can reproduce this
