### ISSUE TITLE
Activity Log JITM should not open in a new tab

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#8769]
Currently, when clicking on the JITM, it opens in a new tab. Can we change that behavior to not open in a new tab?

**Comment by beaulebens** [comment]
@MichaelArestad can you remember exactly which message/where this was shown when you encountered this, just to make sure we're getting the right one?

**Comment by beaulebens** [comment]
cc @withinboredom

**Comment by MichaelArestad** [comment]
I believe it was the one that says "Switch now" or, if you're in master, "Set up" (I think)
