### ISSUE TITLE
Activity Log - Change verbiage of JITM button

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#8771]
Currently, it looks like this:

![image](https://user-images.githubusercontent.com/1123119/35863814-155b6fe6-0b0d-11e8-8eb9-82d9a5eeb032.png)

Let's change it to "Try it out". Since this is a one-way flow, we'll want to update the language in the flows @eliorivero built to make sure this is clear.

**Comment by joanrho** [comment]
How about "Get started"?

**Comment by roccotripaldi** [comment]
I like "Get Started"

**Comment by eliorivero** [comment]
Committed in r176490-wpcom.
