### ISSUE TITLE
Activity log: plugin updates from CLI appear without name

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#8774]
When updating or installing plugins via the filesystem, they appear in Activity log with Mystery Gravatar:

![image](https://user-images.githubusercontent.com/87168/35875277-671485c4-0b77-11e8-8af9-01fc535ff460.png)

### Just throwing in some ideas —

These could include just gray "system" text?

![image](https://user-images.githubusercontent.com/87168/35876033-c17b39d4-0b79-11e8-8676-1e6ee0394551.png)

Instead of Gravatar, there could be "cli" or "server rack" icon?

![image](https://user-images.githubusercontent.com/87168/35876093-e9b71904-0b79-11e8-8a52-1eb759ff885b.png)

**Comment by roccotripaldi** [comment]
We should add a new property to activities for "is_cli"

Look for constant "WP_CLI"

**Comment by roccotripaldi** [comment]
@keoshi - does this seem like a reasonable solution?

**Comment by keoshi** [comment]
I'm worried that there isn't a standardized visual representation for these, and the icon we end up picking might lead to confusion.

Similar to https://github.com/Automattic/jetpack/issues/9507, I'd probably append “via filesystem” (or something descriptive like that) to the description and use the Jetpack actor here.

**Comment by simison** [comment]
If we can recognise plugin was specifically managed via [CLI tool](https://developer.wordpress.org/cli/commands/plugin/), we should probably indicate that in the description? "via filesystem" is fuzzier.

- Jetpack as an actor
- Description: _"Plugin updated via WP-CLI"_

**Comment by keoshi** [comment]
Oh, if we can that would be perfect! Agree on all these ^^

**Comment by gititon** [comment]
This has been merged 

<img width="1194" alt="screen shot 2018-07-24 at 2 14 19 pm" src="https://user-images.githubusercontent.com/3246867/43157781-faff8056-8f4b-11e8-948a-f2332fbcffd6.png">
