### ISSUE TITLE
'jetpack_get_available_modules' Filter Shows 'undefined' Setting for Lazy Loading

### ISSUE THREAD

**Issue by clreed87** [Automattic/jetpack#8778]
#### Steps to reproduce the issue
1. Exclude lazy loading via 'jetpack_get_available_modules' filter
2. 'undefined' setting will display in reading section

![screenshot 2018-02-07 00 10 28](https://user-images.githubusercontent.com/3621730/35901312-a1bc7cda-0b9b-11e8-9b29-2e7248ebc031.png)

#### What I expected
No lazy load option should be displayed

#### What happened instead
'Undefined' setting appeared

**Comment by mrjarbenne** [comment]
This issue extends beyond Lazy Load. It also occurs if you omit Photon: 

![2018-02-07_23-55-44](https://user-images.githubusercontent.com/480667/35956256-7dab2a90-0c62-11e8-8d0e-8acf71360b2c.png)

**Comment by jeherve** [comment]
Related: #8800
