### ISSUE TITLE
Admin Page: Disable/hide setting when module is forced on/off

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#8800]
It is currently possible to force a module to be enabled, or disabled, via the [jetpack_active_modules](https://developer.jetpack.com/hooks/jetpack_active_modules/) filter. Here's an example of using that filter to force the Photon module on:

```php
add_filter( 'option_jetpack_active_modules', 'jetpack_docs_filter_active_modules' );
function jetpack_docs_filter_active_modules( $modules ) {
	return array_values( array_merge( $modules, array( 'photon' ) ) );
}
```

However, while that filter does force the module on, the UI is not aware that the Photon module is forced on. Because of this, I am able to deactivate Photon in the admin UI. But, when I refresh the page, the module is still active.

We should find some way to manage the UI when modules are forced on. It seems like we should either 1) disable the setting in the UI with a message that it is forced to active or 2) just hide the setting like we do when the module is filtered with the [jetpack_get_available_modules filter](https://developer.jetpack.com/hooks/jetpack_get_available_modules/).

**Comment by oskosk** [comment]
Indeed, I encountered a similar problem when working on [Admin Page: Hide Masterbar toggle for Atomic Sites](https://github.com/Automattic/jetpack/pull/8290). Ended up filtering by a custom check about Atomic sites, but there could be something better
