### ISSUE TITLE
Comment says delete this, should it be deleted?

### ISSUE THREAD

**Issue by withinboredom** [Automattic/jetpack#8809]
Discovered during GDPR Audit

https://github.com/Automattic/jetpack/blob/d951c9d42b1b1ab2bace4bfab2ee5a384b738366/modules/custom-css.php#L26

Should we delete this block of code?

**Comment by jeherve** [comment]
cc @georgestephanis who worked on this in #5804.

**Comment by jeherve** [comment]
This was deleted eventually. 👍
