### ISSUE TITLE
'jetpack_get_available_modules' Filter Shows 'undefined' Setting for Photon

### ISSUE THREAD

**Issue by mrjarbenne** [Automattic/jetpack#8810]
I'm creating a separate ticket for this issue (as I should have done initially rather than tagging onto the bottom of this: https://github.com/Automattic/jetpack/issues/8778). The issue was also affecting Lazy Load images prior to this commit: https://github.com/Automattic/jetpack/pull/8780 but is still affecting Photon as seen in the image below: 

![2018-02-07_23-55-44](https://user-images.githubusercontent.com/480667/36065511-ea1676ae-0e69-11e8-8bcb-d80b7c25dbb1.png)

Jetpack Version 5.8

**Comment by jeherve** [comment]
To clarify, you are still experiencing an issue when using the current version of `master`, that includes the changes from #8780?

**Comment by jeherve** [comment]
Related: #8800

**Comment by mrjarbenne** [comment]
Just checked again with the latest master, and with the changes from #8780 the Photon settings are properly hidden. Sorry about the additional issue. Cheers.
