### ISSUE TITLE
Load Twitter widget using https instead of http:

### ISSUE THREAD

**Issue by garikaib** [Automattic/jetpack#8816]
Would it be possible to change the line:
/jetpack/modules/shortcodes/tweet.php:140 from:
`wp_register_script( 'twitter-widgets', set_url_scheme( 'http://platform.twitter.com/widgets.js' ), array(), JETPACK__VERSION, true );`
To use https:
`wp_register_script( 'twitter-widgets', set_url_scheme( 'https://platform.twitter.com/widgets.js' ), array(), JETPACK__VERSION, true );`

This is my first contribution so I apologise if I am breaking any

**Comment by jeherve** [comment]
That sounds like a good idea. You could actually remove the whole `set_url_scheme` check and always load the file via HTTPS. 

```php
wp_register_script( 'twitter-widgets', 'https://platform.twitter.com/widgets.js', array(), JETPACK__VERSION, true );
```

Would you like to [create a Pull Request](https://github.com/Automattic/jetpack/blob/master/docs/pull-request.md) with that change?
