### ISSUE TITLE
Confirm all files check for WP

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#8818]
I ran into a ticket in support where something had crawled every file and attempted to execute each PHP file. This resulted in a ton of fatal errors (the construct class of Jetpack_Admin uses the Jetpack class without checking, for example).

We could resolve this by a simple ABSPATH-> exit check at the top of PHP files to prevent direct execution.

**Comment by jeherve** [comment]
Closing as duplicate of #3056
