### ISSUE TITLE
Lazy Images: Prevents Embedded Tweets from Displaying Properly In Safari

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/jetpack#8821]
#### Steps to reproduce the issue
1. Activate Lazy Load.
2. Embed a tweet in a new post.
3. Load the post in Chrome. Tweet will appear fine.
4. Load the post in Safari. Tweet will only appear as text. 
5. Disable Lazy Load. Tweets load fine.  

Reported in 955457-zen

**Comment by ebinnion** [comment]
I've looked into this a bit, and it appears the issue is our IntersectionObsever polyfill. As soon as I comment that out, the embeds work. I'll look into this some more.
