### ISSUE TITLE
Content Options: Featured Images setting affect WooCommerce products

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/jetpack#8835]
If you uncheck "Display on blog and archives" under Content Options > Featured Images, it affects both the blog and shop.

#### Steps to reproduce the issue

1. Starting with a site with both WooCommerce products set up, and using a theme that supports content options
2. Under Content Options > Featured Images, uncheck "Display on blog and archives"

#### What I expected

That it will affect the blog posts only.

#### What happened instead

The setting also affects the shop pages generated by WooCommerce. They are technically archive pages, but it seems unexpected.

Originally reported as a theme issue here: 4888-wpcom-themes

User's report: 776624-zen

**Comment by kathrynwp** [comment]
Also reported by a user in 2206-wpcom-premium-themes

**Comment by sixhours** [comment]
Also reported in Automattic/jetpack#31 . User info for follow-up:

* User report: #1957041-hc
* Follow-up ticket: #999474-zd
