### ISSUE TITLE
Subscriptions: shortcode stripped from email

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/jetpack#8859]
Install the TablePress plugin (https://en-gb.wordpress.org/plugins/tablepress/#installation) and create a new post with a table using the TablePress shortcode. 

I expected the shortcode to appear in the subscription email as plain text (as per https://jetpack.com/support/subscriptions/) but instead it was completely removed. There was no table and no shortcode in the email.

Reported in #956349-zen

**Comment by jeherve** [comment]
That's the expected behaviour. We remove the `table` shortcodes from the post content that is sent via email, and only display the tables' contents.

If we wanted to support the TablePress format in subscription emails we would have to sync a lot more data about the content rendered by that plugin.
