### ISSUE TITLE
Related Posts appears above article pagination

### ISSUE THREAD

**Issue by johnkawakami** [Automattic/jetpack#8871]
#### Steps to reproduce the issue

This applies to twentyfifteen. Use the &lt;!--nextpage--> tag within an article, and the article pagination appears.

However, it looks weird, because the Related Posts display above the pagination.

#### What I expected

I expected the Related Posts to be below the pagination.

#### What happened instead

![screenshot from 2018-02-18 01-13-40](https://user-images.githubusercontent.com/321307/36350320-73248788-144b-11e8-8112-7965f381c9e3.png)

#### Suggested change

Instead of using the_content filter, use wp_link_pages.

Old code in jetpack-related-posts.php:

                add_filter( 'the_content', array( $this, 'filter_add_target_to_dom' ), 40 );

New code:

                add_filter( 'wp_link_pages', array( $this, 'filter_add_target_to_dom' ), 40 );

![screenshot from 2018-02-18 01-33-45](https://user-images.githubusercontent.com/321307/36350341-d98394c4-144b-11e8-8d8c-8335cfae343a.png)

I don't know the implications of this change.  It seems to work on both the paginated and single-page articles, in the twentyfifteen theme.

**Comment by johnkawakami** [comment]
The software was updated, and the pagination has moved to beneath the related posts, again.

**Comment by jeherve** [comment]
This is a common issue on WordPress, it will happen with all plugins that hook data (like related posts) to the post content. Luckily, there is a work-around so your pagination links can appear higher on the page. I detailed the work-around in this forum thread:
https://wordpress.org/support/topic/page-numbers-above-share-this/#post-6999162

I hope this helps. Unfortunately that is not something we can change in Jetpack itself. I'll consequently close this issue.
