### ISSUE TITLE
Send to Email Sharing pop-up is not responsive

### ISSUE THREAD

**Issue by boboz** [Automattic/jetpack#8872]
#### Steps to reproduce the issue
Jetpack 5.8
Place an email sharing icon after for example two other sharing icons. View on a small screen .

#### What I expected
Responsive behaviour of the send to email sharing pop-up

#### What happened instead
No responsive behaviour of the send to email sharing pop-up. See image below.

![email-sharing2](https://user-images.githubusercontent.com/141707/36355093-0da2fb36-14de-11e8-94f1-0397ad0cdc8a.PNG)

**Comment by jeherve** [comment]
Closing as duplicate of #6617
