### ISSUE TITLE
Lazy Images: Breaks outdenting of big images in compatible themes

### ISSUE THREAD

**Issue by PatTheMav** [Automattic/jetpack#8879]
#### Steps to reproduce the issue

* Activate Lazy Images
* Activate any theme that outdents images via JavaScript (e.g. Independent-Publisher-2 or TwentySixteen)
* Watch posts with big images within the article (> 1100px width)

#### What I expected

Images should be "outdented", breaking out of the page width as the overall viewport is big enough to support this.

#### What happened instead
Images are not "outdented", stay within given article width.

### Additional Notes

The reason for this is that most themes only outdent once at the `load` or `ready` event and even then only look at the image width given by the DOM API.

I was able to fix this by creating a child theme of independent-publisher-2, adding a `lazyOutdent` method that was called by every lazy loaded image's `load` event handler (this also enabled me to add CSS transitions), but this might have the side effect of being called on any `load` and not just the one triggered by the lazy load - a JS hook might fix that.

Also using the `naturalWidth` (or - as a fallback - `offsetWidth`) DOM attribute was necessary to get the correct sizes of an image as supplied by `srcset` attributes to detect if an image will actually be big enough to be outdented after the browser selected the most appropriate one from the source set (`width` reports wrong values in that case).

---

**PS**: You might also want to look at this lazy loading technique which makes the use of `<noscript>` tags redundant by using an empty image for the `srcset` attribute, yet keeping the `src` intact for old browsers and making this solution better for sharing widgets. Also uses a data URL instead of an actual 1x1 pixel GIF to reduce HTTP overhead: https://github.com/ivopetkov/responsively-lazy

**Comment by jeherve** [comment]
cc @ebinnion

**Comment by PatTheMav** [comment]
Quick update: I've observed that Jetpack's lazy-load plugin triggers multiple downloads of the same image, probably due to setting `src` as well as updating `srcset`. Observing the network activity I believe the following to happen:

1. `src` is set, browser downloads image
2. `srcset` is set, browser re-evaluates current sizes/pixel density, downloads image again
3. `sizes` is set, browser re-evaluates `srcset`, image is downloaded a 3rd time

In a best-case scenario the image requests are fulfilled by the browser cache, but I don't know if the same is true if the first request hasn't finished yet. Depending on race conditions we might end up with downloading the image twice.

**Note**: I haven't observed this behavior with the `responsively-lazy` paradigm, as it leaves the `src` element untouched and only updates the `srcset` (modern browsers won't load the `src` when `srcset` is set to an "empty" data URL).

**Comment by alisterscott** [comment]
I discovered this dogfooding today, it confused me as in the Calypso editor preview it was showing them as extra wide but upon publish they were smaller.
