### ISSUE TITLE
Invite Follower: dead end flow for inviting a follower

### ISSUE THREAD

**Issue by drw158** [Automattic/jetpack#8880]
I think this is a dead end. I noticed how on wpcom we show an Add button on the Followers tab, but for a Jetpack site we hide it:

Jetpack site:
![screen shot 2018-02-19 at 3 38 29 pm](https://user-images.githubusercontent.com/618551/36398095-098efb3c-158b-11e8-97f9-5af56cef29af.png)

wpcom site:
![screen shot 2018-02-19 at 3 38 39 pm](https://user-images.githubusercontent.com/618551/36398097-0c06dd3a-158b-11e8-8521-25f726d8ebe3.png)

But, you can still invite a follower on a Jetpack site by:

#### Steps to reproduce the issue

1. start at https://wordpress.com/people/team
2. pick a Jetpack site
3. click the invite user button
4. input a throw away email address
5. make sure dropdown says "Follower"
6. Send invite
7. check inbox of throw away email
8. accept invite by copying the link and pasting in an incognito window
9. create an account using the steps shown on screen
10. click "Sign Up & Follow"
11. Message says click the link in the email to activate 
12. go to inbox of the throw away email
13. Click on the new email — it should say "Log in to WordPress.com"
14. try to login, and it says that the account is not activated

#### What I expected

Able to login with the credentials I created.

#### What happened instead

I could not log in.

Here are all of the screenshots, of the steps above in reverse chronological order:

 
![screen shot 2018-02-19 at 3 33 57 pm](https://user-images.githubusercontent.com/618551/36398350-4d98c96a-158c-11e8-87f8-9bccdcce7c54.png)
![screen shot 2018-02-19 at 3 32 57 pm](https://user-images.githubusercontent.com/618551/36398351-4da5d66e-158c-11e8-8f2f-2f5352eeeb8d.png)
![screen shot 2018-02-19 at 3 32 45 pm](https://user-images.githubusercontent.com/618551/36398352-4db347d6-158c-11e8-93b5-6d790343ed1f.png)
![screen shot 2018-02-19 at 3 32 37 pm](https://user-images.githubusercontent.com/618551/36398353-4dc12608-158c-11e8-860c-d06b4be8c7f3.png)
![screen shot 2018-02-19 at 3 32 04 pm](https://user-images.githubusercontent.com/618551/36398354-4dce3276-158c-11e8-8712-1bfae8ebf457.png)
![screen shot 2018-02-19 at 3 31 41 pm](https://user-images.githubusercontent.com/618551/36398355-4ddc2a70-158c-11e8-90af-9c42dd22b8aa.png)

**Comment by jeherve** [comment]
> it says that the account is not activated

That seems to be the crux of the issue here, right?

This may be something that we need to log on the Calypso side of things, since that's where this lives. What do you think?

**Comment by drw158** [comment]
Whoops! You're right. I assumed it was a Jetpack issue, but it affects wpcom sites as well. Moved https://github.com/Automattic/wp-calypso/issues/22619
