### ISSUE TITLE
JP Logo: Incorrect on Calendly

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/jetpack#8896]
#### Steps to reproduce the issue
1. Click a CTA for scheduling a concierge session
2. Takes you to a url like: https://calendly.com/jetpack/concierge/02-22-2018

#### What happened instead
1. Logo is incorrect

<img width="416" alt="calendly_-_jetpack_by_wordpress_com" src="https://user-images.githubusercontent.com/2287740/36535315-1f15e230-17c1-11e8-8320-631b697bfda4.png">

**Comment by jeherve** [comment]
Is that not the new logo on that screenshot? I'm confused.

@jamilabreu Do you have access to change such settings in Calendly?

**Comment by jamilabreu** [comment]
@jeherve @richardmuscat  I do have access - where can I find the right one?

**Comment by richardmuscat** [comment]
@jeherve -- the icon is correct but the text isn't. Should simply be like this:

<img width="216" alt="recommended_wordpress_and_jetpack_hosting providers_ _jetpack_for_wordpress" src="https://user-images.githubusercontent.com/2287740/36600415-1a0b6172-18aa-11e8-862f-3335f878cd25.png">

**Comment by kraftbj** [comment]
The text isn't an image; it's the title of the group within the scheduling system. We can change the image, but would still have the title text (of some variety) under it.

**Comment by richardmuscat** [comment]
Got it. Can you not have text at all? Or else make the text something like "Concierge Appointments" ?

**Comment by jamilabreu** [comment]
I updated the text to "Schedule a 1-on-1 Concierge Appointment", but they only allow a square image (logo with "Jetpack" text doesn't fit).

Does that look better?

**Comment by jeherve** [comment]
<img width="453" alt="screenshot 2018-02-23 at 17 43 17" src="https://user-images.githubusercontent.com/426388/36605460-1399c24a-18c1-11e8-9951-3f45d7aac4f9.png">

**Comment by beaulebens** [comment]
This fix will work for now -- thanks @jamilabreu !

**Comment by richardmuscat** [comment]
Love it! Good thinking.
