### ISSUE TITLE
Activate Jetpack splash screen copy

### ISSUE THREAD

**Issue by johnHackworth** [Automattic/jetpack#8900]
When you activate Jetpack, we are showing you this modal full-screen:

![image](https://user-images.githubusercontent.com/1554855/36541774-4a3ae410-17df-11e8-83d0-e00d53251be7.png)

I think the text is not explicit enough: it looks like connecting Jetpack will make it work better, or add extra capabilities: We are doing a pretty poor job communicating that the connection is required for Jetpack to even work. I think we should change the copy on that modal window to make this more clear.

@rickybanister ^

**Comment by beaulebens** [comment]
I believe @joanrho has some alternate designs for this entire page which leverage the new jetpack.com design, so we should probably just update it all at once.

**Comment by joanrho** [comment]
Please see p6TEKc-1P8 for the new layouts.

**Comment by rickybanister** [comment]
Thanks @joanrho!

Yup, this was already on your plate to update @johnHackworth

**Comment by joanrho** [comment]
Hey @johnHackworth! Here are the mockups for both the Plugin directory view (dismissable full-screen banner) and Jetpack Dashboard view (just a full-screen page, non-dismissable)

Plugin Directory:
![01 plugin directory dismissable banner](https://user-images.githubusercontent.com/204742/37625913-817cacd4-2b93-11e8-8747-16516419d7a8.png)

Jetpack Dashboard:
![02 jetpack dashboard full screen page](https://user-images.githubusercontent.com/204742/37625914-818ff73a-2b93-11e8-97dc-51eb75f7be75.png)

Will add the four illustration assets for you to use in a separate PR right now.
