### ISSUE TITLE
Lazy load for background images

### ISSUE THREAD

**Issue by lenineto** [Automattic/jetpack#8905]
#### Steps to reproduce the issue
Just insert any image as a background for a section of the page. Any themes using image parallax will do this and pretty much any page created with WP Bakery (formerly Visual Composer) can easily add an image parallax to any row.

I see the preg_match_all function on Jetpack code is searching for
`<img src="https://domain.com/url/to/image.png>`

Problem is when you set an image as the background the code will look like this:

```
<section id=”section1″ data-overlay=”5″ data-vc-parallax-image=”https://image.url”> ::before
<div class=”background-image-holder” style=”transform: translate3d(0px, -1262.31px, 0px); background: url(“https://image.url”); opacity: 1;”>
```

Notice how the image is now loaded thru the "background:url" property. 
Jetpack won't act on those images.

#### What I expected
To have all images lazy loaded, including the ones set as layer backgrounds.

#### What happened instead
Jetpack doesn't find those images and therefore no lazy loading happens for them, which negatively impacts page performance, specially in Google Lighthouse. 

#### Why have this feature added
Most modern themes use image parallax effects, which is a really nice effect, and lazy loading those images is a must in terms of performance. 

Thanks!

**Comment by jeherve** [comment]
cc @ebinnion

**Comment by markman641** [comment]
I am having this same issue. Is there a workaround to get background images lazy loaded?
@jeherve @ebinnion

**Comment by locvfx** [comment]
I'm having the same issue. Please update or any quick fix solution
Thanks

**Comment by locvfx** [comment]
I found a quick fix to disable the lazy load behavior on a specific image, just add class="skip-lazy".
The full article can be found here: 
https://jetpack.com/support/lazy-images/

**Comment by karan4official** [comment]
I am also struggling with this issue, let me know if anyone got it fixed

**Comment by drseo** [comment]
Same here.

**Comment by rsamborski** [comment]
One more vote on this fix or a workaround please.

**Comment by mahnunchik** [comment]
It would be nice to have lazy load for background images in Jatpack.

**Comment by AlexWebLab** [comment]
It would be great!
