### ISSUE TITLE
Plugin directory information mentions Elasticsearch

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#8906]
That's probably a bit of a stretch of relevance for our listing.

Suggest a re-wording based on some of our more popular/broadly-applicable keywords and features.

**Comment by jeherve** [comment]
Some related discussion in #8442

**Comment by gibrown** [comment]
And in #8708

**Comment by richardmuscat** [comment]
@beaulebens -- the only mentions I can see are:

- The strapline
- Under the Marketing Services heading there is a bullet point saying "Elasticsearch-powered related content and site search"

I think we can keep the second and I updated the strapline (needs review) in this PR: https://github.com/Automattic/jetpack/pull/8999

**Comment by beaulebens** [comment]
@richardmuscat oops, sorry, yeah I should have been more specific in the original issue. The mention in the strapline was indeed the one I was referring to.
