### ISSUE TITLE
Plugin Directory Info: Update screenshots

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#8907]
We should refresh and update the screenshots which get displayed in the plugin directory.

At the very least, the logo needs to be updated on them.

**Comment by jeherve** [comment]
Somewhat related, while we are at it: #3055

**Comment by rickybanister** [comment]
@jeffgolenski could you take a look at getting these updated? You're my screenshot king.

**Comment by jeffgolenski** [comment]
On it. Apologies for the delay.

**Comment by oskosk** [comment]
will do @jeffgolenski!

**Comment by oskosk** [comment]
Closing as they're updated now in sync with the Release of Jetpack 6.1.1
