### ISSUE TITLE
JITMS: not displayed in post editor with Gutenberg

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/jetpack#8916]
#### Steps to reproduce the issue
1. Fresh JP installation and purchase a Premium plan
2. Install Gutenberg plugin
3. Visit new post page: https://{site-url}/wp-admin/post-new.php
4. See the JITM for scheduling a concierge session

#### What I expected
To see the JITM

#### What happened instead

<img width="1177" alt="new_post___add_a_new_post_ _richard_s_sandbox_ _wordpress" src="https://user-images.githubusercontent.com/2287740/36589867-ae787276-1884-11e8-92e0-a40a70e94e56.png">

**Comment by dereksmart** [comment]
This happens with all notices hooked onto admin_notices

https://github.com/WordPress/gutenberg/issues/3395

Hacking workarounds could be tricky.  Example: try setting a few notices on the same page with another plugin.

**Comment by jeherve** [comment]
I would be inclined to close this as duplicate, since it's an issue with Gutenberg itself.

Previously in https://github.com/WordPress/gutenberg/issues/3703 , #8163, and #8080

**Comment by jeherve** [comment]
Reopening as default notices are now hidden by default in the Gutenberg editor. We will need to use Gutenberg's own notification system if we want to display JITMs there:
https://github.com/WordPress/gutenberg/blob/18edc8edd6f958b3e939116eb54c65084433cb7a/components/notice/README.md

**Comment by lezama** [comment]
@dereksmart could you take this one? 🙇‍♀️

**Comment by jeherve** [comment]
Moving this out of the milestone as we are not breaking any functionality right now; we are "only" missing some of the JITMs.
