### ISSUE TITLE
Images Above Anchor Link Are Not Lazy Loaded

### ISSUE THREAD

**Issue by pmciano** [Automattic/jetpack#8917]
A user in the WordPress.org forum noticed that the Jetpack Lazy Load implementation does not lazy load images that are above a linked section within a page.

This implementation is different from an alternative plugin's approach, which the user recommended:

https://wordpress.org/plugins/simple-lazyload/

You can see an example of this alternative implementation by going here and scrolling up:

http://www.jangadafilmes.com.br/enin-2015/#dia13

This type of approach may be something that can be incorporated into future versions of the plugin.

**Comment by jeherve** [comment]
cc @ebinnion

**Comment by ebinnion** [comment]
To clarify, do the images not load at all? Or, do the images load but not lazily?

**Comment by tkrameral** [comment]
Hi @ebinnion! clarifying:
 > anchor-link-to-gallery2
> text...
>gallery1
>text...
>gallery2 <-- the anchor goes to here!

On plugin that i suggested, if i click on anchor link, view jump to gallery2 (scrolling down the page by anchor/alias), but no one images above are loaded! I Think this is the correct! But the jetpack plugin load all above on this case and if you scroll down the page too!

Thanks!
