### ISSUE TITLE
SEO Tools: Archive titles only support the date archive pages, not any other archives (CPT, ...)

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#8918]
974268-zen

The Archives setting only has options for Site Title, Tagline and Date:

![image](https://user-images.githubusercontent.com/1990037/36599811-7136d9c4-18a8-11e8-843b-0cc4a715051b.png)

For Custom Post Type archive pages, if you leave it blank, the title structure is:

**Post type - Site Title**

Could we add an option for 'Archive Title' so that the structure can be customized but still include the post type?

**Comment by jeherve** [comment]
Could you add this suggestion to the wp-calypso repo directly?

Thank you!
