### ISSUE TITLE
Publicize: metabox is ugly/out of place

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#8919]
The metabox that Publicize adds to the Editor is pretty dated at this point, and doesn't fit as well as it could with the other UI elements in the Publish metabox.

![screen shot 2018-02-22 at 6 38 21 pm](https://user-images.githubusercontent.com/108942/36600603-f8b42c8c-186f-11e8-90c1-3d4d0f08d87b.png)

Suggest
- add an icon
- use bolding consistently with other elements there
- use an Edit link
- iterate on the layout of the list of services; possibly small icons for each and indent them?

Also consider updating links that appear in here to run via Calypso rather than coming back to wp-admin.

**Comment by jeherve** [comment]
From #6049:

it looks inconsistent:

![screen shot 2017-01-06 at 9 53 59 am](https://cloud.githubusercontent.com/assets/108942/21725569/2e3ab020-d3f6-11e6-8cca-2e859531f8ae.png)

I think we should make it look more like the other items, something along the lines of:

![screen shot 2017-01-06 at 10 01 00 am](https://cloud.githubusercontent.com/assets/108942/21725751/fabf964c-d3f6-11e6-8976-c9e9aa948952.png)

**Comment by beaulebens** [comment]
Note it looks even worse if you are using a plugin like AMP, which formats itself according to the other items in the list:

![screen shot 2018-02-25 at 1 56 46 pm](https://user-images.githubusercontent.com/108942/36646362-da4f3474-1a33-11e8-99d6-01a35ce12455.png)

**Comment by rickybanister** [comment]
I think @jeherve's suggestion is as good as we can do here. Make it so!

**Comment by beaulebens** [comment]
@rickybanister what about for the first screenshot in this issue (e.g. when it's open)? Do you suggest any changes there? Or leave as-is and just make the top-level/icon change for now?

**Comment by rickybanister** [comment]
Good point. I was being lazy. Apologies. 

Let's at least standardize with the other sections (which are pretty unremarkable):


![image](https://user-images.githubusercontent.com/437258/36869034-47029a0c-1d68-11e8-9f51-56e822fd28ca.png)

* Change the 'show' link to 'edit'
* When open add an 'OK' button 
* When open change 'hide' to 'cancel'
* Remove bold from 'Connect to:' 
* Do the things @jeherve suggested above
