### ISSUE TITLE
Notices are still using the old style

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#8920]
The notices that we display in Jetpack are still using Calypso's previous visual style, they should be updated:

![screen shot 2018-02-22 at 6 32 22 pm](https://user-images.githubusercontent.com/108942/36600739-5a86c44c-1870-11e8-83df-59cec6be3d53.png)
![screen shot 2018-02-22 at 6 32 24 pm](https://user-images.githubusercontent.com/108942/36600746-5cd7c82c-1870-11e8-91ec-daf169f2d7b8.png)

vs

![screen shot 2018-02-23 at 8 06 19 am](https://user-images.githubusercontent.com/108942/36600783-7267dfd8-1870-11e8-9d39-fba34ec495bb.png)
![screen shot 2018-02-23 at 8 06 40 am](https://user-images.githubusercontent.com/108942/36600802-7efaf992-1870-11e8-9a1d-8233cb20eb93.png)

**Comment by rickybanister** [comment]
We should be able to copy over the styles part & parcel. Let some design folks know if any assistance is needed.

**Comment by MichaelArestad** [comment]
Assigning myself to help assist since I've done this a bunch.

**Comment by MichaelArestad** [comment]
Note: @shaunandrews has a PR in for a style change on certain inline notices: https://github.com/Automattic/wp-calypso/pull/22924
