### ISSUE TITLE
Activity Log: Icon colors for connect/disconnect

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#8921]
Since Jetpack connecting/disconnecting is a pretty major event, I think disconnection should use red, and connection should use green.

![screen shot 2018-02-23 at 8 09 01 am](https://user-images.githubusercontent.com/108942/36600904-dc8199ea-1870-11e8-8a5c-0508d951e777.png)

**Comment by jeherve** [comment]
This should probably be in the wp-calypso repo?

**Comment by beaulebens** [comment]
Oops, yep. Wrong window. Moved to https://github.com/Automattic/wp-calypso/issues/22773
