### ISSUE TITLE
Information icons throughout the UI only have "Learn More" links out to support docs.

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#8922]
Throughout the Jetpack UI (especially in Settings), we have (i) icons everywhere to give some more information about what each feature is. In every case, they just say "Learn More" and link off to a support doc.

In most cases, we should have a brief message in the tooltip that appears, which might provide enough context for people. Then we can still include the "Learn More" if they'd like to get more details.

![screen shot 2018-02-23 at 8 24 32 am](https://user-images.githubusercontent.com/108942/36601709-06ad5554-1873-11e8-9241-3819f38f2484.png)

They should also probably include an icon/indication that they load in a new window.

**Comment by rickybanister** [comment]
@nicoleckohler obviously we have a lot of settings in Calypso and wp-admin, but it would be great to get a list of microcopy to add to the info popovers beyond just 'learn more'. Even if it's `Learn more about inserting a gallery :external-icon:`

Do you think you could take a run through settings and go through each tab and then down each settings card and provide a quick sentence for each? Once we have that it will be very fast for someone to do a single PR that updates all of them.

**Comment by richardmuscat** [comment]
Moving this to needs dev.

**Comment by keoshi** [comment]
@gravityrail Saw you in a bunch of issues and you're on 🔥— do you have the bandwidth to tackle this one too?

**Comment by rickybanister** [comment]
I see this listed as 'in progress', but no PRs are linking to it, @gravityrail need any assistance here, or a handoff?

**Comment by gravityrail** [comment]
@rickybanister I started working on this one but it was way more complicated than I thought. Prob best to hand to a React expert :)

**Comment by eliorivero** [comment]
@rickybanister does this look ok?

<img width="832" alt="captura de pantalla 2018-03-23 a la s 08 53 17" src="https://user-images.githubusercontent.com/1041600/37827782-a8521f74-2e77-11e8-97ba-44ea846014d7.png">

**Comment by rickybanister** [comment]
yup

**Comment by eliorivero** [comment]
PRs created:
Jetpack: https://github.com/Automattic/jetpack/pull/9137
Calypso: https://github.com/Automattic/wp-calypso/pull/23612
