### ISSUE TITLE
Contact Form styling in editor has weird layout for "Website" field

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#8923]
If you insert the default Contact Form into the Editor (in wp-admin), you get a nice preview of it. Looks great except for the Website field, which for some reason is much smaller than the others:

![screen shot 2018-02-22 at 7 10 49 pm](https://user-images.githubusercontent.com/108942/36601765-317e9bd0-1873-11e8-85f8-04608df595da.png)

**Comment by keoshi** [comment]
The CSS is only targeting certain input types:

```
input[type="text"],
input[type="tel"],
input[type="email"]
```

We need to add `input[type="url"]` to this list. References:

- https://github.com/Automattic/jetpack/blob/4a2958e6ef3e047dc1df55741e52cdaa89006a28/modules/contact-form/css/editor-style.css#L65-L128
- https://github.com/Automattic/jetpack/blob/19b0eec0c298c6029995539ab02796ffa78bf776/modules/contact-form/css/editor-inline-editing-style.css#L118-L181
