### ISSUE TITLE
Remove 'or create an account' language from Connection banner

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack#8943]
Currently we have a link to create an account from the disconnected dashboard

![image](https://user-images.githubusercontent.com/437258/36762240-a20aae40-1bf0-11e8-9eb6-b9fbe7bb797b.png)

Since we properly handle connecting users that do not have accounts this is simply confusing. Let's remove it.

While we're at it, the ToS needs to move above the 'Set up Jetpack' button.

**Comment by designsimply** [comment]
Tested and confirmed using the following steps:

1. Go to My Sites > Switch Site > {Jetpack site} > Settings > “Manage your connection” > “Disconnect from WordPress.com” and click the "Disconnect" button.
1. Go to WP Admin > Jetpack for the same site.

![screen shot 2018-03-08 at thu mar 8 3 09 15 pm](https://user-images.githubusercontent.com/1119271/37179491-0903782c-22e3-11e8-9215-3f0f9340719e.png)
<sup>Seen at https://convenient-cuban.jurassic.ninja/wp-admin/admin.php?page=jetpack#/ running WordPress 4.9.4 and Jetpack 5.9 using Firefox 58.0.2 on macOS 10.13.3.</sup>

**Comment by AnnaMag** [comment]
Fix ready in https://github.com/Automattic/jetpack/pull/8973.
