### ISSUE TITLE
Plans grid links should include site slug

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#8953]
In the current beta, we have a new plans grid:

![screen shot 2018-02-28 at 4 23 38 pm](https://user-images.githubusercontent.com/108942/36818776-d3884758-1ca3-11e8-891f-e2458d100a68.png)

All of the links in that grid to individual features should include the site slug, because otherwise the flow I get pushed into is:

- look at the plans grid in the plugin
- find a feature that sounds interesting (specifically, Search)
- click to find out more
- land on jetpack.com and read some more about it
- click through to purchase it, because it sounds awesome ("Get Search in Jetpack Professional")
- hit a page where i'm asked to enter my site URL (boooooo)

Separately, most of these flows are not very good in this context, because I was expressing interest in a feature, in the context of a specific plan. Then I get dropped on a feature-specific page. Then most of the time my best option is a "Plan Comparison", when in my head, I was already in the context of a plan. It feels very circular and tedious.

**Comment by mattwiebe** [comment]
1. Yes, we need the site slug in feature links
2. I agree that the flow to individual features isn't the best, that would take some more work on the jetpack.com side. The main question, then, is whether it's better to have than not have them (considering that we add the site slug so that part isn't broken)

Thoughts, @jeffgolenski as the driver of feature links?

**Comment by mattwiebe** [comment]
(Note that we can remove the feature links by modifying the API response, too)

**Comment by bubel** [comment]
Unless there are any very apparent objections, I think we should remove the feature links for now so that we're not initially looking after a large amount of independent flows (especially while we're doing some work right now to detangle/optimize the wp-admin — Calypso flows).

**Comment by beaulebens** [comment]
Especially if we can control those links via the API, then I definitely agree it'd be good to give them a bit more thought/reduce complexity by removing them for now.

**Comment by mattwiebe** [comment]
Cool cool, the links have been removed via the API as of a moment ago. The responses are cached in a transient for a day, so people may not see it right away on their sites. 

Caching can be disabled with `add_filter( 'jetpack_cache_plans', '__return_false' );`

**Comment by richardmuscat** [comment]
Is this issue resolved then?

**Comment by mattwiebe** [comment]
Oh, I meant to close it. Doing that now.
