### ISSUE TITLE
Pressable NUX: Auto configure credentials is failing on new Pressable site

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#8955]
#### Steps to reproduce the issue
1. Create new Pressable site & open its setting once it's deployed
2. Click on the "finishing up Jetpack connection" link once it showed.
3. Proceed with Pressable NUX flow without delay
4. Sharing credentials will fail with error.`authorize` response:

```
{"code":400,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"vp_api_error","message":"Unable to find a valid site."}}
```

Related to https://github.com/Automattic/wp-calypso/issues/22378

#### What I expected

My credentials are autoconfigured successfully for the first time.

#### What happened instead

Error notification was shown, my credentials weren't configured.
Sometimes credentials did not auto-configure even when success notification is shown. Video: http://take.ms/J1xBQ

After waiting ~5 min - autoconfiguration works as expected.

cc @rcoll as you were helping with the similar issue

**Comment by brbrr** [comment]
That's still an issue with Pressable sites since the script which is populating/sharing/whatever credentials running every 5 mins. So if you'll try to auto-configure credentials between within 5 min window - you'll get an error. There should be a script which will try to autoconfigure these credentials after failure, so I think we good to close this issue. 

cc @thingalon to make sure I didn't mixed up something.

**Comment by thingalon** [comment]
It should no longer be a problem as of this fix: https://vaultpress.trac.automattic.com/changeset/14443

> That's still an issue with Pressable sites since the script which is populating/sharing/whatever credentials running every 5 mins. So if you'll try to auto-configure credentials between within 5 min window - you'll get an error. There should be a script which will try to autoconfigure these credentials after failure, so I think we good to close this issue.

Yep, there is a job that bounces over a 5-30 minute period retrying until we successfully autoconfigure each Pressable site. We were just failing to kick off that process for any non-Atomic Pressable sites automatically... until the above fix. :)

**Comment by jeherve** [comment]
🎉 Thank you! Closing this then.
