### ISSUE TITLE
Comment form: append form below when replying to an existing comment

### ISSUE THREAD

**Issue by keoshi** [Automattic/jetpack#8966]
When replying to an existing comment, would it be viable to have the form appear below said initial comment, instead of having to reload the entire page?

I reckon we could do this with JS, streamlining the commenting experience quite a bit.

Here's a quick code prototype I did on my site:

![jp-comment](https://user-images.githubusercontent.com/390760/36897958-adcc43ca-1e10-11e8-9413-1e7b82767698.gif)

**Comment by dereksmart** [comment]
this is iframed on wpcom and would have to be done there.  I will not be able to get to it, so un-assigning myself.

**Comment by keoshi** [comment]
@jeherve Pinging you on this to see if you know how much work would be involved here? Is this easy enough to do in a couple of days or should it be a project? Do you any developer that would passionate about making the comments experience a lot better or do you reckon this is something I could give a go? Maybe it's better punted to the next hack day? Any pointers would be helpful — thank you!

**Comment by jeherve** [comment]
I had missed that issue, sorry. 

This is actually the default behaviour of the Comment form. If your theme properly enqueues `comment-reply.js`, a js file that ships with WordPress Core, then the comment form will appear below the comment you are replying to when you hit the "Reply" button.

You can see this in action if you use Twenty Nineteen, for example. Here is a post where you can test this now:
https://beau.blog/2019/08/arcteryx-norvan-sl-hoody-review/

**Comment by keoshi** [comment]
No problem, @jeherve — thanks so much for the clarification! I always dequeue any seemingly unnecessary files from the get go, but I guess this one's important! :D
