### ISSUE TITLE
Search: When clicking a filter link, the checkbox is not toggled in Safari

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#8987]
This is a known issue coming from #8806.

#### Steps to reproduce the issue

On Safari:

1. Add the search widget.
1. Search for something in order to get filters (facets) to show up.
1. Check a checkbox. Verify that it does not check before the page reloads.
1. Uncheck a checkbox. Verify that it's still checked before the page reloads.
1 Click a filter label (link). Verify that the checkbox to the left of it does not get checked before the page reloads.
1. Click an active filter label. Verify that the checkbox to the left of it does not get unchecked before the page reloads.

#### What I expected

Safari to behave as Chrome or Firefox

#### What happened instead

It didn't. The behaviour introduced by #8806 can't be reproduced in Safari.

**Comment by bluefuton** [comment]
Happily, this is resolved in Instant Search.

Thanks for reporting it @oskosk!
