### ISSUE TITLE
Map a CNAME to Photon domain

### ISSUE THREAD

**Issue by eduardogoncalves** [Automattic/jetpack#8988]
How can I enable a custom CNAME map to Photon domain?

Sometimes user's firewall at companies blocks wp.com domain, but others domains like www.saibatudomt.com.br or www.agoramt.com.br aren't blocked, so I want to know if we can map for example i1.noticias.mt to i1.wp.com so something like
https://i1.noticias.mt/www.saibatudomt.com.br/wp-content/uploads/sites/3/2018/03/20180305_4.jpg?resize=450,300&ssl=1 can work...

**Comment by jeherve** [comment]
You can use the `jetpack_photon_domain` filter to use your own domain:
https://developer.jetpack.com/hooks/jetpack_photon_domain/

Note that this means you will also need to run your own self-hosted installation of Photon.
https://code.trac.wordpress.org/browser/photon
