### ISSUE TITLE
Sharing menu does now show up in WordPress.com if Publicize is disabled despite Social Buttons enabled.

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/jetpack#8997]
## Summary
*Sharing* menu does now show up in WordPress.com if Publicize is disabled despite Social Buttons enabled.

The social buttons can only be configured by accessing the *Configure your sharing buttons* link in Jetpack Settings → Sharing.

## Steps to Reproduce

1. Disable Publicize in Jetpack Settings → Sharing
2. Ensure Sharing Buttons is enabled
3. Go to WordPress.com

### Expected Result
The Sharing menu should appear on the left sidebar to allow users to configure the buttons

### Actual Result
The sharing menu does not appear.

**Comment by jeherve** [comment]
Since this happens on WordPress.com, could you open this issue in the wp-calypso repo instead?
https://github.com/Automattic/wp-calypso/issues

Thank you!
