### ISSUE TITLE
EU Cookie Law Banner Widget: Policy URL switches from Custom to Default

### ISSUE THREAD

**Issue by juliasydnor** [Automattic/jetpack#8998]
#### Steps to reproduce the issue

1. Go to Customize > Widgets and add an EU Cookie Law Banner (Jetpack) widget to any widget area.
2. In the Policy URL widget settings section, click "Custom".

#### What I expected

I expected "Custom" to remain selected, so I can enter the custom URL.

#### What happened instead

"Custom" automatically switches back to "Default". 

**"Custom" only remains selected after a custom URL has been entered.**

Screencast: http://cld.wthms.co/8mx1WE

**Comment by jeherve** [comment]
Nice catch!

I was able to reproduce on a Jetpack site. I updated the description accordingly.
