### ISSUE TITLE
Unused Class Method: `change_add_new_menu_location`

### ISSUE THREAD

**Issue by jaswrks** [Automattic/jetpack#9001]
[`Jetpack_VideoPress::change_add_new_menu_location()`](https://github.com/Automattic/jetpack/blob/daaef8b1ad284d4ece8f6e5d7fe0873becd1f283/modules/videopress/class.jetpack-videopress.php#L281) doesn't appear to be used anywhere. The [support page](https://jetpack.com/support/videopress/) for the VideoPress module seems to confirm this is intentional. So perhaps it is time to remove this method altogether?

> https://jetpack.com/support/videopress/
> Note: while you can upload videos to VideoPress from the post editor, or from your Media Library under Media > Library, you won’t be able to upload videos to VideoPress when going to Media → Add New.

**Comment by jeherve** [comment]
Related: #7073

**Comment by nielslange** [comment]
#9029 was my very first pull request and after creating it I saw that @Viper007Bond arleady fixed this issue. 🙈

**Comment by Viper007Bond** [comment]
@nielslange D'oh! 😃
