### ISSUE TITLE
Mixcloud Shortcode not working on published content - serving over HTTP

### ISSUE THREAD

**Issue by alisterscott** [Automattic/jetpack#9006]
#### Steps to reproduce the issue

1. Create a new page or post
2. Use a mixcloud shortcode which can be found on any mixcloud page under Share->WordPress ( eg. `[mixcloud https://www.mixcloud.com/DJDimsa/sunset-surf-deep-jazzy-house/ width=100% height=120 hide_cover=1]` )

#### What I expected

Previewing and publishing the shortcode should show the mixcloud widget - as it does on WordPress.com sites ([support doc](https://en.support.wordpress.com/mixcloud-audio-player/))

#### What happened instead

Widget not displayed - could not see the content and error in console: `Mixed Content: The page at 'https://coming-caribbean-350.jurassic.ninja/2018/03/08/mixcloud-2/' was loaded over HTTPS, but requested an insecure resource 'http://api.mixcloud.com/DJDimsa/sunset-surf-deep-jazzy-house/embed-html/?width=100%&height=120'. This request has been blocked; the content must be served over HTTPS.`

Note: pasting the MixCloud URL directly into the editor - not using the shortcode - works as expected

**Comment by orneta19** [comment]
I also have this issue on my WordPress site.
Will this bug be fixed or do I now need to change all the links I have embedded in my site?

**Comment by jeherve** [comment]
@orneta19 That bug was fixed in Jetpack about a year ago. If you still experience isuses with the most recent version of the Jetpack plugin, could you contact us via [this contact form](https://jetpack.com/contact-support/?rel=support) and give us more details about your site so we can take a closer look with you?

Thank you!

**Comment by orneta19** [comment]
Hey @jeherve ,
Thanks for the quick reply!
The bug came out of nowhere for me yesterday.
Jetpack does the analytics for my site.
Wordpress is looking into it now, if they can't find what happened I will open a ticket to you.
Thanks,
Neta

**Comment by orneta19** [comment]
It seems the issue is in Wordpress itself, just the same bug somewhere else :)
Thank you anyways!
