### ISSUE TITLE
Carousel: Keep the title, description, caption layout uniform.

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#901]
In SHA:11b51d we added this line https://github.com/Automattic/jetpack/blob/master/modules/carousel/jetpack-carousel.js#L176 which re-places the title, description, caption based on screen size.

In windows larger than 760px, we show the photo with the caption under it. The title and description follow.

On sizes under, we show the photo, then the title, the description, and finally the caption.

The result can be odd, as in the below cause, the caption "Dsadasd" blends into the description:
![5jbaxh6fr0-3000x3000](https://cloud.githubusercontent.com/assets/88897/3722533/949af038-166a-11e4-8bfa-ef67eb28de2d.png)

Suggest reverting this to keep ordering of elements the same.

Thanks @rase- for tracking this down.

**Comment by mrwweb** [comment]
I think this is the same or closely-related issue, but on large screens, the caption is extremely narrow if the image itself is very narrow.

Example:
![image](https://cloud.githubusercontent.com/assets/1238696/16541683/65b0e750-403e-11e6-97e1-927467f6b075.png)

**Comment by samiff** [comment]
In JP 9.9 the carousel design has been reworked and will look consistent between desktop/mobile in regards to title/description.

![Screen Shot 2021-06-29 at 1 25 55 PM](https://user-images.githubusercontent.com/15803018/123856071-e36ee600-d8dd-11eb-870c-9735c94906dd.png)
