### ISSUE TITLE
Carousel: tapping on the left side of the image on mobile loads next image

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#9011]
#### Steps to reproduce the issue

1. On mobile, load a page with a gallery on a site using Carousel.
2. Tap on the first gallery image to load the first image.
3. If you tap on the right of the image, the next image loads. 
4. Now tap on the left of the image.

#### What I expected

I expected the previous image to load.

#### What happened instead

The next gallery image was loaded instead.

Reported here:
https://wordpress.org/support/topic/carousel-bug/

**Comment by apeatling** [comment]
Will be fixed in https://github.com/Automattic/jetpack/pull/20107

**Comment by stacimc** [comment]
I was unable to reproduce this -- given the age of the ticket and the fact that it seems we were able to reliably reproduce at the time of reporting, I suspect this was fixed in the interim. Agree it should be tested after #20107 👍
