### ISSUE TITLE
Stats: Provide top post by category

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#9024]
For our Top Posts widget, provide an option to show the top post for a given category.

I think this will need to be a `wontfix` given the stats system just returns post IDs without knowledge of the category unless/until there's a stats middleware layer that would quickly interlink post IDs to meta information about them.

981977-zen

**Comment by jeherve** [comment]
Not ideal, but I think you could use the `jetpack_widget_get_top_posts` filter to remove posts that don't belong to the category you are looking for:
https://developer.jetpack.com/hooks/jetpack_widget_get_top_posts/

You would have to combine this with `jetpack_top_posts_widget_count` to start with a big amount of posts, to be sure to return enough posts at the end, after the filtering.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by JiveDig** [comment]
+1

I'd love a built-in method to do this, especially with the new `WPCOM_Stats` class. We're currently using the top posts function/method, but it would be much more straightforward to have some sort of `tax_query` support.
