### ISSUE TITLE
Settings: Replace site verification activation notice with a module toggle

### ISSUE THREAD

**Issue by tyxla** [Automattic/jetpack#9032]
Currently, for the verification tools module, we display the following settings:

**Module deactivated**
![](https://cldup.com/tqGRPDncFa.png)

**Module activated**
![](https://cldup.com/46IXEA0-I5.png)

But in WP.com settings, we removed the activation notice and replaced with a module activation toggle that is visible at all times. It would be nice to do it in wp-admin settings for consistency.

Got any additional thoughts or suggestions on how to approach this one @MichaelArestad or anyone from @Automattic/jetpack-design?

**Comment by jeherve** [comment]
In this case, should we also remove the settings from the Tools menu?

We're not very consistent with our settings in Jetpack Admin and all over the admin interface: some settings have 4 interfaces (Calypso, Jetpack Admin, wp-admin, and customizer), others have 3, or 2, or just one, and it's often hard to say why and what settings we should link to in Jetpack Admin.

@beaulebens What's your take on this?

**Comment by MichaelArestad** [comment]
I don't see a benefit for our users for removing this from Jetpack settings. The reason the other settings are dotcom only are because of plugin repo rules. Otherwise we would match the settings in both.

**Comment by tyxla** [comment]
Thanks for the background, folks. I didn't realize that we're lacking those settings because of plugin directory rules. 

In that case, it would probably make sense to add the toggle to the Jetpack settings in wp-admin for consistency.

Rephrasing the issue now.

**Comment by rickybanister** [comment]
@MichaelArestad do you think that even having the toggle here would be against the repo rules? Since this is a paid-only feature we have to be careful with that. It may make sense to leave this as is and only remove the settings from the tools menu as @beaulebens. I'm just not 100% sure. Even if we give them a toggle, they still won't have configured GA so having only one action (the link to wp.com) might be the best option.

**Comment by beaulebens** [comment]
Verification tools are actually part of the free service.

**Comment by MichaelArestad** [comment]
Closing in favor of this: https://github.com/Automattic/jetpack/issues/12123
