### ISSUE TITLE
Blacklisting "share by email" spammers

### ISSUE THREAD

**Issue by galbaras** [Automattic/jetpack#9040]
From time to time, I get failure notices for "share by email" messages. The sender is always some user on the qq.com domain, which is well outside my target audience, so I'm happy to blacklist the entire domain in order to stop the abuse.

#### Steps to reproduce the issue

Sorry, I've taken the "share by email" feature off my site.

#### What I expected

To be able to block shared emails by various patterns in attributes, like subject, sender address, recipient address and message body.

#### What happened instead

The email just goes out unfiltered and I get failure notices with the original messages being in Chinese (the site is in English and its target is Brisbane, Australia).

**Comment by jeherve** [comment]
When one uses the Akismet plugin on their site alongside the Email sharing button, all emails go through the Akismet service before being sent. That should filter most of the spam emails.

Another alternative is to rely on Google Recaptcha to protect the email form:
https://jetpack.com/support/sharing/#captcha

We also offer the `sharing_email_can_send` filter so you can filter the emails before they get sent, using your own functions.

Are those options enough in your opinion, or would you be looking for something more?

**Comment by galbaras** [comment]
Thanks for these, Jeremy.

What I was originally looking for, I guess, was a way to report the offending user/domain to Akismet. From what I know, the only interface is in comment moderation, but the email sharing feature is not related.

A captcha can protect against bots, and that's great, but I'm not sure that's what I'm dealing with here. Also, why not use settings for this feature?

The combination of methods above requires code changes, possibly ongoing, but it should give me good coverage.

Thanks again,
Gal

**Comment by jeherve** [comment]
> From what I know, the only interface is in comment moderation, but the email sharing feature is not related.

That is correct. We can't really build in a moderation panel here, since we don't track when the button is used in your dashboard (and I don't think we should, I don't think most readers except the text they enter them to be logged or monitored).

> A captcha can protect against bots, and that's great, but I'm not sure that's what I'm dealing with here. 

That's a good point; if the button users are humans and not bots, the captcha won't stop them. But since the site is public, they would be able to share a link to your posts even without the button. If they abuse the button, one more step (proving they are human) should help.

> why not use settings for this feature?

Since a lot of Jetpack users use the Akismet plugin, Recaptcha isn't really useful most of the time.

I hope this clarifies things a bit.

**Comment by galbaras** [comment]
It does. Thanks.

One more option could be to deliver the email using wp.com servers and handle bounces.

Anyways, thanks again. You've been very helpful.

**Comment by jeherve** [comment]
> One more option could be to deliver the email using wp.com servers and handle bounces.

That's indeed something we've discussed in the past, but if we were to implement this the sharing feature would then rely on your site's connection to your WordPress.com account. That means you would not be able to use the Sharing feature when using [Jetpack's Development Mode](https://jetpack.com/support/development-mode/). That would be a problem for people who use the sharing buttons today without connecting their site to WordPress.com.

We may consider this again in the future, but for now I don't think we'd like to make that feature rely on WordPress.com.
