### ISSUE TITLE
Upgrading from 5.8 to 5.9 removes Elasticsearch search widget

### ISSUE THREAD

**Issue by kevinlisota** [Automattic/jetpack#9041]
We have Elastisearch enabled on our site and use the Jetpack search filter widget on the sidebar of our search results page. This works fine in Jetpack 5.8.

After upgrading our site to Jetpack 5.9, the Jetpack search widget seems to have disappeared. It is not in the widgets list under appearance. It is not in the customizer widget list. And it does not render on the site.  The only search widget that appears is the default WordPress search box, not the special Jetpack one.

The debug log gives this error as well: `Undefined index: jetpack-search-filters-3 in /var/www/geekwire.com/wp-includes/widgets.php on line 813`

Rolling back to 5.8 solves this issue.

**Comment by jeherve** [comment]
Could you try to go to Jetpack > Settings in your dashboard, search for "widgets", and make sure the Extra sidebar widgets feature is enabled?

Let us know how it goes.

**Comment by kevinlisota** [comment]
That was indeed the issue. Enabling Extra Sidebar Widgets made it reappear.

There is still a design flaw here, I think. It allows you to turn on search, then shows a dialog to add a widget, even when the widget isn't technically active (at least in 5.9)

**Comment by Viper007Bond** [comment]
Yep, certainly a bug. The widget should be loaded regardless. I'll work on a fix.
