### ISSUE TITLE
Password stregth assessment fails when Jetpack activated

### ISSUE THREAD

**Issue by p3ob7o** [Automattic/jetpack#9063]
#### Steps to reproduce the issue

- Go to /wp-admin/profile.php on a brand new WordPress site
- Scroll down to the password update section, click on Generate New Password
- Input a long and complex password generated by a password manager.

(I tried with 1Password, and also just pasting the password myself, with passwords from 32 to 64 characters in length, containing from 0 to 5 digits and 0 to 5 symbols.)

#### What I expected
I expected my passwords to be evaluated as strong, especially the 64 characters, 5 digits, 5 symbols ones.

#### What happened instead
I see a message saying: "Password strength unknown" and have to check a box saying "Confirm use of potentially weak password" if I want to validate the password change.

This does not happen if I deactivate Jetpack 5.9. When I deactivate it, everything works as expected.
The only other plugin is Akismet 4.0.3 and WordPress version is 4.9.4

**Comment by jeherve** [comment]
I can't seem to be able to reproduce the issue on a brand new site. It seems to work whether Jetpack is inactive, active, or active and connected to WordPress.com:

<img width="863" alt="screen shot 2018-03-16 at 12 24 33" src="https://user-images.githubusercontent.com/426388/37518347-0cb76d4c-2915-11e8-8b60-3ee1f6d8229e.png">

Could you head over to the `/wp-admin/admin.php?page=jetpack_modules` page and try to deactivate all Jetpack modules, one at a time, and let me know if one of them appears to cause the issue on your site?

**Comment by p3ob7o** [comment]
Done, it is the **Notifications** module. Another symptom I had not noticed the first time is that when Notifications is activated, clicking on the Generate Password button reveals the password input field but leaves it empty.

**Comment by jeherve** [comment]
Hm, I still can't seem to reproduce. Which browser is this in, and are you currently:
- logged in to WordPress.com?
- proxied?

**Comment by p3ob7o** [comment]
Safari 11.0.3 (13604.5.6) on macOS 10.13.3, logged into WordPress.com and proxied.

Doesn't happen in Chrome 65.0.3325.146 and Safari iOS 11.2.6

**Comment by jeherve** [comment]
I still can't reproduce, unfortunately :(

Using the browser's dev tools, could you check for Javascript errors on the page? Could you also try to disable any browser extensions you use and that may get in the way? 

Let me know what you find!

**Comment by p3ob7o** [comment]
I cannot reproduce anymore since Safari was updated to 11.1 on macOS 10.13.4, and Jetpack to 6.0 on WordPress 4.9.5

In other words, I guess this issue can be closed :)
