### ISSUE TITLE
Photon: Special characters in image file names return 404

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/jetpack#9099]
#### Steps to reproduce the issue

1. Use a theme such as Apostrophe 2
2. Enable featured image fallback in the customizer
3. Add image to post with characters such as œ in the file name

#### What I expected

That the image would display properly as the featured image for a post.

#### What happened instead

Photon returns a 404 for images with characters like these in the name and a broken image appears on the page.

#### Screenshots

<img width="1202" alt="broken-image" src="https://user-images.githubusercontent.com/1326294/37676605-24917a3a-2c57-11e8-87b8-bb29f18cc44d.png">
<img width="729" alt="image-file-name" src="https://user-images.githubusercontent.com/1326294/37676613-29645366-2c57-11e8-8f8d-41a3bb231d30.png">

Thanks to @jeherve for helping me figure out what was happening here.

**Comment by brezocordero** [comment]
Another report here: 1030959-zen

**Comment by serabi** [comment]
Another report here: 2598136-hc

**Comment by kathrynwp** [comment]
Another report in 4695988-hc

Filename has Chinese characters that are making the file return a 404 error. When the Chinese characters are removed from the filename, the image appears correctly.

**Comment by tbradsha** [comment]
12229340-hc had Photon 404s due to a copyright symbol (©) in the file name.

**Comment by danjjohnson** [comment]
Also reported in 3883287-zen

**Comment by kraftbj** [comment]
I'd like to confirm this is still happening. 3883287 is something different, I think, and a couple initial tests with the URLs from that ticket work.

**Comment by jeherve** [comment]
Closing this now. See 6529-gh-jpop-issues for more info.
