### ISSUE TITLE
Custom Post Types and Customizer panels not available on local install of Jetpack

### ISSUE THREAD

**Issue by johnpitchko** [Automattic/jetpack#9104]
#### Steps to reproduce the issue
1. Install clean Scotchbox install
2. Install and configure Wordpress
3. Install and activate Jetpack
3. Install and activate Jetpack theme (e.g. Independent Publisher 2 or other theme that supports Portfolios)

4. In Jetpack settings, enable **Portfolios** custom post type

or

Open **Customizer**

#### What I expected
To see the *Portfolios* panel in the admin area, and to see the *Content Options* panel in Customizer.

#### What happened instead
Neither panel is displayed.

![jetpack-settings-portfolio-enabled](https://user-images.githubusercontent.com/7190681/37691068-d76c54be-2c74-11e8-818f-3ae528cde291.png)
You can see here that the **Portfolio** custom post type is enabled, but the menu item on the nav bar is not present.

![missing-content-options-panel](https://user-images.githubusercontent.com/7190681/37685797-6a954aae-2c5a-11e8-8ee1-3fa65c138ab0.png)

Note this happens both with and without Jetpack in Development Mode.

**Comment by jeherve** [comment]
Thanks for the report. Does the problem remain when you refresh the page, after having enabled the option under Jetpack > Settings?

**Comment by johnpitchko** [comment]
Hello @jeherve yes the issue remains after refreshing.

@flurinduerst suggests [here](https://github.com/flurinduerst/WPDistillery/issues/73#issuecomment-375028535) the issue may be related to XML-RPC not working in the current release of Scotchbox. I'll do some digging to see.

**Comment by johnpitchko** [comment]
Tested with a clean install of VCCW. Both Portfolio nav bar item and Content Options panel in Customizer are available.

Issue appears to be part of Scotchbox, so I opened an issue there.

Thanks @jeherve !
