### ISSUE TITLE
My number of subscribers is wrong

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack#9130]
I was testing the subscription widget and noticed this:

![image](https://user-images.githubusercontent.com/437258/37800478-4400ed1c-2df9-11e8-883a-f43378c9d50f.png)

Which didn't sound right because it's a test site. So I checked by visiting settings and clicking on the email subscriber link and saw this:

![image](https://user-images.githubusercontent.com/437258/37800446-3841f840-2df9-11e8-85f3-fa71795cb498.png)

Am I missing something?

**Comment by designsimply** [comment]
You selected the "Show total number of subscribers" option which includes any followers from connected Publicize services. [#](https://en.support.wordpress.com/widgets/follow-blog-widget/)

Does the blog you are working with have sharing services connected?

Also see https://github.com/Automattic/jetpack/issues/7657

**Comment by rickybanister** [comment]
It does:

![image](https://user-images.githubusercontent.com/437258/37834240-afa770f6-2e83-11e8-9783-b7ec5778cec6.png)

That wasn't very intuitive to me, but makes sense.
