### ISSUE TITLE
Instagram embed locked to max-width: 658px

### ISSUE THREAD

**Issue by mskogly** [Automattic/jetpack#9133]
#### Steps to reproduce the issue
When pasting a link to instagram into a post, the max-width of the post is hardcoded to max-width: 658px;
#### What I expected
I expect 100% as a default. When hardcoding inline there is noe way to override.

**Comment by jeherve** [comment]
I'm afraid that's not something we can change in Jetpack. Instagram never returns images that are larger than 658px. Take this example, where we are querying Instagram's API for a specific embed with a width of 1000px:

https://api.instagram.com/oembed/?url=https://www.instagram.com/p/BgMjGO1lg8T/&maxwidth=1000

As you can see in the response, we still get `"width": 658` back from Instagram:

<img width="911" alt="screenshot 2018-03-23 at 17 43 02" src="https://user-images.githubusercontent.com/426388/37842159-aa57d120-2ec1-11e8-9f38-413712fa78bc.png">

I assume Instagram does not store larger images on their end. If you would like larger embeds, you would have to contact them directly about this.
