### ISSUE TITLE
Dashboard stats flashing no stats on render.

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#9141]
introduced in #9108, this is now happening on first page loads of the Jetpack Dashboard: 

![stats](https://user-images.githubusercontent.com/7129409/37851419-284a07c2-2eb5-11e8-881e-db2e721b7565.gif)

**Comment by dereksmart** [comment]
Also, all of the tabs are hidden whenever you switch.

**Comment by dereksmart** [comment]
Also, "Okay Got it" message still shows, even if you've dismissed it before.

**Comment by zinigor** [comment]
Fixed in #9213
