### ISSUE TITLE
Subscriptions: Use the featured image if there is a featured image on the post

### ISSUE THREAD

**Issue by s2r** [Automattic/jetpack#9145]
The subscriptions as of now are too plain, the brief e-mail summary and wordpress.com color scheme makes the emails look always the same, having a featured image makes it much more informative and appealing to the subscribers.

Example: Some posts on my cooking site, are just a featured image and a very brief intro and then it goes into a custom structure to show the recipe and instructions, so sometimes the subscribe emails that everyone gets are just 2 lines of text and a headline, that doesn't make anyone want to visit the site to check it out.

![screen_shot_2018-03-24_at_21_01_29](https://user-images.githubusercontent.com/2265583/37869037-68a195b2-2fa8-11e8-87e7-2c8036d631c8.png)

Example Image attached: as you can see the useful part of the e-mail is less than half of the e-mail, it would make it much more visually appealing if a featured image was also attached to the e-mail, even if just to break the visual monotony of the subscriptions service.

**Comment by Volnus** [comment]
I like this idea the issue I can see though is that by default WordPress' RSS feed doesn't include the featured image by default also they would need to modify the wordpress.com side of things. 

https://github.com/Automattic/jetpack/issues/2957

That being said it looks like three years ago this was brought up and was being tracked internally.

**Comment by jeherve** [comment]
We're indeed still tracking this internally, as that's something we would implement on WordPress.com, and that Jetpack site owners would get as well.

I'm going to close this issue as duplicate, and add a link to it in our internal bug tracking tool.

Thanks for the suggestion.
