### ISSUE TITLE
Sitemaps: home page listed twice when site is set to use a static front page

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#9159]
#### Steps to reproduce the issue

0. Start from a site where Sitemaps are not active yet.
1. Go to Settings > Reading in your dashboard, and set a static front page for your site.
2. Go to Jetpack > Settings and enable the Sitemaps feature.

The site's home page will be listed twice in the main sitemap.

Reported here:
https://wordpress.org/support/topic/home-page-and-categories-links-issue-in-sitemap/

**Comment by kraftbj** [comment]
In `sitemap-builder.php`, we're just adding the homepage without checking for anything and then, we'd also be adding any page in the db. Need to add a conditional to skip if front is set to a static page.
```
		// Add entry for the main page (only if we're at the first one).
		if ( 1 === $number ) {
			$item_array = array(
				'url' => array(
					'loc' => home_url(),
				),
			);
```
