### ISSUE TITLE
RSS Widget: Does not parse Google Alert feeds properly

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/jetpack#9171]
#### Steps to reproduce the issue
- Create an RSS feed alert at https://google.com/alerts/
- On a WordPress.com site add a RSS Widget with the Google Alerts RSS URL
- Example: https://www.google.com/alerts/feeds/18136033019002538928/2071965684389353000

#### What I expected
The items show up in the Widget and I'm able to click on the item title to go to the URL

#### What happened instead
The items show up but each item is not a link
This seems to work on Jetpack sites but not WordPress.com sites

**Comment by jeherve** [comment]
That RSS widget is not part of Jetpack I'm afraid. It is a core WordPress feature:
https://codex.wordpress.org/WordPress_Widgets#Using_RSS_Widgets

If it does not work on WordPress.com sites, I would recommend opening an issue there, on wpcom.trac.
