### ISSUE TITLE
Dashboard: improve display of status numbers

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack#9196]
The number in each box tends to float a bit, with various layouts it can look somewhat bad. Can we try making it more of a block? 

Also note the  copy change to the plugins card—move any text out of the number and we'll rewrite the copy as I've done in my 'after' screenshot for the plugins card.

Before:

![image](https://user-images.githubusercontent.com/437258/38144351-607d52d6-3412-11e8-93ad-8ff9f1f1b31f.png)

After:

![image](https://user-images.githubusercontent.com/437258/38144359-68cf0f1a-3412-11e8-954d-8efc5daeb026.png)

The css I used in the inspector:

```
.jp-dash-item__count {
    margin-top: 0;
    margin-bottom: 0;
    color: #00aadc;
    font-weight: 500;
    font-size: 2rem;
    display: inline;
    border: 1px solid #CBD7E1;
    border-radius: 4px;
    padding: 0px 4px;
    float: left;
    margin-right: 8px;
    min-width: 36px;
    text-align: center;
}
```

**Comment by dereksmart** [comment]
> The css I used in the inspector:

@rickybanister Very helpful to include that here, thank you!

**Comment by rickybanister** [comment]
I thought of you :)
