### ISSUE TITLE
Feature: Markdown support as a Markdown-specific Gutenberg Block

### ISSUE THREAD

**Issue by nuzzio** [Automattic/jetpack#9201]
The reasoning behind this feature addition is to add the ability to save and edit Markdown in posts when using Gutenberg. This would restore the spirit of the classic editor Markdown implementation.

Additional reasons are:

By @MichaelArestad
> There are times (like in p2s) where it’s much more complex to go back and edit a post than to initially create it. This is because p2 removes the markdown formatting replacing it with html. I think there is value in preserving the original content. It would also allow one to compose elsewhere and just paste in valid markdown.

By @mtias
> People who prefer to write markdown want to retain the text as markdown.

### Implementation Approach:

__First Iteration__
Implement a Markdown block as a simple field with no preview functionality.

![markdown-block-v1](https://user-images.githubusercontent.com/952411/38873409-b5f87a00-4223-11e8-994c-8bfe1f6597c9.gif)

__Second Iteration__
Implement a live preview functionality like in Calypso.

![markdown-block-v2](https://user-images.githubusercontent.com/952411/38873420-bcb2e308-4223-11e8-8c51-c747a5c0207a.gif)

__Third Iteration__
Optimize UX by implementing formatting buttons which can wrap text elements in the chosen markup, i.e. bold to bold

![markdown-block-v3](https://user-images.githubusercontent.com/952411/38873431-c180f370-4223-11e8-9fed-41b72f33e844.gif)

I believe this one will require some discussion of the interactions with the toolbar since some of them may be unexpected in current patterns e.g. 

1) Click to bold > bold stays selected
vs
2) Click to bold > bold Markdown bounds selection and bold toolbar button remains unselected

Those considerations are further down the road but worth noting.

###### Sub-tasks to be added as specific changes are determined

- [x] Create a markdown-specific block that preserves markdown content.

###### TBD
- [x] Convert the Markdown to HTML on the server at the time of rendering.

**Comment by jeherve** [comment]
Related: #7786

**Comment by nuzzio** [comment]
Added mockups for each iteration in main issue.

**Comment by nb** [comment]
What do you think about exposing basic formatting without the need to preview. Maybe only for headings, bold, italic, links, code. No need to do it for more complex constructs like tables. Here is what the in-editor formatting could look like:

# # Example
## ## Sub-example
Hello, **\*\*surrounded by double asterisks**** text is bold, _\_by underscores\__ or *\*single asterisk\** is italic, `` `code in backquotes` `` is monospace.

If we decide to include it, how does it affect your current iteration plan?

**Comment by nb** [comment]
One more question – why converting to markdown on the server and not on the client? What are the trade-offs?

**Comment by MichaelArestad** [comment]
> What do you think about exposing basic formatting in edit mode without the need to preview. 

@nb That is something I was thinking about. While I don't think we should highlight them as a preview, I do think we should highlight them to make it clear what is being formatted. For example, Ulysses doesn't show a preview, but does highlight it in a way that is preview-ish. This way, the user gets a good idea of how their markdown is working. We also wouldn't be jumping between font sizes. I do think we'll eventually want a full preview that hides the markdown characters and renders it the way the rest of the standard blocks look. Here's a screenshot from Ulysses:

![image](https://user-images.githubusercontent.com/1123119/38996973-8fbc5258-43a9-11e8-9966-2ab661d36986.png)

**Comment by nb** [comment]
Thanks for the answers, @nuzzio and @MichaelArestad.

**I totally agree with both of you that the exposing the formatting is just a hint and should independent from the full preview, which is both a helpful and a must-have feature.**

**Comment by nb** [comment]
As for client side vs. server side, there is another option that I didn't see above – can we keep it 100% client-side by storing the rendered HTML in the serialized block in `post_content` and the  markdown somewhere else (either a block attribute or `post_content_filtered`). It may require some backwards compatibility wrangling, but seems more in line with Gutenberg’s philosophy to avoid dynamic blocks when we can help it.

P.S. I so much wish GitHub had threaded conversations…

**Comment by nb** [comment]
One more question – how do we reconcile Jetpack’s per-post Markdown option and the per-block markdown rendering discussed here?

**Comment by nuzzio** [comment]
@nb 
> As for client side vs. server side, there is another option that I didn't see above – can we keep it 100% client-side by storing the rendered HTML in the serialized block in post_content and the markdown somewhere else (either a block attribute or post_content_filtered). It may require some backwards compatibility wrangling, but seems more in line with Gutenberg’s philosophy to avoid dynamic blocks when we can help it.

I do think that this is the ultimate solution, I would like to avoid the dynamic block. I also agree that `storing the rendered HTML in the serialized block in post_content` is the way to go. My client side approach above had the client doing all the markdown parsing, and my naive assumption was to use the `post_content_filtered` storage as before.

I think the `backwards compatibility wrangling` will be interesting. I need to get some more background on the intended usage of `post_content_filtered`. Hmm I think I also need to look at how other blocks are storing data that is not intended to be on the rendered post. 

Are there any examples of this that you would suggest looking at?

Your second question:

> how do we reconcile Jetpack’s per-post Markdown option and the per-block markdown rendering discussed here?

I think the user contract of the classic implementation had two key parts: 

1) We will persist your Markdown parts so that the Markdown parts will be there when you edit.

2) People viewing your post will see the rendered HTML version of your Markdown text, formatted as you specified in Markdown.

I think we can stay true to those two things within the block metaphor. We could make the changes clear to the user in the settings text:

> Write posts or pages in plain-text Markdown syntax

to something like

> Enable plain-text Markdown syntax in posts and pages. Enable the Gutenberg Markdown block.

What do you think?

**Comment by brentlogan** [comment]
One potential issue I see with the per-block vs. per-post issue: footnotes. With a per-post perspective, the footnotes end up at the bottom of the post. With a Gutenberg Markdown block, I assume the footnotes should still end up at the bottom of the post, but is that a given?

**Comment by nuzzio** [comment]
That is a good point. The current footnote functionality exists in the Jetpack Markdown module in PHP. If it becomes 100% client side, there will be edge cases like this that will require parity.

**Comment by nuzzio** [comment]
I will be continuing comments on the pull request: GH-9357.
