### ISSUE TITLE
Admin page: App nag is passive-aggressive

### ISSUE THREAD

**Issue by dmsnell** [Automattic/jetpack#9215]
When I logged into my Jetpack settings I found this banner and was offended by the only two options it provides:

 - `Download the free apps`: No, I don't want to.
 - `I already use this app.`: No I don't and I have no intention to

<img width="753" alt="screen shot 2018-04-03 at 1 36 38 pm" src="https://user-images.githubusercontent.com/5431237/38244744-4bddb2e6-3744-11e8-8f7b-61d335f13f72.png">

https://github.com/Automattic/jetpack/blob/c5aea2387b4f5ebacd19b30286a743f1d6520480/_inc/client/components/apps-card/index.jsx

It's clear that the second option is intended to dismiss the nag but in order to do it we're putting someone on edge by forcing them to _say_ something they don't want to through their click and the reason is because we gave them a false binary choice.

Can we replace this with something more straightforward and less passive-aggressive like `Dismiss this banner.`?

**Comment by beaulebens** [comment]
Let's just remove the dismissal message and change it to a white `x` in the top corner to match other dismissals throughout the plugin.
