### ISSUE TITLE
JITMs: be nice to Dolly

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#9221]
When Hello Dolly! is active and showing its paragraph, the JITM shows like this

<img width="1013" alt="captura de pantalla 2018-04-03 a la s 16 41 57" src="https://user-images.githubusercontent.com/1041600/38271892-0e32a75c-375e-11e8-9e2b-a6fab433978a.png">

when it's not, the JITM shows correctly

<img width="1013" alt="captura de pantalla 2018-04-03 a la s 16 42 16" src="https://user-images.githubusercontent.com/1041600/38271893-0e63997a-375e-11e8-83c0-96263ed32cbd.png">

**Comment by withinboredom** [comment]
Also assigning @jeffgolenski as well.

**Comment by jeherve** [comment]
Still an issue.

**Comment by jeffgolenski** [comment]
@jeherve Sorry I missed this one. Giving it a look today.

**Comment by jeffgolenski** [comment]
Both @withinboredom and myself are working to get this fixed up. cc @beaulebens
