### ISSUE TITLE
Jetpack Plans: Show discounts for plan upgrades

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#9225]
#### Steps to reproduce the issue

1. Buy a Personal plan
1. Go to `/wp-admin/admin.php?page=jetpack#/plans`
1. Review plans and their prices
1. Check plans on `https://wordpress.com/plans/YOUR_SITE` and compare with `wp-admin` version

#### What I expected

`wp-admin` Plans page is emphasizing the discounts for plans upgrades, so I will know that I will not over-pay with an upgrade.

#### What happened instead

`wp-admin` Plans page doesn't show any discounts for plan upgrades.

<img width="400" alt="jetpack adverse albatross 178 wordpress 2018-04-04 09-44-28" src="https://user-images.githubusercontent.com/5654161/38292562-e12413ce-37ec-11e8-9131-02071fa8fa2f.png">

<img width="400" alt="plans adverse albatross 178 wordpress com 2018-04-04 09-43-59" src="https://user-images.githubusercontent.com/5654161/38292571-ea2550be-37ec-11e8-98e2-8a8845002a03.png">

**Comment by jeherve** [comment]
Closing this for now since the "My Plans" page now redirects to WordPress.com.
