### ISSUE TITLE
Remove translations from Jetpack-CLI

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#9227]
I just figured wp-cli [doesn't support translations](https://make.wordpress.org/cli/handbook/force-output-specific-locale/). It's possible to support translations only in the output coming from WP (and even force it to specific language as it defaults to English).

So we shouldn't really spend time translating strings in `class.jetpack-cli.php` — it's roughly 100 strings (~3-4% of strings) currently being translated and those translations never end up being used. 😞

We could keep translating them just for the sake of future in case wp-cli someday adds translations support, but as it's now it's just causing extra work for translators.

**Comment by oskosk** [comment]
@simison I get some translations coming from Jetpack

Looks like `Módulos Disponibles` (Availalbe Modules) is being translated to Spanish here.  


```
$ yarn docker:wp jetpack module list

Módulos Disponibles:
	after-the-deadline      Inactivo
	carousel                Activo
	comment-likes           Inactivo
	comments                Inactivo
	contact-form            Activo
	custom-content-types    Activo
	custom-css              Activo
```

The same goes for some more specific Jetpack commands:

```
yarn docker:wp jetpack sitemap generate

Error: El módulo de mapas del sitio de Jetpack está activo pero no está disponible. Esto puede ocurrir si tu sitio está configurado para disuadir del indexado a los motores de búsqueda. Por favor, activa el indexado en los motores de búsqueda para permitir la creación del mapa del sitio.
```

**Comment by simison** [comment]
Oh, that's weird! If I change locale via wp-admin UI it does get translated.

If I change via cli:
```sh
yarn docker:wp language core install es_ES
yarn docker:wp language core activate es_ES
```

It doesn't. 🤷‍♂️  Oh well closing as these clearly do get translated!

**Comment by oskosk** [comment]
could it be that you also need to update translation after activating a language that you weren't using before? Not quite sure tho...
