### ISSUE TITLE
Related Post no preview on external image

### ISSUE THREAD

**Issue by Diddlik** [Automattic/jetpack#9231]
Hello,

in last time I mentored, that related post does not have an preview image. Some tests show if I don’t use width=”xxx” height=”xxx” parameter for image tag, there are now preview image in elated post. I I set this parameter, so I get preview on it.
for example here: https://ewelt.org/blog/das-haus/info/bauvorschrift-fuer-das-baugebiet/

Best regards,
Pavel

The page I need help with: https://ewelt.org/blog/foto/saechsische-schweiz-in-einem-tag-teil-i/

**Comment by jeherve** [comment]
We indeed made some changes to how images are selected to be used in Related Posts or in other places (like Open Graph Meta Tags). Those changes are outlined in #8237, so I will close your issue as duplicate.

If you think we should revert that change, do not hesitate to comment on that issue with your ideas.

Thank you.
