### ISSUE TITLE
Plugins may not track users without their consent.

### ISSUE THREAD

**Issue by grappler** [Automattic/jetpack#9233]
~~According to the [WordPress.org Plugin guidelines](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/):~~
> ## Plugins may not track users without their consent.
> In the interest of protecting user privacy, plugins may not contact external servers without explicit and authorized consent. This is commonly done via an ‘opt in’ method, requiring registration with a service or a checkbox within the plugin settings.

Edit: It is not a requirement from the Plugin guidelines but from GDPR.

This does not seem to be case.
![image](https://user-images.githubusercontent.com/1785641/38296335-596c41c2-37f1-11e8-8d6a-90b0cd3f1695.png)

**Comment by oskosk** [comment]
Closing. As @jeherve explained consent is granted by connecting Jetpack and since Jetpack 6.0, by clicking the button.

**Comment by pesieminski** [comment]
Yes this is correct.

**Comment by BinaryMoon** [comment]
This doesn't meet GDRP requirements.

https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/lawful-basis-for-processing/consent/

A few highlights from that document

> * Consent requires a positive opt-in. Don’t use pre-ticked boxes or any other method of default consent.
> * Explicit consent requires a very clear and specific statement of consent.
> * Keep your consent requests separate from other terms and conditions.
> * Be specific and ‘granular’ so that you get separate consent for separate things. Vague or blanket consent is not enough.

**Comment by grappler** [comment]
@pesieminski @oskosk  I don't think that this is correct but then I am not going to need to defend the decision.

Here is another quote from the ICO Website.
> Unbundled: consent requests must be separate from other terms and conditions. Consent should not be a precondition of signing up to a service unless necessary for that service.

https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/consent/whats-new/
