### ISSUE TITLE
Widgets: Social Icons - Missing argument for enqueue_admin_scripts callback when Page Builder (by SiteOrigin) is installed

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#9234]
I created a fresh site with Jetpack 6.0, connected it, added Page Builder and when attempting to add a new page I saw these warnings in the log 
```
Undefined variable: hook
 Type: PHP Notice Line: 48
 File: wp-content/plugins/jetpack/modules/widgets/social-icons.php

Missing argument 1 for Jetpack_Widget_Social_Icons::enqueue_admin_scripts(), 
called in wp-content/plugins/siteorigin-panels/inc/admin.php on line 449 and defined
```

#### Steps to reproduce the issue

* On a connected site with Jetpack 6.0 and [Page Builder](https://wordpress.org/plugins/siteorigin-panels/) installed.
* Make sure `WP_DEBUG` and/or `WP_DEBUG_LOG` are turned on
* Attempt to create a new Page  ( Pages -> Add New )
* Check the logs.
* Expect to see the warning

#### What I expected

* No warnings

#### What happened instead

* Those warnings

**Comment by jeherve** [comment]
Also in 1064342-zen

**Comment by chaselivingston** [comment]
Also reported in 1064342-zen.

**Comment by tmmbecker** [comment]
also reported in: https://wordpress.org/support/topic/v6-0-i-cant-edit-or-create-posts/

**Comment by oskosk** [comment]
@jeherve I couldn't reproduce anything heavier than this warning. I actually found this warning when trying to reproduce a comment that someone left on the Release post.

**Comment by vinnie2k** [comment]
also reported in https://wordpress.org/support/topic/urgent-conflict-between-site-origin-page-builder-and-wordpress-4-9-5-update/#post-10145485

**Comment by vinnie2k** [comment]
Here is my log of the error breaking the Edit page (fatal error):

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Jetpack_Widget_Social_Icons::enqueue_admin_scripts(), 0 passed in /home/*****/public_html/test/wp-content/plugins/siteorigin-panels/inc/admin.php on line 449 and exactly 1 expected in /home/*****/public_html/test/wp-content/plugins/jetpack/modules/widgets/social-icons.php:45 Stack trace: #0 /home/*****/public_html/test/wp-content/plugins/siteorigin-panels/inc/admin.php(449): Jetpack_Widget_Social_Icons->enqueue_admin_scripts() #1 /home/*****/public_html/test/wp-includes/class-wp-hook.php(286): SiteOrigin_Panels_Admin->enqueue_admin_scripts('') #2 /home/*****/public_html/test/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #3 /home/*****/public_html/test/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /home/*****/public_html/test/wp-admin/admin-header.php(118): do_action('admin_print_scr...') #5 /home/*****/public_html/test/wp-admin/edit-form-advanced.php(483): require_once('/home/*****/...') # in /home/*****/public_html/test/wp-content/plugins/jetpack/modules/widgets/social-icons.php on line 45

**Comment by oskosk** [comment]
Here's a screenshot of the bigger problem coming from this issue that happens when the Social Icons Widget is indeed present on any sidebar and WP is running on PHP 7.1 or PHP 7.2:

To reproduce:
* Same steps described in this issue
* Add a Social Icons widget to a sidebar. No extra configuration needed.



![image](https://user-images.githubusercontent.com/746152/38314652-1cb4ff10-37fd-11e8-9f96-4ee558d26d61.png)

**Comment by chaselivingston** [comment]
Also reported in https://github.com/Automattic/jetpack/issues/9234

**Comment by chaselivingston** [comment]
Also reported in 423088-hc

**Comment by DarrenBatesLLC** [comment]
Having the same issue. I had to DEACTIVATE PAGEBUILDER and ALL SiteOrgin plugins in order to be able to add/edit posts/page and customize site.
![screenshot-2018-4-4 edit post smart cities library wordpress](https://user-images.githubusercontent.com/22603916/38317394-9b1cc15e-37f2-11e8-9cb9-2a97da738159.png)

**Comment by Misplon** [comment]
Hi Darren. Another option would be to temporarily deactivate Extra Sidebar
Widgets module in Jetpack Settings.

If you need the Extra Sidebar Widgets you could also roll back Jetpack to
previous version until next version is released.

**Comment by DarrenBatesLLC** [comment]
I need the EXTRA SIDEBAR functionality.  I use DREAMPRESS and I am not sure how to rollback JETPACK to previous version. Can you send instructions or must I contact DREAMPRESS to roll-back?

thanks.






Darren Bates
President/Global Accessibility & Inclusion Strategist

Darren Bates LLC
2407 South Congress Ave, Suite E136
Austin, TX 78704
Mobile/Text: 512.289.3636
Email: DLB@darrenbatesllc.com <mailto:DLB@darrenbatesllc.com>

Website: www.darrenbatesllc.com <http://www.darrenbatesllc.com/> and www.smartcitieslibrary.com/ <http://www.smartcitieslibrary.com/>

Twitter: @DLBLLC <https://twitter.com/DLBLLC> @SmartCitiesL <https://twitter.com/SMARTCITIESL> 
Facebook: darrenbatesllc <http://www.facebook.com/darrenbatesllc/>
Medium: @darrenbatesllc <https://medium.com/@darrenbatesllc/latest>


Recent Blogs:
▪ Adding Accessibility and Inclusion into Austin’s Smart Cities Strategic Roadmap <http://bit.ly/2lswa6V>
▪ Adding Universal Design Techniques to Keep Austin Beautiful <http://bit.ly/2mAoLDL>
▪ Disability: An Upside for Everyone in Unifying Smart City Design <http://bit.ly/2kjdSrc>
▪ Smart Cities Built for Everyone | Innovations in Accessible & Inclusive Urban Design <http://bit.ly/2kjfZeB>
▪ The Secret Sauce of a Successful Smart City <http://bit.ly/2jyWj1X>
▪  <http://www.darrenbatesllc.com/newsroom/a-smart-city-is-a-connnected-city-and-a-connected-city-is-an-inclusive-city>A Smart City is a Connected City, A Connected City is an Inclusive City <http://bit.ly/2kmN1L8>
▪ The Power of Words: Respect, Equality, Diversity and Inclusion <http://bit.ly/2kmJexp>
▪ Top 10 Ways to Market to People with Disabilities and Boost Your ROI <https://www.linkedin.com/today/post/article/20140703000007-11466134-top-10-ways-to-market-to-people-with-disabilities-and-boost-your-roi?trk=mp-author-card>

Building a Culture of Access and Inclusion in the Modern Workplace™


_________

**Comment by oskosk** [comment]
Seems like the problem is generated when Page builder tries to call the `enqueue_admin_scripts()` methods on all widgets available if the method exists. It does not pass any argument to that method call.

Given that some of the widgets may want to take advantage of the `$hook` parameter  (like social icons) and use this class method to be a callback for the `admin_enqueue_scripts` WordPress action, this fails as a Fatal Error on PHP 7.1 and PHP 7.2

cc @Misplon .

**Comment by Misplon** [comment]
@oskosk SiteOrigin is working the issue. Testing fix at the moment.

@DarrenBatesLLC You can use: https://wordpress.org/plugins/wp-rollback/. (This isn't the best place for support though.)

**Comment by oskosk** [comment]
Thanks for the heads-up @Misplon !

By looking at the conflicting code here: https://github.com/Automattic/jetpack/blob/master/modules/widgets/social-icons.php#L48

...It seems that even if SiteOrigin updates its behaviour then this widget won't show up properly there because we're trying to scope down the pages where we will be loading the supporting js for the widget form.

There's an "Add Icon" button on the Social Icons widget form. Which is supposed to behave like this:

![socialiconwidget](https://user-images.githubusercontent.com/746152/38320699-acd75f62-380b-11e8-9e9e-e9b0fead514d.gif)

But then, by testing with updating the Social Icons Widget `enqueue_admin_scripts` method signature to be `function enqueue_admin_scripts( $hook = null )` so to not throw a fatal, I get to see, that the widget form shows broken in PageBuilder:

![socialiconwidget2](https://user-images.githubusercontent.com/746152/38320793-ef08a724-380b-11e8-89df-d4cc05d6a334.gif)

@zinigor @jeherve what do you think about this ?

**Comment by Misplon** [comment]
We’re going to release a fix to prevent the fatal error. Basically, just not calling that function for anything that isn’t a core WP JS widget.

Existing JP widgets not using the new front end admin JS way of doing things should still work as before

We’d love to have new Jetpack widgets working in Page Builder. In order to do that, we’d need a generic way to enqueue the required front end admin scripts.

**Comment by oskosk** [comment]
Thanks @Misplon!

Looks like there was at least one other Jetpack widget that wasn't working properly with Page Builder (The Twitter Timeline widget) because it also checks if we're on the widgets/customizer page before enqueuing JS. This one didn't conflict because the callback it uses for  `admin_enqueue_scripts` is named `admin_scripts` so Page Builder didn't attempt to call it

**Comment by Misplon** [comment]
Awesome, thanks for your effort and the update, it's most appreciated.

**Comment by oskosk** [comment]
SiteOrigin has just release version **2.6.4** of Page Builder, addressing issues like the one reported here. 

Unfortunately, the fix make the Social Icons widget not be fully configurable if done through Page Builder. 

Props to @Misplon for such a rapid reponse.

I'm closing this issue now.
