### ISSUE TITLE
Dashboard: mobile apps advertisement should link to actually download apps 

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack#9241]
Currently:

![image](https://user-images.githubusercontent.com/437258/38368606-b444e654-38b3-11e8-861f-72fc154c9374.png)

The dashboard mobile advertisements link to https://apps.wordpress.com/ which has information about the apps.

Expected:

Link to https://apps.wordpress.com/get which has device-specific links to the apple app store and play store. 

We can also add a `campaign` parameter to the url so we know they're coming from Jetpack dashboard. 

More info p77Llu-9V4-p2

cc @joanrho @jeffgolenski in case you feel up for updating the illustration and making it more inline with the recent support illustration (lighter weight, etc)

**Comment by joanrho** [comment]
@rickybanister I'd be happy to update that. Will add to my list of things to get ready for 6.1.
