### ISSUE TITLE
Console errors with Facebook Page Widget

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#9242]
When the FB page plugin widget is added to a page with 'Show Stream' enabled, I see an error in the console.

#### Steps to reproduce the issue

1. Add Facebook Page Plugin widget to a widget area, with any Facebook page url, and enable 'Show Stream'.
2. View a page that displays the widget and check the console.

#### What I expected

No errors

#### What happened instead

I see the following error in the console:

```
Refused to display 'https://www.facebook.com/xti.php?xt=AZUvI3gorWT0VGeyxQQxDBZSafKa2lE8yX-RyOscXHDOniYcMZkJF5EBS8D-JCZOtuUiaFICrb4Z2Zph_fvp4yoxq-OUWzqCAUvassdlSrnY2QRhridbY4KYE53RNIArCnnN8lhCi5310O3CWnFOlt073vPPocbp6avH9gKtzqN1Dw5tTyo30z2JQMT2aALmJ-DLGJ3zYET-H-n2U_KnktgSgxfWU5Q9UpEXbmcAaupBVudyvflAp8YqzLriGMfV5V2oJv26KXWeUrjMeMLVZWdA_j3gCXPuKWdEun702i7-8f9LCsorCPl9TjhuwO6l5ZPP3VPvA7hM1gfDVOMcTtrVOPOpGIH4AOozyL25zY9kxGNu4LcXRepU13612_2x1903NArZzjvxUVSDvjnobRG_1_JvTH0Rcrso-mCzWn-6tAvXkoBXavnLq21WP0hLy5ein9kvR-SQoHhgYK2uVItwkl2JGt6f99YjBTDXIES1RIHTf6xpqgJtzuDoWasUB-5rpLiA4CbBdq7kA__JqPVGXQfE5bCbSaMVA6ggI1DIxCCFZmor1Hu-DPzxuJJ8s6671RBMd4HJ3ofOq6EgDCBz6fOnF6g0UBozCgLpf6HpH2lpHXb0hNDackgUKegPVPalyt5rBU8TxBclbnQp9eioBVGcKO8oVQOr7fQX0pMx7DeHjoNJRXsb0jxiWqBYOT0sEx09WOkzqe6b5g-lNvm-&isv=1&cts=1522946432&csp' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```

Note: I didn't see the error initially, but when I switched tabs and then went back the error appeared.

Tried several different FB pages.

Reported in 1056889-zen

**Comment by jeherve** [comment]
It seems to happen to other people as well, and I don't think the issue is linked to Jetpack, since the error comes from the iFrame added by Facebook.

I would recommend posting on this Facebook Bug report if this is still happening:
https://developers.facebook.com/bugs/1545343062241109/
