### ISSUE TITLE
The_Neverending_Home_Page::query_time_filter() cause posts missing

### ISSUE THREAD

**Issue by IronGhost63** [Automattic/jetpack#9247]
#### Steps to reproduce the issue
* Publish handful of contents in very short time (like 20 posts between 10:00 to 10:10)
* Implement Infinite scroll and try to load content
#### What I expected
Every posts should get queried
#### What happened instead
Some post went missing

This issue will occurs if you have amount of posts published in same period (like 20 posts between 10:00 to 10:00) which will get conflicted with `paged` argument. I'm not sure how to explain this. so, let's say here is the sql query produced by jetpack for querying page 2 for infinite scroll

```sql
SELECT SQL_CALC_FOUND_ROWS  wp_posts.ID 
FROM wp_posts  
WHERE 1=1  
	AND wp_posts.post_type = 'post' 
	AND ((wp_posts.post_status = 'publish' OR wp_posts.post_status = 'private')) 
	AND wp_posts.post_date < '2018-04-05 21:23:41'  
ORDER BY wp_posts.post_date 
DESC LIMIT 9, 9
```

Let's say I have 12 posts. Infinite scroll render the first page and last post date is `2018-04-05 21:23:41` when It load page 2 it will look for post that's older that `2018-04-05 21:23:41` which sound about right. but then there is `LIMIT 9,9` which mean JetPack will skip the first 9 posts it found in database then grab whatever is left and return as a result. in my case means there is nothing left to return.

btw, here is the workaround for now
```php
add_filter( "infinite_scroll_posts_where", function( $clause, $query, $operator, $last_post_date ){
    return null;
}, 10, 4);
```

**Comment by jeherve** [comment]
Thanks for the report. This issue is currently tracked in #1554. Closing this as duplicate.
