### ISSUE TITLE
API Errors: when filering out all the jetpack tools

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#9249]
#### Steps to reproduce the issue
Add 
`add_filter( 'jetpack_tools_to_include', '__return_empty_array' );`

you get error  when tryingto get back the api.

#### What I expected
for the endpoints to work as expected.

#### What happened instead
Get php error 
`Class 'Jetpack_SEO_Utils' not found`

Related to this fix. https://github.com/Automattic/jetpack/pull/7900

**Comment by uxcitizen** [comment]
WP.com VIP ticket: 76260-z
P2: ﻿﻿p4IuY0-13k-p2

**Comment by jeherve** [comment]
Closing as duplicate of #19511.
