### ISSUE TITLE
Jetpack_Sitemap_Builder: Why do we `die()`?

### ISSUE THREAD

**Issue by jaswrks** [Automattic/jetpack#9254]
Does anyone know why we're calling `die()` [here](https://github.com/Automattic/jetpack/blob/a7e1b2d30917b467960d4b4fca15cae3dabddb26/modules/sitemaps/sitemap-builder.php#L222)?

Calling `die()` seems problematic because `Jetpack_Sitemap_Builder::update_sitemap()` is called on module activation and that method can also be useful in a WP-CLI tool. The problem is, calling `Jetpack_Sitemap_Builder::update_sitemap()` results in script termination when it's done.

So, for example, it's not possible to do something like:

```php
$sitemap_builder = new Jetpack_Sitemap_Builder();
$sitemap_builder->update_sitemap(); // Script dies here.

echo 'Sitemap rebuilt successfully.'; // This never runs.
```

**Comment by zinigor** [comment]
A very good point, I don't see why we should. @nbloomf can you please take a look and tell us if there are any caveats to just `break`-ing here?

**Comment by jaswrks** [comment]
I have a suggested fix for this in https://github.com/Automattic/jetpack/pull/9273
