### ISSUE TITLE
Plans: Plan not refunded automatically when upgrading from yearly to monthly plan

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#9255]
#### Steps to reproduce the issue
1. create new JN site
2. buy a Personal yearly plan - 39USD Payment
3. buy a Premium monthly plan - 9USD Payment

#### What I expected

Since I switching to the lover paid plan I would expect to see negative amount (-30USD) in the last, Premium payment.

#### What happened instead

I have charged for both plans (39USD + 9USD), my Personal plan was canceled, and refund wan't done.

Internal ref: 1074993-zen

**Comment by jeherve** [comment]
Closing as duplicate as this is being tracked internally at 1158-gh-jpop-issues
