### ISSUE TITLE
In Firefox, can not scroll down the long Contact Form

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#9258]
### Steps to reproduce the issue

1. Create a long contact form like this: 

```
[contact-form to="test@hotmail.com"][contact-field label="Name of submitter" type="name" required="1"][contact-field label="Submitter's email address (This will not be published)" type="email" required="1"][contact-field label="Contact phone number of person submitting the event (This will not be published)" type="text" required="1"][contact-field label="Are you a registered UK charity?" type="radio" required="1" options="Yes,No"][contact-field label="Event Title" type="text" required="1"][contact-field label="Cost of event (including any concessions if applicable)" type="textarea" required="1"][contact-field label="Event starts on - Day, Date and year" type="text" required="1"][contact-field label="What time does the event start at?" type="text" required="1"][contact-field label="AM or PM" type="checkbox-multiple" required="1" options="AM,PM"][contact-field label="Event ends on - day, date and year" type="text" required="1"][contact-field label="What time does the event finish at?" type="text" required="1"][contact-field label="am or pm" type="checkbox-multiple" required="1" options="am,pm"][contact-field label="Event description" type="textarea" required="1"][contact-field label="Please confirm the event location" type="radio" required="1" options="Merton,Wandsworth,Kingston upon Thames,Sutton,Surrey,Greater London"][contact-field label="Event address" type="text"][contact-field label="Address line 2" type="text"][contact-field label="City or town" type="text"][contact-field label="Postcode" type="text"][contact-field label="Event website. Provide the event website if applicable. If not applicable, type None." type="text" required="1"][contact-field label="Enter website booking page if available. If not applicable, type None." type="text" required="1"][contact-field label="Any extra information not covered above. If not applicable, type None." type="textarea"][/contact-form]
``` 

2. Open the visual editor in WP Admin on Firefox. 

3. Click the pencil icon and start to edit the form. 

4. I can not scroll down the contact form to see the buttons like "Add Field", "Cancel", and "Update Form". 

5. There is a message in Console. It seems the cause here: **This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!**

![firefox](https://user-images.githubusercontent.com/10045087/38540564-8dee2a1c-3cc6-11e8-9457-0b711adc043c.png)

### What I expected

I can edit the form normally. It is working well on Chrome. 
![chrome](https://user-images.githubusercontent.com/10045087/38540634-c1fab924-3cc6-11e8-8d67-09027f05dfb3.png)

### What happened instead

The issue as I mentioned in the 4th step above. 

### Other notes: 

* Tested with Jetpack 6.0 and Jetpack Bleeding Edge (updated 7 hours ago). 
* Internal tracking: 1074559-zen

**Comment by alisterscott** [comment]
Noticed this happened on Chrome also, but on second attempt (clicking edit again) I could see the buttons, so I can't reproduce consistently:

<img width="1278" alt="cant see buttons when editing" src="https://user-images.githubusercontent.com/128826/39864522-36cf4ff2-548d-11e8-9d45-4aee4e471379.png">
