### ISSUE TITLE
Subscriber email: Images appears not correctly formatted when "Custom" option is used

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#9265]
#### Steps to reproduce the issue

1. create new JN site and connect it
2. add a page with `[jetpack_subscription_form]` shortcode
3. subscribe to new posts
4. create a new post with an image which is resized using custom option: Add image -> Edit icon -> (Display settings dropdown) select Custom size -> change image size
5. Publish post

#### What I expected

Receive an email with a custom sized image, the same size as it shown in the post page

#### What happened instead

Received an email with an image sized to "Medium" size: `https://arab-echidna-361.jurassic.ninja/wp-content/uploads/2018/04/big-brother-poster-205x300.jpg` while the image was resized to 100x147px

`<img>` tag which is included in the email:

```
<img border=3D"0" style=3D"max-width: 100%; height: auto; mar=
gin-bottom: 12px;" data-attachment-id=3D"9" data-permalink=3D"https://arab-=
echidna-361.jurassic.ninja/2018/04/10/custom-size/big-brother-poster/" data=
-orig-file=3D"https://arab-echidna-361.jurassic.ninja/wp-content/uploads/20=
18/04/big-brother-poster.jpg" data-orig-size=3D"1254,1839" data-comments-op=
ened=3D"1" data-image-meta=3D"{..}" data-image-title=3D"big-brot=
her-poster" data-image-description=3D"" data-medium-file=3D"https://arab-ec=
hidna-361.jurassic.ninja/wp-content/uploads/2018/04/big-brother-poster.jpg?=
w=3D205" data-large-file=3D"https://arab-echidna-361.jurassic.ninja/wp-cont=
ent/uploads/2018/04/big-brother-poster.jpg?w=3D698" class=3D"alignnone wp-i=
mage-9" src=3D"https://arab-echidna-361.jurassic.ninja/wp-content/uploads/2=
018/04/big-brother-poster-205x300.jpg" alt=3D"" />
```

same tag but on the post page:

```
<img class="alignnone wp-image-9" src="https://arab-echidna-361.jurassic.ninja/wp-content/uploads/2018/04/big-brother-poster-205x300.jpg" alt="" width="100" height="147" srcset="https://arab-echidna-361.jurassic.ninja/wp-content/uploads/2018/04/big-brother-poster-205x300.jpg 205w, https://arab-echidna-361.jurassic.ninja/wp-content/uploads/2018/04/big-brother-poster-768x1126.jpg 768w, https://arab-echidna-361.jurassic.ninja/wp-content/uploads/2018/04/big-brother-poster-698x1024.jpg 698w, https://arab-echidna-361.jurassic.ninja/wp-content/uploads/2018/04/big-brother-poster.jpg 1254w" sizes="(max-width: 100px) 100vw, 100px">
```

**Comment by jeherve** [comment]
Do you experience similar issues when testing with a WordPress.com site?

**Comment by brbrr** [comment]
I've just tested it on simple WordPress.com site(from wp-admin editor), and the issue is not reproducible there.

There is one more thing which is worth to mention:
Changing image size via "Custom size" option will visually resize an image on WP.com site, but on Jetpack site - visual image size will remain the same.

(WP.com vs Jetpack)
![screencast 2018-04-11 13-05-59](https://user-images.githubusercontent.com/5654161/38610412-6da50550-3d89-11e8-941c-b30def41a5f2.gif)

**Comment by jeherve** [comment]
Thanks for the extra details!
Does this keep happening when you deactivate Photon on the site?

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
