### ISSUE TITLE
Graceful degradation of lazy load

### ISSUE THREAD

**Issue by galbaras** [Automattic/jetpack#9281]
#### Steps to reproduce the issue

1. Disable JavaScript in the browser
2. Load https://www.behappyinlife.com/

#### What I expected

The actual image loaded immediately and looking the same way as when JavaScript is enabled.

#### What happened instead

The placeholder image appears as a square, pushing the real image down or left.

#### Suggestions

1. Use better styling for displaying images when JS is turned off
2. Check for JS in the HEAD and add a class to HTML (or BODY) when available, e.g. js-on
3. Add styling for .js-on to override the no-JS defaults

**Comment by tmmbecker** [comment]
also reported here: https://wordpress.org/support/topic/lazy-images-no-javascript/
