### ISSUE TITLE
Subscription email is received with redundant text in Windows 10 Mail app

### ISSUE THREAD

**Issue by GamesToEnjoy** [Automattic/jetpack#9282]
#### Steps to reproduce the issue
Subscribe to a blog which uses the Jetpack subscription module. Once a new post is published you receive an email.

#### What I expected
An email describing the post without any redundant text in all platforms.

#### What happened instead
I got the subscription email with redundant line of text at the top of the email.
I use Hotmail as my email provider.
I saw this problem only in Windows 10 Mail app. When I open the mail using the browser it appears as excepted. 
The site I subscribed to is [http://kodibeginner.com](url) which I own, and it has WordPress and all the plugins updated to the latest version.

Attached is the screenshot of the email I received as appeared in Windows 10 Mail app with the redundant text emphasized in red:
![bug](https://user-images.githubusercontent.com/38309820/38659934-2d79a4da-3e34-11e8-8bc7-bb8355b541ab.PNG)

**Comment by jeherve** [comment]
Thanks for the report. That is indeed a known issue with our Subscriptions emails, and it impacts both Jetpack sites and WordPress.com sites.

I'll close your issue as this is already tracked internally at 4215-wpcom, but I'll get back to this issue once we have a fix.
