### ISSUE TITLE
Infinite scroll will not display the last set of POSTS_PER_PAGE

### ISSUE THREAD

**Issue by craigtockman** [Automattic/jetpack#9283]
#### Steps to reproduce the issue
1. Choose a category with 26 items.
2. set  'posts_per_page' => 10

#### What I expected
To see all 26 items
#### What happened instead
I only was able to load 20.

**Comment by jeherve** [comment]
Thanks for the report. Could you try to apply the patch from #9256 on your site, and let us know if it solves the issue for you?

**Comment by craigtockman** [comment]
https://academyofideas.com/category/membership-videos-preview/
