### ISSUE TITLE
Installing Jetpack through WooCommerce takes you immediately to WordPress.com

### ISSUE THREAD

**Issue by robertdall** [Automattic/jetpack#9294]
#### Steps to reproduce the issue

While running the setup wizard of WooCommerce I was asked if I wanted to install Jetpack at no time did it say I was going to be transferred to WordPress.com, I said yes I want to install Jetpack.

#### What I expected

I expect Jetpack to be installed and then given the option to connect to WordPress.com for extra goodness and feature, or at very least you are taken to a new tab that open WordPress.com leaving the website and still open on the original tab.

#### What happened instead

After clicking Install button I was immediately taken to WordPress.com. I was not told I would be taken to another site, I was given a new colour scheme and layout different than the layout of the WooCommerce setup wizard. Also if I decided not to connect Jetpack to WordPress.com there was no way to get back to my site and continue my setup wizard, other then using the back button on the browser. 

This has confused a number of users I have seen install this on there own. Only when someone with some experience with both Woo and Jetpack was contacted and explained what was going on did it make some sense. Taking a user from one colour schemed website to another without any information about what is going on completely confuses the user. 

**Please Note:**
I wasn't sure if this was a WooCommerce Ticket or a Jetpack ticket. But since it involved installing Jetpack and it's connection to WordPress.com I thought it would be best here. Please move if I have put it on the wrong repo.

**Disclaimer:**
I  feel this should be mentioned as well, this is not an anti-WordPress.com / Jetpack rant. It's about **wanting to use your product** and connecting your site to WordPress.com but getting constainly confused about what is going on when I am directed to do so. 

If you are going to transfer someone to another website it might be helpful to tell them what is going to happen. Providing easily digestible disclaimer as to why you need to connect to WordPress.com might be a good idea as well in with data sharing disclosure becoming increasing important.

**Comment by kraftbj** [comment]
Over the years, this was fixed at some point along the way. While it redirects to WordPress.com to complete the activation flow, it explains it a bit better and has an exit option.
![2020-08-27 at 5 14 PM](https://user-images.githubusercontent.com/88897/91500298-dda51000-e888-11ea-95c9-11d21b51c1ed.png)
