### ISSUE TITLE
Make the Jetpack content area wider to match with Calypso

### ISSUE THREAD

**Issue by nozomimimi** [Automattic/jetpack#9298]
As part of Jetpack dashboard improvement initiative (p6TEKc-1WA-p2), we need to increase the width of Jetpack content area to match with Calypso.

Originally, the content area was designed to match with narrow Calypso content area, since they made it wider, we should align with them. This will give us more screen estate to work with and will bring peace and prosperity to Jetpack :)

Let me know if you need any design for this!

**Comment by jeffgolenski** [comment]
After further investigation, I'm noticing that Calypso is inconsistent with the way widths are laid out for content areas. Many areas remain at 720px, just like Jetpack in wp-admin, while others are pushed to 1040px.

720px examples:
![screen shot 2018-12-06 at 9 56 38 am](https://user-images.githubusercontent.com/214813/49591824-8127f180-f93d-11e8-94ac-c675abc7148a.png)
![screen shot 2018-12-06 at 9 57 00 am](https://user-images.githubusercontent.com/214813/49591825-8127f180-f93d-11e8-9f55-d136f5096412.png)


1040px examples:
![screen shot 2018-12-06 at 9 57 16 am](https://user-images.githubusercontent.com/214813/49591829-86853c00-f93d-11e8-89e2-eaec41788b12.png)
![screen shot 2018-12-06 at 9 58 03 am](https://user-images.githubusercontent.com/214813/49591830-86853c00-f93d-11e8-96c0-8f343100e452.png)


Most notably, the settings area remains at 720px in calypso - which is the same as within wp-admin. I'm opting to keep it consistent - either keeping as is, or bumping the width in both areas. I like the idea of making it wider:

AFTER In calypso: 
![screen shot 2018-12-06 at 10 00 11 am](https://user-images.githubusercontent.com/214813/49591929-c51af680-f93d-11e8-88be-d307001261e4.png)

AFTER in wp-admin
![screen shot 2018-12-06 at 10 01 28 am](https://user-images.githubusercontent.com/214813/49591993-f398d180-f93d-11e8-91dd-bf1749511471.png)

All this requires is bumping the max-width of the containers from 720px (or 45REM) to 1040px.

**Comment by joanrho** [comment]
@jeffgolenski your mocks LGTM but please ping Calypso teams for their opinion since it will affect their work. I'd imagine the discrepancy bw the container widths was intentional for some reason at some time.

**Comment by jeffgolenski** [comment]
Closing the issue here since the PR takes care of the jetpack side of things. I'll reach out to Calypso teams for their thoughts on that side of things, shortly.

**Comment by joanrho** [comment]
@jeffgolenski Please don't close issues until the PRs that fix them are merged. You can add a line that says `Fixes #1234` to your PR and that command will automatically close the associated Issue.
