### ISSUE TITLE
Search Widget: Headway Theme Incompatibility

### ISSUE THREAD

**Issue by mbhthompson** [Automattic/jetpack#9314]
This issue was reported in a Concierge session and followup is being made in 1086132-zen.

The [Headway](http://headwaythemes.com/) theme has the following line of CSS that hides the sort and filter options when performing a search from the Jetpack Search Widget:

`li.widget_search label, li.widget_search input#searchsubmit { display: none; }`

![screen shot on 2018-04-13 at 14_16_20](https://user-images.githubusercontent.com/27440539/38758741-49d21740-3f27-11e8-9b19-e69f963fc4c9.png)

Adding the following bit of CSS removes that property, but it still doesn't look exactly as it should:

`li.widget_search label { display: block; }`

![screen shot 2018-04-13 at 2 18 52 pm](https://user-images.githubusercontent.com/27440539/38758499-11723386-3f26-11e8-998e-a486e143d55f.png)

Can we get a fix in place for this particular theme? 

cc: @gibrown

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
