### ISSUE TITLE
Feature Request: Kindly support Graphviz

### ISSUE THREAD

**Issue by parthi2929** [Automattic/jetpack#9316]
#### Steps to reproduce the issue
Currently Graphviz is not natively supported by Jetpack.

#### What I expected
Graphviz support (also in markdown mode) with transparent option.

#### What happened instead
I tried using 3rd party but they are not good. 

If possible, kindly use below format to identify and render graphviz.  

```
    ```dot
digraph G {
    A -> B
    B -> C
    B -> D
}
    ```
```

Why? 
This format is from another Atom|VS Code plugin "[Markdown Preview Enhanced](https://shd101wyy.github.io/markdown-preview-enhanced/#/)" which renders latex and diagrams like graphviz all in one platform. If WP or Jetpack supports these, we could directly port without need to transform. We could code and create documentation in IDE like Atom| VS code, and directly paste in wordpress. 

<!--
PLEASE NOTE
- These comments won't show up when you submit the issue.
- Everything is optional, but try to add as many details as possible.
- If requesting a new feature, explain why you'd like to see it added.
- This issue tracker is not for support. If you have questions about Jetpack, you can [start a new thread in the Jetpack support forums](https://wordpress.org/support/plugin/jetpack#new-post), or [send us an email](http://jetpack.com/contact-support/).
- Do not report potential security vulnerabilities here. For responsible disclosure of security issues and to be eligible for our bug bounty program, please submit your report via [the HackerOne portal](https://hackerone.com/automattic).
-->

**Comment by jeherve** [comment]
That's probably not something we will support out of the box, as we would need to start including [the Graphviz library](http://www.graphviz.org/) for everyone using Jetpack's Markdown feature.

I would recommend using a dedicated plugin to add the library to your site, as explained here:
https://wordpress.org/plugins/wp-graphviz/

**Comment by parthi2929** [comment]
The problem is that plugin is not working when Jetpack's markdown mode enabled.

**Comment by jeherve** [comment]
What notation do you use to insert graphs into your posts with that plugin? The plugin builds its own markup that will work if you use the `[wp_graphviz]` shortcode, as suggested here:
https://wordpress.org/plugins/wp-graphviz/

Let me know how that goes.

**Comment by parthi2929** [comment]
yeah, it worked. However due to differences in other formats ([line space issue](https://github.com/Automattic/jetpack/issues/9320)) which I could not solve, I have disabled markdown and visual altogether in Jetpack. 

The markdown editor I use, uses Github style markdown while yours uses PHP Markdown Extra so there are differences, which I have to manually correct. 

This issue could be closed I guess. Due to many tweaks involved, I think I probably missed it.
