### ISSUE TITLE
Markdown tables conversion issue

### ISSUE THREAD

**Issue by parthi2929** [Automattic/jetpack#9319]
#### Steps to reproduce the issue
Try below markdown
```
| Node    | 1 | 2 | 3 | 4 | 5 | 6 |
|---------|---|---|---|---|---|---|
| Visited |`1`| 0 | 0 | 0 | 0 | 0 |
| Queue   |`1`|   |   |   |   |   |
| Print   |   |   |   |   |   |   | 
```
#### What I expected
![2018-04-16_20h06_23](https://user-images.githubusercontent.com/11896263/38815539-d1900b10-41b1-11e8-8fe4-81add8994b54.png)

#### What happened instead
![2018-04-16_20h06_30](https://user-images.githubusercontent.com/11896263/38815551-d8292da8-41b1-11e8-879a-04dfa699ea0b.png)

Can you kindly check and help?

**Comment by jeherve** [comment]
Could you check the generated HTML for that markup, and see what HTML tags surround the `1`?

Thank you.

**Comment by brbrr** [comment]
Hi, @parthi2929 
I wasn't able to reproduce it on my side with both "TwentySeventeen" & "Dara" themes. What theme are you using? Reproduction steps and any other additional info will help us.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
