### ISSUE TITLE
GA module: default to 'Universal' analytics.js instead of legacy ga.js

### ISSUE THREAD

**Issue by rtrevellyan** [Automattic/jetpack#9335]
Re: #9129

Please default to the 'Universal' analytics.js instead of the legacy ga.js. If there's a need to support the legacy ga.js, perhaps enable it via a filter.

> ga.js is a legacy library. If you are starting a new implementation, we recommend you use the latest version of this library, analytics.js. For existing implementations, learn how to migrate from ga.js to analytics.js.

from https://developers.google.com/analytics/devguides/collection/gajs/

**Comment by davemart-in** [comment]
Related internal thread: p58i-9ss-p2

**Comment by jeherve** [comment]
This should now be working properly, as of #17795.
