### ISSUE TITLE
Code fencing not highlighting code

### ISSUE THREAD

**Issue by parthi2929** [Automattic/jetpack#9342]
#### Steps to reproduce the issue
Try code fencing.   
````
```ruby
require 'redcarpet'
markdown = Redcarpet.new("Hello World!")
puts markdown.to_html
```
````

#### What I expected
```ruby
require 'redcarpet'
markdown = Redcarpet.new("Hello World!")
puts markdown.to_html
```

#### What happened instead
![output](https://s9.postimg.cc/wvufxbgen/2018-04-18_16h18_47.png)

Actual page illustrating this issue is [here](https://www.rparthiban.com/articles/misc/test-pad/).

**Comment by jeherve** [comment]
The Markdown feature processes Markdown into HTML on your site; it does not provide syntax highlighting features. If you want syntax highlighting, you will need to use a different plugin.

**Comment by parthi2929** [comment]
But markdown standard supports code fencing with syntax highlighting already? 

Is it possible to switch from default markdown engine to github flavoured one in jetpack? I see that lib is available [here](https://github.com/Automattic/jetpack/tree/master/_inc/lib/markdown), but do not know how to switch. And that gfm supports code fencing with syntax highlight?

**Comment by jeherve** [comment]
> markdown standard supports code fencing with syntax highlighting already?

By default Markdown itself only handles processing Markdown and creating HTML. Syntax highlighting requires an additional library to handle all the colors. [Here is an example](http://prismjs.com/).

> Is it possible to switch from default markdown engine to github flavoured one in jetpack?

Jetpack's Markdown uses that gfm library by default, you don't need to switch.

**Comment by parthi2929** [comment]
Oh Is it not PHP Markdown Extra any more?

**Comment by jeherve** [comment]
We use the GFM parser, as you can see here:
https://github.com/Automattic/jetpack/blob/master/modules/markdown/easy-markdown.php#L344
