### ISSUE TITLE
Photon sucking almost 2 TB of bandwidth

### ISSUE THREAD

**Issue by zcuric** [Automattic/jetpack#9356]
Hi, I have the same problem described here [Photon: Where Is My Bandwidth Going?](https://www.chromosphere.co.uk/2015/11/07/photon-where-is-my-bandwidth-going/).

I resize images on my end, I'm not even using the image resize from photon. 

What is going on? Why does Photon need to fetch the same image so many times? 

Thanks.

**Comment by jeherve** [comment]
Could you contact us via [this form](https://jetpack.com/contact-support/?rel=support) and give us more details about your site, setup, as well as examples of the queries you see in your logs?

I'll close this issue for now, and we can reopen an issue later on in the Photon repo if needed:
https://code.trac.wordpress.org/query?status=accepted&status=assigned&status=new&status=reopened&component=photon&col=id&col=summary&col=status&col=type&col=priority&col=component&col=time&order=priority

Thank you!
