### ISSUE TITLE
Coding Standards: __() concatenation

### ISSUE THREAD

**Issue by jaswrks** [Automattic/jetpack#9363]
I'm seeing things like this as a potential break away from coding standards and [this i18n sniff](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/06f6d5c0f7588601c2823dd7abb7e9022fd658dc/WordPress/Sniffs/WP/I18nSniff.php#L450). This came to my attention when I ran into a problem earlier today in: pxLjZ-4CL-p2

https://github.com/Automattic/jetpack/blob/b9d5b7fe6b486c93f2c8c8e571aed6cd0a2b7ac9/modules/sitemaps/sitemap-builder.php#L120

```
__(
        '-- WARNING: Jetpack can not load necessary XML manipulation libraries. '
        . 'This can happen if XML support in PHP is not enabled on your server. '
        . 'XML support is highly recommended for WordPress and Jetpack, please enable '
        . 'it or contact your hosting provider about it.',
        'jetpack'
),
```

Note the use of concatenation where we should be using a string literal. Any desire to fix this?

**Comment by jeherve** [comment]
Yes, I think it'd be nice to get this changed. 👍
