### ISSUE TITLE
Likes: en.ca Doesn't Exist

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/jetpack#9377]
Steps to reproduce the issue

1. Enable the Likes module.
2. Go to Settings → General.
3. Change the site language to English (Canada).
4. Load a post. Notice the following pop up:

![screen shot on 2018-04-19 at 17_40_06](https://user-images.githubusercontent.com/22805865/39056066-ab5d4744-4483-11e8-883b-89e71643bd73.png)

5. Also a 404 error in the console for the GET request to https://widgets.wp.com/languages/en-ca.json?ver=20171126.

@richardmtl helped to test this one and also got this weird error in the console at one point:

https://s0.wp.com/_static/??/wp-content/js/postmessage.js,/wp-content/js/jed/jed.js,/wp-content/js/wpcom-proxy-request.js,/wp-content/js/likes-rest-nojquery.js?m=20180221

Now change the site language to English (US). No more errors.

Reported here: https://wordpress.org/support/topic/jetpack-plugin-causing-404-error-2/
Similar to #2791

**Comment by jeherve** [comment]
Also in 1115767-zen

**Comment by richardmtl** [comment]
1123868-zen

**Comment by stephhjacq** [comment]
1056460-zen (Woo ticket)

**Comment by sarahcada** [comment]
2919836-hc

Site language: es-AR

**Comment by StefMattana** [comment]
Also in 1133240-zen, site language is en-AU

**Comment by jeherve** [comment]
Also in 3288854-hc

**Comment by sjaved87** [comment]
Another report: 1133443-zen

site language: nl_BE

**Comment by treibalen** [comment]
2129281-hc, site language was en_CA

**Comment by ehti** [comment]
Came across two such Atomic sites as well. :/

**Comment by eduardozulian** [comment]
1133975-zen (Atomic)
Language: en_AU

**Comment by georgestephanis** [comment]
to confirm the language is being parsed by https://wpcom.trac.automattic.com/browser/trunk/widgets.wp.com/languages-404.php

**Comment by aportbury** [comment]
3308571-HC
Site language: EN

**Comment by htdat** [comment]
1996605-hc 
Site Language: en-ca

**Comment by htdat** [comment]
1118635-hc

**Comment by akirk** [comment]
Just to note, the JS file with the `alert()` in it might still be cached on users' computers, so suggesting to them to clear their browser caches can be a step in order to resolve the issue.

**Comment by jesscga** [comment]
1176269-zen
Site language: NB
