### ISSUE TITLE
Activity Log: ensure we are logging menu-related activities for Simple sites

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#9397]
Need to update / test the Sync module for posts to ensure we are logging menu-related activities for simple sites.

**Comment by roccotripaldi** [comment]
Can we verify that menu activities are working as expected?
Can we either get them working properly, or simplify them.
Can we get them working on wordpress.com

**Comment by gititon** [comment]
We are now logging menu related activities on Jetpack and Simple Sites.
