### ISSUE TITLE
jetpack/modules/infinite-scroll/infinity.php Missing Translation

### ISSUE THREAD

**Issue by kmplngj** [Automattic/jetpack#9414]
Line 810: `					$click_handle_text = sprintf( __( 'More %s', 'jetpack' ), $cpt_text );`

It seems the "More %s" is missing in the translation files. So I don't get a german translation.

Thanks for the work!
Jan

**Comment by zinigor** [comment]
Hello Jan! Thanks for letting us know!
Jetpack translations are currently handled as most of the WordPress plugins - by the community. If you would like to help us with that, you can [contribute your translation](https://translate.wordpress.org/projects/wp-plugins/jetpack/dev/de/default?filters%5Bterm%5D=More+%25s&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc). Language packs are updated every once in a while, so after adding the translation and getting it approved, you will see it in the plugin eventually.
