### ISSUE TITLE
Stats: JavaScript Error Loading Stats Script on WooCommerce Product Pages in IE

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/jetpack#9416]
#### Steps to reproduce the issue

1. Open IE
2. Load a WooCommerce product page. The shop page loads fine. 
3. Note the **SCRIPT438: Object doesn't doesn't support property or method `assign` error** for s-201817.js (1,2111) which links to https://stats.wp.com/s-201817.js

I have a test page to use if you need one. 

This seems to prevent all other scripts running on the page. For example, if using the Product Enquiry Pro plugin to add an Enquiry form, the form will not submit properly.

Reported here: 1099958-zen

**Comment by timmyc** [comment]
Thanks for the report @tmmbecker - `Object.assign` isn't supported in any version of IE11 I believe [#](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)

/cc @psealock @greenafrican

**Comment by timmyc** [comment]
@tmmbecker the code that powers this particular feature is actually in a different github repository - I have created an issue for it in that repository: https://github.com/Automattic/analytics/issues/43
