### ISSUE TITLE
Automatic Posting of Posts To Socialmedia Also Posts Woocommerce Products!

### ISSUE THREAD

**Issue by mikebronner** [Automattic/jetpack#9421]
#### Steps to reproduce the issue
- Set up automattic posting to social media in Jetpack settings.
- Add new Woocommerce products.

#### What I expected
- Only actual posts, not products, would be cross-posted.

#### What happened instead
- May thousand products got pushed out to social media, alienating many of our users.

**Comment by jeherve** [comment]
Closing as duplicate of #7316

@mikebronner That is in fact the expected behaviour. You can deactivate this option thanks to the code snippet in #7316
