### ISSUE TITLE
Infinite Scroll: Privacy Policy link missing from footer

### ISSUE THREAD

**Issue by iandunn** [Automattic/jetpack#9435]
WP 4.9.6 is adding an extra link to the footer on bundled themes, see [#43715-core](https://core.trac.wordpress.org/ticket/43715).

If a site has the the infinite footer enabled, though, then it will not appear.

It seems like it might be worth adding similar a similar link to `$credits`, to mimic the default themes, and help users be GDPR-compliant.

#### Steps to reproduce the issue

1. Check out Core `trunk` (or `4.9.6-beta1` once it's available on Tuesday)
1. Enable one of the bundled themes
1. Create a page for the privacy policy text
1. Set that page as the privacy policy page
1. View the site, you'll see the privacy policy link in the footer
1. Enable the Infinite Scroll module and the infinite footer
1. Refresh the front end, and the privacy link will be gone

#### What I expected

The privacy link should remain, since it's important for GDPR compliance.

#### What happened instead

The link is gone, because the infinite footer is hardcoded.

**Comment by laghee** [comment]
Hi, all! I'm a wordpress noob and interested in filing a fix for this. After following the link above and poking around a bit on a local dev installation, it seems like tweaking `default footer()` to something like the following might work:

<img width="450" alt="screenshot 2018-07-11 21 52 00" src="https://user-images.githubusercontent.com/20972610/42596129-e7c63148-8554-11e8-9d69-2a00a74b7c09.png">

I'll work on figuring out php testing tomorrow, but it would be great if someone could tell me whether it looks like I'm on the right track so far. Thanks!

**Comment by zinigor** [comment]
@laghee thanks for working on this! Your code seems to be a good solution, but it's hard to tell without looking at the diff and testing. Would you mind submitting a pull request? You can learn about how to do it here: https://github.com/Automattic/jetpack/blob/master/docs/guides/submit-patch.md

**Comment by laghee** [comment]
@zinigor Will do!
