### ISSUE TITLE
A typo on WP.org page (or readme.txt file )

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#9443]
https://github.com/Automattic/jetpack/blob/master/readme.txt#L24

Current text: 

```
Measure, promote, and earn moment from your site. Jetpack helps you with:
``` 

It should be `money` instead of `moment`. 

From 1127942-zen. 
@jeherve - you may create a PR for this?

**Comment by jeherve** [comment]
> you may create a PR for this?

Sure. #9445
