### ISSUE TITLE
Hook Photon into `wp_get_attachment_url()`

### ISSUE THREAD

**Issue by rase-** [Automattic/jetpack#946]
For wider coverage.

See #523 for some discussion.

**Comment by kraftbj** [comment]
Holistically related to #1250 (use Photon is all the places)

**Comment by zinigor** [comment]
After going through several issues with Core responsive images ( #2919 #3080 ... ) I don't think it's going to work very well to just use Photon for all attachment URLs. Let's handle this feature by feature.
Correct me if I'm wrong.
