### ISSUE TITLE
Shortcodes: Jetpack claims to have googleapps shortcode, but doesn't

### ISSUE THREAD

**Issue by iandunn** [Automattic/jetpack#947]
The Jetpack docs [claim](http://jetpack.me/support/shortcode-embeds/) to support the `[googleapps]` shortcode, and it does exist on WordPress.com, but it isn't bundled with Jetpack.

Either the documentation should be corrected, or the shortcode should be added. I think the latter is preferable, since it's very useful and seems like a good fit for Jetpack.

xref: http://wordpress.org/support/topic/plugin-jetpack-by-wordpresscom-googleapps-shortcode

**Comment by jeherve** [comment]
#5518

**Comment by jeherve** [comment]
Fixed in #5838
