### ISSUE TITLE
CPTs: Add filter to change rewrite rule

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#949]
All CPTs currently in Jetpack have the rewrite arg hardcoded (e.g. `comics`, `portfolio`, etc).

Suggestion: Allow site owners to change the default permalink rewrite via a filter.

Originally requested in http://wordpress.org/support/topic/changing-the-portfolio-url

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/portfolio-projects-folder?replies=1&view=all

**Comment by kraftbj** [comment]
> What about the scenario where this change is created in the theme functions.php file and then the theme is changed?

Perhaps suggesting explicitly against that in the filter's inline docs?

**Comment by richardmtl** [comment]
This came up in 2229159-t

**Comment by steven-klein** [comment]
Any movement on this?  Is there a way to do this programmatically right now?

**Comment by kraftbj** [comment]
@steven-klein No movement yet, but this one has been hanging around too long. Too late to add it to the 3.7 release cycle, so marking it for 3.8.

**Comment by samhotchkiss** [comment]
After an internal discussion, we've decided that we agree with @blobaugh's initial assessment, which is that this has the potential to create many more problems than it solves.

**Comment by jgehrcke** [comment]
Hey Sam. Thanks for the feedback.

In practice, there are situations where a custom URL path segment *really* makes sense. Imagine there is web site providing recipes for cooking. And this website is in a language other than English. It absolutely makes sense to use the portfolio feature for storing and presenting recipes. And in this case it also absolutely makes sense to replace "portfolio" with e.g. "recipes" in the URL, for two reasons:

* search engine optimization
* URL semantics

This is especially advantageous when hot-linking such content, e.g. in an email. We all know that the expressiveness/semantics of URLs are super-important.

So, if the decision is *against* providing this functionality, I at least would love to understand what the technical difficulties are.

I would also implement a hack/workaround as long as there is a way that survives Jetpack updates. But, once again, while there is a link to a "workaround" here in this thread, this link is dead. It would be great if someone could point out how such a workaround should look like.

**Comment by lschuyler** [comment]
This was requested in 2459124-t as well.

**Comment by ChrissiePollock** [comment]
This was requested in 2658138-t as well.

**Comment by jeherve** [comment]
Also suggested here:
https://wordpress.org/support/topic/change-label-in-portfolio-post-type/

**Comment by fuiowwNQgfi8c47r7PEuihgwivfg34ofh** [comment]
JUST ADD THE F%U#(%#@ING ABILITY TO CHANGE THE PORTFOLIO SLUG!! WTF !! REQUESTED BY SO MANY USERS! CAN'T DO ONE BASIC THING! F$#K JETPACK CAN SUCK A ====D

**Comment by seejacobscott** [comment]
Requested in 3235470-t

**Comment by kraftbj** [comment]
Another vote for this would be for internationalization. It would be nice to allow for these URLs to be localized to the site's language.

**Comment by lamdayap** [comment]
suggested here: https://wordpress.org/support/topic/portfolio-blog-archives/

**Comment by bobmatyas** [comment]
Requested here: https://wordpress.org/support/topic/portfolio-projects-name/

**Comment by lakellie** [comment]
Requested in 5873940-zen for internationalization purposes
