### ISSUE TITLE
GDPR compliance: Publicize data and access tokens are not removed on Jetpack plugin disconnect.

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#9493]
When a user currently disconnects a Publicize service, we properly delete the Publicize connection data and Keyring access token from their database tables. However, when a user disconnects the Jetpack plugin from WordPress.com, or disables the Publicize module, any Publicize connection data and tokens will remain. This should happen for GDPR compliance.

Maybe we can use `register_deactivation_hook()` and the `jetpack_deactivate_module_publicize` hook for plugin and module deactivation respectively; we may want to add a `do_action()` call to `Jetpack::disconnect()` for site disconnection (and hook into `jetpack_unlinked_user` too?).

**Comment by kwight** [comment]
A new endpoint and JP file changes shouldn't be necessary any more: https://github.com/Automattic/jetpack/pull/9536#issuecomment-389352958

**Comment by jeherve** [comment]
Closing as this was handled on WordPress.com directly.
