### ISSUE TITLE
Feature request: display full post within the Reader when using the WordPress app.

### ISSUE THREAD

**Issue by cecoates** [Automattic/jetpack#9496]
When viewing a post via the Reader on the Android app, Jetpack sites will only display an excerpt with a "visit site for more" link below the "cut".

WordPress.com posts display in full, so this appears to be specific to using the Reader in the app.

Tested with multiple Jetpack sites on:

Google Pixel XL

WordPress app version 9.8

Android version 8.1.0

#### Steps to reproduce the issue
Follow a site that uses Jetpack in the Reader: https://wordpress.com/following/manage

Open the WordPress app.

Click on the Reader icon.

Browse to a post from the Jetpack site you just followed.

Tap on post. Only an excerpt displays with a "Visit X site for more" link at the bottom.

#### What I expected

To see the full post once you tap on it in the Reader.

#### What happened instead

Only an excerpt displays with a "Visit X site for more" link at the bottom.

**This is how a post from a WordPress.com displays in the Reader on the app:**

![screenshot_20180506-172006](https://user-images.githubusercontent.com/10121835/39678536-2c6863c8-5154-11e8-83fe-0ab357874d97.png)

**This is how the same post displays once you install a plugin to make it a Jetpack site:**

![screenshot_20180506-172330](https://user-images.githubusercontent.com/10121835/39678535-290e6632-5154-11e8-8d1e-20e633a9c3e2.png)

Related ticket:

1048870-zen

**Comment by jeherve** [comment]
For reference, this is now tracked here:
https://github.com/wordpress-mobile/WordPress-Android/issues/7723
