### ISSUE TITLE
All: Lossless compressed images

### ISSUE THREAD

**Issue by qhobbes** [Automattic/jetpack#9498]
#### Steps to reproduce the issue
I used [FileOptimizer](https://nikkhokkho.sourceforge.io/static.php?page=FileOptimizer) (provided free of charge covered by the [GNU Affero General Public License (AGPL)](https://www.gnu.org/licenses/agpl-3.0.en.html) to losslessly compress the GIF, JPEG and PNG files in jetpack.6.1.zip
#### What I expected
Reduction in file size advantages
#### What happened instead
There was a 41,501 byte reduction in overall file (163) size. Examples include jetpack/modules/publicize/assets/connect.gif from 1,681 bytes to 561 bytes (33%) and jetpack/modules/protect.png from 14,439 bytes to 7,155 bytes (49%)

Some files did not compress at all such as jetpack/images/feature-photon-lrg.png (197,234 bytes)
The full zip of the jetpack folder with the changes can be downloaded at https://www.dropbox.com/s/u4zxk5ad08swo1e/jetpack.6.1-compressed_images.zip?dl=0

**Comment by zinigor** [comment]
Hello!

Thank you for your contributions, but sadly we can't accept contributions in the form of zip archives. You can alternatively check out the Jetpack repository locally, apply compression to the files and submit a Pull Request with the newly compressed files. This way we will be able to see the changes, test them, and get them in if they are OK.

To see how you can create a PR, please follow [this guide](https://github.com/Automattic/jetpack/blob/master/docs/guides/submit-patch.md) we have.

Thank you!
