### ISSUE TITLE
Stats for other pages on the same domain

### ISSUE THREAD

**Issue by alper** [Automattic/jetpack#9504]
I have some other pages on the same domain as my Wordpress. Any chance I could use the Jetpack stats on those as well and see everything in one place?

**Comment by jeherve** [comment]
I am afraid that will not be possible. Jetpack Stats store stats per URL, and per WordPress post ID. If you use pages outside of WordPress on your domain, they won't have a post ID and thus can't be stored anywhere in Jetpack stats.

For such cases, I would recommend using a different Stats solution, like Google Analytics.
