### ISSUE TITLE
Activity log: events via filesystem should not default to any user

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#9507]
_"Plugin installed via Filesystem"_ events default to user:

![image](https://user-images.githubusercontent.com/87168/39755742-af2ba83e-52cf-11e8-90d9-e3df20e971ad.png)

These should probably just have "Jetpack" as an actor.

**Comment by roccotripaldi** [comment]
@keoshi - what do you like better for an actor here:

1. The master user ( that's what shows now )
2. A Jetpack actor
3. An "unknown" actor

**Comment by keoshi** [comment]
This might be a silly question but...what does “via filesystem” mean? Is it when I upload something directly via FTP?

As for your question, I do believe there's value in showing the Jetpack actor here. It wasn't performed by Jetpack, but it is Jetpack that is keeping an eye on changes and reporting back these actions.

**Comment by simison** [comment]
>This might be a silly question but...what does “via filesystem” mean? Is it when I upload something directly via FTP?

Please never feel like any questions are silly. :-)

It could be via ftp or locally at the server downloading the zip and extracting it, or any other method that basically doesn't run through WordPress. Basically the new plugin just "appears" in the plugins folder.

If you're not sure what _“via filesystem”_ means, non-technical customers might be even less sure. I'll see if there could be more descriptive alternative: we cannot really tell more accurately how exactly the plugin got updated so it has to be vague.

> It wasn't performed by Jetpack, but it is Jetpack that is keeping an eye on changes and reporting back these actions.

:thumbsup:

**Comment by simison** [comment]
_"Plugin installed via filesystem"_ alternatives:
- Plugin installed from outside WordPress or Jetpack
- Plugin installed via non-WordPress method
- Plugin installed in plugins folder manually

**Comment by keoshi** [comment]
Awesome explanation — thanks @simison !

If that's the case and we can't pinpoint the origin, I'd rather go for something like:

> Plugin installed manually

- Keeps the description short.
- Everyone knows what manually is.
- Even if it's not a manual operation (via CLI?), advanced users will get the wording, I believe.

**Comment by benhuberman** [comment]
I'm with @keoshi here -- I like the simplicity and conciseness of "Plugin installed manually," and unless there's some technical use case it doesn't reasonably cover, I'd vote for that.

**Comment by keoshi** [comment]
@roccotripaldi cleared myself from the assignees list, but let me know where this lives and I'll create a PR.

**Comment by roccotripaldi** [comment]
No need to create a PR @keoshi - i will make one today! thanks for your input on this!

**Comment by roccotripaldi** [comment]
Fix deployed in r-176880-wpcom

**Comment by keoshi** [comment]
Thank you, Rocco!
