### ISSUE TITLE
JITM: conflicts with NextGen Gallery

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#9515]
I have not been able to reproduce the issue yet, but a user reported that when going to NextGen Gallery > Manage Galleries when both Jetpack and NextGen Gallery are active, and only in Safari and Firefox, the page would start continuously reloading this URL:

```
https://example.com/wp-admin/admin.php?page=nggallery-manage-gallery&skipjs%5B0%5D=https%3A%2F%2Fwww.grafphoto.com%2Fwp-content%2Fplugins%2Fjetpack%2F_inc%2Fbuild%2Fjetpack-jitm.min.js&skipjs%5B1%5D=https%3A%2F%2Fwww.grafphoto.com%2Fwp-content%2Fplugins%2Fjetpack%2F_inc%2Fbuild%2Fjetpack-jitm.min.js&skipjs%5B2%5D=https://example.com/wp-content/plugins/jetpack/_inc/build/jetpack-jitm.min.js
```

Disabling JITM fixes the issue.

Reported in 1137717-zen

**Comment by gsmumbo** [comment]
Another case reported in 1295288-zen

**Comment by almoyen** [comment]
Another case: 1611370-zen.

Disabling JITM did not fix the issue.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
