### ISSUE TITLE
Video Sitemap does not include thumbnails

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#9539]
#### Steps to reproduce the issue

Upload a video to the Media Library

#### What I expected

The video sitemap should include the video's featured image as the thumbnail

#### What happened instead

The thumbnail `<video:thumbnail_loc>` is empty

_Update:_ Ref: 1148771-zen

**Comment by gsmumbo** [comment]
Another instance here: 1239427-zen

**Comment by macmanx2** [comment]
This issue is now leading to errors reported in Google's Search Console:

> Invalid URL | This is not a valid URL. Please correct it and resubmit.
> Tag: thumbnail_loc

It seems that Google wants some sort of URL there, since it's reporting the absence of a URL as "not a valid URL."

**Comment by aheckler** [comment]
Another in 1836818-zen

**Comment by aheckler** [comment]
Bumped up one Pri level

**Comment by aheckler** [comment]
IIRC, WP doesn't have a built-in way to just extract a thumbnail from a video, so not sure what we'd do here.

**Comment by macmanx2** [comment]
Yeah, we only have a way to assign a video thumbnail when it's VideoPress. I'm thinking, for non-VideoPress sites, maybe we just provide a generic thumbnail?

**Comment by aheckler** [comment]
I suppose we could use the fallback image as we do for `og:image`:

https://s0.wp.com/i/blank.jpg

Might see if I can make a PR for this in a bit.
