### ISSUE TITLE
Dashboard cards info icon overlapping content

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#9547]
I'm seeing this icon overlap in master: 

![screen shot 2018-05-14 at 8 16 10 am](https://user-images.githubusercontent.com/7129409/39997257-428aa0ce-5750-11e8-83c1-a3b82c01e478.png)

(possibly) introduced in #9410?

**Comment by rickybanister** [comment]
The best temporary fix without rearchitecting the dash cards completely is to add this:

```
.jp-dash-item__content {
    margin-right: 18px;
}
```
