### ISSUE TITLE
Port Related Posts to work with AMP

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#9556]
In https://github.com/Automattic/jetpack/pull/9458 we propose disabling Related Posts as it is broken on AMP sites, primarily due to the reliance on javascript to load the related posts from WPCOM.

This issue was created to track making this features work with AMP.

A fix would be to load, cache and render the related posts area server-side.

**Comment by westonruter** [comment]
I think this needs the `AMP Support` label.

**Comment by westonruter** [comment]
I [tweeted](https://twitter.com/westonruter/status/1045575580031184897) about this in September but I neglected to comment on this issue: I made a compatibility plugin to a subset of get Related Posts to work work in AMP.

You can see it live on this AMP page: https://make.xwp.co/2018/12/01/amp-plugin-release-v1-0-rc4/?amp

![image](https://user-images.githubusercontent.com/134745/51417641-c55d0300-1b33-11e9-9389-865e17e66ef9.png)

Here's the gist that shims AMP support into Jetpack: https://gist.github.com/westonruter/1515ce1bae788e6d52d1a94ddd61fb59

The amount of code would be less if integrated straight into the Related Posts module.

Also, this code assumes AMP pages being served in paired/native modes. Additional logic would be needed for classic mode.

**Comment by htdat** [comment]
2133418-zen

**Comment by htdat** [comment]
2169258-zen

**Comment by gravityrail** [comment]
@westonruter any chance you could review this? https://github.com/Automattic/jetpack/pull/13028
