### ISSUE TITLE
Lazy Images: Make it a part of Jumpstart

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#9567]
Lazy Images is an excellent performance boost for most sites. It should be a part of JumpStart.

**Comment by dereksmart** [comment]
This is super easy, just add `Jumpstart` to the module header `Feature` section.

**Comment by Dec0y-jb** [comment]
Just created a new Pull Request (#9598)

**Comment by Dec0y-jb** [comment]
It looks like the Quick Start Guide will also need to be updated to include "Lazy Images" in the "Jump Start includes" section as well. 

https://jetpack.com/support/quick-start-guide/
