### ISSUE TITLE
Related Posts: Make the label for using thumbnails clearer

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#9568]
In our Related Posts feature, we currently have the following UI in Jetpack/Calypso:

<img width="743" alt="screen shot 2018-05-17 at 10 13 51 am" src="https://user-images.githubusercontent.com/108942/40190027-09579a10-59bb-11e8-909a-0154a7c3445b.png">

and in the Customizer:

<img width="317" alt="screen shot 2018-05-17 at 10 19 10 am" src="https://user-images.githubusercontent.com/108942/40190299-c6dc4162-59bb-11e8-8a90-1ded677cbc46.png">

The "Use a large and visually striking layout" label is relatively unclear, and doesn't really explain what it does. We should change the wording here to be:

"Show a thumbnail image where available"

I chose that wording because we will auto-select images beyond just specified Featured Images if necessary.

This change needs to happen;

- [ ] In Jetpack's Settings UI
- [ ] In the Customizer UI
- [ ] In Calyspo's Settings UI

**Comment by Dec0y-jb** [comment]
I've created a new pull request for this. #9614

**Comment by jeherve** [comment]
Fixed in #9614

**Comment by eliorivero** [comment]
Addressed in Calypso in https://github.com/Automattic/wp-calypso/pull/25313

**Comment by Dec0y-jb** [comment]
@eliorivero - I believe my PR was already merged.

**Comment by eliorivero** [comment]
@Dec0y-jb your PR was for Jetpack, I'm addressing this in Calypso, totally different. There's nothing else you have to do. Thanks.

**Comment by Dec0y-jb** [comment]
@eliorivero - Thanks, I saw the update through my email and thought this was already closed. Thanks again,

Joe
