### ISSUE TITLE
Search: notice visible even when search is activated

### ISSUE THREAD

**Issue by keoshi** [Automattic/jetpack#9576]
I'm seeing this notice despite having JP search already turned on.

Should we detect whether it’s active and display it accordingly?

![image](https://user-images.githubusercontent.com/390760/40234310-466d8d5e-5a9e-11e8-9d7d-36c84367fe94.png)

**Comment by dereksmart** [comment]
cc @gibrown who I think set up this JITM

**Comment by gibrown** [comment]
We should just remove this message entirely. It has been 6 months, doubt this will have that much impact anymore. I'll note to myself to look at messaging again

**Comment by eliorivero** [comment]
Patch removing this JITM in wpcom side opened in D17616-code.

**Comment by eliorivero** [comment]
Fixed and deployed in D17616-code
