### ISSUE TITLE
Docker environment for Jetpack Development fails on Debian 9 "Stretch"

### ISSUE THREAD

**Issue by mdrovdahl** [Automattic/jetpack#9583]
#### Steps to reproduce the issue
Follow install steps on https://github.com/Automattic/jetpack/tree/master/docker

#### What I expected
A locally installed WordPress instance to be available at http://localhost

#### What happened instead
Installation does not complete because the WordPress container cannot access the MySQL container:

after `sudo yarn docker:up`

> jetpack_wordpress | ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
> jetpack_wordpress | Waiting for creating wp-config.php until mysql is ready to receive connections

The MySQL container is running (as verified with `docker ps`) and can be reached with the default credentials in default.env per `mysql -h localhost -P 3306 --protocol=tcp -u wordpress -p`

What might be happening is that the TCP connection is failing and then falling back to the sock connection, which doesn't exist because MySQL isn't running on the host, but in a container.

I haven't thoroughly tested this, but it appears that changing the `MYSQL_HOST=db:3306` environment variable to `MYSQL_HOST=jetpack_mysql:3306` in https://github.com/Automattic/jetpack/blob/docker-add-error-logging-to-tests/docker/default.env#L24 (or a localized `.env` file) and then `sudo yarn docker:clean` and `sudo docker:up` gets it working.

It may be that the default database container name is wrong, is "db" and should be "jetpack_mysql". Or, it could be something else...

**Comment by jeherve** [comment]
cc @simison who's done some great work with Docker for Jetpack lately

**Comment by simison** [comment]
Yay, interesting bug-report! We've been developing this setup with MacOS and done very little testing with other machines yet.

cc @oskosk

**Comment by mdrovdahl** [comment]
Built a fresh environment today and did not encounter this issue. Haven't looked to see if any recent changes resolved it...but, will close the issue now as it's no longer reproducible.
