### ISSUE TITLE
Check for /amp/ suffix when determining is_amp_request

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#9588]
As per @westonruter's [comment](https://github.com/Automattic/jetpack/pull/9458#pullrequestreview-121498378) on the AMP support patch.

> Until Automattic/amp-wp#1148 is implemented, this should also check if the URL path ends in /amp/. Otherwise, AMP URLs on sites with amp theme support like https://make.xwp.co/2018/05/03/wordpress-amp-plugin-0-7-release/amp/ won't get recognized as an AMP request here.

**Comment by westonruter** [comment]
Note that https://github.com/Automattic/amp-wp/issues/1148 has been resolved. Only the `?amp` URL param will be used when `amp` theme support is present.
