### ISSUE TITLE
Subscriptions: missing thumbnail for YouTube playlists

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#9589]
#### Steps to reproduce the issue

1. Enable the Subscriptions feature on your Jetpack site.
2. Subscribe to your site.
3. Create a new post and insert a YouTube playlist, e.g. this URL, on a separate line in the editor:
`https://www.youtube.com/watch?v=s7L2PVdrb_8&start_radio=1&list=RDQM5K8UxGxZZQc`
4. Publish your post.
5. The email you will receive uses a default YouTube thumbnail:

<img width="550" alt="screenshot 2018-05-21 at 11 29 30" src="https://user-images.githubusercontent.com/426388/40300919-eca2c146-5cea-11e8-9052-d02da97d329d.png">

Reported in 1170121-zen

**Comment by htdat** [comment]
Seems to work for me now. Closing.

![image](https://user-images.githubusercontent.com/10045087/48044836-7f450400-e1c0-11e8-9f02-943e2bed1eb9.png)

--- 

from 1539935-zen

**Comment by htdat** [comment]
Hmm... it's not stable. I've tested with the same YouTube link 

> https://www.youtube.com/watch?v=s7L2PVdrb_8&start_radio=1&list=RDQM5K8UxGxZZQc

However, there is no thumbnail: 

![screen shot on 2018-11-07 at 14 47 48](https://user-images.githubusercontent.com/10045087/48117550-221e8080-e29c-11e8-8e9f-8ea028a6bb7e.png)

---- 

> from 1539935-zen

In this ticket, the user used another link type `https://www.youtube.com/playlist?list=PLji-n0mIRjFAFIBKbOd3O6TLLb4arwY9B` 

Then in new post emails, there is no correct thumbnail and this link is converted to https://www.youtube.com/watch?v=videoseries&w=840&h=473

(I tested this on my site and confirmed what this user is reporting).

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
