### ISSUE TITLE
Social Media Icons: need alt attribute on img tags for accessibility

### ISSUE THREAD

**Issue by gillespieza** [Automattic/jetpack#9590]
The Social Media Widget does not output valid images with alt tags for accessibility. For example, the facebook icon outputs as:

`
<img class="facebook-messenger-avatar" src="http://mysite.com/wp-content/plugins/facebook-messenger/frontend/images/facebook-messenger.svg" />
`

**Comment by jeherve** [comment]
Neither the new nor the old versions of Jetpack's Social Icons widget use `img` tags. Here is how the markup should look like on your site:

With the new version of the widget, introduced in Jetpack 6.0:
<img width="994" alt="screenshot 2018-05-21 at 17 07 49" src="https://user-images.githubusercontent.com/426388/40314696-8e6ce7bc-5d19-11e8-8b51-02063bc59293.png">

With the old, now deprecated version of the widget:
<img width="987" alt="screenshot 2018-05-21 at 17 09 31" src="https://user-images.githubusercontent.com/426388/40314802-e4c58632-5d19-11e8-8022-55a4faeb648a.png">

Here is how the 2 widget settings interfaces look like:

<img width="401" alt="screenshot 2018-05-21 at 17 11 41" src="https://user-images.githubusercontent.com/426388/40314857-0ffba750-5d1a-11e8-82d5-803233499f7b.png">

<img width="414" alt="screenshot 2018-05-21 at 17 11 46" src="https://user-images.githubusercontent.com/426388/40314861-13c5780c-5d1a-11e8-92f7-5969a7d45204.png">

If you use a different plugin to add Social Icons to your site, I would recommend that you contact the plugin author directly about this.

I hope this helps!

**Comment by gillespieza** [comment]
Oh I'm so sorry - I am mortified. It was indeed another plugin (which I had completely forgotten about), not Jetpack!
