### ISSUE TITLE
Lazy Images: Layouts using imagesLoaded.js and Masonry.js not working as expected

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/jetpack#9595]
Themes using imageLoaded.js with masonry.js for layouts can end up with gaps and overlaps when Lazy Images are enabled. 

#### Steps to reproduce the issue

1. Activate a theme using Masonry and imagesLoaded JavaScript libraries for layout. From themes on WP.com, one good option is Baskerville 2.
2. Make sure Lazy load images are activated.
3. Make sure you have a number of posts with featured images.
4. Load the blog posts page.

#### What I expected

The posts would be displayed evenly spaced, like here: https://baskerville2demo.wordpress.com/

#### What happened instead

The posts are often further apart, or slightly overlapped. Resizing the browser window will correct the issue. 

On page load (note the gaps, and the overlap in the bottom-right corner):

![](https://cldup.com/ubHg2Wye4t-3000x3000.png)

After resizing the browser: 

![](https://cldup.com/IjNOi9Sblz-3000x3000.png)

Originally reported for the Opti theme here: 

* 2365-wpcom-premium-themes
* Follow-up ticket: 1143441-zen.

**Comment by sdixon194** [comment]
Similar issue on 4582699-hc. User has a theme using masonry.js. When lazy loading images is enabled, no featured images appear at all: 

![screen shot 2018-06-25 at 1 50 06 pm](https://user-images.githubusercontent.com/33553323/41867181-54b6100c-7880-11e8-95f4-d7f76ee912df.png)

Switching themes fixes the issue. 

follow up at 1242521-zen

**Comment by laurelfulford** [comment]
Hi @sdixon194! I'm not sure that's the same issue -- the original report was that the masonry layout didn't lay itself out correctly. This sounds a bit different, because the images aren't showing at all. 

We ran into something like this with one of our premium themes, where JavaScript in the theme was clashing with lazy loading. Looking at their theme's JS, it already includes [its own lazy loading image code](https://empiresportsmedia.com/wp-content/themes/soledad/js/libs-script.min.js?ver=5.3) -- that could be the culprit!

**Comment by krutidugade** [comment]
User reported similar issue here - 5218710-hc

However, I wasn't able to replicate issue on my end but user shared these screenshots -
https://sandeepa953175044.files.wordpress.com/2018/07/homepage1.png
https://sandeepa953175044.files.wordpress.com/2018/07/homepage2.png
https://sandeepa953175044.files.wordpress.com/2018/07/homepage3.png

**Comment by laurelfulford** [comment]
Hi @krutidugade! Only business & self-hosted sites can enable Lazy Load images separately; looking at that user's site, I think they may be experiencing this theme issue, here: https://github.com/Automattic/themes/issues/208

I've moved the above report over there!

**Comment by krutidugade** [comment]
@laurelfulford Thank you, I missed it completely!

**Comment by liviopv** [comment]
Also affecting Spatial: https://wordpress.com/themes/spatial

Original trac ticket: https://wpcom-premium-themes.trac.automattic.com/ticket/2464
User-report: 1369452-zen

**Comment by jesscga** [comment]
Reported again in 1409732-zen, using Baskerville2

**Comment by tmmbecker** [comment]
reported in 1424789-zen in Garfunkel, Penguin GeneratePress with the upgrade and Cenote. Tested and verified to confirm all that I could.

**Comment by liviopv** [comment]
@eliorivero I see you touched this issue in the past, do you know if there are any plans to include a fix in future Jetpack releases?

**Comment by eliorivero** [comment]
Right now there's nothing planned. I'll try to look into this when I have some time.

**Comment by joeboydston** [comment]
Also reported in 1625283-zen with smartblog theme.
cc: @isabellachen

**Comment by mlaetitia** [comment]
Another repport here: 9661791-hc with the Ippo theme . Disabling lazy load worked.

**Comment by rossanafmenezes** [comment]
Similar issue here HC-9796665

**Comment by thefrosty** [comment]
Is there an event triggered in Jetpack's Lazy Load? If so imagesLoaded and/or Masonry can rebuilt itself.

**Comment by isabellachen** [comment]
@thefrosty where does this code go?

**Comment by thefrosty** [comment]
@isabellachen you can put it anywhere you like. If you're theme allows custom JS in the settings page, or if you have access to a custom JS file in a functionality plugin etc.

**Comment by tgglv** [comment]
Actual for the external theme: https://wordpress.org/themes/minimal-grid/

1988452-zen
