### ISSUE TITLE
VideoPress: Make A VideoPress Video Player Plugin

### ISSUE THREAD

**Issue by jobakb** [Automattic/jetpack#9605]

**Comment by jeherve** [comment]
> VideoPress will be able to compete very well with likes of Vimeo if it had a separate plugin to handle posting of videos on the WordPress platform. It would be great if the plugin can enable the option to use a button to add video into a post from the wordpress video library.

I'll close this one as `wontfix` as we have no plans to create a standalone VideoPress plugin right now. We used to have a VideoPress plugin, but chose to stop maintaining that plugin to focus all efforts on Jetpack, that already includes all the features you mention above.

> Would also be great if you can preview the video within the wordpress editor

That's already possible, and works even if you don't use the Jetpack plugin, thanks to [WordPress' oEmbed feature](https://codex.wordpress.org/Embeds). Here is a quick preview in the current version of WordPress:

![screen recording 2018-05-23 at 11 49 am](https://user-images.githubusercontent.com/426388/40417212-84b4046e-5e7f-11e8-8f59-9a924e8fc63d.gif)
