### ISSUE TITLE
Widgets: Cookie & Consents Banner cannot be activated if widgets module is disabled

### ISSUE THREAD

**Issue by joendotcom** [Automattic/jetpack#9626]
### Steps to Reproduce

1. Set up a new site
1. Disable `Extra Sidebar Widgets` module
1. Add Jetpack Premium plan (auto-enables ads)
1. This banner will show:
![screen shot 2018-05-24 at 12 08 12](https://user-images.githubusercontent.com/8905369/40479231-6447ee94-5f4b-11e8-8b20-499c3d393a5d.png)
1. Click the "Add Widget" button

### Expected Result

Can add `Cookies & Consents Banner` widget.

### Actual Result

`Cookies & Consents Banner` is not available because `Extra Sidebar Widgets` module is turned off.

### Workaround

Turn on `Extra Sidebar Widgets` module manually.

#### Reference

1178816-zen, 1145262-zen, 1180246-zen, 1179590-zen

**Comment by jeherve** [comment]
cc @withinboredom; would it be possible to display a different JITM when the module isn't active on the site yet, or not display the JITM at all?

**Comment by joendotcom** [comment]
Can no longer reproduce this issue because the flow has changed:

a) [This banner](https://user-images.githubusercontent.com/8905369/40479231-6447ee94-5f4b-11e8-8b20-499c3d393a5d.png) no longer appears
b) You cannot access the modules list without connecting Jetpack. Which then enables the Extra Sidebar Widgets module by default.

Closing.

**Comment by jeherve** [comment]
I think it should remain open as it's still an issue. One can still have deactivated the Widgets module manually on their own, via the old module list. This particular JITM can still be displayed in some scenarios.

**Comment by chickenn00dle** [comment]
We've got a user with multiple sites affected by this issue here: 2272973-zen

They've been using workaround to resolve issue for new sites.

**Comment by jeherve** [comment]
D31673-code should fix this. @withinboredom I'd appreciate a review on that one.

**Comment by jeherve** [comment]
This has now been fixed.
