### ISSUE TITLE
robots.txt Twitter error not showing cards for sites

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [Automattic/jetpack#9649]
Some blogs are not properly fetching Twitter cards. Reported to us here: #3563460-hc and a couple of HEs have also confirmed this bug.

#### Steps to reproduce the issue
1. Go to https://cards-dev.twitter.com/validator
2. Input a URL like https://nakedpolitics.co.uk/2018/05/24/stop-playing-politics-and-fund-local-government/

#### What I expected
The link is validated and the twitter card shows post details like the featured image and excerpt content.

#### What happened instead
ERROR: Fetching the page failed because it's denied by robots.txt.

**Comment by jeherve** [comment]
It seems to work on my end:

<img width="685" alt="screenshot 2018-05-28 at 10 39 41" src="https://user-images.githubusercontent.com/426388/40605696-7eaed73c-6263-11e8-93da-ea2412244c57.png">

Do you see anything different on your end?

**Comment by oskosk** [comment]
Works for me too. I would paste a screenshot but it's the same as Jeremy's

**Comment by Piyopiyo-Kitsune** [comment]
The issue is resolved for the user for now. I can make sure to check the items in @oskosk 's response going forward.
