### ISSUE TITLE
Widgets: Instagram Screen Reader Text on Screen

### ISSUE THREAD

**Issue by kriskorn** [Automattic/jetpack#9651]
When there is an image in the Instagram widget with a really long description, then the _off-screen_ screen reader text will be shown in the middle of the screen with all the text on top of other elements.

#### Steps to reproduce the issue

1) Connect an Instagram account through the widget
2) Add an image to Instagram that has a really long description

#### What I expected

That only the Instagram image will be shown in the widget area.

#### What happened instead

Some of the text was also shown on the screen, because the CSS code pushes the screen reader text only -1000em's.

Current code:

```
.screen-reader-text {
    position: absolute;
    left: -1000em;
}
```

Code that should fix the current issue and also future issues:

```
.screen-reader-text {
    position: absolute;
    left: -9999em;
}

```

Reported in #187008-zen

**Comment by jeherve** [comment]
The Instagram Widget is not part of Jetpack, so I would recommend creating an issue on wpcom.trac instead.

Thank you!

**Comment by kriskorn** [comment]
Ah...I am not sure how I missed that. Thank you!
