### ISSUE TITLE
photon cropping most pictures uploaded making my woocommerce unbearable to look at.

### ISSUE THREAD

**Issue by LeBlacKK** [Automattic/jetpack#9652]
when activating photon a lot of the pictures on my website become unbearable to look at due to the fact it's using resize instead of fit to resize the images, cropping all product images within woocommerce.

is there any way to force it to use fit instead of resize or maybe add an option to change which transform option it uses.

#### Steps to reproduce the issue
activate photon
#### What I expected
pictures to show up the same way as without photon but faster delivery
#### What happened instead
pictures get cropped making the whole e-commerce section unbearable to look at.

**Comment by jeherve** [comment]
I can't seem to be able to reproduce the issue on my own installation of WooCommerce.

Could you contact us via this contact form and give us some examples of the problem on your site, so we can investigate and try to find out what is happening?
https://jetpack.com/contact-support/?rel=support

Thank you.
