### ISSUE TITLE
Bug: Jetpack Safe Mode Warning when using Cross-Domain

### ISSUE THREAD

**Issue by koconder** [Automattic/jetpack#9653]
#### Steps to reproduce the issue
```
define('WP_SITEURL', $_SERVER['HTTP_HOST']);
define('WP_HOME', $_SERVER['HTTP_HOST']);
```
Say that site1.com and site2.com are mapped to the same vhost on nginx or apache. site1.com is the main site and site2.com is a mirror. When i go to site2.com then visit site1.com i get a warning asking me for safe mode.

#### What I expected
Not to see jetpack de-linked.

#### What happened instead
Constant disconnections from Jetpack

---

Further to the bug, ideally a documentation or support arround disabling Jetpack communication via wp-config.php on site2.com

**Comment by jeherve** [comment]
With such a setup, I would recommend the following:

```php
if ( 'site2.com' === $_SERVER['HTTP_HOST'] ) {
		// Staging mode for Jetpack: https://jetpack.com/support/staging-sites/
        define( 'JETPACK_STAGING_MODE', true );
}
```

That should help!
