### ISSUE TITLE
Contact Form: Add Akismet privacy notice

### ISSUE THREAD

**Issue by KokkieH** [Automattic/jetpack#9654]
As of [version 4.0.4](https://plugins.trac.wordpress.org/browser/akismet/trunk/readme.txt#L52) Akismet now offers an option to display a privacy notice re Akismet's data collection under the comment form.

![thomas_covenant__the_insufferable_ _if_all_else_fails use_a_hammer](https://user-images.githubusercontent.com/11873759/40622239-de5c2616-62a0-11e8-9141-f20df56a0dad.png)

As Akismet also collects information on visitors that submits the Jetpack contact form, can we allow users on self-hosted and WordPress.com sites to display this notice on the form as well?

Requested by a WordPress.com user in pEOpz-kR-p2. Also some discussion in pZbK5-5fb-p2

**Comment by jeherve** [comment]
> can we allow users on self-hosted and WordPress.com sites to display this notice on the form as well?

That's already possible; you can add your own field to any form, like so:

<img width="869" alt="screenshot 2018-05-23 at 15 00 01" src="https://user-images.githubusercontent.com/426388/40627422-3c65cae6-62bf-11e8-870f-ed085746b4c0.png">

One thing could be improved though, and is being tracked in #9623

**Comment by KokkieH** [comment]
This is specifically for the privacy notice added by Akismet, though, not for the site owner's own privacy policy. Can't we make it possible to enable this notice, which already appears in comments, for people who might not have their own complete privacy policy, but would still like to be transparent about the data collected about their visitors?

**Comment by jeherve** [comment]
> Can't we make it possible to enable this notice, which already appears in comments, for people who might not have their own complete privacy policy, but would still like to be transparent about the data collected about their visitors?

Do you mean on WordPress.com sites? We should be able to hook into all forms there, yes. It may be worth tracking this on wpcom.trac, though.

**Comment by KokkieH** [comment]
Fair enough. I'll open an issue there, then.
