### ISSUE TITLE
Stats: Add Links to Full Stats Detail Beneath Static Tables

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/jetpack#9656]
Since detailed stats information is not available in the Stats area of the wp-admin dashboard, it's possible that some users might not realize that they can access more detail in Calypso. 

Can we add a link below those static tables with a message pointing users there? If possible, can we add it here?

![](http://cld.wthms.co/PnZ3P3+)
Image Link: http://cld.wthms.co/PnZ3P3

Something like this for example:

> You can view detailed stats information for any day, week, month or year in the Stats area of the WordPress.com dashboard for your site: https://wordpress.com/stats/day/SITEDOMAIN

From this forum question: https://wordpress.org/support/topic/monthly-referrers-visualization/

**Comment by pranali333** [comment]
I think this is already done:

![]( https://d.pr/i/KXRVvZ+)
Image link:  https://d.pr/i/KXRVvZ

Can we close this ticket now @tmmbecker ?
