### ISSUE TITLE
Request: Change "enable backups" dark pattern attempt

### ISSUE THREAD

**Issue by glasgowshipyard** [Automattic/jetpack#9658]
Friends,

I saw a notice saying "protect your site before making major changes" and a button saying "enable backups"

My thought was "Wow! Jetpack now offer a site backup utility for free accounts????!!!!!"

The answer is obviously, no, you don't. But if sure looks that way by using a button saying "enable" rather than "purchase" or "upgrade".

I feel like Automattic are better than this. Thoughts?

**Comment by withinboredom** [comment]
We are constantly improving our messaging to make sure it is effective, clear and helpful.  We'll take your feedback under consideration, and thank you for being a Jetpack user who cares so much about our product.
