### ISSUE TITLE
Sharing: do not track stats when the Stats feature is disabled #9183

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#9678]
Follow-up to #9183 

We currently add a tracking pixel  when Jetpack is active but we should check if the Stats module is active too:

https://github.com/Automattic/jetpack/blob/6.1/modules/sharedaddy/sharing.js#L102

#### Steps to reproduce the issue
_Will add later_
#### What I expected
_Will add later_
#### What happened instead
_Will add later_

**Comment by dereksmart** [comment]
Fixed in #9664

**Comment by jeherve** [comment]
Reopening as #9664 only fixed Search, not sharing.
