### ISSUE TITLE
Updating to JetPack 6.1.1 changes CDN setting

### ISSUE THREAD

**Issue by mist-01** [Automattic/jetpack#9680]
#### Steps to reproduce the issue
Updating to Jetpack 6.1.1 changed the following setting:
![image](https://user-images.githubusercontent.com/2146048/40932908-802107ce-67f5-11e8-8afc-af84704cb4c1.png)
It was manually disabled, but the update re-enabled the setting. I am not sure what version the plugin was prior to the update.

**Comment by zinigor** [comment]
Thanks for letting us know about that!

We do have a mechanism that reactivates modules that were disabled previously, but only if they were filtered out before, or added to Jetpack in the current release. This CDN setting has been there since the beginning, so it shouldn't have been activated.

Perhaps you have been using some filters that removed CDN from the features?

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. Feel free to comment below if you start experiencing the issue again!

**Comment by Thomas-Fleming** [comment]
I keep experiencing this same issue. It's driving me insane as the CDN does not work! Every time the setting is re-enabled, images stop showing on my site.

**Comment by jeherve** [comment]
@Thomas-Fleming Could you contact us via [this contact form](https://jetpack.com/contact-support/?rel=support) and give us more details about your site? It would be important for us to know:

- If the problem remains when switching to a different theme.
- If you use any plugins that are build to customize the default behaviour of Jetpack.
- If you use caching / performance plugins that have options aimed to customize or enable Jetpack features.
- If the problem remains when you deactivate all plugins but Jetpack.

Once we figure out why the setting does not behave well on your site, we will also be able to look into the deeper problem on your site; the image CDN should work, and if your images break when it is active it means that something is blocking our image CDN from accesing your images. 

Thank you!

**Comment by Thomas-Fleming** [comment]
Tried everything you suggested and still not working. I've just submitted a support request with more details.
