### ISSUE TITLE
Comments: JS errors when "Show Avatars" option is disabled

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#97]
Environment:
Settings->Discussion>Show Avatars is unchecked. Jetpack Comments enabled.

Steps to Repo:
1. Write a comment.
2. Click on one of the social network icons to sign in (tested with Facebook).
3. Cancel login to third-party service.

Expected:
Return to normal comment box, offering name, e-mail, URL.

Results:
The comments box "flickers" as the browser attempts to render the form. The JS console reports an error:
`"Uncaught ReferenceError: Gravatar is not defined ??/wp-content/js/jquery/jquery.autoresize.js,/wp-content/mu-plugins/highlander-comments/script.js?m…:614
jQuery.extend.updateAvatarWithGravatar ??/wp-content/js/jquery/jquery.autoresize.js,/wp-content/mu-plugins/highlander-comments/script.js?m…:614
jQuery.extend.clickGuestTab ??/wp-content/js/jquery/jquery.autoresize.js,/wp-content/mu-plugins/highlander-comments/script.js?m…:599
jQuery.extend.switchAccount ??/wp-content/js/jquery/jquery.autoresize.js,/wp-content/mu-plugins/highlander-comments/script.js?m…:548
jQuery.extend.doExternalCanceled ??/wp-content/js/jquery/jquery.autoresize.js,/wp-content/mu-plugins/highlander-comments/script.js?m…:792
jQuery.extend.pollExternalWindow ??/wp-content/js/jquery/jquery.autoresize.js,/wp-content/mu-plugins/highlander-comments/script.js?m…:638`

**Comment by kraftbj** [comment]
Let's really try to hit this sooner rather than later. I'd hate for this to join the 2-yr club!

**Comment by dereksmart** [comment]
This was fixed in r-135393-wpcom
