### ISSUE TITLE
Stats page in Jetpack 6.2 visually smaller than in previous versions

### ISSUE THREAD

**Issue by mzakariya** [Automattic/jetpack#9700]
#### Steps to reproduce the issue
1. Update to Jetpack 6.2.
2. Visit your site's Stats page.

#### What I expected
1. No changes, as there is nothing documented for this in Jetpack 6.2's changelog. 

![](http://cld.wthms.co/wCe4pa+)
Image Link: http://cld.wthms.co/wCe4pa

#### What happened instead
1. The Stats page is now constrained, and is the same width as the Jetpack Settings page.

![](http://cld.wthms.co/xJkpVJ+)
Image Link: http://cld.wthms.co/xJkpVJ

#### Changes that likely did this
- https://github.com/Automattic/jetpack/pull/9517
- https://github.com/Automattic/jetpack/pull/9518

(edited to add: thank you @kraftbj for finding the two references above)

**Comment by StefMattana** [comment]
Also reported on https://wordpress.org/support/topic/new-update-june-6-site-stats-issue/
And also on 1193049-zen

**Comment by StefMattana** [comment]
Also reported on https://wordpress.org/support/topic/site-stats-difficult-to-read/

**Comment by kraftbj** [comment]
Reclassifying as High. Any changes to viewing stats that is seen as a negative results in high support load.

**Comment by antermoia** [comment]
Kill the patient with the cure.

Please forgive me for being a bit rash here, but this is really a completely unnecessary and, from a user's perspective, absolutely useless "rebranding" to match Jetpack's appearance. There was absolutely nothing wrong with the way the stats looked previously.

Please revert, thanks.

**Comment by kraftbj** [comment]
@antermoia Please see the attached PR #9728 and note that this report is already closed.
