### ISSUE TITLE
WooCommerce: New Order & Product Review notifications

### ISSUE THREAD

**Issue by astralbodies** [Automattic/jetpack#9708]
Jetpack currently supports sending WordPress.com masterbar notifications for new orders and product reviews for some WooCommerce sites that are hosted on the WordPress.com infrastructure. I'd like to have that opened up to any WooCommerce + Jetpack site specifically to help support the upcoming mobile applications. So this request has several pieces:

1. Enable notifications for new orders and product reviews for all sites, not just those on WP.com.
2. If a site isn't hosted on WP.com do not turn on new order and product review notifications by default. (off by default)

I believe product review notifications are simply comment notifications and as such they may already be working for all WooCommerce + Jetpack sites. That may mean also point 2 above isn't possible to have turned off by default as it would affect normal comment notifications.

I'm assigning to @timmyc as we chatted about it today and he said he's take point on this change.

**Comment by timmyc** [comment]
So it looks like `woocommerce_currency_position` is [already being synced](https://github.com/Automattic/jetpack/blob/162b4a30a2b711fa81c9dea6094fcee537bd81c0/sync/class.jetpack-sync-module-woocommerce.php#L174) - I verified on a test site of mine ( non-WPCOM Business site ) and the setting is there in the Replica Store. As such we can close this out.

**Comment by timmyc** [comment]
@astralbodies  I don't think that is really a Jetpack issue though. Since masterbar notifications management is done in WordPress.com - this would be something for Calypso and likely wpcom codebases.

Just checked and I didn't see anything masterbar notif specific in the Jetpack settings interface in wp-admin.
