### ISSUE TITLE
Custom content types setting: verbiage adjustment

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#9710]
**Currently:**
<img width="758" alt="screen shot 2018-06-07 at 5 10 27 pm" src="https://user-images.githubusercontent.com/214813/41126494-b7eaf39a-6a75-11e8-8120-ee2c49851845.png">

**Proposed:**
<img width="771" alt="screen shot 2018-06-07 at 5 12 58 pm" src="https://user-images.githubusercontent.com/214813/41126608-1df0ca48-6a76-11e8-9004-e05822d04309.png">

> Add, organize, and display testimonials on your website. If your theme doesn’t support Jetpack Testimonials, you can manually insert them in your content area or sidebar using a simple shortcode.

> Add, organize, and display portfolios on your website. If your theme doesn’t support Jetpack Portfolios, you can manually insert them in your content area or sidebar using a simple shortcode.

@benhuberman for more recommendations on shortening the description (sorry for the widow!). 

I think it's important to separate the "marketing" description from the implementation description of the actual shortcode, which I've kept below the toggle.

Thoughts? @simison

**Comment by benhuberman** [comment]
For testimonials, how about this (177 chars vs. 195):
> Add testimonials to your website to attract new customers. If your theme doesn’t support Jetpack Testimonials, you can still use a simple shortcode to display them on your site.

This leaves out some details that sounded a bit esoteric for the purpose of a brief intro (e.g. sidebar, content area, etc.). Let me know if you think some of these elements are crucial and I can try to work them back in.

For portfolios, here's a suggested edit (172 vs. 191 chars):
> Use portfolios on your site to showcase your best work. If your theme doesn’t support Jetpack Portfolios, you can still use a simple shortcode to display them on your site.

In both of these settings, I'm really not sure -- which is to say, I highly doubt -- adding the shortcode like that gives a user enough information/orientation on how to actually use the feature. I wonder... would it make more sense to replace with a "Learn more about the [Testimonials/Portfolios] shortcode" message, linked to the proper support doc?
