### ISSUE TITLE
Change log truncated

### ISSUE THREAD

**Issue by galbaras** [Automattic/jetpack#9722]
The change log is only showing the latest version and even that seems way too short.

**Comment by brbrr** [comment]
Hi @galbaras! 
Thanks for your report. What changelog exactly you are referring to? 
In both GitHub releases ([#](https://github.com/Automattic/jetpack/releases)) and Wordpress.org plugins ([#](https://wordpress.org/plugins/jetpack/#developers) I see similar changelog. 
Changelogs of older versions you can find in [changelog.txt](https://github.com/Automattic/jetpack/blob/master/changelog.txt)

**Comment by galbaras** [comment]
I was referring to the wp.org changelog, as well as the readme.txt on Github. They both only show v6.2.1, which is way shorter than any other release.

Also, changelog.txt is showing everything BUT 6.2.1, which means it's incomplete as well.

**Comment by brbrr** [comment]
WP.org changelog is a rendered readme.txt, which contains the latest release. While changelog.txt contains all the previous releases. 

I'm going to close this issue since it isn't an actual bug.

**Comment by galbaras** [comment]
The most recent version is very different from every version before it, which showed the full changelog, or at least a good number of versions prior to the last one, so this one is inconsistent.

If often avoid x.y.0 releases e.g. 6.2), and when x.y.1 (e.g. 6.2.1) comes along, this means that I'm applying the changes from both versions (and sometimes more) and it's important to know what they are.

Please make the wp.org changelog as it was before.

**Comment by jeherve** [comment]
We will now add a link to the full list of past changelogs at the end of the readme, so you can easily get a list of all changelogs for the past releases.
https://github.com/Automattic/jetpack/commit/d7e6ceb2f845da30d0e5978102dd2ffafa68a305

As I mentioned in that commit, we can't really leave too much in the readme.txt file. Doing so would overwhelm translators who would have way more strings to translate for text that not many people look at, and it may also be overwhelming for site owners only looking for information about the last release.

I hope that compromise works for you?

**Comment by galbaras** [comment]
Personally, I don't apply every update, because sometimes they are followed by some security patch or bug fix, introduced by the larger update before them. In such cases, the last release note has one or two items, but what I really need to look at is the bigger change, which is now invisible.

Can I haggle you up to 3?

**Comment by jeherve** [comment]
Including 3 releases' changelogs in the readme is a significant amount of work for translators getting started translating the readme, so it's not ideal.

You will be able to see all previous releases by clicking on the link at the bottom of the readme. Would that work for you?

**Comment by galbaras** [comment]
By the time a new one comes along, would the previous ones not be translated already?

**Comment by jeherve** [comment]
It is true for some languages, but not all. Not every language can keep up and translate every new string every time a new release comes up.
