### ISSUE TITLE
Feature Request: EU GDPR Banner text

### ISSUE THREAD

**Issue by lizkarkoski** [Automattic/jetpack#9727]
This request came to us through the Jetpack forums: 
https://wordpress.org/support/topic/eu-cookie-law-and-gdpr-compliance-cant-alter-banner-text-with-jetpack-6-2/

> I was trying to modify the placeholder text which says “Privacy & Cookies: This site uses cookies. By continuing to use this website, you agree to their use. To find out more, including how to control cookies, see here:”
> 
> It turns out you can’t treat it like a normal editable block of text, delete some words and add others etc.
> But you can type completely new text into the input textarea.
> I guess this is how textareas are designed to work.
> The normal usage of placeholder text is something like “enter your name here” when you would expect to replace the placeholder text completely.

#### Steps to reproduce the issue
1. Start on /wp-admin/widgets.php
2. Add "Cookies & Consents Banner" widget and open it's settings
3. Try to type in "Banner text" field

#### What I expected

Default text in "Banner text" field is editable, so I can add or remove few words from the sentence. 

#### What happened instead

Default text in "Banner text" is acting like a placeholder - any edit will remove the whole text completely.

![screencast 2018-06-11 19-48-01](https://user-images.githubusercontent.com/5654161/41245884-01f4526c-6db2-11e8-97db-fa1f26228af4.gif)

**Comment by jeherve** [comment]
Closing as I can't seem to reproduce this right now.
