### ISSUE TITLE
Related posts category filter not working

### ISSUE THREAD

**Issue by waybis** [Automattic/jetpack#9733]
"Exclude an entire category from ever appearing among Related Posts results"

Does this filter still work?

**Comment by brbrr** [comment]
Hi @waybis 
It should work as explained here: https://jetpack.com/support/related-posts/customize-related-posts/#exclude-cats :)

If you have problems making it work I can suggest you create a topic in support forums here: https://wordpress.org/support/plugin/jetpack/#new-post

I'm going to close it for now. If you think it is a bug, please re-open it(providing more details and reproduction steps'

**Comment by waybis** [comment]
Hi brbrr, thanks for the quick reply, and sorry my bad, its working fine, looks like the excluded category got changed to a default category somewhere along the way.
