### ISSUE TITLE
Theme enhancements settings: verbiage changes

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#9734]
**Currently:**
<img width="745" alt="screen shot 2018-06-12 at 1 39 12 pm" src="https://user-images.githubusercontent.com/214813/41308370-b09f545a-6e49-11e8-9989-892883dd8500.png">

**Proposed:**
<img width="752" alt="screen shot 2018-06-12 at 2 03 41 pm" src="https://user-images.githubusercontent.com/214813/41308421-d53504d6-6e49-11e8-913a-050017019385.png">

Continuing to elaborate on expanding the self-explanatory verbiage, I'm proposing we add the following to these two sections:

> **Infinite scroll:**
> 
> Automatically load more content as the visitor scrolls down a page. Provides a smooth and uninterrupted reading experience for posts and pages with a lot of content.
> 
> _Choose your infinite scroll behavior:_
> 
> o No infinite scroll / adhere to your current theme's behavior
> o Load more content with a "load more" button
> o Automatically load more content as the reader scrolls down

> Mobile theme: 
> 
> The Jetpack Mobile Theme displays your content in a clean, uncluttered interface for visitors on a mobile device. It's lightweight to ensure faster loading times and provides easy readability for visitors on the go. It's only displayed when a mobile device is detected, otherwise your standard WordPress theme will be displayed as usual.

...and for the mobile theme toggles, just some slight enhancements to text:

> o Enable the Jetpack Mobile theme
> 
> o Use excerpts instead of full posts on front page and archive pages
> o Show featured images of posts
> o Show an ad for the WordPress mobile apps in the footer of the mobile theme

**Comment by benhuberman** [comment]
Here are some suggested edits to the copy:
> Infinite scroll:
> Create a smooth, uninterrupted reading experience on your site by loading more content as visitors scroll down a page.

- Question: does it make sense to add that this applies to blog pages, archive pages, etc. -- or is that overkill? 

> Choose the Infinite Scroll option that suits your needs:
>
> o Don't load more content automatically.
> o Add a **Load More** button that visitors can click to see more content.
> o Load more content automatically as a reader scrolls down the page.

- Note: I removed "/ stick with your current theme's behavior" -- it sounded confusing to me to give users two options here, especially if the end result ("no auto-loading") is the same. But maybe there's a nuance I'm missing? If so, let me know and we can work something out.

> Mobile theme
>
> The Jetpack Mobile Theme gives your content a clean, uncluttered look on mobile devices. It loads fast and gives your on-the-go visitors an excellent reading experience. Jetpack uses the mobile theme when we detect a mobile device. On all other screen sizes visitors will see your regular WordPress theme.

**Mobile theme toggles**
> o Enable the Jetpack Mobile Theme
>
> o Show excerpts instead of full posts on your homepage and archive pages
> o Display posts' featured images 
> o Use the mobile theme's footer area to show an ad for the WordPress mobile apps

Here too, changes are mostly around passive voice, streamlining, and some inconsistency around capitalization in feature names.
