### ISSUE TITLE
Post by Email setting: Verbiage and UX enhancements

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#9735]
**Current:**

**Inactive:**
<img width="747" alt="screen shot 2018-06-12 at 2 40 24 pm" src="https://user-images.githubusercontent.com/214813/41310200-e2321020-6e4e-11e8-9a89-558633bfabde.png">

**Active:**
<img width="746" alt="screen shot 2018-06-12 at 2 13 41 pm" src="https://user-images.githubusercontent.com/214813/41309642-55057490-6e4d-11e8-9761-4fb9b310dffd.png">

**Proposed:**

**1) Inactive:**
<img width="755" alt="screen shot 2018-06-12 at 2 23 13 pm" src="https://user-images.githubusercontent.com/214813/41309657-613a0244-6e4d-11e8-80c6-d0884e5ce46f.png">

added description:

> Post by Email is a way of quickly publishing posts on your blog by sending an email. We’ll generate a unique email address for you to send your content to and it will appear on your site!

**2) Active & no email generated yet:**

<img width="764" alt="screen shot 2018-06-12 at 2 26 48 pm" src="https://user-images.githubusercontent.com/214813/41309716-845d4510-6e4d-11e8-8817-0fdd42669b49.png">

When this feature is initially turned on, a customer must generate an email address. Currently, we display an empty text input and a copy button, which are useless until an email is generated. 

I immediately tried to start typing in the empty input. I then realized it was there to display a generated email address, and I had to click the button first. 

I'm proposing we build a little logic, so the text input field and copy button don't display until the customer clicks the "generate email" button

**3) Active & email generated**

Once "generate email is clicked, we'll then display all the necessary elements, like this:

<img width="757" alt="screen shot 2018-06-12 at 2 34 54 pm" src="https://user-images.githubusercontent.com/214813/41309977-24a65c1e-6e4e-11e8-95e7-2e93364f7465.png">

**Comment by jeffgolenski** [comment]
cc'ing the team to double check if this logic makes sense: @MichaelArestad  @joanrho @keoshi 

And @benhuberman for a quick review on the description.

Thanks!

**Comment by MichaelArestad** [comment]
I dig. Make it so!

**Comment by joanrho** [comment]
@jeffgolenski Love it. In the description, can we replace the exclamation point with a period? Other than that, let's do it!

**Comment by keoshi** [comment]
Agree with @joanrho on the exclamation point, but it's perfect otherwise. Ship it!

**Comment by joanrho** [comment]
Sorry, one more grammar nit: can we add a comma between "to" and "and"? So it would read like this:

>Post by Email is a way of quickly publishing posts on your blog by sending an email. We’ll generate a unique email address for you to send your content to, and it will appear on your site.

**Comment by benhuberman** [comment]
A few minor edits to suggest to clarify/streamline/add some warmth:

**Inactive**
> Post by Email is a quick way to publish new posts without visiting your site. We’ll generate a unique email address for you to send your content to, which will then appear on your site just like any other post.

**prompt**
I love the proposed changes to the flow! I suggest making the copy just above the text box (with the generated email address) just a tad clearer, i.e.:
> Send your new posts to this email address:
