### ISSUE TITLE
WooCommerce Analytics: Exit earlier if WC is not present

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#9736]
Currently, if WooCommerce is not installed, we are not bailing out of the Analytics code until after checking the current user a couple of times ( https://github.com/Automattic/jetpack/blob/master/modules/woocommerce-analytics/wp-woocommerce-analytics.php#L58 ).

This is resulting in db calls on every front end page load when logged in that are irrelevant: 
![2018-06-12 at 14 16](https://user-images.githubusercontent.com/88897/41312128-eafbf69c-6e4b-11e8-9678-e3b80420d37f.jpg)

Additionally, it would likely be more performant if we check for a constant or WC function instead of the `active_plugins` array, but I'm less certain about that.

Related to 1190213-zen cc: @snowmads

**Comment by jeremypaavola** [comment]
@kraftbj any news on this one?

**Comment by eliorivero** [comment]
Solved by #10664
