### ISSUE TITLE
Publicize settings: verbiage enhancements

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#9737]
**Currently:**
<img width="755" alt="screen shot 2018-06-12 at 3 04 15 pm" src="https://user-images.githubusercontent.com/214813/41311673-f1412a8e-6e52-11e8-81b2-f926765c7d68.png">

**Proposed:**

**Inactive:**
<img width="759" alt="screen shot 2018-06-12 at 3 10 11 pm" src="https://user-images.githubusercontent.com/214813/41311723-21a8440a-6e53-11e8-8845-2e51c8629601.png">

**Active:**
<img width="755" alt="screen shot 2018-06-12 at 3 10 01 pm" src="https://user-images.githubusercontent.com/214813/41311737-2ce2c75a-6e53-11e8-9f45-492e3c027c1f.png">

Title: change to "Social Media Automation" to match marketing

Description:

> Save time on marketing by connecting your favorite social media networks to your website. When you publish a post, it'll automatically be shared on all your connected accounts.

**Comment by benhuberman** [comment]
I'd reframe this a bit:
> Connect your website to the social media networks you use and share your content across all your social accounts with a single click. When you publish a post, it will appear on all connected accounts.

I wonder if it would make sense to mention that users can choose which networks to push new posts to, or is it overkill in this context?

Also, re: this:
> Title: change to "Social Media Automation" to match marketing

Where is this change visible? On the Jetpack support pages, for example, it's still Publicize all the way. (As it still is on WordPress.com too.)
