### ISSUE TITLE
Sharing buttons settings: verbiage enhancement 

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#9738]
**Current:**

<img width="762" alt="screen shot 2018-06-12 at 3 19 21 pm" src="https://user-images.githubusercontent.com/214813/41312563-5f0aaf48-6e55-11e8-8a35-3c68a6d7bfdf.png">

**Proposed:**

<img width="761" alt="screen shot 2018-06-12 at 3 24 28 pm" src="https://user-images.githubusercontent.com/214813/41312554-56adea2c-6e55-11e8-96d7-9ee1e4750049.png">

description:

> Allow visitors to easily share your content on their favorite social media networks by placing sharing buttons below your post or page content.

toggle description:

> Add sharing buttons to your posts and pages

**Comment by benhuberman** [comment]
Reframing a bit to highlight the value / end goal:

> Sharing buttons are about expanding your reach: when you add them to your content, site visitors can share your posts and pages on their social accounts with a couple of quick clicks.
