### ISSUE TITLE
Like button settings: verbiage enhancements

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#9740]
Current:
<img width="761" alt="screen shot 2018-06-12 at 4 16 27 pm" src="https://user-images.githubusercontent.com/214813/41314925-1a7ca190-6e5c-11e8-9e61-437751d29f2a.png">

Proposed:
<img width="774" alt="screen shot 2018-06-12 at 4 20 51 pm" src="https://user-images.githubusercontent.com/214813/41315142-ab0d69ba-6e5c-11e8-8d6b-561995293740.png">

description:

> Allow visitors to show appreciation for your content by adding like buttons below your post and page content.

toggle desc: 

> Add like buttons to your posts and pages

cc @benhuberman to help alter this content so there's no widow on large screens. gasp!

**Comment by benhuberman** [comment]
I trimmed a bit -- which I _think_ has a good chance of preventing the widow. My sense is that a Like button is so common across platforms we don't need to explain a whole lot, but let me know if you think I went too far:
> When visitors enjoy your content, let them show it with a Like. 

Toggle text looks good, though "Like" needs to be capitalized.
