### ISSUE TITLE
Subscriptions settings: verbiage enhancements

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#9742]
**Current:**
<img width="774" alt="screen shot 2018-06-12 at 4 59 49 pm" src="https://user-images.githubusercontent.com/214813/41317399-13fefe10-6e63-11e8-9887-635dc2a64e84.png">

**Proposed**
<img width="761" alt="screen shot 2018-06-12 at 5 05 55 pm" src="https://user-images.githubusercontent.com/214813/41317406-19af4c8e-6e63-11e8-9b1e-464ee72091f4.png">

**Description:**

> Keep visitors engaged with your website by allowing them to subscribe via email. Every time you write a new post, they'll get it in their inbox.

Toggles:
o Enable subscriptions
o Show a "follow blog" option in the comment form
o Show a "follow comments" option in the comment form

**Comment by benhuberman** [comment]
I'd try to move away from the passive voice and "allow" language here if we can -- for example:
> Keep your audience engaged with email subscriptions. Every time you write a new post, they'll see it in their inbox within seconds.

Reading the toggle options, I wondered what "comment form" is and whether users can easily figure out what it refers to in this context. I'm not sure they can.

**Comment by scottsweb** [comment]
As part of copy sprint 1.0, we made some changes here: #12765

Closing this issue as stale.
