### ISSUE TITLE
Stats settings: verbiage enhancements

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#9745]
Current:
<img width="837" alt="screen shot 2018-06-13 at 10 49 09 am" src="https://user-images.githubusercontent.com/214813/41361919-30423f38-6efe-11e8-8ee6-38f042302a82.png">

Proposed:

<img width="759" alt="screen shot 2018-06-13 at 11 40 38 am" src="https://user-images.githubusercontent.com/214813/41362157-a84c2cbe-6efe-11e8-9841-30805827ee95.png">
<img width="753" alt="screen shot 2018-06-13 at 11 40 23 am" src="https://user-images.githubusercontent.com/214813/41362158-a87f2614-6efe-11e8-8ef6-4638c000c998.png">

Description:

> Get valuable traffic stats and insights about your website, including unique visitors, page views, popular posts & pages, and more! Stats can be viewed inside your Jetpack dashboard, on WordPress.com, and in the free WordPress mobile apps.
> Jetpack is currently collecting statistics of your website...

Just two toggle desc adjustments:
* Put a chart showing 48 hours of views in the admin bar
* description below the second toggle: "The image helps collect stats more accurately, but should work when hidden."

**Comment by benhuberman** [comment]
For the intro copy, how about:
> Track stats and gain insight into your traffic, including unique visitors, page views, and your most popular posts, pages, and topics. You can view stats in your Jetpack dashboard, on WordPress.com, or in the free WordPress mobile apps.

I wondered about this:
> Jetpack is currently collecting statistics of your website...
Is that a statement to let a user know stats are already active/working? I'm not sure what it's supposed to convey so it's hard to suggest an alternative, but some more context might help.

As for the toggle descriptions, I find them potentially confusing. 
For the first one, maybe...
> Include a small chart in your admin bar with a 48-hour traffic snapshot.
For the second, I'm kind of stumped -- what _is_ the stats smiley face image? Is it important enough to get that prime real estate near the top of the stats settings?

I also think there's room to clarify + explain more around user roles and stats -- the copy here is very, very brief/terse. Is that outside the scope of the current work? In case it is, "logged in views" should still be "logged-in views." In case it isn't, I'd think maybe something like...

> Different people might have different official roles [LINK to user roles doc, maybe?] on your website. When they log in to your site, whose page views should we count?

> To have access your site's stats, what official role [LINK to user roles doc, maybe?] should a person have?

Curious to know what you think, @jeffgolenski @simison
