### ISSUE TITLE
Feature Request: add `Highlighted` folder in Comments Dashboard

### ISSUE THREAD

**Issue by StefMattana** [Automattic/jetpack#9746]
A user passed this feature request / feedback on the JP forum here: https://wordpress.org/support/topic/adding-an-extra-button-on-the-comments-panel-or-turning-all-comments-visible/

They'd like to have a brand new folder on the Comments section that gather together all the Highlighted comments:
![highlight](https://user-images.githubusercontent.com/11662998/41365438-4b1541f6-6f31-11e8-9ae4-e49f8f704f65.gif)

They reckon it'd be useful for us (and maybe for other users too): 

> As an administrator feature, it would satisfy more than one purpose, e.g. manually filter unreplied comments or isolate specific ones for whatever reason.

They also proposed a workaround if the addition won't be possible, but I don't know if also the workaround is doable at all.

**Comment by kichlucas** [comment]
Thank you for starting an issue about it. :+1: 

Just adding that the [svg icon](https://github.com/Automattic/gridicons/blob/master/svg-min/gridicons-heart.svg) that I used I got from here. And just replaced there:

![image](https://user-images.githubusercontent.com/40271741/41421044-3a2ccc6a-6fcc-11e8-9afc-e2699f0bae2f.png)

**Comment by brbrr** [comment]
Hey @StefMattana 

I think this Feature Request is more fits in Calypso rather then Jetpack repo.

**Comment by StefMattana** [comment]
Ah, good point! I thought it could have been applied also in the `wp-admin` but was clearly wrong!

@kichlucas I [opened a new issue here in the Calypso repo](https://github.com/Automattic/wp-calypso/issues/25500), feel free to follow it and add any other info as well :)

Closing this for now!
