### ISSUE TITLE
Carousel + Photon doesn't load in Retina/HiDPI images

### ISSUE THREAD

**Issue by ChrisBegley** [Automattic/jetpack#975]
When you have Carousel and Photon active, the "?zoom=2" attribute is only added to the first two images that you view in a gallery on a Retina display. The "?zoom=2" attribute isn't added to anything after the 2nd image.

Steps to Reproduce:
1. Activate Carousel and Photon.
2. Add a gallery of 3 or more high-resolution images.
3. Click on one of the images and view it in the carousel on a Retina display. Notice that only the 1st two images are optimized with the "?zoom=2" attribute. Everything after that isn't.

**Comment by gaurav1984** [comment]
Also requested in 1115020-zen

**Comment by samiff** [comment]
In the upcoming Jetpack 9.9 release the carousel module has been updated. Per https://github.com/Automattic/jetpack/pull/20204 we should be showing higher resolution images on sites with Photon.
