### ISSUE TITLE
Related posts settings: verbiage enhancements

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#9751]
@simison I know there are other issues / PRs floating about that revolve around the related posts settings area. This issue is strictly related to the opening description and 

**Current:**
<img width="764" alt="screen shot 2018-06-13 at 2 58 46 pm" src="https://user-images.githubusercontent.com/214813/41374443-2b58307c-6f21-11e8-881d-9de4f5997e12.png">

**Proposed:**
<img width="765" alt="screen shot 2018-06-13 at 3 47 48 pm" src="https://user-images.githubusercontent.com/214813/41374447-2dc2e23a-6f21-11e8-85df-e14293f6953b.png">

description:

> Keep visitors on your site and keep them engaged by showing them related content at the bottom of each of your posts.

Related issues / PRs:
- https://github.com/Automattic/jetpack/issues/9568
- https://github.com/Automattic/jetpack/pull/9683

**Comment by benhuberman** [comment]
I like the proposed copy, @jeffgolenski! If I were to nitpick, I'd just suggest a couple of minor trims: 
> Keep site visitors engaged by showing them related content at the bottom of each post.

**Comment by scottsweb** [comment]
As part of copy sprint 1.0, we made some changes here: https://github.com/Automattic/jetpack/pull/12765 

Closing this issue as stale.
