### ISSUE TITLE
SEO settings: Verbiage enhancements

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#9754]
**Current:**

**free, personal plans:**
<img width="756" alt="screen shot 2018-06-13 at 4 42 31 pm" src="https://user-images.githubusercontent.com/214813/41377019-cf05d358-6f28-11e8-9c94-671ba9752404.png">

**premium, pro plans:**
<img width="759" alt="screen shot 2018-06-13 at 4 18 21 pm" src="https://user-images.githubusercontent.com/214813/41375904-6ec4ddde-6f25-11e8-89bd-8e14ee520478.png">

**Proposed:**

**free, personal plans:**
<img width="766" alt="screen shot 2018-06-13 at 4 14 46 pm" src="https://user-images.githubusercontent.com/214813/41375946-9a716628-6f25-11e8-8314-70f5f2904ce3.png">

upgrade prompt description:
> Give your ranking a boost with SEO tools in Jetpack Premium or Professional. Learn more.

**premium, pro plans:**
<img width="751" alt="screen shot 2018-06-13 at 4 38 01 pm" src="https://user-images.githubusercontent.com/214813/41376763-30914e28-6f28-11e8-92d6-24fe1689ae0e.png">

CTA description: 
> Configure your SEO settings in your WordPress.com dashboard

description for all plan levels:

> Jetpack SEO tools will give you live previews of what your site homepage and posts look like in popular search engines. Reorder items such as 'Site Name’' and 'Tagline' without having to touch any code.

cc @benhuberman since I kind of just pieced a few sentences together. could use some refinement!

**Comment by benhuberman** [comment]
Let's see...

In the free/personal prompt, I'd either add:
> Give your search ranking a boost with SEO tools in Jetpack Premium or Professional. Learn more.

Or, if that makes it too long, just go with something even shorter:
> Jetpack Premium and Professional include advanced SEO tools. Learn more

For the CTA, could we go with something friendlier than "configure"? E.g.:
> Customize your SEO settings in your WordPress.com dashboard

Or
> Change your SEO preferences in your WordPress.com dashboard

As an aside, do you often call it the "WordPress.com dashboard" in Jetpack? "Dashboard" has been deprecated for quite some time on the WP.com side of things, but I can see why it would be tricky to do here, given that wp-admin is a dashboard, etc.

Finally, for the intro copy, suggested edits:
> Take control of the way search engines represent your site. With Jetpack's SEO tools you can preview how your content will look on popular search engines and change items like your site name and tagline in seconds.

**Comment by eeeeevon13** [comment]
Suggested copy update "Boost your search engine ranking with the powerful SEO tools in Jetpack Premium"  Listing both packages is not needed here, on the plans page it mentions that each package includes the features from the one below. Also, listing them both out adds to the cognitive overload here. Users will not remember all of that by the time they hit checkout.
