### ISSUE TITLE
Traffic: Google Analytics settings copy

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#9755]
**Currently:**

**free, personal plans:**
<img width="755" alt="screen shot 2018-06-13 at 4 56 52 pm" src="https://user-images.githubusercontent.com/214813/41377671-cf11984e-6f2a-11e8-927f-401057424eaa.png">

**Premium, pro plans:**
<img width="764" alt="screen shot 2018-06-13 at 4 50 57 pm" src="https://user-images.githubusercontent.com/214813/41377479-260762ec-6f2a-11e8-8d1c-add93016fe9d.png">

**Proposed:**

**free, personal plans:**
<img width="764" alt="screen shot 2018-06-13 at 4 58 47 pm" src="https://user-images.githubusercontent.com/214813/41377766-16248c8c-6f2b-11e8-95e8-9342cb5ebcc6.png">

Upgrade CTA text:
> Easy Google Analytics integration with Jetpack Premium or Professional.

**Premium, pro plans:**
<img width="758" alt="screen shot 2018-06-13 at 4 53 00 pm" src="https://user-images.githubusercontent.com/214813/41377558-61703958-6f2a-11e8-98ca-f321eff161fb.png">

CTA text:
> Configure your Google Analytics settings in your WordPress.com dashboard

Small change! I'd just like to start to introduce this idea of folks having an additional "WordPress.com dashboard" since many don't understand the relationship with Jetpack and WordPress.com too well.

**Comment by benhuberman** [comment]
For the upsell CTA, I propose:
> Connect your site to Google Analytics in seconds with Jetpack Premium or Professional.

For the paid CTA, I propose:
> Customize your Google Analytics settings in your WordPress.com dashboard

or
> Change your Google Analytics preferences in your WordPress.com dashboard

**Comment by beaulebens** [comment]
I'm just going to cheat and add something on here. When you do this, can you also remove the `p` tag around the main text of this card, which is adding excess margins/padding at the bottom when compared with other cards:

<img width="1151" alt="screen shot 2019-01-11 at 5 13 15 pm" src="https://user-images.githubusercontent.com/108942/51065894-8aebe700-15c4-11e9-8cef-b30ad4994c33.png">

**Comment by scottsweb** [comment]
Hijacking this issue for copy sprint 1.0, we had reached a similar conclusion. cc @obi2020 for any additional thoughts.
