### ISSUE TITLE
Backups and security scanning settings: verbiage adjustments

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#9757]
**Current:**

**loading:**
<img width="753" alt="screen shot 2018-06-13 at 9 24 36 pm" src="https://user-images.githubusercontent.com/214813/41387220-c216331a-6f53-11e8-80f4-d9f5d004895a.png">

**Free plan:**
<img width="753" alt="screen shot 2018-06-13 at 9 22 48 pm" src="https://user-images.githubusercontent.com/214813/41386597-28eae724-6f50-11e8-90f7-4423786ca474.png">

**personal, premium, professional plans:**
<img width="766" alt="screen shot 2018-06-13 at 9 25 01 pm" src="https://user-images.githubusercontent.com/214813/41387210-b63422b4-6f53-11e8-8df9-fcf550075e5c.png">

**Proposed:**

**loading:**
<img width="753" alt="screen shot 2018-06-13 at 9 40 57 pm" src="https://user-images.githubusercontent.com/214813/41386992-8598787c-6f52-11e8-852d-259912125066.png">

**Free plan:**
<img width="781" alt="screen shot 2018-06-13 at 9 37 47 pm" src="https://user-images.githubusercontent.com/214813/41386918-19253086-6f52-11e8-87d9-d0c273316b59.png">

**personal, premium, professional plans:**
<img width="766" alt="screen shot 2018-06-13 at 9 45 35 pm" src="https://user-images.githubusercontent.com/214813/41387103-27f598c0-6f53-11e8-9198-ef2bfb71d0cc.png">

Currently, when a site is "connected" there are two visuals prompts literally displaying the same thing. I'd like to change the second one to be a bit more descriptive and have a direct CTA to view the AL. Currently, if clicked, it'll take them there, so we don't need to change any logic, just the verbiage.

@benhuberman I definitely need some help writing this long description so it flows a little better!

Description
> Jetpack offers world-class website backups and restores along with daily scans of your site which checks for suspicious code and activity. If something goes wrong with your website, we'll be there to make sure it's fixed so you don't have to waste time worrying.

> Your site is regularly being backed up and scanned
> Take a look at the activity on your site in your WordPress.com dashboard

**Comment by simison** [comment]
Pinging also @eliorivero for this one as I think he was working on these parts.

**Comment by scottsweb** [comment]
Couple of concerns with these proposed changes. 

During loading, I think the copy is too long to read in that short amount of time. Terms like `world-class` offer very little context or direction as to why this feature is worth having. 

Due to the age of this issue, I think it is best to close. We will be looking at some of the other older verbiage changes as part of the copy sprint though.
