### ISSUE TITLE
Activity log: add events for ad earning settings

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#9765]
Changes in earning settings such as "Paypal email" and "Who owns this site" should be added to the activity log.

1. Have a Jetpack pro plan
2. Activate wordads from `https://wordpress.com/settings/traffic` (Settings > Traffic > Ads)
3. Go to `https://wordpress.com/ads/settings/SITE` (From the sidebar: Ads > Settings)

![image](https://user-images.githubusercontent.com/87168/41418651-d2c3e52c-6ff8-11e8-8301-7c653a17cb15.png)

These don't seem to be Jetpack-synced currently.

**Comment by gititon** [comment]
Deployed.
