### ISSUE TITLE
Docker: Add some more debug constants

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#9773]
Follow-up of request by @jeherve in #9541

Let's change about Including this constants. 
```
@error_reporting( E_ALL );
@ini_set( 'log_errors', true );
@ini_set( 'log_errors_max_len', '0' );

define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );
define( 'CONCATENATE_SCRIPTS', false );
define( 'SCRIPT_DEBUG', true );
define( 'SAVEQUERIES', true );

```
#### Steps to reproduce the issue

Not an issue

#### What I expected
Not an issue

#### What happened instead
Not an issue

**Comment by oskosk** [comment]
cc @simison @gititon . What do you think ? Would this fit your regular usage ?

**Comment by codestor4** [comment]
> What do you think ? Would this fit your regular usage ?

@oskosk Submitted a PR. Merge if needed :)
