### ISSUE TITLE
Customizer: add WP-Admin/Admin user only warnings for Simple Payments

### ISSUE THREAD

**Issue by rodrigoi** [Automattic/jetpack#9777]
After the changes on #9650, the Simple Payments product no longer show on downgraded sites, neither on the post and pages, nor in the upcoming Widget. There's an opportunity to warn the user on the WP-Admin interface if there are active products. Also, on the site post or page where the product is published.

#### Steps to reproduce the issue

1. Add a Simple Payments Button to a post or page on a Business Site
2. Downgrade the site to Free.
3. Navigate to the post or page where the SP button was added.

#### What I expected

As a site administrator, to see a warning about why the product is no longer showing.

#### What happened instead

The page does not show the SP button.

**Comment by gwwar** [comment]
Trying this out on a downgraded site, I think we'll want this in as soon as possible. The experience feels more like a bug if folks aren't given a reason why something isn't rendering on the customizer / page

**Comment by rodrigoi** [comment]
Review on https://github.com/Automattic/jetpack/pull/9842
