### ISSUE TITLE
Refactor out IS_WPCOM code

### ISSUE THREAD

**Issue by blobaugh** [Automattic/jetpack#978]
There are currently 23 files that include code specific to running on WordPress.com with the `IS_WPCOM` constant. These should be refactored out so nothing wpcom specific is in the code. If wpcom needs to alter the behavior of Jetpack in some manner it should do so through hooks as all other sites are required to do so.

See: https://github.com/Automattic/jetpack/search?q=IS_WPCOM

Please tag commits/pull request with this ticket to keep track.

**Comment by dereksmart** [comment]
This would be nice, but not something that needs to be tracked via an issue.  We will look at it along with other things as we work on code sync.
