### ISSUE TITLE
Add contact form Gutenberg block

### ISSUE THREAD

**Issue by gilcarvalhoTI** [Automattic/jetpack#9784]
It is necessary to create a block for Gutenberg Editor because it does not accept shortcodes.

**Comment by jakilevy** [comment]
was just about to leave a note for this. i'm relying on being able to get some webforms into my page. and i've no clue (yet) how to do this using cf7, ninja forms, gravity forms, or jetpack forms.

**Comment by georgestephanis** [comment]
Currently working on this over in https://github.com/Automattic/jetpack/pull/10256
