### ISSUE TITLE
Jetpack Followers Not Updating

### ISSUE THREAD

**Issue by Midliferevelations** [Automattic/jetpack#9785]
Recently I received an e-mail notifying me I had a new subscriber (www.midliferevelations.com).  I've received these e-mails before and _usually_ the new sub shows up on blog or email followers within a short time.  It's now been over a day and the person has not been added.  I tried to research this myself and got the WP cache plugin, etc. but nothing seems to be working.  I've tried clearing my own cache in chrome as well.  Any help would be appreciated.

#### Steps to reproduce the issue

1. Went to midliferevelations.wordpress.com and migrated the follower to www.midliferevelations.com
1. On wp.com, clicked switch sites and chose the linked midliferevelations.com option and disconnected it (so it no longer appeared under available sites).
1. Returned to Blue Host and wordpress.org and deactivated jetpack.
1. Reactivated jetpack and immediately was asked to reconnect my wp.com account

**Comment by Midliferevelations** [comment]
Anyone?  Thanks

**Comment by brbrr** [comment]
Hi there
> usually the new sub shows up on blog or email followers
To what page exactly you referring to? WP-Admin or Calypso? Have you tried to use another browser?

Please provide reproduction steps so we can try it on our side.

**Comment by Midliferevelations** [comment]
I actually found the problem.  For some reason, they ended up on my old wordpress.com followers.  I ended up disconnecting from jetpack and and old blog and then reconnecting everything and it fixed the problem.

**Comment by brbrr** [comment]
I'm glad that your issue is resolved now. Could you provide reproduction steps, so we could try to reproduce it?

**Comment by Midliferevelations** [comment]
Sure.  
1.  Went to midliferevelations.wordpress.com and migrated the follower to www.midliferevelations.com
2.  On wp.com, clicked switch sites and chose the linked midliferevelations.com option and disconnected it (so it no longer appeared under available sites).
3.  Returned to Blue Host and wordpress.org and deactivated jetpack.
4.  Reactivated jetpack and immediately was asked to reconnect my wp.com account

Hopefully this will fix it going forward; however, if it doesn't I will have to just migrate the followers over.  Next time someone signs up as a follower for my blog at www.midliferevelations.com, I will let you know if it goes to my wordpress.org follower count.

**Comment by tmmbecker** [comment]
That should fix it going forward. You may also want to set the old WordPress.com site to private so that it's removed from search indexes and so that visitors don't stumble upon it accidentally. That will ensure that this definitely doesn't happen again.
