### ISSUE TITLE
Activity log: user email changed & confirmed -events look the same

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#9796]
#### Steps to reproduce the issue

1. Change user email
2. Confirm user email
3. Check the activity log, two events look the same:
    ![image](https://user-images.githubusercontent.com/87168/41593923-54873bca-73ca-11e8-8eb4-b014a5fb723a.png)

#### What I expected

Different events.

**Comment by gititon** [comment]
In progress

**Comment by gititon** [comment]
Merged/deployed.
