### ISSUE TITLE
Twitter Widget: Does not display on Safari 11.1.1

### ISSUE THREAD

**Issue by lizkarkoski** [Automattic/jetpack#9798]
There's a report of the Twitter widget not displaying after updating Jetpack to 6.2.1 on **macOS version 10.13.5 with Safari version 11.1.1.**  Both versions are the latest available. The Twitter widget works on macOS 10.13.5 with Firefox and Chrome browsers. 

Site: http://www.it-must-schwing.de

Forum thread: https://wordpress.org/support/topic/twitter-widget-not-working-for-safari-on-macos/#post-10387321

**Comment by brbrr** [comment]
Hey @lizkarkoski 
Is that issue is reproducible, if so - don't you mind to provide steps to reproduce this issue?

**Comment by jeherve** [comment]
The twitter timeline now appears to work on that site. Closing.
