### ISSUE TITLE
Youtube repsonsive embed add an extra 30px to height

### ISSUE THREAD

**Issue by RavanH** [Automattic/jetpack#9800]
Hi, as seen on line 202 and 206 of modules/shortcodes/youtube.php

`
$h = ceil( ( $w / 16 ) * 9 ) + 30;
`

there is an extra 30 pixels added to the height of the otherwise perfectly fine 16:9 ratio. The other video embed shortcodes, Vimeo and Dailymotion, do not have this extra height.

Why?

**Comment by brbrr** [comment]
Hey @RavanH 
I looked through commit history and it looks like it was initially created like this: https://github.com/Automattic/jetpack/commit/99e10babcb00e4d5f9a8d9d91584f71626fceb2f

@mdawaffe maybe to have some insight on this?

**Comment by mdawaffe** [comment]
@brbrr, Yes you can see some history at r30050-wpcom, r30306-wpcom.

We needed it back in the day to make room for the video chrome. If it's not useful now, we should ditch it.

**Comment by jeherve** [comment]
Fixed in #9801
