### ISSUE TITLE
Pinterest Share Button: No Longer Allows Image Selection

### ISSUE THREAD

**Issue by donalirl** [Automattic/jetpack#9804]
#### Steps to reproduce the issue

1. Create a test post that includes an image in the post body with recommended Pinterest dimensions (735px x any height) [Here's mine.](https://wpdoc20170704.com/2018/06/20/testing-pinterest-sharing/)
2. Also add a featured image to the post.
3. Enable the Pinterest sharing button, and share the post to Pinterest.

#### What I expected

I expected the button to allow the user to choose which image gets pinned with the post, like this: https://cloudup.com/cOTwU_x2c0n

#### What happened instead

The Pinterest button automatically chooses the featured image to be shared as the pinned image. Only if the post does not have a featured image, does the Pinterest-optimized image get pinned.

I suspect something has changed on the Pinterest side of things.

Multiple user reports such as: #4462193-hc #4428071-hc #1095402-zd #4174612-hc

**Comment by mlaetitia** [comment]
Another user report here: #4260333-hc / #244760-zd
Same issue as reported here: the user is no longer given the option to choose which image to share - instead the Featured image is chosen by default.

**Comment by dereksmart** [comment]
This is expected behavior for any Sharing button type other than `Official buttons` setting. 

If "official buttons" setting is set for the sharing buttons, each of the images on the post will have its own pin button *on hover*. This is not the case with any setting other than "official button".

For any setting, using the pin button at the bottom of the post will be "smart" and grab the first/best image for the pin.

If you would like to override this default, you can do so via the `jetpack_sharing_pinterest_widget_type` filter. Example: 

```
add_filter( 'jetpack_sharing_pinterest_widget_type', 'jetpack_pinterest_share_multi_image' );
function jetpack_pinterest_share_multi_image() {
    return 'buttonBookmark';
}
```

Updated three years ago via https://github.com/Automattic/jetpack/commit/888a5aefb7715fe27e2326902e991976c14fbc39

**Comment by donalirl** [comment]
Thank you for this info. I have followed up with the original user from #4462193-hc to let them know this.

**Comment by donalirl** [comment]
Hey @dereksmart. I'm getting some pushback from the original user that prompted this report. Their concerns line up with several other users, as well as my own experience as a Pinterest user so I wanted to add the feedback and continue the discussion here.

**To summarize the issue**: using the Pinterest share button used to allow the sharer to choose the image to pin, in a way similar to this: https://cloudup.com/cOTwU_x2c0n Now, the Pinterest share button forces the sharer to use the _featured_ image of the post. 

>If "official buttons" setting is set for the sharing buttons, each of the images on the post will have its own pin button on hover. This is not the case with any setting other than "official button".

This doesn't address this issue of the sharing button at the bottom of the post allowing the sharer to choose the image. Readers read to the end of a post, and then they click the Pinterest sharing button. It is not normal user behavior to scroll back up to check if there's a hover button on an image.

>For any setting, using the pin button at the bottom of the post will be "smart" and grab the first/best image for the pin.

Pinterest users don't like posting small, horizontal images like the one that's typically in the post's featured image. They want to post long, vertical images, because Pinterest's algorithm scores higher when these sized images are used. For this reason, the Pinterest share button is not being "smart". Using the featured image for other social networks may make sense, but it does not make sense for Pinterest.

>If you would like to override this default, you can do so via the jetpack_sharing_pinterest_widget_type filter.

This sounds like a good solution, but it is not viable for WordPress.com simple sites. Can we implement this on WPcom?

For reference, Pinterest's documentation on buttons is here: https://developers.pinterest.com/docs/widgets/save/ (I found a HTML workaround there that I'll send to the user in the meantime.)

**Comment by jeherve** [comment]
Thanks for the extra details.
 
We have discussed about the possible behaviours of the non-official Pinterest buttons in the past, in #2650.

Feel free to chime in with your remarks there. I'll copy some of your comment above there!

I will now close this issue, as this is discussed elsewhere.
