### ISSUE TITLE
Why can't we see a list of all active modules easily?

### ISSUE THREAD

**Issue by justanotherco** [Automattic/jetpack#9805]
I only want to use Jetpack for the stats module, as such, any other Jetpack module that is active is literally bloat for my site. I know that you can access the full module list by going to:

yoursite.com/wp-admin/admin.php?page=jetpack_modules

But this is very cumbersome to type for new sites. Why is there no easy way to access that page from within Jetpack?

**Comment by brbrr** [comment]
Hi there,

As mentioned on Jetpack [support page](https://jetpack.com/support/control-jetpacks-modules-on-one-page):

As the number of Jetpack modules grew over the years, we made the decision to simplify our interface. We now activate our most useful modules by default upon installation, so those don’t appear in the primary Settings interface.

You can also find the list on Jetpack’s Debug page.

- Go to Jetpack -> Dashboard and scroll to the bottom.
- Click Debug to open the “Jetpack Debugging Center.”
- Click the “Access the full list of Jetpack modules available on your site.” link at the bottom.

**Comment by justanotherco** [comment]
Hey there,

Thanks for the response.

That does make some sense from a developer's view, but surely the fact that the number of modules grew so much is exactly why there _should_ be an obvious and easy way to access the module list page. There is no way a normal user will ever find it and that means their site's performance and experience takes a hit. 

Just one tiny example, by default you get Jetpack's "feedback" custom post type, that just pollutes and complicates the regular user's experience in the admin panel, especially those who will never use it (most of them).

**Comment by kraftbj** [comment]
All in all, in time, "modules" as such will make less sense as distinct elements. We already have a lot of cross-over —— Tiled Galleries requires the Photon CDN to work (dynamic resizing), some other modules have widgets that are part of the Extra Sidebar Widgets suite. 

In the beginning, Jetpack was more akin as a collection of separate plugins utilizing a common connection base. In our evolution, it is becoming more of a set of features that don't always align well to the older model. 

Discussions on what features should be activated automatically, which ones should be part of the "jump start" screen when first connecting, which ones should be off until specifically activated are good topics, but all in all, we're just moving away from modules as a construct for how our features are intertwined. 

If you are spinning up sites, this explanation of the filters we have to determine available or auto-activated features is still accurate -- https://jeremy.hu/customize-the-list-of-modules-available-in-jetpack/ .

I'm going to close this issue as we've previously discussed and decided on having the one-screen option available (with the backdoor mentioned as being the compromise), but it is still open for replies. Thank for you for your feedback and for using Jetpack!
