### ISSUE TITLE
Change "Jetpack by WordPress.com" 

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#9806]
Currently, we're having these texts on WordPress.com and Jetpack.com: 

* https://wordpress.com/log-in/ and somewhelse on WordPress.com, we have this in the footer "Powered by Jetpack."

* https://jetpack.com/ - we have "Powering WordPress.com". 

So I think we should do the same for our plugin page on WP.org https://wordpress.org/plugins/jetpack/ ? 

We may change ""Jetpack by WordPress.com" to  "Jetpack, powering WordPress.com" or something like that :)

**Comment by htdat** [comment]
Closing. Move this to the internal discussion. 
p1HpG7-5gE-p2

**Comment by ShannaNJd2017** [comment]
![20180616_210158](https://user-images.githubusercontent.com/34980506/41806544-b02ed0ec-7685-11e8-87c4-c65a86d27845.jpg)
