### ISSUE TITLE
Comments: Moderated comments not displayed after WP 4.9.6

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/jetpack#9808]
**Steps to reproduce**: Follow the steps below to reproduce the issue. 

- Create a self-hosted WordPress (WordPress.org) site
- Install and activate Jetpack
- Enable Jetpack comments
- Publish a post and submit a comment on that post

**What is expected:** Comment is submitted, with a notice that it's pending moderation (if required) or submitted with approval 

**What happens instead:** Page refreshes and the entered comment is nowhere to be seen

**Comment by kraftbj** [comment]
In 4.9.6, WordPress added a new checkbox in the default comment form to obtain consent to place a cookie for the site with information regarding the commenter name, email, etc. This data is generally used to make it easier for a returning commenter to leave a comment without having to re-enter the same information.

Additionally, WordPress uses this cookie to know what unapproved comments should be left on a site.

We would need to add a new arg submitted from `jetpack.worpress.com/jetpack-comment `to the site's `wp-comments-post.php` of `wp-comment-cookies-consent` (any value, WP is just checking that it is set). Would need to do that in `mu-plugins/jetpack/class.jetpack-renderer.php` to add the checkbox and process it properly.

In terms of what is actually happening, `wp_list_comment` is calling `wp_get_current_commenter` for logged-out users to determine the author. That function pulls the cookie. If the cookie is present, then unapproved comments from that commenter are displayed with the moderation comment.

I *think* this can be totally done outside of a Jetpack release, but tagging it for the next release to get eyes and triage.

**Comment by mdawaffe** [comment]
We can't fix this very robustly with just a WP.com change. See proposed Jetpack changes at #9828.

That PR fixes the issue for those that opt-in. For those that do not opt-in, the bad UX remains (no feedback about the newly submitted comment). Core also has the same bad UX in this case: https://core.trac.wordpress.org/ticket/43857

We might be able to fix the non-opt-in bad UX in Jetpack separately, but the above PR does not attempt to.
