### ISSUE TITLE
Markdown: Remove usage of $HTTP_RAW_POST_DATA

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#9818]
`Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0; Use php://input instead` is the final issue left to resolve #4346, which itself is the final step to resolve.

I'm opening this as a separate issue so we can close out 4346 to focus on the last actionable item from that conversation.

The only usage is all within one function within /modules/markdown/easy-markdown.php.

**Comment by codestor4** [comment]
> The only usage is all within one function within /modules/markdown/easy-markdown.php.

This seems to be fixed in here: https://github.com/Automattic/jetpack/pull/9905

Here's a comment by Igor on the specific changes relevant to this issue: 
https://github.com/Automattic/jetpack/pull/9905#discussion_r203167927

I'm closing this issue for now! If I'm wrong, reopen and let me know :)
