### ISSUE TITLE
Activity Log: add "wp.com SSO" settings to the Activity log

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#9820]
Add missing SSO setting events to the Activity Log:
- `jetpack_sso_require_two_step` (_"Require accounts to use WordPress.com Two-Step Authentication"_)
- `jetpack_sso_match_by_email` (_"Match accounts using email addresses"_)

```
Sync action: 'added_option'
Array
(
    [0] => jetpack_sso_require_two_step
    [1] => 1
)

Sync action: 'updated_option'
Array
(
    [0] => jetpack_sso_require_two_step
    [1] => 1
    [2] =>
)
```

`jetpack_sso_match_by_email` doesn't seem to be synced from Jetpack currently, PR: https://github.com/Automattic/jetpack/pull/9821

From wp-admin's Jetpack settings Security > "WordPress.com log in"

![image](https://user-images.githubusercontent.com/87168/41909257-3b327344-794f-11e8-8443-3ef815a231b7.png)

**Comment by gititon** [comment]
Implemented and deployed.
