### ISSUE TITLE
Lazy Loaded images hide featured images in no-JS mode.

### ISSUE THREAD

**Issue by zinigor** [Automattic/jetpack#9827]
#### Steps to reproduce the issue
1. Turn on Lazy Loading of images.
2. Visit the site where you can see at least one post with a featured image (I tested on Twenty Fifteen).
3. Disable JS.

#### What I expected
Featured images should be displayed as well as all other content images.

#### What happened instead
Featured images are replaced with a transparent image, and not loaded.

cc @ebinnion because this is a follow-up to #9780

**Comment by zinigor** [comment]
It looks like not only Featured Images are affected by disabled JS and enabled Lazy Images. See p8oabR-fb for more details.

**Comment by ebinnion** [comment]
From what I can tell, the two reports here seem to have the gallery in common. So, adding a note that we'll need to test lazy images in the carousel with no js.

**Comment by damiannep** [comment]
#1670263-zen 
This seems to happen with the Ovation theme for example. I could replicate on my own site that featured images do not show up when that theme is active on blog posts pages nor single post pages with Lazy Load activated.

**Comment by arunsathiya** [comment]
1832526-zen Same as Damianne's comment above!

**Comment by TimBroddin** [comment]
5528193-zd-woothemes
I found a related issue with the Rowling theme, Safari and the site logo not loading
