### ISSUE TITLE
Subscriptions: Improve the error message when an email has too many pending subscriptions

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#9843]
#### Steps to reproduce the issue

1. Try to subscribe some WordPress.com or Jetpack sites
2. At one point, it displays the message "There was an error when subscribing. Please try again." 
3. There is no subscription email sent. 

#### What I expected

A better message to explain for this case. For example: 

> You're had some pending subscriptions. To resolve this issue, please go to https://subscribe.wordpress.com/

#### What happened instead

A too generic message, then users and website owners have no idea to deal with it. 
Then that generates a bunch of support interactions.

#### Notes

Internal refs: 1136-gh-jpop-issues, 1554-gh-jpop-issues, 1037-gh-jpop-issues, 1243485-zen, 1220502-zen. 

A similar issue was fixed and improved in the past #2007

cc @bikedorkjon :)

**Comment by htdat** [comment]
1266442-zen

**Comment by tmmbecker** [comment]
1265653-zen

**Comment by tmmbecker** [comment]
similar to #2278. seems we could close this one in favor of that. What do you think @htdat ?

**Comment by htdat** [comment]
Yeah, thanks Tracy. I am closing this one.
