### ISSUE TITLE
Activating JetPack gave me a fatal error on my multisite

### ISSUE THREAD

**Issue by benvaassen** [Automattic/jetpack#9875]
#### Steps to reproduce the issue
I'm not really sure if this is easily reproducible. This happened on a multisite and the plugins were not network activated. I'll provide the steps I took: 
1. Install Jetpack and activate it
2. Set it up with the default settings
3. Install the[ Mark it Down WordPress](https://wordpress.org/plugins/mark-it-down-wp/) plugin and activate it (even though it only has less than 10 active installs and hasn't been updated in the last year). 
4. See a warning appear that Mark it Down is already included in Jetpack
5. Disable Jetpack
6. Go to Settings -> Writing -> Enable Markdown
7. Create a new post and use markdown
8. Go to plugins and deactivate Mark it Down. 
9. Enable Jetpack.

#### What I expected
I expected Jetpack to activate without throwing a fatal error on my whole multisite.

#### What happened instead
Instead I got a fatal error _Fatal error: Class 'Jetpack_Simple_Payments' not found in /.../.../.../wp-content/plugins/jetpack/modules/widgets/simple-payments.php on line 479_ and I'm unable to access any post/page on my multisite. The fatal error happens on the entire multiste: 
<img width="1147" alt="fatalerror" src="https://user-images.githubusercontent.com/11910661/42367089-4ddf7aee-8103-11e8-9426-df2360c97cad.png">

**Comment by brbrr** [comment]
Hi @benvaassen 
Thanks for the report! This issue is known and should be fixed in next release: #9871

**Comment by benvaassen** [comment]
Awesome! I searched for similar issues, but couldn't find one :-) thanks for letting me know.

**Comment by taupecat** [comment]
I have a multisite install, and this broke on the two subsites that didn't have Jetpack activated (the plugin itself was network activated, but two of the subsites hadn't been configured).

I downgraded to 6.2.1, activated the two remaining subsites, then upgraded back to 6.3.2 and now all the subsites are working fine.

Really annoying. Took me 2 hours to work through this.
