### ISSUE TITLE
Jetpack 6.3.2 breaks image's "aligncenter" when enabling Lazy Images module

### ISSUE THREAD

**Issue by leandroprz** [Automattic/jetpack#9879]
#### Steps to reproduce the issue

1. Update to v6.3.2 and enable Lazy Images module.
2. Go to a post with an image with "alingcenter" class. It should be centered but it isn't.

#### What I expected

I expected the image to be centered.

#### What happened instead

The image is not centered. You can check it here: https://leandroperez.com.ar/blog/como-saber-la-cantidad-de-disparos-de-tu-camara/

**Comment by brentlogan** [comment]
I had a similar issue with some images I wanted centered on my site. I believe it's due to the following CSS that was recently added:

    .jetpack-lazy-images-js .jetpack-lazy-image {
        display: inline-block;
    }

**Comment by htdat** [comment]
FYI. This issue is handled here https://github.com/Automattic/jetpack/pull/9872
