### ISSUE TITLE
Genericons: Fix google-plus-alt SVG

### ISSUE THREAD

**Issue by andpiazza** [Automattic/jetpack#9880]
#### Steps to reproduce the issue
Genericons SVG and TTF file for Google Plus Alt icon (\f218) is the same for Google Plus icon is (\f206)

#### What I expected
Google Plus Alt icon (\f218) to be different from Google Plus icon is (\f206)

#### What happened instead
Google Plus Alt icon (\f218) to the same as Google Plus icon is (\f206)

**Comment by jeherve** [comment]
Thanks for the report. Since Genericons are maintained in a different repository, would you mind opening that issue here instead?
https://github.com/Automattic/genericons/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen

Thank you!
