### ISSUE TITLE
Lazy images: Images not loading in RSS feeds

### ISSUE THREAD

**Issue by scottsweb** [Automattic/jetpack#9886]
#### Steps to reproduce the issue

1. Enable lazy images
2. Subscribe via RSS
3. Images fail to load in feeds

#### What I expected

Images load normally.

#### What happened instead

Images do not load

I have not fully tested this bug yet but it looks to me like we might need a `is_feed` check on the lazy images component to make sure we do not replace images with the `1x1` gif on feeds.

**Comment by Volnus** [comment]
I would like to add, that there is currently an is_feed check already for the lazy images. additionally, when attempting to add a various plugin like RSS with Images https://wordpress.org/plugins/rss-with-images / the images were added to the feed with the correct url and were not lazy loaded.  

How are you adding images to the RSS feed, and how are you subscribing to them.

**Comment by scottsweb** [comment]
I think you could be right that this is the reader I am using actually. I believe it is fetching the original post when a site is not providing a full feed. This is causing it to grab lazy images. 

Will close the issue.
