### ISSUE TITLE
Publicize: Length of Cyrillic characters fails Facebook Publicize action

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/jetpack#9898]
**Steps to reproduce**: Follow the steps below to reproduce the issue. 

- Connect Facebook profile to your site using Jetpack's Publicize
- Compose a post with Cyrillic characters in it
- Publish the post with a considerate amount of Cyrillic characters in the post content. Publicize to Facebook as well during this process

**What is expected:** Post is published to Facebook as well

**What happens instead:** Facebook Publicize action fails, and the post is not published to Facebook.

Internal logs show `Error 400 ((#100) Properties cannot be greater than 10240 after JSON serialization.)`

Interestingly this does not fail when the post content has limited use of Cyrillic characters.

**Comment by arunsathiya** [comment]
#1266095-zen

Slack discussion: p1531158184000340-jpop-support-slack

**Comment by rossanafmenezes** [comment]
User came back asking for an update and mentioned this:

> I just recalled it was about week ago, maybe more, my post wasn't shared as usual, but I was trying to upload location and after few attempts to upload location my post was shared. Maybe it helps your team to solve that issue. I mean not sharing my posts.

Not sure if it's relevant or not to the issue.

**Comment by jeherve** [comment]
Related:

354-gh-io
653-gh-io
#1656
https://github.com/Automattic/wp-calypso/issues/4150

(Character/word counting in non-English languages can be tricky)

**Comment by jeherve** [comment]
Closing this as this is not valid anymore, since we do not publish to Facebook Profiles anymore, and we do not attempt to post content excerpts to Facebook Pages.
