### ISSUE TITLE
Contact form: use namespacing in custom post type to avoid conflicts

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#99]
Themes and/or plugins may register duplicate CPTs, which could cause conflicts with CPTs registered by Jetpack. This can be avoided by using namespacing in CPTs registered in Jetpack.

For example, rather than `feedbacks`, the custom post type should be `jetpack_feedbacks`.

**Comment by dereksmart** [comment]
the back-compat of this sounds like a nightmare, especially thinking about how it needs to be ported back over to dotcom.
