### ISSUE TITLE
Ensure user wpcom connections are unique

### ISSUE THREAD

**Issue by blobaugh** [Automattic/jetpack#991]
Currently it is possible to connect multiple wporg users to a single wpcom account for SSO. This causes issues when attempting to later login to the wporg site via SSO. Which account should be used? 

When linking a wporg account to wpcom Jetpack should check to ensure the wpcom user is not already linked to another user on the wporg site.

**Comment by ebinnion** [comment]
We now use the regular WP.com connection, so I'm going to close this issue.
