### ISSUE TITLE
Lazy Images: WooCommerce shopping cart images disappear when quantity changed

### ISSUE THREAD

**Issue by joendotcom** [Automattic/jetpack#9914]
## Summary

WooCommerce shopping cart images disappear when quantity changed

## Steps to Reproduce

1. Go to site https://dev.natureetpartage.fr/
2. Add an item to shopping cart (panier)
3. Go to shopping cart
4. Change quantity of item
5. Update cart

### Expected Result

- Quantity is updated

### Actual Result

- Quantity is updated, but images also disappear.

#### Screencast

Upload failed, here's a link: https://cloudup.com/i1ZuSDUs3oG

## Site info

- Site URL: https://dev.natureetpartage.fr/ (production site does not have Lazy Images enabled)
- Plan: Free
- Jetpack Debug URL: https://jetpack.com/support/debug/?url=https://dev.natureetpartage.fr/
- Ticket ID: 1258006-zen
- Host: OVH

**Comment by zinigor** [comment]
This happens because we can not know when images appear on the page. In order to fix the problem the author of the theme will need to trigger an additional event on card refresh. You can see that if you run this in the console, images appear:

``` jQuery( 'body' ).trigger( 'jetpack-lazy-images-load' ); ```

This is thanks to Eric's new event listener that was added in 6.3. Do you know if the user has any control over the site's cart refresh code?

**Comment by benoitfouc** [comment]
Hi, i'm the concerned user. Thanks for the reply and thanks joendotcom for the bug report.
I've a full access of my website files, but i don't know where realy is located the cart refresh code. In WooCommerce i think ? Or in Salient theme.

**Comment by zinigor** [comment]
@benoitfouc I have added a PR that should fix this problem, but you can use any plugin that lets you add code snippets and have this be added to your WordPress site:

```
add_action( 'wp_enqueue_scripts', function() {
	if ( ! wp_script_is( 'jquery', 'done' ) ) {
		wp_enqueue_script( 'jquery' );
	}
    wp_add_inline_script( 'jquery-migrate', "
		jOuery( 'body' ).bind( 'wc_fragments_refreshed', function() {
			jQuery( 'body' ).trigger( 'jetpack-lazy-images-load' );
		} );
	" );
} );
```
