### ISSUE TITLE
geo-location causes an RSS error 

### ISSUE THREAD

**Issue by nicoulina** [Automattic/jetpack#9924]
#### Steps to reproduce the issue

1. Installing an other geolocation plugin that already defines namespace 'georss' for example geomashup
2. (same topic issue #9885)
3.

#### What I expected
Do not redefine namespace georss if an other plugin does it

#### What happened instead
rss error duplicate namespace georss line 8

My solution in the meantime : I noted in the code the definition of namespace like this
public function register_rss_hooks() {
		/*add_action( 'rss2_ns', array( $this, 'rss_namespace' ) );*/
		/*add_action( 'atom_ns', array( $this, 'rss_namespace' ) );*/
		/*add_action( 'rdf_ns', array( $this, 'rss_namespace' ) );*/

**Comment by zinigor** [comment]
Thank you, this does look like the same bug that's already reported in #9885. Let's continue the discussion there.
