### ISSUE TITLE
VideoPress: fullscreen button doesn't work on small screens

### ISSUE THREAD

**Issue by lancewillett** [Automattic/jetpack#9942]
#### Steps to reproduce the issue

1. Load a post or page with a VideoPress on it with a tablet, such as Apple iPad
2. Play the video
3. Try to go fullscreen by clicking the icon in the player controls (bottom right usually)

#### What I expected

I expected the player to go fullscreen.

#### What happened instead

The icon state changes, but the player stays the same size.

#### Video / Screenshot

Live test here: https://lancetest35.com/2018/07/23/video-test/

I tested with iPhone 8 / Mobile Safari as well, and the same bug exists there.

**Comment by lancewillett** [comment]
Testing with iPhone 8, pressing the "Enable Fullscreen Mode" button changes the icon text but doesn't make the video player go fullscreen:

<img src="https://user-images.githubusercontent.com/66797/43107081-45bba118-8e90-11e8-97e4-eb8b66a81f7d.png" width="480" />

<img src="https://user-images.githubusercontent.com/66797/43107082-45d22348-8e90-11e8-948e-6d03385f6879.png" width="480" />

**Comment by jeherve** [comment]
This may be an issue with the video player itself; do you experience similar issues when you deactivate Jetpack and embed videos using oEmbed, by adding the video URL on its own line, like so?

`https://videopress.com/v/aViYGiK2`

If so, it may be best for us to log this in the player's repo instead.

Thank you!
