### ISSUE TITLE
Lazy Load Breaks Featured Category Slider Widget on Colormag Theme

### ISSUE THREAD

**Issue by jesscga** [Automattic/jetpack#9946]
Enabling Lazy Loading for Images causes malfunction on the Featured Category Slider widget that's built into the ColorMag theme by ThemeGrill

https://themegrill.com/themes/colormag/

#### Steps to reproduce the issue

1. Install ColorMag theme
2. Create posts with category and featured images
3. Add Featured Category Slider widget to Front Page: Slider Area widget area

#### What I expected

Slider appears in its expected widget area, showing featured images and category/post title, sliding to next post at regular intervals

#### What happened instead

Slider appears with expected content, but with large space beneath. When next slide comes in, the text momentarily appears in the space beneath where it should be, then jumps into place.

Issue seems to resolve after first full cycle of all slides - space disappears, and slider behaves as expected

Screencast: http://cld.wthms.co/phU6ug

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
