### ISSUE TITLE
Changing domain names and not breaking Photon URLs

### ISSUE THREAD

**Issue by gordo019** [Automattic/jetpack#9950]
I recently purchased a new domain name and would like to move my current WP site to the new domain name, terminating my old domain name. I will do the necessary changes within CPanel, but I wanted to confirm the process of changing domain names relating to Jetpack’s Photon. I don’t want to break numerous links to my photos on Photon’s CDN servers. Researching this here at Github, I find this simple (2014) solution: "To fix this, you need to disconnect JetPack and reconnect it on the new domain.” Is this true and is this the current recommended method of making a domain name change with Jetpack/Photon? Could someone at Jetpack please confirm this?

**Comment by gordo019** [comment]
Or maybe reconnect/connect at..... Jetpack> Dashboard>Connections>Manage Site connection?

**Comment by gordo019** [comment]
Where do I replace the domain name and add the new domain name?

**Comment by zinigor** [comment]
Hello, thanks for contacting us about this!

Yes, you're right, you don't have to change anything, only disconnect and reconnect your Jetpack installation using the new domain name. Photon will automatically create new cached versions of images from your new domain as if it was a new site.

You can even migrate all of your Jetpack settings to the new domain if you follow the procedure detailed here:
https://jetpack.com/support/safe-mode/#what-is-an-identity-crisis

You need to go the "Confirm Safe Mode" -> "Migrate Stats & Subscribers" route in your case. If you need help, please contact support about that.

Hope that helps!
