### ISSUE TITLE
Reader Integration: Add ids to RSS feed

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#996]
Per @blowery, it would be helpful for the WordPress.com Reader if feeds from Jetpack sites included the blog ID as metadata in the feed to confirm that site is a Jetpack site.

This would aid the Reader to understand if any of the WP.com data can be trusted or used for hints or if a site was previously a JP site, now no longer.

**Comment by kraftbj** [comment]
I'm going to take this on, aiming for 4.2.

**Comment by sdellis** [comment]
@blowery wrote this, but it doesn't seem like anyone took him up on the advice:
> The namespace here is something I just made up, so feel free to use something more sane.

The way the namespace is defined makes it the default namespace and can break parsers (as was my  case with a Drupal module recently).  Can this namespace be defined with a proper prefix?  Something like: 
`xmlns:automattic="com-wordpress:feed-additions:1"`

**Comment by kraftbj** [comment]
@sdellis I admit I know not nearly enough about XML Namespacing. Opened a new issue at https://github.com/Automattic/jetpack/issues/5219 for this.

**Comment by blowery** [comment]
> The way the namespace is defined makes it the default namespace and can break parsers (as was my case with a Drupal module recently).

Why do you say that? An `xmlns` declaration only applies to the declaring element and that element's descendants. In our case, there are no descendants, so the namespace only applies to the site and post-id elements, not any other elements in the feed. If an xml parser is applying it as the default namespace up the element tree, that parser is in violation of the xml + namespaces spec... 

Unless I'm missing something? Do you have an example showing how it broke something?

**Comment by sdellis** [comment]
My apologies.  You are correct, @blowery, and this seems like a bug in the way the Drupal [Feeds XPath Parser module](https://www.drupal.org/project/feeds_xpathparser) determines default namespaces.  Here's [an example](http://cgit.drupalcode.org/feeds_xpathparser/tree/FeedsXPathParserDOMXPath.inc#n167) of where it's falling down in that module.  Feel free to close #5219 @kraftbj.  I will report the bug over there.  Sorry for the false alarm, and thanks for your feedback!

**Comment by blowery** [comment]
@sdellis no worries! For a bit there I was really quite worried. It'd been a while since I read the XML 1.1 spec. 

:D

**Comment by phubner** [comment]
I know that this was has been rolled into the release already, but this change appears to make the mailchimp rss feed parser unhappy. Is there a way to disable this addition to the RSS feed without having to roll my own feed? The error MC support has pointed me to is the one reported in #35589 . While Google News parser seems better at handling slight errors, the MC one seems a bit less resilient.

**Comment by scripting** [comment]
BTW, in 2025 this is still a very useful feature -- we use it in our WordLand editor to know whether a post is something the reader can edit, and if so, we place an edit icon on it when the user is viewing it.

Also, while it is probably a fully legal way to use a namespace, it is unusual, and thus it's plausible that it might break some software that reads feeds. At some point it would probably be good to come up with a name for the namespace and have it map to a URL where the docs for the elements of the namespace are explained, and include it at the top of the feed as you do with all the other namespaces you use. 

After RSS 2.0 was frozen, I started a namespace of my own, the [Source namespace](https://source.scripting.com/), and used it as a place to document all the items I wanted to add later. I've been doing it this way for quite a few years! :-)
