### ISSUE TITLE
Subscriptions: "...sending email to subscribers" message when blog subscriptions are disabled

### ISSUE THREAD

**Issue by davewarfel** [Automattic/jetpack#9964]
#### Steps to reproduce the issue

1. Go to Jetpack > Discussion
2. Scroll down to Subscriptions
3. Enable the first option, "Allow users..."
4. Disable the "Show a follow blog..."
5. Enable the "Show a follow comments..."

<img width="823" alt="jetpack-subscriptions-follow-comments-enabled" src="https://user-images.githubusercontent.com/783021/43409361-efbb1f4a-93e0-11e8-8079-421377af4fc2.png">

#### What I expected

When publishing a post, I expected a typical "Post published. View Post." message to appear at the top of the screen.

#### What happened instead

I saw this:
![jetpack-post-published-sending-email-to-subscribers](https://user-images.githubusercontent.com/783021/43409334-e5e98c68-93e0-11e8-9187-c45143234548.jpg)

> "Post published and sending emails to subscribers. View post"

Could you only show that message if the "Show a follow blog..." option is enabled? It just doesn't make sense to see that message when I'm only allowing users to follow comments.

**Comment by brbrr** [comment]
Hi there,

Actually, to disable blog subscription, you need to disable "Allow users to subscribe to your posts and comments *and receive notifications via email*" option. Other two options just add links to subscribe to a blog or a specific comment. 

I'm closing it, for now, If you think it is something that should be fixed - feel free to reopen the issue.

**Comment by davewarfel** [comment]
Hi Yaroslav,

I appreciate the quick response. However, I still think something is off. It's just the language that is used so it's not a huge deal, but it could definitely confuse some people.

If I disable the "Allow users to subscribe to your posts and comments and receive notifications via email" option, then neither of the sub-options work. I still want to add the checkbox to my comment form so people can subscribe to receive **comment updates**, but no one can subscribe to **blog updates**. And since no one is subscribed to blog updates, when I see the message, "Post published and sending emails to subscribers," it just doesn't make sense.
