### ISSUE TITLE
Likes: Disabling Like buttons via Calypso for individual pages leaves the Likes enabled via WP-Admin

### ISSUE THREAD

**Issue by cecoates** [Automattic/jetpack#9975]
#### Steps to reproduce the issue

1. Open a page in Calypso that has Likes enabled.

2. Uncheck the Likes box under the Sharing tab.

![screen shot 2018-08-01 at 18 10 13](https://user-images.githubusercontent.com/10121835/43554299-3f9660cc-95b9-11e8-8b33-915c703fe001.png)

3. Click "Update".

4. View the page. Likes are still present.

![screen shot 2018-08-01 at 18 11 20](https://user-images.githubusercontent.com/10121835/43554322-50cbcf62-95b9-11e8-911a-618cc241cbd9.png)

They can, however, be disabled via WP-Admin.

1. Open a page in WP-Admin that has Likes enabled. Even the same one you tested above.

![screen shot 2018-08-01 at 18 09 57](https://user-images.githubusercontent.com/10121835/43554283-2fad99c8-95b9-11e8-9dea-58aef9b9e71f.png)

2. Uncheck the Likes box under the Sharing options.

![screen shot 2018-08-01 at 18 11 51](https://user-images.githubusercontent.com/10121835/43554392-aa88066a-95b9-11e8-8715-b31ad829a601.png)

3. Click "Update".

4. View the page. Likes are now gone.

![screen shot 2018-08-01 at 18 11 39](https://user-images.githubusercontent.com/10121835/43554405-bd423b4a-95b9-11e8-9822-f7653ce09c94.png)

In the above example I was using Gutenberg in WP-Admin, but it works with the Classic WP-Admin as well.

Tested on my own demo site https://8bitchromeporpoise.blog/ and user's site: https://irismingle.com/

#### What I expected
For the Likes to no longer appear on the page they were disabled for.

#### What happened instead
Likes still display as if no change were made.

**Comment by abidhahmed** [comment]
Thanks for the detailed report! I can confirm that disabling/enabling `Likes` under Calypso for an individual page/post does not make any difference when compared with WP-Admin.

However, disabling `Likes` globally by unchecking `Show like button` under `Calypso -> Sharing -> Sharing Buttons` does work as expected. 

We'll take a look into this issue and update when possible, thanks again.

**Comment by jeherve** [comment]
Closing as we are moving away from this editor and will soon introduce Sharing and Likes settings inside the block editor instead.
