### ISSUE TITLE
SEO Tools: Editors can not save posts on Calypso if another SEO plugin is active

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#9979]
#### Steps to reproduce the issue

1. Activate SEO Tools for a Premium or Pro site. 
2. Install a SEO plugin like Yoast SEO or All In One SEO Pack
3. Log in and manage the site on WordPress.com.
4. Edit a post on WordPress.com, e.g: https://wordpress.com/post/my-site.com/584
5. Add some words to "Meta Description". 

#### What I expected

"SEO Description" should not display at first. 

#### What happened instead

1. Editors click "Update".
2. The user sees this "Saving of draft failed." - screenshot below. 

#### A couple of notes. 

1. If I am the connection owner, I do not see "SEO Description" fields in Calypso. 
2. In Network tab of the browser console, there is a message like this, which is pretty misleading HEs in finding out the real cause. 

```
Link: https://public-api.wordpress.com/rest/v1.2/sites/132097576/posts/584?http_envelope=1&context=edit
{"code":403,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"unauthorized","message":"SEO tools are not enabled for this site."}}
```

#### Screenshot

![image](https://user-images.githubusercontent.com/10045087/43628546-cc0d3a96-9724-11e8-973e-98fc04748323.png)

**Comment by htdat** [comment]
I am posting here instead of wp-calypso repo because this issue happens for Jetpack sites only.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
