### ISSUE TITLE
WordPress.com Toolbar: Fix extra left padding for headers in Dashboard > Home.

### ISSUE THREAD

**Issue by kjellr** [Automattic/jetpack#9981]
Enabling the WordPress.com toolbar adds extra left margins to many headers in `Dashboard > Home` on small screens. 

#### Steps to reproduce the issue

1. Enable `Jetpack > Settings > Enable the WordPress.com Toolbar`
2. Visit `Dashboard > Home` 
3. Make your screen size smaller than 480px

#### What I expected

Headers to be properly aligned. 

#### What happened instead

Headers were not properly aligned:

![test](https://user-images.githubusercontent.com/1202812/43656205-8fa00b4c-971f-11e8-9395-ed504609f38f.png)

_Seen with WordPress 4.9.8, Jetpack 6.3.3_

**Comment by torres126** [comment]
The issue appears to be with `.wp-admin .wrap h2 { 
padding-left: 50px;
}` being added on mobile. 

That could be resolved with `.wp-admin .wrap h2 :not(.welcome-panel) { 
padding-left: 50px;
}`

But the issue is that I have no clue where those styles come from.

**Comment by samiff** [comment]
It appears this issue has been resolved, closing 🧹
