### ISSUE TITLE
Missing: ShortURL Button for wp.me tiny urls

### ISSUE THREAD

**Issue by TakaakiTono** [Automattic/jetpack#9987]
Short URL “wp.me” Button is missing. In WordPress classic editor that “Get Short URL” button is right there beside Permalink field. But there is no way to get that in the current version of Gutenberg v3.4.0

**Comment by brbrr** [comment]
Hi @TakaakiTono,

Could you please follow an issue template([ISSUE_TEMPLATE.md](https://github.com/Automattic/jetpack/blob/master/.github/ISSUE_TEMPLATE.md)) and include steps to reproduce, what you expect and what's happened instead? This will help to understand & reproduce your problem. Thanks!

**Comment by htdat** [comment]
Closing. We have a more detailed report on https://github.com/Automattic/jetpack/issues/10925
