### ISSUE TITLE
Widgets: Top Posts and Pages - improved copy suggestion

### ISSUE THREAD

**Issue by coder-karen** [Automattic/jetpack#9995]
The displayed message when the Top Posts and Pages Widget is active on a site can appear confusing.

When logged in as a user to a site, the message that displays when there are posts that haven't had any traffic is 'There are no posts to display. Want more traffic?'.

![noposts](https://user-images.githubusercontent.com/16754605/43799090-6d02b9d2-9a84-11e8-8327-19db387d7e26.PNG)

An expected message would have been more along the lines of 'There are no posts that have received any traffic'.

The text is exactly the same when only Pages have been enabled, when it should say 'There are no pages to display' (thanks to @arunsathiya for reporting this).

<img width="387" alt="tppwidgetadmin" src="https://user-images.githubusercontent.com/16754605/43799532-b450071c-9a85-11e8-9115-a470776b43f5.png" width="50%">

These are some suggestions for a future Jetpack release.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
