### ISSUE TITLE
General: Remove duplicate rel tags and PR cleanup

### ISSUE THREAD

**Issue by abidhahmed** [Automattic/jetpack#9999]
We need to go back and scan for changes in PR (#9644) that may have introduced duplicate `rel` tags. One of it that's part of sharing links has been merged as part of #9992

We also need to cleanup the remaining PRs from the same author which haven't been merged yet:
#9641 
#9642
#9643
#9645

**Comment by jeherve** [comment]
Looks like there were only a few links to fix. I took care of it in #10121
